### PR TITLE
Parse comma-separated list of numbers as URL filter params

### LINKED ISSUE #25374: Comma separated filter value would not hand over from dashboard to question
**Describe the bug**
Comma separated filter value would not hand over from dashboard to question

**Logs**

**To Reproduce**
1. Create Dashboard with default value of comma separated multiple values
2. Open dashboard
3. Click question title which uses 1's default value
4. Only top 1 value will be taken over. Rest of them will be omitted.

**Expected behavior**
All of separated values will be taken over.

**Screenshots**
MicrosoftTeams-image (1)

**Information about your Metabase Installation:**
Docker image metabase/metabase:v0.44.2

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 105.0.5195.102, Firefox 104.0.2
- Your operating system: Windows 10 Enterprise 21H2(Client)
- Your databases: MySQL
- Metabase version: v.0.44.2
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
Customers' use case always starts with this dashboard and they move to each questions and export CSVs. Unless values taken over properly, their business flow will be stopped.

**Additional context**
On v.0.41.5, it doesn't happen.

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #25374 

### How to test

1. Create question: Native › Sample dataset › `select count(*) from orders where id in ({{number}})`
2. Set variable type as "Number" for variable "number".
3. Save
4. In the question url, add get params `?number=1%2C2%2C3` or `?number=1,2,3`

Filter should display: `1,2,3`
URL should show URL-encoded params, looking like `?number=1%2C2%2C3` 

Visualization count should show: `3`
🎗️There are other reproductions you can try in issue https://github.com/metabase/metabase/issues/25374. Worthwhile testing them too.

### CODE REVIEW

File: frontend/src/metabase/parameters/utils/parameter-values.js [hunk 1]
```diff
@@ -29,12 +29,29 @@ export function parseParameterValue(value, parameter) {
 
   const type = getParameterType(parameter);
   if (type === "number") {
-    return parseFloat(value);
```
Comment (gusaiani) [inline frontend/src/metabase/parameters/utils/parameter-values.js:32]: Value was treated as a single integer even if it was a series of integers.

File: frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js [hunk 2]
```diff
@@ -186,6 +186,23 @@ describe("parameters/utils/parameter-values", () => {
...
+      const numberParameter = {
+        id: 111,
+        slug: "numberParameter",
+        type: "number/=",
+      };
+      expect(
+        getParameterValueFromQueryParams(
+          numberParameter,
+          {
+            [numberParameter.slug]: "1, 2,   3",
```
Comment (nemanjaglumac) [inline frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js:199]: There's really no difference between `  2` and `     3`. If you handle spaces in front of a number, this type of test should not give you any more certainty.

It's better to check for both spaces before and after the number. E.g:
`1,2   ,      3`

**Comment by nemanjaglumac** [comment]
I don't fully understand what's going on because there seems to be some kind of a disconnect.
You fixed the literal parsing of the URL queryParams. At the same time, it's not possible to enter those same values in the filterWidget without triggering an error.

If we assume that the saved question from your example has an id `42` **and** the question name is `foo`, then try this scenario:

1. visit `/question/42-foo?number=1,   2,3` (or ascii `?number=1%2C%20%20%202%2C3`
    - it works correctly and the values get normalized to `1,2,3`
    - the result in the query is 3, as expected
2. visit `/question/42-foo`, then try to enter the same sequence of numbers in the filter widget `1,   2,3`
    - the query fails for the `Unparseable number: " 2"`
    - the url query params will correctly show `?number=1%2C%20%20%202%2C3`, nevertheless
        - the weird part is that if you click on the url and hit enter, it will behave as in the scenario 1 and will normalize the value

image

p.s. Let me know if Loom video is easier to follow and I'll create one.

File: frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js (hunk 2 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js:199]: Other scenarios that we're not testing:

1. `,,,` returns `Nan`
2. ` ` returns `Nan` 
3. `1,,2,3,4` returns `1` (drops everything after the comma)
4. `1, ,2,3,4` returns `1` (drops everything after the space)
5. `1,2,3,` (trailing comma) returns `1`
6. `1,0,000,2` returns `1,0,0,2` (correct)
7. `0,000,1,2` returns `0,0,1,2` (correct)


There's probably more, but this is just from the top of my head.

Comment (gusaiani) [reply frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js]: @nemanjaglumac Thanks, added these cases.

File: frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js [hunk 3]
```diff
@@ -363,6 +346,52 @@ describe("parameters/utils/parameter-values", () => {
...
     });
+
+    describe("for number filter type", () => {
+      const numberParameter = {
+        id: 111,
+        slug: "numberParameter",
+        type: "number/=",
+      };
+
+      const runGetParameterValueFromQueryParams = value =>
```
Comment (gusaiani) [inline frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js:357]: Created this function to prevent mind-numbing repetition below.

Would be in favor of a shorter name for this function.

**Comment by gusaiani** [comment]
> I don't fully understand what's going on because there seems to be some kind of a disconnect.

@nemanjaglumac,
your perception is correct.

**Context:**
The URL feeds the input on a page load. After that, the input is king.

As I fixed what happens on page load, from the URL, I made this a tiny bit more user-error-tolerant.
It did become more tolerant than the filter input used by itself, and passes treated value down to the input, but only on page load.

I suppose if we want to invest in making the filter input more tolerant, we can do that in a separate PR.

The latest major version where the issue fixed here works at all is 41.
Even there, the input is no more error-tolerant that it is here, so there seems to be no regression in that regard.

File: frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js (hunk 2 above)
Comment (gusaiani) [reply frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js]: There's no end to potential cases here.

I had trouble falling asleep (took me 3 instead of the usual 1 minute) last night thinking about how, in my native language, the american dot notation for decimals is actually comma notation. And so on and so forth.

For psychiatric prevention reasons, it may be worth mentioning that a run of the question will quickly tell the user if the filter is filled with invalid parameters.

File: frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js [hunk 4]
```diff
@@ -380,6 +346,52 @@ describe("parameters/utils/parameter-values", () => {
...
+      });
+
+      describe("when parsing parameter value that is a comma-separated list of numbers", () => {
+        it("should return list when every item is a number", () => {
+          expect(runGetParameterValueFromQueryParams("1, 2 ,   3")).toEqual([
+            "1,2,3",
+          ]);
+          expect(runGetParameterValueFromQueryParams("1,2.5,3.4")).toEqual([
+            "1,2.5,3.4",
+          ]);
```
Comment (nemanjaglumac) [inline frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js:379]: Great that you included floats 👏

File: frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js [hunk 5]
```diff
@@ -380,6 +346,52 @@ describe("parameters/utils/parameter-values", () => {
...
+        });
+
+        it("should return first float or NaN when list is not formatted properly", () => {
+          expect(runGetParameterValueFromQueryParams("1,,2,3,4")).toEqual([1]);
+          expect(runGetParameterValueFromQueryParams("1, ,2,3,4")).toEqual([1]);
+          expect(runGetParameterValueFromQueryParams("1,2,3,")).toEqual([1]);
+          expect(runGetParameterValueFromQueryParams(",,,")).toEqual([NaN]);
+          expect(runGetParameterValueFromQueryParams(" ")).toEqual([NaN]);
+          expect(runGetParameterValueFromQueryParams(",1,2,3")).toEqual([NaN]);
+        });
```
Comment (nemanjaglumac) [inline frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js:392]: Not sure we understood each other...
Most of the test cases I wrote in the comment were not expected. They were rather some edge cases that your parsing function does not cover.

I don't think we should ever return `NaN`, because it's then displayed in the filter widget. if there's no value (`" "`, `",,,"`), we should treat it as if no value has been passed from the query params.

If we have leading or trailing comma, there's no reason we shouldn't omit it (handle users' input mistake) and still parse the result.

Comment (nemanjaglumac) [inline frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js:392]: Not sure we understood each other...
Most of the test cases I wrote in the comment were not expected. They were rather some edge cases that your parsing function does not cover.

I don't think we should ever return `NaN`, because it's then displayed in the filter widget. if there's no value (`" "`, `",,,"`), we should treat it as if no value has been passed from the query params.

If we have leading or trailing comma, there's no reason we shouldn't omit it (handle users' input mistake) and still parse the result.

**Review by nemanjaglumac — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js (hunk 5 above)
Comment (gusaiani) [reply frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js]: @nemanjaglumac Thank you, I've updated the implementation to handle the cases you mention 👍

**Comment by iethree** [comment]
This looks good to me. It's a small improvement to a pretty niche use-case. @nemanjaglumac is right that our component here should be smarter, but that is a bigger task that likely involves a significant refactor.

**Review by iethree — APPROVED** [review]
⭐

File: frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js [hunk 6]
```diff
@@ -363,6 +346,55 @@ describe("parameters/utils/parameter-values", () => {
...
+          expect(runGetParameterValueFromQueryParams(",,,")).toEqual([
+            undefined,
+          ]);
+          expect(runGetParameterValueFromQueryParams(" ")).toEqual([undefined]);
+        });
+
+        it("should return first parseable float if value includes non-numeric characters", () => {
+          expect(runGetParameterValueFromQueryParams("1,a,3,")).toEqual([1]);
+          expect(runGetParameterValueFromQueryParams("1a,b,3,")).toEqual([1]);
+        });
```
Comment (nemanjaglumac) [inline frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js:395]: Note that this test might change if we ever address https://github.com/metabase/metabase/issues/15295

**Review by nemanjaglumac — APPROVED** [review]
Thank you for expanding the test suite.
