### PR TITLE
Fix past1hours and past1seconds filters

### LINKED ISSUE #57767: Metabase Date variable calculates wrong values when selecting "previous X hours"
### Describe the bug

**TLDR: The "Date" filter provides wrong values in the SQL when selecting "previous 1 hour" - the time window is only 1 minute long instead of 1 hour and the time zones are wrong**

(I also posted this in [Metabases's Discourse](https://discourse.metabase.com/t/metabase-date-variable-calculates-wrong-values-when-selecting-previous-x-hours/233898). I'm unsure whether here or there is a more proper place to discuss this)

## Current situation

I have a query with a Field FIlter that is connected to a Postgres `timestamptz` column.
When selecting a query value of "Previous 1 hour", the resulting SQL is wrong.

Example: 
My Metabase's time zone setting is set to Asia/Jerusalem (GMT+3).
Is is currently 11:40 AM in this time zone.
I have a query that has a Date filter, set to "previous hour".

The resulting SQL Metabase produces is:
```
...
  column_name >= timestamp with time zone '2025-05-09 07:00:00.000 +03:00'
  AND column_name < timestamp with time zone '2025-05-09 07:01:00.000 +03:00'
...
```

There are 2 issues with this:
1. The resulting time window is only 1 minute long instead of 1 hour
2. The time zone calculation is wrong

## Deep dive details
These are pictures of the query I'm making and the resulting values:
Image
Image

Here's the full resulting query:
Image

Metabase version: 0.54.6 (latest)

### To Reproduce

1. Configure Metabase instance to have some non UTC time zone
2. Create query with Date filter
3. Choose value of "previous hour"
4. Look at resulting query

### Expected behavior

It should be one of the following two options:
Option 1:
```
  column_name >= timestamp with time zone '2025-05-09 07:00:00.000Z'
  AND column_name < timestamp with time zone '2025-05-09 08:00:00.000Z'
```
Option 2:
```
  column_name >= timestamp with time zone '2025-05-09 10:00:00.000 +03:00'
  AND column_name < timestamp with time zone '2025-05-09 11:00:00.000 +03:00'
```

1. The difference between is `>=` and the `<` conditions is 1 hour and not 1 minute
2. Either have a Zulu time zone and UTC time values or local time values and timezone offset, but not the original: UTC time values with timezone offset

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-05-06",
      "tag": "v0.54.6",
      "hash": "d56bf23"
    },
    "settings": {
      "report-timezone": "Asia/Jerusalem"
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "6.8.0-1023-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

High - the results are extremely wrong due to the 1min instead of 1hour window

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by metamben**
Fixes #57767 

### Description

This is a minimal change to make sure past1hours and past1seconds filters generate 1 hour and 1 second intervals respectively.

These filters are problematic, because they "bucket" to minute unit and complicated, because we >= for the "After" filters although we want them to mean strictly after. These problems will be solved as a properly planned feature, not as a bugfix (see the [slack conversation](https://metaboat.slack.com/archives/C0645JP1W81/p1747150935283919?thread_ts=1747146990.283349&cid=C0645JP1W81)).

### How to verify

Repeat the reproduction steps from #57767 and check that the generated query filters a one hour period, not a one minute one.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/driver/common/parameters/dates.clj [hunk 1]
```diff
@@ -434,6 +434,20 @@
       (m/update-existing :end u.date/format)
       (dissoc :unit)))
 
+(defn- date-string->raw-range
```
Comment (metamben) [inline src/metabase/driver/common/parameters/dates.clj:437]: Extracted from the function below.

File: src/metabase/driver/common/parameters/dates.clj [hunk 2]
```diff
@@ -398,7 +398,7 @@
 
 (mu/defn- adjust-inclusive-range-if-needed :- [:maybe TemporalRange]
   "Make an inclusive date range exclusive as needed."
-  [{:keys [inclusive-start? inclusive-end?]} temporal-range :- [:maybe TemporalRange]]
+  [temporal-range :- [:maybe TemporalRange] {:keys [inclusive-start? inclusive-end?]}]
```
Comment (metamben) [inline src/metabase/driver/common/parameters/dates.clj:401]: Options usually come last.

File: src/metabase/driver/common/parameters/dates.clj [hunk 3]
```diff
@@ -539,14 +541,16 @@
...
+        [range-raw unit] (try (let [r (date-string->raw-range raw-date-str)]
+                                [(format-date-range r) (:unit r)])
+                              (catch Throwable _
+                                [(fallback-raw-range raw-date-str) :day]))
         date-str-conversion (if (isa? field-type :type/DateTimeWithTZ)
                               date-str->qp-aware-offset-dt
                               date-str->local-dt)]
     (-> (update-vals range-raw date-str-conversion)
-        (m/update-existing :end exclusive-datetime-range-end (date-str->unit-fn (:end range-raw)))
+        (m/update-existing :end exclusive-datetime-range-end (or ({:second t/seconds, :hour t/hours} unit)
```
Comment (metamben) [inline src/metabase/driver/common/parameters/dates.clj:552]: Only seconds and hours have the reported bug, and from the problem with seconds cannot be triggered from the FE, but I handle it for completeness.

File: test/metabase/driver/sql/parameters/substitute_test.clj [hunk 4]
```diff
@@ -951,6 +951,43 @@
...
+(deftest e2e-relative-datetime-test
+  (mt/with-clock (t/mock-clock #t "2016-06-07T12:00-00:00" (t/zone-id "UTC"))
+    (mt/test-drivers (sql-parameters-engines)
+      (testing "generate valid closed-open interval for timestamp field (##57767)"
+        (doseq [{:keys [unit value expected-duration]}
+                [{:unit "seconds",  :value 1, :expected-duration "PT1S"}
+                 {:unit "seconds",  :value 3, :expected-duration "PT3S"}
+                 {:unit "minutes",  :value 1, :expected-duration "PT1M"}
+                 {:unit "minutes",  :value 3, :expected-duration "PT3M"}
+                 {:unit "hours",    :value 1, :expected-duration "PT1H"}
```
Comment (metamben) [inline test/metabase/driver/sql/parameters/substitute_test.clj:963]: This is the important case.

**Review by lbrdnk — APPROVED** [review]
