### PR TITLE
Fixup of Erroring Questions page

### LINKED ISSUE #59697: Settings > Tools is broken: cannot click or interact with the page
### Describe the bug

The page in settings that lists broken queries is broken and not interactable
In this screenshot there are no console errors, but clicking the row does nothing
Image

### To Reproduce

1. create a native sql question that won't work: `select bad from table`. save it
2. run the question
3. Admin > tools and see this question in the list
4. attempt to click it.
5. Nothing happens

Also note that there is a "Rerun selected" button which doesn't seem to connect to an obvious purpose you would want to do here. (on inspecting network tab, we are using mbql queries to generate this list, and that button i think reruns the query)

### Expected behavior

link to questions? or remove the pointer behavior? feels in a weird spot of not doing anything but indicating it does do something

### Logs

_No response_

### Information about your Metabase installation

```JSON
55.3, master
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/59697

### Description
Re-implements the ability to select questions and re-run them from this page, as well as navigate to them when selecting the row

### How to verify
1. Have a question that is erroring (native question that points to an invalid table will do the trick
2. Go to Admin -> Tools -> Erroring questions
3. you should see your question in the table.
4. Click the row your question is on. You should be brought to the question page
5. Fix the question, re-run, and return to Erroring Questions
6. The question should no longer be there
7. You can also re-run the question from the page if you believe it was a timeout

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx [hunk 1]
```diff
@@ -862,6 +866,10 @@ class Visualization extends PureComponent<
                     isRawTable={isRawTable}
                     isQueryBuilder={!!isQueryBuilder}
                     isSettings={!!isSettings}
+                    isSelectable={isSelectable}
+                    rowChecked={rowChecked}
+                    onAllSelectClick={onAllSelectClick}
+                    onRowSelectClick={onRowSelectClick}
```
Comment (iethree) [inline frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx]: I \*\***hate\*\*** that this uses a visualization for admin functionality (obviously, not your fault).

😭  can we at least comment these props so we know they're only used by the erroring question viz? This way we might have a small hope of removing them if/when we rework this to work with a "normal" table.

**Review by iethree — APPROVED** [review]
Approving this because it's a clear improvement over the existing broken state of this page, but using visualizations for admin controls feels so bad. 

This is yet another case where having a nice reusable virtualized table component would make reworking this quick + nice + easy.

Made an issue to help me feel better: [UXW-1793: Rework erroring questions table to use a non-viz table](https://linear.app/metabase/issue/UXW-1793/rework-erroring-questions-table-to-use-a-non-viz-table)
