### PR TITLE
fixed table width in guest embed

### LINKED ISSUE #69831: Table viz guest embeds don't span the whole width of the component (but static embeds did)
### Describe the bug

If you guest embed a question, there is some extra space on the right and it doesn't span the entire width of the container, unlike static embedding where it spans the whole width.

### To Reproduce

1. Create any table question e.g. "Orders"
2. Share > Embed

Image
3. Put the embedding code in your site using the usual Guest embed approach, and also using an iframe on `/embed/question/${token}`:
```js
<script defer src="http://localhost:3073/app/embed.js"></script>
<script>
function defineMetabaseConfig(config) {
  window.metabaseConfig = config;
}
</script>

<script>
  defineMetabaseConfig({
    "isGuest": true,
    "instanceUrl": "http://localhost:3073",
  });
</script>

<h1>Guest embedding</h1>
  <metabase-question token="${token}" with-title="true" with-downloads="false" style="height: 300px;"></metabase-question>
<h1>iframe (static)</h1>
<iframe src="http://localhost:3073/embed/question/${token}" width="100%" height="400px"></iframe>
```
4. The guest embed has extra whitespace to the right, while the iframe occupies 100% of the width

Image

### Expected behavior

It should be a drop-in replacement for static embeds, so it should also occupy the entire width

### Logs

_No response_

### Information about your Metabase installation

```JSON
58.5.3
```

### Severity

P2

### Additional context

Workaround is to use /embed/question anyway or to use a dashboard guest embed (with just the table) instead

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #69831
Closes [EMB-1358: Table viz guest embeds don't span the whole width of the component (but static embeds did)](https://linear.app/metabase/issue/EMB-1358/table-viz-guest-embeds-dont-span-the-whole-width-of-the-component-but)

### Description

Checks whether we're in an embedding context before using the full width to render a table

### How to verify

1. Create any table question e.g. "Orders"
2. Share > Embed

Image
3. Put the embedding code in your site using the usual Guest embed approach, and also using an iframe on `/embed/question/${token}`:

```js
<script defer src="http://localhost:3073/app/embed.js"></script>
<script>
function defineMetabaseConfig(config) {
  window.metabaseConfig = config;
}
</script>

<script>
  defineMetabaseConfig({
    "isGuest": true,
    "instanceUrl": "http://localhost:3073",
  });
</script>

<h1>Guest embedding</h1>
  <metabase-question token="${token}" with-title="true" with-downloads="false" style="height: 300px;"></metabase-question>
<h1>iframe (static)</h1>
<iframe src="http://localhost:3073/embed/question/${token}" width="100%" height="400px"></iframe>
```

### Demo

image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.tsx [hunk 1]
```diff
@@ -707,8 +707,8 @@ export const TableInteractiveInner = forwardRef(function TableInteractiveInner(
   }, [height, settings]);
 
   const minGridWidth = useMemo(() => {
-    return isDashcardViewTable ? width : undefined;
-  }, [isDashcardViewTable, width]);
+    return isDashcardViewTable || isEmbeddingSdk ? width : undefined;
+  }, [isDashcardViewTable, isEmbeddingSdk, width]);
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.tsx:711]: 🥺 I wish we didn't need the isEmbeddingSdk checks, but there's no other way I assume

File: e2e/test/scenarios/embedding/sdk-iframe-embedding/sdk-iframe-embedding.cy.spec.ts [hunk 2]
```diff
@@ -81,6 +81,57 @@ describe("scenarios > embedding > modular embedding", () => {
...
+        ],
+      });
+
+      cy.wait("@getCardQuery");
+
+      frame.within(() => {
+        // clientWidth excludes the scrollbar gutter, giving us the actual content area
+        H.tableInteractive()
+          .findByTestId("table-scroll-container")
+          .then(($scrollContainer) => {
```
Comment (heypoom) [inline e2e/test/scenarios/embedding/sdk-iframe-embedding/sdk-iframe-embedding.cy.spec.ts:116]: nit: using `.should` would make it retryable, which could be helpful if the table didn't immediately load after `@getCardQuery`.

**Review by heypoom — APPROVED** [review]
Tested locally - works well! Static and guest embeds has the same full width.

Image
