### PR TITLE
fix: limit xrays on agg models to source fields

### LINKED ISSUE #43793: firing an x-ray made of aggregated fields will generate bad wrong queries
### Describe the bug

If you try to x-ray some model that was made with aggregations, then the x-ray will fail with all questions being wrong

### To Reproduce

1) build a question like 
image
2) save it as a model
3) then do an x-ray on the model

see the dashboard failing on every question

### Expected behavior

It should work

### Logs

image

ERROR: column source.user_id does not exist
  Position: 926

### Information about your Metabase installation

```JSON
v50, but probably comes from a previous version
```

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by snoe**
Fixes #43793

1. `table-like?` was checking aggregations but not breakouts. This meant that legacy metric definitions would try to apply to the second stage which is generally illegal and would cause things like implicit joins to come in where they make no sense.
2. Trying to bin a `count` metric-like model would give a bin span of 0.0 which would blow up those questions.
3. Trying to self reference breakout fields, in the precense of a question's  aggregation meant that most fields would not be exposed to the next stage and should be ignored. (similar to 1.)

### CODE REVIEW

File: src/metabase/xrays/automagic_dashboards/core.clj [hunk 1]
```diff
@@ -434,16 +436,18 @@
...
+                                 :result_metadata
+                                 (map (fn [field]
+                                        (as-> field field
+                                          (update field :base_type keyword)
+                                          (update field :semantic_type keyword)
+                                          (mi/instance Field field)
+                                          (analyze/run-classifiers field {})
+                                          (assoc field :db db)))))]
+          (constantly source-fields))
+        (constantly [])))))
```
Comment (metamben) [inline src/metabase/xrays/automagic_dashboards/core.clj:450]: Why do aggregated models have no relevant fields?

**Review by metamben — COMMENTED** [review]
I don't see why the existing tests have to be changed like this? Can you explain?

**Review by metamben — APPROVED** [review]
Let's go with this for now and see what @luizarakaki thinks about the way forward.
