### PR TITLE
Fix: #50011 Hides "Here are some explorations of" when there are no explorations

### LINKED ISSUE #50011: Incorrect empty state of automagic dashboards on the homepage
### Describe the bug

Image

### To Reproduce

1. Make GET `/api/automagic-dashboards/database/:id/candidates` return an empty array
2. Open Metabase
3. See "Here are some explorations of ClickHouse" label

There are no explorations

### Expected behavior

There is no "Here are some explorations of ClickHouse" label when there are no explorations 

### Logs

_No response_

### Information about your Metabase installation

```JSON
master, aaedddf828
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bpander**
Closes https://github.com/metabase/metabase/issues/50011
Closes UXW-245

### Description

Hides "Here are some explorations of" when there are no explorations.

### How to verify

See #50011 for repro steps. I repro'd by moving `metabase.db.mv.db` out of the repo root so it'd take me through the setup flow, then I pointed it at a db started using `mage start-db postgres latest` so it wouldn't start with x-rays of sample data.

### Demo

Screenshot 2025-09-22 at 11 56 27 AM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/home/components/HomeXraySection/HomeXraySection.tsx [hunk 1]
```diff
@@ -90,12 +90,12 @@ const HomeXrayView = ({ database, candidates = [] }: HomeXrayViewProps) => {
           {t`schema in`}
           <DatabaseInfo database={database} />
         </HomeCaption>
-      ) : (
+      ) : (candidate?.tables.length ?? 0) > 0 ? (
```
Comment (iethree) [inline frontend/src/metabase/home/components/HomeXraySection/HomeXraySection.tsx]: maybe extract this to a boolean like `hasTables` ?

**Review by iethree — APPROVED** [review]
