### PR TITLE
SDK loaderComponent now applies to all loaders

### LINKED ISSUE #65979: SDK interactive dashboard shows 3 different loaders and only one can be customized
### Describe the bug

Although brief, it's noticeable that the InteractiveDashboard component has three different loaders:
- One for loading the SDK + doing auth `/api/user/current` (overridable through the loaderComponent prop of MetabaseProvider)
- One for loading the dashboard `/api/dashboard/:id`
- Some post dashboard loading (`/api/collection/:id`)

### To Reproduce

1. Start Metabase v56
2. Embed with the SDK, something like this:
```tsx
<MetabaseProvider
  authConfig={authConfig}
  loaderComponent={() => <p>custom loader component...</p>}
>
  <InteractiveDashboard
    dashboardId={1}
  ></InteractiveDashboard>
</MetabaseProvider>
```

3. Use network throttling on the browser or in my case I added `(Thread/sleep 5000)` to the backend on endpoints `api/user/current` (first loader), `/api/dashboard/:id` (second loader) and `/api/collection/:id` (third loader)
4. Only the first loader is replaced, then two more different loaders show up

https://github.com/user-attachments/assets/84b40f0e-59f7-4501-b5bf-a67c251c9025

### Expected behavior

It should consistently use the same loader so the user doesn't see different ones, and it should be possible to replace it with the custom component

### Logs

_No response_

### Information about your Metabase installation

```JSON
v56.14.5
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #65979
Closes [EMB-1036: SDK interactive dashboard shows 3 different loaders and only one can be customized](https://linear.app/metabase/issue/EMB-1036/sdk-interactive-dashboard-shows-3-different-loaders-and-only-one-can)

### Description

When using the SDK, users can pass `loaderComponent` to the MetabaseProvider component. This is now used for all loaders.

The UI component `Loader` now exports a `setCustomLoader` that can be used to override using Mantine's Loader, and I've added a custom hook that reads from the SDK store to possibly set this custom loader.

### How to verify

1. Start Metabase
2. Embed with the SDK, something like this:
```tsx
<MetabaseProvider
  authConfig={authConfig}
  loaderComponent={() => <p>custom loader component...</p>}
>
  <InteractiveDashboard dashboardId={1}/>
</MetabaseProvider>
```
3. Use network throttling on the browser or in my case I added (Thread/sleep 5000) to the backend on endpoints api/user/current (first loader), /api/dashboard/:id (second loader) and /api/collection/:id (third loader)
4. all loaders should be customized

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+import { useMetabaseProviderPropsStore } from "embedding-sdk-shared/hooks/use-metabase-provider-props-store";
+import { setCustomLoader } from "metabase/ui/components/feedback/Loader/Loader";
+
+export function useSdkCustomLoader() {
+  const {
+    state: { props: metabaseProviderProps },
+  } = useMetabaseProviderPropsStore();
+
+  useEffect(() => {
+    setCustomLoader(metabaseProviderProps?.loaderComponent);
```
Comment (deniskaber) [inline frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.ts:12]: WDYT about 

```suggestion
    if (metabaseProviderProps?.loaderComponent) {
        setCustomLoader(metabaseProviderProps.loaderComponent);
    }
```

File: frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.unit.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+    },
+  },
+});
+
+describe("useSdkCustomLoader", () => {
+  beforeEach(() => {
+    jest.clearAllMocks();
+  });
+
+  it("calls setCustomLoader with undefined when no loader component is provided", () => {
```
Comment (deniskaber) [inline frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.unit.spec.tsx:33]: Do you think we really want to call `setCustomLoader` if no loader is provided?

File: frontend/src/metabase/ui/components/feedback/Loader/Loader.tsx [hunk 3]
```diff
@@ -9,6 +9,17 @@ const SIZES: Record<string, string> = {
...
+
+let customLoader: CustomLoader;
+
+export const setCustomLoader = (component: CustomLoader) => {
+  customLoader = component;
+};
+
+export const Loader = ({ size = "md", ...props }: LoaderProps) => {
+  if (customLoader) {
+    return customLoader();
```
Comment (deniskaber) [inline frontend/src/metabase/ui/components/feedback/Loader/Loader.tsx]: Perhaps we should pass props to this customLoader component ?

File: frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.unit.spec.tsx (hunk 2 above)
Comment (lorem--ipsum) [reply frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.unit.spec.tsx:33]: To reinitialize it? It's unlikely but I don't like the idea of setting something and then not being able to reset it.

File: frontend/src/metabase/ui/components/feedback/Loader/Loader.tsx (hunk 3 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/ui/components/feedback/Loader/Loader.tsx]: I've thought of it but I'd rather do that if someone asks for it: it's not in the scope of this issue and it will require documentation (as in, it'd be more of a feature, really).

File: frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.ts (hunk 1 above)
Comment (lorem--ipsum) [reply frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.ts:12]: See my other commment about passing `undefined` to `setCustomLoader` :-)

File: frontend/src/metabase/ui/components/feedback/Loader/Loader.tsx (hunk 3 above)
Comment (WiNloSt) [reply frontend/src/metabase/ui/components/feedback/Loader/Loader.tsx]: I'd rather render this as a react component rather than calling it as a function. This will ensure it's render as a component in React dev tool.

**Comment by WiNloSt** [comment]
I mean we're literally changing the Mantine loader to the new loader we just set via prop. But this doesn't solve this loader, though. It seems it's accompanied by a label. Previously, it was a loading spinner on top of the `Loading...` label.

Screenshot 2025-12-12 at 8 35 31 PM

File: frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.ts [hunk 4]
```diff
@@ -0,0 +1,14 @@
+import { useEffect } from "react";
+
+import { useMetabaseProviderPropsStore } from "embedding-sdk-shared/hooks/use-metabase-provider-props-store";
+import { setCustomLoader } from "metabase/ui/components/feedback/Loader/Loader";
+
+export function useSdkCustomLoader() {
```
Comment (WiNloSt) [inline frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.ts:6]: So we're using both this hook and `getLoaderComponent` (the current way we use the `loaderComponent` prop)? I don't quite fancy we have multiple ways to do the same thing. Could they be consolidated somehow?

File: frontend/src/metabase/ui/components/feedback/Loader/Loader.unit.spec.tsx [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+
+  it("renders custom loader when one is set", () => {
+    const CustomLoader = () => (
+      <div data-testid="custom-loader">Custom Loader</div>
+    );
+
+    setCustomLoader(CustomLoader);
+    renderWithProvider(<Loader />);
+
+    expect(screen.getByTestId("custom-loader")).toBeInTheDocument();
```
Comment (WiNloSt) [inline frontend/src/metabase/ui/components/feedback/Loader/Loader.unit.spec.tsx:31]: nit: I'd just use `getByText`, like we're literally set the loader text here a few lines above this assertion.

File: frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.unit.spec.tsx
Comment (WiNloSt) [inline frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.unit.spec.tsx:1]: Tbh I'd rather write a new case in any of our component test for SDK and actually pass `loaderComponent` rather than relying on mocking in unit tests. You can keep the test, but with a lot of mocking it doesn't give me much confident because the implementation could change any time. But the behavior isn't actually tested.

**Review by WiNloSt — APPROVED** [review]

File: frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.unit.spec.tsx
Comment (lorem--ipsum) [reply frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-custom-loader/use-sdk-custom-loader.unit.spec.tsx:1]: Yup, made a followup task for this: https://linear.app/metabase/issue/EMB-1150/add-an-end-to-end-test-for-the-loadercomponent-prop-in-sdk
