### PR TITLE
fix: druid breakout and agg names must be unique

### LINKED ISSUE #10670: Druid: can't use count aggregation while grouping on a field named "count"
If you try to group by field "count" in our checkins dataset and aggregate by count, you get 
```
java.lang.Exception: Unknown exception Instantiation of [simple type, class io.druid.query.topn.TopNQuery] value failed: [count] already defined Error
```

### PR DESCRIPTION
**Pull request by snoe**
Closes #10670

https://www.loom.com/share/0b0ad1a49b3f460f9bfba5b0d12e32be

### CODE REVIEW

**Review by rileythomp — APPROVED** [review]

File: modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc_test.clj [hunk 1]
```diff
@@ -550,6 +554,18 @@
...
        (take 5)))
 
+(deftest breakout-aggregation-unique-names-test
+  (testing "Breakouts must be unique from aggregation names (#10670)"
+    (tqpt/test-timeseries-drivers
+      (let [mp (lib.metadata.jvm/application-database-metadata-provider (mt/id))
+            query (as-> (lib/query mp (lib.metadata/table mp (mt/id :checkins))) $q
+                    (lib/breakout $q (m/find-first (comp #{"count"} :name) (lib/breakoutable-columns $q)))
+                    (lib/aggregate $q (lib/count)))]
+        (is (= [[1 1000]]
```
Comment (ericnormand) [inline modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc_test.clj]: I'm not sure I like this assertion. It's asserting too much. The original bug was that an exception was thrown. We should just assert that a row is returned, not check actual values.

File: modules/drivers/druid/src/metabase/driver/druid/query_processor.clj [hunk 2]
```diff
@@ -674,11 +674,14 @@
       [:max      _]    [[(or output-name-kwd :max)]
                         {:aggregations [(ag:doubleMax ag-field (or output-name :max))]}])))
 
+(def ^:private ^:dynamic *query-unique-name-fn*
+  nil)
```
Comment (ericnormand) [inline modules/drivers/druid/src/metabase/driver/druid/query_processor.clj]: If someone forgets to set this variable, it will be a null pointer exception. Can we make the default throw something with a clear error message about how to fix it? Something like:

> Please bind `metabase.driver.druid.query-processor/*query-unique-name-fn*` to `(driver-api/unique-name-generator)`. See xxx for an example.

**Review by ericnormand — CHANGES_REQUESTED** [review]
Looks good with a couple of changes.

**Review by ericnormand — APPROVED** [review]
