### PR TITLE
fix(dashboard): In dashboard value source modal, after closing question picker modal, don't also close the first modal

### LINKED ISSUE #46149: Exiting a question picker modal launched by a Selectable values modal closes both modals
Screencast showing the bug: https://www.loom.com/share/d0841e86f37440d38361a212c86660b1?sid=bdbf6102-dc36-400d-9272-4767ceb95284

To reproduce:
1. Create a dashboard
2. Add a text filter
3. Under "How should people filter on this column?", click Edit
4. Click "Pick a modal or question"
5. Close that modal

Expected behavior: The "Selectable values" modal should remain open
Actual behavior: Both modals close

### PR DESCRIPTION
**Pull request by rafpaf**
Fixes #46149

To test, follow the reproduction instructions in #46149 and see that only the top modal is closed, not the modal behind it:

1. Create a dashboard
2. Add a text filter
3. Under "How should people filter on this column?", click Edit
4. Click "Pick a modal or question"
5. Close that modal
6. On this branch (unlike master): The "Selectable values" modal remains open

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#47242** <a href="https://app.graphite.dev/github/pr/metabase/metabase/47242?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: frontend/src/metabase/core/components/SelectButton/SelectButton.tsx [hunk 1]
```diff
@@ -82,6 +82,7 @@ const SelectButton = forwardRef(function SelectButton(
         hasValue={hasValue}
         highlighted={highlighted}
         onClick={rightIcon === "close" ? handleClear : undefined}
+        style={{ flexShrink: 0 }}
```
Comment (rafpaf) [inline frontend/src/metabase/core/components/SelectButton/SelectButton.tsx:85]: Fixing this icon on the fly. It was shrinking very small when the viewport got narrow

**Review by sloansparger — APPROVED** [review]

**Comment by rafpaf** [comment]
### Merge activity

* **Aug 26, 3:33 PM EDT**: @rafpaf merged this pull request with [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/47242).
