### PR TITLE
Fix custom mapping doesn't work on dashboard

### LINKED ISSUE #29347: Custom mappings are broken
**Describe the bug**
We seem to have broken custom field remappings in 45. They worked in 44.6 but now 46-RC3 does not display the mappings:
Values are there, the filters simply don't show them
image

**Logs**
NA

**To Reproduce**
1) go to settings->data model->orders-> change the data type to category and click on the gear on "quantity" field
2) remap a few quantities to words
3) create a new question with the orders table, add it to a dashboard
4) create a dropdown filter and connect it to quantity field
5) Click on the filter, you won't see the remappings

**Expected behavior**
Remappings should be there

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Metabase version: 1.46.0-RC3

**Severity**
P1

**Additional context**
NA

### PR DESCRIPTION
**Pull request by qnkhuat**
This PR is a re-do of https://github.com/metabase/metabase/pull/29359, which I merged without resolving all the comments. 

Fixes #29347, and #29346 by reverting the change I did in https://github.com/metabase/metabase/pull/22836,

Basically, before 43 we have a hydration key `param_values` that is a map of `param-id-> [[label, value]]` which FE used to infer which the label for users selected `param value`.

This PR brings back that hydration key.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30217)

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj [hunk 1]
```diff
@@ -75,6 +76,26 @@
                                          (mbql.u/match-one v [:dimension [:field field-id _]] field-id))]
                     {k (get login-attributes k)})))])))
 
+(defenterprise field-id->field-values-for-current-user
+  "Fetch *existing* FieldValues for a sequence of `field-ids` for the current User. Values are returned as a map of
```
Comment (qnkhuat) [inline enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:80]: Dan: 

Can you clarify the expectation here? The docstring stresses this fetches *existing* FieldValues. It seems the unsandboxed fields behave this way (params.field-values/default-field-id->field-values-for-current-user only selects from the app db), but the sandboxed version calls a get-or-create style function which seems to create FieldValues that do not yet exist.

I guess I'm confused why existence is a relevant factor for return value. To me, it seems like the existence of FieldValues is a bit of an implementation detail. My thinking is both sandboxed and not should create field values if they don't exist. Can you explain the thinking behind the divergence here?

https://github.com/metabase/metabase/pull/29359#discussion_r1170002315

Comment (qnkhuat) [reply enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:80]: there are 2 main types of FieldValues: full and advanced.

In this case sandboxed field values are considered `advanced` FieldValues and we consider them as "on-demand" field values. 

Unlike the full field values, we scan them and store them during sync and do not think of them as `on-demand`.

Comment (qnkhuat) [reply enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:80]: that explains why we did not have `get-or-create` for Full FieldValues.

But, since we introduced [Disable field value scanning for inactive fields](https://github.com/metabase/metabase/pull/26974) a while ago, I think it's also good to call `get-or-create` when fetching Full FieldValues too since it's now semi-on-demand.

File: src/metabase/models/params.clj [hunk 2]
```diff
@@ -67,6 +70,38 @@
...
+  (let [fv-return-keys    [:values :human_readable_values :field_id]
+        field-id->fvs     (t2/select-fn->fn :field_id identity (cons FieldValues fv-return-keys)
+                                            :type :full
+                                            :field_id [:in param-field-ids])
+        missing-field-ids (set/difference (set param-field-ids) (set (keys field-id->fvs)))
+        missing-fields    (when (seq missing-field-ids)
+                            (t2/select Field :id [:in missing-field-ids]))]
+    (into field-id->fvs
+          (for [field missing-fields
+                :let [field-values (field-values/get-or-create-full-field-values! field)]]
```
Comment (qnkhuat) [inline src/metabase/models/params.clj:93]: Dan: 

Does the field-values/get-or-create-full-field-values! function ignore the current user? It seems like it behaves that way but it just hits qp/process-query so I'm a bit surprised that it works if we aren't telling it to ignore the current user.

https://github.com/metabase/metabase/pull/29359/commits/64c82d15ae7834eb74b439e0ded1be6a99209629#r1170039482

File: enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj [hunk 3]
```diff
@@ -14,6 +15,46 @@
    [schema.core :as s]
    [toucan2.core :as t2]))
 
+(deftest params-values-test
```
Comment (qnkhuat) [inline enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj:18]: Dan:

A lot of times these tests can be flaky and really tricky because sometimes the field values already exist and sometimes they don't. I added

```clojure
(t2/delete! 'FieldValues :field_id
            [:in [(mt/id :users :name)
                  (mt/id :categories :name)
                  (mt/id :venues :name)]])
```
Right before the assertion and I got a failure:

```clojure
expected: {46100 {:values ["Garaje" "Gordo Taqueria" "La Tortilla"], :human_readable_values [], :field_id 46100},
           46112 {:values ["African" "American" "Artisan"], :human_readable_values [], :field_id 46112}}
  actual: {46100 {:values ("Garaje" "Gordo Taqueria" "La Tortilla"), :human_readable_values (), :field_id 46100}}
    diff: - {46112 {:values ["African" "American" "Artisan"], :human_readable_values [], :field_id 46112}}
```

Do you know what should happen here if none of these field values exist? 

I'm sorry to harp so much on this but this is a source of really hard to track down bugs. If the answer is "if they exist the user can see them" then that's fine if a bit weird. But at least it is deliberate. And if so we should test them that way.

https://github.com/metabase/metabase/pull/29359#discussion_r1170027893

Comment (qnkhuat) [reply enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj:18]: this is basically related to [this](https://github.com/metabase/metabase/pull/30217/files#r1170878780) problem.

When you call delete like that, it deletes all full and advanced FieldValues for a field. this And since the field `(mt/id :categories :name)` is not sandboxed in this case, it calls to the OSS implementation and get the full values(not sandboxed values). And because the current implementation of full values does not `get-or-create`, we got nothing back.

**Comment by qnkhuat** [comment]
@dpsutton your reviews are spot on, but I think the chance of Full FieldValues to not existing can only be caused by being inactive, which was introduced recently([Disable field value scanning for inactive fields](https://github.com/metabase/metabase/pull/26974))

so I think we should solve that separately and created this issue: https://github.com/metabase/metabase/issues/30218.

That said, I reverted the change([commit](https://github.com/metabase/metabase/pull/30217/commits/63645efb0ef3058424b3228cdc126c120a823d44)) that creates full field values on demand and bring back the old behavior.

Let's solve both issues later.

**Review by dpsutton — APPROVED** [review]
