### PR TITLE
Fix values source modal not handling not having access to the root collection

### LINKED ISSUE #30355: Users with No Access to the Collection Our Analytics are not able to define a dropdown list from models/questions
### Describe the bug

Users with No Access to Collection Our Analytics are not able to define a dropdown list from models ... The reason seems to be that the first call 

image

If you check the underlying calls the first call is a request to `api/collection/root` which will automatically load the Our Analytics. Failing with a permission error:

image

 

### To Reproduce

1. Go to New -> Collection -> New Collection
2. Go to People -> Groups -> New Group -> Name it Test and Save
3. Go to People -> People -> Invite Someone -> Add it to Group Test

image

4. Go to Permissions -> Collections -> Give No Access to Test and All Users to Our Analytics -> Give Curate Access to Test Group for New Collection

image

image

5. Login As User -> New Dashboard -> Add a Text Filter -> Go to Edit Dropdown list -> From another model or Question -> Click on Pick a Model

image

6. Notice it fails with a permission error:

image

### Expected behavior

Models or Questions are loaded from other collections 

### Logs

`WARN metabase.server.middleware.log GET /api/collection/root 403 16.1 ms (2 DB calls) 
"You don't have permissions to do that."`

### Information about your Metabase installation

```JSON
Able to replicate on 1.46.1 and master
```

### Severity

Will cause a lot of trouble for normal users trying this new feature

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/30355

How to test:
- Add a collection in "Our analytics" and add a question to it
- Add another user in Admin -> People
- Revoke "Our analytics" permissions in Admin -> Permissions for All users. The new user would have access to the inner collection but not the root one
- Log in as the new user
- Go to the created collection -> New -> Dashboard -> Filter -> Text or Category -> Is -> Dropdown list -> Edit
- From model or saved question -> Pick question 
- Make sure it's possible to select a question in this case

Screenshot 2023-04-26 at 14 08 27

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30384)

### CODE REVIEW

File: frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceCardModal.tsx [hunk 1]
```diff
@@ -201,7 +202,7 @@ export default _.compose(
   }),
   Collections.load({
     id: (state: State, { card }: ModalCardProps) =>
-      card?.collection_id ?? "root",
+      card ? coerceCollectionId(card.collection_id) : undefined,
```
Comment (ranquild) [inline frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceCardModal.tsx:205]: If we have card, we can load its collection. When we don't - don't try to load the root collection because it can fail.

File: frontend/test/__support__/server-mocks/collection.ts [hunk 2]
```diff
@@ -58,3 +59,16 @@ export function setupCollectionVirtualSchemaEndpoints(
   fetchMock.get(urls.questions, questionVirtualTables);
   fetchMock.get(urls.models, modelVirtualTables);
 }
+
+export function setupUnauthorizedCollectionEndpoints(collection: Collection) {
```
Comment (ranquild) [inline frontend/test/__support__/server-mocks/collection.ts:63]: Same as card endpoints

File: frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx [hunk 3]
```diff
@@ -368,34 +380,41 @@ describe("ValuesSourceModal", () => {
...
 
-const setup = ({
+const setup = async ({
   parameter = createMockUiParameter(),
   parameterValues = createMockParameterValues(),
+  databases = [createMockDatabase()],
+  collections = [createMockCollection(ROOT_COLLECTION)],
   cards = [],
-  hasDataAccess = true,
+  hasCollectionAccess = true,
```
Comment (ranquild) [inline frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx:396]: Data access is a different thing, so lets call it properly here to avoid confusion

File: frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx [hunk 4]
```diff
@@ -255,16 +253,33 @@ describe("ValuesSourceModal", () => {
...
+        hasCollectionAccess: false,
       });
 
       expect(
-        await screen.findByText("You don't have permissions to do that."),
+        screen.getByText("You don't have permissions to do that."),
+      ).toBeInTheDocument();
+    });
+
+    it("should allow searching for a card without access to the root collection (metabase#30355)", async () => {
```
Comment (ranquild) [inline frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx:264]: This test fails if we revert the change to `ValuesSourceCardModel` because it would try to load the root collection in this case

File: frontend/src/metabase/containers/DataPicker/CardPicker/CardPickerContainer.tsx [hunk 5]
```diff
@@ -38,7 +38,7 @@ interface CardPickerStateProps {
 interface CollectionsLoaderProps {
   collectionTree: Collection[];
   collections: Collection[];
-  rootCollection: Collection;
+  rootCollection?: Collection;
```
Comment (ranquild) [inline frontend/src/metabase/containers/DataPicker/CardPicker/CardPickerContainer.tsx:41]: The component handles missing `rootCollection` but the type was incorrect. Lets explicitly tell it can be `undefined` here

**Review by WiNloSt — COMMENTED** [review]
I think you should fix the wrong mock endpoint if I understand that correctly. Otherwise, the fix itself looks pretty straightforward.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30384#-:-NTxZM7e9GmuxRv1Bbdw:b-vj0k82)* status: all files reviewed, 10 unresolved discussions (waiting on @ranquild)

___
*[`frontend/src/metabase/containers/DataPicker/CardPicker/CardPickerContainer.tsx` line 41 at r1](https://reviewable.io/reviews/metabase/metabase/30384#gh-1177722422:-NTxLg1-3bPIhcREkW8k:b-77g2ud) ([raw file](https://github.com/metabase/metabase/blob/ef77c403a984ec524730773f7d10f8bdc9789a3e/frontend/src/metabase/containers/DataPicker/CardPicker/CardPickerContainer.tsx#L41)):*
<details><summary><i>Previously, ranquild (Alexander Polyankin) wrote…</i></summary><blockquote>

The component handles missing `rootCollection` but the type was incorrect
</blockquote></details>

nit: Should we use the same type defined in `frontend/src/metabase/containers/DataPicker/CardPicker/utils.ts`?

```ts
rootCollection: Collection | undefined
```

Also, it should be more correct (if I'm not mistaken) because we pass `rootCollection` as `undefined` here

https://github.com/metabase/metabase/blob/724855886fcc7adcdddf9be360bf1fc1c6fbbb7b/frontend/src/metabase/entities/containers/EntityObjectLoader.jsx#L105



_Code quote (from frontend/src/metabase/containers/DataPicker/CardPicker/utils.ts):_
```XML
rootCollection: Collection | undefined
```
___
*[`frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceCardModal.tsx` line 205 at r1](https://reviewable.io/reviews/metabase/metabase/30384#gh-1177719886:-NTxU17xEikJUxa1lLAv:bdhgs8q) ([raw file](https://github.com/metabase/metabase/blob/ef77c403a984ec524730773f7d10f8bdc9789a3e/frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceCardModal.tsx#L205)):*
<details><summary><i>Previously, ranquild (Alexander Polyankin) wrote…</i></summary><blockquote>

If we have card, we can load its collection. When we don't - don't try to load the root collection because it can fail.
</blockquote></details>

Neat! I just know we can pass null or undefined to tell the entity loader to not call the API
https://github.com/metabase/metabase/blob/724855886fcc7adcdddf9be360bf1fc1c6fbbb7b/frontend/src/metabase/entities/containers/EntityObjectLoader.jsx#L67-L76
___
*[`frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx` line 273 at r1](https://reviewable.io/reviews/metabase/metabase/30384#-NTxW_IbEWwpsxKrFpeq:-NTxW_IbEWwpsxKrFper:brlg9jx) ([raw file](https://github.com/metabase/metabase/blob/ef77c403a984ec524730773f7d10f8bdc9789a3e/frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx#L273)):*
> ```XML
>       );
>       userEvent.click(
>         screen.getByRole("button", { name: /Pick a model or question…/ }),
> ```

What do you think about adding `aria-label` so we could refer to this button with just a simple text? In this case, the regex is used because the accessible name includes the icon too.




_Code quote:_
```XML
        screen.getByRole("button", { name: /Pick a model or question…/ }),
```
___
*[`frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx` line 394 at r1](https://reviewable.io/reviews/metabase/metabase/30384#-NTxXgQnCVCXCE9rtUee:-NTxXgQnCVCXCE9rtUef:b-u2dwac) ([raw file](https://github.com/metabase/metabase/blob/ef77c403a984ec524730773f7d10f8bdc9789a3e/frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx#L394)):*
> ```XML
>   parameterValues = createMockParameterValues(),
>   databases = [createMockDatabase()],
>   collections = [createMockCollection(ROOT_COLLECTION)],
> ```

Having new parameters give the impression that they're being used. I don't think that is the case here. Can we move this inside the setup function instead? We can always lift them up here once we're passing them as arguments.



_Code quote:_
```XML
  databases = [createMockDatabase()],
  collections = [createMockCollection(ROOT_COLLECTION)],
```
___
*[`frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx` line 426 at r1](https://reviewable.io/reviews/metabase/metabase/30384#gh-1177720389:-NTxXJzU5BVoNzUn_sz8:ba3r61t) ([raw file](https://github.com/metabase/metabase/blob/ef77c403a984ec524730773f7d10f8bdc9789a3e/frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx#L426)):*
<details><summary><i>Previously, ranquild (Alexander Polyankin) wrote…</i></summary><blockquote>

Use our established patterns and simplify tests by waiting for content being loaded here.
</blockquote></details>

This is super nice. You can remove a bunch of `findBy` and `waitFor` since we ensure everything is loaded after this point.
___
*[`frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx` line 427 at r1](https://reviewable.io/reviews/metabase/metabase/30384#-NTxVLDD-4VzdFJty7HY:-NTxVLDD-4VzdFJty7HZ:b9wws23) ([raw file](https://github.com/metabase/metabase/blob/ef77c403a984ec524730773f7d10f8bdc9789a3e/frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx#L427)):*
> ```XML
> 
>   await waitFor(() => {
>     expect(screen.queryByText(/Loading/)).not.toBeInTheDocument();
> ```

nit: Can we use a full string instead? I think it should be `Loading...` or `Loading…` whatever we use in this particular case.
___
*[`frontend/test/__support__/server-mocks/collection.ts` line 64 at r1](https://reviewable.io/reviews/metabase/metabase/30384#-NTxYz6G0DBbXxrZJoL9:-NTxYz6G0DBbXxrZJoLA:bglw8i6) ([raw file](https://github.com/metabase/metabase/blob/ef77c403a984ec524730773f7d10f8bdc9789a3e/frontend/test/__support__/server-mocks/collection.ts#L64)):*
> ```XML
> 
> export function setupUnauthorizedCollectionEndpoints(collection: Collection) {
>   fetchMock.get(`path:/api/card/${collection.id}`, {
> ```

I believe this is supposed to be
`path:/api/collection/${collection.id}` right?

the `/api/card` prefix with collection ID just sounds wrong. And that begs the question if it has anything to do with the test if this was mocked wrongly.

**Comment by ranquild** [comment]
@WiNloSt fixed the mock and setup params, please take a look

**Review by WiNloSt — APPROVED** [review]
Looks good to me.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30384#-:-NTxa6v32-1VBNfyMCF7:b9j9n43)* status: all files reviewed, 10 unresolved discussions (waiting on @ranquild)

File: frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx [hunk 6]
```diff
@@ -255,16 +248,33 @@ describe("ValuesSourceModal", () => {
...
+      await setup({
+        hasCollectionAccess: false,
       });
 
+      userEvent.click(
+        screen.getByRole("radio", { name: "From another model or question" }),
+      );
+      userEvent.click(
+        screen.getByRole("button", { name: /Pick a model or question…/ }),
```
Comment (uladzimirdev) [inline frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx:268]: nit: I'd be consistent on using string vs regexp

**Review by uladzimirdev — COMMENTED** [review]
LGTM, left minor comments

**Review by uladzimirdev — APPROVED** [review]
LGTM, left minor comments

File: frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx (hunk 6 above)
Comment (ranquild) [reply frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceModal.unit.spec.tsx:268]: It's not possible easily use string here because of an inner icon that has label
