### PR TITLE
hiding Card Parameter Mapper header on small cards

### LINKED ISSUE #32204: Cards that are 1-2 grid units tall look broken in dashboard filter mapping mode
### Describe the bug

- You can hardly see the dropdown when a dashboard card is only 1-2 rows tall.
- I propose we hide the help text ("Column to filter on") when cards are only one row tall.

Screen Shot 2023-07-06 at 10 23 35 AM

### To Reproduce

1. Create a dashboard
2. Add a filter to it
3. Add a saved question to it and make it one grid row tall
4. Click the filter in edit mode to enter filter mapping mode 
5. See the partly-hidden dropdown

### Expected behavior

I propose we hide the help text ("Column to filter on") when cards are only one row tall.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Mac OS X",
    "os.version": "11.5",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-11-18",
      "src_hash": "09f4ec50c4b6096192e18c140068ce8a7e67434d",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "maz-make-saving-a-question-less-fear-inducing",
      "hash": "f694966"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P2 - looks broken

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/32204

### Description
Applied some changes to how we deice if we render a card parameter mapping header:
- A height is decided based on whether or not we are in a mobile view. If so, we adjust using the same logic that the dashboard grid does. If it is not mobile, we look at `dashcard.size_y`
- if the effective height is less than 2, we no longer render header. If it is more than 2, then the existing logic is followed.
- Some maps were moved to constants and exported so that they could be used in multiple places. I considered making a small function to calculate effective height, but it was able to fit in an inline conditional.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Create a new scalar question (orders, count). Add it to a dashboard
2. Add a Month and Year filter to the dashboard
3. When applying the filter to the card, you should not see the heading `Column to filter on`.
4. Resize the card to be larger, and the heading should be visible in filter mapping mode.
5. Also test in mobile view

### Demo
image
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx [hunk 1]
```diff
@@ -173,6 +173,9 @@ export function DashCardCardParameterMapper({
 
   const headerContent = useMemo(() => {
     if (!isVirtual && !(isNative && isDisabled)) {
+      if (dashcard.size_y <= 2) {
```
Comment (JesseSDevaney) [inline frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx:176]: The issue #32204 states that we should hide the help text only when cards are one row tall. Did this spec change w/o the issue changing, or does Maz still only want it hidden when cards are one row tall?

**Comment by JesseSDevaney** [comment]
Also, are there others fixes for the parameter mapper in the works? I see that one row tall text cards still look clipped when in parameter mapper mode.

image

File: frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx:176]: Shoot, I miss understood the issue. The first bullet point talks about cards that are `1-2 rows tall`, and since things were still cut off at 2 rows I thought that was the requirement. We should double check with @mazameli though... I think content will still be cut off for 2 row cards

Comment (npfitz) [reply frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx:176]: Alternatively, we could also hide the name on 2 row cards. That *might* give us the space we need

Comment (npfitz) [reply frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx]: @JesseSDevaney I got[ some feedback](https://metaboat.slack.com/archives/C02H619CJ8K/p1689178682464829) from the design team and I believe I covered all their asks :)

**Review by JesseSDevaney — APPROVED** [review]
:gem: :rocket:

File: frontend/src/metabase/dashboard/components/grid/utils.js [hunk 2]
```diff
@@ -17,6 +17,16 @@ export function sortCardsForMobile(a, b) {
   return a.x - b.x;
 }
 
+export const MOBILE_HEIGHT_BY_DISPLAY_TYPE = {
```
Comment (alxnddr) [inline frontend/src/metabase/dashboard/components/grid/utils.js:20]: It would be nice to keep the size apsect of cards in a single place. Currenty, the cards sizing is defined in `frontend/src/metabase/visualizations/shared/utils/sizes.ts`

**Review by mazameli — APPROVED** [review]
Looks good to me!

File: frontend/src/metabase/dashboard/components/grid/utils.js (hunk 2 above)
Comment (npfitz) [reply frontend/src/metabase/dashboard/components/grid/utils.js:20]: Good call. I'll move the size related const values 👍
