### PR TITLE
Fix for #24132: Search returns irrelevant matches for non-native questions

### LINKED ISSUE #24132: Search returns irrelevant matches for non-native questions
**Describe the bug**

Global search results can include unrelated results to the search string if they match part of the `dataset_query` string of a question. These include searches like "database", "source" and "filter".

e.g.
image

Here's an example `dataset_query` for a simple question with a filter and a count:
```clojure
  :dataset_query
    "{\"database\":8,\"query\":{\"source-table\":29,\"filter\":[\"=\",[\"field\",133,null],\"user1\"],\"aggregation\":[[\"count\"]]},\"type\":\"query\"}",
```
This question will be included in search results where the search string is a substring of the above dataset-query.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new question, and save it with any title e.g. "Title"
2. Search for "base" (which matches with `database`) or "source" (which matches with `source-table`), and notice the question will appear in search results.

**Expected behavior**
Search results shouldn't include questions that match against the internal structure of the `dataset_query` field for non-native questions.

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/24132

This adds an extra condition on the search query, so that `dataset_query` is only searched if the question is native SQL. 

This will also partially addresses the performance problems in this issue https://github.com/metabase/metabase/issues/17631, as now only native SQL queries will have their text searched (speculative).

### CODE REVIEW

File: test/metabase/api/search_test.clj [hunk 1]
```diff
@@ -596,3 +596,11 @@
               (db/update! Pulse (:id pulse) :dashboard_id (:id dashboard))
               (is (= nil
                      (search-for-pulses pulse))))))))))
+
+(deftest non-native-card-dataset-query-test
+  (testing "You shouldn't see non-native Cards in the search results that match the keys of the dataset_query"
+    ;; https://github.com/metabase/metabase/issues/24132
+    (mt/with-temp Card [card {:name "Round Table" :query_type "query" :dataset_query {:query "select * from round_table"}}]
```
Comment (dpsutton) [inline test/metabase/api/search_test.clj:603]: This test doesn't seem to match up with the description. I would expect it to include a native and a non-native card with a query string that would match both, but only the native card is returned. One example is that you could have one query `"select id, foo from round_table"` and then an mbql card that includes an expression named `"foo"` that is just `(+ 1 1)`, and search for foo.

Comment (dpsutton) [reply test/metabase/api/search_test.clj:603]: something like
```clojure
(deftest non-native-card-dataset-query-test
  (testing "You shouldn't see non-native Cards in the search results that match the keys of the dataset_query"
    ;; https://github.com/metabase/metabase/issues/24132
    (mt/with-temp Card [native-card {:name "native"
                                     :query_type "query"
                                     :dataset_query {:query "select * from foo_bar"}}
                        mbql-card   {:name "mbql"
                                     :query_type "query"
                                     :dataset_query {:query {:expressions {"foo_bar" [:+ 1 1]}}}}]
      (do-test-users [user [:rasta]]
                     (is (= [native-card]
                            (search-request-data user :q "foo_bar")))))))
```
But I don't see this test matching anything. Ideally it would match both cards _before_ the change, and then you evaluate the new code and it matches only a single card.

Comment (calherries) [reply test/metabase/api/search_test.clj]: Good catch, I had some changes to this I forgot to push. I've now updated the test.

**Review by dpsutton — APPROVED** [review]
