### PR TITLE
Fix Permissions Graph failed when schema name has path char

### LINKED ISSUE #22047: Permission graph does not support schemas with slashes
**Describe the bug**
Schemas like `special_/_#_%_'__._&_>_:_ _end` can't be added to the permissions graph because they got trimmed:

Metadata request contains the correct schema name starting with `special_/`
Screenshot 2022-04-26 at 01 54 05

Permissions graph returns a trimmed name
Screenshot 2022-04-26 at 01 54 26

**To Reproduce**
1. Connect a database with a schema called `special_/_#_%_'__._&_>_:_ _end`
2. Go to the permissions page and try setting data permissions for the schema

**Expected behavior**
Permissions graph contains full schema names

**Information about your Metabase Installation:**
Latest master

### PR DESCRIPTION
**Pull request by qnkhuat**
Fix #22047 

We did unescape for schema name that contains path char when granting permissions, but the parse graph function currently trims the schema name from "special/sth" to "sth".

This PR make changes so that the parse function correctly parses schema names with names containing both slash and backslash

### CODE REVIEW

File: src/metabase/api/permission_graph.clj [hunk 1]
```diff
@@ -23,6 +24,14 @@
   [[_ s]]
   (name s))
 
+;; Convert a keyword to string without excluding the namespace.
+;; e.g: :schema/name => "schema/name".
+;; Primarily used for schema-name since schema are allowed to have "/"
+;; and calling (name s) returning a substring after "/".
+(defmethod convert :kw->full-str
```
Comment (qnkhuat) [inline src/metabase/api/permission_graph.clj:31]: Previously we call `(name schema-name)` and it automatically trim "schema/name" => "name" because it recognizes "schema" as the namespace.

File: src/metabase/models/permissions/parse.clj [hunk 2]
```diff
@@ -110,8 +124,8 @@
                                      [:db db-id :data-model :schemas :all])
     [:dm-db db-id db-node]         (let [db-id (Long/parseUnsignedLong db-id)]
                                      (into [:db db-id :data-model :schemas] (path2 db-node)))
-    [:dm-schema schema-name]       [schema-name :all]
-    [:dm-schema schema-name table] (into [schema-name] (path2 table))
+    [:dm-schema schema-name]       [(path1 schema-name) :all]
+    [:dm-schema schema-name table] (into [(path1 schema-name)] (path2 table))
```
Comment (noahmoss) [inline src/metabase/models/permissions/parse.clj:128]: Not a huge deal, but I think it's easier to read & reason about these two matching functions if each one is fully self-contained. Could you add the `:schema-name` clause to this one as well, and then call `path2` here instead?

File: src/metabase/api/permission_graph.clj (hunk 1 above)
Comment (noahmoss) [reply src/metabase/api/permission_graph.clj:31]: Seems like the `:kw->str` method is already only used for schema names. Could you just change that one to call `u/qualified-name` instead of `name`, and avoid adding a new method?

**Review by noahmoss — APPROVED** [review]
👍 just minor comments
