### PR TITLE
Fix mongo OOM during sync

### LINKED ISSUE #42133: Make the sync process more efficient when reading large documents on MongoDB
### Describe the bug

We OOM easily on big documents in MongoDB on relatively small DB's

### To Reproduce

1) spin up a MongoDB 4.4.5 (just mentioning this as the customer who hits this runs this specific MongoDB version, but it can be any). It needs to run on port 27017 with metabase as the username and metasample123 as the password
2) use this script to load a few thousand docs (like 2K docs). Run it with bun runtime for increased speed
```
const { MongoClient, ServerApiVersion } = require("mongodb");

const uri = "mongodb://metabase:metasample123@localhost:27017/admin";

const client = new MongoClient(uri);

// function to generate a random string of length n
function randomString(n) {
  const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let str = "";
  for (let i = 0; i < n; i++) {
    str += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return str;
}

// function to generate a very big and complex bson structure
function generateComplexBSON() {
  return {
    "key1": randomString(65536),
    "key2": randomString(65536),
    "key3": randomString(65536),
    "key4": randomString(65536),
    "key5": randomString(65536),
    "key6": randomString(65536),
    "key7": randomString(65536),
    "key8": randomString(65536),
    "key9": randomString(65536),
    "key10": randomString(65536),
    "key11": randomString(65536),
    "key12": randomString(65536),
    "key13": randomString(65536),
    "key14": randomString(65536),
    "key15": randomString(65536),
  };
};

async function run() {
  try {
    // Connect the client to the server (optional starting in v4.7)
    await client.connect();
    // loop a million times and create documents in the sample.people collection
    for (let i = 0; i < 1000000; i++) {
      await client.db("sample").collection("people").insertOne({
        "id": i + 1,
        // generate a random address key
        "address": "address" + Math.floor(Math.random() * 1000000),
        // generate a random email address key
        "email": "email" + Math.floor(Math.random() * 1000000),
        // generate a random password key
        "password": "password" + Math.floor(Math.random() * 1000000),
        // generate a random name key
        "name": "name" + Math.floor(Math.random() * 1000000),
        // generate a random phone city key
        "phone": "phone" + Math.floor(Math.random() * 1000000),
        // generate a random city key
        "city": "city" + Math.floor(Math.random() * 1000000),
        // generate a random longitude
        "longitude": Math.floor(Math.random() * 1000000),
        // generate a random US state
        "state": "state" + Math.floor(Math.random() * 1000000),
        // generate a random latitude
        "latitude": Math.floor(Math.random() * 1000000),
        // generate a random source
        "source": "source" + Math.floor(Math.random() * 1000000),
        // generate a random birth date
        "birth_date": new Date(),
        // generate a random zip code
        "zip": Math.floor(Math.random() * 1000000),
        // generate a random created at date
        "created_at": new Date(),
        "description": randomString(65536),
        // "facts": {
        //   "key1": generateComplexBSON(),
        //   "key2": randomString(65536),
        //   "key3": randomString(65536),
        //   "key4": randomString(65536),
        //   "key5": randomString(65536),
        //   "key6": randomString(65536),
        //   "key7": randomString(65536),
        //   "key8": randomString(65536),
        //   "key9": randomString(65536),
        //   "key10": randomString(65536),
        //   "key11": randomString(65536),
        //   "key12": randomString(65536),
        //   "key13": randomString(65536),
        //   "key14": randomString(65536),
        //   "key15": randomString(65536),
        // },
        "tags": [
          randomString(65536),
          randomString(65536),
          randomString(65536),
          randomString(65536),
          randomString(65536),
          randomString(65536),
          randomString(65536),
          randomString(65536),
          randomString(65536),
          randomString(65536),
          randomString(65536),
        ],
        "complex": generateComplexBSON(),
            });
      console.log("Inserted " + i + " documents into the 'people' collection.");
    }
  } finally {
    // Ensures that the client will close when you finish/error
    await client.close();
  }
}
run().catch(console.dir);
```
(credits to chatgpt)

3) spin up Metabase and run it with -Xms512m -Xmx1530m, more memory is also fine, it will also blow up
4) Add the DB, it will crash with OOM

### Expected behavior

We should read documents more efficiently, I really don't know how, but there should be a way?

### Logs

```
2024-05-01 23:26:10,813 DEBUG middleware.log :: POST /api/database/4/sync_schema 200 29.1 ms (7 DB calls) App DB connections: 1/10 Jetty threads: 4/50 (6 idle, 0 queued) (70 total active threads) Queries in flight: 0 (0 queued)
2024-05-01 23:26:10,813 INFO sync.util :: STARTING: Sync metadata for mongo Database 4 ''mg''
2024-05-01 23:26:10,822 INFO sync.util :: STARTING: step ''sync-dbms-version'' for mongo Database 4 ''mg''
2024-05-01 23:26:10,823 INFO sync.util :: FINISHED: step ''sync-dbms-version'' for mongo Database 4 ''mg'' (1.1 ms)
2024-05-01 23:26:10,824 INFO sync.util :: STARTING: step ''sync-timezone'' for mongo Database 4 ''mg''
2024-05-01 23:26:10,824 INFO sync-metadata.sync-timezone :: :mongo database 4 default timezone is nil
2024-05-01 23:26:10,824 INFO sync.util :: FINISHED: step ''sync-timezone'' for mongo Database 4 ''mg'' (190.7 µs)
2024-05-01 23:26:10,824 INFO sync.util :: STARTING: step ''sync-tables'' for mongo Database 4 ''mg''
2024-05-01 23:26:10,829 INFO sync-metadata.tables :: Updating table metadata for Table 38 ''people''
2024-05-01 23:26:10,829 INFO sync.util :: FINISHED: step ''sync-tables'' for mongo Database 4 ''mg'' (5.0 ms)
2024-05-01 23:26:10,829 INFO sync.util :: STARTING: step ''sync-fields'' for mongo Database 4 ''mg''
Aborting due to java.lang.OutOfMemoryError: Java heap space
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (debug.cpp:339), pid=1, tid=268
#  fatal error: OutOfMemory encountered: Java heap space
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.22+7 (11.0.22+7) (build 11.0.22+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.22+7 (11.0.22+7, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to //core.1)
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log

```

### Information about your Metabase installation

```JSON
v49.7
```

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/42133

The big memory usage comes from the `mongo.util/do-find` method, which return a vector. We should use a lazy seq instead.

This is a regression and introduced by https://github.com/metabase/metabase/pull/38017

Here is a script to demonstrate memory usage before and after the changes.

```clojure
(require 
 '[toucan2.core :as t2]
 '[metabase.util.log :as log]
 '[metabase.sync.sync-metadata.fields :as sync.fields])

(def db (t2/select-one :model/Database :engine :mongo))

(future
 (def max-memory-usage (atom 0))
 (doseq [_ (range 100)]
   (let [memory-usage (float (/ (- (.. Runtime getRuntime totalMemory) (.. Runtime getRuntime freeMemory)) 1024 1024))]
     (swap! max-memory-usage max memory-usage)
     (log/info (format "Memory usage: %f MB, Max memory usage: %f MB" memory-usage @max-memory-usage)))
   (Thread/sleep 500)))

(do
  (log/info "Start")
  (sync.fields/sync-fields! db)
  (log/info "Done"))
```

Before:
```
2024-05-02 08:19:48,656 INFO local.mongo-oom-sync-fields :: Start
2024-05-02 08:19:48,982 INFO local.mongo-oom-sync-fields :: Memory usage: 1012.117493 MB, Max memory usage: 1404.911377 MB
2024-05-02 08:19:49,483 INFO local.mongo-oom-sync-fields :: Memory usage: 1901.464355 MB, Max memory usage: 1901.464355 MB
2024-05-02 08:19:49,986 INFO local.mongo-oom-sync-fields :: Memory usage: 2566.096924 MB, Max memory usage: 2566.096924 MB
2024-05-02 08:19:50,491 INFO local.mongo-oom-sync-fields :: Memory usage: 2572.239014 MB, Max memory usage: 2572.239014 MB
2024-05-02 08:19:50,993 INFO local.mongo-oom-sync-fields :: Memory usage: 2578.385010 MB, Max memory usage: 2578.385010 MB
2024-05-02 08:19:51,497 INFO local.mongo-oom-sync-fields :: Memory usage: 2584.527100 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:52,002 INFO local.mongo-oom-sync-fields :: Memory usage: 2409.627441 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:52,508 INFO local.mongo-oom-sync-fields :: Memory usage: 2415.769531 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:53,009 INFO local.mongo-oom-sync-fields :: Memory usage: 2421.915527 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:53,512 INFO local.mongo-oom-sync-fields :: Memory usage: 2428.057617 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:54,017 INFO local.mongo-oom-sync-fields :: Memory usage: 2434.203613 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:54,519 INFO local.mongo-oom-sync-fields :: Memory usage: 2440.345459 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:55,023 INFO local.mongo-oom-sync-fields :: Memory usage: 2446.491455 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:55,525 INFO local.mongo-oom-sync-fields :: Memory usage: 2452.633545 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:56,030 INFO local.mongo-oom-sync-fields :: Memory usage: 2458.779541 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:56,531 INFO local.mongo-oom-sync-fields :: Memory usage: 2464.921387 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:57,036 INFO local.mongo-oom-sync-fields :: Memory usage: 2471.067383 MB, Max memory usage: 2584.527100 MB
2024-05-02 08:19:57,323 INFO local.mongo-oom-sync-fields :: Done
```

After
```
2024-05-02 08:18:48,387 INFO local.mongo-oom-sync-fields :: Start
2024-05-02 08:18:48,656 INFO local.mongo-oom-sync-fields :: Memory usage: 1933.911987 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:49,157 INFO local.mongo-oom-sync-fields :: Memory usage: 891.292480 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:49,662 INFO local.mongo-oom-sync-fields :: Memory usage: 1117.596191 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:50,167 INFO local.mongo-oom-sync-fields :: Memory usage: 1250.718262 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:50,672 INFO local.mongo-oom-sync-fields :: Memory usage: 1478.044189 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:51,177 INFO local.mongo-oom-sync-fields :: Memory usage: 1705.374268 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:51,678 INFO local.mongo-oom-sync-fields :: Memory usage: 1932.700195 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:52,179 INFO local.mongo-oom-sync-fields :: Memory usage: 748.504089 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:52,681 INFO local.mongo-oom-sync-fields :: Memory usage: 975.960144 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:53,186 INFO local.mongo-oom-sync-fields :: Memory usage: 1158.104126 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:53,688 INFO local.mongo-oom-sync-fields :: Memory usage: 1385.434082 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:54,189 INFO local.mongo-oom-sync-fields :: Memory usage: 1612.760132 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:54,694 INFO local.mongo-oom-sync-fields :: Memory usage: 1745.882080 MB, Max memory usage: 1933.911987 MB
2024-05-02 08:18:55,200 INFO local.mongo-oom-sync-fields :: Memory usage: 1971.162109 MB, Max memory usage: 1971.162109 MB
2024-05-02 08:18:55,704 INFO local.mongo-oom-sync-fields :: Memory usage: 847.578308 MB, Max memory usage: 1971.162109 MB
2024-05-02 08:18:56,205 INFO local.mongo-oom-sync-fields :: Memory usage: 1042.651367 MB, Max memory usage: 1971.162109 MB
2024-05-02 08:18:56,710 INFO local.mongo-oom-sync-fields :: Memory usage: 1208.026245 MB, Max memory usage: 1971.162109 MB
2024-05-02 08:18:57,215 INFO local.mongo-oom-sync-fields :: Memory usage: 1435.356323 MB, Max memory usage: 1971.162109 MB
2024-05-02 08:18:57,518 INFO local.mongo-oom-sync-fields :: Done
```

You can see that using lazy seq the memory usage barely increases at all.

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo/util.clj [hunk 1]
```diff
@@ -70,7 +70,7 @@
          skip (.skip skip)
          batch-size (.batchSize (int batch-size))
          sort-criteria (.sort (mongo.conversion/to-document (ordered-map/ordered-map sort-criteria))))
-       (mapv #(mongo.conversion/from-document % opts))))
+       (map #(mongo.conversion/from-document % opts))))
```
Comment (qnkhuat) [inline modules/drivers/mongo/src/metabase/driver/mongo/util.clj:73]: there are more places here that use `mapv`. My gut says we should convert them all. Should we? @lbrdnk

File: modules/drivers/mongo/test/metabase/driver/mongo/util_test.clj
Comment (qnkhuat) [inline modules/drivers/mongo/test/metabase/driver/mongo/util_test.clj:1]: I noticed we don't have any behavior test here. I can add it later if we want to. but this PR should fix the escalation only.

File: modules/drivers/mongo/src/metabase/driver/mongo/util.clj (hunk 1 above)
Comment (lbrdnk) [reply modules/drivers/mongo/src/metabase/driver/mongo/util.clj:73]: I'll open tech debt issue tracking this.

**Review by lbrdnk — APPROVED** [review]
LGTM.

File: modules/drivers/mongo/test/metabase/driver/mongo/util_test.clj [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+   [metabase.driver.mongo.connection :as mongo.connection]
+   [metabase.driver.mongo.util :as mongo.util]
+   [metabase.test :as mt]))
+
+(deftest do-find-returns-lazy-seq-test
+  (mt/test-driver :mongo
+    (testing "do-find returns a lazy seq #42133"
+      (mongo.connection/with-mongo-database [db (mt/db)]
+        (is (= clojure.lang.LazySeq
+               (type (mongo.util/do-find (mongo.util/collection db "venues")))))))))
```
Comment (crisptrutski) [inline modules/drivers/mongo/test/metabase/driver/mongo/util_test.clj:13]: Rather than coding to a concrete type, and assuming that it hasn't been realized, you could instead assert that `realized?` is false.

Comment (qnkhuat) [reply modules/drivers/mongo/test/metabase/driver/mongo/util_test.clj:13]: oh yea that'd be nicer.
