### PR TITLE
Cache dashboard parameter values

### LINKED ISSUE #16103: Filter dropdown sends request for values every time widget is opened
**Describe the bug**
From https://github.com/metabase/metabase/pull/15943#pullrequestreview-654993149 - continuation of #13832
When a dashboard has a "A list of all values" filter, every time the dropdown is opened, then it makes a request for values.

**To Reproduce**
1. Simple question > Sample Dataset > People - save as "Q1" to dashboard
2. On dashboard add a category filter and connect to "Q1".Source - save dashboard
3. Refresh the dashboard and click filter widget to open - every click will make a request to get values like this:
```
GET /api/dashboard/:id/params/:paramid/values 200
```

**Expected behavior**
This should probably **not** be fixed until #15977 is fixed, since it could otherwise create a Correctness issue.

The first request is understandable, but subsequent clicks on the dropdown should have stored the results from the first request.
This might be slightly more difficult to do Linked Filters.

**Information about your Metabase Installation:**
Testing commit `aad24de` (almost 0.39.2)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by daltojohnso**
Resolves #16103 

Some basic caching for parameter widget values. I'm creating a key out of the args we pass to the two endpoints we use and using it to store results in redux. The cache is totally cleared when a dashboard is visited (the `INITIALIZE` action) and when a dashboard is saved (the `SAVE_DASHBOARD_AND_CARDS` action).

**Testing**
1. Create a dashboard, add some parameters, map the parameters to card. Open a parameter widget that is mapped to a field that lists values and it should only send a single request for the values list, even if you close it. Once you navigate off the page and back, it should refetch. If you save the dashboard for any reason it should refetch.
2. Test a parameter that is mapped to a field where you must search for values. Repeat the above steps.
3. Test a parameter that has been filtered by another parameter (in the parameters sidebar there's a linked filters tab -- use that to set this up) and make sure that the works and that the parameter is correctly cached using filtering parameter values.
4. Any other ideas to mess up the cache and cause problems

https://user-images.githubusercontent.com/13057258/147375462-94c681ad-909e-47a9-b7d8-5e38ab47268d.mov

Cache is cleared on re-entry

https://user-images.githubusercontent.com/13057258/147375482-3dab3609-2422-42cd-ae40-2926c17a2eb3.mov

Cache is cleared when the dashboard is saved

https://user-images.githubusercontent.com/13057258/147375488-34336b8c-d81b-47e4-9596-5e7c2da0f671.mov

### CODE REVIEW

**Review by guilhermerenew-zz — APPROVED** [review]

File: frontend/src/metabase/parameters/utils/dashboards.js [hunk 1]
```diff
@@ -204,3 +204,29 @@ export function hasMatchingParameters({
...
+export function getParameterValuesSearchKey({
+  dashboardId,
+  parameterId,
+  query = null,
+  filteringParameterValues = {},
+}) {
+  const sortedParameterValues = _.sortBy(
+    Object.entries(filteringParameterValues),
+    "0",
+  );
```
Comment (kulyk) [inline frontend/src/metabase/parameters/utils/dashboards.js:228]: Not sure I follow what does sorting by `"0"` means here. Does it sort an entries list by a parameter ID (first entry element)? I'm thinking if it'd make it easier to read if we define a constant / add a comment explaining what's happening. Something like:

```js
const BY_PARAMETER_ID = "0"
const sortedParameterValues = _.sortBy(
  Object.entries(filteringParameterValues),
  BY_PARAMETER_ID,
);
```

**Review by kulyk — APPROVED** [review]
The code looks good and it works great 👍

File: frontend/src/metabase/parameters/utils/dashboards.js (hunk 1 above)
Comment (daltojohnso) [reply frontend/src/metabase/parameters/utils/dashboards.js]: Good idea -- added that const + a comment explaining the sort
