### PR TITLE
Format zero-arity functions with parens

### LINKED ISSUE #55300: Column named Count is mishandled in aggregation expression editor when creating new metric
### Describe the bug

Column named `Count` can not be referenced in custom aggregation expression.

### To Reproduce

1. Use `daily-bird-counts` dataset.
2. Create a new metric.
3. Set the aggregation to custom expression `Count + [Count]`.
4. Re-open aggregation's custom expression editor.
5. Expression that is present is missing brackets: `Count + Count`.

### Expected behavior

Column named `Count` should be referencable in top level of aggregation expression. Alternatively failure should be noticeable.

### Logs

_No response_

### Information about your Metabase installation

```JSON
today's master: `cc9b45c6dd7189211684c8955e819946a823b8cc`.
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/55300

Solves https://metaboat.slack.com/archives/C0645JP1W81/p1744838902050439

This PR reduces the ambiguity of what an identifier in the Custom Expression is refering too by making non-argument functions render with empty parens, ie. `now()` instead of `now`.

### To verify
1. New -> Question -> Sample Database -> Orders
2. Custom column
3. Type `now` and accept the completion.
4. The editor should contain `now()`
5. Format the expression
6. The editor should still contain `now()`

### CODE REVIEW

File: frontend/src/metabase-lib/v1/expressions/complete/util.ts [hunk 1]
```diff
@@ -49,27 +49,21 @@ export function expressionClauseCompletion(
...
-
 function getSnippet(helpText: HelpText) {
   const args = helpText.args
     ?.filter((arg) => arg.name !== "…")
     ?.map((arg) => "${" + (arg.template ?? arg.name) + "}")
     .join(", ");
 
   if (!args || args.length < 1) {
-    return `${helpText.structure}`;
+    return `${helpText.structure}()`;
```
Comment (ranquild) [inline frontend/src/metabase-lib/v1/expressions/complete/util.ts:66]: should the `structure` include `()`?

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase-lib/v1/expressions/complete/util.ts (hunk 1 above)
Comment (romeovs) [reply frontend/src/metabase-lib/v1/expressions/complete/util.ts:66]: No AFAICT, `structure` contains just the name as it is printed in the expression.

It is the same as `displayName` in `config.ts`. 
I would like to merge `helper-text-strings.ts` and `config.ts` in the future to remove this duplication.

**Comment by romeovs** [comment]
@metabase/tech-writers are there id other documentation or examples you can think of that I should change?
