### PR TITLE
fix: allow password reset if google sso disabled

### LINKED ISSUE #46634: Disabling Google SSO Locks out Previously Provisioned SSO Users
### Describe the bug

If an SSO account is provisioned externally and password authentication is enabled for the instance - the SSO user nor the admin can initiate a password reset to allow the user to begin using password auth. The reset email indicates that a password can't be set because the user has an SSO account.

### To Reproduce

1. Set up Google SSO such that users are provisioned when the account is created
2. Log in as a user
3. Enabled password auth on the instance
4. Try to initiate a pw reset for the provisioned user
5. See that the email indicates that the user should contact the admin for help setting a password

### Expected behavior
If an admin disables Google Auth then password reset functionality should work for the users provisions via SSO.

A point of confusion: docs indicate that enabling password auth applies to all users but this isn't the case:
https://www.metabase.com/docs/latest/people-and-groups/authenticating-with-jwt#disabling-password-logins

### Logs

_No response_

### Information about your Metabase installation

```JSON
v49
```

### Severity

annoying

### Additional context

Currently, when admins want to disable Google SSO & enable password auth they have to hack the core-user table to remove the "sso_auth" indicator. Otherwise password resets will not work.

### PR DESCRIPTION
**Pull request by edpaget**
Closes https://github.com/metabase/metabase/issues/46634

### Description

We want to allow metabase users whose admins have first had google sso enabled and then have disabled to be able to use the reset password link to regain access to the metabase instance. This does not apply to any other supported SSO system.

This works by checking if a user was created through google sso and that no other sso options are enabled and then checks if google sso is still enabled. If All those are true then we allow the user to reset their password. This is supposed to be very conservative since we want to generally prevent password resets of SSO account so administrators can fully control how users access metabase instances. 

### How to verify

1. Setup an instance with google SSO
2. create a user by signing on with google
3. disable google sso
4. use forgot password to send a password reset to that user
5. sign in

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/channel/email/messages.clj [hunk 1]
```diff
@@ -120,7 +120,7 @@
   [email sso-source password-reset-url is-active?]
   {:pre [(u/email? email)
          ((some-fn string? nil?) password-reset-url)]}
-  (let [google-sso? (= "google" sso-source)
```
Comment (johnswanson) [inline src/metabase/channel/email/messages.clj:123]: Looks like this is fixing an old bug right? We transformed `:sso_source` to a keyword but didn't change this?

File: src/metabase/session/api.clj [hunk 2]
```diff
@@ -170,12 +178,14 @@
...
-      (if (some? sso-source)
-        ;; If user uses any SSO method to log in, no need to generate a reset token
+      (if (password-reset-disabled? sso-source)
+        ;; If user uses any SSO method to log in, no need to generate a reset token. Some cases for Google SSO
+        ;; are exempted see `password-reset-allowed?`
         (messages/send-password-reset-email! email sso-source nil is-active?)
         (let [reset-token        (user/set-password-reset-token! user-id)
               password-reset-url (str (public-settings/site-url) "/auth/reset_password/" reset-token)]
           (log/info password-reset-url)
+
```
Comment (johnswanson) [inline src/metabase/session/api.clj:188]: Nit: [blank line](https://guide.clojure.style/#no-blank-lines-within-def-forms)

**Review by johnswanson — APPROVED** [review]
Awesome, looks good! One linty nit.

File: src/metabase/channel/email/messages.clj (hunk 1 above)
Comment (edpaget) [reply src/metabase/channel/email/messages.clj:123]: yeah this was a pre-existing bug, just noticed when I wrote tests I was getting the generic SSO email, but it looks like this change might have broken some other test so I'll check that out.
