### PR TITLE
Block database routing when transforms already exist

### LINKED ISSUE #71891: Block database routing when transforms already exist
## Description of the bug

Enabling database routing is allowed when a database already has at least one transform. This should be prevented.

## Reproduction steps

1. Use a database that already has at least one transform.
2. Enable database routing.

## Expected behavior

Enabling database routing should be blocked when the database already has at least one transform.

## Logs

No logs were provided.

## Diagnostic information (including Metabase version)

Metabase version was not provided.

## Severity

P1

### PR DESCRIPTION
**Pull request by ericnormand**
closes #71891
## Summary
- Prevent enabling database routing on a database that already has transforms, since running transforms on databases with DB routing is not supported
- Backend: added validation check in `PUT /api/ee/database-routing/router-database/:id` that returns 400 if transforms exist for the database
- Frontend: disables the routing toggle in the UI when transforms exist, with a descriptive message
- Also wired through the existing but unused `database-id` filter param in the transforms list API

## Test plan
- [x] Backend test added and passing: `cannot-enable-db-routing-when-other-features-enabled`
- [x] Verify toggle is disabled in the UI when a database has transforms
- [x] Verify enabling routing via API returns 400 when transforms exist
- [x] Verify routing can still be enabled when no transforms exist

Fixes GIT-9695

### CODE REVIEW

File: enterprise/frontend/src/metabase-enterprise/database_routing/DatabaseRoutingSection/DatabaseRoutingSection.tsx [hunk 1]
```diff
@@ -81,7 +85,14 @@ export const DatabaseRoutingSection = ({
   const userAttributeOptions =
     userAttrsReq.data ?? (userAttribute ? [userAttribute] : []);
 
-  const disabledFeatMsg = getDisabledFeatureMessage(database);
+  const transformsReq = useListTransformsQuery(
```
Comment (ranquild) [inline enterprise/frontend/src/metabase-enterprise/database_routing/DatabaseRoutingSection/DatabaseRoutingSection.tsx]: nitpick

```
const transformsQuery = ...
const transforms = transformsQuery.data ?? [];
const hasTransforms = transforms.length > 0;
```

**Review by ranquild — APPROVED** [review]

**Review by galdre — APPROVED** [review]
