### PR TITLE
Fix - Custom expression that has a name consisting only of whitespace breaks the question

### LINKED ISSUE #32571: Custom expression that has a name consisting only of whitespace breaks the question
### Describe the bug

If you name a custom expression with just an space, it will break the question as the query processor is expecting a non-blank string

### To Reproduce

1) create a GUI question. E.g Orders -> group by -> custom expression: "CountIf([Quantity] > 1) / SumIf([Total], [Product → Category] = "Gizmo")" . The name of the custom grouping: just a space char " " (without the double quotes)
2) run it and see
```
Input to resolve-card-id-source-tables* does not match schema: 

	 [0;33m  [(named {:query {:aggregation [[nil nil (named {:name (not ("Non-blank string" " ")), :display-name (not ("Non-blank string" " "))} "options")]]}} arg0)] [0m 
```

### Expected behavior

We shouldn't allow spaces as names

### Logs

NA

### Information about your Metabase installation

```JSON
pretty sure it's been since forever
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ibedwi**
Closes https://github.com/metabase/metabase/issues/32571

### Description

The custom expression that has a name with a space breaks the question. We disallowed the 'space' character using 2 approaches:

1. The user can't type space
2. We'll remove any space characters if the user paste any string with spaces.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. create a GUI question. E.g Orders -> group by -> custom expression: "CountIf([Quantity] > 1) / SumIf([Total], [Product → Category] = "Gizmo")" . The name of the custom grouping: just a space char " " (without the double quotes)

2. Try to type space in the custom expression name.
3. Try to copy string which contain spaces.

### Demo

https://www.loom.com/share/b2cddf8644f847f09df5c96a987afb39?sid=68c0e47e-98a0-4efa-ad4b-44f9b28d5c0e

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by paoliniluis** [comment]
Thanks! Will you be able to add any tests to the PR?

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx [hunk 1]
```diff
@@ -124,11 +124,24 @@ export const ExpressionWidget = (props: ExpressionWidgetProps): JSX.Element => {
...
+                setName(event.target.value);
+              }
+            }}
             onKeyPress={e => {
               if (e.key === "Enter") {
                 handleCommit(expression);
               }
+              // Prevent the user to type spaces since the expression's name
+              // can't contain spaces.
+              if (e.key === " " || e.key === "Spacebar") {
```
Comment (uladzimirdev) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx:142]: `key === " "` should be enough

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx [hunk 2]
```diff
@@ -124,11 +124,24 @@ export const ExpressionWidget = (props: ExpressionWidgetProps): JSX.Element => {
...
-            onChange={event => setName(event.target.value)}
+            onChange={event => {
+              // The expression's name shouldn't contain spaces. This checks
+              // handles if the user pastes a name with spaces.
+              if (event.target.value.includes(" ")) {
+                setName(event.target.value.replace(/\s/g, ""));
+              } else {
+                setName(event.target.value);
+              }
+            }}
```
Comment (uladzimirdev) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx:135]: I believe it should do the trick

```suggestion
            onChange={event => setName(event.target.value.replace(/\s/g, "")}
```

**Review by uladzimirdev — COMMENTED** [review]
Please add tests

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx (hunk 2 above)
Comment (ibedwi) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx]: You're right! The check is not necessary

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx [hunk 3]
```diff
@@ -109,17 +109,38 @@ describe("ExpressionWidget", () => {
...
+
+      userEvent.click(doneButton);
+
+      // Pasted text must be added to the previous name
+      // and its spaces must be removed
+      expect(onChangeExpression).toHaveBeenCalledTimes(2);
+      expect(onChangeExpression).toHaveBeenCalledWith(
+        "Somen_am!efor-expression_123!@#$%^&*()Zxcbyutadded-anotherpastedtext",
+        expression,
+      );
```
Comment (ibedwi) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx:143]: Added test for typing and pasting text with some characters and spaces to the "name" input. For both cases, the as long as the `space`s are removed then it should be a valid name.

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx [hunk 4]
```diff
@@ -124,11 +124,16 @@ export const ExpressionWidget = (props: ExpressionWidgetProps): JSX.Element => {
             value={name}
             placeholder={t`Something nice and descriptive`}
             fullWidth
-            onChange={event => setName(event.target.value)}
+            onChange={event => setName(event.target.value.replace(/\s/g, ""))}
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx:127]: The issue is there when the name consists only of whitespace characters.
Names such as `My awesome metric` must not be disallowed.

**Review by kamilmielnik — CHANGES_REQUESTED** [review]
I think the right way to address this issue is to disable the "Update" button in the form if expression name consists only of whitespace characters.

image

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx (hunk 4 above)
Comment (ibedwi) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx]: Apologize. I've revert my changes and checked whether the name is consist of space only. I've also update the test. Thanks for your feedback! @kamilmielnik

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx [hunk 5]
```diff
@@ -63,7 +63,8 @@ export const ExpressionWidget = (props: ExpressionWidgetProps): JSX.Element => {
 
   const helpTextTargetRef = useRef(null);
 
-  const isValidName = withName ? !!name : true;
+  const isOnlySpaces = (str: string) => /^\s*$/.test(str);
+  const isValidName = withName ? !!name && !isOnlySpaces(name) : true;
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx:67]: 1. This can be done without regexp and without the function
2. The `!!name` part is no longer necessary

```suggestion
  const isValidName = withName ? name.trim().length > 0 : true;
```

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx [hunk 6]
```diff
@@ -109,17 +112,26 @@ describe("ExpressionWidget", () => {
       // enter in expression editor should not trigger "onChangeExpression" as popover is not valid with empty "name"
       expect(onChangeExpression).toHaveBeenCalledTimes(0);
 
+      // The name must not be empty and must not consist of spaces only.
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx:115]: > The name must not be empty

1. Assertion for empty name is missing.

> must not consist of spaces only.

2. The logic isn't only about spaces but about all whitespace characters. Let's assert some tab characters as well and update the comment.

**Review by kamilmielnik — COMMENTED** [review]
Thanks for updating the approach!
Just few more things and it will be ready to merged :rocket:

**Review by kamilmielnik — APPROVED** [review]

**Comment by kamilmielnik** [comment]
I updated the PR title to match the new approach.

All checks pass: #35347. Merging.

**Comment by kamilmielnik** [comment]
Thank you @ibedwi for another contribution! :rocket:
