### PR TITLE
Fix filters with `is-null` and `not-null` operators crashing the QB

### LINKED ISSUE #41783: Clicking existing filter breaks question based on model
### Describe the bug

- crashed frontend in `master` when attempting to update a filter

### To Reproduce

1. Go to https://stats.metabase.com/model/6759-ticket
2. Filter on Assignee Name is null
image

3. Click filter pill button
image

4. Frontend crashes
image

### Expected behavior

_No response_

### Logs

image

Diagnostics available here:
- https://drive.google.com/file/d/1JCMfeXUrg3555ST9ContgEtbgPqbcLDG/view?usp=drive_link

### Information about your Metabase installation

```JSON
- Metabase `master` as of `9e9e310`
```

### Severity

P1: Regression, Common functionality broken

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/41783

We forgot to handle `is-null` and `not-null` string operators. The UI doesn't suggest them usually but it's possible to create such filters via drills.

How to verify:
- CI is green, new tests pass

### CODE REVIEW

File: frontend/src/metabase/querying/hooks/use-string-filter/constants.ts [hunk 1]
```diff
@@ -1,6 +1,11 @@
+import type * as Lib from "metabase-lib";
+
 import type { OperatorOption } from "./types";
 
-export const OPERATOR_OPTIONS: Record<string, OperatorOption> = {
+export const OPERATOR_OPTIONS: Record<
```
Comment (ranquild) [inline frontend/src/metabase/querying/hooks/use-string-filter/constants.ts:5]: Basically, use TypeScript to catch errors like this :(

**Review by alxnddr — APPROVED** [review]
