### PR TITLE
Keep NFC root fields in nested queries (#29184)

### LINKED ISSUE #29184: Question query fails using unfolded JSON fields in custom expressions, and selecting subset of fields
**Describe the bug**
When selecting a subset of fields, and a custom expression that uses a field from an unfolded JSON column, a query in the notebook editor fails with `Unknown column 'source.<json_field_name>' in 'field list'`

Tested on MySQL and Postgres databases. It works on 0.45.3.

**To Reproduce**
1. Create a table with JSON columns in MySQL or Postgres. For Postgres:
```
DROP TABLE IF EXISTS test_table;
CREATE TABLE IF NOT EXISTS test_table (
  id int,
  name varchar(255),
  settings json,
  PRIMARY KEY (id)
);

INSERT INTO test_table (id, name, settings) VALUES
  (1, 'test1', '{"0": {"1": "1v", 
                      "2": "2v"}}'),
  (2, 'test2', '{"0": {"1": "1v",
                      "2": "2v"}}');
```
2. Make sure JSON unfolding is enabled in the connection settings for the database (it should be by default). Sync the database. 
3. Create a new question from the test table with the notebook editor.
4. Select a subset of columns. If you don't select a subset, the error doesn't happen.
image
5. Add a custom expression that uses one of the unfolded fields from the JSON column.
image
6. Run the query and observe the error:
image

**Expected behavior**
The query should run without error.

**Information about your Metabase Installation:**
Tested on master (3e636378) which doesn't work
Tested 0.45.3 and it works

Related to https://github.com/metabase/metabase/issues/29188

### PR DESCRIPTION
**Pull request by metamben**
Fixes #29184.

The problem with NFC fields in nested queries is that the outer query doesn't simply take the value "exported" by the nested query, but tries to recalculate it from the root field. The real fix would be for the outer query to rely on the unfolded field, but that's quite a challenge involving risks. Instead of this, we just keep references to the fields from the same table and with the name of the root field of the nested field column.

### CODE REVIEW

File: src/metabase/query_processor/util/nest_query.clj [hunk 1]
```diff
@@ -35,11 +35,25 @@
 (defn- keep-source+alias-props [field]
   (update field 2 select-keys [::add/source-alias ::add/source-table :join-alias]))
 
+(defn- nfc-root [[_ field-id]]
+  (when-let [field (and (int? field-id) (qp.store/field field-id))]
+    (when-let [nfc-root (first (:nfc_path field))]
+      {:table_id (:table_id field)
+       :name nfc-root})))
+
+(defn- field-props [[_ field-id]]
```
Comment (metamben) [inline src/metabase/query_processor/util/nest_query.clj:44]: I'm thinking about a better name.

**Review by calherries — APPROVED** [review]
LGTM
