### PR TITLE
Fix - Search results has a box with scrollbars

### LINKED ISSUE #28788: Search results has a box with scrollbars
**Describe the bug**
Seems like descriptions of questions make the results box bigger than usual, resulting horizontal scrollbars
image

**Logs**
NA

**To Reproduce**
Search for "field filters" in our Metabase instance

**Expected behavior**
resize the search results box?

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Metabase version: master

**Severity**
P3

**Additional context**
NA

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #28788

### Description

I found an additional case to the original report - the overflow also occurred if a question belonged to a collection with a long name. This is included in test data.
I reported #32140 for markdown separately.

### How to verify

1. Create a collection with a very long name, ideally with also a very long word that's wider than the dropdown.
2. Create a question with very long name & description, as above.
3. Add this question to that collection.
4. Search for this question

The search dropdown should not overflow horizontally.
Horizontal scrollbar should not be shown in it.

### Before

image

### After

image

### CODE REVIEW

File: e2e/support/properties/scrollbars.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
+chai.Assertion.addProperty("scrollableHorizontally", function () {
```
Comment (kamilmielnik) [inline e2e/support/properties/scrollbars.js:1]: > Perhaps we need to extract this helper. I'll remember it next time we need it.

[Following up](https://github.com/metabase/metabase/pull/32119#discussion_r1252690036) and making this reusable.

File: frontend/src/metabase/search/components/SearchResult.styled.tsx [hunk 2]
```diff
@@ -137,6 +137,7 @@ const resultStyles = ({ compact, active, isSelected }: ResultStylesProps) => `
 export const ResultLinkContent = styled.div`
   display: flex;
   align-items: start;
+  overflow-wrap: anywhere;
```
Comment (ranquild) [inline frontend/src/metabase/search/components/SearchResult.styled.tsx:140]: Any reason not to use `break-word`?

File: e2e/support/properties/scrollbars.js (hunk 1 above)
Comment (ranquild) [reply e2e/support/properties/scrollbars.js:1]: I don't think that extending `chai` with non-standard methods is a good idea. This is hard to reason about. Can this functions be extracted as regular ones? We have many e2e helpers available, and we could add them here.

**Review by ranquild — CHANGES_REQUESTED** [review]
Comments inline

File: e2e/support/properties/scrollbars.js (hunk 1 above)
Comment (kamilmielnik) [reply e2e/support/properties/scrollbars.js:1]: > I don't think that extending chai with non-standard methods is a good idea.

I disagree. It reads really easily in tests (`expect(element).to.be.scrollableHorizontally`) and its definition is easily searchable.

>  This is hard to reason about.

Are custom cypress commands not as hard to reason about?

> We have many e2e helpers available, and we could add them here.

The reason I didn't add them there because there are no generic helpers with assertions. There are only 5 _specific_ helpers with assertions - it does not look like a pattern.

It feels like custom assertions belong somewhere else. [Cypress docs guided](https://docs.cypress.io/guides/references/assertions#Adding-New-Assertions) me to this.

Comment (ranquild) [reply e2e/support/properties/scrollbars.js:1]: We avoid adding new custom cypress commands too

**Review by ranquild — CHANGES_REQUESTED** [review]
Comments inline

File: e2e/support/properties/scrollbars.js (hunk 1 above)
Comment (kamilmielnik) [reply e2e/support/properties/scrollbars.js]: Refactored to simple functions: 68b57e21e81e4086c20b8b573aab707777450533

**Review by deniskaber — APPROVED** [review]

**Review by ranquild — APPROVED** [review]
