### PR TITLE
Always pass param values as an array if param is only connected with fields

### LINKED ISSUE #11911: Dashboard filter using boolean value sends string on browser reload
**Describe the bug**
When connecting a dashboard category filter to a boolean column, it only works via the widget. If visiting the dashboard URL or refreshing the dashboard (with the filter set to true/false), sends the `true`/`false` as string.

**Logs**
When visiting the URL or refreshing `/dashboard/172?boolean=false`
```
[6c693206-f2f1-47a6-8450-f804282c1390] 2020-02-13T23:23:37+01:00 WARN metabase.query-processor.middleware.process-userland-query Query failure {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "No matching signature for operator = for argument types: BOOL, STRING. Supported signatures: ANY = ANY at [2:117]",
 :stacktrace
 ("--> driver.google$execute_no_auto_retry.invokeStatic(google.clj:39)"
  "driver.google$execute_no_auto_retry.invoke(google.clj:32)"
  "driver.google$execute$fn__1663.invoke(google.clj:50)"
  "util$do_with_auto_retries.invokeStatic(util.clj:397)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "util$do_with_auto_retries.invokeStatic(util.clj:401)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "util$do_with_auto_retries.invokeStatic(util.clj:401)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "driver.google$execute.invokeStatic(google.clj:49)"
  "driver.google$execute.invoke(google.clj:43)"
  "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:202)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:191)"
  "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:193)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:191)"
  "driver.bigquery$process_native_STAR_$fn__2490.invoke(bigquery.clj:209)"
  "util$do_with_auto_retries.invokeStatic(util.clj:397)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "util$do_with_auto_retries.invokeStatic(util.clj:401)"
  "util$do_with_auto_retries.invoke(util.clj:389)"
  "driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:208)"
  "driver.bigquery$process_native_STAR_.invoke(bigquery.clj:204)"
  "driver.bigquery$eval2494$fn__2496.invoke(bigquery.clj:224)"
  "query_processor$fn__46282$execute_query__46287$fn__46288.invoke(query_processor.clj:69)"
  "query_processor$fn__46282$execute_query__46287.invoke(query_processor.clj:64)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__37469.invoke(mbql_to_native.clj:40)"
  "query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__40576.invoke(annotate.clj:541)"
  "query_processor.middleware.annotate$add_column_info$fn__40482.invoke(annotate.clj:485)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__41516.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__43373.invoke(resolve_joins.clj:184)"
  "query_processor.middleware.limit$limit$fn__42151.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46142.invoke(results_metadata.clj:87)"
  "query_processor.middleware.format_rows$format_rows$fn__42139.invoke(format_rows.clj:76)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38229.invoke(add_dimension_projections.clj:234)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__38880.invoke(add_source_metadata.clj:107)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__43423.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__38717.invoke(add_row_count_and_status.clj:16)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__41591.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__43037.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.store$initialize_store$fn__46167$fn__46168.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__46167.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__37380.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__40633.invoke(async_wait.clj:89)"),
 :query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:userland-query? true},
  :info
  {:executed-by 44,
   :context :question,
   :card-id 1042,
   :dashboard-id nil,
   :query-hash [-100, -74, 83, -75, -125, 92, 37, -58, -8, -31, 68, -30, -68, 74, -101, 108, -6, 112, -51, 85, -99, -43, 82, 124, 96, 109, 2, 55, -104, -28, -87, -78]},
  :query {:source-table 7707},
  :parameters [{:type "category", :target ["dimension" ["field-id" 284395]], :value "false"}],
  :async? true,
  :cache-ttl 41},
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:userland-query? true},
  :info
  {:executed-by 44,
   :context :question,
   :card-id 1042,
   :query-hash [-100, -74, 83, -75, -125, 92, 37, -58, -8, -31, 68, -30, -68, 74, -101, 108, -6, 112, -51, 85, -99, -43, 82, 124, 96, 109, 2, 55, -104, -28, -87, -78]},
  :preprocessing-level 1,
  :database 32,
  :query
  {:source-table 7707,
   :filter [:= [:field-id 284395] [:value "false" {:base_type :type/Boolean, :special_type :type/Category, :database_type "BOOLEAN"}]],
   :fields [[:field-id 284396] [:field-id 284395]],
   :limit 2000},
  :cache-ttl 41},
 :native
 {:query "SELECT `dacort.bool_test`.`name` AS `name`, `dacort.bool_test`.`is_cool` AS `is_cool` FROM `dacort.bool_test` WHERE `dacort.bool_test`.`is_cool` = 'false' LIMIT 2000",
  :table-name "bool_test",
  :mbql? true},
 :ex-data
 {"code" 400,
  "errors"
  [{"domain" "global", "location" "q", "locationType" "parameter", "message" "No matching signature for operator = for argument types: BOOL, STRING. Supported signatures: ANY = ANY at [2:117]", "reason" "invalidQuery"}],
  "message" "No matching signature for operator = for argument types: BOOL, STRING. Supported signatures: ANY = ANY at [2:117]",
  "status" "INVALID_ARGUMENT"}}
```

**To Reproduce**
1. Create a Simple question on a table with boolean values
2. Add question to a dashboard
3. Add Category filter and connect to question
4. Click filter and select "False" - it shows all the rows with `false` boolean column
5. Refresh browser or copy URL to new tab, it will display error-card and the log will contain full error.
When checking the request, it's sending an array (`"value":[false]`) when using the widget, but a string (`"value":"false"`) when visiting/reloading the URL.

**Information about your Metabase Installation:**
stats instance and 1.34.2 - only tested with BigQuery

**Additional context**
This is very likely a duplicate of #11883 - or very related.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #11911 

The bug occurred because FieldValuesWidget would pass `[false]` as the parameter value, but when parsing from a query param we would pass `false`. This is the issue that @walterl mentioned [here](https://github.com/metabase/metabase/pull/12083#pullrequestreview-371530451). To fix, I check whether we're going to use FieldValuesWidget (if `hasOnlyFieldTargets`) and if so wrap single values in arrays.

The test doesn't actually cover the error case. We don't have any boolean columns to test this specific quirk, but I thought this was a good place to add more a general query param test.

### CODE REVIEW

File: frontend/src/metabase/meta/types/Parameter.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ export type Parameter = {
   slug: string,
   default?: string,
   field_ids?: FieldId[],
-
+  hasOnlyFieldTargets?: boolean,
```
Comment (tlrobinson) [inline frontend/src/metabase/meta/types/Parameter.js]: Mind adding a comment about what this means?

**Review by tlrobinson — APPROVED** [review]
