### PR TITLE
Ignore unknown columns when reverting cards and dashboards

### LINKED ISSUE #31901: Reverting a question to a revision prior to Metabase upgrade 0.46 does not work
### Describe the bug

We recently upgraded our Metabase instance from `v0.45.2` to `v0.46.4` and are unable to revert some questions to older versions since then. When clicking on the "Revert to this version" button in the frontend, nothing seems to be happening. Inspecting the server logs reveals that there is an exception, which essentially says:
```
ERROR: column "is_write" of relation "report_card" does not exist
```
This leads me to believe it has something to do with the huge PR #27413 where I think this column has been removed.

### To Reproduce

It's currently pretty difficult for me to actually test this, but I would assume these steps would reproduce the behavior:

1. Install Metabase <0.46
2. Create a question
3. Upgrade to >0.46
4. Edit that question
5. Attempt to roll back to the previous version

### Expected behavior

The rollback should work

### Logs

If needed, I can attempt to sanitize and share the full stack trace

### Information about your Metabase installation

```JSON
self-hosted `v0.46.4` in docker on kubernetes using a Postgres database
```

### Severity

Annyoing, since we cannot roll back, but manual reverts should be possible

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
When reverting cards and dashboards, ignores columns that are present in the revision but don't exist on the actual model. This should solve cases where a field is dropped between versions and makes a revision incompatible.

I've done this by first selecting the existing instance that we're reverting (via table name rather than toucan model) and getting the set of keys that are present. Then we simply ignore any fields that aren't part of that set.

I've also added a test case for this, and did some clean up of old toucan model references (i.e. `Card` -> `:model/Card`).

Note: this is _not_ a comprehensive fix for cross-version revisions. There only handles cases where columns are dropped, but other types of schema changes could also break revisions. So we still need to add better error handling for cases that aren't covered. 

Resolves https://github.com/metabase/metabase/issues/31901

I've filed https://github.com/metabase/metabasea/issues/45070 as a lower-priority follow-up to surface error messages better in revisions.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#45067** <a href="https://app.graphite.dev/github/pr/metabase/metabase/45067?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: src/metabase/models/revision.clj [hunk 1]
```diff
@@ -36,7 +36,9 @@
 
 (defmethod revert-to-revision! :default
   [model id _user-id serialized-instance]
-  (t2/update! model id serialized-instance))
+  (let [valid-columns   (keys (t2/select-one (t2/table-name model) :id id))
+        revert-instance (select-keys serialized-instance valid-columns)]
+    (t2/update! model id revert-instance)))
```
Comment (escherize) [inline src/metabase/models/revision.clj:41]: Looks good. Do you think a comment here about why we're doing that, and what other errors can happen makes sense here?

**Review by escherize — APPROVED** [review]
Thanks, looks great! I just have a nit about potentially adding a comment.

I am tired of the Card style model references, so thanks for removing those too! 🔨
