### PR TITLE
Render bucketing popover in portal

### LINKED ISSUE #58151: Safari doesn't allow you to select granularity of group by (by month, bin, ...)
### Describe the bug

When working with the notebook editor on safari you're not able to select granularity of group by (by month, bin, ...)

### To Reproduce

Open Safari:
 
1. Go to New -> Question -> Orders -> Try to click on group by granularity: 

https://github.com/user-attachments/assets/8a17ef28-701f-4ee1-bce8-9a36631e89ff

### Expected behavior

I am able to use the Notebook Editor. It works on Chrome

### Logs

Cannot find anything relevant even on the developer tools of safari (but could be cause I am not familiar with it)

### Information about your Metabase installation

```JSON
1.54 and happens on stats as well
```

### Severity

I would consider this as P1 even though the workaround is easy and to use Chrome but if you don't know it can force you to hate the product

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/58151

The issue only happens on Safari, so I've not added e2e tests. 

The problem is that the bucket picker popover is rendered as a child of the `AccordionList` which has `overflow: auto` and so doesn't render children outside of it's bounding box the way it should (which seems to be related to [this Safari bug](https://bugs.webkit.org/show_bug.cgi?id=160953)).

Moving it to it's own portal fixes the issue.

### CODE REVIEW

**Review by iethree — CHANGES_REQUESTED** [review]
This breaks the "More" menu, which, I think, Is why that prop was added

breaksMoreMenu

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx [hunk 1]
```diff
@@ -116,7 +116,6 @@ function _BaseBucketPickerPopover({
       opened={isOpened}
       position="right"
       onClose={handlePopoverClose}
-      withinPortal={false}
```
Comment (ranquild) [inline frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx:119]: @romeovs try https://github.com/metabase/metabase/blob/5a1d6774441f865812dc05fc39db1980493713da/frontend/src/metabase/visualizations/components/settings/ChartSettingSelect.jsx#L69

**Review by ranquild — COMMENTED** [review]
Inline

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx (hunk 1 above)
Comment (romeovs) [reply frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx:119]: This is already set on this component [in this line](https://github.com/metabase/metabase/pull/58170/files#diff-304d293d38124406ea9adcf57767c473070b68427d2e5036730b95334a157d19R120), but that doesn't help.

I think it's a Safari bug wrt. z-index and overflow but I'm struggling to track down where the overflow if set.

**Review by ranquild — COMMENTED** [review]
I think this is s hack, as noted. A custom `size` middleware removes the default one, and the DatePicker becomes unscrollable:
Screenshot 2025-05-21 at 15 44 01

master:
Screenshot 2025-05-21 at 15 45 03
 
Maybe it can be done with CSS only to preserve the middleware: https://metaboat.slack.com/archives/C0645JP1W81/p1747855919665149?thread_ts=1747842760.354289&cid=C0645JP1W81. 

Otherwise the default middleware should be carefully examined to not lose any logic.

**Review by iethree — DISMISSED** [review]
Yikes 😬  LGTM, thanks for adding that big fat comment

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.tsx [hunk 2]
```diff
@@ -44,10 +46,12 @@ export function ClausePopover({
         offset={{ mainAxis: 4 }}
         trapFocus
         onChange={handleChange}
+        floatingStrategy="fixed"
```
Comment (uladzimirdev) [inline frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.tsx:49]: I don't see difference whether I have or don't have floatingStrategy specified

File: frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.tsx [hunk 3]
```diff
@@ -44,10 +46,12 @@ export function ClausePopover({
...
+        classNames={{ dropdown: S.dropdown }}
       >
         <Popover.Target>{renderItem(handleOpen)}</Popover.Target>
         <Popover.Dropdown data-testid="clause-popover">
-          {renderPopover(handleClose)}
+          <Box className={S.dropdownContent}>{renderPopover(handleClose)}</Box>
```
Comment (uladzimirdev) [inline frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.tsx:54]: can't we add those classed to `Popover.Dropdown` itself? Maybe we can get rid of Box

File: frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.module.css [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+   *
+   *  This workaround solves the issue by moving the overflow
+   *  onto a child element instead.
+   */
+  overflow: visible;
+}
+
+.dropdownContent {
+  overflow: auto;
+  max-width: inherit;
```
Comment (uladzimirdev) [inline frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.module.css:19]: do we really need max-width?

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx [hunk 5]
```diff
@@ -115,8 +115,8 @@ function _BaseBucketPickerPopover({
     <Popover
       opened={isOpened}
       position="right"
-      onClose={handlePopoverClose}
       withinPortal={false}
+      onClose={handlePopoverClose}
```
Comment (uladzimirdev) [inline frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx:119]: seems nothing changed, could you please revert order?

**Review by uladzimirdev — APPROVED** [review]
I tested this solution in safari and it works like a charm, nice work!

What do you think, should we fix other places with nested popovers?

File: frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.tsx (hunk 2 above)
Comment (romeovs) [reply frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.tsx]: This was a debugging leftover, I removed it.

File: frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.module.css (hunk 4 above)
Comment (romeovs) [reply frontend/src/metabase/querying/notebook/components/ClauseStep/ClausePopover.module.css:19]: Yes we want to resize the element exactly as it's parent.

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx (hunk 5 above)
Comment (romeovs) [reply frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx]: Reverted!
