### PR TITLE
Fix missing database details blows up FE

### LINKED ISSUE #25715: Admin panel database view blows up in an unacceptable way if Database `details` is `NULL`
See #25658

Theoretically we disallow people from creating or updating Databases with invalid `details`, but this is not enforced in the application database schema itself; in some cases when using SerDes v2 it is possible to create a Database without `details`. That is probably a bug. Either way, the error behavior in the frontend client in this situation is unacceptable from a user perspective; we **need** to wrap the whole thing in some sort of `try-catch` to handle **unexpected** errors like this one.

To repro: 

1. Add a row to the `metabase_database` Table in the application database with `NULL` `details` or change an existing row
2. Visit the admin panel details view for that Database e.g. http://localhost:3000/admin/databases/2
3. Frontend application blows up with no error messages at all

   image (1)

The error itself is some sort of "cannot access property of undefined" error. But the problem isn't the error itself, but that we have no fallback unexpected error handling code. There will always be unexpected errors like these, and we need to handle them in some way better than letting it crash with a blank screen.

I would expect it to show some sort of "unexpected error" message/graphic, preferably with a details toggle and maybe a "please report this" and a button to open a GH issue. 

This should be done globally somewhere (perhaps in our component base class?) so we can eliminate blank screen situations altogether. I don't want to see a one-off fix for this specific page leaving the rest of the application open to the same issues.

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/25715

### Description

1. Fix the behavior of `<ErrorBoundary />`
2. Add an `<ErrorBoundary />` to `<DatabaseEditApp />` so it's possible for users to remove database while it has an error.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Run the reproduced test case in this PR, and it should pass
### Demo
Screenshot 2023-02-24 at 6 50 09 PM

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/ErrorBoundary.tsx [hunk 1]
```diff
@@ -29,24 +27,20 @@ export default class ErrorBoundary extends React.Component<
     // if we don't provide a specific onError action, the component will display a generic error message
     if (this.props.onError) {
       this.props.onError(errorInfo);
-    } else {
       this.setState({
-        hasError: true,
-        errorDetails: errorInfo.componentStack,
+        hasError: false,
```
Comment (WiNloSt) [inline frontend/src/metabase/ErrorBoundary.tsx:31]: The problem with the code in `componentDidCatch` is that the way this component works before, makes `componentDidCatch` never get called in some cases like when our DB is blowing up for instance.

Here's an explanation of how it worked previously (which blows up the FE)

1. `getDerivedStateFromError` is called setting `state.hasError: true`
2. since we also pass `onError`, this component will render `children`
    https://github.com/metabase/metabase/blob/0c56664819bb84a7a317caf0fc393d2fa1bf3ccd/frontend/src/metabase/App.tsx#L99
3. And since the children cause an error, this component throws the same error up, but since this is the uppermost `<ErrorBoundary />` no other component will catch the error this one thrown causing the application to blow up. So, `componentDidCatch` is never called, because it's called [after the render phase](https://beta.reactjs.org/reference/react/Component#componentdidcatch) (It's not clear to me when `componentDidCatch` will be called from the doc, but seems like the error boundary should never throw any error to make `componentDidCatched` being called. 

The solution is to ensure the uppermost `<ErrorBoundary />` never throws any error.

This is how this component is modified.
1. Always, render a fallback error component first. 
2. This makes sure `componentDidCatch` will be called.
3. `onError` will set `errorPage` which will be rendered here.
    https://github.com/metabase/metabase/blob/0c56664819bb84a7a317caf0fc393d2fa1bf3ccd/frontend/src/metabase/App.tsx#L108
4. But we need to render the children so `errorPage` could be rendered (otherwise, we'll only see the error rendered from this component), that's why we now set `hasError: false`

File: frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx [hunk 2]
```diff
@@ -128,25 +130,27 @@ class DatabaseEditApp extends Component {
...
-                    <DatabaseForm
-                      initialValues={database}
-                      isAdvanced
-                      onSubmit={handleSubmit}
-                    />
-                  </DatabaseEditForm>
-                  <div>{addingNewDatabase && <DatabaseEditHelp />}</div>
-                </DatabaseEditContent>
-              </LoadingAndErrorWrapper>
+          <ErrorBoundary errorComponent={GenericError}>
```
Comment (WiNloSt) [inline frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx:133]: Add an error boundary component so it matches the expectation in the test–that we can remove the database even if the form blows up.

File: frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js [hunk 3]
```diff
@@ -103,17 +103,12 @@ describe("scenarios > admin > databases > list", () => {
...
-        ...body,
-        details: null,
-      };
-
-      cy.intercept("GET", "/api/database/1", req => {
-        req.reply({ body: stubbedResponse });
-      }).as("loadDatabase");
-    });
+  it("should handle malformed (null) database details (metabase#25715)", () => {
+    cy.intercept("GET", "/api/database/1", req => {
```
Comment (WiNloSt) [inline frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js:107]: @nemanjaglumac I tidy this part up, there's no need for Cypress to call `/api/databas/1` beforehand as Cypress could modify the response on the fly.

File: frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js [hunk 4]
```diff
@@ -103,17 +103,12 @@ describe("scenarios > admin > databases > list", () => {
...
-      const stubbedResponse = {
-        ...body,
-        details: null,
-      };
-
-      cy.intercept("GET", "/api/database/1", req => {
-        req.reply({ body: stubbedResponse });
-      }).as("loadDatabase");
-    });
+  it("should handle malformed (null) database details (metabase#25715)", () => {
```
Comment (WiNloSt) [inline frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js:106]: Unskip to the repro

**Review by iethree — APPROVED** [review]
Great work! 💎  Thanks for digging into this.

Just wanted to take this opportunity to say that
1) error boundaries are awesome and we should use them more throughout the app, it's really easy.
2) if in the future we find that our error boundary component needs to do anything but this dead-simple behavior, we should look at [react-error-boundary](https://www.npmjs.com/package/react-error-boundary)

File: frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js (hunk 4 above)
Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js:106]: Works like a charm.
Thank you

**Review by nemanjaglumac — APPROVED** [review]
🚀
