### PR TITLE
fix aggressive y-axis splitting in line, area, bar charts

### LINKED ISSUE #12939: Y-axis is sometimes automatically split when it's not needed
**Describe the bug**
When result values are almost the same, then it can cause the Y-axis to automatically split the axis.

Also see https://github.com/metabase/metabase/issues/12939#issuecomment-1047207005 for other examples and notes

**To Reproduce**
1. Native question > Sample Dataset
```SQL
SELECT 1075 AS "media_create_count", 1075 AS "media_create_success_count", 1072 AS "media_process_success_count", '2020-07-02' AS "date" UNION ALL
SELECT 614 AS "media_create_count", 611 AS "media_create_success_count", 608 AS "media_process_success_count", '2020-07-03' AS "date" UNION ALL
SELECT 327 AS "media_create_count", 327 AS "media_create_success_count", 327 AS "media_process_success_count", '2020-07-04' AS "date" UNION ALL
SELECT 421 AS "media_create_count", 421 AS "media_create_success_count", 420 AS "media_process_success_count", '2020-07-05' AS "date" UNION ALL
SELECT 995 AS "media_create_count", 993 AS "media_create_success_count", 981 AS "media_process_success_count", '2020-07-06' AS "date" UNION ALL
SELECT 913 AS "media_create_count", 913 AS "media_create_success_count", 911 AS "media_process_success_count", '2020-07-07' AS "date" UNION ALL
SELECT 1089 AS "media_create_count", 1086 AS "media_create_success_count", 1050 AS "media_process_success_count", '2020-07-08' AS "date" UNION ALL
SELECT 1132 AS "media_create_count", 1131 AS "media_create_success_count", 1065 AS "media_process_success_count", '2020-07-09' AS "date" UNION ALL
SELECT 1432 AS "media_create_count", 1413 AS "media_create_success_count", 1396 AS "media_process_success_count", '2020-07-10' AS "date" UNION ALL
SELECT 433 AS "media_create_count", 433 AS "media_create_success_count", 420 AS "media_process_success_count", '2020-07-11' AS "date" UNION ALL
SELECT 628 AS "media_create_count", 626 AS "media_create_success_count", 624 AS "media_process_success_count", '2020-07-12' AS "date" UNION ALL
SELECT 1020 AS "media_create_count", 1019 AS "media_create_success_count", 1017 AS "media_process_success_count", '2020-07-13' AS "date" UNION ALL
SELECT 1072 AS "media_create_count", 1062 AS "media_create_success_count", 1059 AS "media_process_success_count", '2020-07-14' AS "date" UNION ALL
SELECT 1283 AS "media_create_count", 1283 AS "media_create_success_count", 1278 AS "media_process_success_count", '2020-07-15' AS "date" UNION ALL
SELECT 683 AS "media_create_count", 683 AS "media_create_success_count", 681 AS "media_process_success_count", '2020-07-16' AS "date"
```
2. Visualize as Bar chart - notice it's splitting the Y-axis even when all values are very close to each other and probably doesn't need the split.
image

**Workaround:** Disable split in visualization Settings > Axes > "Use a split y-axis when necessary"

**Information about your Metabase Installation:**
Metabase 0.35.4 thru 0.42.1

**Additional context**
https://discourse.metabase.com/t/graph-plot-inconsistency/10893

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by EmmadUsmani**
Closes https://github.com/metabase/metabase/issues/12939

### Description

Our previous logic for determining when to split the y-axis for the `Split y-axis when necessary` setting (which is enabled by default) was nonsensically aggressive. It essentially always split the y-axis whenever the different series in a visualization had different columns for their y-axis (see code in [`LineAreaBarRenderer.js`](https://github.com/metabase/metabase/blob/26656c26ad10ed3581eb40cd682ab37cd7e612c6/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js#L300)), which for most multi-series charts is the case.

The new logic introduced in this PR is more nuanced. While keeping the existing preliminary checks (scalar series, stacked, scatter chart, setting disabled), we replaced the aggressive `hasDifferentYAxisColumns` with three new checks:

1. The semantic types of the columns are different. When series have different units on the y-axes, we should split the axis.
2. Column settings are different. If the column settings are different that means the way we want to format the labels for each column differ, so we should show multiple axes.
3. The smallest range on the chart is ≤5% of the chart's total range. This is to prevent any one series from becoming too small and unreadable.

### How to verify

1. New question -> Orders, Average of Total and Average of Subtotal, Grouped by Product → Category
2. Visualize with bars
3. By default, y-axis should not be split (before it was)
4. Try changing any column settings (e.g. currency formatting), it now should be split
5. Try stacking the bars, y-axis should not be split
6. Deselect "Split y-axis when necessary", y-axis should not be split
7. Try another question with a larger range of values, e.g. Orders, Sum of Total and Minimum of Total, Grouped by Created At (month), y-axis should be split by default

### Demo

Screenshot 2023-03-15 at 3 47 17 PM
Before, many of these charts (top left, bottom left, bottom right) have their y-axes split in places where it really isn't necessary, making the data look very skewed.

Screenshot 2023-03-15 at 3 37 07 PM
After, those three no longer have their y-axes split, while the ones that needed it still do.

https://user-images.githubusercontent.com/37751258/225459283-31666bf0-0669-4f1b-bc94-8665981f6c30.mov

### Checklist

- ✅ Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/renderer_utils.js [hunk 1]
```diff
@@ -352,6 +352,72 @@ export function xValueForWaterfallTotal({ settings, series }) {
...
+  // of the chart's total range, we split the y-axis so it doesn't look too small.
+  return minRange / chartRange <= 0.05;
+}
+
+function getColumnSettingsKey(series) {
+  return JSON.stringify(["name", series.data.cols[1].name]);
+}
+
+function normalizeLineAreaBarSettings(colSettings) {
+  const defaultSettings = {
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/lib/renderer_utils.js:402]: I'd prefer not to duplicate `defaultSettings` here because they can get out of sync. You could get already normalized column settings like this
`const columnSettings = series.map(s => settings.column(s.data.cols[1]));`

File: frontend/src/metabase/visualizations/lib/renderer_utils.js [hunk 2]
```diff
@@ -352,6 +352,72 @@ export function xValueForWaterfallTotal({ settings, series }) {
...
+  const minExtent = Math.min(...yExtents.map(extent => extent[0]));
+  const chartRange = maxExtent - minExtent;
+
+  // Note (EmmadUsmani): When the series with the smallest range is less than 5%
+  // of the chart's total range, we split the y-axis so it doesn't look too small.
+  return minRange / chartRange <= 0.05;
+}
+
+function getColumnSettingsKey(series) {
+  return JSON.stringify(["name", series.data.cols[1].name]);
```
[the remark this answers is not in the document]
Comment (EmmadUsmani) [reply frontend/src/metabase/visualizations/lib/renderer_utils.js]: Thanks for the heads up, I forgot that function existed. I ended up not needing it though since I used the `settings.column` method you suggested in your other comment.

File: frontend/src/metabase/visualizations/lib/renderer_utils.js (hunk 1 above)
Comment (EmmadUsmani) [reply frontend/src/metabase/visualizations/lib/renderer_utils.js]: I agree it's better not to duplicate `defaultSettings` and to use `settings.column` instead. However `settings.column` doesn't return a perfectly normalized version of the column settings which I need for comparison.

Screenshot 2023-03-16 at 8 59 45 AM

First, it returns extra fields (`_column_title_full`, `_numberFormatter`, and `column`) that mess up the comparison, so I have to manually remove them. This is not a huge issue.

Screenshot 2023-03-16 at 9 07 33 AM

The more concerning issue is that it does not remove the strings from `prefix` and `suffix` when they are empty, so I have to manually do that. I don't like this since it also feels like a duplication of the source of truth for column settings, I don't like having to manually delete some specific settings, and there is a potential for bugs to be introduced if new settings are added that are not deleted when they return to their default value.

For now I've updated my function to look like this
```javascript
function normalizeColumnSettings(settings, series) {
  const colSettings = { ...settings.column(series.data.cols[1]) };
  delete colSettings._column_title_full;
  delete colSettings._numberFormatter;
  delete colSettings.column;
  delete colSettings.prefix;
  delete colSettings.suffix;

  return colSettings;
}
```
but let me know if you think there is a better way to do this. Perhaps we should update the `.column` method to not return `prefix` and `suffix` when they are empty strings?

Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/renderer_utils.js]: Yes, we need to compare only specific keys. What do you think about:
1) creating a util function in `frontend/src/metabase/visualizations/lib/settings.js` like this:
```
const COLUMN_SETTINGS_KEYS_TO_COMPARE = [
  "prefix",
  "suffix",
  "currency",
  "number_style",
  "number_separators",
  // ...
];

function getColumnFormattingSettings(columnSettings) {
  return _.pick(columnSettings, (value, key) => {
    if (!COLUMN_SETTINGS_KEYS_TO_COMPARE.includes(key)) {
      return false;
    }

    if (key === "suffix" && value === "") {
      return false;
    }

    // handle other settings

    return true;
  });
}
```

2) Using it here
```
const columnSettings = series.map(s =>
  getColumnFormattingSettings(settings.column(s.data.cols[1])),
);

```

We cannot really delete `prefix` and `suffix` because they can be different for each column.

The previous way with `defaultSettings` would not work correctly because actual defaults are selected in the admin panel:

Screen Shot 2023-03-16 at 2 17 36 PM

Comment (EmmadUsmani) [reply frontend/src/metabase/visualizations/lib/renderer_utils.js]: This looks great, thanks! I like that the code is close to the source of truth in `visualizations/lib/settings.js`. I will update the PR with something like this.

**Review by alxnddr — APPROVED** [review]
