### PR TITLE
fix(sdk): echarts tooltip is cut off below the viewport height

### LINKED ISSUE #51904: Chart tooltips does not show up below the initial screen height in the sdk
Tooltips of visualizations gets cut off at a point beyond the bottom edge of the initial screen size, then disappears completely. Tooltips will never be visible for any dashboard cards that are below the initial screen size.

The root cause is that the `.echarts-tooltip-container` class only covers the screen height (painted in blue in the below screenshot), so tooltips don't show up below that. If you update the tooltip container to either `position: fixed` (with high z-index) or a very tall height in your browser's inspector, the tooltip now shows up again.

Image

See this [private Loom video](https://www.loom.com/share/43a6ab205ca7410eb12b60559814342e?sid=d39067f8-5359-41de-b516-5dc947ca1a99) for how to reproduce. 

### How to reproduce

- Open an interactive dashboard in the SDK, using a dashboard that has a longer height than your screen size (e.g. an x-rayed auto-generated dashboard)
  - I recommend https://embedded-analytics-sdk-demo.metabase.com/admin/analytics/12 and scroll down to the "Hours when Orders were added" dashboard card - it becomes really obvious.
- Scroll to a dashcard at the edge at your screen. Tooltips gets partially cut off - notice the bottom of the tooltip in the above screenshot.
- Scroll to a dashcard beyond the edge of your screen. Tooltips are no longer visible.

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/51904

> [!CAUTION]
> This is a second attempt for https://github.com/metabase/metabase/pull/52310 as it was reverted due to it causing a P1 issue https://github.com/metabase/metabase/issues/52732. The P1 was caused by 1) the automatically backported PR referencing a CSS variable that does not exist yet which relies on https://github.com/metabase/metabase/pull/49442 (not backported), and 2) the e2e changes for custom fixed-position visibility checks does not assert the resulting z-index. See [postmortem](https://www.notion.so/metabase/Echarts-tooltip-in-a-dashboard-is-hidden-behind-charts-18869354c9018094a5efe812c3a8228b?pvs=4) for more info.

As a result of the P1, this PR will do the following:
- Adds an assertion for sane position + z-index to the echarts tooltip test helper. This way, we are asserting for this in every usage of echartsTooltip() helper.
- Adds a similar style-assertion for the tooltip-reproduction test in the SDK, as the advanced `elementFromPoint` test is super flaky on CI and has been skipped earlier. The difference is that we also check that the `--mb-popover-z-index` property from the `theme.components.popover.zIndex` theme option is applied.

- It will be no-backport as I'll do a manual backport to prevent the missing CSS variable issue from happening again.

---

### Description

image

Tooltips of visualizations gets cut off at a point beyond the bottom edge of the initial screen size, then disappears completely. This is because `.echarts-tooltip-container only covers the screen height (the blue area in the above screenshot), so tooltips don't show up below that.

This PR updates the tooltip to use `position: fixed` with an appropriate z-index. It also adds an e2e test for the SDK to ensure that tooltips are always properly visible below the fold.

### How to verify

On the SDK:

- Open an interactive dashboard in the SDK, using a dashboard that has a longer height than your screen size (e.g. an x-rayed auto-generated dashboard)
  - You can use the Shoppy demo's Orders dashboard (https://embedded-analytics-sdk-demo.metabase.com/admin/analytics/12) and scroll down to the "Hours when Orders were added" dashboard card.
- Scroll to a dashcard at the edge at your screen. Tooltip should not get cut off anymore, unlike the above screenshot.
- Scroll to a dashcard beyond the edge of your screen. Tooltips should also be visible.

On the main Metabase app, static iframe embedding and iframe embedding with iframe-resizer:

- Tooltips should still continue to work with no visual artifacts.

### Demo

- Cypress E2E Local Runs - [Private Loom](https://www.loom.com/share/e190643a56da4ca79ac03afc26f29e65?sid=3ea15c61-1c12-47d8-9d2a-83594b42b440)

- Tested on Shoppy - [Private Loom](https://www.loom.com/share/dceb33a742044b50bc400ce7c2efaa3e?sid=565f8f2a-6a82-4533-a5e3-a6f2964ed2d5) - below-the-fold echarts tooltip now works

- Tested on iframe (static embedding) and iframe-resizer script - [Private Loom](https://www.loom.com/share/4e3f7cb6419948779e319d8c808c9dd3?sid=44efc182-9923-4c31-8ec7-01a958e65f08)

- Tested on the main app - [Private Loom](https://www.loom.com/share/5b1c9c14c59f4c6f919a19902fef95e6?sid=b0936d18-4d12-49e6-9977-16345a789a8a)

### Checklist

- [x] Tests have been added/updated to cover changes in this PR - E2E

### CODE REVIEW

File: e2e/support/helpers/e2e-visual-tests-helpers.js [hunk 1]
```diff
@@ -190,7 +217,6 @@ function assertTooltipFooter({ name, value, secondaryValue }) {
 }
 
 export function assertEChartsTooltip({ header, rows, footer, blurAfter }) {
-  echartsTooltip().should("be.visible");
```
Comment (heypoom) [inline e2e/support/helpers/e2e-visual-tests-helpers.js:193]: `be.visible` does not work with fixed-position elements. simply calling echartsTooltip() already does the style assertions in isFixedPositionElementVisible plus the z-index and position assertions automatically.

File: e2e/test-component/scenarios/embedding-sdk/tooltip-reproductions.cy.spec.tsx [hunk 2]
```diff
@@ -59,53 +52,56 @@ describeEE("scenarios > embedding-sdk > tooltip-reproductions", () => {
...
 
-  // This is flaking on CI but not locally :()
-  it.skip("should render tooltips below the screen's height (metabase#51904)", () => {
-    cy.get("@dashboardId").then(dashboardId => {
-      mountSdkContent(<InteractiveDashboard dashboardId={dashboardId} />);
-    });
+  it("should have the correct tooltip position and z-index (metabase#51904, metabase#52732)", () => {
+    const testCases = [
+      // should use the user-supplied z-index
+      { input: 1337, expected: 1337 },
```
Comment (heypoom) [inline e2e/test-component/scenarios/embedding-sdk/tooltip-reproductions.cy.spec.tsx:58]: We allow people to customize their `theme.components.popover.zIndex` in case some apps use a z-index that is higher than 200. This is the only aspect where the SDK test differs from the echarts tooltip helper assertions.

File: enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts [hunk 3]
```diff
@@ -19,6 +20,12 @@ import { colorTuple } from "./color-tuple";
 
 const SDK_BASE_FONT_SIZE = `${DEFAULT_SDK_FONT_SIZE}px`;
 
+// Strip any key that has the value of "undefined"
+const stripUndefinedKeys = <T>(x: T): unknown =>
+  _.isObject(x)
+    ? _.pick(_.mapObject(x, stripUndefinedKeys), v => !_.isUndefined(v))
+    : x;
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts:27]: If I define a theme object like `{components: {popover: {zIndex: undefined}}}` then the zIndex should fallback to the default theme values (e.g. 200), and not literally be `undefined`. Added the test case for this below.

If I instead pass `null` or other non-undefined values, it should still be applied.

File: enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.unit.spec.ts [hunk 4]
```diff
@@ -18,6 +18,11 @@ describe("Transform Embedding Theme Override", () => {
           "text-tertiary": "green",
           "background-disabled": "pink",
         },
+        components: {
+          popover: {
+            zIndex: undefined,
+          },
+        },
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.unit.spec.ts:27]: Modified this test to ensure that even if we provide `zIndex: undefined`, we would still get an appropriate `zIndex: 200` default value back. Expand the diff to see how that works.

File: frontend/src/metabase/components/Popover/TippyPopover.tsx [hunk 5]
```diff
@@ -126,15 +123,11 @@ function TippyPopover({
     [flip, sizeToFit, popperOptions],
   );
 
-  const zIndex =
-    theme.other.popover?.zIndex ||
-    ("var(--mb-overlay-z-index)" as unknown as number);
```
Comment (heypoom) [inline frontend/src/metabase/components/Popover/TippyPopover.tsx:131]: We don't need `theme.other.popover.zIndex` anymore thanks to the CSS variable definition generation. This is a cleanup so we rely on CSS variables instead of direct Mantine theme object access.

File: e2e/support/helpers/e2e-visual-tests-helpers.js [hunk 6]
```diff
@@ -134,11 +136,36 @@ export function pieSliceWithColor(color) {
...
+      visibleTooltip.closest(".echarts-tooltip-container"),
+    );
+
+    // (metabase#51904): tooltip container must render above the fold in the Embedding SDK.
+    // ensures that we are using fixed-positioned tooltips.
+    expect(tooltipContainerStyle.position).to.equal("fixed");
+
+    // (metabase#52732): tooltip container must have the correct z-index (200)
+    // this assertion prevents the tooltip from being rendered below charts.
+    expect(Number(tooltipContainerStyle.zIndex)).to.equal(200);
```
[the remark this answers is not in the document]
Comment (npretto) [reply e2e/support/helpers/e2e-visual-tests-helpers.js:164]: Isn't this testing configuration more than the outcome?

File: e2e/support/helpers/e2e-element-visibility-helpers.ts [hunk 7]
```diff
@@ -0,0 +1,53 @@
+/**
+ * Using `.filter(":visible")` or `.should("be.visible")` fails here as Cypress
+ * is not able to reliably detect a fixed-position element as visible.
+ */
+export function isFixedPositionElementVisible(element: HTMLElement): boolean {
```
[the remark this answers is not in the document]
Comment (npretto) [reply e2e/support/helpers/e2e-element-visibility-helpers.ts:5]: Wasn't the issue that this function didn't catch that the tooltip wasn't visible?

File: e2e/support/helpers/e2e-visual-tests-helpers.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (heypoom) [reply e2e/support/helpers/e2e-visual-tests-helpers.js:164]: @npretto yes, but the problem is Cypress doesn't really do these stacking order checks well. I had one test that works really well locally and it tries to check the element at popup (https://github.com/metabase/metabase/pull/52577), but the problem is it flakes like crazy

File: e2e/support/helpers/e2e-element-visibility-helpers.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (heypoom) [reply e2e/support/helpers/e2e-element-visibility-helpers.ts:5]: @npretto I was wrong about that actually. The visibility checks is working as expected, but the z-index is defined at the tooltip container level and not the tooltip level, so you can't add a z-index or stacking order check here.

[the remark this answers is not in the document]
Comment (npretto) [reply e2e/support/helpers/e2e-element-visibility-helpers.ts:5]: Sorry, what I meant is that this function didn't make the e2e fail on the backport right? Doesn't that mean that its logic isn't reliable?

[the remark this answers is not in the document]
Comment (heypoom) [reply e2e/support/helpers/e2e-element-visibility-helpers.ts:5]: @npretto I think it's a limitation of what this custom visibility check can do, yes. It checks for a couple of things except z-index, which needs to be asserted separately as z-index could be defined on the parent and not at child. 

Ideally we have a function that knows whether an element is not obscured by any element and has a higher z-index, which is what Cypress' `be.visible` and `:visible` filters are _supposed_ to do, but it failed 😢

[the remark this answers is not in the document]
Comment (heypoom) [reply e2e/support/helpers/e2e-element-visibility-helpers.ts:8]: I added a warning to the function in https://github.com/metabase/metabase/pull/52822/commits/421697e1f57609df6df00456d60b939c8e1894e7 that it does not account for stacking orders. Couldn't think of a better name for the function though.

File: frontend/src/metabase/components/Popover/TippyPopover.unit.spec.js [hunk 8]
```diff
@@ -52,22 +50,6 @@ describe("Popover", () => {
...
-        </TippyPopover>
-      </ThemeProvider>,
-    );
-
-    // Tippy's root element is a direct parent, but it has no identifiable role.
-    // eslint-disable-next-line testing-library/no-node-access
-    expect(screen.getByRole("tooltip").parentElement).toHaveStyle({
-      zIndex: 505,
-    });
-  });
```
Comment (heypoom) [inline frontend/src/metabase/components/Popover/TippyPopover.unit.spec.js:69]: We don't need this test anymore as the same test has been added on Cypress. The problem is that Jest does not support CSS variables propagation in their CSSOM, so using `getComputedStyle` here would just return the CSS variable string `var(--mb-overlay-z-index)` instead of `505`

File: e2e/support/helpers/e2e-visual-tests-helpers.js [hunk 9]
```diff
@@ -134,11 +136,36 @@ export function pieSliceWithColor(color) {
 
 export function echartsTooltip() {
   // ECharts may keep two dom instances of the tooltip
-  return cy
-    .findAllByTestId("echarts-tooltip")
-    .filter(":visible")
-    .should("have.length", 1)
-    .eq(0);
+  return cy.findAllByTestId("echarts-tooltip").should($elements => {
```
Comment (WiNloSt) [inline e2e/support/helpers/e2e-visual-tests-helpers.js:139]: I'm worried this could cause flakiness, or failed to capture the actual failure on the core app. From my testing, the current assertion works fine. I think the problem only arises in the SDK. Can you confirm that?

I did remove `:visible` though. It's using `jQuery`'s logic to determine the visibility, while we also have Cypress, so I'm not sure why we need both logic which could be conflicted with each other.

Comment (heypoom) [reply e2e/support/helpers/e2e-visual-tests-helpers.js:139]: @WiNloSt let me try this locally, last time I tried this assertion fails because of `position: fixed; z-index: ...` even in the core app.

Comment (heypoom) [reply e2e/support/helpers/e2e-visual-tests-helpers.js:139]: @WiNloSt the tooltip tests in the core app always fail if I leave the assertion as-is. For example, the `dashboard-drill.cy.spec.js` fails at `filter(:visible)` here

CleanShot 2568-01-29 at 18 55 12@2x

Comment (heypoom) [reply e2e/support/helpers/e2e-visual-tests-helpers.js:139]: the only way to keep the existing echartsTooltip assertion is if we use different `position: ...` values for SDK (`fixed`) and core app (`absolute`) but that isn't good 😢

Comment (WiNloSt) [reply e2e/support/helpers/e2e-visual-tests-helpers.js:139]: > @WiNloSt the tooltip tests in the core app always fail if I leave the assertion as-is. For example, the `dashboard-drill.cy.spec.js` fails at `filter(:visible)` here. It expects to find a visible element but did not found any.
> 
> CleanShot 2568-01-29 at 18 55 12@2x
> 
> This is the same as in the previous PR where all e2e test suite related to tooltips fail unless I update this.

Can you try removing filter(": visible") but keep cypress' be.visible? See if that works. It did for me on one test thought

Comment (heypoom) [reply e2e/support/helpers/e2e-visual-tests-helpers.js:139]: @WiNloSt it does not work because `be.visible` throws. I tried with this minimal example:

```ts
export function echartsTooltip() {
  return cy.findByTestId("echarts-tooltip").should("be.visible");
}
```

This error is quite explicit: "it has CSS property: position: fixed and it's being covered by another element", even though in reality it is not covered by anything as far as we're aware.

```
Timed out retrying after 4000ms: expected '<div>' to be 'visible'

This element <div> is not visible because it has CSS property: position: fixed and it's being covered by another element:

<svg width="445" height="296.13543701171875" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" baseProfile="full" style="position: absolute; left: 0px; top: 0px; user-select: none;">...</svg>
```

CleanShot 2568-01-29 at 19 15 06@2x

Comment (WiNloSt) [reply e2e/support/helpers/e2e-visual-tests-helpers.js:139]: Ok maybe it's not working on all tests 😭.

Comment (heypoom) [reply e2e/support/helpers/e2e-visual-tests-helpers.js:139]: I just noticed that Cypress tells us that it's been covered by the `<svg>` which is the bar chart in front of it. I think their covering checks need more work 😅

File: frontend/src/metabase/components/Popover/TippyPopover.tsx [hunk 10]
```diff
@@ -126,15 +123,11 @@ function TippyPopover({
...
-
   return (
     <TippyComponent
       className={cx("popover", ZIndex.Overlay, className)}
       theme="popover"
-      zIndex={zIndex}
+      zIndex={"var(--mb-overlay-z-index)" as unknown as number}
```
Comment (alxnddr) [inline frontend/src/metabase/components/Popover/TippyPopover.tsx:130]: Should we update the prop type here to support strings?

File: enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts (hunk 3 above)
Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts:27]: I don't know if between this or using the [associator](https://github.com/aearly/icepick?tab=readme-ov-file#mergetarget-source-associator), would be simpler. I think if we use the associator, it'd be a simple function that we'd ignore the nully value from `theme.components`

**Review by WiNloSt — APPROVED** [review]
I'm not happy with the way we do custom check on echart tooltip. I'm worried this might cause flakiness or fail to detect the visibility completely.

Would we consider using a different CSS solution that works with `be.visible` (if it exist)?

I'd refer to the echart tooltip helper to Sasha then. I'm cool with it just for the SDK, but this is for the whole app.

That said, from the SDK's perspective, it looks good. I've tested the app, static embedding, and the SDK, and they all worked.

**Comment by heypoom** [comment]
> Would we consider using a different CSS solution that works with be.visible (if it exist)?

@WiNloSt yes, if there exists a solution in Cypress I'd be happy to use it. Technically, you can add an "if" statement to the tooltip that uses `position: fixed` only on the SDK, and it should work with `be.visible`. I feel weird doing that just to satisfy Cypress though, but it can be done.

**Comment by WiNloSt** [comment]
> > Would we consider using a different CSS solution that works with be.visible (if it exist)?
> 
> @WiNloSt yes, if there exists a solution in Cypress I'd be happy to use it. Technically, you can add an "if" statement to the tooltip that uses `position: fixed` only on the SDK, and it should work with `be.visible`. I feel weird doing that just to satisfy Cypress though, but it can be done.

let's wait and see how sasha will think about the util first then.

**Comment by heypoom** [comment]
@WiNloSt Sounds good! I pinged Sasha, but he's on the offsite right now so will take a bit of time.

File: enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts (hunk 3 above)
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts:27]: @WiNloSt nice, I didn't knew that associator argument existed! let me update the code

Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts:27]: @WiNloSt I think icepick's latest type definition is still 2.3.3 which does not have a resolver yet, as that is available in 2.4.0. https://www.npmjs.com/package/@types/icepick seems to be outdated 😞 

```ts
export function merge<T, S1>(target: T, source: S1): T & S1;
```

I'll keep the existing code for now.

Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts:27]: well yeah. that sucks. Thanks for trying it out tho.

**Review by alxnddr — APPROVED** [review]

**Comment by heypoom** [comment]
I'll merge this for now as it get approved, but I'm happy to switch to the `isSDK ? "fixed" : "absolute"` approach if this custom visibility check turns out to be problematic and causes annoying stacking context bugs that we did not anticipate.

**Comment by heypoom** [comment]
@metabase-bot backport release-x.53.x

**Comment by heypoom** [comment]
@metabase-bot backport release-x.52.x
