### PR TITLE
fix(cache): Fix two bugs in Admin / Performance

### LINKED ISSUE #44249: In Admin/Performance/Database caching, when a minimum query duration is saved for an adaptive policy, the new value does not appear in the form
https://www.loom.com/share/35fe0eeb6d5045049e5a93e6d634cab8?sid=f4de67c4-2983-432d-ae3d-a812c939f571

### LINKED ISSUE #44257: In Admin/Performance/Database caching, 12:00PM cannot be used as a time in the Schedule component

### PR DESCRIPTION
**Pull request by rafpaf**
Closes #44249: When a new minimum query duration is added to an adaptive policy, it disappears from the form on save.
Closes #44257: Aberrant edge case: 12:00PM cannot be used as a time in the Schedule component.

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#44255** <a href="https://app.graphite.dev/github/pr/metabase/metabase/44255?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: frontend/src/metabase/components/Schedule/utils.tsx [hunk 1]
```diff
@@ -74,5 +74,3 @@ export const getLongestSelectLabel = (data: SelectProps["data"]) =>
     const label = typeof option === "string" ? option : option.label || "";
     return label.length > acc.length ? label : acc;
   }, "");
-
-// HIIII
```
Comment (rafpaf) [inline frontend/src/metabase/components/Schedule/utils.tsx:78]: <i class='graphite__hidden'>[Re: line 79]<br/><br/></i>

A comment that snuck while I was showing Sloan something<span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/metabase/metabase/44255?utm_source=unchanged-line-comment">Graphite</a>.</span>

Comment (sloansparger) [reply frontend/src/metabase/components/Schedule/utils.tsx:78]: Heeeeeeyyyyyyy

File: frontend/src/metabase/admin/performance/hooks/useSaveStrategy.tsx [hunk 2]
```diff
@@ -52,17 +62,29 @@ export const useSaveStrategy = (
...
+        const newConfig: CacheConfig = {
           ...baseConfig,
           strategy: validatedStrategy,
         };
 
         const translatedConfig = translateConfigToAPI(newConfig);
         await CacheConfigApi.update(translatedConfig);
+
+        if (newConfig.strategy.type === "ttl") {
+          newConfig.strategy = populateMinDurationSeconds(newConfig.strategy);
```
Comment (sloansparger) [inline frontend/src/metabase/admin/performance/hooks/useSaveStrategy.tsx:74]: Is there a reason we're passing in newConfig into `translateConfigToAPI` before it gets mutated on line 74? If so, it's not exactly clear to me why. If it's not, it looks like a potential source of bugs. I think it's best to try to write this without doing a mutation, something like:

```suggestion
        const newConfig: CacheConfig = {
          ...baseConfig,
          strategy: validatedStrategy.type === "ttl"
            ? populateMinDurationSeconds(validatedStrategy)
            : validatedStrategy,
        };

        const translatedConfig = translateConfigToAPI(newConfig);
        await CacheConfigApi.update(translatedConfig);
```

File: frontend/src/metabase/admin/performance/hooks/useInvalidateTarget.tsx [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+  const dispatch = useDispatch();
+  const invalidateTarget = useCallback(async () => {
+    if (targetId === null) {
+      return;
+    }
+    try {
+      const invalidate = CacheConfigApi.invalidate(
+        { include: "overrides", [targetModel]: targetId },
+        { hasBody: false },
+      );
```
Comment (sloansparger) [inline frontend/src/metabase/admin/performance/hooks/useInvalidateTarget.tsx:24]: I understand this is being refactored from elsewhere, but ideally we should refactor this to RTKQuery in another PR.

**Review by sloansparger — DISMISSED** [review]

File: frontend/src/metabase/admin/performance/hooks/useSaveStrategy.tsx (hunk 2 above)
Comment (rafpaf) [reply frontend/src/metabase/admin/performance/hooks/useSaveStrategy.tsx]: This approach populates the minimum query duration in seconds a bit early, so that the API receives the number both in milliseconds (which it needs) and in seconds (which it doesn't need). That might be harmless, but I don't remember if the API will accept this additional input.

**Review by npfitz — APPROVED** [review]
Checked that the issues mentioned were resolved, and they seem to be. I don't entirely follow all the conversion logic though. Will catch up with @rafpaf when he's back to get an overview
