### PR TITLE
Fix missing JS metadata for Saved Question/Model source query

### LINKED ISSUE #29739: [MLv2] [Bug] JS MetadataProvider not working correctly for questions using Saved Questions/Models as source
Apparently not working for native questions either. See https://metaboat.slack.com/archives/C04DN5VRQM6/p1680268395463109

### PR DESCRIPTION
**Pull request by kulyk**
Fixes #29739

@kulyk wrote the JS test and @camsaul wrote the CLJS fixes.

The problems here were

1. Models or Saved Questions sometimes have their metadata saved as `:fields` rather than `:result_metadata`, which is what the old code assumed (it's returned as `:result_metadata` by the API, so somebody must be renaming it; doesn't matter, we'll handle both for now. In the future maybe we can clean it up and avoid the rename but for MLv1 compatibility that time is not yet)
2. `:result_metadata`/`:fields` in Saved Question metadata were not recursively getting parsed; fixed 

This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29732)

### CODE REVIEW

File: src/metabase/lib/js/metadata.cljs [hunk 1]
```diff
@@ -25,26 +25,34 @@
...
+                       (= (goog/typeOf v) "function")))
+             xform)
+            (gobject/getKeys obj)))))
+
+(defmulti ^:private excluded-keys
   {:arglists '([object-type])}
   keyword)
 
-(defmethod excluded-fields :default
+(defmethod excluded-keys :default
```
Comment (camsaul) [inline src/metabase/lib/js/metadata.cljs:55]: I renamed this for a little more clarity

**Review by snoe — APPROVED** [review]

**Review by camsaul — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29732#-:-NSMtLwHAI7SaY7A_xqH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kulyk)
