### PR TITLE
Handle bad site-url values

### LINKED ISSUE #9764: MB_SITE_URL env var does not work for site-url setting
As mentioned in #2090 

Settings defined with env vars are supposed to override any values in the cache/DB. However `site-url` has a custom magic getter function which calls `setting/get-string`, correctly; I suspect `setting/get-string` is just getting the cached/DB value instead of the env var value, which is not the behavior we want.

Investigate this issue and if my suspicions are correct fix `get-string` so Settings with custom magic getters will use env var values if they are present.

### PR DESCRIPTION
**Pull request by camsaul**
*  Validate `site-url` before saving it
*  If `site-url` is not a valid URL, reset it automatically on the next request
*  Properly handle site URLs set via env vars

Fixes #9764, #9849, #9850

### CODE REVIEW

File: project.clj [hunk 1]
```diff
@@ -75,6 +76,12 @@
    [com.mattbertolini/liquibase-slf4j "2.0.0"]                        ; Java Migrations lib logging. We don't actually use this AFAIK (?)
    [com.mchange/c3p0 "0.9.5.3"]                                       ; connection pooling library
    [com.taoensso/nippy "2.14.0"]                                      ; Fast serialization (i.e., GZIP) library for Clojure
+   [commons-codec/commons-codec "1.12"]                               ; Apache Commons -- useful codec util fns
```
Comment (camsaul) [inline project.clj]: these were already pulled in by various other dependencies, I've made them explicit so we can use some of these functions more readily and not have to reimplement the wheel ourselves
