### PR TITLE
Don't return table data for archive searches

### LINKED ISSUE #10439: Collections archive incorrectly listing tables
As [mentioned](https://github.com/metabase/metabase/pull/10429#issuecomment-516657176) by @flamber, https://github.com/metabase/metabase/pull/10429 seems to have introduced a bug where tables are appearing in the collections archive page, `/archive`:

image

To quote Flamber:
`Clicking [the trash icon] just results in following log: DELETE /api/table/1 404 1 ms (0 DB calls) "API endpoint does not exist."`

### PR DESCRIPTION
**Pull request by walterl**
Fixes #10439

### CODE REVIEW

File: test/metabase/api/search_test.clj [hunk 1]
```diff
@@ -311,6 +311,19 @@
     (tt/with-temp Table [table {:name table-name}]
       (search-request :rasta :q table-name))))
 
+;; But *archived* tables should not appear in search results
+(let [table-name (tu/random-name)]
+  (expect
+    []
+    (tt/with-temp Table [table {:name table-name}]
```
Comment (camsaul) [inline test/metabase/api/search_test.clj]: no need to change this now but `with-temp` automatically gives objects random names as needed so you could have done this instead:

```clj
(expect
  []
  (tt/with-temp Table [{table-name :name}]
    (search-request :rasta :q table-name, :archived true))
```

You only need to `let` it outside of the `expect` form if you need to refer to it in both the expected and actual forms

**Review by camsaul — APPROVED** [review]
