### PR TITLE
UXW-2449 fix pasting mixed content containing cardEmbed

### LINKED ISSUE #66504: Cannot Copy/Paste a chart in Documents
### Describe the bug

Copy + pasting. section of a document including a chart does not show the chart after pasting. 

### To Reproduce

1. Create a document
2. Add some text and a chart
3. Select the text and chart and copy then paste the selection
4. The Chart is not displayed

See slack: https://metaboat.slack.com/archives/C05NXACAG1G/p1764683370360469

### Expected behavior

The chart should display. 

### Logs

_No response_

### Information about your Metabase installation

```JSON
{stats}
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deniskaber**
closes #66504
Closes UXW-2449 / https://github.com/metabase/metabase/issues/66504

### Description

Issue happened because copied tiptap content got serialized into HTML, and some nodes didn't render proper `data-type` tags. Because of that, ProseMirror tried to produce valid content that is close enough.

### How to verify

I haven't managed to reproduce this specific use case locally, but you can try the same that I do in the demo.

### Demo

https://github.com/user-attachments/assets/4a4daa6e-f5dc-48d3-bda2-d238e3d5002a

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR - ⚠️  I don't know how to reproduce this in local setup

### CODE REVIEW

File: frontend/src/metabase/rich_text_editing/tiptap/extensions/PlainLink/PlainLink.ts [hunk 1]
```diff
@@ -92,6 +92,24 @@ export const PlainLink = Link.extend({
...
+          // Don't parse smart-link elements as plain links
+          if (element.getAttribute("data-type") === "smart-link") {
+            return false;
+          }
+          return null;
+        },
+      },
+    ];
+  },
+
```
Comment (andsalves) [inline frontend/src/metabase/rich_text_editing/tiptap/extensions/PlainLink/PlainLink.ts:112]: Hey @deniskaber, I was able to reproduce the issue locally.
The problem with the chart has been fixed, but there seems to be some code changes that did not affect the pasting behavior, like this block, that does not help with the chart or smart links.
Please check out the video attached (no audio). Notice that your updates properly fix the chart being pasted, but the smart links are still going as regular links.

https://www.loom.com/share/b24ce509e9bc4b7a9256894f6d4aeb1f

Also, there are extra line breaks when copy-pasting stuff.

These two issues (smart links & line breaks) are not the main problem reported in UXW-2449, so I'd say to either:
- Remove any code that does not contribute to fixing specifically the chart copy-paste issue, or 
- Adjust it so that the smart links copy-paste also works as expected.

I would go with only fixing the chart issue and undoing any changes that do not help with that, but feel free to fix the other stuff too if you think it's worth it.
Let me know if you still can't reproduce it locally.

**Review by andsalves — DISMISSED** [review]

File: frontend/src/metabase/rich_text_editing/tiptap/extensions/PlainLink/PlainLink.ts (hunk 1 above)
Comment (deniskaber) [reply frontend/src/metabase/rich_text_editing/tiptap/extensions/PlainLink/PlainLink.ts:112]: Hey @andsalves ! Could you please make `yarn install` and refresh page with open document after you switch branch. These DOM changes to missing attributes won't be picked up after regular fast-reload and also we need to make sure prosemirror package is updated.

Could you please double-check ?

https://github.com/user-attachments/assets/debf2d18-f4fd-44a4-b4e7-d2cc96363bab

Comment (andsalves) [reply frontend/src/metabase/rich_text_editing/tiptap/extensions/PlainLink/PlainLink.ts:112]: Hey @deniskaber,
I tried to run yarn install, yarn build and then reran the frontend and backend multiple times but got the same results. Tried with Chrome and Firefox.
I'm starting to think it might have to do with my environment (Linux), because of the way the system handles clipboard stuff.
Can you ask for a third pair of eyes to try it out? 
We can also huddle on Slack if you think I'm still missing something to get it working.

**Comment by iethree** [comment]
fix works properly for me: 

https://github.com/user-attachments/assets/645790f3-1b44-4c77-aac1-3e0c5da6768a

**Review by iethree — APPROVED** [review]
LGTM
