### PR TITLE
Correct saving of pivot card metadata

### LINKED ISSUE #59275: Saved pivot table doesn't show expected results when used as source data for another question
### Describe the bug

If you try to use a saved pivot table as the source data for a new question, the results set you get consists of just the pivot's measures and the artificial `pivot-grouping` column. This contradicts the SQL displayed for the question which correctly matches the original MBQL query.

Image

Image

### To Reproduce

1. Create an MBQL question with two breakouts like this one:
Image

2. Select the Pivot Table visualization type
3. Save the question
4. Go back to the query builder and select this saved question as the starting data
5. Run the question, and see what results you get

### Expected behavior

Should presumably show the aggregated but non-pivoted query results, like for other visualization types, and should definitely not show the `pivot-grouping` column

### Logs

_No response_

### Information about your Metabase installation

```JSON
875d28d5e07
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nvoxland**
Fixes https://github.com/metabase/metabase/issues/59275

### Description

The `metabase.query-processor.middleware.results-metadata/record-metadata!` method gets triggered for all the sub-queries of a pivot card, updating the `report_card.result_metadata` value for each one, and it does it on every view since each change is a unique (and wrong) value.

This PR adds the overall pivot result metadata to the query information at the beginning when we know it's a pivot query, then in `record-metadata!` we use that value to consider updating the column value.

Because there are more differences between what ends up in the result of `qp.metadata/result-metadata` vs. what is actually stored in the db, the `comparable-metadata` function has been expanded a bit. 

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Load the example dashboard, tracking how many times the call to `t2/update!` in `record-metadata!` is called
2. It should not be called when the metadata was not changed

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/middleware/results_metadata.clj [hunk 1]
```diff
@@ -22,22 +22,35 @@
...
+            (cond
+              (keyword? m) (str (symbol m))
+              (map? m) (dissoc (reduce-kv
+                                (fn [acc k v]
+                                  (assoc acc k
+                                         (standardize-metadata v))) {} m) :ident :display_name)
+              (sequential? m) (mapv standardize-metadata m)
+              (set? m) (set (map standardize-metadata m))
+              :else m))]
+    (standardize-metadata metadata)))
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/results_metadata.clj]: - `u/qualified-name` does the right thing for the keywords.
- That `reduce-kv` is `(update-vals m standardize-metadata)`.
    - It's also really hard to read the nested `(dissoc (reduce-kv ...`; prefer `->`
- `(set (map f xs))` has more overhead than the equivalent `(into #{} (map f) xs)`
    - Not all `set?`s are `set`s, it could be an `ordered-set` or something. It doesn't matter here since this is bound for `=` comparison only, but it's safer in general to use `(empty m)` to get an empty target of the same kind as `m`.
- The only thing stopping this from being `(clojure.walk/postwalk #(cond-> % (keyword? %) u/qualified-name) m)` is that it doesn't transform map keys to strings like it does the values. Do we actually care about that, since this is only used for comparison?
```suggestion
  (letfn [(standardize-metadata [m]
            (cond
              (keyword? m)    (u/qualified-name m)
              (map? m)        (-> (update-vals m standardize-metadata)
                                  (dissoc :ident :display_name))
              (sequential? m) (mapv standardize-metadata m)
              (set? m)        (into #{} (map standardize-metadata) m)
              :else           m))]
    (standardize-metadata metadata)))
```

File: src/metabase/query_processor/middleware/results_metadata.clj [hunk 2]
```diff
@@ -22,22 +22,35 @@
...
-               driver/*driver*
-               (driver.u/supports? driver/*driver* :nested-queries (lib.metadata/database (qp.store/metadata-provider)))
-               card-id
-               ;; don't want to update metadata when we use a Card as a source Card.
-               (not (:qp/source-card-id query))
-               ;; Only update changed metadata
-               (not= (comparable-metadata metadata) (comparable-metadata (qp.store/miscellaneous-value [::card-stored-metadata]))))
-      (t2/update! :model/Card card-id {:result_metadata metadata
-                                       :updated_at      :updated_at}))
+    (let [actual-metadata (or (get-in query [:info :pivot/result-metadata]) metadata)]
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/results_metadata.clj]: `get` and `get-in` optionally take the default as the last argument.
```suggestion
    (let [actual-metadata (get-in query [:info :pivot/result-metadata] metadata)]
```

File: src/metabase/query_processor/middleware/results_metadata.clj [hunk 3]
```diff
@@ -22,22 +22,35 @@
...
   "Smooth out any unimportant differences in metadata so we can do an easy equality check."
   [metadata]
-  (mapv #(dissoc % :ident) metadata))
+  (letfn [(standardize-metadata [m]
+            (cond
+              (keyword? m) (str (symbol m))
+              (map? m) (dissoc (reduce-kv
+                                (fn [acc k v]
+                                  (assoc acc k
+                                         (standardize-metadata v))) {} m) :ident :display_name)
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/results_metadata.clj]: `:display_name` is a pretty important bit of metadata! Are we certain that excluding it from these comparisons is necessary and not going to break eg. changing the display-name of a model column?

**Review by bshepherdson — CHANGES_REQUESTED** [review]

**Review by bshepherdson — APPROVED** [review]
