### PR TITLE
Don't return Pulses used for DashboardSubscriptions in the search endpoint

### LINKED ISSUE #14190: dashboard subscription via slack also creates pulse
**Describe the bug**
Creating a dashboard subscription to send an update via Slack creates a pulse.

**Logs**

Server logs:
```
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:27-08:00 INFO metabase.middleware.exceptions Request canceled before finishing.
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:27-08:00 DEBUG metabase.middleware.log GET /api/user/current 200 4.7 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (1 idle, 0 queued) (80 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:27-08:00 DEBUG metabase.middleware.log GET /api/session/properties 200 5.5 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (80 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:27-08:00 DEBUG metabase.middleware.log GET /api/database 200 6.1 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (80 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:28-08:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 11.0 ms (7 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (80 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:28-08:00 DEBUG metabase.middleware.log GET /api/collection/root 200 3.4 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (80 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:35-08:00 DEBUG metabase.middleware.log GET /api/search 200 9.4 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (80 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:38-08:00 DEBUG metabase.middleware.log GET /api/user 200 3.1 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (80 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:38-08:00 DEBUG metabase.middleware.log GET /api/pulse/1 200 13.0 ms (7 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (1 idle, 0 queued) (80 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:39-08:00 DEBUG metabase.middleware.log GET /api/pulse/form_input 200 939.2 ms (0 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (1 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:43-08:00 DEBUG metabase.middleware.log GET /api/pulse/preview_card_info/50 200 4.6 s (15 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:44-08:00 DEBUG metabase.middleware.log PUT /api/pulse/1 200 17.2 ms (14 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (1 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:44-08:00 DEBUG metabase.middleware.log GET /api/collection/tree 200 4.5 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (0 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:44-08:00 DEBUG metabase.middleware.log GET /api/collection/root 200 2.3 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (0 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:44-08:00 DEBUG metabase.middleware.log GET /api/collection/root/items 200 12.4 ms (7 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:48-08:00 DEBUG metabase.middleware.log GET /api/dashboard/6 200 8.8 ms (7 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:48-08:00 INFO metabase.api.card Question's average execution duration is 88.0 ms; using 'magic' TTL of 1000.0 ms 💾
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:48-08:00 DEBUG metabase.middleware.log GET /api/table/2/query_metadata 200 17.2 ms (11 DB calls) App DB connections: 1/7 Jetty threads: 6/50 (0 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:48-08:00 INFO metabase.query-processor.middleware.cache Query took 28.0 ms to run; minimum for cache eligibility is 60.0 s
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:48-08:00 DEBUG metabase.middleware.log POST /api/card/50/query 202 [ASYNC: completed] 49.3 ms (15 DB calls) App DB connections: 1/7 Jetty threads: 4/50 (0 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:48-08:00 DEBUG metabase.middleware.log GET /api/table/3/query_metadata 200 11.3 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:48-08:00 DEBUG metabase.middleware.log GET /api/table/1/query_metadata 200 13.2 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:57-08:00 DEBUG metabase.middleware.log GET /api/pulse 200 1.8 ms (1 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (0 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:27:58-08:00 DEBUG metabase.middleware.log GET /api/pulse/form_input 200 796.4 ms (0 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:08-08:00 DEBUG metabase.middleware.log POST /api/pulse 200 17.9 ms (15 DB calls) App DB connections: 1/7 Jetty threads: 5/50 (0 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:08-08:00 DEBUG metabase.middleware.log GET /api/pulse 200 6.3 ms (7 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:16-08:00 DEBUG metabase.middleware.log GET /api/search 200 9.6 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:22-08:00 DEBUG metabase.middleware.log GET /api/pulse/2 200 18.5 ms (7 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (0 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:22-08:00 DEBUG metabase.middleware.log GET /api/pulse/preview_card_info/50 200 60.8 ms (15 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (0 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:23-08:00 DEBUG metabase.middleware.log GET /api/pulse/form_input 200 697.8 ms (0 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:32-08:00 DEBUG metabase.middleware.log GET /api/setting 200 1.3 ms (0 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (0 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:32-08:00 DEBUG metabase.middleware.log GET /api/session/properties 200 7.3 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (0 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:32-08:00 DEBUG metabase.middleware.log GET /api/setup/admin_checklist 200 15.6 ms (11 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (86 total active threads) Queries in flight: 0 (0 queued)
[44eb2bfb-60de-4a19-8b6a-094ca3397dd5] 2020-12-23T16:28:38-08:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 2.7 ms (1 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (0 idle, 0 queued) (86 total active threads) Queries in flight: 0 (0 queued)
```

Client logs:
```
16:27:26.660 unreachable code after return statement
utils.js:407
16:27:26.694 [HMR] Waiting for update signal from WDS... log.js:23
16:27:26.764 Setting moment.js start of week for Locale en to sunday i18n.js:58
16:27:26.812 Download the React DevTools for a better development experience: https://fb.me/react-devtools ReactDOM.js:71
16:27:26.942 unreachable code after return statement
utils.js:407
16:27:27.540 Can't make class FormField hot reloadable due to being read-only. To fix this you can try two solutions. First, you can exclude files or directories (for example, /node_modules/) using 'exclude' option in loader configuration. Second, if you are using Babel, you can enable loose mode for `es6.modules` using the 'loose' option. See: http://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/#options-loose and http://babeljs.io/docs/usage/options/ makeExportsHot.js:47
16:27:27.549 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs lowPriorityWarning.js:38
16:27:27.549 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class lowPriorityWarning.js:38
16:27:28.214
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See LoadingAndErrorWrapper > Link > BaseLink > Link > a > ... > Link > BaseLink > Link > a. warning.js:33
16:27:28.429 [WDS] Hot Module Replacement enabled. index.js:77
16:27:35.511
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `LoadingAndErrorWrapper`. See https://fb.me/react-warning-keys for more information.
    in Link (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by EntityListLoader)
    in EntityListLoader (created by search.ListLoader)
    in search.ListLoader (created by SearchApp)
    in div
    in Clean.div (created by Box)
    in Box (created by SearchApp)
    in div
    in Clean.div (created by Box)
    in Box (created by SearchApp)
    in SearchApp (created by Title[SearchApp])
    in Title[SearchApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:38.437
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `PulseEdit`. See https://fb.me/react-warning-keys for more information.
    in a (created by PulseEdit)
    in PulseEdit (created by PulseEditApp)
    in PulseEditApp (created by Title[PulseEditApp])
    in Title[PulseEditApp] (created by Connect(Title[PulseEditApp]))
    in Connect(Title[PulseEditApp]) (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by EntityListLoader)
    in EntityListLoader (created by PulseEditApp)
    in PulseEditApp (created by RouterContext)
    in Unknown (created by Title[])
    in Title[] (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:38.445
Warning: Failed prop type: The prop `field` is marked as required in `ItemSelect`, but its value is `undefined`.
    in ItemSelect (created by PulseEditCollection)
    in PulseEditCollection (created by PulseEdit)
    in div (created by PulseEdit)
    in div (created by PulseEdit)
    in PulseEdit (created by PulseEditApp)
    in PulseEditApp (created by Title[PulseEditApp])
    in Title[PulseEditApp] (created by Connect(Title[PulseEditApp]))
    in Connect(Title[PulseEditApp]) (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by EntityListLoader)
    in EntityListLoader (created by PulseEditApp)
    in PulseEditApp (created by RouterContext)
    in Unknown (created by Title[])
    in Title[] (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:39.450
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `PulseEditChannels`. See https://fb.me/react-warning-keys for more information.
    in Option (created by PulseEditChannels)
    in PulseEditChannels (created by PulseEdit)
    in div (created by PulseEdit)
    in div (created by PulseEdit)
    in div (created by PulseEdit)
    in PulseEdit (created by PulseEditApp)
    in PulseEditApp (created by Title[PulseEditApp])
    in Title[PulseEditApp] (created by Connect(Title[PulseEditApp]))
    in Connect(Title[PulseEditApp]) (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by EntityListLoader)
    in EntityListLoader (created by PulseEditApp)
    in PulseEditApp (created by RouterContext)
    in Unknown (created by Title[])
    in Title[] (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:41.675
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Triggerable[Modal]`. See https://fb.me/react-warning-keys for more information.
    in strong (created by Triggerable[Modal])
    in Triggerable[Modal] (created by PulseEdit)
    in div (created by PulseEdit)
    in div (created by PulseEdit)
    in PulseEdit (created by PulseEditApp)
    in PulseEditApp (created by Title[PulseEditApp])
    in Title[PulseEditApp] (created by Connect(Title[PulseEditApp]))
    in Connect(Title[PulseEditApp]) (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by EntityListLoader)
    in EntityListLoader (created by PulseEditApp)
    in PulseEditApp (created by RouterContext)
    in Unknown (created by Title[])
    in Title[] (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:44.238
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See PinnedItem > Link > BaseLink > Link > a > ... > NormalItem > Link > BaseLink > Link > a. warning.js:33
16:27:44.458
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Triggerable[Modal] component. warning.js:33
16:27:45.043
Warning: Unknown prop `depth` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by Link)
    in Link (created by BaseLink)
    in BaseLink (created by Link)
    in Link (created by CollectionLink)
    in CollectionLink (created by CollectionSidebar)
    in div
    in Clean.div (created by Box)
    in Box (created by CollectionSidebar__Sidebar)
    in CollectionSidebar__Sidebar (created by CollectionSidebar)
    in CollectionSidebar (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by EntityListLoader)
    in EntityListLoader (created by CollectionSidebar)
    in CollectionSidebar (created by Connect(CollectionSidebar))
    in Connect(CollectionSidebar) (created by CollectionLanding)
    in div
    in Clean.div (created by Box)
    in Box (created by Layout__PageWrapper)
    in Layout__PageWrapper (created by CollectionLanding)
    in CollectionLanding (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:45.048
Warning: Unknown props `hovered`, `highlighted` on <a> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by Link)
    in Link (created by BaseLink)
    in BaseLink (created by Link)
    in Link (created by CollectionLink)
    in CollectionLink (created by DropArea)
    in div (created by DropArea)
    in DropArea (created by DropTarget(DropArea))
    in DropTarget(DropArea) (created by CollectionsList)
    in div
    in Clean.div (created by Box)
    in Box (created by CollectionsList)
    in div
    in Clean.div (created by Box)
    in Box (created by CollectionsList)
    in CollectionsList (created by CollectionSidebar)
    in div
    in Clean.div (created by Box)
    in Box (created by CollectionSidebar)
    in div
    in Clean.div (created by Box)
    in Box (created by CollectionSidebar__Sidebar)
    in CollectionSidebar__Sidebar (created by CollectionSidebar)
    in CollectionSidebar (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by EntityListLoader)
    in EntityListLoader (created by CollectionSidebar)
    in CollectionSidebar (created by Connect(CollectionSidebar))
    in Connect(CollectionSidebar) (created by CollectionLanding)
    in div
    in Clean.div (created by Box)
    in Box (created by Layout__PageWrapper)
    in Layout__PageWrapper (created by CollectionLanding)
    in CollectionLanding (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:48.532
Warning: Failed prop type: The prop `onSharingClick` is marked as required in `Dashboard`, but its value is `undefined`.
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Dashboard)
    in Dashboard (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp (created by Unknown)
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by DashboardApp)
    in DashboardApp (created by Title[DashboardApp])
    in Title[DashboardApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:48.533
Warning: Failed prop type: The prop `onEmbeddingClick` is marked as required in `Dashboard`, but its value is `undefined`.
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Dashboard)
    in Dashboard (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp (created by Unknown)
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by DashboardApp)
    in DashboardApp (created by Title[DashboardApp])
    in Title[DashboardApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:48.580
Warning: Failed prop type: DashboardHeader: prop type `onEmbeddingClick` is invalid; it must be a function, usually from React.PropTypes.
    in DashboardHeader (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Dashboard)
    in Dashboard (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp (created by Unknown)
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by DashboardApp)
    in DashboardApp (created by Title[DashboardApp])
    in Title[DashboardApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:48.588
Warning: Unknown props `collectionId`, `dispatch`, `fetchList`, `fetch`, `create`, `update`, `setArchived`, `setCollection`, `fetched`, `loading`, `error`, `reload`, `object`, `remove` on <a> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by Link)
    in Link (created by BaseLink)
    in BaseLink (created by Link)
    in Link (created by MaybeLink)
    in MaybeLink (created by Badge)
    in Badge (created by CollectionBadge)
    in CollectionBadge (created by EntityObjectLoader)
    in EntityObjectLoader (created by Connect(EntityObjectLoader))
    in Connect(EntityObjectLoader) (created by EntityType)
    in EntityType (created by EntityObjectLoader)
    in EntityObjectLoader (created by CollectionBadge)
    in CollectionBadge (created by Header)
    in div (created by Header)
    in div (created by Header)
    in div (created by Header)
    in Header (created by DashboardHeader)
    in DashboardHeader (created by LoadingAndErrorWrapper)
    in header (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Dashboard)
    in Dashboard (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp (created by Unknown)
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by DashboardApp)
    in DashboardApp (created by Title[DashboardApp])
    in Title[DashboardApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:48.598
Warning: Failed prop type: The prop `gridItemWidth` is marked as required in `DashCard`, but its value is `null`.
    in DashCard (created by DashboardGrid)
    in DashboardGrid (created by DashboardGrid)
    in DashboardGrid (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Dashboard)
    in Dashboard (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp (created by Unknown)
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by DashboardApp)
    in DashboardApp (created by Title[DashboardApp])
    in Title[DashboardApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:48.606 Error getting setting graph.x_axis._is_timeseries TypeError: data is undefined
    getDefault graph.js:371
    getComputedSetting settings.js:151
    getComputedSettings settings.js:99
    getComputedSettingsForSeries visualization.js:89
    transform Visualization.jsx:233
    componentWillMount Visualization.jsx:166
    React 3
settings.js:160
16:27:48.607 Error getting setting graph.x_axis._is_numeric TypeError: data is undefined
    getDefault graph.js:382
    getComputedSetting settings.js:151
    getComputedSettings settings.js:99
    getComputedSettingsForSeries visualization.js:89
    transform Visualization.jsx:233
    componentWillMount Visualization.jsx:166
    React 3
settings.js:160
16:27:48.607 Error getting setting graph.x_axis._is_histogram TypeError: _ref25[0].data is undefined
    getDefault graph.js:396
    getComputedSetting settings.js:151
    getComputedSettings settings.js:99
    getComputedSettingsForSeries visualization.js:89
    transform Visualization.jsx:233
    componentWillMount Visualization.jsx:166
    React 3
settings.js:160
16:27:48.607 Error getting setting graph.x_axis.title_text TypeError: series[0].data is undefined
    getDefault graph.js:543
    getComputedSetting settings.js:151
    getComputedSettings settings.js:99
    getComputedSettingsForSeries visualization.js:89
    transform Visualization.jsx:233
    componentWillMount Visualization.jsx:166
    React 3
settings.js:160
16:27:48.658 Error getting setting graph.x_axis._is_timeseries TypeError: data is undefined
    getDefault graph.js:371
    getComputedSetting settings.js:151
    getComputedSettings settings.js:99
    getComputedSettingsForSeries visualization.js:89
    transform Visualization.jsx:233
    componentWillMount Visualization.jsx:166
    React 3
settings.js:160
16:27:48.658 Error getting setting graph.x_axis._is_numeric TypeError: data is undefined
    getDefault graph.js:382
    getComputedSetting settings.js:151
    getComputedSettings settings.js:99
    getComputedSettingsForSeries visualization.js:89
    transform Visualization.jsx:233
    componentWillMount Visualization.jsx:166
    React 3
settings.js:160
16:27:48.658 Error getting setting graph.x_axis._is_histogram TypeError: _ref25[0].data is undefined
    getDefault graph.js:396
    getComputedSetting settings.js:151
    getComputedSettings settings.js:99
    getComputedSettingsForSeries visualization.js:89
    transform Visualization.jsx:233
    componentWillMount Visualization.jsx:166
    React 3
settings.js:160
16:27:48.658 Error getting setting graph.x_axis.title_text TypeError: series[0].data is undefined
    getDefault graph.js:543
    getComputedSetting settings.js:151
    getComputedSettings settings.js:99
    getComputedSettingsForSeries visualization.js:89
    transform Visualization.jsx:233
    componentWillMount Visualization.jsx:166
    React 3
settings.js:160
16:27:48.684
Uncaught Invariant Violation: findDOMNode was called on an unmounted component.
    invariant invariant.js:42
    findDOMNode React
    _getElement ExplicitSize.jsx:28
    wrapMethod makeAssimilatePrototype.js:15
    _updateSize ExplicitSize.jsx:93
invariant.js:42
16:27:48.684
Uncaught Invariant Violation: findDOMNode was called on an unmounted component.
    invariant invariant.js:42
    findDOMNode React
    _getElement ExplicitSize.jsx:28
    wrapMethod makeAssimilatePrototype.js:15
    _updateSize ExplicitSize.jsx:93
invariant.js:42
16:27:48.895
Warning: Unknown prop `maxHeight` on <table> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in table (created by ChartTooltip)
    in div
    in span warning.js:33
16:27:56.560
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See DashboardSharingEmbeddingModal > Triggerable[Modal] > a > ... > a. warning.js:33
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `SharingSidebar`. See https://fb.me/react-warning-keys for more information.
    in span (created by SharingSidebar)
    in SharingSidebar (created by Connect(SharingSidebar))
    in Connect(SharingSidebar) (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by EntityListLoader)
    in EntityListLoader (created by SharingSidebar)
    in SharingSidebar (created by Sidebars)
    in Sidebars (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Dashboard)
    in Dashboard (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp (created by Unknown)
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by DashboardApp)
    in DashboardApp (created by Title[DashboardApp])
    in Title[DashboardApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:27:59.331
Warning: Failed prop type: The prop `value` is marked as required in `Select`, but its value is `null`.
    in Select (created by Select)
    in Select (created by SharingSidebar)
    in div (created by SharingSidebar)
    in div (created by SharingSidebar)
    in div (created by SharingSidebar)
    in div (created by Sidebar)
    in div (created by Sidebar)
    in Sidebar (created by SharingSidebar)
    in SharingSidebar (created by Connect(SharingSidebar))
    in Connect(SharingSidebar) (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by EntityListLoader)
    in EntityListLoader (created by SharingSidebar)
    in SharingSidebar (created by Sidebars)
    in Sidebars (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Dashboard)
    in Dashboard (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp (created by Unknown)
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by DashboardApp)
    in DashboardApp (created by Title[DashboardApp])
    in Title[DashboardApp] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:28:32.455
Warning: Failed prop type: Invalid prop `sections` of type `object` supplied to `SettingsEditorApp`, expected `array`.
    in SettingsEditorApp (created by Title[SettingsEditorApp])
    in Title[SettingsEditorApp] (created by SettingsEditorApp)
    in SettingsEditorApp (created by RouterContext)
    in Unknown (created by Title[])
    in Title[] (created by RouterContext)
    in Unknown (created by UserIsAdmin(Component))
    in UserIsAdmin(Component) (created by Connect(UserIsAdmin(Component)))
    in Connect(UserIsAdmin(Component)) (created by UserIsAuthenticated(Connect(UserIsAdmin(Component))))
    in UserIsAuthenticated(Connect(UserIsAdmin(Component))) (created by Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))))
    in Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component))))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component))))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Connect(UserIsAdmin(Component)))))) (created by BackgroundApplicator)
    in BackgroundApplicator (created by Title[BackgroundApplicator])
    in Title[BackgroundApplicator] (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by ScrollToTop)
    in ScrollToTop (created by App)
    in App (created by App)
    in App (created by Title[App])
    in Title[App] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider warning.js:33
16:30:18.212 unreachable code after return statement
injected.js:7:2
```

Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**

1. Create a dashboard subscription via Slack.
2. Search for the pulse that Metabase created. 

**Expected behavior**
Dashboard subscriptions should not create pulses.

**Screenshots**
accidental-pulse

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.9.1+1",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.9.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.9.1+1",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2020-08-19",
      "tag": "v0.37.0-snapshot",
      "branch": "master",
      "hash": "bb267d3"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Severe. People will inadvertently create pulses they would need to archive.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #14190

I added a new `pulse.dashboard_id` column to solve this. Now we can look at that to check whether a Pulse is a Dashboard subscription pulse or not

### CODE REVIEW

**Comment by tsmacdonald** [comment]
> if creating a Dashboard Subscription creates an underlying internal Pulse object, shouldn't that Pulse have a NULLABLE `dashboard_id` foreign key to the Dashboard that owns it?

I wouldn't want to have two sources of truth (`pulse.dashboard_id` and the existing `report_card.dashboard_id`). I don't know why Rob chose the way we have it, but it does allow us to only send a subset of dashboard cards in the future (currently there's no UI for it).

It is true that if a dashboard is deleted, its pulses and its pulses' cards should also be deleted.

**Review by tsmacdonald — APPROVED** [review]

**Comment by robdaemon** [comment]
I don't think I added a migration for `pulse.dashboard_id`? IIRC, it's a synthetic field and not part of the database schema.

But I did add `report_card.dashboard_id` to the database itself.

The reason for `report_card.dashboard_id` was because that seemed the right level because of the `include_csv` / `include_xls` - I will admit it's not quite perfect because of the cascades that need to exist when a dashboard is renamed or deleted (up to the pulse itself), but I was stuck with adding on to the existing pulse mechanism.

**Comment by camsaul** [comment]
@robdaemon Not sure `report_card.dashboard_id` would make sense... a Card can belong to more than one Dashboard. That's why we have the DashboardCard model... it's a MtM relationship

**Comment by camsaul** [comment]
RE `pulse.dashboard_id` -- it seems like to get DashboardSubscriptions working we actually had to creating underlying Pulse and PulseCard objects -- it seems like the PulseCards are linked to the respective DashboardCards with an FK relationship but there's no corresponding relationship between Pulse and Dashboard. I was suggesting we create it

**Comment by robdaemon** [comment]
Ahhhh yeah that makes sense - I did it through report_card not realizing they belonged to multiple dashboards.

This part of the schema is a little confusing.

**Comment by camsaul** [comment]
@robdaemon It looks like now we just have `pulse_card.dashboard_card_id` added as part of the Dashboard subscription stuff. I don't see any migrations that add a `dashboard_id` to anything.

Having a `pulse.dashboard_id` for Pulses would make it easy to tell which ones are the "internal" Pulses used by Dashboard Subscriptions, and make it easy to migrate everything over at some point in the future. Right now you basically have to do something like

```sql
SELECT *
FROM pulse
INNER JOIN (
  SELECT pulse_id
  FROM pulse_card
  WHERE dashboard_card_id IS NOT NULL
  GROUP BY pulse_id
  HAVING count(*) > 1
) dashboard_pulse
ON pulse.id = dashboard_pulse.id
```

To get Pulses used for Dashboard Subscriptions rather than something like

```sql
SELECT *
FROM pulse
WHERE dashboard_id IS NOT NULL
```

**Comment by robdaemon** [comment]
There was a reason I did it this way.... and for the life of me I can't remember what it was. Let me look through the code to see if I can remember.

**Comment by camsaul** [comment]
The other benefit of having `pulse.dashboard_id` that we can make it `ON DELETE CASCADE` so if the Dashboard that owns it gets deleted the Pulse will get deleted automatically as well. I'd rather let the application DB do that for us than have to code it up in Clojure-land

**Comment by camsaul** [comment]
made the changes to add Pulse.dashboard_id -- @robdaemon or @tsmacdonald please re-review

**Review by akbaraliayubi — COMMENTED** [review]
9c7992fed3e7358556b86aef77788b526f1b766c

**Comment by tsmacdonald** [comment]
@akbaraliayubi what do you mean?

File: src/metabase/api/dashboard.clj [hunk 1]
```diff
@@ -138,7 +138,8 @@
   "Return a tuple of possible hashes that would be associated with executions of CARD. The first is the hash of the
   query dictionary as-is; the second is one with the `default-query-constraints`, which is how it will most likely be
   run."
-  [{:keys [dataset_query]}]
+  [{:keys [dataset_query], :as x}]
+  (println "x:" x) ; NOCOMMIT
```
Comment (tsmacdonald) [inline src/metabase/api/dashboard.clj:142]:
```suggestion
```

Comment (tsmacdonald) [inline src/metabase/api/dashboard.clj:142]:
```suggestion
  [{:keys [dataset_query]}]
  ```

File: src/metabase/models/dashboard.clj [hunk 2]
```diff
@@ -69,48 +69,51 @@
...
         (db/transaction
-          (db/update-where! Pulse {:id [:in pulse-ids]}
+          (db/update-where! Pulse {:dashboard_id dashboard-id}
             :name (:name dashboard))
           (pulse-card/bulk-create! new-pulse-cards))))))
 
+(defn- post-update
+  [dashboard]
+  (update-dashboard-subscription-pulses! dashboard))
+
```
Comment (tsmacdonald) [inline src/metabase/models/dashboard.clj:116]: always instructive to see little Cam improvements to code I wrote

**Review by tsmacdonald — APPROVED** [review]
Looks good to me

File: src/metabase/api/dashboard.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/api/dashboard.clj:142]: oops. thanks

File: src/metabase/models/dashboard.clj (hunk 2 above)
Comment (camsaul) [reply src/metabase/models/dashboard.clj:116]: sorry, this wasn't really necessary, but I thought it made the `post-update` stuff a little clearer and wouldn't get hairy if we went and added more stuff to `post-update` in the future. Also it lets us test `update-dashboard-subscription-pulses!` by itself if we were so inclined

Comment (tsmacdonald) [reply src/metabase/models/dashboard.clj:116]: I was referring to all of the minor edits above, not just pulling this function out specifically.
