### PR TITLE
BigQuery should qualify columns from source query with `source` in the `SELECT` clause

### LINKED ISSUE #18742: BigQuery can cause conflict with some column names like `source`
**Describe the bug**
New BigQuery driver can cause conflict with some column names like `source` (possibly others too)
Regression compared to old driver.

**To Reproduce**
1. Native query > BigQuery > ``select 1 as `val`, '2' as `source` `` - save as "Q1"
2. Click "Explore results"
3. Summarize Count grouped by "source" column
4. Errors with `Cannot GROUP BY field references from SELECT list alias source`

<details><summary>Full stacktrace</summary>

```
[3957e5ee-1718-4643-873c-48da7f48b18d] 2021-10-28T20:03:45+02:00 INFO metabase.api.dataset Source query for this query is Card 3,471
[3957e5ee-1718-4643-873c-48da7f48b18d] 2021-10-28T20:03:46+02:00 INFO metabase.query-processor.middleware.fetch-source-query Fetched source query from Card 3,471: 
 {:native "select 1 as `val`, '2' as `source`"}

[3957e5ee-1718-4643-873c-48da7f48b18d] 2021-10-28T20:03:46+02:00 INFO metabase.query-processor.middleware.fetch-source-query Fetched source query from Card 3,471: 
 {:native "select 1 as `val`, '2' as `source`"}

[3957e5ee-1718-4643-873c-48da7f48b18d] 2021-10-28T20:03:48+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 50,
 :started_at #t "2021-10-28T18:03:45.996707Z[GMT]",
 :via
 [{:status :failed,
   :class com.google.cloud.bigquery.BigQueryException,
   :error "Cannot GROUP BY field references from SELECT list alias source at [2:119]",
   :stacktrace
   ["com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)"
    "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:637)"
    "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1255)"
    "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1252)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
    "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
    "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
    "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1251)"
    "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1239)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__77637.invoke(bigquery_cloud_sdk.clj:169)"]}
  {:status :failed,
   :class java.util.concurrent.ExecutionException,
   :error
   "com.google.cloud.bigquery.BigQueryException: Cannot GROUP BY field references from SELECT list alias source at [2:119]",
   :stacktrace
   ["java.base/java.util.concurrent.FutureTask.report(Unknown Source)"
    "java.base/java.util.concurrent.FutureTask.get(Unknown Source)"
    "clojure.core$deref_future.invokeStatic(core.clj:2304)"
    "clojure.core$future_call$reify__8477.deref(core.clj:6976)"
    "clojure.core$deref.invokeStatic(core.clj:2324)"
    "clojure.core$deref.invoke(core.clj:2310)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:157)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:153)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:195)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:193)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__77738.invoke(bigquery_cloud_sdk.clj:255)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:263)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:247)"
    "driver.bigquery_cloud_sdk$fn__77744.invokeStatic(bigquery_cloud_sdk.clj:283)"
    "driver.bigquery_cloud_sdk$fn__77744.invoke(bigquery_cloud_sdk.clj:275)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50069.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__50556.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__48442.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__50930.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51923.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51967.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__50126.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__36959.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__42104.invoke(annotate.clj:623)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46603.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51107.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46995.invoke(cumulative_aggregations.clj:60)"
    "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87847.invoke(row_level_restrictions.clj:338)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__46933.invoke(visualization_settings.clj:63)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48040.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__51693.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51229.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__48059.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__51281.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__47431.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__46906.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__45853.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__46246.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__50481.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50779.invoke(add_implicit_clauses.clj:147)"
    "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87847.invoke(row_level_restrictions.clj:338)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48427.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47808.invoke(add_source_metadata.clj:123)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__86233.invoke(column_level_perms_check.clj:30)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__51029.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__49378.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46227.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__49032.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46300.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__52351.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48811.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51296.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50790$fn__50794.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50790.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46844.invoke(fetch_source_query.clj:272)"
    "query_processor.middleware.store$initialize_store$fn__47032$fn__47033.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__47032.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__51079.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__51086.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48757.invoke(add_rows_truncated.clj:35)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__40965.invoke(handle_audit_queries.clj:130)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__50055.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48775.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__51065.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51376.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___40253$thunk__40254.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___40253.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___40262$fn__40265.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___40262.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
    "query_processor$fn__52399$process_query_and_save_execution_BANG___52408$fn__52411.invoke(query_processor.clj:253)"
    "query_processor$fn__52399$process_query_and_save_execution_BANG___52408.invoke(query_processor.clj:245)"
    "query_processor$fn__52443$process_query_and_save_with_max_results_constraints_BANG___52452$fn__52455.invoke(query_processor.clj:265)"
    "query_processor$fn__52443$process_query_and_save_with_max_results_constraints_BANG___52452.invoke(query_processor.clj:258)"
    "api.dataset$run_query_async$fn__58590.invoke(dataset.clj:64)"
    "query_processor.streaming$streaming_response_STAR_$fn__44762$fn__44763.invoke(streaming.clj:148)"
    "query_processor.streaming$streaming_response_STAR_$fn__44762.invoke(streaming.clj:147)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$fn__25100.invoke(streaming_response.clj:84)"]}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.bigquery_cloud_sdk$throw_invalid_query.invokeStatic(bigquery_cloud_sdk.clj:149)"
    "driver.bigquery_cloud_sdk$throw_invalid_query.invoke(bigquery_cloud_sdk.clj:148)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:191)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:153)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:195)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:193)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__77738.invoke(bigquery_cloud_sdk.clj:255)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:263)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:247)"
    "driver.bigquery_cloud_sdk$fn__77744.invokeStatic(bigquery_cloud_sdk.clj:283)"
    "driver.bigquery_cloud_sdk$fn__77744.invoke(bigquery_cloud_sdk.clj:275)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50069.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__50556.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__48442.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__50930.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51923.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51967.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__50126.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__36959.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__42104.invoke(annotate.clj:623)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46603.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51107.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46995.invoke(cumulative_aggregations.clj:60)"
    "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87847.invoke(row_level_restrictions.clj:338)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__46933.invoke(visualization_settings.clj:63)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48040.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__51693.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51229.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__48059.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__51281.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__47431.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__46906.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__45853.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__46246.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__50481.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50779.invoke(add_implicit_clauses.clj:147)"
    "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87847.invoke(row_level_restrictions.clj:338)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48427.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47808.invoke(add_source_metadata.clj:123)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__86233.invoke(column_level_perms_check.clj:30)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__51029.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__49378.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46227.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__49032.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46300.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__52351.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48811.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51296.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50790$fn__50794.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50790.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46844.invoke(fetch_source_query.clj:272)"
    "query_processor.middleware.store$initialize_store$fn__47032$fn__47033.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__47032.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__51079.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__51086.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48757.invoke(add_rows_truncated.clj:35)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__40965.invoke(handle_audit_queries.clj:130)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__50055.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48775.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__51065.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51376.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___40253$thunk__40254.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___40253.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___40262$fn__40265.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___40262.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
    "query_processor$fn__52399$process_query_and_save_execution_BANG___52408$fn__52411.invoke(query_processor.clj:253)"
    "query_processor$fn__52399$process_query_and_save_execution_BANG___52408.invoke(query_processor.clj:245)"
    "query_processor$fn__52443$process_query_and_save_with_max_results_constraints_BANG___52452$fn__52455.invoke(query_processor.clj:265)"
    "query_processor$fn__52443$process_query_and_save_with_max_results_constraints_BANG___52452.invoke(query_processor.clj:258)"
    "api.dataset$run_query_async$fn__58590.invoke(dataset.clj:64)"
    "query_processor.streaming$streaming_response_STAR_$fn__44762$fn__44763.invoke(streaming.clj:148)"
    "query_processor.streaming$streaming_response_STAR_$fn__44762.invoke(streaming.clj:147)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$fn__25100.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "-- Metabase:: userID: 44 queryType: MBQL queryHash: 3bfd12fd4f92f65639814b757af953132434491f532833b47d99f093c7f9ce86\nSELECT `source`.`source` AS `source`, count(*) AS `count` FROM (select 1 as `val`, '2' as `source`) `source` GROUP BY `source`.`source` ORDER BY `source`.`source` ASC",
    :parameters nil}}],
 :error_type :invalid-query,
 :json_query
 {:database 50,
  :query
  {:source-table "card__3471", :aggregation [["count"]], :breakout [["field" "source" {:base-type "type/Text"}]]},
  :type "query",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT `source`.`source` AS `source`, count(*) AS `count` FROM (select 1 as `val`, '2' as `source`) `source` GROUP BY `source`.`source` ORDER BY `source`.`source` ASC",
  :params nil,
  :table-name "source",
  :mbql? true},
 :status :failed,
 :class com.google.api.client.googleapis.json.GoogleJsonResponseException,
 :stacktrace
 ["com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:444)"
  "com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:542)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:475)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592)"
  "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:635)"
  "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1255)"
  "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1252)"
  "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
  "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
  "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
  "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1251)"
  "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1239)"
  "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__77637.invoke(bigquery_cloud_sdk.clj:169)"],
 :card_id 3471,
 :context :ad-hoc,
 :error
 "400 Bad Request\n{\n  \"code\" : 400,\n  \"errors\" : [ {\n    \"domain\" : \"global\",\n    \"location\" : \"q\",\n    \"locationType\" : \"parameter\",\n    \"message\" : \"Cannot GROUP BY field references from SELECT list alias source at [2:119]\",\n    \"reason\" : \"invalidQuery\"\n  } ],\n  \"message\" : \"Cannot GROUP BY field references from SELECT list alias source at [2:119]\",\n  \"status\" : \"INVALID_ARGUMENT\"\n}",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 50,
  :query
  {:aggregation [[:aggregation-options [:count] {:name "count"}]],
   :breakout [[:field "source" {:base-type :type/Text}]],
   :source-card-id 3471,
   :source-metadata
   [{:name "val",
     :display_name "val",
     :base_type :type/Integer,
     :effective_type :type/Integer,
     :field_ref [:field "val" {:base-type :type/Integer}],
     :semantic_type nil,
     :fingerprint
     {:global {:distinct-count 1, :nil% 0}, :type {:type/Number {:min 1, :q1 1, :q3 1, :max 1, :sd nil, :avg 1}}}}
    {:name "source",
     :display_name "source",
     :base_type :type/Text,
     :effective_type :type/Text,
     :field_ref [:field "source" {:base-type :type/Text}],
     :semantic_type :type/Source,
     :fingerprint
     {:global {:distinct-count 1, :nil% 0},
      :type {:type/Text {:percent-json 0, :percent-url 0, :percent-email 0, :percent-state 0, :average-length 1}}}}],
   :order-by [[:asc [:field "source" {:base-type :type/Text}]]],
   :source-query {:native "select 1 as `val`, '2' as `source`"}},
  :type :query,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 44,
   :context :ad-hoc,
   :card-id 3471,
   :nested? true,
   :query-hash
   [59, -3, 18, -3, 79, -110, -10, 86, 57, -127, 75, 117, 122, -7, 83, 19, 36, 52, 73, 31, 83, 40, 51, -76, 125, -103,
    -16, -109, -57, -7, -50, -122]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

[3957e5ee-1718-4643-873c-48da7f48b18d] 2021-10-28T20:03:48+02:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 2.3 s (8 DB calls) App DB connections: 0/15 Jetty threads: 2/50 (4 idle, 0 queued) (147 total active threads) Queries in flight: 0 (0 queued)
```

</details>

**Information about your Metabase Installation:**
Tested 0.41.1 with old and new driver - regression on new driver

### LINKED ISSUE #20362: BigQuery nested query with ambiguous columns causes error
**Describe the bug**
After upgrade version v0.42.0, the nested query on BigQuery database generated error.

**Screenshots**
image

And the generated query is below:

image

### LINKED ISSUE #20413: BigQuery incorrectly aliasing, which can make the query fail
**Describe the bug**
BigQuery incorrectly aliasing, which can make the query fail.

**To Reproduce**
1. Admin > Data Model > **BigQuery** Sample > Products - rename to "Products Renamed"
2. Question > BigQuery Sample > Orders
3. Join "Products Renamed"
4. Custom Column `1 + 1` as "CC" (just to trigger nested query)
5. Filter "Products Renamed".Category=`Doohickey`
image

<details><summary>Full stacktrace</summary>

```
2022-02-10 09:33:17,223 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 43,
 :started_at #t "2022-02-10T09:33:15.661477+01:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class com.google.cloud.bigquery.BigQueryException,
   :error "Unrecognized name: `Products Renamed__category` at [2:1960]",
   :stacktrace
   ["com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)"
    "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:637)"
    "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1255)"
    "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1252)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
    "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
    "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
    "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1251)"
    "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1239)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__89607.invoke(bigquery_cloud_sdk.clj:184)"]}
  {:status :failed,
   :class java.util.concurrent.ExecutionException,
   :error "com.google.cloud.bigquery.BigQueryException: Unrecognized name: `Products Renamed__category` at [2:1960]",
   :stacktrace
   ["java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)"
    "java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)"
    "clojure.core$deref_future.invokeStatic(core.clj:2304)"
    "clojure.core$future_call$reify__8477.deref(core.clj:6976)"
    "clojure.core$deref.invokeStatic(core.clj:2324)"
    "clojure.core$deref.invoke(core.clj:2310)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:172)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:168)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:210)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:208)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__89708.invoke(bigquery_cloud_sdk.clj:270)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:278)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:262)"
    "driver.bigquery_cloud_sdk$fn__89714.invokeStatic(bigquery_cloud_sdk.clj:298)"
    "driver.bigquery_cloud_sdk$fn__89714.invoke(bigquery_cloud_sdk.clj:290)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49659.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__50405.invoke(check_features.clj:42)"
    "query_processor.middleware.limit$limit$fn__48032.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__50788.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51821.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51865.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49716.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39821.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__44587.invoke(annotate.clj:659)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46329.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51010.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46725.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__46663.invoke(visualization_settings.clj:63)"
    "query_processor.middleware.fix_bad_references$fix_bad_references_middleware$fn__50975.invoke(fix_bad_references.clj:91)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47610.invoke(resolve_joined_fields.clj:111)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__51591.invoke(resolve_joins.clj:176)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51133.invoke(add_implicit_joins.clj:202)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47629.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__51185.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46997.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__46636.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__39550.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45971.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__50342.invoke(add_dimension_projections.clj:487)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50636.invoke(add_implicit_clauses.clj:164)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48017.invoke(upgrade_field_literals.clj:117)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47374.invoke(add_source_metadata.clj:125)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50887.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48974.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45952.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48628.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46025.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__52249.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48407.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51200.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50647$fn__50652.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50647.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46571.invoke(fetch_source_query.clj:286)"
    "query_processor.middleware.store$initialize_store$fn__46762$fn__46763.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46762.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50982.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50989.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48353.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49645.invoke(results_metadata.clj:82)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48371.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50923.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51280.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___43323$thunk__43324.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___43323.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___43332$fn__43335.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___43332.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:245)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:241)"
    "query_processor$fn__52297$process_query_and_save_execution_BANG___52306$fn__52309.invoke(query_processor.clj:256)"
    "query_processor$fn__52297$process_query_and_save_execution_BANG___52306.invoke(query_processor.clj:249)"
    "query_processor$fn__52341$process_query_and_save_with_max_results_constraints_BANG___52350$fn__52353.invoke(query_processor.clj:268)"
    "query_processor$fn__52341$process_query_and_save_with_max_results_constraints_BANG___52350.invoke(query_processor.clj:261)"
    "api.dataset$run_query_async$fn__65276.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__38459$fn__38460.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__38459.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__26889.invoke(streaming_response.clj:84)"]}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.bigquery_cloud_sdk$throw_invalid_query.invokeStatic(bigquery_cloud_sdk.clj:164)"
    "driver.bigquery_cloud_sdk$throw_invalid_query.invoke(bigquery_cloud_sdk.clj:163)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:206)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:168)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:210)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:208)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__89708.invoke(bigquery_cloud_sdk.clj:270)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:278)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:262)"
    "driver.bigquery_cloud_sdk$fn__89714.invokeStatic(bigquery_cloud_sdk.clj:298)"
    "driver.bigquery_cloud_sdk$fn__89714.invoke(bigquery_cloud_sdk.clj:290)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49659.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__50405.invoke(check_features.clj:42)"
    "query_processor.middleware.limit$limit$fn__48032.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__50788.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51821.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51865.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49716.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39821.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__44587.invoke(annotate.clj:659)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46329.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51010.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46725.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__46663.invoke(visualization_settings.clj:63)"
    "query_processor.middleware.fix_bad_references$fix_bad_references_middleware$fn__50975.invoke(fix_bad_references.clj:91)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47610.invoke(resolve_joined_fields.clj:111)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__51591.invoke(resolve_joins.clj:176)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51133.invoke(add_implicit_joins.clj:202)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47629.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__51185.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46997.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__46636.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__39550.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45971.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__50342.invoke(add_dimension_projections.clj:487)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50636.invoke(add_implicit_clauses.clj:164)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48017.invoke(upgrade_field_literals.clj:117)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47374.invoke(add_source_metadata.clj:125)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50887.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48974.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45952.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48628.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46025.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__52249.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48407.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51200.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50647$fn__50652.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50647.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46571.invoke(fetch_source_query.clj:286)"
    "query_processor.middleware.store$initialize_store$fn__46762$fn__46763.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46762.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50982.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50989.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48353.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49645.invoke(results_metadata.clj:82)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48371.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50923.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51280.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___43323$thunk__43324.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___43323.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___43332$fn__43335.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___43332.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:245)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:241)"
    "query_processor$fn__52297$process_query_and_save_execution_BANG___52306$fn__52309.invoke(query_processor.clj:256)"
    "query_processor$fn__52297$process_query_and_save_execution_BANG___52306.invoke(query_processor.clj:249)"
    "query_processor$fn__52341$process_query_and_save_with_max_results_constraints_BANG___52350$fn__52353.invoke(query_processor.clj:268)"
    "query_processor$fn__52341$process_query_and_save_with_max_results_constraints_BANG___52350.invoke(query_processor.clj:261)"
    "api.dataset$run_query_async$fn__65276.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__38459$fn__38460.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__38459.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__26889.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: d33e9441d379c580b218903cbfa36e917fa23a05c40b74c96503004b8205b9c2\nSELECT `id` AS `id`, `user_id` AS `user_id`, `product_id` AS `product_id`, `subtotal` AS `subtotal`, `tax` AS `tax`, `total` AS `total`, `discount` AS `discount`, `created_at` AS `created_at`, `quantity` AS `quantity`, `CC` AS `CC`, `Products Renamed__id` AS `Products_Renamed__id_4408b1be`, `Products Renamed__ean` AS `Products_Renamed__ean_b48361a7`, `Products Renamed__title` AS `Products_Renamed__title_325dad00`, `Products Renamed__category` AS `Products_Renamed__category_1f39b42c`, `Products Renamed__vendor` AS `Products_Renamed__vendor_cb8bd978`, `Products Renamed__price` AS `Products_Renamed__price_1ab6323c`, `Products Renamed__rating` AS `Products_Renamed__rating_3eb4d2e2`, `Products Renamed__created_at` AS `Products_Renamed__created_at_8de4c02f` FROM (SELECT `v3_sample_dataset.orders`.`id` AS `id`, `v3_sample_dataset.orders`.`user_id` AS `user_id`, `v3_sample_dataset.orders`.`product_id` AS `product_id`, `v3_sample_dataset.orders`.`subtotal` AS `subtotal`, `v3_sample_dataset.orders`.`tax` AS `tax`, `v3_sample_dataset.orders`.`total` AS `total`, `v3_sample_dataset.orders`.`discount` AS `discount`, `v3_sample_dataset.orders`.`created_at` AS `created_at`, `v3_sample_dataset.orders`.`quantity` AS `quantity`, (1 + 1) AS `CC`, `Products Renamed`.`id` AS `Products_Renamed__id_4408b1be`, `Products Renamed`.`ean` AS `Products_Renamed__ean_b48361a7`, `Products Renamed`.`title` AS `Products_Renamed__title_325dad00`, `Products Renamed`.`category` AS `Products_Renamed__category_1f39b42c`, `Products Renamed`.`vendor` AS `Products_Renamed__vendor_cb8bd978`, `Products Renamed`.`price` AS `Products_Renamed__price_1ab6323c`, `Products Renamed`.`rating` AS `Products_Renamed__rating_3eb4d2e2`, `Products Renamed`.`created_at` AS `Products_Renamed__created_at_8de4c02f` FROM `v3_sample_dataset.orders` LEFT JOIN `v3_sample_dataset.products` `Products Renamed` ON `v3_sample_dataset.orders`.`product_id` = `Products Renamed`.`id`) `source` WHERE `Products Renamed__category` = ? LIMIT 2000",
    :parameters ("Doohickey")}}],
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :query
  {:source-table 6554,
   :joins
   [{:fields "all",
     :source-table 6552,
     :condition ["=" ["field" 38264 nil] ["field" 38247 {:join-alias "Products Renamed"}]],
     :alias "Products Renamed"}],
   :filter ["=" ["field" 38241 {:join-alias "Products Renamed"}] "Doohickey"],
   :expressions {:CC ["+" 1 1]}},
  :database 43,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT `id` AS `id`, `user_id` AS `user_id`, `product_id` AS `product_id`, `subtotal` AS `subtotal`, `tax` AS `tax`, `total` AS `total`, `discount` AS `discount`, `created_at` AS `created_at`, `quantity` AS `quantity`, `CC` AS `CC`, `Products Renamed__id` AS `Products_Renamed__id_4408b1be`, `Products Renamed__ean` AS `Products_Renamed__ean_b48361a7`, `Products Renamed__title` AS `Products_Renamed__title_325dad00`, `Products Renamed__category` AS `Products_Renamed__category_1f39b42c`, `Products Renamed__vendor` AS `Products_Renamed__vendor_cb8bd978`, `Products Renamed__price` AS `Products_Renamed__price_1ab6323c`, `Products Renamed__rating` AS `Products_Renamed__rating_3eb4d2e2`, `Products Renamed__created_at` AS `Products_Renamed__created_at_8de4c02f` FROM (SELECT `v3_sample_dataset.orders`.`id` AS `id`, `v3_sample_dataset.orders`.`user_id` AS `user_id`, `v3_sample_dataset.orders`.`product_id` AS `product_id`, `v3_sample_dataset.orders`.`subtotal` AS `subtotal`, `v3_sample_dataset.orders`.`tax` AS `tax`, `v3_sample_dataset.orders`.`total` AS `total`, `v3_sample_dataset.orders`.`discount` AS `discount`, `v3_sample_dataset.orders`.`created_at` AS `created_at`, `v3_sample_dataset.orders`.`quantity` AS `quantity`, (1 + 1) AS `CC`, `Products Renamed`.`id` AS `Products_Renamed__id_4408b1be`, `Products Renamed`.`ean` AS `Products_Renamed__ean_b48361a7`, `Products Renamed`.`title` AS `Products_Renamed__title_325dad00`, `Products Renamed`.`category` AS `Products_Renamed__category_1f39b42c`, `Products Renamed`.`vendor` AS `Products_Renamed__vendor_cb8bd978`, `Products Renamed`.`price` AS `Products_Renamed__price_1ab6323c`, `Products Renamed`.`rating` AS `Products_Renamed__rating_3eb4d2e2`, `Products Renamed`.`created_at` AS `Products_Renamed__created_at_8de4c02f` FROM `v3_sample_dataset.orders` LEFT JOIN `v3_sample_dataset.products` `Products Renamed` ON `v3_sample_dataset.orders`.`product_id` = `Products Renamed`.`id`) `source` WHERE `Products Renamed__category` = ? LIMIT 2000",
  :params ("Doohickey"),
  :table-name "orders",
  :mbql? true},
 :status :failed,
 :class com.google.api.client.googleapis.json.GoogleJsonResponseException,
 :stacktrace
 ["com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)"
  "com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)"
  "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:635)"
  "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1255)"
  "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1252)"
  "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
  "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
  "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
  "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1251)"
  "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1239)"
  "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__89607.invoke(bigquery_cloud_sdk.clj:184)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "400 Bad Request\nPOST https://www.googleapis.com/bigquery/v2/projects/metabase-bigquery-driver/queries\n{\n  \"code\" : 400,\n  \"errors\" : [ {\n    \"domain\" : \"global\",\n    \"location\" : \"q\",\n    \"locationType\" : \"parameter\",\n    \"message\" : \"Unrecognized name: `Products Renamed__category` at [2:1960]\",\n    \"reason\" : \"invalidQuery\"\n  } ],\n  \"message\" : \"Unrecognized name: `Products Renamed__category` at [2:1960]\",\n  \"status\" : \"INVALID_ARGUMENT\"\n}",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-table 6554,
   :filter
   [:=
    [:field 38241 {:join-alias "Products Renamed"}]
    [:value
     "Doohickey"
     {:base_type :type/Text,
      :effective_type :type/Text,
      :coercion_strategy nil,
      :semantic_type :type/Category,
      :database_type "STRING",
      :name "category"}]],
   :expressions {:CC [:+ 1 1]},
   :fields
   [[:field 38269 nil]
    [:field 38267 nil]
    [:field 38264 nil]
    [:field 38265 nil]
    [:field 38261 nil]
    [:field 38263 nil]
    [:field 38268 nil]
    [:field 38266 {:temporal-unit :default}]
    [:field 38262 nil]
    [:expression "CC"]
    [:field 38247 {:join-alias "Products Renamed"}]
    [:field 38243 {:join-alias "Products Renamed"}]
    [:field 38240 {:join-alias "Products Renamed"}]
    [:field 38241 {:join-alias "Products Renamed"}]
    [:field 38244 {:join-alias "Products Renamed"}]
    [:field 38246 {:join-alias "Products Renamed"}]
    [:field 38242 {:join-alias "Products Renamed"}]
    [:field 38245 {:temporal-unit :default, :join-alias "Products Renamed"}]],
   :joins
   [{:strategy :left-join,
     :fields
     [[:field 38247 {:join-alias "Products Renamed"}]
      [:field 38243 {:join-alias "Products Renamed"}]
      [:field 38240 {:join-alias "Products Renamed"}]
      [:field 38241 {:join-alias "Products Renamed"}]
      [:field 38244 {:join-alias "Products Renamed"}]
      [:field 38246 {:join-alias "Products Renamed"}]
      [:field 38242 {:join-alias "Products Renamed"}]
      [:field 38245 {:temporal-unit :default, :join-alias "Products Renamed"}]],
     :source-table 6552,
     :condition [:= [:field 38264 nil] [:field 38247 {:join-alias "Products Renamed"}]],
     :alias "Products Renamed"}],
   :limit 2000},
  :database 43,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash
   [-45, 62, -108, 65, -45, 121, -59, -128, -78, 24, -112, 60, -65, -93, 110, -111, 127, -94, 58, 5, -60, 11, 116, -55,
    101, 3, 0, 75, -126, 5, -71, -62]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

2022-02-10 09:33:17,237 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.6 s (22 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (3 idle, 0 queued) (111 total active threads) Queries in flight: 0 (0 queued)
```

</details>

**Information about your Metabase Installation:**
0.42.0 - works on 0.41.6

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #20362
~Fixxes #20413~

This was caused by a misunderstaning on our part. In #18772 (to fixx #18742) we removed the `source` alias columns in the source query specifically for BigQuery. With some of the recent changes I made this ended up happening more consistently which broke queries.

This is actually the wrong behavior. We should always be qualifying stuff with `source` in the `SELECT` clause, but nowhere else, which we're already doing. By removing the special casing things now work as expected.

### CODE REVIEW

File: test/metabase/query_processor_test/explicit_joins_test.clj [hunk 1]
```diff
@@ -690,39 +690,42 @@
...
+              (mt/with-native-query-testing-context query
+                (let [results (qp/process-query query)]
+                  (when (#{:postgres :h2} driver/*driver*)
+                    (is (= ["Category" "Count" "Q2 → Category" "Q2 → Sum" "Q3 → Category" "Q3 → Avg"]
+                           (map :display_name (get-in results [:data :results_metadata :columns])))))
+                  (is (= [["Doohickey" 42 "Doohickey" 2185.89 "Doohickey" 3.73]
+                          ["Gadget"    53 "Gadget"    3019.2  "Gadget"    3.43]
+                          ["Gizmo"     51 "Gizmo"     2834.88 "Gizmo"     3.64]
+                          ["Widget"    54 "Widget"    3109.31 "Widget"    3.15]]
+                         (mt/formatted-rows [str int str 2.0 str 2.0] results))))))))))))
```
Comment (camsaul) [inline test/metabase/query_processor_test/explicit_joins_test.clj:731]: This test **should** have caught this regression but like a big dummy I wrote it to only run against H2. I tweaked it to run against all relevant drivers now

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj [hunk 2]
```diff
@@ -819,17 +819,20 @@
...
+        (is (sql= '{:select   [source.source    AS source
+                               count (*)        AS count]
+                    :from     [(select 1 as val "2" as source)
+                               source]
+                    :group-by [source]
+                    :order-by [source ASC]}
+                  query))
+        (mt/with-native-query-testing-context query
+          (is (= [["2" 1]]
+                 (mt/rows (qp/process-query query)))))))))
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj:838]: Tweaked this test to not only verify that the SQL is correct but to also run the query to make sure it actually works. Just to confirm that the SQL we generated is actually valid

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj [hunk 3]
```diff
@@ -511,12 +511,8 @@
...
     ;; project ID no matter what
     (binding [*field-is-from-join-or-source-query?* (not (integer? source-table))]
-      ;; if this Field is from a source table DO NOT qualify it at all.
-      (let [field-clause (cond-> field-clause
-                           (= source-table ::add/source)
-                           (mbql.u/update-field-options assoc ::add/source-table ::add/none))]
-        (-> (parent-method driver field-clause)
-            (with-temporal-type (temporal-type field-clause)))))))
+      (-> (parent-method driver field-clause)
+          (with-temporal-type (temporal-type field-clause))))))
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:515]: This is the actual fix. Just removing the logic that excludes the `source.` qualification for Fields in the `SELECT` clause.

**Review by flamber — COMMENTED** [review]
It fixes #20362, but #20413 still fails.

<details><summary>Full stacktrace</summary>

```
2022-02-11 15:34:29,962 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 43,
 :started_at #t "2022-02-11T15:34:27.305650+01:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class com.google.cloud.bigquery.BigQueryException,
   :error "Name Products Renamed__category not found inside source at [2:2131]",
   :stacktrace
   ["com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)"
    "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:637)"
    "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1255)"
    "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1252)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
    "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
    "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
    "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1251)"
    "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1239)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__80427.invoke(bigquery_cloud_sdk.clj:184)"]}
  {:status :failed,
   :class java.util.concurrent.ExecutionException,
   :error
   "com.google.cloud.bigquery.BigQueryException: Name Products Renamed__category not found inside source at [2:2131]",
   :stacktrace
   ["java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)"
    "java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)"
    "clojure.core$deref_future.invokeStatic(core.clj:2304)"
    "clojure.core$future_call$reify__8477.deref(core.clj:6976)"
    "clojure.core$deref.invokeStatic(core.clj:2324)"
    "clojure.core$deref.invoke(core.clj:2310)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:172)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:168)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:210)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:208)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__80528.invoke(bigquery_cloud_sdk.clj:270)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:278)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:262)"
    "driver.bigquery_cloud_sdk$fn__80534.invokeStatic(bigquery_cloud_sdk.clj:298)"
    "driver.bigquery_cloud_sdk$fn__80534.invoke(bigquery_cloud_sdk.clj:290)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___50681.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46498.invoke(permissions.clj:108)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49622.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__52123$combined_post_process__52128$combined_post_process_STAR___52129.invoke(query_processor.clj:201)"
    "query_processor$fn__52123$combined_pre_process__52124$combined_pre_process_STAR___52125.invoke(query_processor.clj:198)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50602$fn__50607.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:59)"
    "driver$do_with_driver.invoke(driver.clj:55)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50602.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46741.invoke(fetch_source_query.clj:281)"
    "query_processor.middleware.store$initialize_store$fn__46929$fn__46930.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46929.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50874.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__47998.invoke(constraints.clj:52)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50813.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51154.invoke(catch_exceptions.clj:162)"
    "query_processor.reducible$async_qp$qp_STAR___43526$thunk__43528.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___43526.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___43526.invoke(reducible.clj:91)"
    "query_processor.reducible$sync_qp$qp_STAR___43537.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:325)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:321)"
    "query_processor$fn__52171$process_query_and_save_execution_BANG___52180$fn__52183.invoke(query_processor.clj:336)"
    "query_processor$fn__52171$process_query_and_save_execution_BANG___52180.invoke(query_processor.clj:329)"
    "query_processor$fn__52215$process_query_and_save_with_max_results_constraints_BANG___52224$fn__52227.invoke(query_processor.clj:348)"
    "query_processor$fn__52215$process_query_and_save_with_max_results_constraints_BANG___52224.invoke(query_processor.clj:341)"
    "api.dataset$run_query_async$fn__65176.invoke(dataset.clj:68)"
    "query_processor.streaming$streaming_response_STAR_$fn__38677$fn__38678.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__38677.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__27051.invoke(streaming_response.clj:84)"]}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.bigquery_cloud_sdk$throw_invalid_query.invokeStatic(bigquery_cloud_sdk.clj:164)"
    "driver.bigquery_cloud_sdk$throw_invalid_query.invoke(bigquery_cloud_sdk.clj:163)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:206)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:168)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:210)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:208)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__80528.invoke(bigquery_cloud_sdk.clj:270)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:278)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:262)"
    "driver.bigquery_cloud_sdk$fn__80534.invokeStatic(bigquery_cloud_sdk.clj:298)"
    "driver.bigquery_cloud_sdk$fn__80534.invoke(bigquery_cloud_sdk.clj:290)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___50681.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46498.invoke(permissions.clj:108)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49622.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__52123$combined_post_process__52128$combined_post_process_STAR___52129.invoke(query_processor.clj:201)"
    "query_processor$fn__52123$combined_pre_process__52124$combined_pre_process_STAR___52125.invoke(query_processor.clj:198)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50602$fn__50607.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:59)"
    "driver$do_with_driver.invoke(driver.clj:55)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50602.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46741.invoke(fetch_source_query.clj:281)"
    "query_processor.middleware.store$initialize_store$fn__46929$fn__46930.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46929.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50874.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__47998.invoke(constraints.clj:52)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50813.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51154.invoke(catch_exceptions.clj:162)"
    "query_processor.reducible$async_qp$qp_STAR___43526$thunk__43528.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___43526.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___43526.invoke(reducible.clj:91)"
    "query_processor.reducible$sync_qp$qp_STAR___43537.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:325)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:321)"
    "query_processor$fn__52171$process_query_and_save_execution_BANG___52180$fn__52183.invoke(query_processor.clj:336)"
    "query_processor$fn__52171$process_query_and_save_execution_BANG___52180.invoke(query_processor.clj:329)"
    "query_processor$fn__52215$process_query_and_save_with_max_results_constraints_BANG___52224$fn__52227.invoke(query_processor.clj:348)"
    "query_processor$fn__52215$process_query_and_save_with_max_results_constraints_BANG___52224.invoke(query_processor.clj:341)"
    "api.dataset$run_query_async$fn__65176.invoke(dataset.clj:68)"
    "query_processor.streaming$streaming_response_STAR_$fn__38677$fn__38678.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__38677.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__27051.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: e8905cd11ab4379cf5f6a947c922996e9aa1402177087a2ceccda7e1a207668e\nSELECT `source`.`id` AS `id`, `source`.`user_id` AS `user_id`, `source`.`product_id` AS `product_id`, `source`.`subtotal` AS `subtotal`, `source`.`tax` AS `tax`, `source`.`total` AS `total`, `source`.`discount` AS `discount`, `source`.`created_at` AS `created_at`, `source`.`quantity` AS `quantity`, `source`.`CC` AS `CC`, `source`.`Products Renamed__id` AS `Products_Renamed__id_4408b1be`, `source`.`Products Renamed__ean` AS `Products_Renamed__ean_b48361a7`, `source`.`Products Renamed__title` AS `Products_Renamed__title_325dad00`, `source`.`Products Renamed__category` AS `Products_Renamed__category_1f39b42c`, `source`.`Products Renamed__vendor` AS `Products_Renamed__vendor_cb8bd978`, `source`.`Products Renamed__price` AS `Products_Renamed__price_1ab6323c`, `source`.`Products Renamed__rating` AS `Products_Renamed__rating_3eb4d2e2`, `source`.`Products Renamed__created_at` AS `Products_Renamed__created_at_8de4c02f` FROM (SELECT `v3_sample_dataset.orders`.`id` AS `id`, `v3_sample_dataset.orders`.`user_id` AS `user_id`, `v3_sample_dataset.orders`.`product_id` AS `product_id`, `v3_sample_dataset.orders`.`subtotal` AS `subtotal`, `v3_sample_dataset.orders`.`tax` AS `tax`, `v3_sample_dataset.orders`.`total` AS `total`, `v3_sample_dataset.orders`.`discount` AS `discount`, `v3_sample_dataset.orders`.`created_at` AS `created_at`, `v3_sample_dataset.orders`.`quantity` AS `quantity`, (1 + 1) AS `CC`, `Products Renamed`.`id` AS `Products_Renamed__id_4408b1be`, `Products Renamed`.`ean` AS `Products_Renamed__ean_b48361a7`, `Products Renamed`.`title` AS `Products_Renamed__title_325dad00`, `Products Renamed`.`category` AS `Products_Renamed__category_1f39b42c`, `Products Renamed`.`vendor` AS `Products_Renamed__vendor_cb8bd978`, `Products Renamed`.`price` AS `Products_Renamed__price_1ab6323c`, `Products Renamed`.`rating` AS `Products_Renamed__rating_3eb4d2e2`, `Products Renamed`.`created_at` AS `Products_Renamed__created_at_8de4c02f` FROM `v3_sample_dataset.orders` LEFT JOIN `v3_sample_dataset.products` `Products Renamed` ON `v3_sample_dataset.orders`.`product_id` = `Products Renamed`.`id`) `source` WHERE `source`.`Products Renamed__category` = ? LIMIT 2000",
    :parameters ("Doohickey")}}],
 :error_type :invalid-query,
 :json_query
 {:database 43,
  :query
  {:source-table 6554,
   :joins
   [{:fields "all",
     :source-table 6552,
     :condition ["=" ["field" 38264 nil] ["field" 38247 {:join-alias "Products Renamed"}]],
     :alias "Products Renamed"}],
   :expressions {:CC ["+" 1 1]},
   :filter ["=" ["field" 38241 {:join-alias "Products Renamed"}] "Doohickey"]},
  :type "query",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT `source`.`id` AS `id`, `source`.`user_id` AS `user_id`, `source`.`product_id` AS `product_id`, `source`.`subtotal` AS `subtotal`, `source`.`tax` AS `tax`, `source`.`total` AS `total`, `source`.`discount` AS `discount`, `source`.`created_at` AS `created_at`, `source`.`quantity` AS `quantity`, `source`.`CC` AS `CC`, `source`.`Products Renamed__id` AS `Products_Renamed__id_4408b1be`, `source`.`Products Renamed__ean` AS `Products_Renamed__ean_b48361a7`, `source`.`Products Renamed__title` AS `Products_Renamed__title_325dad00`, `source`.`Products Renamed__category` AS `Products_Renamed__category_1f39b42c`, `source`.`Products Renamed__vendor` AS `Products_Renamed__vendor_cb8bd978`, `source`.`Products Renamed__price` AS `Products_Renamed__price_1ab6323c`, `source`.`Products Renamed__rating` AS `Products_Renamed__rating_3eb4d2e2`, `source`.`Products Renamed__created_at` AS `Products_Renamed__created_at_8de4c02f` FROM (SELECT `v3_sample_dataset.orders`.`id` AS `id`, `v3_sample_dataset.orders`.`user_id` AS `user_id`, `v3_sample_dataset.orders`.`product_id` AS `product_id`, `v3_sample_dataset.orders`.`subtotal` AS `subtotal`, `v3_sample_dataset.orders`.`tax` AS `tax`, `v3_sample_dataset.orders`.`total` AS `total`, `v3_sample_dataset.orders`.`discount` AS `discount`, `v3_sample_dataset.orders`.`created_at` AS `created_at`, `v3_sample_dataset.orders`.`quantity` AS `quantity`, (1 + 1) AS `CC`, `Products Renamed`.`id` AS `Products_Renamed__id_4408b1be`, `Products Renamed`.`ean` AS `Products_Renamed__ean_b48361a7`, `Products Renamed`.`title` AS `Products_Renamed__title_325dad00`, `Products Renamed`.`category` AS `Products_Renamed__category_1f39b42c`, `Products Renamed`.`vendor` AS `Products_Renamed__vendor_cb8bd978`, `Products Renamed`.`price` AS `Products_Renamed__price_1ab6323c`, `Products Renamed`.`rating` AS `Products_Renamed__rating_3eb4d2e2`, `Products Renamed`.`created_at` AS `Products_Renamed__created_at_8de4c02f` FROM `v3_sample_dataset.orders` LEFT JOIN `v3_sample_dataset.products` `Products Renamed` ON `v3_sample_dataset.orders`.`product_id` = `Products Renamed`.`id`) `source` WHERE `source`.`Products Renamed__category` = ? LIMIT 1048575",
  :params ("Doohickey"),
  :table-name "orders",
  :mbql? true},
 :status :failed,
 :class com.google.api.client.googleapis.json.GoogleJsonResponseException,
 :stacktrace
 ["com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)"
  "com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)"
  "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:635)"
  "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1255)"
  "com.google.cloud.bigquery.BigQueryImpl$34.call(BigQueryImpl.java:1252)"
  "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
  "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
  "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
  "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1251)"
  "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1239)"
  "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__80427.invoke(bigquery_cloud_sdk.clj:184)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "400 Bad Request\nPOST https://www.googleapis.com/bigquery/v2/projects/metabase-bigquery-driver/queries\n{\n  \"code\" : 400,\n  \"errors\" : [ {\n    \"domain\" : \"global\",\n    \"location\" : \"q\",\n    \"locationType\" : \"parameter\",\n    \"message\" : \"Name Products Renamed__category not found inside source at [2:2131]\",\n    \"reason\" : \"invalidQuery\"\n  } ],\n  \"message\" : \"Name Products Renamed__category not found inside source at [2:2131]\",\n  \"status\" : \"INVALID_ARGUMENT\"\n}",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 43,
  :query
  {:source-table 6554,
   :expressions {"CC" [:+ 1 1]},
   :filter
   [:=
    [:field 38241 {:join-alias "Products Renamed"}]
    [:value
     "Doohickey"
     {:base_type :type/Text,
      :effective_type :type/Text,
      :coercion_strategy nil,
      :semantic_type :type/Category,
      :database_type "STRING",
      :name "category"}]],
   :fields
   [[:field 38269 nil]
    [:field 38267 nil]
    [:field 38264 nil]
    [:field 38265 nil]
    [:field 38261 nil]
    [:field 38263 nil]
    [:field 38268 nil]
    [:field 38266 {:temporal-unit :default}]
    [:field 38262 nil]
    [:expression "CC"]
    [:field 38247 {:join-alias "Products Renamed"}]
    [:field 38243 {:join-alias "Products Renamed"}]
    [:field 38240 {:join-alias "Products Renamed"}]
    [:field 38241 {:join-alias "Products Renamed"}]
    [:field 38244 {:join-alias "Products Renamed"}]
    [:field 38246 {:join-alias "Products Renamed"}]
    [:field 38242 {:join-alias "Products Renamed"}]
    [:field 38245 {:temporal-unit :default, :join-alias "Products Renamed"}]],
   :joins
   [{:strategy :left-join,
     :fields
     [[:field 38247 {:join-alias "Products Renamed"}]
      [:field 38243 {:join-alias "Products Renamed"}]
      [:field 38240 {:join-alias "Products Renamed"}]
      [:field 38241 {:join-alias "Products Renamed"}]
      [:field 38244 {:join-alias "Products Renamed"}]
      [:field 38246 {:join-alias "Products Renamed"}]
      [:field 38242 {:join-alias "Products Renamed"}]
      [:field 38245 {:temporal-unit :default, :join-alias "Products Renamed"}]],
     :source-table 6552,
     :condition [:= [:field 38264 nil] [:field 38247 {:join-alias "Products Renamed"}]],
     :alias "Products Renamed"}],
   :limit 1048575,
   :metabase.query-processor.middleware.limit/original-limit nil},
  :type :query,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 1, :context :ad-hoc}},
 :data {:rows [], :cols []}}

2022-02-11 15:34:29,969 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 2.9 s (46 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (3 idle, 0 queued) (52 total active threads) Queries in flight: 1 (0 queued)
```

</details>

**Comment by camsaul** [comment]
Ok. I'll have to do a follow-on fix for #20413. It's going to build on this one so I still want to get this 👍 so I can merge it in first.

**Review by flamber — APPROVED** [review]

**Review by ariya — APPROVED** [review]
Let's ship this :rocket:
