### PR TITLE
Don't crash with null collection search result

### LINKED ISSUE #26466: Use of global search multiple times very fast can cause blank screen under certain conditions
**Describe the bug**
When going to the search page very fast multiple times with the same search string can lead to the frontend crashing.

**To Reproduce**
1. Native > Sample > `select 1` - save a "Break search"
2. Use the global search - type "break" and press enter, so we go to the search page and should list the question created in step 1
3. Click the search result to go to the question
4. Either move or archive the question - any action that triggers a toast notification
5. Very quickly, before the toast message disappears, use the global search and type "break" and press enter - frontend crashes with blank screen

```
Uncaught TypeError: Cannot read properties of null (reading 'id')
    at M (utils.js:35:40)
    at getCollection (questions.js:79:19)
    at W.G.<computed> [as getCollection] (entities.js:594:24)
    at M (InfoText.jsx:35:16)
    at Qo (react-dom.production.min.js:153:146)
    at xa (react-dom.production.min.js:261:496)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at ll (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
```

https://user-images.githubusercontent.com/1447303/201517862-22296593-33b2-40e9-a57e-af4a8b1e24ac.mp4

**Information about your Metabase Installation:**
Tested 0.44.6

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/26466

### Description

This bug is really hard to reproduce, but sometimes if you have a bunch of entities in the root (null) collection, it can manifest, possibly, due to race conditions in the entities served up by the search endpoint overwriting other data in the store. I could not reproduce this bug at all locally, but it manifested in a staging environment recently. I wonder if you might need more network latency than exists in a local dev environment for it to happen. 🤔 

Screen Shot 2023-04-25 at 3 16 07 PM

Screen Shot 2023-04-25 at 3 16 40 PM

Fortunately, in that branch, I added an error boundary around the app bar so it can no longer cause a full app crash.

I basically followed the error trail and found that sometimes `collection` would be undefined and would throw an error trying to access `collection.id`. I added some null chaining and handling the resulting `undefined` value.

### How to verify

Do a bunch of fast searching with items in the root (our analytics) collection and the application doesn't crash 🤷‍♀️

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30378)

### CODE REVIEW

**Review by alxnddr — COMMENTED** [review]
I remember there were regressions around `canonicalCollectionId` before, would you mind adding specs on such corner cases to keep it safe?

File: frontend/src/metabase/collections/utils.ts [hunk 1]
```diff
@@ -121,7 +121,11 @@ export function coerceCollectionId(
 export function canonicalCollectionId(
   collectionId: string | number | null | undefined,
```
Comment (nemanjaglumac) [inline frontend/src/metabase/collections/utils.ts:122]: Do we have a scenario in which `collectionId` can be `0`?

Comment (iethree) [reply frontend/src/metabase/collections/utils.ts:122]: I don't think so. I think the root collection is always null

**Review by alxnddr — APPROVED** [review]
