### PR TITLE
Show "Use instance font" in default dropdown in static embed

### LINKED ISSUE #54490: Default font not showing in Mantine select dropdown in static embed modal's look and feel
### Describe the bug

When embedding a question or a dashboard with static embed and going to the "Look and Feel" tab, the default font is not showing.

Image

If I select the default option, we'll highlight the embed option, but the code has not actually changed.

Image

Please note that I'm using [this PR](https://github.com/metabase/metabase/pull/54268) to report this bug. It will go into master soon, but the same error happens on master as well.

### To Reproduce

1. Go to the example dashboard
2. Click sharing icon > Embed > select static embedding
3. Select "Look and Feel" tab

### Expected behavior

the option "Use instance font" should be selected by default.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-02-25",
      "src_hash": "de59f87a031ee8978de2e53b31716520e56c7ecf",
      "tag": "v1.54.2-SNAPSHOT",
      "hash": "b0c36a8"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.2+13-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.2+13-LTS",
    "os.name": "Mac OS X",
    "os.version": "15.3.1",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

p2 - it's confusing

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/54490

### Description

When embedding a question or a dashboard with static embed and going to the "Look and Feel" tab, the default font box was showing up as an empty box. Now it shows "Use instance font".

### How to verify

- Open a static embed modal
- Font shows "Use instance font" by default

### Demo

CleanShot 2568-05-22 at 15 14 31@2x

## Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/config.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ export function getDefaultDisplayOptions(
   shouldShownDownloadData: boolean,
 ): EmbeddingDisplayOptions {
   return {
-    font: null,
+    font: "",
```
Comment (heypoom) [inline frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/config.ts:7]: We are already using `""` in the options. Using `null` crashes the Mantine v7's dropdown select as it expects a string.

**Review by npretto — APPROVED** [review]
