### PR TITLE
Fix world map crop issue

### LINKED ISSUE #4378: Why world map is cropped at the top?
When I open the MAP, MAP is cropped from the top section. The below picture speaks thousands word:
screen shot 2017-02-14 at 2 13 07 pm

Is this a bug? How should I solve this issue?

- browser and the version: (Chrome 56.0, Firefox Developer Edition 53.0)
- operating system: (OS X 10,)
- databases: (MySQL)
- Metabase version: (0.22.2)

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #4378

## What does this do?

This PR fixes a bug where northern countries were cropped in the world map. It does this by adding an explicit longitude/latitude based frame for each map.

## How did it work before?

Previously, we used the default framing of the projection itself. This would leave the default dimensions of 960x500px and the default zoom of 150 in place. This worked well for the Albers US projection, but the default framing for the Mercator-projected world map cropped important regions.

### Before
Screen Shot 2019-05-07 at 3 01 40 PM

### After
Screen Shot 2019-05-07 at 3 00 43 PM

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/ChoroplethMap.jsx [hunk 1]
```diff
@@ -146,11 +146,14 @@ export default class ChoroplethMap extends Component {
     let { geoJson, minimalBounds } = this.state;
 
     // special case builtin maps to use legacy choropleth map
-    let projection;
+    let projection, projectionFrame;
+    // projectionFrame is the lng/lat of the top left and bottom right corners
     if (settings["map.region"] === "us_states") {
       projection = d3.geo.albersUsa();
+      projectionFrame = [[-135.0, 46.6], [-69.1, 21.7]];
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/components/ChoroplethMap.jsx]: This frame was picked to match what we had before from the D3 defaults.

File: frontend/src/metabase/visualizations/components/ChoroplethMap.jsx [hunk 2]
```diff
@@ -146,11 +146,14 @@ export default class ChoroplethMap extends Component {
...
     } else if (settings["map.region"] === "world_countries") {
       projection = d3.geo.mercator();
+      projectionFrame = [[-170, 78], [180, -60]];
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/components/ChoroplethMap.jsx]: This frame was hand-crafted and crops of Antarctica, part of Greenland, and a few other tiny parts. It should be easy to adjust if we want to update the framing.

**Review by tlrobinson — APPROVED** [review]
LGTM
