### PR TITLE
upgrade-field-literals should do case-insensitive fixes

### LINKED ISSUE #16389: BigQuery summarizing nested query fails query with wrong alias reference
**Describe the bug**
Extension of #15370, just with nested query. Worked in 0.37.8

**To Reproduce**
Using BigQuery with a version of Sample Dataset
1. Custom question > BigQuery > Orders
2. Summarize Count by Products.CreatedAt:Month - **note** important to pick a (implicit/explicit) joined table date column
3. Filter CreatedAt previous 30 years
4. Summarize (again) "Sum of Count" grouped by "Created At"
image
5. Visualize - fails with `` Unrecognized name: `v6_sample_dataset.source` at [2:28] ``
<details><summary>Full stacktrace</summary>

```
2021-06-07 16:06:33,788 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 43,
 :started_at #t "2021-06-07T16:06:30.520736+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:224)"
    "driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)"
    "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:205)"
    "driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)"
    "driver.bigquery$process_native_STAR_$thunk__2161.invoke(bigquery.clj:277)"
    "driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:279)"
    "driver.bigquery$process_native_STAR_.invoke(bigquery.clj:272)"
    "driver.bigquery$eval2165$fn__2167.invoke(bigquery.clj:299)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47511.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__46625.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__47497.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__46077.invoke(cache.clj:211)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47757.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49687.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45196.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41497.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__41372.invoke(annotate.clj:605)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46497.invoke(permissions.clj:81)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48615.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46698.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48914.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__49227.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44772.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47461.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__47442.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44066.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__46764.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__45583.invoke(binning.clj:227)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__46300.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__44421.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44650.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49636.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44935.invoke(add_source_metadata.clj:123)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48789.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45143.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46347.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48597.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46399.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__47148.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44944.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49589.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800$fn__48804.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47388.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__49598$fn__49599.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__49598.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__49643.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__47524.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44790.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49574.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__46641.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__48686.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46581.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___38051$fn__38054.invoke(reducible.clj:108)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: 59418309ed08ca24b836155ad7df17d5247094807b51b74a9ff4ca96a78cc16c\nSELECT datetime_trunc(CAST(`v6_sample_dataset.source`.`products__via__product_id__created_at` AS datetime), day) AS `products__via__product_id__created_at`, sum(`source`.`count`) AS `sum` FROM (SELECT timestamp_trunc(`products__via__product_id`.`created_at`, month) AS `products__via__product_id__created_at`, count(*) AS `count` FROM `v6_sample_dataset.orders` LEFT JOIN `v6_sample_dataset.products` `products__via__product_id` ON `v6_sample_dataset.orders`.`product_id` = `products__via__product_id`.`id` GROUP BY `products__via__product_id__created_at` ORDER BY `products__via__product_id__created_at` ASC) `source` WHERE (`source`.`products__via__product_id__created_at` >= CAST(datetime_trunc(datetime_add(current_datetime(), INTERVAL -30 year), year) AS timestamp) AND `source`.`products__via__product_id__created_at` < CAST(datetime_trunc(current_datetime(), year) AS timestamp)) GROUP BY `products__via__product_id__created_at` ORDER BY `products__via__product_id__created_at` ASC",
    :parameters nil}}],
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :database 43,
  :query
  {:source-query
   {:source-table 6174,
    :aggregation [[:count]],
    :breakout [[:field 35284 {:source-field 35254, :temporal-unit :month}]]},
   :filter [:time-interval [:field "created_at" {:base-type :type/DateTimeWithLocalTZ}] -30 :year],
   :aggregation [[:sum [:field "count" {:base-type :type/Integer}]]],
   :breakout [[:field "created_at" {:base-type :type/DateTimeWithLocalTZ}]]},
  :parameters [],
  :async? true,
  :cache-ttl nil},
 :native
 {:query
  "SELECT datetime_trunc(CAST(`v6_sample_dataset.source`.`products__via__product_id__created_at` AS datetime), day) AS `products__via__product_id__created_at`, sum(`source`.`count`) AS `sum` FROM (SELECT timestamp_trunc(`products__via__product_id`.`created_at`, month) AS `products__via__product_id__created_at`, count(*) AS `count` FROM `v6_sample_dataset.orders` LEFT JOIN `v6_sample_dataset.products` `products__via__product_id` ON `v6_sample_dataset.orders`.`product_id` = `products__via__product_id`.`id` GROUP BY `products__via__product_id__created_at` ORDER BY `products__via__product_id__created_at` ASC) `source` WHERE (`source`.`products__via__product_id__created_at` >= CAST(datetime_trunc(datetime_add(current_datetime(), INTERVAL -30 year), year) AS timestamp) AND `source`.`products__via__product_id__created_at` < CAST(datetime_trunc(current_datetime(), year) AS timestamp)) GROUP BY `products__via__product_id__created_at` ORDER BY `products__via__product_id__created_at` ASC",
  :params nil,
  :table-name "source",
  :mbql? true},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> driver.google$execute_no_auto_retry.invokeStatic(google.clj:41)"
  "driver.google$execute_no_auto_retry.invoke(google.clj:33)"
  "driver.google$execute.invokeStatic(google.clj:55)"
  "driver.google$execute.invoke(google.clj:45)"
  "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:216)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)"
  "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:205)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)"
  "driver.bigquery$process_native_STAR_$thunk__2161.invoke(bigquery.clj:277)"
  "driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:279)"
  "driver.bigquery$process_native_STAR_.invoke(bigquery.clj:272)"
  "driver.bigquery$eval2165$fn__2167.invoke(bigquery.clj:299)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47511.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__46625.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__47497.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__46077.invoke(cache.clj:211)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47757.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49687.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45196.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41497.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__41372.invoke(annotate.clj:605)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46497.invoke(permissions.clj:81)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48615.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46698.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48914.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__49227.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44772.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47461.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__47442.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44066.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__46764.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45583.invoke(binning.clj:227)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46300.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__44421.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44650.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49636.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44935.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48789.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45143.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46347.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48597.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46399.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47148.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44944.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49589.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800$fn__48804.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47388.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__49598$fn__49599.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__49598.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__49643.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47524.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44790.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49574.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46641.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48686.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46581.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___38051$fn__38054.invoke(reducible.clj:108)"],
 :context :question,
 :error "Unrecognized name: `v6_sample_dataset.source` at [2:28]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :info
  {:executed-by 1,
   :context :question,
   :card-id 640,
   :query-hash
   [89, 65, -125, 9, -19, 8, -54, 36, -72, 54, 21, 90, -41, -33, 23, -43, 36, 112, -108, -128, 123, 81, -73, 74, -97,
    -12, -54, -106, -89, -116, -63, 108]},
  :database 43,
  :query
  {:filter
   [:and
    [:>=
     [:field 35284 {:source-field 35254, :temporal-unit :default, :join-alias "products__via__product_id"}]
     [:relative-datetime -30 :year]]
    [:<
     [:field 35284 {:source-field 35254, :temporal-unit :default, :join-alias "products__via__product_id"}]
     [:relative-datetime 0 :year]]],
   :aggregation [[:aggregation-options [:sum [:field "count" {:base-type :type/Integer}]] {:name "sum"}]],
   :breakout [[:field 35284 {:source-field 35254, :temporal-unit :day, :join-alias "products__via__product_id"}]],
   :source-metadata
   [{:semantic_type :type/CreationTimestamp,
     :table_id 6177,
     :coercion_strategy nil,
     :unit :month,
     :name "created_at",
     :settings nil,
     :field_ref [:field 35284 {:source-field 35254, :temporal-unit :month, :join-alias "products__via__product_id"}],
     :effective_type :type/DateTimeWithLocalTZ,
     :parent_id nil,
     :id 35284,
     :display_name "Product → Created At",
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147Z", :latest "2019-04-15T13:34:19.931Z"}}},
     :base_type :type/DateTimeWithLocalTZ,
     :source_alias "products__via__product_id"}
    {:name "count",
     :display_name "Count",
     :base_type :type/BigInteger,
     :semantic_type :type/Number,
     :field_ref [:aggregation 0]}],
   :order-by
   [[:asc [:field 35284 {:source-field 35254, :temporal-unit :day, :join-alias "products__via__product_id"}]]],
   :source-query
   {:source-table 6174,
    :aggregation [[:aggregation-options [:count] {:name "count"}]],
    :breakout [[:field 35284 {:source-field 35254, :temporal-unit :month, :join-alias "products__via__product_id"}]],
    :order-by
    [[:asc [:field 35284 {:source-field 35254, :temporal-unit :month, :join-alias "products__via__product_id"}]]],
    :joins
    [{:strategy :left-join,
      :alias "products__via__product_id",
      :condition [:= [:field 35254 nil] [:field 35286 {:join-alias "products__via__product_id"}]],
      :source-table 6177,
      :fk-field-id 35254}]}},
  :async? true},
 :ex-data
 {"code" 400,
  "errors"
  [{"domain" "global", "location" "q", "locationType" "parameter", "message" "Unrecognized name: `v6_sample_dataset.source` at [2:28]", "reason" "invalidQuery"}],
  "message" "Unrecognized name: `v6_sample_dataset.source` at [2:28]",
  "status" "INVALID_ARGUMENT"},
 :data {:rows [], :cols []}}

2021-06-07 16:06:33,826 DEBUG middleware.log :: POST /api/card/640/query 202 [ASYNC: completed] 3.3 s (19 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (3 idle, 0 queued) (55 total active threads) Queries in flight: 1 (0 queued)
```

</details>

**Alternatve reproduce:**
1. Native query > BigQuery > `select 1 AS val, current_timestamp as dt` - save as "Q1"
2. Simple question > Saved Questions > "Q1"
3. Summarize "Sum of val" grouped by "dt":
image

<details><summary>Full stacktrace</summary>

```
2021-06-07 16:08:20,726 INFO middleware.fetch-source-query :: Fetched source query from Card 642: 
 {:native "select 1 AS val, current_timestamp as dt"}

2021-06-07 16:08:20,732 INFO middleware.fetch-source-query :: Fetched source query from Card 642: 
 {:native "select 1 AS val, current_timestamp as dt"}

2021-06-07 16:08:22,295 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 43,
 :started_at #t "2021-06-07T16:08:20.717820+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:224)"
    "driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)"
    "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:205)"
    "driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)"
    "driver.bigquery$process_native_STAR_$thunk__2161.invoke(bigquery.clj:277)"
    "driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:279)"
    "driver.bigquery$process_native_STAR_.invoke(bigquery.clj:272)"
    "driver.bigquery$eval2165$fn__2167.invoke(bigquery.clj:299)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47511.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__46625.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__47497.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__46077.invoke(cache.clj:211)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47757.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49687.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45196.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41497.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__41372.invoke(annotate.clj:605)"
    "query_processor.middleware.permissions$check_query_permissions$fn__46497.invoke(permissions.clj:81)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48615.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46698.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48914.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__49227.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44772.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47461.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__47442.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44066.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__46764.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__45583.invoke(binning.clj:227)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__46300.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__44421.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44650.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49636.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44935.invoke(add_source_metadata.clj:123)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48789.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45143.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46347.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48597.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46399.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__47148.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44944.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49589.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800$fn__48804.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47388.invoke(fetch_source_query.clj:273)"
    "query_processor.middleware.store$initialize_store$fn__49598$fn__49599.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__49598.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__49643.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__47524.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44790.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49574.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__46641.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__48686.invoke(process_userland_query.clj:135)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46581.invoke(catch_exceptions.clj:173)"
    "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___38051$fn__38054.invoke(reducible.clj:108)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: 28870dc748821103c0a20541783ac119a2f2b67701d66db61574635c4412028d\nSELECT datetime_trunc(CAST(`v6_sample_dataset.source`.`dt` AS datetime), day) AS `dt`, sum(`source`.`val`) AS `sum` FROM (select 1 AS val, current_timestamp as dt) `source` GROUP BY `dt` ORDER BY `dt` ASC",
    :parameters nil}}],
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :database 43,
  :query
  {:source-table "card__642",
   :aggregation [[:sum [:field "val" {:base-type :type/Integer}]]],
   :breakout [[:field "dt" {:base-type :type/DateTimeWithLocalTZ}]]},
  :parameters [],
  :async? true,
  :cache-ttl nil},
 :native
 {:query
  "SELECT datetime_trunc(CAST(`v6_sample_dataset.source`.`dt` AS datetime), day) AS `dt`, sum(`source`.`val`) AS `sum` FROM (select 1 AS val, current_timestamp as dt) `source` GROUP BY `dt` ORDER BY `dt` ASC",
  :params nil,
  :table-name "source",
  :mbql? true},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> driver.google$execute_no_auto_retry.invokeStatic(google.clj:41)"
  "driver.google$execute_no_auto_retry.invoke(google.clj:33)"
  "driver.google$execute.invokeStatic(google.clj:55)"
  "driver.google$execute.invoke(google.clj:45)"
  "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:216)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)"
  "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:205)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)"
  "driver.bigquery$process_native_STAR_$thunk__2161.invoke(bigquery.clj:277)"
  "driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:279)"
  "driver.bigquery$process_native_STAR_.invoke(bigquery.clj:272)"
  "driver.bigquery$eval2165$fn__2167.invoke(bigquery.clj:299)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47511.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__46625.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__47497.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__46077.invoke(cache.clj:211)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47757.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49687.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45196.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41497.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__41372.invoke(annotate.clj:605)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46497.invoke(permissions.clj:81)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48615.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46698.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48914.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__49227.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44772.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47461.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__47442.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44066.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__46764.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45583.invoke(binning.clj:227)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46300.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__44421.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44650.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49636.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44935.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48789.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45143.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46347.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48597.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46399.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47148.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44944.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49589.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800$fn__48804.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47388.invoke(fetch_source_query.clj:273)"
  "query_processor.middleware.store$initialize_store$fn__49598$fn__49599.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__49598.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__49643.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47524.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44790.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49574.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46641.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48686.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46581.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___38051$fn__38054.invoke(reducible.clj:108)"],
 :context :question,
 :error "Unrecognized name: `v6_sample_dataset.source` at [2:28]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :info
  {:executed-by 1,
   :context :question,
   :card-id 643,
   :query-hash
   [40, -121, 13, -57, 72, -126, 17, 3, -64, -94, 5, 65, 120, 58, -63, 25, -94, -14, -74, 119, 1, -42, 109, -74, 21,
    116, 99, 92, 68, 18, 2, -115]},
  :database 43,
  :query
  {:aggregation [[:aggregation-options [:sum [:field "val" {:base-type :type/Integer}]] {:name "sum"}]],
   :breakout [[:field "dt" {:base-type :type/DateTimeWithLocalTZ, :temporal-unit :day}]],
   :source-metadata
   [{:base_type :type/Integer,
     :display_name "val",
     :name "val",
     :special_type nil,
     :fingerprint
     {:global {:distinct-count 1, :nil% 0}, :type {:type/Number {:min 1, :q1 1, :q3 1, :max 1, :sd nil, :avg 1}}}}
    {:base_type :type/DateTimeWithLocalTZ,
     :display_name "dt",
     :name "dt",
     :special_type nil,
     :fingerprint
     {:global {:distinct-count 1, :nil% 0},
      :type {:type/DateTime {:earliest "2021-06-07T16:00:55.405+02:00", :latest "2021-06-07T16:00:55.405+02:00"}}}}],
   :order-by [[:asc [:field "dt" {:base-type :type/DateTimeWithLocalTZ, :temporal-unit :day}]]],
   :source-query {:native "select 1 AS val, current_timestamp as dt"}},
  :async? true},
 :ex-data
 {"code" 400,
  "errors"
  [{"domain" "global", "location" "q", "locationType" "parameter", "message" "Unrecognized name: `v6_sample_dataset.source` at [2:28]", "reason" "invalidQuery"}],
  "message" "Unrecognized name: `v6_sample_dataset.source` at [2:28]",
  "status" "INVALID_ARGUMENT"},
 :data {:rows [], :cols []}}

2021-06-07 16:08:22,301 DEBUG middleware.log :: POST /api/card/643/query 202 [ASYNC: completed] 1.6 s (9 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (2 idle, 0 queued) (56 total active threads) Queries in flight: 0 (0 queued)

```

</details>

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.39.3 - regression since 0.38.0

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by camsaul**
Follow on to #19384
Fixes #16389

The root cause of #16389 is that the frontend in some places is still disregarding the `:field_ref` in query results metadata and incorrectly generating `[:field <string> ...]` ("field literal") clauses to refer to Fields returned by joins or source queries, even when they're normal Fields returned by normal MBQL queries. `:field`+String name clauses are only meant for referring to things that have no corresponding `Field`, e.g. columns that come back from a native query or columns introduced by aggregations or expressions in the source query. See https://github.com/metabase/metabase/issues/16389#issuecomment-1013780973 for a longer explanation.

The frontend has been generating "broken" queries like these basically forever, so in #14812 I introduced middleware that would attempt to rewrite "field literals" to proper `[:field <integer> ...]` clauses. This fixed a bunch of bugs. However this middleware only attempted case-sensitive fixes. 

For #16389 in particular it turns out the frontend is generating clauses like `[:field "price" ...]` even when the **actual** name of the Field is `PRICE`. 

This PR: 
- extends the `upgrade-field-literals` middleware from #14812 to be case-insensitive
- Logs warnings on "bad" field literal clauses so we can catch and fix code in the FE client that is generating them
- Logs warnings on "bad" field literal clauses that cannot figure out how to fix (which would have made debugging #16389 much easier). I considered throwing an Exception if the clause is bad and we can't fix it, but there's still a _chance_ the query might work somehow, and I didn't want to end up breaking things that used to work for one reason or another

### CODE REVIEW

File: src/metabase/query_processor/middleware/add_source_metadata.clj [hunk 1]
```diff
@@ -105,7 +105,9 @@
 (defn- add-source-metadata-at-all-levels [inner-query]
   (walk/postwalk maybe-add-source-metadata inner-query))
 
-(defn- add-source-metadata-for-source-queries* [{query-type :type, :as query}]
+(defn add-source-metadata-for-source-queries*
+  "Add `:source-metadata` for source queries inside `query`."
```
Comment (dpsutton) [inline src/metabase/query_processor/middleware/add_source_metadata.clj:109]: big 👍 for adding docstrings. I'm gonna try to be more cognizant of that too.

File: test/metabase/query_processor_test.clj [hunk 2]
```diff
@@ -418,33 +418,45 @@
...
+                               (thunk)))))
+                       thunk
+                       (if (str/includes? (:name (data/db)) "sample")
+                         {[:orders :product_id]  [:products :id]
+                          [:orders :user_id]     [:people :id]
+                          [:reviews :product_id] [:products :id]}
+                         {[:checkins :user_id]   [:users :id]
+                          [:checkins :venue_id]  [:venues :id]
+                          [:venues :category_id] [:categories :id]}))]
+            (thunk)))))))
```
Comment (camsaul) [inline test/metabase/query_processor_test.clj:450]: I upgraded this so it works with the sample dataset and so we can use it on both `:bigquery` and `:bigquery-cloud-sdk` at the same time

File: src/metabase/query_processor/middleware/upgrade_field_literals.clj [hunk 3]
```diff
@@ -1,36 +1,113 @@
...
+        ;; If the matching Field ref is an integer `:field` clause then replace it with the corrected clause and log
+        ;; a developer-facing warning. Things will still work and this should be fixed on the FE, but we don't need to
+        ;; blow up prod logs
+        [:field (id :guard integer?) new-options]
+        (u/prog1 [:field id (merge new-options (dissoc options :base-type))]
+          (when (and (not config/is-prod?)
+                     (not (has-a-native-source-query-at-some-level? inner-query)))
+            ;; don't i18n this because it's developer-facing only.
+            (warn-once
+             (str "Warning: query is using a [:field <string> ...] clause to refer to a Field in an MBQL source query."
```
Comment (dpsutton) [inline src/metabase/query_processor/middleware/upgrade_field_literals.clj:42]: this warning says it is using `[:field <string> ...]` but the match clause is `[:field (id :guard integer?) new-options]`. They seem incongruous.

Comment (dpsutton) [reply src/metabase/query_processor/middleware/upgrade_field_literals.clj:42]: ah i missed it. I see now.

File: src/metabase/query_processor/middleware/upgrade_field_literals.clj [hunk 4]
```diff
@@ -1,36 +1,113 @@
...
+        (warn-once
+         (trs "Warning: clause {0} refers to a Field that may not be present in the source query. Query may not work as expected. Found: {1}"
+              (pr-str field-clause) (pr-str (or (not-empty source-aliases)
+                                                (set (keys field-name->field))))))
+        field-clause))))
 
 (defn- upgrade-field-literals-one-level [{:keys [source-metadata], :as inner-query}]
-  (let [field-name->field (u/key-by :name source-metadata)]
-    ;; look for `field` clauses that use a string name...
+  (let [source-aliases    (into #{} (comp (map :source_alias) (filter some?)) source-metadata)
```
Comment (dpsutton) [inline src/metabase/query_processor/middleware/upgrade_field_literals.clj:79]: `(comp (map :source_alias) (filter some?))` is just `(keep :source_alias)`

File: src/metabase/util.clj [hunk 5]
```diff
@@ -811,7 +811,7 @@
   [message start-time]
   ;; indent the message according to [[*profile-level*]] and add a little down-left arrow so it (hopefully) points to
   ;; the parent form
-  (println (format-color (case (mod *profile-level* 4)
+  (println (format-color (case (int (mod *profile-level* 4))
```
Comment (dpsutton) [inline src/metabase/util.clj:814]: small thing but i don't understand the `int` here. I did some simple testing and there was little to no difference as far as i can tell
```clojure
annotate=> (time
             (dotimes [_ 1000000]
               (case (mod 244224 4)
                 0 :zero
                 1 :one
                 2 :two
                 3 :three)))
"Elapsed time: 24.125041 msecs"
nil
annotate=> (time
             (dotimes [_ 1000000]
               (case (int (mod 244224 4))
                 0 :zero
                 1 :one
                 2 :two
                 3 :three)))
"Elapsed time: 33.01825 msecs"
nil
```

Comment (camsaul) [reply src/metabase/util.clj:814]: the only difference is it complains if `*warn-on-reflection*` is enabled since `case` doesn't have a primitive test case or something like that

**Review by dpsutton — APPROVED** [review]

File: src/metabase/util.clj (hunk 5 above)
Comment (dpsutton) [reply src/metabase/util.clj:814]: oh so it does. oddly it doesn't seem to impact the performance at all. whatever.

File: src/metabase/query_processor/middleware/upgrade_field_literals.clj (hunk 4 above)
Comment (camsaul) [reply src/metabase/query_processor/middleware/upgrade_field_literals.clj:79]:
```suggestion
  (let [source-aliases    (into #{} (keep :source_alias) source-metadata)
```

File: src/metabase/util.clj (hunk 5 above)
Comment (camsaul) [reply src/metabase/util.clj:814]: Yeah not 100% sure why here, I guess it's because it doesn't know that `*profile-level*` is an `Integer`. I didn't think about it that much TBH
