### PR TITLE
Fix `type/PK`  -> `type/Name` and `type/FK` field remapping in the QB

### LINKED ISSUE #7231: "No matching name" found when it clearly has been found
This is with 0.28.3

When I use the search widget for a User ID in a SQL query it tells me "No matching first name found":

screen shot 2018-03-28 at 4 13 56 pm

but when I hit enter the first name clearly *was* found because it shows up on the screen.

screen shot 2018-03-28 at 4 14 01 pm

Steps to repro:

1.  Connect the Metabase database (I'm using Postgres) 
2.  Create new SQL question using this SQL:
     ```sql
     SELECT COUNT(*)
     FROM core_user
     WHERE {{user}}
     ```
3.  Wire up `user` param as Field Filter on `core_user.id` with Filter Widget Type of `ID`. No default value
4.  Try to use `User` search widget and type in the ID of a User
5.  "No First Name Found" pops up in widget
6.  Hit enter to choose ID
7.  First name shows up

### LINKED ISSUE #37955: Table filter multiselect input box does not work
### Describe the bug

If you try to filter "Suite Name" or "Test Name" on this model, https://stats.metabase.com/model/14829-test-result, the filter input box doesn't work. You cannot enter text in the input box and there are no dropdown values.

image 

Loom:
https://www.loom.com/share/08ac4a92258640c58da3ad189fcd3efa?sid=815694aa-f78a-420e-bab3-d51c919d11d4

### To Reproduce

I couldn't reproduce the bug with any of the test tables unfortunately, I just saw this on stats.

### Expected behavior

typing should search a list of values

### Logs

2cd8c5f

### Information about your Metabase installation

```JSON
master (2cd8c5f)
```

### Severity

filtering is a pretty common operation, but not sure how common this is

### Additional context

_No response_

### LINKED ISSUE #45063: `type/FK` -> column and `type/FK` -> `type/Name` field values remapping doesn't work in QB filter widgets when `Search box` is used
### Describe the bug

Automatic PK field values remapping to a field with "Entity Name" semantic type doesn't work in query builder widgets with `Search box`. The same with FK -> Use foreign key -> Column remapping.

### To Reproduce

`type/FK` -> `type/Name`:
1. Admin -> Table Metadata -> People. 
2. Make sure that `People.Name` has `Entity Name` semantic type.
3. Make sure that `People.ID` has `Search box` in `Filtering on this field` section (`has_field_values` property).
4. New -> Question -> Tables -> People
5. Filter -> ID
6. Start typing a person name. Nothing happens - there is no autocomplete.
7. Enter some valid person ID and add this filter.
8. Open the filter again. See that the value is not remapped either.

`type/FK` -> column:
1. Admin -> Table Metadata -> Orders. 
2. Open `PRODUCT_ID` -> Remapping -> Use foreign key -> Select `Product.Title`.
3. Make sure there is `Search box` enabled as well.
4. New -> Question -> Tables -> Orders
5. Filter -> Product ID
7. Start typing a product title. Nothing happens - there is no autocomplete.
8. Enter some valid product ID and add this filter.
9. Open the filter again. See that the value is not remapped either.

### Expected behavior

Both cases work with `List of values`. They should work with `Search box`. 
Screenshot 2024-07-02 at 15 19 51
Screenshot 2024-07-02 at 15 21 13

### Logs

_No response_

### Information about your Metabase installation

```JSON
- v50
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/45063
Fixes https://github.com/metabase/metabase/issues/7231
Fixes https://github.com/metabase/metabase/issues/37955

BE changes:
- Hydrates `name_field` for query metadata.

MBQL lib API changes:
- Fixes `dimensions` parsing. This makes `external`, i.e. `type/FK` remapping work out of the box. 
- Makes `type/PK` -> `type/Name` field remapping work.

FE changes:
- Makes `SearchValuePicker` handle mixed remapping options. Adds loading state.
- **Note that selected values are displayed as raw values and this is out of scope for this PR.**

How to verify type/PK -> type/Name remapping:
- Make sure that in Table Metadata for `People.Name` `Entity Name` semantic type is set
- Set `Filtering on this field` for `People.ID` to `A list of all values`
- Open `People` table. Click on `ID` -> Filter on this column. You should see a list of remapped values.
- Set `Filtering on this field` for `People.ID` to `Search box`
- Open `People` table. Click on `ID` -> Filter on this column.  Start typing some name. You should get autocomplete. Please note that the placeholder `Search by ID` is misleading and this is something that we need to fix separately.

How to verify type/FK -> column remapping:
- Open Table Metadata -> `Orders.Product ID` -> Click `Use original value` -> `Use foreign key` -> Select `Products.Title`.
- Set `Filtering on this field` to `A list of all values`
- Open `Orders` table. Click on `Product ID` -> Filter on this column. You should see a list of product names.
- Do the same with `Search box`.

### CODE REVIEW

**Review by bshepherdson — COMMENTED** [review]
These changes look sensible to me.

File: src/metabase/lib/js/metadata.cljs [hunk 1]
```diff
@@ -265,17 +265,17 @@
   `:internal`."
   [dimensions]
   (when-let [dimension (m/find-first (fn [dimension]
-                                       (#{"external" "internal"} (object-get dimension "type")))
```
Comment (ranquild) [inline src/metabase/lib/js/metadata.cljs:268]: `dimension` is a CLJS map here, not JS object; that's why all `object-get` calls return `nil`

File: src/metabase/lib/field.cljc [hunk 2]
```diff
@@ -787,16 +787,18 @@
 (mu/defn ^:private remapped-field :- [:maybe ::lib.schema.metadata/column]
   [metadata-providerable :- ::lib.schema.metadata/metadata-providerable
    column                :- ::lib.schema.metadata/column]
-  (when-let [remap-field-id (get-in column [:lib/external-remap :field-id])]
-    (lib.metadata/field metadata-providerable remap-field-id)))
+  (or
+   (when (lib.types.isa/primary-key? column)
```
Comment (ranquild) [inline src/metabase/lib/field.cljc:791]: Please note that this won't work for models for at least 2 reasons:
- We only load model metadata itself and not raw tables, that's why `lib.metadata/field` won't return the field
- Model could have metadata overrides and we should search `type/Name` within the model itself.

File: src/metabase/api/field.clj [hunk 3]
```diff
@@ -396,53 +396,56 @@
...
-   value       ms/NonBlankString}
+   value       [:maybe ms/NonBlankString] ;; deprecated
+   values      [:maybe (ms/QueryVectorOf ms/NonBlankString)]}
   (let [field          (api/read-check Field id)
         remapped-field (api/read-check Field remapped-id)
-        value          (parse-query-param-value-for-field field value)]
-    (remapped-value field remapped-field value)))
+        values         (parse-query-param-values-for-field field (or values [value]))
+        remapped       (remapped-values field remapped-field values)]
+    (if (some? value) ;; preserve backward compability; previously only one row was returned
```
Comment (ranquild) [inline src/metabase/api/field.clj:446]: @bshepherdson do you have better ideas to make this backward compatible and more clean?

File: src/metabase/lib/field.cljc (hunk 2 above)
Comment (ranquild) [reply src/metabase/lib/field.cljc:791]: @bshepherdson

File: frontend/src/metabase/schema.js [hunk 4]
```diff
@@ -99,9 +99,6 @@ FieldSchema.define({
   target: FieldSchema,
   table: TableSchema,
   name_field: FieldSchema,
-  dimensions: {
```
Comment (ranquild) [inline frontend/src/metabase/schema.js:102]: Broken normalizr schema

File: src/metabase/lib/field.cljc [hunk 5]
```diff
@@ -787,16 +787,18 @@
...
+           table-fields (lib.metadata/fields metadata-providerable (:table-id field))]
+           (m/find-first lib.types.isa/entity-name? table-fields)))
+    (when-let [remap-field-id (get-in column [:lib/external-remap :field-id])]
+      (lib.metadata/field metadata-providerable remap-field-id))))
 
 (mu/defn ^:private search-field :- [:maybe ::lib.schema.metadata/column]
   [metadata-providerable :- ::lib.schema.metadata/metadata-providerable
    column                :- ::lib.schema.metadata/column]
-  ;; ignore remappings for PK columns.
-  (let [col (or (when (lib.types.isa/primary-key? column)
```
Comment (ranquild) [inline src/metabase/lib/field.cljc:797]: I either don't get it or it was a noop.

File: src/metabase/lib/field.cljc [hunk 6]
```diff
@@ -787,16 +787,16 @@
 (mu/defn ^:private remapped-field :- [:maybe ::lib.schema.metadata/column]
   [metadata-providerable :- ::lib.schema.metadata/metadata-providerable
    column                :- ::lib.schema.metadata/column]
-  (when-let [remap-field-id (get-in column [:lib/external-remap :field-id])]
-    (lib.metadata/field metadata-providerable remap-field-id)))
+  (or
+    (when-let [name-field-id (:name-field column)]
```
Comment (ranquild) [inline src/metabase/lib/field.cljc:791]: This is a hack. There is no `name-field` property on `column` that returns the field id. The actual property has the whole field. This becomes an id only because of FE normalization. I think we should do what we do with `fk-target-field-id` - MBQL lib doesn't rely on the normalized `target` but the actual BE property. Maybe we could add `name-field-id` to the batch hydration method for `:name_field` on the BE and use this new property instead.

File: frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx [hunk 7]
```diff
@@ -35,19 +38,37 @@ export function SearchValuePicker({
   const [searchValue, setSearchValue] = useState("");
   const [searchQuery, setSearchQuery] = useState(searchValue);
 
-  const { data: fieldValues = initialFieldValues } = useSearchFieldValuesQuery(
+  const { data: searchFieldValues = initialFieldValues } =
+    useSearchFieldValuesQuery(
```
Comment (ranquild) [inline frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx:42]: Tests TBD

File: src/metabase/api/field.clj [hunk 8]
```diff
@@ -396,53 +396,52 @@
...
+      ;; -> [[20 \"Peter Watsica\"]]"
+  [field remapped-field values]
   (try
     (let [field   (follow-fks field)
           results (qp/process-query
                    {:database (db-id field)
                     :type     :query
                     :query    {:source-table (table-id field)
-                               :filter       [:= [:field (u/the-id field) nil] value]
+                               :filter       (concat [:= [:field (u/the-id field) nil]] values)
```
Comment (metamben) [inline src/metabase/api/field.clj:417]: It might a good idea keep filter as a vector.
```suggestion
                               :filter       (into [[:= [:field (u/the-id field) nil]]] values)
```

File: test/metabase/lib/js/metadata_test.cljs [hunk 9]
```diff
@@ -44,17 +43,11 @@
   #js {"id"               33
        "name"             "ID"
        "has_field_values" "none"
-       "dimensions"       #js [#js {"id"                      66
-                                    "field_id"                33
-                                    "name"                    "ID [internal remap]"
-                                    "type"                    "internal"
-                                    "human_readable_field_id" nil}]
-       "values"           #js {"has_more_values"       false
```
Comment (ranquild) [inline test/metabase/lib/js/metadata_test.cljs:52]: `values` are never returned by the BE

File: frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx [hunk 10]
```diff
@@ -35,19 +38,37 @@ export function SearchValuePicker({
...
-      limit: SEARCH_LIMIT,
+      remappedFieldId: searchFieldId,
+      values: selectedValues,
     },
     {
-      skip: !searchQuery,
+      skip:
+        fieldId === searchFieldId ||
+        selectedValues.length === 0 ||
+        searchValue.length !== 0,
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx:64]: Is this to avoid CLS while user is typing? Or to optimize?
Definitely deserves a comment.

But maybe we don't need it?

File: frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx [hunk 11]
```diff
@@ -35,19 +38,37 @@ export function SearchValuePicker({
...
     },
   );
 
-  const options = useMemo(() => getFieldOptions(fieldValues), [fieldValues]);
+  const options = useMemo(
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx:68]: Sometimes remapped values turn back to raw values.
In the video I'm using commas to apply subsequent values.


https://github.com/metabase/metabase/assets/6830683/ebfbda3a-bbfe-4d5c-8c0a-4a270b125ce5

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js [hunk 12]
```diff
@@ -1737,6 +1739,238 @@ describe("issue 39771", () => {
...
+        visitCard: () => cy.get("@modelId").then(visitModel),
+        fieldId: PEOPLE.ID,
+        fieldDisplayName: "ID",
+        fieldValue: 1,
+        fieldValueLabel: "Hudson Borer",
+        expectedRowCount: 1,
+      });
+    });
+
+    it("should work with native models", () => {
```
Comment (kamilmielnik) [inline e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:1904]: Should we assert native questions as well?

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js [hunk 13]
```diff
@@ -1737,6 +1739,238 @@ describe("issue 39771", () => {
...
+    assertQueryBuilderRowCount(expectedRowCount);
+  }
+
+  beforeEach(() => {
+    restore();
+    cy.signInAsAdmin();
+  });
+
+  describe("type/PK -> type/Name remapping (metabase#45063)", () => {
+    it("should work with questions", () => {
```
Comment (kamilmielnik) [inline e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:1880]: Should we assert metrics as well?

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js [hunk 14]
```diff
@@ -1737,6 +1739,238 @@ describe("issue 39771", () => {
   });
 });
 
+describe("issue 45063", () => {
```
Comment (kamilmielnik) [inline e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:1742]: I don't see a repro for #7231

File: frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx (hunk 11 above)
Comment (kamilmielnik) [reply frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx:68]: https://github.com/metabase/metabase/assets/6830683/d5786de2-fd50-43ea-b019-7704cbb3d956

Comment (ranquild) [reply frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx:68]: ^ native inputs are not changed here, it's a different component

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js (hunk 12 above)
Comment (ranquild) [reply e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:1904]: different component / bug

File: frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx (hunk 11 above)
Comment (ranquild) [reply frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx:68]: @kamilmielnik the only reason I can think of why values can turn into raw values:
- search response -> pick value
- we can remap the value because search results are still here
- we send a new remapping request to the newly selected values
- you start typing something new
- there is a new search response
- if the search response becomes available before the remapping response, in this internal you would see unmapped values

Comment (ranquild) [reply frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx]: OK, here we go.

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js (hunk 13 above)
Comment (ranquild) [reply e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:1879]: Metrics are going to be reworked soon. It's better not to test them right now

File: src/metabase/lib/field.cljc [hunk 15]
```diff
@@ -787,15 +787,16 @@
 (mu/defn ^:private remapped-field :- [:maybe ::lib.schema.metadata/column]
```
Comment (ranquild) [inline src/metabase/lib/field.cljc:787]: PK values are not remapped to type/Name fields. But we allow searching by Name. That's why `remapped-field` checks for FKs only.

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js (hunk 14 above)
Comment (kamilmielnik) [reply e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:1742]: Let's add a `(metabase#7231)` tag somewhere (`cy.log`?) for it.
Also for #37955

File: frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx [hunk 16]
```diff
@@ -25,29 +28,44 @@ interface SearchValuePickerProps {
...
     },
   );
 
-  const options = useMemo(() => getFieldOptions(fieldValues), [fieldValues]);
+  const searchOptions = canSearch ? getFieldOptions(fieldValues) : [];
+  const visibleOptions = getFilteredOptions(
+    searchOptions,
+    searchValue,
+    selectedValues,
+  );
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx:62]: I'm not confident it's a good idea to have FE-side filtering on top of BE-side filtering.
I see where this is coming from but it makes for a bad UX in some of the cases.
I tried it without `getFilteredOptions` and I think it works way more smooth this way.
Please consult product/design team if you disagree.

There's an annoying flicker of dropdown content on subsequent searches (but not the first one).

https://github.com/user-attachments/assets/f24d417b-3bd8-4bac-84d4-1b131288a5bd

**Review by kamilmielnik — APPROVED** [review]
FE code looks good, approving.
Please consider the UX suggestion :pray: 

> Note that selected values are displayed as raw values and this is out of scope for this PR.

Do we have this reported as a separate issue?

File: frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx (hunk 16 above)
Comment (kamilmielnik) [reply frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx:62]: I reported it separately: #45473
