### PR TITLE
21056 long question names wrapping for question modal

### LINKED ISSUE #21056: Combining question modal does not wrap long question names
**Describe the bug**
When adding series to a dashboard card, the names of the questions get cropped if they are long, so you can't see the full name and you might not know what you're adding

**Logs**
No logs

**To Reproduce**
1) create a dashboard
2) create 2 questions, one with a short name and another with a long long long name
3) add the first question to a dashboard and then add click the "add series" button on the first card to add the second one overlapped
4) see the long name being cropped

**Expected behavior**
Have a wrapping at least, or the famous "..." to see the full name as a tooltip

**Screenshots**
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: NA
- Your databases: Postgres
- Metabase version: master
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Cosmetic

**Additional context**
NA

### PR DESCRIPTION
**Pull request by losrebellos**
Fixes #21056.

### CODE REVIEW

**Review by alxnddr — COMMENTED** [review]
I'm a bit worried that it will return https://github.com/metabase/metabase/issues/13100
If we render the full list, it can bring 6k+ DOM nodes on larger instances. 

@flamber could you please take a look and share your thoughts?

**Comment by losrebellos** [comment]
Screenshots added [here](https://github.com/metabase/metabase/issues/21056#issuecomment-1088734817).

File: frontend/src/metabase/core/components/CheckBox/types.ts [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+  checkedColor?: string;
+  uncheckedColor?: string;
+  autoFocus?: boolean;
+  onChange?: (event: ChangeEvent<HTMLInputElement>) => void;
+  onFocus?: (event: FocusEvent<HTMLInputElement>) => void;
+  onBlur?: (event: FocusEvent<HTMLInputElement>) => void;
+}
+
+export interface CheckboxTooltipProps {
+  condition: boolean;
```
Comment (alxnddr) [inline frontend/src/metabase/core/components/CheckBox/types.ts:44]: nit: this prop name could be more descriptive

BTW, maybe `Ellipsified` component can be useful here?

File: frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionListItem.styled.jsx [hunk 2]
```diff
@@ -3,28 +3,36 @@ import { color } from "metabase/lib/colors";
...
+  &:last-child {
+    padding-bottom: 0.5rem;
+  }
 `;
 
-export const CheckboxContainer = styled.li`
-  display: flex;
-  flex-shrink: 0;
-  padding: 0 0.5rem;
+export const CheckboxContainer = styled.div`
```
Comment (alxnddr) [inline frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionListItem.styled.jsx:23]: 👍 for fixing invalid nesting I missed

**Review by alxnddr — APPROVED** [review]
Looks and works good! Please take a look a comment I left before merging

**Review by flamber — APPROVED** [review]
Works great. I'm not sure if it can easily be backported, otherwise just leave it in master for 43

File: frontend/src/metabase/core/components/CheckBox/types.ts (hunk 1 above)
Comment (losrebellos) [reply frontend/src/metabase/core/components/CheckBox/types.ts]: Not using `Ellipsified` because:
- It will add a `Tooltip` component for every rows even when not necessary
- It is using an observer when resizing but mobile layout is to be reviewed
