### PR TITLE
fix(webapp/sidenav): Fix bookmark reordering

### LINKED ISSUE #45635: When bookmarks are reordered, the wrong ordering gets recorded
The order doesn't get preserved in the FE:

Kapture 2024-07-16 at 07 55 51

Also, the FE is sending the wrong ordering to the API. Below, I drag items 1 and 2 to the bottom, but item 1 is still at the top after a refresh.

Kapture 2024-07-16 at 07 57 56

### PR DESCRIPTION
**Pull request by rafpaf**
On master, when you drag bookmarks to reorder them, the correct order is not saved, and bookmarks appear to be shuffled almost randomly if you reorder them more than once.

On this branch, bookmarks are reordered correctly and optimistically.

Kapture 2024-07-19 at 19 59 39

Closes #45635

Known problem: There is some flickering, as the GIF above shows

[x] e2e tests added

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#45632** <a href="https://app.graphite.dev/github/pr/metabase/metabase/45632?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by npfitz — CHANGES_REQUESTED** [review]
I don't think I agree with the direction this PR is going, which is adding another copy of the bookmark state to memory. Currently, this state exists within the entity framework, and now as a cached value in RTK Query.

It looks like the bookmark reorder action changed from a function that returned an object to a function that returns another function. This meant that when that function returned the `REORDER_ACTION` action, but it wasn't being dispatched, so the reducer for bookmarks wasn't picking it up. Dispatching that within the function causes re-ordering to work as expected

File: frontend/src/metabase/entities/bookmarks.js [hunk 1]
```diff
@@ -51,12 +51,12 @@ const Bookmarks = createEntity({
         type,
         item_id,
       }));
+      dispatch({ type: REORDER_ACTION, payload: bookmarks });
```
Comment (npfitz) [inline frontend/src/metabase/entities/bookmarks.js:54]: One thing about dispatching this event optimistically is that we don't handle the scenario where the request fails for some reason. If we want to be optimistic about this update, we should probably catch any incoming errors and revert things back to their previous state.

Comment (rafpaf) [reply frontend/src/metabase/entities/bookmarks.js:56]: Added this functionality, with an e2e test

File: frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BookmarkList/BookmarkList.tsx [hunk 2]
```diff
@@ -44,7 +44,7 @@ interface CollectionSidebarBookmarksProps {
   }: {
     newIndex: number;
     oldIndex: number;
-  }) => void;
+  }) => Promise<any>;
```
Comment (npfitz) [inline frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BookmarkList/BookmarkList.tsx:47]: In the future, it may be safer to use `Promise<void>` or something. Just incase someone tries to use whatever that promise may return

**Review by npfitz — APPROVED** [review]
