### PR TITLE
Fix Dimension instance mismatch problems when filtering via a native Model's remapped field

### LINKED ISSUE #16674: [Binning] UI inconsistencies for bucket display on tables from implicitly joined tables
As part of on ongoing process of documenting and covering binning issues (#16387), I noticed a few irregularities that are not strictly bugs, but definitely feel weird.

Binning options (buckets) render differently for the columns on implicitly joined table than they do for any other scenario.

#### To reproduce:
1. New Simple question > Sample Dataset > Orders
2. Click on the "Summarize" (right sidebar will open)

Longitude
3. Under "Group By" open the binning popover for User Longitude
4. `Don't bin` doesn't exist - it displays as `Longitude` (name of the column)
5. Also, there is no `Bin every X degrees`. It displays as `X°`

Number
3. Under "Group By" open the binning popover for Products Price
4. `Don't bin` doesn't exist - it displays as `Price` (name of the column)

For both number and longitude, the default "Auto bin" option is displayed as "Auto binned".

image

image

### LINKED ISSUE #16675: [Binning] UI inconsistencies for bucket display on tables from explicitly joined tables
As part of on ongoing process of documenting and covering binning issues (#16387), I noticed a few irregularities that are not strictly bugs, but definitely feel weird.

Binning options (buckets) render differently for the columns on explicitly joined table than they do for any other scenario.

#### To reproduce:
Longitude
1. New Custom question > Sample Dataset > Orders
2. Join with "People" on User ID = ID
3. Summarize, Count of Rows and then click "Pick a column to group by"
4. Under the "People" (can be aliased as "People -> User") choose `Longitude` binning options
5. `Don't bin` doesn't exist - it displays as `Default`
6. Also, there is no Bin every `X` degrees. It displays as `X°`

Number
1. New Cusotm question > Sample Dataset > Orders
2. Join with "Products" on Product ID = ID
3. Summarize, Count of Rows and then click "Pick a column to group by"
4. Under the "Product" (can be aliased as "Products") choose `Price` binning options
5. `Don't bin` doesn't exist - it displays as `Default`

*For both number and longitude, the default "Auto bin" option is displayed as "Auto binned".

image

image

### LINKED ISSUE #22715: Model query fails if mapped Metadata is using different column identifier than returned in the query (eg. aliases)
**Describe the bug**
If a model is based on a native query and has aliases, query fails if the aliased field is used.

**To Reproduce**
1. Go to [Instances model in Stats](https://stats.metabase.com/model/4165-instance)
2. Click on `Filter`
3. Select `Timestamp`, `Previous 7 days`
```
ERROR: column source.root_tstamp does not exist
```

**Expected behavior**
It should resolve the field and look for the alias. In this case, `timestamp`.

**Screenshots**
Generated query:
```
SELECT 
"source"."root_id" AS "root_id", 
"source"."instance_id" AS "instance_id", 
"source"."created_at" AS "created_at", 
"source"."timestamp" AS "timestamp", ...
FROM (SELECT root_id,
       id AS instance_id,
	   created_at,
	   root_tstamp AS timestamp,
...
FROM snowplow.com_metabase_instance_1
ORDER BY timestamp DESC) "source"
WHERE ("source"."root_tstamp" >= CAST(dateadd('day', -7, CAST(getdate() AS timestamp)) AS date)
   AND "source"."root_tstamp" < CAST(getdate() AS date))
LIMIT 1048575
```

The generated query uses the proper alias on the `select`, but uses the literal name on the `where` clause

**Information about your Metabase Installation:**
Stats on `master`

**Severity**
Impossible to use models based on native questions with aliases

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #22715
Fixes #16674
Fixes #16675

Root cause
1. `ColumnFilterDrill` was sending a filter with the incorrect `field_ref`
2. Code in `Filter` to determine if it is valid was returning false because we fail to hold onto a field_ref's third entry (the `options` object) in several different scenarios

The fix for this improves our ability to hold onto a field_ref's options, but this object is used when comparing dimensions for equality, so it had some consequences elsewhere in the app that I had to deal with in this PR. The upside is that it fixed a couple of other bugs.

I've added in-lined comments to explain my changes.

**Testing**
Follow the steps as described here: https://github.com/metabase/metabase/issues/22715#issuecomment-1126958012

Demo of the fix:

https://user-images.githubusercontent.com/13057258/184416912-a2b80626-8538-4468-912f-86ea14ac101c.mov

### CODE REVIEW

File: frontend/src/metabase-lib/lib/Dimension.ts [hunk 1]
```diff
@@ -982,8 +986,10 @@ export class FieldDimension extends Dimension {
       { ...this._options, ...options },
       this._metadata,
       this._query,
-      this._fieldInstance && {
+      {
         _fieldInstance: this._fieldInstance,
+        _subDisplayName: this._subDisplayName,
+        _subTriggerDisplayName: this._subTriggerDisplayName,
```
Comment (daltojohnso) [inline frontend/src/metabase-lib/lib/Dimension.ts:992]: These two properties are added here https://github.com/metabase/metabase/blob/dac22382883b2da98fdddcf44abe7c07581e5401/frontend/src/metabase-lib/lib/Dimension.ts#L991 so when reinstantiating FieldDimensions with more options via the `withOptions` method, we need to retain them explicitly.

File: frontend/src/metabase-lib/lib/Dimension.ts [hunk 2]
```diff
@@ -1141,9 +1147,14 @@ export class FieldDimension extends Dimension {
     if (this.fk()) {
       const fkDisplayName =
         this.fk() && stripId(this.fk().field().displayName());
-      displayName = `${fkDisplayName} ${FK_SYMBOL} ${displayName}`;
+      if (!displayName.startsWith(`${fkDisplayName} ${FK_SYMBOL}`)) {
```
Comment (daltojohnso) [inline frontend/src/metabase-lib/lib/Dimension.ts:1150]: Previously, calling `this.fk().field().displayName()` was pretty bad at actually obtaining a value. Now, it is much better, but sometimes creating a `displayName` using the `fkDisplayName` AND the `displayName` looks awful as the values can repeat. (Example: `Products --> Products --> Category`)

File: frontend/src/metabase-lib/lib/queries/StructuredQuery.ts [hunk 3]
```diff
@@ -330,28 +330,31 @@ class StructuredQueryInner extends AtomicQuery {
...
-                {
-                  "base-type": column.base_type,
-                },
-              ],
-              source: "fields",
-              // HACK: need to thread the query through to this fake Field
-              query: this,
-            }),
-        ),
+        fields,
```
Comment (daltojohnso) [inline frontend/src/metabase-lib/lib/queries/StructuredQuery.ts:357]: No changes here besides moving the evaluation of `fields` to a variable. I find myself stepping through this logic in the browser debugger not infrequently so having it be more debuggable is nice.

File: frontend/src/metabase/query_builder/components/BreakoutPopover.jsx [hunk 4]
```diff
@@ -26,6 +26,8 @@ const BreakoutPopover = ({
       className={className}
       width={width}
       field={breakout}
+      query={query}
+      metadata={query.metadata()}
```
Comment (daltojohnso) [inline frontend/src/metabase/query_builder/components/BreakoutPopover.jsx:30]: Passing these components to `FieldList` because this "ui" component instantiates Dimensions, so we need access to queries to properly instantiate the dimensions of models, nested questions, etc.

File: frontend/test/metabase/scenarios/models/reproductions/22715-remapped-values-override-column-identifier.cy.spec.js [hunk 5]
```diff
@@ -26,10 +26,10 @@ describe.skip("filtering based on the remapped column name should result in a co
...
       // Let's go straight to the model metadata editor
       cy.visit(`/model/${id}/metadata`);
-      // Without this Cypress fails to remap the column because an element becomes detached from the DOM
-      cy.findByText(
-        "Use the tab key to navigate through settings and columns.",
-      );
+      // Without this Cypress fails to remap the column because an element becomes detached from the DOM.
+      // This is caused by the DatasetFieldMetadataSidebar component rerendering mulitple times.
+      cy.findByText("Database column this maps to");
+      cy.wait(5000);
```
Comment (daltojohnso) [inline frontend/test/metabase/scenarios/models/reproductions/22715-remapped-values-override-column-identifier.cy.spec.js:32]: This is awful, but the component this tests rerenders like 10 times, so you run into situations where the element this test finds has been detached from the DOM. Waiting for 5 secs lets the component calm down.

https://user-images.githubusercontent.com/13057258/184419208-fbe2675e-5480-42ca-ad97-dd2817c0e96d.mov

File: frontend/src/metabase/query_builder/components/DimensionList.jsx [hunk 6]
```diff
@@ -60,9 +61,14 @@ export default class DimensionList extends Component {
...
   itemIsSelected = item => {
     const dimensions = this._getDimensions();
+    const { dimension } = item;
     return (
       item.dimension &&
-      _.any(dimensions, d => item.dimension.isSameBaseDimension(d))
+      _.any(dimensions, d => {
+        return isVirtualCardId(dimension?.query()?.table()?.id)
+          ? d.isSameBaseDimension(dimension.withoutJoinAlias())
+          : d.isSameBaseDimension(dimension);
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/components/DimensionList.jsx:70]: Seems worthwhile to have a comment in the code along the lines of the PR comment.

Silly question: just using `dimension.withoutJoinAlias()` for everything wouldn't work here, would it?

File: frontend/src/metabase-lib/lib/queries/StructuredQuery.ts [hunk 7]
```diff
@@ -330,28 +330,31 @@ class StructuredQueryInner extends AtomicQuery {
...
+          "field",
+          column.name,
+          {
+            "base-type": column.base_type,
+          },
+        ];
+
+        return new Field({
+          ...column,
+          // TODO FIXME -- Do NOT use field-literal unless you're referring to a native query
```
Comment (gusaiani) [inline frontend/src/metabase-lib/lib/queries/StructuredQuery.ts:344]: Should this TODO get fixed before merging this, or rather: how much has this been hurting us?

Comment (gusaiani) [inline frontend/src/metabase-lib/lib/queries/StructuredQuery.ts:344]: Extracting this block that yields `const fields` into a function with a nice name might further help readers in the future. 

Also smaller cyclomatic complexity.

File: frontend/src/metabase-lib/lib/queries/StructuredQuery.ts (hunk 3 above)
Comment (gusaiani) [reply frontend/src/metabase-lib/lib/queries/StructuredQuery.ts:357]: Definitely way better.

File: frontend/test/metabase/scenarios/models/reproductions/22715-remapped-values-override-column-identifier.cy.spec.js (hunk 5 above)
Comment (gusaiani) [reply frontend/test/metabase/scenarios/models/reproductions/22715-remapped-values-override-column-identifier.cy.spec.js:32]: Noted, thanks.

**Review by gusaiani — APPROVED** [review]
Impressive investigation and solution.

A few super minor comments inlined.

File: frontend/src/metabase/query_builder/components/DimensionList.jsx (hunk 6 above)
Comment (daltojohnso) [reply frontend/src/metabase/query_builder/components/DimensionList.jsx]: Good call out! This apparently works and is much simpler 🥇

File: frontend/src/metabase-lib/lib/queries/StructuredQuery.ts (hunk 7 above)
Comment (daltojohnso) [reply frontend/src/metabase-lib/lib/queries/StructuredQuery.ts:344]: This TODO is from aeons ago. I'll keep it for now, but may remove soon as not sure what the value is.
