### PR TITLE
Avoid updating url when navigating to query builder

### LINKED ISSUE #68856: Drill through shows duplicate events due to URL changing twice.
### Describe the bug

If you have an event listener on the iframe. Take full app embedding for example and you drill through a question the event listener will show two entries

Image

In reality it's not a duplicate but the URL changeing twice (the hash for the new question is different in both)

### To Reproduce

Just have full-app embedding and add a `window.addEventListener("message", handleMessage);` to the iframe and drill through a question inside of a dashboard. Notice the double events

### Expected behavior

Only 1 event shows up because only 1 URL should be created

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.58 but I think it was always like this
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/68856

Removes the unnecessary url updates that happens on some navigations.

The updates are caused by different implementations for the function that returns the query has in the url, resulting in slightly different (but equivalent) hashes.

This is not really a UI issue but it was creating double navigation events in the event log for some customers.

#### To verify
1. Open `Examples` → `E-commerce insights` 
3. Click the header for `Revenue and orders over time` whilst carefully watching the browser url bar.
4. The url should just change once to the target page, instead of updating twice.

Same goes for clicking a bar in the chart and clicking `See these orders`.

### CODE REVIEW

File: frontend/src/metabase-lib/v1/Question.ts [hunk 1]
```diff
@@ -680,12 +680,10 @@ class Question {
       const origCardSerialized =
         originalQuestion &&
         originalQuestion._serializeForUrl({
-          includeEntityId: false,
           includeDatasetQuery: false,
           includeOriginalCardId: false,
         });
       const currentCardSerialized = this._serializeForUrl({
-        includeEntityId: false,
```
Comment (romeovs) [inline frontend/src/metabase-lib/v1/Question.ts:688]: No longer used

File: frontend/test/metabase-lib/lib/Question.unit.spec.js [hunk 2]
```diff
@@ -590,7 +590,7 @@ describe("Question", () => {
 
   describe("URLs", () => {
     const adhocUrl =
-      "/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJsaWIvdHlwZSI6Im1icWwvcXVlcnkiLCJzdGFnZXMiOlt7ImxpYi90eXBlIjoibWJxbC5zdGFnZS9tYnFsIiwic291cmNlLXRhYmxlIjoyfV19LCJkaXNwbGF5IjoidGFibGUiLCJuYW1lIjoiUmF3IG9yZGVycyBkYXRhIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319";
+      "/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJsaWIvdHlwZSI6Im1icWwvcXVlcnkiLCJzdGFnZXMiOlt7ImxpYi90eXBlIjoibWJxbC5zdGFnZS9tYnFsIiwic291cmNlLXRhYmxlIjoyfV19LCJkaXNwbGF5IjoidGFibGUiLCJuYW1lIjoiUmF3IG9yZGVycyBkYXRhIiwicGFyYW1ldGVyVmFsdWVzIjp7fSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319";
```
Comment (romeovs) [inline frontend/test/metabase-lib/lib/Question.unit.spec.js:594]: Added `parameterValues: {}` for consistency.

File: frontend/test/metabase-lib/lib/Question.unit.spec.js [hunk 3]
```diff
@@ -982,10 +982,12 @@ describe("Question", () => {
         const deserializedCard = {
           ...card,
           parameters,
-          id: undefined,
           original_card_id: card.id,
+          parameterValues: {},
         };
 
+        delete deserializedCard.id;
```
Comment (romeovs) [inline frontend/test/metabase-lib/lib/Question.unit.spec.js:989]: `id: undefined` does not serialize the same as no `id` present.

**Review by heypoom — APPROVED** [review]
(React SDK review only) changes to ad-hoc question looks good!

File: frontend/src/metabase-lib/v1/Question.ts [hunk 4]
```diff
@@ -724,60 +719,45 @@ class Question {
...
+      "dashboardId",
+      "dashcardId",
+      "description",
+      "display",
+      "name",
+      "parameters",
+      "parameterValues",
+      "type",
+      "visualization_settings",
+      "parameterValues",
```
Comment (fraserdrops) [inline frontend/src/metabase-lib/v1/Question.ts]: parameterValues appears twice

File: frontend/src/metabase/lib/card.ts [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+  const res: { [key in Key]?: unknown } = {};
+  for (const key of keysToInclude) {
+    // coerce to undefined to omit
+    res[key as Key] = value[key as Key] ?? undefined;
+  }
+
+  return res;
+}
+
+export function isEqualCard(card1: Card, card2: Card) {
```
Comment (fraserdrops) [inline frontend/src/metabase/lib/card.ts]: These types don't seem to reflect that card1 and card2 possibly don't exist?

**Review by fraserdrops — APPROVED** [review]
Good cleanup!
