### PR TITLE
fix bug where column settings were dropped

### LINKED ISSUE #11113: 0.33.3/0.33.4 X-axis date style
Seems like the X-axis labels, want using dates, won't apply any given date styles anymore.
Not the abbreviated style or a different date style.
Screenshot 2019-10-10 at 09 51 05

This used to work in the previous version we used, 0.32.10, but ever since 0.33.3 the label style can't be changed anymore.
In the screenshot you can see the editor when applying the style, but after saving the original style hasn't changed.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #11113

I think this broke in #10864. I had forgotten a `...` 🤦‍♂. This PR adds the `...` and a test.

### CODE REVIEW

**Comment by mazameli** [comment]
@kdoh and/or @tlrobinson, mind giving this a review?

File: frontend/src/metabase/visualizations/lib/apply_axis.js [hunk 1]
```diff
@@ -145,7 +145,9 @@ export function applyChartTimeseriesXAxis(
       const timestampFixed = moment(timestamp)
         .utcOffset(dataOffset)
         .format();
-      const { column, columnSettings } = chart.settings.column(dimensionColumn);
+      const { column, ...columnSettings } = chart.settings.column(
```
Comment (tlrobinson) [inline frontend/src/metabase/visualizations/lib/apply_axis.js]: Oh interesting, I though spreading `undefined` (which `columnSettings` would have been) would have crashed, but apparently you can spread `null`/`undefined`. I guess I can stop doing things like `{ ...(something || {}) }`

**Review by tlrobinson — APPROVED** [review]

File: frontend/src/metabase/visualizations/lib/apply_axis.js (hunk 1 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/lib/apply_axis.js]: Yeah! I just had the [same realization](https://github.com/metabase/metabase/pull/10996#discussion_r335158902) a few days ago!
