### PR TITLE
Fix native time tooltip formatting

### LINKED ISSUE #11435: Time display in Tooltip/ticks is broken for timeseries charts
Display of time in tooltips of timeseries charts has been missing/broken since 0.33.1 

image

- Metabase jar file on Win10
- Postgres 12.1
- Chrome 78.0.3904.108 (Official Build) (64-bit)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/11435

How to test:
- Create a native question
```
SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY"
FROM "PUBLIC"."ORDERS"
WHERE ("PUBLIC"."ORDERS"."CREATED_AT" >= timestamp with time zone '2019-03-12 00:00:00.000+03:00'
       AND "PUBLIC"."ORDERS"."CREATED_AT" < timestamp with time zone '2019-03-13 00:00:00.000+03:00')
LIMIT 1048575
```
- Visualization -> Line. Use `CREATED_AT` for dimension (`X`) and `TOTAL` for metric (`Y`).
- Settings -> Data -> `CREATED_AT` -> Show the time -> `HH:MM:SS.MS`
- Hover over a dot on the chart. The formatted value should contain milliseconds. 

Screenshot 2022-07-21 at 19 57 57

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/settings/column.js [hunk 1]
```diff
@@ -154,6 +154,32 @@ function timeStyleOption(style, description) {
   };
 }
 
+function getTimeEnabledOptionsForUnit(unit) {
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/lib/settings/column.js:157]: Uses the same approach used for `date_style`

File: frontend/src/metabase/visualizations/lib/apply_axis.js [hunk 2]
```diff
@@ -116,9 +116,6 @@ export function applyChartTimeseriesXAxis(
       chart.settings["graph.x_axis.gridLine_enabled"],
     );
 
-    if (dimensionColumn.unit == null) {
-      dimensionColumn = { ...dimensionColumn, unit: dataInterval.interval };
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/lib/apply_axis.js:120]: This approach created a race condition since calls to `isValid` for settings are cached. If tick were formatted before settings/tooltips are shown, it would constantly return `false` because of the invalid `unit` value.

**Review by WiNloSt — APPROVED** [review]
Works as expected, but this trips another test in https://github.com/metabase/metabase/runs/7454526483?check_suite_focus=true
