### PR TITLE
Fix #25521: 403 page when visiting question's URL with a card template tag

### LINKED ISSUE #25521: 403 page when visiting question's URL with a card template tag
Link to slack for more context: https://metaboat.slack.com/archives/C01LQQ2UW03/p1663660070441759

Directly caused by [this merged PR](https://github.com/metabase/metabase/pull/25319), (update: although indirectly by this PR https://github.com/metabase/metaboat/issues/121).

### Steps to reproduce:

Note you can quickly reproduce bug on stats.metabase.com by following [this link](https://stats.metabase.com/question/3967-mom-mrr-growth#eyJuYW1lIjoiTW9NIE1SUiBHcm93dGgiLCJkZXNjcmlwdGlvbiI6Ik1vbnRoIG92ZXIgTW9udGggKE1vTSkgTVJSIGdyb3d0aCBpcyBjYWxjdWxhdGVkIGJ5IHN1YnRyYWN0aW5nIE5ldCBNUlIgaW4gdGhlIGN1cnJlbnQgcGVyaW9kIGZyb20gTmV0IE1SUiBpbiB0aGUgcHJldmlvdXMgcGVyaW9kLCBhbmQgZGl2aWRpbmcgdGhhdCBmaWd1cmUgYnkgTmV0IE1SUiBpbiB0aGUgcHJldmlvdXMgcGVyaW9kLiIsImRhdGFzZXRfcXVlcnkiOnsidHlwZSI6Im5hdGl2ZSIsIm5hdGl2ZSI6eyJxdWVyeSI6IndpdGggbXJyIGFzIChcbiAgc2VsZWN0XG4gICAgICBkYXRlX3RydW5jKCdtb250aCcsIGguZGF0ZSkgYXMgbW9udGgsXG4gICAgICBzdW0oYW1vdW50X2RvbGxhcnMpIGFzIG1yclxuICBmcm9tIHt7IzI4NzktaG9zdGluZy1hcnJ9fSBoXG4gIGlubmVyIGpvaW4gZGJ0X21vZGVscy5zZWxmX3NlcnZpY2VfYWNjb3VudHMgYVxuICAgICAgb24gaC5zdWJzY3JpcHRpb25faWQgPSBhLnN0cmlwZV9zdWJzY3JpcHRpb25faWRcbiAgZ3JvdXAgYnkgMSBcbiAgb3JkZXIgYnkgMVxuKSwgbW9tX21ycl9ncm93dGggYXMgKFxuICAgIHNlbGVjdFxuICAgICAgbW9udGgsXG4gICAgICBtcnIsXG4gICAgICBsYWcobXJyKSBvdmVyKG9yZGVyIGJ5IG1vbnRoIGFzYykgYXMgcHJldl9tb250aF9tcnIsXG4gICAgICAobXJyL2xhZyhtcnIpIG92ZXIob3JkZXIgYnkgbW9udGggYXNjKSkgLSAxIGFzIG1vbV9tcnJfZ3Jvd3RoXG4gICAgZnJvbSBtcnJcbilcbnNlbGVjdCAqIFxuZnJvbSBtb21fbXJyX2dyb3d0aCBcbndoZXJlIG1vbnRoID49ICcyMDIwLTExLTAxJyIsInRlbXBsYXRlLXRhZ3MiOnsiIzI4NzktaG9zdGluZy1hcnIiOnsiaWQiOiI4MzU3Y2FlMi00YTlmLTk1NGYtYWEzMi1mYWM4NTdhZDM0NGEiLCJuYW1lIjoiIzI4NzktaG9zdGluZy1hcnIiLCJkaXNwbGF5LW5hbWUiOiIjMjg3OS1ob3N0aW5nLWFyciIsInR5cGUiOiJjYXJkIiwiY2FyZC1pZCI6Mjg3OX19fSwiZGF0YWJhc2UiOjI2fSwiZGlzcGxheSI6ImJhciIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsiZ3JhcGgueV9heGlzLnRpdGxlX3RleHQiOiIlIE1SUiBHcm93dGgiLCJncmFwaC5zaG93X3ZhbHVlcyI6dHJ1ZSwidGFibGUuY2VsbF9jb2x1bW4iOiJtcnIiLCJncmFwaC54X2F4aXMuYXhpc19lbmFibGVkIjoiY29tcGFjdCIsImdyYXBoLnhfYXhpcy50aXRsZV90ZXh0IjoiTW9udGgiLCJncmFwaC5tZXRyaWNzIjpbIm1vbV9tcnJfZ3Jvd3RoIixudWxsXSwidGFibGUucGl2b3RfY29sdW1uIjoibW9udGgiLCJjb2x1bW5fc2V0dGluZ3MiOnsiW1wibmFtZVwiLFwibXJyXCJdIjp7Im51bWJlcl9zdHlsZSI6ImN1cnJlbmN5IiwiZGVjaW1hbHMiOjB9LCJbXCJuYW1lXCIsXCJwcmV2X21vbnRoX21yclwiXSI6eyJudW1iZXJfc3R5bGUiOiJjdXJyZW5jeSIsImRlY2ltYWxzIjowfSwiW1wibmFtZVwiLFwibW9tX21ycl9ncm93dGhcIl0iOnsibnVtYmVyX3N0eWxlIjoicGVyY2VudCJ9LCJbXCJuYW1lXCIsXCJtb250aFwiXSI6eyJ0aW1lX2VuYWJsZWQiOm51bGwsImRhdGVfYWJicmV2aWF0ZSI6dHJ1ZX19LCJzZXJpZXNfc2V0dGluZ3MiOnsibXJyIjp7InRpdGxlIjoiTVJSIChUaGlzIE1vbnRoKSJ9LCJwcmV2X21vbnRoX21yciI6eyJ0aXRsZSI6Ik1SUiAoUHJldmlvdXMgTW9udGgpIn0sIm1vbV9tcnJfZ3Jvd3RoIjp7InRpdGxlIjoiTW9NIE1SUiBHcm93dGgifX0sImdyYXBoLnlfYXhpcy5hdXRvX3JhbmdlIjp0cnVlLCJncmFwaC5kaW1lbnNpb25zIjpbIm1vbnRoIl0sInN0YWNrYWJsZS5zdGFja190eXBlIjoic3RhY2tlZCJ9LCJvcmlnaW5hbF9jYXJkX2lkIjozOTY3fQ==).

[Loom demo](https://www.loom.com/share/76aa0757d0e04f11bb3d280b4623f23a)

1. Create & save a native query question with a card template tag that isn't the correct slug, e.g. `select * from {{#1}}`
2. Refresh the page, the URL should have a base64 string of the encoded question, e.g. http://localhost:3000/question/64-test-repro#eyJuYW1lIjoidGVzdC1yZXBybyIsImRlc2NyaXB0aW9uIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgKiBmcm9tIHt7IzYxLW99fSIsInRlbXBsYXRlLXRhZ3MiOnsiIzYxLW8iOnsiaWQiOiIzZDAzOGFlZi0wNDcyLTRhYjEtNmQ0MC0wMzQ4MGM2ZmRmZmMiLCJuYW1lIjoiIzYxLW8iLCJkaXNwbGF5LW5hbWUiOiIjNjEtbyIsInR5cGUiOiJjYXJkIiwiY2FyZC1pZCI6NjF9fX0sImRhdGFiYXNlIjoxfSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5waXZvdF9jb2x1bW4iOiJRVUFOVElUWSIsInRhYmxlLmNlbGxfY29sdW1uIjoiSUQifSwib3JpZ2luYWxfY2FyZF9pZCI6NjR9

3. Use that URL to open the question in another tab. You'll get a 403 error page.
image

### PR DESCRIPTION
**Pull request by calherries**
This fixes https://github.com/metabase/metabase/issues/25521

### What the error page was designed to prevent:

The error page was designed to show a better error messages to the user if they were trying to view a dashcard that had been removed from a dashboard. Rather than an arbitrary server error, we show them a permissions error page. See [this PR for details](https://github.com/metabase/metabase/pull/19300).

### What causes the error page to show in this instance:

The error page is mistakenly shown when opening a link to a card with a serialized URL, e.g. [this](https://stats.metabase.com/question/3967-mom-mrr-growth#eyJuYW1lIjoiTW9NIE1SUiBHcm93dGgiLCJkZXNjcmlwdGlvbiI6Ik1vbnRoIG92ZXIgTW9udGggKE1vTSkgTVJSIGdyb3d0aCBpcyBjYWxjdWxhdGVkIGJ5IHN1YnRyYWN0aW5nIE5ldCBNUlIgaW4gdGhlIGN1cnJlbnQgcGVyaW9kIGZyb20gTmV0IE1SUiBpbiB0aGUgcHJldmlvdXMgcGVyaW9kLCBhbmQgZGl2aWRpbmcgdGhhdCBmaWd1cmUgYnkgTmV0IE1SUiBpbiB0aGUgcHJldmlvdXMgcGVyaW9kLiIsImRhdGFzZXRfcXVlcnkiOnsidHlwZSI6Im5hdGl2ZSIsIm5hdGl2ZSI6eyJxdWVyeSI6IndpdGggbXJyIGFzIChcbiAgc2VsZWN0XG4gICAgICBkYXRlX3RydW5jKCdtb250aCcsIGguZGF0ZSkgYXMgbW9udGgsXG4gICAgICBzdW0oYW1vdW50X2RvbGxhcnMpIGFzIG1yclxuICBmcm9tIHt7IzU0NDctY2hhcmdlc319IGhcbiAgaW5uZXIgam9pbiBkYnRfbW9kZWxzLnNlbGZfc2VydmljZV9hY2NvdW50cyBhXG4gICAgICBvbiBoLnN1YnNjcmlwdGlvbl9pZCA9IGEuc3RyaXBlX3N1YnNjcmlwdGlvbl9pZFxuICBncm91cCBieSAxIFxuICBvcmRlciBieSAxXG4pLCBtb21fbXJyX2dyb3d0aCBhcyAoXG4gICAgc2VsZWN0XG4gICAgICBtb250aCxcbiAgICAgIG1ycixcbiAgICAgIGxhZyhtcnIpIG92ZXIob3JkZXIgYnkgbW9udGggYXNjKSBhcyBwcmV2X21vbnRoX21ycixcbiAgICAgIChtcnIvbGFnKG1ycikgb3ZlcihvcmRlciBieSBtb250aCBhc2MpKSAtIDEgYXMgbW9tX21ycl9ncm93dGhcbiAgICBmcm9tIG1yclxuKVxuc2VsZWN0ICogXG5mcm9tIG1vbV9tcnJfZ3Jvd3RoIFxud2hlcmUgbW9udGggPj0gJzIwMjAtMTEtMDEnIiwidGVtcGxhdGUtdGFncyI6eyIjNTQ0Ny1jaGFyZ2VzIjp7ImlkIjoiODM1N2NhZTItNGE5Zi05NTRmLWFhMzItZmFjODU3YWQzNDRhIiwibmFtZSI6IiM1NDQ3LWNoYXJnZXMiLCJkaXNwbGF5LW5hbWUiOiIjNTQ0Ny1jaGFyZ2VzIiwidHlwZSI6ImNhcmQiLCJjYXJkLWlkIjo1NDQ3fX19LCJkYXRhYmFzZSI6MjZ9LCJkaXNwbGF5IjoiYmFyIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJncmFwaC55X2F4aXMudGl0bGVfdGV4dCI6IiUgTVJSIEdyb3d0aCIsImdyYXBoLnNob3dfdmFsdWVzIjp0cnVlLCJ0YWJsZS5jZWxsX2NvbHVtbiI6Im1yciIsImdyYXBoLnhfYXhpcy5heGlzX2VuYWJsZWQiOiJjb21wYWN0IiwiZ3JhcGgueF9heGlzLnRpdGxlX3RleHQiOiJNb250aCIsImdyYXBoLm1ldHJpY3MiOlsibW9tX21ycl9ncm93dGgiLG51bGxdLCJ0YWJsZS5waXZvdF9jb2x1bW4iOiJtb250aCIsImNvbHVtbl9zZXR0aW5ncyI6eyJbXCJuYW1lXCIsXCJtcnJcIl0iOnsibnVtYmVyX3N0eWxlIjoiY3VycmVuY3kiLCJkZWNpbWFscyI6MH0sIltcIm5hbWVcIixcInByZXZfbW9udGhfbXJyXCJdIjp7Im51bWJlcl9zdHlsZSI6ImN1cnJlbmN5IiwiZGVjaW1hbHMiOjB9LCJbXCJuYW1lXCIsXCJtb21fbXJyX2dyb3d0aFwiXSI6eyJudW1iZXJfc3R5bGUiOiJwZXJjZW50In0sIltcIm5hbWVcIixcIm1vbnRoXCJdIjp7InRpbWVfZW5hYmxlZCI6bnVsbCwiZGF0ZV9hYmJyZXZpYXRlIjp0cnVlfX0sInNlcmllc19zZXR0aW5ncyI6eyJtcnIiOnsidGl0bGUiOiJNUlIgKFRoaXMgTW9udGgpIn0sInByZXZfbW9udGhfbXJyIjp7InRpdGxlIjoiTVJSIChQcmV2aW91cyBNb250aCkifSwibW9tX21ycl9ncm93dGgiOnsidGl0bGUiOiJNb00gTVJSIEdyb3d0aCJ9fSwiZ3JhcGgueV9heGlzLmF1dG9fcmFuZ2UiOnRydWUsImdyYXBoLmRpbWVuc2lvbnMiOlsibW9udGgiXSwic3RhY2thYmxlLnN0YWNrX3R5cGUiOiJzdGFja2VkIn0sIm9yaWdpbmFsX2NhcmRfaWQiOjM5Njd9).

It happens because the serialized card contains an empty parameters list, which according to this [conditional](https://github.com/metabase/metabase/blob/49e023f673d58dc0ce2e362cf54a2a0089376304/frontend/src/metabase/query_builder/actions/core/parameterUtils.ts#L44), will cause the frontend to verify if the dashboard still has a matching dashcard that matches this card.

We then check for a dashcard's existence on the dashboard (unnecessarily in this case, since the card is not a dashcard, and it's not on a dashboard) [here](https://github.com/metabase/metabase/blob/49e023f673d58dc0ce2e362cf54a2a0089376304/frontend/src/metabase/parameters/utils/dashboards.ts#L220). Given the question doesn't have a dashcardId, the check fails, triggering the 403 error page. 

### How this PR fixes the bug, and doesn't cause any security issues.

Cards that are not dashcards shouldn't be checked whether they still exist on a dashboard or not. So we simply don't need to check if the card doesn't have a dashcardId. There is no risk of causing the original issue, 

Relevant links:
- Original Issue: https://github.com/metabase/metaboat/issues/121
- Original PR where the error handling is introduced: https://github.com/metabase/metabase/pull/19300
- [Notion doc](https://www.notion.so/metabase/Parameters-Security-Fix-360bbde060fc4e33a1c94f8bc61311e3) for the security fix

### CODE REVIEW

File: frontend/src/metabase/query_builder/actions/core/parameterUtils.ts [hunk 1]
```diff
@@ -128,7 +128,11 @@ export async function handleDashboardParameters(
     deserializedCard,
     originalCard,
   });
-  if (shouldPropagateParameters && deserializedCard) {
+  if (
+    shouldPropagateParameters &&
+    deserializedCard &&
+    deserializedCard.dashcardId
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/actions/core/parameterUtils.ts:134]:
```suggestion
    deserializedCard?.dashcardId
```

???

**Review by daltojohnso — APPROVED** [review]

**Comment by daltojohnso** [comment]
I think the committed suggestion might be formatted incorrectly -- if you run prettier on the file it'll probably make that if predicate a single line.
