### PR TITLE
Don't show metrics in the join step

### LINKED ISSUE #66210: Metrics should not be a valid join target for joins in the entity picker
### Describe the bug

In the entity picker, we present metrics as a valid join target, we should not.

Image

### To Reproduce

1. Go to the query builder and select a table from a db that has metrics
2. open the join menu, and open the big entity picker (browse all from the minipicker)
3. browse to a colleciton with metrics
4. 😢

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
master: 0b42ad8
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npfitz**
closes #66210
### Description
Removes metrics from the data picker in the join step

### How to verify
1. Make sure you have a metric on your instance
2. start a new question and pick a data source
3. Start a join, and look for your metric. It should not be shown.

### Demo
 
https://github.com/user-attachments/assets/3d8fab03-aca3-4106-bcbe-ec10ff5bf411

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/common/components/Pickers/DataPicker/components/DataPickerModal.tsx [hunk 1]
```diff
@@ -219,19 +219,17 @@ export const DataPickerModal = ({
...
         folderModels: ["collection", "dashboard", "schema", "database"],
         icon: "folder",
         extraButtons: [filterButton],
         render: ({ onItemSelect }) => (
           <QuestionPicker
             initialValue={value}
-            models={QUESTION_PICKER_MODELS}
+            models={[
+              ...models,
+              ...(models.includes("card") ? ["dashboard" as const] : []),
```
Comment (iethree) [inline frontend/src/metabase/common/components/Pickers/DataPicker/components/DataPickerModal.tsx:231]: I'd vote we not make questions-in-dashboards valid data picker targets 😵‍💫

**Review by iethree — APPROVED** [review]

File: frontend/src/metabase/common/components/Pickers/DataPicker/components/DataPickerModal.tsx (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/common/components/Pickers/DataPicker/components/DataPickerModal.tsx:231]: We had that vote (and lost) forever ago, but it sounds like we're going to start moving in that direction now. But as of right now, they're valid targets aren't they?
