### PR TITLE
Fix "Exclude" field filter in Native Query params for SQL databases

### LINKED ISSUE #26861: "Exclude" field filter on Native Query breaks if you select a value to exclude
**Describe the bug**

 The “Exclude” time filter in SQL Native queries doesn't seem to work. It only works when the whole selection is present, the moment you deselect any granularity it breaks

**To Reproduce**

1. Go to New SQL Query and write a query with a date field filter

```
Select * 
from orders
Where {{date}}
```

2. Setup the variable as a Field Filter (Date Filter) on Created At:

image

5. Click on the filter widget > click "Excludes..." >  De-select any granularity

image

6. See error

`Don't know how to parse date param 'exclude-days-Mon-Tue-Wed-Thu-Fri-Sat-Sun' — invalid format`

**Expected behavior**
Query excludes my selected options

**Information about your Metabase Installation:**

- Metabase version: 44.6 

**Additional context**
Could be related to https://github.com/metabase/metabase/issues/24236 since it doesn't replicate on the GUI Editor only on Native SQL

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/26861 for sql databases. A fix for Non-SQL databases (e.g. Mongo) is to come.

### Solution 

The solution is discussed in this comment:
https://github.com/metabase/metabase/pull/30760#discussion_r1193992517

### Required background understanding

Most importantly: parameters have a `type` that is copied from a template tag's `widget-type` on the frontend.

Note there's no option on the frontend to set a filter widget type of "Exclude" or something like that on a native query. I just created an [issue for this](https://github.com/metabase/metabase/issues/30764). You can only create a template tag with filter widget type of "Date Filter". This will set `widget-type="date/all-options"` for the template-tag.

image

If you select an "Exclude..." type parameter like so:
image

The parameter for the template-tag will have a `value="exclude-months-Jan"` and `type="date/all-options"`. The `type` will always be copied from the widget-type, regardless of which type of parameter it is, e.g. under "Specific dates..." or "Relative dates..."

### Alternatives considered

Another solution would be to set the `type` of the parameter to a more narrow type, like `"date/exclusion"` on the FE, instead of `date/all-options`. The difficulty with this is the code would have to be backwards compatible with the type being `date/all-options` anyway, since all previously created parameters would have this type. This could be solved with a migration, but it's more effort for little gain. In any case, this migration is possible in the future and little code will need to be changed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30760)

### CODE REVIEW

File: src/metabase/driver/sql/parameters/substitution.clj [hunk 1]
```diff
@@ -262,30 +262,42 @@
...
-                                                  (date-range-field-filter->replacement-snippet-info driver value))
+
+      (and (params.dates/date-type? param-type)
+           (re-matches params.dates/date-exclude-regex value))
+      (let [field-clause (field->clause driver field param-type)]
+        (->> (params.dates/date-string->filter value field-clause)
+             mbql.u/desugar-filter-clause
+             qp.wrap-value-literals/wrap-value-literals-in-mbql
+             ->honeysql
+             (honeysql->replacement-snippet-info driver)))
```
Comment (calherries) [inline src/metabase/driver/sql/parameters/substitution.clj:287]: This is the block of code that fixes the bug. "Exclude..." type params never worked with native query template tags because the next condition on [line 281](https://github.com/metabase/metabase/pull/30760/files#diff-b545fa8a68713ab8d1171bc5fb528b1ff68042490d9a25f28e480ba4c04dc3c5L281) would evaluate to `true`, and the value (e.g. "exclude-months-Jan") would be passed to `date-range-field-filter->replacement-snippet-info`, which would blow up because it's not a date range. So the solution is to match against exclude type parameters and convert them to an MBQL filter clause with `params.dates/date-string->filter`.

**Review by qnkhuat — APPROVED** [review]
Thanks for having an alternative solution, but having another type would mean we need to change the UI as well, and that probably needs Product's feedback.

I agree with the current approach as mbql is currently doing the same thing.
