### PR TITLE
fix(sdk): secondary background color is not mapped to theme

### LINKED ISSUE #65115: [SDK] Dashboard background color is not mapped in 57
### Describe the bug

https://github.com/metabase/metabase/pull/65084 caused the `bg-secondary` color (used in dashboard background) to be broken when the SDK theming is applied, because that color was defined via createColorVars("light") yet it wasn't mapped on the SDK theming.

Image

### To Reproduce

1. Go to the embed wizard
2. Set background color to a different color, maybe dark
3. The dashboard background is now always greyish white

### Expected behavior

The dashboard background must be mapped to `background-secondary`

### Logs

_No response_

### Information about your Metabase installation

```JSON
-
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by heypoom**
Closes EMB-935
Closes #65115

Maps the `background-secondary` SDK theme color to `bg-secondary` which are used in the dashboard's background. The dashboard's body has a different color than its header:

CleanShot 2568-10-29 at 03 34 59@2x

### How to verify

Basic mapping

1. Go to the embed wizard
2. Set background color to a darkish color
3. The dashboard background should be dark, not white

Fallback case

1. Create a theme with `background` set but without `background-secondary`
2. Render a dashboard
3. The dashboard body's background color should be the same as the dashboard's

### Demo

When `background-secondary` is provided (in this case, automatically derived by embed wizard):

CleanShot 2568-10-29 at 02 59 14@2x

When `background-secondary` is not provided, but `background` is provided:

image 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk-bundle/lib/theme/get-embedding-theme.ts [hunk 1]
```diff
@@ -60,9 +60,17 @@ export function getEmbeddingThemeOverride(
   if (theme.colors) {
     override.colors = {};
 
+    const userColors = { ...theme.colors };
+
+    // If `background` is set but `background-secondary` is not,
+    // use the value of `background` as the fallback.
+    if (userColors.background && !userColors["background-secondary"]) {
+      userColors["background-secondary"] = userColors.background;
+    }
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk-bundle/lib/theme/get-embedding-theme.ts]: `background-secondary` defaults to a greyish white color, which does not makes sense when `background` color is customized but `background-secondary` is not set. A sensible default would be to use the same `background` color for both.

Note that we already derived `background-secondary` automatically in embed wizard.

Before:

Image

After:

Image

File: frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts [hunk 2]
```diff
@@ -53,7 +53,7 @@ export const SDK_TO_MAIN_APP_COLORS_MAPPING: Record<
   "text-tertiary": ["text-light", "text-tertiary"],
   background: ["bg-white", "bg-primary", "background"],
   "background-hover": ["bg-light", "background-hover"],
-  "background-secondary": ["bg-medium"],
+  "background-secondary": ["bg-medium", "bg-secondary"],
```
Comment (heypoom) [inline frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts:58]: This is the fix for the actual issue - it adds the missing `background-secondary -> bg-secondary` mapping.

File: frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts
Comment (WiNloSt) [inline frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts]: can you adjust this part to match the current file structure? Currently all colors are located at `frontend/src/metabase/lib/colors/colors.ts`

File: enterprise/frontend/src/embedding-sdk-bundle/lib/theme/get-embedding-theme.ts (hunk 1 above)
Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk-bundle/lib/theme/get-embedding-theme.ts]: I'm not sure I like the approach here. I feel like there should be a way to tell the config that, if a color isn't provided, use a color from a different defined one.

Maybe that's overkill for a start. But I just feel like the relationship between the code that defines a mapping from background-secondary -> bg-secondary and how bg-secondary would fallback to is completely in different places.

**Review by WiNloSt — APPROVED** [review]
While this works, it behaves differently on the embed wizard from before the bug was introduced by https://github.com/metabase/metabase/pull/65084.


#### This PR

Image

#### Before the bug was introduced

Image

Can you consult with @AlessioLaiso to see if it's cool? Otherwise, this looks like a breaking change (since the colors now behave differently).

File: frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts
Comment (heypoom) [reply frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts]: Fixed in https://github.com/metabase/metabase/pull/65116/commits/732d92d46dc6ce425e8bca7998357f00ae4c3ecc

File: enterprise/frontend/src/embedding-sdk-bundle/lib/theme/get-embedding-theme.ts (hunk 1 above)
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk-bundle/lib/theme/get-embedding-theme.ts]: @WiNloSt Good point, I made the fallback a config object now so it lives in the same file as the colors mapping; test still passes. Fixed in https://github.com/metabase/metabase/pull/65116/commits/71fa282a444551e5cda89d8ac682cbf0b4c0ac7a

Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk-bundle/lib/theme/get-embedding-theme.ts]: That looks good. Yeah, my intent wasn't that the approach wasn't good, but rather the how the logic between color mapping and fallback logic being co-located is more preferable 👍
