### PR TITLE
Fix duplicate "user joined" activity feed entries

### LINKED ISSUE #2448: activity feed creating duplicate "user joined" events
this is happening in v0.16.1

took a look into this and it's caused by the matching logic for a first session, which effectively breaks if the user logs out because when a logout occurs we actively delete the session from the db.

### PR DESCRIPTION
**Pull request by agilliland**
fixes #2448 by reworking the logic for determining when it's a users first login.  we no longer lookup the first session for the user because it's possible they logged out and deleted their only session, then logged in to create their "first" session.  we now use the :last_login timestamp on the User record, which is more consistent and accurate.

### CODE REVIEW

File: src/metabase/models/session.clj [hunk 1]
```diff
@@ -22,4 +22,4 @@
   "Retrieves the first Session `:id` for a given user (if available), or nil otherwise."
   [user-id]
   {:pre [(integer? user-id)]}
-  (sel :one :id Session, :user_id user-id, (k/order :created_at :ASC)))
+  (db/sel :one :field [Session :id], :user_id user-id, (k/order :created_at :ASC)))
```
Comment (camsaul) [inline src/metabase/models/session.clj]: why?

File: test_resources/log4j.properties [hunk 2]
```diff
@@ -16,3 +16,4 @@ log4j.appender.file.layout.ConversionPattern=%d [%t] %-5p%c - %m%n
 
 # customizations to logging by package
 log4j.logger.metabase=INFO
+log4j.logger.metabase.sync-database=WARN
```
Comment (camsaul) [inline test_resources/log4j.properties]: why?

File: test/metabase/models/session_test.clj [hunk 3]
```diff
@@ -16,7 +16,10 @@
     (k/insert Session
               (k/values [{:id         "the-greatest-day-ever"
                           :user_id    user-id
-                          :created_at (metabase.util/->Timestamp "1980-10-19")}
+                          :created_at (metabase.util/->Timestamp "1980-10-19T05:05:05.000Z")}
+                         {:id         "even-more-greatness"
+                          :user_id    user-id
+                          :created_at (metabase.util/->Timestamp "1980-10-19T05:08:05.000Z")}
```
Comment (camsaul) [inline test/metabase/models/session_test.clj]: you shouldn't do this, refer to a namespace like `metabase.util` without `:require`-ing it. It might not be loaded yet so this makes the code implicitly dependent on being ran after some other namespace loaded `metabase.util`.

File: src/metabase/models/session.clj (hunk 1 above)
Comment (agilliland) [inline src/metabase/models/session.clj]: I prefer the second syntax.  it's more clear.

File: test/metabase/models/session_test.clj (hunk 3 above)
Comment (agilliland) [inline test/metabase/models/session_test.clj]: 👍
