### PR TITLE
Dashboard action warning text

### LINKED ISSUE #29365: Dashboard action expecting single value warning text cut off
**Describe the bug**
When you add an action to a dashboard that has a parameter that supports multiple values, the warning message in the action button is cut off for certain action button sizes.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create a model based on Products
2. Create an action that has a **Text** parameter
3. Create a dashboard
4. Add **Text** > **Is** parameter, make sure **Multiple values** is selected (should be the default value), click **Done**
5. Click **Add action button** icon > **Pick an action**, choose the action you just created.
6. For the text action parameter choose the dashboard parameter you just added. Click **Done**
7. Resize the action button to 4x3. And click the dashboard parameter
image
8. Click **Done**, resize the button to 4x4. And click the dashboard parameter again. You should see that there is more info, but it was hidden when the action button size is too small.
image
9. Resize the action button to 1x3. And click the dashboard parameter again. You will see the icon with popover, however, the warning `This field only accepts a single value because it's used in a SQL query.` isn't there.
image

**Expected behavior**
The warning `This field only accepts a single value because it's used in a SQL query.` should be visible at all time either in the popover, or in the action button body itself, and shouldn't be cut off like that.

**Screenshots/videos**
included in the repro

**Information about your Metabase Installation:**
commit hash: `master` @ `5eecb79cd516d99812c6b0ee4a8c69e51c14035c` 
**Severity**
Just annoying

### PR DESCRIPTION
**Pull request by deniskaber**
closes #29365
Closes:
https://github.com/metabase/metabase/issues/29365 / UXW-119
https://github.com/metabase/metabase/issues/25835 / UXW-124
https://github.com/metabase/metabase/issues/58231 / UXW-304

### Description

Fix 3 small issues.
UXW-119 - Update action dashcard parameters mapping message - it should fit card size. Content that doesn't fit should go into a tooltip.

Demo - 

https://github.com/user-attachments/assets/541dbd8a-a089-4354-a8b6-c33b232e957d

UXW-124 - Add gap between multiple parameters.

UXW-304 - Fix link button logic for collection menu + e2e test

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/collections/components/CollectionHeader/CollectionPermissions.tsx [hunk 1]
```diff
@@ -21,6 +24,10 @@ export const CollectionPermissions = ({
         aria-label={t`Edit permissions`}
         tooltipLabel={t`Edit permissions`}
         tooltipPosition="bottom"
+        onClick={() => {
```
Comment (deniskaber) [inline frontend/src/metabase/collections/components/CollectionHeader/CollectionPermissions.tsx:27]: Fix for 58231 + e2e test

File: frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardParameterMapper.jsx [hunk 2]
```diff
@@ -38,6 +38,7 @@ export const DashCardParameterMapper = ({
       justify="space-around"
       maw="100%"
       m={compact ? undefined : "0 2rem"}
+      gap="sm"
```
Comment (deniskaber) [inline frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardParameterMapper.jsx:41]: Fix for UXW-124

**Review by alxnddr — APPROVED** [review]
Looks good! Would be nice to be splitting more or less distant from each other fixes into separate PRs
