### PR TITLE
68048 missing bar label

### LINKED ISSUE #68048: X-axis labels missing in subscription emails for categorical bar charts at some widths
### Describe the bug
When sending dashboard subscription emails containing bar charts with categorical x-axis data, the x-axis labels are sometimes completely hidden in the email. The bar value labels display correctly, but there is no way to identify what each bar represents because the category names are not shown. There is no workaround for this to display the labels in the email body when the email is sent to someone external who does not have a login to Metabase instance, so they can't see what the values are unless the sender includes an attachment but that defeats the purpose of the chart.

This appears to be related to #62831 but is distinct: #62831 covers ordinal scale x-axes, while this bug affects categorical (non-ordinal) data. This is more severe since ordinal x-axis can be inferred (i.e. what's between 2025-01-07 and 2025-01-09 vs what's between Category X and Category Y).

Image

### To Reproduce
1. Create a native SQL question using the Sample Database:
```sql
SELECT * FROM (
    VALUES
    ('Alnyba', 390000),
    ('Bvsieginlri', 500000),
    ('Cflonta', 700000),
    ('Dgamruh', 50000),
    ('Eitstrugb', 130000),
    ('Farnotcs', 107000),
    ('Gkro', 750000)
) AS Data(LABEL, amount);
```
2. Change visualization to a bar chart
3. Save to a dashboard with full width and a height of 6 blocks
4. Create a subscription and send the email
5. Observe that x-axis labels (Alnyba, Bvsieginlri, etc.) are completely missing in the email

NOTE: the length of the label has an effect as well, when I tried sending with longer labels, it automatically rotated as I would expect instead of just having a random label or two disappearing.

### Expected behavior
X-axis category labels should be visible in subscription emails, allowing recipients to identify what each bar represents. They should be rotated

### Logs
N/A - This is a static-viz rendering issue in subscription emails, not an application error.

### Information about your Metabase installation
Reproduced on:
- v0.57.8
- master branch as of commit bff5dfb

### Severity
Blocking some users - Content of Subscription emails are essentially unusable for categorical bar charts because recipients cannot identify what the bars represent.

### Additional context
- Related issue: #62831 (ordinal scale x-axis hiding) - this is a separate but related issue for categorical data

### PR DESCRIPTION
**Pull request by deniskaber**
Closes https://github.com/metabase/metabase/issues/68048 , https://github.com/metabase/metabase/issues/68049

### Description

This fixes issue with missing labels on small screen sizes (and emails). Issue happened because we measured label actual size incorrectly - without extra spaces we add on latter stages of chart rendering.

### How to verify

Follow steps from https://github.com/metabase/metabase/issues/68048. 
Use window width of 940px.

### Demo

https://github.com/user-attachments/assets/3f4408a2-d442-479a-839a-57603d83f5ef

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts [hunk 1]
```diff
@@ -641,18 +642,20 @@ const areHorizontalXAxisTicksOverlapping = (
       return;
     }
     const prevDatum = dataset[index - 1];
-    const leftTickWidth = measureText(
-      formatter(datum[X_AXIS_DATA_KEY]),
+    const rightTickWidth = measureText(
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts:645]: Nice catch!

**Review by alxnddr — APPROVED** [review]
