### PR TITLE
Fix - Values from the returned rows not present in the visualization are interpolable in the URL but don't have values

### LINKED ISSUE #46318: Click behavior | Custom destination | URL interpolation - Values from the returned rows not present in the visualization are interpolable in the URL but don't have values
### Describe the bug

When creating a custom click behaviour to open a link from a visualization, we are prompted to use any of the query columns in the URL interpolation.

However, using a value not used in the visualization itself ends up with an empty value, meaning that we cannot really use it in the URL.

### To Reproduce

1. Create a new Dashboard
2. Add a new SQL question to that dashboard. To use an an example you can use this query:

<details>

<summary>SQL Query</summary>

```sql
WITH data AS (
    SELECT 
        ('group_1') AS main_group,
        ('sub_group_1') AS sub_group,
        (1) AS value,
    
    UNION ALL
    SELECT 
        ('group_1') AS main_group,
        ('sub_group_1') AS sub_group,
        (77) AS value,
        
    UNION ALL
    SELECT 
        ('group_1') AS main_group,
        ('sub_group_1') AS sub_group,
        (33) AS value,
        
    UNION ALL
    SELECT 
        ('group_1') AS main_group,
        ('sub_group_2') AS sub_group,
        (2) AS value,
    
    UNION ALL
    SELECT 
        ('group_1') AS main_group,
        ('sub_group_2') AS sub_group,
        (66) AS value,
        
    UNION ALL
    SELECT 
        ('group_2') AS main_group,
        ('sub_group_1') AS sub_group,
        (67) AS value,
        
    UNION ALL
    SELECT 
        ('group_2') AS main_group,
        ('sub_group_1') AS sub_group,
        (12) AS value,
    
    UNION ALL
    SELECT 
        ('group_2') AS main_group,
        ('sub_group_2') AS sub_group,
        (44) AS value
    
    UNION ALL
    SELECT 
        ('group_2') AS main_group,
        ('sub_group_2') AS sub_group,
        (8) AS value
)

SELECT
    main_group,
    sub_group,
    SUM(value) AS value_sum,
    CONCAT(main_group, '__', sub_group) AS group_name
FROM DATA
GROUP BY main_group, sub_group;
```

Expected result:

|main_group|sub_group  |value_sum|group_name          |
|----------|-----------|---------|--------------------|
|group_1   |sub_group_1|111      |group_1__sub_group_1|
|group_1   |sub_group_2|68       |group_1__sub_group_2|
|group_2   |sub_group_1|79       |group_2__sub_group_1|
|group_2   |sub_group_2|52       |group_2__sub_group_2|

</details>

3. Set the visualization type to `Row`
4. Configure the visualization like in the following image:
<details>

<summary>Row Visualization Configuration</summary>

Screenshot 2024-07-31 at 10 51 34

Expected result:
Screenshot 2024-07-31 at 10 51 41

</details>

5. Add a custom click behaviour on that dashboard -> question
6. Set it to a Custom desintation and interpolate the value `{{group_name}}`, you can use this as an example: `https://google.com/search?q=data:{{group_name}}`
7. Save the dashboard
8. Click on any of the 4 rows in the dashboard

### Expected behavior

* The expected behaviour would be to arrive at `https://google.com/search?q=data:something`
* The actual behaviour is that we arrive at `https://google.com/search?q=data:` (no value after `data:`)

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Browser: Chrome 127.0.6533.73
- OS: MacOS 14.6 (23G80)
- Databases: BigQuery
- Metabase: SAAS version
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #46318

### How to verify

1. New > SQL query
2. Paste this: `SELECT 'group_1' AS main_group, 'sub_group_1' AS sub_group, 111 AS value_sum, 'group_1__sub_group_1' AS group_name
UNION ALL
SELECT 'group_1', 'sub_group_2', 68, 'group_1__sub_group_2'
UNION ALL
SELECT 'group_2', 'sub_group_1', 79, 'group_2__sub_group_1'
UNION ALL
SELECT 'group_2', 'sub_group_2', 52, 'group_2__sub_group_2';
`
3. Run query
4. Change viz type to "Row"
5. Open viz settings
6. Set Y-Axis to "main_group"
7. Set X-Axis to "value_sum"
8. Click "Add series breakout" and select "sub_group"
    - if you do this step before step 7 you'll hit #49529
10. Save question and add it to dashboard
11. Configure click behavior for this dashcard: custom URL: `https://example.com/?{{group_name}}`
12. Save dashboard
13. Try out click behavior

URL should contain value after `?`.

Related PR: #26547

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts [hunk 1]
```diff
@@ -66,8 +70,7 @@ const getColumnData = (columns: ColumnDescriptor[], datum: GroupedDatum) => {
 
         value = formatNullable(metricSum);
       } else {
-        const distinctValues = new Set(datum.rawRows.map(row => row[index]));
-        value = distinctValues.size === 1 ? datum.rawRows[0][index] : null;
+        value = datum.rawRows[seriesIndex][index];
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts:73]: I don't understand the purpose of counting unique values here. It's been introduced in #26547.
@alxnddr do you remember what was it for?

**Review by romeovs — APPROVED** [review]

File: frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts (hunk 1 above)
Comment (alxnddr) [reply frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts:73]: @kamilmielnik it was there to prevent the invalid behaivor. 
Let's add another row to the query:
```
SELECT
  'group_2',
  'sub_group_1',
  400,
  'something else'
```

Now the bar with `Y=group_2` and `Breakout=sub_group_1` represents two rows where `group_name` is `{ "group_2_sub_group_1", "something else" }` but with the fix applied we would extrapolate the URL with `group_2_sub_group_1` which is not correct.
However, I'm not agains this fix because it sort of makes the behavior consistent to other charts with breakouts which historically has been like this and even covered with specs AFAIR. 
Let's ask for @cdeweyx opinion, maybe it would be better to implement the correct behavior right away.

**Review by alxnddr — APPROVED** [review]
