### PR TITLE
Don't duplicate uploads in admin page

### LINKED ISSUE #60625: Upload entries are duplicated in Admin Settings / Uploads
### Describe the bug

Each uploaded file appear twice:
Image

### To Reproduce

Upload any CSV file and go to Admin Settings / Uploads.

### Expected behavior

_No response_

### Logs

`/api/ee/upload-management/tables` response:

```
[
    {
        "description": null,
        "entity_type": "entity/GenericTable",
        "view_count": 2,
        "schema": "db_014efc122b3f41e1",
        "database_require_filter": null,
        "show_in_getting_started": false,
        "name": "upload_dupe_20250708104729",
        "caveats": null,
        "updated_at": "2025-07-08T10:47:30.121701Z",
        "active": true,
        "id": 4227,
        "db_id": 100,
        "visibility_type": null,
        "field_order": "database",
        "is_upload": true,
        "initial_sync_status": "complete",
        "display_name": "Dupe",
        "created_at": "2025-07-08T10:47:29.736818Z",
        "estimated_row_count": null,
        "points_of_interest": null
    },
    {
        "description": null,
        "entity_type": "entity/GenericTable",
        "view_count": 0,
        "schema": "db_014efc122b3f41e1",
        "database_require_filter": null,
        "show_in_getting_started": false,
        "name": "upload_dupe_v55_20250708110459",
        "caveats": null,
        "updated_at": "2025-07-08T11:05:00.396118Z",
        "active": true,
        "id": 4228,
        "db_id": 100,
        "visibility_type": null,
        "field_order": "database",
        "is_upload": true,
        "initial_sync_status": "complete",
        "display_name": "Dupe.v55",
        "created_at": "2025-07-08T11:04:59.645727Z",
        "estimated_row_count": null,
        "points_of_interest": null
    },
    {
        "description": null,
        "entity_type": "entity/GenericTable",
        "view_count": 2,
        "schema": "db_014efc122b3f41e1",
        "database_require_filter": null,
        "show_in_getting_started": false,
        "name": "upload_dupe_20250708104729",
        "caveats": null,
        "updated_at": "2025-07-08T10:47:30.121701Z",
        "active": true,
        "id": 4227,
        "db_id": 100,
        "visibility_type": null,
        "field_order": "database",
        "is_upload": true,
        "initial_sync_status": "complete",
        "display_name": "Dupe",
        "created_at": "2025-07-08T10:47:29.736818Z",
        "estimated_row_count": null,
        "points_of_interest": null
    },
    {
        "description": null,
        "entity_type": "entity/GenericTable",
        "view_count": 0,
        "schema": "db_014efc122b3f41e1",
        "database_require_filter": null,
        "show_in_getting_started": false,
        "name": "upload_dupe_v55_20250708110459",
        "caveats": null,
        "updated_at": "2025-07-08T11:05:00.396118Z",
        "active": true,
        "id": 4228,
        "db_id": 100,
        "visibility_type": null,
        "field_order": "database",
        "is_upload": true,
        "initial_sync_status": "complete",
        "display_name": "Dupe.v55",
        "created_at": "2025-07-08T11:04:59.645727Z",
        "estimated_row_count": null,
        "points_of_interest": null
    }
]
```

### Information about your Metabase installation

```JSON
Seen on 1.54.12 and 1.55.6.2 .
```

### Severity

Reported by an affected customer

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nvoxland**
closes #60625
### Description

Don't double-query for uploaded entries

Also, make sure results are still sorted in output despite two queries

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/upload_management/api.clj [hunk 1]
```diff
@@ -26,11 +26,13 @@
 (api.macros/defendpoint :get "/tables"
   "Get all `Tables` visible to the current user which were created by uploading a file."
   []
-  (as-> (t2/select :model/Table, :active true, :is_upload true, {:order-by [[:name :asc]]}) tables
+  (as-> (t2/select :model/Table, :active true, :is_upload true) tables
         ;; See https://github.com/metabase/metabase/issues/41023
     (concat tables (attached-dwh-tables))
     (map #(update % :schema str) tables)
-    (filterv mi/can-read? tables)))
+    (filter mi/can-read? tables)
```
Comment (edpaget) [inline enterprise/backend/src/metabase_enterprise/upload_management/api.clj:33]: should we filter readable tables in sql rather than using a filter after read here

File: enterprise/backend/src/metabase_enterprise/upload_management/api.clj [hunk 2]
```diff
@@ -26,11 +26,13 @@
...
+    (sort-by :name tables)
```
Comment (edpaget) [inline enterprise/backend/src/metabase_enterprise/upload_management/api.clj]: why change the sort-by to outside sql?

Comment (nvoxland) [reply enterprise/backend/src/metabase_enterprise/upload_management/api.clj]: Because we're doing a concat of the attached-dwh-tables so the final list isn't necessarily sorted.

I brought the original sort back for a bit better performance, and added a comment

File: enterprise/backend/src/metabase_enterprise/upload_management/api.clj (hunk 1 above)
Comment (nvoxland) [reply enterprise/backend/src/metabase_enterprise/upload_management/api.clj:33]: The can-read? logic is a relatively complex, visible-filter-clause doesn't capture it all, and I don't think there is a version that does. The number of tables should be pretty small, so I don't think it's worth adding for this bugfix

**Review by edpaget — APPROVED** [review]
