### PR TITLE
Fix date range pickers

### LINKED ISSUE #6952: Dashboard Filters - Unable to select date range spanning over multiple years
I'm trying to add a date range filter to my dashboard that by default would start since Sept 1 2017, however I'm unable to set it. When I select a range within a year (e.g. Jan 1 2018 - Feb 2 2018) it works but when it crosses to another year (be it before or after) (e.g. Dec 30 2017 - Jan 2 2018), it fails to set the date range, it resets it.

-------

Your browser and the version: Chrome 63.0.3239.132
Your operating system: Mac OS X Sierra 10.12.6
Your databases: Postgres
Metabase version:  0.28.1
Metabase hosting environment: Docker
Metabase internal database: H2 (default)

**Repeatable steps to reproduce the issue**
1. Create a dashboard
2. Add a filter to the dashboard
3. Try to set a date range that spans at least two years (e.g. Dec 30 2017 - Jan 3 2018)

### LINKED ISSUE #7035: DateFilter - Between doesn't work properly
Hi
We are experience some issues when using a DateFilter variable with between mode.

As you can see in the video, after you choose the start date, if you wanna to change the month for End Date, you only can go over one step more after it crashes and date picker shakes.

Using Windows 10 + Chrome + Metabase v0.28.1 + Database=Mysql

https://share.vidyard.com/watch/Tju6HFvTvjeuJaCbg7J6pE

Reproduce:

1.  Create a new variable, and choose a Field Filter type, then DateFilter as widget type
image

1. Using the filter, change to "Between" mode.
image

1. Try to select October 1st 2017 to February, 25th 2018.  Start Date = 2017-10-01 and then click to next month arrow until 2018-February
image

Then you cannnot do that, because after two months the date picker shakes

### LINKED ISSUE #7036: DateFilter - Date Range doesn't allow to select date ranges properly
- Your browser and the version: Chrome Versión 64.0.3282.186 (Build oficial) (64 bits)
- Your operating system: Windows 10
- Your databases: Mysql
- Metabase version: v0.28.1

When trying to select a date range for for example 2017-10-01 to 2017-12-25 , the variable DateFilter - Date Range doesn't allow it.

https://share.vidyard.com/watch/KtGyGUWWN9sRdWBAaQ1gA1

- *Repeatable steps to reproduce the issue*

1. Define a new DateFilter variable and use Date Range as widget
image

1. Go to any month of previous year, like 2017-October and set any date as Start Date
image

1. Then try to set any date of the next month as End Date. 

The result is the range is reset and you have just started from the begining selecting start date instead of EndDate.

-------

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #6952
Resolves #7035
Resolves #7036

### CODE REVIEW

**Comment by tlrobinson** [comment]
@kurbar @jescorotero @bugo99iot If you could pull this branch and verify it resolves all of your issues that would be fantastic. Thanks.

**Comment by salsakran** [comment]
This seems to fix things, but I get weird highlighting as I mentioned off-channel.

I'm ok with merging as the highlighting is cosmetic and this clears some really annoying bugs

**Review by salsakran — APPROVED** [review]

File: frontend/src/metabase/parameters/components/widgets/DateRangeWidget.jsx [hunk 1]
```diff
@@ -1,38 +1,44 @@
 import React, { Component } from "react";
+import PropTypes from "prop-types";
```
Comment (kdoh) [inline frontend/src/metabase/parameters/components/widgets/DateRangeWidget.jsx]: Would it make sense to convert this stuff to flow here instead of continuing to use PropTypes?

**Review by kdoh — APPROVED** [review]
Code looks good, left one tiny comment. Thanks for the tests 👍

**Comment by kurbar** [comment]
@tlrobinson I checked the date range picker and it works perfectly now with crossing year boundaries. I will also test it out on a database with variables later today. Thank-you for the fix.

**Comment by dhnguyen92** [comment]
Can you merge this pull request? Those bugs should be fixed ASAP. Thank you.
