### PR TITLE
Asynchronously fix missing, stale, or orphaned Query Analysis

### LINKED ISSUE #45464: Implement SQL Analysis Sweeper worker
Add an always running background thread which works its way over all cards with missing or stale analysis, and synchronously offers them to the SQL Analysis queue.

There should be a feature flag controlling whether we start this worker or not.

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes https://github.com/metabase/metabase/issues/45464

### Description

This beefs up the old backfill task, so that it will fix stale analysis on start up, and clean up trash. The job also runs continuously now.

It was already upgraded to use back pressure from the analyzer worker.

### Manual testing

1. Check that we fix stale analysis on start-up.
  - Have some cards with more than one query field.
  - Stop the server.
  - Delete some of the query fields, but leaving at least 1 per card.
  - Start the server.
  - Verify that the gaps are filled.
2. Check that we fill in the gaps for running instance.
  - Have some cards with analysis.
  - Delete all analysis for some cards.
  - Wait up to 4 hours (sorry - you're welcome to tweak the config 😉)
  - Verify that the analysis is present.
 3. Check that we delete orphan records.
  - Have some cards with analysis.
  - Archive some cards.
  - Wait up to 4 hours (ditto)
  - Verity that the analysis is *no longer* present.

### CODE REVIEW

File: src/metabase/task/sweep_query_analysis.clj [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+                  (jobs/of-type SweepQueryAnalysis)
+                  (jobs/with-identity (jobs/key "metabase.task.backfill-query-fields.job"))
+                  (jobs/store-durably))
+        trigger (triggers/build
+                  (triggers/with-identity (triggers/key "metabase.task.backfill-query-fields.trigger"))
+                  (triggers/start-now)
+                  (triggers/with-schedule
+                   (cron/schedule
+                    (cron/cron-schedule
+                     ;; run every 4 hours at a random minute:
```
Comment (crisptrutski) [inline src/metabase/task/sweep_query_analysis.clj:87]: Randomness is generally a good idea, but in this case it's extra useful as it'll de-correlate runs on different instances, so they complement each other more effectively.

File: src/metabase/task/sweep_query_analysis.clj [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+   (sweep-query-analysis-loop! (not @has-run?))
+   (reset! has-run? true))
+  ([first-time?]
+   (sweep-query-analysis-loop! first-time? query-analysis/analyze-sync!))
+  ([first-time? analyze-fn]
+   ;; prioritize cards that are missing analysis
+   (analyze-cards-without-query-fields! analyze-fn)
+
+   ;; we run through all the existing analysis on our first run, as it may be stale due to an old macaw version, etc.
+   (when first-time?
```
Comment (crisptrutski) [inline src/metabase/task/sweep_query_analysis.clj:63]: I'm on the fence about this. The problem is that if we drop an event, we're left with stale analysis until the instance restarts.

File: src/metabase/task/sweep_query_analysis.clj [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+      (+ running-count (count ids))))
+   0
+   (t2/reducible-select [:model/QueryField :id]
+                        {:join  [[:report_card :c] [:= :c.id :query_field.card_id]]
+                         :where [:or
+                                 [:= :c.id nil]
+                                 :c.archived]})))
+
+(def ^:private has-run?
+  "Has the sweeper been run before?"
```
Comment (crisptrutski) [inline src/metabase/task/sweep_query_analysis.clj:49]: I should clarify this - "has it run before in the lifetime of this instance"

File: src/metabase/task/sweep_query_analysis.clj [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+   (org.quartz DisallowConcurrentExecution)))
+
+(set! *warn-on-reflection* true)
+
+(defn- analyze-cards-without-query-fields!
+  ([]
+   (analyze-cards-without-query-fields! query-analysis/analyze-sync!))
+  ([analyze-fn]
+   (let [cards (t2/reducible-select [:model/Card :id]
+                                    {:left-join [[:query_field :f] [:= :f.card_id :report_card.id]]
```
Comment (tsmacdonald) [inline src/metabase/task/sweep_query_analysis.clj:19]: nitpick, but I've been religiously using `qf` as the alias since more often than not `Field` gets joined in too and that would be `f`.

File: src/metabase/task/sweep_query_analysis.clj (hunk 2 above)
Comment (tsmacdonald) [reply src/metabase/task/sweep_query_analysis.clj:63]: without the timestamp column is there a reasonable way around it?

File: test/metabase/task/setup/query_analysis_setup.clj [hunk 5]
```diff
@@ -36,31 +33,17 @@
...
-  (queue/clear! @#'query-analysis/queue)
-  (.-queued-set @#'query-analysis/queue)
-  (.peek (.-async-queue @#'query-analysis/queue))
-  (.peek (.-sync-queue @#'query-analysis/queue)))
+(defmacro with-test-setup!
+  "Set up the data required to test the Query Analysis related tasks"
+  [& body]
+  `(do-with-test-setup!
+    (mt/with-anaphora [c1 c2 c3 c4 arch]
+                      ~@body)))
```
Comment (tsmacdonald) [inline test/metabase/task/setup/query_analysis_setup.clj:49]: ah whoops

https://github.com/metabase/metabase/pull/45716

File: test/metabase/task/sweep_query_analysis_test.clj [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+  (setup/with-test-setup! [c1 c2 c3 c4]
+    (testing "There is at least one card with existing analysis"
+      (is (pos? (t2/count :model/QueryField :card_id (:id c3)))))
+    (let [expected-ids (into #{} (map :id) [c1 c2 c4])
+          not-expected (into #{} (map :id) [c3 arch])
+          queued-ids   (queued-card-ids #'sweeper/analyze-cards-without-query-fields!)]
+      (testing "The expected cards were all sent to the analyzer"
+        (is (= expected-ids (set/intersection expected-ids queued-ids))))
+      (testing "The card with existing analysis was not sent to the analyzer again"
+        (is (empty? (set/intersection not-expected queued-ids)))))))
```
Comment (tsmacdonald) [inline test/metabase/task/sweep_query_analysis_test.clj:26]: very clear tests, thank you

File: test/metabase/task/sweep_query_analysis_test.clj [hunk 7]
```diff
@@ -0,0 +1,60 @@
...
+
+      (testing "The task deletes at least one record"
+        (is (pos? (#'sweeper/delete-orphan-analysis!))))
+      (testing "There is no analysis left after the task is run"
+        (is (zero? (t2/count :model/QueryField :card_id card-id))))
+      (testing "No cards were harmed in the process"
+        (is (= 5 (t2/count :model/Card :id [:in (mapv :id [c1 c2 c3 c4 arch])])))))))
+
+(comment
+  (set! *warn-on-reflection* true)
```
Comment (tsmacdonald) [inline test/metabase/task/sweep_query_analysis_test.clj:56]: surely you want this at the top of the ns for real?

File: src/metabase/task/sweep_query_analysis.clj [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+   (fn
+     ([final-count] final-count)
+     ([running-count ids]
+      (t2/delete! :model/QueryField :id [:in ids])
+      (+ running-count (count ids))))
+   0
+   (t2/reducible-select [:model/QueryField :id]
+                        {:join  [[:report_card :c] [:= :c.id :query_field.card_id]]
+                         :where [:or
+                                 [:= :c.id nil]
```
Comment (tsmacdonald) [inline src/metabase/task/sweep_query_analysis.clj:45]: When would `c.id` ever be nil?

File: src/metabase/task/sweep_query_analysis.clj [hunk 9]
```diff
@@ -0,0 +1,90 @@
+(ns metabase.task.sweep-query-analysis
```
Comment (tsmacdonald) [inline src/metabase/task/sweep_query_analysis.clj:1]: <putting on my hat as the local Marginalia gremlin>

It'd be nice to have a ns-level docstring that summarized what the job does, how you define stale and orphan cards, etc.

**Review by tsmacdonald — APPROVED** [review]
Me gusta, just a couple non-blocking comments

File: test/metabase/task/setup/query_analysis_setup.clj (hunk 5 above)
Comment (crisptrutski) [reply test/metabase/task/setup/query_analysis_setup.clj:49]: I was shamefully using IntelliJ, so I'll also need to fix it in my um settings.jar (snazzy)

File: test/metabase/task/sweep_query_analysis_test.clj (hunk 7 above)
Comment (crisptrutski) [reply test/metabase/task/sweep_query_analysis_test.clj:56]: Only needed for the stuff in this rich comment 🤷

File: src/metabase/task/sweep_query_analysis.clj (hunk 8 above)
Comment (crisptrutski) [reply src/metabase/task/sweep_query_analysis.clj:45]: I guess there are cascading deletes and I overthought this. Will simplify.

File: src/metabase/task/sweep_query_analysis.clj (hunk 9 above)
Comment (crisptrutski) [reply src/metabase/task/sweep_query_analysis.clj:1]: Oh man, you're right but I'm too eager right now and will put on my technical writing hat [tomorrow](https://github.com/metabase/metabase/issues/45720).

File: src/metabase/task/sweep_query_analysis.clj (hunk 2 above)
Comment (crisptrutski) [reply src/metabase/task/sweep_query_analysis.clj:63]: Well, the alternative is to keep looping through everything, each time. That makes me uneasy.

**Comment by crisptrutski** [comment]
@tsmacdonald updated the test to use a test encapsulated queue, and I haven't been able to catch it flaking again. 

I like having explicit methods that take arguments instead of using globals, but I also like hiding the inner queue from other modules, so this is somewhere in between.

I'm not convinced I fixed the issue though, and worry that there could be some Heisenbug-ishness around whether I'm logging things out.
