### PR TITLE
Fix errors from disallowed characters in BigQuery custom expression names

### LINKED ISSUE #17918: BigQuery Custom Column difficult to use because of name restrictions
**Describe the bug**
BigQuery Custom Column difficult to use because of name restrictions.

**To Reproduce**
1. Custom question > **BigQuery** Sample Dataset > Products
2. Custom Column `1 + 1` as "My custom column" - errors with `Invalid field name "My custom column". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 300 characters long`
image

<details><summary>Full stacktrace</summary>

```
2021-09-16 11:39:25,034 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 43,
 :started_at #t "2021-09-16T11:39:22.612575+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class com.google.cloud.bigquery.BigQueryException,
   :error
   "Invalid field name \"My custom column\". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 300 characters long.",
   :stacktrace
   ["com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)"
    "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:628)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1348)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1343)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
    "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
    "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
    "com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1342)"
    "com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1326)"
    "com.google.cloud.bigquery.Job$1.call(Job.java:334)"
    "com.google.cloud.bigquery.Job$1.call(Job.java:331)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
    "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
    "com.google.cloud.RetryHelper.poll(RetryHelper.java:64)"
    "com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:330)"
    "com.google.cloud.bigquery.Job.getQueryResults(Job.java:291)"
    "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1242)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:195)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:183)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:203)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:201)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__70120.invoke(bigquery_cloud_sdk.clj:254)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:256)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:249)"
    "driver.bigquery_cloud_sdk$fn__70125.invokeStatic(bigquery_cloud_sdk.clj:276)"
    "driver.bigquery_cloud_sdk$fn__70125.invoke(bigquery_cloud_sdk.clj:267)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49029.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__49518.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__47416.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__49892.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__50885.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__50929.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49088.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39208.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__43639.invoke(annotate.clj:615)"
    "query_processor.middleware.permissions$check_query_permissions$fn__45571.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__50069.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45969.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__45907.invoke(visualization_settings.clj:57)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47014.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__50655.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__50191.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47033.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__50243.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46405.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__45880.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__39108.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45214.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__49443.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__49741.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47401.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__46782.invoke(add_source_metadata.clj:123)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__49991.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48332.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45195.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48006.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45268.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__51313.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__47785.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50258.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49752$fn__49756.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49752.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45818.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__46006$fn__46007.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46006.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50041.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50048.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47731.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49014.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__47749.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50027.invoke(process_userland_query.clj:138)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__50338.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___42459$thunk__42460.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___42459.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___42468$fn__42471.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___42468.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
    "query_processor$fn__51361$process_query_and_save_execution_BANG___51370$fn__51373.invoke(query_processor.clj:253)"
    "query_processor$fn__51361$process_query_and_save_execution_BANG___51370.invoke(query_processor.clj:245)"
    "query_processor$fn__51405$process_query_and_save_with_max_results_constraints_BANG___51414$fn__51417.invoke(query_processor.clj:265)"
    "query_processor$fn__51405$process_query_and_save_with_max_results_constraints_BANG___51414.invoke(query_processor.clj:258)"
    "api.dataset$run_query_async$fn__57530.invoke(dataset.clj:63)"
    "query_processor.streaming$streaming_response_STAR_$fn__38017$fn__38018.invoke(streaming.clj:140)"
    "query_processor.streaming$streaming_response_STAR_$fn__38017.invoke(streaming.clj:139)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$fn__25207.invoke(streaming_response.clj:84)"]}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:197)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:183)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:203)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:201)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__70120.invoke(bigquery_cloud_sdk.clj:254)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:256)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:249)"
    "driver.bigquery_cloud_sdk$fn__70125.invokeStatic(bigquery_cloud_sdk.clj:276)"
    "driver.bigquery_cloud_sdk$fn__70125.invoke(bigquery_cloud_sdk.clj:267)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49029.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__49518.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__47416.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__49892.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__50885.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__50929.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49088.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39208.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__43639.invoke(annotate.clj:615)"
    "query_processor.middleware.permissions$check_query_permissions$fn__45571.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__50069.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45969.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__45907.invoke(visualization_settings.clj:57)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47014.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__50655.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__50191.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47033.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__50243.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46405.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__45880.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__39108.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45214.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__49443.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__49741.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47401.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__46782.invoke(add_source_metadata.clj:123)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__49991.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48332.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45195.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48006.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45268.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__51313.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__47785.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50258.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49752$fn__49756.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49752.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45818.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__46006$fn__46007.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46006.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50041.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50048.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47731.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49014.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__47749.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50027.invoke(process_userland_query.clj:138)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__50338.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___42459$thunk__42460.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___42459.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___42468$fn__42471.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___42468.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
    "query_processor$fn__51361$process_query_and_save_execution_BANG___51370$fn__51373.invoke(query_processor.clj:253)"
    "query_processor$fn__51361$process_query_and_save_execution_BANG___51370.invoke(query_processor.clj:245)"
    "query_processor$fn__51405$process_query_and_save_with_max_results_constraints_BANG___51414$fn__51417.invoke(query_processor.clj:265)"
    "query_processor$fn__51405$process_query_and_save_with_max_results_constraints_BANG___51414.invoke(query_processor.clj:258)"
    "api.dataset$run_query_async$fn__57530.invoke(dataset.clj:63)"
    "query_processor.streaming$streaming_response_STAR_$fn__38017$fn__38018.invoke(streaming.clj:140)"
    "query_processor.streaming$streaming_response_STAR_$fn__38017.invoke(streaming.clj:139)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$fn__25207.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: 3fdecae74887c839141862726eb38c81648b10e6d90cc2bd88409ffecb010d62\nSELECT `source`.`id` AS `id`, `source`.`ean` AS `ean`, `source`.`title` AS `title`, `source`.`category` AS `category`, `source`.`vendor` AS `vendor`, `source`.`price` AS `price`, `source`.`rating` AS `rating`, `source`.`created_at` AS `created_at`, `source`.`My custom column` AS `My custom column` FROM (SELECT `metabase-bigquery-driver.v6_sample_dataset.products`.`id` AS `id`, `metabase-bigquery-driver.v6_sample_dataset.products`.`ean` AS `ean`, `metabase-bigquery-driver.v6_sample_dataset.products`.`title` AS `title`, `metabase-bigquery-driver.v6_sample_dataset.products`.`category` AS `category`, `metabase-bigquery-driver.v6_sample_dataset.products`.`vendor` AS `vendor`, `metabase-bigquery-driver.v6_sample_dataset.products`.`price` AS `price`, `metabase-bigquery-driver.v6_sample_dataset.products`.`rating` AS `rating`, `metabase-bigquery-driver.v6_sample_dataset.products`.`created_at` AS `created_at`, (1 + 1) AS `My custom column` FROM `metabase-bigquery-driver.v6_sample_dataset.products`) `source` LIMIT 10",
    :parameters nil}}],
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :query {:source-table 6177, :expressions {:My custom column ["+" 1 1]}, :limit 10},
  :database 43,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT `source`.`id` AS `id`, `source`.`ean` AS `ean`, `source`.`title` AS `title`, `source`.`category` AS `category`, `source`.`vendor` AS `vendor`, `source`.`price` AS `price`, `source`.`rating` AS `rating`, `source`.`created_at` AS `created_at`, `source`.`My custom column` AS `My custom column` FROM (SELECT `metabase-bigquery-driver.v6_sample_dataset.products`.`id` AS `id`, `metabase-bigquery-driver.v6_sample_dataset.products`.`ean` AS `ean`, `metabase-bigquery-driver.v6_sample_dataset.products`.`title` AS `title`, `metabase-bigquery-driver.v6_sample_dataset.products`.`category` AS `category`, `metabase-bigquery-driver.v6_sample_dataset.products`.`vendor` AS `vendor`, `metabase-bigquery-driver.v6_sample_dataset.products`.`price` AS `price`, `metabase-bigquery-driver.v6_sample_dataset.products`.`rating` AS `rating`, `metabase-bigquery-driver.v6_sample_dataset.products`.`created_at` AS `created_at`, (1 + 1) AS `My custom column` FROM `metabase-bigquery-driver.v6_sample_dataset.products`) `source` LIMIT 10",
  :params nil,
  :table-name "products",
  :mbql? true},
 :status :failed,
 :class com.google.api.client.googleapis.json.GoogleJsonResponseException,
 :stacktrace
 ["com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)"
  "com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)"
  "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:626)"
  "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1348)"
  "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1343)"
  "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
  "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
  "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
  "com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1342)"
  "com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1326)"
  "com.google.cloud.bigquery.Job$1.call(Job.java:334)"
  "com.google.cloud.bigquery.Job$1.call(Job.java:331)"
  "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
  "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
  "com.google.cloud.RetryHelper.poll(RetryHelper.java:64)"
  "com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:330)"
  "com.google.cloud.bigquery.Job.getQueryResults(Job.java:291)"
  "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1242)"
  "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:195)"
  "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:183)"
  "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:203)"
  "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:201)"
  "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__70120.invoke(bigquery_cloud_sdk.clj:254)"
  "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:256)"
  "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:249)"
  "driver.bigquery_cloud_sdk$fn__70125.invokeStatic(bigquery_cloud_sdk.clj:276)"
  "driver.bigquery_cloud_sdk$fn__70125.invoke(bigquery_cloud_sdk.clj:267)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49029.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__49518.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__47416.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__49892.invoke(cache.clj:204)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__50885.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__50929.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49088.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39208.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__43639.invoke(annotate.clj:615)"
  "query_processor.middleware.permissions$check_query_permissions$fn__45571.invoke(permissions.clj:108)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__50069.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45969.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.visualization_settings$update_viz_settings$fn__45907.invoke(visualization_settings.clj:57)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47014.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__50655.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__50191.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47033.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__50243.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46405.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__45880.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__39108.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__45214.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__49443.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__49741.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47401.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__46782.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__49991.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48332.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45195.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48006.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45268.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__51313.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__47785.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50258.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49752$fn__49756.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49752.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45818.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__46006$fn__46007.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__46006.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50041.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__50048.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47731.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49014.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__47749.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__50027.invoke(process_userland_query.clj:138)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__50338.invoke(catch_exceptions.clj:169)"
  "query_processor.reducible$async_qp$qp_STAR___42459$thunk__42460.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___42459.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___42468$fn__42471.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___42468.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
  "query_processor$fn__51361$process_query_and_save_execution_BANG___51370$fn__51373.invoke(query_processor.clj:253)"
  "query_processor$fn__51361$process_query_and_save_execution_BANG___51370.invoke(query_processor.clj:245)"
  "query_processor$fn__51405$process_query_and_save_with_max_results_constraints_BANG___51414$fn__51417.invoke(query_processor.clj:265)"
  "query_processor$fn__51405$process_query_and_save_with_max_results_constraints_BANG___51414.invoke(query_processor.clj:258)"
  "api.dataset$run_query_async$fn__57530.invoke(dataset.clj:63)"
  "query_processor.streaming$streaming_response_STAR_$fn__38017$fn__38018.invoke(streaming.clj:140)"
  "query_processor.streaming$streaming_response_STAR_$fn__38017.invoke(streaming.clj:139)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__25207.invoke(streaming_response.clj:84)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "400 Bad Request\nGET https://www.googleapis.com/bigquery/v2/projects/metabase-bigquery-driver/queries/0b8fd18f-24fb-4bd8-b530-1eccac828343?location=US&maxResults=0&prettyPrint=false\n{\n  \"code\" : 400,\n  \"errors\" : [ {\n    \"domain\" : \"global\",\n    \"message\" : \"Invalid field name \\\"My custom column\\\". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 300 characters long.\",\n    \"reason\" : \"invalid\"\n  } ],\n  \"message\" : \"Invalid field name \\\"My custom column\\\". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 300 characters long.\",\n  \"status\" : \"INVALID_ARGUMENT\"\n}",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-table 6177,
   :expressions {:My custom column [:+ 1 1]},
   :limit 10,
   :fields
   [[:field 35286 nil]
    [:field 35282 nil]
    [:field 35279 nil]
    [:field 35280 nil]
    [:field 35283 nil]
    [:field 35285 nil]
    [:field 35281 nil]
    [:field 35284 {:temporal-unit :default}]
    [:expression "My custom column"]]},
  :database 43,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash
   [63, -34, -54, -25, 72, -121, -56, 57, 20, 24, 98, 114, 110, -77, -116, -127, 100, -117, 16, -26, -39, 12, -62, -67,
    -120, 64, -97, -2, -53, 1, 13, 98]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

2021-09-16 11:39:25,060 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 2.5 s (18 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (60 total active threads) Queries in flight: 0 (0 queued)
```

</details>

**Expected behavior**
Perhaps something similar to Custom Expression, which automatically translates the name, but perhaps without the suffix?
```
SELECT (1 + 1) AS `My_custom_expression_b7a24d61`
FROM `metabase-bigquery-driver.v6_sample_dataset.products`
```
image

**Information about your Metabase Installation:**
master `b4b5200` using the new BigQuery driver.

**Severity**
The workaround is fairly easy - simply just follow the naming restrictions, almost making this a P3 issue.
But since Pivot Table uses a systematicly-added column called `pivot-grouping`, then fixing the naming would also address #15008 for BigQuery at least, which would be a huge "free" win.

### PR DESCRIPTION
**Pull request by jeff303**
Add `expression-name->alias` multimethod to sql.qp to handle translating the expression name to one that is supported by the driver

Add default impl that is essentially identity

Override for new BigQuery driver to run through the same `->valid-field-identifier` function already added for this purpose

Add test for a custom expression with weird characters

### CODE REVIEW

File: src/metabase/driver/sql/query_processor.clj [hunk 1]
```diff
@@ -274,6 +274,18 @@
 
 (defmethod ->honeysql [:sql :value] [driver [_ value]] (->honeysql driver value))
 
+(defmulti ^String expression-name->alias
+  "Return the String alias that should be used for `expression-name`, to follow the `AS` clause. This is to allow for
+  translating names that particular databases may not allow as identifiers for custom expressions (even when quoted).
+  Defaults to identity (i.e. returns `expression-name` unchanged)."
+  {:added "0.41.0" :arglists '([driver expression-name])}
+  driver/dispatch-on-initialized-driver
+  :hierarchy #'driver/hierarchy)
```
Comment (camsaul) [inline src/metabase/driver/sql/query_processor.clj:283]: I was actually considering adding something like this but more general, called `clause-alias`. Then we  can combine the existing `field->alias` method into it... 

https://github.com/metabase/metabase/pull/16656/files#diff-4fc60f4638cf98beb78946404682d4f857c629a070a01fc2d30112da04347b96R42-R46

A more general method might be better so we don't need to add `aggregation-reference->alias` or other stuff down the line

**Review by camsaul — APPROVED** [review]
This fix works for me 👍

The only thing I think we should think about is seeing whether we could generalize the identifier escaping method since we also have to do it for Field aliases (we already have `field->alias`). Maybe just a general `escape-identifier` method is a better solution? `expression-name->alias` and `field->alias` (once we've gone thru the deprecation cycle) can just be plain functions that call `escape-identifier`. This would also future proof us nicely since we want to support materialized views or other DDL stuff at some point in the long-term future.

LMK if that makes sense, if it's going to be too much of a hassle then it doesn't ruin my life to add the new separate method instead.

**Comment by camsaul** [comment]
One more note: I'm 95% sure we have some sort of `escape-identifier` method of some sort in the driver test extension code... so we could also combine _that_ method into this one. So instead of a net gain of one new method this PR could actually be a net removal of one method

**Comment by flamber** [comment]
May I just say - woohooo :tada: - probably 80 upvotes in #15008 will be very happy!
image

File: src/metabase/driver/sql/query_processor.clj (hunk 1 above)
Comment (jeff303) [reply src/metabase/driver/sql/query_processor.clj:283]: So just to confirm, there is no chance that a driver might want different behavior for translating the name of an aggregation reference versus a field alias?

**Comment by jeff303** [comment]
> One more note: I'm 95% sure we have some sort of `escape-identifier` method of some sort in the driver test extension code... so we could also combine _that_ method into this one. So instead of a net gain of one new method this PR could actually be a net removal of one method

Are you referring to [`qualified-name-components`](https://github.com/metabase/metabase/blob/master/test/metabase/test/data/sql.clj#L35)?

**Comment by camsaul** [comment]
I don't think we need to worry about refactoring all of the test code to use the new `escape-identifier` method and do away with `format-name`, but it's at least worth marking `format-name` as `^:deprecated` and leave a note that we should use `escape-identifier` instead going forward

**Comment by jeff303** [comment]
@camsaul ,

I opted for `translate-identifier`, since I don't think "escaping" is quite accurate here (since you are actually renaming things, to some extent).  At any rate, I'm not sure we can really go to this level yet without figuring some things out.  For instance, H2 was doing `str/upper-case` to the "field or table" names, from its previous `format-name` (now `translate-identifier`).  The problem is applying that to expression aliases breaks a bunch of stuff (you can see the linked failures [here](https://app.circleci.com/pipelines/github/metabase/metabase/22235/workflows/b31e19f0-a83a-4123-8608-aa0044fed719/jobs/978100), for example).

I think we may actually need to keep the `expression-name->alias` multi (or something like it) to isolate that behavior somehow.  But I'm not sure what the best way is.  Thoughts?

**Comment by camsaul** [comment]
That's a good point. I think maybe we should not try to subsume all of `format-name`'s responsibilities in that case, since it's doing something a little different. I think just the separate `escape-identifier`

File: src/metabase/driver/sql/query_processor.clj [hunk 2]
```diff
@@ -181,18 +181,29 @@
...
-(defmulti ^String field->alias
-  "Return the string alias that should be used to for `field`, an instance of the Field model, i.e. in an `AS` clause.
-  The default implementation calls `:name`, which returns the *unqualified* name of the Field.
+(defmulti ^String escape-alias
+  "Return the String that should be emitted in the query for the given `alias-name`, which will follow the `AS` clause.
+  This is to allow for escaping names that particular databases may not allow as aliases for custom expressions
+  or fields (even when quoted).
 
-  Return `nil` to prevent `field` from being aliased."
-  {:arglists '([driver field])}
```
Comment (camsaul) [inline src/metabase/driver/sql/query_processor.clj:189]: It might be a good idea to just leave this method unused for the time being and mark it as deprecated just so it's not a breaking change for 3rd-party drivers in 41. Normally we've been marking something as deprecated and removing it 3 versions later.

Not sure anybody else ever actually implemented this method but since it's not `^:private` we can't be sure

**Review by camsaul — APPROVED** [review]
LGTM. We should think about whether there's a way to leave `field->alias` in as a deprecated/unused method (maybe rename the function version to something else) to give 3rd party driver authors a chance to remove their impls if they have one

File: src/metabase/driver/sql/query_processor.clj [hunk 3]
```diff
@@ -181,18 +181,36 @@
...
-  The default implementation calls `:name`, which returns the *unqualified* name of the Field.
+  The default implementation calls `escape-alias` on the field `:name`, which returns the *unqualified* name of the
+  Field.
+
+  Return `nil` to prevent `field` from being aliased.
 
-  Return `nil` to prevent `field` from being aliased."
+  DEPRECATED as of x.41.  This multimethod will be removed in a future release.  Instead, drivers will simply
+  override the `escape-alias` multimethod if they want to influence the alias to be used for a given field name."
   {:arglists '([driver field])}
```
Comment (camsaul) [inline src/metabase/driver/sql/query_processor.clj:207]:
```suggestion
  {:arglists '([driver field]), :deprecated "0.41.0"}
```

File: src/metabase/driver/sql/query_processor.clj [hunk 4]
```diff
@@ -181,18 +181,36 @@
...
+  Defaults to identity (i.e. returns `alias-name` unchanged)."
+  {:added "0.41.0" :arglists '([driver alias-name])}
+  driver/dispatch-on-initialized-driver
+  :hierarchy #'driver/hierarchy)
+
+(defmethod escape-alias :sql
+  [_ alias-name]
+  alias-name)
+
+(defmulti ^:deprecated ^String field->alias
```
Comment (camsaul) [inline src/metabase/driver/sql/query_processor.clj:198]:
```suggestion
(defmulti ^String field->alias
```

File: src/metabase/driver/sql/query_processor.clj (hunk 3 above)
Comment (jeff303) [reply src/metabase/driver/sql/query_processor.clj]: Fixed

File: src/metabase/driver/sql/query_processor.clj (hunk 4 above)
Comment (jeff303) [reply src/metabase/driver/sql/query_processor.clj]: Fixed
