### PR TITLE
Fix stacked redirects to homepage dashboard crashing the app

### LINKED ISSUE #43800: Clicking two times over the metabase logo will return that something's wrong
### Describe the bug

Weird bug probably related to https://github.com/metabase/metabase/issues/41563?

### To Reproduce

1) in the home page of stats, do double click to the logo
2) see the error

### Expected behavior

we should load the home page?

### Logs

NA

### Information about your Metabase installation

```JSON
master
```

### Severity

P1

### Additional context

image

### PR DESCRIPTION
**Pull request by kulyk**
Closes #43800

Avoids navigating a user to `/` and then back to the homepage dashboard while being on the homepage dashboard. Clicking the logo multiple times in a row would stack up a few redirects, each of them canceling the previous one and eventually leading to an error

I don't feel great about duplicating this logic in both the logo and the sidebar's Home link. I've tried solving this closer to the [redirect](https://github.com/metabase/metabase/blob/dfdaab03b3200cc21aa0ea3e4b6f8b0393090038/frontend/src/metabase/home/components/HomePage/HomePage.tsx#L101) itself, but we don't seem to have a clean way to access the previous route while inside that hook to disable navigation. For the sake of fixing a P1 this feels alright though, looking forward to feedback and suggestions 🙏 

### To verify

1. Go to `/admin/settings/general#custom-homepage` and turn any dashboard into the homepage
2. Open `/`
3. Click the Metabase logo at the top left multiple times
4. Click the "Home" link in the navigation sidebar multiple times 
5. Ensure you stay on the homepage and there are no reloads or errors

### Demo

**Before**

https://github.com/metabase/metabase/assets/17258145/16ea07f0-24aa-4f2f-832b-d44058615f43

**After**

https://github.com/metabase/metabase/assets/17258145/1171814c-107b-476c-ab2a-b1db4cfc5ef1

### CODE REVIEW

File: frontend/src/metabase/common/hooks/use-homepage-dashboard.tsx [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+export const useHomepageDashboard = () => {
+  const dashboardId = useSelector(getCustomHomePageDashboardId);
+  const isLoadingSettings = useSelector(getSettingsLoading);
+  const { pathname } = useLocation();
+
+  const { data: dashboard, isLoading: isLoadingDashboard } =
+    useGetDashboardQuery(dashboardId ? { id: dashboardId } : skipToken);
+
+  const isAtHomepageDashboard = Boolean(
+    dashboardId && pathname?.startsWith(`/dashboard/${dashboardId}`),
```
Comment (alxnddr) [inline frontend/src/metabase/common/hooks/use-homepage-dashboard.tsx:17]: I assume `.startsWith(`/dashboard/${dashboardId}`)` may not work correctly when a metabase instance is not in under the root path, for instance `https://myapp.com/analytics/`

**Review by alxnddr — COMMENTED** [review]
I left one concern about checking for the current path which may not work when an instance is not under the root. I wonder if we can fix it by something like:
```
import { useSelector } from "metabase/lib/redux";
import { getCustomHomePageDashboardId } from "metabase/home/selectors";

export const useHomePageUrl = () => {
  const dashboardId = useSelector(getCustomHomePageDashboardId);
  return dashboardId != null ? `/dashboard/${dashboardId}` : "/";
};
```
And use it in `frontend/src/metabase/nav/components/AppBar/AppBarLogo.tsx` and `frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx`

**Comment by kulyk** [comment]
@alxnddr great catch! The fix didn't work if Metabase wasn't hosted under a root path. Please take a look at [`ae631f7`](https://github.com/metabase/metabase/pull/43836/commits/ae631f74d3be3377db394d17f2530c41409079b9), I went a slightly different path, but it seems to be working as expected

CleanShot 2024-06-10 at 14 48 03@2x

(`href` is coming from `location`, `pathname` is `href.replace(siteUrl, ""`)

**Review by alxnddr — APPROVED** [review]
