### PR TITLE
SQL snippets should not always have scrollbars

### LINKED ISSUE #21550: SQL snippets show scrollbars when it isn't needed
**Describe the bug**
We show scrollbars for the SQL snippets even when it's not needed

**Logs**
None

**To Reproduce**
In a Metabase instance go to:
1) new->sql query
2) click on the snippets button
3) Add a snippet as small as "select * from people* and save it
4) now expand the snippet to see the scrollbars

**Expected behavior**
If we don't need scrollbars, either horizontal or vertical, we shouldn't show them

**Screenshots**
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgres 14
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
Cosmetic

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ariya**
Instead, the (vertical) scrollbar should appear only when necessary.

To verify:
1. New, SQL query
2. Click on `SQL Snippets` to display the snippets sidebar
3. `+` to add a new snippet, e.g. `select * from people`
4. Give it a name and click `Save`

**Before this PR**

Both scrollbar are visible, despite the fact that there is no need to scroll at all.

image

**After this PR**

Clean look, with no scrollbars.

image

**Note**

If the snippet is really long, i.e. spanning multiple lines, scrolling is needed and the scrollbar is present automatically.

image

### CODE REVIEW

**Review by flamber — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/template_tags/snippet-sidebar/SnippetRow.jsx [hunk 1]
```diff
@@ -68,8 +68,8 @@ class SnippetRow extends React.Component {
           <div className="px3 pb2 pt1">
             {description && <p className="text-medium mt0">{description}</p>}
             <pre
-              className="bg-light bordered rounded p1 text-monospace text-small text-pre-wrap overflow-scroll overflow-x-scroll"
-              style={{ maxHeight: 320 }}
+              className="bg-light bordered rounded p1 text-monospace text-small text-pre-wrap"
+              style={{ maxHeight: 320, overflow: "auto" }}
```
Comment (iethree) [inline frontend/src/metabase/query_builder/components/template_tags/snippet-sidebar/SnippetRow.jsx:72]:
```suggestion
              className="bg-light bordered rounded p1 text-monospace text-small text-pre-wrap overflow-auto"
              style={{ maxHeight: 320 }}
```
