### PR TITLE
Fix - Uncaught TypeError when making native query parameter required

### LINKED ISSUE #52812: Uncaught TypeError when making native query parameter required
### Describe the bug

`TagEditorParam` assumes `parameter` props is never `undefined`, but it can be.

### To Reproduce

1. New > SQL Query
2. `{{x}}`
3. Change variable type to "Field Filter"
4. Notice Field picker automatically opened
5. Close the field picker by click on "Select..."
6. Observe JS console in the next step
7. Check the "Always require a value" switch
 
```
TagEditorParam.tsx:165 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at TagEditorParamInner.setRequired (TagEditorParam.tsx:165:1)
```

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
master, 760f65f7e5a4973d583544cafe26a3d3d14debcf
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #52812

### Description

Hides "Default filter widget value" input when "Variable type" is "Field Filter" but "Field to map to" has not been selected yet.
The `onChange` handler of "Default filter widget value" would not work in that state.
Other inputs that depend on "Field to map to" being selected are also hidden in the same way.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New > SQL Query
2. `{{x}}`
3. Change variable type to "Field Filter"
4. Notice Field picker automatically opened
5. Close the field picker by click on "Select..."

The "Default filter widget value" input should not be rendered.

### CODE REVIEW

File: frontend/src/metabase/query_builder/actions/native.ts [hunk 1]
```diff
@@ -172,7 +172,7 @@ export const setTemplateTag = createThunkAction(
 export const SET_TEMPLATE_TAG_CONFIG = "metabase/qb/SET_TEMPLATE_TAG_CONFIG";
 export const setTemplateTagConfig = createThunkAction(
   SET_TEMPLATE_TAG_CONFIG,
-  (tag: TemplateTag, parameter: Parameter) => {
+  (tag: TemplateTag, parameter: ParameterValuesConfig) => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/actions/native.ts:175]: It was not necessary to pass the entire `Parameter` here

File: frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.tsx [hunk 2]
```diff
@@ -162,16 +168,21 @@ class TagEditorParamInner extends Component<Props> {
       setTemplateTag({ ...tag, required: required });
     }
 
+    if (!parameter) {
+      // this handler is attached to a component rendered only when parameter is truthy
+      // so this case should never happen
+      return;
+    }
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.tsx:175]: The TypeError this PR is fixing comes from line 177

**Review by uladzimirdev — APPROVED** [review]

**Comment by kamilmielnik** [comment]
@uladzimirdev Some tests were failing, I pushed a fix, please have another look

**Review by uladzimirdev — APPROVED** [review]
👍
