### PR TITLE
Fix bug in ordering by an aggregate expression [ci drivers]

### LINKED ISSUE #5943: Cannot sort on custom and saved metrics
Reproduced on sample dataset on Master.

Steps
select sample dataset -> orders
select count of rows grouped by created_date/year
click on count in table header -> descending
it works
now modify count of rows and click on custome metric and put something like count*10 for eg.
click on "count *" in table header -> descending/ascending 
no effect

PS: name of the column "count*" is wierd, should be "count * 10 "

### PR DESCRIPTION
**Pull request by senior**
When ordering by a non-aliased aggregate expression, the order by
clause wouldn't resolve correctly. This resulted in a null value in the
order by which would then have no affect on the order of the
results. The AgFieldRef wasn't able to handle an expression in the
order-by.

Fixes #5943

### CODE REVIEW

File: test/metabase/driver/bigquery_test.clj [hunk 1]
```diff
@@ -76,24 +76,37 @@
                                                                       ["field-id" (data/id :checkins :venue_id)]]]
                                                   "User ID Plus Venue ID"]]}})))
 
-;; make sure BigQuery can handle two aggregations with the same name (#4089)
```
Comment (camsaul) [inline test/metabase/driver/bigquery_test.clj]: having the comment explaining what we're testing is still useful IMO

**Review by camsaul — APPROVED** [review]
Other than removing explanation for a test this looks good. If we put that comment back in then :+1:

File: test/metabase/driver/bigquery_test.clj (hunk 1 above)
Comment (senior) [reply test/metabase/driver/bigquery_test.clj]: That wasn't intentional, I'll put it back in 👍
