### PR TITLE
String fields fetch field type info from :field_ref as well as :source_metadata

### LINKED ISSUE #53451: Filtering on a Postgres enum after a Summarize stage breaks the question
### Describe the bug

Filtering on a Postgres enum after a summarize stage causes an 'Error generating the query' error.

The query works when the filter on the enum is added before the summarize.

### To Reproduce

1. Using Postgres, create a table with an enum data type. My example:
```
CREATE TYPE test_enums.order_status AS ENUM ( 'NEW', 'CANCELED' );
CREATE TABLE test_enums.test_enums_orders (
                        order_id SERIAL PRIMARY KEY,
                        status test_enums.order_status
                        );
INSERT INTO test_enums.test_enums_orders (status) VALUES
                                                         ('NEW'),
                                                         ('NEW'),
                                                         ('CANCELED');
```
2. Create a GUI query on the table: Group by: Status, Summarize: Count of rows, Filter after the Summarize stage: Status is New
Image

3. Visualize and see the error: 'Error generating the query'
Image

### Expected behavior

It should work.

### Logs

`/api/dataset` response:
```
{
  "database_id": 7,
  "started_at": "2025-02-10T14:12:05.13919Z",
  "via": [
    {
      "status": "failed",
      "class": "class clojure.lang.ExceptionInfo",
      "error": "Error compiling query: null",
      "stacktrace": [
        "--> query_processor.compile$compile_preprocessed74542__74543$fn__74544.invoke(compile.clj:35)",
        "query_processor.setup$do_with_qp_setup73931__73932.invokeStatic(setup.clj:225)",
        "query_processor.setup$do_with_qp_setup73931__73932.invoke(setup.clj:216)",
        "query_processor.compile$compile_preprocessed74542__74543.invokeStatic(compile.clj:30)",
        "query_processor.compile$compile_preprocessed74542__74543.invoke(compile.clj:26)",
        "query_processor.compile$attach_compiled_query74554__74555.invokeStatic(compile.clj:54)",
        "query_processor.compile$attach_compiled_query74554__74555.invoke(compile.clj:45)",
        "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)",
        "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)",
        "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__91412$handle_audit_app_internal_queries__91413$fn__91414.invoke(handle_audit_queries.clj:145)",
        "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__73415.invoke(enterprise.clj:103)",
        "query_processor.middleware.process_userland_query$process_userland_query_middleware78674__78675$fn__78676.invoke(process_userland_query.clj:217)",
        "query_processor.middleware.catch_exceptions$catch_exceptions78739__78740$fn__78741.invoke(catch_exceptions.clj:132)",
        "query_processor$process_query78780__78781$fn__78782.invoke(query_processor.clj:80)",
        "query_processor.setup$do_with_canceled_chan73926__73927$fn__73928.invoke(setup.clj:187)",
        "query_processor.setup$do_with_database_local_settings73919__73920$fn__73921.invoke(setup.clj:181)",
        "query_processor.setup$do_with_driver73912__73913$fn__73914$fn__73915.invoke(setup.clj:166)",
        "driver$do_with_driver.invokeStatic(driver.clj:106)",
        "driver$do_with_driver.invoke(driver.clj:101)",
        "query_processor.setup$do_with_driver73912__73913$fn__73914.invoke(setup.clj:165)",
        "query_processor.setup$do_with_metadata_provider73903__73904$fn__73905$fn__73908.invoke(setup.clj:151)",
        "query_processor.store$do_with_metadata_provider59870__59871.invokeStatic(store.clj:170)",
        "query_processor.store$do_with_metadata_provider59870__59871.invoke(store.clj:150)",
        "query_processor.store$do_with_metadata_provider59870__59871.invokeStatic(store.clj:159)",
        "query_processor.store$do_with_metadata_provider59870__59871.invoke(store.clj:150)",
        "query_processor.setup$do_with_metadata_provider73903__73904$fn__73905.invoke(setup.clj:150)",
        "query_processor.setup$do_with_resolved_database73893__73894$fn__73895.invoke(setup.clj:128)",
        "query_processor.setup$do_with_qp_setup73931__73932.invokeStatic(setup.clj:232)",
        "query_processor.setup$do_with_qp_setup73931__73932.invoke(setup.clj:216)",
        "query_processor$process_query78780__78781.invokeStatic(query_processor.clj:78)",
        "query_processor$process_query78780__78781.invoke(query_processor.clj:71)",
        "api.dataset$run_streaming_query103181__103184$fn__103188.invoke(dataset.clj:84)",
        "query_processor.streaming$_streaming_response$fn__83332$fn__83333$fn__83334.invoke(streaming.clj:185)",
        "query_processor.streaming$_streaming_response$fn__83332$fn__83333.invoke(streaming.clj:183)",
        "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:174)",
        "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:161)",
        "query_processor.streaming$_streaming_response$fn__83332.invoke(streaming.clj:180)",
        "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)",
        "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)",
        "async.streaming_response$do_f_async$task__53508.invoke(streaming_response.clj:93)"
      ],
      "error_type": "driver",
      "ex-data": {
        "query": {
          "database": 7,
          "middleware": {
            "js-int-to-string?": true,
            "userland-query?": true,
            "add-default-userland-constraints?": true
          },
          "info": {
            "executed-by": 1,
            "context": "ad-hoc",
            "query-hash": "0x46FB70D4"
          },
          "constraints": {
            "max-results": 10000,
            "max-results-bare-rows": 2000
          },
          "type": "query",
          "query": {
            "fields": [
              [
                "field",
                1485,
                {
                  "base-type": "type/PostgresEnum"
                }
              ],
              [
                "field",
                "count",
                {
                  "base-type": "type/Integer"
                }
              ]
            ],
            "filter": [
              "=",
              [
                "field",
                "status",
                {
                  "base-type": "type/PostgresEnum"
                }
              ],
              [
                "value",
                "NEW",
                {
                  "base_type": "type/PostgresEnum",
                  "effective_type": "type/PostgresEnum"
                }
              ]
            ],
            "source-query": {
              "source-table": 132,
              "aggregation": [
                [
                  "aggregation-options",
                  [
                    "count"
                  ],
                  {
                    "name": "count"
                  }
                ]
              ],
              "breakout": [
                [
                  "field",
                  1485,
                  {
                    "base-type": "type/PostgresEnum"
                  }
                ]
              ],
              "order-by": [
                [
                  "asc",
                  [
                    "field",
                    1485,
                    {
                      "base-type": "type/PostgresEnum"
                    }
                  ]
                ]
              ]
            },
            "source-metadata": [
              {
                "semantic_type": "type/Category",
                "table_id": 132,
                "name": "status",
                "field_ref": [
                  "field",
                  1485,
                  {
                    "base-type": "type/PostgresEnum"
                  }
                ],
                "effective_type": "type/PostgresEnum",
                "id": 1485,
                "display_name": "Status",
                "fingerprint": {
                  "global": {
                    "distinct-count": 2,
                    "nil%": 0.0
                  }
                },
                "base_type": "type/PostgresEnum"
              },
              {
                "name": "count",
                "display_name": "Count",
                "base_type": "type/Integer",
                "semantic_type": "type/Quantity",
                "field_ref": [
                  "aggregation",
                  0
                ]
              }
            ],
            "limit": 2000,
            "metabase.query-processor.middleware.limit/original-limit": null
          }
        },
        "type": "driver"
      }
    }
  ],
  "action_id": null,
  "error_type": "driver",
  "json_query": {
    "database": 7,
    "type": "query",
    "query": {
      "filter": [
        "=",
        [
          "field",
          "status",
          {
            "base-type": "type/PostgresEnum"
          }
        ],
        "NEW"
      ],
      "source-query": {
        "source-table": 132,
        "aggregation": [
          [
            "count"
          ]
        ],
        "breakout": [
          [
            "field",
            1485,
            {
              "base-type": "type/PostgresEnum"
            }
          ]
        ]
      }
    },
    "parameters": [],
    "middleware": {
      "js-int-to-string?": true,
      "userland-query?": true,
      "add-default-userland-constraints?": true
    }
  },
  "native": null,
  "status": "failed",
  "class": "class java.lang.NullPointerException",
  "stacktrace": [
    null
  ],
  "card_id": null,
  "context": "ad-hoc",
  "error": "Error running query",
  "row_count": 0,
  "running_time": 0,
  "preprocessed": {
    "database": 7,
    "middleware": {
      "js-int-to-string?": true,
      "userland-query?": true,
      "add-default-userland-constraints?": true
    },
    "info": {
      "executed-by": 1,
      "context": "ad-hoc"
    },
    "constraints": {
      "max-results": 10000,
      "max-results-bare-rows": 2000
    },
    "type": "query",
    "query": {
      "fields": [
        [
          "field",
          1485,
          {
            "base-type": "type/PostgresEnum"
          }
        ],
        [
          "field",
          "count",
          {
            "base-type": "type/Integer"
          }
        ]
      ],
      "filter": [
        "=",
        [
          "field",
          "status",
          {
            "base-type": "type/PostgresEnum"
          }
        ],
        [
          "value",
          "NEW",
          {
            "base_type": "type/PostgresEnum",
            "effective_type": "type/PostgresEnum"
          }
        ]
      ],
      "source-query": {
        "source-table": 132,
        "aggregation": [
          [
            "aggregation-options",
            [
              "count"
            ],
            {
              "name": "count"
            }
          ]
        ],
        "breakout": [
          [
            "field",
            1485,
            {
              "base-type": "type/PostgresEnum"
            }
          ]
        ],
        "order-by": [
          [
            "asc",
            [
              "field",
              1485,
              {
                "base-type": "type/PostgresEnum"
              }
            ]
          ]
        ]
      },
      "source-metadata": [
        {
          "semantic_type": "type/Category",
          "table_id": 132,
          "name": "status",
          "field_ref": [
            "field",
            1485,
            {
              "base-type": "type/PostgresEnum"
            }
          ],
          "effective_type": "type/PostgresEnum",
          "id": 1485,
          "display_name": "Status",
          "fingerprint": {
            "global": {
              "distinct-count": 2,
              "nil%": 0.0
            }
          },
          "base_type": "type/PostgresEnum"
        },
        {
          "name": "count",
          "display_name": "Count",
          "base_type": "type/Integer",
          "semantic_type": "type/Quantity",
          "field_ref": [
            "aggregation",
            0
          ]
        }
      ],
      "limit": 2000,
      "metabase.query-processor.middleware.limit/original-limit": null
    }
  },
  "data": {
    "rows": [],
    "cols": []
  }
}
```

### Information about your Metabase installation

```JSON
1.51.13 and 1.52.9.1
```

### Severity

Found by looking for something else

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wzimrin**
Closes https://github.com/metabase/metabase/issues/53451

### Description

When wrapping literal values in :value clauses, fields with string-type ids (for example, fields after an aggregation) were getting their type info from source-metadata.  When the field in question was a postgres enum, the source metadata was missing important data.  Fetching info from both source-metadata and the type info of field-ref fixes that.

### How to verify

Repro steps are in the linked case

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/middleware/wrap_value_literals.clj [hunk 1]
```diff
@@ -51,10 +51,14 @@
                              (some #(when (= join-alias (:alias %))
                                       (:source-metadata %))
                                    (:joins inner-query))
-                             (:source-metadata inner-query))]
-      (some #(when (= (:name %) field-name)
-               (select-keys % [:base_type :effective_type :database_type]))
-            source-metadatas))))
+                             (:source-metadata inner-query))
+          [{[_ field-name :as field-ref] :field_ref :as field-metadata}] (filter #(= (:name %) field-name)
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/wrap_value_literals.clj:55]: Use `m/find-first` rather than `filter` + destructuring, if you only want the first match.

**Review by metamben — APPROVED** [review]

File: test/metabase/query_processor/middleware/wrap_value_literals_test.clj [hunk 2]
```diff
@@ -334,3 +334,20 @@
...
+
+(deftest ^:parallel type-info-gets-field-ref-data-test
+  (testing "type info includes data from :field_ref as well as :source-metadata"
+    (is (=? {:query
+             {:filter
+              [:=
+               [:field "CATEGORY" {:base-type :type/Text}]
+               [:value "Doohickey" {:base_type :type/Text,
+                                    :effective_type :type/Text,
+                                    :database_type "CHARACTER VARYING"}]]}}
```
Comment (bshepherdson) [inline test/metabase/query_processor/middleware/wrap_value_literals_test.clj:346]: Please wrap this with `mt/mbql-query` too; it does more than fill in field IDs. It does some `=?` magic to ignore the drift of randomized values.

**Review by bshepherdson — APPROVED** [review]
