### PR TITLE
Use name from metric aggregation after preprocessing

### LINKED ISSUE #48625: Model that uses v1 metrics does not work after v2 migration
Briefly, model that uses 2 v1 metrics fails to execute after the migration to v2 metrics.

- I've used tag `v0.49.25.2` where I defined those metrics. Then started the application on `v1.51.0.1-beta`. Migration ran successfully.
- I've used Postgresql as data warehouse (`test-data`) and application database.

Metric 1 definition (named mfa):
Image

Metric 2 definition (named mt):
Image

Model:
Image

Finally, opening that model after migration results in an error. Screenshot and trace follow.
Image

<details closed>
<summary>Trace</summary>
<code>
2024-10-11 14:27:54,548 ERROR middleware.catch-exceptions :: Error processing query: ERROR: column source.avg does not exist
  Position: 183
{:database_id 2,
 :started_at #t "2024-10-11T14:27:53.964048Z[UTC]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query: ERROR: column source.avg does not exist\n  Position: 183",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__140327$fn__140328.invoke(execute.clj:717)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__140327.invoke(execute.clj:714)"
    "driver.sql_jdbc.execute$eval140041$fn__140042$fn__140043.invoke(execute.clj:398)"
    "driver.sql_jdbc.execute$fn__139990$do_with_resolved_connection139989__139991.invoke(execute.clj:338)"
    "driver.sql_jdbc.execute$fn__139990$fn__139994.invoke(execute.clj:321)"
    "driver.sql_jdbc.execute$eval140041$fn__140042.invoke(execute.clj:392)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
    "driver.sql_jdbc$eval142036$fn__142037.invoke(sql_jdbc.clj:79)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
    "query_processor.execute$run.invokeStatic(execute.clj:62)"
    "query_processor.execute$run.invoke(execute.clj:56)"
    "query_processor.middleware.update_used_cards$fn__104007$update_used_cards_BANG_104006__104008$_AMPERSAND_f__104009.invoke(update_used_cards.clj:60)"
    "query_processor.middleware.update_used_cards$fn__104007$update_used_cards_BANG_104006__104008$fn__104019.invoke(update_used_cards.clj:52)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__104031.invoke(execute.clj:25)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__104037.invoke(execute.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___103857.invoke(cache.clj:239)"
    "query_processor.middleware.permissions$check_query_permissions$fn__102771.invoke(permissions.clj:147)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__100777.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__100787.invoke(enterprise.clj:64)"
    "query_processor.execute$fn__104071$execute104070__104072$fn__104073.invoke(execute.clj:94)"
    "query_processor.setup$fn__103338$do_with_qp_setup103337__103339.invoke(setup.clj:225)"
    "query_processor.setup$fn__103338$fn__103343.invoke(setup.clj:216)"
    "query_processor.execute$fn__104071$execute104070__104072.invoke(execute.clj:93)"
    "query_processor.execute$fn__104071$fn__104076.invoke(execute.clj:89)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
    "query_processor.middleware.enterprise$eval100804$handle_audit_app_internal_queries__100805$fn__100807.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__100815.invoke(enterprise.clj:103)"
    "query_processor.middleware.process_userland_query$fn__104458$process_userland_query_middleware104457__104459$_AMPERSAND_f__104460.invoke(process_userland_query.clj:204)"
    "query_processor.middleware.process_userland_query$fn__104458$process_userland_query_middleware104457__104459$fn__104466.invoke(process_userland_query.clj:188)"
    "query_processor.middleware.catch_exceptions$fn__104170$catch_exceptions104169__104171$_AMPERSAND_f__104172.invoke(catch_exceptions.clj:132)"
    "query_processor.middleware.catch_exceptions$fn__104170$catch_exceptions104169__104171$fn__104187.invoke(catch_exceptions.clj:122)"
    "query_processor$fn__104802$process_query104801__104803$fn__104804.invoke(query_processor.clj:80)"
    "query_processor.setup$fn__103329$do_with_canceled_chan103328__103330$fn__103331.invoke(setup.clj:187)"
    "query_processor.setup$fn__103318$do_with_database_local_settings103317__103319$fn__103320.invoke(setup.clj:181)"
    "query_processor.setup$fn__103307$do_with_driver103306__103308$fn__103309$fn__103310.invoke(setup.clj:166)"
    "driver$do_with_driver.invokeStatic(driver.clj:106)"
    "driver$do_with_driver.invoke(driver.clj:101)"
    "query_processor.setup$fn__103307$do_with_driver103306__103308$fn__103309.invoke(setup.clj:165)"
    "query_processor.setup$fn__103294$do_with_metadata_provider103293__103295$fn__103296$fn__103299.invoke(setup.clj:151)"
    "query_processor.store$fn__86949$do_with_metadata_provider86948__86950.invoke(store.clj:170)"
    "query_processor.store$fn__86949$fn__86953.invoke(store.clj:150)"
    "query_processor.store$fn__86949$do_with_metadata_provider86948__86950.invoke(store.clj:159)"
    "query_processor.store$fn__86949$fn__86953.invoke(store.clj:150)"
    "query_processor.setup$fn__103294$do_with_metadata_provider103293__103295$fn__103296.invoke(setup.clj:150)"
    "query_processor.setup$fn__103274$do_with_resolved_database103273__103275$_AMPERSAND_f__103276.invoke(setup.clj:128)"
    "query_processor.setup$fn__103274$do_with_resolved_database103273__103275$fn__103279.invoke(setup.clj:122)"
    "query_processor.setup$fn__103338$do_with_qp_setup103337__103339.invoke(setup.clj:232)"
    "query_processor.setup$fn__103338$fn__103343.invoke(setup.clj:216)"
    "query_processor$fn__104802$process_query104801__104803.invoke(query_processor.clj:78)"
    "query_processor$fn__104802$fn__104808.invoke(query_processor.clj:71)"
    "api.dataset$fn__150512$run_streaming_query150511__150515$fn__150519.invoke(dataset.clj:84)"
    "query_processor.streaming$_streaming_response$fn__127832$fn__127833$fn__127834.invoke(streaming.clj:176)"
    "query_processor.streaming$_streaming_response$fn__127832$fn__127833.invoke(streaming.clj:174)"
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
    "query_processor.streaming$_streaming_response$fn__127832.invoke(streaming.clj:171)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
    "async.streaming_response$do_f_async$task__64242.invoke(streaming_response.clj:97)"],
   :error_type :invalid-query,
   :ex-data
   {:driver :postgres,
    :sql
    ["-- Metabase:: userID: 1 queryType: MBQL queryHash: 7bc9be55d5035954b5b452ae1680126b7d0f72a349ab772c370b2c52855fb6c4"
     "SELECT"
     "  \"source\".\"Products__created_at\" AS \"Products__created_at\","
     "  \"source\".\"avg\" AS \"avg\","
     "  \"source\".\"sum\" AS \"sum\""
     "FROM"
     "  ("
     "    SELECT"
     "      DATE_TRUNC('month', \"Products\".\"created_at\") AS \"Products__created_at\","
     "      AVG(\"public\".\"orders\".\"tax\") AS \"mfa\","
     "      SUM(\"public\".\"orders\".\"total\") AS \"mt\""
     "    FROM"
     "      \"public\".\"orders\""
     "      LEFT JOIN \"public\".\"products\" AS \"Products\" ON \"public\".\"orders\".\"product_id\" = \"Products\".\"id\""
     "    WHERE"
     "      (\"Products\".\"created_at\" < ?)"
     "      AND (\"public\".\"orders\".\"user_id\" < 30)"
     "      AND (\"public\".\"orders\".\"user_id\" > 10)"
     "    GROUP BY"
     "      DATE_TRUNC('month', \"Products\".\"created_at\")"
     "    ORDER BY"
     "      DATE_TRUNC('month', \"Products\".\"created_at\") ASC"
     "  ) AS \"source\""
     "LIMIT"
     "  2000"],
    :params (#t "2024-10-11T00:00Z"),
    :type :invalid-query}}],
 :action_id nil,
 :state "42703",
 :error_type :invalid-query,
 :json_query
 {:database 2,
  :type "query",
  :query {:source-table "card__76"},
  :parameters [],
  :middleware {:js-int-to-string? true, :userland-query? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"Products__created_at\" AS \"Products__created_at\", \"source\".\"avg\" AS \"avg\", \"source\".\"sum\" AS \"sum\" FROM (SELECT DATE_TRUNC('month', \"Products\".\"created_at\") AS \"Products__created_at\", AVG(\"public\".\"orders\".\"tax\") AS \"mfa\", SUM(\"public\".\"orders\".\"total\") AS \"mt\" FROM \"public\".\"orders\" LEFT JOIN \"public\".\"products\" AS \"Products\" ON \"public\".\"orders\".\"product_id\" = \"Products\".\"id\" WHERE (\"Products\".\"created_at\" < ?) AND (\"public\".\"orders\".\"user_id\" < 30) AND (\"public\".\"orders\".\"user_id\" > 10) GROUP BY DATE_TRUNC('month', \"Products\".\"created_at\") ORDER BY DATE_TRUNC('month', \"Products\".\"created_at\") ASC) AS \"source\" LIMIT 2000",
  :params (#t "2024-10-11T00:00Z")},
 :status :failed,
 :class org.postgresql.util.PSQLException,
 :stacktrace
 ["org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)"
  "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)"
  "org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)"
  "org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)"
  "--> driver.sql_jdbc.execute$eval140209$fn__140210.invoke(execute.clj:566)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:579)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:575)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__140327$fn__140328.invoke(execute.clj:715)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__140327.invoke(execute.clj:714)"
  "driver.sql_jdbc.execute$eval140041$fn__140042$fn__140043.invoke(execute.clj:398)"
  "driver.sql_jdbc.execute$fn__139990$do_with_resolved_connection139989__139991.invoke(execute.clj:338)"
  "driver.sql_jdbc.execute$fn__139990$fn__139994.invoke(execute.clj:321)"
  "driver.sql_jdbc.execute$eval140041$fn__140042.invoke(execute.clj:392)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
  "driver.sql_jdbc$eval142036$fn__142037.invoke(sql_jdbc.clj:79)"
  "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
  "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
  "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
  "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
  "query_processor.execute$run.invokeStatic(execute.clj:62)"
  "query_processor.execute$run.invoke(execute.clj:56)"
  "query_processor.middleware.update_used_cards$fn__104007$update_used_cards_BANG_104006__104008$_AMPERSAND_f__104009.invoke(update_used_cards.clj:60)"
  "query_processor.middleware.update_used_cards$fn__104007$update_used_cards_BANG_104006__104008$fn__104019.invoke(update_used_cards.clj:52)"
  "query_processor.execute$add_native_form_to_result_metadata$fn__104031.invoke(execute.clj:25)"
  "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__104037.invoke(execute.clj:36)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___103857.invoke(cache.clj:239)"
  "query_processor.middleware.permissions$check_query_permissions$fn__102771.invoke(permissions.clj:147)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__100777.invoke(enterprise.clj:51)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__100787.invoke(enterprise.clj:64)"
  "query_processor.execute$fn__104071$execute104070__104072$fn__104073.invoke(execute.clj:94)"
  "query_processor.setup$fn__103338$do_with_qp_setup103337__103339.invoke(setup.clj:225)"
  "query_processor.setup$fn__103338$fn__103343.invoke(setup.clj:216)"
  "query_processor.execute$fn__104071$execute104070__104072.invoke(execute.clj:93)"
  "query_processor.execute$fn__104071$fn__104076.invoke(execute.clj:89)"
  "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
  "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
  "query_processor.middleware.enterprise$eval100804$handle_audit_app_internal_queries__100805$fn__100807.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__100815.invoke(enterprise.clj:103)"
  "query_processor.middleware.process_userland_query$fn__104458$process_userland_query_middleware104457__104459$_AMPERSAND_f__104460.invoke(process_userland_query.clj:204)"
  "query_processor.middleware.process_userland_query$fn__104458$process_userland_query_middleware104457__104459$fn__104466.invoke(process_userland_query.clj:188)"
  "query_processor.middleware.catch_exceptions$fn__104170$catch_exceptions104169__104171$_AMPERSAND_f__104172.invoke(catch_exceptions.clj:132)"
  "query_processor.middleware.catch_exceptions$fn__104170$catch_exceptions104169__104171$fn__104187.invoke(catch_exceptions.clj:122)"
  "query_processor$fn__104802$process_query104801__104803$fn__104804.invoke(query_processor.clj:80)"
  "query_processor.setup$fn__103329$do_with_canceled_chan103328__103330$fn__103331.invoke(setup.clj:187)"
  "query_processor.setup$fn__103318$do_with_database_local_settings103317__103319$fn__103320.invoke(setup.clj:181)"
  "query_processor.setup$fn__103307$do_with_driver103306__103308$fn__103309$fn__103310.invoke(setup.clj:166)"
  "driver$do_with_driver.invokeStatic(driver.clj:106)"
  "driver$do_with_driver.invoke(driver.clj:101)"
  "query_processor.setup$fn__103307$do_with_driver103306__103308$fn__103309.invoke(setup.clj:165)"
  "query_processor.setup$fn__103294$do_with_metadata_provider103293__103295$fn__103296$fn__103299.invoke(setup.clj:151)"
  "query_processor.store$fn__86949$do_with_metadata_provider86948__86950.invoke(store.clj:170)"
  "query_processor.store$fn__86949$fn__86953.invoke(store.clj:150)"
  "query_processor.store$fn__86949$do_with_metadata_provider86948__86950.invoke(store.clj:159)"
  "query_processor.store$fn__86949$fn__86953.invoke(store.clj:150)"
  "query_processor.setup$fn__103294$do_with_metadata_provider103293__103295$fn__103296.invoke(setup.clj:150)"
  "query_processor.setup$fn__103274$do_with_resolved_database103273__103275$_AMPERSAND_f__103276.invoke(setup.clj:128)"
  "query_processor.setup$fn__103274$do_with_resolved_database103273__103275$fn__103279.invoke(setup.clj:122)"
  "query_processor.setup$fn__103338$do_with_qp_setup103337__103339.invoke(setup.clj:232)"
  "query_processor.setup$fn__103338$fn__103343.invoke(setup.clj:216)"
  "query_processor$fn__104802$process_query104801__104803.invoke(query_processor.clj:78)"
  "query_processor$fn__104802$fn__104808.invoke(query_processor.clj:71)"
  "api.dataset$fn__150512$run_streaming_query150511__150515$fn__150519.invoke(dataset.clj:84)"
  "query_processor.streaming$_streaming_response$fn__127832$fn__127833$fn__127834.invoke(streaming.clj:176)"
  "query_processor.streaming$_streaming_response$fn__127832$fn__127833.invoke(streaming.clj:174)"
  "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
  "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
  "query_processor.streaming$_streaming_response$fn__127832.invoke(streaming.clj:171)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
  "async.streaming_response$do_f_async$task__64242.invoke(streaming_response.clj:97)"],
 :card_id 76,
 :context :ad-hoc,
 :error "ERROR: column source.avg does not exist\n  Position: 183",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :middleware {:js-int-to-string? true, :userland-query? true, :add-default-userland-constraints? true},
  :qp/source-card-id 76,
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id 76,
   :metadata/model-metadata
   [{:semantic_type :type/CreationTimestamp,
     :unit :month,
     :name "created_at",
     :field_ref [:field 278 {:base-type :type/DateTimeWithLocalTZ, :join-alias "Products", :temporal-unit :month}],
     :effective_type :type/DateTimeWithLocalTZ,
     :id 278,
     :visibility_type :normal,
     :display_name "Products → Created At",
     :fingerprint
     {:global {:distinct-count 200, :nil% 0},
      :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147Z", :latest "2019-04-15T13:34:19.931Z"}}},
     :base_type :type/DateTimeWithLocalTZ}
    {:display_name "mfa",
     :field_ref [:aggregation 0],
     :name "avg",
     :base_type :type/Float,
     :effective_type :type/Float,
     :fingerprint
     {:global {:distinct-count 32, :nil% 0},
      :type
      {:type/Number
       {:min 0, :q1 1.7537500000000001, :q3 4.26625, :max 8.42, :sd 2.236228905364952, :avg 3.2791850340136057}}}}
    {:display_name "mt",
     :field_ref [:aggregation 1],
     :name "sum",
     :base_type :type/Float,
     :effective_type :type/Float,
     :fingerprint
     {:global {:distinct-count 35, :nil% 0},
      :type
      {:type/Number
       {:min 41.24,
        :q1 122.4425,
        :q3 337.0625,
        :max 644.4599999999999,
        :sd 152.21541606519085,
        :avg 245.8065714285714}}}}]},
  :database 2,
  :type :query,
  :query
  {:qp/stage-had-source-card 76,
   :source-query/model? true,
   :source-metadata
   [{:database_type "timestamptz",
     :semantic_type :type/CreationTimestamp,
     :table_id 27,
     :unit :month,
     :name "created_at",
     :field_ref [:field 278 {:base-type :type/DateTimeWithLocalTZ, :join-alias "Products", :temporal-unit :month}],
     :effective_type :type/DateTimeWithLocalTZ,
     :id 278,
     :position 7,
     :visibility_type :normal,
     :display_name "Products → Created At",
     :fingerprint
     {:global {:distinct-count 200, :nil% 0},
      :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147Z", :latest "2019-04-15T13:34:19.931Z"}}},
     :base_type :type/DateTimeWithLocalTZ}
    {:name "avg",
     :field_ref [:aggregation 0],
     :effective_type :type/Float,
     :display_name "mfa",
     :fingerprint
     {:global {:distinct-count 32, :nil% 0},
      :type
      {:type/Number
       {:min 0, :q1 1.7537500000000001, :q3 4.26625, :max 8.42, :sd 2.236228905364952, :avg 3.2791850340136057}}},
     :base_type :type/Float}
    {:name "sum",
     :field_ref [:aggregation 1],
     :effective_type :type/Float,
     :display_name "mt",
     :fingerprint
     {:global {:distinct-count 35, :nil% 0},
      :type
      {:type/Number
       {:min 41.24,
        :q1 122.4425,
        :q3 337.0625,
        :max 644.4599999999999,
        :sd 152.21541606519085,
        :avg 245.8065714285714}}},
     :base_type :type/Float}],
   :fields
   [[:field 278 {:base-type :type/DateTimeWithLocalTZ, :join-alias "Products"}]
    [:field "avg" {:base-type :type/Float}]
    [:field "sum" {:base-type :type/Float}]],
   :source-query
   {:source-table 24,
    :aggregation
    [[:aggregation-options [:avg [:field 262 {:base-type :type/Float}]] {:name "mfa"}]
     [:aggregation-options [:sum [:field 263 {:base-type :type/Float}]] {:name "mt"}]],
    :breakout [[:field 278 {:base-type :type/DateTimeWithLocalTZ, :join-alias "Products", :temporal-unit :month}]],
    :qp/stage-is-from-source-card 76,
    :filter
    [:and
     [:<
      [:field 278 {:base-type :type/DateTimeWithLocalTZ, :join-alias "Products", :temporal-unit :default}]
      [:absolute-datetime #t "2024-10-11T00:00Z" :default]]
     [:<
      [:field 260 nil]
      [:value
       30
       {:effective_type :type/Integer,
        :name "user_id",
        :base_type :type/Integer,
        :semantic_type :type/FK,
        :database_type "int4"}]]
     [:>
      [:field 260 nil]
      [:value
       10
       {:effective_type :type/Integer,
        :name "user_id",
        :base_type :type/Integer,
        :semantic_type :type/FK,
        :database_type "int4"}]]],
    :order-by
    [[:asc [:field 278 {:base-type :type/DateTimeWithLocalTZ, :join-alias "Products", :temporal-unit :month}]]],
    :joins
    [{:alias "Products",
      :strategy :left-join,
      :fields
      [[:field 274 {:join-alias "Products"}]
       [:field 280 {:join-alias "Products"}]
       [:field 275 {:join-alias "Products"}]
       [:field 279 {:join-alias "Products"}]
       [:field 281 {:join-alias "Products"}]
       [:field 277 {:join-alias "Products"}]
       [:field 276 {:join-alias "Products"}]
       [:field 278 {:join-alias "Products"}]],
      :condition
      [:= [:field 256 {:base-type :type/Integer}] [:field 274 {:base-type :type/Integer, :join-alias "Products"}]],
      :source-table 27}]},
   :limit 2000,
   :metabase.query-processor.middleware.limit/original-limit nil}},
 :data {:rows [], :cols []}}

</code>
</details>

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes https://github.com/metabase/metabase/issues/48625

### Description

Prior to this PR name of metric's aggregation from before preprocessing was used. For migrated metrics (and probably also for other metrics) that was `nil`. This PR adjusts that, so the name is used after it was added by preprocessing.

### How to verify

Run the new test or follow reproduction steps from the linked issue.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/query_processor/middleware/annotate_test.clj [hunk 1]
```diff
@@ -460,15 +460,14 @@
...
-      (is (=? {:cols [{:name           "totalEvents"
-                       :display_name   "Total Events"
+      (is (=? {:cols [{:display_name   "Total Events"
                        :base_type      :type/Text
                        :effective_type :type/Text
                        :source         :aggregation
                        :field_ref      [:aggregation 0]}]}
               (add-column-info
                (lib.tu.macros/mbql-query venues {:aggregation [[:metric 1]]})
-               {:cols [{:name "totalEvents", :display_name "Total Events", :base_type :type/Text}]}))))))
```
Comment (lbrdnk) [inline test/metabase/query_processor/middleware/annotate_test.clj:471]: Prior to this PR the name of metric was slapped onto metrics metadata in `lib.metadata.calculation/metadata-method :metric` implementation (called in the trace of `add-column-info`). Because (1) original aggregation's name is used now and (2) `[:metric 1]` is not defined (ie. no original aggregation) and (3) `:name` of `ours` (ie. coming from query) as per `metabase.query-processor.middleware.annotate/merge-col-metadata` is prefered it does not make sense to test for that here anymore.

Comment (lbrdnk) [inline test/metabase/query_processor/middleware/annotate_test.clj:471]: Prior this PR metric name was slapped onto ... in .... In this case that is nil because metric 1 is not defined. 

Then, `metabase.query-processor.middleware.annotate/merge-col-metadata` picks `:name` from mocked cols over `nil`.

With the change to `lib.metadata.calculation/metadata-method :metric` in place the underlying logic sets the `:name` to `"nil"` for not defined metric.

The `metabase.query-processor.middleware.annotate/merge-col-metadata` then uses `"nil"`.

That said, it does not make sense to test this for undefined metric.

**Review by metamben — APPROVED** [review]
I think this is good for now.
