### PR TITLE
fix `ChartSettingInputNumeric` not accepting decimals on safari

### LINKED ISSUE #28402: Safari Browser doesn't allow input of decimal numbers in multiply by a number formatting field
**Describe the bug**
Safari Browser doesn't allow input of decimal numbers in multiply by a number formatting 

**To Reproduce**
Make sure you are on Safari Browser:

1. Go to New -> Question -> Orders -> Visualize
2. Click on Total Column -> Column Formatting

image

3. Try to add a decimal value to the `Multiply by a number` field:

image

**Expected behavior**
I am able to insert decimal values like `0.10`

**Information about your Metabase Installation:**

Able to replicate on both 1.45.2.1 and `master`

### PR DESCRIPTION
**Pull request by EmmadUsmani**
Closes https://github.com/metabase/metabase/issues/28402

### Description

Decimals were not being accepted on numeric inputs for column settings in Safari. Safari handles typing a `.` character into a input with `type="number"` differently than Firefox and Chrome. The latter two will trigger the change event on the next digit input after the `.` with the correct value. Safari will instead trigger the input with an empty string as the value.

image
image

To fix this issue, we made this input of `type="text"` instead, and adding the correct parsing and validation to accommodate this change.

### How to verify

1. New question -> Orders
2. Click on a column settings for a numeric field like tax
3. Go the "multiply by a number" field, and confirm it can accept a decimal on Safari.

### Demo

https://github.com/metabase/metabase/assets/37751258/9aced495-1154-494c-a4f3-9160da9a98bd

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.tsx [hunk 1]
```diff
@@ -14,20 +16,25 @@ const ChartSettingInputNumeric = ({
   value,
   ...props
 }: ChartSettingInputProps) => {
-  const [internalValue, setInternalValue] = useState(value);
+  const [internalValue, setInternalValue] = useState(value?.toString() ?? "");
```
Comment (EmmadUsmani) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.tsx:19]: The root cause of this bug was that Safari doesn't now allow decimals in inputs with `type="number"`. Below we changed that to `type="text"`, and here we are now storing the internal value as a string to match the change in input type.

File: frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.tsx [hunk 2]
```diff
@@ -14,20 +16,25 @@ const ChartSettingInputNumeric = ({
...
-      type="number"
+      type="text"
       {..._.omit(props, "onChangeSettings")}
-      error={!!internalValue && isNaN(internalValue)}
+      error={internalValue !== "" && isNaN(Number(internalValue))}
       value={internalValue}
       onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
-        const num = parseFloat(e.target.value);
-        setInternalValue(num);
+        const everyCharValid = e.target.value
```
Comment (EmmadUsmani) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.tsx:28]: A side effect of changing the `type` to `"text"` is that `"text"` inputs be default allow any character to be typed. Here we prevent that  with this validation logic.

File: frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.tsx [hunk 3]
```diff
@@ -14,20 +16,25 @@ const ChartSettingInputNumeric = ({
...
+          .split("")
+          .every(char => ALLOWED_CHARS.includes(char));
+
+        if (everyCharValid) {
+          setInternalValue(e.target.value);
+        }
       }}
       onBlur={(e: React.ChangeEvent<HTMLInputElement>) => {
-        const num = parseFloat(e.target.value);
+        const num = e.target.value !== "" ? Number(e.target.value) : Number.NaN;
```
Comment (EmmadUsmani) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.tsx:37]: `parseFloat` allows invalid inputs with multiple decimals, wheras `Number` returns `NaN` for them.

Screenshot 2023-08-09 at 10 40 20 AM

**Review by alxnddr — APPROVED** [review]
It also lets users start typing negative numbers with `-` 👏
