### PR TITLE
Static Viz Line/Area/Bar Should now respect set Y-axis min/max

### LINKED ISSUE #27927: Static viz doesn't respect y-axis range
**Describe the bug**
A cousin of https://github.com/metabase/metabase/issues/20559, when using a custom y-axis range, static viz won't respect it

**Logs**
NA

**To Reproduce**
1) New->question->Orders table->sum of total group by Product category. Save it
2) tweak y-axis
3) Add the question to the dashboard
4) Add a subscription and test it
5) see that the custom axis are not there

**Expected behavior**
Have the same axis in the email sub as in the chart

**Screenshots**
See chart
image

See subscription
image

**Information about your Metabase Installation:**
- Metabase version: 1.45.2.1
- 
**Severity**
P3

**Additional context**
NA

### PR DESCRIPTION
**Pull request by adam-james-v**
The values for y-axis min and max are available to the static-viz js, it is just a matter of pulling them into the y domain calculations.

This PR also adds a rendering test to the backend unit tests to confirm that the setting is respected through the render pipeline.

Fixes: #27927

y-axis settings:
image

Render before this fix:
image

Render after this fix:
image

### CODE REVIEW

File: frontend/src/metabase/static-viz/components/XYChart/utils/scales.ts [hunk 1]
```diff
@@ -101,13 +103,15 @@ const calculateYDomain = (
   const maxValue = max(values);
 
   return [
-    Math.min(0, minValue, goalValue ?? 0),
-    Math.max(0, maxValue, goalValue ?? 0),
+    Math.min(0, minValue, setMinValue ?? 0, goalValue ?? 0),
```
Comment (WiNloSt) [inline frontend/src/metabase/static-viz/components/XYChart/utils/scales.ts:106]: I think this might be wrong. `Math.min` will return the minimum value from any of the parameters.

As I understand the `min` and `max` viz settings should either (not sure what's the behaviors are at the moment):
1. Don't allow the chart scale to go beyond these set values
2. set the chart scale to exactly these values (I don't think this is the case though)

If it's 1) then it's kind of like if the result from `Math.min(0, minValue, goalValue ?? 0)` is less than `setMinValue` uses `setMinValue` instead. Similarly, if `Math.max(0, maxValue, goalValue ?? 0)` is more than `setMaxValue` uses `setMaxValue` instead.

In either case, just making the `min` and `max` values one of the argument of `Math.min` and `Math.max` sounds wrong.

**Review by WiNloSt — CHANGES_REQUESTED** [review]
I think the logic is a bit wrong, other than that, the change looks okay.

File: frontend/src/metabase/static-viz/components/XYChart/utils/scales.ts (hunk 1 above)
Comment (WiNloSt) [reply frontend/src/metabase/static-viz/components/XYChart/utils/scales.ts:106]: You are definitely right. Sounds good matching this behavior with the app, it's just not what I expected initially. I thought we should let users set whatever they want for their charts, but seems we prevent them from shooting themselves in the foot in a lot of places too.

File: frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx [hunk 2]
```diff
@@ -62,7 +62,14 @@ export const XYChart = ({
     series = calculateStackedItems(series);
   }
 
-  const yDomains = calculateYDomains(series, settings.goal?.value);
+  const setMinValue = settings.visualization_settings["graph.y_axis.min"];
```
Comment (WiNloSt) [inline frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx:65]: I was thinking about this yesterday, but forgot to comment. `setMinValue` sounds more like a function than a value. I know `minValue` also doesn't convey the exact same thing. We use `minValue` in other places (viz) to say it's the min value from the series, not the settings.

So I'm not totally confident about the suggestion, but something along the line of `minValueSetting` should do. What do you think?

**Review by WiNloSt — APPROVED** [review]
FE change looks simple and easy to follow with one small comment.

File: frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx (hunk 2 above)
Comment (adam-james-v) [reply frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx:65]: Yea, that's a good call. thanks :)
