### PR TITLE
Fix empty state icon in activity page misalignment

### LINKED ISSUE #18960: Icon on empty activity page is misaligned
The icon shown on the activity page when there is no activity to show is misaligned.

image

http://localhost:3000/activity

image

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes #18960

## What
Fix the empty icon state icon misalignment on activity page.

### Before the fix
image

### After the fix
image

## Why
- It's because <Card /> has a line-height set to `24px` which throw things off.
- I set the `line-height` inline because there's seem to only be 2 places that use `.QuestionCircle` class so far. And while there's a class named `text-unspaced` that set `line-height: normal;` I don't think that represents what we want to do here, that's why I inlined it.
- And after observing the card, there's no `margin-bottom` set, so I added it to make the text look center-aligned.

## Reproduction steps
I couldn't find a way to enforce an empty state in activity page so I change https://github.com/metabase/metabase/blob/c52c6b9ef33928768fc95f62b097de0fd77cd88d/frontend/src/metabase/home/containers/ActivityApp.jsx#L61

to

```ts
<Activity {...this.props} activity={[]} />
```

### CODE REVIEW

File: frontend/src/metabase/home/components/Activity.jsx [hunk 1]
```diff
@@ -528,8 +528,13 @@ export default class Activity extends Component {
           <div className="full flex flex-column">
             <div className="">
               {activity.length === 0 ? (
-                <div className="flex flex-column layout-centered mt4">
-                  <span className="QuestionCircle">!</span>
+                <div className="flex flex-column layout-centered my4">
```
Comment (WiNloSt) [inline frontend/src/metabase/home/components/Activity.jsx:531]: Change `mt4` to `my4`.

`mt4`:
```css
margin-top: var(--margin-4);
```

`my4`:
```css
margin-top: var(--margin-4);
margin-bottom: var(--margin-4);
```

File: frontend/src/metabase/home/components/Activity.jsx [hunk 2]
```diff
@@ -528,8 +528,13 @@ export default class Activity extends Component {
...
+                  <span
+                    className="QuestionCircle"
+                    style={{ lineHeight: "normal" }}
```
Comment (WiNloSt) [inline frontend/src/metabase/home/components/Activity.jsx:534]: Set `line-height` to normal to counter the `line-height` set by the `<Card />` component.

Comment (daltojohnso) [reply frontend/src/metabase/home/components/Activity.jsx:534]: My inclination is we put `line-height: normal` in the `.QuestionCircle` rule found in `metabase/css/home.css`. The only other place we use the `QuestionCircle` class is in the dashboard empty state and it seems like it could theoretically be affected by a similar issue where some parent component (arguably erroneously) sets a `line-height` that its children inherit. And that way you can avoid the in-lined styling.

**Review by daltojohnso — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/home/components/Activity.jsx (hunk 2 above)
Comment (WiNloSt) [reply frontend/src/metabase/home/components/Activity.jsx:534]: Makes sense.

File: frontend/src/metabase/css/home.css [hunk 3]
```diff
@@ -11,6 +11,7 @@
   border-radius: 99px;
   border: 3px solid currentcolor;
   text-align: center;
+  line-height: normal;
```
Comment (WiNloSt) [inline frontend/src/metabase/css/home.css:14]: @daltojohnso Fixed https://github.com/metabase/metabase/pull/20820#discussion_r818985025

**Review by daltojohnso — APPROVED** [review]

**Comment by WiNloSt** [comment]
@metabase-bot backport release-x.42.x
