### PR TITLE
Make "Invite someone" button not overlapping with other elements

### LINKED ISSUE #16350: "Invite someone" button overlaps activate/deactivate radio buttons on small screen widths
**To Reproduce**
1. Go to Admin -> People
2. Reduce width of screen

image

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes #16350

There is some notable space between the button and content below it due to how I make the button a flex item, since flex and floating siblings don't play nice.

### Before
localhost_3000_admin_people (2)

### After
localhost_3000_admin_people (3)

### Before
localhost_3000_admin_people

### After
localhost_3000_admin_people (1)

### CODE REVIEW

File: frontend/src/metabase/components/AdminPaneLayout.jsx [hunk 1]
```diff
@@ -12,28 +14,33 @@ const AdminPaneTitle = ({
...
-        {buttonText}
-      </Button>
-    )}
-    {headingContent && <React.Fragment>{headingContent}</React.Fragment>}
-    {title && <h2 className="PageTitle">{title}</h2>}
-    {description && <p className="text-measure">{description}</p>}
-  </section>
-);
+}) => {
+  const buttonClassName = "ml-auto flex-no-shrink";
```
Comment (WiNloSt) [inline frontend/src/metabase/components/AdminPaneLayout.jsx:18]: - `ml-auto` (margin-left: auto) for pushing the button to the right of the screen
- `flex-no-shrink` (flex-shrink: 0) to not allow the button text to wrap

File: frontend/src/metabase/components/AdminPaneLayout.jsx [hunk 2]
```diff
@@ -12,28 +14,33 @@ const AdminPaneTitle = ({
...
+        {buttonText && buttonAction && (
+          <Button
+            className={buttonClassName}
+            primary={!buttonDisabled}
+            disabled={buttonDisabled}
+            onClick={buttonAction}
+          >
+            {buttonText}
+          </Button>
+        )}
```
Comment (WiNloSt) [inline frontend/src/metabase/components/AdminPaneLayout.jsx:38]: Move `Link` and `Button` to be after `headingContent` and `title` as they're now parts of the same flex container as `headingContent` and `title`.

Previously they were placed at the start to avoid being on a different line as `headingContent` and `title` and `float: right` will make the button float on the right.

The new code will now look more like the actual UI.

File: frontend/src/metabase/components/AdminPaneLayout.styled.jsx [hunk 3]
```diff
@@ -0,0 +1,13 @@
+import styled from "@emotion/styled";
+
+export const Container = styled.section`
+  padding-left: 1rem;
+  padding-right: 1rem;
+`;
```
Comment (WiNloSt) [inline frontend/src/metabase/components/AdminPaneLayout.styled.jsx:6]: The previous `section` has `px2` as a class.

File: frontend/src/metabase/components/AdminPaneLayout.styled.jsx [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+
+export const HeadingContainer = styled.div`
+  display: flex;
+  flex-wrap: wrap;
```
Comment (WiNloSt) [inline frontend/src/metabase/components/AdminPaneLayout.styled.jsx:10]: Allow the button to wrap.

File: frontend/src/metabase/components/AdminPaneLayout.styled.jsx [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+  align-items: baseline;
+  gap: 0 1rem;
```
Comment (WiNloSt) [inline frontend/src/metabase/components/AdminPaneLayout.styled.jsx:12]: [`gap` is still not fully supported](https://caniuse.com/?search=gap) (88%), but I think it's a good compromise than trying to mess around with margin and padding.

## This is what it will look like when browsers don't support `gap`
image

## This is when it's supported
image

**Review by daltojohnso — APPROVED** [review]
