### PR TITLE
Fix button group breaking

### LINKED ISSUE #50038: Little cosmetic bug in GUI editor when joining tables with names of different lenghts
### Describe the bug

When a short-named table is joined to a table that has a longer name and the table box name is larger, there's a small cosmetic bug with the editor
Image

### To Reproduce

1. Have a table with a long name and join it to a table with a shorter name

### Expected behavior

the account one in this case should adjust 

### Logs

_No response_

### Information about your Metabase installation

```JSON
- master
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/50038

### Description

Does some small style changes to allow join picker buttons for long table names to look less broken.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Create two questions with long names
2. New -> Question -> One of the questions 
3. Join -> The other question

Make sure the buttons don't look disjointed and broken.

##### Before
Screenshot 2024-11-15 at 14 53 47

##### After 

Screenshot 2024-11-15 at 14 53 40

### CODE REVIEW

File: frontend/src/metabase/querying/notebook/components/JoinStep/JoinTablePicker/JoinTablePicker.tsx [hunk 1]
```diff
@@ -92,6 +92,6 @@ const CONTAINER_STYLE = {
 
 const RIGHT_CONTAINER_STYLE = {
   width: 37,
-  height: 37,
+  height: "100%",
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/notebook/components/JoinStep/JoinTablePicker/JoinTablePicker.tsx:95]: :x: We need to change the height of the button, not its container.
Otherwise not the entire "blue area" is interactive.

image

**Review by kamilmielnik — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/querying/notebook/components/JoinStep/JoinTablePicker/JoinTablePicker.tsx (hunk 1 above)
Comment (kamilmielnik) [reply frontend/src/metabase/querying/notebook/components/JoinStep/JoinTablePicker/JoinTablePicker.tsx:95]: And let's fix this issue for data source as well

image

Comment (kamilmielnik) [reply frontend/src/metabase/querying/notebook/components/JoinStep/JoinTablePicker/JoinTablePicker.tsx:95]: Please pay attention to the icon on left-hand side (both cases) - it needs to be vertically centered, and text has to go on the right of it

Comment (romeovs) [reply frontend/src/metabase/querying/notebook/components/JoinStep/JoinTablePicker/JoinTablePicker.tsx:95]: > We need to change the height of the button, not its container.

Good catch. Off course the whole button had a `cursor: pointer` applied so it looked like it worked. Fixed it in 1577a79bc6d15ff2f79bb70b4bca4bb41cd37610

> Please pay attention to the icon on left-hand side (both cases) - it needs to be vertically centered, and text has to go on the right of it

It already does (in this branch) on all browsers on my machine.
Screenshot 2024-11-16 at 00 25 52

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js [hunk 2]
```diff
@@ -2357,3 +2357,82 @@ describe("issue 48829", () => {
     modal().should("not.exist");
   });
 });
+
+describe("issue 50064", () => {
```
Comment (kamilmielnik) [inline e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:2361]:
```suggestion
describe("issue 50038", () => {
```

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js [hunk 3]
```diff
@@ -2357,3 +2357,82 @@ describe("issue 48829", () => {
...
+    });
+  });
+
+  function assertEqualHeight(selector, otherSelector) {
+    selector.invoke("outerHeight").then(height => {
+      otherSelector.invoke("outerHeight").should("eq", height);
+    });
+  }
+
+  it("should not break data source and join source buttons when the source names are too long (metabase#50064)", () => {
```
Comment (kamilmielnik) [inline e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:2419]:
```suggestion
  it("should not break data source and join source buttons when the source names are too long (metabase#50038)", () => {
```

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js [hunk 4]
```diff
@@ -2357,3 +2357,82 @@ describe("issue 48829", () => {
...
+          { visitQuestion: true },
+        );
+      });
+    });
+  });
+
+  function assertEqualHeight(selector, otherSelector) {
+    selector.invoke("outerHeight").then(height => {
+      otherSelector.invoke("outerHeight").should("eq", height);
+    });
```
Comment (kamilmielnik) [inline e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:2416]: This is possibly flaky, let's verify it empirically: https://github.com/metabase/metabase/actions/runs/11888570003

**Review by kamilmielnik — APPROVED** [review]
:+1:

File: e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js (hunk 4 above)
Comment (romeovs) [reply e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js:2416]: Seems fine!
