### PR TITLE
[QP] Handle Snowflake tables with UUID columns more gracefully

### LINKED ISSUE #71595: Snowflake tables with UUID columns fail to sync: "no Fields associated with it"
## Describe the bug

When a Snowflake table contains a column with the native `UUID` data type (introduced in Snowflake in 2024), Metabase fails to sync any fields for that table. The table appears in the Metabase UI but shows the error: **"Table 'TABLE_NAME' has no Fields associated with it."**

All columns in the table are affected — including non-UUID columns (e.g., VARCHAR) — because the sync exception aborts the entire table's field sync.

## To Reproduce

**REPRODUCED**

1. In Snowflake, create a table with a UUID column:
```sql
CREATE TABLE SUCCESS_REPROS.PUBLIC.PYL_61431 (uuid1 UUID, uuid2 VARCHAR, description VARCHAR);
```

2. Insert sample data:
```sql
INSERT INTO SUCCESS_REPROS.PUBLIC.PYL_61431 (uuid1, uuid2, description) VALUES
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'both uuid'),
('b1ffc2a0-1d2e-4f3a-9c8b-7dd0ce491b22', 'b1ffc2a0-1d2e-4f3a-9c8b-7dd0ce491b22', 'both uuid'),
('c2aad3b1-2e3f-4a4b-ad9c-8ee1df5a2c33', 'not-a-uuid-just-text', 'uuid col has uuid, varchar has text'),
('d3bbe4c2-3f40-4b5c-bead-9ff2e06b3d44', '12345', 'uuid col has uuid, varchar has number string'),
('e4ccf5d3-4051-4c6d-cfbe-a003f17c4e55', '', 'uuid col has uuid, varchar is empty');
```

3. Add the Snowflake database to Metabase and wait for sync to complete.
4. Navigate to the table — see error: **"Table 'PYL_61431' has no Fields associated with it."**

## Expected behavior

- UUID columns should be coerced to a field type Metabase can process (e.g., text)
- Non-UUID fields (VARCHAR, etc.) should still be synced and visible even if the UUID type cannot be handled

### Sync error (during `sync-fields` step):

```
ERROR metabase.sync.fetch-metadata Error while fetching metadata with 'table-fields-metadata',
java.sql.SQLException: An SQLException was provoked by the following failure:
java.lang.IllegalArgumentException: No enum constant net.snowflake.client.jdbc.SnowflakeType.UUID,
    at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:82),
    at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:42),
    at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:39),
    at com.mchange.v2.c3p0.impl.NewPooledConnection.handleThrowable(NewPooledConnection.java:493),
    at com.mchange.v2.c3p0.impl.NewProxyResultSet.next(NewProxyResultSet.java:1141),
    at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__97218$fn__97219.invoke(common.clj:43),
    at clojure.core$repeatedly$fn__6556.invoke(core.clj:5202),
    at clojure.lang.LazySeq.force(LazySeq.java:50),
    at clojure.lang.LazySeq.realize(LazySeq.java:89),
    at clojure.lang.LazySeq.seq(LazySeq.java:106),
    at clojure.lang.RT.seq(RT.java:555),
    at clojure.core$seq__5488.invokeStatic(core.clj:139),
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24),
    at clojure.core.protocols$fn__8266.invokeStatic(protocols.clj:74),
    at clojure.core.protocols$fn__8266.invoke(protocols.clj:74),
    at clojure.core.protocols$fn__8207$G__8202__8220.invoke(protocols.clj:13),
    at clojure.core$reduce.invokeStatic(core.clj:6965),
    at clojure.core$reduce.invoke(core.clj:6947),
    at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__97218.reduce(common.clj:39)

WARN metabase.sync.fetch-metadata Could not fetch fields from table 599
```

### Frontend query error (when attempting to view the table):

```
ERROR metabase.query-processor.middleware.catch-exceptions Error processing query:
Table 'PYL_61431' has no Fields associated with it.
{:database_id 13,
 :parameterized false,
 :started_at #t "2026-03-27T19:33:24.780359716Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error preprocessing query in #'metabase.query-processor.middleware.add-implicit-clauses/add-implicit-clauses: Table 'PYL_61431' has no Fields associated with it.",
   :stacktrace
   ["--> query_processor.preprocess$preprocess$fn__82367$fn__82368.invoke(preprocess.clj:147)"
    "query_processor.preprocess$preprocess$fn__82367.invoke(preprocess.clj:121)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:223)"
    "query_processor.preprocess$preprocess.invokeStatic(preprocess.clj:119)"
    "query_processor.preprocess$preprocess.invoke(preprocess.clj:114)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:45)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__97196$handle_audit_app_internal_queries__97197$fn__97198.invoke(handle_audit_queries.clj:143)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__80510.invoke(enterprise.clj:131)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__88518.invoke(process_userland_query.clj:185)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__88578.invoke(catch_exceptions.clj:139)"
    "query_processor$process_query$fn__88630.invoke(query_processor.clj:81)"
    "query_processor.setup$do_with_canceled_chan$fn__81970.invoke(setup.clj:194)"
    "query_processor.setup$do_with_database_local_settings$fn__81965.invoke(setup.clj:188)"
    "query_processor.setup$do_with_driver$fn__81952$fn__81955.invoke(setup.clj:173)"
    "driver$do_with_driver.invokeStatic(driver.clj:54)"
    "driver$do_with_driver.invoke(driver.clj:49)"
    "query_processor.setup$do_with_driver$fn__81952.invoke(setup.clj:172)"
    "query_processor.setup$do_with_metadata_provider$fn__81944$fn__81947.invoke(setup.clj:148)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:200)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:186)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:193)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:186)"
    "query_processor.setup$do_with_metadata_provider$fn__81944.invoke(setup.clj:147)"
    "query_processor.setup$do_with_resolved_database$fn__81936.invoke(setup.clj:125)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:240)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:223)"
    "query_processor$process_query.invokeStatic(query_processor.clj:79)"
    "query_processor$process_query.invoke(query_processor.clj:72)"
    "query_processor.api$run_streaming_query$fn__118279.invoke(api.clj:89)"
    "query_processor.streaming$_streaming_response$fn__71445$fn__71446$fn__71447.invoke(streaming.clj:244)"
    "query_processor.streaming$_streaming_response$fn__71445$fn__71446.invoke(streaming.clj:242)"
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:215)"
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:202)"
    "query_processor.streaming$_streaming_response$fn__71445.invoke(streaming.clj:239)"
    "server.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:132)"
    "server.streaming_response$do_f_STAR_.invoke(streaming_response.clj:130)"
    "server.streaming_response$do_f_async$task__63796.invoke(streaming_response.clj:163)"],
   :error_type :qp}]}
```

## Information about your Metabase installation

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:149.0) Gecko/20100101 Firefox/149.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "snowflake",
      "h2",
      "clickhouse",
      "sqlserver"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2026-03-11",
      "tag": "v1.59.2.4",
      "hash": "ff4efd6"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.15 (Debian 15.15-1.pgdg13+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.8"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.10+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.10+7-LTS",
    "os.name": "Linux",
    "os.version": "6.17.8-orbstack-00308-g8f9c941121b1",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

## Severity

P1: Entire table doesn't load due to incompatible field. Any Snowflake table with a UUID column becomes completely unusable. The workaround is to cast UUID columns to VARCHAR in a view, which defeats the purpose of Snowflake's native UUID type.

### PR DESCRIPTION
**Pull request by bshepherdson**
closes #71595
Closes QUE2-476.

### Description

An upstream Snowflake JDBC driver issue causes an exception to be thrown
because the UUID column type is not present in an enum.

This adds logic to fall back to the more generic `SELECT *` sync mode if
this error occurs during a sync.

### How to verify

Try to sync a Snowflake table containing a UUID column; see #71595 for an example table and data.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- ~~If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)~~

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#72034** <a href="https://app.graphite.com/github/pr/metabase/metabase/72034?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/metabase/metabase/72034?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj [hunk 1]
```diff
@@ -441,6 +441,39 @@
                #_{:clj-kondo/ignore [:deprecated-var]}
                (is (= #{} (driver/describe-table-fks :snowflake (mt/db) dynamic-table)))))))))))
 
+(deftest ^:sequential describe-table-fields-uuid-column-test
+  (mt/test-driver :snowflake
+    (testing "Snowflake tables with UUID columns should sync successfully (#71595)"
+      (let [db-name    (#'driver.snowflake/db-name (mt/db))
+            table-name (str "uuid_test_" (u.random/random-name))]
```
Comment (metamben) [inline modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj:448]: I wonder if we should include a timestamp in the name so that when things go horribly wrong and the finally block doesn't clean up, we leave a table behind whose age can be guessed. this might be useful for manual cleanup.

**Review by metamben — APPROVED** [review]

**Comment by prmoore77** [comment]
🚀🚀🚀🚀🚀
