### PR TITLE
Last Used Param Value doesn't fill in with default value if cleared

### LINKED ISSUE #46368: Keys with null values are missing in `last_used_param_values`
### Describe the bug

https://github.com/user-attachments/assets/946697d0-b31e-4388-8175-a57b1e353684

### To Reproduce

1. Create a question based on Orders table and add it to a dashboard
2. Create a non-required dashboard filter with default value and connect it to the question, save dashboard
3. Clear filter value
4. Close the dashboard 
5. Open it again (e.g. from command palette)

Actual: filter value is the default value
Expected: filter value should be empty

### Information about your Metabase installation

master, 683faf64e9122ee964e2740b29246e755e02140a

### Severity

P2

### Additional context

Original report: https://metaboat.slack.com/archives/C0645JP1W81/p1722447097137469?thread_ts=1722436543.931399&cid=C0645JP1W81

Related product doc: https://www.notion.so/metabase/Preserve-dashboard-filter-states-for-users-0f89ff0da0c24026a3692b0f9d704fed
Related PR: #40415

It looks like `last_used_param_values` do not include keys with `null` values (GET `/api/dashboard/:id`).

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes #46368

The Last used parameter value is cleared when the frontend sends `nil` as the parameter's value. This works except in cases where a user clears a parameter with a default value. In this case, we want to indicate that the parameter is cleared, so we store `nil` in the appdb in such a case.

### CODE REVIEW

File: src/metabase/query_processor/dashboard.clj [hunk 1]
```diff
@@ -142,12 +139,14 @@
                                         (map (fn [[param-id param]]
                                                [param-id (dissoc param :default)]))
                                         (:resolved-params dashboard))
-        request-param-id->param   (into {} (map (juxt :id identity)) request-params)
+        ;; ignore default values in request params as well. (#20516)
+        request-param-id->param   (into {} (map (juxt :id identity)) (for [param request-params]
+                                                                       (dissoc param :default)))
```
Comment (metamben) [inline src/metabase/query_processor/dashboard.clj:144]:
```suggestion
        request-param-id->param   (into {} (map (juxt :id #(dissoc % :default))) request-params)
```

**Review by metamben — APPROVED** [review]
LGTM, but a test showing that the problem is solved (i.e., demonstrating that having the entry with `nil` in the DB actually makes a difference) would be nice.
