### PR TITLE
[P0] Fix filters don't work for public and embedded questions

### LINKED ISSUE #17019: Questions filters does not work in Embedded/Public
**Describe the bug**
Questions filters does not work in Embedded/Public (it works via dashboards). Regression in 0.40.0

**To Reproduce**
1. Native query > Sample Dataset > `select {{filter}}` - just leave it as Text filter - save question
2. View via Public Sharing or Embedded with Editable filter
3. Try to input anything into the filter - it gets reset/removed - no errors in the browser console

https://user-images.githubusercontent.com/1447303/125486931-8f4bf58e-56bc-480e-832e-c62a3fcf1327.mp4

**Information about your Metabase Installation:**
Metabase 0.40.0

### PR DESCRIPTION
**Pull request by kulyk**
Fixes #17019, a regression caused by #16765 and #16795 (fixed missing default parameters for public questions)

**Explanation**
When a public / embedded question page opens, it retrieves info about parameters and their default values. Once this info is fetched, we apply default parameter values and rerun the query.

Earlier, `PublicQuestion` had a [`setParameterValue` method](https://github.com/metabase/metabase/blob/f538050317f999c5d7be4413985ffd389a83fd76/frontend/src/metabase/public/containers/PublicQuestion.jsx#L126) accepting `parameterId` and `parameterValue`. It was updating a dictionary with an updated parameter and instantly triggered a new query run, so we display relevant data.

Looks like it didn't work quite well with many parameters. My guess is that there was a race condition. Let's say we have two parameters: "Country" and "Source". They would call `setParameterValue` twice and there is no guarantee, the second call will use a parameter from the first one. Example:

1. `setParameterValue` is called with "Country" filter arguments
2. React`setState` is called with "Country" filter arguments
2. `setParameterValue` is called with "Source" at the same time
3. React`setState` is called with "Source" filter arguments
4. One of the `setState` calls probably overwrites another one (see screenshots from #7120)

So `setParameterValue` method [was refactored](https://github.com/metabase/metabase/blob/961caedc9983dfef7e25dfdfb0e18c9bde02dca4/frontend/src/metabase/public/containers/PublicQuestion.jsx#L126) to update all the filters in a single batch.

The problem is that when parameters are updated individually, i.e. when you click them, it still uses the `setParameterValue(id, value)` notation, so we can't set filter value appropriately.

This PR fixes the issue in the most straightforward way I found: by adding an extra `setMultipleParameterValues` method and reverting `setParameterValue` to its previous state (I guess you wouldn't expect `setParameterValue` to handle > 1 parameter anyway, as the name is in the singular form). Also, `setParameterValue` accepts `parameterId` and `parameterValue` for internal questions, so I think it's better to keep things more consistent.

### To Verify

1. Ask a question > Native Question > Sample Dataset
2. Enter `select * from PRODUCTS where {{filter}}`
3. In the right sidebar, set `{{ filter }}` to be "Field Filter" and map it to Products > Category
4. Save question
5. In the bottom right corner, click the "Sharing" icon (an arrow)
6. Open the share URL
7. Try to change the filters. Each time you change a filter, it should be properly represented on the UI and the query has to rerun with the new filters applied

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/125565666-6c57584a-7635-44ef-9ae9-07be88f41a0f.mov

**After**

https://user-images.githubusercontent.com/17258145/125565709-5b4ff582-61bf-43c6-bb51-d856517e3a76.mov

### CODE REVIEW

File: frontend/src/metabase/public/components/EmbedFrame.jsx [hunk 1]
```diff
@@ -33,6 +33,9 @@ type Props = {
   parameters?: Parameter[],
   parameterValues?: { [key: string]: string },
   setParameterValue: (id: string, value: string) => void,
+  setMultipleParameterValues: (parameterValues: {
+    [key: string]: string,
+  }) => void,
```
Comment (kulyk) [inline frontend/src/metabase/public/components/EmbedFrame.jsx:38]: We don't use flow types, but I guess it would be handy to have the definition here, just to make the difference from `setParameterValue` a bit more explicit

**Review by gusaiani — APPROVED** [review]
👍

Do you think this change could allow `syncQueryParamsWithURL` to be greatly simplified? 🤔

`syncForPublicQuestion` and `syncForInternalQuestion` are very similar with one fundamental difference: one updates the state after every iteration and the other accumulates changes and updates state all at once.

I wonder if the change you introduce here allows those two functions to work the same way. (I can play with that later btw)

**Review by alxnddr — APPROVED** [review]
Works as expected. Thanks again for such a comprehensive explanation

**Comment by kulyk** [comment]
> Do you think this change could allow `syncQueryParamsWithURL` to be greatly simplified? 🤔
> 
> `syncForPublicQuestion` and `syncForInternalQuestion` are very similar with one fundamental difference: one updates the state after every iteration and the other accumulates changes and updates state all at once.
> 
> I wonder if the change you introduce here allows those two functions to work the same way. (I can play with that later btw)

Not sure, it still calls `setParamterValue` one by one for internal questions and in batch for public questions, there are just two different methods for that now. I'd vote for moving it to the higher level as described in #17034

**Comment by gusaiani** [comment]
> I'd vote for moving it to the higher level as described in #17034

@kulyk Sounds like a plan to me 👍

**Review by flamber — APPROVED** [review]
:tada: :rocket: LGTM
Guess we're doing fixes on master now and :cherries: to the branches? I'm just seeing a mix in some PRs, so just want to make sure it lands in x.40.x

**Comment by kulyk** [comment]
> Guess we're doing fixes on master now and 🍒 to the branches? I'm just seeing a mix in some PRs, so just want to make sure it lands in x.40.x

@flamber, correct. I'm merging this now and will follow up with a 🍒 PR
