### PR TITLE
Don't count app-db not setup errors in circuit breaker

### LINKED ISSUE #65294: app cannot startup with config file that sets sso settings
### Describe the bug

following https://github.com/metabase/metabase/pull/65208, having a config file like:

```yaml
version: 1
config:
  users:
    - first_name: Rene
      last_name: Descartes
      password: foobarbaz
      email: rene@example.com
  settings:
    enable-embedding-sdk: true
    jwt-enabled: true
```

The application will fail to startup:

```
2025-10-31 11:07:56,290 ERROR core.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Setting jwt-enabled is not enabled because feature :sso-jwt is not available {:description #object[metabase_enterprise.sso.settings$fn__109589$fn__109592 0x46b007ac "metabase_enterprise.sso.settings$fn__109589$fn__109592@46b007ac"], :database-local :never, :cache? true, :user-local :never, :init nil, :can-read-from-env? true, :default false, :name :jwt-enabled, :export? false, :type :boolean, :setter #object[clojure.core$partial$fn__5929 0x430d15f "clojure.core$partial$fn__5929@430d15f"], :enabled? nil, :encryption :no, :deprecated nil, :audit :getter, :getter #object[metabase_enterprise.sso.settings$fn__109589$fn__109590 0x60a548cc "metabase_enterprise.sso.settings$fn__109589$fn__109590@60a548cc"], :sensitive? false, :tag java.lang.Boolean, :on-change nil, :doc "When set to true, will enable JWT authentication with the options configured in the MB_JWT_* variables.\n        This is for JWT SSO authentication, and has nothing to do with Static embedding, which is MB_EMBEDDING_SECRET_KEY.", :include-in-list? true, :feature :sso-jwt, :namespace metabase-enterprise.sso.settings, :munged-name "jwt-enabled", :visibility :admin}
        at metabase.settings.models.setting$set_BANG_.invokeStatic(setting.clj:875)
        at metabase.settings.models.setting$set_BANG_.doInvoke(setting.clj:860)
        at clojure.lang.RestFn.invoke(RestFn.java:428)
        at metabase_enterprise.advanced_config.file.settings$eval652$fn__653.invoke(settings.clj:20)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase_enterprise.advanced_config.file$initialize_BANG_.invokeStatic(file.clj:268)
        at metabase_enterprise.advanced_config.file$initialize_BANG_.invoke(file.clj:253)
        at clojure.lang.Var.invoke(Var.java:382)
        at metabase.core.config_from_file$init_from_file_if_code_available_BANG_.invokeStatic(config_from_file.clj:17)
        at metabase.core.config_from_file$init_from_file_if_code_available_BANG_.invoke(config_from_file.clj:6)
        at metabase.core.core$init_BANG__STAR_.invokeStatic(core.clj:191)
        at metabase.core.core$init_BANG__STAR_.invoke(core.clj:151)
        at metabase.core.core$init_BANG_.invokeStatic(core.clj:229)
        at metabase.core.core$init_BANG_.invoke(core.clj:224)
        at metabase.core.core$start_normally.invokeStatic(core.clj:243)
        at metabase.core.core$start_normally.invoke(core.clj:235)
        at metabase.core.core$entrypoint.invokeStatic(core.clj:278)
        at metabase.core.core$entrypoint.doInvoke(core.clj:269)
        at clojure.lang.RestFn.invoke(RestFn.java:400)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:135)
        at clojure.lang.Var.applyTo(Var.java:707)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.core.bootstrap$_main.invokeStatic(bootstrap.clj:36)
        at metabase.core.bootstrap$_main.doInvoke(bootstrap.clj:29)
        at clojure.lang.RestFn.invoke(RestFn.java:400)
        at user$eval684.invokeStatic(NO_SOURCE_FILE:4)
        at user$eval684.invoke(NO_SOURCE_FILE:4)
        at clojure.lang.Compiler.eval(Compiler.java:7739)
        at clojure.lang.Compiler.eval(Compiler.java:7729)
        at clojure.lang.Compiler.eval(Compiler.java:7694)
        at clojure.core$eval.invokeStatic(core.clj:3232)
        at clojure.core$eval.invoke(core.clj:3228)
        at clojure.main$repl$read_eval_print__9248$fn__9251.invoke(main.clj:437)
        at clojure.main$repl$read_eval_print__9248.invoke(main.clj:437)
        at clojure.main$repl$fn__9257.invoke(main.clj:459)
        at clojure.main$repl.invokeStatic(main.clj:459)
        at clojure.main$repl_opt.invokeStatic(main.clj:523)
        at clojure.main$main.invokeStatic(main.clj:668)
        at clojure.main$main.doInvoke(main.clj:617)
        at clojure.lang.RestFn.invoke(RestFn.java:400)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:135)
        at clojure.lang.Var.applyTo(Var.java:707)
        at clojure.main.main(main.java:40)
2025-10-31 11:07:56,299 INFO core.core :: Metabase Shutting Down ...
```

### To Reproduce

The above

### Expected behavior

should startup

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

p1

### Additional context

We need setting values for some of the token check stuff (number of users, site uuid, etc) so we wait for that to be ready. The way we wait is to just throw errors. Following https://github.com/metabase/metabase/pull/65208 these errors go through the circuit breaker so those errors in startup count towards the window watching for errors and it shuts down further token checks.

We need to exclude these types of errors from the circuit breaker.

### PR DESCRIPTION
**Pull request by dpsutton**
Closes https://github.com/metabase/metabase/issues/65294

we want to not hammer the network when things are down. But during startup we don't need to circuit break these errors that we throw before the app-db is read

copying over the gist of the issue from #65294
during startup, there are assertions that the db is setup otherwise we don't check the tokens. These failures are caught in the normal course of business. But previously they were not counted in the circuit breaker. After https://github.com/metabase/metabase/pull/65208 they were, and then we would catch 10 exceptions during startup and close the circuit breaker, so then when the app db was ready, we wouldn't check a token there and fail startup.

Now those errors don't go through the circuit breaker.
I tried a few different ways, where the circuit breaker could see those errors and do `(.recordSuccess breaker)` which i hoped would reset the state. But this did not work. Ideally we could tell it not to care about these types of errors but it got a bit more frustrating than i had hoped. So just assert before we get to the circuit breaker and we are good to go.

note that there is an error checking layer underneath this so it doesn't throw errors into other code.

### CODE REVIEW

File: test/metabase/premium_features/token_check_test.clj [hunk 1]
```diff
@@ -125,7 +126,38 @@
     (testing "When connectivity is restored we get successful token checks"
       (reset! behavior :success)
       (Thread/sleep 100) ;; wait for circuit breaker to open back up
-      (is (= good-response (token-check/-check-token checker token))))))
+      (is (= good-response (token-check/-check-token checker token)))))
+  (testing "App db not setup yet does not invoke the circuit breaker (#65294)"
```
Comment (noahmoss) [inline test/metabase/premium_features/token_check_test.clj:130]: is there anything preventing these tests from being parallelized? maybe this test case should be broken out as a separate `deftest` & run in parallel?

File: src/metabase/premium_features/token_check.clj [hunk 2]
```diff
@@ -288,6 +288,11 @@
         (when *token-check-happening*
           (throw (ex-info "Token check is being called recursively, there is a good chance some `defenterprise` is causing this"
                           {:pass-thru true})))
+        ;; important to not count these errors against the circuit breaker. These are not the types of errors we need
+        ;; to circuit break. (#65294)
+        (when-not ((requiring-resolve 'metabase.app-db.core/db-is-set-up?))
```
Comment (noahmoss) [inline src/metabase/premium_features/token_check.clj:293]: is this to avoid a circular dep?

**Review by noahmoss — APPROVED** [review]

File: src/metabase/premium_features/token_check.clj (hunk 2 above)
Comment (dpsutton) [reply src/metabase/premium_features/token_check.clj:293]: great question. i wonder if at one point it was an now it no longer is?

Comment (dpsutton) [reply src/metabase/premium_features/token_check.clj:293]: so this seems like it just was always like this. i'm gonna leave it like so for now and clean this up soon. This needs to backport to 53 and i don't want to deal with module config allowing for this to see the app db module through 5 different versions.

**Review by sanex3339 — APPROVED** [review]
Tested locally
