### PR TITLE
Guard notification pool from exhaustion

### LINKED ISSUE #56379: Scheduled alerts not sent in Metabase despite task success
**Describe the bug**

Since upgrading to Metabase _v0.54.1_, scheduled alerts are not being sent. This issue affects both newly created alerts and those existing prior to the upgrade, across email and Slack notifications. In the **Troubleshooting > Tasks** section, the `notification-trigger` task shows a status of `"success"`, but no notifications are received. Manually triggering the alert using the "Send now" button works as expected.

Example payload for the scheduled alert:

```json
{
  "trigger_type": "notification-subscription/cron",
  "notification_subscription_id": 144,
  "cron_schedule": "0 04 * * * ? *",
  "notification_ids": [144]
}
```

**Logs**

No specific errors appear in logs. The `notification-trigger` task status is `"success"` but the notifications are not sent.

**To Reproduce**

1. Upgrade to Metabase _v0.54.1_.
2. Create a new alert or use an existing one.
3. Set the alert condition to "When this question has results."
4. Schedule the alert for a specific time.
5. Wait for the scheduled time — no notification is received.
6. Click "Send now" — notification is successfully sent.

**Expected behavior**

Scheduled alerts should send notifications via configured channels (email/Slack) at the scheduled time.

**Screenshots**

N/A

**Severity**

High — This is blocking scheduled alerting functionality.

**Additional context**

N/A

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-04-02",
      "tag": "v0.54.1",
      "hash": "774e5a3"
    },
    "settings": {
      "report-timezone": "UTC"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.5"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.6+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.6+7-LTS",
    "os.name": "Linux",
    "os.version": "6.6.72+",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### PR DESCRIPTION
**Pull request by qnkhuat**
Closes #56379

Our notification pools are exhausted if there are failure when sending notifications.
Even though we've guarded it by catching `Exception`, but there can be cased where it can gets Errors (Assertions).

image

So the fix is to catch `Throwable` instead.
I've also added self-healing to make sure whenever we enqueue a notification, there will be at least one thread to execute it.

### CODE REVIEW

File: src/metabase/notification/send.clj [hunk 1]
```diff
@@ -343,18 +354,10 @@
...
-                                 (send-notification-sync! notification))
-                               (catch InterruptedException _
-                                 (log/info "Notification worker interrupted, shutting down")
-                                 (throw (InterruptedException.)))
-                               (catch Exception e
-                                 (log/error e "Error in notification worker")))))))
+      (start-worker!))
     (fn [notification]
+      ;; ensure there is always a worker to handle the notification
+      (start-worker!)
```
Comment (qnkhuat) [inline src/metabase/notification/send.clj:360]: this is fine to call whenever we submit a notification because the pool is a fixed pool

File: src/metabase/notification/send.clj [hunk 2]
```diff
@@ -343,18 +354,16 @@
...
+      (start-worker!))
     (fn [notification]
+      ;; ensure there is always a worker to handle the notification
+      (while (< (.getActiveCount ^ExecutorService executor) pool-size)
+        (log/debugf "Not enough workers, starting a new one %d/%d"
+                    (.getActiveCount ^ExecutorService executor)
+                    pool-size)
+        (start-worker!)
+        ;; wait a bit for the worker to start
+        (Thread/sleep 10))
```
Comment (crisptrutski) [inline src/metabase/notification/send.clj:366]: Why do we need this wait? Does the active count of the executor not update synchronously?

How about instead doing `(dotimes [i (- pool-size (.getActiveCount executor))] ...) instead?

This is also proof against looping infinitely if something if the workers are instantly dying or something.

**Review by crisptrutski — APPROVED** [review]

File: src/metabase/notification/send.clj (hunk 2 above)
Comment (qnkhuat) [reply src/metabase/notification/send.clj:366]: nice, dotimes is better!

about the sleep, yea it's not updated synchronously.

File: src/metabase/notification/send.clj [hunk 3]
```diff
@@ -333,28 +332,36 @@
...
-                               (catch Exception e
-                                 (log/error e "Error in notification worker")))))))
+      (start-worker!))
     (fn [notification]
+      ;; ensure there is always a worker to handle the notification
+      (dotimes [_ (- pool-size (.getActiveCount ^ThreadPoolExecutor executor))]
+        (log/debugf "Not enough workers, starting a new one %d/%d"
+                    (.getActiveCount ^ThreadPoolExecutor executor)
+                    pool-size)
+        (start-worker!))
```
Comment (wotbrew) [inline src/metabase/notification/send.clj]: Now the worker loop only terminates on interrupt, is this really necessary?

Comment (qnkhuat) [reply src/metabase/notification/send.clj]: yea, this is just me being annoyed of this bug and want to be super-extra safe :D . I think it's almost always a no-op anyway.
