### PR TITLE
Fix wrong operator formatting in filter popover header

### LINKED ISSUE #27104: Wrong operator formatting in filter popover header
**Describe the bug**
"Count" is shown as "- Count"

**To Reproduce**
1. Sample Database > People
2. Summarize by Count, breakout by Longitude (auto-binned)
3. Click on "Filter" and select "Count"
image
4. Notice the extra "minus" or a dash symbol in front of "Count"

**Expected behavior**
When there is only an operator without the table prefix, do not display "-" in front of it

**Information about your Metabase Installation:**
local dev, Sample Database, H2, `master`, 5305c173dc631e0f2385b9399ac4ba5677e2c06d

**Severity**
P3, cosmetic

**Additional context**
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx#L56:L59

### PR DESCRIPTION
**Pull request by nemanjaglumac**
Fixes #27104

Adds reproduction for #27104
image

As a sanity check, this was the same E2E test before the fix was properly applied
Screenshot 2023-05-03 at 16 39 34

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30318)

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx [hunk 1]
```diff
@@ -54,8 +54,9 @@ export default function FilterPopoverHeader({
             pr2: !showOperatorSelectorOnOwnRow,
           })}
           title={
-            (field.table ? field.table.displayName() + " – " : "") +
-            field.displayName()
+            (field.table?.displayName()
+              ? field.table.displayName() + " – "
+              : "") + field.displayName()
```
Comment (nemanjaglumac) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx:59]: There is probably a more beautiful and idiomatic way to write this in JS.
But I wanted to first check if this is even acceptable idea?

Comment (WiNloSt) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx:59]: This looks fine to me. Although, I'm more curious about the expected behavior. From your screenshot


`Count` is a column on an aggregated result. I believe it's correct that we don't say `Count` belongs to any table, so that's why we left out the name right? Because if you filter before the summarize step all fields will be in this format `table_name – field_name`, since we can infer which fields belong to which table.

**Review by WiNloSt — APPROVED** [review]
Looks good to me.

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx:59]: We shouldn't have logic like this on the FE. It seems that we should call a proper `metabase-lib` method, like 
```
field.displayName({ includeTable: true }) 
```

Comment (ranquild) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx:59]: @nemanjaglumac could you check if that works for this case?

**Review by ranquild — CHANGES_REQUESTED** [review]
We need to use `metabase-lib` here

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx:59]: `field.displayName({ includeTable: true })` in this case returns `→ Count`.
So, we're still missing the `table.displayName` but printing the `→`

What would be the correct way to proceed? @ranquild 
Does this method from the `metabase-lib` need to be updated?

Comment (ranquild) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx:59]: @kulyk could you take a look at this thread please?

**Review by kulyk — APPROVED** [review]
Looks good to me, thanks for addressing the comments, Nemanja 🙏

**Comment by nemanjaglumac** [comment]
@kulyk I've just ran through this scenario once again and the problem is not fixed. The root seems to be running deeper into the `Table.ts`.

image

I'll add E2E repro.

**Review by ranquild — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30318)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kulyk and @nemanjaglumac)

___
*[`frontend/src/metabase-lib/metadata/Field.ts` line 135 at r3](https://reviewable.io/reviews/metabase/metabase/30318#-NURr9Xj-zw3xE07he3l:-NURr9Xj-zw3xE07he3m:b-agcrqq) ([raw file](https://github.com/metabase/metabase/blob/2cf62c53440e48322acf4b4e936f2f98a85b5f73/frontend/src/metabase-lib/metadata/Field.ts#L135)):*
> ```XML
>     let displayName = "";
> 
>     if (includeTable && this.table?.displayName) {
> ```

@nemanjaglumac could you explain this change? Does it mean that a table can be not `undefined` but not an instance of `metabase-lib/metadata/Table`?

**Review by nemanjaglumac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30318)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kulyk and @ranquild)

___
*[`frontend/src/metabase-lib/metadata/Field.ts` line 135 at r3](https://reviewable.io/reviews/metabase/metabase/30318#-NURr9Xj-zw3xE07he3l:-NUWvTiAEHSJAXrgjToA:b-6klzv5) ([raw file](https://github.com/metabase/metabase/blob/2cf62c53440e48322acf4b4e936f2f98a85b5f73/frontend/src/metabase-lib/metadata/Field.ts#L135)):*
<details><summary><i>Previously, ranquild (Alexander Polyankin) wrote…</i></summary><blockquote>

@nemanjaglumac could you explain this change? Does it mean that a table can be not `undefined` but not an instance of `metabase-lib/metadata/Table`?
</blockquote></details>

I think I used wrong logic here.
The table's `displayName` method is **always** defined, but when invoked can resolve to an empty string.

What I needed here was `this.table.displayName?.()` instead.

**Review by ranquild — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30318)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @kulyk and @nemanjaglumac)

___
*[`frontend/src/metabase-lib/metadata/Field.ts` line 135 at r3](https://reviewable.io/reviews/metabase/metabase/30318#-NURr9Xj-zw3xE07he3l:-NUWx_QU8vtP-8y8QJFH:b-kqj871) ([raw file](https://github.com/metabase/metabase/blob/2cf62c53440e48322acf4b4e936f2f98a85b5f73/frontend/src/metabase-lib/metadata/Field.ts#L135)):*
<details><summary><i>Previously, nemanjaglumac (Nemanja Glumac) wrote…</i></summary><blockquote>

I think I used wrong logic here.
The table's `displayName` method is **always** defined, but when invoked can resolve to an empty string.

What I needed here was `this.table.displayName?.()` instead.
</blockquote></details>

Yes, sounds good. Could you change that?

**Review by ranquild — APPROVED** [review]
