### PR TITLE
Fix model sigma icon

### LINKED ISSUE #54400: Models shouldn't be represented by the sigma icon
### Describe the bug

This model is called "Customers" and it should have a model icon next to it, not the sigma/sum icon.

Image

Image

Image

### To Reproduce

If you open up the filter modal, or the filter or summarize popovers in the notebook editor when using a model as a data source, you'll see a sigma icon when you'd expect a model icon.

### Expected behavior

It should be a model icon.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "databricks",
      "druid-jdbc",
      "postgres",
      "mongo",
      "redshift",
      "bigquery-cloud-sdk",
      "snowflake",
      "athena",
      "h2",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-02-26",
      "tag": "vUNKNOWN",
      "hash": "1071dbb"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/54400

How to verify:
- New -> Model -> Orders -> Save
- Editor -> Filter -> Verify that icons are correct (no sigma icon)

Screenshot 2025-06-04 at 20 13 09

### CODE REVIEW

File: frontend/src/metabase/common/utils/column-groups.ts [hunk 1]
```diff
@@ -7,6 +7,9 @@ export function getColumnGroupIcon(
   if (groupInfo.isSourceTable) {
     return "table";
   }
+  if (groupInfo.isSourceCard) {
+    return "table2";
```
Comment (ranquild) [inline frontend/src/metabase/common/utils/column-groups.ts:11]: This is the icon we use for cards in the notebook editor.

**Review by romeovs — APPROVED** [review]
