### PR TITLE
fix: Change pool acquireRetryAttemps to 0

### LINKED ISSUE #51176: Better handling of broken database connections
Context thread: https://metaboat.slack.com/archives/C010L1Z4F9S/p1733861342280199

Snowflake logging was updated to indicate each time an unauthorized database connection was attempted. This revealed a potential problem in our connection pool.

[This is the relevant document](https://www.mchange.com/projects/c3p0/#configuring_recovery)
What's going on: What we have are saved, configured databases in metabase where the credentials/account/etc changed out from under us and the database connection is no longer valid. This is not specific to snowflake.

By default our connection pool will retry getting a connection 30 times with a 1 second interval. It is during this internal c3p0 pool process that these snowflake logs are being generated. The exception is not surfaced to our code until after the final retry.
Our field values sync is particularly troublesome and seen in these logs because we try to get a new connection for each field and so we get minutes, or hours of retries.

Proposal 1: I think changing the pool to fail faster with an acquireRetryAttempts of  1 or 2 would be a good idea. It means that users will get faster feedback if their credentials have changed and our automated processes won't heat the world so much. The downside is that if a database is legitimately restarting, then queries during the restart wont continue to retry and will more likely fail.

Proposal 2: Verify the connection outside of the pool (same as we do when adding a db) before sync tasks and only proceed if it's successful.
The downside is that if users are trying to run queries /look at dashboards for these dbs the same retries will happen and they'll be sitting there for a 30+s until the pool surfaces an error.

Hotfix to quiet logging.
https://github.com/metabase/metabase/pull/51138

### PR DESCRIPTION
**Pull request by snoe**
Fixes: #51176

### CODE REVIEW

File: src/metabase/driver/sql_jdbc/connection.clj [hunk 1]
```diff
@@ -123,6 +123,10 @@ For setting the maximum, see [MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE](#mb_ap
   {;; only fetch one new connection at a time, rather than batching fetches (default = 3 at a time). This is done in
    ;; interest of minimizing memory consumption
    "acquireIncrement"             1
+   ;; Only retry once instead of the default of 30 (#51176)
+   ;; While a couple queries may fail during a reboot, this should allow quicker recovery and less spinning on outdated
+   ;; credentials
+   "acquireRetryAttempts"         1
```
Comment (metamben) [inline src/metabase/driver/sql_jdbc/connection.clj:129]: In what real world situations is this going to be better than `0`?

Comment (snoe) [reply src/metabase/driver/sql_jdbc/connection.clj]: Good question, changed to 0

File: src/metabase/driver/sql_jdbc/connection.clj [hunk 2]
```diff
@@ -123,6 +123,10 @@ For setting the maximum, see [MB_APPLICATION_DB_MAX_CONNECTION_POOL_SIZE](#mb_ap
   {;; only fetch one new connection at a time, rather than batching fetches (default = 3 at a time). This is done in
    ;; interest of minimizing memory consumption
    "acquireIncrement"             1
+   ;; Only retry once instead of the default of 30 (#51176)
+   ;; While a couple queries may fail during a reboot, this should allow quicker recovery and less spinning on outdated
+   ;; credentials
```
Comment (metamben) [inline src/metabase/driver/sql_jdbc/connection.clj:128]: This is out of date now.

**Review by metamben — APPROVED** [review]
