### PR TITLE
Closes VIZ-1145 row chart label cut off

### LINKED ISSUE #59507: Show values of data points on row charts doesn't show the value of the max
### Describe the bug

If you have a row chart, the max value of the row chart won't display its value if you set the option "show values on data points", while all other values will

### To Reproduce

1) create a sql question as
```
select 50 as value, 'a' as series
union all
select 40, 'b'
```
2) set it as a row chart
3) set to show the values of the the data points
4) see that the first row won't have a value
see
Image

### Expected behavior

We should show all the values from all the series

### Logs

NA

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-06-12",
      "tag": "v1.55.3",
      "hash": "73e60da"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.5"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "6.12.10-76061203-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #59507
Closes [VIZ-1145: Show values of data points on row charts doesn't show the value of the max](https://linear.app/metabase/issue/VIZ-1145/show-values-of-data-points-on-row-charts-doesnt-show-the-value-of-the)

### Description
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
Comment (lorem--ipsum) [inline frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx:1]: This change is unrelated, I made it to prevent an error in the console

File: frontend/src/metabase/visualizations/shared/components/RowChartView/utils/data-labels.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ export const getDataLabel = <TDatum>(
   }
 
   const [xDomainStart, xDomainEnd] = xScale.domain();
-  const isOutOfDomain = value <= xDomainStart || value >= xDomainEnd;
+  const isOutOfDomain = value < xDomainStart || value > xDomainEnd;
```
Comment (bpander) [inline frontend/src/metabase/visualizations/shared/components/RowChartView/utils/data-labels.ts:20]: 🌟 Nice work catching negatives too.

File: frontend/src/metabase/visualizations/shared/components/RowChartView/utils/data-labels.unit.spec.ts [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+import type { BarData } from "../../RowChart/types";
+
+import { getDataLabel } from "./data-labels";
+
+describe("getDataLabel", () => {
+  const mockXScale = scaleLinear().domain([0, 100]).range([0, 500]);
+  const seriesKey = "test-series";
+
+  const createBarData = (overrides: Partial<BarData<any>> = {}): BarData<any> =>
```
Comment (bpander) [inline frontend/src/metabase/visualizations/shared/components/RowChartView/utils/data-labels.unit.spec.ts]: I'm not a huge fan of `any`. I get why it's used on L18, but maybe we can use a generic in this create function?
```suggestion
  const createBarData = <T>(overrides: Partial<BarData<T>> = {}): BarData<T> =>
```

**Review by bpander — APPROVED** [review]
✅ Works great. Just had one minor nit about a type in the unit tests.
