### PR TITLE
fix serialization errors we get on big old databases

### LINKED ISSUE #44747: You cannot do a full serialization export on stats via API
If you go to `/api/docs/`, find serialization and click `Try` without changing anything, you'll get a following message — with some toucan context, but with no actual stacktrace. [Some context](https://metaboat.slack.com/archives/C05MPF0TM3L/p1718060686322929)

```
{"lvl":"ERROR","lgr":"metabase-enterprise.serialization.api","m":"Error during serialization","exception":{"exception_class":"clojure.lang.ExceptionInfo","exception_message":null,"stacktrace":"clojure.lang.ExceptionInfo: null
```

Serializing some particular collection seems to be working — be sure to disable settings and data model export, they put quite a load on the server.

### PR DESCRIPTION
**Pull request by sansolovyov**
It fixes a few errors encountered during export of stats:

- `[:metric <id>]` targets a `Card` nowadays rather than `LegacyMetric`
- `{:linkType "page"}` seems to be targeting dashboards, just an old name for them maybe?
- Some archived questions target stuff which does not exist in the database anymore, agreed with Arakaki we're going to skip and log

Fixes #44747

### CODE REVIEW

File: src/metabase/models/card.clj [hunk 1]
```diff
@@ -856,22 +856,19 @@
...
-        (update :made_public_by_id      serdes/*export-user*)
-        (update :dataset_query          serdes/export-mbql)
-        (update :parameters             serdes/export-parameters)
-        (update :parameter_mappings     serdes/export-parameter-mappings)
-        (update :visualization_settings serdes/export-visualization-settings)
-        (update :result_metadata        export-result-metadata)
-        (dissoc :cache_invalidated_at :view_count :last_used_at :initially_published_at
-                :dataset_query_metrics_v2_migration_backup))
-    (catch Exception e
-      (throw (ex-info (format "Failed to export Card: %s" (ex-message e)) {:card card} e)))))
```
Comment (crisptrutski) [inline src/metabase/models/card.clj:874]: Did you mean to remove this exception wrapping, or was it just part of your process to find all the underlying issues?

File: src/metabase/models/serialization.clj [hunk 2]
```diff
@@ -748,10 +752,13 @@
     (let [model-name (name model)
           model      (t2.model/resolve-model (symbol model-name))
           entity     (t2/select-one model (first (t2/primary-keys model)) id)
-          path       (mapv :id (generate-path model-name entity))]
-      (if (= (count path) 1)
-        (first path)
-        path))))
+          path       (when entity (mapv :id (generate-path model-name entity)))]
```
Comment (crisptrutski) [inline src/metabase/models/serialization.clj:755]: This line would look quite nice with `some->>` I think 😄

**Review by crisptrutski — APPROVED** [review]
LGTM

File: src/metabase/models/card.clj (hunk 1 above)
Comment (piranha) [reply src/metabase/models/card.clj:874]: yep, I want to remove it - it's redundant since #45093, should've commented on that

File: src/metabase/models/serialization.clj (hunk 2 above)
Comment (piranha) [reply src/metabase/models/serialization.clj:755]: to be honest I really want `when entity` to stand out here, logic-wise...

Comment (crisptrutski) [reply src/metabase/models/serialization.clj:755]: I just don't like reading from left to right for a bit, then right to left. Maybe put a line break then? 😋
