### PR TITLE
expressions->subselect: exclude fields used only inside expressions

### LINKED ISSUE #14255: Regression : custom column with the same name as a table column
Worked perfectly on V0.36.8.2 but regression after migration to V0.37.4

If I select the custom column now, I see the table column

Capture d’écran 2021-01-05 à 11 34 56
Capture d’écran 2021-01-05 à 11 34 49

My source labels are the source column table values and not the custom column values
Capture d’écran 2021-01-05 à 11 35 55

### PR DESCRIPTION
**Pull request by pawit-metabase**
The expressions are executed inside the sub-query, so the fields do not need to be exposed outside.

Fixes #14255. However, it only fix that very specific regression but does not add support for the more-generic case of having both the original column and the expression in the same query. (That did not work even before regression.)

### CODE REVIEW

File: test/metabase/query_processor_test/explicit_joins_test.clj [hunk 1]
```diff
@@ -575,6 +575,6 @@
                                               [:field "count" {:base-type :type/BigInteger, :join-alias "Q2"}]
                                               [:field "count" {:base-type :type/BigInteger}]]}
                          :limit        2})]
-            (is (= [[4 41 0.46 41]]
+            (is (= [[4 89 0.46 89]]
```
Comment (pawit-metabase) [inline test/metabase/query_processor_test/explicit_joins_test.clj:578]: The actual correct result is `[4 89 0.46 41]`, but it's too complicated to fix in this PR. (So this is just changing from one wrong result to another wrong result.)

Opened #18086 to track the actual issue

**Review by camsaul — APPROVED** [review]
works for me. I've been working on overhauling the SQL QP nested query code since stuff like `expressions->subselect` is kinda buggy, hopefully when that lands we'll actually get that test to return the correct results
