### PR TITLE
fix: hide editing toggle for unsupported engines

### LINKED ISSUE #65901: Disable option to Edit table data for any db that is not MySQL or Postgres.
Currently it is possible to flip the switch for MariaDB, Mongo, H2 to edit table data in Database settings.
While it is possible to proceed with data editing in some databases (H2, Mongo), others throw an error message "INSERT, UPDATE, and DELETE need to be activated for at least one table."

We need to hide an option to turn on data editing for any db that is not MySQL or Posgtres, since we are supporting only the two above for this feature and won't fix any issues that may arise with other databases.

&gt; Also, despite what our documentation says, I'm able to turn on editing for our sample database in H2. Is that on purpose?
Yes, it does work on H2, also on Mongo. But since we never properly tested those databases, and will not fix any issues if those arise, we'll need to hide an option to edit from those as well.

[Slack Message](https://metaboat.slack.com/archives/C0645JP1W81/p1763370479860399?thread_ts=1763077504.737259&cid=C0645JP1W81)

### PR DESCRIPTION
**Pull request by chodorowicz**
closes #65901
Closes https://linear.app/metabase/issue/GDGT-1243/disable-option-to-edit-table-data-for-any-db-that-is-not-mysql-or

### Description

Although some drivers like MongoDB or H2 have table editing capabilities, they were not thoroughly tested and verified. We want to, for now at least, allow users to turn on table editing just for PostgreSQL and MySQL databases. 

The conclusion from discussion was that it's enough to turn off the possibility toggle editing in the UI and leave drivers themselves, as is. That's why a new reason to turn of editing was not introduced.

Adding a separate reason in the UI breaks many drivers which support editing, but are not supported and fully verified and tested by us. Doing this change in the UI has much less blast radius and is inline with the discussions and product requirements.
- https://github.com/metabase/metabase/actions/runs/20572390572?pr=67564
- https://github.com/metabase/metabase/pull/67564/changes/7116b107a8866c2257f32493799c34e92bb61c71

### How to verify

Go to unsupported DB, like H2. It should have the table editing section hidden.
Supported DB, like PostgreSQL, should have the section visible and enabled. 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/metabase-enterprise/table-editing/admin/AdminDatabaseTableEditingSection.tsx [hunk 1]
```diff
@@ -27,15 +27,17 @@ enum DisabledReasonKey {
...
 }
 
 const VISIBLE_REASONS: string[] = [
   DisabledReasonKey.NoWriteableTable,
   DisabledReasonKey.SyncInProgress,
-  DisabledReasonKey.DatabaseEmtpy,
+  DisabledReasonKey.DatabaseEmpty,
 ];
 
+const ALLOWED_ENGINES_FOR_TABLE_EDITING = ["postgres", "mysql"];
```
Comment (egorgrushin) [inline enterprise/frontend/src/metabase-enterprise/table-editing/admin/AdminDatabaseTableEditingSection.tsx]: It's okay. However, I see that we already have a file with such constants here frontend/src/metabase/databases/constants.tsx. I would suggest to move this const to the file.

I'm concerned about typo issues. Maybe we need an enum or something that will establish correct DB vendor names across the product?

**Review by egorgrushin — APPROVED** [review]

File: enterprise/frontend/src/metabase-enterprise/table-editing/admin/AdminDatabaseTableEditingSection.tsx (hunk 1 above)
Comment (chodorowicz) [reply enterprise/frontend/src/metabase-enterprise/table-editing/admin/AdminDatabaseTableEditingSection.tsx]: Good point! thanks
https://github.com/metabase/metabase/pull/67564/changes/4ad821787f05ffc7fa38848e2daf2bf91187a4ca
