### PR TITLE
Fix embedding

### LINKED ISSUE #37437: Embedding height is not dynamic
### Describe the bug

When embedding a dashboard, and using a "dynamic" iFrame resize, like [iFrameResizer](https://github.com/davidjbradshaw/iframe-resizer), the height of the html is always expending, but never shrinking when it change, due to the use of `height: 100%;` instead of `height: auto;` on the metabase html tag.

https://github.com/metabase/metabase/assets/59898438/9b89b1a2-de16-419d-b3e6-2c370f22f93c

But, when I change the `height` to `auto`, it work as excepted:

https://github.com/metabase/metabase/assets/59898438/91faf735-6f65-41f3-8d89-53ff5f7d2b5e

### To Reproduce

- Using a metabase embedding.

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
- macOS 14.1 (23B2073)
- chrome 120.0.6099.129
- metabase: metabase-enterprise:v1.47.7
```

### Severity

Annoying but not blocking

### Additional context

_No response_

### LINKED ISSUE #40660: Iframe embedding overflow widgets issue
### Describe the bug

Screenshot 2024-03-27 at 10 50 14 AM

`EmbedFrame` is not resizing according to the widgets inside it. Widgets are overflowing out side of the main container. 
Setting `overflow: 'auto'` from dev tools fixes the issue however we can't inject the styles in iframe. 

### To Reproduce

1. Create a dashboard with lots of widgets
2. Render the iframe with Light theme inside the parent app with black background. 
3. You will see frame container is falling short of the combined widgets height. 

### Expected behavior

Background container should expand to the full widgets height. 

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "4.14.336-253.554.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-12",
      "tag": "v1.48.6",
      "hash": "b8818f9"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

blocking your usage of metabase entierly

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes #40660
Fixes #37437

### Description

This PR fixes the 2 issue above. For #37437, I fix it so that dashboards return `fit` event correctly.

### How to verify

1. Follow the repro steps in #40660
1. For #37437, subscribe to `message` event. I use this custom snippet for interactive embedding to change the embedding height. When the height is 0, it uses the default height instead.
    ```ts
    useEffect(() => {
      const callback = (event) => {
        const metabaseEvent = event.data.metabase
        if (metabaseEvent) {
          if (
            metabaseEvent.type === 'location' &&
            !metabaseEvent.location.pathname.startsWith('/dashboard/')
          ) {
            setHeight(0)
          }
          if (metabaseEvent.type === 'frame') {
            setHeight(metabaseEvent.frame.height)
          }
        }
      }
      window.addEventListener('message', callback)
      return () => {
        window.removeEventListener('message', callback)
      }
    }, [])
    ```
### Demo

For #40660
image

For #37437 
https://www.loom.com/share/208e32fd73204248b9d311e886850a31

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/lib/embed.js [hunk 1]
```diff
@@ -59,8 +59,28 @@ function sendMessage(message) {
...
+  const dashboardHeaderHeight =
+    document.getElementById("Dashboard-Header-Container")?.offsetHeight ?? 0;
+  const dashboardContentHeight =
+    document.getElementById("Dashboard-Parameters-And-Cards-Container")
+      ?.scrollHeight ?? 0;
+  const dashboardHeight = dashboardHeaderHeight + dashboardContentHeight;
+
+  if (dashboardHeight > 0) {
+    return appBarHeight + dashboardHeight;
+  }
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/embed.js:83]: This is the fix for #37437

Previously we only used `document.body.scrollHeight` which doesn't account for the dashboard content inside the scroll container.

This fix the issue by summing the all the dashboard element heights.

File: frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.styled.tsx [hunk 2]
```diff
@@ -17,6 +17,7 @@ export const Root = styled.div<{
 }>`
   display: flex;
   flex-direction: column;
+  overflow: auto;
```
Comment (WiNloSt) [inline frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.styled.tsx:20]: This is the fix for #40660

File: frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.tsx [hunk 3]
```diff
@@ -140,6 +140,8 @@ export const ParametersAndCardsContainer = styled.div<{
     overflow-x: clip;
   }
   padding-bottom: 40px;
+  /* Makes sure it doesn't use all the height, so the actual content height could be used in embedding #37437 */
+  align-self: flex-start;
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.tsx:144]: image

Previously this flex element stretched its height to fit the container, which makes it harder to get the total dashboard height since we need to sum more sub-elements.

By doing this we don't need to sum dashboard parameter height and card container heights. We can use this element height directly.

File: frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.tsx [hunk 4]
```diff
@@ -140,6 +140,9 @@ export const ParametersAndCardsContainer = styled.div<{
     overflow-x: clip;
   }
   padding-bottom: 40px;
+  /* Makes sure it doesn't use all the height, so the actual content height could be used in embedding #37437 */
+  align-self: ${({ shouldMakeDashboardHeaderStickyAfterScrolling }) =>
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.tsx:144]: image

Previously this flex element stretched its height to fit the container, which makes it harder to get the total dashboard height since we need to sum more sub-elements.

By doing this we don't need to sum dashboard parameter height and card container heights. We can use this element height directly.

We don't want to set this when we're editing a dashboard because it prevent the dashboard header from being sticky which failed bunch of tests as well.

File: e2e/test/scenarios/embedding/reproductions/40660-overflow-when-embedding-long-dashboards.cy.spec.js [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+  name: "Products",
+  query: { "source-table": PRODUCTS_ID, limit: 2 },
+};
+
+const dashboardDetails = {
+  name: "long dashboard",
+  enable_embedding: true,
+};
+
+describe("issue 37914", () => {
```
[the remark this answers is not in the document]
Comment (WiNloSt) [reply e2e/test/scenarios/embedding/reproductions/40660-overflow-when-embedding-long-dashboards.cy.spec.js:22]: Good catch, I use the test file from that issue as a starting point.

File: frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx [hunk 6]
```diff
@@ -533,6 +533,7 @@ function DashboardInner(props: DashboardProps) {
       {() => (
         <DashboardStyled>
           <DashboardHeaderContainer
+            id="Dashboard-Header-Container"
```
[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx:536]: I could use `data-element-id` for consistency. But this fix shouldn't have anything to do with embedding SDK. This fix is only for interactive embedding because we have trouble resizing the iframe to fit the dashboard. Let's also consider other features.

1. Static embedding. We don't have to use this fix because static embedding works with [`iframe-resizer`](https://github.com/davidjbradshaw/iframe-resizer) that would automatically resize the iframe to the height of the iframe content.
2. Embedding SDK. We also don't have to rely on this fix because users will just use the component directly, as there's no iframe, SDK component parent container could just expand as much as the SDK components would take space.

Actually, another solution to this bug is to make `iframe-resizer` work on interactive embedding. But due to how different our DOM structures are between interactive embedding and static embedding. `iframe-resizer` wouldn't work well out of the box for interactive embedding. I've tried a few more configurations it offers, but couldn't make it work properly, so I rely on sending `fit` event and users can use that information to scale their iframe size properly.

[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx:537]: Use `data-element-id` in 438db18614343dcb1447e362d264b226af85d825.

File: e2e/test/scenarios/embedding/reproductions/40660-overflow-when-embedding-long-dashboards.cy.spec.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (WiNloSt) [reply e2e/test/scenarios/embedding/reproductions/40660-overflow-when-embedding-long-dashboards.cy.spec.js]: Fixed in 45d6b2bde672214371d0972c39ec12c898641e3d. Also fixed another test name with wrong issue as well.

File: frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx [hunk 7]
```diff
@@ -553,13 +555,14 @@ function DashboardInner(props: DashboardProps) {
...
               id={DASHBOARD_PDF_EXPORT_ROOT_ID}
+              data-element-id="dashboard-parameters-and-cards"
               data-testid="dashboard-parameters-and-cards"
               shouldMakeDashboardHeaderStickyAfterScrolling={
                 !isFullscreen && (isEditing || isSharing)
               }
             >
               {renderParameterList()}
-              <CardsContainer id="Dashboard-Cards-Container">
+              <CardsContainer data-element-id="dashboard-cards-container">
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx:565]: This doesn't have anything to do with this bug fix, but I change it to make it more consistent with other selectors in this file.

**Review by deniskaber — APPROVED** [review]
