### PR TITLE
Handle non-number cases in NumberFingerprint

### LINKED ISSUE #46574: v0.50.x - question crashes with numeric type and oracle database "TypeError: e.toFixed is not a function"
### Describe the bug

Since v0.50.x hovering over the header of a NUMBER typed column causes a frontend error that crashes the displayed question. This happens when using an oracle DB and when the column metadata is not set or set to a numeric type.

metabase-crash-1

grafik

### To Reproduce

1. Set up a new metabase instance with docker putting an oracle-jdbc-driver into the plugins folder.
2. Set up a table with a `NUMBER` column on the oracle database
3. Connect metabase to the Oracle database
4. Create a question for the previously created table and hover over the column headers

I used the latest [ojdbc11.jar](https://download.oracle.com/otn-pub/otn_software/jdbc/234/ojdbc11.jar) as jdbc driver.
To reproduce the error i used [Oracle Database XE Release 21c](https://container-registry.oracle.com/ords/f?p=113:4:116595847545161:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:803,803,Oracle%20Database%20Express%20Edition,Oracle%20Database%20Express%20Edition,1,0&cs=31RJ2Qrbu6s3cv9VTJmRigJuIm2BglixteP4I7m8uBo7s1uurGg1td0jk0Lhlme1etvT9Qc-v5-O6uA1el6SuSA)

In my setup to reproduce the error i started a fresh metabase with a fresh oracle-xe Database with the following docker compose file:

```
version: "2"

services:
  metabase:
    image: metabase/metabase:v0.50.18
    depends_on:
      - oracle-xe
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./plugins
        target: /plugins

  oracle-xe:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PWD=test
```

Make sure u have a plugins folder with the ojdbc.jar in the folder you have the docker compose.yml.
Start it with docker compose up.
You can connect to the oracle database on:

    url: oracle-xe
    port: 1521
    service: XE
    user: system
    password: test

I set up a table in the database with this sql (schema was called DBSFWUSER by default):

```
CREATE TABLE DBSFWUSER.TEST_TABLE (ID NUMBER(10,0), TEST_COLUMN NUMBER);
INSERT INTO DBSFWUSER.TEST_TABLE(ID) VALUES (1);
```

When loading this table into a question everything seems to work fine. When hovering over the column header the question crashes.

### Expected behavior

Hovering over the column headers should show the column metadata.

grafik

### Logs

frontend log - the error appears to be here
```
TypeError: e.toFixed is not a function
    T NumberFingerprint.tsx:56
    D NumberFingerprint.tsx:21
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    onOpen DelayGroup.tsx:44
    y Popover.tsx:46
    s use-disclosure.js:9
    React 2
    s use-disclosure.js:7
    setTimeout handler*openDropdown use-delayed-hover.js:15
    r create-event-handler.js:4
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 9
    f5 app.js:68
    f2 app.js:99
    45600 app-main.js:24
    Webpack 6
 
Object { componentStack: "\nD@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:28:11574\nN@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:28:12608\ndiv\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\ndiv\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\nL@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:28:13754\ndiv\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\ndiv\n21761/g<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:104000\nd@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:144281\nx@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:356487\ndiv\ng@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:255104\nw@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:256160\nZ@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:249565\ntf@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:119:478545\ny@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:154136\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\n84976/i/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:451671\nen@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:252000\n84976/i/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:451671\nB@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:155975\nh@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:28:18037\na@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:246:62920\ndiv\n21761/g<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:104000\nb@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:83:325047\ng@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:83:320089\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\ndiv\ndiv\nt@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:125:36922\ndiv\n21761/g<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:104000\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\nt@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:125:124022\ntI@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:119:480406\nfy@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:246:24613\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\na@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:21:29151\n79576/fj</fj@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:246:41972\nfA@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:246:47697\ndiv\ndiv\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\ns@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:7:128559\neY@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:119:527665\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\na@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:21:29151\nHr@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:193:135242\ndiv\ndiv\nHa@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:193:137551\ndiv\ndiv\nV8@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:196:1400\na@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:21:29151\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\nmain\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\ndiv\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\ndiv\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\ndiv\nenV@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:215:25378\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\na@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:21:29151\n45600/enG<@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:215:34343\n45600/Bg/</<@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:193:77475\n@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:186456\n@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:186456\nn@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:185245\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\nb@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:167292\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\n@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:169239\n@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:173511\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\nConnect(Favicon)\nh@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:21:49493\nb@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:167292\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\n@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:169239\n@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:173511\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\nConnect(Favicon)\n45600/edl<@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:228:13550\ni@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:139:13331\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\ni@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:139:13331\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\nmain\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\ndiv\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\ndiv\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\n77466/t.KBarProvider@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:76:232414\nc6@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:127:83592\nwithRouter(c6)\ns@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:7:128559\n45600/p6<@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:127:159185\nc@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:106:5990\n@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:32:186456\nRouterContext\nRouter\nd@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:419457\ntZ@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:119:479228\nh@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:63004\n$@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:434369\n10/u/<@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:7:62661\n7138/t.DragDropContextProvider@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:83:176867\ntW@http://localhost:3000/app/dist/app-main.9fae825abe7ec0b12735.js:228:53554\nN@http://localhost:3000/app/dist/vendor.78be941a71c4863ea2f6.js:110:468" }
console.js:13:4
```

server-log - no error here
```
[4482d035-bba0-4597-905a-9d4ae730d5ec] 2024-08-07T14:42:58+02:00 DEBUG metabase.server.middleware.log GET /api/alert/question/30 200 2.2 ms (1 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (7 idle, 0 queued) (92 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
[4482d035-bba0-4597-905a-9d4ae730d5ec] 2024-08-07T14:42:58+02:00 DEBUG metabase.server.middleware.log GET /api/card/30/query_metadata 200 84.4 ms (21 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (7 idle, 0 queued) (92 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
[4482d035-bba0-4597-905a-9d4ae730d5ec] 2024-08-07T14:42:59+02:00 DEBUG metabase.server.middleware.log POST /api/card/30/query 202 [ASYNC: completed] 63.1 ms (22 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (7 idle, 0 queued) (93 total active threads) Queries in flight: 0 (0 queued); oracle DB 4 connections: 0/1 (0 threads blocked) {:metabase-user-id 1}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "de",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "4.19.128-microsoft-standard",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-30",
      "tag": "v0.50.18",
      "hash": "c323ffc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

The issue is blocking some of our users. A workaround exits using a (wrong) text-type for column metadata.

### Additional context

Error only seen using an Oracle database. When testing with version v0.49.13 everything worked fine.

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/46574

### Description

Fixes a P1 bug that caused the question to crash when displaying the fingerprint info for certain tables.

The TypeScript types are incorrect which made the code pass the checker. If fixed it locally but I think we should consider fixing all the incorrect api types (like the one for [`NumberFingerprintDisplayInfo`](https://github.com/metabase/metabase/blob/master/frontend/src/metabase-lib/types.ts#L193-L200)).

### How to verify

Follow the reproduction steps in the [issue](https://github.com/metabase/metabase/issues/46574) to see if the crash still happens.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR, we don't have Oracle tests for Cypress so only a unit test was added

### CODE REVIEW

File: frontend/src/metabase/components/MetadataInfo/ColumnFingerprintInfo/NumberFingerprint.tsx [hunk 1]
```diff
@@ -48,10 +48,18 @@ export function NumberFingerprint({
...
 
-  return [true, Number.isInteger(num) ? num.toString() : num.toFixed(2)];
+  if (Number.isInteger(num)) {
+    return [true, num.toString()];
+  }
+
+  return [true, num.toFixed(2)];
+}
+
+function isNumber(num: unknown): num is number {
```
Comment (ranquild) [inline frontend/src/metabase/components/MetadataInfo/ColumnFingerprintInfo/NumberFingerprint.tsx:63]: typeof num === "number"?

File: frontend/src/metabase-lib/types.ts [hunk 2]
```diff
@@ -191,12 +191,12 @@ export type TextFingerprintDisplayInfo = {
 };
 
 export type NumberFingerprintDisplayInfo = {
-  avg: number;
-  max: number;
-  min: number;
-  q1: number;
-  q3: number;
-  sd: number;
+  avg: unknown;
```
Comment (ranquild) [inline frontend/src/metabase-lib/types.ts:194]: Could you leave a comment here that we expect malformed data - strings, etc?

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/components/MetadataInfo/ColumnFingerprintInfo/NumberFingerprint.tsx (hunk 1 above)
Comment (romeovs) [reply frontend/src/metabase/components/MetadataInfo/ColumnFingerprintInfo/NumberFingerprint.tsx:63]: I wanted to catch the `isNan` and `isFinite` cases too while we're at it.
