### PR TITLE
Remove `:foreign-keys` feature or convert to `:metadata/key-constraints` where appropriate

### LINKED ISSUE #44511: v50: Foreign keys no longer work with MongoDB
### Describe the bug

Questions that leverage foreign keys are no longer working as of Metabase 50, but were working well in Metabase 49.

### To Reproduce

Repro steps:
- create two collections
  - collectionA: `{ _id: ObjectId, bID: ObjectId, value: string }`
  - collectionB: `{ _id: ObjectId, value: string }`
- in metabase admin, set `collectionA.bID` as a foreign key to `collectionB._id`
- ask a new question: count of rows for collectionA where collectionB.value == 'foo'

### Expected behavior

This worked well in Metabase 49, but regressed in Metabase 50. It would answer the question.

Now I'm getting: `:mongo driver does not support foreign keys.`

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9-LTS",
    "os.name": "Linux",
    "os.version": "4.14.109-99.92.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

pretty darn significant for mongodb users

### Additional context

_No response_

### LINKED ISSUE #44573: Add automated tests for implicit joins on Mongo
Automated testing is missing for implicit joins on Mongo. For context see the PR's https://github.com/metabase/metabase/pull/44572 description. As mentioned in the PR, stub from [`tx-post-sync-hook`](https://github.com/metabase/metabase/tree/tx-post-sync-hook) could be used as a starting point.

### LINKED ISSUE #44842: Sorting by joined field does not work on Mongo
Create products joining orders on id in `test-data` and sort by id column from orders. Results are sorted on id column from products. This is prerequisite of https://github.com/metabase/metabase/issues/44511 as problem surfaced enabling implicit joins tests.

### LINKED ISSUE #45381: Automatically mark FKs for test data drivers like BigQuery that don't actually have real FKs
This way we can run tests that rely on implicit joins. We have `mt/with-mock-fks-for-drivers-without-fk-constraints` but you have to use it on each individual test. It would be nice to eliminate the need for this

### LINKED ISSUE #45589: Fix bigquery driver to pass tests
Following tests fail for bigquery with `:foreign-keys` removed from codebase:

- `metabase.query-processor-test.explicit-joins-test/joining-nested-queries-with-same-aggregation-test`
- `metabase.query-processor-test.implicit-joins-test/join-multiple-tables-test`
- `metabase.query-processor-test.offset-test/offset-expression-inside-other-expression-test`
- `metabase.query-processor-test.offset-test/offset-expression-test-order-by-parameterized-expression`
- `metabase.query-processor-test.remapping-test/remappings-with-implicit-joins-test`

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes  #44511 
Closes #44573
Closes #44842
Closes #45381
Closes #45589

### Description

This PR does multiple things:

1. Adds join alias also to Mongo lvalue fields. This is necessary for eg. sorting on joined fields to work correctly.
2. Changes implicit joins dependency from `:foreign-keys` to `:left-join`. That enables use of implicit joins with dbmses that do not support foreign keys.
3. Adds `add-foreign-keys!` function to `get-or-create` logic. That's responsible for adding foreign key relationships to app db manually for dbmses that do not support fks. This enables testing implicit joins.
4. As per [slack discussion](https://metaboat.slack.com/archives/C04DN5VRQM6/p1720024835058369?thread_ts=1719971343.726209&cid=C04DN5VRQM6), **this PR also removes `:foreign-keys` feature or converts usage to `:metadata/key-constraints`.**
5. Adds `escape-alias` implementation to presto.
6. Sets `:metadata/key-constraints` to false for bigquery.
7. Fixes bigquery's order by joined field functionality.
8. Sets sqlite :metadata/key-constraints to false.
9. Updates tests -- lot of tests that were depending on foreign keys now depend on `:left-join`. Meaning also eg. remapping tests run now with non `:metadata/key-constraints` drivers.
10. Sparks joy.

### How to verify

Run modified tests. Attempt reproduction from original issue.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by theyough** [comment]
any update on this @camsaul ?

File: test/metabase/test/data/impl/get_or_create.clj [hunk 1]
```diff
@@ -147,6 +148,60 @@
...
+             (into result
+                   (comp (filter (comp some? :fk))
+                         (map #(vector (:table-name table-def)
+                                       (:field-name %)
+                                       (name (:fk %)))))
+                   (:field-definitions table-def))))))
+
+(defn- dbdef->fk-field-infos
+  "Generate `fk-field-infos` structure. It is a seq of maps of 2 keys: :id and :fk-target-field-id. Existing database,
+  tables and fields in app db are examined to get the required info."
```
Comment (metamben) [inline test/metabase/test/data/impl/get_or_create.clj:168]: Have you considered returning a map from ids to target-ids?

**Review by metamben — COMMENTED** [review]
The docs (driver change log for sure) should be updated.

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 2]
```diff
@@ -474,17 +474,17 @@
...
-                              :expressions             true
-                              :foreign-keys            true
-                              :now                     true
-                              :percentile-aggregations true
+(doseq [[feature supported?] {:convert-timezone         true
+                              :datetime-diff            true
+                              :expressions              true
+                              :now                      true
+                              :percentile-aggregations  true
+                              :metadata/key-constraints false
```
[the remark this answers is not in the document]
Comment (lbrdnk) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:482]: I'll update PR description and title shortly. This PR should not only fix joins support, but also eliminate `:foreign-keys`. See [this discussion](https://metaboat.slack.com/archives/C04DN5VRQM6/p1720024835058369?thread_ts=1719971343.726209&cid=C04DN5VRQM6).

As to this specific change, `:foreign-keys` were set to true in driver code. But tests used `qp.test-util/*enable-fk-support-for-disabled-drivers-in-tests*` for `database-supports?` result value for the feature, defaulting to `false`.

That makes me think fks relationships _may_ not be supported or tested.

At the moment the value is set what I _think_ it should be, but I'm still in the process of figuring out what's the right thing to do.

File: test/metabase/test/data/impl/get_or_create.clj [hunk 3]
```diff
@@ -147,6 +148,60 @@
...
+  [dbdef db]
+  (when-some [table-field-fk (not-empty (preprocess-dbdef-for-fks dbdef))]
+    (let [tables (t2/select :model/Table :db_id (:id db))
+          fields (t2/select :model/Field {:where [:in :table_id (map :id tables)]})
```
[the remark this answers is not in the document]
Comment (lbrdnk) [reply test/metabase/test/data/impl/get_or_create.clj:172]: It should not by means of `when-some` and `(not-empty (preprocess-dbdef-for-fks dbdef))`.

[the remark this answers is not in the document]
Comment (metamben) [reply test/metabase/test/data/impl/get_or_create.clj:172]: That is, it could but that would mean that creating the database according to `dbdef` has gone wrong.

File: test/metabase/driver_test.clj [hunk 4]
```diff
@@ -19,12 +19,12 @@
 
 (driver/register! ::test-driver, :abstract? true)
 
-(defmethod driver/database-supports? [::test-driver :foreign-keys] [_driver _feature _db] true)
-(defmethod driver/database-supports? [::test-driver :foreign-keys] [_driver _feature db] (= db "dummy"))
+(defmethod driver/database-supports? [::test-driver :metadata/key-constraints] [_driver _feature _db] true)
+(defmethod driver/database-supports? [::test-driver :metadata/key-constraints] [_driver _feature db] (= db "dummy"))
```
[the remark this answers is not in the document]
Comment (lbrdnk) [reply test/metabase/driver_test.clj:23]: I believe it is safe to remove the first definition, done.

File: test/metabase/test/data/impl/get_or_create.clj (hunk 1 above)
Comment (lbrdnk) [reply test/metabase/test/data/impl/get_or_create.clj:173]: That would make the code more succinct, but I'm leaning towards this version as key names follow what's in app db so it is evident from glance on:
```
{:id (get-in table-name->field-name->field [table-name field-name :id])
 :fk-target-field-id (get-in table-name->pk-field [target-table-name :id])}
```
what are the returned data. If that does not make sense lmk, I'll change that.

File: src/metabase/util/date_2.clj [hunk 5]
```diff
@@ -592,3 +592,24 @@
...
+    (let [t (parse tstr)
+          inst (cond (instance? LocalDate t)
+                     (.toInstant ^LocalDateTime (.atStartOfDay ^LocalDate t) java.time.ZoneOffset/UTC)
+
+                     (instance? LocalDateTime t)
+                     (.toInstant ^LocalDateTime t java.time.ZoneOffset/UTC)
+
+                     :else
+                     t)]
+      (format "yyyy-MM-dd'T'HH:mm:ss'Z'" inst))))
```
Comment (lbrdnk) [inline src/metabase/util/date_2.clj:615]: Currently we store sqlite test data with second precision. Ideal solution would be to find a way of increasing it. That's over the scope of this PR.

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj [hunk 6]
```diff
@@ -753,17 +753,38 @@
...
+   ;;
+   ;; Also it handles case as follows: `select b from T join U ... order by a`, where field a is in both T and U
+   ;; tables. Problem is solved by qualifying that order by field.
+   (if (and
+        (::add/desired-alias opts)
+        (not (and (pos-int? (::add/source-table opts))
+                  (not (or (:binning opts)
+                           (:temporal-unit opts))))))
+     (sql.qp/rewrite-fields-to-force-using-column-aliases clause)
+     clause)])
```
Comment (lbrdnk) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:775]: This fixes bigquery order by issues.

File: test/metabase/query_processor/test_util.clj [hunk 7]
```diff
@@ -454,25 +448,6 @@
...
-
-(defmacro with-mock-fks-for-drivers-without-fk-constraints
-  "Execute `body` with test-data `checkins.user_id`, `checkins.venue_id`, and `venues.category_id` (for `test-data`) or
-  other relevant columns (for `test-data`) marked as foreign keys and with `:foreign-keys` a supported feature
-  when testing against BigQuery or similar drivers that do not support Foreign Key constraints. (We still let people
-  mark FKs manually.) The macro helps replicate the situation where somebody has manually marked FK relationships."
-  {:style/indent 0}
-  [& body]
-  `(do-with-mock-fks-for-drivers-without-fk-constraints (^:once fn* [] ~@body)))
-
```
Comment (lbrdnk) [inline test/metabase/query_processor/test_util.clj:475]: As we now add fks to app db during dataset creation this is not necessary.

File: test/metabase/test/data/impl/get_or_create.clj [hunk 8]
```diff
@@ -147,6 +148,60 @@
...
+          table-id->table (m/index-by :id tables)
+          table-name->field-name->field (-> (group-by :table_id fields)
+                                            (update-keys (comp :name table-id->table))
```
[the remark this answers is not in the document]
Comment (lbrdnk) [reply test/metabase/test/data/impl/get_or_create.clj:186]: Totally! Thanks.

File: modules/drivers/sqlite/test/metabase/test/data/sqlite.clj [hunk 9]
```diff
@@ -11,6 +13,10 @@
 
 (defmethod tx/supports-timestamptz-type? :sqlite [_driver] false)
 
+;; TODO: It seems that foreign keys sync does not work on sqlite. The [[metabase.driver-test/describe-table-fks-test]]
+;;       is failing. Resolve that and re-enable feature!
+(defmethod driver/database-supports? [:sqlite :metadata/key-constraints] [_driver _feature _db] (not config/is-test?))
```
Comment (metamben) [inline modules/drivers/sqlite/test/metabase/test/data/sqlite.clj:18]: Does this mean that it doesn't work in tests but does work in production?

File: src/metabase/util/date_2.clj (hunk 5 above)
Comment (metamben) [reply src/metabase/util/date_2.clj:615]: I understand SQLite can understand ISO8601 strings in "YYYY-MM-DD HH:MM:SS.SSS" format, millisecond precision should be achievable. See also https://www.sqlite.org/lang_datefunc.html#subsec.

File: test/metabase/query_processor/test_util.clj [hunk 10]
```diff
@@ -432,15 +432,9 @@
...
-  "Whether to enable `:foreign-keys` in drivers like `:bigquery-cloud-sdk` that don't have formal FKs
-  when [[metabase.config/is-test?]] is true."
-  false)
-
 (defn mock-fks-application-database-metadata-provider
-  "Impl for [[with-mock-fks-for-drivers-without-fk-constraints]]. A mock metadata provider composed with the application
-  database metadata provider that adds FK relationships for Tables that would normally have them in drivers that have
-  formal FK constraints."
+  "A mock metadata provider composed with the application database metadata provider that adds FK relationships
+  for Tables that would normally have them in drivers that havev formal FK constraints."
```
Comment (metamben) [inline test/metabase/query_processor/test_util.clj:437]:
```suggestion
  for Tables that would normally have them in drivers that have formal FK constraints."
```

**Review by metamben — APPROVED** [review]
I've suggested changes to the documentation reflecting my understanding of what's going on.
I also have some questions I would like to be answered, but nothing that should block the PR.

File: src/metabase/util/date_2.clj (hunk 5 above)
Comment (lbrdnk) [reply src/metabase/util/date_2.clj:615]: I've opened https://github.com/metabase/metabase/issues/45790 to track this.

File: docs/developers-guide/driver-changelog.md [hunk 11]
```diff
@@ -54,6 +54,15 @@ title: Driver interface changelog
...
   supported version since Metabase 0.49.0.
 
+- The `:foreign-keys` driver feature has been removed. `:metadata/keys-constraints` should be used for drivers that support
+  foreign key relationships reporting during sync. Implicit joins now depend on the `:left-join` feature instead. The
+  default value is true for `:sql` based drivers. All join features are now enabled for `:sql` based drivers
+  by default. Previously, those depended on the `:foreign-keys` feature. If your driver supports `:left-join`, 
+  the test for remapping and implicit joins will be now executed.
+
+-  The`:parameterized-sql` driver feature has been added to distinguish drivers that don't support parametrized SQL in tests. Currently,
+this is disabled only for `:sparksql`.
```
Comment (metamben) [inline docs/developers-guide/driver-changelog.md:64]: This looks like an unusually long line. (But that's probably not a problem.)

**Review by metamben — APPROVED** [review]
