### PR TITLE
Don't crash for ignored status codes in embedding responses

### LINKED ISSUE #51386: Downloading results of an embedded question (via iframe) fails
### Describe the bug

When pressing the "Download full results" widget and clicking the Download button, it immediately gives a download error, see screenshot. This only happens in the iframe-embedded question. The network request shows a 500 internal server error with message `"No matching clause: [\"embedding-iframe\" nil]"`. If I access the download URL directly (by copying it from Chrome dev tools), the download works without problems.

Image
Image

### To Reproduce

1. Go to the download link of an embedded question
2. Click on the Download button
3. Observe the error

### Expected behavior

_No response_

### Logs

<details>
<summary> Logs: </summary>

```
{
  "via": [
    {
      "type": "java.lang.IllegalArgumentException",
      "message": "No matching clause: [\"embedding-iframe\" nil]",
      "at": [
        "metabase.analytics.sdk$track_sdk_response",
        "invokeStatic",
        "sdk.clj",
        40
      ]
    }
  ],
  "trace": [
    [
      "metabase.analytics.sdk$track_sdk_response",
      "invokeStatic",
      "sdk.clj",
      40
    ],
    [
      "metabase.analytics.sdk$track_sdk_response",
      "invoke",
      "sdk.clj",
      37
    ],
    [
      "metabase.analytics.sdk$embedding_mw$embedding_mw_fn__78293$responder__78294",
      "invoke",
      "sdk.clj",
      64
    ],
    [
      "metabase.server.middleware.session$reset_session_timeout$fn__72177$fn__72178",
      "invoke",
      "session.clj",
      568
    ],
    [
      "metabase.server.middleware.json$wrap_streamed_json_response$fn__55864$respond_STAR___55865",
      "invoke",
      "json.clj",
      91
    ],
    [
      "clojure.core$comp$fn__5895",
      "invoke",
      "core.clj",
      2586
    ],
    [
      "metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__106746$fn__106747",
      "invoke",
      "exceptions.clj",
      116
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__54210$fn__54211",
      "invoke",
      "core.clj",
      151
    ],
    [
      "compojure.response$send",
      "invokeStatic",
      "response.clj",
      28
    ],
    [
      "compojure.response$send",
      "invoke",
      "response.clj",
      22
    ],
    [
      "compojure.response$fn__53439$fn__53440",
      "invoke",
      "response.clj",
      70
    ],
    [
      "metabase.server.routes$redirect_including_query_string$fn__109990",
      "invoke",
      "routes.clj",
      28
    ],
    [
      "compojure.response$fn__53439",
      "invokeStatic",
      "response.clj",
      70
    ],
    [
      "compojure.response$fn__53439",
      "invoke",
      "response.clj",
      67
    ],
    [
      "compojure.response$fn__53397$G__53392__53408",
      "invoke",
      "response.clj",
      17
    ],
    [
      "compojure.response$send",
      "invokeStatic",
      "response.clj",
      27
    ],
    [
      "compojure.response$send",
      "invoke",
      "response.clj",
      22
    ],
    [
      "compojure.core$wrap_response$fn__54217",
      "invoke",
      "core.clj",
      160
    ],
    [
      "compojure.core$wrap_route_middleware$fn__54201",
      "invoke",
      "core.clj",
      132
    ],
    [
      "compojure.core$wrap_route_info$fn__54206",
      "invoke",
      "core.clj",
      139
    ],
    [
      "compojure.core$wrap_route_matches$fn__54210",
      "invoke",
      "core.clj",
      151
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229",
      "invoke",
      "core.clj",
      200
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229",
      "invoke",
      "core.clj",
      200
    ],
    [
      "compojure.core$make_context$handler__54257",
      "invoke",
      "core.clj",
      290
    ],
    [
      "compojure.core$make_context$fn__54261",
      "invoke",
      "core.clj",
      300
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$make_context$fn__54261",
      "invoke",
      "core.clj",
      301
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$make_context$fn__54261",
      "invoke",
      "core.clj",
      301
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$make_context$fn__54261",
      "invoke",
      "core.clj",
      301
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__54210",
      "invoke",
      "core.clj",
      153
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__54210",
      "invoke",
      "core.clj",
      152
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__54210",
      "invoke",
      "core.clj",
      152
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__54210",
      "invoke",
      "core.clj",
      152
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229$f__54230$respond_SINGLEQUOTE___54231",
      "invoke",
      "core.clj",
      197
    ],
    [
      "metabase.server.routes$fn__110002$fn__110004",
      "invoke",
      "routes.clj",
      47
    ],
    [
      "compojure.core$routes$fn__54229$f__54230",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__54229",
      "invoke",
      "core.clj",
      200
    ],
    [
      "metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__106746",
      "invoke",
      "exceptions.clj",
      111
    ],
    [
      "metabase.server.middleware.exceptions$catch_api_exceptions$fn__106743",
      "invoke",
      "exceptions.clj",
      100
    ],
    [
      "metabase.server.middleware.log$log_api_call$fn__110385",
      "invoke",
      "log.clj",
      221
    ],
    [
      "metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__114100",
      "invoke",
      "browser_cookie.clj",
      40
    ],
    [
      "metabase.server.middleware.security$add_security_headers$fn__106702",
      "invoke",
      "security.clj",
      273
    ],
    [
      "ring.middleware.json$wrap_json_body$fn__114359",
      "invoke",
      "json.clj",
      64
    ],
    [
      "metabase.server.middleware.offset_paging$handle_paging$fn__96235",
      "invoke",
      "offset_paging.clj",
      56
    ],
    [
      "metabase.server.middleware.json$wrap_streamed_json_response$fn__55864",
      "invoke",
      "json.clj",
      88
    ],
    [
      "ring.middleware.keyword_params$wrap_keyword_params$fn__114448",
      "invoke",
      "keyword_params.clj",
      55
    ],
    [
      "ring.middleware.params$wrap_params$fn__114467",
      "invoke",
      "params.clj",
      77
    ],
    [
      "metabase.server.middleware.misc$maybe_set_site_url$fn__70111",
      "invoke",
      "misc.clj",
      59
    ],
    [
      "metabase.server.middleware.session$reset_session_timeout$fn__72177",
      "invoke",
      "session.clj",
      566
    ],
    [
      "metabase.server.middleware.session$bind_current_user$fn__72143$fn__72144",
      "invoke",
      "session.clj",
      459
    ],
    [
      "metabase.server.middleware.session$do_with_current_user",
      "invokeStatic",
      "session.clj",
      438
    ],
    [
      "metabase.server.middleware.session$do_with_current_user",
      "invoke",
      "session.clj",
      421
    ],
    [
      "metabase.server.middleware.session$bind_current_user$fn__72143",
      "invoke",
      "session.clj",
      458
    ],
    [
      "metabase.server.middleware.session$wrap_current_user_info$fn__72120",
      "invoke",
      "session.clj",
      383
    ],
    [
      "metabase.analytics.sdk$embedding_mw$embedding_mw_fn__78293",
      "invoke",
      "sdk.clj",
      61
    ],
    [
      "metabase.server.middleware.session$wrap_session_id$fn__72092",
      "invoke",
      "session.clj",
      261
    ],
    [
      "metabase.server.middleware.auth$wrap_static_api_key$fn__104629",
      "invoke",
      "auth.clj",
      33
    ],
    [
      "ring.middleware.cookies$wrap_cookies$fn__114287",
      "invoke",
      "cookies.clj",
      200
    ],
    [
      "metabase.server.middleware.misc$add_content_type$fn__70093",
      "invoke",
      "misc.clj",
      28
    ],
    [
      "metabase.server.middleware.misc$disable_streaming_buffering$fn__70119",
      "invoke",
      "misc.clj",
      75
    ],
    [
      "ring.middleware.gzip$wrap_gzip$fn__114329",
      "invoke",
      "gzip.clj",
      86
    ],
    [
      "metabase.server.middleware.request_id$wrap_request_id$fn__110081",
      "invoke",
      "request_id.clj",
      9
    ],
    [
      "metabase.server.middleware.misc$bind_request$fn__70122",
      "invoke",
      "misc.clj",
      91
    ],
    [
      "metabase.server.middleware.ssl$redirect_to_https_middleware$fn__114116",
      "invoke",
      "ssl.clj",
      51
    ],
    [
      "metabase.server$async_proxy_handler$fn__56833",
      "invoke",
      "server.clj",
      77
    ],
    [
      "metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a",
      "handle",
      null,
      -1
    ],
    [
      "org.eclipse.jetty.server.handler.StatisticsHandler",
      "handle",
      "StatisticsHandler.java",
      173
    ],
    [
      "org.eclipse.jetty.server.handler.HandlerWrapper",
      "handle",
      "HandlerWrapper.java",
      122
    ],
    [
      "org.eclipse.jetty.server.Server",
      "handle",
      "Server.java",
      563
    ],
    [
      "org.eclipse.jetty.server.HttpChannel$RequestDispatchable",
      "dispatch",
      "HttpChannel.java",
      1598
    ],
    [
      "org.eclipse.jetty.server.HttpChannel",
      "dispatch",
      "HttpChannel.java",
      753
    ],
    [
      "org.eclipse.jetty.server.HttpChannel",
      "handle",
      "HttpChannel.java",
      501
    ],
    [
      "org.eclipse.jetty.server.HttpConnection",
      "onFillable",
      "HttpConnection.java",
      287
    ],
    [
      "org.eclipse.jetty.io.AbstractConnection$ReadCallback",
      "succeeded",
      "AbstractConnection.java",
      314
    ],
    [
      "org.eclipse.jetty.io.FillInterest",
      "fillable",
      "FillInterest.java",
      100
    ],
    [
      "org.eclipse.jetty.io.SelectableChannelEndPoint$1",
      "run",
      "SelectableChannelEndPoint.java",
      53
    ],
    [
      "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
      "runTask",
      "AdaptiveExecutionStrategy.java",
      421
    ],
    [
      "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
      "consumeTask",
      "AdaptiveExecutionStrategy.java",
      390
    ],
    [
      "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
      "tryProduce",
      "AdaptiveExecutionStrategy.java",
      277
    ],
    [
      "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
      "run",
      "AdaptiveExecutionStrategy.java",
      199
    ],
    [
      "org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread",
      "run",
      "ReservedThreadExecutor.java",
      411
    ],
    [
      "org.eclipse.jetty.util.thread.QueuedThreadPool",
      "runJob",
      "QueuedThreadPool.java",
      969
    ],
    [
      "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
      "doRunJob",
      "QueuedThreadPool.java",
      1194
    ],
    [
      "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
      "run",
      "QueuedThreadPool.java",
      1149
    ],
    [
      "java.lang.Thread",
      "run",
      null,
      -1
    ]
  ],
  "cause": "No matching clause: [\"embedding-iframe\" nil]",
  "message": "No matching clause: [\"embedding-iframe\" nil]"
}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-12-14",
      "tag": "v0.52.3",
      "hash": "6f76bb6"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.4 (Ubuntu 16.4-1.pgdg20.04+2)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.5+11-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.5+11-LTS",
    "os.name": "Linux",
    "os.version": "5.10.228-219.884.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

</details>

### Severity

The issue is pretty severe, as we have customers who download a daily Excel report from our dashboards and now they're blocked in doing so

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by escherize**
resolves #51386

- short circuit tracking for ignored requests
- add fall-through for ignored embedding requests

### CODE REVIEW

File: src/metabase/analytics/sdk.clj [hunk 1]
```diff
@@ -41,7 +41,8 @@
     [embedding-sdk-client :ok]       (prometheus/inc! :metabase-sdk/response-ok)
```
Comment (dpsutton) [inline src/metabase/analytics/sdk.clj:41]: i think we should relax this `condp`. Perhaps log if something comes through unrecognized? Right now it will throw an `IllegalArgumentException` and that's heavy handed.

Comment (escherize) [reply src/metabase/analytics/sdk.clj:41]: I can add some logging there, but note: I've already relaxed the condp by adding `nil` on line 45 which allows it to take any args, and never throw `IllegalArgumentException`. I can add in some logging instead of the `nil` that's acting as the fallthrough condition there, even though I think this shouldn't get hit due to the when-let on line 64.

Comment (dpsutton) [reply src/metabase/analytics/sdk.clj:41]: ah! yes you did. I'm sorry i missed that. Ignore what i said. You directly addressed it and i miss it.

Comment (escherize) [reply src/metabase/analytics/sdk.clj:42]: no worries, I added the logging! 👍

**Review by noahmoss — APPROVED** [review]
