### PR TITLE
Make sure block perm enforcement allows native queries if powering a sandbox

### LINKED ISSUE #49969: Advanced Sandboxing is Broken on 51
### Describe the bug

Advanced Sandboxing is Broken on 51

### To Reproduce

1. Go to New People -> Add Person -> Give attribute product with value as Gizmo

Image

2. Create new SQL question which will be used for sandboxing ->  

```
Select orders.* from orders
JOIN products on orders.product_id = products.id
WHERE Category = {{category}}
```

Image

3. Go to permission -> All Users -> Products -> Assign the above question to the Orders table (assign the create queries with query builder to the products table) -> Save

Image

Image

4. Login with the Sandboxed user and try to access the Orders table from the browse data. You will notice this works! 

5. Now go to new question -> Select the Orders Table -> Check that the preview works (and it works)

Image

6. Save the Question and then refresh the page. The moment you refresh the page you get:

Image

Even if the Admin created a question from the orders table this question will load with the above error. So things are very strange here

### Expected behavior

The Question should load since it's properly sandboxed

### Logs

```
[c2abaa4e-b380-4b88-8f1f-930adebdd5dc] 2024-11-13T17:37:38+01:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: You do not have permissions to run this query.
{:database_id 1,
 :started_at #t "2024-11-13T17:37:38.863542+01:00[Europe/Malta]",
 :action_id nil,
 :error_type :missing-required-permissions,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware
  {:js-int-to-string? true, :ignore-cached-results? false, :process-viz-settings? false, :userland-query? true},
  :cache-strategy nil,
  :viz-settings {},
  :database 1,
  :query {:source-table 5},
  :parameters []},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> metabase_enterprise.advanced_permissions.models.permissions.block_permissions$throw_block_permissions_exception.invokeStatic(block_permissions.clj:14)"
  "metabase_enterprise.advanced_permissions.models.permissions.block_permissions$throw_block_permissions_exception.invoke(block_permissions.clj:12)"
  "metabase_enterprise.advanced_permissions.models.permissions.block_permissions$fn__119130$check_block_permissions__119132.invoke(block_permissions.clj:34)"
  "public_settings.premium_features$dynamic_ee_oss_fn$fn__57112.doInvoke(premium_features.clj:615)"
  "query_processor.middleware.permissions$check_query_permissions_STAR_73942__73944.invokeStatic(permissions.clj:115)"
  "query_processor.middleware.permissions$check_query_permissions_STAR_73942__73944.invoke(permissions.clj:99)"
  "query_processor.middleware.permissions$check_query_permissions$fn__73971.invoke(permissions.clj:146)"
  "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__113843$check_download_permissions__113844$fn__113845.invoke(permissions.clj:91)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__74682.invoke(enterprise.clj:51)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$fn__115782$maybe_apply_column_level_perms_check__115783$fn__115784.invoke(column_level_perms_check.clj:38)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__74692.invoke(enterprise.clj:64)"
  "query_processor.execute$execute77011__77012$fn__77013.invoke(execute.clj:94)"
  "query_processor.setup$do_with_qp_setup75207__75208.invokeStatic(setup.clj:225)"
  "query_processor.setup$do_with_qp_setup75207__75208.invoke(setup.clj:216)"
  "query_processor.execute$execute77011__77012.invokeStatic(execute.clj:93)"
  "query_processor.execute$execute77011__77012.invoke(execute.clj:89)"
  "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
  "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__87801$handle_audit_app_internal_queries__87802$fn__87803.invoke(handle_audit_queries.clj:145)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__74720.invoke(enterprise.clj:103)"
  "query_processor.middleware.process_userland_query$process_userland_query_middleware77867__77868$fn__77869.invoke(process_userland_query.clj:204)"
  "query_processor.middleware.catch_exceptions$catch_exceptions77932__77933$fn__77934.invoke(catch_exceptions.clj:132)"
  "query_processor$process_query77973__77974$fn__77975.invoke(query_processor.clj:80)"
  "query_processor.setup$do_with_canceled_chan75202__75203$fn__75204.invoke(setup.clj:187)"
  "query_processor.setup$do_with_database_local_settings75195__75196$fn__75197.invoke(setup.clj:181)"
  "query_processor.setup$do_with_driver75188__75189$fn__75190$fn__75191.invoke(setup.clj:166)"
  "driver$do_with_driver.invokeStatic(driver.clj:106)"
  "driver$do_with_driver.invoke(driver.clj:101)"
  "query_processor.setup$do_with_driver75188__75189$fn__75190.invoke(setup.clj:165)"
  "query_processor.setup$do_with_metadata_provider75179__75180$fn__75181$fn__75184.invoke(setup.clj:151)"
  "query_processor.store$do_with_metadata_provider58714__58715.invokeStatic(store.clj:170)"
  "query_processor.store$do_with_metadata_provider58714__58715.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider58714__58715.invokeStatic(store.clj:159)"
  "query_processor.store$do_with_metadata_provider58714__58715.invoke(store.clj:150)"
  "query_processor.setup$do_with_metadata_provider75179__75180$fn__75181.invoke(setup.clj:150)"
  "query_processor.setup$do_with_resolved_database75169__75170$fn__75171.invoke(setup.clj:128)"
  "query_processor.setup$do_with_qp_setup75207__75208.invokeStatic(setup.clj:232)"
  "query_processor.setup$do_with_qp_setup75207__75208.invoke(setup.clj:216)"
  "query_processor$process_query77973__77974.invokeStatic(query_processor.clj:78)"
  "query_processor$process_query77973__77974.invoke(query_processor.clj:71)"
  "query_processor.card$process_query_for_card_default_qp89650__89651.invokeStatic(card.clj:186)"
  "query_processor.card$process_query_for_card_default_qp89650__89651.invoke(card.clj:182)"
  "query_processor.card$process_query_for_card_default_run_fn$fn__89653$fn__89654.invoke(card.clj:193)"
  "query_processor.streaming$_streaming_response$fn__61545$fn__61546$fn__61547.invoke(streaming.clj:176)"
  "query_processor.streaming$_streaming_response$fn__61545$fn__61546.invoke(streaming.clj:174)"
  "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
  "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
  "query_processor.streaming$_streaming_response$fn__61545.invoke(streaming.clj:171)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
  "async.streaming_response$do_f_async$task__53198.invoke(streaming_response.clj:97)"],
 :card_id 112,
 :context :question,
 :error "You do not have permissions to run this query.",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :metabase.models.query.permissions/perms
  {:gtaps {:perms/create-queries :query-builder-and-native, :perms/view-data :unrestricted}},
  :type :query,
  :middleware
  {:js-int-to-string? true, :ignore-cached-results? false, :process-viz-settings? false, :userland-query? true},
  :viz-settings {},
  :metabase-enterprise.sandbox.query-processor.middleware.row-level-restrictions/original-metadata
  [{:description
    "This is a unique ID for the product. It is also called the “Invoice number” or “Confirmation number” in customer facing emails and screens.",
    :database_type "BIGINT",
    :semantic_type :type/PK,
    :table_id 5,
    :coercion_strategy nil,
    :name "ID",
    :settings nil,
    :source :fields,
    :fk_target_field_id nil,
    :field_ref [:field 37 nil],
    :effective_type :type/BigInteger,
    :active true,
    :nfc_path nil,
    :parent_id nil,
    :id 37,
    :position 0,
    :visibility_type :normal,
    :display_name "ID",
    :fingerprint nil,
    :base_type :type/BigInteger}
   {:description
    "The id of the user who made this order. Note that in some cases where an order was created on behalf of a customer who phoned the order in, this might be the employee who handled the request.",
    :database_type "INTEGER",
    :semantic_type :type/FK,
    :table_id 5,
    :coercion_strategy nil,
    :name "USER_ID",
    :settings nil,
    :source :fields,
    :fk_target_field_id 46,
    :field_ref [:field 43 nil],
    :effective_type :type/Integer,
    :active true,
    :nfc_path nil,
    :parent_id nil,
    :id 43,
    :position 1,
    :visibility_type :normal,
    :display_name "User ID",
    :fingerprint {:global {:distinct-count 929, :nil% 0.0}},
    :base_type :type/Integer}
   {:description "The product ID. This is an internal identifier for the product, NOT the SKU.",
    :database_type "INTEGER",
    :semantic_type :type/FK,
    :table_id 5,
    :coercion_strategy nil,
    :name "PRODUCT_ID",
    :settings nil,
    :source :fields,
    :fk_target_field_id 62,
    :field_ref [:field 40 nil],
    :effective_type :type/Integer,
    :active true,
    :nfc_path nil,
    :parent_id nil,
    :id 40,
    :position 2,
    :visibility_type :normal,
    :display_name "Product ID",
    :fingerprint {:global {:distinct-count 200, :nil% 0.0}},
    :base_type :type/Integer}
   {:description
    "The raw, pre-tax cost of the order. Note that this might be different in the future from the product price due to promotions, credits, etc.",
    :database_type "DOUBLE PRECISION",
    :semantic_type nil,
    :table_id 5,
    :coercion_strategy nil,
    :name "SUBTOTAL",
    :settings nil,
    :source :fields,
    :fk_target_field_id nil,
    :field_ref [:field 44 nil],
    :effective_type :type/Float,
    :active true,
    :nfc_path nil,
    :parent_id nil,
    :id 44,
    :position 3,
    :visibility_type :normal,
    :display_name "Subtotal",
    :fingerprint
    {:global {:distinct-count 340, :nil% 0.0},
     :type
     {:type/Number
      {:min 15.691943673970439,
       :q1 49.74894519060184,
       :q3 105.42965746993103,
       :max 148.22900526552291,
       :sd 32.53705013056317,
       :avg 77.01295465356547}}},
    :base_type :type/Float}
   {:description
    "This is the amount of local and federal taxes that are collected on the purchase. Note that other governmental fees on some products are not included here, but instead are accounted for in the subtotal.",
    :database_type "DOUBLE PRECISION",
    :semantic_type nil,
    :table_id 5,
    :coercion_strategy nil,
    :name "TAX",
    :settings nil,
    :source :fields,
    :fk_target_field_id nil,
    :field_ref [:field 38 nil],
    :effective_type :type/Float,
    :active true,
    :nfc_path nil,
    :parent_id nil,
    :id 38,
    :position 4,
    :visibility_type :normal,
    :display_name "Tax",
    :fingerprint
    {:global {:distinct-count 797, :nil% 0.0},
     :type
     {:type/Number
      {:min 0.0,
       :q1 2.273340386603857,
       :q3 5.337275338216307,
       :max 11.12,
       :sd 2.3206651358900316,
       :avg 3.8722100000000004}}},
    :base_type :type/Float}
   {:description "The total billed amount.",
    :database_type "DOUBLE PRECISION",
    :semantic_type nil,
    :table_id 5,
    :coercion_strategy nil,
    :name "TOTAL",
    :settings nil,
    :source :fields,
    :fk_target_field_id nil,
    :field_ref [:field 42 nil],
    :effective_type :type/Float,
    :active true,
    :nfc_path nil,
    :parent_id nil,
    :id 42,
    :position 5,
    :visibility_type :normal,
    :display_name "Total",
    :fingerprint
    {:global {:distinct-count 4426, :nil% 0.0},
     :type
     {:type/Number
      {:min 8.93914247937167,
       :q1 51.34535490743823,
       :q3 110.29428389265787,
       :max 159.34900526552292,
       :sd 34.26469575709948,
       :avg 80.35871658771228}}},
    :base_type :type/Float}
   {:description "Discount amount.",
    :database_type "DOUBLE PRECISION",
    :semantic_type :type/Discount,
    :table_id 5,
    :coercion_strategy nil,
    :name "DISCOUNT",
    :settings nil,
    :source :fields,
    :fk_target_field_id nil,
    :field_ref [:field 36 nil],
    :effective_type :type/Float,
    :active true,
    :nfc_path nil,
    :parent_id nil,
    :id 36,
    :position 6,
    :visibility_type :normal,
    :display_name "Discount",
    :fingerprint
    {:global {:distinct-count 701, :nil% 0.898},
     :type
     {:type/Number
      {:min 0.17088996672584322,
       :q1 2.9786226681458743,
       :q3 7.338187788658235,
       :max 61.69684269960571,
       :sd 3.053663125001991,
       :avg 5.161255547580326}}},
    :base_type :type/Float}
   {:description "The date and time an order was submitted.",
    :database_type "TIMESTAMP",
    :semantic_type :type/CreationTimestamp,
    :table_id 5,
    :coercion_strategy nil,
    :name "CREATED_AT",
    :settings nil,
    :source :fields,
    :fk_target_field_id nil,
    :field_ref [:field 41 nil],
    :effective_type :type/DateTime,
    :active true,
    :nfc_path nil,
    :parent_id nil,
    :id 41,
    :position 7,
    :visibility_type :normal,
    :display_name "Created At",
    :fingerprint
    {:global {:distinct-count 10001, :nil% 0.0},
     :type {:type/DateTime {:earliest "2022-04-30T18:56:13.352Z", :latest "2026-04-19T14:07:15.657Z"}}},
    :base_type :type/DateTime}
   {:description "Number of products bought.",
    :database_type "INTEGER",
    :semantic_type :type/Quantity,
    :table_id 5,
    :coercion_strategy nil,
    :name "QUANTITY",
    :settings nil,
    :source :fields,
    :fk_target_field_id nil,
    :field_ref [:field 39 nil],
    :effective_type :type/Integer,
    :active true,
    :nfc_path nil,
    :parent_id nil,
    :id 39,
    :position 8,
    :visibility_type :normal,
    :display_name "Quantity",
    :fingerprint
    {:global {:distinct-count 62, :nil% 0.0},
     :type
     {:type/Number
      {:min 0.0, :q1 1.755882607764982, :q3 4.882654507928044, :max 100.0, :sd 4.214258386403798, :avg 3.7015}}},
    :base_type :type/Integer}],
  :info {:executed-by 2, :context :question, :card-id 112, :card-name "Orders"},
  :database 1,
  :query
  {:fields
   [[:field 37 nil]
    [:field 43 nil]
    [:field 40 nil]
    [:field 44 nil]
    [:field 38 nil]
    [:field 42 nil]
    [:field 36 nil]
    [:field 41 nil]
    [:field 39 nil]],
   :source-query
   {:params ["Gizmo"],
    :native "Select orders.* from orders\nJOIN products on orders.product_id = products.id\nWHERE Category = ?"},
   :source-metadata
   [{:description
     "This is a unique ID for the product. It is also called the “Invoice number” or “Confirmation number” in customer facing emails and screens.",
     :database_type "BIGINT",
     :semantic_type :type/PK,
     :table_id 5,
     :name "ID",
     :source :fields,
     :field_ref [:field 37 nil],
     :effective_type :type/BigInteger,
     :active true,
     :id 37,
     :position 0,
     :visibility_type :normal,
     :display_name "ID",
     :base_type :type/BigInteger}
    {:description
     "The id of the user who made this order. Note that in some cases where an order was created on behalf of a customer who phoned the order in, this might be the employee who handled the request.",
     :database_type "INTEGER",
     :semantic_type :type/FK,
     :table_id 5,
     :name "USER_ID",
     :source :fields,
     :fk_target_field_id 46,
     :field_ref [:field 43 nil],
     :effective_type :type/Integer,
     :active true,
     :id 43,
     :position 1,
     :visibility_type :normal,
     :display_name "User ID",
     :fingerprint {:global {:distinct-count 929, :nil% 0.0}},
     :base_type :type/Integer}
    {:description "The product ID. This is an internal identifier for the product, NOT the SKU.",
     :database_type "INTEGER",
     :semantic_type :type/FK,
     :table_id 5,
     :name "PRODUCT_ID",
     :source :fields,
     :fk_target_field_id 62,
     :field_ref [:field 40 nil],
     :effective_type :type/Integer,
     :active true,
     :id 40,
     :position 2,
     :visibility_type :normal,
     :display_name "Product ID",
     :fingerprint {:global {:distinct-count 200, :nil% 0.0}},
     :base_type :type/Integer}
    {:description
     "The raw, pre-tax cost of the order. Note that this might be different in the future from the product price due to promotions, credits, etc.",
     :database_type "DOUBLE PRECISION",
     :table_id 5,
     :name "SUBTOTAL",
     :source :fields,
     :field_ref [:field 44 nil],
     :effective_type :type/Float,
     :active true,
     :id 44,
     :position 3,
     :visibility_type :normal,
     :display_name "Subtotal",
     :fingerprint
     {:global {:distinct-count 340, :nil% 0.0},
      :type
      {:type/Number
       {:min 15.691943673970439,
        :q1 49.74894519060184,
        :q3 105.42965746993103,
        :max 148.22900526552291,
        :sd 32.53705013056317,
        :avg 77.01295465356547}}},
     :base_type :type/Float}
    {:description
     "This is the amount of local and federal taxes that are collected on the purchase. Note that other governmental fees on some products are not included here, but instead are accounted for in the subtotal.",
     :database_type "DOUBLE PRECISION",
     :table_id 5,
     :name "TAX",
     :source :fields,
     :field_ref [:field 38 nil],
     :effective_type :type/Float,
     :active true,
     :id 38,
     :position 4,
     :visibility_type :normal,
     :display_name "Tax",
     :fingerprint
     {:global {:distinct-count 797, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0,
        :q1 2.273340386603857,
        :q3 5.337275338216307,
        :max 11.12,
        :sd 2.3206651358900316,
        :avg 3.8722100000000004}}},
     :base_type :type/Float}
    {:description "The total billed amount.",
     :database_type "DOUBLE PRECISION",
     :table_id 5,
     :name "TOTAL",
     :source :fields,
     :field_ref [:field 42 nil],
     :effective_type :type/Float,
     :active true,
     :id 42,
     :position 5,
     :visibility_type :normal,
     :display_name "Total",
     :fingerprint
     {:global {:distinct-count 4426, :nil% 0.0},
      :type
      {:type/Number
       {:min 8.93914247937167,
        :q1 51.34535490743823,
        :q3 110.29428389265787,
        :max 159.34900526552292,
        :sd 34.26469575709948,
        :avg 80.35871658771228}}},
     :base_type :type/Float}
    {:description "Discount amount.",
     :database_type "DOUBLE PRECISION",
     :semantic_type :type/Discount,
     :table_id 5,
     :name "DISCOUNT",
     :source :fields,
     :field_ref [:field 36 nil],
     :effective_type :type/Float,
     :active true,
     :id 36,
     :position 6,
     :visibility_type :normal,
     :display_name "Discount",
     :fingerprint
     {:global {:distinct-count 701, :nil% 0.898},
      :type
      {:type/Number
       {:min 0.17088996672584322,
        :q1 2.9786226681458743,
        :q3 7.338187788658235,
        :max 61.69684269960571,
        :sd 3.053663125001991,
        :avg 5.161255547580326}}},
     :base_type :type/Float}
    {:description "The date and time an order was submitted.",
     :database_type "TIMESTAMP",
     :semantic_type :type/CreationTimestamp,
     :table_id 5,
     :name "CREATED_AT",
     :source :fields,
     :field_ref [:field 41 nil],
     :effective_type :type/DateTime,
     :active true,
     :id 41,
     :position 7,
     :visibility_type :normal,
     :display_name "Created At",
     :fingerprint
     {:global {:distinct-count 10001, :nil% 0.0},
      :type {:type/DateTime {:earliest "2022-04-30T18:56:13.352Z", :latest "2026-04-19T14:07:15.657Z"}}},
     :base_type :type/DateTime}
    {:description "Number of products bought.",
     :database_type "INTEGER",
     :semantic_type :type/Quantity,
     :table_id 5,
     :name "QUANTITY",
     :source :fields,
     :field_ref [:field 39 nil],
     :effective_type :type/Integer,
     :active true,
     :id 39,
     :position 8,
     :visibility_type :normal,
     :display_name "Quantity",
     :fingerprint
     {:global {:distinct-count 62, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0, :q1 1.755882607764982, :q3 4.882654507928044, :max 100.0, :sd 4.214258386403798, :avg 3.7015}}},
     :base_type :type/Integer}],
   :limit 2000,
   :metabase.query-processor.middleware.limit/original-limit nil}},
 :ex-data
 {:type :missing-required-permissions,
  :actual-permissions
  #{"/collection/2/"
    "/collection/namespace/snippets/root/"
    "/collection/1/"
    "/collection/root/"
    "/application/subscription/"
    "/collection/6/"},
  :permissions-error? true},
 :data {:rows [], :cols []}}
```

### Information about your Metabase installation

```JSON
51.3 (doesn't happen on 50.33)
```

### Severity

Blocker cause it breaks Advanced serialization

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Resolves https://github.com/metabase/metabase/issues/49969

https://github.com/metabase/metabase/pull/49364 moved block permission enforcement explicitly back to EE code in the `check-block-permissions` function, as it was before we introduced table-level block.

However, the `check-block-permissions` did not take into account the `gtap-perms` key in the query, added by sandboxing middleware, which contains permissions which should be implicitly granted to the current user to allow sandboxing to function. I guess this wasn't needed before table-level block, since block and sandboxing couldn't live side-by-side. But now, you can have a native sandbox in one table and block perms in a different table, and we should allow the sandboxed query to execute despite the user not having native query perms for the DB.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#49974** <a href="https://app.graphite.dev/github/pr/metabase/metabase/49974?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: src/metabase/query_processor/middleware/permissions.clj [hunk 1]
```diff
@@ -108,11 +108,12 @@
     (let [card-id         (or *card-id* (:qp/source-card-id outer-query))
           required-perms  (query-perms/required-perms-for-query outer-query :already-preprocessed? true)
           source-card-ids (set/difference (:card-ids required-perms) (:card-ids gtap-perms))]
+      ;; On EE, check block permissions up front for all queries. If block perms are in place, reject all native queries
+      ;; (unless overriden by `gtap-perms`) and any queries that touch blocked tables/DBs
+      (check-block-permissions outer-query)
```
Comment (noahmoss) [inline src/metabase/query_processor/middleware/permissions.clj:113]: I moved this up since I think we should do the explicit block perm check unconditionally, not just for saved cards. It results in a redundancy since `query-perms/check-data-perms` will also reject the same queries for not having the minimum required data perms. But I think this approach is safer and avoids confusing cases like the original issue where there's a different behavior before and after saving a card. I can change it back if anyone disagrees.

**Review by johnswanson — APPROVED** [review]
LGTM!
