### PR TITLE
Detect the use of unsupported features in the expression editor

### LINKED ISSUE #39773: Show better error message when function is not supported by the database
### Describe the bug

Currently when a function is not supported by the database, we don't show an error message.
In some cases we even show an error that is about calling the function incorrectly, even though it does not exist.

### To Reproduce

1. New Question → MariaDB instance
2. Select a table
3. Add an aggregation and select Custom Expression
4. Type `percentile(1, 0.9)`
5. Tab out of the expression field
6. No error is show
7. Now type `percentile(1)` in the expression field and tab out
8. An error is displayed: `Function Percentile expects 2 arguments`, even though this database does not support `percentile`

### Expected behavior

There should be an error when a function is called that is not supported

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Mac OS X",
    "os.version": "14.2.1",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2024-03-07",
      "src_hash": "e35fc04830cd05dc48aa5d85ab07fc5c2eade141",
      "tag": "v0.48.1-SNAPSHOT",
      "hash": "a5261dc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3

### Additional context

This is related to https://github.com/metabase/metabase/issues/35156

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/39773

### Description

This adds an extra check to the diagnostics to make sure a functions is supported by the database in the custom expression editor.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question → Sample Dataset → Orders (or any database that does not support `percentile-aggregations`)
2. Click "Pick the metric you want to see" → Custom Expression
3. In the expression editor, type `percentile([Discount], 0.9)`
4. Tab out of the expression editor text field
5. An error should show up: `Unsupported function percentile`

### Demo

Screenshot 2024-03-07 at 16 49 50

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase-lib/expressions/resolver.js [hunk 1]
```diff
@@ -152,6 +158,11 @@ export function resolve(expression, type = "expression", fn = undefined) {
     if (!clause) {
       throw new ResolverError(t`Unknown function ${op}`, expression.node);
     }
+
+    if (database && !database.hasFeature(clause)) {
```
Comment (kamilmielnik) [inline frontend/src/metabase-lib/expressions/resolver.js:162]: `clause` is an object, `Database.prorotype.hasFeature` accepts a `string`.
Currently it's not possible to use any function :see_no_evil: 

```suggestion
    if (database && !database.hasFeature(clause.displayName)) {
```

File: frontend/src/metabase-lib/expressions/resolver.js [hunk 2]
```diff
@@ -73,8 +73,14 @@ const isCompatible = (a, b) => {
...
  * @param {string} type
  * @param {?(kind: string, name: string, node: import("./pratt").Node) => void} fn
+ * @param {Database | null} database
  */
-export function resolve(expression, type = "expression", fn = undefined) {
+export function resolve(
+  expression,
+  type = "expression",
+  fn = undefined,
+  database,
```
Comment (kamilmielnik) [inline frontend/src/metabase-lib/expressions/resolver.js:82]: nit: optional arguments should go last

Maybe in this case we'd be better off with a param object instead of N arguments.

**Review by kamilmielnik — CHANGES_REQUESTED** [review]
There's 1 mistake and code has not been updated everywhere (see failing `type-check` job).

File: frontend/src/metabase-lib/expressions/resolver.js (hunk 1 above)
Comment (romeovs) [reply frontend/src/metabase-lib/expressions/resolver.js]: My brain must've been turned of when I wrote this. I've fixed this and added database to the recursive `resolve` calls too.

File: frontend/src/metabase-lib/expressions/resolver.js [hunk 3]
```diff
@@ -69,12 +69,19 @@ const isCompatible = (a, b) => {
...
+ *   fn?: ?(kind: string, name: string, node: import("./pratt").Node) => void
+ *   database?: Database | null
+ * }} options
  */
-export function resolve(expression, type = "expression", fn = undefined) {
+export function resolve({
+  expression,
+  type = "expression",
+  fn = undefined,
+  database = undefined,
```
Comment (kamilmielnik) [inline frontend/src/metabase-lib/expressions/resolver.js:83]: Should we make `database` required and pass it in all of the calls?
e2e tests for custom columns are failing, this might be related.

Comment (romeovs) [reply frontend/src/metabase-lib/expressions/resolver.js:83]: Not sure what to do here: the tests are broken because they incorrectly assumed that the built in database supports the `convert-timezone` features, whereas it does not.

I think the only correct way to fix this is to remove that case from the test, but then we don't have a test for those functions anymore.

**Review by kamilmielnik — APPROVED** [review]
I'm not sure if it's ready for review but LGTM :+1:

File: e2e/test/scenarios/custom-column/cc-data-type.cy.spec.js [hunk 4]
```diff
@@ -132,11 +139,11 @@ function addCustomColumns(columns) {
     if (index) {
       getNotebookStep("expression").icon("add").click();
     } else {
-      cy.findByText("Custom column").click();
+      cy.findByLabelText("Custom column").click();
     }
 
     enterCustomColumnDetails(column);
-    cy.button("Done").click();
+    cy.button("Done").click({ force: true });
```
Comment (kamilmielnik) [inline e2e/test/scenarios/custom-column/cc-data-type.cy.spec.js:146]: It should just work. Why do we need `force: true`?

Comment (romeovs) [reply e2e/test/scenarios/custom-column/cc-data-type.cy.spec.js:146]: Because the help text popover might still be covering the button.

I could add timeouts to wait for it to go away, but I think this is more robust.

Comment (kamilmielnik) [reply e2e/test/scenarios/custom-column/cc-data-type.cy.spec.js]: It might be a good idea to [stress-test](https://github.com/metabase/metabase/actions/workflows/e2e-stress-test-flake-fix.yml) this change.
