### PR TITLE
fix: allow postgres downloads to use ddl sql

### LINKED ISSUE #61892: Postgres Downloads Fail for Native SQL that Contains Functions with DDL Statements
### Describe the bug

If you have a function in Postgres that contains DDL statements the Question runs as expected. When you attempt to download the question it fails with:

> "status":"failed","class":"class clojure.lang.ExceptionInfo","error":"Error executing query: ERROR: cannot execute DROP TABLE in a read-only transaction\n 

From reporting customer:

"CTEs are not an option in our case – we are going over DB links, and using CTE is highly inefficient. Which is why we use temp tables, to get data from one DB locally (into temp table), then another, etc. – and then join temp tables together in the same environment to produce results."

### To Reproduce

1. Create a function in Postgres that contains DDL statements

```
-- DROP TABLE public.faux_table;

CREATE TABLE public.faux_table (
	created_at timestamp NOT NULL,
	updated_at timestamp NOT NULL,
	organization_id uuid NOT NULL
);


-- DROP FUNCTION public.recreate_and_load_faux_table();

CREATE OR REPLACE FUNCTION public.recreate_and_load_faux_table()
 RETURNS SETOF faux_table
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Create temp table to hold intermediate data
    CREATE TEMP TABLE temp_faux_table (
        created_at timestamp NOT NULL,
        updated_at timestamp NOT NULL,
        organization_id uuid NOT NULL
    ) ON COMMIT DROP;

    -- Insert fake/generated data into temp table
    INSERT INTO temp_faux_table (
        created_at, updated_at, organization_id
    )
    SELECT
        now() - (random() * interval '30 days'),
        now(),
        gen_random_uuid()
    FROM generate_series(1, 10);

    TRUNCATE public.faux_table;

    INSERT INTO public.faux_table
    SELECT * FROM temp_faux_table;

    -- Return the freshly loaded data
    RETURN QUERY SELECT * FROM public.faux_table;
END;
$function$;
```

2. Call the function from the native editor in Metabase:

`select * from public.recreate_and_load_faux_table();`

3. See error

### Expected behavior

If a query can be executed in the native editor then it should also be downloadable.

### Logs

_No response_

### Information about your Metabase installation

```JSON
55.8.5 (works in prior 55 versions)
```

### Severity

blocking a customer

### Additional context

Probably caused by this OOM fix:
https://github.com/metabase/metabase/pull/60807

### PR DESCRIPTION
**Pull request by edpaget**
closes #61892
### Description

Fixes a regression where making sure the autocommit was correctly set to enable reading streaming result sets disallowed ddl and other non-readonly changes in postgresql due to the interaction of the 'readOnly', 'readOnlyMode', and 'autoCommit' jdbc driver settings.

### Checklist

- [N/A] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/driver/sql_jdbc/execute.clj [hunk 1]
```diff
@@ -377,7 +377,11 @@
     (log/tracef "Setting default connection options with options %s" (pr-str options))
     (set-best-transaction-level! driver conn)
     (set-time-zone-if-supported! driver conn session-timezone)
-    (let [read-only? (not write?)]
+    (let [read-only? (not (or write?
+                              ;; we need to set autoCommit to false which causes postgresql
+                              ;; to enforce readOnly which will break queries that rely on
+                              ;; ddl statements, etc (#61892)
+                              (and (-> options :download?) (= driver :postgres))))]
```
Comment (johnswanson) [inline src/metabase/driver/sql_jdbc/execute.clj:384]: On line 411 below we do `(isa? driver/hierarchy driver :postgres)` for essentially the same check. Wondering if we want to do the same (not sure if there's an effective difference though, I suppose someone might write their own driver that inherits form `:postgres`?)

Comment (edpaget) [reply src/metabase/driver/sql_jdbc/execute.clj:384]: I think that was the idea in Dan's original fix. That Redshift, which inherits from postgres, doesn't have the same issue with autocommit and result streaming.

**Review by johnswanson — APPROVED** [review]
