### PR TITLE
Adjust distinct aggregation expansion on Mongo

### LINKED ISSUE #35425: Using MongoDB, creating a custom expression that operates a number by the Distinct aggregation fails because of lack of $size aggregation
### Describe the bug

The aggregation pipeline is encountering an error when attempting to use the $divide operator to calculate the ratio of a number to the count of unique elements. The error message received is: "$divide only supports numeric types, not long and array."

When executing the provided MongoDB aggregation pipeline, an error occurs at the $divide stage. The issue seems to stem from the incorrect usage of the $divide operator. The pipeline attempts to divide a numeric value by an array, which is the result of the $addToSet operator. This operation is not supported, as $divide only works with numeric types.

### To Reproduce

1. Create a custom expression like this `Count / Distinct([column])`
2. execute and see error 

### Expected behavior

It should return a number

### Logs

_No response_

### Information about your Metabase installation

```JSON
Metabase version: 0.47.6
MongoDB version: 6.0.11
```

### Severity

Medium

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes  #35425

### Description

This PR modifies expressions that are used in `$addFields` stage in aggregation transformation. Specifically, names that are result of `:distinct` aggregation are wrapped in `$size` to produce actual counts.

### How to verify

- Existing test was modified to check for the new behavior.
- New test was added to check compilation of more complex case.
- New test was added to ensure querying works as expected even more complex case.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 1]
```diff
@@ -46,9 +46,6 @@
 ;; this is just a very limited schema to make sure we're generating valid queries. We should expand it more in the
 ;; future
 
-(def ^:private $addFields
-  :$addFields)
-
```
Comment (lbrdnk) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:51]: Operators are defined as strings. This removal produces consistent compilation results in modified test, ie. also `$addFields` is string in compiled query.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 2]
```diff
@@ -1127,6 +1122,32 @@
...
+(defn- adjust-distinct-aggregations
+  "This function transforms `aggr-expr'` as in [[expand-aggregations]] so identifiers representing array that is
+  a set of _distinct_ values are wrapped in `{$size...}.
+
+  `aggr-expr` is expected to be a clause that is a result of [[extract-aggregations]]. For details see its docstring.
+
+  Distinct values are computed using the `$addToSet` in a `$group` stage. `$size` transforms them to actual count.
+
+  If there is a need for more _pre-post_ transformations (as per results of [[expand-aggregations]]), this function
+  should be generalized."
```
Comment (bshepherdson) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:1134]: It's not clear what this means. I'd either turn this into a `TODO` comment that calls out a specific weakness to be fixed later, or just remove this sentence.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 3]
```diff
@@ -1127,6 +1122,32 @@
...
+                                  ;; are used match against `aggr-expr` where identifiers have the prefix.
+                                  (map #(str \$ %)))
+                            distinct-keys)
+        aggr-expr' (walk/postwalk (fn [x]
+                                    (if (and (string? x)
+                                             (distinct-vals x))
+                                      {$size x}
+                                      x))
+                                  aggr-expr)]
+    [aggr-expr' mappings]))
```
Comment (bshepherdson) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:1149]: No need for an extra `let` binding here; this can be inlined into the output clause.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 4]
```diff
@@ -1136,9 +1157,11 @@
   usually does) refer to the fields introduced by the preceding maps."
   [aggr-expr]
   (let [aggr-name (annotate/aggregation-name (:query *query*) aggr-expr)
-        [aggr-expr' aggregations-seen] (simplify-extracted-aggregations
-                                        aggr-name
-                                        (extract-aggregations aggr-expr aggr-name))
+        [aggr-expr' aggregations-seen] (-> (simplify-extracted-aggregations
+                                            aggr-name
+                                            (extract-aggregations aggr-expr aggr-name))
+                                           adjust-distinct-aggregations)
```
Comment (bshepherdson) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:1163]:
```suggestion
        [aggr-expr' aggregations-seen] (->> (extract-aggregations aggr-expr aggr-name)
                                            (simplify-extracted-aggregations aggr-name)
                                            adjust-distinct-aggregations)
```

File: modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj [hunk 5]
```diff
@@ -284,6 +285,32 @@
                                [:distinct $price]]
                  :limit       5})))))))
 
+(deftest ^:parallel multiple-aggregations-with-distinct-count-expression-test
+  (mt/test-driver
+   :mongo
+   (testing "Should generate correct queries for `:distinct` in expressions ()"
```
Comment (bshepherdson) [inline modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj:291]: Missing the bug number?

**Review by bshepherdson — APPROVED** [review]
Good stuff, just some Clojure code polishing.

File: modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj (hunk 5 above)
Comment (lbrdnk) [reply modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj]: Thanks.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 3 above)
Comment (lbrdnk) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:1146]: In context of the following function, `expand-aggregations`, I've deliberately decided to have an explicit var `aggr-expr'`, to signal _on the first sight_ that returned value has a same shape as what's used in the other function. I've also decided to bind the `distinct-keys` var, despite it could have been omitted by moving filter into transducer composition on the next line. I, subjectively, find this form easier on eyes of future reader.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 2 above)
Comment (lbrdnk) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj]: By `pre-post transformations` I mean transformations that are necessary on `:post` key of `expand-aggregations` return value. Even if meaning of the comment was evident, its added value is questionable. Removed.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 3 above)
Comment (lbrdnk) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj]: But as I'm not the only future reader I did as suggested :)

**Comment by lbrdnk** [comment]
@metabase-bot backport release-x.49.x
