### PR TITLE
Fix #14327: Collapsed calendar prevented adding a date filter

### LINKED ISSUE #14327: Cannot add (date) filter if calendar is collapsed
**Describe the bug**
It is not possible to click "Add filter" button when calendar is collapsed.

**Logs**
N/A

**To Reproduce**
1. Ask a question > Custom question > Sample Dataset > Orders
2. Add filter > Created At
3. Choose "Before" (or any option that requires calendar picker)
4. Click on the calendar icon to hide it
5. Feel free to update the date in the input field, although it is not necessary for this reproduction
5. Click on "Add filter" button - note that it doesn't work
6. Click on calendar icon again to expand the calendar
7. It is now possible to add filter

**Expected behavior**
One should be able to add a filter without using the calendar picker and with calendar being collapsed.

**Screenshots**
_The screenshot is showing an SQL question with a filter, but the mechanics of this bug are the same._

**Information about your Metabase Installation:**
- Local dev environment, latest master... it doesn't seem to matter (tested as back as v0.34)
- H2

**Severity**
Probably P3.

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
READY

### What does this PR accomplish?
- Fixes #14327 by setting a hidden overflow to the parent of a collapsed calendar

### How to test this manually?
- `yarn test-cypress-open`
- `frontend/test/metabase/scenarios/question/filter.cy.spec.js`
- All tests should pass

*Alternatively, follow the steps from the original issue and try to add a filter when the calendar is collapsed.

### Additional notes:
- All tests in CI should pass

`frontend/src/metabase/components/ExpandingContent.jsx` is used in two files only:
- `frontend/src/metabase/query_builder/components/filters/pickers/SpecificDatePicker.jsx`
- `frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx`

It doesn't seem like this can introduce a greater risk of breaking something, but let's err on the side of caution.

The original issue wasn't only blocking a filter button. It was possible to actually click anywhere on the calendar without knowing it, because it was only "invisible" (opacity set to 0). 
Please see the following [GIF](https://share.getcloudapp.com/ApuRKnyy)

Calendar's parent was collapsed (with `max-height` set to 0), but because there wasn't an overflow control in place, its children were exposed.

### CODE REVIEW

File: frontend/src/metabase/components/ExpandingContent.jsx [hunk 1]
```diff
@@ -59,6 +59,7 @@ class ExpandingContent extends Component {
           transition: `all ${duration}ms ease`,
           maxHeight: !animateHeight || isOpen ? maxHeight : 0,
           opacity: !animateOpacity || isOpen ? 1 : 0,
+          overflow: isOpen ? null : "hidden",
         }}
```
Comment (paulrosenzweig) [inline frontend/src/metabase/components/ExpandingContent.jsx:63]:
```suggestion
        }}
        className={cx({"overflow-hidden": !isOpen})}
```

This probably has the same effect assuming there's no weird css precedence issues. This uses a class instead style, which is better in case we need to override something. It won't matter here though, so either way works for me.

**Review by paulrosenzweig — APPROVED** [review]

File: frontend/src/metabase/components/ExpandingContent.jsx (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/components/ExpandingContent.jsx:63]: I like this approach a lot. It's even cleaner and I agree - we should always strive for classes over inline styles. And I learned something new about our system today, which is awesome. Thank you.

However, until we resolve the issue of including CSS twice, I'd leave this as a style for now.

Comment (paulrosenzweig) [reply frontend/src/metabase/components/ExpandingContent.jsx:63]: > until we resolve the issue of including CSS twice, I'd leave this as a style for now

We should fix that, but why avoid using classes before it's fixed?

Comment (nemanjaglumac) [reply frontend/src/metabase/components/ExpandingContent.jsx:63]: To avoid having it included twice. Although, one line will not make any difference - it just felt weird.
Ok, I'll switch to class.

Comment (paulrosenzweig) [reply frontend/src/metabase/components/ExpandingContent.jsx]: Oh I see. The "overflow-hidden" class is already in our styles, so I guess it's already being repeated haha. But I agree that even if you were adding a class here the additional line or two wouldn't make a difference.
