### PR TITLE
Duplicate question button missing, when question is in a view-only collection

### LINKED ISSUE #22726: Duplicate question button missing, when question is in a view-only collection
**Describe the bug**
Duplicate question button missing, when question is in a view-only collection, but the user has data permissions.

**To Reproduce**
1. Admin: Question > Sample > Orders - save as "Q1" to "Our analytics"
2. User: go to "Q1" - click the title to expand the sidebar, which shows "Duplicate this question"
image
3. Admin: Admin > Permissions > Collections > set "Our analytics" to `View` for "All users"
4. User: go to "Q1" - click the title to expand the sidebar, which does not show duplicate button
image

**Expected behavior**
It should be possible to use duplicate button if the user has the sufficient data permissions.
If the user does not have data permissions (eg. no SQL write), then it should not show this button.

**Information about your Metabase Installation:**
Tested 0.42.4 and 0.43.0

**Additional context**
Related to #15255

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/22726
Reproduces https://github.com/metabase/metabase/issues/22726

How to test:
- Create a question and save it in `Our analytics`
- Go to Admin -> Permissions and change access `All Users` -> `Our analytics` to view-only.
- You would need a non-admin user. Go to Admin -> People and create one if there is none yet.
- Login as this user and open the saved question.
- Open the question menu and click on `Duplicate`
- Make sure the suggested collection is not `Our analytics` since the user doesn't have access to it.

Screenshot 2022-07-26 at 16 35 52

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/QueryModals.jsx [hunk 1]
```diff
@@ -211,10 +217,15 @@ class QueryModals extends React.Component {
       <Modal onClose={onCloseModal}>
         <EntityCopyModal
           entityType="questions"
-          entityObject={this.props.card}
+          entityObject={{
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/components/QueryModals.jsx:220]: Might be cleaner if we declare an entityObject constant above this return, and have a more direct
`entityObject={entityObject}`
here.

File: frontend/src/metabase/query_builder/components/QueryModals.jsx [hunk 2]
```diff
@@ -211,10 +217,15 @@ class QueryModals extends React.Component {
...
+            ...question.card(),
+            collection_id: question.canWrite()
+              ? question.collectionId()
+              : initialCollectionId,
+          }}
           copy={async formValues => {
             const object = await this.props.onCreate({
-              ...this.props.card,
+              ...question.card(),
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/components/QueryModals.jsx:228]: I'd say extracting this function should make this component easier to understand.

**Review by gusaiani — COMMENTED** [review]
Awesome, thank you very much @ranquild  👍

Two inlined comments, not central to the PR.

**Review by gusaiani — APPROVED** [review]
Should've been an approval above.
