### PR TITLE
Ensure we use a different connection per `have-select-privilege?` call

### LINKED ISSUE #58304: Metabase Does Not Work on Oracle (sync fails when trying to sync tables without privileges)
Arakaki edit:
- The problem here is that sync is dying when trying to get metadata from tables we don't have access to. This shouldn't happen, sync should be resilient to this kind of problem.
- Simply ignoring `APEX_` and `ORDS_` tables isn't a good solution because there might be valid reasons to sync these tables.

### Describe the bug

Oracle Apex is a Oracle product for low code development on Oracle Databases. Although it is a separated product, Oracle actually license Apex on any licensed Oracle DBMS. That means it is nowadays extremely popular and expected to be present in most Oracle DBMS intances.

When installed, Apex creates a schema named APEX_[Version] on the database. That schema is a black box and stores Apex source code and Metadata. It should keep untouched. Whenever upgraded, Apex will add new APEX_[Version] schemas to the database and keep the older ones for its own purposes.

Due to the intensive release pace, it's impossible to keep privileges on those schemas and their hundreds objects so that Metabase sync it. Also, APEX objects shouldn't be shown on Metabase metadata.

Right now, Metabase already deal with this, but in a faulty manner given a single old Apex version is hard coded.

(https://github.com/metabase/metabase/blob/master/modules%2Fdrivers%2Foracle%2Fsrc%2Fmetabase%2Fdriver%2Foracle.clj#L596-L597).

That mean Metabase will not sync metadata from virtually any Oracle Database other then the hard coded one. It will always break by absent privilege on one of the many (and always mutating) Apex objects.

Metabase should ignore all Oracle schemas prefixed "APEX_". The same applies for "ORDS_" prefixed schemas (also part of Apex "stack")

### To Reproduce

1. Connect metabase to a Oracle with Apex installed (not the old version hard coded)
2. Try to sync the metadata
3. The process breaks with error on some Apex table/view before it ends
4. Metabase Logs register a exception.

### Expected behavior

Metabase should ignore all Oracle schemas prefixed "APEX_". The same applies for "ORDS_" prefixed schemas (also part of Apex "stack")

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "h2",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-05-21",
      "tag": "v0.54.9.1",
      "hash": "5baf7ff"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.4 (Debian 17.4-1.pgdg120+2)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "6.8.0-55-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

SEVERE

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bronsa**
closes #58304
Closes: https://linear.app/metabase/issue/SEM-349/metabase-does-not-work-on-oracle-sync-fails-when-trying-to-sync-tables

# Description
In some permission-related error scenarios, certain databases may abruptly close a JDBC connection instead of simply throwing an exception. During sync, we check whether the current user has SELECT access to a table by issuing a probing SELECT quer. This can inadvertently trigger such connection closures.

Currently, the sync process uses a single database connection to probe all tables. If that connection is closed due to one of these permission errors, the entire sync fails.

This PR resolves the issue by executing each probing query using a separate database connection. This allows the connection pool to automatically handle reconnections if any are closed during the process.

As a result of scoping connections more narrowly, some functions needed to be updated to return concrete sequences instead of reducibles. This ensures that the data is materialized before the corresponding connection is closed. While this slightly changes how results are processed (e.g., mapping over sequences instead of reducibles), the memory footprint remains the same, and the performance impact should be minimal.

### CODE REVIEW

File: src/metabase/driver/sql_jdbc/sync/interface.clj [hunk 1]
```diff
@@ -15,7 +15,7 @@
   functions for more details on the differences."
   {:added "0.37.1"
    :arglists '([driver
-                ^java.sql.Connection connection
+                database
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/sync/interface.clj:18]: I think this, and the following signature changes should be documented in `driver-changelog.yml`. Looping in @luizarakaki: how to do that reasonably? Is merging this to master and messaging prior 56 enough of action from our side? Should that take more versions?

File: src/metabase/driver/sql_jdbc/sync/describe_database.clj [hunk 2]
```diff
@@ -160,40 +180,38 @@
...
         (if (#{[:postgres "FOREIGN TABLE"]}
              [driver ttype])
-          (sql-jdbc.sync.interface/have-select-privilege? driver conn schema table)
+          (have-selected-privilege? driver database schema table)
           (contains? schema+table-with-select-privileges [schema table]))))
     (fn [{schema :schema table :name}]
-      (sql-jdbc.sync.interface/have-select-privilege? driver conn schema table))))
+      (have-selected-privilege? driver database schema table))))
 
 (defn fast-active-tables
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/sync/describe_database.clj:200]: This is public, meaning we should let the community know about the change in advance.

File: src/metabase/driver/sql_jdbc/sync/describe_database.clj [hunk 3]
```diff
@@ -133,24 +139,38 @@
...
+          (map (juxt :schema :table))
+          set))))
+
+(defn- have-selected-privilege? [driver database schema table]
+  (sql-jdbc.execute/do-with-connection-with-options
+   driver database nil
+   (fn [^Connection conn]
+     (sql-jdbc.sync.interface/have-select-privilege? driver conn schema table))))
 
 (defn have-select-privilege-fn
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/sync/describe_database.clj:175]: Same as with rest of my "this is public" comments applies here.

File: src/metabase/driver/sql_jdbc/sync/describe_database.clj [hunk 4]
```diff
@@ -133,24 +139,38 @@
 
 (defn db-tables
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/sync/describe_database.clj:140]: Same as with rest of my "this is public" comments applies here.

File: src/metabase/driver/sql_jdbc/sync/describe_database.clj [hunk 5]
```diff
@@ -96,13 +102,13 @@
...
-                    (str (when table-schema
-                           (str (pr-str table-schema) \.))
-                         (pr-str table-name)))
+        (let [allow? (driver/query-canceled? driver e)
+              table-str (str (when table-schema
+                               (str (pr-str table-schema) \.))
+                             (pr-str table-name))]
+          (if allow?
+            (log/infof "%s: Assuming SELECT privileges: caught timeout exception" table-str)
+            (log/infof e "%s: Assuming no SELECT privileges: caught exception" table-str))
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/sync/describe_database.clj:111]: Why do you think it is necessary to print exception on info level?

**Review by lbrdnk — COMMENTED** [review]
I like the solution. Let's wait for @luizarakaki to resolve how this should be messaged and backported, then approve and merge.

File: src/metabase/driver/sql_jdbc/sync/describe_database.clj (hunk 5 above)
Comment (bronsa) [reply src/metabase/driver/sql_jdbc/sync/describe_database.clj:111]: In the positive branch of the conditional, we know it is safe to ignore the exception without losing context because it’s a timeout. In the negative branch, we assume the exception is related to missing SELECT privileges, but we can’t be certain. The bug report that prompted this change showed that not logging the exception made it harder to debug; we had to rely on assumptions instead of concrete information.

As for why it's logged at the info level instead of debug or error, I followed the original behavior that was in place before [a refactor](https://github.com/metabase/metabase/commit/93bd0995b90696bf0400f9710749f1f65fb95e3b#diff-1e7eacafc3c5d4b4da2a64cd300aef24460b9ffc170c84a7841dc7b352312111L60-L104). That change, I believe unintentionally, caused the exception to be swallowed and the format string to go unused. This update simply restores the earlier, more transparent behavior.

**Comment by luizarakaki** [comment]
> I like the solution. Let's wait for @luizarakaki to resolve how this should be messaged and backported, then approve and merge.

I think adding a note in the driver changelog should be sufficient. I believe we need a review from the drivers team so we understand the change.

**Comment by bronsa** [comment]
> @bronsa this takes the decision to create a new connection for each query and relies on the connection pool to ensure this is not onerous performance wise. 

Correct

>Did you look into the possibility of having this recover closed connections rather than getting a new one each time?

I did, and the contract of `java.sql.Connection` is such that closed connections are fundamentally unrecoverable, the only way is getting a new connection of the pool.
Moreover, the contract of `SQLRecoverableException` mandates that " At a minimum, the recovery operation must include [..] getting a new connection"

**Comment by dpsutton** [comment]
Sorry @bronsa i meant if we only attempt to get a new connection in the event of losing the existing connection. I did some prototyping and thought i saw a high overhead of getting a new connection each time. But i think i must have been profiling something else because this demonstrates that it's not a big overhead:

```clojure
compare-pool=> (time
                 (let [^com.mchange.v2.c3p0.PooledDataSource pooled (sql-jdbc.conn/db->pooled-connection-spec 10)]
                   (with-open [conn (jdbc/get-connection pooled)]
                     (dotimes [_ 50]
                       (with-open [ps (.createStatement conn)]
                         (let [rs (.executeQuery ps "select 1 as foo")]
                           (while (.next rs)
                             (.getInt rs "foo"))))))))
"Elapsed time: 28.911708 msecs"
nil
compare-pool=> (time
                 (let [^com.mchange.v2.c3p0.PooledDataSource pooled (sql-jdbc.conn/db->pooled-connection-spec 10)]
                   (dotimes [_ 50]
                     (with-open [conn (jdbc/get-connection pooled)]
                       (with-open [ps (.createStatement conn)]
                         (let [rs (.executeQuery ps "select 1 as foo")]
                           (while (.next rs)
                             (.getInt rs "foo"))))))))
"Elapsed time: 18.10175 msecs"
nil
```

one gets a new connection inside the loop, the other uses the same connection across the loop. So there's seemingly no need to try to optimize and only get a new connection when one fails. So i'm happy with the changes.

**Comment by bronsa** [comment]
> Sorry @bronsa i meant if we only attempt to get a new connection in the event of losing the existing connection. I did some prototyping and thought i saw a high overhead of getting a new connection each time. But i think i must have been profiling something else because this demonstrates that it's not a big overhead

Ah yes, fair enough. That was also a worry I initially had, but indeed from profiling it seems that the impact is actually pretty low.

**Comment by bronsa** [comment]
hmmm, i had assumed the snowflake failures were flakey since I had been getting a lot of random failures in the snowflake tests in other unrelated branches, but now I think there may be an issue introduced with this branch. 
I'll try to repro locally

**Review by rileythomp — APPROVED** [review]
