### PR TITLE
Return integers when appropriate for Druid date bucketing :bathtub:

### LINKED ISSUE #2874: Hour-of-day formatting is wrong on Druid
As you can see, the formatting only works for hours till 12pm.

screen shot 2016-07-03 at 22 13 10

If this is a bug report, please fill in the blanks:

*  I am using the chrome browser.
*  My computer's OS is macosX
*  I'm running Metabase 0.18 locally from the JAR .
*  My database is druid/h2.

### PR DESCRIPTION
**Pull request by camsaul**
Instead of strings. Fixes #2874

### CODE REVIEW

**Comment by camsaul** [comment]
@metabase/core-developers does anyone want to review this? Otherwise I will merge

File: src/metabase/driver/druid/query_processor.clj [hunk 1]
```diff
@@ -163,56 +163,72 @@
...
-                                 "  var quarterMonth = month - ((month - 1) % 3);"
-                                 "  return '' + date.getFullYear() + '-' + (quarterMonth < 10 ? '0' : '') + quarterMonth + '-01';"
-                                 "}")
-    :quarter-of-year (extract:js "function (timestamp) {"
-                                 "  var date = new Date(timestamp);"
-                                 "  return Math.floor((date.getMonth() + 3) / 3);"
-                                 "}")
-    :year            (extract:timeFormat "yyyy")))
+(def ^:private ^:const unit->extraction-fn
+  {:default         (extract:timeFormat "yyyy-MM-dd'T'HH:mm:ssZ")
```
Comment (salsakran) [inline src/metabase/driver/druid/query_processor.clj]: Do we have any specific point in a style guide re: which of these forms to prefer?

I think there's a reasonable case to be made with either (conciseness + lack of side effects for destructuring vs clarity for the function call version)

File: src/metabase/driver/druid/query_processor.clj [hunk 2]
```diff
@@ -530,6 +548,20 @@
...
+(defn- columns->getter-fns
+  "Given a sequence of COLUMNS keywords, return a sequence of appropriate getter functions to get values from a single result row. Normally,
+   these are just the keyword column names themselves, but for `:timestamp___int`, we'll also parse the result as an integer (for further
+   explanation, see the docstring for `units-that-need-post-processing-int-parsing`)."
+  [columns]
+  (vec (for [k columns]
+         (if (not= k :timestamp___int)
+           k
+           (comp (fn [^String s]
+                   (when (seq s)
```
Comment (salsakran) [inline src/metabase/driver/druid/query_processor.clj]: Is this checking for a null string?

**Comment by salsakran** [comment]
I'm a little weirded out by modifying the names to __int and back. 

Is there a reason you did that vs using the column unit type in `columns->getter-fns`?

File: src/metabase/driver/druid/query_processor.clj (hunk 2 above)
Comment (camsaul) [inline src/metabase/driver/druid/query_processor.clj]: null or empty

File: src/metabase/driver/druid/query_processor.clj (hunk 1 above)
Comment (camsaul) [inline src/metabase/driver/druid/query_processor.clj]: If it can be a constant map it should be; that way we don't waste time reconstructing values every time.

**Comment by camsaul** [comment]
`:timestamp` is actually a column that gets added to the results so it's not present in the input. The logic would be hairy if we tried to determine what column produced timestamp originally so we could look at its unit info. Doing things this way was simpler

File: src/metabase/driver/druid/query_processor.clj (hunk 2 above)
Comment (camsaul) [inline src/metabase/driver/druid/query_processor.clj]: This is what's called "nil-punning" in Lisp languages. `seq` will return a (lazy) sequence of objects in a collection if the collection is non-empty, otherwise nil. For the purposes of `seq` a string is considered to be a sequence of chars so

```clojure
(seq nil)    -> nil
(seq "")     -> nil
(seq "ab") -> [\a \b]
```

**Comment by salsakran** [comment]
Gotcha. That makes sense.  👍

File: src/metabase/driver/druid/query_processor.clj (hunk 1 above)
Comment (camsaul) [inline src/metabase/driver/druid/query_processor.clj]: In Clojure maps can act as functions, e.g.

```clojure
(def ^:private ^:const my-map {:a 1, :b 2})

(my-map :a) -> 1
```

So the difference with making something a constant map vs using a function with `case` would be that the entire map will be built a single time during compile time and using it is a simple key-value lookup. For a function call there's the key lookup in the `:case` statement and then the resulting value is constructed at runtime

**Comment by camsaul** [comment]
@salsakran is this g2g?

**Comment by salsakran** [comment]
yup
