### PR TITLE
Prevent an exception in api.table/batch-fetch-card-query-metadatas when cards is empty

### LINKED ISSUE #48461: Deleting a model will corrupt all dashboards where cards based on the model are
### Describe the bug

if you delete a model from where cards are based upon, we'll send a "SELECT * FROM "metabase_database" WHERE "id" IN ()" to the app db, that makes the query metadata endpoint to fail

### To Reproduce

1) create a model
2) create a question based on this model
3) create a dashboard and add the question
4) delete the model

see the dashboard corrupting

### Expected behavior

_No response_

<details>
<summary> logs:</summary>
### Logs

```
{
    "via": [
        {
            "type": "clojure.lang.ExceptionInfo",
            "message": "ERROR: syntax error at or near \")\"\n  Position: 50",
            "data": {
                "toucan2/context-trace": [
                    [
                        "execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection",
                        {
                            "toucan2.jdbc.query/sql-args": [
                                "SELECT * FROM \"metabase_database\" WHERE \"id\" IN ()"
                            ]
                        }
                    ],
                    [
                        "resolve connection",
                        {
                            "toucan2.connection/connectable": "class metabase.db.connection.ApplicationDB"
                        }
                    ],
                    [
                        "resolve connection",
                        {
                            "toucan2.connection/connectable": "default"
                        }
                    ],
                    [
                        "resolve connection",
                        {
                            "toucan2.connection/connectable": null
                        }
                    ],
                    {
                        "toucan2.pipeline/rf": "clojure.core$map$fn__5931$fn__5932@18572694"
                    },
                    [
                        "with compiled query",
                        {
                            "toucan2.pipeline/compiled-query": [
                                "SELECT * FROM \"metabase_database\" WHERE \"id\" IN ()"
                            ]
                        }
                    ],
                    [
                        "with built query",
                        {
                            "toucan2.pipeline/built-query": {
                                "select": [
                                    "*"
                                ],
                                "from": [
                                    [
                                        "metabase_database"
                                    ]
                                ],
                                "where": [
                                    "in",
                                    "id",
                                    []
                                ]
                            }
                        }
                    ],
                    [
                        "with resolved query",
                        {
                            "toucan2.pipeline/resolved-query": {}
                        }
                    ],
                    [
                        "with parsed args",
                        {
                            "toucan2.pipeline/query-type": "toucan.query-type/select.instances",
                            "toucan2.pipeline/parsed-args": {
                                "kv-args": {
                                    "id": [
                                        "in",
                                        []
                                    ]
                                },
                                "queryable": {}
                            }
                        }
                    ],
                    [
                        "with model",
                        {
                            "toucan2.pipeline/model": "model/Database"
                        }
                    ],
                    [
                        "with unparsed args",
                        {
                            "toucan2.pipeline/query-type": "toucan.query-type/select.instances",
                            "toucan2.pipeline/unparsed-args": [
                                "model/Database",
                                "id",
                                [
                                    "in",
                                    []
                                ]
                            ]
                        }
                    ]
                ]
            },
            "at": [
                "org.postgresql.core.v3.QueryExecutorImpl",
                "receiveErrorResponse",
                "QueryExecutorImpl.java",
                2725
            ]
        },
        {
            "type": "org.postgresql.util.PSQLException",
            "message": "ERROR: syntax error at or near \")\"\n  Position: 50",
            "at": [
                "org.postgresql.core.v3.QueryExecutorImpl",
                "receiveErrorResponse",
                "QueryExecutorImpl.java",
                2725
            ]
        }
    ],
    "trace": [
        [
            "org.postgresql.core.v3.QueryExecutorImpl",
            "receiveErrorResponse",
            "QueryExecutorImpl.java",
            2725
        ],
        [
            "org.postgresql.core.v3.QueryExecutorImpl",
            "processResults",
            "QueryExecutorImpl.java",
            2412
        ],
        [
            "org.postgresql.core.v3.QueryExecutorImpl",
            "execute",
            "QueryExecutorImpl.java",
            371
        ],
        [
            "org.postgresql.jdbc.PgStatement",
            "executeInternal",
            "PgStatement.java",
            502
        ],
        [
            "org.postgresql.jdbc.PgStatement",
            "execute",
            "PgStatement.java",
            419
        ],
        [
            "org.postgresql.jdbc.PgPreparedStatement",
            "executeWithFlags",
            "PgPreparedStatement.java",
            194
        ],
        [
            "org.postgresql.jdbc.PgPreparedStatement",
            "execute",
            "PgPreparedStatement.java",
            180
        ],
        [
            "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement",
            "execute",
            "NewProxyPreparedStatement.java",
            67
        ],
        [
            "toucan2.jdbc.query$reduce_jdbc_query",
            "invokeStatic",
            "query.clj",
            40
        ],
        [
            "toucan2.jdbc.query$reduce_jdbc_query",
            "invoke",
            "query.clj",
            22
        ],
        [
            "toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default",
            "invokeStatic",
            "pipeline.clj",
            19
        ],
        [
            "toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default",
            "invoke",
            "pipeline.clj",
            9
        ],
        [
            "methodical.impl.combo.common$partial_STAR_$fn__18186",
            "invoke",
            "common.clj",
            15
        ],
        [
            "methodical.impl.combo.threaded$combine_methods_thread_last$fn__18496$combined_method_thread_last__18497",
            "invoke",
            "threaded.clj",
            64
        ],
        [
            "methodical.util.FnWithMeta",
            "invoke",
            "util.clj",
            46
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invokeStatic",
            "standard.clj",
            65
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invoke",
            "standard.clj",
            47
        ],
        [
            "methodical.impl.standard.StandardMultiFn",
            "invoke",
            "standard.clj",
            216
        ],
        [
            "toucan2.pipeline$transduce_execute$with_connection_STAR___21604",
            "invoke",
            "pipeline.clj",
            78
        ],
        [
            "toucan2.connection$bind_current_connectable_fn$fn__21281",
            "invoke",
            "connection.clj",
            104
        ],
        [
            "toucan2.connection$bind_current_connectable_fn$fn__21281",
            "invoke",
            "connection.clj",
            104
        ],
        [
            "toucan2.connection$bind_current_connectable_fn$fn__21281",
            "invoke",
            "connection.clj",
            104
        ],
        [
            "toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource",
            "invokeStatic",
            "connection.clj",
            18
        ],
        [
            "toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource",
            "invoke",
            "connection.clj",
            15
        ],
        [
            "methodical.impl.combo.common$partial_STAR_$fn__18186",
            "invoke",
            "common.clj",
            12
        ],
        [
            "methodical.util.FnWithMeta",
            "invoke",
            "util.clj",
            46
        ],
        [
            "toucan2.connection$do_with_connection_around_method_toucan2_connection_default",
            "invokeStatic",
            "connection.clj",
            118
        ],
        [
            "toucan2.connection$do_with_connection_around_method_toucan2_connection_default",
            "invoke",
            "connection.clj",
            106
        ],
        [
            "methodical.impl.combo.common$partial_STAR_$fn__18186",
            "invoke",
            "common.clj",
            12
        ],
        [
            "methodical.util.FnWithMeta",
            "invoke",
            "util.clj",
            46
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invokeStatic",
            "standard.clj",
            55
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invoke",
            "standard.clj",
            47
        ],
        [
            "methodical.impl.standard.StandardMultiFn",
            "invoke",
            "standard.clj",
            210
        ],
        [
            "metabase.db.connection$do_with_connection_primary_method_default",
            "invokeStatic",
            "connection.clj",
            132
        ],
        [
            "metabase.db.connection$do_with_connection_primary_method_default",
            "invoke",
            "connection.clj",
            130
        ],
        [
            "methodical.impl.combo.common$partial_STAR_$fn__18186",
            "invoke",
            "common.clj",
            12
        ],
        [
            "methodical.util.FnWithMeta",
            "invoke",
            "util.clj",
            46
        ],
        [
            "toucan2.connection$do_with_connection_around_method_toucan2_connection_default",
            "invokeStatic",
            "connection.clj",
            118
        ],
        [
            "toucan2.connection$do_with_connection_around_method_toucan2_connection_default",
            "invoke",
            "connection.clj",
            106
        ],
        [
            "methodical.impl.combo.common$partial_STAR_$fn__18186",
            "invoke",
            "common.clj",
            12
        ],
        [
            "methodical.util.FnWithMeta",
            "invoke",
            "util.clj",
            46
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invokeStatic",
            "standard.clj",
            55
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invoke",
            "standard.clj",
            47
        ],
        [
            "methodical.impl.standard.StandardMultiFn",
            "invoke",
            "standard.clj",
            210
        ],
        [
            "toucan2.connection$do_with_connection_primary_method_",
            "invokeStatic",
            "connection.clj",
            204
        ],
        [
            "toucan2.connection$do_with_connection_primary_method_",
            "invoke",
            "connection.clj",
            194
        ],
        [
            "methodical.impl.combo.common$partial_STAR_$fn__18186",
            "invoke",
            "common.clj",
            12
        ],
        [
            "methodical.util.FnWithMeta",
            "invoke",
            "util.clj",
            46
        ],
        [
            "toucan2.connection$do_with_connection_around_method_toucan2_connection_default",
            "invokeStatic",
            "connection.clj",
            118
        ],
        [
            "toucan2.connection$do_with_connection_around_method_toucan2_connection_default",
            "invoke",
            "connection.clj",
            106
        ],
        [
            "methodical.impl.combo.common$partial_STAR_$fn__18186",
            "invoke",
            "common.clj",
            12
        ],
        [
            "methodical.util.FnWithMeta",
            "invoke",
            "util.clj",
            46
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invokeStatic",
            "standard.clj",
            55
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invoke",
            "standard.clj",
            47
        ],
        [
            "methodical.impl.standard.StandardMultiFn",
            "invoke",
            "standard.clj",
            210
        ],
        [
            "toucan2.pipeline$transduce_execute",
            "invokeStatic",
            "pipeline.clj",
            77
        ],
        [
            "toucan2.pipeline$transduce_execute",
            "invoke",
            "pipeline.clj",
            64
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            399
        ],
        [
            "toucan2.pipeline$transduce_compiled_query",
            "invokeStatic",
            "pipeline.clj",
            244
        ],
        [
            "toucan2.pipeline$transduce_compiled_query",
            "invoke",
            "pipeline.clj",
            240
        ],
        [
            "toucan2.pipeline$transduce_built_query",
            "invokeStatic",
            "pipeline.clj",
            252
        ],
        [
            "toucan2.pipeline$transduce_built_query",
            "invoke",
            "pipeline.clj",
            246
        ],
        [
            "toucan2.pipeline$transduce_query_primary_method_default",
            "invokeStatic",
            "pipeline.clj",
            272
        ],
        [
            "toucan2.pipeline$transduce_query_primary_method_default",
            "invoke",
            "pipeline.clj",
            269
        ],
        [
            "methodical.impl.combo.common$partial_STAR_$fn__18186",
            "invoke",
            "common.clj",
            15
        ],
        [
            "methodical.impl.combo.threaded$combine_methods_thread_last$fn__18496$combined_method_thread_last__18497",
            "invoke",
            "threaded.clj",
            64
        ],
        [
            "methodical.util.FnWithMeta",
            "invoke",
            "util.clj",
            46
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invokeStatic",
            "standard.clj",
            65
        ],
        [
            "methodical.impl.standard$invoke_multifn",
            "invoke",
            "standard.clj",
            47
        ],
        [
            "methodical.impl.standard.StandardMultiFn",
            "invoke",
            "standard.clj",
            216
        ],
        [
            "toucan2.pipeline$transduce_query_STAR_",
            "invokeStatic",
            "pipeline.clj",
            278
        ],
        [
            "toucan2.pipeline$transduce_query_STAR_",
            "invoke",
            "pipeline.clj",
            274
        ],
        [
            "toucan2.pipeline$transduce_with_model",
            "invokeStatic",
            "pipeline.clj",
            293
        ],
        [
            "toucan2.pipeline$transduce_with_model",
            "invoke",
            "pipeline.clj",
            280
        ],
        [
            "toucan2.pipeline$transduce_parsed",
            "invokeStatic",
            "pipeline.clj",
            309
        ],
        [
            "toucan2.pipeline$transduce_parsed",
            "invoke",
            "pipeline.clj",
            295
        ],
        [
            "toucan2.pipeline$transduce_unparsed",
            "invokeStatic",
            "pipeline.clj",
            317
        ],
        [
            "toucan2.pipeline$transduce_unparsed",
            "invoke",
            "pipeline.clj",
            311
        ],
        [
            "toucan2.select$select_fn__GT_fn",
            "invokeStatic",
            "select.clj",
            195
        ],
        [
            "toucan2.select$select_fn__GT_fn",
            "doInvoke",
            "select.clj",
            181
        ],
        [
            "clojure.lang.RestFn",
            "applyTo",
            "RestFn.java",
            142
        ],
        [
            "clojure.core$apply",
            "invokeStatic",
            "core.clj",
            673
        ],
        [
            "clojure.core$apply",
            "invoke",
            "core.clj",
            662
        ],
        [
            "toucan2.select$select_pk__GT_fn",
            "invokeStatic",
            "select.clj",
            221
        ],
        [
            "toucan2.select$select_pk__GT_fn",
            "doInvoke",
            "select.clj",
            210
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            464
        ],
        [
            "metabase.api.table$batch_fetch_card_query_metadatas",
            "invokeStatic",
            "table.clj",
            517
        ],
        [
            "metabase.api.table$batch_fetch_card_query_metadatas",
            "invoke",
            "table.clj",
            497
        ],
        [
            "metabase.api.query_metadata$batch_fetch_query_metadata_STAR_",
            "invokeStatic",
            "query_metadata.clj",
            49
        ],
        [
            "metabase.api.query_metadata$batch_fetch_query_metadata_STAR_",
            "invoke",
            "query_metadata.clj",
            41
        ],
        [
            "metabase.api.query_metadata$batch_fetch_query_metadata",
            "invokeStatic",
            "query_metadata.clj",
            71
        ],
        [
            "metabase.api.query_metadata$batch_fetch_query_metadata",
            "invoke",
            "query_metadata.clj",
            68
        ],
        [
            "metabase.api.query_metadata$batch_fetch_card_metadata",
            "invokeStatic",
            "query_metadata.clj",
            83
        ],
        [
            "metabase.api.query_metadata$batch_fetch_card_metadata",
            "invoke",
            "query_metadata.clj",
            73
        ],
        [
            "metabase.api.query_metadata$batch_fetch_dashboard_metadata",
            "invokeStatic",
            "query_metadata.clj",
            142
        ],
        [
            "metabase.api.query_metadata$batch_fetch_dashboard_metadata",
            "invoke",
            "query_metadata.clj",
            131
        ],
        [
            "metabase.api.dashboard$fn__96434$fn__96437",
            "invoke",
            "dashboard.clj",
            915
        ],
        [
            "metabase.api.dashboard$do_with_dashboard_load_id",
            "invokeStatic",
            "dashboard.clj",
            309
        ],
        [
            "metabase.api.dashboard$do_with_dashboard_load_id",
            "invoke",
            "dashboard.clj",
            304
        ],
        [
            "metabase.api.dashboard$fn__96434",
            "invokeStatic",
            "dashboard.clj",
            912
        ],
        [
            "metabase.api.dashboard$fn__96434",
            "invoke",
            "dashboard.clj",
            908
        ],
        [
            "compojure.core$wrap_response$fn__52779",
            "invoke",
            "core.clj",
            160
        ],
        [
            "compojure.core$wrap_route_middleware$fn__52763",
            "invoke",
            "core.clj",
            132
        ],
        [
            "compojure.core$wrap_route_info$fn__52768",
            "invoke",
            "core.clj",
            139
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            151
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            393
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            152
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            393
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            153
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            393
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            153
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            393
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            152
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            393
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            153
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            393
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            153
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            393
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "metabase.server.middleware.auth$enforce_authentication$fn__98192",
            "invoke",
            "auth.clj",
            18
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$make_context$handler__52819",
            "invoke",
            "core.clj",
            290
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            300
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            152
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            393
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "metabase.api.routes$fn__103866$fn__103867",
            "invoke",
            "routes.clj",
            70
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.core$apply",
            "invokeStatic",
            "core.clj",
            667
        ],
        [
            "clojure.core$apply",
            "invoke",
            "core.clj",
            662
        ],
        [
            "metabase.server.routes$fn__104146$fn__104147",
            "doInvoke",
            "routes.clj",
            73
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$make_context$handler__52819",
            "invoke",
            "core.clj",
            290
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            300
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            153
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__52772",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$make_context$handler__52819",
            "invoke",
            "core.clj",
            290
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            300
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791$f__52792$respond_SINGLEQUOTE___52793",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__52823",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$routes$fn__52791$f__52792",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__52791",
            "invoke",
            "core.clj",
            200
        ],
        [
            "metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__100226",
            "invoke",
            "exceptions.clj",
            107
        ],
        [
            "metabase.server.middleware.exceptions$catch_api_exceptions$fn__100223",
            "invoke",
            "exceptions.clj",
            96
        ],
        [
            "metabase.server.middleware.log$log_api_call$fn__106503$fn__106504$fn__106505",
            "invoke",
            "log.clj",
            233
        ],
        [
            "metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info",
            "invokeStatic",
            "diagnostic.clj",
            18
        ],
        [
            "metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info",
            "invoke",
            "diagnostic.clj",
            12
        ],
        [
            "metabase.server.middleware.log$log_api_call$fn__106503$fn__106504",
            "invoke",
            "log.clj",
            224
        ],
        [
            "toucan2.execute$do_with_call_counts",
            "invokeStatic",
            "execute.clj",
            112
        ],
        [
            "toucan2.execute$do_with_call_counts",
            "invoke",
            "execute.clj",
            103
        ],
        [
            "metabase.server.middleware.log$log_api_call$fn__106503",
            "invoke",
            "log.clj",
            223
        ],
        [
            "metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__112705",
            "invoke",
            "browser_cookie.clj",
            40
        ],
        [
            "metabase.server.middleware.security$add_security_headers$fn__100182",
            "invoke",
            "security.clj",
            246
        ],
        [
            "ring.middleware.json$wrap_json_body$fn__112964",
            "invoke",
            "json.clj",
            64
        ],
        [
            "metabase.server.middleware.offset_paging$handle_paging$fn__88545",
            "invoke",
            "offset_paging.clj",
            43
        ],
        [
            "metabase.server.middleware.json$wrap_streamed_json_response$fn__54407",
            "invoke",
            "json.clj",
            83
        ],
        [
            "ring.middleware.keyword_params$wrap_keyword_params$fn__113053",
            "invoke",
            "keyword_params.clj",
            55
        ],
        [
            "ring.middleware.params$wrap_params$fn__113072",
            "invoke",
            "params.clj",
            77
        ],
        [
            "metabase.server.middleware.misc$maybe_set_site_url$fn__64266",
            "invoke",
            "misc.clj",
            59
        ],
        [
            "metabase.server.middleware.session$reset_session_timeout$fn__65819",
            "invoke",
            "session.clj",
            549
        ],
        [
            "metabase.server.middleware.session$bind_current_user$fn__65785$fn__65786",
            "invoke",
            "session.clj",
            443
        ],
        [
            "metabase.server.middleware.session$do_with_current_user",
            "invokeStatic",
            "session.clj",
            422
        ],
        [
            "metabase.server.middleware.session$do_with_current_user",
            "invoke",
            "session.clj",
            405
        ],
        [
            "metabase.server.middleware.session$bind_current_user$fn__65785",
            "invoke",
            "session.clj",
            442
        ],
        [
            "metabase.server.middleware.session$wrap_current_user_info$fn__65766",
            "invoke",
            "session.clj",
            381
        ],
        [
            "metabase.server.middleware.session$wrap_session_id$fn__65738",
            "invoke",
            "session.clj",
            259
        ],
        [
            "metabase.server.middleware.auth$wrap_static_api_key$fn__98200",
            "invoke",
            "auth.clj",
            32
        ],
        [
            "ring.middleware.cookies$wrap_cookies$fn__112892",
            "invoke",
            "cookies.clj",
            200
        ],
        [
            "metabase.server.middleware.misc$add_content_type$fn__64248",
            "invoke",
            "misc.clj",
            28
        ],
        [
            "metabase.server.middleware.misc$disable_streaming_buffering$fn__64274",
            "invoke",
            "misc.clj",
            75
        ],
        [
            "ring.middleware.gzip$wrap_gzip$fn__112934",
            "invoke",
            "gzip.clj",
            86
        ],
        [
            "metabase.server.middleware.misc$bind_request$fn__64277",
            "invoke",
            "misc.clj",
            91
        ],
        [
            "metabase.server.middleware.ssl$redirect_to_https_middleware$fn__112721",
            "invoke",
            "ssl.clj",
            51
        ],
        [
            "metabase.server$async_proxy_handler$fn__72022",
            "invoke",
            "server.clj",
            77
        ],
        [
            "metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a",
            "handle",
            null,
            -1
        ],
        [
            "org.eclipse.jetty.server.handler.StatisticsHandler",
            "handle",
            "StatisticsHandler.java",
            173
        ],
        [
            "org.eclipse.jetty.server.handler.HandlerWrapper",
            "handle",
            "HandlerWrapper.java",
            122
        ],
        [
            "org.eclipse.jetty.server.Server",
            "handle",
            "Server.java",
            563
        ],
        [
            "org.eclipse.jetty.server.HttpChannel$RequestDispatchable",
            "dispatch",
            "HttpChannel.java",
            1598
        ],
        [
            "org.eclipse.jetty.server.HttpChannel",
            "dispatch",
            "HttpChannel.java",
            753
        ],
        [
            "org.eclipse.jetty.server.HttpChannel",
            "handle",
            "HttpChannel.java",
            501
        ],
        [
            "org.eclipse.jetty.server.HttpConnection",
            "onFillable",
            "HttpConnection.java",
            287
        ],
        [
            "org.eclipse.jetty.io.AbstractConnection$ReadCallback",
            "succeeded",
            "AbstractConnection.java",
            314
        ],
        [
            "org.eclipse.jetty.io.FillInterest",
            "fillable",
            "FillInterest.java",
            100
        ],
        [
            "org.eclipse.jetty.io.SelectableChannelEndPoint$1",
            "run",
            "SelectableChannelEndPoint.java",
            53
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "runTask",
            "AdaptiveExecutionStrategy.java",
            421
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "consumeTask",
            "AdaptiveExecutionStrategy.java",
            390
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "tryProduce",
            "AdaptiveExecutionStrategy.java",
            277
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "run",
            "AdaptiveExecutionStrategy.java",
            199
        ],
        [
            "org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread",
            "run",
            "ReservedThreadExecutor.java",
            411
        ],
        [
            "org.eclipse.jetty.util.thread.QueuedThreadPool",
            "runJob",
            "QueuedThreadPool.java",
            969
        ],
        [
            "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
            "doRunJob",
            "QueuedThreadPool.java",
            1194
        ],
        [
            "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
            "run",
            "QueuedThreadPool.java",
            1149
        ],
        [
            "java.lang.Thread",
            "run",
            "Thread.java",
            829
        ]
    ],
    "cause": "ERROR: syntax error at or near \")\"\n  Position: 50",
    "message": "ERROR: syntax error at or near \")\"\n  Position: 50"
}
```
</details>
### Information about your Metabase installation

v50

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by appleby**
### Description

Closes #48461

Ensure we don't throw an exception by attempting to fetch an empty set of `Databases` associated with potentially-deleted card ids in api.table/batch-fetch-card-query-metadatas.

In particular, this ensures we don't generate an exception if the user does the following

1. Create a card "Source Card"
2. Create another card "Derived Card" with a :source-table of "Source Card"
3. Add Derived Card to a dashboard
4. Permanently delete (not just archive) the Source Card

### How to verify

Note that this actually won't reproduce if you do everything on v51+ due to changes in #46356 where we added a new `report_card.source_card_id` column with a corresponding "ON DELETE CASCADE" constraint (`fk_report_card_source_card_id_ref_report_card_id`), so that on v51+ when you delete the source card, the derived card is also deleted. No dangling card is left, which also fixes the bug as described in #48461.

In order to repro, you need start from v50 or earlier and do the steps described above or in the linked issue. If you then upgrade to v51, the card remains dangling and the dashboard is broken.

In addition, some of the new tests added in this PR do still trigger the bug even with cascading deletes of the source card, in particular the tests for the `POST "/dataset/query_metadata"` and `GET "/table/card__:id/query_metadata"` endpoints can still trigger the issue without this fix.

### Demo

Prior to this change, you might (depending on app DB) get an error like this one when attempting to view a dashboard that contained only "dangling" cards created via the above process.

Screenshot 2024-11-15 at 3 07 47 PM

Whether you see an error depends on whether your DBMS is ok with a query like `SELECT * FROM "metabase_database" WHERE "id" IN ()`. E.g. Postgres considers it an error, but H2 is fine with it.

After this change, you'll instead see

Screenshot 2024-11-15 at 3 23 26 PM

We still can't display the card, but the rest of the dashboard displays and you can remove the offending card(s).

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/api/automagic_dashboards_test.clj [hunk 1]
```diff
@@ -572,7 +572,4 @@
        {:tables (sort-by :id [{:id (mt/id :venues)}
                               {:id (mt/id :categories)}])}
        (-> (mt/user-http-request :crowberto :get 200 (str "automagic-dashboards/table/" (mt/id :venues) "/query_metadata"))
-            ;; The output is so large, these help debugging
-           #_#_#_(update :fields #(map (fn [x] (select-keys x [:id])) %))
-               (update :databases #(map (fn [x] (select-keys x [:id :engine])) %))
-             (update :tables #(map (fn [x] (select-keys x [:id :name])) %))))))
+           #_(api.test-util/select-query-metadata-keys-for-debugging)))))
```
Comment (appleby) [inline test/metabase/api/automagic_dashboards_test.clj:575]: Unrelated but this snippet of debug code was repeated in a handful of places, so I moved it into helper function in a new `metabase.api.test-util` namespace

**Review by metamben — APPROVED** [review]
LGTM
