### PR TITLE
GDGT-2143 Use subscription creator's perms for attachment check

### LINKED ISSUE #71696: We stopped sending the attachments on subscriptions
### Describe the bug

We stopped sending the attachments on subscriptions

### To Reproduce

Don't know

### Expected behavior

We should send the attachments if the subscription is configured to send them

### Logs

NA

### Information about your Metabase installation

```JSON
59.x
```

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by qnkhuat**
closes #71696
Fixes [GDGT-2143](https://linear.app/metabase/issue/GDGT-2143) / metabase/metabase#71696.

Subscription emails silently drop CSV/XLSX attachments when the underlying card's author lacks download permissions, even if the subscription creator has full perms.

**Introduced in:** #66827 (v59), backported to v58.1 in #67175. The PR added a send-time download-perms check to `result-attachment` but used `(:creator_id card)` — the card author — instead of the subscription creator.

**Fix:** thread the subscription creator's user-id from `notification-payload` through to `result-attachment` and check that user's perms instead.

### CODE REVIEW

File: src/metabase/channel/email/result_attachment.clj [hunk 1]
```diff
@@ -86,14 +86,16 @@
...
     result :result
-    :as part}]
+    :as part}
+   creator-id]
   (when (and (or (:include_csv card) (:include_xls card))
              (pos-int? (:row_count result))
-             (not= (perms/download-perms-level (:dataset_query card) (:creator_id card))  :no))
+             (not= (perms/download-perms-level (:dataset_query card) creator-id) :no))
     (let [maybe-realize-data-rows (requiring-resolve 'metabase.channel.shared/maybe-realize-data-rows)
           result            (:result (maybe-realize-data-rows part))
```
Comment (qnkhuat) [inline src/metabase/channel/email/result_attachment.clj:98]: @nvoxland could you take a look if this was intentional at all?

**Review by bronsa — APPROVED** [review]
this fix makes sense to me, but wait for @nvoxland's feedback re: the intention behind the original change

File: src/metabase/channel/email/result_attachment.clj (hunk 1 above)
Comment (nvoxland) [reply src/metabase/channel/email/result_attachment.clj:98]: No, I think your fix is good. Thanks!

**Review by nvoxland — APPROVED** [review]
