### PR TITLE
Fields values work for secondary series in a dashcard

### LINKED ISSUE #58328: No field values for parameters mapped to multi-series dashcards
### Describe the bug

For a multi-series dashcard, if a parameter is mapped to a non-primary card, no field values will be shown for nested queries.

Checked master (v55), v54, v53 - all were broken.

### To Reproduce

1. New -> Model -> Products -> Save as `M1`
2. New -> Question -> `M1` -> Count, Group by Category -> Save as `Q1` -> Convert to SQL -> Viz as Bar -> Overwrite Q1
3. New -> Question -> `M1` -> Count, Group by Category -> Viz as Bar -> Save as `Q2`
4. New -> Dashboard -> Add `Q1` -> Visualizer -> Add more data -> `Q2` ->  Save
5. Add param `P1` -> Map to `Q1.CATEGORY`
6. Add param `P2`-> Map to `Q2.Category` -> Save dashboard
7. The parameter widget for `P2` is a plain text box without field values

### Expected behavior

There should be field values, like if it was the main card.

### Logs

Nothing

### Information about your Metabase installation

```JSON
master (pre v55)
```

### Severity

P1-P2

### Additional context

`params.clj` doesn't take `:series` into account. https://github.com/metabase/metabase/blob/44aba6b92e4e21e47cba6dcb31d577a420968def/src/metabase/parameters/params.clj#L262

It needs to check the `:card_id` in the parameter mapping and find the card in the dashcard - either in `:card` or in `:series`.

### PR DESCRIPTION
**Pull request by wzimrin**
Closes https://github.com/metabase/metabase/issues/58328

### Description

Field values check both :card and :series for the relevant card

### How to verify

See case

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/parameters/params.clj [hunk 1]
```diff
@@ -260,7 +261,13 @@
...
    (if-not param-target-field
      ctx
-     (let [card (get-in param-dashcard-info [:dashcard :card])
+     (let [card-id (:card_id param-mapping)
+           card (if card-id
+                  (some #(and (= (:id %) card-id)
+                              %)
+                        (cons (get-in param-dashcard-info [:dashcard :card])
+                              (get-in param-dashcard-info [:dashcard :series])))
+                  (get-in param-dashcard-info [:dashcard :card]))
```
Comment (bshepherdson) [inline src/metabase/parameters/params.clj]:
```suggestion
           card (if card-id
                  (m/find-first #(= (:id %) card-id)
                                (cons (get-in param-dashcard-info [:dashcard :card])
                                      (get-in param-dashcard-info [:dashcard :series])))
                  (get-in param-dashcard-info [:dashcard :card]))
```

**Review by bshepherdson — APPROVED** [review]
