### PR TITLE
Pass validation errors to create dashboard modal

### LINKED ISSUE #63176: Creating a dashboard with a null name will give you a success message (and a 400 BE error)
### Describe the bug

What the title say

### To Reproduce

Create a dashboard with a space
click save
see that the message is a success although the backend returned a 400

### Expected behavior

We should return an error in the FE

### Logs

Image

### Information about your Metabase installation

```JSON
v55
```

### Severity

P3

### Additional context

NA

### PR DESCRIPTION
**Pull request by romeovs**
Closes #63176

### To verify

1. New -> Dashboard
2. Type a space in the name field and save
3. You should see an error

### CODE REVIEW

File: frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx [hunk 1]
```diff
@@ -85,7 +85,10 @@ export function CreateDashboardForm({
 
   const handleCreate = useCallback(
     async (values: CreateDashboardProperties) => {
-      const { data: dashboard } = await handleCreateDashboard(values);
+      const { data: dashboard, error } = await handleCreateDashboard(values);
```
Comment (ranquild) [inline frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx]: @romeovs you could use `await handleCreateDashboard(values).unwrap()`. Search for `.unwrap` in the repo, it's a standard way of making RTK query hook functions throw

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx (hunk 1 above)
Comment (romeovs) [reply frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx]: TIL!
