### PR TITLE
Fix question and dashboard cache settings

### LINKED ISSUE #27806: Single question, dashboard, and database cache option is missing
**Describe the bug**
The `Cache configuration` section in the `More info` tab in questions and dashboards is missing in `master`.
The section is in 45.2.

**To Reproduce**
For questions/dashboards
0. Pro/EE instance with question cache enabled
1. Go to any question or dashboard in Stats like https://stats.metabase.com/question/3888-team-members
2. Click on `i`
3. You should see the `Cache configuration` section, but nothing is there

For database
0. Pro/EE instance with question cache enabled
1. Go to any database like the Sample Dataset
2. Click on `Show advanced options` 
3. You should see the `Default result cache duration` section, but nothing is there

**Expected behavior**
### Dashboard and question
image

### Database
image

**Severity**
P1 makes it impossible to use a Pro/EE feature

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/27806

Fixes caching settings disappear in master after recent settings changes. There was an issue with how the corresponding e2e tests were written and that's why we didn't catch the issue automatically.

How to test:
- Run Metabase EE
- Admin -> Settings -> Caching -> Enable
- Go to a saved question and click the info button
- There should be a section for caching settings
- Same for dashboards

Screenshot 2023-01-24 at 13 29 16

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/27831)

### CODE REVIEW

File: src/metabase/public_settings.clj [hunk 1]
```diff
@@ -224,8 +224,7 @@
 (defsetting enable-query-caching
   (deferred-tru "Enabling caching will save the results of queries that take a long time to run.")
   :type    :boolean
-  :default false
-  :visibility :settings-manager)
+  :default false)
```
Comment (ranquild) [inline src/metabase/public_settings.clj:227]: @noahmoss I'm reverting your recent change to the setting because it caused issues.

**Review by kulyk — APPROVED** [review]

File: src/metabase/public_settings.clj (hunk 1 above)
Comment (noahmoss) [inline src/metabase/public_settings.clj:227]: Oh, thanks for catching that. I didn't realize this setting was read outside of the admin panel (and obviously Cypress didn't catch it).

However I think this should actually be `:visibility :authenticated`. Otherwise only admins will see this in the info sidebar, since `:admin` is the default visibility level.

```suggestion
  :default    :false
  :visibility :authenticated)
```

Comment (ranquild) [reply src/metabase/public_settings.clj]: great catch, thanks!
