### PR TITLE
Restore reproduction e2e test

### LINKED ISSUE #13306: Custom Expression formula editor is aggressively changing/removing parenthesis
**Describe the bug**
When inputting a Custom Expression formula with multiple parenthesis, then some of those parenthesis are incorrectly changed/removed, when leaving the input field, which makes the formula incorrect.
Workaround is to sneak in an addition (or similar) to preserve the parenthesis.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Summarize
   1. Custom Expression formula `Sum([Total]) / (Sum([Product → Price]) * Average([Quantity]))` as "Incorrect"
      Notice when leaving the field (blur), then the formula gets stripped of the Sum*Average parenthesis.
   2. Custom Expression formula `Sum([Total]) / (0 + Sum([Product → Price]) * Average([Quantity]))` as "Correct - hack"
image
image

**Expected behavior**
Don't strip/auto-correct manually input parenthesis.

**Information about your Metabase Installation:**
Metabase 0.36.6

### PR DESCRIPTION
**Pull request by deniskaber**
Closes https://github.com/metabase/metabase/issues/13306

### Description

When inputting a Custom Expression formula with multiple parenthesis, then some of those parenthesis are incorrectly changed/removed, when leaving the input field, which makes the formula incorrect.

### How to verify

1. Custom question > Sample Dataset > Orders
2. Summarize
   1. Custom Expression formula `Sum([Total]) / (Sum([Product → Price]) * Average([Quantity]))` as "Incorrect"
      Notice when leaving the field (blur), then the formula gets stripped of the Sum*Average parenthesis.
   2. Custom Expression formula `Sum([Total]) / (0 + Sum([Product → Price]) * Average([Quantity]))` as "Correct - hack"
image
image

**Expected behavior**
Don't strip/auto-correct manually input parenthesis.

### Demo

https://user-images.githubusercontent.com/7983744/227042672-ff73cd76-90aa-4adf-aaf8-522bc9a02d39.mov

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29429)

### CODE REVIEW

**Comment by uladzimirdev** [comment]
LGTM, but I'm curious, why this "autocorrect" works only on the first blur from the input?

File: frontend/src/metabase-lib/expressions/format.js [hunk 1]
```diff
@@ -121,11 +121,27 @@ function formatOperator([op, ...args], options) {
...
+
+    // "*","/" always have two arguments. If the second argument of "/" is an expression, we have to calculate it first.
+    // Hence, adding parenthesis.
+    // "a / b * c" vs "a / (b * c)"
+    // "a / b / c" vs "a / (b / c)"
+    const isSamePrecedenceWithExecutionPriority =
+      index > 0 &&
+      isOperator(arg) &&
+      OPERATOR_PRECEDENCE[op] === OPERATOR_PRECEDENCE[argOp] &&
+      op === "/";
```
Comment (ranquild) [inline frontend/src/metabase-lib/expressions/format.js:139]: Could we remove this check? If yes, what would happen? Based on my testing it seems that we would preserve parenthesis that were entered manually for `+ - * =`, which I think is even better.

File: e2e/test/scenarios/question/summarization.cy.spec.js [hunk 2]
```diff
@@ -174,19 +174,22 @@ describe("scenarios > question > summarize sidebar", () => {
...
     openOrdersTable({ mode: "notebook" });
     summarize({ mode: "notebook" });
+
     popover().contains("Custom Expression").click();
     popover().within(() => {
-      cy.get(".ace_text-input").type(FORMULA).blur();
+      enterCustomColumnDetails({ formula: FORMULA });
+      cy.get("@formula").blur();
+
+      cy.wait(100); // waits for formula update after blur
```
Comment (ranquild) [inline e2e/test/scenarios/question/summarization.cy.spec.js:189]: We could rely on some visible effect of updating the formula rather than just waiting for some arbitrary amount. One idea is to rely on `SUM([Total])` being renamed to `Sum([Total])`.

**Review by ranquild — APPROVED** [review]
