### PR TITLE
Remove value-label-outline text to fix blurry night mode value labels

### LINKED ISSUE #13125: Embedded dark mode bar graph data points unreadable
**Describe the bug**
When embedding a question which is a bar chart using data points and the dark mode option is checked, the data points become unreadable. This doesn't apply to light mode

**Logs**
Not necessary

**To Reproduce**
1. Create a bar graph with data points enabled
2. Click share and then embed
3. Under style on the right click dark

**Expected behavior**
Data points to be clearly visible

**Screenshots**
Screen Shot 2020-08-17 at 12 13 16

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "5.3.0-1023-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-05-28",
      "tag": "v0.35.4",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "Europe/London"
    }
  }
}
```

**Severity**
This issue is annoying but users can hover over each bar and see the value the data point should show.

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #13125 

**Before**
Screen Shot 2022-04-28 at 11 50 44 AM

**After**
Screen Shot 2022-04-28 at 11 50 57 AM

**Testing**
1. Create a new question, Products table, Count rows, Group by Created At (month)
2. Click the "Settings" button in the footer and toggle the "Show values on data points" toggle
3. Save the question
4. Click on the sharing link in the footer, enable sharing, open up the public question link
5. Data points on the chart should look the same
6. Add `#theme=night` to the end of the public question link to view it in nightmode
7. Data points on the chart should no longer be blurry
8. Test in various browsers

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/chart_values.js [hunk 1]
```diff
@@ -320,7 +316,7 @@ export function onRenderValueLabels(
     addLabels(sample, compactForSeries[index]);
     const totalWidth = chart
       .svg()
-      .selectAll(".value-label-outline")
+      .selectAll(".value-label, .value-label-white")
```
Comment (daltojohnso) [inline frontend/src/metabase/visualizations/lib/chart_values.js:319]: Since the `text` with the `value-label-outline` class was ever present, we used it to calculate this `totalWidth` value. Now, we just need to select whichever of `value-label` or `.value-label-white` is present.

**Review by kulyk — APPROVED** [review]
Looks nice on Safari, Brave and Firefox 👍

**Review by ariya — APPROVED** [review]
Ship it :rocket:

**Comment by ariya** [comment]
Note: rebase to the latest master to have that failing unit test fixed.
