### PR TITLE
Extract sample DB to plugins directory on startup

### LINKED ISSUE #26648: Analysis of Sample DB on initial startup takes ~2 minutes
**Describe the bug**
Ever since the new sample database tables were changed to be unhidden by default in #26505, the initial sync of the DB when an instance is first started up has exploded to 2 minutes from around 2 seconds. This is because we're now running the `analysis` sync steps (including fingerprinting and fetching field values) on these new tables, and these steps take much longer than expected. Strangely, this only happens when you run Metabase as a jar, not when you start the backend from the REPL.

**Expected behavior**
Sample DB sync should not take more than a few seconds

**Severity**
P1 - blocking release per https://metaboat.slack.com/archives/C03DP70ENLF/p1668694650401319?thread_ts=1668690787.830959&cid=C03DP70ENLF

### PR DESCRIPTION
**Pull request by noahmoss**
Second go at fixing the slow startup times due to sample database sync. It seems that the slowdown has to do with reading directly from the database file in the JAR, so this PR copies it into the `plugins/` directory (which is supposed to be a stable, writable location) on startup.

Fixes https://github.com/metabase/metabase/issues/26648

### CODE REVIEW

File: src/metabase/plugins.clj [hunk 1]
```diff
@@ -17,41 +18,49 @@
...
-;; logic for determining plugins dir -- see below
-(defonce ^:private plugins-dir*
-  (delay
-    (let [filename (plugins-dir-filename)]
-      (try
-        ;; attempt to create <current-dir>/plugins if it doesn't already exist. Check that the directory is readable.
-        (let [path (u.files/get-path filename)]
-          (u.files/create-dir-if-not-exists! path)
+(def ^:private plugins-dir*
+  (memoize/memo
```
Comment (noahmoss) [inline src/metabase/plugins.clj:22]: Changed this from a `defonce` to a function memoized on the result of `plugins-dir-filename` to facilitate testing

File: src/metabase/sample_data.clj [hunk 2]
```diff
@@ -37,8 +76,11 @@
...
   "Update the path to the sample database DB if it exists in case the JAR has moved."
-  []
-  (when-let [sample-db (db/select-one Database :is_sample true)]
-    (let [intended (db-details)]
-      (when (not= (:details sample-db) intended)
-        (db/update! Database (:id sample-db) :details intended)))))
+  ([]
+   (update-sample-database-if-needed! (db/select-one Database :is_sample true)))
+
+  ([sample-db]
```
Comment (noahmoss) [inline src/metabase/sample_data.clj:82]: arity 1 here is also to facilitate testing

File: src/metabase/sample_data.clj [hunk 3]
```diff
@@ -3,42 +3,90 @@
...
-    {:db (-> (.getPath resource)
-             (str/replace #"^file:" "zip:") ; to connect to an H2 DB inside a JAR just replace file: with zip: (this doesn't do anything when running from the Clojure CLI, which has no `file:` prefix)
-             (str/replace #"\.mv\.db$" "")  ; strip the .mv.db suffix from the path
-             (str/replace #"%20" " ") ; for some reason the path can get URL-encoded and replace spaces with `%20`; this breaks things so switch them back to spaces
-             (str ";USER=GUEST;PASSWORD=guest"))})) ; specify the GUEST user account created for the DB
+    {:db
+     (if-not (:temp (plugins/plugins-dir-info))
+       (do
+        (extract-sample-database!)
+        (extracted-db-details))
```
Comment (metamben) [inline src/metabase/sample_data.clj:59]: Consider returning the details from `extract-sample-database!` (or computing the details from it).

**Review by metamben — APPROVED** [review]

File: src/metabase/sample_data.clj [hunk 4]
```diff
@@ -3,42 +3,90 @@
...
+  []
+  (u.files/with-open-path-to-resource [sample-db-path sample-database-filename]
+    (u.files/copy-file! sample-db-path (target-path))))
+
+(defn- process-sample-db-path
+  [base-path]
+  (-> base-path
+      (str/replace #"\.mv\.db$" "")        ; strip the .mv.db suffix from the path
+      (str/replace #"%20" " ")             ; for some reason the path can get URL-encoded and replace spaces with `%20`;
+                                           ;   this breaks things so switch them back to spaces
```
[the remark this answers is not in the document]
Comment (noahmoss) [reply src/metabase/sample_data.clj:32]: yeah, I suppose. this code was there before so I'm not sure if there's a reason full URL-decoding could break anything? I can't think of any

File: src/metabase/sample_data.clj [hunk 5]
```diff
@@ -3,42 +3,90 @@
...
 
 (def ^:private ^String sample-database-name     "Sample Database")
 (def ^:private ^String sample-database-filename "sample-database.db.mv.db")
 
-(defn- db-details []
+;; Reuse the plugins directory for the destination to extract the sample database because it's pretty much guaranteed
+;; to exist and be writable.
+(defn- target-path
+  []
+  (u.files/append-to-path (plugins/plugins-dir) sample-database-filename))
```
[the remark this answers is not in the document]
Comment (noahmoss) [reply src/metabase/sample_data.clj:20]: Good question. The only issue would be if a user puts an identical filename in that directory...seems unlikely but technically possible. I'll check with the writing team if there's a good place to mention this.

File: src/metabase/plugins.clj [hunk 6]
```diff
@@ -17,41 +18,48 @@
...
-            (assert (Files/isWritable path)
-              (trs "Metabase cannot write to temporary directory. Please set MB_PLUGINS_DIR to a writable directory and restart Metabase."))
-            path))))))
-
-;; Actual logic is wrapped in a delay rather than a normal function so we don't log the error messages more than once
-;; in cases where we have to fall back to the system temporary directory
-(defn- plugins-dir
-  "Get a `Path` to the Metabase plugins directory, creating it if needed. If it cannot be created for one reason or
-  another, or if we do not have write permissions for it, use a temporary directory instead."
+(def ^:private plugins-dir*
```
Comment (camsaul) [inline src/metabase/plugins.clj:21]: Not that it makes any difference to running things but I think it's nice to add `^{:arglists '([filename])}` just so Kondo knows it's a function and can do arg-count checks and so it pops up in your editor auto-complete
