### PR TITLE
Do not insert newlines when typing text in the native editor.

### LINKED ISSUE #40538: Creating a new native query inserts 3 newlines in sql editor
### Describe the bug

Click on "New > SQL query"

image

The cursor appears at the top of the text input. Start typing "select" and three new lines will be inserted
image

Seems to only manifest in Firefox and not chrome

### To Reproduce

stated above

### Expected behavior

no unintentional newlines

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

p3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/40538

### Description

Works around a weird quirk in the ACE editor that causes newlines to be inserted when focus is called to quickly.

We were already using a timeout elsewhere, this approach just consolidates that.

The original issue was introduced when [upgrading to React 18](https://github.com/metabase/metabase/pull/41975).

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> SQL Query
2. Start typing `SELECT`
3. Make sure the editor does not add spurious newlines

### Demo

https://github.com/metabase/metabase/assets/1250185/780ac0ba-101d-436b-8c4b-f0c2331409f6

### Checklist

I found no way to reproduce this issue in Cypress. I think the bug is innocent enough for it not to have e2e tests.

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx [hunk 1]
```diff
@@ -390,6 +395,18 @@ export class NativeQueryEditor extends Component<
...
+  focus() {
+    if (this.props.readOnly) {
+      return;
+    }
+
+    clearTimeout(this._focusTimeout);
+
+    // HACK: the cursor doesn't blink without this intended small delay
+    // HACK: the editor injects newlines into the query without this small delay
+    this._focusTimeout = setTimeout(() => this._editor?.focus(), 50);
```
Comment (uladzimirdev) [inline frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx:407]: out of curiosity, why not rAF?

Comment (romeovs) [reply frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx]: That works too! (I've updated the PR).

File: frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx [hunk 2]
```diff
@@ -316,6 +321,7 @@ export class NativeQueryEditor extends Component<
     if (this.props.cancelQueryOnLeave) {
       this.props.cancelQuery?.();
     }
+    window.cancelAnimationFrame(this._focusFrame);
```
Comment (uladzimirdev) [inline frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx:324]: do we really need to cancel animation frame? could you please record a glitch if we do not cancel it

File: e2e/test/scenarios/native/native-reproductions.cy.spec.js [hunk 3]
```diff
@@ -586,6 +586,7 @@ describe("issue 34330", () => {
 
     // can't use cy.type because it does not simulate the bug
     // Delay needed for React 18. TODO: fix shame
+    cy.wait(50);
```
Comment (uladzimirdev) [inline e2e/test/scenarios/native/native-reproductions.cy.spec.js:589]: @romeovs I tested locally with x6 throttling without this `cy.wait` and it passed to me. Could you please try to remove it?

if it doesn't work, there should be a popup with `loading...` message, so we can rely on it

**Review by uladzimirdev — APPROVED** [review]
