### PR TITLE
Fix starbust query cancellation with isClosed proxy implementations

### LINKED ISSUE #63731: Query cancellation fails for Trino with UnsupportedOperationException: isClosed in Starburst Driver
### Describe the bug

When a user attempts to cancel a running query against a Trino data source, the cancellation fails. The query continues to run on the Trino cluster until it eventually times out.

The Metabase logs show that this is caused by a `java.lang.UnsupportedOperationException: isClosed ` error originating from the Metabase Starburst driver proxy. This indicates the driver is attempting to call a method that is not supported by the Trino JDBC connection, causing the cancellation thread to crash before it can send the cancellation command to Trino.

### To Reproduce

1. Connect Metabase to a Trino database (version 453 in our case).
2. Execute a long-running query that takes more than a few seconds to complete.
3.  While the query is running, click the "Cancel" button in the Metabase UI.
4. Observe that the query continues to run on the Trino cluster (verifiable via the Trino UI).
5. Check the Metabase server logs for the UnsupportedOperationException stack trace.

### Expected behavior

The query should stop executing in Trino. 

### Logs

```
Exception in thread "async-dispatch-3" java.lang.UnsupportedOperationException: isClosed
    at metabase.driver.starburst.proxy$java.lang.Object$Statement$ed45fa56.isClosed(Unknown Source)
    at metabase.driver.sql_jdbc.execute$wire_up_canceled_chan_to_cancel_Statement_BANG_$fn__95971$state_machine__61636__auto____95976$fn__95978.invoke(execute.clj:557)
    at metabase.driver.sql_jdbc.execute$wire_up_canceled_chan_to_cancel_Statement_BANG_$fn__95971$state_machine__61636__auto____95976.invoke(execute.clj:555)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:58)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:57)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:62)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:60)
    at clojure.core.async.impl.ioc_macros$take_BANG_$fn__57968.invoke(ioc_macros.clj:71)
    at clojure.core.async.impl.channels$appm$fn__57784.invoke(channels.clj:36)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at clojure.core.async.impl.concurrent$counted_thread_factory$reify__39368$fn__39369.invoke(concurrent.clj:29)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.base/java.lang.Thread.run(Unknown Source)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "druid",
      "starburst"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-09-18",
      "tag": "v0.56.6.2",
      "hash": "5b06760"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "6.1.147-172.266.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

High

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/63731

### Description

Adds `isClosed` proxy implementations for statements and prepared statements. 

### How to verify

See repro steps in reported issue. The query should be cancelled without an exception. 

### Demo

todo

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/driver.clj [hunk 1]
```diff
@@ -758,7 +758,10 @@
     :database-replication
 
     ;; whether this driver supports checking table writeable permissions
-    :metadata/table-writable-check})
+    :metadata/table-writable-check
+
+    ;; Does this driver support creating a java.sql.Statement via a Connection?
+    :statements})
```
Comment (metamben) [inline src/metabase/driver.clj]: shouldn't this have a namespace? `jdbc` or something similar if there's nothing better.

**Review by metamben — APPROVED** [review]
LGTM
