### PR TITLE
Display trend line for Stack-100% bar charts

### LINKED ISSUE #25614: Trend line not visible when using Stacking 100%
**Describe the bug**
Trend line not visible when using Stacking 100%.

**To Reproduce**
1. Question > Sample > Products - summarize Count and Average of Price grouped by CreatedAt:Year
image
2. Change visualization to Bar or Area, visualization Settings > Display > enable Trend line, and set stacking to Stack 100%
image

**Expected behavior**
Display trendline similar to just stacked
image

**Information about your Metabase Installation:**
Tested 0.44.3

### PR DESCRIPTION
**Pull request by shaunlebron**
Closes https://github.com/metabase/metabase/issues/25614

### Description

To show trend lines for normalized stacked bar charts, we have to:

1. Ensure that the `_raw` property (needed for computing the trend line) remains attached to the `series` array after a series transformation is performed for normalized bar charts.
2. Normalize the trend line points so that they all total 100% for a given x.

### How to verify

Follow the repro steps in the issue above to verify that the trend line is now visible (for both stacked Bar and Area charts):

Stack | Stack 100% (This PR)
---|---
CleanShot 2023-07-24 at 23 03 52@2x | CleanShot 2023-07-24 at 23 04 04@2x
CleanShot 2023-07-24 at 23 24 03@2x | CleanShot 2023-07-24 at 23 24 17@2x

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/trends.js [hunk 1]
```diff
@@ -57,5 +57,5 @@ export function getTrendDataPointsFromInsight(insight, xDomain, count = 10) {
 
 function getValuesInRange(start, end, count) {
   const delta = (end - start) / (count - 1);
-  return _.range(start, end, delta).concat([end]);
+  return _.range(count).map(i => start + delta * i);
```
Comment (shaunlebron) [inline frontend/src/metabase/visualizations/lib/trends.js:60]: I wanted to guarantee that the array is always of size `count`.

**Comment by shaunlebron** [comment]
I will figure out how to test this when I get back on Friday.

**Review by alxnddr — COMMENTED** [review]
Looks good! Can you please add a percy test?

**Comment by shaunlebron** [comment]
> Looks good! Can you please add a percy test?

@alxnddr Thanks!  I added tests:

1.  unit spec for trend data normalization
2. e2e spec to ensure trend line is visible
3. percy test for detecting trend line changes

**Review by alxnddr — APPROVED** [review]

**Comment by alxnddr** [comment]
Bugfix can be backported to include them into x.47
