### PR TITLE
Restore cumulative aggregations before annotation

### LINKED ISSUE #21502: Cumulative operations are not named correctly in the series config
**Describe the bug**
When using a cumulative operation (Cumulative count of rows or cumulative sum of ...), the display name of the series is not built correctly, so for "Cumulative count of rows" we show "Count" and for "Cumulative sum of..." we show "Sum of ..." which confuses the users on multi-series charts.

**Logs**
There are no logs here

**To Reproduce**
1) Build a question with a cumulative operation like Orders -> Cumulative count of rows per created_at
2) Go to the settings of the chart and check the Display tab. You will see just "Count"

**Expected behavior**
Name the series as it should be: Cumulative count or Cumulative sum

**Screenshots**
This is for Cumulative count of rows
image

This is for Cumulative sum
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgres 14
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
It's cosmetic but it can lead to confusion

**Additional context**
NA

### PR DESCRIPTION
**Pull request by metamben**
Fixes #21502.

The fix is in `src/metabase/query_processor/middleware/annotate.clj`, the changes in `src/metabase/query_processor/middleware/cumulative_aggregations.clj` are cosmetic.

### CODE REVIEW

File: src/metabase/query_processor/middleware/annotate.clj [hunk 1]
```diff
@@ -475,9 +475,25 @@
...
+                             [:sum field]   [:cum-sum field]))
+                         (vec aggregations)
+                         replaced-indices)]
+    (assoc inner-query :aggregation restored)))
+
 (defmethod column-info :query
-  [{inner-query :query} results]
-  (u/prog1 (mbql-cols inner-query results)
+  [{inner-query :query,
+    replaced-indices :metabase.query-processor.middleware.cumulative-aggregations/replaced-indecies}
```
Comment (metamben) [inline src/metabase/query_processor/middleware/annotate.clj:492]: It's quite brittle to refer to data created by the `cumulative-aggregations` middleware here, but I couldn't find a simple way to encapsulate the whole functionality there, because post processing middleware cannot "modify" the query.

File: test/metabase/test/util.clj [hunk 2]
```diff
@@ -810,8 +810,10 @@
             (is (= "New Dashboard name" (t2/select-one-fn :name :model/Dashboard dash-id)))))
 
         (testing "outside macro, the changes should be reverted"
-          (is (= card (t2/select-one :model/Card card-id)))
-          (is (= dash (t2/select-one :model/Dashboard dash-id)))))
+          (is (= (dissoc card :updated_at)
+                 (dissoc (t2/select-one :model/Card card-id) :updated_at)))
+          (is (= (dissoc dash :updated_at)
+                 (dissoc (t2/select-one :model/Dashboard dash-id) :updated_at)))))
```
Comment (metamben) [inline test/metabase/test/util.clj:816]: Flaky test fix.

File: src/metabase/query_processor/middleware/cumulative_aggregations.clj [hunk 3]
```diff
@@ -7,15 +7,14 @@
 
 ;;;; Pre-processing
 
-(defn- diff-indecies
+(defn- diff-indices
```
Comment (snoe) [inline src/metabase/query_processor/middleware/cumulative_aggregations.clj:10]: typo in the docstring too

**Review by snoe — APPROVED** [review]
LGTM, would probably fix the indecies typo in the keyword unless it's used in a lot of other places.

File: src/metabase/query_processor/middleware/annotate.clj (hunk 1 above)
[the remark this answers is not in the document]
Comment (metamben) [reply src/metabase/query_processor/middleware/annotate.clj]: done

File: src/metabase/query_processor/middleware/cumulative_aggregations.clj (hunk 3 above)
Comment (metamben) [reply src/metabase/query_processor/middleware/cumulative_aggregations.clj:10]: done
