### PR TITLE
treat empty string parameter in url like it is unset

### LINKED ISSUE #17578: Empty filter parameters in the URL causes weird filter state
**Describe the bug**
When going to a SQL question with filters, but not defining values in the parameters, then the filters are applied in UI with blanks, while being auto-removed from the URL, and the query uses the blank values, which gives unexpected results and sometimes fails.

**To Reproduce**
1. Native query > Sample Dataset - variables should match filter type, and `category` and `created_at` are Field Filters to their respective columns - save the question.
image
```
select *
from PRODUCTS
where true
[[and CATEGORY={{text}}]]
[[and RATING>{{number}}]]
[[and CREATED_AT::date<{{date}}]]
[[and {{category}}]]
[[and {{created_at}}]]
limit 1
```
2. If the question ID is `1`, then go to the following URL - note that this will create a failed query:
`/question/1?text=&number=&date=&category=&created_at=`
Going to an URL, which doesn't have the `number` or `created_at` will run the query, but with "No results!".
3. The filters gets marked as filled-out state, but the URL is now auto-corrected to the following:
`/question/1?category=`
image

**Expected behavior**
If parameters are being auto-corrected in the URL, then they should not be applied to the filter state or the query.

**Information about your Metabase Installation:**
Tested 0.40.2 and master commit `b795f9f`

**Additional context**
Related to #13961 and #15498 and historically to #13960

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #17578 

This change let me simplify the `metabase/meta/Parameter.js` interface a bit, so I refactored it further to make it clearer what it does.

When building the map of parameter values from query parameters, we now ALWAYS treat a value of `""` as meaning the same thing as `null` or `undefined`. This means that for a native query, a value of `""` for a defaulted parameter will get set to the default value. On dashboards, it takes on a bit of special meaning; a defaulted parameter set to `""` will not defer to using the default value, unlike `undefined` and `null`.

Here's the behavior on a dashboard:

https://user-images.githubusercontent.com/13057258/133671178-b755d762-ab89-45e9-bb23-d51c58d3c074.mov

Here's the behavior for a native question:

https://user-images.githubusercontent.com/13057258/133671220-c5777b81-c8b7-4dc2-9fd5-e5bb2485a71f.mov

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
This seems to work great.

File: frontend/src/metabase/dashboard/actions.js [hunk 1]
```diff
@@ -707,15 +705,10 @@ export const fetchDashboard = createThunkAction(FETCH_DASHBOARD, function(
     }
 
     const parameterValuesById = preserveParameters
-      ? getParameterValuesByIdFromPreviousValues(
```
Comment (daltojohnso) [inline frontend/src/metabase/dashboard/actions.js:710]: Removed this util function because it didn't actually do anything to the given `parameterValues` value besides instantiate a new array

**Review by kulyk — APPROVED** [review]
LGTM
