### PR TITLE
Don't compute a different hash key if they only differ on the order of values in a parameter

### LINKED ISSUE #48887: Order of selected filter values may cause cache miss due to hash mismatch
### Describe the bug

The order in which values are selected in a category filter affects the hash used for query caching. This can lead to a cache miss when the same values are selected in a different order.

### To Reproduce

1. Create a question
2. Add it to a dashboard and link a category filter
3. Set caching policy for the dashboard: Duration: 1 hour
4. Select two values in the filter, e.g. 'Widget', 'Gizmo'
5. Check the logs, and note the question is being cached
6. Deselect the values
7. Select the same values again, but in a different order: 'Gizmo', 'Widget'
8. Check the logs and see a different cache key has been generated for the query

### Expected behavior

The same value selection should generate the same cache key, regardless of the order in which the values are selected.

### Logs

```{"parameters":[{"type":"string/=","value":["Widget","Gizmo"],"id":"5e84a14b","target":["dimension",["field",357,{"base-type":"type/Text","source-field":366}]]}],"dashboard_id":13,"dashboard_load_id":"f16cf5aa-588c-da10-ec07-fb56427b0329"}```

> metabase-v1.50.30-ee-1  | 2024-10-18 13:48:53,647 INFO middleware.cache :: Query 72082a2b took 24.2 ms to run; minimum for cache eligibility is 0.0 ns; eligible
> metabase-v1.50.30-ee-1  | 2024-10-18 13:48:53,647 INFO middleware.cache :: Caching results for next time for query with hash "72082a2b". 💾
> metabase-v1.50.30-ee-1  | 2024-10-18 13:48:53,671 DEBUG middleware.log :: POST /api/dashboard/13/dashcard/70/card/104/query 202 [ASYNC: completed] 151.7 ms (27 DB calls) App DB connections: 1/13 Jetty threads: 4/50 (8 idle, 0 queued) (133 total active threads) Queries in flight: 0 (0 queued); mysql DB 3 connections: 0/1 (0 threads blocked) {:metabase-user-id 1}

```{"parameters":[{"type":"string/=","value":["Gizmo","Widget"],"id":"5e84a14b","target":["dimension",["field",357,{"base-type":"type/Text","source-field":366}]]}],"dashboard_id":13,"dashboard_load_id":"ed9af5cd-b565-2fa2-c1cd-883162210e32"}```

> metabase-v1.50.30-ee-1  | 2024-10-18 13:50:54,825 INFO middleware.cache :: Query 197b7422 took 24.0 ms to run; minimum for cache eligibility is 0.0 ns; eligible
> metabase-v1.50.30-ee-1  | 2024-10-18 13:50:54,827 INFO middleware.cache :: Caching results for next time for query with hash "197b7422". 💾
> metabase-v1.50.30-ee-1  | 2024-10-18 13:50:54,860 DEBUG middleware.log :: POST /api/dashboard/13/dashcard/70/card/104/query 202 [ASYNC: completed] 200.4 ms (27 DB calls) App DB connections: 1/13 Jetty threads: 4/50 (10 idle, 0 queued) (127 total active threads) Queries in flight: 0 (0 queued); mysql DB 3 connections: 0/1 (0 threads blocked) {:metabase-user-id 1}

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-10-15",
      "tag": "v1.50.30",
      "hash": "a49cb77"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.19 (Debian 12.19-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.1.75-0-virt",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
}

### Severity

P2 - found it while troubleshooting something else

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nvoxland**
Closes #48887

### Description

Updated `select-keys-for-hashing` to sort parameter values

### How to verify

Steps from the issue:

1. Create a question
2. Add it to a dashboard and link a category filter
3. Set caching policy for the dashboard: Duration: 1 hour
4. Select two values in the filter, e.g. 'Widget', 'Gizmo'
5. Check the logs, and note the question is being cached
6. Deselect the values
7. Select the same values again, but in a different order: 'Gizmo', 'Widget'
8. Check the logs and see a different cache key has been generated for the query
 

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/util.clj [hunk 1]
```diff
@@ -94,6 +94,7 @@
   (let [{:keys [constraints parameters], :as query} (select-keys query [:database :lib/type :stages :parameters :constraints])]
     (cond-> query
       (empty? constraints) (dissoc :constraints)
+      true                 (update :parameters  (fn [params] (mapv #(if (sequential? (:value %)) (update % :value sort) %) params)))
```
Comment (noahmoss) [inline src/metabase/query_processor/util.clj:97]: nit - this might be enough logic to be worth pulling out to a helper function, like `walk-query-sort-maps`

**Review by noahmoss — APPROVED** [review]
