### PR TITLE
[QP] Drop last stage aggregations for questions in chain filtering

### LINKED ISSUE #43154: Filters connected to categorical fields don't work anymore if question is based on a model
### Describe the bug

We have a big regression in filters on dashboards. It does not even fire the query to populate the values

### To Reproduce

1) create a model (orders join people), save it
2) create a question based on that model, just get the entire model as a table
3) create a dashboard, add the question and add a categorical filter, connect it to "people - user -> source"
image
4) then save it and try to use the filter, you don't get any values
image

### Expected behavior

It should get the filter values

### Logs

NA

### Information about your Metabase installation

```JSON
v50, but I think this comes from v49
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bshepherdson**
Models are treated as opaque here, but for a saved question we expose
filters on the query before its final aggregation step.

This drops the aggregation clauses and gets the possible values for the
column of interest.

Fixes #43154.

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#43274** <a href="https://app.graphite.dev/github/pr/metabase/metabase/43274?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bshepherdson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ranquild — APPROVED** [review]

File: src/metabase/models/params/custom_values.clj [hunk 1]
```diff
@@ -63,21 +63,34 @@
...
+                                        (-> card :dataset_query :query))]
+                 ;; MBQL query - hijack the final stage, drop its aggregation and breakout (if any).
+                 (-> inner-mbql
+                     (dissoc :aggregation)
+                     (assoc :breakout [value-field-ref]
+                            :limit    *max-rows*)
+                     (update :filter (fn [old]
+                                       (if old
+                                         [:and old new-filter]
+                                         new-filter))))
```
Comment (metamben) [inline src/metabase/models/params/custom_values.clj:88]:
```suggestion
                                       (cond->> new-filter
                                         old (conj [:and old])))))
```

**Review by metamben — APPROVED** [review]
LGTM
