### PR TITLE
Fix question header when the original question is a native query

### LINKED ISSUE #48690: Wrong header when doing the native drill thru
### Describe the bug

When doing some of the native drill thrus (sort by this column, filter by this column, ...?), we show a header and breadcrumbs like it's a model
Image

### To Reproduce

1. Create and save a sql query like `select * from orders`
2. Click on the column header in the table view
3. Click sort button, or click Filter by this column and apply settings
4. See the header and breadcrumbs like for a model

### Expected behavior

We should show a header and breadcrumbs to reflect that it's a new ad-hoc mbql question created on top of the sql question as a data source.
Image

### Logs

_No response_

### Information about your Metabase installation

464902f

### Severity

Minor

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/48690

Changes:
- Converts `QuestionDataSource` utils to TypeScript
- Fixes a bug with an icon when the original question is a native query

How to verify:
- New -> SQL query -> `SELECT * FROM ORDERS` -> Save as `SQL query` -> Run
- Click on a cell -> Filter -> Click on an operator -> You should get an ad-hoc query
- Check that the icon in the query builder header is now `table2`, which matches what you get in the notebook editor (click `Show Editor` to verify)

Screenshot 2024-10-16 at 21 53 51

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/utils.tsx [hunk 1]
```diff
@@ -43,32 +61,34 @@ export function getDataSourceParts({
...
-        href: database.id >= 0 && Urls.browseSchema(table),
+        href: database.id >= 0 ? Urls.browseSchema(table) : undefined,
       });
     }
   }
 
   if (table) {
     const hasTableLink = subHead || isObjectDetail;
     if (isNative) {
-      return {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/utils.tsx:68]: This was a bug or unreachable code.

File: frontend/src/metabase-types/api/table.ts [hunk 2]
```diff
@@ -1,4 +1,4 @@
-import type { Card } from "./card";
+import type { Card, CardType } from "./card";
```
Comment (kamilmielnik) [inline frontend/src/metabase-types/api/table.ts:1]: 1. New -> SQL query -> SELECT * FROM ORDERS -> Save as SQL query -> Run
2. Click on "Explore results"

The icon in query builder header is now `database` - is this expected?
If you go to the editor the data source will have `table2` icon.

3. Click on a cell -> Filter -> Click on an operator -> You should get an ad-hoc query

The icon in query builder header is still `database` - is this expected?
If you go to the editor the data source will have `table2` icon.

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.unit.spec.js [hunk 3]
```diff
@@ -571,4 +577,36 @@ describe("QuestionDataSource", () => {
     setup({ card: SOURCE_CARD, subHead: true });
     expect(screen.queryByLabelText("More info")).not.toBeInTheDocument();
   });
+
+  it("should show the correct icon when the original question is a native query", () => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.unit.spec.js:581]:
```suggestion
  it("should show the correct icon when the original question is a native query (metabase#48690)", () => {
```

**Review by kamilmielnik — APPROVED** [review]
