### PR TITLE
use the correct endpoint for downloading results from dashboards

### LINKED ISSUE #28876: Download CSV/XLSX/JSON from card on dashboard when filter applied produces invalid data download
**Describe the bug**
When attempting to download CSV from dashboard card if a filter is applied to dashboard that affects the card, the CSV produced is invalid and contains a stack trace. Attempted XLSX/JSON but got stack traces for those too and XLSX was corrupted.

**Logs**
image

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create and save a question with a table of Invoices from Sample Database
2. Add that saved question to a dashboard
3. Add a date filter to filter Invoices - Created At
4. Save dashboard
5. Select a valid date range, and update filter
6. Select 3 dots and under Download full results, select csv/xlsx/json

**Expected behavior**
- Download a valid CSV/XLSX/JSON

**Screenshots/videos**
image

```
cause:"Invalid   parameter: Card 7
--
030 does not have a template tag named   nil."
data:{"type":"invalid-parameter"
invalid-parameter:{"type":"date/all-options"
value:"2020-01-10~2020-10-31"
id:"8d025f60"
target:["dimension"
["field"
521858
{"source-field":521872}]]}
allowed-parameters:null}
message:"Invalid parameter: Card 7
030 does not have a template tag named   nil."
invalid-parameter:{"type":"date/all-options"
value:"2020-01-10~2020-10-31"
id:"8d025f60"
target:["dimension"
["field"
521858
{"source-field":521872}]]}
allowed-parameters:null}
```

**Information about your Metabase Installation:**

- Chrome: Version 110.0.5481.177 (Official Build) (x86_64)
- Metabase version: latest (stats)

**Severity**
- Broken functionality, will affect any users attempting to download filtered data on dashboard

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/28876

### Description

Switch to the correct endpoint when downloading results from dashcards. It should have been `api/dashboard/${dashboardId}/dashcard/${dashcardId}/card/${card.id}/query/${type}` instead of `api/card/${card.id}/query/${type}` which was used previously.

### How to verify

1. New question -> Sample Dataset -> Orders -> Save question
2. Create a dashboard, add the question
3. Ensure you can export csv/xlsx/json from the card
4. Add a dashboard filter, connect it to the question, filter by any value
5. Ensure you can export csv/xlsx/json from the card

### Checklist

- [x] Tests have been added/updated to cover changes in this PR — added e2e tests, will add specs on `utils.ts` later today

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/QueryDownloadWidget/utils.ts [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+      params: params,
+    };
+  }
+
+  const isSavedQuery = card?.id != null;
+  if (isSavedQuery) {
+    return {
+      url: `api/card/${card.id}/query/${type}`,
+      params: { parameters: JSON.stringify(result?.json_query?.parameters) },
+    };
```
Comment (EmmadUsmani) [inline frontend/src/metabase/query_builder/components/QueryDownloadWidget/utils.ts:79]: Why is there no `method` field for this return value unlike the ones above?

File: frontend/src/metabase/query_builder/components/QueryDownloadWidget/utils.ts [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+  }
+
+  const isUnsavedQuery = card && !card.id;
+  if (isUnsavedQuery) {
+    return {
+      url: `api/dataset/${type}`,
+      params: {
+        query: JSON.stringify(_.omit(result?.json_query, "constraints")),
+        visualization_settings: JSON.stringify(visualizationSettings),
+      },
```
Comment (EmmadUsmani) [inline frontend/src/metabase/query_builder/components/QueryDownloadWidget/utils.ts:89]: Also no `method` here, not sure if it this is intentional.

**Review by EmmadUsmani — APPROVED** [review]
Looks good 👍
