### PR TITLE
[QP] Fix confusion of expressions with the same name as columns

### LINKED ISSUE #25931: Expression name with spaces causes incorrect aliasing when used together with Custom Column on BigQuery
**Describe the bug**
Expression name with spaces causes incorrect aliasing when used together with Custom Column on BigQuery.
Historically similar to #22310.

Workaround: Only use expression names without spaces.

**To Reproduce**
1. Question > **BigQuery** > Products
2. Summarize Custom Expression `1 * 1` as "expression name with spaces" grouped by Category
3. Custom Column `1 * 1` as "CC"
image

<details><summary>Full stacktrace</summary>

```
2022-10-14 15:40:48,480 ERROR middleware.catch-exceptions :: Error processing query: 400 Bad Request
POST https://www.googleapis.com/bigquery/v2/projects/metabase-bigquery-driver/queries
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "q",
    "locationType" : "parameter",
    "message" : "Name expression name with spaces not found inside source at [2:195]",
    "reason" : "invalidQuery"
  } ],
  "message" : "Name expression name with spaces not found inside source at [2:195]",
  "status" : "INVALID_ARGUMENT"
}
{:database_id 43,
 :started_at #t "2022-10-14T15:40:47.389879+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class com.google.cloud.bigquery.BigQueryException,
   :error "Name expression name with spaces not found inside source at [2:195]",
   :stacktrace
   ["com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)"
    "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:652)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1278)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1275)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
    "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
    "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
    "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1274)"
    "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1262)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__82495.invoke(bigquery_cloud_sdk.clj:193)"]}
  {:status :failed,
   :class java.util.concurrent.ExecutionException,
   :error
   "com.google.cloud.bigquery.BigQueryException: Name expression name with spaces not found inside source at [2:195]",
   :stacktrace
   ["java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)"
    "java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)"
    "clojure.core$deref_future.invokeStatic(core.clj:2317)"
    "clojure.core$future_call$reify__8544.deref(core.clj:7041)"
    "clojure.core$deref.invokeStatic(core.clj:2337)"
    "clojure.core$deref.invoke(core.clj:2323)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:181)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:177)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:219)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:217)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__82596.invoke(bigquery_cloud_sdk.clj:279)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:287)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:271)"
    "driver.bigquery_cloud_sdk$fn__82602.invokeStatic(bigquery_cloud_sdk.clj:307)"
    "driver.bigquery_cloud_sdk$fn__82602.invoke(bigquery_cloud_sdk.clj:299)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___52619.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__48140.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__51564.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__54095$combined_post_process__54100$combined_post_process_STAR___54101.invoke(query_processor.clj:212)"
    "query_processor$fn__54095$combined_pre_process__54096$combined_pre_process_STAR___54097.invoke(query_processor.clj:209)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52540$fn__52545.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52540.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__48575.invoke(fetch_source_query.clj:353)"
    "query_processor.middleware.store$initialize_store$fn__48763$fn__48764.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__48763.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__52812.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__49845.invoke(constraints.clj:53)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__52751.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__53123.invoke(catch_exceptions.clj:167)"
    "query_processor.reducible$async_qp$qp_STAR___44978$thunk__44980.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___44978.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___44978.invoke(reducible.clj:91)"
    "query_processor.reducible$sync_qp$qp_STAR___44989.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:327)"
    "query_processor$fn__54142$process_query_and_save_execution_BANG___54151$fn__54154.invoke(query_processor.clj:342)"
    "query_processor$fn__54142$process_query_and_save_execution_BANG___54151.invoke(query_processor.clj:335)"
    "query_processor$fn__54186$process_query_and_save_with_max_results_constraints_BANG___54195$fn__54198.invoke(query_processor.clj:354)"
    "query_processor$fn__54186$process_query_and_save_with_max_results_constraints_BANG___54195.invoke(query_processor.clj:347)"
    "api.dataset$run_query_async$fn__68893.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__40096$fn__40097.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__40096.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__19006.invoke(streaming_response.clj:84)"]}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: com.google.cloud.bigquery.BigQueryException: Name expression name with spaces not found inside source at [2:195]",
   :stacktrace
   ["--> driver.bigquery_cloud_sdk$throw_invalid_query.invokeStatic(bigquery_cloud_sdk.clj:173)"
    "driver.bigquery_cloud_sdk$throw_invalid_query.invoke(bigquery_cloud_sdk.clj:172)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:215)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:177)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:219)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:217)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__82596.invoke(bigquery_cloud_sdk.clj:279)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:287)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:271)"
    "driver.bigquery_cloud_sdk$fn__82602.invokeStatic(bigquery_cloud_sdk.clj:307)"
    "driver.bigquery_cloud_sdk$fn__82602.invoke(bigquery_cloud_sdk.clj:299)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___52619.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__48140.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__51564.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__54095$combined_post_process__54100$combined_post_process_STAR___54101.invoke(query_processor.clj:212)"
    "query_processor$fn__54095$combined_pre_process__54096$combined_pre_process_STAR___54097.invoke(query_processor.clj:209)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52540$fn__52545.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52540.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__48575.invoke(fetch_source_query.clj:353)"
    "query_processor.middleware.store$initialize_store$fn__48763$fn__48764.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__48763.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__52812.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__49845.invoke(constraints.clj:53)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__52751.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__53123.invoke(catch_exceptions.clj:167)"
    "query_processor.reducible$async_qp$qp_STAR___44978$thunk__44980.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___44978.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___44978.invoke(reducible.clj:91)"
    "query_processor.reducible$sync_qp$qp_STAR___44989.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:327)"
    "query_processor$fn__54142$process_query_and_save_execution_BANG___54151$fn__54154.invoke(query_processor.clj:342)"
    "query_processor$fn__54142$process_query_and_save_execution_BANG___54151.invoke(query_processor.clj:335)"
    "query_processor$fn__54186$process_query_and_save_with_max_results_constraints_BANG___54195$fn__54198.invoke(query_processor.clj:354)"
    "query_processor$fn__54186$process_query_and_save_with_max_results_constraints_BANG___54195.invoke(query_processor.clj:347)"
    "api.dataset$run_query_async$fn__68893.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__40096$fn__40097.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__40096.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__19006.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: 6e55ba9bb45e8854094984093b76c20d41fe3a2e0ef6c1532b5bc00c69b7d190\nSELECT `source`.`category` AS `category`, `source`.`expression_name_with_spaces` AS `expression_name_with_spaces`, `source`.`CC` AS `CC` FROM (SELECT `source`.`category` AS `category`, `source`.`expression name with spaces` AS `expression_name_with_spaces`, (1 * 1) AS `CC` FROM (SELECT `v6_sample_dataset.products`.`category` AS `category`, (1 * 1) AS `expression_name_with_spaces` FROM `v6_sample_dataset.products` GROUP BY `category` ORDER BY `category` ASC) `source`) `source` LIMIT 10",
    :parameters nil}}],
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :query
  {:source-query
   {:source-table 6177,
    :aggregation
    [["aggregation-options"
      ["*" 1 1]
      {:name "expression name with spaces", :display-name "expression name with spaces"}]],
    :breakout [["field" 35280 nil]]},
   :expressions {:CC ["*" 1 1]},
   :limit 10},
  :database 43,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT `source`.`category` AS `category`, `source`.`expression_name_with_spaces` AS `expression_name_with_spaces`, `source`.`CC` AS `CC` FROM (SELECT `source`.`category` AS `category`, `source`.`expression name with spaces` AS `expression_name_with_spaces`, (1 * 1) AS `CC` FROM (SELECT `v6_sample_dataset.products`.`category` AS `category`, (1 * 1) AS `expression_name_with_spaces` FROM `v6_sample_dataset.products` GROUP BY `category` ORDER BY `category` ASC) `source`) `source` LIMIT 10",
  :params nil,
  :table-name "source",
  :mbql? true},
 :status :failed,
 :class com.google.api.client.googleapis.json.GoogleJsonResponseException,
 :stacktrace
 ["com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)"
  "com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)"
  "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:650)"
  "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1278)"
  "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1275)"
  "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
  "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
  "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
  "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1274)"
  "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1262)"
  "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__82495.invoke(bigquery_cloud_sdk.clj:193)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "400 Bad Request\nPOST https://www.googleapis.com/bigquery/v2/projects/metabase-bigquery-driver/queries\n{\n  \"code\" : 400,\n  \"errors\" : [ {\n    \"domain\" : \"global\",\n    \"location\" : \"q\",\n    \"locationType\" : \"parameter\",\n    \"message\" : \"Name expression name with spaces not found inside source at [2:195]\",\n    \"reason\" : \"invalidQuery\"\n  } ],\n  \"message\" : \"Name expression name with spaces not found inside source at [2:195]\",\n  \"status\" : \"INVALID_ARGUMENT\"\n}",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:expressions {"CC" [:* 1 1]},
   :limit 10,
   :source-metadata
   [{:semantic_type :type/Category,
     :table_id 6177,
     :coercion_strategy nil,
     :name "category",
     :settings nil,
     :field_ref [:field 35280 nil],
     :effective_type :type/Text,
     :nfc_path nil,
     :parent_id nil,
     :id 35280,
     :display_name "Category",
     :fingerprint
     {:global {:distinct-count 4, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
     :base_type :type/Text}
    {:name "expression name with spaces",
     :display_name "expression name with spaces",
     :base_type :type/Float,
     :field_ref [:aggregation 0]}],
   :fields [[:field 35280 nil] [:field "expression name with spaces" {:base-type :type/Float}] [:expression "CC"]],
   :source-query
   {:source-table 6177,
    :aggregation
    [[:aggregation-options
      [:* 1 1]
      {:name "expression name with spaces", :display-name "expression name with spaces"}]],
    :breakout [[:field 35280 nil]],
    :order-by [[:asc [:field 35280 nil]]]}},
  :database 43,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 1, :context :ad-hoc}},
 :data {:rows [], :cols []}}

2022-10-14 15:40:48,484 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.1 s (18 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (3 idle, 0 queued) (103 total active threads) Queries in flight: 0 (0 queued)

```

</details>

**Information about your Metabase Installation:**
Tested 0.44.4

### LINKED ISSUE #39059: Custom columns that have same name as existing columns cause failure
### Describe the bug

Using PostgreSQL 15.1 as the data source,

I attempted the following custom column expression within the notebook editor for a model:  
 `coalesce([approved_change_orders], 0)` named: `approved_change_orders`

This results in the following error:
```
ERROR: column source.approved_change_orders does not exist
  Hint: Perhaps you meant to reference the column "source.approved_change_orders_2".
  Position: 740
```

### To Reproduce

1. Create a model using the notebook editor
2. Create a custom column that coalesces over an existing column
3. Name the custom column same as the old column
4. Attempt to run

Note: I did try removing the original column and keeping only the custom column- with varying results... At one point, I got it to work. At another point, I couldn't reproduce that success. Metabase seems to want to keep the original column visually checked in the notebook, even if logically it is unchecked.

image

### Expected behavior

The query should run without error

### Logs

```
[f813fc80-23db-477a-8fd7-1a59e35a2d41] 2024-02-22T07:04:23-08:00 INFO metabase.api.dataset Source query for this query is Card 140
[f813fc80-23db-477a-8fd7-1a59e35a2d41] 2024-02-22T07:04:23-08:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: ERROR: column source.approved_change_orders does not exist
  Hint: Perhaps you meant to reference the column "source.approved_change_orders_2".
  Position: 740
{:database_id 5,
 :started_at #t "2024-02-22T15:04:23.487278Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: ERROR: column source.approved_change_orders does not exist\n  Hint: Perhaps you meant to reference the column \"source.approved_change_orders_2\".\n  Position: 740",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__77840$fn__77841.invoke(execute.clj:698)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__77840.invoke(execute.clj:695)"
    "driver.sql_jdbc.execute$fn__77633$fn__77634.invoke(execute.clj:388)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
    "driver.sql_jdbc.execute$fn__77633.invokeStatic(execute.clj:382)"
    "driver.sql_jdbc.execute$fn__77633.invoke(execute.clj:380)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:686)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
    "driver.sql_jdbc$fn__105608.invokeStatic(sql_jdbc.clj:82)"
    "driver.sql_jdbc$fn__105608.invoke(sql_jdbc.clj:80)"
    "query_processor.context$executef.invokeStatic(context.clj:60)"
    "query_processor.context$executef.invoke(context.clj:49)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
    "query_processor.context.default$default_runf.invoke(default.clj:42)"
    "query_processor.context$runf.invokeStatic(context.clj:46)"
    "query_processor.context$runf.invoke(context.clj:40)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70834.invoke(cache.clj:229)"
    "query_processor.middleware.permissions$check_query_permissions$fn__65043.invoke(permissions.clj:140)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__70655.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__70665.invoke(enterprise.clj:64)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__69902.invoke(mbql_to_native.clj:24)"
    "query_processor$fn__71968$combined_post_process__71973$combined_post_process_STAR___71974.invoke(query_processor.clj:262)"
    "query_processor$fn__71968$combined_pre_process__71969$combined_pre_process_STAR___71970.invoke(query_processor.clj:259)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__65140.invoke(fetch_source_query.clj:299)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__70745$fn__70749.invoke(resolve_database_and_driver.clj:77)"
    "driver$do_with_driver.invokeStatic(driver.clj:94)"
    "driver$do_with_driver.invoke(driver.clj:89)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__70745.invoke(resolve_database_and_driver.clj:76)"
    "query_processor.middleware.store$initialize_store$fn__65532$fn__65533.invoke(store.clj:14)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.middleware.store$initialize_store$fn__65532.invoke(store.clj:13)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__70742.invoke(resolve_database_and_driver.clj:60)"
    "query_processor.middleware.normalize_query$normalize$fn__71047.invoke(normalize_query.clj:38)"
    "query_processor.middleware.enterprise$fn__70682$handle_audit_app_internal_queries__70683$fn__70685.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__70693.invoke(enterprise.clj:103)"
    "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__69617.invoke(constraints.clj:102)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__70978.invoke(process_userland_query.clj:156)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__71568.invoke(catch_exceptions.clj:171)"
    "query_processor.reducible$async_qp$qp_STAR___60713$thunk__60715.invoke(reducible.clj:126)"
    "query_processor.reducible$async_qp$qp_STAR___60713.invoke(reducible.clj:132)"
    "query_processor.reducible$sync_qp$qp_STAR___60725.doInvoke(reducible.clj:153)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
    "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
    "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
    "api.dataset$run_query_async$fn__93366.invoke(dataset.clj:79)"
    "query_processor.streaming$streaming_response_STAR_$fn__51578$fn__51580.invoke(streaming.clj:168)"
    "query_processor.streaming$streaming_response_STAR_$fn__51578.invoke(streaming.clj:167)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
    "async.streaming_response$do_f_async$task__42901.invoke(streaming_response.clj:88)"],
   :error_type :invalid-query,
   :ex-data
   {:driver :postgres,
    :sql
    ["-- Metabase:: userID: 1 queryType: MBQL queryHash: 96b313781f5c9de8504952de479874fc1b45878a12b7f9239be6839bc990c6fe"
     "SELECT"
     "  \"source\".\"id\" AS \"id\","
     "  \"source\".\"project_id\" AS \"project_id\","
     "  \"source\".\"division_id\" AS \"division_id\","
     "  \"source\".\"phase_id\" AS \"phase_id\","
     "  \"source\".\"subjob_id\" AS \"subjob_id\","
     "  \"source\".\"cost_type_id\" AS \"cost_type_id\","
     "  \"source\".\"original_budget\" AS \"original_budget\","
     "  \"source\".\"budget_modifications\" AS \"budget_modifications\","
     "  \"source\".\"pending_budget_changes\" AS \"pending_budget_changes\","
     "  \"source\".\"committed_costs\" AS \"committed_costs\","
     "  \"source\".\"cost_to_date\" AS \"cost_to_date\","
     "  \"source\".\"pending_cost_changes\" AS \"pending_cost_changes\","
     "  \"source\".\"source\" AS \"source\","
     "  \"source\".\"last_modified\" AS \"last_modified\","
     "  \"source\".\"approved_change_orders\" AS \"approved_change_orders\""
     "FROM"
     "  ("
     "    SELECT"
     "      \"source\".\"id\" AS \"id\","
     "      \"source\".\"project_id\" AS \"project_id\","
     "      \"source\".\"division_id\" AS \"division_id\","
     "      \"source\".\"phase_id\" AS \"phase_id\","
     "      \"source\".\"subjob_id\" AS \"subjob_id\","
     "      \"source\".\"cost_type_id\" AS \"cost_type_id\","
     "      \"source\".\"original_budget\" AS \"original_budget\","
     "      \"source\".\"budget_modifications\" AS \"budget_modifications\","
     "      \"source\".\"pending_budget_changes\" AS \"pending_budget_changes\","
     "      \"source\".\"committed_costs\" AS \"committed_costs\","
     "      \"source\".\"cost_to_date\" AS \"cost_to_date\","
     "      \"source\".\"pending_cost_changes\" AS \"pending_cost_changes\","
     "      \"source\".\"source\" AS \"source\","
     "      \"source\".\"last_modified\" AS \"last_modified\","
     "      \"source\".\"approved_change_orders_2\" AS \"approved_change_orders_2\""
     "    FROM"
     "      ("
     "        SELECT"
     "          \"budgets\".\"wbs_cost\".\"id\" AS \"id\","
     "          \"budgets\".\"wbs_cost\".\"project_id\" AS \"project_id\","
     "          \"budgets\".\"wbs_cost\".\"division_id\" AS \"division_id\","
     "          \"budgets\".\"wbs_cost\".\"phase_id\" AS \"phase_id\","
     "          \"budgets\".\"wbs_cost\".\"subjob_id\" AS \"subjob_id\","
     "          \"budgets\".\"wbs_cost\".\"cost_type_id\" AS \"cost_type_id\","
     "          \"budgets\".\"wbs_cost\".\"original_budget\" AS \"original_budget\","
     "          \"budgets\".\"wbs_cost\".\"budget_modifications\" AS \"budget_modifications\","
     "          \"budgets\".\"wbs_cost\".\"approved_change_orders\" AS \"approved_change_orders\","
     "          \"budgets\".\"wbs_cost\".\"pending_budget_changes\" AS \"pending_budget_changes\","
     "          \"budgets\".\"wbs_cost\".\"committed_costs\" AS \"committed_costs\","
     "          \"budgets\".\"wbs_cost\".\"cost_to_date\" AS \"cost_to_date\","
     "          \"budgets\".\"wbs_cost\".\"pending_cost_changes\" AS \"pending_cost_changes\","
     "          \"budgets\".\"wbs_cost\".\"source\" AS \"source\","
     "          \"budgets\".\"wbs_cost\".\"last_modified\" AS \"last_modified\","
     "          COALESCE(\"budgets\".\"wbs_cost\".\"approved_change_orders\", 0) AS \"approved_change_orders_2\","
     "          \"phase - phase_id\".\"cost_code\" AS \"phase - phase_id__cost_code\","
     "          \"phase - phase_id\".\"id\" AS \"phase - phase_id__id\""
     "        FROM"
     "          \"budgets\".\"wbs_cost\""
     "          LEFT JOIN \"wbs\".\"phase\" AS \"phase - phase_id\" ON \"budgets\".\"wbs_cost\".\"phase_id\" = \"phase - phase_id\".\"id\""
     "        WHERE"
     "          NOT (\"budgets\".\"wbs_cost\".\"source\" = ?)"
     "          OR ("
     "            NOT (\"phase - phase_id\".\"cost_code\" = ?)"
     "            AND NOT (\"phase - phase_id\".\"cost_code\" = ?)"
     "          )"
     "      ) AS \"source\""
     "    ORDER BY"
     "      \"source\".\"phase - phase_id__cost_code\" ASC"
     "  ) AS \"source\""
     "LIMIT"
     "  2000"],
    :params ("realpage" "55-9800" "55-9900"),
    :type :invalid-query}}],
 :action_id nil,
 :state "42703",
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :database 5,
  :query {:source-table "card__140"},
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"id\" AS \"id\", \"source\".\"project_id\" AS \"project_id\", \"source\".\"division_id\" AS \"division_id\", \"source\".\"phase_id\" AS \"phase_id\", \"source\".\"subjob_id\" AS \"subjob_id\", \"source\".\"cost_type_id\" AS \"cost_type_id\", \"source\".\"original_budget\" AS \"original_budget\", \"source\".\"budget_modifications\" AS \"budget_modifications\", \"source\".\"pending_budget_changes\" AS \"pending_budget_changes\", \"source\".\"committed_costs\" AS \"committed_costs\", \"source\".\"cost_to_date\" AS \"cost_to_date\", \"source\".\"pending_cost_changes\" AS \"pending_cost_changes\", \"source\".\"source\" AS \"source\", \"source\".\"last_modified\" AS \"last_modified\", \"source\".\"approved_change_orders\" AS \"approved_change_orders\" FROM (SELECT \"source\".\"id\" AS \"id\", \"source\".\"project_id\" AS \"project_id\", \"source\".\"division_id\" AS \"division_id\", \"source\".\"phase_id\" AS \"phase_id\", \"source\".\"subjob_id\" AS \"subjob_id\", \"source\".\"cost_type_id\" AS \"cost_type_id\", \"source\".\"original_budget\" AS \"original_budget\", \"source\".\"budget_modifications\" AS \"budget_modifications\", \"source\".\"pending_budget_changes\" AS \"pending_budget_changes\", \"source\".\"committed_costs\" AS \"committed_costs\", \"source\".\"cost_to_date\" AS \"cost_to_date\", \"source\".\"pending_cost_changes\" AS \"pending_cost_changes\", \"source\".\"source\" AS \"source\", \"source\".\"last_modified\" AS \"last_modified\", \"source\".\"approved_change_orders_2\" AS \"approved_change_orders_2\" FROM (SELECT \"budgets\".\"wbs_cost\".\"id\" AS \"id\", \"budgets\".\"wbs_cost\".\"project_id\" AS \"project_id\", \"budgets\".\"wbs_cost\".\"division_id\" AS \"division_id\", \"budgets\".\"wbs_cost\".\"phase_id\" AS \"phase_id\", \"budgets\".\"wbs_cost\".\"subjob_id\" AS \"subjob_id\", \"budgets\".\"wbs_cost\".\"cost_type_id\" AS \"cost_type_id\", \"budgets\".\"wbs_cost\".\"original_budget\" AS \"original_budget\", \"budgets\".\"wbs_cost\".\"budget_modifications\" AS \"budget_modifications\", \"budgets\".\"wbs_cost\".\"approved_change_orders\" AS \"approved_change_orders\", \"budgets\".\"wbs_cost\".\"pending_budget_changes\" AS \"pending_budget_changes\", \"budgets\".\"wbs_cost\".\"committed_costs\" AS \"committed_costs\", \"budgets\".\"wbs_cost\".\"cost_to_date\" AS \"cost_to_date\", \"budgets\".\"wbs_cost\".\"pending_cost_changes\" AS \"pending_cost_changes\", \"budgets\".\"wbs_cost\".\"source\" AS \"source\", \"budgets\".\"wbs_cost\".\"last_modified\" AS \"last_modified\", COALESCE(\"budgets\".\"wbs_cost\".\"approved_change_orders\", 0) AS \"approved_change_orders_2\", \"phase - phase_id\".\"cost_code\" AS \"phase - phase_id__cost_code\", \"phase - phase_id\".\"id\" AS \"phase - phase_id__id\" FROM \"budgets\".\"wbs_cost\" LEFT JOIN \"wbs\".\"phase\" AS \"phase - phase_id\" ON \"budgets\".\"wbs_cost\".\"phase_id\" = \"phase - phase_id\".\"id\" WHERE NOT (\"budgets\".\"wbs_cost\".\"source\" = ?) OR (NOT (\"phase - phase_id\".\"cost_code\" = ?) AND NOT (\"phase - phase_id\".\"cost_code\" = ?))) AS \"source\" ORDER BY \"source\".\"phase - phase_id__cost_code\" ASC) AS \"source\" LIMIT 1048575",
  :params ("realpage" "55-9800" "55-9900")},
 :status :failed,
 :class org.postgresql.util.PSQLException,
 :stacktrace
 ["org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)"
  "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)"
  "org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)"
  "org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)"
  "--> driver.sql_jdbc.execute$fn__77757.invokeStatic(execute.clj:556)"
  "driver.sql_jdbc.execute$fn__77757.invoke(execute.clj:554)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:569)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:565)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__77840$fn__77841.invoke(execute.clj:696)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__77840.invoke(execute.clj:695)"
  "driver.sql_jdbc.execute$fn__77633$fn__77634.invoke(execute.clj:388)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
  "driver.sql_jdbc.execute$fn__77633.invokeStatic(execute.clj:382)"
  "driver.sql_jdbc.execute$fn__77633.invoke(execute.clj:380)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:686)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc$fn__105608.invokeStatic(sql_jdbc.clj:82)"
  "driver.sql_jdbc$fn__105608.invoke(sql_jdbc.clj:80)"
  "query_processor.context$executef.invokeStatic(context.clj:60)"
  "query_processor.context$executef.invoke(context.clj:49)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
  "query_processor.context.default$default_runf.invoke(default.clj:42)"
  "query_processor.context$runf.invokeStatic(context.clj:46)"
  "query_processor.context$runf.invoke(context.clj:40)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70834.invoke(cache.clj:229)"
  "query_processor.middleware.permissions$check_query_permissions$fn__65043.invoke(permissions.clj:140)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__70655.invoke(enterprise.clj:51)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__70665.invoke(enterprise.clj:64)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__69902.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__71968$combined_post_process__71973$combined_post_process_STAR___71974.invoke(query_processor.clj:262)"
  "query_processor$fn__71968$combined_pre_process__71969$combined_pre_process_STAR___71970.invoke(query_processor.clj:259)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__65140.invoke(fetch_source_query.clj:299)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__70745$fn__70749.invoke(resolve_database_and_driver.clj:77)"
  "driver$do_with_driver.invokeStatic(driver.clj:94)"
  "driver$do_with_driver.invoke(driver.clj:89)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__70745.invoke(resolve_database_and_driver.clj:76)"
  "query_processor.middleware.store$initialize_store$fn__65532$fn__65533.invoke(store.clj:14)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.middleware.store$initialize_store$fn__65532.invoke(store.clj:13)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__70742.invoke(resolve_database_and_driver.clj:60)"
  "query_processor.middleware.normalize_query$normalize$fn__71047.invoke(normalize_query.clj:38)"
  "query_processor.middleware.enterprise$fn__70682$handle_audit_app_internal_queries__70683$fn__70685.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__70693.invoke(enterprise.clj:103)"
  "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__69617.invoke(constraints.clj:102)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__70978.invoke(process_userland_query.clj:156)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__71568.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___60713$thunk__60715.invoke(reducible.clj:126)"
  "query_processor.reducible$async_qp$qp_STAR___60713.invoke(reducible.clj:132)"
  "query_processor.reducible$sync_qp$qp_STAR___60725.doInvoke(reducible.clj:153)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
  "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
  "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
  "api.dataset$run_query_async$fn__93366.invoke(dataset.clj:79)"
  "query_processor.streaming$streaming_response_STAR_$fn__51578$fn__51580.invoke(streaming.clj:168)"
  "query_processor.streaming$streaming_response_STAR_$fn__51578.invoke(streaming.clj:167)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__42901.invoke(streaming_response.clj:88)"],
 :card_id 140,
 :context :ad-hoc,
 :error
 "ERROR: column source.approved_change_orders does not exist\n  Hint: Perhaps you meant to reference the column \"source.approved_change_orders_2\".\n  Position: 740",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :database 5,
  :query
  {:source-card-id 140,
   :source-metadata
   [{:description nil,
     :semantic_type :type/PK,
     :coercion_strategy nil,
     :name "id",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5136 {:base-type :type/Integer}],
     :effective_type :type/Integer,
     :id 5136,
     :visibility_type :normal,
     :display_name "id",
     :fingerprint nil,
     :base_type :type/Integer}
    {:description nil,
     :semantic_type :type/Category,
     :coercion_strategy nil,
     :name "project_id",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5139 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5139,
     :visibility_type :normal,
     :display_name "project_id",
     :fingerprint
     {:global {:distinct-count 28, :nil% 0.0},
      :type
      {:type/Number
       {:min 12.0, :q1 19.52158164046306, :q3 30.000926863170704, :max 46.0, :sd 6.529207780843288, :avg 25.4391}}},
     :base_type :type/BigInteger}
    {:description nil,
     :semantic_type :type/FK,
     :coercion_strategy nil,
     :name "division_id",
     :settings nil,
     :fk_target_field_id 4809,
     :field_ref [:field 5148 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5148,
     :visibility_type :normal,
     :display_name "division_id",
     :fingerprint {:global {:distinct-count 50, :nil% 0.0}},
     :base_type :type/BigInteger}
    {:description nil,
     :semantic_type :type/FK,
     :coercion_strategy nil,
     :name "phase_id",
     :settings nil,
     :fk_target_field_id 4816,
     :field_ref [:field 5141 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5141,
     :visibility_type :normal,
     :display_name "phase_id",
     :fingerprint {:global {:distinct-count 444, :nil% 0.0}},
     :base_type :type/BigInteger}
    {:description nil,
     :semantic_type nil,
     :coercion_strategy nil,
     :name "subjob_id",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5135 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5135,
     :visibility_type :normal,
     :display_name "subjob_id",
     :fingerprint
     {:global {:distinct-count 215, :nil% 0.4417},
      :type
      {:type/Number
       {:min 153.0,
        :q1 228.7728093528213,
        :q3 324.8630031964761,
        :max 375.0,
        :sd 56.79493084837947,
        :avg 276.75998567078625}}},
     :base_type :type/BigInteger}
    {:description nil,
     :semantic_type :type/FK,
     :coercion_strategy nil,
     :name "cost_type_id",
     :settings nil,
     :fk_target_field_id 4805,
     :field_ref [:field 5146 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5146,
     :visibility_type :normal,
     :display_name "cost_type_id",
     :fingerprint {:global {:distinct-count 12, :nil% 0.0}},
     :base_type :type/BigInteger}
    {:description nil,
     :semantic_type nil,
     :coercion_strategy nil,
     :name "original_budget",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5142 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5142,
     :visibility_type :normal,
     :display_name "original_budget",
     :fingerprint
     {:global {:distinct-count 2927, :nil% 0.0},
      :type
      {:type/Number
       {:min -15000.0,
        :q1 1650.862028593805,
        :q3 42427.612653579316,
        :max 6.1998921E7,
        :sd 1222692.0637818938,
        :avg 98694.22240099999}}},
     :base_type :type/Float}
    {:description nil,
     :semantic_type nil,
     :coercion_strategy nil,
     :name "budget_modifications",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5143 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5143,
     :visibility_type :normal,
     :display_name "budget_modifications",
     :fingerprint
     {:global {:distinct-count 5372, :nil% 0.0},
      :type
      {:type/Number
       {:min -1.3961544E7,
        :q1 -46696.048316343105,
        :q3 38079.889821447665,
        :max 7593650.0,
        :sd 388669.6167360365,
        :avg 3251.8723759999975}}},
     :base_type :type/Float}
    {:description nil,
     :semantic_type nil,
     :coercion_strategy nil,
     :name "pending_budget_changes",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5137 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5137,
     :visibility_type :normal,
     :display_name "pending_budget_changes",
     :fingerprint
     {:global {:distinct-count 2, :nil% 0.0},
      :type {:type/Number {:min -3102.5, :q1 -909.0115014843832, :q3 0.0, :max 0.0, :sd 31.025, :avg -0.31025}}},
     :base_type :type/Float}
    {:description nil,
     :semantic_type nil,
     :coercion_strategy nil,
     :name "committed_costs",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5138 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5138,
     :visibility_type :normal,
     :display_name "committed_costs",
     :fingerprint
     {:global {:distinct-count 3608, :nil% 0.0},
      :type
      {:type/Number
       {:min -29039.42,
        :q1 -3164.494824706897,
        :q3 25252.15706035909,
        :max 4299662.6,
        :sd 195574.55726043574,
        :avg 52424.216188}}},
     :base_type :type/Float}
    {:description nil,
     :semantic_type nil,
     :coercion_strategy nil,
     :name "cost_to_date",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5147 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5147,
     :visibility_type :normal,
     :display_name "cost_to_date",
     :fingerprint
     {:global {:distinct-count 5167, :nil% 0.0},
      :type
      {:type/Number
       {:min -73583.93,
        :q1 -9618.972334975959,
        :q3 30335.417426701963,
        :max 5.321365176E7,
        :sd 1068676.5332191263,
        :avg 88005.01605499999}}},
     :base_type :type/Float}
    {:description nil,
     :semantic_type nil,
     :coercion_strategy nil,
     :name "pending_cost_changes",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5144 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5144,
     :visibility_type :normal,
     :display_name "pending_cost_changes",
     :fingerprint
     {:global {:distinct-count 15, :nil% 0.0},
      :type
      {:type/Number
       {:min -2546.0,
        :q1 -744.6993419748337,
        :q3 282.1369614765108,
        :max 194237.5,
        :sd 2771.6265922608873,
        :avg 52.010897}}},
     :base_type :type/Float}
    {:description nil,
     :semantic_type :type/Source,
     :coercion_strategy nil,
     :name "source",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5140 {:base-type :type/Text}],
     :effective_type :type/Text,
     :id 5140,
     :visibility_type :normal,
     :display_name "source",
     :fingerprint
     {:global {:distinct-count 2, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 7.0735}}},
     :base_type :type/Text}
    {:description nil,
     :semantic_type nil,
     :coercion_strategy nil,
     :unit :default,
     :name "last_modified",
     :settings nil,
     :fk_target_field_id nil,
     :field_ref [:field 5145 {:base-type :type/DateTime, :temporal-unit :default}],
     :effective_type :type/DateTime,
     :id 5145,
     :visibility_type :normal,
     :display_name "last_modified",
     :fingerprint
     {:global {:distinct-count 4890, :nil% 0.0},
      :type {:type/DateTime {:earliest "2024-01-23T18:43:06.147593Z", :latest "2024-02-13T15:31:25.346999Z"}}},
     :base_type :type/DateTime}
    {:display_name "approved_change_orders",
     :semantic_type nil,
     :field_ref [:expression "approved_change_orders"],
     :name "approved_change_orders",
     :base_type :type/Float,
     :effective_type :type/Float,
     :coercion_strategy nil,
     :fingerprint
     {:global {:distinct-count 1, :nil% 0.0},
      :type {:type/Number {:min 0.0, :q1 0.0, :q3 0.0, :max 0.0, :sd nil, :avg 0.0}}}}],
   :source-query/dataset? true,
   :fields
   [[:field 5136 {:base-type :type/Integer}]
    [:field 5139 {:base-type :type/BigInteger}]
    [:field 5148 {:base-type :type/BigInteger}]
    [:field 5141 {:base-type :type/BigInteger}]
    [:field 5135 {:base-type :type/BigInteger}]
    [:field 5146 {:base-type :type/BigInteger}]
    [:field 5142 {:base-type :type/Float}]
    [:field 5143 {:base-type :type/Float}]
    [:field 5137 {:base-type :type/Float}]
    [:field 5138 {:base-type :type/Float}]
    [:field 5147 {:base-type :type/Float}]
    [:field 5144 {:base-type :type/Float}]
    [:field 5140 {:base-type :type/Text}]
    [:field 5145 {:base-type :type/DateTime, :temporal-unit :default}]
    [:field "approved_change_orders" {:base-type :type/Float}]],
   :source-query
   {:source-table 307,
    :order-by [[:asc [:field 4818 {:base-type :type/Text, :join-alias "phase - phase_id"}]]],
    :expressions {"approved_change_orders" [:coalesce [:field 5134 {:base-type :type/Float}] 0]},
    :fields
    [[:field 5136 {:base-type :type/Integer}]
     [:field 5139 {:base-type :type/BigInteger}]
     [:field 5148 {:base-type :type/BigInteger}]
     [:field 5141 {:base-type :type/BigInteger}]
     [:field 5135 {:base-type :type/BigInteger}]
     [:field 5146 {:base-type :type/BigInteger}]
     [:field 5142 {:base-type :type/Float}]
     [:field 5143 {:base-type :type/Float}]
     [:field 5137 {:base-type :type/Float}]
     [:field 5138 {:base-type :type/Float}]
     [:field 5147 {:base-type :type/Float}]
     [:field 5144 {:base-type :type/Float}]
     [:field 5140 {:base-type :type/Text}]
     [:field 5145 {:base-type :type/DateTime, :temporal-unit :default}]
     [:expression "approved_change_orders"]],
    :filter
    [:or
     [:not
      [:=
       [:field 5140 {:base-type :type/Text}]
       [:value
        "realpage"
        {:base_type :type/Text,
         :effective_type :type/Text,
         :coercion_strategy nil,
         :semantic_type :type/Source,
         :database_type "varchar",
         :name "source"}]]]
     [:and
      [:not
       [:=
        [:field 4818 {:base-type :type/Text, :join-alias "phase - phase_id"}]
        [:value
         "55-9800"
         {:base_type :type/Text,
          :effective_type :type/Text,
          :coercion_strategy nil,
          :semantic_type nil,
          :database_type "bpchar",
          :name "cost_code"}]]]
      [:not
       [:=
        [:field 4818 {:base-type :type/Text, :join-alias "phase - phase_id"}]
        [:value
         "55-9900"
         {:base_type :type/Text,
          :effective_type :type/Text,
          :coercion_strategy nil,
          :semantic_type nil,
          :database_type "bpchar",
          :name "cost_code"}]]]]],
    :joins
    [{:alias "phase - phase_id",
      :strategy :left-join,
      :condition
      [:=
       [:field 5141 {:base-type :type/BigInteger}]
       [:field 4816 {:base-type :type/Integer, :join-alias "phase - phase_id"}]],
      :source-table 282}]},
   :limit 1048575,
   :metabase.query-processor.middleware.limit/original-limit nil},
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id 140,
   :metadata/dataset-metadata
   [{:semantic_type :type/PK,
     :name "id",
     :field_ref [:field 5136 {:base-type :type/Integer}],
     :effective_type :type/Integer,
     :id 5136,
     :visibility_type :normal,
     :display_name "id",
     :base_type :type/Integer}
    {:semantic_type :type/Category,
     :name "project_id",
     :field_ref [:field 5139 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5139,
     :visibility_type :normal,
     :display_name "project_id",
     :fingerprint
     {:global {:distinct-count 28, :nil% 0.0},
      :type
      {:type/Number
       {:min 12.0, :q1 19.52158164046306, :q3 30.000926863170704, :max 46.0, :sd 6.529207780843288, :avg 25.4391}}},
     :base_type :type/BigInteger}
    {:semantic_type :type/FK,
     :name "division_id",
     :fk_target_field_id 4809,
     :field_ref [:field 5148 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5148,
     :visibility_type :normal,
     :display_name "division_id",
     :fingerprint {:global {:distinct-count 50, :nil% 0.0}},
     :base_type :type/BigInteger}
    {:semantic_type :type/FK,
     :name "phase_id",
     :fk_target_field_id 4816,
     :field_ref [:field 5141 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5141,
     :visibility_type :normal,
     :display_name "phase_id",
     :fingerprint {:global {:distinct-count 444, :nil% 0.0}},
     :base_type :type/BigInteger}
    {:name "subjob_id",
     :field_ref [:field 5135 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5135,
     :visibility_type :normal,
     :display_name "subjob_id",
     :fingerprint
     {:global {:distinct-count 215, :nil% 0.4417},
      :type
      {:type/Number
       {:min 153.0,
        :q1 228.7728093528213,
        :q3 324.8630031964761,
        :max 375.0,
        :sd 56.79493084837947,
        :avg 276.75998567078625}}},
     :base_type :type/BigInteger}
    {:semantic_type :type/FK,
     :name "cost_type_id",
     :fk_target_field_id 4805,
     :field_ref [:field 5146 {:base-type :type/BigInteger}],
     :effective_type :type/BigInteger,
     :id 5146,
     :visibility_type :normal,
     :display_name "cost_type_id",
     :fingerprint {:global {:distinct-count 12, :nil% 0.0}},
     :base_type :type/BigInteger}
    {:name "original_budget",
     :field_ref [:field 5142 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5142,
     :visibility_type :normal,
     :display_name "original_budget",
     :fingerprint
     {:global {:distinct-count 2927, :nil% 0.0},
      :type
      {:type/Number
       {:min -15000.0,
        :q1 1650.862028593805,
        :q3 42427.612653579316,
        :max 6.1998921E7,
        :sd 1222692.0637818938,
        :avg 98694.22240099999}}},
     :base_type :type/Float}
    {:name "budget_modifications",
     :field_ref [:field 5143 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5143,
     :visibility_type :normal,
     :display_name "budget_modifications",
     :fingerprint
     {:global {:distinct-count 5372, :nil% 0.0},
      :type
      {:type/Number
       {:min -1.3961544E7,
        :q1 -46696.048316343105,
        :q3 38079.889821447665,
        :max 7593650.0,
        :sd 388669.6167360365,
        :avg 3251.8723759999975}}},
     :base_type :type/Float}
    {:name "pending_budget_changes",
     :field_ref [:field 5137 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5137,
     :visibility_type :normal,
     :display_name "pending_budget_changes",
     :fingerprint
     {:global {:distinct-count 2, :nil% 0.0},
      :type {:type/Number {:min -3102.5, :q1 -909.0115014843832, :q3 0.0, :max 0.0, :sd 31.025, :avg -0.31025}}},
     :base_type :type/Float}
    {:name "committed_costs",
     :field_ref [:field 5138 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5138,
     :visibility_type :normal,
     :display_name "committed_costs",
     :fingerprint
     {:global {:distinct-count 3608, :nil% 0.0},
      :type
      {:type/Number
       {:min -29039.42,
        :q1 -3164.494824706897,
        :q3 25252.15706035909,
        :max 4299662.6,
        :sd 195574.55726043574,
        :avg 52424.216188}}},
     :base_type :type/Float}
    {:name "cost_to_date",
     :field_ref [:field 5147 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5147,
     :visibility_type :normal,
     :display_name "cost_to_date",
     :fingerprint
     {:global {:distinct-count 5167, :nil% 0.0},
      :type
      {:type/Number
       {:min -73583.93,
        :q1 -9618.972334975959,
        :q3 30335.417426701963,
        :max 5.321365176E7,
        :sd 1068676.5332191263,
        :avg 88005.01605499999}}},
     :base_type :type/Float}
    {:name "pending_cost_changes",
     :field_ref [:field 5144 {:base-type :type/Float}],
     :effective_type :type/Float,
     :id 5144,
     :visibility_type :normal,
     :display_name "pending_cost_changes",
     :fingerprint
     {:global {:distinct-count 15, :nil% 0.0},
      :type
      {:type/Number
       {:min -2546.0,
        :q1 -744.6993419748337,
        :q3 282.1369614765108,
        :max 194237.5,
        :sd 2771.6265922608873,
        :avg 52.010897}}},
     :base_type :type/Float}
    {:semantic_type :type/Source,
     :name "source",
     :field_ref [:field 5140 {:base-type :type/Text}],
     :effective_type :type/Text,
     :id 5140,
     :visibility_type :normal,
     :display_name "source",
     :fingerprint
     {:global {:distinct-count 2, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 7.0735}}},
     :base_type :type/Text}
    {:unit :default,
     :name "last_modified",
     :field_ref [:field 5145 {:base-type :type/DateTime, :temporal-unit :default}],
     :effective_type :type/DateTime,
     :id 5145,
     :visibility_type :normal,
     :display_name "last_modified",
     :fingerprint
     {:global {:distinct-count 4890, :nil% 0.0},
      :type {:type/DateTime {:earliest "2024-01-23T18:43:06.147593Z", :latest "2024-02-13T15:31:25.346999Z"}}},
     :base_type :type/DateTime}
    {:display_name "approved_change_orders",
     :field_ref [:expression "approved_change_orders"],
     :name "approved_change_orders",
     :base_type :type/Float,
     :effective_type :type/Float,
     :fingerprint
     {:global {:distinct-count 1, :nil% 0.0},
      :type {:type/Number {:min 0.0, :q1 0.0, :q3 0.0, :max 0.0, :avg 0.0}}}}]}},
 :data {:rows [], :cols []}}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.1.55-75.123.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-12",
      "tag": "v0.48.6",
      "hash": "b8818f9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

low - valid workarounds exist. Just move the work onto the db instead.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bshepherdson**
When determining column aliases in `add-alias-info`, reuse an existing
desired column alias if one is present.

Fixes #39059. Might fix #25931.

### CODE REVIEW

**Comment by bshepherdson** [comment]
Current dependencies on/for this PR:
* **#39255** <a href="https://app.graphite.dev/github/pr/metabase/metabase/39255?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/39255?utm_source=stack-comment).

File: src/metabase/query_processor/util/add_alias_info.clj [hunk 1]
```diff
@@ -316,6 +321,11 @@
                        (qp.store/->legacy-metadata field)))
     (:name field)))
 
+(defn- field-requires-original-field-name
+  "JSON extraction fields need to be named with their outer `field-name`, not use any existing `::desired-alias`."
+  [field-clause]
+  (boolean (some-> field-clause field-instance :nfc-path)))
```
Comment (metamben) [inline src/metabase/query_processor/util/add_alias_info.clj:327]: Is there a test for this situation?

**Review by metamben — APPROVED** [review]
LGTM

File: src/metabase/query_processor/util/add_alias_info.clj (hunk 1 above)
Comment (bshepherdson) [reply src/metabase/query_processor/util/add_alias_info.clj:327]: Yes, but unfortunately they're DB-specific because JSON unfolding support is not widespread.
