### PR TITLE
The new sync refactor

### LINKED ISSUE #4309: Metabase - Duplicate entry error during migration from h2db to mysql
Hi,

I am trying to migrate metabase(latest version) db from h2db to mysql. When I run the migration command, I see the following error. Could you please advise?

```
java -jar metabase.jar load-from-h2 /opt/metabase/metabase.db
02-06 06:03:04 INFO metabase.util :: Loading Metabase...
02-06 06:03:12 INFO metabase.db :: Verifying mysql Database Connection ...
02-06 06:03:12 DEBUG metabase.driver :: Registered driver :mysql 🚚
02-06 06:03:12 INFO metabase.db :: Verify Database Connection ...  ✅
02-06 06:03:12 INFO metabase.db :: Running Database Migrations...
02-06 06:03:12 INFO metabase.db :: Setting up Liquibase...
02-06 06:03:12 INFO metabase.db :: Liquibase is ready.
02-06 06:03:12 INFO metabase.db :: Checking if Database has unrun migrations...
02-06 06:03:28 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Temporarily disabling DB constraints...
[OK]
Transfering 9 instances of Database....[OK]
Transfering 1430 instances of RawTable........[OK]
Transfering 16640 instances of RawColumn........................................BatchUpdateException:
 Message: Duplicate entry '1019-paymenttype' for key 'uniq_raw_column_table_name'
 SQLState: 23000
 Error Code: 1062
java.sql.BatchUpdateException: Duplicate entry '1019-paymenttype' for key 'uniq_raw_column_table_name'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1161)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:426)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:419)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__2749.invoke(jdbc.clj:792)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:791)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
	at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1069)
	at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1061)
	at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1110)
	at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1093)
	at metabase.cmd.load_from_h2$insert_entity_BANG_$fn__32077.invoke(load_from_h2.clj:132)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:131)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:113)
	at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:147)
	at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:141)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__32157.invoke(load_from_h2.clj:216)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:629)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:213)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:206)
	at clojure.lang.Var.invoke(Var.java:379)
	at metabase.core$load_from_h2.invokeStatic(core.clj:219)
	at metabase.core$load_from_h2.invoke(core.clj:212)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$run_cmd$fn__32911.invoke(core.clj:273)
	at metabase.core$run_cmd.invokeStatic(core.clj:273)
	at metabase.core$run_cmd.doInvoke(core.clj:272)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$_main.invokeStatic(core.clj:287)
	at metabase.core$_main.doInvoke(core.clj:283)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1019-paymenttype' for key 'uniq_raw_column_table_name'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
	... 48 more
Command failed with exception: Duplicate entry '1019-paymenttype' for key 'uniq_raw_column_table_name'
```

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #4309, #3086, #4991. #3448 can also be closed but we should wait a release or two to take out those tables to avoid any potential headaches

### CODE REVIEW

File: src/metabase/models/table.clj [hunk 1]
```diff
@@ -151,48 +151,3 @@
   [table-id]
   {:pre [(integer? table-id)]}
   (db/select-one-field :db_id Table, :id table-id))
-
-
-;;; ------------------------------------------------------------ Persistence Functions ------------------------------------------------------------
-
-(defn retire-tables!
```
Comment (salsakran) [inline src/metabase/models/table.clj]: why are we removing this? Is it because this was only called from the Raw/introspect whatnotery?

File: src/metabase/sync/analyze/special_types/values.clj [hunk 2]
```diff
@@ -0,0 +1,165 @@
...
+             [interface :as i]
+             [util :as sync-util]]
+            [metabase.util.schema :as su]
+            [schema.core :as s]
+            [toucan.db :as db]))
+
+(def ^:private Values
+  "Schema for the VALUES passed to each of the functions below. *Guaranteed* to be non-nil and non-empty."
+  ;; Validating against this is actually pretty quick, in the order of microseconds even for a 10,000 value sequence
+  (s/constrained [(s/pred (complement nil?))] seq "Non-empty sequence of non-nil values."))
```
Comment (salsakran) [inline src/metabase/sync/analyze/special_types/values.clj]: One of the parts of the fingerprint spec is to count the number of nils.

Comment (salsakran) [inline src/metabase/sync/analyze/special_types/values.clj]: So not sure this is in line with how we want to be doing this long term.

File: src/metabase/sync/util.clj [hunk 3]
```diff
@@ -0,0 +1,231 @@
...
+;; functions below that do things like prevent duplicate operations from being ran simultaneously and taking care of
+;; things like event publishing, error handling, and logging.
+;;
+;; These basically operate in a middleware pattern, where the various different steps take a function, and return a new function
+;; that will execute the original in whatever context or with whatever side effects appropriate for that step.
+
+
+;; This looks something like {:sync #{1 2}, :cache #{2 3}} when populated.
+;; Key is a type of sync operation, e.g. `:sync` or `:cache`; vals are sets of DB IDs undergoing that operation.
+(defonce ^:private operation->db-ids (atom {}))
```
Comment (salsakran) [inline src/metabase/sync/util.clj]: I would prefer something like this be done via the DB. This is digging us deeper in the hole of "things that prevent us from being multi-server"

File: src/metabase/sync/util.clj [hunk 4]
```diff
@@ -0,0 +1,231 @@
...
+;;; +------------------------------------------------------------------------------------------------------------------------+
+
+;; This is primarily provided because it makes sync more fun to look at. The functions below make it fairly simple to log a
+;; progress bar with a corresponding emoji when iterating over a sequence of objects during sync, e.g. syncing all the Tables
+;; in a given Database.
+
+(def ^:private ^:const ^Integer emoji-meter-width 50)
+
+(def ^:private progress-emoji
+  ["😱"   ; face screaming in fear
```
Comment (salsakran) [inline src/metabase/sync/util.clj]: No more emoji

**Review by salsakran — APPROVED** [review]
This is a reasonable intermediate step, but misses the mark on a few things

1. We still can't independently schedule syncing, analysis and field value caching which is *the most important driver for doing this*
2. The split of analysis into a fingerprint + a classification is missing.
3. While the removal of the raw* is a net positive, it seems to consume half the code in this PR. See point (1). 

I'm ok with merging this as-is, but it distinctly does not fulfill the specific goals of taking this work on. 

We still do the actual work of reducing the number of times we run `analyze` on a database.

File: src/metabase/sync/util.clj (hunk 4 above)
Comment (camsaul) [inline src/metabase/sync/util.clj]: this is the exact same code that was already there I just moved it

File: src/metabase/models/table.clj (hunk 1 above)
Comment (camsaul) [inline src/metabase/models/table.clj]: yup

**Comment by camsaul** [comment]
> 1. We still can't independently schedule syncing, analysis and field value caching which is *the most important driver for doing this*

@salsakran we talked about this yesterday. This PR doesn't change the scheduling logic. It does break up the things we want to be scheduled separately into separate steps. So we *can* independently schedule things which will be done as part 2 once this is merged.

> 2. The split of analysis into a fingerprint + a classification is missing.

The fingerprint stuff from the other PR didn't really do anything. Since it wasn't critical to allowing separate schedules it's left out of this PR, which again is a "part 1" of a few parts of sync refactoring.

> 3. While the removal of the raw* is a net positive, it seems to consume half the code in this PR. See point (1).

After banging my head against the wall trying to untangle the messes that were the old code and the other sync refactor PR I figured it was just faster and cleaner to rewrite things and pull in the good pieces as I went. We also talked about that

**Comment by salsakran** [comment]
Cool. In which case, we should merge + test this and leave https://github.com/metabase/metabase/issues/4991 open.

File: src/metabase/sync/util.clj (hunk 3 above)
Comment (camsaul) [inline src/metabase/sync/util.clj]: that's a good point I'll see what I can do

**Comment by camsaul** [comment]
@salsakran I think this PR can actually close out #4991 since we already have a separate issue, #4262, for adding fine-grained metadata sync scheduling options. Otherwise #4991 is just a dupe of #4262

File: src/metabase/sync/analyze/special_types/values.clj (hunk 2 above)
Comment (camsaul) [inline src/metabase/sync/analyze/special_types/values.clj]: we can definitely start saving that information down the road but I tried to keep the scope of this PR small so I skipped introducing new models that as of yet don't serve any purpose.

Don't want to fall into the RawTable/RawColumn trap :D

**Comment by brijendra98** [comment]
#5292 Is still not fixed. Please help, I am facing exactly the same issue.

**Comment by camsaul** [comment]
@brijendra98 we haven't shipped this PR yet, we're planning on shipping it as part of 0.26.0

**Comment by brijendra98** [comment]
@camsaul Thanks a lot for your prompt response!
When can I expect that to be, roughly?

**Comment by camsaul** [comment]
@brijendra98 I think we're planning on releasing in the next month or so
