### PR TITLE
Preserve original cause in serdes load errors when app DB tx is aborted

### LINKED ISSUE #72724: Remote sync load errors masked by app DB transaction aborted when reporting fails
## Describe the bug

When a remote sync / serdes v2 load fails partway through, the real exception is frequently replaced by a confusing `current transaction is aborted, commands ignored until end of transaction block` error. The real root cause (FK resolution failure, constraint violation, etc.) is lost before it can be surfaced to the user or logs.

### Root cause

`load-metabase!` wraps the entire import in `t2/with-transaction` ([load.clj L214](https://github.com/metabase/metabase/blob/master/enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj#L214)).

When `serdes/load-one!` throws a SQL-level error for one entity, Postgres marks the transaction as aborted — subsequent statements on the same connection fail with `current transaction is aborted…` until rollback.

The catch block at [load.clj L183-186](https://github.com/metabase/metabase/blob/master/enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj#L183-L186) tries to enrich the exception:

```clojure
(catch Exception e
  (throw (ex-info (format "Failed to load into database for %s" (serdes/log-path-str path))
                  (path-error-data ::load-failure expanding path)
                  e)))
```

…but `path-error-data` calls `serdes/load-find-local`, which runs a `SELECT`. Because the transaction is already poisoned, that SELECT throws the aborted-tx error. `path-error-data` never returns, so `(ex-info … e)` is never constructed, and the *real* cause `e` is lost. The exception that propagates is the aborted-tx one from the enrichment code, with no link to the actual failure.

### Example stack trace (from a real support ticket)

```
clojure.lang.ExceptionInfo: ERROR: current transaction is aborted, commands ignored until end of transaction block
  {:toucan2/context-trace [["execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnectionJdbc43Full"
                            {:toucan2.jdbc.query/sql-args
                             ["SELECT * FROM \"report_card\" WHERE \"entity_id\" = ?" "<entity_id>"]}] …]}
  at metabase.models.serialization$lookup_by_id.invokeStatic(serialization.clj:851)
  at metabase_enterprise.serialization.v2.load$path_error_data.invokeStatic(load.clj:69)
  at metabase_enterprise.serialization.v2.load$load_one_BANG_.invokeStatic(load.clj:186)
  …
  at metabase_enterprise.serialization.v2.load$load_metabase_BANG_$with_connection_STAR___129131$with_transaction_STAR___129132.invoke(load.clj:232)
```

The visible `SELECT` here is the one inside `path-error-data`, not the statement that actually failed. The original SQL error is nowhere in the trace.

## To Reproduce

1. Set up remote sync against a repo that contains an entity whose load will hit a SQL error on import (e.g. a Card whose `database_id` resolves to nil and whose target column is NOT NULL; or any entity that triggers a constraint violation on insert/update).
2. Trigger a pull / reload.
3. Observe the user-facing error: `Failed to reload from git repository: ERROR: current transaction is aborted, commands ignored until end of transaction block`.
4. Check the server logs — the real SQL error is not wrapped into the thrown exception; you only see the aborted-tx chain from `path-error-data`.

## Expected behavior

`path-error-data` should never replace the real cause. If the local-id lookup fails because the transaction is poisoned (or any other reason), `:local-id` should be omitted/`nil`, but the `ex-info` must still be constructed with the original `e` chained as the cause so downstream code (and logs, and `source-error-message` in remote sync) can see the actual failure.

## Impact

Every remote sync support ticket that involves a mid-load failure surfaces the same misleading aborted-tx error. Support engineers can't tell whether the underlying failure is a missing FK, constraint violation, bad data, etc. without reproducing the import locally and instrumenting. It also hides the specific handling in `source-error-message` (e.g. "database not found", "Missing commit", "does not exist on this instance") which rely on the real cause being chained.

## Severity

P2 — functional, but severely harms diagnosability of other remote sync bugs.

### PR DESCRIPTION
**Pull request by rolodato**
Closes https://github.com/metabase/metabase/issues/72724

### Description

When `serdes/load-one!` throws during a remote sync / serdes v2 load, the catch block in `load-one!` tries to enrich the error via `path-error-data`. That helper calls `serdes/load-find-local`, which runs a `SELECT`. When the real failure was a SQL error, the outer transaction is already poisoned, so the enrichment SELECT itself throws `current transaction is aborted, commands ignored until end of transaction block` — preventing `ex-info` from being constructed and dropping the real cause entirely.

This PR extracts the local-id lookup into a `safe-local-id` helper that catches any throwable, logs it at debug, and returns `nil`. `path-error-data` keeps its shape (still includes `:local-id` when available), and — crucially — always returns a map so the calling `ex-info` always chains the original `e` as the cause. Support engineers and logs will now see the real SQL error rather than the aborted-tx symptom.

No change to non-error paths.

### How to verify

Unit test added in `enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj`: `load-error-preserves-original-cause-when-find-local-throws-test`.

It reproduces the bug by stubbing:

- `serdes/load-update!` to throw a known `original-cause` for Card (mimicking the real load failure).
- `serdes/load-find-local` to throw `current transaction is aborted` once the fake poisoning flag is set (mimicking the aborted-tx behavior on the next query).

It asserts that `load-metabase!` throws with:
- Outer message matching `"Failed to load into database"` (i.e. our wrapper was constructed).
- `ex-cause` **`identical?`** to `original-cause` (the real cause is still chained).
- `:local-id` is `nil` in `ex-data` (graceful degradation).

Verification runs:

```
./bin/test-agent :only '[metabase-enterprise.serialization.v2.load-test/load-error-preserves-original-cause-when-find-local-throws-test]'
# With the fix: 3 assertions, 0 failures, 0 errors.

# Temporarily reverted load.clj (test only):
# 3 assertions, 2 failures, 0 errors. Fails on the outer message and cause-chaining
# assertions exactly as expected, confirming the test exercises the bug.

./bin/test-agent :only '[metabase-enterprise.serialization.v2.load-test/tx-test metabase-enterprise.serialization.v2.load-test/circular-links-test metabase-enterprise.serialization.v2.load-test/load-error-preserves-original-cause-when-find-local-throws-test]'
# 16 assertions, 0 failures, 0 errors.
```

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 1]
```diff
@@ -63,11 +63,25 @@
...
+
+  [[path-error-data]] is called from catch blocks inside the outer load transaction. When the original
+  failure was a SQL error it will have poisoned the transaction, so any subsequent query (including
+  [[serdes/load-find-local]]) will throw `current transaction is aborted, commands ignored until end of
+  transaction block` and shadow the real cause. We prefer losing `:local-id` over losing the exception chain."
+  [path]
+  (try
+    (when-let [entity (serdes/load-find-local path)]
+      ((t2/select-pks-fn entity) entity))
+    (catch Throwable e
```
Comment (edpaget) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj]:
```suggestion
    (catch Exception e
```

File: enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj [hunk 2]
```diff
@@ -1524,6 +1524,44 @@
             (is (= (str "qwe_" (:name coll))
                    (t2/select-one-fn :name :model/Collection :id (:id coll))))))))))
 
+(deftest load-error-preserves-original-cause-when-find-local-throws-test
+  (testing "When the load transaction is poisoned and load-find-local throws while building error data,
+            the original exception is still preserved as the cause (not shadowed by the aborted-tx error)"
+    (mt/with-empty-h2-app-db!
```
Comment (edpaget) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj]: I don't _think_ this is necessary and it will make the test very slow.

**Review by edpaget — APPROVED** [review]

**Review by edpaget — APPROVED** [review]
