### PR TITLE
Fix `query->database-and-table-ids` for `source-query`

### LINKED ISSUE #11496: Cannot click on some of "Saved Questions" in my personnal collection, that sometime disappear
## Describe the bug
I want to create a nested query (thus, based on one already existing query). In the editor, when asking a Custom Question, I browse to "Saved Questions- Étienne Boisseau-Sierra's Personal Collection".

The question I want to start building on is called _"Total Lines by Depot_lean"_

* _Issue number 1:_ **Some questions saved in the collection _intermittently_ do not appear in the list** (at the beginning of the recording below — the question was listed a few moments earlier). Note that the same happens for the personnal collections themselves: some users (me — i.e., the current user) are sometimes not listed when selecting _Data/Saved Questions_.
* _Issue number 2:_ When the question does finally appear in the list, **I cannot click on it**.

## **Logs**
Logs do not show a lot (in the recording below, I'm showing the logs in real time).

## **Screen recording**
Peek 2019-12-11 10-55_redacted

1. I show the log, and enter a few blank lines to remember where we started
2. The question  _"Total Lines by Depot_lean"_ is missing in the list (it appeared before, and is not concurrently being modified).
3. I refresh the page, and now I can see the question listed, however…
4. … I can't click on it (or when I do, nothing happen — unlike for _"Lines 1_lean"_ or _"Lines 2_lean"_ )

## **To Reproduce**
That's the hard bit: it's intermittently, so I haven't found what is the common factor among the questions/collections behaving weirdly.

## **Expected behavior**
All items appear all the time (issue 1), and I can click on each of them (issue 2).

## **Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "5.1.16-300.fc30.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

## **Severity**
Blocking some users in their usage of Metabase (i.e. they cannot ask the questions they want — where these question require a join of two previously created questions).

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #11496

`query->database-and-table-ids` didn't handle `source-query`.

Unfortunately this won't fix the issue for existing cards, only newly saved cards.

Not sure the best place to put a test for this? `test/metabase/models/query_test.clj` doesn't exist yet, should it go there?

### CODE REVIEW

**Review by camsaul — CHANGES_REQUESTED** [review]
We should add a test for this. I'll add one

**Review by camsaul — APPROVED** [review]
Ok, I added some tests for this function. Think we can go ahead and merge it once they pass CI

File: src/metabase/models/query.clj [hunk 1]
```diff
@@ -78,21 +78,20 @@
               ;; rethrow e if updating an existing average execution time failed
               (throw e))))))
 
-;; TODO - somewhat confusing that the Ad-hoc queries here use the keys `:table-id` and `:database-id` instead of the
-;; `:database_id` and `:table_id` that come out of the Database. In the automagic dashboards code, for example, we
-;; have special utility functions to account for both possiblities. Should we fix this?
```
Comment (camsaul) [inline src/metabase/models/query.clj]: removed this comment since it's not really applicable anymore now that we normalize queries when as fetch them from the DB
