### PR TITLE
[Mongo] Convert bson Decimal128 negative zero to BigInteger zero

### LINKED ISSUE #44506: Issue processing Mongo BigDecimal when values are less than 0
### Describe the bug

I'm working on a collection that contains several BigDecimal columns. Occasionally, there are negative values, for example -0.02. This results in a the following error:  :error "Negative zero can not be converted to a BigDecimal". The error occurs during the initial table analysis, as well as attempting to visualize the data.

### To Reproduce

Load the following records into a mongodb collection:
{"_id":{"$oid":"765f669ee10537b1f9251821"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.72"},"day":{"percentage":{"$numberDecimal":"-0.01"}},"evening":{"percentage":{"$numberDecimal":"0.02"}},"night":{"percentage":{"$numberDecimal":"1.87"}},"blocked":{"percentage":{"$numberDecimal":"1.33"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}
{"_id":{"$oid":"765f669ee10537b1f9251822"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.63"},"day":{"percentage":{"$numberDecimal":"0.03"}},"evening":{"percentage":{"$numberDecimal":"0.0"}},"night":{"percentage":{"$numberDecimal":"2.66"}},"blocked":{"percentage":{"$numberDecimal":"1.04"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}
{"_id":{"$oid":"765f669ee10537b1f9251823"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.44"},"day":{"percentage":{"$numberDecimal":"-0.12"}},"evening":{"percentage":{"$numberDecimal":"0.09"}},"night":{"percentage":{"$numberDecimal":"2.87"}},"blocked":{"percentage":{"$numberDecimal":"1.25"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}
{"_id":{"$oid":"765f669ee10537b0b2b4b061"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.51"},"day":{"percentage":{"$numberDecimal":"-0.07"}},"evening":{"percentage":{"$numberDecimal":"-0.03"}},"night":{"percentage":{"$numberDecimal":"2.09"}},"blocked":{"percentage":{"$numberDecimal":"1.21"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}
{"_id":{"$oid":"765f669ee10537b0b2b4b062"},"recType":"driver","status":"active","rate":{"rateType":"driver","basePerMinRate":{"$numberDecimal":"0.61"},"day":{"percentage":{"$numberDecimal":"0.01"}},"evening":{"percentage":{"$numberDecimal":"0.09"}},"night":{"percentage":{"$numberDecimal":"1.75"}},"blocked":{"percentage":{"$numberDecimal":"1.03"}}},"audit":{"createdTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedTS":{"$date":"2024-05-13T00:00:00.000Z"},"updatedBy":{"$oid":"4461766566467265656d616e"}}}

Attempt to create the metadata and you will see the error

### Expected behavior

The system should be able to use a BigDecimal value of -0.02 for example.

### Logs

.41baa84f-a01f-4586-ac50-d00ca1b24dc1] 2024-06-20T16:08:34-04:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Negative zero can not be converted to a BigDecimal
{:database_id 2,
 :started_at #t "2024-06-20T16:08:33.877420-04:00[America/New_York]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error reducing result rows: Negative zero can not be converted to a BigDecimal",
   :stacktrace
   ["--> query_processor.pipeline$_STAR_reduce_STAR_$fn__56619.invoke(pipeline.clj:65)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:62)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:49)"
    "query_processor.pipeline$_STAR_run_STAR_$respond__56626.invoke(pipeline.clj:86)"
    "driver.mongo.execute$reduce_results.invokeStatic(execute.clj:177)"
    "driver.mongo.execute$reduce_results.invoke(execute.clj:171)"
    "driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:207)"
    "driver.mongo.execute$execute_reducible_query.invoke(execute.clj:182)"
    "driver.mongo$fn__118236$f__114486__auto____118237.invoke(mongo.clj:314)"
    "driver.mongo.connection$do_with_mongo_client$fn__114477.invoke(connection.clj:94)"
    "util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165)"
    "util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154)"
    "driver.mongo.connection$do_with_mongo_client.invokeStatic(connection.clj:89)"
    "driver.mongo.connection$do_with_mongo_client.invoke(connection.clj:85)"
    "driver.mongo$fn__118236.invokeStatic(mongo.clj:313)"
    "driver.mongo$fn__118236.invoke(mongo.clj:310)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:88)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:81)"
    "query_processor.execute$run.invokeStatic(execute.clj:60)"
    "query_processor.execute$run.invoke(execute.clj:54)"
    

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "22.0.1",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "22.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "22.0.1",
    "os.name": "Mac OS X",
    "os.version": "14.5",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking my usage of Metabase entirely

### Additional context

If you remove the negative sign from the sample data I provided, metabase will work fine.

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes #44506

### Description

~~This PR _has a potential_ to fix the issue. It is not clear from the issue, if results returned from Mongo contain negative zero. Though it seems very likely as the exception mentioned in the issue is almost certainly thrown during the `.bigDecimalValue` conversion of `from-document`.~~

~~I've considered also possibility of digits getting lost _somewhere_ on the application side. I find that unlikely as all `from-document` calls occur right on the results returned from dbms.~~

This PR adds negative zero handling to `from-document` conversion function.

### How to verify

Run the newly added test.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo/conversion.clj [hunk 1]
```diff
@@ -37,7 +38,12 @@
 
   org.bson.types.Decimal128
   (from-document [^org.bson.types.Decimal128 input _opts]
-    (.bigDecimalValue input))
+    (try (.bigDecimalValue input)
+         ;; Convert negative and positive zero to 0M
+         (catch ArithmeticException e
+           (if (str/includes? (ex-message e) "zero can not be converted to a BigDecimal")
+             0M
+             (throw e)))))
```
Comment (bshepherdson) [inline modules/drivers/mongo/src/metabase/driver/mongo/conversion.clj:46]: I'm really dismayed to see us pattern matching on an error message in production code.

- Can we call something on the `input` to check for this case?
- Is there any more structured information on the exception? Is it a custom subclass, or a straight `ArithmeticException`? Does it include a more specific `.cause` from the BSON library?

**Review by bshepherdson — CHANGES_REQUESTED** [review]

File: modules/drivers/mongo/src/metabase/driver/mongo/conversion.clj (hunk 1 above)
Comment (lbrdnk) [reply modules/drivers/mongo/src/metabase/driver/mongo/conversion.clj]: I've removed exception handling in favor of `.equals`.

> Can we call something on the input to check for this case?

I'll keep in mind to examine different ways of value checks than exception handling first.

> Is there any more structured information on the exception?

It was `ArithmeticException` as follows:
```
#error {
 :cause "Negative zero can not be converted to a BigDecimal"
 :via
 [{:type java.lang.ArithmeticException
   :message "Negative zero can not be converted to a BigDecimal"
   :at [org.bson.types.Decimal128 bigDecimalValue "Decimal128.java" 297]}]
 :trace
...
```

**Review by bshepherdson — APPROVED** [review]
