### PR TITLE
Properly Display Remapped Categories in Bulk Filter Modal

### LINKED ISSUE #24626: New filter modal is showing custom mapped values next to their original values
**Describe the bug**
In the new filter modal, with columns that have custom mapping in the data model, they are showing their original data value + de custom mapped value.

**To Reproduce**
1. Go to 'datamodel
2. Put custom keymapping on a column
3. Open the table and the filter modal

**Expected behavior**
You should see duplicate values (original value and the custom mapped)

**Screenshots**
image
image

**Information about your Metabase Installation:**
I'm running the latest 0.44 version.
{
  "browser-info": {
    "language": "nl-NL",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Windows 11",
    "os.version": "10.0",
    "user.language": "nl",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-04",
      "tag": "v0.44.0",
      "branch": "release-x.44.x",
      "hash": "d3700f5"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}

### PR DESCRIPTION
**Pull request by iethree**
## Before

The bulk filter modal was flattening all filter options, which caused it to display both actual filter values as well as remapped display values.

Screen Shot 2022-08-09 at 10 45 30 AM

## Changes

- Respect remapped values and display properly in the `SimpleCategoryFilterPicker`
- Add unit tests for remapped display values

Resolves https://github.com/metabase/metabase/issues/24626

## After

Remapped values display properly, and apply the correct internal values as well.

Screen Shot 2022-08-09 at 10 43 29 AM

## Testing Steps

- follow the repro steps [here](https://github.com/metabase/metabase/issues/24626#issuecomment-1209256656) to remap the rating field on the reviews table
- refresh your browser
- open a bulk filter modal on the reviews table, you should see the remapped values only
- applying a filter on the remapped values works properly

(note, the filter tag widgets do not pull in the remapped values, this is a pre-existing issue unrelated to the filter modal)
Screen Shot 2022-08-09 at 10 43 40 AM

### CODE REVIEW

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/SimpleCategoryFilterPicker.tsx [hunk 1]
```diff
@@ -31,20 +36,21 @@ export function SimpleCategoryFilterPicker({
   };
 
   const hasShortOptions = !options.find(
-    option => String(option).length > LONG_OPTION_LENGTH,
+    ([value, displayValue]) =>
```
Comment (WiNloSt) [inline frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/SimpleCategoryFilterPicker.tsx:39]: I know the PR is merged but I noticed the variable name doesn't match the one on line 48. `value` vs `option` when both are destructured from the same `options`.
