### PR TITLE
Closes EMB-853 renamed legends get ignored by content translation (followup)

### LINKED ISSUE #63972: Renamed legends get ignored by Content Translation
### Describe the bug

https://github.com/user-attachments/assets/9792e0b3-260e-495b-b281-9670a429d635

Renamed legends get ignored by Content Translation 

### To Reproduce

1. Go to New Dashboard -> Add a new Question -> Products -> Count Group by Category -> Visualize as Pie ->  Rename the Widget legend to Price -> Save

Image

2. Upload the following translations [metabase-content-translations.csv](https://github.com/user-attachments/files/22516224/metabase-content-translations.csv)

3.Embed with locale=es and notice how your renaming gets ignored, what makes it more weird is that in this case it seems Widget is still being used cause it translated `Widget` not `Price`

Image

### Expected behavior

The translations should be based on what you see in the UI this is the same bug as this one but instead of columns I am renaming legends:

https://github.com/metabase/metabase/issues/63296

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.56
```

### Severity

A feature which we released and is partially broken

### Additional context

There has been an ongoing of bugs around Content Translation and customers still face issues:

https://github.com/metabase/metabase/issues?q=is%3Aissue%20content%20translation%20label%3APriority%3AP1

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #63972
Closes [EMB-853: Renamed legends get ignored by Content Translation](https://linear.app/metabase/issue/EMB-853/renamed-legends-get-ignored-by-content-translation)

### Description

Followup to #64023, although not related to pie charts but rather to cartesian charts.

In the following screenshots, one column has been renamed to "title" which is translated in the dictionnary I uploaded. This PR makes it so the custom name is picked up to be translated properly.

Before
SCR-20251014-nskz

After
SCR-20251014-nshw

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts [hunk 1]
```diff
@@ -164,11 +169,29 @@ export const translateFieldValuesInSeries = (
...
-      .otherwise(() => {
+      .with(P.when(isCartesianChart), () => {
+        // cartesian charts have series settings that can provide display names
+        // for fields, which we should translate if available
+        const seriesSettings =
+          singleSeries.card.visualization_settings?.series_settings;
+
+        if (!seriesSettings) {
+          return defaultFn();
+        }
```
Comment (WiNloSt) [inline enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts]: we could remove this special condition if we default `seriesSettings` to an empty object, which I think is more preferable since we also did the same for pie charts (`pieRows`).

**Review by WiNloSt — APPROVED** [review]
