### PR TITLE
Fix `add-alias-info` matching for nominal field literal refs

### LINKED ISSUE #41325: `add-alias-info` gets confused when using multiple nominal field literal refs for same column in source query
With a query like

```clj
(lib.tu.macros/mbql-query orders
  {:source-query {:source-table $$orders
                  :fields [!year.created-at
                           !month.created-at
                           $total]}
   :aggregation [[:cum-sum [:field "TOTAL" {:base-type :type/Integer}]]]
   :breakout    [[:field "CREATED_AT" {:base-type :type/Date, :temporal-unit :default}]
                 [:field "CREATED_AT_2" {:base-type :type/Date, :temporal-unit :default}]]})
```

it actually adds info like this

```clj
[[:asc [:field "CREATED_AT" {:base-type :type/Date
                             :temporal-unit :default
                             ::add/source-table ::add/source
                             ::add/source-alias "CREATED_AT"
                             ::add/desired-alias "CREATED_AT"
                             ::add/position 0}]]
 [:asc [:field "CREATED_AT_2" {:base-type :type/Date
                               :temporal-unit :default
                               ::add/source-table ::add/source
                               ::add/source-alias "CREATED_AT" ; <= WRONG
                               ::add/desired-alias "CREATED_AT_2"
                               ::add/position 1}]]]
```

which results in us generating incorrect queries like

```sql
SELECT 
  source.CREATED_AT AS CREATED_AT, 
  source.CREATED_AT AS CREATED_AT_2 -- wrong, should have been source.CREATED_AT_2
FROM (
  ...) AS source
  ```  

I'm not 100% sure whether this is affecting people in the wild since we tend to use Field ID refs, but it's definitely a bug and incorrect behavior we should fix either way.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #41325

I actually ran into this bug while working on some of the window function stuff, I fixed it pretty quickly tho so that's good.

### CODE REVIEW

File: src/metabase/query_processor/util/add_alias_info.clj [hunk 1]
```diff
@@ -235,32 +235,38 @@
...
-              ;; Expressions whose ::desired-alias matches the name we're searching for.
-              (m/find-first (fn [[_expression _expression-name {::keys [desired-alias]} :as _expression-clause]]
-                              (= desired-alias field-name))
-                            (filter (partial mbql.u/is-clause? :expression) all-exports))
-              (m/find-first (fn [[_ _ opts :as _aggregation-options-clause]]
-                              (= (::source-alias opts) field-name))
-                            (filter (partial mbql.u/is-clause? :aggregation-options) all-exports))))
-        ;; look for a field referenced by the name in source-metadata
-        (let [field-name (second field-clause)]
-          (when (string? field-name)
```
Comment (camsaul) [inline src/metabase/query_processor/util/add_alias_info.clj:255]: The "if this is a string field name" stuff here was duplicated with the  "if this is a string field name" stuff directly above so I combined it into one section, so this party is really just whitespace changes

File: src/metabase/query_processor/util/add_alias_info.clj [hunk 2]
```diff
@@ -235,32 +235,38 @@
...
         (when-let [field-name (let [[_ id-or-name] field-clause]
                                 (when (string? id-or-name)
                                   id-or-name))]
-          (or ;; Expressions by exact name.
+          (or ;; First, look for Expressions or fields from the source query stage whose `::desired-alias` matches the
+              ;; name we're searching for.
+              (m/find-first (fn [[tag _id-or-name {::keys [desired-alias], :as _opts} :as _ref]]
+                              (when (#{:expression :field} tag)
+                                (= desired-alias field-name)))
+                            all-exports)
```
Comment (camsaul) [inline src/metabase/query_processor/util/add_alias_info.clj:247]: This is the actual fix, it should have looked at both Field and expression refs for a matching `::desired-alias`, not just expression refs.

**Review by lbrdnk — COMMENTED** [review]
LGTM.

**Review by lbrdnk — APPROVED** [review]
