### PR TITLE
Delete the abandonment email task

### LINKED ISSUE #29006: Abandonment email trigger error in logs
In [Generalize product-triggered survey emails](https://github.com/metabase/metabase/pull/27348#top) I removed the SendAbandomentEmails task definition but didn't delete the triggers from the app db. This means for metabase versions <=45 upgrading to 46 and above, the job is still scheduled but the job doesn't find the appropriate code. Every day, an error appears in the logs.

Here's an example error in the logs:

```
2023-03-03 18:28:03,157 ERROR jdbcjobstore.JobStoreTX :: MisfireHandler: Error handling misfires: Couldn't store trigger 'DEFAULT.metabase.task.abandonment-emails.trigger' for 'DEFAULT.metabase.task.abandonment-emails.job' job:Couldn't retrieve job because a required class was not found: metabase.task.follow_up_emails.AbandonmentEmail
org.quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.metabase.task.abandonment-emails.trigger' for 'DEFAULT.metabase.task.abandonment-emails.job' job:Couldn't retrieve job because a required class was not found: metabase.task.follow_up_emails.AbandonmentEmail [See nested exception: org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: metabase.task.follow_up_emails.AbandonmentEmail [See nested exception: java.lang.ClassNotFoundException: metabase.task.follow_up_emails.AbandonmentEmail]]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1228)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1042)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:991)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3264)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: metabase.task.follow_up_emails.AbandonmentEmail [See nested exception: java.lang.ClassNotFoundException: metabase.task.follow_up_emails.AbandonmentEmail]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1393)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1210)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: metabase.task.follow_up_emails.AbandonmentEmail
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at metabase.task$load_class.invokeStatic(task.clj:118)
        at metabase.task$load_class.invoke(task.clj:117)
        at metabase.task.ClassLoadHelper.loadClass(task.clj:128)
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:852)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1390)
        ... 6 more
```

Metabase version: 45

### PR DESCRIPTION
**Pull request by calherries**
Resolves [Abandonment email error in logs](https://github.com/metabase/metabase/issues/29006#top)

This PR deletes the abandonment email task from the quartzite tables. It's implemented as a clojure migration.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28998)

### CODE REVIEW

File: .clj-kondo/config.edn [hunk 1]
```diff
@@ -442,7 +442,7 @@
   metabase.api.search-test/do-test-users                                               clojure.core/let
   metabase.async.api-response-test/with-response                                       clojure.core/let
   metabase.dashboard-subscription-test/with-dashboard-sub-for-card                     clojure.core/let
-  metabase.db.custom-migrations/defmigration                                           clj-kondo.lint-as/def-catch-all
+  metabase.db.custom-migrations/define-migration                                       clj-kondo.lint-as/def-catch-all
```
Comment (calherries) [inline .clj-kondo/config.edn:445]: I also renamed this to make it more consistent with `define-reversible-migration`, and the convention that macros be named `define-...`

File: src/metabase/task.clj [hunk 2]
```diff
@@ -140,7 +139,7 @@
   connection properties ahead of time, we'll need to set these at runtime rather than Setting them in the
   `quartz.properties` file.)"
   []
-  (when (= (mdb/db-type) :postgres)
+  (when (= (mdb.connection/db-type) :postgres)
```
Comment (calherries) [inline src/metabase/task.clj:142]: This was needed to avoid cyclic dependencies. `mdb` just imports the var from `mdb.connection` for convenience anyway

File: resources/migrations/000_migrations.yaml [hunk 3]
```diff
@@ -14300,6 +14300,15 @@ databaseChangeLog:
             constraintName: fk_action_model_id
             onDelete: CASCADE
 
+  - changeSet:
+      id: v46.00-086
```
Comment (calherries) [inline resources/migrations/000_migrations.yaml:14304]: If this doesn't make it into 46, then I can change it to 47

File: .clj-kondo/config.edn (hunk 1 above)
Comment (qnkhuat) [reply .clj-kondo/config.edn:445]: Where does that convention come from?

File: src/metabase/db/custom_migrations.clj [hunk 4]
```diff
@@ -43,9 +46,9 @@
   [n]
   (log/info "No rollback for: " n))
 
-(defmacro defmigration
-  "Define a custom migration."
-  [name migration-body]
+(defmacro define-migration
+  "Define a custom migration without a reverse migration."
+  [name & migration-body]
   `(define-reversible-migration ~name ~migration-body (no-op ~(str name))))
```
Comment (qnkhuat) [inline src/metabase/db/custom_migrations.clj:52]:
```suggestion
  `(define-reversible-migration ~name (do ~@migration-body) (no-op ~(str name))))
```

**Review by qnkhuat — CHANGES_REQUESTED** [review]
Is this ready to review?...

- it's failed to start metabase with a null pointer error, I think it's because the macro `define-migration` is expanding without a `do` wrapped.
- why can't we do this with a liquibase migration, can't we delete it from `qrtz_job_details` tables`?
- Also I see no tests

File: .clj-kondo/config.edn (hunk 1 above)
Comment (calherries) [reply .clj-kondo/config.edn:445]: I'm not sure where it comes from, I've just seen a tendency to prefer `define-multiple-word-macro` over `defmultiple-word-macro`. `defmigration` is fine because it's one word. But if we want the two names to be consistent, instead of renaming `define-reversible-migration` to `defreversible-migration`, we should rename `defmigration` to `define-migration`.

File: src/metabase/db/custom_migrations.clj (hunk 4 above)
Comment (calherries) [reply src/metabase/db/custom_migrations.clj:52]: Fixed

**Comment by calherries** [comment]
> why can't we do this with a liquibase migration, can't we delete it from qrtz_job_details tables`?
We need the clojure migration because otherwise, we'd need to copy the logic for deleting the quartzite jobs + trigger from all the relevant tables. The storage and deletion of jobs + triggers is an implementation detail of quartzite, so replicating it in a migration would be fragile to changes in the implementation. It's safer to just call quartzite's `delete-trigger` and `delete-job` functions and let the library handle the rest.

> Also I see no tests
Fair. It's pretty tricky to add useful tests to this though. I could at least create a trigger + job, migrate, and check the trigger and job isn't present.

**Comment by calherries** [comment]
@qnkhuat I added a test. Can you re-review?

File: src/metabase/db/custom_migrations.clj [hunk 5]
```diff
@@ -91,3 +94,9 @@
   (t2.execute/query-one {:delete-from :permissions
                          :where [:or [:like :object (h2x/literal "/data/db/%")]
                                  [:like :object (h2x/literal "/query/db/%")]]}))
+
+(define-migration DeleteAbandonmentEmailTask
+  (task/start-scheduler!)
+  (task/delete-task! (jobs/key "metabase.task.abandonment-emails.job")
+                     (triggers/key "metabase.task.abandonment-emails.trigger"))
+  (task/stop-scheduler!))
```
Comment (qnkhuat) [inline src/metabase/db/custom_migrations.clj:102]: just to be "extra sure" should we put this into a try catch and run `stop-scheduler` in finally?

Comment (qnkhuat) [reply src/metabase/db/custom_migrations.clj]: hmm, I'm worried about this. Even though we know now that `start-scheduler!` is idempotent, but we should keep these custom migrations side-effect free.

In fact we would like to keep custom migrations to use as less as possible code from other ns because those functions could change over time.

See [this](https://metaboat.slack.com/archives/CKZEMT1MJ/p1675921528936249?thread_ts=1675892968.988579&cid=CKZEMT1MJ) from Cam

Comment (calherries) [reply src/metabase/db/custom_migrations.clj]: Fair concerns, I will copy the relevant code from the task namespace into this namespace for extra stability, and create a separate scheduler to the one used by the app. That way we can start and stop the scheduler in the repl without side-effects.

File: test/metabase/db/custom_migrations_test.clj [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+(set! *warn-on-reflection* true)
+
+(use-fixtures :once (fixtures/initialize :db))
+
+(jobs/defjob AbandonmentEmail [_] :default)
+
+(deftest delete-abandonment-email-task-test
+  (testing "Migration v46.00-086: Delete the abandonment email task"
+    (impl/test-migrations ["v46.00-086"] [migrate!]
+      (try (do (task/start-scheduler!)
```
Comment (qnkhuat) [inline test/metabase/db/custom_migrations_test.clj:22]:
```suggestion
      (try 
        (do 
          (task/start-scheduler!)
```

**Review by qnkhuat — APPROVED** [review]
Moving needed functions to the custom-migration ns does make me feel safer.

Also, could you add to the docstring of that ns a warning so people are aware that we shouldn't use functions from the source?

**Comment by qnkhuat** [comment]
For sanity, I tested running 45 to have the abandonment task running, then run this branch. Everything works fine.
