### PR TITLE
Field filter: treat :type/Name as STRING instead of NUMBER

### LINKED ISSUE #21973: Max/Min functions on strings incorrectly inferred as numeric
**Describe the bug**
When using Max/Min on string-based columns, then the frontend infers as numeric field, which limits filter options.
Possibly applies to other functions, didn't go through everything.

**To Reproduce**
1. Question > Sample > People
2. Summarize Maximum of ID, Name, Latitude and CreatedAt, grouped by Source
image
3. Filtering by "Max of Name" is not possible, because it's inferred as a number by the frontend even though dataset returns as type/Text.
image

**Possible workaround**
- Add a Custom Column `trim([Max of Name])` after the aggregation
image
image
- Or create a SQL question, which can then be used as a Model or Saved Question as the base for other questions, which adds filtering.

**Expected behavior**
Generally use the inferred type from dataset

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.43.0-rc1

**Additional context**
History #18207 and #4482

### PR DESCRIPTION
**Pull request by ariya**
To verify:
1. New, Question, Sample Database, People
2. Summarize, Maximum of Name, group by Source
3. Filter, choose Max of Name

### Before this PR

The field to filter is incorrectly treated as a number:

image

### After this PR

The field to filter is correctly treated as a string:

image

### CODE REVIEW

File: frontend/src/metabase/lib/schema_metadata.js [hunk 1]
```diff
@@ -137,9 +137,9 @@ export function getFieldType(field) {
     COORDINATE,
     FOREIGN_KEY,
     PRIMARY_KEY,
-    NUMBER,
     STRING,
     STRING_LIKE,
+    NUMBER,
```
Comment (ariya) [inline frontend/src/metabase/lib/schema_metadata.js:142]: This is the real fix, since the earlier types should be the specific ones first (hence, matching `:type/Name` as `STRING`).

File: frontend/test/metabase/scenarios/question/notebook.cy.spec.js [hunk 2]
```diff
@@ -394,6 +394,31 @@ describe("scenarios > question > notebook", () => {
...
+
+    cy.get(".Icon-filter").click();
+    popover().within(() => {
+      cy.findByText("Max of Name").click();
+    });
+
+    cy.findByText("Is").click();
+    cy.findByText("Starts with").click();
+
+    cy.findByText("Case sensitive").click();
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/question/notebook.cy.spec.js:419]: The whole test can be simplified and made faster two times by using the API to set things up.
```js
const questionDetails = {
  name: "21973",
  query: {
    "source-table": PEOPLE_ID,
    aggregation: [["max", ["field", PEOPLE.NAME, null]]],
    breakout: [["field", PEOPLE.SOURCE, null]],
  },
  display: "table",
};

cy.createQuestion(questionDetails, { visitQuestion: true });

cy.findByText("Filter").click();
cy.findByTestId("sidebar-right").within(() => {
  cy.findByText("Max of Name").click();

  cy.findByText("Is").click();
});

cy.findByText("Starts with").click();

cy.findByText("Case sensitive").click();
```

Comment (ariya) [reply frontend/test/metabase/scenarios/question/notebook.cy.spec.js]: Excellent suggestion, thanks. I've adopted that improvement.

**Review by flamber — COMMENTED** [review]
Tested `4146caf`

This seems to depend on some silly semantic_type thing - on Products
image

With a SQL question:
image

And I'm missing some columns too - we really need to stop being so restrictive. I would rather show too many options, where some may fail, than not showing all the options, which makes it impossible to use QB/nested fully. Almost feels like 13186, which is already fixed on master.
image

**Comment by ariya** [comment]
> This seems to depend on some silly semantic_type thing - on Products

That's because Vendor is of the `type/Category` and it's not handled properly yet. Filed as #22154.

> And I'm missing some columns too - we really need to stop being so restrictive. 

Again, similar issue with the type system and metadata (like the old #4482). This one is now tracked as #22155.

**Review by daltojohnso — APPROVED** [review]
