### PR TITLE
Fix applying default values for a pinned sql question

### LINKED ISSUE #37831: Default values are not respected for pinned questions in collections in v48
### Describe the bug

When you add default values to the filters (normal or field filters) on a native questions, those are not taken into account in v48

### To Reproduce

1) new question -> select * from people where {{something}}
2) something is a field filter mapped to the state field, it's of type "location is"
3) add a default value, like NY
4) select a state, run the question, it will run
5) now remove the state from the filter (not from the default value). Run the question, see it failing

### Expected behavior

It should run with the default filter

### Logs

NA

### Information about your Metabase installation

```JSON
v48.x
```

### Severity

P2

### Additional context

Pretty sure this worked in v47

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/37831

### Description

For an SQL question, which is pinned to the collection, we need to run query applying the default parameters values.
To achieve this we pass an empty array as a value for `parameters` in `/api/card/:id/query` POST request

### How to verify
follow steps from e2e test or

- create a new sql question with parameter e.g. `select count(*) from people where {{date}}`
- add a filter mapping (field filter type) to the people -> birth date
- select a default value (e.g. `1999-02-26~2024-02-26`)
- save a question and put it to the root collection
- pin this question (it should appear on the top of collection) - make sure the filter is applied

### Demo

https://github.com/metabase/metabase/assets/125459446/1238b880-7571-4e0e-83f9-a7cf50bd4c39

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase-lib/parameters/utils/parameter-values.js [hunk 1]
```diff
@@ -32,7 +32,12 @@ export function getValuePopulatedParameters({
   parameters,
   values = {},
   defaultRequired = false,
+  collectionPreview = false,
 }) {
+  if (collectionPreview) {
+    return [];
+  }
```
Comment (oleggromov) [inline frontend/src/metabase-lib/parameters/utils/parameter-values.js:39]: It makes me suspicious that we exclude all parameters, but as I am reasoning through:

1. no filters are set — no parameters have values
2. default values should be populated on the backend
3. required parameters/variables can't exist without a default so 2 applies here

In case the logic above is correct, all e2e tests must pass. Otherwise something _might_ fail.

Comment (uladzimirdev) [reply frontend/src/metabase-lib/parameters/utils/parameter-values.js:39]: do you think we should have some comment explaining this?

Comment (oleggromov) [reply frontend/src/metabase-lib/parameters/utils/parameter-values.js:39]: Yeah I guess it won't do any harm.

**Review by oleggromov — APPROVED** [review]
