### PR TITLE
Fix - When DB is stuck in a Sync Loop, DB List in Native Editor Blinks Constantly 

### LINKED ISSUE #55951: When DB is stuck in a Sync Loop, DB List in Native Editor Blinks Constantly
### Describe the bug

If a database connection gets stuck in syncing status we keep making calls to the 'api/database' endpoint. For admin users, when they visit the native SQL editor, this also makes the list of available database connections constantly reload.

If it s a short list you can click on what you need. If it's a long list you need to get to the end of... it's a race you're probably not winning.

### To Reproduce

1. Force your database into a sync death loop
2. Open the network tab and see the calls to '/api/database' hitting on repeat
3. Go to native SQL editor and open the list of databases
4. It constantly refreshes (this only impacts admin users)

https://www.loom.com/share/e9632c0ff79d48d5852755c3782fc33d?sid=0692c6b5-221b-4fb8-a79a-0ddb159a4e10

### Expected behavior

You should be able to choose a DB from the menu in the SQL editor. We shouldn't call the '/api/database' endpoint on loop.

### Logs

2025-03-28 20:38:02,312 DEBUG middleware.log :: GET /api/database 200 10ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:02,954 DEBUG middleware.log :: GET /api/database 200 11ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:04,356 DEBUG middleware.log :: GET /api/database 200 11ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:05,005 DEBUG middleware.log :: GET /api/database 200 13ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:06,434 DEBUG middleware.log :: GET /api/database 200 23ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:07,051 DEBUG middleware.log :: GET /api/database 200 10ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:08,504 DEBUG middleware.log :: GET /api/database 200 13ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:09,098 DEBUG middleware.log :: GET /api/database 200 12ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:10,544 DEBUG middleware.log :: GET /api/database 200 11ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:11,161 DEBUG middleware.log :: GET /api/database 200 25ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:12,588 DEBUG middleware.log :: GET /api/database 200 14ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:13,211 DEBUG middleware.log :: GET /api/database 200 18ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:14,636 DEBUG middleware.log :: GET /api/database 200 25ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:15,260 DEBUG middleware.log :: GET /api/database 200 13ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:16,697 DEBUG middleware.log :: GET /api/database 200 14ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:17,306 DEBUG middleware.log :: GET /api/database 200 13ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:18,744 DEBUG middleware.log :: GET /api/database 200 9ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:19,352 DEBUG middleware.log :: GET /api/database 200 22ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:20,793 DEBUG middleware.log :: GET /api/database 200 11ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:21,399 DEBUG middleware.log :: GET /api/database 200 19ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:22,840 DEBUG middleware.log :: GET /api/database 200 12ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:23,439 DEBUG middleware.log :: GET /api/database 200 13ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:24,889 DEBUG middleware.log :: GET /api/database 200 17ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:25,469 DEBUG middleware.log :: GET /api/database 200 7ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:26,954 DEBUG middleware.log :: GET /api/database 200 24ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:27,503 DEBUG middleware.log :: GET /api/database 200 7ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:27,639 DEBUG middleware.log :: GET /api/health 200 0ms (0 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
2025-03-28 20:38:29,028 DEBUG middleware.log :: GET /api/database 200 16ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:29,539 DEBUG middleware.log :: GET /api/database 200 7ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:31,074 DEBUG middleware.log :: GET /api/database 200 24ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:31,628 DEBUG middleware.log :: GET /api/database 200 15ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:33,169 DEBUG middleware.log :: GET /api/database 200 8ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:33,676 DEBUG middleware.log :: GET /api/database 200 12ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:35,217 DEBUG middleware.log :: GET /api/database 200 13ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:35,734 DEBUG middleware.log :: GET /api/database 200 19ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:37,284 DEBUG middleware.log :: GET /api/database 200 43ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:37,778 DEBUG middleware.log :: GET /api/database 200 12ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:39,368 DEBUG middleware.log :: GET /api/database 200 11ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:39,819 DEBUG middleware.log :: GET /api/database 200 11ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:41,399 DEBUG middleware.log :: GET /api/database 200 6ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:41,875 DEBUG middleware.log :: GET /api/database 200 20ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:43,499 DEBUG middleware.log :: GET /api/database 200 40ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:43,922 DEBUG middleware.log :: GET /api/database 200 13ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:45,541 DEBUG middleware.log :: GET /api/database 200 17ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:45,977 DEBUG middleware.log :: GET /api/database 200 23ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:47,588 DEBUG middleware.log :: GET /api/database 200 11ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:48,035 DEBUG middleware.log :: GET /api/database 200 15ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:49,659 DEBUG middleware.log :: GET /api/database 200 47ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:50,068 DEBUG middleware.log :: GET /api/database 200 7ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:51,704 DEBUG middleware.log :: GET /api/database 200 9ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:52,121 DEBUG middleware.log :: GET /api/database 200 25ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:53,771 DEBUG middleware.log :: GET /api/database 200 9ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:54,153 DEBUG middleware.log :: GET /api/database 200 8ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:55,850 DEBUG middleware.log :: GET /api/database 200 42ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:56,228 DEBUG middleware.log :: GET /api/database 200 8ms (2 DB calls) App DB connections: 1/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:57,665 DEBUG middleware.log :: GET /api/health 200 0ms (0 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
2025-03-28 20:38:57,920 DEBUG middleware.log :: GET /api/database 200 39ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:58,289 DEBUG middleware.log :: GET /api/database 200 10ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2025-03-28 20:38:59,964 DEBUG middleware.log :: GET /api/database 200 9ms (2 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (1 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-03-25",
      "tag": "v1.53.8",
      "hash": "e1eecad"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

blocking some users / TBD

### Additional context

Customer facing this has an Athena connection stuck in this loop (still collecting context on this) and their admins can't build SQL questions. TBD: Whether or not removing the Athena connection until they can figure out the IAM permission issue that led to this is a viable option for them.

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #55951
Fixes [SEM-194](https://linear.app/metabase/issue/SEM-194/when-db-is-stuck-in-a-sync-loop-db-list-in-native-editor-blinks)

### Description

Apart from the fix, it also removes a bunch of dead code.

### How to verify

1. Make sure you have at least 1 non-sample database added
2. Apply this git patch to simulate database being synced:

<details>
<summary>Git patch</summary>

```diff
diff --git a/frontend/src/metabase/api/database.ts b/frontend/src/metabase/api/database.ts
index 3ecd751d6d..9f40758425 100644
--- a/frontend/src/metabase/api/database.ts
+++ b/frontend/src/metabase/api/database.ts
@@ -45,6 +45,12 @@ export const databaseApi = Api.injectEndpoints({
         params,
       }),
       providesTags: (response) => provideDatabaseListTags(response?.data ?? []),
+      transformResponse: (response) => {
+        return response.data.map((db) => ({
+          ...db,
+          initial_sync_status: "incomplete",
+        }));
+      },
     }),
     getDatabase: builder.query<Database, GetDatabaseRequest>({
       query: ({ id, ...params }) => ({

```
</details>

3. New > SQL Query
4. Open the database picker
5. List of databases in the picker should not flicker (loading state should be shown at most once)

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx [hunk 1]
```diff
@@ -161,7 +155,6 @@ export class UnconnectedDataSelector extends Component {
     useOnlyAvailableSchema: PropTypes.bool,
     isInitiallyOpen: PropTypes.bool,
     tableFilter: PropTypes.func,
-    hasTableSearch: PropTypes.bool,
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx:164]: `hasTableSearch` was always `false` (except in unit tests) so I removed it.
Other code removals in this PR are a consequence of this change.

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx [hunk 2]
```diff
@@ -441,9 +433,9 @@ export class UnconnectedDataSelector extends Component {
     }
   }
 
-  isSearchLoading = () => {
-    const { models, metrics, allLoading } = this.props;
-    return models == null || metrics == null || allLoading;
+  isLoading = () => {
+    const { models, metrics, loading } = this.props;
+    return models == null || metrics == null || loading;
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx:438]: This is the fix: changing `allLoading` to `loading`.

It partially reverts this change: https://github.com/metabase/metabase/pull/50535/files#r1862678786

The old Entity Framework bug @ranquild was referring to has since been fixed (see [here](https://github.com/metabase/metabase/pull/51341/files#diff-186f83b598be6be0b89457e8b1f55b33d316e14d798b13f7094b0ede4413c843R290)).

`loading` works as expected now (`allLoading` still does not).

image

Comment (ranquild) [reply frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx:438]: This is incorrect since `loading` indicates the status of the last loader. Here we need at least 2, e.g. both models & metrics. You could potentially replace the second loader, pass `limit: 0`, and use `available_models` instead.

**Review by ranquild — CHANGES_REQUESTED** [review]
Inline comment

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx (hunk 2 above)
Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx]: 25f61ef9cf2f015ad15470b91fffd16f7a7c7597

Comment (ranquild) [reply frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx]: @kamilmielnik you most likely don't need to add `rawData`, there should be `metadata` available

Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx]: db6919326922278103b5dc9e4070e337de2bea55

**Comment by paoliniluis** [comment]
@kamilmielnik I used the double-backport tag, is that fine?

**Review by romeovs — APPROVED** [review]
The fix works for me locally.

**Review by ranquild — APPROVED** [review]

**Comment by kamilmielnik** [comment]
> @kamilmielnik I used the double-backport tag, is that fine?

@paoliniluis it will be released in 53.10 :heavy_check_mark:
