### PR TITLE
fix native gridmap binning calculation

### LINKED ISSUE #49462: Grid map broken with native queries
### Describe the bug

Grid map works good with GUI queries. Selecting from a table, grouping latitude and longitude by 0.1 and counting the rows displays the grids well.
 Image

However, converting the same question to native, SQL renders the map unusable. Grids get turned into awkward stripes.

 Image

### To Reproduce

1. Create a GUI question, summarized by count, grouped by coordinates and select grid map as a viz type
2. Click on Convert this question to SQL
3. Select the same visualization settings
4. See the issue

### Expected behavior

Grid map works fine with native queries.

### Logs

_No response_

### Information about your Metabase installation

I am running the latest Metabase (0.51.1.2, self hosted).

### Severity

This renders the map unusable for any non-trivial analysis or a dashboard that requires more complex filtering

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alxnddr**
closes #49462
Closes [VIZ-203](https://linear.app/metabase/issue/VIZ-203/grid-map-broken-with-native-queries-when-binning-longlat-by-1)

### Description

Fixes native grid maps binning calculation when bin widths are less than 1. Latitude and longitude bin widths define dimensions of rectangles on grid map.

While MBQL queries columns include the actual bin widths in `column.binning_info.bin_width`, for native queries we have to compute bin widths from data. Due to limited precision of floating-point numbers the bin width was incorrectly calculated.

### How to verify

1. New question -> Sample Dataset -> People: Count group by Latitude[Bin every 0.1 degrees] and Longitude[Bin every 0.1 degrees]
2. Make it a grid map visualization
3. Open the notebook mode -> view sql -> convert this question to SQL
4. Try visualizing it as a grid map, set correct latitude and longitude columns
5. Ensure the bin rectangles are rendered correctly

### Demo

Before
Screenshot 2025-06-20 at 7 32 21 PM

After
Screenshot 2025-06-20 at 7 32 53 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/LeafletGridHeatMap.jsx [hunk 1]
```diff
@@ -68,7 +57,15 @@ export default class LeafletGridHeatMap extends LeafletMap {
       const totalSquares = Math.max(points.length, gridSquares.length);
 
       const latitudeValues = points.map((row) => row[latitudeIndex]);
-      const longitureValues = points.map((row) => row[longitudeIndex]);
+      const longitudeValues = points.map((row) => row[longitudeIndex]);
```
Comment (bpander) [inline frontend/src/metabase/visualizations/components/LeafletGridHeatMap.jsx:60]: Thanks for fixing that typo 🙏

**Review by bpander — APPROVED** [review]
✅ Was able to reproduce the issue on master and verified it's fixed on this branch. Also tested auto-binning, binning by 0.05deg, and by 1deg. All seemed to work as expected.

Only weirdness I found was I couldn't increase the row limit after converting to sql so it wasn't showing as many squares as the GUI version. I was able to work around it, but I had to re-add bins via the GUI. I'm assuming that's either unrelated (i.e. outside the scope of this bugfix) or just my own inexperience, but wanted to call it out just in case.

https://github.com/user-attachments/assets/6ea2a600-467d-47c1-b552-ad1ac3e66312

**Comment by alxnddr** [comment]
@bpander thanks for reviewing!

> Only weirdness I found was I couldn't increase the row limit after converting to sql so it wasn't showing as many squares as the GUI version. I was able to work around it, but I had to re-add bins via the GUI. I'm assuming that's either unrelated (i.e. outside the scope of this bugfix) or just my own inexperience, but wanted to call it out just in case.

This is happening because non-aggregated queries (including sql queries) have 2k row limit, while aggregated ones can return up to [10k rows](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_aggregated_query_row_limit) by default
