### PR TITLE
Fix loading locale in setup

### LINKED ISSUE #21403: Setup should automatically detect locale and translate the UI
**Describe the bug**
If you set the locale of your browser then you'll be shown the interface in english till you click on the language that you want. Amazingly enough we detect the locale, so I'm curious why we don't show the translated UI to the user.

**Logs**
No logs

**To Reproduce**
1) change the locale of your browser, let's say: Español (Argentina) - es-AR
2) check the language of your browser effectively by going to the console and doing a console.log(navigator.language)
3) spin up Metabase and see that it will show up in English (first issue)
4) click on "get started", you'll see that we detect the language! click on it so the interface gets translated

**Expected behavior**
Detect the locale and translate it automatically

**Screenshots**
image
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04
- Your databases: H2
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Cosmetic?

**Additional context**
NA

### LINKED ISSUE #21404: Some strings not being translated in setup page
**Describe the bug**
Setup page has many strings without translation like "First name", "Last name", "Email", "Company or team name", "Create a password", "Confirm your password"

**Logs**
None

**To Reproduce**
Change language to another one on setup and see the strings without translation

**Expected behavior**
Have the strings translated to its language

**Screenshots**
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04
- Your databases: H2
- Metabase version: 42.3
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Cosmetic?

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/21403
Fixes https://github.com/metabase/metabase/issues/21404

Changes:
- Adds types for setup state
- Reloads locale in setup when it changes
- Gracefully handles locale loading issues

How to test:
- Go to browser settings and make your preferred language not English
- Run a fresh Metabase instance
- Make sure that the initial page is translated to your browser language
- Go to the language selection step and change languages
- Make sure that all steps are translated when the language changes

Please note that some translations for setup are broken or missing in `.po` files.

### CODE REVIEW

File: frontend/src/metabase/entities/users/forms.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ import { PLUGIN_ADMIN_USER_FORM_FIELDS } from "metabase/plugins";
 import validate from "metabase/lib/validate";
 import FormGroupsWidget from "metabase/components/form/widgets/FormGroupsWidget";
 
-const NAME_FIELDS = [
+const getNameFields = () => [
```
Comment (ranquild) [inline frontend/src/metabase/entities/users/forms.js:10]: When used as constants, `ttag` is called once and strings do not change when locale changes

File: frontend/src/metabase/setup/actions.ts [hunk 2]
```diff
@@ -1,15 +1,23 @@
...
 export const setStep = createAction(SET_STEP);
 
 export const SET_LOCALE = "metabase/setup/SET_LOCALE";
-export const setLocale = createAction(SET_LOCALE);
+export const SET_LOCALE_LOADED = "metabase/setup/SET_LOCALE_LOADED";
+export const setLocale = createThunkAction(
+  SET_LOCALE_LOADED,
+  (locale: Locale) => async (dispatch: any) => {
+    dispatch.action(SET_LOCALE, locale);
+    await loadLocalization(locale.code);
```
Comment (ranquild) [inline frontend/src/metabase/setup/actions.ts:18]: That's the most important part.

File: frontend/src/metabase/setup/components/WelcomePage/WelcomePage.tsx [hunk 3]
```diff
@@ -11,26 +12,34 @@ import {
...
   onStepSubmit,
-}: WelcomePageProps): JSX.Element => {
+}: WelcomePageProps): JSX.Element | null => {
+  const isElapsed = useIsElapsed(LOCALE_TIMEOUT);
+
   useEffect(() => {
     onStepShow();
   }, [onStepShow]);
 
+  if (!isElapsed && !isLocaleLoaded) {
```
Comment (ranquild) [inline frontend/src/metabase/setup/components/WelcomePage/WelcomePage.tsx:31]: In case locale data doesn't load in 300 ms, show the user interface in English. By doing that we:
- prevent a "flash" when immediately changing texts from English to the default language after initial render
- handle locale loading issues, so in case it doesn't load we will show the UI in English and update it when the data is loaded

**Review by alxnddr — APPROVED** [review]
