### PR TITLE
fix: handle more header names in translation csv

### LINKED ISSUE #62194: Content translation copy uses wrong header name
### Describe the bug

The UI copy for translations makes it seem like the columns in the dictionary file for embedding translations should be named Locale Code, String, Translation, but we don't accept a file like this. We accept a file with the header Language, String, Translation, or no header at all.

Image

### To Reproduce

1. Create a CSV with 'Locale Code' Header
2. Upload CSV
3. Error

### Expected behavior

The UI copy should use 'Language' instead of 'Locale Code' if that is what the API enforces

### Logs

_No response_

### Information about your Metabase installation

```JSON
v56
```

### Severity

minor but misleading

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edpaget**
closes #62194
### Description

Handle the locale being specified as 'locale', 'locale code', 'language' also make the check for header a little looser so we can report errors in the header row more accurately.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/content_translation/dictionary.clj [hunk 1]
```diff
@@ -51,7 +52,12 @@
 (defn- format-row
   "Formats a row to be inserted into the content translation table. Locales are standardized, and all fields are trimmed. Extra fields are included as well."
   [headers row]
-  (let [{locale :language msgid :string msgstr :translation} (zipmap headers row)
+  (let [row-with-headers (zipmap headers row)
+        locale (or (get row-with-headers "language")
```
Comment (johnswanson) [inline enterprise/backend/src/metabase_enterprise/content_translation/dictionary.clj:56]: To me it feels super odd to make our code looser to fit the copy instead of making the copy tighter to make it more clear exactly what we expect.

Instead of saying

```
The dictionary must be a CSV with these columns:
- Locale Code
- String
- Translation
```

Why not be very specific in our instructions and say

```
The dictionary must be a CSV with these columns:
- `language` (the locale code that should be used, e.g. `de` or `pt_BR`)
- `string` (the string to be translated)
- `translation` (the resulting translation for this language and string)

The column names are case-insensitive, so for example you may use `Language` or `LANGUAGE` instead of `language` if desired.
```

**Review by johnswanson — APPROVED** [review]
Looks good if this is the direction we want but I wonder if it'd be better to fix the copy than to loosen the code here

File: enterprise/backend/src/metabase_enterprise/content_translation/dictionary.clj (hunk 1 above)
Comment (edpaget) [reply enterprise/backend/src/metabase_enterprise/content_translation/dictionary.clj:56]: I thought it made more sense to be looser here because none of those titles are strictly accurate since we allow a mix of langauge codes and locale codes in the csv anyway. Like zh-TW vs zh-CN are locale codes not language codes, but you could also upload with a column es which is a language code not a locale code.
