### PR TITLE
fix(admin/nav): Ensure that the "Exit admin" button can be clicked regardless of locale or viewport size

### LINKED ISSUE #45876: "Exit admin" button is sometimes offscreen
For example, here's French with a viewport width of 973px

Image

German with a viewport width of 980px

Image

Russian with viewport of 1100px

Image

Suggested workaround: set the hamburger-menu breakpoint based on a runtime calculation of the width of all the strings. We have a `measureTextWidth` function

### PR DESCRIPTION
**Pull request by rafpaf**
Ellipsifies nav items when there's not enough horizontal space to display them.

This ensures that the Exit button is always clickable regardless of locale or viewport size.

Some locales, like Russian, French, and German, previously required so much horizontal space to display the admin nav links that the Exit button was pushed partly or wholly offscreen for viewports around 1000px.

This branch uses a _pure CSS_ approach, so it may be a good balance between attractive design and simplicity of implementation.

Kapture 2024-07-25 at 10 39 40

These ellipsified items have no tooltips. Tooltips require measuring the text with js on the fly, and we didn't think the performance overhead was worth it. You can always see the full name of the tab when you click on it.

image

**Screencast**: In this [loom](https://www.loom.com/share/cefc64d7fa314739826664aaf5804e90) I show what this looks like in a variety of locales.

Closes #45876

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#45882** <a href="https://app.graphite.dev/github/pr/metabase/metabase/45882?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: frontend/src/metabase/nav/components/AdminNavbar/utils.tsx [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+/** The breakpoint is based on the width of the items in the nav */
+export const getAdminNavBreakpoint = (
+  adminPaths: AdminPath[],
+  adminLogoText: string,
+  exitButtonText: string,
+) => {
+  try {
+    const navPadding = 32;
+    const iconWidth = 24;
```
Comment (npfitz) [inline frontend/src/metabase/nav/components/AdminNavbar/utils.tsx:25]: This is a lot of magic numbers used to calculate the breakpoint. I like the Idea of the breakpoint for this menu being more dynamic (especially since language can have an impact on the size). Rather than measure the text like this, could we do something similar to what we do for table visualizations and render offscreen to measure? That should give us an accurate idea of what the breakpoint actually is and capture any future style changes.

**Review by npfitz — DISMISSED** [review]
We also need a test of some kind to capture whatever changes are made.

**Review by iethree — CHANGES_REQUESTED** [review]
I'm concerned that this introduces a lot of complexity and potential performance problems for what can be a [simple CSS fix.](https://wiki.c2.com/?DoTheSimplestThingThatCouldPossiblyWork)

Maybe we should also loop in design about changing the breakpoints here to reduce the cases where the text has to wrap at all?

here's an example of a css-only fix https://github.com/metabase/metabase/pull/45947

**Comment by mazameli** [comment]
In the designs for the Admin UI facelift, Roman introduced an icon to go inside the Exit Admin button. To save space even more space, we could switch the exit button to _just_ this icon once the screen reaches a max width of 900px or so. 

image

The Figma-generated SVG for this new `exit` icon is here:

```
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="path-1-inside-1_4193_1181" fill="white">
<path fill-rule="evenodd" clip-rule="evenodd" d="M6.99987 2.25C7.41408 2.25 7.74987 2.58579 7.74987 3C7.74987 3.41421 7.41408 3.75 6.99987 3.75H3.75V12.25H7.00001C7.41422 12.25 7.75001 12.5858 7.75 13C7.74999 13.4142 7.4142 13.75 6.99999 13.75L3 13.7499C2.5858 13.7499 2.25 13.4142 2.25 12.9999V3C2.25 2.58579 2.5858 2.25 3 2.25H6.99987ZM10.4697 9.46967C10.1768 9.76256 10.1768 10.2374 10.4697 10.5303C10.7626 10.8232 11.2374 10.8232 11.5303 10.5303L13.5241 8.53656C13.6635 8.40037 13.7501 8.21029 13.7501 7.99999C13.7501 7.78637 13.6608 7.59361 13.5175 7.45701L11.5304 5.4697C11.2375 5.17679 10.7626 5.17676 10.4697 5.46964C10.1768 5.76252 10.1768 6.23739 10.4696 6.5303L11.1892 7.24999H7C6.58579 7.24999 6.25 7.58578 6.25 7.99999C6.25 8.4142 6.58579 8.74999 7 8.74999H11.1894L10.4697 9.46967Z"/>
</mask>
<path fill-rule="evenodd" clip-rule="evenodd" d="M6.99987 2.25C7.41408 2.25 7.74987 2.58579 7.74987 3C7.74987 3.41421 7.41408 3.75 6.99987 3.75H3.75V12.25H7.00001C7.41422 12.25 7.75001 12.5858 7.75 13C7.74999 13.4142 7.4142 13.75 6.99999 13.75L3 13.7499C2.5858 13.7499 2.25 13.4142 2.25 12.9999V3C2.25 2.58579 2.5858 2.25 3 2.25H6.99987ZM10.4697 9.46967C10.1768 9.76256 10.1768 10.2374 10.4697 10.5303C10.7626 10.8232 11.2374 10.8232 11.5303 10.5303L13.5241 8.53656C13.6635 8.40037 13.7501 8.21029 13.7501 7.99999C13.7501 7.78637 13.6608 7.59361 13.5175 7.45701L11.5304 5.4697C11.2375 5.17679 10.7626 5.17676 10.4697 5.46964C10.1768 5.76252 10.1768 6.23739 10.4696 6.5303L11.1892 7.24999H7C6.58579 7.24999 6.25 7.58578 6.25 7.99999C6.25 8.4142 6.58579 8.74999 7 8.74999H11.1894L10.4697 9.46967Z" fill="#4C5773"/>
<path d="M3.75 3.75V2.75H2.75V3.75H3.75ZM3.75 12.25H2.75V13.25H3.75V12.25ZM6.99999 13.75L6.99997 14.75H6.99999V13.75ZM3 13.7499L3.00003 12.7499H3V13.7499ZM10.4697 10.5303L9.76255 11.2374L9.76255 11.2374L10.4697 10.5303ZM10.4697 9.46967L9.76256 8.76256L9.76256 8.76257L10.4697 9.46967ZM11.5303 10.5303L10.8232 9.82318L10.8232 9.8232L11.5303 10.5303ZM13.5241 8.53656L12.8253 7.82114L12.817 7.82945L13.5241 8.53656ZM13.5175 7.45701L12.8103 8.16408L12.8188 8.17259L12.8275 8.18089L13.5175 7.45701ZM11.5304 5.4697L12.2375 4.76263L12.2375 4.76263L11.5304 5.4697ZM10.4697 5.46964L11.1768 6.17678L11.1768 6.17678L10.4697 5.46964ZM10.4696 6.5303L11.1768 5.82323L11.1768 5.82323L10.4696 6.5303ZM11.1892 7.24999V8.24999H13.6033L11.8964 6.54292L11.1892 7.24999ZM11.1894 8.74999L11.8965 9.4571L13.6036 7.74999H11.1894V8.74999ZM8.74987 3C8.74987 2.03351 7.96636 1.25 6.99987 1.25V3.25C6.8618 3.25 6.74987 3.13807 6.74987 3H8.74987ZM6.99987 4.75C7.96636 4.75 8.74987 3.96649 8.74987 3H6.74987C6.74987 2.86193 6.8618 2.75 6.99987 2.75V4.75ZM3.75 4.75H6.99987V2.75H3.75V4.75ZM4.75 12.25V3.75H2.75V12.25H4.75ZM7.00001 11.25H3.75V13.25H7.00001V11.25ZM8.75 13C8.75002 12.0335 7.96651 11.25 7.00001 11.25V13.25C6.86193 13.25 6.75 13.1381 6.75 13L8.75 13ZM6.99999 14.75C7.9665 14.75 8.74998 13.9665 8.75 13L6.75 13C6.75 12.8619 6.8619 12.75 6.99999 12.75V14.75ZM2.99997 14.7499L6.99997 14.75L7.00002 12.75L3.00003 12.7499L2.99997 14.7499ZM1.25 12.9999C1.25 13.9666 2.0336 14.7499 3 14.7499V12.7499C3.138 12.7499 3.25 12.8618 3.25 12.9999H1.25ZM1.25 3V12.9999H3.25V3H1.25ZM3 1.25C2.03352 1.25 1.25 2.0335 1.25 3H3.25C3.25 3.13808 3.13808 3.25 3 3.25V1.25ZM6.99987 1.25H3V3.25H6.99987V1.25ZM11.1768 9.8232C11.2744 9.92081 11.2744 10.0791 11.1768 10.1768L9.76256 8.76257C9.07914 9.44599 9.07916 10.554 9.76255 11.2374L11.1768 9.8232ZM10.8232 9.8232C10.9208 9.72556 11.0792 9.72556 11.1768 9.8232L9.76255 11.2374C10.446 11.9208 11.554 11.9208 12.2374 11.2374L10.8232 9.8232ZM12.817 7.82945L10.8232 9.82318L12.2374 11.2374L14.2312 9.24367L12.817 7.82945ZM12.7501 7.99999C12.7501 7.9301 12.7801 7.86541 12.8254 7.82119L14.2228 9.25193C14.547 8.93533 14.7501 8.49048 14.7501 7.99999H12.7501ZM12.8275 8.18089C12.7811 8.13661 12.7501 8.07108 12.7501 7.99999H14.7501C14.7501 7.50166 14.5405 7.05062 14.2074 6.73314L12.8275 8.18089ZM10.8232 6.17677L12.8103 8.16408L14.2246 6.74994L12.2375 4.76263L10.8232 6.17677ZM11.1768 6.17678C11.0791 6.27442 10.9208 6.2744 10.8232 6.17677L12.2375 4.76263C11.5541 4.07919 10.4461 4.0791 9.76263 4.7625L11.1768 6.17678ZM11.1768 5.82323C11.2744 5.92088 11.2744 6.07917 11.1768 6.17678L9.76263 4.7625C9.07918 5.44587 9.0791 6.55391 9.7625 7.23737L11.1768 5.82323ZM11.8964 6.54292L11.1768 5.82323L9.76249 7.23737L10.4821 7.95706L11.8964 6.54292ZM7 8.24999H11.1892V6.24999H7V8.24999ZM7.25 7.99999C7.25 8.13807 7.13807 8.24999 7 8.24999V6.24999C6.03351 6.24999 5.25 7.0335 5.25 7.99999H7.25ZM7 7.74999C7.13807 7.74999 7.25 7.86192 7.25 7.99999H5.25C5.25 8.96649 6.03351 9.74999 7 9.74999V7.74999ZM11.1894 7.74999H7V9.74999H11.1894V7.74999ZM11.1768 10.1768L11.8965 9.4571L10.4822 8.04288L9.76256 8.76256L11.1768 10.1768Z" fill="#4C5773" mask="url(#path-1-inside-1_4193_1181)"/>
</svg>
```

File: frontend/src/metabase/nav/components/AdminNavbar/AdminNavItem.styled.tsx [hunk 2]
```diff
@@ -1,16 +1,38 @@
...
+export const AdminNavListItem = styled(
+  "li",
+  doNotForwardProps("path", "currentPath"),
+)<{ path: string; currentPath: string }>`
+  display: inline-flex;
+  flex-shrink: 1;
+  white-space: nowrap;
+  justify-content: center;
+  min-width: ${props =>
+    props.currentPath.startsWith(props.path) ? "fit-content" : "0px"};
```
Comment (iethree) [inline frontend/src/metabase/nav/components/AdminNavbar/AdminNavItem.styled.tsx:37]: I'd prefer to avoid doing this sort of complex logic in the styles. Instead, just pass an `isSelected` prop and do the logic in the component.

File: frontend/src/metabase/nav/components/AdminNavbar/AdminNavItem.tsx [hunk 3]
```diff
@@ -11,9 +11,9 @@ export const AdminNavItem = ({
   path,
   currentPath,
 }: AdminNavItemProps) => (
-  <li>
+  <AdminNavListItem path={path} currentPath={currentPath}>
```
Comment (iethree) [inline frontend/src/metabase/nav/components/AdminNavbar/AdminNavItem.tsx:14]:
```suggestion
  <AdminNavListItem isSelected={currentPath.startsWith(path)}>
```

**Review by iethree — APPROVED** [review]
Looks good! I'd be cool merging this as-is and following up with Maz's icon, or putting it in here. either way.

**Review by iethree — APPROVED** [review]
Looks good! I'd be cool merging this as-is and following up with Maz's icon, or putting it in here. either way.
