### PR TITLE
Skip fields with inactive table.

### LINKED ISSUE #28241: Inactive table still shows in connected sidebar
**Describe the bug**
When you click on the entity id, it shows a popup with details. In this popup, there is a sidebar that shows how this record is connected to other tables. It seems inactive tables still show in this list -- when then the table is deleted, it would show as unknown count. 

**Logs**
n/a

**To Reproduce**
1. Create 2 tables and link them using foreign key in data modeling in admin. Deactivate the table with foreign key mapping by deleting the underlying table and re-scan the schema. 
2. View the table that the foreign table has mapped to
3. Click on a value under the entity id column to view the detail box and the sidebar. 
4. Sidebar shows the linked table even though it is inactive as the underlying table has been deleted. 

**Expected behavior**
Inactive tables shouldn't show. 

**Screenshots**
n/a

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome
- Your operating system: OS X
- Your databases: Postgres
- Metabase version: master
- Metabase hosting environment: Metabase Cloud
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It's mostly cosmetic but does take up screen space. I suppose eventually the inactive table will go away... 

**Additional context**

### PR DESCRIPTION
**Pull request by ericnormand**
closes #28241
Closes QUE-120

### Description

The /api/test/:id/fks endpoint was returning fields from inactive tables. Let's just filter those out. Also includes a test.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Create 2 tables and link them using foreign key in data modeling in admin. Deactivate the table with foreign key mapping by deleting the underlying table and re-scan the schema.
2. View the table that the foreign table has mapped to
3. Click on a value under the entity id column to view the detail box and the sidebar.
4. Sidebar used to show the linked table even though it is inactive as the underlying table has been deleted. Now it doesn't.

### CODE REVIEW

File: test/metabase/warehouse_schema_rest/api/table_test.clj [hunk 1]
```diff
@@ -1339,3 +1341,26 @@
                       (filter #(= (:db_id %) db-id))
                       (map :id)
                       set))))))))
+
+(deftest no-fks-for-missing-tables-test
+  (testing "Check that we don't return foreign keys for missing/inactive tables"
+    (let []
```
Comment (bshepherdson) [inline test/metabase/warehouse_schema_rest/api/table_test.clj]: Redundant let?

**Review by bshepherdson — APPROVED** [review]

**Review by rileythomp — APPROVED** [review]

**Review by ranquild — APPROVED** [review]
