### PR TITLE
Check user exists for setup redirect

### LINKED ISSUE #12874: When env var `MB_SETUP_TOKEN` is set, then interface is always redirected to `/setup`
**Describe the bug**
When trying to automate setup with a predefined `MB_SETUP_TOKEN`, then after a successful POST to `/api/setup`, it's not possible to login, since the frontend thinks it's still in setup-mode forever until starting the instance without the variable.

**To Reproduce**
1. Start a new instance:
```
java -DMB_SETUP_TOKEN=ad0fb086-351b-4fa5-a17e-76282d2c9753 -jar metabase.jar
```
The following is shown in the log during the initial startup
```
...
07-08 23:34:17 INFO metabase.core :: Looks like this is a new installation ... preparing setup wizard
07-08 23:34:17 INFO metabase.core :: Please use the following URL to setup your Metabase installation:
http://localhost:3000/setup/
...
```
2. Run the setup automated:
```
curl 'http://localhost:3000/api/setup' --compressed -H 'Content-Type: application/json' --data-raw '{"token":"ad0fb086-351b-4fa5-a17e-76282d2c9753","prefs":{"site_name":"Test","allow_tracking":"true"},"database":null,"user":{"first_name":"Meta","last_name":"Base","email":"test@test.test","password":"Testtest1","site_name":"Test"}}'
```
3. Try to login via the browser - it will redirect to `/setup` and `/api/session/properties` will have `setup-token` defined.
4. Restarting the instance with `MB_SETUP_TOKEN` still set, will not have the log lines `Looks like this is a new installation ... preparing setup wizard`, but will still redirect to `/setup` like in step 3.
5. Restarting the instance without `MB_SETUP_TOKEN` will show the login, and allow normal use.

**Expected behavior**
After the setup is completed, then the environment variable should be ignored - without the need to restart the instance without the variable defined.

**Information about your Metabase Installation:**
Metabase 1.35.4.1

**Additional context**
Originally from #12869

### PR DESCRIPTION
**Pull request by escherize**
This change fixes #12874. 

When setting `setup-token` via the `MB_SETUP_TOKEN` environment variable, the setting cannot be changed. We were trying to clear the setting, and use that value on the frontend to skip the setup flow.

This change introduces a new setting: `has-user-setup` which is true iff one or more users have been registered on the instance. `has-user-setup` is used by the frontend to determine whether to redirect to the setup flow, or not.

This setting is also used to allow only _one_ user to be added via a post to `/api/setup`, as the user in the issue was doing.

also note, that tests use the `/api/setup` endpoint to create multiple users, so I have added a check to `config/is-test?` that will allow that behavior.

### CODE REVIEW

File: src/metabase/core.clj [hunk 1]
```diff
@@ -60,6 +59,12 @@
                                    setup-url
                                    "\n\n")))))
 
+(defn- -init-create-setup-token
```
Comment (camsaul) [inline src/metabase/core.clj:62]: I know you didn't come up with the name `-init-create-setup-token` here but since you're touching it I noticed it. I think we should change the name to fit our coding conventions elsewhere. I think something like `create-setup-token-and-log-setup-url!` would be a 100x better name for this function.

1. We don't really prefix anything else with a hyphen no matter how secret/internal it is
2. We suffix DML type things with `!` (https://guide.clojure.style/#naming-unsafe-functions)
3. `-init-create-setup-token` doesn't really tell you much about what this function does

File: src/metabase/core.clj [hunk 2]
```diff
@@ -44,10 +44,9 @@
 
 ;;; --------------------------------------------------- Lifecycle ----------------------------------------------------
 
-(defn- -init-create-setup-token
-  "Create and set a new setup token and log it."
+(defn print-setup-url
```
Comment (camsaul) [inline src/metabase/core.clj:47]: You should make this private https://github.com/metabase/metabase/wiki/Metabase-Clojure-Style-Guide#make-things-private

The main reason is so if we want to refactor it in the future we don't have to look around the codebase and make sure it's not used anywhere else. (Also when you look thru this namespace to use something from it the surface area of it is a little smaller and it's clearer which things are mean to be used elsewhere)

File: src/metabase/api/setup.clj [hunk 3]
```diff
@@ -39,6 +39,9 @@
     "Token does not match the setup token."))
 
 (defn- setup-create-user! [{:keys [email first-name last-name password]}]
+  (when-not config/is-test?
+    ;; many tests use /api/setup to setup multiple users
+    (assert (not (setup/has-user-setup)) "setup-create-user! can only be called when no users have been setup."))
```
Comment (camsaul) [inline src/metabase/api/setup.clj:44]: 1. This should be i18n'ed since there's a chance it can be hit by someone who isn't a actively hacking on Metabase
2. This should throw an `ExceptionInfo` with a `:status-code`. Otherwise I think this would probably end up returning a 500 which is not appropriate here
```suggestion
    (when-not (setup/has-user-setup)
      (throw (ex-info (tru "Setup endpoints can not be used after a user has been created.") {:status-code 400})))
```

File: src/metabase/setup.clj [hunk 4]
```diff
@@ -25,12 +26,14 @@
...
-(defn clear-token!
-  "Clear the setup token if it exists and reset it to `nil`."
-  []
-  (setting/set-value-of-type! :string :setup-token nil))
+(defsetting has-user-setup
+  "A value that is true iff the metabase instance has one or more users registered."
+  :visibility :public
+  :type       :boolean
+  :setter     :none
+  :getter     (fn [] (db/exists? User)))
```
Comment (camsaul) [inline src/metabase/setup.clj:39]: We can't ever become un-set-up after we're set up (we specifically disallow deleting the last User) and since this is a `:public` Setting that gets returned every time someone loads up the app I think it's worth optimizing out the application DB hit. One little hit like this is not a huge deal but they tend to add up over time if we don't try to be aggressive about eliminating them where we can.

I would do something like this:

```suggestion
(defsetting has-user-setup
  "A value that is true iff the metabase instance has one or more users registered."
  :visibility :public
  :type       :boolean
  :setter     :none
  ;; Once a User is created it's impossible for this to ever become falsey -- deleting the last User is disallowed.
  ;; After this returns true once the result is cached and it will continue to return true forever without any
  ;; additional DB hits.
  :getter     (let [user-exists? (atom false)]
                (fn []
                  (or @user-exists?
                      (reset! user-exists? (db/exists? User))))))
```

File: src/metabase/api/setup.clj (hunk 3 above)
Comment (camsaul) [reply src/metabase/api/setup.clj:44]: I think having that `config/is-test?` flag is actually not the best way to go about this since it effectively makes this logic impossible to test. I think adding a dynamic variable like `*disallow-setup-api-calls-after-first-user-is-created*` (default `false`) and then binding that to `true` in relevant tests is better than just a blanket disabling of this logic in tests

File: src/metabase/setup.clj (hunk 4 above)
Comment (dpsutton) [reply src/metabase/setup.clj:39]: I'm still a bit hazy on how the caching system works but would the cache not prevent this from hitting the db all the time?

**Review by camsaul — DISMISSED** [review]
This looks like it's on the right track to me but it **really** needs some tests. Having no test coverage for code in absolutely critical parts of the application like the setup is just too risky (especially since being able to hit setup a second time is a huge security risk -- especially now that we're not clearing out the token anymore). Please add some tests to verify that the endpoints in question actually return a 400 response if a User already exists. Ping me again when tests are added and I will 👍

File: src/metabase/setup.clj (hunk 4 above)
Comment (camsaul) [reply src/metabase/setup.clj:39]: Caching is part of the default get-value-from-application-DB getters but for a Setting with a completely custom getter the cache is bypassed. Calling `(has-user-setup)` or `(setting/get :has-user-setup)` is effectively the same as just calling the `:getter` function here.

This is intentional, since custom getters are usually returning calculated values caching them wouldn't be desirable in most cases. For example because the cache is set up to flush when rows in the `setting` Table change in the app DB, it wouldn't pick up changes to the `User` table and could end up returning the wrong value if this was cached

Comment (dpsutton) [reply src/metabase/setup.clj:39]: Makes sense. Thanks

File: src/metabase/core.clj (hunk 2 above)
Comment (escherize) [reply src/metabase/core.clj:47]: Good catch, thanks!

File: src/metabase/api/setup.clj [hunk 5]
```diff
@@ -38,21 +38,33 @@
   (su/with-api-error-message (s/constrained su/NonBlankString setup/token-match?)
     "Token does not match the setup token."))
 
+(def ^:dynamic ^:private *disallow-api-setup-after-first-user-is-created*
```
Comment (dpsutton) [inline src/metabase/api/setup.clj:41]: this should be `*allow-api-setup-after-first-user-created* false` and then the test can change this to `true` as needed.

File: src/metabase/api/setup.clj [hunk 6]
```diff
@@ -38,21 +38,33 @@
...
+  "We must not allow users to setup multiple super users once the first user is created. But tests still need to be able
+  to do that. This var is redef'd to false by certain tests to allow that."
+  true)
+
 (defn- setup-create-user! [{:keys [email first-name last-name password]}]
+  (when (and *disallow-api-setup-after-first-user-is-created* (setup/has-user-setup))
```
Comment (dpsutton) [inline src/metabase/api/setup.clj:47]: the logic here seems weird. It doesn't feel like an override here. I know we can deMorgan our way into this but the logic could be more clear.
`(when (and (setup/has-user-setup) (not *allow-api-setup...*)` reads more like what my brain interprets it as. There's already a user setup and the override is not in place. It feels backwards to check the override before even the condition. I know its equivalent but my brain is struggling for some reason.

File: src/metabase/core.clj [hunk 7]
```diff
@@ -44,10 +44,9 @@
 
 ;;; --------------------------------------------------- Lifecycle ----------------------------------------------------
 
-(defn- -init-create-setup-token
-  "Create and set a new setup token and log it."
+(defn- print-setup-url
+  "Used to print the setup url during instance initialization."
```
Comment (dpsutton) [inline src/metabase/core.clj:48]: "Used to" adds nothing here. "Print the setup url during instance initialization" is the same but without being verbose.

File: test/metabase/api/setup_test.clj [hunk 8]
```diff
@@ -272,6 +274,39 @@
...
+      (let [token (setup/create-token!)
+            body  {:token token
+                   :prefs {:site_locale "es_MX"
+                           :site_name   (mt/random-name)}
+                   :user  {:first_name (mt/random-name)
+                           :last_name  (mt/random-name)
+                           :email      (mt/random-email)
+                           :password   "p@ssword1"}}]
+
+        (is (setup/has-user-setup))
```
Comment (dpsutton) [inline test/metabase/api/setup_test.clj:289]: If this test is run with `clj -X:dev:test :only metabase.api.setup-test/create-superuser-only-once-test` i suspect this line will fail? It seems we will need to ensure that the user information is completely mocked in this test

File: test/metabase/api/setup_test.clj [hunk 9]
```diff
@@ -272,6 +274,39 @@
...
+
+        (with-redefs [setup/has-user-setup (let [value (atom false)]
+                                             (fn
+                                               ([] @value)
+                                               ([x] (reset! value x))))]
```
Comment (dpsutton) [inline test/metabase/api/setup_test.clj:294]: the setting has a `:setter :none`. Should this throw rather than reset the value? or is this just a helper to change the value in the test?

File: test/metabase/api/setup_test.clj [hunk 10]
```diff
@@ -272,6 +274,39 @@
...
+
+          (is (not (setup/has-user-setup)))
+
+          (mt/discard-setting-changes [site-name
+                                       site-locale ;; anon-tracking-enabled
+                                       admin-email]
+            (fn []
```
Comment (dpsutton) [inline test/metabase/api/setup_test.clj:301]: `mt/discard-setting-changes` is a macro that thunks its body so i don't think you want the manual `(fn [] ...)` bits here

File: src/metabase/api/setup.clj (hunk 6 above)
Comment (escherize) [reply src/metabase/api/setup.clj:47]: Good point, its easy from my pov to focus on the override itself. But it makes more sense to highlight on the triggering condition (aka there is a user already).

File: test/metabase/api/setup_test.clj (hunk 8 above)
Comment (escherize) [reply test/metabase/api/setup_test.clj:289]: There are actually 4 users setup in the test database, so has-user-setup is 'set'. I was working on a function wrapper that would save, and delete them, run the test, and reinstate them, but cannot get it to work in a way that doesn't pollute the test db and break _other_ tests.

File: test/metabase/api/setup_test.clj (hunk 9 above)
Comment (escherize) [reply test/metabase/api/setup_test.clj:294]: I'll simplify this. As you said it doesn't need to be settable, all it needs to do is return a value when called with 0 args, and not accept 1 arg. Would it be worth using an actual setting with a :getter that returns false?

File: test/metabase/api/setup_test.clj (hunk 8 above)
Comment (dpsutton) [reply test/metabase/api/setup_test.clj:289]: That's fair. I'm just not positive that it is always the case that there are four users in the database under scenarios where you run the tests for an individual namespace from the cli.

File: src/metabase/api/setup.clj [hunk 11]
```diff
@@ -38,21 +38,33 @@
...
+    ;; many tests use /api/setup to setup multiple users, so *first-user-only* is redefined by them
+    (throw (ex-info
+            (tru "The /api/setup route can only be used to create the first user, however a user currently exists.")
+            {:status-code 403
```
Comment (dpsutton) [inline src/metabase/api/setup.clj:51]: I'm wondering if we should just return the 403 here and not the other information.

File: test/metabase/api/setup_test.clj (hunk 9 above)
Comment (dpsutton) [reply test/metabase/api/setup_test.clj:294]: I guess I'm wondering if this should be just `(binding [setup/has-user-setup (constantly false))`. Or if you want to change it after a few tests,

`(let [setup? (atom false)] (binding [setup/has-user-setup (fn [] @setup?)] (test) (reset! setup? true) (test asserting that you can do something now)`

File: test/metabase/api/setup_test.clj (hunk 8 above)
Comment (escherize) [reply test/metabase/api/setup_test.clj:289]: Gotcha, I'll remove that line and add a test that takes that into account.

File: src/metabase/api/setup.clj (hunk 11 above)
Comment (escherize) [reply src/metabase/api/setup.clj:51]: I noticed some other places ex-info used return information, but perhaps the `has-users-setup` value is too internal to be useful here.

File: test/metabase/api/setup_test.clj (hunk 9 above)
Comment (escherize) [reply test/metabase/api/setup_test.clj]: I thought about the `(constantly false)` piece a bit: I think it shouldn't be because I want an exception to occur if `setup/has-user-setup` arity-1 version gets called, because thats how the setting behaves with a `:none` `:getter`.

File: test/metabase/api/setup_test.clj (hunk 10 above)
Comment (escherize) [reply test/metabase/api/setup_test.clj]: How embarrassing! 😆

File: test/metabase/api/setup_test.clj (hunk 9 above)
Comment (escherize) [reply test/metabase/api/setup_test.clj]: The latest PR includes the switching to `true` of `setup/has-user-setup`.

File: src/metabase/api/setup.clj (hunk 3 above)
Comment (escherize) [reply src/metabase/api/setup.clj]: Makes sense. I have added `*allow-setup-api-calls-after-first-user-is-created*` and am working on testing it

File: src/metabase/models/setting.clj [hunk 12]
```diff
@@ -932,7 +932,7 @@
   (binding [*database-local-values* nil]
     (into
      {}
-     (comp (filter (fn [[_ setting]]
+     (comp (filter (fn [[_setting-name setting]]
```
Comment (dpsutton) [inline src/metabase/models/setting.clj:935]: just an aside, I love the convention of `_setting-name` to make this easier to read. Thanks

**Comment by dpsutton** [comment]
Works for me. I grabbed the jar from here,

```shell
MB_SETUP_TOKEN=0e64bb35-187a-458b-a85d-c182398b238a \
  MB_DB_CONNECTION_URI="postgres://<redact>/setup1" \
  MB_JETTY_PORT=3006 java -jar metabase.jar
```

and in another terminal

```shell
❯ http POST http://localhost:3006/api/setup token=0e64bb35-187a-458b-a85d-c182398b238a "user[first_name]"=dan "user[last_name]"=sutton "user[email]"="dan@metabase.com" "user[password]"=bugbash1 "prefs[site_name]"=test
HTTP/1.1 200 OK
 [stuff omitted]

{
    "id": "65fef68a-e73c-4d10-8c54-e837817a6ccf"
}

❯ http POST http://localhost:3006/api/setup token=0e64bb35-187a-458b-a85d-c182398b238a "user[first_name]"=dan "user[last_name]"=sutton "user[email]"="dan1@metabase.com" "user[password]"=bugbash1 "prefs[site_name]"=test
HTTP/1.1 403 Forbidden

The /api/setup route can only be used to create the first user, however a user currently exists.
```
and of course

```sql
setup1=# select count(*) from core_user;
 count
-------
     1
(1 row)
```

And the app took me to the login screen instead of the setup flow.

File: test/metabase/api/setup_test.clj [hunk 13]
```diff
@@ -272,6 +274,39 @@
...
+        (with-redefs [setup/has-user-setup (let [value (atom false)]
+                                             (fn
+                                               ([] @value)
+                                               ([t-or-f] (reset! value t-or-f))))]
+          (mt/discard-setting-changes
+              [site-name site-locale anon-tracking-enabled admin-email]
+            (http/client :post 200 "setup" body))
+
+          ;; In the non-test context, this is 'set' iff there is one or more users, and doesn't have to be toggled
+          (setup/has-user-setup true)
```
Comment (dpsutton) [inline test/metabase/api/setup_test.clj:304]: I think i'd rather see `(reset! allow-setup true)` so no one gets the impression that this setting is settable, even though we are `redef`ing it above. I think I'd also like some user count assertions. Get the count of users in the let, assert it increments after you 200 post, then assert it does not change again after you 403 post.

Comment (dpsutton) [reply test/metabase/api/setup_test.clj:304]: The user count is what is actually super important here and what we want to assert.

**Comment by camsaul** [comment]
I'm 👍 on this WRT to the changes I requested but I'll defer to @dpsutton to give the final 👍 since he has more context

**Review by dpsutton — APPROVED** [review]

**Review by camsaul — APPROVED** [review]
