### PR TITLE
hide action popover when scrolling data table

### LINKED ISSUE #5302: Data table popovers positioned incorrectly when target is scrolled out of view
### Metabase Mac App

issue

Sometimes, the query bar shows up in a totally unexpected place. This is not intended to happen, although I do not know the reason for it. Any ideas?

### PR DESCRIPTION
**Pull request by kdoh**
Fixes #5302

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/Visualization.jsx [hunk 1]
```diff
@@ -396,6 +396,7 @@ export default class Visualization extends Component {
                         visualizationIsClickable={this.visualizationIsClickable}
                         onRenderError={this.onRenderError}
                         onRender={this.onRender}
+                        onActionDismissal={() => this.setState({ clicked: null })}
```
Comment (attekei) [inline frontend/src/metabase/visualizations/components/Visualization.jsx]: We should try to avoid arrow functions inside `render()` for performance reasons so move `() => ...` to a class method! See https://flexport.engineering/optimizing-react-rendering-part-1-9634469dca02

File: frontend/src/metabase/visualizations/components/TableInteractive.jsx [hunk 2]
```diff
@@ -362,7 +363,10 @@ export default class TableInteractive extends Component {
                         rowCount={rows.length}
                         rowHeight={ROW_HEIGHT}
                         cellRenderer={this.cellRenderer}
-                        onScroll={({ scrollLeft }) => onScroll({ scrollLeft })}
+                        onScroll={({ scrollLeft }) => {
+                            this.props.onActionDismissal()
```
Comment (attekei) [inline frontend/src/metabase/visualizations/components/TableInteractive.jsx]: Feels a little wasteful to trigger `onActionDismissal` all the time during scroll but seems that there isn't anything like `onScrollStart` for react-virtualized `Grid` element 😕 So probably it's good as it currently is!

**Review by attekei — COMMENTED** [review]
Seems to work correctly at least on Chrome and Safari! Only a tiny comment about usage of arrow functions, after that g2g :)
