### PR TITLE
Don't reset map zoom when filter is active and a marker is clicked to view details

### LINKED ISSUE #65076: Clicking on Detail View for a Map Pin Reset Zoom if there's a Filter Applied
### Describe the bug

If you Zoom in on a pin map and then click on a pin you get a nice pop up modal with details. If you apply a filter before you do this, the Zoom is reset every time you visit the detail view. This makes it really difficult to use the map to explore details in a specific area because you have to re-zoom every time you look at details.

### To Reproduce

1. Create a map on the people table
2. Set the pin type to "markers"
3. Save
4. Zoom in on a section of the map and click a pin
5. Note the details modal pops up and behaves just fine
6. Add a filter
7. Zoom in on a section of the map
8. Click a pin
9. Note the Zoom is reset

https://www.loom.com/share/18e7fe6432c749488df46321bd527ccd

### Expected behavior

Zoom level should be retained when viewing details

### Logs

_No response_

### Information about your Metabase installation

```JSON
56.11
```

### Severity

Renders maps unusable for some cases

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andsalves**
closes #65076
Closes https://linear.app/metabase/issue/UXW-2159/clicking-on-detail-view-for-a-map-pin-reset-zoom-if-theres-a-filter

### Description

When a map question has a filter applied, then you change the zoom, and then click a map marker to view the details, the zoom gets reset to the initial state.

### How to verify

Please refer to the [reproduction steps](https://linear.app/metabase/issue/UXW-2159/clicking-on-detail-view-for-a-map-pin-reset-zoom-if-theres-a-filter#to-reproduce-87e1ddb5).

### Demo
https://www.loom.com/share/a82299cea7494e0cb75f0e583253404e

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/utils.js [hunk 1]
```diff
@@ -196,7 +196,7 @@ const cardinalityCache = new Map();
 export function getColumnCardinality(cols, rows, index) {
   const col = cols[index];
   const key = getColumnKey(col);
-  if (!cardinalityCache.has(key)) {
+  if (!cardinalityCache.has(key) && rows) {
```
Comment (andsalves) [inline frontend/src/metabase/visualizations/lib/utils.js:199]: getting rid of a console error that happens because `rows` is undefined.

**Review by deniskaber — APPROVED** [review]
Works as described!

**Review by bpander — APPROVED** [review]
Definitely works, just wondering why `shouldRecalculateZoom` was defined the way it was? If I make the condition `if (prevProps?.points !== this.props.points) {`, it also prevents unnecessary zoom recalculations.

**Comment by andsalves** [comment]
> Definitely works, just wondering why `shouldRecalculateZoom` was defined the way it was? If I make the condition `if (prevProps?.points !== this.props.points) {`, it also prevents unnecessary zoom recalculations.

You're right! A trivial comparison actually works. I think at some point I thought the issue was that the array reference was being changed but the points not. I also didn't want to do a full deep comparison as we may have hundreds or thousands of points (containing floating-point numbers).

I updated the condition to be simplified here [a0c5fd7](https://github.com/metabase/metabase/pull/67063/commits/a0c5fd7533d52423853a041dd02c97cf908004a5)
