### PR TITLE
Frontend loading performance fixes

### LINKED ISSUE #8327: JS and CSS not properly compressed/uglified
self hosting metabase using the docker image:
```
metabase/metabase      latest              3ea53572d627
```
which is also tagged as `v0.30.0`

The front-end assets are not compressed at all, all of them are in plain text together with all the comment.
For example the `vendor.bundle.js` alone is 7.18MB in size, 1.7MB after nginx's gzip. It's abnormally large for a web page asset.

I think it's a packing issue during the build but I'm unfamiliar with front-end building/packing staff, hope it can be fixed soon.

Thanks.

### PR DESCRIPTION
**Pull request by tlrobinson**
* [x] re-enable minification
* [x] re-enable caching of static assets

Resolves #8327

### CODE REVIEW

File: src/metabase/middleware.clj [hunk 1]
```diff
@@ -216,10 +226,12 @@
   (when-let [k (ssl-certificate-public-key)]
     {"Public-Key-Pins" (format "pin-sha256=\"base64==%s\"; max-age=31536000" k)}))
 
-(defn- security-headers [& {:keys [allow-iframes?]
-                            :or   {allow-iframes? false}}]
+(defn- security-headers [& {:keys [allow-iframes? allow-cache?]
+                            :or   {allow-iframes? false, allow-cache? false}}]
```
Comment (senior) [inline src/metabase/middleware.clj]: This doesn't hurt anything, but it's also not required. If `allow-cache?` isn't in the map, it will be nil which is falsey.

File: src/metabase/middleware.clj [hunk 2]
```diff
@@ -168,6 +173,11 @@
    "Expires"        "Tue, 03 Jul 2001 06:00:00 GMT"
    "Last-Modified"  (du/format-date :rfc822)})
 
+ (defn- cache-far-future-headers
+   "Headers that tell browsers to cache a static resource for a long time."
+   []
+   {"Cache-Control" "public, max-age=31536000"})
```
Comment (senior) [inline src/metabase/middleware.clj]: This can just be a `def`

**Review by senior — CHANGES_REQUESTED** [review]
Looks good, just some minor comments.

File: src/metabase/middleware.clj (hunk 1 above)
Comment (tlrobinson) [reply src/metabase/middleware.clj]: I was just following what `allow-iframe?` did. Is there a reason for one to have a default but not the other?

File: src/metabase/middleware.clj (hunk 2 above)
Comment (tlrobinson) [reply src/metabase/middleware.clj]: Again I was just copying what `cache-prevention-headers` did, which also doesn't seem like it needs to be a function, but is for some reason.

File: src/metabase/middleware.clj (hunk 1 above)
Comment (senior) [reply src/metabase/middleware.clj]: I missed that `allow-iframes?` was defaulted too. It doesn't look like it's needed there either. I'd say just leave it the way you have it though, no big deal there.

File: src/metabase/middleware.clj (hunk 2 above)
Comment (senior) [reply src/metabase/middleware.clj]: `cache-prevention-headers` needs to be a function because it includes the time of the request as the `Last-Modified` value, which is different for every request. `cache-far-future-headers` is basically just a constant and doesn't change on each request.
