### PR TITLE
Fix usage_info IN clause exceeding 65K parameter limit (GHY-2413)

### LINKED ISSUE #63174: GET /api/database/2/usage_info uses IN statement which can't have more than 65K parameters
### Describe the bug

We're shooting ourselves in the foot here again:

{:via
 [{:type clojure.lang.ExceptionInfo,
   :message
   "Error executing SQL query: PreparedStatement can have at most 65,535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. Given query has 201,533 parameters\n\nSELECT\n  *\nFROM\n  (\n    SELECT\n      COUNT(*) AS \"question\"\n    FROM\n      \"report_card\"\n    WHERE\n      (\"database_id\" = ?)\n      AND (\"type\" = ?)\n  ) AS \"question\",\n  (\n    SELECT\n      COUNT(*) AS \"dataset\"\n    FROM\n      \"report_card\"\n    WHERE\n      (\"database_id\" = ?)\n      AND (\"type\" = ?)\n  ) AS \"dataset\",\n  (\n    SELECT\n      COUNT(*) AS \"metric\"\n    FROM\n      \"report_card\"\n    WHERE\n      (\"database_id\" = ?)\n      AND (\"type\" = ?)\n  ) AS \"metric\",\n  (\n    SELECT\n      COUNT(*) AS \"segment\"\n    FROM\n      \"segment\"\n    WHERE\n      \"table_id\" IN (\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n        ?,\n      ...

### To Reproduce

This is a massive DB with more than 100K tables for sure
Start Metabase and see the error (also the query takes ages). E.g.:
[12302bd1-343c-44d2-b9a8-e8298881a728] 2025-09-05T11:32:47-03:00 ERROR metabase.server.middleware.log GET /api/database/2/usage_info 500 **483948ms** (3 DB calls) {:metabase-user-id 2} 

### Expected behavior

We should not use IN statements on endpoints with prepared statements

### Logs

Above

### Information about your Metabase installation

```JSON
v56.3 on the cloud
```

### Severity

P2

### Additional context

NA

### PR DESCRIPTION
**Pull request by ericnormand**
closes #63174

## Summary
- Fixes `GET /api/database/:id/usage_info` failing when a database has more than 65K tables
- The segment count query was passing all table IDs as parameters to an `IN` clause, which exceeds PostgreSQL's 65,535 parameter limit
- Replaced the `IN` clause with a subselect (`SELECT id FROM metabase_table WHERE db_id = ?`), eliminating the parameter explosion
- Removed the now-unnecessary `select-pks-set` call and `table-ids` argument from `database-usage-query`

## Test plan
- [x] New test `get-database-usage-info-no-large-in-test` intercepts HoneySQL and asserts no `IN` clauses with inline collections
- [x] Test fails with old code, passes with fix
- [x] Existing `get-database-usage-info-test` and `get-database-usage-info-test-2` still pass
- [x] Verified fix on Postgres locally — reproduces the 65K param error before, passes after
- [x] Kondo clean (0 errors, 0 warnings)

### CODE REVIEW

File: test/metabase/warehouses_rest/api_test.clj [hunk 1]
```diff
@@ -278,6 +278,26 @@
...
+                        "   SELECT x + 1 FROM nums WHERE x < 66000"
+                        " )"
+                        " SELECT ?, CONCAT('table_', x), TRUE, 'database', NOW(), NOW()"
+                        " FROM nums")
+                   db-id])
+        (is (= {:question 0
+                :dataset  0
+                :metric   0
+                :segment  0}
+               (mt/user-http-request :crowberto :get 200 (format "database/%d/usage_info" db-id))))))))
```
Comment (galdre) [inline test/metabase/warehouses_rest/api_test.clj]: If we wanted to avoid a 10s test we could probably just assert on the generated SQL.

**Review by galdre — APPROVED** [review]

File: test/metabase/warehouses_rest/api_test.clj (hunk 1 above)
Comment (ericnormand) [reply test/metabase/warehouses_rest/api_test.clj]: Yeah. It's 22 seconds on h2 on my local machine. Let me see how to test it.

Comment (ericnormand) [reply test/metabase/warehouses_rest/api_test.clj]: Alright, I changed it to check the sql for IN clauses with lists instead of generating 66K tables.
