### PR TITLE
Fix flaky test caused by unmounted HoverCard

### LINKED ISSUE #39991: [E2E] Fix the flake `question/caching.cy.spec.js`
Failed job: https://github.com/metabase/metabase/actions/runs/8247731157/job/22556914384?pr=38946#step:13:194

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/39991

### Description

The problem occurred because somehow sometimes, the test would not unmount the [fake columns](https://github.com/metabase/metabase/blob/359a8dacc6b656a83bc0709e66753a024514ea06/frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx#L270) we used to measure the table size. And when that happened, `popover()` E2E util will find not only the open popover, but also `MetadataInfo/Popover` which has a different class `.mantine-HoverCard-dropdown` than what we exclude in that util `.emotion-HoverCard-dropdown`. I believe this is because we use `ReactDOM.render` and didn't render this under any provider that changes its prefix.

The fix is to change the way info dot popover works. Previously it will always mount, so the selector for `popover()` in our E2E tests would always find these info dots.

Since we only render these info dots when we hover over it, `popover()` won't find more than 1 element.

### How to verify

The main component changed is the `MetadataInfo/Popover` which is used in 3 places.
1. Table info dot > Browse a table > See the info dot beside the table name
1. Query column info dot > Browse a table > Hover over the column name
1. Table column info dot > Native query > Add a parameter and set it to Field Filter > Select a table > See the info dot beside any field

So, we need to verify that those 3 HoverCard still works as expected by hover over it and see if clicking inside the hover card should not close it.

### Demo
1. QueryColumnInfoPopover
    image
1. TableColumnInfoPopover
    image
1. TableInfoPopover
    image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### Note
- I didn't backport this because the [original PR that introduced `MetadataInfo/Popover`](https://github.com/metabase/metabase/pull/39296) isn't backported.
- [Stress test result](https://github.com/metabase/metabase/actions/runs/8541267532) 20/20 ✅

### CODE REVIEW

File: e2e/support/helpers/e2e-ui-elements-helpers.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 // various Metabase-specific "scoping" functions like inside popover/modal/navbar/main/sidebar content area
 export const POPOVER_ELEMENT =
-  ".popover[data-state~='visible'],[data-position]:not(.emotion-HoverCard-dropdown)";
+  ".popover[data-state~='visible'],[data-element-id=mantine-popover]";
```
Comment (WiNloSt) [inline e2e/support/helpers/e2e-ui-elements-helpers.js:3]: `[data-element-id=mantine-popover]` is basically the same as `[data-position]`, but the reason we can remove `:not(.emotion-HoverCard-dropdown)` now is because we don't display hover card before we hover over them now.

If you read the issue description this was the cause of the flake, because the fake columns somehow have a different class name `.mantine-HoverCard-dropdown` instead of `.emotion-HoverCard-dropdown`. And I don't want to keep adding more class since it looks more like a hack.

File: e2e/test/scenarios/admin-2/whitelabel.cy.spec.js [hunk 2]
```diff
@@ -156,7 +155,7 @@ describeEE("formatting > whitelabel", () => {
           cy.findByRole("searchbox", {
             name: "Login and unsubscribe pages",
           }).click();
-          mantinePopover().findByText("Custom").click();
+          popover().findByText("Custom").click();
```
Comment (WiNloSt) [inline e2e/test/scenarios/admin-2/whitelabel.cy.spec.js:158]: Reuse the current util. `mantinePopover` was introduce way before `popover` was made to work with Mantine popover.

File: frontend/src/metabase/components/MetadataInfo/Popover/Popover.tsx [hunk 3]
```diff
@@ -60,14 +58,19 @@ export function Popover({
       transitionProps={{
         duration: group.shouldDelay ? POPOVER_TRANSITION_DURATION : 0,
       }}
-      keepMounted
```
Comment (WiNloSt) [inline frontend/src/metabase/components/MetadataInfo/Popover/Popover.tsx:63]: This is the key fix. When we don't always render this component, we don't need to exclude it from `popover()` util anymore, since this will only appear after we hover over it.

File: frontend/src/metabase/components/MetadataInfo/Popover/Popover.tsx [hunk 4]
```diff
@@ -60,14 +58,19 @@ export function Popover({
...
     >
       <HoverCard.Target>{children}</HoverCard.Target>
       <Dropdown>
         {/* HACK: adds an element between the target and the card */}
         {/* to avoid the card from disappearing */}
         <Target />
-        <WidthBound ref={ref}>{isOpen && content}</WidthBound>
+        <WidthBound
+          ref={node => {
+            setupCloseHandler(node, () => setIsOpen(false));
```
Comment (WiNloSt) [inline frontend/src/metabase/components/MetadataInfo/Popover/Popover.tsx:69]: Move the `setupCloseHandler` here instead because `handleOpen` will be called before `ref.current` is set. When that happens, if we click inside this hover card, it will still close it because we never call `setupCloseHandler` with the hover card DOM node.

File: frontend/src/metabase/ui/components/overlays/Popover/index.tsx [hunk 5]
```diff
@@ -6,15 +6,12 @@ export { getPopoverOverrides } from "./Popover.styled";
 
 const MantinePopoverDropdown = Popover.Dropdown;
 
-const PopoverDropdown = Object.assign(function PopoverDropdown(
-  props: PopoverDropdownProps,
-) {
+const PopoverDropdown = function PopoverDropdown(props: PopoverDropdownProps) {
```
Comment (WiNloSt) [inline frontend/src/metabase/ui/components/overlays/Popover/index.tsx:9]: This is only a refactor. I removed unnecessary `Object.assign` and type casting.

File: frontend/src/metabase/ui/components/overlays/Popover/index.tsx [hunk 6]
```diff
@@ -6,15 +6,12 @@ export { getPopoverOverrides } from "./Popover.styled";
...
   return (
     <MantinePopoverDropdown {...props} data-element-id="mantine-popover" />
   );
-},
-MantinePopoverDropdown);
-
-Popover.Dropdown = PopoverDropdown as typeof MantinePopoverDropdown;
+};
+PopoverDropdown.displayName = MantinePopoverDropdown.displayName;
```
Comment (WiNloSt) [inline frontend/src/metabase/ui/components/overlays/Popover/index.tsx:14]: I wasn't setting `displayName` before that's why I needed to cast its type.

**Review by uladzimirdev — APPROVED** [review]

**Comment by uladzimirdev** [comment]
actually I didn't notice your stress test and ran my own - https://github.com/metabase/metabase/actions/runs/8543913608/job/23408771278 - it failed

**Comment by WiNloSt** [comment]
The commit that merged those tests [ran fine the first time](https://github.com/metabase/metabase/actions/runs/8535325913/job/23381890462) (no retry)

I also ran that test locally `e2e/test/scenarios/admin-2/whitelabel.cy.spec.js`, and all tests passed.

**Comment by qnkhuat** [comment]
not all heroes wea capes
