### PR TITLE
Fix AccordionList PropType

### LINKED ISSUE #16159: Wrong PropType in AccordionList component
Getting the following warning in web console:

```
react_devtools_backend.js:2557 Warning: Failed prop type: Invalid prop `width` of type `string` supplied to `AccordionList`, expected `number`.
    in AccordionList (created by TablePicker)
    in TablePicker (created by UnconnectedDataSelector)
    in div
    in OnClickOutsideWrapper
    in span
```

**To Reproduce**

1. Open orders table from a custom question
2. Click on the small grid icon to create custom column

**Expected behavior**

No warning.

**Screenshots**

image

**Severity**
Low

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #16159 

## How to Test

1. Open orders table from a custom question
2. Click on the small grid icon to create custom column
3. Filter console for `AccordionList`

You should see no warning.

### CODE REVIEW

**Review by kulyk — APPROVED** [review]
LGTM. Thank you for structuring and approaching console error issues 💪

File: frontend/src/metabase/components/AccordionList.jsx [hunk 1]
```diff
@@ -51,7 +49,9 @@ export default class AccordionList extends Component {
     className: PropTypes.string,
     id: PropTypes.string,
 
-    width: PropTypes.number,
+    // TODO: pass width to this component as solely number or string if possible
```
Comment (nemanjaglumac) [inline frontend/src/metabase/components/AccordionList.jsx:52]: Just as a general approach for future:
Do we want to immediately open related issues that are "tied" to these TODOs? There are far too many TODO comments in the code base so it's really easy to lose track of them and to forget them.

Comment (kulyk) [reply frontend/src/metabase/components/AccordionList.jsx:52]: That's actually a very good question. We can also mark those issues with a "good first issue" label, so if someone wants to contribute, it might be a good start

**Review by nemanjaglumac — APPROVED** [review]
Left a comment about a comment :D
I'm looking forward to more of these sweet, short fixes and to seeing less and less errors/warnings in the console.

File: frontend/src/metabase/components/AccordionList.jsx (hunk 1 above)
Comment (gusaiani) [reply frontend/src/metabase/components/AccordionList.jsx:52]: @nemanjaglumac @kulyk 👍, I also like the idea of labeling these "Good first issue".

In this case I was investigating a bug, saw this, fixed it and filed the issue at the same time.

I think, with time, I'll be able to pinpoint and fix buxes more easily than now.
Until then, it's a lot of reading code.
It seems (to me) helpful to clean up obvious things around the issue, should make future changes gradually cheaper to implement.

Comment (nemanjaglumac) [reply frontend/src/metabase/components/AccordionList.jsx:52]: @gusaiani there is still a chance to open a follow up issue that can be labeled "Good first issue". The issue should be concerned about this TODO and the follow-up action needed around it.
That way we don't forget to do it.
