### PR TITLE
Fix 28368: null parameters for implicit actions in dashboards

### LINKED ISSUE #28368: Implicit action parameters are null in `GET /api/dashboard/:id` response
Implicit actions don't work in dashboards when the model they are built from isn't present in the dashboard.

Steps to reproduce:
1. Create a model and create implicit actions
2. Add the "Delete" action for the model in a new dashboard, with no other dashcards. Save and click on the "Delete" button. You'll see there is no ID parameter field in the popup. This is the bug.
image
3. Add the model to the dashboard, and the ID parameter field appears, as it should have been all along: (note the screenshot is from a different dashboard to the first, but the popup is the same)
image

### PR DESCRIPTION
**Pull request by calherries**
This PR fixes #28368

Previously, hydrated implicit actions for dashcards have null parameters if the action's model isn't in another dashcard on the dashboard.

The fix is to remove the assumption that an dashcard with an action has `card_id` equal to the action's model id. This assumption was implicitly made by the BE, including in the tests. But the FE doesn't satisfy this assumption when the dashcard is created. Dashcards are created by calls to `POST /api/dashboard/%s/cards`, and when the dashcard has an action, the `card_id` is null in the request.

The problem went undetected on the BE because the tests for dashcard actions expect the card_id field for action dashcards on the POST /api/dashboard/:id/cards request to include the model id of the action. But the FE doesn't satisfy this assumption.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28369)

### CODE REVIEW

File: src/metabase/models/action.clj [hunk 1]
```diff
@@ -250,7 +250,7 @@
   "Hydrates action from DashboardCard."
   [dashcards]
   (let [actions-by-id (when-let [action-ids (seq (keep :action_id dashcards))]
-                        (m/index-by :id (select-actions (map :card dashcards) :id [:in action-ids])))]
```
Comment (calherries) [inline src/metabase/models/action.clj:253]: This might have worked if the `:card` of an implicit action dashcard contained the card of the action. But it doesn't. The `card_id` for implicit actions is `null` and the hydrated `card` is `{query_average_duration: null}`.

File: src/metabase/models/action.clj [hunk 2]
```diff
@@ -250,7 +250,7 @@
   "Hydrates action from DashboardCard."
```
Comment (qnkhuat) [inline src/metabase/models/action.clj:250]:
```suggestion
  "Hydrates action from DashboardCards."
```

File: src/metabase/models/action.clj (hunk 1 above)
Comment (qnkhuat) [reply src/metabase/models/action.clj:253]: should this comment be reflected in the code?

File: src/metabase/models/action.clj (hunk 2 above)
Comment (qnkhuat) [inline src/metabase/models/action.clj:250]: does it still makes sense for this hydration to be under dashcard tho? should it be in dashboard ns instead?

**Review by qnkhuat — APPROVED** [review]
some comments to suggest putting a comment into code and moving the hydration method to dashboard ns.

It's not critical so up to you if you want to address it.

File: src/metabase/models/action.clj (hunk 1 above)
Comment (calherries) [reply src/metabase/models/action.clj:253]: I've asked the question on [slack](https://metaboat.slack.com/archives/CKZEMT1MJ/p1676623946326239). I'll make a follow up PR
