### PR TITLE
Fix invalid API request fired on chart legend click

### LINKED ISSUE #43077: Invalid API request fired when clicking chart legend item
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/19c5a257-b2f4-4e13-a87f-7f7c214d6d6d

### To Reproduce

1. Create a new question based on Orders table
2. Add Count aggregation
3. Add Sum of Total aggregation
4. Breakout by Created At: Month
5. Visualize
6. Observe network tab in developer tools
7. Click any item in chart legend

GET `/api/card/undefined` request is fired

### Expected behavior

No API request should be fired

### Information about your Metabase installation

master, c9f2ffe99e

### Severity

P2

### PR DESCRIPTION
**Pull request by JesseSDevaney**
- Closes: https://github.com/metabase/metabase/issues/43077

---
**Demo**

https://github.com/metabase/metabase/assets/22608765/e7f7f1e8-7462-4880-9934-0c18dfdedb43

---
**Acceptance Criteria**
- [ ] Chart legends exhibit the same user-visible behaviors as before
- [ ] Chart legends with multiple aggregations no longer fire invalid API requests when clicked
- [ ] E2E test added to validate and enforce the desired behavior

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts [hunk 1]
```diff
@@ -322,16 +323,12 @@ export const useChartEvents = (
         settings,
       };
 
-      if (
-        !areMultipleCards &&
-        hasBreakout &&
-        visualizationIsClickable(clickData)
-      ) {
+      if (hasBreakout && visualizationIsClickable(clickData)) {
```
Comment (JesseSDevaney) [inline frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts:326]: Removing unnecessary boolean in conditional:

Since the `areMultipleCards` check is already occurring on line 304/305, we know that one we reach this check `!areMultipleCards` is true, since we passed the conditional above without exiting the function.

File: frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts [hunk 2]
```diff
@@ -322,16 +323,12 @@ export const useChartEvents = (
...
         onVisualizationClick({
           ...clickData,
           element: event.currentTarget,
         });
-      } else {
+      } else if (isDashboard) {
```
Comment (JesseSDevaney) [inline frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts:331]: We have to add this `isDashboard` check to the else conditional, or else that function will be fired in the query builder, which is the thing that is causing the invalid request, since `seriesModel.cardId` is undefined in the query builder

File: frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
Comment (JesseSDevaney) [inline frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx:1]: Fixed Row Charts in the same vein as the Cartesian Charts fix

**Review by alxnddr — APPROVED** [review]
