### PR TITLE
fix: sql edit tools creating new questions instead of editing

### LINKED ISSUE #68991: “Have Metabot fix it” resets SQL variable configuration
### Describe the bug

When using Metabot to fix the SQL syntax of a native question that contains variables, the SQL variables lose their previously configured settings after the fix is found and applied.

### To Reproduce

1. Create a native SQL question with some SQL variables, make sure to change the variable configuration (widget label, variable type, etc.)
2. Save the question.
3. Edit the question and introduce an SQL error. Run the query so the error appears.
4. Click Have Metabot fix it.
5. All variables reset to their default unconfigured state

### Expected behavior

SQL variable settings should be preserved exactly as they were before the fix.{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2026-01-27",
      "tag": "v1.58.4",
      "hash": "712da34"
    },
    "settings": {
      "report-timezone": "Australia/Melbourne"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2026-01-27",
      "tag": "v1.58.4",
      "hash": "712da34"
    },
    "settings": {
      "report-timezone": "Australia/Melbourne"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Annoying

### Additional context

_No response_

### LINKED ISSUE #68992: “Have Metabot fix it” - fixed question is treated as new on Save
### Describe the bug

After using **Have Metabot fix it** on an existing native question, saving behaves as if the question was created from scratch. Metabase no longer offers the option to save changes and replace the original question.

### To Reproduce

1. Create a native SQL question. Save it.
2. Edit the question and introduce an error. Run it so it appears.
3. Click **Have Metabot fix it.**
4. The questions title becomes New question and when attempting to Save, there is no option to replace the original question.

### Expected behavior

The question should be treated as an edited version of the original and the usual Save as new / Replace original question choice should be offered on Save.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2026-01-27",
      "tag": "v1.58.4",
      "hash": "712da34"
    },
    "settings": {
      "report-timezone": "Australia/Melbourne"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by undrfined**
closes #68992
 closes #68991
Closes [BOT-922: “Have Metabot fix it” resets SQL variable configuration](https://linear.app/metabase/issue/BOT-922/have-metabot-fix-it-resets-sql-variable-configuration)

### Description

Edit tools were creating new questions instead of editing existing ones.

### How to verify

1. Create new native query
2. Ask metabot (omnibot) to edit the SQL.

### Demo

https://github.com/user-attachments/assets/585e1982-9791-40e5-af88-34ec78075a7d

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [x] ~~If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)~~

### CODE REVIEW

**Comment by undrfined** [comment]
Moved back to draft to verify a usecase where metabot needs to edit a query that user is not viewing.
Also verify if it's able to create a new query instead of editing existing one

**Comment by undrfined** [comment]
nvm metabot is not able to edit anything that is not currently in user_is_viewing context. Creation works fine

File: frontend/src/metabase/metabot/components/MetabotInlineSQLPrompt/useInlineSQLPrompt.tsx [hunk 1]
```diff
@@ -40,17 +40,16 @@ function useRegisterCodeEditorMetabotContext(
   databaseId: DatabaseId | null,
   bufferId: string,
 ): void {
-  useRegisterMetabotContextProvider(
-    async () => ({
+  useRegisterMetabotContextProvider(async () => {
```
Comment (sloansparger) [inline frontend/src/metabase/metabot/components/MetabotInlineSQLPrompt/useInlineSQLPrompt.tsx]: boosting your diff stats, huh? 🤨 /s

File: enterprise/frontend/src/metabase-enterprise/metabot/tests/query-builder-code-edit.unit.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+    setupEnterprisePlugins();
+    Object.assign(PLUGIN_METABOT, {
+      useMetabotSQLSuggestion: useMetabotSQLSuggestionEE,
+    });
+    mockedAiStreamingQuery.mockReset();
+    jest.mocked(findMatchingInflightAiStreamingRequests).mockReturnValue([]);
+  });
+
+  it("updates the proposed SQL in query builder when omnibot streams a code_edit", async () => {
+    mockedAiStreamingQuery.mockImplementation(async (_request, callbacks) => {
```
Comment (sloansparger) [inline enterprise/frontend/src/metabase-enterprise/metabot/tests/query-builder-code-edit.unit.spec.tsx]: mocking implementations make future refactors a PITA. as a policy let's avoid doing this in our unit tests where possible.

i think this test would get a lot simpler if you rendered the `<Metabot />` component alongside what you have. `enterprise/frontend/src/metabase-enterprise/metabot/tests/utils.tsx`'s `setup` function takes `ui` option, which would let you compose the two.

sending a message w/ would get much easier, and you could register context by using `useRegisterMetabotContextProvider`

File: enterprise/frontend/src/metabase-enterprise/metabot/tests/actions.unit.spec.ts [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+  });
+
+describe("sendAgentRequest", () => {
+  beforeEach(() => {
+    mockedAiStreamingQuery.mockReset();
+    jest.mocked(findMatchingInflightAiStreamingRequests).mockReturnValue([]);
+  });
+
+  it("opens the QB code editor when receiving a qb code edit", async () => {
+    mockedAiStreamingQuery.mockImplementation(async (_request, callbacks) => {
```
Comment (sloansparger) [inline enterprise/frontend/src/metabase-enterprise/metabot/tests/actions.unit.spec.ts]: same comments at the other file. this is brittle, so let's rethink it.

**Review by sloansparger — CHANGES_REQUESTED** [review]

File: enterprise/backend/src/metabase_enterprise/metabot_v3/agent/profiles.clj [hunk 4]
```diff
@@ -110,8 +110,8 @@
   :tools               [#'agent-tools/sql-search-tool
                         #'agent-tools/read-resource-tool
                         #'agent-tools/create-sql-query-code-edit-tool
```
Comment (appleby) [inline enterprise/backend/src/metabase_enterprise/metabot_v3/agent/profiles.clj]: why did we consolidate `edit` and `replace` tools, but not `create`?

File: src/metabase/metabot/tools/sql.clj [hunk 5]
```diff
@@ -152,15 +152,16 @@
...
         (let [structured  (assoc action-result :result-type :query)
               instr       (instructions/edit-sql-query-instructions-for query-id)
-              results-url (streaming/query->question-url query)]
+              results-url (streaming/query->question-url query)
+              buffer-id  (first-code-editor-buffer-id)]
           {:output (format-query-output structured instr)
            :structured-output structured
            :instructions instr
-           :data-parts [(streaming/navigate-to-part results-url)]})
+           :data-parts [(if buffer-id (code-edit-part buffer-id query-content) (streaming/navigate-to-part results-url))]})
```
Comment (appleby) [inline src/metabase/metabot/tools/sql.clj:174]: I guess this is ok, just double checking this is what we want. IIUC, previously whether we send `code_edit` vs `navigate_to` was controlled by the profile: 

* sql profile -> always `code_edit` part
* everything else -> always `navigate_to` part
 
And if sql profile was selected and `code_editor` was missing from `user_is_viewing` you'd get an explicit error message.

After this change:
* if `code_editor` is present in `user_is_viewing` -> `code_edit` part
* otherwise -> `navigate_to` part

Looking at the tests below, I guess that is the desired behavior and we now expect to get a `code_edit` part even for internal / omnibot profile, assuming you've got the sql editor open? ~~What about transforms codegen in data studio?~~ edit: forgot transforms have their own set of tools

**Review by appleby — COMMENTED** [review]
BE changes LGTM, just a (nonblocking) question about expected behavior for the consolidated sql tools

File: enterprise/backend/src/metabase_enterprise/metabot_v3/agent/profiles.clj (hunk 4 above)
Comment (undrfined) [reply enterprise/backend/src/metabase_enterprise/metabot_v3/agent/profiles.clj]: I kept `create` separate because it still encodes two different intents: the SQL profile should create into the active editor buffer, while internal/omnibot should create a new question and navigate to it. `edit` and `replace` both target an existing query, so those were safe to unify behind the `code_editor`-present fallback.

**Review by sloansparger — APPROVED** [review]
approving FE

File: src/metabase/metabot/tools/sql.clj (hunk 5 above)
Comment (undrfined) [reply src/metabase/metabot/tools/sql.clj:174]: Yeah, that's the desired behavior
