### PR TITLE
fix replacement for plural message

### LINKED ISSUE #15694: Some places shows `{0}` placeholder instead of expected value
After upgrade from 0.38.x to 0.39.0 I've noticed problems with filters on dashboards that are stored as a multiple choice.
Instead of number of choosen values system displays placeholder like {0}.

**To Reproduce**
You need to have saved dashboard with multiple default values. (you cannot create new because of bug #15689)
If you have one, than you need to display it... and that's it. 

**Expected behavior**
I'm expecting to see number of choosen default values.
{0} wybranych -> 2 wybranych
bad                 -> expected

**Screenshots**
bug

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Edge 88.0.705.50 
- Your operating system: Windows 10 20H2
- Your databases: Oracle 19c
- Metabase version: 0.39.0
- Metabase hosting environment: Redhat Linux. straight from the .jar
- Metabase internal database: Postgres

**Severity**
Looks bad... but i can live with it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by yo-iida**
Fix https://github.com/metabase/metabase/issues/15694

After this change, run the following command.
`./bin/i18n/build-translation-resources`

I confirmed the fix for plural placeholders in several languages.

スクリーンショット 2021-05-11 2 12 35
スクリーンショット 2021-05-11 2 24 17
スクリーンショット 2021-05-11 2 25 35

-----

###### Before submitting the PR, please make sure you do the following

- [x] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`
- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### CODE REVIEW

File: test/metabase/api/login_history_test.clj [hunk 1]
```diff
@@ -58,7 +58,7 @@
                  :device_description "Browser (Chrome/Windows)"
                  :ip_address         "185.233.100.23"
                  :active             true
-                 :location           "Begles, Nouvelle-Aquitaine, France"
+                 :location           "Talence, Nouvelle-Aquitaine, France"
```
Comment (yo-iida) [inline test/metabase/api/login_history_test.clj:61]: This change is to fix https://app.circleci.com/pipelines/github/metabase/metabase/16017/workflows/4e935ffe-050c-407c-9d25-c9e0998d9ae7/jobs/616408

**Comment by yo-iida** [comment]
The test that is currently failing seems to be due to insufficient settings of environment variables, etc.
Do I need to fix this on my end?
スクリーンショット 2021-05-11 9 28 11
スクリーンショット 2021-05-11 9 31 17

**Comment by flamber** [comment]
Hi @yo-iida Thank you for the PR. Ignore those failing tests - our CI currently doesn't handle third-party commits.

**Review by camsaul — APPROVED** [review]
Cool, this LGTM. We should probably backport the fix to the release-x.39.x branch as well

**Comment by rlotun** [comment]
Thank you for your contribution!
