### PR TITLE
Multi Series Dashcards Render with Filters Applied To All Series

### LINKED ISSUE #39083: Multi-question cards filter data incorrectly in email / Slack dashboard subscriptions
### Describe the bug

When a card has multiple questions added filters set in the dashboard subscription will only filter the first series of the card.

### To Reproduce

1. Create a dashboard
2. Add a question
3. Add another question to the first card
4. Set up a dashboard filter and wire it to both questions of the first card
5. Set up an email or Slack subscription for the dashboard, set a filter value, and send a test email
6. (!) Only one of the series will be filtered

Dashboard filter with unfiltered data:
image

Output of email subscription when data is filtered (should only return for 1 month for both series)
image

### Expected behavior

Similarly as it works on a dashboard, the filter should be applied to each series of the card

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.209-198.812.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "bigquery-cloud-sdk",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-06",
      "tag": "v1.48.5",
      "hash": "dab12cf"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

### Severity

P1 (correctness)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes: #39083

Multi-series dashcards now properly render when a subscription is set up with filters that impact the values of each card in the multi-series card.

image

### CODE REVIEW

File: src/metabase/pulse/util.clj [hunk 1]
```diff
@@ -45,24 +46,49 @@
...
-          ;; NOTE/TODO - dashcard-or-id is nil with multiple time series
-          card    (t2/select-one :model/Card :id card-id, :archived false)]
-      [(execute-card {:creator_id (:creator_id card)} (:id card))])))
+(defn execute-dashboard-subscription-card
+  "Returns subscription result for a card.
+
+  This function should be executed under pulse's creator permissions."
+  [dashcard parameters]
+  (let [{card-id      :card_id
+         dashboard-id :dashboard_id} dashcard]
```
Comment (qnkhuat) [inline src/metabase/pulse/util.clj:66]: I think we could pack this these let with the inner let

File: src/metabase/pulse/render/body.clj [hunk 2]
```diff
@@ -528,37 +527,35 @@
...
 ;; As of 2024-03-21, isomorphic chart types include: line, area, bar (LAB), and trend charts
 ;; Because this effort began with LAB charts, this method is written to handle multi-series dashcards.
 ;; Trend charts were added more recently and will not have multi-series.
-;; Despite this, the function `pu/execute-multi-card` will still correctly execute dashcards.
-;; This conditional is here to cover the case of trend charts in Alerts (not subscriptions). Alerts
-;; exist on Questions and thus have no associated dashcard, which causes `pu/execute-multi-card` to fail.
 (mu/defmethod render :javascript_visualization :- formatter/RenderedPulseCard
   [_chart-type render-type _timezone-id card dashcard data]
-  (let [combined-cards-results (if dashcard
-                                 (pu/execute-multi-card card dashcard)
```
Comment (qnkhuat) [inline src/metabase/pulse/render/body.clj:543]: awesome, I love that you moved the execution up the stack. We basically executed a dashcard twice before! so this will improve the performance somewhat.

File: src/metabase/pulse/util.clj [hunk 3]
```diff
@@ -45,24 +46,49 @@
...
+    (try
+      (let [card           (t2/select-one :model/Card :id card-id)
+            multi-cards    (dashboard-card/dashcard->multi-cards dashcard)
+            result-fn      (fn [card-id]
+                             {:card     (if (= card-id (:id card))
+                                          card
+                                          (t2/select-one :model/Card :id card-id))
+                              :dashcard dashcard
+                              :type     :card
```
Comment (qnkhuat) [inline src/metabase/pulse/util.clj:75]: I'd not die on this hill, but what about introducing a new type of `multi-cards` so we could differentiate between a single card and a card that has multi-series results?

I don't like the fact that we're assuming a card and a multi-card is the samething.

File: src/metabase/pulse/render/body.clj [hunk 4]
```diff
@@ -528,37 +527,35 @@
...
-                                  (fn [c d] {:card c :data d}))
-                                 (cond-> (map :card combined-cards-results)
-                                   dashcard (conj card))
-                                 (cond-> (map #(get-in % [:result :data]) combined-cards-results)
-                                   dashcard (conj data))))
-        dashcard-viz-settings  (get dashcard :visualization_settings)
-        {rendered-type :type content :content} (js-svg/javascript-visualization cards-with-data dashcard-viz-settings)]
+  (let [series-cards-results                   (:series-results dashcard)
+        cards-with-data                        (->> series-cards-results
+                                                    (map result-k->data-k)
```
Comment (qnkhuat) [inline src/metabase/pulse/render/body.clj:547]:
```suggestion
                                                    (map #(clojure.set/rename-keys % {:result :data}))
```
this should do the same thing

File: src/metabase/pulse/util.clj (hunk 3 above)
Comment (adam-james-v) [reply src/metabase/pulse/util.clj:75]: Yea, I've been thinking about that too. I'd like to merge this PR first, though.

I'm also working on multi-series cards csv/xlsx downloads/subscription attachments, where it will probably be much better to have mulit-cards as their own thing, like you suggest. 

So, for this PR, I think no, but in a next step, yea, almost certainly a good idea.

File: src/metabase/pulse/render/body.clj (hunk 4 above)
Comment (adam-james-v) [reply src/metabase/pulse/render/body.clj]: Ah, turns out I do need to use a function here to achieve what I need: The :data key inside the result key of the card passed in is what we need, we don't want to just rename :result to :data because that results in this:
`{:data {:data {...}}` when what we actually want is: `{:data {...}}`

**Review by qnkhuat — APPROVED** [review]
nice!
