### PR TITLE
Invalidate sandbox FieldValues cache on question change

### LINKED ISSUE #25411: Changing Saved Question used as Custom View for Sandboxing doesn't update the Dashboard Drop down Filter with new list but keeps the old one
**Describe the bug**
When you have a Filter with a drop down in a dashboard that is used against a sandboxed table it should show the distinct rows available to filter. When you change the query used for sandboxing and filter for a different set of rows. The filter keeps the old values rather than the new. It takes a lot of time to update, with the only current workaround being that of pressing the Database option of `Discard saved field values` 

**To Reproduce**

1. Create a Group:
image

2. Create a User & Assign it to this Group

3. create a question on the ORDERS Table, Select all columns AND filter where product_id = 1, 2, 3) and use it for sandboxing on group 1:

image

image

4. Create a simple dashboard with a Filter on the Product_ID against the Orders Table:

image

5. Login with the user and check the dashboard (notice the 1, 2, 3 options):

image

6. Go back to the question created for sandboxing permission and this time change it to 4,5,6 ... the user will still be seeing the previous options. Even if they are selected no results come out since the sandboxing is still working:

image

image

7. You either wait until Metabase updates on it's own, may take a couple of min to hours or go to Admin -> Database -> Discard saved field values and you will see the new available options

image

**Expected behavior**
Metabase automatically detects that the sandboxing question was updated and in turn it would require discarding the values automatically , so it gets new values

**Information about your Metabase Installation:**

- Your browser and the version: Chrome
- Your operating system: OS X 
- Your databases: H2 (Sample DatabasE)
- Metabase version: 44.2
- Metabase hosting environment: H2

### PR DESCRIPTION
**Pull request by metamben**
Fixes #25411.

This PR includes the last modification date of the question (`report_card.update_at`) in the list of fields used for checking for validating the cache.

As it stands, this PR creates multiple `FieldValues` entries of type `:sandbox` with different `hash_key`s for the same field which, according to #668, might be wrong.

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/sandbox/models/params/field_values_test.clj [hunk 1]
```diff
@@ -45,7 +47,23 @@
...
              :sandbox
              (db/select-one Field :id (mt/id :categories :id)))
-            (is (= 1 (db/count FieldValues :field_id categories-id :type fv-type)))))))
+            (is (= 1 (db/count FieldValues :field_id categories-id :type fv-type))))
+
+          (testing "after changing the question, should create new FieldValues"
+            (let [new-query (mt/mbql-query categories
+                                           {:filter [:and [:> $id 1] [:< $id 4]]})]
+              ;; sleeping should ensure that updated_at changes
+              (Thread/sleep 1000)
```
Comment (metamben) [inline enterprise/backend/test/metabase_enterprise/sandbox/models/params/field_values_test.clj:56]: MySQL seems to have second granularity, which makes this test somewhat slow. This also means that if the sandboxed user uses the sandboxed query within a second after the modification of the query, they will. get wrong filter values. I don't think this is a problem in practice.

Comment (camsaul) [reply enterprise/backend/test/metabase_enterprise/sandbox/models/params/field_values_test.clj:56]: Yeah, `timestamp` in MySQL is second granularity by default. You should just add a migration to change that column to `timestamp(3)` (millisecond) or `timestamp(6)` (nanosecond) so we don't have to worry about this in the future. We've done it a bunch of times in the past to fix the same situation with other columns, so there's prior art in the migration file that you could refer to

Comment (metamben) [reply enterprise/backend/test/metabase_enterprise/sandbox/models/params/field_values_test.clj:56]: I suppose `timestamp_type` (microseconds) is the right type to set. I'll update the PR.

File: resources/migrations/000_migrations.yaml [hunk 2]
```diff
@@ -13990,6 +13990,21 @@ databaseChangeLog:
...
+        - modifyDataType:
+            tableName: report_card
+            columnName: updated_at
+            newDataType: ${timestamp_type}
+      rollback:
+        - modifyDataType:
+            tableName: report_card
+            columnName: updated_at
+            newDataType: DATETIME
+
```
Comment (metamben) [inline resources/migrations/000_migrations.yaml:14007]: Should this change be constrained to mysql and mariadb?

Comment (camsaul) [reply resources/migrations/000_migrations.yaml:14007]: I think it makes sense for Postgres and H2 too, since `${timestamp_type}` is `TIMESTAMP FOR TIME ZONE` for those, which is definitely preferrable to `DATETIME` for storing timestamps

**Review by camsaul — APPROVED** [review]
