### PR TITLE
Use mantine popover in entityMenu

### LINKED ISSUE #37343: Item dropdown menu overflows the viewport in Collections page
### Describe the bug

image

### To Reproduce

1. Go to https://stats.metabase.com/collection/616
2. Open menu for any of the 2 items on the list at the bottom of the page

Can't see all the options in the dropdown menu. Can't scroll to see all the options.

### Expected behavior

Dropdown opens up if there's not enough space for it in the viewport below the trigger button

### Information about your Metabase installation

master, v48, a2d1fc3

### Severity

P2

### PR DESCRIPTION
**Pull request by iethree**
resolves https://github.com/metabase/metabase/issues/37343

>[!warning]
> this is a risky change to a component that appears in a lot of places in the app

### Description

Looking into fixing #37343, I didn't really want to muck around hacking a fix into the older of our two deprecated popover implementations. Instead, I updated the component that uses the popover (EntityMenu) to use Mantine's popover.  

I also tried totally rewriting it to use Mantine's Menu, but I got mired in quite a few edge cases (that component is used in a lot of places and has lots of props). I think it's best to do the smallest change necessary to use this new popover implementation.

popoverScroll

**Bonuses 🥳**
- this popover actually updates when you scroll, so it never overflows the viewport
- there's several snazzy animation options
- we don't have to use react-motion (a rarely used or updated library) anymore in this component.

### How to verify

click on the context menu for collection items near the bottom of your screen, see that it never overflows the viewport

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/components/EntityMenu/EntityMenu.jsx [hunk 1]
```diff
@@ -52,148 +45,97 @@ class EntityMenu extends Component {
...
-          hasBackground={false}
-          horizontalAttachments={horizontalAttachments}
-          targetOffsetY={targetOffsetY || 0}
-          ignoreTrigger
-        >
-          {/* Note: @kdoh 10/12/17
-           * React Motion has a flow type problem with children see
-           * https://github.com/chenglou/react-motion/issues/375
-           * TODO This can be removed if we upgrade to flow 0.53 and react-motion >= 0.5.1
-           */}
```
Comment (iethree) [inline frontend/src/metabase/components/EntityMenu/EntityMenu.jsx:108]: Let's pour one out for this 6-year-old comment 🫡

File: frontend/src/metabase/components/EntityMenu/EntityMenu.jsx [hunk 2]
```diff
@@ -52,148 +45,97 @@ class EntityMenu extends Component {
...
-      targetOffsetY,
       triggerAriaLabel,
       tooltipPlacement,
     } = this.props;
     const { open, menuItemContent } = this.state;
     return (
-      <Container
+      <Popover
         className={cx(className, open ? openClassNames : closedClassNames)}
-        open={open}
```
Comment (iethree) [inline frontend/src/metabase/components/EntityMenu/EntityMenu.jsx:77]: this _seems_ to work correctly in an uncontrolled state, merely tracking the `open` state for the sake of other visual changes (like showing a different icon when open)

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailHeader.tsx [hunk 3]
```diff
@@ -73,7 +73,6 @@ export function ObjectDetailHeader({
 
           {actionItems.length > 0 && (
             <EntityMenu
-              horizontalAttachments={["right", "left"]}
```
Comment (iethree) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailHeader.tsx:76]: this was the only usage of the horizontalAttachments prop, and it didn't seem to do much here, so I removed it.

File: frontend/src/metabase/components/EntityMenu/EntityMenu.jsx [hunk 4]
```diff
@@ -52,148 +45,97 @@ class EntityMenu extends Component {
...
       triggerProps,
       className,
       openClassNames,
       closedClassNames,
-      horizontalAttachments,
       minWidth,
       tooltip,
       trigger,
       renderTrigger,
-      targetOffsetY,
```
Comment (iethree) [inline frontend/src/metabase/components/EntityMenu/EntityMenu.jsx:69]: this prop wasn't ever used

File: frontend/src/metabase/components/EntityMenu/EntityMenu.jsx [hunk 5]
```diff
@@ -1,18 +1,11 @@
 /* eslint-disable react/prop-types */
 import { createRef, Component } from "react";
-import { Motion, spring } from "react-motion";
 import cx from "classnames";
 
-import { isReducedMotionPreferred } from "metabase/lib/dom";
```
Comment (iethree) [inline frontend/src/metabase/components/EntityMenu/EntityMenu.jsx:6]: we don't need this because Mantine obeys prefers-reduced-motion out of the box 🪄

File: frontend/src/metabase/components/EntityMenu/EntityMenu.jsx (hunk 2 above)
Comment (iethree) [reply frontend/src/metabase/components/EntityMenu/EntityMenu.jsx:77]: this was false. I made it controlled. 😁

**Review by kulyk — APPROVED** [review]
Wooo! Thank you!
