### PR TITLE
Do not bin relation fields even if they have fingerprints

### LINKED ISSUE #17768: If Entity Key fields are fingerprinted, then they show binning options in GUI
**Describe the bug**
If Entity Key (PK) fields are fingerprinted at some point (by accidentally setting the wrong field type, or field type was detected incorrect during initial sync), then they show binning options in GUI.
Regression since 0.40.0 - feels like a frontend issue more than sync.

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Reviews > ID :gear: 
2. Change type to "Category" and filtering "A list of all values"
3. Admin > Databases > Sample Dataset > Sync database schema now
4. Admin > Data Model > Sample Dataset > Reviews > ID :gear: > change back to "Entity Key" and "Plain input box"
5. (browser refresh) Custom question > Sample Dataset > Reviews > open Group by
image

**Expected behavior**
Should not show binning for Entity Key (or granularity options for FK, which would also fix #16787).
Of course, this might conflict with other issues like #13098.

**Information about your Metabase Installation:**
Tested 0.39.5 thru 0.40.3.1 and master `ceb0af3` - regression since 0.40.0

**Severity**
P2 contender, since it is very difficult to get rid of fingerprints and making it annoying to group by an ID - and there might be other consequences from this too.

### PR DESCRIPTION
**Pull request by pawit-metabase**
Fixes #17768

### CODE REVIEW

File: test/metabase/api/table_test.clj [hunk 1]
```diff
@@ -664,6 +664,13 @@
                      ["field" nil {:binning {:strategy "num-bins", :num-bins 10}}]}
                    (extract-dimension-options response "price"))))))
 
+      (testing "Relationship fields should not have binning options"
+        (let [fingerprint (db/select-one-field :fingerprint Field {:id (mt/id :venues :price)})]
```
Comment (camsaul) [inline test/metabase/api/table_test.clj:668]: This query doesn't do what you think it's doing. You need to write either

```clj
(db/select-one-field :fingerprint Field :id (mt/id :venues :price))
```

or

```clj
(db/select-one-field :fingerprint Field {:where [:=:id (mt/id :venues :price)]})
```

Maps passed to Toucan function are just treated as raw HoneySQL. `:id` in a HoneySQL map just gets ignored

File: test/metabase/api/table_test.clj [hunk 2]
```diff
@@ -664,6 +664,13 @@
...
+          (mt/with-temp-vals-in-db Field (mt/id :venues :id) {:fingerprint fingerprint}
+           (let [response (mt/user-http-request :rasta :get 200 (format "table/%d/query_metadata" (mt/id :venues)))]
```
Comment (camsaul) [inline test/metabase/api/table_test.clj:670]: this should be indented two spaces

File: test/metabase/api/table_test.clj (hunk 1 above)
Comment (camsaul) [reply test/metabase/api/table_test.clj:668]: Can you add an assertion like  

```clj
(is (seq (extra-dimension-options response "id")))
```

_before_ adding the fingerprint information? So the whole test looks like

1. before changing anything
   1. test that dimension options get returned
1. add Fingerprint info
   1. test that dimension options no longer get returned

otherwise for all we know the change you made adding `:fingerprint` info had nothing to do with anything and the dimension options wouldn't have been returned either way

**Review by camsaul — CHANGES_REQUESTED** [review]
A couple of small things:

1. Need to make a small tweak to the `db/select-one-field` call
2. Let's add an extra test to make sure `extra-dimension-options` were being returned in the first place and that the change we made causes them to no longer be returned (as opposed to them not being returned regardless of this change)
3. Minor formatting notes

**Comment by pawit-metabase** [comment]
> Need to make a small tweak to the db/select-one-field call 

It's gone now after reworking the test.

However, I got it from the `Numeric fields without min/max values should not have binning options` test below. Let me fix it there.

> Let's add an extra test to make sure extra-dimension-options were being returned in the first place and that the change we made causes them to no longer be returned (as opposed to them not being returned regardless of this change)

With or without the fingerprint, the result should be the same - no dimension options. The bug was that dimension options were being returned if fingerprint information is present when it shouldn't be.

I've changed the test to use the `price` column instead. The "base" case is be provided by the `Number columns without a semantic type should use "num-bins"` test immediately above. Does that work?

> Minor formatting notes

Fixed

**Review by camsaul — APPROVED** [review]
