### PR TITLE
Fix issue with moment locale not working

### LINKED ISSUE #8964: Calendar — Missing translations
The Callendar is not translated on charts and tables. That means months name and days. The default setting it's to print name of the month. I know that default format can be globally changed in settings. But still it supposed to be translated.

When editing a table.
2018-11-18 15_06_20-pytanie metabase

And also functions related to sorting by data on charts.

I use Polish translation.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #8964

Seems like we include moment locales in our bundle already as you can see the files in devtools with source maps but for whatever reason doing `moment.locale(momentLocale)` alone does not work. Adding an additional `require` for the specific locale file fixes things. I'm... not sure why.

Screen Shot 2021-11-12 at 1 42 58 PM

### CODE REVIEW

File: frontend/src/metabase/lib/i18n.js [hunk 1]
```diff
@@ -74,10 +74,30 @@ export function setLocalization(translationsObject) {
...
+}
+
+function mapToMomentLocale(locale) {
+  switch (locale) {
+    case "zh-Hans":
+      return "zh-cn";
+    case "zh-TW":
+      return "zh-tw";
+    default:
+      return locale;
```
Comment (flamber) [inline frontend/src/metabase/lib/i18n.js:97]: Couldn't the default just be to lowercase, since that seems like the Moment convention?

**Review by flamber — APPROVED** [review]
Seems to work great in all locales

File: frontend/src/metabase/lib/i18n.js (hunk 1 above)
Comment (daltojohnso) [reply frontend/src/metabase/lib/i18n.js]: Yeah, good idea.

**Review by flamber — APPROVED** [review]

**Review by ranquild — APPROVED** [review]
