### PR TITLE
Serdes v2 export import logs

### LINKED ISSUE #26859: The export and import commands should generate useful logs
# Context
Both `dump` and `load` processes may take a while to complete and they can also fail.
Currently, both commands don't generate logs. If something fails, it is hard to debug.

# Proposal
Add logs to `export` and `import` processes. The solution depends on what is available when running the command, the following bullets are ideas of what we could generate:
- Log what is being processed at that moment. We need to define the granularity here. For content, `collection` looks a good idea, for data model we may use `table`. Besides these, we also have the `settings.yaml` file.
- Export some kind of progress awareness. Something like table 23/500 or collection 1/25. A total progress bar + ETA is desirable but not required.

### PR DESCRIPTION
**Pull request by john-metabase**
Resolves #26859

Adds helpful logs for export like:

```
...
2023-02-24 19:01:12,463 INFO storage.yaml :: Storing entity Database BigQuery > Schema dev > Table baseball_games > Field hitterFirstName
2023-02-24 19:01:12,463 INFO storage.yaml :: Storing entity Database MySQL > Table ndb_binlog_index > Field orig_server_id
2023-02-24 19:01:12,464 INFO storage.yaml :: Storing entity Database MySQL > Table slave_relay_log_info > Field Master_log_name
2023-02-24 19:01:12,464 INFO storage.yaml :: Storing entity Database Athena > Schema athena-dev > Table products > Field price
2023-02-24 19:01:12,464 INFO storage.yaml :: Storing entity Database Mongo > Table movies > Field critic
2023-02-24 19:01:12,464 INFO storage.yaml :: Storing entity Database Mongo > Table theaters > Field address
2023-02-24 19:01:12,465 INFO storage.yaml :: Storing entity Database Mongo > Table theaters > Field coordinates
2023-02-24 19:01:12,465 INFO storage.yaml :: Storing entity Database Mongo > Table theaters > Field zipcode
2023-02-24 19:01:12,465 INFO storage.yaml :: Storing entity Database Mongo > Table movies > Field consensus
2023-02-24 19:01:12,466 INFO storage.yaml :: Storing entity Database Mongo > Table movies > Field website
2023-02-24 19:01:12,466 INFO storage.yaml :: Storing entity Database Mongo > Table movies > Field dvd
2023-02-24 19:01:12,467 INFO storage.yaml :: Storing entity Database Mongo > Table theaters > Field street2
2023-02-24 19:01:12,467 INFO storage.yaml :: Storing entity Database Mongo > Table movies > Field viewer
2023-02-24 19:01:12,473 INFO serialization.base :: Extracting FieldValues 1
2023-02-24 19:01:12,475 INFO serialization.base :: Extracting FieldValues 2
2023-02-24 19:01:12,476 INFO serialization.base :: Extracting FieldValues 3
2023-02-24 19:01:12,477 INFO serialization.base :: Extracting FieldValues 4
...
```

And for import:

```
...
2023-02-24 19:02:24,950 INFO ingest.yaml :: Loading Card sriB8K-mGQZSjYkEYnAEI
2023-02-24 19:02:24,966 INFO ingest.yaml :: Loading Database MySQL > Table event > Field body_utf8 > FieldValues 0
2023-02-24 19:02:24,972 INFO ingest.yaml :: Loading Setting premium-embedding-token
2023-02-24 19:02:24,974 INFO ingest.yaml :: Loading Database MySQL > Table user > Field ssl_type
2023-02-24 19:02:24,979 INFO ingest.yaml :: Loading Database BigQuery > Schema dev > Table baseball_games > Field pitcherThrowHand
2023-02-24 19:02:24,985 INFO ingest.yaml :: Loading Database MySQL > Table proc > Field db_collation > FieldValues 0
2023-02-24 19:02:24,986 INFO ingest.yaml :: Loading Database MySQL > Table proc > Field db_collation
2023-02-24 19:02:24,995 INFO ingest.yaml :: Loading Setting ldap-configured?
...
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28589)

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/serialization/cmd.clj [hunk 1]
```diff
@@ -192,15 +192,16 @@
       (v2.extract/extract-metabase opts))))
 
 (defn- v2-dump [path opts]
+  (log/info "Exporting Metabase to" path (u/emoji "🏭 🚛💨"))
```
Comment (john-metabase) [inline enterprise/backend/src/metabase_enterprise/serialization/cmd.clj:195]: Because emoji make everything more fun.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj [hunk 2]
```diff
@@ -1,15 +0,0 @@
-(ns metabase-enterprise.serialization.v2.storage
```
Comment (qnkhuat) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj:1]: I didn't expect a PR changing the logs will change the API, is there context for this?

Comment (john-metabase) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj:1]: It's just an implementation detail. The namespace defined a single multimethod which had one implementation.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/utils/yaml.clj [hunk 3]
```diff
@@ -24,15 +23,20 @@
...
         dirnames    (drop-last base-path)
         ;; Attach the file extension to the last part.
         basename    (str (last base-path) ".yaml")]
-    (apply io/file (:root-dir ctx) (map escape-segment (concat dirnames [basename])))))
+    (map escape-segment (concat dirnames [basename]))))
+
+(defn path-str
+  "Returns a human-readable path string from a sequence of path elements (like in :serdes/meta)"
+  [elements]
+  (->> elements (map (comp (partial str/join "#") (juxt :model :id))) (str/join "/")))
```
Comment (metamben) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/utils/yaml.clj:39]: It might be more readable to define a function formatting a path component for an element.
```clojure
(defn- format-path-component [element]
  (str (:model element) "#" (:id element)))
```

File: src/metabase/models/serialization/base.clj [hunk 4]
```diff
@@ -226,8 +226,13 @@
   {:arglists '([model-name opts instance])}
   (fn [model-name _opts _instance] model-name))
 
+(defn- log-and-extract-one
+  [model opts instance]
+  (log/info "Extracting" (str model "#" (:id instance)))
```
Comment (metamben) [inline src/metabase/models/serialization/base.clj:231]: Could this also use `format-path-component` above?

File: enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj (hunk 2 above)
Comment (john-metabase) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj:1]: I think we can cross that bridge when we come to it. There are lots of opportunities for streamlining code without breaking anything, and while making it easy to change in the future. We don't have to decide on a dispatch approach before we have more than one backend. We may find that there is a better approach when we come to it.

**Comment by john-metabase** [comment]
@metamben the log format is improved, with less formatting logic, and further code reduction.

**Comment by camsaul** [comment]
@john-metabase don't forget to add review requests if this is ready for review

**Comment by john-metabase** [comment]
PR has been rewritten to remove any and all controversial/unrelated refactoring.

File: enterprise/backend/src/metabase_enterprise/serialization/cmd.clj (hunk 1 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/serialization/cmd.clj:195]: Shouldn't this be i18n'ed?

**Review by camsaul — APPROVED** [review]
