### PR TITLE
Fix - Card reference in a native query with a long title does not wrap

### LINKED ISSUE #53171: Card reference in a native query with a long title does not wrap
### Describe the bug

Referencing a card in a native query will insert its entire slug, which doesn't line wrap. This can cause the "learn about your data" sidebar to be cut off awkwardly, or entirely non-visible.

Image

### To Reproduce

1. Create and save a question or model with a long title 
2. Reference it from a native query, using the inline autocomplete to fill in the card title
3. Try to open the sidebar, and see that it gets cut off

### Expected behavior

Slug should probably be truncated at a certain length? Or allowed to wrap in some way.

### Logs

_No response_

### Information about your Metabase installation

```JSON
feb7db2c06
```

### Severity

p3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #53171

### Description

Icons are no longer centered vertically against the text. The "x" button surely is meant to be in the top-right corner of the sidebar, and it looks really weird if the other icons do not follow that pattern.

No backport as it's not in v53.

### How to verify

Browse data reference in native SQL editor (anything: questions, databases, schemas, fields), especially the ones with long names.

### Demo

Long text: [before](https://github.com/user-attachments/assets/3ec399f0-5161-475b-b120-a63e3d1bd6b9) & [after](https://github.com/user-attachments/assets/d043332c-2fbf-4ae2-9c7d-39f9b079e3f1)
Long text no whitespace: [before](https://github.com/user-attachments/assets/36f8db7f-e79e-479a-b8dc-cd3149899b23) & [after](https://github.com/user-attachments/assets/a8dd3940-952d-4626-b024-4da8e1282c24)

### CODE REVIEW

File: e2e/support/helpers/e2e-ui-elements-overflow-helpers.js [hunk 1]
```diff
@@ -34,12 +34,16 @@ export const assertDescendantNotOverflowsContainer = (
     return;
   }
 
-  expect(descendantRect.bottom, `${message} bottom`).to.be.lte(
+  const getMessage = suffix => {
+    return [message, suffix].filter(Boolean).join(" ");
```
Comment (kamilmielnik) [inline e2e/support/helpers/e2e-ui-elements-overflow-helpers.js:38]: Handling the case when `message` is `undefined`

File: frontend/src/metabase/query_builder/components/SidebarHeader/SidebarHeader.tsx [hunk 2]
```diff
@@ -48,29 +44,46 @@ function SidebarHeader({ className, title, icon, onBack, onClose }: Props) {
...
         </a>
       )}
-    </SidebarHeaderRoot>
+    </Flex>
   );
 }
 
 // eslint-disable-next-line import/no-default-export -- deprecated usage
-export default Object.assign(SidebarHeader, { Root: SidebarHeaderRoot });
+export default Object.assign(SidebarHeader);
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/SidebarHeader/SidebarHeader.tsx:89]: `SidebarHeaderRoot` export had no usages

File: e2e/support/helpers/e2e-ui-elements-overflow-helpers.js (hunk 1 above)
Comment (romeovs) [reply e2e/support/helpers/e2e-ui-elements-overflow-helpers.js:38]: Can we use `isNotNull` for this?

**Review by romeovs — APPROVED** [review]
Just one nit.

File: e2e/support/helpers/e2e-ui-elements-overflow-helpers.js (hunk 1 above)
Comment (kamilmielnik) [reply e2e/support/helpers/e2e-ui-elements-overflow-helpers.js:38]: It wouldn't handle empty strings as expected.
