### PR TITLE
PivotTable scroll alignment fix

### LINKED ISSUE #14352: Pivot tables: horizontal scrollbar causing rows to be misaligned
If on Mac, turn `Show scroll bars` to `Always` to see this behavior. Here's an [example query](http://localhost:3000/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MiwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJicmVha291dCI6W1siZmstPiIsWyJmaWVsZC1pZCIsMTFdLFsiZmllbGQtaWQiLDI1XV0sWyJmay0-IixbImZpZWxkLWlkIiwxM10sWyJmaWVsZC1pZCIsNF1dLFsiZmstPiIsWyJmaWVsZC1pZCIsMTNdLFsiZmllbGQtaWQiLDNdXV19LCJkYXRhYmFzZSI6MX0sImRpc3BsYXkiOiJwaXZvdCIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJtYXAudHlwZSI6InJlZ2lvbiIsIm1hcC5yZWdpb24iOiJ1c19zdGF0ZXMiLCJwaXZvdF90YWJsZS5jb2x1bW5fc3BsaXQiOnsicm93cyI6W1siZmstPiIsWyJmaWVsZC1pZCIsMTNdLFsiZmllbGQtaWQiLDRdXSxbImZrLT4iLFsiZmllbGQtaWQiLDEzXSxbImZpZWxkLWlkIiwzXV1dLCJjb2x1bW5zIjpbWyJmay0-IixbImZpZWxkLWlkIiwxMV0sWyJmaWVsZC1pZCIsMjVdXV0sInZhbHVlcyI6W1siYWdncmVnYXRpb24iLDBdXX19fQ==) to test against.

The horizontal scrollbar should be below the Grand totals row. This is important because it causes all the rows in this section to be misaligned with their row labels:

image

### PR DESCRIPTION
**Pull request by kdoh**
Closes #14352 

## What this does
- Adds some special casing to the computed height of the PivotTable left column to prevent the presence of a horizontal scrollbar causing rows in the left sidebar and main content area getting out of sync.

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx [hunk 1]
```diff
@@ -199,6 +206,28 @@ export default class PivotTable extends Component {
...
+      // windows always has scrollbars, otherwise check for the Mac setting
+      const hasScrollbars =
+        window.navigator.platform === "Win32" || areScrollbarsVisible();
+
+      console.log("hasScrollbars?", hasScrollbars);
+
+      return scrollsHorizontally && scrollsVertically && hasScrollbars;
+    }
+
+    console.log(needsScrollbarOffset());
```
Comment (kdoh) [inline frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:229]:
```suggestion
```

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx [hunk 2]
```diff
@@ -390,7 +418,11 @@ export default class PivotTable extends Component {
                     leftHeaderCellSizeAndPositionGetter
                   }
                   width={leftHeaderWidth}
-                  height={height - topHeaderHeight}
+                  height={
+                    needsScrollbarOffset()
+                      ? height - topHeaderHeight - 20
```
Comment (kdoh) [inline frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:423]: Need to move this to a platform specific constant, but this value roughly works on Windows

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx [hunk 3]
```diff
@@ -178,6 +181,10 @@ export default class PivotTable extends Component {
     },
   };
 
+  setBodyRef = element => {
+    this.bodyRef = element;
```
Comment (kdoh) [inline frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:185]: Could probably use a better name here. Suggestions welcome.

**Comment by mazameli** [comment]
It looks like I can scroll the row groupings down a bit past the cells to misalign them still. This is on Safari 14, but I'm seeing it in Chrome, too:

scroll-behavior

Here's a detail:

image

Even without scrolling the row groupings, the Grand Total background looks slightly cut off:

image

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx [hunk 4]
```diff
@@ -199,6 +206,27 @@ export default class PivotTable extends Component {
...
+    function needsScrollbarOffset() {
+      if (!grid) {
+        return false;
+      }
+      // check to see if the main data container has Y scrolling
+      const scrollsVertically = grid.scrollHeight > parseInt(grid.style.height);
+      const scrollsHorizontally = grid.scrollWidth > parseInt(grid.style.width);
+      // windows always has scrollbars, otherwise check for the Mac setting
+      const hasScrollbars =
+        window.navigator.platform === "Win32" || areScrollbarsVisible();
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:222]: Shouldn't `areScrollbarsVisible` always return true on Windows then? If not, maybe move the platform check into that function.

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx [hunk 5]
```diff
@@ -199,6 +206,27 @@ export default class PivotTable extends Component {
...
+
+      console.log("hasScrollbars?", hasScrollbars);
+
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:225]:
```suggestion
```

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx (hunk 3 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:185]: I think "body" is descriptive enough in the context of this visualization.

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx [hunk 6]
```diff
@@ -199,6 +206,27 @@ export default class PivotTable extends Component {
...
+      return scrollsHorizontally && scrollsVertically && hasScrollbars;
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:226]: Does it break if we just use `scrollsHorizontally && hasScrollbars`? It seems like the extra padding wouldn't be an issue if there's vertical space anyways, but I didn't actually test to check this.

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx (hunk 2 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:423]: Maybe that could live in lib/browser since `isMac` is already there?

Also, this is a nitpick but I'd put the ternary inside the arithmetic expression to reduce duplication: `height - topHeaderHeight - (needsScrollbarOffset() ? SCROLLBAR_HEIGHT : 0)`

Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:423]: Actually, maybe `needsScrollbarOffset` could be `scrollbarOffsetSize` instead which returns `SCROLLBAR_HEIGHT` or `0`

File: frontend/src/metabase/lib/dom.js [hunk 7]
```diff
@@ -26,6 +27,28 @@ export const IFRAMED_IN_SELF = (function() {
...
+    innerElem = document.createElement("div");
+  scrollableElem.style.width = "30px";
+  scrollableElem.style.height = "30px";
+  scrollableElem.style.overflow = "scroll";
+  scrollableElem.style.borderWidth = "0";
+  innerElem.style.width = "30px";
+  innerElem.style.height = "60px";
+  scrollableElem.appendChild(innerElem);
+  document.body.appendChild(scrollableElem); // Elements only have width if they're in the layout
+  const diff = scrollableElem.offsetWidth - scrollableElem.clientWidth;
```
Comment (paulrosenzweig) [inline frontend/src/metabase/lib/dom.js:47]: Does `diff` reliably give us the scrollbar size?

**Review by paulrosenzweig — APPROVED** [review]
👏 👏 👏

File: frontend/src/metabase/lib/dom.js (hunk 7 above)
Comment (kdoh) [reply frontend/src/metabase/lib/dom.js:44]: It does!

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx (hunk 6 above)
Comment (kdoh) [reply frontend/src/metabase/visualizations/visualizations/PivotTable.jsx]: Yeah I think i was being overly cautious, seems fine without it.

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx (hunk 4 above)
Comment (kdoh) [reply frontend/src/metabase/visualizations/visualizations/PivotTable.jsx]: Yup, goof on my part.

**Comment by kdoh** [comment]
Should be all fixed up now.

**Comment by paulrosenzweig** [comment]
Updates look great!

**Comment by mazameli** [comment]
The [issues](https://github.com/metabase/metabase/pull/14522#issuecomment-767673997) I saw look resolved. Nice!

**Review by mazameli — APPROVED** [review]
