### PR TITLE
Enforcing Filter Widget Lables be present

### LINKED ISSUE #24040: Backend does not accept a blank filter widget label
**Describe the bug**
When you do a native query with filters and leave the widget label blank, the backend will return an error

**Logs**
<details>
```
metabase-postgres         | 2022-07-18 01:28:53,399 ERROR middleware.catch-exceptions :: Error processing query: Input to resolve-card-id-source-tables* does not match schema: 
metabase-postgres         | 
metabase-postgres         | 	   [(named {:native {:template-tags {"state" {:display-name (not ("Non-blank string" ""))}}}} arg0)]  
metabase-postgres         | 
metabase-postgres         | 
metabase-postgres         | {:database_id 2,
metabase-postgres         |  :started_at #t "2022-07-18T01:28:53.352034Z[GMT]",
metabase-postgres         |  :error_type :invalid-query,
metabase-postgres         |  :json_query
metabase-postgres         |  {:database 2,
metabase-postgres         |   :native
metabase-postgres         |   {:template-tags {:state {:id "b786093f-6ade-6bed-4e9c-b14fe4d2f44f", :name "state", :display-name "", :type "text"}},
metabase-postgres         |    :query "select * from people [[where state = {{state}}]]"},
metabase-postgres         |   :type "native",
metabase-postgres         |   :parameters [],
metabase-postgres         |   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
metabase-postgres         |  :status :failed,
metabase-postgres         |  :class clojure.lang.ExceptionInfo,
metabase-postgres         |  :stacktrace
metabase-postgres         |  ["--> query_processor.middleware.fetch_source_query$fn__48240$resolve_card_id_source_tables_STAR___48245.invoke(fetch_source_query.clj:322)"
metabase-postgres         |   "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__48262.invoke(fetch_source_query.clj:338)"
metabase-postgres         |   "query_processor.middleware.store$initialize_store$fn__48450$fn__48451.invoke(store.clj:11)"
metabase-postgres         |   "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
metabase-postgres         |   "query_processor.store$do_with_store.invoke(store.clj:38)"
metabase-postgres         |   "query_processor.middleware.store$initialize_store$fn__48450.invoke(store.clj:10)"
metabase-postgres         |   "query_processor.middleware.normalize_query$normalize$fn__52459.invoke(normalize_query.clj:22)"
metabase-postgres         |   "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__59158.invoke(handle_audit_queries.clj:130)"
metabase-postgres         |   "query_processor.middleware.constraints$add_default_userland_constraints$fn__49518.invoke(constraints.clj:53)"
metabase-postgres         |   "query_processor.middleware.process_userland_query$process_userland_query$fn__52398.invoke(process_userland_query.clj:145)"
metabase-postgres         |   "query_processor.middleware.catch_exceptions$catch_exceptions$fn__52770.invoke(catch_exceptions.clj:167)"
metabase-postgres         |   "query_processor.reducible$async_qp$qp_STAR___44675$thunk__44677.invoke(reducible.clj:100)"
metabase-postgres         |   "query_processor.reducible$async_qp$qp_STAR___44675.invoke(reducible.clj:106)"
metabase-postgres         |   "query_processor.reducible$async_qp$qp_STAR___44675.invoke(reducible.clj:91)"
metabase-postgres         |   "query_processor.reducible$sync_qp$qp_STAR___44686.doInvoke(reducible.clj:126)"
metabase-postgres         |   "query_processor$process_userland_query.invokeStatic(query_processor.clj:330)"
metabase-postgres         |   "query_processor$process_userland_query.doInvoke(query_processor.clj:326)"
metabase-postgres         |   "query_processor$fn__53789$process_query_and_save_execution_BANG___53798$fn__53801.invoke(query_processor.clj:341)"
metabase-postgres         |   "query_processor$fn__53789$process_query_and_save_execution_BANG___53798.invoke(query_processor.clj:334)"
metabase-postgres         |   "query_processor$fn__53833$process_query_and_save_with_max_results_constraints_BANG___53842$fn__53845.invoke(query_processor.clj:353)"
metabase-postgres         |   "query_processor$fn__53833$process_query_and_save_with_max_results_constraints_BANG___53842.invoke(query_processor.clj:346)"
metabase-postgres         |   "api.dataset$run_query_async$fn__69159.invoke(dataset.clj:68)"
metabase-postgres         |   "query_processor.streaming$streaming_response_STAR_$fn__39858$fn__39859.invoke(streaming.clj:162)"
metabase-postgres         |   "query_processor.streaming$streaming_response_STAR_$fn__39858.invoke(streaming.clj:161)"
metabase-postgres         |   "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
metabase-postgres         |   "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
metabase-postgres         |   "async.streaming_response$do_f_async$task__19010.invoke(streaming_response.clj:84)"],
metabase-postgres         |  :card_id nil,
metabase-postgres         |  :context :ad-hoc,
metabase-postgres         |  :error
metabase-postgres         |  "Input to resolve-card-id-source-tables* does not match schema: \n\n\t   [(named {:native {:template-tags {\"state\" {:display-name (not (\"Non-blank string\" \"\"))}}}} arg0)]  \n\n",
metabase-postgres         |  :row_count 0,
metabase-postgres         |  :running_time 0,
metabase-postgres         |  :ex-data
metabase-postgres         |  {:type :schema.core/error,
metabase-postgres         |   :value
metabase-postgres         |   [{:database 2,
metabase-postgres         |     :native
metabase-postgres         |     {:template-tags
metabase-postgres         |      {"state" {:id "b786093f-6ade-6bed-4e9c-b14fe4d2f44f", :name "state", :display-name "", :type :text}},
metabase-postgres         |      :query "select * from people [[where state = {{state}}]]"},
metabase-postgres         |     :type :native,
metabase-postgres         |     :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
metabase-postgres         |     :info
metabase-postgres         |     {:executed-by 1,
metabase-postgres         |      :context :ad-hoc,
metabase-postgres         |      :query-hash
metabase-postgres         |      [58, 57, -11, -46, 31, 11, 117, 3, 100, -68, 95, 90, 89, -45, -80, -52, -12, -86, -65, -115, 68, 115, 64, 19, -40,
metabase-postgres         |       124, -27, 69, -103, 99, -45, 42]},
metabase-postgres         |     :constraints {:max-results 10000, :max-results-bare-rows 2000}}],
metabase-postgres         |   :error [(named {:native {:template-tags {"state" {:display-name (not ("Non-blank string" ""))}}}} arg0)]},
metabase-postgres         |  :data {:rows [], :cols []}}
```
</details>

**To Reproduce**
1) New->native query
2) use the following query: "select * from people [[where state = {{state}}]]" without the double quotes
3) remove the text from the "Filter widget label"
4) run the query and see the error

**Expected behavior**
Either force a name for the widget in the FE or run the query without the field widget name

**Screenshots**
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: H2
- Metabase version: 1.43.4
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
P2

**Additional context**
NA

### PR DESCRIPTION
**Pull request by npfitz**
Fixes #24040

Adding a check to `NativeQuery.validateTemplateTags()` to ensure that tags have `display-name` set. Happily taking suggestions on what the validation error should actually say 😂.

chrome_KlnmvCkG6s

### CODE REVIEW

**Review by ranquild — COMMENTED** [review]
We don't show error messages like this. They are usually displayed below the field. Should we ask someone from the design team to validate this solution?

**Comment by npfitz** [comment]
@ranquild I was following the pattern we use for missing field references, so I think the pattern could work. But I'm happy to get some design input!

image

File: frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.jsx [hunk 1]
```diff
@@ -247,7 +248,12 @@ export class TagEditorParam extends Component {
 
         {(hasWidgetOptions || !isDimension) && (
           <div className="pb4">
-            <h4 className="text-medium pb1">{t`Filter widget label`}</h4>
+            <h4 className="text-medium pb1">
+              {t`Filter widget label`}
+              {hasNoWidgetLabel && (
+                <span className="text-error mx1">{t`(required)`}</span>
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.jsx:254]: Ideally we shouldn't use global css classes in new code because it increases the scope of migration

**Review by ranquild — APPROVED** [review]
