### PR TITLE
Fix external link in dashboard doesn't use correct target

### LINKED ISSUE #26131: External links in dashboard Textbox does not use correct target
**Describe the bug**
External links in dashboard Textbox does not use correct target, which can be more problematic when embedding.

**To Reproduce**
1. Go to dashboard, add a Textbox
```
[internal](/)

[external](https://example.com/)

[external](https://example.com/){:target="_blank"}
```
2. All links doesn't have a target-attribute
image

**Expected behavior**
External links should always have target=_blank (and noreferrer noopener for security)

**Information about your Metabase Installation:**
Tested 0.40.5 thru 0.44.5

**Additional context**
Related to #10370 and #10857

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes: #26131

This PR will set `target="_blank"` for markdown with external links (starting with `http`)

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/27037)

### CODE REVIEW

**Review by iethree — COMMENTED** [review]
I'm not sure how one would do this via the markdown component, but I think it's best security practice to set `rel="noreferrer"` on `target="_blank"` links.

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md

File: frontend/src/metabase/visualizations/visualizations/Text/Text.jsx [hunk 1]
```diff
@@ -202,3 +204,13 @@ export default class Text extends Component {
     );
   }
 }
+
+function getMarkdownLinkTarget(link) {
```
[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/visualizations/visualizations/Text/Text.jsx:208]: image

Thank you! I'd been searching for it for a while but gave up.

[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/visualizations/visualizations/Text/Text.jsx]: @ranquild I ended up removing the function entirely and not even using `getUrlTarget` since the only way we could configure `rel` is to use [rehype-external-links](https://github.com/rehypejs/rehype-external-links). Which handles detecting external links for us already.

**Review by WiNloSt — COMMENTED** [review]
[Without changing the babel file name to `babel.config.js`](https://babeljs.io/docs/en/configuration#whats-your-use-case), babel won't transform `rehype-external-links` inside `node_modules/`. Since [`rehype-external-links`](https://github.com/rehypejs/rehype-external-links) is only available in ES module.

File: jest.tz.unit.conf.json [hunk 2]
```diff
@@ -3,8 +3,12 @@
     "\\.(css|less)$": "<rootDir>/frontend/test/__mocks__/styleMock.js",
     "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/frontend/test/__mocks__/fileMock.js",
     "^promise-loader\\?global\\!metabase-lib\\/metadata\\/utils\\/ga-metadata$": "<rootDir>/frontend/src/metabase-lib/metadata/utils/ga-metadata.js",
-    "^d3-(.*)$": "<rootDir>/node_modules/d3-$1/dist/d3-$1"
+    "^d3-(.*)$": "<rootDir>/node_modules/d3-$1/dist/d3-$1",
+    "react-markdown": "<rootDir>/node_modules/react-markdown/react-markdown.min.js"
   },
+  "transformIgnorePatterns": [
+    "<rootDir>/node_modules/(?!rehype-external-links/)"
```
Comment (WiNloSt) [inline jest.tz.unit.conf.json:10]: Need to transpile [`rehype-external-links`](https://github.com/rehypejs/rehype-external-links) since it's only available in ES Module.

File: jest.tz.unit.conf.json [hunk 3]
```diff
@@ -3,8 +3,12 @@
     "\\.(css|less)$": "<rootDir>/frontend/test/__mocks__/styleMock.js",
     "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/frontend/test/__mocks__/fileMock.js",
     "^promise-loader\\?global\\!metabase-lib\\/metadata\\/utils\\/ga-metadata$": "<rootDir>/frontend/src/metabase-lib/metadata/utils/ga-metadata.js",
-    "^d3-(.*)$": "<rootDir>/node_modules/d3-$1/dist/d3-$1"
+    "^d3-(.*)$": "<rootDir>/node_modules/d3-$1/dist/d3-$1",
+    "react-markdown": "<rootDir>/node_modules/react-markdown/react-markdown.min.js"
```
Comment (WiNloSt) [inline jest.tz.unit.conf.json:7]: This line is needed since I've encountered an error after upgrading `react-markdown` to v8.0.4.

Ref: https://stackoverflow.com/questions/72382316/jest-encountered-an-unexpected-token-react-markdown

File: jest.unit.conf.json [hunk 4]
```diff
@@ -4,8 +4,12 @@
     "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/frontend/test/__mocks__/fileMock.js",
     "^promise-loader\\?global\\!metabase-lib\\/metadata\\/utils\\/ga-metadata$": "<rootDir>/frontend/src/metabase-lib/metadata/utils/ga-metadata.js",
     "ace/ext-searchbox": "<rootDir>/frontend/test/__mocks__/aceSearchBoxExtMock.js",
-    "^d3-(.*)$": "<rootDir>/node_modules/d3-$1/dist/d3-$1"
+    "^d3-(.*)$": "<rootDir>/node_modules/d3-$1/dist/d3-$1",
+    "react-markdown": "<rootDir>/node_modules/react-markdown/react-markdown.min.js"
```
Comment (WiNloSt) [inline jest.unit.conf.json:8]: Changes are the same as introduced in `jest.tz.unit.conf.json`

**Review by ranquild — APPROVED** [review]
