### PR TITLE
[Dashboard] Do not lose filters state on navigating back from Question

### LINKED ISSUE #34382: Dashboard loses effective filter values when auto-apply is turned off
### Describe the bug

When returning to a dashboard from a card  the values of filters are not restored if Auto-apply filters is turned off on the dashboard.

### To Reproduce

1. Create a saved question (e.g. select Products from the sample database), save it and add it to a dashboard.
2. Add a dashboard filter and connect it to the question (e.g. add Category).
3. Turn Apply filter values off for the dasboard.
4. Set a value for the filter, and apply it.
5. Open the card from the dashboard, notice that the filter values remain in effect.
6. Click the blue left arrow button to return to the dashboard (the Metabase one, not the browser back button).
7. (!) The filter values are cleared in the dashboard filters.
8. (!) Reload the page, and the card also returns to an unfiltered state.

### Expected behavior

The applied filter values should be retained on return from a card.

### Logs

n/a

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.192-183.736.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-18",
      "tag": "v1.47.2",
      "branch": "release-x.47.x",
      "hash": "536c24c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

A severe issue for some of our users.

### Additional context
Screen recording: filters are correctly restored when auto_apply_filters is set, and lost when the flag is unset.
https://github.com/metabase/metabase/assets/11080638/54ef0114-8a36-4044-8a91-ac525e1e6c7f

_No response_

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/34382

### Description

We need to preserve filter values not only when auto-apply is enabled for filters, but on navigating back to the dashboard from question

### How to verify

1. Create a saved question (e.g. select Products from the sample database), save it and add it to a dashboard.
2. Add a dashboard filter and connect it to the question (e.g. add Category).
3. Turn Apply filter values off for the dasboard.
4. Set a value for the filter, and apply it.
5. Open the card from the dashboard, notice that the filter values remain in effect.
6. Click the blue left arrow button to return to the dashboard (the Metabase one, not the browser back button).
7. (!) The filter values are kept in the dashboard filters.
8. (!) Reload the page keeps card filtered

### Demo

https://www.loom.com/share/11bf1d7700fd41dbadee91fcfcff0e47

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx [hunk 1]
```diff
@@ -61,7 +61,7 @@ import {
   getSlowCards,
   getIsAutoApplyFilters,
   getSelectedTabId,
-  getisNavigatingBackToDashboard,
+  getIsNavigatingBackToDashboard,
```
Comment (uladzimirdev) [inline frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx:64]: just renaming `is` -> `Is`

File: frontend/src/metabase/dashboard/reducers.js [hunk 2]
```diff
@@ -338,7 +338,11 @@ const parameterValues = handleActions(
 
 const draftParameterValues = handleActions(
   {
-    [INITIALIZE]: { next: () => ({}) },
+    [INITIALIZE]: {
```
Comment (uladzimirdev) [inline frontend/src/metabase/dashboard/reducers.js:341]: here we apply common logic on resetting state only when `clearCache` is passed. otherwise it's navigatingBack

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 3]
```diff
@@ -268,7 +268,7 @@ export const fetchCardData = createThunkAction(
         },
       });
 
-      // If the dataset_query was filtered then we don't have permisison to view this card, so
+      // If the dataset_query was filtered then we don't have permission to view this card, so
```
Comment (uladzimirdev) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:271]: typo

File: frontend/src/metabase/dashboard/reducers.js (hunk 2 above)
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/reducers.js:341]: We could add a case for it in `./reducers.unit.spec.js`

File: e2e/test/scenarios/dashboard/reproductions/34382-dashboard-back-navigation-preserve-filters.cy.spec.js [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+          });
+        },
+      );
+
+      cy.wrap(dashboard_id).as("dashboardId");
+    },
+  );
+};
+
+function setFilterValue(value) {
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard/reproductions/34382-dashboard-back-navigation-preserve-filters.cy.spec.js:106]: nit: `setFilterValue` can't be called twice in a row (because button label changes from "Add filter" to "Update filter"), but the name suggests it can.

**Review by kamilmielnik — APPROVED** [review]
LGTM :+1: 

Thanks for cleaning up things around!

----

> Do not loose filters state on navigating back from Question

lose*

**Review by ranquild — APPROVED** [review]
