### PR TITLE
Send `param_fields` per parameter to avoid field ref matching

### LINKED ISSUE #57604: Questions based on models with renamed fields will not get field values in public or embedded dashboards
### Describe the bug

If the underlying column name doesn't match the field name in a model, there will be no dropdown (field values) in public & embedded dashboards. It can happen when:
- It's an MBQL model but the column name gets de-duplicated (`name` -> `name_2`)
- It's a SQL model where the column is renamed in the query

### To Reproduce

1. New -> Model -> SQL -> `SELECT ID, CATEGORY AS CATEGORY_2 FROM PRODUCTS;` -> Save a M1
2. M1 -> Edit query metadata -> Map ID to Products.ID, CATEGORY_2 to Products.Category -> Save
3. New -> Question -> M1 -> Save as Q1
4. New -> Dashboard -> Add Q1 -> Add Text filter -> Map to Category -> Save
5. Make sure you have field values when opening the filter widget
6. Now create a public link for this dashboard. Open it -> You will have a plain text input.

### Expected behavior

Should work the same in the app.

### Logs

_No response_

### Information about your Metabase installation

```JSON
v54
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/57604

Currently, `param_fields` in dashboards and questions is returned as a plain list. The FE matches parameters with the list based on the `target`. The problem is that we don't have query metadata in public & embedding questions and dashboards to do that in non-trivial cases. To fix this issue, we simply need to return a map where the key is the parameter id, so that the FE doesn't need to do matching in these cases at all.

When I did that, I discovered many issues with the existing logic behind `param_fields` which became visible now.

### BE changes

For both questions and dashboards, return `param_fields` as a map, per parameter id. 

BE issues with parameter->fields matching this PR is trying to solve:
1. `stage-number` from parameter `target` is not taken into account. It always uses `-1`, which is incorrect and can work both ways - "overmatch" or don't match a valid column
2. It didn't handle "post-aggregation filters" where we normally call `lib/ensure-filter-stage`. 
3. it tried to match field refs manually by destructuring them and comparing with `(:name column)`. Which is obviously not correct since we normally have `:lib/desired-column-alias` in name-based refs and not the name itself. I replaced it with a `lib/find-matching-column` call
4. it didn't take models or metrics into account. We need to always create a query using them as data source. If we don't do that, we won't be able to match columns correctly as incoming field refs are from essentially another query.
5. before, it tried to match a column by a direct comparison with `result_metadata`. The problem is that the QP incorrectly computes `:id` on columns. Simple example - an identity expression `= [Field]`. It should not get an `:id`. Now, this part is removed and we use MBQL lib.
6. metadata-providers are created from scratch for each call. Performance-wise it should be bad
7. logic is duplicated in `api/dashboard.clj` which doesn't handle most of these cases as well

### FE changes

Use this mapping as is and don't do field ref matching in public & embedding cases.

### CODE REVIEW

File: frontend/src/metabase-lib/v1/parameters/utils/targets.ts [hunk 1]
```diff
@@ -101,15 +101,6 @@ function getParameterTargetFieldFromFieldRef(
   }
 
   const { query, columns } = getParameterColumns(question, parameter);
-
-  if (columns.length === 0) {
-    // query and metadata are not available: 1) no data permissions 2) embedding
-    // there is no way to find the correct field so pick the first one matching by name
-    return fields.find(
```
Comment (ranquild) [inline frontend/src/metabase-lib/v1/parameters/utils/targets.ts:108]: This is essentially how our logic for parameters<->field matching for public and embedding cases looked like before :)

File: src/metabase/models/params.clj [hunk 2]
```diff
@@ -275,49 +301,51 @@
...
      ctx
-     (let [card (get-in param-dashcard-info [:dashcard :card])]
-       (if-some [field-id (or
-                           ;; Get the field id from the field-clause if it contains it. This is the common case
-                           ;; for mbql queries.
-                           (lib.util.match/match-one param-target-field [:field (id :guard integer?) _] id)
-                           ;; Attempt to get the field clause from the model metadata corresponding to the field.
-                           ;; This is the common case for native queries in which mappings from original columns
-                           ;; have been performed using model metadata.
-                           (:id (qp.util/field->field-info param-target-field (:result_metadata card))))]
```
Comment (ranquild) [inline src/metabase/models/params.clj:290]: This is not correct!!! It has `:id` when it shouldn't

**Comment by bshepherdson** [comment]
* **#57554** <a href="https://app.graphite.dev/github/pr/metabase/metabase/57554?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/metabase/metabase/57554?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: src/metabase/api/dashboard.clj [hunk 3]
```diff
@@ -1129,6 +1129,9 @@
     (keyword (name type))
     :=))
 
+;; TODO needs to call [[lib/ensure-filter-stage]] and take `stage-number` from the parameter mapping into account
+;; TODO duplicates code in params.clj
+;; TODO needs to wrap models and metrics properly!
```
Comment (appleby) [inline src/metabase/api/dashboard.clj:1134]: still TODO?

File: src/metabase/embedding/api/common.clj [hunk 4]
```diff
@@ -332,7 +332,8 @@
                                                         (contains? param-ids-to-remove parameter_id)) param-mappings))))]
     (-> dashboard
         (update :dashcards #(map remove-parameters %))
-        (update :param_fields #(apply dissoc % field-ids-to-remove)))))
+        ;; TODO cleanup
```
Comment (appleby) [inline src/metabase/embedding/api/common.clj:335]: Still TODO? This one feels like it needs more context to be actionable (or else resolved/dropped in this PR)

File: src/metabase/models/params.clj [hunk 5]
```diff
@@ -202,46 +174,53 @@
...
+        param-target       (get-in param-dashcard-info [:param-mapping :target])
         card-id            (get-in param-dashcard-info [:dashcard :card :id])
-        filterable-columns (get-in ctx [:card-id->filterable-columns card-id])]
-    (if-some [field-id (lib.util.match/match-one param-target
+        filterable-columns (get-in ctx [:card-id->filterable-columns card-id stage-number])
+        [_ dimension]      (->> (mbql.normalize/normalize-tokens param-target :ignore-path)
+                                (mbql.u/check-clause :dimension))]
+    (if-some [field-id (lib.util.match/match-one dimension
+                         ;; TODO it's basically a workaround for ignoring non-dimension parameter targets such as SQL variables
+                         ;; TODO code is misleading; let's check for :dimension and drop the match call here
```
Comment (appleby) [inline src/metabase/models/params.clj:216]: Still TODO?

File: src/metabase/models/params.clj [hunk 6]
```diff
@@ -212,36 +219,55 @@
...
+  [database-id card stage-number]
+  ;; TODO for sure we need to re-use metadata providers per database-id
+  (let [metadata-provider (lib.metadata.jvm/application-database-metadata-provider database-id)
+        ;; TODO explain it better - models and metrics are always "wrapped" in dashboards
+        query (if (= :question (:type card))
+                (lib/query metadata-provider (:dataset_query card))
+                (->> (lib.metadata/card metadata-provider (:id card))
+                     (lib/query metadata-provider)))]
+    (-> query
+        lib/ensure-filter-stage
```
[the remark this answers is not in the document]
Comment (appleby) [reply src/metabase/models/params.clj:187]: should this pass the `stage-number` to `lib/ensure-filter-stage`, or you want the filter stage even if `stage-number` is not the last stage?

**Review by appleby — COMMENTED** [review]
BE part LGTM. Won't hit approve yet to make sure it still shows up on FE review radar.

File: src/metabase/models/params.clj (hunk 6 above)
[the remark this answers is not in the document]
Comment (ranquild) [reply src/metabase/models/params.clj:187]: We should append a new stage and _then_ try to find the stage by stage-number

File: src/metabase/embedding/api/common.clj (hunk 4 above)
Comment (ranquild) [reply src/metabase/embedding/api/common.clj:335]: Fixed

File: src/metabase/models/params.clj (hunk 5 above)
Comment (ranquild) [reply src/metabase/models/params.clj:216]: Fixed

File: src/metabase/api/dashboard.clj (hunk 3 above)
Comment (ranquild) [reply src/metabase/api/dashboard.clj:1134]: @bshepherdson this still needs to be fixed. It's not only that the logic is duplicated - it doesn't handle cases like models, metrics, post-aggregation filtering

File: frontend/src/metabase/parameters/utils/dashboards.ts [hunk 7]
```diff
@@ -117,7 +118,33 @@ function getMappings(dashcards: QuestionDashboardCard[]): ExtendedMapping[] {
...
+    if (isFieldFilterParameter(parameter)) {
+      return buildSavedDashboardParameter(
+        parameter,
+        mappings,
+        parameterFields,
+        metadata,
+      );
+    }
+
+    return {
```
Comment (uladzimirdev) [inline frontend/src/metabase/parameters/utils/dashboards.ts:139]: why do we need shallow copying here?

File: frontend/src/metabase/parameters/utils/dashboards.ts [hunk 8]
```diff
@@ -165,7 +192,36 @@ export function getDashboardQuestions(
...
+  fields: Dashboard["param_fields"],
+  metadata: Metadata,
+) {
+  const parameterMappings = mappings.filter(
+    (mapping) => mapping.parameter_id === parameter.id,
+  );
+  const hasNativeQueryTarget = parameterMappings.some(
+    (mapping) => mapping.card.dataset_query?.type === "native",
+  );
+  const hasVariableTemplateTagTarget = parameterMappings.some((mapping) =>
```
Comment (uladzimirdev) [inline frontend/src/metabase/parameters/utils/dashboards.ts:207]: probably can be optimized by checking `hasNativeQueryTarget` first? like

```
hasNativeQueryTarget && parameterMappings.some
```

File: frontend/src/metabase/parameters/utils/dashboards.ts [hunk 9]
```diff
@@ -165,7 +192,36 @@ export function getDashboardQuestions(
...
+    isParameterVariableTarget(mapping.target),
+  );
+  const parameterFields = (fields?.[parameter.id] ?? [])
+    .map((field) => metadata.field(field.id))
+    .filter(isNotNull)
+    // TODO we need to preserve this hack until remapping is migrated to the BE. See #57571
```
Comment (uladzimirdev) [inline frontend/src/metabase/parameters/utils/dashboards.ts:213]: could you please clarify, what exactly to see there?

**Review by uladzimirdev — APPROVED** [review]
minor comments

File: frontend/src/metabase/parameters/utils/dashboards.ts (hunk 9 above)
Comment (ranquild) [reply frontend/src/metabase/parameters/utils/dashboards.ts:213]: This is what makes FK+PK remapping work. I'll try to address it shortly.

Comment (uladzimirdev) [reply frontend/src/metabase/parameters/utils/dashboards.ts:213]: ah, I see, BE leftover probably
