### PR TITLE
Filters blocking small screen devices

### LINKED ISSUE #20879: Dashboard with many filters block the entire screen on smaller devices
**Describe the bug**
When access a dashboard on mobile, the filter panel covers the dashboard graphs.

**Logs**
Irrelevant in this case. It is all about frontend/layout.

**To Reproduce**
1. Create a dashboard with 15 filters (I know it is insane, but is real here xD) and some graphics (we need a good scroll down to reproduce properly);
2. Access this dashboard on mobile or simulate it on browser. You must see a big filter list covering all (almost) screen.
3. Just try to scroll down;
4. Well, the filter panel now is fixed, covering all dashboard content.

**Expected behavior**
I like filter panel fixed, but only on big screens, desktops, TVs etc. On mobile, a non-fixed filter panel should works better.

**Screenshots**
Mobo view, emulated on browser
img1

Little bigger screen view (browser)
img2

**Information about your Metabase Installation:**
It is a Docker container: metabase/metabase:v0.42.1 

I have test it on:
- Desktop Debian 10 Linux + xfce + Firefox 91.6;
- Xiaomi Redmi + Chrome 98.0...

**Severity**
It is not severe, but it is blocking all mobile users. 

The city hall of [itajaí / Santa Catarina / Brazil](https://goo.gl/maps/SmdKZHpSiEanBNNZA) thanks the Metabase team in advance 
😃

### PR DESCRIPTION
**Pull request by losrebellos**
Fixes #20879.

__After__

- The filters have the default width
image

- The filters have a 100% width on small screen devices
image

- The filters are not sticky as there is more than 6 parameters
image

### CODE REVIEW

File: frontend/src/metabase/parameters/components/SyncedParametersList/SyncedParametersList.jsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ const propTypes = {
   setEditingParameter: PropTypes.func,
 };
 
-export function SyncedParametersList({
+export default function SyncedParametersList({
```
Comment (ariya) [inline frontend/src/metabase/parameters/components/SyncedParametersList/SyncedParametersList.jsx:26]: Is this `default` change related to the issue?

File: frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js [hunk 2]
```diff
@@ -1,5 +1,7 @@
 import { getMainElement } from "metabase/lib/dom";
 
+export const MAXIMUM_PARAMETERS_FOR_STICKINESS = 6;
+
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js:4]: Should we really set a threshold for desktop screens too? Six filter widgets can fit nicely on a 13-inch display, not to mention bigger screens. Maybe something like an [`isSmallScreen` check](https://github.com/metabase/metabase/blob/2fe5330a295e240847ac9e6abfcaa48b01782e15/frontend/src/metabase/lib/dom.js#L448) will work better?

File: frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx [hunk 3]
```diff
@@ -98,6 +99,18 @@ export default class Dashboard extends Component {
...
+      props.parameters,
+      props.parameterValues,
+    );
+    if (!_.isEqual(parametersList, state.parametersList)) {
+      return { parametersList };
+    }
+
+    return null;
+  }
+
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx:113]: Seems like we only need a parameters count for the `stickyParameters` thing, so should we maybe just pass `props.parameters.length`? There won't be any need to do `getValuePopulatedParameters` too

Comment (ariya) [reply frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx:113]: I'm on the fence, while I think passing the length is a nice optimization, the current code is already explicit and rather be on the "safe side".

File: frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js (hunk 2 above)
Comment (ariya) [reply frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js:4]: This can be a potential nice follow-up (since the scope of this PR can be kept to narrow viewport situation).

**Review by ariya — APPROVED** [review]

File: frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx (hunk 3 above)
Comment (losrebellos) [reply frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx:113]: We might want to keep it that way because:
- `parametersList` is now used in [render()](https://github.com/metabase/metabase/pull/21848/files#diff-b27f144c8d7c51c6c4556af35ba48cb7b62b040e84b5a3d52ff9ac344c579310R237)
- we need the actual length of the `parametersList` generated from `getValuePopulatedParameters`

File: frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js [hunk 4]
```diff
@@ -34,11 +36,16 @@ const checkIfShouldToggleStickiness = (dashboard, shouldBeSticky) => {
 };
 
 const checkIfParametersWidgetShouldBeSticky = dashboard => {
+  const isStickyForDevice = !(
+    dashboard.state.parametersList &&
+    dashboard.state.parametersList.length > MAXIMUM_PARAMETERS_FOR_STICKINESS &&
+    isSmallScreen()
+  );
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js:43]: This makes it impossible to make filters sticky on desktop devices

**Review by kulyk — CHANGES_REQUESTED** [review]
Looks good, just noticed one unexpected behavior

File: frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js (hunk 4 above)
Comment (losrebellos) [reply frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js:43]: I don't think so... because the statement in the brackets is catering for when it is should not be sticky:
- IF it has `parametersList`
- AND `parametersList` is greater than 6
- AND it is a small screen
- THEN !(it is not sticky)

```
const isStickyForDevice = !(...);
```

Comment (kulyk) [reply frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js:43]: @losrebellos apologies, you're right, it works as expected! Just realized it was a different issue that made me think something's off with `isStickyForDevice`. For some reason, if I start editing a dashboard, add a few filters, save and then start scrolling, filter stickiness starts lagging (although it works fine if I open a dashboard with filters already / refresh the page). Please take a look:

**Steps to reproduce**

1. Open a dashboard with 4-5 filters
2. Click the "pencil" icon
3. Add 3-4 more filters (no need to connect them to card fields)
4. Save the changes
5. Start scrolling
6. Notice the filters don't become sticky for quite some time
7. Refresh the page and now it works as fast as it usually

### Demo

**This branch**

https://user-images.githubusercontent.com/17258145/165484234-f95f7c96-ddbd-4a43-8b98-f3056b6e12ef.mp4

**Master branch**

https://user-images.githubusercontent.com/17258145/165484245-4c18d51a-ef82-462b-9e2d-6161f716de5f.mp4

**Review by kulyk — APPROVED** [review]
Approving: code looks good and the target issue is fixed, nice work! There's a potential [performance drop](https://github.com/metabase/metabase/pull/21848#discussion_r859570628) that could appear, would appreciate if you can investigate that @losrebellos

**Comment by losrebellos** [comment]
@kulyk @ariya 

> Approving: code looks good and the target issue is fixed, nice work! There's a potential [performance drop](https://github.com/metabase/metabase/pull/21848#discussion_r859570628) that could appear, would appreciate if you can investigate that @losrebellos

Well spotted regarding the [performance issue](https://github.com/metabase/metabase/pull/21848#pullrequestreview-953172463), it was related to populating and passing the full parameters list and you did spot it [here](https://github.com/metabase/metabase/pull/21848#discussion_r857657185) as well.

**Review by kulyk — APPROVED** [review]
Nice!

**Review by ariya — APPROVED** [review]
Go go go :rocket:
