### PR TITLE
fix(sdk): remove the unknown premium feature console warnings

### LINKED ISSUE #47656: Remove the "Unknown Premium Feature" console warning
The "Unknown Premium Feature" console warning is spamming the console for sdk users.

image

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/47656

### Description

Removes the "unknown premium feature" warning that spams the SDK's console logs by removing EE plugins and overrides. See [this comment](https://github.com/metabase/metabase/pull/47885#pullrequestreview-2299641382).

image

### How to verify

- Use the SDK
- There should no longer be console warnings

### CODE REVIEW

**Comment by WiNloSt** [comment]
Does feature flags in the SDK actually work? Does this change fix an instance where we call `hasPremiumFeature` before the token is loaded in the SDK?

**Review by npretto — CHANGES_REQUESTED** [review]
I actually [suggested to do this a while back](https://metaboat.slack.com/archives/C505ZNNH4/p1721996330199199), but then I realized that this warning is actually telling us that we're doing something wrong (ie: plugins not working on the sdk).
The warnings area also useful because IIRC they show in tests only if we don't mock the token features properly.
The real "solution" to not make the warnings show up in the sdk is, for now, to remove this line:
https://github.com/metabase/metabase/blob/520c4bdd42d664c1568bc16bf11dccaad3c8fb40/enterprise/frontend/src/embedding-sdk/components/public/index.ts#L2-L3
as it is loading the ee plugins before we have the token features, which doesn't activate them (and the warning is telling us about it).

I'll leave https://github.com/metabase/metabase/pull/47473 here as reference on how we could go to make the ee plugins work

File: enterprise/frontend/src/embedding-sdk/components/public/index.ts [hunk 1]
```diff
@@ -1,6 +1,3 @@
-import "ee-overrides"; // eslint-disable-line import/no-duplicates
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/index.ts:1]: We don't need EE overrides right now because we already did something similar in the SDK, but it uses `application-colors` _after_ the SDK loads the settings instead, so it doesn't rely on hydrated JSON settings. For reference, this is what ee-overrides do: 

```ts
import "./whitelabel/overrides";
```

and

```ts
import { hasPremiumFeature } from "metabase-enterprise/settings";
import { updateColors } from "metabase-enterprise/whitelabel/lib/whitelabel";

if (hasPremiumFeature("whitelabel")) {
  updateColors();
}
```

**Review by npretto — APPROVED** [review]
image

solves issue ✅

removes code ✅

me happy     ✅

**Review by WiNloSt — APPROVED** [review]
If @npretto is happy, I'm also happy.
