### PR TITLE
Fix the distance between "Field to map to" and "required"

### LINKED ISSUE #46724: No space between "Field to Map To" and "(required)"
### Describe the bug

There is no space between "Field to Map To" and "(required)" when mapping field filters in version 50.

### To Reproduce

Create a SQL question with a field filter variable.

no_space

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
v50
```

### Severity

cosmetic

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nemanjaglumac**
Closes #46724

### Description

This PR fixes the CSS regression described in #46724. I checked the version 49.14 where the space between these two words was 0.5rem.

I used this opportunity to replace the styled component with Mantine's `Text`.

### How to verify

1. New sql query
2. `select * from orders where {{ foo }}`
3. Set foo as the field filter but do not map it to any table
4. There should be a distance between "Field to map to" and "(required)"

### Demo

**Before**
image

**After**
image

### Checklist
- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/template_tags/TagEditorParamParts/FieldMappingSelect.tsx [hunk 1]
```diff
@@ -36,7 +33,11 @@ export function FieldMappingSelect({
     <InputContainer>
       <ContainerLabel>
         {t`Field to map to`}
-        {tag.dimension == null && <ErrorSpan>{t`(required)`}</ErrorSpan>}
+        {tag.dimension == null && (
+          <Text c="error" span={true} ml="sm">
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/template_tags/TagEditorParamParts/FieldMappingSelect.tsx:37]: I was hoping we're going to fix it with whitespace (not margin) as in other places ([ParameterSettings](https://github.com/metabase/metabase/blob/35d9a8177edd2885bcfa95107c34201c9691bf35/frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.tsx#L243), [DefaultRequiredValueControl](https://github.com/metabase/metabase/blob/35d9a8177edd2885bcfa95107c34201c9691bf35/frontend/src/metabase/query_builder/components/template_tags/TagEditorParamParts/DefaultRequiredValueControl.tsx#L30)).

Also the parens are decorative and should not be a part of the translation string.
