### PR TITLE
Disable implicit actions if update query to include clauses

### LINKED ISSUE #28949: Basic actions become unusable if clauses are added to the model later
**Describe the bug**
Currently we don't allow to create **basic** actions for "non-raw" models, e.g. models with any clauses defined (joins, filters, aggregations). But it's possible to create basic actions for a model and then change its definition, and afterwards its basic actions start to work weirdly. 

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Make sure actions are enabled for you database. You can do it via Admin -> Databases
2. New -> Model -> Orders -> Save
3. Info panel -> Model details -> Actions -> Create basic actions
4. Edit definition -> Add summary by count, breakout by Created At (month) -> Save
5.  Info panel -> Model details -> Actions -> Try running an action
6. You get a weird form based on the latest stage of the query

**Expected behavior**
As discussed: 
  - Disable basic actions if the updated query include clauses (expression, limit, filter ...)

**Screenshots/videos**
Screenshot 2023-03-06 at 15 29 13
Screenshot 2023-03-06 at 15 29 50

**Information about your Metabase Installation:**
`v0.46.0-RC2`

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- Metabase version: (e.g., 0.19.3)
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

### PR DESCRIPTION
**Pull request by qnkhuat**
Resolves #28949

Implicit actions are only allowed on a simple model (aka model with only a source table).
This PR will make
- update model query to include new clauses (sort, aggregation, etc ) will need remove any implicit actions that are linked to it
- update the API to make sure we don't allow creating implicit actions on a complex model. (we already had this check on FE so it's not possible to hit this from UI, but add it just to make sure)

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29021)

### CODE REVIEW

File: src/metabase/models/card.clj [hunk 1]
```diff
@@ -344,8 +361,13 @@
...
       (when (:dataset_query changes)
         (check-for-circular-source-query-references changes))
+      ;; updating a model dataset query to includes any clauses will disable implicit acitons(if it exists)
+      (when (and (:dataset_query changes)
+                 (:dataset old-card-info)
+                 (not (model-supports-implicit-actions? changes)))
+        (disable-implicit-action-for-model! id))
       ;; Archive associated actions
-      (when (and (not (:dataset changes))
+      (when (and (false? (:dataset changes))
```
Comment (qnkhuat) [inline src/metabase/models/card.clj:370]: this was a bug before and tested it here : https://github.com/metabase/metabase/blob/fe252f7c79a8584b18a10a195d9007acd8983a6b/test/metabase/models/action_test.clj#L137

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e/yaml_test.clj [hunk 2]
```diff
@@ -158,6 +158,16 @@
                                                {:table_id      [:t    100]
                                                 :collection_id [:coll 100]
                                                 :creator_id    [:u    10]}))
+               :simple-model            (mapv #(update-in % [1 :refs] table->db)
```
Comment (qnkhuat) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/e2e/yaml_test.clj:161]: with the new `pre-update` in card, all implicit actions will be deleted during the generate part( I'm not sure why it calls update here but it is what it is).

The reason implicit actions got deleted is that the spec for `:card` in this test is a complex query with aggregation and breakout.

So I need to create a new spec that use a simple model so that our actions are safe from updates.

File: src/metabase/models/card.clj [hunk 3]
```diff
@@ -317,12 +317,29 @@
         (when-not (= parameters new-parameters)
           (db/update! model po-id {:parameters new-parameters}))))))
 
+(defn model-supports-implicit-actions?
+  "A model with implicit action supported iff they are a raw table,
+  meaning there are no clauses such as(filter, limit, breakout...)"
+  [{dataset-query :dataset_query :as _card}]
+  (and (= :query (:type dataset-query))
+       (every? #(nil? (get-in dataset-query [:query %])) [:expressions :filter :limit :breakout :aggregation :joins])))
```
Comment (qnkhuat) [inline src/metabase/models/card.clj:325]: it matches the check on FE: https://github.com/metabase/metabase/blob/89f8d515fe544cf85ed810b0b4cdc112222c71b5/frontend/src/metabase-lib/queries/StructuredQuery.ts#L508

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e/yaml_test.clj (hunk 2 above)
Comment (calherries) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e/yaml_test.clj:161]: Can you add a comment for this in the code? It would be almost impossible to know this without diving into this PR otherwise.

File: src/metabase/models/card.clj (hunk 3 above)
Comment (calherries) [reply src/metabase/models/card.clj:325]: Again, this kind of comment should live in the code. Whenever there's a co-dependency between BE and FE there should be a comment in both spots, so if the FE updates they know the BE needs to update as well, and vice versa.

File: src/metabase/models/card.clj [hunk 4]
```diff
@@ -344,8 +361,13 @@
       ;; make sure this Card doesn't have circular source query references if we're updating the query
       (when (:dataset_query changes)
         (check-for-circular-source-query-references changes))
+      ;; updating a model dataset query to includes any clauses will disable implicit acitons(if it exists)
```
Comment (calherries) [inline src/metabase/models/card.clj:364]:
```suggestion
      ;; updating a model dataset query to not support implicit actions will disable implicit actions if they exist
```

File: src/metabase/models/card.clj [hunk 5]
```diff
@@ -344,8 +361,13 @@
...
+      (when (and (:dataset_query changes)
+                 (:dataset old-card-info)
+                 (not (model-supports-implicit-actions? changes)))
+        (disable-implicit-action-for-model! id))
       ;; Archive associated actions
-      (when (and (not (:dataset changes))
+      (when (and (false? (:dataset changes))
                  (:dataset old-card-info))
         (t2/update! 'Action {:model_id id} {:archived true}))
```
Comment (calherries) [inline src/metabase/models/card.clj:372]: Not related to your PR but I just realised this is a bug too. Implicit actions should be deleted when a card is changed from a model to a card. Currently they are archived. Only query actions should be archived.

File: test/metabase/test/generate.clj [hunk 6]
```diff
@@ -238,6 +238,14 @@
                                               :database_id   [:database :id]
                                               :table_id      [:table :id]
                                               :collection_id [:collection :id]}}
+   ;; like card but is a model and the query is very simple
```
Comment (calherries) [inline test/metabase/test/generate.clj:241]: Would be good to document why we need this here as well

File: test/metabase/models/card_test.clj [hunk 7]
```diff
@@ -107,6 +109,67 @@
       (is (= {:name "another name" :database_id (mt/id)}
              (into {} (db/select-one [Card :name :database_id] :id id)))))))
 
+(deftest disable-implicit-actions-if-needed-test
+  (mt/with-actions-enabled
+    (testing "when updating a model to include any clauses will disable implicit actions if exists\n"
```
Comment (calherries) [inline test/metabase/models/card_test.clj:114]:
```suggestion
    (testing "when updating a model to include any clauses will disable implicit actions if they exist\n"
```

File: src/metabase/models/card.clj (hunk 3 above)
Comment (calherries) [reply src/metabase/models/card.clj:325]: This also doesn't match the FE perfectly. You need to add `:order-by` and `:fields`
```suggestion
       (every? #(nil? (get-in dataset-query [:query %])) [:expressions :filter :limit :breakout :aggregation :joins :order-by :fields])))
```

**Review by calherries — CHANGES_REQUESTED** [review]

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e/yaml_test.clj (hunk 2 above)
Comment (qnkhuat) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e/yaml_test.clj:164]: yep, added here: https://github.com/metabase/metabase/pull/29021/commits/1d8c6582972870b47b21603782d8618639ef371d

File: test/metabase/test/generate.clj (hunk 6 above)
Comment (qnkhuat) [reply test/metabase/test/generate.clj:241]: added a line under this : https://github.com/metabase/metabase/pull/29021/commits/1d8c6582972870b47b21603782d8618639ef371d

File: src/metabase/models/card.clj (hunk 3 above)
Comment (qnkhuat) [reply src/metabase/models/card.clj]: nice catch, Added the comment and include the missing clauses here: https://github.com/metabase/metabase/pull/29021/commits/1d8c6582972870b47b21603782d8618639ef371d

File: src/metabase/models/card.clj (hunk 5 above)
Comment (qnkhuat) [reply src/metabase/models/card.clj:375]: nice catch. you'll fix it, right?

Comment (calherries) [reply src/metabase/models/card.clj:375]: yes

File: frontend/src/metabase-lib/queries/StructuredQuery.ts [hunk 8]
```diff
@@ -506,6 +506,7 @@ class StructuredQueryInner extends AtomicQuery {
   }
 
   hasAnyClauses() {
+    // this list should be kept in sync with BE in `metabase.models.card/model-supports-implicit-actions?`
```
Comment (tsmacdonald) [inline frontend/src/metabase-lib/queries/StructuredQuery.ts:509]: Candidate for (eventual) CLJS-ification?

File: src/metabase/models/card.clj [hunk 9]
```diff
@@ -317,12 +317,34 @@
         (when-not (= parameters new-parameters)
           (db/update! model po-id {:parameters new-parameters}))))))
 
+(defn model-supports-implicit-actions?
+  "A model with implicit action supported iff they are a raw table,
+  meaning there are no clauses such as(filter, limit, breakout...).
```
Comment (tsmacdonald) [inline src/metabase/models/card.clj:322]:
```suggestion
  meaning there are no clauses such as filter, limit, breakout...
```

**Review by tsmacdonald — APPROVED** [review]
:clap:

File: frontend/src/metabase-lib/queries/StructuredQuery.ts (hunk 8 above)
Comment (qnkhuat) [reply frontend/src/metabase-lib/queries/StructuredQuery.ts:509]: yep

**Comment by qnkhuat** [comment]
@calherries could you help re-review this?

**Review by calherries — APPROVED** [review]
Nice
