### PR TITLE
Fix various collection editor form bugs

### LINKED ISSUE #4758: Creating a new Collection's Save Button says "Update" instead of "Save"
pretty minor 

screen shot 2017-04-11 at 12 49 48 pm

### PR DESCRIPTION
**Pull request by kdoh**
fixes #4758 plus tests.

@tlrobinson / @attekei Let me know what you think of the testing approach here and how it gels with our talk earlier today. It's a little ugly using `refs` but it was the easiest way I could find to test modal action buttons without resorting to an e2e test.

### CODE REVIEW

File: frontend/src/metabase/questions/containers/CollectionEditorForm.jsx [hunk 1]
```diff
@@ -41,12 +42,14 @@ export default class CollectionEditorForm extends Component {
                 form
                 title={fields.id.value != null ? fields.name.value : "New collection"}
                 footer={[
-                    <Button className="mr1" onClick={onClose}>
-                        Cancel
-                    </Button>,
-                    <Button primary disabled={invalid} onClick={handleSubmit}>
-                        { fields.id.value != null ? "Update" : "Create" }
-                    </Button>
+                    <div ref={(ref) => { this.footerRef = ref}}>
```
Comment (tlrobinson) [inline frontend/src/metabase/questions/containers/CollectionEditorForm.jsx]: Adding this `ref` just for the test seems a little wrong, but I see why you did it. I think ideally we'd be more strict about having the modal content separated from the actual modal itself to make things more easily testable.

Comment (kdoh) [inline frontend/src/metabase/questions/containers/CollectionEditorForm.jsx]: Yeah it definitely feels silly. I think unfortunately some kind of reference to the Modal content inside this component is the only way to get this test to work with how our Modals are currently structured.

Comment (kdoh) [inline frontend/src/metabase/questions/containers/CollectionEditorForm.jsx]: (Or writing a much more cumbersome e2e test)

Comment (tlrobinson) [inline frontend/src/metabase/questions/containers/CollectionEditorForm.jsx]: The alternative is to move the content and `title` and `footer` props to a separate component that uses `ModalContent` directly, then test that instead of the component that returns a `Modal`.

I'm wondering if `Modal` should actually just be a higher order component anyway.

Comment (kdoh) [inline frontend/src/metabase/questions/containers/CollectionEditorForm.jsx]: Yeah I wouldn't necessarily mind our Modals being a bit more composable and having Modal itself really just handle positioning.

**Comment by kdoh** [comment]
@tlrobinson Went ahead and switched this over to using it's own component. Thanks for the idea.

**Comment by kdoh** [comment]
Going to fix #4693 and #4769 here.

File: frontend/src/metabase/questions/containers/CollectionEditorForm.jsx [hunk 2]
```diff
@@ -31,23 +31,27 @@ import { normal } from "metabase/lib/colors";
...
+    <div>
+        <Button className="mr1" onClick={onClose}>
+            Cancel
+        </Button>
+        <Button primary disabled={invalid} onClick={handleSubmit}>
+            { fields.id.value != null ? "Update" : "Create" }
+        </Button>
+    </div>
+
+export class CollectionEditorForm extends Component {
```
Comment (attekei) [inline frontend/src/metabase/questions/containers/CollectionEditorForm.jsx]: lacking prop (Flow) types, would be nice to have because of prop propagation

File: package.json [hunk 3]
```diff
@@ -177,6 +178,9 @@
     "testPathIgnorePatterns": [
       "<rootDir>/frontend/test/"
     ],
+    "moduleNameMapper": {
+      "\\.(css|less)$": "identity-obj-proxy"
```
Comment (attekei) [inline package.json]: I did exactly the same thing in the dashboard branch too 👍

**Review by attekei — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/questions/containers/CollectionEditorForm.jsx (hunk 2 above)
Comment (attekei) [inline frontend/src/metabase/questions/containers/CollectionEditorForm.jsx]: see https://flow.org/en/docs/frameworks/react/#toc-adding-types-for-react-component-props for the most modern way to add Flow prop types

**Comment by kdoh** [comment]
@attekei / @tlrobinson Updated how I'm testing this stuff. Was a doofus and realized that there's no real need to involve React at all for fixing these bugs. Mind taking another look?

**Review by attekei — APPROVED** [review]

File: package.json (hunk 3 above)
Comment (kdoh) [inline package.json]: @attekei Turns out circle doesn't seem to like this package. @tlrobinson Added a simple mock as part of #4765 which seems to work just fine though.

File: frontend/src/metabase/lib/colors.js [hunk 4]
```diff
@@ -57,3 +58,8 @@ export const harmony = [
     '#c1a877',
     '#f95c67',
 ]
+
+export const getRandomColor = (family: Object) => {
```
Comment (tlrobinson) [inline frontend/src/metabase/lib/colors.js]: Instead of Object I'd do

```
type ColorFamily = { [name: string]: string };
```

Or if you want to be really fancy

```
type ColorName = string;
type Color = string
type ColorFamily = { [name: ColorName]: Color };

export const getRandomColor = (family: ColorFamily): Color => {
   // $FlowFixMe: Object.values doesn't preserve the type :-/
   const colors: Color[] = Object.values(family)
```

**Review by tlrobinson — CHANGES_REQUESTED** [review]
Yay tests

**Comment by kdoh** [comment]
@tlrobinson updated.

**Review by tlrobinson — APPROVED** [review]
