### PR TITLE
fix: setup url should use MB_SITE_URL if available

### LINKED ISSUE #26402: MB_SITE_URL does not apply to setup URL shown in the logs
I'm trying to use MB_SITE_URL variable with _docker run_ command:

`docker run -d --rm --expose 3000 --name metabase --env MB_SITE_URL="http://localhost:3000/metabase/" metabase/metabase:latest`

But the variable is not used by Metabase:

```
docker logs metabase | grep -A3 "Please use the following URL"
Warning: protocol #'java-time.core/Amount is overwriting function abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: java-time.core, being replaced by: #'java-time.core/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: java-time, being replaced by: #'java-time/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: taoensso.encore, being replaced by: #'taoensso.encore/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: kixi.stats.math, being replaced by: #'kixi.stats.math/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: kixi.stats.test, being replaced by: #'kixi.stats.math/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: kixi.stats.distribution, being replaced by: #'kixi.stats.math/abs
2022-11-11 09:32:15,227 INFO metabase.core :: Please use the following URL to setup your Metabase installation:

http://0.0.0.0:3000/setup/
```

I'm tryied with v.0.41, v.0.43 and v.0.44

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #26402

### CODE REVIEW

File: src/metabase/core.clj [hunk 1]
```diff
@@ -63,10 +63,11 @@
   []
   (let [hostname  (or (config/config-str :mb-jetty-host) "localhost")
         port      (config/config-int :mb-jetty-port)
-        setup-url (str "http://"
-                       (or hostname "localhost")
-                       (when-not (= 80 port) (str ":" port))
-                       "/setup/")]
+        site-url  (or (public-settings/site-url)
```
Comment (filipesilva) [inline src/metabase/core.clj:66]: `(public-settings/site-url)` ensures the url does not have a trailing slash, whereas `(config/config-str :mb-site-url)` would not.

File: src/metabase/core.clj [hunk 2]
```diff
@@ -63,10 +63,11 @@
...
+                      (str "http://"
+                           hostname
```
Comment (filipesilva) [inline src/metabase/core.clj:68]: No need to default to `localhost` again, the binding already does that.

**Review by escherize — APPROVED** [review]
