### PR TITLE
Closes VIZ-588 wrong hover index

### LINKED ISSUE #55684: [Bug Report] Pie visualization highlights wrong labels when hovering slices
### Description
When you hover over each slice, it seems to highlight the wrong value in the left sidebar. For example when you hover over Education, it highlights "Couldn't enrich" at the left sidebar.

Some of the slices correctly highlight their entry on the left, and some don't highlight anything.
 
I also note that the ordering of the slices is a bit strange; they're not in descending order.

### Links
- Original URL: https://stats.metabase.com/question/9313-industries-of-people-filling-out-forms
- Slack File: https://metaboat.slack.com/files/U02T6V8MXN2/F08K5GLRKG9/diagnostic-info.json

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #55684
Closes [VIZ-588: \[Bug Report\] Pie visualization highlights wrong labels when hovering slices](https://linear.app/metabase/issue/VIZ-588/[bug-report]-pie-visualization-highlights-wrong-labels-when-hovering)

### Description

The pie chart model computation would consider hidden slices as still hoverable, which led to wrong hover indices...

### How to verify

 1. Create a pie chart with a bunch of values
 1. Set the minimum slice percentage to something low
 1. Reorder the series so a small slice is now above a bigger one (like, take the last one and move it to the third place or something)
 1. Change the minimum slice percentage back to its original value
 1. Hover over the slice after where the small one was, the legend should highlight the wrong data because the hoverIndex calculation is done using pie.rows, but pie.rows is calculated without consideration for the minimum slice percentage 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/pie/model/index.ts [hunk 1]
```diff
@@ -343,18 +343,21 @@ export function getPieChartModel(
...
-    .map(({ value, color, key, name, isOther }, index) => {
+    .map(({ value, color, key, name, isOther }) => {
       const visible = isOther
         ? !hiddenSlices.includes(OTHER_SLICE_KEY)
         : !hiddenSlices.includes(key);
 
-      return {
+      const normalizedPercentage = visible ? value / total : 0; // slice percentage values are normalized to 0-1 scale
+
+      const o = {
```
Comment (kulyk) [inline frontend/src/metabase/visualizations/echarts/pie/model/index.ts:355]: nit: we could give it a name that'd tell that is, maybe `slice`?

**Review by kulyk — APPROVED** [review]

File: frontend/src/metabase/visualizations/echarts/pie/model/index.ts (hunk 1 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/visualizations/echarts/pie/model/index.ts:355]: Woops, I saw your comment after merging 🤦‍♂️
