### PR TITLE
Use non-whitelabeled blue color for Metabase logo

### LINKED ISSUE #58349: Metabase logo color shouldn't be overrideable
### Describe the bug

We shouldn't allow changing our brand identity where the logo appears [(Ref)](https://metaboat.slack.com/archives/C057WD5L0JG/p1747917852670589?thread_ts=1747917649.491319&cid=C057WD5L0JG).

This happens in a couple of places, in our internal app when modifying the brand color, in embedding SDK. And there might be more.

We also have another Logo color scheme for dark theme. We do this in static/public embed when using the dark theme.

Image

Here are some of the examples:
- embedding SDK

Image
- Our logo at the top left corner when changing brand color.

Image

### To Reproduce

1. Change brand color in the appearance settings.
2. Metabase logo color shouldn't change

### Expected behavior

The color stays consistent regarding of the color overrides whether it's from our app or the SDK, or other embedding flavors (if any)

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-05-22",
      "src_hash": "c816d6c95be5507b95d239d4358c6d2f7a290d6b",
      "tag": "v1.55.2-SNAPSHOT",
      "hash": "0c1a173"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.2+13-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.2+13-LTS",
    "os.name": "Mac OS X",
    "os.version": "15.5",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

minor

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/58349
Closes UXW-296

Makes the default Metabase logo color always use the blue logo color. See this [comment](https://metaboat.slack.com/archives/C057WD5L0JG/p1747917852670589?thread_ts=1747917649.491319&cid=C057WD5L0JG) from Bruno.

### How to verify

- Change the colors in admin settings > branding to purple
- Go to homepage
- The Metabase logo should be blue, not purple

For the Embedding SDK / EAJS, use this HTML snippet and turn off embedding in admin settings:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>

  <style>
  body {
    margin: 0;
  }

  metabase-metabot {
    height: 100vh;
  }
  </style>
</head>
<body>
<script defer src="http://localhost:3000/app/embed.js"></script>

<script>
  function defineMetabaseConfig(config) {
    window.metabaseConfig = config;
  }
</script>

<script>
  defineMetabaseConfig({
    "instanceUrl": "http://localhost:3000/",
    "useExistingUserSession": true,
    "theme": {
      "colors": {
        "brand": "#e74c3c"
      }
    }
  });
</script>

<div>
  <metabase-metabot></metabase-metabot>
</div>
</body>
</html>
```

### Demo

Homepage

CleanShot 2568-10-08 at 22 53 54@2x

Login Page

CleanShot 2568-10-08 at 22 54 53@2x

React SDK & Embedded Analytics JS - UsageProblemBanner

CleanShot 2568-10-08 at 23 19 14@2x

### CODE REVIEW

File: frontend/src/metabase/common/components/LogoIcon/LogoIcon.jsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ export class DefaultLogoIcon extends Component {
       <svg
         className={cx(
           "Icon",
-          { [CS.textBrand]: !dark },
+          { [CS.textMetabaseBrand]: !dark },
```
Comment (heypoom) [inline frontend/src/metabase/common/components/LogoIcon/LogoIcon.jsx:25]: This is the default non-white-labeled logo icon. Always use Metabase blue.

File: frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts [hunk 2]
```diff
@@ -65,6 +65,14 @@ export const SDK_TO_MAIN_APP_COLORS_MAPPING: Record<
   "text-hover": ["text-hover"],
 };
 
+/**
+ * These colors must never be changed.
+ * For example, the blue Metabase brand color.
+ **/
+export const SDK_UNCHANGEABLE_COLORS: (ColorName | SemanticColorKey)[] = [
```
Comment (heypoom) [inline frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts:72]: To define `--mb-color-metabase-brand: ...` on the SDK, for the SdkUsageProblemBanner.

**Comment by heypoom** [comment]
(Removed UX west from reviewer per [Roman's comment](https://metaboat.slack.com/archives/C010L1Z4F9S/p1759941889713429?thread_ts=1759395387.427479&cid=C010L1Z4F9S))

File: frontend/src/metabase/common/components/LogoIcon/LogoIcon.jsx (hunk 1 above)
Comment (WiNloSt) [reply frontend/src/metabase/common/components/LogoIcon/LogoIcon.jsx:25]: what's the difference between this file and the file above. They have the same name, but the diff aren't the same. We don't check `isDefaultMetabaseLogo` here. Why is that?

File: enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemBanner.tsx [hunk 3]
```diff
@@ -60,7 +59,7 @@ export const SdkUsageProblemBanner = ({
           i-should-be-flex="true"
         >
           <Flex bg="white" px="sm" className={S.Logo} align="center">
-            <LogoIcon height={24} fill={unthemedBrand} />
+            <DefaultLogoIcon height={24} />
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemBanner.tsx]: Why do you want to change the name here?

File: frontend/src/metabase/common/components/LogoIcon/LogoIcon.jsx (hunk 1 above)
Comment (WiNloSt) [reply frontend/src/metabase/common/components/LogoIcon/LogoIcon.jsx:25]: Ok, this is the default logo for users without a license.

**Review by WiNloSt — APPROVED** [review]
looks good to me.

File: frontend/src/metabase/common/components/LogoIcon/LogoIcon.jsx (hunk 1 above)
Comment (heypoom) [reply frontend/src/metabase/common/components/LogoIcon/LogoIcon.jsx:25]: Yes, we should just name it to `DefaultMetabaseLogo`.

File: enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemBanner.tsx (hunk 3 above)
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemBanner.tsx]: @WiNloSt Because for the SdkUsageProblemBanner, we should not show the user's logo but the Metabase logo as the component here is purposefully non-whitelabeled. Probably `DefaultMetabaseLogo` is even better.

Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemBanner.tsx]: Ok, I'm on board with the name 👍 Or just `MetabaseLogo` as there's no non-default Metabase logo? We either have Metabase logo or users' logo.

Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemBanner.tsx]: MetabaseLogo sounds nice, let me do a quick rename.

Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemBanner.tsx]: Fixed in https://github.com/metabase/metabase/pull/64524/commits/ae45a6c4e0c420adee7ccf09122439304096de6b
