### PR TITLE
Redundant separator displayed in table filter popup

### LINKED ISSUE #32120: Redundant separator displayed in table filter popup
**Describe the bug**

image

**To Reproduce**

1. Browse data in the sidebar
2. Open Sample database
3. Open People table
4. Click on "Address" / "Email" / "Password" / "Name" table header
5. Choose "Filter by this column"
6. Now choose one of: "Is empty" / "Not empty".

**Expected behavior**

Only 1 horizontal separator should be shown when text input is hidden.

**Severity**

P4

### PR DESCRIPTION
**Pull request by oisincoveney**
Closes #32120 

### Description

On column filter dropdowns, there's a redundant border here:

image

This PR removes that.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Browse data in the sidebar
2. Open Sample database
3. Open People table
4. Click on "Address" / "Email" / "Password" / "Name" table header
5. Choose "Filter by this column"
6. Now choose one of: "Is empty" / "Not empty".
7. There should only be one gray separator line between the dropdown and the button.

### Demo

image

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx [hunk 1]
```diff
@@ -30,6 +30,7 @@ export default function FilterPopoverHeader({
 
   const field = dimension.field();
   const operator = filter.operatorName();
+  const hasEmptyPicker = filter.operator()?.fields.length === 0;
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx:33]: `hasEmptyPicker` will be `false` if `filter.operator()` is falsy.

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 2]
```diff
@@ -154,4 +158,43 @@ describe("FilterPopover", () => {
       });
     });
   });
+  describe("filter rendering", () => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:161]: None of these tests verify that the issue has been fixed.

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 3]
```diff
@@ -154,4 +158,43 @@ describe("FilterPopover", () => {
...
+        />,
+      );
+
+      expect(screen.getByTestId("select-button-content")).toHaveTextContent(
+        "Contains",
+      );
+
+      expect(
+        screen.getByTestId("default-picker-container").childNodes.length,
+      ).toBeGreaterThan(0);
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:197]: I don't understand the name of this test or this assertion.
Can you please describe what is this checking?

**Review by kamilmielnik — CHANGES_REQUESTED** [review]
Please add a test that reproduces the issue.

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx (hunk 1 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx:33]: That's fine, no? If we don't have an operator then we can't have a filter or a picker.

Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx:33]: Oh, ok, because later it's negated - got it.

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx (hunk 3 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:197]: We're checking if the number of children within the `default-picker-container` `div` is 0 - i.e. there is no picker component (i.e. no text box, no dropdown, etc)

File: frontend/src/metabase/components/Popover/Popover.css [hunk 4]
```diff
@@ -177,7 +177,7 @@
   border-bottom-right-radius: 6px;
   border-bottom-left-radius: 6px;
   padding-top: 8px;
-  width: calc(100% - 2px);
+  width: 100%;
```
Comment (oisincoveney) [inline frontend/src/metabase/components/Popover/Popover.css:180]: the only thing I saw the extra 2px doing was leaving a slight space on the border above the "add filter" button which really bothered me

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx [hunk 5]
```diff
@@ -20,3 +20,13 @@ export const Button = styled(BaseButton)<Props>`
...
   }
 `;
+
+export const FilterPopoverSeparator = styled.hr`
+  border: 0;
+  height: 0;
+  border-top: 1px solid ${color("border")};
+`;
+
+export const EmptyFilterPickerPlaceholder = styled.div`
```
Comment (oisincoveney) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx:30]: Mimics the `.PopoverBody--marginBottom` class that the filter pickers have. I didn't want to use the class name on the `div` to keep with our current standards

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx (hunk 3 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx]: Removed this since the test is a little more generic and just checks the separator. More tests can be made in the future for each of the different pickers

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 6]
```diff
@@ -36,82 +37,70 @@ const QUERY = Question.create({
     ["field", PRODUCTS.TITLE, { "source-field": ORDERS.PRODUCT_ID }],
     "asdf",
   ]);
-
 const [RELATIVE_DAY_FILTER, NUMERIC_FILTER, STRING_CONTAINS_FILTER] =
   QUERY.filters();
 
 const dummyFunction = jest.fn();
 
+const setup = ({
```
Comment (oisincoveney) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:45]: Added this since it seemed like we were just doing the same thing over and over again on the setup side

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx [hunk 7]
```diff
@@ -20,3 +20,13 @@ export const Button = styled(BaseButton)<Props>`
...
+  margin-bottom: 60px;
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx:31]: I understand that this style/component exists only because of the `position: absolute` hack on `PopoverFooter`.
I'd rather fix that hack instead of infecting the rest of the code with its repercussions.

The hack can be avoided while preserving [the original goal](https://github.com/metabase/metabase/pull/16308) by adjusting the DOM tree.

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 8]
```diff
@@ -154,4 +129,46 @@ describe("FilterPopover", () => {
       });
     });
   });
+  describe("filter rendering", () => {
+    describe("no-value filters: %s filter", () => {
+      it.each(["is-null", "not-null", "is-empty", "not-empty"])(
+        "should not render picker or separator when selecting a new filter from the column dropdown",
+        async operator => {
+          setup({
+            filter: [operator, ["field", PRODUCTS.TITLE, null], null] as Filter,
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:138]: Can we avoid `as Filter`?

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx [hunk 9]
```diff
@@ -238,6 +242,8 @@ export default function FilterPopover({
   const shouldShowDatePicker = field?.isDate() && !field?.isTime();
   const supportsExpressions = query.database()?.supportsExpressions();
 
+  const hasEmptyPicker = filter.operator()?.fields.length === 0;
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx:245]: How about

```suggestion
  const isPickerEmpty = filter.operator()?.fields.length === 0;
```

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 10]
```diff
@@ -154,4 +129,46 @@ describe("FilterPopover", () => {
...
+    });
+
+    describe("non datetime filters", () => {
+      it.each([
+        { filterElem: STRING_CONTAINS_FILTER, label: "contains" },
+        { filterElem: NUMERIC_FILTER, label: "equals" },
+      ])(
+        "should render the default filter picker with a separator if the $label filter has arguments",
+        async ({ filterElem }) => {
+          setup({ filter: filterElem });
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:161]: Two different names refer to the same thing both here and in `setup`. We should choose one.

```suggestion
        { filter: STRING_CONTAINS_FILTER, label: "contains" },
        { filter: NUMERIC_FILTER, label: "equals" },
      ])(
        "should render the default filter picker with a separator if the $label filter has arguments",
        async ({ filter }) => {
          setup({ filter });
```

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 11]
```diff
@@ -154,4 +129,46 @@ describe("FilterPopover", () => {
...
+            filter: [operator, ["field", PRODUCTS.TITLE, null], null] as Filter,
+            showFieldPicker: false,
+          });
+
+          expect(
+            screen.queryByTestId("filter-popover-separator"),
+          ).not.toBeInTheDocument();
+
+          // if the "empty filter picker" boolean check fails, we will see the default filter picker
+          expect(
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:147]: In the future it'll be hard to say what the `"empty filter picker" boolean check` is without having a full context of this PR.
It'd be better to refer to the actual variable name related to this.

**Review by kamilmielnik — COMMENTED** [review]
Fix looks good, tests look good.

1. I'd like to see us fixing a [hack](https://github.com/metabase/metabase/pull/32172#discussion_r1255295417) rather than spreading its consequences.
2. Vertical paddings around inputs in that popup are not consistent, can we fix this here as well?

image

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx (hunk 9 above)
Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx:245]: Actually, this does not affect children of `FilterPopoverPicker`, but rendering of `FilterPopoverPicker` itself.
So maybe this would be better?

```suggestion
  const hasPicker = filter.operator() & filter.operator().fields.length > 0;
```

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 12]
```diff
@@ -154,4 +129,46 @@ describe("FilterPopover", () => {
       });
     });
   });
+  describe("filter rendering", () => {
+    describe("no-value filters: %s filter", () => {
```
Comment (WiNloSt) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:133]: `%s` is supposed to be in the `it.each` name. You can see that the test names are not using any of the specified options below e.g. `is-null` or `not-null`
image

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 13]
```diff
@@ -154,4 +129,46 @@ describe("FilterPopover", () => {
...
+        "should not render picker or separator when selecting a new filter from the column dropdown",
+        async operator => {
+          setup({
+            filter: [operator, ["field", PRODUCTS.TITLE, null], null] as Filter,
+            showFieldPicker: false,
+          });
+
+          expect(
+            screen.queryByTestId("filter-popover-separator"),
+          ).not.toBeInTheDocument();
```
Comment (WiNloSt) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:144]: It's hard for me to feel confident about tests without asserting certain UI exists. For example, if this component is rendering asynchronously e.g. relying on an API call and displaying the loading spinner, the test would have passed before those UIs that aren't supposed to be rendered are rendered in later render cycle.

Could you add some assertions on the existing UI before this check? It should look something like
```
assertSomethingShouldBeVisible
assertSomethingShouldNotBeRendered
assertSomethingShouldNotBeRendered
```

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx (hunk 12 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:133]: Ah I pushed some changes but not others. Just need to push

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx (hunk 7 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx:31]: Yeah, I want to do that as well, but is it worth pursuing for this issue? I think a bunch of tests and things would need to be written to make sure that we haven't messed anything up, and I think it would blow the scope out of this cosmetic P4.

Comment (WiNloSt) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx:31]: If there's no easy way to fix this I'd skip

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx (hunk 13 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:144]: I ended up switching the tests to check that the "empty" `div` is visible, rather than checking the absence of those two elements

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx (hunk 7 above)
Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx:31]: Good points.

How about we just leave a comment next to it explaining its existence and mentioning `PopoverFooter` name?

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 14]
```diff
@@ -36,82 +37,70 @@ const QUERY = Question.create({
...
 const dummyFunction = jest.fn();
 
+const setup = ({
+  filter: filterElem,
+  query = QUERY,
+  onChange = dummyFunction,
+  onChangeFilter = dummyFunction,
+  showFieldPicker = true,
+}: {
+  filter: Array<any>;
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:52]: With [my comment](https://github.com/metabase/metabase/pull/32172#discussion_r1255306945) I meant using `new Field` instead of `as Field` - not to relax the typing.

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx (hunk 2 above)
Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:132]: Awesome!

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx (hunk 7 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx:31]: done

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx (hunk 14 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:52]: I should have said something about that - the constructor for `Filter` comes from here https://github.com/metabase/metabase/blob/6a071da76e733e3914eac3ebe03b67a85c182e26/frontend/src/metabase-lib/queries/structured/MBQLClause.ts#L9-L13

The only reason why `Filter` was working is because it extends `MBQLClause` which extends `Array`

Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:52]: Ah wait I see what you mean, I'll do that. But yeah the typing wasn't a deliberate relaxation, it was just copying the type that's already there 😄

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 15]
```diff
@@ -154,4 +129,45 @@ describe("FilterPopover", () => {
       });
     });
   });
+  describe("filter rendering", () => {
+    describe("no-value filters", () => {
+      it.each(["is-null", "not-null", "is-empty", "not-empty"])(
+        "should not render picker or separator when selecting '%s' filter from the column dropdown",
+        async operator => {
+          setup({
+            filter: new Filter(
```
Comment (oisincoveney) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:138]: @kamilmielnik let me know if this is what you have in mind

**Review by kamilmielnik — APPROVED** [review]
Looks great!

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 16]
```diff
@@ -36,82 +37,70 @@ const QUERY = Question.create({
...
+  onChangeFilter = dummyFunction,
+  showFieldPicker = true,
+}: {
+  filter: Filter;
+  query?: StructuredQuery;
+  onChange?: (filter: Filter) => void;
+  onChangeFilter?: (filter: Filter) => void;
+  showFieldPicker?: boolean;
+}) => {
+  const filter = new Filter(filterElem, null, query);
```
Comment (WiNloSt) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:58]: I don't get this part. What's the point of recreating a new filter here?

Why can't we just pass along `filter`? e.g.
```ts
const setup = ({
  filter,
  onChange = dummyFunction,
  onChangeFilter = dummyFunction,
  showFieldPicker = true,
}: {
  filter: Filter;
  query?: StructuredQuery;
  onChange?: (filter: Filter) => void;
  onChangeFilter?: (filter: Filter) => void;
  showFieldPicker?: boolean;
}) => {
  renderWithProviders(
    <FilterPopover
      query={QUERY}
      filter={filter}
      onChange={onChange}
      onChangeFilter={onChangeFilter}
      showFieldPicker={showFieldPicker}
    />,
  );
};
```

All tests still pass that way.

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx [hunk 17]
```diff
@@ -36,82 +37,70 @@ const QUERY = Question.create({
...
-
-const [RELATIVE_DAY_FILTER, NUMERIC_FILTER, STRING_CONTAINS_FILTER] =
+const [RELATIVE_DAY_FILTER, NUMERIC_FILTER, STRING_CONTAINS_FILTER]: Filter[] =
   QUERY.filters();
 
 const dummyFunction = jest.fn();
 
+const setup = ({
+  filter: filterElem,
+  query = QUERY,
```
Comment (WiNloSt) [inline frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx:47]: `query` never seem to be used.

**Review by WiNloSt — COMMENTED** [review]
This is almost great! I have a question about constructing a new `Filter` other than that, all good.

File: frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx (hunk 16 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx]: Ah that makes sense considering the typing of `Filter` as an extension of `Array`. I was following what the previous test cases were doing where it was creating a new filter every time, didn't realize that could be nuked.

**Review by WiNloSt — APPROVED** [review]
Looks good to me now. Awesome!

**Review by cdeweyx — APPROVED** [review]
