### PR TITLE
Don't email "new login" detected emails on embedded logins

### LINKED ISSUE #52196: Disable device login emails for authentication via the Embedding SDK
**Context**
https://metaboat.slack.com/archives/C07166YL2UU/p1733956559768879

[Product doc](https://www.notion.so/metabase/Do-not-send-unexpected-emails-to-embedding-users-15b69354c90180ddbdb2f282ca72dd36#15b69354c9018123801ce4074f493c2c)

Customers have noticed that every time they navigate to our page using the Metabase SDK, they receive an email about a new device login.

While we are working on the proper solution, for the public release, we simply want to disable these messages for the Embedding SDK context. Since we are using the same /auth/sso API endpoint, we can’t base this on the endpoint itself. However, as a temporary solution, we can rely on an additional parameter `token` that is used only in the context of the Embedding SDK.

**Suggestion** 
if `(if (not (nil? token))` in `defmethod sso.i/sso-get :jwt` disable sending emails in session-data -> create-session! -> (events/publish-event! :XXX

### PR DESCRIPTION
**Pull request by nvoxland**
Closes #52196

### Description

This PR first does a bit of cleanup around session management in order to centralize the login handling better. 

Then, it is able to move the `maybe-send-login-from-new-device-email!` call from the `after-insert` callback on login_history into `create-session!`

Because create-session doesn't have direct access to the original request, whether the request came from an embedded use case or not is added to the device-info information which is passed to it for use here or anywhere else long-term. The implementation of whether it is embedded or not is just a check for a "token" attribute but that can be changed as needed down the road. 

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Open an embedded chart and see that you don't get a "new login detected" email

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/models/session.clj [hunk 1]
```diff
@@ -29,3 +39,68 @@
...
+  [:and
+   [:map-of :keyword :any]
+   [:map
+    [:id uuid?]
+    [:type [:enum :normal :full-app-embed]]]])
+
+(defmulti create-session!
+  "Generate a new Session for a User. `session-type` is currently either `:password` (for email + password login) or
+  `:sso` (for other login types). Returns the newly generated Session."
+  {:arglists '(^java.util.UUID [session-type user device-info])}
```
Comment (johnswanson) [inline src/metabase/models/session.clj:77]: I see that this was copied from the previous implementation, but I don't really get the type hint here (the `^java.util.UUID` bit). It looks like we're type hinting the whole vector, but... it's not a UUID. I wonder if this was a mistake at some point?

File: src/metabase/models/session.clj [hunk 2]
```diff
@@ -29,3 +39,68 @@
...
+      (assoc session :id session-id))))
+
+(mu/defmethod create-session! :password :- SessionSchema
+  [session-type
+   user :- CreateSessionUserInfo
+   device-info :- request/DeviceInfo]
+  ;; this is actually the same as `create-session!` for `:sso` but we check whether password login is enabled.
+  (when-not (public-settings/enable-password-login)
+    (throw (ex-info (str (tru "Password login is disabled for this instance.")) {:status-code 400})))
+  ((get-method create-session! :sso) session-type user device-info))
```
Comment (johnswanson) [inline src/metabase/models/session.clj:106]: Right now, the `:sso` implementation is kind of the base implementation, but I wonder if it makes sense to make this more explicit? E.g. someone could decide "hey, I'll save the session type as part of the login history" and then we'd accidentally record `:password` logins as `:sso` logins. On the other hand this is small enough right now to see at a glance what's happening, so don't let this block you.

**Review by johnswanson — APPROVED** [review]
LGTM, but could you add a test for the new behavior `embedded=true` case before merging?

File: src/metabase/models/session.clj (hunk 2 above)
Comment (nvoxland) [reply src/metabase/models/session.clj:106]: I think I'll leave it as-is for now, and as the code gets more complex we can think about it

File: src/metabase/models/session.clj [hunk 3]
```diff
@@ -29,3 +39,68 @@
...
+  [:and
+   [:map-of :keyword :any]
+   [:map
+    [:id uuid?]
+    [:type [:enum :normal :full-app-embed]]]])
+
+(defmulti create-session!
+  "Generate a new Session for a User. `session-type` is currently either `:password` (for email + password login) or
+  `:sso` (for other login types). Returns the newly generated Session."
+  [session-type user device-info]
```
Comment (johnswanson) [inline src/metabase/models/session.clj:77]:
```suggestion
  {:arglists '([session-type user device-info])}```

**Comment by nvoxland** [comment]
@metabase-bot backport release-x.52.x
