### PR TITLE
Fix issues with object detail FK queries

### LINKED ISSUE #6830: UI problems with "connected to" counters
Hi,

I have a customers table related to eleven tables. At detail view of a row sometimes the related data is not loading.  If the related data is slow to load and I click at navigate bottons(right and left arrows) I can view the older values of the last data and If I receive the response of the older related data the number is writed and replaced with the actually related data.

- Your browser and the version: last Chrome and last Firefox
- Your operating system: windows 7
- Your databases: SQL Server
- Metabase version: 0.27.2
- Metabase hosting environment: Java jar file
- Metabase internal database:  H2

- Repeatable steps to reproduce the issue:

Go to detail of a row with slowly connected data, navigate to next row.

I think that a correct behaivor is:

- Clear connected data values on load detail page
- Cancel pending querys when navigate to next page
- Link to detail connected data before number is loading
- Paint data values independently and not when all responses are finished

Metabase is a awesome project! 

Thanks!

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #6830 

There were three small related issues:

1. The FK count data never loads.
This issue was caused by a race between loading table metadata and calling `loadObjectDetailFKReferences`. We can't query the FK references until the table metadata has loaded.
2. If you quickly advance from one object to the next the old FK references API calls are still in flight and overwrite the current counts when they return. 
Here, I added a check that the object id hasn't changed. If it has, we throw out the result.
3. When you advance to the prev/next object, you still see the old FK counts until new data loads.
To fix this I added `CLEAR_OBJECT_DETAIL_FK_REFERENCES`. Calling `loadObjectDetailFKReferences` first clears out the old data, which will display spinners until the new data loads.

It didn't seem practical to test this since the initial bug relies on a race condition. Any ideas one a good way to add some coverage?

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx [hunk 1]
```diff
@@ -106,8 +108,10 @@ export class ObjectDetail extends Component {
   }
 
   componentWillReceiveProps(nextProps) {
-    // if the card has changed then reload fk references
-    if (this.props.data != nextProps.data) {
+    // if the card has changed or table metadat laoded then reload fk references
```
Comment (kdoh) [inline frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx]: Small thing but missing the `a` in `metadata` here

**Review by kdoh — APPROVED** [review]
Don't have any smart ideas around testing this but the implementation looks good.
