### PR TITLE
Extra remapped fields

### LINKED ISSUE #67128: Internal remapping triggers externally remapped columns to appear via models
### Describe the bug

When remapping field values using custom values (internal remapping), there are unexpected columns returned for models.

### To Reproduce

1. Table metadata -> Orders -> Quantity -> Display values -> Custom mapping -> Enter A, B, C etc
2. Models -> New -> Orders -> Save as M1
3. New -> Question -> M1 -> Count
4. Open the column picker for breakouts. See there are unexpected columns (Product -> Title, User -> Name)

Image

### Expected behavior

There should be no such columns in this case as in v56

### Logs

_No response_

### Information about your Metabase installation

```JSON
master `9a96a65abf8ead0364bc7dc356b0b5baf951b27c`
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ericnormand**
Closes https://github.com/metabase/metabase/issues/67128

### Description

When saving metadata for a query to report_card, we should disable remaps.

### CODE REVIEW

File: src/metabase/queries/models/card.clj [hunk 1]
```diff
@@ -972,7 +972,7 @@
                                                   (assoc :type :question))
                                                 (m/update-existing :dataset_query lib-be/normalize-query))
          {:keys [metadata metadata-future]} (card.metadata/maybe-async-result-metadata
-                                             {:query     (:dataset_query card-data)
+                                             {:query     (assoc-in (:dataset_query card-data) [:middleware :disable-remaps?] true)
```
Comment (bshepherdson) [inline src/metabase/queries/models/card.clj:978]: Let's at least fight the entropy with a comment explaining the purpose of setting this option.

File: src/metabase/queries/models/card/metadata.clj [hunk 2]
```diff
@@ -176,7 +176,8 @@ saved later when it is ready."
   [query]
   (not-empty (request/with-current-user nil
                (u/ignore-exceptions
-                 (qp.preprocess/query->expected-cols query)))))
+                 (qp.preprocess/query->expected-cols
+                  (assoc-in query [:middleware :disable-remaps?] true))))))
```
Comment (bshepherdson) [inline src/metabase/queries/models/card/metadata.clj:183]: Likewise here, let's explain why this is being set.

**Review by bshepherdson — APPROVED** [review]
