### PR TITLE
Fix query->preprocessed when the query has cached results

### LINKED ISSUE #18579: Sandboxing queries fails with caching is enabled
**Describe the bug**
Sandboxing queries fails with caching is enabled.
Quite difficult to reproduce consistently, but Sandboxing caching is a black box, logging is close to not helpful, and what I wouldn't pay for having a button to clear cache (both for a specific question, and all - should of course also apply to the in-memory Sandboxing cache).

Regression since 1.38.0, works on 1.37.9, but only tested 1.38.2 since there was other problems with cache in 1.38.0/1.

**Workaround**: Disable cache in Admin > Settings > Caching.

**To Reproduce**
1. Admin > People > add user "U1" - add attribute `user_id`=`1` and `user_cat`=`Widget`
2. Admin > Permissions > Sample Dataset > setup Sandboxing for Orders with "User ID"=`user_id`, and Products with "Category"=`user_cat`
3. Admin > Caching > Duration=`0.0001` TTL=`60` (adjust to higher TTL if you have a faster computer, this works for me)
Be aware of `query.average_running_time`, which makes the TTL difficult to predict.
4. Simple question > Sample Dataset > Orders save as "Orders", and Products save as "Products" - add to a dashboard
5. Now open an incognito window and login as "U1" and goto the dashboard
6. Admin: Refresh the dashboard
7. Incognito: Refresh the dashboard - one or both cards should fail - go back and forth between step 6 and 7.
Errors with `Not something with an ID: null` (not to be confused with similar error, when there's a number instead of null)

<details><summary>Full stacktrace</summary>

```
2021-10-20 22:32:36,204 DEBUG middleware.log :: GET /api/user/current 200 2.1 ms (3 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 0 (0 queued)
2021-10-20 22:32:36,219 DEBUG middleware.log :: GET /api/session/properties 200 3.6 ms (2 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 0 (0 queued)
2021-10-20 22:32:36,392 DEBUG middleware.log :: GET /api/database 200 6.9 ms (3 DB calls) App DB connections: 1/13 Jetty threads: 4/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 0 (0 queued)
2021-10-20 22:32:36,468 DEBUG middleware.log :: GET /api/dashboard/9 200 21.1 ms (12 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 0 (0 queued)
2021-10-20 22:32:36,624 DEBUG middleware.log :: GET /api/table/2/query_metadata 200 14.8 ms (12 DB calls) App DB connections: 3/13 Jetty threads: 5/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 0 (0 queued)
2021-10-20 22:32:36,644 DEBUG middleware.log :: GET /api/table/1/query_metadata 200 17.1 ms (9 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 0 (0 queued)
2021-10-20 22:32:36,673 INFO api.card :: Question's average execution duration is 561.0 ms; using 'magic' TTL of 34.0 s 💾
2021-10-20 22:32:36,683 INFO api.card :: Question's average execution duration is 280.0 ms; using 'magic' TTL of 17.0 s 💾
2021-10-20 22:32:36,691 INFO api.card :: Question's average execution duration is 90.0 ms; using 'magic' TTL of 5.0 s 💾
2021-10-20 22:32:36,736 INFO middleware.cache :: Query took 3.0 ms to run; minimum for cache eligibility is 100.0 µs
2021-10-20 22:32:36,736 INFO middleware.cache :: Caching results for next time for query with hash "04e8e5bd". 💾
2021-10-20 22:32:36,749 DEBUG middleware.log :: GET /api/collection/root 200 24.2 ms (2 DB calls) App DB connections: 2/13 Jetty threads: 4/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 2 (0 queued)
2021-10-20 22:32:36,760 DEBUG middleware.log :: POST /api/card/76/query 202 [ASYNC: completed] 61.3 ms (12 DB calls) App DB connections: 2/13 Jetty threads: 3/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 2 (0 queued); h2 DB 1 connections: 0/2 (0 threads blocked)
2021-10-20 22:32:37,889 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 1,
 :started_at #t "2021-10-20T22:32:36.687785+02:00[Europe/Copenhagen]",
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :process-viz-settings? false},
  :database 1,
  :query {:source-table 1},
  :parameters [],
  :async? true,
  :cache-ttl 17},
 :native nil,
 :status :failed,
 :class java.lang.Exception,
 :stacktrace
 ["--> util$the_id.invokeStatic(util.clj:525)"
  "util$the_id.invoke(util.clj:516)"
  "driver.util$database__GT_driver_STAR_.invokeStatic(util.clj:63)"
  "driver.util$database__GT_driver_STAR_.invoke(util.clj:60)"
  "query_processor$query__GT_expected_cols$fn__52292.invoke(query_processor.clj:190)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:42)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor$query__GT_expected_cols.invokeStatic(query_processor.clj:188)"
  "query_processor$query__GT_expected_cols.invoke(query_processor.clj:178)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$merge_metadata$merge_cols__87733$fn__87734.invoke(row_level_restrictions.clj:310)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$merge_metadata$merge_cols__87733.invoke(row_level_restrictions.clj:309)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$merge_metadata.invokeStatic(row_level_restrictions.clj:316)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$merge_metadata.invoke(row_level_restrictions.clj:304)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87755$fn__87757.invoke(row_level_restrictions.clj:336)"
  "query_processor.middleware.add_dimension_projections$remap_results_rff$fn__50394.invoke(add_dimension_projections.clj:302)"
  "query_processor.middleware.format_rows$format_rows$fn__51198$fn__51201.invoke(format_rows.clj:77)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47976$fn__47994.invoke(large_int_id.clj:58)"
  "query_processor.middleware.annotate$add_column_info$fn__42014$fn__42016.invoke(annotate.clj:619)"
  "query_processor.middleware.cache$run_query_with_cache$fn__50839.invoke(cache.clj:179)"
  "query_processor.middleware.limit$limit$fn__48359$fn__48360.invoke(limit.clj:40)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49986$fn__49987.invoke(mbql_to_native.clj:31)"
  "query_processor.context.default$default_reducef.invokeStatic(default.clj:55)"
  "query_processor.context.default$default_reducef.invoke(default.clj:48)"
  "query_processor.context$reducef.invokeStatic(context.clj:69)"
  "query_processor.context$reducef.invoke(context.clj:62)"
  "query_processor.context.default$default_runf$respond_STAR___40099.invoke(default.clj:69)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:485)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:472)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
  "driver.sql_jdbc$fn__89876.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__89876.invoke(sql_jdbc.clj:52)"
  "driver.h2$fn__84733.invokeStatic(h2.clj:83)"
  "driver.h2$fn__84733.invoke(h2.clj:80)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49986.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__50473.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__48359.invoke(limit.clj:37)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:177)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:168)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__50847.invoke(cache.clj:203)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51840.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51884.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__50043.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__36889.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__42014.invoke(annotate.clj:615)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46514.invoke(permissions.clj:108)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51024.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46912.invoke(cumulative_aggregations.clj:60)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87755.invoke(row_level_restrictions.clj:338)"
  "query_processor.middleware.visualization_settings$update_viz_settings$fn__46850.invoke(visualization_settings.clj:63)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47957.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__51610.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51146.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47976.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__51198.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__47348.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__46823.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45764.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46157.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__50398.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50696.invoke(add_implicit_clauses.clj:147)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87755.invoke(row_level_restrictions.clj:333)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48344.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47725.invoke(add_source_metadata.clj:123)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__86141.invoke(column_level_perms_check.clj:30)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50946.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__49295.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46138.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48949.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46211.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__52268.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48728.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51213.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50707$fn__50711.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50707.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46761.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__46949$fn__46950.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__46949.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50996.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__51003.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48674.invoke(add_rows_truncated.clj:35)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__40879.invoke(handle_audit_queries.clj:130)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49972.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48692.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__50982.invoke(process_userland_query.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51293.invoke(catch_exceptions.clj:169)"
  "query_processor.reducible$async_qp$qp_STAR___40183$thunk__40184.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___40183$fn__40186.invoke(reducible.clj:108)"],
 :card_id 64,
 :context :question,
 :error "Not something with an ID: null",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :process-viz-settings? false},
  :info
  {:executed-by 2,
   :context :question,
   :card-id 64,
   :card-name "Plain QB - Products",
   :dashboard-id 9,
   :query-hash
   [-81, -97, 82, -22, -103, -59, -98, -4, -33, -106, 51, -98, 125, -128, 56, -102, 7, -96, 29, 119, 3, 95, -20, -106,
    78, -124, -79, 96, -85, -31, 106, 114]},
  :database 1,
  :query
  {:source-metadata
   [{:description
     "The numerical product number. Only used internally. All external communication should use the title or EAN.",
     :semantic_type :type/PK,
     :table_id 1,
     :coercion_strategy nil,
     :name "ID",
     :settings nil,
     :source :fields,
     :field_ref [:field 4 nil],
     :effective_type :type/BigInteger,
     :parent_id nil,
     :id 4,
     :visibility_type :normal,
     :display_name "ID",
     :fingerprint nil,
     :base_type :type/BigInteger}
    {:description "The international article number. A 13 digit number uniquely identifying the product.",
     :semantic_type nil,
     :table_id 1,
     :coercion_strategy nil,
     :name "EAN",
     :settings nil,
     :source :fields,
     :field_ref [:field 1 nil],
     :effective_type :type/Text,
     :parent_id nil,
     :id 1,
     :visibility_type :normal,
     :display_name "Ean",
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 13.0}}},
     :base_type :type/Text}
    {:description "The name of the product as it should be displayed to customers.",
     :semantic_type :type/Name,
     :table_id 1,
     :coercion_strategy nil,
     :name "TITLE",
     :settings nil,
     :source :fields,
     :field_ref [:field 5 nil],
     :effective_type :type/Text,
     :parent_id nil,
     :id 5,
     :visibility_type :normal,
     :display_name "Title",
     :fingerprint
     {:global {:distinct-count 199, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.495}}},
     :base_type :type/Text}
    {:description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
     :semantic_type :type/Category,
     :table_id 1,
     :coercion_strategy nil,
     :name "CATEGORY",
     :settings nil,
     :source :fields,
     :field_ref [:field 6 nil],
     :effective_type :type/Text,
     :parent_id nil,
     :id 6,
     :visibility_type :normal,
     :display_name "Category",
     :fingerprint
     {:global {:distinct-count 4, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
     :base_type :type/Text}
    {:description "The source of the product.",
     :semantic_type :type/Company,
     :table_id 1,
     :coercion_strategy nil,
     :name "VENDOR",
     :settings nil,
     :source :fields,
     :field_ref [:field 8 nil],
     :effective_type :type/Text,
     :parent_id nil,
     :id 8,
     :visibility_type :normal,
     :display_name "Vendor",
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}},
     :base_type :type/Text}
    {:description
     "The list price of the product. Note that this is not always the price the product sold for due to discounts, promotions, etc.",
     :semantic_type nil,
     :table_id 1,
     :coercion_strategy nil,
     :name "PRICE",
     :settings nil,
     :source :fields,
     :field_ref [:field 3 nil],
     :effective_type :type/Float,
     :parent_id nil,
     :id 3,
     :visibility_type :normal,
     :display_name "Price",
     :fingerprint
     {:global {:distinct-count 170, :nil% 0.0},
      :type
      {:type/Number
       {:min 15.691943673970439,
        :max 98.81933684368194,
        :avg 55.74639966792074,
        :sd 21.711481557852057,
        :q1 37.25154462926434,
        :q3 75.45898071609447}}},
     :base_type :type/Float}
    {:description "The average rating users have given the product. This ranges from 1 - 5",
     :semantic_type :type/Score,
     :table_id 1,
     :coercion_strategy nil,
     :name "RATING",
     :settings nil,
     :source :fields,
     :field_ref [:field 2 nil],
     :effective_type :type/Float,
     :parent_id nil,
     :id 2,
     :visibility_type :normal,
     :display_name "Rating",
     :fingerprint
     {:global {:distinct-count 23, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0, :max 5.0, :avg 3.4715, :sd 1.3605488657451452, :q1 3.5120465053408525, :q3 4.216124969497314}}},
     :base_type :type/Float}
    {:description "The date the product was added to our catalog.",
     :semantic_type :type/CreationTimestamp,
     :table_id 1,
     :coercion_strategy nil,
     :unit :default,
     :name "CREATED_AT",
     :settings nil,
     :source :fields,
     :field_ref [:field 7 {:temporal-unit :default}],
     :effective_type :type/DateTime,
     :parent_id nil,
     :id 7,
     :visibility_type :normal,
     :display_name "Created At",
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147", :latest "2019-04-15T13:34:19.931"}}},
     :base_type :type/DateTime}],
   :fields
   [[:field 4 nil]
    [:field 1 nil]
    [:field 5 nil]
    [:field 6 nil]
    [:field 8 nil]
    [:field 3 nil]
    [:field 2 nil]
    [:field 7 {:temporal-unit :default}]],
   :source-query
   {:source-table 1,
    :filter
    [:=
     [:field 6 nil]
     [:value
      "Widget"
      {:base_type :type/Text,
       :effective_type :type/Text,
       :coercion_strategy nil,
       :semantic_type :type/Category,
       :database_type "VARCHAR",
       :name "CATEGORY"}]],
    :fields
    [[:field 4 nil]
     [:field 1 nil]
     [:field 5 nil]
     [:field 6 nil]
     [:field 8 nil]
     [:field 3 nil]
     [:field 2 nil]
     [:field 7 {:temporal-unit :default}]],
    :metabase-enterprise.sandbox.query-processor.middleware.row-level-restrictions/gtap? true},
   :limit 2000},
  :async? true,
  :cache-ttl 17},
 :data {:rows [], :cols []}}

2021-10-20 22:32:37,910 DEBUG middleware.log :: POST /api/card/64/query 202 [ASYNC: completed] 1.2 s (50 DB calls) App DB connections: 0/13 Jetty threads: 3/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 1 (0 queued); h2 DB 1 connections: 1/2 (0 threads blocked)
2021-10-20 22:32:38,063 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 1,
 :started_at #t "2021-10-20T22:32:36.677137+02:00[Europe/Copenhagen]",
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :process-viz-settings? false},
  :database 1,
  :query {:source-table 2},
  :parameters [],
  :async? true,
  :cache-ttl 34},
 :native nil,
 :status :failed,
 :class java.lang.Exception,
 :stacktrace
 ["--> util$the_id.invokeStatic(util.clj:525)"
  "util$the_id.invoke(util.clj:516)"
  "driver.util$database__GT_driver_STAR_.invokeStatic(util.clj:63)"
  "driver.util$database__GT_driver_STAR_.invoke(util.clj:60)"
  "query_processor$query__GT_expected_cols$fn__52292.invoke(query_processor.clj:190)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:42)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor$query__GT_expected_cols.invokeStatic(query_processor.clj:188)"
  "query_processor$query__GT_expected_cols.invoke(query_processor.clj:178)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$merge_metadata$merge_cols__87733$fn__87734.invoke(row_level_restrictions.clj:310)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$merge_metadata$merge_cols__87733.invoke(row_level_restrictions.clj:309)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$merge_metadata.invokeStatic(row_level_restrictions.clj:316)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$merge_metadata.invoke(row_level_restrictions.clj:304)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87755$fn__87757.invoke(row_level_restrictions.clj:336)"
  "query_processor.middleware.add_dimension_projections$remap_results_rff$fn__50394.invoke(add_dimension_projections.clj:302)"
  "query_processor.middleware.format_rows$format_rows$fn__51198$fn__51201.invoke(format_rows.clj:77)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47976$fn__47994.invoke(large_int_id.clj:58)"
  "query_processor.middleware.annotate$add_column_info$fn__42014$fn__42016.invoke(annotate.clj:619)"
  "query_processor.middleware.cache$run_query_with_cache$fn__50839.invoke(cache.clj:179)"
  "query_processor.middleware.limit$limit$fn__48359$fn__48360.invoke(limit.clj:40)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49986$fn__49987.invoke(mbql_to_native.clj:31)"
  "query_processor.context.default$default_reducef.invokeStatic(default.clj:55)"
  "query_processor.context.default$default_reducef.invoke(default.clj:48)"
  "query_processor.context$reducef.invokeStatic(context.clj:69)"
  "query_processor.context$reducef.invoke(context.clj:62)"
  "query_processor.context.default$default_runf$respond_STAR___40099.invoke(default.clj:69)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:485)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:472)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)"
  "driver.sql_jdbc$fn__89876.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__89876.invoke(sql_jdbc.clj:52)"
  "driver.h2$fn__84733.invokeStatic(h2.clj:83)"
  "driver.h2$fn__84733.invoke(h2.clj:80)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49986.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__50473.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__48359.invoke(limit.clj:37)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:177)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:168)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__50847.invoke(cache.clj:203)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51840.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51884.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__50043.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__36889.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__42014.invoke(annotate.clj:615)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46514.invoke(permissions.clj:108)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51024.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46912.invoke(cumulative_aggregations.clj:60)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87755.invoke(row_level_restrictions.clj:338)"
  "query_processor.middleware.visualization_settings$update_viz_settings$fn__46850.invoke(visualization_settings.clj:63)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47957.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__51610.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51146.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47976.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__51198.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__47348.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__46823.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45764.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46157.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__50398.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50696.invoke(add_implicit_clauses.clj:147)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__87755.invoke(row_level_restrictions.clj:333)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48344.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47725.invoke(add_source_metadata.clj:123)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__86141.invoke(column_level_perms_check.clj:30)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50946.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__49295.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46138.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48949.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46211.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__52268.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48728.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51213.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50707$fn__50711.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50707.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46761.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__46949$fn__46950.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__46949.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50996.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__51003.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48674.invoke(add_rows_truncated.clj:35)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__40879.invoke(handle_audit_queries.clj:130)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49972.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48692.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__50982.invoke(process_userland_query.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51293.invoke(catch_exceptions.clj:169)"
  "query_processor.reducible$async_qp$qp_STAR___40183$thunk__40184.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___40183$fn__40186.invoke(reducible.clj:108)"],
 :card_id 1,
 :context :question,
 :error "Not something with an ID: null",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :process-viz-settings? false},
  :info
  {:executed-by 2,
   :context :question,
   :card-id 1,
   :card-name "Plain QB - Orders",
   :dashboard-id 9,
   :query-hash
   [124, -42, -83, -50, 18, 48, -36, -112, -27, 10, -49, 40, -68, 96, 62, -23, -109, 32, -39, 104, -21, -76, 25, 28,
    31, -10, 50, -60, -88, -9, -77, -15]},
  :database 1,
  :query
  {:source-metadata
   [{:description
     "This is a unique ID for the product. It is also called the “Invoice number” or “Confirmation number” in customer facing emails and screens.",
     :semantic_type :type/PK,
     :table_id 2,
     :coercion_strategy nil,
     :name "ID",
     :settings nil,
     :source :fields,
     :field_ref [:field 12 nil],
     :effective_type :type/BigInteger,
     :parent_id nil,
     :id 12,
     :visibility_type :normal,
     :display_name "ID",
     :fingerprint nil,
     :base_type :type/BigInteger}
    {:description
     "The id of the user who made this order. Note that in some cases where an order was created on behalf of a customer who phoned the order in, this might be the employee who handled the request.",
     :semantic_type :type/FK,
     :table_id 2,
     :coercion_strategy nil,
     :name "USER_ID",
     :settings {},
     :source :fields,
     :field_ref [:field 9 nil],
     :effective_type :type/Integer,
     :parent_id nil,
     :id 9,
     :visibility_type :normal,
     :display_name "User ID",
     :fingerprint {:global {:distinct-count 929, :nil% 0.0}},
     :base_type :type/Integer}
    {:description "The product ID. This is an internal identifier for the product, NOT the SKU.",
     :semantic_type :type/FK,
     :table_id 2,
     :coercion_strategy nil,
     :name "PRODUCT_ID",
     :settings {},
     :source :fields,
     :field_ref [:field 11 nil],
     :effective_type :type/Integer,
     :parent_id nil,
     :id 11,
     :visibility_type :normal,
     :display_name "Product ID",
     :fingerprint {:global {:distinct-count 200, :nil% 0.0}},
     :base_type :type/Integer}
    {:description
     "The raw, pre-tax cost of the order. Note that this might be different in the future from the product price due to promotions, credits, etc.",
     :semantic_type nil,
     :table_id 2,
     :coercion_strategy nil,
     :name "SUBTOTAL",
     :settings nil,
     :source :fields,
     :field_ref [:field 13 nil],
     :effective_type :type/Float,
     :parent_id nil,
     :id 13,
     :visibility_type :normal,
     :display_name "Subtotal",
     :fingerprint
     {:global {:distinct-count 340, :nil% 0.0},
      :type
      {:type/Number
       {:min 15.691943673970439,
        :max 148.22900526552291,
        :avg 77.01295465356547,
        :sd 32.53705013056317,
        :q1 49.74894519060184,
        :q3 105.42965746993103}}},
     :base_type :type/Float}
    {:description
     "This is the amount of local and federal taxes that are collected on the purchase. Note that other governmental fees on some products are not included here, but instead are accounted for in the subtotal.",
     :semantic_type nil,
     :table_id 2,
     :coercion_strategy nil,
     :name "TAX",
     :settings nil,
     :source :fields,
     :field_ref [:field 16 nil],
     :effective_type :type/Float,
     :parent_id nil,
     :id 16,
     :visibility_type :normal,
     :display_name "Tax",
     :fingerprint
     {:global {:distinct-count 797, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0,
        :max 11.12,
        :avg 3.8722100000000004,
        :sd 2.3206651358900316,
        :q1 2.273340386603857,
        :q3 5.337275338216307}}},
     :base_type :type/Float}
    {:description "The total billed amount.",
     :semantic_type nil,
     :table_id 2,
     :coercion_strategy nil,
     :name "TOTAL",
     :settings nil,
     :source :fields,
     :field_ref [:field 17 nil],
     :effective_type :type/Float,
     :parent_id nil,
     :id 17,
     :visibility_type :normal,
     :display_name "Total",
     :fingerprint
     {:global {:distinct-count 10000, :nil% 0.0},
      :type
      {:type/Number
       {:min 12.061602936923117,
        :max 238.32732001721533,
        :avg 82.96014815230805,
        :sd 38.35967664847571,
        :q1 52.006147617878135,
        :q3 109.55803018499738}}},
     :base_type :type/Float}
    {:description "Discount amount.",
     :semantic_type :type/Discount,
     :table_id 2,
     :coercion_strategy nil,
     :name "DISCOUNT",
     :settings nil,
     :source :fields,
     :field_ref [:field 10 nil],
     :effective_type :type/Float,
     :parent_id nil,
     :id 10,
     :visibility_type :normal,
     :display_name "Discount",
     :fingerprint
     {:global {:distinct-count 701, :nil% 0.898},
      :type
      {:type/Number
       {:min 0.17088996672584322,
        :max 61.69684269960571,
        :avg 5.161255547580326,
        :sd 3.053663125001991,
        :q1 2.9786226681458743,
        :q3 7.338187788658235}}},
     :base_type :type/Float}
    {:description "The date and time an order was submitted.",
     :semantic_type :type/CreationTimestamp,
     :table_id 2,
     :coercion_strategy nil,
     :unit :default,
     :name "CREATED_AT",
     :settings {:time_enabled nil},
     :source :fields,
     :field_ref [:field 15 {:temporal-unit :default}],
     :effective_type :type/DateTime,
     :parent_id nil,
     :id 15,
     :visibility_type :normal,
     :display_name "Created At",
     :fingerprint
     {:global {:distinct-count 9998, :nil% 0.0},
      :type {:type/DateTime {:earliest "2016-04-30T18:56:13.352", :latest "2020-04-19T14:07:15.657"}}},
     :base_type :type/DateTime}
    {:description "Number of products bought.",
     :semantic_type :type/Quantity,
     :table_id 2,
     :coercion_strategy nil,
     :name "QUANTITY",
     :settings nil,
     :source :fields,
     :field_ref [:field 14 nil],
     :effective_type :type/Integer,
     :parent_id nil,
     :id 14,
     :visibility_type :normal,
     :display_name "Quantity",
     :fingerprint
     {:global {:distinct-count 62, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0, :max 100.0, :avg 3.7015, :sd 4.214258386403798, :q1 1.755882607764982, :q3 4.882654507928044}}},
     :base_type :type/Integer}],
   :fields
   [[:field 12 nil]
    [:field 9 nil]
    [:field 11 nil]
    [:field 13 nil]
    [:field 16 nil]
    [:field 17 nil]
    [:field 10 nil]
    [:field 15 {:temporal-unit :default}]
    [:field 14 nil]],
   :source-query
   {:source-table 2,
    :filter
    [:=
     [:field 9 nil]
     [:value
      1
      {:base_type :type/Integer,
       :effective_type :type/Integer,
       :coercion_strategy nil,
       :semantic_type :type/FK,
       :database_type "INTEGER",
       :name "USER_ID"}]],
    :fields
    [[:field 12 nil]
     [:field 9 nil]
     [:field 11 nil]
     [:field 13 nil]
     [:field 16 nil]
     [:field 17 nil]
     [:field 10 nil]
     [:field 15 {:temporal-unit :default}]
     [:field 14 nil]],
    :metabase-enterprise.sandbox.query-processor.middleware.row-level-restrictions/gtap? true},
   :limit 2000},
  :async? true,
  :cache-ttl 34},
 :data {:rows [], :cols []}}

2021-10-20 22:32:38,068 DEBUG middleware.log :: POST /api/card/1/query 202 [ASYNC: completed] 1.4 s (52 DB calls) App DB connections: 0/13 Jetty threads: 3/50 (1 idle, 0 queued) (115 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/2 (0 threads blocked)
```

</details>

https://user-images.githubusercontent.com/1447303/138168180-27f8cdc0-34eb-48f7-abd0-316abd22cb73.mp4

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #18579

The problem here was `metabase.query-processor/query->preprocessed` was broken if the query had cached results. `query->preprocessed` is supposed to run the query thru the normal middleware steps and then at the last minute, instead of handing off the query to a driver to be executed, just return the query in its current state. When the query was cached however the caching middleware would ignore the rest of the pipleline and return the cached results instead. 

The fix here was to have `query->preprocessed` add the `:ignore-cached-results?` key to the query so the caching middleware would not attempt to return cached results.

### CODE REVIEW

File: src/metabase/query_processor.clj [hunk 1]
```diff
@@ -171,9 +171,11 @@
...
   Especially helpful for debugging or testing driver QP implementations."
   [query]
-  (preprocess-query query {:preprocessedf
-                           (fn [query context]
-                             (context/raisef (qp.reducible/quit query) context))}))
+  ;; Make sure the caching middleware doesn't try to return any cached results. That will totally break things
+  (preprocess-query (assoc-in query [:middleware :ignore-cached-results?] true)
+                    {:preprocessedf
+                     (fn [query context]
+                       (context/raisef (qp.reducible/quit query) context))}))
```
Comment (camsaul) [inline src/metabase/query_processor.clj:178]: This is the actual fix

File: src/metabase/query_processor/middleware/cache_backend/db.clj [hunk 2]
```diff
@@ -47,7 +44,7 @@
         (throw e)))))
 
 (defn- cached-results [query-hash max-age-seconds respond]
-  (with-open [conn (.getConnection (datasource))
+  (with-open [conn (jdbc/get-connection (db/connection))
```
Comment (camsaul) [inline src/metabase/query_processor/middleware/cache_backend/db.clj:47]: Not specifically related to the fix but my sandboxing test was failing because `toucan.db/connection` was getting bound to `{:connection java.sql.Connection}` by the `with-gtaps` macro which broke this stuff. This change made sense to me anyway since getting a `Connection` from a JDBC spec is something we should let `clojure.java.jdbc` do for us.

**Review by flamber — APPROVED** [review]
I've been beating on this and cannot reproduce the error at all anymore :tada: 

I don't fully understand the with-open change, but looks similar to what is being done [some](https://github.com/metabase/metabase/blob/b461087789d1bfcce754d9019d4a2e321845ed45/test/metabase/db/schema_migrations_test.clj#L241) [other](https://github.com/metabase/metabase/blob/e3fcb9953ccf95752968b6b41820fed9c8b8ebcc/enterprise/backend/src/metabase_enterprise/audit_app/pages/common.clj#L116) places too. Though, some places defines the [pool](https://github.com/metabase/metabase/blob/ce939219f8a3e28ecb00deb232154780a1dcfcef/src/metabase/driver/sql_jdbc/sync/describe_database.clj#L120), but maybe it's doing something different. I don't understand Clojure.

**Comment by camsaul** [comment]
@flamber the `with-open` change just makes so it works if the connection defined is not a pool. It normally always is but in some tests we swap it out for other non-pools so it's just a tweak to make it work either way
