### PR TITLE
shorten filename to not overflow byte limit in some filesystems

### LINKED ISSUE #59233: Serialisation breaks with (Filename too long) when questions/dashboards have a long name
### Describe the bug

It seems that most Linux filesystems (like ext4) have a filename length limit of 255 bytes, not characters. The problem is more evident with Thai characters (UTF-8) typically take 3 bytes per character, so:

79 Thai characters × ~3 bytes = ~237 bytes

So they are running up against the byte limit when filenames + directory paths get too long

### To Reproduce

Create a large question name and then run an export. 

### Expected behavior

I would assume the export is independent of the file name. There are 2 ways to go about it:

1) Only include entity_id in the filename during serialization, not the report name itself since the full question name is already there inside the .yaml file 

2) Cut off the length of the name 

### Logs

2025-06-05 17:38:51,615 ERROR serialization.api :: Error during serialization: /tmp/serdesv2-PGIQZHSAUXMWAYJEYNOP/baac-2025-06-05_17-38/collections/zd9kJ36GCC2HjF5FH3KNi_virtual_audit/Lq2L4R5-pojK_xrQJTKqx_36___%E0%B8%A3%E0%B8%B2%E0%B8%A2%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%81%E0%B/cards/-Q9uuc4YSkjclFzNsVChF_การปฏิบัติงานที่ไม่เป็นไปตามกระบวนการเสนอขาย_ของผลิตภัณฑ์เงินฝากสงเคราะห์ชีวิต_เปรียบเทียบย้อนหลังรา.yaml (Filename too long)

### Information about your Metabase installation

```JSON
1.54 and master
```

### Severity

Was not an issue for normal languages but a customer using Thai is hitting this with basic Question names 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sansolovyov**
in particular ext4 limits file name by 255 *bytes*, not chars, which is doable by using 3-byte chars

fixes #59233

as for `limit-bytes`:

```
;; old one
Evaluation count : 69444 in 6 samples of 11574 calls.
             Execution time mean : 9.385244 µs
    Execution time std-deviation : 993.904052 ns
   Execution time lower quantile : 8.635478 µs ( 2.5%)
   Execution time upper quantile : 10.583322 µs (97.5%)
                   Overhead used : 1.693418 ns

;; new one
Evaluation count : 1005306 in 6 samples of 167551 calls.
             Execution time mean : 604.163079 ns
    Execution time std-deviation : 14.545828 ns
   Execution time lower quantile : 594.599907 ns ( 2.5%)
   Execution time upper quantile : 622.892874 ns (97.5%)
                   Overhead used : 1.693418 ns
```

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 1]
```diff
@@ -175,7 +175,7 @@
                     (when-not continue-on-error
                       (throw e))
                     ;; eschew big and scary stacktrace
-                    (log/warnf "Skipping deserialization error: %s %s" (ex-message e) (ex-data e))
+                    (log/warnf (u/strip-error e "Skipping deserialization error"))
```
Comment (crisptrutski) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:178]: TIL this cool helper, thanks @qnkhuat!

File: src/metabase/models/serialization.clj [hunk 2]
```diff
@@ -843,11 +844,16 @@
...
-  (if (> (count s) max-label-length)
-    (subs s 0 max-label-length)
-    s))
+(def ^:private max-label-bytes 200) ;; 255 is a limit in ext4
+
+(defn- truncate-label [^String s]
+  (let [char-count (count s)
+        byte-count (Utf8/encodedLength s)]
+    (cond
+      (> byte-count max-label-bytes)  (let [target-count (int (* char-count (/ max-label-bytes byte-count)))]
```
Comment (crisptrutski) [inline src/metabase/models/serialization.clj]: This heuristic might not always work - maybe it's worth recurring until it converges?

Also what if there are still too many characters after we truncate the bytes? Maybe this should be `cond->` rather.

Comment (crisptrutski) [reply src/metabase/models/serialization.clj]: I suggest using `metabase.util.string/limit-bytes` instead for the first truncation.

Comment (sansolovyov) [reply src/metabase/models/serialization.clj]: done

File: src/metabase/util/string.clj [hunk 3]
```diff
@@ -56,35 +57,38 @@
...
-        (remove-chars (String. (byte-array (take max-bytes bytes)) "UTF-8") max-bytes)))))
+    (if (<= (Utf8/encodedLength s) max-bytes)
+      s
+      ;; first do big first-pass at truncating, then truncate the rest of the way to preserve a valid string
+      (let [bytes (.getBytes s "UTF-8")
+            end   (loop [pos max-bytes]
+                    (if-not (and (pos? pos)
+                                 (continuation-byte? (aget bytes pos)))
+                      pos
+                      (recur (dec pos))))]
```
Comment (crisptrutski) [inline src/metabase/util/string.clj:76]: nit: having separate cases feels more readable to me
```clojure
(cond 
  (zero? pos) 0 
  (not (continuation-byte? ...)) pos
  :else (recur ...))
```

File: test/metabase/util/string_test.clj [hunk 4]
```diff
@@ -33,7 +33,9 @@
 
 (deftest ^:parallel elide-test
   (is (= "short" (u.str/elide "short" 5)))
-  (is (= "lo..." (u.str/elide "longer string" 5))))
+  (is (= "lo..." (u.str/elide "longer string" 5)))
+  (is (= "short" (u.str/limit-chars "short" 5)))
+  (is (= "longe" (u.str/limit-chars "longer string" 5))))
```
Comment (crisptrutski) [inline test/metabase/util/string_test.clj:38]: Why not give this function its own deftest?

**Review by crisptrutski — APPROVED** [review]
Nice optimization 🧠

File: test/metabase/util/string_test.clj (hunk 4 above)
Comment (sansolovyov) [reply test/metabase/util/string_test.clj:38]: I'm just greedy

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj (hunk 1 above)
Comment (qnkhuat) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:178]: it's actually Sanya's
