### PR TITLE
Filter nulls out of histograms

### LINKED ISSUE #10769: Null value problem when binning
Consider the question "count of rows group by x" for a table containing 100 random numbers in [-10, 10] and 25 null values. The tabular view in Postgres and SQL Server:
tabular
Everything is fine (except the difference in placement of the null bin).  
But when we do bar visualization
- In **Postgres** null values are regarded as 0 and added to the bin containing 0 (and boundaries of the null bin are not correct. Number 10 must be to the left of the null bin).
postgres
- In **SQL Server** the bin containing 0 is added to the null bin.
mssql

<details><summary>To Reproduce</summary>
We create `test` table and insert 100 random numbers in [-10,10] and 25 null values: <br>

<code>
create table test (x float)

insert into test values 
(-3.2223126092533345)
,(7.050839575578113)
,(3.2074002791551504)
,(1.6531328965120657)
,(7.8076327091584545)
,(6.178552695618325)
,(4.927174114457429)
,(-1.783814070643846)
,(8.636848906641298)
,(-3.4882012964242577)
,(-2.5048886803726367)
,(-5.193758834645528)
,(-6.91094410332556)
,(-3.6470152857076377)
,(5.421716530951111)
,(-1.3635556988869464)
,(-8.343558488861195)
,(-6.265092575584765)
,(-7.287182112787236)
,(-4.878867567082992)
,(-3.090376597806099)
,(6.067776253282368)
,(-7.672594779560229)
,(-2.5367566615213484)
,(-7.640617587566281)
,(-2.385034293603381)
,(-6.846520778279648)
,(-5.570270737880236)
,(-5.547801676092925)
,(-1.272618051200185)
,(3.0506246651564783)
,(8.704369776544713)
,(-2.4598352405178803)
,(-2.8024258339491226)
,(9.437043849515554)
,(4.887725773524508)
,(-6.6433659766125714)
,(-7.5528563641134046)
,(9.045725111970121)
,(-7.511771018048547)
,(-0.09354071908656003)
,(6.736192679408365)
,(-6.216943755850284)
,(1.4809404360939364)
,(-1.9293869364266651)
,(8.599942712255064)
,(-7.629128797998062)
,(-1.410675372606791)
,(3.1712732770339045)
,(2.2602898510927982)
,(0.025479593860906036)
,(7.987961887714345)
,(-3.6363892616247684)
,(-7.2130829405863945)
,(0.09583085415528458)
,(3.1029247470589176)
,(-3.1292207028305663)
,(9.4078803723458)
,(-3.485223596670579)
,(-8.684556134473407)
,(9.705175141939733)
,(-2.9900966567873954)
,(6.039290743513185)
,(-1.4279710015581735)
,(-6.405801792643658)
,(-1.3729091587906233)
,(0.5304371564710291)
,(6.522257477589395)
,(8.655852466168888)
,(3.8236156271140924)
,(-7.7258355590412275)
,(-4.018813468983813)
,(9.117860005841298)
,(-0.187841045412938)
,(0.0827970539237981)
,(-8.942645958822574)
,(5.917312490941608)
,(-4.806525792156783)
,(8.053909311768795)
,(-0.3570375968974062)
,(-4.489036609172079)
,(-6.406402867281882)
,(-0.6002289336634643)
,(0.20886301086849635)
,(3.83283876936302)
,(-9.488982240721374)
,(-5.933026857017786)
,(-6.446213539198564)
,(-3.0099311575644583)
,(4.726122053115622)
,(1.7594473233746655)
,(3.5603682522157083)
,(8.178419608758748)
,(2.4001611696574585)
,(5.798585725399244)
,(6.315609817857421)
,(-1.0884192925704088)
,(8.012498894466965)
,(-0.2636994571738924)
,(8.992350061350432)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
,(null)
</code>
Now create a question "count of rows group by x".
</details>
Metabase Version: 0.33.0

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #10769

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/renderer_utils.js [hunk 1]
```diff
@@ -128,9 +128,17 @@ function getParseOptions({ settings, data }) {
 }
 
 export function getDatas({ settings, series }, warn) {
+  const isHist = isHistogram(settings);
```
Comment (tlrobinson) [inline frontend/src/metabase/visualizations/lib/renderer_utils.js]: Should we also filter nulls for any non-ordinal scale?

Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/lib/renderer_utils.js]: just made that change

**Review by tlrobinson — APPROVED** [review]
