### PR TITLE
metadata.cljs: always prefer `lib/source` over `source`

### LINKED ISSUE #66721: Drill-though on a scatterplot from a dashboard causes an error
### Describe the bug

If you have a scatterplot with X axis set to some aggregation, and you try to drill through on that scatterplot from a dashboard specifically, you get an error. Metabase is trying to add a filter on that aggregation.

Note that same drilthrough works just fine when it's done from the question, not on the dashboard.

This is a regression in v56+. Works fine in v55.

https://github.com/user-attachments/assets/3895dad8-701c-4d3d-b96d-96593b38b0c2

### To Reproduce

**For a ready-made example:**
1. Go to the E-commerce example dashboard
2. Switch to "Portfolio Performance" tab
3. On the "Total order amount vs. discount given" scatterplot, click on any data point and select "See these orders"

Image

**For an artisanal handcrafted example:**
1. Make a QB question "Orders > `Count` and `Sum of Total` by `Created At`" on the sample DB
Image

3. Build a scatterplot with `Count` on one axis, and `Sum` of total on the other axis

Image

4. Click on any bubble and try using "See these records" drill through - should work fine
5. Add this scatterplot to a dashboard

Image

6. While on the dashboard, click on any bubble and try using "See these records" drill through - see errorImage

### Expected behavior

The behavior or drill-through on a dashboard should be the same as in the question. There shouldn't be a filter by x value added.

### Logs

_No response_

### Information about your Metabase installation

```JSON
56.1,..., 57.5
```

### Severity

P2, regression

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by galdre**
Closes https://github.com/metabase/metabase/issues/66721.

### Description

Full breakdown of the problem is [here](https://github.com/metabase/metabase/issues/66721#issuecomment-3639423536) on the original issue. **TL;DR:** `source` is a legacy key on the frontend that gets translated to `lib/source`. Some maps are using both `source` and `lib/source`, and the translation layer translates keys and values in completely separate steps. When the time comes to translate the legacy value of `source` into a valid value for `lib/source`, the code can't tell what the key was originally named. So already-valid values were going through the translation process, producing invalid values (e.g., `:source/source/aggregations`).

This adds a step to object parsing to detect that both keys are present; when they are, it sets an option to simply skip `source` during the parsing; secondly, it adds a step in the value parsing to check whether the value is already a keyword namespaced by `source/`.

### How to verify

See repro steps in the original issue. You can use a dashboard like [this one](https://stats.metabase.com/dashboard/6259-scatterplot-drill-through) in a local instance.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/lib/js/metadata.cljs [hunk 1]
```diff
@@ -36,20 +36,23 @@
   "Convert a JS object of *any* class to a ClojureScript object."
   ([xform obj]
    (obj->clj xform obj {}))
-  ([xform obj {:keys [use-plain-object?] :or {use-plain-object? true}}]
+  ([xform obj {:keys [use-plain-object? skip-keys] :or {use-plain-object? true}}]
    (if (map? obj)
      ;; already a ClojureScript object.
-     (into {} xform obj)
+     (into {} xform (cond->> obj
+                      skip-keys (m/remove-keys skip-keys)))
```
Comment (metamben) [inline src/metabase/lib/js/metadata.cljs]: Could we apply `m/remove-keys` unconditionally?

File: src/metabase/lib/js/metadata.cljs [hunk 2]
```diff
@@ -36,20 +36,23 @@
...
      ;; has a plain-JavaScript `_plainObject` attached: apply `xform` to it and call it a day
      (if-let [plain-object (when use-plain-object?
                              (some-> (object-get obj "_plainObject")
                                      js->clj
                                      not-empty))]
-       (into {} xform plain-object)
+       (into {} xform (cond->> plain-object
+                        skip-keys (m/remove-keys skip-keys)))
```
Comment (metamben) [inline src/metabase/lib/js/metadata.cljs]: Here too.

File: src/metabase/lib/js/metadata.cljs [hunk 3]
```diff
@@ -36,20 +36,23 @@
...
        ;; otherwise do things the hard way and convert an arbitrary object into a Cljs map. (`js->clj` doesn't work on
        ;; arbitrary classes other than `Object`)
        (into {}
              (comp
+              (remove (set skip-keys))
```
Comment (metamben) [inline src/metabase/lib/js/metadata.cljs:55]: If we go the conditional way, this should be `(if skip-keys (remove skip-keys) identity)`, I guess.

**Review by metamben — APPROVED** [review]

File: src/metabase/lib/js/metadata.cljs (hunk 1 above)
Comment (galdre) [reply src/metabase/lib/js/metadata.cljs]: `(m/remove-keys nil obj)` throws an exception. But you're right, this is awkward. I removed the conditional and just added `#{}` to the `:or` when destructuring.
