### PR TITLE
Fix for null year units in x-rays 35170

### LINKED ISSUE #35170: null strings appear in x-ray titles
### Describe the bug

When a `year` filter is used, the title shows `null` instead of `year`:
image

### To Reproduce

1. Go to `Browse Data`
2. Select `Sample Database`
3. Select `Orders`
4. Click `Summarize`
5. Group by `Created At by year`

At this point you should see this chart:
image

6. Click on any chart point
7. Select `Automatic Insights...`
8. Select `X-ray`

You will see an x-ray with a null in the title like "A closer look at number of Orders where null of Created At is 2025"

### Expected behavior

It should show the unit of "year" instead of null.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Latest master
```

### Severity

Low

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by markbastian**
Fixing situations where a cell queries with a temporal unit of year produced nulls in description strings like:
    
"A closer look at number of Orders where null of Created At is 2025"
    
The simple fix was just to add `:year` to the `unit-name` function in `metabase.automagic-dashboards.names`. In addition to adding a unit test for this case, several other temporal units were added to the test.
    
Fixes [#35170](https://github.com/metabase/metabase/issues/35170)

### CODE REVIEW

File: test/metabase/automagic_dashboards/names_test.clj [hunk 1]
```diff
@@ -126,3 +126,34 @@
...
+        (testing "Should not contain nulls when temporal-unit is month"
+          (is (= "number of Users where Last Login is in January 2020"
+                 (names/cell-title root
+                                   ["=" ["field" %last_login {:temporal-unit :month}] "2020"]))))
+        (testing "Should not contain nulls when temporal-unit is quarter"
+          (is (= "number of Users where Last Login is in Q1 - 2020"
+                 (names/cell-title root
+                                   ["=" ["field" %last_login {:temporal-unit :quarter}] "2020"]))))
+        ;; This was producing "number of Users where null of Last Login is 2020" originally
+        (testing "Should not contain nulls when temporal-unit is yar"
```
Comment (tsmacdonald) [inline test/metabase/automagic_dashboards/names_test.clj:156]:
```suggestion
        (testing "Should not contain nulls when temporal-unit is year"
```

**Review by tsmacdonald — APPROVED** [review]
:boat:
