### PR TITLE
Use single connection for test data loading & big test data loading improvements

### LINKED ISSUE #45378: Test data loading should be smart enough to reload data when needed automatically
The H2 test data loading code is smart enough to reload the data if it was created in a different session (since it’s an in-memory database. 

We should have BigQuery and Redshift be smart too since these get deleted every few hours in automatic cleanup -- figure out that the DB is gone upstream and recreate it automatically next time you try to use it, ideally in place (using the same `Database`) so you don't lose any test Cards using that DB

We should also do this for DBs we run locally with Docker images, if the Docker image gets nuked and restarted, it should be smart enough to figure it out there too.

It would be good to come up with a general way to do this as opposed to having to write custom code for each driver.

### LINKED ISSUE #45760: MySQL `describe-nested-field-columns` type detection doesn't work correctly unless Database human-friendly name matches physical name
Seems to only affect MySQL AFAIK. MariaDB seems to work ok still, or maybe we're not testing JSON support for it?

There's a bug in the default implementation of `sql-jdbc.sync.interface/describe-nested-field-columns` here

https://github.com/metabase/metabase/blob/d60facf3fc669c0560338d4516ee4a79fbe32b15/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L614

where we're using `(:name database)` (the human-friendly display name) for fetching PKs (`metabase.driver.sql-jdbc.sync.describe-table/get-table-pks`). This does not return any matching PKs if the human-friendly display name (e.g. `Test Data`) does not match the actual physical database name e.g. `test-data`.

If there are no matching PKs then our type JSON type detection logic only checks the most recent values instead of a sampling of oldest and newest values, since it doesn't have a good column to order by. This means our advanced detection logic is basically broken for MySQL unless database display name matches the physical database name,

Tests were previously passing because we used `test-data` for both, but in #45268 I changed this to use `test-data (h2)` for the display name while keeping `test-data` for the physical database name, and it resulted in a test failure.

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #45378
Fixes #45760

- Reuse one connection for test data loading instead of one connection per statement or chunk of rows to load (extremely wasteful). Big CI performance improvement.
- Do not destroy and recreate test datasets several dozen times during test runs.
- Fix a bunch of tests that weren't cleaning up after themselves that previously used to work ok because we destroyed and recreated test data so many times -- especially CSV upload tests, which created dozens of orphaned `UPLOADED_MAGIC_EXAMPLE_` tables.
- Do not destroy existing test datasets with the same name automatically when loading test data. No longer needed since we're smart enough to only load data if needed now
- Added `metabase.test.data.interface/dataset-already-loaded?` to check if given test data is already loaded; if it is, test data loading code will reuse it rather than destroying and recreating it. 
- **BIG! Test data loading code now automatically checks whether test Databases created in previous sessions have test data loaded or not and automatically reloads data in place (reusing existing Database) if needed**
- Test Databases now include driver name in their `:name` e.g. `test-data (postgres)` for ease of use from the GUI
- Overhaul the confusing JDBC test data loading methods. See driver changelog for more info. This is hopefully a stepping stone to more significant overhauls in the near future, specifically #45079
- Increased test data chunk size for Spark SQL from 200 to 1000, which means **test data loading for Spark SQL is now ~5x faster**, e.g. 11 seconds to load the `orders` table instead of 60
- Presto JDBC test data loading is at least 2x faster

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj [hunk 1]
```diff
@@ -784,9 +784,11 @@
...
           (let [db-id       (mt/id)
                 upload-csv! (fn []
-                              (upload-test/upload-example-csv! {:grant-permission? false
-                                                                :schema-name       (:schema table)
-                                                                :table-prefix      "uploaded_magic_"}))]
+                              (upload-test/do-with-uploaded-example-csv!
+                               {:grant-permission? false
+                                :schema-name       (:schema table)
+                                :table-prefix      "uploaded_magic_"}
+                               identity))]
```
Comment (camsaul) [inline enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj:791]: `upload-example-csv!` did not clean up after itself and created a bunch of `UPLOADED_MAGIC_EXAMPLE_CSV_FILE_` tables that never got cleaned up. Tests used to work ok because we deleted and recreated the `test-data` dataset several times in a test run. Now that we don't do that I had to fix these tests. Fixed by replacing this function with `do-with-uploaded-example-csv!` that properly cleans up after itself

File: modules/drivers/sparksql/test/metabase/test/data/sparksql.clj [hunk 2]
```diff
@@ -83,24 +82,20 @@
...
-  [driver spec table-identifier row-or-rows]
+  [driver ^java.sql.Connection conn table-identifier row-or-rows]
   (let [statements (ddl/insert-rows-ddl-statements driver table-identifier row-or-rows)]
-    (sql-jdbc.execute/do-with-connection-with-options
-     driver
-     spec
-     {:write? true}
-     (fn [^java.sql.Connection conn]
-       (try
-         (.setAutoCommit conn false)
```
Comment (camsaul) [inline modules/drivers/sparksql/test/metabase/test/data/sparksql.clj:94]: Auto-commit false here doesn't make sense, databases generally get pretty fussy if you try to do DDL stuff inside transactions. Changed to auto-commit = true. If data loading fails it destroys the whole DB anyway.

File: test/metabase/test/data/impl/get_or_create.clj [hunk 3]
```diff
@@ -147,29 +147,65 @@
   (data-perms/set-database-permission! (perms-group/all-users) new-db-id :perms/create-queries :query-builder-and-native)
   (data-perms/set-database-permission! (perms-group/all-users) new-db-id :perms/download-results :one-million-rows))
 
+(defonce ^:private driver->loaded-datasets
```
Comment (camsaul) [inline test/metabase/test/data/impl/get_or_create.clj:150]: I think as a follow-on I'll try to implement new driver method to check if a test dataset is already loaded or not locally, and also call it automatically if the test data was created by a previous session

File: modules/drivers/oracle/test/metabase/test/data/oracle.clj [hunk 4]
```diff
@@ -169,6 +169,9 @@
                       (u/one-or-many row-or-rows))])
 
 ;;; see also [[metabase.driver.oracle-test/insert-rows-ddl-test]]
+(defn x []
```
Comment (snoe) [inline modules/drivers/oracle/test/metabase/test/data/oracle.clj:172]: This looks like repl code.

File: modules/drivers/presto-jdbc/test/metabase/test/data/presto_jdbc.clj [hunk 5]
```diff
@@ -176,3 +171,32 @@
 (defmethod sql.tx/add-fk-sql :presto-jdbc
   [_driver _dbdef _tabledef _fielddef]
   nil)
+
+(defmethod tx/dataset-already-loaded? :presto-jdbc
```
Comment (snoe) [inline modules/drivers/presto-jdbc/test/metabase/test/data/presto_jdbc.clj:175]: What happens in the case of a partial load? Should we check that all tables are loaded? What if loading, as the last operation, added a secret `_<dataset>_checksum` table+value?

File: test/metabase/query_processor_test/advanced_math_test.clj [hunk 6]
```diff
@@ -14,11 +13,9 @@
         :order-by    [[:asc [:field (mt/id :venues :id) nil]]]
         :limit       1}
        (mt/run-mbql-query venues)
-       mt/rows
-       ffirst
-       double
        ;; Round to prevent minute differences across DBs due to differences in how float point math is handled
-       (u/round-to-decimals 2)))
+       (mt/formatted-rows [2.0])
```
Comment (snoe) [inline test/metabase/query_processor_test/advanced_math_test.clj:17]: nit, it's weird that this looks for `float` to represent precision, I believe the impl could be changed to `number?` safely.

**Review by snoe — APPROVED** [review]
Looks great!

File: modules/drivers/oracle/test/metabase/test/data/oracle.clj (hunk 4 above)
Comment (camsaul) [reply modules/drivers/oracle/test/metabase/test/data/oracle.clj:172]: haha oops yeah it is.

File: modules/drivers/presto-jdbc/test/metabase/test/data/presto_jdbc.clj (hunk 5 above)
Comment (camsaul) [reply modules/drivers/presto-jdbc/test/metabase/test/data/presto_jdbc.clj:175]: Yeah this is still a known problem that I'm hoping to address at some point with a follow-on PR. This is also a problem if test data changes for one reason or another. I did experiment with that secret checksum idea a while back for Postgres so I think there's some promise there. 

I'm hoping this PR is just the first of several incremental PRs that improve test data loading a lot

File: test/metabase/query_processor_test/advanced_math_test.clj (hunk 6 above)
Comment (camsaul) [reply test/metabase/query_processor_test/advanced_math_test.clj:17]: I'm not 100% sure I'm following, `(mt/formatted-rows [2.0] ...)` has been our shorthand for round-to-2-decimal-places since basically forever, the old code was doing exactly the same thing but not using our normal pattern. The old code actually failed with an NPE for me because I messed up test data loading and it was trying to call `(u/round-to-decimals 2 nil)`... that's why I switched it to do the same thing with `u/formatted-rows`, because it has built-in checks for `nil`.

We need the rounding here because otherwise some DBs will return like `1.23456` and others will return `1.23455` and those are not meaningful differences
