### PR TITLE
Remove activity

### LINKED ISSUE #30695: Activity feed leaks metadata
### Product team edit:
- We decided to remove this page from the product. This issue will be closed when this page is removed.
- Details are in the (internal) [product doc](https://www.notion.so/metabase/Remove-the-Activity-page-04d59167ae7649fb90d1cdb562bcb77d).

### Describe the bug

First of all - we love Metabase and use it for an extensive setup of internal and external reporting! So keep up the great work :)

I wanted to raise a behavior we observed when it comes to the "Activity" feed a user can see. Currently it looks like this is not limited by the permission group a user is in. He/she rather sees every activity from everyone updating/creating stuff in our space.

When using Metabase for external reporting with partners it means that they can scroll through the "Activity" feed and see who and (most importantly) what other questions & dashboards are edited. They are not able to access them, but they see all clear names of the questions etc. 

Imagining the following scenario: you have multiple partners that must not see other partners you as a company work with. You create multiple dashboards that have the partners' names in their title. With a little bit of luck they will easily find out what other partners you work with via the "Activity" feed. 

### To Reproduce

1. Create two completely separate user groups: A & B
2. Create a question with user A and save it in a collection user B cannot see
3. Log in as user B and go to "Activity" --> you'll see that user A created a question as well as the clear name of the user & the question

### Expected behavior

Only see activity logs from questions & dashboards that you have access to.

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Chrome 112.0.5615.137 (Offizieller Build) (x86_64)
- OS 12.3.1
- Snowflake & Postgres Database
- Metabase version: 0.46.1
- Metabase hosting env: Elastic Beanstalk
- Metabase internal database: Postgres
```

### Severity

-

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdoh**
Resolves https://github.com/metabase/metabase/issues/30695

In the long long ago activity featured more prominently in Metabase, but we haven't updated or invested in said for a while. This PR puts it to a dignified rest. We may take another crack at it, but for now no need to ship these bits to folks.

- [X] Remove frontend components
- [x] Remove API endpoints used only by the feed (some, like `recent_views` are still used other places)
    - [x] GET `/api/activity/`
- [x] Update any tests (would imagine there aren't many)

reminder: make sure to backport

### CODE REVIEW

**Review by iethree — APPROVED** [review]
FE looks good 👍

File: test/metabase/cmd/endpoint_dox_test.clj [hunk 1]
```diff
@@ -1,6 +1,7 @@
 (ns metabase.cmd.endpoint-dox-test
   (:require
    [clojure.test :refer :all]
+   [metabase.api.activity]
```
Comment (noahmoss) [inline test/metabase/cmd/endpoint_dox_test.clj:4]: Was this line intentional?

**Review by noahmoss — APPROVED** [review]
