### PR TITLE
[dashboards] Handle parallel FKs with dashboard filter values

### LINKED ISSUE #65838: Filter shows wrong display values when table has multiple FK columns pointing to the same column
### Describe the bug

Hello and thanks for taking a look at this!

We are seeing an issue where dashboard filters are showing the incorrect display value mappings when a table has multiple FK columns pointing to the same target column. The FKs are configured to use the same display values field.

Here is a simplified version of our data schema to illustrate what is happening:

Table 1: `teams`
Contains all teams
| columns |
| ------ |
| uid |
| name |

Table 2: `item_ownership`
A hierarchical ownership table with team columns that are FKs pointing to the `team.uid` with display field `team.name`.
| columns |
| ---------- |
| item |
| parent_team - FK => `team.uid` (display field `team.name`) | 
| child_team - FK => `team.uid` (display field `team.name`)

Lets say these tables have the following rows:

`teams`:
| uid | name |
| ------ | ----- |
| crm | CRM |
| sales | Sales |
| root | Root |

`item_ownership`:
| item | parent_team | child_team |
| ------ | ----- | ----- |
| 1 | crm | sales |
| 1 | root | crm |

The issue arrises when you try to filter a question built using the `item_ownership` table. 

Using the `child_team` as the filter column works fine and the filter shows correctly mapped display values:

Image

But when using `parent_team` as the filter column the **display value is not mapped correctly**. I would expect it to still be "CRM - crm":

Image

And looking at the responses coming from `/dashboard/:dashId/params/:paramId/values` I can see the mismatch there as well:
```json
{
    "values": [
        [
            "crm",
            "Sales"
        ]
    ]
}
```

### To Reproduce

1. Create and populate tables as illustrated above
4. Create a question using the table that is not the FK target
5. Add a filter to the dashboard and attempt to filter the question using the first of the two FK columns.
6. If the mapping looked correct, attempt to filter the question using the second of the two FK columns.
7. One of the columns should have resulted in the incorrect mapping.
### Expected behavior

The FK display field value should be correctly mapped for all FK columns even when they are pointed to the same target column.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "duckdb"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-11-12",
      "tag": "v56",
      "hash": "ebc3907"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.9+10-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.9+10-LTS",
    "os.name": "Linux",
    "os.version": "6.1.155",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
}
```

### Severity

blocking an upgrade

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bshepherdson**
Fixes #65838.

### Description

This issue was about dashboard filters showing the wrong value when
the filter was bound to an FK field from a table with multiple FKs to
the same foreign table. The dashboard parameters logic on the BE was
choosing which FK to use for the filter values arbitrarily, meaning that
binding the filter to one of them would work fine, but the other would
give incoherent results.

The fix is to be deliberate about selecting the parameter's column. That
doesn't solve all ambiguous cases, but we really can't help if there's
a multi-hop join that has parallel edges in the middle!

### How to verify

Reproduce with the instructions on the bug. The `avian-singles` test database has
parallel FKs.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#66287** <a href="https://app.graphite.com/github/pr/metabase/metabase/66287?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/metabase/metabase/66287?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: src/metabase/parameters/chain_filter/dedupe_joins.clj [hunk 1]
```diff
@@ -58,19 +58,46 @@
...
+(defn- prefer-requested-fks
+  "Sometimes when trying to find a chain of joins between two requested tables, there are multiple FKs which point
+  between them. These create parallel edges in the graph of joins, and we need to choose one. This function groups
+  edges by their source and target, keeps any single edges, and tries to disambiguate using the input set of preferred
+  field IDs.
+
+  If they cannot be disambiguated (either because multiple FKs are preferred, or none are) then log quietly and choose
+  one arbitrarily."
+  [preferred-fk-ids edges]
+  (if (= (count edges) 1)
```
Comment (ericnormand) [inline src/metabase/parameters/chain_filter/dedupe_joins.clj:70]: Minor nit: I don't think we need this outer `if`. Could be simpler logic: Choose the first preferred or the first edge if there isn't one. Could move the log to a when:

```
(let [preferred ...]
  (when (and (seq (rest preferred))
             (seq (rest edges))
    (log...))
  (or (first preferred) (first edges)))
  ```

**Review by ericnormand — APPROVED** [review]
