### PR TITLE
Check environment variable before db or cache in `setting/get-string`

### LINKED ISSUE #13084: Can't turn off HTTPS redirect
**Describe the bug**
Can't turn off HTTPS redirect since metabase not respecting environment variables. I accidentally enabled always redirect on from admin panel and now i can't turn it off since metabase doesn't have a valid SSL and it is always redirecting to HTTPS. 
[here](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html) mentions 

> The environment variables always take precedence.

But after setting the environment variable i am still being redirected to HTTPS and i'm stuck. 

here are my ENVs
```
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=****
TERM=xterm
JAVA_TOOL_OPTIONS=-Xmx4096m
MB_DB_FILE=/metabase-data/metabase.db
MB_REDIRECT_ALL_REQUESTS_TO_HTTPS=false
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
JAVA_VERSION=jdk-11.0.8+10
JAVA_HOME=/opt/java/openjdk
FC_LANG=en-US
LC_CTYPE=en_US.UTF-8
HOME=/root

```
**Logs** 
`2020/08/07 21:18:39 [error] 11963#11963: *6024 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: ****, server: metabase.example.com, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:3000/", host: "metabase.example.com"`

**To Reproduce**
1. Enable HTTPS redirect from admin panel when you don't have a certificate setup
2. set MB_REDIRECT_ALL_REQUESTS_TO_HTTPS to false

**Expected behavior**
disabling HTTPS redirect

**Information about your Metabase Installation:**

- Metabase version: (e.x. 0.36.3)
- Metabase hosting environment: (Docker stack)

**Severity**
Well it's on production server and no one can access metabase 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by noahmoss**
The [documentation](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html) says that `Many settings in Metabase can be viewed and modified in the Admin Panel, or set via environment variables. The environment variables always take precedence.`

Currently, however, the db or cached value takes precedence. Changing the order should resolve #13084. I've had to adjust a number of tests to reflect this new behavior, but it doesn't seem like any product behavior was affected so I don't think this is a particularly risky change to make.

I've also fixed a number of lint errors in `setting.clj` and `setting_test.clj` that were popping up in my editor, mainly missing docstrings.

### CODE REVIEW

File: test/metabase/test/util.clj [hunk 1]
```diff
@@ -282,21 +282,24 @@
...
       (testing (colorize/blue (format "\nSetting %s = %s\n" (keyword setting-k) (pr-str value)))
-        (f))
+        (if env-var-value
+          (testing (colorize/red (format "NOTE: %s is set to %s by an env var, which takes precedence\n"
+                                         (keyword setting-k) (pr-str env-var-value)))
+            (f))
+          (f)))
       (finally
-        (setting/set! setting-k original-value)))))
+        (setting/set! setting-k original-db-or-cache-value)))))
```
Comment (noahmoss) [inline test/metabase/test/util.clj:302]: Calling this out as a somewhat non-obvious change. Since the env var value now takes precedence when reading a setting, `do-with-temporary-setting-value` would pick it up and then write it back to the DB in the `finally` step. Instead we should just read the DB value directly and write it back at the end of the function.

I've added additional logging if a setting has an env var value set that overrides the temporary setting value, to hopefully avoid tricky testing bugs in the future.

File: test/metabase/api/notify_test.clj [hunk 2]
```diff
@@ -12,66 +12,63 @@
 (use-fixtures :once (fixtures/initialize :db :web-server))
 
 (deftest unauthenticated-test
-  (mt/with-temporary-setting-values [api-key "testing-api-key"]
```
Comment (noahmoss) [inline test/metabase/api/notify_test.clj:15]: Removed the temporary settings from these tests because `api-key` is already being set as an env var in `project.clj`.

File: test/metabase/test/util.clj [hunk 3]
```diff
@@ -282,21 +282,25 @@
...
-        (f))
+        (if env-var-value
+          (testing (colorize/red (format "NOTE: %s is set to %s by an env var, which takes precedence\n"
+                                         (keyword setting-k) (pr-str env-var-value)))
+            (f))
+          (f)))
       (finally
-        (setting/set! setting-k original-value)))))
+        ;; Use set-string! to bypass custom setters, since they might reject the raw string read from the DB
+        (setting/set-string! setting-k original-db-or-cache-value)))))
```
Comment (noahmoss) [inline test/metabase/test/util.clj:303]: Calling this out as a somewhat non-obvious change. Since the env var value now takes precedence when reading a setting, `do-with-temporary-setting-value` would pick it up and then write it back to the DB in the `finally` step. Instead we should just read the DB value directly and write it back at the end of the function.

I've added additional logging if a setting has an env var value set that overrides the temporary setting value, to hopefully avoid tricky testing bugs in the future.

File: src/metabase/integrations/ldap.clj [hunk 4]
```diff
@@ -79,10 +79,15 @@
...
-             (setting/set-json! :ldap-group-mappings new-value)))
+             (cond
+               (string? new-value)
+               (recur (json/parse-string new-value))
+
+               (map? new-value)
+               (do (doseq [k (keys new-value)]
+                     (when-not (DN/isValidDN (name k))
+                       (throw (IllegalArgumentException. (tru "{0} is not a valid DN." (name k))))))
+                   (setting/set-json! :ldap-group-mappings new-value)))))
```
Comment (noahmoss) [inline src/metabase/integrations/ldap.clj:90]: I've changed this because it was throwing an error when used with my revised version of `with-temporary-setting-values` (see below). The macro was reading the JSON string from the DB, changing the setting temporarily, then writing back the original value via the custom setter. But the custom setter would error because it's expecting a Clojure map.

Changing this setter to accept JSON strings fixes the error, but there still is a broader issue that `with-temporary-setting-values` requires custom setters to accept values of the same type & format as what is stored in the DB. Changing `with-temporary-setting-values` to bypass custom setters doesn't work, because it breaks tests that use the `humanization-strategy` setting which has side-effects in its custom setter (changing table & field names). Not sure if there's a clean way to avoid both issues.

File: test/metabase/test/util.clj (hunk 1 above)
Comment (noahmoss) [inline test/metabase/test/util.clj:302]: This function originally had a bug, if a setting wasn't saved in the DB but was set via an env var:
- The original value was fetched with `setting/get`, which would return the env var value
- This value would then be written to the DB in the `finally` form

I guess this never was an issue with the old precedence rules, since usually the DB value was being returned by `setting/get` anyway, but with the new rules it could be fairly confusing. I think this function should only ever read and write the DB value, since `do-with-temp-env-var-value` is a separate helper.

I've instead added some logging if you try to use this function on a setting that is also set by an env var.

Comment (camsaul) [reply test/metabase/test/util.clj:302]: I think the fact that `do-with-temporary-setting-values` won't override the Setting value in certain cases will indeed be a little confusing. How about we just have it check whether the Setting was set via an env var and call `do-with-temp-env-var-value` if it was? That way `do-with-temporary-setting-values` will always do the right thing, and you won't have to be aware of special rules to know when it will and won't work.

Then you'd only need to use `with-temp-env-var-value` for changing env vars that aren't related to Settings

Comment (camsaul) [reply test/metabase/test/util.clj:302]: Either way, if you were to make this change, that little gotcha is definitely something worth calling out in the docstring for `with-temporary-setting-values`. Otherwise you'd either have to notice the `testing` context (which you might not see, if your test is (possibly incorrectly) passing), or go in and read the definition of the implementation function for the macro to learn about an important usage caveat

**Review by camsaul — APPROVED** [review]
_Overall_ this change as a whole LGTM. But I would really prefer making `with-temporary-setting-values` continue to work generally instead of introducing an undocumented situation where it no-ops. I'm worried that it could possibly cause tests to incorrectly pass if people assume it works differently than it actually does. It's also an unnecessary bit of cognitive load I think we can avoid.

So once that minor tweak is in feel free to merge this

File: test/metabase/test/util.clj (hunk 1 above)
Comment (noahmoss) [reply test/metabase/test/util.clj:302]: Yeah, I guess that makes sense -- I'll update the PR to reflect that behavior.
