### PR TITLE
Conditional formatting fixes + string column support + null/not null support

### LINKED ISSUE #7922: Design: Conditional cell formatting for text
This is a design to amend the existing cell coloring functionality from #7644 and add the ability to color text cells. It would allow users to be able to color cells based on statuses. Examples could include "Sale Pending", "Sale Complete", "Sale Lost" for sales or "Failed", "Passed", "Warning" values for common statuses.

Design
- Add support for two more groups of types: string and category
  - The string type will only support single color selection
  - The category type will only support single color selection and will be restricted to one field
- Modify dialog to show field input fields based on the type group being used (radio buttons for numeric for single/gradient, text input for string, category typeahead search for categories)
- Prevent selection of non-related group columns once a field is chosen. If all fields are unselected then the input sections should be hidden and all fields will become selectable.
  - For example if the first field I pick is numeric, I should be prevented from being able to pick a text like field
- Reuse logic from operators in schema_metadata.js
  - Stretch goal: Add support for BETWEEN, NULL, and NOT NULL on numeric types

Example only allowing selection of fields from the same type group:
image

Example criteria from filtering on a text field in the query builder:
image

Original design for numeric cell coloring: #7122

### LINKED ISSUE #8478: Table Color Formatting - Equals Not Working
Looks like the "equal to" and "not equals to" condition for formatting colors on a table isn't working. All of the others conditions appear to work.

Example:
```
create table mbase.number_test (
    str VARCHAR(3) PRIMARY KEY,
    val NUMBER(3)
);

insert into mbase.number_test values ('1', 1);
insert into mbase.number_test values ('2', 2);
insert into mbase.number_test values ('3', 3);
insert into mbase.number_test values ('10', 10);
insert into mbase.number_test values ('20', 20);
insert into mbase.number_test values ('30', 30);
insert into mbase.number_test values ('100', 100);
insert into mbase.number_test values ('200', 200);
insert into mbase.number_test values ('300', 300);

commit;
```

image

All Options:

table_color_equals

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: 68.0.3440.106 (Official Build) (64-bit)
- Your operating system: Windows 7
- Your databases: Oracle
- Metabase version: 0.30.0
- Metabase hosting environment: RHEL 7
- Metabase internal database: MySQL

### LINKED ISSUE #8578: Conditional Formatting - Gradient Format Not Working in Safari
## Conditional Formatting - Gradient Format Not Working

This issue exists in:
Safari, OSX Yosemite, Postgres, 30.3, Ubuntu 12 - hosting.

The conditional formatting gradient does not work in Safari. Although it works perfectly fine in Firefox and Chrome. 

It also does not work at all for custom defined ranges in any browser.

mb1
mb2

### LINKED ISSUE #8636: Gradient conditional formatting does not work when using custom defined ranges
If you set a custom range for a gradient rule, it doesn't render at all. This is on master in Chrome:

conditional-formatting

### PR DESCRIPTION
**Pull request by tlrobinson**
* Gradient not working in Safari. Resolves #8578
* Gradient custom ranges not working. Resolves #8636 
* Text column support + null/not null support. Resolves #7922
* Fix equals operator. Resolves #8478

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/table_format.js [hunk 1]
```diff
@@ -21,8 +21,8 @@ type SingleFormat = {
   type: "single",
   columns: ColumnName[],
   color: Color,
-  operator: "<" | ">" | "<=" | ">=" | "=" | "!=",
-  value: number,
+  operator: "<" | ">" | "<=" | ">=" | "=" | "!=" | "is-null" | "not-null",
```
Comment (MarkRx) [inline frontend/src/metabase/visualizations/lib/table_format.js]: schema_metadata uses an underscore instead of a -. Might want to keep it consistent and use IS_NULL and NOT_NULL

File: frontend/src/metabase/visualizations/lib/table_format.js [hunk 2]
```diff
@@ -127,17 +127,21 @@ function compileFormatter(
...
-        return v => (v <= value ? color : null);
+        return v => (typeof value === "number" && v <= value ? color : null);
       case ">=":
-        return v => (v >= value ? color : null);
+        return v => (typeof value === "number" && v >= value ? color : null);
       case ">":
-        return v => (v > value ? color : null);
+        return v => (typeof value === "number" && v > value ? color : null);
       case "=":
         return v => (v === value ? color : null);
```
Comment (MarkRx) [inline frontend/src/metabase/visualizations/lib/table_format.js]: Mise well fix #8478 while you are in here. Either that or merge #8545

File: frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx [hunk 3]
```diff
@@ -9,24 +9,39 @@ import Radio from "metabase/components/Radio";
...
   "!=": t`not equal to`,
+  "is-null": t`null`,
+  "not-null": t`not null`,
+};
+
+const STRING_OPERATOR_NAMES = {
+  "=": t`equal to`,
+  "!=": t`not equal to`,
+  "is-null": t`null`,
+  "not-null": t`not null`,
```
Comment (MarkRx) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx]: For consistency with how Metabase filters work I think you should also add contains, does not contain, starts with and ends with

**Review by mazameli — COMMENTED** [review]
Verified this fixes the issues in the description. I agree with @MarkRx that it would be great to add the `contains, does not contain, starts with` and `ends with` conditions if it's easy enough.

File: frontend/src/metabase/visualizations/lib/table_format.js (hunk 2 above)
Comment (tlrobinson) [reply frontend/src/metabase/visualizations/lib/table_format.js]: I think it should already be fixed (probably only for new rules)

File: frontend/src/metabase/visualizations/lib/table_format.js (hunk 1 above)
Comment (tlrobinson) [reply frontend/src/metabase/visualizations/lib/table_format.js]: Actually those need to be updated since we started normalizing MBQL to the lower-case-with-dashes style. In fact filters with dashes in them aren't appearing the query builder correctly.

File: frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx (hunk 3 above)
Comment (tlrobinson) [reply frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx]: Done

**Comment by mazameli** [comment]
Ship it ⛵️

**Review by kdoh — APPROVED** [review]

**Comment by mazameli** [comment]
Checked with @tlrobinson and he said this is ready to merge, so I'll do so.
