### PR TITLE
Fix GroupSelect showing groups section title even if section is empty

### LINKED ISSUE #27728: Dropdown shows subheading when there are no subitems to display in LDAP group mappings widget
### To Reproduce

1. In http://localhost:3000/admin/people/groups, be sure you have no groups other than Administrators and All Users.
2. Visit http://localhost:3000/admin/settings/authentication/ldap
3. Scroll all the way down and click on `Edit Mappings`
4. `Create a Mapping`
5. Add one with a name like `cn=People`
6. Click on the dropdown that says `Default ▼`

Notice the blue subheading `Groups`, even though there are no group names below it to pick from.

image

### Expected 

a. If there are groups to list, then the blue subheading "Groups" should be displayed.
b. If there are no groups, then no subheading.

40-second Loom with same:

https://www.loom.com/share/7cffa98727a44d8ab7290011c113040a

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #27728

#### When only Admin groups are offered in Group Mappings Widget

1. Visit http://localhost:3000/admin/people/groups
2. Make sure only All Users and Admins groups exist.
3. Visit http://localhost:3000/admin/settings/authentication/ldap
4. All the way down › `New Mapping`
5. Use a name like `cn=Group`
6. `Add`
7. Click on `Default` to open select box

You should see this:

image

<details>
  <summary>This is what is looked like before</summary>

  image

</details>

#### When other custom groups are set in the system

1. Visit http://localhost:3000/admin/people/groups
2. Add a group.
3. Visit http://localhost:3000/admin/settings/authentication/ldap
4. All the way down › `New Mapping`
5. Use a name like `cn=Group`
6. `Add`
7. Click on `Default` to open select box

Here nothing should be changed from what we have.

image

### CODE REVIEW

File: frontend/src/metabase/admin/people/components/GroupSelect/GroupSelect.tsx [hunk 1]
```diff
@@ -38,35 +46,50 @@ export const GroupSelect = ({
...
-  const other = groups.filter(g => !isAdminGroup(g) && !isDefaultGroup(g));
+
   const adminGroup = groups.find(isAdminGroup);
   const defaultGroup = groups.find(isDefaultGroup);
   const topGroups = [defaultGroup, adminGroup].filter(g => g != null);
+  const groupsExceptDefaultAndAdmin = groups.filter(
+    g => !isAdminGroup(g) && !isDefaultGroup(g),
+  );
+
+  const sections =
```
Comment (gusaiani) [inline frontend/src/metabase/admin/people/components/GroupSelect/GroupSelect.tsx:57]: The things we do to avoid a `let` and array pushes…if too complicated below, please tell me.

Comment (npfitz) [reply frontend/src/metabase/admin/people/components/GroupSelect/GroupSelect.tsx:57]: I think you could use the `isNotNull` check in your filter, which might be a bit more readable.

Personally, I'd probably prefer a `let` with a `switch/case`, or just putting that logic in it's own function.

**Review by npfitz — APPROVED** [review]
Other than the comment above on the big inline if, This looks great to me!

File: frontend/src/metabase/admin/people/components/GroupSelect/GroupSelect.tsx (hunk 1 above)
Comment (gusaiani) [reply frontend/src/metabase/admin/people/components/GroupSelect/GroupSelect.tsx:57]: Thanks @npfitz.

I've extracted a function and it uses `isNotNull`, thanks for the suggestion.

Function could've been used an array push instead of filtering.

Thing is, the Type definition in the Select component is surprisingly complicated.
By doing it like we are here, the type is inferred.
