### PR TITLE
fix(sdk): echarts tooltip is cut off below the viewport height

### LINKED ISSUE #51904: Chart tooltips does not show up below the initial screen height in the sdk
Tooltips of visualizations gets cut off at a point beyond the bottom edge of the initial screen size, then disappears completely. Tooltips will never be visible for any dashboard cards that are below the initial screen size.

The root cause is that the `.echarts-tooltip-container` class only covers the screen height (painted in blue in the below screenshot), so tooltips don't show up below that. If you update the tooltip container to either `position: fixed` (with high z-index) or a very tall height in your browser's inspector, the tooltip now shows up again.

Image

See this [private Loom video](https://www.loom.com/share/43a6ab205ca7410eb12b60559814342e?sid=d39067f8-5359-41de-b516-5dc947ca1a99) for how to reproduce. 

### How to reproduce

- Open an interactive dashboard in the SDK, using a dashboard that has a longer height than your screen size (e.g. an x-rayed auto-generated dashboard)
  - I recommend https://embedded-analytics-sdk-demo.metabase.com/admin/analytics/12 and scroll down to the "Hours when Orders were added" dashboard card - it becomes really obvious.
- Scroll to a dashcard at the edge at your screen. Tooltips gets partially cut off - notice the bottom of the tooltip in the above screenshot.
- Scroll to a dashcard beyond the edge of your screen. Tooltips are no longer visible.

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/51904

### Description

image

Tooltips of visualizations gets cut off at a point beyond the bottom edge of the initial screen size, then disappears completely. This is because `.echarts-tooltip-container only covers the screen height (the blue area in the above screenshot), so tooltips don't show up below that.

This PR updates the tooltip to use `position: fixed` with an appropriate z-index. It also adds an e2e test for the SDK to ensure that tooltips are always properly visible below the fold.

### How to verify

On the SDK:

- Open an interactive dashboard in the SDK, using a dashboard that has a longer height than your screen size (e.g. an x-rayed auto-generated dashboard)
  - You can use the Shoppy demo's Orders dashboard (https://embedded-analytics-sdk-demo.metabase.com/admin/analytics/12) and scroll down to the "Hours when Orders were added" dashboard card.
- Scroll to a dashcard at the edge at your screen. Tooltip should not get cut off anymore, unlike the above screenshot.
- Scroll to a dashcard beyond the edge of your screen. Tooltips should also be visible.

On the main Metabase app, static iframe embedding and iframe embedding with iframe-resizer:

- Tooltips should still continue to work with no visual artifacts.

### Demo

- Cypress E2E Local Runs - [Private Loom](https://www.loom.com/share/e190643a56da4ca79ac03afc26f29e65?sid=3ea15c61-1c12-47d8-9d2a-83594b42b440)

- Tested on Shoppy - [Private Loom](https://www.loom.com/share/dceb33a742044b50bc400ce7c2efaa3e?sid=565f8f2a-6a82-4533-a5e3-a6f2964ed2d5) - below-the-fold echarts tooltip now works

- Tested on iframe (static embedding) and iframe-resizer script - [Private Loom](https://www.loom.com/share/4e3f7cb6419948779e319d8c808c9dd3?sid=44efc182-9923-4c31-8ec7-01a958e65f08)

- Tested on the main app - [Private Loom](https://www.loom.com/share/5b1c9c14c59f4c6f919a19902fef95e6?sid=b0936d18-4d12-49e6-9977-16345a789a8a)

### Checklist

- [x] Tests have been added/updated to cover changes in this PR - E2E

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/tooltip/index.tsx [hunk 1]
```diff
@@ -70,14 +71,18 @@ export const getTooltipBaseOption = (
...
       if (!container) {
         container = document.createElement("div");
         container.classList.add("echarts-tooltip-container");
         container.style.setProperty("overflow", "hidden");
-        container.style.setProperty("position", "absolute");
+        container.style.setProperty("position", "fixed");
         container.style.setProperty("inset", "0");
         container.style.setProperty("pointer-events", "none");
 
+        const tooltipContainerZIndex = `var(--mb-overlay-z-index, ${OVERLAY_Z_INDEX})`;
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/echarts/tooltip/index.tsx:83]: Use the `--mb-overlay-z-index` z-index value if overrides are applied via the SDK theme configuration, otherwise use the default `OVERLAY_Z_INDEX` value as a fallback. We need to add the fallback here because we did not set `--mb-overlay-z-index` by default.

**Review by alxnddr — APPROVED** [review]

**Review by WiNloSt — COMMENTED** [review]
The code looks good. I also tested it locally and it works great. There are a bunch of failing tests which I assume what you mentioned on Slack about the [`is.visible` not doing its job properly](https://metaboat.slack.com/archives/C063Q3F1HPF/p1737117340792459?thread_ts=1737032513.608249&cid=C063Q3F1HPF).

There are 2 things I'd like to see addressed.
1. the new test suite is quite flaky, it even failed half of the time I ran locally.
2. fix all the failing tests re: `be.visible`

File: frontend/src/metabase/visualizations/echarts/tooltip/index.tsx (hunk 1 above)
Comment (heypoom) [reply frontend/src/metabase/visualizations/echarts/tooltip/index.tsx:83]: @WiNloSt Definitely, this was on my mind too. Now that I check the code more carefully, we actually might be able to simply remove the `OVERLAY_Z_INDEX` fallback here as Raffi already added it as `popover.zIndex`'s default:

https://github.com/metabase/metabase/blob/0db07a59977069db6d1ea3dfadff60e819070fc4/frontend/src/metabase/embedding-sdk/theme/default-component-theme.ts#L92-L95

And he already mapped it here:

https://github.com/metabase/metabase/blob/0db07a59977069db6d1ea3dfadff60e819070fc4/frontend/src/metabase/styled-components/theme/css-variables.ts#L25

Let me try to remove it and see if it works.

**Comment by heypoom** [comment]
@WiNloSt Thanks for pointing out the local flakes! I removed the unnecessary wait in https://github.com/metabase/metabase/pull/52310/commits/eedef60b2c80f0170b909f407f1cd0673990b00f and local runs seems to not be flaking anymore - [Private Loom](https://www.loom.com/share/e190643a56da4ca79ac03afc26f29e65?sid=a08bd477-60c1-45d0-8814-9f799b4ccbbe)

**Comment by heypoom** [comment]
@WiNloSt I fixed the `be.visible` and `:visible` tests to use a custom visibility check that emulates what Cypress does, they're working reliably now. Also, the flakes in the new test suite is gone as far as my local environment goes 🙏🏻

**Review by npretto — APPROVED** [review]
The PR looks good, I'm not a fan of having to much logic in tests but I guess we don't have a viable solution to test this outside of visual regressions tests.
I'd feel more comfortable if we waited for Kelvin to re-review again before merging 🙏

**Review by WiNloSt — APPROVED** [review]
The test works now. Can you ping Sasha for a re-review since he probably didn't see new echart E2E test util.

**Review by alxnddr — APPROVED** [review]
