### PR TITLE
Change Funnel subtitle to display metric rather than dimension

### LINKED ISSUE #19198: Funnel chart label states the step when it should state the measure
**Describe the bug**
The top-of-funnel label reflects the step, when it should state the name of the measure.

**To Reproduce**
Reproduce in the notebook editor like so:

image

Then set visualization to funnel.

**Expected behavior**
The label under 5,061 should be the measure, in this case "Count".

image

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.252-131.483.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "bigquery",
      "redshift",
      "druid",
      "mongo",
      "googleanalytics",
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.22"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-03",
      "tag": "v1.42.0-SNAPSHOT",
      "branch": "master",
      "hash": "7fc4fc7"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}

```

**Severity**
Makes reading the funnel chart confusing.

**Additional context**
See also https://github.com/metabase/metabase/issues/19197.

### PR DESCRIPTION
**Pull request by npfitz**
Fixes #19198

Quick change to Funnel charts to display the name of the metric in the main subtitle, rather than the name of the dimension. Tested with Counts, Averages, Sums etc.

Before:
image

After:
image

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/FunnelNormal.jsx [hunk 1]
```diff
@@ -65,6 +65,9 @@ export default class FunnelNormal extends Component {
 
     let remaining = rows[0][metricIndex];
 
+    console.log(cols, metricIndex);
+    console.log(rows);
```
Comment (losrebellos) [inline frontend/src/metabase/visualizations/components/FunnelNormal.jsx:69]: Can we remove the logs?

**Review by alxnddr — APPROVED** [review]
