### PR TITLE
Show error when running selected SQL

### LINKED ISSUE #11471: Native query "Run selected text" hides errors
**Describe the bug**
When using "Run selected text" in Native, it doesn't show any error message - just blank space.

**To Reproduce**
1. Native question > Sample Dataset
2. Run query `SELECT * FROM ORDERS WHERE ID<3 AND FAKECOLUMN=1 ORDER BY ID`, returns error message `Column "FAKECOLUMN" not found`
3. Select only this text and run query (Run selected text) `SELECT * FROM ORDERS WHERE ID<3 AND FAKECOLUMN=1` and no error message is shown, but the log says `:error "Column \"FAKECOLUMN\" not found"`
4. Even worse if you accidentally just selected a word/string because of copy-paste or bad mouse-move and try to run the query, since it doesn't provide any feedback on what's going on.

**Screenshots**
Screencast 2019-12-08 13 38 46

**Information about your Metabase Installation:**
Metabase `master` on Firefox 70

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #11471

This problem was that we only displayed errors if the query wasn't dirty. My hack/fix was to change that behavior. We now show the error as long as the last run query was an error.

@mazameli what do you think about that change? Should errors disappear as soon as the query is edited?

If we do want want to keep the previous behavior, I think the right fix is to correct our definition of dirty for selections. That's a bit more complicated, but doable.

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx [hunk 1]
```diff
@@ -472,9 +473,16 @@ export default class NativeQueryEditor extends Component {
...
+            <DataReferenceButton
+              {...this.props}
+              size={ICON_SIZE}
+              className="mt3"
+            />
+            <NativeVariablesButton
+              {...this.props}
+              size={ICON_SIZE}
+              className="mt3"
+            />
```
Comment (paulrosenzweig) [inline frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx]: unrelated change, it fixes a react warning I saw while testing

File: frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx [hunk 2]
```diff
@@ -19,6 +19,7 @@ import "ace/mode-pgsql";
 import "ace/mode-sqlserver";
 import "ace/mode-json";
 
+import "ace/snippets/text";
```
Comment (paulrosenzweig) [inline frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx]: unrelated, fixed an error

**Comment by mazameli** [comment]
I think this change makes more sense. 👍

**Review by kdoh — APPROVED** [review]
Looks good. Just had one question on the test.

File: frontend/test/metabase/query_builder/components/NativeQueryEditor.cy.spec.js [hunk 3]
```diff
@@ -0,0 +1,42 @@
+import { signInAsNormalUser } from "__support__/cypress";
+describe("NativeQueryEditor", () => {
+  beforeEach(() => {
+    signInAsNormalUser();
+    cy.on("uncaught:exception", (err, runnable) => {
+      // ignore the error if it's a "script error"
+      if (err.message.match(/^Script error./)) {
```
[the remark this answers is not in the document]
Comment (paulrosenzweig) [reply frontend/test/metabase/query_builder/components/NativeQueryEditor.cy.spec.js]: Cypress fails tests on any uncaught error. I think that's a good move on their part, but unfortunately, we have a handful of "benign" uncaught errors.

I first tried to fix the error (which I believe is coming from Ace). When I couldn't find it, I decided to just ignore it. Instead of ignoring all errors, I match the beginning of the Cypress message that wraps the error. It's still a broad category of errors but somewhat more specific to what I was looking for.
