### PR TITLE
Handle rubbish in mongodb versionArray

### LINKED ISSUE #29678: Mongodb won’t work if version does fall into the “semantic-version-gte” pattern (Percona)
**Describe the bug**
After upgrading to metabase version 0.46, I can't access to any mongodb databases.
From what I've seen, in metabase database, table `metabase_database`, the dbms_version is wrong, because mongodb doest not follow semantic version.

What i get from the `dbms_version` => {"version":"5.0.14-12","semantic-version":[5,0,15,-100]}  

**Logs**

```
2023-03-30 10:07:39,751 INFO driver.impl :: Initializing driver :mongo...
2023-03-30 10:07:39,753 INFO plugins.classloader :: Added URL file:/plugins/mongo.metabase-driver.jar to classpath
2023-03-30 10:07:39,755 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.mongo...
WARNING: random-uuid already refers to: #'clojure.core/random-uuid in namespace: monger.util, being replaced by: #'monger.util/random-uuid
2023-03-30 10:07:41,857 INFO driver.impl :: Registered driver :mongo  🚚
2023-03-30 10:07:41,897 INFO metabase.util :: Load lazy loading driver :mongo took 2.1 s
2023-03-30 10:07:41,916 ERROR metabase.task :: Error initializing task :metabase.task.persist-refresh/PersistRefresh
clojure.lang.ExceptionInfo: Input to semantic-version-gte does not match schema: 

	   [(named [nil nil nil (not ("Integer greater than or equal to zero" -100))] xv) nil]  

 {:type :schema.core/error, :schema [#schema.core.One{:schema [(constrained Int "Integer greater than or equal to zero")], :optional? false, :name xv} #schema.core.One{:schema [(constrained Int "Integer greater than or equal to zero")], :optional? false, :name yv}], :value [[5 0 15 -100] [4 2]], :error [(named [nil nil nil (not ("Integer greater than or equal to zero" -100))] xv) nil], :toucan2/context-trace [["execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection" {:toucan2.jdbc.query/sql-args ["SELECT * FROM \"metabase_database\""]}] ["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}] ["resolve connection" {:toucan2.connection/connectable :default}] ["resolve connection" {:toucan2.connection/connectable nil}] {:toucan2.pipeline/rf #object[clojure.core$map$fn__5931$fn__5932 0x658e0f88 "clojure.core$map$fn__5931$fn__5932@658e0f88"]} ["with compiled query" {:toucan2.pipeline/compiled-query ["SELECT * FROM \"metabase_database\""]}] ["with built query" {:toucan2.pipeline/built-query {:select [:*], :from [[:metabase_database]]}}] ["with resolved query" {:toucan2.pipeline/resolved-query {}}] ["with parsed args" {:toucan2.pipeline/query-type :toucan.query-type/select.instances, :toucan2.pipeline/parsed-args {:queryable {}}}] ["with model" {:toucan2.pipeline/model :metabase.models.database/Database}] ["with unparsed args" {:toucan2.pipeline/query-type :toucan.query-type/select.instances, :toucan2.pipeline/unparsed-args (:metabase.models.database/Database)}]]}
	at metabase.driver.util$fn__46893$semantic_version_gte__46898.invoke(util.clj:209)
	at metabase.driver.mongo$fn__120574.invokeStatic(mongo.clj:295)
	at metabase.driver.mongo$fn__120574.invoke(mongo.clj:290)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.util$features$iter__46856__46860$fn__46861.invoke(util.clj:199)
```

**To Reproduce**

**Expected behavior**

We should have a semantic version correct in `metabase_database` table
```
{"version":"5.0.14-12","semantic-version":[5,0,14]}
```

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  }
}
- Your databases: MongoDB
- Metabase version: 0.46
- Metabase hosting environment: Kubernetes / Docker
- Metabase internal database: postgre

**Severity**
Critical

**Additional context**

### PR DESCRIPTION
**Pull request by metamben**
Fixes #29678.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30879)

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo.clj [hunk 1]
```diff
@@ -183,9 +183,14 @@
 (defmethod driver/dbms-version :mongo
   [_ database]
   (with-mongo-connection [^com.mongodb.DB conn database]
-    (let [build-info (mg/command conn {:buildInfo 1})]
+    (let [build-info (mg/command conn {:buildInfo 1})
+          version-array (get build-info "versionArray")
+          sanitized-version-array (into [] (take-while nat-int?) version-array)]
+      (when (not= (take 3 version-array) (take 3 sanitized-version-array))
+        (log/warnf "sanitizing versionArray %s results in %s, losing information"
```
Comment (dpsutton) [inline modules/drivers/mongo/src/metabase/driver/mongo.clj:190]: how often is `dbms-version` called? Do we compute once and stick in the `metabase_database` table or get it dynamically a bunch? Wondering how many times this warn will appear.

Also, from the [thread](https://metaboat.slack.com/archives/C013N8XL286/p1684501559790059) the offending value was  `[4 2 18 -100]`. Your `sanitized-version-array` will throw away the `-100` but it's count will be 3 and you will not fire the warning that you are losing information despite throwing away the `-100`.

Comment (metamben) [reply modules/drivers/mongo/src/metabase/driver/mongo.clj:190]: The normal pattern is to get the version from the `:dbms_version` field of the DB object like this:

```clojure
(defmethod driver/database-supports? [:mongo :expressions]
  [_driver _feature db]
  (-> (:dbms_version db)
      :semantic-version
      (driver.u/semantic-version-gte [4 2])))
```

I don't intend to warn about losing anything after the patch version.

File: modules/drivers/mongo/test/metabase/driver/mongo_test.clj [hunk 2]
```diff
@@ -488,3 +489,19 @@
...
+  (mt/test-driver :mongo
+    (testing "Negative values in versionArray are ignored (#29678)"
+      (with-redefs [mg/command (constantly {"version" "4.0.28-23"
+                                            "versionArray" [4 0 29 -100]})]
+        (is (= {:version "4.0.28-23"
+                :semantic-version [4 0 29]}
+               (driver/dbms-version :mongo (mt/db))))))
+
+    (testing "Any values after rubbish in versionArray are ignored"
+      (with-redefs [mg/command (constantly {"version" "4.0.28-23"
```
Comment (dpsutton) [inline modules/drivers/mongo/test/metabase/driver/mongo_test.clj:503]: i see where the negative numbers come from. I'm surprised the solution wasn't to parse this as `[4 0 28]` instead of sanitizing `[4 0 "NaN" 29]` or `[4 0 "NaN" -29]`.

For instance, my h2 version is
```clojure
{:flavor "H2",
 :version "2.1.214 (2022-06-13)",
 :semantic-version [2 1]}
```

and i'm surprised to see it as `[2 1]` and not `[2 1 214]`. Is that too complicated of a fix?

Comment (metamben) [reply modules/drivers/mongo/test/metabase/driver/mongo_test.clj:503]: This is because whenever a driver offers a machine processable (i.e., parsed) version, we use that as semantic version.  The JDBC driver and Mongo provide such versions.

I agree it's ugly that the human readably and the machine processable versions are out of sync, but the source of that is in the driver.

**Review by dpsutton — APPROVED** [review]

**Review by dpsutton — APPROVED** [review]
