### PR TITLE
Fix handling of object columns in pie charts

### LINKED ISSUE #52686: Pie chart represents only a single series when there should be more
### Describe the bug

There's data that the pie chart will not represent even though the values are the same as other series

### To Reproduce

1) set up Metabase with MongoDB
2) add to the MongoDB this table

```
// Connect to your MongoDB database
use sample

// Define the collection name
const collectionName = "myCollection";

// Drop the collection if it exists (optional, for clean slate)
db[collectionName].drop();

// Insert documents into the collection
db[collectionName].insertMany([
    {
        key1: "value1",
        key2: { nestedKey1: "nestedValue1", nestedKey2: null },
        key3: "value3",
        key4: null,
        key5: { nestedKey1: "nestedValue2" },
        key6: "value6",
        key7: null,
        key8: { nestedKey1: "nestedValue3", nestedKey2: "nestedValue4" },
        key9: null,
        key10: "value10"
    },
    {
        key1: null,
        key2: { nestedKey1: "nestedValue1" },
        key3: null,
        key4: "value4",
        key5: null,
        key6: { nestedKey1: "nestedValue5", nestedKey2: null },
        key7: "value7",
        key8: null,
        key9: { nestedKey1: "nestedValue6" },
        key10: null
    },
    {
        key1: "value1",
        key2: "value2",
        key3: null,
        key4: null,
        key5: { nestedKey1: "nestedValue7", nestedKey2: "nestedValue8" },
        key6: null,
        key7: "value7",
        key8: "value8",
        key9: null,
        key10: { nestedKey1: "nestedValue9" }
    },
    {
        key1: null,
        key2: null,
        key3: "value3",
        key4: { nestedKey1: "nestedValue10", nestedKey2: "nestedValue11" },
        key5: null,
        key6: null,
        key7: { nestedKey1: "nestedValue12" },
        key8: null,
        key9: "value9",
        key10: "value10"
    },
    {
        key1: "value1",
        key2: null,
        key3: "value3",
        key4: null,
        key5: { nestedKey1: "nestedValue13" },
        key6: { nestedKey1: "nestedValue14", nestedKey2: null },
        key7: null,
        key8: "value8",
        key9: null,
        key10: { nestedKey1: "nestedValue15", nestedKey2: "nestedValue16" }
    }
]);

print("Documents with nested properties inserted successfully!");
```

3) sync
4) go to a table view on that new table
5) Make a count of Key5

Image

6) Do a pie chart

See that there's many series that we don't render (and the series has the count wrong)

Image

Image

### Expected behavior

We should render the correct data

### Logs

NA

### Information about your Metabase installation

```JSON
v52.6
```

### Severity

P2 only because no one reported it yet

### Additional context

NA

### PR DESCRIPTION
**Pull request by kevinkelleher12**
Closes #52686

### Description

This fix uses `JSON.stringify` to aggregate object columns in pie charts rather than `String` (which mapped all objects to `'[object Object]'`). In addition, this PR makes changes to:

- Use `getKeyFromDimensionValue` consistently rather than `String`
- Skips click events when clicking on an object column in a pie chart. The underlying records filter doesn't work when the value is an object, and it seems like a big lift to get it to work for what is probably a fairly niche use case
- Passes the existing colors in `pie.rows` into `getColorsForValues`. `getColorsForValues` is careful to respect the existing color mapping and assign new colors as needed to avoid duplicating colors. Previously, without passing the saved colors in `pie.rows` to `getColorsForValues`, a user could end up with duplicate colors.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Follow the steps in #52686
2. Verify the pie chart has 4 slices for the 4 different values of key5 as expected

### Demo

Before:
image

After:
image

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/shared/settings/pie.ts [hunk 1]
```diff
@@ -66,6 +65,8 @@ export const getDefaultSliceThreshold = () => SLICE_THRESHOLD * 100;
 export function getKeyFromDimensionValue(dimensionValue: RowValue) {
   if (dimensionValue == null) {
     return NULL_DISPLAY_VALUE;
+  } else if (typeof dimensionValue === "object") {
+    return JSON.stringify(dimensionValue);
   }
   return String(dimensionValue);
```
Comment (iethree) [inline frontend/src/metabase/visualizations/shared/settings/pie.ts:68]: might well just use JSON.stringify. it'll be the same for primitives.
```suggestion
  } 
return JSON.stringify(dimensionValue);
```

File: .loki/reference/chrome_laptop_Components_Table_Default.png
Comment (iethree) [inline .loki/reference/chrome_laptop_Components_Table_Default.png:1]: why are these images deleted?

File: .loki/reference/chrome_laptop_Viz_Static_Viz_PieChart_Null_Dimension.png
Comment (iethree) [inline .loki/reference/chrome_laptop_Viz_Static_Viz_PieChart_Null_Dimension.png:1]: I'm a little concerned that we've changed default color assignment. Can we do this in a way that doesn't change existing charts?

**Review by iethree — DISMISSED** [review]

File: .loki/reference/chrome_laptop_Components_Table_Default.png
Comment (kevinkelleher12) [reply .loki/reference/chrome_laptop_Components_Table_Default.png:1]: I can't find the commit that did it, but someone deleted these stories. The images weren't deleted until I ran the loki update workflow. These are deleted on master as well

File: frontend/src/metabase/visualizations/shared/settings/pie.ts (hunk 1 above)
Comment (kevinkelleher12) [reply frontend/src/metabase/visualizations/shared/settings/pie.ts:68]: actually I think we want to keep it as is, or at the very least handle strings separately:

`JSON.stringify("foo")` returns '"foo"'

`String("foo")` returns "foo"

**Review by alxnddr — APPROVED** [review]
