### PR TITLE
Make sure field refs returned by sandboxing middleware match non-sandboxed field refs

### LINKED ISSUE #13641: Drill-through not working on implicit joined tables with sandboxes
**Describe the bug**
Not possible for sandboxed user to drill-through when question is using implicit joins and grouped by a joined column.
Doesn't matter if field remapping to the joined table.

Workaround is to use explicit joins (manually joining tables in the question).

**To Reproduce**
1. Admin > People > create user "U1" with attribute `user_id=1`
2. Admin > Permissions > Sample Dataset > revoke all, sandbox Orders on "User ID"=`user_id`, and full access to Products
image
3. Custom question > Sample Dataset > Orders - summarize Count by Category, save as "Q1"
image
4. Login as "U1" > open "Q1" > click one of the bars to "View these Orders" - fails with `Column "source.CATEGORY" not found;`

<details><summary>Full stacktrace</summary>

```
2020-10-30 16:54:22,850 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 1,
 :started_at #t "2020-10-30T16:54:22.168199+01:00[Europe/Copenhagen]",
 :state "42S22",
 :json_query
 {:type "query", :query {:source-table 2, :filter ["and" ["=" ["field-id" 6] "Gadget"]]}, :database 1, :parameters [], :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)"
  "org.h2.expression.Comparison.optimize(Comparison.java:177)"
  "org.h2.command.dml.Select.prepare(Select.java:861)"
  "org.h2.command.Parser.prepareCommand(Parser.java:283)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)"
  "org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1135)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:267)"
  "--> driver.sql_jdbc.execute$fn__44809.invokeStatic(execute.clj:239)"
  "driver.sql_jdbc.execute$fn__44809.invoke(execute.clj:237)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:257)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:254)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:390)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:386)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc$fn__82086.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__82086.invoke(sql_jdbc.clj:47)"
  "driver.h2$fn__80898.invokeStatic(h2.clj:87)"
  "driver.h2$fn__80898.invoke(h2.clj:84)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49316.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__48591.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__49481.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__47392.invoke(auto_parse_filter_values.clj:44)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__43451.invoke(wrap_value_literals.clj:149)"
  "query_processor.middleware.annotate$add_column_info$fn__43314.invoke(annotate.clj:575)"
  "query_processor.middleware.permissions$check_query_permissions$fn__48466.invoke(permissions.clj:70)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__49999.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__48664.invoke(cumulative_aggregations.clj:61)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__51266.invoke(row_level_restrictions.clj:292)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__50236.invoke(resolve_joined_fields.clj:36)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__50555.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__46997.invoke(add_implicit_joins.clj:254)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__49277.invoke(large_int_id.clj:44)"
  "query_processor.middleware.limit$limit$fn__49302.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__49257.invoke(format_rows.clj:84)"
  "query_processor.middleware.desugar$desugar$fn__48730.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__47751.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__48268.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__46545.invoke(add_dimension_projections.clj:318)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__46748.invoke(add_implicit_clauses.clj:141)"
  "metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__51266.invoke(row_level_restrictions.clj:287)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47146.invoke(add_source_metadata.clj:105)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__50968.invoke(column_level_perms_check.clj:24)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50196.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__47339.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__48315.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__49981.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__48367.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__48986.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__47155.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50917.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50207$fn__50211.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50207.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49204.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__50926$fn__50927.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__50926.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__48244.invoke(cache.clj:214)"
  "query_processor.middleware.validate$validate_query$fn__50935.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__49329.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47015.invoke(add_rows_truncated.clj:36)"
  "metabase_enterprise.audit.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__31552.invoke(handle_audit_queries.clj:165)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__50902.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48607.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__50070.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__48550.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___40109$thunk__40110.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___40109.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___40118$fn__40121.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___40118.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:237)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:233)"
  "query_processor$fn__51311$process_query_and_save_execution_BANG___51320$fn__51323.invoke(query_processor.clj:249)"
  "query_processor$fn__51311$process_query_and_save_execution_BANG___51320.invoke(query_processor.clj:241)"
  "query_processor$fn__51355$process_query_and_save_with_max_results_constraints_BANG___51364$fn__51367.invoke(query_processor.clj:261)"
  "query_processor$fn__51355$process_query_and_save_with_max_results_constraints_BANG___51364.invoke(query_processor.clj:254)"
  "api.dataset$fn__62550$fn__62553.invoke(dataset.clj:59)"
  "query_processor.streaming$streaming_response_STAR_$fn__37118$fn__37119.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__37118.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__24642.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error
 "Column \"source.CATEGORY\" not found; SQL statement:\n-- Metabase:: userID: 2 queryType: MBQL queryHash: 8ea2371b4dfbb51f69cf6f042debf36a013574b2a9dac257bc859fed22b1d03d\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\" FROM \"PUBLIC\".\"ORDERS\" WHERE \"PUBLIC\".\"ORDERS\".\"USER_ID\" = 1) \"source\" WHERE \"source\".\"CATEGORY\" = ? LIMIT 2000 [42122-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:filter [:= [:field-id 6] [:value "Gadget" {:base_type :type/Text, :special_type :type/Category, :database_type "VARCHAR", :name "CATEGORY"}]],
   :source-metadata
   [{:name "ID", :id 12, :table_id 2, :display_name "ID", :base_type :type/BigInteger, :special_type :type/PK, :fingerprint nil, :settings nil}
    {:name "USER_ID", :id 9, :table_id 2, :display_name "User ID", :base_type :type/Integer, :special_type :type/FK, :fingerprint {:global {:distinct-count 929, :nil% 0.0}}, :settings {}}
    {:name "PRODUCT_ID", :id 11, :table_id 2, :display_name "Product ID", :base_type :type/Integer, :special_type :type/FK, :fingerprint {:global {:distinct-count 200, :nil% 0.0}}, :settings {}}
    {:name "SUBTOTAL",
     :id 13,
     :table_id 2,
     :display_name "Subtotal",
     :base_type :type/Float,
     :special_type nil,
     :fingerprint
     {:global {:distinct-count 340, :nil% 0.0},
      :type {:type/Number {:min 15.691943673970439, :max 148.22900526552291, :avg 77.01295465356547, :sd 32.53705013056317, :q1 49.74894519060184, :q3 105.42965746993103}}},
     :settings nil}
    {:name "TAX",
     :id 16,
     :table_id 2,
     :display_name "Tax",
     :base_type :type/Float,
     :special_type nil,
     :fingerprint
     {:global {:distinct-count 797, :nil% 0.0}, :type {:type/Number {:min 0.0, :max 11.12, :avg 3.8722100000000004, :sd 2.3206651358900316, :q1 2.273340386603857, :q3 5.337275338216307}}},
     :settings nil}
    {:name "TOTAL",
     :id 17,
     :table_id 2,
     :display_name "Total",
     :base_type :type/Float,
     :special_type nil,
     :fingerprint
     {:global {:distinct-count 10000, :nil% 0.0},
      :type {:type/Number {:min 12.061602936923117, :max 238.32732001721533, :avg 82.96014815230805, :sd 38.35967664847571, :q1 52.006147617878135, :q3 109.55803018499738}}},
     :settings nil}
    {:name "DISCOUNT",
     :id 10,
     :table_id 2,
     :display_name "Discount",
     :base_type :type/Float,
     :special_type :type/Discount,
     :fingerprint
     {:global {:distinct-count 701, :nil% 0.898},
      :type {:type/Number {:min 0.17088996672584322, :max 61.69684269960571, :avg 5.161255547580326, :sd 3.053663125001991, :q1 2.9786226681458743, :q3 7.338187788658235}}},
     :settings nil}
    {:table_id 2,
     :special_type :type/CreationTimestamp,
     :unit :default,
     :name "CREATED_AT",
     :settings nil,
     :id 15,
     :display_name "Created At",
     :fingerprint {:global {:distinct-count 9998, :nil% 0.0}, :type {:type/DateTime {:earliest "2016-04-30T18:56:13.352", :latest "2020-04-19T14:07:15.657"}}},
     :base_type :type/DateTime}
    {:name "QUANTITY",
     :id 14,
     :table_id 2,
     :display_name "Quantity",
     :base_type :type/Integer,
     :special_type :type/Quantity,
     :fingerprint {:global {:distinct-count 62, :nil% 0.0}, :type {:type/Number {:min 0.0, :max 100.0, :avg 3.7015, :sd 4.214258386403798, :q1 1.755882607764982, :q3 4.882654507928044}}},
     :settings nil}],
   :fields
   [[:field-literal "ID" :type/BigInteger]
    [:field-literal "USER_ID" :type/Integer]
    [:field-literal "PRODUCT_ID" :type/Integer]
    [:field-literal "SUBTOTAL" :type/Float]
    [:field-literal "TAX" :type/Float]
    [:field-literal "TOTAL" :type/Float]
    [:field-literal "DISCOUNT" :type/Float]
    [:field-literal "CREATED_AT" :type/DateTime]
    [:field-literal "QUANTITY" :type/Integer]],
   :limit 2000,
   :source-query
   {:source-table 2,
    :filter [:= [:field-id 9] [:value 1 {:base_type :type/Integer, :special_type :type/FK, :database_type "INTEGER", :name "USER_ID"}]],
    :fields [[:field-id 12] [:field-id 9] [:field-id 11] [:field-id 13] [:field-id 16] [:field-id 17] [:field-id 10] [:datetime-field [:field-id 15] :default] [:field-id 14]],
    :gtap? true}},
  :database 1,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 2,
   :context :ad-hoc,
   :nested? false,
   :query-hash [-114, -94, 55, 27, 77, -5, -75, 31, 105, -49, 111, 4, 45, -21, -13, 106, 1, 53, 116, -78, -87, -38, -62, 87, -68, -123, -97, -19, 34, -79, -48, 61]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :gtap-perms #{"/db/1/schema/PUBLIC/table/2/query/"}},
 :data {:rows [], :cols []}}

2020-10-30 16:54:22,854 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 695.6 ms (22 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (1 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
```

</details>

**Information about your Metabase Installation:**
Metabase 1.37.0.2

**Additional context**
Related to https://github.com/metabase/metabase-enterprise/issues/535

### LINKED ISSUE #14724: Cannot use Saved Questions that contains joins as base in new questions
**Describe the bug**
Cannot use Saved Questions that contains joins as base in new questions.
Worked in 0.37.8 and 0.38.0-rc3, but not in 0.38.0-rc4 or latest 38 commit `25f6faa`

**To Reproduce**
1. Custom question > Sample Dataset > Orders and join Products, and save question as "Q1"
image
2. Simple question > Saved Questions > "Q1" fails with error: `Column "source.ID_2" not found;...`
If FK remapping is enabled, then the error is slightly different `Column "source.TITLE" not found;...`
image

<details><summary>Full stacktrace</summary>

```
2021-02-09 18:32:54,043 INFO middleware.fetch-source-query :: Fetched source query from Card 397: 
 {:source-table 11, :joins [{:fields :all, :source-table 10, :condition [:= [:field-id 82] [:joined-field "Products" [:field-id 105]]], :alias "Products"}]}

2021-02-09 18:32:54,054 INFO middleware.fetch-source-query :: Fetched source query from Card 397: 
 {:source-table 11, :joins [{:fields :all, :source-table 10, :condition [:= [:field-id 82] [:joined-field "Products" [:field-id 105]]], :alias "Products"}]}

2021-02-09 18:32:55,280 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2021-02-09T18:32:54.033920+01:00[Europe/Copenhagen]",
 :state "42S22",
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :database 4,
  :query {:source-table "card__397"},
  :parameters [],
  :async? true,
  :cache-ttl nil},
 :native
 {:query
  "SELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"ID_2\" AS \"ID_2\", \"source\".\"EAN\" AS \"EAN\", \"source\".\"TITLE\" AS \"TITLE\", \"source\".\"CATEGORY\" AS \"CATEGORY\", \"source\".\"VENDOR\" AS \"VENDOR\", \"source\".\"PRICE\" AS \"PRICE\", \"source\".\"RATING\" AS \"RATING\", \"source\".\"CREATED_AT_2\" AS \"CREATED_AT_2\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\", \"Products\".\"ID\" AS \"Products__ID\", \"Products\".\"EAN\" AS \"Products__EAN\", \"Products\".\"TITLE\" AS \"Products__TITLE\", \"Products\".\"CATEGORY\" AS \"Products__CATEGORY\", \"Products\".\"VENDOR\" AS \"Products__VENDOR\", \"Products\".\"PRICE\" AS \"Products__PRICE\", \"Products\".\"RATING\" AS \"Products__RATING\", \"Products\".\"CREATED_AT\" AS \"Products__CREATED_AT\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"Products\".\"ID\") \"source\" LIMIT 2000",
  :params nil},
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)"
  "org.h2.expression.Alias.optimize(Alias.java:51)"
  "org.h2.command.dml.Select.prepare(Select.java:858)"
  "org.h2.command.Parser.prepareCommand(Parser.java:283)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)"
  "org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1135)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:267)"
  "--> driver.sql_jdbc.execute$fn__77201.invokeStatic(execute.clj:236)"
  "driver.sql_jdbc.execute$fn__77201.invoke(execute.clj:234)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:254)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:251)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:387)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:374)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:383)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:374)"
  "driver.sql_jdbc$fn__78785.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__78785.invoke(sql_jdbc.clj:52)"
  "driver.h2$fn__77591.invokeStatic(h2.clj:81)"
  "driver.h2$fn__77591.invoke(h2.clj:78)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46299.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__45575.invoke(check_features.clj:41)"
  "query_processor.middleware.limit$limit$fn__46285.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__45226.invoke(cache.clj:211)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46464.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44373.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40732.invoke(wrap_value_literals.clj:147)"
  "query_processor.middleware.annotate$add_column_info$fn__40595.invoke(annotate.clj:578)"
  "query_processor.middleware.permissions$check_query_permissions$fn__45450.invoke(permissions.clj:69)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46983.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45648.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47224.invoke(resolve_joined_fields.clj:39)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__47543.invoke(resolve_joins.clj:184)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__43971.invoke(add_implicit_joins.clj:249)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__46260.invoke(large_int_id.clj:44)"
  "query_processor.middleware.format_rows$format_rows$fn__46240.invoke(format_rows.clj:74)"
  "query_processor.middleware.desugar$desugar$fn__45714.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__44732.invoke(binning.clj:225)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__45250.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__43519.invoke(add_dimension_projections.clj:315)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43722.invoke(add_implicit_clauses.clj:138)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44120.invoke(add_source_metadata.clj:103)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47180.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44320.invoke(auto_bucket_datetimes.clj:139)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45297.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__46965.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45349.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__45970.invoke(expand_macros.clj:155)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44129.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47905.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47191$fn__47195.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47191.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46188.invoke(fetch_source_query.clj:264)"
  "query_processor.middleware.store$initialize_store$fn__47914$fn__47915.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__47914.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__47923.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__46312.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__43989.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47890.invoke(results_metadata.clj:146)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__45591.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__47054.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45534.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___37374$thunk__37375.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___37374$fn__37377.invoke(reducible.clj:108)"],
 :context :question,
 :error
 "Column \"source.ID_2\" not found; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 5bf186963a0b195c2d4f741136072b4849ccd2fd0610418ff174180a7ee29b37\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"ID_2\" AS \"ID_2\", \"source\".\"EAN\" AS \"EAN\", \"source\".\"TITLE\" AS \"TITLE\", \"source\".\"CATEGORY\" AS \"CATEGORY\", \"source\".\"VENDOR\" AS \"VENDOR\", \"source\".\"PRICE\" AS \"PRICE\", \"source\".\"RATING\" AS \"RATING\", \"source\".\"CREATED_AT_2\" AS \"CREATED_AT_2\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\", \"Products\".\"ID\" AS \"Products__ID\", \"Products\".\"EAN\" AS \"Products__EAN\", \"Products\".\"TITLE\" AS \"Products__TITLE\", \"Products\".\"CATEGORY\" AS \"Products__CATEGORY\", \"Products\".\"VENDOR\" AS \"Products__VENDOR\", \"Products\".\"PRICE\" AS \"Products__PRICE\", \"Products\".\"RATING\" AS \"Products__RATING\", \"Products\".\"CREATED_AT\" AS \"Products__CREATED_AT\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"Products\".\"ID\") \"source\" LIMIT 2000 [42122-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :info
  {:executed-by 1,
   :context :question,
   :card-id 398,
   :query-hash [91, -15, -122, -106, 58, 11, 25, 92, 45, 79, 116, 17, 54, 7, 43, 72, 73, -52, -46, -3, 6, 16, 65, -113, -15, 116, 24, 10, 126, -30, -101, 55]},
  :database 4,
  :query
  {:source-metadata
   [{:base_type :type/BigInteger,
     :display_name "ID",
     :name "ID",
     :description "This is a unique ID for the product. It is also called the “Invoice number” or “Confirmation number” in customer facing emails and screens.",
     :special_type :type/PK,
     :fingerprint nil}
    {:base_type :type/Integer,
     :display_name "User ID",
     :name "USER_ID",
     :description
     "The id of the user who made this order. Note that in some cases where an order was created on behalf of a customer who phoned the order in, this might be the employee who handled the request.",
     :special_type :type/FK,
     :fingerprint {:global {:distinct-count 929, :nil% 0.0}}}
    {:base_type :type/Integer,
     :display_name "Product ID",
     :name "PRODUCT_ID",
     :description "The product ID. This is an internal identifier for the product, NOT the SKU.",
     :special_type :type/FK,
     :fingerprint {:global {:distinct-count 200, :nil% 0.0}}}
    {:base_type :type/Float,
     :display_name "Subtotal",
     :name "SUBTOTAL",
     :description "The raw, pre-tax cost of the order. Note that this might be different in the future from the product price due to promotions, credits, etc.",
     :special_type :type/Currency,
     :fingerprint
     {:global {:distinct-count 340, :nil% 0.0},
      :type {:type/Number {:min 15.691943673970439, :max 148.22900526552291, :avg 77.01295465356547, :sd 32.53705013056317, :q1 49.74894519060184, :q3 105.42965746993103}}}}
    {:base_type :type/Float,
     :display_name "Tax",
     :name "TAX",
     :description
     "This is the amount of local and federal taxes that are collected on the purchase. Note that other governmental fees on some products are not included here, but instead are accounted for in the subtotal.",
     :special_type :type/Currency,
     :fingerprint
     {:global {:distinct-count 797, :nil% 0.0}, :type {:type/Number {:min 0.0, :max 11.12, :avg 3.8722100000000004, :sd 2.3206651358900316, :q1 2.273340386603857, :q3 5.337275338216307}}}}
    {:base_type :type/Float,
     :display_name "Total",
     :name "TOTAL",
     :description "The total billed amount.",
     :special_type :type/Income,
     :fingerprint
     {:global {:distinct-count 10000, :nil% 0.0},
      :type {:type/Number {:min 12.061602936923117, :max 238.32732001721533, :avg 82.96014815230805, :sd 38.35967664847571, :q1 52.006147617878135, :q3 109.55803018499738}}}}
    {:base_type :type/Float,
     :display_name "Discount",
     :name "DISCOUNT",
     :description "Discount amount.",
     :special_type :type/Discount,
     :fingerprint
     {:global {:distinct-count 701, :nil% 0.898},
      :type {:type/Number {:min 0.17088996672584322, :max 61.69684269960571, :avg 5.161255547580326, :sd 3.053663125001991, :q1 2.9786226681458743, :q3 7.338187788658235}}}}
    {:base_type :type/DateTime,
     :display_name "Created At",
     :name "CREATED_AT",
     :description "The date and time an order was submitted.",
     :special_type :type/CreationTimestamp,
     :unit :default,
     :fingerprint {:global {:distinct-count 10001, :nil% 0.0}, :type {:type/DateTime {:earliest "2016-05-01T00:56:13.352Z", :latest "2020-04-19T20:07:15.657Z"}}}}
    {:base_type :type/Integer,
     :display_name "Quantity",
     :name "QUANTITY",
     :description "Number of products bought.",
     :special_type :type/Quantity,
     :fingerprint {:global {:distinct-count 62, :nil% 0.0}, :type {:type/Number {:min 0.0, :max 100.0, :avg 3.7015, :sd 4.214258386403798, :q1 1.755882607764982, :q3 4.882654507928044}}}}
    {:base_type :type/BigInteger,
     :display_name "Products → ID",
     :name "ID_2",
     :description "The numerical product number. Only used internally. All external communication should use the title or EAN.",
     :special_type :type/PK,
     :fingerprint nil}
    {:base_type :type/Text,
     :display_name "Products → Ean",
     :name "EAN",
     :description "The international article number. A 13 digit number uniquely identifying the product.",
     :special_type :type/Title,
     :fingerprint {:global {:distinct-count 200, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 13.0}}}}
    {:base_type :type/Text,
     :display_name "Products → Title",
     :name "TITLE",
     :description "The name of the product as it should be displayed to customers.",
     :special_type :type/Name,
     :fingerprint {:global {:distinct-count 199, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.495}}}}
    {:base_type :type/Text,
     :display_name "Products → Category",
     :name "CATEGORY",
     :description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
     :special_type :type/Category,
     :fingerprint {:global {:distinct-count 4, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}}}
    {:base_type :type/Text,
     :display_name "Products → Vendor",
     :name "VENDOR",
     :description "The source of the product.",
     :special_type :type/Company,
     :fingerprint {:global {:distinct-count 200, :nil% 0.0}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}}}
    {:base_type :type/Float,
     :display_name "Products → Price",
     :name "PRICE",
     :description "The list price of the product. Note that this is not always the price the product sold for due to discounts, promotions, etc.",
     :fingerprint
     {:global {:distinct-count 170, :nil% 0.0},
      :type {:type/Number {:min 15.691943673970439, :max 98.81933684368194, :avg 55.74639966792074, :sd 21.711481557852057, :q1 37.25154462926434, :q3 75.45898071609447}}},
     :special_type nil}
    {:base_type :type/Float,
     :display_name "Products → Rating",
     :name "RATING",
     :description "The average rating users have given the product. This ranges from 1 - 5",
     :special_type :type/Score,
     :fingerprint {:global {:distinct-count 23, :nil% 0.0}, :type {:type/Number {:min 0.0, :max 5.0, :avg 3.4715, :sd 1.3605488657451452, :q1 3.5120465053408525, :q3 4.216124969497314}}}}
    {:base_type :type/DateTime,
     :display_name "Products → Created At",
     :name "CREATED_AT_2",
     :description "The date the product was added to our catalog.",
     :special_type :type/CreationTimestamp,
     :unit :default,
     :fingerprint {:global {:distinct-count 200, :nil% 0.0}, :type {:type/DateTime {:earliest "2016-04-27T01:29:55.147Z", :latest "2019-04-15T19:34:19.931Z"}}}}],
   :fields
   [[:field-literal "ID" :type/BigInteger]
    [:field-literal "USER_ID" :type/Integer]
    [:field-literal "PRODUCT_ID" :type/Integer]
    [:field-literal "SUBTOTAL" :type/Float]
    [:field-literal "TAX" :type/Float]
    [:field-literal "TOTAL" :type/Float]
    [:field-literal "DISCOUNT" :type/Float]
    [:field-literal "CREATED_AT" :type/DateTime]
    [:field-literal "QUANTITY" :type/Integer]
    [:field-literal "ID_2" :type/BigInteger]
    [:field-literal "EAN" :type/Text]
    [:field-literal "TITLE" :type/Text]
    [:field-literal "CATEGORY" :type/Text]
    [:field-literal "VENDOR" :type/Text]
    [:field-literal "PRICE" :type/Float]
    [:field-literal "RATING" :type/Float]
    [:field-literal "CREATED_AT_2" :type/DateTime]],
   :source-query
   {:source-table 11,
    :joins [{:strategy :left-join, :source-table 10, :condition [:= [:field-id 82] [:joined-field "Products" [:field-id 105]]], :alias "Products"}],
    :fields
    [[:field-id 83]
     [:field-id 80]
     [:field-id 82]
     [:field-id 84]
     [:field-id 87]
     [:field-id 88]
     [:field-id 81]
     [:datetime-field [:field-id 86] :default]
     [:field-id 85]
     [:joined-field "Products" [:field-id 105]]
     [:joined-field "Products" [:field-id 102]]
     [:joined-field "Products" [:field-id 106]]
     [:joined-field "Products" [:field-id 107]]
     [:joined-field "Products" [:field-id 109]]
     [:joined-field "Products" [:field-id 104]]
     [:joined-field "Products" [:field-id 103]]
     [:datetime-field [:joined-field "Products" [:field-id 108]] :default]]},
   :limit 2000},
  :async? true},
 :data {:rows [], :cols []}}
```

</details>

**Information about your Metabase Installation:**
Worked in 0.37.8 and 0.38.0-rc3, but not in 0.38.0-rc4 or latest release-x.38.x commit `25f6faa`

**Additional context**
Related to #12928

### PR DESCRIPTION
**Pull request by camsaul**
Fixes some bugs using sandboxed queries for drill thru. Fixes #13641. Fixes #14724 (this might already be fixed somewhere else, but I've manually verified that it is working here)

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
Tested `1f21ed3`

I'm now not even able to view the question (step 4) before doing drill-through - no matter if FK remapping is enabled or not:
`Value does not match schema: {:query {:source-query {:filter (named [nil nil (named [nil nil (named {:base-type disallowed-key, :special-type disallowed-key, :database-type disallowed-key} "type-info")] "value-or-field")] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment")}}}`

**Comment by nemanjaglumac** [comment]
> I'm now not even able to view the question (step 4) before doing drill-through - no matter if FK remapping is enabled or not:
> `Value does not match schema: {:query {:source-query {:filter (named [nil nil (named [nil nil (named {:base-type disallowed-key, :special-type disallowed-key, :database-type disallowed-key} "type-info")] "value-or-field")] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment")}}}`

Basically, this:
https://app.circleci.com/pipelines/github/metabase/metabase/12802/workflows/6b4993b6-80b2-47ed-8156-4e6dcce98de8/jobs/482659

File: enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj [hunk 1]
```diff
@@ -264,45 +263,33 @@
   "Replace `:source-table` entries that refer to Tables for which we have applicable GTAPs with `:source-query` entries
   from their GTAPs."
   [m table-id->gtap]
-  ;; replace maps that have `:source-table` key and a matching entry in `table-id->gtap`, but do not have `:gtap?` key
+  ;; replace maps that have `:source-table` key and a matching entry in `table-id->gtap`, but do not have `::gtap?` key
   (mbql.u/replace m
-    (_ :guard (every-pred map? (complement :gtap?) :source-table #(get table-id->gtap (:source-table %))))
+    (_ :guard (every-pred map? (complement ::gtap?) :source-table #(get table-id->gtap (:source-table %))))
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj:268]: does the auto resolved keyword `::gtap?` vs `:gtap?` fix anything or just a bit more descriptive in tests?

File: enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj [hunk 2]
```diff
@@ -264,45 +263,33 @@
...
-                                          (db/select-field->id :name Field :table_id source-table-id))
-                                 (qp.store/fetch-and-store-fields! (vals <>))))]
-    (update metadata :cols (fn [cols]
-                             (mapv (partial update-col-metadata query field-name->id-delay) cols)))))
+  "Merge column metadata from the non-GTAPped version of the query into the GTAPped results `metadata`. This way the
+  final results metadata coming back matches what we'd get if the query was not running with a GTAP."
+  [original-query metadata]
+  (letfn [(merge-cols [cols]
+            (let [expected-cols          (binding [*current-user-permissions-set* (atom #{"/"})]
+                                           ((requiring-resolve 'metabase.query-processor/query->expected-cols) original-query))
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj:286]: `query->expected-cols` throws if the query-type is not `:query`. Is that constraint satisfied by all pathways here?

File: enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj (hunk 1 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj:268]: it's just more descriptive. Doesn't change anything

**Comment by camsaul** [comment]
@flamber @nemanjaglumac I think I broke something with my most recent test fix, let me fix it

File: enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj (hunk 2 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj:286]: original query is always going to be MBQL, we can't apply a GTAP (sandbox) to a native query

**Comment by camsaul** [comment]
@flamber @nemanjaglumac please give this another try when you get a chance, it should be fixed now

**Comment by nemanjaglumac** [comment]
My first few Cypress runs locally show that #13641 is passing both _with_ and _without_ remapping.

**Review by flamber — APPROVED** [review]
Tested `663edd2` - it works! :+1:

**Review by nemanjaglumac — APPROVED** [review]
Basing my review only on FE / Cypress tests:

Tested d2be1f5170240612ecceb3b766250b489210eaa1

- Local Cypress tests are passing
- CircleCI [passed](https://app.circleci.com/pipelines/github/metabase/metabase/12858/workflows/71cf864a-fac0-42e8-a8c7-dd98f0e76405) ✅
- GitHub CI (stress-testing)
    - `sandboxes` (including both versions of #13641 ) [19/20 passed*](https://github.com/nemanjaglumac/metabase-tests/actions/runs/553059802)
    - `nested` (including repro for #14724 ) [20/20 passed](https://github.com/nemanjaglumac/metabase-tests/actions/runs/553070013)
    
    
*_One process failed during build phase, before Cypress even ran._
