### PR TITLE
Fix order by custom expression aggregations

### LINKED ISSUE #65893: BigQuery - Custom Expressions with space break when sorted
### Describe the bug

Custom Expressions with space break when sorted, seems to only happen to Bigquery but there could be other DBs (tested on Postgres and Mysql both work)

Doesn't happen on 56

### To Reproduce

Use Bigquery
 
1. Go to New -> Orders -> Custom Expression named space space `Distinct([ID])` group by month -> Sort

Image

This question on [stats already has the issue](https://stats.metabase.com/question/31290-orders-space-space-grouped-by-created-at-month-sorted-by-space-space-ascending/notebook)

### Expected behavior

The sorting works

### Logs

400 Bad Request POST https://bigquery.googleapis.com/bigquery/v2/projects/metabase-bigquery-driver/queries { "code": 400, "errors": [ { "domain": "global", "location": "q", "locationType": "parameter", "message": "Unrecognized name: `space space`; Did you mean space_space? at [2:231]", "reason": "invalidQuery" } ], "message": "Unrecognized name: `space space`; Did you mean space_space? at [2:231]", "status": "INVALID_ARGUMENT" }

### Information about your Metabase installation

```JSON
1.57.2.4 and master
```

### Severity

This can break questions if people upgrade and already have sorting applied to custom expressions

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/65893

### Description

Use the desired column alias instead of the source column alias when generating the sql for a non-top level aggregation field. 

### How to verify

1. See steps in original issue
2. It should work now

### Demo

https://github.com/user-attachments/assets/dfa3f6bc-3167-43e4-880a-04bcaca33b41

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/driver/sql/query_processor.clj [hunk 1]
```diff
@@ -1290,6 +1290,9 @@
 (defmethod ->honeysql [:sql :aggregation]
   [driver [_ index]]
   (driver-api/match-one (nth (:aggregation *inner-query*) index)
+    [:aggregation-options ag (options :guard driver-api/qp.add.desired-alias)]
+    (->honeysql driver (h2x/identifier :field-alias (driver-api/qp.add.desired-alias options)))
```
Comment (metamben) [inline src/metabase/driver/sql/query_processor.clj:1294]: I can see this fixes the issue and all tests pass, but I'm not 100% sure this is the right logic. At any given stage, we use  the source alias to refer to columns. The desired alias is the name the given column will be known at the next stage or in the result. My understanding is that many (most?) SQL servers support order by on the alias, but are we sure we can ignore those that don't? If we can't or don't want to ignore them, we could introduce a new feature with default true, so that individual drivers can opt out of this.

**Review by metamben — APPROVED** [review]

File: src/metabase/driver/sql/query_processor.clj (hunk 1 above)
Comment (rileythomp) [reply src/metabase/driver/sql/query_processor.clj:1294]: Good point. I'm not 100% sure either. In cases where order by on the alias isn't supported, does this issue not exist with the current logic of using the source alias? And instead of a new feature could drivers not just implement their own `sql.qp/->honeysql` to get different behaviour?

Comment (metamben) [reply src/metabase/driver/sql/query_processor.clj:1294]: Sure they can override the whole thing, so if not supporting this is exceedingly rare, then we can ignore it.
