### PR TITLE
Fix showing saved value in language picker

### LINKED ISSUE #15657: Selecting languages with dialects doesn't show them as selected
**Describe the bug**
Selecting languages with dialects doesn't show them as selected. The language is correctly set.

**To Reproduce**
1. Admin > Settings > Localization > Instant Language: change to any language with dialect (eg Portuguese `pt-BR`)
It will correctly set the language, but the Select and dropdown does not have the selected language set, because the returned selected value is `pt_BR` (with underscore).
image

**Information about your Metabase Installation:**
Tested 0.38.4 and release-x.39.x commit `fe9903b`

**Additional context**
Historically related #12560

### LINKED ISSUE #16654: Language picker in user config hides chosen language on page load if language includes substring between parentheses
## To reproduce

1. http://localhost:3000/user/edit_current
2. Choose any language that has any text between parentheses, such as `Portuguese (Brazil)`
3. Click button to update
4. Wait for page reload

Dropdown will render empty.
For other languages with nothing between parentheses, the language shows.

### PR DESCRIPTION
**Pull request by pawit-metabase**
The locale list sent to the UI is formatted "pt-BR" but when it is saved to the database, we re-format the locale to "pt_BR", thus on next load, the UI cannot match the saved locale with the locale list.

Fix the issue by using normalized value (e.g. "pt_BR") in the available locale list.

Fixes #15657, fixes #16654

### CODE REVIEW

**Comment by pawit-metabase** [comment]
Admin
image


User
image

**Review by flamber — APPROVED** [review]
Works great and does not seem to cause problems elsewhere (though, we've had several problems with dash vs underscore, when it was changed around 34/35 and 37).

File: test/metabase/util/i18n_test.clj [hunk 1]
```diff
@@ -4,6 +4,11 @@
             [metabase.test :as mt]
             [metabase.util.i18n :as i18n]))
 
+(deftest available-locales-test
+  (testing "Should return locale in normalized format"
+    (is (contains? (set (i18n/available-locales-with-names))
+                   ["pt_BR", "Portuguese (Brazil)"]))))
```
Comment (camsaul) [inline test/metabase/util/i18n_test.clj:10]:
```suggestion
                   ["pt_BR" "Portuguese (Brazil)"]))))
```

https://guide.clojure.style/#no-commas-for-seq-literals

**Review by camsaul — APPROVED** [review]
