### PR TITLE
Do not Move and Archive personal collections

### LINKED ISSUE #28127: Do not offer Move or Archive for personal collections
**Describe the bug**
As of https://github.com/metabase/metabase/pull/28023, we display subcollections in a parent collection view. For root collection ("Our analytics"), those are admin's own and everyone else's personal collections. That alone can be problematic for instances with large number of users, but that's a separate problem. (Related #24330)

If we already display personal collections, we shouldn't offer neither "Move", nor "Archive" actions for them.
This goes both for the `...` menu next to the item, and for when we select the item and then have the bulk edit collection actions at the bottom of the screen.

**To Reproduce**
_Log in as an admin_
1. Go to `/collections/root`
2. See your own personal collection in the list of collection items
(nit: Why is it called "Your personal collection" in the sidebar but not here?)
3. Click on the ellipsis menu `...` and notice "Move" and "Archive", which will not have any effect and are just confusing
image
4. The same thing happens if you click on the icon to select this collection (see the bottom bulk action toolbar)
image

```js
`PUT /api/collection/:id`

// responds with
`500 Server Error`
```

**Expected behavior**
Do not offer Move or Archive for personal collections

**Information about your Metabase Installation:**
local dev, `master`, ffa0362, H2, Sample Database

**Severity**
P3, only because it's not possible to execute the action.

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/28127

How to verify:
- Open the root collection. You should be able to see a personal collection of another user
- Open the menu for it. It should not be possible to Move or Archive it. 

Screenshot 2023-02-14 at 14 27 24
Screenshot 2023-02-14 at 14 27 31

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28229)

### CODE REVIEW

**Comment by WiNloSt** [comment]
@ranquild it's still possible to do step 4 from https://github.com/metabase/metabase/issues/28127
> 4. The same thing happens if you click on the icon to select this collection (see the bottom bulk action toolbar)

image

Probably the personal collection shouldn't be selectable at all.

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.tsx [hunk 1]
```diff
@@ -88,12 +98,12 @@ function ActionMenu({
         isBookmarked={isBookmarked}
         isPreviewShown={isPreviewShown(item)}
         isPreviewAvailable={isFullyParametrized(item)}
-        onPin={collection.can_write && item.setPinned ? handlePin : null}
-        onMove={collection.can_write && item.setCollection ? handleMove : null}
+        onPin={canPin && item.setPinned ? handlePin : null}
```
Comment (WiNloSt) [inline frontend/src/metabase/collections/components/ActionMenu/ActionMenu.tsx:101]: since `canPin` already tests that`item.setPinned != null`, it should be fine to remove `item.setPinned` from this condition what do you think?

```suggestion
        onPin={canPin ? handlePin : null}
```

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.tsx [hunk 2]
```diff
@@ -50,8 +52,16 @@ function ActionMenu({
...
 }: ActionMenuProps) {
   const isBookmarked = bookmarks && getIsBookmarked(item, bookmarks);
-  const isPreviewOptionShown =
+  const canPin = collection.can_write && item.setPinned != null;
+  const canPreview =
     isItemPinned(item) && isItemQuestion(item) && collection.can_write;
+  const canMove =
+    collection.can_write &&
+    item.setCollection != null &&
+    (!isItemCollection(item) || !isPersonalCollection(item));
```
Comment (WiNloSt) [inline frontend/src/metabase/collections/components/ActionMenu/ActionMenu.tsx:61]: I find this line `(!isItemCollection(item) || !isPersonalCollection(item))` a bit hard to understand at first. Then I realized this is essentially
`!(isItemCollection(item) && isPersonalCollection(item))` or `!canNotMove`.

Maybe there's a way to juggle these flags that make them easier to understand. What do you think?

File: frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js [hunk 3]
```diff
@@ -73,6 +74,18 @@ describe("personal collections", () => {
...
+
+      openEllipsisMenuFor(`${getFullName(USERS.admin)}'s Personal Collection`);
+
+      popover().within(() => {
+        cy.findByText("Bookmark").should("be.visible");
+        cy.findByText("Move").should("not.exist");
+        cy.findByText("Archive").should("not.exist");
+      });
+    });
+
```
Comment (WiNloSt) [inline frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js:88]: Adding a step to test that we can't use select these personal collections for bulk actions could be necessary https://github.com/metabase/metabase/pull/28229#issuecomment-1429704024

File: frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js [hunk 4]
```diff
@@ -179,3 +192,9 @@ function addNewCollection(name) {
   cy.findByLabelText("Name").type(name, { delay: 0 });
   cy.button("Create").click();
 }
+
+function openEllipsisMenuFor(item) {
```
Comment (WiNloSt) [inline frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js:196]: @nemanjaglumac since we're improving accessibility in our app, I'm not sure what's the best way to navigate table cells. I get the impression that how we write Cypress also determines how accessible our app is.

Am I overthinking this, or what we're doing here works just fine.

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx [hunk 5]
```diff
@@ -1,78 +1,98 @@
...
+import { renderWithProviders } from "__support__/ui";
+import { Collection, CollectionItem } from "metabase-types/api";
 import {
   createMockCollection,
   createMockCollectionItem,
 } from "metabase-types/api/mocks";
-import ActionMenu, { ActionMenuProps } from "./ActionMenu";
+import ActionMenu from "./ActionMenu";
+
+interface SetupOpts {
```
Comment (WiNloSt) [inline frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx:12]: Should we be using `opts` for options? I'm fine either way, but just want to know what I should be using next time.

However, I'm inclined to use full names almost all of the time. I think `opts` is one of the very few places that use abbreviations.

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx [hunk 6]
```diff
@@ -1,78 +1,98 @@
...
+  renderWithProviders(
+    <ActionMenu
+      item={item}
+      collection={collection}
+      onCopy={onCopy}
+      onMove={onMove}
+    />,
+  );
+
+  return { onCopy, onMove };
```
Comment (WiNloSt) [inline frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx:33]: We've never seem to use these return values, should we still return them? This gives me the impression that they'll be asserted somewhere else.

**Review by WiNloSt — COMMENTED** [review]
Overall code looks good. If I'm not mistaken, we should prevent users to select collections that will lead to showing archive and move actions in the bulk edit context.

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx (hunk 6 above)
Comment (ranquild) [reply frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx:33]: We use them in one of the tests

Comment (WiNloSt) [reply frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx:33]: I couldn't find we use the return value anywhere in this file https://github.com/metabase/metabase/blob/f9f71d85a4e9aa249da33cc8fb8c095265c39fb3/frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx. What test were you mentioning?

File: frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js (hunk 4 above)
Comment (ranquild) [reply frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js:196]: Used the same thing we do in `collections.cy.spec.js`

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx (hunk 5 above)
Comment (ranquild) [reply frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx:12]: I think we explicitly added `SetupOpts` to frontend docs

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx (hunk 6 above)
Comment (ranquild) [reply frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx:33]: Forgot to push the test, fixed

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.tsx (hunk 2 above)
Comment (ranquild) [reply frontend/src/metabase/collections/components/ActionMenu/ActionMenu.tsx]: Fixed

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.tsx (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/collections/components/ActionMenu/ActionMenu.tsx]: Fixed

**Comment by ranquild** [comment]
@WiNloSt I believe I've addressed all the comments, please take a look

File: frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx (hunk 6 above)
Comment (WiNloSt) [reply frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx:33]: That's good, but only the `onMove` is used actually. Should we not return `onCopy` then? Or at least test `onCopy` which is actually a duplicate button (I was thinking when copying you'll need to paste it yourself, that's another story, I wish it's called `onDuplicate` instead)

**Review by WiNloSt — APPROVED** [review]
Apart from a small comment this looks good 👍
