### PR TITLE
Fix iframe resizer not working

### LINKED ISSUE #47061: iFrameResizer doesn't work on master (v51)
### Describe the bug

iFrameResizer doesn't work anymore on master

#### master (1b9a267551a1f192436935f3de31c706cbc7f316)
Screenshot 2024-08-21 at 5 30 25 PM

#### release-x.50.x (5ac95a7e4a07f156a54f1b36b2b0c982a0bcee19)
Screenshot 2024-08-21 at 5 28 27 PM

### To Reproduce

1. Embed a dashboard.
2. Follow [this step](https://www.metabase.com/docs/latest/embedding/static-embedding#resizing-dashboards-to-fit-their-content) to trigger `iFrameResizer`

### Expected behavior

The dashboard content is resized correctly.

### Logs

_No response_

### Information about your Metabase installation

```JSON
master @ 1b9a267551a1f192436935f3de31c706cbc7f316
```

### Severity

P1 this blocks customers that are using iframe resizer from using our embeds

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/47061

### Description

This fixes the issue where iframe-resizer not working on static embedded dashboards

### How to verify

Run the Cypress test `e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js`'s "should resize iframe to dashboard content size (metabase#47061)"

#### After
image

#### Before
Screenshot 2024-08-21 at 5 30 25 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by WiNloSt** [comment]
not backport because this doesn't happen in v50

File: frontend/src/metabase/lib/dom.js [hunk 1]
```diff
@@ -495,23 +495,10 @@ export function initializeIframeResizer(onReady = () => {}) {
...
-      return false;
-    }
-
     // Make iframe-resizer avaliable to the embed
     // We only care about contentWindow so require that minified file
 
-    require.ensure([], require => {
-      require("iframe-resizer/js/iframeResizer.contentWindow.js");
-    });
+    import("iframe-resizer/js/iframeResizer.contentWindow.js");
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/dom.js:501]: This has been broken since the SWC change https://github.com/metabase/metabase/commit/e02589a386814a83aaf330db61d4377e129eeb95

File: e2e/support/helpers/e2e-embedding-helpers.js [hunk 2]
```diff
@@ -107,18 +107,24 @@ export function visitEmbeddedPage(
...
  * Grab an iframe `src` via UI and open it,
  * but make sure user is signed out.
  */
 export function visitIframe() {
-  modal().findByText("Preview").click();
-
-  cy.document().then(doc => {
-    const iframe = doc.querySelector("iframe");
-
+  getIframeUrl().then(iframeUrl => {
```
Comment (WiNloSt) [inline e2e/support/helpers/e2e-embedding-helpers.js:125]: This function works the same, but I extract part of it as a `getIframeUrl` so I could get only the URL without navigating to it.

File: e2e/test/scenarios/embedding/embedding-dashboard.html [hunk 3]
```diff
@@ -0,0 +1,11 @@
+<script src="http://localhost:4000/app/iframeResizer.js"></script>
```
Comment (WiNloSt) [inline e2e/test/scenarios/embedding/embedding-dashboard.html:1]: Add a new HTML file for testing embedding because I need to import `http://localhost:4000/app/iframeResizer.js`.

Thess scripts follow our [doc for static embedding.](https://www.metabase.com/docs/latest/embedding/static-embedding#resizing-dashboards-to-fit-their-content)

File: frontend/src/metabase/lib/dom.js (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/lib/dom.js:501]: wow, why?

Comment (WiNloSt) [reply frontend/src/metabase/lib/dom.js:501]: IDK, but it just didn't import `iframe-resizer/js/iframeResizer.contentWindow.js` with `require.ensure`. I'd been troubleshooting this for so long until I tried using your code `import()` and it imported this module correctly 🤷. From the behavior, it seems this syntax doesn't work with SWC.

Comment (uladzimirdev) [reply frontend/src/metabase/lib/dom.js:501]: oh, you're right, swc is the reason

https://github.com/swc-project/swc/issues/7505
https://github.com/webpack/webpack/discussions/17849

that's great we didn't backport this change and you noticed it 😄

**Review by heypoom — APPROVED** [review]
Both code and test results looks good to me. To confirm my understanding, the root cause is the use of `require.ensure` being incompatible with SWC?

**Comment by WiNloSt** [comment]
> Both code and test results looks good to me. To confirm my understanding, the root cause is the use of `require.ensure` being incompatible with SWC?

Yes, that is correct.
