### PR TITLE
Fixing strings for relative date params in subscriptions

### LINKED ISSUE #24651: Subscription filter values displays technical values for date, which can be difficult to read for humans
**Describe the bug**
Subscription filter values displays technical values for date, which can be difficult to read for humans

**To Reproduce**
1. Dashboard > add a question and connect a couple of date filters with default values
image
2. Send subscription - the email received will look like this
image

**Expected behavior**
Since emails are static by nature, it would be great if we showed the static period (just like the relative filter preview does), but any less technical way of showing dates would be helpful. It should fall-back to the technical value if it cannot translate instead of displaying nothing/null/error.

**Information about your Metabase Installation:**
Tested 0.44.0

### PR DESCRIPTION
**Pull request by tsplude**
closes #24651
Closes VIZ-54

Changes include:
  - Support for relative date params that include an offset e.g. `past30days-from-7days`
  - Fixes OSS subscription sidebar to also show translated relative dates

<details>
<summary>Screenshots</summary>

Subscription email
image

Subscription sidebar
image

Pulse card
image

</details>

### CODE REVIEW

**Review by noahmoss — APPROVED** [review]
BE looks fine, didn't look at FE

File: frontend/src/metabase/notifications/AddEditSidebar/DefaultParametersSection.jsx [hunk 1]
```diff
@@ -12,8 +13,27 @@ import Heading from "./Heading";
...
+          .filter(Boolean);
+
+        if (formattedValues.length > 0) {
+          formattedValue = conjunct(formattedValues, t`and`);
+        }
+      } else {
+        formattedValue = conjunct([].concat(defaultValue), t`and`);
+      }
+
+      return formattedValue && `${name} -> ${formattedValue}`;
```
Comment (lorem--ipsum) [inline frontend/src/metabase/notifications/AddEditSidebar/DefaultParametersSection.jsx:36]: Nitpick but I'd use a good old if statement here, especially since this is JS and not TS, in order to avoid unexpected returned values in case formattedValue isn't a string or whatever.

**Review by lorem--ipsum — APPROVED** [review]

File: frontend/src/metabase/notifications/PulsesListSidebar.jsx [hunk 2]
```diff
@@ -170,10 +172,29 @@ function buildFilterText(pulse, parameters) {
...
-    numValues > 1 ? t`${numValues} selections` : firstParameter.value
-  }`;
+
+  // Format the first parameter value using the same logic as DefaultParametersSection
+  let formattedValue;
+  if (firstParameter.type && firstParameter.type.startsWith("date/")) {
+    const values = [].concat(firstParameter.value);
+    const formattedValues = values
+      .map((val) => formatDateValue(firstParameter, val))
+      .filter(Boolean);
```
Comment (kulyk) [inline frontend/src/metabase/notifications/PulsesListSidebar.jsx:182]: nit: it'd be more idiomatic to do `values = [...firstParameter.value]` to copy an array. But it this case, we could also just do the following since `map` and `filter` will give us a copy of the list:

```ts
const formatedValues = firstParameter.value
  .map((val) => formatDateValue(firstParameter, val))
  .filter(Boolean); 
```

File: frontend/src/metabase/notifications/PulsesListSidebar.jsx [hunk 3]
```diff
@@ -170,10 +172,29 @@ function buildFilterText(pulse, parameters) {
...
+
+    if (formattedValues.length > 0) {
+      formattedValue = conjunct(formattedValues, t`and`);
+    } else {
+      formattedValue = firstParameter.value;
+    }
+  } else {
+    const numValues = [].concat(firstParameter.value).length;
+    formattedValue =
+      numValues > 1
```
Comment (kulyk) [inline frontend/src/metabase/notifications/PulsesListSidebar.jsx:192]: nit: we could skip copying an array here and get the `length` directly:
```ts
formattedValue = firstParameter.value.length ? ... : ...
```

File: frontend/src/metabase/notifications/AddEditSidebar/DefaultParametersSection.unit.spec.jsx [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+  it("should render the heading and info text", () => {
+    setup([]);
+    expect(screen.getByText("Filter values")).toBeInTheDocument();
+    expect(
+      screen.getByText(
+        "If a dashboard filter has a default value, it'll be applied when your subscription is sent.",
+      ),
+    ).toBeInTheDocument();
+    // Check for info icon tooltip text
+    expect(screen.getByRole("img", { name: /info icon/i })).toBeInTheDocument();
```
Comment (kulyk) [inline frontend/src/metabase/notifications/AddEditSidebar/DefaultParametersSection.unit.spec.jsx:37]: nit: there's a `getIcon` utility in `"__support__/ui"` that we can use here:
```ts
expect(getIcon("info")).toBeInTheDocument();
```

**Review by kulyk — APPROVED** [review]
Looks great! Left a couple of nitpicks
