### PR TITLE
Exclude snippet and card template tags from parameters returned from BE endpoints

### LINKED ISSUE #37270: Public native questions with snippets don't work
### Describe the bug

A native question that contains a snippet always returns errors when made public.

### To Reproduce

1. Enable public sharing in Admin settings
2. New -> SQL query
3. Create a native query snippet `CATEGORY = 'Gadget'` with name `IsGadget`
4. Set query to `SELECT * FROM ORDERS WHERE {{snippet:IsGadget}}`
5. Save the question
6. Share -> public question -> open the link
7. See the error

Screenshot 2024-01-04 at 15 53 17
Screenshot 2024-01-04 at 15 53 25

### Expected behavior

I should see question results

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-LTS",
    "os.name": "Mac OS X",
    "os.version": "12.1",
    "user.language": "en",
    "user.timezone": "Asia/Jerusalem"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2024-01-04",
      "src_hash": "f566ffd0966ca096ad05e3d0a080a917e9932288",
      "tag": "v0.48.1-SNAPSHOT",
      "hash": "3d45805"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calherries**
Fixes #37270

### Explanation of the bug

When snippet or card template tags are used in a native SQL question, the incorrect list of parameters is returned by the endpoint GET `/api/public/card`. There should be no parameters for snippet or card template tags.

example screenshot:
Screenshot 2024-01-05 at 15 46 57

The problem is related to the use of `metabase.models.card/template-tag-parameters`. It was introduced in this PR: [Properly return parameters for card in public and embedding endpoints](https://github.com/metabase/metabase/pull/29233#top).

The BE should mirror the FE and use the logic in `getTemplateTagsForParameters` [here](https://github.com/metabase/metabase/blob/67b3b1454eb85ec33e834c99a9107308307c78e4/frontend/src/metabase-lib/parameters/utils/template-tags.ts#L69) which excludes snippets from the result of `getTemplateTagParametersFromCard`.

### Summary of changes

- FE: 
  - refactoring to match the BE halfway. Previously the logic was split between two functions but now both the BE and FE have it in one
  - added e2e tests for (a) snippets in public questions and (b) card template tags in public questions
- BE: 
  - updated to match the logic on the FE, excluding template tags of type "snippet" and "card"

### What's not included 

`template-tag-parameters` contains duplicated logic with `metabase.query-processor.card/card-template-tag-parameters`. These should probably be merged into a MLv2 function so that logic is not duplicated in different parts of the FE and BE.

### CODE REVIEW

**Comment by calherries** [comment]
@metabase/querying-components This fix includes a refactoring of `frontend/src/metabase-lib/parameters/utils/template-tags.ts` to match the BE code, but I realised that these functions on the FE and BE should probably be replaced by MLv2 functions. Can you take a look and confirm whether continuing to use these functions makes sense, or should I reach for MLv2?

File: test/metabase/models/card_test.clj [hunk 1]
```diff
@@ -327,6 +328,35 @@
        (is (= expected
               (t2/select-one-fn :visualization_settings :model/Card :id (u/the-id card))))))))
 
+(deftest template-tag-parameters-test
+  (testing "Card with a Field filter parameter"
+    (t2.with-temp/with-temp [:model/Card card {:dataset_query (qp.card-test/field-filter-query)}]
```
Comment (qnkhuat) [inline test/metabase/models/card_test.clj:333]:
```suggestion
    (mt/with-temp [:model/Card card {:dataset_query (qp.card-test/field-filter-query)}]
```'

we should use `mt/with-temp` moving forward. It makes future refactoring easier in case we want to change how with-temp works internally.

File: frontend/src/metabase-lib/parameters/utils/template-tags.unit.spec.js [hunk 2]
```diff
@@ -161,6 +168,38 @@ describe("parameters/utils/cards", () => {
...
+          "card-id": 123,
+        }),
+        createMockTemplateTag({
+          type: "snippet",
+          id: "3",
+          "snippet-id": 1,
+          "snippet-name": "C",
+        }),
+      ];
+      expect(getTemplateTagParameters(tags)).toEqual([
```
Comment (qnkhuat) [inline frontend/src/metabase-lib/parameters/utils/template-tags.unit.spec.js:192]: should we write this test using negation? I think it's easier to understand what we want to test here if we write this test as  "template tag does not contains snippet" instead of using equal here.

**Review by qnkhuat — APPROVED** [review]
BE lgtm

File: frontend/src/metabase-lib/parameters/utils/template-tags.ts [hunk 3]
```diff
@@ -60,25 +60,21 @@ export function getTemplateTagParameters(
     .filter(
       tag =>
         tag.type != null &&
+        tag.type !== "card" &&
```
Comment (kamilmielnik) [inline frontend/src/metabase-lib/parameters/utils/template-tags.ts:63]: I think the comment for this function needs to be updated (lines 51-52), at least the path where the clojure function is defined. Is the rest still relevant?

**Review by kamilmielnik — COMMENTED** [review]
Can you please add an e2e test for it?

File: test/metabase/models/card_test.clj (hunk 1 above)
Comment (calherries) [reply test/metabase/models/card_test.clj]: Done a1e7cb5ad37a4a22a2fc2027de2498ee72cbe4f5

File: frontend/src/metabase-lib/parameters/utils/template-tags.unit.spec.js (hunk 2 above)
Comment (calherries) [reply frontend/src/metabase-lib/parameters/utils/template-tags.unit.spec.js:192]: Writing this test with negation is less safe I think. There are many changes I could make to code that would break the functionality but keep the test passing if it were written with negation. The same is not true with the way this test is currently written.

For example, if I wrote this test with negation in clojure, it might be:
```
(is (empty (set/intersection #{:snippet :card) (map :type (get-template-tag-parameters tags))
```
If the way `:type` is represented on a `template-tag` changes, e.g. `{:type :snippet}` changes to `{:type "snippet"}` then this test would still pass even though `get-template-tag-parameters` can be completely broken.

As for understanding, I think the test description is enough to understand pretty quickly what is going on.

File: frontend/src/metabase-lib/parameters/utils/template-tags.ts (hunk 3 above)
Comment (calherries) [reply frontend/src/metabase-lib/parameters/utils/template-tags.ts:63]: Good catch, I've updated the comment. The rest is still relevant of course

**Comment by calherries** [comment]
@kamilmielnik Can you explain why this warrants an e2e test? Maybe a BE test on the endpoint would suffice?

**Comment by kamilmielnik** [comment]
> To me the BE endpoint is simply wrong, this has nothing to do with the FE.
> Maybe a BE test on the endpoint would suffice?

@calherries Fair enough, a BE-only reproduction test should suffice :+1:

**Review by ranquild — COMMENTED** [review]
It would be great to add an E2E test for the original issue

**Comment by calherries** [comment]
@ranquild why?

**Comment by ranquild** [comment]
@calherries because if it broke like that, it means we don't have a single e2e test for public questions with snippets

**Comment by calherries** [comment]
@qnkhuat can you give this a re-review? I've added some BE tests

**Review by qnkhuat — APPROVED** [review]
still good 👍

**Comment by calherries** [comment]
@metabase/querying-components I've added e2e tests for using snippets and card template tags in public questions. Can you review?

File: e2e/test/scenarios/sharing/public-question.cy.spec.js [hunk 4]
```diff
@@ -140,6 +136,64 @@ describe("scenarios > public > question", () => {
       });
     }),
   );
+
+  it("should be able to view public questions with snippets", () => {
+    cy.visit("/");
+
+    openNativeEditor();
```
Comment (kamilmielnik) [inline e2e/test/scenarios/sharing/public-question.cy.spec.js:143]: `openNativeEditor` already does `cy.visit("/")` under the hood

```suggestion
    openNativeEditor();
```

File: e2e/test/scenarios/sharing/public-question.cy.spec.js [hunk 5]
```diff
@@ -140,6 +136,64 @@ describe("scenarios > public > question", () => {
...
+        },
+      );
+    });
+  });
+
+  it("should be able to view public questions with card template tags", () => {
+    cy.createNativeQuestion({
+      name: "Nested Question",
+      native: {
+        query: "SELECT * FROM PEOPLE",
```
Comment (kamilmielnik) [inline e2e/test/scenarios/sharing/public-question.cy.spec.js:174]: Our e2e tests will run a bit faster (which pays out in the long run) if we limit the amount of data exchanged in API requests:

```suggestion
        query: "SELECT * FROM PEOPLE LIMIT 5",
```

**Review by kamilmielnik — APPROVED** [review]
LGTM :+1:

File: e2e/test/scenarios/sharing/public-question.cy.spec.js [hunk 6]
```diff
@@ -140,6 +136,62 @@ describe("scenarios > public > question", () => {
...
+      );
+      cy.findByLabelText("Give your snippet a name").type("string 'test'");
+      cy.findByText("Save").click();
+    });
+
+    cy.get("@editor").type(`{moveToStart}select `);
+
+    saveQuestion("test question", { wrapId: true });
+    cy.get("@questionId").then(id => {
+      cy.request("POST", `/api/card/${id}/public_link`).then(
```
Comment (WiNloSt) [inline e2e/test/scenarios/sharing/public-question.cy.spec.js:159]: we could use `createPublicQuestionLink` which is already imported in this file. This applies to another test too.

File: e2e/test/scenarios/sharing/public-question.cy.spec.js [hunk 7]
```diff
@@ -140,6 +136,62 @@ describe("scenarios > public > question", () => {
...
+        ({ body: { uuid } }) => {
+          cy.visit(`/public/question/${uuid}`);
```
Comment (WiNloSt) [inline e2e/test/scenarios/sharing/public-question.cy.spec.js:161]: I'd sign out and call `cy.signInAsNormalUser()` like other tests to ensure the admin session doesn't have any effect on the public question. Well, it shouldn't anyway, but I'd still do that for consistency with other tests.

File: frontend/src/metabase-lib/parameters/utils/template-tags.ts [hunk 8]
```diff
@@ -60,25 +60,21 @@ export function getTemplateTagParameters(
...
     .map(tag => getTemplateTagParameter(tag, parametersById[tag.id]));
 }
 
-export function getTemplateTagsForParameters(card: Card) {
-  const templateTags: TemplateTag[] =
-    card &&
+export function getTemplateTags(card: Card): TemplateTag[] {
+  return card &&
     card.dataset_query &&
     card.dataset_query.type === "native" &&
```
Comment (uladzimirdev) [inline frontend/src/metabase-lib/parameters/utils/template-tags.ts:74]: nit. `card` existence is checked above, dataset_query always should persist on card, but we can stay on the safe side and use optional chaining
```suggestion
  return card.dataset_query?.type === "native" &&
```

**Review by uladzimirdev — APPROVED** [review]
LGTM

File: frontend/src/metabase-lib/parameters/utils/template-tags.ts (hunk 8 above)
Comment (uladzimirdev) [reply frontend/src/metabase-lib/parameters/utils/template-tags.ts:74]: not only this (I don't trust types I didn't write 😄 ) but also at `getParametersFromCard` there is an explicit check about card 

```
 if (!card) {
    return [];
  }
```

Comment (calherries) [reply frontend/src/metabase-lib/parameters/utils/template-tags.ts:74]: Right, but `getTemplateTagParametersFromCard` is called by three functions other than `getParametersFromCard`, so that's not sufficient.

Comment (calherries) [reply frontend/src/metabase-lib/parameters/utils/template-tags.ts:74]: Yeah I think I'll use `card?.dataset_query?.type === "native"` and leave it at that. I'm not confident in the change to remove the runtime check

Comment (calherries) [reply frontend/src/metabase-lib/parameters/utils/template-tags.ts]: Updated in [0d03b3d](https://github.com/metabase/metabase/pull/37405/commits/0d03b3d156cb3369e0d3f53a7f1221e00bc1e7c8)

File: e2e/test/scenarios/sharing/public-question.cy.spec.js (hunk 7 above)
Comment (calherries) [reply e2e/test/scenarios/sharing/public-question.cy.spec.js:163]: Done [0d03b3d](https://github.com/metabase/metabase/pull/37405/commits/0d03b3d156cb3369e0d3f53a7f1221e00bc1e7c8)

File: e2e/test/scenarios/sharing/public-question.cy.spec.js (hunk 6 above)
Comment (calherries) [reply e2e/test/scenarios/sharing/public-question.cy.spec.js]: Done [0d03b3d](https://github.com/metabase/metabase/pull/37405/commits/0d03b3d156cb3369e0d3f53a7f1221e00bc1e7c8)
