### PR TITLE
Fix searching for uuid column values in dashboard filter

### LINKED ISSUE #59020: Field values search endpoint not returning some field values for FK field referencing a UUID
### Describe the bug

We are seeing a sporadic issue where searching for legal values for a FK field that references a UUID column is only returning results found within the initial 20 records that we show in the preview. Even searching for the full, exact value corresponding to other rows returns no results.

This bug was encountered on the `internal-tools` branch, but we expect that it exists in `master` and our recent releases also.

The corresponding fields do not store fieldvalues.

API route: `/api/field/16147/search/16147?value=...`

Corresponding namespace: `metabase.warehouse-schema.api.field`

### To Reproduce

See [this dashboard](https://stats.metabase.com/dashboard/3469-debug-returning-field-values-search-endpoint-not-returning-uuid-values?id=). Try filtering by the value da445791-e206-4929-ade2-0ad40a0ecdda the filter will return 0 results, while the record exists in the table placed in the dashboard.

### Expected behavior

Search should be able to match any existing values

### Logs

*No response*

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:138.0) Gecko/20100101 Firefox/138.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-06-05",
      "tag": "vUNKNOWN",
      "hash": "57a7d60"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

2 (may escalate towards alpha launch of the internal-tools product)

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes https://github.com/metabase/metabase/issues/59020

### Description

Field in chain filter query is implicitly remapped when it is type/PK and table contains other type/Name field. Prior this PR chain filter query used for values to power up the search operated on the name column instead of id column.

With this PR query returns id field values __only for uuid fields__.

### How to verify

Run new test or follow [this thread](https://metaboat.slack.com/archives/C08E17FN206/p1749488211469999) for repro.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/driver/sql/query_processor.clj [hunk 1]
```diff
@@ -1545,6 +1545,11 @@
   [x]
   (and (driver-api/mbql-clause? x)
        (isa? (or (:effective-type (get x 2))
+                 (let [field-id (some-> x second)]
+                   (when (pos-int? field-id)
+                     (let [{:keys [base-type effective-type]}
+                           (driver-api/field (driver-api/metadata-provider) field-id)]
+                       (or effective-type base-type))))
```
Comment (appleby) [inline src/metabase/driver/sql/query_processor.clj:1552]: why is the ordering here: (1) ET from options, (2) ET from metadata, (3) BT from metadata, (4) BT from options?

File: src/metabase/parameters/chain_filter.clj [hunk 2]
```diff
@@ -117,24 +117,29 @@
 (defn- joined-table-alias [table-id]
   (format "table_%d" table-id))
 
-(def ^:private ^{:arglists '([field-id])} temporal-field?
+(def ^:private ^{:arglists '([field-id])} memoized-field-by-id
   "Whether Field with `field-id` is a temporal Field such as a Date or Datetime. Cached for 10 minutes to avoid hitting
```
Comment (appleby) [inline src/metabase/parameters/chain_filter.clj]: Docstring no longer matches

**Review by appleby — APPROVED** [review]

File: src/metabase/driver/sql/query_processor.clj [hunk 3]
```diff
@@ -1545,6 +1545,11 @@
   [x]
   (and (driver-api/mbql-clause? x)
        (isa? (or (:effective-type (get x 2))
+                 (let [field-id (some-> x second)]
```
Comment (metamben) [inline src/metabase/driver/sql/query_processor.clj]:
```suggestion
                 (let [field-id (second x)]
```

File: src/metabase/driver/sql/query_processor.clj (hunk 1 above)
Comment (metamben) [inline src/metabase/driver/sql/query_processor.clj:1552]: When is this needed? Why can't we rely on the type info being there?

File: src/metabase/parameters/chain_filter.clj [hunk 4]
```diff
@@ -117,24 +117,29 @@
...
   the DB too much since this is unlike to change often, if ever."
```
Comment (metamben) [inline src/metabase/parameters/chain_filter.clj]: The name is not very good (we don't return the whole field, just the type info), and the docstring is out of sync.

File: src/metabase/parameters/chain_filter.clj [hunk 5]
```diff
@@ -722,7 +734,13 @@
   (assert (even? (count options)))
   (let [{:as options}         options
         v->human-readable     (delay (schema.metadata-queries/human-readable-remapping-map field-id))
-        the-remapped-field-id (delay (remapped-field-id field-id))]
+        the-remapped-field-id (delay (let [{:keys [base_type effective_type]} (memoized-field-by-id field-id)]
+                                       (binding [*allow-implicit-remapping*
+                                                 ;; For the details on following condition see the dynamic var's
+                                                 ;; docstring.
```
Comment (metamben) [inline src/metabase/parameters/chain_filter.clj:740]: I think the fact that this influences only how UUID fields are handled should be reflected in the name of the variable.

**Review by metamben — APPROVED** [review]

File: src/metabase/driver/sql/query_processor.clj (hunk 1 above)
Comment (lbrdnk) [reply src/metabase/driver/sql/query_processor.clj:1552]: I wanted the effective type to have precedence over the base type.

File: src/metabase/parameters/chain_filter.clj (hunk 5 above)
Comment (lbrdnk) [reply src/metabase/parameters/chain_filter.clj:740]: I'll modify that shortly.

File: src/metabase/parameters/chain_filter.clj (hunk 4 above)
Comment (lbrdnk) [reply src/metabase/parameters/chain_filter.clj]: I'll update the docstring and name.

File: src/metabase/parameters/chain_filter.clj (hunk 2 above)
Comment (lbrdnk) [reply src/metabase/parameters/chain_filter.clj]: Thanks, I'll adjust that.

File: src/metabase/driver/sql/query_processor.clj (hunk 1 above)
Comment (lbrdnk) [reply src/metabase/driver/sql/query_processor.clj:1552]: This is not _strictly_ needed due to the modification done in `filter-clause` (in src/metabase/parameters/chain_filter.clj). It was an alternative which I've also experimented with. I've decided to leave that in as I believe that makes the codebase more robust overall.

Comment (appleby) [reply src/metabase/driver/sql/query_processor.clj:1552]: Yeah, I just would have expected something like (1) ET from options, (2) ET from metadata, (3) BT from options, (4) BT from metadata or some such, but maybe base types are unlikely to differ in any case.

Comment (lbrdnk) [reply src/metabase/driver/sql/query_processor.clj:1552]: > base types are unlikely to differ in any case

That is my assumption.
