### PR TITLE
Fix detection of backend files when generating i18n EDN

### LINKED ISSUE #24943: Loss of old translations in v0.44.1
In v0.44.1 many translations are missing in the admin settings. I translated these expressions two years ago, in previous versions like 0.43.1 they were present, now they are missing. It happens in Czech and Slovak, probably in others as well (I haven't tried). In PoEditor the expressions are still available.
SettingMenu1
Slack
DoesYour

SettingMenu2
Timezone

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes #24943

Seems like a fairly large number of translations defined in backend files were not being correctly identified as backend strings, and thus not being included in the EDN generated from the `build-translation-resources` script. This is because we were looking at path prefixes and checking whether they were one of `["src" "backend" "enterprise/backend" "shared"]` but a lot of the backend paths in our `.po` files actually start with `metabase/` or `metabase_enterprise/`. (Maybe something changed in the `.po` file generation code at some point?)

I've fixed this by instead just checking for `.clj` and `.cljc` file extensions, rather than going by prefixes. I think this covers all backend files that could contain translations, but let me know if I'm overlooking anything. Also added a unit test for the `backend-message?` function.

### CODE REVIEW

File: test/metabase/util/i18n_test.clj [hunk 1]
```diff
@@ -117,15 +117,15 @@
              (fn [n] (str (i18n/deferred-trsn "{0} table" "{0} tables" n)))}]
       (testing message
         (testing "Should fall back to English if user locale & system locale are unset"
-          (mt/with-temporary-setting-values [site-locale nil])
-          (is (= "0 tables"
-                 (f 0)))
+          (mt/with-temporary-setting-values [site-locale nil]
```
Comment (noahmoss) [inline test/metabase/util/i18n_test.clj:120]: I noticed this test had incorrect nesting so I've fixed it; though I think it wasn't failing in CI anyway because `site-locale` is `nil` by default

Comment (metamben) [reply test/metabase/util/i18n_test.clj:120]: The changes in this file are not related to the real purpose of the PR, are they?

**Review by metamben — APPROVED** [review]
Looks like a reasonable idea to me.

File: test/metabase/util/i18n_test.clj (hunk 1 above)
Comment (noahmoss) [reply test/metabase/util/i18n_test.clj:120]: No, but I noticed it while poking around this code

File: bin/i18n/test/i18n/create_artifacts/backend_test.clj [hunk 2]
```diff
@@ -28,3 +28,33 @@
...
                  (str/split-lines)))))
+
+(deftest backend-message?
+  (testing "messages present in any .clj and .cljc files are detected as backend messages"
+    (are [source-references expected] (= (@#'backend/backend-message? {:source-references source-references})
+                                         expected)
+      ;; Simple .clj and .cljc files with and without line numbers
+      ["test.clj"]                                                                  true
+      ["test.clj:123"]                                                              true
+      ["test.clj"]                                                                  true
```
Comment (tsmacdonald) [inline bin/i18n/test/i18n/create_artifacts/backend_test.clj:39]:
```suggestion
      ["test.cljc"]                                                                 true
```

**Review by tsmacdonald — APPROVED** [review]

File: bin/i18n/test/i18n/create_artifacts/backend_test.clj (hunk 2 above)
Comment (noahmoss) [reply bin/i18n/test/i18n/create_artifacts/backend_test.clj:39]: Whoops, thanks

File: src/metabase/api/table.clj [hunk 3]
```diff
@@ -338,7 +338,7 @@
   "Schema name to use for the saved questions virtual database for Cards that are in the root collection (i.e., not in
   any collection)."
   []
-  (tru "Everything else"))
+  "Everything else")
```
Comment (noahmoss) [inline src/metabase/api/table.clj:341]: For future reference, this is not a user-facing string, and the fact that it was being translated on the BE but not translated on the FE was causing a Cypress test to fail. [Here's a discussion](https://metaboat.slack.com/archives/C010L1Z4F9S/p1666210591030479) about it on Slack.

**Comment by tsmacdonald** [comment]
Looks good to me :boat:

**Comment by mazameli** [comment]
@noahmoss So if we do a 44.6 we'll need to rebuild the .pot files, no?

**Comment by noahmoss** [comment]
@mazameli No, not the POT files -- this has to do with the script that converts the PO files download from POEditor to the EDN files consumed by the backend. I think this is done automatically as part of the build process but I'm not 100% on that.
