### PR TITLE
Filter nulls out of histograms

### LINKED ISSUE #16049: Histograms should filter out null x values
When plotting data with nulls in the x dimension, linear scales filter out that row and ordinal scales display it. Histogram scales act line ordinal but I think they should act like linear.

## Linear

Repro steps:
1. Count Orders by Discount with auto binning
2. See the leftmost histogram bar

Related to #15554

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #16049

Due to some visualization setting hackery, histograms were showing bars for nulls. Only ordinal charts should do that. I worked around the issue.

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/renderer_utils.js [hunk 1]
```diff
@@ -142,16 +142,20 @@ function getParseOptions({ settings, data }) {
   };
 }
 
+function canDisplayNull(settings) {
+  // histograms are converted to ordinal scales, so we need this ugly logic as a workaround
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/lib/renderer_utils.js:146]: https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js#L817

☝️ That's the culprit. I thought about unwinding it, but that seemed like too big of a change for my penultimate day at Metabase.

File: frontend/src/metabase/visualizations/lib/settings/graph.js [hunk 2]
```diff
@@ -402,7 +402,6 @@ export const GRAPH_AXIS_SETTINGS = {
     section: t`Axes`,
     title: t`X-axis scale`,
     widget: "select",
-    default: "ordinal",
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/lib/settings/graph.js:405]: Unrelated to the fix, but I noticed it wasn't doing anything since `getDefault` is used.

**Review by alxnddr — APPROVED** [review]
Looks good 👍
