### PR TITLE
E2E test coverage for "Highlight the selected data source in the notebook editor" project

### LINKED ISSUE #25142: Data Selector opens with database field picker if no saved questions exist, but models exist
**Describe the bug**

image

**To Reproduce**

1. Have no saved question in the system
2. Save one or more model.
3. `+New` › `Question`
4. Data selector will open with the Sample Dataset field picker (if that's the data you use) 

**Expected behavior**

Data selector should open with the option to choose between Raw Data or Models.

### LINKED ISSUE #39542: [Epic] Highlight the selected data source in the notebook editor
**Links**
- [product doc](https://www.notion.so/metabase/Highlight-the-selected-data-source-in-the-query-builder-877bf66e580543eb881fca601a714817)
- feature branch: `highlight-data-source`
- issue links: N/A
- [testing plan](https://github.com/metabase/metabase/issues/39544)

**Implementation Plan**
Any of the initial tasks can be expanded into a full-blown task list as we learn more about them. For each item on the list, the plan is to:
1. go over the happy-path scenarios
2. document what's not working
3. fix what's not working
4. add tests

```[tasklist]
### Cleanup and refactoring
- [ ] https://github.com/metabase/metabase/pull/39681
```

```[tasklist]
### Dimensions
- [x] Ad-hoc
- [x] Saved question (simple)
- [x] Saved question (nested)
- [x] Saved model (view + edit query definition)
```

```[tasklist]
### Edge cases
- [ ] TBD
```

```[tasklist]
## Existing or related issue
- [ ] #39699
- [ ] #25142
- [ ] https://github.com/metabase/metabase/issues/39807
- [ ] https://github.com/metabase/metabase/issues/39812
```

### LINKED ISSUE #39544: [Testing plan] Highlight the selected data source in the notebook editor
# Testing plan for #39542

## Dimensions
- Type of the query
    - Ad-hoc
    - Saved
- Type of the entity
    - Question
        - GUI
        - Native
    - Model
- Source-table
    - Table `:id`
    - Question `card__:id`
- Where was the entity saved (collection permissions play the role here)
    - Root collection
    - Personal collection
- How many data(bases) sources are there?
    - Only one
    - Multiple

## Actions
TBD

## Test Cases
TBD

### PR DESCRIPTION
**Pull request by nemanjaglumac**
This PR adds a test coverage for #39542
Closes #39542
Closes #39544
Closes #25142

Reproduces #25142
Reproduces #40223

### CODE REVIEW

File: e2e/support/cypress_sample_instance_data.js [hunk 1]
```diff
@@ -53,6 +53,9 @@ export const FIRST_COLLECTION_ID = _.findWhere(
   { name: "First collection" },
 ).id;
 
+/**
+ * @type number
+ */
```
Comment (nemanjaglumac) [inline e2e/support/cypress_sample_instance_data.js:58]: Before we end up converting all helpers to TS, some of the monkey-patching will be needed because TS complains in TS specs.

File: e2e/test/scenarios/question/notebook-data-source.cy.spec.ts [hunk 2]
```diff
@@ -0,0 +1,331 @@
...
+  });
+
+  describe("saved entity as a source (aka the virtual table)", () => {
+    const modelDetails = {
+      name: "GUI Model",
+      query: { "source-table": REVIEWS_ID, limit: 1 },
+      display: "table",
+      type: "model",
+      collection_id: SECOND_COLLECTION_ID,
+    };
```
Comment (kamilmielnik) [inline e2e/test/scenarios/question/notebook-data-source.cy.spec.ts:202]: Only `modelDetails.name` is used later on.

**Review by kamilmielnik — APPROVED** [review]
:+1:

File: e2e/test/scenarios/question/notebook-data-source.cy.spec.ts (hunk 2 above)
Comment (nemanjaglumac) [reply e2e/test/scenarios/question/notebook-data-source.cy.spec.ts:202]: Ok?
I mostly extract this for readability.

Comment (kamilmielnik) [reply e2e/test/scenarios/question/notebook-data-source.cy.spec.ts:202]: It looks like this object was meant to be passed to `createQuestion` but instead a different (identical) object is passed there - this duplication looks like a leftover.

Comment (nemanjaglumac) [reply e2e/test/scenarios/question/notebook-data-source.cy.spec.ts:202]: Oh, could be.
Will take a look at it. Thank you.

Comment (nemanjaglumac) [reply e2e/test/scenarios/question/notebook-data-source.cy.spec.ts:202]: I was stuck at a discrepancy between how the data picker works in OSS vs EE mode so I might have missed a few other details. Thanks again.
https://github.com/metabase/metabase/issues/40223

Comment (nemanjaglumac) [reply e2e/test/scenarios/question/notebook-data-source.cy.spec.ts]: Addressed this comment in https://github.com/metabase/metabase/pull/40199/commits/d32bd0eda24d72d6be1e83dfb2e188a8fbe66306

File: e2e/test/scenarios/question/notebook-data-source.cy.spec.ts [hunk 3]
```diff
@@ -0,0 +1,357 @@
...
+      });
+    });
+  });
+
+  describe("saved entity as a source (aka the virtual table)", () => {
+    const modelDetails = {
+      name: "GUI Model",
+      query: { "source-table": REVIEWS_ID, limit: 1 },
+      display: "table",
+      type: "model" as const,
```
Comment (nemanjaglumac) [inline e2e/test/scenarios/question/notebook-data-source.cy.spec.ts:235]: This was needed because otherwise TS complains that "string" is not compatible with the type `CardType | undefined`

File: e2e/test/scenarios/question/notebook-data-source.cy.spec.ts (hunk 2 above)
Comment (kamilmielnik) [reply e2e/test/scenarios/question/notebook-data-source.cy.spec.ts]: IMO the best way out is to explicitly define the type of `modelDetails`, like this: `const modelDetails: Parameters<typeof cy.createQuestion>[0] = {`. No casting and we get a proper type check.

Comment (nemanjaglumac) [reply e2e/test/scenarios/question/notebook-data-source.cy.spec.ts]: Sounds good.
But my only concern is what happens if we ever decide to change the order in the future?

**Comment by nemanjaglumac** [comment]
Stress-test after https://github.com/metabase/metabase/pull/40199/commits/ff0d3509a80e245d24a85f16f10022afce23b198
https://github.com/metabase/metabase/actions/runs/8324903214
