### PR TITLE
40232 sortable with popovers

### LINKED ISSUE #40232: Parameter filter widget jumps and doesn't allow to pick a value
### Describe the bug

Instead of allowing to pick the value for the filter, the widget jumps (as if sorting has begun) and does nothing.

https://github.com/metabase/metabase/assets/2196347/96c8f918-c677-47df-b0bc-15a41642e60d

Must be related to `Sortable` because when I comment it out, the bug no longer exists. https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/components/ParametersList.jsx#L53-L59

### To Reproduce

1. Create a native query with a template tag. Literlaly `{{ x }}` will work
2. Set it to a list of values (shouldn't contain actual values)
3. Try clicking the filter widget, entering a value and clicking "add" or "update"

May not be 100% reproducible every time but at some point you'll see awkward jumping and the actual adding/change won't happen.

### Expected behavior

The value should be selectable. 
It shouldn't "jump" without actual dragging happening. 

### Logs

_No response_

### Information about your Metabase installation

```JSON
True as of `6fe41dd4379f4476b3eb78215b600393dd34474d`
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/40232

### Description
Bug was caused by the sortable element wrapping entire popover components, rather than only their triggers that are rendered on screen. This change moves the sortable element down to the different types of parameters, and if there are popovers then only the trigger is wrapped with `<Sortable>`

### How to verify
1. New -> SQL Query
2. Create a query with some parameters, and change one to be a search box
3. Click the parameter to open the popover, and try dragging the popover to the right. It should not move the parameter

### Demo
chrome_o2h78ln8iT

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.jsx [hunk 1]
```diff
@@ -59,6 +64,8 @@ export class ParameterWidget extends Component {
         commitImmediately={commitImmediately}
         setParameterValueToDefault={setParameterValueToDefault}
         enableRequiredBehavior={enableParameterRequiredBehavior}
+        isSortable={isSortable}
```
Comment (ranquild) [inline frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.jsx:67]: Can we pass `isSortable={isSortable && !isEditing}` here to avoid adding `disableSort`? or something like that

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.jsx (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.jsx:67]: Yessir!
