### PR TITLE
Overhaul add-implicit-joins, fix/consolidate metadata normalization and other issues

### LINKED ISSUE #39882: [MLv2 × QP] Migrate pre-processing middleware `metabase.query-processor.middleware.add-implicit-joins`

### LINKED ISSUE #58314: Native model with column alias and mapped DB column in metadata errors on join
### Describe the bug

When a native model has a column alias, and that column's metadata indicates it is mapped to an underlying column in the database with a different name, a new question cannot join this model.

### To Reproduce

1. Create a SQL model from Orders `SELECT id, product_id as prod_id FROM orders`
2. In Metadata > prod_id > Database column this maps to > Orders > "Product ID" and save.
Image
3. Create a new question, starting from Products, joining with the previous model

Image

Image

If you remove the metadata mapping to the column, it works again.

### Expected behavior

It should run the question correctly regardless of the Model's field reference in metadata settings.

### Logs

_No response_

### Information about your Metabase installation

```JSON
v0.54.8
```

### Severity

P2

### Additional context

The problem seems to be related to the mapped database column having a different name from the aliased column. 
The question generates the following SQL, using the mapped column name (product_id) instead of the actual column name of the model (prod_id)

```sql
SELECT
  "PUBLIC"."PRODUCTS"."ID" AS "ID",
  "PUBLIC"."PRODUCTS"."EAN" AS "EAN",
  "PUBLIC"."PRODUCTS"."TITLE" AS "TITLE",
  "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY",
  "PUBLIC"."PRODUCTS"."VENDOR" AS "VENDOR",
  "PUBLIC"."PRODUCTS"."PRICE" AS "PRICE",
  "PUBLIC"."PRODUCTS"."RATING" AS "RATING",
  "PUBLIC"."PRODUCTS"."CREATED_AT" AS "CREATED_AT",
  "Orders model"."ID" AS "Orders model__ID",
  "Orders model"."PRODUCT_ID" AS "Orders model__PRODUCT_ID" -- Wrong, it should be prod_id
FROM
  "PUBLIC"."PRODUCTS"
 
LEFT JOIN (
    select
      id,
      product_id as prod_id
    from
      orders
  ) AS "Orders model" ON "PUBLIC"."PRODUCTS"."ID" = "Orders model"."PROD_ID" -- Correct? 🤔
LIMIT
  1048575
```

As a workaround, removing the "Database column this maps to" setting on foreign keys fixes the issue

### LINKED ISSUE #59695: Implicit joins via a joined data source don't work when the main data source is not a raw table
### Describe the bug

Implicit joins via a joined data source don't work when the main data source is not a raw table.

### To Reproduce

1. New -> Question -> Orders -> Save as `Orders Question`
2. New -> Question -> `Orders Question` -> Join `Invoices` -> Filter ` Account -> Plan is Basic` -> Run the query

Image

Based on the error, the QP is pushing the joined field to the source query incorrectly.

Reproduced on:
- x.55.x
- v0.54.1
- v0.53.1

### Expected behavior

The query should work. More context here https://metaboat.slack.com/archives/C05MPF0TM3L/p1749737656045579

### Logs

`add-alias-info` throws an error, but at this point the query is already invalid.

```
{
    "type": "invalid-query",
    "clause": [
        "field", 32, {"join-alias": "Invoices"}
    ],
    "query": {
        "source-table": 5,
        "qp/stage-is-from-source-card": 28,
        "fields": [
            ["field", 37, null],
            ["field", 43, null],
            ["field", 40, null],
            ["field", 44, null],
            ["field", 38, null],
            ["field", 42, null],
            ["field", 36, null],
            ["field", 41, null],
            ["field", 39, null],
            ["field", 32, {"join-alias": "Invoices"}]
        ]
    }
}
```

### Information about your Metabase installation

```JSON
master (v55, `f5b5de0dbd185638a37465d3d6f518d04059564c`)
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #58314
Fixes #59695
Resolves #39882
Fixes QUE-1566
Fixes QUE-1563
Fixes QUE-1573
Resolves QUE-1574
Fixes QUE-1575
Fixes QUE-1576
Fixes QUE-1577

This is really just a first pass at converting this middleware to Lib; not everything is idiomatic (there is a lot of raw MBQL clause generation) but after my first attempt at a much more substantial rewrite #61307 floundered I decided to try something a little more minimal for a first pass.

I fixed a bunch of other issues related to metadata roundtripping and normalization that I haven't bothered to open bugs for yet

### CODE REVIEW

File: src/metabase/query_processor/middleware/add_implicit_joins.clj [hunk 1]
```diff
@@ -3,255 +3,336 @@
...
-  [{:keys [source-query joins]}]
-  (distinct
-   (into joins
-         (when source-query
-           (visible-joins source-query)))))
+  [query                       :- ::lib.schema/query
+   path                        :- ::lib.walk/path
+   {:keys [joins], :as _stage} :- ::lib.schema/stage]
+  (into (vec joins)
+        (distinct)
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/add_implicit_joins.clj]: This is a subtle change of behaviour - the new logic only de-duplicates the new joins with themselves, not the entire list of joins.

Contrast `(into [] (comp cat (distinct)) [joins (when-let ...)])`

File: src/metabase/query_processor/middleware/add_implicit_joins.clj [hunk 2]
```diff
@@ -3,255 +3,336 @@
...
 
     :else
-    (let [form (cond-> form
-                 (empty? source-query-fields) (update :source-query qp.add-implicit-clauses/add-implicit-mbql-clauses))]
-      (if (empty? (get-in form [:source-query :fields]))
-        form
-        (-> form
-            add-condition-fields-to-source
-            (add-referenced-fields-to-source reused-joins))))))
+    (as-> stage $stage
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/add_implicit_joins.clj]:
```suggestion
    (->> stage
```

**Review by bshepherdson — APPROVED** [review]
