### PR TITLE
display sql transforms errors in editor

### LINKED ISSUE #71042: Transform SQL editor fails to return error
### Describe the bug

Image

Queries with errors don't return any feedback. 

400 error in console.

### To Reproduce

In the transforms SQL editor, write a query with a syntax error. 

Try to run it. 

Nothing happens in the UI.

### Expected behavior

Metabase should respond with the error.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "e2e",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2026-03-17",
      "tag": "v1.59.3",
      "hash": "aafb270"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.13 (Debian 16.13-1.pgdg13+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.8"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.10+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.10+7-LTS",
    "os.name": "Linux",
    "os.version": "6.10.14-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

It's not clear whether your query is broken, or Metabase is broken.

### Additional context

https://metaboat.slack.com/archives/C096T8NED1S/p1773770893867369

### PR DESCRIPTION
**Pull request by chodorowicz**
closes #71042
Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

The error from running an adhoc querywas swallowed, instead of being passed to the editor.
I've also updated `setupCardDataset` API call mock, so it accepts also `status` parameter.

### How to verify

Run SQL transform with an error, e.g. `SELECXT 1 as num`

### Demo

https://www.loom.com/share/8c2a88425d99402fb2481619fb3feb45

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/querying/editor/hooks/use-query-results/use-query-results.ts [hunk 1]
```diff
@@ -85,3 +86,7 @@ export function useQueryResults(
     cancelQuery,
   };
 }
+
+function hasDataset(value: unknown): value is { data: Dataset } {
+  return typeof value === "object" && value !== null && "data" in value;
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/editor/hooks/use-query-results/use-query-results.ts]: `import { isObject } from "metabase-types/guards";` + 

```suggestion
  return isObject(value) && "data" in value;
```

File: frontend/src/metabase/querying/editor/hooks/use-query-results/use-query-results.unit.spec.ts [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+  native: { query: "SELECXT 1" },
+});
+
+const ERROR_DATASET: Dataset = {
+  ...createMockDataset(),
+  data: createMockDatasetData({}),
+  error: 'ERROR: syntax error at or near "SELECXT"',
+  error_type: "invalid-query",
+  status: "failed",
+};
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/editor/hooks/use-query-results/use-query-results.unit.spec.ts]:
```suggestion
const ERROR_DATASET = createMockDataset({
  error: 'ERROR: syntax error at or near "SELECXT"',
  error_type: "invalid-query",
  status: "failed",
});
```

**Review by kamilmielnik — APPROVED** [review]

File: frontend/src/metabase/querying/editor/hooks/use-query-results/use-query-results.unit.spec.ts (hunk 2 above)
Comment (chodorowicz) [reply frontend/src/metabase/querying/editor/hooks/use-query-results/use-query-results.unit.spec.ts]: https://github.com/metabase/metabase/pull/71092/commits/8082b3af32ba25a206f49491c4936650d9f309ac

Season 3 Wall GIF by The Simpsons

File: frontend/src/metabase/querying/editor/hooks/use-query-results/use-query-results.ts (hunk 1 above)
Comment (chodorowicz) [reply frontend/src/metabase/querying/editor/hooks/use-query-results/use-query-results.ts]: https://github.com/metabase/metabase/pull/71092/commits/d0fab3653fea2a33768e54e8cc34612bef87e2a9
