### PR TITLE
Truncate Slack attachments (namely dashboard filters) that are too long

### LINKED ISSUE #25704: Dashboard Slack Subscription hits slack API max characters allowed per block
**Describe the bug**
When setting up a Dashboard to be sent via Slack and the default filter parameters exceed 2000 characters the dashboard is not sent and there is an error in the logs

**Logs**

`Caused by: clojure.lang.ExceptionInfo: Slack API error: invalid_attachments {:error-code "invalid_attachments", :message "Slack API error: invalid_attachments", :response {:ok false, :error "invalid_attachments", :errors ["failed to match all allowed schemas [json-pointer:/attachments/0/blocks/1/fields/0]" "must be less than 2001 characters [json-pointer:/attachments/0/blocks/1/fields/0/text]"], :response_metadata {:messages ["[ERROR] failed to match all allowed schemas [json-pointer:/attachments/0/blocks/1/fields/0]" "[ERROR] must be less than 2001 characters [json-pointer:/attachments/0/blocks/1/fields/0/text]"]}}}`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a metabase instance that has Slack integrated.
2. Click on add Dashboard and then Add filter Text
3. You have 2 options now, either create a Default list having a lot of parameters that would amount to 2000 characters or just 1 parameter of 2000 characters:

image

4. Add a question (doesn't matter which since without a question the sent to slack option is not visible) -> Save -> Subscription -> Sent to Slack -> See error in logs

**Expected behaviour**
The Dashboard is sent irrespective of how large the Filter List is 

**Information about your Metabase Installation:**

- Metabase version: (e.g., 0.44.3)

### PR DESCRIPTION
**Pull request by tsmacdonald**
[Fixes #25704]

I have a soft preference for using real constants instead of dynamic vars if the only reason to be dynamic is for testing (as you can see), but if somebody has a good reason to do it the other way I'm happy to be converted.

Tested in #bot-testing

### CODE REVIEW

File: test/metabase/dashboard_subscription_test.clj [hunk 1]
```diff
@@ -289,70 +289,71 @@
...
+        :slack
+        (fn [{:keys [card-id dashboard-id]} [pulse-results]]
+          (testing "Markdown cards are included in attachments list as :blocks sublists, and markdown is
+                  converted to mrkdwn (Slack markup language) and truncated appropriately"
+            (is (= {:channel-id "#general"
+                    :attachments
+                    [{:blocks [{:type "header", :text {:type "plain_text", :text "Aviary KPIs", :emoji true}}
+                               {:type "section",
+                                :fields [{:type "mrkdwn", :text (str (subs "*State*\nCA, NY and NJ" 0 14)       "…")}
+                                         {:type "mrkdwn", :text (str (subs "*Quarter and Year*\nQ1, 2021" 0 14) "…")}]}
```
Comment (noahmoss) [inline test/metabase/dashboard_subscription_test.clj:322]: My personal bias is towards minimizing logic in the expected values of tests, so I'd probably just write these out as the literal values. Not a big deal either way though.

**Review by noahmoss — APPROVED** [review]

**Comment by noahmoss** [comment]
@tsmacdonald Are you planning on backporting?
