### PR TITLE
fix arabic number inconsistency

### LINKED ISSUE #34271: Inconsistent display of numbers in Arabic locales
### Describe the bug

When the locale is set to Arabic, visualizations show Western numbers except for dates which are shown with Arabic numerals.

products_arabic_locale

### To Reproduce

1. Set Instance Language to Arabic in Admin Settings / Localization.
2. Open any chart or table with dates and other numbers and see dates are in Arabic, while other numbers are displayed with Western numerals.

### Expected behavior

In a visualization, all numbers should be displayed the same way. Ideally whether to display Arabic or Western numerals should be configurable / selectable.

### Logs

n/a

### Information about your Metabase installation

```JSON
`1.47.2`
```

### Severity

It has been reported / requested by a customer.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by EmmadUsmani**
Closes https://github.com/metabase/metabase/issues/34271

### Description

In Arabic locales (`ar` and `ar-sa`), we were displaying Arabic numerals for translated dates, but in the rest of the app we used Western numerals. This PR makes it so that for  dates we also use Western numerals.

Ideally we would have an option for which kind of numeral to use, but it's a sufficient solution to always use Western numerals. Even in Arabic-speaking countries where Arabic numerals are widely used, Western numerals are commonly seen on digital interfaces, so users should not be bothered by it.

### How to verify

1. Go to the Products model.
2. See "Created At" field in English.
3. Go to account settings, change language to "Arabic", then go back to Products model.
4. "Created At" field should now be translated, but using Western numerals.
5. Repeat the same for "Arabic (Saudi Arabia)" locale, and using admin site locale setting.
6. Go back to English, in Products model should see English dates again.

### Demo

https://github.com/metabase/metabase/assets/37751258/826375a2-1f85-4a3d-9abf-fab2e26dd0c0

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by EmmadUsmani** [comment]
Current dependencies on/for this PR:
* master
  * **PR #34633** <a href="https://app.graphite.dev/github/pr/metabase/metabase/34633" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/34633?utm_source=stack-comment).

File: frontend/src/metabase/lib/formatting/date.tsx [hunk 1]
```diff
@@ -690,16 +690,18 @@ function replaceDateFormatNames(format: string, options: OptionsType) {
 }
 
 function formatDateTimeWithFormats(
-  value: number,
+  value: number | Moment,
```
Comment (EmmadUsmani) [inline frontend/src/metabase/lib/formatting/date.tsx:693]: This is not needed for the fix, but I wanted to update the type to reflect the fact that this function is called with `value` as a `Moment` object.

**Review by alxnddr — APPROVED** [review]

**Comment by EmmadUsmani** [comment]
### Merge activity

* **Oct 31, 1:24 PM**: @EmmadUsmani merged this pull request with [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/34633).
