### PR TITLE
Pass parameter values as JSON

### LINKED ISSUE #46240: Text Filters turn number like entries into numeric when filtering on static embedding
### Describe the bug

If you have a question inside a dashboard and you try to use a TEXT filter on TEXT field it will fail for values such as "1234567" when using static embedding

### To Reproduce

1. Go to New -> Question -> Sample Database -> Products -> Save
2. Add the Question to Dashboard -> Add a TEXT Filter (set it as an input/search box) and link it to Category
3. Setup Static Embedding and try to filter using 12345 as an entry

You can go to stats using this [dashboard](https://stats.metabase.com/dashboard/2552-test-text-filter-turns-numeric?text=)

Go to Static Embedding and simply add 1234 to the filter, it fails with the following error:

image

Notice that on metabase it works without problem and outputs a no results found

image

The issue is that on static embedding when you type a number the where clause is sending a `"CATEGORY" = 1234` and if you type anything else which is not numeric you get `"CATEGORY" = '1234x'`

### Expected behavior

Text filter works

### Logs

1618970a-de54-4df8-b1e0-45ba1c5a1d7f] 2024-07-29T18:07:23+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Data conversion error converting "Gizmo"; SQL statement:
-- Metabase:: userID: 1 queryType: MBQL queryHash: 90c17f8cdbff4b671604d7ae59913a0a5a024d9477e6d75b5f3652471593844a
SELECT "PUBLIC"."PRODUCTS"."ID" AS "ID", "PUBLIC"."PRODUCTS"."EAN" AS "EAN", "PUBLIC"."PRODUCTS"."TITLE" AS "TITLE", "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY", "PUBLIC"."PRODUCTS"."VENDOR" AS "VENDOR", "PUBLIC"."PRODUCTS"."PRICE" AS "PRICE", "PUBLIC"."PRODUCTS"."RATING" AS "RATING", "PUBLIC"."PRO [22018-214]
{:database_id 1,
 :started_at #t "2024-07-29T16:07:22.359501Z[GMT]",
 :via
 [{:status :failed,
   :class org.h2.jdbc.JdbcSQLDataException,
   :error
   "Data conversion error converting \"Gizmo\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 90c17f8cdbff4b671604d7ae59913a0a5a024d9477e6d75b5f3652471593844a\nSELECT \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\", \"PUBLIC\".\"PRODUCTS\".\"EAN\" AS \"EAN\", \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\", \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\", \"PUBLIC\".\"PRODUCTS\".\"VENDOR\" AS \"VENDOR\", \"PUBLIC\".\"PRODUCTS\".\"PRICE\" AS \"PRICE\", \"PUBLIC\".\"PRODUCTS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"PRO [22018-214]",
   :stacktrace
   ["org.h2.message.DbException.getJdbcSQLException(DbException.java:506)"
    "org.h2.message.DbException.getJdbcSQLException(DbException.java:477)"
    "org.h2.message.DbException.get(DbException.java:212)"
    "org.h2.value.ValueStringBase.getInt(ValueStringBase.java:133)"
    "org.h2.value.Value.convertToInt(Value.java:1575)"
    "org.h2.value.Value.convertTo(Value.java:1135)"
    "org.h2.value.Value.convertTo(Value.java:1003)"
    "org.h2.value.Value.compareToNotNullable(Value.java:2630)"
    "org.h2.value.Value.compareWithNull(Value.java:2654)"
    "org.h2.engine.SessionLocal.compareWithNull(SessionLocal.java:1966)"
    "org.h2.expression.condition.Comparison.compare(Comparison.java:250)"
    "org.h2.expression.condition.Comparison.getValue(Comparison.java:222)"
    "org.h2.expression.Expression.getBooleanValue(Expression.java:332)"
    "org.h2.command.query.Select.isConditionMet(Select.java:449)"
    "org.h2.command.query.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1835)"
    "org.h2.result.LazyResult.hasNext(LazyResult.java:78)"
    "org.h2.result.FetchedResult.next(FetchedResult.java:34)"
    "org.h2.command.query.Select.queryFlat(Select.java:728)"
    "org.h2.command.query.Select.queryWithoutCache(Select.java:833)"
    "org.h2.command.query.Query.queryWithoutCacheLazyCheck(Query.java:197)"
    "org.h2.command.query.Query.query(Query.java:512)"
    "org.h2.command.query.Query.query(Query.java:475)"
    "org.h2.command.CommandContainer.query(CommandContainer.java:251)"
    "org.h2.command.Command.executeQuery(Command.java:190)"
    "org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:247)"
    "org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)"
    "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
    "--> driver.sql_jdbc.execute$fn__81456.invokeStatic(execute.clj:569)"
    "driver.sql_jdbc.execute$fn__81456.invoke(execute.clj:567)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:577)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:574)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__81537$fn__81538.invoke(execute.clj:714)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__81537.invoke(execute.clj:713)"
    "driver.h2$fn__84725$fn__84727.invoke(h2.clj:546)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:337)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:320)"
    "driver.h2$fn__84725.invokeStatic(h2.clj:537)"
    "driver.h2$fn__84725.invoke(h2.clj:533)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:707)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:704)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
    "driver.sql_jdbc$fn__115437.invokeStatic(sql_jdbc.clj:78)"
    "driver.sql_jdbc$fn__115437.invoke(sql_jdbc.clj:76)"
    "driver.h2$fn__84564.invokeStatic(h2.clj:272)"
    "driver.h2$fn__84564.invoke(h2.clj:268)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
    "query_processor.execute$run.invokeStatic(execute.clj:61)"
    "query_processor.execute$run.invoke(execute.clj:55)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__70034.invoke(execute.clj:24)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__70039.invoke(execute.clj:35)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70025.invoke(cache.clj:242)"
    "query_processor.middleware.permissions$check_query_permissions$fn__64004.invoke(permissions.clj:118)"
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__110068$check_download_permissions__110069$fn__110070.invoke(permissions.clj:90)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__64614.invoke(enterprise.clj:51)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$fn__111901$maybe_apply_column_level_perms_check__111902$fn__111903.invoke(column_level_perms_check.clj:38)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__64624.invoke(enterprise.clj:64)"
    "query_processor.execute$execute$fn__70066.invoke(execute.clj:93)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
    "query_processor.execute$execute.invokeStatic(execute.clj:92)"
    "query_processor.execute$execute.invoke(execute.clj:88)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__81906$handle_audit_app_internal_queries__81907$fn__81908.invoke(handle_audit_queries.clj:145)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__64652.invoke(enterprise.clj:103)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__75840.invoke(process_userland_query.clj:186)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__75909.invoke(catch_exceptions.clj:128)"
    "query_processor$process_query$fn__75946.invoke(query_processor.clj:78)"
    "query_processor.setup$do_with_canceled_chan$fn__65056.invoke(setup.clj:189)"
    "query_processor.setup$do_with_database_local_settings$fn__65051.invoke(setup.clj:181)"
    "query_processor.setup$do_with_driver$fn__65046$fn__65047.invoke(setup.clj:166)"
    "driver$do_with_driver.invokeStatic(driver.clj:104)"
    "driver$do_with_driver.invoke(driver.clj:99)"
    "query_processor.setup$do_with_driver$fn__65046.invoke(setup.clj:165)"
    "query_processor.setup$do_with_metadata_provider$fn__65039$fn__65042.invoke(setup.clj:151)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:171)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:160)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
    "query_processor.setup$do_with_metadata_provider$fn__65039.invoke(setup.clj:150)"
    "query_processor.setup$do_with_resolved_database$fn__65033.invoke(setup.clj:128)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
    "query_processor$process_query.invokeStatic(query_processor.clj:76)"
    "query_processor$process_query.invoke(query_processor.clj:69)"
    "query_processor.card$process_query_for_card_default_qp.invokeStatic(card.clj:170)"
    "query_processor.card$process_query_for_card_default_qp.invoke(card.clj:166)"
    "api.public$process_query_for_card_with_id_run_fn$run__99074$fn__99075$fn__99076.invoke(public.clj:140)"
    "server.middleware.session$do_with_current_user.invokeStatic(session.clj:425)"
    "server.middleware.session$do_with_current_user.invoke(session.clj:408)"
    "api.public$process_query_for_card_with_id_run_fn$run__99074$fn__99075.invoke(public.clj:139)"
    "query_processor.streaming$_streaming_response$fn__68509$fn__68510$fn__68511.invoke(streaming.clj:175)"
    "query_processor.streaming$_streaming_response$fn__68509$fn__68510.invoke(streaming.clj:174)"
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
    "query_processor.streaming$_streaming_response$fn__68509.invoke(streaming.clj:171)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:68)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66)"
    "async.streaming_response$do_f_async$task__52275.invoke(streaming_response.clj:87)"],
   :state "22018"}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: Data conversion error converting \"Gizmo\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 90c17f8cdbff4b671604d7ae59913a0a5a024d9477e6d75b5f3652471593844a\nSELECT \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\", \"PUBLIC\".\"PRODUCTS\".\"EAN\" AS \"EAN\", \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\", \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\", \"PUBLIC\".\"PRODUCTS\".\"VENDOR\" AS \"VENDOR\", \"PUBLIC\".\"PRODUCTS\".\"PRICE\" AS \"PRICE\", \"PUBLIC\".\"PRODUCTS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"PRO [22018-214]",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__81537$fn__81538.invoke(execute.clj:716)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__81537.invoke(execute.clj:713)"
    "driver.h2$fn__84725$fn__84727.invoke(h2.clj:546)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:337)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:320)"
    "driver.h2$fn__84725.invokeStatic(h2.clj:537)"
    "driver.h2$fn__84725.invoke(h2.clj:533)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:707)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:704)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
    "driver.sql_jdbc$fn__115437.invokeStatic(sql_jdbc.clj:78)"
    "driver.sql_jdbc$fn__115437.invoke(sql_jdbc.clj:76)"
    "driver.h2$fn__84564.invokeStatic(h2.clj:272)"
    "driver.h2$fn__84564.invoke(h2.clj:268)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
    "query_processor.execute$run.invokeStatic(execute.clj:61)"
    "query_processor.execute$run.invoke(execute.clj:55)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__70034.invoke(execute.clj:24)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__70039.invoke(execute.clj:35)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70025.invoke(cache.clj:242)"
    "query_processor.middleware.permissions$check_query_permissions$fn__64004.invoke(permissions.clj:118)"
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__110068$check_download_permissions__110069$fn__110070.invoke(permissions.clj:90)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__64614.invoke(enterprise.clj:51)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$fn__111901$maybe_apply_column_level_perms_check__111902$fn__111903.invoke(column_level_perms_check.clj:38)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__64624.invoke(enterprise.clj:64)"
    "query_processor.execute$execute$fn__70066.invoke(execute.clj:93)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
    "query_processor.execute$execute.invokeStatic(execute.clj:92)"
    "query_processor.execute$execute.invoke(execute.clj:88)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__81906$handle_audit_app_internal_queries__81907$fn__81908.invoke(handle_audit_queries.clj:145)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__64652.invoke(enterprise.clj:103)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__75840.invoke(process_userland_query.clj:186)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__75909.invoke(catch_exceptions.clj:128)"
    "query_processor$process_query$fn__75946.invoke(query_processor.clj:78)"
    "query_processor.setup$do_with_canceled_chan$fn__65056.invoke(setup.clj:189)"
    "query_processor.setup$do_with_database_local_settings$fn__65051.invoke(setup.clj:181)"
    "query_processor.setup$do_with_driver$fn__65046$fn__65047.invoke(setup.clj:166)"
    "driver$do_with_driver.invokeStatic(driver.clj:104)"
    "driver$do_with_driver.invoke(driver.clj:99)"
    "query_processor.setup$do_with_driver$fn__65046.invoke(setup.clj:165)"
    "query_processor.setup$do_with_metadata_provider$fn__65039$fn__65042.invoke(setup.clj:151)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:171)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:160)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
    "query_processor.setup$do_with_metadata_provider$fn__65039.invoke(setup.clj:150)"
    "query_processor.setup$do_with_resolved_database$fn__65033.invoke(setup.clj:128)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
    "query_processor$process_query.invokeStatic(query_processor.clj:76)"
    "query_processor$process_query.invoke(query_processor.clj:69)"
    "query_processor.card$process_query_for_card_default_qp.invokeStatic(card.clj:170)"
    "query_processor.card$process_query_for_card_default_qp.invoke(card.clj:166)"
    "api.public$process_query_for_card_with_id_run_fn$run__99074$fn__99075$fn__99076.invoke(public.clj:140)"
    "server.middleware.session$do_with_current_user.invokeStatic(session.clj:425)"
    "server.middleware.session$do_with_current_user.invoke(session.clj:408)"
    "api.public$process_query_for_card_with_id_run_fn$run__99074$fn__99075.invoke(public.clj:139)"
    "query_processor.streaming$_streaming_response$fn__68509$fn__68510$fn__68511.invoke(streaming.clj:175)"
    "query_processor.streaming$_streaming_response$fn__68509$fn__68510.invoke(streaming.clj:174)"
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
    "query_processor.streaming$_streaming_response$fn__68509.invoke(streaming.clj:171)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:68)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66)"
    "async.streaming_response$do_f_async$task__52275.invoke(streaming_response.clj:87)"],
   :error_type :invalid-query,
   :ex-data
   {:driver :h2,
    :sql
    ["-- Metabase:: userID: 1 queryType: MBQL queryHash: 90c17f8cdbff4b671604d7ae59913a0a5a024d9477e6d75b5f3652471593844a"
     "SELECT"
     "  \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\","
     "  \"PUBLIC\".\"PRODUCTS\".\"EAN\" AS \"EAN\","
     "  \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\","
     "  \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\","
     "  \"PUBLIC\".\"PRODUCTS\".\"VENDOR\" AS \"VENDOR\","
     "  \"PUBLIC\".\"PRODUCTS\".\"PRICE\" AS \"PRICE\","
     "  \"PUBLIC\".\"PRODUCTS\".\"RATING\" AS \"RATING\","
     "  \"PUBLIC\".\"PRODUCTS\".\"CREATED_AT\" AS \"CREATED_AT\""
     "FROM"
     "  \"PUBLIC\".\"PRODUCTS\""
     "WHERE"
     "  \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" = 1234"
     "LIMIT"
     "  10000"],
    :params nil,
    :type :invalid-query}}],
 :action_id nil,
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 10000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :userland-query? true},
  :cache-strategy nil,
  :viz-settings {:table.pivot_column "CATEGORY", :table.cell_column "PRICE"},
  :database 1,
  :query {:source-table 8},
  :parameters
  [{:type :string/=,
    :value [1234],
    :slug "text",
    :id "28b7ec17",
    :target [:dimension [:field 58 {:base-type :type/Text}]]}]},
 :native
 {:query
  "SELECT \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\", \"PUBLIC\".\"PRODUCTS\".\"EAN\" AS \"EAN\", \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\", \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\", \"PUBLIC\".\"PRODUCTS\".\"VENDOR\" AS \"VENDOR\", \"PUBLIC\".\"PRODUCTS\".\"PRICE\" AS \"PRICE\", \"PUBLIC\".\"PRODUCTS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"PRODUCTS\".\"CREATED_AT\" AS \"CREATED_AT\" FROM \"PUBLIC\".\"PRODUCTS\" WHERE \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" = 1234 LIMIT 10000",
  :params nil},
 :status :failed,
 :class java.lang.NumberFormatException,
 :stacktrace
 ["java.base/java.lang.NumberFormatException.forInputString(Unknown Source)"
  "java.base/java.lang.Integer.parseInt(Unknown Source)"
  "java.base/java.lang.Integer.parseInt(Unknown Source)"
  "org.h2.value.ValueStringBase.getInt(ValueStringBase.java:131)"
  "org.h2.value.Value.convertToInt(Value.java:1575)"
  "org.h2.value.Value.convertTo(Value.java:1135)"
  "org.h2.value.Value.convertTo(Value.java:1003)"
  "org.h2.value.Value.compareToNotNullable(Value.java:2630)"
  "org.h2.value.Value.compareWithNull(Value.java:2654)"
  "org.h2.engine.SessionLocal.compareWithNull(SessionLocal.java:1966)"
  "org.h2.expression.condition.Comparison.compare(Comparison.java:250)"
  "org.h2.expression.condition.Comparison.getValue(Comparison.java:222)"
  "org.h2.expression.Expression.getBooleanValue(Expression.java:332)"
  "org.h2.command.query.Select.isConditionMet(Select.java:449)"
  "org.h2.command.query.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1835)"
  "org.h2.result.LazyResult.hasNext(LazyResult.java:78)"
  "org.h2.result.FetchedResult.next(FetchedResult.java:34)"
  "org.h2.command.query.Select.queryFlat(Select.java:728)"
  "org.h2.command.query.Select.queryWithoutCache(Select.java:833)"
  "org.h2.command.query.Query.queryWithoutCacheLazyCheck(Query.java:197)"
  "org.h2.command.query.Query.query(Query.java:512)"
  "org.h2.command.query.Query.query(Query.java:475)"
  "org.h2.command.CommandContainer.query(CommandContainer.java:251)"
  "org.h2.command.Command.executeQuery(Command.java:190)"
  "org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:247)"
  "org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__81456.invokeStatic(execute.clj:569)"
  "driver.sql_jdbc.execute$fn__81456.invoke(execute.clj:567)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:577)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:574)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__81537$fn__81538.invoke(execute.clj:714)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__81537.invoke(execute.clj:713)"
  "driver.h2$fn__84725$fn__84727.invoke(h2.clj:546)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:337)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:320)"
  "driver.h2$fn__84725.invokeStatic(h2.clj:537)"
  "driver.h2$fn__84725.invoke(h2.clj:533)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:707)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:704)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)"
  "driver.sql_jdbc$fn__115437.invokeStatic(sql_jdbc.clj:78)"
  "driver.sql_jdbc$fn__115437.invoke(sql_jdbc.clj:76)"
  "driver.h2$fn__84564.invokeStatic(h2.clj:272)"
  "driver.h2$fn__84564.invoke(h2.clj:268)"
  "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
  "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
  "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
  "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
  "query_processor.execute$run.invokeStatic(execute.clj:61)"
  "query_processor.execute$run.invoke(execute.clj:55)"
  "query_processor.execute$add_native_form_to_result_metadata$fn__70034.invoke(execute.clj:24)"
  "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__70039.invoke(execute.clj:35)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70025.invoke(cache.clj:242)"
  "query_processor.middleware.permissions$check_query_permissions$fn__64004.invoke(permissions.clj:118)"
  "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__110068$check_download_permissions__110069$fn__110070.invoke(permissions.clj:90)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__64614.invoke(enterprise.clj:51)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$fn__111901$maybe_apply_column_level_perms_check__111902$fn__111903.invoke(column_level_perms_check.clj:38)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__64624.invoke(enterprise.clj:64)"
  "query_processor.execute$execute$fn__70066.invoke(execute.clj:93)"
  "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225)"
  "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
  "query_processor.execute$execute.invokeStatic(execute.clj:92)"
  "query_processor.execute$execute.invoke(execute.clj:88)"
  "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)"
  "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__81906$handle_audit_app_internal_queries__81907$fn__81908.invoke(handle_audit_queries.clj:145)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__64652.invoke(enterprise.clj:103)"
  "query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__75840.invoke(process_userland_query.clj:186)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__75909.invoke(catch_exceptions.clj:128)"
  "query_processor$process_query$fn__75946.invoke(query_processor.clj:78)"
  "query_processor.setup$do_with_canceled_chan$fn__65056.invoke(setup.clj:189)"
  "query_processor.setup$do_with_database_local_settings$fn__65051.invoke(setup.clj:181)"
  "query_processor.setup$do_with_driver$fn__65046$fn__65047.invoke(setup.clj:166)"
  "driver$do_with_driver.invokeStatic(driver.clj:104)"
  "driver$do_with_driver.invoke(driver.clj:99)"
  "query_processor.setup$do_with_driver$fn__65046.invoke(setup.clj:165)"
  "query_processor.setup$do_with_metadata_provider$fn__65039$fn__65042.invoke(setup.clj:151)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:171)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:160)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:151)"
  "query_processor.setup$do_with_metadata_provider$fn__65039.invoke(setup.clj:150)"
  "query_processor.setup$do_with_resolved_database$fn__65033.invoke(setup.clj:128)"
  "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)"
  "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
  "query_processor$process_query.invokeStatic(query_processor.clj:76)"
  "query_processor$process_query.invoke(query_processor.clj:69)"
  "query_processor.card$process_query_for_card_default_qp.invokeStatic(card.clj:170)"
  "query_processor.card$process_query_for_card_default_qp.invoke(card.clj:166)"
  "api.public$process_query_for_card_with_id_run_fn$run__99074$fn__99075$fn__99076.invoke(public.clj:140)"
  "server.middleware.session$do_with_current_user.invokeStatic(session.clj:425)"
  "server.middleware.session$do_with_current_user.invoke(session.clj:408)"
  "api.public$process_query_for_card_with_id_run_fn$run__99074$fn__99075.invoke(public.clj:139)"
  "query_processor.streaming$_streaming_response$fn__68509$fn__68510$fn__68511.invoke(streaming.clj:175)"
  "query_processor.streaming$_streaming_response$fn__68509$fn__68510.invoke(streaming.clj:174)"
  "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
  "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
  "query_processor.streaming$_streaming_response$fn__68509.invoke(streaming.clj:171)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:68)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66)"
  "async.streaming_response$do_f_async$task__52275.invoke(streaming_response.clj:87)"],
 :card_id 135,
 :context :embedded-dashboard,
 :error
 "Data conversion error converting \"Gizmo\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 90c17f8cdbff4b671604d7ae59913a0a5a024d9477e6d75b5f3652471593844a\nSELECT \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\", \"PUBLIC\".\"PRODUCTS\".\"EAN\" AS \"EAN\", \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\", \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\", \"PUBLIC\".\"PRODUCTS\".\"VENDOR\" AS \"VENDOR\", \"PUBLIC\".\"PRODUCTS\".\"PRICE\" AS \"PRICE\", \"PUBLIC\".\"PRODUCTS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"PRO [22018-214]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 10000},
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :userland-query? true},
  :user-parameters
  [{:value [1234],
    :type :string/=,
    :slug "text",
    :id "28b7ec17",
    :target [:dimension [:field 58 {:base-type :type/Text}]]}],
  :viz-settings {:table.pivot_column "CATEGORY", :table.cell_column "PRICE"},
  :info
  {:executed-by 1,
   :context :embedded-dashboard,
   :card-id 135,
   :card-name "Products",
   :dashboard-id 11,
   :visualization-settings {:table.pivot_column "CATEGORY", :table.cell_column "PRICE"}},
  :database 1,
  :type :query,
  :query
  {:source-table 8,
   :filter
   [:=
    [:field 58 {:base-type :type/Text}]
    [:value
     1234
     {:base_type :type/Text,
      :effective_type :type/Text,
      :coercion_strategy nil,
      :semantic_type :type/Category,
      :database_type "CHARACTER VARYING",
      :name "CATEGORY"}]],
   :fields
   [[:field 62 nil]
    [:field 63 nil]
    [:field 65 nil]
    [:field 58 nil]
    [:field 60 nil]
    [:field 59 nil]
    [:field 61 nil]
    [:field 64 {:temporal-unit :default}]],
   :limit 10000,
   :metabase.query-processor.middleware.limit/original-limit nil}},
 :data {:rows [], :cols []}}

### Information about your Metabase installation

```JSON
Tested this on 1.50.17 and also stats. 

Doesn't happen on 49
```

### Severity

Major issue cause it's breaking dashboards. To give a perspective a customer hitting this has 50+ dashboards that they have built and are customer-facing, many of which have 10+ filters, so they would need to go and audit + update all of those to resolve the issue completely

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/46240

The problem was that we pass parameter values as separate query string params in embeded cards & dashboards. It looks like this `?param1=A&param2=10&param3=true`. The issue is that we cannot correctly parse these parameters on the BE since any type information was lost during the parameter values serialization. Is `10` a number or a string? Is `true` a boolean or a string? We don't know. We could do either 1) pass parameters from the FE in another way where this information is not lost OR 2) find the corresponding fields for each parameter, check their types, and convert the values correctly. The latter is difficult and could be a performance concern, so this PR implements 1).

Now parameter values are passed as `?parameters=<json>`. This is exactly the same as public dashboards work right now. To maintain backward compatibility we still accept separate parameter values if `parameters` is not present or when it cannot be parsed. I thought that breaking the API contract for `query` endpoints is not acceptable in a patch release.

How to verify:
- Enable embedding in Admin
- New -> Question -> Products -> Save as `Q1`
- New -> Dashboard -> Add `Q1` -> Add Text filter for `Product.Category` -> Set the parameter to be just `Input` -> Save
- Share -> Embed -> Static -> Enable the parameter -> Preview -> Look and feel
- Try to enter a numeric value in the parameter widget
- The query should not fail. There should be no results.
- We have e2e tests that check embedded cards & dashboards and downloads in them.

### CODE REVIEW

File: frontend/src/metabase/redux/downloads.ts [hunk 1]
```diff
@@ -143,11 +146,13 @@ const getDatasetParams = ({
     // For whatever wacky reason the /api/embed endpoint expect params like ?key=value instead
     // of like ?params=<json-encoded-params-array> like the other endpoints do.
```
Comment (adam-james-v) [inline frontend/src/metabase/redux/downloads.ts:147]: Might be worth updating this comment, as now the endpoints will work with json encoded params

**Comment by nemanjaglumac** [comment]
Tried everything I could think of in this scenario.
Required filter, default values, editable, locked, export PDF, download xlsx, csv, json...

Everything works like a charm!
🚀

**Review by adam-james-v — APPROVED** [review]
Using the json encoded parameters is a much better approach, thanks for this PR!
