### PR TITLE
Simplify and shorten upload table names

### LINKED ISSUE #52116: Uploading CSV file containing unicode characters to a ClickHouse database creates table with long URL-encoded name
### Describe the bug

Uploading a CSV file named `سلام.csv` (basename has 4 graphemes encoded as 8 bytes) will create a table named `upload_%d8%b3%d9%84%d8%a7%d9%85_20250114151659` (46 bytes).  I.e. uploading a file with a relatively short name can cause the table name to be quite large.

This can cause ClickHouse table name length limits to be violated, causing problems executing operations on the database: In another example, a 19 grapheme (37 bytes) CSV file name ended up as a 131 bytes table name, which internally in ClickHouse operations ended up as a 203 byte file name, that eventually prevented database operations, cf. https://github.com/ClickHouse/ClickHouse/issues/64861#issuecomment-2586989564 and https://github.com/metabase/harbormaster/issues/5751.

To workaround this, is it possible to create the table with the original unicode name instead of URL-encoding it?

### To Reproduce

1. Connect a Metabase instance to a ClickHouse database and configure it for uploads
2. Create a file named `سلام.csv`
3. Upload the file through Metabase's "Upload CSV" button in the left side bar
4. Execute `SHOW TABLES IN [...]` in ClickHouse
5. Notice the table name `upload_%d8%b3%d9%84%d8%a7%d9%85_20250114151659`

### Expected behavior

Metabase encodes file names in a more space-efficient way.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "clickhouse",
      "h2",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "starter",
    "version": {
      "date": "2024-12-09",
      "tag": "v1.52.2.1",
      "hash": "35a4c28"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Blocking some users

### Additional context

References: https://github.com/metabase/harbormaster/issues/5751
References: https://github.com/ClickHouse/ClickHouse/issues/64861

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes: https://github.com/metabase/metabase/issues/52116

Note that of icu4j was already a dependency, via graalvm. 

We have just made it explicit now, ~~and updated to the latest version.~~ ([upgrading version breaks rendering](https://github.com/metabase/metabase/actions/runs/12926546646/job/36049844305?pr=52581))

```
org.graalvm.js/js 22.3.5
  . org.graalvm.regex/regex 22.3.5
    . org.graalvm.truffle/truffle-api 22.3.5
    . com.ibm.icu/icu4j 71.1
  . org.graalvm.truffle/truffle-api 22.3.5
    . org.graalvm.sdk/graal-sdk 22.3.5
  . org.graalvm.sdk/graal-sdk 22.3.5
  . com.ibm.icu/icu4j 71.1
```

### CODE REVIEW

File: test/metabase/upload_test.clj [hunk 1]
```diff
@@ -253,12 +253,19 @@
...
+
 (deftest ^:parallel unique-table-name-test
   (mt/test-drivers (mt/normal-drivers-with-feature :uploads)
     (testing "File name is slugified"
-      (is (=? #"my_file_name_\d+" (@#'upload/unique-table-name driver/*driver* "my file name"))))
+      (is (=? #"my_file_name_\d+" (unique-table-name "my file name"))))
     (testing "semicolons are removed"
-      (is (nil? (re-find #";" (@#'upload/unique-table-name driver/*driver* "some text; -- DROP TABLE.csv")))))
+      (let [escaped (unique-table-name "some text; -- DROP TABLE.csv")]
+        (is (nil? (re-find #";" escaped)))
```
Comment (crisptrutski) [inline test/metabase/upload_test.clj:265]: Redundant right now, but protects against a dumb regression if we change the way we escape again.

**Comment by crisptrutski** [comment]
This breaks `metabase.channel.render.body-test/multiseries-dashcard-render-filters-test`, and superficially I have no idea why.

File: src/metabase/upload.clj [hunk 2]
```diff
@@ -145,11 +146,24 @@
                 (t/plus (t/seconds 1))
                 (t/truncate-to :seconds))))))
 
+(def ^:private transliterator (Transliterator/getInstance "Any-Latin; Latin-ASCII"))
```
Comment (piranha) [inline src/metabase/upload.clj:149]: We need a better one tbh, because this one generates weird translit. Results of this seem quite sane to me: `"Arabic-Latin; Bulgarian-Latin/BGN; Cyrillic-Latin/BGN; Greek-Latin/BGN; Any-Latin; Latin-ASCII"`.

File: src/metabase/upload.clj [hunk 3]
```diff
@@ -145,11 +146,24 @@
...
+
 (defn- unique-table-name
   "Append the current datetime to the given name to create a unique table name. The resulting name will be short enough for the given driver (truncating the supplied `table-name` if necessary)."
   [driver table-name]
+  ;; TODO we should not rely on the timestamp to make the filename unique
+  ;; Ideally we would add an incrementing count, but it may be cheaper and easier to include some randomness.
   (let [time-format                 "_yyyyMMddHHmmss"
-        slugified-name               (or (u/slugify table-name) "")
+        slugified-name               (transliterate table-name)
+        slugified-name               (if (str/blank? slugified-name) "blank" slugified-name)
```
Comment (piranha) [inline src/metabase/upload.clj:166]:
```suggestion
        slugified-name               (or (not-empty (transliterate table-name)) "blank")
```

maybe like this? 😁

File: src/metabase/upload.clj [hunk 4]
```diff
@@ -145,11 +146,24 @@
...
 
+(def ^:private transliterator (Transliterator/getInstance "Any-Latin; Latin-ASCII"))
+
+(defn- transliterate [s]
+  (when-not (str/blank? s)
+    (-> (.transliterate ^Transliterator transliterator ^String s)
+        (str/replace #"\s+" "_")
+        (str/replace #"[^\w]+" "_")
+        (str/replace #"_{2,}" "_")
+        (str/replace #"^_|_$" ""))))
```
Comment (piranha) [inline src/metabase/upload.clj:157]: + `str/trim` here?

**Review by sansolovyov — APPROVED** [review]
Except that transliterator set needs to be improved everything else seems fine.

File: src/metabase/upload.clj (hunk 3 above)
Comment (crisptrutski) [reply src/metabase/upload.clj:166]: Calling seq on a string is a bit gross, wastes memory, but this is much cleaner! Didn't think of it.

File: src/metabase/upload.clj (hunk 2 above)
Comment (crisptrutski) [reply src/metabase/upload.clj:149]: Can you give an example of what's weird about it?

Comment (crisptrutski) [reply src/metabase/upload.clj:149]: Would be good to have test cases driving it

Comment (piranha) [reply src/metabase/upload.clj:149]: The main one is `"шо" => "sho"` (not "so"), but also `"хліб" => "khlib"` (rather than "hlib").

I also am struggling to find an example for Greek I figured out last time, my repl history is hiding that. :\ Also I think we can drop generic `Cyrillic-Latin/BGN` from that set, isn't really needed it seems.

File: src/metabase/upload.clj (hunk 3 above)
Comment (piranha) [reply src/metabase/upload.clj:166]: we really need `str/not-blank` <_<
