### PR TITLE
Fixing aggregate dropdowns in dashboard filters

### LINKED ISSUE #12985: Dashboard filter dropdown/search not shown for nested questions (Saved Questions and aggregated)
**Describe the bug**
When a question is based on a nested query (Saved Question or filtered aggregate), then it doesn't show the dropdown list values on dashboard filters.

**Workaround**
Include another question with the column needed for dropdown, which isn't aggregated, and also connect the filter to that question. That will make the dashboard filter show a dropdown. This does not work for Search until #24741 is fixed.

**Reproduce example 1**
1. Simple question > Sample Dataset > Products
2. Save question as Q1
3. Simple question > Saved Questions > Q1
4. Save question as Q2 and add to dashboard
5. Add two filter linked to Q2, a time "All options" for "Created At" and a "Other categories" for "Category" and save dashboard
6. Refresh the page, the browser console will have errors like this:
```
Request entities,fields,field-literal,CATEGORY,type/Text,fetch failed: 
Object { status: 404, data: "API endpoint does not exist.", isCancelled: false }
Request entities,fields,field-literal,CREATED_AT,type/DateTime,fetch failed: 
Object { status: 404, data: "API endpoint does not exist.", isCancelled: false }
```
And log shows calls to literals instead of :id's
```
07-23 15:28:06 WARN middleware.log :: GET /api/field/field-literal%2CCATEGORY%2Ctype%2FText 404 386.4 µs (0 DB calls) 
"API endpoint does not exist."
07-23 15:28:06 WARN middleware.log :: GET /api/field/field-literal%2CCREATED_AT%2Ctype%2FDateTime 404 737.1 µs (0 DB calls) 
"API endpoint does not exist."
```
7. Clicking the Category filter will only show a text input instead of a dropdown list of values
image

**Reproduce example 2**
1. Custom question > Sample Data > Products
2. Summarize Count by Category
3. Aggregation filter Count greater than 1
image
4. Save question, add to dashboard and add filter `Other Categories` and connect to question.
5. Clicking the Category filter will show plain-text input instead of a dropdown list of values:
image

Since version 0.42.x the log will now produce a large stacktrace `Parameter "9784a25d" does not have any Fields associated with it`:
<details><summary>Full stacktrace</summary>

```
2022-05-15 11:55:32,625 ERROR middleware.log :: GET /api/dashboard/6/params/9784a25d/values 500 12.7 ms (5 DB calls) 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "Parameter \"9784a25d\" does not have any Fields associated with it",
   :data
   {:param
    {:name "Text",
     :slug "text",
     :id "9784a25d",
     :type :string/=,
     :sectionId "string",
     :mappings
     #{{:parameter_id "9784a25d",
        :card_id 337,
        :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]],
        :dashcard
        {:sizeX 4,
         :collection_authority_level nil,
         :card
         {:description nil,
          :archived false,
          :collection_position nil,
          :table_id 10,
          :result_metadata
          ({:description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
            :semantic_type :type/Category,
            :coercion_strategy nil,
            :name "CATEGORY",
            :settings nil,
            :field_ref [:field 107 nil],
            :effective_type :type/Text,
            :id 107,
            :display_name "Category",
            :fingerprint
            {:global {:distinct-count 4, :nil% 0.0},
             :type
             {:type/Text
              {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
            :base_type :type/Text}
           {:description "The source of the product.",
            :semantic_type :type/Company,
            :coercion_strategy nil,
            :name "VENDOR",
            :settings nil,
            :field_ref [:field 109 nil],
            :effective_type :type/Text,
            :id 109,
            :display_name "Vendor",
            :fingerprint
            {:global {:distinct-count 200, :nil% 0.0},
             :type
             {:type/Text
              {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}},
            :base_type :type/Text}
           {:display_name "Count",
            :semantic_type :type/Quantity,
            :field_ref [:field "count" {:base-type :type/BigInteger}],
            :name "count",
            :base_type :type/BigInteger,
            :effective_type :type/BigInteger,
            :fingerprint
            {:global {:distinct-count 1, :nil% 0.0},
             :type {:type/Number {:min 1.0, :q1 1.0, :q3 1.0, :max 1.0, :sd 0.0, :avg 1.0}}}}),
          :database_id 4,
          :enable_embedding false,
          :collection_id nil,
          :query_type :query,
          :name "Test 12985 - QB Products filter aggregated",
          :creator_id 1,
          :updated_at #t "2022-05-15T11:55:28.981",
          :made_public_by_id nil,
          :embedding_params nil,
          :cache_ttl nil,
          :dataset_query
          {:database 4,
           :query
           {:source-query {:source-table 10, :aggregation [[:count]], :breakout [[:field 107 nil] [:field 109 nil]]},
            :filter [:> [:field "count" {:base-type :type/Integer}] 0]},
           :type :query},
          :id 337,
          :display :table,
          :visualization_settings {:table.pivot_column "CATEGORY", :table.cell_column "count"},
          :dataset false,
          :created_at #t "2020-10-24T11:32:10.460",
          :public_uuid nil},
         :updated_at #t "2022-05-15T11:55:25.053",
         :col 0,
         :id 1428,
         :parameter_mappings
         [{:parameter_id "9784a25d", :card_id 337, :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]]}],
         :card_id 337,
         :visualization_settings {},
         :dashboard_id 6,
         :created_at #t "2022-05-15T11:55:24.843",
         :sizeY 4,
         :row 0}}}}},
   :at [metabase.api.dashboard$fn__69608$chain_filter__69617$fn__69620 invoke "dashboard.clj" 631]}],
 :trace
 [[metabase.api.dashboard$fn__69608$chain_filter__69617$fn__69620 invoke "dashboard.clj" 631]
  [metabase.api.dashboard$fn__69608$chain_filter__69617 invoke "dashboard.clj" 607]
  [metabase.api.dashboard$fn__69608$chain_filter__69617$fn__69618 invoke "dashboard.clj" 618]
  [metabase.api.dashboard$fn__69608$chain_filter__69617 invoke "dashboard.clj" 607]
  [metabase.api.dashboard$fn__69643 invokeStatic "dashboard.clj" 657]
  [metabase.api.dashboard$fn__69643 invoke "dashboard.clj" 649]
  [compojure.core$wrap_response$fn__32284 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__32268 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__32273 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 151]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__65391 invoke "auth.clj" 14]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32324 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 299]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [metabase.api.routes$fn__76516$fn__76519 invoke "routes.clj" 56]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__76661$fn__76662 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32324 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 299]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [metabase.server.routes$fn__76649$fn__76651 invoke "routes.clj" 41]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73644 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__73641 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__77130$fn__77131$fn__77132 invoke "log.clj" 209]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__77130$fn__77131 invoke "log.clj" 201]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__77130 invoke "log.clj" 200]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80483 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__55251 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__79638 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__79656 invoke "json.clj" 98]
  [metabase.server.middleware.offset_paging$handle_paging$fn__55275 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__80750 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__80766 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__34391 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__45744$fn__45745 invoke "session.clj" 262]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 243]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 235]
  [metabase.server.middleware.session$bind_current_user$fn__45744 invoke "session.clj" 261]
  [metabase.server.middleware.session$wrap_current_user_info$fn__45731 invoke "session.clj" 221]
  [metabase.server.middleware.session$wrap_session_id$fn__45717 invoke "session.clj" 167]
  [metabase.server.middleware.auth$wrap_api_key$fn__65399 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__80670 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__34374 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__34399 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__80712 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__34402 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80499 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__76903 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 388]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 633]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 380]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 386]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run "Thread.java" 829]],
 :cause "Parameter \"9784a25d\" does not have any Fields associated with it",
 :data
 {:param
  {:name "Text",
   :slug "text",
   :id "9784a25d",
   :type :string/=,
   :sectionId "string",
   :mappings
   #{{:parameter_id "9784a25d",
      :card_id 337,
      :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]],
      :dashcard
      {:sizeX 4,
       :collection_authority_level nil,
       :card
       {:description nil,
        :archived false,
        :collection_position nil,
        :table_id 10,
        :result_metadata
        ({:description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
          :semantic_type :type/Category,
          :coercion_strategy nil,
          :name "CATEGORY",
          :settings nil,
          :field_ref [:field 107 nil],
          :effective_type :type/Text,
          :id 107,
          :display_name "Category",
          :fingerprint
          {:global {:distinct-count 4, :nil% 0.0},
           :type
           {:type/Text
            {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
          :base_type :type/Text}
         {:description "The source of the product.",
          :semantic_type :type/Company,
          :coercion_strategy nil,
          :name "VENDOR",
          :settings nil,
          :field_ref [:field 109 nil],
          :effective_type :type/Text,
          :id 109,
          :display_name "Vendor",
          :fingerprint
          {:global {:distinct-count 200, :nil% 0.0},
           :type
           {:type/Text
            {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}},
          :base_type :type/Text}
         {:display_name "Count",
          :semantic_type :type/Quantity,
          :field_ref [:field "count" {:base-type :type/BigInteger}],
          :name "count",
          :base_type :type/BigInteger,
          :effective_type :type/BigInteger,
          :fingerprint
          {:global {:distinct-count 1, :nil% 0.0},
           :type {:type/Number {:min 1.0, :q1 1.0, :q3 1.0, :max 1.0, :sd 0.0, :avg 1.0}}}}),
        :database_id 4,
        :enable_embedding false,
        :collection_id nil,
        :query_type :query,
        :name "Test 12985 - QB Products filter aggregated",
        :creator_id 1,
        :updated_at #t "2022-05-15T11:55:28.981",
        :made_public_by_id nil,
        :embedding_params nil,
        :cache_ttl nil,
        :dataset_query
        {:database 4,
         :query
         {:source-query {:source-table 10, :aggregation [[:count]], :breakout [[:field 107 nil] [:field 109 nil]]},
          :filter [:> [:field "count" {:base-type :type/Integer}] 0]},
         :type :query},
        :id 337,
        :display :table,
        :visualization_settings {:table.pivot_column "CATEGORY", :table.cell_column "count"},
        :dataset false,
        :created_at #t "2020-10-24T11:32:10.460",
        :public_uuid nil},
       :updated_at #t "2022-05-15T11:55:25.053",
       :col 0,
       :id 1428,
       :parameter_mappings
       [{:parameter_id "9784a25d", :card_id 337, :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]]}],
       :card_id 337,
       :visualization_settings {},
       :dashboard_id 6,
       :created_at #t "2022-05-15T11:55:24.843",
       :sizeY 4,
       :row 0}}}}},
 :message "Parameter \"9784a25d\" does not have any Fields associated with it",
 :param
 {:name "Text",
  :slug "text",
  :id "9784a25d",
  :type :string/=,
  :sectionId "string",
  :mappings
  #{{:parameter_id "9784a25d",
     :card_id 337,
     :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]],
     :dashcard
     {:sizeX 4,
      :collection_authority_level nil,
      :card
      {:description nil,
       :archived false,
       :collection_position nil,
       :table_id 10,
       :result_metadata
       ({:description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
         :semantic_type :type/Category,
         :coercion_strategy nil,
         :name "CATEGORY",
         :settings nil,
         :field_ref [:field 107 nil],
         :effective_type :type/Text,
         :id 107,
         :display_name "Category",
         :fingerprint
         {:global {:distinct-count 4, :nil% 0.0},
          :type
          {:type/Text
           {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
         :base_type :type/Text}
        {:description "The source of the product.",
         :semantic_type :type/Company,
         :coercion_strategy nil,
         :name "VENDOR",
         :settings nil,
         :field_ref [:field 109 nil],
         :effective_type :type/Text,
         :id 109,
         :display_name "Vendor",
         :fingerprint
         {:global {:distinct-count 200, :nil% 0.0},
          :type
          {:type/Text
           {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}},
         :base_type :type/Text}
        {:display_name "Count",
         :semantic_type :type/Quantity,
         :field_ref [:field "count" {:base-type :type/BigInteger}],
         :name "count",
         :base_type :type/BigInteger,
         :effective_type :type/BigInteger,
         :fingerprint
         {:global {:distinct-count 1, :nil% 0.0},
          :type {:type/Number {:min 1.0, :q1 1.0, :q3 1.0, :max 1.0, :sd 0.0, :avg 1.0}}}}),
       :database_id 4,
       :enable_embedding false,
       :collection_id nil,
       :query_type :query,
       :name "Test 12985 - QB Products filter aggregated",
       :creator_id 1,
       :updated_at #t "2022-05-15T11:55:28.981",
       :made_public_by_id nil,
       :embedding_params nil,
       :cache_ttl nil,
       :dataset_query
       {:database 4,
        :query
        {:source-query {:source-table 10, :aggregation [[:count]], :breakout [[:field 107 nil] [:field 109 nil]]},
         :filter [:> [:field "count" {:base-type :type/Integer}] 0]},
        :type :query},
       :id 337,
       :display :table,
       :visualization_settings {:table.pivot_column "CATEGORY", :table.cell_column "count"},
       :dataset false,
       :created_at #t "2020-10-24T11:32:10.460",
       :public_uuid nil},
      :updated_at #t "2022-05-15T11:55:25.053",
      :col 0,
      :id 1428,
      :parameter_mappings
      [{:parameter_id "9784a25d", :card_id 337, :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]]}],
      :card_id 337,
      :visualization_settings {},
      :dashboard_id 6,
      :created_at #t "2022-05-15T11:55:24.843",
      :sizeY 4,
      :row 0}}}}}
```

</details>

**Information about your Metabase Installation:**
Metabase 0.36.0 thru 0.43.0, multiple different setups.

**Severity**
Only giving P2, since it's not a regression, but it makes filters from nested queries much less useful (which was fixed in 0.36.0 #9802 and 0.37.0 #11007).

**Additional context**
If going to the question Q2 in example 1 step 4 and clicking Category-column > Filter, then it doesn't show a list either, which is likely #5594.
This is not the case for the question in example 2, it will show the dropdown list.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by markbastian**
The `values-from-card-query` constructs a new query to determine enumerable values for filter drop-downs in dashboards. It does this by generating a simple query from the passed in query with the filtered value as a query filter. This query didn't know about expressions which the filter might use. The fix was to just add in the expressions from the base query.

Fixes #12985

### CODE REVIEW

File: src/metabase/models/params/custom_values.clj [hunk 1]
```diff
@@ -52,13 +52,16 @@
...
      :type     :query
      :query    (merge
-                 {:source-table (format "card__%d" (:id card))
-                  :breakout     [value-field]
-                  :limit        *max-rows*}
+                 (cond-> {:source-table (format "card__%d" (:id card))
+                          :breakout     [value-field]
+                          :limit        *max-rows*}
+                   expressions
+                   (assoc :expressions expressions))
```
Comment (adam-james-v) [inline src/metabase/models/params/custom_values.clj:64]: Just curious: is the query map not allowed to have `{:expressions nil}` ? If it could, we wouldn't need the cond-> right?

I'm not bothered by doing it this way at all, though.

**Review by adam-james-v — APPROVED** [review]
Looks good!
I like the 🦜 emojis in the test :)

File: src/metabase/models/params/custom_values.clj (hunk 1 above)
Comment (markbastian) [reply src/metabase/models/params/custom_values.clj:64]: Not sure, but this feels a little safer.
