### PR TITLE
Relax concat args to allow any ExpressionArg

### LINKED ISSUE #39439: Not possible to add nested custom expression
### Describe the bug

https://stats.metabase.com/question/16385-invoices-mbql-bug-2/notebook
I've added custom column QS2 defined by expression expression `concat(year([Date Received]), " Q", quarter([Date Received]))`.
It causes error `Invalid query: {:query {:expressions {"QS2" [nil ["valid instance of one of these MBQL clauses: :expression, :field"]]}}}`
Having separate custom columns year([Date Received] and quarter([Date Received]) I can create a custom column with equivalent definition `concat("Q", [Quarter], " ", [Year])` and it works fine.
Captura de ecrã 2024-03-01, às 06 33 41
Captura de ecrã 2024-03-01, às 06 33 28

### To Reproduce

1. Start new GUI question in stats.metabase.com
2. Choose Invoices dataset from Sample Database
3. Add custom column `concat(year([Date Received]), " Q", quarter([Date Received]))`
4. Click Visualize
5. Error will be shown

### Expected behavior

The expression should be parsed normally

### Logs

Invalid query: {:query {:expressions {"QS2" [nil ["valid instance of one of these MBQL clauses: :expression, :field"]]}}}

### Information about your Metabase installation

```JSON
stats.metabase.com
```

### Severity

Blocks some (rare) use cases

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by appleby**
Closes #39439

### Description

Relax the arg types to `ExpressionArg` for `:concat` expressions since many DBs allow to concatenate non-string types. This also aligns with the corresponding MLv2 schema and with the [reference docs](https://www.metabase.com/docs/latest/questions/query-builder/expressions/concat.html#accepted-data-types).

MLv2 schema:
```clojure
(mbql-clause/define-catn-mbql-clause :concat :- :type/Text
  [:args [:repeat {:min 2} [:schema [:ref ::expression/expression]]]])
```

### How to verify

Follow repro steps in linked issue, or see tests added.

### Demo

Screenshot 2024-10-08 at 4 03 49 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/query_processor_test/string_extracts_test.clj [hunk 1]
```diff
@@ -70,9 +71,30 @@
...
-      (is (= "foobar" (test-string-extract [:concat "f" "o" "o" "b" "a" "r"]))))))
+      (is (= "foobar" (test-string-extract [:concat "f" "o" "o" "b" "a" "r"]))))
+    (testing "Does concat work with nested concat expressions"
+      (is (= "foobar" (test-string-extract [:concat [:concat "f" "o" "o"] [:concat "b" "a" "r"]]))))))
+
+(defmethod driver/database-supports? [::driver/driver ::concat-non-string-args]
+  [_driver _feature _database]
+  true)
+
+;; These drivers do not support concat with non-string args
```
Comment (appleby) [inline test/metabase/query_processor_test/string_extracts_test.clj:85]: Is this the right way to exclude these drivers from this test? Ad-hoc, file-local features like this seem to be the most common idiom in our tests, but occasionally we add a key like `:test/dynamic-dataset-loading` or `:test/jvm-timezone-setting` to `metabase.driver.features`. And then some features are a middle ground between the two, like `:test/timestamptz-type` or `:test/time-type` which are `:test`-prefixed and implemented in a common place (`metabase.test.data.interface`), but not added to `metabase.driver.features`.

Pinging @lbrdnk as I seem to recall seeing a comment from him related to this topic in a gh review somewhere, but can't find it now...

Comment (lbrdnk) [reply test/metabase/query_processor_test/string_extracts_test.clj:85]: I believe you mean [this](https://github.com/metabase/metabase/pull/41384#issuecomment-2289243742) reply from Cam to my review or the original comment.

Based on that, the general features go into the `metabase.driver/features` and ad-hoc, ie. disabling just one test, should live right next to it.

With regards to namespacing, I used `:test/...` in the `dynamic-dataset-loading` to make it clear that this is related _only_ to our tests.

I think we are still in the process of finding the universal approach. Current model is fine, but as we define more and more test features it may become hard to find the real features among those. Either the product features or dbms quirks vs features defined just for the purposes of disabling some test/s.

That said, in this situation, I'd define the feat in the general namespace. But also I'm not saying it is the only right answer :)

Comment (appleby) [reply test/metabase/query_processor_test/string_extracts_test.clj:85]: That's the comment I was remembering, thanks! Really good comment btw, all good callouts.

> That said, in this situation, I'd define the feat in the general namespace

To clarify, you mean naming the feature `:test/concat-non-string-args` but not adding it to `driver/features` right? Similar to, e.g. `:test/time-type`?

Personally, I think I lean towards leaving it ad-hoc since it's used in a single test and namespace, but could be convinced otherwise. Wdyt?

Comment (lbrdnk) [reply test/metabase/query_processor_test/string_extracts_test.clj:85]: > Personally, I think I lean towards leaving it ad-hoc since it's used in a single test and namespace...

You are right. I've edited my comment realizing that's the case. I think it is fine the way it is.

**Review by lbrdnk — APPROVED** [review]
LGTM.
