### PR TITLE
Fix oom during sync field values

### LINKED ISSUE #46411: OOM errors during sync field values
During fingerprint, we set `metabase_field.has_field_values = auto-list` for fields that have less than 1K distinct values.
Then during `update-field-values` step, we'll fetch the distinct values for these fields and insert into FieldValues table. 

The problem here is that for text fields, we don't know how long each text entry are and it's possible that it's so big that fetching 1K rows like this will blow up memory. Even though we already have a guard to not save field values if the total char length exceed `metabase.models.field-values/*total-max-length*` but this is done in clojure land, which requires fetching all rows into memory.

We should optimize this so that we cut off the field values so that it does not exceed `metabase.models.field-values/*total-max-length*` char length during query execution.

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/46411 by reworking the `field-distinct-values` function so that it stops getting rows from jdbc if the total char of all rows exceeds the char limit.

### How to test:
1. Create a db with this script

```sql
CREATE TABLE example_table (id SERIAL PRIMARY KEY,
                            content TEXT);

INSERT INTO example_table (content)
SELECT
    substr(
        -- Generate a long random string
        repeat(
            md5(random()::text) ||
            md5(random()::text) ||
            md5(random()::text) ||
            md5(random()::text) ||
            md5(random()::text) ||
            md5(random()::text) ||
            md5(random()::text) ||
            md5(random()::text) ||
            md5(random()::text) ||
            md5(random()::text) ||
            md5(random()::text),
            90909  -- Number of repetitions to exceed 1,000,000 characters
        ),
        1,
        200000
    )
FROM generate_series(1, 999);
```
2. Start MB with a max heap size of 512mb
3. Sync the DB should succeed

### CODE REVIEW

File: src/metabase/models/params/chain_filter.clj [hunk 1]
```diff
@@ -439,6 +439,8 @@
     (log/debugf "Chain filter MBQL query:\n%s" (u/pprint-to-str 'magenta mbql-query))
     (try
       (let [query-limit (get-in mbql-query [:query :limit])
+            ;; FIXME: this can OOM for text column if each value are too large. See #46411
```
Comment (qnkhuat) [inline src/metabase/models/params/chain_filter.clj:442]: there will be a follow-up for this

File: src/metabase/models/field_values.clj [hunk 2]
```diff
@@ -321,35 +341,72 @@
 ;;; |                                                    CRUD fns                                                    |
 ;;; +----------------------------------------------------------------------------------------------------------------+
 
+(defn- distinct-text-field-rff
```
Comment (calherries) [inline src/metabase/models/field_values.clj:344]: it might be nice to add a schema to this, to make the coupling to the QP explicit. then if the QP's `rff` type changes we'll get a schema error:
```suggestion
(mu/defn- distinct-text-field-rff :- ::qp.schema/rff
```

File: src/metabase/models/field_values.clj [hunk 3]
```diff
@@ -321,35 +341,72 @@
...
 
   (This function provides the values that normally get saved as a Field's
   FieldValues. You most likely should not be using this directly in code outside of this namespace, unless it's for a
   very specific reason, such as certain cases where we fetch ad-hoc FieldValues for GTAP-filtered Fields.)"
   [field]
   (try
-    (let [distinct-values         (metadata-queries/field-distinct-values field)
-          limited-distinct-values (take-by-length *total-max-length* distinct-values)]
-      {:values          limited-distinct-values
+    (let [rff             (if (isa? (:base_type field) :type/Text)
```
Comment (calherries) [inline src/metabase/models/field_values.clj:392]: Why is this only applied to `:type/Text` fields? `take-by-length` applied to all types and just assumed that all values had a `.toString()` method.

Comment (calherries) [reply src/metabase/models/field_values.clj:392]: for reference, the source of `take-by-length`:
https://github.com/metabase/metabase/blob/49654444c9ae810e31f85a94e1f38538307d92fe/src/metabase/models/field_values.clj#L260-L279

Comment (qnkhuat) [reply src/metabase/models/field_values.clj:392]: I wasn't sure it's useful for other types, but I guess you're right.

Comment (qnkhuat) [reply src/metabase/models/field_values.clj:392]: Do you think it's useful for types other than text? I can see float number being extra long but it's unlikely

File: src/metabase/db/metadata_queries.clj [hunk 4]
```diff
@@ -66,48 +54,23 @@
...
+   {:pre [(integer? table-id)]}
+   (binding [qp.i/*disable-qp-logging* true]
+     (qp/process-query
+      {:type       :query
+       :database   (t2/select-one-fn :db_id :model/Table table-id)
+       :query      (-> mbql-query
+                       (assoc :source-table table-id)
+                       add-required-filters-if-needed)
+       :middleware {:disable-remaps? true}}
+      rff))))
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/db/metadata_queries.clj:73]: yea because in `distinct-values` we want to read `::reached-char-len-limit` from the qp result.

File: src/metabase/models/field_values.clj [hunk 5]
```diff
@@ -321,35 +341,72 @@
...
+            (assoc-in [:data :rows] (persistent! @rows))))
+
+       ([result row]
+        (assert (= 1 (count row)))
+        (vswap! total-char + (count (first row)))
+        (if (> @total-char max-char-len)
+          (reduced (assoc result ::reached-char-len-limit true))
+          (do
+           (offer-row row)
+           result)))))))
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/models/field_values.clj:376]: this is so much better! Composition ftw!

File: src/metabase/db/metadata_queries.clj [hunk 6]
```diff
@@ -66,48 +54,23 @@
...
 
 ;; I'm not sure whether this field-distinct-values and field-distinct-values belong to this namespace
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/db/metadata_queries.clj:75]: removed

File: src/metabase/models/field_values.clj (hunk 2 above)
Comment (qnkhuat) [reply src/metabase/models/field_values.clj]: added the schema here 4e6f6e6de4

File: src/metabase/models/field_values.clj (hunk 3 above)
Comment (calherries) [reply src/metabase/models/field_values.clj]: it's a good question. doing this for other types is probably not useful right now. on the other hand there could be other types in the future that are long that aren't `:type/Text` and are `:type/TextLike` or something. doing this on every value is rather cheap though, since we are converting to strings anyway

File: src/metabase/db/metadata_queries.clj (hunk 4 above)
[the remark this answers is not in the document]
Comment (calherries) [reply src/metabase/db/metadata_queries.clj:73]: right, makes sense.

File: src/metabase/models/field_values.clj [hunk 7]
```diff
@@ -335,21 +376,20 @@
...
-                          ;; with limit = [[metabase.db.metadata-queries/absolute-max-distinct-values-limit]].
-                          ;; So, if the returned `distinct-values` has length equal to that exact limit,
-                          ;; we assume the returned values is just a subset of what we have in DB.
-                          (= (count distinct-values)
-                             metadata-queries/absolute-max-distinct-values-limit))})
+       :has_more_values (or (true? (::reached-char-len-limit result))
+                            ;; [[field-distinct-values]] runs a query
+                            ;; with limit = [[*absolute-max-distinct-values-limit*]].
+                            ;; So, if the returned `distinct-values` has length equal to that exact limit,
+                            ;; we assume the returned values is just a subset of what we have in DB.
```
Comment (calherries) [inline src/metabase/models/field_values.clj:390]: this is out-of-date. maybe something like this?
```suggestion
                            ;; `distinct-values` is from a query 
                            ;; with limit = [[*absolute-max-distinct-values-limit*]].
                            ;; So, if the returned `distinct-values` has length equal to that exact limit,
                            ;; we assume the returned values is just a subset of what we have in DB.
```

**Review by calherries — APPROVED** [review]
Nice

File: src/metabase/models/field_values.clj (hunk 3 above)
Comment (qnkhuat) [reply src/metabase/models/field_values.clj]: make sense, did it in [4e6f6e6](https://github.com/metabase/metabase/pull/46524/commits/4e6f6e6de480a6328af8a7d60f035d65ce8ba3c5)

**Comment by qnkhuat** [comment]
@metabase-bot backport release-x.49.x
