### PR TITLE
pass lat and lon fields to the tile endpoints as query params

### LINKED ISSUE #63465: Map Pins are Repeated Across the Map Grid when using SQL Question as Data Source
### Describe the bug

If you use a SQL query as the source for a pin map things get weird:

Image

### To Reproduce

1. From sample DB convert the People table to SQL question
2. Use it as the source for a pin map

### Expected behavior

Pins shouldn't be replicated.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "starter",
    "version": {
      "date": "2025-08-26",
      "tag": "v1.55.14",
      "hash": "53044c2"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Annoying

### Additional context

My eyes. They burn.

### PR DESCRIPTION
**Pull request by alxnddr**
closes #63465
### Description

Passes latitude and longitude field refs as query parameters instead of path segments to solve https://github.com/metabase/metabase/issues/63465. Field refs may include hyphens and slashes so when they are passed as segments it [does not work as expected](https://metaboat.slack.com/archives/C0645JP1W81/p1758302870533529?thread_ts=1758302252.665629&cid=C0645JP1W81) with Jetty.

### How to verify

- Create a native query `select * from people`
- Render it as a pin map
- Ensure it shows correct pin map

### Demo

Before
Screenshot 2025-09-15 at 8 50 57 PM

After
Screenshot 2025-09-15 at 8 51 04 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by deniskaber — APPROVED** [review]
I checked only FE code

**Review by iethree — APPROVED** [review]
frontend looks good!

**Review by ranquild — COMMENTED** [review]
I'd like to get answers in the thread first https://metaboat.slack.com/archives/C0645JP1W81/p1758302252665629

File: src/metabase/tiles/api.clj [hunk 1]
```diff
@@ -260,34 +251,40 @@
...
+       [:zoom ms/Int]
+       [:x ms/Int]
+       [:y ms/Int]]
+   {:keys [parameters latField lonField]}
+   :- [:map
+       [:parameters {:optional true} ms/JSONString]
+       [:latField string?]
+       [:lonField string?]]]
+  (let [parameters (when parameters (json/decode+kw parameters))
+        lat-field  (json/decode+kw latField)
```
Comment (johnswanson) [inline src/metabase/tiles/api.clj:268]: Not your bug, but this will 500 on malformed JSON and we should probably 400 instead... fine for now though.

File: src/metabase/util/field_ref.cljc [hunk 2]
```diff
@@ -0,0 +1,36 @@
+(ns metabase.util.field-ref
+  "Utilities for encoding and decoding field refs for URL usage."
+  (:require
+   #?(:clj [metabase.util.json :as json])
+   [clojure.string :as str]
+   [metabase.util.malli :as mu])
+  #?(:cljs (:require [goog.crypt.base64 :as base64])))
+
+(mu/defn encode-field-ref-for-url :- :string
```
Comment (johnswanson) [inline src/metabase/util/field_ref.cljc]: Is this used somewhere and I'm just missing it?

**Review by johnswanson — APPROVED** [review]
LGTM, minor comment and noticed one existing issue that you don't need to fix.

File: src/metabase/util/field_ref.cljc (hunk 2 above)
Comment (alxnddr) [reply src/metabase/util/field_ref.cljc]: Good catch, I'll remote these
