### PR TITLE
Fix dashboard menu closing when clicking outside

### LINKED ISSUE #3338: Dashboard dropdown menu should close when you click outside of it
Right now it's remaining open unless you click the menu button again, even if you navigate elsewhere, which is crazy annoying. It should behave like the Account Settings/Logout menu.

screen shot 2016-09-09 at 12 42 37 pm

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3338

### CODE REVIEW

File: frontend/src/metabase/nav/components/ProfileLink.jsx [hunk 1]
```diff
@@ -62,18 +62,18 @@ export default class ProfileLink extends Component {
...
+                        <div className="flex align-center">
+                            <UserAvatar user={user} style={{backgroundColor: 'transparent'}}/>
+                            <Icon name="chevrondown" className="Dropdown-chevron ml1" size={8} />
                         </div>
-                    </a>
+                    </div>
+                </a>
 
-                    { dropdownOpen ?
+                { dropdownOpen ?
```
Comment (kdoh) [inline frontend/src/metabase/nav/components/ProfileLink.jsx]: This is more of a question than a suggestion but would it make sense to use the ` someBool && <youJSXHere>` pattern in this instance rather than doing the ternary with a null? I know we do both but I'm curious if we prefer one over the other and if this might be an instance to start solidifying.

File: frontend/src/metabase/nav/components/ProfileLink.jsx [hunk 2]
```diff
@@ -129,42 +129,42 @@ export default class ProfileLink extends Component {
...
-                                    }
-                                </div>
+                    </OnClickOutsideWrapper>
+                : null }
+
+                { modalOpen === "about" ?
+                    <Modal className="Modal Modal--small" onClose={this.closeModal}>
+                        <div className="px4 pt4 pb2 text-centered relative">
+                            <span className="absolute top right p4 text-normal text-grey-3 cursor-pointer" onClick={this.closeModal}>
+                                <Icon name={'close'} size={16} />
```
Comment (kdoh) [inline frontend/src/metabase/nav/components/ProfileLink.jsx]: This is small, but any reason this is an expression versus just a prop string?

File: frontend/src/metabase/nav/components/ProfileLink.jsx (hunk 1 above)
Comment (tlrobinson) [inline frontend/src/metabase/nav/components/ProfileLink.jsx]: It's basically a style preference, but I think there are a couple minor advantages to using ternary:

1. The order of operations of ternary vs boolean operators sometimes lets you leave off parenthesis, e.x. `a || b && <div />` could incorrectly evaluate to `a`, so you have to do `(a || b) && <div />`, but  `a || b ? <div /> : null` is fine. Of course the lack of parenthesis are offset by the addition of `: null`, but at least the logic won't be wrong.
2. If you decide you want to add an `else` you don't need to change the top part.
3. Consistency (except we're not consistent)

File: frontend/src/metabase/nav/components/ProfileLink.jsx (hunk 2 above)
Comment (tlrobinson) [inline frontend/src/metabase/nav/components/ProfileLink.jsx]: No reason. I didn't change any of this code, just the indentation.

**Comment by kdoh** [comment]
👍
