### PR TITLE
Fix scalar error when rendering null

### LINKED ISSUE #13801: When visualization returns `null` (No results), then UI becomes broken
If a question return 0, stuck spinning and all nexts question in same dashboard too.
From console all request to card there result correct (all request response 200  and content if exists).
No associate JS errors shows in console.

To Reproduce:
1. Create a Dashboard
2. Put 3 questions. First one response non zero value ie: 5, the next question response 0. the next question (top to bottom, left to right) return non zero ie: 6.
3. Shows first question ok, next spinning stuck, next spinning stuck.

1. First question return 5
2. Second question return 0
3 Third question return 6

Selección_551

{
  "browser-info": {
    "language": "es-ES",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "4.14.181-108.257.amzn1.x86_64",
    "user.language": "es",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.32-0ubuntu0.18.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.37.2-SNAPSHOT",
      "date": "2020-11-12",
      "branch": "?",
      "hash": "ba57ab6"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

Severity
Is Blocking

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #13801 

This PR fixes the direct cause of the crash and makes the QB error display work better. I poked at fixing the core issue with Visualizations globally, but I didn't see why the error boundary wasn't triggering.

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/Scalar.jsx [hunk 1]
```diff
@@ -206,7 +206,8 @@ export default class Scalar extends Component {
     // use the compact version of formatting if the component is narrower than
     // the cutoff and the formatted value is longer than the cutoff
     const displayCompact =
```
Comment (ariya) [inline frontend/src/metabase/visualizations/visualizations/Scalar.jsx:208]: Should we add a special guard for `null`? Since `fulllScalarValue` (and also `compactScalarValue`) is either `null` or a string, the whole conditional with `displayCompact` is kind of redundant.

Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/visualizations/Scalar.jsx:208]: Yeah good call. It's better to be explicit.

I considered updating our formatting code to always return a string ("" for null), but that feels like a more dangerous change.

**Comment by nemanjaglumac** [comment]
@paulrosenzweig do you want to merge this asap and I'll add repro on top of it or would you rather wait for a Cypress repro?

**Comment by paulrosenzweig** [comment]
@nemanjaglumac I don't think we should wait on a Cypress repo, but feel free to push it here if you have it ready before this is merged.

**Comment by nemanjaglumac** [comment]
I don't have it ready yet. Go ahead and merge it, please.

**Review by robdaemon — APPROVED** [review]
