### PR TITLE
Handle mismatching date parameters in dashboard -> native question drills

### LINKED ISSUE #34129: Date filters - inconsistent filter values displayed when a question is opened from a filtered dashboard
### Describe the bug

Opening a filtered question from a dashboard will display an inconsistent or confusing date value if the filter widget type of the question is different from the widget type of the dashboard.

### To Reproduce

1. Create a SQL question on the sample database: 
```select min(CREATED_AT), max(CREATED_AT), count(*) from ORDERS where {{ time }}```
Set the variable type: field filter, map to: `ORDERS.CREATED_AT`, filter widget type: _Month and year_.
2. Add the question to a dashboard.
3. Create a dashboard filter _time_, filter type: _Relative date_. Link it to the question.
4. On the dashboard, the filter works properly.
5. Now set a filter on the dashboard, and click on the card to open the question. Note that the card will still show the correct values, but the year and month filter box on the question will show some invalid or unexpected date (e.g. it shows January 0001 for _Last Year_, or an empty value for _This Month_).

### Expected behavior

Seeing an invalid or unrelated date is confusing for the user. The effective filter value should be shown, even if the filter widget type does not support setting that in the first place. 

### Logs

n/a

### Information about your Metabase installation
`1.47.2`

### Severity

This has been reported by a customer. More than a cosmetic issue as it results in confusing information being displayed.

### Additional context

Filtering on _Last Month_ ...
image
results in an inconsistent date when the question is opened:
image

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/34129

How to verify:
- Follow the steps from the issue or run the new cypress test
- Try all dashboard time widget types with different native date parameter widget types. 

Screenshot 2023-10-02 at 12 11 52

### CODE REVIEW

File: frontend/src/metabase/parameters/utils/date-formatting.ts [hunk 1]
```diff
@@ -111,52 +114,68 @@ function getFilterTitle(filter: any[]) {
...
   }
   const filter = dateParameterValueToMBQL(urlEncoded, noopRef);
-
   return filter ? getFilterTitle(filter) : null;
 }
 
 function parseDateRangeValue(value: string) {
   const [start, end] = (value || "").split(RANGE_SEPARATOR);
-  return { start, end };
+  return { start: moment(start, true), end: moment(end, true) };
```
Comment (ranquild) [inline frontend/src/metabase/parameters/utils/date-formatting.ts:127]: Had to enable strict parsing (`true` argument) everywhere, otherwise `past1days` gets parsed as `yyyy-MM` (as year 1) etc

File: frontend/src/metabase/query_builder/actions/core/initializeQB.ts [hunk 2]
```diff
@@ -114,9 +114,7 @@ async function fetchAndPrepareSavedQuestionCards(
 
   // for showing the "started from" lineage correctly when adding filters/breakouts and when going back and forth
   // in browser history, the original_card_id has to be set for the current card (simply the id of card itself for now)
-  card.original_card_id = card.id;
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/actions/core/initializeQB.ts:117]: `card` is immutable (frozen) and modifying it throws an exception

File: frontend/src/metabase/parameters/utils/date-formatting.ts [hunk 3]
```diff
@@ -111,52 +114,68 @@ function getFilterTitle(filter: any[]) {
...
+}
+
+export function formatDateValue(
+  value: string,
+  parameter: UiParameter,
+): string | null {
+  // the value can be from a mismatching parameter, so we need to test every date parameter type
+  const types = [
+    parameter.type,
+    ...PARAMETER_OPERATOR_TYPES.date.map(({ type }) => type),
```
Comment (kamilmielnik) [inline frontend/src/metabase/parameters/utils/date-formatting.ts:165]: We should pay attention to the order in `PARAMETER_OPERATOR_TYPES` array.
I think `date/range` should be before `date/single`, otherwise ranges will get treated as single dates.

It'd be great if we had unit tests for `formatDateValue`.

Comment (ranquild) [reply frontend/src/metabase/parameters/utils/date-formatting.ts:165]: With strict parsing the order should matter (unless there is a bug)

Comment (ranquild) [reply frontend/src/metabase/parameters/utils/date-formatting.ts:165]: Tests for these changes are in `formatting.unit.spec.ts`

Comment (ranquild) [reply frontend/src/metabase/parameters/utils/date-formatting.ts:165]: @kamilmielnik added a test for date ranges

**Review by kamilmielnik — APPROVED** [review]
LGTM :+1: 
I checked e2e & unit tests.

**Comment by uladzimirdev** [comment]
I didn't get the idea of why do we need to add `| null` into formatting, is it because of not mapped value?

**Comment by ranquild** [comment]
@uladzimirdev `null` means that the value cannot be formatted using the given parameter type

**Comment by uladzimirdev** [comment]
> @uladzimirdev `null` means that the value cannot be formatted using the given parameter type

got it. In different situation I'd rather rely on typescript to understand if we know this type or not. also I don't see a new test covering this situation. anyhow, this solution works 👍

**Comment by ranquild** [comment]
@uladzimirdev there are tests for this. Otherwise we wouldn't find the correct type
