### PR TITLE
Disable saving models without up-to-date result_metadata

### LINKED ISSUE #37009: Updated native models may lose their result set metadata
### Describe the bug

Upon updating a native model which is based on another model, the result set metadata may be lost.
When this occurs, the query editor won't show available columns for questions that are based on this model.

The workaround is to update the model, and making sure to preview the results before saving it.

### To Reproduce

1. Create native model `model1`:
```
      select 1 as "client_id", 1 as "value"
UNION select 1 as "client_id", 2 as "value"
UNION select 2 as "client_id", 3 as "value"
UNION select 3 as "client_id", 4 as "value"
```
2. Create and save a native model `model2`, which uses `model1` as its source:
```
select * from {{ #nnn-model1 }}
```

3. Update the query definition of model2, and make a minor, non-impactful change, for instance:
```
select cte.* from {{ #nnn-model1 }} as cte
```
, and save it, without previewing the results in the editor.

4. Now start a GUI question based on `model2`. 
5. (!)The columns of the model won't be available in the editor.
image

### Expected behavior

It should wirk

### Logs

Logs:
```
2023-12-20 18:47:06,445 INFO api.dataset :: Source query for this query is Card 77
2023-12-20 18:47:06,455 WARN middleware.add-implicit-clauses :: Warning: cannot determine fields for an explicit `source-query` unless you also include `source-metadata`.
Query: {:params [],
 :native
 "select cte.* from (select 1 as \"client_id\", 1 as \"value\"\nUNION select 1 as \"client_id\", 2 as \"value\"\nUNION select 2 as \"client_id\", 3 as \"value\"\nUNION select 3 as \"client_id\", 4 as \"value\") as cte"}
```

/api/card response for `model2`:
```
{
  "description": null,
  "archived": false,
  "collection_position": 1,
  "table_id": null,
  "result_metadata": null,
  "creator": {
[…]
  },
  "can_write": true,
  "database_id": 1,
  "enable_embedding": false,
  "collection_id": null,
  "query_type": "native",
  "name": "model2",
  "last_query_start": "2023-12-20T18:49:08.371778Z",
  "dashboard_count": 0,
  "persisted": false,
  "average_query_time": 21.0,
  "creator_id": 1,
  "moderation_reviews": [],
  "updated_at": "2023-12-20T18:47:06.210264Z",
  "made_public_by_id": null,
  "embedding_params": null,
  "cache_ttl": null,
  "dataset_query": {
    "type": "native",
    "native": {
      "query": "select cte.* from {{ #76-model1 }} as cte",
      "template-tags": {
        "#76-model1": {
          "type": "card",
          "name": "#76-model1",
          "id": "56149603-5eb3-4829-84a3-1afb2774f8ff",
          "card-id": 76,
          "display-name": "#76 Model1"
        }
      }
    },
    "database": 1
  },
  "id": 77,
  "parameter_mappings": [],
  "display": "table",
  "entity_id": "srrDqNwZugt2Ip3tYamZH",
  "collection_preview": true,
  "last-edit-info": {
[…]
  },
  "visualization_settings": {
    "table.pivot_column": "client_id",
    "table.cell_column": "value"
  },
  "collection": {
    "metabase.models.collection.root/is-root?": true,
    "authority_level": null,
    "name": "Our analytics",
    "is_personal": false,
    "id": "root",
    "can_write": true
  },
  "metabase_version": "v1.48.1 (a8302d4)",
  "parameters": [],
  "dataset": true,
  "created_at": "2023-12-20T18:45:50.916686",
  "parameter_usage_count": 0,
  "public_uuid": null
}```

### Information about your Metabase installation

```JSON
1.48.0, 1.47.9
```

### Severity

Found this while troubleshooting for a customer. A simple workaround exists.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/37009

Disables creating new and updating existing models without `result_metadata`. That means that if the query was changed, the user would have to run the query first and wait for results.

How to verify:
- New -> Modal -> Native
- SELECT * FROM PRODUCTS
- Try to save the model without running the query. The button should be disabled and there should be a tooltip.
- Run the query
- Now the save button should become enabled
- Save the model
- ... menu -> Edit query definition
- Try changing the model query. The button should become disabled
- Run the updated query. The button should become enabled

Screenshot 2024-03-15 at 16 23 04

### CODE REVIEW

File: frontend/src/metabase/entities/tables.js [hunk 1]
```diff
@@ -82,13 +81,6 @@ const Tables = createEntity({
     // loads `query_metadata` for a single table
     fetchMetadata: compose(
       withAction(FETCH_METADATA),
-      withForceReload((state, { id }) => {
```
Comment (ranquild) [inline frontend/src/metabase/entities/tables.js:85]: This hack is no longer needed

**Review by luizarakaki — APPROVED** [review]
lgtm

File: frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx [hunk 2]
```diff
@@ -464,20 +489,17 @@ function DatasetEditor(props) {
...
-            activeText={t`Saving…`}
-            failedText={t`Save failed`}
-            successText={t`Saved`}
-            className={cx(
-              ButtonsS.Button,
-              ButtonsS.ButtonPrimary,
-              ButtonsS.ButtonSmall,
-            )}
-          />,
+          saveButtonTooltipLabel ? (
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx:492]: Instead of conditionally rendering the `Tooltip` we could pass `disabled={!saveButtonTooltipLabel}` prop to it.
This way we could inline the `ActionButton` back here and remove `key` prop from it.

File: frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx [hunk 3]
```diff
@@ -413,18 +418,21 @@ function DatasetEditor(props) {
...
-    return everyFieldHasDisplayName && isDirty;
-  }, [dataset, fields, isDirty]);
+  const canSaveChanges =
+    !isEmpty &&
+    isDirty &&
+    (!isNative || !isResultDirty) &&
+    fields.every(field => field.display_name);
+
+  const saveButtonTooltipLabel =
+    !isEmpty && isDirty && isNative && isResultDirty
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx:433]: Why only native models?

File: frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx (hunk 2 above)
Comment (ranquild) [reply frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx]: Didn't about about `disabled`, thanks!

File: frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx (hunk 3 above)
Comment (ranquild) [reply frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx:433]: Because for MBQL queries `result_metadata` can be computed by the BE without running the query

**Review by kamilmielnik — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx [hunk 4]
```diff
@@ -464,20 +472,27 @@ function DatasetEditor(props) {
...
-              ButtonsS.ButtonPrimary,
-              ButtonsS.ButtonSmall,
-            )}
-          />,
+            refProp="innerRef"
+            label={saveButtonTooltipLabel}
+            disabled={!saveButtonTooltipLabel}
+          >
+            <ActionButton
+              key="save"
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx:482]: Redundant
