### PR TITLE
Closes VIZ-1034: can't click through to source question for cards with an empty title

### LINKED ISSUE #58414: [Bug Report] Can't click through to source question if you remove the titles from visualizer dashcards
### Description
I removed the titles from these cards as I didn't like they way they looked and the purpose of this dash is to use the cards for slides for the board.  And now I can't edit them, because there is no title to click through and Edit Visualization is the only option.  I was lucky these questions are saved in a folder and not the dash, so I could go find them to edit them.  https://stats.metabase.com/dashboard/2391-success-engineering-summary-board-version-v2?date_filter=2025-01-01~2025-03-31&tab=954-slide-3

### Links
- Slack File: https://metaboat.slack.com/files/U02T6V8MXN2/F08TKRGHN21/diagnostic-info.json

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #58414
Closes [VIZ-1034: \[Bug Report\] Can't click through to source question if you remove the titles from visualizer dashcards](https://linear.app/metabase/issue/VIZ-1034/bug-report-cant-click-through-to-source-question-if-you-remove-the)

### Description

In cards with an empty title, the related questions can be reached through the dash card menu:
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx [hunk 1]
```diff
@@ -351,6 +397,10 @@ export function DashCardVisualization({
       );
     }
 
+    // We only show the titleMenuItems if the card has no title.
+    const settings = getComputedSettingsForSeries(series) as any;
+    const title = settings["card.title"] ?? series?.[0].card.name ?? "";
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx:402]: Can we use the `ComputedVisualizationSettings` type from `"metabase/visualizations/types"` here?

**Review by kulyk — APPROVED** [review]
