### PR TITLE
Show email/password login errors when SSO is active

### LINKED ISSUE #16122: Normal login errors are not surfaced if SSO is also active
**Describe the bug**
If Google sign-in is configured, and a user tries to login with incorrect credentials, no error is shown. Instead, the user is brought back to the page with the "Sign in with Google" button.  

**To Reproduce**
1. Enable Google sign-in by entering any value into the "Client ID" field in the admin page
3. Log out
4. Click "sign in with email"
5. Try to log in with invalid credentials

**Expected Behavior**
Email login form should behave the same regardless of whether Google sign-in is active

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #16122 

## How to Test

1. Go to Admin
2. On left menu, click `Authentication`
3. In section titled `Sign in with Google`, click `Configure`
4. Add any string to `Client ID` input
5. Click `Save Changes`
6. Sign Out of Metabase
7. Click on `Sign in with email`
8. Add a correct email but wrong password, or other login mistakes
9. Click `Sign in`

### After

Form shows error messages.

### Before

Page showed Google authentication button

### CODE REVIEW

File: frontend/src/metabase/app-main.js [hunk 1]
```diff
@@ -24,6 +24,15 @@ init(reducers, getRoutes, store => {
     if (url.indexOf("/api/user/current") >= 0) {
       return;
     }
+
+    // If SSO is enabled, page url for login with email and password
+    // is `/auth/login/password` instead of `/auth/login`.
+    // So if call to api when signing in fails, let’s stay in the current page.
+    // Otherwise it will always redirect us to the Google auth interaction.
+    if (url === "/api/session") {
```
Comment (daltojohnso) [inline frontend/src/metabase/app-main.js:32]: let's use `url.includes("/api/session")` or similar like the above check on `/api/user/current` so that this doesn't fail on `/api/session/` (note the last char `/`)

**Review by daltojohnso — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/app-main.js (hunk 1 above)
Comment (gusaiani) [reply frontend/src/metabase/app-main.js]: @daltojohnso, thanks.

We have a few variations of `/api/session/…` calls:

https://github.com/metabase/metabase/blob/a04d0cc21050bf66bf92f873bae586d5e6dc5855/frontend/src/metabase/services.js#L355-L363

I'd be concerned that checking for an `include` would be too encompassing. And without test coverage we might shoot our feet.

Updated with `_.contains` to check for either variation.
Wdyt?

Comment (ariya) [reply frontend/src/metabase/app-main.js]: Also, watch for a potential security issue: https://codeql.github.com/codeql-query-help/javascript/js-incomplete-url-substring-sanitization/

Comment (daltojohnso) [reply frontend/src/metabase/app-main.js]: that works for me. since this piece of code is to prevent a redirect I think this code is fine, unless I am mistaken

**Review by daltojohnso — APPROVED** [review]
