### PR TITLE
Notify endpoint should 404 with incorrect table name/id (#25627)

### LINKED ISSUE #25627: Notify endpoint will always return 200 even if the tables don't exist
**Describe the bug**
If you call the notify endpoint with id's or names that don't exist in the payload, the endpoint will return 200 and {"success": true}.
We should be consistent with the error codes and the responses

**Logs**
NA

**To Reproduce**
1) Call the notify endpoint with non-existent id's or names, see it responding ok all the time. It won't do anything

**Expected behavior**
If the table does not exist, we should respond a 500 and the corresponding error message in the payload

**Screenshots**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.44.3
- Metabase hosting environment: Docker

**Severity**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by tsmacdonald**
Fixes #25627; previously a missing table would silently fail (and return a 200).

### CODE REVIEW

File: test/metabase/api/notify_test.clj [hunk 1]
```diff
@@ -19,17 +19,39 @@
...
+      (testing "table name must exist or we get a 404"
+        (is (= {:status 404
+                :body   "Not found."}
+               (try (http/post (client/build-url (format "notify/db/%d" (:id (mt/db))) {})
+                               (merge {:accept       :json
+                                       :content-type :json
+                                       :form-params  {:table_name "IncorrectToucanFact"}}
+                                      api-headers))
+                    (catch clojure.lang.ExceptionInfo e
+                      (select-keys (ex-data e) [:status :body])))))))))
```
Comment (tsmacdonald) [inline test/metabase/api/notify_test.clj:54]: Not the DRYest testing, but I don't like to get too cute with function extraction in test.

File: test/metabase/api/notify_test.clj [hunk 2]
```diff
@@ -38,11 +60,10 @@
             post       (fn post-api
                          ([payload] (post-api payload 200))
                          ([payload expected-code]
-                          (mt/client :post expected-code (format "notify/db/%d" (u/the-id (mt/db)))
-                                     {:request-options
-                                      {:headers {"X-METABASE-APIKEY" "test-api-key"
-                                                 "Content-Type"      "application/json"}}}
-                                     payload)))]
+                          (mt/with-temporary-setting-values [api-key "test-api-key"]
```
Comment (tsmacdonald) [inline test/metabase/api/notify_test.clj:63]: This (and the one above) lets the test work correctly when run from the REPL. See [Cam's comment here](https://metaboat.slack.com/archives/CKZEMT1MJ/p1664300567452529?thread_ts=1664294388.338909&cid=CKZEMT1MJ)

**Review by noahmoss — APPROVED** [review]
lgtm!
