### PR TITLE
Closes EMB-853 renamed legends get ignored by translation

### LINKED ISSUE #63972: Renamed legends get ignored by Content Translation
### Describe the bug

https://github.com/user-attachments/assets/9792e0b3-260e-495b-b281-9670a429d635

Renamed legends get ignored by Content Translation 

### To Reproduce

1. Go to New Dashboard -> Add a new Question -> Products -> Count Group by Category -> Visualize as Pie ->  Rename the Widget legend to Price -> Save

Image

2. Upload the following translations [metabase-content-translations.csv](https://github.com/user-attachments/files/22516224/metabase-content-translations.csv)

3.Embed with locale=es and notice how your renaming gets ignored, what makes it more weird is that in this case it seems Widget is still being used cause it translated `Widget` not `Price`

Image

### Expected behavior

The translations should be based on what you see in the UI this is the same bug as this one but instead of columns I am renaming legends:

https://github.com/metabase/metabase/issues/63296

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.56
```

### Severity

A feature which we released and is partially broken

### Additional context

There has been an ongoing of bugs around Content Translation and customers still face issues:

https://github.com/metabase/metabase/issues?q=is%3Aissue%20content%20translation%20label%3APriority%3AP1

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #63972
Closes [EMB-853: Renamed legends get ignored by Content Translation](https://linear.app/metabase/issue/EMB-853/renamed-legends-get-ignored-by-content-translation)

### Description

Consider special case of `pie.rows` when translating datasets

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts [hunk 1]
```diff
@@ -133,9 +134,34 @@ export const translateFieldValuesInSeries = (
     }
     const untranslatedRows = singleSeries.data.rows.concat();
 
-    const translatedRows = singleSeries.data.rows.map((row) =>
-      row.map((value) => tc(value)),
-    );
+    let translatedRows: RowValue[][];
+
+    if (singleSeries.card?.display === "pie") {
+      const pieRows = singleSeries.card.visualization_settings?.["pie.rows"];
```
Comment (heypoom) [inline enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts]: nit: I prefer `Object.fromEntries` for these things, makes the intent a little clearer, and maybe a bit more concise.

```suggestion
      const pieRows = singleSeries.card.visualization_settings?.["pie.rows"] ?? [];
      const keyToNameMap = Object.fromEntries(
        pieRows.map(row => [row.key, row.name])
      );
```

File: enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts [hunk 2]
```diff
@@ -133,9 +134,34 @@ export const translateFieldValuesInSeries = (
...
+              return acc;
+            },
+            {} as Record<string, string>,
+          )
+        : {};
+
+      translatedRows = singleSeries.data.rows.map((row) =>
+        row.map((value) => {
+          if (typeof value === "string" && keyToNameMap[value] !== undefined) {
+            return tc(keyToNameMap[value]);
```
Comment (heypoom) [inline enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts]: Would the row value be a translation key in this case? I think a little comment would be nice, since I didn't fully get why the row value became a translation key.

**Review by heypoom — APPROVED** [review]
Translation logic and the unit test cases looks correct to me

File: enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts [hunk 3]
```diff
@@ -133,9 +134,38 @@ export const translateFieldValuesInSeries = (
     }
     const untranslatedRows = singleSeries.data.rows.concat();
 
-    const translatedRows = singleSeries.data.rows.map((row) =>
-      row.map((value) => tc(value)),
-    );
+    let translatedRows: RowValue[][];
+
+    if (singleSeries.card?.display === "pie") {
```
Comment (WiNloSt) [inline enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts]: can we use `ts-pattern` instead of reassigning `translatedRows`?
