### PR TITLE
Fix query builder loading metadata for saved nested queries

### LINKED ISSUE #11235: Saved Questions Not Loading Data from Linked Tables
**Describe the bug**
Saved questions do not show linked tables in Filter and Summarize options, but new questions do. In existing saved questions, filters and group options show an empty field in the editor where the linked table field was. When trying to add a new filter or summarize in the question, the linked tables do not show up. 

When a new question is made that queries the same thing as an existing one, the linked tables and their fields show up as expected. When the new question is saved and the page is refreshed in the browser the linked tables and fields do not show up.

**Logs**
Server log from the time of loading a question using a linked table:
```10-30 16:52:47 DEBUG middleware.log :: GET /api/user/current 200 3.2 ms (3 DB calls) Jetty threads: 6/50 (5 idle, 0 queued) (316 total active threads) Queries in flight: 0
10-30 16:52:47 DEBUG middleware.log :: GET /api/session/properties 200 5.5 ms (1 DB calls) Jetty threads: 5/50 (5 idle, 0 queued) (316 total active threads) Queries in flight: 0
10-30 16:52:47 DEBUG middleware.log :: GET /api/database 200 18.0 ms (3 DB calls) Jetty threads: 7/50 (5 idle, 0 queued) (316 total active threads) Queries in flight: 0
10-30 16:52:47 DEBUG middleware.log :: GET /api/card/1493 200 10.7 ms (6 DB calls) Jetty threads: 8/50 (5 idle, 0 queued) (316 total active threads) Queries in flight: 0
10-30 16:52:47 DEBUG middleware.log :: GET /api/setting 200 1.0 ms (0 DB calls) Jetty threads: 8/50 (5 idle, 0 queued) (316 total active threads) Queries in flight: 0
10-30 16:52:47 DEBUG middleware.log :: GET /api/alert/question/1493 200 1.8 ms (1 DB calls) Jetty threads: 6/50 (4 idle, 0 queued) (316 total active threads) Queries in flight: 0
10-30 16:52:47 DEBUG middleware.log :: GET /api/table/10775/query_metadata 200 23.2 ms (11 DB calls) Jetty threads: 6/50 (4 idle, 0 queued) (316 total active threads) Queries in flight: 0
10-30 16:52:47 DEBUG middleware.log :: GET /api/collection/178 200 7.3 ms (4 DB calls) Jetty threads: 6/50 (4 idle, 0 queued) (316 total active threads) Queries in flight: 0
10-30 16:52:48 DEBUG middleware.log :: GET /api/database 200 1.1 s (24 DB calls) Jetty threads: 5/50 (4 idle, 0 queued) (316 total active threads) Queries in flight: 0
```

**To Reproduce**
1. Go to a saved question whose source table has other tables linked to it via FKs in the Data Model settings
2. See that Filters and Summarize options that use fields on the linked tables are empty
3. Click on plus buttons for Filter or Summarize to add a new Filter or Summarize and see that no linked tables show up

**Expected behavior**
Saved questions that use tables linked via FKs should be able to access the linked tables

**Screenshots**
`Creating a new question from Memberships table with a filter and group by using linked Recipients table:`
image

`Saving the new question:`
saved_question_after_save

`Reloading the saved question or accessing from its URL:`
image

`The Recipient column in the Memberships table is set in the Data Model settings to be a foreign key to the Users table:`
image

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11-post-Ubuntu-1ubuntu218.04.3",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11-post-Ubuntu-1ubuntu218.04.3",
    "os.name": "Linux",
    "os.version": "5.0.0-1021-gcp",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "sqlserver",
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-10-07",
      "tag": "v0.33.4",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}

**Severity**
We use linked tables a lot in our Metabase reports and they don't work anymore. Others may be experiencing this as well.

### LINKED ISSUE #11495: Missing values after creating a working question.
**Description**
On some questions, when I try to access them later or create another query on top of them I encounter missing or bugged values. See screenshots. 

**Logs**
```
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:13+00:00 DEBUG metabase.middleware.log GET /api/user/current 200 12.5 ms (3 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (59 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:13+00:00 DEBUG metabase.middleware.log GET /api/session/properties 200 28.3 ms (1 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (59 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:13+00:00 DEBUG metabase.middleware.log GET /api/database 200 9.0 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (61 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:13+00:00 DEBUG metabase.middleware.log GET /api/card/40 200 16.3 ms (6 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (61 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:13+00:00 DEBUG metabase.middleware.log GET /api/setting 200 1.5 ms (0 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (61 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:13+00:00 DEBUG metabase.middleware.log GET /api/alert/question/40 200 2.5 ms (1 DB calls) Jetty threads: 5/50 (2 idle, 0 queued) (61 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:13+00:00 DEBUG metabase.middleware.log GET /api/database 200 129.0 ms (7 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (61 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:13+00:00 DEBUG metabase.middleware.log GET /api/collection/1 200 6.4 ms (3 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (61 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:18+00:00 DEBUG metabase.middleware.log GET /api/session/properties 200 9.0 ms (1 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (61 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:18+00:00 DEBUG metabase.middleware.log GET /api/setup/admin_checklist 200 25.3 ms (11 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (61 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:18+00:00 DEBUG metabase.middleware.log GET /api/setting 200 695.4 µs (0 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (61 total active threads) Queries in flight: 0
[085da644-080e-4bee-87e5-ef93c0a39ab5] 2019-12-11T11:24:19+00:00 DEBUG metabase.middleware.log GET /api/util/bug_report_details 200 7.7 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (61 total active threads) Queries in flight: 0
```

**Screenshots**
missing_values
missing_values_2

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Linux",
    "os.version": "5.1.16-300.fc30.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

```
**Severity**
It's impossible to achieve some of the charts necessary. 

**Additional context**
It happens on all the fields, there is no rule. So in one case the filter is Unknown, some of the group-by's dissapear, or the method of summarizing.

### LINKED ISSUE #11561: Group by fields "lost" on filtered aggregated question
**Describe the bug**
After creating a question with a filter on aggregated data, and saving the question, the group-by are "lost"/empty (just displays an arrow `→`), but the question still works. Though it's not possible to change/remove the group-by.

**Logs**
When trying to remove the group-by (via the `X` under Editor), it gives this error:
```
Firefox: TypeError: e.field(...).name is undefined
Chromium: Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
```

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Summarize Count by User->ID
3. Filter Count > 5
4. Visualize and Save and refresh browser
5. Check Editor where group-by shows a `→` and cannot click any of `X`s to remove it or the entire Summarize section.
6. Notice the empty Group By in Simple > Summarize.

**Screenshots**
image
image

**Information about your Metabase Installation:**
Metabase 0.33.6/0.33.7.3 (didn't test on `master` because of #11560) on various backends/browsers.

**Additional context**
https://discourse.metabase.com/t/cannot-remove-a-seemingly-corrupted-group-by-field/8387
Related to #11495 - perhaps a duplicate, but I was getting different errors.
And perhaps a side-issue of #11235, which confused me in thinking it was not fixed

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #11561 
Resolves #11495 
Resolves #11235

### CODE REVIEW

File: frontend/src/metabase/query_builder/actions.js [hunk 1]
```diff
@@ -554,26 +547,23 @@ export const loadMetadataForCard = createThunkAction(
...
+        newIds = _.difference(query.dependentTableIds(), loadedIds);
+        await Promise.all(
+          newIds
+            // don't try to load tables we don't have access to
+            // this assumes the list of tables has been loaded
+            .filter(id => metadata.table(id))
+            .map(id => dispatch(Tables.actions.fetchMetadata({ id }))),
+        );
+        loadedIds.push(...newIds);
+      } while (newIds.length > 0);
```
Comment (paulrosenzweig) [inline frontend/src/metabase/query_builder/actions.js]: Will this loop ever happen more than twice?

If it can repeat more than twice, maybe it makes sense to have cards include a list of all dependent tables when returned from the server. That would avoid waiting on multiple round trips.

**Review by paulrosenzweig — APPROVED** [review]

File: frontend/src/metabase/query_builder/actions.js (hunk 1 above)
Comment (tlrobinson) [reply frontend/src/metabase/query_builder/actions.js]: I don't believe so.

Another alternative I considered was something like changing `dependentTableIds` to `dependentMetadata` which returns something like:

```
[
  { type: "table", id: 123, foreignTables: true },
  { type: "table", id: 234 },
  { type: "table", id: 345 }
]
```

That seems a little cleaner to me. We could also have `loadMetadataForQuestion` in `metabase/redux/metadata` that calls `dependentMetadata` and loads everything necessary.

File: frontend/src/metabase-lib/lib/queries/StructuredQuery.js [hunk 2]
```diff
@@ -1487,42 +1487,38 @@ export default class StructuredQuery extends AtomicQuery {
     return queries;
   }
 
-  dependentTableIds({ includeFKs = true } = {}) {
-    const tableIds = new Set();
+  /**
+   * Metadata this query needs to display correctly
+   */
+  dependentMetadata({ foreignTables = true } = {}) {
```
Comment (paulrosenzweig) [inline frontend/src/metabase-lib/lib/queries/StructuredQuery.js]: This is tested with the e2e test you added, but there's probably enough logic to justify some metabase-lib unit tests too.

Comment (tlrobinson) [reply frontend/src/metabase-lib/lib/queries/StructuredQuery.js]: Good call, adding some unit tests found a bug :)

**Comment by mazameli** [comment]
I've manually verified this PR fixes the repro steps in #11561, #11495, and #11235.

**Review by mazameli — APPROVED** [review]
