### PR TITLE
Don't update report_card.result_metadata if it has not changed

### LINKED ISSUE #56058: PostgreSQL locks are causing Metabase downtimes with MB_SEARCH_ENGINE=appdb
### Description
After upgrading from `v1.52.2.3` to `v1.53.8.2` and changing `MB_SEARCH_ENGINE` from unspecified to `appdb`, we experienced a series of downtimes. None of these downtimes has been resolved automatically and a restart of Metabase was sufficient every time.

We noticed the problem appeared only during peaks of activity and it seemed to disappear when unsetting the `MB_SEARCH_ENGINE` parameter.

Here is some information we gathered for the last downtime.

### Data collected
**PostgreSQL locks** 
Executing [this query](https://wiki.postgresql.org/wiki/Lock_Monitoring) in  Metabase internal Postgres DB gave the results attached to this issue : [mb_postgresql_locks.csv](https://github.com/user-attachments/files/19547295/mb_postgresql_locks.csv)

**Metabase logs**
By chance, we managed to retrieve a chunk of Metabase logs at the end of the downtime (just before restart) :  [mb_logs_before_restart.log](https://github.com/user-attachments/files/19547330/mb_logs_before_restart.log).

We are working on a better log management so that we can provide the full error logs when the issue occurs again.

**Prometheus metrics**
Here is a series of Metabase prometheus metrics around the last downtime (the same downtime for which we provide PostgreSQL locks and Metabase logs).

Image
Image
Image
Image
Image
Image

### Our environment
- Metabase self-hosted : `v1.53.8.2` (enterprise), deployed with docker compose
- PostgreSQL version (App DB) : `PostgreSQL 14.3 (Ubuntu 14.3-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit`

**Metabase docker service configuration :**
```yaml
metabase:
    image: metabase/metabase-enterprise:v1.52.2.3
    logging: *default-logging
    container_name: metabase
    restart: unless-stopped
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=<our_db>
      - MB_DB_PORT=5432
      - MB_DB_USER=<user>
      - MB_DB_PASS=<password>
      - MB_DB_HOST=host-postgres
      - MB_PROMETHEUS_SERVER_PORT=9191
      - MB_SEARCH_ENGINE=appdb
    extra_hosts:
      - "host-postgres:172.17.0.1"
 ```

### To Reproduce

Unknown. It happens during peaks of activity.

### Expected behavior

_No response_

### Logs

```shell
metabase  |   "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__72694.invoke(enterprise.clj:109)"
metabase  |   "query_processor.middleware.process_userland_query$process_userland_query_middleware80397__80398$fn__80399.invoke(process_userland_query.clj:221)"
metabase  |   "query_processor.middleware.catch_exceptions$catch_exceptions80462__80463$fn__80464.invoke(catch_exceptions.clj:132)"
metabase  |   "query_processor$process_query80625__80626$fn__80627.invoke(query_processor.clj:80)"
metabase  |   "query_processor.setup$do_with_canceled_chan72902__72903$fn__72904.invoke(setup.clj:187)"
metabase  |   "query_processor.setup$do_with_database_local_settings72895__72896$fn__72897.invoke(setup.clj:181)"
metabase  |   "query_processor.setup$do_with_driver72888__72889$fn__72890$fn__72891.invoke(setup.clj:166)"
metabase  |   "driver$do_with_driver.invokeStatic(driver.clj:107)"
metabase  |   "driver$do_with_driver.invoke(driver.clj:102)"
metabase  |   "query_processor.setup$do_with_driver72888__72889$fn__72890.invoke(setup.clj:165)"
metabase  |   "query_processor.setup$do_with_metadata_provider72879__72880$fn__72881$fn__72884.invoke(setup.clj:151)"
metabase  |   "query_processor.store$do_with_metadata_provider57616__57617.invokeStatic(store.clj:170)"
metabase  |   "query_processor.store$do_with_metadata_provider57616__57617.invoke(store.clj:150)"
metabase  |   "query_processor.store$do_with_metadata_provider57616__57617.invokeStatic(store.clj:159)"
metabase  |   "query_processor.store$do_with_metadata_provider57616__57617.invoke(store.clj:150)"
metabase  |   "query_processor.setup$do_with_metadata_provider72879__72880$fn__72881.invoke(setup.clj:150)"
metabase  |   "query_processor.setup$do_with_resolved_database72869__72870$fn__72871.invoke(setup.clj:128)"
metabase  |   "query_processor.setup$do_with_qp_setup72907__72908.invokeStatic(setup.clj:232)"
metabase  |   "query_processor.setup$do_with_qp_setup72907__72908.invoke(setup.clj:216)"
metabase  |   "query_processor$process_query80625__80626.invokeStatic(query_processor.clj:78)"
metabase  |   "query_processor$process_query80625__80626.invoke(query_processor.clj:71)"
metabase  |   "query_processor.card$process_query_for_card_default_qp87817__87818.invokeStatic(card.clj:232)"
metabase  |   "query_processor.card$process_query_for_card_default_qp87817__87818.invoke(card.clj:228)"
metabase  |   "api.public$process_query_for_card_with_id_run_fn$run__102010$fn__102011$fn__102012.invoke(public.clj:137)"
metabase  |   "request.session$do_with_current_user.invokeStatic(session.clj:47)"
metabase  |   "request.session$do_with_current_user.invoke(session.clj:30)"
metabase  |   "api.public$process_query_for_card_with_id_run_fn$run__102010$fn__102011.invoke(public.clj:136)"
metabase  |   "query_processor.streaming$_streaming_response$fn__87129$fn__87130$fn__87131.invoke(streaming.clj:185)"
metabase  |   "query_processor.streaming$_streaming_response$fn__87129$fn__87130.invoke(streaming.clj:183)"
metabase  |   "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:174)"
metabase  |   "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:161)"
metabase  |   "query_processor.streaming$_streaming_response$fn__87129.invoke(streaming.clj:180)"
metabase  |   "server.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
metabase  |   "server.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
metabase  |   "server.streaming_response$do_f_async$task__85090.invoke(streaming_response.clj:93)"],
metabase  |  :card_id 4301,
metabase  |  :context :embedded-dashboard,
metabase  |  :error "ERROR: canceling statement due to statement timeout",
metabase  |  :row_count 0,
metabase  |  :running_time 0,
metabase  |  :data {:rows [], :cols []}}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:136.0) Gecko/20100101 Firefox/136.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2025-03-26",
      "tag": "v1.53.8.2",
      "hash": "9dde7e5"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.3 (Ubuntu 14.3-1.pgdg20.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.6+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.6+7-LTS",
    "os.name": "Linux",
    "os.version": "5.4.0-211-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Critical : blocks our Metabase using entirely

### Additional context

_No response_

### LINKED ISSUE #56223: Database connection exhaustion caused by repeated queries to dashcard query API
I wrote the following script when trying to reproduce the cluster last_used_at dead lock #56148 

```bash
#!/bin/bash
#
# Check if a number argument is provided
if [ $# -eq 0 ]; then
    echo "Please provide a number of requests to send"
    echo "Usage: $0 <number_of_requests>"
    exit 1
fi

# Number of concurrent requests
num_requests=$1

for _ in $(seq 1 "$num_requests"); do
    for port in 3006 3007; do
        curl "http://localhost:$port/api/dashboard/1/dashcard/6/card/12/query" --compressed -X POST \
            -H 'X-Api-Key: mb_firsttestapikey' \
            -H 'Accept: application/json' \
            --data-raw '{"parameters":[{"type":"date/all-options","value":null,"id":"81cd957","target":["dimension",["field",13,{"base-type":"type/DateTime","temporal-unit":"quarter"}],{"stage-number":0}]},{"type":"temporal-unit","value":null,"id":"efd919c7","target":["dimension",["field",13,{"base-type":"type/DateTime","temporal-unit":"quarter"}],{"stage-number":0}]},{"type":"string/=","value":["Doohickey","Gizmo","Gadget","Widget"],"id":"9d9cddd4","target":["dimension",["field",18,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]},{"type":"string/=","value":null,"id":"1ebab259","target":["dimension",["field",34,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]}],"dashboard_id":1,"dashboard_load_id":"d5197e14-85a2-0a02-5b67-8a71d4e33b02"}' &
        curl "http://localhost:$port/api/dashboard/1/dashcard/8/card/15/query" --compressed -X POST \
            -H 'X-Api-Key: mb_firsttestapikey' \
            -H 'Accept: application/json' \
            --data-raw '{"parameters":[{"type":"date/all-options","value":null,"id":"81cd957","target":["dimension",["field",13,{"base-type":"type/DateTime"}],{"stage-number":0}]},{"type":"temporal-unit","value":null,"id":"efd919c7","target":["dimension",["field",13,{"base-type":"type/DateTime","temporal-unit":"quarter"}],{"stage-number":0}]},{"type":"string/=","value":["Doohickey","Gizmo","Gadget","Widget"],"id":"9d9cddd4","target":["dimension",["field",18,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]},{"type":"string/=","value":null,"id":"1ebab259","target":["dimension",["field",34,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]}],"dashboard_id":1,"dashboard_load_id":"d5197e14-85a2-0a02-5b67-8a71d4e33b02"}' &
        curl "http://localhost:$port/api/dashboard/1/dashcard/9/card/17/query" --compressed -X POST \
            -H 'X-Api-Key: mb_firsttestapikey' \
            -H 'Accept: application/json' \
            --data-raw '{"parameters":[{"type":"date/all-options","value":null,"id":"81cd957","target":["dimension",["field",13,{"base-type":"type/DateTime"}],{"stage-number":0}]},{"type":"string/=","value":["Doohickey","Gizmo","Gadget","Widget"],"id":"9d9cddd4","target":["dimension",["field",18,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]},{"type":"string/=","value":null,"id":"1ebab259","target":["dimension",["field",34,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]}],"dashboard_id":1,"dashboard_load_id":"d5197e14-85a2-0a02-5b67-8a71d4e33b02"}' &
        curl "http://localhost:$port/api/dashboard/1/dashcard/13/card/20/query" --compressed -X POST \
            -H 'X-Api-Key: mb_firsttestapikey' \
            -H 'Accept: application/json' \
            --data-raw '{"parameters":[{"type":"date/all-options","value":null,"id":"81cd957","target":["dimension",["field",13,{"base-type":"type/DateTime"}],{"stage-number":0}]},{"type":"string/=","value":["Doohickey","Gizmo","Gadget","Widget"],"id":"9d9cddd4","target":["dimension",["field",18,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]},{"type":"string/=","value":null,"id":"1ebab259","target":["dimension",["field",34,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]}],"dashboard_id":1,"dashboard_load_id":"d5197e14-85a2-0a02-5b67-8a71d4e33b02"}' &
        curl "http://localhost:$port/api/dashboard/1/dashcard/10/card/13/query" --compressed -X POST \
            -H 'X-Api-Key: mb_firsttestapikey' \
            -H 'Accept: application/json' \
            --data-raw '{"parameters":[{"type":"date/all-options","value":null,"id":"81cd957","target":["dimension",["field",13,{"base-type":"type/DateTime","temporal-unit":"month","original-temporal-unit":"quarter"}],{"stage-number":0}]},{"type":"temporal-unit","value":null,"id":"efd919c7","target":["dimension",["field",13,{"base-type":"type/DateTime","temporal-unit":"month","original-temporal-unit":"quarter"}],{"stage-number":0}]},{"type":"string/=","value":["Doohickey","Gizmo","Gadget","Widget"],"id":"9d9cddd4","target":["dimension",["field",18,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]},{"type":"string/=","value":null,"id":"1ebab259","target":["dimension",["field",34,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]}],"dashboard_id":1,"dashboard_load_id":"d5197e14-85a2-0a02-5b67-8a71d4e33b02"}' &
        curl "http://localhost:$port/api/dashboard/1/dashcard/2/card/24/query" --compressed -X POST \
            -H 'X-Api-Key: mb_firsttestapikey' \
            -H 'Accept: application/json' \
            --data-raw '{"parameters":[{"type":"date/all-options","value":null,"id":"81cd957","target":["dimension",["field",13,{"base-type":"type/DateTime"}],{"stage-number":0}]},{"type":"temporal-unit","value":null,"id":"efd919c7","target":["dimension",["field",13,{"base-type":"type/DateTime","temporal-unit":"quarter"}],{"stage-number":0}]},{"type":"string/=","value":["Doohickey","Gizmo","Gadget","Widget"],"id":"9d9cddd4","target":["dimension",["field",18,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]},{"type":"string/=","value":null,"id":"1ebab259","target":["dimension",["field",34,{"base-type":"type/Text","source-field":14}],{"stage-number":0}]}],"dashboard_id":1,"dashboard_load_id":"d5197e14-85a2-0a02-5b67-8a71d4e33b02"}' &
    done
    sleep 2
done

wait

echo "FINISHED"
```

Running this script with num requests between 20 and 40 would result in the connection filling up with mutually blocking transactions like

```sql
UPDATE report_at SET id = $1, updated_at = updated_at WHERE id = $2 
```

That were all also blocked by a query that never completed doing this

```sql
SELECT * FROM "report_card" WHERE "id" IN ($1)
```

I'm not sure this can be reproduced in practice yet, but seems like even if the database didn't come to a complete halt it could steal connections from the pool

### PR DESCRIPTION
**Pull request by nvoxland**
closes #56058
closes #56223 
### Description

Currently we are updating the card metadata on every run. That value is often large so is an expensive call, plus under load causes deadlocks especially with the new appdb search.

This PR passes along the original metadata so we can compare it with the new metadata and only save it when it changes

### How to verify

1. Run a card like: `POST http://localhost:3000/api/dashboard/1/dashcard/6/card/12/query` and see that it does not update `report_card.result_metadata` if there has been no changes.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/middleware/results_metadata.clj [hunk 1]
```diff
@@ -36,8 +49,11 @@
                card-id
                ;; don't want to update metadata when we use a Card as a source Card.
                (not (:qp/source-card-id query)))
-      (t2/update! :model/Card card-id {:result_metadata metadata
-                                       :updated_at      :updated_at}))
+      ;; Don't update the metadata if it hasn't changed
```
Comment (edpaget) [inline src/metabase/query_processor/middleware/results_metadata.clj:52]:
```suggestion
      ;; Only update changed metadata
```

File: src/metabase/query_processor/middleware/results_metadata.clj [hunk 2]
```diff
@@ -60,16 +76,16 @@
...
         {:base_type final-base-type})))
    final-col-metadata
    insights-col-metadata))
 
 (mu/defn- insights-xform :- fn?
   [orig-metadata :- [:maybe :map]
-   record!       :- ifn?
-   rf            :- ifn?]
+   record! :- ifn?
+   rf :- ifn?]
```
Comment (edpaget) [inline src/metabase/query_processor/middleware/results_metadata.clj:88]: want to keep the same spacing?

**Review by edpaget — APPROVED** [review]

File: src/metabase/query_processor/middleware/results_metadata.clj [hunk 3]
```diff
@@ -36,8 +49,11 @@
                card-id
                ;; don't want to update metadata when we use a Card as a source Card.
                (not (:qp/source-card-id query)))
-      (t2/update! :model/Card card-id {:result_metadata metadata
-                                       :updated_at      :updated_at}))
+      ;; Don't update the metadata if it hasn't changed
+      (when (and metadata (not= (standardize-metadata metadata)
+                                (:stored-metadata (:info query))))
```
Comment (edpaget) [inline src/metabase/query_processor/middleware/results_metadata.clj:54]:
```suggestion
                                (:card-stored-metadata (:info query))))
```

from [here](https://github.com/metabase/metabase/pull/56314/files#diff-e9e6c4a1c0b5bd90ee0ac026ca5fa71490995b625af14f7d2e205d1bc0375660R292)

**Review by bshepherdson — CHANGES_REQUESTED** [review]

File: src/metabase/query_processor/middleware/results_metadata.clj [hunk 4]
```diff
@@ -19,13 +20,24 @@
...
+      (map? metadata)
+      (m/filter-kv (fn [k v] (or (some? v)
+                                 (not (drop-nil-keys k))))
+                   metadata)
+
+      (sequential? metadata)
+      (mapv standardize-metadata metadata)
+
+      :else
+      metadata)))
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/results_metadata.clj:39]: This function is still being way more flexible about shapes than it needs to be.

You can just `map` the `m/filter-kv` over each column:

```suggestion
    (for [col metadata]
      (m/filter-kv (fn [k v] (or (some? v)
                                 (not (drop-nil-keys k))))
                    col))))
```

**Review by bshepherdson — APPROVED** [review]

**Comment by dpsutton** [comment]
The implementation looks weird to me. We seem to store the metadata at a key and then check a _different_ key to see the metadata in the qp.store. Does the qp.store's `store-miscellaneous-value`system change the key that values are stored at? It goes in at `::card-stored-metadata` which expands to `:metabase.query-processor.card/card-stored-metadata`, but the keyword checked is `:metadata.query-processor.card/card-stored-metadata` which is different. Is this a typo or is there some kind of magic happening in the query processor?

**Comment by edpaget** [comment]
@dpsutton it was a typo I was rushing to try to get it out before pick up and made a mistake here.

**Review by johnswanson — APPROVED** [review]
LGTM!
