### PR TITLE
Fix multi-level nested queries with joins

### LINKED ISSUE #22859: Multi-level nested questions with joins causes failed query because of incorrect column aliasing
**Describe the bug**
Creating a question based on another question with joins, which itself is based on another saved question with joins causes incorrect column aliasing and the query will fail.
This bug is not specific to Models, but makes it much more common to hit the problem with Models, because of how nesting is done.

**To Reproduce**
Let's play the Inception game.
1. Question > Sample > Reviews join Products - save as "Q1"
image
2. Question > Sample > Orders join Saved Questions "Q1" on Product ID - save as "Q2" (it works if "Q1" join Orders)
image
3. If we converted "Q2" into a Model, then using that Model would start making failed queries - let's skip the Model for now
4. Question > Saved Questions > "Q2" - the query will fail because of incorrect aliasing `Column "source.Question 957__TITLE" not found;`
image

```
SELECT "source"."ID" AS "ID",
       "source"."USER_ID" AS "USER_ID",
       "source"."PRODUCT_ID" AS "PRODUCT_ID",
       "source"."SUBTOTAL" AS "SUBTOTAL",
       "source"."TAX" AS "TAX",
       "source"."TOTAL" AS "TOTAL",
       "source"."DISCOUNT" AS "DISCOUNT",
       "source"."CREATED_AT" AS "CREATED_AT",
       "source"."QUANTITY" AS "QUANTITY",
       "source"."Question 957__ID" AS "Question 957__ID",
       "source"."Question 957__PRODUCT_ID" AS "Question 957__PRODUCT_ID",
       "source"."Question 957__REVIEWER" AS "Question 957__REVIEWER",
       "source"."Question 957__RATING" AS "Question 957__RATING",
       "source"."Question 957__BODY" AS "Question 957__BODY",
       "source"."Question 957__CREATED_AT" AS "Question 957__CREATED_AT",
       "source"."Question 957__ID" AS "Question 957__ID_2",
       "source"."Question 957__TITLE" AS "Question 957__TITLE",
       "source"."Question 957__CATEGORY" AS "Question 957__CATEGORY",
       "source"."Question 957__VENDOR" AS "Question 957__VENDOR",
       "source"."Question 957__PRICE" AS "Question 957__PRICE",
       "source"."Question 957__RATING" AS "Question 957__RATING_2",
       "source"."Question 957__CREATED_AT" AS "Question 957__CREATED_AT_2"
FROM
  (SELECT "PUBLIC"."ORDERS"."ID" AS "ID",
          "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID",
          "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID",
          "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL",
          "PUBLIC"."ORDERS"."TAX" AS "TAX",
          "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL",
          "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT",
          "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT",
          "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY",
          "Question 957"."ID" AS "Question 957__ID",
          "Question 957"."PRODUCT_ID" AS "Question 957__PRODUCT_ID",
          "Question 957"."REVIEWER" AS "Question 957__REVIEWER",
          "Question 957"."RATING" AS "Question 957__RATING",
          "Question 957"."BODY" AS "Question 957__BODY",
          "Question 957"."CREATED_AT" AS "Question 957__CREATED_AT",
          "Question 957"."Products__ID" AS "Question 957__Products__ID",
          "Question 957"."Products__TITLE" AS "Question 957__Products__TITLE",
          "Question 957"."Products__CATEGORY" AS "Question 957__Products__CATEGORY",
          "Question 957"."Products__VENDOR" AS "Question 957__Products__VENDOR",
          "Question 957"."Products__PRICE" AS "Question 957__Products__PRICE",
          "Question 957"."Products__RATING" AS "Question 957__Products__RATING",
          "Question 957"."Products__CREATED_AT" AS "Question 957__Products__CREATED_AT"
   FROM "PUBLIC"."ORDERS"
   LEFT JOIN
     (SELECT "PUBLIC"."REVIEWS"."ID" AS "ID",
             "PUBLIC"."REVIEWS"."PRODUCT_ID" AS "PRODUCT_ID",
             "PUBLIC"."REVIEWS"."REVIEWER" AS "REVIEWER",
             "PUBLIC"."REVIEWS"."RATING" AS "RATING",
             "PUBLIC"."REVIEWS"."BODY" AS "BODY",
             "PUBLIC"."REVIEWS"."CREATED_AT" AS "CREATED_AT",
             "Products"."ID" AS "Products__ID",
             "Products"."TITLE" AS "Products__TITLE",
             "Products"."CATEGORY" AS "Products__CATEGORY",
             "Products"."VENDOR" AS "Products__VENDOR",
             "Products"."PRICE" AS "Products__PRICE",
             "Products"."RATING" AS "Products__RATING",
             "Products"."CREATED_AT" AS "Products__CREATED_AT"
      FROM "PUBLIC"."REVIEWS"
      LEFT JOIN "PUBLIC"."PRODUCTS" "Products" ON "PUBLIC"."REVIEWS"."PRODUCT_ID" = "Products"."ID") "Question 957" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "Question 957"."Products__ID") "source"
LIMIT 2000
```

<details><summary>Full stacktrace</summary>

```
2022-05-19 20:26:53,904 INFO api.dataset :: Source query for this query is Card 958
2022-05-19 20:26:55,218 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2022-05-19T20:26:54.060512+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: Column \"source.Question 957__TITLE\" not found; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 596d44f4b714120eec7936accf786568eafe6086b183d96da9ece16649aa6a2e\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"Question 957__ID\" AS \"Question 957__ID\", \"source\".\"Question 957__PRODUCT_ID\" AS \"Question 957__PRODUCT_ID\", \"source\".\"Question 957__REVIEWER\" AS \"Question 957__REVIEWER\", \"source\".\"Question 957__RATING\" AS \"Question 957__RATING\", \"source\".\"Question 957__BODY\" AS \"Question 957__BODY\", \"source\".\"Question 957__CREATED_AT\" AS \"Question 957__CREATED_AT\", \"source\".\"Question 957__ID\" AS \"Question 957__ID_2\", \"source\".\"Question 957__TITLE\" AS \"Question 957__TITLE\", \"source\".\"Question 957__CATEGORY\" AS \"Question 957__CATEGORY\", \"source\".\"Question 957__VENDOR\" AS \"Question 957__VENDOR\", \"source\".\"Question 957__PRICE\" AS \"Question 957__PRICE\", \"source\".\"Question 957__RATING\" AS \"Question 957__RATING_2\", \"source\".\"Question 957__CREATED_AT\" AS \"Question 957__CREATED_AT_2\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\", \"Question 957\".\"ID\" AS \"Question 957__ID\", \"Question 957\".\"PRODUCT_ID\" AS \"Question 957__PRODUCT_ID\", \"Question 957\".\"REVIEWER\" AS \"Question 957__REVIEWER\", \"Question 957\".\"RATING\" AS \"Question 957__RATING\", \"Question 957\".\"BODY\" AS \"Question 957__BODY\", \"Question 957\".\"CREATED_AT\" AS \"Question 957__CREATED_AT\", \"Question 957\".\"Products__ID\" AS \"Question 957__Products__ID\", \"Question 957\".\"Products__TITLE\" AS \"Question 957__Products__TITLE\", \"Question 957\".\"Products__CATEGORY\" AS \"Question 957__Products__CATEGORY\", \"Question 957\".\"Products__VENDOR\" AS \"Question 957__Products__VENDOR\", \"Question 957\".\"Products__PRICE\" AS \"Question 957__Products__PRICE\", \"Question 957\".\"Products__RATING\" AS \"Question 957__Products__RATING\", \"Question 957\".\"Products__CREATED_AT\" AS \"Question 957__Products__CREATED_AT\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN (SELECT \"PUBLIC\".\"REVIEWS\".\"ID\" AS \"ID\", \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"REVIEWS\".\"REVIEWER\" AS \"REVIEWER\", \"PUBLIC\".\"REVIEWS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"REVIEWS\".\"BODY\" AS \"BODY\", \"PUBLIC\".\"REVIEWS\".\"CREATED_AT\" AS \"CREATED_AT\", \"Products\".\"ID\" AS \"Products__ID\", \"Products\".\"TITLE\" AS \"Products__TITLE\", \"Products\".\"CATEGORY\" AS \"Products__CATEGORY\", \"Products\".\"VENDOR\" AS \"Products__VENDOR\", \"Products\".\"PRICE\" AS \"Products__PRICE\", \"Products\".\"RATING\" AS \"Products__RATING\", \"Products\".\"CREATED_AT\" AS \"Products__CREATED_AT\" FROM \"PUBLIC\".\"REVIEWS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" = \"Products\".\"ID\") \"Question 957\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"Question 957\".\"Products__ID\") \"source\" LIMIT 10 [42122-197]",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__54055.invoke(execute.clj:502)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:499)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc$fn__83551.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__83551.invoke(sql_jdbc.clj:52)"
    "driver.h2$fn__80644.invokeStatic(h2.clj:90)"
    "driver.h2$fn__80644.invoke(h2.clj:87)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51444.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__47226.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50385.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__52917$combined_post_process__52922$combined_post_process_STAR___52923.invoke(query_processor.clj:207)"
    "query_processor$fn__52917$combined_pre_process__52918$combined_pre_process_STAR___52919.invoke(query_processor.clj:204)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365$fn__51370.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47469.invoke(fetch_source_query.clj:277)"
    "query_processor.middleware.store$initialize_store$fn__47657$fn__47658.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__47657.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__51637.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48727.invoke(constraints.clj:52)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__51576.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51948.invoke(catch_exceptions.clj:162)"
    "query_processor.reducible$async_qp$qp_STAR___44196$thunk__44198.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___44196.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___44196.invoke(reducible.clj:91)"
    "query_processor.reducible$sync_qp$qp_STAR___44207.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
    "query_processor$fn__52964$process_query_and_save_execution_BANG___52973$fn__52976.invoke(query_processor.clj:337)"
    "query_processor$fn__52964$process_query_and_save_execution_BANG___52973.invoke(query_processor.clj:330)"
    "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017$fn__53020.invoke(query_processor.clj:349)"
    "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017.invoke(query_processor.clj:342)"
    "api.dataset$run_query_async$fn__66683.invoke(dataset.clj:68)"
    "query_processor.streaming$streaming_response_STAR_$fn__39319$fn__39320.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__39319.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: 596d44f4b714120eec7936accf786568eafe6086b183d96da9ece16649aa6a2e\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"Question 957__ID\" AS \"Question 957__ID\", \"source\".\"Question 957__PRODUCT_ID\" AS \"Question 957__PRODUCT_ID\", \"source\".\"Question 957__REVIEWER\" AS \"Question 957__REVIEWER\", \"source\".\"Question 957__RATING\" AS \"Question 957__RATING\", \"source\".\"Question 957__BODY\" AS \"Question 957__BODY\", \"source\".\"Question 957__CREATED_AT\" AS \"Question 957__CREATED_AT\", \"source\".\"Question 957__ID\" AS \"Question 957__ID_2\", \"source\".\"Question 957__TITLE\" AS \"Question 957__TITLE\", \"source\".\"Question 957__CATEGORY\" AS \"Question 957__CATEGORY\", \"source\".\"Question 957__VENDOR\" AS \"Question 957__VENDOR\", \"source\".\"Question 957__PRICE\" AS \"Question 957__PRICE\", \"source\".\"Question 957__RATING\" AS \"Question 957__RATING_2\", \"source\".\"Question 957__CREATED_AT\" AS \"Question 957__CREATED_AT_2\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\", \"Question 957\".\"ID\" AS \"Question 957__ID\", \"Question 957\".\"PRODUCT_ID\" AS \"Question 957__PRODUCT_ID\", \"Question 957\".\"REVIEWER\" AS \"Question 957__REVIEWER\", \"Question 957\".\"RATING\" AS \"Question 957__RATING\", \"Question 957\".\"BODY\" AS \"Question 957__BODY\", \"Question 957\".\"CREATED_AT\" AS \"Question 957__CREATED_AT\", \"Question 957\".\"Products__ID\" AS \"Question 957__Products__ID\", \"Question 957\".\"Products__TITLE\" AS \"Question 957__Products__TITLE\", \"Question 957\".\"Products__CATEGORY\" AS \"Question 957__Products__CATEGORY\", \"Question 957\".\"Products__VENDOR\" AS \"Question 957__Products__VENDOR\", \"Question 957\".\"Products__PRICE\" AS \"Question 957__Products__PRICE\", \"Question 957\".\"Products__RATING\" AS \"Question 957__Products__RATING\", \"Question 957\".\"Products__CREATED_AT\" AS \"Question 957__Products__CREATED_AT\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN (SELECT \"PUBLIC\".\"REVIEWS\".\"ID\" AS \"ID\", \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"REVIEWS\".\"REVIEWER\" AS \"REVIEWER\", \"PUBLIC\".\"REVIEWS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"REVIEWS\".\"BODY\" AS \"BODY\", \"PUBLIC\".\"REVIEWS\".\"CREATED_AT\" AS \"CREATED_AT\", \"Products\".\"ID\" AS \"Products__ID\", \"Products\".\"TITLE\" AS \"Products__TITLE\", \"Products\".\"CATEGORY\" AS \"Products__CATEGORY\", \"Products\".\"VENDOR\" AS \"Products__VENDOR\", \"Products\".\"PRICE\" AS \"Products__PRICE\", \"Products\".\"RATING\" AS \"Products__RATING\", \"Products\".\"CREATED_AT\" AS \"Products__CREATED_AT\" FROM \"PUBLIC\".\"REVIEWS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" = \"Products\".\"ID\") \"Question 957\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"Question 957\".\"Products__ID\") \"source\" LIMIT 10",
    :params nil,
    :type :invalid-query}}],
 :state "42S22",
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :query {:source-table "card__958", :limit 10},
  :database 4,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"Question 957__ID\" AS \"Question 957__ID\", \"source\".\"Question 957__PRODUCT_ID\" AS \"Question 957__PRODUCT_ID\", \"source\".\"Question 957__REVIEWER\" AS \"Question 957__REVIEWER\", \"source\".\"Question 957__RATING\" AS \"Question 957__RATING\", \"source\".\"Question 957__BODY\" AS \"Question 957__BODY\", \"source\".\"Question 957__CREATED_AT\" AS \"Question 957__CREATED_AT\", \"source\".\"Question 957__ID\" AS \"Question 957__ID_2\", \"source\".\"Question 957__TITLE\" AS \"Question 957__TITLE\", \"source\".\"Question 957__CATEGORY\" AS \"Question 957__CATEGORY\", \"source\".\"Question 957__VENDOR\" AS \"Question 957__VENDOR\", \"source\".\"Question 957__PRICE\" AS \"Question 957__PRICE\", \"source\".\"Question 957__RATING\" AS \"Question 957__RATING_2\", \"source\".\"Question 957__CREATED_AT\" AS \"Question 957__CREATED_AT_2\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\", \"Question 957\".\"ID\" AS \"Question 957__ID\", \"Question 957\".\"PRODUCT_ID\" AS \"Question 957__PRODUCT_ID\", \"Question 957\".\"REVIEWER\" AS \"Question 957__REVIEWER\", \"Question 957\".\"RATING\" AS \"Question 957__RATING\", \"Question 957\".\"BODY\" AS \"Question 957__BODY\", \"Question 957\".\"CREATED_AT\" AS \"Question 957__CREATED_AT\", \"Question 957\".\"Products__ID\" AS \"Question 957__Products__ID\", \"Question 957\".\"Products__TITLE\" AS \"Question 957__Products__TITLE\", \"Question 957\".\"Products__CATEGORY\" AS \"Question 957__Products__CATEGORY\", \"Question 957\".\"Products__VENDOR\" AS \"Question 957__Products__VENDOR\", \"Question 957\".\"Products__PRICE\" AS \"Question 957__Products__PRICE\", \"Question 957\".\"Products__RATING\" AS \"Question 957__Products__RATING\", \"Question 957\".\"Products__CREATED_AT\" AS \"Question 957__Products__CREATED_AT\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN (SELECT \"PUBLIC\".\"REVIEWS\".\"ID\" AS \"ID\", \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"REVIEWS\".\"REVIEWER\" AS \"REVIEWER\", \"PUBLIC\".\"REVIEWS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"REVIEWS\".\"BODY\" AS \"BODY\", \"PUBLIC\".\"REVIEWS\".\"CREATED_AT\" AS \"CREATED_AT\", \"Products\".\"ID\" AS \"Products__ID\", \"Products\".\"TITLE\" AS \"Products__TITLE\", \"Products\".\"CATEGORY\" AS \"Products__CATEGORY\", \"Products\".\"VENDOR\" AS \"Products__VENDOR\", \"Products\".\"PRICE\" AS \"Products__PRICE\", \"Products\".\"RATING\" AS \"Products__RATING\", \"Products\".\"CREATED_AT\" AS \"Products__CREATED_AT\" FROM \"PUBLIC\".\"REVIEWS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" = \"Products\".\"ID\") \"Question 957\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"Question 957\".\"Products__ID\") \"source\" LIMIT 10",
  :params nil},
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)"
  "org.h2.expression.Alias.optimize(Alias.java:51)"
  "org.h2.command.dml.Select.prepare(Select.java:858)"
  "org.h2.command.Parser.prepareCommand(Parser.java:283)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)"
  "org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__53975.invokeStatic(execute.clj:367)"
  "driver.sql_jdbc.execute$fn__53975.invoke(execute.clj:365)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:375)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:372)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__54055.invoke(execute.clj:500)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:499)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
  "driver.sql_jdbc$fn__83551.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__83551.invoke(sql_jdbc.clj:52)"
  "driver.h2$fn__80644.invokeStatic(h2.clj:90)"
  "driver.h2$fn__80644.invoke(h2.clj:87)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
  "query_processor.context.default$default_runf.invoke(default.clj:65)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51444.invoke(cache.clj:220)"
  "query_processor.middleware.permissions$check_query_permissions$fn__47226.invoke(permissions.clj:109)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50385.invoke(mbql_to_native.clj:23)"
  "query_processor$fn__52917$combined_post_process__52922$combined_post_process_STAR___52923.invoke(query_processor.clj:207)"
  "query_processor$fn__52917$combined_pre_process__52918$combined_pre_process_STAR___52919.invoke(query_processor.clj:204)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365$fn__51370.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:75)"
  "driver$do_with_driver.invoke(driver.clj:71)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47469.invoke(fetch_source_query.clj:277)"
  "query_processor.middleware.store$initialize_store$fn__47657$fn__47658.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__47657.invoke(store.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__51637.invoke(normalize_query.clj:22)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48727.invoke(constraints.clj:52)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__51576.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51948.invoke(catch_exceptions.clj:162)"
  "query_processor.reducible$async_qp$qp_STAR___44196$thunk__44198.invoke(reducible.clj:100)"
  "query_processor.reducible$async_qp$qp_STAR___44196.invoke(reducible.clj:106)"
  "query_processor.reducible$async_qp$qp_STAR___44196.invoke(reducible.clj:91)"
  "query_processor.reducible$sync_qp$qp_STAR___44207.doInvoke(reducible.clj:126)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
  "query_processor$fn__52964$process_query_and_save_execution_BANG___52973$fn__52976.invoke(query_processor.clj:337)"
  "query_processor$fn__52964$process_query_and_save_execution_BANG___52973.invoke(query_processor.clj:330)"
  "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017$fn__53020.invoke(query_processor.clj:349)"
  "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017.invoke(query_processor.clj:342)"
  "api.dataset$run_query_async$fn__66683.invoke(dataset.clj:68)"
  "query_processor.streaming$streaming_response_STAR_$fn__39319$fn__39320.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__39319.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
 :card_id 958,
 :context :ad-hoc,
 :error
 "Column \"source.Question 957__TITLE\" not found; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 596d44f4b714120eec7936accf786568eafe6086b183d96da9ece16649aa6a2e\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"USER_ID\" AS \"USER_ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"source\".\"TAX\" AS \"TAX\", \"source\".\"TOTAL\" AS \"TOTAL\", \"source\".\"DISCOUNT\" AS \"DISCOUNT\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\", \"source\".\"QUANTITY\" AS \"QUANTITY\", \"source\".\"Question 957__ID\" AS \"Question 957__ID\", \"source\".\"Question 957__PRODUCT_ID\" AS \"Question 957__PRODUCT_ID\", \"source\".\"Question 957__REVIEWER\" AS \"Question 957__REVIEWER\", \"source\".\"Question 957__RATING\" AS \"Question 957__RATING\", \"source\".\"Question 957__BODY\" AS \"Question 957__BODY\", \"source\".\"Question 957__CREATED_AT\" AS \"Question 957__CREATED_AT\", \"source\".\"Question 957__ID\" AS \"Question 957__ID_2\", \"source\".\"Question 957__TITLE\" AS \"Question 957__TITLE\", \"source\".\"Question 957__CATEGORY\" AS \"Question 957__CATEGORY\", \"source\".\"Question 957__VENDOR\" AS \"Question 957__VENDOR\", \"source\".\"Question 957__PRICE\" AS \"Question 957__PRICE\", \"source\".\"Question 957__RATING\" AS \"Question 957__RATING_2\", \"source\".\"Question 957__CREATED_AT\" AS \"Question 957__CREATED_AT_2\" FROM (SELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\", \"Question 957\".\"ID\" AS \"Question 957__ID\", \"Question 957\".\"PRODUCT_ID\" AS \"Question 957__PRODUCT_ID\", \"Question 957\".\"REVIEWER\" AS \"Question 957__REVIEWER\", \"Question 957\".\"RATING\" AS \"Question 957__RATING\", \"Question 957\".\"BODY\" AS \"Question 957__BODY\", \"Question 957\".\"CREATED_AT\" AS \"Question 957__CREATED_AT\", \"Question 957\".\"Products__ID\" AS \"Question 957__Products__ID\", \"Question 957\".\"Products__TITLE\" AS \"Question 957__Products__TITLE\", \"Question 957\".\"Products__CATEGORY\" AS \"Question 957__Products__CATEGORY\", \"Question 957\".\"Products__VENDOR\" AS \"Question 957__Products__VENDOR\", \"Question 957\".\"Products__PRICE\" AS \"Question 957__Products__PRICE\", \"Question 957\".\"Products__RATING\" AS \"Question 957__Products__RATING\", \"Question 957\".\"Products__CREATED_AT\" AS \"Question 957__Products__CREATED_AT\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN (SELECT \"PUBLIC\".\"REVIEWS\".\"ID\" AS \"ID\", \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"REVIEWS\".\"REVIEWER\" AS \"REVIEWER\", \"PUBLIC\".\"REVIEWS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"REVIEWS\".\"BODY\" AS \"BODY\", \"PUBLIC\".\"REVIEWS\".\"CREATED_AT\" AS \"CREATED_AT\", \"Products\".\"ID\" AS \"Products__ID\", \"Products\".\"TITLE\" AS \"Products__TITLE\", \"Products\".\"CATEGORY\" AS \"Products__CATEGORY\", \"Products\".\"VENDOR\" AS \"Products__VENDOR\", \"Products\".\"PRICE\" AS \"Products__PRICE\", \"Products\".\"RATING\" AS \"Products__RATING\", \"Products\".\"CREATED_AT\" AS \"Products__CREATED_AT\" FROM \"PUBLIC\".\"REVIEWS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" = \"Products\".\"ID\") \"Question 957\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"Question 957\".\"Products__ID\") \"source\" LIMIT 10 [42122-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:limit 10,
   :source-card-id 958,
   :source-metadata
   [{:description
     "This is a unique ID for the product. It is also called the “Invoice number” or “Confirmation number” in customer facing emails and screens.",
     :semantic_type :type/PK,
     :coercion_strategy nil,
     :name "ID",
     :settings nil,
     :field_ref [:field 83 nil],
     :effective_type :type/BigInteger,
     :id 83,
     :display_name "ID",
     :fingerprint
     {:global {:distinct-count 10001, :nil% 0.0},
      :type
      {:type/Number
       {:min 1.0, :q1 2491.740180650251, :q3 7500.666771221716, :max 10000.0, :sd 2886.486531970992, :avg 5000.5}}},
     :base_type :type/BigInteger}
    {:description
     "The id of the user who made this order. Note that in some cases where an order was created on behalf of a customer who phoned the order in, this might be the employee who handled the request.",
     :semantic_type :type/FK,
     :coercion_strategy nil,
     :name "USER_ID",
     :settings nil,
     :field_ref [:field 80 nil],
     :effective_type :type/Integer,
     :id 80,
     :display_name "User ID",
     :fingerprint {:global {:distinct-count 929, :nil% 0.0}},
     :base_type :type/Integer}
    {:description "The product ID. This is an internal identifier for the product, NOT the SKU.",
     :semantic_type :type/FK,
     :coercion_strategy nil,
     :name "PRODUCT_ID",
     :settings nil,
     :field_ref [:field 82 nil],
     :effective_type :type/Integer,
     :id 82,
     :display_name "Product ID",
     :fingerprint {:global {:distinct-count 200, :nil% 0.0}},
     :base_type :type/Integer}
    {:description
     "The raw, pre-tax cost of the order. Note that this might be different in the future from the product price due to promotions, credits, etc.",
     :semantic_type :type/Price,
     :coercion_strategy nil,
     :name "SUBTOTAL",
     :settings {:currency "EUR", :currency_in_header false, :currency_style "symbol"},
     :field_ref [:field 84 nil],
     :effective_type :type/Float,
     :id 84,
     :display_name "Subtotal",
     :fingerprint
     {:global {:distinct-count 340, :nil% 0.0},
      :type
      {:type/Number
       {:min 15.691943673970439,
        :q1 49.74894519060184,
        :q3 105.42965746993103,
        :max 148.22900526552291,
        :sd 32.53705013056317,
        :avg 77.01295465356547}}},
     :base_type :type/Float}
    {:description
     "This is the amount of local and federal taxes that are collected on the purchase. Note that other governmental fees on some products are not included here, but instead are accounted for in the subtotal.",
     :semantic_type :type/Currency,
     :coercion_strategy nil,
     :name "TAX",
     :settings {:currency_style "code"},
     :field_ref [:field 87 nil],
     :effective_type :type/Float,
     :id 87,
     :display_name "Tax",
     :fingerprint
     {:global {:distinct-count 797, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0,
        :q1 2.273340386603857,
        :q3 5.337275338216307,
        :max 11.12,
        :sd 2.3206651358900316,
        :avg 3.8722100000000004}}},
     :base_type :type/Float}
    {:description "The total billed amount.",
     :semantic_type :type/Income,
     :coercion_strategy nil,
     :name "TOTAL",
     :settings {:currency_style "code"},
     :field_ref [:field 88 nil],
     :effective_type :type/Float,
     :id 88,
     :display_name "Total",
     :fingerprint
     {:global {:distinct-count 4426, :nil% 0.0},
      :type
      {:type/Number
       {:min 8.93914247937167,
        :q1 51.34535490743823,
        :q3 110.29428389265787,
        :max 159.34900526552292,
        :sd 34.26469575709948,
        :avg 80.35871658771228}}},
     :base_type :type/Float}
    {:description "Discount amount.",
     :semantic_type :type/Discount,
     :coercion_strategy nil,
     :name "DISCOUNT",
     :settings {},
     :field_ref [:field 81 nil],
     :effective_type :type/Float,
     :id 81,
     :display_name "Discount",
     :fingerprint
     {:global {:distinct-count 701, :nil% 0.898},
      :type
      {:type/Number
       {:min 0.17088996672584322,
        :q1 2.9786226681458743,
        :q3 7.338187788658235,
        :max 61.69684269960571,
        :sd 3.053663125001991,
        :avg 5.161255547580326}}},
     :base_type :type/Float}
    {:description "The date and time an order was submitted.",
     :semantic_type :type/CreationTimestamp,
     :coercion_strategy nil,
     :unit :default,
     :name "CREATED_AT",
     :settings nil,
     :field_ref [:field 86 {:temporal-unit :default}],
     :effective_type :type/DateTime,
     :id 86,
     :display_name "Created At",
     :fingerprint
     {:global {:distinct-count 9998, :nil% 0.0},
      :type {:type/DateTime {:earliest "2016-04-30T18:56:13.352Z", :latest "2020-04-19T14:07:15.657Z"}}},
     :base_type :type/DateTime}
    {:description "Number of products bought.",
     :semantic_type :type/Quantity,
     :coercion_strategy nil,
     :name "QUANTITY",
     :settings nil,
     :field_ref [:field 85 nil],
     :effective_type :type/Integer,
     :id 85,
     :display_name "Quantity",
     :fingerprint
     {:global {:distinct-count 62, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0, :q1 1.755882607764982, :q3 4.882654507928044, :max 100.0, :sd 4.214258386403798, :avg 3.7015}}},
     :base_type :type/Integer}
    {:description "A unique internal identifier for the review. Should not be used externally.",
     :semantic_type :type/PK,
     :coercion_strategy nil,
     :name "ID_2",
     :settings nil,
     :field_ref [:field 111 {:join-alias "Question 957"}],
     :effective_type :type/BigInteger,
     :id 111,
     :display_name "Question 957 → ID",
     :fingerprint nil,
     :base_type :type/BigInteger}
    {:description "The product the review was for",
     :semantic_type :type/FK,
     :coercion_strategy nil,
     :name "PRODUCT_ID_2",
     :settings nil,
     :field_ref [:field 110 {:join-alias "Question 957"}],
     :effective_type :type/Integer,
     :id 110,
     :display_name "Question 957 → Product ID",
     :fingerprint {:global {:distinct-count 176, :nil% 0.0}},
     :base_type :type/Integer}
    {:description "The user who left the review",
     :semantic_type :type/Name,
     :coercion_strategy nil,
     :name "REVIEWER",
     :settings nil,
     :field_ref [:field 113 {:join-alias "Question 957"}],
     :effective_type :type/Text,
     :id 113,
     :display_name "Question 957 → Reviewer",
     :fingerprint
     {:global {:distinct-count 1076, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0,
        :percent-url 0.0,
        :percent-email 0.0,
        :percent-state 0.001798561151079137,
        :average-length 9.972122302158274}}},
     :base_type :type/Text}
    {:description "The rating (on a scale of 1-5) the user left.",
     :semantic_type :type/Score,
     :coercion_strategy nil,
     :name "RATING",
     :settings nil,
     :field_ref [:field 115 {:join-alias "Question 957"}],
     :effective_type :type/Integer,
     :id 115,
     :display_name "Question 957 → Rating",
     :fingerprint
     {:global {:distinct-count 5, :nil% 0.0},
      :type
      {:type/Number
       {:min 1.0,
        :q1 3.54744353181696,
        :q3 4.764807071650455,
        :max 5.0,
        :sd 1.0443899855660577,
        :avg 3.987410071942446}}},
     :base_type :type/Integer}
    {:description "The review the user left. Limited to 2000 characters.",
     :semantic_type :type/Description,
     :coercion_strategy nil,
     :name "BODY",
     :settings nil,
     :field_ref [:field 112 {:join-alias "Question 957"}],
     :effective_type :type/Text,
     :id 112,
     :display_name "Question 957 → Body",
     :fingerprint
     {:global {:distinct-count 1112, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0,
        :percent-url 0.0,
        :percent-email 0.0,
        :percent-state 0.0,
        :average-length 177.41996402877697}}},
     :base_type :type/Text}
    {:description "The day and time a review was written by a user.",
     :semantic_type :type/CreationTimestamp,
     :coercion_strategy nil,
     :name "CREATED_AT_2",
     :settings nil,
     :field_ref [:field 114 {:join-alias "Question 957", :temporal-unit :default}],
     :effective_type :type/DateTime,
     :id 114,
     :display_name "Question 957 → Created At",
     :fingerprint
     {:global {:distinct-count 1112, :nil% 0.0},
      :type {:type/DateTime {:earliest "2016-06-03T00:37:05.818Z", :latest "2020-04-19T14:15:25.677Z"}}},
     :base_type :type/DateTime}
    {:description
     "The numerical product number. Only used internally. All external communication should use the title or EAN.",
     :semantic_type :type/PK,
     :coercion_strategy nil,
     :name "ID_3",
     :settings nil,
     :field_ref [:field 105 {:join-alias "Question 957"}],
     :effective_type :type/BigInteger,
     :id 105,
     :display_name "Question 957 → ID",
     :fingerprint nil,
     :base_type :type/BigInteger}
    {:description "The name of the product as it should be displayed to customers.",
     :semantic_type :type/Name,
     :coercion_strategy nil,
     :name "TITLE",
     :settings nil,
     :field_ref [:field 106 {:join-alias "Question 957"}],
     :effective_type :type/Text,
     :id 106,
     :display_name "Question 957 → Title",
     :fingerprint
     {:global {:distinct-count 199, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.495}}},
     :base_type :type/Text}
    {:description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
     :semantic_type :type/Category,
     :coercion_strategy nil,
     :name "CATEGORY",
     :settings nil,
     :field_ref [:field 107 {:join-alias "Question 957"}],
     :effective_type :type/Text,
     :id 107,
     :display_name "Question 957 → Category",
     :fingerprint
     {:global {:distinct-count 4, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
     :base_type :type/Text}
    {:description "The source of the product.",
     :semantic_type :type/Company,
     :coercion_strategy nil,
     :name "VENDOR",
     :settings nil,
     :field_ref [:field 109 {:join-alias "Question 957"}],
     :effective_type :type/Text,
     :id 109,
     :display_name "Question 957 → Vendor",
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type
      {:type/Text
       {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}},
     :base_type :type/Text}
    {:description
     "The list price of the product. Note that this is not always the price the product sold for due to discounts, promotions, etc.",
     :semantic_type :type/Price,
     :coercion_strategy nil,
     :name "PRICE",
     :settings {},
     :field_ref [:field 104 {:join-alias "Question 957"}],
     :effective_type :type/Float,
     :id 104,
     :display_name "Question 957 → Price",
     :fingerprint
     {:global {:distinct-count 170, :nil% 0.0},
      :type
      {:type/Number
       {:min 15.691943673970439,
        :q1 37.25154462926434,
        :q3 75.45898071609447,
        :max 98.81933684368194,
        :sd 21.711481557852057,
        :avg 55.74639966792074}}},
     :base_type :type/Float}
    {:description "The average rating users have given the product. This ranges from 1 - 5",
     :semantic_type :type/Score,
     :coercion_strategy nil,
     :name "RATING_2",
     :settings nil,
     :field_ref [:field 103 {:join-alias "Question 957"}],
     :effective_type :type/Float,
     :id 103,
     :display_name "Question 957 → Rating",
     :fingerprint
     {:global {:distinct-count 23, :nil% 0.0},
      :type
      {:type/Number
       {:min 0.0, :q1 3.5120465053408525, :q3 4.216124969497314, :max 5.0, :sd 1.3605488657451452, :avg 3.4715}}},
     :base_type :type/Float}
    {:description "The date the product was added to our catalog.",
     :semantic_type :type/CreationTimestamp,
     :coercion_strategy nil,
     :name "CREATED_AT_3",
     :settings {:date_separator ".", :time_style "k:mm"},
     :field_ref [:field 108 {:join-alias "Question 957", :temporal-unit :default}],
     :effective_type :type/DateTime,
     :id 108,
     :display_name "Question 957 → Created At",
     :fingerprint
     {:global {:distinct-count 200, :nil% 0.0},
      :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147Z", :latest "2019-04-15T13:34:19.931Z"}}},
     :base_type :type/DateTime}],
   :fields
   [[:field 83 nil]
    [:field 80 nil]
    [:field 82 nil]
    [:field 84 nil]
    [:field 87 nil]
    [:field 88 nil]
    [:field 81 nil]
    [:field 86 {:temporal-unit :default}]
    [:field 85 nil]
    [:field 111 {:join-alias "Question 957"}]
    [:field 110 {:join-alias "Question 957"}]
    [:field 113 {:join-alias "Question 957"}]
    [:field 115 {:join-alias "Question 957"}]
    [:field 112 {:join-alias "Question 957"}]
    [:field 114 {:join-alias "Question 957", :temporal-unit :default}]
    [:field 105 {:join-alias "Question 957"}]
    [:field 106 {:join-alias "Question 957"}]
    [:field 107 {:join-alias "Question 957"}]
    [:field 109 {:join-alias "Question 957"}]
    [:field 104 {:join-alias "Question 957"}]
    [:field 103 {:join-alias "Question 957"}]
    [:field 108 {:join-alias "Question 957", :temporal-unit :default}]],
   :source-query
   {:source-table 11,
    :fields
    [[:field 83 nil]
     [:field 80 nil]
     [:field 82 nil]
     [:field 84 nil]
     [:field 87 nil]
     [:field 88 nil]
     [:field 81 nil]
     [:field 86 {:temporal-unit :default}]
     [:field 85 nil]
     [:field 111 {:join-alias "Question 957"}]
     [:field 110 {:join-alias "Question 957"}]
     [:field 113 {:join-alias "Question 957"}]
     [:field 115 {:join-alias "Question 957"}]
     [:field 112 {:join-alias "Question 957"}]
     [:field 114 {:join-alias "Question 957"}]
     [:field 105 {:join-alias "Question 957"}]
     [:field 106 {:join-alias "Question 957"}]
     [:field 107 {:join-alias "Question 957"}]
     [:field 109 {:join-alias "Question 957"}]
     [:field 104 {:join-alias "Question 957"}]
     [:field 103 {:join-alias "Question 957"}]
     [:field 108 {:join-alias "Question 957"}]],
    :joins
    [{:alias "Question 957",
      :strategy :left-join,
      :fields
      [[:field 111 {:join-alias "Question 957"}]
       [:field 110 {:join-alias "Question 957"}]
       [:field 113 {:join-alias "Question 957"}]
       [:field 115 {:join-alias "Question 957"}]
       [:field 112 {:join-alias "Question 957"}]
       [:field 114 {:join-alias "Question 957"}]
       [:field 105 {:join-alias "Question 957"}]
       [:field 106 {:join-alias "Question 957"}]
       [:field 107 {:join-alias "Question 957"}]
       [:field 109 {:join-alias "Question 957"}]
       [:field 104 {:join-alias "Question 957"}]
       [:field 103 {:join-alias "Question 957"}]
       [:field 108 {:join-alias "Question 957"}]],
      :condition [:= [:field 82 nil] [:field 105 {:join-alias "Question 957"}]],
      :source-card-id 957,
      :source-query
      {:source-table 13,
       :fields
       [[:field 111 nil]
        [:field 110 nil]
        [:field 113 nil]
        [:field 115 nil]
        [:field 112 nil]
        [:field 114 {:temporal-unit :default}]
        [:field 105 {:join-alias "Products"}]
        [:field 106 {:join-alias "Products"}]
        [:field 107 {:join-alias "Products"}]
        [:field 109 {:join-alias "Products"}]
        [:field 104 {:join-alias "Products"}]
        [:field 103 {:join-alias "Products"}]
        [:field 108 {:temporal-unit :default, :join-alias "Products"}]],
       :joins
       [{:alias "Products",
         :strategy :left-join,
         :fields
         [[:field 105 {:join-alias "Products"}]
          [:field 106 {:join-alias "Products"}]
          [:field 107 {:join-alias "Products"}]
          [:field 109 {:join-alias "Products"}]
          [:field 104 {:join-alias "Products"}]
          [:field 103 {:join-alias "Products"}]
          [:field 108 {:temporal-unit :default, :join-alias "Products"}]],
         :source-table 10,
         :condition [:= [:field 110 nil] [:field 105 {:join-alias "Products"}]]}]},
      :source-metadata
      [{:description "A unique internal identifier for the review. Should not be used externally.",
        :semantic_type :type/PK,
        :coercion_strategy nil,
        :name "ID",
        :settings nil,
        :field_ref [:field 111 nil],
        :effective_type :type/BigInteger,
        :id 111,
        :display_name "ID",
        :fingerprint nil,
        :base_type :type/BigInteger}
       {:description "The product the review was for",
        :semantic_type :type/FK,
        :coercion_strategy nil,
        :name "PRODUCT_ID",
        :settings nil,
        :field_ref [:field 110 nil],
        :effective_type :type/Integer,
        :id 110,
        :display_name "Product ID",
        :fingerprint {:global {:distinct-count 176, :nil% 0.0}},
        :base_type :type/Integer}
       {:description "The user who left the review",
        :semantic_type :type/Name,
        :coercion_strategy nil,
        :name "REVIEWER",
        :settings nil,
        :field_ref [:field 113 nil],
        :effective_type :type/Text,
        :id 113,
        :display_name "Reviewer",
        :fingerprint
        {:global {:distinct-count 1076, :nil% 0.0},
         :type
         {:type/Text
          {:percent-json 0.0,
           :percent-url 0.0,
           :percent-email 0.0,
           :percent-state 0.001798561151079137,
           :average-length 9.972122302158274}}},
        :base_type :type/Text}
       {:description "The rating (on a scale of 1-5) the user left.",
        :semantic_type :type/Score,
        :coercion_strategy nil,
        :name "RATING",
        :settings nil,
        :field_ref [:field 115 nil],
        :effective_type :type/Integer,
        :id 115,
        :display_name "Rating",
        :fingerprint
        {:global {:distinct-count 5, :nil% 0.0},
         :type
         {:type/Number
          {:min 1.0,
           :q1 3.54744353181696,
           :q3 4.764807071650455,
           :max 5.0,
           :sd 1.0443899855660577,
           :avg 3.987410071942446}}},
        :base_type :type/Integer}
       {:description "The review the user left. Limited to 2000 characters.",
        :semantic_type :type/Description,
        :coercion_strategy nil,
        :name "BODY",
        :settings nil,
        :field_ref [:field 112 nil],
        :effective_type :type/Text,
        :id 112,
        :display_name "Body",
        :fingerprint
        {:global {:distinct-count 1112, :nil% 0.0},
         :type
         {:type/Text
          {:percent-json 0.0,
           :percent-url 0.0,
           :percent-email 0.0,
           :percent-state 0.0,
           :average-length 177.41996402877697}}},
        :base_type :type/Text}
       {:description "The day and time a review was written by a user.",
        :semantic_type :type/CreationTimestamp,
        :coercion_strategy nil,
        :unit :default,
        :name "CREATED_AT",
        :settings nil,
        :field_ref [:field 114 {:temporal-unit :default}],
        :effective_type :type/DateTime,
        :id 114,
        :display_name "Created At",
        :fingerprint
        {:global {:distinct-count 1112, :nil% 0.0},
         :type {:type/DateTime {:earliest "2016-06-03T00:37:05.818Z", :latest "2020-04-19T14:15:25.677Z"}}},
        :base_type :type/DateTime}
       {:description
        "The numerical product number. Only used internally. All external communication should use the title or EAN.",
        :semantic_type :type/PK,
        :coercion_strategy nil,
        :name "ID_2",
        :settings nil,
        :field_ref [:field 105 {:join-alias "Products"}],
        :effective_type :type/BigInteger,
        :id 105,
        :display_name "Products → ID",
        :fingerprint nil,
        :base_type :type/BigInteger}
       {:description "The name of the product as it should be displayed to customers.",
        :semantic_type :type/Name,
        :coercion_strategy nil,
        :name "TITLE",
        :settings nil,
        :field_ref [:field 106 {:join-alias "Products"}],
        :effective_type :type/Text,
        :id 106,
        :display_name "Products → Title",
        :fingerprint
        {:global {:distinct-count 199, :nil% 0.0},
         :type
         {:type/Text
          {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.495}}},
        :base_type :type/Text}
       {:description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
        :semantic_type :type/Category,
        :coercion_strategy nil,
        :name "CATEGORY",
        :settings nil,
        :field_ref [:field 107 {:join-alias "Products"}],
        :effective_type :type/Text,
        :id 107,
        :display_name "Products → Category",
        :fingerprint
        {:global {:distinct-count 4, :nil% 0.0},
         :type
         {:type/Text
          {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
        :base_type :type/Text}
       {:description "The source of the product.",
        :semantic_type :type/Company,
        :coercion_strategy nil,
        :name "VENDOR",
        :settings nil,
        :field_ref [:field 109 {:join-alias "Products"}],
        :effective_type :type/Text,
        :id 109,
        :display_name "Products → Vendor",
        :fingerprint
        {:global {:distinct-count 200, :nil% 0.0},
         :type
         {:type/Text
          {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}},
        :base_type :type/Text}
       {:description
        "The list price of the product. Note that this is not always the price the product sold for due to discounts, promotions, etc.",
        :semantic_type :type/Price,
        :coercion_strategy nil,
        :name "PRICE",
        :settings {},
        :field_ref [:field 104 {:join-alias "Products"}],
        :effective_type :type/Float,
        :id 104,
        :display_name "Products → Price",
        :fingerprint
        {:global {:distinct-count 170, :nil% 0.0},
         :type
         {:type/Number
          {:min 15.691943673970439,
           :q1 37.25154462926434,
           :q3 75.45898071609447,
           :max 98.81933684368194,
           :sd 21.711481557852057,
           :avg 55.74639966792074}}},
        :base_type :type/Float}
       {:description "The average rating users have given the product. This ranges from 1 - 5",
        :semantic_type :type/Score,
        :coercion_strategy nil,
        :name "RATING_2",
        :settings nil,
        :field_ref [:field 103 {:join-alias "Products"}],
        :effective_type :type/Float,
        :id 103,
        :display_name "Products → Rating",
        :fingerprint
        {:global {:distinct-count 23, :nil% 0.0},
         :type
         {:type/Number
          {:min 0.0, :q1 3.5120465053408525, :q3 4.216124969497314, :max 5.0, :sd 1.3605488657451452, :avg 3.4715}}},
        :base_type :type/Float}
       {:description "The date the product was added to our catalog.",
        :semantic_type :type/CreationTimestamp,
        :coercion_strategy nil,
        :unit :default,
        :name "CREATED_AT_2",
        :settings {:date_separator ".", :time_style "k:mm"},
        :field_ref [:field 108 {:temporal-unit :default, :join-alias "Products"}],
        :effective_type :type/DateTime,
        :id 108,
        :display_name "Products → Created At",
        :fingerprint
        {:global {:distinct-count 200, :nil% 0.0},
         :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147Z", :latest "2019-04-15T13:34:19.931Z"}}},
        :base_type :type/DateTime}]}]}},
  :database 4,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 1, :context :ad-hoc, :card-id 958}},
 :data {:rows [], :cols []}}

2022-05-19 20:26:55,237 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.3 s (71 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (3 idle, 0 queued) (119 total active threads) Queries in flight: 0 (0 queued); h2 DB 4 connections: 0/1 (0 threads blocked)
```

</details>

**Information about your Metabase Installation:**
Tested 0.41.7 thru 0.43.1

**Additional context**
Likely very related to #20809, historically to #12928 and #14724
Initially discovered by @snarfed

### PR DESCRIPTION
**Pull request by metamben**
Fixes #22859.

The problem is related to fields "inherited" from a join (i.e., having a join alias) in a nested query where the actual alias of the field is different from the "default" name, i.e., from the one that is generated for fields from joins (composed from the table name and the field name). The suggested fix is to prefer the actual name in the nested query to the default name for joined fields.

Before this change for such fields Metabase would generate a dangling name and the drivers would throw an exception. The test I added uses the query from the bug ticket which doesn't make much sense, so all I do is to check if the query can be run successfully.

### CODE REVIEW

**Review by dpsutton — APPROVED** [review]

File: src/metabase/query_processor/util/add_alias_info.clj [hunk 1]
```diff
@@ -289,9 +289,9 @@
     ;; suffix to escaped identifiers.)
     ;;
     ;; We'll have to look into this more in the future. For now, it seems to work for everything we try it with.
-    (and join-alias (not join-is-this-level?)) (prefix-field-alias join-alias field-name)
     (and join-is-this-level? alias-from-join)  alias-from-join
     alias-from-source-query                    alias-from-source-query
```
Comment (metamben) [inline src/metabase/query_processor/util/add_alias_info.clj:293]: I'm not quite sure if this is the right order, if the reverse order would be better or if it doesn't matter. (I guess it doesn't matter.)
