### PR TITLE
Fix tooltip value on unaggregated data

### LINKED ISSUE #11907: Tooltip on unaggregated data does not show summed value like the visualization
**Describe the bug**
When showing a line/bar chart with unaggregated data, it sums up the values correctly in the visualization, but hovering the tick will only show a single data point in the tooltip.
Hovering the warning triangle in the right-top corner of the visualization will show the warning: `"d" is an unaggregated field: if it has more than one value at a point on the x-axis, the values will be summed.`

**To Reproduce**
Run this SQL (H2) and set the visualization to line/bar and hover the first tick, which has a summed value of `10` (shown on the visualization correctly), but will show `5` in the tooltip.
```
SELECT parsedatetime('2020-01-01', 'yyyy-MM-dd') AS "d", 5 AS "c" UNION ALL
SELECT parsedatetime('2020-01-01', 'yyyy-MM-dd') AS "d", 2 AS "c" UNION ALL
SELECT parsedatetime('2020-01-01', 'yyyy-MM-dd') AS "d", 3 AS "c" UNION ALL
SELECT parsedatetime('2020-01-02', 'yyyy-MM-dd') AS "d", 1 AS "c" UNION ALL
SELECT parsedatetime('2020-01-02', 'yyyy-MM-dd') AS "d", 4 AS "c"
```

**Expected behavior**
Tooltip should show same value as the visualization.

**Screenshots**
Screenshot_00000

**Information about your Metabase Installation:**
Metabase x.34.2 and `master` with multiple backends and browsers.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by alxnddr**
### Description

In order to show correct values inside the tooltip when data is unaggregated, we have to retrieve metric value from crossfilter groups

Query:
```
SELECT 1 AS "d", 1 AS "c", 100 as "j" UNION ALL
SELECT 1 AS "d", 2 AS "c", 200 as "j" UNION ALL
SELECT 3 AS "d", 10 AS "c", 500 as "j" 
```
Result:
Screen Shot 2021-04-07 at 03 06 20
It shows grouped values `c = 3` and `j = 300` for `d = 1`

Fixes https://github.com/metabase/metabase/issues/11907

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/apply_tooltips.js [hunk 1]
```diff
@@ -95,7 +95,9 @@ export function getClickHoverObject(
     // Loop over *all* of the columns and create the new array
     if (rawRow) {
       data = rawCols.map((col, i) => {
-        if (isNormalized && cols[1].field_ref === col.field_ref) {
+        const isSeriesValueColumn = cols[1].field_ref === col.field_ref;
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/lib/apply_tooltips.js:98]: @paulrosenzweig is it possible to have `field_ref` null or undefined?

Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/lib/apply_tooltips.js:98]: I can't think of a situation where that would be undefined. Even if it's a native query or aggregated value in a GUI query, it should have a field ref.

This isn't code you wrote, but comparing objects with `===` makes me nervous. I guess we're fine here if it's been working, but it might be worth the perf hit to use `_.isEquals` instead.

Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/lib/apply_tooltips.js:98]: > This isn't code you wrote

It turns out that I wrote it. 😆 Though, prior to my change it was comparing columns with `===`.

Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/apply_tooltips.js]: @paulrosenzweig thanks for the answer! I also changed the comparison to `_.isEquals` as you suggested

**Review by paulrosenzweig — APPROVED** [review]
LGTM!
