### PR TITLE
Apply field settings to parameter field widget

### LINKED ISSUE #62107: Number Format Settings not Respected in Dashboard Filters
### Describe the bug

If you modify the number formatting in table metadata for a field (ex. change the separator style) the results return data with the correct format but the dashboard filters do not.

### To Reproduce

1. Create a test table in Postgres with int8 field

```
CREATE TABLE public.test_table (
    id SERIAL PRIMARY KEY,
    text_field TEXT NOT NULL,
    int8_field BIGINT NOT NULL
);

INSERT INTO public.test_table (text_field, int8_field)
SELECT 
    'Sample text ' || g AS text_field,
    2000 + (g % 26) AS int8_field
FROM generate_series(1, 20) AS g;
```

2. Sync it and set the formatting setting for the int8 field such that there are no commas
3. Create a Question & add it to a dashboard
4. Note the correct formatting in the Question results
5. Add a dashboard filter and wire it to the int8 field
6. Note the items int he dropdown contain a comma

https://www.loom.com/share/32bacb77fdb9473d8c2c9a31f98ced99

### Expected behavior

Formatting in the filter should match the formatting configured for the field.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-08-06",
      "tag": "v1.55.11",
      "hash": "313ee38"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "5.15.167.4-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

The filters look incorrect

### Additional context

Setting the formatting globally doesn't impact filter behavior, either.

### PR DESCRIPTION
**Pull request by fraserdrops**
closes #62107

The formatting in the dropdown now matches the formatting in the table. See the linked issue for detailed repro steps.

Screenshot 2025-12-23 at 4 48 41 PM

### CODE REVIEW

File: frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/ParameterFieldWidget.tsx [hunk 1]
```diff
@@ -113,9 +113,11 @@ export function ParameterFieldWidget({
               fields={fields}
               autoFocus={index === 0}
               multi={supportsMultipleValues}
-              formatOptions={
-                operator && getFilterArgumentFormatOptions(operator, index)
-              }
+              formatOptions={{
+                ...(operator &&
+                  getFilterArgumentFormatOptions(operator, index)),
+                ...fields?.[0]?.settings,
```
Comment (fraserdrops) [inline frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/ParameterFieldWidget.tsx:119]: There's some really complicated type stuff going on. 

MutableParametersSection.unit.spec.tsx had a failing test because it doesn't pass fields in the mock, and the types don't require it to.

The isFieldWidget type guard doesn't check if parameter.fields exists in all cases, but it asserts that parameter is of type FieldFilterUiParameter which has fields key always defined.
The downstream consequence is that ParameterFieldWidget expects fields to be always defined, but some consumers of ParameterFieldWidget could be passing undefined (I'm not sure if any actually are in practice aside from the test, but the type system won't catch it).

**Review by romeovs — APPROVED** [review]
