### PR TITLE
Fix public/embedded pivot tables

### LINKED ISSUE #14447: Pivot tables use the wrong public/embed endpoints
At some point in the past few days public/embedded pivot tables stopped using the correct endpoints instead of the normal authenticated ones.

### LINKED ISSUE #14465: Pivot tables fail in dashboards
The first half of [this video](https://share.getcloudapp.com/Z4uqW7GG) shows the problem.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #14447, Fixes #14465
Adds repro for #14465 and fixes that issue

### CODE REVIEW

File: frontend/src/metabase/services.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ export function maybeUsePivotEndpoint(
     card.display !== "pivot" ||
     !question.isStructured() ||
     // if we have metadata for the db, check if it supports pivots
-    !(question.database() && question.database().supportsPivots())
+    (question.database() && !question.database().supportsPivots())
```
Comment (paulrosenzweig) [inline frontend/src/metabase/services.js:78]: The comment was right, but my logic in the code didn't match.

File: frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js [hunk 2]
```diff
@@ -272,7 +273,9 @@ describe("scenarios > visualizations > pivot tables", () => {
             /Embed this (question|dashboard) in an application/,
           ).click();
           cy.findByText(test.subject);
-          assertOnPivotFields();
+          cy.get("iframe")
+            .its("0.contentDocument.body")
+            .within(assertOnPivotFields);
```
Comment (paulrosenzweig) [inline frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:278]: @nemanjaglumac Is there another way around this? I got the "0.contentDocument.body" part from [this blog post](https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/).

File: frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js [hunk 3]
```diff
@@ -263,7 +264,7 @@ describe("scenarios > visualizations > pivot tables", () => {
             .then($value => {
               cy.visit($value);
             });
-          cy.findByText(test.subject);
+          cy.findAllByText(test.subject); // the inspector only saw one, but findByText failed due to multiple elements
```
Comment (paulrosenzweig) [inline frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:267]: This flake was a mystery to me. I went back to the DOM snapshot in the Cypress UI and `contains` only found "pivot table dashboard" once, but `findByText` had failed because there were multiple elements.

File: frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js [hunk 4]
```diff
@@ -192,8 +192,9 @@ describe("scenarios > visualizations > pivot tables", () => {
     cy.findByText("Pivot tables can only be used with aggregated queries.");
   });
 
-  describe.skip("sharing (metabase#14447)", () => {
+  describe("sharing (metabase#14447)", () => {
     beforeEach(() => {
+      cy.viewport(1400, 800); // Row totals on embed preview was getting cut off at the normal width
```
Comment (paulrosenzweig) [inline frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:197]: This seemed easier than scrolling within the iframe.

File: frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js (hunk 3 above)
Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:267]: 😳

Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:267]: 😳

File: frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js (hunk 2 above)
Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:278]: Before I read the blog post - Why was this change needed in the first place? Was it failing with `iframe[0].src`?

Comment (paulrosenzweig) [reply frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:278]: I didn't read the blog post I just skimmed for that snippet haha. 

The failure was on the first assertion in `assertOnPivotFields`: `cy.findByText(/Users? → Source/)`. That was weird since it was clearly visible in the page.

Comment (paulrosenzweig) [reply frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:278]: Oh I missed the `iframe[0].src` part in next test. That approach would probably work in the embed preview one too. I'll push that change if it works.

Comment (paulrosenzweig) [reply frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:279]: I dug in a little more. I think we want to use both approaches, but I added comments to explain.

For published embeds we need to visit the src to ensure we don't use the preview endpoints. For previews we need to reach inside while it's still an iframe so that it does use the preview endpoints.

**Comment by nemanjaglumac** [comment]
Upon further inspection, I think that Cypress failure is a legitimate one. Please take a look at the following video:
https://share.getcloudapp.com/Z4uqW7GG

- Dashboard with the pivot table cannot render (Still waiting...)
- Cick sharing, then "Embed this dashboard" in an application
- It seems that it renders initially,
- But note that the timer runs in the tab title
- It then re-renders the whole iframe/page/preview
- The counter continues forever

**Comment by paulrosenzweig** [comment]
I ended up fixing #14465 on this branch as well since the fix was overlapping. That issue exposed that we didn't have any e2e coverage of pivot tables on dashboards so I added a test of that.

I also took a pass at fixing the embed preview test. I confirmed that we need to explicitly reach inside the iframe. Trying to find the elements otherwise will only look on the parent frame. I used another snippet from that blog post with more assertions. That should at least let us know why it flaked if it does. I'll rerun it a few times before merging.

**Comment by nemanjaglumac** [comment]
This keeps failing for me locally :/
It's intermittent and unpredictable, though.

If you're in a hurry to merge this, it's better if you skip these two tests.

File: frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js [hunk 5]
```diff
@@ -192,8 +193,52 @@ describe("scenarios > visualizations > pivot tables", () => {
...
+            }).then(() => {
+              cy.log("**--Open the dashboard--**");
+              cy.visit(`/dashboard/${DASHBOARD_ID}`);
+            });
+          });
+        });
+      });
+    });
+
+    it("should display a pivot table on a dashboard", () => {
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:234]:
```suggestion
    it("should display a pivot table on a dashboard (metabase#14465)", () => {
```

File: frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js [hunk 6]
```diff
@@ -192,8 +193,52 @@ describe("scenarios > visualizations > pivot tables", () => {
...
+                  col: 0,
+                  sizeX: 12,
+                  sizeY: 8,
+                },
+              ],
+            }).then(() => {
+              cy.log("**--Open the dashboard--**");
+              cy.visit(`/dashboard/${DASHBOARD_ID}`);
+            });
+          });
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:229]:
```suggestion
            });
            cy.log("**--Open the dashboard--**");
            cy.visit(`/dashboard/${DASHBOARD_ID}`);
          });
```

You don't actually need another promise here. This is all nested within the scope in which `DASHBOAD_ID` already exists.

**Review by ariya — APPROVED** [review]
LGTM :+1:
