### PR TITLE
only query for db-metadata once per sync operation + scan each table for its PKs

### LINKED ISSUE #26054: Snowflake sync is consuming more resources than necessary
**Describe the bug**
There are a few issues with Snowflake sync leading to unneeded credit consumption.

**To Reproduce**
1. Connect our Snowflake dev instance as a data source. Credentials [here](https://start.1password.com/open/i?a=AEO4BXOSHNFCJLK26XA7AD522E&v=fbhwdxcon6hj77du2c5cc7wvaa&i=kzp4a5bx4pnhv4z6pabmbn5awa&h=my.1password.com).
2. Wait for the automatic sync or trigger it manually.
3. Go to https://ls10467.us-east-2.aws.snowflakecomputing.com/console#/monitoring/queries to see query logs

**Identified issues**
1. describe-database: The heavy `SHOW OBJECTS IN DATABASE "v3_sample-dataset"` ran twice. After this query, we run `SELECT TRUE AS "_" FROM "v3_sample-dataset"."PUBLIC"."reviews" WHERE 1 <> 1 LIMIT 0` for each table, so these are also duplicated.
2. add-table-pks: Instead of getting primary keys for each table, we are running `show /* JDBC:DatabaseMetaData.getPrimaryKeys() */ primary keys in account`. This scans the entire account for primary keys. We should scan a single table or scan the database (not account) once.
3. describe-table: One of our users reported that instead of running `show /* JDBC:DatabaseMetaData.getColumns() */ columns in table "v3_sample-dataset"."PUBLIC"."reviews"` for each table, we are running `show /* JDBC:DatabaseMetaData.getColumns() */ columns in database "DB_NAME"` for each table (scanning the entire db multiple times). _I couldn't repro this._

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Tested on 44 and 45. The behavior on each version is a bit different, but the issues are the same.
- For reference, this user reported the `sync` task is taking 4.8 hours (`sync-fields` accounts for 3.5 hours and `sync-fks` for 1.1) 

**Severity**
P1 - it significantly increases costs for Snowflake users with larger databases.
Related to #24319 and #24862

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by escherize**
fixes #26054

# Part 1:

I've solved the excessive re-querying issue by querying for `db-metadata` up front, and passing the data into `sync-tables` and `metabase-metadata`.

```mermaid

graph TD
POST_:id/sync_schema --> api/write-check
POST_:id/sync_schema --> future
future --> sync-metadata/sync-db-metadata!
sync-metadata/sync-db-metadata! --> sync-operation
sync-operation --> timezone
sync-operation --> tables
sync-operation --> fields
sync-operation --> fks
sync-operation --> metabase-metadata

future --> analyze/analyze-db!

analyze/analyze-db! --> sync-operation2[sync-operation]
sync-operation2[sync-operation] --> fingerprint-fields
sync-operation2[sync-operation] --> classify-fields
sync-operation2[sync-operation] --> classify-tables


style tables color:#f22
style metabase-metadata color:#f22
```

`sync-tables` and `metabase-metadata` both call `describe-tables`, but we should only call it once for the sync operation.

---

# Part 2

The Snowflake JDBC driver ignores the table in `metadata.getPrimaryKeys(catalog, schema, table)`, unless `catalog` and `schema` are both passed.

Passing all 3 forces the Snowflake JDBC driver to issue the proper query. Here's a screenshot of the snowflake activity log:

Screen Shot 2022-12-01 at 3 33 56 PM

(For reference, this used to issue the query: `show primary keys in account;`).

---

# Part 3

I couldn't reproduce this, and didn't attempt a fix.

### CODE REVIEW

**Comment by escherize** [comment]
Not sure if 5 minutes is right here, but this will resolve both: redundant ❄️ queries, and the race condition.

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 1]
```diff
@@ -283,12 +284,12 @@
                                               (qp.store/fetch-and-store-database! (u/the-id database))
                                               (sql.qp/->honeysql driver table))]}))
 
-(defmethod driver/describe-database :snowflake
-  [driver database]
+(defn describe-database* [database]
```
Comment (metamben) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:287]: Might make sense to keep the `driver` parameter, so that drivers inheriting from snowflake can profit from it.

**Review by metamben — COMMENTED** [review]
Especially if consistency (i.e., that the table descriptions are equal) is important, wouldn't be better to make `sync-tables` and `metabase-metadata` get the result of `describe-tables` as input parameter? This solution feels more like a work around than a real fix.

**Comment by escherize** [comment]
I'll reopen this tomorrow

File: src/metabase/sync/sync_metadata.clj [hunk 2]
```diff
@@ -32,25 +33,26 @@
   (trs "Total number of foreign keys sync''d {0}, {1} updated and {2} tables failed to update"
        total-fks updated-fks total-failed))
 
-(def ^:private sync-steps
+(defn ^:private make-sync-steps [db-metadata]
```
Comment (metamben) [inline src/metabase/sync/sync_metadata.clj:36]:
```suggestion
(defn- make-sync-steps [db-metadata]
```

File: test/metabase/sync/util_test.clj [hunk 3]
```diff
@@ -54,9 +54,8 @@
         ;; make sure both of the futures have finished
         (deref f1)
         (deref f2)
-        ;; Check the number of syncs that took place. Should be 2 (just the first)
-        (is (= 2
-               @calls-to-describe-database))))))
+        ;; Check the number of syncs that took place. Should be 1 (just the first)
```
Comment (metamben) [inline test/metabase/sync/util_test.clj:57]: This comment is no more helpful than the actual check following it and I don't quite understand "just the first". I would remove the comment.

**Review by metamben — APPROVED** [review]
LGTM. My only concern is that making the `.getPrimaryKeys` calls with dbname and schema might break other drivers. If the tests pass, it's good, IMO.

**Review by luizarakaki — CHANGES_REQUESTED** [review]
@escherize It is now running the sync only once 🙌 , but I'm getting this exception when trying to sync FK
Using these [credentials](https://start.1password.com/open/i?a=AEO4BXOSHNFCJLK26XA7AD522E&v=fbhwdxcon6hj77du2c5cc7wvaa&i=kzp4a5bx4pnhv4z6pabmbn5awa&h=my.1password.com)

```
[backend] 2022-12-02 14:38:51,877 INFO sync.util :: STARTING: step 'sync-fields' for snowflake Database 5 'Snowflake Dev'
[backend] 2022-12-02 14:38:52,361 WARN sync.util :: Error syncing Fields for Table 'Table 92 'PUBLIC.TIMESTAMP_TEST''
[backend] clojure.lang.ArityException: Wrong number of args (2) passed to: metabase.driver.sql-jdbc.sync.describe-table/add-table-pks
```

**Review by luizarakaki — APPROVED** [review]
LGTM!

**Comment by escherize** [comment]
Once I get the `Oracle` test working, I'll go ahead and merge this.
