### PR TITLE
Harden insights

### LINKED ISSUE #12251: Query fails on "Error reducing result rows"
I found more information about the problem um the api response.
The data for questions is returned bu the error I mentioned, `Error reducing result rows`, is returned together. In the returned stack trace an 

Error on Api Response:
```
class clojure.lang.ExceptionInfo","error":"Error reducing result rows","stacktrace":["--> query_processor.context.default$default_reducef$fn__37780.invoke(default.clj:61)","query_processor.context.default$default_reducef.invokeStatic(default.clj:58)","query_processor.context.default$default_reducef.invoke(default.clj:49)","query_processor.context$reducef.invokeStatic(context.clj:69)"
``` 

Error on the result query status:
```
class java.lang.StackOverflowError","stacktrace":["clojure.lang.Numbers.isZero(Numbers.java:117)","--> sync.analyze.fingerprint.insights$change.invokeStatic(insights.clj:29)","sync.analyze.fingerprint.insights$change.invoke(insights.clj:26)","sync.analyze.fingerprint.insights$change.invokeStatic(insights.clj:35)","sync.analyze.fingerprint.insights$change.invoke(insights.clj:26)"
```

_Originally posted by @rjansen in https://github.com/metabase/metabase/issues/12228#issuecomment-608113217_

### PR DESCRIPTION
**Pull request by sbelak**
Wraps insights transducer in an error handling rf, preventing the entire QP failing on error. Fixes #12251.

### CODE REVIEW

File: test/metabase/sync/analyze/query_results_test.clj [hunk 1]
```diff
@@ -99,3 +104,19 @@
...
+        :breakout    [[:datetime-field [:field-id (data/id :checkins :date)] :month]]}
+       (mt/run-mbql-query checkins)
+       :data))
+
+(deftest error-resilience-test
+  (testing "Data should come back even if there is an error during fingerprinting"
+    (is (= 36 (with-redefs [fprint/earliest sync-test/crash-fn]
+                (-> (timeseries-dataset) :rows count)))))
+  (testing "Data should come back even if there is an error when calculating insights"
+    (testing "Data should come back even if there is an error during fingerprinting"
```
Comment (walterl) [inline test/metabase/sync/analyze/query_results_test.clj:120]: This line looks like a copy-and-paste leftover, and should probably be removed, right?

**Review by walterl — APPROVED** [review]
Just one superfluous line that needs nuking :+1:.
