### PR TITLE
Prevent coercion after nesting for all fields with coercion-strategy

### LINKED ISSUE #48721: Upgrading to v50 broke all queries that have summaries with custom expressions on unix timestamp columns
### Describe the bug

Seems like the upgrade to v50 broke all of our queries that have summaries with custom expressions on tables with timestamp columns for dates. 

Specifically what happens is that the FROM clause in the query converts the timestamp to date and assigns that as the "ts" field of the "source" alias, but then the SUM calculations perform another FROM_UNIXTIME conversion on that value, which will obviously fail. 

Converting the query to SQL and manually removing the extraneous FROM_UNIXTIME calls from all the SUM columns restores the original functionality, but this is not desirable. 

I tried manually adjusting the table's metadata in the admin settings and converting it from unix timestamp (seconds) to datetime, however this had no effect.

### To Reproduce

Upgrade Metabase to v50.

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-10-02",
      "tag": "v0.50.28",
      "hash": "3179ef2"
    },
    "settings": {
      "report-timezone": "Europe/Helsinki"
    },
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.13-MariaDB-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.214-202.855.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}

### Severity

Blocking the usage of Metabase entirely

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by metamben**
Fixes #48721

### Description

We started nesting queries in the QP that we hadn't nested before, but double coercion prevention was only implemented for field references with the `:temporal-unit` option. This PR prevents double coercion for any field with the `:coercion-strategy` option.

### How to verify

Use the steps from https://github.com/metabase/metabase/issues/48721#issuecomment-2486662090. The query should not blow up on this branch. The new unit test fails on `master` but passes on this branch.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/util/nest_query.clj [hunk 1]
```diff
@@ -134,9 +148,11 @@
     :expression
     (raise-source-query-expression-ref query &match)
 
-    ;; mark all Fields at the new top level as `:qp/ignore-coercion` so QP implementations know not to apply coercion or
-    ;; whatever to them a second time.
-    [:field _id-or-name (_opts :guard (every-pred :temporal-unit (complement :qp/ignore-coercion)))]
+    ;; Mark all Fields at the new top level as `:qp/ignore-coercion` so QP implementations know not to apply coercion
+    ;; or whatever to them a second time.
+    ;; In fact, we don't mark all Fields, only the ones we deem coercible. Marking all would make a bunch of tests
+    ;; fail, but it might still make sense. For example, #48721 would have been avoided by unconditional marking.
```
Comment (metamben) [inline src/metabase/query_processor/util/nest_query.clj:154]: @camsaul, would it be a bad idea to really add `:qp/ignore-coercion` to all field refs?

File: src/metabase/query_processor/util/nest_query.clj [hunk 2]
```diff
@@ -124,6 +124,20 @@
                 ::add/source-table  ::add/source
                 ::add/source-alias  source-alias))]))
 
+(defn- coerced-field?
+  [field-id]
+  (contains? (lib.metadata/field (qp.store/metadata-provider) field-id) :coercion-strategy))
```
Comment (bshepherdson) [inline src/metabase/query_processor/util/nest_query.clj:129]: Is it possible to get coercion strategies from anywhere else than proper Fields?

Eg. a custom expression, or more likely in the metadata for a model?

File: src/metabase/query_processor/util/nest_query.clj [hunk 3]
```diff
@@ -124,6 +124,20 @@
...
+
+(defn- coercible-field-ref?
+  [form]
+  (and (vector? form)
+       (let [[tag id-or-name opts] form]
+         (and (= tag :field)
+              (not (:qp/ignore-coercion opts))
+              (or (contains? opts :temporal-unit)
+                  (and (int? id-or-name)
+                       (coerced-field? id-or-name)))))))
```
Comment (bshepherdson) [inline src/metabase/query_processor/util/nest_query.clj:139]: This might be easier to read as a `lib.match/match-one`?

File: src/metabase/query_processor/util/nest_query.clj (hunk 1 above)
Comment (bshepherdson) [reply src/metabase/query_processor/util/nest_query.clj:154]: I think this is fine for now. This will get ported to MBQL lib and new refs in the middle term (< 6 months) and there are better ways to address this.

**Review by bshepherdson — APPROVED** [review]

File: src/metabase/query_processor/util/nest_query.clj (hunk 2 above)
Comment (metamben) [reply src/metabase/query_processor/util/nest_query.clj:129]: I think only fields can have coercion strategies.

File: src/metabase/query_processor/util/nest_query.clj (hunk 3 above)
Comment (metamben) [reply src/metabase/query_processor/util/nest_query.clj:139]: I did it this way to make sure the field lookup comes last.
