### PR TITLE
[Metrics V2] Port Legacy metric tests and fixes

### LINKED ISSUE #43093: Remove Query Processor legacy metric expansion and port legacy metric tests

### PR DESCRIPTION
**Pull request by snoe**
Fixes #43093

Errors fixed:
- Filters were being applied at stage -1 instead of 0 when splicing in compatible source-table metrics.
- When joining to a saved question that used a metric, a malli error would cause the preprocess to fail.

### CODE REVIEW

File: src/metabase/query_processor/middleware/expand_macros.clj [hunk 1]
```diff
@@ -97,7 +78,6 @@
    metadata-providerable :- ::lib.schema.metadata/metadata-providerable
    legacy-macro-ids      :- [:maybe [:set {:min 1} pos-int?]]]
   (let [metadata-type     (case macro-type
-                            :metric  :metadata/legacy-metric
                             :segment :metadata/segment)]
```
Comment (metamben) [inline src/metabase/query_processor/middleware/expand_macros.clj:81]: This will look quite surprising to the uninitiated.

File: test/metabase/query_processor/middleware/metrics_test.clj [hunk 2]
```diff
@@ -297,3 +326,99 @@
...
+    (let [[source-metric mp] (mock-metric (-> (lib/query meta/metadata-provider (meta/table-metadata :venues))
+                                              (lib/filter (lib/= (meta/field-metadata :venues :name) "abc"))
+                                              (lib/aggregate (lib/sum (meta/field-metadata :venues :price)))
+                                              (add-aggregation-options {:display-name "My Cool Aggregation"})))
+          {:keys [before after]} {:before {:source-table (meta/id :venues)
+                                           :aggregation  [[:metric (:id source-metric)]]}
+                                  :after  {:source-table (meta/id :venues)
+                                           :aggregation  [[:aggregation-options [:sum [:field (meta/id :venues :price) {}]]
+                                                           {:display-name "My Cool Aggregation"}]]
+                                           :filter       [:= [:field (meta/id :venues :name) {}] [:value "abc" {}]]}}
```
Comment (metamben) [inline test/metabase/query_processor/middleware/metrics_test.clj:386]: Why not just define `before` and `after` separately?

**Review by metamben — APPROVED** [review]
Nice!
