### PR TITLE
fix(sdk): handle relative urls for metabaseInstance in loading maps

### LINKED ISSUE #50132: GeoJSON asset file should follow the metabaseInstanceUrl when in embedding sdk
When the frontend loads the world.json asset file (example: https://shoppy.hosted.staging.metabase.com/app/assets/geojson/world.json) when loading maps, it should use a prefix following `metabaseInstanceUrl` when in the context of the embedding sdk. This allows users to use reverse proxying with Metabase.

How to reproduce with Vite:

```tsx
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {},
  },
  server: {
    proxy: {
      "/metabase-proxy/": {
        target: "http://localhost:3000/",
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/metabase-proxy/, ""),
      },
    },
  },
});
```

### PR DESCRIPTION
**Pull request by npretto**
Closes https://github.com/metabase/metabase/issues/50132

To reproduce the error (and check that it doesn't show up in this pr)

Make a new vite project with the following config to enable the proxy:
```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {},
  },
  server: {
    proxy: {
      "/metabase-proxy/": {
        target: "http://localhost:3000",
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/metabase-proxy/, ""),
      },
    },
  },
});
```

Use the following sdk config: (it should work with both, but will fail with `/metabase-proxy` without this fix)
```
  const config = defineEmbeddingSdkConfig({
    // metabaseInstanceUrl: "http://localhost:5173/metabase-proxy",
    metabaseInstanceUrl: "/metabase-proxy",
```

If using the example db, render `<StaticDashboard dashboardId={1} />` and open the Demographics tab, it should contain a map card

### CODE REVIEW

**Review by heypoom — APPROVED** [review]
I tested and this works great. Thanks!

Before: error is thrown because URL fails to construct.



After: the maps render correctly.

**Comment by WiNloSt** [comment]
This also fixes the [absolute path URL with Next JS reverse proxy issue](https://metaboat.slack.com/archives/C06FCQT0KMZ/p1731976803383909).

File: frontend/src/metabase/visualizations/components/ChoroplethMap.jsx [hunk 1]
```diff
@@ -110,10 +110,19 @@ const mapStateToProps = state => ({
 
 const connector = connect(mapStateToProps, null);
 
-function getMapUrl(details, props) {
+const addTrailingSlash = url => (url.endsWith("/") ? url : url + "/");
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/components/ChoroplethMap.jsx:113]: nit: A little misleading. This function only adds a trailing slash for URLs without it. And I might be worried to pass a URL with a trailing slash to this function.

I'd name this

```suggestion
const ensureTrailingSlash = url => (url.endsWith("/") ? url : url + "/");
```

**Review by WiNloSt — APPROVED** [review]
Looks good to me. Also tested with Next JS reverse proxy with absolute Metabase URL

File: frontend/src/metabase/visualizations/components/ChoroplethMap.jsx [hunk 2]
```diff
@@ -110,10 +110,19 @@ const mapStateToProps = state => ({
...
     if (props?.isSdk && props?.sdkMetabaseInstanceUrl) {
-      return new URL(details.url, props.sdkMetabaseInstanceUrl).href;
+      const baseUrl = new URL(
+        props.sdkMetabaseInstanceUrl,
+        window.location.origin,
+      ).href;
+
+      // if the second parameter ends with a slash, it will join them together
+      // new URL("/sub-path", "http://example.org/proxy/") => "http://example.org/proxy/sub-path"
+      return new URL(details.url, addTrailingSlash(baseUrl)).href;
```
Comment (npretto) [inline frontend/src/metabase/visualizations/components/ChoroplethMap.jsx:125]:
```suggestion
      return new URL(details.url, ensureTrailingSlash(baseUrl)).href;
```
