### PR TITLE
Fixing bad pulses when bad params exist

### LINKED ISSUE #30100: Subscriptions will fail when parameter doesn't exists
**Describe the bug**
If a dashboard had a parameter and it was configured in a subscription, then removing the parameter will break the subscription, and you won't be able to fix it so you'll have to recreate the subcription

**Logs**
<details>
```
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message
   "Input to defaulted-timezone does not match schema: \n\n\t   [(named (not (\"instance of a Card\" nil)) card)]  \n\n",
   :data
   {:type :schema.core/error,
    :schema [{:schema (pred "instance of a Card"), :optional? false, :name card}],
    :value [nil],
    :error [(named (not ("instance of a Card" nil)) card)]},
   :at [metabase.pulse$fn__97347$defaulted_timezone__97352 invoke "pulse.clj" 132]}],
 :trace
 [[metabase.pulse$fn__97347$defaulted_timezone__97352 invoke "pulse.clj" 132]
  [metabase.pulse$fn__97459 invokeStatic "pulse.clj" 333]
  [metabase.pulse$fn__97459 invoke "pulse.clj" 327]
  [clojure.lang.MultiFn invoke "MultiFn.java" 239]
  [metabase.pulse$results__GT_notifications$iter__97493__97497$fn__97498$fn__97499 invoke "pulse.clj" 390]
  [metabase.pulse$results__GT_notifications$iter__97493__97497$fn__97498 invoke "pulse.clj" 388]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5467 invokeStatic "core.clj" 139]
  [clojure.core$seq__5467 invoke "core.clj" 139]
  [metabase.pulse$send_notifications_BANG_ invokeStatic "pulse.clj" 510]
  [metabase.pulse$send_notifications_BANG_ invoke "pulse.clj" 509]
  [metabase.pulse$send_pulse_BANG_ invokeStatic "pulse.clj" 537]
  [metabase.pulse$send_pulse_BANG_ doInvoke "pulse.clj" 518]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [metabase.api.pulse$fn__98706 invokeStatic "pulse.clj" 328]
  [metabase.api.pulse$fn__98706 invoke "pulse.clj" 314]
  [compojure.core$wrap_response$fn__42375 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__42359 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__42364 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 151]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 152]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__87421 invoke "auth.clj" 17]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [compojure.core$make_context$handler__42415 invoke "core.clj" 290]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 300]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 199]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 199]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 199]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [metabase.api.routes$fn__99252$fn__99253 invoke "routes.clj" 62]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__99413$fn__99414 doInvoke "routes.clj" 70]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [compojure.core$make_context$handler__42415 invoke "core.clj" 290]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 300]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 199]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__95936 invoke "exceptions.clj" 103]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__95933 invoke "exceptions.clj" 91]
  [metabase.server.middleware.log$log_api_call$fn__102710$fn__102711$fn__102712 invoke "log.clj" 216]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
  [metabase.server.middleware.log$log_api_call$fn__102710$fn__102711 invoke "log.clj" 208]
  [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
  [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
  [metabase.server.middleware.log$log_api_call$fn__102710 invoke "log.clj" 207]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__109431 invoke "browser_cookie.clj" 42]
  [metabase.server.middleware.security$add_security_headers$fn__80250 invoke "security.clj" 153]
  [metabase.server.middleware.json$wrap_json_body$fn__106683 invoke "json.clj" 67]
  [metabase.server.middleware.offset_paging$handle_paging$fn__80274 invoke "offset_paging.clj" 45]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__106701 invoke "json.clj" 103]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__109698 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__109717 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__50479 invoke "misc.clj" 61]
  [metabase.server.middleware.session$reset_session_timeout$fn__63769 invoke "session.clj" 430]
  [metabase.server.middleware.session$bind_current_user$fn__63739$fn__63740 invoke "session.clj" 336]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 315]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 304]
  [metabase.server.middleware.session$bind_current_user$fn__63739 invoke "session.clj" 335]
  [metabase.server.middleware.session$wrap_current_user_info$fn__63721 invoke "session.clj" 285]
  [metabase.server.middleware.session$wrap_session_id$fn__63704 invoke "session.clj" 217]
  [metabase.server.middleware.auth$wrap_api_key$fn__87429 invoke "auth.clj" 30]
  [ring.middleware.cookies$wrap_cookies$fn__109618 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__50461 invoke "misc.clj" 29]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__50487 invoke "misc.clj" 78]
  [ring.middleware.gzip$wrap_gzip$fn__109660 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__50490 invoke "misc.clj" 95]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__109447 invoke "ssl.clj" 51]
  [metabase.server$async_proxy_handler$fn__101476 invoke "server.clj" 77]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
  [org.eclipse.jetty.server.Server handle "Server.java" 563]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$0 "HttpChannel.java" 505]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 762]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 497]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 282]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
  [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy runTask "AdaptiveExecutionStrategy.java" 416]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy consumeTask "AdaptiveExecutionStrategy.java" 385]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy tryProduce "AdaptiveExecutionStrategy.java" 272]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy lambda$new$0 "AdaptiveExecutionStrategy.java" 140]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 411]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 936]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1080]
  [java.lang.Thread run nil -1]],
 :cause
 "Input to defaulted-timezone does not match schema: \n\n\t   [(named (not (\"instance of a Card\" nil)) card)]  \n\n",
 :data
 {:type :schema.core/error,
  :schema [{:schema (pred "instance of a Card"), :optional? false, :name card}],
  :value [nil],
  :error [(named (not ("instance of a Card" nil)) card)]},
 :message
 "Input to defaulted-timezone does not match schema: \n\n\t   [(named (not (\"instance of a Card\" nil)) card)]  \n\n",
 :value [nil],
 :error [(named (not ("instance of a Card" nil)) card)]}
```
</details>

**To Reproduce**
1) create a gui question (e.g. people table)
2) add it to a dashboard
3) add a filter to the dashboard and connect it to the card (e.g. source column)
4) create a subscription, and add the "source" parameter  to the subscription (e.g. google), add yourself to the subscription and save it
5) now remove the filter
6) go to the subscription and try to send it, it will fail

**Expected behavior**
We should warn the person that deletes the filter that it's connected to a subscription and delete the subscription as well when a filter which is populated for a subscription gets deleted.

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Metabase version: 1.46.1
- Metabase hosting environment: Docker

**Severity**
P2

**Additional context**
NA

### PR DESCRIPTION
**Pull request by markbastian**
Previously, when a dashboard parameter was removed that was depended upon by a subscription, the subscription went into a broken state that was unfixable (the removed param was still attached to the notification but not visible in the UI for editing). Rather than remove that parameter, which could potentially lead to data leaks, we just archive the pulse.

Now, when a dashboard is saved that would break a pulse/subscription, we archive the pulse and send an email the the dashboard and pulse creators to notify them that the pulse has been removed. The email also contains which params were removed as well as a list of who will no longer be receiving the messages.

One code consideration when writing the query logic to determine the blast radius of the bad pulse was whether to write a large join query then reorganize the results or do N+1 queries starting from the pulse id (The logic requires hitting all of pulse, pulse channel, pulse channel recipients, and user tables). I started with a full join query along the lines of what is shown below, but opted for the N+1 query as broken pulses should be a very rare occurrence so readability was preferred over performance.

```clojure
  (let [parameter-ids ["a3d043d5"]]
    (when (seq parameter-ids)
      (t2/query
        (sql/format
          {:with   [[:params {:select [[:id]
                                       [[:raw "json_array_elements(parameters::json) ->> 'id'"]
                                        :parameter_id]]
                              :from   :pulse}]
                    [:pulse_ids {:select-distinct [[:id :pulse_id]]
                                 :where           [:in :parameter_id parameter-ids]
                                 :from            :params}]]
           :select [[:p.id :pulse_id]
                    [:pc.id :pulse_channel_id]
                    [:pcr.id :pulse_channel_recipient_id]
                    [:creator.first_name :creator_first_name]
                    [:creator.last_name :creator_last_name]
                    [:creator.email :creator_email]
                    [:recipient.first_name :recipient_first_name]
                    [:recipient.last_name :recipient_last_name]
                    [:recipient.email :recipient_email]]
           :from   [[:pulse :p]]
           :join   [:pulse_ids [:= :p.id :pulse_ids.pulse_id]
                    [:pulse_channel :pc] [:= :pc.pulse_id :p.id]
                    [:pulse_channel_recipient :pcr] [:= :pcr.pulse_channel_id :pc.id]
                    ;; Get the pulse creator
                    [:core_user :creator] [:= :creator.id :p.creator_id]
                    ;; Get the pulse recipient
                    [:core_user :recipient] [:= :recipient.id :pcr.user_id]]}))))
```

The new behavior can be easily tested with this ns:

```clojure
(ns tickets.30100-subscriptions-fail-no-param
  "Subscriptions will fail when parameter doesn't exists #30100
  https://github.com/metabase/metabase/issues/30100"
  (:require
    [clojure.test :refer :all]
    [metabase.api.dashboard-test :as dashboard-test]
    [metabase.test :as mt]))

(comment
  (let [param {:name "Source"
               :slug "source"
               :id   "_SOURCE_PARAM_ID_"
               :type :string/=}]
    (mt/dataset test-data
      (mt/with-temp
        [:model/Card {card-id :id
                      query   :dataset_query} {:name          "Native card"
                                               :database_id   (mt/id)
                                               :dataset_query {:database (mt/id)
                                                               :type     :query
                                                               :query    {:source-table (mt/id :people)
                                                                          :limit        5
                                                                          :fields       [[:field (mt/id :people :id)
                                                                                          {:base-type :type/BigInteger}]
                                                                                         [:field (mt/id :people :name)
                                                                                          {:base-type :type/Text}]
                                                                                         [:field (mt/id :people :source)
                                                                                          {:base-type :type/Text}]]}}
                                               :dataset       true}
         :model/Dashboard {dash-id :id} {:name       "My Awesome Dashboard"
                                         :parameters [param]}
         :model/DashboardCard {dash-card-id :id} {:dashboard_id       dash-id
                                                  :card_id            card-id
                                                  :parameter_mappings [{:parameter_id "_SOURCE_PARAM_ID_"
                                                                        :card_id      card-id
                                                                        :target       [:dimension
                                                                                       [:field (mt/id :people :source)
                                                                                        {:base-type :type/Text}]]
                                                                        }]}
         :model/Pulse {bad-slack-pulse-id :id} {:name         "Bad Slack Pulse"
                                                :dashboard_id dash-id
                                                :creator_id   (mt/user->id :trashbird)
                                                :parameters   [(assoc param :value ["LinkedIn"])]}
         :model/PulseCard _ {:pulse_id          bad-slack-pulse-id
                             :card_id           card-id
                             :dashboard_card_id dash-card-id}
         :model/PulseChannel {bad-slack-pulse-channel-id :id} {:channel_type :slack
                                                               :pulse_id     bad-slack-pulse-id
                                                               :details      {:channel "#my-channel"}
                                                               :enabled      true}
         :model/Pulse {pulse-id :id :as pulse} {:name         "Test Pulse"
                                                :dashboard_id dash-id
                                                :creator_id   (mt/user->id :trashbird)
                                                :parameters   [(assoc param :value ["Twitter", "Facebook"])
                                                               {:name "Froob"
                                                                :slug "froob"
                                                                :id   "_FROOB_PARAM_ID_"
                                                                :type :string/=
                                                                :value Math/PI}]}
         :model/PulseCard _ {:pulse_id          pulse-id
                             :card_id           card-id
                             :dashboard_card_id dash-card-id}
         :model/PulseChannel {pulse-channel-id :id} {:channel_type :email
                                                     :pulse_id     pulse-id
                                                     :enabled      true}
         :model/PulseChannelRecipient _ {:pulse_channel_id pulse-channel-id
                                         :user_id          (mt/user->id :rasta)}
         :model/PulseChannelRecipient _ {:pulse_channel_id pulse-channel-id
                                         :user_id          (mt/user->id :crowberto)}]
        (#'dashboard-test/dashboard-response
          (mt/user-http-request :rasta :put 200 (str "dashboard/" dash-id)
                                {:parameters []}))))))

```

Fixes #30100

### CODE REVIEW

File: src/metabase/api/dashboard.clj [hunk 1]
```diff
@@ -598,13 +600,90 @@
...
+  - The users affected by the pulse"
+  [{bad-pulse-id :id pulse-name :name :keys [parameters creator_id]}]
+  (let [creator                  (t2/select-one [:model/User :first_name :last_name :email] creator_id)
+        pulse-channel-ids        (mapv :id (t2/select [:model/PulseChannel :id] :pulse_id [:= bad-pulse-id]))
+        ;; When checks are defensive as in () causes SQL exceptions
+        pulse-channel-recipients (when (seq pulse-channel-ids)
+                                   (t2/select :model/PulseChannelRecipient :pulse_channel_id [:in pulse-channel-ids]))
+        affected-users           (when (seq pulse-channel-recipients)
+                                   (t2/select [:model/User :first_name :last_name :email]
+                                     :id [:in (map :user_id pulse-channel-recipients)]))]
```
Comment (adam-james-v) [inline src/metabase/api/dashboard.clj:619]: can we send pulses to emails that are not associated with a user? I ask because if we can do that, I then wonder if it's possible that `(map :user_id pulse-channel-recipients)` is an empty seq. If so, the defensive `when` might still break in such a case?

File: src/metabase/api/dashboard.clj [hunk 2]
```diff
@@ -623,7 +702,8 @@
                                    :present #{:description :position :width :collection_id :collection_position :cache_ttl}
                                    :non-nil #{:name :parameters :caveats :points_of_interest :show_in_getting_started :enable_embedding
                                               :embedding_params :archived :auto_apply_filters}))]
-              (t2/update! Dashboard id updates))
+              (t2/update! Dashboard id updates)
+              (handle-broken-subscriptions id original-params))
```
Comment (adam-james-v) [inline src/metabase/api/dashboard.clj:706]: Should we conditionally `handle-broken-subscriptions` only when `:parameters` change? Or do we effectively get a no-op if no parameters change already?

**Review by adam-james-v — APPROVED** [review]
Looks good to me, just a few non-blocking questions I had. :)

File: src/metabase/api/dashboard.clj (hunk 1 above)
Comment (markbastian) [reply src/metabase/api/dashboard.clj]: At this point, we just send the user name or slack channel if they are affected, so I think we're good to go. If the seq returns nil, the email will just not contain a list of users affected, but the owners will still be notified.

File: src/metabase/api/dashboard.clj (hunk 2 above)
Comment (markbastian) [reply src/metabase/api/dashboard.clj]: Done.
