### PR TITLE
Fix pie chart legend issues

### LINKED ISSUE #29597: We add hyphens on the series on narrow viewports
**Describe the bug**
We seem to add hypens next to the series on narrow viewports.
image

but those are not in wider viewports
image

**Logs**
NA

**To Reproduce**
1) create a pie chart, see the legend
2) change the dimensions to iPhone XR, see the legend

**Expected behavior**
Keep the legend the same

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop OS LTS
- Metabase version: master

**Severity**
P3

**Additional context**
NA

### LINKED ISSUE #46213: Legend labels on pie charts on dashboards where the legend is below the pie and the percentage is on the wedge have an extraneous dash
### Describe the bug

If you make a pie chart really long on a dashboard so the legend is below the pie, and you set the percentages to show on the pie chart, the legend will have an extraneous dash like, "Pie - "

image

### To Reproduce

1.  Create a pie chart
2. Put it on a dash
3. Make the pie chart card really long so the legend is below piet
4. Marvel at the legend being below the pie
5. Set the pie chart display settings to have the percentage on the chart

### Expected behavior

There should not be a dash

### Logs

_No response_

### Information about your Metabase installation

```JSON
Built on 2024-07-26

Hash: f27d115
```

### Severity

It doesn't look great, but it works

### Additional context

See example at https://stats.metabase.com/dashboard/2546

### LINKED ISSUE #48125: pie chart legend is aggressively truncated
### Describe the bug

Screenshot 2024-09-25 at 2 07 32 PM

When percentages are shown on the legend of the pie chart, the dimension names are truncated so aggressively you can't really read them.

### To Reproduce

1. Create any pie chart question (e.g. count of orders by product category)
2. Enable show percentages "in legend" or "both" setting

### Expected behavior

If there's enough space, the whole dimension name and percentage in the legend show be shown. If there isn't enough space, the dimension name should be truncated, but only the end.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Stats commit 2173e65
```

### Severity

Makes the pie chart difficult to use, since you need to be able to read the dimension names from the legend since they aren't on the chart itself

### Additional context

_No response_

### LINKED ISSUE #49779: When you rename pie chart segments, the labels are truncated until you save or change settings
### Describe the bug

When you rename pie chart segments, the labels are truncated until you save or change settings.  This would lead me to not use this visualization or rename the wedges as it looks terrible

### To Reproduce

1.  I created a question using sample data:  Join Products to Order and summarize count by product category
2. I relabeled the pie slices with longer labels
3. Notice how they look truncating

Image

After saving, the page refreshes and it looks fine.  In real life though, I wouldn't save, I would just change the chart type or rename the labels to be smaller.

Loom  https://www.loom.com/share/03e7df71af334a2e864da2bd94eba777?sid=e722b6ab-90a5-44ec-85ae-ebe7e3df3043

### Expected behavior

If we need to refresh to show it, we should refresh

### Logs

_No response_

### Information about your Metabase installation

```JSON
master, Built on 2024-11-07

Hash: 5669cb0
```

### Severity

It would prevent me from using this new feature

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/48125
Closes https://github.com/metabase/metabase/issues/49779
Closes https://github.com/metabase/metabase/issues/46213
Closes https://github.com/metabase/metabase/issues/29597

### Description

The existing PieChart legend has a few bugs and it gets reported internally frequently enough. This PR addresses a few issues related to it.

#### 1. Agressive truncation logic without further resizing

Screenshot 2024-11-15 at 8 28 26 PM

If a chart is initially rendered within dimensions that require truncating legend items they won't expand after resizing.
This is due to a [very old code](https://github.com/metabase/metabase/pull/50116/files#diff-fe909f84350014a57230560476960418653079c031c6c92a2c0159eaa84acdbfL26) that explicitly prevents legend with from changing unless legend items change. I assume this is to preserve the exact legend total width when toggling percentages in legend and this behavior does not seem valuable because it would be actually nice to resize the legend instead of truncating its items.

#### 2. Agressive truncation logic without further resizing

Hide legend fully on tiny dashcards where it is not useful.

Before
<video src="https://github.com/user-attachments/assets/ab369b6f-60c7-4a0d-8724-d98c4518770c" />

After
<video src="https://github.com/user-attachments/assets/e9e406c4-5798-4a8c-ab7a-c7864c97b9e6" />

#### 3. Drop hyphens on horizontal legend

Before
Screenshot 2024-11-15 at 8 49 01 PM

After
Screenshot 2024-11-15 at 8 48 53 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/ChartWithLegend.jsx [hunk 1]
```diff
@@ -59,14 +61,11 @@ class ChartWithLegend extends Component {
     const isHorizontal = gridSize.width > gridSize.height / GRID_ASPECT_RATIO;
     if (showLegend === false) {
       type = "small";
-    } else if (
-      !gridSize ||
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/ChartWithLegend.jsx:63]: `gridSize` always exists because we set it on line 48

File: frontend/src/metabase/visualizations/components/ChartWithLegend.jsx [hunk 2]
```diff
@@ -59,14 +61,11 @@ class ChartWithLegend extends Component {
...
-      (isHorizontal &&
-        (showLegend || gridSize.width > 4 || gridSize.height > 4))
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/ChartWithLegend.jsx:65]: `showLegend` is redundant since it is always `true` here and below

**Review by ranquild — APPROVED** [review]
