### PR TITLE
Remove regionid from Snowflake config

### LINKED ISSUE #10142: Snowflake Connector Requires Deprecated Region Id
**Expected behaviour:**
Account name is entered as described in the  [Account name details section here](https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#connection-parameters).
Login is successful

**Actual Behaviour:**
Account name is entered as described in the  [Account name details section here](https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#connection-parameters).
Login fails with the error "DEBUG metabase.middleware.log :: POST /api/database 400 2 s (0 DB calls) {:valid false, :dbname "net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver not able to connect to Snowflake. Error code: 390100, Message: Incorrect username or password was specified..""

**Problem:**
Region Id is now deprecated in Snowflake JDBC connections as per [the Snowflake documentation](https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#connection-parameters)

The Snowflake database connector dialog asks for a separate Region Id field. In order to successfully connect, account name and region Id need to be entered in the deprecated manner.

**Solution:**
At the very least the dialogue should allow successful connection when account name is entered as per the  [Account name details section here](https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#connection-parameters)
Better still the deprecated Region ID should be removed and users guided to use the Snowflake account name guidance.

**Note**
The [code in the driver](https://github.com/metabase/metabase/blob/master/modules/drivers/snowflake/src/metabase/driver/snowflake.clj) appears to try to solve it with this:

`  (let [host (if regionid
               (str account "." regionid)
               account)]
`

but using the driver dialog, it doesn't seem to work. 
Unfortunately my Clojure is not up to debugging it - although I wondered if the display-name: Region ID from the YAML file is getting used when nothing is entered in that field?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by jeff303**
Remove regionid from plugin YAML file

Add new driver multimethod to normalize db-details, and implementing to handle this particular "migration" within Snowflake

Adding hook from database model post-select to invoke the new multi

Adding test

### CODE REVIEW

File: src/metabase/models/database.clj [hunk 1]
```diff
@@ -49,9 +49,12 @@
     (schedule-tasks! database)))
 
 (defn- post-select [{driver :engine, :as database}]
-  ;; TODO - this is only really needed for API responses. This should be a `hydrate` thing instead!
   (cond-> database
-    (driver/initialized? driver) (assoc :features (driver.u/features driver))))
+    (driver/initialized? driver)
+    ;; TODO - this is only really needed for API responses. This should be a `hydrate` thing instead!
+    (assoc :features (driver.u/features driver))
+    (get-method driver/normalize-db-details driver)
```
Comment (jeff303) [inline src/metabase/models/database.clj:56]: @camsaul , not sure if this is what you meant, in terms of normalizing.

I put it in post-select since the hook already existed, and we want the UI to be populated with the updated values coming out of the DB (which presumably also overwrite the existing values on save, thereby removing the `:regionid` key).

It doesn't seem quite optimal, though, since this will run on **every** select.  I suppose the only way to prevent that would be to write a Clojure migration?

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 2]
```diff
@@ -42,16 +43,13 @@
   :sunday)
 
 (defmethod sql-jdbc.conn/connection-details->spec :snowflake
-  [_ {:keys [account regionid], :as opts}]
-  (let [host (if regionid
-               (str account "." regionid)
-               account)
-        upcase-not-nil (fn [s] (when s (u/upper-case-en s)))]
+  [_ {:keys [account], :as opts}]
```
Comment (dpsutton) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:46]: why aren't you doing the normalizing here. What's the point of having the separate defmethod rather than doing it here?

File: src/metabase/models/database.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/models/database.clj:56]: Oh i see why you did it this way. I'd add a `:default` implementation that just returned the details rather than optionally calling this or not.

**Review by dpsutton — APPROVED** [review]

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj (hunk 2 above)
Comment (jeff303) [reply modules/drivers/snowflake/src/metabase/driver/snowflake.clj:46]: This was at Cam's initial suggestion, but happy to go either way.

Comment (dpsutton) [reply modules/drivers/snowflake/src/metabase/driver/snowflake.clj:46]: Fair enough. Roll with it

File: src/metabase/models/database.clj (hunk 1 above)
Comment (jeff303) [reply src/metabase/models/database.clj:56]: Ah yeah, that's better.  Will make the change.

Comment (jeff303) [reply src/metabase/models/database.clj]: Implementation note (for posterity): @camsaul  had suggested using the `:types` facility of Toucan do to this work.  However, I opted to add it here instead, because:

- `:details` is already type `:encrypted-json`, which has its own `:out` handling going on (to decrypt the JSON), so that would need to be changed to perform this additional step (and possibly change the semantics of that field type)
- this `post-select` fn was already in place, I'm just changing the initial value that is threaded through

Still, if there is a cleaner way, I'm open to it.

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj (hunk 2 above)
Comment (camsaul) [reply modules/drivers/snowflake/src/metabase/driver/snowflake.clj:46]: @dpsutton, that's a totally valid point. 

I think the only situation where adding a new `normalize-db-details` method would be useful would be if we needed the transformation to apply to other places the details are used as well. AFAIK the only other place we use DB details is in the Edit Database page in the admin panel. 

In this case it looks like we actually want to append region id to `:account` itself, and that _should_ be something visible in the admin Edit Database page, so the `normalize-db-details` method seems appropriate.

If I'm reading the code wrong and the changes don't actually need to affect the admin page then I agree with Dan, we should just do the normalization in `connection-details->spec` and skip adding the new method

File: src/metabase/models/database.clj [hunk 3]
```diff
@@ -49,9 +49,12 @@
...
 
 (defn- post-select [{driver :engine, :as database}]
-  ;; TODO - this is only really needed for API responses. This should be a `hydrate` thing instead!
   (cond-> database
-    (driver/initialized? driver) (assoc :features (driver.u/features driver))))
+    (driver/initialized? driver)
+    ;; TODO - this is only really needed for API responses. This should be a `hydrate` thing instead!
+    (as-> db* ; database from outer cond->
+        (assoc db* :features (driver.u/features driver))
+        (driver/normalize-db-details driver db*))))
```
Comment (camsaul) [inline src/metabase/models/database.clj:57]: You should probably only call `normalize-db-details` if the DB has the `:details` map... it's possible that we're fetching DB without `:details` and the various impls of the multimethod shouldn't have to deal with that situation

File: src/metabase/driver.clj [hunk 4]
```diff
@@ -602,3 +602,18 @@
...
   dispatch-on-uninitialized-driver
   :hierarchy #'hierarchy)
+
+(defmulti normalize-db-details
+  "Normalizes db-details for the given driver. This is to handle migrations that are too difficult to perform via
+  regular Liquibase queries. This multimethod will be called from a `:post-select` handler within the database model.
+  The full `database` model object is passed as the 2nd parameter, and the multimethod implementation is expected to
+  update the value for `:details`. The default implementation is essentially `identity` (i.e returns `db-details`
+  unchanged)."
+  {:added "0.40.0" :arglists '([driver db-details])}
```
Comment (camsaul) [inline src/metabase/driver.clj:612]: 0.41.0?

Comment (camsaul) [reply src/metabase/driver.clj:612]: > The full `database` model object is passed as the 2nd parameter

The arglist has `db-details` as the second parameter

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj [hunk 5]
```diff
@@ -178,3 +178,13 @@
...
+
+(deftest normalize-test
+  (mt/test-driver :snowflake
+    (testing "details should be normalized coming out of the DB"
+      (mt/with-temp Database [db {:name    "Legacy Snowflake DB"
+                                  :engine  :snowflake,
+                                  :details {:account  "my-instance"
+                                            :regionid "us-west-1"}}]
+                             (is (= {:account "my-instance.us-west-1"}
+                                   (:details db)))))))
```
Comment (camsaul) [inline modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj:190]: this should be indented 2 spaces e.g. the same way you'd indent the body of a `let` or `with-open` form

**Review by camsaul — APPROVED** [review]
This LGTM other than the notes I left about the new method's arglists having the wrong parameter name and the weird indentation in one spot

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj (hunk 2 above)
Comment (jeff303) [reply modules/drivers/snowflake/src/metabase/driver/snowflake.clj:46]: Yeah, so in this case, the changes should definitely affect the admin page, **and** other pages.

- When we render the DB edit page, the `regionid` field is simply gone, so its value will need to have been migrated over to `account`, so that it will be appended there on save.
- Even if the user never actually saves it again, the `:regionid` is still gone, and the connection functions are no longer trying to find it in the details map.  Thus, to maintain consistency between what the connectivity code uses, and what the user might see on the admin screen, it should still be "normalized" even for connections.

Given this, I suppose the conclusion stands to have the multimethod.

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj (hunk 5 above)
Comment (jeff303) [reply modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj]: Fixed.

File: src/metabase/driver.clj (hunk 4 above)
Comment (jeff303) [reply src/metabase/driver.clj]: Fixed both.

File: src/metabase/models/database.clj (hunk 3 above)
Comment (jeff303) [reply src/metabase/models/database.clj]: Fixed.
