### PR TITLE
[Blocker] Fix optional parameter handling in action forms

### LINKED ISSUE #28982: Action forms with all optional parameters don't work correctly
**Describe the bug**
If an action has parameters that are all optional, the form is initially disabled until you edit a parameter.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create an action with at least one parameter, e.g. `UPDATE PRODUCTS SET CATEGORY = CATEGORY WHERE CATEGORY = {{category}}`. Make this parameter optional and save the action.
2. Click on the run button.
3. The submit button would be disabled despite all parameters being optional.

**Workaround**
Click in any input, type a character and remove it.

**Expected behavior**
The submit should be enabled after opening the form.

**Screenshots/videos**
Screenshot 2023-03-07 at 14 18 45

**Information about your Metabase Installation:**

46 RC2

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/28982
Demo https://www.loom.com/share/25ac0e50fddf44e685de796cf3b09e9d
Depends on `action-blank-param` branch

Changes:
- **Allows optional values to be cleared and submitted in basic action forms**
- Allow to set `Default value` only for required fields, like it's done in the QB
- Make the default value user-visible - previously because of wrong form initialization it didn't work
- Allow to submit the form if all missing parameters are optional

How to test:
- New -> Action
- Add a few parameters and make them all optional
- Make sure it is possible to run the action without providing any values from the model detail page

Screenshot 2023-03-08 at 21 15 04

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29049)

### CODE REVIEW

File: frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx [hunk 1]
```diff
@@ -154,37 +159,28 @@ export const ActionForm = ({
...
-              disabled={!dirty && hasFormFields}
-              title={submitTitle ?? t`Submit`}
-              {...submitButtonVariant}
-            />
-          </ActionFormButtonContainer>
-
-          <FormErrorMessage />
-        </Form>
-      )}
+      <Form role="form" data-testid="action-form">
```
Comment (ranquild) [inline frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx:169]: Removed `dirty` check

File: frontend/src/metabase/actions/components/ActionForm/utils.ts [hunk 2]
```diff
@@ -96,46 +97,46 @@ export const getForm = (
...
 
       if (fieldSetting.required) {
-        yupType = yupType.required(requiredMessage);
-      } else {
-        yupType = yupType.nullable();
-      }
-
-      if (!isEmpty(fieldSetting.defaultValue)) {
-        yupType = yupType.default(fieldSetting.defaultValue);
+        yupType = yupType.required(Errors.required);
```
Comment (ranquild) [inline frontend/src/metabase/actions/components/ActionForm/utils.ts:139]: Use the same error message for missing required fields we use elsewhere

File: frontend/src/metabase/actions/components/ActionForm/ActionFormFieldWidget.tsx [hunk 3]
```diff
@@ -41,5 +41,5 @@ export const FormFieldWidget = forwardRef(function FormFieldWidget(
   const Widget =
     (formField.type ? WIDGETS[formField.type] : FormInputWidget) ??
     FormInputWidget;
-  return <Widget {...formField} nullable={formField.optional} ref={ref} />;
+  return <Widget {...formField} nullable ref={ref} />;
```
Comment (ranquild) [inline frontend/src/metabase/actions/components/ActionForm/ActionFormFieldWidget.tsx:44]: `nullable` means that empty values are converted to `null`. It's different to a field being required/optional.

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.tsx [hunk 4]
```diff
@@ -189,19 +189,19 @@ function RequiredInput({
         <RequiredToggleLabel htmlFor="is-required">{t`Required`}</RequiredToggleLabel>
         <Toggle
           id="is-required"
-          value={!!value}
-          onChange={required => onChange({ required, defaultValue })}
+          value={value}
+          onChange={required => onChange({ required })}
```
Comment (ranquild) [inline frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.tsx:193]: Use the same pattern we use in QB - drop the default value when `required` flag is changed. This removes a lot of weird issues we have to deal with, like setting the default value only for required fields.

Comment (kulyk) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.tsx:193]: It doesn't seem like we cover the `defaultValue` reset in unit tests; mind adding a test for it / changing an existing one?

File: frontend/src/metabase/public/containers/PublicAction/PublicAction.unit.spec.tsx [hunk 5]
```diff
@@ -104,9 +104,9 @@ describe("PublicAction", () => {
     expect(screen.getByRole("button", { name: "Submit" })).toBeInTheDocument();
   });
 
-  it("doesn't let to submit a clean form", async () => {
+  it("should allow to submit a clean form if all parameters are optional", async () => {
     await setup();
-    expect(screen.getByRole("button", { name: "Submit" })).toBeDisabled();
+    expect(screen.getByRole("button", { name: "Submit" })).toBeEnabled();
   });
```
Comment (kulyk) [inline frontend/src/metabase/public/containers/PublicAction/PublicAction.unit.spec.tsx:110]: Should we still test if the button is disabled if there's at least one required parameter without a value yet?

File: frontend/src/metabase/actions/components/ActionForm/ActionFormFieldWidget.tsx (hunk 3 above)
Comment (kulyk) [reply frontend/src/metabase/actions/components/ActionForm/ActionFormFieldWidget.tsx:44]: @iethree I remember some shenanigans about nullable/optional action parameters, mind double-checking this?

File: frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx (hunk 1 above)
Comment (kulyk) [reply frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx:168]: I know it's not something this PR is doing, but doesn't `Form` have a `role="form"` out of the box?

Comment (kulyk) [reply frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx:168]: Also, should we better check for `isValid` for the `disabled` prop?

File: frontend/src/metabase/actions/components/ActionForm/ActionForm.unit.spec.tsx [hunk 6]
```diff
@@ -338,13 +336,11 @@ describe("Actions > ActionForm", () => {
...
 
-      expect(
-        await screen.findByText(/this field is required/i),
-      ).toBeInTheDocument();
+      expect(await screen.findByText(/required/i)).toBeInTheDocument();
       expect(onSubmit).not.toHaveBeenCalled();
     });
 
-    it("disables form submission when no fields are changed", async () => {
+    it("allows form submission when all fields are optional", async () => {
```
Comment (kulyk) [inline frontend/src/metabase/actions/components/ActionForm/ActionForm.unit.spec.tsx:343]: Should we also add a test checking that submit is disabled if there's at least one parameter without a value yet?

**Review by kulyk — APPROVED** [review]
Looks and works great! Have a few thoughts about tests, apart from that it's good to go I think

File: frontend/src/metabase/actions/components/ActionForm/ActionFormFieldWidget.tsx (hunk 3 above)
Comment (ranquild) [reply frontend/src/metabase/actions/components/ActionForm/ActionFormFieldWidget.tsx:44]: https://metaboat.slack.com/archives/C04FG88HL95/p1678369078943209

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.tsx (hunk 4 above)
Comment (ranquild) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.tsx:193]: Modified the existing test for that

File: frontend/src/metabase/actions/components/ActionForm/ActionFormFieldWidget.tsx (hunk 3 above)
Comment (ranquild) [reply frontend/src/metabase/actions/components/ActionForm/ActionFormFieldWidget.tsx:44]: long story short, we had to change the backend to be able to always send `null` for empty parameter values

File: frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx]: the form itself and the submit button are disabled when the form is invalid. Or are you talking about something else?

Comment (ranquild) [reply frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx]: removed `role="form"` btw - there is a native form underneath, it's not needed

Comment (kulyk) [reply frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx]: > the form itself and the submit button are disabled when the form is invalid. Or are you talking about something else?

Hm, I think I've seen we used `isValid` somewhere for the `disabled` prop, maybe I got confused 🤔

File: src/metabase/actions/execution.clj [hunk 7]
```diff
@@ -114,37 +114,39 @@
         extra-parameters         (set/difference (set (keys request-parameters))
                                                  (set (keys slug->field-name)))
         pk-field                 (first pk-fields)
-        simple-parameters        (update-keys request-parameters (comp keyword slug->field-name))
+        simple-parameters        (->> (update-keys request-parameters (comp keyword slug->field-name))
```
Comment (dpsutton) [inline src/metabase/actions/execution.clj:117]: Trying to understand this change. The gist is that we want optional parameters to be honored: the action can work and optional params that aren't supplied work. I would have guessed that the implementation would allow for parameters with null values and the optional values spliced in. I'm surprised to see them stripped from the `simple-parameters` map here. I'm not sure I understand the implications of one versus the other.

Comment (ranquild) [reply src/metabase/actions/execution.clj:117]: I want to clarify this. There was a FE bug (fixed in this PR) where no values were sent for fields not changed by the user in **basic** action forms, and that's how they previously work. If you type a character into an optional field and remove it, the FE sends `null`, which is handled differently by the backend, and sometimes leads to errors. This change on the backend makes it work the same way with if the parameter is not send or if `null` is send, which totally makes sense for optional parameters in implicit actions. So in other words - this PR is not changing the execution behavior, it just simplifies/fixes the frontend by sending `null` in all cases, and lets the backend handle that case (in the same way the frontend did before).

Comment (tsmacdonald) [reply src/metabase/actions/execution.clj:117]: To Dan's point, this change makes it no longer possible for an action to set a non-null value to null. But I don't see how the backend can be smarter about it: if it receives `{favorite_color: null}` there's no way to know if the user no longer has a favorite color or if it just happens that nothing was selected in the FE's color-picker.

I think the real way around this is to do a more major overhaul and let users configure which columns they care about, populate the form with existing values, etc.

Comment (tsmacdonald) [reply src/metabase/actions/execution.clj:117]: (@dpsutton @ranquild )

**Comment by tsmacdonald** [comment]
@ranquild could you cherry-pick this commit with a BE unit test? https://github.com/metabase/metabase/commit/8d689f7cba4671437e602a710ca758a5d121cd1b

**Comment by ranquild** [comment]
@tsmacdonald I'd rather do it in a separate PR. I've been re-trying broken tests for the 5th time now, hopefully it's the last one

**Comment by tsmacdonald** [comment]
@ranquild I'm not thrilled about code going into master without unit tests. It'll need a :heavy_check_mark: from a backender as well

**Comment by ranquild** [comment]
@tsmacdonald pushed the test. Could you ask for reviews in the team channel? 🙏

**Comment by tsmacdonald** [comment]
Slack discussion: https://metaboat.slack.com/archives/C04FG88HL95/p1678466672494759

File: src/metabase/actions/execution.clj [hunk 8]
```diff
@@ -114,37 +114,39 @@
...
         pk-field-name            (keyword (:name pk-field))
         row-parameters           (cond-> simple-parameters
                                    (not= implicit-action :row/create) (dissoc pk-field-name))
         requires_pk              (contains? #{:row/delete :row/update} implicit-action)]
     (api/check (or (not requires_pk)
                    (some? (get simple-parameters pk-field-name)))
-               400
-               (tru "Missing primary key parameter: {0}"
-                    (pr-str (u/slugify (:name pk-field)))))
+      400
```
Comment (qnkhuat) [inline src/metabase/actions/execution.clj:126]: the previous indentaitno is correct.

File: src/metabase/actions/execution.clj [hunk 9]
```diff
@@ -114,37 +114,39 @@
         extra-parameters         (set/difference (set (keys request-parameters))
                                                  (set (keys slug->field-name)))
         pk-field                 (first pk-fields)
-        simple-parameters        (update-keys request-parameters (comp keyword slug->field-name))
+        simple-parameters        (->> (update-keys request-parameters (comp keyword slug->field-name))
+                                      (filter (fn [[_k v]] (some? v)))
```
Comment (qnkhuat) [inline src/metabase/actions/execution.clj:118]: we probably should have a comment explaining this here.

File: test/metabase/api/action_test.clj [hunk 10]
```diff
@@ -522,3 +522,18 @@
                                         :post 400
                                         (format "action/%s/execute" action-id)
                                         {:parameters {:id 1 :name "European"}})))))))))
+
+(deftest parameter-stripping-test
```
Comment (qnkhuat) [inline test/metabase/api/action_test.clj:526]:
```suggestion
(deftest parameter-ignore-test
```

ignores feel like a better suited word

**Review by qnkhuat — APPROVED** [review]
Approving but we should create an issue to address this https://github.com/metabase/metabase/pull/29049/files#r1133605016

File: src/metabase/actions/execution.clj (hunk 9 above)
Comment (tsmacdonald) [reply src/metabase/actions/execution.clj:120]: @qnkhuat done

**Comment by tsmacdonald** [comment]
@qnkhuat issue created #29159
