### PR TITLE
Short circuit on sync error

### LINKED ISSUE #51683: Field Values must short circuit on sync ending errors
### Describe the bug

Syncing field values does not short circuit on errors which indicate a sync job has no hope of completing.

Background: 
We've seen a _ton_ of snowflake logs logging that they must use MFA and that it cannot get a connection.
https://github.com/snowflakedb/snowflake-jdbc/blob/master/src/main/java/net/snowflake/client/core/SessionUtil.java#L743-L746

This happens a lot when c3p0 is trying to get us a connection in https://github.com/swaldman/c3p0/blob/0.10.x/src/com/mchange/v2/c3p0/impl/C3P0PooledConnectionPool.java#L901

We are _flooding_ with logs. As a short term effort we are turning off this log hitting us, but that means we are still doing a _ton_ of work that has no hope of succeeding. So let's not do the work.

We have some abort retry logic in mb.sync.util:

```clojure
(doseq [klass [java.net.ConnectException
               java.net.NoRouteToHostException
               java.net.UnknownHostException
               com.mchange.v2.resourcepool.CannotAcquireResourceException
               javax.net.ssl.SSLHandshakeException]]
  (derive klass ::exception-class-not-to-retry))

(defn- do-not-retry-exception? [e]
  (or (isa? (class e) ::exception-class-not-to-retry)
      (some-> (ex-cause e) recur)))
```

And this _does_ register the error that is thrown in this pathway:

```clojure
util=> (do-not-retry-exception?
         (com.mchange.v2.sql.SqlUtils/toSQLException
           "Connections could not be qcquired from the underlying database!"
           "08001"
           (com.mchange.v2.resourcepool.CannotAcquireResourceException.)))
true
```

And we can even add a test that this is true:

```clojure
(deftest ^:parallel error-handling-test
  (testing "A ConnectException will cause sync to stop"
    (mt/dataset time-test-data
      (doseq [error [(java.io.IOException.
                      "outer"
                      (java.net.ConnectException.
                       "inner, this one triggers the failure"))
                     ;; this is what c3p0 throws in checkoutPooledConnection
                     (SqlUtils/toSQLException "Connections could not be qcquired from the underlying database!"
                                              "08001"
                                              (CannotAcquireResourceException.))]]
        (let [expected           error
              actual             (sync-util/sync-operation ::sync-error-handling (mt/db) "sync error handling test"
                                                           (sync-util/run-sync-operation
                                                            "sync"
                                                            (mt/db)
                                                            [(sync-util/create-sync-step "failure-step"
                                                                                         (fn [_]
                                                                                           (throw expected)))
                                                             (sync-util/create-sync-step "should-not-run"
                                                                                         (fn [_]
                                                                                           {}))]))
              [step-name result] (first (:steps actual))]
          (is (= 1 (count (:steps actual))))
          (is (= "failure-step" step-name))
          (is (= {:throwable expected :log-summary-fn nil}
                 (dissoc result :start-time :end-time))))))))

,,,
util-test=> (clojure.test/run-test error-handling-test)

Testing metabase.sync.util-test

Ran 1 tests containing 6 assertions.
0 failures, 0 errors.
{:test 1, :pass 6, :fail 0, :error 0, :type :summary}
```

However, this machinery does not help us when running the field values task that runs in sync database task.

If we update `create-or-update-full-field-values!` to 

```clojure
(throw (com.mchange.v2.sql.SqlUtils/toSQLException
         "Connections could not be qcquired from the underlying database!"
         "08001"
         (com.mchange.v2.resourcepool.CannotAcquireResourceException.)))
```

We would hope that we hit this error _once_. But that is not the case

```clojure
sync-databases=> (let [database (t2/select-one :model/Database :id 1)]
                   (sync.field-values/update-field-values! database))
{:start-time ""
 :end-time ""
 :steps [["delete-expired-advanced-field-values"
          {:deleted 0}]
         ["update-field-values"
          {:errors 24, :created 0, :updated 0, :deleted 0}]]}
```

And this means we have no hope of succeeding, we hit this error 24 times instead of once. We are doing work repeatedly that we know and can classify as futile.

### To Reproduce

The actual pathway that our customers are hitting is to have snowflake connected, and then add MFA to the account and watch it fail.

A simple way locally is to modify `metabase.models.field-values/create-or-update-full-field-values!` to throw 

```clojure
    (throw (com.mchange.v2.sql.SqlUtils/toSQLException "Connections could not be qcquired from the underlying database!"
                                    "08001"
                                    (com.mchange.v2.resourcepool.CannotAcquireResourceException.)))
```

And then sync the sample database. Note there is some logic about inactive fields in `metabase.sync.field-values/update-field-values-for-field!` that checks `(field-values/inactive? field-values)` and i commented that out so it would always hit the `field-values/create-or-update-full-field-values!` branch.

### Expected behavior

One of these errors should stop the rest of the sync job.

For instance, the current output is 

```clojure
{:start-time ""
 :end-time ""
 :steps [["delete-expired-advanced-field-values"
          {:deleted 0}]
         ["update-field-values"
          {:errors 24, :created 0, :updated 0, :deleted 0}]]}
```

There seem to be multiple ways to fix this:
- there's lots of error insulation on the field values. It does addition and is careful to catch exceptions so that it can add numbers, using 0 on a swallowed error. Putting the `com.mchange.v2.sql.SqlUtils/toSQLException` trick in various places of syncing fields doesn't work because of lots of opaque error handling.

```clojure
sync-databases=> (let [database (t2/select-one :model/Database :id 1)]
                   (f (sync-metadata/sync-db-metadata! database)))
{:steps [["sync-dbms-version"
          {:flavor "H2",
           :version "2.1.214 (2022-06-13)",
           :semantic-version [2 1]}]
         ["sync-timezone" {:timezone-id "UTC"}]
         ["sync-tables" {:updated-tables 0, :total-tables 8}]
         ["sync-fields"
          {:throwable #object[java.sql.SQLException
                              "0x13146d4e"
                              "java.sql.SQLException: Connections could not be qcquired from the underlying database!"]}]]}
```

Here is successfully stops syncing when i put the exception at the right level. Note i had to turn error checking off because the type it expects does not handle an error. And at that point the error returned actually is _not_ interruptible. Note here that the sync fields step is the last step because the `:throwable` key aborts the remaining steps.

```clojure
(mu/defn sync-fields! #_#_ :- [:map
                          [:updated-fields ms/IntGreaterThanOrEqualToZero]
                          [:total-fields   ms/IntGreaterThanOrEqualToZero]]
  "Sync the Fields in the Metabase application database for all the Tables in a `database`."
  [database :- i/DatabaseInstance]
  (sync-util/with-error-handling (format "Error syncing Fields for Database ''%s''" (sync-util/name-for-logging database))
    (throw (doto (com.mchange.v2.sql.SqlUtils/toSQLException "Connections could not be qcquired from the underlying database!"
                                                        "08001"
                                                        (com.mchange.v2.resourcepool.CannotAcquireResourceException.))
             (.setStackTrace (into-array StackTraceElement []))))
```

If I leave the type checking in, I get the following error

```clojure
{:steps [["sync-dbms-version"
          {:flavor "H2",
           :version "2.1.214 (2022-06-13)",
           :semantic-version [2 1]}]
         ["sync-timezone" {:timezone-id "UTC"}]
         ["sync-tables" {:updated-tables 0, :total-tables 8}]
         ["sync-fields"
          {:throwable #object[clojure.lang.ExceptionInfo
                              "0x79aa5272"
                              "clojure.lang.ExceptionInfo: Invalid output: [\"invalid type, got: #error {\\n :cause \\\"\\\"\\n :via\\n [{:type java.sql.SQLException\\n   :message \\\"Connections could not be qcquired from the underlying database!\\\"}\\n  {:type com.mchange.v2.resourcepool.CannotAcquireResourceException\\n   :message \\\"\\\"\\n   :at [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \\\"fields.clj\\\" 76]}]\\n :trace\\n [[metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \\\"fields.clj\\\" 76]\\n  [metabase.sync.util$do_with_error_handling invokeStatic \\\"util.clj\\\" 191]\\n  [metabase.sync.util$do_with_error_handling invoke \\\"util.clj\\\" 184]\\n  [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460 invoke \\\"fields.clj\\\" 76]\\n  [metabase.sync.sync_metadata.fields$fn__3613459$fn__3613474 invoke \\\"fields.clj\\\" 71]\\n  [clojure.lang.AFn applyToHelper \\\"AFn.java\\\" 154]\\n  [clojure.lang.AFn applyTo \\\"AFn.java\\\" 144]\\n  [clojure.core$apply invokeStatic \\\"core.clj\\\" 669]\\n  [clojure.core$apply invoke \\\"core.clj\\\" 662]\\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047$fn__3613050 invoke \\\"util.clj\\\" 495]\\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \\\"task_history.clj\\\" 122]\\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \\\"task_history.clj\\\" 110]\\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047 doInvoke \\\"util.clj\\\" 488]\\n  [clojure.lang.RestFn invoke \\\"RestFn.java\\\" 400]\\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \\\"util.clj\\\" 132]\\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \\\"util.clj\\\" 126]\\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invokeStatic \\\"util.clj\\\" 150]\\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invoke \\\"util.clj\\\" 146]\\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045 invoke \\\"util.clj\\\" 482]\\n  [metabase.sync.util$fn__3613043$fn__3613058 invoke \\\"util.clj\\\" 477]\\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111$fn__3613119 invoke \\\"util.clj\\\" 577]\\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111 invoke \\\"util.clj\\\" 575]\\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \\\"task_history.clj\\\" 122]\\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \\\"task_history.clj\\\" 110]\\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110 invoke \\\"util.clj\\\" 572]\\n  [metabase.sync.util$fn__3613109$fn__3613129 invoke \\\"util.clj\\\" 567]\\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455$fn__141456 invoke \\\"sync_metadata.clj\\\" 70]\\n  [metabase.sync.util$do_with_error_handling invokeStatic \\\"util.clj\\\" 191]\\n  [metabase.sync.util$do_with_error_handling invoke \\\"util.clj\\\" 184]\\n  [clojure.core$partial$fn__5929 invoke \\\"core.clj\\\" 2647]\\n  [metabase.driver$eval89685$fn__89686 invoke \\\"driver.clj\\\" 910]\\n  [clojure.lang.MultiFn invoke \\\"MultiFn.java\\\" 239]\\n  [metabase.sync.util$sync_in_context$fn__3612917 invoke \\\"util.clj\\\" 167]\\n  [metabase.sync.util$with_db_logging_disabled$fn__3612914 invoke \\\"util.clj\\\" 159]\\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \\\"util.clj\\\" 132]\\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \\\"util.clj\\\" 126
]\\n  [metabase.sync.util$with_start_and_finish_logging$fn__3612897 invoke \\\"util.clj\\\" 144]\\n  [metabase.sync.util$fn__3612884$with_sync_events3612883__3612885$fn__3612889 invoke \\\"util.clj\\\" 118]\\n  [metabase.sync.util$with_duplicate_ops_prevented$fn__3612871 invoke \\\"util.clj\\\" 90]\\n  [metabase.sync.util$fn__3612939$do_sync_operation3612938__3612940 invoke \\\"util.clj\\\" 216]\\n  [metabase.sync.util$fn__3612939$fn__3612942 invoke \\\"util.clj\\\" 210]\\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455 invoke \\\"sync_metadata.clj\\\" 68]\\n  [metabase.sync.sync_metadata$fn__141454$fn__141459 invoke \\\"sync_metadata.clj\\\" 65]\\n  [metabase.task.sync_databases$eval3613486 invokeStatic \\\"NO_SOURCE_FILE\\\" 636]\\n  [metabase.task.sync_databases$eval3613486 invoke \\\"NO_SOURCE_FILE\\\" 635]\\n  [clojure.lang.Compiler eval \\\"Compiler.java\\\" 7700]\\n  [clojure.lang.Compiler eval \\\"Compiler.java\\\" 7655]\\n  [clojure.core$eval invokeStatic \\\"core.clj\\\" 3232]\\n  [clojure.core$eval invoke \\\"core.clj\\\" 3228]\\n  [user$eval3444021$fn__3444024 invoke \\\"NO_SOURCE_FILE\\\" 8]\\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \\\"main.clj\\\" 437]\\n  [clojure.main$repl$read_eval_print__9244 invoke \\\"main.clj\\\" 437]\\n  [clojure.main$repl$fn__9253 invoke \\\"main.clj\\\" 459]\\n  [clojure.main$repl invokeStatic \\\"main.clj\\\" 459]\\n  [clojure.main$repl doInvoke \\\"main.clj\\\" 368]\\n  [clojure.lang.RestFn invoke \\\"RestFn.java\\\" 622]\\n  [user$eval3444021 invokeStatic \\\"NO_SOURCE_FILE\\\" 6]\\n  [user$eval3444021 invoke \\\"NO_SOURCE_FILE\\\" 6]\\n  [clojure.lang.Compiler eval \\\"Compiler.java\\\" 7700]\\n  [clojure.lang.Compiler eval \\\"Compiler.java\\\" 7655]\\n  [clojure.core$eval invokeStatic \\\"core.clj\\\" 3232]\\n  [clojure.core$eval invoke \\\"core.clj\\\" 3228]\\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \\\"main.clj\\\" 437]\\n  [clojure.main$repl$read_eval_print__9244 invoke \\\"main.clj\\\" 437]\\n  [clojure.main$repl$fn__9253 invoke \\\"main.clj\\\" 459]\\n  [clojure.main$repl invokeStatic \\\"main.clj\\\" 459]\\n  [clojure.core.server$repl invokeStatic \\\"server.clj\\\" 183]\\n  [clojure.core.server$repl invoke \\\"server.clj\\\" 183]\\n  [clojure.lang.AFn applyToHelper \\\"AFn.java\\\" 152]\\n  [clojure.lang.AFn applyTo \\\"AFn.java\\\" 144]\\n  [clojure.lang.Var applyTo \\\"Var.java\\\" 707]\\n  [clojure.core$apply invokeStatic \\\"core.clj\\\" 667]\\n  [clojure.core.server$accept_connection invokeStatic \\\"server.clj\\\" 74]\\n  [clojure.core.server$start_server$fn__9040$fn__9041$fn__9043 invoke \\\"server.clj\\\" 118]\\n  [clojure.lang.AFn run \\\"AFn.java\\\" 22]\\n  [java.lang.Thread run \\\"Thread.java\\\" 1583]]}\"] {:type :metabase.util.malli.fn/invalid-output, :error {:schema [:map [:updated-fields [:int {:min 0, :description #metabase.util.i18n.UserLocalizedString{:format-string \"value must be an integer greater than zero.\", :args [], :pluralization-opts {}}, :error/fn #object[clojure.core$constantly$fn__5759 0x1a42a52d \"clojure.core$constantly$fn__5759@1a42a52d\"]}]] [:total-fields [:int {:min 0, :description #metabase.util.i18n.UserLocalizedString{:format-string \"value must be an integer greater than zero.\", :args [], :pluralization-opts {}}, :error/fn #object[clojure.core$constantly$fn__5759 0x1a42a52d \"clojure.core$constantly$fn__5759@1a42a52d\"]}]]], :value #error {\n :cause \"\"\n :via\n [{:type java.sql.SQLException\n   :message \"Connections could not be qcquired from the underlying database!\"}\n  {:type com.mchange.v2.resourcepool.CannotAcquireResourceException\n   :message \"\"\n   :at [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \"fields.clj\" 76]}]\n :trace\n [[metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \"fields.clj\" 76]\n  [metabase.sync.util$do_with_error_handling invokeStatic \"util.clj\" 191]\n  [metabase.sync.util$do_with_error_handling invoke \"util.clj\" 
184]\n  [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460 invoke \"fields.clj\" 76]\n  [metabase.sync.sync_metadata.fields$fn__3613459$fn__3613474 invoke \"fields.clj\" 71]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 154]\n  [clojure.lang.AFn applyTo \"AFn.java\" 144]\n  [clojure.core$apply invokeStatic \"core.clj\" 669]\n  [clojure.core$apply invoke \"core.clj\" 662]\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047$fn__3613050 invoke \"util.clj\" 495]\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \"task_history.clj\" 122]\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \"task_history.clj\" 110]\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047 doInvoke \"util.clj\" 488]\n  [clojure.lang.RestFn invoke \"RestFn.java\" 400]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \"util.clj\" 132]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \"util.clj\" 126]\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invokeStatic \"util.clj\" 150]\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invoke \"util.clj\" 146]\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045 invoke \"util.clj\" 482]\n  [metabase.sync.util$fn__3613043$fn__3613058 invoke \"util.clj\" 477]\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111$fn__3613119 invoke \"util.clj\" 577]\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111 invoke \"util.clj\" 575]\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \"task_history.clj\" 122]\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \"task_history.clj\" 110]\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110 invoke \"util.clj\" 572]\n  [metabase.sync.util$fn__3613109$fn__3613129 invoke \"util.clj\" 567]\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455$fn__141456 invoke \"sync_metadata.clj\" 70]\n  [metabase.sync.util$do_with_error_handling invokeStatic \"util.clj\" 191]\n  [metabase.sync.util$do_with_error_handling invoke \"util.clj\" 184]\n  [clojure.core$partial$fn__5929 invoke \"core.clj\" 2647]\n  [metabase.driver$eval89685$fn__89686 invoke \"driver.clj\" 910]\n  [clojure.lang.MultiFn invoke \"MultiFn.java\" 239]\n  [metabase.sync.util$sync_in_context$fn__3612917 invoke \"util.clj\" 167]\n  [metabase.sync.util$with_db_logging_disabled$fn__3612914 invoke \"util.clj\" 159]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \"util.clj\" 132]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \"util.clj\" 126]\n  [metabase.sync.util$with_start_and_finish_logging$fn__3612897 invoke \"util.clj\" 144]\n  [metabase.sync.util$fn__3612884$with_sync_events3612883__3612885$fn__3612889 invoke \"util.clj\" 118]\n  [metabase.sync.util$with_duplicate_ops_prevented$fn__3612871 invoke \"util.clj\" 90]\n  [metabase.sync.util$fn__3612939$do_sync_operation3612938__3612940 invoke \"util.clj\" 216]\n  [metabase.sync.util$fn__3612939$fn__3612942 invoke \"util.clj\" 210]\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455 invoke \"sync_metadata.clj\" 68]\n  [metabase.sync.sync_metadata$fn__141454$fn__141459 invoke \"sync_metadata.clj\" 65]\n  [metabase.task.sync_databases$eval3613486 invokeStatic \"NO_SOURCE_FILE\" 636]\n  [metabase.task.sync_databases$eval3613486 invoke \"NO_SOURCE_FILE\" 635]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7700]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7655]\n  [clojure.core$eval invokeStatic \"core.clj\" 3232]\n  [clojure.core$eval invoke \"core.clj\" 3228]\n  [user$eval3444021$fn__3444024 invoke \"NO_SOURCE_FILE\" 8]\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \"main.clj\" 437]\n  [clojure.main$repl$read_eval_print__9244 invoke \"main.clj\" 437]\n  [clojure.main$repl$fn__9253 invoke \"main.clj\" 459]\n  [clojure.main$repl
 invokeStatic \"main.clj\" 459]\n  [clojure.main$repl doInvoke \"main.clj\" 368]\n  [clojure.lang.RestFn invoke \"RestFn.java\" 622]\n  [user$eval3444021 invokeStatic \"NO_SOURCE_FILE\" 6]\n  [user$eval3444021 invoke \"NO_SOURCE_FILE\" 6]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7700]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7655]\n  [clojure.core$eval invokeStatic \"core.clj\" 3232]\n  [clojure.core$eval invoke \"core.clj\" 3228]\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \"main.clj\" 437]\n  [clojure.main$repl$read_eval_print__9244 invoke \"main.clj\" 437]\n  [clojure.main$repl$fn__9253 invoke \"main.clj\" 459]\n  [clojure.main$repl invokeStatic \"main.clj\" 459]\n  [clojure.core.server$repl invokeStatic \"server.clj\" 183]\n  [clojure.core.server$repl invoke \"server.clj\" 183]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 152]\n  [clojure.lang.AFn applyTo \"AFn.java\" 144]\n  [clojure.lang.Var applyTo \"Var.java\" 707]\n  [clojure.core$apply invokeStatic \"core.clj\" 667]\n  [clojure.core.server$accept_connection invokeStatic \"server.clj\" 74]\n  [clojure.core.server$start_server$fn__9040$fn__9041$fn__9043 invoke \"server.clj\" 118]\n  [clojure.lang.AFn run \"AFn.java\" 22]\n  [java.lang.Thread run \"Thread.java\" 1583]]}, :errors ({:path [], :in [], :schema [:map [:updated-fields [:int {:min 0, :description #metabase.util.i18n.UserLocalizedString{:format-string \"value must be an integer greater than zero.\", :args [], :pluralization-opts {}}, :error/fn #object[clojure.core$constantly$fn__5759 0x1a42a52d \"clojure.core$constantly$fn__5759@1a42a52d\"]}]] [:total-fields [:int {:min 0, :description #metabase.util.i18n.UserLocalizedString{:format-string \"value must be an integer greater than zero.\", :args [], :pluralization-opts {}}, :error/fn #object[clojure.core$constantly$fn__5759 0x1a42a52d \"clojure.core$constantly$fn__5759@1a42a52d\"]}]]], :value #error {\n :cause \"\"\n :via\n [{:type java.sql.SQLException\n   :message \"Connections could not be qcquired from the underlying database!\"}\n  {:type com.mchange.v2.resourcepool.CannotAcquireResourceException\n   :message \"\"\n   :at [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \"fields.clj\" 76]}]\n :trace\n [[metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \"fields.clj\" 76]\n  [metabase.sync.util$do_with_error_handling invokeStatic \"util.clj\" 191]\n  [metabase.sync.util$do_with_error_handling invoke \"util.clj\" 184]\n  [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460 invoke \"fields.clj\" 76]\n  [metabase.sync.sync_metadata.fields$fn__3613459$fn__3613474 invoke \"fields.clj\" 71]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 154]\n  [clojure.lang.AFn applyTo \"AFn.java\" 144]\n  [clojure.core$apply invokeStatic \"core.clj\" 669]\n  [clojure.core$apply invoke \"core.clj\" 662]\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047$fn__3613050 invoke \"util.clj\" 495]\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \"task_history.clj\" 122]\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \"task_history.clj\" 110]\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047 doInvoke \"util.clj\" 488]\n  [clojure.lang.RestFn invoke \"RestFn.java\" 400]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \"util.clj\" 132]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \"util.clj\" 126]\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invokeStatic \"util.clj\" 150]\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invoke \"util.clj\" 146]\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045 invoke \"util.clj\" 482]\n  [metabase.sync.util$fn__3613043$fn__3613058 invoke \"util.clj\" 477]\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111$fn__3613119 invoke \"util.clj\" 577]\n 
 [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111 invoke \"util.clj\" 575]\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \"task_history.clj\" 122]\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \"task_history.clj\" 110]\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110 invoke \"util.clj\" 572]\n  [metabase.sync.util$fn__3613109$fn__3613129 invoke \"util.clj\" 567]\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455$fn__141456 invoke \"sync_metadata.clj\" 70]\n  [metabase.sync.util$do_with_error_handling invokeStatic \"util.clj\" 191]\n  [metabase.sync.util$do_with_error_handling invoke \"util.clj\" 184]\n  [clojure.core$partial$fn__5929 invoke \"core.clj\" 2647]\n  [metabase.driver$eval89685$fn__89686 invoke \"driver.clj\" 910]\n  [clojure.lang.MultiFn invoke \"MultiFn.java\" 239]\n  [metabase.sync.util$sync_in_context$fn__3612917 invoke \"util.clj\" 167]\n  [metabase.sync.util$with_db_logging_disabled$fn__3612914 invoke \"util.clj\" 159]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \"util.clj\" 132]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \"util.clj\" 126]\n  [metabase.sync.util$with_start_and_finish_logging$fn__3612897 invoke \"util.clj\" 144]\n  [metabase.sync.util$fn__3612884$with_sync_events3612883__3612885$fn__3612889 invoke \"util.clj\" 118]\n  [metabase.sync.util$with_duplicate_ops_prevented$fn__3612871 invoke \"util.clj\" 90]\n  [metabase.sync.util$fn__3612939$do_sync_operation3612938__3612940 invoke \"util.clj\" 216]\n  [metabase.sync.util$fn__3612939$fn__3612942 invoke \"util.clj\" 210]\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455 invoke \"sync_metadata.clj\" 68]\n  [metabase.sync.sync_metadata$fn__141454$fn__141459 invoke \"sync_metadata.clj\" 65]\n  [metabase.task.sync_databases$eval3613486 invokeStatic \"NO_SOURCE_FILE\" 636]\n  [metabase.task.sync_databases$eval3613486 invoke \"NO_SOURCE_FILE\" 635]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7700]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7655]\n  [clojure.core$eval invokeStatic \"core.clj\" 3232]\n  [clojure.core$eval invoke \"core.clj\" 3228]\n  [user$eval3444021$fn__3444024 invoke \"NO_SOURCE_FILE\" 8]\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \"main.clj\" 437]\n  [clojure.main$repl$read_eval_print__9244 invoke \"main.clj\" 437]\n  [clojure.main$repl$fn__9253 invoke \"main.clj\" 459]\n  [clojure.main$repl invokeStatic \"main.clj\" 459]\n  [clojure.main$repl doInvoke \"main.clj\" 368]\n  [clojure.lang.RestFn invoke \"RestFn.java\" 622]\n  [user$eval3444021 invokeStatic \"NO_SOURCE_FILE\" 6]\n  [user$eval3444021 invoke \"NO_SOURCE_FILE\" 6]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7700]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7655]\n  [clojure.core$eval invokeStatic \"core.clj\" 3232]\n  [clojure.core$eval invoke \"core.clj\" 3228]\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \"main.clj\" 437]\n  [clojure.main$repl$read_eval_print__9244 invoke \"main.clj\" 437]\n  [clojure.main$repl$fn__9253 invoke \"main.clj\" 459]\n  [clojure.main$repl invokeStatic \"main.clj\" 459]\n  [clojure.core.server$repl invokeStatic \"server.clj\" 183]\n  [clojure.core.server$repl invoke \"server.clj\" 183]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 152]\n  [clojure.lang.AFn applyTo \"AFn.java\" 144]\n  [clojure.lang.Var applyTo \"Var.java\" 707]\n  [clojure.core$apply invokeStatic \"core.clj\" 667]\n  [clojure.core.server$accept_connection invokeStatic \"server.clj\" 74]\n  [clojure.core.server$start_server$fn__9040$fn__9041$fn__9043 invoke \"server.clj\" 118]\n  [clojure.lang.AFn run \"AFn.java\" 22]\n  [java.lang.Thread run \"Thread.java\" 1583]]}, :type :malli.core/invalid-type})}, :humanized [\"invalid type, got: #error {\\n :cause \\\"\\\"\\n :via\\n [{:type java.sql.SQLException\\n   :message \\\"Connections could not be qcquired from the underlying database!\\\"}\\n  {:type com.mchange.v2.res
ourcepool.CannotAcquireResourceException\\n   :message \\\"\\\"\\n   :at [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \\\"fields.clj\\\" 76]}]\\n :trace\\n [[metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \\\"fields.clj\\\" 76]\\n  [metabase.sync.util$do_with_error_handling invokeStatic \\\"util.clj\\\" 191]\\n  [metabase.sync.util$do_with_error_handling invoke \\\"util.clj\\\" 184]\\n  [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460 invoke \\\"fields.clj\\\" 76]\\n  [metabase.sync.sync_metadata.fields$fn__3613459$fn__3613474 invoke \\\"fields.clj\\\" 71]\\n  [clojure.lang.AFn applyToHelper \\\"AFn.java\\\" 154]\\n  [clojure.lang.AFn applyTo \\\"AFn.java\\\" 144]\\n  [clojure.core$apply invokeStatic \\\"core.clj\\\" 669]\\n  [clojure.core$apply invoke \\\"core.clj\\\" 662]\\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047$fn__3613050 invoke \\\"util.clj\\\" 495]\\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \\\"task_history.clj\\\" 122]\\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \\\"task_history.clj\\\" 110]\\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047 doInvoke \\\"util.clj\\\" 488]\\n  [clojure.lang.RestFn invoke \\\"RestFn.java\\\" 400]\\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \\\"util.clj\\\" 132]\\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \\\"util.clj\\\" 126]\\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invokeStatic \\\"util.clj\\\" 150]\\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invoke \\\"util.clj\\\" 146]\\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045 invoke \\\"util.clj\\\" 482]\\n  [metabase.sync.util$fn__3613043$fn__3613058 invoke \\\"util.clj\\\" 477]\\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111$fn__3613119 invoke \\\"util.clj\\\" 577]\\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111 invoke \\\"util.clj\\\" 575]\\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \\\"task_history.clj\\\" 122]\\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \\\"task_history.clj\\\" 110]\\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110 invoke \\\"util.clj\\\" 572]\\n  [metabase.sync.util$fn__3613109$fn__3613129 invoke \\\"util.clj\\\" 567]\\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455$fn__141456 invoke \\\"sync_metadata.clj\\\" 70]\\n  [metabase.sync.util$do_with_error_handling invokeStatic \\\"util.clj\\\" 191]\\n  [metabase.sync.util$do_with_error_handling invoke \\\"util.clj\\\" 184]\\n  [clojure.core$partial$fn__5929 invoke \\\"core.clj\\\" 2647]\\n  [metabase.driver$eval89685$fn__89686 invoke \\\"driver.clj\\\" 910]\\n  [clojure.lang.MultiFn invoke \\\"MultiFn.java\\\" 239]\\n  [metabase.sync.util$sync_in_context$fn__3612917 invoke \\\"util.clj\\\" 167]\\n  [metabase.sync.util$with_db_logging_disabled$fn__3612914 invoke \\\"util.clj\\\" 159]\\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \\\"util.clj\\\" 132]\\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \\\"util.clj\\\" 126]\\n  [metabase.sync.util$with_start_and_finish_logging$fn__3612897 invoke \\\"util.clj\\\" 144]\\n  [metabase.sync.util$fn__3612884$with_sync_events3612883__3612885$fn__3612889 invoke \\\"util.clj\\\" 118]\\n  [metabase.sync.util$with_duplicate_ops_prevented$fn__3612871 invoke \\\"util.clj\\\" 90]\\n  [metabase.sync.util$fn__3612939$do_sync_operation3612938__3612940 invoke \\\"util.clj\\\" 216]\\n  [metabase.sync.util$fn__3612939$fn__3612942 invoke \\\"util.clj\\\" 210]\\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455 invoke \\\"sync_metadata.clj\\\" 68]\\n  [metabase.sync.sync_metadata$fn__141454$fn__141459 inv
oke \\\"sync_metadata.clj\\\" 65]\\n  [metabase.task.sync_databases$eval3613486 invokeStatic \\\"NO_SOURCE_FILE\\\" 636]\\n  [metabase.task.sync_databases$eval3613486 invoke \\\"NO_SOURCE_FILE\\\" 635]\\n  [clojure.lang.Compiler eval \\\"Compiler.java\\\" 7700]\\n  [clojure.lang.Compiler eval \\\"Compiler.java\\\" 7655]\\n  [clojure.core$eval invokeStatic \\\"core.clj\\\" 3232]\\n  [clojure.core$eval invoke \\\"core.clj\\\" 3228]\\n  [user$eval3444021$fn__3444024 invoke \\\"NO_SOURCE_FILE\\\" 8]\\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \\\"main.clj\\\" 437]\\n  [clojure.main$repl$read_eval_print__9244 invoke \\\"main.clj\\\" 437]\\n  [clojure.main$repl$fn__9253 invoke \\\"main.clj\\\" 459]\\n  [clojure.main$repl invokeStatic \\\"main.clj\\\" 459]\\n  [clojure.main$repl doInvoke \\\"main.clj\\\" 368]\\n  [clojure.lang.RestFn invoke \\\"RestFn.java\\\" 622]\\n  [user$eval3444021 invokeStatic \\\"NO_SOURCE_FILE\\\" 6]\\n  [user$eval3444021 invoke \\\"NO_SOURCE_FILE\\\" 6]\\n  [clojure.lang.Compiler eval \\\"Compiler.java\\\" 7700]\\n  [clojure.lang.Compiler eval \\\"Compiler.java\\\" 7655]\\n  [clojure.core$eval invokeStatic \\\"core.clj\\\" 3232]\\n  [clojure.core$eval invoke \\\"core.clj\\\" 3228]\\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \\\"main.clj\\\" 437]\\n  [clojure.main$repl$read_eval_print__9244 invoke \\\"main.clj\\\" 437]\\n  [clojure.main$repl$fn__9253 invoke \\\"main.clj\\\" 459]\\n  [clojure.main$repl invokeStatic \\\"main.clj\\\" 459]\\n  [clojure.core.server$repl invokeStatic \\\"server.clj\\\" 183]\\n  [clojure.core.server$repl invoke \\\"server.clj\\\" 183]\\n  [clojure.lang.AFn applyToHelper \\\"AFn.java\\\" 152]\\n  [clojure.lang.AFn applyTo \\\"AFn.java\\\" 144]\\n  [clojure.lang.Var applyTo \\\"Var.java\\\" 707]\\n  [clojure.core$apply invokeStatic \\\"core.clj\\\" 667]\\n  [clojure.core.server$accept_connection invokeStatic \\\"server.clj\\\" 74]\\n  [clojure.core.server$start_server$fn__9040$fn__9041$fn__9043 invoke \\\"server.clj\\\" 118]\\n  [clojure.lang.AFn run \\\"AFn.java\\\" 22]\\n  [java.lang.Thread run \\\"Thread.java\\\" 1583]]}\"], :schema [:map [:updated-fields [:int {:min 0, :description #metabase.util.i18n.UserLocalizedString{:format-string \"value must be an integer greater than zero.\", :args [], :pluralization-opts {}}, :error/fn #object[clojure.core$constantly$fn__5759 0x1a42a52d \"clojure.core$constantly$fn__5759@1a42a52d\"]}]] [:total-fields [:int {:min 0, :description #metabase.util.i18n.UserLocalizedString{:format-string \"value must be an integer greater than zero.\", :args [], :pluralization-opts {}}, :error/fn #object[clojure.core$constantly$fn__5759 0x1a42a52d \"clojure.core$constantly$fn__5759@1a42a52d\"]}]]], :value #error {\n :cause \"\"\n :via\n [{:type java.sql.SQLException\n   :message \"Connections could not be qcquired from the underlying database!\"}\n  {:type com.mchange.v2.resourcepool.CannotAcquireResourceException\n   :message \"\"\n   :at [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \"fields.clj\" 76]}]\n :trace\n [[metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460$fn__3613461 invoke \"fields.clj\" 76]\n  [metabase.sync.util$do_with_error_handling invokeStatic \"util.clj\" 191]\n  [metabase.sync.util$do_with_error_handling invoke \"util.clj\" 184]\n  [metabase.sync.sync_metadata.fields$fn__3613459$sync_fields_BANG_3613458__3613460 invoke \"fields.clj\" 76]\n  [metabase.sync.sync_metadata.fields$fn__3613459$fn__3613474 invoke \"fields.clj\" 71]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 154]\n  [clojure.lang.AFn applyTo \"AFn.java\" 144]\n  [clojure.core$apply invokeStatic \"core.clj\" 669]\n  [clojure.core$apply invoke \"core.clj\" 662]\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047$fn__3613050 invoke \"util.clj\" 495]\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \"task_history.clj\" 122]\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \"task_
history.clj\" 110]\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045$fn__3613047 doInvoke \"util.clj\" 488]\n  [clojure.lang.RestFn invoke \"RestFn.java\" 400]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \"util.clj\" 132]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \"util.clj\" 126]\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invokeStatic \"util.clj\" 150]\n  [metabase.sync.util$do_with_start_and_finish_debug_logging invoke \"util.clj\" 146]\n  [metabase.sync.util$fn__3613043$run_step_with_metadata3613042__3613045 invoke \"util.clj\" 482]\n  [metabase.sync.util$fn__3613043$fn__3613058 invoke \"util.clj\" 477]\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111$fn__3613119 invoke \"util.clj\" 577]\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110$fn__3613111 invoke \"util.clj\" 575]\n  [metabase.models.task_history$fn__93966$do_with_task_history93965__93967 invoke \"task_history.clj\" 122]\n  [metabase.models.task_history$fn__93966$fn__93975 invoke \"task_history.clj\" 110]\n  [metabase.sync.util$fn__3613109$run_sync_operation3613108__3613110 invoke \"util.clj\" 572]\n  [metabase.sync.util$fn__3613109$fn__3613129 invoke \"util.clj\" 567]\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455$fn__141456 invoke \"sync_metadata.clj\" 70]\n  [metabase.sync.util$do_with_error_handling invokeStatic \"util.clj\" 191]\n  [metabase.sync.util$do_with_error_handling invoke \"util.clj\" 184]\n  [clojure.core$partial$fn__5929 invoke \"core.clj\" 2647]\n  [metabase.driver$eval89685$fn__89686 invoke \"driver.clj\" 910]\n  [clojure.lang.MultiFn invoke \"MultiFn.java\" 239]\n  [metabase.sync.util$sync_in_context$fn__3612917 invoke \"util.clj\" 167]\n  [metabase.sync.util$with_db_logging_disabled$fn__3612914 invoke \"util.clj\" 159]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \"util.clj\" 132]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \"util.clj\" 126]\n  [metabase.sync.util$with_start_and_finish_logging$fn__3612897 invoke \"util.clj\" 144]\n  [metabase.sync.util$fn__3612884$with_sync_events3612883__3612885$fn__3612889 invoke \"util.clj\" 118]\n  [metabase.sync.util$with_duplicate_ops_prevented$fn__3612871 invoke \"util.clj\" 90]\n  [metabase.sync.util$fn__3612939$do_sync_operation3612938__3612940 invoke \"util.clj\" 216]\n  [metabase.sync.util$fn__3612939$fn__3612942 invoke \"util.clj\" 210]\n  [metabase.sync.sync_metadata$fn__141454$sync_db_metadata_BANG_141453__141455 invoke \"sync_metadata.clj\" 68]\n  [metabase.sync.sync_metadata$fn__141454$fn__141459 invoke \"sync_metadata.clj\" 65]\n  [metabase.task.sync_databases$eval3613486 invokeStatic \"NO_SOURCE_FILE\" 636]\n  [metabase.task.sync_databases$eval3613486 invoke \"NO_SOURCE_FILE\" 635]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7700]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7655]\n  [clojure.core$eval invokeStatic \"core.clj\" 3232]\n  [clojure.core$eval invoke \"core.clj\" 3228]\n  [user$eval3444021$fn__3444024 invoke \"NO_SOURCE_FILE\" 8]\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \"main.clj\" 437]\n  [clojure.main$repl$read_eval_print__9244 invoke \"main.clj\" 437]\n  [clojure.main$repl$fn__9253 invoke \"main.clj\" 459]\n  [clojure.main$repl invokeStatic \"main.clj\" 459]\n  [clojure.main$repl doInvoke \"main.clj\" 368]\n  [clojure.lang.RestFn invoke \"RestFn.java\" 622]\n  [user$eval3444021 invokeStatic \"NO_SOURCE_FILE\" 6]\n  [user$eval3444021 invoke \"NO_SOURCE_FILE\" 6]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7700]\n  [clojure.lang.Compiler eval \"Compiler.java\" 7655]\n  [clojure.core$eval invokeStatic \"core.clj\" 3232]\n  [clojure.core$eval invoke \"core.clj\" 3228]\n  [clojure.main$repl$read_eval_print__9244$fn__9247 invoke \"main.clj\" 437]\n  [clojure.main$repl$read_eval_print__9244 invoke \"main.clj\" 437]\n  [clojure.main$repl$fn__9253 invoke \"main.clj\" 459]\n  [clojure.main$repl invokeStatic \"main.clj\" 459]
\n  [clojure.core.server$repl invokeStatic \"server.clj\" 183]\n  [clojure.core.server$repl invoke \"server.clj\" 183]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 152]\n  [clojure.lang.AFn applyTo \"AFn.java\" 144]\n  [clojure.lang.Var applyTo \"Var.java\" 707]\n  [clojure.core$apply invokeStatic \"core.clj\" 667]\n  [clojure.core.server$accept_connection invokeStatic \"server.clj\" 74]\n  [clojure.core.server$start_server$fn__9040$fn__9041$fn__9043 invoke \"server.clj\" 118]\n  [clojure.lang.AFn run \"AFn.java\" 22]\n  [java.lang.Thread run \"Thread.java\" 1583]]}, :fn-name sync-fields!}"]}]
         ["sync-fks" {:total-fks 6, :updated-fks 0, :total-failed 0}]
         ["sync-indexes"
          {:total-indexes 0, :added-indexes 0, :removed-indexes 0}]
         ["sync-metabase-metadata" {}]
         ["sync-table-privileges" {}]]}
```

And this error is an error from _malli_ which we do not consider as interruptible, and we carry on.

- Another way to fix this is to do the connection checking that is done for the syncing of the database at https://github.com/metabase/metabase/blob/master/src/metabase/task/sync_databases.clj#L78-L85 where we only try to sync if we can connect. This is smart™, but seems to be a bandaid over the above which should work better.

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

p

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bronsa**
closes #51683
Closes https://linear.app/metabase/issue/SEM-13/field-values-must-short-circuit-on-sync-ending-errors

# Description
Let sync's `with-error-handling` respect `::exception-class-not-to-retry` as its docstring actually promises.

This allows the entire sync pipeline to avoid doing needless work once one such exception is thrown, which is the goal of the original ticket

### CODE REVIEW

File: test/metabase/sync/field_values_test.clj [hunk 1]
```diff
@@ -270,3 +272,19 @@
...
+(deftest sync-aborts-on-non-recoverable-error-test
+  (testing "Make sure sync aborts on non-recoverable errors"
+    (one-off-dbs/with-blueberries-db
+      ;; insert 50 rows & sync
+      (one-off-dbs/insert-rows-and-sync! [(str/join (repeat 50 "A"))])
+      ;; Manually activate Field values since they are not created during sync (#53387)
+      (field-values/get-or-create-full-field-values! (t2/select-one :model/Field (mt/id :blueberries_consumed :str)))
+      ;; we throw ConnectException, which is a non-recoverable exception
+      (with-redefs [field-values/create-or-update-full-field-values! (fn [& _] (throw (java.net.ConnectException.)))]
+        (is (->> (sync/update-field-values! (data/db))
```
Comment (lbrdnk) [inline test/metabase/sync/field_values_test.clj]: Not suggesting anything, as that's rather subjective. I just think the `=?` is worth mentioning.
```
(is (=? {:steps [["delete-expired-advanced-field-values" {}]
                 ["update-field-values" {:throwable (partial instance? Exception)}]]}
        (sync/update-field-values! (data/db))))
```

**Review by lbrdnk — APPROVED** [review]

File: test/metabase/sync/field_values_test.clj (hunk 1 above)
Comment (bronsa) [reply test/metabase/sync/field_values_test.clj]: much nicer, thanks!
