### PR TITLE
Static Viz and Exports/Downloads Respect Dashcard Viz Settings

### LINKED ISSUE #45061: Dashboard level visualization settings not taken into account on dashboard subscriptions
### Describe the bug

If you change a column name in a dashboard, these changes are not taken into account on the subscription and on the static rendering

### To Reproduce

1) make a question (e.g. orders table)
2) add it to a dashboard
3) change the name of the address column to something you like
4) send a subscription with an xlsx attachment

### Expected behavior

We should respect the column names in the following orders:
1) dashboard level column name
2) question level column name

This should happen on the rendering + on the attachments

### Logs

NA

### Information about your Metabase installation

```JSON
v50.x

I think it's a regression
```

### Severity

P1

### Additional context

image
image

Please make sure that in the tests we respect the situations mentioned above

### PR DESCRIPTION
**Pull request by adam-james-v**
WIP

Fixes: #45061

Downloads, subscriptions, and subscription attachments don't necessarily respect the viz-settings applied to a Dashboard Card.

This PR fixes discrepancies and adds test utils+tests to improve coverage in this area.

In this screenshot
TAXTAXTAX is a custom column name coming from the card.
CASH MONEY is a custom column name coming from the Dashcard.
Both get merged in correctly when downloading:
image

A subscription attachment also works.

### CODE REVIEW

File: test/metabase/api/downloads_exports_test.clj [hunk 1]
```diff
@@ -427,3 +539,69 @@
...
+          (let [card-result     (card-download card :csv true)
+                dashcard-result (dashcard-download dashcard :csv true)
+                card-header     ["ID" "User ID" "Product ID" "SUB CASH MONEY" "Tax"
+                                 "Total" "Discount ($)" "Created At" "Quantity"]
+                dashcard-header ["ID" "User ID" "Product ID" "SUB CASH MONEY" "Tax"
+                                 "CASH MONEY" "Discount ($)" "Created At" "Quantity"]]
+            (is (= {:card-download     [card-header]
+                    :dashcard-download [dashcard-header]}
+                   {:card-download     (take 1 card-result)
+                    :dashcard-download (take 1 dashcard-result)}))))))))
```
Comment (piranha) [inline test/metabase/api/downloads_exports_test.clj:574]: `first`? 😁

File: src/metabase/query_processor/middleware/visualization_settings.clj [hunk 2]
```diff
@@ -44,10 +44,11 @@
 (defn- viz-settings
   "Pull viz settings from either the query map or the DB"
   [query]
-  (or (let [viz (-> query :viz-settings)]
-        (when (seq viz) viz))
-      (when-let [card-id (-> query :info :card-id)]
-        (mb.viz/db->norm (:visualization-settings (lib.metadata.protocols/card (qp.store/metadata-provider) card-id))))))
+  (mb.viz/db->norm
+   (or (let [viz (-> query :viz-settings)]
+         (when (seq viz) viz))
```
Comment (piranha) [inline src/metabase/query_processor/middleware/visualization_settings.clj:49]: it's not your code, but it could say `(-> query :viz-settings not-empty)` to be a bit easier to read.

**Review by sansolovyov — APPROVED** [review]
Logic is cool, had a few non-blocking comments on code style in tests.

File: test/metabase/api/downloads_exports_test.clj (hunk 1 above)
Comment (adam-james-v) [reply test/metabase/api/downloads_exports_test.clj:574]: 😮‍💨 yea, of course haha

File: src/metabase/query_processor/middleware/visualization_settings.clj (hunk 2 above)
Comment (adam-james-v) [reply src/metabase/query_processor/middleware/visualization_settings.clj:49]: Hmm.. I think this is actually to cover the case where :viz-settings IS there, but it's just an empty map, hence the `(seq viz)` check.

Comment (piranha) [reply src/metabase/query_processor/middleware/visualization_settings.clj:49]: `not-empty` does exactly that :) `(not-empty {}) ; => nil`
