### PR TITLE
Handle errors when enabling database actions

### LINKED ISSUE #27852: [Actions] Actions-enabling failure
**Describe the bug**

If a user attempts to enable actions, but, for some reason there is a backend error, there's no user feedback. We should show an error message, however generic, to indicate that at leas the UI isn't broken.

### PR DESCRIPTION
**Pull request by kulyk**
Closes #27852

### Description

Adds error handling to a toggle enabling/disabling actions for a database

### How to verify

1. For your Postgres / MySQL database, create a _database_ user with read-only permissions
2. Connect the database to Metabase using these credentials
3. Try to enable actions using the sidebar on the database connection page
4. Ensure you can see an error

**Quicker way**

1. Remove [this condition](https://github.com/metabase/metabase/blob/0eb21adb625a53dda779a60c45f9f59254363ee1/frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.tsx#L184), so the actions toggle shows up for database not supporting actions
2. Try to enable actions for e.g. Mongo
3. Ensure you can see an error

### Demo

> **Warning**
> For demo purposes, I've made the actions control show up for database not supporting actions. This shouldn't happen in the real world

https://user-images.githubusercontent.com/17258145/221905416-74ef955f-6f05-4924-afb1-28ba77886dac.mp4

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28744)

### CODE REVIEW

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.tsx [hunk 1]
```diff
@@ -25,7 +25,9 @@ interface DatabaseEditAppSidebarProps {
   database: Database;
   isAdmin: boolean;
   isModelPersistenceEnabled: boolean;
-  updateDatabase: (database: { id: DatabaseId } & Partial<IDatabase>) => void;
+  updateDatabase: (
```
Comment (WiNloSt) [inline frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.tsx:28]: Do you think it would be nicer to keep other signatures consistent, e.g. `deleteDatabase` for sure, also returns a promise?

I believe almost if not all other actions probably return a promise as well.

**Review by WiNloSt — APPROVED** [review]
Looks good to me.

File: frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.tsx (hunk 1 above)
Comment (kulyk) [reply frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.tsx:28]: You're right, wrapped other callback return types into `Promise` as well 👍

File: frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/ModelActionsSection/ModelActionsSection.tsx [hunk 2]
```diff
@@ -1,33 +1,47 @@
...
   onToggleModelActionsEnabled,
 }: ModelActionsSectionProps) {
+  const [error, setError] = useState<string | null>(null);
+
+  const handleToggleModelActionsEnabled = async (enabled: boolean) => {
+    try {
+      setError(null);
+      await onToggleModelActionsEnabled(enabled);
+    } catch (err) {
+      setError(getResponseErrorMessage(err) || t`Something went wrong`);
```
[the remark this answers is not in the document]
Comment (kulyk) [reply frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/ModelActionsSection/ModelActionsSection.tsx]: Thanks for double-checking! Just to be on the safe side, I've replaced it with a more common "An error occurred" message
