### PR TITLE
Translate more strings on static embed with `#locale`

### LINKED ISSUE #49864: There are instance locale texts on static embeds when using `#locale` hash parameter
### Describe the bug

During the testing of #8490 I found out that there are still texts that use instance locale, these texts are determined at load time. I used [`ttag/no-module-declaration`](https://github.com/ttag-org/eslint-plugin-ttag/blob/master/docs/rules/no-module-declaration.md) to pinpoint files that need to be fixed.

The problem was that there were 1381 errors when enabling that ESLint rule, so I only selectively focused on files related to visualizations and I drilled them down to just 3 places
1. Pie chart - Other
     Image

1. Trend chart - No data
     Image

1. Line chart - Tooltip aggregation name
     Image

### To Reproduce

1. Set the instance locale to something not English, so we can see the problem clearer
2. Embed a pie chart with a lot of data points, so it shows an "Other" slice
3. Embed a trend chart, link it to a dashboard filter, and when embedding set the filter so that it shows no data
4. Embed a bar chart with a lot of breakout data points. e.g. summarize orders by created and user.state
5. Put all of the above charts in a dashboard and embed it. You'll need to link a filter to the trend chart for this. Make the filter "editable", then publish the embed.
6. View this dashboard in either a static embedding or public link.
7. Filter the embed so that the trend chart shows no data,
8. for bar chart, hover over the "other" bar (the last one). And see the tooltip label.

### Expected behavior

All the 3 places mentioned should have proper translated text according to `#locale=xxx`

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-11-07",
      "src_hash": "83d542c00dfed390ffebec623205a11417eac506",
      "tag": "v1.1.39-SNAPSHOT",
      "hash": "9585f56"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.2+13-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.2+13-LTS",
    "os.name": "Mac OS X",
    "os.version": "15.1",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

could be really blocking, but this is such a rare case and it isn't as severe if the instance locale is set to English

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/49864

### Description

This PR translates the 3 places mentioned in the issue in static embeddings/public links.

### How to verify
Follow the repro from https://github.com/metabase/metabase/issues/49864

Just to make sure, you can also revert all the code except the E2E test and run the test, and all new assertions should fail.

### Demo
1. Pie chart - Other
     Screenshot 2024-11-12 at 3 01 53 PM

1. Trend chart - No data
     Screenshot 2024-11-12 at 2 37 29 PM

1. Line chart - Tooltip aggregation name
     Screenshot 2024-11-12 at 3 01 01 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by WiNloSt** [comment]
Not backporting this because we will release this feature `#locale` on 52.

File: frontend/src/metabase/visualizations/echarts/cartesian/model/other-series.ts [hunk 1]
```diff
@@ -100,55 +100,75 @@ const AGGREGATION_FN_MAP: Record<
...
+      fn: sum,
+    };
   },
-  avg: {
-    label: t`Average`,
-    fn: values => sum(values) / values.length,
+  get avg() {
+    return {
+      label: t`Average`,
+      fn: (values: number[]) => sum(values) / values.length,
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/other-series.ts:130]: it seems the type in `fn` can't be inferred from the `Record`'s value type. But it checks the type, so if you return something else in each getter, TS would complain.

File: frontend/src/metabase/visualizations/echarts/cartesian/model/other-series.ts [hunk 2]
```diff
@@ -100,55 +100,75 @@ const AGGREGATION_FN_MAP: Record<
   AggregationType,
   { fn: (values: number[]) => number; label: string }
 > = {
-  count: {
-    label: t`Total`,
-    fn: sum,
+  get count() {
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/other-series.ts:103]: use getter syntax, so I don't need to change callsites.

File: frontend/src/metabase/visualizations/echarts/pie/constants.ts [hunk 3]
```diff
@@ -36,8 +36,8 @@ export const OTHER_SLICE_MIN_PERCENTAGE = 0.005;
 
 export const OTHER_SLICE_KEY = `${NULL_CHAR}___OTHER___`;
 
-export const OTHER_SLICE_NAME = t`Other`;
+export const getSliceName = () => t`Other`;
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/echarts/pie/constants.ts:39]: these 2 variables need to be changed to a function since they're not inside an object like the other 2 files. But they're used only in a number of places, so I'm fine changing it like this.

File: frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js [hunk 4]
```diff
@@ -526,18 +526,24 @@ function formatDateStr({ date, dateUnitSettings, options }) {
 }
 
 export const CHANGE_TYPE_OPTIONS = {
-  MISSING: {
-    CHANGE_TYPE: "PREVIOUS_VALUE_MISSING",
-    PERCENT_CHANGE_STR: t`N/A`,
-    COMPARISON_VALUE_STR: t`(No data)`,
+  get MISSING() {
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js:529]: use getter syntax so I don't need to change the callsites.

File: e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js [hunk 5]
```diff
@@ -1112,11 +1224,9 @@ describe("issue 8490", () => {
 
     cy.findByTestId("embed-frame").within(() => {
       // X-axis labels: Jan 2023
-      cy.findByText("4월 2022").should("be.visible");
-
+      cy.findByText("11월 2023").should("be.visible");
```
Comment (WiNloSt) [inline e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js:1227]: since the line chart question changed, I updated the visible label accordingly.

File: e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js [hunk 6]
```diff
@@ -1082,24 +1154,64 @@ describe("issue 8490", () => {
...
+        // Other
+        cy.findByTestId("chart-legend").findByText("기타").should("be.visible");
+      });
     });
 
     cy.log("test a static embedded question");
-    cy.get("@questionId").then(questionId => {
+
+    cy.log("assert the line chart");
+    cy.get("@lineChartQuestionId").then(lineChartQuestionId => {
```
Comment (WiNloSt) [inline e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js:1211]: I don't want to repeat the same question test for each new question types, since they're basically the same, and visiting each question adds about 2 seconds on my machine, I could imagine it's a lot worse on CI with 2 more questions.

File: frontend/src/metabase/visualizations/echarts/pie/constants.ts (hunk 3 above)
Comment (npretto) [inline frontend/src/metabase/visualizations/echarts/pie/constants.ts:39]:
```suggestion
export const getOtherSliceName = () => t`Other`;
```
Was the removal of "other" intentional?

**Review by npretto — APPROVED** [review]
Left a comment but looks good otherwise

File: frontend/src/metabase/visualizations/echarts/pie/constants.ts (hunk 3 above)
Comment (WiNloSt) [reply frontend/src/metabase/visualizations/echarts/pie/constants.ts:39]: Aweeeee sheesh. That was a mistaken. Thanks for spotting it. 🙏

Comment (WiNloSt) [reply frontend/src/metabase/visualizations/echarts/pie/constants.ts]: Fixed in https://github.com/metabase/metabase/pull/49868/commits/9549a7065e1715fdbc487eb46de4202af2e8737e

File: frontend/src/metabase/visualizations/echarts/pie/constants.ts [hunk 7]
```diff
@@ -36,8 +36,8 @@ export const OTHER_SLICE_MIN_PERCENTAGE = 0.005;
 
 export const OTHER_SLICE_KEY = `${NULL_CHAR}___OTHER___`;
 
-export const OTHER_SLICE_NAME = t`Other`;
+export const getOtherSliceName = () => t`Other`;
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/echarts/pie/constants.ts:39]: https://github.com/metabase/metabase/pull/49868#discussion_r1837718184

**Review by kulyk — APPROVED** [review]
