### PR TITLE
Fix sync_schema silently dropping when executor is busy (GHY-3254)

### LINKED ISSUE #70628: `/sync_schema` returns 200 but no sync executes on Athena connector
### Describe the bug

Calling `POST /api/database/:id/sync_schema` returns HTTP 200, but no actual sync runs. Logs only show the POST was received — none of the expected sync steps (`sync-dbms-version`, `sync-tables`, `sync-fields`, etc.) ever start. Tables and fields do not update in Metabase.

Reproducible via both the UI "Sync database schema" button and the API. We've hit this on two separate Metabase instances — it went away after spinning up a fresh instance, then resurfaced.

Notably, this affects **all** databases on the problematic instance, including the **Sample Database** — not just our Athena-connected ones. On our other Metabase instance (same version), sync works correctly for all databases including Sample Database.

### To Reproduce

1. Have a database configured (we use Athena, but this also reproduces on the built-in Sample Database)
2. Trigger sync via UI button or `POST /api/database/:id/sync_schema`
3. Response is 200, but logs show only the POST request and health checks — no sync steps execute

### Expected behavior

`POST /api/database/:id/sync_schema` triggers a full metadata sync (all sync steps execute and complete).

### Logs

Working instance (sync runs):

Truncated summary:
```
POST /api/database/3/sync_schema 200 1113ms
STARTING: Sync metadata for athena Database 3 '<db_name>'
STARTING: step 'sync-dbms-version' ...
FINISHED: step 'sync-dbms-version' ...
STARTING: step 'sync-tables' ...
FINISHED: step 'sync-tables' ...
STARTING: step 'sync-fields' ...
FINISHED: step 'sync-fields' ...
FINISHED: Sync metadata for athena Database 3 '<db_name>' (11.9 s)
```

Full server logs:
```
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:25+08:00 DEBUG metabase.server.middleware.log POST /api/database/3/sync_schema 200 1113ms (1 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (822 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 5}
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:25+08:00 INFO metabase.sync.util STARTING: Sync metadata for athena Database 3 ''db_name_1'' (free: 0.10G, total: 0.60G, ratio: 0.17)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:25+08:00 WARN com.amazon.athena.jdbc.configuration.UrlParser ParameterizedMessage[messagePattern=The connection parameter "{}" is unknown or unsupported and will be ignored, argCount=1, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:25+08:00 WARN com.amazon.athena.jdbc.configuration.UrlParser ParameterizedMessage[messagePattern=The connection parameter "{}" was ignored because it was empty, argCount=1, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:26+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:26+08:00 DEBUG metabase.server.middleware.log GET /api/bug-reporting/details 200 2ms (1 DB calls) App DB connections: 2/15 Jetty threads: 4/50 (6 idle, 0 queued) (827 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 5}
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:26+08:00 INFO metabase.sync.util STARTING: step ''sync-dbms-version'' for athena Database 3 ''db_name_1'' (free: 0.10G, total: 0.60G, ratio: 0.16)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:26+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:26+08:00 INFO metabase.sync.util FINISHED: step ''sync-dbms-version'' for athena Database 3 ''db_name_1'' (39.6 ms) (free: 0.10G, total: 0.60G, ratio: 0.16)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:26+08:00 INFO metabase.sync.util STARTING: step ''sync-timezone'' for athena Database 3 ''db_name_1'' (free: 0.10G, total: 0.60G, ratio: 0.16)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:26+08:00 INFO metabase.sync.sync-metadata.sync-timezone :athena database 3 default timezone is nil
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:26+08:00 INFO metabase.sync.util FINISHED: step ''sync-timezone'' for athena Database 3 ''db_name_1'' (13.5 ms) (free: 0.10G, total: 0.60G, ratio: 0.16)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:26+08:00 INFO metabase.sync.util STARTING: step ''sync-tables'' for athena Database 3 ''db_name_1'' (free: 0.10G, total: 0.60G, ratio: 0.16)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:27+08:00 INFO metabase.sync.util FINISHED: step ''sync-tables'' for athena Database 3 ''db_name_1'' (36.4 ms) (free: 0.09G, total: 0.60G, ratio: 0.16)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:27+08:00 INFO metabase.sync.util STARTING: step ''sync-fields'' for athena Database 3 ''db_name_1'' (free: 0.09G, total: 0.60G, ratio: 0.16)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:27+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:27+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:27+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:28+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (831 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:28+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (831 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:28+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:29+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:29+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:30+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:31+08:00 INFO metabase.driver.athena Running Athena query : 'DESCRIBE `db_name_1`.`dim_anne_report`;'...
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:31+08:00 WARN com.amazon.athena.jdbc.configuration.UrlParser ParameterizedMessage[messagePattern=The connection parameter "{}" is unknown or unsupported and will be ignored, argCount=1, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:31+08:00 WARN com.amazon.athena.jdbc.configuration.UrlParser ParameterizedMessage[messagePattern=The connection parameter "{}" was ignored because it was empty, argCount=1, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:33+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (840 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:35+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:35+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:36+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:36+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util FINISHED: step ''sync-fields'' for athena Database 3 ''db_name_1'' (10.3 s) (free: 0.41G, total: 0.60G, ratio: 0.69)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util STARTING: step ''sync-fks'' for athena Database 3 ''db_name_1'' (free: 0.41G, total: 0.60G, ratio: 0.69)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util FINISHED: step ''sync-fks'' for athena Database 3 ''db_name_1'' (18.1 ms) (free: 0.41G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util STARTING: step ''sync-indexes'' for athena Database 3 ''db_name_1'' (free: 0.41G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util FINISHED: step ''sync-indexes'' for athena Database 3 ''db_name_1'' (13.3 ms) (free: 0.41G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util STARTING: step ''sync-metabase-metadata'' for athena Database 3 ''db_name_1'' (free: 0.41G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util FINISHED: step ''sync-metabase-metadata'' for athena Database 3 ''db_name_1'' (12.9 ms) (free: 0.41G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util FINISHED: Sync metadata for athena Database 3 ''db_name_1'' (11.9 s) (free: 0.41G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util STARTING: Analyze data for athena Database 3 ''db_name_1'' (free: 0.41G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util STARTING: step ''fingerprint-fields'' for athena Database 3 ''db_name_1'' (free: 0.41G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [*****·············································] 😢   12% Table 163 ''anne_user''
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [***********·······································] 😒   24% Table 140 ''dim_anne_story''
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util FINISHED: step ''fingerprint-fields'' for athena Database 3 ''db_name_1'' (38.0 ms) (free: 0.40G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util STARTING: step ''classify-fields'' for athena Database 3 ''db_name_1'' (free: 0.40G, total: 0.60G, ratio: 0.68)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.analyze classify-fields Analyzed [*****************·································] 😕   35% Table 161 ''anne_report_enriched''
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.analyze classify-fields Analyzed [***********************···························] 😬   47% Table 162 ''anne_time_workflow''
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.analyze classify-fields Analyzed [*****************************·····················] 😌   59% Table 142 ''dim_anne_project''
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util FINISHED: step ''classify-fields'' for athena Database 3 ''db_name_1'' (30.1 ms) (free: 0.40G, total: 0.60G, ratio: 0.67)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util STARTING: step ''classify-tables'' for athena Database 3 ''db_name_1'' (free: 0.40G, total: 0.60G, ratio: 0.67)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.analyze classify-tables Analyzed [***********************************************···] 😍   94% Table 154 ''fct_anne_time''
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.analyze classify-tables Analyzed [*****************************************·········] 😊   82% Table 164 ''anne_daily_user_engagement''
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.analyze classify-tables Analyzed [***********************************···············] 😏   71% Table 160 ''fct_anne_usage''
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util FINISHED: step ''classify-tables'' for athena Database 3 ''db_name_1'' (16.9 ms) (free: 0.40G, total: 0.60G, ratio: 0.67)
[6f798db6-beb1-4385-9794-beaab23f1e5b] 2026-03-10T11:04:37+08:00 INFO metabase.sync.util FINISHED: Analyze data for athena Database 3 ''db_name_1'' (104.9 ms) (free: 0.40G, total: 0.60G, ratio: 0.67)
```

Broken instance (sync silently dropped):

Truncated summary:
```
POST /api/database/5/sync_schema 200 1077ms
GET /api/health 200 0ms
GET /api/health 200 0ms
... (only health checks, no sync steps ever start)
```

Full server logs:
```
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:08+08:00 DEBUG metabase.server.middleware.log POST /api/database/5/sync_schema 200 1077ms (1 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (608 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 3}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:09+08:00 DEBUG metabase.server.middleware.log GET /api/bug-reporting/details 200 2ms (1 DB calls) App DB connections: 2/15 Jetty threads: 4/50 (5 idle, 0 queued) (608 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 3}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:09+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (608 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:09+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (608 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:14+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (604 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:19+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (576 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:19+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (576 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:24+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:24+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (577 total active threads) Queries in flight: 1 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:27+08:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 3426ms (3 DB calls) App DB connections: 2/15 Jetty threads: 3/50 (5 idle, 0 queued) (584 total active threads) Queries in flight: 1 (0 queued); athena DB 3 connections: 0/1 (0 threads blocked) {:metabase-user-id 5}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:29+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (584 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:29+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (584 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:34+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (584 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:39+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (576 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:39+08:00 DEBUG metabase.server.middleware.log GET /api/health 200 0ms (0 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (5 idle, 0 queued) (576 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
[d5ca38c0-a8fa-4156-9ee6-c984e420f409] 2026-03-10T11:04:40+08:00 WARN com.amazon.athena.jdbc.AthenaConnection ParameterizedMessage[messagePattern=The Executor parameter is currently not supported and will be ignored, argCount=0, throwableProvided=false]
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "athena",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2026-02-24",
      "tag": "v0.58.7.4",
      "hash": "93cd8a0"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.8"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.10+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.10+7-LTS",
    "os.name": "Linux",
    "os.version": "6.1.155-176.282.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

Blocking usage partially

### Additional context

We rely on the API to trigger sync programmatically as a core part of our workflow. The only workaround is to PUT a modified sync schedule to force a scheduler rebuild, which is hacky and adds a ~2 minute delay.

Updating the database via `PUT /api/database/:id` with a modified `schedules.metadata_sync.schedule_minute` forces Metabase to rebuild the scheduler and triggers a real sync. This is the same as saving the sync schedule in the UI. This suggests the `sync_schema` endpoint's internal dispatch is silently dropping the request rather than a database connectivity issue.

The fact that even the Sample Database exhibits the same behavior on the affected instance likely rules out driver-specific issues.

### PR DESCRIPTION
**Pull request by ericnormand**
<!-- Added by 'Add Issue References to PR' GitHub Action. To disable linking, add 'no-auto-issue-links' label to your PR. --> closes #70628
## Summary

Fixes [GHY-3254](https://linear.app/metabase/issue/GHY-3254): `POST /api/database/:id/sync_schema` returns 200 but no sync executes.

### Root cause

The `sync_schema` endpoint submits work to a single-threaded executor (`quick-task/submit-task!`) and immediately returns 200. If any previous task in that executor hangs (e.g., a stuck JDBC connection), all subsequent manual sync requests queue forever — silently dropped from the user's perspective.

This executor is shared by 14 different call sites (manual sync, field value rescans, table sync, database health checks, etc.), so a single stuck task blocks everything.

This explains all reported symptoms:
- **Affects ALL databases** (including Sample Database) — the executor is a global singleton, not per-DB
- **Restart fixes temporarily** — fresh JVM means fresh thread pool
- **Workaround (modifying sync schedule) works** — scheduled syncs use Quartz's own thread pool, bypassing `quick-task` entirely
- **No errors in logs** — the task is successfully queued, it just never executes

### Fix

Each task submitted to the quick-task executor now runs on a child thread with a configurable timeout (`*task-timeout-ms*`, default 2 hours). If a task exceeds the timeout, it is cancelled and the executor moves on to the next queued task.

The stuck thread's stack trace is logged at WARN level so operators can diagnose the underlying cause.

Note: `Thread.interrupt()` won't terminate a thread stuck in classic socket I/O (e.g., JDBC reads), but those calls already have a 30-minute network timeout via `Connection.setNetworkTimeout`. The per-task timeout here is a safety net for any case where an individual task hangs beyond what's reasonable.

### Other possible fixes

Timing out tasks is an important safety net. However, this does not address the root cause, which is whatever is being stuck. There are 13 operations that share this queue.

  1. warehouses_rest/api.clj — manual sync (sync_schema endpoint)                                                                                                                                                                                                            
  2. warehouses_rest/api.clj — rescan field values                                                                                                                                                                                                                           
  3. warehouses/models/database.clj — health check + details migration                                                                                                                                                                                                       
  4. warehouse_schema_rest/api/table.clj — sync unhidden tables                                                                                                                                                                                                              
  5. warehouse_schema_rest/api/table.clj — rescan field values for table                                                                                                                                                                                                     
  6. warehouse_schema_rest/api/table.clj — sync table schema                                                                                                                                                                                                                 
  7. warehouse_schema_rest/api/field.clj — sync table for JSON unfolding                                                                                                                                                                                                     
  8. warehouse_schema_rest/api/field.clj — refingerprint after type change                                                                                                                                                                                                   
  9. sync/events/sync_database.clj — sync on database creation                                                                                                                                                                                                               
  10. data_studio/api/table.clj — sync table schema (data studio)                                                                                                                                                                                                            
  11. data_studio/api/table.clj — rescan field values (data studio)                                                                                                                                                                                                          
  12. metabase_enterprise/workspaces/common.clj — workspace setup                                                                                                                                                                                                            
  13. metabase_enterprise/advanced_config/file/databases.clj — sync from config file                                                                                                                                                                                         

  
The actual root cause could be in any of them. Anything that never returns (or takes a very long time), could block this queue. 

Another idea is to have separate queues.

### CODE REVIEW

**Comment by ericnormand** [comment]
An open question is: How long to make this timeout?

Does a 2 hour timeout solve the customer's problem? How often do they want to trigger this from their automation?

The [JDBC timeouts are 30 minutes](https://github.com/metabase/metabase/blob/master/src/metabase/driver/settings.clj#L107) for the sync calls. But there are multiple sequential calls that could take much longer than 30 minutes total.

File: src/metabase/util/quick_task.clj [hunk 1]
```diff
@@ -20,10 +22,32 @@
 (defonce ^:private executor
   (delay (Executors/newFixedThreadPool 1 ^ThreadFactory thread-factory)))
 
+(def ^:dynamic *task-timeout-ms*
+  "Maximum time in milliseconds a quick-task is allowed to run before being cancelled.
+   Default is 2 hours."
+  (* 2 60 60 1000))
```
Comment (camsaul) [inline src/metabase/util/quick_task.clj]: We have a `(u/hours->ms 2)` function that is marginally more readable here

I think it could be worth it to make this a real setting ... I don't want to pull in more deps of a util namespace on settings tho, so just a config env var (`metabase.config.core`) should be enough here -- that way if 2 hours doesn't work for someone they can set it to something else without waiting for us to cut a new release. Just as an escape hatch

It might be better to use minute resolution or something instead of hours if it's configurable th.

**Review by camsaul — APPROVED** [review]
👍 I think this change makes sense

File: src/metabase/util/quick_task.clj (hunk 1 above)
Comment (ericnormand) [reply src/metabase/util/quick_task.clj]: @camsaul I added a config env var for this. The customer can configure it for their needs.
