### PR TITLE
Load tables when db id is present in data permissions pages, e2e test

### LINKED ISSUE #37774: Refreshing after setting a table to be sandboxed causes an error
### Describe the bug

If you change a table's permissions to be sandboxed, and then refresh, you get an error page.

### To Reproduce

1. On an EE instance with sandboxing enabled, go to Admin -> Permissions 
2. Click on a database and change the Data Access permissions for any table to `Sandboxed`
3. Configure sandboxing in the model, click `Save`, then click `Save Changes` in the header
4. Refresh
5. You should see `Something's gone wrong`

It seems like after you've configured sandboxing, the URL is `/admin/permissions/data/group/1/database/1/schema/PUBLIC` which errors on a fresh load. 

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
current master
```

### Severity

mild

### Additional context

_No response_

### LINKED ISSUE #37811: Changing groups or dbs on data permissions, after saving a value causes the client to falsely believe that someone else edited the perm graph
### Describe the bug

I encountered a potential bug in setting permissions through the UI. I think it's related to our splitting api access patterns to using lookups by group-id (or db-id) on the data permission graphs. 

When I attempt to change a permission for one group and then try to save a permission change for another group, I encounter a UX issue instead of being able to save. I have attached a screenshot to illustrate the problem. The error says that someone else changed a permission, but of course no-one else can change permissions on my dev instance. Interestingly, this issue doesn't occur when I don't change groups. I have also included a link to a video that demonstrates the problem [here](https://www.loom.com/share/94d5afe5fbf840bf8f0355baeec2bc8f). The `revision` number seems to be correct.

Also worth mentioning that refreshing the page allows me to change permissions, which seems to indicate that it's just a UX issue.

### To Reproduce

see linked loom

### Expected behavior

it should only tell me someone else edited the perm graph when someone else edited the perm graph

### Logs

2024-01-17 17:16:11,499 DEBUG middleware.log :: GET /api/permissions/graph/group/1 200 21.2 ms (4 DB calls) App DB connections: 1/10 Jetty threads: 6/50 (0 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
2024-01-17 17:16:11,545 DEBUG middleware.log :: GET /api/database/1/metadata 200 60.2 ms (16 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (0 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
2024-01-17 17:16:11,659 DEBUG middleware.log :: GET /api/permissions/graph/db/1 200 4.0 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (0 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
2024-01-17 17:16:16,626 WARN api.common :: Unexpected parameters at [:put "/api/permissions/graph"]: [:revision :sandboxes :impersonations :groups]
Please add them to the schema or remove them from the API client
2024-01-17 17:16:16,674 DEBUG middleware.log :: PUT /api/permissions/graph 200 47.4 ms (43 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (0 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
2024-01-17 17:16:23,089 WARN api.common :: Unexpected parameters at [:put "/api/permissions/graph"]: [:revision :sandboxes :impersonations :groups]
Please add them to the schema or remove them from the API client
2024-01-17 17:16:23,167 DEBUG middleware.log :: PUT /api/permissions/graph 200 77.8 ms (28 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (0 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
2024-01-17 17:16:28,338 DEBUG middleware.log :: GET /api/permissions/graph/db/2 200 11.6 ms (3 DB calls) App DB connections: 1/10 Jetty threads: 6/50 (0 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
2024-01-17 17:16:28,353 DEBUG middleware.log :: GET /api/database/2/metadata 200 21.5 ms (7 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (0 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)

### Information about your Metabase installation

```JSON
on master
```

### Severity

not severe

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/37774
Closes https://github.com/metabase/metabase/issues/37811

### Description
Due to the way we fetch and manage data in the Groups and Database permissions pages, it was possible to cause the page to error by navigating directly to a permissions schema page. This is because the parent page is responsible for observing the URL, pulling the DB ID out, and getting table information for that database. However, we would still render the children component while that was happening. The children components then call selectors that make assumptions about what is in the entity store based on the URL. In this specific case, we assumed we would find a schema entity based on the URL, but in reality it hadn't been loaded yet

This bug was caused by something kinda weird, in that when dismissing the sandbox permissions modal we would always have a schema in the URL even if there wasn't one previously (this is due to how we determine parent routes in the app). This change ensures that those routes with the schema will load properly.

This PR also adds some test coverage specifically for editing sandbox access in a group focused view (previously, only database focused view was covered).

Edit:
While working on this, I noticed that the impersonated.cy.spec.js suite was failing do to #37811. Because the change was small, I included it in this PR to get CI green. If needed, I can separate it out into it's own PR

### How to verify

1. Go to Admin -> Permissions
2. Select a group, then a database, and select sandboxed access on one of the tables
3. Once the modal opens, simply dismiss it. You should now see a schema present in your URL
4. Refresh the page.

### Demo
chrome_e2SrAROaew

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/admin/permissions/selectors/data-permissions/permission-editor.ts [hunk 1]
```diff
@@ -159,11 +161,13 @@ export const getDatabasesPermissionEditor = createSelector(
     if (!defaultGroup) {
       throw new Error("No default group found");
     }
-
+ 
     const hasSingleSchema =
       databaseId != null &&
       metadata.database(databaseId)?.getSchemas().length === 1;
 
+    // console.log(hasSingleSchema)
```
Comment (iethree) [inline frontend/src/metabase/admin/permissions/selectors/data-permissions/permission-editor.ts]: 🗑️

Comment (npfitz) [reply frontend/src/metabase/admin/permissions/selectors/data-permissions/permission-editor.ts]: Rude haha

File: frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.tsx [hunk 2]
```diff
@@ -70,26 +70,16 @@ function DataPermissionsPage({
...
-    fetchTables(params.databaseId);
-  }, [params.databaseId, fetchTables]);
+  const { isLoading: isLoadingTables } = useTableListQuery({
+    query: {
+      dbId: params.databaseId,
+      include_hidden: true,
+      remove_inactive: true,
+    },
+    enabled: params.databaseId !== undefined,
+  });
```
Comment (iethree) [inline frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.tsx:80]: ❤️

File: frontend/src/metabase/admin/permissions/test/GroupsPermissionsPage/GroupsPermissionsPage.unit.spec.tsx [hunk 3]
```diff
@@ -80,8 +82,8 @@ describe("GroupsPermissionsPage", function () {
 
       await editDatabasePermission();
 
-      expect(screen.getByText("Cancel")).toBeInTheDocument();
-      expect(screen.getByText("Save changes")).toBeInTheDocument();
+      await expect(screen.getByText("Cancel")).toBeInTheDocument();
+      await expect(screen.getByText("Save changes")).toBeInTheDocument();
```
Comment (iethree) [inline frontend/src/metabase/admin/permissions/test/GroupsPermissionsPage/GroupsPermissionsPage.unit.spec.tsx:86]: pretty sure expect is synchronous so these `await`s don't do anything.

**Review by iethree — APPROVED** [review]
