### PR TITLE
Fix date filter + relative date + offset bug

### LINKED ISSUE #25481: When using Date Filters and setting up relative dates "starting from" the range specified provides inconsistent results.
**Describe the bug**
When using Date Filters and setting up relative dates "starting from" the range specified provides inconsistent results. There is inconsistency between the frontend and backend:

image

**To Reproduce**
1. Go to New -> Sql Query -> Select Sample Database
2. Paste the following query:
```
Select MIN(CASE WHEN {{pre}} THEN CREATED_AT END) AS pre_min,
	   MAX(CASE WHEN {{pre}} THEN CREATED_AT END) AS pre_max
FROM orders
```
4. Set Variable Type Field Filter,  Field to Map -> CreatedAt, Filter Widget Type -> Date Filter 
5. Go to filter -> Relative Dates -> Choose Starting From -> Starting From 36 months and past 1 month ... Run query and notice inconsistency in the image above

 
**Expected behavior**
The result should filter for just 1 month. Since even the description is stating "Previous Month, Starting 36 months ago"

image

Notice that setting the value to 0 gives correct result but inconsistent range:

image

"

**Information about your Metabase Installation:**

- Metabase version: Tested on both 1.43.0 and 1.44.3 ... Seems to be a bug introduced with the new date filter widget 

**Additional Context**

This behaviour doesn't happen if you create a Question. The only issue I think might be good to consider/fix is that it allows you to input 0 and even though nothing is outputted the preview shows a range which makes sense from a logic perspective but not a user perspective, it can be removed altogether to not allow the input of 0 but this is trivial and just adding here as additional context 

image

### PR DESCRIPTION
**Pull request by escherize**
fixes #25481 
Screen Shot 2022-09-29 at 12 40 57 PM

When it comes to relative date ranges, `past1months-from-0months` should return the same result as `past1months`. There's a generative test to test this fix.

I'm not 100% sure, but I believe this bug was introduced when adding the "-from[n][time-unit]s" suffix. So checking for `(seq relative-suffix)` was improperly returning true when it was actually checking for `(= "~" relative-suffix)`.

### CODE REVIEW

File: src/metabase/driver/common/parameters/dates.clj [hunk 1]
```diff
@@ -172,34 +172,35 @@
...
                            [:int-value :unit :relative-suffix :int-value-1 :unit-1])
     :range  (fn [{:keys [unit int-value unit-range to-period relative-suffix unit-1 int-value-1]} dt]
-              (let [dt-off (cond-> dt
-                             unit-1 (t/plus ((get-in operations-by-date-unit [unit-1 :to-period]) int-value-1)))
-                    dt-res (maybe-reduce-resolution unit dt-off)]
-                (unit-range (t/plus dt-res (to-period (if (seq relative-suffix) 0 1)))
-                            (t/plus dt-res (to-period int-value)))))
+              (let [dt-offset (cond-> dt
+                                unit-1 (t/plus ((get-in operations-by-date-unit [unit-1 :to-period]) int-value-1)))
+                    dt-resolution (maybe-reduce-resolution unit dt-offset)]
```
Comment (camsaul) [inline src/metabase/driver/common/parameters/dates.clj:194]: Big fan of giving variables more explicit names 👍 ... makes the code easier to read. I personally don't see the word `off` and think that it's short for `offset`

File: src/metabase/driver/common/parameters/dates.clj [hunk 2]
```diff
@@ -172,34 +172,35 @@
...
+                (unit-range (t/plus dt-resolution (to-period (if (= "~" relative-suffix) 0 1)))
```
Comment (camsaul) [inline src/metabase/driver/common/parameters/dates.clj:195]: I've seen the `(= relative-suffix "~")` check in a few places... is it worth abstracting out into a separate function? Not so much to save code duplication, but to make the code easier to understand. Something like `(include-current-suffix? relative-suffix)` would be easier for people to understand than `(= "~" ...)`. Not everybody might know the special purpose of `~` which could make this confusing

File: test/metabase/driver/common/parameters/dates_test.clj [hunk 3]
```diff
@@ -127,61 +130,70 @@
...
   (t/with-clock (t/mock-clock #t "2016-06-07T12:13:55Z")
     (doseq [[group s->expected]
-            {"absolute datetimes"         {"Q1-2016"               {:end "2016-03-31", :start "2016-01-01"}
-                                           "2016-02"               {:end "2016-02-29", :start "2016-02-01"}
-                                           "2016-04-18"            {:end "2016-04-18", :start "2016-04-18"}
-                                           "2016-04-18~2016-04-23" {:end "2016-04-23", :start "2016-04-18"}
+            {"absolute datetimes"         {"Q1-2016"               {:start "2016-01-01", :end "2016-03-31"}
+                                           "2016-02"               {:start "2016-02-01", :end "2016-02-29"}
+                                           "2016-04-18"            {:start "2016-04-18", :end "2016-04-18"}
+                                           "2016-04-18~2016-04-23" {:start "2016-04-18", :end "2016-04-23"}
```
Comment (camsaul) [inline test/metabase/driver/common/parameters/dates_test.clj:136]: 👍 on changing the orders around here... doesn't make any difference if you're a computer but it's certainly weird to have to flip these around in your head to get a real date range when looking at it as a human. Thanks for doing this

File: test/metabase/driver/common/parameters/dates_test.clj [hunk 4]
```diff
@@ -201,6 +213,36 @@
                  (params.dates/date-string->range s options))
               (format "%s with options %s should parse to %s" (pr-str s) (pr-str options) (pr-str expected))))))))
 
+(deftest relative-dates-with-starting-from-zero-must-match
+  (testing "relative dates need to behave the same way, offset or not."
+    (t/with-clock (t/mock-clock #t "2016-06-07T12:13:55Z")
```
Comment (camsaul) [inline test/metabase/driver/common/parameters/dates_test.clj:218]: We actually have an `mt/with-clock` macro that can take a temporal object directly. It also adds `testing` context and checks to make sure you're not using it inside a `^:parallel` test. So I'd recommend using that instead of `t/with-clock` directly. Now that we have the capability of writing custom linters in Kondo we should probably go add this in there at some point

```suggestion
    (mt/with-clock #t "2016-06-07T12:13:55Z"
```

File: test/metabase/driver/common/parameters/dates_test.clj [hunk 5]
```diff
@@ -201,6 +213,36 @@
...
+      (gen/elements #{"next" "past"})
+      (gen/such-that #(not= % 0) gen/pos-int)
+      (gen/elements time-units)
+      (gen/elements time-units)))))
+
+(tc/quick-check 1000
+  (prop/for-all [[tr tr+from-zero] time-range-generator]
+    (tap> [tr tr+from-zero])
+    (= (params.dates/date-string->range tr)
+       (params.dates/date-string->range tr+from-zero))))
```
Comment (camsaul) [inline test/metabase/driver/common/parameters/dates_test.clj:244]: Love seeing the generative tests

**Review by camsaul — APPROVED** [review]
This PR looks great. Thanks for the code cleanup you did as well -- it's always good to try to make things a little more readable even if it's not really needed for the bug fix.

File: test/metabase/driver/common/parameters/dates_test.clj (hunk 4 above)
Comment (escherize) [reply test/metabase/driver/common/parameters/dates_test.clj]: Good point, I'll fix the other `(with-clock .. mock-clock ..` calls in there too.

**Comment by mazameli** [comment]
@escherize, minor edge case, but inputting 0 in the "days ago" input incorrectly changes it to "day from now" (I would expect it to say "days ago"). But no one should be putting 0 in this box in real life, so 🤷🏼‍♂️ 

image

**Comment by mazameli** [comment]
@escherize, you asked me to give this a spin yesterday, and it seems like things look correct from my ~15 minutes of testing. 👍🏼

File: src/metabase/driver/common/parameters/dates.clj (hunk 1 above)
Comment (piranha) [reply src/metabase/driver/common/parameters/dates.clj:200]: OTOH in this context `dt-` seems a bit superfluous. It's not distracting, but also doesn't add any information I think.
