### PR TITLE
Delay substituting persisted native query until after analysis

### LINKED ISSUE #28679: Using a custom column on top of a persisted model will generate an invalid SQL
**Describe the bug**
When asking a question on a persisted model and then adding a custom column, will generate a query that aliases with the same name twice causing an error in the engine

**Logs**
Not needed

**To Reproduce**
1) Generate a model, persist it
2) ask a question to that model, and add a custom column
3) see the error

Or just see question 6866 in stats

**Expected behavior**
Use different aliases when doing nested queries

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Metabase version: master

**Severity**
P1

**Additional context**
NA

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes https://github.com/metabase/metabase/issues/28679

(I can't quite recreate the behavior of that issue but pretty sure this will solve it)

We were substituting persisted queries into the query at too early a stage.

Card 729 is a persisted model of `select * from categories`

```clojure
{:type :query,
 :query {:source-table "card__729",
         :expressions {:adjective ["case"
                                   [[[">" ["field" 100 nil] 30] ;; price > 30
                                     "expensive"]
                                    [[">" ["field" 100 nil] 20] ;; price > 20
                                     "not too bad"]]
                                   {:default "its ok"}]},
         :aggregation [["count"]],
         :breakout [["expression" "adjective" nil]
                    ["field" 101 nil]]}, ;; group by "adjective" and category
 :database 3,
 :parameters []}
```

This would immediately get turned into an equivalent

```clojure
{:type :query,
 :query {:source-table 12
         :persisted-info/native "select \"id\", \"ean\", \"title\", \"category\", \"vendor\", \"price\", \"rating\", \"created_at\" from \"metabase_cache_424a9_3\".\"model_729_products_r\""
         :expressions {:adjective ["case"
                                   [[[">" ["field" 100 nil] 30]
                                     "expensive"]
                                    [[">" ["field" 100 nil] 20]
                                     "not too bad"]]
                                   {:default "its ok"}]},
         :aggregation [["count"]],
         :breakout [["expression" "adjective" nil]
                    ["field" 101 nil]]},
 :database 3,
 :parameters []}
```

And the obvious failure here is the use of `[:field 100 nil]` (price) against an inner query of `select ... price ... from cache_table`. This could break many queries and caused a flood of

```
WARN middleware.fix-bad-references :: Bad :field clause [:field 100 #:metabase.query-processor.util.add-alias-info{:source-table :metabase.query-processor.util.add-alias-info/source, :source-alias "price"}] for field "products.price" at [:expressions "adjective" :case :>]: clause should have a :join-alias. Unable to infer an appropriate join. Query may not work as expected.
WARN middleware.fix-bad-references :: Bad :field clause [:field 100 #:metabase.query-processor.util.add-alias-info{:source-table :metabase.query-processor.util.add-alias-info/source, :source-alias "price"}] for field "products.price" at [:expressions "adjective" :case :>]: clause should have a :join-alias. Unable to infer an appropriate join. Query may not work as expected.
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28739)

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj [hunk 1]
```diff
@@ -1031,7 +1031,7 @@
                    (run-query)))))))))
 
 (deftest persistence-disabled-when-sandboxed
-  (mt/test-driver :postgres
+  (mt/test-drivers (mt/normal-drivers-with-feature :persist-models)
```
Comment (dpsutton) [inline enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj:1034]: adding extra drivers but forgetting to set `mt/test-drivers` with an s makes tests silently not run. See https://github.com/metabase/metabase/issues/28735

File: src/metabase/driver/sql/query_processor.clj [hunk 2]
```diff
@@ -1372,10 +1372,18 @@
...
+                          persisted :persisted-info/native
+                          :as source-query} :source-query}]
   (assoc honeysql-form
-         :from [[(if native
+         :from [[(cond
+                   native
                    (sql-source-query native params)
+
+                   persisted
+                   (sql-source-query persisted nil)
```
Comment (dpsutton) [inline src/metabase/driver/sql/query_processor.clj:1384]: This is the fix. We substitute the native sql in as we are emitting sql rather than earlier where it messes up aliases and field info.

Straight swap of `select <fields> from public.products` -> `select <fields> from cache_schema.cached_model`.

File: src/metabase/query_processor/middleware/fetch_source_query.clj [hunk 3]
```diff
@@ -152,7 +144,7 @@
        (log/info (trs "Found substitute cached query for card {0} from {1}.{2}"
                       card-id
                       (ddl.i/schema-name {:id database-id} (public-settings/site-uuid))
-                      (:table_name card))))
+                      (:table_name persisted-info))))
```
Comment (dpsutton) [inline src/metabase/query_processor/middleware/fetch_source_query.clj:147]: We used to select the card and persisted info into one object. Now two queries but never updated where we got `:table_name`. So we were logging "found substitute cached query for card 1234 from cache_schema.null"

File: test/metabase/query_processor/persistence_test.clj [hunk 4]
```diff
@@ -0,0 +1,85 @@
+(ns metabase.query-processor.persistence-test
```
Comment (dpsutton) [inline test/metabase/query_processor/persistence_test.clj:1]: persistence tests were kinda scattered. Now we have a proper home for them.

File: src/metabase/driver/sql/query_processor.clj (hunk 2 above)
Comment (snoe) [reply src/metabase/driver/sql/query_processor.clj:1384]: Can `persisted` and  `native` both be true? I think `persisted` should be above it to be safe

Comment (dpsutton) [reply src/metabase/driver/sql/query_processor.clj:1384]: Yes i suppose it can. Thank you

**Review by snoe — APPROVED** [review]

**Review by bshepherdson — APPROVED** [review]

**Review by camsaul — APPROVED** [review]
