### PR TITLE
Match deduplicated column to field-ref if desired col name fails

### LINKED ISSUE #64058: Question based on model with same-named columns from v55 fails in v56
### Describe the bug

If you create a model based on another model in v55, where the base model has multiple tables with columns with the same name, and then filter on one of those columns, the question works normally. But if you upgrade to v56, the same question or new questions over that model will fail with "column not found".

### To Reproduce

1. Start v55.15.4 or any version prior to 56
2. Create a notebook model, Orders + Products

Image

3. Create a model from that model, Orders + Products 2, no need to add anything

Image

4. Try to create a question over Orders + Products 2, and add a filter on Product -> Created At. Should work.
5. Save the question
6. Upgrade to v56 (in here I upgraded to v56.6)
7. Now the question fails. If you try and create a new question on the model it will also break.
Image

Image

You can duplicate the model and the duplicate will work, but the original won't

### Expected behavior

It should run the question normally

### Logs

See the bottom of the generated SQL, where created_at_2 is referenced but doesn't exist earlier in the query:

```sql
SELECT
  "source"."ID" AS "ID",
  "source"."USER_ID" AS "USER_ID",
  "source"."PRODUCT_ID" AS "PRODUCT_ID",
  "source"."SUBTOTAL" AS "SUBTOTAL",
  "source"."TAX" AS "TAX",
  "source"."TOTAL" AS "TOTAL",
  "source"."DISCOUNT" AS "DISCOUNT",
  "source"."CREATED_AT" AS "CREATED_AT",
  "source"."QUANTITY" AS "QUANTITY",
  "source"."Products__ID" AS "Products__ID",
  "source"."Products__EAN" AS "Products__EAN",
  "source"."Products__TITLE" AS "Products__TITLE",
  "source"."Products__CATEGORY" AS "Products__CATEGORY",
  "source"."Products__VENDOR" AS "Products__VENDOR",
  "source"."Products__PRICE" AS "Products__PRICE",
  "source"."Products__RATING" AS "Products__RATING",
  "source"."Products__CREATED_AT" AS "Products__CREATED_AT",
  "source"."PEOPLE__via__USER_ID__NAME" AS "PEOPLE__via__USER_ID__NAME",
  "source"."PRODUCTS__via__PRODUCT_ID__TITLE" AS "PRODUCTS__via__PRODUCT_ID__TITLE"
FROM
  (
    SELECT
      "source"."ID" AS "ID",
      "source"."USER_ID" AS "USER_ID",
      "source"."PRODUCT_ID" AS "PRODUCT_ID",
      "source"."SUBTOTAL" AS "SUBTOTAL",
      "source"."TAX" AS "TAX",
      "source"."TOTAL" AS "TOTAL",
      "source"."DISCOUNT" AS "DISCOUNT",
      "source"."CREATED_AT" AS "CREATED_AT",
      "source"."QUANTITY" AS "QUANTITY",
      "source"."Products__ID" AS "Products__ID",
      "source"."Products__EAN" AS "Products__EAN",
      "source"."Products__TITLE" AS "Products__TITLE",
      "source"."Products__CATEGORY" AS "Products__CATEGORY",
      "source"."Products__VENDOR" AS "Products__VENDOR",
      "source"."Products__PRICE" AS "Products__PRICE",
      "source"."Products__RATING" AS "Products__RATING",
      "source"."Products__CREATED_AT" AS "Products__CREATED_AT",
      "source"."PEOPLE__via__USER_ID__NAME" AS "PEOPLE__via__USER_ID__NAME",
      "source"."PRODUCTS__via__PRODUCT_ID__TITLE" AS "PRODUCTS__via__PRODUCT_ID__TITLE"
    FROM
      (
        SELECT
          "PUBLIC"."ORDERS"."ID" AS "ID",
          "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID",
          "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID",
          "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL",
          "PUBLIC"."ORDERS"."TAX" AS "TAX",
          "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL",
          "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT",
          "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT",
          "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY",
          "Products"."ID" AS "Products__ID",
          "Products"."EAN" AS "Products__EAN",
          "Products"."TITLE" AS "Products__TITLE",
          "Products"."CATEGORY" AS "Products__CATEGORY",
          "Products"."VENDOR" AS "Products__VENDOR",
          "Products"."PRICE" AS "Products__PRICE",
          "Products"."RATING" AS "Products__RATING",
          "Products"."CREATED_AT" AS "Products__CREATED_AT",
          "PEOPLE__via__USER_ID"."NAME" AS "PEOPLE__via__USER_ID__NAME",
          "PRODUCTS__via__PRODUCT_ID"."TITLE" AS "PRODUCTS__via__PRODUCT_ID__TITLE"
        FROM
          "PUBLIC"."ORDERS"
         
LEFT JOIN (
            SELECT
              "PUBLIC"."PRODUCTS"."ID" AS "ID",
              "PUBLIC"."PRODUCTS"."EAN" AS "EAN",
              "PUBLIC"."PRODUCTS"."TITLE" AS "TITLE",
              "PUBLIC"."PRODUCTS"."CATEGORY" AS "CATEGORY",
              "PUBLIC"."PRODUCTS"."VENDOR" AS "VENDOR",
              "PUBLIC"."PRODUCTS"."PRICE" AS "PRICE",
              "PUBLIC"."PRODUCTS"."RATING" AS "RATING",
              "PUBLIC"."PRODUCTS"."CREATED_AT" AS "CREATED_AT"
            FROM
              "PUBLIC"."PRODUCTS"
          ) AS "Products" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "Products"."ID"
          LEFT JOIN "PUBLIC"."PEOPLE" AS "PEOPLE__via__USER_ID" ON "PUBLIC"."ORDERS"."USER_ID" = "PEOPLE__via__USER_ID"."ID"
          LEFT JOIN "PUBLIC"."PRODUCTS" AS "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID"
      ) AS "source"
  ) AS "source"
WHERE
  (
    "source"."CREATED_AT_2" >= CAST(DATEADD('day', -30, NOW()) AS date)
  )
 
   AND ("source"."CREATED_AT_2" < CAST(NOW() AS date))
LIMIT
  1048575
```

Complete error:

[error.log](https://github.com/user-attachments/files/22540478/error.log)

### Information about your Metabase installation

```JSON
v56.6.4
```

### Severity

P1

### Additional context

Workaround is to go to the affected model (the "model on top of a model"), make some simple change to it like going to its Edit Metadata screen and changing a column name and then reverting it, and then saving it again. After this, it works again

### PR DESCRIPTION
**Pull request by metamben**
Closes #64058

### Description

The problem reported in #64058 is the result of field reference by a name created in v55 which in v56 gets resolved differently. Instead of the deduplicated name, the reference is expected to contain the join alias (i.e., `Products__CREATED_AT` (v56) instead of `CREATED_AT_2` (v55)).

This PR just adds yet another fallback if the standard resolution methods don't work. This is fixed on master properly, thanks to the the ref work done by @camsaul.

### How to verify

The repro from #64058 should now work.

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/util/add_alias_info.clj [hunk 1]
```diff
@@ -331,10 +331,14 @@
...
-                                (= (::desired-alias opts) desired-column-alias))
-                              all-exports)))))
+              (or (when-let [desired-column-alias (:lib/desired-column-alias col)]
+                    (m/find-first (fn [[_tag _id-or-name opts]]
+                                    (= (::desired-alias opts) desired-column-alias))
+                                  all-exports))
+                  (when-let [field-id-or-name (-> col :field_ref second)]
+                    (m/find-first (fn [[_tag id-or-name _opts]]
+                                    (= id-or-name field-id-or-name))
+                                  all-exports))))))
```
Comment (metamben) [inline src/metabase/query_processor/util/add_alias_info.clj:341]: this is the new fallback.

Comment (camsaul) [reply src/metabase/query_processor/util/add_alias_info.clj:341]: The Field name in `field_ref` in old metadata should be the same as `:name` (which should be the same as `:lib/deduplicated-name`), does it work if you use those instead of `:field_ref`?

Comment (camsaul) [reply src/metabase/query_processor/util/add_alias_info.clj:341]: I'm not sure why `:field_ref` even works at all here since the column should be called `:field-ref` whenever Lib sees it

**Review by camsaul — APPROVED** [review]
