### PR TITLE
Don't notify admins of new SSO users when setting is disabled

### LINKED ISSUE #24381: "NOTIFY ADMINS OF NEW SSO USERS" toggle does not work
https://github.com/metabase/metabase/issues/11384

**Describe the bug**
We've toggled the "notify admins of new SSO users" to off, but we (admins) are still receiving emails about new users.

**To Reproduce**
1. Enable Google SSO.
2. Disable "notify admins of new SSO users."
3. A new users signs in via SSO, and we receive an email.

**Expected behavior**
The expected behavior is that we don't receive any emails.

**Screenshots**

**Information about your Metabase Installation:**
Screen Shot 2022-07-28 at 11 39 37 AM

**Severity**
Not very severe, but it is annoying!

**Additional context**
[This](https://github.com/metabase/metabase/issues/11384) is the closest related bug I could find.

### PR DESCRIPTION
**Pull request by qwef**
Closes https://github.com/metabase/metabase/issues/24381

### How to verify

Describe the steps to verify that the changes are working as expected.

1. tested with maildev turning on/off setting to see if email shows up
2. tested both oss/ee works as intended

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/models/user.clj [hunk 1]
```diff
@@ -2,6 +2,7 @@
   (:require
    [clojure.data :as data]
    [clojure.string :as str]
+   [metabase-enterprise.sso.integrations.sso-settings :as sso-settings]
```
Comment (noahmoss) [inline src/metabase/models/user.clj:5]: You're getting a build error on this PR, I think because you're requiring an EE namespace here and EE code isn't guaranteed to be available.

I think the right approach would be actually to change that setting into a multi-setting using the `define-multi-setting` macro. That allows you to dispatch to two separate setting implementations depending on whether EE functionality is enabled. Take a look at the implementation of `google-auth-auto-create-accounts-domain`; you can probably do something similar and put a multi-setting definition in `metabase.integrations.common`, and just make the OSS implementation non-settable and default it to `true`

File: src/metabase/models/user.clj [hunk 2]
```diff
@@ -330,9 +331,10 @@
   admins will receive an email right away."
   [new-user :- NewUser]
   (u/prog1 (insert-new-user! (assoc new-user :google_auth true))
```
Comment (noahmoss) [inline src/metabase/models/user.clj:333]: The `prog1` macro has `:style/indent` metadata which indicates it should be indented like `defn` (i.e. with the first arg on the same line and subsequent args indented by two spaces). So the previous indentation was actually correct here. Your editor probably doesn't parse the `:style/indent` metadata automatically, although it should work now if you're using Clojure-LSP since Braden [added it a couple months ago](https://metaboat.slack.com/archives/CKZEMT1MJ/p1675265762179199)

**Review by noahmoss — CHANGES_REQUESTED** [review]
on the right track, but I think the `define-multi-setting` approach is the way to go here

File: src/metabase/models/user.clj (hunk 1 above)
Comment (qwef) [reply src/metabase/models/user.clj:5]: Ah I see, I only tested the code with the ee flag turned on. If I understand correctly, would I be placing both the ee and oss implementations (`define-multi-setting-impl`) also in `metabase.integrations.common`?

File: src/metabase/models/user.clj (hunk 2 above)
Comment (qwef) [reply src/metabase/models/user.clj:333]: I think Calva does use Clojure-LSP, though it doesn't recognize the macro here. Not sure why, is there a way to manually run Clojure LSP? I tried the `clj-kondo` command found [here](https://github.com/metabase/metabase/wiki/Migrating-from-Leiningen-to-tools.deps), but there wasn't any changes.

File: src/metabase/models/user.clj (hunk 1 above)
Comment (noahmoss) [reply src/metabase/models/user.clj:5]: I think you can put the base definition and the OSS implementation in that namespace and keep the EE one where it is. EE code needs to be in the `enterprise/` directory so that it's protected by a more restrictive license.

File: src/metabase/integrations/common.clj [hunk 3]
```diff
@@ -51,3 +55,12 @@
         (db/insert! PermissionsGroupMembership :group_id id, :user_id user-id)
         (catch Throwable e
           (log/error e (trs "Error adding User {0} to Group {1}" user-id id)))))))
+
+#_{:clj-kondo/ignore [:missing-docstring]}
```
Comment (noahmoss) [inline src/metabase/integrations/common.clj:59]: Does clj-kondo generate a warning without this line? I added a new multi-setting recently (`audit-max-retention-days`) and didn't get any missing docstring warnings so you might be fine without it.

**Review by noahmoss — APPROVED** [review]
