### PR TITLE
Model X-rays Step 1: x-ray base model and test

### LINKED ISSUE #28674: BE - Update `metabase.automagic-dashboards.core/source` to return a model card rather than its underlying table.
- This is a small change, seems to break no unit tests, and ensures that the number of available fields to create cards from is not oversampled (e.g. We don’t see cards generated from the underlying table)
- Note that the number of fields is undersampled - The reason why is unclear
  - I think it has to do with how our dimensioning system works and this is a separate issue
- Add meaningful unit tests (beyond “This made lots of cards”). Current unit tests set up a scenario (generally not well documented as to why or what the scenario is about) and assert that many cards were created and none failed certain constraints (has name, correct cardinality, correct url, etc.).
    - A key deliverable for this task is to provide a more meaningful test setup and result than the above
    - We should assert both positive and negative field values
        - What dimensions were used
        - No data that is not visible is used
        - Models should produce links to related entities if the entity fields are visible

### PR DESCRIPTION
**Pull request by markbastian**
Fixes #28674

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28705)

### CODE REVIEW

File: src/metabase/automagic_dashboards/core.clj [hunk 1]
```diff
@@ -243,11 +245,15 @@
...
   [card]
   (cond
+    ;; This is a query based on a query. Eventually we will want to change this as it suffers from the same sourcing
+    ;; problems as other cards -- The x-ray is not done on the card, but on its source.
     (nested-query? card) (-> card
                              source-question
                              (assoc :entity_type :entity/GenericTable))
     (native-query? card) (-> card (assoc :entity_type :entity/GenericTable))
-    :else                (->> card table-id (db/select-one Table :id))))
+    ;; This is a non-native question with no ancestors (It is a query on a table).
```
Comment (markbastian) [inline src/metabase/automagic_dashboards/core.clj:254]: This is the only material change to the src branch in this PR. Everything else is cleanup, docs, refactoring for clarification, etc.

File: test/metabase/automagic_dashboards/core_test.clj [hunk 2]
```diff
@@ -208,6 +208,110 @@
             (perms/grant-collection-readwrite-permissions! (perms-group/all-users) collection-id)
             (test-automagic-analysis (db/select-one Card :id card-id) 8)))))))
```
Comment (markbastian) [inline test/metabase/automagic_dashboards/core_test.clj:210]: Step 1: Add some reasonable tests about the actual contents of cards being generated for specific cases. In this PR, the focus is on a model created from a table.

File: src/metabase/automagic_dashboards/core.clj [hunk 3]
```diff
@@ -713,10 +719,13 @@
 (defmethod inject-root Field
   [context field]
   (let [field (assoc field
-                :link   (->> context
-                             :tables
-                             (m/find-first (comp #{(:table_id field)} u/the-id))
-                             :link)
+                :link (->> context
```
Comment (dpsutton) [inline src/metabase/automagic_dashboards/core.clj:722]: Is it possible to add a helpful error in the case it otherwise blows up? Doesn't improve the functionality, but helps in understanding. An error like "Unable to find Table to link root" or something versus "integer is not seqable" or whatever the blow up is here.

Comment (markbastian) [reply src/metabase/automagic_dashboards/core.clj:722]: Yeah, just need to remember how I reproduced this. It was kind of a corner case. Part of the next several steps is putting together more complicated cases to explicitly unearth and test this stuff.

File: src/metabase/api/automagic_dashboards.clj [hunk 4]
```diff
@@ -101,6 +101,10 @@
   [_entity-type segment-id-str]
   (api/read-check (db/select-one Segment :id (ensure-int segment-id-str))))
```
Comment (markbastian) [inline src/metabase/api/automagic_dashboards.clj:103]: This enables the `/auto/dashboard/model/:id` endpoint (vs. question instead of model before).

File: src/metabase/api/automagic_dashboards.clj [hunk 5]
```diff
@@ -101,6 +101,12 @@
...
```
Comment (markbastian) [inline src/metabase/api/automagic_dashboards.clj:103]: Add the `/auto/dashboard/model/:id` route. Note that this will ensure the requested entity is a model, where `/auto/dashboard/question/:id` will not. The latter will still product a model x-ray for a model, but will do something else for questions.

File: src/metabase/automagic_dashboards/core.clj [hunk 6]
```diff
@@ -243,11 +245,15 @@
 (defn- source
   [card]
   (cond
```
Comment (markbastian) [inline src/metabase/automagic_dashboards/core.clj:247]: This is the fundamental logic change -- if the card is a model, x-ray it as a GenericTable. Nearly all other changes are documentation, tests, and refactors for better understanding.

File: src/metabase/automagic_dashboards/core.clj [hunk 7]
```diff
@@ -243,11 +245,15 @@
...
+    ;; This is a non-native question with no ancestors (It is a query on a table).
```
Comment (dpsutton) [inline src/metabase/automagic_dashboards/core.clj:248]: I don't understand this comment. The only thing checked here is if the card is a model. Non-native, no ancestors, even "query on a table" can all be invalidated. I'm not seeing anything the comment really could say and this feels wrong.

File: src/metabase/automagic_dashboards/core.clj [hunk 8]
```diff
@@ -378,39 +384,46 @@
                  (str/starts-with? name "id_")
                  (str/ends-with? name "_id"))))))
 
+(defn- field-spec-pred
+  "Generate a predicate of the form f(field) -> true | false based on a field spec."
```
Comment (dpsutton) [inline src/metabase/automagic_dashboards/core.clj:388]: `f(field)` is a weird way to write a function signature for a lisp

File: src/metabase/automagic_dashboards/core.clj [hunk 9]
```diff
@@ -378,39 +384,46 @@
                  (str/starts-with? name "id_")
                  (str/ends-with? name "_id"))))))
 
+(defn- field-spec-pred
```
Comment (dpsutton) [inline src/metabase/automagic_dashboards/core.clj:387]: what does `spec` mean in this matcher and the `named-spec-pred` and why is it absent from `max-cardinality-pred`?

It's also weird that the `field-spec-pred` matches either on the type or the name, and then there's another matcher to match on the regex.

Can these be broken out to `field-type-matcher`, `name-exact-matcher`, `name-regex-matcher`, `max-cardinality-matcher` or something like that?

File: test/metabase/automagic_dashboards/core_test.clj [hunk 10]
```diff
@@ -208,6 +209,402 @@
...
 
+(deftest field-matching-predicates-test
+  (testing "The field spec predicate should match fields by their fieldspec"
```
Comment (dpsutton) [inline test/metabase/automagic_dashboards/core_test.clj:213]: This doesn't test the `(comp #{fieldspec} :name)` branch of `field-spec-pred`. (I actually think that's ok because it's weird that this matches on the semantic type OR the name if you give it a string)

File: test/metabase/automagic_dashboards/core_test.clj [hunk 11]
```diff
@@ -208,6 +209,402 @@
...
+        (is (nil? (ice-pred category-field))))))
+  (testing "The named spec predicate should match fields by name"
+    (mt/dataset sample-dataset
+      (let [category-field (db/select-one Field :id (mt/id :products :category))]
+        (is (false? ((#'magic/max-cardinality-pred 3) category-field)))
+        (is (true? ((#'magic/max-cardinality-pred 4) category-field)))
+        (is (true? ((#'magic/max-cardinality-pred 100) category-field))))))
+  (testing "Roll the above together and test filter-fields"
+    (mt/dataset sample-dataset
+      (let [category-field (db/select-one Field :id (mt/id :products :category))
```
Comment (dpsutton) [inline test/metabase/automagic_dashboards/core_test.clj:238]: this repetition is begging for a 
```clojure
  (defn field! [table column]
    (or (db/select-one Field :id (mt/id table column))
        (throw (ex-info (format "Did not find %s.%s" (name table) (name column))
                        {:table table :column column}))))
```

File: test/metabase/automagic_dashboards/core_test.clj [hunk 12]
```diff
@@ -208,6 +209,402 @@
...
+               (set (map :id (#'magic/filter-fields {:max-cardinality 5} fields)))))
+        ;; People.Source is rejected here
+        (is (= #{(mt/id :products :category)}
+               (set (map :id (#'magic/filter-fields {:max-cardinality 4} fields)))))))))
+
+(deftest ensure-field-dimension-bindings-test
+  (testing "A very simple card with two plain fields should return the singe assigned dimension for each field."
+    (mt/dataset sample-dataset
+      (mt/with-non-admin-groups-no-root-collection-perms
+        (let [source-query {:database (mt/id)
```
Comment (dpsutton) [inline test/metabase/automagic_dashboards/core_test.clj:268]: This query might be easier to read and write if you use `mt/$ids`

```clojure
(mt/$ids {:source-table $$orders
          :joins [{:fields [&u.people.state
                            &u.people.longitude
                            &u.people.latitude]
                   :source-table $$people
                   :condition [:= $orders.user_id &u.people.id]}]})
...
```

**Review by dpsutton — APPROVED** [review]
I'm approving but left a few comments that could be addressed for clarity.

File: src/metabase/automagic_dashboards/core.clj (hunk 7 above)
Comment (markbastian) [reply src/metabase/automagic_dashboards/core.clj:248]: Yeah, that might be historical and have gotten shifted around. Updating to simply "This is a model".

File: src/metabase/automagic_dashboards/core.clj (hunk 8 above)
Comment (markbastian) [reply src/metabase/automagic_dashboards/core.clj:388]: I was thinking "mathy" but I'll change to `(f field)`.

File: src/metabase/automagic_dashboards/core.clj (hunk 9 above)
Comment (markbastian) [reply src/metabase/automagic_dashboards/core.clj]: Refactored to consistent naming and added more branch testing.

File: test/metabase/automagic_dashboards/core_test.clj (hunk 10 above)
Comment (markbastian) [reply test/metabase/automagic_dashboards/core_test.clj]: Added a test. It's even weirder than that because the fieldspec in this branch has to be named "ga:fieldname."
