### PR TITLE
Fix send once alerts repeatedly sending

### LINKED ISSUE #56978: Alerts are repeated even with 'Only send this alert once' enabled
### Describe the bug

**Only send this alert once** does not seem to work on v1.54.3

### To Reproduce

1. Create any question

2. Set up an email alert that triggers, enable Only send this alert once

Image

3. See repeated alerts coming in
Image

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-04-15",
      "tag": "v1.54.3",
      "hash": "6b5b460"
    },
    "settings": {
      "report-timezone": "US/Central"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Reported by a customer - P1 if this is a regression

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Closes https://github.com/metabase/metabase/issues/56978

### CODE REVIEW

File: src/metabase/notification/send.clj [hunk 1]
```diff
@@ -179,7 +179,7 @@
                             (channel-send-retrying! id payload_type handler message)))
                         (catch Exception e
                           (log/warnf e "Error sending to channel %s" (handler->channel-name handler))))))))
-              (do-after-notification-sent notification-info notification-payload)
+              (do-after-notification-sent hydrated-notification notification-payload)
```
Comment (qnkhuat) [inline src/metabase/notification/send.clj:182]: `do-after-notification-sent` requires fully hydrated notification to work, especially it needs the `:payload` to be hydrated.

File: test/metabase/notification/payload/impl/card_test.clj [hunk 2]
```diff
@@ -408,14 +408,15 @@
...
     [notification {:notification-card {:send_once true}}]
-    (testing "do not archive if the send fail for any reason"
-      (mt/with-dynamic-fn-redefs [notification.payload/notification-payload (fn [& _args] (throw (ex-info "error" {})))]
-        (u/ignore-exceptions (notification/send-notification! notification))
-        (is (true? (t2/select-one-fn :active :model/Notification (:id notification))))))
-
-    (testing "archive if the send is successful"
-      (notification/send-notification! notification)
-      (is (false? (t2/select-one-fn :active :model/Notification (:id notification)))))))
+    (let [notification (t2/select-one :model/Notification (:id notification))]
```
Comment (qnkhuat) [inline test/metabase/notification/payload/impl/card_test.clj:411]: this test was not catching the bug before because notification here is already fully hydrated, and when sending notification we skip hydration for it.

In the sending notification from quartz path, the notification is not hydrated.

**Review by crisptrutski — APPROVED** [review]
