### PR TITLE
fix(sdk): fix data picker crash by using mantine popover

### LINKED ISSUE #51906: Notebook data picker throws an error in the sdk's starter kit environment
When rendering the the notebook's data picker in the Embedding SDK starter kit at https://github.com/metabase/metabase-nodejs-react-sdk-embedding-sample, the component throws a Tether error due to the old data picker causing crashes.

The same error does not show up when rendering  the notebook data picker in the Storybook environment and in the [Shoppy demo app](https://embedded-analytics-sdk-demo.metabase.com).

This is reproducible by rendering either the `<CreateQuestion />` component, or the notebook editor inside interactive question:

```tsx
<InteractiveQuestion>
  <InteractiveQuestion.Editor />
</InteractiveQuestion>
```

### Stacktrace

```tsx
Error: Tether Error: Both element and target must be defined
    at tether.js:700:1
    at Array.forEach (<anonymous>)
    at TetherClass2.setOptions (tether.js:698:1)
    at new TetherClass2 (tether.js:640:1)
    at Popover._setTetherOptions (Popover.jsx:293:1)
    at Popover._getBestAttachmentOptions (Popover.jsx:338:1)
    at Popover.updateComponentPosition (Popover.jsx:145:1)
    at Popover.componentDidMount (Popover.jsx:121:1)
    at invokeLayoutEffectMountInDEV (react-dom.development.js:25172:22)
    at invokeEffectsInDev (react-dom.development.js:27390:11)
```

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/51906

### Description

Rendering the data picker in the starter kit (https://github.com/metabase/metabase-nodejs-react-sdk-embedding-sample) such as with `<CreateQuestion />` or with `InteractiveQuestion.Editor` causes the following crash.

```tsx
Error: Tether Error: Both element and target must be defined
    at tether.js:700:1
    at Array.forEach (<anonymous>)
    at TetherClass2.setOptions (tether.js:698:1)
    at new TetherClass2 (tether.js:640:1)
    at Popover._setTetherOptions (Popover.jsx:293:1)
    at Popover._getBestAttachmentOptions (Popover.jsx:338:1)
    at Popover.updateComponentPosition (Popover.jsx:145:1)
    at Popover.componentDidMount (Popover.jsx:121:1)
    at invokeLayoutEffectMountInDEV (react-dom.development.js:25172:22)
    at invokeEffectsInDev (react-dom.development.js:27390:11)
```

Note that this crash cannot be reproduced in both the Storybook environment and in the [Shoppy demo app](https://embedded-analytics-sdk-demo.metabase.com) - it only happens in our starter kit.

A similar popover error happened before in https://github.com/metabase/metabase/issues/45488 in the parameter popover, and Oisin fixed this in in https://github.com/metabase/metabase/pull/45671 by replacing the legacy Popover with Mantine's. To quote Oisin:

> In the PopoverWithTrigger that we were using, there are issues with the usage of Tether (for a reason I still can't figure out) that cause the referred target to turn to null - something to the effect of the target component unmounting causes this error. The solution here is to get rid of this PopoverWithTrigger and replace it with the Mantine popover, which hasn't given us any issues on the SDK so far, so I felt it was a better option than attempt to debug deprecated code.

### How to verify

In the Embedding SDK

- Render the `<CreateQuestion />` component (or `InteractiveQuestion` with `InteractiveQuestion.Editor`)
- Run the demo again. It should crash
- Setup the starter kit via https://github.com/metabase/metabase-nodejs-react-sdk-embedding-sample
- Build the module locally via `yarn build-embedding-sdk`
- Link the locally built package to the starter kit.
   - Example: `rm -rf node_modules/.vite && rm -rf node_modules/@metabase/ && yarn add file:../../metabase/resources/embedding-sdk && env NODE_OPTIONS="--max-old-space-size=7000" yarn dev`. Tweak this to match your own folder structure.
- Run the demo again. It should no longer crash.

In the Metabase app

- Create a new SQL question
- The database dropdown should work as expected with no visual glitches

### Demo

The database dropdown in the SQL editor looks and works as before in the main Metabase app

CleanShot 2568-01-15 at 19 28 02@2x

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx [hunk 1]
```diff
@@ -164,7 +163,6 @@ export class UnconnectedDataSelector extends Component {
     tableFilter: PropTypes.func,
     hasTableSearch: PropTypes.bool,
     canChangeDatabase: PropTypes.bool,
-    containerClassName: PropTypes.string,
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx:167]: Unused.

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx [hunk 2]
```diff
@@ -811,7 +809,7 @@ export class UnconnectedDataSelector extends Component {
 
     return (
       <Trigger
-        className={className}
+        className={cx(this.getTriggerClasses(), className)}
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx:812]: Move the trigger classes into the trigger, as we are using Mantine's Popover.

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx [hunk 3]
```diff
@@ -872,15 +870,17 @@ export class UnconnectedDataSelector extends Component {
...
-          <DataBucketPicker
-            dataTypes={getDataTypes({
-              hasModels: this.hasModels(),
-              hasNestedQueriesEnabled,
-              hasSavedQuestions: this.hasSavedQuestions(),
-              hasMetrics: this.hasMetrics(),
-            })}
-            {...props}
-          />
+          <Box p="sm">
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx:873]: Padding is moved to a parent container. See notes below.

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.module.css [hunk 4]
```diff
@@ -1,6 +1,5 @@
 .DataBucketList {
   width: 300px;
-  padding: 4px 8px 12px;
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.module.css:3]: This padding is moved to the parent container, as this is overridden by this line as non-Mantine SelectList uses `ul` underneath, cc @oisincoveney 

https://github.com/metabase/metabase/blob/c7b50a14267e2fa065b759453e9c9998e3fa5833/enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx#L68

File: frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.module.css [hunk 5]
```diff
@@ -1,7 +1,6 @@
 .SavedEntityListRoot {
   overflow: auto;
   width: 100%;
-  padding: 0.5rem;
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.module.css:4]: padding moved to the parent container for the same reason as above

File: frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.tsx [hunk 6]
```diff
@@ -49,42 +49,44 @@ const SavedEntityList = ({
...
-        className={SavedEntityListS.LoadingWrapper}
-        loading={!collection || isFetching}
-        error={error}
-      >
-        <Fragment>
-          {list.map(collectionItem => {
-            const { id, name, moderated_status } = collectionItem;
-            const virtualTableId = getQuestionVirtualTableId(id);
+    <Box p="sm" w="100%">
+      <SelectList className={SavedEntityListS.SavedEntityListRoot}>
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.tsx:53]: wrapped this container with `<Box p="sm">` as the padding is moved here

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx [hunk 7]
```diff
@@ -1075,24 +1075,17 @@ export class UnconnectedDataSelector extends Component {
...
-          triggerClasses={this.getTriggerClasses()}
-          hasArrow={this.props.hasArrow}
-          tetherOptions={this.props.tetherOptions}
-          sizeToFit
-          isOpen={this.props.isOpen}
+        <Popover
+          opened={this.props.isOpen}
           onClose={this.handleClose}
+          position="bottom-start"
         >
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx:1082]: Uses the Mantine popover instead of the legacy popover.

**Review by uladzimirdev — COMMENTED** [review]
LGTM

**Review by uladzimirdev — APPROVED** [review]
LGTM

**Review by npretto — APPROVED** [review]
Verified the crash and the fix 🚀

**Comment by heypoom** [comment]
Ouch, the DataSelector components are also used by the native query editor and FilteredToUrlTable, not just the LegacyDataPicker used by embedding, and this PR would have wrecked both if we merged it as-is. Thankfully the E2E and unit tests caught this early before we merge 😨 

CleanShot 2568-01-15 at 18 59 52@2x
