### PR TITLE
Fix joins with incomplete conditions are removed on query run

### LINKED ISSUE #17710: Notebook: joins on multiple fields are removed if contain at least one incomplete condition
**Describe the bug**
Originally described in [this comment](https://github.com/metabase/metabase/pull/17633#issuecomment-908330423) from #17633. In notebook editor, if you have an incomplete join condition (e.g. you specified the left join field, but not the right one), once you click "Visualise" to run the query, the whole join gets removed. [It worked that way earlier](https://github.com/metabase/metabase/pull/17633#issuecomment-908527953), but with joins on multiple fields it became much easier to face the problem.

**To Reproduce**

1. Ask a question > Custom Question > Sample Dataset > Orders
2. Join the Products table, you should see Metabase automatically suggests joining on `PRODUCT_ID` FK
3. Click "Visualize", then open the notebook editor back (with an icon in the top right corner). You should see the join sections
4. Click the "+" icon on the right side of the join section. Two cells with "Pick a column..." labels should appear. Don't touch them or select only one of them.
5. Click "Visualize" again, open the notebook editor back. You can see the whole join section disappeared.

**Expected behavior**
The incomplete conditions should either stay on the UI, but not affect the query. Or only the incomplete conditions have to be removed.

**Demo**

https://user-images.githubusercontent.com/17258145/131648654-ae32b136-6adb-4be0-a739-a33472560016.mov

**Information about your Metabase Installation:**

Metabase v0.41.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by kulyk**
Followup on [this comment](https://github.com/metabase/metabase/pull/17633#issuecomment-908330423) from #17633. In notebook editor, if you have an incomplete join condition (e.g. you specified the left join field, but not the right one), once you click "Visualise" to run the query, the whole join gets removed. [It worked that way earlier](https://github.com/metabase/metabase/pull/17633#issuecomment-908527953), but with joins on multiple fields it became much easier to face the problem.

This happens because of the current "query lifecycle" in the notebook editor. Right before Metabase runs the query after a user clicks "Visualize", it invokes the `StructuredQuery's` [`clean` method](https://github.com/metabase/metabase/blob/cd758c966f59beddfeb75eae64ac54020dbfa9af/frontend/src/metabase-lib/lib/queries/StructuredQuery.js#L324) that removes invalid MBQL clauses from it.

A [`Join` instance](https://github.com/metabase/metabase/blob/cd758c966f59beddfeb75eae64ac54020dbfa9af/frontend/src/metabase-lib/lib/queries/structured/Join.js#L538) is considered invalid if at least one join field is not specified (left or right). Right now, multiple fields join would be treated as invalid if it has _just one_ incomplete pair of fields. E.g. we join Orders and Products on `orders.PRODUCT_ID = products.ID` and have a `orders.CREATED_AT = N/A`. Because of a single missed field, the whole join will be removed, no matter how many valid field pairs it has.

Reproduces #17710, fixes #17710

**About the fix**

This PR adds a `clean` method to `Join` that would remove incomplete conditions and keep the valid ones. So if we join Orders and Products on `orders.PRODUCT_ID = products.ID` and have a `orders.CREATED_AT = N/A`, after `clean` is invoked, the join will only contain the `orders.PRODUCT_ID = products.ID` condition.

On top of that, this PR updates `StructuredQuery's` `cleanJoins` method. Normally `cleanJoins` will just drop any invalid join (and lose the valid conditions). In this PR, it starts by sequentially calling `join.clean()` for every join the query has. After that, it follows the rest of the `cleanJoins` flow, but now `cleanJoins` will only remove completely invalid joins (e.g. ones without a table / any field / just one field specified).

### To Verify

1. Ask a question > Custom Question > Sample Dataset > Orders
2. Join the Products table, you should see Metabase automatically suggests joining on `PRODUCT_ID` FK
3. Click "Visualize", then open the notebook editor back (with an icon in the top right corner). You should see the join sections
4. Click the "+" icon on the right side of the join section. Two cells with "Pick a column..." labels should appear. Don't touch them. Click "Visualize" again, open the notebook editor back. You should see two empty cells disappeared, but the `PRODUCT_ID` condition has to be there.
5. Click the "+" icon again, but select _just a one_ field now (left OR right). Click "Visualize" again, open the notebook editor back. You should see the incomplete condition disappeared, but the `PRODUCT_ID` condition has to be there.

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/131647933-9a274d1c-43be-4d00-8c92-e66bff58b99e.mov

**After**

https://user-images.githubusercontent.com/17258145/131647955-53b74609-109c-4361-97d6-f8ceb0100dd2.mov

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx [hunk 1]
```diff
@@ -147,7 +152,12 @@ export default class NotebookStep extends React.Component {
 
     return (
       <ExpandingContent isInitiallyOpen={!isLastOpened} isOpen>
-        <Box mb={[1, 2]} pb={[1, 2]} className="hover-parent hover--visibility">
+        <Box
+          mb={[1, 2]}
+          pb={[1, 2]}
+          className="hover-parent hover--visibility"
+          data-testid={getTestId(step)}
+        >
```
Comment (kulyk) [inline frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx:160]: @nemanjaglumac this change adds a test ID to every notebook step. It looks pretty difficult to select a specific step in Cypress, so I tried to simplify this just a bit. Please share your feedback.

Test ID structure:

1. Just a "step" word
2. Step's type (data / join / filter / summarize, etc.)
3. Step's stage index. If a question has a complete Summarize section, you can add joins, filters, sorting, and other breakouts on top of that query. In this case, the notebook is split into "stages". Step's stage index identifying to which stage the step belongs
4. Step's item index. If a question has let's say a few joins in a row, they would have unique item indexes

See a screenshot with an example:

CleanShot 2021-09-01 at 13 19 55@2x

Comment (kulyk) [reply frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx:160]: Thinking out loud: maybe we can also have a cypress helper looking something like that:

```js
function findNotebookSection(type, { stage = 0, index = 0 }) {
   return cy.findByTestId(`step-${type}-${stage}-${index}`);
}

// Usage

findNotebookSection("join") // returns first join section
findNotebookSection("join", { index: 1 }) // returns second join section
findNotebookSection("join, { stage: 1 }) // returns first join section in the second stage
```

**Review by flamber — COMMENTED** [review]
This works great - exactly like how I would expect, only removing invalid stuff and not entire sections (and possible dependencies)

File: frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx:160]: Thank you for putting this together. It is very much needed.
Just a qq: shouldn't `step-filter` from the screenshot be `0-0`?

This seems good to me as the first step, and we can work on the Cypress helper next.
With just slightly better HTML and CSS structure, we might not even need data-testids, but that's a whole different story.

Once again, let's go with this.
Thank you <3

Comment (kulyk) [reply frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx:160]: Oh my bad, it would be `step-filter-0-0`. Happy to help!

**Review by daltojohnso — APPROVED** [review]
nice!
