### PR TITLE
Fix crash when navigating between bookmarked dashboards

### LINKED ISSUE #47170: App crashes when navigating between dashboards
### Describe the bug

https://github.com/user-attachments/assets/6c802894-d0f9-405b-ae14-acd2dbc65cb8

Error in JS console:
```
Error: {status: 0, data: '', isCancelled: true}
```

### To Reproduce

1. Create and bookmark 2 dashboards 
2. Open app sidebar
3. Throttle your network (or use stats instance) or be quick with the next steps
4. Navigate to 1st dashboard
5. Open app sidebar
6. Navigate to 2nd dashboard

### Information about your Metabase installation

master, 743ae09aca

### Severity

P2

### PR DESCRIPTION
**Pull request by kulyk**
Fixes #47170

The PR updates the dashboard fetching logic, so it no longer calls `setErrorPage` for canceled request exceptions.

Would appreciate ideas on test coverage for this: I believe a Cypress test would be too flaky for bugs like that, and I failed to tune request timing/sequencing in a Jest test for this :/

### To verify

1. Create and bookmark 2 dashboards
2. Open app sidebar
3. Throttle your network (or use stats instance) or be quick with the next steps
4. Navigate to 1st dashboard
5. Open app sidebar
6. Navigate to 2nd dashboard
7. Ensure there're no visible errors

### Demo

**Before**

https://github.com/user-attachments/assets/0f1d7ff3-3f04-4683-951a-534e02de5895

**After**

https://github.com/user-attachments/assets/abec24e1-5b90-4086-a240-e7e92a14a404

### CODE REVIEW

**Review by EmmadUsmani — APPROVED** [review]
Fix itself looks good. Regarding tests, it might not be the most useful/accurate test, but something that you can do easily is extracting the body of `handleLoadDashboard` into its own function, and using mock functions in jest making sure that `setErrorPage` is not called when `isCancelled` is true

**Comment by kulyk** [comment]
> Fix itself looks good. Regarding tests, it might not be the most useful/accurate test, but something that you can do easily is extracting the body of `handleLoadDashboard` into its own function, and using mock functions in jest making sure that `setErrorPage` is not called when `isCancelled` is true

Thanks! I've tried to do that, but IMO it ended up making the code harder to parse and reason about. And, as you mentioned, the test itself ends up being not so robust and useful. I gonna merge this as is, but happy to tweak this if we come up with something

File: frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx [hunk 1]
```diff
@@ -258,7 +258,10 @@ function Dashboard(props: DashboardProps) {
       });
 
       if (!isSuccessfulFetchDashboardResult(result)) {
-        setErrorPage(result.payload);
+        const payload = result.payload as { isCancelled?: boolean };
```
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx:261]: Please use a type guard instead of a cast - `result.payload` is `unknown` and this code can fail in case `payload` is `null` or `undefined`.

**Review by kamilmielnik — COMMENTED** [review]
> Would appreciate ideas on test coverage for this: I believe a Cypress test would be too flaky for bugs like that, and I failed to tune request timing/sequencing in a Jest test for this :/

We should not try to mock this in unit tests.
We should be able to reliably reproduce it in e2e tests by [throttling requests](https://docs.cypress.io/api/commands/intercept#Throttle-or-delay-response-all-incoming-responses).

**Comment by kulyk** [comment]
@kamilmielnik thank you for great suggestions! Implemented in #47400
