### PR TITLE
SQL Server doesn't cast when compiling uuid field filters

### LINKED ISSUE #51189: Cannot Filter on UUID ID Columns in SQL Server / Azure Synapse
### Describe the bug

Cannot filter on any UUID columns in azure synapse. Receive the error:
"Unsupported parameter type found while parsing RPC request. The request has been terminated."

From the GUI editor you can get this error by applying a filter. But if you take the generated SQL and run it directly from the native editor it works.

### To Reproduce

Haven't been able to repro outside the customer instance yet. Tried setting up a local test with SQL server but had no luck. it's unclear if the fact that these are UUIDs is specifically relevant.

### Expected behavior

Filtering should work.

### Logs

Added diagnostic export to Slack:
https://metaboat.slack.com/archives/C05NXACAG1G/p1733961071267499

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "sqlserver"
    ],
    "run-mode": "prod",
    "plan-alias": "starter",
    "version": {
      "date": "2024-12-03",
      "tag": "v1.51.6.5",
      "hash": "22b76e9"
    },
    "settings": {
      "report-timezone": "Europe/Amsterdam"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

hindering use of several dashboards

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wzimrin**
Closes https://github.com/metabase/metabase/issues/51189

### Description

Apparently, a filter like `blah in (cast([uuid] as uuid))` is fine in postgres, but sqlserver doesn't like it very much.  This gives sql server the syntax it needs.

### How to verify

Follow steps in case

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/test/data/sql.clj [hunk 1]
```diff
@@ -323,15 +323,17 @@
...
+   (tx/count-with-field-filter-query driver table field 1))
+  ([driver table field sample-value]
+   (driver/with-driver driver
+     (let [mbql-query      (data/mbql-query nil
+                             {:source-table (data/id table)
+                              :aggregation  [[:count]]
+                              :filter       [:= [:field-id (data/id table field)] sample-value]})
+           {:keys [query]} (qp.compile/compile mbql-query)
+           query           (str/replace query (re-pattern #"WHERE .* = .*") (format "WHERE {{%s}}" (name field)))]
+       {:query query}))))
```
Comment (wzimrin) [inline test/metabase/test/data/sql.clj:336]: For whatever reason, trying to use this function to generate a query on a uuid field breaks when you are using a 1 as the sample value -- it complains about being unable to cast a long to a string.  Adding the option to specify the sample value gives me a workaround.

**Review by bshepherdson — APPROVED** [review]
