### PR TITLE
Fix root collection links in sidebars

### LINKED ISSUE #48257: Broken root collection link in dashboard info sidebar
### Describe the bug

https://github.com/user-attachments/assets/865876f7-6299-40cb-8d8d-18f4e1ca8df3

### To Reproduce

1. Create a new dashboard and save it in "Our analytics" collection
2. Open dashboard
3. Open "more info" pane
4. Click link to the collection it's "Saved in"

### Information about your Metabase installation

master, 3a3785d27b

### Severity

P2

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/48257

### Description

Ye olde root collection has a null id rears its ugly head again.

### How to verify

- Questions and Dashboards in the root collection now have links to `/collection/root` instead of `/collection/null` in their sidebars

Screen Shot 2024-10-02 at 8 23 23 AM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardDetails.tsx [hunk 1]
```diff
@@ -68,7 +68,7 @@ export const DashboardDetails = ({ dashboard }: { dashboard: Dashboard }) => {
           <div>
             <Text>
               <Link
-                to={`/collection/${dashboard.collection_id}`}
+                to={`/collection/${dashboard.collection_id ?? "root"}`}
```
Comment (rafpaf) [inline frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardDetails.tsx:71]: I think `Urls.collection` also handles this

`frontend/src/metabase/lib/urls/collections.ts:41`

**Review by rafpaf — APPROVED** [review]

**Comment by rafpaf** [comment]
I'd recommend `Urls.collection` but otherwise looks good
