### PR TITLE
Fix non-legible text and icon colors in fullscreen dark mode

### LINKED ISSUE #51524: CSS issue: Metabase Dashboards that display a bunch of table data are nearly invisible in dark mode
### Describe the bug

Hello, we're running latest Metabase 52.2.3, JDK 17 on linux/mysql8.

I don't know which exact release this broke in, but a lot of our dashboards are nearly invisible in dark mode/full screen.  I've redacted some of the data below with background colors, but you can see below that the dark text on a dark background is nearly impossible to read.

Image

We're happy long time Metabase users and continue to recommend the platform to everyone we know. Thank you for your consideration! To avoid creating additional work, I did search for existing bugs on this but did not find a similar one. If my search was ineffective, my apologies for adding a duplicate ticket, please feel free to close this and link me to the correct one.

### To Reproduce

1. Create a dashboard with a tables
2. Enter Full screen and select dark mode
3. Squint

### Expected behavior

These were legible up to a recent release, I imagine this was just an oversight. I believe the bug existed in 52.2.2 as well

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-12-14",
      "tag": "v0.52.3",
      "hash": "6f76bb6"
    },
    "settings": {
      "report-timezone": "US/Central"
    },
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.39-30"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.12+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.12+7",
    "os.name": "Linux",
    "os.version": "5.15.0-126-generic",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  }
}
```

### Severity

Blocking Some Usages/Obnoxious, but there is a workaround: use light mode

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/51524

### Description

The color of the table text, dashboard title and toolbar icon are not legible in the fullscreen dashboard's dark mode. We should use the same legible color mapping as dark mode in embedding.

### Demo

Before:

CleanShot 2567-12-20 at 02 36 17@2x

CleanShot 2567-12-20 at 02 36 24@2x

After:

CleanShot 2567-12-20 at 02 48 44@2x

CleanShot 2567-12-20 at 02 48 37@2x

### How to verify

- Go to a dashboard
- Click on "Fullscreen"
- Click on "Dark Mode" icon
- The above should be legible now. It should be similar to what we have in static embedding's dark mode.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR - E2E

### CODE REVIEW

File: frontend/src/metabase/components/ToolbarButton/ToolbarButton.tsx [hunk 1]
```diff
@@ -51,6 +52,7 @@ export const ToolbarButton = forwardRef(function ToolbarButton(
       onClick={handleButtonClick}
       bg={hasBackground ? undefined : "transparent"}
       disabled={disabled}
+      c="var(--mb-color-text-primary)"
```
Comment (heypoom) [inline frontend/src/metabase/components/ToolbarButton/ToolbarButton.tsx:54]: For some strange reason `c="text-dark"` did not work, and creating a `ToolbarButton.module.css` class and adding it here did not work. I have no idea why.

File: frontend/src/metabase/css/dashboard.module.css [hunk 2]
```diff
@@ -6,6 +6,28 @@
 
 /* Night mode */
 .Dashboard.DashboardNight {
+  /**
+    * Apply dark mode colors to semantic color variables.
+    * Referenced from EmbedFrame.module.css
```
Comment (heypoom) [inline frontend/src/metabase/css/dashboard.module.css:11]: It would be best to share a selector for dark mode that would combine `.DashboardNight` for dashboard and `[data-metabase-theme="night"][data-metabase-theme="night"]` for embedding, but let's do that later.

**Review by alxnddr — APPROVED** [review]

File: frontend/src/metabase/css/dashboard.module.css (hunk 2 above)
Comment (npretto) [reply frontend/src/metabase/css/dashboard.module.css:11]: If we have to change the theme logic, I think it would be best to use the theme provider that we use in the sdk, we shouldn't have too many ways of styling things, especially because the underlying themed components are the same

**Review by npretto — APPROVED** [review]
