### PR TITLE
Nested queries revamp base

### LINKED ISSUE #12649: Table joins and Custom Column returns same results for columns with the same name
**Describe the bug**
A question with joins and a Custom Column, will overwrite results from same-named columns.

**Logs** No errors.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Join Products on ProductID=ID - result should look like this (correct):
image
3. Now add Custom Column, formula `1+1`, name `X`
Notice that all columns with the same name have the same result. First column `ID` is showing the value of `Product.ID`, and `Product.CreatedAt` is showing value of `CreatedAt`
image

**Information about your Metabase Installation:**
Metabase 0.35.0, 0.35.1, 0.35.2, 0.35.4 and `master` - multiple backends and stats.

**Additional context**
Results are correct in 0.35.3
Maybe related to what fixed #12588, which only existed in 0.35.3

### PR DESCRIPTION
**Pull request by sbelak**
This lays the groundwork for nested queries (and sanboxing) fixes. Fundamentally it does 4 (related) things:
1) allows `field-id` to be used for fields from a source query
2) improves how we flow metadata for fields
3) cleans up how we generate SQL for queries with expressions 
4) changes our SQL generation to decorate fields with table name prefix 

## Limitations

* We still don't handle well the case where source query has two joins to the same table that both pull in the same fields. This is not so much a limitation of the current approach as it is of MBQL semantics. The problem is we don't have a good way to reference such fields. This is one area where the existing approach with `field-literals` was superior. It however relied on an implementation detail of how we disambiguate duplicate names (by appending __N) which in itself is quite brittle as it's position-dependent. This means that small changes to the source query could cause the order of how we process and name fields change, and break things (or alternatively it places another invariant on the query processing pipeline that ordering has to be stable). In addition it also means more work for the frontend as dropping columns can mean that `field-literal` references become invalid. I think that the best long-term solution is to introduce an options argument to `field-id` which could be used to disambiguate via something like `:source_alias` clause.  

* The metadata flowing is currently aggressive only for fields because we can be aggressive about matching via ID and it's the most common case of clashes. The approach taken should work just as well for things referred to by `field-id`, but is something I would attempt only after (& if) we implement `:source_alias` clause from above. Issues here can only arise if you do something silly like using the same expression name for multiple different expressions; or shadowing field names with expression names or aggregation names; etc. 

* Table name prefix could be insufficient if you do weird stuff and join from tables with the same name but different schemas. I was unsure whether to make the names even uglier to work around that. We could easily modify `unambiguous-field-alias` to either include the schema, or change it to a hash of table name + table schema, or similar.

- Fixes: 
    - #12649, ✅
    - #12762, ✅
    - metabase/metabase-enterprise#520,
    - metabase/metabase-enterprise#154,
    - metabase/metabase-enterprise#524,
    ... [more to be added as I put back the tests]

### CODE REVIEW

File: src/metabase/query_processor/middleware/annotate.clj [hunk 1]
```diff
@@ -58,10 +58,9 @@
 ;;; |                                      Adding :cols info for native queries                                      |
 ;;; +----------------------------------------------------------------------------------------------------------------+
 
-(defn- check-driver-native-columns
+(s/defn ^:private check-driver-native-columns
   "Double-check that the *driver* returned the correct number of `columns` for native query results."
-  [cols rows]
-  {:pre [(sequential? cols) (every? map? cols)]}
+  [cols :- [{s/Any s/Any}], rows]
```
Comment (sbelak) [inline src/metabase/query_processor/middleware/annotate.clj:63]: This felt cleaner as we want to also support the version where `cols` = nil

**Comment by rlotun** [comment]
just a reminder that there is a reproduction for bug this issue closes - see info at https://github.com/metabase/metabase/pull/13557

File: test/metabase/query_processor_test/explicit_joins_test.clj [hunk 2]
```diff
@@ -387,22 +380,24 @@
       (tt/with-temp Card [{card-id               :id
                            {source-query :query} :dataset_query
                            source-metadata       :result_metadata} (qp.test-util/card-with-source-metadata-for-query
-                                                                    (mt/mbql-query checkins
+                                                                    (mt/mbql-query venues
```
Comment (sbelak) [inline test/metabase/query_processor_test/explicit_joins_test.clj:383]: I've changed this query because the self join was confusing and was detracting from what's really the point.

File: src/metabase/driver/sql/query_processor.clj [hunk 3]
```diff
@@ -301,7 +312,8 @@
 
 (defmethod ->honeysql [:sql :joined-field]
   [driver [_ alias field]]
-  (binding [*table-alias* alias]
+  (binding [*table-alias*   alias
```
Comment (sbelak) [inline src/metabase/driver/sql/query_processor.clj:315]: This is ugly and it's making me sad. I'm torn between using a flag and introducing `*join-alias*`. In the latter case `->honeysql` for `:joined-field` would only set `*join-alias*`, and we'd use `(or *joined-alias* *source-alias)` where relevant.

Adjacent to the issues around `:source_alias` I mention above.

**Comment by sbelak** [comment]
The EE test that's failing requires #13715 to be done

**Review by camsaul — APPROVED** [review]
This works for me

**Comment by rlotun** [comment]
can we publish this PR? it looks like we have an approved draft PR, which seems a bit strange

**Review by camsaul — APPROVED** [review]

**Comment by sbelak** [comment]
Oracle before 12.2 apparently doesn't like identifier names > 30. Do we sacrifice some readability of the generated SQL and just use a hash prefix, or do we do some driver-specific truncation?

**Comment by sbelak** [comment]
Probably makes more sense to push the name limit to the drivers so we also fix #9204. With Oracle the issue is somewhat more pernicious though as it comes up during our regular tests and if we mangle names differently for different dbs a lot of tests will break.

**Comment by nemanjaglumac** [comment]
[metabase/metabase-enterprise#520](https://github.com/metabase/metabase-enterprise/issues/520) is still failing:

image

**Comment by nemanjaglumac** [comment]
[metabase/metabase-enterprise#154](https://github.com/metabase/metabase-enterprise/issues/154) is still failing:

image

File: modules/drivers/oracle/src/metabase/driver/oracle.clj [hunk 4]
```diff
@@ -127,6 +129,30 @@
...
+
+(defn- truncate-identifier
+  [identifier]
+  (->> identifier
+       hash
+       str
+       (map (fn [digit]
+              (-> digit
+                  int
+                  (+ 65)
```
Comment (rlotun) [inline modules/drivers/oracle/src/metabase/driver/oracle.clj:144]: where does the 65 come from?

**Review by rlotun — CHANGES_REQUESTED** [review]
1. Seems like we need to unskip the test for EE#520: https://github.com/metabase/metabase/commit/e1e4278a4ee3b1487b84a32f1197f87865b9e6d0#diff-0b620ecf37aabe49d79827f61977722016f157674b390a23f28e1ac1096b8a79R779-R795

2. We should also unskip the tests for EE#154: https://github.com/metabase/metabase/commit/394dfa83f37628118a09f286e74eb3ff037ec73d#diff-0b620ecf37aabe49d79827f61977722016f157674b390a23f28e1ac1096b8a79R278-R284

~~3. We need to unskip tests for EE#524: https://github.com/metabase/metabase/pull/13902/files#diff-0b620ecf37aabe49d79827f61977722016f157674b390a23f28e1ac1096b8a79R577-R584~~

**Comment by sbelak** [comment]
FK remappings in nested queries/sandboxes now work again (part of ee/520 regression).

**Comment by nemanjaglumac** [comment]
> FK remappings in nested queries/sandboxes now work again (part of ee/520 regression).

Can you please unskip EE_520 to make sure this indeed works. Also, if there are any other related issues that may be fixed by this, they should be unskipped as well.

**Comment by sbelak** [comment]
It fixes one half or the issues in 520? Should I split the cypress test in two so each can be done individually or just wait until I have the full fix

**Comment by nemanjaglumac** [comment]
> It fixes one half or the issues in 520? Should I split the cypress test in two so each can be done individually or just wait until I have the full fix

No. Please don't. Let's wait for the full fix in that case 💪

**Comment by sbelak** [comment]
Fixed the regressions and re-enabled cypress tests for ee/520 & ee/154. Everything green

**Review by rlotun — APPROVED** [review]

File: modules/drivers/oracle/src/metabase/driver/oracle.clj (hunk 4 above)
Comment (camsaul) [reply modules/drivers/oracle/src/metabase/driver/oracle.clj:144]: 65 is ASCII `A` so I'm guess Simon is converting the digits in the truncated identifier here to letters

**Review by camsaul — APPROVED** [review]

File: modules/drivers/oracle/src/metabase/driver/oracle.clj (hunk 4 above)
Comment (rlotun) [reply modules/drivers/oracle/src/metabase/driver/oracle.clj:144]: yeah, realized after ;-)
