### PR TITLE
Fix segments revision history

### LINKED ISSUE #45577: Segments revision history is broken
### Describe the bug

Segments revision history is broken.
The loading spinner keeps spinning ad infinitum, and the request fails.

### To Reproduce

1. Go to `admin/datamodel/segments`
2. Create a segment if you don't already have one
3. Click on `...` next to the segment and select "Revision history"
image
4. The page is stuck on a loader
image

The console has a failed request because the `:entity` parameter is `undefined`
`GET http://localhost:3000/api//1/revisions` returns `400`

The correct URL should be `http://localhost:3000/api/segment/1/revisions`
https://www.metabase.com/docs/latest/api/segment#get-apisegmentidrevisions

### Expected behavior

Segments should load the revision history.

### Logs

_No response_

### Information about your Metabase installation

```JSON
local dev, master, 51c1d83, H2, Sample database
```

### Severity

P1

### Additional context

This is a regression in `master` only. It works correctly in x.50.13.

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### What does this PR accomplish?
This PR fixes #45577 and adds an E2E test to prevent further regressions.

### Demo
**datamodel page**
image

**reference page**
image

### Stress-test
50 x ✅  https://github.com/metabase/metabase/actions/runs/9945501277

### CODE REVIEW

File: frontend/src/metabase/admin/datamodel/components/revisions/RevisionHistory.jsx [hunk 1]
```diff
@@ -20,7 +20,7 @@ class RevisionHistory extends Component {
   };
 
   render() {
-    const { object, objectType, revisions, table, user } = this.props;
```
Comment (nemanjaglumac) [inline frontend/src/metabase/admin/datamodel/components/revisions/RevisionHistory.jsx:23]: `objectType` was undefined.
But in any way, this component is now only used for segments in `master` so it's safe to remove this and to fetchSegments directly.

**Review by ranquild — APPROVED** [review]
