### PR TITLE
Port code for building i18n resources to Clojure build scripts

### LINKED ISSUE #13513: msgfmt seems to be failing on osx
running `bin/build` is failing.

simplest repro: `msgfmt --verbose --java2 -d resources -r metabase.Messages -l es locales/es.po`

```shell
~/p/c/metabase ❯❯❯ msgfmt --verbose --java2 -d resources -r metabase.Messages -l es locales/es.po
msgfmt: Java compiler not found, try installing gcj or set $JAVAC
msgfmt: compilation of Java class failed, please try to set $JAVAC
3531 translated messages.
```
possible red herring: https://lists.gnu.org/archive/html/bug-gnulib/2013-09/msg00042.html  (related to temp files and Windows)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### LINKED ISSUE #14396: Translate /admin/store
In the enterprise edition, `/admin/store` is mostly missing translations.

image

### LINKED ISSUE #14581: Translations marked as "fuzzy" in POEditor are not translated in UI
### Current Behavior
On a dashboard with an "all options" date filter and the Language set to Portuguese, the first option is not translated (Previous).  
Also makes the Embedded dashboard default value (on which Year was selected) to be half translated: "Previous Ano" or "Previous Mês".   

### Desired Behavior
The all options date filter should have the "Previous" date selection translated, like "Ano Anterior" or "Mês Anterior".   

### Prints

image

image

Will take some time to understand how translation works within the project, so that on the next time I can open a PR myself, sorry about that :(

### PR DESCRIPTION
**Pull request by camsaul**
Remove dependency on Java 8 and `gettext` for running `bin/build`. The resources are now created directly in Clojure.

This script replaces old bash/node.js scripts that relied on external calls to `msgfmt` to generate translation bundles for the frontend and backend with a Clojure script that integrates into our larger build script. Leverages the Fedora [`jgettext`](https://github.com/zanata/jgettext) library for PO file parsing

Key benefits:

* Build scripts no longer only work on Java 8.
* Fixes `msgfmt` issues on macOS  (#13513). `msgfmt` is no longer used.
* An order of magnitude faster: (**~2 seconds for the new script vs ~30 seconds for the old script** on my computer)
* Scripts integrate directly into rest of build/release script and can be debugged from the REPL, and now have tests (!)
* Backend resource artifact format changed from java resource bundle class files to plain edn files, which are easier to debug and simplifies the code in Metabase itself somewhat.  
* Optimized resource bundles for the backend now strip out translations not used in the backend itself. We were already doing this for the FE. So this should result in a slightly smaller JAR size.
*  It's now also possible to ship additional translations as a Metabase plugin by sticking a `metabase/xx.edn` or `metabase/xx-YY.edn`  file in a JAR and putting it in the `plugins/` directory.

I've also fixed #14581 as part of this PR. I was translating the old code and I just didn't port over the part that filtered out fuzzy translations. 

Fixes #13513
Fixes #14581
~AFAIK, this also fixes another bug where frontend EE strings weren't being added to the resources bundle, but I can't find any related GH issues.~
Fixes #14396

### CODE REVIEW

**Comment by camsaul** [comment]
I didn't port over the scripts that generate the `.pot` file(s) from the source code, or the script for uploading the `.pot` to POEditor, or the script for downloading the latest `.po` files from POEditor. Those are still a mix of bash/node.js and still rely on having `gettext` installed locally -- although I don't think `msgfmt` is used specifically.

This only ports the scripts that are used by `bin/build`; we can port the others later.

File: .gitignore [hunk 1]
```diff
@@ -49,6 +49,7 @@
 /resources/frontend_client/embed.html
 /resources/frontend_client/index.html
 /resources/frontend_client/public.html
+/resources/metabase/*.edn
```
Comment (dpsutton) [inline .gitignore:52]: this seems like a really big gitignore. should this be a bit more targeted?

File: bin/i18n/src/i18n/create_artifacts/backend.clj [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+            [metabuild-common.core :as u])
+  (:import [java.io FileOutputStream OutputStreamWriter]
+           java.nio.charset.StandardCharsets))
+
+(defn- backend-message? [{:keys [source-references]}]
+  (some (fn [path]
+          (some
+           (fn [dir]
+             (str/starts-with? path dir))
+           ["src" "backend" "enterprise/backend"]))
```
Comment (dpsutton) [inline bin/i18n/src/i18n/create_artifacts/backend.clj:14]: do we need shared here?

Comment (dpsutton) [reply bin/i18n/src/i18n/create_artifacts/backend.clj:14]: oh, in shared does that need to be in backend and frontend?

File: .gitignore (hunk 1 above)
Comment (dpsutton) [reply .gitignore:52]: i'm wondering if we add more edn config files, this would be the normal place they might go. Perhaps add a directory `resources/metabase/i18n` or translate or something that things can go into.

**Comment by dpsutton** [comment]
looks good with two considerations

File: .gitignore (hunk 1 above)
Comment (camsaul) [reply .gitignore:52]: yeah that's a good point. That was the old directory for the resource bundle class files so I didn't change it

File: bin/i18n/src/i18n/create_artifacts/backend.clj (hunk 2 above)
Comment (camsaul) [reply bin/i18n/src/i18n/create_artifacts/backend.clj:14]: Good point. Shared should probably go here. Altho I don't know how we're going to i18n things in shared right now, since `metabase.util.i18n` isn't going to work in ClojureScript. I guess we can make a cljs version that compiles to whatever we use on the FE (`ttag`?)

**Comment by flamber** [comment]
@camsaul I think you're looking for #14396

**Comment by paoliniluis** [comment]
I changed the language to spanish on my instance and it's really weird, have you seen this? 
image

**Comment by camsaul** [comment]
@paoliniluis that doesn't look right 😳

**Comment by camsaul** [comment]
@paoliniluis I fixed it. The format for the FE resources was wrong. You'll have to rebuild the translation resources and restart the server to see the changes (or reload the `metabase.server.routes.index` namespace if you're running the server from a REPL).

**Review by dpsutton — APPROVED** [review]
