### PR TITLE
Disable slow test to prevent flakiness

### LINKED ISSUE #29266: [FLAKE, BE] Mongo 4-2-ssl, `join-order-test` flake/timeout
Example of a failed run:
https://github.com/metabase/metabase/actions/runs/4435239667/jobs/7782162749?pr=29262#step:6:549

```
ERROR in metabase.query-processor-test.explicit-joins-test/join-order-test (default.clj:90)
Joins should be emitted in the same order as they were specified in MBQL (#15342) 
:mongo using sample-dataset dataset
 :inner-join before :left-join 
Native Query =
[{"$lookup"
  {:from "orders",
   :let {"let__id_323879" "$_id"},
   :pipeline [{"$match" {"$expr" {"$eq" ["$$let__id_323879" "$user_id"]}}}],
   :as "join_alias_Orders"}}
 {"$unwind" {:path "$join_alias_Orders", :preserveNullAndEmptyArrays false}}
 {"$lookup"
  {:from "products",
   :let {"let_product_id_323880" "$join_alias_Orders.product_id"},
   :pipeline [{"$match" {"$expr" {"$eq" ["$$let_product_id_323880" "$_id"]}}}],
   :as "join_alias_Products"}}
 {"$unwind" {:path "$join_alias_Products", :preserveNullAndEmptyArrays true}}
 {"$sort" {"_id" 1}}
 {"$project" {"_id" "$_id", "Orders___id" "$join_alias_Orders._id", "Products___id" "$join_alias_Products._id"}}
 {"$limit" 1}]


{:projections ("_id" "Orders___id" "Products___id"), :collection "people", :mbql? true}


expected: (=
           [[1 1 14]]
           (mt/formatted-rows [int int int] (qp/process-query query)))
  actual: 
clojure.lang.ExceptionInfo: Timed out after 60.0 s.
    status: :timed-out
      type: :timed-out
                               metabase.query-processor.context.default/default-timeoutf              default.clj:   90
                                               metabase.query-processor.context/timeoutf              context.clj:   85
metabase.query-processor.reducible/wire-up-context-channels!/fn/state-machine--auto--/fn            reducible.clj:   63
   metabase.query-processor.reducible/wire-up-context-channels!/fn/state-machine--auto--            reducible.clj:   57
                                       clojure.core.async.impl.runtime/run-state-machine              runtime.clj:   62
                               clojure.core.async.impl.runtime/run-state-machine-wrapped              runtime.clj:   66
                                                         clojure.core.async/ioc-alts!/fn                async.clj:  423
                                                        clojure.core.async/do-alts/fn/fn                async.clj:  290
                                   clojure.core.async.impl.channels.ManyToManyChannel/fn             channels.clj:  269
                                                                                     ...                               
                                       java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1128
                                      java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  628
                      clojure.core.async.impl.concurrent/counted-thread-factory/reify/fn           concurrent.clj:   29
                                                                                     ...                               
                                                                    java.lang.Thread.run              Thread.java:  829
```

### PR DESCRIPTION
**Pull request by metamben**
Fixes #29266.

### CODE REVIEW

File: test/metabase/query_processor_test/explicit_joins_test.clj [hunk 1]
```diff
@@ -884,8 +886,15 @@
     (mt/test-drivers (mt/normal-drivers-with-feature :left-join :inner-join)
       ;; For SQL drivers, this is only fixed for drivers using Honey SQL 2. So skip the test for ones still using Honey
       ;; SQL 1. Honey SQL 1 support is slated for removal in Metabase 0.49.0.
-      (when (or (not (isa? driver/hierarchy driver/*driver* :sql))
-                (= (sql.qp/honey-sql-version driver/*driver*) 2))
+      (when (and (or (not (isa? driver/hierarchy driver/*driver* :sql))
+                     (= (sql.qp/honey-sql-version driver/*driver*) 2))
+                 ;; Joins in MongoDB are extremely slow, especially on version 4.2
+                 ;; (version 5 is about two times faster but still very slow) and
+                 ;; this test is flaky on CI.
```
Comment (qnkhuat) [inline test/metabase/query_processor_test/explicit_joins_test.clj:893]: I'd include the #29266 in the comment

**Review by qnkhuat — APPROVED** [review]
