### PR TITLE
fix(sdk): Fix nextJS compatibility layer missing components

### LINKED ISSUE #52511: [SDK] Update Next.js compat layer's components list
We filed this issue before [our customer ran into it.](https://metaboat.slack.com/archives/C063Q3F1HPF/p1737657965959669)

`generate-nextjs-compat` is out of date as the InteractiveQuestion sub-components has been updated:

https://github.com/metabase/metabase/blob/1d5b5c6b33ba26fb032c0d7d32a44d3eb4c35f34/enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx#L95

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/52511

### Backport reason
We need to backport this as [our customer ran into this issue](https://metaboat.slack.com/archives/C063Q3F1HPF/p1737657965959669) on 52, now [they have downgraded to v51](https://metaboat.slack.com/archives/C063Q3F1HPF/p1737658288250829?thread_ts=1737657965.959669&cid=C063Q3F1HPF) as a temporary solution.

### Description

Fix missing nextJS compat because we manually set the components and subcomponents we want to add to `/nextjs` export. This solves the problem by automatically walking all the public React components and their subcomponents.

### How to verify
- Run `yarn embedding-sdk:generate-nextjs-compat` and check the content of `resources/embedding-sdk/dist/nextjs-no-ssr.js`
- Alternatively, you can also log `COMPONENTS_TO_EXPORT` in `enterprise/frontend/src/embedding-sdk/bin/generate-nextjs-compat.ts`, to see the result. And compare the result with our current SDK component public index file (`enterprise/frontend/src/embedding-sdk/components/public/index.ts`). Every top-level component should be included, and any component with sub-components should be included as well e.g. `InteractiveQuestion`.

#### After
Screenshot 2025-01-24 at 11 25 50 PM
Screenshot 2025-01-24 at 11 25 44 PM

#### Before
Screenshot 2025-01-24 at 11 20 46 PM

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/bin/get-public-components.ts [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+function isType(node: ExportSpecifier) {
+  return node.isTypeOnly() || node.getParent()?.getParent().isTypeOnly();
+}
+
+function isJsxElement(node?: Node) {
+  if (!node) {
+    return false;
+  }
+  const kind = node.getKind();
+  return kind >= SyntaxKind.JsxElement && kind <= SyntaxKind.JsxClosingFragment;
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/bin/get-public-components.ts:91]: Since these types are related and are next to each other, we can just compare it easier as a number.

https://github.com/dsherret/ts-morph/blob/6c092c8a760b38e9ed3bebdc75f6d6ad654762ea/packages/common/lib/typescript.d.ts#L3950-L3956

**Review by npretto — APPROVED** [review]
Generates the configuration as expected 🔥🔥🔥

File: enterprise/frontend/src/embedding-sdk/bin/get-public-components.ts (hunk 1 above)
Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/bin/get-public-components.ts:91]: This seems to be a file that they extended from typescript. I guess the part I'm referring to hasn't been modified by the author.

https://github.com/microsoft/TypeScript/blob/caf1aee269d1660b4d2a8b555c2d602c97cb28d7/src/compiler/types.ts#L360-L366

I checked that the order matches.

However, I like the explicitness of your idea. I'll do that instead.

Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/bin/get-public-components.ts]: @npretto fixed in 5c07db0817b957aee72afb058fc517834ee69473
