### PR TITLE
[serdes] introduce (partial) schema coercion for Dashboard

### LINKED ISSUE #54941: Serialization won't work with dashboards that have a time grouping filter
### Describe the bug

Sad but true 

Image

### To Reproduce

1) create a question like the count of orders per created at:month
2) add it to a dashboard and add a filter of time grouping
3) REMOVE SOME OF THE TIME GROUPING SELECTIONS
4) export
5) import
see the error

### Expected behavior

Should work fine, export and import

### Logs

```
2025-03-11 21:52:45,650 ERROR serialization.cmd :: Error during deserialization: Failed to load into database for Dashboard Q_VchiYwp8r0Ek95pFpb0 {:path [{:id "Q_VchiYwp8r0Ek95pFpb0", :model "Dashboard"}], :deps-chain #{}, :model "Dashboard", :table :report_dashboard, :error :metabase-enterprise.serialization.v2.load/load-failure}
  caused by: :parameters must be a sequence of maps with :id and :type keys {:parameters (#ordered/map ([:id "dac4fd17"] [:name "Time grouping"] [:sectionId "temporal-unit"] [:slug "time_grouping"] [:temporal_units ["minute" "hour" "day" "month" "year" "minute-of-hour" "hour-of-day" "day-of-week" "day-of-month" "day-of-year" "week-of-year" "month-of-year" "quarter-of-year"]] [:type "temporal-unit"])), :errors ({:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 0], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "minute"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 1], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "hour"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 2], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "day"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 3], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "month"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 4], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "year"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 5], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "minute-of-hour"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 6], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "hour-of-day"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 7], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "day-of-week"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 8], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "day-of-month"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 9], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "day-of-year"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 10], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "week-of-year"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 11], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "month-of-year"} {:path [0 0 :temporal_units 0 0], :in [0 :temporal_units 12], :schema [:enum {:error/message "Valid temporal bucketing unit", :decode/normalize #object[metabase.lib.schema.common$normalize_keyword 0xb24a153 "metabase.lib.schema.common$normalize_keyword@b24a153"]} :quarter :day :hour :week :second :default :day-of-week :hour-of-day :month :month-of-year :day-of-month :year :day-of-year :millisecond :year-of-era :second-of-minute :week-of-year :quarter-of-year :minute-of-hour :minute], :value "quarter-of-year"})}
```

### Information about your Metabase installation

```JSON
53.5
```

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by sansolovyov**
This adds coercion support for serialization and adds a very limited partial schema for a Dashboard, in hopes that this grows to be a full schema for our data models at some point.

fixes #54941

### CODE REVIEW

File: src/metabase/models/dashboard.clj [hunk 1]
```diff
@@ -410,7 +410,8 @@
                :made_public_by_id      (serdes/fk :model/User)
                :parameters             {:export serdes/export-parameters :import serdes/import-parameters}
                :tabs                   (serdes/nested :model/DashboardTab :dashboard_id opts)
-               :dashcards              (serdes/nested :model/DashboardCard :dashboard_id opts)}})
+               :dashcards              (serdes/nested :model/DashboardCard :dashboard_id opts)}
+   :schema {:parameters [:maybe [:sequential ms/Parameter]]}})
```
Comment (escherize) [inline src/metabase/models/dashboard.clj:414]: Might be difficult to understand that `:schema` acts on keys and isn't actually the "dashboard schema". Are you open to renaming the `:schema` key?

**Review by escherize — APPROVED** [review]
LGTM, but it needs docs, also might be worth renaming the `:schema` key.

**Comment by piranha** [comment]
> LGTM, but it needs docs, also might be worth renaming the `:schema` key.

Yeah of course, any ideas?

And yep, I need to augment docs, it's just it was eod and I wanted to get something out. :)

File: src/metabase/models/dashboard.clj (hunk 1 above)
Comment (piranha) [reply src/metabase/models/dashboard.clj]: Do you like the new one?

**Review by escherize — APPROVED** [review]

File: src/metabase/models/dashboard.clj (hunk 1 above)
Comment (escherize) [reply src/metabase/models/dashboard.clj]: amazing
