### PR TITLE
Fix saving of existing question

### LINKED ISSUE #4695: saving an existing question after editing broken
Seems to be happening on multiple branches and both @salsakran and I have been able to repro

1. create a SQL question
2.  run question
3.  edit query
4.  choose “Replace original question”
5.  press save
6.  nothing happens

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #4695

### CODE REVIEW

**Review by kdoh — APPROVED** [review]

File: frontend/src/metabase/hoc/Routeless.jsx [hunk 1]
```diff
@@ -41,13 +41,22 @@ export default (ComposedComponent) => class extends Component {
         // if the state previously was the saved one and is now not, then we probably
         // hit the back button, so close the wrapped component
         if (location.state === this._state && nextLocation.state !== this._state) {
-            this.props.onClose();
+            // close in a timeout in case it will be closed anyway and the URL changes.
```
Comment (attekei) [inline frontend/src/metabase/hoc/Routeless.jsx]: Didn't really understand based on this comment that _why_ this solves the described issue (or what the version without timeout was lacking)

Comment (attekei) [inline frontend/src/metabase/hoc/Routeless.jsx]: The fix itself works well.
