### PR TITLE
Closes VIZ-579: jarring layout change in object detail view

### LINKED ISSUE #55503: Jarring layout shift in when clicking into object detail view
### Describe the bug

[https://metaboat.slack.com/archives/C02H619CJ8K/p1742370056130679](https://metaboat.slack.com/archives/C02H619CJ8K/p1742370056130679)

When I'm using the table viz, I'll click into a row to see the object detail view to see more information. When I open the modal, I see the initial stuff (great) but then, sometimes a few seconds later, I get a small but noticeable layout shift as new information loads on the side.

There's also no indication that more information is loading or that there is any more information to view - I suggest something like a skeleton or something to make it less annoying

### To Reproduce

* Go to the table visualization
* Click into a row's primary key (ID on the sample database)
* See the object detail view here.
* (depending on load times) see the layout shift happen when the connection data appears on the right side

You might need to throttle your network if you see things immediately, usually locally. On some instances, this loading time can a few seconds as shown in the video

### Expected behavior

Show a skeleton loader on the right side so that the main data doesn't shift when the right sidebar loads.

### Logs

*No response*

### Information about your Metabase installation

```JSON
{}
```

### Severity

P3

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #55503
Closes [VIZ-579: Jarring layout shift in when clicking into object detail view](https://linear.app/metabase/issue/VIZ-579/jarring-layout-shift-in-when-clicking-into-object-detail-view)

### Description

The loading state wasn't handled very gracefully, and would generate some layout jumps.

### Demo

https://www.loom.com/share/3f5996cf698847a08c260d9c6d4a1189

### CODE REVIEW

File: frontend/src/metabase/components/IconBorder/IconBorder.jsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ import CS from "metabase/css/core/index.css";
 
 export default class IconBorder extends Component {
   static propTypes = {
-    borderWidth: PropTypes.oneOf([PropTypes.string, PropTypes.number]),
+    borderWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
```
Comment (lorem--ipsum) [inline frontend/src/metabase/components/IconBorder/IconBorder.jsx:20]: This is completely unrelated and cleans up the dev tools console a bit by not displaying an error.

**Review by kulyk — APPROVED** [review]
