### PR TITLE
feat: fix this query feature not using inline sql edits

### LINKED ISSUE #68992: “Have Metabot fix it” - fixed question is treated as new on Save
### Describe the bug

After using **Have Metabot fix it** on an existing native question, saving behaves as if the question was created from scratch. Metabase no longer offers the option to save changes and replace the original question.

### To Reproduce

1. Create a native SQL question. Save it.
2. Edit the question and introduce an error. Run it so it appears.
3. Click **Have Metabot fix it.**
4. The questions title becomes New question and when attempting to Save, there is no option to replace the original question.

### Expected behavior

The question should be treated as an edited version of the original and the usual Save as new / Replace original question choice should be offered on Save.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2026-01-27",
      "tag": "v1.58.4",
      "hash": "712da34"
    },
    "settings": {
      "report-timezone": "Australia/Melbourne"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by undrfined**
closes #68992
Closes [BOT-1046: "Fix this query" feature should use the SQL profile instead of Omnibot](https://linear.app/metabase/issue/BOT-1046/fix-this-query-feature-should-use-the-sql-profile-instead-of-omnibot)
Closes [BOT-923: “Have Metabot fix it” - fixed question is treated as new on Save](https://linear.app/metabase/issue/BOT-923/have-metabot-fix-it-fixed-question-is-treated-as-new-on-save)

### Description

Now it's using the inline sql editor.

### How to verify

1. New native query 
2. Create a query with errors
3. Click "Have Metabot fix it"

### Demo

https://github.com/user-attachments/assets/8d6c1645-c2f4-4921-879c-0be1e583dc12

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [x] ~~If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)~~

### CODE REVIEW

**Comment by undrfined** [comment]
https://github.com/user-attachments/assets/1a18e1ae-073a-4003-9c13-5338a664aa7b

@kdoh changed it so it doesn't open the prompt popup

**Comment by sloansparger** [comment]
can you check on requirements for if this needs to be supported in OSS? I think if we drop support there, i think we could achieve this functionality with only this diff. you might even be able to drop registering the context if we move the call in `use-metabot-sql-suggestion.tsx` out of that file and up higher in the tree.


CleanShot 2026-03-05 at 12 19 37@2x

**Comment by undrfined** [comment]
It is disabled in OSS. I think the proposed solution will cause two code_editor in the context which we don't really want? @sloansparger

**Comment by sloansparger** [comment]
sure, but i think we can solve this by moving the context registration higher up in the react tree. if the context was higher, i think this functionality is a 1 line change and don't require a bulk of what is in this PR.

File: frontend/src/metabase/metabot/hooks/use-metabot-sql-suggestion.tsx [hunk 1]
```diff
@@ -54,15 +55,16 @@ export function useMetabotSQLSuggestion({
           setSource(result.sql);
           onGenerated?.(result);
         } else {
-          setError(t`Something went wrong. Please try again.`);
+          throw new Error(t`Something went wrong. Please try again.`);
```
Comment (sloansparger) [inline frontend/src/metabase/metabot/hooks/use-metabot-sql-suggestion.tsx:58]: do we need to setError here too?

**Review by sloansparger — APPROVED** [review]
approved, with one question

File: frontend/src/metabase/metabot/hooks/use-metabot-sql-suggestion.tsx (hunk 1 above)
Comment (undrfined) [reply frontend/src/metabase/metabot/hooks/use-metabot-sql-suggestion.tsx:58]: It is caught below in `catch` block that calls setError

Comment (sloansparger) [reply frontend/src/metabase/metabot/hooks/use-metabot-sql-suggestion.tsx:58]: duh. my bad. ship it then.
