### PR TITLE
Fix sidebar loading causes UI jump

### LINKED ISSUE #14603: Collection tree loader causes UI jump
**Describe the bug**
When going into collections for the first time during a sessions, the loading spinner is shown above the collection elements instead of on the side, which causes the UI to jump. Depending on how slow the load is, or how fast the user is, this might cause the user to click a different element.

**To Reproduce**
1. Go to root collection for the first time during a session, and depending on how many collections are available, it will show the loading-spinner on top of collection elements
image
2. ... until the collection tree is loaded in the left side
image

**Expected behavior**
Loading spinner should only take up space for the container it's initializing.

**Information about your Metabase Installation:**
Tested 0.38.0-rc4

### PR DESCRIPTION
**Pull request by kulyk**
Closes #14603 

When going into collections for the first time during a sessions, the loading spinner is shown above the collection elements instead of on the side, which causes the UI to jump. Depending on how slow the load is, or how fast the user is, this might cause the user to click a different element.

### To Verify

1. Log out (the issue reproduces for the first time in a session)
2. (Optional) Open developer tools, open the Network tab and turn on some throttling, so the loading state lasts longer

3. Visit `/collection/root`

### Demo

**Before**

before

**After**

after

### CODE REVIEW

File: frontend/src/metabase/collections/containers/CollectionSidebar.jsx [hunk 1]
```diff
@@ -126,6 +128,22 @@ class CollectionSidebar extends React.Component {
...
+  render() {
+    const { loaded } = this.props;
+    return (
+      <Sidebar w={340} pt={3} data-testid="sidebar">
+        {loaded ? (
+          this.renderContent()
+        ) : (
+          <div className="text-brand text-centered">
+            <LoadingSpinner />
+            <h2 className="text-normal text-light mt1">{t`Loading ...`}</h2>
```
Comment (alxnddr) [inline frontend/src/metabase/collections/containers/CollectionSidebar.jsx:144]: @kulyk we already have a translated string with an ellipsis so I would suggest using it instead of a new one with 3 dots: 
`Loading…`

**Review by alxnddr — APPROVED** [review]
@kulyk looks good! I left one tiny request, please take a look

File: frontend/src/metabase/collections/containers/CollectionSidebar.jsx (hunk 1 above)
Comment (kulyk) [reply frontend/src/metabase/collections/containers/CollectionSidebar.jsx:144]: Good call! Honestly I just copy pasted it from the [`LoadingAndErrorWrapper`](https://github.com/metabase/metabase/blob/785060d44a1c4f1e2c547e432e8858969c9b9c05/frontend/src/metabase/components/LoadingAndErrorWrapper.jsx#L35). Makes sense to replace it there as weel

File: frontend/src/metabase/collections/containers/CollectionSidebar.jsx [hunk 2]
```diff
@@ -41,16 +42,17 @@ const Sidebar = styled(Box)`
...
-  componentDidMount() {
-    // an array to store the ancestors
+  componentDidUpdate(prevProps) {
     const { collectionId, collections, loading } = this.props;
-    if (!loading) {
+    const loaded = prevProps.loading && !loading;
+    if (loaded) {
       const ancestors = getParentPath(collections, Number(collectionId)) || [];
       this.setState({ openCollections: ancestors });
     }
```
Comment (kulyk) [inline frontend/src/metabase/collections/containers/CollectionSidebar.jsx:58]: Replacing `didMount` with `didUpdate` ended up in one of the tests failing
Going to look at it tomorrow, until then putting the PR into draft

File: frontend/src/metabase/collections/containers/CollectionSidebar.jsx (hunk 1 above)
Comment (flamber) [reply frontend/src/metabase/collections/containers/CollectionSidebar.jsx:144]: Avoid making translation changes in dot-releases (eg 39.x), since we don't update translations until major releases.

Comment (kulyk) [reply frontend/src/metabase/collections/containers/CollectionSidebar.jsx:144]: @flamber I guess we're safe here? If we're sure `Loading…` is covered with translations

Comment (flamber) [reply frontend/src/metabase/collections/containers/CollectionSidebar.jsx:144]: You'll have to ask someone who understand how translations are hooked into the frontend.
I can see there's three styles for this: `` t`Loading ...` `` and `` t`Loading...` `` and then a three-dot `` t`Loading…` ``

File: frontend/src/metabase/collections/containers/CollectionSidebar.jsx (hunk 2 above)
Comment (kulyk) [reply frontend/src/metabase/collections/containers/CollectionSidebar.jsx:58]: Funny thing, I guess it just made it better. So `didMount` made sure the correct tree "branch" is expanded when we go to a specific nested collection.

The reason `didMount` is replaced `didUpdate` is that entity loader's `loadingAndErrorWrapper` is now disabled for `CollectionSidebar`. In that way, we can display the loader that won't cause the UI jump. But having `loadingAndErrorWrapper` enabled guaranteed that the sidebar is rendered only after its data is loaded, so the `loading` prop was always `false`. Now when the sidebar is responsible for loading state handling, it mounts in the `loading` state, and the method body won't be executed.

So now ancestors are recalculated each time sidebar's data changes. It worked well with this logic in the `didMount`, but the failing test catched the edge case

So imagine I have a collection structure like this:

initial-state

I want to move "Second collection" to the "New collection". So I select the "Second collection", click edit, and change its parent collection. On the `release-x.39.x` I sometimes appear in the next state after I move the collection:

release-after-move

But on this branch, after the same steps I appear in the next state:

fix-after-move

So I guess it's actually better

File: frontend/src/metabase/collections/containers/CollectionSidebar.jsx [hunk 3]
```diff
@@ -41,16 +42,17 @@ const Sidebar = styled(Box)`
     we should eventually refactor code elsewhere in the app to use this by default instead of determining the relationships clientside, but this works in the interim
   */
   query: () => ({ tree: true }),
+  loadingAndErrorWrapper: false,
```
Comment (kdoh) [inline frontend/src/metabase/collections/containers/CollectionSidebar.jsx:45]: I know in our style guide we want to try and discourage too many unnecessary comments but this feels like a place where having a note about why we're setting this to false would be likely be useful in the future.

File: frontend/src/metabase/collections/containers/CollectionSidebar.jsx [hunk 4]
```diff
@@ -126,6 +128,23 @@ class CollectionSidebar extends React.Component {
...
+
+  render() {
+    const { allFetched } = this.props;
+
+    return (
+      <Sidebar w={340} pt={3} data-testid="sidebar">
+        {allFetched ? (
+          this.renderContent()
+        ) : (
+          <div className="text-brand text-centered">
```
Comment (kdoh) [inline frontend/src/metabase/collections/containers/CollectionSidebar.jsx:143]: Not a huge deal but it feels like it'd be nice to just pull out the existing loader UI elements into a shareable component and use it here.

**Review by kdoh — APPROVED** [review]

File: frontend/test/metabase/scenarios/collections/collections.cy.spec.js [hunk 5]
```diff
@@ -388,18 +388,11 @@ describe("scenarios > collection_defaults", () => {
...
-
-      // TODO: This was an original test that made sure the collection is indeed open immediately.
-      //       That part is going to be addressed in a separate issue.
-      // cy.findByText(NEW_COLLECTION)
-      //   .closest("a")
-      //   .within(() => {
-      //     cy.icon("chevrondown");
-      //     cy.findByText("First collection");
-      //   });
+      getSidebarCollectionChildren(cy.findByText(NEW_COLLECTION)).within(() => {
```
[the remark this answers is not in the document]
Comment (kulyk) [reply frontend/test/metabase/scenarios/collections/collections.cy.spec.js:391]: Yeah, I agree; it doesn't actually look like a Cypress test. Still, I think the helper might be useful in other collection page tests (e.g., some `permissions` tests query sidebar items).

The raw selector is pretty hard to read, and it isn't clear what it actually does (getting closest anchor element, then its parent, then its siblings). If we want to remove the function, I think we should at least leave a comment describing what's actually going on. Or we can slightly update the syntax, so it matches the Cypress style:

```js
getSidebarCollectionChildrenFor(NEW_COLLECTION)

function getSidebarCollectionChildrenFor(item) {
    return cy.findByText(item)
               .closest("a")
               .parent()
               .siblings();
}
```

[the remark this answers is not in the document]
Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/collections/collections.cy.spec.js:391]: Where do parent and siblings come from all of a sudden?

[the remark this answers is not in the document]
Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/collections/collections.cy.spec.js:391]: @kulyk I like the proposal for the updated syntax. Wanted to suggest something like that myself, but there are still 2 things here that can be improved.

1. If the sidebar collection is already open, this function will fail because `cy.findByText(item)` will find 2 strings - one in the sidebar, and one in the title. We can use new testid to prevent this:
```javascript
function getSidebarCollectionChildren(item) {
  return cy
    .findByTestId("sidebar")
    .findByText(item)
    .closest("a")
    .parent()
    .siblings();
}
```

2. Using `.siblings()` moves the "containing area" to the children only so we can't assert anything on the target collection ("NEW_COLLECTION") in this case. using `.parent()` once again moves us to the top level container for this scope - we can see both the target collection and its children at once.
```javascript
function getSidebarCollectionChildren(item) {
  return cy
    .findByTestId("sidebar")
    .findByText(item)
    .closest("a")
    .parent()
    .parent();
}
```

By doing this, we can finally make assertion like this one:
```javascript
getSidebarCollectionChildren(NEW_COLLECTION).within(() => {
  cy.icon("chevrondown").should("have.length", 2); // both target collection and "First collection" are open
  cy.findByText("First collection");
  cy.findByText("Second collection");
});
```

And yes, I agree we should have some comment explaining what's going on here. Whenever we need to use some obscure and complicated selector that requires a comment to even understand it, that is a good pointer that HTML structure can be improved. Following the guidelines of React Testing Library that encourages good accessibility practices, we can _at least_ use `aria-expanded` attribute and that would've already made our life easier for testing.
Not saying you should implement this in this commit. Just analyzing the problem and thinking out loud.

Another thing we could've solved with pure CSS (had we used BEM, for example) is some class that clearly denotes top level group/container for collections that contain children.

[the remark this answers is not in the document]
Comment (kulyk) [reply frontend/test/metabase/scenarios/collections/collections.cy.spec.js]: Awesome, thanks for your suggestions, the selector looks much better now. I also added `tree` and `treeitem` roles to the sidebar and its children, and an `aria-expanded` prop to sidebar children. So we can now use the `findByRole` selector when testing the sidebar

File: frontend/src/metabase/collections/containers/CollectionSidebar.jsx (hunk 4 above)
Comment (kulyk) [reply frontend/src/metabase/collections/containers/CollectionSidebar.jsx:148]: I've checked a few places where loaders are used, and they seem pretty different. Some components just render the `LoadingSpinner` without any wrappers and messages, and mostly all of them use different CSS classes for styling. I think we can get it wrong if we try to pull it out right now 🤔

**Review by nemanjaglumac — APPROVED** [review]
Looking good :)
