### PR TITLE
pulling out column title logic and sharing with settings

### LINKED ISSUE #28935: Updated Column names are not present in Chart Settings
When in a table visualization, if you update the column name, that new name is not reflected in the chart settings UI

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Go to New -> Question -> Orders -> Visualize
2. Open chart settings and click the `...` next to Subtotal
3. Update the name and close the formatting popover

**Expected behavior**
I would expect the column title to be update in Chart Settings, as it is in the Table Viz

**Information about your Metabase Installation:**
V0.45.0

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/28935

### Description
Updated the `ChartSettingOrderedColums` component to accept a getColumnName function. This function uses the same logic that the Table Viz does to render it's column titles. It feels a little weird pulling this logic out into a shared function since it means we do some redundant things, but it keeps the changes minimal and can be adjusted when we revisit table columns. Open to suggestions on how to improve this though!

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> Orders -> Visualize
2. Open columns settings and change the name of a column
3. The new column name should be displayed in chart settings

### Demo
Before updating name:
image

After updating name: 
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/columns.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
+import { t } from "ttag";
+
+import Table from "metabase/visualizations/visualizations/Table";
```
Comment (npfitz) [inline frontend/src/metabase/visualizations/lib/columns.ts:3]: Was a bit worried about a cyclic dependency here, but it seems to work fine

File: frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedColumns.jsx [hunk 2]
```diff
@@ -57,12 +56,10 @@ export default class ChartSettingOrderedColumns extends Component {
...
 
-  getColumnName = columnSetting =>
-    getFriendlyName(
-      findColumnForColumnSetting(this.props.columns, columnSetting) || {
-        display_name: "[Unknown]",
-      },
-    );
+  getColumnName = columnSetting => {
+    const { getColumnName } = this.props;
+    return getColumnName(columnSetting) || "[Unknown]";
```
Comment (npfitz) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedColumns.jsx:61]: This should never actually happen since if we have a column setting that can't be found in `data.cols`, the settingDef's `isValid()` check should return false and we should recompute a default, which is based off data.cols. However, I figured I should keep a backup value in there anyways.

File: frontend/test/metabase/visualizations/visualizations/Table.unit.spec.js [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+          visualization_settings: {},
+        },
+        metadata,
+      ),
+    );
+
+    const onChange = update => {
+      setQuestion(q => {
+        const newQuestion = q.updateSettings(update);
+        return new Question(thaw(newQuestion.card()), metadata);
```
Comment (npfitz) [inline frontend/test/metabase/visualizations/visualizations/Table.unit.spec.js:36]: Need to thaw the card since we freeze it when calling updateSettings (we call `icepick.assoc` and write `visualization_settings`). This causes the ChartSettings component to start throwing errors when it re-renders.

File: frontend/src/metabase/visualizations/lib/columns.ts (hunk 1 above)
Comment (EmmadUsmani) [reply frontend/src/metabase/visualizations/lib/columns.ts:3]: We could also define `getTitleForColumn` in `Table.jsx` and export it from there, that would avoid the cyclic dependency.

File: frontend/test/metabase/visualizations/visualizations/Table.unit.spec.js [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+    );
+  };
+
+  renderWithProviders(<Container />);
+};
+
+describe("table settings", () => {
+  it("should show you related columns in structured queries", async () => {
+    setup();
+    expect(await screen.findByText("More columns")).toBeInTheDocument();
```
Comment (EmmadUsmani) [inline frontend/test/metabase/visualizations/visualizations/Table.unit.spec.js:65]: Nit: I don't think you need to use `await` for the testing-library methods like `screen` and `within`, they don't return promises

**Review by EmmadUsmani — COMMENTED** [review]
Looks good! I will let someone with more context give approve

File: frontend/test/metabase/visualizations/visualizations/Table.unit.spec.js (hunk 4 above)
Comment (npfitz) [reply frontend/test/metabase/visualizations/visualizations/Table.unit.spec.js:65]: I think the `findBy` functions return promises, as they will re-query after a certain interval to give something time to show up. `getBy` and `queryBy` are synchronous, so they wouldn't require the awaits.

File: frontend/src/metabase/visualizations/lib/columns.ts (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/visualizations/lib/columns.ts:3]: For sure, and that may be the better way to go here. We tend to tuck this kinda stuff into lib or util files outside of the components, but all the static class props make this a little awkward 🥲

**Review by alxnddr — COMMENTED** [review]
It would be nice to fix it for pivot tables as well:
Screen Shot 2023-03-06 at 6 46 30 PM

**Comment by npfitz** [comment]
Good catch! I hadn't thought to check Pivot Tables. I'll see what I can do

File: frontend/src/metabase/visualizations/lib/columns.ts (hunk 1 above)
Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/columns.ts:3]: Yep, let's extract this function to avoid having cyclic dependencies

**Review by alxnddr — APPROVED** [review]
