### PR TITLE
[QP] Update breakouts in `:order-by` when setting time granularity

### LINKED ISSUE #49263: Explicitly sorting by a temporal column will break the time granularity parameter on a dashboard
### Describe the bug

If you sort by a time field, it will end up breaking the time granularity filter due to a QP error

### To Reproduce

1) create a question as simple as 
Image

see the temporal field being added to the sort stage

2) add the card to a dashboard and add a time granularity parameter
3) change the time granularity and see the BE breaking

### Expected behavior

should work

### Logs

```
2024-10-29 00:44:54,010 ERROR middleware.catch-exceptions :: Error processing query: ERROR: column "orders.created_at" must appear in the GROUP BY clause or be used in an aggregate function
  Position: 332
{:database_id 2,
 :started_at #t "2024-10-29T00:44:53.982942Z[Etc/UTC]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: ERROR: column \"orders.created_at\" must appear in the GROUP BY clause or be used in an aggregate function\n  Position: 332",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__86031$fn__86032.invoke(execute.clj:717)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__86031.invoke(execute.clj:714)"
    "driver.sql_jdbc.execute$fn__85835$fn__85836.invoke(execute.clj:398)"
    "driver.sql_jdbc.execute$do_with_resolved_connection85805__85806.invokeStatic(execute.clj:338)"
    "driver.sql_jdbc.execute$do_with_resolved_connection85805__85806.invoke(execute.clj:321)"
    "driver.sql_jdbc.execute$fn__85835.invokeStatic(execute.clj:392)"
    "driver.sql_jdbc.execute$fn__85835.invoke(execute.clj:390)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
    "driver.sql_jdbc$fn__119504.invokeStatic(sql_jdbc.clj:79)"
    "driver.sql_jdbc$fn__119504.invoke(sql_jdbc.clj:77)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
    "query_processor.execute$run.invokeStatic(execute.clj:62)"
    "query_processor.execute$run.invoke(execute.clj:56)"
    "query_processor.middleware.update_used_cards$update_used_cards_BANG_76882__76883$fn__76884.invoke(update_used_cards.clj:60)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__76899.invoke(execute.clj:25)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__76905.invoke(execute.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76855.invoke(cache.clj:241)"
    "query_processor.middleware.permissions$check_query_permissions$fn__73895.invoke(permissions.clj:147)"
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__113603$check_download_permissions__113604$fn__113605.invoke(permissions.clj:90)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__74603.invoke(enterprise.clj:51)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$fn__115542$maybe_apply_column_level_perms_check__115543$fn__115544.invoke(column_level_perms_check.clj:38)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__74613.invoke(enterprise.clj:64)"
    "query_processor.execute$execute76932__76933$fn__76934.invoke(execute.clj:94)"
    "query_processor.setup$do_with_qp_setup75128__75129.invokeStatic(setup.clj:225)"
    "query_processor.setup$do_with_qp_setup75128__75129.invoke(setup.clj:216)"
    "query_processor.execute$execute76932__76933.invokeStatic(execute.clj:93)"
    "query_processor.execute$execute76932__76933.invoke(execute.clj:89)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__86509$handle_audit_app_internal_queries__86510$fn__86511.invoke(handle_audit_queries.clj:145)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__74641.invoke(enterprise.clj:103)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware77788__77789$fn__77790.invoke(process_userland_query.clj:204)"
    "query_processor.middleware.catch_exceptions$catch_exceptions77853__77854$fn__77855.invoke(catch_exceptions.clj:132)"
    "query_processor$process_query77894__77895$fn__77896.invoke(query_processor.clj:80)"
    "query_processor.setup$do_with_canceled_chan75123__75124$fn__75125.invoke(setup.clj:187)"
    "query_processor.setup$do_with_database_local_settings75116__75117$fn__75118.invoke(setup.clj:181)"
    "query_processor.setup$do_with_driver75109__75110$fn__75111$fn__75112.invoke(setup.clj:166)"
    "driver$do_with_driver.invokeStatic(driver.clj:106)"
    "driver$do_with_driver.invoke(driver.clj:101)"
    "query_processor.setup$do_with_driver75109__75110$fn__75111.invoke(setup.clj:165)"
    "query_processor.setup$do_with_metadata_provider75100__75101$fn__75102$fn__75105.invoke(setup.clj:151)"
    "query_processor.store$do_with_metadata_provider58718__58719.invokeStatic(store.clj:170)"
    "query_processor.store$do_with_metadata_provider58718__58719.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider58718__58719.invokeStatic(store.clj:159)"
    "query_processor.store$do_with_metadata_provider58718__58719.invoke(store.clj:150)"
    "query_processor.setup$do_with_metadata_provider75100__75101$fn__75102.invoke(setup.clj:150)"
    "query_processor.setup$do_with_resolved_database75090__75091$fn__75092.invoke(setup.clj:128)"
    "query_processor.setup$do_with_qp_setup75128__75129.invokeStatic(setup.clj:232)"
    "query_processor.setup$do_with_qp_setup75128__75129.invoke(setup.clj:216)"
    "query_processor$process_query77894__77895.invokeStatic(query_processor.clj:78)"
    "query_processor$process_query77894__77895.invoke(query_processor.clj:71)"
    "query_processor.card$process_query_for_card_default_qp88337__88338.invokeStatic(card.clj:186)"
    "query_processor.card$process_query_for_card_default_qp88337__88338.invoke(card.clj:182)"
    "query_processor.card$process_query_for_card_default_run_fn$fn__88340$fn__88341.invoke(card.clj:193)"
    "query_processor.streaming$_streaming_response$fn__61503$fn__61504$fn__61505.invoke(streaming.clj:176)"
    "query_processor.streaming$_streaming_response$fn__61503$fn__61504.invoke(streaming.clj:174)"
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
    "query_processor.streaming$_streaming_response$fn__61503.invoke(streaming.clj:171)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
    "async.streaming_response$do_f_async$task__53224.invoke(streaming_response.clj:97)"],
   :error_type :invalid-query,
   :ex-data
   {:driver :postgres,
    :sql
    ["-- Metabase:: userID: 1 queryType: MBQL queryHash: 0ba59ce7f41a36bd3c549c313b2d43ba4ce8ed6ecf801dc48965a117e214aef9"
     "SELECT"
     "  CAST(\"public\".\"orders\".\"created_at\" AS date) AS \"created_at\","
     "  SUM(\"public\".\"orders\".\"total\") AS \"sum\""
     "FROM"
     "  \"public\".\"orders\""
     "GROUP BY"
     "  CAST(\"public\".\"orders\".\"created_at\" AS date)"
     "ORDER BY"
     "  DATE_TRUNC('month', \"public\".\"orders\".\"created_at\") DESC,"
     "  CAST(\"public\".\"orders\".\"created_at\" AS date) ASC"],
    :params nil,
    :type :invalid-query}}],
 :action_id nil,
 :state "42803",
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :userland-query? true},
  :cache-strategy nil,
  :viz-settings {:table.cell_column "sum"},
  :database 2,
  :query
  {:source-table 24,
   :aggregation [[:sum [:field 285 {:base-type :type/Float}]]],
   :breakout [[:field 287 {:base-type :type/DateTime, :temporal-unit :month}]],
   :order-by [[:desc [:field 287 {:base-type :type/DateTime, :temporal-unit :month}]]]},
  :parameters
  [{:type :temporal-unit,
    :value "day",
    :id "3d48aedf",
    :target [:dimension [:field 287 {:base-type :type/DateTime, :temporal-unit :month}]]}]},
 :native
 {:query
  "SELECT CAST(\"public\".\"orders\".\"created_at\" AS date) AS \"created_at\", SUM(\"public\".\"orders\".\"total\") AS \"sum\" FROM \"public\".\"orders\" GROUP BY CAST(\"public\".\"orders\".\"created_at\" AS date) ORDER BY DATE_TRUNC('month', \"public\".\"orders\".\"created_at\") DESC, CAST(\"public\".\"orders\".\"created_at\" AS date) ASC",
  :params nil},
 :status :failed,
 :class org.postgresql.util.PSQLException,
 :stacktrace
 ["org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)"
  "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)"
  "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)"
  "org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)"
  "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__85961.invokeStatic(execute.clj:570)"
  "driver.sql_jdbc.execute$fn__85961.invoke(execute.clj:568)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:578)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:575)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__86031$fn__86032.invoke(execute.clj:715)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__86031.invoke(execute.clj:714)"
  "driver.sql_jdbc.execute$fn__85835$fn__85836.invoke(execute.clj:398)"
  "driver.sql_jdbc.execute$do_with_resolved_connection85805__85806.invokeStatic(execute.clj:338)"
  "driver.sql_jdbc.execute$do_with_resolved_connection85805__85806.invoke(execute.clj:321)"
  "driver.sql_jdbc.execute$fn__85835.invokeStatic(execute.clj:392)"
  "driver.sql_jdbc.execute$fn__85835.invoke(execute.clj:390)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)"
  "driver.sql_jdbc$fn__119504.invokeStatic(sql_jdbc.clj:79)"
  "driver.sql_jdbc$fn__119504.invoke(sql_jdbc.clj:77)"
  "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
  "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
  "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
  "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
  "query_processor.execute$run.invokeStatic(execute.clj:62)"
  "query_processor.execute$run.invoke(execute.clj:56)"
  "query_processor.middleware.update_used_cards$update_used_cards_BANG_76882__76883$fn__76884.invoke(update_used_cards.clj:60)"
  "query_processor.execute$add_native_form_to_result_metadata$fn__76899.invoke(execute.clj:25)"
  "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__76905.invoke(execute.clj:36)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76855.invoke(cache.clj:241)"
  "query_processor.middleware.permissions$check_query_permissions$fn__73895.invoke(permissions.clj:147)"
  "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__113603$check_download_permissions__113604$fn__113605.invoke(permissions.clj:90)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__74603.invoke(enterprise.clj:51)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$fn__115542$maybe_apply_column_level_perms_check__115543$fn__115544.invoke(column_level_perms_check.clj:38)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__74613.invoke(enterprise.clj:64)"
  "query_processor.execute$execute76932__76933$fn__76934.invoke(execute.clj:94)"
  "query_processor.setup$do_with_qp_setup75128__75129.invokeStatic(setup.clj:225)"
  "query_processor.setup$do_with_qp_setup75128__75129.invoke(setup.clj:216)"
  "query_processor.execute$execute76932__76933.invokeStatic(execute.clj:93)"
  "query_processor.execute$execute76932__76933.invoke(execute.clj:89)"
  "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
  "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__86509$handle_audit_app_internal_queries__86510$fn__86511.invoke(handle_audit_queries.clj:145)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__74641.invoke(enterprise.clj:103)"
  "query_processor.middleware.process_userland_query$process_userland_query_middleware77788__77789$fn__77790.invoke(process_userland_query.clj:204)"
  "query_processor.middleware.catch_exceptions$catch_exceptions77853__77854$fn__77855.invoke(catch_exceptions.clj:132)"
  "query_processor$process_query77894__77895$fn__77896.invoke(query_processor.clj:80)"
  "query_processor.setup$do_with_canceled_chan75123__75124$fn__75125.invoke(setup.clj:187)"
  "query_processor.setup$do_with_database_local_settings75116__75117$fn__75118.invoke(setup.clj:181)"
  "query_processor.setup$do_with_driver75109__75110$fn__75111$fn__75112.invoke(setup.clj:166)"
  "driver$do_with_driver.invokeStatic(driver.clj:106)"
  "driver$do_with_driver.invoke(driver.clj:101)"
  "query_processor.setup$do_with_driver75109__75110$fn__75111.invoke(setup.clj:165)"
  "query_processor.setup$do_with_metadata_provider75100__75101$fn__75102$fn__75105.invoke(setup.clj:151)"
  "query_processor.store$do_with_metadata_provider58718__58719.invokeStatic(store.clj:170)"
  "query_processor.store$do_with_metadata_provider58718__58719.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider58718__58719.invokeStatic(store.clj:159)"
  "query_processor.store$do_with_metadata_provider58718__58719.invoke(store.clj:150)"
  "query_processor.setup$do_with_metadata_provider75100__75101$fn__75102.invoke(setup.clj:150)"
  "query_processor.setup$do_with_resolved_database75090__75091$fn__75092.invoke(setup.clj:128)"
  "query_processor.setup$do_with_qp_setup75128__75129.invokeStatic(setup.clj:232)"
  "query_processor.setup$do_with_qp_setup75128__75129.invoke(setup.clj:216)"
  "query_processor$process_query77894__77895.invokeStatic(query_processor.clj:78)"
  "query_processor$process_query77894__77895.invoke(query_processor.clj:71)"
  "query_processor.card$process_query_for_card_default_qp88337__88338.invokeStatic(card.clj:186)"
  "query_processor.card$process_query_for_card_default_qp88337__88338.invoke(card.clj:182)"
  "query_processor.card$process_query_for_card_default_run_fn$fn__88340$fn__88341.invoke(card.clj:193)"
  "query_processor.streaming$_streaming_response$fn__61503$fn__61504$fn__61505.invoke(streaming.clj:176)"
  "query_processor.streaming$_streaming_response$fn__61503$fn__61504.invoke(streaming.clj:174)"
  "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
  "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
  "query_processor.streaming$_streaming_response$fn__61503.invoke(streaming.clj:171)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
  "async.streaming_response$do_f_async$task__53224.invoke(streaming_response.clj:97)"],
 :card_id 113,
 :context :dashboard,
 :error
 "ERROR: column \"orders.created_at\" must appear in the GROUP BY clause or be used in an aggregate function\n  Position: 332",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :middleware {:js-int-to-string? true, :ignore-cached-results? false, :userland-query? true},
  :user-parameters
  [{:value "day",
    :type :temporal-unit,
    :id "3d48aedf",
    :target [:dimension [:field 287 {:base-type :type/DateTime, :temporal-unit :month}]]}],
  :viz-settings {:table.cell_column "sum"},
  :info
  {:executed-by 1,
   :context :dashboard,
   :card-id 113,
   :card-name "orders, Sum of total, Grouped by created_at: Month, Sorted by created_at: Month descending",
   :dashboard-id 12,
   :visualization-settings {:table.cell_column "sum"}},
  :database 2,
  :type :query,
  :query
  {:source-table 24,
   :aggregation [[:aggregation-options [:sum [:field 285 {:base-type :type/Float}]] {:name "sum"}]],
   :breakout [[:field 287 {:base-type :type/DateTime, :temporal-unit :day}]],
   :order-by
   [[:desc [:field 287 {:base-type :type/DateTime, :temporal-unit :month}]]
    [:asc [:field 287 {:base-type :type/DateTime, :temporal-unit :day}]]]}},
 :data {:rows [], :cols []}}

2024-10-29 00:44:54,218 DEBUG middleware.log :: POST /api/dashboard/12/dashcard/97/card/113/query 202 [ASYNC: completed] 251.2 ms (16 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (2 idle, 0 queued) (144 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked) {:metabase-user-id 1}
```

### Information about your Metabase installation

v51.1

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by bshepherdson**
Closes #49263.

### Description

Previously the `:order-by` clauses were not updated, which caused invalid SQL to be
generated, since the ORDER BY (time unit not updated) and GROUP BY (time unit updated)
did not line up.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> MBQL -> Sample Database -> Orders
2. COUNT aggregation
3. Break out by Created At by both month and day
4. Explicitly order by Created At: Day, Descending.
5. Add this card to a dashboard
6. Add a time granularity parameter to the dashboard and link it to the Created At: Day column
7. Try to set the time granularity using the dashboard filter.

Originally this caused the query to fail to run because of the SQL error. Now it works correctly.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#49403** <a href="https://app.graphite.dev/github/pr/metabase/metabase/49403?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bshepherdson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: test/metabase/query_processor/middleware/parameters/mbql_test.clj [hunk 1]
```diff
@@ -432,3 +432,23 @@
...
+                               :aggregation  [[:count]]
+                               :breakout     [(by-unit :day)
+                                              (by-unit :month)]
+                               :order-by     [[:asc (by-unit :month)]]}
+                    :parameters [{:type   :temporal-unit
+                                  :target [:dimension (by-unit :month)]
+                                  :value  :week}]}]
+      (is (= ["2016-04-30T00:00:00Z" "2016-04-24T00:00:00Z" 1]
+             (first (mt/rows (mt/process-query
+                               query))))))))
```
Comment (appleby) [inline test/metabase/query_processor/middleware/parameters/mbql_test.clj:454]: indentation?

**Review by appleby — APPROVED** [review]
