### PR TITLE
Fix Dashboard Subscription email validation (second pass)

### LINKED ISSUE #17977: On master: new restricted domain list doesn't respect 'Send Now' button
**Describe the bug**
With the new restricted domains list, I can still send dashboard subscription emails using Send Now to an email address whose domain is not on the list.

**To Reproduce**
1. Add a user with an email outside of the domain you want to filter down to - e.g. a persona email address (through Admin)
2. Go to Admin -> General
2. Set a domain in the "Approved Domains for Notifications" box (e.g. metabase.com)
3. Go to a dashboard, click share, and click add an email notification and 'Send Now'.
4. See email sent to account where it shouldn't.

**Expected behavior**
It shouldn't sent, and should probably show an error saying 'Domain not allowed, contact administrator' or something to that effect.

This happens on the current master.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #17977

### CODE REVIEW

File: test/metabase/models/pulse_channel_test.clj [hunk 1]
```diff
@@ -415,3 +416,26 @@
...
+    (testing "should check that User `:id` and `:email`s match for User `:recipients`"
+      (let [input {:recipients [{:email "rasta@metabase.com"
+                                 :id    (mt/user->id :rasta)}]}]
+        (is (= input
+               (pc/validate-email-domains input))))
+      (testing "Throw Exception if User does not exist"
+        ;; should validate even if `:email` isn't specified
+        (doseq [input [{:id Integer/MAX_VALUE}
+                       {:email "rasta@example.com"
+                        :id    Integer/MAX_VALUE}]]
```
Comment (jeff303) [inline test/metabase/models/pulse_channel_test.clj:431]: Nit: seems like the map values aren't horizontally aligned, but there are also multiple spaces after `:id` here.  I would go with one or the other.

**Review by jeff303 — APPROVED** [review]
LGTM with one tiny nit

File: test/metabase/models/pulse_channel_test.clj (hunk 1 above)
Comment (camsaul) [reply test/metabase/models/pulse_channel_test.clj:431]: they're definitely horizontally aligned. Maybe it just looks off because there are quote marks on the value for `:email`

Comment (jeff303) [reply test/metabase/models/pulse_channel_test.clj:431]: Blah, my mistake.  `{:id Integer/MAX_VALUE}` is a completely different map.
