### PR TITLE
Use PUT /api/dashboard/:id to update dashcards and tabs

### LINKED ISSUE #35351: Adding a tab to a dashboard makes the dashboard shows double in collection view
### Describe the bug

Adding a tab to a dashboard makes the dashboard shows double in collection view. This has been tested on a fresh Metabase  instance, though this occurred with my usual testing instance as well.

### To Reproduce

1. Create a dashboard, after it's created and is in edit mode, click cancel (not sure it has any implication, but I did that)
2. Go to the root collection. See that there is only 1 dashboard
    Screenshot 2023-11-03 at 4 41 28 PM
4. Go to the dashboard again, edit, add a tab and save
5. Go to the root collection. Now you'll see 2 dashboards with the same name
    Screenshot 2023-11-03 at 4 41 39 PM
7. Refresh the page, it still shows 2 dashboards
8. Archive the dashboard, clicking one will automatically select the duplicate.
9. Restore the archive dashboard and go to the root collection. You'll only see 1 dashboard.

### Expected behavior

I should only see 1 dashboard each not also its duplicate

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Mac OS X",
    "os.version": "14.0",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-10-30",
      "src_hash": "a3c4f2dde12e997149db5929f356c3181ffa94d3",
      "tag": "v1.47.1-SNAPSHOT",
      "hash": "84c16b6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Not blocking but looks super weird and confusing

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calherries**
Epic: https://github.com/metabase/metabase/issues/35209

This is the 2nd PR in a series of 3 PRs to change the way dashboards are saved to use `PUT /api/dashboard/:id`.

This also fixes https://github.com/metabase/metabase/issues/35351, though that wasn't the main goal initially.

The 1st PR in this series focused on BE prep for this change: https://github.com/metabase/metabase/pull/35223

We currently have to call two endpoints to update a dashboard with its nested entities. There should only be one.

**Before, to update a dashboard and its dashcards/tabs, you need to:** 
- Make a request to `PUT /api/dashboard/:id` to update the dashboard, excluding dashcards and tabs
- Then make a request to `PUT /api/dashboard/:id/cards` to update the dashcards and tabs

**With this PR, to update a dashboard and its dashcards/tabs, you need to:** 

1. (exact same steps as before)

OR

2. Make a single request to `PUT /api/dashboard/:id` to update the dashboard, _including_ dashcards and tabs (this method is currently untested and unused, but it works with manual testing)

In the previous PR, all code and tests still follow method 1. In this PR, I update the code and tests to follow method 2.

### BE changes
I've updated the tests that follow method 1, (i.e. all tests using the `PUT /api/dashboard/:id/cards` endpoint) to use method 2.

I've marked `/api/dashboard/:id/cards` as deprecated, to be removed in 49.

### FE changes
I've updated the code and tests that follow method 1, (i.e. all places using the `PUT /api/dashboard/:id/cards` endpoint) to use method 2.

### Follow up work: 

PR 3:
  - [De-duplicate BE events that do the same thing, i.e. multiple calls to `push-revision!`](https://github.com/metabase/metabase/pull/35413)

### CODE REVIEW

**Comment by calherries** [comment]
@metabase/core-backend-dashviz the BE is ready for review. The FE is still a WIP.

File: test/metabase/api/dashboard_test.clj [hunk 1]
```diff
@@ -1442,36 +1442,42 @@
...
+                                                       :size_x           1
+                                                       :size_y           1
+                                                       :col              3
+                                                       :row              3
+                                                       :dashboard_tab_id -1
+                                                       :card_id          card-id-2}]})]
+          (testing "name got updated correctly"
+            (is (= "Updated dashboard name"
+                   (t2/select-one-fn :name :model/Dashboard :id dashboard-id)
+                   (:name resp))))
```
Comment (calherries) [inline test/metabase/api/dashboard_test.clj:1479]: This is the single new BE test. Every other change to this namespace just switches existing tests that use `PUT /api/dashboard/:id/cards` to use `PUT /api/dashboard/:id` instead.

**Review by markbastian — APPROVED** [review]
🚢 🇮🇹

File: frontend/src/metabase/schema.js [hunk 2]
```diff
@@ -70,6 +71,10 @@ export const SnippetCollectionSchema = new schema.Entity("snippetCollections");
 export const TimelineSchema = new schema.Entity("timelines");
 export const TimelineEventSchema = new schema.Entity("timelineEvents");
 
+DashboardSchema.define({
+  dashcards: [DashcardSchema],
+});
+
```
Comment (kulyk) [inline frontend/src/metabase/schema.js:77]: Why do we need to normalize dashboard cards now? Not sure I've noticed a place where it's used

**Review by kulyk — CHANGES_REQUESTED** [review]
Looks great! Left a question about `normalizr`. Also, I think I ran into a bug:

1. Browse data > Sample Database
2. X-ray the Orders table, save it, and open it
3. Enter the editing mode, remove any dashcard, click Save
4. Save fails with the following error

```js
TypeError: Cannot read properties of undefined (reading '1')
    at tabs.ts:400:1
    at Array.forEach (<anonymous>)
    at tabs.ts:396:1
    at redux-toolkit.esm.js:672:1
    at produce (immer.esm.mjs:1:1)
    at redux-toolkit.esm.js:671:1
    at Array.reduce (<anonymous>)
    at reducer (redux-toolkit.esm.js:650:1)
    at index.js:30:1
    at Array.reduce (<anonymous>)
```

File: frontend/src/metabase/schema.js (hunk 2 above)
Comment (calherries) [reply frontend/src/metabase/schema.js:77]: I didn't think this was necessary either but I tried it and it fixed a bunch of e2e tests. But after hearing about your bug I suspect it fixed them because of a race condition. I'll remove this

**Comment by calherries** [comment]
@kulyk I can't repro the bug you found unfortunately, there might be some race condition happening.

**Review by kulyk — COMMENTED** [review]
Looks good!

**Review by kulyk — APPROVED** [review]
Looks good!
