### PR TITLE
Fix marking visible columns when joining Saved Questions with self-joins or native queries

### LINKED ISSUE #27521: Query fails when selecting two fields from nested query, when fields are identical except for their join-alias
Creating a question where we are selecting at least two fields with the same field_ref from a nested question (excluding the :join-alias option) results in an error when we run the query: `Distinct, non-empty sequence of Field clauses`.

# How to reproduce:

### Step 1: 

Create a question (Q1) with a "self-join", where the same table is joined to itself. Select at least one common field from both the left and right joins.

For example:

image
 
Here's the MBQL of this example (note field `[:field 38 nil]` is the ID field from Orders)
```
{:database 1,
 :query
 {:fields [[:field 38 nil]],
  :joins [{:alias "Orders",
           :condition [:= [:field 38 nil] [:field 38 {:join-alias "Orders"}]],
           :fields [[:field 38 {:join-alias "Orders"}]],
           :source-table 2}],
  :source-table 2},
 :type :query}
```

### Step 2: 

Create a question (Q2) where the , where the same table is joined to another. Make sure two columns are selected from the same column on the original table.

image

Here's the MBQL of this example question:
```
{:database 1,
 :query
   {:fields [[:field 49 nil]],
    :joins [{:alias "Question 212",
             :condition [:= [:field 49 nil]
                         [:field 38 {:join-alias "Question 212"}]], ;; Where "Question 212" is Q1
             :fields :all,
             :source-table "card__212"}],
    :source-table 5},
 :type :query}
```

This is the stacktrace from processing the query:
```
metabase.query-processor.middleware.resolve-joins/eval78193 (resolve_joins.clj:76)
clojure.core/map (core.clj:2759)
clojure.lang.PersistentVector/reduce (PersistentVector.java:343)
clojure.core/transduce (core.clj:6946)
clojure.core/into (core.clj:6962)
clojure.core/into (core.clj:6950)
metabase.query-processor.middleware.resolve-joins/eval78241 (resolve_joins.clj:90)
metabase.query-processor.middleware.resolve-joins/eval78241 (resolve_joins.clj:87)
clojure.core/comp (core.clj:2586)
clojure.core/update (core.clj:6231)
clojure.core/update (core.clj:6223)
metabase.query-processor.middleware.resolve-joins/eval78349 (resolve_joins.clj:144)
metabase.query-processor.middleware.resolve-joins/eval78349 (resolve_joins.clj:141)
metabase.query-processor.middleware.resolve-joins/resolve-joins-in-mbql-query-all-levels (resolve_joins.clj:162)
metabase.query-processor.middleware.resolve-joins/resolve-joins-in-mbql-query-all-levels (resolve_joins.clj:160)
clojure.core/update (core.clj:6231)
clojure.core/update (core.clj:6223)
metabase.query-processor.middleware.resolve-joins/resolve-joins (resolve_joins.clj:176)
metabase.query-processor.middleware.resolve-joins/resolve-joins (resolve_joins.clj:172)
clojure.lang.Var/invoke (Var.java:384)
metabase.query-processor/preprocess* (query_processor.clj:158)
clojure.lang.PersistentVector/reduce (PersistentVector.java:343)
clojure.core/reduce (core.clj:6885)
clojure.core/reduce (core.clj:6868)
metabase.query-processor/preprocess* (query_processor.clj:156)
metabase.query-processor/preprocess* (query_processor.clj:151)
metabase.query-processor/fn (query_processor.clj:240)
metabase.query-processor.middleware.resolve-database-and-driver/resolve-database-and-driver (resolve_database_and_driver.clj:36)
metabase.driver/do-with-driver (driver.clj:76)
metabase.driver/do-with-driver (driver.clj:72)
metabase.query-processor.middleware.resolve-database-and-driver/resolve-database-and-driver (resolve_database_and_driver.clj:35)
metabase.query-processor.middleware.fetch-source-query/resolve-card-id-source-tables (fetch_source_query.clj:317)
metabase.query-processor.middleware.store/initialize-store (store.clj:12)
metabase.query-processor.store/do-with-store (store.clj:46)
metabase.query-processor.store/do-with-store (store.clj:40)
metabase.query-processor.middleware.store/initialize-store (store.clj:11)
metabase.query-processor.middleware.normalize-query/normalize (normalize_query.clj:23)
metabase-enterprise.audit-app.query-processor.middleware.handle-audit-queries/handle-internal-queries (handle_audit_queries.clj:131)
metabase.query-processor.reducible/async-qp (reducible.clj:101)
metabase.query-processor.reducible/async-qp (reducible.clj:107)
clojure.core/apply (core.clj:667)
clojure.core/apply (core.clj:662)
metabase.query-processor/base-qp (query_processor.clj:261)
clojure.core/apply (core.clj:667)
clojure.core/apply (core.clj:662)
metabase.query-processor.reducible/sync-qp (reducible.clj:127)
clojure.core/apply (core.clj:669)
clojure.core/apply (core.clj:662)
metabase.query-processor/process-query (query_processor.clj:278)
metabase.query-processor/process-query (query_processor.clj:272)
dev.nocommit.scratch/eval165528 (NO_SOURCE_FILE:30)
dev.nocommit.scratch/eval165528 (NO_SOURCE_FILE:28)
clojure.lang.Compiler/eval (Compiler.java:7194)
clojure.core/eval (core.clj:3215)
clojure.core/eval (core.clj:3211)
nrepl.middleware.interruptible-eval/evaluate (interruptible_eval.clj:87)
clojure.core/apply (core.clj:667)
clojure.core/with-bindings* (core.clj:1990)
nrepl.middleware.interruptible-eval/evaluate (interruptible_eval.clj:87)
clojure.main/repl (main.clj:437)
clojure.main/repl (main.clj:458)
clojure.main/repl (main.clj:368)
nrepl.middleware.interruptible-eval/evaluate (interruptible_eval.clj:84)
nrepl.middleware.interruptible-eval/evaluate (interruptible_eval.clj:56)
nrepl.middleware.interruptible-eval/interruptible-eval (interruptible_eval.clj:152)
nrepl.middleware.session/session-exec (session.clj:218)
nrepl.middleware.session/session-exec (session.clj:217)
java.lang.Thread/run (Thread.java:829)
```

Reproduced on metabase version: 0.45.2

### LINKED ISSUE #39033: findColumnIndexesFromLegacyRefs doesn't handle columns with the same name
### Describe the bug

When there are columns with the same name coming from different sources (e.g. source table and a joined table) then `findColumnIndexesFromLegacyRefs` won't match the columns correctly even if `field_ref` has the correct join alias.

### To Reproduce

1. Create native question A `select ID, PRODUCT_ID, TOTAL from orders`
2. Create native question B `select * from products`
3. Create GUI question C based on A, joins B on A.PRODUCT_ID = B.ID
4. Visualize the question in branch `new-table-viz-settings-2`
5. `B.ID` column would not be shown in the table because the corresponding table setting wasn't matched with the column

For this question
```
findColumnIndexesFromLegacyRefs(
  query,
  -1,
  data.cols,
  data.cols.map(col => col.field_ref)
);
```

don't match for one of the joined columns.

Screenshot 2024-02-22 at 00 31 29

### Expected behavior

All columns should be matched given that all data here is coming from QP

### Logs

_No response_

### Information about your Metabase installation

```JSON
-
```

### Severity

P1/P2 no data shown

### Additional context

_No response_

### LINKED ISSUE #47734: Cannot toggle join fields for a question that has multiple breakouts
### Describe the bug

When a question used for a join has multiple breakouts of the same column, is not possible to toggle columns on and off.

### To Reproduce

1. New -> Question -> Sample DB -> Orders
2. Aggregate by Count, Breakout by Created At: Month, Created At: Year -> Save as Q1
3. New -> Question -> Select Orders
4. Join -> Questions -> Select Q1 -> On Orders.ID = Q1.Count
5. Visualize
6. Open the viz settings sidebar (Gear icon in the bottom left corner) -> Add or remove columns
7. Try to toggle Created At columns from Q1 on and off

### Expected behavior

It should be possible to add/remove join fields; the `:selected` property should be correct.

The root cause seems to be that `lib.ref/ref` returns a field id-based field ref in this case that would be fully identical for these columns.

### Logs

`Multiple plausible matches with the same :join-alias - more disambiguation needed`

### Information about your Metabase installation

```JSON
Date: 2024-09-06
Commit: 38dcee8
Version: Pre-0.51
```

### Severity

P2

### Additional context

_No response_

### LINKED ISSUE #62383: Lib.visibleColumns are not marked as selected when joining a saved question with a self-join
This is what the test in #60583 "for #27521" is actually testing. 

https://github.com/metabase/metabase/pull/60583/files#diff-a61dd84afd16b942264df96ebd9007e423c2bcf9fe49e5bcd9c71d4413887930R71

The test doesn't actually test #27521

This bug is similar to #39033 so I am prioritizing it the same way.

### PR DESCRIPTION
**Pull request by camsaul**
I was trying to fix #27521 when I realized it's actually already fixed on Stats/`master` -- see https://stats.metabase.com/question/28013-27521-q2

This PR adds a backend test to repro #27521 and confirm that it is fixed, and enables a skipped Cypress test for this bug.

Fixes #27521

There's a test for #27521 added by #60583 here: https://github.com/metabase/metabase/pull/60583/files#diff-a61dd84afd16b942264df96ebd9007e423c2bcf9fe49e5bcd9c71d4413887930R71 but it doesn't actually test whether the query can run or not -- it just checks whether fields are marked selected by Lib correctly or not. This is a completely separate bug from #27521, which I opened as #62383, and went ahead and fixed anyway.

Fixes #62383

By fixing that I also ended up fixing https://github.com/metabase/metabase/issues/39033 and #47734

Fixes https://github.com/metabase/metabase/issues/39033
Fixes #47734

### CODE REVIEW

**Review by ranquild — APPROVED** [review]

File: test/metabase/query_processor_test/field_ref_repro_test.clj [hunk 1]
```diff
@@ -65,176 +63,6 @@
                (mt/rows+column-names
                 (qp/process-query query))))))))
 
-;;; TODO (Cam 8/19/25) -- move these tests into Lib (probably [[metabase.lib.field-ref-repro-test]]) since marking
-;;; things `:selected?` is a pure-Lib concern.
-
-;; other than producing the metadata for the card, there is no query processing here
-(deftest ^:parallel duplicate-names-selection-test
```
Comment (camsaul) [inline test/metabase/query_processor_test/field_ref_repro_test.clj:72]: I moved these tests into `metabase.lib.equality-test` since they're pure-Lib tests anyway

File: test/metabase/lib/equality_test.cljc [hunk 2]
```diff
@@ -1140,3 +1141,260 @@
...
+              (map #(select-keys % [:lib/source-column-alias :lib/desired-column-alias :display-name])
+                   returned)))
+      (is (=? [{:lib/source-column-alias "ID",         :display-name "ID",         :selected? true}
+               {:lib/source-column-alias "PRODUCT_ID", :display-name "Product ID", :selected? true}
+               {:lib/source-column-alias "REVIEWER",   :display-name "Reviewer",   :selected? true}
+               {:lib/source-column-alias "RATING",     :display-name "Rating",     :selected? true}
+               {:lib/source-column-alias "BODY",       :display-name "Body",       :selected? true}
+               {:lib/source-column-alias "CREATED_AT", :display-name "Created At", :selected? true}
+               ;; the following two Card 1 → ID should have :selected? true
+               {:lib/source-column-alias "ID",    :display-name "Card 1 → ID", :selected? true} ; FIXME - these should be true
```
Comment (bshepherdson) [inline test/metabase/lib/equality_test.cljc:1203]: Are they not fixed now? This `FIXME` comment seems stale.

**Review by bshepherdson — APPROVED** [review]

File: test/metabase/lib/equality_test.cljc (hunk 2 above)
Comment (camsaul) [reply test/metabase/lib/equality_test.cljc:1203]: oh yeah oops. I did fix it. Haha
