### PR TITLE
Fix FieldValuesWidget not showing spinner when loading list values

### LINKED ISSUE #25322: Loading spinners in filters don't appear anymore
**Describe the bug**
In pre-44, we had a loading spinner to indicate that the filter values were being loaded
image

In 44, we don't show anything, and this is concerning for users with huge app db's where the queries take a long time
image

**Logs**
NA

**To Reproduce**
1) create a question in 43.4 (just select people table), add it to a dashboard, then add a location filter to the dashboard, connect it to the question and save it
2) throttle the browser to slow 3g, see the spinner
3) upgrade the instance to 44
4) do the same and see that the spinner dissapeared

**Expected behavior**
bring back the spinners when things take time!

**Screenshots**
Above

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres 14
- Metabase version: 44
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
P2 (since it impacts our bigger customers)

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/25322
Reproduces https://github.com/metabase/metabase/issues/25322

How to test:
- Follow the steps from the issue or run the cypress test which does exactly the same

Screenshot 2022-09-21 at 13 47 55

### CODE REVIEW

File: frontend/src/metabase/components/FieldValuesWidget.jsx [hunk 1]
```diff
@@ -301,11 +301,7 @@ class FieldValuesWidgetInner extends Component {
     const isLoading = loadingState === "LOADING";
     const usesListField =
       !disableList &&
-      hasList({
-        fields,
-        disableSearch,
-        options,
```
Comment (ranquild) [inline frontend/src/metabase/components/FieldValuesWidget.jsx:307]: options here will always be empty because they haven't been loaded yet

**Review by daltojohnso — APPROVED** [review]
