### PR TITLE
If multiple limit or offset arguments are passed, only use the 1st one

### LINKED ISSUE #45345: Passing `?limit=` twice to a question URL returns a bare 500
### Describe the bug

When adding the `?limit=` url search parameter to a question twice, I get a bare unstyled 500 page. Even for questions that do not have a `limit` parameter defined at all.

Screenshot 2024-07-09 at 16 51 59

### To Reproduce

1. Create any question and save it
2. Visit the question and add `?limit=1&limit=2` to the url
3. See the bare 500 page

### Expected behavior

Passing the limit url param twice is not supported, but we should either redirect to remove one of the limits, or render a more useful error page.

### Logs

_No response_

### Information about your Metabase installation

```JSON
On `master` at 6946a5d3dd122d4510cabbae407a44d1ab1e2d6b as well as on stats.
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nvoxland**
### Description

Fixes #45345 based closed PR #48650

Did not end up using Malli as the change was well isolated already and simple

### How to verify

Adding an extra &limit or &offset to a question loads the page and strips off the extra limit/offset like in PR 48650

image

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by noahmoss — APPROVED** [review]

**Comment by noahmoss** [comment]
Nice!

File: src/metabase/server/middleware/offset_paging.clj [hunk 1]
```diff
@@ -21,9 +21,16 @@
   Automatically generated by a handler in offset-paging middleware."
   false)
 
+(defn- ensure-single-value
+  "For parameters that should have a single value, only return the 1st if multiple values were passed in the request"
+  [v]
+  (if (vector? v)
```
Comment (dpsutton) [inline src/metabase/server/middleware/offset_paging.clj:27]: This is all reasonable, but I'm not convinced that the collections of params will always be vectors. Is this too concrete of a collection type? Should it be something more generally "sequential"-y?

Comment (nvoxland) [reply src/metabase/server/middleware/offset_paging.clj]: Good point. New version look better?

**Review by dpsutton — APPROVED** [review]

**Review by dpsutton — CHANGES_REQUESTED** [review]
We should have a real test that hits the webserver

**Comment by dpsutton** [comment]
```clojure
(deftest multiple-limits
  (is (= 2
         (-> (mt/user-real-request :crowberto :get 200 "search?q=product&limit=2&limit=3")
             :data count))))
```

```clojure
offset-test=> (clojure.test/run-test multiple-limits)

Testing metabase.query-processor-test.offset-test

FAIL in (multiple-limits) (http_client.clj:211)
GET http://localhost:3000/api/search?q=product&limit=2&limit=3 expected a status code of 200, got 500.
expected: 200
  actual: 500
    diff: - 200
          + 500

FAIL in (multiple-limits) (offset_test.clj:316)
expected: 2
  actual: 0
    diff: - 2
          + 0

Ran 1 tests containing 2 assertions.
2 failures, 0 errors.
{:test 1, :pass 0, :fail 2, :error 0, :type :summary}
```

File: test/metabase/query_processor_test/offset_test.clj [hunk 2]
```diff
@@ -310,3 +310,12 @@
                  (mt/formatted-rows
                   [->local-date 2.0]
                   (qp/process-query query)))))))))
+
+(deftest multiple-limits
+  (let [total_count (-> (mt/user-real-request :crowberto :get 200 "search?q=product")
+                        :data count)
+        result_count (-> (mt/user-real-request :crowberto :get 200 "search?q=product&limit=2&limit=3")
+                         :data count)]
+    (is (and
```
Comment (escherize) [inline test/metabase/query_processor_test/offset_test.clj:319]: I think it would be better to have two `is`s here, that test for each one of these seperately. That way when one or the other (or both) fail you'll know in the test report.

File: test/metabase/query_processor_test/offset_test.clj [hunk 3]
```diff
@@ -310,3 +310,12 @@
                  (mt/formatted-rows
                   [->local-date 2.0]
                   (qp/process-query query)))))))))
+
+(deftest multiple-limits
+  (let [total_count (-> (mt/user-real-request :crowberto :get 200 "search?q=product")
+                        :data count)
+        result_count (-> (mt/user-real-request :crowberto :get 200 "search?q=product&limit=2&limit=3")
+                         :data count)]
```
Comment (escherize) [inline test/metabase/query_processor_test/offset_test.clj:318]: We name most args using kebab-case not snake_case.

**Review by dpsutton — APPROVED** [review]
Removing the request changes hold

**Review by escherize — APPROVED** [review]
