### PR TITLE
Remove :bigquery driver

### LINKED ISSUE #20141: Remove legacy BigQuery driver
As of release 43, it's time to remove the "legacy" `:bigquery` driver, and migrate any existing databases to the newer driver, `:bigquery-cloud-sdk`.

- If the database already uses a `service-account-json` for authentication (which has been the only option since x.36 via #12498), then this migration will be seamless
- If the database in question still has OAuth credentials, we will log an error message during the data migration phase, and the database will be left in a broken state (admin will need to update it to specify the service account, then Save)

### PR DESCRIPTION
**Pull request by jeff303**
Add data migration to convert existing Database instances from :bigquery to :bigquery-cloud-sdk (with error log if using outdated OAuth mechanisms)

Removing references to :bigquery from various places in the code

### CODE REVIEW

File: src/metabase/db/data_migrations.clj [hunk 1]
```diff
@@ -369,6 +369,19 @@
...
+    (when-not (empty? (filter some? ((juxt :auth-code :client-id :client-secret) details)))
+      (log/errorf (str "Database ID %d used the :bigquery driver with OAuth style authentication scheme, which cannot"
+                       " be automatically migrated to :bigquery-cloud-sdk; leaving authentication options nil in the"
+                       " db details, which must be corrected by an admin (by setting a service-account-json), so that"
+                       " sync and query can work again")
+                  (u/the-id bigquery-db)))
+    (let [migrated-details (-> (assoc details :engine :bigquery-cloud-sdk) ; switch to new driver
+                               ;; remove all OAuth related keys
+                               (dissoc :auth-code :client-id :client-secret :access-token :refresh-token))]
+      (db/update! Database (u/the-id bigquery-db) :details migrated-details))))
```
Comment (camsaul) [inline src/metabase/db/data_migrations.clj:383]: I really really would prefer this be done in a Liquibase migration. Are you 100% sure we can't just migrate the driver in Liqubase e.g.

```sql
UPDATE metabase_database
SET engine = 'bigquery-cloud-sdk'
WHERE engine = 'bigquery'
```

And then detect and correct this situation (legacy OAuth details) in the `normalize-db-details` method?

Comment (camsaul) [reply src/metabase/db/data_migrations.clj:383]: Actually, wouldn't it be sufficient just to ignore those keys entirely? Do you even need to remove them at all?

File: src/metabase/db/data_migrations.clj [hunk 2]
```diff
@@ -369,6 +369,19 @@
...
 
+(defmigration ^{:author "jeff303" :added "0.43.0"} remove-bigquery-driver
+  (doseq [{:keys [:details] :as bigquery-db} (db/select Database :engine "bigquery")]
+    (when-not (empty? (filter some? ((juxt :auth-code :client-id :client-secret) details)))
+      (log/errorf (str "Database ID %d used the :bigquery driver with OAuth style authentication scheme, which cannot"
+                       " be automatically migrated to :bigquery-cloud-sdk; leaving authentication options nil in the"
+                       " db details, which must be corrected by an admin (by setting a service-account-json), so that"
+                       " sync and query can work again")
+                  (u/the-id bigquery-db)))
+    (let [migrated-details (-> (assoc details :engine :bigquery-cloud-sdk) ; switch to new driver
```
Comment (camsaul) [inline src/metabase/db/data_migrations.clj:380]: `engine` is a separate top-level column in `Database`. It's not inside `details`

**Review by camsaul — CHANGES_REQUESTED** [review]
It looks like the data migration doesn't actually update `Database.engine`. Either way, that part should 100% be done as a Liquibase migration. I don't think we **need** to remove the old OAuth keys from details but if we do we should do it in `normalize-details` rather than in a Clojure-land data migration.

I would vote for just ignoring them, that way if someone switches branches and downgrades they'd just have to switch the driver back and wouldn't have to re-enter all of their OAuth credentials 

Other than that everything else is looking good

File: src/metabase/db/data_migrations.clj [hunk 3]
```diff
@@ -180,7 +180,7 @@
 ;; continue to run as legacy SQL.
 (defmigration ^{:author "camsaul", :added "0.30.0"} add-legacy-sql-directive-to-bigquery-sql-cards
   ;; For each BigQuery database...
-  (doseq [database-id (db/select-ids Database :engine "bigquery")]
+  (doseq [database-id (db/select-ids Database :engine "bigquery")] ; TODO: keep this?
```
Comment (camsaul) [inline src/metabase/db/data_migrations.clj:183]: We should go ahead and take this out now. Since we'd be upgrading to the new driver before we ever reach this point this migration will effectively always be a no-op. 

If anyone migrates from 29 or older to 43 or newer they'll have to manually add `#legacy` directives to their BigQuery SQL queries written in legacy SQL

File: src/metabase/db/data_migrations.clj (hunk 1 above)
Comment (jeff303) [reply src/metabase/db/data_migrations.clj:383]: Yeah, this is feasible.  I originally got stuck into thinking I could register `normalize-db-details` for `:bigquery`, but that obviously wouldn't work if the driver (which needs initialization) is being removed.

File: src/metabase/db/data_migrations.clj (hunk 2 above)
Comment (jeff303) [reply src/metabase/db/data_migrations.clj]: Oops, you'd think I would remember this by now.

File: src/metabase/db/data_migrations.clj (hunk 3 above)
Comment (jeff303) [reply src/metabase/db/data_migrations.clj]: Done.

**Review by camsaul — APPROVED** [review]
Awesome. This LGTM. Thanks for doing this

**Comment by camsaul** [comment]
@jeff303 Done
