### PR TITLE
Fixes ordering issue in parameters

### LINKED ISSUE #62079: Variable/Parameter odering is not kept on published questions
### Describe the bug

Variables/Parameters are not ordered the same way in the embed as they are ordered in the editor UI, where the user can set their custom ordering

# Question

1. I don't know if this is a bug or missing feature?
2. If it's a missing feature: how can I influence the order of the parameters in the embedded version?

### To Reproduce

1. Create new question
2. Order parameter fields in a userfriendly way
3. Publish question for static embed with one locked parameter and all others editable
4. Expect in the embed/preview to see the parameters in the order I've set them up in the UI
5. Actual: parameters are in "random" order.

https://github.com/user-attachments/assets/ec0c4e0b-53d9-4f44-ae4c-e79ac3c622be

### Expected behavior

I would expect to see the same order in the embed as I've set it up in the question/editor.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-08-11",
      "tag": "v0.56.1.5",
      "hash": "a6ddf2f"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",                 //// this happens also on our postgres backed productive installation 
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "5.15.0-91-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

not blocking entirely. it is very ugly not being able to create consistently organized embeds.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #62079
Closes [EMB-718: Variable/Parameter odering is not kept on published questions](https://linear.app/metabase/issue/EMB-718/variableparameter-odering-is-not-kept-on-published-questions)

### Description

The function that syncs query variables with card parameters for native questions used to put all parameters in a map, losing user-made ordering (if any). This was only visible above a certain number of parameters (9 for me, but maybe it depends on... other things? It's not supposed to be deterministic anyway).

This change preserves the order users might have done.

### How to verify

1. Create new question, with a bunch of parameters (9 did the trick for me)
2. Order parameter fields in a userfriendly way
3. Publish question as a public link
4. Expect in the public question to have the parameters in the order you've set them up in the UI
5. Actual: parameters are in "random" order.

You can also create the question using the API and then publish it (the custom ordering here is defined by the `parameters` array, and you can see how it differs from the template-tags):

```
curl -s -X POST http://localhost:3000/api/card \
  -H "Content-Type: application/json" \
  -H "x-api-key: <YOUR_API_TOKEN>" \
  -d '{
    "name": "EMB-718 Parameter Order Test",
    "dataset_query": {
      "type": "native",
      "native": {
        "query": "SELECT * FROM ORDERS WHERE 1=1 [[AND TOTAL > {{zeta}}]] [[AND TOTAL < {{alpha}}]] [[AND QUANTITY > {{mu}}]] [[AND QUANTITY < {{beta}}]] [[AND DISCOUNT > {{omega}}]] [[AND DISCOUNT < {{gamma}}]] [[AND SUBTOTAL > {{theta}}]] [[AND SUBTOTAL < {{delta}}]] [[AND ID > {{epsilon}}]]",
        "template-tags": {
          "zeta":    {"id": "_ZETA_",    "name": "zeta",    "display-name": "1 - Zeta",    "type": "number"},
          "alpha":   {"id": "_ALPHA_",   "name": "alpha",   "display-name": "2 - Alpha",   "type": "number"},
          "mu":      {"id": "_MU_",      "name": "mu",      "display-name": "3 - Mu",      "type": "number"},
          "beta":    {"id": "_BETA_",    "name": "beta",    "display-name": "4 - Beta",    "type": "number"},
          "omega":   {"id": "_OMEGA_",   "name": "omega",   "display-name": "5 - Omega",   "type": "number"},
          "gamma":   {"id": "_GAMMA_",   "name": "gamma",   "display-name": "6 - Gamma",   "type": "number"},
          "theta":   {"id": "_THETA_",   "name": "theta",   "display-name": "7 - Theta",   "type": "number"},
          "delta":   {"id": "_DELTA_",   "name": "delta",   "display-name": "8 - Delta",   "type": "number"},
          "epsilon": {"id": "_EPSILON_", "name": "epsilon", "display-name": "9 - Epsilon", "type": "number"}
        }
      },
      "database": 1
    },
    "parameters": [
      {"id": "_ZETA_",    "type": "number/=", "slug": "zeta",    "name": "1 - Zeta",    "target": ["variable", ["template-tag", "zeta"]]},
      {"id": "_ALPHA_",   "type": "number/=", "slug": "alpha",   "name": "2 - Alpha",   "target": ["variable", ["template-tag", "alpha"]]},
      {"id": "_MU_",      "type": "number/=", "slug": "mu",      "name": "3 - Mu",      "target": ["variable", ["template-tag", "mu"]]},
      {"id": "_BETA_",    "type": "number/=", "slug": "beta",    "name": "4 - Beta",    "target": ["variable", ["template-tag", "beta"]]},
      {"id": "_OMEGA_",   "type": "number/=", "slug": "omega",   "name": "5 - Omega",   "target": ["variable", ["template-tag", "omega"]]},
      {"id": "_GAMMA_",   "type": "number/=", "slug": "gamma",   "name": "6 - Gamma",   "target": ["variable", ["template-tag", "gamma"]]},
      {"id": "_THETA_",   "type": "number/=", "slug": "theta",   "name": "7 - Theta",   "target": ["variable", ["template-tag", "theta"]]},
      {"id": "_DELTA_",   "type": "number/=", "slug": "delta",   "name": "8 - Delta",   "target": ["variable", ["template-tag", "delta"]]},
      {"id": "_EPSILON_", "type": "number/=", "slug": "epsilon", "name": "9 - Epsilon", "target": ["variable", ["template-tag", "epsilon"]]}
    ],
    "display": "table",
    "visualization_settings": {}
  }'
```

### Demo

Before:
SCR-20260407-nefg

After:
SCR-20260407-ndko

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

**Review by WiNloSt — COMMENTED** [review]
I only verified that the test captures the bug on master by making sure it failed.

I would wait to BE engineer to give the stamp to the PR.

File: test/metabase/query_processor/card_test.clj [hunk 1]
```diff
@@ -391,3 +391,26 @@
...
+    ;; PersistentArrayMap (used for <= 8 entries) preserves insertion order, but PersistentHashMap (>= 9) does not.
+    (let [tag-names  ["zeta" "alpha" "mu" "beta" "omega" "gamma" "theta" "delta" "epsilon"]
+          tag-ids    (mapv #(str "_" (u/upper-case-en %) "_") tag-names)
+          tags       (into {} (map (fn [n id] [n {:id id :name n :display-name (str n " param") :type :text}])
+                                   tag-names tag-ids))
+          params     (mapv (fn [n id] {:id id :type :string/= :slug n :name (str n " param")
+                                       :target [:variable [:template-tag n]]})
+                           tag-names tag-ids)
+          placeholders (str/join " AND " (map #(str % " = {{" % "}}") tag-names))
+          query      (str "SELECT * FROM t WHERE " placeholders)]
```
Comment (bshepherdson) [inline test/metabase/query_processor/card_test.clj:415]: Let's try to reorganize this to make it easier to follow. The `:id`s are constructed so they can be inlined.

```suggestion
    (let [tag-names  ["zeta" "alpha" "mu" "beta" "omega" "gamma" "theta" "delta" "epsilon"]
          name->id   #(str "_" (u/upper-case-en %) "_")
          tags       (into {} (map (fn [n]
                                     [n {:id           (name->id n)
                                         :name         n
                                         :display-name (str n " param")
                                         :type         :text}]))
                              tag-names)
          params     (mapv (fn [n]
                             {:id     (name->id n)
                              :type   :string/=
                              :slug   n
                              :name   (str n " param")
                              :target [:variable [:template-tag n]]})
                           tag-names)
          placeholders (str/join " AND " (map #(str % " = {{" % "}}") tag-names))
          query      (str "SELECT * FROM t WHERE " placeholders)]
```

File: test/metabase/query_processor/card_test.clj [hunk 2]
```diff
@@ -391,3 +391,26 @@
...
+      (mt/with-temp [:model/Card card {:dataset_query {:database (mt/id)
+                                                       :type     :native
+                                                       :native   {:template-tags tags
+                                                                  :query         query}}
+                                       :parameters    params}]
+        (let [result (qp.card/combined-parameters-and-template-tags card)]
+          (is (= tag-ids
```
Comment (bshepherdson) [inline test/metabase/query_processor/card_test.clj]:
```suggestion
          (is (= (mapv name->id tag-names)
```

**Review by bshepherdson — APPROVED** [review]

File: src/metabase/query_processor/card.clj [hunk 3]
```diff
@@ -256,12 +256,19 @@
...
-                       ;; order importance: we want the info from `template-tag` to be merged last
-                       (update acc id #(merge % parameter)))
-                     id->parameter
-                     id->template-tags-parameter))))
+        parameter-ids               (into #{} (map :id) parameters)
+        ;; Preserve the order of card.parameters, merging in template-tag info
+        merged-parameters           (mapv (fn [param]
+                                            (if-let [tt-param (get id->template-tags-parameter (:id param))]
+                                              ;; order importance: we want the info from `template-tag` to be merged last
+                                              (merge param tt-param)
```
Comment (metamben) [inline src/metabase/query_processor/card.clj:264]: if `param` is a hash map, then `merge`, there ordering will be unpredictable. i.e., the same problem we are fixing regarding `reduce-kv`.

File: src/metabase/query_processor/card.clj [hunk 4]
```diff
@@ -256,12 +256,19 @@
...
+                                              param))
+                                          parameters)
+        ;; Append any template-tag parameters not already present in card.parameters
+        extra-parameters            (into []
+                                          (remove #(contains? parameter-ids (:id %)))
+                                          template-tag-parameters)]
+    (into merged-parameters extra-parameters)))
```
Comment (metamben) [inline src/metabase/query_processor/card.clj]:
```suggestion
                                          parameters)]
    ;; Append any template-tag parameters not already present in card.parameters
    (into merged-parameters
          (remove #(contains? parameter-ids (:id %)))
          template-tag-parameters))
```

File: test/metabase/query_processor/card_test.clj [hunk 5]
```diff
@@ -391,3 +391,26 @@
                      (get-in response [:headers "Content-Disposition"])
                      (str expected-slug "_"))
                     (str "Expected filename to contain: " expected-slug))))))))))
+
+(deftest combined-parameters-and-template-tags-preserves-parameter-order-test
+  (testing "combined-parameters-and-template-tags should preserve the order of card.parameters (#62079)"
+    ;; Use enough parameters (9) so that Clojure's PersistentHashMap doesn't coincidentally preserve insertion order.
```
Comment (metamben) [inline test/metabase/query_processor/card_test.clj]:
```suggestion
    ;; Use enough parameters (9) so that Clojure switches to PersistentHashMap.
```

**Review by metamben — APPROVED** [review]
