### PR TITLE
Fix filtering on LocalDates

### LINKED ISSUE #20333: Question Builder: Generate SQL with naive dates instead of localized timestamps
I'm using Metabase 0.42.0 with PostgreSQL and I noticed that one particular question built with the question builder took very long to complete compared to a native query.

The question is basically "count all rows where column = x", where column has the PostgreSQL type `date`. In the question builder, everything looks like Metabase correctly detects that this column is a date column. It allows me to specify the time in addition to the date, but this is optional. However, the Metabase logs showed the following:

```
{:type :query, 
…
:filter
…
[:field 716 {:temporal-unit :default}]
[:absolute-datetime #t "2022-01-01T00:00+01:00[Europe/Berlin]" :default]]
[:< 
 [:field 716 {:temporal-unit :default}]
```

which already indicates that Metabase is using a localized timestamp instead of a naive date type. The slow query log revealed the following:

```sql
 …WHERE (… AND "my_schema"."my_table"."my_date_column" >= $2 AND "my_schema"."my_table"."my_date_column" < $3)
 --  parameters: … $2 = '2021-01-01 00:00:00+01', $3 = '2021-01-22 00:00:00+01'
```

The slow query log unfortunately does not tell us which type is used for ` '2021-01-01 00:00:00+01'` and `'2021-01-22 00:00:00+01'`, but given the output from the Metabase log and the fact that the string includes timezone information, I would assume it's `timestamptz`. So based on this assumption, I try to reproduce what Metabase is doing by running a raw SQL query, like this:

```sql
…WHERE (… AND "my_schema"."my_table"."my_date_column" >= '2021-01-01 00:00:00+01'::timestamptz AND
"my_schema"."my_table"."my_date_column" < '2021-01-22 00:00:00+01'::timestamptz)
```
which takes about 56 seconds to complete, which is about the same time it took metabase to complete this query from the question builder. The explain plan shows that no indexes are being used. Next, I try to run a raw SQL query like the one above, but with `date` types instead of `timestamptz` types:

```sql
…WHERE (… AND "my_schema"."my_table"."my_date_column" >= '2021-01-01'::date AND
"my_schema"."my_table"."my_date_column" < ' 2021-01-22'::date)
```

This time, the query takes 140ms to complete, and the index is being used.

**Proposal**

Could you provide the possibility to treat columns of type `date` as simple, naive dates without any timestamp conversions in the background to make it easier for PostgreSQL (and perhaps other databases) to use indexes?

**Motivation**

We have tables with more than 100 million rows, and the date column is usually that one column that allows us to run queries that don't take forever to complete. So, it would be a great improvement for us if Metabase generates SQL queries where indexes based on `date` columns are used whenever possible.

### LINKED ISSUE #39769: Filtering by a Specific Date in Snowflake will bring inaccurate results
### Describe the bug

Filtering by "Specific date" filter in Snowflake will bring wrong results

### To Reproduce

1. Create a table in Snowflake with the SQL below the steps
2. Create a GUI * from table and put it in a dashboard
3. Add a Relative dates filter and connect it to the card
4. Select "Specific dates" as a filter, "On" and filter by "November 12th, 2023"
5. See that the card will show records from November 13th as well
Screenshot 2024-03-07 at 11 39 29 AM

<details>
<summary>SQL for creating table and adding data with date time column</summary>

CREATE TABLE sample_table (
    id INTEGER,
    user_name VARCHAR,
    created_at TIMESTAMP
);

-- Insert sample data for each hour of each day from November 10 to November 15
INSERT INTO sample_table (id, user_name, created_at)
SELECT
    ROW_NUMBER() OVER (ORDER BY day, hour) AS id,
    'User_' || ROW_NUMBER() OVER (ORDER BY day, hour) AS user_name,
    DATEADD('MINUTE', (hour + day * 24) * 60, '2023-11-10 00:00:00') AS created_at
FROM
    (
        SELECT 0 AS day UNION ALL
        SELECT 1 UNION ALL
        SELECT 2 UNION ALL
        SELECT 3 UNION ALL
        SELECT 4 UNION ALL
        SELECT 5
    ) AS days
CROSS JOIN
    (
        SELECT 0 AS hour UNION ALL
        SELECT 1 UNION ALL
        SELECT 2 UNION ALL
        SELECT 3 UNION ALL
        SELECT 4 UNION ALL
        SELECT 5 UNION ALL
        SELECT 6 UNION ALL
        SELECT 7 UNION ALL
        SELECT 8 UNION ALL
        SELECT 9 UNION ALL
        SELECT 10 UNION ALL
        SELECT 11 UNION ALL
        SELECT 12 UNION ALL
        SELECT 13 UNION ALL
        SELECT 14 UNION ALL
        SELECT 15 UNION ALL
        SELECT 16 UNION ALL
        SELECT 17 UNION ALL
        SELECT 18 UNION ALL
        SELECT 19 UNION ALL
        SELECT 20 UNION ALL
        SELECT 21 UNION ALL
        SELECT 22 UNION ALL
        SELECT 23
    ) AS hours;
</details>

### Expected behavior

Should only bring the results from that day

### Logs

query in snowflake
```
SELECT "PUBLIC"."SAMPLE_TABLE_2"."ID" AS "ID", "PUBLIC"."SAMPLE_TABLE_2"."USER_NAME" AS "USER_NAME", "PUBLIC"."SAMPLE_TABLE_2"."CREATED_AT" AS "CREATED_AT" 
FROM "sample"."PUBLIC"."SAMPLE_TABLE_2" 
WHERE ("PUBLIC"."SAMPLE_TABLE_2"."CREATED_AT" >= ?) AND ("PUBLIC"."SAMPLE_TABLE_2"."CREATED_AT" < ?) LIMIT 2000

-- {"pulseId":null,"serverId":"adbf7a69-c037-43f2-9b43-bb98001f852f","client":"Metabase","queryHash":"233e5c2a605bb015ded3bc42a539d1c9607a48eae959eed9d316e10ce199d526","queryType":"query","cardId":114,"dashboardId":35,"context":"dashboard","userId":1,"databaseId":34}
```

### Information about your Metabase installation

```JSON
- Metabase 48.8
```

### Severity

P2

### Additional context

_No response_

### LINKED ISSUE #40332: Specific date filter shifts dates by one day
### Describe the bug

When creating a question with the Metabase editor and setting a filter on a range of specific dates as shown

image

the results returned are shifted one day 'forward' (spanning Feb 2 through Feb 8) as shown

image

What is most puzzling is that that the generated SQL from the editor appears to be correct
```
SELECT
  DATE_TRUNC("day", "_DIM_DATES__via___DIM_DATE_KEY"."DATE") AS "_DIM_DATES__via___DIM_DATE_KEY__DATE",
  COUNT(*) AS "count"
FROM
  "ANALYTICS"."PUBLIC"."_REDACTED_"
 
LEFT JOIN "ANALYTICS"."PUBLIC"."_DIM_DATES" AS "_DIM_DATES__via___DIM_DATE_KEY" ON "PUBLIC"."_REDACTED_"."_DIM_DATE_KEY" = "_DIM_DATES__via___DIM_DATE_KEY"."_DIM_DATE_KEY"
WHERE
  (
    "_DIM_DATES__via___DIM_DATE_KEY"."DATE" >= '2024-02-01 00:00 Z':: timestamp_tz
  )
 
   AND (
    "_DIM_DATES__via___DIM_DATE_KEY"."DATE" < '2024-02-08 00:00 Z':: timestamp_tz
  )
GROUP BY
  DATE_TRUNC("day", "_DIM_DATES__via___DIM_DATE_KEY"."DATE")
ORDER BY
  DATE_TRUNC("day", "_DIM_DATES__via___DIM_DATE_KEY"."DATE") ASC
  ```
  
  And, indeed, if I take the above SQL and create a new SQL query in Metabase, I get the correct range of dates
  
  
image

### To Reproduce

Unfortunately, I am not able to reproduce with an equivalent query in the sample database. One potential difference is that the  sample database uses colums of type DateTime, whereas the date dimension in my example is of type Date. But it's still baffling why the same SQL generated by the question editor works when submitted as SQL.

### Expected behavior

I would expect the Metabase question to return the same set of rows as the SQL query does, for a set of dates that match what was selected in the date picker.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.210-201.852.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "materialize"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-14",
      "tag": "v0.49.0",
      "hash": "46c668b"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

Severely degrading the trust our stakeholders place in Metabase

### Additional context

This example is running against Snowflake.

### PR DESCRIPTION
**Pull request by camsaul**
Stop doing dumb things with local dates that give you unexpected results.

1. Don't parse a local date literal like `2024-03-20` to an `OffsetDateTime` or `ZonedDateTime`. Previously, we'd try to parse it to something like `#t "2024-03-20T00:00:00-07:00[US/Pacific]"` using the QP results timezone (either `report-timezone` if the DB supports session timezones, or the database timezone if it does not). Predictably, this caused bugs. Just parse it to a `LocalDate` instead.
2. Don't try to optimize a `LocalDate = LocalDate` or `day(LocalDate) = day(LocalDate)` filters to `:between` filters; we can leave them as `=`. E.g. instead of generating 

   ```sql
   WHERE date_column >= timestamp '2024-03-20T00:00:00-07:00` 
     AND date_column < timestamp  '2024-03-21T00:00:00-07:00'
   ```
   
   we should just generate
   
   ```sql
   WHERE date_column = date '2024-03-20'
   ```
   
   This causes way less problems and is more performant, and is nicer to look at.

Fixes #39769
Fixes #40332

This was split off from #40416, which is a more significant overhaul that fixes more things, but too big to backport.

### CODE REVIEW

File: src/metabase/query_processor/middleware/wrap_value_literals.clj [hunk 1]
```diff
@@ -101,19 +104,129 @@
...
+
+(defn- LocalTime->OffsetTime [t]
+  (if (= (qp.timezone/results-timezone-id) "UTC")
+    (t/offset-time t (t/zone-offset 0))
+    ;; if the zone is something else, we'll just have to make do with a LocalTime, since there's no way to determine
+    ;; what the appropriate offset to use for something like `US/Pacific` is for a give TIME with no DATE associated
+    ;; with it.
+    t))
+
+(defmethod coerce-temporal [LocalDate      LocalTime] [_t _target-class] (throw-invalid-time))
```
Comment (snoe) [inline src/metabase/query_processor/middleware/wrap_value_literals.clj:137]: I feel that a few comment blocks explaining some of the things to consider would be helpful.

- All Local to Offset/Zoned conversions must consider `results-timezone-id`
- All Offset/Zoned to Local conversions do not need to consider `results-timezone-id` because session timezone will already be applied (is that correct?)
- Others?

File: src/metabase/query_processor/middleware/wrap_value_literals.clj [hunk 2]
```diff
@@ -101,19 +104,129 @@
...
+(defmethod coerce-temporal [OffsetTime     OffsetDateTime] [_t _target-class] (throw-invalid-datetime))
+(defmethod coerce-temporal [LocalDateTime  OffsetDateTime] [t _target-class]  (t/offset-date-time t (qp.timezone/results-timezone-id)))
+(defmethod coerce-temporal [OffsetDateTime OffsetDateTime] [t _target-class]  t)
+(defmethod coerce-temporal [ZonedDateTime  OffsetDateTime] [t _target-class]  (t/offset-date-time t))
+
+(defmethod coerce-temporal [LocalDate      ZonedDateTime] [t target-class]   (coerce-temporal (t/local-date-time t (t/local-time 0)) target-class))
+(defmethod coerce-temporal [LocalTime      ZonedDateTime] [_t _target-class] (throw-invalid-datetime))
+(defmethod coerce-temporal [OffsetTime     ZonedDateTime] [_t _target-class] (throw-invalid-datetime))
+(defmethod coerce-temporal [LocalDateTime  ZonedDateTime] [t _target-class]  (t/zoned-date-time t (t/zone-id (qp.timezone/results-timezone-id))))
+(defmethod coerce-temporal [OffsetDateTime ZonedDateTime] [t _target-class]  t) ; OffsetDateTime is perfectly fine.
```
Comment (snoe) [inline src/metabase/query_processor/middleware/wrap_value_literals.clj:172]: I'm not sure it is perfectly fine, I believe adding/comparing time to an offsetdatetime across a daylight savings shift could give an incorrect result. I'm not sure when we would actually get into this conversion though to test this scenario.

```

 snoe> snoe=# set timezone = "America/Edmonton";
SET
 snoe> snoe=# select ('2024-03-09T23:59'::timestamp) at time zone 'America/Chicago' + '3 hour'::interval;
        ?column?
------------------------
 2024-03-10 01:59:00-07
(1 row)

 snoe> snoe=# select ('2024-03-09T23:59'::timestamp) at time zone 'America/Chicago' + '4 hour'::interval;
        ?column?
------------------------
 2024-03-10 03:59:00-06
(1 row)

 snoe> snoe=# set timezone = "MST";
SET
 snoe> snoe=# select ('2024-03-09T23:59'::timestamp) at time zone 'America/Chicago' + '3 hour'::interval;
        ?column?
------------------------
 2024-03-10 01:59:00-07
(1 row)

 snoe> snoe=# select ('2024-03-09T23:59'::timestamp) at time zone 'America/Chicago' + '4 hour'::interval;
        ?column?
------------------------
 2024-03-10 02:59:00-07
(1 row)

```

**Review by snoe — APPROVED** [review]
