### PR TITLE
Fix BigQuery incorrectly quoting datetime-truncated field literal forms

### LINKED ISSUE #20806: BigQuery: Aggregating by a datetime in a saved question fails because of bad aliasing
**Describe the bug**
There's a bug in the way that backticks are placed around table aliases and field names that's causing saved questions to fail with BigQuery when you try to group by a datetime field using the query builder. 

**To Reproduce**
1. Write SQL, save a question as the following:
```
select
    date 
from
    unnest(generate_date_array('2021-01-01', '2022-01-01')) date
```
2. Click Explore results, open editor
3.  Summarize count and group by date:week

This is the output SQL:

```
SELECT datetime_trunc(CAST(`source.date` AS datetime), week(monday)) AS `date`, count(*) AS `count`
FROM (select
    date 
from
    unnest(generate_date_array('2021-01-01', '2022-01-01')) date) `source`
GROUP BY `date`
ORDER BY `date` ASC
```

The error is because BigQuery expects the table alias and field to be backticked separately, so instead of ``` `source.date` ```, it should be ``` `source`.`date` ```

**Severity**

Honestly, this has been a pretty annoying blocker for me over the past couple weeks. I got my company upgraded to 0.42, excited to make more use of the new models feature. However, I've been reverting back to writing SQL and pre-building dbt models just to get things done on time, rather than using joins or saved questions. I'd like to do more data modelling within metabase as one might with Looker, but little bugs like this while working with joined, nested and saved questions are preventing me from doing so

### PR DESCRIPTION
**Pull request by camsaul**
Our BigQuery driver was incorrectly qualifying Field literal forms that were subject to datetime truncation. 

Clauses like 
```clojure
[:field "date" {:base-type :type/Date, :temporal-unit :week}]
```

were incorrectly compiled to SQL like

```sql
datetime_trunc(CAST(`source.date` AS datetime), week(sunday))
```

As opposed to 

```sql
datetime_trunc(CAST(`source`.`date` AS datetime), week(sunday))
```

BigQuery requires tables to be qualified with the dataset name (project ID), but as if it were a identifier, e.g.

```sql
`my_dataset.table`.`field`
```

Our code that qualified identifiers with the dataset name was incorrectly being applied to identifiers from the `source` query in certain cases, resulting in 

```sql
`source.field`
```

instead of

```sql
`source`.`field`
``` 

The main reason for this is that we were not properly recording that Fields from the `source` query should not be qualified; we were passing this info along with a dynamic variable, but it was out of scope by the time we compiled `TruncForm` objects to SQL. I fixed this by adding the information in the `Identifier` object itself 

Fixes #20806

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 1]
```diff
@@ -161,7 +161,7 @@
   nil)
 
 (defn- throw-invalid-query [e sql parameters]
-  (throw (ex-info (tru "Error executing query")
+  (throw (ex-info (tru "Error executing query: {0}" (ex-message e))
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:164]: Unrelated to this fix but I changed a few errors to include the parent error message to make query failures easier to debug. The updated error message is already used elsewhere so it's already i18n'ed

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj [hunk 2]
```diff
@@ -466,9 +466,9 @@
   table e.g.
 
     `table`.`field` -> `dataset.table`.`field`"
-  [{:keys [identifier-type components] :as identifier}]
+  [{:keys [identifier-type components], ::keys [do-not-qualify?], :as _identifier}]
   (cond
-    (::already-qualified? (meta identifier))
+    do-not-qualify?
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:471]: We were previously recording whether something was _already_ qualified using metadata attached to the `Identifier`. I switched this to adding a key to the `Identifier` object itself to make it easier to see when debugging stuff and harder to accidentally toss

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj [hunk 3]
```diff
@@ -491,17 +491,16 @@
...
+  (letfn [(prefix-components [[dataset-id table & more]]
+            (cons (str (when-let [proj-id (project-id-for-current-query)]
+                         (str proj-id \.))
+                       dataset-id
+                       \.
+                       table)
+                  more))]
+    (cond-> identifier
+      (should-qualify-identifier? identifier) (update :components prefix-components)
+      true                                    (assoc ::do-not-qualify? true))))
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:503]: The main change here is to always add the `::do-not-qualify?` (previously `::already-qualified?`) key here, even if `should-qualify-identifier?` is falsey, This effectively captures the value of `*field-is-from-join-or-source-query?*` so deferred compilation to SQL will still do the right thing

File: src/metabase/util/honeysql_extensions.clj [hunk 4]
```diff
@@ -83,8 +83,11 @@
        (for [component components]
          (hformat/quote-identifier component, :split false)))))
   pretty/PrettyPrintable
-  (pretty [_]
-    (cons `identifier (cons identifier-type components))))
+  (pretty [this]
+    (if (= (set (keys this)) #{:identifier-type :components})
+      (cons `identifier (cons identifier-type components))
+      ;; if there's extra info beyond the usual two keys print with the record type reader literal syntax e.g. #metabase..Identifier {...}
+      (list (symbol (str \# `Identifier)) (into {} this)))))
```
Comment (camsaul) [inline src/metabase/util/honeysql_extensions.clj:90]: I tweaked the pretty-print method for `hx/Identifier` to print it with normal record type reader literal syntax e.g.

```clojure
#metabase.util.honeysql_extensions.Identifier {...}
```

if it contains extra keys beyond the usual `identifier-type` and `components` keys. This is so it will print any additional info that a driver might add, like the `::do-not-qualify?` info that we add

**Review by flamber — APPROVED** [review]
Works :tada: - and I've tried doing a few more levels of nesting and more advanced things, but cannot seem to cause any problems.

**Comment by flamber** [comment]
@camsaul Just noticed these, but I'm unsure if it comes from this PR:
```
2022-03-10 20:28:47,047 WARN middleware.upgrade-field-literals :: Warning: clause [:field "date" {:base-type :type/Date, :temporal-unit :year}] does not match a column in the source query. Attempting to correct this to [:field "date" {:base-type :type/Date, :temporal-unit :year}]
2022-03-10 20:28:47,131 WARN middleware.upgrade-field-literals :: Warning: clause [:field "date" {:base-type :type/Date, :temporal-unit :year}] does not match a column in the source query. Attempting to correct this to [:field "date" {:base-type :type/Date, :temporal-unit :year}]
2022-03-10 20:28:47,191 WARN middleware.upgrade-field-literals :: Warning: clause [:field "date" {:base-type :type/Date, :temporal-unit :year}] does not match a column in the source query. Attempting to correct this to [:field "date" {:base-type :type/Date, :temporal-unit :year}]
2022-03-10 20:28:48,343 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.3 s (15 DB calls) App DB connections: 1/7 Jetty threads: 3/50 (4 idle, 0 queued) (60 total active threads) Queries in flight: 0 (0 queued)
```
The question looks like this, where the custom column is just `1+1`
image

**Comment by camsaul** [comment]
@flamber that wouldn't come from this PR, that message happens way before we get to the MBQL -> SQL transpilation stage. It does seem a little weird tho. Probably a bug. I'll look in to it separately
