### PR TITLE
i18n: do not remove empty plural from translation

### LINKED ISSUE #16323: Cannot create more than 2 metrics, when UI language is Turkish - screen goes blank or displays "Something went wrong"
**Describe the bug**
When UI language is set to Turkish, then it's not possible to create questions with more than 2 metrics. Regression since 0.39.0
This is a close P1.

**To Reproduce**
1. Change system/user locale to Turkish
2. Simple question > Sample Dataset > Orders
3. Summarize 3 times by Count (that's `Satır sayısı` for non-natives) - _it could be any metrics, just trying to simplify the repro_
4. The screen goes blank and the console have the following errors in the browser console
<details><summary>Browser console</summary>

```
vendor.bundle.js?8f423c47488b32b1f66b:487 TypeError: Cannot read property 'replace' of undefined
    at vendor.bundle.js?8f423c47488b32b1f66b:448
    at Array.reduce (<anonymous>)
    at g (vendor.bundle.js?8f423c47488b32b1f66b:448)
    at l (vendor.bundle.js?8f423c47488b32b1f66b:448)
    at t.default (app-main.bundle.js?8f423c47488b32b1f66b:5)
    at Go (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at za (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at vs (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at vu (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at gu (vendor.bundle.js?8f423c47488b32b1f66b:487)
ns @ vendor.bundle.js?8f423c47488b32b1f66b:487
o.componentDidCatch.n.callback @ vendor.bundle.js?8f423c47488b32b1f66b:487
fo @ vendor.bundle.js?8f423c47488b32b1f66b:487
ss @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487
t.unstable_runWithPriority @ vendor.bundle.js?8f423c47488b32b1f66b:495
Wi @ vendor.bundle.js?8f423c47488b32b1f66b:487
Mu @ vendor.bundle.js?8f423c47488b32b1f66b:487
uu @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487
t.unstable_runWithPriority @ vendor.bundle.js?8f423c47488b32b1f66b:495
Wi @ vendor.bundle.js?8f423c47488b32b1f66b:487
Vi @ vendor.bundle.js?8f423c47488b32b1f66b:487
Ui @ vendor.bundle.js?8f423c47488b32b1f66b:487
P @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487

vendor.bundle.js?8f423c47488b32b1f66b:487 TypeError: Cannot read property 'replace' of undefined
    at vendor.bundle.js?8f423c47488b32b1f66b:448
    at Array.reduce (<anonymous>)
    at g (vendor.bundle.js?8f423c47488b32b1f66b:448)
    at l (vendor.bundle.js?8f423c47488b32b1f66b:448)
    at t.default (app-main.bundle.js?8f423c47488b32b1f66b:5)
    at Go (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at vs (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at vu (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at gu (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at uu (vendor.bundle.js?8f423c47488b32b1f66b:487)
ns @ vendor.bundle.js?8f423c47488b32b1f66b:487
n.callback @ vendor.bundle.js?8f423c47488b32b1f66b:487
fo @ vendor.bundle.js?8f423c47488b32b1f66b:487
ss @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487
t.unstable_runWithPriority @ vendor.bundle.js?8f423c47488b32b1f66b:495
Wi @ vendor.bundle.js?8f423c47488b32b1f66b:487
Mu @ vendor.bundle.js?8f423c47488b32b1f66b:487
uu @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487
t.unstable_runWithPriority @ vendor.bundle.js?8f423c47488b32b1f66b:495
Wi @ vendor.bundle.js?8f423c47488b32b1f66b:487
Vi @ vendor.bundle.js?8f423c47488b32b1f66b:487
Ui @ vendor.bundle.js?8f423c47488b32b1f66b:487
P @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487

vendor.bundle.js?8f423c47488b32b1f66b:448 Uncaught TypeError: Cannot read property 'replace' of undefined
    at vendor.bundle.js?8f423c47488b32b1f66b:448
    at Array.reduce (<anonymous>)
    at g (vendor.bundle.js?8f423c47488b32b1f66b:448)
    at l (vendor.bundle.js?8f423c47488b32b1f66b:448)
    at t.default (app-main.bundle.js?8f423c47488b32b1f66b:5)
    at Go (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at vs (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at vu (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at gu (vendor.bundle.js?8f423c47488b32b1f66b:487)
    at uu (vendor.bundle.js?8f423c47488b32b1f66b:487)
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:448
g @ vendor.bundle.js?8f423c47488b32b1f66b:448
l @ vendor.bundle.js?8f423c47488b32b1f66b:448
t.default @ app-main.bundle.js?8f423c47488b32b1f66b:5
Go @ vendor.bundle.js?8f423c47488b32b1f66b:487
vs @ vendor.bundle.js?8f423c47488b32b1f66b:487
vu @ vendor.bundle.js?8f423c47488b32b1f66b:487
gu @ vendor.bundle.js?8f423c47488b32b1f66b:487
uu @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487
t.unstable_runWithPriority @ vendor.bundle.js?8f423c47488b32b1f66b:495
Wi @ vendor.bundle.js?8f423c47488b32b1f66b:487
Vi @ vendor.bundle.js?8f423c47488b32b1f66b:487
Ui @ vendor.bundle.js?8f423c47488b32b1f66b:487
P @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487

app-main.bundle.js?8f423c47488b32b1f66b:5 Couldn't load metadata TypeError: Cannot read property 'setDefaultQuery' of null
    at app-main.bundle.js?8f423c47488b32b1f66b:5
    at l (vendor.bundle.js?8f423c47488b32b1f66b:98)
    at Generator._invoke (vendor.bundle.js?8f423c47488b32b1f66b:98)
    at Generator.next (vendor.bundle.js?8f423c47488b32b1f66b:98)
    at r (app-main.bundle.js?8f423c47488b32b1f66b:5)
    at app-main.bundle.js?8f423c47488b32b1f66b:5
(anonymous) @ app-main.bundle.js?8f423c47488b32b1f66b:5
l @ vendor.bundle.js?8f423c47488b32b1f66b:98
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:98
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:98
r @ app-main.bundle.js?8f423c47488b32b1f66b:5
(anonymous) @ app-main.bundle.js?8f423c47488b32b1f66b:5
Promise.then (async)
r @ app-main.bundle.js?8f423c47488b32b1f66b:5
(anonymous) @ app-main.bundle.js?8f423c47488b32b1f66b:5
(anonymous) @ app-main.bundle.js?8f423c47488b32b1f66b:5
(anonymous) @ app-main.bundle.js?8f423c47488b32b1f66b:5
(anonymous) @ app-main.bundle.js?8f423c47488b32b1f66b:5
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:495
value @ app-main.bundle.js?8f423c47488b32b1f66b:5
O @ app-main.bundle.js?8f423c47488b32b1f66b:5
onChangeAggregation @ app-main.bundle.js?8f423c47488b32b1f66b:5
r.commitAggregation @ app-main.bundle.js?8f423c47488b32b1f66b:5
r.onPickAggregation @ app-main.bundle.js?8f423c47488b32b1f66b:5
handleChange @ app-main.bundle.js?8f423c47488b32b1f66b:5
c.default.createElement.c.default.createElement.onClick @ app-main.bundle.js?8f423c47488b32b1f66b:5
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487
h @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487
g @ vendor.bundle.js?8f423c47488b32b1f66b:487
ot @ vendor.bundle.js?8f423c47488b32b1f66b:487
rt @ vendor.bundle.js?8f423c47488b32b1f66b:487
at @ vendor.bundle.js?8f423c47488b32b1f66b:487
ht @ vendor.bundle.js?8f423c47488b32b1f66b:487
j @ vendor.bundle.js?8f423c47488b32b1f66b:487
F @ vendor.bundle.js?8f423c47488b32b1f66b:487
Gt @ vendor.bundle.js?8f423c47488b32b1f66b:487
Xt @ vendor.bundle.js?8f423c47488b32b1f66b:487
t.unstable_runWithPriority @ vendor.bundle.js?8f423c47488b32b1f66b:495
Wi @ vendor.bundle.js?8f423c47488b32b1f66b:487
P @ vendor.bundle.js?8f423c47488b32b1f66b:487
(anonymous) @ vendor.bundle.js?8f423c47488b32b1f66b:487

app-main.bundle.js?8f423c47488b32b1f66b:5 Uncaught (in promise) TypeError: Cannot read property 'card' of null
    at app-main.bundle.js?8f423c47488b32b1f66b:5
    at l (vendor.bundle.js?8f423c47488b32b1f66b:98)
    at Generator._invoke (vendor.bundle.js?8f423c47488b32b1f66b:98)
    at Generator.next (vendor.bundle.js?8f423c47488b32b1f66b:98)
    at r (app-main.bundle.js?8f423c47488b32b1f66b:5)
    at app-main.bundle.js?8f423c47488b32b1f66b:5
    at new Promise (<anonymous>)
    at app-main.bundle.js?8f423c47488b32b1f66b:5
    at app-main.bundle.js?8f423c47488b32b1f66b:5
    at app-main.bundle.js?8f423c47488b32b1f66b:5
```

</details>

5. Doing the same summarization, but through Custom question (Notebook) will show a "Something went wrong" box and the frontend reloads, so all unsaved changes are lost
<details><summary>Something went wrong</summary>

```
    in Unknown
    in div
    in Text
    in Subhead
    in ViewHeading
    in div
    in div
    in div
    in Clean.div
    in Flex
    in ViewSection
    in ViewTitleHeader
    in div
    in Unknown
    in div
    in div
    in t
    in View
    in t
    in FitViewport
    in Unknown
    in Title[]
    in Title[Title[]]
    in QueryBuilder
    in Unknown
    in UserIsAuthenticated(Component)
    in Connect(UserIsAuthenticated(Component))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in div
    in t
    in ScrollToTop
    in t
    in App
    in Title[App]
    in RouterContext
    in Router
    in t
    in DragDropContextProvider
    in a
```

</details>

**Information about your Metabase Installation:**
Regression since 0.39.0

**Additional context**
I'm quite sure that this is the same problem as #16198 or very related.

### PR DESCRIPTION
**Pull request by pawit-metabase**
The ttag library expect the plural array to be exactly the size as the number of plural forms defined in the header.

If we remove empty plural, the array will have the wrong size and the library will crash when the trying to use the non-existent plural.

By leaving the empty string there, the ttag library will correctly detect it and use the English version for the missing variant.

This does not affect the backend because the backend does not support plurals.

Fixes #16323

### CODE REVIEW

**Review by flamber — APPROVED** [review]
It works, and will be correctly translated from 0.41
image

Would be great if a Clojure dev could review it too.

File: bin/i18n/src/i18n/common.clj [hunk 1]
```diff
@@ -36,7 +36,7 @@
     {:id                (.getMsgid message)
      :id-plural         (.getMsgidPlural message)
      :str               (.getMsgstr message)
-     :str-plural        (seq (remove str/blank? (.getMsgstrPlural message)))
+     :str-plural        (seq (.getMsgstrPlural message))
```
Comment (pawit-metabase) [inline bin/i18n/src/i18n/common.clj:39]: @camsaul Can you help take a look at this? Was there any specific reason we're removing blank string from plurals?

Comment (camsaul) [reply bin/i18n/src/i18n/common.clj:39]: I don't know exactly _why_ we're doing it. These scripts are just a port of some old node.js scripts written by someone who left years ago... I just made the new scripts return exactly the same thing as the old ones. I don't know why the old ones did this, but if it doesn't make sense then we should change it

**Review by camsaul — APPROVED** [review]
