### PR TITLE
Use MLv2 to determine whether a query can be previewed

### LINKED ISSUE #40608: Notebook query preview exists even before the data source is selected
### Describe the bug

We're showing the notebook query preview even before someone selects a data source. Clicking on it will result in a forever loading spinner and a failed `POST /api/dataset` request.

### To Reproduce

1. Click on "New" > Question
new
2. Click on the little preview button next to the blue "Pick your starting data" rectangle
3. The loader is spinning ad infinitum and there is a failed request in the network tab
Kapture 2024-03-26 at 08 50 21

### Expected behavior

The preview button should appear only when a query can run, i.e. when there is a data source.

### Logs
```json
{
  "via": [
    {
      "type": "clojure.lang.ExceptionInfo",
      "message": "`database` is required for all queries whose type is not `internal`.",
      "data": {
        "status-code": 400,
        "query": {
          "type": "query",
          "query": {
            "limit": 10
          },
          "parameters": [],
          "middleware": {
            "js-int-to-string?": true,
            "userland-query?": true,
            "add-default-userland-constraints?": true
          },
          "info": null
        }
      },
      "at": [
        "metabase.api.dataset$fn__114124$_AMPERSAND_f__114127",
        "doInvoke",
        "dataset.clj",
        60
      ]
    }
  ],
  "trace": [
    [
      "metabase.api.dataset$fn__114124$_AMPERSAND_f__114127",
      "doInvoke",
      "dataset.clj",
      60
    ],
    [...],
    [
      "java.lang.Thread",
      "run",
      "Thread.java",
      829
    ]
  ],
  "cause": "`database` is required for all queries whose type is not `internal`.",
  "data": {
    "status-code": 400,
    "query": {
      "type": "query",
      "query": {
        "limit": 10
      },
      "parameters": [],
      "middleware": {
        "js-int-to-string?": true,
        "userland-query?": true,
        "add-default-userland-constraints?": true
      },
      "info": null
    }
  },
  "message": "`database` is required for all queries whose type is not `internal`.",
  "query": {
    "type": "query",
    "query": {
      "limit": 10
    },
    "parameters": [],
    "middleware": {
      "js-int-to-string?": true,
      "userland-query?": true,
      "add-default-userland-constraints?": true
    },
    "info": null
  }
}
```

### Information about your Metabase installation

local dev, `master`, dc279fd, H2, Sample Database

### Severity

P3

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### What does this PR accomplish?

It fixes #40608 by determining whether the query can run as a precondition to showing the preview button.

### How to verify
1. Start a new question
2. Make sure that the preview button doesn't exist before you select a data source

or

Run a provided E2E reproduction.

### Demo
Kapture 2024-04-02 at 21 15 58

### Checklist
- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx [hunk 1]
```diff
@@ -104,7 +105,7 @@ function NotebookStep({
   } = STEP_UI[step.type] || {};
 
   const color = getColor();
-  const canPreview = Boolean(step.getPreviewQuery);
+  const canPreview = Lib.canRun(step.query);
```
Comment (uladzimirdev) [inline frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx:108]: `Boolean(step.getPreviewQuery)` and `step.active && step.visible` lead the same result. 

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/notebook/lib/steps.ts#L281-L286

`Lib.canRun` is to determine if the query can run, but what if step is not visible? I'd double check at least by running e2e tests

Comment (uladzimirdev) [reply frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx:108]: you can check on `step.active` - if we render it, it's visible. `canRun` can return true even for not active step (e.g. expression step when there is no expression)

Comment (uladzimirdev) [reply frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx:108]: I don't mind, all my comments were about the previous implementation and my initial comment was about the wrong semantics (we checked that there was a function passed and based on this we show or hide preview button). I like dropping old code, but sometimes there is a reason why the code works like this and not differently. 

so once again, if can_preview works, that's great

Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx:108]: > all my comments were about the previous implementation and my initial comment was about the wrong semantics

Oh, got it now. Thanks for the clarification.

File: frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx [hunk 2]
```diff
@@ -105,7 +106,7 @@ function NotebookStep({
...
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx:109]: :x:  The preview button should not be shown for empty/incomplete steps.

https://github.com/metabase/metabase/assets/6830683/81fc21da-3ab8-4fbb-9299-3300ba5a942a

**Review by kamilmielnik — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx (hunk 2 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx:109]: https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGpiam9kMzlmcmF2eWN0MTBjajVybGozZzB2ZWJqcXh2OWVrdDM5cSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xT5LMzIK1AdZJ4cYW4/giphy.gif

Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx:109]: image

**Review by kamilmielnik — APPROVED** [review]
:+1:

File: e2e/test/scenarios/question/notebook.cy.spec.js [hunk 3]
```diff
@@ -678,9 +678,27 @@ describe("scenarios > question > notebook", { tags: "@slow" }, () => {
...
+      .within(() => {
+        cy.findByText("Pick your starting data").should("exist");
+        cy.icon("play").should("not.be.visible");
+      });
+
+    popover().findByTextEnsureVisible("Raw Data").click();
+    cy.get("@dataStep").icon("play").should("not.be.visible");
+    popover().findByTextEnsureVisible("Orders").click();
+
+    cy.findByTestId("step-filter-0-0").icon("play").should("not.be.visible");
```
Comment (uladzimirdev) [inline e2e/test/scenarios/question/notebook.cy.spec.js:698]: nit: `getNotebookStep` can be used

**Review by uladzimirdev — APPROVED** [review]

File: e2e/test/scenarios/question/notebook.cy.spec.js (hunk 3 above)
Comment (nemanjaglumac) [reply e2e/test/scenarios/question/notebook.cy.spec.js]: Great tip! Thank you.
https://github.com/metabase/metabase/pull/40609/commits/133743f0f59f67f072a8039bcad5a4f788b48984
