### PR TITLE
Test: Oracle compares dates (no time) correctly

### LINKED ISSUE #49878: Variable - Missing trunc when field filter is calling a date column with date and time
### Describe the bug

I use a field filter called date, with default value Today. 
This variable is compared with a date column with date and time.
The variabel look like this:
and "KUNDE"."EKKONTRIMPORT"."LOGGDATOTIDNY" = date '2024-11-12'

since LOGGDATOTIDNY have date and time, this two dates will never be correct without a trunc, like this.
and trunc("KUNDE"."EKKONTRIMPORT"."LOGGDATOTIDNY") = date '2024-11-12'

I have upgrade to last version, then trunc dissapear from the variable.

Could you please add trunc again to the column we comparing against, or let me choose to use trunc or not?

best regards Vilfred Gangsøy

### To Reproduce

1. Define a field variable with date widget type, select Today as default value.
2. Compare against a column with date and time
3. Will never be equal without trunc(fildname)

### Expected behavior

Use trunc around the field, as used in previus releases.
and trunc("KUNDE"."EKKONTRIMPORT"."LOGGDATOTIDNY") = date '2024-11-12'

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Metabase 0.51.3 
- Oracle 19
```

### Severity

Annoying with this kind of issues.

### Additional context

Please fix thisi ssue.

### PR DESCRIPTION
**Pull request by ericnormand**
Closes https://github.com/metabase/metabase/issues/49878

### Description

Issue https://github.com/metabase/metabase/issues/49878, back in November, was that Oracle was not comparing date-times correctly when compared to a single date without time. I was able to reproduce it in `v0.51.3` (reported in issue), but could not reproduce on master.

Just to be safe, I created tests that fail on `v0.51.3` that now pass on master. The tests cover two cases with field filters in native SQL queries that compare a datetime to a single date:

* Single Date
* All Options

### Note

Since this is a test only, I recommend not backporting because the test will fail on some prior releases.

### CODE REVIEW

File: modules/drivers/oracle/test/metabase/driver/oracle_test.clj [hunk 1]
```diff
@@ -563,3 +563,42 @@
...
+                                          :display-name "Date Filter"
+                                          :type         :dimension
+                                          :dimension    [:field (mt/id :date_cols_with_datetime_values_dates_with_time :date_with_time) nil]
+                                          :widget-type  :date/all-options}}})
+                query (assoc query :parameters [{:type   :date/all-options
+                                                 :target [:dimension [:template-tag "date_filter"]]
+                                                 :value  "2024-11-06"}])]
+            (is (= [[2M "2024-11-06T13:13:13Z"]]
+                   (mt/rows
+                    (qp/process-query query))))))))))
```
Comment (bshepherdson) [inline modules/drivers/oracle/test/metabase/driver/oracle_test.clj:604]: It looked at first like a single test case is getting duplicated here. There is a difference: the `:widget-type` is either `:date/all-options` or `:date/single`.

I think this would be much easier to read if that difference (and any others; perhaps I missed one) were captured in a `doseq`.

**Review by bshepherdson — CHANGES_REQUESTED** [review]

File: modules/drivers/oracle/test/metabase/driver/oracle_test.clj (hunk 1 above)
Comment (ericnormand) [reply modules/drivers/oracle/test/metabase/driver/oracle_test.clj]: You're right! I've fixed this.

**Review by bshepherdson — APPROVED** [review]
