### PR TITLE
Format date + time properly in action forms

### LINKED ISSUE #26442: [P1] Date input has broken values in implicit update form (but edit works)

### PR DESCRIPTION
**Pull request by iethree**
closes #26442

## Description

This is a band-aid fix for date editing that simply uses native date and [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) inputs in action forms. Datetime-local is a wonderful web primitive, but doesn't have awesome browser support in non-chromium browsers. Nonetheless, it makes dates actually editable in action forms for now.

Why not just fix it right and use a real, robust date component? I'm glad you asked. We're in the process of migrating all of our forms to formik, so as part of this process, we basically need to fork the old `FormWidget` component, and hook it up to all the new form components, including the new date component. This gets date forms basically working with minimal changes and doesn't waste time building date support into our old form framework. ([slack thread](https://metaboat.slack.com/archives/C049USTRF60/p1668543086349249?thread_ts=1668542534.542229&cid=C049USTRF60))

This also disables the quarter/year and month/year options for data parameters because we don't support those components yet.

Screen Shot 2022-11-15 at 3 24 22 PM

Screen Shot 2022-11-15 at 2 38 52 PM

## Testing Steps

- Edit a detail record in the People table in the sample database
- see that when you open a record in the edit modal for the scaffolded action, the date populates and is editable

### CODE REVIEW

File: frontend/src/metabase/writeback/containers/ActionParametersInputForm/utils.ts [hunk 1]
```diff
@@ -53,6 +54,15 @@ export const getInitialValues = (
...
   return Object.fromEntries(
-    form.fields.map(field => [field.name, prefetchValues[field.name] ?? ""]),
+    form.fields.map(field => {
+      const value = prefetchValues[field.name];
+      const formattedValue =
+        field.type === "date"
+          ? moment(value).utc(false).format("YYYY-MM-DD")
+          : field.type === "datetime-local"
+          ? moment(value).utc(false).format("YYYY-MM-DDTHH:mm")
+          : value ?? "";
```
Comment (kulyk) [inline frontend/src/metabase/writeback/containers/ActionParametersInputForm/utils.ts:64]: This is a bit hard to parse IMO, can we do something about it to make it a easier to follow? Maybe extract it to a function like `formatValue` or something?

**Review by kulyk — APPROVED** [review]
