### PR TITLE
Fix crash in ObjectDetail when parsing invalid JSON

### LINKED ISSUE #12600: Object Details breaks if Field Type is "Field containing JSON", but data is not `JSON`
**Describe the bug**
Object Details (visualization when clicking a primary key) does not work if it contains a field with type "Field is JSON", but the field is returning a non-JSON value.
This can happen if someone accidentally chooses that field type, but it's also a problem for columns that might contain mixed data (like Metabase's application database's table `setting`).

**To Reproduce**
1. Go to Admin > Data Model > Sample Dataset > Reviews
2. Set Field Type for "Body" to "Field containing JSON"
3. Simple question > Sample Dataset > Reviews
4. Click `ID` cell of first row, which should show Object Details, but is showing an error with the Run button as overlay, so it's not possible to see the error (which is only available in frontend):
image
5. Inspecting the source, reveals the error is `JSON.parse: unexpected character at line 1 column 1 of the JSON data`, but it's not shown in browser console

**Information about your Metabase Installation:**
Metabase 0.35.3 and `master` with various backends and browsers

**Additional context**
Similar to #12586, but this issue is frontend only (from what I can tell)

### PR DESCRIPTION
**Pull request by ghiculescu**
Fixes https://github.com/metabase/metabase/issues/12600

cc @flamber

### CODE REVIEW

**Comment by ghiculescu** [comment]
I'm not sure how I could have broken those tests :/

**Comment by dacort** [comment]
@ghiculescu It's not you, it's us. :) Cypress doesn't play well with 3rd-party PRs for some reason.

**Comment by nemanjaglumac** [comment]
@ghiculescu weirdly enough it's the same test failing in different CI groups. Feel free to skip it with the note, commit and push again. I'll keep an eye on any other potential failing tests for your PR.

```javascript
 // [quarantined]: flake, blocking 3rd party PR
    it.skip("allows 'Custom mapping' null values", () => {...})
```

The test lives in `frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js:147`

**Comment by ghiculescu** [comment]
@nemanjaglumac done! Feels weird disabling a test on your repo, but I guess you can always revert that after this is merged.

**Comment by nemanjaglumac** [comment]
@ghiculescu Yeah, no worries about that. There are some other flakes that were quarantined as well. I'll handle that. As long as there is a clear note and I'm aware that it's skipped.

This one was flaking for core contributors as well, if I'm not mistaken.

Thank you for your contribution! :)

**Comment by ghiculescu** [comment]
@nemanjaglumac looks like quite a few cypress tests are flakey for me. They don't seem to break on other people's PRs. Do you want me to `it.skip` all of them?

**Comment by nemanjaglumac** [comment]
@ghiculescu no, no. It was ok to skip that first one because it was flaking for us as well. Like @dacort said, something weird is going on with CI for 3rd party PRs. If failing tests are not related to your changes, GitHub admin can force merge your PR even with the failing Cypress.
We need to wait on a code review and approval from a dev who is OOO this week. I requested a review so he should be able to check your changes sometimes next week.

File: frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx [hunk 1]
```diff
@@ -160,7 +160,12 @@ export class ObjectDetail extends Component {
       if (value === null || value === undefined || value === "") {
         cellValue = <span className="text-light">{t`Empty`}</span>;
       } else if (isa(column.special_type, TYPE.SerializedJSON)) {
-        const formattedJson = JSON.stringify(JSON.parse(value), null, 2);
+        let formattedJson;
+        try {
+          formattedJson = JSON.stringify(JSON.parse(value), null, 2);
+        } catch (e) {
+          formattedJson = JSON.stringify(value, null, 2);
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx:167]: Since we didn't parse `value` as JSON, I don't think we need to `stringify` it here. We'd end up with quotes around the malformed JSON in the display.

e.g. `JSON.stringify('{"malformedJSON": ')` -> `"{\"malformedJSON\": "` rather than `{\"malformedJSON\": `.

Just this is probably fine though I guess `formattedJson` is a bit of a misnomer if we went into the `catch`.

```suggestion
          formattedJson = value;
```

**Review by paulrosenzweig — CHANGES_REQUESTED** [review]
Thanks for the PR, @ghiculescu! I left a comment with one small change, but otherwise it looks good!

File: frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx (hunk 1 above)
Comment (ghiculescu) [reply frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx:167]: Hmmm okay, I just copied what was happening in the next code path.

image

I figured this made sense because we don't know what type `value` is, but we can be confident `JSON.stringify` will return a string.

(Between you and me, I didn't actually verify my changes in a browser because the process of getting everything set up for just this change was a bit daunting. I just verified via the test passing.)

Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx]: I hadn't check in browser either, but I just did and it worked.

**Review by paulrosenzweig — APPROVED** [review]
