### PR TITLE
Remove collections without questions or models from SavedQuestionPicker

### LINKED ISSUE #28068: Admins seeing "All personal collections" in New question data picker can lead to performance issues
**Describe the bug**
Admins have the option to start a new question based on any question saved in any of the (potentially hundreds and thousands) other users' personal collections. This is sub-optimal for large instances.

**To Reproduce**
_Log in as admin_
1. Create several additional users 
2. Have at least one saved question in ANY collection
3. Create new question with "New > Question" and then
4. Click on "Saved questions" in the data picker
image

Notice two things:
1. UI displays "All personal collections"
2. Network tab reveals that the call to `GET /api/collection/tree?tree=true` has been made

**Expected behavior**
Not an easy thing to say because this behavior was in the product for a very long time.
- One approach would be to completely remove "All personal collections" from the question picker, but that would most likely break flows and expectations for many people
- Another approach would be to not show empty personal collections
- One more approach would be to introduce pagination or something similar, but that requires new design

**Information about your Metabase Installation:**
local dev, `master`, 52df7fcaef74f6e068d670c886287e6b4f49a561, H2, Sample database

**Severity**
P1 performance.
On large instances with hundreds or even thousands of users, this can lead to performance penalties.

**Additional context**
This is a sister issue of https://github.com/metabase/metabase/issues/24330.

Related: https://github.com/metabase/metabase/issues/15339

### PR DESCRIPTION
**Pull request by ranquild**
Epic https://github.com/metabase/metabase/issues/28190
Fixes https://github.com/metabase/metabase/issues/28068

Fixes the performance issue with `SavedQuestionPicker`:
- Similar to models, display only collection subtrees that actually contain saved questions, instead of all of them
- `All personal collections` will be available only if there is at least one personal collection of another user that has a saved question (either within itself or child collections)
- Optimizes logic to check whether a collection contains questions

Before
Screenshot 2023-02-22 at 21 53 36

After
Screenshot 2023-02-22 at 21 54 57
Screenshot 2023-02-22 at 21 55 00

### CODE REVIEW

File: frontend/src/metabase/collections/utils.ts [hunk 1]
```diff
@@ -147,14 +148,14 @@ function isPersonalOrPersonalChild(
...
-  collectionMap: Record<CollectionId, Collection>,
+  collectionMap: Partial<Record<CollectionId, Collection>>,
 ) {
   if (isPersonalCollection(collection)) {
     return false;
   }
   const parentId = coerceCollectionId(collection.parent_id);
   const parentCollection = collectionMap[parentId];
-  const collections = Object.values(collectionMap);
+  const collections = Object.values(collectionMap).filter(isNotNull);
```
Comment (kulyk) [inline frontend/src/metabase/collections/utils.ts:158]: Woah, can we have null-ish values in `state.entities.collections`? Curios how is that possible?

File: frontend/src/metabase-types/store/entities.ts [hunk 2]
```diff
@@ -19,7 +19,7 @@ import {
 
 export interface EntitiesState {
   actions?: Record<WritebackActionId, WritebackAction>;
-  collections?: Record<CollectionId, Collection>;
+  collections?: Partial<Record<CollectionId, Collection>>;
```
Comment (kulyk) [inline frontend/src/metabase-types/store/entities.ts:22]: What does `Partial` solve here?

File: frontend/test/metabase/scenarios/question/new.cy.spec.js [hunk 3]
```diff
@@ -149,6 +149,29 @@ describe("scenarios > question > new", () => {
...
       });
     });
+
+    it("should be possible to create a question based on a question in another user personal collection", () => {
+      cy.signOut();
+      cy.signIn("nocollection");
+      startNewQuestion();
+      popover().findByText("Orders").click();
+      visualize();
+      saveQuestion("Personal question");
```
Comment (kulyk) [inline frontend/test/metabase/scenarios/question/new.cy.spec.js:159]: Should we maybe do this via an API request to speed up things?

**Review by kulyk — APPROVED** [review]

File: frontend/src/metabase-types/store/entities.ts (hunk 2 above)
Comment (WiNloSt) [reply frontend/src/metabase-types/store/entities.ts:22]: I believe you want to use `Record<CollectionId, Partial<Collection>>` instead?

This will ensure the state always looks something like this:
```js
{
  1: collection,
  2: collectionWithoutRootOrPersonal
}
```

But `Partial<Record<CollectionId, Collection>>` could give you:
```js
{
  1: undefined
  2: collection
}
```

unless I misread this.

Comment (kulyk) [reply frontend/src/metabase-types/store/entities.ts:22]: Gotcha, I think it might make sense to leave a comment about it

File: frontend/test/metabase/scenarios/question/new.cy.spec.js (hunk 3 above)
Comment (WiNloSt) [reply frontend/test/metabase/scenarios/question/new.cy.spec.js:159]: ➕

**Review by cdeweyx — APPROVED** [review]
