### PR TITLE
[streaming-response] Use HttpEndpoint.isOpen() instead of reading a byte from TCP socket

### LINKED ISSUE #46071: Intermittent (but frequent) "There was a problem displaying this chart."
**Describe the bug**
I am intermittently getting the message "There was a problem displaying this chart " across charts randomly. Its happens randomly on different charts. If I refresh, they might work, they might not. It might happen to a different chart. Who knows, it's completely random!

**Logs**
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/1486/dashcard/4762/card/5228/query 202 [ASYNC: completed] 4.2 s (25 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (120 total active threads) Queries in flight: 5 (0 queued); redshift DB 3 connections: 3/8 (0 threads blocked) {:metabase-user-id 1}
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 WARN metabase.server.middleware.log OST /api/dashboard/1486/dashcard/4760/card/5226/query 404 145.8 µs (0 DB calls) {:metabase-user-id 1} 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/1486/dashcard/4761/card/5227/query 202 [ASYNC: completed] 2.9 s (25 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (6 idle, 0 queued) (120 total active threads) Queries in flight: 3 (0 queued); redshift DB 3 connections: 5/8 (0 threads blocked) {:metabase-user-id 1}
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/1486/dashcard/4764/card/5230/query 202 [ASYNC: completed] 4.2 s (24 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (120 total active threads) Queries in flight: 4 (0 queued); redshift DB 3 connections: 1/8 (0 threads blocked) {:metabase-user-id 1}
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 WARN metabase.server.middleware.log OST /api/dashboard/pivot/1486/dashcard/4274/card/4966/query 404 123.1 µs (0 DB calls) {:metabase-user-id 1} 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 DEBUG metabase.server.middleware.log POST /api/dashboard/1486/dashcard/4763/card/5229/query 202 [ASYNC: completed] 4.2 s (25 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (120 total active threads) Queries in flight: 2 (0 queued); redshift DB 3 connections: 0/8 (0 threads blocked) {:metabase-user-id 1}
[f61dbcf7-3732-44cf-a710-0176a8d2d8a2] 2024-07-24T18:26:10+02:00 WARN metabase.server.middleware.log OST /api/dashboard/1486/dashcard/4768/card/5225/query 404 118.9 µs (0 DB calls) {:metabase-user-id 1} 
#metabase.util.i18n.UserLocalizedString{:format-string "API endpoint does not exist.", :args [], :pluralization-opts {}}

**Severity**
HIGH

**Metabase Diagnostic Info**

{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.219-208.866.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-15",
      "tag": "v0.50.13",
      "hash": "2086968"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

### PR DESCRIPTION
**Pull request by alexander-yakushev**
Should fix #46071.

## Context for posterity

Current implementation of HTTP request cancellation detection relied on reading a byte from the TCP socket and making decisions on what comes back. This causes problems when Keep-Alive is enabled for the request, and the TCP socket (connection) is reused by the client to send another request. If in the meantime the Metabase server continues producing data for the previous request, the cancellation detection loop can steal a few bytes from the connection corrupting the next request sent over that connection.

A proper test for this fix is possible to write but might be overspecific. It would look a bit like a test for something we shouldn't be doing in the first place:) Still, ping me if you want that test to appear, I'll get it done in a separate PR so that the bugfix is not delayed.

### CODE REVIEW

File: src/metabase/async/streaming_response.clj [hunk 1]
```diff
@@ -169,22 +169,14 @@
...
-        (let [buf        (ByteBuffer/allocate 1)
-              status     (.read channel buf)]
-          (log/tracef "Check cancelation status: .read returned %d" status)
-          (neg? status))
-        (do
-          (log-unexpected-transport! transport)
-          false)))
+    (let [endpoint (.. request getHttpChannel getEndPoint)
+          is-open  (.isOpen endpoint)]
+      (log/tracef "Check cancelation status: .osOpen returned %s" is-open)
```
Comment (piranha) [inline src/metabase/async/streaming_response.clj:178]:
```suggestion
      (log/tracef "Check cancelation status: .isOpen returned %s" is-open)
```

**Review by sansolovyov — APPROVED** [review]
