### PR TITLE
Make the number formatting, global or otherwise, apply to percentages in pie charts

### LINKED ISSUE #11394: Formatting not always respecting Global formatting
**Describe the bug**
There has been several questions/problems with how formatting is applied. Some of it could be documented better. But currently Global formatting is not applied unless the Field Type is `Creation/Cancellation/Deletion/Join timestamp`.
It's not specific to date/time, but also number formatting.

This means that Native/SQL questions always shows Default formatting (can be overruled by Question formatting).
Same goes for QB questions, where the Field Type isn't defined as `*** timestamp` (can be overruled by Question formatting).

Another trickery thing. When Global formatting is applied, and when seeing the column formatting in Data Model, but where Field Type is i.e. `No special type`, then it shows Default formatting.

These are the levels of formatting, as I understand - [documentation only lists 3](https://www.metabase.com/docs/latest/administration-guide/19-formatting-settings.html):
1. Default/fall-back (US-style generally, but this is at code-level)
2. Global: Admin > Settings > Formatting
3. Model: Admin > Data Model > (database) > (table) > (column) :gear: > Formatting
4. Question: visualization Settings > Data > (column) :gear: > Formatting
5. Card: hover dashboard card and click :gear: > Formatting

**To Reproduce**
1. Admin > Settings > Formatting > set to `2018-1-7` and `24h-style`
2. Admin > Data Model > Sample Dataset > Orders > Created At :gear: > set Field Type to `No special type`, and check Formatting side menu, which shows Default formatting
   1. Simple question > Sample Dataset > Orders, shows "Created At" with Default formatting (can be overruled by Model and Question formatting)
   2. Native question > Sample Dataset > `SELECT * FROM ORDERS`, shows Default formatting (can be overruled by Question formatting)
3. Revert Field Type to `Creation timestamp`, and check Formatting side menu, which shows Global formatting
   1. Simple question > Sample Dataset > Orders, shows "Created At" with Global formatting
   2. Native question > Sample Dataset > `SELECT * FROM ORDERS`, shows Default formatting (can be overruled by Question formatting)

**Expected behavior**
Always respect Global formatting.

**Information about your Metabase Installation:**
Metabase 0.33.6 and master on different backends and various browsers.

**Severity**
If you're not used to US-style formatting, then this is just as difficult to understand as feet/meters or Fahrenheit/Celsius.

**Additional context**
Related to #5859, #7447, #7494, #9079, #10787, #10856, #11398, #11426

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #12659: Global number formatting does not apply to percentages
**Describe the bug**
When setting in the admin a global number format different than the default (e.g. 100 000,00), the formatting is not applied to percentages of pie charts.

**To Reproduce**
1. Go to Admin > Formatting and change the separator style to non-default (e.g. 100 000,00)
2. Exit admin and create a new pie chart question, for example:
3. Table orders, metric = count of rows, group by = product category, viz = pie chart
4. The total number of order in the chart is correctly formatted (18 760) but not the percentages in the legend (21.2%) 

**Expected behavior**
The number format should also apply to percentages (e.g. should be 21,2%)

**Screenshots**
image

**Information about your Metabase Installation:**

Metabase version: v0.35.2

**Severity**
Low severity, only prevents from displaying metrics consistently and avoiding confusion of users

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to #12659.

Does not fix #11394 nor #12152.

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/PieChart.jsx [hunk 1]
```diff
@@ -288,6 +288,7 @@ export default class PieChart extends Component {
     const formatPercent = percent =>
       formatValue(percent, {
         column: cols[metricIndex],
+        number_separators: settings.column(cols[metricIndex]).number_separators,
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/visualizations/PieChart.jsx:291]:
```suggestion
        ...settings.column(cols[metricIndex]),
```

I think this change will work, but it's worth testing. `settings.column()`'s result should have `column` in it.

It's probably identical but might save us from a similar oversight in the future.

**Review by paulrosenzweig — APPROVED** [review]
Nicely done!

File: frontend/src/metabase/visualizations/visualizations/PieChart.jsx (hunk 1 above)
Comment (howonlee) [reply frontend/src/metabase/visualizations/visualizations/PieChart.jsx:291]: Oh, I tried this explicitly, it removed the percentage signs in the percent, I tried for a few hours to get it to work with the other column stuff and it does seem that I don't understand the precedence rules of the destructuring sugar to get it to actually work

Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/visualizations/PieChart.jsx:291]: Ah it looks like `settings.column()`'s result includes a `_numberFormatter` property which is taking precedence over the other settings. This will work, but I think leaving as-is is fine too.

```js
...settings.column(cols[metricIndex]),
_numberFormatter: undefined,
```

Comment (howonlee) [reply frontend/src/metabase/visualizations/visualizations/PieChart.jsx:291]: I feel like my WTF factor would be less with the explicit single thing, as opposed to using the sugar and then explicitly unsetting a thing
