### PR TITLE
Viz 1323 visualizer cant combine single series chart and breakout

### LINKED ISSUE #61133: Visualizer - can't combine single-series chart and breakout charts
### Describe the bug

In v55 it is no longer possible to combine a single-series chart with a multi-series one including a breakout, even if they otherwise have the exact same dimensions. 
This was working before.

### To Reproduce

Create these charts in Sample Database and try to combine them:
Image

### Expected behavior

This should still be supported.

### Logs

_No response_

### Information about your Metabase installation

```JSON
1.55.6
```

### Severity

P1 — customers depend on this, and existing merged charts can’t be updated anymore. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #61133
Closes [VIZ-1323: Visualizer - can't combine single-series chart and breakout charts](https://linear.app/metabase/issue/VIZ-1323/visualizer-cant-combine-single-series-chart-and-breakout-charts)

### Description

Loosens a bit the compatibility check when searching, so users can still add datasources they know will work.

### Demo

https://github.com/user-attachments/assets/2d12f8be-9115-4d35-85dc-2cda30e584e1

TODO: add tests once the design is validated.

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizer/components/DataImporter/DatasetsList/DatasetsList.tsx [hunk 1]
```diff
@@ -127,7 +120,7 @@ export function DatasetsList({
         models: ["card", "dataset", "metric"],
         include_dashboard_questions: true,
         include_metadata: true,
-        has_temporal_dimensions: timeDimensions.length > 0,
+        // has_temporal_dimensions: timeDimensions.length > 0,
```
Comment (alxnddr) [inline frontend/src/metabase/visualizer/components/DataImporter/DatasetsList/DatasetsList.tsx]: Can we drop this line?

File: frontend/src/metabase/visualizer/visualizations/cartesian.ts [hunk 2]
```diff
@@ -214,13 +214,15 @@ export function addDimensionColumnToCartesianChart(
   };
 }
 
+// TODO clean up the unused parameters
```
Comment (alxnddr) [inline frontend/src/metabase/visualizer/visualizations/cartesian.ts]: Would be nice to clean this up

**Review by alxnddr — APPROVED** [review]

**Comment by ixipixi** [comment]
Hey guys - I'm still unable to combine charts in 56.1 the way explained int he original issue. In v55 the questions would return in the search but you didn't have the "plus" option to add them. No, in v56, it doesn't return on search at all.
