### PR TITLE
Fix formatter support for field id or name col settings

### LINKED ISSUE #55066: Table metadata column settings break user column settings for tables in subscriptions
### Describe the bug

Configuring column specific settings in admin panel -> table metadata breaks table viz settings formatting in subscriptions

### To Reproduce

1. Create dashboard
2. Create new question from Orders, visualize as table
    a. Subtotal column, add prefix
    b. Created at column, change date style to "31 Jan, 2018"
3. Add question to dashboard and save
4. Admin panel -> table metadata -> orders
    a. Subtotal column -> settings -> formatting -> set "Display as" to "Text"
    b. Created at column -> settings -> formatting -> set "Date style" to "1/31/2018"
5. Send a subscription email
6. Notice that there is no prefix in subtotal cells, and the date style is not in "31 Jan, 2018" format

### Expected behavior

Column viz settings should work in rendered table in email subscriptions

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "h2"
    ],
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "tag": "vLOCAL_DEV",
      "hash": "06d1ba2ae111e66253209c01c244d6379acfc6dcb1911fa9ab6012cec9ce52e5"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.5+11-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.5+11-LTS",
    "os.name": "Mac OS X",
    "os.version": "15.3.2",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tsplude**
Resolves #55066 

See repro steps in the linked issue

- Table cell [formatters](https://github.com/metabase/metabase/blob/3e84a672336c09a5d76e9bc3d53383499351ea16/src/metabase/channel/render/body.clj#L143) are not building correctly because viz settings has multiple conflicting entries
- When the column settings in admin panel -> table metadata are changed, they are populated in the `:settings` metadata field on the columns in the result of the query from QP (*1)
- These also show up in the QP result `viz-settings` but using field ID references not column name references (*2)
- Now viz-settings has both sets of settings for the column but with different entries, one using column name and one using field ID
- We default to settings keyed by field ID and since they're not null we ignore the settings keyed by column name
<details>
<summary>(*1) Result of Admin panel -> table metadata -> sample database -> orders -> subtotal -> settings -> formatting -> Display as = Text</summary>
image
</details>
<details>
<summary>(*2) Viz settings</summary>
image
</details>

QUESTIONS
- [x] Is this the right fix? Should we be using field IDs in column metadata `:settings` ?
  - Huddled with Braden and confirmed field id keys for the "global" column metadata settings is correct, see [qp viz setting logic](https://github.com/metabase/metabase/blob/c43780e97f1e7c4eafd02a984709e64932684fda/src/metabase/query_processor/middleware/visualization_settings.clj#L15)
- [x] Is the merge in `query_processor.streaming.common/viz-settings-for-col` correct? This will override the settings keyed by field ID, which in the reproduction example is what we want, but maybe by accident?
  - Believe answer is yes after speaking with Braden, need to test column disambiguation though 

TODO
- [x] Write unit test for the `common/viz-settings-for-col` fix
- [x] Test that conflicting / duplicate column names are disambiguated when we are in here

### CODE REVIEW

File: test/metabase/formatter_test.clj [hunk 1]
```diff
@@ -11,14 +11,26 @@
...
+                                    {::mb.viz/column-settings
+                                     {{::mb.viz/field-id 1} {::mb.viz/view-as nil}
+                                      {::mb.viz/column-name "FOO"} viz}})
+        value)))
+
 (deftest number-formatting-test
   (let [value 12345.5432
-        fmt   (partial format value)]
+        fmt   (partial format value)
+        fmt2  (partial format-with-merged-settings value)]
```
Comment (bshepherdson) [inline test/metabase/formatter_test.clj:26]: This seems like a good place to use `doseq` to run each case below with all three permutations (just id, just name, and both).

File: test/metabase/formatter/datetime_test.clj [hunk 2]
```diff
@@ -101,68 +101,91 @@
...
-                                                                            :date_separator "-"}}]
-        (let [global-settings (m/map-vals mb.viz/db->norm-column-settings-entries
-                                          (public-settings/custom-formatting))]
-          (is (= "7-16-2020, 6:04 PM"
-                 (format-temporal-str
-                  "UTC"
-                  now
-                  {:effective_type :type/DateTime}
-                  {::mb.viz/global-column-settings global-settings}))))))))
+    (let [column {:field_ref [:field 1 nil] :name "created_at" :id 1 :effective_type :type/Date}]
```
Comment (tsplude) [inline test/metabase/formatter/datetime_test.clj:130]: This column def used for testing used to use `:field_ref [:column_name "created_at"]`. This actually breaks if the viz settings passed in have column settings that are only keyed by field ID since [field-id-or-name](https://github.com/metabase/metabase/blob/b6e957c05b155b660fa888a2060780280bbd3c8c/src/metabase/query_processor/streaming/common.clj#L200) resolves to "created_at" and no settings exist for either `{:field-id "created_at"}` or `{:column-name "created_at"}`

If you look at the first screenshot in the PR description, field_ref in the column defs coming out of QP are of the form `:field_ref [:field <id> nil]` so thats what I changed these tests to use.

Is this right? Do we have any up to date documentation on the types of field_refs we need to support?

Comment (tsplude) [reply test/metabase/formatter/datetime_test.clj:130]: See https://www.notion.so/metabase/Refs-in-Legacy-MBQL-1c469354c9018071a7d3e86227002fcb?pvs=4

> Legacy MBQL (including the `:field_ref` on column metadata) has four flavours of refs:
> 
> - `[:field 12 {...}]` giving the ID of a field in the user's data warehouse
> - `[:field "created_at" {...}]` using the name of the field
> - `[:aggregation 2]` indexing into the list of aggregations (0-based)
> - `[:expression "tax rate"]` using the name of an expression.

File: src/metabase/formatter.clj [hunk 3]
```diff
@@ -122,12 +122,15 @@
                                (streaming.common/global-type-settings col viz-settings)
                                (catch Exception _e
                                  (streaming.common/global-type-settings (dissoc col :base_type :effective_type) viz-settings)))
-        col-id               (or col-id (second field-ref))
+        ref-type             (first field-ref)
+        col-id-or-name       (or col-id (second field-ref))
```
Comment (noahmoss) [inline src/metabase/formatter.clj:126]: maybe @bshepherdson can confirm but there might be a metabase-lib way to extract these values from the field ref?

**Review by noahmoss — APPROVED** [review]
Stamping to unblock but I'm still nervous about any code that's reaching into field refs by position, would be good to double check that with the querying team

File: src/metabase/formatter.clj (hunk 3 above)
Comment (bshepherdson) [reply src/metabase/formatter.clj:126]: The query and field ref here are legacy MBQL, not the lib's PMBQL. I agree it's a code smell to be reaching into these structures in many hundreds of places in the codebase. But that ship has not just sailed, it's circumnavigated the globe, discovered a new continent, and wrecked on its shores.

So I think this is fine. All legacy refs have the form `[ref-type identifying-thing & maybe-more-stuff]`.

File: src/metabase/formatter/datetime.clj [hunk 4]
```diff
@@ -61,9 +61,9 @@
                               ;; and not have any metadata. Since we don't know the metadata, we can never
                               ;; match a key with metadata, even if we do have the correct name or id
                               (update-keys #(select-keys % [::mb.viz/field-id ::mb.viz/column-name])))]
-    (or (all-cols-settings {::mb.viz/field-id field-id-or-name})
-        (all-cols-settings {::mb.viz/column-name field-id-or-name})
-        (all-cols-settings {::mb.viz/column-name column-name}))))
+    (merge (all-cols-settings {::mb.viz/field-id field-id-or-name})
+           (all-cols-settings {::mb.viz/column-name field-id-or-name})
+           (all-cols-settings {::mb.viz/column-name column-name}))))
```
Comment (bshepherdson) [inline src/metabase/formatter/datetime.clj:66]: Should these latter two `::mb.viz/column-name` lookups be a nested `or`, like we discussed elsewhere?

**Review by bshepherdson — APPROVED** [review]
