### PR TITLE
Fix toggle button alignment

### LINKED ISSUE #22463: SSL toggle is aligned incorrectly
**Describe the bug**
SSL toggle is aligned incorrectly - might be a general problem with toggle component

**To Reproduce**
1. Go to Admin > Databases > Create new - SSL toggle is positioned incorrectly
image

Previous versions for context
image

**Information about your Metabase Installation:**
0.43.0 and master

### PR DESCRIPTION
**Pull request by ariya**
Fixes #22463.

To verify:
1. Settings, Admin Settings, Databases
2. Add database

### Before

image

### After

image

### CODE REVIEW

**Review by flamber — APPROVED** [review]
Looks good.
Off-topic, could you add a `<label>` around the "Remember me", so it's clickable?
image

File: frontend/src/metabase/components/form/FormField.jsx [hunk 1]
```diff
@@ -62,6 +62,7 @@ function FormField(props) {
     hidden = formField && (formField.hidden || formField.type === "hidden"),
     horizontal = formField &&
       (formField.horizontal || formField.type === "boolean"),
+    isToggle = formField && formField.type === "boolean",
```
Comment (kulyk) [inline frontend/src/metabase/components/form/FormField.jsx:65]: It seems it should just be a local variable, rather than a prop. If it's a prop, I'll be able to set `isToggle={true}` on any other input type and it'd be confusing

**Review by kulyk — APPROVED** [review]
🎉

**Comment by ariya** [comment]
> Off-topic, could you add a `<label>` around the "Remember me", so it's clickable?

Tackled in PR #22488.
