### PR TITLE
load analytics only when changed using a checksum

### LINKED ISSUE #38270: Stop trying to update the analytics content on every start up
### Describe the bug

Seems that we're trying to update the contents on every startup. How do I know? if you start Metabase several times over the same instance, you'll see that the step "Loading Analytics Content" takes some time of the initialization

### To Reproduce

1) set up Metabase 48 with a persistent database
2) then shut it down
3) start it again
4) see in the app db that are queries like
		    10 Query	UPDATE `report_card` SET `query_type` = 'query', `dataset_query` = '{\"database\":13371337,\"query\":{\"aggregation\":[[\"count\"]],\"breakout\":[[\"field\",185,{\"base-type\":\"type/DateTimeWithLocalTZ\",\"temporal-unit\":\"month\"}]],\"filter\":[\"=\",[\"field\",190,{\"base-type\":\"type/Text\"}],\"dashboard\"],\"joins\":[{\"alias\":\"Content - Entity Qualified\",\"condition\":[\"=\",[\"field\",189,{\"base-type\":\"type/Text\"}],[\"field\",73,{\"base-type\":\"type/Text\",\"join-alias\":\"Content - Entity Qualified\"}]],\"source-table\":\"card__3\",\"strategy\":\"left-join\"},{\"alias\":\"Group Members - User\",\"condition\":[\"=\",[\"field\",187,{\"base-type\":\"type/Integer\"}],[\"field\",125,{\"base-type\":\"type/Integer\",\"join-alias\":\"Group Members - User\"}]],\"source-table\":\"card__5\",\"strategy\":\"left-join\"}],\"source-table\":\"card__23\"},\"type\":\"query\"}', `display` = 'line', `visualization_settings` = '{\"column_settings\":null,\"graph.dimensions\":[\"timestamp\"],\"graph.metrics\":[\"count\"],\"graph.show_values\":true,\"table.cell_column\":\"model_id\",\"table.pivot_column\":\"end_timestamp\"}', `created_at` = '2023-08-17 21:55:45.764868', `updated_at` = NOW(6) WHERE `id` = 39

### Expected behavior

We shouldn't do that on every load

### Logs

_No response_

### Information about your Metabase installation

```JSON
v48
```

### Severity

P1ish?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by escherize**
resolves #38270

- over audit deserialization files

Extracts logic that decides to laod into `should-load-audit?` which checks the resource dir exists, `load-analytics-content` is turned on, and that the newly calculated checksum is different from the previously calculated checksum (calculated on startup each time).

Screenshot 2024-01-30 at 2 46 24 PM

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/audit_db.clj [hunk 1]
```diff
@@ -186,24 +186,53 @@
...
-                   (serialization.cmd/v2-load-internal! (str (instance-analytics-plugin-dir (plugins/plugins-dir)))
-                                                        {:backfill? false}
-                                                        :token-check? false))]
-      (if (not-empty (:errors report))
-        (log/info (str "Error Loading Analytics Content: " (pr-str report)))
-        (log/info (str "Loading Analytics Content Complete (" (count (:seen report)) ") entities loaded."))))
-    (when-let [audit-db (t2/select-one :model/Database :is_audit true)]
-      (adjust-audit-db-to-host! audit-db))))
+  (let [current-checksum (analytics-checksum)
+        last-checksum (last-analytics-checksum)]
```
Comment (noahmoss) [inline enterprise/backend/src/metabase_enterprise/audit_db.clj:215]: maybe move these into `should-load-audit?`?

File: enterprise/backend/test/metabase_enterprise/audit_db_test.clj [hunk 2]
```diff
@@ -129,3 +129,16 @@
...
+  (testing "no resource path => do not load"
+    (is (= (#'audit-db/should-load-audit? nil true 1 3) false)))
+  (testing "load-analytics-content false => do not load"
+    (is (= (#'audit-db/should-load-audit? nil false 3 5) false)))
+  (testing "resource path exists + load-analytics-content + checksums dont match  => load"
+    (is (= (#'audit-db/should-load-audit? #'audit-db/analytics-dir-resource true 1 3) true)))
+  (testing "checksums are the same => do not load"
+    (is (= (#'audit-db/should-load-audit? #'audit-db/analytics-dir-resource true 3 3) false)))
+  (testing
+      "resource path does not exist + load-analytics-content is false + checksums match  => do not load"
```
Comment (noahmoss) [inline enterprise/backend/test/metabase_enterprise/audit_db_test.clj:143]: nit: whitespace

File: enterprise/backend/src/metabase_enterprise/audit_db.clj [hunk 3]
```diff
@@ -186,24 +186,53 @@
   :audit      :never
   :doc        false)
 
+(defsetting last-analytics-checksum
+  "Whether or not we should load Metabase analytics content on startup. Defaults to true, but can be disabled via environment variable."
```
Comment (noahmoss) [inline enterprise/backend/src/metabase_enterprise/audit_db.clj:190]: nit: docstring out of date

**Review by noahmoss — APPROVED** [review]

File: enterprise/backend/test/metabase_enterprise/audit_db_test.clj [hunk 4]
```diff
@@ -129,3 +129,16 @@
...
+    (is (= (#'audit-db/should-load-audit? #'audit-db/analytics-dir-resource false 1 3) false))))
```
Comment (johnswanson) [inline enterprise/backend/test/metabase_enterprise/audit_db_test.clj:144]: Should this say "checksums do not match", or be `3 3` instead of `1 3`?

File: enterprise/backend/test/metabase_enterprise/audit_db_test.clj (hunk 2 above)
Comment (escherize) [reply enterprise/backend/test/metabase_enterprise/audit_db_test.clj:143]: This testing string was kinda long, so I broke it out

File: enterprise/backend/src/metabase_enterprise/audit_db.clj (hunk 1 above)
Comment (escherize) [reply enterprise/backend/src/metabase_enterprise/audit_db.clj:215]: I pulled this out to make it easier to test o:)

File: enterprise/backend/test/metabase_enterprise/audit_db_test.clj (hunk 4 above)
Comment (escherize) [reply enterprise/backend/test/metabase_enterprise/audit_db_test.clj:144]: yep!

File: enterprise/backend/src/metabase_enterprise/audit_db.clj (hunk 3 above)
Comment (escherize) [reply enterprise/backend/src/metabase_enterprise/audit_db.clj]: fixed
