### PR TITLE
fix empty-group-permissions-graph + api test

### LINKED ISSUE #29191: Group with no permissions causes error when saving permissions of another group
**Describe the bug**
Under certain circumstances, a permissions group with no access causes issues with changing other groups' permissions.

**Logs**
```
Cannot parse permissions graph because it is invalid: {:schema [:map [:groups [:map-of [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}] [:schema {:registry {"DataPerms" [:map [:native {:optional true} [:maybe [:enum :write :none :full :limited]]] [:schemas {:optional true} [:or [:enum :all :segmented :none :block :full :limited] [:map-of [:string {:decode/perm-graph #function[clojure.core/name]}] [:or [:keyword {:title "schema name"}] [:map-of [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}] [:or [:enum :all :segmented :none :full :limited] [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]]]]]]]]]}} [:map-of [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}] [:map [:data {:optional true} "DataPerms"] [:query {:optional true} "DataPerms"] [:download {:optional true} "DataPerms"] [:data-model {:optional true} "DataPerms"] [:details {:optional true} [:enum :yes :no]] [:execute {:optional true} [:enum :all :none]]]]]]]], :value {:groups {:1 {:1 {:download {:native "full", :schemas "full"}, :data {:native "none", :schemas {:PUBLIC {:1 "none", :2 "none", :3 "none", :4 "all", :5 "none", :6 "none", :7 "none", :8 "none"}}}}}, :2 {:1 {:data {:native "write", :schemas "all"}, :download {:native "full", :schemas "full"}, :data-model {:schemas "all"}, :details "yes"}}, :3 nil}, :revision 2, :sandboxes []}, :errors ({:path [:groups 0], :in [:groups :1], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :1} {:path [:groups 1 0 0], :in [:groups :1 :1], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :1} {:path [:groups 1 0 1 :data 0 :native 0], :in [:groups :1 :1 :data :native], :schema [:enum :write :none :full :limited], :value "none"} {:path [:groups 1 0 1 :data 0 :schemas 0], :in [:groups :1 :1 :data :schemas], :schema [:enum :all :segmented :none :block :full :limited], :value {:PUBLIC {:1 "none", :2 "none", :3 "none", :4 "all", :5 "none", :6 "none", :7 "none", :8 "none"}}} {:path [:groups 1 0 1 :data 0 :schemas 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC], :schema [:string {:decode/perm-graph #function[clojure.core/name]}], :value :PUBLIC} {:path [:groups 1 0 1 :data 0 :schemas 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC], :schema [:keyword {:title "schema name"}], :value {:1 "none", :2 "none", :3 "none", :4 "all", :5 "none", :6 "none", :7 "none", :8 "none"}} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :1], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :1} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :1], :schema [:enum :all :segmented :none :full :limited], :value "none"} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 1], :in [:groups :1 :1 :data :schemas :PUBLIC :1], :schema [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]], :value "none", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :2], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :2} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :2], :schema [:enum :all :segmented :none :full :limited], :value "none"} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 1], :in [:groups :1 :1 :data :schemas :PUBLIC :2], :schema [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]], :value "none", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :3], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :3} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :3], :schema [:enum :all :segmented :none :full :limited], :value "none"} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 1], :in [:groups :1 :1 :data :schemas :PUBLIC :3], :schema [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]], :value "none", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :4], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :4} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :4], :schema [:enum :all :segmented :none :full :limited], :value "all"} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 1], :in [:groups :1 :1 :data :schemas :PUBLIC :4], :schema [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]], :value "all", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :5], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :5} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :5], :schema [:enum :all :segmented :none :full :limited], :value "none"} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 1], :in [:groups :1 :1 :data :schemas :PUBLIC :5], :schema [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]], :value "none", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :6], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :6} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :6], :schema [:enum :all :segmented :none :full :limited], :value "none"} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 1], :in [:groups :1 :1 :data :schemas :PUBLIC :6], :schema [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]], :value "none", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :7], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :7} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :7], :schema [:enum :all :segmented :none :full :limited], :value "none"} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 1], :in [:groups :1 :1 :data :schemas :PUBLIC :7], :schema [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]], :value "none", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :8], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :8} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 0], :in [:groups :1 :1 :data :schemas :PUBLIC :8], :schema [:enum :all :segmented :none :full :limited], :value "none"} {:path [:groups 1 0 1 :data 0 :schemas 1 1 1 1 1], :in [:groups :1 :1 :data :schemas :PUBLIC :8], :schema [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]], :value "none", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :download 0 :native 0], :in [:groups :1 :1 :download :native], :schema [:enum :write :none :full :limited], :value "full"} {:path [:groups 1 0 1 :download 0 :schemas 0], :in [:groups :1 :1 :download :schemas], :schema [:enum :all :segmented :none :block :full :limited], :value "full"} {:path [:groups 1 0 1 :download 0 :schemas 1], :in [:groups :1 :1 :download :schemas], :schema [:map-of [:string {:decode/perm-graph #function[clojure.core/name]}] [:or [:keyword {:title "schema name"}] [:map-of [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}] [:or [:enum :all :segmented :none :full :limited] [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]]]]]], :value "full", :type :malli.core/invalid-type} {:path [:groups 0], :in [:groups :2], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :2} {:path [:groups 1 0 0], :in [:groups :2 :1], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :1} {:path [:groups 1 0 1 :data 0 :native 0], :in [:groups :2 :1 :data :native], :schema [:enum :write :none :full :limited], :value "write"} {:path [:groups 1 0 1 :data 0 :schemas 0], :in [:groups :2 :1 :data :schemas], :schema [:enum :all :segmented :none :block :full :limited], :value "all"} {:path [:groups 1 0 1 :data 0 :schemas 1], :in [:groups :2 :1 :data :schemas], :schema [:map-of [:string {:decode/perm-graph #function[clojure.core/name]}] [:or [:keyword {:title "schema name"}] [:map-of [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}] [:or [:enum :all :segmented :none :full :limited] [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]]]]]], :value "all", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :download 0 :native 0], :in [:groups :2 :1 :download :native], :schema [:enum :write :none :full :limited], :value "full"} {:path [:groups 1 0 1 :download 0 :schemas 0], :in [:groups :2 :1 :download :schemas], :schema [:enum :all :segmented :none :block :full :limited], :value "full"} {:path [:groups 1 0 1 :download 0 :schemas 1], :in [:groups :2 :1 :download :schemas], :schema [:map-of [:string {:decode/perm-graph #function[clojure.core/name]}] [:or [:keyword {:title "schema name"}] [:map-of [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}] [:or [:enum :all :segmented :none :full :limited] [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]]]]]], :value "full", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :data-model 0 :schemas 0], :in [:groups :2 :1 :data-model :schemas], :schema [:enum :all :segmented :none :block :full :limited], :value "all"} {:path [:groups 1 0 1 :data-model 0 :schemas 1], :in [:groups :2 :1 :data-model :schemas], :schema [:map-of [:string {:decode/perm-graph #function[clojure.core/name]}] [:or [:keyword {:title "schema name"}] [:map-of [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}] [:or [:enum :all :segmented :none :full :limited] [:map [:read {:optional true} [:enum :all :none]] [:query {:optional true} [:enum :all :none :segmented]]]]]]], :value "all", :type :malli.core/invalid-type} {:path [:groups 1 0 1 :details], :in [:groups :2 :1 :details], :schema [:enum :yes :no], :value "yes"} {:path [:groups 0], :in [:groups :3], :schema [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}], :value :3} {:path [:groups 1 0], :in [:groups :3], :schema [:map-of [:int {:decode/perm-graph #function[metabase.api.permission-graph/kw-int->int-decoder]}] [:map [:data {:optional true} "DataPerms"] [:query {:optional true} "DataPerms"] [:download {:optional true} "DataPerms"] [:data-model {:optional true} "DataPerms"] [:details {:optional true} [:enum :yes :no]] [:execute {:optional true} [:enum :all :none]]]], :value nil, :type :malli.core/invalid-type})}
```

**To Reproduce**
1. Start up a fresh EE instance with a valid enterprise token
2. Create a new permissions group
3. Change the data permissions for the new group from `No self service` to `Unrestricted` and save
4. Change the data permissions from the new group back to `No self service` and save
5. Change any data permissions for the All Users group and try to save. You should see a long Malli error.

**Information about your Metabase Installation:**
Current master

**Severity**
P1?

### PR DESCRIPTION
**Pull request by escherize**
resolves [#29191](https://github.com/metabase/metabase/issues/29191)

Group level permissions can be `null` on the group-id level, which indicates no self-service for all fields.

The schema was overly-restrictive, but has been adjusted to enable null group permission maps.

### CODE REVIEW

File: src/metabase/api/permissions.clj [hunk 1]
```diff
@@ -82,8 +81,9 @@
         (throw (ex-info (tru "Cannot parse permissions graph because it is invalid: {0}"
                              (pr-str explained))
                         {:status-code 400
-                         :error explained
-                         :humanized (me/humanize explained)}))))
+                         :error (str (me/humanize explained)
```
Comment (escherize) [inline src/metabase/api/permissions.clj:84]: This will put the shorter (readable) error front and center if there is an error with the shape of this data.

File: src/metabase/models/permissions.clj [hunk 2]
```diff
@@ -1322,7 +1322,7 @@
     (throw (ee-permissions-exception perm-type))))
 
 (mu/defn ^:private update-group-permissions!
-  [group-id :- pos-int? new-group-perms :- api.permission-graph/StrictDbGraph]
+  [group-id :- pos-int? new-group-perms :- [:maybe api.permission-graph/StrictDbGraph]]
```
Comment (escherize) [inline src/metabase/models/permissions.clj:1325]: Since the DB Graph shapes can be nil over the API, we need to accept nil DB Graphs here.

**Review by noahmoss — APPROVED** [review]

**Comment by noahmoss** [comment]
backport too?
