### PR TITLE
Do not cache all token check failures

### LINKED ISSUE #41654: Token activation error persists, even after connectivity is restored
### Describe the bug

If a license activation attempt fails because token-check.metabase.com is not reachable or anything else prevents the token check API to be called, subsequent activation attempts continue to fail with the same error, even after the connectivity is restored. 
The issue persists until Metabase is restarted.

### To Reproduce

1. Set up a new instance
2. Disable connectivity to the token-check API (I just turned off my wifi connection while running Metabase locally)
3. In Admin Settings / Licencing, enter a valid token, and click Activate
4. Activation will time out
5. Now restore the connectivity
6. Try to activate the same token again
7.(!) The same validation timeout error occurs. 
The validation error will persist until Metabase is restarted.

### Expected behavior

Validation should be successful once the connectivity is restored.

### Logs

2024-04-19 17:38:58,209 DEBUG middleware.log :: GET /api/setting 200 47.0 ms (15 DB calls) App DB connections: 1/7 Jetty threads: 6/50 (4 idle, 0 queued) (46 total active threads) Queries in flight: 0 (0 queued)
2024-04-19 17:38:58,250 WARN middleware.log :: GET /api/premium-features/token/status 404 1.5 ms (0 DB calls)
"Not found."
2024-04-19 17:39:04,645 ERROR public-settings.premium-features :: Error setting premium features token
clojure.lang.ExceptionInfo: Unable to validate token {:status-code 400, :error-details "Token validation timed out."}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.1.75-0-virt",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-16",
      "tag": "v1.49.6",
      "hash": "5abf130"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P2 - rare but confusing

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by johnswanson**
We want to cache token checks to avoid an issue where we repeatedly ask the store "hey, is this token valid?? is this token valid?? is this token valid??" for the same token.

However, transient errors can also occur. For example, maybe a network issue causes the HTTP request to fail entirely. In this case, if we cache the result, the user needs to restart metabase (or wait 5 minutes until the cache is cleared) before they can attempt to validate their token again.

This PR moves the cache logic deeper into the stack. We want to cache "successful" responses from the store API - cases where the store has told us categorically that the token is or is not valid. We don't want or need to cache other things that might happen. Maybe your token isn't the right length - we can recalculate that, it's ok. Maybe you get a 503 error from the Store - we should let you retry. Maybe your network is having issues and you can't contact the Store at all - again, we should let you retry.

~The one potential issue I see here is that if the store goes down temporarily, we'll massively increase the number of requests we send to the store, potentially making it harder to recover from an outage. If this is a concern, I can add a circuit breaker: if we repeatedly get errors back from the store, back off and stop making requests for a while.~

Edit: I added the following:

In the pathological case where the store goes down for >5 minutes, the
cache will expire and all instances everywhere will start repeatedly
making requests for token validation at once. This might make recovering
from an outage more difficult.

This adds a circuit breaker around the API request. If the call
repeatedly throws (5XX errors, socket timeouts, etc.) then we'll pause
for 30 seconds, during which time all calls to token validation will
immediately fail without making any request to the API.

After 30 seconds, we'll allow one request through to the API. If it
succeeds, we'll go back to normal operation. Otherwise, we'll wait
another 30 seconds.

Fixes #41654

### CODE REVIEW

File: src/metabase/public_settings/premium_features.clj [hunk 1]
```diff
@@ -194,28 +214,11 @@
...
-  "TTL-memoized version of `fetch-token-status*`. Caches API responses for 5 minutes. This is important to avoid making
-  too many API calls to the Store, which will throttle us if we make too many requests; putting in a bad token could
-  otherwise put us in a state where `valid-token->features*` made API calls over and over, never itself getting cached
-  because checks failed."
-  ;; don't blast the token status check API with requests if this gets called a bunch of times all at once -- wait for
-  ;; the first request to finish
-  (let [lock (Object.)
-        f    (memoize/ttl
-              (fn [token]
-                ;; this is a sanity check to make sure we can actually get the active user count BEFORE we try to call
```
Comment (johnswanson) [inline src/metabase/public_settings/premium_features.clj:206]: Note: I removed this because I moved caching deeper - it only wraps the HTTP request itself now. Therefore, a failure to get the active users count will no longer be cached.

File: src/metabase/public_settings/premium_features.clj [hunk 2]
```diff
@@ -110,18 +110,38 @@
...
+         :else (throw (ex-info "An unknown error occurred when validating token." {:status status
+                                                                                   :body body})))))
+
+   :ttl/threshold (u/minutes->ms 5)))
 
 (defn- fetch-token-and-parse-body
   [token base-url site-uuid]
-  (let [fut    (future (fetch-token-and-parse-body* token base-url site-uuid))
+  (let [active-user-count (cached-active-users-count)
+        fut    (future (fetch-token-and-parse-body* token base-url site-uuid active-user-count))
```
Comment (noahmoss) [inline src/metabase/public_settings/premium_features.clj:144]:
```suggestion
  (let [active-user-count (cached-active-users-count)
        fut (future (fetch-token-and-parse-body* token base-url site-uuid active-user-count))
```

**Review by noahmoss — APPROVED** [review]

**Review by noahmoss — APPROVED** [review]
Circuit breaker lgtm!
