### PR TITLE
Show only valid linked filters in dashboards

### LINKED ISSUE #14595: Linked Filters should warn or not allow linking unless it will work
**Describe the bug**
It's currently possible to create a Linked Filter, which has no effect.

Workaround: If using SQL, then make sure that both filters are Field Filter.

**To Reproduce**
1. Native question > Sample Dataset - make single_date a Date filter, and field_filter a Field Filter of Products.Category
```
SELECT * FROM PRODUCTS WHERE 1=1
[[AND DATE(CREATED_AT)={{single_date}}]]
[[AND {{field_filter}}]]
```
2. Add to dashboard, create a single date filter and category filter and connect to the card, and set category filter as linked to single date filter:
image
3. Save dashboard, and set single date filter to 2019-04-11, which then would expect category filter to only show "Doohickey":
image

**Expected behavior**
While it's possible to click the name of the linked filter in the sidebar, which will show how the linking will be done, that's not obvious that those are clickable, and the warning should probably always be shown, when the linked filter has no effect.
image

**Information about your Metabase Installation:**
Tested 0.37.0 thru 0.37.8

**Additional context**
Another interesting part of this, is that it's getting all the dropdown options for category filter in `param_values` from the `/api/dashboard/:id` request, which is just like it used to be in pre-0.37 instead of the behavior as noted in #13832

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/14595

After this change, only parameters that can be linked to the current parameter are allowed to be linked in parameter settings.

How to verify:
- New -> Question -> Products -> Save as Products
- New -> Question -> Orders -> Save as Orders
- New -> Question -> Invoices -> Save as Invoices
- Add all of these questions to a dashboard, with a category parameter linked to each (e.g. Category, Vendor, Plan)
- Open parameter settings for each parameter. As there is no link between Orders+Products and Invoices, `Plan` will be in the inactive section.

Screenshot 2025-06-09 at 14 37 09

### CODE REVIEW

**Comment by mazameli** [comment]
Ideally the text in these two areas would be styled the same (their line-heights at least are different), but not a deal-breaker: 
image

File: frontend/src/metabase/parameters/components/ParameterLinkedFilters/ParameterLinkedFilters.tsx [hunk 1]
```diff
@@ -79,237 +104,276 @@ function Content({
...
-  );
-
   return (
-    <div>
-      <SectionMessage>
+    <Stack gap="lg">
+      <Text lh="1.25rem">
         {jt`If you toggle on one of these dashboard filters, selecting a value for that filter will limit the available choices for ${(
-          <em key="text">{t`this`}</em>
+          <Box key="text" component="em" mr="xs">{t`this`}</Box>
```
Comment (mazameli) [inline frontend/src/metabase/parameters/components/ParameterLinkedFilters/ParameterLinkedFilters.tsx]: I think we're probably overdoing it here, and I don't know that this will translate well — though I appreciate the attention to detail! I think we'd be fine with `<strong>` text.

**Comment by mazameli** [comment]
Two relatively minor comments — otherwise seems good to me.

File: frontend/src/metabase/parameters/components/ParameterLinkedFilters/ParameterLinkedFilters.tsx (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/parameters/components/ParameterLinkedFilters/ParameterLinkedFilters.tsx]: @mazameli fixed both issues, thanks!

**Review by mazameli — APPROVED** [review]

**Review by romeovs — APPROVED** [review]
