### PR TITLE
Fix - Resize handle misplaced in Notebook view

### LINKED ISSUE #53817: Resize handle misplaced in Notebook view
### Describe the bug

The resize handle is at the top of the viewport, it should be between the query editor and the preview table.

Image

### To Reproduce

1. Create a new model by using the notebook editor
2. Notice the resize handle at the top of the screen, right below the header bar

### Expected behavior

The resize handle should be between the query editor and the table

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "druid",
      "h2"
    ],
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-02-14",
      "src_hash": "416f109246d9ae9fce955b6b0edd1b12d022d354",
      "tag": "v0.53.2-SNAPSHOT",
      "hash": "c615e19"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "21.0.5+9-LTS-239",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "21.0.5",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "21.0.5+9-LTS-239",
    "os.name": "Mac OS X",
    "os.version": "15.2",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  }
}
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #53817

### Description

Caused by Mantine 7 upgrade (that's why no repro).

### Demo

[before](https://github.com/user-attachments/assets/8631851b-3a41-44b8-b46a-836a7227fa00) & [after](https://github.com/user-attachments/assets/1e4334f4-7f1c-42c7-962f-d3d60f5fda5a)

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/DatasetNotebook.jsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ const Handle = forwardRef(function Handle(props, ref) {
       w="100%"
       h="sm"
       pos="absolute"
-      bottom={`-${rem(4)}`}
+      bottom={rem(-4)}
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/DatasetNotebook.jsx:35]: `rem` function now outputs `calc` expression, so the style looked like this:
image
`-calc` did not work.

File: frontend/src/metabase/querying/metrics/components/MetricEditor/MetricEditorBody/ResizableBoxHandle/ResizableBoxHandle.tsx [hunk 2]
```diff
@@ -18,7 +18,7 @@ export const ResizableBoxHandle = forwardRef(function ResizableBoxHandle(
       w="100%"
       h="sm"
       pos="absolute"
-      bottom={`-${rem(4)}`}
+      bottom={rem(-4)}
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/metrics/components/MetricEditor/MetricEditorBody/ResizableBoxHandle/ResizableBoxHandle.tsx:21]: I found only 2 usages, I also checked the `em` function.

**Review by romeovs — APPROVED** [review]
