### PR TITLE
Fix - `useIsTruncated` gives incorrect results

### LINKED ISSUE #45358: `useIsTruncated` gives incorrect results
### Describe the bug

The current [`getIsTruncated`](https://github.com/metabase/metabase/blob/54c1e07/frontend/src/metabase/hooks/use-is-truncated.ts#L41-L46) implementation uses `clientHeight`/`clientWidth`/`scrollHeight`/`scrollWidth`:
- these properties are integers and so they lose precision - it means they don't account for cases where 0px < difference < 1px
- setting `width` on an element may prevent it from resizing when ellipsis is applied, so comparing the aforementioned properties won't give any useful information

Background: [Slack thread](https://metaboat.slack.com/archives/C052LBPDAF3/p1720176721037599?thread_ts=1720096231.281389&cid=C052LBPDAF3)

### To Reproduce

https://jsfiddle.net/8b14pv96/1/

-----

1. New question > Orders
2. Add breakout "Created At" - "Month of year"
3. Click to edit breakout
4. Hover over truncated "by month of year"

There should be a tooltip.

### Information about your Metabase installation

master, 4db6ede44af77f1abce3186718400ddad232ace4

### Severity

P3

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #45358

Previous attempt: #45347

### Description

The current [`getIsTruncated`](https://github.com/metabase/metabase/blob/54c1e07/frontend/src/metabase/hooks/use-is-truncated.ts#L41-L46) implementation uses `clientHeight`/`clientWidth`/`scrollHeight`/`scrollWidth`:
- these properties are integers and so they lose precision - it means they don't account for cases where 0px < difference < 1px (where "difference" means the difference between ellipsis being applied and not)
- setting `width` on an element may prevent it from resizing when ellipsis is applied, so comparing the aforementioned properties won't give any useful information

Credits to @ranquild for [the idea](https://metaboat.slack.com/archives/C0645JP1W81/p1721052584800439?thread_ts=1721031248.290819&cid=C0645JP1W81) :1st_place_medal: 

### How to verify

CI is green.

1. New question > Orders
2. Add breakout "Created At" - "Month of year"
3. Click to edit breakout
4. Hover over truncated "by month of year"

There should be a tooltip.

### CODE REVIEW

File: frontend/src/metabase/browse/components/CollectionBreadcrumbsWithTooltip.tsx [hunk 1]
```diff
@@ -39,9 +39,7 @@ export const CollectionBreadcrumbsWithTooltip = ({
     : collections;
   const justOneShown = shownCollections.length === 1;
 
-  const { areAnyTruncated, ref } = useAreAnyTruncated<HTMLDivElement>({
-    tolerance: 1,
```
Comment (kamilmielnik) [inline frontend/src/metabase/browse/components/CollectionBreadcrumbsWithTooltip.tsx:43]: `tolerance` is no longer needed

File: frontend/src/metabase/hooks/use-is-truncated.ts [hunk 2]
```diff
@@ -33,21 +30,24 @@ export const useIsTruncated = <E extends Element>({
...
       resizeObserver.unsubscribe(element, handleResize);
     };
-  }, [disabled, tolerance]);
+  }, [disabled]);
 
   return { isTruncated, ref };
 };
 
-const getIsTruncated = (element: Element, tolerance: number): boolean => {
+const getIsTruncated = (element: Element): boolean => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/hooks/use-is-truncated.ts:38]: This is the function that got fixed

**Review by ranquild — APPROVED** [review]
