### PR TITLE
Do not count empty lines and duplicates in action option editor

### LINKED ISSUE #29652: "Custom options" list for custom actions accepts newline as an option
**Describe the bug**
One can add multiple newline characters to the "custom options" in custom actions and they'd all be accepted. This leads to certain errors.

**To Reproduce**
_Create a custom `invoices` action [following the official documentation example](https://www.metabase.com/docs/latest/actions/custom.html)_
1. Click on the ellipsis menu next to an action name and then click on "Edit"
2. Set the "Payment" field type to Number
3. Click on the "cog" icon and select a "dropdown" as an option
4. Then click on the "change options" icon next to it to be able to enter custom options
image
5. Type in "1{enter}2{enter}{enter}{enter}{enter}"
image
6. Click "Save" (it will happily accept)
7. Click on the "Payment" **preview** dropdown modal and see that each newline was accepted as an option, which makes them all appear selected at once

> **Note**
> - Number field type will replace `newline` with zero `0`
> - Text field type will replace `newline` with an empty string

**Expected behavior**
This is a question for the product team, but I'd probably expect the (1) newline to be ignored and (2) all duplicates to be ignored

**Information about your Metabase Installation:**
Metabase `x.46.0`

**Severity**
P2

**Additional context**
- The same behavior applies to "Inline select"
- **Possibly a separate issue**, but there is no restriction that options must be unique

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/29652

### Description

Option editor filters out duplicates and empty lines now.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New model -> actions -> create new action
2. put a code like `select * from products where order_id == {{param}};`
3. on the right hand you have Action Parameter, find `param` there, click cog icon, choose `dropdown`
4. save -> click on the icon left to cog. paste there values with duplicates and empty lines
e.g

```
premium
basic
business

premium

```

after clicking "save", you should be able co click on input below "appearance" section and see only `premium, basic, business` values

### Demo

TBA

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx [hunk 1]
```diff
@@ -16,22 +16,36 @@ import {
...
 function getValidationError(options: FieldValueOptions, fieldType: FieldType) {
-  if (fieldType === "number") {
-    const isValid = options.every(option => !Number.isNaN(option));
-    return isValid ? undefined : t`Invalid number format`;
+  if (fieldType !== "number") {
+    return;
   }
-  return;
+
+  const isValid = options.every(option => !Number.isNaN(option));
```
Comment (kamilmielnik) [inline frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:46]: I know this code is just moved but it got my attention.
I believe the original intention was to check `isValid = options.every(isNumber)`, but:

```js
getValidationError([5], "number") // undefined - as expected
getValidationError([5, "5", "definitely-not-a-number", Symbol(), {}, []], 'number') // undefined - not expected
```

I suggest to fix it and add tests for that function (also extract it to utils).

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx [hunk 2]
```diff
@@ -16,22 +16,36 @@ import {
 } from "./OptionEditor.styled";
 
 const optionsToText = (options: FieldValueOptions) => options.join("\n");
-const textToOptions = (text: string): FieldValueOptions =>
-  text.split("\n").map(option => option.trim());
+const textToOptions = (text: string): FieldValueOptions => {
+  const options = text
+    .trim()
```
Comment (kamilmielnik) [inline frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:21]: This trim should not be necessary if we're going to trim every option afterwards

**Review by kamilmielnik — COMMENTED** [review]
Fix looks good :+1: 

I suggest to create dedicated test suite for `testToOptions`, cover the `trim()` part with tests, fix `getValidationError`, and cover it with tests as well.

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx (hunk 2 above)
Comment (oisincoveney) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:21]: It looks like the `Boolean` would be more important than the trim here - I played around with a test string and it looks like we can get rid of the first `trim` call as long as we filter out the empty (falsy) strings at the end
image

**Review by oisincoveney — COMMENTED** [review]
Tested locally on this branch and compared against master, and it works 😄 I think Kamil makes some good points about unit testing the functions really quickly, should just be some string manipulation tests and should be good

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx (hunk 1 above)
Comment (oisincoveney) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:46]: @kamilmielnik Another thing going on here is that we're using `Number.isNaN` vs `isNaN` which seem to be very different functions despite the similar names (https://stackoverflow.com/questions/33164725/confusion-between-isnan-and-number-isnan-in-javascript)

For example:
image

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx [hunk 3]
```diff
@@ -16,22 +16,36 @@ import {
 } from "./OptionEditor.styled";
 
 const optionsToText = (options: FieldValueOptions) => options.join("\n");
-const textToOptions = (text: string): FieldValueOptions =>
-  text.split("\n").map(option => option.trim());
+const textToOptions = (text: string): FieldValueOptions => {
```
[the remark this answers is not in the document]
Comment (uladzimirdev) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:19]: I don't think it makes sense to be honest as we want to have component tested and this function is not exported. Consider it as the implementation details

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx (hunk 2 above)
Comment (uladzimirdev) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:21]: trim solves the different problem - it drops all the empty spaces which would be considered as new lines and passed through the filter - it's not that optimal (I know we're not talking about perf for 5 lines, but anyway)

image

I'd keep trim

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:46]: @kamilmielnik you're right, but if you check `transformOptionsIfNeeded` method which we call just before `getValidationError`, you'll see that we converted all the options to Number type, so values are either numbers or `NaN`

so it's more or less correct 
image

Comment (uladzimirdev) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:46]: two methods could be merged together for sure

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.unit.spec.tsx [hunk 4]
```diff
@@ -103,5 +103,31 @@ describe("OptionEditor", () => {
...
       expect(onChange).toHaveBeenCalledWith([1, 2]);
     });
+
+    it("should omit empty lines and duplicates", async () => {
+      const { input, saveButton, onChange } = await baseSetup({
+        fieldType: "number",
+        options: [],
+      });
+
+      userEvent.type(input, "1\n2\n\n2\n\n1\n\n");
```
[the remark this answers is not in the document]
Comment (uladzimirdev) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.unit.spec.tsx:117]: added a test for the helper function

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (uladzimirdev) [reply frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx]: added a test as such function might be useful in other similar places

**Review by kamilmielnik — APPROVED** [review]
:+1:
