### PR TITLE
Dashboard move confirmation

### LINKED ISSUE #7697: Moving a dashboard or saved question should provide feedback when complete
Currently when you move a dashboard or question into a different collection you are redirected back to the detail for either type with no confirmation the thing you did worked. We should reuse our toasts here.

### LINKED ISSUE #7967: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
I have just installed the Java SDK 10.1 and then started up the **metabase.jar** with the following

```
java -jar metabase.jar
```

I have tried to add an MSSQL database, but keep getting the following error:
**java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter**

What's the problem here? I don't know much about Java. Am I needing to install something or configure something? Or is this a bug?

### PR DESCRIPTION
**Pull request by kdoh**
Uses our toasts to let a user know their move occurred.

- [x] Dashboards
- [x] Toast width

Resolves #7697

### CODE REVIEW

**Comment by mazameli** [comment]
Looks good! We'll want to do this to saved questions, too, once entity menus are implemented on those such that the Move action is in a question's edit menu.

File: frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx [hunk 1]
```diff
@@ -2,15 +2,27 @@ import React from "react";
...
 
 import CollectionListLoader from "metabase/containers/CollectionListLoader";
 
+const mapDispatchToProps = {
+  addUndo,
+  createUndo,
+};
+
 @withRouter
+@connect(() => ({}), mapDispatchToProps)
```
Comment (tlrobinson) [inline frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx]: You can pass `null` instead of `() => ({})`

File: frontend/src/metabase/containers/UndoListing.css [hunk 2]
```diff
@@ -9,7 +9,6 @@
   composes: bordered rounded shadowed from "style";
   composes: relative from "style";
   composes: flex align-center from "style";
-  width: 320px;
```
Comment (tlrobinson) [inline frontend/src/metabase/containers/UndoListing.css]: Where do undos get their size now?

File: frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx [hunk 3]
```diff
@@ -23,11 +35,33 @@ class DashboardMoveModal extends React.Component {
...
     try {
       await DashboardApi.update({
         id: this.props.params.dashboardId,
         collection_id: this.state.selectedCollection.id,
       });
+      addUndo(
+        createUndo({
+          type: "dashboard-move-confirm",
+          message: () => (
+            <Flex align="center">
```
Comment (tlrobinson) [inline frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx]: It might be nice to pull this out into a component then do `message: () => <DashbaordMoveConfirm collection={selectedCollection} />`

File: frontend/src/metabase/containers/UndoListing.css (hunk 2 above)
Comment (kdoh) [reply frontend/src/metabase/containers/UndoListing.css]: It should just be based on their content now. Figured that's the better gauge / place to trim things rather than setting the same width globally.

File: frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx (hunk 3 above)
Comment (kdoh) [reply frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx]: Yeah I'll do that. One thing I've found is it's kinda arcane to create these. Knowing to do `addUndo(createUndo(...))` took me a little while to grok initially even though I know it now after making a few of these over the past few months. Ideally it'd be nice to have a `<Toast message={...} {...otherRelevantProps} />` form and an easier way to trigger it. I suppose we could just start with `genToast(message)` or something that uses both under the hood since there should be a fairly limited surface are on what these look like and what they can do.

Comment (tlrobinson) [reply frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx]: Yeah we could definitely make it easier by abstracting away the Redux stuff, though I don't think it makes a lot of sense to have a declarative style `<Toast ... />` component that requires calling a method on a ref or whatever (like we have with the `*WithTrigger` components)

Maybe a `withToaster` HoC...

```javascript
@withToaster
class MyComponent extends React.Component {
  render() {
    return (
      <button
        onClick={() => this.props.toast(<div>my toast</div>)}
      >
        Toast!
      </button>
    );
  }
}
```

**Comment by kdoh** [comment]
@tlrobinson Made the changes you requested. Started in on some potential Toast changes in #7755.

File: frontend/src/metabase/containers/UndoListing.css (hunk 2 above)
Comment (tlrobinson) [reply frontend/src/metabase/containers/UndoListing.css]: That might look weird if we have multiple toasts on screen with different sizes, but that's a bit of an edge case. Maybe a `min-width` at least?

**Review by tlrobinson — APPROVED** [review]
