### PR TITLE
Use actual metadata in a Notebook in Embedding SDK/Embed JS

### LINKED ISSUE #66610: No fields to join when a table doesn't have a FK set up - EmbedJS exploration embed
### Describe the bug

When there's no relation between tables, at the Table Metadata layer, you can't join between tables when using EmbedJS exploration. 
Image

### To Reproduce

1. Run 57.5
3. Settings > Embedding > Modular > New embed > Exploration
4. Create a GUI question from Analytics Events table from the Sample database
5. Try to join with Invoices or a table that Analtyics Events has no FK set up, no suggestion will show up

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
- v1.57.5
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
closes #66610
Use actual metadata in a Notebook in Embedding SDK/Embed JS

This fixes https://linear.app/metabase/issue/EMB-1102/no-fields-to-join-when-a-table-doesnt-have-a-fk-set-up-embedjs

Original issue:

> When there's no relation between tables, at the Table Metadata layer, you can't join between tables when using EmbedJS exploration.

To Reproduce bug: 
- Run 57.5
- Settings > Embedding > Modular > New embed > Exploration
- Create a GUI question from Accounts table from the Sample database
- Try to join with the Analytics Events table, no suggestion will show up

To validate bug:
- Settings > Embedding > Modular > New embed > Exploration
- Create a GUI question from Accounts table from the Sample database
- Try to join with the Analytics Events table, columns to select should be shown

The fix:
We work wrong with Question in SDK, we store the whole question in a state, though a question should be stored, instead a card or metadata should be stored, and a question composed from it in places where it should be used.
Such a refactoring is a complex task, so the current fix ensures that we use the latest `metadata` that is feched deeply inside the Notebook Editor for a joined table.

### CODE REVIEW

File: frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/components/Editor.tsx [hunk 1]
```diff
@@ -40,8 +41,22 @@ export const Editor = ({
...
+
+  const metadata = useSelector(getMetadata);
+
+  const question = useMemo(() => {
+    if (!rawQuestion) {
+      return rawQuestion;
+    }
+
+    return new Question(rawQuestion?.card(), metadata);
+  }, [rawQuestion, metadata]);
```
Comment (sanex3339) [inline frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/components/Editor.tsx:59]: As I mentioned in the description, this is a fast way to fix it, but the proper way requires an overhaul of the SDK and how we work with a question.

**Review by ranquild — APPROVED** [review]

File: frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/components/Editor.tsx (hunk 1 above)
Comment (WiNloSt) [reply frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/components/Editor.tsx:59]: Can you add todo comment saying this? This is great info that shouldn't be lost.
e.g. something along this line. And [about the date format](https://metaboat.slack.com/archives/C010L1Z4F9S/p1762540282888169).
```ts
// TODO: (Timofei 2025-12-25) This is a fast way to fix it, but the proper way requires an overhaul of the SDK and how we work with a question.
const question = useMemo(...)
```

**Review by WiNloSt — APPROVED** [review]
Tested. Works as described.
