### PR TITLE
Fix click-and-drag filtering in dashboards for firefox

### LINKED ISSUE #24912: Click-and-Drag filtering in dashboards has an offset if card is not touching the left wall
The amount of offset equals the distance of the card from the left wall.

mb_dynamic_issue

v .44.1

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/24912

How to test:
- Follow the steps from the issue in **Firefox**
- You should get the correct filtering range while and after dragging

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/graph/brush.js [hunk 1]
```diff
@@ -20,6 +20,11 @@ export function initBrush(parent, child, onBrushChange, onBrushEnd) {
   // the last updated range when brushing
   let range = null;
 
+  // remove deprecated createSVGPoint to fix d3.mouse firefox bug (metabase#24912)
+  if (SVGSVGElement.prototype.createSVGPoint) {
+    SVGSVGElement.prototype.createSVGPoint = undefined;
+  }
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/lib/graph/brush.js:26]: nit: seeing an if block makes me think that this code would behave differently when there's no `createSVGPoint`, but what essentially we want to do here is to remove `createSVGPoint` entirely.

What it ends up behaving is that we want to make `createSVGPoint` `undefined` and if there's no `createSVGPoint` in the first place it will also be `undefined`, so I think it's more concise to drop the if statement since they're equivalent. What do you think?

```suggestion
  SVGSVGElement.prototype.createSVGPoint = undefined;
```

**Review by WiNloSt — APPROVED** [review]
This fix works great for me 🎉

File: frontend/src/metabase/visualizations/lib/graph/brush.js (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/visualizations/lib/graph/brush.js:26]: It's not equivalent. Changing a `prototype`, even just setting `undefined` to a not-existing property causes some performance issues. That's why it's better to check if we actually need to do this (we don't need for Chrome and Safari).
