### PR TITLE
Fix card loading state in different tabs when parameters change

### LINKED ISSUE #33767: We're not signaling when a card is loading if you change the filters on a dashboard and switch tabs
### Describe the bug

When you have a loaded dashboard and apply a filter, if you have a card in another tab that is connected to the same filter, the  card in another tab being filtered doesn't signal loading and, depending on the time, it may result in confusing results. 

### To Reproduce

1. Build a beautiful dashboard full of reports and complex questions and 2 tabs
2. Add filters to the dashboard and connect cards to it, in both tabs. I used the Orders table for almost every report to connect to filters, and in the video, I put the same card on both tabs to visually see the bug. 
3. Apply a filter in tab 1. When it finishes loading, change to tab 2. As filters are currently global (not tab-specific), they will apply to the cards in the new tab as well. 
4. See that there is no loading signal

For a more visual impact, in the following video I added the same cards that should be changed to the two tabs. The card in Tab 1 took almost 10 seconds without a loading signal. It's all Sample Database information.

https://github.com/metabase/metabase/assets/132273646/27581390-22c2-42b9-be8f-7af72c5b8b7a

### Expected behavior

The loading signal on cards affected by the filter should be there

### Logs

_No response_

### Information about your Metabase installation

```JSON
v1.47.0
```

### Severity

It can show misleading information.

### PR DESCRIPTION
**Pull request by oleggromov**
Fixes https://github.com/metabase/metabase/issues/33767

## Description
Unlike https://github.com/metabase/metabase/pull/36910, fixes the issue by reacting to change in _parameters_ in `fetchCardData`, which is the correct way to fix it.

### Before
https://github.com/metabase/metabase/assets/2196347/4180acc8-83f2-4074-8228-87f95a50814b 

### After

https://github.com/metabase/metabase/assets/2196347/1680c2b2-f39b-430e-9c9d-8a3dc55500ba

### CODE REVIEW

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 1]
```diff
@@ -345,7 +345,16 @@ export const fetchCardData = createThunkAction(
 
       cancelFetchCardData(card.id, dashcard.id);
 
-      if (clearCache) {
+      // When dashcard parameters change, we need to clean previous (stale)
+      // state so that the loader spinner shows as expected (#33767)
+      const hasParametersChanged =
+        !lastResult ||
```
Comment (oleggromov) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:351]: @alxnddr do you think it should be this or `lastResult && equals(...)`?

File: e2e/test/scenarios/dashboard/tabs.cy.spec.js [hunk 2]
```diff
@@ -410,3 +467,19 @@ describeWithSnowplow("scenarios > dashboard > tabs", () => {
...
+
+/**
+ * When you need to postpone a response (to check for loading spinners or alike),
+ * use this:
+ *
+ * `cy.intercept('POST', path, delayResponse(1000)).as('delayed')`
+ *
+ * `cy.wait('@delayed')` - you'll have 1000 ms until this resolves
+ */
+function delayResponse(delayMs) {
```
Comment (oleggromov) [inline e2e/test/scenarios/dashboard/tabs.cy.spec.js:479]: As discussed with @nemanjaglumac, we don't extract this as a global helper until needed by some other test.

File: e2e/test/scenarios/dashboard/tabs.cy.spec.js [hunk 3]
```diff
@@ -351,6 +354,60 @@ describe("scenarios > dashboard > tabs", () => {
...
+    });
+
+    // Auto-connection happens here
+    selectDashboardFilter(getDashboardCard(0), "Created At");
+    saveDashboard();
+
+    cy.intercept(
+      "POST",
+      "/api/dashboard/*/dashcard/*/card/*/query",
+      delayResponse(500),
```
Comment (oleggromov) [inline e2e/test/scenarios/dashboard/tabs.cy.spec.js:387]: This is needed so that the test is deterministic and won't flake because of too fast responses.

File: e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js [hunk 4]
```diff
@@ -215,7 +215,7 @@ describe("scenarios > dashboard > dashboard cards > click behavior", () => {
       cy.get("aside").findByText("No available targets").should("exist");
       cy.get("aside").button("Done").click();
 
-      saveDashboard();
+      saveDashboard({ waitMs: 250 });
```
Comment (oleggromov) [inline e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js:218]: This is needed for [the same reason](https://github.com/metabase/metabase/pull/36910/files#r1437018691) it was needed before.

File: frontend/src/metabase/dashboard/actions/data-fetching.js (hunk 1 above)
Comment (alxnddr) [reply frontend/src/metabase/dashboard/actions/data-fetching.js:351]: I think the equals part should definitely be `!equals(...)` since there should be difference. Regarding lastResult, I think we do not need to clear anything if there is no last result. But these are guesses based on logic which may not always work 😬

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 5]
```diff
@@ -345,7 +345,16 @@ export const fetchCardData = createThunkAction(
 
       cancelFetchCardData(card.id, dashcard.id);
 
-      if (clearCache) {
+      // When dashcard parameters change, we need to clean previous (stale)
+      // state so that the loader spinner shows as expected (#33767)
```
Comment (alxnddr) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:349]: 👍 for the explanation comment

**Review by alxnddr — APPROVED** [review]
This approach looks more reasonable to me, thanks for addressing my feedback! The timeouts in tests look not great, but I guess there is no simple solution to avoid them, right? cc @nemanjaglumac

**Comment by oleggromov** [comment]
@alxnddr I haven't found a better way - and [neither did](https://github.com/metabase/metabase/pull/36910/files#r1437036987) @ranquild

**Review by ranquild — APPROVED** [review]
