### PR TITLE
Fix MySQL 5.1 support

### LINKED ISSUE #3502: Broken compatibility with MySQL 5.1
The newly permissions_revision table contains remarks that exceed 60 characters. This breaks the migration from v0.19 to v0.20 with the error:

> Comment for table 'permissions_revision' is too long (max = 60)

This issue with MySQL was fixed after version 5.1 - however, still a lot of enterprise software is using 5.1.

### PR DESCRIPTION
**Pull request by camsaul**
Fix support for MySQL 5.1. (Fixes #3502)

Unfortunately, while we have been writing really good explanations of what things are used for lately, MySQL 5.1 has a strict limit of 60 characters for table/column/etc. remarks. So I went in an shortened up the 40-odd remarks that were over that limit and added new valid check sums for each changed migration.

To make sure this doesn't happen again I added a short linter script that checks for any remarks over the limit. Testing against MySQL 5.1 would be better but that version is close to 9 years old and it doesn't seem like there's any easy way to install it on Circle. So this is the next best thing.

### CODE REVIEW

File: bin/check_for_long_migration_remarks.pl [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+# loop over every line in migrations file. If line starts with `remarks:` and is over 60 chars, inc count & log error
+open(FILE, '<:encoding(UTF-8)', './resources/migrations/000_migrations.yaml') or die $!;
+while (<FILE>) {
+    $long_remarks += 1 && print "Remark on line $. is too long (${\(length)}/60): $_"
+      if m/remarks/ && s/^\s+remarks:\s'(.*)'$/$1/ && length > 60;
+}
+
+# if we've seen any remarks that are too long print message and die
+die "$long_remarks remarks are over 60 characters long, making them incompatible with MySQL 5.1." if $long_remarks;
```
Comment (senior) [inline bin/check_for_long_migration_remarks.pl]: I think you might want a `\n` at the end of this string. I currently get:
```
Remark on line 3849 is too long (122/60): Whether we                                                                    should do On-Demand caching of FieldValues.
1 remarks are over 60 characters long, making them incompatible with MySQL 5.1. at ./bin/check_for_long_migration_remarks.pl line 16, <FILE> line 3861.
```
But with the newline
```
Remark on line 3849 is too long (122/60): Whether we                                                                    should do On-Demand caching of FieldValues.
1 remarks are over 60 characters long, making them incompatible with MySQL 5.1.
```
Maybe a leading `\n` would be good too so that the failing lines and the concluding line don't run together

File: resources/migrations/000_migrations.yaml [hunk 2]
```diff
@@ -3208,11 +3208,13 @@ databaseChangeLog:
   - changeSet:
       id: 47
       author: camsaul
+      validCheckSum: '7:381e18d5008269e299f12c9726163675'
```
Comment (senior) [inline resources/migrations/000_migrations.yaml]: I learned something here 👍

File: bin/check_for_long_migration_remarks.pl (hunk 1 above)
Comment (camsaul) [reply bin/check_for_long_migration_remarks.pl]: not a bad idea

**Review by senior — APPROVED** [review]
Looks good to me, just a minor suggestion on the error message at the end.
