### PR TITLE
fix: only remove vis_settings from dashboardcard

### LINKED ISSUE #55496: We're loading the analytics cards on every upgrade
### Describe the bug

Seems that we reload everything on every version upgrade

### To Reproduce

1) start Metabase 52.8, wait for it to initialize. check the report_card and report_dashboardcard tables on the database, see the id of the cards of the analytic collection
2) start Metabase 53.7, wait for it to initialize, check the same tables, see how the id's changed

### Expected behavior

if the content is the same, it should not change

### Logs

NA

### Information about your Metabase installation

```JSON
it's been there for ages I guess
```

### Severity

P2

### Additional context

NA

### PR DESCRIPTION
**Pull request by edpaget**
closes #55496
### Description

Fixes loading serialized dashboard cards where we would previously delete and recreate them on each load.

In order to handle circular dependencies caused by links to other dashboards in a dashboardcard's visualization_settings we were removing the dashboardcards entirely from the dashboard model to break the cycle. Later when we traversed back through the dependency path we would load the original dashboard a second time with the restored dashboardcards.

However, on the load of the cycle breaking change we could entirely drop dashcards belonging to the dashboard because the serialization code was treating our cycle breaking changes as an edit to the dashboard to drop those cards. This meant when we got back to the the second load of the dashboard we would create the dashcards fresh instead of updating existing instances.

The fix here is that we only remove the values from the dasboard card model that can cause the cycle -- in this case just the visualization_settings column. This seemed the most straightforward fix, but there are other possibilities here.

One is that we could _just_ preserve the entity_id column in dashcards which would eliminate the possibility of any other cycles here.

Another option would be to change how we handle nested models in serialization. There is not really a foreign key dependency here between dashboard A and dashboard B linked by the dashboard card. If we instead just created those dashboards first _then_ went back and created their dashcards we don't have any problems at all. We could move nested models up to the same level of handling in serialization that we do for models, which would let us create the dashboards first then create any dashboard cards in a subsequent step.

### How to verify

On an instance of metabase with an open repl run 
```clojure
(require '[metabase-enterprise.audit-app.audit :as audit])
(require '[metabase.plugins :as plugins])
(require '[metabase-enterprise.serialization.cmd :as serialization.cmd])


(serialization.cmd/v2-load-internal! (str (#'audit/instance-analytics-plugin-dir (plugins/plugins-dir)))
                                                            {:backfill? false}
                                                            :token-check? false
                                                            :require-initialized-db? false)
```

You would previously see the ids of the dashcards for the audit analytics change. now they will not change. 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 1]
```diff
@@ -21,8 +21,15 @@
 
   This map works around this: given a model (e.g. `Card`) that triggered a dependency loop, it provides a set of keys
   to remove from the model so that we'll be able to successfully load it."
-  {"Dashboard" #{:dashcards}
-   "Card" #{:dashboard_id}})
+  {"Dashboard" #{[:dashcards :* :visualization_settings]}
+   "Card" #{[:dashboard_id]}})
+
+(defn- remove-by-path
```
Comment (edpaget) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:27]: Desperately wanted to use a zipper here.

Comment (escherize) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:27]: Nice. Can you update the docstring in `model->circular-dependency-keys` to explain that it no longer `"provides a set of keys to remove from the model"`?

**Review by escherize — APPROVED** [review]
LGTM

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 2]
```diff
@@ -19,10 +19,18 @@
...
+  indicate that all items in that vector should have a key removed."
+  {"Dashboard" #{[:dashcards :* :visualization_settings]}
+   "Card" #{[:dashboard_id]}})
+
+(defn- remove-by-path
+  [entity [first-key & rest]]
+  (cond
+    (empty? rest) (dissoc entity first-key)
+    (= :* first-key) (mapv #(remove-by-path % rest) entity)
+    :else (update entity first-key remove-by-path rest)))
```
Comment (piranha) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:33]: poor man's specter 😁
