### PR TITLE
Remove unnecessary calls to `/api/collection`

### LINKED ISSUE #46695: /api/collection takes too much time in v50
### Describe the bug

There seems to be an issue in /api/collection (you hit this endpoint as soon as the save question modal appears): the query to the DB seems super fast, but we take a lot of time to send it back to the user
image

### To Reproduce

1) set up Metabase v50
2) add a lot of collections (10K would be fine, I used 30K to make it worse)
3) create a question and click on save, to make the modal window appear
4) see the /api/collection endpoint hitting, it should take a considerable amount of time (takes 25 secs on my example and returns a 11MB JSON). (uses 100% of a single CPU so I believe it's building JSON)

image

image

### Expected behavior

Should be fast

### Logs

NA

### Information about your Metabase installation

```JSON
v50.19
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/46695

### Description

Removes the remaining calls to very slow endpoint: `/api/collection` in the app, and removes one of the hooks that calls it. We were using this endpoint to find the "Custom Reports" collection for enterprise instances when a user would save a modified instance analytics question, our copy and save modals would default to this collection.

1. Creates a new hook: `useGetDefaultCollectionId` in enterprise and OSS flavors
2. The enterprise hook just calls the the endpoint that tells us the id of the custom reports collection, and returns it if the source question is in the instance analytics collection, instead of fetching all collections and searching through them for the custom reports collection
3. **Bonus bugfix**: checks whether the user has write permissions to the custom reports collection before suggesting it as a save target

### How to verify

On an EE instance:

User Type | Scenario | Suggested Collection
--|--|--
ee admin | copying an instance analytics dashboard | Custom Reports
ee admin | copying an instance analytics question | Custom Reports
ee admin | copying a regular dashboard | the parent collection of that dashboard
ee admin | copying a regular question | the parent collection of that question
ee admin | creating a new question |  Our Analytics
ee admin | creating a new dashboard | Our Analytics
ee limited user with curate access to custom reports  | copying an instance analytics dashboard | Custom Reports
ee limited user with curate access to custom reports | copying an instance analytics question | Custom Reports
ee limited user with view access to custom reports  | copying an instance analytics dashboard | Our analytics
ee limited user with view access to custom reports | copying an instance analytics question | Our analytics
ee limited user | creating a new question |  Our Analytics
ee limited user | creating a new dashboard | Our Analytics

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/common/hooks/entity-framework/use-collection-list-query/index.ts
Comment (iethree) [inline frontend/src/metabase/common/hooks/entity-framework/use-collection-list-query/index.ts:1]: we don't want people using this endpoint, so I deleted the hook which was already deprecated 🔥

File: frontend/src/metabase/collections/components/CollectionContent/CollectionContent.tsx [hunk 1]
```diff
@@ -29,15 +29,13 @@ export function CollectionContent({
 }) {
   const { data: bookmarks, error: bookmarksError } = useBookmarkListQuery();
   const { data: databases, error: databasesError } = useDatabaseListQuery();
-  const { data: collections, error: collectionsError } = useCollectionListQuery(
```
Comment (iethree) [inline frontend/src/metabase/collections/components/CollectionContent/CollectionContent.tsx:32]: this was the only remaining use of `useCollectionListQuery`

File: frontend/src/metabase/entities/containers/EntityCopyModal.tsx [hunk 2]
```diff
@@ -32,61 +27,46 @@ const EntityCopyModal = ({
...
-          <CopyQuestionForm
-            onSubmit={copy}
-            onClose={onClose}
-            onSaved={onSaved}
-            collections={collections}
-            {...props}
-          />
-        );
-    }
-  };
```
Comment (iethree) [inline frontend/src/metabase/entities/containers/EntityCopyModal.tsx:77]: we didn't need this extraneous `renderForm` function, we can just do it inline

File: frontend/src/metabase/entities/containers/EntityCopyModal.tsx [hunk 3]
```diff
@@ -32,61 +27,46 @@ const EntityCopyModal = ({
...
   return (
     <ModalContent
       title={title || t`Duplicate "${resolvedObject.name}"`}
       onClose={onClose}
     >
-      {!collections?.length ? (
-        <Flex justify="center" p="lg">
-          <Loader />
-        </Flex>
-      ) : (
```
Comment (iethree) [inline frontend/src/metabase/entities/containers/EntityCopyModal.tsx:88]: we no longer have to wait for all the collections to load 🥳

File: frontend/src/metabase/entities/collections/getInitialCollectionId.ts [hunk 4]
```diff
@@ -51,7 +51,7 @@ const getInitialCollectionId = createSelector(
     byCollectionIdProp,
     byCollectionIdNavParam,
     byCollectionUrlId,
```
Comment (iethree) [inline frontend/src/metabase/entities/collections/getInitialCollectionId.ts:53]: I think these are unnecessary but I'm not brave enough to delete them

**Review by sloansparger — APPROVED** [review]
i tried to find something wrong with this but it looks really good! great work!

File: frontend/src/metabase/entities/collections/getInitialCollectionId.ts (hunk 4 above)
Comment (npfitz) [reply frontend/src/metabase/entities/collections/getInitialCollectionId.ts:53]: `byCollectionId` will still work because you're passing `{collectionId: id}` to the selector in `_useGetDefaultCollectionId`. But the others depend on router props that won't be there anymore. Is `getInitialCollectionId` used anywhere else?

**Review by npfitz — APPROVED** [review]
