### PR TITLE
Query builder bug fixes

### LINKED ISSUE #1986: Cards / queries break and can't be modified if underlying column is removed
Hi,

we modified some of our tables, moved around some columns etc. in our postgre db. We discovered that existing cards (correctly) now give us the error "ERROR: column abc.xyz does not exist Position: 123" - but we can't modify the query anymore, so we have to rebuild all the affected cards. Would be great if you could just modify queries that run into errors.

### LINKED ISSUE #3171: I shouldn't be able to select filters, view options, or groupings until I've chosen a table
I can't remember if this behavior has always been possible, so it might be a regression. In any case, it's super stupid that I can do this, especially because these selections get wiped out when I finally **do** pick a table:

screen shot 2016-08-11 at 10 19 29 am

### LINKED ISSUE #3173: Mongo nested fields being displayed in the QB filter dropdown without the top level
Eg, for the parse backend's mongo collections, there are documents like:
{"acl":{"blah":1}} that are being showing in the query builder as 
a field named `blah` instead of a field named `acl.blah`

### LINKED ISSUE #3416: UI pulled back to query answer after navigating away from query while "doing science"
Metabase Version: v0.17.1
Browser: Chrome
OS: Win 7x64

This happens to me frequently with queries that take a long time to run. I'll write some SQL, Get Answer (let's say this takes 20 seconds), and then go to Save. After saving, the query runs again (this is potentially one thing to fix). I don't want to wait for the answer, because I've already confirmed and saved, so I navigate away (to a new or different question, dashboard, etc). Then about 20 seconds later, the screen flips back and shows me the Answer for the previous query I saved (this is something to fix for sure). 

The query must not be aborted when I navigate away?

### LINKED ISSUE #3467: Saving a card causes the query to be re-run
Repro'd using the sample dataset off master.

Do a count of orders, and save it. I get the below server logs showing that the query is re-run. For heavy queries on slow data warehouses (i.e. redshift), this can be really annoying.

```
10-06 12:19:05 DEBUG metabase.query-processor :: 
QUERY: 😎
{:database 1,
 :type "query",
 :query {:source_table 2, :aggregation ["count"], :breakout [], :filter []},
 :parameters [],
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info {:executed-by 1, :card-id nil, :uuid "dbd431ec-5ce3-48d9-9fd9-f8495d7f714e", :query-hash 486051882, :query-type "MBQL"}}

10-06 12:19:05 DEBUG metabase.query-processor :: 

PARAMS/SUBSTITUTED: 😻
{:database 1,
 :type "query",
 :query {:source_table 2, :aggregation ["count"], :breakout [], :filter []},
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info {:executed-by 1, :card-id nil, :uuid "dbd431ec-5ce3-48d9-9fd9-f8495d7f714e", :query-hash 486051882, :query-type "MBQL"},
 :driver {},
 :settings {}}

10-06 12:19:05 DEBUG metabase.query-processor :: 
PREPROCESSED/EXPANDED: 😻
{:database {:name "Sample Dataset", :id 1, :engine :h2, :details "😋 ", :features (:standard-deviation-aggregations :foreign-keys :native-parameters :expressions)},
 :type "query",
 :query {:source-table {:schema "PUBLIC", :name "ORDERS", :id 2}, :aggregation {:aggregation-type :count}},
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info {:executed-by 1, :uuid "dbd431ec-5ce3-48d9-9fd9-f8495d7f714e", :query-hash 486051882, :query-type "MBQL"},
 :driver "H2",
 :settings {},
 :fk-field-ids #{}}

10-06 12:19:05 DEBUG query-processor.permissions :: Permissions Check 🔒 : Can User 1 access Table 2 (PUBLIC.ORDERS)?
10-06 12:19:05 DEBUG query-processor.permissions :: Permissions Check 🔓 : Yes ✅  because User 1 is a member of Group 1 (All Users) which has permissions for '/db/1/'
10-06 12:19:05 DEBUG generic-sql.query-processor :: HoneySQL Form: 🍯
 {:from (:PUBLIC.ORDERS), :select ([:%count.* :count])}

10-06 12:19:05 DEBUG metabase.query-processor :: NATIVE FORM: 😳
{:query "SELECT count(*) AS \"count\" FROM \"PUBLIC\".\"ORDERS\"", :params nil}


10-06 12:19:05 DEBUG driver.generic-sql :: Creating new connection pool for database 1 ...
10-06 12:19:05 DEBUG query-processor.annotate :: Sorted fields:
([:1-aggregation 2147483647 :2-other :count])

10-06 12:19:05 DEBUG metabase.middleware :: POST /api/dataset 200 (174 ms) (10 DB calls)
10-06 12:19:38 DEBUG metabase.middleware :: POST /api/card 200 (8 ms) (4 DB calls)
10-06 12:19:39 DEBUG metabase.query-processor :: 
QUERY: 😎
{:database 1,
 :type "query",
 :query {:source_table 2, :aggregation ["count"], :breakout [], :filter []},
 :parameters [],
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info {:executed-by 1, :card-id 4, :uuid "5f872602-e230-48a2-a0dd-3c8856a4c29b", :query-hash 486051882, :query-type "MBQL"}}

10-06 12:19:39 DEBUG metabase.query-processor :: 

PARAMS/SUBSTITUTED: 😻
{:database 1,
 :type "query",
 :query {:source_table 2, :aggregation ["count"], :breakout [], :filter []},
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info {:executed-by 1, :card-id 4, :uuid "5f872602-e230-48a2-a0dd-3c8856a4c29b", :query-hash 486051882, :query-type "MBQL"},
 :driver {},
 :settings {}}

10-06 12:19:39 DEBUG metabase.query-processor :: 
PREPROCESSED/EXPANDED: 😻
{:database {:name "Sample Dataset", :id 1, :engine :h2, :details "😋 ", :features (:standard-deviation-aggregations :foreign-keys :native-parameters :expressions)},
 :type "query",
 :query {:source-table {:schema "PUBLIC", :name "ORDERS", :id 2}, :aggregation {:aggregation-type :count}},
 :constraints {:max-results 10000, :max-results-bare-rows 2000},
 :info {:executed-by 1, :card-id 4, :uuid "5f872602-e230-48a2-a0dd-3c8856a4c29b", :query-hash 486051882, :query-type "MBQL"},
 :driver "H2",
 :settings {},
 :fk-field-ids #{}}

10-06 12:19:39 DEBUG query-processor.permissions :: Permissions Check 🔒 : Can User 1 access Table 2 (PUBLIC.ORDERS)?
10-06 12:19:39 DEBUG query-processor.permissions :: Permissions Check 🔓 : Yes ✅  because User 1 is a member of Group 1 (All Users) which has permissions for '/db/1/'
10-06 12:19:39 DEBUG generic-sql.query-processor :: HoneySQL Form: 🍯
 {:from (:PUBLIC.ORDERS), :select ([:%count.* :count])}

10-06 12:19:39 DEBUG metabase.query-processor :: NATIVE FORM: 😳
{:query "SELECT count(*) AS \"count\" FROM \"PUBLIC\".\"ORDERS\"", :params nil}


10-06 12:19:39 DEBUG query-processor.annotate :: Sorted fields:
([:1-aggregation 2147483647 :2-other :count])

10-06 12:19:39 DEBUG metabase.middleware :: POST /api/card/4/query 200 (80 ms) (11 DB calls)

```

### LINKED ISSUE #3645: Table list doesn't close when moving off a new question and returning
Steps to reproduce
1. open a "new question" 
2. Go to the questions page
3. click on a question

you'll see that the saved question loads with the table select dropdown open.

### PR DESCRIPTION
**Pull request by tlrobinson**
- [x] Clear old state, including `queryResult`, immediately upon returning to qb
  - [x] Prevent previous query from appearing briefly while metadata loads
  - [x] Table list doesn't close when moving off a new question and returning. Resolves #3645
  - [x] I shouldn't be able to select filters, view options, or groupings until I've chosen a table. Resolves #3171
- [x] If the card is saved but dirty use `MetabaseApi.dataset` instead of `CardApi.query`.
- [x] Saving a card causes the query to be re-run. Resolves #3467
- [x] UI pulled back to query answer after navigating away from query while "doing science". Resolves #3416
- [x] Cards / queries break and can't be modified if underlying column is removed. Resolves #1986
- ~~Number displayed as a boolean #3506~~ (not qb issue)
- [x] Mongo nested fields being displayed in the QB filter dropdown without the top level Resolves #3173

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers These should all be fixed. I might try to add some tests, but they're going to be tricky. In the meantime here are some things to try:

1. Run a query, navigate away from the query builder (e.x. "Pulses"), then click "New Question". You should *not* briefly see the previous query result
2. Click "New Question", click "Questions", click a previously saved (GUI) question. The db/table widget should *not* be open.
3. Run a query, click "New Question", you should *not* be able to add a filter/aggregation/breakout until you select a db/table.
4. Open a saved query, click the edit/pencil icon, change the query and run it. It should run the new query, not the old one.
5. Save a query, it should *not* re-run it
6. Run query that takes a long time (e.x. Postgres SQL query `select pg_sleep(10)`), click "New Question", the result of the old query should *not* appear. 
7. Run query that takes a long time (e.x. Postgres SQL query `select pg_sleep(10)`), navigate away from the query builder (e.x. "Pulses") then back to the query builder (e.x. "New Question") before the query should finish, the result of the old query should *not* appear.

**Comment by salsakran** [comment]
verified all 7 of those 👍

**Comment by tlrobinson** [comment]
@metabase/core-developers Anyone want to review the code?

File: frontend/src/metabase/components/AddToDashSelectDashModal.jsx [hunk 1]
```diff
@@ -24,13 +25,13 @@ export default class AddToDashSelectDashModal extends Component {
 
     static propTypes = {
         card: PropTypes.object.isRequired,
-        dashboardApi: PropTypes.object.isRequired,
         closeFn: PropTypes.func.isRequired,
         onChangeLocation: PropTypes.func.isRequired
     };
 
     async loadDashboardList() {
-        var dashboards = await this.props.dashboardApi.list({ f: "all" });
```
Comment (salsakran) [inline frontend/src/metabase/components/AddToDashSelectDashModal.jsx]: 👍  it feels way more straightforward to just import things like services rather than inject them into components. Feel like we should either Do-DI  or NotDo-DI, but mixing them seems like the worst of all worlds

**Review by salsakran — APPROVED** [review]
looks good to me 👍
