### PR TITLE
fix(formatting): round compact numbers with Intl; preserve legacy k casing (closes #59454)

### LINKED ISSUE #59454: Number card shows truncated value instead of rounding when condensed
### Describe the bug

The "big number" card seems to truncate (vs. rounding) the number when switching to condensed number format, which results in a misleading display.

Image

### To Reproduce

1. Create a card with a single large (currency) number
2. Reduce its size to the minimum

### Expected behavior

Condensed (currency) numbers should be rounded, in my case (and for anything >= $1,500,000,000) it should show "$2B".

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "hu",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-04-24",
      "tag": "v0.54.4.3",
      "hash": "ac4440d"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "5.10.234-225.910.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lwensveen**
Closes [https://github.com/metabase/metabase/issues/59454](https://github.com/metabase/metabase/issues/59454)

### Description

This patch replaces the existing `Humanize.compactInteger` call in `_formatNumberCompact` with an `Intl.NumberFormat` configured for **compact notation**, ensuring that large numbers are **rounded** (not truncated) when abbreviated. For example:

* Previously: `1.95 B` with 0 decimals → `$1B`
* Now: `1.95 B` with 0 decimals → `$2B`

We preserve legacy behavior such as lower-case `k` for thousands (e.g. `-$500.0k`) and the existing currency/locale logic remains untouched.

### How to verify

1. **Run Metabase in dev mode** (e.g. `yarn start` or `bin/start`).
2. **Create a SQL question** on the Sample Dataset:

   ```sql
   SELECT 1500000000 AS amount;
   ```
3. **Switch to “Single value”** visualization, set:

   * Decimals → **0**
   * Prefix → **\$** (or Number style → Currency)
   * Enable **Abbreviate / Compact** (if available).
4. **Save** and **add** the question to a new dashboard.
5. **Resize** the card to the smallest 1×1 tile.
6. **Observe:** the card now displays **`$2B`** instead of **`$1B`**.
7. **Run the tests** to confirm edge cases:

   ```bash
   yarn test frontend/src/metabase/lib/formatting/numbers.unit.spec.ts
   ```

   All tests, including the new rounding boundaries, should pass.

### Demo

Screenshot 2568-07-31 at 11 25 58

### Checklist

* [x] Tests have been added/updated to cover compact-rounding behavior
* [x] All existing tests pass (`yarn test`)

### CODE REVIEW

File: frontend/src/metabase/lib/formatting/numbers.tsx [hunk 1]
```diff
@@ -263,15 +262,17 @@ function _formatNumberCompact(
...
-    // 1 => 1
-    // 1000 => 1K
     const isDefaultDecimalCount =
       options.maximumFractionDigits ===
       DEFAULT_NUMBER_OPTIONS.maximumFractionDigits;
-    formatted = Humanize.compactInteger(
-      Math.round(value),
-      isDefaultDecimalCount ? 1 : options.maximumFractionDigits,
-    );
+    const decimals =
```
Comment (deniskaber) [inline frontend/src/metabase/lib/formatting/numbers.tsx:268]:
```suggestion
    const decimalsCount =
```

**Review by deniskaber — APPROVED** [review]
Looks good! Thank you!

**Comment by somiandras** [comment]
I'm still seeing this error in the latest version (0.56.4.2), though the fix seems to have been merged a month ago.
image
