### PR TITLE
Fixing xlsx pivot table exports to respect table column names

### LINKED ISSUE #51342: Pivoted xlsx exports - pivot table fields are named as 'Sum' instead of column name
### Describe the bug

When exporting a pivot table as xlsx (with data kept pivoted), the summarized columns in Excel are displayed as 'Sum' instead of the actual column names.
Image

In Numbers, the value field titles differ and include the source column names:
Image

### To Reproduce

1. Create a pivot table, for example:
Image
2. Export as xlsx, keep the data pivoted.
3. View the exported results in Excel.

### Expected behavior

The column titles in Excel should match the original column names from Metabase.

Numbers may display the titles differently, but I think the xlsx export should prioritize how Excel renders the formatting since it is the original tool used for this file type.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Seen in v1.51.8 and v1.52.2.5
```

### Severity

Reported by a customer. Annoying as the fields need to be manually renamed.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tsplude**
Closes #51342 #49605 

- Fixes xlsx pivot table exports to respect table column names
  - Previously we were passing no column name into `XSSFPivotTable.addColumnLabel` and everything was getting the default name for whatever aggregation function was being used, which is hard coded to `DataConsolidateFunction/SUM`
  - We have to hardcode `DataConsolidateFunction/SUM` because we can't rely on excel's pivot table aggregation functions since QP pre-aggregates the data for us, so `DataConsolidateFunction/SUM` effectively acts as a pass through so that the pre-aggregated values that get dumped into the `data` sheet show up in the resulting pivot table. This works for simple pivot tables but ultimately is not ideal; more context [here](https://github.com/metabase/metabase/issues/51786)
- Adds fallback logic to column title generation to use `:display_type` if the custom column title is empty

<details>
<summary>Before</summary>
image
</details>
<details>
<summary>After</summary>
image
</details>

### CODE REVIEW

File: src/metabase/query_processor/streaming/common.clj [hunk 1]
```diff
@@ -113,7 +113,9 @@
                            (if is-currency?
                              (merge-global-settings format-settings :type/Currency)
                              format-settings))
-          column-title    (or (when format-rows? (::mb.viz/column-title merged-settings))
+          column-title    (or (when format-rows? (if (seq (::mb.viz/column-title merged-settings))
+                                                   (::mb.viz/column-title merged-settings)
+                                                   (:display_name col)))
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming/common.clj:118]: Why is this extra condition needed? If the first arg of the `or` is `false` or `nil` it should evaluate the next one, so `:display_name` was already the fallback here.

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 2]
```diff
@@ -623,7 +623,13 @@
     (doseq [idx pivot-cols]
       (.addColLabel pivot-table idx))
     (doseq [idx pivot-measures]
-      (.addColumnLabel pivot-table DataConsolidateFunction/SUM #_(get aggregation-functions idx DataConsolidateFunction/SUM) idx))
+      ;; Really this should be doing (get _aggregation-functions idx) in place of the hard coded SUM function
+      ;; But since QP sends us pre-aggregated data we can't use excel's innate aggregation functions
+      (let [col-name (let [name (nth col-names idx)]
+                       (if (not-empty name)
+                         name
+                         (:display_name (get ordered-cols idx))))]
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming/xlsx.clj:631]: nit - a little more idiomatic: 
```suggestion
      (let [col-name (or (not-empty (nth col-names idx))
                         (get-in ordered-cols [idx :display_name]))]
```

**Review by noahmoss — APPROVED** [review]

File: src/metabase/query_processor/streaming/common.clj (hunk 1 above)
Comment (tsplude) [reply src/metabase/query_processor/streaming/common.clj:118]: The intention here is to stop empty string column titles from being used as they break the xlsx export. I should probably add a comment saying as such

Comment (noahmoss) [reply src/metabase/query_processor/streaming/common.clj]: Couldn't you use `not-empty` here too for that?

**Comment by tsplude** [comment]
@metabase-bot backport release-x.52.x
