### PR TITLE
Fix basic actions aren't showing in the order of CUD

### LINKED ISSUE #29593: Basic actions (CUD) display order is non-deterministic
**Describe the bug**
The way we display automatically created basic actions is non-deterministic. It's really hard to spot and can lead to mistakes.

**To Reproduce**
_Repro steps assume you have at least one model and actions enabled on a database_
1. Go to model details
2. Click on "Create basic actions" *
3. The order is "random", and can sometimes be CUD, DCU, UCD...

* _Hint: You can disable basic actions (which will delete them) and then create them again in order to see this randomness in action_

**Expected behavior**
We should display these basic actions in the same order every single time.

**Screenshots/videos**
image

image

image

**Information about your Metabase Installation:**
local dev, `master`, b96c3998c9078d6ae1a6da22408890bffd870505, H2, Sample Database

**Severity**
P3 since this is just a UX thing, **but** it might lead to someone not even realizing which action they trigger.

**Additional context**
When someone clicks on "Create basic actions" button, three `POST` requests are fired (one for each of CUD operations). We literally display these actions in the same order as the requests' responses reach frontend. As an alternative, we could first wait for all responses to come back and then display the order **we want**.

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/29593

### Description

Previously, the test would fail intermittently because we were ordering actions by their created UNIX seconds. And in Cypress environment, the requests are fast and are usually created in the same second. That means we would show the basic actions in the order they're created. However, sometimes the actions that are created after another can be finished in the next second and this is when things start to get a little weird.

We are showing the latest created actions first, so when that happens, the last created action is shown first so the order could be e.g. Delete, Create, Update given that Create and Update are created in for example, second 1 and Delete is created in second 2.

So, to fix this problem, we should order actions by their created millisecond instead, and revert the order of basic action creation from Create, Update, Delete to Delete, Update, Create to account for the actual sorting.

### How to verify

1. Run the test `should allow CRUD operations on model actions` in `e2e/test/scenarios/models/model-actions.cy.spec.js` as many times as you like and it shouldn't fail once. I tested by looping the test 20 times, and it did not fail. Usually, you could see it fails after less than 10 tries.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/entities/actions/actions.ts [hunk 1]
```diff
@@ -57,11 +57,14 @@ const defaultImplicitActionCreateOptions = {
 const enableImplicitActionsForModel =
   async (modelId: number, options = defaultImplicitActionCreateOptions) =>
   async (dispatch: Dispatch) => {
-    if (options.insert) {
+    // We're ordering actions that's most recently created first.
```
Comment (WiNloSt) [inline frontend/src/metabase/entities/actions/actions.ts:60]: There is also a detail explanation in the [PR description here](https://github.com/metabase/metabase/pull/31184#issue-1733552826).

File: frontend/src/metabase/models/components/ModelDetailPage/ModelActionDetails/ModelActionDetails.tsx [hunk 2]
```diff
@@ -218,7 +218,7 @@ function NoActionsState({
 
 function mostRecentFirst(action: WritebackAction) {
   const createdAt = parseTimestamp(action["created_at"]);
-  return -createdAt.unix();
+  return -createdAt.valueOf();
```
Comment (WiNloSt) [inline frontend/src/metabase/models/components/ModelDetailPage/ModelActionDetails/ModelActionDetails.tsx:221]: This is the fix. [`moment.unix()`](https://momentjs.com/docs/#/displaying/unix-timestamp/) would return the Unix timestamp in seconds, but [`moment.valueOf()`](https://momentjs.com/docs/#/displaying/unix-timestamp-milliseconds/) would return the Unix timestamp in milliseconds.

**Comment by WiNloSt** [comment]
I stress test this test, [but the run is going to timeout eventually](https://github.com/metabase/metabase/actions/runs/5130817139/jobs/9230103022)
image

At least the test we want to stress passed all 20 times.

**Review by nemanjaglumac — APPROVED** [review]
Makes sense.
Thank you for the detailed explanation.

**Review by kulyk — APPROVED** [review]
