### PR TITLE
Include EE endpoints in API documentation.

### LINKED ISSUE #22396: API docs is not including any of the EE endpoints
**Describe the bug**
Running the api-documentation tool does not include EE functions like Sandboxing.
Guessing it has something to do with how they're included (modular).
Those endpoints should have a note that they're EE exclusive.

**Logs**
NA

**To Reproduce**
NA

**Expected behavior**
Have all the endpoints included (specifying the enterprise ones)

**Screenshots**
NA

**Information about your Metabase Installation:**
NA

**Severity**
NA

**Additional context**
We can get less questions about this

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #22396

Note that not all EE endpoints follow the usual convention so we'll need to fix those for them to have the correct routes in the docstrings. The routes are a little off for these until #22687 is fixed.

### CODE REVIEW

File: test/metabase/api/common/internal_test.clj [hunk 1]
```diff
@@ -113,3 +114,12 @@
     ;; should work with some wacky binding form
     '[id :as {body :body}]
     '(clojure.core/let [id (clojure.core/when id (metabase.api.common.internal/parse-int id))] 'body)))
+
+(deftest enterprise-endpoint-name-test
+  (when config/ee-available?
+    (testing "Make sure the route name for enterprise API endpoints is somewhat correct"
+      (require 'metabase-enterprise.advanced-permissions.api.application)
+      (is (= "GET /api/ee/advanced-permissions/applications/graph"
```
Comment (jeff-bruemmer) [inline test/metabase/api/common/internal_test.clj:122]:
```suggestion
      (is (= "GET /api/ee/advanced-permissions/application/graph"
```

**Review by jeff-bruemmer — APPROVED** [review]
