### PR TITLE
Fix Presto bytes to Honey SQL conversion

### LINKED ISSUE #46848: `yyyymmddhhmmss` bytes to timestamp coercion broken for Presto JDBC
The Presto JDBC driver implements a method for `sql.qp/cast-temporal-byte` for `:Coercion/YYYYMMDDHHMMSSBytes->Temporal` but it does not appear to actually work when enabling a test for it in #41384

```
ERROR in metabase.query-processor-test.alternative-date-test/yyyymmddhhmmss-binary-dates (sql.clj:234)

:presto-jdbc

expected: (=
           (yyyymmddhhmmss-binary-dates-expected-rows driver/*driver*)
           (sort-by
            first
            (mt/rows
             (mt/dataset
              yyyymmddhhss-binary-times
              (qp/process-query
               (assoc (mt/mbql-query times) :middleware {:format-rows? false}))))))
  actual: 
clojure.lang.ExceptionInfo: Missing datatype for field "as_bytes" for driver: :presto-jdbc
    driver: :presto-jdbc
     field: {:field-name "as_bytes",
             :base-type {:natives {:postgres "BYTEA", :h2 "BYTEA", :mysql "VARBINARY(100)"}},
             :effective-type :type/DateTime,
             :coercion-strategy :Coercion/YYYYMMDDHHMMSSBytes->Temporal,
             :semantic-type nil,
             :visibility-type nil,
             :fk nil,
             :field-comment nil}
                               metabase.test.data.sql/field-definition-sql                  sql.clj:  234
                           metabase.test.data.sql/eval161930/fn/iter/fn/fn                  sql.clj:  260
                              metabase.test.data.sql/eval161930/fn/iter/fn                  sql.clj:  259
                                                                       ...                               
                                                         clojure.core/next                 core.clj:   64
                                                       clojure.string/join               string.clj:  180
                                      metabase.test.data.sql/eval161930/fn                  sql.clj:  257
                              metabase.test.data.presto-jdbc/eval323175/fn          presto_jdbc.clj:  151
                                                                       ...                               
                                  metabase.test.data.sql.ddl/eval303406/fn                  ddl.clj:   70
                                                                       ...                               
                                                        clojure.core/apply                 core.clj:  671
metabase.test.data.sql-jdbc.load-data/create-db-execute-db-ddl-statements!            load_data.clj:  234
                       metabase.test.data.sql-jdbc.load-data/create-db!/fn            load_data.clj:  267
                              metabase.driver.presto-jdbc/eval323011/fn/fn          presto_jdbc.clj:  706
     metabase.driver.sql-jdbc.execute/fn/do-with-resolved-connection115806              execute.clj:  337
                                    metabase.driver.sql-jdbc.execute/fn/fn              execute.clj:  320
                                 metabase.driver.presto-jdbc/eval323011/fn          presto_jdbc.clj:  699
                                                                       ...                               
                                 metabase.driver.presto-jdbc/eval323011/fn          presto_jdbc.clj:  693
                                                                       ...                               
                          metabase.test.data.sql-jdbc.load-data/create-db!            load_data.clj:  260
                          metabase.test.data.sql-jdbc.load-data/create-db!            load_data.clj:  254
                                                                       ...                               
                                                        clojure.core/apply                 core.clj:  667
                                 metabase.test.data.sql-jdbc/eval303675/fn             sql_jdbc.clj:   40
                                                                       ...                               
  metabase.test.data.impl.get-or-create/load-dataset-data-if-needed!/fn/fn        get_or_create.clj:  251
                   metabase.test.util.timezone/do-with-system-timezone-id!             timezone.clj:   18
     metabase.test.data.impl.get-or-create/load-dataset-data-if-needed!/fn        get_or_create.clj:  250
                                       clojure.core/binding-conveyor-fn/fn                 core.clj: 2047
                                                                       ...                               
                                       java.util.concurrent.FutureTask.run          FutureTask.java:  264
                         java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1128
                        java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  628
                                                      java.lang.Thread.run              Thread.java:  829
```

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/46848

### Description

Fixes Presto varbinary to date test by handling byte arrays. 

### How to verify

The `metabase.query-processor-test.alternative-date-test/yyyymmddhhmmss-binary-dates` test should pass.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj [hunk 1]
```diff
@@ -133,6 +133,10 @@
   [_ bool]
   [:raw (if bool "TRUE" "FALSE")])
 
+(defmethod sql.qp/->honeysql [:presto-jdbc (Class/forName "[B")]
+  [_driver bs]
+  [:to_utf8 (String. bs)])
```
Comment (snoe) [inline modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj:138]: I'm not sure this is safe, this is turning bs into a string with the default charset which could vary from machine to machine and isn't guaranteed to have valid string bytes. I would prefer the base64 encoding as that sidesteps these issues.

**Review by snoe — CHANGES_REQUESTED** [review]

File: modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj (hunk 1 above)
Comment (rileythomp) [reply modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj]: Good point, updated.

**Review by snoe — APPROVED** [review]
