### PR TITLE
Stop publishing elastic beanstalk artifacts

### LINKED ISSUE #31151: Deprecate Elastic Beanstalk
### Describe the bug

We can’t encourage anyone to use elastic beanstalk anymore:
- it’s a black box, our users can’t see the logs easily, and I’m not even considering when things don’t go well where you can’t see what happened with the machine
- AWS doesn’t upgrade it at the same pace it does with other products
- it fails a lot with certain configurations (e.g it obliges your to use multi az on rds when you don’t want to spin up an rds)

If we want to make Metabase easy to use, we can ni longer recommend nor have guides for an AWS product that we wouldn’t use. It would be even easier and more sustainable if we built terraform or cloudformation scripts with a simpler architecture (you can run Metabase in a server connected to an rds db, why would we use a product that was made to deploy entire stacks?)

### To Reproduce

NA

### Expected behavior

NA

### Logs

NA

### Information about your Metabase installation

```JSON
NA
```

### Severity

P1

### Additional context

I know that many people will put a thumbs down to this issue, but if we want to build the simplest way of getting information out of your DB, Beanstalk shouldn’t be on that list.

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/31151

### Description

Metabase 47.2 will be the last version for which we publish elastic beanstalk artifacts. Our [documentation has already been updated](https://www.metabase.com/docs/v0.47/installation-and-operation/running-metabase-on-elastic-beanstalk) to reflect that we do not recommend deploying Metabase on EBS any longer. Instructions for elastic beanstalk setup for older metabase versions are [still available](https://www.metabase.com/docs/v0.46/installation-and-operation/running-metabase-on-elastic-beanstalk) in older versions of the docs.

### CODE REVIEW

File: resources/locales.clj [hunk 1]
```diff
@@ -1,6 +1,9 @@
 {:locales
  #{"nl"
    "en"
+   "sq"
```
Comment (nemanjaglumac) [inline resources/locales.clj:4]: Let's not mess with the `locales.clj` :)
Please checkout and remove this file from the PR.

**Review by nemanjaglumac — APPROVED** [review]
I'm all in for this change and have been waiting a long time to see it.
But please just check one more time with the product before you merge it.

**Comment by nemanjaglumac** [comment]
@iethree No backport?

What if someone needs to release 47.x using the fallback Clojure release script instead of the new automated release process in CI?
