### PR TITLE
Select temporal units for join date-time dimensions

### LINKED ISSUE #10924: Joining two tables by DateTime columns, casts/parses the join as week/month
**Describe the bug**
When using Custom question (Notebook), and joining two tables by `DateTime` columns, the SQL casts/parses the joining-columns as weeks (Postgres) or months (H2).

**To Reproduce**
1. Go to Custom question
2. Select Orders
3. Join by Reviews on Created At = Created At
4. Click "View the SQL"
```SQL
SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT", "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", "PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", "PRODUCTS__via__PRODUCT_ID"."TITLE" AS "TITLE", "Reviews"."ID" AS "ID_2", "Reviews"."BODY" AS "BODY", "Reviews"."CREATED_AT" AS "CREATED_AT_2", "Reviews"."PRODUCT_ID" AS "PRODUCT_ID_2", "Reviews"."RATING" AS "RATING", "Reviews"."REVIEWER" AS "REVIEWER"
FROM "PUBLIC"."ORDERS"
LEFT JOIN "PUBLIC"."REVIEWS" "Reviews" ON parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') = parsedatetime(formatdatetime("Reviews"."CREATED_AT", 'yyyyMM'), 'yyyyMM') LEFT JOIN "PUBLIC"."PRODUCTS" "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID"
LIMIT 1048576
```

**Expected behavior**
Just to join by the selected columns without any casting/parsing.

**Information about your Metabase Installation:**
Metabase 0.33.2 querying Postgres and H2.

**Additional context**
https://discourse.metabase.com/t/0-33-2-join-table-duplicate-rows/7393

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #17826: Joining behavior on datetime columns needs to be clearer
As seen in the demo day today, joining e.g. on `Orders.CreatedAt = Products.CreatedAt` actually evaluates the datetime columns at the month level of granularity, but this isn't clear or obvious at all. 

At minimum, we need to make this behavior explicit. A stretch or future goal is to allow for this granularity to be changed.

## Current behavior

This has evidently been a problem since at least 0.39 as you can see here:

image

That query above generates this SQL:

```
SELECT "PUBLIC"."ORDERS"."ID" AS "ID", "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID", 
"PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID", "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL", 
"PUBLIC"."ORDERS"."TAX" AS "TAX", "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL", "PUBLIC"."ORDERS"."DISCOUNT" AS 
"DISCOUNT", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT", "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY", 
"People"."NAME" AS "People__NAME", "People"."CREATED_AT" AS "People__CREATED_AT"
FROM "PUBLIC"."ORDERS" INNER JOIN "PUBLIC"."PEOPLE" "People" 
ON parsedatetime(formatdatetime("PUBLIC"."ORDERS"."CREATED_AT", 'yyyyMM'), 'yyyyMM') =
parsedatetime(formatdatetime("People"."CREATED_AT", 'yyyyMM'), 'yyyyMM')
LIMIT 1048575
```

### At minimum, clarify the existing behavior

The minimum we can do is change the labels of datetime columns to show that the granularity is hardcoded to `Month`, like this:

image

### Stretch / future: make the granularity modifiable

Let's reuse the granularity picker that we have e.g. for group-bys to allow for the granularity of datetime columns here to be selectable.

Whenever the granularity is changed for one datetime column in a join condition pair, **the granularity for the other column should be changed to match**.

image

### PR DESCRIPTION
**Pull request by kulyk**
In the notebook editor, when you join tables by date-time columns, the SQL casts the joining columns as months. So rows with 11 Jul 2020 and 27 Jul 2020 will match the condition.

This PR makes it possible to select a temporal unit for join dimensions. The options are the same as for breakouts (Day, Week, Month, Year, Quarter, etc.)

Fixes #17826, resolves #10924

### To Verify

1. Ask a question > Custom question > Sample Dataset > Orders
2. Join Products table
3. Select "Inner join" strategy (otherwise the join wouldn't make a lot of sense)
4. Click the "+" button on the right side of the `Orders.PRODUCT_ID = Products.ID` condition to add a new dimensions pair
5. The dimensions picker should open automatically. Hover the "Created At" option and click the "by month" label. From a new popup, select the "Week" option
6. Once the "left" dimension is selected, the "right" dimension picker should open automatically. Now just click "Created At" without specifying the temporal unit.
7. "right" dimension's unit should now also be "Week"
8. Click on the left / right "Created At" dimension and change the temporal unit to "Day"
9. The second dimension's temporal unit should also change to "Day"
10. Click visualize and make sure "Created At" and "Products —> Created At" are the same day-month-year (time can vary). You can hide irrelevant columns to make the testing more convenient.

### Demo

https://user-images.githubusercontent.com/17258145/133302634-20583cc9-2aa3-4545-a191-0364f4302e58.mov

### CODE REVIEW

**Review by flamber — APPROVED** [review]
May I just say: Probably the coolest feature of 41. Awesome work!

I've tried multiple different databases, and SQL questions. Works great.

My only note: Would it be possible to default to Unbinned for non-temporal? Since there's a very small chance that anyone would be using binning on join (because of the lack of control, other issues open about that). I'm not saying binning should be removed, since it might have it's use (example geo location binning).
If not, then it's probably okay. But could it then show the binning selection in the blue join-button, just like it does for temporal?
image

**Review by mazameli — APPROVED** [review]
Bra-vo. 👏🏼 🎉

**Comment by kulyk** [comment]
@flamber 

> Would it be possible to default to Unbinned for non-temporal?

Looks like it's not that simple. The default binning option comes from the deeps of `metabase-lib`, not sure there's a straightforward way to overwrite it and keep the UI consistent. Should we temporarily hide binning for joins maybe?

**Comment by flamber** [comment]
@kulyk No, let's leave them then. Otherwise you would have absolutely no control, kinda similar to how temporal joins work today.
Perhaps Ariya could assist in a follow-up PR - he has played around with binning a lot.

File: frontend/src/metabase-lib/lib/queries/structured/Join.js [hunk 1]
```diff
@@ -406,23 +406,59 @@ export default class Join extends MBQLObjectClause {
...
     const condition = this.getConditionByIndex(index);
-    const newCondition = [
-      "=",
-      condition ? condition[PARENT_DIMENSION_INDEX] : null,
-      this._convertDimensionIntoMBQL(dimension),
-    ];
+    let joinDimension = this._convertDimensionIntoMBQL(dimension);
+    let parentDimension = condition ? condition[PARENT_DIMENSION_INDEX] : null;
+
+    if (
```
Comment (daltojohnso) [inline frontend/src/metabase-lib/lib/queries/structured/Join.js:414]: I'd prefer if we pulled this new `if` block out of `setJoinDimension` and `setParentDimension` to keep them simpler. I think something like the following could be nice:
```
const newCondition = isDateTimeFieldJoin(...)
  ? getDateTimeFieldCondition(...)
  : ["=", parentDimension, joinDimension]
```
But feel free to abstract in whatever way makes sense to you

File: frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx [hunk 2]
```diff
@@ -575,6 +593,12 @@ class JoinDimensionPicker extends React.Component {
   open() {
     this._popover.open();
   }
+
+  hasTemporalUnit = fieldRef => {
+    const [, , opts] = fieldRef;
+    return !!opts?.["temporal-unit"];
```
Comment (daltojohnso) [inline frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx:599]: let's move `getFieldTemporalUnit` in `frontend/src/metabase-lib/lib/queries/structured/Join.js` to `metabase/lib/join.js` and then we can use it here to do most of this logic

File: frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx [hunk 3]
```diff
@@ -537,6 +545,16 @@ function getDimensionSourceName(dimension) {
...
 }
 
+function getDimensionDisplayName(dimension) {
+  if (!dimension) {
+    return t`Pick a column...`;
+  }
+  if (dimension.temporalUnit()) {
+    return `${dimension.displayName()}: ${dimension.subDisplayName()}`;
+  }
+  return dimension.displayName();
```
Comment (daltojohnso) [inline frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx:555]: would it be awful to make this something like...
```
return [
  dimension.displayName(),
  dimension.subDisplayName()
].filter(str => str !== "").join(': ');
```
so that we can avoid have dimension specific logic here?

File: frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx [hunk 4]
```diff
@@ -603,10 +627,20 @@ class JoinDimensionPicker extends React.Component {
...
-            onFieldChange={field => {
-              onChange(field);
+            onFieldChange={(field, item) => {
+              if (this.hasTemporalUnit(field)) {
+                // When we set a default temporal unit by just clicking the dimension name,
+                // FieldList provides a second argument to onFieldChange callback
+                // When a temporal unit is selected explicitly (like by Week, Quarter, Year, etc.)
+                // the item argument is undefined
+                // In this case we want to make sure the second dimension will use the same unit
+                onChange(field, { overwrite: !item });
```
Comment (daltojohnso) [inline frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx:637]: does `item` here mean "sub-dimension" or does it mean more than that? I see that the word `item` is used in `DimensionOptions.js` and `DimensionList.jsx` too so I'm just sort of confused.

I'm left wondering if there isn't a more generic feature hidden here. Specifically, the passing of subdimensions to `Join` which then reconciles whatever is passed to it. IDK if that makes sense--just food for thought.

**Review by daltojohnso — CHANGES_REQUESTED** [review]
nice work! just a few refactor requests if you'll humor me 🙂

File: frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx (hunk 2 above)
Comment (kulyk) [reply frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx:599]: Do we want `metabase-lib` to depend on `metabase`? 🤔 I thought we wanted it to be completely independent ideally. At the moment everything is very coupled (and `metabase-lib` even has methods dispatching Redux actions 😛 ), I'm just thinking if we should couple them more

File: frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx (hunk 3 above)
Comment (kulyk) [reply frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx:555]: You're right it'd be better to hide this logic somewhere, the problem is `subDisplayName` returns `"Default"` for most of the dimensions. And for numeric ones, it would return the binning strategy. So a join sections could look like the following:

CleanShot 2021-09-16 at 13 09 59@2x

File: frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx (hunk 4 above)
Comment (kulyk) [reply frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx]: After a fresh look here it seems to be too hacky TBH. I changed `DimensionList` so it passes a `{ isSubDimension: true }` object as a second argument if subdimension is selected (it used to pass only the first arg). This should be more straightforward

**Review by daltojohnso — APPROVED** [review]
