### PR TITLE
Sanitize SVG before parsing with Batik to prevent render failures when invalid characters are in the SVG content

### LINKED ISSUE #43677: special characters on the data will break subscriptions
### Describe the bug

Some crazy chars will break the subscriptions since batik can't handle those

### To Reproduce

1) new sql question
2) 
```
select '	

  ,',1
union all
select '	

  ',2
```
3) save it as a bar chart
4) add it to a dashboard
5) send as a subscription

### Expected behavior

_No response_

### Logs

```	
2024-06-05 13:00:05.497	
2024-06-05 13:00:05,495 ERROR pulse.render :: Pulse card render error
2024-06-05 13:00:04.909	
	... 68 more
2024-06-05 13:00:04.909	
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:453)
2024-06-05 13:00:04.909	
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)



2024-06-05 13:00:04.909	
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
2024-06-05 13:00:04.909	
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
2024-06-05 13:00:04.909	
Caused by: org.xml.sax.SAXParseException; systemId: file:///fake.svg; lineNumber: 1; columnNumber: 9159; An invalid XML character (Unicode: 0x1f) was found in the element content of the document.
2024-06-05 13:00:04.909	
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2024-06-05 13:00:04.909	
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
2024-06-05 13:00:04.909	
	at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:96)
2024-06-05 13:00:04.909	
	at metabase.models.task_history$do_with_task_history.invoke(task_history.clj:91)
2024-06-05 13:00:04.909	
	at metabase.models.task_history$do_with_task_history.invokeStatic(task_history.clj:96)
2024-06-05 13:00:04.909	
	at metabase.task.send_pulses.SendPulses$fn__107633.invoke(send_pulses.clj:110)
2024-06-05 13:00:04.909	
	at metabase.task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:39)
2024-06-05 13:00:04.909	
	at metabase.task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:46)
2024-06-05 13:00:04.909	
	at metabase.task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:39)
2024-06-05 13:00:04.909	
	at metabase.task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:52)
2024-06-05 13:00:04.909	
	at metabase.task.send_pulses$send_pulses_BANG_$fn__107593.invoke(send_pulses.clj:53)
2024-06-05 13:00:04.909	
	at metabase.models.task_history$do_with_task_history.invoke(task_history.clj:91)
2024-06-05 13:00:04.909	
	at metabase.models.task_history$do_with_task_history.invokeStatic(task_history.clj:96)
2024-06-05 13:00:04.909	
	at metabase.task.send_pulses$send_pulses_BANG_$fn__107593$fn__107594.invoke(send_pulses.clj:57)
2024-06-05 13:00:04.909	
	at clojure.lang.RestFn.invoke(RestFn.java:439)
2024-06-05 13:00:04.909	
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:576)
2024-06-05 13:00:04.909	
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:595)
2024-06-05 13:00:04.909	
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:567)
2024-06-05 13:00:04.909	
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:568)
2024-06-05 13:00:04.909	
	at clojure.core$seq__5467.invoke(core.clj:139)
2024-06-05 13:00:04.909	
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
2024-06-05 13:00:04.909	
	at clojure.lang.RT.seq(RT.java:535)
2024-06-05 13:00:04.909	
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
2024-06-05 13:00:04.909	
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
2024-06-05 13:00:04.909	
	at metabase.pulse$parts__GT_notifications$iter__99964__99968$fn__99969.invoke(pulse.clj:513)
2024-06-05 13:00:04.909	
	at metabase.pulse$parts__GT_notifications$iter__99964__99968$fn__99969$fn__99970.invoke(pulse.clj:515)
2024-06-05 13:00:04.909	
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
2024-06-05 13:00:04.909	
	at metabase.pulse$fn__99889.invoke(pulse.clj:433)
2024-06-05 13:00:04.909	
	at metabase.pulse$fn__99889.invokeStatic(pulse.clj:444)
2024-06-05 13:00:04.909	
	at metabase.email.messages$render_pulse_email.invoke(messages.clj:520)
2024-06-05 13:00:04.909	
	at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:523)
2024-06-05 13:00:04.909	
	at metabase.email.messages$render_message_body.invoke(messages.clj:494)
2024-06-05 13:00:04.909	
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:496)
2024-06-05 13:00:04.909	
	at metabase.email.messages$render_message_body$fn__76480.invoke(messages.clj:497)
2024-06-05 13:00:04.909	
	at clojure.core$mapv.invoke(core.clj:6971)
2024-06-05 13:00:04.909	
	at clojure.core$mapv.invokeStatic(core.clj:6971)
2024-06-05 13:00:04.909	
	at clojure.core$reduce.invokeStatic(core.clj:6887)
2024-06-05 13:00:04.909	
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
2024-06-05 13:00:04.909	
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
2024-06-05 13:00:04.909	
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
2024-06-05 13:00:04.909	
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
2024-06-05 13:00:04.909	
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
2024-06-05 13:00:04.909	
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
2024-06-05 13:00:04.909	
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
2024-06-05 13:00:04.909	
	at clojure.core$mapv$fn__8535.invoke(core.clj:6980)
2024-06-05 13:00:04.909	
	at metabase.email.messages$render_message_body$fn__76480$fn__76481.invoke(messages.clj:497)
2024-06-05 13:00:04.909	
	at metabase.email.messages$render_part.invoke(messages.clj:440)
2024-06-05 13:00:04.909	
	at metabase.email.messages$render_part.invokeStatic(messages.clj:444)
2024-06-05 13:00:04.909	
	at metabase.pulse.render$fn__75440$render_pulse_section__75445.invoke(render.clj:198)
2024-06-05 13:00:04.909	
	at metabase.pulse.render$fn__75440$render_pulse_section__75445$fn__75449.invoke(render.clj:201)
2024-06-05 13:00:04.909	
	at metabase.pulse.render$fn__75440$render_pulse_section__75445$fn__75449$fn__75452.invoke(render.clj:203)
2024-06-05 13:00:04.909	
	at metabase.pulse.render$fn__75407$render_pulse_card__75412.invoke(render.clj:151)
2024-06-05 13:00:04.908	
	at metabase.pulse.render$fn__75407$render_pulse_card__75412$fn__75413.invoke(render.clj:169)
2024-06-05 13:00:04.908	
	at metabase.pulse.render$fn__75367$render_pulse_card_body__75372.invoke(render.clj:130)
2024-06-05 13:00:04.908	
	at metabase.pulse.render$fn__75367$render_pulse_card_body__75372$fn__75376.invoke(render.clj:140)
2024-06-05 13:00:04.908	
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.body$fn__74566$render__74554__74571.invoke(body.clj:840)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.body$fn__74566$render__74554__74571$fn__74572.invoke(body.clj:842)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.body$lab_image_bundle.invoke(body.clj:798)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.body$lab_image_bundle.invokeStatic(body.clj:823)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.js_svg$combo_chart.invoke(js_svg.clj:146)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.js_svg$combo_chart.invokeStatic(js_svg.clj:154)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invoke(js_svg.clj:111)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invokeStatic(js_svg.clj:114)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.js_svg$parse_svg_string.invoke(js_svg.clj:81)
2024-06-05 13:00:04.908	
	at metabase.pulse.render.js_svg$parse_svg_string.invokeStatic(js_svg.clj:85)
2024-06-05 13:00:04.908	
	at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:226)
2024-06-05 13:00:04.908	
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:357)
2024-06-05 13:00:04.908	
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:459)
2024-06-05 13:00:04.908	
org.apache.batik.dom.util.SAXIOException: An invalid XML character (Unicode: 0x1f) was found in the element content of the document.
```

### Information about your Metabase installation

```JSON
since the beginning
```

### Severity

P2

### Additional context

image

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes: #43677 

Sanitize the svg before parse/render. This may not be the best method yet, it might be better to disable the strict XML validation instead, so that we don't have to rely on building up a regex.

### CODE REVIEW

**Review by sansolovyov — APPROVED** [review]
I wonder if it makes sense to log a warning that you had to remove some chars from SVG? Not sure about that, I just wonder how surprising can that be to our users (maybe not that much given right now it just fails 🤣).

File: src/metabase/util/malli/schema.clj [hunk 1]
```diff
@@ -333,7 +334,13 @@
...
      [:name {:optional true} :string]
      [:default {:optional true} :any]
-     [:sectionId {:optional true} NonBlankString]]
+     [:sectionId {:optional true} NonBlankString]
+     [:temporal_units {:optional true}
+      [:sequential
+       (into [:enum]
+             (concat
+              lib.schema.temporal-bucketing/temporal-bucketing-units
+              (map name lib.schema.temporal-bucketing/temporal-bucketing-units)))]]]
```
Comment (piranha) [inline src/metabase/util/malli/schema.clj:343]: Ehm.. I guess this is not relevant for svg sanitization?

Comment (adam-james-v) [reply src/metabase/util/malli/schema.clj:343]: oh, oops. Good catch, I'll remove that :)
