### PR TITLE
Remove abillity for users with DB detail perms to delete DBs

### LINKED ISSUE #22293: Non-admin database manager can delete database using the API
**Describe the bug**
Non-admin database managers (a role that can be assigned to any user group) don't have the option to delete a database in the UI. They can do it using the API, though which comes with a certain risk. The product team eventually decided it's best to prevent that, although the original spec allowed it.

**Logs**
N/A

**To Reproduce**
1. As an admin, give "Database permissions" to All users
2. Log in as normal user
3. Using any API tool, send a `DELETE` request to the `/api/database/:id` (in the case of the Sample Database, the id is `1`)
4. The response is `204` and database actually gets deleted!
5. Try going to `/admin/databases/1`
6. You will see an error message weirdly printed on the home page that you don't have permissions to see that

image

**Expected behavior**
We should block this API request issued by non-admin database managers.

**Information about your Metabase Installation:**
local dev, `master`, 2ba9546ae2a8daf3abf17997edc582dd9ebec287, H2, Sample Database

**Severity**
P1

**Additional context**
~~HUGE edit and moving this from P1 to P2, because I mistakenly thought that the UI displayed a correct behavior and the backend didn't.~~

Another edit and going back to the original issue which was a P1 and a release blocker. Product decided that it makes sense indeed to prevent release managers from deleting a database.

### PR DESCRIPTION
**Pull request by noahmoss**
See https://metaboat.slack.com/archives/C010L1Z4F9S/p1651262695941719 for context.

The original product spec allowed users to delete DBs that they have write perms for. We've decided to revert this decision, so I'm changing the `DELETE /api/database/:id` endpoint to be restricted only to admins. No FE changes are necessary since the delete button is already hidden for these users.

Closes #22293

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj [hunk 1]
```diff
@@ -327,18 +327,9 @@
...
-        (premium-features-test/with-premium-features #{}
-          (mt/user-http-request :rasta :delete 403 (format "database/%d" db-id)))))
-
-    (testing "A non-admin cannot update database metadata if they do not have DB details permissions"
-      (with-all-users-data-perms {db-id {:details :no}}
-        (mt/user-http-request :rasta :delete 403 (format "database/%d" db-id))))
-
-    (testing "A non-admin can update database metadata if they have DB details permissions"
-      (with-all-users-data-perms {db-id {:details :yes}}
-        (mt/user-http-request :rasta :put 200 (format "database/%d" db-id) {:name "Database Test"})))))
```
Comment (noahmoss) [inline enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj:341]: These had been accidentally duplicated from the `update-database-test` above, so just removing them here

File: src/metabase/api/database.clj [hunk 2]
```diff
@@ -718,8 +718,8 @@
 (api/defendpoint DELETE "/:id"
   "Delete a `Database`."
   [id]
-  (let [db (api/write-check (Database id))]
-    (api/write-check db)
+  (api/check-superuser)
+  (let [db (Database id)]
```
Comment (dpsutton) [inline src/metabase/api/database.clj:722]: this should be `api/check-404` so we don't attempt to delete a database that does not exist.

Comment (dpsutton) [reply src/metabase/api/database.clj:722]: or `(api/let-404 [database (Database id)]`

**Review by dpsutton — APPROVED** [review]
