### PR TITLE
fix: snowflake rsa doesn't work with hostname

### LINKED ISSUE #53749: Snowflake RSA connection doesn't work with Hostname setting
### Describe the bug

Snowflake RSA connection doesn't work with Hostname setting

### To Reproduce

Just try to connect with the RSA key but instead of Account Name toggle to Host Name

Image

You will get an error. Doesn't matter what you enter in that section even a simple character

Image

### Expected behavior

If we don't support hostname with RSA key then remove the option

### Logs

`POST /api/database 400 205ms (0 DB calls) {:metabase-user-id 1} 
{:message "Cannot invoke \"java.lang.CharSequence.length()\" because \"this.text\" is null"}`

### Information about your Metabase installation

```JSON
53.1 and master
```

### Severity

Might be confusing for someone who doesn't know what is going on

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snoe**
Fixes #53749

Figured out that we can combine `account` with `snowflakecomputing.com` in order to test host connectivity. In theory, this should work the same in a private-link scenario.

### CODE REVIEW

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 1]
```diff
@@ -87,15 +87,15 @@
...
+                              (when-let [sub (:subname details)]
+                                (format "jdbc:snowflake:%s" sub))
                               (format "jdbc:snowflake://%s.snowflakecomputing.com" account))
         opts-str (sql-jdbc.common/additional-opts->string :url
                                                           {:user (codec/url-encode user)
                                                            :private_key_file (codec/url-encode (.getCanonicalPath ^File private-key-file))})
         new-conn-uri (sql-jdbc.common/conn-str-with-additional-opts existing-conn-uri :url opts-str)]
     (-> details
-        (assoc :connection-uri new-conn-uri)
-        ;; The Snowflake driver uses the :account property, but we need to drop the region from it first
```
Comment (snoe) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:97]: I can find no reference that this is necessary. It could be that private-link requires `:account` but it does not seem required under normal circumstances.

Comment (rileythomp) [reply modules/drivers/snowflake/src/metabase/driver/snowflake.clj:97]: Not sure if this is still relevant but seems like it came from here: https://github.com/metabase/metabase/issues/30376#issuecomment-1591997170
Maybe safer to leave it in and only split if it's non-empty? If not then small nit to just do `(assoc details :connection-uri new-conn-uri)`

**Review by rileythomp — APPROVED** [review]
