### PR TITLE
Check download perms recursively on referenced card-ids

### LINKED ISSUE #50304: Users without Full Download Permissions Cannot DL Results of certain Questions
### Describe the bug

User cannot download the results of a question built from the combo of a table and another question unless they have DL access to every table in the database.

### To Reproduce

1. Set up v51
2.  Go to data permissions and revoke access to any table except Orders
3. Create a Question from the Orders table (note that you can download results)
4. Create another question from the Orders table and join it the first Question
5. Save- note that you cannot download results
7. Go to data permissions and grant DL access to the table you removed it from
8. Refresh your test question and you can now DL again

### Expected behavior

User should be able to download

### Logs

_No response_

### Information about your Metabase installation

```JSON
v51.3
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes https://github.com/metabase/metabase/issues/50304

In https://github.com/metabase/metabase/pull/49364 I changed `query->source-table-ids` to return sets of `table-ids` and `card-ids`. In that PR, I adjusted download perm enforcement to require full native perms if any `card-ids` were returned from that function, since we previously hadn't been considering referenced cards at all for download perms. (i.e. we were being overly permissive, allowing downloads even for queries joined to cards without download perms).

This was too restrictive, though, and ended up blocking downloads for some queries that should be allowed. The more correct behavior is to check download perms recursively for any referenced card IDs in the query, and go with the least-permissive value from that entire set.

I've fixed the logic and added a test to catch this case.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#50307** <a href="https://app.graphite.dev/github/pr/metabase/metabase/50307?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/metabase/metabase/50307?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: enterprise/backend/test/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions_test.clj [hunk 1]
```diff
@@ -80,8 +80,8 @@
         (testing "Native queries are unmodified"
           (is (= (native-download-query) (ee.qp.perms/apply-download-limit (native-download-query))))))
 
-      (with-download-perms! (mt/id) {:schemas {"PUBLIC" {(mt/id 'venues) :limited
-                                                         (mt/id 'checkins) :full}}}
```
Comment (noahmoss) [inline enterprise/backend/test/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions_test.clj:84]: Changed all these since keywords are used in `mt/id` everywhere else in the codebase

File: enterprise/backend/test/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions_test.clj [hunk 2]
```diff
@@ -183,24 +183,24 @@
...
+                                                           (mt/id :products)   :limited
+                                                           (mt/id :people)     :limited
+                                                           (mt/id :reviews)    :limited
+                                                           (mt/id :orders)     :limited}}}
           (streaming-test/do-test!
            "A user with limited download perms for a table has their query results limited for queries on that table"
            {:query      {:database (mt/id)
                          :type     :query
-                         :query    {:source-table (mt/id 'venues)
+                         :query    {:source-table (mt/id :venues)
```
Comment (escherize) [inline enterprise/backend/test/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions_test.clj:203]: thanks for updating these, much cleaner with keywords.

File: enterprise/backend/src/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions.clj [hunk 3]
```diff
@@ -32,16 +35,23 @@
   ;; Remove the :native key (containing the transpiled MBQL) so that this helper function doesn't think the query is
   ;; a native query. Actual native queries are dispatched to a different method by the :type key.
   (let [{:keys [table-ids card-ids native?]} (query-perms/query->source-ids (dissoc query :native))
-        table-perms (if (or native? (seq card-ids))
+        table-perms (if native?
```
Comment (escherize) [inline enterprise/backend/src/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions.clj:38]: the comment on 35 reads that this query cannot be native, should it be reworded? to something like:

```
  ;; Remove the :native key (containing the transpiled MBQL) so that this helper function doesn't mistakenly classify
  ;; the query as a native query. Actual native queries are dispatched to a different method by the :type key.
  ```
  
Actually, I don't see why the dissoc matters since a different defmethod will handle :native. If it's clear to you tho please update the comment.

File: enterprise/backend/src/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions.clj [hunk 4]
```diff
@@ -32,16 +35,23 @@
...
                       (set (map (fn [table-id]
                                   (data-perms/table-permission-for-user api/*current-user-id* :perms/download-results db-id table-id))
-                                table-ids)))]
-    ;; The download perm level for a query should be equal to the lowest perm level of any table referenced by the query.
-    (or (table-perms :no)
-        (table-perms :ten-thousand-rows)
+                                table-ids)))
+        card-perms  (set
+                     ;; If we have any card references in the query, check perms recursively
+                     (map (fn [card-id]
```
Comment (escherize) [inline enterprise/backend/src/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions.clj:47]: nit: naming anon functions makes stack traces easier to follow

```suggestion
                     (map (fn card-perms-lookup [card-id]
```

**Review by escherize — APPROVED** [review]

File: enterprise/backend/src/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions.clj (hunk 3 above)
Comment (noahmoss) [reply enterprise/backend/src/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions.clj:36]: Good point, the dissoc is unnecessary now, I've removed it
