### PR TITLE
No error message on preview api error

### LINKED ISSUE #40724: API error not handled in the query step preview
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/7429a962-197a-45ff-8972-b56e388efc15

### To Reproduce

1. Start a new GUI question
2. Select source table
3. Disable network
4. Click "preview" button

There's an API error and preview will stay in a loading state indefinitely.

### Expected behavior

API errors should be shown. Loading state should not be displayed

### Information about your Metabase installation

master, bee426d232

### Severity

P3

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/40724

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question → Sample Dataset → Orders
2. Disable network requests
3. Click the Preview button
4. Make sure an error message appears, not just a loading spinner

Additionally (and optionally): I've removed the buggy implementation of the height animation for the preview container. The browser is doing rendering a lot of things so the animation was very choppy, and it does not add much value. If this doesn't belong in this PR, I'm happy to remove it.

### Demo

Screenshot 2024-04-03 at 19 12 23

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.jsx [hunk 1]
```diff
@@ -106,4 +102,20 @@ function getPreviewHeightForResult(result) {
   return rowCount * 36 + 36 + 2;
 }
 
+function coerceError(err) {
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.jsx:105]: :pray: 

```suggestion
function coerceError(error) {
```

File: frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.unit.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+
+test("vizualization preview a custom error message when an error occurs (metabase#40724)", () => {
+  const message = "This is a custom message";
+  renderWithProviders(
+    <VisualizationPreview rawSeries={null} result={null} error={{ message }} />,
+  );
+  expect(screen.getByText(message)).toBeInTheDocument();
+});
+
+test("vizualization preview an error message when an error is passed from the results (metabase#40724)", () => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.unit.spec.tsx:24]:
```suggestion
test("vizualization preview should render an error message when an error is passed from the results (metabase#40724)", () => {
```

**Review by kamilmielnik — APPROVED** [review]
Works well :+1: 

Please double-check with the product team before removing the animation.
