### PR TITLE
Don't guess site url from requests to healthcheck endpoint

### LINKED ISSUE #16754: Site URL can sometimes be incorrectly defined during startup
**Describe the bug**
Continuation of #14819
Sometimes during startup (e.g. K8s pods), the `site-url` can incorrectly be detected from a health-checker or another request, which can then set the URL to something incorrect (like the server local IP).
This happens even if it is defined in `setting` table. Seems like it might be a race-condition between establishing an appdb connection and when a request comes in that makes it auto-guess the URL, which is then used instead of the value from appdb.

https://github.com/metabase/metabase/blob/ce939219f8a3e28ecb00deb232154780a1dcfcef/src/metabase/server/middleware/misc.clj#L34-L58

**Expected behavior**
1. Never auto-guess the URL unless Metabase is in setup-mode.
2. Never auto-guess if `MB_SITE_URL` is defined.

**Information about your Metabase Installation:**
Have seen this sporadically happen on many previous versions thru latest 39.4, but I cannot reproduce.

**Severity**
The Site URL is a critical part of a lot of functionality in Metabase.

### PR DESCRIPTION
**Pull request by noahmoss**
* Adds a check that the current endpoint isn't `/api/health`, which as far as I can tell should be the only endpoint used for healthchecks (is this correct?)
* Removes the check on `api/*current-user*`. Since this is an atom, this check was always passing since the value wasn't being dereferenced. And I don't think this check is relevant because a user isn't bound yet during initial setup of MB.
* Removed some unused function params
* Added some tests

Resolves #16754

### CODE REVIEW

**Review by dpsutton — APPROVED** [review]

File: src/metabase/server/middleware/misc.clj [hunk 1]
```diff
@@ -39,10 +39,11 @@
 ;;
 ;; Effectively the very first API request that gets sent to us (usually some sort of setup request) ends up setting
 ;; the (initial) value of `site-url`
-(defn- maybe-set-site-url* [{{:strs [origin x-forwarded-host host user-agent] :as headers} :headers, :as request}]
+(defn- maybe-set-site-url* [{{:strs [origin x-forwarded-host host user-agent]} :headers, uri :uri}]
   (when (and (mdb/db-is-set-up?)
              (not (public-settings/site-url))
-              api/*current-user* (or (nil? user-agent) ((complement clojure.string/includes?) user-agent "HealthChecker"))); Not setting URL if it's a healthcheck by ELB
+             (not= uri "/api/health")
```
Comment (robdaemon) [inline src/metabase/server/middleware/misc.clj:45]: 🙌🏻
