### PR TITLE
Force slack channel cache refresh when new token is saved

### LINKED ISSUE #23251: Slack setup doesn't work if channels cache was recently cleared
**Describe the bug**
A slack channels cache was added in #20570 to improve performance. The cache is only refreshed if it was not refreshed within the last 10 minutes. It is also cleared whenever a Slack token is deleted. This means that if you've deleted a Slack app within the last 10 minutes, you can't add a new one, because the cache will be empty and the check that the files channel exists will fail.

**To Reproduce**
1. Create a new Slack integration in Metabase using the instructions in the admin panel
2. Delete the Slack integration
3. Add the Slack integration again
4. See a "channel not found" error on save, even though the files channel exists

**Information about your Metabase Installation:**
Current master

**Severity**
p1/2? only workaround is to wait 10 minutes and try again

### PR DESCRIPTION
**Pull request by noahmoss**
If you've recently deleted a Slack token, the Slack channels cache is cleared. If you then try to save a new token within 10 minutes of adding the previous one, it will try to populate the cache, but will fail the `needs-refresh?` check and thus not work.

This PR fixes this by resetting the `slack-channels-and-usernames-last-updated!` when the Slack cache is cleared in addition to the cache itself.

Resolves #23251

### CODE REVIEW

File: test/metabase/integrations/slack_test.clj [hunk 1]
```diff
@@ -137,8 +137,8 @@
     (testing "should be able to fetch list of users and page"
       (http-fake/with-fake-routes {users-endpoint (comp mock-200-response mock-users-response-body)}
         (let [expected-result (map
-                              (comp #(str \@ %) :name)
-                              (concat (mock-users) (mock-users)))]
```
Comment (noahmoss) [inline test/metabase/integrations/slack_test.clj:141]: Unrelated indentation fix

**Review by dpsutton — APPROVED** [review]
we need the `backport` label as well
