### PR TITLE
Use correct filter value for region maps, fix tooltips

### LINKED ISSUE #14650: Drilling down by a Region Map assigns the wrong value to the filter
- Start off with a GUI question where you break out Count of Orders or Count of People by People.State
- Visualize it as a map (should happen automatically)
- Click on a state like Texas and select "View these Orders"
- The filter is incorrectly set to `State is Texas` instead of `State is TX`, so you won't see results
- If you manually change the filter value to `TX`, you'll see results.

I noticed that relatively recently we merged a change that made the tooltips for these maps "smarter" by replacing "TX" in the tooltip with "Texas," and I suspect that change is the cause of or at least related to this bug: you'll notice that if you visualize the same query as e.g. a bar chart instead, and try drilling down the same way, you won't encounter this bug.

wrong-state-value

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #14650

This PR fixes two small bugs in region maps:
1. Don't use the feature name for the dimension value. (#14650)
2. Display the column name in the tooltip. (I didn't see an issue for this)

~I added a Cypress test that covers both.~ I unskipped the repro and added an assertion for the tooltip.

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/ChartTooltip.jsx [hunk 1]
```diff
@@ -19,7 +19,10 @@ export default class ChartTooltip extends Component {
     }
     if (Array.isArray(hovered.data)) {
       // Array of key, value, col: { data: [{ key, value, col }], element, event }
-      return hovered.data;
+      return hovered.data.map(d => ({
+        ...d,
+        key: d.key || getFriendlyName(d.col),
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/components/ChartTooltip.jsx:24]: The choropleth visualization wasn't setting `key` in each `data` item. I added a fallback in the `ChartTooltip` rather than patching the specific issue.

Separately, it'd be nice to document exactly what these click object data structures should contain.

File: frontend/src/metabase/visualizations/components/ChoroplethMap.jsx [hunk 2]
```diff
@@ -254,10 +255,7 @@ export default class ChoroplethMap extends Component {
             column: cols[metricIndex],
             dimensions: [
               {
-                value:
-                  feature != null
-                    ? getFeatureName(feature)
-                    : row[dimensionIndex],
+                value: row[dimensionIndex],
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/components/ChoroplethMap.jsx:257]: The old code was wrong. We shouldn't use "feature name" in dimensions since data will be used for the tooltips.

File: frontend/src/metabase/visualizations/components/ChartTooltip.jsx (hunk 1 above)
Comment (daltojohnso) [reply frontend/src/metabase/visualizations/components/ChartTooltip.jsx:24]: Why use `getFriendlyName` vs using `d.col.name`?

**Comment by nemanjaglumac** [comment]
@paulrosenzweig there was a `.Reproduced` label on this issue.
Existing repro: https://github.com/metabase/metabase/pull/14665

File: frontend/src/metabase/visualizations/components/ChartTooltip.jsx (hunk 1 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/components/ChartTooltip.jsx:24]: I used `getFriendlyName` without thinking much about it since I saw that dimensions were using that in an adjacent code branch. It looks like `getFriendlyName` has logic to expand/translate aggregation names (e.g. `"avg"` => `` t`Average` ``) and falls back to `column.display_name`.

**Comment by paulrosenzweig** [comment]
@nemanjaglumac thanks for catching that! I removed the new test and unskipped the existing repro.

**Comment by flamber** [comment]
@paulrosenzweig As for 2: Looks like that would fix #12308, right?
image

**Comment by paulrosenzweig** [comment]
@flamber if I understand #12308 right, that was already fixed. 

### Before this PR
We showed multiple metrics but the labels were missing.

image

### After
The labels show up now.

image

File: frontend/src/metabase/visualizations/components/ChartTooltip.jsx (hunk 1 above)
Comment (daltojohnso) [reply frontend/src/metabase/visualizations/components/ChartTooltip.jsx:24]: Likely a rare edge case, but it seems like since `display_name` is user editable an admin could accidentally use the same `display_name` for two columns and cause a dup key problem here. Won't block on it, but figured it was worth noting.

**Review by daltojohnso — APPROVED** [review]

File: frontend/src/metabase/visualizations/components/ChartTooltip.jsx (hunk 1 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/components/ChartTooltip.jsx:24]: Hmm good point. We probably need to enforce uniqueness (within a given context) for all our display names.

**Comment by flamber** [comment]
@paulrosenzweig That's funny - so the extra metrics was added in 0.37.0, but then that also removed the column names in the tooltips, which is why probably didn't notice it.
I think we can say this officially fixes #12308 - and with a test to prevent regression too :superhero:

File: frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js [hunk 3]
```diff
@@ -121,19 +121,23 @@ describe("scenarios > visualizations > maps", () => {
...
-    cy.wait("@cardQuery");
     cy.get(".CardVisualization svg path")
-      .as("states")
-      .eq(22) // Texas
-      .click({ force: true });
+      .eq(22)
+      .as("texas");
+
+    // hover to see the tooltip
+    cy.get("@texas").trigger("mousemove");
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js:131]: TIL we can do this to trigger a tooltip ("mouseover" didn't work).
