### PR TITLE
Fix Bigquery can't sync materialized views

### LINKED ISSUE #42008: BigQuery - Can't sync materialized views since 1.49.0
### Describe the bug

Testing in 1.49.7.
Not able to successfully sync Materialized Views in BigQuery and run into the following error:

> java.lang.ClassCastException: class com.google.cloud.bigquery.AutoValue_MaterializedViewDefinition cannot be cast to class com.google.cloud.bigquery.StandardTableDefinition (com.google.cloud.bigquery.AutoValue_MaterializedViewDefinition and com.google.cloud.bigquery.StandardTableDefinition are in unnamed module of loader clojure.lang.DynamicClassLoader @4f5d587c)

<br>

Metadata for the materialized view within Admin Settings will not be brought in.
Attempting to query or browse the data will give a "no fields found" message. 

Screenshot 2024-04-29 at 5 51 25 PM

<br>
<br>

Tested syncing on **1.49.0** and encounter the same issue.
Syncing functions correctly **1.48.7**.

### To Reproduce

1. Create materialized view in BigQuery
2. Sync database

It doesn't matter whether this is an update to an existing materialized view, or a newly created one.

### Expected behavior

For the sync to function as it did prior to 1.49.0.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Mac OS X",
    "os.version": "13.5.1",
    "user.language": "en",
    "user.timezone": "America/Chicago"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "mysql",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-04-22",
      "tag": "v1.49.7",
      "hash": "f0ff786"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

P1 - Not able to sync Materialized Views or query them

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/42008

```(.getTableDefinition table)```
- returns: MaterializedViewDefinition if table is a materialized view ([src](https://github.com/googleapis/java-bigquery/blob/8fa6d279bc8dd8fc11fd7f0ebadcbeca7f88ef42/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/MaterializedViewDefinition.java#L24))
- returns: StandardTableDefinition if table is a normal table ([doc](https://cloud.google.com/java/docs/reference/google-cloud-bigquery/latest/com.google.cloud.bigquery.StandardTableDefinition))

Currently, we're annotation the returned type as `StandardTableDefinition`, which is wrong for materialized, and that's why we get the casting error.

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj [hunk 1]
```diff
@@ -329,12 +355,16 @@
...
                         (format "INSERT INTO %s (company, founded)
                                 VALUES ('Metabase', DATETIME('2014-10-10 00:00:00')),
                                 ('Tesla', DATETIME('2003-07-01 00:00:00')),
                                 ('Apple', DATETIME('1976-04-01 00:00:00'));"
-                                (fmt-table-name "partitioned_by_datetime"))
+                                (fmt-table-name "partition_by_datetime"))
+                        (format "CREATE MATERIALIZED VIEW %s AS
+                                SELECT company AS ev_company FROM %s WHERE founded = DATETIME('2003-07-01 00:00:00');"
+                                (fmt-table-name "mv_partition_by_datetime")
+                                (fmt-table-name "partition_by_datetime"))
```
Comment (calherries) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:367]: This tests the case that there's a materialized view with a range partition but doesn't test the case that there's a materialized view with a time partition. Since checking range partitions vs time partitions are defined in separate functions I think we should cover them both with tests, in case they evolve independently

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 2]
```diff
@@ -201,12 +220,12 @@
 (defmethod driver/describe-table :bigquery-cloud-sdk
   [_ database {table-name :name, dataset-id :schema}]
   (let [table                  (get-table database dataset-id table-name)
-        ^StandardTableDefinition tabledef (.getDefinition table)
+        ^TableDefinition       tabledef (.getDefinition table)
```
Comment (calherries) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:223]: Indentation was correct before

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj [hunk 3]
```diff
@@ -253,6 +257,27 @@
                    {:source-table (mt/id view-name)
                     :order-by     [[:asc (mt/id view-name :id)]]}))))))))
 
+(deftest sync-materialized-view-test
```
Comment (calherries) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:260]: Where did this come from?

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 4]
```diff
@@ -218,7 +237,7 @@
                ;; meaning this table is partitioned by ingestion time
                ;; so we manually sync the 2 pseudo-columns _PARTITIONTIME AND _PARTITIONDATE
                (and is-partitioned?
-                    (some? (.getTimePartitioning tabledef))
+                    (some? (tabledef->time-partition tabledef))
```
Comment (calherries) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:240]: potentially being pedantic here, but I _think_ this change isn't covered by tests

**Review by calherries — APPROVED** [review]
LGTM, I think the tests could be a little stronger but on the other hand, this stuff is unlikely to change

**Review by calherries — COMMENTED** [review]
Tests are failing though. I can't see what's wrong by inspection

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj (hunk 4 above)
Comment (qnkhuat) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:240]: it should be covered [here](https://github.com/metabase/metabase/blob/79097cfb24c92e01b399d8875f7b63936aaee06f/modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj#L412) no?

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj (hunk 3 above)
Comment (qnkhuat) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:260]: I'm not following the question. but I notice we don't have any sync materialized view test, so I added one.

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj (hunk 1 above)
Comment (qnkhuat) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:371]: added one here 1b5f9ca770

**Comment by qnkhuat** [comment]
@calherries test is fixed in [cd18cd0](https://github.com/metabase/metabase/pull/42092/commits/cd18cd06946ba3faf096c653a8c20f949d1b5455), strangely comparison using `case` does not work.

**Comment by calherries** [comment]
Right... `TableDefinition$Type/TABLE` is not a compile-time literal. https://clojuredocs.org/clojure.core/case

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj (hunk 4 above)
Comment (calherries) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:240]: I mean the `change` is not covered. That is a test for normal tables, not materialized views.

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj (hunk 3 above)
Comment (calherries) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:260]: ah cool makes sense
