### PR TITLE
Remove extra scrollbars from summarization sidebar

### LINKED ISSUE #45452: Too many scrollbars in summarize sidebar
### Describe the bug

image

### To Reproduce

1. Change viewport size to 1250x950
2. New question > Orders > join Products > visualize
3. Summarize

There are just too many scrollbars (3). This sidebar needs 1 scrollbar only.

### Information about your Metabase installation

master, 7e6adfa

### Severity

P3

### PR DESCRIPTION
**Pull request by oisincoveney**
Fixes #45452 

before:
image

after:
image

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Summarize.tsx [hunk 1]
```diff
@@ -69,26 +70,28 @@ const SummarizeInner = ({
...
-        stageIndex={stageIndex}
-        aggregations={aggregations}
-        onAddAggregations={handleAddAggregations}
-        onUpdateAggregation={handleUpdateAggregation}
-        onRemoveAggregation={handleRemoveAggregation}
-      />
-      <Divider my="lg" />
-      {hasAggregations && (
-        <SummarizeBreakoutColumnList
+    <Stack className={CS.overflowHidden} h="inherit" w="100%">
```
Comment (oisincoveney) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Summarize.tsx:73]: Not sure what happened here with the diff. Essentially I added an inner `Stack` that holds the `SummarizeAggregationItemList` and the `SummarizeBreakoutColumnList`, and acts as the scrollable area for the elements inside. This will ensure that the `Apply` and `Close` buttons stay at the bottom, while the main summarize area is scrollable

File: frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeContent/SummarizeBreakoutColumnList.tsx [hunk 2]
```diff
@@ -29,12 +27,7 @@ export const SummarizeBreakoutColumnList = ({
   onReplaceBreakouts,
   ...containerProps
 }: SummarizeBreakoutColumnListProps) => (
-  <Stack
-    h="100%"
-    spacing="0"
-    className={cx(CS.flex1, CS.overflowYScroll)}
-    {...containerProps}
-  >
+  <Stack h="100%" spacing="0" {...containerProps}>
```
Comment (oisincoveney) [inline frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeContent/SummarizeBreakoutColumnList.tsx:30]: We don't need this for either the main app or the SDK

File: frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeContent/SummarizeAggregationItemList.tsx [hunk 3]
```diff
@@ -28,12 +25,7 @@ export const SummarizeAggregationItemList = ({
   onRemoveAggregation,
   ...containerProps
 }: SummarizeAggregationItemListProps) => (
-  <Group
-    spacing="sm"
-    align="flex-start"
-    className={cx(CS.overflowYScroll)}
-    {...containerProps}
-  >
+  <Group spacing="sm" align="flex-start" {...containerProps}>
```
Comment (oisincoveney) [inline frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeContent/SummarizeAggregationItemList.tsx:28]: We don't need this for either the main app or the SDK

**Review by heypoom — APPROVED** [review]
