### PR TITLE
Handle exception in rollback better

### LINKED ISSUE #46111: SAVEPOINT ... does not exist
### Describe the bug

There's something weird with v50.x and MySQL as the app DB, after we do a DELETE the DB sends that message and stops the questions from running (returning an error in the query run endpoint)

### To Reproduce

I can't reproduce

### Expected behavior

This should not happen

### Logs

```
[c28010c7-1210-4dbe-8bab-ddf6b73af980] 2024-07-24T15:07:31-04:00 ERROR metabase.server.middleware.log POST /api/dashboard/28/dashcard/346/card/384/query 500 918.3 ms (10 DB calls) {:metabase-user-id 1} 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "(conn=4548157) SAVEPOINT 58dded4e-eb80-432d-99cb-6adbf96a1fe4 does not exist",
   :data
   {:toucan2/context-trace
    [["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}]
     ["resolve connection" {:toucan2.connection/connectable :default}]
     ["resolve connection" {:toucan2.connection/connectable nil}]
     {:toucan2.pipeline/rf
      #object[clojure.core$completing$fn__8528 0x73604ed9 "clojure.core$completing$fn__8528@73604ed9"]}
     ["with compiled query"
      {:toucan2.pipeline/compiled-query
       ["DELETE FROM `user_parameter_value` WHERE (`user_id` = ?) AND (`dashboard_id` = ?) AND (`parameter_id` = ?)"
        1
        28
        "50f949f9"]}]
     ["with built query"
      {:toucan2.pipeline/built-query
       {:delete-from [:user_parameter_value],
        :where [:and [:= :user_id 1] [:= :dashboard_id 28] [:= :parameter_id "50f949f9"]]}}]
     ["with resolved query" {:toucan2.pipeline/resolved-query {}}]
     ["with parsed args"
      {:toucan2.pipeline/query-type :toucan.query-type/delete.update-count,
       :toucan2.pipeline/parsed-args
       {:kv-args {:user_id 1, :dashboard_id 28, :parameter_id "50f949f9"}, :queryable {}}}]
     ["with model" {:toucan2.pipeline/model :model/UserParameterValue}]
     ["with unparsed args"
      {:toucan2.pipeline/query-type :toucan.query-type/delete.update-count,
       :toucan2.pipeline/unparsed-args
       (:model/UserParameterValue :user_id 1 :dashboard_id 28 :parameter_id "50f949f9")}]]},
   :at [org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory createException "ExceptionFactory.java" 62]}
  {:type java.sql.SQLSyntaxErrorException,
   :message "(conn=4548157) SAVEPOINT 58dded4e-eb80-432d-99cb-6adbf96a1fe4 does not exist",
   :at [org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory createException "ExceptionFactory.java" 62]}
  {:type org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException,
   :message "SAVEPOINT 58dded4e-eb80-432d-99cb-6adbf96a1fe4 does not exist",
   :at [org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException of "MariaDbSqlException.java" 34]}
  {:type java.sql.SQLException,
   :message "SAVEPOINT 58dded4e-eb80-432d-99cb-6adbf96a1fe4 does not exist",
   :at [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket "AbstractQueryProtocol.java" 1693]}],
 :trace
 [[org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket "AbstractQueryProtocol.java" 1693]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readPacket "AbstractQueryProtocol.java" 1555]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol getResult "AbstractQueryProtocol.java" 1518]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol executeQuery "AbstractQueryProtocol.java" 257]
  [org.mariadb.jdbc.MariaDbStatement executeInternal "MariaDbStatement.java" 356]
  [org.mariadb.jdbc.MariaDbStatement execute "MariaDbStatement.java" 500]
  [org.mariadb.jdbc.MariaDbConnection rollback "MariaDbConnection.java" 784]
  [com.mchange.v2.c3p0.impl.NewProxyConnection rollback "NewProxyConnection.java" 1007]
  [metabase.db.connection$do_transaction$thunk__42679 invoke "connection.clj" 146]
  [metabase.db.connection$do_transaction invokeStatic "connection.clj" 152]
  [metabase.db.connection$do_transaction invoke "connection.clj" 136]
  [metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection invokeStatic "connection.clj" 189]
  [metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection invoke "connection.clj" 162]
  [clojure.lang.AFn applyToHelper "AFn.java" 165]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 457]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2643]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [methodical.impl.combo.threaded$fn__18174$fn__18175$fn__18178 invoke "threaded.clj" 71]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144$fn__18148 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 invoke "core.clj" 2588]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18154 invoke "threaded.clj" 44]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [toucan2.connection$do_with_transaction_around_method_toucan2_connection_default invokeStatic "connection.clj" 249]
  [toucan2.connection$do_with_transaction_around_method_toucan2_connection_default invoke "connection.clj" 245]
  [clojure.lang.AFn applyToHelper "AFn.java" 165]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 457]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2643]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 58]
  [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 195]
  [toucan2.pipeline$transduce_execute$with_connection_STAR___21403 invoke "pipeline.clj" 74]
  [toucan2.connection$bind_current_connectable_fn$fn__21084 invoke "connection.clj" 104]
  [toucan2.connection$bind_current_connectable_fn$fn__21084 invoke "connection.clj" 104]
  [toucan2.connection$bind_current_connectable_fn$fn__21084 invoke "connection.clj" 104]
  [toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource invokeStatic "connection.clj" 18]
  [toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource invoke "connection.clj" 15]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.combo.threaded$fn__18174$fn__18175$fn__18176 invoke "threaded.clj" 70]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144$fn__18148 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18154 invoke "threaded.clj" 43]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invokeStatic "connection.clj" 118]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invoke "connection.clj" 106]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 55]
  [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 193]
  [metabase.db.connection$do_with_connection_primary_method_default invokeStatic "connection.clj" 132]
  [metabase.db.connection$do_with_connection_primary_method_default invoke "connection.clj" 130]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.combo.threaded$fn__18174$fn__18175$fn__18176 invoke "threaded.clj" 70]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144$fn__18148 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18154 invoke "threaded.clj" 43]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invokeStatic "connection.clj" 118]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invoke "connection.clj" 106]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 55]
  [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 193]
  [toucan2.connection$do_with_connection_primary_method_ invokeStatic "connection.clj" 204]
  [toucan2.connection$do_with_connection_primary_method_ invoke "connection.clj" 194]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.combo.threaded$fn__18174$fn__18175$fn__18176 invoke "threaded.clj" 70]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144$fn__18148 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18154 invoke "threaded.clj" 43]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invokeStatic "connection.clj" 118]
  [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invoke "connection.clj" 106]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 55]
  [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 193]
  [toucan2.pipeline$transduce_execute invokeStatic "pipeline.clj" 74]
  [toucan2.pipeline$transduce_execute invoke "pipeline.clj" 64]
  [clojure.lang.Var invoke "Var.java" 399]
  [toucan2.pipeline$transduce_compiled_query invokeStatic "pipeline.clj" 244]
  [toucan2.pipeline$transduce_compiled_query invoke "pipeline.clj" 240]
  [toucan2.pipeline$transduce_built_query invokeStatic "pipeline.clj" 252]
  [toucan2.pipeline$transduce_built_query invoke "pipeline.clj" 246]
  [toucan2.pipeline$transduce_query_primary_method_default invokeStatic "pipeline.clj" 272]
  [toucan2.pipeline$transduce_query_primary_method_default invoke "pipeline.clj" 269]
  [clojure.lang.AFn applyToHelper "AFn.java" 178]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 675]
  [clojure.core$partial$fn__5908 doInvoke "core.clj" 2639]
  [clojure.lang.RestFn applyTo "RestFn.java" 146]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [methodical.impl.combo.threaded$fn__18174$fn__18175$fn__18182 invoke "threaded.clj" 79]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144$fn__18148 invoke "threaded.clj" 23]
  [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
  [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
  [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6887]
  [clojure.core$reduce invoke "core.clj" 6869]
  [methodical.impl.combo.threaded$reducer_fn$fn__18144 invoke "threaded.clj" 21]
  [clojure.core$comp$fn__5876 doInvoke "core.clj" 2589]
  [clojure.lang.RestFn applyTo "RestFn.java" 146]
  [clojure.core$apply invokeStatic "core.clj" 675]
  [clojure.core$apply doInvoke "core.clj" 662]
  [clojure.lang.RestFn invoke "RestFn.java" 533]
  [methodical.impl.combo.threaded$combine_with_threader$fn__18154 doInvoke "threaded.clj" 46]
  [clojure.lang.RestFn applyTo "RestFn.java" 151]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 675]
  [clojure.core$apply doInvoke "core.clj" 662]
  [clojure.lang.RestFn invoke "RestFn.java" 533]
  [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 65]
  [methodical.impl.standard$invoke_multifn doInvoke "standard.clj" 47]
  [clojure.lang.RestFn invoke "RestFn.java" 594]
  [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 199]
  [toucan2.pipeline$transduce_query_STAR_ invokeStatic "pipeline.clj" 278]
  [toucan2.pipeline$transduce_query_STAR_ invoke "pipeline.clj" 274]
  [toucan2.pipeline$transduce_with_model invokeStatic "pipeline.clj" 293]
  [toucan2.pipeline$transduce_with_model invoke "pipeline.clj" 280]
  [toucan2.pipeline$transduce_parsed invokeStatic "pipeline.clj" 309]
  [toucan2.pipeline$transduce_parsed invoke "pipeline.clj" 295]
  [toucan2.pipeline$transduce_unparsed invokeStatic "pipeline.clj" 317]
  [toucan2.pipeline$transduce_unparsed invoke "pipeline.clj" 311]
  [toucan2.pipeline$transduce_unparsed_with_default_rf invokeStatic "pipeline.clj" 374]
  [toucan2.pipeline$transduce_unparsed_with_default_rf invoke "pipeline.clj" 368]
  [toucan2.delete$delete_BANG_ invokeStatic "delete.clj" 24]
  [toucan2.delete$delete_BANG_ doInvoke "delete.clj" 8]
  [clojure.lang.RestFn invoke "RestFn.java" 551]
  [metabase.models.user_parameter_value$upsert_BANG_ invokeStatic "user_parameter_value.clj" 49]
  [metabase.models.user_parameter_value$upsert_BANG_ invoke "user_parameter_value.clj" 33]
  [metabase.query_processor.dashboard$resolve_params_for_query invokeStatic "dashboard.clj" 149]
  [metabase.query_processor.dashboard$resolve_params_for_query invoke "dashboard.clj" 118]
  [metabase.query_processor.dashboard$process_query_for_dashcard invokeStatic "dashboard.clj" 182]
  [metabase.query_processor.dashboard$process_query_for_dashcard doInvoke "dashboard.clj" 163]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [medley.core$mapply invokeStatic "core.cljc" 243]
  [medley.core$mapply invoke "core.cljc" 237]
  [metabase.api.dashboard$fn__99414$fn__99418 invoke "dashboard.clj" 1231]
  [metabase.api.dashboard$do_with_dashboard_load_id invokeStatic "dashboard.clj" 308]
  [metabase.api.dashboard$do_with_dashboard_load_id invoke "dashboard.clj" 303]
  [metabase.api.dashboard$fn__99414 invokeStatic "dashboard.clj" 1230]
  [metabase.api.dashboard$fn__99414 invoke "dashboard.clj" 1222]
  [compojure.core$wrap_response$fn__53013 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__52997 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__53002 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 151]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [metabase.server.middleware.auth$enforce_authentication$fn__98468 invoke "auth.clj" 18]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [compojure.core$make_context$handler__53053 invoke "core.clj" 290]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 300]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 199]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 199]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 199]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [metabase.api.routes$fn__105149$fn__105150 invoke "routes.clj" 70]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__105429$fn__105430 doInvoke "routes.clj" 73]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [compojure.core$make_context$handler__53053 invoke "core.clj" 290]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 300]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__53006 invoke "core.clj" 153]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 199]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 199]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 199]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [compojure.core$make_context$handler__53053 invoke "core.clj" 290]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 300]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025$f__53026$respond_SINGLEQUOTE___53027 invoke "core.clj" 197]
  [compojure.core$make_context$fn__53057 invoke "core.clj" 301]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [compojure.core$routes$fn__53025$f__53026 invoke "core.clj" 198]
  [compojure.core$routes$fn__53025 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__101566 invoke "exceptions.clj" 107]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__101563 invoke "exceptions.clj" 96]
  [metabase.server.middleware.log$log_api_call$fn__107772$fn__107773$fn__107774 invoke "log.clj" 236]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
  [metabase.server.middleware.log$log_api_call$fn__107772$fn__107773 invoke "log.clj" 227]
  [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
  [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
  [metabase.server.middleware.log$log_api_call$fn__107772 invoke "log.clj" 226]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__113898 invoke "browser_cookie.clj" 40]
  [metabase.server.middleware.security$add_security_headers$fn__101522 invoke "security.clj" 240]
  [ring.middleware.json$wrap_json_body$fn__114157 invoke "json.clj" 64]
  [metabase.server.middleware.offset_paging$handle_paging$fn__87757 invoke "offset_paging.clj" 43]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__54545 invoke "json.clj" 83]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__114246 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__114265 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__70247 invoke "misc.clj" 60]
  [metabase.server.middleware.session$reset_session_timeout$fn__77370 invoke "session.clj" 552]
  [metabase.server.middleware.session$bind_current_user$fn__77336$fn__77337 invoke "session.clj" 446]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 425]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 408]
  [metabase.server.middleware.session$bind_current_user$fn__77336 invoke "session.clj" 445]
  [metabase.server.middleware.session$wrap_current_user_info$fn__77317 invoke "session.clj" 383]
  [metabase.server.middleware.session$wrap_session_id$fn__77289 invoke "session.clj" 259]
  [metabase.server.middleware.auth$wrap_static_api_key$fn__98476 invoke "auth.clj" 32]
  [ring.middleware.cookies$wrap_cookies$fn__114085 invoke "cookies.clj" 200]
  [metabase.server.middleware.misc$add_content_type$fn__70229 invoke "misc.clj" 28]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__70255 invoke "misc.clj" 77]
  [ring.middleware.gzip$wrap_gzip$fn__114127 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__70258 invoke "misc.clj" 94]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__113914 invoke "ssl.clj" 51]
  [metabase.server$async_proxy_handler$fn__70593 invoke "server.clj" 77]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
  [org.eclipse.jetty.server.Server handle "Server.java" 563]
  [org.eclipse.jetty.server.HttpChannel$RequestDispatchable dispatch "HttpChannel.java" 1598]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 753]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 501]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 287]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
  [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy runTask "AdaptiveExecutionStrategy.java" 421]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy consumeTask "AdaptiveExecutionStrategy.java" 390]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy tryProduce "AdaptiveExecutionStrategy.java" 277]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy run "AdaptiveExecutionStrategy.java" 199]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 411]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 969]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner doRunJob "QueuedThreadPool.java" 1194]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1149]
  [java.lang.Thread run nil -1]],
 :cause "SAVEPOINT 58dded4e-eb80-432d-99cb-6adbf96a1fe4 does not exist",
 :message "(conn=4548157) SAVEPOINT 58dded4e-eb80-432d-99cb-6adbf96a1fe4 does not exist"}
```

### Information about your Metabase installation

```JSON
v50.x
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nvoxland**
### Description

If the rollback call fails during error handling, the original error is lost. For example, troubleshooting #46111 seems like it would be easier with this PR.

This catches the exception in rollback and rethrows an error with both the actual error and the rollback error in it

### How to verify

Need to have a rollback call that fails for some reason. 

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/db/connection.clj [hunk 1]
```diff
@@ -143,7 +143,10 @@
                     (.commit connection))
                   result)
                 (catch Throwable e
-                  (.rollback connection savepoint)
+                  (try
+                    (.rollback connection savepoint)
+                    (catch Exception rollback-e (throw (ex-info (ex-message e) {:cause e :rollback-error rollback-e}))))
```
Comment (dpsutton) [inline src/metabase/db/connection.clj:148]: This line is getting pretty long. I'd break it up a bit, and also suggest this construction:
rename `e` to `txn-e` and then do
```clojure
(catch Throwable txn-e
  (try (.rollback connection savepoint)
       (catch Exception rollback-e
         (throw (ex-info "Error in transaction"
                         {:rollback-error rollback-e}
                         txn-e))))
  (throw txn-e))
```

And in the tests:

```clojure
(deftest rollback-error-handling
  (testing "rollback error handling"
    (let [real-conn (.getConnection ^DataSource mdb.connection/*application-db*)
          mock-conn (reify Connection
                      (rollback [_ _savepoint]
                        (throw (ex-info "Rollback error" {})))
                      (setAutoCommit [_ auto?]
                        (.setAutoCommit real-conn auto?))
                      (getAutoCommit [_]
                        (.getAutoCommit real-conn))
                      (setSavepoint [_]
                        (.setSavepoint real-conn))
                      (commit [_]
                        (.commit real-conn)))]
      (binding [t2.connection/*current-connectable* mock-conn]
        (let [e (is (thrown? Exception
                             (t2/with-transaction [_t-conn] (throw (ex-info "Actual error" {})))))]
          (def e e)
          (is (= "Error in transaction" (ex-message e)))
          (is (= "Rollback error" (-> e ex-data :rollback-error ex-message)))
          (is (= "Actual error" (-> e ex-cause ex-message))))))))
```

File: test/metabase/db/connection_test.clj [hunk 2]
```diff
@@ -16,31 +19,31 @@
...
+                                  (throw e)))))]
     (testing "inside transaction"
       (do-in-transaction
        (fn []
          (create-user! user-1)
          (is (user-exists? user-1))
          (testing "inside nested transaction"
-           ;; do this on a separate thread to make sure we're not deadlocking, see
-           ;; https://github.com/seancorfield/next-jdbc/issues/244
+            ;; do this on a separate thread to make sure we're not deadlocking, see
```
Comment (dpsutton) [inline test/metabase/db/connection_test.clj:45]: there's lots of noise in this diff. We should get your editor to agree with our comment indents and kick them out of this diff

File: src/metabase/db/connection.clj (hunk 1 above)
Comment (nvoxland) [reply src/metabase/db/connection.clj]: Mostly used your suggestion, what do you think of the new version?

File: test/metabase/db/connection_test.clj (hunk 2 above)
Comment (nvoxland) [reply test/metabase/db/connection_test.clj:45]: Yes, I need to get that figured in out in general. It doesn't seem to have an option to directly import the cljfmt settings from what I could tell on quick first-glance

In this case, the problem seems more in the the original code? Because I don't trust my IDE formatter, I'm running cljfmt before committing and that was what changed the formatting there. I reverted the changes for now, though.

Comment (noahmoss) [reply test/metabase/db/connection_test.clj:45]: Still looks a bit off — comments should generally be aligned with the following form. e.g. on these lines (44-45) the original indentation was correct.

cljfmt doesn't touch comments, which be the source of some issues — it'll move the code around but you might still need to manually fix comments. https://metaboat.slack.com/archives/CKZEMT1MJ/p1731704390488579

File: test/metabase/db/connection_test.clj [hunk 3]
```diff
@@ -16,31 +19,31 @@
   (fixtures/initialize :db))
 
 (deftest nested-transaction-test
-  (let [user-1                    (mt/random-email)
```
Comment (noahmoss) [inline test/metabase/db/connection_test.clj:19]: The indentation in this block was fine before. Generally in a `let` form (or values in a map) it's OK to align the values (i.e. the original code here) or use a single space for each one (i.e. what you've changed it to), as long as it's consistent within the form.

So don't feel the need to revert, but the original was OK too. If your editor changed this automatically I'd look into configuring it or else it'll be auto-correcting a lot of code.

File: test/metabase/db/connection_test.clj [hunk 4]
```diff
@@ -138,3 +141,24 @@
...
+                      (rollback [_ _savepoint]
+                        (throw (ex-info "Rollback error" {})))
+                      (setAutoCommit [_ auto?]
+                        (.setAutoCommit real-conn auto?))
+                      (getAutoCommit [_]
+                        (.getAutoCommit real-conn))
+                      (setSavepoint [_]
+                        (.setSavepoint real-conn))
+                      (commit [_]
+                        (.commit real-conn)))]
```
Comment (noahmoss) [inline test/metabase/db/connection_test.clj:158]: I think you can get this test to work without acquiring a real connection? Just mock all the other methods as well
```suggestion
    (let [mock-conn (reify Connection
                      (rollback [_ _savepoint]
                        (throw (ex-info "Rollback error" {})))
                      (setAutoCommit [_ _auto?])
                      (getAutoCommit [_] true)
                      (setSavepoint [_])
                      (commit [_]))]
```

If you do want to use a real connection, probably better to use `with-open` so that it gets automatically closed.

**Review by noahmoss — APPROVED** [review]

**Comment by paoliniluis** [comment]
Fixes https://github.com/metabase/metabase/issues/46111
