### PR TITLE
Mantine UI Regressions part 1

### LINKED ISSUE #54217: Blocking Visual Regressions introduced in the Mantine V7 upgrade
Container issue for visual regressions that could potentially block a major release

- [x] [EMB-138: Error/Danger button hover state shows brand color](https://linear.app/metabase/issue/EMB-138/errordanger-button-hover-state-shows-brand-color)
- [x] [ADM-343: Year Picker arrows not spaced correctly](https://linear.app/metabase/issue/ADM-343/year-picker-arrows-not-spaced-correctly)
- [x] [ADM-342: Month Picker light theme hover state](https://linear.app/metabase/issue/ADM-342/month-picker-light-theme-hover-state)
- [x] [ADM-339: Spacing on year picker is incorrect](https://linear.app/metabase/issue/ADM-339/spacing-on-year-picker-is-incorrect)
- [x] [ADM-338: Month picker not picking up correct colors with dark theme](https://linear.app/metabase/issue/ADM-338/month-picker-not-picking-up-correct-colors-with-dark-theme)
- [x] [EMB-136: API key value not visible](https://linear.app/metabase/issue/EMB-136/api-key-value-not-visible)
- [x] [ADM-335: Fix hover state in Date Picker Options - should be `brand` color](https://linear.app/metabase/issue/ADM-335/fix-hover-state-in-date-picker-options-should-be-brand-color)

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/54217
Closes EMB-138
Closes EMB-136
Closes ADM-332
Closes ADM-334
Closes ADM-335
Closes ADM-336
Closes ADM-338
Closes ADM-339
Closes ADM-340
Closes ADM-341
Closes ADM-342
Closes ADM-343
Closes ADM-344

### Description
Adjusts a lot of UI regressions found after the migration to mantine. Many were issues around using the incorrect css variables for colors when working with light and dark themes, and some issues were caused by poor migrations of components. 

### How to verify
The best way to verify these would be to examine the new loki screenshot references and ensure that things look reasonable. A more involved check could be to check out the branch, reset the changes in the loki/reference folder, and run the visual tests and examine the diffs. They should be scoped to minor positioning differences.

I've also recorded [a loom](https://www.loom.com/share/70c0aa34296c4e76ac9aa829607f01b3) to walk through the changes in the failed tests. 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/admin/settings/components/ApiKeys/SecretKeyModal.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ export const SecretKeyModal = ({
         disabled
         styles={{
           input: {
-            color: `black !important`,
+            color: `black`,
```
Comment (npfitz) [inline frontend/src/metabase/admin/settings/components/ApiKeys/SecretKeyModal.tsx:32]: The !important was causing the rule to not be applied (this happened elsewhere as well). Also, this should probably be converted to use CSS modules :/

**Review by sloansparger — APPROVED** [review]

**Review by uladzimirdev — APPROVED** [review]
MonthPicker LGTM :shipit:
