### PR TITLE
Hide pin action button when user can't pin

### LINKED ISSUE #20043: Don't show pins or helper on view-only collections
**Describe the bug**
Don't collection pins or helper on view-only collections

**To Reproduce**
1. Login as view-user and go to a collection - should not show helper, and should not show pins for dashboards (or any other object)
image

**Information about your Metabase Installation:**
Tested "rc2" commit `a29860c`

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #20043 

The `showPinnedAction` boolean includes whether or not the `onPin` function is defined. For view-only users, `onPin` is undefined.

The banner mentioned in the bug report is no longer shown, so nothing needed there.

**Testing**
1. Create a user and set their **Collection** permissions on a collection with unpinned items to **view only**
2. With this user navigate to the above collection and see that there no longer is a pin icon in the table

### CODE REVIEW

File: frontend/src/metabase/components/EntityItem.jsx [hunk 1]
```diff
@@ -138,7 +138,7 @@ function EntityItemMenu({
   }
   return (
     <EntityMenuContainer align="center">
-      {!isPinned && (
+      {showPinnedAction && (
```
Comment (kulyk) [inline frontend/src/metabase/components/EntityItem.jsx:141]: I now can't see the pin button with write-permissions to the collection. `showPinnedAction = onPin && isPinned`, so it means it should be shown for pinned items which is not the case.

Comment (daltojohnso) [reply frontend/src/metabase/components/EntityItem.jsx]: oops, misread that, added a second boolean, `showUnpinnedAction`

**Review by kulyk — APPROVED** [review]
