### PR TITLE
Fix custom columns in pivot tables

### LINKED ISSUE #14604: Custom Columns breaks Pivot Table
**Describe the bug**
Custom Columns from pre-aggregate added to Pivot Table rows section

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Custom Column `1+1` as "Should not be included"
3. Summarize Count by People.Source and Products.Category
image
4. Visualize as Pivot Table, noticed the Custom Column is included:
image

**Information about your Metabase Installation:**
Tested 0.38.0-rc4

### PR DESCRIPTION
**Pull request by camsaul**
The issue here was that the `qp.pivot` code was merging in *all* `:expressions` into the `:breakouts` list rather than just the expression that returned the pivot group. It was actually a simple fix but it took me a while to figure that out

Fixes #14604

### CODE REVIEW

File: src/metabase/query_processor/pivot.clj [hunk 1]
```diff
@@ -84,29 +86,30 @@
...
+    ;;TODO: `pivot-grouping` is not "magic" enough to mark it as an internal thing
+    (update-in query [:query :fields] concat [[:expression "pivot-grouping"]])
+    ;;TODO: replace this value with a bitmask or something to indicate the source better
+    (update-in query [:query :expressions] assoc :pivot-grouping [:abs bitmask])
+    ;; in PostgreSQL and most other databases, all the expressions must be present in the breakouts. Add a pivot
+    ;; grouping expression ref to the breakouts
+    (update-in query [:query :breakout] concat [[:expression "pivot-grouping"]])
+    (do
+      (log/tracef "Added pivot-grouping expression to query\n%s" (u/pprint-to-str 'yellow query))
+      query)))
```
Comment (camsaul) [inline src/metabase/query_processor/pivot.clj:102]: I added some extra logging here while I was working out what was happening

File: src/metabase/query_processor/pivot.clj [hunk 2]
```diff
@@ -84,29 +86,30 @@
...
 
 (defn- generate-queries
   "Generate the additional queries to perform a generic pivot table"
   [{{all-breakouts :breakout} :query, :keys [pivot-rows pivot-cols query], :as outer-query}]
   (try
-    (for [breakout-indices (breakout-combinations (count all-breakouts) pivot-rows pivot-cols)
-          :let             [group-bitmask    (group-bitmask (count all-breakouts) breakout-indices)
+    (for [breakout-indices (u/prog1 (breakout-combinations (count all-breakouts) pivot-rows pivot-cols)
+                             (log/tracef "Using breakout combinations: %s" (pr-str <>)))
```
Comment (camsaul) [inline src/metabase/query_processor/pivot.clj:109]: more extra logging

File: src/metabase/query_processor/pivot.clj [hunk 3]
```diff
@@ -84,29 +86,30 @@
...
-              (concat breakout (map (fn [expr] [:expression (name expr)])
-                                    (keys (get-in new-query [:query :expressions])))))))
+  (as-> query query
+    ;;TODO: `pivot-grouping` is not "magic" enough to mark it as an internal thing
+    (update-in query [:query :fields] concat [[:expression "pivot-grouping"]])
+    ;;TODO: replace this value with a bitmask or something to indicate the source better
+    (update-in query [:query :expressions] assoc :pivot-grouping [:abs bitmask])
+    ;; in PostgreSQL and most other databases, all the expressions must be present in the breakouts. Add a pivot
+    ;; grouping expression ref to the breakouts
+    (update-in query [:query :breakout] concat [[:expression "pivot-grouping"]])
```
Comment (camsaul) [inline src/metabase/query_processor/pivot.clj:99]: this line was the actual fix

File: test/metabase/query_processor_test/expressions_test.clj [hunk 4]
```diff
@@ -85,6 +86,37 @@
...
+        (is (= [[2 22] [3 59] [4 13]]
+               (mt/formatted-rows [int int]
+                 (mt/run-mbql-query venues
+                   {:expressions {"Price + 1" [:+ $price 1]
+                                  "1 + 1"     [:+ 1 1]}
+                    :aggregation [:count]
+                    :breakout    [[:expression "Price + 1"]]
+                    :order-by    [[:asc [:expression "Price + 1"]]]
+                    :limit       3}))))))))
+
```
Comment (camsaul) [inline test/metabase/query_processor_test/expressions_test.clj:119]: I initially thought this was an issue with expressions coming back even if they weren't in the `:fields` clause in general, so I wrote a bunch of tests because it seemed like we didn't have any for that specific case. That turned out to not be the issue. But it doesn't hurt to have the extra (unrelated) test coverage

**Review by robdaemon — APPROVED** [review]

File: src/metabase/query_processor/pivot.clj (hunk 3 above)
Comment (paulrosenzweig) [reply src/metabase/query_processor/pivot.clj]: 😬 oops I think I introduced this.
