### PR TITLE
fix Popover styles to avoid horizontal scroll on body

### LINKED ISSUE #43163: Animation happening when hovering between columns that prevents the column metadata from populating fast
### Describe the bug

There's a weird animation happening when I hover between columns

### To Reproduce

1) create a question and transform it into a model
2) then hover over the columns on the right, see the screen turning white'ish

### Expected behavior

It should not do any animation

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P3

### Additional context

Peek 2024-05-24 19-44

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/43163

### Description

Do not create horizontal scroll on wiht popover

### How to verify

- open models' metadata
- hover table columns close to the edge of the viewport
- notice **no** horizontal scroll in the bottom

### Demo

https://github.com/metabase/metabase/assets/125459446/04ea2543-9d33-4777-9c81-5b0b0e7d37bf

### Checklist

- no tests

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx [hunk 1]
```diff
@@ -903,7 +903,7 @@ class TableInteractive extends Component {
           }
         >
           <QueryColumnInfoPopover
-            placement="bottom-start"
+            position="bottom-start"
```
Comment (uladzimirdev) [inline frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx:906]: `QueryColumnInfoPopover` accepts `position`, not `placelement`

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/MetadataInfo/ColumnInfoPopover/ColumnInfoPopover.tsx#L10

**Review by romeovs — APPROVED** [review]

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx:906]: Oh my...
