### PR TITLE
Handle non UTF-8 encoded CSV uploads

### LINKED ISSUE #45689: Column names with special characters are created with encoded characters
### Describe the bug

I don't know why it happens with only this file and not if I generate a new one

### To Reproduce

1) just import this as a CSV
[colegios_alumnos_activos.csv](https://github.com/user-attachments/files/16257255/colegios_alumnos_activos.csv)

### Expected behavior

we should not create columns with special characters

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes https://github.com/metabase/metabase/issues/45689

### Description

~~This adds very rudimentary character set detection, and uses it to handle a "legacy" file encoding.~~

This adds a very mature library for handling character sets.

### CODE REVIEW

**Review by tsmacdonald — APPROVED** [review]
Seems reasonable to me; good test

File: src/metabase/upload.clj [hunk 1]
```diff
@@ -279,6 +281,30 @@
...
+          (let [bytes-read (.read input-stream buffer)]
+            (if (pos? bytes-read)
+              (do
+                (.handleData detector buffer 0 bytes-read)
+                (if (.isDone detector)
+                  (.getDetectedCharset detector)
+                  (recur)))
+              (do
+                (.dataEnd detector)
+                (.getDetectedCharset detector)))))))
```
Comment (tsmacdonald) [inline src/metabase/upload.clj:299]: This is the height of nitpickery but I'd maybe have something more like


```
(if (pos? bytes-read)
  (do ...
    (when-not (.isDone detector)
      (recur)))
  (.dataEnd detector))
(.getDetectedCharset detector)
```

(in other words, pulling the `.getDetectedCharset` down to simplify some of the if/do logic)

File: src/metabase/upload.clj [hunk 2]
```diff
@@ -279,6 +281,30 @@
...
+    (catch Exception _
+      ;; Just live with unrecognized characters
+      "UTF-8")))
```
Comment (tsmacdonald) [inline src/metabase/upload.clj:302]: Interested in when this would actually trigger

File: test_resources/csv/utf-8.csv [hunk 3]
```diff
@@ -0,0 +1,3 @@
+"Dirección";"País"
+"foo";"bar"
+
```
Comment (tsmacdonald) [inline test_resources/csv/utf-8.csv:3]: I was surprised these files weren't in the PR earlier but assumed they must have existed from before (or CI would fail). I take it CI failed, haha

File: deps.edn [hunk 4]
```diff
@@ -36,6 +36,7 @@
                                              :exclusions  [it.unimi.dsi/fastutil
                                                            org.slf4j/slf4j-api]}
   com.draines/postal                        {:mvn/version "2.0.5"}              ; SMTP library
+  com.github.albfernandez/juniversalchardet {:mvn/version "2.5.0"}
```
Comment (tsmacdonald) [inline deps.edn:39]:
```suggestion
  ; Detect the charset in uploaded CSV files
  com.github.albfernandez/juniversalchardet {:mvn/version "2.5.0"}
```

**Review by tsmacdonald — APPROVED** [review]
Agree it's safer to just use a lib.

I don't know what went into the 8kb buffer choice but I'm sure it's fine
