### PR TITLE
Fix appends for long column names

### LINKED ISSUE #44724: Cann append CSV with long column name
### Describe the bug

Many databases have modest limits in the length of the column names that they support, and they may truncate them silently.

The Upload feature uses the column name as the source of truth, and compares these to the normalized header values from an appended file, which will not have been truncated.

This can cause a mismatch and a false positive on a missing field.

### To Reproduce

1. Enable uploads.
2. Go to collection.
3. Upload a CSV file with a column containing 64 or more characters.
4. Open the model created by (3)
5. Attempt to append the same file to the model.

### Expected behavior

The append should succeed.

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Metabase version: 48+
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes https://github.com/metabase/metabase/issues/44724

### Description

This adds explicit truncation to the uploaded column names, to fix a spurious mismatch between the existing and appended schema.

This also fixes a few places where we were doing redundant normalization.

### CODE REVIEW

File: src/metabase/driver.clj [hunk 1]
```diff
@@ -963,6 +963,16 @@
   dispatch-on-initialized-driver
   :hierarchy #'hierarchy)
 
+(defmulti column-name-length-limit
+  "Return the maximum number of characters allowed in a column name, or `nil` if there is no limit."
+  {:changelog-test/ignore true, :added "0.49.0", :arglists '([driver])}
```
Comment (crisptrutski) [inline src/metabase/driver.clj:968]: I plan to backport this twice. Even though 48 is still affected, I suspect it will have no further releases.

File: src/metabase/upload.clj [hunk 2]
```diff
@@ -577,17 +577,17 @@
               [header & rows]    (cond-> (parse reader)
                                    auto-pk?
                                    without-auto-pk-columns)
-              normed-name->field (m/index-by (comp normalize-column-name :name)
+              normed-name->field (m/index-by (comp (partial normalize-column-name driver ) :name)
                                              (t2/select :model/Field :table_id (:id table) :active true))
-              normed-header      (map normalize-column-name header)
+              normalized-header  (for [h header] (normalize-column-name driver h))
```
Comment (crisptrutski) [inline src/metabase/upload.clj:582]: Might as well use a consistent name everywhere.

**Review by tsmacdonald — COMMENTED** [review]
A test would be really  nice

File: src/metabase/driver.clj (hunk 1 above)
Comment (crisptrutski) [reply src/metabase/driver.clj:968]: D'oh, thanks for catching.

**Comment by crisptrutski** [comment]
Testing was a good call, by using H2 I ran into a second issue - the maximum length of `metabase_field.name` values.

File: src/metabase/upload.clj [hunk 3]
```diff
@@ -41,11 +41,25 @@
 
 (set! *warn-on-reflection* true)
 
+(def ^:private max-field-name-length
+  "This tracks the size of the metabase_field.name field"
+  254)
+
+(def ^:private unique-field-name-buffer
```
Comment (crisptrutski) [inline src/metabase/upload.clj:48]: I'm not sure this is worth it, as it only ends up supporting `create` and not `update` (for now).

I don't really like the idea of the buffer - it can truncate things it didn't need to, and could end up getting too long again. A better solution would be a smarter version of `uniquify-names` that preserves a maximum length. Not sure if it's better to extend that complex util or write something minimal for our needs.

**Review by tsmacdonald — APPROVED** [review]
Looks reasonable to me :ship:

File: src/metabase/upload.clj (hunk 3 above)
Comment (crisptrutski) [reply src/metabase/upload.clj:48]: Decided to keep it for now. Can revisit if we work on the related bug.

File: src/metabase/driver.clj [hunk 4]
```diff
@@ -963,6 +963,16 @@
   dispatch-on-initialized-driver
   :hierarchy #'hierarchy)
 
+(defmulti column-name-length-limit
+  "Return the maximum number of characters allowed in a column name, or `nil` if there is no limit."
```
Comment (calherries) [inline src/metabase/driver.clj:967]: Perhaps this is a bit pedantic, but we could mention in the docstring for `column-name-length-limit` and `table-name-length-limit` that this is the maximum number of _single-byte_ characters, not characters in general. We currently use `u/slufigy` to convert non-ASCII characters to ASCII, but there's a future where we forget to do this.

Comment (crisptrutski) [reply src/metabase/driver.clj:967]: That's a good call out, this detail bothered me as well.

**Comment by calherries** [comment]
This fixes the issue for CSV upload tables created after this change lands, but doesn't solve the problem for any upload tables created previously. I think we should at least try and fix appends/replacements for any CSV files that were previously uploaded with long names too.

Repro steps:
1. Checkout before this change merged to master `git checkout fb4bbfa6e7`
2. Start Metabase, attach a Postgres DB, and enable uploads
3. Upload a CSV with a long name (greater than 63 characters for Postgres)
4. Checkout after this change `git checkout dd7996b756`
5. Try to append to the CSV table created in step 3 with the same file

If you remove the ` unique-field-name-buffer` it fixes the issue in this case, like this:

```diff
diff --git a/src/metabase/upload.clj b/src/metabase/upload.clj
index c5e2ba7076..263b23801a 100644
--- a/src/metabase/upload.clj
+++ b/src/metabase/upload.clj
@@ -59,7 +59,7 @@
     (u/slugify (str/trim raw-name)
                (let [column-limit (some-> driver driver/column-name-length-limit)
                      max-len      (min-safe column-limit max-field-name-length)]
-                 {:max-length (- max-len unique-field-name-buffer)}))))
+                 {:max-length max-len}))))
 
 (def auto-pk-column-name
   "The lower-case name of the auto-incrementing PK column. The actual name in the database could be in upper-case."
```

Of course the downside is that we don't have a buffer anymore, but since there's not a clear case for its existence, I think it's better to remove it. And if we really want a buffer in the future we should introduce it in a way that doesn't break existing CSV uploads.

**Comment by crisptrutski** [comment]
Good catch - I tested that use case only before adding the buffer. It should have had a test.

Regarding it lacking a use case, the buffer was needed to fix behavior with exactly matching columns in the initial upload. We had tests for shorter columns and one would expect that property to carry over. I agree that gracefully handling existing uploads is more important though.

The improvement mentioned in my earlier comment, of replacing the uniquify util to preserve length, will also fix this issue, without the regression on initial uploads, and solving the long matching prefix problem at the same time.

Since it's not that complicated, I'd rather roll forward rather than revert.

**Comment by crisptrutski** [comment]
We actually did have a test which "should" have caught this issue, but unfortunately since we rely on using an intermediate "start" CSV file to test appending the issues cancelled out. Perhaps it's worth tweaking these tests so that we can build the initial table directly, which will also be more efficient.
