### PR TITLE
Fix selector scroll jankyness

### LINKED ISSUE #5829: Double scrollbars in data selector popover
This is on Chrome on our Stats instance:

screen shot 2017-08-28 at 11 47 55 am

### LINKED ISSUE #6969: Select popover scrolling weirdness
The title of this description reads like a tag cloud, but what I'm seeing is that when you go to map a dashboard filter to a field in a saved question, when the scroll down a bit, and then try to scroll up just a little bit, the scroll bar jumps all the way back up to the top of the list:

scrolling problems

### LINKED ISSUE #8656: Search bar focus, can't scroll filter list
- Safari 12.0.1
- macOS Mojave 10.14.1
- Metabase 0.30.4-0.31.2

Reproduce:
- New question > custom > open any table with 10+ columns to filter (or zoom the interface to make it bigger). Try to scroll when search bar is active.

P.S As far as I can say it's not a problem in Chrome

P.P.S I want to say thank you guys, your project helping many people around the world to be a successful company and you should be proud of it ❤️ 

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by flamber**
This feels a little hacky, but it is way less ugly than before and behaves more sane.
I could use an adult (Paul? :wink:) to validate that it's not causing some unforeseen problem.

And yes, Firefox also added a x-scroll, which made one of the y-scrollbars even more difficult to use.
I have manually scrolled to the right, so it shows both y-scrollbars.
**Before:**
image
image

**After:**
image
image

Fixes #5829 - double-scrollbars
Fixes #6969 - weird scroll-to-top on scroll-up on table/field
And probably also fixes #8656, but I don't have Safari, so I could use a hand testing

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/DataSelector.jsx [hunk 1]
```diff
@@ -859,12 +859,14 @@ const TablePicker = ({
...
     return (
-      <div>
+      <div style={{ width: 300, overflowY: "auto" }}>
         <AccordionList
           id="TablePicker"
           key="tablePicker"
           className="text-brand"
           sections={sections}
+          maxHeight={Infinity}
+          width={"100%"}
```
Comment (paulrosenzweig) [inline frontend/src/metabase/query_builder/components/DataSelector.jsx:869]: Do we need these `width={"100%"}`? It seems to be working for me without, but I probably missed some cases.

**Review by paulrosenzweig — APPROVED** [review]
LGTM! I still see a horizontal scroll in Safari (13.1.1) in the dimension picker. I played around a little, but I don't think it's worth working around now. It's pretty clearly a Safari bug and not causing huge issues. If I uncheck and recheck the width in inspector, the issue resolves 🤷.

image

File: frontend/src/metabase/query_builder/components/DataSelector.jsx (hunk 1 above)
Comment (flamber) [reply frontend/src/metabase/query_builder/components/DataSelector.jsx:869]: Yes, since `width:100%` is the full width without the scrollbar. That was why I called it hacky, since it's doesn't feel clean, but that's what you get when you mix CSS, JS and React I guess.

In Firefox, I specifically noticed it in Native variable sidebar, when it was showing more elements than what would fit in the Popover (like I showed in the screenshots).
If I remove the width, then it looks okay, but hovering the elements will show it's overflowing on the right, because of how scrollbar-width is calculated differently.

Let me do a bit more of testing, just so I'm totally sure about everything, since this is such a prominent function.
