### PR TITLE
fix(sdk): Fix unmapped theme colors

### LINKED ISSUE #46648: Add missing color mapping to the SDK
### Describe the bug

After merging 2 milestones of [[Epic] Re-design transparent theme for static embedding and public links](https://github.com/metabase/metabase/issues/43838#top), some SDK color mappings are missing.

image

### To Reproduce

1. Run the SDK in dev mode with:
    ```
    yarn build-release:cljs && yarn build-embedding-sdk:watch
    ```
1. After the bundle is built, run shoppy app with:
    ```
    yarn dev:link && yarn dev
    ```
1. Vistit http://localhost:3004/admin/products/1
1. Click on a bar in the chart
1. Click the date filter
1. See the date filter popover

### Expected behavior

Date filter popover background should be what's define in the SDK's `colors.background`

### Logs

_No response_

### Information about your Metabase installation

```JSON
master @ 5e549cf5acd4dbd5e316b8577bfb68cf64d5ec7f
```

### Severity

blocking

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/46648

### Description

Add missing color mappings for some of the new semantic colors

### How to verify

Follow the repro in #46648

#### Before
image

#### After (move this into a PR description)
image

### Checklist

- [ ] ~Tests have been added/updated to cover changes in this PR~

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/lib/theme/embedding-color-palette.ts [hunk 1]
```diff
@@ -13,22 +13,35 @@ import { getEmbeddingChartColors } from "./get-embedding-chart-colors";
...
-  background: "bg-white",
-  "background-hover": "bg-light",
-  shadow: "shadow",
-  positive: "success",
-  negative: "danger",
+  brand: ["brand"],
+  border: ["border"],
+  filter: ["filter"],
+  summarize: ["summarize"],
+  "text-primary": ["text-dark", "text-primary"],
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/lib/theme/embedding-color-palette.ts:37]: Modify the structure, so some colors could be mapped to more CSS custom properties.

File: enterprise/frontend/src/embedding-sdk/lib/theme/embedding-color-palette.ts [hunk 2]
```diff
@@ -45,19 +58,20 @@ const originalColors = { ...colors };
...
-    return originalColors;
-  }
-
   const mappedSdkColors = Object.fromEntries(
     Object.entries(sdkColors)
-      .map(([key, value]) => [
-        SDK_TO_MAIN_APP_COLORS_MAPPING[key as MappableSdkColor],
-        value,
-      ])
+      .flatMap(([key, value]) => {
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/lib/theme/embedding-color-palette.ts:66]: just a change to support the new value as an array

File: enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts [hunk 3]
```diff
@@ -56,10 +56,12 @@ export function getEmbeddingThemeOverride(
       const color = theme.colors[name as MetabaseColor];
 
       if (color && typeof color === "string") {
-        const themeColorName =
+        const themeColorNames =
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts:59]: just a change to support the new value as an array

File: frontend/src/metabase/styled-components/theme/css-variables.ts [hunk 4]
```diff
@@ -23,7 +23,21 @@ type MetabaseComponentThemeKey = FlattenObjectKeys<MetabaseComponentTheme>;
 export function getMetabaseCssVariables(theme: MantineTheme) {
   return css`
     :root {
-      ${getDesignSystemCssVariables(theme)}
+      --mb-default-font-family: "${theme.fontFamily}";
```
Comment (WiNloSt) [inline frontend/src/metabase/styled-components/theme/css-variables.ts:26]: make it obvious which function is used for which app.

- `getMetabaseCssVariables` for the main app and
- `getMetabaseSdkCssVariables` for the SDK
So there would be no confusion what CSS custom properties is for which app.

the main app, for example, has no ability to override these colors:

https://github.com/metabase/metabase/blob/35d1f6e9b48f24c2af057d09dd52e59d5e86e9ed/enterprise/frontend/src/embedding-sdk/lib/theme/embedding-color-palette.ts#L37-L44

so, it's unnecessary to set them as CSS custom properties.

File: frontend/src/metabase/styled-components/theme/css-variables.ts [hunk 5]
```diff
@@ -23,7 +23,21 @@ type MetabaseComponentThemeKey = FlattenObjectKeys<MetabaseComponentTheme>;
...
+
+      /* Semantic colors */
+      --mb-color-brand: ${theme.fn.themeColor("brand")};
+      --mb-color-summarize: ${theme.fn.themeColor("summarize")};
+      --mb-color-filter: ${theme.fn.themeColor("filter")};
```
Comment (WiNloSt) [inline frontend/src/metabase/styled-components/theme/css-variables.ts:31]: we only use these 3 colors dynamically in the main app via CSS custom properties, other colors `accentx` aren't referenced from CSS custom properties, so we don't need to define them here.

File: frontend/src/metabase/styled-components/theme/css-variables.ts [hunk 6]
```diff
@@ -37,70 +51,21 @@ export function getMetabaseCssVariables(theme: MantineTheme) {
...
-    --mb-color-filter: ${theme.fn.themeColor("filter")};
-    --mb-color-bg-error: ${color("bg-error")};
-    --mb-color-bg-medium: ${theme.fn.themeColor("bg-medium")};
-    --mb-color-bg-night: ${color("bg-night")};
-    --mb-color-text-white: ${theme.fn.themeColor("text-white")};
-    --mb-color-success: ${theme.fn.themeColor("success")};
-    --mb-color-summarize: ${theme.fn.themeColor("summarize")};
-    --mb-color-warning: ${theme.fn.themeColor("warning")};
+    /* Dynamic colors from SDK */
+    ${Object.entries(SDK_TO_MAIN_APP_COLORS_MAPPING).flatMap(
```
Comment (WiNloSt) [inline frontend/src/metabase/styled-components/theme/css-variables.ts:60]: remove all the colors and only define necessary custom properties. Since these are the only dynamic values, we don't need to override more than necessary. e.g. we don't support overriding `success` yet, so defining `--mb-color-success: ${theme.fn.themeColor("success")};` does nothing.

File: enterprise/frontend/src/embedding-sdk/lib/theme/embedding-color-palette.ts [hunk 7]
```diff
@@ -45,19 +58,20 @@ const originalColors = { ...colors };
  * @param appPalette color palette from the admin appearance settings
  */
 export function getEmbeddingColorPalette(
-  sdkColors?: MetabaseColors,
+  sdkColors: MetabaseColors = {},
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/lib/theme/embedding-color-palette.ts:61]: This fixes the issue where passing an empty colors `colors: {}` results in wrong colors.

If you override `brand` color on the instance and pass `colors: {}`, previously, the brand color would turn blue instead of your set `brand` color.

File: enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.unit.spec.ts [hunk 8]
```diff
@@ -24,7 +24,9 @@ describe("Transform Embedding Theme Override", () => {
       colors: {
         brand: expect.arrayContaining(["hotpink"]),
         "text-dark": expect.arrayContaining(["yellow"]),
+        "text-primary": expect.arrayContaining(["yellow"]),
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.unit.spec.ts:27]: You can see from the new mapping that `text-primary` will map to both:
- `text-dark`
- `text-primary`

https://github.com/metabase/metabase/blob/7b68b42d9452afd4db37fc6d776d556d38113fde/enterprise/frontend/src/embedding-sdk/lib/theme/embedding-color-palette.ts#L41

**Review by heypoom — APPROVED** [review]
I really like the approach here! I like how it makes it explicit which overrides is specifically for the SDK and isolates it - so non-SDK values can remain in `colors.module.css` - nice.

(I was thinking about using CSS variables to override the value of `--mb-color-bg-white` based on `--mb-color-background`, but I think this approach is much more explicit.)

PS. I [tested Shoppy](https://www.loom.com/share/563f7f7134d3419ba9251bac2617346f?sid=b313c273-6795-4801-967a-70dfe90679f1) with this PR and it works as expected. The datepicker range issue we'll solve in a separate PR.

File: frontend/src/metabase/styled-components/theme/css-variables.ts [hunk 9]
```diff
@@ -37,70 +51,37 @@ export function getMetabaseCssVariables(theme: MantineTheme) {
...
```
[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/styled-components/theme/css-variables.ts:60]: ah... I should have added the semicolon at the end. Maybe Emotion helps this under the hood, but it wouldn't hurt to be explicit.

[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/styled-components/theme/css-variables.ts:60]: Fixed with 6890601009a305b3afd981d7539f768baf4ba28c

**Review by albertoperdomo — APPROVED** [review]
