### PR TITLE
Format Pie Chart Legend Labels as Month, YYYY

### LINKED ISSUE #21505: Pie chart in static viz renders timestamps in different format than the chart
**Describe the bug**
When sending a pie chart as a subscription, the time field is rendered as a YYYY-MM-DD with timezone instead of the value that is rendered on the chart, which lead me to think this is due to https://github.com/metabase/metabase/issues/21504

**Logs**
No logs

**To Reproduce**
1) Build a pie chart with the following: Orders-> sum of quantity per Created_at (month)
2) add the pie chart to a dashboard
3) go to dashboard subcription and send a test email with this pie chart
4) see the series getting rendered as a timestamp with timezone instead of the short date

**Expected behavior**
See the exact same pie chart series that are shown on the Metabase web application

**Screenshots**
This is the chart on the dashboard
image

But this is the chart on the subscription
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgres 14
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
Completeness issue clearly

**Additional context**
NA

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes: https://github.com/metabase/metabase/issues/21505

On the backend, the pie chart legend is not rendered in the javascript, it is instead re-created server side as a set
of html elements. This means "YYYY-MM-DD" formatted dates do not get passed through the frontend code responsible for formatting date times (I believe this is done with a library called 'moment.js'). And, since the SVG cannot contain html foreignObjects (the backend SVG renederer 'batik' ignores foreign objects), the legend is left as a responsiblility for Clojure land.

This PR adds a `format-month` function to handle this case.

Note that the linked issue also suggests that it may be related to #21504, but it is in fact, a bit different. In both cases, the row data ultimately passed to the component (either in the frontend, or static-viz) has the shape:

```clojure
[["2016-04-01T00:00:00Z" 2]
 ["2016-05-01T00:00:00Z" 75]
 ["2016-06-01T00:00:00Z" 255]
 ["2016-07-01T00:00:00Z" 317]
 ["2016-08-01T00:00:00Z" 594]
 ["2016-09-01T00:00:00Z" 495]
 ["2016-10-01T00:00:00Z" 732]
 ["2016-11-01T00:00:00Z" 448] ... ]
```
Any component on the frontend can adjust how the timestamp is displayed using moment js and/or metabase metric/dimension formatting utils, but in the world of static-viz, we cannot render the legend in the component, and so don't have the timestamps formatted in that component. The data sent in is correct in both cases, the formatting was missed in the static viz case.

## Current caveats with this approach:

- doesn't consider localization
- adjusted the html to use a table instead of a div full of spans and the formatting could use some tweaks
- assumes any string that is parse-able into a Jave DateTime object will be displayed in this Month, Year format, which might not be true in all cases

### before
image

### after
image

### CODE REVIEW

File: src/metabase/pulse/render/body.clj [hunk 1]
```diff
@@ -247,15 +247,19 @@
...
   (let [unit (or unit :default)]
-    (or (get-in override-date-styles [date-style unit])
-        (get-in default-date-styles [unit])
-        date-style)))
+    (cond-> (or (get-in override-date-styles [date-style unit])
+                (get-in default-date-styles [unit])
+                date-style)
+      (not= date-separator "/") (str/replace #"/" date-separator)
+      date-abbreviate (-> (str/replace #"MMMM" "MMM")
+                          (str/replace #"EEEE" "E")))))
```
Comment (adam-james-v) [inline src/metabase/pulse/render/body.clj:262]: If the static-viz settings have `{:date-abbreviate true}`, we want to adjust the formatter to respect this. String replacing these covers such a case.

File: src/metabase/pulse/render/body.clj [hunk 2]
```diff
@@ -272,7 +276,7 @@
   [col-settings col]
   (-> (m/map-keys (fn [k] (-> k name (str/replace #"-" "_") keyword)) col-settings)
       (backfill-currency)
-      (u/update-if-exists :date_style update-date-style (:unit col))))
+      (u/update-if-exists :date_style update-date-style (:unit col) col-settings)))
```
Comment (adam-james-v) [inline src/metabase/pulse/render/body.clj:279]: `col-settings` here has a shape like this: 

```clojure
#:metabase.shared.models.visualization-settings{:date-style "YYYY/M/D"
                                                :date-separator "-"
                                                :date-abbreviate true
                                                :time-style "HH:mm"
                                                :time-enabled "minutes"}
```

Which is a map of viz-settings that correspond to data options a user has specified in the visualization UI. It gets passed in to `update-date-style` which I modified to change the date style format in a way that respects those settings, where previously it did not.

File: src/metabase/pulse/render/body.clj [hunk 3]
```diff
@@ -397,8 +401,38 @@
...
+                   [:td percentage]])))]
+    (if (< (count legend-entries) 8)
+      (table-fn legend-entries)
+      [:table (into [:tr]
+                    (map (fn [some-entries]
+                           [:td {:style (style/style {:padding-right  "20px"
+                                                      :vertical-align "top"})}
+                            (table-fn some-entries)])
+                         (split-at (/ (count legend-entries) 2) legend-entries)))])))
+
```
Comment (adam-james-v) [inline src/metabase/pulse/render/body.clj:433]: The donut legend is given a list of entries which are expected to look like `{:label "some label, timestamp or any string" :percentage "42%" :color "#004412"}`. I pulled this out into its own function to keep the :categorical/donut method a bit easier to follow.

One thing of note in this function is an (arbitrary) choice to split the legend into 2 columns when the count is greater than 8 entries, where the list is just split in half. So, this means a legend of 8 entries will render in a single column, but a legend of 9 entries will render in 2 columns (the first has 5 entries).

Since that number is arbitrary, it can be changed if needed.

Additionally, I didn't put any logic into cases where 3 columns might make sense, its 1 or 2, and that's it. Not certain it's a perfect solution, but seems reasonable to me.

Comment (adam-james-v) [reply src/metabase/pulse/render/body.clj:433]: I've also attempted to adjust the styling of the elements here (used a table to get better alignment when label names have variable width), but I'm not 100% happy with the 'magic number' nature of the pixel values here. Would be open to suggestions on cleanup here.

File: src/metabase/pulse/render/datetime.clj [hunk 4]
```diff
@@ -11,33 +11,107 @@
...
+  "Returns `true` if the string `s` is parseable as a datetime.
+
+  `(temporal-string? \"asdf\")` -> false
+  `(temporal-string? \"2020-02-02\")` -> true"
+  [s]
+  (boolean
+    (try
+      (u.date/parse s)
+      (catch Exception _e false))))
+
```
Comment (adam-james-v) [inline src/metabase/pulse/render/datetime.clj:24]: Use this to make sure legend labels like "asdf" don't get put through the temporal string formatting. Open to a better way than to use a try catch.

File: src/metabase/pulse/render/datetime.clj [hunk 5]
```diff
@@ -11,33 +11,107 @@
...
+             :day-of-week     (day-of-week s abbreviate) ;; s is just a number as a string here
+             :month-of-year   (month-of-year s abbreviate)
+             :quarter-of-year (format "Q%s" s)
+             :hour-of-day     (hour-of-day s (str/replace (or time-style "h a") #"A" "a"))
+
+             (:week-of-year :minute-of-hour :day-of-month :day-of-year) (x-of-y s)
+             ;; TODO: probably shouldn't even be showing sparkline for x-of-y groupings?
+
+             ;; for everything else return in this format
+             (reformat-temporal-str timezone-id s "MMM d, yyyy"))))))
```
Comment (adam-james-v) [inline src/metabase/pulse/render/datetime.clj:114]: I've re-worked this function somewhat to optionally use `viz-settings`. I did this because prior, only column :unit data was used to switch cases, but the column unit is not sufficient. User selected viz-settings are also required (eg. 'abbreviate' boolean changes how Month names should be rendered).

While I was here, I changed the 'x-of-y' behaviours too, because we allow a user to make changes in the UI for those, we should (try) to respect those settings in static-viz too.

One thing I don't know about is if I have done the right thing handling, for example, :day-of-week. The string `s` being passed in that case is actually something like "2" (which means "Tuesday", regardless of the app's start-of-week setting). It's in the same category of 'temporal' rendering, but it is NOT actually an ISO-8601 string in this case. That's also true for `:month-of-year`, `:quarter-of-year`, `:hour-of-day`.

**Review by adam-james-v — COMMENTED** [review]
I've done a bit of self review to highlight some choices/reasons for things, as well as some areas where my confidence is a bit lower, and some eyes/advice would be appreciated.

File: src/metabase/pulse/render/body.clj (hunk 3 above)
Comment (dpsutton) [reply src/metabase/pulse/render/body.clj:433]: I'm surprised to see nested tables as a solution. Can we not express this in a single table? `table-fn` returns a table and all of this is nested inside of :table > :tr > :td

File: src/metabase/pulse/render/datetime.clj [hunk 6]
```diff
@@ -11,33 +11,107 @@
...
+  (let [n (int (read-string int-str))]
+    (case (mod n 10)
+      1 (tru "{0}st" n)
+      2 (tru "{0}nd" n)
+      3 (tru "{0}rd" n)
+      (tru "{0}th" n))))
+
+(defn- hour-of-day
+  [s time-style]
+  (let [n (int (read-string s))
```
Comment (dpsutton) [inline src/metabase/pulse/render/datetime.clj:73]: `read-string` is 100% wrong. If you want to get a numeric value use a proper parse function. Clojure 1.11.x now has `parse-long`, or static methods from java `(Long/parseLong "123")`

File: src/metabase/pulse/render/datetime.clj [hunk 7]
```diff
@@ -11,33 +11,107 @@
...
+     "4" {:full (tru "Wednesday") :abbreviated (tru "Wed")}
+     "5" {:full (tru "Thursday") :abbreviated (tru "Thu")}
+     "6" {:full (tru "Friday") :abbreviated (tru "Fri")}
+     "7" {:full (tru "Saturday") :abbreviated (tru "Sat")}}
+    (if abbreviate
+      [s :abbreviated]
+      [s :full])))
+
+(defn- month-of-year
+  [s abbreviate]
```
Comment (dpsutton) [inline src/metabase/pulse/render/datetime.clj:43]: I think this could better be done as 
```clojure
datetime=> (let [fmtr (java.time.format.DateTimeFormatter/ofPattern "MMMM")]
             (.format fmtr (java.time.Month/of 2)))
"February"
datetime=> (let [fmtr (java.time.format.DateTimeFormatter/ofPattern "MMM")]
             (.format fmtr (java.time.Month/of 2)))
"Feb"
datetime=> (java.util.Locale/setDefault java.util.Locale/FRENCH)
nil
datetime=> (let [fmtr (java.time.format.DateTimeFormatter/ofPattern "MMMM")]
             (.format fmtr (java.time.Month/of 2)))
"février"
datetime=> (let [fmtr (java.time.format.DateTimeFormatter/ofPattern "MMM")]
             (.format fmtr (java.time.Month/of 2)))
"févr."
```

File: src/metabase/pulse/render/datetime.clj [hunk 8]
```diff
@@ -11,33 +11,107 @@
...
+  (boolean
+    (try
+      (u.date/parse s)
+      (catch Exception _e false))))
+
 (defn- reformat-temporal-str [timezone-id s new-format-string]
   (t/format new-format-string (u.date/parse s timezone-id)))
 
+(defn- day-of-week
+  [s abbreviate]
```
Comment (dpsutton) [inline src/metabase/pulse/render/datetime.clj:29]:
```clojure
datetime=> (let [fmtr (java.time.format.DateTimeFormatter/ofPattern "EEE")]
             (.format fmtr (java.time.DayOfWeek/of 2)))
"mar."
datetime=> (let [fmtr (java.time.format.DateTimeFormatter/ofPattern "EEEE")]
             (.format fmtr (java.time.DayOfWeek/of 2)))
"mardi"
datetime=> (java.util.Locale/setDefault java.util.Locale/US)
nil
datetime=> (let [fmtr (java.time.format.DateTimeFormatter/ofPattern "EEEE")]
             (.format fmtr (java.time.DayOfWeek/of 2)))
"Tuesday"
datetime=> (let [fmtr (java.time.format.DateTimeFormatter/ofPattern "EEE")]
             (.format fmtr (java.time.DayOfWeek/of 2)))
"Tue"
```

File: src/metabase/pulse/render/datetime.clj [hunk 9]
```diff
@@ -11,33 +11,107 @@
...
+     "9"  {:full (tru "September") :abbreviated (tru "Sep")}
+     "10" {:full (tru "October") :abbreviated (tru "Oct")}
+     "11" {:full (tru "November") :abbreviated (tru "Nov")}
+     "12" {:full (tru "December") :abbreviated (tru "Dec")}}
+    (if abbreviate
+      [s :abbreviated]
+      [s :full])))
+
+(defn- x-of-y
+  "Format an integer as x-th of y, for example, 2nd week of year."
```
Comment (dpsutton) [inline src/metabase/pulse/render/datetime.clj:62]: I don't know if we want to pull this dep in but it could be useful:

```clojure
clj -Sdeps '{:deps {com.ibm.icu/icu4j {:mvn/version "71.1"}}}'
user=> (import 'java.util.Locale 'com.ibm.icu.text.RuleBasedNumberFormat)
com.ibm.icu.text.RuleBasedNumberFormat
user=> (doseq [[locale n] [[Locale/GERMAN "german"]
                    [Locale/JAPANESE "japanese"]
                    [Locale/ITALY "italian"]
                    [Locale/FRANCE "french"]
                    [Locale/US "american"]]]
  (let [nf (RuleBasedNumberFormat. ^Locale locale RuleBasedNumberFormat/ORDINAL)]
    (println n ":")
    (doseq [i [1 2 3 4 10 11 1000 1001 1011]]
      (println i (.format nf i "%digits-ordinal")))
    (println)))
german :
1 1.
2 2.
3 3.
4 4.
10 10.
11 11.
1000 1.000.
1001 1.001.
1011 1.011.

japanese :
1 第1
2 第2
3 第3
4 第4
10 第10
11 第11
1000 第1,000
1001 第1,001
1011 第1,011

italian :
1 1º
2 2º
3 3º
4 4º
10 10º
11 11º
1000 1.000º
1001 1.001º
1011 1.011º

french :
1 1er
2 2e
3 3e
4 4e
10 10e
11 11e
1000 1 000e
1001 1 001e
1011 1 011e

american :
1 1st
2 2nd
3 3rd
4 4th
10 10th
11 11th
1000 1,000th
1001 1,001st
1011 1,011th

nil
```

File: src/metabase/pulse/render/body.clj (hunk 3 above)
Comment (adam-james-v) [reply src/metabase/pulse/render/body.clj:433]: A nested table occurs when the legend is split into 2 'columns'. If there are 8 or fewer legend entries, it doesn't actually nest a table, just puts the table-fn table in directly.

Doing it this way let me adjust the padding between each column fairly easily. It was also the first solution I thought of, so if you think I could do it better, that's cool. I don't think this nesting is particularly bad or anything, though.

File: src/metabase/pulse/render/datetime.clj (hunk 6 above)
Comment (adam-james-v) [reply src/metabase/pulse/render/datetime.clj:73]: Ah, yes. Thanks for calling that out. Felt wrong at the time, then I forgot to try dig in more. I didn't know about `parse-long`, that's good to know!

File: src/metabase/pulse/render/datetime.clj (hunk 9 above)
Comment (adam-james-v) [reply src/metabase/pulse/render/datetime.clj:40]: Probably a good idea... especially considering I didn't account for 12 -> "12nd"... if I miss things in my own language, I think I can't be sure things will work properly with other locales either

Comment (adam-james-v) [reply src/metabase/pulse/render/datetime.clj:42]: I think that lib is pulled in with another of our dependencies. I was able to import it without changing anything in the deps.edn.

Comment (dpsutton) [reply src/metabase/pulse/render/datetime.clj:42]: bizarre. It seems to be vendored in from graal?
```clojure
(clojure.java.io/resource "com/ibm/icu/text/RuleBasedNumberFormat.class")
#object[java.net.URL
        "0x16eae632"
        "jar:file:/Users/dan/.m2/repository/org/graalvm/regex/regex/22.1.0/regex-22.1.0.jar!/com/ibm/icu/text/RuleBasedNumberFormat.class"]
```

That seems to be in the `22.1.0` jar, but not in 20.1.0, 21.2.0, or 22.0.0.2. I think we need to add this version to our top level dependencies so we don't break if they remove this in the future. I don't understand why they version it like this though.

File: src/metabase/pulse/render/body.clj (hunk 2 above)
Comment (camsaul) [reply src/metabase/pulse/render/body.clj:279]: This is something that could be nice as a comment in the code itself. The next person to touch this is never going to see this info and is going to have to rediscover it the same way you did

File: src/metabase/pulse/render/datetime.clj (hunk 9 above)
Comment (camsaul) [reply src/metabase/pulse/render/datetime.clj:42]: If we didn't have this and didn't want to pull in another dep for some reason, I think `clojure.pprint/cl-format` can do this too. But I think it's only for English

**Review by camsaul — APPROVED** [review]
This looks good to me... definitely an improvement over the current state of affairs at any rate.
