### PR TITLE
Fix #17657: No recipients causes error resulting in blank screen

### LINKED ISSUE #17657: Possible to not input recipient of Subscription, which will then cause blank screen
**Describe the bug**
It is possible to create a Dashboard Subscription without any recipients, which then result in a blank screen. But after a browser reload, then when trying to open the subscription sidebar will cause blank screen.

The only way to fix it is to manually archive the problematic subscription in the application database table `pulse`.

**To Reproduce**
1. Go to a Dashboard, edit and insert a question and save.
2. Click Sharing-icon > Dashboard subscriptions > Email
3. Do not input recipient and select "Monthly", which now enabled the Done-button - click Done
image
4. Blank screen
5. Do a browser refresh > click Sharing-icon > Dashboard subscriptions - while opening sidebar, will cause blank screen again

**Information about your Metabase Installation:**
Tested 0.39.4 thru 0.40.3.1

**Severity**
P1 contender, since it's difficult to recover from if someone accidentally did this.

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### Status
PENDING REVIEW

### What does this PR accomplish?
- Closes #17657
- Makes FE gracefully handle the situation when there is a subscription with no recipients

### Before this PR
The screen would go blank. Please see the original issue.

### After this PR
- It is not possible to save a subscription without recipients
- Even if such subscription gets created either via API, or the last recipient gets deleted, the admin can still manage (open and delete, for example) such subscription

### Demo
https://user-images.githubusercontent.com/31325167/131388225-f3dc1869-55e7-4580-90e8-9ad3f3139b2e.mp4

### CODE REVIEW

File: frontend/src/metabase/lib/pulse.js [hunk 1]
```diff
@@ -8,6 +8,28 @@ export function channelIsValid(channel, channelSpec) {
...
+        field.required &&
+        channel.details &&
+        (channel.details[field.name] == null ||
+          channel.details[field.name] === "")
+      ) {
+        return false;
+      }
+    }
+  }
+
```
Comment (nemanjaglumac) [inline frontend/src/metabase/lib/pulse.js:32]: FYI, didn't go into rewriting the logic or simplifying `channelIsValid` function in any way for this PR.

Before this PR the `switch` statement was executed before the logic that checks whether there are any recipients or not. For whatever reason, that `switch` statement returns `true` if the selected schedule was `monthly` (which is exactly the error @flamber discovered and described in the issue).

File: frontend/src/metabase/sharing/components/PulsesListSidebar.jsx [hunk 2]
```diff
@@ -103,11 +103,14 @@ function buildRecipientText(pulse) {
   const {
     channels: [firstChannel],
   } = pulse;
-  if (firstChannel.channel_type !== "email") {
+
+  const { channel_type, recipients } = firstChannel;
+
+  if (channel_type !== "email" || _.isEmpty(recipients)) {
```
Comment (nemanjaglumac) [inline frontend/src/metabase/sharing/components/PulsesListSidebar.jsx:109]: Although it shouldn't be possible any more to intentionally create a subscription without recipients, we still need to guard against that case.

File: frontend/test/metabase/scenarios/sharing/reproductions/17657.cy.spec.js [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+    cy.findByText(`${first_name} ${last_name}`).click();
+
+    sidebar().within(() => {
+      cy.button("Done").should("not.be.disabled");
+    });
+  });
+});
+
+function createSubscriptionWithoutRecipients() {
+  cy.request("POST", "/api/pulse", {
```
Comment (ranquild) [inline frontend/test/metabase/scenarios/sharing/reproductions/17657.cy.spec.js:40]: There is also `cy.createPulse` command

File: frontend/src/metabase/lib/pulse.js (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/lib/pulse.js:32]: Makes sense

**Review by ranquild — APPROVED** [review]

File: frontend/test/metabase/scenarios/sharing/reproductions/17657.cy.spec.js (hunk 3 above)
Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/sharing/reproductions/17657.cy.spec.js:40]: Thanks.
Tbh, I forgot to even look there :)
