### PR TITLE
fix(sdk): Add toggle for saving questions

### LINKED ISSUE #47464: Add onSave and isSaveEnabled prop to CreateQuestion component in the sdk
Add the `onSave` and `isSaveEnabled` prop to the `<CreateQuestion />` component in the SDK, to allow handling when the question has been saved (e.g. close the modal) and to hide the save button.
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/47442
- [ ] #47538
```

### PR DESCRIPTION
**Pull request by oisincoveney**
Adds a prop called `isSaveEnabled` on `InteractiveQuestion` to allow users to enable and disable saving a question to their Metabase instance.

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx [hunk 1]
```diff
@@ -26,12 +26,14 @@ import type { CardId } from "metabase-types/api";
 
 export type InteractiveQuestionProps = PropsWithChildren<{
   questionId?: CardId;
+  enableSave?: boolean;
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx:29]: nit: I slightly prefer `saveEnabled`, as `enableSave` sounds like an action e.g. `enableSave(...)`

**Review by heypoom — APPROVED** [review]
This behaviour (hiding the save button and preventing save) looks good to me!

File: enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx [hunk 2]
```diff
@@ -8,7 +8,8 @@ import { Box, Group, Overlay, Paper, Tabs } from "metabase/ui";
 import { useInteractiveQuestionContext } from "../InteractiveQuestion/context";
 
 const QuestionEditorInner = () => {
-  const { queryResults, runQuestion } = useInteractiveQuestionContext();
+  const { queryResults, runQuestion, enableSave } =
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx:11]: Let's make this default to `"true"` so saving is enabled by default.
