### PR TITLE
Uxw 1070/fail early if unsupported appdb version is detected

### LINKED ISSUE #36848: Fail early if unsupported appdb version is detected
For appdb, we support mysql >= v8 starting in v48

We also have [min version requirements](https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data) for other databases.

It would be helpful to lookup the appdb version during startup and if the detected version is less than the minimum supported version, we fail with a clear error. 

This will make issues such as https://github.com/metabase/metabase/issues/36842 easier for customers to debug.

### PR DESCRIPTION
**Pull request by bgrabow**
closes #36848

### Description

We have minimum version requirements for the App DB. Before this PR we didn't have any proactive validation of App DB version. The likely first place a customer would encounter a problem is during start-up when the application runs a migration that uses a feature unsupported by the out-of-date DB ([example](https://github.com/metabase/metabase/issues/36842)).

Now we proactively validate the App DB version on start-up (both for starting the application, and when running any Metabase command that involves the App DB connection). If the App DB version is too old, start-up will exit early with an error message. The only way for the customer to proceed will be to either:
1. Revert to their previously-used Metabase version
2. Upgrade their App DB to a supported version and resume their upgrade to the new Metabase version

> [!IMPORTANT]
> [Some of our docs claim](https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data) we only support MariaDB 10.4 and later, though many of our tests use MariaDB 10.2.23, and [some other docs claim](https://www.metabase.com/docs/latest/installation-and-operation/configuring-application-database#mysql-or-mariadb) we support as old as MariaDB 10.2.2. This PR takes the most lenient option and requires at least `10.2.2` in an attempt to limit scope.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Start an old database (e.g. `docker run -d -p 5432:5432 -e POSTGRES_USER=metabase -e POSTGRES_DB=metabase -e POSTGRES_PASSWORD=password -e PGDATA=/var/lib/postgresql/data --name mb-postgres-11 postgres:11`)
2. Start Metabase pointing at that old database (e.g. `clojure -M:dev:ee:ee-dev:dev-start:db/postgres-oldest`)
4. You should see a stacktrace and error report similar to the one below.

### Demo

Example log output
```
[backend] 2026-03-04 22:36:55,527 INFO core.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute... 
[backend] 2026-03-04 22:36:55,529 INFO app-db.setup :: Verifying h2 Database Connection ... 
[backend] {:clojure.main/message
[backend]  "Execution error at metabase.app-db.setup/fn$verify-db-connection61513 (setup.clj:173).\nMetabase h2 DB version not supported (found 2.1.214 (2022-06-13), required 2.1.215). Please upgrade your database to a supported version and try again.\nhttps://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data\n",
[backend]  :clojure.main/triage
[backend]  {:clojure.error/class java.lang.Exception,
[backend]   :clojure.error/line 173,
[backend]   :clojure.error/cause
[backend]   "Metabase h2 DB version not supported (found 2.1.214 (2022-06-13), required 2.1.215). Please upgrade your database to a supported version and try again.\nhttps://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data",
[backend]   :clojure.error/symbol metabase.app-db.setup/fn$verify-db-connection61513,
[backend]   :clojure.error/source "setup.clj",
[backend]   :clojure.error/phase :execution},
[backend]  :clojure.main/trace
[backend]  {:via
[backend]   [{:type java.lang.Exception,
[backend]     :message
[backend]     "Metabase h2 DB version not supported (found 2.1.214 (2022-06-13), required 2.1.215). Please upgrade your database to a supported version and try again.\nhttps://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data",
[backend]     :at [metabase.app_db.setup$fn__61514$verify_db_connection61513__61515 invoke "setup.clj" 173]}],
[backend]   :trace
[backend]   [[metabase.app_db.setup$fn__61514$verify_db_connection61513__61515 invoke "setup.clj" 173]
[backend]    [metabase.app_db.setup$fn__61514$fn__61536 invoke "setup.clj" 156]
[backend]    [metabase.app_db.setup$fn__61657$setup_db_BANG_61656__61658$fn__61661$fn__61662 invoke "setup.clj" 253]
[backend]    [metabase.util.jvm$do_with_us_locale invokeStatic "jvm.clj" 251]
[backend]    [metabase.util.jvm$do_with_us_locale invoke "jvm.clj" 237]
[backend]    [metabase.app_db.setup$fn__61657$setup_db_BANG_61656__61658$fn__61661 invoke "setup.clj" 249]
[backend]    [metabase.app_db.setup$fn__61657$setup_db_BANG_61656__61658 invoke "setup.clj" 248]
[backend]    [metabase.app_db.setup$fn__61657$fn__61669 invoke "setup.clj" 241]
[backend]    [metabase.app_db.core$setup_db_BANG_$fn__61818 invoke "core.clj" 123]
[backend]    [metabase.app_db.core$setup_db_BANG_ invokeStatic "core.clj" 118]
[backend]    [metabase.app_db.core$setup_db_BANG_ doInvoke "core.clj" 105]
[backend]    [clojure.lang.RestFn invoke "RestFn.java" 424]
[backend]    [metabase.core.core$init_BANG__STAR_ invokeStatic "core.clj" 180]
[backend]    [metabase.core.core$init_BANG__STAR_ invoke "core.clj" 157]
[backend]    [metabase.core.core$init_BANG_ invokeStatic "core.clj" 236]
[backend]    [metabase.core.core$init_BANG_ invoke "core.clj" 230]
[backend]    [dev$init_BANG_ invokeStatic "dev.clj" 146]
[backend]    [dev$init_BANG_ invoke "dev.clj" 142]
[backend]    [dev$start_BANG_ invokeStatic "dev.clj" 183]
[backend]    [dev$start_BANG_ invoke "dev.clj" 179]
[backend]    [clojure.lang.Var invoke "Var.java" 382]
[backend]    [user$_main invokeStatic "user.clj" 102]
[backend]    [user$_main doInvoke "user.clj" 71]
[backend]    [clojure.lang.RestFn applyTo "RestFn.java" 140]
[backend]    [clojure.lang.Var applyTo "Var.java" 707]
[backend]    [clojure.core$apply invokeStatic "core.clj" 667]
[backend]    [clojure.main$main_opt invokeStatic "main.clj" 515]
[backend]    [clojure.main$main_opt invoke "main.clj" 511]
[backend]    [clojure.main$main invokeStatic "main.clj" 665]
[backend]    [clojure.main$main doInvoke "main.clj" 617]
[backend]    [clojure.lang.RestFn applyTo "RestFn.java" 140]
[backend]    [clojure.lang.Var applyTo "Var.java" 707]
[backend]    [clojure.main main "main.java" 40]],
[backend]   :cause
[backend]   "Metabase h2 DB version not supported (found 2.1.214 (2022-06-13), required 2.1.215). Please upgrade your database to a supported version and try again.\nhttps://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data"}}
[backend] 
[backend] Execution error at metabase.app-db.setup/fn$verify-db-connection61513 (setup.clj:173).
[backend] Metabase h2 DB version not supported (found 2.1.214 (2022-06-13), required 2.1.215). Please upgrade your database to a supported version and try again.
[backend] https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data
[backend] 
[backend] 2026-03-04 22:36:55,744 INFO core.core :: Metabase Shutting Down ... 
[backend] 2026-03-04 22:36:55,745 INFO server.instance :: Shutting Down Embedded Jetty Webserver 
[backend] 2026-03-04 22:36:55,752 INFO notification.send :: Shutting down notification dispatchers... {mb-dispatcher-count=2}
[backend] 2026-03-04 22:36:55,754 INFO notification.send :: Starting notification thread pool with 3 threads {mb-dispatcher-count=2}
[backend] 2026-03-04 22:36:55,755 INFO notification.send :: Gracefully shutting down notification dispatcher with 0 pending notifications to process {mb-dispatcher-count=2}
[backend] 2026-03-04 22:36:56,758 INFO notification.send :: Notification worker shut down successfully {mb-dispatcher-count=2}
[backend] 2026-03-04 22:36:56,759 INFO notification.send :: Starting notification thread pool with 5 threads {mb-dispatcher-count=2}
[backend] 2026-03-04 22:36:56,759 INFO notification.send :: Gracefully shutting down notification dispatcher with 0 pending notifications to process {mb-dispatcher-count=2}
[backend] 2026-03-04 22:36:57,763 INFO notification.send :: Notification worker shut down successfully {mb-dispatcher-count=2}
[backend] 2026-03-04 22:36:57,763 INFO notification.send :: All notification workers shut down successfully {mb-dispatcher-count=2}
[backend] 2026-03-04 22:36:57,765 WARN app-db.liquibase :: () 
[backend] 2026-03-04 22:36:57,765 INFO core.core :: Metabase Shutdown COMPLETE 
[backend] clojure -M:run:dev:dev-start --hot exited with code 1

```

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by bgrabow** [comment]
Currently the error output is accompanied by an ugly Clojure stack trace. I [read](https://www.notion.so/metabase/The-Zen-of-Metabase-the-Product-7399ce09bcc7457bb1fd824137ddd5f4) that this is not generally the desired style. Does that apply in this case? The [existing error reporting](https://github.com/metabase/metabase/blob/89bb889883baf951dc13814d429003608e27740f/src/metabase/core/core.clj#L261) already puts stack traces in the log (the `e` is passed to `log/error` which puts the stack trace in the log). Should we change that now?

**Comment by bgrabow** [comment]
We will need documentation updates to the following pages:

https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data
https://www.metabase.com/docs/latest/installation-and-operation/configuring-application-database#mysql-or-mariadb

Perhaps instead of hard-coding the supported versions we could link from the docs to the file that defines the minimum required versions?

```
resources/metabase/app_db/supported-db-versions.edn
```

Some possible formats of the min versions file. Which one is most user-friendly, particularly if people want to write a script to notice a required version change?

[As semver strings](https://raw.githubusercontent.com/metabase/metabase/0633a4d3d5a4cd5819e848e6103939c2b5bee038/resources/metabase/app_db/supported-db-versions-semver-string.edn)
[As vectors](https://raw.githubusercontent.com/metabase/metabase/0633a4d3d5a4cd5819e848e6103939c2b5bee038/resources/metabase/app_db/supported-db-versions-vector.edn)
[As maps](https://raw.githubusercontent.com/metabase/metabase/0633a4d3d5a4cd5819e848e6103939c2b5bee038/resources/metabase/app_db/supported-db-versions.edn)

File: src/metabase/app_db/setup.clj [hunk 1]
```diff
@@ -120,6 +123,42 @@
...
+(defn- load-supported-db-versions
+  []
+  (if-let [resource (io/resource "metabase/app_db/supported-db-versions.edn")]
+    (edn/read-string (slurp resource))
+    (throw (ex-info "Resource not found: metabase/app_db/supported-db-versions.edn"
+                    {:path "metabase/app_db/supported-db-versions.edn"}))))
+
+(def supported-db-versions
+  "https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data"
+  (load-supported-db-versions))
```
Comment (bgrabow) [inline src/metabase/app_db/setup.clj]: Are there better idioms for resource loading besides eagerly at load time? This is going to be used during app init, so it's really just a tradeoff between load-time delay/failure and init-time delay/failure so there may not be much practical difference.

File: src/metabase/app_db/setup.clj [hunk 2]
```diff
@@ -131,9 +170,27 @@
...
+                   (.getDatabaseProductName metadata) (.getDatabaseProductVersion metadata) (u/emoji "✅"))
+        (throw (ex-info (str/join \newline [(trs "Metabase {0} DB version not supported (found {1}, required {2}). Please upgrade your database to a supported version and try again."
+                                                 (name db-type)
+                                                 (.getDatabaseProductVersion metadata)
+                                                 (let [required-version (get supported-db-versions db-type)]
+                                                   (format "%s.%s.%s"
+                                                           (:major required-version)
+                                                           (:minor required-version)
+                                                           (:patch required-version))))
+                                            "https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data"])
```
Comment (bgrabow) [inline src/metabase/app_db/setup.clj:192]: If we ever change the URL path of this doc, will we notice that this error message should be updated to match?

File: src/metabase/app_db/setup.clj [hunk 3]
```diff
@@ -131,9 +170,27 @@
...
+      (log/warn "Found DB metadata" {:product-name (.getDatabaseProductName metadata)
+                                     :major (.getDatabaseMajorVersion metadata)
+                                     :minor (.getDatabaseMinorVersion metadata)
+                                     :product-version (.getDatabaseProductVersion metadata)})
+      (if (supported-app-db-version? db-type db-version)
+        (log/infof "Successfully verified %s %s application database connection. %s"
+                   (.getDatabaseProductName metadata) (.getDatabaseProductVersion metadata) (u/emoji "✅"))
+        (throw (ex-info (str/join \newline [(trs "Metabase {0} DB version not supported (found {1}, required {2}). Please upgrade your database to a supported version and try again."
+                                                 (name db-type)
+                                                 (.getDatabaseProductVersion metadata)
```
Comment (bgrabow) [inline src/metabase/app_db/setup.clj]: This will print the full product version string e.g. `"12.2.2-MariaDB-ubu2404"`, more than just the semver numbers. It will be useful in some debugging situations if we ever run into problems parsing the semver from the product version string.

File: test/metabase/app_db/setup_test.clj [hunk 4]
```diff
@@ -27,6 +27,72 @@
...
+    (is (= {:major 11 :minor 16 :patch 0} (#'mdb.setup/parse-db-version "11.16 (Debian 11.16-1.pgdg90+1)"))))
+
+  (testing "Can parse mysql version strings"
+    (is (= {:major 9 :minor 6 :patch 0} (#'mdb.setup/parse-db-version "9.6.0")))
+    (is (= {:major 8 :minor 0 :patch 45} (#'mdb.setup/parse-db-version "8.0.45"))))
+
+  (testing "Can parse mariadb version strings"
+    (is (= {:major 12 :minor 2 :patch 2} (#'mdb.setup/parse-db-version "12.2.2-MariaDB-ubu2404")))))
+
+(comment
```
Comment (bgrabow) [inline test/metabase/app_db/setup_test.clj]: TODO: delete this repl code

Comment (ericnormand) [reply test/metabase/app_db/setup_test.clj]: Yes, please.

File: src/metabase/app_db/setup.clj [hunk 5]
```diff
@@ -120,6 +123,42 @@
...
     (= result 1)))
 
+(defn- load-supported-db-versions
+  []
+  (if-let [resource (io/resource "metabase/app_db/supported-db-versions.edn")]
+    (edn/read-string (slurp resource))
+    (throw (ex-info "Resource not found: metabase/app_db/supported-db-versions.edn"
+                    {:path "metabase/app_db/supported-db-versions.edn"}))))
+
+(def supported-db-versions
```
Comment (ericnormand) [inline src/metabase/app_db/setup.clj]: I believe this should be private.

File: src/metabase/app_db/setup.clj [hunk 6]
```diff
@@ -120,6 +123,42 @@
...
+  "https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data"
+  (load-supported-db-versions))
+
+(defn- parse-db-version
+  [product-version]
+  (let [[_ major minor patch] (re-find #"^(\d+)(?:\.(\d+))?(?:\.(\d+))?" product-version)]
```
Comment (ericnormand) [inline src/metabase/app_db/setup.clj:139]: Good change ;)

**Review by ericnormand — COMMENTED** [review]
It looks good. A few minor nits. Great work.

I tested it against the postgres 11 from the docker command you gave and it worked. Still works on postgres 17.

File: src/metabase/app_db/setup.clj [hunk 7]
```diff
@@ -131,9 +170,27 @@
...
            (throw (ex-info error-msg {} e)))))
   (with-open [conn (.getConnection ^javax.sql.DataSource data-source)]
-    (let [metadata (.getMetaData conn)]
-      (log/infof "Successfully verified %s %s application database connection. %s"
-                 (.getDatabaseProductName metadata) (.getDatabaseProductVersion metadata) (u/emoji "✅")))))
+    (let [metadata (.getMetaData conn)
+          db-version (db-version metadata)
+          db-type (or (when (= "MariaDB" (.getDatabaseProductName metadata)) :mariadb)
+                      db-type)]
+      (log/warn "Found DB metadata" {:product-name (.getDatabaseProductName metadata)
```
Comment (bgrabow) [inline src/metabase/app_db/setup.clj]: To-do: remove debugging log message

**Comment by bgrabow** [comment]
> We will need documentation updates to the following pages:
> 
> [metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data](https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data) [metabase.com/docs/latest/installation-and-operation/configuring-application-database#mysql-or-mariadb](https://www.metabase.com/docs/latest/installation-and-operation/configuring-application-database#mysql-or-mariadb)
> 
> Perhaps instead of hard-coding the supported versions we could link from the docs to the file that defines the minimum required versions?
> 
> ```
> resources/metabase/app_db/supported-db-versions.edn
> ```
> 
> Some possible formats of the min versions file. Which one is most user-friendly, particularly if people want to write a script to notice a required version change?
> 
> [As semver strings](https://raw.githubusercontent.com/metabase/metabase/0633a4d3d5a4cd5819e848e6103939c2b5bee038/resources/metabase/app_db/supported-db-versions-semver-string.edn) [As vectors](https://raw.githubusercontent.com/metabase/metabase/0633a4d3d5a4cd5819e848e6103939c2b5bee038/resources/metabase/app_db/supported-db-versions-vector.edn) [As maps](https://raw.githubusercontent.com/metabase/metabase/0633a4d3d5a4cd5819e848e6103939c2b5bee038/resources/metabase/app_db/supported-db-versions.edn)

This will be tracked in [DOC-94](https://linear.app/metabase/issue/DOC-94/docs-updates-for-minimum-app-db-version-breaking-change)

File: src/metabase/app_db/setup.clj (hunk 3 above)
Comment (escherize) [reply src/metabase/app_db/setup.clj]: Is it worth putting in the version that we parsed as well? would make tricky versioning strings easier to debug in the future. something like e.g.:

````
12.2.2-MariaDB-ubu2404 (parsed as 12.2.2), required version: 13.0.7
````

Tricky example: MariaDB prepends `5.5.5-` to its version string in the MySQL protocol handshake packet when the actual version is 10.x.x or higher. So we'd see something like: `5.5.5-10.6.12-MariaDB`. Then the message would be pretty helpful:

````
5.5.5-12.2.2-MariaDB-ubu2404 (parsed as 5.5.5), required version: 13.0.7
````

Comment (ericnormand) [reply src/metabase/app_db/setup.clj]: I like this suggestion.

**Review by ericnormand — APPROVED** [review]

File: src/metabase/app_db/setup.clj (hunk 3 above)
Comment (bgrabow) [reply src/metabase/app_db/setup.clj]: Going with this format:
```
found 5.5.5 (5.5.5-12.2.2-MariaDB-ubu2404), required 13.0.7
```
