### PR TITLE
Include partitioned tables in sync

### LINKED ISSUE #15049: Data model not showing PostgreSQL tables when they are partitioned
**Describe the bug**
If a table is partitioned, it's not being visible in the Data Model section of the admin panel and can't be subsequently accessed when creating a question using the "simple question" method. 

Example: I've got a table called "order" partitioned by year with a default partition that stores all the data not fitting the partition. In the earlier versions I could just select the "order" table, in the current I only see the partitions (as per screenshot below):

**Logs**
No errors in console.

**To Reproduce**
Create a partitioned PostgreSQL table and try accessing it via Admin -> Data Model.

**Expected behavior**
You should be able to see and select the whole table, not just its partitions.

**Screenshots**

Data Model (no Order table):
image

Simple question (no Order table):
image

Actual table structure in DataGrip (Order table exists):

image

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.19.0-14-cloud-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.0 (Debian 13.0-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-02-19",
      "tag": "v0.38.0.1",
      "branch": "release-x.38.x",
      "hash": "0635914"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Blocking some users - the tables can still be accessed using an SQL query, but people not familiar with SQL aren't able to use Metabase.

**Additional context**
Did work properly in a previous version about two months ago (last time I've checked).

### PR DESCRIPTION
**Pull request by jeff303**
Include partitioned tables in sync

Add new table type ("PARTITIONED TABLE") to `.getTables` invocation

Add test for Postgres to ensure all partitions, in addition to main table, are synced

Pull `exec!` into helper fn in `postgres_test.clj`

### CODE REVIEW

**Comment by jeff303** [comment]
Fixes #15049.

File: test/metabase/driver/postgres_test.clj [hunk 1]
```diff
@@ -205,35 +209,70 @@
...
                         (db/select [Table :name :active] :db_id (u/the-id database), :name "angry_birds"))))))))))
 
+(deftest partitioned-table-test
+  (mt/test-driver :postgres
+    (testing (str "Make sure that partitioned tables (in addition to the individual partitions themselves) are
+                   synced properly (#15049")
+      (let [db-name "partitioned_table_test"
+            details (mt/dbdef->connection-details :postgres :db {:database-name db-name})
+            spec    (sql-jdbc.conn/connection-details->spec :postgres details)
+            pg-ver  (-> {:query "SHOW SERVER_VERSION;"}
```
Comment (camsaul) [inline test/metabase/driver/postgres_test.clj:246]: https://docs.oracle.com/javase/9/docs/api/java/sql/DatabaseMetaData.html#getDatabaseProductVersion--

**Review by camsaul — APPROVED** [review]
Cool this LGTM. I still think we should tackle #13444 and #13136 at some point instead of special casing version checks, but that's a larger task

**Comment by jeff303** [comment]
> Cool this LGTM. I still think we should tackle #13444 and #13136 at some point instead of special casing version checks, but that's a larger task

Yeah, that would be ideal I think.  In this particular case, we're not special casing our own behavior at least (the fact that someone can create with different syntax in a newer version of Postgres is not something we do directly from our code, just something we need to accommodate).

**Comment by dpsutton** [comment]
I ran a bisect on this to try to track it down. Came up with

```
a78d8b2126de885741ff68742a7384c27d50f8a7 is the first bad commit
commit a78d8b2126de885741ff68742a7384c27d50f8a7
Author: Robert Roland <rob@metabase.com>
Date:   Mon Feb 1 15:17:02 2021 -0800
    Allow SSL client certificates to work in pgsql (#13797)
    
    * Allow SSL client certificates to work in pgsql
    
    When a user specifies a `sslmode` or `sslfactory`, we should honor that instead of overwriting their selections.
    
    The NonValidatingFactory isn't something we should default to - it just checks that an SSL certificate is present, it does not attempt
    any sort of validation of said certificate, and it also explicitly blocks support for client certificates.
    
    Update pgsql driver to one that supports PKCS12
```

which included this change:

```
modified   project.clj
@@ -134,7 +134,7 @@
    [org.liquibase/liquibase-core "3.6.3"                              ; migration management (Java lib)
     :exclusions [ch.qos.logback/logback-classic]]
    [org.mariadb.jdbc/mariadb-java-client "2.6.2"]                     ; MySQL/MariaDB driver
-   [org.postgresql/postgresql "42.2.8"]                               ; Postgres driver
+   [org.postgresql/postgresql "42.2.18"]                              ; Postgres driver
```

The changelog for Version 42.2.11 (2020-03-09) lists:
> feat: add way to distinguish base and partitioned tables in PgDatabaseMetaData.getTables PR 1708

And this is the change that added 'PARTITIONED TABLE'.

Was just wondering if we had broken something somewhere else in sync or if it was a driver change shifting underneath us. And that method is what we're calling in describe-database:

```clojure
(defn- db-tables
  "Fetch a JDBC Metadata ResultSet of tables in the DB, optionally limited to ones belonging to a given
  schema. Returns a reducible sequence of results."
  [driver ^DatabaseMetaData metadata ^String schema-or-nil ^String db-name-or-nil]
  (common/reducible-results
   #(.getTables metadata db-name-or-nil (some->> schema-or-nil (driver/escape-entity-name-for-metadata driver)) "%"
                (into-array String ["TABLE" "PARTITIONED TABLE" "VIEW" "FOREIGN TABLE" "MATERIALIZED VIEW"
                                    "EXTERNAL TABLE"]))
   (fn [^ResultSet rs]
     (fn []
       {:name        (.getString rs "TABLE_NAME")
        :schema      (.getString rs "TABLE_SCHEM")
        :description (when-let [remarks (.getString rs "REMARKS")]
                       (when-not (str/blank? remarks)
                         remarks))}))))
```
