### PR TITLE
Fix expression string literal performance

### LINKED ISSUE #12154: Using a long "field formula" in Custom Column/Expression freezes browser
**Describe the bug**
Using the new functions like `concat`/`coalesce`/`contains` can become almost impossible, when strings become more than ~30 characters, because the browser becomes unresponsive.

**Logs**
Nothing, but browser will ask to stop slow-running-script.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2.
    - Add Custom Column and try writing `concat('this is a test of a long string with an ID: ', [ID])` - it should become unresponsive around the word "string".
    - Add Filter > Custom Expression and try writing `contains([Product → Title], 'this is a test of a long string')`

**Information about your Metabase Installation:**
1.35.0-snapshot and stats on Firefox and Chromium.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #12154

The actual fix was removing the `+` from the string literal regexes, but I took the opportunity to refactor those regexes into a helper function.

### CODE REVIEW

File: frontend/src/metabase/lib/expressions/lexer.js [hunk 1]
```diff
@@ -196,19 +196,27 @@ const getQuoteCategories = character => {
     : [];
 };
 
+const quotedStringRegex = (character, closed = true) => {
+  const open = character;
+  const close = closed ? character : "";
+  return new RegExp(
+    `${open}(?:[^\\\\${character}]|\\\\(?:[bfnrtv${character}\\\\/]|u[0-9a-fA-F]{4}))*${close}`,
```
Comment (paulrosenzweig) [inline frontend/src/metabase/lib/expressions/lexer.js]: Nice fix! "catastrophic backtracking" I guess? What's the `bfnrtv` part?

**Review by paulrosenzweig — APPROVED** [review]

File: frontend/src/metabase/lib/expressions/lexer.js (hunk 1 above)
Comment (tlrobinson) [reply frontend/src/metabase/lib/expressions/lexer.js]: Those are other characters that can be escaped, e.x. `\n`. I copied it from Chevrotain's JSON lexer since we just use `JSON.stringify`/`parse` to escape/unescape string literals. I think they must have fixed the regex since I first copied it.

**Review by mazameli — APPROVED** [review]
Nice! I didn't run into any weirdness in testing out string literals in custom columns, filter expressions, or when using `countif` conditions with literals.
