### PR TITLE
fix click behavior permission error

### LINKED ISSUE #15993: Click Behavior with filter pass-thru causes permission error (even for admins)
**Describe the bug**
When setting up a Click Behavior to question with a filter pass through, then it will show permission error, which are really difficult to debug.

This issue has been through several iterations, since it began as a annoyance, which turned out it also stored unintended information similar to #13595 and would not show the filter widget, but since the new parameter rewrite in 0.42.0, then it's causing a permission error (only in the frontend), which is insanely difficult to debug.
Changing this to a P1 regression now in 0.43.0.

**To Reproduce**
1. Simple question > Sample Dataset > Orders - save as "Q1"
2. Native query > Sample Dataset > `select 0` - save as "Q2"
3. Add "Q2" to dashboard and add Click Behavior to question "Q1" and set it to pass filter to Quantity or Products.Rating:
image
4. Save dashboard - click the Number visualization value (zero) - it goes to the question and has the filter defined
image
image
5. Go back to the dashboard and do a **browser refresh** and click the value again - it goes to the question, but since 0.42 it will show a permission error `Sorry, you don’t have permission to see that.` (pre-42 would show the "Q1" question, but without showing it was filter, though the results were filtered).
There's **no** errors in the backend on 0.43.0, `POST /api/card/35/query 202 [ASYNC: completed] ...`
image

When I tested on 0.42.4, then I got a backend error stacktrace:
`Invalid parameter: Card 35 does not have a template tag named nil`
<details><summary>Full stacktrace</summary>

```
2022-05-12 14:32:36,596 ERROR middleware.log :: POST /api/card/35/query 500 18.0 ms (6 DB calls) 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "Invalid parameter: Card 35 does not have a template tag named nil.",
   :data
   {:type :invalid-parameter,
    :invalid-parameter
    {:type :text, :value [0], :target [:dimension [:field 85 nil]], :id "[\"dimension\",[\"field\",85,null]]"},
    :allowed-parameters nil},
   :at [metabase.query_processor.card$fn__68423$validate_card_parameters__68428$fn__68429 invoke "card.clj" 160]}],
 :trace
 [[metabase.query_processor.card$fn__68423$validate_card_parameters__68428$fn__68429 invoke "card.clj" 160]
  [metabase.query_processor.card$fn__68423$validate_card_parameters__68428 invoke "card.clj" 151]
  [metabase.query_processor.card$run_query_for_card_async invokeStatic "card.clj" 208]
  [metabase.query_processor.card$run_query_for_card_async doInvoke "card.clj" 169]
  [clojure.lang.RestFn invoke "RestFn.java" 826]
  [metabase.api.card$fn__71266 invokeStatic "card.clj" 671]
  [metabase.api.card$fn__71266 invoke "card.clj" 661]
  [compojure.core$wrap_response$fn__32284 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__32268 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__32273 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 151]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 152]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__65391 invoke "auth.clj" 14]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32324 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 299]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 300]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [metabase.api.routes$fn__76516$fn__76519 invoke "routes.clj" 56]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__76661$fn__76662 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32324 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32328 invoke "core.clj" 299]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32277 invoke "core.clj" 153]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296$f__32297$respond_SINGLEQUOTE___32298 invoke "core.clj" 197]
  [metabase.server.routes$fn__76649$fn__76651 invoke "routes.clj" 41]
  [compojure.core$routes$fn__32296$f__32297 invoke "core.clj" 198]
  [compojure.core$routes$fn__32296 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73644 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__73641 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__77130$fn__77131$fn__77132 invoke "log.clj" 209]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__77130$fn__77131 invoke "log.clj" 201]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__77130 invoke "log.clj" 200]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80483 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__55251 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__79638 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__79656 invoke "json.clj" 98]
  [metabase.server.middleware.offset_paging$handle_paging$fn__55275 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__80750 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__80766 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__34391 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__45744$fn__45745 invoke "session.clj" 262]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 243]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 235]
  [metabase.server.middleware.session$bind_current_user$fn__45744 invoke "session.clj" 261]
  [metabase.server.middleware.session$wrap_current_user_info$fn__45731 invoke "session.clj" 221]
  [metabase.server.middleware.session$wrap_session_id$fn__45717 invoke "session.clj" 167]
  [metabase.server.middleware.auth$wrap_api_key$fn__65399 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__80670 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__34374 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__34399 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__80712 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__34402 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80499 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__76903 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 388]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 633]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 380]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 386]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run "Thread.java" 829]],
 :cause "Invalid parameter: Card 35 does not have a template tag named nil.",
 :data
 {:type :invalid-parameter,
  :invalid-parameter
  {:type :text, :value [0], :target [:dimension [:field 85 nil]], :id "[\"dimension\",[\"field\",85,null]]"},
  :allowed-parameters nil},
 :message "Invalid parameter: Card 35 does not have a template tag named nil.",
 :invalid-parameter
 {:type :text, :value [0], :target [:dimension [:field 85 nil]], :id "[\"dimension\",[\"field\",85,null]]"},
 :allowed-parameters nil}
```

</details>

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.43.0

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/15993

## Changes
Allow creating drilling to dashboard questions through click behavior when there is no question metadata loaded.

## How to verify
- New -> Question -> Sample Dataset -> Orders - save as "Q1"
- New -> SQL query -> Sample Dataset -> `select 0` - save as "Q2"
- Add "Q2" to dashboard and add Click Behavior to question "Q1" and set it to pass filter to Quantity
- Save the dashboard and reload the page
- Click on `0` from Q2 and ensure it leads to Q1 with a correct filter state

### CODE REVIEW

File: frontend/src/metabase-lib/lib/Question.ts [hunk 1]
```diff
@@ -1274,7 +1274,7 @@ class QuestionInner {
     if (this.isStructured()) {
       const questionWithParameters = this.setParameters(parameters);
 
-      if (this.query().isEditable()) {
+      if (!this.query().readOnly()) {
```
Comment (alxnddr) [inline frontend/src/metabase-lib/lib/Question.ts:1277]: `isEditable` is false if there is no metadata for the query, but I think it should not be necessary just for creating a link

**Comment by flamber** [comment]
@alxnddr Can you merge master. I cannot test because of the font PR.

**Comment by alxnddr** [comment]
@flamber done

**Review by flamber — COMMENTED** [review]
This works great for admins, but for users with no-data permissions, then it shows permission error.
Here I'm showing an example of dashboard filter on a question, where drill-through works as expected, but on the Click Behavior question, then I get a permission error, when doing something that basically should be doing the same thing.

https://user-images.githubusercontent.com/1447303/168811767-dec278ec-142c-4b9f-894d-94c231e16e75.mp4

<details><summary>Full stacktrace</summary>

```
2022-05-17 14:28:34,496 DEBUG middleware.log :: GET /api/timeline 200 2.9 ms (3 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
2022-05-17 14:28:34,531 DEBUG middleware.log :: GET /api/card/587 200 22.3 ms (10 DB calls) App DB connections: 0/13 Jetty threads: 4/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
2022-05-17 14:28:34,617 DEBUG middleware.log :: GET /api/alert/question/587 200 1.6 ms (1 DB calls) App DB connections: 1/13 Jetty threads: 5/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
2022-05-17 14:28:34,631 WARN middleware.log :: GET /api/database/4/schemas 403 3.0 ms (3 DB calls) 
"You don't have permissions to do that."

2022-05-17 14:28:34,636 WARN middleware.log :: GET /api/table/11/query_metadata 403 7.7 ms (3 DB calls) 
"You don't have permissions to do that."

2022-05-17 14:28:34,637 DEBUG middleware.log :: GET /api/dashboard/ 200 21.5 ms (5 DB calls) App DB connections: 0/13 Jetty threads: 6/50 (1 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
2022-05-17 14:28:34,707 WARN middleware.log :: GET /api/field/103 403 7.1 ms (7 DB calls) 
"You don't have permissions to do that."

2022-05-17 14:28:34,715 WARN middleware.log :: GET /api/field/103/values 403 4.5 ms (4 DB calls) 
"You don't have permissions to do that."

2022-05-17 14:28:35,087 ERROR middleware.log :: POST /api/card/587/query 500 9.9 ms (6 DB calls) 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "Invalid parameter: Card 587 does not have a template tag named nil.",
   :data
   {:type :invalid-parameter,
    :invalid-parameter
    {:type :text,
     :value ["0"],
     :target [:dimension [:field 103 {:source-field 82}]],
     :id "[\"dimension\",[\"field\",103,{\"source-field\":82}]]"},
    :allowed-parameters nil},
   :at [metabase.query_processor.card$fn__70202$validate_card_parameters__70207$fn__70208 invoke "card.clj" 160]}],
 :trace
 [[metabase.query_processor.card$fn__70202$validate_card_parameters__70207$fn__70208 invoke "card.clj" 160]
  [metabase.query_processor.card$fn__70202$validate_card_parameters__70207 invoke "card.clj" 151]
  [metabase.query_processor.card$run_query_for_card_async invokeStatic "card.clj" 208]
  [metabase.query_processor.card$run_query_for_card_async doInvoke "card.clj" 169]
  [clojure.lang.RestFn invoke "RestFn.java" 1124]
  [metabase.api.card$fn__73034 invokeStatic "card.clj" 673]
  [metabase.api.card$fn__73034 invoke "card.clj" 662]
  [compojure.core$wrap_response$fn__28058 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__28042 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__28047 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 151]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 153]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 152]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 153]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 152]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 153]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 152]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 152]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 153]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 153]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 153]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 152]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 152]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__67684 invoke "auth.clj" 14]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28098 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28102 invoke "core.clj" 299]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28102 invoke "core.clj" 300]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28102 invoke "core.clj" 300]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28102 invoke "core.clj" 300]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28102 invoke "core.clj" 300]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [metabase.api.routes$fn__78663$fn__78666 invoke "routes.clj" 61]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__78820$fn__78821 doInvoke "routes.clj" 67]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28098 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28102 invoke "core.clj" 299]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 153]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 153]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28051 invoke "core.clj" 153]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070$f__28071$respond_SINGLEQUOTE___28072 invoke "core.clj" 197]
  [metabase.server.routes$fn__78806$fn__78808 invoke "routes.clj" 45]
  [compojure.core$routes$fn__28070$f__28071 invoke "core.clj" 198]
  [compojure.core$routes$fn__28070 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75544 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__75541 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__79273$fn__79274$fn__79275 invoke "log.clj" 211]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__79273$fn__79274 invoke "log.clj" 203]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__79273 invoke "log.clj" 202]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__82529 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__61323 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__81649 invoke "json.clj" 63]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__81667 invoke "json.clj" 99]
  [metabase.server.middleware.offset_paging$handle_paging$fn__61347 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__82796 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__82815 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__35226 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__46666$fn__46667 invoke "session.clj" 291]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 270]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 259]
  [metabase.server.middleware.session$bind_current_user$fn__46666 invoke "session.clj" 290]
  [metabase.server.middleware.session$wrap_current_user_info$fn__46648 invoke "session.clj" 240]
  [metabase.server.middleware.session$wrap_session_id$fn__46632 invoke "session.clj" 173]
  [metabase.server.middleware.auth$wrap_api_key$fn__67692 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__82716 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__35209 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__35234 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__82758 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__35237 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__82545 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__79045 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 400]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 645]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 392]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 409]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run "Thread.java" 829]],
 :cause "Invalid parameter: Card 587 does not have a template tag named nil.",
 :data
 {:type :invalid-parameter,
  :invalid-parameter
  {:type :text,
   :value ["0"],
   :target [:dimension [:field 103 {:source-field 82}]],
   :id "[\"dimension\",[\"field\",103,{\"source-field\":82}]]"},
  :allowed-parameters nil},
 :message "Invalid parameter: Card 587 does not have a template tag named nil.",
 :invalid-parameter
 {:type :text,
  :value ["0"],
  :target [:dimension [:field 103 {:source-field 82}]],
  :id "[\"dimension\",[\"field\",103,{\"source-field\":82}]]"},
 :allowed-parameters nil}
```

</details>

^ similar stacktrace as I saw on 42.

Dalton might be able to provide some hints on resolving it, since he did made the question drill-through work.

**Comment by alxnddr** [comment]
@flamber to what question clicking on `0` leads? When I use a structured question from orders table it shows the permission error, but isn't that reasonable since a user with limited permissions could not create such filter manually from the query builder?

**Review by ranquild — APPROVED** [review]
