### PR TITLE
Fix Admin Nested Navlink Behavior

### LINKED ISSUE #62780: Navigating Settings Presents Error When you Select Auth or Embedding Sections
### Describe the bug

If you select the "Authentication" or "Embedding" menu items from the admin panel you're presented with the error page:

"We're a little lost"

You can still navigate to the sub items in the menu just fine but it seems odd to display an error there.

### To Reproduce

https://www.loom.com/share/babce35a01ca493ebccad8860b6b6060

### Expected behavior

Just expand the menu without presenting the error message?

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-08-22",
      "tag": "v1.56.3.1",
      "hash": "8526023"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "5.15.167.4-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iethree**
Closes UXW-585
Closes #62780 

### Description

Previously, Mantine NavLinks would ignore click events if the NavLink contained other items. That changed somewhere between mantine 8.0 and 8.2. 

Previously, our SettingsNavItem component relied on the inactive `path` prop to handle highlighting behavior, relying on the fact that it would not navigate. Now that that is no longer true, I have introduced another prop: `folderPattern` - which will handle folder highlighting behavior more explicitly. (e.g. if a folder is collapsed while you're on a subpage, we should highlight the top level folder). That behavior was probably a bug and we shouldn't have relied on it in the first place.

CleanShot 2025-08-26 at 13 14 51

### Checklist

I spent a bunch of time trying to get this tested in jest, and I think it's just not possible to write a meaningful navigation test with the current state of react-router + redux, so I did it in cypress.

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/admin/settings/components/SettingsNav/SettingsNav.tsx [hunk 1]
```diff
@@ -59,6 +63,7 @@ export function SettingsNav() {
       <SettingsNavItem path="maps" label={t`Maps`} icon="pinmap" />
       <SettingsNavItem
         path="whitelabel"
+        folderPattern="whitelabel"
```
Comment (bpander) [inline frontend/src/metabase/admin/settings/components/SettingsNav/SettingsNav.tsx:66]: Very minor. Was just wondering why this nav item still has a path? I'm guessing it's because it needs to function as a link when `hasWhitelabel` is `false`?

It threw me for a loop that it worked differently than the other expandable nav items. What do you think about making its path conditional?

```suggestion
        path={!hasWhitelabel ? "whitelabel" : undefined}
```

**Review by bpander — APPROVED** [review]
☑️ Looks good! Just had one question/suggestion about the whitelabel menu item.
