### PR TITLE
prevent moving snippet collections into descendents, remove recents tab

### LINKED ISSUE #44930: Collection picker behaving oddly for snippets
### Describe the bug

There are three main issues with the collection picker in the context of adding a snippet to a collection.

- the "Recents" tab on the collection picker is showing all recent collections, including non-snippet collections
- the regular collection picker is showing a weird mix of regular collections and snippet collections
- if i try to add a new collection, it tries to create it without the "snippet" namespace (which fails)

### To Reproduce

1. Create some regular collections.
2. Create a native query and click SQL Snippets
3. Click the + sign and "New Folder"
4. Type some details and hit "Save"
5. Click the + sign again and "New Folder"
6. Click "Folder this should be in" to open the collection picker
7. **Problem 1: See your regular collections in the Recents tab**
8. Click "Collections" tab
9. **Problem 2: See your regular collections in this tab** (This one was inconsistent - caching?)
10. Click "Create a new collection"
11. If you created a new collection in the "root" collection, it'll be invisible. If you tried to create one in your snippet collection, the creation will fail. (The frontend is trying to create a collection without the "snippets" namespace inside a collection that has the "snippets" namespace.

### Expected behavior

The collection picker should consistently show/create collections with the correct namespace.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Master
```

### Severity

minor annoyance

### Additional context

https://www.loom.com/share/4635fcfc23f6456c91b26896189618c0

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/44930

### Description
When working with snippets, there were a couple features / checks that were not quite working properly in the collection picker.
- Collection Picker as showing the resents tab, which shouldn't have any valid options for snippets
- When moving a snippet collection, collection descendants were not disabled
- Creating a new collection from the collection picker was not working (namespace wasn't included in request)

### How to verify
1. Go to New -> SQL Query
2. Open the snipets sidebar
3. check the above.

### Demo
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx [hunk 1]
```diff
@@ -102,6 +105,7 @@ function FormCollectionPicker({
       hasConfirmButtons: true,
       namespace: type === "snippet-collections" ? "snippets" : undefined,
       allowCreateNew: showCreateNewCollectionOption,
+      hasRecents: type === "snippet-collections" ? false : true,
```
Comment (rafpaf) [inline frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx:108]: could be simplified with `!==`

File: enterprise/frontend/src/metabase-enterprise/snippets/components/SnippetCollectionForm.tsx [hunk 2]
```diff
@@ -112,6 +113,16 @@ function SnippetCollectionForm({
     [collection.id, isEditing, handleCreate, handleUpdate, onSave],
   );
 
+  const shouldDisableItem = useCallback(
+    (item: CollectionPickerItem) => {
+      return passedCollection.id
+        ? item.effective_location?.includes(String(passedCollection.id)) ||
+            passedCollection.id === item.id
```
Comment (iethree) [inline enterprise/frontend/src/metabase-enterprise/snippets/components/SnippetCollectionForm.tsx:120]: I think you'll need to split effective_location, right?  otherwise you'll disable stuff overly-aggressively like

passedCollection.id: `11`
effective_location: `1/113/8113`

**Review by rafpaf — APPROVED** [review]

**Review by iethree — CHANGES_REQUESTED** [review]
looks good, just one little bug with shouldDisableItem

File: enterprise/frontend/src/metabase-enterprise/snippets/components/SnippetCollectionForm.tsx (hunk 2 above)
Comment (npfitz) [reply enterprise/frontend/src/metabase-enterprise/snippets/components/SnippetCollectionForm.tsx:120]: Fair point! I'll get that fixed

File: enterprise/frontend/src/metabase-enterprise/snippets/components/SnippetCollectionForm.tsx [hunk 3]
```diff
@@ -112,6 +113,16 @@ function SnippetCollectionForm({
...
+        : false;
```
[the remark this answers is not in the document]
Comment (npfitz) [reply enterprise/frontend/src/metabase-enterprise/snippets/components/SnippetCollectionForm.tsx]: Fair point on the implicit coercion of `passedCollection.id`. I was mainly just checking if it existed or not. Thankfully, `partialCollection` always exists, so checking if the id is undefined works well!

File: enterprise/frontend/src/metabase-enterprise/snippets/components/SnippetCollectionForm.tsx (hunk 2 above)
Comment (npfitz) [reply enterprise/frontend/src/metabase-enterprise/snippets/components/SnippetCollectionForm.tsx]: Good catch. doing a split

**Review by iethree — APPROVED** [review]
🥳
