### PR TITLE
Fix "View as table" in visualizer

### LINKED ISSUE #69038: "View as a Table" in the Visualizer Doesn't Work
### Describe the bug

"View as a table" doesn't work in the visualizer.

Image

### To Reproduce

1. Add a visualization to a dashboard (reproduced with bar, line and area)
2. Go to visualizer
3. Click "View as a table" in the bottom left corner of the chart

### Expected behavior

The table view should work.

### Logs

{
    "message": "Invalid query: query cannot be empty",
    "data": {
        "I": null,
        "H": 1,
        "v": [
            {
                "Bb": null,
                "name": "query",
                "K": "query",
                "Cd": -1288509510,
                "A": 2153775105,
                "F": 4096
            },
            {}
        ],
        "J": null,
        "A": 16647951,
        "F": 401412
    },
    "cause": null,
    "name": "Error",
    "stack": "Error: Invalid query: query cannot be empty\n    at new push.24318.tl.Ni (http://localhost:1571/app/dist/app-main.36d781495282020f.js:6:125108)\n    at push.24318.tl.Oi (http://localhost:1571/app/dist/app-main.36d781495282020f.js:6:125418)\n    at push.24318.tl.Pi (http://localhost:1571/app/dist/app-main.36d781495282020f.js:6:125375)\n    at Object.from_js_query (http://localhost:1571/app/dist/app-main.36d781495282020f.js:6:928825)\n    at Module.X (http://localhost:1571/app/dist/app-main.36d781495282020f.js:10:47628)\n    at j.query (http://localhost:1571/app/dist/app-main.36d781495282020f.js:10:70763)\n    at http://localhost:1571/app/dist/app-main.36d781495282020f.js:318:16060\n    at iA (http://localhost:1571/app/dist/vendor.4ad55c2ae5020149.js:7:1573394)\n    at ag (http://localhost:1571/app/dist/vendor.4ad55c2ae5020149.js:7:1585245)\n    at ah (http://localhost:1571/app/dist/vendor.4ad55c2ae5020149.js:7:1584453)"
}

### Information about your Metabase installation

```JSON
Reproduce on 58.4 and 57.10
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevinkelleher12**
Closes #69038

### Description

Clicking the "View as table" button in visualizer was broken (I believe) by #63913, because the visualizer creates an empty `dataset_query` object (see `getTabularPreviewSeries`) which causes an error whenever it's used to construct a `Lib.Query` (see `from-js-query`).

This PR works around the issue by preventing `Table` from every trying to construct a `Query` when used in the visualizer, but this seems a little hacky. Perhaps there's a way visualizer can create non-empty `dataset_query` objects instead.

### How to verify

See #69038

### Demo

Before:
image

After:
image

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/Table/Table.tsx [hunk 1]
```diff
@@ -129,10 +129,17 @@ export class Table extends Component<TableProps, TableState> {
         settings: ComputedVisualizationSettings,
       ) => data && data.cols.length !== 3 && !settings["table.pivot"],
       getDefault: ([{ card, data }]: Series) => {
+        let native: boolean;
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/visualizations/Table/Table.tsx:132]: How to reproduce the crash? When I tested the only `HeaderCellWithColumnInfo` change did the trick

Comment (kevinkelleher12) [reply frontend/src/metabase/visualizations/visualizations/Table/Table.tsx:132]: this one is only so that the table pivots correctly:
- make a question: Count of Orders grouped by Created At and Category
- add to dashboard, open it in visualizer, view as table
- without this code, the table is visible, but not pivoted correctly

**Review by alxnddr — APPROVED** [review]
