### PR TITLE
fix sandboxing parameter field disabled

### LINKED ISSUE #29143: Under specific circumstances, when editing an existing sandbox, the "Parameter or variable" dropdown for a filter is incorrectly grayed out
**Describe the bug**
This is some kind of weird state issue that I'm hitting while investigating https://github.com/metabase/metabase/issues/29135. 

**To Reproduce**
1. Create a group, user and sandbox per the repro steps in https://github.com/metabase/metabase/issues/29135
2. Refresh the permissions page and edit the sandbox you just created. Scroll down in the sandboxing modal.
3. Under "Parameter or variable", the first dropdown will show "State" and be editable but the second dropdown will say "Pick a parameter" and be grayed out
4. Exit the modal without editing anything, and then open the modal again
5. Now both dropdowns will show up correctly

**Screenshots/videos**
https://user-images.githubusercontent.com/32746338/224433070-946e1784-954f-40c8-ad8b-4126ba43d7c0.mov

**Information about your Metabase Installation:**
Current master

**Severity**
Could be extremely confusing for admins who hit this

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/29143

### Description

Question parameters in the sandboxing modal used the old `SavedQuestionLoader` which loads a saved question first and then loads the question metadata. Even though loading card data went through redux, the code actually retrieved card data from the returned promise like `const card = await this.props.fetchQuestion(questionId);`. As you may know, the entity's `fetch` action tracks the request state in the store which prevents firing multiple requests for the same data. The reproduction steps render two fields, each of them called this action but the second invocation does not actually trigger a new request since there is an existing one in progress, hence the second action itself resolves with `undefined`. Overall, the approach of getting data from action is a hack and here it led to a bug. I replaced it with our Question loader which selects data from the store.

### How to verify

Run Metabase EE

1. Create a group, user, and sandbox per the repro steps in https://github.com/metabase/metabase/issues/29135
2. Refresh the permissions page and edit the sandbox you just created. Scroll down in the sandboxing modal.
3. Under "Parameter or variable", ensure both "State" and "Source" parameters selects are enabled

### Demo

<video src="https://user-images.githubusercontent.com/14301985/225758866-8d02ab2c-b965-47b4-84da-8fe72f46f84a.mov" />

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29256)

### CODE REVIEW

File: frontend/src/metabase/containers/SavedQuestionLoader.jsx [hunk 1]
```diff
@@ -38,107 +39,50 @@ import Question from "metabase-lib/Question";
  * The raw un-connected component is also exported so we can unit test it
  * without the redux store.
  */
```
Comment (EmmadUsmani) [inline frontend/src/metabase/containers/SavedQuestionLoader.jsx:41]: Nit: I think we can remove this comment since now we are using Redux inside the component

**Review by EmmadUsmani — APPROVED** [review]
