### PR TITLE
Show all breakouts and metrics in tooltip when merging stacked bar charts

### LINKED ISSUE #30561: Add Series with Stack - 100% charts causes discrepancy between release 45 and 46
### Describe the bug

Let's say i have 2 questions which return the same result. Currently there is no union option on GUI so you can go to a dashboard -> Add 1 question -> Add Series -> Second question ... So in 45 we aggregate the total of the 2 questions and calculated % accordingly but in 46 we calculate % individually for each question. This would show 25% in 45 and 50% in 46

### To Reproduce

1. Go to New Question -> Products -> Count -> Group by Category, Created At: Month

    image

2. Click on Bar Chart -> Display -> Stack - 100% -> Save this question as Stack 1

    image

3. Do Step 1 -> Step 2 -> Save this question as Stack 2
4. New Dashboard -> Add Stack 1 -> Add Series -> Add Stack 2

5. Result on release 45

    image

6. Result on 46

    image

Notice that in 45 we aggregate the total of the 2 questions and calculated % accordingly but in 46 we calculate % individually for each question. This would show 25% in 45 and 50% in 46

### Expected behavior

Same behaviour as 45 for Stack - 100% charts

### Logs

None

### Information about your Metabase installation

```JSON
release 46
```

### Severity

Currently impacting clients since there is no union option on GUI so this workaround to Add Series used to do the trick for them.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shaunlebron**
Closes https://github.com/metabase/metabase/issues/30561

### Description

* When multiple stacked bar charts are merged, the bars belonging to the same original chart are grouped into a logical “card”.
* The new v46 tooltip shows all percentages inside a given card, but the v45 tooltip had only a single absolute percentage.
* [The design team and product team commented about this here](https://metaboat.slack.com/archives/C02H619CJ8K/p1687916296041109), and recommended that we display percentages for the whole stack instead of just the card.

v45 | v46 (regression) | fixed here
---|---|---
CleanShot 2023-06-27 at 19 21 08@2x | CleanShot 2023-06-27 at 19 22 01@2x | CleanShot 2023-06-29 at 15 36 27@2x

### How to verify

Follow steps in the linked issue.

### Checklist

- [x] Write tests.

### CODE REVIEW

**Comment by shaunlebron** [comment]
@alxnddr I changed the behavior of the stacked tooltip to show all series in the stack, instead of the ones belonging to the hovered item’s “card”.  The tests still pass, but I’m unsure about the original intention behind of the “card”.  Am I missing a use case by removing this?

File: frontend/src/metabase/visualizations/lib/apply_tooltips.js [hunk 1]
```diff
@@ -331,16 +331,12 @@ export const getStackedTooltipModel = (
   }));
 
   const hoveredSeries = seriesWithGroupedData[hoveredIndex];
-  const hoveredCardId = hoveredSeries?.card?.id;
-  const hoveredCardSeries = seriesWithGroupedData.filter(
-    series => series.card?.id === hoveredCardId,
-  );
-  const hasBreakout = hoveredCardSeries?.some(
+  const hasBreakout = seriesWithGroupedData.some(
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/lib/apply_tooltips.js:334]: There can be series without breakouts and just with multiple metrics. I believe we should not include them in the calculation of percentages. Here is the [spec](https://www.notion.so/metabase/Offer-automated-percentages-on-stacked-charts-a8af42d2b81e458b827b679dac2b61c6?pvs=4#d0fc4c7acd114e3f9f75fae629905dbf)

Here is an example of a question with multiple series because of multiple metrics:
Screen Shot 2023-06-29 at 10 14 10 PM

The result of combining it with a question with breakouts:
Screen Shot 2023-06-29 at 10 15 23 PM

So `seriesToShow` should only include series with breakouts

Comment (shaunlebron) [reply frontend/src/metabase/visualizations/lib/apply_tooltips.js:334]: I guess when adding a card with multiple metrics to a card with breakouts, they shouldn’t even be rendered together as a stacked bar chart, but I suppose we can just fix the tooltip first.

Comment (shaunlebron) [reply frontend/src/metabase/visualizations/lib/apply_tooltips.js:334]: Can you detail on how to reproduce this?  I created the chart with multiple metrics, but couldn’t merge it onto the stacked bar chart— the chart wasn’t listed on the right:

CleanShot 2023-07-05 at 14 46 43@2x

And likewise, I couldn’t merge the multi-metric chart onto the stacked bar chart (wasn’t listed on the right):

CleanShot 2023-07-05 at 14 46 17@2x

Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/apply_tooltips.js:334]: I'm still able to reproduce it, please have a look:
<video src="https://github.com/metabase/metabase/assets/14301985/d90dcaa6-11f8-40c2-9b7e-16ec0ad28cb4" />

Comment (shaunlebron) [reply frontend/src/metabase/visualizations/lib/apply_tooltips.js:334]: Resolved the issue in this [slack discussion with Conor](https://metaboat.slack.com/archives/C02H619CJ8K/p1688594596966999?thread_ts=1687916296.041109&cid=C02H619CJ8K).  We’re erroneously only displaying percentages for breakouts not metrics, but stacked charts should always display percentages.

**Comment by shaunlebron** [comment]
@alxnddr Can you take another look?  I got [clarification from product](https://metaboat.slack.com/archives/C02H619CJ8K/p1688594596966999?thread_ts=1687916296.041109&cid=C02H619CJ8K) that we should display percentages for all things being stacked, even metrics.

The part of the spec that said [we should exclude metrics from percentages](https://www.notion.so/metabase/Offer-automated-percentages-on-stacked-charts-a8af42d2b81e458b827b679dac2b61c6?pvs=4#d0fc4c7acd114e3f9f75fae629905dbf) was actually conflating display types with data types based on the common use-cases:

* the user will normally display _metrics_ with “Don’t stack”
* the user will normally display _breakouts_ with “Stack” or “Stack 100%”

And we should only omit percentages when “Don’t stack” is set.  (We’re actually not showing the stack tooltip for this setting anyway, but that can be resolved in a separate PR.)

This simplifies the logic to indiscriminately show percentages and a total, regardless of what’s being displayed.  I updated our tests to reflect this behavior.

File: frontend/src/metabase/visualizations/lib/apply_tooltips.unit.spec.js [hunk 2]
```diff
@@ -211,27 +211,20 @@ describe("getStackedTooltipModel", () => {
...
-    },
-    {
-      data: {
-        cols,
-        rows: [["foo", 200]],
-        settings: {},
-      },
-      card: { name: "Series 2" },
-    },
+    getMockSerie({
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/lib/apply_tooltips.unit.spec.js:222]: nit: since `serie` is an obsolete word we in other places of the codebase we use `series` and `multipleSeries`

**Review by alxnddr — APPROVED** [review]
Looks good!

File: frontend/src/metabase/visualizations/lib/apply_tooltips.unit.spec.js (hunk 2 above)
Comment (shaunlebron) [reply frontend/src/metabase/visualizations/lib/apply_tooltips.unit.spec.js]: ✅ 4602b8c547227736d2ec1d05e24b79d8bb38aa7f

**Comment by alxnddr** [comment]
@shaunlebron is there anything that prevents it from being backported to 47?
