### PR TITLE
Fix object detail crashing when a table from foreign key is hidden

### LINKED ISSUE #32654: Clicking on "View details" after a drill down generates an error in the FE
### Describe the bug
1. Go to Admin > Table Metadata > Hide Orders table
2. Go to Products table and click the view detail icon.

<details>
<summary>Old reproduction</summary>

1) Go to question 2915 in our internal Metabase instance. then click on the pie chart on "show xxxx"
2) in the table that appears, go to the left side till the "view details" icon appears

you'll see that the FE breaks there with
```
TypeError: Cannot read properties of undefined (reading 'table')
    at schema_metadata.js:10:41
    at Array.map (<anonymous>)
    at i (schema_metadata.js:9:6)
    at p7 (ObjectRelationships.tsx:34:27)
    at Jo (react-dom.production.min.js:153:146)
    at Os (react-dom.production.min.js:261:496)
    at mc (react-dom.production.min.js:246:265)
    at bc (react-dom.production.min.js:246:194)
    at cc (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
```
</details>

### To Reproduce

Above

### Expected behavior

It should show the detail view without problems

### Logs

NA

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

### Additional context

NA

### PR DESCRIPTION
**Pull request by WiNloSt**
> **Note**
> We're also considering fixing this on the BE, [if we've confirmed to fix BE](https://metaboat.slack.com/archives/C05MPF0TM3L/p1693886467150039?thread_ts=1693399181.395239&cid=C05MPF0TM3L), after the BE fix is merged I'll create a follow-up PR to remove this FE fix.

Closes https://github.com/metabase/metabase/issues/32654

### Description

Fix the problem by filtering out foreign key information that its table is hidden, the other way to fix this is for BE to not send the information for hidden tables in the first place

### How to verify

1. Go to Admin > Table Metadata > Hide Orders table
2. Go to Products table and click the view detail icon.

#### After
Screenshot 2023-09-06 at 5 29 22 PM

#### Before
Screenshot 2023-09-06 at 5 28 56 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase-types/api/table.ts [hunk 1]
```diff
@@ -81,5 +81,5 @@ export interface ForeignKey {
   origin_id: FieldId;
   destination?: Field;
   destination_id: FieldId;
-  relationship: string; // enum?
+  relationship: "Mt1";
```
Comment (WiNloSt) [inline frontend/src/metabase-types/api/table.ts:84]: We seem to only hardcode this, there is a single place that specifies this property.
https://github.com/metabase/metabase/blob/1a3decaadadc8d2d19699857e570bbab94b362cf/src/metabase/api/table.clj#L461

File: frontend/src/metabase/query_builder/selectors.js [hunk 2]
```diff
@@ -220,10 +220,14 @@ export const getTableMetadata = createSelector(
...
 );
 
-export const getTableForeignKeys = createSelector(
-  [getTableMetadata],
-  table => table?.fks ?? [],
-);
+export const getTableForeignKeys = createSelector([getTableMetadata], table => {
+  const tableForeignKeys = table?.fks ?? [];
+  const tableForeignKeysWithoutHiddenTables = tableForeignKeys.filter(
+    tableForeignKey => tableForeignKey.origin != null,
```
Comment (WiNloSt) [inline frontend/src/metabase/query_builder/selectors.js:226]: This is the fix. For hidden tables, `ferignKey.origin` would be `undefined`. https://github.com/metabase/metabase/blob/1a3decaadadc8d2d19699857e570bbab94b362cf/frontend/src/metabase/selectors/metadata.ts#L345

We should filter out the FK foreign key completely so other parts of the code behave as if the foreign key for the hidden table never existed.

The [other suggested fix](https://github.com/metabase/metabase/issues/32654#issuecomment-1662929055) doesn't completely fix the issue since there are other places that read this `tableForeignKeys` and assume all foreign keys will have `origin` value.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx [hunk 3]
```diff
@@ -77,9 +78,15 @@ const mapDispatchToProps = (dispatch: any) => ({
...
+  ObjectDetailProps,
+  keyof MapStateProps | keyof MapDispatchProps
+>;
 
 // eslint-disable-next-line import/no-default-export -- deprecated usage
 export default connect(
   mapStateToProps,
   mapDispatchToProps,
-)(ObjectDetailWrapper);
+)(ObjectDetailWrapper) as unknown as React.ComponentType<OwnProps>;
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx:92]: Fix the type so that TypeScript doesn't complain when I use the component in `frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx`. Previously, it would complain I needed to pass props that would be passed automatically from `mapStateToProps` and `mapDispatchToProps`.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.unit.spec.tsx [hunk 4]
```diff
@@ -273,7 +273,7 @@ function setup(
   );
 }
 
-describe("Object Detail", () => {
+describe("ObjectDetailView", () => {
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.unit.spec.tsx:276]: Modify the name so we don't get confused with the new test I created `frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx`

File: frontend/test/__support__/server-mocks/table.ts [hunk 5]
```diff
@@ -1,11 +1,14 @@
...
 
-export function setupTableEndpoints(table: Table) {
+export function setupTableEndpoints(
+  table: Table,
+  foreignKeys: ForeignKey[] = [],
+) {
   fetchMock.get(`path:/api/table/${table.id}`, table);
   fetchMock.get(`path:/api/table/${table.id}/query_metadata`, table);
-  fetchMock.get(`path:/api/table/${table.id}/fks`, []);
+  fetchMock.get(`path:/api/table/${table.id}/fks`, foreignKeys);
```
Comment (WiNloSt) [inline frontend/test/__support__/server-mocks/table.ts:11]: This is used in `frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx`

File: frontend/test/__support__/testDataset.ts [hunk 6]
```diff
@@ -1,19 +1,21 @@
...
 import { createMockDatasetData } from "metabase-types/api/mocks";
+import { PRODUCTS_ID, PRODUCTS } from "metabase-types/api/mocks/presets";
 
 const testColumns: DatasetColumn[] = [
   {
     description:
       "The numerical product number. Only used internally. All external communication should use the title or EAN.",
     semantic_type: "type/PK",
-    table_id: 1,
+    table_id: PRODUCTS_ID,
```
Comment (WiNloSt) [inline frontend/test/__support__/testDataset.ts:10]: avoid using hard-coded values and use our defined constants instead since it's more standardized.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx [hunk 7]
```diff
@@ -0,0 +1,167 @@
...
+      visualizationIsClickable={jest.fn()}
+    />,
+    {
+      storeInitialState: state,
+    },
+  );
+}
+
+function setupForeignKeyCountQueryEndpoints() {
+  fetchMock.post(
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx:107]: Even though there is an existing function for this (`setupCardDataset`)
https://github.com/metabase/metabase/blob/d3a9d9d6013daf4e5b12bc1b9e83996957e0d151/frontend/test/__support__/server-mocks/dataset.ts#L16-L24

it only uses `url` as a matcher rather than using an object like I do in this case, so I call `fetchMock` directly. If we ever need to use object matcher again we can consider refactoring `setupCardDataset` in the future.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx [hunk 8]
```diff
@@ -0,0 +1,167 @@
...
+const HIDDEN_ORDERS_TABLE = createOrdersTable({
+  visibility_type: "hidden",
+});
+const REVIEWS_TABLE = createReviewsTable();
+
+interface SetupOpts {
+  hideOrdersTable?: boolean;
+}
+
+function setup({ hideOrdersTable = false }: SetupOpts = {}) {
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx:41]: All the following API mocks + state mocks are inserted one by one until the test starts rendering, so I'm pretty they're needed. It might not be apparent from the get-go why all of these are required.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx [hunk 9]
```diff
@@ -0,0 +1,167 @@
...
+      status: "completed",
+      data: {
+        rows: [[8]],
+      },
+    }),
+  );
+}
+
+function findField(fields: Field[] | undefined, name: string): Field {
+  return fields?.find(field => field.name === name) as Field;
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx:142]: nit: I believe this cast belongs somewhere else. I'd make this function return `Field | undefined`, and use `isNotNull` next to the actual usages where we know the field is going to be found.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx [hunk 10]
```diff
@@ -0,0 +1,167 @@
...
+}
+
+describe("ObjectDetail", () => {
+  it("should render foreign key count when no table is hidden", async () => {
+    setup();
+
+    expect(
+      await screen.findByText(getBrokenUpTextMatcher("8Reviews")),
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx:150]: nit: This makes it a little bit more readable:

```suggestion
      await screen.findByText(getBrokenUpTextMatcher(["8", "Reviews"].join(""))),
```

**Review by kamilmielnik — APPROVED** [review]
LGTM :+1: Left some minor comments.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx (hunk 10 above)
Comment (WiNloSt) [reply frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx:150]: Good idea.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx [hunk 11]
```diff
@@ -0,0 +1,167 @@
...
+    ).toBeInTheDocument();
+    expect(
+      await screen.findByText(getBrokenUpTextMatcher("93Orders")),
+    ).toBeInTheDocument();
+  });
+
+  it("should render only foreign key count for foreign keys that their tables are not hidden (metabase#32654)", async () => {
```
[the remark this answers is not in the document]
Comment (kamilmielnik) [reply frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx:157]: Ah, it's not foreign key count (there are only 2 foreign keys here), it's related objects count.

```suggestion
  it("should render related objects count only for foreign keys referencing non-hidden tables (metabase#32654)", async () => {
```

[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx]: Fixed in cc0cf9c90407ea0e5e51c8773f6667cad86af11a

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx (hunk 10 above)
Comment (WiNloSt) [reply frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx]: Fixed in https://github.com/metabase/metabase/pull/33697/commits/9b97b91957cdb5324e234c3fb64f1e80ba38b9da
