### PR TITLE
Fix alert with goal archived even though goal is not met

### LINKED ISSUE #61491: Alerts on progress bars are being disabled automatically
### Describe the bug

I am creating this ticket as I haven't found a relevant issue already reported here.

We use dashboards to monitor our clients' activity. On those dashboards, we depend on progress bars to set a limit of usage the client can use. Once passed, an alert is sent to a ticketing system that gives a green light for Accounting to invoice the excess consumption. Everything was working like a charm for the past few years, until recently. 
We noticed last week (26/07) that all progress bars that had Alerts when the limit goes over the goal were disabled - **[EDIT 12h44 - 2025-07-28]** even if the progress bar did NOT reach the goal). To accelerate the operations within our organization, I have reset those alerts one by one (they are over 280 Metabase questions).
I have checked again today to make sure that everything is in order. Again all the alerts on the progress bars have been disabled. I checked with another users to double-check and same results on their screen (so not a cache related)

We have updated our Metabase first week of July to this version 0.54.15, and not sure it is related to that, but I suspect it might be linked. 

These alerts are very important to us as to not miss out on invoicing, and your help will be appreciated.

PS: I am not a dev, or engineer, so kindly take it easy on me with technical questions :)

Thanks in advance

Image

### To Reproduce

1. Create a progress bar with a limit (Goal)
2. Click on Sharing to set up an alert
3. Select When results go above the goal line
4. Toggle Only Send this alert once
5. Include the email that the alert will be sent to
6. Done

Image

### Expected behavior

**[EDIT: 2025-7-28 13h05]** If the limit has not been reached, the alert must remain active. 
And after the limit (Goal) has been crossed, Metabase will send the alert to the email defined in the alert when set up and then get deactivated.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "athena",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-06-30",
      "tag": "v0.54.15",
      "hash": "ae24a7b"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.21"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "6.1.134-152.225.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Blocking some users

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/61491

### CODE REVIEW

File: src/metabase/notification/payload/impl/card.clj [hunk 1]
```diff
@@ -68,16 +68,20 @@
 
 (mu/defmethod notification.send/do-after-notification-sent :notification/card
   [{:keys [id creator_id handlers] :as notification-info} :- ::models.notification/FullyHydratedNotification
-   notification-payload]
-  (when (-> notification-info :payload :send_once)
+   notification-payload
+   skip-reason]
```
Comment (crisptrutski) [inline src/metabase/notification/payload/impl/card.clj]: How about just passing a `skipped?` flag? 

Seeing `skip-reason` in the signature at first could make one thing that this is a code path only for when things are skipped, or that we need to use the specific reason some how.

File: src/metabase/notification/payload/core.clj [hunk 2]
```diff
@@ -152,7 +152,7 @@
          :context (default-context)))
 
 (defmulti skip-reason
-  "Determine whether a notification should be sent. Default to true."
+  "Determine whether a notification should be sent. Default to nil."
```
Comment (crisptrutski) [inline src/metabase/notification/payload/core.clj:155]: Starting to think an LLM vibe check for finding stale comments when we update existing functions could be useful.

File: src/metabase/notification/send.clj [hunk 3]
```diff
@@ -153,8 +153,9 @@
           (task-history/with-task-history {:task          "notification-send"
                                            :task_details {:notification_id       id
                                                           :notification_handlers (map #(select-keys % [:id :channel_type :channel_id :template_id]) handlers)}}
-            (let [notification-payload (notification.payload/notification-payload (dissoc hydrated-notification :handlers))]
-              (if-let [reason (notification.payload/skip-reason notification-payload)]
+            (let [notification-payload (notification.payload/notification-payload (dissoc hydrated-notification :handlers))
+                  reason               (notification.payload/skip-reason notification-payload)]
```
Comment (crisptrutski) [inline src/metabase/notification/send.clj]: How about `skip-reason` for the binding here, to be clearer. I would prefer actually `reason-if-skipped`, so it's clear that it has special `nil` semantics, but using inconsistent terminology sucks and doesn't seem worth a bulk rename.

**Review by crisptrutski — APPROVED** [review]
Functionally looks OK

File: src/metabase/notification/payload/impl/card.clj (hunk 1 above)
Comment (qnkhuat) [reply src/metabase/notification/payload/impl/card.clj]: yea, I wanted to have skip-reason in case we might want more granular check. but let's keep it a boolean for now.

File: src/metabase/notification/send.clj (hunk 3 above)
Comment (qnkhuat) [reply src/metabase/notification/send.clj]: replaced
