### PR TITLE
Ldap group mapping slash issue

### LINKED ISSUE #29629: LDAP Group Schema mapping doesn't accept strings containing forward slash "/" character
**Describe the bug**
We use LDAP for Metabase login, we use Active Directory for our LDAP directory, this works as expected. 

I've looked at setting up group membership mapping but the OU containing the user groups I want to use is called `Security/Distribution Groups` in Active Directory. I cannot change that name.

When I try to use that OU name into Metabase for a mapping I get and error on the page and no mapping is created:
`Distribution Groups,DC=metabase,DC=com is not a valid DN.`

The full distinguished name used is `CN=People,OU=Security/Distribution Groups,DC=metabase,DC=com`, this is obviously not our real DN but used for this example.

I've tried escaping the forward slash with the LDAP escape character "\" but this doesn't change the behaviour. e.g. `CN=People,OU=Security\/Distribution Groups,DC=metabase,DC=com`

**Logs**
Javascript console log:
```
PUT http://localhost:3000/api/setting/ldap-group-mappings 500 (Server Error)
```

Server log:
```
2023-03-29 11:24:19,794 ERROR middleware.log :: PUT /api/setting/ldap-group-mappings 500 877.2 ╡s (0 DB calls)
{:via
 [{:type java.lang.IllegalArgumentException,
   :message "Distribution Groups,DC=metabase,DC=com is not a valid DN. is not a valid DN.",
   :at [metabase.integrations.ldap$fn__96837$fn__96842 invoke "ldap.clj" 94]}],
 :trace
 [[metabase.integrations.ldap$fn__96837$fn__96842 invoke "ldap.clj" 94]
  [metabase.models.setting$set_BANG_ invokeStatic "setting.clj" 749]
  [metabase.models.setting$set_BANG_ invoke "setting.clj" 732]
  [metabase.api.setting$fn__94965$fn__94968 invoke "setting.clj" 57]
  [metabase.api.setting$do_with_setting_access_control invokeStatic "setting.clj" 14]
  [metabase.api.setting$do_with_setting_access_control invoke "setting.clj" 10]
  [metabase.api.setting$fn__94965 invokeStatic "setting.clj" 56]
  [metabase.api.setting$fn__94965 invoke "setting.clj" 51]
  [compojure.core$wrap_response$fn__42375 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__42359 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__42364 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 151]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__86624 invoke "auth.clj" 17]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [compojure.core$make_context$handler__42415 invoke "core.clj" 290]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 300]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [metabase.api.routes$fn__98449$fn__98452 invoke "routes.clj" 64]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__98610$fn__98611 doInvoke "routes.clj" 70]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [compojure.core$make_context$handler__42415 invoke "core.clj" 290]
  [compojure.core$make_context$fn__42419 invoke "core.clj" 300]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
  [metabase.server.routes$fn__98595$fn__98597 invoke "routes.clj" 47]
  [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
  [compojure.core$routes$fn__42387 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__95133 invoke "exceptions.clj" 103]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__95130 invoke "exceptions.clj" 91]
  [metabase.server.middleware.log$log_api_call$fn__100334$fn__100335$fn__100336 invoke "log.clj" 216]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
  [metabase.server.middleware.log$log_api_call$fn__100334$fn__100335 invoke "log.clj" 208]
  [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
  [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
  [metabase.server.middleware.log$log_api_call$fn__100334 invoke "log.clj" 207]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__103755 invoke "browser_cookie.clj" 42]
  [metabase.server.middleware.security$add_security_headers$fn__79453 invoke "security.clj" 153]
  [metabase.server.middleware.json$wrap_json_body$fn__102499 invoke "json.clj" 67]
  [metabase.server.middleware.offset_paging$handle_paging$fn__79477 invoke "offset_paging.clj" 45]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__102517 invoke "json.clj" 103]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__104022 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__104041 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__50479 invoke "misc.clj" 61]
  [metabase.server.middleware.session$reset_session_timeout$fn__63769 invoke "session.clj" 430]
  [metabase.server.middleware.session$bind_current_user$fn__63739$fn__63740 invoke "session.clj" 336]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 315]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 304]
  [metabase.server.middleware.session$bind_current_user$fn__63739 invoke "session.clj" 335]
  [metabase.server.middleware.session$wrap_current_user_info$fn__63721 invoke "session.clj" 285]
  [metabase.server.middleware.session$wrap_session_id$fn__63704 invoke "session.clj" 217]
  [metabase.server.middleware.auth$wrap_api_key$fn__86632 invoke "auth.clj" 30]
  [ring.middleware.cookies$wrap_cookies$fn__103942 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__50461 invoke "misc.clj" 29]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__50487 invoke "misc.clj" 78]
  [ring.middleware.gzip$wrap_gzip$fn__103984 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__50490 invoke "misc.clj" 95]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__103771 invoke "ssl.clj" 41]
  [metabase.server$async_proxy_handler$fn__99100 invoke "server.clj" 77]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
  [org.eclipse.jetty.server.Server handle "Server.java" 563]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$0 "HttpChannel.java" 505]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 762]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 497]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 282]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
  [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy runTask "AdaptiveExecutionStrategy.java" 416]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy consumeTask "AdaptiveExecutionStrategy.java" 385]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy tryProduce "AdaptiveExecutionStrategy.java" 272]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy lambda$new$0 "AdaptiveExecutionStrategy.java" 140]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 411]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 936]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1080]
  [java.lang.Thread run nil -1]],
 :cause "Distribution Groups,DC=metabase,DC=com is not a valid DN. is not a valid DN.",
 :message "Distribution Groups,DC=metabase,DC=com is not a valid DN. is not a valid DN."}
```

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Go to Admin > Authentication > LDAP > Edit
2. In Group Schema, click "New Mapping"
3. Enter `CN=People,OU=Security/Distribution Groups,DC=metabase,DC=com` into the text box
4. Click "Add" button
5. Note the error is displayed

**Expected behavior**
All valid LDAP entity names should be accepted.

**Screenshots/videos**
image

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.2+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-28",
      "tag": "v0.46.0",
      "branch": "release-x.46.x",
      "hash": "0ca7df3"
    },
    "settings": {
      "report-timezone": "NZ"
    }
  }
}
```

**Severity**
This is preventing us from using the LDAP -> Metabase group mapping functionality. Work around is to manage groups manually but there's significant overhead to doing it that way.

We could make some changes in Active Directory, setting up a new OU and new groups specially for Metabase access with the other "standard" groupings as members, but that will create clutter in our AD to work around this issue.

**Additional context**
Forward slash "/" doesn't appear to be a [reserved or special character in LDAP](https://www.ibm.com/docs/en/sva/9.0.2.1?topic=tasks-valid-characters-ldap-user-group-names) I've looked into getting the OU renamed but it's apparently not feasible.

### PR DESCRIPTION
**Pull request by perivamsi**
Closes https://github.com/metabase/metabase/issues/29629

### Description

Use the custom qualified-name function to not strip out the slash in the LDAP group name

### CODE REVIEW

File: test/metabase/integrations/ldap_test.clj [hunk 1]
```diff
@@ -172,6 +172,14 @@
                "CN=Shipping,OU=Groups,DC=metabase,DC=com"]
               {:group-mappings (ldap/ldap-group-mappings)}))))))
 
+(deftest valid-group-mapping
+  (testing "Validating that the LDAP keyword can contain a forward slash (#29629)"
```
Comment (noahmoss) [inline test/metabase/integrations/ldap_test.clj:176]:
```suggestion
  (testing "Validating that a group mapping DN can contain a forward slash when set as a keyword (#29629)"
```

**Review by noahmoss — APPROVED** [review]
Small suggestion to make the test wording more precise, otherwise 👍
