### PR TITLE
Fixes for load-from-h2 migration command

### LINKED ISSUE #2632: load-from-h2 not working because of circular references between RawColumns
hey guys! i'm working on migrating from H2 to Postgres again, and i'm close, but hitting a new error. it looks like you maybe need to tweak the table ordering so that foreign key constraints are satisfied? or something?

i upgraded to 0.17.1 successfully today, then later stopped metabase, backed up `metabase.db.h2.db`, and restarted. when i set up and run `load-from-h2`, i get:

```
$ java -jar ~/metabase.jar load-from-h2
05-20 00:31:02 INFO metabase.db :: Verifying Database Connection ...
05-20 00:31:02 DEBUG metabase.driver :: Registered driver :postgres 🚚
05-20 00:31:02 INFO metabase.db :: Verify Database Connection ... ✅
05-20 00:32:02 INFO metabase.db :: Database Migrations Current ... ✅
05-20 00:32:02 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
05-20 00:32:03 INFO db.migrations :: Running data migration 'set-card-database-and-table-ids'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'set-mongodb-databases-ssl-false'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'set-default-schemas'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'set-admin-email'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'remove-database-sync-activity-entries'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'remove-duplicate-fk-entries'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'update-dashboards-to-new-grid'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'migrate-field-visibility-type'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'fix-dashboard-cards-without-positions'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'migrate-fk-metadata'...
05-20 00:32:03 INFO db.migrations :: Running data migration 'create-raw-tables'...
05-20 00:32:03 INFO db.migrations :: Finished running data migrations.
Transfering 4 instances of Database....[OK]
Transfering 220 instances of RawTable....[OK]
Transfering 1672 instances of RawColumn....org.postgresql.util.PSQLException: ERROR: insert or update on table "raw_column" violates foreign key constraint "fk_rawcolumn_fktarget_ref_rawcolumn"
  Detail: Key (fk_target_column_id)=(766) is not present in table "raw_column".
...
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
...
	at metabase.cmd.load_from_h2$load_from_h2.invokeStatic(load_from_h2.clj:80)
	at metabase.cmd.load_from_h2$load_from_h2.invoke(load_from_h2.clj:70)
...
Command failed with exception: ERROR: insert or update on table "raw_column" violates foreign key constraint "fk_rawcolumn_fktarget_ref_rawcolumn"
  Detail: Key (fk_target_column_id)=(766) is not present in table "raw_column".
```

i get the same error when i run it locally, on a mac, with the same jar and H2 db into postgres.

thanks in advance!

*  My server's OS is Ubuntu 14.04.
*  I'm running Metabase 0.17.1 on AWS EC2, from the JAR.
*  My database is H2, trying to port to Postgres 9.3.10 on RDS.

### PR DESCRIPTION
**Pull request by agilliland**
Turns out there were several things that needed to be addressed:
- Resolves #2632 where self-referencing columns caused FK constraint violation
- fixes an issue on postgres migrations where `:sizeX` and `:sizeY` column names were not getting handled properly
- manually updates the postgres sequence values after a migration to avoid duplicate key errors when running the app after a migration
- fixes an error with jdbc clob values not getting inserted properly on postgres databases

I've tried this out on both MySQL and Postgres and it's working for me in both cases at this point.

### CODE REVIEW

File: resources/log4j.properties [hunk 1]
```diff
@@ -18,7 +18,6 @@ log4j.appender.metabase=metabase.logger.Appender
 
 # customizations to logging by package
 log4j.logger.metabase=INFO
-log4j.logger.metabase.db=DEBUG
```
Comment (camsaul) [inline resources/log4j.properties]: don't forget to remove this

File: src/metabase/cmd/load_from_h2.clj [hunk 2]
```diff
@@ -67,27 +71,77 @@
...
+                           RawColumn :fk_target_column_id
+                           Field     :fk_target_field_id)
+        self-referencing (filter self-ref-attr objs)
+        others           (set/difference (set objs) (set self-referencing))]
+    ;; first insert the non-self-referencing objects
+    (insert-entity e others)
+    ;; then insert the rest, which should be safe to insert now
+    (insert-entity e self-referencing)))
+
+(defn- set-postgres-sequence-values []
```
Comment (camsaul) [inline src/metabase/cmd/load_from_h2.clj]: This should end in a `!` because it has side effects

File: src/metabase/cmd/load_from_h2.clj [hunk 3]
```diff
@@ -67,27 +71,77 @@
...
+    (print (color/blue \.))
+    (flush)
+    (k/insert e (k/values (if (= e DashboardCard)
+                            ;; mini-HACK to fix korma/h2 lowercasing these couple attributes
+                            ;; luckily this is the only place in our schema where we have camel case names
+                            (mapv #(set/rename-keys % {:sizex :sizeX, :sizey :sizeY}) chunk)
+                            chunk))))
+  (println (color/green "[OK]")))
+
+(defn- insert-self-referencing-entity [e objs]
```
Comment (camsaul) [inline src/metabase/cmd/load_from_h2.clj]: This should end in a `!` because it has side effects

File: src/metabase/cmd/load_from_h2.clj [hunk 4]
```diff
@@ -67,27 +71,77 @@
...
+
+(def ^:private entities-without-autoinc-ids
+  "Entities that do NOT use an auto incrementing ID column."
+  #{Setting Session})
+
+(def ^:private ^:dynamic *db-conn*
+  "Active database connection to the target database we are loading into."
+  nil)
+
+(defn- insert-entity [e objs]
```
Comment (camsaul) [inline src/metabase/cmd/load_from_h2.clj]: Same thing. `!`

File: src/metabase/cmd/load_from_h2.clj [hunk 5]
```diff
@@ -67,27 +71,77 @@
...
+  (print (u/format-color 'blue "Setting postgres sequence ids to proper values..."))
+  (flush)
+  (doseq [e    (filter #(not (contains? entities-without-autoinc-ids %)) entities)
+          :let [table-name (:table e)
+                seq-name   (str table-name "_id_seq")
+                sql        (format "SELECT setval('%s', COALESCE((SELECT MAX(id) FROM %s), 1), true) as val" seq-name table-name)]]
+    (jdbc/db-query-with-resultset *db-conn* [sql] :val))
+  (println (color/green "[OK]")))
+
 (defn load-from-h2
```
Comment (camsaul) [inline src/metabase/cmd/load_from_h2.clj]: This should definitely be called `load-from-h2!` because it's writing to a DB
