### PR TITLE
fix click behavior on pie charts

### LINKED ISSUE #15250: Click Behavior not parsing measure value for first row on Pie chart
**Describe the bug**
Click Behavior not parsing measure value(s) for first row on Pie chart

**To Reproduce**
1. Simple question > Sample Dataset > Products
2. Summarize Count by Category, and change visualization to Pie chart
image
3. Add to dashboard and add "Click Behavior" - any type (custom destination/cross filter) - save dashboard
4. Hover the Doohickey slice (which is the first result row) with Count 42 and click - the value `42` is not parsed along.

**Information about your Metabase Installation:**
Tested 0.37.0 thru 0.38.2

Related to #13597

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/15250

Please check the original issue for repro steps. The reason is an incorrect implicit boolean conversion of `0` — that is why it did not work only for the first row.

### CODE REVIEW

**Review by flamber — APPROVED** [review]
Well, that makes a lot of sense why the first row didn't play nice.

File: frontend/src/metabase/visualizations/visualizations/PieChart.jsx [hunk 1]
```diff
@@ -439,6 +439,7 @@ export default class PieChart extends Component {
           </div>
           <div className={cx(styles.Chart, "layout-centered")}>
             <svg
+              data-testid="pie-chart"
```
Comment (nemanjaglumac) [inline frontend/src/metabase/visualizations/visualizations/PieChart.jsx:442]: 🚀
