### PR TITLE
Use mongo field filter alias if available

### LINKED ISSUE #66888: Field filter alias doesn't work on MongoDB
### Describe the bug

Field filter alias does not apply on MongoDB

### To Reproduce

1. Create a new native question on MongoDB, e.g. I have a People collection:
```
[
  {
    "$project": {
      "_id": "$_id",
      "name": "$name",
      "age": "$age"
    }
  },
  {
    "$match": {{test}}
  }
  {
    "$limit": 1048575
  }
]
```
2. Set up the field filter to point to a field, then set anything to its alias
Image

3. Set a value to the filter and preview its output - the alias is not applied

### Expected behavior

It should either apply the alias or not show the option to do it

### Logs

_No response_

### Information about your Metabase installation

```JSON
v57.5.1
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/66888

### Description

Uses the the field filter alias for mongo if it is provided

### How to verify

1. Create a mongo query on the orders table and join it with the products table
2. Add a filter by a column in the products table
3. Convert to a native query
4. Replace the `match` from the product column filter with a field filter variable
5. See that it fails without adding a field alias
6. Add the correct field alias
7. See that it works

### Demo

https://www.loom.com/share/aaad69d3a11c446baf938369c52446d6

<details> 

<summary> before and after</summary>

| before | after | 
| --- | --- |
|   Screenshot 2025-12-16 at 11 16 26 AM |   Screenshot 2025-12-16 at 11 15 36 AM  |

</details>

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo/parameters.clj [hunk 1]
```diff
@@ -64,24 +64,27 @@
...
 
   ([field :- driver-api/schema.metadata.column
+    alias
     pr?]
    ;; for native parameters we serialize and don't need the extra pr
-   (cond-> (mongo.qp/field->name field ".")
+   (cond-> (if (str/blank? alias)
+             (mongo.qp/field->name field ".")
+             alias)
      pr? pr-str)))
```
Comment (ericnormand) [inline modules/drivers/mongo/src/metabase/driver/mongo/parameters.clj]: @rileythomp It's not your fault, but this is a bad function. We should not pass in a boolean that determines whether we do extra processing. And it's only used in one place! Here are some options for getting rid of `pr?`:

1. Change the name to `native?` (per the comment).
2. Add quotes to the `format` expressions to be more clear that quotes are added around names in certain places.
3. Add an explicit `pr-str` at the appropriate call sites.
4. Make another function that doesn't pr-str and call that in the one place we don't use it.

It makes sense to improve this function in this PR because you're changing every call site.

File: modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj [hunk 2]
```diff
@@ -480,3 +480,98 @@
                                                                             :snippet-name "first 3 checkins"
                                                                             :snippet-id   (:id snippet)}}}
                   :parameters []}))))))))
+
+(deftest ^:parallel field-filter-variable-with-alias-test
+  (testing "native query with field filter variable and a field alias works"
+    (mt/test-driver :mongo
+      (let [query (mt/native-query
+                   {:collection "orders"
```
Comment (ericnormand) [inline modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj:488]: Is there a simpler query that would reproduce the bug?

File: modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj [hunk 3]
```diff
@@ -480,3 +480,98 @@
...
+                                          "count" true}}])
+                    :template-tags {"category_filter" {:id "category_filter_id"
+                                                       :name "category_filter"
+                                                       :display-name "Category Filter"
+                                                       :type :dimension
+                                                       :dimension [:field (mt/id :products :category) nil]
+                                                       :alias "join_alias_Products.category"
+                                                       :widget-type :string/=
+                                                       :default ["Gizmo"]}}})]
+        (is (= [[4784]]
```
Comment (ericnormand) [inline modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj]: This asserts too much. The original bug was that it returned no results. The complex query plus exact rows returned makes it hard to understand. I would change it to `(is (seq (-> ...`

File: modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj [hunk 4]
```diff
@@ -480,3 +480,98 @@
...
+               (-> query qp/process-query mt/rows)))))))
+
+(deftest ^:parallel field-filter-date-range-with-alias-test
+  (testing "native query with date range filter and a field alias works"
+    (mt/test-driver :mongo
+      (let [query (mt/native-query
+                   {:collection "orders"
```
Comment (ericnormand) [inline modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj:511]: Ditto on complex query and assertion.

File: modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj [hunk 5]
```diff
@@ -480,3 +480,98 @@
...
+                                                   :alias "join_alias_Products.created_at"
+                                                   :widget-type :date/all-options
+                                                   :default "past6years"}}})]
+        (is (= [[1697]]
+               (-> query qp/process-query mt/rows)))))))
+
+(deftest ^:parallel field-filter-single-date-with-alias-test
+  (testing "native query with date field filter and a field alias works"
+    (mt/test-driver :mongo
+      (let [query (mt/native-query
```
Comment (ericnormand) [inline modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj:533]: Ditto on complex query and assertion.

**Review by ericnormand — CHANGES_REQUESTED** [review]

File: modules/drivers/mongo/src/metabase/driver/mongo/parameters.clj (hunk 1 above)
Comment (rileythomp) [reply modules/drivers/mongo/src/metabase/driver/mongo/parameters.clj]: Fair, I made it do `pr-str` unconditionally and copied the "alias or field" logic to the one call site that doesn't use `pr-str`

**Review by ericnormand — APPROVED** [review]
