### PR TITLE
Not retrying to send notifications to missing slack channels (#49647)

### LINKED ISSUE #49647: [Notification] We shouldn't retry sending slack if it has error "channel_not_found"
### Describe the bug

When sending notifications to a slack channel that's no longer exists, we keep retrying until the retry attempts are maxed-out.
The retry mechanism includes uploading the assets and posting the message.

This is necessary, we should stop sending the channel at the first attempt and have the task_history.status = failed.

### To Reproduce

1. On slack: create a channel "testing-alert" 
2. On metabase: Setup slack connection
3. Create an alert that send to "testing-alert" channel
4. Delete the "testing-alert" channel
5. Trigger sending the "alert"

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

master

### Severity

p3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amuradyan**
> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [Crowdin project](https://crowdin.com/project/metabase-i18n) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/49647

### Description

We're categorizing the _channel not found_ error in the slack integration and passing it upwards, where the retry decision is made in `should-retry-sending?`. The latter is extended to manage the new error.

### How to verify

Create an alert with a missing slack channel and sent one. In the logs you should see the following message.
  🔍 The Slack channel you've configured doesn't exist. Please update it.

Plus there's a test verifying we don't retry.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/integrations/slack.clj [hunk 1]
```diff
@@ -118,15 +118,20 @@
...
-                          :message    message
-                          :response   body})]
+        missing-channel? (= (:error body) "channel_not_found")
+        message        (cond
+                         invalid-token? "Invalid token"
+                         missing-channel? "Channel not found"
+                         :else (format "Slack API error: %s" (:error body)))
+        error          (cond
+                         invalid-token? {:error-code (:error body)
+                                         :errors     {:slack-token message}}
```
Comment (qnkhuat) [inline src/metabase/integrations/slack.clj:128]: I know it's an existing pattern but I don't think having the message here is useful. I don't think we use it anywhere.

In fact, inside `metabase.notification.send/should-retry-sending?` we're using the existent of a key to determine the error type.

I propose we instead replace this errors map with an `:error-type` key with 3 possible values: `:slack/invalid-token, :slack/channel-not-found, :slack/unknown`.

Let me know if you're interested in improving this.

**Review by qnkhuat — COMMENTED** [review]
Thanks for the PR! Have a suggestion to improve the mechanics.

File: src/metabase/integrations/slack.clj [hunk 2]
```diff
@@ -137,6 +142,8 @@
     (when invalid-token?
       (log/warn (u/colorize :red (str "🔒 Your Slack authorization token is invalid or has been revoked. Please"
                                       " update your integration in Admin Settings -> Slack."))))
+    (when missing-channel?
+      (log/warn (u/colorize :red "🔍 The Slack channel you've configured doesn't exist. Please update it.")))
```
Comment (amuradyan) [inline src/metabase/integrations/slack.clj:146]: I tried to log the channel name here as well but it's lost somewhere higher in the calls. Do you think I should pull that in as well?

**Comment by qnkhuat** [comment]
Cool! Running CI in https://github.com/metabase/metabase/pull/55309: once it's green we can merge this.

File: src/metabase/integrations/slack.clj [hunk 3]
```diff
@@ -117,16 +117,15 @@
...
-                          :response   body})]
+  (let [invalid-token?   (slack-token-error-codes (:error body))
+        missing-channel? (= (:error body) "channel_not_found")
+        message          (format "Slack API error: %s" (:error body))
+        error-stub       {:error-code (:error body)
+                          :error-type :slack/unknown}
+        error            (cond
+                           invalid-token?   (assoc error-stub :error-type :slack/invalid-token)
+                           missing-channel? (assoc error-stub :error-type :slack/channel-not-found)
+                           :else            (assoc error-stub :response body))]
```
Comment (qnkhuat) [inline src/metabase/integrations/slack.clj:128]: another way to shorten this cond is to use `cond->`


```clojure
(cond-> {:error-code (:error body)
                           :error-type :slack/unknown}
                     invalid-token?   (assoc :error-type :slack/invalid-token)
                     missing-channel? (assoc :error-type :slack/channel-not-found)
                     true            (assoc :response body))
```

File: src/metabase/integrations/slack.clj (hunk 2 above)
Comment (qnkhuat) [reply src/metabase/integrations/slack.clj:140]: I don't think we need this log tbh. we have the log for invalid-token because it's instance wide error. this missing channel is per-notification and we'll log this in task history.

**Comment by qnkhuat** [comment]
Looks like we have some failing tests: https://github.com/metabase/metabase/actions/runs/13914028538/job/38933690000?pr=55309#step:4:1265

File: src/metabase/integrations/slack.clj (hunk 2 above)
Comment (amuradyan) [reply src/metabase/integrations/slack.clj:140]: Agreed. I'll remove it.

File: src/metabase/integrations/slack.clj (hunk 3 above)
Comment (amuradyan) [reply src/metabase/integrations/slack.clj:128]: Thanks. I'm new to Clojure, so any tips you have are welcome.

**Comment by amuradyan** [comment]
> Looks like we have some failing tests: https://github.com/metabase/metabase/actions/runs/13914028538/job/38933690000?pr=55309#step:4:1265

My bad, let me fix this. Is there a way to run only the affected tests under a watcher?

File: src/metabase/integrations/slack.clj (hunk 3 above)
Comment (amuradyan) [reply src/metabase/integrations/slack.clj:128]: Oh, but this form does not short circuit so the `:response` will always be in the map. Is that something we want?

**Comment by qnkhuat** [comment]
The recommended way to develop and running tests is through a repl, depend on your editors and plugins you use, you can probably find a shortcut to run tests.

Alternative, you can do
```clojure
(clojure.test/run-test-var #'metabase.integrations.slack-test/users-list-test)
```
in the repl to run a test.

From the command line:

```
clj -X:dev:ee:ee-dev:test :only metabase.integrations.slack-test
```

which run all tests in that namespace.

Or

```
clj -X:dev:ee:ee-dev:test :only metabase.integrations.slack-test/users-list-test
```

to run a specific test.

**Comment by amuradyan** [comment]
> ```
> clj -X:dev:ee:ee-dev:test :only metabase.integrations.slack-test/users-list-test
> ```
> 
> to run a specific test.

Actually I was doing something like that with `entr`, e.g. 

    find test/metabase/pulse -type f -name '*test*.clj' | entr clojure -X:dev:test :only metabase.pulse.send-test

, but I was hoping for a more _out-of-the-box_ approach. Thanks a lot!

**Comment by qnkhuat** [comment]
Re-running CI

**Comment by qnkhuat** [comment]
There is a conflict with one of PR I've recently merged: https://github.com/metabase/metabase/pull/55312 (which thanks to you because I found a bug when reviewing your PR).

Could you resolve the conflicts?

**Comment by qnkhuat** [comment]
just one more to go: ERROR in metabase.notification.send-test/slack-notification-retry-test (ERROR in metabase.notification.send-test/slack-notification-retry-test )

**Comment by amuradyan** [comment]
Done and done. The retry test error sneaked in via an accidental undo.

**Review by qnkhuat — APPROVED** [review]
Tests passed 🎉 Thanks for your contribution!

**Comment by amuradyan** [comment]
@qnkhuat wonderful. Will it be merged automatically or should someone do it? What happens next?

**Comment by amuradyan** [comment]
@qnkhuat  Also, I was planning to look into something else and picked #32822, but maybe you would suggest something else? My filter is backend good first issues.

**Comment by qnkhuat** [comment]
@amuradyan that's one is a rabbit hole and require some deep understanding.

Wanna take a look at this one? : https://github.com/metabase/metabase/issues/39021

**Comment by amuradyan** [comment]
> @amuradyan that's one is a rabbit hole and require some deep understanding.

Maybe we should remove the good-first-issue tag from it?

> Wanna take a look at this one? : #39021

Sure, thanks a lot.
