### PR TITLE
handle display of 0 in the number picker

### LINKED ISSUE #4373: Numeric column filter value disappears from UI when set to zero
Steps to reproduce:

1. start new question, choose ie. sample dataset / orders table
2. click "filtered by" field, choose "total" field
3. choose "greater than" 
4. in the "enter desired number" field enter 0 (zero)
5. click "add filter"
6. click the filter again

The "enter desired number" field is empty. Instead it should have "0" (zero) in it.

7. enter "1" into "enter desired number" and click "add filter"
8. click the filter again

Now it shows the filter value. 

It looks like somewhere in the code "0" is assumed to be equal to "null" or empty string. 

This is IMHO very low priority minor issue, but since I've noticed it I decided to report it.

Chrome 56.0 on Mac OS 10.12.2
Postgres 9.4 database
Metabase 0.22.2 self-hosted on linux server
Metabase internal database: H2

### PR DESCRIPTION
**Pull request by kdoh**
fixes #4373 

Turns out `String(0 || "")`(which is what we were passing to the textfield to display the selected value) will always return an empty string which is why even though a value was selected it was showing up blank. This is due to javascript being `neat and cool`. This is a "dumb" fix. Dunno if @attekei or @tlrobinson have a more elegant way to handle the checking here.

### CODE REVIEW

**Comment by attekei** [comment]
The `isEmpty` of Ramda/Lodash treat this scenario correctly but Underscore.js which we are currently using doesn't, so I don't have a direct answer.

Why are we showing empty text instead of explicitly indicating that something is wrong with the value?

**Comment by kdoh** [comment]
@attekei I think the original intent was to return an empty string in cases where there is no value which happens when you're creating a new filter since we reuse this component for new and existing filters.

File: frontend/src/metabase/query_builder/components/filters/pickers/NumberPicker.jsx [hunk 1]
```diff
@@ -23,7 +23,12 @@ export default class NumberPicker extends Component<*, Props, State> {
     constructor(props: Props) {
         super(props);
         this.state = {
-            stringValues: props.values.map(v => String(v || "")),
+            stringValues: props.values.map(v => {
+                if(v === 0) {
+                    return String(v)
+                }
+                return String(v || "")}
```
Comment (tlrobinson) [inline frontend/src/metabase/query_builder/components/filters/pickers/NumberPicker.jsx]: brace should go on the next line.

also I'd probably do 

```
if (typeof v === "number") {
  return String(v);
} else {
  return String(v || ");
}
```

**Review by tlrobinson — CHANGES_REQUESTED** [review]

**Review by attekei — APPROVED** [review]
