### PR TITLE
Pivot Measures Order Used in Pivot Exports

### LINKED ISSUE #48442: Pivot Table Column reordering from Visualization UI doesn't reflect in downloaded files
### Describe the bug

If you order the columns for a Pivot Table via the UI, they will show up in the Visual but will not reflected in downloaded files:

 Image

It only works if you order them form the editor section:

Image

### To Reproduce

1. Go toNew ->  Question -> Products -> Count and Sum of Rating -> Grouped by Created At -> Turn into a Pivot

Image

2.Re-order the columns from the UI

Image

3. Download the Pivot and notice that the order didn't match the Pivot

Image

You can test this on stats https://stats.metabase.com/question/20058-test

### Expected behavior

The download should be an exact copy of what you get presented in the UI

### Logs

None that are relevant

### Information about your Metabase installation

Tested on 50.28 and master

### Severity

It's very annoying if you don't know about this bug. 

### Additional context

There is a workaround in which you need to go and order the columns from the editor

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes #48442

A pivot table can have any number of measures, and the user can order these by dragging in the UI. Before this PR, that order was ignored and measures would always be in index order, which is confusing for any user who needs the measures to be displayed in a particular order, especially if they've re-ordered them in the pivot viz settings UI.

A test has been added to check that measure order is used.

A few minor changes to the pivot qp and post-processor
 - measure indices are looked up in the pivot qp and added in viz-settings order
 - the pivot measures are only added if the qp has not already added them.
 - pivot-opts Malli spec has been made in the namespace, adjusted to allow `nil` as a valid pivot-opts output, and used in relevant functions

### CODE REVIEW

File: src/metabase/query_processor/pivot.clj [hunk 1]
```diff
@@ -342,48 +347,52 @@
...
+        breakouts             (into []
+                                    (map-indexed (fn [i col]
+                                                   (cond-> col
+                                                     true                         (assoc ::i i)
+                                                     ;; if the col has a card-id, we swap the :lib/source to say source/card
+                                                     ;; this allows `lib/find-matching-column` to properly match a column that has a join-alias
+                                                     ;; but whose source is a model
+                                                     (contains? col :lib/card-id) (assoc :lib/source :source/card))))
+                                    (concat (lib/breakouts-metadata mlv2-query)
+                                            (lib/aggregations-metadata mlv2-query)))
```
Comment (adam-james-v) [inline src/metabase/query_processor/pivot.clj:372]: Key change here is adding the aggregations metadata to the list of checked cols. This is necessary since the :pivot-measures must be aggregations.

File: test/metabase/api/downloads_exports_test.clj [hunk 2]
```diff
@@ -1061,32 +1061,72 @@
...
+                   formatted-results))
             (is (= {:unsaved-card-download    [["A"] [1234.567]]
                     :card-download            [["A"] [1234.567]]
                     :public-question-download [["A"] [1234.567]]
                     :dashcard-download        [["A"] [1234.567]]
                     :public-dashcard-download [["A"] [1234.567]]}
-                   unformatted-json-results))))))))
+                   unformatted-results))))))))
+
+(deftest pivot-measures-order-test
```
Comment (escherize) [inline test/metabase/api/downloads_exports_test.clj:1094]: is it worth adding tests for rows/columns/measures independently? Might be nice if one of them fails to figure out what's going on sooner.

File: src/metabase/query_processor/pivot.clj [hunk 3]
```diff
@@ -529,10 +538,11 @@
...
              query             (lib/query (qp.store/metadata-provider) query)
-             pivot-options     (or
-                                (not-empty (select-keys query [:pivot-rows :pivot-cols]))
-                                (pivot-options query (get-in query [:info :visualization-settings])))
-             query             (assoc-in query [:middleware :pivot-options] pivot-options)
-             all-queries       (generate-queries query pivot-options)
+             pivot-opts        (or
+                                (pivot-options query (get query :viz-settings))
+                                (pivot-options query (get-in query [:info :visualization-settings]))
+                                (not-empty (select-keys query [:pivot-rows :pivot-cols :pivot-measures])))
```
Comment (escherize) [inline src/metabase/query_processor/pivot.clj:544]: Is it worth adding tests to make sure we follow the precedence order for these 3 pivot-opts sources?

e.g. make sure `(not-empty (select-keys query [:pivot-rows :pivot-cols :pivot-measures]))` beats `(get-in query [:info :visualization-settings])` etc

**Review by escherize — APPROVED** [review]
Looks good, just some styling requests, and questions about test coverage. 👍
