### PR TITLE
Fix archived personal sub-collections are displayed in the sidebar

### LINKED ISSUE #15343: Sub-collection in Personal Collections shows in sidebar hierarchy even after they are archived
**Describe the bug**
It is not possible to get rid of (sub) collections that live inside users' personal collections after they are archived. At first I thought it's just a UI glitch that requires a page reload. Nope - it simply won't go away. That creates a bunch of new issues because it is possible to edit such (archived) collection, add questions/dashboards/new collections to it, etc.

The weirdest possible thing is that if you look inside the archive, it lives there as well 👽

**Logs**
Examining `GET /api/collection/:id` (when loading UI) will show that such collection has archived attribute already set.
`archived: true`

**To Reproduce**
1. Go to your own personal collection
2. Add new collection to it (call it "Foo")
3. Navigate inside newly created (sub) collection
4. Click pencil icon
5. Choose "Archive this collection" (confirm by clicking "Archive" button in the modal)
6. You will see that "Foo" is still visible in the sidebar
7. Refresh the page - "Foo" collection is still there
    - if you examine the GET request like I described above, you'll see that this collection has `archived: true`
8. Click on "View archive" in bottom left corner (Go to archive)
9. You will see that "Foo" collection shows inside archive

**Expected behavior**
Archived collection should immediately vanish from the UI and should live in "Archive" only!

**Screenshots**
N/A

**Information about your Metabase Installation:**
- Metabase version: v0.38.3-SNAPSHOT
- Metabase hosting environment: local dev, release-x.38.x
- Metabase internal database: H2 (default), sample dataset

**Severity**
I'd say P2. This shouldn't happen at all.

**Additional context**
N

### PR DESCRIPTION
**Pull request by kulyk**
Fixes #15343 

Fixes archived personal sub-collections are displayed in the sidebar collection three

The easiest fix is to filter them on the client (as it's done now), but it looks like a thing that ideally has to be done on the server side. Also, I've seen a few cases where frontend could be radically simplified if we move some filtering parts to the backend (e.g. [filtering items by permissions](https://github.com/metabase/metabase/pull/15613)). Should we think about that?

### CODE REVIEW

**Review by kdoh — APPROVED** [review]
Looks good, although I'd recommend also filing a ticket to highlight that this could also be handled at the API level like the comment says.

**Comment by nemanjaglumac** [comment]
Is this intentionally targeted to `master` instead of `release-x.39.x` branch?

**Comment by kulyk** [comment]
> Is this intentionally targeted to `master` instead of `release-x.39.x` branch?

Thanks for raising that, it's actually a thing I'm a bit unaware of. Can you help me figure this out?
We're going to release 0.39 today, the bug bash is done, should I still target `release-x.39.x`?

**Comment by nemanjaglumac** [comment]
> Thanks for raising that, it's actually a thing I'm a bit unaware of. Can you help me figure this out?
> We're going to release 0.39 today, the bug bash is done, should I still target `release-x.39.x`?

I would say - yes. It definitely doesn't belong to `master` because those changes are meant for 0.40. I understand your concern re: pushing the changes in the last minute before the release, but 39 will have minor version fixes anyway. So, anything that we merge into `release-x.39.x` will bu published in those subsequent minor releases.

Just for the future reference - let's say some change/dix is reaaaaaally tricky and you're reluctant to merge it prior to the release. Even then you shouldn't merge it to `master` but rather wait for the official release and then merge it in a realease branch (it will have enough time until the next "patch").

Hope this helps?

**Comment by kulyk** [comment]
> > Thanks for raising that, it's actually a thing I'm a bit unaware of. Can you help me figure this out?
> > We're going to release 0.39 today, the bug bash is done, should I still target `release-x.39.x`?
> 
> I would say - yes. It definitely doesn't belong to `master` because those changes are meant for 0.40. I understand your concern re: pushing the changes in the last minute before the release, but 39 will have minor version fixes anyway. So, anything that we merge into `release-x.39.x` will bu published in those subsequent minor releases.
> 
> Just for the future reference - let's say some change/fix is reaaaaaally tricky and you're reluctant to merge it prior to the release. Even then you shouldn't merge it to `master` but rather wait for the official release and then merge it in a release branch (it will have enough time to get checked and observed until the next "patch" release).
> 
> Hope this helps?

Yes, thank you! I'll rebase the branch on `master`. But should we do something with #15670 now?

**Comment by nemanjaglumac** [comment]
> But should we do something with #15670 now?

Like Flamber [suggested](https://github.com/metabase/metabase/pull/15670#issuecomment-822592578), just cherry-pick that commit and it should be ok.

**Comment by nemanjaglumac** [comment]
Just noticed one thing.
After you archive a collection which was the only child, parent still has chevron icon even though it is empty. You already fixed that issue, I believe. This seems to be the edge case.

Do you mind trying to fix that in this same PR or do you prefer we open a separate issue for it?

File: frontend/src/metabase/collections/containers/CollectionSidebar.jsx [hunk 1]
```diff
@@ -46,24 +46,31 @@ class CollectionSidebar extends React.Component {
...
-  componentDidMount() {
-    // an array to store the ancestors
-    const { collectionId, collections, loading } = this.props;
-    if (!loading) {
-      const ancestors = getParentPath(collections, Number(collectionId)) || [];
-      this.setState({ openCollections: ancestors });
-    }
-  }
+
+  // TODO Should we update the API to filter archived collections?
```
Comment (daltojohnso) [inline frontend/src/metabase/collections/containers/CollectionSidebar.jsx:71]: A personal preference on my part but I'd prefer we avoid adding theoretical TODOs since they are often quickly forgotten about.

**Review by daltojohnso — APPROVED** [review]
looks good!

**Comment by kulyk** [comment]
@nemanjaglumac the issue with chevron icons should be fixed now. Added a test to check we won't miss it again. That's for being on the lookout!

**Review by daltojohnso — APPROVED** [review]
