### PR TITLE
Null out invalid dates and warn users

### LINKED ISSUE #10020: Bug in auto convert data to date
Metabase version `0.32.5`

When the X axis value is week of format `%Y-W%U`, metabase automatically convert them into date, but it seems the grouping process is too forceful and cause data week 52 of previous year to merge with week 0 if this year. 

Is there a way not to do this?

The data week label:
Screen Shot 2019-05-22 at 2 31 36 PM

This is data when visualzie: The peak is an abnormally high value which is wrong:
Screen Shot 2019-05-22 at 2 23 36 PM

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #10020 

The issue occurred because some of the weeks were invalid according to moment.js (e.g. '2019-W00'). Invalid dates would lead to NaNs in crossfilter dimensions which would break things and sum values for distinct weeks.

The core of this PR is to add a warning for invalid dates and null them out to prevent summing their values:
```js
if (!m.isValid()) {
  warn(createInvalidDateWarning(value));
  return null;
}
```

Most of the diff is updating how the warnings work. Previously, we called `warn` with a string that would both dedupe warnings and be displayed to the user. I wanted to include a row-specific example date in the warning but still dedupe by warning type, so I split out `key` and `text` fields. We dedupe by `key`, but only display `text` to the user. The diff is noisy from updating existing warnings.

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js [hunk 1]
```diff
@@ -72,10 +72,12 @@ import type { VisualizationProps } from "metabase/meta/types/Visualization";
 const BAR_PADDING_RATIO = 0.2;
 const DEFAULT_INTERPOLATION = "linear";
 
-const UNAGGREGATED_DATA_WARNING = col =>
-  t`"${getFriendlyName(
+const UNAGGREGATED_DATA_WARNING = col => ({
+  key: UNAGGREGATED_DATA_WARNING,
```
Comment (tlrobinson) [inline frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js]: I think `key` should be a string rather than the function itself.

Also for a bit of cleanup, maybe move these all to frontend/src/metabase/visualizations/lib/warnings.js and make them all functions, following this form (with or without the `create` prefix):

```
export const UNAGGREGATED_DATA_WARNING = "UNAGGREGATED_DATA_WARNING";

export function unaggregatedDataWarning(col) {
  return {
    key: UNAGGREGATED_DATA_WARNING,
    text: ...
  }
}
```

**Review by tlrobinson — CHANGES_REQUESTED** [review]
Just some cleanup suggestions

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js (hunk 1 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js]: whoops! I meant to make it a string but forgot quotes. 

Consolidating sounds good!

**Review by tlrobinson — APPROVED** [review]
