### PR TITLE
Can't choose recently viewed link with the mouse when editing dashboard link card #35037

### LINKED ISSUE #35037: Can't choose recently viewed link with the mouse when editing dashboard link card
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/9d7877b5-79e8-4dfb-9585-033b7f6c9834

### To Reproduce

1. Create a new dashboard A, visit it.
2. Create a new dashboard B.
3. Add a link card to it
4. A dropdown with "Recently viewed" items will appear
5. Click the first entry in it with a mouse

You're being redirected to that link.

### Expected behavior

The clicked item should be chosen as a link for the link card

### Logs

_No response_

### Information about your Metabase installation

```JSON
`master`
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by oisincoveney**
Closes https://github.com/metabase/metabase/issues/35037

### Description

Ensures that clicking on a search/recents entry only triggers the onClick action, rather than the href/redirect behavior that the issue brings up.

_What Changed:_
- Added a new prop `isEnabled` to the InfoTextTableLink component.
- Modified the href attribute of a ResultTitle component.

### How to verify
 
- Create a new dashboard A, save it and visit it
- Create a new dashboard B and edit it.
- Add a link card to it
- A dropdown with "Recently viewed" items will appear
- Click header of the first entry in it with a mouse

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by oisincoveney** [comment]
Current dependencies on/for this PR:
* master
  * **PR #35042** <a href="https://app.graphite.dev/github/pr/metabase/metabase/35042" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/35042?utm_source=stack-comment).

File: frontend/src/metabase/nav/components/search/RecentsList/util.ts [hunk 1]
```diff
@@ -14,5 +14,7 @@ export const isItemActive = ({ model, model_object }: RecentItem) => {
   return isSyncCompleted(model_object);
 };
 
-export const getItemUrl = (item: RecentItem) =>
-  isItemActive(item) ? Urls.modelToUrl(item) : "";
+export const getItemUrl = (item: RecentItem) => {
+  const url = isItemActive(item) && Urls.modelToUrl(item);
```
Comment (oisincoveney) [inline frontend/src/metabase/nav/components/search/RecentsList/util.ts:18]: - Ensures that we only get a string or `undefined`
- Uses `undefined` because `href`  on `Anchor` only accepts `string | undefined` so just adapting to that.

File: frontend/src/metabase/nav/components/search/RecentsList/RecentsListContent.tsx [hunk 2]
```diff
@@ -80,7 +80,7 @@ export const RecentsListContent = ({
                   <ResultTitle
                     data-testid="recently-viewed-item-title"
                     truncate
-                    href={getItemUrl(item) ?? undefined}
+                    href={!onClick ? getItemUrl(item) : undefined}
```
Comment (kamilmielnik) [inline frontend/src/metabase/nav/components/search/RecentsList/RecentsListContent.tsx:83]: The logic is simpler without the negation:

```suggestion
                    href={onClick ? undefined: getItemUrl(item)}
```

File: frontend/src/metabase/search/components/InfoText/InfoText.tsx [hunk 3]
```diff
@@ -26,6 +26,7 @@ import { LastEditedInfoText, LastEditedInfoTooltip } from "./InfoText.styled";
 export type InfoTextProps = {
   result: WrappedResult;
   isCompact?: boolean;
+  isEnabled?: boolean;
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoText.tsx:29]: 1. Using `disabled` would be more aligned with [DOM nomenclature](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled).
2. `InfoTextEditedInfo` does not make use of that prop, yet it uses this very interfece. It's misleading, as it suggests it does support that prop. Similarly, `isCompact` is used in only one of the components here. This would not be a problem if each component lived in a separate file and had its own explicit `Props` definition.

File: e2e/test/scenarios/dashboard/reproductions/35037-recently-viewed-link-editing-dashboard-link-card.cy.spec.js [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+    cy.intercept("GET", "/api/activity/recent_views").as("recentViews");
+  });
+
+  it("should not redirect users to recent item", () => {
+    visitDashboard(ORDERS_DASHBOARD_ID);
+    // get the URL of page and store it in a variable
+    const initialUrl = cy.url();
+
+    editDashboard();
+    createLinkCard();
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard/reproductions/35037-recently-viewed-link-editing-dashboard-link-card.cy.spec.js:26]: Can you please inline it? :pray: 
Just to avoid conflicts with [my PR](https://github.com/metabase/metabase/pull/34899) where [I removed this function](https://github.com/metabase/metabase/pull/34899/commits/0f53956d0657ed77998b5ee3df3f0331c2956f5a).

```suggestion
    cy.icon("link").click();
```

and in one more place below.

File: frontend/src/metabase/search/components/InfoText/InfoText.tsx [hunk 5]
```diff
@@ -63,33 +64,56 @@ export const InfoTextTableLink = ({ result }: InfoTextProps) => {
...
     db: { id: result.database_id },
     schema_name: result.table_schema,
   });
 
   return (
     <>
-      <SearchResultLink key={result.table_schema} href={link}>
+      <SearchResultLink
+        isEnabled={isEnabled}
+        key={result.table_schema}
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoText.tsx:104]: 1. Wrapping fragment is redundant
2. `key` is redundant (also in other components here)

File: frontend/src/metabase/search/components/InfoText/InfoText.tsx [hunk 6]
```diff
@@ -104,30 +128,37 @@ export const InfoTextTablePath = ({ result }: InfoTextProps) => {
...
     <>
-      {showDatabaseLink && <DatabaseLink database={database} />}
+      {showDatabaseLink && (
+        <DatabaseLink isEnabled={isEnabled} database={database} />
+      )}
       {showTableLink && (
         <>
           {LinkSeparator}
-          <TableLink result={result} />
+          <TableLink isEnabled={isEnabled} result={result} />
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoText.tsx:137]: nit: If you're bothered by too much props passing, we could inline `DatabaseLink` and `TableLink` components here, as they're small and only used here.

File: e2e/test/scenarios/dashboard/reproductions/35037-recently-viewed-link-editing-dashboard-link-card.cy.spec.js [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+    restore();
+    cy.signInAsAdmin();
+    cy.intercept("GET", "/api/search?q=*").as("search");
+    cy.intercept("GET", "/api/activity/recent_views").as("recentViews");
+  });
+
+  it("should not redirect users to recent item", () => {
+    visitDashboard(ORDERS_DASHBOARD_ID);
+    // get the URL of page and store it in a variable
+    const initialUrl = cy.url();
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard/reproductions/35037-recently-viewed-link-editing-dashboard-link-card.cy.spec.js:23]: That comment brings no value.

```suggestion
    const initialUrl = cy.url();
```

**Review by kamilmielnik — COMMENTED** [review]
The issue is fixed and tests look good.
I think component interfaces could be improved.

File: frontend/src/metabase/search/components/InfoText/InfoText.tsx (hunk 6 above)
Comment (oisincoveney) [reply frontend/src/metabase/search/components/InfoText/InfoText.tsx:137]: It'll be fine for now

File: frontend/src/metabase/search/components/InfoText/InfoText.tsx (hunk 3 above)
Comment (oisincoveney) [reply frontend/src/metabase/search/components/InfoText/InfoText.tsx:29]: I don't think using `disabled` makes sense here - `disabled` usually implies that there's a clickable element that's grayed out (like a disabled link) but here we just want some text.

On the `InfoTextEditedInfo` thing we can do that in a separate PR specifically for that - let's not muddy this PR with extra things. I can make the changes to the props here though.

Comment (oisincoveney) [reply frontend/src/metabase/search/components/InfoText/InfoText.tsx:10]: Ok split it a little bit

Comment (kamilmielnik) [reply frontend/src/metabase/search/components/InfoText/InfoText.tsx:10]: > I don't think using `disabled` makes sense here - `disabled` usually implies that there's a clickable element that's grayed out (like a disabled link) but here we just want some text.

In that case, given that `isEnabled` is semantically an inverse of `disabled`, should we call it `showLinks`?

File: frontend/src/metabase/search/components/InfoText/InfoTextEditedInfo.tsx [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+import { t } from "ttag";
+import { isNull } from "underscore";
+import type { UserListResult } from "metabase-types/api";
+import { useUserListQuery } from "metabase/common/hooks/use-user-list-query";
+import Tooltip from "metabase/core/components/Tooltip";
+import { isNotNull } from "metabase/core/utils/types";
+import { getRelativeTime } from "metabase/lib/time";
+import type { WrappedResult } from "metabase/search/types";
+import { Text } from "metabase/ui";
+import { LastEditedInfoText, LastEditedInfoTooltip } from "./InfoText.styled";
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoTextEditedInfo.tsx:12]: We should move the styled components too:

```suggestion
import { LastEditedInfoText, LastEditedInfoTooltip } from "./InfoTextEditedInfo.styled";
```

File: frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx [hunk 9]
```diff
@@ -0,0 +1,141 @@
...
+  isEnabled: InfoTextAssetLinkProps["isEnabled"];
+}) => (
+  <SearchResultLink
+    key={database.name}
+    href={isEnabled ? browseDatabase(database) : undefined}
+  >
+    {database.name}
+  </SearchResultLink>
+);
+export const TableLink = ({ result, isEnabled }: InfoTextAssetLinkProps) => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx]:
```suggestion
);

export const TableLink = ({ result, isEnabled }: InfoTextAssetLinkProps) => {
```

File: frontend/src/metabase/search/components/InfoText/InfoTextEditedInfo.tsx [hunk 10]
```diff
@@ -0,0 +1,102 @@
...
+    data-testid={dataTestId}
+  >{t`Loading…`}</Text>
+);
+
+const InfoTextSeparator = (
+  <Text span size="sm" mx="xs" c="text.1">
+    •
+  </Text>
+);
+export const InfoTextEditedInfo = ({
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoTextEditedInfo.tsx:29]:
```suggestion
);

export const InfoTextEditedInfo = ({
```

File: frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx [hunk 11]
```diff
@@ -0,0 +1,141 @@
...
+}: InfoTextAssetLinkProps) => {
+  const { data: table, isLoading } = useTableQuery({
+    id: result.table_id,
+  });
+
+  const link = tableRowsQuery(result.database_id, result.table_id);
+  const label = table?.display_name ?? null;
+
+  if (isLoading) {
+    return <LoadingText data-testid="info-text-asset-link-loading-text" />;
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx:50]: We don't need the `data-testId` prop now, we can just inline it in `LoadingText` definition.

File: frontend/src/metabase/search/components/InfoText/InfoTextEditedInfo.tsx [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+      },
+    },
+    prefix,
+  };
+
+  if (isLoading) {
+    return (
+      <>
+        {InfoTextSeparator}
+        <LoadingText data-testid="last-edited-info-loading-text" />
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoTextEditedInfo.tsx:73]: We don't need the `data-testId` prop now, we can just inline it in `LoadingText` definition.

File: frontend/src/metabase/search/components/InfoText/InfoText.tsx (hunk 3 above)
Comment (oisincoveney) [reply frontend/src/metabase/search/components/InfoText/InfoText.tsx:10]: sure, why not

File: frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx [hunk 13]
```diff
@@ -0,0 +1,141 @@
...
+
+export const DatabaseLink = ({
+  database,
+  isEnabled,
+}: {
+  database: Database;
+  isEnabled: InfoTextAssetLinkProps["isEnabled"];
+}) => (
+  <SearchResultLink
+    key={database.name}
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx:68]: Redundant `key` prop

File: frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx [hunk 14]
```diff
@@ -0,0 +1,141 @@
...
+
+  const link = tableRowsQuery(result.database_id, result.table_id);
+  const label = table?.display_name ?? null;
+
+  if (isLoading) {
+    return <LoadingText data-testid="info-text-asset-link-loading-text" />;
+  }
+
+  return (
+    <SearchResultLink key={label} href={isEnabled ? link : undefined}>
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx]: Redundant `key` prop

File: frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx [hunk 15]
```diff
@@ -0,0 +1,141 @@
...
+
+  if (result.model === "segment" || result.model === "metric") {
+    return <InfoTextTableLink isEnabled={isEnabled} result={result} />;
+  }
+
+  const { label, link, icon }: InfoTextData = getInfoText(result);
+
+  return label ? (
+    <SearchResultLink
+      key={label}
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx:134]: Redundant `key` prop

File: frontend/src/metabase/search/components/InfoText/InfoText.tsx (hunk 3 above)
Comment (oisincoveney) [reply frontend/src/metabase/search/components/InfoText/InfoText.tsx]: ok changed @kamilmielnik

File: frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx [hunk 16]
```diff
@@ -0,0 +1,141 @@
...
+  return (
+    <SearchResultLink href={showLinks ? link : undefined}>
+      {result.table_schema}
+    </SearchResultLink>
+  );
+};
+
+export const InfoTextTablePath = ({
+  result,
+  showLinks = true,
```
Comment (kamilmielnik) [inline frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx:89]: Is there a reason why some components have default value for `isEnabled` and some don't?

**Review by kamilmielnik — APPROVED** [review]
Looks good :+1: 
Left some formatting/consistency comments.

File: e2e/test/scenarios/dashboard/reproductions/35037-recently-viewed-link-editing-dashboard-link-card.cy.spec.js [hunk 17]
```diff
@@ -0,0 +1,68 @@
...
+  beforeEach(() => {
+    restore();
+    cy.signInAsAdmin();
+    cy.intercept("GET", "/api/search?q=*").as("search");
+    cy.intercept("GET", "/api/activity/recent_views").as("recentViews");
+  });
+
+  it("should not redirect users to recent item", () => {
+    visitDashboard(ORDERS_DASHBOARD_ID);
+    const initialUrl = cy.url();
```
Comment (ranquild) [inline e2e/test/scenarios/dashboard/reproductions/35037-recently-viewed-link-editing-dashboard-link-card.cy.spec.js:22]: This is undocumented, it's better to use `cy.wrap(cy.url()).as("originUrl")` and then `cy.get("originalUrl").should...`

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx (hunk 16 above)
Comment (oisincoveney) [reply frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx:89]: Solved, only `InfoTextAssetLink` should have a default

**Comment by oisincoveney** [comment]
### Merge activity

* **Oct 27, 7:06 AM**: @oisincoveney merged this pull request with [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/35042).
