### PR TITLE
Remove "Debug SQL errors" link for non-sql databases

### LINKED ISSUE #28917: Remove "Debug SQL error" link from the native query editor for non-SQL queries (e.g. Mongo)
**Describe the bug**
The contextual help link ("Learn how to debug SQL errors") should not show up if someone is running a non-SQL native query.

**Logs**
n/a

**To Reproduce**
Run a broken Mongo query against a working MongoDB.

**Expected behavior**
No contextual help for Mongo users ):

image

**Additional context**
Could apply to non-SQL databases other than Mongo (unsure if there are others that we support).

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/28917

How to verify:
- `yarn test-qa-dbs:up`
- Add MongoDB in Admin -> Databases
- Try to run an invalid native query

Screenshot 2023-06-29 at 13 34 19

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/VisualizationError.jsx [hunk 1]
```diff
@@ -90,13 +91,12 @@ class VisualizationError extends Component {
     via: PropTypes.object.isRequired,
     question: PropTypes.object.isRequired,
     duration: PropTypes.number.isRequired,
-    error: PropTypes.object.isRequired,
+    error: PropTypes.any.isRequired,
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/VisualizationError.jsx:94]: It's expected as both an object and a string

File: frontend/src/metabase/query_builder/components/VisualizationError.unit.spec.tsx [hunk 2]
```diff
@@ -44,6 +116,12 @@ describe("VisualizationError", () => {
       errorLineNumbers,
     );
   });
+});
+describe("stripRemarks", () => {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/VisualizationError.unit.spec.tsx:120]: Moved tests to a separate block

File: frontend/src/metabase/query_builder/components/VisualizationError.jsx (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/query_builder/components/VisualizationError.jsx:94]: nit

```
PropTypes.oneOfType([
  PropTypes.object,
  PropTypes.string
]),
```

**Review by uladzimirdev — APPROVED** [review]
