### PR TITLE
Force user to type database name to delete the database

### LINKED ISSUE #12883: Delete database popup don't have the database name
**Describe the bug**
The "Delete database" popup have no clue about which database the action will be executed.

**To Reproduce**
1. Go to admin Databases
2. Click on Delete

image

3. Close the popup and repeat the process to be sure you selected the correct database and click delete again...

**Expected behavior**
I want to know which database I selected. "Delete database **MY_AMAZING_DB**?"

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Metabase version: 0.35.4

**Severity**
It is annoying and easy to fix. Just a small text change would be amazing to user experience here.

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #12883

**Description**
I liked the suggestions from @nemanjaglumac and @xPaw so I've taken the liberty to combine their ideas into the simplest change that avoids the need for a localization update. I've added the database name to the modal title and am also forcing the user to type the database name to delete the database. Happy to go in a different direction if preferred.

What do you think, @kdoh & @mazameli?

**Verification**
The updated Cypress test covers the logic change -- the "Delete" button is disabled until you type in the full database name. Here's what it looks like:
Screen Shot 2021-02-01 at 4 18 14 PM

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
Awesome!
That issue was buried for so long, it's a pity. I wanted to tackle it this week, but you took it a step further which is awesome! 💪

I'll try this locally tomorrow, but just a quick question before that: Will this be case-dependent? Asking because before you could've typed both "delete" and "DELETE" and it worked, but it was kind of ambiguous.

File: frontend/src/metabase/admin/databases/components/DeleteDatabaseModal.jsx [hunk 1]
```diff
@@ -46,14 +47,11 @@ export default class DeleteDatabaseModal extends Component {
...
-    // allow English or localized
-    const confirmed =
-      confirmValue.toUpperCase() === "DELETE" ||
-      confirmValue.toUpperCase() === t`DELETE`;
+    const confirmed = confirmValue === database.name;
 
     return (
       <ModalContent
-        title={t`Delete this database?`}
+        title={`${database.name}: ${t`Delete this database?`}`}
```
Comment (mazameli) [inline frontend/src/metabase/admin/databases/components/DeleteDatabaseModal.jsx:54]: This doesn't read naturally, and I'd prefer we construct this so it reads:

`Delete the {database.name} database?`

I get that this would require a string change, but that's okay if this is going in to 0.39. If we really want to avoid any string changes (i.e., we want it to go into 0.38 or 0.38.1), then I'd prefer leaving out this change entirely.

**Review by mazameli — CHANGES_REQUESTED** [review]
Overall I quite like this change; I just don't think the new heading for the modal reads naturally.

File: frontend/src/metabase/admin/databases/components/DeleteDatabaseModal.jsx (hunk 1 above)
Comment (daltojohnso) [reply frontend/src/metabase/admin/databases/components/DeleteDatabaseModal.jsx]: Alright, updated it.

**Review by mazameli — APPROVED** [review]

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac - I went ahead and made it slightly more forgiving by trimming any whitespace and comparing strings that have been made lowercase.

Great thinking. 🎉
