### PR TITLE
29553 add actions button is shown even when actions are not enabled for the database

### LINKED ISSUE #29553: "Add actions" button is shown even when actions are not enabled for the database
**Describe the bug**
Add actions button is shown even when actions are not enabled for the database.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Make sure the sample database model actions are disabled
2. Create a new dashboard or open an existing one and go to the edit mode
3. Notice the "Add actions" button

**Expected behavior**
Do not show "Add actions" button unless a database has model actions enabled

**Information about your Metabase Installation:**
local dev, `master`, 9f22669f39623ab5a2173d50c0090dd9ffac1749, H2, Sample Database

**Severity**
P3

### PR DESCRIPTION
**Pull request by oisincoveney**
Closes https://github.com/metabase/metabase/issues/29553

### Description

We want to remove the `Add Actions` button from dashboards whose data sources are databases that don't allow model actions. This change will only apply to dashboards where _all_ cards use data from those databases. Otherwise, things will remain as they are now.

### How to verify

1. Go to Metabase Admin, and ensure that the "Enable Model Actions" toggle is disabled within the Sample Database
2. Go to an existing dashboard whose cards only use Sample data and see that the "Add actions" button isn't there.
3. Go to an existing dashboard whose cards have different sources (where cards source data from at least one database with model actions) and see that the "Add actions" button is still there.
4. You can also go back to Metabase Admin, re-enable the model actions in the sample database, and go back to the dashboard from step (2) and see that the "Add actions" button is back.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29863)

### CODE REVIEW

File: frontend/src/metabase/dashboard/containers/DashboardHeader.jsx [hunk 1]
```diff
@@ -209,10 +210,18 @@ class DashboardHeader extends Component {
...
       isShowingDashboardInfoSidebar,
       closeSidebar,
+      databases,
     } = this.props;
 
     const canEdit = dashboard.can_write && isEditable && !!dashboard;
 
+    // check the dashboard card's source database,
+    // and check if the database has actions enabled
+    const hasModelActionsEnabled = dashboard.ordered_cards.every(cardData => {
```
Comment (ranquild) [inline frontend/src/metabase/dashboard/containers/DashboardHeader.jsx:220]: Adding new actions shouldn't be tight to existing cards on the dashboard. It should be enough to check where there is a database with actions among all databases.

File: frontend/src/metabase/dashboard/containers/DashboardHeader.jsx [hunk 2]
```diff
@@ -101,6 +100,8 @@ class DashboardHeader extends Component {
     setSidebar: PropTypes.func.isRequired,
     closeSidebar: PropTypes.func.isRequired,
     addActionToDashboard: PropTypes.func.isRequired,
+
+    databases: PropTypes.object,
```
Comment (ranquild) [inline frontend/src/metabase/dashboard/containers/DashboardHeader.jsx:104]: PropTypes.array?

File: frontend/src/metabase/dashboard/containers/DashboardHeader.jsx (hunk 1 above)
Comment (oisincoveney) [reply frontend/src/metabase/dashboard/containers/DashboardHeader.jsx]: Ah ok. From what I understood, the cards (and their source databases) would dictate whether or not there would be an actions button. So instead we will just have the actions button solely based on the database properties?

File: frontend/src/metabase/dashboard/containers/DashboardHeader.jsx (hunk 2 above)
Comment (oisincoveney) [reply frontend/src/metabase/dashboard/containers/DashboardHeader.jsx:105]: That's what I thought as well, but when I log the databases props, it's an object with the ID as the key, and the DB data as the value

File: frontend/src/metabase/dashboard/containers/DashboardHeader.jsx [hunk 3]
```diff
@@ -209,10 +211,15 @@ class DashboardHeader extends Component {
...
       isShowingDashboardInfoSidebar,
       closeSidebar,
+      databases,
     } = this.props;
 
     const canEdit = dashboard.can_write && isEditable && !!dashboard;
 
+    const hasModelActionsEnabled = isDatabaseActionsEnabled(
+      Object.values(databases),
+    );
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/containers/DashboardHeader.jsx:221]: I think we should rather have a utility checking the actions setting for _one_ database, and then do something like that:

```js
const hasModelActionsEnabled = Object.values(databases).some(isDatabaseActionsEnabled)
```

Otherwise we won't be able to use it when we have a single database

File: frontend/src/metabase/dashboard/utils.unit.spec.js [hunk 4]
```diff
@@ -13,6 +15,9 @@ describe("Dashboard utils", () => {
       const successfulFetch = Promise.resolve(data);
 
       const result = await fetchDataOrError(successfulFetch);
+
+      console.log(result);
+
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/utils.unit.spec.js:20]: Could you remove the log, please?

File: frontend/src/metabase/dashboard/utils.unit.spec.js [hunk 5]
```diff
@@ -32,6 +37,19 @@ describe("Dashboard utils", () => {
...
+        { id: 1, settings: { "database-enable-actions": true } },
+        { id: 2, settings: { "database-enable-actions": true } },
+        { id: 3, settings: { "database-enable-actions": false } },
+      ];
+
+      const databases = dbData.map(createMockDatabase);
+
+      const result = isDatabaseActionsEnabled(databases);
+      expect(result).toBe(true);
+    });
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/utils.unit.spec.js:52]: Let's add a test for a negative scenario too

**Review by kulyk — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/dashboard/utils.unit.spec.js (hunk 4 above)
Comment (oisincoveney) [reply frontend/src/metabase/dashboard/utils.unit.spec.js:20]: Ah missed that, thanks

File: frontend/src/metabase/dashboard/utils.unit.spec.js (hunk 5 above)
Comment (oisincoveney) [reply frontend/src/metabase/dashboard/utils.unit.spec.js]: Nice, added a database to each test as well where the settings key is also undefined, since we can run into that as well (if the database has nothing set for the `settings` key)

File: frontend/src/metabase/dashboard/utils.unit.spec.js [hunk 6]
```diff
@@ -32,6 +35,31 @@ describe("Dashboard utils", () => {
...
+      const dbData = [
+        { id: 1, settings: { "database-enable-actions": false } },
+        { id: 2 },
+        { id: 3, settings: { "database-enable-actions": false } },
+      ];
+
+      const databases = dbData.map(createMockDatabase);
+      const result = databases.some(isDatabaseActionEnabled);
+      expect(result).toBe(false);
+    });
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/utils.unit.spec.js:62]: nit: I think this is the first time we're doing a `.map(createMock)` trick in the codebase. Looks good to me, but maybe we should keep things consistent. Not sure, but I suppose it'd require changes when we migrate this file to TypeScript

File: frontend/src/metabase/dashboard/containers/DashboardHeader.jsx [hunk 7]
```diff
@@ -297,11 +304,11 @@ class DashboardHeader extends Component {
         </span>,
       );
 
-      if (canEdit) {
+      if (canEdit && hasModelActionsEnabled) {
         buttons.push(
           <>
             <DashboardHeaderActionDivider />
-            <Tooltip key="add-action-button" tooltip={t`Add action button`}>
+            <Tooltip key="add-action-button" tooltip={t`Add`}>
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/containers/DashboardHeader.jsx:311]: Why are we updating a tooltip here?

**Review by kulyk — COMMENTED** [review]
Looks good to me overall! Have a question about a tooltip + a very minor comment on tests

File: frontend/src/metabase/dashboard/containers/DashboardHeader.jsx (hunk 7 above)
Comment (oisincoveney) [reply frontend/src/metabase/dashboard/containers/DashboardHeader.jsx:311]: <insert expletive here> that's not great on my part, I updated that to make sure I was working on the right part of the code. Thanks for the catch

File: frontend/src/metabase/dashboard/utils.unit.spec.js (hunk 6 above)
Comment (oisincoveney) [reply frontend/src/metabase/dashboard/utils.unit.spec.js:62]: Yep, I agree that we should keep it consistent - what do you propose that we do here? From what I'm reading on other parts of the codebase, I'm thinking something where we hoist the database constants in some sort of variable i.e. 
```
ENABLED_ACTIONS_DATABASE = createMockDatabase({ id: 1, settings: { "database-enable-actions": true } }) 
DISABLED_ACTIONS_DATABASE = createMockDatabase({ id: 1, settings: { "database-enable-actions": false } }) 
```
and so on, then populate the tests with these vars so it matches the style of what I've seen, and remove the map (can't find the article but I did read that we really shouldn't use `map` without an explicit function i.e. `map(x => <whatever func>(x))` instead of `map(<whatever func>)` since there's additional params that we don't explicitly throw away and could cause issues in the future

File: frontend/src/metabase/dashboard/utils.js [hunk 8]
```diff
@@ -103,6 +103,10 @@ export function getAllDashboardCards(dashboard) {
   return results;
 }
 
+export function isDatabaseActionEnabled(database) {
+  return database.settings?.["database-enable-actions"] ?? false;
+}
+
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/utils.js:109]: nit: "is database action enabled" makes me think we're talking about some single action affecting the database somehow. I'm not sure, but maybe something like `hasDatabaseActionsEnabled` would make it a bit more clear? Please feel free to ignore that proposal though

**Review by kulyk — APPROVED** [review]
Unblocking since only cosmetic feedback is left. Thanks for addressing all the comments @oisincoveney 🙏

File: frontend/src/metabase/dashboard/utils.js (hunk 8 above)
Comment (oisincoveney) [reply frontend/src/metabase/dashboard/utils.js:109]: yep I agree with that as well - I keep thinking of database syncs now that you've mentioned it

File: frontend/src/metabase/dashboard/utils.unit.spec.js (hunk 6 above)
Comment (oisincoveney) [reply frontend/src/metabase/dashboard/utils.unit.spec.js:62]: Ok that makes sense - I think I'll pull out the mocks so I can share them across the two tests. I'll use the same logic of testing multiple databases (i.e. `Array.some`) to replicate what we're doing on the frontend

**Review by kulyk — CHANGES_REQUESTED** [review]

**Review by kulyk — APPROVED** [review]
Nevermind, I didn't notice you're testing against both `DISABLED_ACTIONS_DATABASE` and `NO_ACTIONS_DATABASE` in the second test 🤦 Great job!

File: frontend/src/metabase/dashboard/utils.unit.spec.js [hunk 9]
```diff
@@ -32,6 +45,24 @@ describe("Dashboard utils", () => {
...
+      const result = databases.some(hasDatabaseActionsEnabled);
+      expect(result).toBe(true);
+    });
+
+    it("should return false if all databases have actions disabled", () => {
+      const databases = [DISABLED_ACTIONS_DATABASE, NO_ACTIONS_DATABASE];
+
+      const result = databases.some(hasDatabaseActionsEnabled);
+      expect(result).toBe(false);
+    });
```
[the remark this answers is not in the document]
Comment (oisincoveney) [reply frontend/src/metabase/dashboard/utils.unit.spec.js:65]: despite the approval I do get what you mean - I'll add another test that tests each one individually. At least then, if a bug comes up with the function, we can at least get a more explicit view of what might be going wrong

**Comment by mazameli** [comment]
@oisincoveney seems to work as advertised, though one funny thing I noticed is that disabled buttons get a bolt icon next to their text which goes away once they're active again. Is this intentional? (See the bottom disabled button as compared to the top one.)

image

**Comment by oisincoveney** [comment]
> @oisincoveney seems to work as advertised, though one funny thing I noticed is that disabled buttons get a bolt icon next to their text which goes away once they're active again. Is this intentional? (See the bottom disabled button as compared to the top one.)
> 
> image

Ah yeah I found the issue, super weird. It seems like disabled buttons had a `bolt` icon hard-coded in, while (as you show there) active action buttons don't have an icon associated with them. Should I put this in a new PR?

**Comment by chalenge** [comment]
@oisincoveney can we backport this to v46 too?
