### PR TITLE
Format compact currency and scientific style values

### LINKED ISSUE #10055: Currency formatting is broken on compact cards
Similar to the percent issue described in #9932, we should support compact formatting for currencies.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #10055 

When a dashboard card was small enough to trigger compact formatting, values displayed as currency or in scientific notation lost their styling. 

Currency values use Intl.NumberFormat to get the currency symbol and adds it to the compact formatted number.

Numbers in scientific notation are delegated to `formatNumberScientific` but fix the number of decimals at 1.

### CODE REVIEW

File: frontend/src/metabase/lib/formatting.js [hunk 1]
```diff
@@ -252,6 +252,30 @@ function formatNumberCompact(value: number, options: FormattingOptions) {
   if (options.number_style === "percent") {
     return formatNumberCompactWithoutOptions(value * 100) + "%";
   }
+  if (options.number_style === "currency") {
+    try {
+      const { value: currency } = numberFormatterForOptions(options)
+        .formatToParts(value)
+        .find(p => p.type === "currency");
+
+      // this special case ensures the "~" comes before the currency
```
Comment (tlrobinson) [inline frontend/src/metabase/lib/formatting.js]: It's actually not safe to assume currency comes before the number. If you set the `currency_style` to `name` it will format like `100 US Dollars` (maybe also depending on the locale)

I'm not sure but it might be safe to assume the currency part comes first or last, which would also avoid iterating over all the parts, though you'll also want to check for a `literal` whitespace character https://runkit.com/tlrobinson/5cef1a906e2c4b001c2a55b8

**Review by tlrobinson — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/lib/formatting.js (hunk 1 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/lib/formatting.js]: Good catch! I had totally ignored this UI:
image

What do you think about always using `currencyDisplay: "symbol"` for compact formatting? It would be more compact I guess 🤷‍♂  I _think_ symbols will always come before the number, but I can do more testing.

As you point out, locale is another place where this breaks. I think that's ok because we currently have `"en"` hardcoded. Do you think we'll change that?

Comment (tlrobinson) [reply frontend/src/metabase/lib/formatting.js]: Yeah, I think that seems reasonable.

Comment (paulrosenzweig) [reply frontend/src/metabase/lib/formatting.js]: OK sweet. It looks safe with the list of currencies in our app. 

image

I'm actually kinda surprised that nothing was like ¢ where it comes after the number.

**Review by tlrobinson — APPROVED** [review]
