### PR TITLE
Properly apply transparent background for Public Embedding

### LINKED ISSUE #62391: Public dashboard embedding does not respect `background=false` setting
### Describe the bug

Public dashboard embedding does not respect `background=false` setting.

Public at the top, static at the bottom:

Image

### To Reproduce

Reproduced locally

### Expected behavior

Background should be transparent when set to `false`

### Logs

_No response_

### Information about your Metabase installation

```JSON
-
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
closes #62391
Closes https://linear.app/metabase/issue/GIT-7880/public-dashboard-embedding-does-not-respect-background=false-setting

How to verify:
- CI should check it now
- Manually via Public Embedding, set `#dashboard=false` to the iframe url

Before (public at top, static at bottom):
image

After (public at top, static at bottom):
image

### CODE REVIEW

File: frontend/src/metabase/app-embed.js [hunk 1]
```diff
@@ -3,14 +3,8 @@
...
-
 import { init } from "./app";
 import { publicReducers } from "./reducers-public";
 import { getRoutes } from "./routes-embed";
 
-init(publicReducers, getRoutes, () => {
-  if (isWithinIframe()) {
-    document.body.style.backgroundColor = "transparent";
-  }
-});
```
Comment (sanex3339) [inline frontend/src/metabase/app-embed.js:16]: Moved this logic to PublicApp.tsx

File: frontend/src/metabase/public/containers/PublicApp/PublicApp.tsx [hunk 2]
```diff
@@ -22,9 +25,16 @@ function mapStateToProps(state: State) {
 }
 
 function PublicApp({ errorPage, children }: Props) {
+  useLayoutEffect(() => {
+    if (isWithinIframe()) {
+      document.body.style.backgroundColor = "transparent";
+    }
+  }, []);
+
```
Comment (sanex3339) [inline frontend/src/metabase/public/containers/PublicApp/PublicApp.tsx:33]: use `useLayoutEffect` to apply bg color before paint, so to avoid flickering

File: frontend/src/metabase/lib/dom.js [hunk 3]
```diff
@@ -15,15 +15,15 @@ export const getScrollY = () =>
...
-    // Mock that we're embedding, so we could visual test embed components
+    // Mock that we're embedding, so we could test embed components
     if (window.overrideIsWithinIframe) {
       return true;
     }
 
+    if (isCypressActive || isStorybookActive) {
+      return false;
+    }
+
```
Comment (sanex3339) [inline frontend/src/metabase/lib/dom.js:26]: We check the `override` first to be able mocking it in Cypress tests

File: frontend/src/metabase/public/containers/PublicApp/PublicApp.tsx [hunk 4]
```diff
@@ -22,9 +25,16 @@ function mapStateToProps(state: State) {
 }
 
 function PublicApp({ errorPage, children }: Props) {
+  useLayoutEffect(() => {
```
[the remark this answers is not in the document]
Comment (sanex3339) [reply frontend/src/metabase/public/containers/PublicApp/PublicApp.tsx:28]: We don't need it, we didn't have it before

**Review by npretto — APPROVED** [review]
