### PR TITLE
Fix funnel viz to handle increasing data

### LINKED ISSUE #67932: Funnel viz - shape is cropped when first step value is lower than some later steps
### Describe the bug

When visualizing a funnel where step values are not strictly monotone decreasing the funnel chart may render incorrectly.
The funnel shape appears clipped instead of scaling to accommodate the maximum step width, when Step 1 value is lower than some of the later steps. 

This results in a misleading/incorrect funnel representation.

### To Reproduce

1. Create the following native question and visualize it as a funnel
```
select 75 val, 'Step1' step
union all
select 100, 'Step2'
union all
select 50, 'Step3'
union all
select 25, 'Step4'
```

Image

### Expected behavior

The viz should render all steps fully within bounds, even if the “funnel” is not a strict funnel.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "athena",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2026-01-06",
      "tag": "v1.57.8",
      "hash": "8208922"
    },
    "settings": {
      "report-timezone": "Australia/Melbourne"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Potentially affects an enterprise customer

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevinkelleher12**
Closes #67932

### Description

Previously funnel heights were based on the first data point, which results in a misleading viz when the data is increasing and a later point is larger than the first data point.

The tricky part was solving this for both the viz and static-viz, since the code isn't aligned. I refactored the viz code to also use `calculateFunnelSteps` to align the logic on how funnel height is calculated.

Note that if you follow the steps in #67932 to reproduce exactly, testing the static-viz via email won't work due to #28568. Reverse the order of the `step` and `val` columns to be able to successfully send emails.

### How to verify

See below screenshot or #67932 for details

### Demo

Before:
image

After:
image

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/FunnelNormal.tsx
Comment (iethree) [inline frontend/src/metabase/visualizations/components/FunnelNormal.tsx:1]: 😍

File: frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ import { BarChart } from "metabase/visualizations/visualizations/BarChart";
 import { funnelToBarTransform } from "metabase/visualizations/visualizations/Funnel/funnel-bar-transform";
 import type { DatasetData, RawSeries, RowValue } from "metabase-types/api";
 
-import FunnelNormal from "../../components/FunnelNormal";
+import { FunnelNormal } from "../../components/FunnelNormal";
```
Comment (iethree) [inline frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.tsx:34]: 😍

File: frontend/src/metabase/visualizations/components/FunnelNormal.tsx [hunk 2]
```diff
@@ -0,0 +1,300 @@
...
+  HoveredObject,
+  VisualizationProps,
+} from "metabase/visualizations/types";
+
+import { computeChange } from "../lib/numeric";
+
+type FunnelStepInfo = {
+  value: number;
+  percent: number;
+  dimension: unknown;
```
Comment (iethree) [inline frontend/src/metabase/visualizations/components/FunnelNormal.tsx]: can we find a better type for dimension, maybe `DimensionReference` ?

File: frontend/src/metabase/visualizations/components/FunnelNormal.tsx [hunk 3]
```diff
@@ -0,0 +1,300 @@
...
+          rows.find((row) => formatNullable(row[dimensionIndex]) === fr.key),
+        )
+        .filter(isNotNull)
+    : rows;
+
+  const isNarrow = Boolean(gridSize && gridSize.width < 7);
+  const isShort = Boolean(gridSize && gridSize.height <= 5);
+  const isSmall = isShort || isNarrow;
+
+  const formatDimension = (dimension: unknown, jsx = true) =>
```
Comment (iethree) [inline frontend/src/metabase/visualizations/components/FunnelNormal.tsx]: again, let's avoid unknown if possible

**Review by iethree — APPROVED** [review]
Looks great!

😬  | 🤩
---|---
 Image | Image

Also very nice job doing the FC + TS conversion. let's just see if we can tighten up that Dimension type a bit.
