### PR TITLE
Nested queries have limits which can defeat their purpose

### LINKED ISSUE #24969: Incorrect results from SQL query referencing saved question with more than 1,048,575 rows
**Describe the bug**

Using a saved question as the source of a native SQL question applies the `absolute-max-row` limit on a referenced saved question. This causes incorrect results if the number of rows in the results of the saved question exceeds the `absolute-max-row` limit of 1,048,575 rows.

**To Reproduce**

To reproduce this bug on stats.metabase.com:

1. Open the query builder, using the Snowplow database, select the "Page Views" model for Data, and "Count rows of..." for summarization. Observe the result is over 1,048,575.
2. Open a native SQL query editor, using the Snowplow database. Run this query: `select count(*) from {{#3367}}`. The result will be 1,048,575, even though we should get the same result as step 1.

Related to https://github.com/metabase/metabase/issues/24793

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes https://github.com/metabase/metabase/issues/24969

Consider a query

```sql
select count(*) from {{#199}}
```

This query should return the number of distinct rows in the query defined by 199. But it's actually limited by the excel limit of 1048575 (meta note, ignore that this is a link. Github is being weird). And that's because when the value of `{{#199}}` is expanded it has that limit applied as normal.

```clojure
qp=> (let [card-id 199] ;; use a valid card id for you
       (-> {:database 1,
            :type :native,
            :native {:query "select count(*) from {{ref}}"
                     :template-tags {:ref {:card-id card-id
                                           :type :card
                                           :name "ref"
                                           :display-name "ref"}}}
            :middleware {:disable-max-results? true}} ;; note this middleware is not propagated to the subquery
           qp.compile/compile
           :query
           (metabase.db.query/format-sql )
           println))
select
  count(*)
from
  (
    SELECT
      "PUBLIC"."ORDERS"."ID" AS "ID",
      "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL"
    FROM
      "PUBLIC"."ORDERS"
    LIMIT
      1048575         -- this is improper here
  )
```

I thought about trying to propagate that limit middleware, but i think it should not be the solution.
- that limit is actually not honored for the containing sql query
- we don't want to indiscriminately start adding that
- we might still want a limit on the _total_ query, but the inner query should be unbounded

When the parameter substitution code gets to the `{{#199}}` parameter tag, it compiles the query for card 199, which naturally includes the default excel limit. But we can suppress this limit specifically as a card parameter value when substituting a query inside yielding

```sql
select
  count(*)
from
  (
    SELECT
      "PUBLIC"."ORDERS"."ID" AS "ID",
      "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL"
    FROM
      "PUBLIC"."ORDERS"
  )
```

### CODE REVIEW

File: src/metabase/driver/common/parameters/values.clj [hunk 1]
```diff
@@ -201,7 +201,7 @@
                       {:query (qp.persistence/persisted-info-native-query
                                (u/the-id (lib.metadata/database (qp.store/metadata-provider)))
                                persisted-info)})
-                    (qp.compile/compile query)))))
+                    (qp.compile/compile (assoc-in query [:middleware :disable-max-results?] true))))))
```
Comment (metamben) [inline src/metabase/driver/common/parameters/values.clj:204]: I suggest using `(limit/disable-max-results query)`.

**Review by metamben — APPROVED** [review]
LGTM

File: src/metabase/driver/common/parameters/values.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/driver/common/parameters/values.clj]: ah good note. Thanks!
