### PR TITLE
Fix - Custom Expression error can sometimes be slightly misleading

### LINKED ISSUE #15892: Custom Expression error can sometimes be slightly misleading
**Describe the bug**
Custom Expression error can sometimes be slightly misleading, when forgetting some commas.

**To Reproduce**
1. Custom question > Sample Dataset > Products
2. Custom Column > type `concat([Category] "test")` and blur input, errors with `Expected closing parenthesis but found  '"test"'`
image

Current message: Invalid expression
Expected message: Missing comma after [Category]

Part of https://github.com/metabase/metabase/issues/15894

**Information about your Metabase Installation:**
Tested 0.39.1 and master

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #15892

### Description

This PR exposes `compileError` to be utilized by `ExpressionEditorTextfield` in order to show detailed errors coming from the parser instead of generic "Invalid expression" error.

It also changes "Expecting closing parenthesis" error to "Expecting comma" when 2 tokens in parens are not separated by a comma.

### How to verify

Follow repro steps from the issue.
Note that issue was reported in v39 - the actual result was different back then.

### Demo

[before](https://github.com/user-attachments/assets/c301da03-ddf9-437e-9056-091f7c9b0b3f) vs [after](https://github.com/user-attachments/assets/09ea1e1a-0f18-4e6e-a6b5-b8d9d2d1b8e7)

### CODE REVIEW

File: frontend/src/metabase-lib/v1/expressions/recursive-parser.js [hunk 1]
```diff
@@ -58,17 +58,17 @@ function recursiveParse(source) {
...
   // Parameters ::= "(" * Expression ")"
   const parseParameters = () => {
-    expectOp(OP.OpenParenthesis);
+    expectOp(OP.OpenParenthesis, t`opening parenthesis`);
     const params = [];
     while (!matchOps([OP.Comma, OP.CloseParenthesis])) {
       const expr = parseExpression();
       params.push(expr);
-      if (!matchOps([OP.Comma])) {
+      if (!matchOps([OP.Comma]) && matchOps([OP.CloseParenthesis])) {
```
Comment (kamilmielnik) [inline frontend/src/metabase-lib/v1/expressions/recursive-parser.js:66]: Without this condition parser would throw "Expecting closing parenthesis" error which is why the issue was reported.

**Review by ranquild — APPROVED** [review]
