### PR TITLE
Fixing null error when value is null and isCustom is true

### LINKED ISSUE #24053: "Custom..." model refresh setting does not work on first request
**Describe the bug**
The "custom" model refresh option does not work, it just refreshes the page if you try to move the sync on the first try from 6 hours to custom as soon as you set up the instance

**Logs**
NA

**To Reproduce**
1) set up a new Metabase instance
2) go to settings->admin->caching->enable model caching-> change to "Custom"
3) see how the page gets refreshed without doing nothing

But, if you change to, e.g. hour, and then to "Custom..." it works

**Expected behavior**
Make it work on the first shot :)

**Screenshots**
custom_caching

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.44.0-RC1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
Cosmetic

**Additional context**
NA

### PR DESCRIPTION
**Pull request by npfitz**
Fixes #24053 

Error was caused by isCustom being true but setting.value being null and getting passed to `formatCronExpression()`. Also called onChange with the value to prevent users from needing to click and blur the input to save the default value.

chrome_xsMin4i1C0

### CODE REVIEW

File: frontend/src/metabase/admin/settings/components/widgets/ModelCachingScheduleWidget/ModelCachingScheduleWidget.jsx [hunk 1]
```diff
@@ -41,14 +41,15 @@ const PersistedModelRefreshIntervalWidget = ({
   const [customCronSchedule, setCustomCronSchedule] = useState(
     // We don't allow to specify the "year" component, but it's present in the value
     // So we need to cut it visually to avoid confusion
-    isCustom ? formatCronExpression(setting.value) : "",
+    isCustom ? formatCronExpression(setting.value || setting.default) : "",
```
Comment (ranquild) [inline frontend/src/metabase/admin/settings/components/widgets/ModelCachingScheduleWidget/ModelCachingScheduleWidget.jsx:44]: Maybe `setting.value ?? setting.default`? Or it will always use `default` when the value is `false` (which might be ok here but not sure if it was intended)

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/admin/settings/components/widgets/ModelCachingScheduleWidget/ModelCachingScheduleWidget.jsx (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/admin/settings/components/widgets/ModelCachingScheduleWidget/ModelCachingScheduleWidget.jsx]: I'm pretty sure in this case, `setting.value` should only be a string or null, but it doesn't hurt to be more specific! Changed.
