### PR TITLE
Gracefully handle null arrays in results

### LINKED ISSUE #54190: PostgreSQL integer array column breaks showing query in v0.53.3.4
### Describe the bug

After upgrading Metabase from v0.53.3.3 to v0.53.3.4 (Docker), a query that included a array of integers as result column, started to give an error. Removing the column from the query made the result show again (but would break our use-case, so we downgraded instead).

### To Reproduce

1. Open Metabase v0.53.3.4 or v0.53.3.5 from the Docker image
2. Connect to a PostgreSQL database
3. Create a SQL query with an integer array result column and run it

### Expected behavior

show the query result

### Logs

Server logs indicated

```
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error reducing result rows: Cannot invoke \"java.sql.Array.getArray()\" because the return value of \"java.sql.ResultSet.getObject(int)\" is null",
   :stacktrace
   ["--> query_processor.pipeline$_STAR_reduce_STAR_$fn__65630.invoke(pipeline.clj:79)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:67)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:54)"
    "query_processor.middleware.cache$run_query_with_cache72233__72235$reduce_SINGLEQUOTE___72241$fn__72242.invoke(cache.clj:215)"
    "query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:83)"
    "query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54)"
    "query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:73)"
    "query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54)"
    "query_processor.middleware.cache$run_query_with_cache72233__72235$reduce_SINGLEQUOTE___72241.invoke(cache.clj:211)"
    "query_processor.pipeline$_STAR_run_STAR_$respond__65642.invoke(pipeline.clj:100)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__85698.invoke(execute.clj:729)"
    "driver.sql_jdbc.execute$fn__85500$fn__85501.invoke(execute.clj:398)"
    "driver.sql_jdbc.execute$do_with_resolved_connection85470__85471.invokeStatic(execute.clj:338)"
    "driver.sql_jdbc.execute$do_with_resolved_connection85470__85471.invoke(execute.clj:321)"
    "driver.sql_jdbc.execute$fn__85500.invokeStatic(execute.clj:392)"
    "driver.sql_jdbc.execute$fn__85500.invoke(execute.clj:390)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:712)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:698)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:709)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:698)"
    "driver.sql_jdbc$fn__117605.invokeStatic(sql_jdbc.clj:79)"
    "driver.sql_jdbc$fn__117605.invoke(sql_jdbc.clj:77)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:52)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:39)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:102)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:95)"
    "query_processor.execute$run.invokeStatic(execute.clj:62)"
    "query_processor.execute$run.invoke(execute.clj:56)"
    "query_processor.middleware.update_used_cards$update_used_cards_BANG_72284__72285$fn__72286.invoke(update_used_cards.clj:60)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__72389.invoke(execute.clj:25)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__72395.invoke(execute.clj:36)"
    "query_processor.middleware.cache$run_query_with_cache72233__72235.invokeStatic(cache.clj:216)"
    "query_processor.middleware.cache$run_query_with_cache72233__72235.invoke(cache.clj:189)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___72257.invoke(cache.clj:245)"
    "query_processor.middleware.permissions$check_query_permissions$fn__72028.invoke(permissions.clj:148)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__72122.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__72132.invoke(enterprise.clj:64)"
    "query_processor.execute$execute72422__72423$fn__72424.invoke(execute.clj:94)"
    "query_processor.setup$do_with_qp_setup72375__72376.invokeStatic(setup.clj:225)"
    "query_processor.setup$do_with_qp_setup72375__72376.invoke(setup.clj:216)"
    "query_processor.execute$execute72422__72423.invokeStatic(execute.clj:93)"
    "query_processor.execute$execute72422__72423.invoke(execute.clj:89)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
    "query_processor.middleware.enterprise$fn__72149$handle_audit_app_internal_queries__72150$fn__72152.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__72160.invoke(enterprise.clj:103)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware78995__78996$fn__78997.invoke(process_userland_query.clj:221)"
    "query_processor.middleware.catch_exceptions$catch_exceptions79060__79061$fn__79062.invoke(catch_exceptions.clj:132)"
    "query_processor$process_query79101__79102$fn__79103.invoke(query_processor.clj:80)"
    "query_processor.setup$do_with_canceled_chan72370__72371$fn__72372.invoke(setup.clj:187)"
    "query_processor.setup$do_with_database_local_settings72363__72364$fn__72365.invoke(setup.clj:181)"
    "query_processor.setup$do_with_driver72356__72357$fn__72358$fn__72359.invoke(setup.clj:166)"
    "driver$do_with_driver.invokeStatic(driver.clj:107)"
    "driver$do_with_driver.invoke(driver.clj:102)"
    "query_processor.setup$do_with_driver72356__72357$fn__72358.invoke(setup.clj:165)"
    "query_processor.setup$do_with_metadata_provider72347__72348$fn__72349$fn__72352.invoke(setup.clj:151)"
    "query_processor.store$do_with_metadata_provider58076__58077.invokeStatic(store.clj:170)"
    "query_processor.store$do_with_metadata_provider58076__58077.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider58076__58077.invokeStatic(store.clj:159)"
    "query_processor.store$do_with_metadata_provider58076__58077.invoke(store.clj:150)"
    "query_processor.setup$do_with_metadata_provider72347__72348$fn__72349.invoke(setup.clj:150)"
    "query_processor.setup$do_with_resolved_database72337__72338$fn__72339.invoke(setup.clj:128)"
    "query_processor.setup$do_with_qp_setup72375__72376.invokeStatic(setup.clj:232)"
    "query_processor.setup$do_with_qp_setup72375__72376.invoke(setup.clj:216)"
    "query_processor$process_query79101__79102.invokeStatic(query_processor.clj:78)"
    "query_processor$process_query79101__79102.invoke(query_processor.clj:71)"
    "query_processor.card$process_query_for_card_default_qp85905__85906.invokeStatic(card.clj:232)"
    "query_processor.card$process_query_for_card_default_qp85905__85906.invoke(card.clj:228)"
    "query_processor.card$process_query_for_card_default_run_fn$fn__85908$fn__85909.invoke(card.clj:239)"
    "query_processor.streaming$_streaming_response$fn__83568$fn__83569$fn__83570.invoke(streaming.clj:185)"
    "query_processor.streaming$_streaming_response$fn__83568$fn__83569.invoke(streaming.clj:183)"
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:174)"
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:161)"
    "query_processor.streaming$_streaming_response$fn__83568.invoke(streaming.clj:180)"
    "server.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
    "server.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
    "server.streaming_response$do_f_async$task__81558.invoke(streaming_response.clj:93)"],
   :error_type :qp,
   :ex-data {:type :qp}}],
```

note that when I upgraded to v0.53.3.5, I saw a different error:

```
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error reducing result rows: null",
   :stacktrace
   ["--> query_processor.pipeline$_STAR_reduce_STAR_$fn__65630.invoke(pipeline.clj:79)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:67)"
    "query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:54)"
    "query_processor.pipeline$_STAR_run_STAR_$respond__65642.invoke(pipeline.clj:100)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__85698.invoke(execute.clj:729)"
    "driver.sql_jdbc.execute$fn__85500$fn__85501.invoke(execute.clj:398)"
    "driver.sql_jdbc.execute$do_with_resolved_connection85470__85471.invokeStatic(execute.clj:338)"
    "driver.sql_jdbc.execute$do_with_resolved_connection85470__85471.invoke(execute.clj:321)"
    "driver.sql_jdbc.execute$fn__85500.invokeStatic(execute.clj:392)"
    "driver.sql_jdbc.execute$fn__85500.invoke(execute.clj:390)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:712)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:698)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:709)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:698)"
    "driver.sql_jdbc$fn__117605.invokeStatic(sql_jdbc.clj:79)"
    "driver.sql_jdbc$fn__117605.invoke(sql_jdbc.clj:77)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:52)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:39)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:102)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:95)"
    "query_processor.execute$run.invokeStatic(execute.clj:62)"
    "query_processor.execute$run.invoke(execute.clj:56)"
    "query_processor.middleware.update_used_cards$update_used_cards_BANG_72284__72285$fn__72286.invoke(update_used_cards.clj:60)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__72389.invoke(execute.clj:25)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__72395.invoke(execute.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___72257.invoke(cache.clj:246)"
    "query_processor.middleware.permissions$check_query_permissions$fn__72028.invoke(permissions.clj:148)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__72122.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__72132.invoke(enterprise.clj:64)"
    "query_processor.execute$execute72422__72423$fn__72424.invoke(execute.clj:94)"
    "query_processor.setup$do_with_qp_setup72375__72376.invokeStatic(setup.clj:225)"
    "query_processor.setup$do_with_qp_setup72375__72376.invoke(setup.clj:216)"
    "query_processor.execute$execute72422__72423.invokeStatic(execute.clj:93)"
    "query_processor.execute$execute72422__72423.invoke(execute.clj:89)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
    "query_processor.middleware.enterprise$fn__72149$handle_audit_app_internal_queries__72150$fn__72152.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__72160.invoke(enterprise.clj:103)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware78995__78996$fn__78997.invoke(process_userland_query.clj:221)"
    "query_processor.middleware.catch_exceptions$catch_exceptions79060__79061$fn__79062.invoke(catch_exceptions.clj:132)"
    "query_processor$process_query79101__79102$fn__79103.invoke(query_processor.clj:80)"
    "query_processor.setup$do_with_canceled_chan72370__72371$fn__72372.invoke(setup.clj:187)"
    "query_processor.setup$do_with_database_local_settings72363__72364$fn__72365.invoke(setup.clj:181)"
    "query_processor.setup$do_with_driver72356__72357$fn__72358$fn__72359.invoke(setup.clj:166)"
    "driver$do_with_driver.invokeStatic(driver.clj:107)"
    "driver$do_with_driver.invoke(driver.clj:102)"
    "query_processor.setup$do_with_driver72356__72357$fn__72358.invoke(setup.clj:165)"
    "query_processor.setup$do_with_metadata_provider72347__72348$fn__72349$fn__72352.invoke(setup.clj:151)"
    "query_processor.store$do_with_metadata_provider58076__58077.invokeStatic(store.clj:170)"
    "query_processor.store$do_with_metadata_provider58076__58077.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider58076__58077.invokeStatic(store.clj:159)"
    "query_processor.store$do_with_metadata_provider58076__58077.invoke(store.clj:150)"
    "query_processor.setup$do_with_metadata_provider72347__72348$fn__72349.invoke(setup.clj:150)"
    "query_processor.setup$do_with_resolved_database72337__72338$fn__72339.invoke(setup.clj:128)"
    "query_processor.setup$do_with_qp_setup72375__72376.invokeStatic(setup.clj:232)"
    "query_processor.setup$do_with_qp_setup72375__72376.invoke(setup.clj:216)"
    "query_processor$process_query79101__79102.invokeStatic(query_processor.clj:78)"
    "query_processor$process_query79101__79102.invoke(query_processor.clj:71)"
    "api.dataset$run_streaming_query97876__97879$fn__97883.invoke(dataset.clj:82)"
    "query_processor.streaming$_streaming_response$fn__83568$fn__83569$fn__83570.invoke(streaming.clj:185)"
    "query_processor.streaming$_streaming_response$fn__83568$fn__83569.invoke(streaming.clj:183)"
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:174)"
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:161)"
    "query_processor.streaming$_streaming_response$fn__83568.invoke(streaming.clj:180)"
    "server.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
    "server.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
    "server.streaming_response$do_f_async$task__81558.invoke(streaming_response.clj:93)"],
   :error_type :qp,
   :ex-data {:type :qp}}],
```

### Information about your Metabase installation

Note that this is info from our current, downgraded, installation.

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Ubuntu",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-02-19",
      "tag": "v0.53.3.3",
      "hash": "0b68d6d"
    },
    "settings": {
      "report-timezone": "Europe/Amsterdam"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.2 (Debian 17.2-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.6+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.6+7-LTS",
    "os.name": "Linux",
    "os.version": "5.15.0-116-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

blocking upgrade

### Additional context

Looking at the [commits between these versions](https://github.com/metabase/metabase/compare/v0.53.3.3...v0.53.3.4), I do see that PostgreSQL array code was touched in https://github.com/metabase/metabase/pull/53551, incl. the [removal of two lines handling `PgArray`](https://github.com/metabase/metabase/compare/v0.53.3.3...v0.53.3.4#diff-122d8f1486c5b97fd092fb98e7419b767c12d378bc6e668c16b1041cd965f9cb). Might be related.

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/54190
Closes https://linear.app/metabase/issue/DRI-149/postgresql-integer-array-column-breaks-showing-query-in-v05334

### Description

Checks that the array is not null before attempting to get the array. 

### How to verify

1. Run `select cast(null as integer[])` on a Postgres database
2. It should return `null` instead of an error

### Demo

https://github.com/user-attachments/assets/1e04ec8a-5b2f-4937-b0ac-2f094b3c8175

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/test/data/interface.clj [hunk 1]
```diff
@@ -876,7 +876,7 @@
     [_driver]
     {:access_key (u.random/random-name)}))
 
-(doseq [driver [:postgres :mysql :snowflake :databricks :redshift :sqlite :vertica :athena]]
+(doseq [driver [:postgres :mysql :snowflake :databricks :redshift :sqlite :vertica :athena :oracle]]
```
Comment (rileythomp) [inline test/metabase/test/data/interface.clj:879]: This is unrelated to the other changes in this PR, but I noticed that the Oracle driver can be included in the `array-query-can-be-cached-test` and `array-query-can-be-emailed-test` tests.

**Review by snoe — APPROVED** [review]
