### PR TITLE
Fetch relevant db's metadata when card is added to a dashboard

### LINKED ISSUE #10085: Cannot connect card filter, when starting with an empty dashboard
1. Create new dashboard (or use an existing empty dashboard)
2. Add question to dashboard (I just used simple Orders table question)
3. Add a filter (I used Time All Options, since it exists in Orders)
4. *(should be able to select the card connection to filter)*

**Work-around**: Save the dashboard with at least 1 card and then edit the dashboard again, then you'll be able to connect filters.

Screencast 2019-06-03 13 27 06

It's not an issue, if you click the "Add to dashboard" from a question.

Metabase 0.32.8 (test env on H2 and production on MariaDB) with Firefox 67 and Chromium 74.

I'm not sure when this was introduced, but I remember someone created reported something similar a few months back (cannot find it), but without steps to reproduce.
Might be related to #8627

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #10085 

We weren't showing any valid fields for the new filter because we didn't have any data on the table.

This PR fetches metadata whenever a card is added to a dashboard. This should use a cached fetch and doesn't redundantly pull db metadata.

### CODE REVIEW

File: frontend/src/metabase/dashboard/dashboard.js [hunk 1]
```diff
@@ -188,6 +188,11 @@ export const addCardToDashboard = function({
     };
     dispatch(createAction(ADD_CARD_TO_DASH)(dashcard));
     dispatch(fetchCardData(card, dashcard, { reload: true, clear: true }));
+
+    // guard in case card was filtered
+    if (card.dataset_query && card.dataset_query.database) {
```
Comment (paulrosenzweig) [inline frontend/src/metabase/dashboard/dashboard.js]: I'm not 100% sure this guard is necessary. Similar logic existed in `fetchCardData`, so I copied it.

**Review by tlrobinson — APPROVED** [review]

**Review by tlrobinson — APPROVED** [review]
