### PR TITLE
fix(admin/performance): Ensure that adding or removing default values doesn't make cache policy form count as dirty

### LINKED ISSUE #42974: In Admin / Performance, form is still considered dirty after a certain kind of change is saved
### Describe the bug

On Admin / Performance, after deleting the multiplier from the Adaptive strategy and then saving changes, the form is still considered dirty and asks to abandon changes when I click a different database

### To Reproduce

   https://jam.dev/c/66517dcb-5030-4aaa-a630-2474d6507f7b

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.215-203.850.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "postgres",
      "redshift",
      "mysql",
      "bigquery-cloud-sdk",
      "mongo",
      "h2",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-21",
      "tag": "vUNKNOWN",
      "hash": "9771eaa"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

P4

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rafpaf**
Loom of the bug: https://www.loom.com/share/7b1981d1f6364ce5a9ef4f6a5e6446a1?sid=56b6eb83-13e5-49c4-8299-13bb575b8019

Loom of the bug fix: https://www.loom.com/share/c70cf15fb8684f14b047c0995fe55145?sid=9ebd9b06-17d9-4bb4-89b2-0ddc3f3f235f

- [x] unit test added

Closes #42974

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#46543** <a href="https://app.graphite.dev/github/pr/metabase/metabase/46543?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: frontend/src/metabase/admin/performance/utils.tsx [hunk 1]
```diff
@@ -315,3 +315,13 @@ export const translateConfigFromAPI = (config: CacheConfig): CacheConfig =>
...
+
+export const getDefaultValueForField = (
+  strategyType: CacheStrategyType,
+  fieldName?: string,
+) => {
+  const schema = getStrategyValidationSchema(
+    PLUGIN_CACHING.strategies[strategyType],
+  );
+  return fieldName ? schema.cast({})[fieldName] : "";
+};
```
Comment (rafpaf) [inline frontend/src/metabase/admin/performance/utils.tsx:327]: <i class='graphite__hidden'>[Re: line +328]<br/><br/></i>

Moved this function here from `frontend/src/metabase/admin/performance/components/StrategyForm.tsx`<span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/metabase/metabase/46543?utm_source=unchanged-line-comment">Graphite</a>.</span>

Comment (rafpaf) [inline frontend/src/metabase/admin/performance/utils.tsx:327]: Moved this function here from `frontend/src/metabase/admin/performance/components/StrategyForm.tsx`

File: frontend/src/metabase/admin/performance/components/StrategyForm.tsx [hunk 2]
```diff
@@ -94,14 +94,30 @@ export const StrategyForm = ({
...
+    const strategy: any = { ...(savedStrategy ?? defaultStrategy) };
+    for (const fieldName in strategy) {
+      const value = strategy[fieldName as keyof CacheStrategy];
+      const defaultValue = getDefaultValueForField(strategy.type, fieldName);
+      if (defaultValue && value === defaultValue) {
+        delete strategy[fieldName as keyof CacheStrategy];
+      }
+    }
+    return strategy;
+  }, [savedStrategy, defaultStrategy]);
```
Comment (rafpaf) [inline frontend/src/metabase/admin/performance/components/StrategyForm.tsx:115]: This solution feels heavy to me. I'd love to avoid it.

One option might be to change how default values are handled in this form.

Currently, they're shown as placeholders. On master, when you delete the value and click save, the default value becomes part of the initialValues of the Formik form. But it's not displayed in the text inputs. So there's a mismatch between the saved values and the values that appear in the text inputs, and the form is considered dirty.

An alternative approach would be this: we set each text input's value to its default value (if there is one). If someone deletes the value from the input and clicks save, the default value is put into the input before the data is submitted.

File: frontend/src/metabase/admin/performance/components/StrategyForm.tsx [hunk 3]
```diff
@@ -164,6 +182,24 @@ const StrategyFormBody = ({
...
+          // eslint-disable-next-line eqeqeq
+          if (defaultValue && value == defaultValue) {
+            setFieldValue(fieldName, undefined);
+          }
+        }
+      }
+    },
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+    [isSubmitting],
+  );
```
Comment (rafpaf) [inline frontend/src/metabase/admin/performance/components/StrategyForm.tsx:201]: The ugliness of this `==` comparison is another reason to reconsider how default values are handled in this form.

File: frontend/src/metabase/admin/performance/components/StrategyForm.tsx (hunk 2 above)
Comment (rafpaf) [reply frontend/src/metabase/admin/performance/components/StrategyForm.tsx:115]: I don't think this is a good idea anymore. The conventional behavior of our forms is to use the default value as a placeholder

File: frontend/src/metabase/admin/performance/components/StrategyForm.tsx [hunk 4]
```diff
@@ -164,6 +186,29 @@ const StrategyFormBody = ({
...
+        for (const fieldName in values) {
+          const value = values[fieldName as keyof CacheStrategy];
+          const defaultValue = getDefaultValueForField(values.type, fieldName);
+          if (
+            defaultValue !== undefined &&
+            defaultValue !== null &&
+            (value === defaultValue ||
+              // Formik initially records numbers as strings so we need to
+              // compare them as numbers
+              Number(value) === Number(defaultValue))
```
Comment (sloansparger) [inline frontend/src/metabase/admin/performance/components/StrategyForm.tsx:201]: I'm not sure I'm following the exact need for conversion here. My first comment would be to prefer comparison by strings if possible, second would be to make sure you want to use `Number` over `parseInt`/`parseFloat`.

File: frontend/src/metabase/admin/performance/components/StrategyForm.tsx [hunk 5]
```diff
@@ -94,14 +94,34 @@ export const StrategyForm = ({
...
+      if (
+        defaultValue !== undefined &&
+        defaultValue !== null &&
+        value === defaultValue
+      ) {
+        delete strategy[fieldName as keyof CacheStrategy];
+      }
+    }
+    return strategy;
+  }, [savedStrategy, defaultStrategy]);
```
Comment (sloansparger) [inline frontend/src/metabase/admin/performance/components/StrategyForm.tsx:119]:
```suggestion
  // Remove default values from the form
  const initialValues = useMemo(() => {
    return _.chain(savedStrategy ?? defaultStrategy)
      .pairs()
      .filter(([fieldName, value]) => {
        const defaultValue = getDefaultValueForField(strategy.type, fieldName);
        return defaultValue !== undefined && defaultValue !== null && value === defaultValue;
      })
      .object()
      .value();
  }, [savedStrategy, defaultStrategy]);
```

^ something like this reads a little cleaner IMO

File: frontend/src/metabase/admin/performance/components/StrategyForm.tsx [hunk 6]
```diff
@@ -164,6 +186,29 @@ const StrategyFormBody = ({
     }
   }, [selectedStrategyType, values, setFieldValue]);
 
+  useEffect(
```
Comment (sloansparger) [inline frontend/src/metabase/admin/performance/components/StrategyForm.tsx:189]: I really love to avoid syncing state / using `useEffect` as much as possible, I find less bugs result from deriving values / using `useMemo` when possible. My question is, instead of syncing the state to formik so that it computes dirtiness, would it be possible for us to compute dirtiness on our own by taking the formik idea of dirtiness + detecting if values are set to their defaults.

File: frontend/src/metabase/admin/performance/components/StrategyForm.tsx (hunk 5 above)
Comment (rafpaf) [reply frontend/src/metabase/admin/performance/components/StrategyForm.tsx]: Thanks! I used more underscore in the new draft

File: frontend/src/metabase/admin/performance/components/StrategyForm.tsx [hunk 7]
```diff
@@ -117,11 +122,38 @@ export const StrategyForm = ({
...
         isInSidebar={isInSidebar}
+        strategyType={initialValues.type}
       />
     </FormProvider>
   );
 };
 
+/** Don't count the addition/deletion of a default value as a reason to consider the form dirty */
+const isFormDirty = (values: CacheStrategy, initialValues: CacheStrategy) => {
+  const fieldNames = [...Object.keys(values), ...Object.keys(initialValues)];
```
Comment (sloansparger) [inline frontend/src/metabase/admin/performance/components/StrategyForm.tsx:133]:
```suggestion
  const fieldNames = _.uniq([...Object.keys(values), ...Object.keys(initialValues)]);
```
is this needed to avoid duplicate keys?

**Review by sloansparger — APPROVED** [review]

**Comment by rafpaf** [comment]
### Merge activity

* **Aug 28, 10:10 AM EDT**: @rafpaf merged this pull request with [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/46543).
