### PR TITLE
fix(embed-js, sdk): Properly handle restricted collection access in MetabaseBrowser

### LINKED ISSUE #66769: Users get "Stuck" in Exploration when they don't have Access to "Initial Collection" in metabase-browser
### Describe the bug

If you embed metabase-browser and set "initial collection" to a collection the user has no access to, the browser still "works". You can create a new exploration and you can see the toast at the top of the page.

From there they get a bit "stuck" because they are presented with a save option they can't use. Then, at the top, the "New Exploration" toast is isolated and looks like a clickable link but it's not. 

### To Reproduce

1. Embed metabase-browser component with EAJS
2. Set the initial-collection to a collection the user has "No access" to
3. Create a new exploration
4. Note that "save' doesn't work because the user doesn't have curate permissions
5. Note that the "new exploration" in the toast looks clickable/like navigation
6.  User is stranded

This is still confusing if the user has "No access" to the initial collection because the "New exploration" toast looks clickable. The reporting customer expected that to be another method of creating a new explore because it sounds a bit like a call to action.

https://www.loom.com/share/200e76ca88034f2b848ac1dbe8ce8959

### Expected behavior

I'm not positive but I suspect if the user doesn't have access at all to the initial collection we should show an error instead of allowing exploration? 

### Logs

_No response_

### Information about your Metabase installation

```JSON
v57.5
```

### Severity

confusing

### Additional context

Reporting customer though this would allow you to begin a new exploration because it appears to be a button.

### PR DESCRIPTION
**Pull request by sanex3339**
closes #66769
Properly handle restricted collection access in MetabaseBrowser

> Describe the bug
> If you embed metabase-browser and set "initial collection" to a collection the user has no access to, the browser still "works". You can create a new exploration and you can see the toast at the top of the page.
> 
> From there they get a bit "stuck" because they are presented with a save option they can't use. Then, at the top, the "New Exploration" toast is isolated and looks like a clickable link but it's not.
> 
> To Reproduce
> - Embed metabase-browser component with EAJS
> - Set the initial-collection to a collection the user has "No access" to
> - Create a new exploration
> - Note that "save' doesn't work because the user doesn't have curate permissions
> - Note that the "new exploration" in the toast looks clickable/like navigation
> - User is stranded
> - This is still confusing if the user has "No access" to the initial collection because the "New exploration" toast looks clickable. The reporting customer expected that to be another method of creating a new explore because it sounds a bit like a call to action.
> 
> [loom.com/share/200e76ca88034f2b848ac1dbe8ce8959](https://www.loom.com/share/200e76ca88034f2b848ac1dbe8ce8959)

To fix the issue, i had to fetch collection data for a question, so we have one extra request now.

If you watch the loom, it also describes a bug that the `New exploration` breadcrumb item when clicking does nothing. I also fixed it by resetting the editor state.

How to validate? Follow `how to reproduce` steps and ensure that now we handle such case.

### CODE REVIEW

File: frontend/src/embedding-sdk-bundle/hooks/private/use-collection-data.ts [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+import { useSdkBreadcrumbs } from "embedding-sdk-bundle/hooks/private/use-sdk-breadcrumb";
+import { useSdkSelector } from "embedding-sdk-bundle/store";
+import { getCollectionIdSlugFromReference } from "embedding-sdk-bundle/store/collections";
+import type { SdkCollectionId } from "embedding-sdk-bundle/types/collection";
+import { useGetCollectionQuery } from "metabase/api";
+import type { CollectionId } from "metabase-types/api";
+
+export const useCollectionData = (
+  collectionId: SdkCollectionId = "personal",
+  { skip = false }: { skip?: boolean } = {},
```
Comment (WiNloSt) [inline frontend/src/embedding-sdk-bundle/hooks/private/use-collection-data.ts]: This flag isn't clear enough about what it's supposed to mean. Like skipping what? What does it mean to pass `collectionId=number` and `skip: true`?

I'd rename it to be something along the lines of "should we check if users can access this collection".

File: frontend/src/embedding-sdk-bundle/components/public/CollectionBrowser/CollectionBrowser.tsx [hunk 2]
```diff
@@ -149,6 +138,18 @@ export const CollectionBrowserInner = ({
     reportLocation,
   ]);
 
+  if (
+    isObject(collectionLoadingError) &&
+    collectionLoadingError.status === 403
+  ) {
+    return (
+      <EmptyState
+        title={t`You don't have access to this collection.`}
```
Comment (WiNloSt) [inline frontend/src/embedding-sdk-bundle/components/public/CollectionBrowser/CollectionBrowser.tsx]: I found we have a similar string, but without the full stop

https://github.com/metabase/metabase/blob/96bc72a415264ce5366c645188f364ca442ce893/enterprise/frontend/src/metabase-enterprise/data-studio/data-model/components/TableSection/TableCollection.tsx#L31

We probably should use that, also, I sampled some places that use `EmptyState`, they don't have full stops.

File: frontend/src/embedding-sdk-bundle/components/private/SdkQuestionDefaultView/SdkQuestionDefaultView.tsx [hunk 3]
```diff
@@ -122,17 +124,29 @@ export const SdkQuestionDefaultView = ({
     question && shouldRunCardQuery({ question, isGuestEmbed }) && !queryResults;
 
   useEffect(() => {
-    if (
+    const isNewQuestion = originalId === "new";
+    const isExistingQuestion =
+      question &&
```
Comment (WiNloSt) [inline frontend/src/embedding-sdk-bundle/components/private/SdkQuestionDefaultView/SdkQuestionDefaultView.tsx:129]: What's the point of checking the value of `question` if you're still using optional chaining on line 131? Can't you just leave this condition (`question &&`) off?

File: frontend/src/embedding-sdk-bundle/hooks/private/use-collection-data.ts (hunk 1 above)
Comment (WiNloSt) [inline frontend/src/embedding-sdk-bundle/hooks/private/use-collection-data.ts]: This flag isn't clear what it's representing. If you look at the implementation, it's more like control whether we're checking to see if users can access a given `collectionId`. So if users care about `collectionLoadingError`, they need to not pass `skip: true` however, even with `skip: true` other propreties are still working e.g. `baseCollectionId`, `effectiveCollectionId`, but just not anything that requires the API call.

**Review by WiNloSt — APPROVED** [review]
Looks good to me 👍

File: frontend/src/embedding-sdk-bundle/components/private/SdkQuestionDefaultView/SdkQuestionDefaultView.tsx (hunk 3 above)
Comment (sanex3339) [reply frontend/src/embedding-sdk-bundle/components/private/SdkQuestionDefaultView/SdkQuestionDefaultView.tsx:129]: If i remove the explicit `question` check, typescript can't properly infer types at line 145-149

image
