### PR TITLE
[parameters] Use MBQL lib to query for field values from a card

### LINKED ISSUE #35840: Getting filter values from a model with custom columns returns an error + a FE glitch
### Describe the bug

Getting the filter values from a model that has a custom column returns an error
image

### To Reproduce

1) create a question with a custom column (e.g. products with a custom column being simply "category")
2) set it as a model
3) then create a dashboard
4) add a category filter
5) get the filter values from a model or question
6) pick the custom column

### Expected behavior

the values should get populated

### Logs

```
metabase-postgres            | 2023-11-16 03:16:38,338 ERROR middleware.log :: POST /api/dataset/parameter/values 500 77.2 ms (14 DB calls) 
metabase-postgres            | {:via
metabase-postgres            |  [{:type clojure.lang.ExceptionInfo,
metabase-postgres            |    :message
metabase-postgres            |    "Error compiling HoneySQL form: These SQL clauses are unknown or have nil values: :metabase.query-processor.util.add-alias-info/desired-alias, :metabase.query-processor.util.add-alias-info/position",
metabase-postgres            |    :data
metabase-postgres            |    {:dialect :ansi,
metabase-postgres            |     :form
metabase-postgres            |     {:from
metabase-postgres            |      [[{:from
metabase-postgres            |         [[{:from [[[:metabase.util.honey-sql-2/identifier :table ["public" "products"]]]],
metabase-postgres            |            :select
metabase-postgres            |            [[[:metabase.util.honey-sql-2/typed
metabase-postgres            |               [:metabase.util.honey-sql-2/identifier :field ["public" "products" "id"]]
metabase-postgres            |               {:metabase.util.honeysql-extensions/database-type "int8"}]
metabase-postgres            |              [[:metabase.util.honey-sql-2/identifier :field-alias ["id"]]]]
metabase-postgres            |             [[:metabase.util.honey-sql-2/typed
metabase-postgres            |               [:metabase.util.honey-sql-2/identifier :field ["public" "products" "ean"]]
metabase-postgres            |               {:metabase.util.honeysql-extensions/database-type "bpchar"}]
metabase-postgres            |              [[:metabase.util.honey-sql-2/identifier :field-alias ["ean"]]]]
metabase-postgres            |             [[:metabase.util.honey-sql-2/typed
metabase-postgres            |               [:metabase.util.honey-sql-2/identifier :field ["public" "products" "title"]]
metabase-postgres            |               {:metabase.util.honeysql-extensions/database-type "varchar"}]
metabase-postgres            |              [[:metabase.util.honey-sql-2/identifier :field-alias ["title"]]]]
metabase-postgres            |             [[:metabase.util.honey-sql-2/typed
metabase-postgres            |               [:metabase.util.honey-sql-2/identifier :field ["public" "products" "category"]]
metabase-postgres            |               {:metabase.util.honeysql-extensions/database-type "varchar"}]
metabase-postgres            |              [[:metabase.util.honey-sql-2/identifier :field-alias ["category"]]]]
metabase-postgres            |             [[:metabase.util.honey-sql-2/typed
metabase-postgres            |               [:metabase.util.honey-sql-2/identifier :field ["public" "products" "vendor"]]
metabase-postgres            |               {:metabase.util.honeysql-extensions/database-type "varchar"}]
metabase-postgres            |              [[:metabase.util.honey-sql-2/identifier :field-alias ["vendor"]]]]
metabase-postgres            |             [[:metabase.util.honey-sql-2/typed
metabase-postgres            |               [:metabase.util.honey-sql-2/identifier :field ["public" "products" "price"]]
metabase-postgres            |               {:metabase.util.honeysql-extensions/database-type "float8"}]
metabase-postgres            |              [[:metabase.util.honey-sql-2/identifier :field-alias ["price"]]]]
metabase-postgres            |             [[:metabase.util.honey-sql-2/typed
metabase-postgres            |               [:metabase.util.honey-sql-2/identifier :field ["public" "products" "rating"]]
metabase-postgres            |               {:metabase.util.honeysql-extensions/database-type "float8"}]
metabase-postgres            |              [[:metabase.util.honey-sql-2/identifier :field-alias ["rating"]]]]
metabase-postgres            |             [[:metabase.util.honey-sql-2/typed
metabase-postgres            |               [:metabase.util.honey-sql-2/identifier :field ["public" "products" "created_at"]]
metabase-postgres            |               {:metabase.util.honeysql-extensions/database-type "timestamp"}]
metabase-postgres            |              [[:metabase.util.honey-sql-2/identifier :field-alias ["created_at"]]]]
```

### Information about your Metabase installation

```JSON
v47.7
```

### Severity

P1

### Additional context

workaround: create a question from the model and then use that to populate the filter

There's also a visual regression
image

### PR DESCRIPTION
**Pull request by bshepherdson**
Closes #44077. Closes #35840.

### Description

Previously this used some custom legacy MBQL manipulation. It was
incorrect and led to a handful of bugs. Now it's a straightforward
edit of the query powered by MBQL lib.

### How to verify

Check the repros for #44077 and #35840; both of them work great now.

All custom values tests are passing.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#60510** <a href="https://app.graphite.dev/github/pr/metabase/metabase/60510?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/metabase/metabase/60510?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: test/metabase/parameters/custom_values_test.clj [hunk 1]
```diff
@@ -174,9 +174,24 @@
...
                   card
-                  [:field "NAME_2" {:base_type :type/Text}]
+                  [:field "Categories__NAME" {:base_type :type/Text}]
                   {:stage-number 1}))))))))
 
+(deftest ^:parallel with-mbql-card-test-6-expressions
+  (binding [custom-values/*max-rows* 3]
+    (testing "source card with expressions (#44703)"
+      (mt/with-temp
+        [:model/Card card (merge (mt/card-with-source-metadata-for-query
```
Comment (camsaul) [inline test/metabase/parameters/custom_values_test.clj:184]: Can't you use a mock metadata provider for this? I want to ban `with-temp` across QP + Parameters test namespaces

Comment (bshepherdson) [reply test/metabase/parameters/custom_values_test.clj:184]: Not easily; the `custom-values/values-from-card` function checks `(ms/InstanceOf :model/Card` and executes the generated query. That should probably come with a separate refactor.

File: src/metabase/parameters/custom_values.clj [hunk 2]
```diff
@@ -58,45 +60,24 @@
...
+        textual?          (lib.types.isa/string? value-column)
+        nonempty          ((if textual? lib/not-empty lib/not-null) value-column)
+        query-filter      (when query-string
+                            (if textual?
+                              (lib/contains (lib/lower value-column) (u/lower-case-en query-string))
+                              (lib/= value-column query-string)))]
+    (-> query
+        (lib/limit *max-rows*)
+        (lib/filter nonempty)
+        (cond-> #_query query-filter (lib/filter query-filter))
```
Comment (galdre) [inline src/metabase/parameters/custom_values.clj:76]: Is the `#_query` here an intentional stylistic hint as to what's being threaded? If so, I kind of like that pattern.

File: test/metabase/parameters/custom_values_test.clj (hunk 1 above)
Comment (galdre) [reply test/metabase/parameters/custom_values_test.clj:184]: @camsaul For my own learning, what is the reason, and what is an example of a good different pattern to follow? One of my first PRs here created exactly [such a test](https://github.com/metabase/metabase/blob/master/test/metabase/parameters/dashboard_test.clj#L54).

**Review by galdre — COMMENTED** [review]
The new code is *so* much easier to read and understand.

File: src/metabase/parameters/custom_values.clj (hunk 2 above)
Comment (bshepherdson) [reply src/metabase/parameters/custom_values.clj:76]: Yes, we often do this with nested threading macros, as a mnemonic placeholder kind of thing.

File: test/metabase/parameters/custom_values_test.clj (hunk 1 above)
Comment (camsaul) [reply test/metabase/parameters/custom_values_test.clj:184]: @galdre almost all of the tests in `metabase.test.query-processor-test` use mock metadata providers -- look at those for examples

**Review by camsaul — APPROVED** [review]
Cool LGTM (Let's Get This Merged)
