### PR TITLE
If the entity id is unknown when calling the export API, throw an error

### LINKED ISSUE #61227: Serializing a non existent collection entity id points to root collection (Our Analytics)
### Describe the bug

If I send a non-existent collection entity ID by mistake, it tries to export Our Analytics, and there are no errors or warnings indicating that I've most likely made a mistake. As a side note, this is the only way to select "Our Analytics" for export -- maybe there should also be a cleaner way to point to the root collection, like `collection=root`.

This happened to a customer that tried to send a dashboard ID as the `eid` and then an error popped when trying to export the root collection

### To Reproduce

1. Create any question and save it in Our Analytics
2. Create an API key
3. `POST /api/ee/serialization/export?all_collections=false&data_model=false&settings=false&collection=eid:this-id-doesnot-exist`
4. It exports Our Analytics

### Expected behavior

It should throw an error or warn me that I've sent an `eid` that doesn't exist in the logs (and it shouldn't export the root collection). There should also be a clearer way to refer to the root collection if desired

### Logs

_No response_

### Information about your Metabase installation

```JSON
v55.8.3
```

### Severity

P2

### Additional context

[Here](https://github.com/metabase/metabase/blob/f5b5de0dbd185638a37465d3d6f518d04059564c/src/metabase/models/serialization.clj#L145), to convert the eid to a regular ID, we try to find the ID of a collection with entity_id "this-id-doesnot-exist". This finds nothing so it returns nil, which is the ID of the root collection

### PR DESCRIPTION
**Pull request by nvoxland**
closes #61227
### Description

Instead of exporting "Our analytics" when `POST /api/ee/serialization/export` is passed an invalid entity_id, throw a 400 error 

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/serialization/api_test.clj [hunk 1]
```diff
@@ -157,7 +157,15 @@
                                               :dirname "check" :all_collections false :data_model false :settings false)]
                   (is (= "check/"
                          (with-open [tar (open-tar f)]
-                           (.getName ^TarArchiveEntry (first (u.compress/entries tar))))))))))))
+                           (.getName ^TarArchiveEntry (first (u.compress/entries tar))))))))
+
+              (testing "Invalid entity ID returns an error instead of falling back to root collection"
```
Comment (edpaget) [inline enterprise/backend/test/metabase_enterprise/serialization/api_test.clj:162]: always nice to break these out into separate deftests so it's easier to debug them.

**Review by edpaget — APPROVED** [review]
