### PR TITLE
Bugfix 37914 wrong filters UI in embedding

### LINKED ISSUE #37914: Text filters shown as input box in embed instead as dropdown
### Describe the bug

Decided to open this issue after spending some time reproducing #31347 and noticing the behavior has changed a lot.
Essentially, you expect filters to look the same in the embed, in the embed preview and in the dashboard inside of Metabase.

Findings:
* filter set as dropdown in dashboard, no default value for filter in dashboard, editable in embed -> filter is rendered as input box in embed 
* filter set as dropdown in dashboard, default value set for filter in dashboard, locked in embed -> filter is rendered as input box in embed
* filter set as droddown in dashboard, default value set for filter in dashboard, editable in embed -> filter is rendered as dropdown in embed as it should, but it's rendered differently in the preview

The preview features and linking of the filters seems to work properly, unlike reported in #31347.

### To Reproduce

1. Go to New -> Question -> Products -> Save
2. Create New Dashboard -> Add 3 Filters and Add the above question then link them to column Category
image
3. Link the first filter to the second one -> Save
image
4. Confirm that the link is working by selecting Doohickey for Second Filter and Gadget,Gizmo for Third filter ... Notice that on metabase works as expected and First filter only shows Doohickey as an option
image
5. Go to Sharing -> Embed your application -> Make the filters editable -> Publish
6. The filters are rendered in the embed and preview as input boxes instead of as dropdown
image

7. Edit the dashboard, set the default value for text 1 as Doohickey -> Save

8. Go to Sharing -> Embed your application -> Preview

9. In the preview Text filter is still rendered as input box but text 1 is rendered as multi-select, in the embed it is a proper dropdown

Text:
image

Text 1 in preview inside of UI:
image

Text 1 opening iframe from preview URL  in incognito mode:
image

10. Copy the iframe URL from the preview using inspect and open it in incognito mode. You will see that text and text1 are now rendered as dropdown and also that the linking of the filters is working as expected. Text2 is still rendered as input box.

11. Set text1 to locked, set a preview value for it as "Doohickey", publish, copy the iframe URL from the preview using inspect, open it in incognito mode. The results are properly filtered (Doohickey only), but text filter shows again as input box even though there is a default value
  

### Expected behavior

The filters should look the same across dashboard in MB, embed preview and real life embed. The combination of setting a default value in the dashboard and setting the filter as editable triggers this consistent behavior but it should not be needed

### Logs

_No response_

### Information about your Metabase installation

```JSON
Metabase v1.48.1
```

### Severity

Might be blocking in certain use cases

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes: https://github.com/metabase/metabase/issues/37914

Previously, we removed locked parameters entirely. This is to prevent leaking potentially sensitive values.

However, for the situation where the same field backs 1 locked or disabled paramter and 1 enabled parameter, we do
still want to send the paramater values, because the enabled parameter implies that the values are permissible to see
in the embed.

So, this change will still remove parameters based on their 'disabled/locked/enabled' status, but will NOT remove the
linked field ids if they're also being used by 'enabled' parameters.

This results in the backend correctly sending necessary parameter values to the embed, where the frontend can then
render the appropriate UI instead of falling back to just text filters.

### CODE REVIEW

File: src/metabase/api/embed.clj [hunk 1]
```diff
@@ -117,23 +117,28 @@
...
 
+(defn- classify-params-as-keep-or-remove
+  [dashboard-or-card-params embedding-params]
+  (let [param-slugs                   (map #(keyword (:slug %)) dashboard-or-card-params)
+        grouped-param-slugs           {:remove (remove (fn [k] (contains? embedding-params k)) param-slugs)}
+        grouped-embedding-param-slugs (-> (group-by #(= (second %) "enabled") embedding-params)
+                                          (update-keys {true :keep false :remove})
+                                          (update-vals #(into #{} (map first) %)))]
+    (merge-with (comp set concat)
+                {:keep [] :remove []}
```
Comment (escherize) [inline src/metabase/api/embed.clj:128]: Could these be sets?

like:
```suggestion
                {:keep #{} :remove #{}}
```

File: src/metabase/api/embed.clj [hunk 2]
```diff
@@ -275,20 +280,26 @@
...
-                                      (remove (fn [{:keys [parameter_id]}]
-                                                (contains? param-ids-to-remove parameter_id)) param-mappings))))]
+  (let [{params-to-remove :remove
+         params-to-keep   :keep}  (classify-params-as-keep-or-remove (:parameters dashboard) embedding-params)
+        param-ids-to-remove       (set (for [parameter (:parameters dashboard)
+                                             :when     (contains? params-to-remove (keyword (:slug parameter)))]
+                                         (:id parameter)))
+        param-ids-to-keep         (set (for [parameter (:parameters dashboard)
+                                             :when     (contains? params-to-keep (keyword (:slug parameter)))]
+                                         (:id parameter)))
```
Comment (escherize) [inline src/metabase/api/embed.clj:290]: what are your thoughts on using `keep` instead of `for` here?

e.g.
```
(set (keep
      (fn [{:keys [slug id]}]
        (when (contains? params-to-remove (keyword slug))
          id)
        (:parameters dashboard))))
```

**Review by escherize — APPROVED** [review]
LGTM

Thanks for fixing this, that was a subtle bug.

I really love where you've taken the style too! just left a couple other style notes (aka nitpicks and bikeshedding).
