### PR TITLE
Restore Google sign-in deactivated account message

### LINKED ISSUE #16701: Error message missing when logging in to a disabled account with Google sign-in
Regression caused by the 400 -> 401 error response change on the backend for login failure. This should be fixed by #16689.

### PR DESCRIPTION
**Pull request by noahmoss**
This was another regression caused by the 400 -> 401 response code change for auth failure (#15883). Small fix to restore the deactivated account banner:
image

We don't need to check the status of the response explicitly because a successful response will have payload set to `undefined`. So let's just check if there's a payload that includes errors.

Resolves #16701

### CODE REVIEW

File: src/metabase/api/session.clj [hunk 1]
```diff
@@ -265,7 +265,7 @@
          (if (and user (:is_active user))
            (mw.session/set-session-cookie request response session)
            (throw (ex-info (str disabled-account-message)
-                           {:status-code 400
+                           {:status-code 401
```
Comment (noahmoss) [inline src/metabase/api/session.clj:268]: This was already returning `401` because of the `http-401-on-error` wrapper, but I'm making this change for consistency.

**Comment by gusaiani** [comment]
Hi @noahmoss, as I did a couple of things recently in this domain. I'm testing this PR locally.

Can't see the message `Your acount is disabled.` :| 

This is what I see after attemping a login with a Gmail account that is not signed up to Metabase.

image

**Comment by flamber** [comment]
@gusaiani Good catch.

Issue #13068 is not about `core_user.is_active=false`, but trying to login with a different Google account than what Metabase has knowledge about (example your private Gmail instead of work account). But if the goal is to fix #13068, then it would replace PR #13183.

**Comment by noahmoss** [comment]
@flamber @gusaiani Oh, good catch, I misunderstood #13068.

Regardless, this PR does fix the `Your account was disabled` banner, which was broken by the error code change. I'll open a separate issue for it and resolve #13068 in a different PR.

**Review by flamber — APPROVED** [review]
