### PR TITLE
Some Email/Attachment Improvements and Fixes

### LINKED ISSUE #18789: Horizontal scroll of tables in email reports should be more discoverable, and apply to the table only
**Describe the bug**
When a table with a large number of columns is rendered for a dashboard subscription email, we make it horizontally scrollable. However the scroll is applied to the entire section, rather than just the table itself, so it also scrolls the pulse title, and the copy above and below the table, which is a bit awkward.

It's also quite difficult to discover the fact that the table is scrollable, particularly on mobile clients where the scroll bar might be hidden by default. We should force the scrollbar to always appear if possible, and maybe add some text to inform the user that they can scroll? cc @brunobergher 

For backend context, the scroll behavior is implemented here: https://github.com/metabase/metabase/blob/master/src/metabase/pulse/render.clj#L150-L153. It should be probably be moved down into `metabase.pulse.render.table` somewhere, but we should be careful to ensure that the link behavior still works as expected (i.e. the entire section links to the question when clicked, and text doesn't underline on hover) and that clicking and dragging the scrollbar in a web mail client still works.

Related to #18755

**To Reproduce**
1. Save a table with a relatively large number of columns as a question (e.g. any of the sample dataset tables)
2. Add the table to a dashboard
3. Send a test dashboard subscription to an email
4. Open the email in a mobile email client, like Gmail for iOS/Android

**Information about your Metabase Installation:**
Current master

**Severity**
I think the discoverability issue is pretty important, but the behavior of the scroll itself (table vs pulse section) is minor.

### LINKED ISSUE #37491: Subscription does not reflect conditional formatting
### Describe the bug

I created a custom SQL question visualized as Table. I added conditional formatting so each second row is background colored. I hid the column that is used to evaluate the odd column and then put the SQL question on the dashboard. This dashboard I tried to email using dashboard subscription. Unfortunately the conditional formatting is not present in the email.

### To Reproduce

1. Create random custom SQL question
2. Visualize it as table
3. Add some conditional formatting
4. Hide the column that is used to evaluate the conditional formatting
5. Put the question into some dashboard
6. Send dashboard as email with XLSX results attached

### Expected behavior

The question render in the email should contain the conditional formatting as well

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.4.0-148-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.6 (Ubuntu 14.6-1.pgdg22.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-05",
      "tag": "v0.48.2",
      "hash": "e66c075"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

annoying

### Additional context

_No response_

### LINKED ISSUE #45123: Can't Remove Dashboard Sole Tab Name in Pulse
### Describe the bug

For a dashboard that previously added new tabs, after removing all tabs but the last one, the pulse still attaches that last tab's name. 

### To Reproduce

1. Create a new dashboard.
2. Add a random question.
3. Create a new tab, save, then remove the new tab.
4. Email that dashboard.
5. Email shows 'Tab 1' under dashboard title.

### Expected behavior

It should not show tab's name if there is only one tab.

### Logs

_No response_

### Information about your Metabase installation

```JSON
"version": {
      "date": "2024-07-02",
      "tag": "v0.50.9",
      "hash": "720e549"
    },
```

### Severity

Mild

### Additional context

_No response_

### LINKED ISSUE #45678: Since Metabase 0.50.13, colors on tables are no longer visible on dashboard subscriptions
### Describe the bug

Before Metabase 0.50.13, we were getting subscriptions like this with conditional formatting appearing in Slack:

image

We upgraded from 0.50.10 to 0.50.13 and now we get no highlighting:
image

Which is a shame because colors help visually scan tables pretty fast.

The report still has colors in Metabase, but being able to scan it on Slack is very useful.

I see the same behavior on some slack alerts we have set up, so this doesn't seem to be exclusive to dashboard subs.

### To Reproduce

1. Send a subscription with conditional formatting enabled
2. Check that it has no colors on Slack

### Expected behavior

We should be seeing the same colors as we see in Metabase

### Logs

```[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:37-03:00 DEBUG metabase.server.middleware.log GET /api/pulse/form_input 200 11.2 ms (1 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (3 idle, 0 queued) (127 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 142}
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:37-03:00 DEBUG metabase.server.middleware.log GET /api/user/recipients 200 38.3 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (3 idle, 0 queued) (127 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 142}
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:52-03:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 57.1 ms (10 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (1 idle, 0 queued) (127 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 142}
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:52-03:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 59.5 ms (12 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (1 idle, 0 queued) (127 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 142}
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:52-03:00 DEBUG metabase.server.middleware.log GET /api/database 200 18.2 ms (1 DB calls) App DB connections: 1/15 Jetty threads: 9/50 (1 idle, 0 queued) (130 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 142}
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:52-03:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 40.2 ms (12 DB calls) App DB connections: 1/15 Jetty threads: 8/50 (1 idle, 0 queued) (130 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 142}
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:52-03:00 DEBUG metabase.server.middleware.log GET /api/setting 200 59.2 ms (16 DB calls) App DB connections: 1/15 Jetty threads: 8/50 (1 idle, 0 queued) (130 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 142}
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:52-03:00 DEBUG metabase.server.middleware.log GET /api/search 200 88.5 ms (5 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (2 idle, 0 queued) (130 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 142}
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:53-03:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "bd1b1f4a". 💾
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:53-03:00 INFO metabase.query-processor.middleware.cache Query bd1b1f4a took 9.8 s to run; minimum for cache eligibility is 3.0 s; eligible
[6df9c9db-3639-4f84-b447-0d7c5daeb174] 2024-07-16T17:10:55-03:00 DEBUG metabase.server.middleware.log POST /api/pulse/test 200 12.2 s (46 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (5 idle, 0 queued) (130 total active threads) Queries in flight: 0 (0 queued); snowflake DB 4 connections: 0/1 (0 threads blocked) {:metabase-user-id 142}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.219-208.866.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-15",
      "tag": "v0.50.13-logs",
      "hash": "8b72e50"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

### Severity

It's an annoying regression of a feature we have been using

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes: #45678

An update that passes formatted column names to the table renderer broke the conditional formatting color lookup.
This PR includes a fix, passing the original column names to the table body render function, so colors will be found
and used. It also adds a test confirming this behaviour.

Fixes: #37491

Even with fixed color lookup, if a row has conditional formatting that depends on the value of a hidden column, that row would not have its formatting applied. Now, the function that creates the color lookup is given all columns, even if they're hidden. This means that in the actual table render, all columns will be available in the color lookup and so rows can be correctly formatted. Note that the color lookup seeing all columns does NOT affect if those columns are rendered; we still correctly hide the hidden columns in rendering.

Fixes: #18789

Adjusting the pulse body structure can move the horizontal scrolling to the card's contents rather than Title +
contents, allowing for better behaviour. It appears that the horizontal scrollbar is automatically displayed when
there is an opportunity to scroll, so that part of the issue should already be covered.

Fixes: #45123

When a dashboard contains a single tab, we don't need to render that tab's title in emails. Likewise, if multiple tabs exist but only 1 contains cards, we also don't need to render the title.

### CODE REVIEW

File: src/metabase/pulse/render/body.clj [hunk 1]
```diff
@@ -226,15 +226,16 @@
...
+   {:keys [rows viz-settings format-rows?] :as unordered-data}]
+  (let [[ordered-cols ordered-rows] (order-data unordered-data viz-settings)
+        data                        (-> unordered-data
                                         (assoc :rows ordered-rows)
                                         (assoc :cols ordered-cols))
         table-body                  [:div
                                      (table/render-table
-                                      (color/make-color-selector data viz-settings)
-                                      (common/column-titles ordered-cols (::mb.viz/column-settings viz-settings) format-rows?)
+                                      (color/make-color-selector unordered-data viz-settings)
```
Comment (adam-james-v) [inline src/metabase/pulse/render/body.clj:236]: pass the unordered data here so that the color selector contains necessary data for every column, even ones hidden by viz-settings.

Comment (adam-james-v) [reply src/metabase/pulse/render/body.clj:236]: This fixes conditional formatting not showing up on rows when the condition is on a hidden column.

File: src/metabase/pulse/render/table.clj [hunk 2]
```diff
@@ -144,16 +144,16 @@
   background color for a given cell. `column-names` is different from the header in `header+rows` as the header is the
   display_name (i.e. human friendly. `header+rows` includes the text contents of the table we're about ready to
   create. If `normalized-zero` is set (defaults to 0), render values less than it as negative"
-  ([color-selector column-names contents]
-   (render-table color-selector 0 column-names contents))
+  ([color-selector column-names-map contents]
+   (render-table color-selector 0 column-names-map contents))
 
-  ([color-selector normalized-zero column-names [header & rows]]
+  ([color-selector normalized-zero {:keys [col-names cols-for-color-lookup]} [header & rows]]
```
Comment (adam-james-v) [inline src/metabase/pulse/render/table.clj:150]: here we pass the column names for display as `col-names` and the original column names for the color lookup. This fixes the conditional formatting not showing up at all.

File: src/metabase/models/dashboard.clj [hunk 3]
```diff
@@ -386,9 +386,10 @@
         (->> (filter identity)))))
 
 (defn has-tabs?
-  "Check if a dashboard has tabs."
+  "Check if a dashboard has more than 1 tab.
+  We don't need to render the tab title if only 1 exists (issue #45123)."
   [dashboard-or-id]
-  (t2/exists? :model/DashboardTab :dashboard_id (u/the-id dashboard-or-id)))
+  (< 1 (t2/count :model/DashboardTab :dashboard_id (u/the-id dashboard-or-id))))
```
Comment (qnkhuat) [inline src/metabase/models/dashboard.clj:392]: I don't think we should change this method for the sake of rendering pulse.

We could have use cases where the distinguish between 0 and 1 tab is needed.

I think if you need something specific for pusle we should define it in pulse namespace and call it `should-render-tab?`

File: src/metabase/pulse/render.clj [hunk 4]
```diff
@@ -184,7 +184,8 @@
                          title
                          description
                          [:div {:class "pulse-body"
-                                :style (style/style {:display :block
+                                :style (style/style {:overflow-x :auto
```
Comment (qnkhuat) [inline src/metabase/pulse/render.clj:187]: an explanation here would help my limited css understanding :D

File: src/metabase/pulse.clj [hunk 5]
```diff
@@ -155,9 +155,14 @@
   (let [dashboard-id (u/the-id dashboard)]
     (mw.session/with-current-user pulse-creator-id
       (let [parts (if (dashboard/has-tabs? dashboard)
-                    (let [tabs-with-cards (t2/hydrate (t2/select :model/DashboardTab :dashboard_id dashboard-id) :tab-cards)]
-                      (doall (flatten (for [{:keys [cards] :as tab} tabs-with-cards]
-                                        (concat [(tab->part tab)] (dashcards->part cards pulse dashboard))))))
+                    (let [tabs            (t2/hydrate (t2/select :model/DashboardTab :dashboard_id dashboard-id) :tab-cards)
+                          tabs-with-cards (filter #(seq (:cards %)) tabs)]
+                      (doall (flatten (for [{:keys [cards] :as tab} tabs-with-cards
+                                            :when                   (seq cards)]
```
Comment (qnkhuat) [inline src/metabase/pulse.clj:161]: we don't need to do the filter on line 159 if we have a when here.

File: src/metabase/pulse.clj [hunk 6]
```diff
@@ -155,9 +155,14 @@
...
+                                        (concat
+                                         (when (< 1 (count tabs-with-cards))
```
Comment (qnkhuat) [inline src/metabase/pulse.clj:163]: I'd make this a `should-render-tab?` in the let for better readability.

File: src/metabase/pulse/render/table.clj [hunk 7]
```diff
@@ -144,16 +144,16 @@
   background color for a given cell. `column-names` is different from the header in `header+rows` as the header is the
```
Comment (qnkhuat) [inline src/metabase/pulse/render/table.clj:144]: we should update the doc for this

**Review by qnkhuat — APPROVED** [review]
4 bugs in 1! I have a couple of readability suggestions but they're non-blocking

**Comment by qnkhuat** [comment]
oh that auto-merge is unexpected

**Comment by adam-james-v** [comment]
@qnkhuat thanks for the review and you bring up good points. Sorry about the auto-merge.
I can open a small PR that addresses the little things you've mentioned and I'll tag you for review on that one.
