### PR TITLE
UXW-136 Fix issue with bar viz on filtered column

### LINKED ISSUE #10493: Post-aggregation filters mess up histograms where x-axis is a binned number
When I try to add a post-aggregation filter on a bar chart broken out by a binned numerical column, the visualization settings seem to get blown away. If I remove the filter and re-set the x and y-axis columns, the bars appear really skinny, as if the binning/histogram behavior is broken.

This does not happen when the dimension is a binned date column. This _does_ happen with line charts if the x-axis is a binned number.

post-agg-filter-histogram

Here's what the JS console has to say about the matter:

```
dataset::fieldRefForColumn mismatch
dataset.js:70 column x undefined
fieldRefForColumnWithLegacyFallback @ dataset.js:70
fieldRefForColumn @ dataset.js:100
keyForColumn @ dataset.js:137
(anonymous) @ nested.js:155
(anonymous) @ apply_axis.js:300
(anonymous) @ d3.js:782
(anonymous) @ d3.js:962
d3_selection_each @ d3.js:968
../../../node_modules/d3/d3.js.d3_selectionPrototype.each @ d3.js:961
../../../node_modules/d3/d3.js.d3_selectionPrototype.text @ d3.js:781
(anonymous) @ d3.js:8991
(anonymous) @ d3.js:962
d3_selection_each @ d3.js:968
../../../node_modules/d3/d3.js.d3_selectionPrototype.each @ d3.js:961
axis @ d3.js:8983
../../../node_modules/d3/d3.js.d3_selectionPrototype.call @ d3.js:975
_chart.renderXAxis @ dc.js:3290
drawChart @ dc.js:3925
_chart._doRender @ dc.js:3898
_chart.render @ dc.js:1691
lineAreaBar @ LineAreaBarRenderer.js:872
barRenderer @ LineAreaBarRenderer.js:902
renderChart @ CardRenderer.jsx:87
componentDidUpdate @ CardRenderer.jsx:50
measureLifeCyclePerf @ ReactCompositeComponent.js:73
(anonymous) @ ReactCompositeComponent.js:726
notifyAll @ CallbackQueue.js:74
close @ ReactReconcileTransaction.js:78
closeAll @ Transaction.js:207
perform @ Transaction.js:154
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:65
onStateChange @ connectAdvanced.js:202
(anonymous) @ makeAssimilatePrototype.js:15
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:17
dispatch @ applyMiddleware.js:35
action @ store.js:22
_callee15$ @ actions.js:971
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:978
(anonymous) @ store.js:16
dispatch @ applyMiddleware.js:35
(anonymous) @ actions.js:912
Promise.then (async)
_callee14$ @ actions.js:911
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:928
(anonymous) @ store.js:16
dispatch @ applyMiddleware.js:35
_callee11$ @ actions.js:725
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ actions.js:77
(anonymous) @ actions.js:77
Promise.then (async)
step @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:779
(anonymous) @ store.js:16
(anonymous) @ bindActionCreators.js:3
update @ Question.js:191
update @ Query.js:112
handleCommit @ FilterSidebar.jsx:20
(anonymous) @ makeAssimilatePrototype.js:15
onChangeFilter @ FilterSidebar.jsx:48
ViewFilterPopover._this.handleCommitFilter @ FilterPopover.jsx:107
ViewFilterPopover._this.handleCommitOnEnter @ FilterPopover.jsx:97
Show 32 more frames
dataset.js:71 new undefined
fieldRefForColumnWithLegacyFallback @ dataset.js:71
fieldRefForColumn @ dataset.js:100
keyForColumn @ dataset.js:137
(anonymous) @ nested.js:155
(anonymous) @ apply_axis.js:300
(anonymous) @ d3.js:782
(anonymous) @ d3.js:962
d3_selection_each @ d3.js:968
../../../node_modules/d3/d3.js.d3_selectionPrototype.each @ d3.js:961
../../../node_modules/d3/d3.js.d3_selectionPrototype.text @ d3.js:781
(anonymous) @ d3.js:8991
(anonymous) @ d3.js:962
d3_selection_each @ d3.js:968
../../../node_modules/d3/d3.js.d3_selectionPrototype.each @ d3.js:961
axis @ d3.js:8983
../../../node_modules/d3/d3.js.d3_selectionPrototype.call @ d3.js:975
_chart.renderXAxis @ dc.js:3290
drawChart @ dc.js:3925
_chart._doRender @ dc.js:3898
_chart.render @ dc.js:1691
lineAreaBar @ LineAreaBarRenderer.js:872
barRenderer @ LineAreaBarRenderer.js:902
renderChart @ CardRenderer.jsx:87
componentDidUpdate @ CardRenderer.jsx:50
measureLifeCyclePerf @ ReactCompositeComponent.js:73
(anonymous) @ ReactCompositeComponent.js:726
notifyAll @ CallbackQueue.js:74
close @ ReactReconcileTransaction.js:78
closeAll @ Transaction.js:207
perform @ Transaction.js:154
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:65
onStateChange @ connectAdvanced.js:202
(anonymous) @ makeAssimilatePrototype.js:15
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:17
dispatch @ applyMiddleware.js:35
action @ store.js:22
_callee15$ @ actions.js:971
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:978
(anonymous) @ store.js:16
dispatch @ applyMiddleware.js:35
(anonymous) @ actions.js:912
Promise.then (async)
_callee14$ @ actions.js:911
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:928
(anonymous) @ store.js:16
dispatch @ applyMiddleware.js:35
_callee11$ @ actions.js:725
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ actions.js:77
(anonymous) @ actions.js:77
Promise.then (async)
step @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:77
(anonymous) @ actions.js:779
(anonymous) @ store.js:16
(anonymous) @ bindActionCreators.js:3
update @ Question.js:191
update @ Query.js:112
handleCommit @ FilterSidebar.jsx:20
(anonymous) @ makeAssimilatePrototype.js:15
onChangeFilter @ FilterSidebar.jsx:48
ViewFilterPopover._this.handleCommitFilter @ FilterPopover.jsx:107
ViewFilterPopover._this.handleCommitOnEnter @ FilterPopover.jsx:97
Show 32 more frames
dataset.js:72 old null
```

### PR DESCRIPTION
**Pull request by deniskaber**
Closes https://github.com/metabase/metabase/issues/10493 / UXW-136

### Description

This fixes issue with default bar visualization after applying a filter on numeric column with binning.

### How to verify

Follow steps from https://github.com/metabase/metabase/issues/10493 :

1. New Question > Orders > display as table.
2. Click on Questions column header > Distribution
3. Filter > Summaries > Count > Greater than 20
4. Visualization should still be displayed properly as bar chart

### Demo

https://github.com/user-attachments/assets/9fe8659e-b0ad-4424-b411-8fd1c11d7418

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/utils.js [hunk 1]
```diff
@@ -284,9 +284,12 @@ export function getSingleSeriesDimensionsAndMetrics(
 
   // in MBQL queries that are broken out, metrics and dimensions are mutually exclusive
   // in SQL queries and raw MBQL queries metrics are numeric, summable, non-PK/FK and dimensions can be anything
-  const metricColumns = cols.filter((col) => isMetric(col));
+  // columns with binning_info are always dimensions (they represent categorical buckets)
+  const metricColumns = cols.filter(
+    (col) => isMetric(col) && !col.binning_info,
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/lib/utils.js]: Wdyt about adjusting isMetric and isDimension functions instead? Or maybe just isDimension to see if there is `binning_info`

**Review by alxnddr — APPROVED** [review]
