### PR TITLE
Fix UX bugs in ExpressionWidget

### LINKED ISSUE #16126: ExpressionEditor loses value when user clicks away from associated name input
**To Reproduce**

1. Open orders table from a custom question
2. Click on the small grid icon to create custom column
3. Modal will appear and "Field formula" is `contenteditable` field
4. Type `1+1` (without spaces) as a field formula
5. Click on the description field (notice `1+1` got formatted as `1 + 1`) and type "Math" as description
6. Go back to the formula and delete the last digit `1` leaving the field as `1 + `
7. Click the name again (let's say you wanted to edit a typo or something)
8. Note that formula got erased together with the name of the CC

**Expected behavior**

Value is preserved when blurring from name input.

**For more information:**

See https://github.com/metabase/metabase/issues/15734 for related issues and links to adjacent fixes.

### LINKED ISSUE #16127: ExpressionEditor loses value when user resizes browser window
**To Reproduce**

1. Open orders table from a custom question
2. Click on the small grid icon to create custom column
3. Modal will appear and "Field formula" is `contenteditable` field
4. Type `1+1` (without spaces) as a field formula
5. Click on the description field (notice `1+1` got formatted as `1 + 1`) and type "Math" as description
6. Resize the window or open the dev tools
7. All your changes are now gone

**Expected behavior**

Both inputs' values be preserved when window is resized.

**Screenshot:**

**For more information:**

See https://github.com/metabase/metabase/issues/15734 for related issues and links to adjacent fixes.

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #16126
Fixes #16127

## To Reproduce #16126

Issue: ExpressionEditor lost value when user clicked away from associated name input

1. Open orders table from a custom question
2. Click on the small grid icon to create custom column
3. Modal will appear and "Field formula" is `contenteditable` field
4. Type `1+1` (without spaces) as a field formula
5. Click on the description field (notice `1+1` got formatted as `1 + 1`) and type "Math" as description
6. Go back to the formula and delete the last digit `1` leaving the field as `1 + `
7. Click the name again (let's say you wanted to edit a typo or something)
8. Note that formula got erased together with the name of the Custom column

**Updated behavior**

Value is preserved when blurring from name input.

## To Reproduce #16127

Issue: ExpressionEditor lost value when user resizes browser window

1. Open orders table from a custom question
2. Click on the small grid icon to create custom column
3. Modal will appear and "Field formula" is `contenteditable` field
4. Type `1+1` (without spaces) as a field formula
5. Click on the description field (notice `1+1` got formatted as `1 + 1`) and type "Math" as description
6. Resize the window or open the dev tools
7. All your changes are now gone

**Updated behavior**

Both inputs' values be preserved when window is resized.

**Screenshot:**

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx [hunk 1]
```diff
@@ -16,7 +18,7 @@ export default class ExpressionWidget extends Component {
     query: PropTypes.object.isRequired,
     onChangeExpression: PropTypes.func.isRequired,
     onRemoveExpression: PropTypes.func,
-    onClose: PropTypes.func.isRequired,
+    onClose: PropTypes.func,
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx:21]: Was getting a warning here when using it in dev. Hope it's ok to update the PropType along with the fix.

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx [hunk 2]
```diff
@@ -29,10 +31,12 @@ export default class ExpressionWidget extends Component {
   }
 
   UNSAFE_componentWillReceiveProps(newProps) {
-    this.setState({
-      name: newProps.name,
-      expression: newProps.expression,
-    });
+    if (!this.state || !_.isEqual(this.props.expression, newProps.expression)) {
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx:34]: All kudos to @ariya here…he did it.

Comment (kulyk) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx:34]: Wow, I'm just curious why don't we define `state` as a class property right away? This isn't a common approach, maybe it's worth a comment if it can't be avoided?

**Review by kulyk — APPROVED** [review]
Looks good 🙌

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx (hunk 2 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx:34]: The console is littered with lifecycle warnings. We prefixed them with `UNSAFE_` but this was just a temporary fix (that doesn't work in strict mode, if I understand correctly).
Just wanted to ask does it make sense to follow up with the PR to get rid of the unsupported lifecycle method and do it properly (according to the guidelines from the warning):

> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

File: frontend/test/metabase/scenarios/question/custom_column.cy.spec.js [hunk 3]
```diff
@@ -492,24 +492,25 @@ describe("scenarios > question > custom columns", () => {
...
       cy.findByText("Custom column").click();
+
+      cy.get("[contenteditable='true']").as("formula");
+
       popover().within(() => {
-        cy.get("[contenteditable='true']")
-          .as("formula")
-          .type("1+1")
-          .blur();
+        _typeUsingGet("[contenteditable='true']", "1 + 1", 400);
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/question/custom_column.cy.spec.js:506]: It was `1+1` in the original repro intentionally. We should keep it like that here.

Btw, I am experimenting with this locally and seeing good results even without helper functions.
Do you mind if I open a PR agains this one?

Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/question/custom_column.cy.spec.js:506]: Stress testing regular type (even without a delay) x10 gives me all green:
image

I'll do that in GitHub CI as well, just to make sure everything's working as expected.

File: frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx (hunk 2 above)
Comment (gusaiani) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx:34]: @kulyk @nemanjaglumac  So far I've been quite confused but this (and other things).

To be honest, it's been years since I used Class components at all in React.

I'd be quite inclined to support improvements around this, at the same time it's a bit early for me to have a solid opinion.

But definitely let's keep talking about it, please.

Comment (kulyk) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx:34]: Sorry, I probably asked a not really clear question. I wanted to know why do we check for `!this.state`? This check means that the state is not initialized in the class constructor. Why so if we can e.g. define a state as usual:

```jsx
class TheComponent extends React.Component {
    state = {
        name: "some-initial-value",
        expression: "some-initial-value",
    }
}

Comment (ariya) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx:34]: @kulyk It's used in some other places (likely legacy), see also ExpressionEditorTextfield.

While this leaves a great deal to be desired, to be honest I think we shall just do the minimum here (just like what works in ExpressionEditorTextfield) and perform a better refactoring/improvement in the master branch instead.

Comment (gusaiani) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx:34]: @kulyk, imo it would be extremely helpful if you created a Github issue with what you propose to improve here.

Could be labeled as `.TechDebt`.

Even if we don't get around to it very soon, giving these issues visibility should help us, as a team, to elect priorities in improving the codebase.

cc @ariya @nemanjaglumac
