### PR TITLE
Make it possible to convert relative filters to expressions

### LINKED ISSUE #21978: Cannot convert new relative filters to Custom Expression - creates `undefined(...)` functions
**Describe the bug**
Cannot convert new relative filters to Custom Expression - creates `undefined(...)` functions.

**To Reproduce**
1. Question > Sample > Products
2. Filter CreatedAt > Relative > Past > Starting from - Add filter
image
3. Edit the filter again, click `<` (back button) a few times until you see Custom Expression, creates `undefined(...)` functions:
image

**Expected behavior**
It should always be possible to convert GUI filter to expressions.

**Information about your Metabase Installation:**
0.43.0-rc1 and master `b9cedcc`

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/21978

TBD:
- Proofread new function names
- Proofread documentation

How to test:
- Question > Sample > Products
- Filter CreatedAt > Relative > Past > Starting from - Add filter
- Edit the filter again, click < (back button) a few times until you see Custom Expression
- Make sure the custom expression is created correctly
- Make sure it's possible to write these expressions manually

Screenshot 2022-05-05 at 18 09 26
Screenshot 2022-05-05 at 18 09 32
Screenshot 2022-05-05 at 18 09 36

### CODE REVIEW

File: frontend/src/metabase/lib/expressions/config.js [hunk 1]
```diff
@@ -226,12 +226,22 @@ export const MBQL_CLAUSES = {
     type: "boolean",
     args: ["expression", "expression", "expression"],
   },
+  interval: {
+    displayName: "timeInterval",
```
Comment (ranquild) [inline frontend/src/metabase/lib/expressions/config.js:230]: Unfortunately, the new function was called `interval` when there was existing `time-interval` function. It does a different thing, but anyway.

Comment (alxnddr) [reply frontend/src/metabase/lib/expressions/config.js:230]: Should we call this function `timeSpan` maybe to avoid confusion because of similarities in naming with the existing one?

**Review by alxnddr — COMMENTED** [review]
We need to support a new parameter when you select "include today"
Screenshot 2022-05-05 at 20 03 01

File: frontend/src/metabase/lib/expressions/config.js (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/lib/expressions/config.js:230]: I like `timespan` (or `timeSpan`). Should we get an approve from someone?

**Review by alxnddr — COMMENTED** [review]
Wdyt about fixing conversion of the Exclude filter here too? If it does not add much work. So that we can proofread copy in a single place

**Comment by ranquild** [comment]
@alxnddr Exclude filters are currently converted to plain filters. Given how it's implemented in MBQL, I don't think it's possible to translate these filters to a custom expression without adding new functions on the backend.

Screenshot 2022-05-06 at 16 14 22

Screenshot 2022-05-06 at 16 15 09

File: frontend/src/metabase/lib/expressions/config.js (hunk 1 above)
Comment (jeff-bruemmer) [reply frontend/src/metabase/lib/expressions/config.js:230]: `timeSpan` works for me.

Comment (ranquild) [reply frontend/src/metabase/lib/expressions/config.js]: Changed this to `timeSpan`. Also changed `relativeDatetime` to `relativeDateTime` to match this.

**Review by alxnddr — APPROVED** [review]
