### PR TITLE
Properly detect when Snowflake is using a local key file when expanding connection properties 

### LINKED ISSUE #45393: Snowflake RSA Private Key stored in /tmp directory on single node in load balanced setup
### Describe the bug

When using a local file for the Snowflake RSA Private Key, the key should not be stored in a `/tmp` file. This breaks when running Metabase in load balanced mode where the private key is only available on the node where the connection was originally created.

### To Reproduce

Run Metabase in load balanced setup with multiple nodes/pods. Create a Snowflake database connection using a local private key. Attempt to query Snowflake. You'll see this error if you are serviced by a pod that doesn't have the `/tmp` private key file.

```
Private key provided is invalid or not supported: /tmp/metabase-secret_5371015221724238340.tmp: null
```

### Expected behavior

If possible, it would be good to bypass the `/tmp` file pointer to the private key. If you look in the contents of `/tmp/metabase-secret_5371015221724238340.tmp` it's just a file path to the private key not the actual contents of the key.

### Logs

Private key provided is invalid or not supported: /tmp/metabase-secret_5371015221724238340.tmp: null

### Information about your Metabase installation

```JSON
Metabase 1.50.11. Postgres backend. Snowflake data warehouse. Running on EKS with 3 pods.
```

### Severity

Blocking us from using Snowflake as a Pro customer

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes https://github.com/metabase/metabase/issues/45393

Previously, the Snowflake driver's `resolve-private-key` logic was looking for the key `private-key-path` in the database details to determine whether the key is in a local path, or uploaded and stored in the `secret` table.

However, `private-key-path` doesn't seem to be in the details map at this point, and I can't find any other references to it in the code. This meant that both local keys and uploaded keys were using the same code path which would write the value from the `secret` table to a temp file. But for local keys, this value is just the path to the key file, so the temp file would contain a path and not an actual key.

I think because `metabase.models.secret/value->file!` is memoized, the file path is being cached correctly when the database is initially added. But on restart, or for a second instance in a cluster, the correct value would not be cached and it will fail. This is probably why this issue wasn't caught earlier.

Fix: instead of using `private-key-path`, it seems that `private-key-options` will be set to either `"local"` or `"uploaded"`, and we can look at this to differentiate the two types of key storage. This fixes the issue for me locally.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#46348** <a href="https://app.graphite.dev/github/pr/metabase/metabase/46348?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by troyharvey** [comment]
Thanks for working on this @noahmoss!

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 1]
```diff
@@ -97,30 +97,28 @@
...
+    details
+    (let [base-details (apply dissoc details (vals (secret/->sub-props "private-key")))
+          secret-map   (secret/db-details-prop->secret-map details "private-key")
+          private-key-file (cond
+                             ;; Local file path
+                             (= private-key-options "local")
+                             (secret/value->file! secret-map :snowflake)
+
+                             ;; Uploaded file stored in `secrets` table
+                             :else
```
Comment (escherize) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:112]: nit: you could make it explicit that this is expected to be `(= private-key-options "uploaded")`, with an else branch that throws?

**Review by escherize — APPROVED** [review]
Thank you for fixing this, you explanation and fix makes sense. (I took a stab but couldn't figure out why it wasn't behaving properly.)

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj (hunk 1 above)
Comment (noahmoss) [reply modules/drivers/snowflake/src/metabase/driver/snowflake.clj:112]: It's actually not — see the comment below the `:else` which I've preserved from the previous code. Seems like in cloud `private-key-options` isn't sent and we want to default to uploaded.
