### PR TITLE
Show loading state while fetching data in a new model page

### LINKED ISSUE #44813: Empty state shown instead of loading state in new model page
### Describe the bug

The issue is very easy to reproduce in stats instance. Locally it's easier to reproduce with network throttling.

https://github.com/metabase/metabase/assets/6830683/341cde3b-b1c9-4ebe-a844-85760a6bb030

### To Reproduce

1. Go to https://stats.metabase.com/model/new

----

1. Throttle your network 
2. Go to http://localhost:3000/model/new

### Expected behavior

Empty state is not displayed if data is still loading

### Information about your Metabase installation

master, 7091c9eb47

### Severity

P3

### PR DESCRIPTION
**Pull request by nemanjaglumac**
Closes #44813

### Description

This PR introduces a Loader while the data `isFetching`

### How to verify

1. Throttle your network
2. Go to `http://localhost:3000/model/new`
3. You should briefly see a loading spinner before the notebook vs native model UI shows up

### Demo
https://github.com/user-attachments/assets/677404e3-a290-4179-8524-181b6658d2c4

### Checklist
- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx [hunk 1]
```diff
@@ -44,6 +45,14 @@ const NewModelOptions = ({ location }: NewModelOptionsProps) => {
 
   const showMetabaseLinks = useSelector(getShowMetabaseLinks);
 
+  if (isFetching) {
+    return (
+      <Center style={{ flexGrow: 1, height: "100vh" }}>
```
Comment (kamilmielnik) [inline frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx:50]: :x: `100vh` causes the page to be scrollable

File: frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx [hunk 2]
```diff
@@ -44,6 +45,14 @@ const NewModelOptions = ({ location }: NewModelOptionsProps) => {
...
+        <Loader size="lg" data-testid="loading-indicator" />
+      </Center>
+    );
```
Comment (kamilmielnik) [inline frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx:53]: We should use the `DelayedLoadingSpinner`:
- the delay makes sense here
- it will automatically (and correctly) take available height and center itself
- we probably shouldn't use `Loader` directly - it'd be great if we had a few reusable `Loader`-based components that would take care of `data-testid` and a11y (which we lack as of now)

```suggestion
  return <DelayedLoadingSpinner />;
```

File: frontend/src/metabase/models/containers/NewModelOptions/tests/common.unit.spec.tsx [hunk 3]
```diff
@@ -13,6 +16,22 @@ describe("NewModelOptions (OSS)", () => {
...
   describe("has data access", () => {
+    it("should render loading indicator when fetching databases (metabase#44813)", async () => {
+      fetchMock.get(
+        "path:/api/database",
+        delay(2000).then(() => {
+          return [createMockDatabase()];
+        }),
+      );
+
+      setup({ databases: [createMockDatabase()] });
```
Comment (kamilmielnik) [inline frontend/src/metabase/models/containers/NewModelOptions/tests/common.unit.spec.tsx:27]: WDYT about calling `setup` in the first line of this test, and mocking the endpoint after that with `overwriteRoutes: true` to make it more explicit which mock is going to actually take effect?

```suggestion
      setup({ databases: [createMockDatabase()] });
      
      fetchMock.get(
        "path:/api/database",
        delay(2000).then(() => {
          return [createMockDatabase()];
        }),
        { overwriteRoutes: true },
      );
```

**Review by ranquild — APPROVED** [review]
