### PR TITLE
Fix dashboard filter values coercion for actions

### LINKED ISSUE #28951: Sometimes dashboard filter values are not coerced when used with actions
**Describe the bug**
Sometimes when a dashboard filter is attached to an action parameter, its value doesn't get coerced to a number when it should happen.

**To Reproduce**

1. Connect a Postgres / MySQL database and enable actions for it
2. Create a structured model based on this database's table
3. Create an action that takes a numeric parameter (e.g. `DELETE FROM orders WHERE id = {{ id }}` (make sure to set the parameter type to "Number" when needed)
4. Create a dashboard, add an action button, add a numeric filter, and connect it to the action parameter
5. Manually paste a value into the filter
6. Try to run the action
7. You get an error about string value passed to a numeric parameter

**Expected behavior**
Metabase should coerce string filter value to a number before submitting action parameters

### PR DESCRIPTION
**Pull request by kulyk**
Closes #28951

### Description

Fixes dashboard filter values connected to numeric action parameters were not coerced to numbers before submitting the form. That was causing type mismatch errors.

### How to verify

1. Having a sample Postgres/MySQL database with actions enabled connected to Metabase
2. Create a GUI model from the products table
3. Create an action doing `UPDATE products SET category = {{ category }} WHERE id = {{ id }}` (set the ID parameter type to "number")
4. Create a new dashboard, add a products table, an ID dashboard filter, and the new action to it. Connect the ID filter to the ID action parameter
5. Fill in a product ID into the filter and hit Enter
6. Click the action button, and fill in a new product category (e.g. Gadget)
7. Click "Run", the action should change the category

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/223203022-2b03c3e0-9036-4ea2-830c-e05054183bff.mp4

**After**

https://user-images.githubusercontent.com/17258145/223203047-eeebd8f2-be19-4f36-be1b-25b379bf82a6.mp4

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28963)

### CODE REVIEW

File: frontend/src/metabase/actions/components/ActionViz/Action.tsx [hunk 1]
```diff
@@ -84,13 +84,13 @@ export function ActionComponent({
...
       const params = {
-        ...setNumericValues(
-          dashcardParamValues,
-          generateFieldSettingsFromParameters(
-            dashcard?.action?.parameters ?? [],
-          ),
-        ),
+        ...setNumericValues(dashcardParamValues, fieldSettings),
         ...parameterMap,
       };
```
Comment (kulyk) [inline frontend/src/metabase/actions/components/ActionViz/Action.tsx:95]: The root cause is that we didn't use the action's form field setting directly, and instead, we tried to generate them out of action parameters. There's a parameter type mismatch between implicit and explicit actions that makes `generateFieldSettingsFromParameters` treat numeric parameters as strings. Although `generateFieldSettingsFromParameters` should never be called for explicit actions what form settings are always defined, but I believe it still might be worth fixing in another PR

File: frontend/src/metabase/actions/components/ActionViz/Action.unit.spec.tsx [hunk 2]
```diff
@@ -174,6 +176,61 @@ describe("Actions > ActionViz > ActionComponent", () => {
...
+          "path:/api/dashboard/123/dashcard/456/execute",
+        );
+        expect(await call?.request?.json()).toEqual({
+          modelId: 777,
+          parameters: {
+            parameter_1: 44,
+          },
+        });
+      });
+    });
```
Comment (kulyk) [inline frontend/src/metabase/actions/components/ActionViz/Action.unit.spec.tsx:233]: I reached out for help about this assertion not working, but somehow it suddenly started working just fine 🤷‍♂️

File: frontend/src/metabase/actions/components/ActionViz/Action.tsx (hunk 1 above)
Comment (EmmadUsmani) [reply frontend/src/metabase/actions/components/ActionViz/Action.tsx:95]: I noticed that in the only other two places where `generateFieldSettingsFromParameters` is called ([`ActionParmetersInputForm`](https://github.com/metabase/metabase/blob/a90fff13405ffc232ff18e6dce51a8a08245d115/frontend/src/metabase/actions/containers/ActionParametersInputForm/ActionParametersInputForm.tsx#L97), [`PublicAction`](https://github.com/metabase/metabase/blob/a90fff13405ffc232ff18e6dce51a8a08245d115/frontend/src/metabase/public/containers/PublicAction/PublicAction.tsx#L37)) we are also first checking if `action.visualization_settings.fields` is defined before calling the method as a backup.

To me it seems like a bit of an anti-pattern to manually do this check everywhere we use the function. It could be easy for a developer to forget this check which may cause another bug like this one. Perhaps we should refactor the function or define another function like `getActionFieldSettings(action, backupParams)` that does this check inside of it and use that instead?

**Comment by iethree** [comment]
I'm not entirely sure what to make of this, but I've tried this on several DBs and cannot reproduce the original issue locally on `master`.  Even though the frontend sends a string, the backend seems able to coerce it properly.

changePrice
Screen Shot 2023-03-06 at 2 57 33 PM

**Comment by iethree** [comment]
> I'm not entirely sure what to make of this, but I've tried this on several DBs and cannot reproduce the original issue locally on `master`. Even though the frontend sends a string, the backend seems able to coerce it properly.

Update: wrote an e2e test, and on master, mysql works without the frontend type coercion, but postgres is more strict. 🤷 will push the test to this branch, where both tests pass ✅ 

Screen Shot 2023-03-06 at 3 31 11 PM

File: frontend/src/metabase/actions/components/ActionViz/Action.tsx (hunk 1 above)
Comment (iethree) [reply frontend/src/metabase/actions/components/ActionViz/Action.tsx:95]: I agree with @EmmadUsmani that this is not very ergonomic for frontend developers. I think, however, that the better solution is to make implicit and explicit action parameters behave consistently so that type casting can be based on the parameters (not visualization_settings), so we could always just rely on the types provided by the backend for parameters, and leave visualization_settings for more cosmetic things like placeholder text, etc.

Put differently, this code is confusing because our entire parameters situation is confusing. The better fix is to make it less confusing all the way down. 🥴

File: e2e/support/helpers/e2e-dragndrop-helpers.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
+// Rely on native drag events, rather than on the coordinates
+// We have 3 "drag-handles" in this test. Their indexes are 0-based.
```
Comment (iethree) [inline e2e/support/helpers/e2e-dragndrop-helpers.js:2]: we were using this helper function in the pivot tables unit test, and it works perfectly here, so I extracted it to use multiple places.

I think this function is based on [this github issue.](https://github.com/cypress-io/cypress/issues/3942#issuecomment-485648100)

File: e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js [hunk 4]
```diff
@@ -75,29 +77,47 @@ const MODEL_NAME = "Test Action Model";
 
           cy.findByRole("dialog").within(() => {
             fillActionQuery(
-              `INSERT INTO ${TEST_TABLE} (team_name) VALUES ('Zany Zebras')`,
+              `UPDATE ${TEST_TABLE} SET score = {{ new_score }} WHERE id = {{ id }}`,
```
Comment (iethree) [inline e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js:80]: instead of adding a new e2e test, I beefed up this existing one to test more aspects of actions.

File: frontend/src/metabase/actions/components/ActionViz/Action.unit.spec.tsx (hunk 2 above)
Comment (iethree) [reply frontend/src/metabase/actions/components/ActionViz/Action.unit.spec.tsx:233]: 618061a7-cbef-4eeb-b6c1-eb46ec30d21b_text

File: frontend/src/metabase/actions/components/ActionViz/Action.tsx (hunk 1 above)
Comment (iethree) [inline frontend/src/metabase/actions/components/ActionViz/Action.tsx:95]: I think this little change will make this PR also close https://github.com/metabase/metabase/issues/28953

Essentially doing the same coercion based on settings for dashboard and form values.

```suggestion
        ...setNumericValues({
          ...dashcardParamValues, 
          ...parameterMap,
         }, fieldSettings),
      };
```

**Review by iethree — APPROVED** [review]
Looks good! thanks for fixing this.

- I added an e2e test to cover dashboard param coercion
- I also suggested a change that will close another open issue related to parameter types

File: frontend/src/metabase/actions/components/ActionViz/Action.tsx (hunk 1 above)
Comment (kulyk) [reply frontend/src/metabase/actions/components/ActionViz/Action.tsx:95]: Agreeing re: making parameter behavior consistent. I think consolidating logic is still important, though: right now IMO, it is not clear which form component we should use for actions. There are a couple of options doing slightly different things, but IMO we should just have one

Comment (kulyk) [reply frontend/src/metabase/actions/components/ActionViz/Action.tsx:95]: @iethree you're absolutely right! If you don't mind, I'd do this in another PR because we also want to validate numeric dropdown values + add some test coverage around all that

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/actions/components/ActionViz/Action.tsx (hunk 1 above)
Comment (iethree) [reply frontend/src/metabase/actions/components/ActionViz/Action.tsx:95]: I agree that the layers of logic are a little confusing, but not sure we can get away with one component to rule them all without just making it confusing in a different way. We're putting actions forms in a few different places doing a few different things (create action form, run from dashboard, run from model detail). I'd love to see a more elegant structure though!

Comment (kulyk) [reply frontend/src/metabase/actions/components/ActionViz/Action.tsx:95]: FWIW, I had a draft that looked pretty decent, but it's way outdated with the latest `master` already. I'd love to get back to it once we sort out open issues first
