### PR TITLE
fix: increment graph revision when parent permissions are copied

### LINKED ISSUE #41498: Permissions for a subcollection are not set if the admin frontend does not see the newly created subcollection
### Describe the bug

Permissions for a subcollection are not set if the admin frontend does not see the newly created subcollection (which was created by another user in the meantime).

### To Reproduce

1. open admin settings
2. create a sub-collection by another user (in another PC)
3. set permission for some user/group, but in root collection for #2 (and firstly activate option "Also change sub-collections")
4. permission is not set for sub-collection created in step #2

### Expected behavior

Set permissions on all sub-collections regardless of what the admin frontend currently sees.
(do not require a **manual** refresh of the admin frontend before setting permissions).

### Logs

_No response_

### Information about your Metabase installation

```JSON
Metabase v v0.49.4
```

### Severity

low

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edpaget**
closes #41498
### Description

This fixes a bug where selecting update permissions on subcollections does not take into account new collections created between loading the collection permissions page and submitting changes. This updates the collection revision model to write a new revision when the collection permissions graph changes due to the insertion of a new collection which means we would respond 409 to the graph update. This makes sure the administrator double checks the set of collections they want to change to take into account the new collections. 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/permissions/models/permissions.clj [hunk 1]
```diff
@@ -366,23 +366,22 @@
...
-     ;; on some occasions through weirdness we might accidentally try to insert a key that's already been inserted
-     (catch Throwable e
-       (log/error e (u/format-color 'red "Failed to grant permissions"))
-       ;; if we're running tests, we're doing something wrong here if duplicate permissions are getting assigned,
-       ;; mostly likely because tests aren't properly cleaning up after themselves, and possibly causing other tests
-       ;; to pass when they shouldn't. Don't allow this during tests
-       (when config/is-test?
-         (throw e))))))
+  "Grant permissions for `group-or-id` and return the inserted permissions. Two-arity grants any arbitrary Permissions `path`."
+  [group-or-id path]
```
Comment (johnswanson) [inline src/metabase/permissions/models/permissions.clj:370]: heyyyy, I knew I'd just fixed this (this is the same thing we saw earlier and I was like, I swear I fixed this somewhere else 😂 )

**Review by johnswanson — APPROVED** [review]
