### PR TITLE
Fix date/range native query template tags for UNIX timestamp columns

### LINKED ISSUE #11934: Input to date-string->range does not match schema
Running 0.34.2, we have the following table:

```sql
CREATE TABLE `users` (
`user_id` int unsigned NOT NULL AUTO_INCREMENT,
`user_type` enum('dummy1','dummy2','dummy3') ,
`signup_time` int unsigned comment 'unix timestamp',
`published_time` int unsigned comment 'unix timestamp'  default null,
`reviewed_time` int unsigned comment 'unix timestamp' default null
);
```

and a native sql question like this:

```sql
select DATE(FROM_UNIXTIME(signup_time)) as signup_date, COUNT(*) AS published_count
from users
where user_type in ('dummy1','dummy2')
and GREATEST(published_time,reviewed_time)<=signup_time+(60*60*24*30)
[[AND  {{date}}]]
group by signup_date
```

In `users` table metadata, `signup_time`, `published_time` and `reviewed_time` fields are configured as `UNIX timestamp (seconds)`

**Note:** for this particular question we need this filter `GREATEST(published_time,reviewed_time)<=signup_time+(60*60*24*30)` which cannot be configured by using a custom question.
When creating a custom question, without adding this where clause, we haven't had issues filtering the data by using date filters. This only applies to Native queries.

**Logs**
```
WARN middleware.process-userland-query :: Query failure {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "Unable to substitute parameters",
 :stacktrace
 ("--> driver.sql.parameters.substitute$substitute$fn__71266.invoke(substitute.clj:69)"
  "driver.sql.parameters.substitute$substitute.invokeStatic(substitute.clj:66)"
  "driver.sql.parameters.substitute$substitute.invoke(substitute.clj:57)"
  "driver.sql$fn__71299.invokeStatic(sql.clj:42)"
  "driver.sql$fn__71299.invoke(sql.clj:38)"
  "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
  "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
  "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:50)"
  "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)"
  "query_processor.middleware.parameters$expand_all$replace_42749__42750.invoke(parameters.clj:59)"
  "mbql.util.match$replace_in_collection$iter__24076__24080$fn__24081.invoke(match.clj:132)"
  "mbql.util.match$replace_in_collection.invokeStatic(match.clj:131)"
  "mbql.util.match$replace_in_collection.invoke(match.clj:126)"
  "query_processor.middleware.parameters$expand_all$replace_42749__42750.invoke(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)"
  "query_processor.middleware.parameters$fn__42765$substitute_parameters_STAR___42770$fn__42771.invoke(parameters.clj:82)"
  "query_processor.middleware.parameters$fn__42765$substitute_parameters_STAR___42770.invoke(parameters.clj:79)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__41578.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__43094.invoke(resolve_driver.clj:22)"
  "query_processor.middleware.store$initialize_store$fn__46220$fn__46221.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__46220.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__37366.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__40619.invoke(async_wait.clj:89)"),
 :query
 {:native
  {:query
   "select DATE(FROM_UNIXTIME(signup_time)) as signup_date, COUNT(*) AS published_count\nfrom users\nwhere user_type in ('dummy1','dummy2')\nand GREATEST(published_time,reviewed_time)<=signup_time+(60*60*24*30)\n[[AND  {{date}}]]\ngroup by signup_date",
   :template-tags {:date {:id "1ef79484-c3eb-d904-5b8d-1ffa002f14d5", :name "date", :display-name "Signup date", :type "dimension", :dimension ["field-id" 219], :widget-type "date/range"}}},
  :type "native",
  :parameters [{:type "date/range", :target ["dimension" ["template-tag" "date"]], :value "2020-02-01~2020-02-29"}],
  :async? true,
  :middleware {:add-default-userland-constraints? true, :userland-query? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [74, -43, -105, 72, 5, 57, -122, -92, 114, 84, -93, -125, -70, 85, -14, -99, 5, 94, 62, -68, 49, 41, 118, 18, -124, 47, -50, 43, -124, -28, -19, -68]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :cause
 {:class clojure.lang.ExceptionInfo,
  :error "Input to date-string->range does not match schema: \n\n\t   [(named (not (instance? java.lang.String 2020)) date-string) nil]  \n\n",
  :ex-data {:type :schema.core/error, :value [2020 nil], :error [(named (not (instance? java.lang.String 2020)) date-string) nil]}},
 :ex-data
 {:type :schema.core/error,
  :params {"date" (map->FieldFilter {:field {:name "signup_time", :parent_id nil, :table_id 23, :base_type :type/Integer}, :value {:type :date/range, :value 2020}})},
  :parsed-query
  ["select DATE(FROM_UNIXTIME(signup_time)) as signup_date, COUNT(*) AS published_count\nfrom users\nwhere user_type in ('dummy1','dummy2')\nand GREATEST(published_time,reviewed_time)<=signup_time+(60*60*24*30)\n"
   (optional "AND  " (param "date"))
   "\ngroup by signup_date"]}}
```

**To Reproduce**
1. Configure the parameter for this question for `{date}`
2. Select `Field Filter` and select `Users` table, `signup_time` field and  `Date range` for Filter widget type. Save the question.
3. When selecting a date range we get `Unable to substitute parameters` error in screen, logs are pasted above

**Expected behavior**
Should filter on `signup_time` by the date range selected.

**Screenshots**
Annotation 2020-02-18 161922

**Information about your Metabase Installation:**
- Your browser and the version: N/A
- Your operating system: CentOS 7
- Your databases: MySQL
- Metabase version: 0.34.2
- Metabase hosting environment: N/A
- Metabase internal database:  H2

**Severity**
How severe an issue is this bug to you? 
blocking most of our users as we need native queries questions to be able to use the date range or date filter widgets

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #11934

### CODE REVIEW

File: test/metabase/driver/common/parameters/values_test.clj [hunk 1]
```diff
@@ -135,57 +168,71 @@
...
 
   (testing "Card query template tag wraps error in tag details"
     (tt/with-temp Card [param-card {:dataset_query
                                     (data/native-query
-                                     {:query "SELECT {{x}}"
-                                      :template-tags
-                                      {"x"
-                                       {:id "x-tag", :name "x", :display-name "Number x",
-                                        :type :number, :required false}}})}]
+                                      {:query "SELECT {{x}}"
```
Comment (walterl) [inline test/metabase/driver/common/parameters/values_test.clj]: Why the extra space indent? Doesn't [this rule](https://guide.clojure.style/#one-space-indent) apply?

File: test/metabase/query_processor_test/unix_timestamp_test.clj [hunk 2]
```diff
@@ -74,10 +74,31 @@
...
+                     :native   (merge (parameters-test/count-with-field-filter-query driver/*driver* :sightings :timestamp)
+                                      (mt/$ids sightings
+                                        {:template-tags {"timestamp" {:name         "timestamp"
+                                                                      :display-name "Sighting Timestamp"
+                                                                      :type         :dimension
+                                                                      :dimension    $timestamp
+                                                                      :widget-type  :date/range}}
+                                         :parameters    [{:type   :date/range
+                                                          :target [:dimension [:template-tag "timestamp"]]
+                                                          :value  "2014-02-01~2015-02-29"}]}))}]
```
Comment (walterl) [inline test/metabase/query_processor_test/unix_timestamp_test.clj]: Simplify with `mt/native-query`?

```suggestion
        (let [query (mt/native-query
                     (merge (parameters-test/count-with-field-filter-query driver/*driver* :sightings :timestamp)
                            (mt/$ids sightings
                                     {:template-tags {"timestamp" {:name         "timestamp"
                                                                   :display-name "Sighting Timestamp"
                                                                   :type         :dimension
                                                                   :dimension    $timestamp
                                                                   :widget-type  :date/range}}
                                      :parameters    [{:type   :date/range
                                                       :target [:dimension [:template-tag "timestamp"]]
                                                       :value  "2014-02-01~2015-02-29"}]})))]
```

**Review by walterl — APPROVED** [review]
Looks great! My comments are all minor formatting/style related.

The concern I had in #12120 is that, if we should take a field's special type into account, wouldn't there be _n-base-field-types_ × _n-special-field-types_ cases to cover, in some more general way? But looking at this PR of yours, I get the sense that we can handle those cases as we need to. :+1:

File: test/metabase/driver/common/parameters/values_test.clj [hunk 3]
```diff
@@ -30,29 +32,53 @@
...
+                       :base_type    :type/Date
+                       :special_type nil})
+              :value {:type  :date/range
+                      :value "2015-04-01~2015-05-01"}}
+             (into {} (#'values/value-for-tag
+                       {:name         "checkin_date"
+                        :display-name "Checkin Date"
+                        :type         :dimension
+                        :dimension    [:field-id (data/id :checkins :date)]}
+                       [{:type :date/range, :target [:dimension [:template-tag "checkin_date"]], :value
```
[the remark this answers is not in the document]
Comment (camsaul) [reply test/metabase/driver/common/parameters/values_test.clj]: yeah

File: test/metabase/driver/common/parameters/values_test.clj (hunk 1 above)
Comment (camsaul) [reply test/metabase/driver/common/parameters/values_test.clj]: IMO `data/native-query` is a macro with a body so the 2-space-indent rule applies to it. I guess it could really go either way but I put `:style/indent 2` metadata on it a while back so that's just what CIDER does for me automatically

File: test/metabase/query_processor_test/unix_timestamp_test.clj (hunk 2 above)
Comment (camsaul) [reply test/metabase/query_processor_test/unix_timestamp_test.clj]: good idea

File: src/metabase/driver/sql/query_processor.clj [hunk 4]
```diff
@@ -147,6 +147,7 @@
 (defmethod quote-style :sql [_] :ansi)
 
 
+;; TODO - we should rename this to `unix-timestamp->honeysql`
```
[the remark this answers is not in the document]
Comment (camsaul) [reply src/metabase/driver/sql/query_processor.clj]: true
