### PR TITLE
Fix ssh tunneling for clickhouse

### LINKED ISSUE #62377: ClickHouse connections do not use SSH tunnels for all operations, causing sync failure
### Describe the bug

When connecting to a ClickHouse database via an SSH tunnel, ~and having `advanced-permissions` enabled in your Metabase token,~ some operations such as checking the ClickHouse database version will not go through the SSH tunnel. This makes it impossible to sync some ClickHouse databases with Metabase over SSH.

Note that this only happens if Metabase cannot talk directly to ClickHouse, which is not the case by default on a local Docker setup.

### To Reproduce

1. Launch a local ClickHouse database by re-using the [Docker Compose setup](https://github.com/metabase/metabase/blob/15ea427ec532ee0cc626c76615b5b2b6fa6d7cbe/modules/drivers/clickhouse/docker-compose.yml) from this repository's tests:

```
docker compose -f 'modules/drivers/clickhouse/docker-compose.yml' up -d clickhouse
```

2. Launch Metabase EE and an OpenSSH server using Docker Compose:

```yaml
name: metabase-clickhouse-ssh

volumes:
  pgdata:

services:
  metabase:
    image: metabase/metabase-enterprise:v1.56.x
    volumes:
      # - ./log4j2.xml:/metabase.db/log4j2.xml
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
      MB_PREMIUM_EMBEDDING_TOKEN: ...

      # METASTORE_DEV_SERVER_URL: https://token-check.staging.metabase.com
      # MB_RUN_MODE: dev

      JAVA_TOOL_OPTIONS: -Dlog4j.configurationFile=file:/metabase.db/log4j2.xml
    ports:
      - 127.0.0.1:3000:3000

  postgres:
    image: postgres:17.5
    # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 10s

  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD_ACCESS=true #optional
      - USER_NAME=sshuser #optional
      - USER_PASSWORD=password #optional
      - LOG_STDOUT=true #optional
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
    # volumes:
    #   - ${PWD}/sshd_extra_config.conf:/etc/ssh/sshd_config.d/sshd_extra_config.conf
    ports:
      - 2222:2222
    restart: unless-stopped
```

3. Add a hostname alias to ClickHouse that is not reachable by Metabase, and reachable by the SSH tunnel:

```bash
# Replace 192.168.97.6 with a non-reachable address on the same network as Metabase
docker compose exec -it metabase bash -c 'echo "192.168.97.6 clickhouse-alias" >> /etc/hosts'
```

```bash
# Replace 192.168.107.2 with the actual address for the ClickHouse container
docker compose exec -it openssh-server bash -c 'echo "192.168.107.2 clickhouse-alias" >> /etc/hosts'
```

4. Create a ClickHouse connection in Metabase with the following details:

* Host: `clickhouse-alias`
* Username: `user_with_password`
* Password: `foo@bar!`
* Use an SSH tunnel ✔️ 
* SSH tunnel host: `openssh-server` (or a suitable DNS alias)
* SSH tunnel port: 2222
* SSH tunnel username: `sshuser`
* SSH authentication: Password
* SSH tunnel password: `password`

The connection modal will show an error, but the connection will actually be created and attempt syncing in the background:

Image

The database will show as connected, but syncing will never complete and no table metadata ever shows up:

Image

The root cause seems to be that checking for `connection-impersonation` happens outside of the SSH tunnel:

```
2025-08-19 20:27:05,113 ERROR driver.util :: Failed to check feature 'connection-impersonation' for database 'ClickHouse'
java.util.concurrent.TimeoutException: Timed out after 5.0 s
```

### Expected behavior

Always use any configured SSH tunnel for all database connection traffic.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:141.0) Gecko/20100101 Firefox/141.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "clickhouse"
    ],
    "run-mode": "dev",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2025-08-08",
      "tag": "v1.56.1.4",
      "hash": "f8cd3e3"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.5 (Debian 17.5-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "6.14.10-orbstack-00291-g1b252bd3edea",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Blocking ~a customer~ 2 Cloud customers

### Additional context

https://metaboat.slack.com/archives/C05MPF0TM3L/p1755636952573469?thread_ts=1755636125.657619&cid=C05MPF0TM3L

### PR DESCRIPTION
**Pull request by ericnormand**
Closes #62377

This fix removes the cloud? check which was not going through the ssh tunnel and causing errors, cascading into an inability to add clickhouses behind a tunnel and inability to sync them.

## To reproduce

Set up the docker-compose as in the verification steps below.

Add the clickhouse database:

- Host: clickhouse
- Port: 8123
- Username: user
- Password: password
- Use an SSH tunnel ✔️
- SSH tunnel host: openssh-server (or a suitable DNS alias)
- SSH tunnel port: 2222
- SSH tunnel username: user
- SSH authentication: Password
- SSH tunnel password: password

It either fails to add or it does add and fails to sync.

To double check that it is indeed clickhouse and not the openssh server, try adding the postgres behind the tunnel:

- Host: postgres
- Port: 5432
- Database name: metabase
- Username: user
- Password: password
- Use an SSH tunnel ✔️
- SSH tunnel host: openssh-server (or a suitable DNS alias)
- SSH tunnel port: 2222
- SSH tunnel username: user
- SSH authentication: Password
- SSH tunnel password: password

It should add and sync fine.

## To verify

Set up a `docker-compose.yml` with this contents:

```
version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: password

  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD_ACCESS=true #optional
      - USER_NAME=user
      - USER_PASSWORD=password
      - LOG_STDOUT=true #optional
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
    # volumes:
    #   - ${PWD}/sshd_extra_config.conf:/etc/ssh/sshd_config.d/sshd_extra_config.conf
    ports:
      - 2222:2222
    restart: unless-stopped
```

Start the docker-compose:

```
docker compose up --force-recreate
```

Add the clickhouse database into metabase:

- Host: clickhouse
- Username: user
- Password: password
- Use an SSH tunnel ✔️
- SSH tunnel host: openssh-server (or a suitable DNS alias)
- SSH tunnel port: 2222
- SSH tunnel username: user
- SSH authentication: Password
- SSH tunnel password: password

It should work.

### CODE REVIEW

**Comment by ericnormand** [comment]
Still looking into whether we can test this tunnel stuff in our CI.

File: modules/drivers/clickhouse/src/metabase/driver/clickhouse_version.clj [hunk 1]
```diff
@@ -28,12 +28,18 @@
...
+                    cloud-stmt (.createStatement conn)
+                    cloud-rset (.executeQuery cloud-stmt "SELECT value='1' FROM system.settings WHERE name='cloud_mode'")]
+          (cond-> nil
+            (.next ver-rset)
+            (assoc :version          (.getString ver-rset 1)
+                   :semantic-version {:major (.getInt ver-rset 2)
+                                      :minor (.getInt ver-rset 3)})
+
+            (.next cloud-rset)
+            (assoc :cloud? (.getBoolean cloud-rset 1)))))))
```
Comment (dpsutton) [inline modules/drivers/clickhouse/src/metabase/driver/clickhouse_version.clj]: i was on fence about including the `?` in the json blob. Did you go back and forth here? I know the FE folks would be a bit annoyed at this in the json

**Comment by ericnormand** [comment]
~~Blocked until we hear more from [this](https://metaboat.slack.com/archives/C0439QDFHFZ/p1757708334532539).~~

Now unblocked https://metaboat.slack.com/archives/C0439QDFHFZ/p1759161894440009?thread_ts=1757708334.532539&cid=C0439QDFHFZ

File: modules/drivers/clickhouse/src/metabase/driver/clickhouse_version.clj (hunk 1 above)
Comment (ericnormand) [reply modules/drivers/clickhouse/src/metabase/driver/clickhouse_version.clj]: Fixed.

**Comment by dpsutton** [comment]
test failures:
```clojure
(deftest impersonation-support-check-over-ssh-tunnel-test
  (testing "driver-supports? :connection-impersonation should work through an SSH tunnel (#62377)"
    ;; Use an in-memory SSH server that forwards to the correct port through localhost.
    ;; Since the real database is still reachable locally, it's possible for the driver to ignore the SSH tunnel and
    ;; still connect to the DB. So this test runs twice, once with all correct and once with an incorrect SSH
    ;; password. The latter check should fail (returning false for `driver-supports?`) if the SSH tunnel is being
    ;; respected.
    (mt/test-driver :clickhouse
      (let [username "username", password "password"]
        (with-open [ssh-server (driver.tu/basic-auth-ssh-server username password)]
          (doseq [[correct-password? ssh-password] [[true password] [false "wrong-password"]]]
            (memoize/memo-clear! @#'clickhouse.version/get-clickhouse-version)
            (let [ssh-port (.getPort ssh-server)]
              (with-ssh-tunnel! {:tunnel-enabled true
                                 :tunnel-host "localhost"
                                 :tunnel-auth-option "password"
                                 :tunnel-port ssh-port
                                 :tunnel-user username
                                 :tunnel-pass ssh-password}
                (testing (str "using " ssh-password)
                  (is (= correct-password?
                         (driver/database-supports? :clickhouse :connection-impersonation (mt/db)))))))))))))
```
I had to change this test to not pass `mt/id` but `mt/db` as the supports? function expects a database, not a database id.

But this test no longer applies. It used to be important when we would open up a connection to check if a database was cloud or not. But now we capture that into the db details and this test no longer requires a connection and therefore using ssh or not is not relevant.

This test should go away as well. Database-supports no longer opens a connection
```clojure
(deftest clickhouse-connection-fails-test
  (mt/test-driver :clickhouse
    (mt/with-temp [:model/Database db {:details (assoc (:details (mt/db)) :password "wrongpassword")
                                       :dbms_version (:dbms_version (mt/db))
                                       :engine :clickhouse}]
      (testing "`driver/database-supports? :uploads` does not throw even if the connection fails."
        (is (false? (driver/database-supports? :clickhouse :uploads db)))
        (is (false? (driver/database-supports? :clickhouse :uploads nil))))
      (testing "`driver/database-supports? :connection-impersonation` does not throw even if the connection fails."
        (is (false? (driver/database-supports? :clickhouse :connection-impersonation db)))
        (is (false? (driver/database-supports? :clickhouse :connection-impersonation nil))))
      (testing (str "`sql-jdbc.conn/connection-details->spec` does not throw even if the connection fails, "
                    "and doesn't include the `select_sequential_consistency` parameter.")
        (is (nil? (:select_sequential_consistency (sql-jdbc.conn/connection-details->spec :clickhouse db))))
        (is (nil? (:select_sequential_consistency (sql-jdbc.conn/connection-details->spec :clickhouse nil))))))))
```

in fact, this test i think should be considered a bug report.

**Comment by rileythomp** [comment]
@dpsutton Agreed that `clickhouse-connection-fails-test` can be removed. I've added `uploads-supported-test` to check `:uploads` is supported based on the `:cloud` field, and `:connection-impersonation` support is tested in `clickhouse-set-role`. Also agree that `impersonation-support-check-over-ssh-tunnel-test` doesn't need to be checking for `:connection-impersonation` support, but I think a test for connecting with ssh is still useful. I renamed this test to `clickhouse-ssh-tunnel-test` and modified it to check that.

**Review by metamben — APPROVED** [review]

**Review by rolodato — APPROVED** [review]
