### PR TITLE
Dashboard Paramter Value Now Works in Preview Embed

### LINKED ISSUE #44962: Dashboard parameter values doesn't work in the static embed modal preview when the dashboard isn't published
### Describe the bug

image

`/preview_embed/*` endpoint is supposed to work without requiring the resource to be published.

I think the culprit might be this line
https://github.com/metabase/metabase/blob/44427fb61df5aca633d2a2aa0103457f10a656c2/src/metabase/api/embed/common.clj#L420

This util is used in the `preview_embed` as well that's why it throws this error. https://github.com/metabase/metabase/blob/44427fb61df5aca633d2a2aa0103457f10a656c2/src/metabase/api/preview_embed.clj#L62

### To Reproduce

I followed the repro here (https://github.com/metabase/metabase/issues/27643) using `Invoice` table from sample database since it contains a boolean field, but we could actually use any table. We just need the static embedded dashboard preview to call the parameter values endpoint. 

### Expected behavior

We should get the parameter values without having to publish the dashboard first.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.2+13-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.2+13-LTS",
    "os.name": "Mac OS X",
    "os.version": "14.5",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2024-06-28",
      "src_hash": "58821c9b03182508a0baad8b060bcb4a219eba4a",
      "tag": "v1.1.15-SNAPSHOT",
      "hash": "578f5d3"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes: #44962

Prior, a common util fn used both in the embed and preview_embed endpoints was causing the preview_embed to error out
when fetching dashboard parameter values because it was checking if embedding was enabled. This check is needed for
the normal embedding endpoints, but we want the preview embed endpoints to work without needing to publish the
dashboard first.

### CODE REVIEW

File: src/metabase/api/embed/common.clj [hunk 1]
```diff
@@ -414,10 +414,11 @@
 
 (defn dashboard-param-values
   "Common implementation for fetching parameter values for embedding and preview-embedding."
-  [token searched-param-id prefix id-query-params]
+  [token searched-param-id prefix id-query-params
```
Comment (escherize) [inline src/metabase/api/embed/common.clj:417]: Could you beef up the docstring on this with relevant info about `preview`?

**Review by escherize — APPROVED** [review]
