### PR TITLE
Do not let API users archive the last superuser

### LINKED ISSUE #26759: API allows deactiving yourself which can lead to lockout
**Describe the bug**
The UI protects against deactivating yourself, but there's no such protection via the API, which means you can end up locked out of an instance without any other admins.
There's currently [a check](https://github.com/metabase/metabase/blob/67c4aadd464ffed3466e9703d8fc8be41ffe9aa4/src/metabase/models/permissions_group_membership.clj#L10-L12) that makes sure there's at least 1 member in the Administrators group.

Workaround: Requires manually editing the application database table `core_user.is_active=true`

**To Reproduce**
1. Setup a new instance
2. Make a request to `DELETE http://localhost:3000/api/user/1` - it's successful and you're now locked out of the instance completely

**Expected behavior**
- Prevent deactivating yourself.
- Have a check which prevent having less than 1 active admin.

**Information about your Metabase Installation:**
Tested 0.44.6

### PR DESCRIPTION
**Pull request by tsmacdonald**
[Fixes #26759]

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/27524)

### CODE REVIEW

File: src/metabase/models/permissions_group_membership.clj [hunk 1]
```diff
@@ -27,8 +27,13 @@
...
 (defn- check-not-last-admin []
-  (when (<= (db/count PermissionsGroupMembership
-              :group_id (:id (perms-group/admin)))
+  (when (<= (:count
+             (first
+              (db/query {:select [:%count.*]
+                         :from   [[:permissions_group_membership :pgm]]
+                         :join   [[:core_user :user] [:= :user.id :pgm.user_id]]
+                         :where  [:and [:= :pgm.group_id (u/the-id (perms-group/admin))]
+                                       [:= :user.is_active true]]})))
```
Comment (tsmacdonald) [inline src/metabase/models/permissions_group_membership.clj:36]: All this nonsense is not strictly part of the ticket, but I noticed that the existing check ensuring you couldn't remove the last admin (from the permissions group side, not the user API side) didn't care if the last admin was archived. This didn't seem right, so I changed it, but it'd be great to get confirmation from @flamber or someone.

File: src/metabase/models/user.clj [hunk 2]
```diff
@@ -98,7 +100,14 @@
...
           :group_id (u/the-id (perms-group/admin))
-          :user_id  id))))
+          :user_id  id)))
+    (when (and still-superuser?
+               (false? active?)
+               (not (db/exists? PermissionsGroupMembership
+                      :group_id (:id (perms-group/admin))
+                      :user_id [:!= id])))
+      (throw (ex-info (str perms-group-membership/fail-to-remove-last-admin-msg)
+                      {:status-code 400}))))
```
Comment (tsmacdonald) [inline src/metabase/models/user.clj:110]: I don't love the nearly-duplicated logic between `user/pre-update` and `perms-group-membership/pre-delete`, but it was just different enough that I thought DRYing it up would be counter-productive.

File: test/metabase/models/permissions_group_membership_test.clj [hunk 3]
```diff
@@ -24,4 +24,16 @@
     (mt/with-temp User [user {:is_superuser true}]
       (db/delete! PermissionsGroupMembership :user_id (u/the-id user), :group_id (u/the-id (perms-group/admin)))
       (is (= false
-             (db/select-one-field :is_superuser User :id (u/the-id user)))))))
+             (db/select-one-field :is_superuser User :id (u/the-id user))))))
+
+  (testing "it should not let you remove the last admin"
+    (mt/with-single-admin-user [{id :id}]
+      (is (thrown? Exception
+                   (db/delete! PermissionsGroupMembership :user_id id, :group_id (u/the-id (perms-group/admin)))))))
```
Comment (tsmacdonald) [inline test/metabase/models/permissions_group_membership_test.clj:32]: This tests existing behavior that simply wasn't tested before (probably since `with-single-admin-user` didn't exist).

File: test/metabase/models/permissions_group_membership_test.clj [hunk 4]
```diff
@@ -24,4 +24,16 @@
...
+
+  (testing "it should not let you remove the last non-archived admin"
+    (mt/with-single-admin-user [{id :id}]
+      (mt/with-temp User [_ {:is_active    false
+                             :is_superuser true}]
+        (is (thrown? Exception
+                     (db/delete! PermissionsGroupMembership :user_id id, :group_id (u/the-id (perms-group/admin)))))))))
```
Comment (tsmacdonald) [inline test/metabase/models/permissions_group_membership_test.clj:39]: This tests the new behavior described here: https://github.com/metabase/metabase/pull/27524/files#r1062599865

File: src/metabase/models/permissions_group_membership.clj (hunk 1 above)
Comment (flamber) [reply src/metabase/models/permissions_group_membership.clj:36]: Yes, I have two expectations as noted in "Expected behavior" of the issue, which should prevent any problems; cannot deactivate yourself and make sure there's at least 1 active admin.

File: src/metabase/models/user.clj [hunk 5]
```diff
@@ -82,10 +82,18 @@
...
-                               :user_id  id)]
+  (let [membership-exists? (db/exists? PermissionsGroupMembership
+                             :group_id (:id (perms-group/admin))
+                             :user_id  id)
+        still-superuser?   (or superuser?
+                               (and (nil? superuser?) membership-exists?))]
+    ;; Do not let the last admin archive themselves
+    (when (and still-superuser?
+               (false? active?)
+               (= 1 (perms-group-membership/admin-count))) ;; The 1 is this very user
```
Comment (calherries) [inline src/metabase/models/user.clj:93]: Why isn't this sufficient? I'm having trouble imagining why `superuser?`'s value has any relevance here.
```suggestion
    (when (and membership-exists?
               (false? active?)
               (= 1 (perms-group-membership/admin-count))) ;; The 1 is this very user
```

File: src/metabase/models/user.clj [hunk 6]
```diff
@@ -82,10 +82,18 @@
...
+      (throw (ex-info (str perms-group-membership/fail-to-remove-last-admin-msg)
+                      {:status-code 400})))
```
Comment (calherries) [inline src/metabase/models/user.clj:95]: Why can't we reuse `permissions-group-membership/check-not-last-admin` for this?

File: test/metabase/test.clj [hunk 7]
```diff
@@ -287,6 +290,34 @@
...
+        _                          (db/simple-delete! PermissionsGroupMembership :group_id (:id (perms-group/admin)))
+        temp-admin                 (db/insert! User (merge (with-temp-defaults User)
+                                                           attributes
+                                                           {:is_superuser true}))
+        primary-key                (models/primary-key User)]
+    (try
+      (thunk temp-admin)
+      (finally
+        (db/delete! User primary-key (primary-key temp-admin))
+        (db/insert-many! PermissionsGroupMembership existing-admin-memberships)))))
```
Comment (qnkhuat) [inline test/metabase/test.clj:305]: `insert-many!` does not call `post-insert` on inserted entities.

I guess in this particular case it's not important because `PermissionsGroupMembership/post-insert` do is making sure the `user.is_superuser=true`.

But maybe still consider doing multiple insert-one, or you can try using `metabase-enterprise.serialization.upsert/maybe-insert-many!` for this sort of things.

File: test/metabase/test.clj [hunk 8]
```diff
@@ -287,6 +290,34 @@
   [clock & body]
   `(do-with-clock ~clock (fn [] ~@body)))
 
+(defn do-with-single-admin-user
+  [attributes thunk]
+  (let [existing-admin-memberships (db/select PermissionsGroupMembership :group_id (:id (perms-group/admin)))
+        _                          (db/simple-delete! PermissionsGroupMembership :group_id (:id (perms-group/admin)))
```
Comment (qnkhuat) [inline test/metabase/test.clj:296]: you're using `simple-delete!` to avoid delete hooks being called right? 
if so should we add a comment there?

File: src/metabase/models/user.clj [hunk 9]
```diff
@@ -82,10 +82,18 @@
 (defn- pre-update
   [{reset-token :reset_token, superuser? :is_superuser, active? :is_active, :keys [email id locale], :as user}]
   ;; when `:is_superuser` is toggled add or remove the user from the 'Admin' group as appropriate
-  (when (some? superuser?)
-    (let [membership-exists? (db/exists? PermissionsGroupMembership
-                               :group_id (:id (perms-group/admin))
-                               :user_id  id)]
+  (let [membership-exists? (db/exists? PermissionsGroupMembership
```
Comment (qnkhuat) [inline src/metabase/models/user.clj:85]:
```suggestion
  (let [in-admin-group? (db/exists? PermissionsGroupMembership
```

not part of this PR, but does this sound more descriptive?

File: src/metabase/models/permissions_group_membership.clj [hunk 10]
```diff
@@ -26,10 +26,20 @@
       (throw (ex-info (tru "You cannot add or remove users to/from the ''All Users'' group.")
                {:status-code 400})))))
 
-(defn- check-not-last-admin []
-  (when (<= (db/count PermissionsGroupMembership
-              :group_id (:id (perms-group/admin)))
-            1)
+(defn admin-count
+  "The current number of non-archived admins (superusers)"
```
Comment (qnkhuat) [inline src/metabase/models/permissions_group_membership.clj:30]: 👍  for optimizing this.

Also, docstring should end with a punctuation https://guide.clojure.style/#docstring-grammar
```suggestion
  "The current number of non-archived admins (superuser)."
```

File: test/metabase/test.clj (hunk 8 above)
Comment (qnkhuat) [reply test/metabase/test.clj:296]: now I'm thinking about it, calling `simple-delete` makes this macro incomplete.

if I do 

```clojure
(with-single-admin-user [{id :id}]
  (println (db/select User :is_superuser true)))
```

This does not guarantee to print 1.

I guess it's not important for the immediate usecase, but if you want to make this a generic macro, I think we should fix it.

File: test/metabase/models/permissions_group_membership_test.clj (hunk 4 above)
Comment (tsmacdonald) [reply test/metabase/models/permissions_group_membership_test.clj:39]: idk why comment permalinks don't work reliably. It was supposed to link to this:
image

File: src/metabase/models/user.clj (hunk 5 above)
Comment (tsmacdonald) [reply src/metabase/models/user.clj:93]: There's a scenario (probably unreachable from the current API, but I want to be future-proof since this is model-level code) where a user is not an admin, then in one update they become an admin and also get archived. In that scenario, we'll have:

| var | value
| -- | -- |
| `membership-exists?` | `false` |
| `active?` | `false` |
| `superuser?` | `true` |
| `still-superuser?` | `true` |

File: src/metabase/models/user.clj (hunk 6 above)
Comment (tsmacdonald) [reply src/metabase/models/user.clj]: Fair point, fixed here: https://github.com/metabase/metabase/pull/27524/commits/d1d755bb9e8391358b026027fbac803669259b3d

I wasn't convinced it was any better until I renamed `check-not-last-admin` to something more descriptive.

File: test/metabase/test.clj (hunk 7 above)
Comment (tsmacdonald) [reply test/metabase/test.clj:305]: My rationale with skipping the lifecycle hooks was that the `existing-admin-memberships` presumably would've been validated by `post-insert` and so forth when they were originally inserted. All we're doing here is restoring the DB state to what it was a few seconds previously.

File: src/metabase/models/user.clj (hunk 5 above)
Comment (calherries) [reply src/metabase/models/user.clj]: In that scenario, since the user is not an admin, there must be at least one other admin. So setting this user to be admin and also archiving them should be a valid operation, albeit senseless.

File: test/metabase/test.clj (hunk 8 above)
Comment (tsmacdonald) [reply test/metabase/test.clj:296]: > you're using simple-delete! to avoid delete hooks being called right?

Yes, for the reasons explained below.

> <snip> does not guarantee to print 1.

Good point, fixed.  Rather than futzing with the hooks it seemed easier to just save and restore `is_superuser` directly.  Since this is very behind-the-scenes code I feel okay about doing it directly.

File: test/metabase/test.clj (hunk 7 above)
Comment (tsmacdonald) [reply test/metabase/test.clj:310]: here's the commit https://github.com/metabase/metabase/pull/27524/commits/f012b9498bd67d4e062a7bafb68b33624807ed1a

**Review by calherries — APPROVED** [review]
nice

**Comment by nemanjaglumac** [comment]
@tsmacdonald did you intentionally skip the backport?
