### PR TITLE
Actions preprocess queries before compiling

### LINKED ISSUE #47139: Basic actions do not work for models with a UUID primary key
### Describe the bug

Basic actions do not work for models with a UUID type primary key.

### To Reproduce

1. Create a table with an UUID primary key. For example:
```
CREATE TABLE public.fuel_ean (
   id UUID PRIMARY KEY,
   npi_class TEXT,
   fuel_family TEXT
);

INSERT INTO public.fuel_ean (id, npi_class, fuel_family) VALUES
('df87adec-f142-4547-8866-3e05fe0991f5', 'Car', 'Gasoline'),
('e38d48f2-3a4e-4b1f-b2e9-8d77ec8f42bf', 'Truck', 'Diesel'),
('b1d4c5e2-8fc4-4297-94d6-9a847c2f0b45', 'SUV', 'Hybrid');
```
2. Scan the table, and ensure the `id` column is set as a primary key, and filter type is drop down in the table metadata.
3. Create a simple model and enable basic actions for it
4. Open the model, click on an id to view an individual record
5. Select `...` / Update, and try to update the record.
6. (!)It fails with an error message: 
```
Missing primary key parameter: "id"
```
<img width="488" alt="image" src="https://github.com/user-attachments/assets/ad86dd99-54d1-472f-8eaa-e8061e0b8804">

7. Go to the model, enter Model details / Actions, try to trigger an action from there
8.(!)The action fails with the following error:
```
ERROR: operator does not exist: uuid = character varying 
Hint: No operator matches the given name and argument types. You might need to add explicit type casts. 
```

<img width="478" alt="image" src="https://github.com/user-attachments/assets/cbc1aea2-0539-40a7-95f0-a07f2ca5f579">


### Expected behavior

Actions should work on uuid fields.

### Logs

```
postgres-sample-15-1    | 2024-08-22 16:13:21.912 UTC [262] ERROR:  operator does not exist: uuid = character varying at character 65                                                                                 
postgres-sample-15-1    | 2024-08-22 16:13:21.912 UTC [262] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.                                                  
postgres-sample-15-1    | 2024-08-22 16:13:21.912 UTC [262] STATEMENT:  DELETE  FROM "public"."fuel_ean" WHERE "public"."fuel_ean"."id" = $1                                                                          
postgres-sample-15-1    | 2024-08-22 16:13:21.914 UTC [262] ERROR:  current transaction is aborted, commands ignored until end of transaction block                                                                   

                                                                                                                                     
metabase-v1.50.21-ee-1  | 2024-08-22 16:13:21,920 DEBUG middleware.log :: POST /api/action/4/execute 400 193.0 ms (21 DB calls) {:metabase-user-id 1}                                                                 
metabase-v1.50.21-ee-1  | {:via                                                                                                                                                                                       
metabase-v1.50.21-ee-1  |  [{:type clojure.lang.ExceptionInfo,                                                                                                                                                        
metabase-v1.50.21-ee-1  |    :message                                                                                                                                                                                 
metabase-v1.50.21-ee-1  |    "Batch entry 0 DELETE  FROM \"public\".\"fuel_ean\" WHERE \"public\".\"fuel_ean\".\"id\" = ('123') was aborted: ERROR: operator does not exist: uuid = character varying\n  Hint: No oper
ator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 65  Call getNextException to see other errors in the batch.",                                                 
metabase-v1.50.21-ee-1  |    :data                                                                                                                                                                                    
metabase-v1.50.21-ee-1  |    {:message                                                                                                                                                                                
metabase-v1.50.21-ee-1  |     "Batch entry 0 DELETE  FROM \"public\".\"fuel_ean\" WHERE \"public\".\"fuel_ean\".\"id\" = ('123') was aborted: ERROR: operator does not exist: uuid = character varying\n  Hint: No ope
rator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 65  Call getNextException to see other errors in the batch.",                                                
metabase-v1.50.21-ee-1  |     :status-code 400},                                                                                                                                                                      
metabase-v1.50.21-ee-1  |    :at [metabase.driver.sql_jdbc.actions$do_with_auto_parse_sql_error invokeStatic "actions.clj" 73]}],                               
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-08-21",
      "tag": "v1.50.21",
      "hash": "ec9f5d7"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.19 (Debian 12.19-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.1.75-0-virt",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
}
```


### Severity

Reported by a customer

### Additional context

The issue was reported and replicated while using PostgreSQL. I haven't tried with other databases.

### PR DESCRIPTION
**Pull request by wzimrin**
We need to preprocess queries (and use the results) to ensure that we properly cast arguments in where clauses

Closes https://github.com/metabase/metabase/issues/47139

### Description

The original issue was happening because we weren't converting the arguments in the where clause to uuids and then trying to compare a string to a uuid.  To fix this, we need to preprocess the query, which checks the types of arguments and annotates things so that when we generate the sql, it will convert things appropriately.  However, preprocessing also includes limit parameters, which we need to eliminate if we want to generate valid sql.

### How to verify

Follow the steps in the issue

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/driver/sql_jdbc/actions.clj [hunk 1]
```diff
@@ -209,7 +207,7 @@
   [driver action database {database-id :database, :as query}]
   (let [raw-hsql    (mbql-query->raw-hsql driver query)
         delete-hsql (-> raw-hsql
-                        (dissoc :select)
+                        (dissoc :select :limit)
```
Comment (wzimrin) [inline src/metabase/driver/sql_jdbc/actions.clj:210]: :row/update uses select-keys to pull stuff out instead of dissoc'ing a list of keys.  I considered switching this and the line below to do the same thing instead of dissocing specific things out, but wasn't convinced enough to make the switch.

File: test/metabase/actions_test.clj [hunk 2]
```diff
@@ -560,3 +560,70 @@
...
+                               :pk? true}
+                              {:field-name "name"
+                               :base-type :type/Text}]
+                             [[#uuid "d6b02fa2-bf7b-4b32-80d5-060b649c9859" "Tim"]
+                              [#uuid "d39bbe77-4e2e-4b7b-8565-cce90c25c99b" "Bob"]
+                              [#uuid "b34b5c6e-2613-494a-9278-8a74c7ea915e" "Jane"]]]]
+     (mt/with-actions-enabled
+       (binding [*current-user-permissions-set* (delay #{"/"})]
+         ~@body))))
+
```
Comment (bshepherdson) [inline test/metabase/actions_test.clj:580]: Using an ad-hoc dataset like this, but whose name coincides with one of the Sample Database tables, is a trap for the unwary reader of the code.

Can we rename this table to `uuid_people` or something, or just make up a totally new table name like `employees` or `cafeteria_staff`?

**Review by bshepherdson — CHANGES_REQUESTED** [review]

**Review by bshepherdson — APPROVED** [review]
