### PR TITLE
Fix static embedding dashboard calling GET: /api/dashboard unnecessarily

### LINKED ISSUE #63310: Static-embedded and publicly shared dashboards attempt to call /api/database and /api/query_metadata
EMB-793

### Describe the bug

When a dashboard is shared via a public link or static embedding and then loaded, the frontend attempts to call the endpoints /api/database and /api/query_metadata. These are unnecessary calls and will fail.

Image

### To Reproduce

Share any dashboard via a public link or static embedding and see the api calls made while the dashboard is loading.

### Expected behavior

These endpoints should not be called by questions / dashboards shared via public links or static embedding .

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "athena",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-09-03",
      "tag": "v1.56.4.2",
      "hash": "5583c1b"
    },
    "settings": {
      "report-timezone": "Etc/UTC"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Noticed while troubleshooting something else.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
closes #63310
Closes EMB-793

### Backport reason
The code was backported to 55 (via https://github.com/metabase/metabase/pull/60835), and 56 (via #59529), so it should be safe to double backport now.

### Description

In the original code before #59529, we render `DashboardEmptyStateWithoutAddPrompt` directly inside `PublicOrEmbeddedDashboardView` and this component doesn't need to check conditions that relies on `GET /api/database`. After the consolidation every dashboard uses the same component, so we probably missed this case.

### How to verify

1. E2E should pass.
1. Comment out this line and run E2E again, it should now fail.
        https://github.com/metabase/metabase/blob/bb6ca06a39ca33fdea12f45097ce54fa0fd6ba1b/frontend/src/metabase/dashboard/components/Dashboard/components/Grid.tsx#L59

### Demo

image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/Dashboard/components/Grid.tsx [hunk 1]
```diff
@@ -46,7 +48,16 @@ export const Grid = ({
...
-  const { data: databasesResponse, isError } = useListDatabasesQuery();
+  /**
+   * In the original code before (metabase#59529), we render `DashboardEmptyStateWithoutAddPrompt` directly
+   * inside `PublicOrEmbeddedDashboardView` and this component doesn't need to check conditions that relies
+   * on `GET /api/database`. After the consolidation every dashboard uses the same component, so we probably
+   * missed this case.
+   */
+  const isLoggedIn = useSelector((state) => !!getUser(state));
+  const { data: databasesResponse, isError } = useListDatabasesQuery(
+    isLoggedIn ? undefined : skipToken,
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/components/Dashboard/components/Grid.tsx:59]: comment out this line and run the test again, it should fail.

**Review by heypoom — APPROVED** [review]
Skipping useListDatabase when user is not logged in looks good!

**Comment by oisincoveney** [comment]
Thanks for catching this!
