### PR TITLE
Fix snowflake ssh tunnel

### LINKED ISSUE #17663: Cannot connect to Snowflake via SSH
**Describe the bug**
We are not able to setup a connection to Snowflake via SSH. When we try to add the database and click "Save" all form values are reset and there is also no error Message. The XHR request does get an error 400 with some empty values

```
{
    "valid": false,
    "dbname": null,
    "message": null
}
```

Also the server logs of the metabase instance show an Exception (see Logs).

**Logs**

```
2021-08-30 10:46:22,507 ERROR driver.util :: Database connection error
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.base/java.util.regex.Matcher.reset(Unknown Source)
        at java.base/java.util.regex.Matcher.<init>(Unknown Source)
        at java.base/java.util.regex.Pattern.matcher(Unknown Source)
        at clojure.core$re_matcher.invokeStatic(core.clj:4856)
        at clojure.core$re_find.invokeStatic(core.clj:4898)
        at clojure.core$re_find.invoke(core.clj:4898)
        at metabase.util.ssh$include_ssh_tunnel_BANG_.invokeStatic(ssh.clj:135)
        at metabase.util.ssh$include_ssh_tunnel_BANG_.invoke(ssh.clj:130)
        at metabase.util.ssh$fn__35627.invokeStatic(ssh.clj:162)
        at metabase.util.ssh$fn__35627.invoke(ssh.clj:152)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invokeStatic(connection.clj:195)
        at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invoke(connection.clj:191)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:209)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:205)
        at metabase.driver.sql_jdbc$fn__82278.invokeStatic(sql_jdbc.clj:35)
        at metabase.driver.sql_jdbc$fn__82278.invoke(sql_jdbc.clj:33)
        at metabase.driver.snowflake$eval624$fn__626.invoke(snowflake.clj:301)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.util$can_connect_with_details_QMARK_$fn__29859.invoke(util.clj:34)
        at metabase.util$do_with_timeout$fn__15630.invoke(util.clj:346)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2021-08-30 10:46:22,517 ERROR driver.snowflake :: (type message)
=> nil
2021-08-30 10:46:22,518 ERROR api.database :: Cannot connect to Database
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.base/java.util.regex.Matcher.reset(Unknown Source)
        at java.base/java.util.regex.Matcher.<init>(Unknown Source)
        at java.base/java.util.regex.Pattern.matcher(Unknown Source)
        at clojure.core$re_matcher.invokeStatic(core.clj:4856)
        at clojure.core$re_matches.invokeStatic(core.clj:4886)
        at clojure.core$re_matches.invoke(core.clj:4886)
        at metabase.driver.snowflake$eval406$fn__407.invoke(snowflake.clj:34)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:39)
        at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:22)
        at clojure.lang.RestFn.invoke(RestFn.java:442)
        at metabase.api.database$test_database_connection.invokeStatic(database.clj:401)
        at metabase.api.database$test_database_connection.doInvoke(database.clj:391)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at metabase.api.database$fn__64755$test_connection_details__64760$fn__64761.invoke(database.clj:448)
        at metabase.api.database$fn__64755$test_connection_details__64760.invoke(database.clj:430)
        at metabase.api.database$fn__64785.invokeStatic(database.clj:467)
        at metabase.api.database$fn__64785.invoke(database.clj:454)
        at compojure.core$wrap_response$fn__1996.invoke(core.clj:160)
        at compojure.core$wrap_route_middleware$fn__1980.invoke(core.clj:132)
        at compojure.core$wrap_route_info$fn__1985.invoke(core.clj:139)
        at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:151)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008.invoke(core.clj:200)
        at metabase.server.middleware.auth$enforce_authentication$fn__77067.invoke(auth.clj:14)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008.invoke(core.clj:200)
        at compojure.core$make_context$handler__2036.invoke(core.clj:287)
        at compojure.core$make_context$fn__2038.invoke(core.clj:296)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at compojure.core$make_context$fn__2038.invoke(core.clj:297)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at compojure.core$make_context$fn__2038.invoke(core.clj:297)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at compojure.core$make_context$fn__2038.invoke(core.clj:297)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at compojure.core$make_context$fn__2038.invoke(core.clj:297)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at compojure.core$make_context$fn__2038.invoke(core.clj:297)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at compojure.core$make_context$fn__2038.invoke(core.clj:297)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at metabase.api.routes$fn__77133$fn__77135.invoke(routes.clj:70)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008.invoke(core.clj:200)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.server.routes$fn__79369$fn__79370.doInvoke(routes.clj:57)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008.invoke(core.clj:200)
        at compojure.core$make_context$handler__2036.invoke(core.clj:287)
        at compojure.core$make_context$fn__2038.invoke(core.clj:296)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
        at metabase.server.routes$fn__79357$fn__79359.invoke(routes.clj:41)
        at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
        at compojure.core$routes$fn__2008.invoke(core.clj:200)
        at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77124.invoke(exceptions.clj:98)
        at metabase.server.middleware.exceptions$catch_api_exceptions$fn__77121.invoke(exceptions.clj:86)
        at metabase.server.middleware.log$log_api_call$fn__79283$fn__79284$fn__79285.invoke(log.clj:209)
        at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
        at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
        at metabase.server.middleware.log$log_api_call$fn__79283$fn__79284.invoke(log.clj:201)
        at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
        at toucan.db$_do_with_call_counting.invoke(db.clj:209)
        at metabase.server.middleware.log$log_api_call$fn__79283.invoke(log.clj:200)
        at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__78902.invoke(browser_cookie.clj:30)
        at metabase.server.middleware.security$add_security_headers$fn__57732.invoke(security.clj:148)
        at metabase.server.middleware.json$wrap_json_body$fn__79047.invoke(json.clj:62)
        at metabase.server.middleware.json$wrap_streamed_json_response$fn__79065.invoke(json.clj:98)
        at metabase.server.middleware.offset_paging$handle_paging$fn__57754.invoke(offset_paging.clj:42)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__79626.invoke(keyword_params.clj:55)
        at ring.middleware.params$wrap_params$fn__79642.invoke(params.clj:69)
        at metabase.server.middleware.misc$maybe_set_site_url$fn__36092.invoke(misc.clj:59)
        at metabase.server.middleware.session$bind_current_user$fn__42987$fn__42988.invoke(session.clj:257)
        at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:238)
        at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:230)
        at metabase.server.middleware.session$bind_current_user$fn__42987.invoke(session.clj:256)
        at metabase.server.middleware.session$wrap_current_user_info$fn__42974.invoke(session.clj:216)
        at metabase.server.middleware.session$wrap_session_id$fn__42960.invoke(session.clj:162)
        at metabase.server.middleware.auth$wrap_api_key$fn__77075.invoke(auth.clj:27)
        at ring.middleware.cookies$wrap_cookies$fn__79546.invoke(cookies.clj:216)
        at metabase.server.middleware.misc$add_content_type$fn__36075.invoke(misc.clj:27)
        at metabase.server.middleware.misc$disable_streaming_buffering$fn__36100.invoke(misc.clj:76)
        at ring.middleware.gzip$wrap_gzip$fn__79588.invoke(gzip.clj:86)
        at metabase.server.middleware.misc$bind_request$fn__36103.invoke(misc.clj:93)
        at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__79302.invoke(ssl.clj:48)
        at metabase.server$async_proxy_handler$fn__78846.invoke(server.clj:71)
        at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Unknown Source)
2021-08-30 10:46:22,530 DEBUG middleware.log :: POST /api/database 400 20.6 ms (0 DB calls)
{:valid false, :dbname nil, :message nil}
```

**To Reproduce**
1. Go to /admin/databases/create
2. Provide all Snowflake information
3. Check "Use an SSH-tunnel for database connections"
4. Provide SSH connection information
4. Click "Save"

**Expected behavior**
The database being added to Metabase or at least an error messages I can see from what error occurred.

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-gb",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.225-169.362.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.9"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-26",
      "tag": "v0.40.3.1",
      "branch": "release-x.40.x",
      "hash": "0550b86"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

We are deploying Metabase into Kubernetes using the official helm chart.

**Severity**
Blocking some users

**Additional context**
* when we do not select SSH we get a 5s timeout coming from Snowflake (as our instance has an IP allow list)
* when we select SSH the error happens instantly and we also cannot see any logs on the bastion host we provided to connect to.

### PR DESCRIPTION
**Pull request by snoe**
Fixes #17663

### CODE REVIEW

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 1]
```diff
@@ -662,3 +663,21 @@
...
+      (not (ssh/use-ssh-tunnel? details))
+      details
+
+      ;; tunnel in use, and is open
+      (ssh/ssh-tunnel-open? details)
+      details
+
+      ;; tunnel in use, and is not open
+      :else
+      (ssh/include-ssh-tunnel! details))))
```
Comment (metamben) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:683]: Wouldn't it make sense to delegate to the parent (`:sql-jdbc`) driver?

File: test/metabase/driver/sql_jdbc/connection_test.clj [hunk 2]
```diff
@@ -212,3 +221,145 @@
...
+                             (mt/rows (mt/run-mbql-query venues {:filter [:= $id 60] :fields [$name]})))))]
+              ;; check that some data can be queried
+              (check-row)
+              ;; kill the ssh tunnel; fortunately, we have an existing function that can do that
+              (ssh/close-tunnel! (sql-jdbc.conn/db->pooled-connection-spec (mt/db)))
+              ;; check the query again; the tunnel should have been reestablished
+              (check-row))))))))
+
+(deftest test-ssh-tunnel-connection-h2
+  (testing (str "We need a customized version of this test for H2. It will bring up a new H2 TCP server, pointing to "
```
Comment (metamben) [inline test/metabase/driver/sql_jdbc/connection_test.clj:272]: I see this has been moved, still it might make sense to explain why H2 needs special treatment (not running a TCP server).

File: test/metabase/driver/sql_jdbc/connection_test.clj [hunk 3]
```diff
@@ -212,3 +221,145 @@
...
+                                     :tunnel-user ssh-test/ssh-username
+                                     :tunnel-pass ssh-test/ssh-password)]
+        (t2.with-temp/with-temp [Database tunneled-db {:engine (tx/driver), :details tunnel-db-details}]
+          (mt/with-db tunneled-db
+            (sync/sync-database! (mt/db))
+            (is (= [["Polo Lounge"]]
+                   (mt/rows (mt/run-mbql-query venues {:filter [:= $id 60] :fields [$name]}))))))))))
+
+(deftest test-ssh-tunnel-reconnection
+  ;; for now, run against Postgres, although in theory it could run against many different kinds
```
Comment (metamben) [inline test/metabase/driver/sql_jdbc/connection_test.clj:248]: This is a bit outdated, `:mysql` is also tested.

**Review by metamben — APPROVED** [review]
LGTM

**Comment by saadbahir** [comment]
Hello @snoe 

I reported a regression in 49.4 in regards to the SSH tunnel for AWS RDS Postgres right [here](https://github.com/metabase/metabase/issues/41439)

Do you know whether this PR might have impacted that?
