### PR TITLE
Keep click behavior when reset settings

### LINKED ISSUE #14919: Clicking "Reset to defaults" on dashboard card visualization settings also removes all Click Behavior
**Describe the bug**
When a dashboard card is configured with Click Behavior, then those will also be removed, when using the "Reset to defaults" in the visualization settings.

**To Reproduce**
1. Simple question > Sample Dataset > Products, and save as "Q1" to dashboard
2. On dashboard in edit-mode, hover "Q1" card and click "Click Behavior" > select "Category" > select "Custom Destination" > select "URL" > input `/` as the address, click Done, and Done in the sidebar.
image
3. Hover the card and click "Visualization Options" > click "Reset to defaults" > Done.
image
4. Hover the card and click "Click Behavior" - now all behaviors have been removed.
image

**Expected behavior**
Clicking "Reset to defaults" in "Visualization Options" shouldn't also remove Click Behavior (unless otherwise noted)

**Information about your Metabase Installation:**
Metabase 0.38.0

**Additional context**
Continuation of #14597, which fixed formatting getting reset, when adding Click Behavior.

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/14919

Check the original issue for repro steps.
The fix is pretty straightforward: keep `click_behavior` settings when reset to defaults.
`click_behavior` setting can exist on the card level as well as on the column level for table visualizations.

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/settings.js [hunk 1]
```diff
@@ -287,3 +287,26 @@ export function mergeSettings(first: Settings = {}, second: Settings = {}) {
...
+      if (fieldSettings.click_behavior == null) {
+        return;
+      }
+
+      newSettings.column_settings = newSettings.column_settings || {};
+      newSettings.column_settings[key] = {
+        click_behavior: fieldSettings.click_behavior,
+      };
+    });
+  }
```
Comment (gusaiani) [inline frontend/src/metabase/visualizations/lib/settings.js:309]: This block _could_ be extracted onto a named function.

Benefits might be:

1. giving the function a nice name that will help readers grasp the intent of this block quickly.
2. making function `getClickBehaviorSettings` very quick to understand overall.

`newSettings` could be mutated in this other function and not even need to be returned explicitly from said function for everything to work fine.

**Review by gusaiani — APPROVED** [review]
Working nicely now.

Left one minor comment inlined.

File: frontend/src/metabase/visualizations/lib/settings.js (hunk 1 above)
Comment (gusaiani) [reply frontend/src/metabase/visualizations/lib/settings.js:309]: …in other words, less cyclomatic complexity.

**Review by flamber — APPROVED** [review]
