### PR TITLE
Fix scrollbar interaction in the custom expression suggestion list

### LINKED ISSUE #41165: Cannot interact with the scrollbar in the suggestions list
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/2304f6f6-7797-4dc4-ba0c-d38c3ecedb51

### To Reproduce

1. Start a new question based on the Orders table
2. Click + to add new column
3. Type `[` to show suggestions list
4. Try to press & hold the vertical scrollbar to scroll the list

Suggestions list disappears

### Expected behavior

Scrollbar is interactive

### Information about your Metabase installation

master, 1504b86572

### Severity

P2

### PR DESCRIPTION
**Pull request by hyperNURb**
Fixes https://github.com/metabase/metabase/issues/41165

### Description
For followup for failing unit tests, see [comment](https://github.com/metabase/metabase/pull/43837#discussion_r1634495095)

I've run tests locally a couple of times to ensure everything is running smoothly 
```
Test Suites: 889 passed, 889 total
Tests:       9 skipped, 8694 passed, 8703 total
Snapshots:   0 total
Time:        461.118 s
Ran all test suites.
```

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
The CI is running here
https://github.com/metabase/metabase/pull/43996

**Comment by nemanjaglumac** [comment]
FE unit tests passed in CI.
https://github.com/metabase/metabase/actions/runs/9463925451

Just for a good measure, I ran them locally and everything seems to be working:
```
 PASS  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx (37.703 s)
  ExpressionWidget
    ✓ should render proper controls (263 ms)
    ✓ should not render Name field (36 ms)
    ✓ should render help icon with tooltip which opens documentation page (137 ms)
    ✓ should trigger onChangeExpression if expression is valid (158 ms)
    ✓ should trigger onChangeClause if expression is valid (115 ms)
    ✓ should render interactive header if it is passed (50 ms)
    withName=true
      ✓ should render Name field (28 ms)
      ✓ should validate name value (470 ms)

Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        37.997 s
```

```
 PASS  frontend/src/metabase/querying/components/FilterPicker/FilterPicker.unit.spec.tsx (7.88 s)
  FilterPicker
    without a filter
      ✓ should list filterable columns (124 ms)
      ✓ should list segments (28 ms)
      ✓ should not highlight anything (29 ms)
      ✓ should add a segment filter (37 ms)
      filter pickers
        ✓ should open correct picker for a boolean column (144 ms)
        ✓ should open correct picker for a coordinate column (275 ms)
        ✓ should open correct picker for a date column (196 ms)
        ✓ should open correct picker for a datetime column (60 ms)
        ✓ should open correct picker for a number column (122 ms)
        ✓ should open correct picker for a string column (135 ms)
        ✓ should open correct picker for a time column (95 ms)
        ✓ should open a number picker for a numeric column (54 ms)
    with a filter
      ✓ should highlight the selected column (220 ms)
      ✓ should highlight the selected segment (36 ms)
      ✓ should ignore the existing filter state when changing a column (349 ms)
      ✓ should initialize widgets correctly after changing a column (186 ms)
      ✓ should change a filter segment (58 ms)
      ✓ should replace a segment filter with a column filter (275 ms)
      filter pickers
        ✓ should open correct picker for a boolean column (15 ms)
        ✓ should open correct picker for a coordinate column (24 ms)
        ✓ should open correct picker for a date column (259 ms)
        ✓ should open correct picker for a datetime column (43 ms)
        ✓ should open correct picker for a number column (17 ms)
        ✓ should open correct picker for a string column (29 ms)
        ✓ should open correct picker for a time column (22 ms)
        ✓ should open the date picker for a specific date filter (39 ms)
        ✓ should open the date picker for a relative date filter (57 ms)
        ✓ should open the date picker for a exclude date filter (65 ms)
        ✓ should open the expression editor when column type isn't supported (132 ms)
    custom expression
      ✓ should create a filter with a custom expression (434 ms)
      ✓ should open the expression editor for unsupported expressions (47 ms)
      ✓ should update a filter with a numeric custom expression (1573 ms)

Test Suites: 1 passed, 1 total
Tests:       32 passed, 32 total
Snapshots:   0 total
Time:        7.94 s
```

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx [hunk 1]
```diff
@@ -109,60 +115,62 @@ export function ExpressionEditorSuggestions({
...
-          </ExpressionList>
-          {footers.map(suggestion => (
-            <Footer
-              key={suggestion.index}
-              suggestion={suggestion}
-              highlightedIndex={highlightedIndex}
-              onHighlightSuggestion={onHighlightSuggestion}
-            />
-          ))}
+          <div ref={ref}>
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx:118]: Do we need to attach `ref` to 2 different elements here or could we use `useMergedRef` to avoid adding an extra div?

Comment (hyperNURb) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx:118]: @kamilmielnik I was hesitant to do it since `listRef` was used internally, but it does make sense. Let me update it

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx [hunk 2]
```diff
@@ -446,6 +447,15 @@ class ExpressionEditorTextfield extends React.Component<
   };
 
   handleInputBlur = (e: React.FocusEvent) => {
+    // Ensure there is no active popup menu before we blur or
+    // that user didn't interact with the popup menu
+    if (
+      this.popupMenuTarget?.current &&
+      e.relatedTarget?.contains(this.popupMenuTarget?.current)
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx:454]: `popupMenuTarget` is always defined 
```suggestion
      this.popupMenuTarget.current &&
      e.relatedTarget?.contains(this.popupMenuTarget.current)
```

**Review by kamilmielnik — APPROVED** [review]
Works well :+1: 

Thank you for your contribution :heart:

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx [hunk 3]
```diff
@@ -48,27 +50,33 @@ type WithIndex<T> = T & {
...
-  onSuggestionMouseDown: (index: number) => void;
-  open: boolean;
-  highlightedIndex: number;
-  onHighlightSuggestion: (index: number) => void;
-  children: ReactNode;
-}) {
-  const ref = useRef(null);
-
+export const ExpressionEditorSuggestions = forwardRef<
+  HTMLDivElement,
```
Comment (romeovs) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx:54]: The ref is going on a `ul` element (`ExpressionList`).

```suggestion
  HTMLUListElement,
```

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx [hunk 4]
```diff
@@ -87,7 +95,7 @@ export function ExpressionEditorSuggestions({
   const groups = group(items);
 
   function handleMouseDown(evt: MouseEvent) {
-    if (evt.target === ref.current) {
+    if (evt.target === mergedRef.current) {
```
Comment (romeovs) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx:98]: `mergedRef` returns a function so we cannot read the `.current` property, you will need to read from the `listRef` instead.

```suggestion
    if (evt.target === listRef.current) {
```

**Comment by hyperNURb** [comment]
@kamilmielnik @romeovs  
Screenshot 2024-06-11 at 15 04 12

I'm assuming it's by design to have `ul > div > li`, right?

**Comment by kamilmielnik** [comment]
> I'm assuming it's by design to have `ul > div > li`, right?

@hyperNURb that's not intended, nice catch!

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx [hunk 5]
```diff
@@ -251,8 +259,9 @@ function ExpressionEditorSuggestionsListItem({
   }, [index, onHighlightSuggestion]);
 
   return (
-    <HoverParent>
+    <HoverParent as="li">
       <ExpressionListItem
+        as="div"
```
Comment (hyperNURb) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx:264]: I checked, `ExpressionListItem` is used only here, which means that instead of using `as="div"`, we could just change the styled element into `styled.div`

Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx:264]: We're in the process of getting rid of styled components. We're using Mantine whenever possible.

But furthermore, `ExpressionListItem` is also used for the `GroupTitle` which should then also need to be updated.
```
export const GroupTitle = styled(ExpressionListItem)`
  font-weight: bold;
  font-size: 12px;
  color: var(--mb-color-text-medium);
  pointer-events: none;
  margin-top: 12px;

  &:first-child {
    margin-top: 0;
  }
`;
```

Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx:264]: `Box` or `Flex` are the most commonly used ones.
Flex seems to be the better choice here.

Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx:264]: I couldn't find anything better than this in just a few minutes when going through some of my closed PRs.
https://github.com/metabase/metabase/pull/40136/files

Hope this helps.
