### PR TITLE
Wrap non-latin characters in a span specifying working font

### LINKED ISSUE #38753: International characters do not display in Slack alerts
### Describe the bug

Unicode characters not showing up in Slack alerts, known to affect at least these versions: v1.47.9, v1.48.3 and v1.48.5.
In email notifications the text displays as expected.

### To Reproduce

Create a native question that returns text with international characters, and set up a Slack alert for either the card or the  dashboard.

```SELECT 'هذا نص عربي عشوائي، يستخدم لأغراض توضيحية فقط. لا يحتوي على أي معنى محدد ومصمم ليكون غير مسيء.' AS Text, 'Arabic' AS Language
SELECT '这是一个随机的中文文本，仅用于说明目的。它没有具体的意义，旨在不冒犯。', 'Chinese'
UNION ALL
SELECT 'זהו טקסט עברי אקראי, המשמש למטרות המחשה בלבד. אינו מכיל משמעות מסוימת ומעוצב להיות לא מעליב.', 'Hebrew'
UNION ALL
SELECT 'árvíztűrő tükörfúrógép', 'Hungarian'
UNION ALL
SELECT '이것은 임의의 한국어 텍스트로, 설명 목적으로만 사용됩니다. 구체적인 의미를 포함하지 않으며 불쾌감을 주지 않도록 설계되었습니다.', 'Korean'
```

Results in the browser:
image

Results in Email:
image

Results in Slack:
image

### Expected behavior

All characters should be rendered correctly

### Logs

n/a

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.209-198.812.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "bigquery-cloud-sdk",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-06",
      "tag": "v1.48.5",
      "hash": "dab12cf"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    }
  }
}
```

### Severity

P1 - no workaround, reported by a customer

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes: #38753

Please keep in mind that this bug will only show up in rendered table cards, on Slack. All other static-viz chart types render as SVGs via Batik.

CSSBox seems to have a bug where font fallback doesn't work properly. This is noticeable when a font does not contain glyphs that are present in the string being rendered. For example, Lato does not have international characters (Cyrillic, Hangul, etc.), so the rendered version of tables (that show up in Slack messages) will not render properly, making the card unreadable.

Since this appears to be a downstream bug, I've opted to work around this limitation by wrapping strings containing non-lato characters in a `<span>` that specifies the font family to be sans-serif, which should properly fall back to a font that contains the glyphs and thus render legibly. 

This is done with a postwalk over the Hiccup data structure, and only attempts to wrap strings inside `#{:div :span :td :th :tr :table :p :tbody :thead}`. If a string contains any glyphs not present in the Lato font, the entire string is wrapped. This is to keep mixed strings (Latin + non-latin chars/glyphs) visibly cohesive.

### Why doesn't the fallback work as we would expect, can't we configure things to work properly?

We load the Lato font directly into our GraphicsEnvironment using `java.awt.Font/createFont`
https://github.com/metabase/metabase/blob/88a31b41217f14b6ead98829c53cd5068b5a4ba8/src/metabase/pulse/render/style.clj#L102

We do that because it's used in the SVG rendering to give charts the proper font+style. If we do not load the font in, our SVG charts render slightly incorrectly (font weight is not correct, for example).

When you create a font in this way, it is a 'physical font', and will not fallback to another font when glyphs don't exist. Logical fonts DO, but we cannot create logical fonts, they are defined by the JRE. We can derive new fonts from logical fonts, but that copies *attributes* such as size and weight but not glyphs.

It *is* possible to have fonts fall back appropriately if you rely on the system's font setup. That is, if you do NOT register Lato, and you DO have lato installed on your machine (at least for me it worked on MacOS), then fallbacks seem to work. I did not go with this approach because I want static-viz renders to still work 'out of the box', so a user shouldn't have to install Lato to get proper renders.

For now, I figured it's worth trying this solution over using Noto for 2 reasons:
- we can keep Lato, which has been the decided font style for the app for some time (this keeps things consistent where possible)
- the Noto font containing all glyphs is quite a large font (>20mb, I think) and it would be nice to avoid bundling that if we can.

The fallback clearly isn't working in the first render, which is what the render will look like without this change.
And The bottom render is after this wrapping was added:

image

### CODE REVIEW

**Comment by piranha** [comment]
It is kind of weird, I've checked [Lato's wikipedia page](https://en.wikipedia.org/wiki/Lato_(typeface)) and it says it supports Cyrillic alphabet, but on Google Fonts it does not. I wonder if it makes sense downloading [from their site](https://www.latofonts.com/lato-free-fonts/) and trying that out?

**Comment by adam-james-v** [comment]
> It is kind of weird, I've checked [Lato's wikipedia page](https://en.wikipedia.org/wiki/Lato_(typeface)) and it says it supports Cyrillic alphabet, but on Google Fonts it does not. I wonder if it makes sense downloading [from their site](https://www.latofonts.com/lato-free-fonts/) and trying that out?

Hmm... even if it does support Cyrillic alphabet, that's not sufficient coverage, I don't think. For instance, Hangul (Korean characters, pardon my ignorance if this isn't the right way to refer to them), I don't think is covered anyway.

**Review by camsaul — DISMISSED** [review]
1. Could we just add the `font-family` style to the top-level `<body>` tag instead of trying to find each non-ASCII character and wrapping each one in its own `<span>`? That way the entire document defaults to it and you don't need to do the risky regex search-and-replace? You could actually do that in the `render-html-to-png` function below this one, we're already setting a few other things like `margin: 0` there so you can just add it to that. Don't forget `font-family` can have multiple fonts as fallbacks so you can specify whatever fancy font first and then `sans-serif` as the fallback

2. Splicing in raw HTML like this has me extremely itchy, if you actually do need to do something like this I think it would have been better to walk the Hiccup form in the `render-html-to-png` function below and wrap element bodies as needed band output modified Hiccup rather than try to search and replace in the compiled HTML. That way we don't have to worry about something like `<a href="example.com/jalapeño">` getting replaced with `<a href="example.com/jalape<span style=\"font-family: sans-serif;\">ñ</span>o">`. Then you can also test this stuff much more easily

   But of course it's even better if you can just specify the font family in the `<body>` and don't have to worry about walking anything in the first place.
   
3. This really needs some tests

4. Something like this really needs some comments explaining why you're doing what you're doing here, in a year someone is going to come in here and have to spend 10 minutes trying to figure out why in the world we're doing this

**Comment by camsaul** [comment]
Ok actually I just saw your PR description where you mentioned that CSS box font fallback doesn't work properly and Ngoc's upstream issue https://github.com/radkovo/CSSBox/issues/85 ...

Have you looked at submitting a patch to CSSBox to fix this instead of the risky hack?

I've looked at the code for a few minutes and I found the string drawing code

https://github.com/radkovo/CSSBox/blob/c3e3e0832867da4d3a8d36df13b3a203ee2c5671/src/main/java/org/fit/cssbox/awt/GraphicsRenderer.java#L423-L438

It's using AWT which I'm pretty sure has a built-in notion of fallback fonts, maybe there's a way we can configure things to fall back to Noto or whatever else when it's rendering stuff. Maybe https://docs.oracle.com/javase/8/docs/technotes/guides/intl/fontconfig.html is worth reading 

Also we are already bundling Noto in the Docker image 

https://github.com/metabase/metabase/blob/8cda1be2676ed314edb8464db86a8f9ab43574d8/Dockerfile#L37

so it's already there and the JRE should have access to it

**Comment by camsaul** [comment]
Here [this seems relevant](https://docs.oracle.com/javase/8/docs/technotes/guides/intl/font.html)

> Users can add a limited number of supported TrueType and Type 1 physical fonts as fallback fonts for logical fonts used in Java 2D rendering by installing them in the lib/fonts/fallback directory within the JRE.

That's worth trying. If it fixes things we could easily symlink Noto to that directory when we build our Docker image so the JRE will be able to use it as a fallback font when it renders AWT stuff

**Comment by adam-james-v** [comment]
Thanks for the comments, Cam. You're right about the drawbacks here.
I was also experimenting locally. I don't know exactly the reason yet, but it turns out if I specify "Lato Regular", the rendering issue goes away. So, I'll be undoing this approach anyway, and trying something along the lines of what you say, related to making sure our java.awt font stuff is properly configured.

**Comment by piranha** [comment]
> Hmm... even if it does support Cyrillic alphabet, that's not sufficient coverage, I don't think.

Yeah, but then it'll cover much more, especially for alphabets where it's very easy to notice that the font is different (Cyrillic and Greek mainly). You have no idea how _bad_ it looks when part of your string is one font and part is another.

**Comment by camsaul** [comment]
Honestly, is that a real problem we expect people to see a lot of -- mixed fonts in the same sentence because the sentence is mixing different languages with different writing systems? I would expect most stuff to be in just one language.

**Comment by piranha** [comment]
> sentence is mixing different languages with different writing systems

This is extremely common outside of English-speaking world.

File: test/metabase/pulse/render/png_test.clj [hunk 1]
```diff
@@ -13,9 +20,64 @@
...
+
+(deftest non-lato-characters-can-render-test
+  (testing "Strings containing characters that are not included in the Lato font can still be rendered."
+    (let [content                       [:span "안녕"]
+          ^BufferedImage broken-render  (render-without-wrapping content 200)
+          ^BufferedImage working-render (render-with-wrapping content 200)]
+      ;; The broken-render's width is around 17px. It is the width of 2 `[?]` charaters
+      ;; We assert that the working render is wider based on the assumption (verified manually by
+      ;; actually looking at the rendered images) that the correctly rendered glyphs are wider.
+      (is (< (.getWidth broken-render) (.getWidth working-render))))))
```
Comment (adam-james-v) [inline test/metabase/pulse/render/png_test.clj:83]: For a visual ref, here's the broken/working render:

image

File: src/metabase/pulse/render/png.clj [hunk 2]
```diff
@@ -73,16 +74,66 @@
...
+      (let [char-range (range 0x0000 0xFFFF)]
+        (filter #(let [code (int %)]
+                   (.canDisplay font code)) char-range)))))
+
+(def ^:private lato-supported-chars
+  (into #{} (map char) (get-supported-glyphs "Lato Regular")))
+
+#_
+(def ^:private non-latin-regex
+  (re-pattern "[^A-Za-z0-9!@#$%^&*()_+\\-=\\[\\]{}|;:'\",.<>?/`~\\s\\t\\n\\r]"))
```
Comment (piranha) [inline src/metabase/pulse/render/png.clj:94]: I still think this is too narrow; Lato supports cyrillic and greek chars.

Comment (piranha) [reply src/metabase/pulse/render/png.clj:94]: disregard that comment, I did not notice `#_` :)

Comment (adam-james-v) [reply src/metabase/pulse/render/png.clj:94]: It's left there as a commented out form. Perhaps I should just remove it.

**Review by sansolovyov — APPROVED** [review]
Aside from tests failing if you run only them because no fonts registered - works nicely!

File: src/metabase/pulse/render/png.clj [hunk 3]
```diff
@@ -73,16 +74,65 @@
           (.getSubimage image 0 0 content-width (.getHeight image))
           image)))))
 
+(defn- font-can-fully-render?
+  [^Font font s]
+  (neg? (.canDisplayUpTo font s)))
+
+(def ^:private get-lato
```
Comment (camsaul) [inline src/metabase/pulse/render/png.clj:81]: If you add `^{:arglists '(^java.awt.Font [])}` metadata on this then you can use `(get-lato)` directly in Java interop without having to worry about type hinting it

File: src/metabase/pulse/render/png.clj [hunk 4]
```diff
@@ -73,16 +74,65 @@
...
+                  env        (GraphicsEnvironment/getLocalGraphicsEnvironment)
+                  fonts      (.getAllFonts env)
+                  font       ^Font (some #(when (lato-names (.getName ^Font %)) %) fonts)]
+              font))]
+    (memoize get-lato*)))
+
+(defn- lato-can-render?
+  [s]
+  (let [lato (get-lato)]
+    (when lato
```
Comment (camsaul) [inline src/metabase/pulse/render/png.clj:93]: You can use `when-let` here

File: test/metabase/pulse/render/png_test.clj [hunk 5]
```diff
@@ -13,9 +20,66 @@
...
+      (#'png/render-to-png width)))
+
+(defn- render-with-wrapping
+  [content width]
+  (-> {:content     content
+       :attachments {}}
+      (png/render-html-to-png width)
+      bytes->image))
+
+(deftest wrap-non-lato-characters-test
```
Comment (camsaul) [inline test/metabase/pulse/render/png_test.clj:60]: Can you make this test `^:parallel`?

File: src/metabase/pulse/render/png.clj (hunk 3 above)
Comment (piranha) [reply src/metabase/pulse/render/png.clj:81]: Isn't it ok to put `def ^:private get-lato ^Font [...]` directly? `:arglists` are more for varargs thingie I guess and it could be simpler here?
