### PR TITLE
Fix archived items tooltip that's missing the item type

### LINKED ISSUE #33969: Archived items tooltip doesn't show the item type
Archived items are using non-existing `type` prop which results in slightly decreased UX.

For example, it says "Delete this" instead of "Delete this quesiton/dashboard"
image

while the code suggests that the tooltip should have the full description of what it tries to act on
```js
{isAdmin && (onUnarchive || onDelete) && (
  <span className="ml-auto mr2">
    {onUnarchive && (
      <Tooltip tooltip={t`Unarchive this ${type}`}>
        <ActionIcon
          onClick={onUnarchive}
          className="hover-child"
          name="unarchive"
        />
      </Tooltip>
    )}
    {onDelete && (
      <Tooltip tooltip={t`Delete this ${type}`}>
        <ActionIcon
          onClick={onDelete}
          className="hover-child"
          name="trash"
        />
      </Tooltip>
    )}
  </span>
)}
```

### PR DESCRIPTION
**Pull request by nemanjaglumac**
The `type` prop doesn't exist in the list of items. `models` on the other hand exists and it shows the underlying item model, which almost 1:1 matches the desired type.

We call questions "card" in the code, and models "dataset". @alxnddr pointed me to the `getTranslatedEntityName` that will take care of that, and that's what I used.

I had to move the helper out of the `nav` folder and into the `common/utils`.
Unrelated file diffs are simply updated imports.

Resolves #33969

**Before:**
image

**After**
image
image

### CODE REVIEW

File: frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ export const ArchivedItem = ({
     {isAdmin && (onUnarchive || onDelete) && (
       <span className="ml-auto mr2">
         {onUnarchive && (
-          <Tooltip tooltip={t`Unarchive this ${type}`}>
+          <Tooltip tooltip={t`Unarchive this ${model}`}>
```
Comment (nemanjaglumac) [inline frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx:59]: The underlying model reveals the item as we call it in the code, but we want its colloquially used name instead.

E.g.
`model` instead of `dataset`
`question` instead of `card`

image

image

@alxnddr where would be a good place to apply this logic? Should I create a helper that takes in `model` and spits out the `type` before I use it in the tooltip?

Also, if we have a fairly limited set of item types we can archive, does it make sense to narrow down the types for `model` from `string` to a union type of specific strings?

Comment (alxnddr) [reply frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx]: We should keep it translated so let's use `getTranslatedEntityName` from `frontend/src/metabase/nav/utils/model-names.ts` which should be moved out of `nav` module in this case. Limiting model types would be great too. We need to define a union type in the `metabase-types/api` and use it instead of strings in related API types. Then we can use it in `frontend/src/metabase/nav/utils/model-names.ts`

Comment (alxnddr) [reply frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx]: Let me know if you want to handle it by yourself or you need any help!

Comment (nemanjaglumac) [reply frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx]: I realized there is a `CollectionItemModel` type and have used it in https://github.com/metabase/metabase/pull/33970/commits/28c6e38576f20c729f42e09a6e617c129021f01a.

Would that be enough or would you rather narrow it down even further?
I have to double check what can be archived.

Let me learn a bit more about `getTranslatedEntityName`. Thanks for the hint.

Comment (alxnddr) [reply frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx]: Nice, we already have `CollectionItemModel` so you can use it in `frontend/src/metabase/nav/utils/model-names.ts`. I would not narrow down it any further

File: frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx [hunk 2]
```diff
@@ -65,7 +70,7 @@ export const ArchivedItem = ({
           </Tooltip>
         )}
         {onDelete && (
-          <Tooltip tooltip={t`Delete this ${type}`}>
+          <Tooltip tooltip={t`Delete this ${getTranslatedEntityName(model)}`}>
```
Comment (nemanjaglumac) [inline frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx:73]: @alxnddr thanks for the tip about the `getTranslatedEntityName` helper. I didn't even know we have it.

Just a final nit - do you mind if I lowercase the output?
It currently looks like this:
image

Comment (alxnddr) [reply frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx:73]: Yep, you can lowercase the translated string

**Review by alxnddr — COMMENTED** [review]
Can you please add tests for this change?

File: frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx [hunk 3]
```diff
@@ -65,7 +72,11 @@ export const ArchivedItem = ({
           </Tooltip>
         )}
         {onDelete && (
-          <Tooltip tooltip={t`Delete this ${type}`}>
+          <Tooltip
+            tooltip={t`Delete this ${getTranslatedEntityName(
+              model,
+            )?.toLowerCase()}`}
```
Comment (nemanjaglumac) [inline frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx:78]: TypeScript complained if I didn't use the optional chain here, because a `model` can be `null`.

**Review by alxnddr — APPROVED** [review]
