### PR TITLE
Track query analysis failures in an in-memory map

### LINKED ISSUE #45471: Use in-memory failure map to avoid endless retries
Add a map of `{card-id retries-remaining}` in an atom.

- In the Analyzer
  - Update with `(fnil dec max-retries)` when there's an exception analyzing a card. 
  - Dissoc this entry when we successfully parse a card.
- In the Sweeper
  - Skip enqueuing these records if there's a zero entry.
  It's OK for the reducible select to fetch them as that's cheaper than sending a potentially massive exclusion list in the query.

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes https://github.com/metabase/metabase/issues/45471

### Description

In the future, we will track a record summarizing the result of the last analysis attempt, which can include a running count of failures encountered.

Until then, we want some protection against runaway retries.

This does so with the aid of a bounded in-memory map.

### CODE REVIEW

File: src/metabase/query_analysis/failure_map.clj [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+  "Used by tests"
+  []
+  (.clear cached-failures))
+
+(defn track-failure!
+  "Record when we have failed to analyze a given version of a card, to prevent endless retrying."
+  [card]
+  ;; This size operation is close to constant time at the moment - watch out if you change the data structure.
+  (.compute cached-failures (:id card)
+            (reify BiFunction
```
Comment (crisptrutski) [inline src/metabase/query_analysis/failure_map.clj:27]: Once we update to Clojure 1.12 we can just use a Clojure map and avoid this ugliness.

File: .clj-kondo/config.edn [hunk 2]
```diff
@@ -204,7 +204,8 @@
                                      metabase.pulse.render.js-svg
                                      metabase.pulse.render.style}                                   ; TODO -- consolidate these into a real API namespace.
     metabase.query-processor       :any                                                             ; TODO omg scream, 29 namespaces used outside of the module. WHAT THE HECC
-    metabase.query-analysis        #{metabase.query-analysis}
+    metabase.query-analysis        #{metabase.query-analysis
+                                     metabase.query-analysis.failure-map}
```
Comment (crisptrutski) [inline .clj-kondo/config.edn:208]: Really we should be putting the analyzer code into this module instead, but ergh I'm a bit tired of reorganizing things for now.

File: test/metabase/query_analysis/failure_map_test.clj [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+(def id-generator (atom 0))
+
+(defn- random-card []
+  {:id (swap! id-generator inc) :dataset_query (rand)})
+
+(def ^:private max-retries @#'failure-map/max-retries)
+(def ^:private max-size @#'failure-map/max-size)
+
+(deftest failure-map-non-retryable-test
+  (failure-map/reset-map!)
```
Comment (crisptrutski) [inline test/metabase/query_analysis/failure_map_test.clj:15]: We should probably use fixtures instead, but this seems fine for now.

Comment (crisptrutski) [reply test/metabase/query_analysis/failure_map_test.clj:15]: As it stands neither test leaks, part of me wants to just assert that in a post-test hook.

**Review by tsmacdonald — APPROVED** [review]
Looks reasonable to me
