### PR TITLE
Test question that is archived because the collection it is in has been archived

### LINKED ISSUE #23649: Add e2e test: archived question page should be shown correctly when its collection was archived
We have had a temporary regression: https://github.com/metabase/metabase/issues/23501

To prevent recurrence, please write a test.

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #23649 

Outcome of investigating issue https://github.com/metabase/metabase/issues/23501

If possible, please review https://github.com/metabase/metabase/issues/23647 before this one. This is an iteration.

### CODE REVIEW

File: frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js [hunk 1]
```diff
@@ -132,6 +132,17 @@ export function visitQuestion(id) {
...
+ * Visit an archived question.
+ *
+ * @param {number} id
+ */
+export function visitArchivedQuestion(id) {
+  cy.visit(`/question/${id}`);
+
+  cy.findByText("This question has been archived");
+}
+
```
Comment (nemanjaglumac) [inline frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js:145]: Let's, **please** avoid creating global helpers for something that's going to be used in just a couple of tests.

Side note, there is already a helper called `visitQuestion(:id)` that "intelligently" waits for the necessary queries to finish loading. Use that rather than `cy.visit(/question/${id});`

Comment (gusaiani) [reply frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js:145]: Thanks @nemanjaglumac 

Thing with `visitQuestion` for this test is that it waits for something to load that will not be loaded in an archived question's page.

We will have 2 uses of this check for an archived question's page.
If you prefer not to have a dedicated function doing it, no problem, I'll inline the code in each test.

Comment (nemanjaglumac) [reply frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js:145]: Oh, right.
That is an excellent opportunity and a reminder for me to add that logic to that helper.

**Review by nemanjaglumac — APPROVED** [review]
