### PR TITLE
[serdes] NativeQuerySnippet collection_id should not prevent export

### LINKED ISSUE #51901: Error during deserialization: Failed to read file for NativeQuerySnippet
### Describe the bug

Native query snippets do not seem be exported when exporting a collection using the Metabase CLI, which leads to `Failed to read file for NativeQuerySnippet` on a subsequent import. 

We're exporting as follows: `metabase.jar export export --full-stacktrace --collection 2 --no-settings --no-data-model`

### To Reproduce

Export a collection containing questions that reference native SQL snippets.

### Expected behavior

Snippets should be exported.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2024-12-23",
      "tag": "v1.51.10",
      "hash": "e9d96ac"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "5.10.230-223.885.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

Blocks our use of snippets

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sansolovyov**
Previously `extract-query "NativeQuerySnippet"` would use standard method for exporting entities, which checks for collection_id in entity and prevents its export if it's outside requested collections.

While that makes sense for Cards (and we do escape analysis for those), snippets live in their own separate collection namespace and this logic is not relevant to them. So now we export either those in requested collections _or_ dependencies of cards that are being exported.

Closes #51901

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj [hunk 1]
```diff
@@ -69,43 +69,44 @@
       (format "%d: %s" coll-id names))
     "[no collection]"))
 
-(defn- card-label [card-id]
-  (let [card (t2/select-one [:model/Card :collection_id :name] :id card-id)]
-    (format "Card %d (%s from collection %s)" card-id (:name card) (collection-label (:collection_id card)))))
+(defn- entity-label [{:keys [model id]}]
+  (let [entity (t2/select-one [model :collection_id :name] :id id)]
+    (format "%s %d (%s from collection %s)" (name model) id (:name entity) (collection-label (:collection_id entity)))))
```
Comment (sansolovyov) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:77]: I rewrote escape-analysis to check both cards and snippets first (before understanding what should be the adequate behavior) - and while that turned out to be unnecessary I'd rather keep a more generic version of functions here.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj [hunk 2]
```diff
@@ -26,9 +28,12 @@
     (apply io/file (:root-dir ctx) (map escape-segment (concat dirnames [basename])))))
 
 (defn- store-entity! [opts entity]
-  (log/info "Storing" {:path (serdes/log-path-str (:serdes/meta entity))})
-  (spit-yaml! (file opts entity) entity)
-  (:serdes/meta entity))
+  (let [f (file opts entity)]
+    (log/info "Storing" {:path (serdes/log-path-str (:serdes/meta entity))
+                         :file (str (.relativize (Path/of (:root-dir opts) (make-array String 0))
+                                                 (.toPath f)))})
```
Comment (sansolovyov) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj:34]: Realized that I would love to see real file path in logs :-)

File: src/metabase/native_query_snippets/models/native_query_snippet.clj [hunk 3]
```diff
@@ -110,8 +111,15 @@
...
-  (serdes/extract-query-collections :model/NativeQuerySnippet opts))
+(defmethod serdes/extract-query "NativeQuerySnippet" [_ {:keys [collection-set where]}]
+  ;; NativeQuerySnippets leave in their own special collections, so the logic is the following:
+  ;; - you either are exporting one of those
+  ;; - or it was requested as a dependency of some Card, so export it regardless of collection
+  (t2/reducible-select :model/NativeQuerySnippet (cond-> {:where [:or
+                                                                  [:in :collection_id (remove nil? collection-set)]
+                                                                  (when (some nil? collection-set)
+                                                                    [:= :collection_id nil])]}
+                                                   where (sql.helpers/where :or where))))
```
Comment (sansolovyov) [inline src/metabase/native_query_snippets/models/native_query_snippet.clj:122]: Actual logic change — generates `:or` for top-level here instead of `:and` in default `extract-query-collections`.

File: src/metabase/models/serialization.clj [hunk 4]
```diff
@@ -562,7 +560,7 @@
       (t2/reducible-select model {:where (or where true)})
       (t2/reducible-select model {:where [:and
                                           [:or
-                                           [:in :collection_id collection-set]
+                                           [:in :collection_id (remove nil? collection-set)]
```
Comment (bshepherdson) [inline src/metabase/models/serialization.clj]: If the `collection-set` is ever empty or contains only nils, this will cause a SQL syntax error for `x IN ()`.

Are we certain it always contains some non-nil values in this context?

**Review by bshepherdson — APPROVED** [review]
I want to be clear: we shouldn't fail an export's escape analysis because of snippet collections, but we do still need to export the snippet collections! It's not obvious from this PR that the snippet collections are being properly exported.

If they are, then LGTM.

File: src/metabase/models/serialization.clj (hunk 4 above)
Comment (sansolovyov) [reply src/metabase/models/serialization.clj]: We're kind of on the fence about it 🤣 I'll improve the logic, thanks for noticing. Or maybe I should just remove that "improvement" I've added. 😁

**Comment by sansolovyov** [comment]
Yeah snippets collections are being exported with no problems, we have a test case for that (in the same test where I've added a new one).

EDIT: actually, I'm wrong, snippets collections are not exported, fixing this...

File: enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj [hunk 5]
```diff
@@ -72,43 +72,57 @@
...
+  [targets user-id]
+  (let [initial-targets (if (seq targets)
+                          (mapv parse-target targets)
+                          (mapv vector (repeat "Collection") (collection-set-for-user user-id)))
+        ;; a map of `{[model-name id] {source-model source-id ...}}`
+        targets         (u/traverse initial-targets #(serdes/descendants (first %) (second %)))]
+    ;; due to traverse argument we'd lose original source entities, lets track them
+    (merge-with into
+                targets
+                (u/traverse (map key targets) #(serdes/required (first %) (second %))))))
```
Comment (sansolovyov) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:125]: second part of the change - `serdes/required` is called on every target (including those we got via "descending" the graph) to get all necessary entities.

**Review by bshepherdson — APPROVED** [review]
