### PR TITLE
Filter out the is_saved_questions db in the db reference view

### LINKED ISSUE #18331: Data reference lists "Saved Questions" as a database
**Describe the bug**
Data reference lists "Saved Questions" as a database

**Logs**
N/A

**To Reproduce**
_Start with having some questions already saved_
1. Go to `/reference/databases`
2. Note that there is a "Sample Dataset", but also "Saved Questions"
image
3. Click on "Saved Questions"
image
4. You can click on the "Edit" but none of the metadata you enter cannot be saved/preserved
5. "Tables in Saved Questions" is pointless and (obviously) leads to am

**Expected behavior**
"Saved Questions" shouldn't be displayed as a database in the data reference.

**Screenshots**

**Information about your Metabase Installation:**
local dev, `master`, H2, Sample Dataset

**Severity**
P3

**Additional context**
Tested as back as 37.9 and it was still there.

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #18331 

**Testing**
- Follow steps in #18331 
- Sometimes the "Saved Questions" option doesn't appear; you may want to navigate to the "New question" page before navigating to the DB reference page to guarantee all data is hydrated in the client.

Before
Screen Shot 2022-04-20 at 5 01 56 PM

After
Screen Shot 2022-04-20 at 5 01 38 PM

### CODE REVIEW

File: frontend/src/metabase/reference/databases/DatabaseList.jsx [hunk 1]
```diff
@@ -40,6 +40,16 @@ export default class DatabaseList extends Component {
...
+    const databases = Object.values(entities)
+      .filter(database => {
+        const exists = Boolean(database?.id && database?.name);
+        return exists && !database.is_saved_questions;
+      })
+      .sort((a, b) => {
+        const compared = a.name.localeCompare(b.name);
+        return compared !== 0 ? compared : a.engine.localeCompare(b.engine);
+      });
+
```
Comment (kulyk) [inline frontend/src/metabase/reference/databases/DatabaseList.jsx:52]: Should we maybe move this entire logic to a selector? Can be a good opportunity to rename `entities` to `databases` here too

**Review by kulyk — APPROVED** [review]

**Review by ariya — APPROVED** [review]

File: frontend/src/metabase/reference/databases/DatabaseList.jsx (hunk 1 above)
Comment (daltojohnso) [reply frontend/src/metabase/reference/databases/DatabaseList.jsx:52]: Good idea; I'll do in a separate PR (clicked the merge button before I saw this comment 🙂 )

**Comment by flamber** [comment]
@daltojohnso ^^^ can you create a manual backport on 43?

**Comment by daltojohnso** [comment]
This depends on changes in https://github.com/metabase/metabase/pull/21821 so once that lands there will no longer be a conflict
