### PR TITLE
Don't use the deprecated enable-query-caching value

### LINKED ISSUE #68398: If you explicitly disabled query caching in the past, you can't re-enable it again
### Describe the bug

Seems that after https://github.com/metabase/metabase/pull/44263, if you had an explicit false in the enable-query-caching flag in the app db, there's no way to set it to "true" now, disabling query caching

### To Reproduce

1) just start metabase and then go to the app db and set enable-query-caching to false (as if you were in an old version and setting the toggle to false)
2) then set the cache durations to anything you want (as if you wanted to enable query caching). This won't cause any effect

### Expected behavior

Query caching should be enabled, if there's a caching at the root/db/question level

### Logs

NA

### Information about your Metabase installation

```JSON
v57.x, but this happens after https://github.com/metabase/metabase/pull/44263
```

### Severity

P2

### Additional context

NA

### PR DESCRIPTION
**Pull request by nvoxland**
closes #68398
### Description

If you explicitly disabled the cache in the the past using the old `enable-query-caching` setting, that value still overrides other cache settings even though you can no longer set it through the UI.

This further removes the usage of the enable-query-caching setting by making the value be computed based on whether there are cache configurations defined and disabling the setter.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: src/metabase/cache/settings.clj [hunk 1]
```diff
@@ -2,14 +2,17 @@
...
+   [toucan2.core :as t2]))
 
 (defsetting enable-query-caching
   (deferred-tru "Allow caching results of queries that take a long time to run.")
   :type       :boolean
   :default    true
   :visibility :authenticated
-  :audit      :getter)
+  :audit      :getter
+  :getter     #(t2/exists? :model/CacheConfig)
```
Comment (edpaget) [inline src/metabase/cache/settings.clj:14]: How does this interact with the settings cache? Could it get stale unless we bust the cache on changes to CacheConfig?

**Review by edpaget — COMMENTED** [review]
Just want to clarify the one comment first but otherwise lgtm

File: src/metabase/cache/settings.clj (hunk 1 above)
Comment (nvoxland) [reply src/metabase/cache/settings.clj:14]: The settings cache is in the default getter, so with our custom getter it's not using the cache at all.

I thought about trying to hook it in, but it seemed to open up too many questions and edge cases around busting the config to be safe

**Review by edpaget — APPROVED** [review]
