### PR TITLE
Remove extra decimals in small x-axis scales

### LINKED ISSUE #15188: Zero showing as -0.0000...89 in chart x-axis
**Describe the bug**
In a x-axis label for a bar, line, and scatter chart, instead of 0 it's displaying -0.0000000000000000089

**Logs**
The only possibly relevant javascript console error is:

```
vendor.bundle.js?fc344f13f5994a3b4142:130 [re-reselect] Invalid cache key "undefined" has been returned by keySelector function.
```
Although that happens before the data is even loaded (via POST /api/dataset) so I highly doubt it's relevant.

**To Reproduce**
1. Create SQL question in sample database with the following SQL:
```sql
select 0 AS delay, 35 as "count(*)"
union all
select 1 AS delay, 10 as "count(*)"
```
2. Convert to a bar chart, with DELAY as the x axis and count(*) as the y axis

**Expected behavior**
The data legend and x-axis should both show the value as 0. The data legend popover is correct, but the x-axis is doing some funky floating point thing.

**Screenshots**
image

This is clearly a client-side thing - the server is returning the values as `[[0,35],[1,10]]`

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-b08",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.15.2.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.4.13-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.0",
      "date": "2021-02-16",
      "branch": "release-x.38.x",
      "hash": "471aa51"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```
We're running metabase in docker with a custom-built docker image.

**Severity**
Annoying

### PR DESCRIPTION
**Pull request by iethree**
## Before

- For low-value x-axis scales, we got tons of funny looking decimal places instead of a nice round 0 on our graphs' linear x-axes

Screenshot from 2022-03-25 13-21-39

bar chart | line chart
--- | ---
Screenshot from 2022-03-25 13-18-58 | Screenshot from 2022-03-25 13-18-46

## Changes
- for small numbers, we were hitting a floating-point precision issue when adding padding to our chart axes
- added some rounding to our x-axis padding
- Resolves #15188 

## After

- no extra digits on graphs with low-value x axes

bar chart | line chart
--- | ---
Screenshot from 2022-03-25 13-16-05 | Screenshot from 2022-03-25 13-17-47

- other graphs continue to function properly, and have an appropriate amount of x-padding

Screenshot from 2022-03-25 13-14-28

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/apply_axis.js [hunk 1]
```diff
@@ -285,7 +285,8 @@ export function applyChartQuantitativeXAxis(
   }
 
   // pad the domain slightly to prevent clipping
-  xDomain = [xDomain[0] - xInterval * 0.75, xDomain[1] + xInterval * 0.75];
+  const pad = Math.round(xInterval * 0.75 * 10) / 10;
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/lib/apply_axis.js:288]: @iethree works nice! I'm wondering why not simply `const pad = Math.round(xInterval * 0.75);`

Comment (iethree) [reply frontend/src/metabase/visualizations/lib/apply_axis.js:288]: Good question! I wanted to preserve a bit more precision than nearest whole number. If we're looking at numbers less than 1, rounding to a whole number would round the pad to 0, giving us graphs that overlap the vertical axes like this:

Screenshot from 2022-03-28 15-25-07

Which is exactly what this padding is trying to eliminate

Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/apply_axis.js:288]: Good, thanks for your clarification!

**Review by alxnddr — APPROVED** [review]
