### PR TITLE
record group membership removals in activity log

### LINKED ISSUE #66905: Group membership removal from custom groups is not recorded in activity log
### Describe the bug

When a user is removed from a group, an event like this is created in the [activity log](https://www.metabase.com/docs/latest/usage-and-performance-tools/usage-analytics#activity-log-model):

Image

When a user is removed from a custom group, no activity log entry is created.

Note that this only happens for custom groups. Removing a user's admin permissions does create a log entry as expected.

https://github.com/user-attachments/assets/0c472dc5-87d7-4929-a48a-4f249bde784c

### To Reproduce

1. Add a user to a custom group
2. Observe in the activity log that a `group-membership-create` topic entry is created
3. Remove the user from the group
4. No `group-membership-delete` entry is created

### Expected behavior

Create activity log entries when a user is removed from a custom group.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:145.0) Gecko/20100101 Firefox/145.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-12-10",
      "tag": "v1.57.5.8",
      "hash": "b88ce88"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Can cause false alarms during permission audits

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by johnswanson**
closes #66905
Previously the `PUT /api/membership/:group-id/clear` and `DELETE /api/membership/:id` endpoints did not emit group membership deletion events.

In the long run it would be better if `t2` were the interface for PermissionsGroupMembership, so users didn't need to call these "blessed" functions. But for now, let's go along with the existing pattern here, have some blessed functions for doing things, and throw exceptions if someone does a direct `t2/delete!` on a `:model/PermissionsGroupMembership`.

Fixes [UXW-2564: Group membership removal from custom groups is not recorded in activity log](https://linear.app/metabase/issue/UXW-2564/group-membership-removal-from-custom-groups-is-not-recorded-in)

### CODE REVIEW

File: test/metabase/warehouses/models/database_test.clj [hunk 1]
```diff
@@ -815,7 +815,8 @@
         (data-perms/set-database-permission! pg1 db3-id :perms/view-data :blocked)
         (data-perms/set-database-permission! pg2 db3-id :perms/view-data :blocked)
         ;; Remove user from groups we added (avoid touching All Users group)
-        (t2/delete! :model/PermissionsGroupMembership
+        ;; Use raw table name to bypass before-delete guard (test cleanup, not a real user action)
+        (t2/delete! (t2/table-name :model/PermissionsGroupMembership)
```
Comment (edpaget) [inline test/metabase/warehouses/models/database_test.clj]: should we use the macro to bind the dynamic var instead?

**Review by edpaget — APPROVED** [review]

File: test/metabase/warehouses/models/database_test.clj (hunk 1 above)
Comment (johnswanson) [reply test/metabase/warehouses/models/database_test.clj]: Good call, done

**Comment by rolodato** [comment]
@johnswanson Could we please do a backport to 58 as well? It'll be quite some time until 59 is released and customers can upgrade to it.
