### PR TITLE
unstemmed words should still appear in search

### LINKED ISSUE #60649: Parital-word search results sometimes don't show expected results
### Describe the bug

As you type out the word "Organization" in the search bar, it finds matches through "Organ" but once you get to "Organi" it no longer matches.

It will show again once you get to "Organization"

### To Reproduce

1. Type "Organi" in the search bar
2. Expect a match on "Organization" but get nothing

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
Running master
```

### Severity

Surprising behavior

### Additional context

Internal report: https://metaboat.slack.com/archives/CKZEMT1MJ/p1751555358540149

### PR DESCRIPTION
**Pull request by sansolovyov**
This is done by putting them in the full-text index using a 'simple' stemmer, just with a lower priority than a normal stemmed words are.

Fixes #60649

### CODE REVIEW

File: test/metabase/search/appdb/scoring_test.clj [hunk 1]
```diff
@@ -101,11 +101,11 @@
           ;; Note that, ceteris paribus, the ordering in the database is currently stable - this might change!
           ;; Due to stemming, we do not distinguish between exact matches and those that differ slightly.
         (is (= [["card" 1 "orders"]
-                ["card" 4 "order"]
-                  ;; We do not currently normalize the score based on the number of words in the vector / the coverage.
+                ;; We do not currently normalize the score based on the number of words in the vector / the coverage.
                 ["card" 5 "orders, invoices, other stuff"]
                 ["card" 6 "ordering"]
-                  ;; If the match is only in a secondary field, it is less preferred.
+                ["card" 4 "order"]
```
Comment (crisptrutski) [inline test/metabase/search/appdb/scoring_test.clj]: It looks like exact matches get their scores implicitly boosted now?

Strictly speaking we should then adjust the weights to account for the double counting, but I guess they weren't set too precisely before this.

File: test/metabase/search/appdb/index_test.clj [hunk 2]
```diff
@@ -151,6 +152,9 @@
       (is (= #_2 3 (index-hits "projected")))
       (is (= 2 (index-hits "revenue")))
       (is (= #_1 2 (index-hits "projected revenue")))
+      (testing "Simple dictionary allows searching for unstemmed words #60649"
+        (is (= 1 (index-hits "organ")))
+        (is (= 1 (index-hits "organi"))))
```
Comment (crisptrutski) [inline test/metabase/search/appdb/index_test.clj]: Is this test case running for the non-simple configuration scenario too?

**Comment by crisptrutski** [comment]
Mentioned this in DM, but you don't seem to be testing the desired case, and I don't think it will work anyway.

This change will store the unstemmed word in the vector, but when we search we'll still search using the stemmed version, right?

File: test/metabase/search/appdb/scoring_test.clj (hunk 1 above)
Comment (crisptrutski) [reply test/metabase/search/appdb/scoring_test.clj]: Fixed 😎

File: test/metabase/search/appdb/index_test.clj (hunk 2 above)
Comment (crisptrutski) [reply test/metabase/search/appdb/index_test.clj]: Yes (but now we also force it, to be certain)

File: src/metabase/search/appdb/specialization/postgres.clj [hunk 3]
```diff
@@ -73,9 +79,12 @@
 ;; 32 divides the rank by itself + 1
 (def ^:private ts-rank-normalization 0)
 
+;; The order here is {D, C, B, A} - but just see the link to docs up there ^
+(def ^:private ts-rank-weights "{0, 0.2, 0.4, 1.0}")
```
Comment (crisptrutski) [inline src/metabase/search/appdb/specialization/postgres.clj:86]: We should explain what we're using each letter for semantically, and why D is zero.

**Review by crisptrutski — APPROVED** [review]
