### PR TITLE
[E2E] Remove the `default-ee` spec

### LINKED ISSUE #47095: E2E Sandboxing Test Fixes/Improvements
Some sandboxing E2E tests are giving us false positives. There's two major issues that led to this being possible:
- E2E sandboxing setup was broken during the split permissions migration that happened from v49 -> v50
- Assertions in our sandbox tests aren't strict enough and generally make no assertions that the underlying data is actually sandboxed.

For a more eloquent explanation and history of this problem, read @nemanjaglumac's message here:
https://metaboat.slack.com/archives/C505ZNNH4/p1724187422396359

```[tasklist]
### Tasks
- [x] add assertions that tests are working with sandboxed data (test for `is_sandboxed` on results data, add assertions that certain data should not be visible, and add assertions that results are limited)
- [x] add helpers for modifying the default group's permissions to allow for setting up sandboxing using `default` snapshot + port tests to new utils
- [x] remove the` default-ee` snapshot
```

### PR DESCRIPTION
**Pull request by sloansparger**
Closes #47095

### Description

Improvements based on these internal slack threads: https://metaboat.slack.com/archives/C505ZNNH4/p1722611219985539
https://metaboat.slack.com/archives/C505ZNNH4/p1724187422396359

Removes the `default-ee` snapshot in favor of a util that restricts all of a groups permissions. Full reason in threads. The hope is for folks to make better assertions using the helpers utilized in  #46465 to assert that permissions have been set up correctly and that the data under test is in fact sandboxed.

### How to verify

- Remove calls to `blockUserGroupPermissions` and see that the tests fail 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by rafpaf — APPROVED** [review]

File: e2e/support/helpers/e2e-permissions-helpers.js [hunk 1]
```diff
@@ -161,3 +162,17 @@ export function assertDatasetReqIsSandboxed(
     }
   });
 }
+
+export function blockUserGroupPermissions(
+  groupName,
```
Comment (nemanjaglumac) [inline e2e/support/helpers/e2e-permissions-helpers.js:167]: Nit (semantics): this is actually a group ID, not a name.

**Review by nemanjaglumac — APPROVED** [review]
Left an inline comment.

But otherwise, this is sooooo much better and cleaner!
Thank you
