### PR TITLE
Fix inconsistent header button styles

### LINKED ISSUE #53829: Editor buttons inconsistencies
### Describe the bug

Image

### To Reproduce

1. New > Question > Orders > Visualize
2. Hover "Editor" button

❌ the background changes without transition (unlike "Summarize" or "Filter" buttons)

3. Hover "Summarize" button

❌ border-color changes (unlike 2 other buttons)

4. Click "Editor" button
5. Hover "Visualization" button 

❌ the background changes without transition (unlike "Summarize" or "Filter" buttons)

6. Hover "View SQL" button

❌ the background changes without transition (unlike "Summarize" or "Filter" buttons)

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
master, d8ed6a46df177bb8c71fb46c9a05cc0a5d453e0f
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fraserdrops**
closes #53829
Some of the header buttons were behaving differently from the others. This tidies them up

Before:
https://github.com/user-attachments/assets/9047596b-6905-460e-ae25-f170555cc901

After:
https://github.com/user-attachments/assets/6109d2c6-08ed-4221-a6d8-e8f3e3c1f97a

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/FilterHeaderButton.tsx [hunk 1]
```diff
@@ -61,6 +61,7 @@ export function FilterHeaderButton({
             leftSection={<Icon name={hasFilters ? "filter_plus" : "filter"} />}
             onClick={toggle}
             data-testid="question-filter-header"
+            data-filters-active={hasFilters}
```
Comment (npfitz) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/FilterHeaderButton.tsx]: I think we prefer adding a class conditionally vs adding data props that read in CSS

**Review by npfitz — CHANGES_REQUESTED** [review]
Just one piece of feedback, but otherwise it looks good codewise

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/FilterHeaderButton.tsx (hunk 1 above)
Comment (fraserdrops) [reply frontend/src/metabase/query_builder/components/view/ViewHeader/components/FilterHeaderButton.tsx]: I did this because that to fit in with the rest of the code here. Not sure why it was done this way. Should I just change my one back, or change all these to classes?

```js
 <Button
      color="summarize"
      variant={isShowingSummarySidebar ? "filled" : "default"}
      leftSection={<Icon name="sum" />}
      onClick={handleClick}
      data-active={isShowingSummarySidebar}
      className={cx(className, ViewTitleHeaderS.SummarizeButton)}
    >
      {t`Summarize`}
    </Button>

.SummarizeButton {
  transition:
    background 300ms linear,
    border 300ms linear;

  &:hover:not([data-active="true"]) {
    color: var(--mb-color-summarize);
    border-color: color-mix(in srgb, var(--mb-color-summarize) 40%, white);
    background-color: color-mix(in srgb, var(--mb-color-summarize) 15%, white);
  }
}


```

**Review by romnitt — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/FilterHeaderButton.tsx (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/query_builder/components/view/ViewHeader/components/FilterHeaderButton.tsx]: If it'll take 20 min then sure, but I wouldn't spend much time refactoring the existing stuff. I'm mostly concerned with the net new stuff

Comment (fraserdrops) [reply frontend/src/metabase/query_builder/components/view/ViewHeader/components/FilterHeaderButton.tsx]: I just changed the one I added

**Review by npfitz — APPROVED** [review]
