### PR TITLE
Fix 30727: Sort database tables by name in the data reference view

### LINKED ISSUE #30727: Tables in reference section are not ordered alphabetically
### Describe the bug

References Section doesn't show tables in alphabetical order:

image

### To Reproduce

1. Go to Browse Data -> Sample Database -> Learn About our Data ... this will load all the databases (which doesn't make much sense since i had already clicked the Sample Database) but notice how the Databases are alphabetically ordered

2. Go to  Browse Data -> Sample Database -> Learn About our Data ->  Sample Database -> Tables in Sample DB

image

If you go to Admin -> Data Model -> Sample Database ... You can find them ordered correctly here as well

image

### Expected behavior

All paths are consistent so Tables section in Learn About our Data should be ordered as well

### Logs

None

### Information about your Metabase installation

```JSON
1.46.2 and master
```

### Severity

 .

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nemanjaglumac**
Fixes #30727 
Reproduces #30727

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30751)

### CODE REVIEW

File: frontend/src/metabase/reference/databases/TableList.jsx [hunk 1]
```diff
@@ -100,8 +99,10 @@ class TableList extends Component {
       loading,
     } = this.props;
 
+    const tables = Object.values(entities);
```
Comment (nemanjaglumac) [inline frontend/src/metabase/reference/databases/TableList.jsx:102]: Apart from fixing the issue, this line here is the main change.
It defines tables as an array in one place and all other functions in this spec now know what to expect.

Using a mix of `Object.keys(entities)` and `Object.values(entities)` randomly was outright confusing.
Not to mention the use of `Object.values(tables)` at https://github.com/metabase/metabase/pull/30751/files#diff-3341dfa456411686e965258000bfbfce2ac7b853cd8d8d96336af0680d3bb9eeL63

🤯

File: frontend/src/metabase/reference/databases/TableList.jsx [hunk 2]
```diff
@@ -59,26 +60,24 @@ export const separateTablesBySchema = (
...
+    .sortBy(t => t.name)
+    .sortBy(t => t.schema_name)
+    .value();
+
+  return sortedTables.map((table, index, sortedTables) => {
+    if (!table || !table.id || !table.name) {
+      return;
+    }
+    // add schema header for first element and if schema is different from previous
+    const previousTableId = Object.keys(sortedTables)[index - 1];
```
Comment (ranquild) [inline frontend/src/metabase/reference/databases/TableList.jsx:74]: I know that was implemented this way but this looks complex. If I were implementing this part I'd just group by schema and add a separator if it's not the first schema. Something like this:

```
const createSchemaSeparator = schemaName => (
  <li className={R.schemaSeparator}>{schemaName}</li>
);
```

```
const tablesBySchema = _.chain(tables)
    .sortBy(t => t.name)
    .sortBy(t => t.schema_name)
    .groupBy(t => t.schema_name)
    .value();

return Object.entries(tablesBySchema).map(([schemaName, tables], index) => 
  <Fragment key={schemaName}>
   {index > 0 && createSchemaSeparator(schemaName)}
    {createListItem(table)}
  </Fragment>
);

```

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/reference/databases/TableList.jsx (hunk 2 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/reference/databases/TableList.jsx:74]: Thank you for the tip @ranquild 

I didn't want to touch that part because it wasn't a part of the actual fix. If it was any other piece of the codebase, I'd open a separate PR for it, but there's a chance `/reference`s are soon going to be removed or rewritten so I'd just leave this for now.

Comment (ranquild) [reply frontend/src/metabase/reference/databases/TableList.jsx:74]: lgtm
