### PR TITLE
fix: select dataset editor header column after reordering by the corner

### LINKED ISSUE #41419: Moving a column while editing model Metadata gets you back to the beginning of the table
### Describe the bug

Moving a column while editing model Metadata can be very frustrating. It gets you to the beginning of the table every time you move a column, and it doesn't let you drag it to the beginning as well.

### To Reproduce

1. Create a model with more than 10 columns
2. Move a column and see the error

https://github.com/metabase/metabase/assets/132273646/1f3ea101-d7f7-460a-8fae-26ad3c508fe7

### Expected behavior

Should maintain the current view and not bring you back to the beginning each time.

### Logs

_No response_

### Information about your Metabase installation

```JSON
- 49.3
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/41419

### Description

When you drag the column header by the corner, internal magic does not fire and virtual table thinks you need to select the first column to be able to use tab navigation.

### How to verify

- new model -> orders -> join products -> visualize -> visualize -> edit metadata -> scroll right -> reorder some column by the edge of the column header

### Before

https://github.com/user-attachments/assets/5f8a513a-ee98-4f36-8f58-4ab412f478b3

### After

https://github.com/user-attachments/assets/0e1ab8a7-2944-4ad0-bfa9-b1e82ec1b791

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

Screenshot 2025-03-05 at 17 08 12

### CODE REVIEW

**Review by ranquild — COMMENTED** [review]
This fix has unwanted consequences:
- Open any table
- Drag & drop columns multiple times:
Screenshot 2025-03-05 at 14 32 02

I believe we should fix DatasetEditor instead.

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx [hunk 1]
```diff
@@ -858,6 +858,11 @@ class TableInteractive extends Component {
             dragColIndex !== dragColNewIndex
           ) {
             this.onColumnReorder(dragColIndex, dragColNewIndex);
+
+            // if the column is dragged, we need to tell DatasetEditor know that
+            // this specific column needs to be marked as selected to be able to
+            // scroll to it in a virtual table
+            this.props.onHeaderColumnReorder?.(clicked.column.name);
```
Comment (uladzimirdev) [inline frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx:865]: maybe it should be a part of `onColumnReorder`? @ranquild

**Comment by uladzimirdev** [comment]
@ranquild I changed the approach, please take a look. DatasetEditor doesn't have access to the TableInteractive, we have to make changes there anyway

**Review by ranquild — COMMENTED** [review]
one comment inline. much better now

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx]: fixed 34f6fcf50041ded37aa916cd1912e8fee902ae52

**Review by ranquild — APPROVED** [review]
@uladzimirdev maybe rename `onHeaderColumnReorder` to `onColumnReorder`?
