### PR TITLE
Edit metric and model links

### LINKED ISSUE #44168: Dashcard > “…” > Edit question - it does not make sense for models and metrics, we should navigate user to edit query definition instead

### LINKED ISSUE #44211: Edit question option on dashboard card for metrics does not make sense
### Describe the bug

The context menu for metrics on a dashboard contains the option "Edit question", this does not make sense.

Screenshot 2024-06-14 at 14 06 11

### To Reproduce

1. Create a metric and add it to a dashboard
2. Visit the 
4. Click the "..." context menu on the dashboard card
5. It has the "Edit question" option

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Mac OS X",
    "os.version": "14.2.1",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2024-06-12",
      "src_hash": "7a87e1a1173927a489fc70b6fc3e9bded123a326",
      "tag": "v1.2.0-SNAPSHOT",
      "hash": "3afe482"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/44168
Closes https://github.com/metabase/metabase/issues/44211

### Description

Uses the model and metric editors when editing models and metrics, instead of the default notebook editor.

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenuItems.tsx [hunk 1]
```diff
@@ -46,13 +46,34 @@ export const DashCardMenuItems = ({
       key: string;
     })[] = [];
 
+    // console.log("HERE", question.card().type === "model");
```
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenuItems.tsx:49]: leftovers

File: e2e/test/scenarios/dashboard/dashboard.cy.spec.js [hunk 2]
```diff
@@ -402,6 +403,51 @@ describe("scenarios > dashboard", () => {
...
+            name: "Dashboard",
+          },
+        }).then(({ body: { dashboard_id, ...rest } }) => {
+          visitDashboard(dashboard_id);
+        });
+
+        showDashboardCardActions();
+        getDashboardCardMenu().click();
+        popover().findByText("Edit model").should("be.visible").click();
+        cy.location("pathname").should("match", /\/model\/.*\/query/);
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard/dashboard.cy.spec.js:426]: `createQuestionAndDashboard` will resolve with `questionId` (in `...rest`) - we can use it to exactly match the pathname

File: frontend/src/metabase/lib/urls/questions.ts [hunk 3]
```diff
@@ -77,7 +77,11 @@ export function question(
   }
 
   if (mode === "notebook") {
-    path = `${path}/notebook`;
+    if (card.type === "model" || card.type === "metric") {
```
Comment (kamilmielnik) [inline frontend/src/metabase/lib/urls/questions.ts:80]: I'm not sure if putting this condition here is a good idea.
It makes it ambiguous what `mode === "notebook"` means (it won't be possible to navigate to `/model/:id/notebook` via this function anymore). I don't have a counterexample where we wouldn't want this to happen though.

Still, I think it'd be better to introduce a new `mode` to make it unambiguous.

File: frontend/src/metabase/lib/urls/questions.ts [hunk 4]
```diff
@@ -15,7 +15,7 @@ type Card = Partial<SavedCard> & {
 };
 
 export type QuestionUrlBuilderParams = {
-  mode?: "view" | "notebook";
+  mode?: "view" | "notebook" | "editor";
```
Comment (kamilmielnik) [inline frontend/src/metabase/lib/urls/questions.ts:18]: `"editor"` could mean query editor (`/query`) or metadata editor (`/metadata`).

How about `"query"` or `"query-editor"` instead?

File: frontend/src/metabase/dashboard/actions/navigation.js [hunk 5]
```diff
@@ -11,15 +11,16 @@ import { getNewCardUrl } from "./getNewCardUrl";
 export const EDIT_QUESTION = "metabase/dashboard/EDIT_QUESTION";
 export const editQuestion = createThunkAction(
   EDIT_QUESTION,
-  question => (dispatch, getState) => {
-    const dashboardId = getDashboardId(getState());
-    const { isNative } = Lib.queryDisplayInfo(question.query());
-    const mode = isNative ? "view" : "notebook";
-    const url = Urls.question(question.card(), { mode });
+  (question, as = "notebook") =>
```
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/actions/navigation.js:14]: I think `as` should be called `mode`.
We can rename the current `mode` to `finalMode` or `effectiveMode`, etc.

**Review by kamilmielnik — APPROVED** [review]
Looks good :+1: 

I left some naming suggestions.
