### PR TITLE
Fix scrollbar interaction in the custom expression suggestion list

### LINKED ISSUE #41165: Cannot interact with the scrollbar in the suggestions list
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/2304f6f6-7797-4dc4-ba0c-d38c3ecedb51

### To Reproduce

1. Start a new question based on the Orders table
2. Click + to add new column
3. Type `[` to show suggestions list
4. Try to press & hold the vertical scrollbar to scroll the list

Suggestions list disappears

### Expected behavior

Scrollbar is interactive

### Information about your Metabase installation

master, 1504b86572

### Severity

P2

### PR DESCRIPTION
**Pull request by hyperNURb**
Closes https://github.com/metabase/metabase/issues/41165

### Description
The underlying issue is that AceEditor has an `onBlur` event handler, triggered once the user clicks out of the `textarea` (in this case, onto the `ExpressionEditorSuggestions` scrollbar).

### How to verify
1. Start a new question based on the Orders table
2. Click + to add a new column
3. Type [ to show suggestions list
4. Try to press & hold the vertical scrollbar to scroll the list
5. Expression Suggestions should be scrollable and remain visible 

### Demo

https://github.com/metabase/metabase/assets/59742/fe37c5ab-fd6c-4afa-9cba-978d4f477b9e

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR
- [x] Writing a test to verify this would be tricky. It's hard to mock, and Cypress has an issue with clicking on the scrollbar

### CODE REVIEW

**Comment by romeovs** [comment]
The code looks good and the fix works! Thanks for the contribution @hyperNURb.

@hyperNURb could you add a reproduction for this issue [here](https://github.com/metabase/metabase/blob/master/e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js)?

**Comment by nemanjaglumac** [comment]
> The code looks good and the fix works! Thanks for the contribution @hyperNURb.
> 
> @hyperNURb could you add a reproduction for this issue [here](https://github.com/metabase/metabase/blob/master/e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js)?

@romeovs I don't think we can test this using E2E tests. At least I don't know of a way to "click on a scrollbar", which is what was causing this issue. If we use Cypress' `scrollTo`, I'm not sure it will give us any confidence.

Did you have something else in mind?

p.s. All tests are green, except for the few stubborn flakes.
https://github.com/metabase/metabase/pull/43840

**Comment by romeovs** [comment]
@nemanjaglumac I just tried to write the test myself, and I agree, clicking the scrollbar is not really supported. In that case I think this PR is ready to merge!

**Review by romeovs — APPROVED** [review]

**Comment by kamilmielnik** [comment]
> clicking the scrollbar is not really supported

I think it can be simulated with `mousedown` + `mousemove` + `mouseup`, similarly to how we handle drag & drop or [resize handler](https://github.com/metabase/metabase/blob/ead905b105b88c9c524c034cc87eb16935e9c27f/e2e/support/helpers/e2e-dashboard-helpers.js#L240)

**Comment by nemanjaglumac** [comment]
> I think it can be simulated with `mousedown` + `mousemove` + `mouseup`, similarly to how we handle drag & drop or [resize handler](https://github.com/metabase/metabase/blob/ead905b105b88c9c524c034cc87eb16935e9c27f/e2e/support/helpers/e2e-dashboard-helpers.js#L240)

Interesting.
But I'm wondering how easy/hard would it be to target the "scrollbar" with this click.

@kamilmielnik do you feel strongly about adding this test? I.e. Do you mind merging the PR without it?
Of course, if @hyperNURb wants to give it a go - more power to him.

**Comment by kamilmielnik** [comment]
> Do you mind merging the PR without it?

We can add the test later

**Comment by hyperNURb** [comment]
@kamilmielnik @romeovs An end-to-end test feels like overkill for this use case. However, I understand why it's the simplest way to prove that the fix is working.

A unit test using React Testing Library would probably be a better fit, but I struggled mocking `ExpressionEditorTextfield`, and passing external callbacks such as `handleOnBlur` to verify that everything is being called correctly.

I propose that we merge the PR, and I'll play more with `ExpressionEditorTextfield` test and see how far it gets me.

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx [hunk 1]
```diff
@@ -446,6 +447,11 @@ class ExpressionEditorTextfield extends React.Component<
   };
 
   handleInputBlur = (e: React.FocusEvent) => {
+    // Ensure there is no active popup menu before we blur
+    if (this.popupMenuTarget?.current) {
+      return;
+    }
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx:453]: This change causes `ExpressionWidget.unit.spec.tsx` and `FilterPicker.unit.spec.tsx` tests to fail

Comment (hyperNURb) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx:453]: @kamilmielnik apologies, this is the fix - https://github.com/metabase/metabase/compare/master...hyperNURb:ivan/41165_scrollbar_suggestion_interaction?expand=1

Comment (hyperNURb) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx:453]: Should I open a followup PR?

Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx:453]: > Should I open a followup PR?

Please do, we are [reverting](https://github.com/metabase/metabase/pull/43992) the original one because it prevents us from merging things to `master`.
