### PR TITLE
Don't format non-temporal columns as datetimes in XLSX exports

### LINKED ISSUE #18729: XLSX export of "X of Y" (eg. Month of Year) is formatted as date column
**Describe the bug**
XLSX export of "X of Y" (eg. Month of Year) is formatted as date column.

Workaround: In they XLSX viewer (Excel, Numbers, Calc), disable date formatting on the column.

**To Reproduce**
1. Custom question > Sample Dataset > Products
2. Count grouped by CreatedAt:MonthOfYear and Category
image
3. Export as XLSX
image
4. Export as CSV
```
Created At,Category,Count
1,Doohickey,2
1,Gadget,7
1,Gizmo,6
1,Widget,1
2,Doohickey,4
2,Gadget,5
2,Gizmo,4
```

**Expected behavior**
Preferably return the value similar to what is shown in Metabase (this might be tricky, especially with i18n), otherwise return the numeric value without date formatting.

**Information about your Metabase Installation:**
Tested 0.40.5 thru 0.41.1 - regression since 0.41.0

**Additional context**
Lightly related to #18572 and #18219

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #18729 

The root issue was we were only checking temporal type and/or viz settings to decide whether to format something as datetime, but not looking at effective type. `month-of-year` bucketed columns have an effective type of `type/Integer` alto semantic type might be something like `type/CreationTimestamp`. The fix here is to make sure the column is actually temporal before doing the special formatting.

We probably shouldn't be looking at semantic type at all here but I didn't want to open that can of worms yet. This minor tweak is enough to fix #18729

### CODE REVIEW

File: test/metabase/query_processor/streaming/xlsx_test.clj [hunk 1]
```diff
@@ -499,3 +501,19 @@
...
       (is (= expected-poifiles-count (count (file-seq poifiles-directory)))))))
+
+(deftest dont-format-non-temporal-columns-as-temporal-columns-test
+  (testing "Don't format columns with temporal semantic type as datetime unless they're actually datetimes (#18729)"
+    (mt/dataset sample-dataset
+      (is (= [["CREATED_AT"]
+              [1.0]
+              [2.0]]
+             (xlsx-export [{:id             0
+                            #_:semantic_type  #_:type/CreationTimestamp
```
Comment (noahmoss) [inline test/metabase/query_processor/streaming/xlsx_test.clj:512]: this line should not be skipped, right?

**Review by noahmoss — APPROVED** [review]
👍 this works for displaying the `month-of-year` column in the repro as plain integers. It'd be nice if we could actually display the month names...that's what I was trying to figure out how to do when I first looked at this issue. But at least now we have parity between XLSX/CSV/JSON.

File: test/metabase/query_processor/streaming/xlsx_test.clj (hunk 1 above)
Comment (camsaul) [reply test/metabase/query_processor/streaming/xlsx_test.clj]: fixed
