### PR TITLE
Dashboard add-question sidebar is limited to showing 50 questions per collection

### LINKED ISSUE #19748: Dashboard add-question sidebar is limited to showing 50 questions per collection
**Describe the bug**
Dashboard add-question sidebar is limited to showing 50 questions per collection, which was done to prevent loading huge slow lists on large instances, but it is not obvious that Metabase is only listing the first 50 questions in the collection alphabetically.
And the search can be confusing and don't prioritize questions in the collection I'm viewing, so it can be difficult to find things #19366

It's a "regression" since 0.40, which introduced pagination on the sidebar to prevent overload on large instances.

**To Reproduce**
1. Create more than 50 questions in a collection
2. On dashboard, open the add-question sidebar and go to that collection
3. It will only show the first 50 questions (alphabetically)

**Expected behavior**
Pagination. Either manual or auto-pagination, when scrolling down.

**Information about your Metabase Installation:**
Tested 0.40.0 thru 0.41.6

**Additional context**
Likely very related to #19366

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #19748
###### Before submitting the PR, please make sure you do the following

- [x] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### Demo
https://www.loom.com/share/521332da137049cdaeb96d4b14a836dc

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionList.jsx [hunk 1]
```diff
@@ -71,6 +92,15 @@ export function QuestionList({
                 )}
               />
             ))}
+            <PaginationControls
```
Comment (alxnddr) [inline frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionList.jsx:95]: Semantically it would be better to make like that:
```<>
    <SelectList>
    ...
    </SelectList>
    <PaginationControls />
</>``` 

that's because SelectList is `ul` and `QuestionListItem` is `li` and the pagniation element does not fit in there

**Review by alxnddr — COMMENTED** [review]
@gitstart really good work here! I left one minor comment about the code. Could you please also align the elements on the right side similarly to other pagination screens?

Screenshot 2022-07-21 at 01 18 13

**Review by alxnddr — APPROVED** [review]
Thanks for your contribution!
