### PR TITLE
Remove Unsubscribe link from unsaved subscription test email for non-users

### LINKED ISSUE #43391: pulse unsubscribe does not work
### Describe the bug

Emails on dashboard subscriptions can go to users and also to email addresses not associated with a user account:
image
Here the `dan sutton` user is a user in the system, and i have added `test@test.com` as an email address not associated with a user account locally.

The dashboard sent over email to the user account includes a link to "manage your subscriptions"
image

For the non-user account, we offer an "unsubscribe" link:
image

This link points to:
http://localhost:3006/unsubscribe?hash=ef9bc8f75949969efa79791d03397efe0afd42f66bca4c65db1962ff68bb27b9cde17d33ca087deaf5b69bf0d681526c56cc3df11325e05aa42c4afde03c3ce1&email=test@test.com&pulse-id=

There are a few issues with this:
- note the lack of a pulse-id on `pulse-id=`
- the route `http://localhost:3006/unsubscribe` is not a route
- the route that anticipates doing the unsubscribe is `metabase.api.session POST "/pulse/unsubscribe"`
- i'm not sure we can use POST request from an email like that handler expects?

image

### To Reproduce

Create a dashboard, send it to your user and also some non-user email address. Check the emails.

If you need an easy way to see emails, run the following docker container:
`docker run -p 1080:1080 -p 1025:1025  maildev/maildev`

and then view it on `localhost:1080`
image

And the email settings for your local mb are simple: host is localhost and port is 1025. No username or creds required
image

### Expected behavior

The unsubscribe link should work. 

### Logs

_No response_

### Information about your Metabase installation

```JSON
tested on 1.49.6, 1.49.13, 1.50.0-RC1
```

### Severity

seemingly not that high, but we should fix this

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by stasgavrylov**
Closes https://github.com/metabase/metabase/issues/43391

Closes [WRK-80](https://linear.app/metabase/issue/WRK-80/unsubscribe-on-unsaved-pulse-doesnt-work)

### Description

This PR resolves the issue where test emails for non-users sent from unsaved subscription menu contained a broken "Unsubscribe" link, since `pulse-id` parameter for the link didn't exist at this moment yet. For such scenarios, it was decided to remove "Unsubscribe" link completely, since it's impossible to tie it to the entity.

### How to verify

1. Create a dashboard, add a question, save.
2. Click "Sharing - Subscriptions - Email it"
3. Enter an email for non-registered user which you have access to (when developing locally, start local email backend - `docker run -p 1080:1080 -p 1025:1025  maildev/maildev`)
4. Click "Send email now" without clicking "Done" to save the subscription.

### Demo
**Before**
image

**After**
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/pulse/api/pulse_test.clj [hunk 1]
```diff
@@ -991,6 +991,45 @@
                         :recipient-type nil}
                        (mt/summarize-multipart-single-email (-> channel-messages :channel/email first) #"Daily Sad Toucans")))))))))))
 
+(deftest send-test-pulse-to-non-user-test
+  (testing "POST /api/pulse/test"
```
Comment (qnkhuat) [inline test/metabase/pulse/api/pulse_test.clj:995]: we should include some testing context here. I'd put a description saying: sending test email to non user won't include unsubscribe link. and also the github issue `#43391`

**Review by qnkhuat — APPROVED** [review]
just have a suggestion for the testing context, other than that this looks good.

Nice work!

File: test/metabase/pulse/api/pulse_test.clj (hunk 1 above)
Comment (stasgavrylov) [reply test/metabase/pulse/api/pulse_test.clj:995]: Thanks! I've missed to update the description, you're absolutely correct.

Comment (qnkhuat) [reply test/metabase/pulse/api/pulse_test.clj:995]: it's always easier to debug a small test than a big one :)
