### PR TITLE
Handle long body cells in pivot table

### LINKED ISSUE #14574: Right alignment of pivot table value cells looks broken
Opening up a separate bug issue for this, which was originally reported in https://github.com/metabase/metabase/issues/14351. This seems to occur when there's more than one aggregation/metric:

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #14574

I had set the flex-basis to 0 so adjacent cells with unequal contents would grow evenly. That breaks down when the content exceeds the size of the cell since flex-shrink was also set to 0.

I also added `Ellipsified` back to body cells so we can display longer values.

### Before
image

### After
image

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx [hunk 1]
```diff
@@ -555,19 +555,18 @@ function Cell({
...
+        {
+          "text-bold": isSubtotal,
+          "cursor-pointer": onClick,
+        },
+      )}
       onClick={onClick}
     >
       <div className={cx("px1 flex align-center", { "justify-end": isBody })}>
-        {isBody ? (
-          // Ellipsified isn't really needed for body cells. Avoiding it helps performance.
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:566]: I don't think the performance hit will be too large. I removed it among a bunch of other tweaks a while back.

**Comment by mazameli** [comment]
This seems to fix the alignment issue and it does handle longer values, though elipsifying long cell values makes me somewhat nauseous. 🤢 I think it's an acceptable stop-gap for now, but I as you've already said, and which I agree with, the real solution will be to add dynamic column width calculation and the ability to manually resize column widths. Do we have issues for those follow-ons?

**Comment by paulrosenzweig** [comment]
@mazameli #14350 is for dynamic widths. IMO we should see how that feels before necessarily adding manual resizing. Since pivot table body cells will mostly be numeric, I think there's less need for manual sizing than in normal tables.

**Review by mazameli — APPROVED** [review]
