### PR TITLE
Fix row/delete action; other misc. improvements

### LINKED ISSUE #24021: [Actions] `row/delete` is broken
This only seems to be happening on our test instance -- it's working in the tests for me locally 🙀 

A request like

```json
{"type":"query","database":24,"query":{"source-table":103,"filter":["=",["field",597,null],15]}}
```

- Database 24 = Sample Database (Postgres)
- Table 103 = `products`
- Field 597 = `id`

is failing with a 500

```json
"\"sql-params\" expected vector [sql param*], found clojure.lang.MapEntry [:identifers #object[clojure.core$identity 0x5c0d6694 \"clojure.core$identity@5c0d6694\"]]"
```

<details>
<summary>Full Response</summary>

```json
{
  "via": [
    {
      "type": "java.lang.IllegalArgumentException",
      "message": "\"sql-params\" expected vector [sql param*], found clojure.lang.MapEntry [:identifers #object[clojure.core$identity 0x5c0d6694 \"clojure.core$identity@5c0d6694\"]]",
      "at": [
        "clojure.java.jdbc$query",
        "invokeStatic",
        "jdbc.clj",
        1167
      ]
    }
  ],
  "trace": [
    [
      "clojure.java.jdbc$query",
      "invokeStatic",
      "jdbc.clj",
      1167
    ],
    [
      "clojure.java.jdbc$query",
      "invoke",
      "jdbc.clj",
      1144
    ],
    [
      "metabase.driver.postgres.actions$constraint__GT_columns",
      "invokeStatic",
      "actions.clj",
      10
    ],
    [
      "metabase.driver.postgres.actions$constraint__GT_columns",
      "invoke",
      "actions.clj",
      8
    ],
    [
      "metabase.driver.postgres.actions$update_or_delete_with_fk_constraint",
      "invokeStatic",
      "actions.clj",
      36
    ],
    [
      "metabase.driver.postgres.actions$update_or_delete_with_fk_constraint",
      "invoke",
      "actions.clj",
      32
    ],
    [
      "metabase.driver.postgres.actions$fn__60793$fn__60794",
      "invoke",
      "actions.clj",
      48
    ],
    [
      "clojure.core$some",
      "invokeStatic",
      "core.clj",
      2718
    ],
    [
      "clojure.core$some",
      "invoke",
      "core.clj",
      2709
    ],
    [
      "metabase.driver.postgres.actions$fn__60793",
      "invokeStatic",
      "actions.clj",
      48
    ],
    [
      "metabase.driver.postgres.actions$fn__60793",
      "invoke",
      "actions.clj",
      46
    ],
    [
      "clojure.lang.MultiFn",
      "invoke",
      "MultiFn.java",
      239
    ],
    [
      "metabase.driver.sql_jdbc.actions$parse_error",
      "invokeStatic",
      "actions.clj",
      37
    ],
    [
      "metabase.driver.sql_jdbc.actions$parse_error",
      "invoke",
      "actions.clj",
      28
    ],
    [
      "metabase.driver.sql_jdbc.actions$fn__60618$fn__60622",
      "invoke",
      "actions.clj",
      158
    ],
    [
      "metabase.driver.sql_jdbc.actions$do_with_jdbc_transaction$fn__60604",
      "invoke",
      "actions.clj",
      113
    ],
    [
      "metabase.driver.sql_jdbc.actions$do_with_jdbc_transaction",
      "invokeStatic",
      "actions.clj",
      112
    ],
    [
      "metabase.driver.sql_jdbc.actions$do_with_jdbc_transaction",
      "invoke",
      "actions.clj",
      101
    ],
    [
      "metabase.driver.sql_jdbc.actions$fn__60618",
      "invokeStatic",
      "actions.clj",
      143
    ],
    [
      "metabase.driver.sql_jdbc.actions$fn__60618",
      "invoke",
      "actions.clj",
      131
    ],
    [
      "clojure.lang.MultiFn",
      "invoke",
      "MultiFn.java",
      244
    ],
    [
      "metabase.actions$perform_action_BANG_",
      "invokeStatic",
      "actions.clj",
      145
    ],
    [
      "metabase.actions$perform_action_BANG_",
      "invoke",
      "actions.clj",
      107
    ],
    [
      "metabase.api.action$fn__74553",
      "invokeStatic",
      "action.clj",
      21
    ],
    [
      "metabase.api.action$fn__74553",
      "invoke",
      "action.clj",
      17
    ],
    [
      "compojure.core$wrap_response$fn__28113",
      "invoke",
      "core.clj",
      160
    ],
    [
      "compojure.core$wrap_route_middleware$fn__28097",
      "invoke",
      "core.clj",
      132
    ],
    [
      "compojure.core$wrap_route_info$fn__28102",
      "invoke",
      "core.clj",
      139
    ],
    [
      "compojure.core$wrap_route_matches$fn__28106",
      "invoke",
      "core.clj",
      151
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__28106",
      "invoke",
      "core.clj",
      153
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__28106",
      "invoke",
      "core.clj",
      152
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125",
      "invoke",
      "core.clj",
      200
    ],
    [
      "metabase.actions$_PLUS_check_actions_enabled$fn__60430",
      "invoke",
      "actions.clj",
      35
    ],
    [
      "metabase.api.common$_PLUS_check_superuser$fn__29405",
      "invoke",
      "common.clj",
      358
    ],
    [
      "metabase.server.middleware.auth$enforce_authentication$fn__69720",
      "invoke",
      "auth.clj",
      14
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125",
      "invoke",
      "core.clj",
      200
    ],
    [
      "compojure.core$make_context$handler__28153",
      "invoke",
      "core.clj",
      289
    ],
    [
      "compojure.core$make_context$fn__28157",
      "invoke",
      "core.clj",
      299
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      199
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$make_context$fn__28157",
      "invoke",
      "core.clj",
      300
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      199
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$make_context$fn__28157",
      "invoke",
      "core.clj",
      300
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$make_context$fn__28157",
      "invoke",
      "core.clj",
      300
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125",
      "invoke",
      "core.clj",
      200
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      199
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$make_context$fn__28157",
      "invoke",
      "core.clj",
      300
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125",
      "invoke",
      "core.clj",
      200
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125",
      "invoke",
      "core.clj",
      200
    ],
    [
      "metabase.api.routes$fn__81113$fn__81114",
      "invoke",
      "routes.clj",
      60
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125",
      "invoke",
      "core.clj",
      200
    ],
    [
      "clojure.lang.AFn",
      "applyToHelper",
      "AFn.java",
      160
    ],
    [
      "clojure.lang.AFn",
      "applyTo",
      "AFn.java",
      144
    ],
    [
      "clojure.core$apply",
      "invokeStatic",
      "core.clj",
      667
    ],
    [
      "clojure.core$apply",
      "invoke",
      "core.clj",
      662
    ],
    [
      "metabase.server.routes$fn__81272$fn__81273",
      "doInvoke",
      "routes.clj",
      67
    ],
    [
      "clojure.lang.RestFn",
      "invoke",
      "RestFn.java",
      436
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125",
      "invoke",
      "core.clj",
      200
    ],
    [
      "compojure.core$make_context$handler__28153",
      "invoke",
      "core.clj",
      289
    ],
    [
      "compojure.core$make_context$fn__28157",
      "invoke",
      "core.clj",
      299
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__28106",
      "invoke",
      "core.clj",
      153
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__28106",
      "invoke",
      "core.clj",
      153
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$wrap_route_matches$fn__28106",
      "invoke",
      "core.clj",
      153
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      199
    ],
    [
      "compojure.core$routes$fn__28125$f__28126$respond_SINGLEQUOTE___28127",
      "invoke",
      "core.clj",
      197
    ],
    [
      "compojure.core$make_context$fn__28157",
      "invoke",
      "core.clj",
      300
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125",
      "invoke",
      "core.clj",
      200
    ],
    [
      "compojure.core$routes$fn__28125$f__28126",
      "invoke",
      "core.clj",
      198
    ],
    [
      "compojure.core$routes$fn__28125",
      "invoke",
      "core.clj",
      200
    ],
    [
      "metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77853",
      "invoke",
      "exceptions.clj",
      98
    ],
    [
      "metabase.server.middleware.exceptions$catch_api_exceptions$fn__77850",
      "invoke",
      "exceptions.clj",
      86
    ],
    [
      "metabase.server.middleware.log$log_api_call$fn__83272$fn__83273$fn__83274",
      "invoke",
      "log.clj",
      211
    ],
    [
      "metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info",
      "invokeStatic",
      "diagnostic.clj",
      15
    ],
    [
      "metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info",
      "invoke",
      "diagnostic.clj",
      9
    ],
    [
      "metabase.server.middleware.log$log_api_call$fn__83272$fn__83273",
      "invoke",
      "log.clj",
      203
    ],
    [
      "toucan.db$_do_with_call_counting",
      "invokeStatic",
      "db.clj",
      236
    ],
    [
      "toucan.db$_do_with_call_counting",
      "invoke",
      "db.clj",
      229
    ],
    [
      "metabase.server.middleware.log$log_api_call$fn__83272",
      "invoke",
      "log.clj",
      202
    ],
    [
      "metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__88861",
      "invoke",
      "browser_cookie.clj",
      38
    ],
    [
      "metabase.server.middleware.security$add_security_headers$fn__63105",
      "invoke",
      "security.clj",
      149
    ],
    [
      "metabase.server.middleware.json$wrap_json_body$fn__85921",
      "invoke",
      "json.clj",
      63
    ],
    [
      "metabase.server.middleware.json$wrap_streamed_json_response$fn__85939",
      "invoke",
      "json.clj",
      99
    ],
    [
      "metabase.server.middleware.offset_paging$handle_paging$fn__63129",
      "invoke",
      "offset_paging.clj",
      42
    ],
    [
      "ring.middleware.keyword_params$wrap_keyword_params$fn__89128",
      "invoke",
      "keyword_params.clj",
      55
    ],
    [
      "ring.middleware.params$wrap_params$fn__89147",
      "invoke",
      "params.clj",
      77
    ],
    [
      "metabase.server.middleware.misc$maybe_set_site_url$fn__35762",
      "invoke",
      "misc.clj",
      59
    ],
    [
      "metabase.server.middleware.session$reset_session_timeout$fn__47257",
      "invoke",
      "session.clj",
      377
    ],
    [
      "metabase.server.middleware.session$bind_current_user$fn__47240$fn__47241",
      "invoke",
      "session.clj",
      313
    ],
    [
      "metabase.server.middleware.session$do_with_current_user",
      "invokeStatic",
      "session.clj",
      292
    ],
    [
      "metabase.server.middleware.session$do_with_current_user",
      "invoke",
      "session.clj",
      281
    ],
    [
      "metabase.server.middleware.session$bind_current_user$fn__47240",
      "invoke",
      "session.clj",
      312
    ],
    [
      "metabase.server.middleware.session$wrap_current_user_info$fn__47222",
      "invoke",
      "session.clj",
      262
    ],
    [
      "metabase.server.middleware.session$wrap_session_id$fn__47206",
      "invoke",
      "session.clj",
      195
    ],
    [
      "metabase.server.middleware.auth$wrap_api_key$fn__69728",
      "invoke",
      "auth.clj",
      27
    ],
    [
      "ring.middleware.cookies$wrap_cookies$fn__89048",
      "invoke",
      "cookies.clj",
      216
    ],
    [
      "metabase.server.middleware.misc$add_content_type$fn__35745",
      "invoke",
      "misc.clj",
      27
    ],
    [
      "metabase.server.middleware.misc$disable_streaming_buffering$fn__35770",
      "invoke",
      "misc.clj",
      76
    ],
    [
      "ring.middleware.gzip$wrap_gzip$fn__89090",
      "invoke",
      "gzip.clj",
      86
    ],
    [
      "metabase.server.middleware.misc$bind_request$fn__35773",
      "invoke",
      "misc.clj",
      93
    ],
    [
      "metabase.server.middleware.ssl$redirect_to_https_middleware$fn__88877",
      "invoke",
      "ssl.clj",
      48
    ],
    [
      "metabase.server$async_proxy_handler$fn__83044",
      "invoke",
      "server.clj",
      73
    ],
    [
      "metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a",
      "handle",
      null,
      -1
    ],
    [
      "org.eclipse.jetty.server.handler.HandlerWrapper",
      "handle",
      "HandlerWrapper.java",
      127
    ],
    [
      "org.eclipse.jetty.server.Server",
      "handle",
      "Server.java",
      516
    ],
    [
      "org.eclipse.jetty.server.HttpChannel",
      "lambda$handle$1",
      "HttpChannel.java",
      400
    ],
    [
      "org.eclipse.jetty.server.HttpChannel",
      "dispatch",
      "HttpChannel.java",
      645
    ],
    [
      "org.eclipse.jetty.server.HttpChannel",
      "handle",
      "HttpChannel.java",
      392
    ],
    [
      "org.eclipse.jetty.server.HttpConnection",
      "onFillable",
      "HttpConnection.java",
      277
    ],
    [
      "org.eclipse.jetty.io.AbstractConnection$ReadCallback",
      "succeeded",
      "AbstractConnection.java",
      311
    ],
    [
      "org.eclipse.jetty.io.FillInterest",
      "fillable",
      "FillInterest.java",
      105
    ],
    [
      "org.eclipse.jetty.io.ChannelEndPoint$1",
      "run",
      "ChannelEndPoint.java",
      104
    ],
    [
      "org.eclipse.jetty.util.thread.strategy.EatWhatYouKill",
      "runTask",
      "EatWhatYouKill.java",
      338
    ],
    [
      "org.eclipse.jetty.util.thread.strategy.EatWhatYouKill",
      "doProduce",
      "EatWhatYouKill.java",
      315
    ],
    [
      "org.eclipse.jetty.util.thread.strategy.EatWhatYouKill",
      "tryProduce",
      "EatWhatYouKill.java",
      173
    ],
    [
      "org.eclipse.jetty.util.thread.strategy.EatWhatYouKill",
      "run",
      "EatWhatYouKill.java",
      131
    ],
    [
      "org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread",
      "run",
      "ReservedThreadExecutor.java",
      409
    ],
    [
      "org.eclipse.jetty.util.thread.QueuedThreadPool",
      "runJob",
      "QueuedThreadPool.java",
      883
    ],
    [
      "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
      "run",
      "QueuedThreadPool.java",
      1034
    ],
    [
      "java.lang.Thread",
      "run",
      null,
      -1
    ]
  ],
  "cause": "\"sql-params\" expected vector [sql param*], found clojure.lang.MapEntry [:identifers #object[clojure.core$identity 0x5c0d6694 \"clojure.core$identity@5c0d6694\"]]",
  "message": "\"sql-params\" expected vector [sql param*], found clojure.lang.MapEntry [:identifers #object[clojure.core$identity 0x5c0d6694 \"clojure.core$identity@5c0d6694\"]]"
}
```

</details>

This is failing in `psql`

```
sample-dataset=# DELETE FROM products WHERE id = 15;
ERROR:  update or delete on table "products" violates foreign key constraint "roduct_id_products_-2038959040" on table "reviews"
DETAIL:  Key (id)=(15) is still referenced from table "reviews".
```

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #24021

The root cause of this was a regression introduced in #23848 that we didn't catch because we didn't have test coverage around the Postgres error parsing code -- it was passing the parameters to `jdbc/query` in the wrong order.

Fixed and added new tests around this code.

In order to write the new tests I had to be able to trigger and FK constraint violation when deleting rows; to make this easy I introduced the new `actions.test-util/with-actions-test-data-tables` macro that makes it possible to specify which tables should be available in the actions test data. By default, we only copy the `categories` Table, for speed reasons; using this macro we can specify that we'd like to copy `categories` _and_ `venues` for example in order to test FK constraint violations.

```clj
(actions.test-util/with-actions-test-data-tables #{"venues" "categories"} 
  ...)
```

I made some other various improvements, including wrapping calls to `parse-sql-error` in a `try-catch` so future errors in parsing won't cause the entire operation to fail. I will call out other changes in comments.

### CODE REVIEW

File: src/metabase/driver/postgres/actions.clj [hunk 1]
```diff
@@ -3,52 +3,58 @@
...
+   [metabase.util :as u]
    [metabase.util.i18n :refer [tru]]))
 
-(defn- constraint->columns [conn constraint-name]
-  (->> ["select column_name from information_schema.constraint_column_usage where constraint_name = ?" constraint-name]
-       (jdbc/query conn {:identifers identity, :transaction? false})
-       (map :column_name)))
-
-(defn- violates-not-null-constraint [_conn error-message]
+(defn- maybe-parse-not-null-error [_database error-message]
```
Comment (camsaul) [inline src/metabase/driver/postgres/actions.clj:10]: I couldn't help myself and renamed these functions to better match what they actually **do**.

File: src/metabase/driver/postgres/actions.clj [hunk 2]
```diff
@@ -3,52 +3,58 @@
...
 
-(defn- violates-unique-constraint [conn error-message]
+(defn- constraint->column-names
+  "Given a constraint with `constraint-name` fetch the column names associated with that constraint."
+  [database constraint-name]
+  (let [jdbc-spec (sql-jdbc.conn/db->pooled-connection-spec (u/the-id database))
+        sql-args  ["select column_name from information_schema.constraint_column_usage where constraint_name = ?" constraint-name]]
+    (into []
+          (map :column_name)
+          (jdbc/reducible-query jdbc-spec sql-args {:identifers identity, :transaction? false}))))
```
Comment (camsaul) [inline src/metabase/driver/postgres/actions.clj:24]: `reducible-query` isn't needed here but it's slightly more memory-efficient and works nicely with `(into [] ...)` which I wanted to use here

**Review by snoe — APPROVED** [review]

File: src/metabase/driver/sql_jdbc/actions.clj [hunk 3]
```diff
@@ -14,29 +14,32 @@
...
-            [metabase.util.i18n :refer [tru]]
+            [metabase.util.i18n :refer [tru trs]]
             [toucan.db :as db])
   (:import java.sql.Connection))
 
 (defmulti parse-sql-error
   "Parses the raw error message returned after an error in the driver database occurs, and converts it into a sequence
   of maps with a :column and :message key indicating what went wrong."
-  {:arglists '([driver ^java.sql.Connection connection e]), :added "0.44.0"}
+  {:arglists '([driver database e]), :added "0.44.0"}
```
Comment (camsaul) [inline src/metabase/driver/sql_jdbc/actions.clj:24]: I tweaked `parse-sql-error` to take the original Database rather than a `java.sql.Connection`. The expectation is that someone will use `sql-jdbc.conn/db->pooled-connection-spec` to get a connection from the pool rather than using the current `Connection`. Why? because the current Connection might be inside a transaction and in an error state, which means future queries against it will fail with some sort of "transaction already aborted" error. So it's better to query this information from a separate Database connection.

File: src/metabase/driver/postgres/actions.clj [hunk 4]
```diff
@@ -3,52 +3,58 @@
   (:require
    [clojure.java.jdbc :as jdbc]
    [metabase.driver.sql-jdbc.actions :as sql-jdbc.actions]
+   [metabase.driver.sql-jdbc.connection :as sql-jdbc.conn]
+   [metabase.util :as u]
    [metabase.util.i18n :refer [tru]]))
 
-(defn- constraint->columns [conn constraint-name]
```
Comment (camsaul) [inline src/metabase/driver/postgres/actions.clj:8]: I moved this down a bit so it appears directly above the function where it's used for the first time.

File: src/metabase/driver/sql_jdbc/actions.clj [hunk 5]
```diff
@@ -14,29 +14,32 @@
...
-        (if-let [errors (and message
-                             (parse-sql-error driver conn message))]
-
-          {:errors (->> errors
+        (if-let [parsed-errors (when message
+                                 (try
+                                   (parse-sql-error driver database message)
+                                   (catch Throwable e
+                                     (log/error e (trs "Error parsing SQL error message {0}: {1}" (pr-str message) (ex-message e)))
+                                     nil)))]
```
Comment (camsaul) [inline src/metabase/driver/sql_jdbc/actions.clj:41]: Catch errors in `parse-sql-error` and log them so more errors in the future don't break the entire action. We'll still get the original unparsed error message.

File: test/metabase/api/action_test.clj [hunk 6]
```diff
@@ -238,6 +230,45 @@
...
+                       ;; TODO -- this really should be returning a 400 but we need to rework the code in
+                       ;; [[metabase.driver.sql-jdbc.actions]] a little to have that happen without changing other stuff
+                       ;; that SHOULD be returning a 404
+                       (mt/user-http-request :crowberto :post 404
+                                             "action/row/delete"
+                                             (mt/mbql-query categories {:filter [:= $id "one"]})))
+              "Delete should return the right shape")
+          (testing "no rows should have been deleted"
+            (is (= 75
+                   (categories-row-count)))))))))
```
Comment (camsaul) [inline test/metabase/api/action_test.clj:249]: This test is actually not related to this bug or the fix but I wrote it while trying to figure out what the cause of the bug was. We didn't have any other tests like it so it made sense to keep it

File: test/metabase/driver/sql_jdbc/actions_test.clj [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+          (reset! parse-sql-error-called? false)
+          ;; attempting to delete the `Pizza` category should fail because there are several rows in `venues` that have
+          ;; this `category_id` -- it's an FK constraint violation.
+          (is (schema= {:message #"Referential integrity constraint violation:.*"
+                        s/Keyword s/Any}
+                       (mt/user-http-request :crowberto :post 400
+                                             "action/row/delete"
+                                             (mt/mbql-query categories {:filter [:= $id 58]}))))
+          (testing "Make sure our impl was actually called."
+            (is @parse-sql-error-called?)))))))
```
Comment (camsaul) [inline test/metabase/driver/sql_jdbc/actions_test.clj:34]: I added this test to make sure that exceptions in `parse-sql-error` get caught and the original unparsed error is returned to prevent future regressions of the new fallback behavior

File: test/metabase/actions/test_util.clj [hunk 8]
```diff
@@ -11,20 +11,63 @@
...
+  [tables thunk]
+  ;; make sure all the table names are valid so we can catch errors/typos
+  (let [valid-table-names-set (into #{}
+                                    (map :table-name)
+                                    (:table-definitions (tx/get-dataset-definition defs/test-data)))]
+    (doseq [table-name tables]
+      (assert (contains? valid-table-names-set table-name)
+              (format "Invalid table for `with-actions-test-data-tables` %s. Valid tables: %s"
+                      (pr-str table-name)
+                      (pr-str valid-table-names-set)))))
```
Comment (camsaul) [inline test/metabase/actions/test_util.clj:28]: This sort of thing is a nice thing to have when writing test tooling. We check that the tables you pass in to `with-actions-test-data-tables` are all valid and fail if not. This makes it impossible to write a test that you think is checking things under one condition but actually isn't because you misspelled a table name. Example:

```clj
(with-actions-test-data-tables #{"categories" "venue"}
  (with-actions-test-data
    (delete-category! 58))) ; delete Pizza which should trigger an FK constraint
```

You might think you're triggering an FK constraint by using the `venues` Table, since several venues have `category_id 58`. But the `test-data` Table name is actually `venues`, not `venue`; if we didn't have this check here we'd actually be creating a database with only the `categories` table since `venue` doesn't match anything.
