### PR TITLE
Only validate map URLs that changed

### LINKED ISSUE #44353: [Custom-map] Impossible to modify or add new geojson map if one existing map is not reacheable
### Describe the bug

After a migration of metabase from a windows host to an ubuntu/docker host,
Several custom maps stop working.  With some digging, we did found that the issue is coming from docker that don't use our private dns to resolve the hostname used in the url of the geojson.
Our server is disconnected of internet, so we use a private local server to host the geojson of the map. 

Anyway, because we are not sure how to fixe this issues, we decide to use the ip address of the geojson server.

We can change one map url, but we cannot save the change. Same with adding a new map.
In the log of metabase, we see that when we try to save the new url, some validation is done on all the other custom map. 
image

We have several of them that use our geojson server.  
What we understand so far is that we can't save because the other url are not resolved.
 
By looking in the database, we see that all map url are save in the same field custom-geojson of the settings table.
image

Witch seem to confirm our analyse, before commit the change, metabase check all the map url. 

The only way to fixe the issue, for now, would be to modify directly in the database the url of each geojson.

This only happen when at least 2 map urls are not working.

### To Reproduce

1. Go to admin/settings/maps
2. Add at least 2 working urls for a geojson map.
3. After validate that both are working
4. Some how, make at least one of the url impossible to resolve. For example by overloading one of the hostname in the host file to a wrong ip.
5. Try to add a new map from a working url, and save. Nothing should happen from the UI when clicking save.
6. In the log file, an entry about an exception for the wrong url should be show.

### Expected behavior

Each map url should be modifiable individually. 

### Logs

[25042258-e8a8-447b-8a27-814eeaa0d7ff] 2024-06-18T14:06:41+02:00 DEBUG metabase.server.middleware.log PUT /api/setting/custom-geojson 400 5.0 s (0 appels de DB) {:metabase-user-id 1} 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message
   "Emplacement du fichier GeoJSON non valide : doit commencer par http:// ou https:// ou être un chemin d'accès relatif à un fichier sur le classpath. Les URL faisant référence à des hôtes qui fournissent des métadonnées d'hébergement interne sont interdites.",
   :data {:status-code 400, :url "http://srv-dd-carto/geojson/fr-regions.geojson"},
   :at [metabase.api.geojson$valid_url_QMARK_ invokeStatic "geojson.clj" 92]}
  {:type java.net.UnknownHostException,
   :message "srv-dd-carto",
   :at [java.net.InetAddress$CachedAddresses get nil -1]}],
 :trace
 [[java.net.InetAddress$CachedAddresses get nil -1]
  [java.net.InetAddress getAllByName0 nil -1]
  [java.net.InetAddress getAllByName nil -1]
  [java.net.InetAddress getAllByName nil -1]
  [java.net.InetAddress getByName nil -1]
  [metabase.api.geojson$valid_host_QMARK_ invokeStatic "geojson.clj" 79]
  [metabase.api.geojson$valid_host_QMARK_ invoke "geojson.clj" 72]
  [metabase.api.geojson$valid_url_QMARK_ invokeStatic "geojson.clj" 90]
  [metabase.api.geojson$valid_url_QMARK_ invoke "geojson.clj" 85]
  [metabase.api.geojson$valid_geojson_url_QMARK_ invokeStatic "geojson.clj" 97]
  [metabase.api.geojson$valid_geojson_url_QMARK_ invoke "geojson.clj" 94]
  [metabase.api.geojson$valid_geojson_urls_QMARK_$fn__85934 invoke "geojson.clj" 101]
  [clojure.core$every_QMARK_ invokeStatic "core.clj" 2698]
  [clojure.core$every_QMARK_ invoke "core.clj" 2689]
  [metabase.api.geojson$valid_geojson_urls_QMARK_ invokeStatic "geojson.clj" 101]
  [metabase.api.geojson$valid_geojson_urls_QMARK_ invoke "geojson.clj" 99]
  [metabase.api.geojson$validate_geojson invokeStatic "geojson.clj" 109]
  [metabase.api.geojson$validate_geojson invoke "geojson.clj" 104]
  [metabase.api.geojson$fn__85944$fn__85947 invoke "geojson.clj" 120]
  [metabase.models.setting$set_with_audit_logging_BANG_ invokeStatic "setting.clj" 922]
  [metabase.models.setting$set_with_audit_logging_BANG_ invoke "setting.clj" 910]
  [metabase.models.setting$set_BANG_ invokeStatic "setting.clj" 950]
  [metabase.models.setting$set_BANG_ doInvoke "setting.clj" 926]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [metabase.api.setting$fn__99941$fn__99944 invoke "setting.clj" 59]
  [metabase.api.setting$do_with_setting_access_control invokeStatic "setting.clj" 14]
  [metabase.api.setting$do_with_setting_access_control invoke "setting.clj" 10]
  [metabase.api.setting$fn__99941 invokeStatic "setting.clj" 58]
  [metabase.api.setting$fn__99941 invoke "setting.clj" 53]
  [compojure.core$wrap_response$fn__52891 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__52875 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__52880 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__52884 invoke "core.clj" 151]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [metabase.server.middleware.auth$enforce_authentication$fn__97195 invoke "auth.clj" 18]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903 invoke "core.clj" 200]
  [compojure.core$make_context$handler__52931 invoke "core.clj" 290]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 300]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52884 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [metabase.api.routes$fn__103634$fn__103637 invoke "routes.clj" 73]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__103914$fn__103915 doInvoke "routes.clj" 73]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903 invoke "core.clj" 200]
  [compojure.core$make_context$handler__52931 invoke "core.clj" 290]
  [compojure.core$make_context$fn__52935 invoke "core.clj" 300]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52884 invoke "core.clj" 153]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52884 invoke "core.clj" 153]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52884 invoke "core.clj" 153]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52884 invoke "core.clj" 153]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903$f__52904$respond_SINGLEQUOTE___52905 invoke "core.clj" 197]
  [metabase.server.routes$fn__103897$fn__103899 invoke "routes.clj" 47]
  [compojure.core$routes$fn__52903$f__52904 invoke "core.clj" 198]
  [compojure.core$routes$fn__52903 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__100064 invoke "exceptions.clj" 107]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__100061 invoke "exceptions.clj" 96]
  [metabase.server.middleware.log$log_api_call$fn__104194$fn__104195$fn__104196 invoke "log.clj" 236]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
  [metabase.server.middleware.log$log_api_call$fn__104194$fn__104195 invoke "log.clj" 227]
  [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
  [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
  [metabase.server.middleware.log$log_api_call$fn__104194 invoke "log.clj" 226]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__107482 invoke "browser_cookie.clj" 40]
  [metabase.server.middleware.security$add_security_headers$fn__100020 invoke "security.clj" 238]
  [ring.middleware.json$wrap_json_body$fn__107741 invoke "json.clj" 64]
  [metabase.server.middleware.offset_paging$handle_paging$fn__86504 invoke "offset_paging.clj" 43]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__54346 invoke "json.clj" 83]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__107830 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__107849 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__69791 invoke "misc.clj" 60]
  [metabase.server.middleware.session$reset_session_timeout$fn__76935 invoke "session.clj" 552]
  [metabase.server.middleware.session$bind_current_user$fn__76901$fn__76902 invoke "session.clj" 446]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 425]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 408]
  [metabase.server.middleware.session$bind_current_user$fn__76901 invoke "session.clj" 445]
  [metabase.server.middleware.session$wrap_current_user_info$fn__76882 invoke "session.clj" 383]
  [metabase.server.middleware.session$wrap_session_id$fn__76854 invoke "session.clj" 259]
  [metabase.server.middleware.auth$wrap_static_api_key$fn__97203 invoke "auth.clj" 32]
  [ring.middleware.cookies$wrap_cookies$fn__107669 invoke "cookies.clj" 200]
  [metabase.server.middleware.misc$add_content_type$fn__69773 invoke "misc.clj" 28]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__69799 invoke "misc.clj" 77]
  [ring.middleware.gzip$wrap_gzip$fn__107711 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__69802 invoke "misc.clj" 94]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__107498 invoke "ssl.clj" 41]
  [metabase.server$async_proxy_handler$fn__70137 invoke "server.clj" 77]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
  [org.eclipse.jetty.server.Server handle "Server.java" 563]
  [org.eclipse.jetty.server.HttpChannel$RequestDispatchable dispatch "HttpChannel.java" 1598]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 753]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 501]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 287]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
  [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy runTask "AdaptiveExecutionStrategy.java" 421]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy consumeTask "AdaptiveExecutionStrategy.java" 390]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy tryProduce "AdaptiveExecutionStrategy.java" 277]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy run "AdaptiveExecutionStrategy.java" 199]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 411]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 969]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner doRunJob "QueuedThreadPool.java" 1194]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1149]
  [java.lang.Thread run nil -1]],
 :cause "srv-dd-carto",
 :message
 "Emplacement du fichier GeoJSON non valide : doit commencer par http:// ou https:// ou être un chemin d'accès relatif à un fichier sur le classpath. Les URL faisant référence à des hôtes qui fournissent des métadonnées d'hébergement interne sont interdites.",
 :url "http://srv-dd-carto/geojson/fr-regions.geojson"}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.0-112-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "oracle",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.3 (Debian 16.3-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-15",
      "tag": "v0.50.5",
      "hash": "48f6978"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nvoxland**
closes #44353
### Description

Do not validate unchanged URLs so any existing invalid maps do not block saving new maps

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/geojson/settings.clj [hunk 1]
```diff
@@ -110,9 +123,13 @@
   :getter     (fn [] (merge (setting/get-value-of-type :json :custom-geojson) (builtin-geojson)))
   :setter     (fn [new-value]
                 ;; remove the built-in keys you can't override them and we don't want those to be subject to validation.
-                (let [new-value (not-empty (reduce dissoc new-value (keys (builtin-geojson))))]
+                (let [new-value      (not-empty (reduce dissoc new-value (keys (builtin-geojson))))
+                      current-value  (setting/get-value-of-type :json :custom-geojson)
+                      ;; Only validate URLs for entries that are new or have changed URLs.
+                      changed-entries (when new-value
```
Comment (edpaget) [inline src/metabase/geojson/settings.clj:129]: could we use clojure.data/diff here?

**Review by edpaget — APPROVED** [review]

File: src/metabase/geojson/settings.clj (hunk 1 above)
Comment (nvoxland) [reply src/metabase/geojson/settings.clj:129]: We only want to filter based on changed url, and since diff is diffing on everything it seemed easiest to just look for the url differences directly
