### PR TITLE
Fix incorrectness issue for advanced FieldValues when sandboxing use native question

### LINKED ISSUE #24966: Advanced FieldValues does not change if sandbox rule use a native query
**Describe the bug**
If we have a sandbox rule that uses a native query, the advanced FieldValues do not update if users-attribute change.

**To Reproduce**

0. Activate enterprise
1. Create 1 user with attribute State = "CA"
2. Create a group "Test Group" and add the created user in
3. Create a native question : `select * from people where state = {{STATE}}`. Save it as Q1
4. Go to Data Model > Sample Dataset > People, change "filtering on this field" to a "A list of values"
5. Go to Permissions > Data > All Users > Sample Database > set data access to no-self-service
6. Go to Permissions > Data > Test Group > Sample Dataset > People > Data Access > Sandbox, 
7. Select `Use a saved question to create a custom view for this table` > Select question Q1 and map column "State" equals user' attribute "State"
8. Create a People question and add them to a dashboard
9. Create a location/dropdown parameter and link to the `People.City` column.
10. Open a new window, log in as the created user, and open the parameter, notice it'll show a list with the 1st option "Arbuckle"
11. Back to admin, change user attribute to State=NY
12. Back to the created user and open the parameter again. Notice it is still the same list as before( 1st option is Arbuckle)

**Expected behavior**
When the user attribute changes, the Parameter for `People.City` should be updated as well.

**Severity**
Incorrect parameters values for the customer who updates user-attribute on the fly + sandbox using a native query.

**Additional context**
A customer reported this issue in https://github.com/metabase/metabase/pull/24740#issuecomment-1223137404 - historically #15977

### PR DESCRIPTION
**Pull request by qnkhuat**
Fix #24966
Reproduces #24966 

### The bug
For sandboxing using a native query, then if 2 users with different login-attribute fetch values for a Field, they will see the same values list.

The expected behavior is they should get a different values list that is filtered correctly based on their login-attribute

### Background

In #24096 we tried to make hashing for Advanced FieldValues smarter by hashing a map with:
- the key is the user attribute we used in the sandbox rule
- value is the user attribute of the user for the corresponding key.
https://github.com/metabase/metabase/blob/3ef9c19fe80a074a85db2d1f2c7668a1d92929b3/enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj#L60-L64

The problem with that implementation is that it relies on finding a `field-id` in the definition of GTAP.
But, If we set up a sandbox that uses a native query, it'll only contain the name of the parameter, which looks like this:
```
{"State": ["dimension" ["template-tag" "State"]]}
```

So what happened is this map will be empty anytime for any users that try to access it, even if they have different login attributes => so they'll have the same hash => thus getting the same list of values.

My solution for this is to hash the user attribute in case sandboxing uses a native query, please see this [comment](https://github.com/metabase/metabase/pull/24967/files#r956970629) for more details

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/sandbox/api/field_test.clj [hunk 1]
```diff
@@ -22,67 +22,82 @@
...
-          ;; Rasta Toucan is only allowed to see Venues that are in the "Mexican" category [category_id = 50]. So
-          ;; fetching FieldValues for `venue.name` should do an ad-hoc fetch and only return the names of venues in
-          ;; that category.
-          (is (= {:field_id        (mt/id :venues :name)
-                  :values          [["Garaje"]
-                                    ["Gordo Taqueria"]
-                                    ["La Tortilla"]]
-                  :has_more_values false}
-                 (fetch-values :rasta :name)))
+    (mt/with-temp-copy-of-db
```
Comment (qnkhuat) [inline enterprise/backend/test/metabase_enterprise/sandbox/api/field_test.clj:25]: the test itself was not updated, what changed in this test is I added another round of test where GTAP use a native question with parameter.

**Comment by dpsutton** [comment]
I think this makes sense but we'll need @camsaul for a final approval for anything touching sandboxing.

**Review by camsaul — APPROVED** [review]
Cool, as far as I can tell this looks good to me.
