### PR TITLE
[QP] Correctly handle "struct" fields on Athena and similar drivers

### LINKED ISSUE #47003: There was a field matching error when using the field filter of Metabase to query Athena's data
### Describe the bug

When I use Metabase's variable filter to select fields from an Athena table, the field mapping works correctly due to the nested data structure. However, when I execute the query, I discover that Metabase's parameter is missing one level of nesting, resulting in no data being retrieved.

image

### To Reproduce

1.This is one of my data：{"project": "ScrapingInstagramPostsFromTagsSearch", "taskid": "00799b2e54742822cca04270b6626f22", "url": "data:,on_message?tag=banana&id=3435415062162709246", "result": {"tag_name": "banana", "post": {"post_id": "3435415062162709246", "shortcode": "C-tC8wkPBr-", "url": "[https://www.instagram.com/p/C-tC8wkPBr-/](<https://www.instagram.com/p/C-tC8wkPBr-/>)", "thumbnail": "[https://scontent-lax3-2.cdninstagram.com/v/t51.29350-15/455816674_3733006713588552_4087020744170563399_n.heic?stp=dst-jpg_e35_s150x150&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4zMjB4MzIwLnNkci5mMjkzNTAuZGVmYXVsdF9pbWFnZSJ9&\_nc_ht=scontentlax32.cdninstagram.com&\_nc_cat=100&\_nc_ohc=\_28RN1aSYyUQ7kNvgGI2BuH&edm=AA0rjkIBAAAA&ccb=7-5&oh=00_AYAvoJvNnnN-PiuuBVDM0Q4MZKR0T3HBu-yfpWDRTvyG9w&oe=66C9CE08&\_nc_sid=49ed71](<https://scontent-lax3-2.cdninstagram.com/v/t51.29350-15/455816674_3733006713588552_4087020744170563399_n.heic?stp=dst-jpg_e35_s150x150&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4zMjB4MzIwLnNkci5mMjkzNTAuZGVmYXVsdF9pbWFnZSJ9&_nc_ht=scontentlax32.cdninstagram.com&_nc_cat=100&_nc_ohc=_28RN1aSYyUQ7kNvgGI2BuH&edm=AA0rjkIBAAAA&ccb=7-5&oh=00_AYAvoJvNnnN-PiuuBVDM0Q4MZKR0T3HBu-yfpWDRTvyG9w&oe=66C9CE08&_nc_sid=49ed71>)", "caption": "Banana #banana #ballzbanana #batman #art", "owner": {"user_id": "60784577547"}, "display_url": "[https://scontent-lax2.cdninstagram.com/v/t51.293515/455816674_3733006713588552_4087020744170563399_n.heic?stp=dstjpg_e35&\_nc_ht=scontent2.cdninstagram.com&\_nc_cat=100&\_nc_ohc=\_28RN1aSYyUQ7kNvgGI2BuH&edm=AA0rjkIBAAAA&ccb=7-5&oh=00_AYDgPaINV7EII4BDWKTYLCoRv1c9ZN4V-YIa6NERrvh6ZA&oe=66C9CE08&\_nc_sid=49ed71](<https://scontent-lax2.cdninstagram.com/v/t51.293515/455816674_3733006713588552_4087020744170563399_n.heic?stp=dstjpg_e35&_nc_ht=scontent2.cdninstagram.com&_nc_cat=100&_nc_ohc=_28RN1aSYyUQ7kNvgGI2BuH&edm=AA0rjkIBAAAA&ccb=7-5&oh=00_AYDgPaINV7EII4BDWKTYLCoRv1c9ZN4V-YIa6NERrvh6ZA&oe=66C9CE08&_nc_sid=49ed71>)", "is_video": false, "likes_count": 0, "comments_count": 0, "published_time": 1723753410}, "scraped_time": 1724120799807}, "createTime": 1724123022.4007459}

2.this is my DDL: CREATE EXTERNAL TABLE scrapinginstagrampostsfromtagssearch(<br>taskid string COMMENT 'from deserializer',<br>url string COMMENT 'from deserializer',<br>result struct<tag_name:string,post:struct<post_id:string,shortcode:string,url:string,thumbnail:string,caption:string,owner:struct<user_id:string>,display_url:string,is_video:boolean,video_view_count:int,likes_count:int,comments_count:int,published_time:timestamp>, createTime:timestamp> COMMENT 'from deserializer',<br>updatetime timestamp COMMENT 'from deserializer')<br>ROW FORMAT SERDE<br>'org.openx.data.jsonserde.JsonSerDe'<br>STORED AS INPUTFORMAT<br>'org.apache.hadoop.mapred.TextInputFormat'<br>OUTPUTFORMAT<br>'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'<br>LOCATION<br>'s3://\*\*\*\*/'<br>TBLPROPERTIES (<br>'classification'='json')

3.Connect Athena using Metabase and then use variable filters

### Expected behavior

*No response*

### Logs

\[Simba\][AthenaJDBC](<https://github.com/metabase/metabase/issues/100071>) An error has been thrown from the AWS Athena client. COLUMN_NOT_FOUND: line 4:8: Column 'pyspider.scrapinginstagrampostsfromtagssearch.tag_name' cannot be resolved or requester is not authorized to access requested resources \[Execution ID: d3b4c9bd-937c-4254-ba22-d0c65152df13\]

### Information about your Metabase installation

```JSON
v0.49.14
```

### Severity

P2

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by bshepherdson**
closes #47003
Fixes QUE2-34.

### Description

These are nested fields (`:parent_id` is set) but not JSON nesting, so
the mechanism is slightly different from `:nfc_path`. This change should
include the necessary metadata on `:field` refs inserted by field filters
to correctly handle struct fields.

### How to verify

Using Athena or BigQuery (or another engine that supports struct-style nesting) confirm that a field filter bound to a nested field is correctly executed and doesn't produce errors like in the bug.

The new unit test also failed with the same error as the bug report before the fix.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- ~~If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)~~

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#71917** <a href="https://app.graphite.com/github/pr/metabase/metabase/71917?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/metabase/metabase/71917?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: test/metabase/driver/sql/parameters/substitute_test.clj [hunk 1]
```diff
@@ -112,6 +115,55 @@
...
+                                  :nfc-path      nil)
+            field-filter   (params/map->FieldFilter
+                            {:field field-metadata
+                             :value {:type  :string/=
+                                     :value ["banana"]}})
+            [sql _args] (mt/with-metadata-provider metadata-provider
+                          (sql.params.substitute/substitute query {"tag" field-filter}))]
+        (testing "The SQL identifier should include the parent field 'result' before 'tag_name'"
+          ;; Currently this FAILS: the identifier is "PUBLIC"."VENUES"."tag_name" (missing "result")
+          ;; It should be "PUBLIC"."VENUES"."result"."tag_name"
```
Comment (metamben) [inline test/metabase/driver/sql/parameters/substitute_test.clj]: Should this be deleted?

File: src/metabase/driver/sql/parameters/substitution.clj [hunk 2]
```diff
@@ -271,10 +271,11 @@
...
     (:id field)
-    (merge {:base-type                     (:base-type field)
-            driver-api/qp.add.source-table (:table-id field)
-            ::compiling-field-filter?      true}
-           other-opts)]))
+    (cond-> (merge {:base-type                     (:base-type field)
+                    driver-api/qp.add.source-table (:table-id field)
+                    ::compiling-field-filter?      true}
+                   other-opts)
+      (seq (:nfc-path field)) (assoc driver-api/qp.add.nfc-path (:nfc-path field)))]))
```
Comment (metamben) [inline src/metabase/driver/sql/parameters/substitution.clj]: Is this necessary for the fix? If it fixes something different, then there should be a test case demonstrating that we need it.

File: src/metabase/driver/sql/query_processor.clj [hunk 3]
```diff
@@ -890,6 +890,18 @@
   [_driver [_ _nfc-path]]
   nil)
 
+(defn- parent-id->ancestor-names
+  "Walk the parent chain for a field with `:parent-id` set and return the ancestor field names in order.
```
Comment (metamben) [inline src/metabase/driver/sql/query_processor.clj]: I'm not sure "in order" is well defined. procedurally, I would expect them to start with the parent, but the example says otherwise. I suppose we should say something like "in the order necessary for the prefix of the qualified field name".

File: src/metabase/driver/sql/query_processor.clj [hunk 4]
```diff
@@ -890,6 +890,18 @@
...
+  For example, if field `tag_name` has parent `result`, returns `[\"result\"]`.
+  If `tag_name` has parent `post` which has parent `result`, returns `[\"result\" \"post\"]`."
+  [parent-id]
+  (loop [id parent-id
+         path (list)]
```
Comment (metamben) [inline src/metabase/driver/sql/query_processor.clj]:
```suggestion
         path ()]
```
`[]` would work too, since we are `cons`ing anyway.

**Review by metamben — CHANGES_REQUESTED** [review]
LGTM, just some cleanup is needed, I think.

File: src/metabase/driver/sql/parameters/substitution.clj (hunk 2 above)
Comment (bshepherdson) [reply src/metabase/driver/sql/parameters/substitution.clj]: Ah, you're right, this is left over from a first cut at the solution, but BQ-style structs are not JSON things and don't use `:nfc-path`.

File: src/metabase/driver/sql/query_processor.clj (hunk 3 above)
Comment (bshepherdson) [reply src/metabase/driver/sql/query_processor.clj]: Updated to be more explicitly "oldest first", which is the intended order and what the code returns.

**Review by metamben — APPROVED** [review]
