### PR TITLE
Fix MongoDB's native query preview overflow

### LINKED ISSUE #2834: We should pretty-print Mongo & Druid JSON queries when converting MBQL -> native
When I convert to a native query I see

screen shot 2016-06-24 at 1 00 40 pm

I would prefer to see something more like

screen shot 2016-06-24 at 1 01 17 pm

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #21018: Native query preview overflow window when there are no space
**Describe the bug**
When seeing the native query in a Mongo GUI generated query, the text goes waaaay out of bounds
image

**Logs**
No Logs

**To Reproduce**
1) set up a Metabase with the sample Mongo DB
2) generate a simple GUI query with a filter
3) check the native query, see the error

**Expected behavior**
At least have the query contained in the box

**Screenshots**
NA

**Severity**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes #21018

There could be 2 simple ways to fix this. By replacing this line https://github.com/metabase/metabase/blob/59d222b88eac438938b515a709dbea457ee4fc37/frontend/src/metabase/lib/engine.js#L82
with 
1. Add space between each key to allow text to wrap
    ```js
    return String(JSON.stringify(query)).replaceAll('","', '", "');
    ```
2. Use JSON.stringify's builtin `space`
    ```js
    return return JSON.stringify(query, null, 2);
    ```

#### Before the fix
image

#### After the first option
localhost_3000_question_notebook (3)

#### After the second option
localhost_3000_question_notebook (2)

I personally think the second option looks better, so I went with it.

### CODE REVIEW

**Review by flamber — APPROVED** [review]
Seems to work great - here's Druid:
image

But could the actual Convert button somehow be always visible, so you don't have to scroll?

https://user-images.githubusercontent.com/1447303/161728754-146bb992-27a4-4eec-aa16-56d828c17ed3.mp4

Another example with a large table (or something with a lot of joins):
image

**Comment by WiNloSt** [comment]
@flamber 
> But could the actual Convert button somehow be always visible, so you don't have to scroll?

I could try to add some CSS magic so that the query section is scrollable instead and the whole modal is as high as the screen is available.

**Comment by WiNloSt** [comment]
@flamber I don't think it's viable to make `pre` scrollable and expand it all the way if screen real estate permits via CSS to my knowledge. I'll leave it as is.

File: frontend/src/metabase/lib/engine.js [hunk 1]
```diff
@@ -79,7 +79,7 @@ export function formatJsonQuery(query, engine) {
   if (engine === "googleanalytics") {
     return formatGAQuery(query);
   } else {
-    return JSON.stringify(query);
+    return JSON.stringify(query, null, 2);
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/engine.js:82]: Note to reviewers.

I want to achieve something like this

#### When SQL is longer than the modal
image

#### When SQL is shorter than the modal
image

I'm not sure how to do that only via CSS without resorting to JS hack.

**Comment by losrebellos** [comment]
@flamber @paoliniluis

__After__

- Mobile portrait

image

- Mobile landscape

image

- Tablet

image

- Desktop

image

File: frontend/src/metabase/query_builder/components/view/NativeQueryButton.jsx [hunk 2]
```diff
@@ -84,6 +88,7 @@ export default class NativeQueryButton extends React.Component {
           <SqlIconButton iconSize={size} onClick={this.handleOpen} />
         </Tooltip>
         <Modal
+          style={{ padding: "1em" }}
```
Comment (losrebellos) [inline frontend/src/metabase/query_builder/components/view/NativeQueryButton.jsx:91]: Add padding so the modal will have some spacing on the left and right on small screen devices.

File: frontend/src/metabase/query_builder/components/view/NativeQueryButton.jsx [hunk 3]
```diff
@@ -96,7 +101,11 @@ export default class NativeQueryButton extends React.Component {
           onClose={this.handleClose}
         >
           <LoadingAndErrorWrapper loading={loading} error={error}>
-            <pre className="mb3 p2 sql-code">{this.getFormattedQuery()}</pre>
+            <NativeCodeWrapper>
```
Comment (losrebellos) [inline frontend/src/metabase/query_builder/components/view/NativeQueryButton.jsx:104]: Updated tagging hierarchy so it is:
```css
div > pre > code
```

File: frontend/src/metabase/styled-components/theme/media-queries.ts [hunk 4]
```diff
@@ -9,3 +9,11 @@ export const breakpointMaxSmall = "@media screen and (max-width: 40em)";
 export const breakpointMaxMedium = "@media screen and (max-width: 60em)";
 export const breakpointMaxLarge = "@media screen and (max-width: 80em)";
 export const breakpointMaxExtraLarge = "@media screen and (max-width: 120em)";
+
+export const breakpointMinHeightExtraSmall =
```
Comment (losrebellos) [inline frontend/src/metabase/styled-components/theme/media-queries.ts:13]: Height breakpoints created.

File: frontend/src/metabase/query_builder/components/view/NativeQueryButton.styled.jsx [hunk 5]
```diff
@@ -21,3 +26,39 @@ export const SqlIconButton = styled(Button)`
...
+  margin: 0;
+  max-height: 20vh;
+  max-width: 100%;
+  overflow: auto;
+  vertical-align: bottom;
+  white-space: pre;
+  width: 100%;
+  word-break: break-all;
+
+  ${breakpointMinHeightExtraSmall} {
```
Comment (losrebellos) [inline frontend/src/metabase/query_builder/components/view/NativeQueryButton.styled.jsx:53]: Height breakpoints added so we use the maximum screen `real estate` to display the native code.

**Review by flamber — APPROVED** [review]
This feels much better than currently and looks great.

File: frontend/src/metabase/query_builder/components/view/NativeQueryButton.styled.jsx (hunk 5 above)
Comment (WiNloSt) [reply frontend/src/metabase/query_builder/components/view/NativeQueryButton.styled.jsx:53]: Great, I focused too much on getting this to work with only flexbox and totally forgot the good ol' media query 😆
