### PR TITLE
Show sensitive columns in the sandboxing UI

### LINKED ISSUE #53378: sandbox UI doesn't show hidden columns
### Describe the bug

Sandbox on a column

Image

Hide the column

Image

UI no longer shows column in config box

Image

Network includes correctly configured sandbox information

Image
But the field is missing from query metadata (presumably)

### To Reproduce

above is a pretty exhaustive repro

### Expected behavior

should show the column in the config box.

### Logs

_No response_

### Information about your Metabase installation

```JSON
any version
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by metamben**
Closes #53378

### Description

Make it possible to get the sensitive columns for a query too and make the FE use this option when presenting sandboxing options.

### How to verify

The repro steps should now lead the sensitive column (`ID`) to be displayed.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/sandbox/api/table_test.clj [hunk 1]
```diff
@@ -110,14 +110,12 @@
       (testing "Users with restricted access to the columns of a table should only see columns included in the GTAP question"
         (mt/with-current-user (mt/user->id :rasta)
           (is (= #{"VENUES.CATEGORY_ID" "VENUES.ID" "VENUES.NAME"}
-                 (->> [(mt/id :venues) (mt/id :checkins)]
-                      table/batch-fetch-table-query-metadatas
+                 (->> (table/batch-fetch-table-query-metadatas [(mt/id :venues) (mt/id :checkins)] nil)
                       upper-case-field-names)))))
```
Comment (bshepherdson) [inline enterprise/backend/test/metabase_enterprise/sandbox/api/table_test.clj:114]:
```suggestion
                 (-> [(mt/id :venues) (mt/id :checkins)]
                     (table/batch-fetch-table-query-metadatas nil)
                     upper-case-field-names)))))
```

Comment (bshepherdson) [reply enterprise/backend/test/metabase_enterprise/sandbox/api/table_test.clj:114]: And below.

File: src/metabase/lib/metadata.cljc [hunk 2]
```diff
@@ -63,29 +63,33 @@
...
-      (cond->> only-active?
-        (remove (fn [col]
-                  (or (false? (:active col))
-                      (#{:sensitive :retired} (:visibility-type col))))))
-      (->> (sort-by (juxt #(:position % 0) #(u/lower-case-en (:name % "")))))))
+(defn- fields* [metadata-providerable table-id {:keys [include-sensitive?]}]
+  (->> (lib.metadata.protocols/fields (->metadata-provider metadata-providerable)
+                                      table-id
+                                      {:include-sensitive? (boolean include-sensitive?)})
+       (sort-by (juxt #(:position % 0) #(u/lower-case-en (:name % ""))))))
```
Comment (bshepherdson) [inline src/metabase/lib/metadata.cljc:53]: Why is it `:include-sensitive-fields?` in some places and `:include-sensitive?` in others?

**Review by bshepherdson — APPROVED** [review]
LGTM overall, but perhaps we can make the naming more consistent.

File: src/metabase/lib/metadata.cljc (hunk 2 above)
Comment (metamben) [reply src/metabase/lib/metadata.cljc:53]: In the function which is already scoped to fields, I omitted the `-fields` part.
