### PR TITLE
Don't pass query parameters when compiling Saved Question references

### LINKED ISSUE #21246: Cannot use Sub-Query referencing a GUI question and a date based filter
**Describe the bug**
When creating a SQL question, which uses a [Saved Question](https://www.metabase.com/docs/latest/users-guide/referencing-saved-questions-in-queries.html) that is GUI based and a Date filter or Field Filter on a date column, then query fails. It works with Text and Number filters.

Workaround is to convert the GUI question to SQL, then it will work.

**To Reproduce**
1. Question > Sample > Products - save as "Q1"
2. SQL query > Sample - replace `114` with the ID of Q1 from step 1 - set `filter` as Field Filter of Orders.CreatedAt or a Date filter
```
with exclude_products as {{#114}}
select count(*) from orders where true [[and {{filter}}]] -- Field Filter, but will also fail with Date filter: [[and created_at={{datevariable}}]]
```
3. Run the query - it works
image
4. Input anything in the filter widget and the query will fail with `Error building query parameter map: Error determining value for parameter \"#114\": The sub-query from referenced question #114 failed with the following error: \"Output of unwrap-field-clause does not match schema: \\n\\n\\t   [(not (present? :field)) (not (present? \\\"id-or-name\\\")) (not (present? \\\"options\\\"))]  \\n\\n\"`

<details><summary>Full stacktrace</summary>

```
2022-03-25 13:04:43,661 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2022-03-25T13:04:42.528037+01:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "The sub-query from referenced question #114 failed with the following error: \"Output of unwrap-field-clause does not match schema: \\n\\n\\t   [(not (present? :field)) (not (present? \\\"id-or-name\\\")) (not (present? \\\"options\\\"))]  \\n\\n\"",
   :stacktrace
   ["--> driver.common.parameters.values$fn__78245$parse_tag__78238__78250$fn__78254.invoke(values.clj:134)"
    "driver.common.parameters.values$fn__78245$parse_tag__78238__78250.invoke(values.clj:121)"
    "driver.common.parameters.values$fn__78500$value_for_tag__78505$fn__78506.invoke(values.clj:307)"
    "driver.common.parameters.values$fn__78500$value_for_tag__78505.invoke(values.clj:302)"
    "driver.common.parameters.values$fn__78524$query__GT_params_map__78529$fn__78533$iter__78535__78539$fn__78540.invoke(values.clj:326)"
    "driver.common.parameters.values$fn__78524$query__GT_params_map__78529$fn__78533.invoke(values.clj:325)"
    "driver.common.parameters.values$fn__78524$query__GT_params_map__78529.invoke(values.clj:316)"
    "driver.sql$fn__78608$substitute_native_parameters__78601__78613$fn__78617.invoke(sql.clj:46)"
    "driver.sql$fn__78608$substitute_native_parameters__78601__78613.invoke(sql.clj:42)"
    "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
    "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
    "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:49)"
    "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:40)"
    "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
    "mbql.util.match.impl$replace_in_collection$iter__27400__27404$fn__27405.invoke(impl.cljc:44)"
    "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
    "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
    "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:58)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:55)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
    "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:76)"
    "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:72)"
    "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604$fn__48605.invoke(parameters.clj:81)"
    "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604.invoke(parameters.clj:78)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48624.invoke(parameters.clj:109)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45984.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__52276.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48404.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51227.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643$fn__50648.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46530.invoke(fetch_source_query.clj:286)"
    "query_processor.middleware.store$initialize_store$fn__46721$fn__46722.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46721.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50978.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50985.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48350.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49641.invoke(results_metadata.clj:82)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48368.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50919.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51307.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___43282$thunk__43283.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___43282.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___43291$fn__43294.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___43291.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:247)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:243)"
    "query_processor$fn__52324$process_query_and_save_execution_BANG___52333$fn__52336.invoke(query_processor.clj:258)"
    "query_processor$fn__52324$process_query_and_save_execution_BANG___52333.invoke(query_processor.clj:251)"
    "query_processor$fn__52368$process_query_and_save_with_max_results_constraints_BANG___52377$fn__52380.invoke(query_processor.clj:270)"
    "query_processor$fn__52368$process_query_and_save_with_max_results_constraints_BANG___52377.invoke(query_processor.clj:263)"
    "api.dataset$run_query_async$fn__65303.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__38418$fn__38419.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__38418.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__26888.invoke(streaming_response.clj:84)"],
   :error_type :invalid-parameter,
   :ex-data
   {:card-query-error? true,
    :card-id 114,
    :tag {:id "8c468524-e0f4-aaf7-3757-f84141a5e27d", :name "#114", :display-name "#114", :type :card, :card-id 114},
    :type :invalid-parameter}}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error determining value for parameter \"#114\": The sub-query from referenced question #114 failed with the following error: \"Output of unwrap-field-clause does not match schema: \\n\\n\\t   [(not (present? :field)) (not (present? \\\"id-or-name\\\")) (not (present? \\\"options\\\"))]  \\n\\n\"",
   :stacktrace
   ["--> driver.common.parameters.values$fn__78500$value_for_tag__78505$fn__78506.invoke(values.clj:309)"
    "driver.common.parameters.values$fn__78500$value_for_tag__78505.invoke(values.clj:302)"
    "driver.common.parameters.values$fn__78524$query__GT_params_map__78529$fn__78533$iter__78535__78539$fn__78540.invoke(values.clj:326)"
    "driver.common.parameters.values$fn__78524$query__GT_params_map__78529$fn__78533.invoke(values.clj:325)"
    "driver.common.parameters.values$fn__78524$query__GT_params_map__78529.invoke(values.clj:316)"
    "driver.sql$fn__78608$substitute_native_parameters__78601__78613$fn__78617.invoke(sql.clj:46)"
    "driver.sql$fn__78608$substitute_native_parameters__78601__78613.invoke(sql.clj:42)"
    "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
    "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
    "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:49)"
    "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:40)"
    "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
    "mbql.util.match.impl$replace_in_collection$iter__27400__27404$fn__27405.invoke(impl.cljc:44)"
    "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
    "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
    "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:58)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:55)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
    "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:76)"
    "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:72)"
    "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604$fn__48605.invoke(parameters.clj:81)"
    "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604.invoke(parameters.clj:78)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48624.invoke(parameters.clj:109)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45984.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__52276.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48404.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51227.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643$fn__50648.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46530.invoke(fetch_source_query.clj:286)"
    "query_processor.middleware.store$initialize_store$fn__46721$fn__46722.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46721.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50978.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50985.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48350.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49641.invoke(results_metadata.clj:82)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48368.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50919.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51307.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___43282$thunk__43283.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___43282.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___43291$fn__43294.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___43291.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:247)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:243)"
    "query_processor$fn__52324$process_query_and_save_execution_BANG___52333$fn__52336.invoke(query_processor.clj:258)"
    "query_processor$fn__52324$process_query_and_save_execution_BANG___52333.invoke(query_processor.clj:251)"
    "query_processor$fn__52368$process_query_and_save_with_max_results_constraints_BANG___52377$fn__52380.invoke(query_processor.clj:270)"
    "query_processor$fn__52368$process_query_and_save_with_max_results_constraints_BANG___52377.invoke(query_processor.clj:263)"
    "api.dataset$run_query_async$fn__65303.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__38418$fn__38419.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__38418.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__26888.invoke(streaming_response.clj:84)"],
   :error_type :invalid-parameter,
   :ex-data
   {:tag {:id "8c468524-e0f4-aaf7-3757-f84141a5e27d", :name "#114", :display-name "#114", :type :card, :card-id 114},
    :type :invalid-parameter}}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error building query parameter map: Error determining value for parameter \"#114\": The sub-query from referenced question #114 failed with the following error: \"Output of unwrap-field-clause does not match schema: \\n\\n\\t   [(not (present? :field)) (not (present? \\\"id-or-name\\\")) (not (present? \\\"options\\\"))]  \\n\\n\"",
   :stacktrace
   ["--> driver.common.parameters.values$fn__78524$query__GT_params_map__78529$fn__78533.invoke(values.clj:334)"
    "driver.common.parameters.values$fn__78524$query__GT_params_map__78529.invoke(values.clj:316)"
    "driver.sql$fn__78608$substitute_native_parameters__78601__78613$fn__78617.invoke(sql.clj:46)"
    "driver.sql$fn__78608$substitute_native_parameters__78601__78613.invoke(sql.clj:42)"
    "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
    "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
    "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:49)"
    "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:40)"
    "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
    "mbql.util.match.impl$replace_in_collection$iter__27400__27404$fn__27405.invoke(impl.cljc:44)"
    "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
    "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
    "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:58)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:55)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
    "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:76)"
    "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:72)"
    "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604$fn__48605.invoke(parameters.clj:81)"
    "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604.invoke(parameters.clj:78)"
    "query_processor.middleware.parameters$substitute_parameters$fn__48624.invoke(parameters.clj:109)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45984.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__52276.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48404.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51227.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643$fn__50648.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46530.invoke(fetch_source_query.clj:286)"
    "query_processor.middleware.store$initialize_store$fn__46721$fn__46722.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__46721.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50978.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50985.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48350.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49641.invoke(results_metadata.clj:82)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48368.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__50919.invoke(process_userland_query.clj:146)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51307.invoke(catch_exceptions.clj:169)"
    "query_processor.reducible$async_qp$qp_STAR___43282$thunk__43283.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___43282.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___43291$fn__43294.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___43291.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:247)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:243)"
    "query_processor$fn__52324$process_query_and_save_execution_BANG___52333$fn__52336.invoke(query_processor.clj:258)"
    "query_processor$fn__52324$process_query_and_save_execution_BANG___52333.invoke(query_processor.clj:251)"
    "query_processor$fn__52368$process_query_and_save_with_max_results_constraints_BANG___52377$fn__52380.invoke(query_processor.clj:270)"
    "query_processor$fn__52368$process_query_and_save_with_max_results_constraints_BANG___52377.invoke(query_processor.clj:263)"
    "api.dataset$run_query_async$fn__65303.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__38418$fn__38419.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__38418.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__26888.invoke(streaming_response.clj:84)"],
   :error_type :invalid-parameter,
   :ex-data
   {:type :invalid-parameter,
    :tags
    {"#114"
     {:id "8c468524-e0f4-aaf7-3757-f84141a5e27d", :name "#114", :display-name "#114", :type :card, :card-id 114},
     "filter"
     {:id "79400356-2c24-782c-fa46-e9d29b9dacfb",
      :name "filter",
      :display-name "Filter",
      :type :dimension,
      :dimension [:field 86 nil],
      :widget-type :date/all-options,
      :default nil}},
    :params
    [{:type :date/all-options,
      :value "past30years",
      :target [:dimension [:template-tag "filter"]],
      :id "79400356-2c24-782c-fa46-e9d29b9dacfb"}]}}],
 :error_type :invalid-query,
 :json_query
 {:database 4,
  :native
  {:template-tags
   {:#114 {:id "8c468524-e0f4-aaf7-3757-f84141a5e27d", :name "#114", :display-name "#114", :type "card", :card-id 114},
    :filter
    {:id "79400356-2c24-782c-fa46-e9d29b9dacfb",
     :name "filter",
     :display-name "Filter",
     :type "dimension",
     :dimension ["field" 86 nil],
     :widget-type "date/all-options",
     :default nil}},
   :query "with exclude_products as {{#114}}\nselect count(*) from orders where {{filter}}"},
  :type "native",
  :parameters
  [{:type "date/all-options",
    :value "past30years",
    :target ["dimension" ["template-tag" "filter"]],
    :id "79400356-2c24-782c-fa46-e9d29b9dacfb"}],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> models.params$fn__38495$unwrap_field_clause__38500.invoke(params.clj:21)"
  "query_processor.middleware.parameters.mbql$fn__48480$build_filter_clause__48485$fn__48495.invoke(mbql.clj:57)"
  "query_processor.middleware.parameters.mbql$fn__48480$build_filter_clause__48485.invoke(mbql.clj:44)"
  "query_processor.middleware.parameters.mbql$expand.invokeStatic(mbql.clj:86)"
  "query_processor.middleware.parameters.mbql$expand.invoke(mbql.clj:72)"
  "query_processor.middleware.parameters$expand_mbql_params.invokeStatic(parameters.clj:36)"
  "query_processor.middleware.parameters$expand_mbql_params.invoke(parameters.clj:32)"
  "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:48)"
  "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:40)"
  "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
  "mbql.util.match.impl$replace_in_collection$iter__27400__27404$fn__27405.invoke(impl.cljc:44)"
  "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
  "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
  "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:58)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:55)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:76)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:72)"
  "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604$fn__48605.invoke(parameters.clj:81)"
  "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604.invoke(parameters.clj:78)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48624.invoke(parameters.clj:109)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45984.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__52276.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48404.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51227.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643$fn__50648.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46530.invoke(fetch_source_query.clj:286)"
  "query_processor.middleware.store$initialize_store$fn__46721$fn__46722.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:42)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__46721.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50978.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__50985.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48350.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49641.invoke(results_metadata.clj:82)"
  "query_processor.reducible$async_qp$qp_STAR___43282$thunk__43283.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___43282.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___43291$fn__43294.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___43291.invoke(reducible.clj:134)"
  "query_processor$preprocess_query.invokeStatic(query_processor.clj:172)"
  "query_processor$preprocess_query.invoke(query_processor.clj:164)"
  "query_processor$query__GT_native.invokeStatic(query_processor.clj:203)"
  "query_processor$query__GT_native.invoke(query_processor.clj:199)"
  "driver.common.parameters.values$fn__78245$parse_tag__78238__78250$fn__78254.invoke(values.clj:132)"
  "driver.common.parameters.values$fn__78245$parse_tag__78238__78250.invoke(values.clj:121)"
  "driver.common.parameters.values$fn__78500$value_for_tag__78505$fn__78506.invoke(values.clj:307)"
  "driver.common.parameters.values$fn__78500$value_for_tag__78505.invoke(values.clj:302)"
  "driver.common.parameters.values$fn__78524$query__GT_params_map__78529$fn__78533$iter__78535__78539$fn__78540.invoke(values.clj:326)"
  "driver.common.parameters.values$fn__78524$query__GT_params_map__78529$fn__78533.invoke(values.clj:325)"
  "driver.common.parameters.values$fn__78524$query__GT_params_map__78529.invoke(values.clj:316)"
  "driver.sql$fn__78608$substitute_native_parameters__78601__78613$fn__78617.invoke(sql.clj:46)"
  "driver.sql$fn__78608$substitute_native_parameters__78601__78613.invoke(sql.clj:42)"
  "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:39)"
  "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:30)"
  "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:49)"
  "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:40)"
  "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
  "mbql.util.match.impl$replace_in_collection$iter__27400__27404$fn__27405.invoke(impl.cljc:44)"
  "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
  "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
  "query_processor.middleware.parameters$expand_all$replace_48583__48584.invoke(parameters.clj:58)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:58)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:55)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:52)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:76)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:72)"
  "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604$fn__48605.invoke(parameters.clj:81)"
  "query_processor.middleware.parameters$fn__48599$substitute_parameters_STAR___48604.invoke(parameters.clj:78)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48624.invoke(parameters.clj:109)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45984.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__52276.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__48404.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51227.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643$fn__50648.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50643.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46530.invoke(fetch_source_query.clj:286)"
  "query_processor.middleware.store$initialize_store$fn__46721$fn__46722.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__46721.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50978.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__50985.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48350.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49641.invoke(results_metadata.clj:82)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48368.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__50919.invoke(process_userland_query.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51307.invoke(catch_exceptions.clj:169)"
  "query_processor.reducible$async_qp$qp_STAR___43282$thunk__43283.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___43282.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___43291$fn__43294.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___43291.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:247)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:243)"
  "query_processor$fn__52324$process_query_and_save_execution_BANG___52333$fn__52336.invoke(query_processor.clj:258)"
  "query_processor$fn__52324$process_query_and_save_execution_BANG___52333.invoke(query_processor.clj:251)"
  "query_processor$fn__52368$process_query_and_save_with_max_results_constraints_BANG___52377$fn__52380.invoke(query_processor.clj:270)"
  "query_processor$fn__52368$process_query_and_save_with_max_results_constraints_BANG___52377.invoke(query_processor.clj:263)"
  "api.dataset$run_query_async$fn__65303.invoke(dataset.clj:69)"
  "query_processor.streaming$streaming_response_STAR_$fn__38418$fn__38419.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__38418.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$task__26888.invoke(streaming_response.clj:84)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "Output of unwrap-field-clause does not match schema: \n\n\t   [(not (present? :field)) (not (present? \"id-or-name\")) (not (present? \"options\"))]  \n\n",
 :row_count 0,
 :running_time 0,
 :ex-data
 {:type :schema.core/error,
  :value nil,
  :error [(not (present? :field)) (not (present? "id-or-name")) (not (present? "options"))]},
 :data {:rows [], :cols []}}

2022-03-25 13:04:43,668 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.1 s (8 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (3 idle, 0 queued) (56 total active threads) Queries in flight: 1 (0 queued)
```

</details>

**Information about your Metabase Installation:**
Tested 0.38.5 thru 0.42.3

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #21246

The problem was we were passing along parameters meant for the top-level native query along to the referenced Saved Questions (e.g. the `{{#1234}}` parameters) which caused things to fail since native query parameters don't work when compiling MBQL questions. I thought we must have been doing this for some sort of good reason but it looks like all tests are passing when we remove it and it fixes the problem

### CODE REVIEW

File: src/metabase/driver/common/parameters/values.clj [hunk 1]
```diff
@@ -128,8 +128,10 @@
                                   {:card-id card-id, :tag tag, :type qp.error-type/invalid-parameter})))]
     (try
       (params/map->ReferencedCardQuery
-       (merge {:card-id card-id}
-              (qp/compile (assoc query :parameters params, :info {:card-id card-id}))))
+       (let [query (assoc query :info {:card-id card-id})]
+         (log/tracef "Compiling referenced query for Card %d\n%s" card-id (u/pprint-to-str query))
+         (merge {:card-id card-id}
+                (qp/compile query))))
```
Comment (camsaul) [inline src/metabase/driver/common/parameters/values.clj:134]: This is the actual fix (removing `:parameters params`) but I added extra logging while debugging

File: test/metabase/query_processor_test/parameters_test.clj [hunk 2]
```diff
@@ -223,12 +224,47 @@
...
-                                             :display-name "Cat"
-                                             :type         :dimension
-                                             :dimension    [:field (mt/id :products :category) nil]}}})]
+      (let [query (mt/native-query
+                    {:query         "SELECT count(*) FROM products WHERE {{cat}};"
+                     :template-tags {"cat" {:id           "__MY_CAT__"
+                                            :name         "cat"
+                                            :display-name "Cat"
+                                            :type         :dimension
+                                            :dimension    [:field (mt/id :products :category) nil]}}})]
```
Comment (camsaul) [inline test/metabase/query_processor_test/parameters_test.clj:233]: Unrelated indentation fix

**Review by bshepherdson — APPROVED** [review]
Not sure if a new hire's 👍 counts, but this looks good to me.
