### PR TITLE
Fix: Setting a very high Session Timeout causes instance to stop working

### LINKED ISSUE #25253: Setting a very high Session Timeout causes instance to stop working
**Describe the bug**
Setting a very high Session Timeout causes instance to stop working.

Workaround:
1. Delete the row `setting.key='session-timeout'` in the application database
2. Or define an environment variable to override the setting, e.g `MB_SESSION_TIMEOUT="{\"amount\":24,\"unit\":\"hours\"}"`

**To Reproduce**
1. Go to Admin > Settings > Authentication
3. Enable "Session Timeout" and set it to a very high value like `9999999999 hours`
image
4. Instance is completely broken (the stacktraces thrown are different depending on length of the value), e.g `Field Year cannot be printed as the value 1142817 exceeds the maximum print width of 4` or `java.time.DateTimeException: Invalid value for EpochDay (valid values -365243219162 - 365241780471): 41666666685907` (unsure how to cause the EpochDay error)

**Expected behavior**
BE validation should make sure that the duration defined works before it is using.
And any existing setting value (or if set via envvar) should be ignored if it will not work.

**Information about your Metabase Installation:**
Tested 1.44.2

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/25253

The bug was caused by trying to format a date so far in the future that it has more than 4 digits in the year.

My solution is to limit the timeout to less than 100 years which seems reasonable. 

Validation is done on the FE and BE. This is how the FE validation error looks to the user:
image

### CODE REVIEW

**Comment by calherries** [comment]
@metabase/core-backend-app The changes in the PR are FE only, but I tagged the team as a reviewer because you might have opinions about whether this solution is sufficient. Should validation be handled on the BE as well?

**Comment by calherries** [comment]
> I think we should do the check in BE.

Why? I was looking for this feedback specifically

**Comment by qnkhuat** [comment]
1. The error is from BE, having FE code to prevent BE problem might cause confusion for FE devs.
2. Setting through UI is not the only way to set a setting. we could set it via env too IIRC([source](https://github.com/metabase/metabase/blob/ngoc-card-custom-list-support-column-selection/src/metabase/models/setting.clj#L462)) . So keeping them in BE will prevent all possible ways of setting that value.

**Comment by calherries** [comment]
True, thanks. I'll validate on the BE too.

File: enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.tsx [hunk 1]
```diff
@@ -33,10 +34,25 @@ interface SessionTimeoutSettingProps {
...
+  // has more than 4 digits (#25253)
+  const momentDuration = moment.duration(
+    value.amount,
+    value.unit as moment.unitOfTime.DurationConstructor,
+  );
+  if (momentDuration.asYears() >= 100) {
+    return t`Timeout must be less than 100 years`;
+  }
+  return null;
+};
```
Comment (kulyk) [inline enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.tsx:55]: Can we cover the validator with unit tests please?

**Review by kulyk — COMMENTED** [review]
FE part looks good to me, would be cool to add some tests though

**Review by ranquild — CHANGES_REQUESTED** [review]
@calherries please add a unit test for the component, e.g. when the user enters an incorrect value and the desired error message is visible.

File: src/metabase/server/middleware/session.clj [hunk 2]
```diff
@@ -356,10 +356,23 @@
...
+                  ;; Otherwise, we could fail to format the expires date if the year
+                  ;; has more than 4 digits (#25253)
+                  (let [{:keys [unit amount]} new-value
+                        days (.toDays (case unit
+                                        "seconds" (t/seconds amount)
+                                        "minutes" (t/minutes amount)
+                                        "hours"  (t/hours amount)))
+                        years (/ days 365.25)]
+                    (assert (< years 100) "Session timeout must be less than 100 years")))
+                (setting/set-value-of-type! :json :session-timeout new-value)))
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:372]: This doesn't really cover the case of someone setting this to something insane if they set it via env var, or handle cases where they set it to something insane before this check was in place. Does it make sense to have some logic in the `:getter` as well to make sure it returns a sane value?

File: test/metabase/server/middleware/session_test.clj [hunk 3]
```diff
@@ -395,6 +395,11 @@
 ;;; ----------------------------------------------------- Session timeout -----------------------------------------------------
 
 (deftest session-timeout-tests
+  (testing "Setting the session timeout should fail if the timeout is more than 100 years"
+    (is (thrown-with-msg?
+         java.lang.AssertionError
+         #"Session timeout must be less than 100 years"
+         (mw.session/session-timeout! {:unit "hours", :amount (* 101 365 24 60 60)}))))
```
Comment (camsaul) [inline test/metabase/server/middleware/session_test.clj:402]: I think you were trying to test that whether it errors if you set it to 101 years here but `(* 101 365 24 60 60)` hours is 101 * 60 * 60 years, right?

File: src/metabase/server/middleware/session.clj [hunk 4]
```diff
@@ -356,10 +356,23 @@
...
+                  ;; Assert the duration is less than 100 years.
+                  ;; Otherwise, we could fail to format the expires date if the year
+                  ;; has more than 4 digits (#25253)
+                  (let [{:keys [unit amount]} new-value
+                        days (.toDays (case unit
+                                        "seconds" (t/seconds amount)
+                                        "minutes" (t/minutes amount)
+                                        "hours"  (t/hours amount)))
+                        years (/ days 365.25)]
+                    (assert (< years 100) "Session timeout must be less than 100 years")))
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:371]: Shouldn't this error message be i18n'ed with `tru`? What happens when someone tries to set this to something invalid and isn't using English?

File: src/metabase/server/middleware/session.clj [hunk 5]
```diff
@@ -356,10 +356,23 @@
   ;; The amount is nillable.
   (deferred-tru "Time before inactive users are logged out. By default, sessions last indefinitely.")
   :type       :json
-  :default    nil)
+  :default    nil
+  :setter     (fn [new-value]
+                (when (some? new-value)
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:361]: Should we also be checking that the value is positive? It seems like a negative number would cause problems as well.

**Review by camsaul — CHANGES_REQUESTED** [review]
- error messages need to be i18n'ed with `tru`
- We should probably be validating that the `:amount` is positive. There should be tests for this
- We should probably have some logic in the `:getter` to return a sane amount if the value is crazy -- this way we will handle people who set this via env var, or via the config file, or who set it to something insane in the past before this check was in place. There should be tests for this.

**Comment by calherries** [comment]
@kulyk @ranquild I've updated the FE to mirror the BE logic and included unit tests. Let me know if it looks good

File: src/metabase/server/middleware/session.clj (hunk 2 above)
Comment (calherries) [reply src/metabase/server/middleware/session.clj:372]: >  if they set it via env var

I don't think we have any validation for settings set by env vars in general. Perhaps we should add a general validation function property to `defsetting`, so env vars can be validated with the same logic as the setter?

> or handle cases where they set it to something insane before this check was in place.

If they set it to something insanely before this check was in place, then they'd have run into the error this PR fixes and their Metabase instance would be producing errors everywhere. I don't think it's in scope to fix that.

File: test/metabase/server/middleware/session_test.clj (hunk 3 above)
Comment (calherries) [reply test/metabase/server/middleware/session_test.clj]: Yeah, thanks. Updated and added more tests  https://github.com/metabase/metabase/pull/27347/commits/f7d4b9917c7e564f21604d715c622d8fca60f17e

File: src/metabase/server/middleware/session.clj (hunk 5 above)
Comment (calherries) [reply src/metabase/server/middleware/session.clj:361]: Yeah, updated https://github.com/metabase/metabase/pull/27347/commits/53a4854231d1f5331bf18b20350cc24c05860063

File: src/metabase/server/middleware/session.clj (hunk 4 above)
Comment (calherries) [reply src/metabase/server/middleware/session.clj]: Yes thanks, updated https://github.com/metabase/metabase/commit/f7d4b9917c7e564f21604d715c622d8fca60f17e

File: enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.unit.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+    it(`validates ${value.amount} ${value.unit} correctly`, () => {
+      const setting = { value: value, key: "...", default: "..." };
+      render(<SessionTimeoutSetting setting={setting} onChange={jest.fn()} />);
+      const input = screen.getByTestId("session-timeout-input");
+      if (expected == null) {
+        expect(screen.queryByText(/Timeout must be/)).toBeNull();
+      } else {
+        expect(screen.queryByText(expected)).not.toBeNull();
+      }
+      cleanup();
```
Comment (kulyk) [inline enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.unit.spec.tsx:51]: AFAIR we don't need to call `cleanup` manually

**Review by kulyk — CHANGES_REQUESTED** [review]
Thanks for adding the tests @calherries 🙏 Left a few comments about testing syntax + some thoughts about the validator code itself

File: enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.tsx [hunk 7]
```diff
@@ -30,13 +31,22 @@ interface SessionTimeoutSettingProps {
...
 
-const validate = (
-  setting: SessionTimeoutSettingProps["setting"],
-  value: TimeoutValue,
-) =>
-  setting.value == null || value.amount > 0
-    ? null
-    : t`Timeout must be greater than 0`;
+// Returns a string if the timeout value is invalid, null otherwise.
+// It should mirror the validation of the session-timeout setting on the backend.
```
[the remark this answers is not in the document]
Comment (calherries) [reply enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.tsx:35]: Line 35 is absolutely necessary, because this is non-obvious from reading the code. 34 not so much. I can remove 34.

**Comment by calherries** [comment]
@kulyk Thanks for reviewing, can you give it one more look?

**Review by kulyk — APPROVED** [review]
LGTM! Thanks for addressing all the comments, Cal

File: src/metabase/server/middleware/session.clj [hunk 8]
```diff
@@ -356,10 +356,24 @@
...
+                  ;; Assert the duration is less than 100 years and greater than 0.
+                  ;; We need to limit the duration from being too large because
+                  ;; the year of the expires date must be 4 digits (#25253)
+                  (let [{:keys [unit amount]} new-value
+                        days (/ amount (case unit
+                                         "seconds" (* 60 60 24)
+                                         "minutes" (* 60 24)
+                                         "hours"  24))
```
Comment (qnkhuat) [inline src/metabase/server/middleware/session.clj:369]:
```suggestion
                                         "hours"   24))
```
nit.

**Review by qnkhuat — APPROVED** [review]
BE LGTM

**Review by ranquild — APPROVED** [review]

File: test/metabase/server/middleware/session_test.clj [hunk 9]
```diff
@@ -1,24 +1,27 @@
...
-            [metabase.public-settings.premium-features-test :as premium-features-test]
-            [metabase.server.middleware.session :as mw.session]
-            [metabase.test :as mt]
-            [metabase.util.i18n :as i18n]
-            [ring.mock.request :as ring.mock]
-            [toucan.db :as db])
-  (:import clojure.lang.ExceptionInfo
-           java.util.UUID))
+  (:require
+   [cheshire.core :as json]
```
Comment (qnkhuat) [inline test/metabase/server/middleware/session_test.clj:3]: this looks like it needs a space?

File: src/metabase/server/middleware/session.clj (hunk 2 above)
Comment (calherries) [reply src/metabase/server/middleware/session.clj]: @camsaul I've added validation via on the getter fn in this commit for env vars

Let me know if you think this is sufficient
https://github.com/metabase/metabase/pull/27347/commits/dc594c619096059a3c3288f3a402337e1c4305a4

File: test/metabase/server/middleware/session_test.clj (hunk 9 above)
Comment (qnkhuat) [reply test/metabase/server/middleware/session_test.clj:3]: nvm,  one space is correct: https://guide.clojure.style/#sort-requirements-and-imports

File: src/metabase/server/middleware/session.clj [hunk 10]
```diff
@@ -351,21 +351,41 @@
...
   ;; Should be in the form {:amount 60 :unit "minutes"} where the unit is one of "seconds", "minutes" or "hours".
   ;; The amount is nillable.
   (deferred-tru "Time before inactive users are logged out. By default, sessions last indefinitely.")
-  :type       :json
-  :default    nil)
+  :type    :json
+  :default nil
+  :getter  (fn []
+             (let [value (setting/get-value-of-type :json :session-timeout)]
+               (check-session-timeout value)
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:375]: I would rather not effectively brick the instance if someone had previously set a bad value. Wouldn't this make it impossible to log in? 

That's why I was suggesting falling back to some default or something in the better rather than erroring

**Review by camsaul — CHANGES_REQUESTED** [review]
Please don't have the getter throw errors. That will basically brick the instance if someone had set something crazy in the past. Just have the getter log an error and return the default or something like that

**Comment by calherries** [comment]
@camsaul I've changed the getter to return `nil` and print a warning instead of throwing an exception if the amount is invalid. A `nil` `session-timeout` is equivalent to not setting the session timeout at all - which is the default state.

File: src/metabase/server/middleware/session.clj [hunk 11]
```diff
@@ -359,21 +359,46 @@
...
   ;; The amount is nillable.
   (deferred-tru "Time before inactive users are logged out. By default, sessions last indefinitely.")
-  :type       :json
-  :default    nil)
+  :type    :json
+  :default nil
+  :getter  (fn []
+             (let [value (setting/get-value-of-type :json :session-timeout)]
+               (if-let [exception (check-session-timeout value)]
+                 (println (str "WARNING: " (ex-message exception)))
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:387]: Don't use `println` here since people can't configure it

We should probably add some sort of Kondo warning for that

File: test/metabase/server/middleware/session_test.clj [hunk 12]
```diff
@@ -397,7 +397,54 @@
...
+    (testing "Setting the session timeout with env var should work with valid timeouts"
+      (doseq [timeout [{:unit "hours", :amount 1}
+                       {:unit "hours", :amount (dec (* 100 365.25 24))}]]
+        (is (= timeout
+               (set-and-get timeout)))))
+    (testing "Setting the session timeout via the env var should fail if the timeout isn't positive"
+      (doseq [amount [0 -1]
+              :let [timeout {:unit "hours", :amount amount}]]
+        (is (nil? (set-and-get timeout)))
+        (is (= (println-str "WARNING: Session timeout amount must be positive.")
```
Comment (camsaul) [inline test/metabase/server/middleware/session_test.clj:438]: We have a helper called something like `mt/log-messages-for-level` to capture log messages in tests

File: test/metabase/server/middleware/session_test.clj [hunk 13]
```diff
@@ -12,16 +13,15 @@
...
    [metabase.server.middleware.session :as mw.session]
    [metabase.test :as mt]
    [metabase.util.i18n :as i18n]
    [ring.mock.request :as ring.mock]
    [toucan.db :as db])
   (:import
-   (clojure.lang ExceptionInfo)
-   (java.util UUID)))
+   clojure.lang.ExceptionInfo
+   java.util.UUID))
```
Comment (camsaul) [inline test/metabase/server/middleware/session_test.clj:24]: The old way was correct -- see https://stuartsierra.com/2016/clojure-how-to-ns.html#vectors-or-lists-1

File: src/metabase/server/middleware/session.clj (hunk 11 above)
Comment (camsaul) [reply src/metabase/server/middleware/session.clj:387]: At any rate `WARNING` isn't i18n'ed

Comment (camsaul) [reply src/metabase/server/middleware/session.clj:387]: For log messages, it should be i18n'ed with `trs` rather than `tru` -- if the system locale is English but some user has their locale set to French it's going to be confusing for the admin when a bunch of error messages in French start popping up in the logs. You might want to have a separate message for the warning or do this in some other way

File: src/metabase/server/middleware/session.clj [hunk 14]
```diff
@@ -359,21 +359,46 @@
...
+  (when (some? timeout)
+    (let [{:keys [unit amount]} timeout
+          units-in-24-hours (case unit
+                              "seconds" (* 60 60 24)
+                              "minutes" (* 60 24)
+                              "hours"   24)
+          units-in-100-years (* units-in-24-hours 365.25 100)]
+      (cond
+        (not (pos? amount))
+        (Exception. (tru "Session timeout amount must be positive."))
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:374]: Maybe instead of returning Exceptions directly this should just return some sort of error keyword, that way you can i18n it correctly based on whether it's logged or thrown as an Exception

**Review by camsaul — CHANGES_REQUESTED** [review]
- don't use `println` to log warnings -- use `log/warn`
- all parts of the logged warning should be i18n'ed -- don't print part of the error in English and the rest in a different language
- logged errors should be i18n'ed with `trs` (site locale) rather than `tru` (current user locale)
- thrown exceptions for invalid values should have `ex-info` `{:status-code 400}` so the `PUT /api/setting/:key` endpoint will return a 400 rather than a 500 on invalid input

**Comment by calherries** [comment]
@camsaul Thanks for these suggestions, I've addressed them now.

File: src/metabase/server/middleware/session.clj [hunk 15]
```diff
@@ -382,14 +382,22 @@
...
-             (if-let [exception (check-session-timeout new-value)]
-               (throw exception)
-               (setting/set-value-of-type! :json :session-timeout new-value))))
+             (let [error-key (check-session-timeout new-value)]
+               (case error-key
+                 :amount-must-be-positive
+                 (throw (ex-info (tru "Session timeout amount must be positive.") {:status-code 400}))
+                 :amount-must-be-less-than-100-years
+                 (throw (ex-info (tru "Session timeout must be less than 100 years.") {:status-code 400}))
+                 (setting/set-value-of-type! :json :session-timeout new-value)))))
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:400]: This is just a suggestion for future code but here's a different way to structure this code.  

```suggestion
             (when-let [error-key (check-session-timeout new-value)]
               (throw (ex-info (case error-key
                                 :amount-must-be-positive            (tru "Session timeout amount must be positive.")
                                 :amount-must-be-less-than-100-years (tru "Session timeout must be less than 100 years."))
                               {:status-code 400}))
             (setting/set-value-of-type! :json :session-timeout new-value))))
```

I think it has a few benefits

1. The `case` expression would error on an unhandled error type -- the way it's structured now, because `setting/set-value-of-type!` is the fall-thru condition, if you had a typo in one of the error keywords it would go unhandled and nothing would catch it
2. It pushes the `case` statement down to the lowest point it can go and means the `(throw (ex-info ... {:status-code 400}))` doesn't have to be repeated twice
3. The unexceptional normal code path is kept at the top level of the function. It's less cognitive load to read code that is nested less (not a big difference here but over time little differences do add up)

**Review by camsaul — APPROVED** [review]
