### PR TITLE
Markdown support in the pinned items

### LINKED ISSUE #30381: Markdown support in the pinned items
### Describe the bug

Markdown in the pinned items in the collection is rendered as a plain text

### To Reproduce

1. Create a modal with markdown in the description `Awesome description ## header [link](https://metabase.com)`
2. pin this model
3. check how description is rendered

image

### Desired behaviour

- Markdown in description is rendered correctly, but only the first line is shown with ellipses. e.g. `Awesome description…`
- tooltip with the rendered markdown is shown on hover over description

image

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes https://github.com/metabase/metabase/issues/30381

I found the following issues while working on this:
- #31326
- #31327
- #31328

### Description

Adds markdown support in tooltips in pinned items.
- Headings and links are disabled in tooltips (to be consistent with changes in #29890)

### How to verify

1. Create a:
    - Dashboard
    - Model
    - Question
2. Add description to it:
    - markdown with short / long text
    - plain text with short / long text
3. Pin it to a dashboard
4. If it's a question, turn the visualization on and off
5. In the pinned item hover the text description (or description icon) to display the tooltip - it should show markdown without headings and links formatted
6. If there is a description block in the card, it should contain only the first description line with markdown formatting removed

To verify skeletons, check out the description tooltip when card is loading. To keep it in that state forever you can block requests to `api/card/*/query` URL in your developer tools.

#### Before

https://github.com/metabase/metabase/assets/6830683/bf7ba71f-3eed-4a42-8309-8765ad09915b

#### After

https://github.com/metabase/metabase/assets/6830683/d501b58e-32a9-4e1b-a4cb-1f642dda9b70

### CODE REVIEW

File: frontend/src/metabase/lib/markdown/parseMarkdown.tsx [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import ReactDOMServer from "react-dom/server";
```
Comment (ranquild) [inline frontend/src/metabase/lib/markdown/parseMarkdown.tsx:1]: This is not something we'd want to use on the client

**Review by ranquild — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/lib/markdown/parseMarkdown.tsx (hunk 1 above)
Comment (kamilmielnik) [reply frontend/src/metabase/lib/markdown/parseMarkdown.tsx:1]: > This is not something we'd want to use on the client

Why not?

BTW `frontend/src/metabase/static-viz/index.js` already uses it.

> `:first-line` selector seems promising https://caniuse.com/css-first-line

How would we use it?
Keep in mind that:
- [not all CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-line#allowable_properties) can be used with it.
- markdown may contain non-text nodes, e.g. images (see unit tests for it) - if the first node is not a text node `:first-line` won't help

> Instead of doing all the parsing, could you rely on CSS instead? 

I'm open for suggestions but I see nothing wrong with the current approach.

Comment (ranquild) [reply frontend/src/metabase/lib/markdown/parseMarkdown.tsx:1]: Static viz uses it on the server, not in browser

Comment (ranquild) [reply frontend/src/metabase/lib/markdown/parseMarkdown.tsx:1]: As for the explanation why I think it's a problematic approach. `react-dom/server` is a heavy dependency, it relies on the nodejs runtime. It works because we use webpack which polyfills used native nodejs modules, but it seems to be an overkill for a cosmetic change. 

If this task is something that cannot be achieved with a simpler approach, let's start a discussion with product people and see if there are alternatives.

**Review by ranquild — COMMENTED** [review]
Added comments inline

**Review by ranquild — COMMENTED** [review]
@kamilmielnik I think the API can be improved. From the consumer point of view, I want to render `Markdown` and say that I only want to show a single line. Wdyt about that? This way we could also consolidate all markdown related logic in the component folder, and make it more straightforward to use.

File: frontend/src/metabase/lib/markdown/parseMarkdown.tsx (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/lib/markdown/parseMarkdown.tsx:1]: @kamilmielnik tagging again just to make sure you get a notification - I think the new approach from the comment is good

Comment (kamilmielnik) [reply frontend/src/metabase/lib/markdown/parseMarkdown.tsx]: 41e627ef35...d702b570d19da2a29f282dbc577d0bf361d4ad7a

**Comment by kamilmielnik** [comment]
> I think the API can be improved. From the consumer point of view, I want to render Markdown and say that I only want to show a single line. Wdyt about that?

Sorry, I don't follow. Can you please provide some pseudocode to illustrate the idea?

> This way we could also consolidate all markdown related logic in the component folder, and make it more straightforward to use.

I'm not sure if this is a good idea:
- those markdown-related utility functions are not used by those components
- I haven't found a case in `metabase/core/components` where a utility function is exported
- I'd expect general utilities to live in general `utils`/`lib` etc. (think POLA)

File: frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.tsx [hunk 2]
```diff
@@ -44,7 +52,19 @@ const StaticSkeleton = ({
...
+        <SkeletonDescription
+          alwaysShowTooltip={hasMoreDescriptionToShow}
+          placement="bottom"
+          tooltip={
+            <Markdown disallowHeading unstyleLinks>
+              {description}
+            </Markdown>
+          }
+        >
+          {getLeadingText(defaultedDescription)}
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.tsx:65]: @kamilmielnik I think that we parse markdown 2 times with the current API, could that be avoided?

File: frontend/src/metabase/lib/markdown/getLeadingText.ts [hunk 3]
```diff
@@ -0,0 +1,20 @@
+import { parseMarkdown } from "./parseMarkdown";
+import type { Node } from "./types";
+
+export const getLeadingText = (value: string): string => {
```
Comment (ranquild) [inline frontend/src/metabase/lib/markdown/getLeadingText.ts:4]: We don't create a separate module per (utility) function. In this case it would be a single `markdown.ts` module with all the functions in the folder. If you feel doing otherwise I'd recommend starting an RRC and getting approvals first before changing the approach.

File: frontend/src/metabase/lib/markdown/parseMarkdown.tsx [hunk 4]
```diff
@@ -0,0 +1,20 @@
+import type { Options } from "react-markdown/lib/rehype-filter";
+import rehypeFilter from "react-markdown/lib/rehype-filter";
+import remarkGfm from "remark-gfm";
+import remarkParse from "remark-parse";
+import remarkRehype from "remark-rehype";
+import { unified } from "unified";
+
+const REMARK_PLUGINS = [remarkGfm];
+
+export const parseMarkdown = (value: string, options: Options = {}) => {
```
Comment (ranquild) [inline frontend/src/metabase/lib/markdown/parseMarkdown.tsx:10]: I don't see tests for `markdown` functions

File: e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js [hunk 5]
```diff
@@ -241,9 +265,244 @@ describe("scenarios > collection pinned items overview", () => {
       .findByText("Orders, Count, Grouped by Created At (year)")
       .should("exist");
   });
-});
 
-const openRootCollection = () => {
-  cy.visit("/collection/root");
-  cy.wait("@getPinnedItems");
-};
+  describe("scenarios > collection pinned items overview > pinned model description tooltip", () => {
```
Comment (ranquild) [inline e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js:269]: There are no backend calls or browser-specific logic (e.g. something rendering or layout-specific) that we test here, so I think we could (should?) test it in Jest in tests for the affected components.

**Review by ranquild — COMMENTED** [review]
Looks good, left some comments

File: frontend/src/metabase/lib/markdown/parseMarkdown.tsx (hunk 4 above)
Comment (kamilmielnik) [reply frontend/src/metabase/lib/markdown/parseMarkdown.tsx:10]: > I don't see tests for markdown functions

When I try to test `parseMarkdown` which imports `remark-parse` (or any other `remark-*` lib) I get an error because it uses ESM import syntax.
`react-markdown` luckily comes with `min.js` which is [configured to be imported instead](https://github.com/metabase/metabase/blob/master/jest.unit.conf.json#L8) of default ESM.
`remark-*` libs come as pure ESM and if we import them directly into our code, tests fail.

@ranquild any suggestions for this?

File: frontend/src/metabase/lib/markdown/getLeadingText.ts (hunk 3 above)
Comment (kamilmielnik) [reply frontend/src/metabase/lib/markdown/getLeadingText.ts]: a6ffcfff32a790e45d017861fbfb4bab7e47fe6c

File: frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.tsx (hunk 2 above)
Comment (kamilmielnik) [reply frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.tsx:65]: e120c406717db8478c41511ec55e67781c4eadbc

File: frontend/src/metabase/lib/markdown/parseMarkdown.tsx (hunk 4 above)
Comment (kamilmielnik) [reply frontend/src/metabase/lib/markdown/parseMarkdown.tsx]: > any suggestions for this?

I had to enable transformations for these dependencies: 9236735f1b9c659dadaeff24c1d6136b5f0f9951
These are naturally required for unit tests of `PinnedItemCard` anyway.

Comment (kamilmielnik) [reply frontend/src/metabase/lib/markdown/parseMarkdown.tsx]: > I don't see tests for `markdown` functions

d2290e2056803e6f7495e83743b4fb5213bcc541 + fbcc2b9d0817738cbe2ca75649906d6fd2b00e1c

File: e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js (hunk 5 above)
Comment (ranquild) [reply e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js]: There is a **draft** doc that clarifies the part about e2e. It's probably the best I have right now https://www.notion.so/metabase/Shift-the-engineering-quality-strategy-c75e948910654f348ec345c20b7044f6?pvs=4#ca158621ff3a4f92a9d4384fa053e1de

Comment (ranquild) [reply e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js]: In my own words, I'd say that we add e2e tests for:
- any new shape or data coming from the BE
- any flows that involve interacting with the BE **and** processing the response, e.g. updating an entity or something similar
- cross-feature functionality, e.g. something that isn't scoped to a particular area and would require rendering the whole app

**Comment by kamilmielnik** [comment]
@ranquild I've addressed all comments. It's ready for re-review.

**Review by ranquild — COMMENTED** [review]
Responded in Slack

**Comment by kamilmielnik** [comment]
> Responded in Slack

The suggestion in Slack was [this prototype](https://github.com/metabase/metabase/pull/31573).

There are differences in how these 2 approaches will work:

1. This PR: only the first line of markdown will be rendered.
image

2. Suggested approach: all markdown will be rendered.
image

**Comment by kamilmielnik** [comment]
@alxnddr Please see my [comment above](https://github.com/metabase/metabase/pull/31251#issuecomment-1592773212).

I believe this was Alexander's last remark/suggestion for this PR.
After thinking it through I don't think it's worth doing - the behavior would be affected negatively.
Also it does not feel like we'd gain much (we wouldn't need to add `metabase/lib/markdown.ts`) given the effort and aforementioned consequence.

**Review by alxnddr — COMMENTED** [review]
@kamilmielnik I tried Alexander's approach and it worked correctly for me, and codewise looks more concise without adding new packages. How can I repro the issue you pointed out to? Is it solvable by `white-space: pre`?
Screen Shot 2023-06-15 at 3 18 17 PM

**Comment by kamilmielnik** [comment]
> Is it solvable by `white-space: pre`?

`pre` breaks ellipsis but `pre-line` does the job, thank you!
Ready for review @alxnddr.

File: frontend/src/metabase/dashboard/containers/DashboardHeader.jsx [hunk 6]
```diff
@@ -440,6 +440,7 @@ class DashboardHeader extends Component {
             <DashboardHeaderButton
               icon="info"
               isActive={isShowingDashboardInfoSidebar}
+              data-testid="dashboard-header-info-button"
```
Comment (alxnddr) [inline frontend/src/metabase/dashboard/containers/DashboardHeader.jsx:443]: this `data-testid` is unused and in general it is better to assign an `aria-label` to icon buttons

File: frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.styled.tsx [hunk 7]
```diff
@@ -14,9 +15,15 @@ export const SkeletonTitle = styled(Ellipsified)`
   font-weight: bold;
 `;
 
-export const SkeletonDescription = styled(Ellipsified)`
+export const TruncatedMarkdown = styled(Markdown)`
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.styled.tsx:18]: nit: both truncated markdown components look very similar, it would be nice to reduce duplication if possible and makes sense

**Review by alxnddr — APPROVED** [review]
Looks great! Please check out a couple of minor comments before merging

File: frontend/src/metabase/dashboard/containers/DashboardHeader.jsx (hunk 6 above)
Comment (kamilmielnik) [reply frontend/src/metabase/dashboard/containers/DashboardHeader.jsx]: 575c7596f2215397f518010c9b05b84b32dd39b7

File: frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.styled.tsx (hunk 7 above)
Comment (kamilmielnik) [reply frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.styled.tsx]: Extracted `metabase/core/MarkdownPreview` component: f6106ffe4793c35d3e017a4fd6fbe4ce93546b4d + 7bbc68bf716654f19c6b76ba33865e7cdf1b0d69
Requesting re-review as this is the first component that I'm adding.

File: frontend/src/metabase/collections/components/PinnedItemCard/PinnedItemCard.unit.spec.js [hunk 8]
```diff
@@ -110,4 +128,29 @@ describe("PinnedItemCard", () => {
       );
     });
   });
+
+  describe("description", () => {
```
Comment (ranquild) [inline frontend/src/metabase/collections/components/PinnedItemCard/PinnedItemCard.unit.spec.js:132]: I think since this is now handled by `MarkdownPreview` component, we should only have maybe 1 integration test here with a very basic case, and move advanced tests to the component itself

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/collections/components/PinnedItemCard/PinnedItemCard.unit.spec.js (hunk 8 above)
Comment (kamilmielnik) [reply frontend/src/metabase/collections/components/PinnedItemCard/PinnedItemCard.unit.spec.js:132]: 02656114e633871245785e77bf494b836b7bc4d6
