### PR TITLE
XLSX formatting for temporal breakout fields

### LINKED ISSUE #18219: Temporal breakout fields are not formatted in export
**Describe the bug**
If you group a table by a temporal field, XLSX exports will show the raw timestamps instead of the aggregation values, and the column title does not include the unit.

This problem arises because the formatting of these columns is defined by the `:unit` metadata, and isn't actually included in the column's visualization settings. We'll need to write custom logic to convert data in columns with a `:unit` to the appropriate value (unless this already exists somewhere). 

**To Reproduce**
1. Go to the Orders table in the sample dataset
2. Group by `Count` -> `Created at by year` (or any other unit)
3. Export to XLSX and open in Excel/Numbers
4. The `Created At` column will include values like `January 1, 2016, 12:00 AM` rather than `2016`. Furthermore, the column title will not include the unit.

**Expected behavior**
Values and column titles should look the same as they do in Metabase.

**Information about your Metabase Installation:**
Current master

### PR DESCRIPTION
**Pull request by noahmoss**
* Only add time format to the format string if `unit` is in the set of `time-bucketing-units`, or is `nil`.
* Use specific format string overrides for the `:month` unit
* Always use `yyyy` format string for the `:year` unit
* A bit of code & test refactor

Resolves #18219

### CODE REVIEW

File: test/metabase/query_processor/streaming/xlsx_test.clj [hunk 1]
```diff
@@ -110,126 +109,137 @@
...
-
-      (testing "Global localization settings are incorporated with lower precedence than column format settings"
-        (mt/with-temporary-setting-values [custom-formatting {:type/Currency {:currency "EUR",
-                                                                              :currency_in_header false,
-                                                                              :currency_style "code"}}]
-          (is (= "[$EUR] #,##0.00" (format-string {} :type/Price)))
-          (is (= "[$CAD] #,##0.00" (format-string {::mb.viz/currency "CAD"} :type/Price)))
-          (is (= "[$€]#,##0.00"    (format-string {::mb.viz/currency-style "symbol"} :type/Price)))
-          (is (= "#,##0.00"        (format-string {::mb.viz/currency-in-header true} :type/Price))))))
+      (let [price-col {:semantic_type :type/Price, :effective_type :type/Float}]
```
Comment (noahmoss) [inline test/metabase/query_processor/streaming/xlsx_test.clj:112]: Almost all the changes are due to the addition of this binding, which each test passes into `format-string` as the last arg

**Review by dpsutton — APPROVED** [review]
