### PR TITLE
collections in 'analytics' namespace should not be extracted

### LINKED ISSUE #37453: [Serialization] Skip Metabase Analytics and Custom reports collections when exporting content
### Describe the bug

The Metabase analytics collection is a Pro/EE only feature and is automatically added on all instances. We shouldn't serialiaze it.

### To Reproduce

1. export any Pro/EE instance
2. see exported `Metabase Analytics` and `Custom reports` collection

### Expected behavior

Skip these collections

### Logs

_No response_

### Information about your Metabase installation

```JSON
Master
```

### Severity

P1 - exposes paid content

### Additional context

One way to find the `Metabase analytics` collection is by its type=`instance-analytics`, namespace=`analytics` or entity_id (stable across all instances = `vG58R8k-QddHWA7_47umn`)

To find `Custom reports`: namespace=`analytics` and entity_id=`okNLSZKdSxaoG58JSQY54` (note that custom reports has type=null)

### PR DESCRIPTION
**Pull request by sansolovyov**
Resolves #37453

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj [hunk 1]
```diff
@@ -1711,3 +1712,11 @@
                (by-model "Collection" ser)))
         (is (= #{ncard-eid}
                (by-model "Card" ser)))))))
+
+(deftest skip-analytics-collections-test
+  (testing "Collections in 'analytics' namespace should not be extracted, see #37453"
+    (mt/with-empty-h2-app-db
+      (mbc/ensure-audit-db-installed!)
+      (let [ser (extract/extract {:no-settings   true
+                                  :no-data-model true})]
```
Comment (qnkhuat) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj:1721]: I'd have this
```clojure
(testing "sanity check that the audit collection exists"
  (is (true? (t2/exists? :model/Collection :is_audit true))))
```

for document purposes

File: enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj [hunk 2]
```diff
@@ -48,7 +48,9 @@
   [user-id]
   (let [roots (t2/select Collection {:where [:and [:= :location "/"]
                                                   [:or [:= :personal_owner_id nil]
-                                                       [:= :personal_owner_id user-id]]]})]
+                                                       [:= :personal_owner_id user-id]]
+                                                  [:or [:= :namespace nil]
+                                                       [:!= :namespace "analytics"]]]})]
```
Comment (qnkhuat) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:53]: I don't think `[:= :namespace nil]` is necessary, right?

Comment (qnkhuat) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:53]: and could you please update the doc of this function too?

Comment (piranha) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:53]: It is, since `!=` will skip all NULL entries. So it's either that, or using `is distinct from`.

Comment (piranha) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:55]: > and could you please update the doc of this function too?

I can, no probs, but it feels still relevant to me as it is.

Comment (qnkhuat) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:55]: huh, so TIL then!

**Review by qnkhuat — APPROVED** [review]
LGTM
