### PR TITLE
nest-query explicitly adds all fields to the query

### LINKED ISSUE #57784: Bigquery STRUCT types break in the GUI for combination of custom expression and custom column
### Describe the bug

Seems to be related to this issue https://github.com/metabase/metabase/issues/55562 cause that one fixed a lot but some areas still break

### To Reproduce

You need to connect to bigquery and create a sample Table and Data containing STRUCT:

```
CREATE OR REPLACE TABLE my_project.my_dataset.dictionary (
  word_id INT64,
  details STRUCT<
    frequency INT64,
    length INT64,
    popularity_score FLOAT64
  >
);

INSERT INTO my_project.my_dataset.dictionary (word_id, details)
VALUES
  (1, STRUCT(1200, 11, 8.7)),
  (2, STRUCT(800, 9, 7.4)),
  (3, STRUCT(1500, 10, 9.2));
```

Then sync to metabase. JSON unfolding is enabled by default for Bigquery

Go to New Question -> Dictionary -> Custom Column -> `Frequency * 100` -> Name it Test

Image

Custom Expression -> `CountIf([ Frequency] > 1)` -> Group by Test

Image

Run and see the error:

Image

```
400 Bad Request POST https://bigquery.googleapis.com/bigquery/v2/projects/senseful-cl-mb/queries { "code": 400, "errors": [ { "domain": "global", "location": "q", "locationType": "parameter", "message": "Unrecognized name: frequency at [2:49]", "reason": "invalidQuery" } ], "message": "Unrecognized name: frequency at [2:49]", "status": "INVALID_ARGUMENT" }
```

### Expected behavior

The query runs similar to other Data Types

### Logs

[84c833ef-5264-4c2f-97a3-ca7d33758095] 2025-05-09T18:05:36+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: 400 Bad Request
POST https://bigquery.googleapis.com/bigquery/v2/projects/senseful-cl-mb/queries
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Unrecognized name: frequency at [2:49]",
      "reason": "invalidQuery"
    }
  ],
  "message": "Unrecognized name: frequency at [2:49]",
  "status": "INVALID_ARGUMENT"
}
{:database_id 11,
 :parameterized false,
 :started_at #t "2025-05-09T16:05:35.275259002Z[GMT]",
 :via
 [{:status :failed,
   :class com.google.cloud.bigquery.BigQueryException,
   :error "Unrecognized name: frequency at [2:49]",
   :stacktrace
   ["com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:116)"
    "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:792)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1374)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1371)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:102)"
    "com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)"
    "com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)"
    "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1370)"
    "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1358)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__138340.invoke(bigquery_cloud_sdk.clj:604)"]}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query: Unrecognized name: frequency at [2:49]",
   :stacktrace
   ["--> driver.bigquery_cloud_sdk$throw_invalid_query.invokeStatic(bigquery_cloud_sdk.clj:474)"
    "driver.bigquery_cloud_sdk$throw_invalid_query.invoke(bigquery_cloud_sdk.clj:473)"
    "driver.bigquery_cloud_sdk$handle_bigquery_exception.invokeStatic(bigquery_cloud_sdk.clj:495)"
    "driver.bigquery_cloud_sdk$handle_bigquery_exception.invoke(bigquery_cloud_sdk.clj:482)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:622)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:590)"
    "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_138422__138423$thunk__138424.invoke(bigquery_cloud_sdk.clj:636)"
    "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_138422__138423.invokeStatic(bigquery_cloud_sdk.clj:643)"
    "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_138422__138423.invoke(bigquery_cloud_sdk.clj:626)"
    "driver.bigquery_cloud_sdk$fn__138428.invokeStatic(bigquery_cloud_sdk.clj:658)"
    "driver.bigquery_cloud_sdk$fn__138428.invoke(bigquery_cloud_sdk.clj:650)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:52)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:39)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:102)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:95)"
    "query_processor.execute$run.invokeStatic(execute.clj:62)"
    "query_processor.execute$run.invoke(execute.clj:56)"
    "query_processor.middleware.update_used_cards$update_used_cards_BANG_76080__76081$fn__76082.invoke(update_used_cards.clj:63)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__76185.invoke(execute.clj:25)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__76191.invoke(execute.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76030.invoke(cache.clj:241)"
    "query_processor.middleware.permissions$check_query_permissions$fn__75795.invoke(permissions.clj:148)"
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__128556$check_download_permissions__128557$fn__128558.invoke(permissions.clj:99)"
    "query_processor.middleware.enterprise$check_download_permissio...

### Information about your Metabase installation

```JSON
1.54 and master
```

### Severity

Not many people use the Struct and is specific to Bigquery but I would classify this as a P1 since it breaks normal functionality

### Additional context

I believe it has to do with this issue https://github.com/metabase/metabase/issues/55562

### PR DESCRIPTION
**Pull request by wzimrin**
closes #57784
Closes https://linear.app/metabase/issue/QUE-1173

### Description

Before, nest-query relied on the preprocessor (specifically, the add-implicit-clauses middleware) to add all possible fields to the newly created inner query (and then removes unnecessary fields later).  However, add-implicit-fields ignores fields with a parent id.  The main user of parent-id is mongo, and mongo doesn't use nest-query, so this usually isn't an issue.  However, bigquery also uses parent-id, and bigquery is a sql driver that uses nest-query.  As a result, nest-query wasn't adding bigquery struct member fields to the inner query, which caused some queries to break.  Now, nest-query explicitly finds all non-sensitive/retired fields (including fields with parent ids) and ensures that they are in the inner query.

### How to verify

1. Set up a bigquery table with a struct field -- dev.struct-test in bigquery-driver-dev works
2. Create a query with a custom column and a summarize block that uses both the custom column and a column from the struct
3. Verify that the inner query in the resulting sql selects the struct column and that the query runs correctly

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/util/nest_query.clj [hunk 1]
```diff
@@ -19,6 +19,24 @@
    [metabase.util :as u]
    [metabase.util.log :as log]))
 
+(defn- all-fields-for-table [table-id]
+  (->> (lib.metadata/fields (qp.store/metadata-provider) table-id)
+       (remove #(#{:sensitive :retired} (:visibility-type %)))
```
Comment (wzimrin) [inline src/metabase/query_processor/util/nest_query.clj:24]: Not sure whether this logic is actually important.  I took it from add-implicit-clauses, but while it isn't connected to the current bug, it seems like it could possibly cause a similar bug when the inner query needs to rely on a sensitive or retired field.

So yeah, on one hand, any fields that aren't needed for the outer query will get removed by nest-query, so adding extra fields should be safe.  On the other hand, I'm assuming that sensitive or required fields can't be selected in the query builder, so we shouldn't need these fields in the first place.  Not sure what that works out to.

File: src/metabase/query_processor/util/nest_query.clj [hunk 2]
```diff
@@ -19,6 +19,24 @@
...
+
+(defn- add-all-fields
+  [{{source-table-id :source-table, :keys [fields]} :query, :as outer-query}]
+  (if source-table-id
+    (let [all-fields (all-fields-for-table source-table-id)
+          existing-fields (into #{} (map second) fields)]
+      (assoc-in outer-query [:query :fields]
+                (into fields
+                      (filter (fn [[_ field-id]]
+                                (not (existing-fields field-id))))
```
Comment (metamben) [inline src/metabase/query_processor/util/nest_query.clj:36]: This looks like a `(remove (comp existing-fields second))`.

File: src/metabase/query_processor/util/nest_query.clj [hunk 3]
```diff
@@ -19,6 +19,24 @@
    [metabase.util :as u]
    [metabase.util.log :as log]))
 
+(defn- all-fields-for-table [table-id]
+  (->> (lib.metadata/fields (qp.store/metadata-provider) table-id)
+       (remove #(#{:sensitive :retired} (:visibility-type %)))
+       (map (fn [field]
+              [:field (u/the-id field) nil]))))
+
+(defn- add-all-fields
```
Comment (metamben) [inline src/metabase/query_processor/util/nest_query.clj:28]: This might be a good place to explain why this function is needed, basically your PR's description.

**Review by metamben — APPROVED** [review]
LGTM
