### PR TITLE
Lift dimensions from nested queries

### LINKED ISSUE #10474: Cannot use Saved Question, when original question uses "Display values"="Use foreign key"
**Describe the bug**
When a field in Admin > Data Model has "Display values"="Use foreign key", then the question cannot be used as Saved Question.
It will just return an error that the foreign table column was not found (depending on database, the error might be different):
`Invalid column name "TITLE"`
`Column "source.TITLE" not found`

**To Reproduce**
Steps to reproduce with Sample Dataset:
1. Go to Admin > Data Model > Sample Dataset > Orders > Product ID :gear: 
2. Change "Display values"="Use foreign key", connected to "Title"
3. Create a QB/Simple question of Orders and save it as "Q1"
4. Create a new question and use the "Q1" in Saved Questions, and run it.
5. Fails with the error: `Column "source.TITLE" not found`

**Information about your Metabase Installation:**
Metabase 0.32.10 (prod) and 0.33.0-RC1 (test)
This used to work in 0.32.9

### PR DESCRIPTION
**Pull request by sbelak**
Fixes a bug where our middleware that added dimension remappings didn't recur into `source-query`s and applies remapping logic to `breakout` clause.

## Notes

* For breakout the code adds both the source and remapped cols to the breakout (analogous to how we do it in `:fields`). This shouldn't change the semantics of the group by and as far as I can tell the FE is happy with this and everything works as expected. 
* While this fixes the bug it strikes me that the overall approach where each piece of middleware that's part of the MBQL processing needs to correctly handle nested queries is quite error prone. It would be better if nested queries were handled recursively by the same code path. Where it potentially gets tricky -- and this is also the cause of some of the messiness in this PR -- is that due to our single pass QP we don't get entire metadata until the full pass which makes recursive combining tricky [but this is of course beyond the scope of this PR]. 
* When `:source-query` is MBQL, we needlessly revert to `:field-value`s in `:cols` loosing field IDs. Again a big change at least in the number of tests we'd need to fix, but would retain much more information and for instance allow this fix to be much more robust as we wouldn't have to mess around with name matching. 

Fixes #10474 and #5600

### CODE REVIEW

**Comment by sbelak** [comment]
Also fixes #5600

File: test/metabase/query_processor_test/remapping_test.clj [hunk 1]
```diff
@@ -93,7 +118,7 @@
            :order-by [[:asc $name]]
            :limit    4})))))
 
-;; Test that we can remap inside an MBQL nested query
```
Comment (sbelak) [inline test/metabase/query_processor_test/remapping_test.clj:96]: either the comment was wrong, or the test

**Comment by camsaul** [comment]
> When `:source-query` is MBQL, we needlessly revert to `:field-values` in `:cols` loosing field IDs. Again a big change at least in the number of tests we'd need to fix, but would retain much more information and for instance allow this fix to be much more robust as we wouldn't have to mess around with name matching.

Totally agree. The way we handle source queries right now is a little hacky and could use some rethinking

**Review by camsaul — APPROVED** [review]
This looks good to me. I'm going to go ahead and merge this so it can go out as part of 0.36.5
