### PR TITLE
Fix EmbedJS/SDK dashboard styles to properly display the EmbedJS branding footer

### LINKED ISSUE #68118: Metabase 58: Embed JS OSS footer banner is visible only after scroll for Dashboard components
### Describe the bug

Metabase 58: Embed JS OSS footer banner is visible only after scroll for Dashboard components

### To Reproduce

We can check it in Embed JS wizard for a dashboard for OSS version

### Expected behavior

We should not have scroll bar when dashboard content is less in height than a parent window, so the footer with banner must be visible

### Logs

_No response_

### Information about your Metabase installation

```JSON
-
```

### Severity

p1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
closes #68118
Fix EmbedJS/SDK dashboard styles to properly display the EmbedJS branding footer

Fixes https://linear.app/metabase/issue/EMB-1187/metabase-58-embed-js-oss-footer-banner-is-visible-only-after-scroll

We had `min-height: 100vw` for Dashboard in SDK/EmbedJS and for EmbedJS it causes issues because it's parent (in an iframe) has  mih="100vh" and grid-template rows `1fr auto` so with `100vh` it behaves wrong.

The fix sets only for Embed JS `min-hight: 100%` to fill the available space according to `1fr`. 
Also PR fixes the empty bottom gap when a footer is not rendered.

image

How to test:
- comment `return null` in `frontend/src/metabase/embedding/embedding-iframe-sdk/components/SdkIframeEmbedRoute.tsx` at line 282
- in OSS version locally, open Embed JS Wizard => dashboard.
- ensure that footer with `metabase logo` visible IF content of a dashboard is less than a page height.
- ensure that footer with `metabase logo` is still scrollable if content of a dashboard is larger in height than a page height

Check case when Embed JS dashboard is added on a page

### CODE REVIEW

**Review by heypoom — APPROVED** [review]
Hmm, is there a way to do this without adding the isEmbeddingEajs condition inside of SDK dashboard directly? I think the principle of EAJS is it should try to use the public-facing API of SDK like just another consumer.

One idea might be to expose a style prop that merges with the minHeight style we have {minHeight, ...style}, so that customers can do something similar by simply passing the style prop.

What do you think?

File: frontend/src/metabase/embedding/embedding-iframe-sdk/components/constants.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+export const DASHBOARD_STYLES = {
```
Comment (npretto) [inline frontend/src/metabase/embedding/embedding-iframe-sdk/components/constants.ts]: Could we try and see if this can be a class? since we already have the css modules file
If we cannot overwrite `minHeight`, then it's gonna be an issue for customers too

**Review by npretto — APPROVED** [review]
