### PR TITLE
Fix static embed card download when param has accentuation

### LINKED ISSUE #49118: Unknown parameter when name label has accentuation - embedded data download
### Describe the bug

Error on download data when the parameter label has accentuation.
Tested on static embedding.

[dbe7ab84-dd27-4f58-83a2-c7201c342f63] 2024-10-24T14:26:09-03:00 DEBUG metabase.server.middleware.log GET /api/embed/dashboard/eyJhbGciOiJIUxxxxxxxxxxx/dashcard/2570/card/2337/xlsx 400 6,9 ms (2 chamadas ao banco de dados) {:metabase-user-id 446} 
"Unknown parameter :nome_do_usuário."

Image

### To Reproduce

1. Create a question
2. Create a dashboard
3. Insert a filter and name it using accentuation like "usuários"
4. Embedded it
5. Try to download the data

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

{
  "browser-info": {
    "language": "pt-BR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2024-10-23",
      "tag": "v1.51.1",
      "hash": "b8178a8"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.1.90+",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/49118

Caused by MS3 of a project #46335, I believe there was a merge conflict when the fix #46250 landed a day before we merged the project PR, so we missed this.

### Description

Restore the fix from #46250 by passing params in `parameters` as a JSON string rather than passing it directly.

I also change question download to use `parameters` like the original fix from #46250, but there's no bug in question downloads as we can't seem to create a parameter with accentuation unlike dashboard parameters.

### How to verify

Follow the repro step from #49118

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/redux/downloads.ts [hunk 1]
```diff
@@ -206,20 +206,23 @@ const getDatasetParams = ({
       return {
         method: "GET",
         url: `/api/embed/dashboard/${token}/dashcard/${dashcardId}/card/${cardId}/${type}`,
-        params: Urls.getEncodedUrlSearchParams({ ...params, ...exportParams }),
+        params: new URLSearchParams({
+          parameters: JSON.stringify(params),
```
Comment (WiNloSt) [inline frontend/src/metabase/redux/downloads.ts:210]: Restore the fix from https://github.com/metabase/metabase/pull/46250/files#diff-7a0c448475100a29b2d3e28699cf20381b32b5b785fd6e4128966e1620cb3987, but also incorporate change from https://github.com/metabase/metabase/pull/46995/files#diff-7a0c448475100a29b2d3e28699cf20381b32b5b785fd6e4128966e1620cb3987R209

File: frontend/src/metabase/redux/downloads.ts [hunk 2]
```diff
@@ -164,9 +164,9 @@ const getDatasetParams = ({
 }: DownloadQueryResultsOpts): DownloadQueryResultsParams => {
   const cardId = question.id();
 
-  const exportParams = {
-    format_rows: enableFormatting,
-    pivot_results: enablePivot,
+  const exportParams: Record<string, string> = {
+    format_rows: String(enableFormatting),
```
Comment (WiNloSt) [inline frontend/src/metabase/redux/downloads.ts:168]: Since we're spreading this into `URLSearchParams` we need to make the value a string otherwise, TypeScript would complain.

File: frontend/src/metabase/redux/downloads.ts [hunk 3]
```diff
@@ -206,20 +206,23 @@ const getDatasetParams = ({
...
-      // of like ?params=<json-encoded-params-array> like the other endpoints do.
       const params = new URLSearchParams(window.location.search);
-      params.set("format_rows", String(enableFormatting));
-      params.set("pivot_results", String(enablePivot));
+
       return {
         method: "GET",
         url: Urls.embedCard(token, type),
-        params,
+        params: new URLSearchParams({
```
Comment (WiNloSt) [inline frontend/src/metabase/redux/downloads.ts:222]: Restore the fix from https://github.com/metabase/metabase/pull/46250/files#diff-7a0c448475100a29b2d3e28699cf20381b32b5b785fd6e4128966e1620cb3987, but also incorporate change from https://github.com/metabase/metabase/pull/46995/files#diff-7a0c448475100a29b2d3e28699cf20381b32b5b785fd6e4128966e1620cb3987R209

File: frontend/src/metabase/redux/downloads.ts [hunk 4]
```diff
@@ -206,20 +206,23 @@ const getDatasetParams = ({
...
+        }),
       };
     }
 
     if (resource === "question" && token) {
-      // For whatever wacky reason the /api/embed endpoint expect params like ?key=value instead
-      // of like ?params=<json-encoded-params-array> like the other endpoints do.
       const params = new URLSearchParams(window.location.search);
-      params.set("format_rows", String(enableFormatting));
-      params.set("pivot_results", String(enablePivot));
```
Comment (WiNloSt) [inline frontend/src/metabase/redux/downloads.ts:218]: This is set in `...exportParams` instead.

File: e2e/support/helpers/api/createDashboardWithQuestions.ts [hunk 5]
```diff
@@ -16,14 +16,11 @@ export const createDashboardWithQuestions = ({
...
   questions: (NativeQuestionDetails | StructuredQuestionDetails)[];
-  cards?: Partial<Card>[];
-}): Cypress.Chainable<
-  Cypress.Response<{
-    dashboard: Dashboard;
-    questions: Card;
-  }>
-> => {
-  // @ts-expect-error - Cypress typings don't account for what happens in then() here
+  cards?: Partial<DashboardCard>[];
```
Comment (WiNloSt) [inline e2e/support/helpers/api/createDashboardWithQuestions.ts:19]: types were wrong. I used this function inside `e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts`. Without this change, TypeScript would complain

File: e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts [hunk 6]
```diff
@@ -120,6 +127,89 @@ describeWithSnowplowEE(
...
         });
       });
+
+      describe("with dashboard parameters", () => {
+        beforeEach(() => {
+          cy.signInAsAdmin();
+
+          setTokenFeatures("all");
+
+          // Test parameter with accentuation (metabase#49118)
```
Comment (WiNloSt) [inline e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts:137]: I added a generic test, but note that with this specific filter it also test #49118. You can verify by reverting `frontend/src/metabase/redux/downloads.ts` and this test should fail (I already tested that).

File: e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts [hunk 7]
```diff
@@ -120,6 +127,89 @@ describeWithSnowplowEE(
...
+            type: "string/=",
+          });
+          const questionDetails = {
+            name: "Products",
+            query: {
+              "source-table": PRODUCTS_ID,
+            },
+          };
+          createDashboardWithQuestions({
+            // Can't figure out the type if I extracted `dashboardDetails` to a variable.
```
Comment (WiNloSt) [inline e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts:151]: I don't know how to make extracting this to a variable works. I set it `as const` but TypeScript still complained, so I inline the value instead 🤷

File: e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts [hunk 8]
```diff
@@ -120,6 +127,89 @@ describeWithSnowplowEE(
...
+                  },
+                ],
+              },
+            });
+          });
+
+          cy.signOut();
+        });
+
+        it("should be able to download a static embedded dashcard as CSV", () => {
```
Comment (WiNloSt) [inline e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts:183]: The test was basically copied from the version without parameter.

File: e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts [hunk 9]
```diff
@@ -216,6 +306,92 @@ describeWithSnowplowEE(
...
+            {
+              idAlias: "questionId",
+              wrapId: true,
+            },
+          );
+
+          cy.signOut();
+        });
+
+        it("should be able to download a static embedded dashcard as CSV", () => {
```
Comment (WiNloSt) [inline e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts:356]: The test was basically copied from the version without parameter.

File: e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts [hunk 10]
```diff
@@ -216,6 +306,92 @@ describeWithSnowplowEE(
           export_type: "csv",
         });
       });
+
+      describe("with native question parameters", () => {
```
Comment (WiNloSt) [inline e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts:310]: we never had this test before, since I changed the code for question download with parameters I needed to add this test as well. It's not part of the bug though.

File: e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts [hunk 11]
```diff
@@ -216,6 +306,92 @@ describeWithSnowplowEE(
...
+                pageStyle: {
+                  downloads: true,
+                },
+              },
+            );
+          });
+
+          waitLoading();
+
+          main().findByText(value).should("exist");
```
Comment (WiNloSt) [inline e2e/test/scenarios/embedding/embed-resource-downloads.cy.spec.ts:376]: I added this assertion just to make sure we actually pass value to the embed

File: frontend/src/metabase/redux/downloads.ts [hunk 12]
```diff
@@ -206,20 +206,23 @@ const getDatasetParams = ({
       return {
         method: "GET",
         url: `/api/embed/dashboard/${token}/dashcard/${dashcardId}/card/${cardId}/${type}`,
-        params: Urls.getEncodedUrlSearchParams({ ...params, ...exportParams }),
+        params: new URLSearchParams({
+          parameters: JSON.stringify(params),
+          ..._.mapObject(exportParams, value => String(value)),
```
Comment (WiNloSt) [inline frontend/src/metabase/redux/downloads.ts:211]: `exportParams` needs to have values as strings if we want to pass it to `URLSearchParams`

File: frontend/src/metabase/redux/downloads.ts [hunk 13]
```diff
@@ -206,20 +206,23 @@ const getDatasetParams = ({
...
+        }),
       };
     }
 
     if (resource === "question" && token) {
-      // For whatever wacky reason the /api/embed endpoint expect params like ?key=value instead
-      // of like ?params=<json-encoded-params-array> like the other endpoints do.
```
Comment (WiNloSt) [inline frontend/src/metabase/redux/downloads.ts:215]: We also removed this comment in the [original fix](https://github.com/metabase/metabase/pull/46250/files#diff-7a0c448475100a29b2d3e28699cf20381b32b5b785fd6e4128966e1620cb3987)

**Review by npretto — APPROVED** [review]
Reproduced the error on master and confirm that it's fixed on this branch
