### PR TITLE
Only update dashboard cards if their own filter changes

### LINKED ISSUE #25914: Avoid updating dashboard cards unless filter changes
**Describe the bug**
Continuation of #8030. Avoid updating dashboard cards unless filter changes.
Important that the behavior in-app dashboard is also reflected on Public and Embedding, so it doesn't divert in behavior.

**To Reproduce**
1. Question > Sample > Orders - summarize by Count - save as "Q1"
2. Add "Q1" three times to a dashboard, then add two filters and connect first filter to first card, second filter to second card
image
3. Set a value in first filter, only first card is updated - as expected
4. Set a value in second filter (while there's a value in first filter), now both first and second card is updated - instead of just the second card

https://user-images.githubusercontent.com/1447303/195641046-cb9c37bd-8606-4b2f-b995-dae2962ab5e8.mp4

**Information about your Metabase Installation:**
Tested 0.44.4

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes: https://github.com/metabase/metabase/issues/25914

Fixes cards reloading when we change a filter that has not been connected to them.

99.9% of the kudos should go to @swk777 who wrote this PR: https://github.com/metabase/metabase/pull/26783
If there's a way he can be added as a contributor, I'm all in.

### How to Test

1. Question > Sample > Orders - summarize by Count - save as "Q1"
2. Add "Q1" three times to a dashboard, then add two filters and connect first filter to first card, second filter to second card
image
3. Set a value in first filter, only first card is updated - as expected
4. Set a value in second filter (while there's a value in first filter)

Only the second filter should be reloaded.

### CODE REVIEW

File: frontend/src/metabase-lib/queries/utils/card.js [hunk 1]
```diff
@@ -117,24 +117,24 @@ export function applyParameters(
...
       deriveFieldOperatorFromParameter(parameter)?.optionsDefaults;
 
+    const queryParameter = {
+      type,
+      value: normalizeParameterValue(type, value),
+      id: parameter.id,
+    };
+
+    if (options) {
+      queryParameter.options = options;
```
Comment (gusaiani) [inline frontend/src/metabase-lib/queries/utils/card.js:127]: This is the only real change. 

If the options are undefined, don't pass them.

**Review by iethree — APPROVED** [review]
👍
