### PR TITLE
fix funnel tooltip artifacts in safari

### LINKED ISSUE #11005: Funnel chart hovering glitches
Funnel charts have this weird glitch when hovering on macOS/Safari. Not sure how it plays out with other browsers/OSs.

**Logs**

```
[Error] Error: Problem parsing d="MZ"
	(anonymous function) (vendor.bundle.js:1:85724)
	(anonymous function) (vendor.bundle.js:1:91129)
	pe (vendor.bundle.js:1:87392)
	(anonymous function) (vendor.bundle.js:1:91101)
	(anonymous function) (vendor.bundle.js:1:87837)
	(anonymous function) (app-main.bundle.js:5:759008)
	(anonymous function) (app-main.bundle.js:5:759411)
	r (vendor.bundle.js:1:82996)
	(anonymous function) (vendor.bundle.js:1:515815)
	(anonymous function) (vendor.bundle.js:1:515579)
	(anonymous function) (app-main.bundle.js:5:761049)
	V (app-main.bundle.js:5:449984)
	value (app-main.bundle.js:5:739304)
	value (app-main.bundle.js:5:738848)
	value
	(anonymous function) (vendor.bundle.js:1:1241570)
	close (vendor.bundle.js:1:2010040)
	closeAll (vendor.bundle.js:1:730057)
	perform (vendor.bundle.js:1:729556)
	perform (vendor.bundle.js:1:729469)
	w (vendor.bundle.js:1:599819)
	close (vendor.bundle.js:1:598504)
	closeAll (vendor.bundle.js:1:730057)
	perform (vendor.bundle.js:1:729556)
	w (vendor.bundle.js:1:599819)
	w
	closeAll (vendor.bundle.js:1:730057)
	perform (vendor.bundle.js:1:729556)
	e (vendor.bundle.js:1:600160)
	a (vendor.bundle.js:1:798681)
	enqueueSetState (vendor.bundle.js:1:799690)
	(anonymous function) (vendor.bundle.js:1:1062234)
	(anonymous function) (vendor.bundle.js:1:1265923)
	(anonymous function)
	notify (vendor.bundle.js:1:2030403)
	(anonymous function) (vendor.bundle.js:1:2030037)
	(anonymous function)
	(anonymous function) (vendor.bundle.js:1:1265949)
	(anonymous function)
	m (vendor.bundle.js:1:1267971)
	(anonymous function) (app-main.bundle.js:5:83118)
	c (vendor.bundle.js:1:777987)
	(anonymous function) (vendor.bundle.js:1:777779)
	r (app-main.bundle.js:5:79566)
	(anonymous function) (app-main.bundle.js:5:79661)
	promiseReactionJob
[Error] Error: Problem parsing d="MZ"
	(anonymous function) (vendor.bundle.js:1:85724)
	(anonymous function) (vendor.bundle.js:1:91129)
	pe (vendor.bundle.js:1:87392)
	(anonymous function) (vendor.bundle.js:1:91101)
	(anonymous function) (vendor.bundle.js:1:87837)
	(anonymous function) (app-main.bundle.js:5:759008)
	(anonymous function) (app-main.bundle.js:5:759411)
	r (vendor.bundle.js:1:82996)
	(anonymous function) (vendor.bundle.js:1:515815)
	(anonymous function) (vendor.bundle.js:1:515579)
	(anonymous function) (app-main.bundle.js:5:761049)
	V (app-main.bundle.js:5:449984)
	value (app-main.bundle.js:5:739304)
	value (app-main.bundle.js:5:738848)
	value
	(anonymous function) (vendor.bundle.js:1:1241570)
	close (vendor.bundle.js:1:2010040)
	closeAll (vendor.bundle.js:1:730057)
	perform (vendor.bundle.js:1:729556)
	perform (vendor.bundle.js:1:729469)
	w (vendor.bundle.js:1:599819)
	close (vendor.bundle.js:1:598504)
	closeAll (vendor.bundle.js:1:730057)
	perform (vendor.bundle.js:1:729556)
	w (vendor.bundle.js:1:599819)
	w
	closeAll (vendor.bundle.js:1:730057)
	perform (vendor.bundle.js:1:729556)
	e (vendor.bundle.js:1:600160)
	a (vendor.bundle.js:1:798681)
	enqueueSetState (vendor.bundle.js:1:799690)
	(anonymous function) (vendor.bundle.js:1:1062234)
	(anonymous function) (vendor.bundle.js:1:1265923)
	(anonymous function)
	notify (vendor.bundle.js:1:2030403)
	(anonymous function) (vendor.bundle.js:1:2030037)
	(anonymous function)
	(anonymous function) (vendor.bundle.js:1:1265949)
	(anonymous function)
	m (vendor.bundle.js:1:1267971)
	(anonymous function) (app-main.bundle.js:5:1955014)
	value (app-main.bundle.js:5:1962641)
	(anonymous function) (app-main.bundle.js:5:1963014)
	c (vendor.bundle.js:1:777987)
	(anonymous function) (vendor.bundle.js:1:777779)
	r (app-main.bundle.js:5:1961411)
	(anonymous function) (app-main.bundle.js:5:1961506)
	promiseReactionJob
[Error] TypeError: null is not an object (evaluating 'n.offsetHeight')
	value (app-main.bundle.js:5:2060142)
	value (app-main.bundle.js:5:2060322)
	value
	u (vendor.bundle.js:1:9987)
[Error] TypeError: undefined is not an object (evaluating 'n.refs.popover.toggle')
	(anonymous function) (app-main.bundle.js:5:826579)
	(anonymous function) (app-main.bundle.js:5:828199)
```

**To Reproduce**

1. Ask a new question
2. Insert data
```sql
SELECT 'Step1' AS Step, 31159 AS Count UNION ALL 
SELECT 'Step2' AS Step, 28372 AS Count UNION ALL 
SELECT 'Step3' AS Step, 21494 AS Count UNION ALL 
SELECT 'Step4' AS Step, 19317 AS Count UNION ALL 
SELECT 'Step5' AS Step, 12284 AS Count UNION ALL 
SELECT 'Step6' AS Step, 1522 AS Count
```
3. Vizualise as Funnel
4. Move the cursor over it for a while
5. See error

**Screenshots**
Screen Shot 2019-09-27 at 10 54 23 AM

**Expected behavior**

The hovering shouldn't change the color of the chart in any way... 

**Information about your Metabase Installation:**

- Your browser and the version: Safari Version 13.0.1 (14608.2.11.1.11)
- Your operating system: macOS 10.14.6
- Metabase version: v0.33.3 - Built on 2019-09-20

**Severity**

Just annoying

### PR DESCRIPTION
**Pull request by shaunlebron**
Closes #11005

> **I filed a WebKit bug report here:** 🐛
> 
> * bug preview: https://jsbin.com/fapebec/4/edit?html,output
> * bug report: https://bugs.webkit.org/show_bug.cgi?id=257924

### Description

This PR fixes Safari-related rendering artifacts caused by `ChartTooltip` as it moves over `FunnelNormal`.

https://github.com/metabase/metabase/assets/116838/4afd4c77-fc8f-4833-b725-1b9ada39ac91

https://github.com/metabase/metabase/assets/116838/f6363442-0c17-423c-b632-8180492a4dff

Some things I found:

1. Verified that the ChartTooltip was responsible for the artifacts by removing it from the render tree.
2. Adding a background color to `#popover-event-target` fixes the dot trail, but the tooltip hairlines were still showing up (when first creating the query, not after saving).
3. All artifacts disappear when the window size changes, which forces a redraw.
4. Found our internal util function `forceRedraw(element)`.
5. Added a check to only redraw on Desktop Safari.

### How to verify

1.  This depends on [PR #31457](https://github.com/metabase/metabase/pull/31457), so cherry-pick it with this:

    ```
    git cherry-pick -n c91bc16
    ```
3. Open <http://localhost:3000> in Safari
4. New > SQL query > Sample Database
6. Paste query and run:

    ```sql
    SELECT 'Step1' AS Step, 31159 AS Count UNION ALL
    SELECT 'Step2' AS Step, 28372 AS Count UNION ALL
    SELECT 'Step3' AS Step, 21494 AS Count UNION ALL
    SELECT 'Step4' AS Step, 19317 AS Count UNION ALL
    SELECT 'Step5' AS Step, 12284 AS Count UNION ALL
    SELECT 'Step6' AS Step, 1522 AS Count
    ```
7. Visualizations > Funnel
8. Mouse over the Funnel
9. Verify tooltip doesn’t create artifacts.

### Demo

https://github.com/metabase/metabase/assets/116838/3d420950-6186-404a-a759-3b3633a067fb

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/FunnelNormal.jsx [hunk 1]
```diff
@@ -200,8 +202,16 @@ const GraphSection = ({
   onVisualizationClick,
   className,
 }) => {
+  const rootRef = useRef();
+  useLayoutEffect(() => {
+    // In Safari, the ChartTooltip leaves a trail of artifacts over the Funnel component,
+    // which we fix by redrawing this component when the tooltip moves (i.e. when `hovered` changes).
+    if (isDesktopSafari()) {
+      forceRedraw(rootRef.current);
```
Comment (uladzimirdev) [inline frontend/src/metabase/visualizations/components/FunnelNormal.jsx:210]: when I'm not against such solution completely, if it's the only solution, can't we force redraw in any browser?

Comment (shaunlebron) [reply frontend/src/metabase/visualizations/components/FunnelNormal.jsx:210]: Are you requesting this change?  I thought it would be best to not redraw unnecessarily, but given the state of browser apps these days I suppose a single wasteful repaint isn’t a big deal.

Comment (alxnddr) [reply frontend/src/metabase/visualizations/components/FunnelNormal.jsx:210]: Forcing redraw on every rerender causes layout thrashing. Wdyt about adding css `will-change: transform` to suggest the browser to use a composite layer for the funnel chart only on safari desktop?

File: frontend/src/metabase/visualizations/components/FunnelNormal.jsx [hunk 2]
```diff
@@ -200,12 +201,17 @@ const GraphSection = ({
   onVisualizationClick,
   className,
 }) => {
+  // Force SVG composite-layer until Safari bug is fixed: https://bugs.webkit.org/show_bug.cgi?id=257924
+  const compositeLayerStyles = isDesktopSafari()
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/FunnelNormal.jsx:205]: It would be a bit more consistent if you created `FunnelNormal.styled.tsx`, created the root element styles like 'const funnelRoot = props => css`...`' where props has `isNarrow`, `isSmall` transfer all the styles from the `div` on line 124, and added `will-change: transform` there

Comment (shaunlebron) [reply frontend/src/metabase/visualizations/components/FunnelNormal.jsx]: Added your commit! Thanks

**Review by alxnddr — APPROVED** [review]

**Comment by marceloboeira** [comment]
that's awesome 💪🏼
