### PR TITLE
Fix race between jobs accessing the search index

### LINKED ISSUE #50978: Insert setting error on master
### Describe the bug

checkout master and starts with an empty db you'll see this error
```
2024-12-06 04:07:13,425 INFO appdb.index :: Dropped 1 stale indexes
2024-12-06 04:07:13,426 WARN models.setting :: Error inserting a new Setting:
 ERROR: duplicate key value violates unique constraint "setting_pkey"
  Detail: Key (key)=(search-engine-appdb-index-state) already exists.
 Assuming Setting already exists in DB and updating existing value.
2024-12-06 04:07:13,439 INFO appdb.index :: Dropped 1 stale indexes
```

### Expected behavior

no warning on startup

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

start normally but still should fix this

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crisptrutski**
Fixes https://github.com/metabase/metabase/issues/50978

TIL that simple jobs run immediately the first time they're scheduled.

### CODE REVIEW

File: src/metabase/search/appdb/index.clj [hunk 1]
```diff
@@ -70,7 +70,7 @@
                            [:in :table_name ["search_index" "search_index_next" "search_index_retired"]]]})))
 
 (defn- sync-metadata [_old-setting-raw new-setting-raw]
-  ;; Oh dear, we get the raw setting. Save a little bit of overhead by no keywordizing the keys.
+  ;; Oh dear, we get the raw setting. Save a little bit of overhead by not converting keys
```
Comment (crisptrutski) [inline src/metabase/search/appdb/index.clj:73]: My grammar plugin is annoying

**Review by sansolovyov — APPROVED** [review]
Ohh! Do you think that's the reason for search setting being in weird state sometimes?

**Comment by crisptrutski** [comment]
Yeah, I was able to reproduce the problem. The locking avoids the conflict, but we'd still do a double initialize hence also delaying the redundant job.
