### PR TITLE
Fix long running queries possibly piling up via auto-refresh

### LINKED ISSUE #12578: Long running queries possibly piling up via auto-refresh
**Describe the bug**
I am not absolutely certain this is a bug, but I have run into it twice now.  I find my postgresql instance running 12 instances of the same query, which happen to be quite slow.

I am theorizing that they came about due to someone having that query on a page with auto-refresh enabled and the query not completing by the time the next auto-refresh occurs.

I was wondering: "is metabase meant to cancel the outstanding query before submitting the next query via auto-refresh?"

**Logs**

**To Reproduce**
1. Create a very long running query (even an infinite one)
2. Put it in a chart/dashboard with auto-refresh
3. Wait for auto-refresh to run a few cycles
4. See queries building up in postgresql

**Expected behavior**
Cancelling outstanding queries on auto-refresh, prior to starting the next one.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 77.0b9 (64-bit)
- Your operating system: debian 10
- Your databases: Postgresql 11.8
- Metabase version: "v0.34.3"
- Metabase hosting environment: DigitalOcean debian 10
- Metabase internal database: Postgresql

**Severity**
I removed the long query so users do not create the conditions that may lead to the issue.
The severity is low.

**Additional context**

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/12578

### Description

Avoid fetching new dashcard when the current dashcard request is still on going

### How to verify

For now follow the repro steps in https://github.com/metabase/metabase/issues/12578

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 1]
```diff
@@ -98,9 +98,8 @@ function isNewAdditionalSeriesCard(card, dashcard) {
 
 const updateLoadingTitle = createThunkAction(
   SET_DOCUMENT_TITLE,
-  () => (dispatch, getState) => {
+  totalCards => (_dispatch, getState) => {
     const loadingDashCards = getLoadingDashCards(getState());
-    const totalCards = loadingDashCards.dashcardIds.length;
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:103]: The only reason `dashcardIds` exist in our redux store is to be used here. I think removing it would make our dashboard reducer easier to understand.

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 2]
```diff
@@ -419,32 +418,54 @@ export const fetchCardData = createThunkAction(
...
-    dispatch(setDocumentTitle(t`0/${promises.length} loaded`));
+    const newLoadingIds = nonVirtualDashcardsToFetch.map(({ dashcard }) => {
+      return dashcard.id;
+    });
+    dispatch(
+      fetchDashboardCardDataSync({
+        currentTime: performance.now(),
+        loadingIds: newLoadingIds,
+      }),
+    );
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:451]: Dispatch a new action to avoid a race condition explained in https://github.com/metabase/metabase/pull/31578/files#r1240203745.

Also, modify the action [not to use `createThunkAction` anymore](https://metaboat.slack.com/archives/C505ZNNH4/p1690449178067109).

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 3]
```diff
@@ -419,32 +418,54 @@ export const fetchCardData = createThunkAction(
...
+    )
       .filter(({ dashcard }) => !isVirtualDashCard(dashcard))
-      .map(({ card, dashcard }) => {
-        dashcardIds.push(dashcard.id);
-        return dispatch(fetchCardData(card, dashcard, options)).then(() => {
-          return dispatch(updateLoadingTitle());
-        });
+      .filter(({ dashcard }) => {
+        if (skipOngoingDashcardRequests) {
+          const loadingIds = getLoadingDashCards(getState()).loadingIds;
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:436]: I deliberately put `loadingIds` here, so it's closer to where it's used. I know calling a function every loop might not be the best practice generally, but in this case, it should be negligible since `getLoadingDashCards` is just getting a value from our redux store, and doesn't involve any expensive calculations.

File: frontend/src/metabase/dashboard/hoc/DashboardControls.jsx [hunk 4]
```diff
@@ -174,6 +174,7 @@ export default ComposedComponent =>
             { preserveParameters: true },
           );
           this.props.fetchDashboardCardData({
+            skipOngoingDashcardRequests: true,
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/hoc/DashboardControls.jsx:177]: This is under `_tickRefreshClock` function. So this new parameter `skipOngoingDashcardRequests` is a way to tell the action that we want to skip fetching new dashcards when we know those dashcards are still being loaded.

The previous name I came up with was `skipLoadingDashcards` as in **to skip the dashcards that are being loaded**, but that's ambiguous since it could be interpreted as **to skip loading any dashcards**

File: frontend/src/metabase/dashboard/reducers.js [hunk 5]
```diff
@@ -372,14 +371,14 @@ const loadingDashCards = handleActions(
...
         return {
           ...state,
-          dashcardIds: loadingIds,
-          loadingIds,
-          loadingStatus: loadingIds.length > 0 ? "running" : "idle",
+          // used for updating documents title. It's used for the number of total request loaded.
+          // dashcardIds: loadingIds,
+          loadingIds: newLoadingIds,
+          loadingStatus: newLoadingIds.length > 0 ? "running" : "idle",
           startTime: loadingIds.length > 0 ? currentTime : null,
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/reducers.js:382]: I still need to figure out how to deal with `startTime` this isn't done yet. `startTime` is used to determine if we want to flag a dashboard slow.

File: frontend/src/metabase/dashboard/reducers.js [hunk 6]
```diff
@@ -406,15 +405,6 @@ const loadingDashCards = handleActions(
         };
       },
     },
-    [SET_LOADING_DASHCARDS_COMPLETE]: {
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/reducers.js:409]: This was added in https://github.com/metabase/metabase/pull/31578/files#r1240203745, and it makes working on the fix harder, so I had to remove it and addressed the linked comment by dispatching `FETCH_DASHBOARD_CARD_DATA` before `FETCH_CARD_DATA` [here](https://github.com/metabase/metabase/pull/32754/files#diff-636074b28010ac8c8f8597b27dc79a72530c430dbfd344340c399de22a1f6c80R446-R451)

**Review by ranquild — COMMENTED** [review]
I think the fix makes sense. I've left some small comments. Please add tests for this fix.

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 7]
```diff
@@ -419,32 +418,54 @@ export const fetchCardData = createThunkAction(
...
+
+        return true;
       });
 
-    dispatch(setDocumentTitle(t`0/${promises.length} loaded`));
+    const newLoadingIds = nonVirtualDashcardsToFetch.map(({ dashcard }) => {
+      return dashcard.id;
+    });
+    dispatch(
+      fetchDashboardCardDataSync({
```
[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/dashboard/actions/data-fetching.js:447]: I was gonna do that, but thought it isn't a pattern we use. Now you mentioned this. I found 80 or so places where we use this style, so it could be good to go.

File: frontend/src/metabase/dashboard/hoc/DashboardControls.jsx (hunk 4 above)
Comment (WiNloSt) [reply frontend/src/metabase/dashboard/hoc/DashboardControls.jsx:177]: Fair, this is only for this particular use case. If in the future, we decide to do the same for other scenarios we can rename it to something else then.

File: frontend/src/metabase/dashboard/hoc/DashboardControls.jsx [hunk 8]
```diff
@@ -174,6 +174,7 @@ export default ComposedComponent =>
             { preserveParameters: true },
           );
           this.props.fetchDashboardCardData({
+            isRefreshing: true,
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/hoc/DashboardControls.jsx:177]: So others also use this. [Ref from Apple doc](https://developer.apple.com/documentation/uikit/uirefreshcontrol/1624844-isrefreshing).

As a side note, naming this option is very refreshing.

File: frontend/src/metabase-types/store/dashboard.ts [hunk 9]
```diff
@@ -56,7 +56,7 @@ export interface DashboardState {
   parameterValues: Record<ParameterId, ParameterValueOrArray>;
 
   loadingDashCards: {
-    dashcardIds: DashCardId[];
+    dashboardId: number | null;
```
Comment (WiNloSt) [inline frontend/src/metabase-types/store/dashboard.ts:59]: This is a new state, used for checking if `loadingIds` are for the dashboard we're loading. This is because this PR introduce a way for dashboard to still have ongoing `loadingIds` while loading other dashcards that aren't in `loadingIds`.

File: frontend/src/metabase/dashboard/reducers.js [hunk 10]
```diff
@@ -372,15 +371,37 @@ const loadingDashCards = handleActions(
       }),
     },
     [FETCH_DASHBOARD_CARD_DATA]: {
-      next: (state, { payload: { currentTime, dashcardIds } }) => {
-        const loadingIds = Array.isArray(dashcardIds) ? dashcardIds : [];
+      next: (state, { payload: { currentTime, loadingIds, dashboardId } }) => {
+        // Loading a new dahsboard e.g. when navigating to a new dashboard
+        if (dashboardId !== state.dashboardId) {
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/reducers.js:376]: Previously, this block isn't needed, because we'll just always replace `loadingIds` with a new set, but with new requirements, there could be a case where we dispatch not all dashcard IDs in a single dashboard. e.g. if a dashboard has dashcard 1 and 2, and 1 is still loading when the refresh interval came, this action will only dispatch 2 in `loadingIds`, but if the new `loadingIds` are for different dashboard, we will keep the previous behavior.

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 11]
```diff
@@ -419,32 +418,69 @@ export const fetchCardData = createThunkAction(
...
-    const promises = getCurrentTabDashboardCards(dashboard, selectedTabId)
-      .filter(({ dashcard }) => !isVirtualDashCard(dashcard))
-      .map(({ card, dashcard }) => {
-        dashcardIds.push(dashcard.id);
-        return dispatch(fetchCardData(card, dashcard, options)).then(() => {
-          return dispatch(updateLoadingTitle());
-        });
+
+    const loadingIds = getLoadingDashCards(getState()).loadingIds;
+    const nonVirtualDashcards = getCurrentTabDashboardCards(
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:428]: Extract from `promises` in the previous version so we could act on this variable.

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 12]
```diff
@@ -419,32 +418,69 @@ export const fetchCardData = createThunkAction(
...
+      dashboard,
+      selectedTabId,
+    ).filter(({ dashcard }) => !isVirtualDashCard(dashcard));
+
+    let nonVirtualDashcardsToFetch = [];
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:433]: Not sure if leaving this `let nonVirtualDashcardsToFetch` (undefined) would better communicate that we will set this value in the if blocks below.

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 13]
```diff
@@ -419,32 +418,69 @@ export const fetchCardData = createThunkAction(
...
+      const newLoadingIds = nonVirtualDashcardsToFetch.map(({ dashcard }) => {
+        return dashcard.id;
       });
 
-    dispatch(setDocumentTitle(t`0/${promises.length} loaded`));
+      dispatch({
+        type: FETCH_DASHBOARD_CARD_DATA,
+        payload: {
+          currentTime: performance.now(),
+          loadingIds: loadingIds.concat(newLoadingIds),
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:448]: When auto-refreshing, we will fetch only dash cards that aren't loaded. So, `newLoadingIds` will not have the same id as in `loadingIds`

Consider the following scenario:
- The first refresh we load card 1 and 2
- card 1 finished, card 2 is still loading
- The second refresh we load only card 1 since card 2 is still loading

In this case `loadingIds` from redux would be `[1]` and `newLoadingIds` would be `[2]`, so we need to send `[1, 2]` in the action so we set loading IDs correctly.

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 14]
```diff
@@ -419,32 +418,69 @@ export const fetchCardData = createThunkAction(
...
+        },
+      });
+    } else {
+      nonVirtualDashcardsToFetch = nonVirtualDashcards;
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:452]: This block basically does the same thing as before.

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 15]
```diff
@@ -419,32 +418,69 @@ export const fetchCardData = createThunkAction(
...
-    // the previous API calls finished.
-    Promise.all(promises).then(() => {
-      dispatch(loadingComplete());
+      dispatch({
+        type: FETCH_DASHBOARD_CARD_DATA,
+        payload: {
+          currentTime: performance.now(),
+          loadingIds: newLoadingIds,
+        },
+      });
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:463]: Dispatch a new action to avoid a race condition explained in https://github.com/metabase/metabase/pull/31578/files#r1240203745.

Also, modify the action [not to use `createThunkAction` anymore](https://metaboat.slack.com/archives/C505ZNNH4/p1690449178067109).

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 16]
```diff
@@ -419,32 +418,69 @@ export const fetchCardData = createThunkAction(
...
+    const promises = nonVirtualDashcardsToFetch.map(({ card, dashcard }) => {
+      return dispatch(fetchCardData(card, dashcard, options)).then(() => {
+        return dispatch(updateLoadingTitle(nonVirtualDashcardsToFetch.length));
+      });
     });
 
-    return { currentTime: performance.now(), dashcardIds };
-  },
-);
+    if (nonVirtualDashcardsToFetch.length > 0) {
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:472]: When `isRefreshing: true`, it's possible that we would not fetch any new dashcards e.g. when all the previous cards are still loading.

I need to nest these lines under the if block otherwise we will dispatch
- `setDocumentTitle`
- `loadingComplete`

which causes our redux state to change to an unintended state.

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/dashboard/actions/data-fetching.js [hunk 17]
```diff
@@ -419,32 +418,69 @@ export const fetchCardData = createThunkAction(
...
+      dispatch(
+        setDocumentTitle(t`0/${nonVirtualDashcardsToFetch.length} loaded`),
+      );
+
+      // TODO: There is a race condition here, when refreshing a dashboard before
+      // the previous API calls finished.
```
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/actions/data-fetching.js:478]: @WiNloSt was this TODO meant to be addressed in this PR? It's in `master` now.
