### PR TITLE
Fix object detail view appearing up on every arrow key

### LINKED ISSUE #30039: Sporadic "we're a little lost..." pop-up when scrolling up and down my query after expanding a row
**Describe the bug**
Random bug where if you scroll up and down (using arrow keys) in the query editor on your query, a `we're a little lost...` pop-up comes. Im just trying to scroll, im not hitting "run".

**Logs**
Couldn't get JS frontend console in time. 

**To Reproduce**
1) create a new sql query (select * from people)
2) run it
3) expand the first row
4) click on the sql query and press the up arrow

**Expected behavior**
When you write a sql query and hit run, and go back to refine the query. You are allowed and no interruption by this weird modal.

**Screenshots/videos**
https://user-images.githubusercontent.com/47357846/231531682-db62837a-edfd-4e5a-be2a-92d49daee0f7.mov

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+0-adhoc..source",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+0-adhoc..source",
    "os.name": "Linux",
    "os.version": "5.4.84",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-07",
      "tag": "v0.46.1-SNAPSHOT",
      "branch": "release-x.46.metabot-alpha",
      "hash": "b96b662"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

THis is just very annoying and messing up screenshares during meetings with the team.

**Additional context**

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/30039
Caused by https://github.com/metabase/metabase/pull/28203

Fixes wrong usages of `useMount` hook where it was expected that the "cleanup" function is executed. 

How to verify:
- I'd suggest reverting the fix and running the e2e test; it should fail. The test should pass with the fix applied.

Before

Screenshot 2023-06-12 at 17 44 28

After

Screenshot 2023-06-12 at 17 44 47

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterFieldSearch.tsx [hunk 1]
```diff
@@ -19,15 +17,15 @@ export const FieldSearch = ({
   const [showSearch, setShowSearch] = useState(false);
   const inputRef = useRef<HTMLInputElement | null>(null);
 
-  useMount(() => {
+  useEffect(() => {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterFieldSearch.tsx:20]: Required change - cleanup function

File: frontend/src/metabase/query_builder/components/view/ViewHeader.jsx [hunk 2]
```diff
@@ -213,12 +213,12 @@ function SavedQuestionLeftSide(props) {
 
   const [showSubHeader, setShowSubHeader] = useState(true);
 
-  useMount(() => {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ViewHeader.jsx:216]: Required change - cleanup function

File: frontend/src/metabase/query_builder/containers/QueryBuilder.jsx [hunk 3]
```diff
@@ -293,12 +293,12 @@ function QueryBuilder(props) {
 
   useMount(() => {
     initializeQB(location, params);
-  }, []);
+  });
 
-  useMount(() => {
+  useEffect(() => {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/containers/QueryBuilder.jsx:298]: Required change - cleanup function

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx [hunk 4]
```diff
@@ -185,12 +185,37 @@ export function ObjectDetailView({
...
+  });
 
-    return () => {
-      window.removeEventListener("keydown", onKeyDown, true);
+  useEffect(() => {
+    if (hasNotFoundError) {
+      return;
+    }
+
+    const onKeyDown = (event: KeyboardEvent) => {
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx:195]: Moves `onKeyDown` to the effect to avoid deps issues.

**Review by uladzimirdev — APPROVED** [review]
I'm approving since it solves the problem, but left a few comments, feel free to ignore them

**Review by oisincoveney — APPROVED** [review]
Tested locally, fix seems to work 🎉

**Review by oisincoveney — APPROVED** [review]
Tested locally, fix seems to work 🎉

File: frontend/src/metabase/query_builder/containers/QueryBuilder.jsx [hunk 5]
```diff
@@ -293,12 +293,12 @@ function QueryBuilder(props) {
...
     window.addEventListener("resize", forceUpdateDebounced);
     return () => window.removeEventListener("resize", forceUpdateDebounced);
-  }, []);
+  });
```
[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/query_builder/containers/QueryBuilder.jsx:301]: @ranquild seems this is still missing on `master`, if we don't add a dependency here this effect will be run every render cycle which I assume isn't what we want.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx (hunk 4 above)
Comment (WiNloSt) [reply frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx:195]: @uladzimirdev If a callback is only used inside the effect itself I think it's too verbose to create it outside the effect with `useCallback`.

Putting that function inside the effect would not only eliminate the need to have it in the dependency array, but also limit the scope of the callback function so its potential of being misused/misunderstood is a lot less, since you can only access the function inside the `useEffect` you will know it will only be used here. In contrast, when putting this callback outside the effect readers need to use an IDE/text search to check where this function is being called to make sure it's only used in the effect, otherwise, they could assume it will be used somewhere else, maybe in the render body.
