### PR TITLE
fix(sdk): Fix static dashboard API

### LINKED ISSUE #43463: Review and refine static dashboard props for embedding SDK
Let's review the props of the static dashboard component to ensure that they're cleaned up and consistent with our expectations. See the [discussion thread](https://metaboat.slack.com/archives/C063Q3F1HPF/p1717150408109729) on Slack.

### PR DESCRIPTION
**Pull request by oisincoveney**
Closes #43463

Changes Static Dashboard props to:
```
type StaticDashboardProps = {
  dashboardId: DashboardId;
  withTitle?: boolean; // = true
  withDownloads?: boolean; // = true
  hiddenParameters?: string[]; // = []
  initialParameterValues?: Query; // = {}
};
```

Also changes `font` usage to use the value from the redux store, rather than a user-passed prop. This will help us with using fonts with global theming.

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx [hunk 1]
```diff
@@ -55,27 +57,29 @@ const _StaticDashboard = ({
     });
 
   const { hasNightModeToggle, isNightMode, onNightModeChange, theme } =
-    useEmbedTheme(options.theme);
+    useEmbedTheme();
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx:60]: Do we show a button to toggle the theme in the embedded static dashboard? Since I see `onNightModeChange` here, but not sure if that is a no-op in this case. (Since we want SDK users to rely on the custom theming, rather than the display theme)

File: enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx [hunk 2]
```diff
@@ -55,27 +57,29 @@ const _StaticDashboard = ({
...
-        theme={theme}
         titled={options.titled}
+        theme={theme}
         isFullscreen={isFullscreen}
         onFullscreenChange={onFullscreenChange}
         refreshPeriod={refreshPeriod}
         onRefreshPeriodChange={onRefreshPeriodChange}
         setRefreshElapsedHook={setRefreshElapsedHook}
+        font={font}
+        bordered={options.bordered}
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx:82]: Is `options.bordered` here a fixed value in this case? Since we don't accept any props for `bordered`

**Review by heypoom — APPROVED** [review]
The new API looks good!

PS. the font is also available via `theme.fontFamily`, but if you want to use the redux store as a source-of-truth that's fine with me too.

File: enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx (hunk 1 above)
Comment (oisincoveney) [reply enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx:60]: If you go fullscreen with the SDK dashboard, there's a toggle for night mode. It's the same behavior as that of public or embedded dashboards, but we can disable the toggle with a flag within `useEmbedTheme`

Comment (oisincoveney) [reply enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx:60]: What do you think? Should we just remove the option for now?

**Review by albertoperdomo — COMMENTED** [review]
I thought  you were going to call it `hiddenParameters` instead of `hideParameters`?

**Comment by oisincoveney** [comment]
> I thought  you were going to call it `hiddenParameters` instead of `hideParameters`?

Yep, I just forgot to update the description. That change is already in the code

**Review by albertoperdomo — APPROVED** [review]
