### PR TITLE
Fix Chinese weekdays localization

### LINKED ISSUE #22871: Chinese weekdays in calendar widget are incorrect
**Describe the bug**
Chinese weekdays in calendar widget are incorrect.
There were several MomentJS adjustments in 43, so likely caused by one of those.
I have no idea what is correct or not, or what the values mean. Someone who understands the difference between the various `zh` dialects should validate it's correct.

**To Reproduce**
1. Account Settings or Admin > Settings > Localization > change language to Chinese
2. Question > Sample > Products - filter by specific date on Created At
image

**Expected behavior**
0.42.4 was correct
image

**Information about your Metabase Installation:**
Tested 0.42.4 thru 0.43.1

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/22871

How to test:
- Get a jar from here https://github.com/metabase/metabase/actions/runs/3009020861
- Run Metabase and complete setup
- Go to Account settings and change your language to Chinese
- New -> Question -> Sample -> Orders
- Filter by `Created At`-> Specific dates
- Make sure text for weekdays is correct (see the following screenshot) and compare it with the screenshot from the issue

Note: I've taken the translations from the previous release where it worked correctly

Screenshot 2022-09-07 at 20 45 34
Screenshot 2022-09-07 at 20 45 42

### CODE REVIEW

File: frontend/src/metabase/components/Calendar.tsx [hunk 1]
```diff
@@ -134,6 +134,7 @@ export default class Calendar extends Component<Props, State> {
   }
 
   renderDayNames() {
+    // translator: weekdays abbreviations
```
Comment (alxnddr) [inline frontend/src/metabase/components/Calendar.tsx:137]: Do translators see comments like that?

**Review by alxnddr — APPROVED** [review]
Great job on learning Chinese

File: frontend/src/metabase/components/Calendar.tsx (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/components/Calendar.tsx:137]: Yep
