### PR TITLE
Avoid unneeded CAST() statements

### LINKED ISSUE #11502: Don't need to cast DATE columns with `date()`
**Bug description**
When segmenting by DATE column resulting SQL query uses date() function even though field is already DATE. This results in a quite slower query, specially if used column is indexed.

**To Reproduce**
1. Go to 'Admin > Data Model > Segment'
2. Create a segment on DATE column for last 30 days
3. Add filter
4. Create new question using newly created segment

**Expected behavior**
If column type is DATE there is no need to do another conversion.

**Information about your Metabase Installation:**
```
"metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-19",
      "tag": "v0.33.6",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": "Europe/Belgrade"
    }
  }
```
We are using MySQL 8.0.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by camsaul**
Should improve SQL performance significantly in situations where we break out by day.

Fixes #11502

#### BEFORE

```sql
-- slow
SELECT cast(my_date AS date)
FROM my_table
GROUP BY cast(my_date AS date)
ORDER BY cast(my_date AS date)
```

#### AFTER 
```sql
-- fast
SELECT my_date
FROM my_table
GROUP BY my_date
ORDER BY my_date
```

#### DETAILS

I added a new `TypedHoneySQLForm` class in `metabase.util.honeysql-extensions` that lets you pass around type information with a HoneySQL form (currently just `:database-type`, although we can add more in the future) and a some new helper functions that make use of this type info. `hx/maybe-cast` will only perform a `cast()` if something isn't already of the type in question; various helper functions like `hx/->date` and `hx/->datetime` now use `maybe-cast`. The SQL QP code now adds type information to the HoneySQL generated from `:field` clauses, so different drivers get this optimization for free.

We can probably leverage this a bit more extensively in the future, especially in BigQuery which has to do a lot of crazy nonsense because `DATETIME` and `TIMESTAMP` cannot be used interchangeably

### CODE REVIEW

File: test/metabase/driver/mysql_test.clj [hunk 1]
```diff
@@ -283,33 +286,44 @@
...
+                       {:breakout [!minute.time]
+                        :order-by [[:asc !minute.time]]
+                        :limit    3})))))
+          (testing "by hour"
+            (is (= (map add-date-fn ["23:00:00Z" "20:00:00Z" "19:00:00Z"])
+                   (mt/rows
+                     (mt/run-mbql-query attempts
+                       {:breakout [!hour.time]
+                        :order-by [[:desc !hour.time]]
+                        :limit    3}))))))))))
```
Comment (camsaul) [inline test/metabase/driver/mysql_test.clj:307]: not specifically related to this fix, but I rewrote this test to use the existing `attempted-murders` dataset instead of creating a new one, which is faster and a lot simpler

**Comment by dpsutton** [comment]
This looks fine to me. One thought: i think we will make our lives drastically easier if we namespace the `{:database-type "date"}` information. Database_type and database-type already exist in fields and having it easier to find usages of the type system flowing rather than just db fields would be quite useful. I'm already feeling this a bit when introducing `:effective_type`. It's hard to figure out `:base_type` is used, inferred in middleware, or just happens to exist on a field. Making this inferred information stand out and easily findable would be a big win with zero cost in my opinion. Especially since we don't seem to use fields as these maps.

**Review by dpsutton — APPROVED** [review]

**Comment by camsaul** [comment]
Good suggestion @dpsutton, went ahead and made those changes.
