### PR TITLE
Fix wrong aggregation field's `base_type`

### LINKED ISSUE #25994: Filtering a Question between specific dates after summarizing by date leads to input error
**Describe the bug**
If I summarize the data by `created` (Date) and then summarize the data by counting the rows - everything works; I can see the SQL code and I can visualize results. However, if I try to filter the summarized created date data between specific dates (`October 7, 2022 and October 8, 2022`), then I get a 404 error on the SQL code and an input error on the visualization: `For input string: "2022-10-07"`. 

**Logs**
Screen Shot 2022-10-18 at 9 32 36 AM
Screen Shot 2022-10-18 at 9 32 54 AM

**To Reproduce**
1. Create Questions > Summarize data by Min of <Date>: Day > Group by userId > Filter Min of <Date>: Day between October 7, 2022 and October 8, 2022
2. View the SQL code (404 Error)
3. Visualize (Input Error - `For input string: "2022-10-07"`)

**Expected behavior**
I expected the summarize data of dates to be filtered between the dates since this is possible to do in SQL. 

**Screenshots**

https://user-images.githubusercontent.com/62862233/196491339-d6ea9c55-3655-46bf-b2b3-015bba79f94a.mov

Screen Shot 2022-10-17 at 5 35 01 PM

**Information about your Metabase Installation:**

- Your browser and the version: Chrome Version 106.0.5249.119 (Official Build) (arm64)
- Your operating system: macOS Monterey Version 12.6
- Your databases: PostgresQL
- Metabase version: v1.44.4 

**Severity**
This blocks one of the charts we want to make causing us to have to use a different platform to get that information.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/25994

### Description

The current `base_type` set from `Aggregation` is for `min` and `max` aggregation functions is plainly wrong. The issue referenced for instance, has the aggregation field as **Min of Created Date**. And the issue was that we say the `base_type` is `type/Float` instead of using the underlying field's `base_type` of `type/DateTime`

#### Documentations confirming that `min` or `max` returns the same type as the input type (some of the databases from [supported databases](https://www.metabase.com/docs/latest/databases/connecting#connecting-to-supported-databases) that I could find their docs):
- [Postgres](https://www.postgresql.org/docs/15/functions-aggregate.html)
- [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#max)
- [Amazon Athena](https://trino.io/docs/current/functions/aggregate.html#min)
    > Functions in Athena engine version 3 are based on Trino. For information about Trino functions, operators, and expressions, see [Functions and operators](https://trino.io/docs/current/functions.html) and the following subsections from the Trino documentation.
- [Presto](https://prestodb.io/docs/current/functions/aggregate.html?highlight=min)
- [Redshift](https://docs.aws.amazon.com/redshift/latest/dg/r_MIN.html#c_Supported_data_types_min)
- [SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/functions/max-transact-sql?view=sql-server-ver16#return-types)
- [Vertica](https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Aggregate/MINAggregate.htm)

### How to verify

There are a couple of ways

1. The unskipped reproduced E2E test is passing (1 test)
2. Follow [Flamber's repro from here](https://github.com/metabase/metabase/issues/25994#issuecomment-1283912610), and your query shouldn't result in any error.

#### Question
image

#### Before result
image

#### After result
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### Note

This is the produced query before the fix which resulted in an error
```json
{
  "type": "query",
  "query": {
    "source-query": {
      "source-table": 1,
      "aggregation": [["min", ["field", 63, { "temporal-unit": "day" }]]],
      "breakout": [["field", 58, null]]
    },
    "filter": [
      "between",
      ["field", "min", { "base-type": "type/Float" }],
      "2016-01-29",
      "2023-02-28"
    ]
  },
  "database": 1,
  "parameters": []
}
```

VS the fixed query

```json
{
  "type": "query",
  "query": {
    "source-query": {
      "source-table": 1,
      "aggregation": [["min", ["field", 63, { "temporal-unit": "day" }]]],
      "breakout": [["field", 58, null]]
    },
    "filter": [
      "between",
      ["field", "min", { "base-type": "type/DateTime" }],
      "2016-01-29",
      "2023-02-28"
    ]
  },
  "database": 1,
  "parameters": []
}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28741)

### CODE REVIEW

File: frontend/src/metabase-lib/Dimension.ts [hunk 1]
```diff
@@ -1472,11 +1472,11 @@ export class AggregationDimension extends Dimension {
 
     const dimension = aggregation.dimension();
     const field = dimension && dimension.field();
-    const { semantic_type } = field || {};
+    const { base_type, semantic_type } = field || {};
     return new Field({
       name: aggregation.columnName(),
       display_name: aggregation.displayName(),
-      base_type: aggregation.baseType(),
+      base_type: base_type ?? aggregation.baseType(),
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/Dimension.ts:1479]: Quoting [the PR description](https://github.com/metabase/metabase/pull/28741#issue-1603298559)
> The current `base_type` set from `Aggregation` is plainly wrong. The issue referenced for instance, has the aggregation field as **Min of Created Date**. And the issue was that we say the `base_type` is `type/Float` instead of using the underlying field's `base_type` of `type/DateTime`

File: frontend/src/metabase-lib/queries/structured/Aggregation.ts [hunk 2]
```diff
@@ -12,7 +12,10 @@ import Metric from "metabase-lib/metadata/Metric";
 import StructuredQuery from "../StructuredQuery";
 import Dimension, { AggregationDimension } from "../../Dimension";
 import MBQLClause from "./MBQLClause";
+
 const INTEGER_AGGREGATIONS = new Set(["count", "cum-count", "distinct"]);
+const ORIGINAL_FIELD_TYPE_AGGREGATIONS = new Set(["min", "max"]);
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/queries/structured/Aggregation.ts:17]: This is from testing that only `min` and `max` will result in the value with the base field's `base_type` other aggregations will always result in a number.

image

File: frontend/src/metabase-lib/queries/structured/Aggregation.ts [hunk 3]
```diff
@@ -134,7 +137,16 @@ export default class Aggregation extends MBQLClause {
...
   baseType() {
     const short = this.short();
-    return INTEGER_AGGREGATIONS.has(short) ? TYPE.Integer : TYPE.Float;
+    if (INTEGER_AGGREGATIONS.has(short)) {
+      return TYPE.Integer;
+    }
+
+    const field = this.dimension()?.field;
+    if (ORIGINAL_FIELD_TYPE_AGGREGATIONS.has(short) && field) {
+      return field.base_type;
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/queries/structured/Aggregation.ts:146]: for `min` and `max` aggregation functions. Uses the base field`s `base_type` instead.

e.g. min(Name) = `type/Text`, min(CreatedAt) = `type/DateTime`, etc.

Comment (ranquild) [reply frontend/src/metabase-lib/queries/structured/Aggregation.ts:146]: what would happen if we simply check for `field != null` and use its `base_type`? would it work, or is there a case where it doesn't?

Comment (WiNloSt) [reply frontend/src/metabase-lib/queries/structured/Aggregation.ts:146]: Yeah, [a unit test fails](https://github.com/metabase/metabase/blob/f71f20e18788f2997a55e8bdafb1a39843d06a13/frontend/test/metabase-lib/lib/Dimension.unit.spec.js#L796-L802) (sorry couldn't find the failed run, I should have done that yesterday, now it's too hard to find). And I think that makes sense, we can't always relying on the `field.base_type`.

Let's say we do **Count Created At** the result field type should be integer still, as stated in the unit test.

Comment (ranquild) [reply frontend/src/metabase-lib/queries/structured/Aggregation.ts:146]: Makes sense, thanks for the detailed explanation

**Review by ranquild — COMMENTED** [review]
@WiNloSt could we add some unit tests to this? I'll also tag people from the QP team because they're rewriting metabase-lib

**Review by bshepherdson — APPROVED** [review]
Makes sense. Thanks for keeping us in the loop.

File: frontend/test/metabase-lib/lib/Dimension.unit.spec.js [hunk 4]
```diff
@@ -801,6 +801,62 @@ describe("Dimension", () => {
           expect(base_type).toBe("type/Integer");
         });
 
+        it.each([
+          {
+            field: ["field", PRODUCTS.CATEGORY.id, null],
```
Comment (WiNloSt) [inline frontend/test/metabase-lib/lib/Dimension.unit.spec.js:806]: use an object-styled parameter in the table so I could refer to their property in the test name.

Screenshot 2023-03-01 at 6 41 59 PM

**Comment by WiNloSt** [comment]
@ranquild unit tests added

**Review by ranquild — APPROVED** [review]
