### PR TITLE
Persist email attachment settings correctly in dashboard subs

### LINKED ISSUE #14117: Results attachment settings for dashboard subscriptions don't persist
This is on master.

**To reproduce**
1. Create a new dashboard and add some questions to it.
2. Make sure you have SMTP set up.
3. Click the sharing and embedding button on your dashboard and click on the create new subscription button and pick Email.
4. Toggle on the attach-results option and pick at least one question whose results you want to attach.
5. Click Done.
6. Click on the subscription again and see that your file attachment settings have been lost.

Here's a gif:

https://share.getcloudapp.com/llunEmmb

### PR DESCRIPTION
**Pull request by tsmacdonald**
[Fixes #14117]

### CODE REVIEW

File: frontend/src/metabase/sharing/components/SharingSidebar.jsx [hunk 1]
```diff
@@ -802,6 +802,9 @@ class SharingSidebar extends React.Component {
                 />
               </div>
             </div>
+            <pre>ID:
```
Comment (kdoh) [inline frontend/src/metabase/sharing/components/SharingSidebar.jsx:805]: I assume this was just for testing?

File: frontend/src/metabase/sharing/components/EmailAttachmentPicker.jsx [hunk 2]
```diff
@@ -20,140 +23,163 @@ export default class EmailAttachmentPicker extends Component {
...
+  }
 
-  updateStateFromCards() {
-    const { cards } = this.props;
-    const { attachmentType } = this.state;
+  componentDidUpdate() {
+    const newState = this.calculateStateFromCards();
+    
+    newState.isEnabled = newState.isEnabled || this.state.isEnabled;
+    if(newState.selectedCardIds.size == 0) newState.selectedAttachmentType = this.state.selectedAttachmentType;
```
Comment (tsmacdonald) [inline frontend/src/metabase/sharing/components/EmailAttachmentPicker.jsx:34]: these two lines especially feel like a hack, but I didn't know what to do about it.

The issue is that if no cards have been selected and the user clicks the ".xls" button, the calculated state is an attachment type of ".csv" (the default—there are no selected cards with `include_xls: true` to say otherwise).

File: frontend/src/metabase/sharing/components/EmailAttachmentPicker.jsx [hunk 3]
```diff
@@ -20,140 +23,163 @@ export default class EmailAttachmentPicker extends Component {
...
+    if (as.size !== bs.size) {
+      return false;
+    }
+    for (let a of as) {
+      if (!bs.has(a)) {
+        return false;
+      }
+    }
+    return true;
+  }
```
Comment (tsmacdonald) [inline frontend/src/metabase/sharing/components/EmailAttachmentPicker.jsx:70]: I was a little shocked I had to write this, but Stack Overflow told me to :shrug:

File: frontend/src/metabase/sharing/components/SharingSidebar.jsx (hunk 1 above)
Comment (tsmacdonald) [reply frontend/src/metabase/sharing/components/SharingSidebar.jsx:805]: yes, good catch, thanks!

File: frontend/src/metabase/sharing/components/EmailAttachmentPicker.jsx (hunk 3 above)
Comment (kdoh) [reply frontend/src/metabase/sharing/components/EmailAttachmentPicker.jsx:75]: Does `_` or maybe `icepick` have some sort of function that we could use instead of writing our own here?

**Review by kdoh — APPROVED** [review]
Still feels a bit more complicated than I'm truly comfortable with but seems to do what it says on the tin.

**Comment by tsmacdonald** [comment]
image
Good call re. using underscore

**Comment by tsmacdonald** [comment]
Will merge once green

**Comment by nemanjaglumac** [comment]
#14117 had `.Reproduced` label, which means there was a Cypress test tied to it. Please, make sure you unskip related tests when fixing an issue by following the instructions provided in each or those repros. For reference, see https://github.com/metabase/metabase/pull/14170.
