### PR TITLE
Don't show CORS settings in OSS/Starter editions

### LINKED ISSUE #68559: 58 release: SDK/Modular embedding CORS input is visible in OSS/Starter
### Describe the bug

SDK/Modular embedding CORS input is visible in OSS/Starter

It should not:
context https://metaboat.slack.com/archives/C063Q3F1HPF/p1768830114406389

### To Reproduce

In OSS/Starter open Embedding settings in Admin UI

### Expected behavior

CORS input should be hidden in OSS/Starter as we don't need tp setup CORS for guest embedding

### Logs

_No response_

### Information about your Metabase installation

```JSON
-
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
closes #68559
Don't show CORS settings in OSS/Starter editions

Context: https://metaboat.slack.com/archives/C063Q3F1HPF/p1768830114406389

This PR removes CORS settings input from OSS/Starter editions. It was already disabled, but this PR completely hides it.

How to verify?
- in OSS and Starter edition open embedding settings in Admin UI and ensure that there's no CORS input

### CODE REVIEW

File: frontend/src/metabase/admin/settings/components/EmbeddingSettings/SharedCombinedEmbeddingSettings/SharedCombinedEmbeddingSettings.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ export function SharedCombinedEmbeddingSettings({
     <>
       <EmbeddingSettingsCard
         title={t`Enable guest embeds`}
-        description={t`A secure way to embed charts and dashboards, without single sign-on, when you don’t want to offer ad-hoc querying or chart drill-through. Enables modular embedding and static embedding.`}
```
Comment (sanex3339) [inline frontend/src/metabase/admin/settings/components/EmbeddingSettings/SharedCombinedEmbeddingSettings/SharedCombinedEmbeddingSettings.tsx:43]: This line was not adjusted in a prev PR, so do it here

**Review by NevRA — APPROVED** [review]
