### PR TITLE
Handle non-JSON native mongo queries 

### LINKED ISSUE #38311: `ObjectId` in filter is transformed to string after conversion to native
### Describe the bug

Conversion of mongo query containing filtering by a `ObjectId` yields pipeline that contains string instead of an oid.

### To Reproduce

1. Use dataset containing `ObjectId` field.
2. Add filtering by that field. (This works on `release-x.48.x` at the time of writing, not on master. See #38242).
3. Convert question to native -- oid is formatted as string.

Pipeline of native query does filtering by string instead of correct oid structure:
- for EJSON v1 shell mode it would be`ObjectId("...")`
- and for EJSON v2 `{"$oid": "..."}`.

### Expected behavior

Native query should contain usable oid representation either in EJSON v1 shell mode or EJSON v2.

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Exercised on `release-x.48.x` but very probably also in master.
```

### Severity

P3

### Additional context

After conversion user would have to modify the filter's value.

### LINKED ISSUE #38469: Consider upgrading the way we handle native query represenation in mongo
While solving the issue #37713, I've opened multiple issues relating to the way we handle mongo native query representation. I believe those issues could be solved together by changing the way we parse `bson` or generate `ejson`. Those issues are:

- #38311,
- #38288,
- #38181.

_Problem_. When we load saved native query, we parse it to array of bson documents in [`mongo.qp/parse-query-string`](https://github.com/metabase/metabase/blob/39fba6166af4e21cf18f120fe7c3fd1b46fed120/modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj#L1372). Then, when add new stages to the query, those are clojure structures. [`/dataset/native/`](https://github.com/metabase/metabase/blob/39fba6166af4e21cf18f120fe7c3fd1b46fed120/src/metabase/api/dataset.clj#L164) then generates json from the query. Newly added stages are transformed correctly. But bson documents from saved query are not.

_Possible solution_. To fix this, we could take advantage of `org.bson` package ejson parsing capabilities. We could either represent queries as ejson v2, which conforms to json rfc. That would make standard json parser sufficient when loading saved queries. Or we could try to generate ejson in mongo driver which would be returned on calls to `/dataset/native`, instead of generating json in the endpoint code.

_Watch for parameters_. It is important to consider how we use native query parameters, while trying to solve those issues as I believe eg. `{{x}}` would not be parseable.

_Usefule references_:
- [ejson v2 doc](https://www.mongodb.com/docs/manual/reference/mongodb-extended-json/),
- [ejson v1 doc](https://www.mongodb.com/docs/manual/reference/mongodb-extended-json-v1/),
- [`org.bson` package API](https://mongodb.github.io/mongo-java-driver/4.11/apidocs/bson/org/bson/package-summary.html).

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/38311
Closes https://github.com/metabase/metabase/issues/38469
Closes https://linear.app/metabase/issue/DRI-140/native-mongo-query-doesnt-display-bson-objectiduuids-correctly

### Description

We currently return native Mongo queries from `/native` as a JSON object. The problem is that not all Mongo queries can be represented as JSON. For example if you filter with an ObjectId or a UUID, we return
```json
{
  "$and": [
    {
      "uuid": "073ab27f-a4e6-4cb9-86c0-c8affe3902b8"
    },
    {
      "_id": "67b8a146113d318d39fc0428"
    }
  ]
}
``` 
which doesn't work when run on Mongo because it does a string comparison instead of ObjectId/UUID comparison. Instead we want to return this:
```
{
  "$and": [
    {
      "uuid": UUID("073ab27f-a4e6-4cb9-86c0-c8affe3902b8")
    },
    {
      "_id": ObjectId("67b8a146113d318d39fc0428")
    }
  ]
}
```
We can do this with a custom Mongo encoder that traverses the query, formats maps and arrays, encodes "normal" values with the usual JSON encoder, and then do custom encoding for the "weird" types like ObjectId and UUID.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Create a Mongo query with an ObjectId or UUID filter
2. Click "View native query"
3. Copy the query as is and run it from a Mongo shell
4. You should get the same results as Metabase

### Demo

https://github.com/user-attachments/assets/7922838a-b2d5-4384-8b56-12f838f15649

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo.clj [hunk 1]
```diff
@@ -505,6 +505,49 @@
...
+         (instance? ObjectId mgo) (encode-object-id mgo)
+         (instance? Binary mgo) (encode-binary mgo)
+         :else (json/encode mgo))))))
+
+(defmethod driver/prettify-native-form :mongo
+  [_driver native-form]
+  (try
+    (encode-mongo native-form)
+    (catch Exception _
+      native-form)))
```
Comment (rileythomp) [inline modules/drivers/mongo/src/metabase/driver/mongo.clj:549]: Should we add a log/something for observability here to let us know something went wrong?

File: test/metabase/driver_test.clj [hunk 2]
```diff
@@ -183,8 +183,12 @@
...
             formatted-query (driver/prettify-native-form :mongo query)]
 
-        (testing "Formatting a non-sql query returns the same query"
-          (is (= query formatted-query)))
+        (testing "Formatting a mongo query returns a JSON-like string"
+          (is (= "[\n  {\n    \"$group\": {\n      \"_id\": {\n        \"created_at\": {\n          \"$let\": {\n            \"vars\": {\n              \"parts\": {\n                \"$dateToParts\": {\n                  \"timezone\": \"UTC\",\n                  \"date\": \"$created_at\"\n                }\n              }\n            },\n            \"in\": {\n              \"$dateFromParts\": {\n                \"timezone\": \"UTC\",\n                \"year\": \"$$parts.year\",\n                \"month\": \"$$parts.month\",\n                \"day\": \"$$parts.day\"\n              }\n            }\n          }\n        }\n      },\n      \"sum\": {\n        \"$sum\": \"$tax\"\n      }\n    }\n  },\n  {\n    \"$sort\": {\n      \"_id\": 1\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": false,\n      \"created_at\": \"$_id.created_at\",\n      \"sum\": true\n    }\n  }\n]"
```
Comment (snoe) [inline test/metabase/driver_test.clj:187]: These big strings could be more readable by splitting into multiple strs and use `str` / `str/join`
```
(str "[\n"
     "  {\n" 
     ...
     "]"
```

File: modules/drivers/mongo/src/metabase/driver/mongo.clj (hunk 1 above)
Comment (snoe) [reply modules/drivers/mongo/src/metabase/driver/mongo.clj:546]: Yes, I think a log/error could be useful here.

**Review by snoe — APPROVED** [review]

File: modules/drivers/mongo/src/metabase/driver/mongo.clj (hunk 1 above)
Comment (lbrdnk) [reply modules/drivers/mongo/src/metabase/driver/mongo.clj:546]: As we expect this to not fail, I think failure should be logged with error level containing just simple notice and debug with more context.

File: test/metabase/driver_test.clj [hunk 3]
```diff
@@ -167,7 +167,7 @@
   (mt/test-drivers (mt/normal-drivers-with-feature :table-privileges)
     (is (some? (driver/current-user-table-privileges driver/*driver* (mt/db))))))
 
-(deftest nonsql-dialects-return-original-query-test
+(deftest mongo-prettify-native-form-test
   (mt/test-driver :mongo
     (testing "Passing a mongodb query through [[driver/prettify-native-form]] returns the original query (#31122)"
```
Comment (lbrdnk) [inline test/metabase/driver_test.clj:172]: I think this testing context should also be removed.

File: test/metabase/driver_test.clj (hunk 2 above)
Comment (lbrdnk) [inline test/metabase/driver_test.clj:187]: I think use of `str` as follows would make this read much easier.
```
(str "something\n"
     "else\n")
```

File: modules/drivers/mongo/test/metabase/driver/mongo_test.clj [hunk 4]
```diff
@@ -930,3 +941,31 @@
...
...      },\n        {\n          \"$expr\": {\n            \"$eq\": [\n              \"$date\",\n              {\n                \"$dateFromString\": {\n                  \"dateString\": \"2025-01-01T12:00Z\"\n                }\n              }\n            ]\n          }\n        },\n        {\n          \"$expr\": {\n            \"$regexMatch\": {\n              \"input\": \"$text\",\n              \"regex\": \"^a\",\n              \"options\": \"i\"\n            }\n          }\n        },\n        {\n          \"mixed_not_uuid\": {\n            \"$ne\": null\n          }\n        },\n        {\n          \"int\": {\n            \"$gte\": 1\n          }\n        },\n        {\n          \"float\": {\n            \"$lt\": 5.5\n          }\n        }\n      ]\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": \"$_id\",\n      \"date\": \"$date\",\n      \"int\": \"$int\",\n      \"float\": \"$float\",\n      \"nested_mixed_not_uuid\": \"$nested_mixed_not_uuid\",\n      \"mixed_not_uuid\": \"$mixed_not_uuid\",\n      \"mixed_uuid\": \"$mixed_uuid\",\n      \"nested_mixed_uuid\": \"$nested_mixed_uuid\",\n      \"text\": \"$text\"\n    }\n  },\n  {\n    \"$limit\": 1048575\n  }\n]"
```
Comment (lbrdnk) [inline modules/drivers/mongo/test/metabase/driver/mongo_test.clj:949]: Same for this line as in my other comment about use of `str`.

**Review by lbrdnk — COMMENTED** [review]
Please see my comments for now. I'll take another look when those are addressed. Also I have one more general question - have you considered using [.toJson](https://mongodb.github.io/mongo-java-driver/5.3/apidocs/bson/org/bson/Document.html#toJson()) with [JsonMode](https://mongodb.github.io/mongo-java-driver/5.3/apidocs/bson/org/bson/json/JsonMode.html) set for outputing shell json strings.

File: modules/drivers/mongo/src/metabase/driver/mongo.clj (hunk 1 above)
Comment (rileythomp) [reply modules/drivers/mongo/src/metabase/driver/mongo.clj:548]: @lbrdnk Let me know if the logs I added are what you had in mind

**Comment by rileythomp** [comment]
> Please see my comments for now. I'll take another look when those are addressed. Also I have one more general question - have you considered using [.toJson](https://mongodb.github.io/mongo-java-driver/5.3/apidocs/bson/org/bson/Document.html#toJson()) with [JsonMode](https://mongodb.github.io/mongo-java-driver/5.3/apidocs/bson/org/bson/json/JsonMode.html) set for outputing shell json strings.

Yeah my initial preference was to use a library like that, see option 2 in this discussion: https://metaboat.slack.com/archives/C07HJBQ9VAN/p1740065425249219

I tried a few different implementations and eventually decided against that approach. Happy to go into more detail but the main reasons were:
* The generated queries aren't formatted, so we'd basically still need to do a traversal with special handling
* With relaxed and extended mode the generated queries return an error when run on a Mongo shell 
* With shell mode the generated queries work but they give a warning when run on a Mongo shell
* Queries with UUIDs were less readable due to using base64 representations

But I'm still open to any thoughts or opinions on this so let me know what you think.

File: modules/drivers/mongo/src/metabase/driver/mongo.clj (hunk 1 above)
Comment (lbrdnk) [reply modules/drivers/mongo/src/metabase/driver/mongo.clj:548]: I think it would be enough for debug log to print the native form and exception. As eg.:
```
(log/debugf e "Query: \n```%s\n```" native-form)
```
Idea was that if debug level is used, both, the debug message but also more severe error message will be printed. If the level was info or error (I think info is the default for this ns) only the error notice would get printed without poisoning the logs with too much detail.

Or to put it a bit differently, if more info was needed for debugging log level could be simply raised.

**Review by lbrdnk — APPROVED** [review]
LGTM. Please see my comment. And thank you for the explanation.
