### PR TITLE
fix(sdk): migrate to custom redux context to allow using the sdk on host apps that use redux

### LINKED ISSUE #51398: Create and use custom redux context on the sdk
Part of https://github.com/metabase/metabase/issues/51397

### PR DESCRIPTION
**Pull request by npretto**
Closes https://github.com/metabase/metabase/issues/51398, which is the first task in https://github.com/metabase/metabase/issues/51397

This PR adds a custom context for redux and only uses is in the sdk, this allows host apps that use redux to use the sdk without crashing because it finds the wrong store.

The [parent  project](https://github.com/metabase/metabase/issues/51397) includes follow up tasks like:
- fixing the `EnterpriseState` type
- fixing the eslint rules to make sure no code can import from `react-redux` directly
- switching the core app to use the custom context too

Tech plan was shared on slack [here](https://metaboat.slack.com/archives/C505ZNNH4/p1734374863986279)

I recommend reviewing watching the [at commits](https://github.com/metabase/metabase/pull/51382/commits)
The second commit was made with a codemod and it's just changing the imports

Codemod used:

codemod.js
```
/* eslint-disable import/no-commonjs */
const { execSync } = require("node:child_process");
const path = require("node:path");
const { run: jscodeshift } = require("jscodeshift/src/Runner");

const filesToExclude = [
  "metabase/lib/redux/custom-context.tsx",
  "metabase/lib/redux/index.ts",
];

// Find all files that import react-redux using grep
function findFilesWithReactReduxImport() {
  // Using a simpler grep pattern that won't confuse the shell
  const grepCommand =
    'grep -r "from.*react-redux" frontend/src enterprise/frontend/src';

  try {
    const output = execSync(grepCommand, { encoding: "utf8" });
    const files = output
      .split("\n")
      .filter(line => line.includes("import"))
      .map(line => {
        const [filePath] = line.split(":");
        return filePath;
      })
      .filter(Boolean); // Remove empty lines

    return files;
  } catch (error) {
    console.error("Error finding files:", error);
    return [];
  }
}

const filesThatImportReactRedux = findFilesWithReactReduxImport();
console.log("Found files:", filesThatImportReactRedux);

async function runTransform() {
  const transformPath = path.resolve("transform.js");

  // Filter out excluded files and prepare paths
  const paths = filesThatImportReactRedux
    .filter(file => !filesToExclude.some(excluded => file.includes(excluded)))
    .map(file => path.resolve(process.cwd(), file));

  const options = {
    dry: false,
    print: true,
    verbose: 1,
    babel: true,
    extensions: "tsx,ts,jsx,js",
    parser: "tsx",
  };

  try {
    const res = await jscodeshift(transformPath, paths, options);
    console.log("Transform completed:", res);

    // Run ESLint on transformed files
    console.log("Running ESLint on transformed files...");
    const filePaths = paths.join(" ");
    try {
      execSync(`yarn eslint --fix ${filePaths}`, {
        stdio: "inherit",
        encoding: "utf8",
      });
      console.log("ESLint fixes applied successfully");

      // Run Prettier on transformed files
      console.log("Running Prettier on transformed files...");
      execSync(`npx prettier --write ${filePaths}`, {
        stdio: "inherit",
        encoding: "utf8",
      });
      console.log("Prettier formatting applied successfully");
    } catch (error) {
      console.error("Error running ESLint/Prettier:", error);
    }
  } catch (error) {
    console.error("Transform failed:", error);
  }
}

runTransform().catch(console.error);
```
transform.js
```
module.exports = function transform(file, api) {
  const j = api.jscodeshift;
  const root = j(file.source);

  // List of imports that should be moved to our custom context
  const importsToMove = ["connect", "useDispatch", "useSelector"];

  // Find all imports from 'react-redux'
  root
    .find(j.ImportDeclaration, {
      source: {
        value: "react-redux",
      },
    })
    .forEach(path => {
      const specifiers = path.node.specifiers;
      const comments = path.node.comments; // Preserve any comments

      // Split specifiers into two groups
      const moveToCustom = [];
      const keepInReactRedux = [];

      specifiers.forEach(spec => {
        if (spec.type === "ImportSpecifier") {
          if (importsToMove.includes(spec.imported.name)) {
            moveToCustom.push(spec);
          } else {
            keepInReactRedux.push(spec);
          }
        }
      });

      // If we have specifiers to move, create a new import for them
      if (moveToCustom.length > 0) {
        const customImport = j.importDeclaration(
          moveToCustom,
          j.stringLiteral("metabase/lib/redux"),
        );

        // If we have specifiers to keep, update the existing import
        if (keepInReactRedux.length > 0) {
          // Keep the original comments on the react-redux import
          path.node.specifiers = keepInReactRedux;
          path.node.comments = comments;

          // Insert the new import after the existing one
          path.insertAfter(customImport);
        } else {
          // If all specifiers are moved, replace the entire import but keep comments
          customImport.comments = comments;
          j(path).replaceWith(customImport);
        }
      }
    });

  return root.toSource({
    quote: "double",
    reuseWhitespace: true,
    useTabs: false,
    lineTerminator: "\n",
  });
};
```

### CODE REVIEW

File: enterprise/frontend/src/metabase-enterprise/redux.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import type { TypedUseSelectorHook } from "react-redux";
+import { createSelectorHook } from "react-redux";
+
+import { MetabaseReduxContext } from "metabase/lib/redux";
+
+// TODO: use the real type after we figure out what it is
```
Comment (npretto) [inline enterprise/frontend/src/metabase-enterprise/redux.ts:6]: It seems like we pass the custom state every time, we have a few `EnterpriseState` types in the code. I'm not sure if this is because all the ee slices are optional because of the plugins/feature tokens.
At the moment, the places where this hooks is used are passing a custom type for the state.

File: enterprise/frontend/src/embedding-sdk/store/use-sdk-selector.ts [hunk 2]
```diff
@@ -17,5 +21,6 @@ export const useSdkSelector: TypedUseSelectorHook<SdkStoreState> = (
     throw new Error(USE_OUTSIDE_OF_CONTEXT_MESSAGE);
   }
 
-  return useSelector(selector, options);
+  // @ts-expect-error -- weird error on the options type
```
Comment (npretto) [inline enterprise/frontend/src/embedding-sdk/store/use-sdk-selector.ts:24]: I couldn't find an easy solution, the resulting hook is typed correct as `TypedUseSelectorHook<SdkStoreState>` so the error shouldn't affect us

File: enterprise/frontend/src/metabase-enterprise/redux.ts (hunk 1 above)
Comment (npretto) [reply enterprise/frontend/src/metabase-enterprise/redux.ts:6]: I actually would love to find a real type so I created https://github.com/metabase/metabase/issues/51400

File: frontend/src/metabase/env.ts [hunk 3]
```diff
@@ -1,15 +1,45 @@
+const tryOrDefault = <T>(fn: () => T, defaultValue: T): T => {
+  try {
+    return fn();
+  } catch (e) {
```
Comment (heypoom) [inline frontend/src/metabase/env.ts:4]: I'm not 100% sure how the property accesses could throw an error, is this because `process.env` could be undefined?

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-usage-problem.ts [hunk 4]
```diff
@@ -17,15 +17,15 @@ export function useSdkUsageProblem({
...
+  const dispatch = useSdkDispatch();
 
   // When the setting haven't been loaded or failed to query, we assume that the
   // feature is _enabled_ first. Otherwise, when a user's instance is temporarily down,
   // their customer would see an alarming error message on production.
   // TODO: replace this with "enable-embedding-sdk" once the settings PR landed.
   const isEnabled = useSetting("enable-embedding") ?? true;
 
-  const hasTokenFeature = useSelector(state => {
+  const hasTokenFeature = useSdkSelector(state => {
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-usage-problem.ts:28]: Just curious, should we always use `useSdkSelector` even when we are not referencing sdk store states? Or is this mostly for consistency.

**Review by heypoom — APPROVED** [review]
Reviewed commits in step 1, 3 and 4 - looks good to me. I haven't reviewed the codemodded commit 2 though as that is too big to review manually, so I'll just trust in codemod. Tips for other reviewers: click on the Commits tab, and use "Next" to go to next commit.

File: frontend/src/metabase/env.ts (hunk 3 above)
Comment (heypoom) [reply frontend/src/metabase/env.ts:4]: I see! It makes sense that the tests doesn't have the env defined as I imagine most of those envs applied to the built bundle, and not the tests itself.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-usage-problem.ts (hunk 4 above)
Comment (npretto) [reply enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-usage-problem.ts:28]: We have a rule for useSdkDispatch: https://github.com/metabase/metabase/blob/09a4f60666594eca8bfd56e235502ca887909445/enterprise/frontend/src/embedding-sdk/.eslintrc#L6-L11
So I updated the import of the selector too for consistency, we should probably add it to the lin rule too

File: frontend/src/metabase/lib/redux/custom-context.tsx [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+  mapStateToProps?: any,
+  mapDispatchToProps?: any,
+  mergeProps?: any,
+  options?: any,
+) => {
+  return ReactRedux.connect(mapStateToProps, mapDispatchToProps, mergeProps, {
+    context: MetabaseReduxContext,
+    ...options,
+  });
+};
```
[the remark this answers is not in the document]
Comment (npretto) [reply frontend/src/metabase/lib/redux/custom-context.tsx:34]: Yep, it's because even if it's typed as `any` it's still considered a require argument and otherwise TS complaints

File: frontend/src/metabase/lib/redux/custom-context.tsx [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+import { createContext } from "react";
+import { Provider, ReactReduxContext } from "react-redux";
+// eslint-disable-next-line no-restricted-imports
+import * as ReactRedux from "react-redux";
+
+import { isEmbeddingSdk } from "metabase/env";
+
+export const MetabaseReduxContext = isEmbeddingSdk
+  ? createContext<any>(null)
+  : ReactReduxContext;
```
[the remark this answers is not in the document]
Comment (npretto) [reply frontend/src/metabase/lib/redux/custom-context.tsx:11]: Exactly, there's another task in the project to find a work around so we can use the custom context in the core app too

File: frontend/src/metabase/lib/redux/custom-context.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (heypoom) [reply frontend/src/metabase/lib/redux/custom-context.tsx:34]: Interesting, I thought `export const connect: typeof ReactRedux.connect = (mapStateToProps, mapDispatchToProps, mergeProps, options) => {...}` would work as the argument types are already inferred. Nevermind then.

**Comment by npretto** [comment]
@metabase-bot backport release-x.51.x
