### PR TITLE
Handle snowflake timeouts

### LINKED ISSUE #55497: New tables/views or fields are not syncing in Snowflake
### Describe the bug

Pending investigation, but seems that new tables or fields are not syncing in Metabase

Snowflake seems to be aware of something similar https://github.com/snowflakedb/snowflake-jdbc/issues/2113

### To Reproduce

TBD

### Expected behavior

Every new entity in snowflake should be in the metabase metadata

### Logs

```
[97c42331-f174-48bb-bdd8-3cd2645d13d6] 2025-03-20T15:19:43-05:00 ERROR metabase.sync.fetch-metadata Error while fetching metdata with 'db-metadata',net.snowflake.client.jdbc.SnowflakeSQLException: Connection has been closed., at net.snowflake.client.jdbc.SnowflakeConnectionV1.raiseSQLExceptionIfConnectionIsClosed(SnowflakeConnectionV1.java:163),                at net.snowflake.client.jdbc.SnowflakeConnectionV1.getAutoCommit(SnowflakeConnectionV1.java:370),      at com.mchange.v2.c3p0.impl.NewProxyConnection.getAutoCommit(NewProxyConnection.java:1509),          at metabase.driver.sql_jdbc.sync.describe_database$fn__81017.invokeStatic(describe_database.clj:91),       at metabase.driver.sql_jdbc.sync.describe_database$fn__81017.invoke(describe_database.clj:75),    at clojure.lang.MultiFn.invoke(MultiFn.java:244),               at metabase.driver.snowflake$fn__111072$fn__111073$fn__111077$fn__111079.invoke(snowflake.clj:588),  at clojure.core$filter$fn__5977$fn__5978.invoke(core.clj:2822),               at clojure.core$take_while$fn__6001$fn__6002.invoke(core.clj:2918),   at clojure.core.protocols$fn__8275.invokeStatic(protocols.clj:167),       at clojure.core.protocols$fn__8275.invoke(protocols.clj:123),    at clojure.core.protocols$fn__8229$G__8224__8238.invoke(protocols.clj:19),  at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31),    at clojure.core.protocols$fn__8262.invokeStatic(protocols.clj:74),          at clojure.core.protocols$fn__8262.invoke(protocols.clj:74),      at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13),  at clojure.core$reduce.invokeStatic(core.clj:6965),          at clojure.core$reduce.invoke(core.clj:6947), at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__80167.reduce(common.clj:39)
[97c42331-f174-48bb-bdd8-3cd2645d13d6] 2025-03-20T15:19:43-05:00 WARN metabase.sync.util Error in sync step Sync metadata for snowflake Database 2 ''Masked (L1)'',net.snowflake.client.jdbc.SnowflakeSQLException: Connection has been closed.,        at net.snowflake.client.jdbc.SnowflakeConnectionV1.raiseSQLExceptionIfConnectionIsClosed(SnowflakeConnectionV1.java:163),                at net.snowflake.client.jdbc.SnowflakeConnectionV1.getAutoCommit(SnowflakeConnectionV1.java:370),      at com.mchange.v2.c3p0.impl.NewProxyConnection.getAutoCommit(NewProxyConnection.java:1509),          at metabase.driver.sql_jdbc.sync.describe_database$fn__81017.invokeStatic(describe_database.clj:91),       at metabase.driver.sql_jdbc.sync.describe_database$fn__81017.invoke(describe_database.clj:75),    at clojure.lang.MultiFn.invoke(MultiFn.java:244),               at metabase.driver.snowflake$fn__111072$fn__111073$fn__111077$fn__111079.invoke(snowflake.clj:588),  at clojure.core$filter$fn__5977$fn__5978.invoke(core.clj:2822),               at clojure.core$take_while$fn__6001$fn__6002.invoke(core.clj:2918),   at clojure.core.protocols$fn__8275.invokeStatic(protocols.clj:167),       at clojure.core.protocols$fn__8275.invoke(protocols.clj:123),    at clojure.core.protocols$fn__8229$G__8224__8238.invoke(protocols.clj:19),  at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31),    at clojure.core.protocols$fn__8262.invokeStatic(protocols.clj:74),          at clojure.core.protocols$fn__8262.invoke(protocols.clj:74),      at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13),  at clojure.core$reduce.invokeStatic(core.clj:6965),          at clojure.core$reduce.invoke(core.clj:6947), at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__80167.reduce(common.clj:39)
```

### Information about your Metabase installation

```JSON
53.x
```

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes: https://github.com/metabase/metabase/issues/55497

We are running a probe query on snowlfake to see if the current db user can see views

```
select true from X where 1 <> 1 limit 0
```

Something like this.

But on large views, it seems snowflake does not quickly determine this has no rows and it can take a while.

This leads to the connection being closed. Then in the error handler we attempt to rollback. But if the connection is closed _this_ throws and we have now thrown from the error handler and we break sync.

This does two things
1. set a timeout on sql statements. This does 10 seconds.
2. If a timeout occurs, assume that they _can_ see the object

The idea is that timeouts might happen but it's trying to run a query that it would quickly reject if the permissions were lacking. So timeouts mean you can see the data, it's just taking a while

### CODE REVIEW

**Review by lbrdnk — APPROVED** [review]
LGTM

File: src/metabase/driver/sql_jdbc/sync/describe_database.clj [hunk 1]
```diff
@@ -70,7 +70,9 @@
     ;; attempting to execute the SQL statement will throw an Exception if we don't have permissions; otherwise it will
     ;; truthy wheter or not it returns a ResultSet, but we can ignore that since we have enough info to proceed at
     ;; this point.
-    (.execute stmt)))
+    (doto stmt
+      (.setQueryTimeout 10)
```
Comment (snoe) [inline src/metabase/driver/sql_jdbc/sync/describe_database.clj:74]: What happens if this throws a NotImplementedException?

**Review by snoe — APPROVED** [review]

File: src/metabase/driver/sql_jdbc/sync/describe_database.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/driver/sql_jdbc/sync/describe_database.clj]: from @snoe :

Looking at the docs, I think they MUST implement https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#setQueryTimeout-int- vs https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#cancel--

we feel comfortable relying on these being implemented.
