### PR TITLE
Reject invalid queries for admins on impersonated DBs

### LINKED ISSUE #72858: I get an "Encountered unexpected token:<EOF>" when running a query which makes the page crash
**Describe the bug**
My colleague gets an "Encountered unexpected token:<EOF>" when running a query which makes the page crash. I can see it in the logs but it doesn't seem to appear every time.

**Logs**

```
[1385282c-bd24-420e-a628-a00658d06eff] 2026-04-20T15:56:20+08:00 WARN metabase.driver.sql Failed to parse native query: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token:<EOF>
    at line 168, column 1.

Was expecting one of:

    "("
    "ALTER"
    "ANALYZE"
    "BEGIN"
    "CALL"
    "COMMENT"
    "COMMIT"
    "CREATE"
    "DECLARE"
    "DELETE"
    "DESC"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "GRANT"
    "IF"
    "INSERT"
    "MERGE"
    "PURGE"
    "REFRESH"
    "RENAME"
    "REPLACE"
    "RESET"
    "ROLLBACK"
    "SAVEPOINT"
    "SET"
    "SHOW"
    "TABLE"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUE"
    "VALUES"
    "WITH"
    <K_SELECT>
    <ST_SEMICOLON>

: Query: with
    enterprise_start as (
        select
            organization_uuid_v4,
            min(hierarchy_started_at)::date as enterprise_started_at
        from sonar.dim_sc_organization_enterprise
        where organization_uuid_v4 is not null
        group by 1
    ),

    org_created as (
        select
            organization_uuid_v4,
            min(creation_date)::date as org_created_at
        from sonar.fct_sc_organization
        where organization_uuid_v4 is not null
        group by 1
    ),

    contract_anchor as (
        select
            o.organization_uuid_v4,
            date_trunc('month', coalesce(e.enterprise_started_at, o.org_created_at))::date as contract_start_month
        from org_created as o
        left join enterprise_start as e
            on o.organization_uuid_v4 = e.organization_uuid_v4
    ),

    eligible_orgs as (
        select
            organization_uuid_v4,
            contract_start_month
        from contract_anchor
        where
            dateadd(month, 6, contract_start_month) <= date_trunc('month', current_date)
    ),

    monthly_snapshot_raw as (
        select
            e.organization_uuid_v4,
            e.contract_start_month,
            date_trunc('month', f.data_timestamp)::date as activity_month,
            f.data_timestamp,
            f.enterprise_uuid,
            f.nb_of_active_users,
            f.nb_of_active_projects,
            f.nb_of_ncloc
        from eligible_orgs as e
        inner join sonar.fct_sc_organization as f
            on f.organization_uuid_v4 = e.organization_uuid_v4
        where
            date_trunc('month', f.data_timestamp)::date >= e.contract_start_month
            and date_trunc('month', f.data_timestamp)::date < dateadd(month, 6, e.contract_start_month)
    ),

    monthly_snapshot_ranked as (
        select
            msr.*,
            row_number() over (
                partition by msr.organization_uuid_v4, date_trunc('month', msr.data_timestamp)::date
                order by msr.data_timestamp desc
            ) as _rno
        from monthly_snapshot_raw as msr
    ),

    monthly_snapshot as (
        select
            organization_uuid_v4,
            contract_start_month,
            activity_month,
            data_timestamp,
            enterprise_uuid,
            nb_of_active_users,
            nb_of_active_projects,
            nb_of_ncloc
        from monthly_snapshot_ranked
        where _rno = 1
    ),

    monthly_deltas as (
        select
            organization_uuid_v4,
            contract_start_month,
            activity_month,
            nb_of_active_users,
            nb_of_active_projects,
            greatest(
                nb_of_active_users
                - coalesce(
                    lag(nb_of_active_users) over (
                        partition by organization_uuid_v4
                        order by activity_month
                    ),
                    nb_of_active_users
                ),
                0
            ) as active_users_added,
            greatest(
                nb_of_active_projects
                - coalesce(
                    lag(nb_of_active_projects) over (
                        partition by organization_uuid_v4
                        order by activity_month
                    ),
                   ...
[1385282c-bd24-420e-a628-a00658d06eff] 2026-04-20T15:56:20+08:00 WARN metabase.driver.sql Failed to parse native query: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token:<EOF>
    at line 168, column 1.

Was expecting one of:

    "("
    "ALTER"
    "ANALYZE"
    "BEGIN"
    "CALL"
    "COMMENT"
    "COMMIT"
    "CREATE"
    "DECLARE"
    "DELETE"
    "DESC"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "GRANT"
    "IF"
    "INSERT"
    "MERGE"
    "PURGE"
    "REFRESH"
    "RENAME"
    "REPLACE"
    "RESET"
    "ROLLBACK"
    "SAVEPOINT"
    "SET"
    "SHOW"
    "TABLE"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUE"
    "VALUES"
    "WITH"
    <K_SELECT>
    <ST_SEMICOLON>

: Query: with
    enterprise_start as (
        select
            organization_uuid_v4,
            min(hierarchy_started_at)::date as enterprise_started_at
        from sonar.dim_sc_organization_enterprise
        where organization_uuid_v4 is not null
        group by 1
    ),

    org_created as (
        select
            organization_uuid_v4,
            min(creation_date)::date as org_created_at
        from sonar.fct_sc_organization
        where organization_uuid_v4 is not null
        group by 1
    ),

    contract_anchor as (
        select
            o.organization_uuid_v4,
            date_trunc('month', coalesce(e.enterprise_started_at, o.org_created_at))::date as contract_start_month
        from org_created as o
        left join enterprise_start as e
            on o.organization_uuid_v4 = e.organization_uuid_v4
    ),

    eligible_orgs as (
        select
            organization_uuid_v4,
            contract_start_month
        from contract_anchor
        where
            dateadd(month, 6, contract_start_month) <= date_trunc('month', current_date)
    ),

    monthly_snapshot_raw as (
        select
            e.organization_uuid_v4,
            e.contract_start_month,
            date_trunc('month', f.data_timestamp)::date as activity_month,
            f.data_timestamp,
            f.enterprise_uuid,
            f.nb_of_active_users,
            f.nb_of_active_projects,
            f.nb_of_ncloc
        from eligible_orgs as e
        inner join sonar.fct_sc_organization as f
            on f.organization_uuid_v4 = e.organization_uuid_v4
        where
            date_trunc('month', f.data_timestamp)::date >= e.contract_start_month
            and date_trunc('month', f.data_timestamp)::date < dateadd(month, 6, e.contract_start_month)
    ),

    monthly_snapshot_ranked as (
        select
            msr.*,
            row_number() over (
                partition by msr.organization_uuid_v4, date_trunc('month', msr.data_timestamp)::date
                order by msr.data_timestamp desc
            ) as _rno
        from monthly_snapshot_raw as msr
    ),

    monthly_snapshot as (
        select
            organization_uuid_v4,
            contract_start_month,
            activity_month,
            data_timestamp,
            enterprise_uuid,
            nb_of_active_users,
            nb_of_active_projects,
            nb_of_ncloc
        from monthly_snapshot_ranked
        where _rno = 1
    ),

    monthly_deltas as (
        select
            organization_uuid_v4,
            contract_start_month,
            activity_month,
            nb_of_active_users,
            nb_of_active_projects,
            greatest(
                nb_of_active_users
                - coalesce(
                    lag(nb_of_active_users) over (
                        partition by organization_uuid_v4
                        order by activity_month
                    ),
                    nb_of_active_users
                ),
                0
            ) as active_users_added,
            greatest(
                nb_of_active_projects
                - coalesce(
                    lag(nb_of_active_projects) over (
                        partition by organization_uuid_v4
                        order by activity_month
                    ),
                   ...
[1385282c-bd24-420e-a628-a00658d06eff] 2026-04-20T15:56:21+08:00 WARN metabase.driver.sql Failed to parse native query: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token:<EOF>
    at line 168, column 1.

Was expecting one of:

    "("
    "ALTER"
    "ANALYZE"
    "BEGIN"
    "CALL"
    "COMMENT"
    "COMMIT"
    "CREATE"
    "DECLARE"
    "DELETE"
    "DESC"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "GRANT"
    "IF"
    "INSERT"
    "MERGE"
    "PURGE"
    "REFRESH"
    "RENAME"
    "REPLACE"
    "RESET"
    "ROLLBACK"
    "SAVEPOINT"
    "SET"
    "SHOW"
    "TABLE"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUE"
    "VALUES"
    "WITH"
    <K_SELECT>
    <ST_SEMICOLON>

: Query: with
    enterprise_start as (
        select
            organization_uuid_v4,
            min(hierarchy_started_at)::date as enterprise_started_at
        from sonar.dim_sc_organization_enterprise
        where organization_uuid_v4 is not null
        group by 1
    ),

    org_created as (
        select
            organization_uuid_v4,
            min(creation_date)::date as org_created_at
        from sonar.fct_sc_organization
        where organization_uuid_v4 is not null
        group by 1
    ),

    contract_anchor as (
        select
            o.organization_uuid_v4,
            date_trunc('month', coalesce(e.enterprise_started_at, o.org_created_at))::date as contract_start_month
        from org_created as o
        left join enterprise_start as e
            on o.organization_uuid_v4 = e.organization_uuid_v4
    ),

    eligible_orgs as (
        select
            organization_uuid_v4,
            contract_start_month
        from contract_anchor
        where
            dateadd(month, 6, contract_start_month) <= date_trunc('month', current_date)
    ),

    monthly_snapshot_raw as (
        select
            e.organization_uuid_v4,
            e.contract_start_month,
            date_trunc('month', f.data_timestamp)::date as activity_month,
            f.data_timestamp,
            f.enterprise_uuid,
            f.nb_of_active_users,
            f.nb_of_active_projects,
            f.nb_of_ncloc
        from eligible_orgs as e
        inner join sonar.fct_sc_organization as f
            on f.organization_uuid_v4 = e.organization_uuid_v4
        where
            date_trunc('month', f.data_timestamp)::date >= e.contract_start_month
            and date_trunc('month', f.data_timestamp)::date < dateadd(month, 6, e.contract_start_month)
    ),

    monthly_snapshot_ranked as (
        select
            msr.*,
            row_number() over (
                partition by msr.organization_uuid_v4, date_trunc('month', msr.data_timestamp)::date
                order by msr.data_timestamp desc
            ) as _rno
        from monthly_snapshot_raw as msr
    ),

    monthly_snapshot as (
        select
            organization_uuid_v4,
            contract_start_month,
            activity_month,
            data_timestamp,
            enterprise_uuid,
            nb_of_active_users,
            nb_of_active_projects,
            nb_of_ncloc
        from monthly_snapshot_ranked
        where _rno = 1
    ),

    monthly_deltas as (
        select
            organization_uuid_v4,
            contract_start_month,
            activity_month,
            nb_of_active_users,
            nb_of_active_projects,
            greatest(
                nb_of_active_users
                - coalesce(
                    lag(nb_of_active_users) over (
                        partition by organization_uuid_v4
                        order by activity_month
                    ),
                    nb_of_active_users
                ),
                0
            ) as active_users_added,
            greatest(
                nb_of_active_projects
                - coalesce(
                    lag(nb_of_active_projects) over (
                        partition by organization_uuid_v4
                        order by activity_month
                    ),
                   ...
```

**To Reproduce**
Try to run the query below.

**Expected behavior**
I expect queries to not make the page crash

**Screenshots**

Image

**Severity**
This is not very common, but it has happened a few times to different people. I cannot confirm that they all had this issue though, but it's the same kind of problem.

**Additional context**
This is the full query that my colleague was trying to run. Full disclosure, it may not be correct because he was debugging, but we expect queries to not crash the whole page.

```
with
    enterprise_start as (
        select
            organization_uuid_v4,
            min(hierarchy_started_at)::date as enterprise_started_at
        from sonar.dim_sc_organization_enterprise
        where organization_uuid_v4 is not null
        group by 1
    ),

    org_created as (
        select
            organization_uuid_v4,
            min(creation_date)::date as org_created_at
        from sonar.fct_sc_organization
        where organization_uuid_v4 is not null
        group by 1
    ),

    contract_anchor as (
        select
            o.organization_uuid_v4,
            date_trunc('month', coalesce(e.enterprise_started_at, o.org_created_at))::date as contract_start_month
        from org_created as o
        left join enterprise_start as e
            on o.organization_uuid_v4 = e.organization_uuid_v4
    ),

    eligible_orgs as (
        select
            organization_uuid_v4,
            contract_start_month
        from contract_anchor
        where
            dateadd(month, 6, contract_start_month) <= date_trunc('month', current_date)
    ),

    monthly_snapshot_raw as (
        select
            e.organization_uuid_v4,
            e.contract_start_month,
            date_trunc('month', f.data_timestamp)::date as activity_month,
            f.data_timestamp,
            f.enterprise_uuid,
            f.nb_of_active_users,
            f.nb_of_active_projects,
            f.nb_of_ncloc
        from eligible_orgs as e
        inner join sonar.fct_sc_organization as f
            on f.organization_uuid_v4 = e.organization_uuid_v4
        where
            date_trunc('month', f.data_timestamp)::date >= e.contract_start_month
            and date_trunc('month', f.data_timestamp)::date < dateadd(month, 6, e.contract_start_month)
    ),

    monthly_snapshot_ranked as (
        select
            msr.*,
            row_number() over (
                partition by msr.organization_uuid_v4, date_trunc('month', msr.data_timestamp)::date
                order by msr.data_timestamp desc
            ) as _rno
        from monthly_snapshot_raw as msr
    ),

    monthly_snapshot as (
        select
            organization_uuid_v4,
            contract_start_month,
            activity_month,
            data_timestamp,
            enterprise_uuid,
            nb_of_active_users,
            nb_of_active_projects,
            nb_of_ncloc
        from monthly_snapshot_ranked
        where _rno = 1
    ),

    monthly_deltas as (
        select
            organization_uuid_v4,
            contract_start_month,
            activity_month,
            nb_of_active_users,
            nb_of_active_projects,
            greatest(
                nb_of_active_users
                - coalesce(
                    lag(nb_of_active_users) over (
                        partition by organization_uuid_v4
                        order by activity_month
                    ),
                    nb_of_active_users
                ),
                0
            ) as active_users_added,
            greatest(
                nb_of_active_projects
                - coalesce(
                    lag(nb_of_active_projects) over (
                        partition by organization_uuid_v4
                        order by activity_month
                    ),
                    nb_of_active_projects
                ),
                0
            ) as active_projects_added
        from monthly_snapshot
    ),

    aggregated as (
        select
            organization_uuid_v4,
            contract_start_month,
            count(*) as months_observed,
            avg(active_users_added * 1.00) as avg_active_users_added_per_month,
            avg(active_projects_added * 1.00) as avg_active_projects_added_per_month
        from monthly_deltas
        group by organization_uuid_v4, contract_start_month
        having count(*) = 6
    ),

    cohort_labels as (
        select
            organization_uuid_v4,
            contract_start_month,
            to_char(contract_start_month, 'YYYY-MM') as cohort_month_label,
            case
                when
                    avg_active_users_added_per_month >= 1
                    and avg_active_projects_added_per_month >= 1.5
                    then 'Healthy'
                else 'At Risk'
            end as cohort_health_segment
        from aggregated
    ),

    ncloc_by_contract_month as (
        select
            c.cohort_health_segment,
            c.cohort_month_label,
            ms.organization_uuid_v4,
            ms.contract_start_month,
            ms.activity_month,
            1
            + datediff(month, ms.contract_start_month, ms.activity_month) as nth_contract_month,
            ms.nb_of_ncloc
        from monthly_snapshot as ms
        inner join cohort_labels as c
            on ms.organization_uuid_v4 = c.organization_uuid_v4
            and ms.contract_start_month = c.contract_start_month
    )

select
    cohort_health_segment,
    cohort_month_label,
    nth_contract_month,
    avg(nb_of_ncloc::float) as avg_nb_of_ncloc,
    count(distinct organization_uuid_v4) as orgs_in_cell
from ncloc_by_contract_month
where nth_contract_month between 1 and 6
and cohort_health_segment = 'Healthy'
group by 1, 2, 3
order by 1, 2, 3;
```

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-cloud",
    "version": {
      "date": "2026-04-15",
      "tag": "v1.59.7",
      "hash": "46c477c"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/72858

### Description

We were only rejecting non-select statements for impersonated users. A query that is accepted by the actual DB might not be accepted by the parser. So it would succeed for an admin user, but not for the impersonated user. This PR makes it so that we parse the query for any impersonated database so that the behaviour is consistent for admin and impersonated users. 

### How to verify

1. Connect to a redshift database
2. Set up impersonation on it
3. Try to execute `select 1;;` as the admin and impersonated user, both queries should error.

### Demo

todo

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/impersonation/middleware.clj [hunk 1]
```diff
@@ -10,19 +10,26 @@
...
-    (do
-      (premium-features/assert-has-feature :advanced-permissions (tru "Advanced Permissions"))
-      (-> (driver/validate-impersonated-query driver/*driver* query)
-          (assoc :impersonation/role role)))
-    query))
+  (if qp.i/*skip-middleware-because-app-db-access*
+    query
+    (let [database              (lib.metadata/database (qp.store/metadata-provider))
+          impersonation-enabled? (impersonation.driver/impersonation-enabled-for-db? database)
+          role                  (impersonation.driver/connection-impersonation-role database)]
```
Comment (metamben) [inline enterprise/backend/src/metabase_enterprise/impersonation/middleware.clj:23]:
```suggestion
    (let [database               (lib.metadata/database (qp.store/metadata-provider))
          impersonation-enabled? (impersonation.driver/impersonation-enabled-for-db? database)
          role                   (impersonation.driver/connection-impersonation-role database)]
```

File: src/metabase/driver/sql.clj [hunk 2]
```diff
@@ -250,12 +251,17 @@
                     (if (lib.util/native-stage? stage)
                       (let [{:keys [is-single-select? sql error]}
                             (sql-tools/is-single-select-stmt? driver (:native stage))]
-                        (when error
-                          (log/warnf "Failed to parse native query: %s\n: Query: %s" error (:native stage)))
-                        (if is-single-select?
-                          (assoc stage :native sql)
-                          (throw (ex-info (tru "Invalid impersonated native query. Must be a single select statement.")
-                                          {:sql (:native stage)}))))
+                        (cond error
```
Comment (metamben) [inline src/metabase/driver/sql.clj:254]:
```suggestion
                        (cond
                          error
```

**Review by metamben — APPROVED** [review]
