### PR TITLE
fix localhost:* in embedding app origins sdk

### LINKED ISSUE #55478: `localhost:*` is removed from the authorized origins when another origin is added
https://metaboat.slack.com/archives/C063Q3F1HPF/p1742483077714679

We should be always allowing localhost:*, but as soon as we add something to embedding-app-origins-sdk then localhost:* is not allowed.

`localhost:*` is added via a getter, it's possible that the bug was introduced by a refactor that bypassed the getter

### PR DESCRIPTION
**Pull request by escherize**
resolves https://github.com/metabase/metabase/issues/55478

We need to call the setting's getter directly, and not use `setting/get-value-of-type`. The setter it adds localhost:* which is required.

It got swapped over to `setting/get-value-of-type` which will not call the defsettings' getter.

Moving the setting out of the `embed.settings` ns sidesteps this cyclic dependency:

```
Cyclic load dependency: 
[ /metabase/analytics/core ]
->/metabase/embed/settings
->/metabase/server/middleware/security
->/metabase/server/middleware/exceptions
->/metabase/server/core
->/metabase/analytics/prometheus
->[ /metabase/analytics/core ]
```

### CODE REVIEW

**Review by npretto — APPROVED** [review]
I didn't review the code but i tested it locally and it works

File: src/metabase/server/middleware/security.clj [hunk 1]
```diff
@@ -242,7 +243,7 @@
    (content-security-policy-header-with-frame-ancestors allow-iframes? nonce)
    (access-control-headers origin
                            (setting/get-value-of-type :boolean :enable-embedding-sdk)
-                           (setting/get-value-of-type :string :embedding-app-origins-sdk))
+                           (aos/embedding-app-origins-sdk))
```
Comment (escherize) [inline src/metabase/server/middleware/security.clj:246]: This is the bug:

File: src/metabase/server/middleware/security.clj [hunk 2]
```diff
@@ -225,7 +226,7 @@
   [origin enabled? approved-origins]
   (when enabled?
     (merge
-     (when (approved-origin? origin (if enabled? approved-origins "localhost:*"))
+     (when (approved-origin? origin approved-origins)
```
Comment (escherize) [inline src/metabase/server/middleware/security.clj:229]: this was redundant, but worked as intended. so I cleaned it up.

**Review by noahmoss — APPROVED** [review]
