### PR TITLE
Parse timestamps only if either the scale or this dimension is timeseries

### LINKED ISSUE #11069: Text columns are converted aggressively to DateTime in charts
**Describe the bug**
Text columns are converted aggressively to DateTime in charts and x-axis shows date even when scale is set to Ordinal.

**To Reproduce**
Set viz to Bar or Line for the following query:
```
SELECT '1396-01' AS t, 40 AS c UNION ALL
SELECT '1396-02' AS t, 40 AS c UNION ALL
SELECT '1396-03' AS t, 40 AS c UNION ALL
SELECT '1396-04' AS t, 40 AS c UNION ALL
SELECT '1396-05' AS t, 40 AS c UNION ALL
SELECT '1396-06' AS t, 40 AS c UNION ALL
SELECT '1396-07' AS t, 40 AS c UNION ALL
SELECT '1396-08' AS t, 40 AS c UNION ALL
SELECT '1396-09' AS t, 40 AS c UNION ALL
SELECT '1396-10' AS t, 40 AS c UNION ALL
SELECT '1396-11' AS t, 40 AS c UNION ALL
SELECT '1396-12' AS t, 40 AS c
```

**Screenshots**
Screenshot_00000

Metabase 0.33.3 and `master` (commit 7b2431e2a4983a4b03dfd32072f2c884cbdd929a) with various browsers.

**Additional context**
https://discourse.metabase.com/t/text-is-considered-as-date-time-in-visualization-v0-33-3/7581

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #11069

This bug occurred because we were parsing anything as a datetime if it looked like one. Many strings (e.g. "1000-01") are valid ISO 8601 but might not actually be dates.

With this PR we continue to default ISO 8601 strings to timeseries scales, but if the user changes it to an ordinal scale, we don't parse strings as datetimes.

However, when the column is a date type, we parse it as a datetime regardless of the scale. This is because even with ordinal scales, we still want to show appropriately formatted ticks and tooltips if we know it's a date.

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/renderer_utils.js [hunk 1]
```diff
@@ -8,7 +8,10 @@ import { datasetContainsNoResults } from "metabase/lib/dataset";
 import { parseTimestamp } from "metabase/lib/time";
 
 import { dimensionIsNumeric } from "./numeric";
-import { dimensionIsTimeseries } from "./timeseries";
+import {
+  dimensionIsTimeseries,
```
Comment (tlrobinson) [inline frontend/src/metabase/visualizations/lib/renderer_utils.js]: In light of this issue, `dimensionIsTimeseries` seems a little misleading, but I can't come up with a better name than `dimensionMightBeTimeseries` or `dimensionIsTimeseriesMaybe` or something.

**Review by tlrobinson — APPROVED** [review]
LGTM, unless we can come up with a better name for `dimensionIsTimeseries`

File: frontend/src/metabase/visualizations/lib/renderer_utils.js (hunk 1 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/lib/renderer_utils.js]: 🤔 yeah good point. Maybe `dimensionLooksLikeTimeseries` if we changed to logic to just inspect the data, but then we'd need to do `dimensionIsTimeseries() || dimensionLooksLikeTimeseries()` in a few places to avoid actually naming that concept.
