### PR TITLE
Make sync timezone log human readable

### LINKED ISSUE #46867: Weird timezone log line for sqlserver
### Describe the bug

In SQL server I saw something like:
metabase.sync.sync-metadata.sync-timezone :sqlserver database 2 default timezone is #object[java.time.ZoneOffset 0x4b796874 "Z"]

### To Reproduce

Can't repro, but saw it on 2713a63a-c572-4ed5-9f2b-9f51bda8017c

### Expected behavior

Log lines should be readable

### Logs

above

### Information about your Metabase installation

```JSON
v50.19
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/46867

### Description

Moves the sync timezone log to after the string conversion. 

Notes:

~~1. `sync-timezone!` will log the SQLServer driver response as is  ("Z"), but converts it to "UTC" when updating the database. Should we make it so that the log and DB values are the same?~~

2. The Mongo driver returns nil. Should it return UTC based on the [Mongo docs](https://www.mongodb.com/docs/v4.4/tutorial/model-time-data/)?

### How to verify

Start an instance of Metabase with a SQLServer database

```
dev=> (metabase.sync.sync-metadata.sync-timezone/sync-timezone! (t2/select-one :model/Database 15))
2025-01-09 21:18:14,722 INFO sync-metadata.sync-timezone :: :sqlserver database 15 default timezone is "UTC"
{:timezone-id "UTC"}
```

The log should be a quoted string and not a Java object.

### Demo

Screenshot 2025-01-08 at 5 45 36 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj [hunk 1]
```diff
@@ -652,8 +652,10 @@
      (with-open [stmt (.prepareStatement conn "SELECT sysdatetimeoffset();")
                  rset (.executeQuery stmt)]
        (when (.next rset)
-         (when-let [offset-date-time (.getObject rset 1 java.time.OffsetDateTime)]
-           (t/zone-offset offset-date-time)))))))
+         (some-> rset
```
Comment (snoe) [inline modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj:655]: I think this is the wrong place for the change, as the docstring for `db-default-timezone` Says:
> This method should return a [[String]], a [[java.time.ZoneId]], or a [[java.time.ZoneOffset]].

So I think this should be done right at the `log/info` where it can be humanized no matter which driver returns a `ZoneOffset`.

**Review by snoe — CHANGES_REQUESTED** [review]

**Review by snoe — APPROVED** [review]
