### PR TITLE
UXW-64 Fix table cell formatting for temporal breakout by week

### LINKED ISSUE #22359: Temporal breakout fields "by week" don't respect format settings in table visualization
**Describe the bug**
If you group a temporal field by week, and then view the results as a table, the temporal field values don't respect format settings. 

**To Reproduce**
1. Go to Sample Database -> Orders -> Summarize -> Created At by week
2. Go to Visualization -> Table
3. Click the gear icon next to Created At
4. Change the date style, and observe that the values in the "Created At: Week" don't change

**Expected behavior**
The values should respect the selected format settings

**Screenshots**
image

**Information about your Metabase Installation:**
Current master

**Severity**
Minor

### PR DESCRIPTION
**Pull request by deniskaber**
Closes https://github.com/metabase/metabase/issues/22359 / UXW-64

### Description

This fixes date value formatting for breakout "by week"

### How to verify

1. Go to Sample Database -> Orders -> Summarize -> Created At by week
2. Go to Visualization -> Table
3. Click the gear icon next to Created At
4. Change the date style, and observe that the values in the "Created At: Week" are displayed in selected format and separator

### Demo

https://github.com/user-attachments/assets/c6f26cd4-2db2-4079-a929-e8b4ed741da6

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by npfitz — APPROVED** [review]
Appears to work, and verified working in Static Viz too (though maybe it always did).

I'm fine with this fix, but it may be worth having someone from @metabase/core-frontend-querying look at this as well. Good work @deniskaber!

File: frontend/src/metabase/lib/formatting/date.tsx [hunk 1]
```diff
@@ -837,6 +837,184 @@ export function normalizeDateTimeRangeWithUnit(
...
+  dateStyle: string,
+  dateSeparator: string = "/",
+): DateRangeFormatSpec[] {
+  const sep = dateSeparator;
+  const M = DATE_RANGE_MONTH_PLACEHOLDER;
+  const D = "D";
+  const Y = "YYYY";
+
+  // Handle numeric date formats (M/D/YYYY, D/M/YYYY, YYYY/M/D)
+  if (dateStyle.includes("/")) {
```
Comment (alxnddr) [inline frontend/src/metabase/lib/formatting/date.tsx]: nit: this outer if seems redundant

File: frontend/src/metabase/lib/formatting/date.tsx [hunk 2]
```diff
@@ -837,6 +837,184 @@ export function normalizeDateTimeRangeWithUnit(
...
 
+/**
+ * Generates custom format specs for week ranges based on date_style setting.
+ * This allows week ranges to respect user's preferred date format (numeric vs text, component order, etc.)
+ */
+function getWeekFormatSpecsWithDateStyle(
+  dateStyle: string,
+  dateSeparator: string = "/",
+): DateRangeFormatSpec[] {
+  const sep = dateSeparator;
```
Comment (alxnddr) [inline frontend/src/metabase/lib/formatting/date.tsx]: Just using `dateSeparator` directly below would be fine

**Review by alxnddr — APPROVED** [review]
Looks good! Left a couple of nitpicks
