### PR TITLE
Fix #16299 MongoDB empty results when filtering against array

### LINKED ISSUE #16299: Questions on MongoDB return 'No results!' after upgrade from 0.38.5 to 0.39.0 when filtering against array
**Describe the bug**
After upgrading from 0.38.5 to 0.39.0 (respectively any 0.39.x), some questions for MongoDB return 'No results!'.

### Logs
Nothing in the console log.

Server logs:

```
metabase_1  | 2021-06-01 07:46:08,478 DEBUG middleware.log :: GET /api/user/current 200 4.6 ms (3 DB calls) App DB connections: 1/7 Jetty threads: 6/50 (2 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
metabase_1  | 2021-06-01 07:46:08,494 DEBUG middleware.log :: GET /api/session/properties 200 10.4 ms (2 DB calls) App DB connections: 1/7 Jetty threads: 6/50 (2 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
metabase_1  | 2021-06-01 07:46:08,514 DEBUG middleware.log :: GET /api/database 200 12.1 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (2 idle, 0 queued) (63 total active threads) Queries in flight: 0 (0 queued)
metabase_1  | 2021-06-01 07:46:08,585 DEBUG middleware.log :: GET /api/database 200 48.5 ms (4 DB calls) App DB connections: 2/7 Jetty threads: 8/50 (1 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued)
metabase_1  | 2021-06-01 07:46:08,587 DEBUG middleware.log :: GET /api/card/142 200 47.9 ms (5 DB calls) App DB connections: 2/7 Jetty threads: 8/50 (1 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued)
metabase_1  | 2021-06-01 07:46:08,596 DEBUG middleware.log :: GET /api/database 200 58.8 ms (9 DB calls) App DB connections: 1/7 Jetty threads: 8/50 (1 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued)
metabase_1  | 2021-06-01 07:46:08,634 DEBUG middleware.log :: GET /api/alert/question/142 200 4.0 ms (1 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (3 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued)
metabase_1  | 2021-06-01 07:46:08,663 DEBUG middleware.log :: GET /api/table/14/query_metadata 200 18.6 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (3 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued)
metabase_1  | 2021-06-01 07:46:08,734 DEBUG middleware.log :: GET /api/collection/root 200 5.1 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (3 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued)
metabase_1  | 2021-06-01 07:46:08,895 DEBUG middleware.log :: POST /api/card/142/query 202 [ASYNC: completed] 67.1 ms (12 DB calls) App DB connections: 1/7 Jetty threads: 3/50 (3 idle, 0 queued) (66 total active threads) Queries in flight: 0 (0 queued)
```

**To Reproduce**

1. Install and setup metabase 0.38.5 and a MongoDB with a database named 'testdb' and a collection named 'testcol'.

2. Import following json in 'testcol'.
   
   ```json
   {"json_field":{"key_1": "value_jf_a", "key_2": "value_jf_z"}, "list_field":["value_lf_a", "value_lf_b"], "metas":{"group_field":"value_gf_a"}}
   {"json_field":{"key_1": "value_jf_b", "key_2": "value_jf_z"}, "list_field":["value_lf_a", "value_lf_b"], "metas":{"group_field":"value_gf_b"}}
   {"json_field":{"key_1": "value_jf_c", "key_2": "value_jf_z"}, "list_field":["value_lf_a", "value_lf_b"], "metas":{"group_field":"value_gf_c"}}
   {"json_field":{"key_1": "value_jf_a", "key_2": "value_jf_z"}, "list_field":["value_lf_c", "value_lf_d"], "metas":{"group_field":"value_gf_a"}}
   {"json_field":{"key_1": "value_jf_b", "key_2": "value_jf_z"}, "list_field":["value_lf_c", "value_lf_d"], "metas":{"group_field":"value_gf_b"}}
   {"json_field":{"key_1": "value_jf_c", "key_2": "value_jf_z"}, "list_field":["value_lf_c", "value_lf_d"], "metas":{"group_field":"value_gf_c"}}
   {"json_field":{"key_1": "value_jf_a", "key_2": "value_jf_z"}, "list_field":["value_lf_c", "value_lf_d"], "metas":{"group_field":"value_gf_a"}}
   {"json_field":{"key_1": "value_jf_b", "key_2": "value_jf_z"}, "list_field":["value_lf_c", "value_lf_d"], "metas":{"group_field":"value_gf_b"}}
   {"json_field":{"key_1": "value_jf_c", "key_2": "value_jf_z"}, "list_field":["value_lf_c", "value_lf_d"], "metas":{"group_field":"value_gf_c"}}
   ```

3. Create a 'Test question' as in screenshots

   screenshot_test_question_1

   and

   screenshot_test_question_2

   The native query for this question is :

   ```json
   [
     {
       "$project": {
         "json_field___key_1": "$json_field.key_1",
         "list_field": "$list_field",
         "metas___group_field": "$metas.group_field"
       }
     },
     {
       "$match": {
         "$and": [
           {
             "$or": [
               {
                 "json_field___key_1": {
                   "$eq": "value_jf_a"
                 }
               },
               {
                 "json_field___key_1": {
                   "$eq": "value_jf_b"
                 }
               }
             ]
           },
           {
             "list_field": {
               "$eq": "value_lf_a"
             }
           }
         ]
       }
     },
     {
       "$project": {
         "_id": "$_id",
         "___group": {
           "metas___group_field": "$metas___group_field"
         }
       }
     },
     {
       "$group": {
         "_id": "$___group",
         "count": {
           "$sum": 1
         }
       }
     },
     {
       "$sort": {
         "_id": 1
       }
     },
     {
       "$project": {
         "_id": false,
         "metas___group_field": "$_id.metas___group_field",
         "count": true
       }
     },
     {
       "$sort": {
         "metas___group_field": 1
       }
     }
   ]
   ```
   
4. The visualize result is

   screenshot_0_38_5

5. Upgrade metabase to 0.39.0 (or any 0.39.x)

6. The native query for 'Test question' is
 
   ```json
   [
     {
       "$match": {
         "$and": [
           {
             "$or": [
               {
                 "$expr": {
                   "$eq": [
                     "$json_field.key_1",
                     "value_jf_a"
                   ]
                 }
               },
               {
                 "$expr": {
                   "$eq": [
                     "$json_field.key_1",
                     "value_jf_b"
                   ]
                 }
               }
             ]
           },
           {
             "$expr": {
               "$eq": [
                 "$list_field",
                 "value_lf_a"
               ]
             }
           }
         ]
       }
     },
     {
       "$group": {
         "_id": {
           "metas": {
             "group_field": "$metas.group_field"
           }
         },
         "count": {
           "$sum": 1
         }
       }
     },
     {
       "$sort": {
         "_id": 1
       }
     },
     {
       "$project": {
         "_id": false,
         "metas.group_field": "$_id.metas.group_field",
         "count": true
       }
     },
     {
       "$sort": {
         "metas.group_field": 1
       }
     }
   ]
   ```
    
   and the visualize result is screenshot_0_39_0

   screenshot_0_39_0

### Expected behavior

Have the same visualize result in 0.39.x as in 0.38.5

### Information about your Metabase Installation:

- Your browser and the version: Chrome 91.0.4472.77
- Your operating system: OS X 11.4
- Your databases: MongoDB
- Metabase version: 0.38.5 and 0.39.0 (still reproducible in every 0.39.x)
- Metabase hosting environment: Docker
- Metabase internal database: MariaDB

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "5.10.25-linuxkit",
    "user.language": "en",
    "user.timezone": "Europe/Zurich"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.5.9-MariaDB-1:10.5.9+maria~focal"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-19",
      "tag": "v0.39.0",
      "branch": "release-x.39.x",
      "hash": "5e40366"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

### Severity

Blocking an upgrade

### Additional context

Thanks for your support

### PR DESCRIPTION
**Pull request by camsaul**
The optimized code from 39 generated 

```clj
{$expr {$eq [$list_field "value_lf_a"]}}
```

where we used to generate 

```clj
{list_field {$eq "value_lf_a"}}
```

Even tho they're both `list_field == value_lf_a`, they have different behaviors for fields whose value is an array. This PR adds tests for `:=` filters against array fields and tweaks the Mongo QP to generate the latter again.

Actually... for `$eq` we can generate

```clj
{list_field "value_lf_a"}
```

(small tweak to make resulting query more idiomatic/concise)

Fixes #16299

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 1]
```diff
@@ -295,11 +295,6 @@
   {:arglists '([clause])}
   mbql.u/dispatch-by-clause-name-or-class)
 
-(def ^:private ^:dynamic *top-level-filter?*
-  "Whether we are compiling a top-level filter clause. This means we can generate somewhat simpler `$match` clauses that
-  don't need to use `$expr` (see below)."
-  true)
-
```
Comment (camsaul) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:302]: I think this was needed for MongoDB 3.0 or something (some ancient unsupported version) but things totally work fine now without it.

File: modules/drivers/mongo/test/metabase/driver/mongo_test.clj [hunk 2]
```diff
@@ -326,3 +330,49 @@
...
+
+(defn- json-from-file [^String filename]
+  (with-open [rdr (java.io.FileReader. (java.io.File. filename))]
+    (json/parse-stream rdr true)))
+
+(defn- array-fields-db []
+  (create-database-from-row-maps!
+   "test-16299"
+   "coll"
+   (json-from-file "modules/drivers/mongo/test/metabase/driver/array-fields.json")))
```
Comment (camsaul) [inline modules/drivers/mongo/test/metabase/driver/mongo_test.clj:365]: Some test tooling to create one-off MongoDB databases/collections from JSON files for testing stuff like this

File: test/metabase/test/data/impl.clj [hunk 3]
```diff
@@ -195,16 +194,32 @@
...
-                             field-name table-id table-name driver db-id db-name
-                             (u/pprint-to-str (db/select-id->field :name Field, :active true, :table_id table-id))))))))
+         (ex-info (format "Couldn't find Field %s for Table %s.\nFound:\n%s"
+                          (pr-str field-name) (pr-str table-name) (u/pprint-to-str all-field-names))
+                  {:field-name  field-name
+                   :table       table-name
+                   :table-id    table-id
+                   :database    db-name
+                   :database-id db-id
+                   :all-fields  all-field-names})))))
```
Comment (camsaul) [inline test/metabase/test/data/impl.clj:222]: Improved the error messages here a little when using the `$ids` and `mbql-query` macros and you reference a **nested** field that doesn't exist.

**Comment by dpsutton** [comment]
> Actually... for $eq we can generate
> `{list_field "value_lf_a"}`

Do we know if this is actually an optimization or if its just sugar?

**Review by dpsutton — APPROVED** [review]

**Comment by dpsutton** [comment]
Two notes:
- i think this was my change for the operators that broke this. I'm not following why it doesn't work though. And this makes me nervous about that fall-through branch where we use this syntax "when we do something complicated". Will it work there? Why doesn't it work for equality
- I was expecting to see `(#16299)` on one of the tests. This seems like we would forget about this and possibly reintroduce the behavior as it doesn't seem wrong. Might be worth having that context there, although I guess the blame could help, as long as someone uses it.

File: modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj [hunk 4]
```diff
@@ -179,10 +179,10 @@
       (doseq [[operator form input] [[:number/<= {"price" {"$lte" 42}} [42]]
                                      [:number/>= {"price" {"$gte" 42}} [42]]
                                      [:number/!= {"price" {"$ne" 42}} [42]]
-                                     [:number/= {"price" {"$eq" 42}} [42]]
-                                     ;; i don't understand the $ on price here
-                                     [:number/between {"$and" [{"$expr" {"$gte" ["$price" 42]}}
-                                                               {"$expr" {"$lte" ["$price" 142]}}]} [42 142]]]]
+                                     [:number/= {"price" 42} [42]]
```
Comment (dpsutton) [inline modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj:182]: I think this really hammers home my confusion about this. It seems like these should all be the same but why is `$eq` behaving differently.

**Comment by camsaul** [comment]
@dpsutton RE

> Actually... for $eq we can generate
> 
> ```
> {list_field "value_lf_a"}
> ```
> 
> Do we know if this is actually an optimization or if its just sugar?

Sorry, I wasn't being clear here. It is just sugar in the sense that they mean the exact same thing. It's optimized in the sense that the query is more concise

File: modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj (hunk 4 above)
Comment (camsaul) [reply modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj:182]: `{price 4}` and `{price {$eq 4}}` both mean the exact same thing and give you the same results. The former is more idiomatic tho from my understanding -- all of the examples from the MongoDB website use the former syntax for simple equality and only use the latter with an operator other than `$eq`

Previously we have been generating `{$expr {$eq [$price 4]}}`, which returns the same results if `$price` is an atomic value but not if it's an array. So it doesn't make a difference _here_ but it was causing the bug I ended up fixing

**Comment by camsaul** [comment]
@dpsutton RE

> Two notes:
> 
> i think this was my change for the operators that broke this. I'm not following why it doesn't work though. And this makes me nervous about that fall-through branch where we use this syntax "when we do something complicated". Will it work there? Why doesn't it work for equality

It wasn't your change that introduced this, it was my changes in #14840

> I was expecting to see (#16299) on one of the tests. This seems like we would forget about this and possibly reintroduce the behavior as it doesn't seem wrong. Might be worth having that context there, although I guess the blame could help, as long as someone uses it. (EDIT: i see the issue number in the db definition now)

The issue number is in the test itself too https://github.com/metabase/metabase/pull/16480/files#diff-1e81a07d7342f134ef01dffd6d67d68604fb7739006b03f6449da3bc32e66e46R367-R378
