### PR TITLE
🤖 backported "Closes VIZ-147 - Title fonts are cut off when exporting a card as png from a dashboard"

### LINKED ISSUE #45499: Title fonts are cut off when exporting a card as png from a dashboard
### Describe the bug

When exporting a card as png from a dashboard, the font is cut off, as seen here
image

### To Reproduce

See examples here https://metaboat.slack.com/archives/C01LQQ2UW03/p1720803141264079

I was able to reproduce this in a combo chart, row chart with a single series, and line chart with multiple series 

### Expected behavior

It should look fine and not cut off

### Logs

_No response_

### Information about your Metabase installation

```JSON
Hash: e1e8e0c
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by github-automation-metabase**
closes #45499
  #60225
  > [!IMPORTANT]
  > Manual conflict resolution is required.
  > Checkout the branch and run `./backport.sh` script. Force push your changes after cherry-picking. Check the box below when done.

  Conflicts:
  ```shell
  100644 e07522f8a05b0bb338f853b53a6a5ea7fdc56ac2 1	frontend/src/metabase/visualizations/components/legend/LegendCaption.tsx
100644 ec5334968b84e4a4b65d0b3e9302bd1b77980929 2	frontend/src/metabase/visualizations/components/legend/LegendCaption.tsx
100644 10a68eab8c765d70d7a523e0ca560640b234f0d8 3	frontend/src/metabase/visualizations/components/legend/LegendCaption.tsx
  ```

  - [x] Conflicts resolved

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/legend/LegendCaption.tsx [hunk 1]
```diff
@@ -87,13 +88,21 @@ export const LegendCaption = ({
         DashboardS.fullscreenNormalText,
         DashboardS.fullscreenNightText,
         EmbedFrameS.fullscreenNightText,
+
```
Comment (bpander) [inline frontend/src/metabase/visualizations/components/legend/LegendCaption.tsx:91]: ℹ️ There was a conflict here, just because on master there's a `CS.h3` class which was added for r56.

**Review by bpander — APPROVED** [review]
