### PR TITLE
switch CSV download over to using an http POST request so we can support long queries

### LINKED ISSUE #1908: CSV downloads are broken on large queries
related to #1758 , which has been resolved, but the problem remains for the CSV download links which attempt to encode the entire query as a query parameter in a GET request.  The end result is that if you write a really long SQL query and attempt to download the result you'll get a 414 error from the server.

### PR DESCRIPTION
**Pull request by agilliland**
fixes #1908

### CODE REVIEW

**Comment by agilliland** [comment]
@tlrobinson @camsaul check this out when you get a chance and let me know if you see any issues with this.  we'll likely need to update the saveCSV() function on window.OSX as well so that this works on the Mac App.

**Comment by camsaul** [comment]
Why not do that as part of the Same PR? The code in question lives here 
https://github.com/metabase/metabase/blob/master/OSX/Metabase/UI/MainViewController.m#L118-L151

Here's what the updated code should look like. Fill in the blanks and give it a whirl. Let me know how it works
```objective-c
NSURL *url = [NSURL URLWithString:apiURL relativeToURL:[NSURL URLWithString:BaseURL()]]; // this is the param passed into saveCSV, change as needed
NSMutableURLRequest *csvRequest = [NSMutableURLRequest requestWithURL:url cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:10.0f];
csvRequest.HTTPMethod = @"POST";
NSDictionary *json = @{@"some_key": @"some-string"};
NSError *jsonError;
csvRequest.HTTPBody = [NSJSONSerialization dataWithJSONObject:json options:0 error:&jsonError];
if (jsonError) {
	NSLog(@"Error encoding JSON: %@", jsonError.localizedDescription);
	return;
}
```

**Comment by agilliland** [comment]
k ... Mac has been updated to handle a new http POST based CSV download endpoint.

this should be full g2g now.

File: OSX/Metabase/UI/MainViewController.m [hunk 1]
```diff
@@ -133,8 +133,14 @@ - (void)saveCSV:(NSString *)apiURL {
...
 		
-		NSURL *url = [NSURL URLWithString:apiURL relativeToURL:[NSURL URLWithString:BaseURL()]];
-		NSURLRequest *csvRequest = [NSURLRequest requestWithURL:url cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:10.0f];
+		NSURL *url = [NSURL URLWithString:@"/api/dataset/csv" relativeToURL:[NSURL URLWithString:BaseURL()]];
+        NSString *postBody = [NSString stringWithFormat:@"query=%@",datasetQuery];
+        NSData *data = [postBody dataUsingEncoding:NSUTF8StringEncoding];
+		NSMutableURLRequest *csvRequest = [NSMutableURLRequest requestWithURL:url cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:10.0f];
+        csvRequest.HTTPMethod = @"POST";
+        [csvRequest setValue:@"application/x-www-form-urlencoded" forHTTPHeaderField:@"Content-Type"];
+        [csvRequest setValue:[NSString stringWithFormat:@"%lu",(unsigned long)[data length]] forHTTPHeaderField:@"Content-Length"];
```
Comment (camsaul) [inline OSX/Metabase/UI/MainViewController.m]: A couple style points here:

*  put spaces after commas, just like in Java
*  `NSUInteger` is the canonical way to say unsigned long in Obj-C
*  just use dot syntax to get `data.length`

```objective-c
[NSString stringWithFormat:@"%lu", (NSUInteger)data.length]
```

File: OSX/Metabase/UI/MainViewController.m [hunk 2]
```diff
@@ -133,8 +133,14 @@ - (void)saveCSV:(NSString *)apiURL {
...
 		NSLog(@"Will save CSV at: %@", savePanel.URL);
 		
-		NSURL *url = [NSURL URLWithString:apiURL relativeToURL:[NSURL URLWithString:BaseURL()]];
-		NSURLRequest *csvRequest = [NSURLRequest requestWithURL:url cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:10.0f];
+		NSURL *url = [NSURL URLWithString:@"/api/dataset/csv" relativeToURL:[NSURL URLWithString:BaseURL()]];
+        NSString *postBody = [NSString stringWithFormat:@"query=%@",datasetQuery];
+        NSData *data = [postBody dataUsingEncoding:NSUTF8StringEncoding];
+		NSMutableURLRequest *csvRequest = [NSMutableURLRequest requestWithURL:url cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:10.0f];
+        csvRequest.HTTPMethod = @"POST";
+        [csvRequest setValue:@"application/x-www-form-urlencoded" forHTTPHeaderField:@"Content-Type"];
```
Comment (camsaul) [inline OSX/Metabase/UI/MainViewController.m]: any reason you're doing this form-encoded instead of JSON?

Comment (agilliland) [inline OSX/Metabase/UI/MainViewController.m]: yeah, that's the way the endpoint is coded up because that's what we have to do in the web app.

File: OSX/Metabase/UI/MainViewController.m [hunk 3]
```diff
@@ -133,8 +133,14 @@ - (void)saveCSV:(NSString *)apiURL {
 	if ([savePanel runModal] == NSFileHandlingPanelOKButton) {
 		NSLog(@"Will save CSV at: %@", savePanel.URL);
 		
-		NSURL *url = [NSURL URLWithString:apiURL relativeToURL:[NSURL URLWithString:BaseURL()]];
-		NSURLRequest *csvRequest = [NSURLRequest requestWithURL:url cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:10.0f];
+		NSURL *url = [NSURL URLWithString:@"/api/dataset/csv" relativeToURL:[NSURL URLWithString:BaseURL()]];
+        NSString *postBody = [NSString stringWithFormat:@"query=%@", datasetQuery];
```
Comment (camsaul) [inline OSX/Metabase/UI/MainViewController.m]: Sorry. One more style thing I just noticed. You should just write this as
```objective-c
NSString *postBody = [@"query=" stringByAppendingString:datasetQuery];
```

File: OSX/Metabase/UI/MainViewController.m (hunk 2 above)
Comment (camsaul) [inline OSX/Metabase/UI/MainViewController.m]: gotcha
