### PR TITLE
Use the date inlcuded in the query to calculate offset in MySQL

### LINKED ISSUE #7106: MySQL datetime offsets always using the current date
As part of a workaround for a bug affecting the MySQL driver and timezone conversions, we switched to serializing datetimes as a string with an offset to avoid the problematic code in the MySQL driver. When we serialize the date now, we figure out what the timezone offset is by using the current time of the system, not using the date we have in hand. The related code is [here](https://github.com/metabase/metabase/blob/master/src/metabase/driver/mysql.clj#L119).

This can cause a problem when time changes, such as it did yesterday. Assuming I have a date from last week (`2018-03-08T00:00:00.000`) that I'm using in a query today. The timestamp generated will be `2018-03-08T00:00:00.000-08:00`, which is incorrect, it should be `2018-03-08T00:00:00.000-07:00` as the timestamp occurred before the time change. When generating a MySQL timestamp string, we need to use the date to determine the offset.

### PR DESCRIPTION
**Pull request by senior**
Previously current date was used determine the offset for a given
timezone. This causes issues when the date being queried has a
different offset than today's date. Daylight savings time is an
example of that as depending on when the date is, the offset can be
different.

Fixes #7106

### CODE REVIEW

File: src/metabase/driver/mysql.clj [hunk 1]
```diff
@@ -114,18 +115,20 @@
       (timezone-id->offset-str \"US/Pacific\") ; -> \"-08:00\"
```
Comment (camsaul) [inline src/metabase/driver/mysql.clj]: don't forget to update those docstrs

**Review by camsaul — APPROVED** [review]
There's a docstr we should update to reflect the new way things work. Once that's done then LGTM
