### PR TITLE
Format QP temporal values using the reporting timezone

### LINKED ISSUE #2034: Query results are not formatting the date/time values using the report timezone
*  database is `all`, Metabase version is `0.15.0`

When you execute any query that returns temporal values such as dates and/or timestamps the results of the query should be accurately formatted in the chosen reporting timezone.  currently all values are formatted in UTC which isn't terrible, but it then requires that all clients separately grab the report timezone and reformat the value as needed, which is undesirable.

To reproduce: Set the report timezone to `Asia/Tokyo` and run the following query (on postgres) `select * from (values (timestamp '1999-01-08 11:05:06 -8:00', (timestamp '1999-01-08 11:05:06 -8:00'::date))) v`.  The output of the query which is returned will be `["1999-01-08T19:05:06.000Z", "1999-01-08T08:00:00.000Z"]` which provides no meaningful relationship with the desired reporting timezone of `Asia/Tokyo`

### PR DESCRIPTION
**Pull request by agilliland**
Resolves #2034 

Previously all query result values of a temporal type (java.sql.Date, java.sql.Timestamp, or java.util.Date) were being left unformatted until they hit the JSON serializer in our api middleware (https://github.com/metabase/metabase/blob/format-qp-results-in-timezone/src/metabase/middleware.clj#L205-L207) which was then formatting them as ISO8601 timestamps in UTC by default.

That's a good default for our api, but for query results we really want to be formatting the values in the reporting timezone, so this PR adds a little formatting code to the QP middleware which proactively formats temporal values as ISO8601 values _WITH_ the reporting timezone offset.

In addition to formatting the query result values with the report timezone this PR also introduces another small piece of QP middleware in pre-processing which looks up the `:report-timezone` setting from the MB instance and adds it to a :settings dictionary on the query.  This just makes it easier for the QP code and drivers to access and use the report timezone value because instead of having various places in the code looking up the value separately it's now accessed in one place and available to all QP code without any effort.

### CODE REVIEW

File: test/metabase/test_setup.clj [hunk 1]
```diff
@@ -113,11 +113,3 @@
...
               :when       (not (:doc (meta varr)))]
           (symbol (str (ns-name ns) "/" symb)))))
-
-(defn- throw-if-metabase-doesnt-have-enough-docstrings!
-  {:expectations-options :before-run}
-  []
-  (when-let [things-that-need-dox (seq (things-that-need-dox))]
-    (println (u/format-color 'red "Every public var in Metabase might as well have a docstring! Go write some for the following (or make them ^:private):\n%s"
-               (u/pprint-to-str things-that-need-dox)))
-    (System/exit -1)))
```
Comment (agilliland) [inline test/metabase/test_setup.clj]: Why is it that we need this check?

Comment (camsaul) [inline test/metabase/test_setup.clj]: The check is in there to catch us when we're tempted to cut corners and write code that's not as high-quality as it ought to be. Our codebase is well-documented right now, so let's keep it that way. If not for our own sake, for the sake of all the people out there who would like to contribute to it.

At any rate I've moved this out into a separate linter.

File: src/metabase/driver.clj [hunk 2]
```diff
@@ -299,6 +299,11 @@
   (when engine
     (contains? (set (keys (available-drivers))) (keyword engine))))
 
+(defn driver-supports?
+  "Predicate function that tests if a driver supports a given feature."
```
Comment (camsaul) [inline src/metabase/driver.clj]: The question mark at the end of the function name implies that it's a predicate function, I don't think it's really necessary to include that in the docstr

File: src/metabase/driver/generic_sql/native.clj [hunk 3]
```diff
@@ -27,9 +27,8 @@
              (.setAutoCommit jdbc-connection false)
              (try
                ;; Set the timezone if applicable
-               (when-let [timezone (driver/report-timezone)]
-                 (when (and (seq timezone)
-                            (contains? (driver/features driver) :set-timezone))
+               (when-let [timezone (:report-timezone settings)]
+                 (when (seq timezone)
```
Comment (camsaul) [inline src/metabase/driver/generic_sql/native.clj]: Not every database supports setting timezones, why would we want to stop taking that into account?

File: src/metabase/util.clj [hunk 4]
```diff
@@ -62,8 +63,30 @@
...
+  ;; memoize this because the formatters are static.  they must be distinct per timezone though.
+  (memoize (fn [timezone-id]
+             (if timezone-id (time/with-zone (time/formatters :date-time) (t/time-zone-for-id timezone-id))
+                             (time/formatters :date-time)))))
+
+(extend-protocol ISO8601
+  nil                    (->ISO8601DateTime [_ _] nil)
+  java.util.Date         (->ISO8601DateTime [this timezone-id] (time/unparse (ISO8601Formatter timezone-id) (coerce/from-date this)))
+  java.sql.Date          (->ISO8601DateTime [this timezone-id] (time/unparse (ISO8601Formatter timezone-id) (coerce/from-sql-date this)))
+  java.sql.Timestamp     (->ISO8601DateTime [this timezone-id] (time/unparse (ISO8601Formatter timezone-id) (coerce/from-sql-time this)))
```
Comment (camsaul) [inline src/metabase/util.clj]: `java.sql.Timestamp` and `java.sql.Date` both extend `java.util.Date` so you don't need all three of these

File: src/metabase/util.clj [hunk 5]
```diff
@@ -62,8 +63,30 @@
...
+  org.joda.time.DateTime (->ISO8601DateTime [this timezone-id] (time/unparse (ISO8601Formatter timezone-id) this)))
+
+
 ;;; ## Date Stuff
 
+(defn is-temporal? [v]
```
Comment (camsaul) [inline src/metabase/util.clj]: What does this mean? (docstr?)

File: src/metabase/util.clj [hunk 6]
```diff
@@ -62,8 +63,30 @@
...
+  (and v (contains? #{:java.sql.Timestamp :java.sql.Date :java.util.Date :org.joda.time.DateTime} (keyword (.getName ^Class (type v))))))
```
Comment (camsaul) [inline src/metabase/util.clj]: as above, you could just check whether it's an `instance?` of `org.joda.time.DateTime` or `java.util.Date` since the other two derive from it

File: src/metabase/util.clj [hunk 7]
```diff
@@ -62,8 +63,30 @@
                                                                                (pprint-to-str (sort (keys time/formatters)))))))))
 
 
+(defprotocol ISO8601
+  "Protocol for converting objects to ISO8601 formatted strings."
+  (->ISO8601DateTime ^String [this timezone-id]
```
Comment (camsaul) [inline src/metabase/util.clj]: Since `ISO8601DateTime` isn't a class or class-like object this method should probably be named something like 
`->iso-8601-datetime` instead. Otherwise it's a bit misleading

File: src/metabase/driver/query_processor.clj [hunk 8]
```diff
@@ -136,6 +149,23 @@
         ;; Add :rows_truncated if we've hit the limit so the UI can let the user know
         (= num-results results-limit) (assoc-in [:data :rows_truncated] results-limit)))))
 
+(defn- format-rows [{:keys [report-timezone]} rows]
+  (let [format-value #(if (u/is-temporal? %)
+                       (u/->ISO8601DateTime % report-timezone)
+                       %)]
+    (for [row rows]
+      (map format-value row))))
```
Comment (camsaul) [inline src/metabase/driver/query_processor.clj]: I think it might be a little more readable to do
```clojure
(for [row rows
       v  row]
  (if (u/is-temporal? v)
    (u/->iso-8601-datetime v report-timezone)
    v))
```

File: src/metabase/driver/query_processor.clj [hunk 9]
```diff
@@ -8,7 +11,7 @@
             [medley.core :as m]
             schema.utils
             [swiss.arrows :refer [<<-]]
-            [metabase.db :refer :all]
+            [metabase.db :as db]
```
Comment (camsaul) [inline src/metabase/driver/query_processor.clj]: :+1:

File: src/metabase/driver/query_processor.clj [hunk 10]
```diff
@@ -1,6 +1,9 @@
 (ns metabase.driver.query-processor
   "Preprocessor that does simple transformations to all incoming queries, simplifing the driver-specific implementations."
-  (:require (clojure [pprint :as pprint]
+  (:require [clj-time.core :as t]
+            [clj-time.coerce :as tc]
+            [clj-time.format :as tf]
```
Comment (camsaul) [inline src/metabase/driver/query_processor.clj]: Could you keep the `clj-time` imports after `clojure` imports? And keep them sorted too? (`coerce`, `core`, `format`)? 

I'd also prefer grouping them like `(clj-time ...)` but that's a more of a personal preference.

File: src/metabase/driver/query_processor.clj [hunk 11]
```diff
@@ -107,6 +111,15 @@
            (fail query e)))))
 
 
+(defn- pre-add-settings [qp]
+  (fn [{:keys [driver] :as query}]
+    (let [settings (->> {:report-timezone (when (driver/driver-supports? driver :set-timezone)
+                                            (setting/get :report-timezone))}
+                        (filter (comp not nil? val))
+                        (into {}))]
+      (qp (assoc query :settings settings)))))
```
Comment (camsaul) [inline src/metabase/driver/query_processor.clj]: I think this would be more readable written this way
```clojure
(into {} (for [[k v] {...}
               :when (not (nil? v))]
           {k v})
```

File: src/metabase/driver/generic_sql/native.clj (hunk 3 above)
Comment (agilliland) [inline src/metabase/driver/generic_sql/native.clj]: that check still takes place, but it happens when the `:settings` are added to the query in our QP middleware ... https://github.com/metabase/metabase/blob/3aebb0376a16fa32c024cb843e20c70943260b38/src/metabase/driver/query_processor.clj#L116-L119

So the benefit is that redundant checking code like this can be eliminated from each individual driver because the drivers can now simply use the value presented on the query :settings and trust that it's been validated already.  In this case the `(when-let [timezone (:report-timezone settings)]` binding does everything we need because if the timezone exists in the query settings then we should use it, otherwise move on.

File: src/metabase/util.clj (hunk 4 above)
Comment (agilliland) [inline src/metabase/util.clj]: I suppose, although clj-time provides different functions for coercing from those separate classes, so I followed their lead.  Doesn't hurt anything.

File: src/metabase/util.clj (hunk 5 above)
Comment (agilliland) [inline src/metabase/util.clj]: Sure.  I'll add a docstring.  Definition is "of or relating to time." 

So this would be in a comparable functions like `number?` or `coll?` except that it returns true if the given value represents a date/time class.

File: src/metabase/util.clj (hunk 6 above)
Comment (agilliland) [inline src/metabase/util.clj]: :+1:

File: src/metabase/driver/query_processor.clj (hunk 8 above)
Comment (agilliland) [inline src/metabase/driver/query_processor.clj]: :+1:

File: src/metabase/driver/generic_sql/native.clj (hunk 3 above)
Comment (camsaul) [inline src/metabase/driver/generic_sql/native.clj]: ok makes sense.

File: src/metabase/util.clj (hunk 4 above)
Comment (camsaul) [inline src/metabase/util.clj]: Ok that makes sense. I didn't see that `from-sql-date` and `from-sql-time` were different function calls

**Comment by agilliland** [comment]
@camsaul anything else we want to validate on this guy?  thinking this is ready to merge now and we can test it out a bit at the same time we are playing with Metabot.

**Comment by camsaul** [comment]
:+1:
