### PR TITLE
Closes EMB-906 custom branding images for SDK

### LINKED ISSUE #64757: [SDK] Custom branding images for No Results don't apply to embeds
### Describe the bug

If you set up custom images for "No results", in Metabase they look correct but in the SDK it shows the default sailboat image

### To Reproduce

1. Go to Admin > Appearance > Conceal Metabase
2. Set a picture for "When calculations return no results"
3. Go to E-Commerce Insights, select a future date in year 2027
4. Shows no results with custom image
5. Now embed the same dashboard with the SDK and select a future date
6. Shows the sailboat instead

### Expected behavior

It should show the custom image in the SDK

### Logs

_No response_

### Information about your Metabase installation

```JSON
v56.9.1
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #64757
Closes [EMB-906: \[SDK\] Custom branding images for No Results don't apply to embeds](https://linear.app/metabase/issue/EMB-906/sdk-custom-branding-images-for-no-results-dont-apply-to-embeds)

### Description

Adds a way to configure custom images (no results and no objects) from the SDK MetabaseProvider component.

### How to verify

In an app that uses the SDK, configure your MetabaseProvider as follows:

```
const base64String = "..."; // some base64-encoded image

<MetabaseProvider
  authConfig={authConfig}
  pluginsConfig={{
    getNoDataIllustration: () => base64String,
    getNoObjectIllustration: () => base64String,
  }}
>
  <InteractiveDashboard dashboardId={1} />
</MetabaseProvider>
```

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk-bundle/components/public/ComponentProvider/ComponentProvider.tsx [hunk 1]
```diff
@@ -57,6 +58,8 @@ export const ComponentProviderInternal = ({
   }, [reduxStore, fontFamily]);
 
   useEffect(() => {
+    // Initialize SDK plugins to make selectors SDK-aware
+    initializeSdkPlugins();
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk-bundle/components/public/ComponentProvider/ComponentProvider.tsx]: I think this is good too, but I noticed `initializeSdkPlugins` is statically updating the `PLUGIN_SELECTORS` without actually needing any SDK state or context, so I wonder if this can be done with a static entry point, just like how our plugins work.

For example, today we have a file called `enterprise/frontend/src/metabase-enterprise/sdk-plugins.js` that registers plugins **only** to the SDK:

https://github.com/metabase/metabase/blob/b56f63252ba51e993fc6d358c81ddad4e6b6e9bf/enterprise/frontend/src/metabase-enterprise/sdk-plugins.js#L1-L12

I wonder if you could just do overrides in that file or import an override into that sdk-plugins.js file, e.g. these selectors that you had

```
PLUGIN_SELECTORS.getNoDataIllustration = ...
PLUGIN_SELECTORS.getNoObjectIllustration = ...
```

Then, it would be immediately registered when the SDK starts, and doesn't have to wait for `useEffect` to run.

cc @npretto @WiNloSt what do you guys think? I know we have a dynamic plugin system coming up, so Sebastien's approach is better in that case.

File: enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.schema.ts [hunk 2]
```diff
@@ -42,6 +42,8 @@ const propsSchema: Yup.SchemaOf<InteractiveDashboardProps> = Yup.object({
   plugins: Yup.object({
     mapQuestionClickActions: Yup.mixed().optional(),
     dashboard: Yup.mixed().optional(),
+    getNoDataIllustration: Yup.mixed().optional(),
+    getNoObjectIllustration: Yup.mixed().optional(),
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.schema.ts:46]: Have we checked with @albertoperdomo about the public-facing names for these plugins? Here is how it's called in admin settings, for reference.

Image

File: enterprise/frontend/src/embedding-sdk-bundle/plugins/index.ts [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+  PLUGIN_SELECTORS.getNoObjectIllustration = (state: State) => {
+    try {
+      // Check if we're in an SDK context with plugins
+      const sdkState = (state as SdkStoreState).sdk;
+      if (sdkState?.plugins?.getNoObjectIllustration) {
+        const sdkResult = sdkState.plugins.getNoObjectIllustration();
+        if (sdkResult !== null && sdkResult !== undefined) {
+          return sdkResult;
+        }
+      }
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk-bundle/plugins/index.ts]: tiny nit: because coalesce returns undefined anyway, you can just call it

```suggestion
      const sdkResult = sdkState?.plugins?.getNoObjectIllustration();
      if (sdkResult !== null && sdkResult !== undefined) {
        return sdkResult;
      }
```

File: enterprise/frontend/src/embedding-sdk-bundle/types/plugins.ts [hunk 4]
```diff
@@ -38,4 +38,17 @@ export type MetabaseDashboardPluginsConfig = {
 export type MetabasePluginsConfig = {
   mapQuestionClickActions?: MetabaseClickActionPluginsConfig;
   dashboard?: MetabaseDashboardPluginsConfig;
+  /**
+   * Provides a custom illustration to display when there is no data.
+   *
+   * @returns A base64-encoded image string, or null to use the default illustration
+   */
+  getNoDataIllustration?: () => string | null | undefined;
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk-bundle/types/plugins.ts:46]: tiny nit: `?:` already implies `| undefined`

File: enterprise/frontend/src/embedding-sdk-bundle/plugins/index.unit.spec.ts [hunk 5]
```diff
@@ -0,0 +1,271 @@
...
+
+      const result = PLUGIN_SELECTORS.getNoDataIllustration(mockState);
+
+      expect(result).toBe(mockSdkIllustration);
+      expect(mockSdkPlugins.getNoDataIllustration).toHaveBeenCalled();
+    });
+
+    it("should handle SDK plugin functions that return null", () => {
+      const mockSdkPlugins = {
+        getNoDataIllustration: jest.fn().mockReturnValue(null),
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk-bundle/plugins/index.unit.spec.ts]: nit: i'd do an `it.each([null, undefined])` as everything else is the same, but this is okay too

File: enterprise/frontend/src/embedding-sdk-bundle/plugins/index.unit.spec.ts [hunk 6]
```diff
@@ -0,0 +1,271 @@
...
+
+      expect(consoleSpy).toHaveBeenCalledWith(
+        "Error in SDK getNoObjectIllustration plugin:",
+        expect.any(Error),
+      );
+
+      consoleSpy.mockRestore();
+    });
+
+    it("should fallback to original selector when SDK plugin returns null", () => {
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk-bundle/plugins/index.unit.spec.ts]: I think this test could be combined with the `should handle SDK plugin functions that return null/undefined` as the setup is exactly the same. We can add the assertion from this test, just to reduce number of tests to maintain.

**Review by heypoom — APPROVED** [review]
Approach looks good!

File: enterprise/frontend/src/embedding-sdk-bundle/components/public/ComponentProvider/ComponentProvider.tsx (hunk 1 above)
Comment (npretto) [reply enterprise/frontend/src/embedding-sdk-bundle/components/public/ComponentProvider/ComponentProvider.tsx]: I think I agree, especially because if I understood correctly, this PR uses the `ee-plugins` system to change the behavior. I don't think we mixed `ee plugins` and `sdk plugins` before, I'm not against it but we should be sure we're not shooting ourselves here.
If we do this I'd rather have a single entrypoint where we do something like this:
```
import `ee-plugins`
import `ee-plugins-sdk-overrides`
```

Comment (lorem--ipsum) [reply enterprise/frontend/src/embedding-sdk-bundle/components/public/ComponentProvider/ComponentProvider.tsx]: That makes sense to me too, and it should work with dynamic plugins from what I understand

File: enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.schema.ts (hunk 2 above)
Comment (lorem--ipsum) [reply enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.schema.ts:46]: No, good call, I'll check with him

File: enterprise/frontend/src/embedding-sdk-bundle/types/plugins.ts (hunk 4 above)
Comment (lorem--ipsum) [reply enterprise/frontend/src/embedding-sdk-bundle/types/plugins.ts:46]: No the `undefined` is there as another return type for the function, not as another type for `getNoDataIllustration`

File: enterprise/frontend/src/embedding-sdk-bundle/plugins/index.unit.spec.ts (hunk 6 above)
Comment (lorem--ipsum) [reply enterprise/frontend/src/embedding-sdk-bundle/plugins/index.unit.spec.ts]: I agree, I'll make this test file cleaner

File: enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.schema.ts (hunk 2 above)
Comment (albertoperdomo) [reply enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.schema.ts:46]: I think it's ok to use more technical terminology here since the audience is developers:

* "no data" for no results sounds good
* I think "not found" is probably better than "no object"

I think `NoDataImage` is probably better than NoDataIllustration. Metabase uses an illustration but it could be any kind of image.

I wonder if not found is a realistic scenario for end-users. My guess is only devs should see this:
* if the user is browsing using collection browser they shouldn't hit this
* if the developer is embedding a specific item by ID then this could pop up but it probably means they either got the ID or the permissions wrong

Comment (lorem--ipsum) [reply enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.schema.ts:46]: yeah I mostly added `getNoObjectIllustration` for parity's sake, I'm cool with removing it if needed

File: enterprise/frontend/src/embedding-sdk-bundle/types/plugins.ts (hunk 4 above)
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk-bundle/types/plugins.ts:46]: Oh sorry I totally misread that
