### PR TITLE
Fix issues reverting dashboard

### LINKED ISSUE #15237: User with permissions sometimes fails to revert the dashboard
**Describe the bug**
User who should be able to revert the dashboard (has necessary permissions) sometimes fails to do so. It seems that it happens for the state PRIOR to adding a card to the dashboard.

**Logs**
N/A

**To Reproduce**
_First you need a dashboard that was initially empty, then added a question to it._
1. Log in as admin
2. Go to that dashboard
2. Go to the revision history
3. Choose the first revision
4. See that it fails with `500` error

<details><summary>Full stacktrace</summary>

```
2021-09-14 22:31:10,934 ERROR middleware.log :: POST /api/revision/revert 500 8.0 ms (11 DB calls) 
{:via
 [{:type java.lang.AssertionError,
   :message "Assert failed: (integer? dashboard_id)",
   :at [metabase.models.dashboard_card$dashboard invokeStatic "dashboard_card.clj" 55]}],
 :trace
 [[metabase.models.dashboard_card$dashboard invokeStatic "dashboard_card.clj" 55]
  [metabase.models.dashboard_card$dashboard invoke "dashboard_card.clj" 55]
  [metabase.models.dashboard_card$delete_dashboard_card_BANG_ invokeStatic "dashboard_card.clj" 162]
  [metabase.models.dashboard_card$delete_dashboard_card_BANG_ invoke "dashboard_card.clj" 157]
  [metabase.models.dashboard$revert_dashboard_BANG_ invokeStatic "dashboard.clj" 175]
  [metabase.models.dashboard$revert_dashboard_BANG_ invoke "dashboard.clj" 158]
  [metabase.models.revision$fn__36334$fn__36388$G__36337__36399 invoke "revision.clj" 19]
  [metabase.models.revision$revert_BANG_$fn__36468 invoke "revision.clj" 169]
  [toucan.db$do_in_transaction$fn__28606 invoke "db.clj" 147]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 807]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 852]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic "jdbc.clj" 789]
  [clojure.java.jdbc$db_transaction_STAR_ invoke "jdbc.clj" 776]
  [toucan.db$do_in_transaction invokeStatic "db.clj" 145]
  [toucan.db$do_in_transaction invoke "db.clj" 142]
  [metabase.models.revision$revert_BANG_ invokeStatic "revision.clj" 167]
  [metabase.models.revision$revert_BANG_ doInvoke "revision.clj" 156]
  [clojure.lang.RestFn invoke "RestFn.java" 619]
  [metabase.api.revision$fn__73763 invokeStatic "revision.clj" 41]
  [metabase.api.revision$fn__73763 invoke "revision.clj" 30]
  [compojure.core$wrap_response$fn__1996 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1980 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1985 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 151]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__77073 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.api.routes$fn__77139$fn__77141 invoke "routes.clj" 70]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.server.routes$fn__79375$fn__79376 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 153]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.server.routes$fn__79363$fn__79365 invoke "routes.clj" 41]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77130 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__77127 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__79289$fn__79290$fn__79291 invoke "log.clj" 209]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__79289$fn__79290 invoke "log.clj" 201]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__79289 invoke "log.clj" 200]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__78908 invoke "browser_cookie.clj" 30]
  [metabase.server.middleware.security$add_security_headers$fn__57741 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__79053 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__79071 invoke "json.clj" 98]
  [metabase.server.middleware.offset_paging$handle_paging$fn__57763 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__79632 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__79648 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__36092 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__42990$fn__42991 invoke "session.clj" 257]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 238]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 230]
  [metabase.server.middleware.session$bind_current_user$fn__42990 invoke "session.clj" 256]
  [metabase.server.middleware.session$wrap_current_user_info$fn__42977 invoke "session.clj" 216]
  [metabase.server.middleware.session$wrap_session_id$fn__42963 invoke "session.clj" 162]
  [metabase.server.middleware.auth$wrap_api_key$fn__77081 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__79552 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__36075 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__36100 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__79594 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__36103 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__79308 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__78852 invoke "server.clj" 71]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 556]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 905]
  [java.lang.Thread run "Thread.java" 829]],
 :cause "Assert failed: (integer? dashboard_id)",
 :message "Assert failed: (integer? dashboard_id)"}
```

</details>

**Expected behavior**
Users with permissions should be able to always revert the dashboard.

**Screenshots**
N/A

**Information about your Metabase Installation:**
N/A

**Severity**
P2, I guess.

**Additional context**
This was originally reported in https://github.com/metabase/metabase/issues/6884, but since that issue has a lot of other weirdness around it, we decided to split them in order to keep lines clear. This also helps in easier reproductions.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by pawit-metabase**
Backend Issues:
 - Reverting will fail if the revert involves dashcard deletion due to missing parameter

Frontend Issues:
 - After reverting, the frontend does not reload the dashboard (regression from #15654)
 - After reverting, the frontend does not reload the history list

Fixes #15237

### CODE REVIEW

**Comment by flamber** [comment]
@pawit-metabase You might want to follow #17858

File: frontend/src/metabase/dashboard/components/DashboardHistoryModal.jsx [hunk 1]
```diff
@@ -4,24 +4,37 @@ import { withRouter } from "react-router";
...
 
 @withRouter
 @Dashboards.load({
   id: (state, props) => Urls.extractEntityId(props.params.slug),
   wrapped: false,
 })
+@connect(
+  null,
+  dashboardActions,
+)
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/components/DashboardHistoryModal.jsx:19]: Mind binding only used actions? Binding everything leads to [prop drilling](https://kentcdodds.com/blog/prop-drilling). This can be changed to:

```jsx
import { fetchDashboard, fetchDashboardCardData } from "metabase/dashboard/actions"

const mapDispatchToProps = {
   fetchDashboard,
   fetchDashboardCardData,
}

@connect(
   null,
   mapDispatchToProps,
)
export default class ...
```

File: frontend/src/metabase/dashboard/components/DashboardHistoryModal.jsx [hunk 2]
```diff
@@ -4,24 +4,37 @@ import { withRouter } from "react-router";
 
 import HistoryModal from "metabase/containers/HistoryModal";
 import * as Urls from "metabase/lib/urls";
+import * as dashboardActions from "metabase/dashboard/actions";
 import Dashboards from "metabase/entities/dashboards";
+import connect from "react-redux/lib/connect/connect";
```
Comment (kulyk) [inline frontend/src/metabase/dashboard/components/DashboardHistoryModal.jsx:9]: 1. Can be `import { connect } from "react-redux"`
2. Could you please move the `connect` import to the top? Under `react` maybe. See the [FE style guide](https://github.com/metabase/metabase/blob/master/docs/developers-guide/frontend.md#javascript-conventions) for details

**Review by kulyk — COMMENTED** [review]
Looks good! Have just a couple of minor comments

File: frontend/src/metabase/dashboard/components/DashboardHistoryModal.jsx (hunk 2 above)
Comment (pawit-metabase) [reply frontend/src/metabase/dashboard/components/DashboardHistoryModal.jsx:9]: Sure!

**Review by camsaul — APPROVED** [review]
backend stuff LGTM

**Comment by pawit-metabase** [comment]
@daltojohnso I saw your PR #17887

I have a related issue here where the history is not updated after reverting. Can you check if my fix is the correct way or not?

**Review by daltojohnso — APPROVED** [review]
checked it out, this looks good!
