### PR TITLE
Fix - Frozen UI after viewing a table with missing fields in the metadata browser

### LINKED ISSUE #53194: Frozen UI after viewing a table with missing fields in the metadata browser
### Describe the bug

The UI becomes unresponsive when attempting to view table metadata of a table with missing fields.

### To Reproduce

1. Go to **Admin Settings / Table Metadata**, and set the visibility of all fields to **Do not include**.
2. Open the native query editor
3. Click on **Learn about your data** to open the metadata browser in the side bar
4. In the side bar navigate locate the table edited in Step 1
5. Click to view the metadata of the table and see the error:
- the UI is frozen and the browser tab cannot be returned to a working state
- it is not possible to copy text from the SQL editor, so any unsaved work will be lost.

### Expected behavior

It should work. Occasionally, tables may have missing columns in the metadata due to permission issues or related errors. Even if this happens as a result of an error, the UI should handle this situation gracefully.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "mongo",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-01-28",
      "tag": "v1.52.8.2",
      "hash": "412e324"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Very annoying, and unsaved work can be lost. Reported by a customer.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #53194

### Description

The issue was that the effect calling `fetchDependentData` ran infinite amount of times due to `fetchDependentData` reference changing on every render (due to `table` reference changing on every render).

### How to verify

Follow repro steps from the issue.

:warning: **The issue is only reproducible on EE.**

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/dataref/TableInfoLoader.tsx [hunk 1]
```diff
@@ -30,12 +30,13 @@ function useDependentTableMetadata({
...
+  const tableId = table.id;
+  const [, fetchDependentData] = useAsyncFn(() => {
     return Promise.all([
-      isMissingFields && fetchMetadata({ id: table.id }),
-      isMissingFks && fetchForeignKeys({ id: table.id }),
+      isMissingFields && fetchMetadata({ id: tableId }),
+      isMissingFks && fetchForeignKeys({ id: tableId }),
     ]);
-  }, [fetchMetadata, table, isMissingFks, isMissingFields, fetchForeignKeys]);
+  }, [fetchMetadata, tableId, isMissingFks, isMissingFields, fetchForeignKeys]);
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/dataref/TableInfoLoader.tsx:39]: This is the fix - `table` was different on every render. `tableId` is a reliable dep.

Comment (romeovs) [reply frontend/src/metabase/query_builder/components/dataref/TableInfoLoader.tsx:39]: Nit: I think this also works without introducing new variable.
```suggestion
  }, [fetchMetadata, table.id, isMissingFks, isMissingFields, fetchForeignKeys]);
```

**Review by romeovs — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/dataref/TableInfoLoader.tsx (hunk 1 above)
Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/dataref/TableInfoLoader.tsx:39]: But then prettier turns this 1 line into 7 lines :see_no_evil:

**Comment by kamilmielnik** [comment]
I had to revert `useSafeAsyncFunction` removal, because it broke some tests (the function returned from `useAsyncFn` never throws, unlike the one returned from `useSafeAsyncFunction`).
