### PR TITLE
Reduce memory usage when sending anon stat

### LINKED ISSUE #46403: OOM during sending anon stats
We have an OOM case while sending anon stats.

Looking at the stack trace, it points to this [line](https://github.com/metabase/metabase/blob/72a201819b3255c3753591297f90f05819d200cc/src/metabase/analytics/stats.clj#L368) in which we do a reducible select on QueryExecution table.

Even though we're selecting reducible, I suspect the OOM is caused by:
- the fact that this table is unbounded (e.g: we have 3M rows on stat) asking product whether we can bound this query [here](https://metaboat.slack.com/archives/C01LQQ2UW03/p1722572166303169)
- query_execution.error is a text field that often has a long stack trace

see [this](https://metaboat.slack.com/archives/C010ZSXQY87/p1721999716487909?thread_ts=1721939174.598129&cid=C010ZSXQY87) for stacktrace

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/46403

How test
1. Start MB with a small heapsize (512MB)
2. insert 200k of query Execution
```clojure
;; insert 200k of query Execution
(let [rand-char (fn [] (char (+ (int \A) (rand-int 26))))
        big-error (clojure.string/join (repeatedly 1e5 rand-char))]
    (doseq [_ (range 200)]
      (t2/insert! :model/QueryExecution (for [_ (range 1e3)]
                                          {:hash (byte-array 32),
                                           :result_rows 1,
                                           :started_at :%now,
                                           :executor_id nil,
                                           :native false,
                                           :card_id nil,
                                           :context :ad-hoc,
                                           :running_time 1
                                           :error big-error})))
    (t2/count :model/QueryExecution))

```
3. Try calling summarize-executions
```clojure
(summarize-executions)
```

### CODE REVIEW

File: src/metabase/analytics/stats.clj [hunk 1]
```diff
@@ -375,7 +375,8 @@
   ([summary execution]
    (-> summary
        (update :executions u/safe-inc)
-       (update-in [:by_status (if (:has_error execution)
+       ;; MYSQL is returning true as 1, false as 0! what!
```
Comment (piranha) [inline src/metabase/analytics/stats.clj:378]: hahaha Chris is fighting with this too 🤣

File: test/metabase/analytics/stats_test.clj [hunk 2]
```diff
@@ -222,6 +222,8 @@
 (deftest new-impl-test
   (mt/with-temp [QueryExecution _ (merge query-execution-defaults
                                          {:error "some error"})
+                 QueryExecution _ (merge query-execution-defaults
+                                         {:error "some error"})
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply test/metabase/analytics/stats_test.clj:226]: I added it so that we get 2 errors and 1 complete, it was 1:1 before and we might count it in the reverse order without knowning, so I think this is needed.

File: src/metabase/analytics/stats.clj (hunk 1 above)
Comment (qnkhuat) [reply src/metabase/analytics/stats.clj:378]: :(

Comment (crisptrutski) [reply src/metabase/analytics/stats.clj:378]: I also had a more complex boolean expression return `0M` (a bigdecimal) from MariaDB. FML 😆

**Review by sansolovyov — APPROVED** [review]

**Comment by qnkhuat** [comment]
@metabase-bot backport release-x.49.x
