### PR TITLE
Fix underlying records drill from pivot tables

### LINKED ISSUE #12368: Drill-through from Pivot table doesn't change table format to raw
**Describe the bug**
When doing a drill-through from a Pivot table, somehow the results of example "View these ..." are returned, but kept inside the same Pivot, which means it doesn't show the correct columns.

_It took a couple of times to reproduce this, so think it might be a race-condition or a state thing. When it started returning the correct result (I'm not sure why, just playing around with settings), then I had to open a new tab and follow every step to reproduce again._

**Logs**
No errors to do with this, as far as I can see.

**To Reproduce**
1. Custom question > Sample Dataset > Orders
2. Join table Products
3. Summarize by "Sum of Quantity", group by "Product->Category" and "Product->Vendor"
image
4. (validation step, can be skipped) Try clicking the first row value `295` (Alfreda Konopelski II Group / Gadget) > View these Orders. This returns 91 orders in full result set, which is correct. Click browser back-button.
image
5. Go to visualization Settings, disable Pivot, click "Sum of Quantity" column :gear:, enable "mini bar chart", enable Pivot again. It should look like this:
image
6. Like step 4, click first row value `295` (Alfreda Konopelski II Group / Gadget) > View these Orders. Somehow the Pivot table stays instead of showing a regular table:
image

**Expected behavior**
Expected full results in raw table format (similar to step 4).

**Information about your Metabase Installation:**
Metabase 1.34.3 and 0.35.2

**Additional context**
I'm not sure how important it is to enable "mini bar chart", but it seems to help triggering the issue.

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/12368

Simplified repro steps:
- New -> Question -> Products
- Aggregation -> Count
- Breakout -> Vendor, Category
- Visualize
- It should be visualized as a table (with a pivot flag, not the actual pivot table!). If not, change the viz type manually
- Open viz settings -> Toggle the pivot toggle off and on
- Save the question
- Click on any cell with data -> See this Product
- Open the viz settings
- You should see regular table options and not pivot table options

Before:
Screenshot 2024-07-12 at 15 49 16

After:
Screenshot 2024-07-12 at 15 49 32

### CODE REVIEW

File: frontend/src/metabase/querying/utils/drills/underlying-records-drill/underlying-records-drill.ts [hunk 1]
```diff
@@ -33,7 +33,10 @@ export const underlyingRecordsDrill: Drill<
       section: "records",
       icon: "table_spaced",
       buttonType: "horizontal",
-      question: () => applyDrill(drill).setDisplay("table"),
+      question: () =>
+        applyDrill(drill)
+          .setDisplay("table")
```
Comment (ranquild) [inline frontend/src/metabase/querying/utils/drills/underlying-records-drill/underlying-records-drill.ts:38]: So far this is the only drill that sets `table` display

**Review by kamilmielnik — APPROVED** [review]
