### PR TITLE
Only check create-queries perms when fetching DB/schema metadata

### LINKED ISSUE #45046: Upgrading to 50v causes some permission in No self-service (deprecated) to block access to the Browse Data
### Describe the bug

Upgrading to 50v causes some permission to be turned into No self-service (deprecated) ... This in turn will impact any table that is part of the database and block access to the Browse Data. More context here:

https://metaboat.slack.com/archives/C013N8XL286/p1719925976490589

### To Reproduce

Have permissions setup on 49 (no self service for some tables and a sandbox permission for another) and then upgrade. You will notice the permissions change in this way:

image

This will cause the sandboxed user to lose browse data permissions

image

Again more context here https://metaboat.slack.com/archives/C013N8XL286/p1719925976490589

### Expected behavior

The sandboxed user should not be impacted by the other tables permissions

### Logs

N/A

### Information about your Metabase installation

```JSON
50.8
```

### Severity

Major issue 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Resolves https://github.com/metabase/metabase/issues/45046

When checking read permissions for databases or schemas (the _metadata_, not the data itself), we previously had required `Data access` to be `Unrestricted` for at least one table.

In the new permissions system in v50, this is now dependent instead on the new `Create queries` permission. You can see a database or schema if you have _at least_ query builder access to any table.

However, we were still checking that the user also has `View data` access to the entire database (either unrestricted or sandboxed). Originally this was fine, since these were the only two options for `View data`, so this was just an extra check that caused no issues. When we added the transitional `No self-service (deprecated)` permission level, however, this resulted in unexpected behavior: if a user is in a group with `No self-service (deprecated)` set for any table, it causes the entire DB to fail the read check and be hidden from the browse data page.

I've fixed this by removing the unnecessary conditions in DB/schema permission checks, and added a couple new test cases.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#45045** <a href="https://app.graphite.dev/github/pr/metabase/metabase/45045?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: enterprise/backend/src/metabase_enterprise/advanced_permissions/common.clj [hunk 1]
```diff
@@ -25,8 +25,9 @@
      db-id
      (:table_id instance))))
 
-(defenterprise current-user-can-read-schema?
-  "Enterprise version. Returns a boolean whether the current user can read the given schema"
+(defenterprise current-user-can-manage-schema-metadata?
```
Comment (noahmoss) [inline enterprise/backend/src/metabase_enterprise/advanced_permissions/common.clj:28]: Unrelated, but I've renamed this function to be clearer

**Review by escherize — APPROVED** [review]

**Comment by Lutz-BY** [comment]
We are running Metabase 0.50.11 as open source on MySql
.
We were wondering, why restricted users couldn't see their tables anymore when 'browsing the database'.

If you disable access to a database for a group first and then allow access to individual tables for 'query only', the table is not shown in the data browser.

if you enable access to a database for a group first and then change the permission for all individual tables to 'no access', except for the tables, you want the group to see, the users can see the tables in the data browser.

The toggle-text in the admin area is the same (Granular)!

As we didn't have this problem before updating, I guess that the cause for this behavior lies in the new permission model in v0.50! And it looks, like it coud share its origins with this topic.

It would save a lot of time and spare errors and misunderstanding, if the result would be the same, regardless of the sequence of the editing of permissions.

Hoping for a solution,
Lutz
