### PR TITLE
pivot download: use source alias name for matching columns

### LINKED ISSUE #63858: Pivot Tables don't' Export Correctly if Columns have Long Names
### Describe the bug

If you create a pivot viz that contains Questions with really long column titles, the pivot export excludes columns from export.

### To Reproduce

https://www.loom.com/share/413f8a5792794c00a781fe1646f71547

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "athena",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-09-17",
      "tag": "v1.56.6",
      "hash": "c168e71"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "5.15.167.4-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

extremely annoying - cause and workaround are unclear to users

### Additional context

This has a work around but there is nothing at all that would tell a customer what the root cause is the a work around is extremely in obvious.

### PR DESCRIPTION
**Pull request by sansolovyov**
fixes #63858 

Why this change makes sense: `column-alias->index` was added in 18bfb2052304a5a2e6204fe2d07328d980147e3c where apparently using `:name` was not enough to uniquefy column names. It seems like what's stored in `:name` got changed over time, because `pivot-long-column-names-download-test` (introduced in that commit) is passing.

But we cannot just change `desired-column-alias` to `source-column-alias`, because we'll get two `sum` in that test and there is an override happening in that map. But we still need `source-column-alias` that has not been shortened, so we use this as a backup.

I haven't been able (by reading the code) to confirm what FE is doing for this though - somehow it gets full-length names in `:name`. :\

### CODE REVIEW

File: src/metabase/query_processor/pivot.clj [hunk 1]
```diff
@@ -391,16 +391,16 @@
         aggregations       (filter #(= (:lib/source %) :source/aggregations)
                                    returned-columns)
         breakouts          (filter :lib/breakout? returned-columns)
-        column-alias->index (into {}
-                                  (map-indexed (fn [i column] [(:lib/desired-column-alias column) i]))
+        source-alias->index (into {}
+                                  (map-indexed (fn [i column] [(:lib/source-column-alias column) i]))
```
Comment (bshepherdson) [inline src/metabase/query_processor/pivot.clj]: These many permutations of column names are a perennial pain point both inside the lib and outside.

To illustrate, consider that each stage (or referenced card) is an inner query, so we have a shape like this:
`SELECT later stage things FROM (SELECT SourceAlias.SourceColumnAlias AS DesiredColumnAlias FROM ...) AS "source"`

On `lib/returned-columns`, we see the columns as they appear _inside_ the inner query's `SELECT`. A later stage, or in your case the output of the entire query, will see the columns **named by their `:lib/desired-column-alias`**.

If the truncation is a problem, use `:lib/deduplicated-name` instead, which gets `_2` unique names like `:lib/desired-column-alias` but never gets truncated.

`:lib/source-column-alias` is being used in the wrong scope here. While it's not truncated, it is not a unique key for two reasons: it doesn't include any join alias, and it hasn't had `_2` added in case of a collision.

**Review by bshepherdson — CHANGES_REQUESTED** [review]

File: src/metabase/query_processor/pivot.clj (hunk 1 above)
Comment (sansolovyov) [reply src/metabase/query_processor/pivot.clj]: @bshepherdson hah, I've spent some time pondering on those different properties of a field, but w/o having enough context it's hard. I took my swing and missed. 😁

How do you like the change now? I'm wondering if I should have a test that combines very long and duplicated names, do you think there is a chance something will be off in this case? :-)

File: src/metabase/query_processor/pivot.clj [hunk 2]
```diff
@@ -391,16 +391,16 @@
...
                                  (concat breakouts aggregations))
+        dedup-name->index  (into {}
+                                 (map-indexed (fn [i column] [(:lib/deduplicated-name column) i]))
+                                 (concat breakouts aggregations))
         process-columns    (fn process-columns [column-names]
                              (when (seq column-names)
-                               (into [] (keep (fn [n] (or (column-alias->index n)
-                                                          (column-name->index n)))) column-names)))
+                               (into [] (keep (fn [n] (or (column-name->index n)
+                                                          (dedup-name->index n)))) column-names)))
```
Comment (bshepherdson) [inline src/metabase/query_processor/pivot.clj]: Prioritize the deduplicated name for matching. I cannot stress enough how little you should rely on `:name`.

**Review by bshepherdson — APPROVED** [review]
