### PR TITLE
Handle api/tiles requests for native queries

### LINKED ISSUE #4394: Pin Maps with more than 1000 results (LeafletTilePinMap) not working with native queries
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome and firefox
- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
MySQL
- Metabase version: (e.x. 0.19.3)
0.22.2
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Azure/"DC/OS"/Marathon/Docker
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Postgres
- *Repeatable steps to reproduce the issue*
Generate a pin map from a custom query with long lat. If the query has 999 of fewer results it displays fine, otherwise it crashes.
The error on the client is 
`https://our-domain.com/api/tiles/8/46/94/undefined/undefined/2/3/?query…ourquery Failed to load resource: the server responded with a status of 404 (Not Found)`
and the server logs
`02-15 17:23:38 [1mDEBUG metabase.middleware[0m :: [31mGET /api/tiles/8/47/93/undefined/undefined/2/3/ 404 (80 µs) (0 DB calls)[0m
"GET /api/tiles/8/47/93/undefined/undefined/2/3/ does not exist."`

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes #4394 

Ordinarily the api takes the source query and adds in a filter clause
for a region:

```clojure
;; card's query
{:database 19
 :query {:source-table 88
         :fields [[:field 562 nil]
                  [:field 574 nil]
                  [:field 576 nil]]
         :limit 2000}
 :type :query}

;; add a filter to only get coordinates inside of a region for a tile
{:database 19
 :query {:source-table 88
         :fields [[:field 562 nil]
                  [:field 574 nil]
                  [:field 576 nil]]
         :limit 2000
         :filter [:inside
                  [:field 576 nil]
                  [:field 574 nil]
                  -40.97989944013222
                  -179.99999564141046
                  -66.51326189011354
                  -134.99999673105785]}
 :type :query
 :async? false}
```

But when native, this would break, for three different reasons:
- native queries don't necessarily (or possibly) know their field
ids. So the api request it would construct would have `undefined` in the
slot where the field-id would normally go. This would cause the route to
404 as it would fail to match the expected numeric part of the url
- just passing in the field name isn't suffiencient, because mbql cannot
natively use an mbql filter clause into a native snippet. We do this to
a limited extent with filters and substitution but this requires a
marker like `{{filter}}` placeholder for us to add the filter text.
- when using `[:field name ...]` type field references we need the
base-type of a field in order to construct a query.

So the solution:
- allow the route to take field ids or names
- if native, rewrite the query to be a nested query using the native
query as the source query. ie, "select name, lat, long from table" ->
"select source.* from (select name, lat, long from table) source" but in
mbql so we can add our fliter clause
- if a string name is passed in, annotate it with a base-type of
:type/Float since we are dealing with lats and longs.

A concern was that we need to include the source-metadata. I'm omitting
this because we are essentially "select * from nested" so we just take
what we want, and the route already expects the index of the lat and
long columns and then selects only those from the query results.

As it stands we end up with a working query but a log

```
2021-11-02 14:37:25,470 DEBUG middleware.log :: GET /api/tiles/2/1/1/latitude/longitude/1/2/ 200 47.3 ms (5 DB calls) App DB connections: 2/13 Jetty threads: 9/50 (2 idle, 0 queued) (128 total active threads) Queries in flight: 0 (0 queued); postgres DB 19 connections: 3/6 (0 threads blocked)
2021-11-02 14:37:25,474 WARN middleware.add-implicit-clauses :: Warning: cannot determine fields for an explicit `source-query` unless you also include `source-metadata`.
2021-11-02 14:37:25,490 WARN middleware.add-implicit-clauses :: Warning: cannot determine fields for an explicit `source-query` unless you also include `source-metadata`.
2021-11-02 14:37:25,501 DEBUG middleware.log :: GET /api/tiles/2/0/2/latitude/longitude/1/2/ 200 39.4 ms (5 DB calls) App DB connections: 1/13 Jetty threads: 8/50 (2 idle, 0 queued) (128 total active threads) Queries in flight: 0 (0 queued); postgres DB 19 connections: 2/6 (0 threads blocked)
```

It might be possible to suppress these logs when we are in a query
context of `:map-tiles`. Or we might be able to require the frontend to
send along the metadata to include in the query. I didn't do this yet
since it seems to work fine and it would just make the urls quite long
if there are lots of columns (and the metadata can get quite verbose).

```clojure
;; source query of the card
{:type :native
 :native {:query "select name, latitude, longitude from zomato limit 2000;"
          :template-tags {}}
 :database 19}

;; nest it into a source query
{:database 19
 :type :query
 :query {:source-query {:template-tags {}
                        :native "select name, latitude, longitude from zomato limit 2000;"}}}

;; add the `:inside` filter for the tile

{:database 19
 :type :query
 :query {:source-query {:template-tags {}
                        :native "select name, latitude, longitude from zomato limit 2000;"}
         :filter [:inside
                  [:field
                   "latitude"
                   {:base-type :type/Float}]
                  [:field
                   "longitude"
                   {:base-type :type/Float}]
                  0.0
                  89.99999782070523
                  -66.51326189011354
                  179.99999564141046]}
 :async? false}
```

### CODE REVIEW

**Comment by dpsutton** [comment]
@ranquild adding you here because i did a change to how the api is called. Can you let me know if it needs to be different or more robust? I suspect we may need to url encode it but a) wasn't sure if column names can even have weird stuff like that although i suspect they can and b) the best way to do so.

**Comment by ranquild** [comment]
> @ranquild adding you here because i did a change to how the api is called. Can you let me know if it needs to be different or more robust? I suspect we may need to url encode it but a) wasn't sure if column names can even have weird stuff like that although i suspect they can and b) the best way to do so.

@dpsutton yep, I would replace 
```
(latitudeField.id || latitudeField.name) +
```
with
```
(latitudeField.id || encodeURIComponent(latitudeField.name)) +
```
and the same for `longitude`.

**Review by ranquild — COMMENTED** [review]
Tested the fix and it seems to be working correctly. Please add encoding to column names in `LeatletTitlePinMap`.

**Review by jeff303 — APPROVED** [review]

File: src/metabase/api/tiles.clj [hunk 1]
```diff
@@ -109,40 +112,59 @@
...
+    query))
 
 
 ;;; ---------------------------------------------------- ENDPOINT ----------------------------------------------------
 
+(defn- int-or-string
+  "Parse a string into an integer if it can be otherwise return the string. Intended to determine whether something is a
+  field id or a field name."
+  [x]
+  (try (Integer/parseInt x)
```
Comment (jeff303) [inline src/metabase/api/tiles.clj:132]: I don't really love this, but I suppose it's cheaper than checking the string with a regex or something first.

Comment (dpsutton) [reply src/metabase/api/tiles.clj:132]: the assumption is that it is either an integer or a column name. We could switch it to `(if (re-matches #"\d*" x))` but i suspect that is basically what parseInt is doing. Happy to change if you have a strong opinion.

**Comment by dpsutton** [comment]
@metabase-bot backport release-x.41.x
