### PR TITLE
Fix order by field refs

### LINKED ISSUE #44653: Unable to sort by the breakout column
### Describe the bug

Stats, see the link below, I get this error "ERROR: column "source.created_at" must appear in the GROUP BY clause or be used in an aggregate function Position: 2383"

Screenshot 2024-06-24 at 9 48 24 PM

### To Reproduce

https://stats.metabase.com/question/18343-repro-for-44653

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
stats
```

### Severity

P1 - can't sort 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes https://github.com/metabase/metabase/issues/44653

### Description

Problem _is_ that lib returns integer field ref from `orderable-columns` and string field ref presumably from `breakoutable-columns` if source table references a model.

QP middleware `add-implicit-clauses`, while attempting to add breakout columns to order by, did not recognize those, which reference same column as already referenced by other order by elements. That resulted in a duplicates (or near duplicates, that are also incorrect).

This PR mitigates that by (1) adding a check, if there are any _top level order by elements that are integer field refs_, and that reference same fields as string field references in breakout. (2) If there are, those are swapped for field refs from breakout.

Aside, on 49 integer field ids are used consistently. I recall reading somewhere we should aim for string ids. I was unable to find reasonable way of achieving that in a lib code, hence this fix. The underlying problem, of this and multiple other issues, will be solved by field refs effort that hopefully will take place soon.

### How to verify

Execute reproduction from linked issue. See modified and added tests.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/middleware/add_implicit_clauses.clj [hunk 1]
```diff
@@ -117,14 +117,49 @@
...
+
+  Reference: https://github.com/metabase/metabase/issues/44653."
+  [{:keys [breakout order-by] :as inner-query}]
+  (if (or (empty? breakout) (empty? order-by))
+    inner-query
+    (let [name->breakout (into {}
+                               (keep (fn [[tag id-or-name :as clause]]
+                                       (when (and (= :field tag)
+                                                  (string? id-or-name))
+                                         [id-or-name clause])))
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/add_implicit_clauses.clj:140]: Keying on the `id-or-name` might cause collisions, eg. if we breakout on the same field twice with different time granularity. (That's not really supported right now, but the point stands.)

However I don't know if that really matters in this case, since the ordering will still be the same.
I've noted this PR as a case to test in the multiple-breakouts doc.

File: src/metabase/query_processor/middleware/add_implicit_clauses.clj [hunk 2]
```diff
@@ -117,14 +117,49 @@
...
+              (partial reduce (fn [acc [dir [tag id-or-name] :as order-by]]
+                                (conj acc (or (and (= :field tag)
+                                                   (integer? id-or-name)
+                                                   (let [name ((some-fn :lib/desired-column-alias :name)
+                                                               (lib.metadata/field (qp.store/metadata-provider)
+                                                                                   id-or-name))]
+                                                     (when-some [breakout (name->breakout name)]
+                                                       [dir breakout])))
+                                              order-by)))
+                       [])))))
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/add_implicit_clauses.clj:152]: This is hard to read. `(reduce (fn [acc x] (conj x ...)) [] xs)` is `mapv`, so let's start there.

In a case like this with nontrivial logic inside, I think `(update inner-query :order-by #(vec (for [order-by %] ...)))` would be easier to read, but factoring out the inner function is usually better.

The `(and ...)` case distilling the ref into the field name makes a nice factor. Then the `mapv` function is
```clojure
(if-let [breakout (-> inner-ref ref->field-name name->breakout))]
  [dir breakout]
  order-by)```

**Review by bshepherdson — APPROVED** [review]

File: src/metabase/query_processor/middleware/add_implicit_clauses.clj (hunk 1 above)
Comment (lbrdnk) [reply src/metabase/query_processor/middleware/add_implicit_clauses.clj:140]: > That's not really supported right now, but the point stands.
That's true. I'm not sure, but I'd expect support for that being added as part of refs revamp. Then, hopefully, this function will become redundant.

File: src/metabase/query_processor/middleware/add_implicit_clauses.clj (hunk 2 above)
Comment (lbrdnk) [reply src/metabase/query_processor/middleware/add_implicit_clauses.clj]: Thanks for the pointer. I've modified the the code to use `mapv` and moved the inner logic into 2 functions bound in `let`. I haven't used `letfn` to avoid another nesting.
