### PR TITLE
Fix failed to dismiss spinner when db has no tables

### LINKED ISSUE #30837: dismiss_spinner generates wrong SQL
### Describe the bug

dismissing the spinner on a db that does syncing generates badly formed SQL. Testing this with a snowflake:
```
metabase-snowflake         | 2023-05-17 22:08:54,668 ERROR middleware.log :: POST /api/database/3/dismiss_spinner 500 26.2 ms (8 DB calls) 
metabase-snowflake         | {:via
metabase-snowflake         |  [{:type clojure.lang.ExceptionInfo,
metabase-snowflake         |    :message "ERROR: syntax error at or near \")\"\n  Position: 71",
metabase-snowflake         |    :data
metabase-snowflake         |    {:toucan2/context-trace
metabase-snowflake         |     [["execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection"
metabase-snowflake         |       {:toucan2.jdbc.query/sql-args
metabase-snowflake         |        ["UPDATE \"metabase_table\" SET \"initial_sync_status\" = ? WHERE \"id\" IN ()" "complete"]}]
metabase-snowflake         |      ["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}]
metabase-snowflake         |      ["resolve connection" {:toucan2.connection/connectable :default}]
metabase-snowflake         |      ["resolve connection" {:toucan2.connection/connectable nil}]
metabase-snowflake         |      {:toucan2.pipeline/rf
metabase-snowflake         |       #object[clojure.core$completing$fn__8528 0xb0a3a5e "clojure.core$completing$fn__8528@b0a3a5e"]}
metabase-snowflake         |      ["with compiled query"
metabase-snowflake         |       {:toucan2.pipeline/compiled-query
metabase-snowflake         |        ["UPDATE \"metabase_table\" SET \"initial_sync_status\" = ? WHERE \"id\" IN ()" "complete"]}]
metabase-snowflake         |      ["with built query"
metabase-snowflake         |       {:toucan2.pipeline/built-query
metabase-snowflake         |        {:update [:metabase_table], :set {:initial_sync_status "complete"}, :where [:in :id ()]}}]
metabase-snowflake         |      ["with resolved query" {:toucan2.pipeline/resolved-query {:id [:in ()]}}]
metabase-snowflake         |      ["with parsed args"
metabase-snowflake         |       {:toucan2.pipeline/query-type :toucan.query-type/update.update-count,
metabase-snowflake         |        :toucan2.pipeline/parsed-args {:queryable {:id [:in ()]}, :changes {:initial_sync_status "complete"}}}]
metabase-snowflake         |      ["with model" {:toucan2.pipeline/model (toucan.db/->SimpleModel :metabase.models.table/Table)}]
metabase-snowflake         |      ["with unparsed args"
metabase-snowflake         |       {:toucan2.pipeline/query-type :toucan.query-type/update.update-count,
metabase-snowflake         |        :toucan2.pipeline/unparsed-args
metabase-snowflake         |        ((toucan.db/->SimpleModel :metabase.models.table/Table) {:id [:in ()]} {:initial_sync_status "complete"})}]]},
metabase-snowflake         |    :at [org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2676]}
metabase-snowflake         |   {:type org.postgresql.util.PSQLException,
metabase-snowflake         |    :message "ERROR: syntax error at or near \")\"\n  Position: 71",
metabase-snowflake         |    :at [org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2676]}],
metabase-snowflake         |  :trace
metabase-snowflake         |  [[org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2676]
metabase-snowflake         |   [org.postgresql.core.v3.QueryExecutorImpl processResults "QueryExecutorImpl.java" 2366]
metabase-snowflake         |   [org.postgresql.core.v3.QueryExecutorImpl execute "QueryExecutorImpl.java" 356]
metabase-snowflake         |   [org.postgresql.jdbc.PgStatement executeInternal "PgStatement.java" 496]
metabase-snowflake         |   [org.postgresql.jdbc.PgStatement execute "PgStatement.java" 413]
metabase-snowflake         |   [org.postgresql.jdbc.PgPreparedStatement executeWithFlags "PgPreparedStatement.java" 190]
metabase-snowflake         |   [org.postgresql.jdbc.PgPreparedStatement execute "PgPreparedStatement.java" 177]
metabase-snowflake         |   [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement execute "NewProxyPreparedStatement.java" 67]
metabase-snowflake         |   [toucan2.jdbc.query$reduce_jdbc_query invokeStatic "query.clj" 40]
metabase-snowflake         |   [toucan2.jdbc.query$reduce_jdbc_query invoke "query.clj" 22]
metabase-snowflake         |   [toucan2.query_execution_backend.jdbc$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default
metabase-snowflake         |    invokeStatic
metabase-snowflake         |    "jdbc.clj"
metabase-snowflake         |    21]
metabase-snowflake         |   [toucan2.query_execution_backend.jdbc$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default
metabase-snowflake         |    invoke
metabase-snowflake         |    "jdbc.clj"
metabase-snowflake         |    11]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 178]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 137]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 675]
metabase-snowflake         |   [clojure.core$partial$fn__5908 doInvoke "core.clj" 2639]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 146]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 137]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 667]
metabase-snowflake         |   [clojure.core$apply invoke "core.clj" 662]
metabase-snowflake         |   [methodical.impl.combo.threaded$fn__19588$fn__19589$fn__19596 invoke "threaded.clj" 79]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558$fn__19562 invoke "threaded.clj" 23]
metabase-snowflake         |   [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
metabase-snowflake         |   [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
metabase-snowflake         |   [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
metabase-snowflake         |   [clojure.core$reduce invokeStatic "core.clj" 6886]
metabase-snowflake         |   [clojure.core$reduce invoke "core.clj" 6868]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558 invoke "threaded.clj" 21]
metabase-snowflake         |   [clojure.core$comp$fn__5876 doInvoke "core.clj" 2589]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 146]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 675]
metabase-snowflake         |   [clojure.core$apply doInvoke "core.clj" 662]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 533]
metabase-snowflake         |   [methodical.impl.combo.threaded$combine_with_threader$fn__19568 doInvoke "threaded.clj" 46]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 151]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 137]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 675]
metabase-snowflake         |   [clojure.core$apply doInvoke "core.clj" 662]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 533]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 65]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn doInvoke "standard.clj" 47]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 594]
metabase-snowflake         |   [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 199]
metabase-snowflake         |   [toucan2.pipeline$transduce_execute$with_connection_STAR___24258$with_transaction_STAR___24259
metabase-snowflake         |    invoke
metabase-snowflake         |    "pipeline.clj"
metabase-snowflake         |    82]
metabase-snowflake         |   [toucan2.connection$bind_current_connectable_fn$fn__23875 invoke "connection.clj" 104]
metabase-snowflake         |   [toucan2.connection$do_with_transaction_primary_method_java_sql_Connection$fn__23937 invoke "connection.clj" 277]
metabase-snowflake         |   [next.jdbc.transaction$transact_STAR_ invokeStatic "transaction.clj" 72]
metabase-snowflake         |   [next.jdbc.transaction$transact_STAR_ invoke "transaction.clj" 51]
metabase-snowflake         |   [next.jdbc.transaction$fn__23363 invokeStatic "transaction.clj" 122]
metabase-snowflake         |   [next.jdbc.transaction$fn__23363 invoke "transaction.clj" 115]
metabase-snowflake         |   [next.jdbc.protocols$fn__22523$G__22518__22532 invoke "protocols.clj" 58]
metabase-snowflake         |   [next.jdbc$transact invokeStatic "jdbc.clj" 381]
metabase-snowflake         |   [next.jdbc$transact invoke "jdbc.clj" 373]
metabase-snowflake         |   [toucan2.connection$do_with_transaction_primary_method_java_sql_Connection invokeStatic "connection.clj" 276]
metabase-snowflake         |   [toucan2.connection$do_with_transaction_primary_method_java_sql_Connection invoke "connection.clj" 270]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 165]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 457]
metabase-snowflake         |   [clojure.core$partial$fn__5908 invoke "core.clj" 2643]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [methodical.impl.combo.threaded$fn__19588$fn__19589$fn__19592 invoke "threaded.clj" 71]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558$fn__19562 invoke "threaded.clj" 23]
metabase-snowflake         |   [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
metabase-snowflake         |   [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
metabase-snowflake         |   [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
metabase-snowflake         |   [clojure.core$reduce invokeStatic "core.clj" 6886]
metabase-snowflake         |   [clojure.core$reduce invoke "core.clj" 6868]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558 invoke "threaded.clj" 21]
metabase-snowflake         |   [clojure.core$comp$fn__5876 invoke "core.clj" 2588]
metabase-snowflake         |   [methodical.impl.combo.threaded$combine_with_threader$fn__19568 invoke "threaded.clj" 44]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [metabase.db.connection$do_with_transaction_around_method_java_sql_Connection invokeStatic "connection.clj" 145]
metabase-snowflake         |   [metabase.db.connection$do_with_transaction_around_method_java_sql_Connection invoke "connection.clj" 141]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 165]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 457]
metabase-snowflake         |   [clojure.core$partial$fn__5908 invoke "core.clj" 2643]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [toucan2.connection$do_with_transaction_around_method_toucan2_connection_default invokeStatic "connection.clj" 268]
metabase-snowflake         |   [toucan2.connection$do_with_transaction_around_method_toucan2_connection_default invoke "connection.clj" 264]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 165]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 457]
metabase-snowflake         |   [clojure.core$partial$fn__5908 invoke "core.clj" 2643]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 58]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
metabase-snowflake         |   [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 195]
metabase-snowflake         |   [toucan2.pipeline$transduce_execute$with_connection_STAR___24258 invoke "pipeline.clj" 80]
metabase-snowflake         |   [toucan2.connection$bind_current_connectable_fn$fn__23875 invoke "connection.clj" 104]
metabase-snowflake         |   [toucan2.connection$bind_current_connectable_fn$fn__23875 invoke "connection.clj" 104]
metabase-snowflake         |   [toucan2.connection$bind_current_connectable_fn$fn__23875 invoke "connection.clj" 104]
metabase-snowflake         |   [toucan2.connection$do_with_connection_primary_method_javax_sql_DataSource invokeStatic "connection.clj" 213]
metabase-snowflake         |   [toucan2.connection$do_with_connection_primary_method_javax_sql_DataSource invoke "connection.clj" 210]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 156]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 421]
metabase-snowflake         |   [methodical.impl.combo.threaded$fn__19588$fn__19589$fn__19590 invoke "threaded.clj" 70]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558$fn__19562 invoke "threaded.clj" 23]
metabase-snowflake         |   [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
metabase-snowflake         |   [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
metabase-snowflake         |   [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
metabase-snowflake         |   [clojure.core$reduce invokeStatic "core.clj" 6886]
metabase-snowflake         |   [clojure.core$reduce invoke "core.clj" 6868]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558 invoke "threaded.clj" 21]
metabase-snowflake         |   [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
metabase-snowflake         |   [methodical.impl.combo.threaded$combine_with_threader$fn__19568 invoke "threaded.clj" 43]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 156]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 421]
metabase-snowflake         |   [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invokeStatic "connection.clj" 118]
metabase-snowflake         |   [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invoke "connection.clj" 106]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 156]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 421]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 55]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
metabase-snowflake         |   [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 193]
metabase-snowflake         |   [metabase.db.connection$do_with_connection_primary_method_default invokeStatic "connection.clj" 139]
metabase-snowflake         |   [metabase.db.connection$do_with_connection_primary_method_default invoke "connection.clj" 137]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 156]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 421]
metabase-snowflake         |   [methodical.impl.combo.threaded$fn__19588$fn__19589$fn__19590 invoke "threaded.clj" 70]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558$fn__19562 invoke "threaded.clj" 23]
metabase-snowflake         |   [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
metabase-snowflake         |   [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
metabase-snowflake         |   [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
metabase-snowflake         |   [clojure.core$reduce invokeStatic "core.clj" 6886]
metabase-snowflake         |   [clojure.core$reduce invoke "core.clj" 6868]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558 invoke "threaded.clj" 21]
metabase-snowflake         |   [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
metabase-snowflake         |   [methodical.impl.combo.threaded$combine_with_threader$fn__19568 invoke "threaded.clj" 43]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 156]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 421]
metabase-snowflake         |   [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invokeStatic "connection.clj" 118]
metabase-snowflake         |   [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invoke "connection.clj" 106]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 156]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 421]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 55]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
metabase-snowflake         |   [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 193]
metabase-snowflake         |   [toucan2.connection$do_with_connection_primary_method_ invokeStatic "connection.clj" 204]
metabase-snowflake         |   [toucan2.connection$do_with_connection_primary_method_ invoke "connection.clj" 194]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 156]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 421]
metabase-snowflake         |   [methodical.impl.combo.threaded$fn__19588$fn__19589$fn__19590 invoke "threaded.clj" 70]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558$fn__19562 invoke "threaded.clj" 23]
metabase-snowflake         |   [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
metabase-snowflake         |   [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
metabase-snowflake         |   [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
metabase-snowflake         |   [clojure.core$reduce invokeStatic "core.clj" 6886]
metabase-snowflake         |   [clojure.core$reduce invoke "core.clj" 6868]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558 invoke "threaded.clj" 21]
metabase-snowflake         |   [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
metabase-snowflake         |   [methodical.impl.combo.threaded$combine_with_threader$fn__19568 invoke "threaded.clj" 43]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 156]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 421]
metabase-snowflake         |   [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invokeStatic "connection.clj" 118]
metabase-snowflake         |   [toucan2.connection$do_with_connection_around_method_toucan2_connection_default invoke "connection.clj" 106]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [clojure.core$partial$fn__5908 invoke "core.clj" 2642]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 156]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 132]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 421]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 55]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invoke "standard.clj" 47]
metabase-snowflake         |   [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 193]
metabase-snowflake         |   [toucan2.pipeline$transduce_execute invokeStatic "pipeline.clj" 80]
metabase-snowflake         |   [toucan2.pipeline$transduce_execute invoke "pipeline.clj" 70]
metabase-snowflake         |   [clojure.lang.Var invoke "Var.java" 399]
metabase-snowflake         |   [toucan2.pipeline$transduce_compiled_query invokeStatic "pipeline.clj" 278]
metabase-snowflake         |   [toucan2.pipeline$transduce_compiled_query invoke "pipeline.clj" 274]
metabase-snowflake         |   [toucan2.pipeline$transduce_built_query invokeStatic "pipeline.clj" 286]
metabase-snowflake         |   [toucan2.pipeline$transduce_built_query invoke "pipeline.clj" 280]
metabase-snowflake         |   [toucan2.pipeline$transduce_query_primary_method_default invokeStatic "pipeline.clj" 312]
metabase-snowflake         |   [toucan2.pipeline$transduce_query_primary_method_default invoke "pipeline.clj" 309]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 178]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 137]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 675]
metabase-snowflake         |   [clojure.core$partial$fn__5908 doInvoke "core.clj" 2639]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 146]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 482]
metabase-snowflake         |   [toucan.db$transduce_query_primary_method_default_SimpleModel_default invokeStatic "db.clj" 332]
metabase-snowflake         |   [toucan.db$transduce_query_primary_method_default_SimpleModel_default invoke "db.clj" 329]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 178]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 137]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 675]
metabase-snowflake         |   [clojure.core$partial$fn__5908 doInvoke "core.clj" 2639]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 146]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 137]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 667]
metabase-snowflake         |   [clojure.core$apply invoke "core.clj" 662]
metabase-snowflake         |   [methodical.impl.combo.threaded$fn__19588$fn__19589$fn__19596 invoke "threaded.clj" 79]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558$fn__19562 invoke "threaded.clj" 23]
metabase-snowflake         |   [clojure.lang.ArrayChunk reduce "ArrayChunk.java" 58]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invokeStatic "protocols.clj" 136]
metabase-snowflake         |   [clojure.core.protocols$fn__8244 invoke "protocols.clj" 124]
metabase-snowflake         |   [clojure.core.protocols$fn__8204$G__8199__8213 invoke "protocols.clj" 19]
metabase-snowflake         |   [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
metabase-snowflake         |   [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
metabase-snowflake         |   [clojure.core$reduce invokeStatic "core.clj" 6886]
metabase-snowflake         |   [clojure.core$reduce invoke "core.clj" 6868]
metabase-snowflake         |   [methodical.impl.combo.threaded$reducer_fn$fn__19558 invoke "threaded.clj" 21]
metabase-snowflake         |   [clojure.core$comp$fn__5876 doInvoke "core.clj" 2589]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 146]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 675]
metabase-snowflake         |   [clojure.core$apply doInvoke "core.clj" 662]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 533]
metabase-snowflake         |   [methodical.impl.combo.threaded$combine_with_threader$fn__19568 doInvoke "threaded.clj" 46]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 151]
metabase-snowflake         |   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
metabase-snowflake         |   [clojure.lang.RestFn applyTo "RestFn.java" 137]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 675]
metabase-snowflake         |   [clojure.core$apply doInvoke "core.clj" 662]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 533]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn invokeStatic "standard.clj" 65]
metabase-snowflake         |   [methodical.impl.standard$invoke_multifn doInvoke "standard.clj" 47]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 594]
metabase-snowflake         |   [methodical.impl.standard.StandardMultiFn invoke "standard.clj" 199]
metabase-snowflake         |   [toucan2.pipeline$transduce_query_STAR_ invokeStatic "pipeline.clj" 318]
metabase-snowflake         |   [toucan2.pipeline$transduce_query_STAR_ invoke "pipeline.clj" 314]
metabase-snowflake         |   [toucan2.pipeline$transduce_with_model invokeStatic "pipeline.clj" 333]
metabase-snowflake         |   [toucan2.pipeline$transduce_with_model invoke "pipeline.clj" 320]
metabase-snowflake         |   [toucan2.pipeline$transduce_parsed invokeStatic "pipeline.clj" 349]
metabase-snowflake         |   [toucan2.pipeline$transduce_parsed invoke "pipeline.clj" 335]
metabase-snowflake         |   [toucan2.pipeline$transduce_unparsed invokeStatic "pipeline.clj" 357]
metabase-snowflake         |   [toucan2.pipeline$transduce_unparsed invoke "pipeline.clj" 351]
metabase-snowflake         |   [toucan2.pipeline$transduce_unparsed_with_default_rf invokeStatic "pipeline.clj" 414]
metabase-snowflake         |   [toucan2.pipeline$transduce_unparsed_with_default_rf invoke "pipeline.clj" 408]
metabase-snowflake         |   [toucan2.update$update_BANG_ invokeStatic "update.clj" 53]
metabase-snowflake         |   [toucan2.update$update_BANG_ doInvoke "update.clj" 50]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [toucan.db$update_where_BANG_ invokeStatic "db.clj" 343]
metabase-snowflake         |   [toucan.db$update_where_BANG_ doInvoke "db.clj" 334]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 464]
metabase-snowflake         |   [metabase.api.database$fn__95694 invokeStatic "database.clj" 991]
metabase-snowflake         |   [metabase.api.database$fn__95694 invoke "database.clj" 982]
metabase-snowflake         |   [compojure.core$wrap_response$fn__42375 invoke "core.clj" 160]
metabase-snowflake         |   [compojure.core$wrap_route_middleware$fn__42359 invoke "core.clj" 132]
metabase-snowflake         |   [compojure.core$wrap_route_info$fn__42364 invoke "core.clj" 139]
metabase-snowflake         |   [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 151]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387 invoke "core.clj" 200]
metabase-snowflake         |   [metabase.server.middleware.auth$enforce_authentication$fn__87427 invoke "auth.clj" 17]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387 invoke "core.clj" 200]
metabase-snowflake         |   [compojure.core$make_context$handler__42415 invoke "core.clj" 290]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 300]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 199]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 199]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387 invoke "core.clj" 200]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 199]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387 invoke "core.clj" 200]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387 invoke "core.clj" 200]
metabase-snowflake         |   [metabase.api.routes$fn__99241$fn__99242 invoke "routes.clj" 62]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387 invoke "core.clj" 200]
metabase-snowflake         |   [clojure.lang.AFn applyToHelper "AFn.java" 160]
metabase-snowflake         |   [clojure.lang.AFn applyTo "AFn.java" 144]
metabase-snowflake         |   [clojure.core$apply invokeStatic "core.clj" 667]
metabase-snowflake         |   [clojure.core$apply invoke "core.clj" 662]
metabase-snowflake         |   [metabase.server.routes$fn__99402$fn__99403 doInvoke "routes.clj" 70]
metabase-snowflake         |   [clojure.lang.RestFn invoke "RestFn.java" 436]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387 invoke "core.clj" 200]
metabase-snowflake         |   [compojure.core$make_context$handler__42415 invoke "core.clj" 290]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 300]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$wrap_route_matches$fn__42368 invoke "core.clj" 153]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 199]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389 invoke "core.clj" 197]
metabase-snowflake         |   [compojure.core$make_context$fn__42419 invoke "core.clj" 301]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387 invoke "core.clj" 200]
metabase-snowflake         |   [compojure.core$routes$fn__42387$f__42388 invoke "core.clj" 198]
metabase-snowflake         |   [compojure.core$routes$fn__42387 invoke "core.clj" 200]
metabase-snowflake         |   [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__95938 invoke "exceptions.clj" 103]
metabase-snowflake         |   [metabase.server.middleware.exceptions$catch_api_exceptions$fn__95935 invoke "exceptions.clj" 91]
metabase-snowflake         |   [metabase.server.middleware.log$log_api_call$fn__102699$fn__102700$fn__102701 invoke "log.clj" 216]
metabase-snowflake         |   [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
metabase-snowflake         |   [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
metabase-snowflake         |   [metabase.server.middleware.log$log_api_call$fn__102699$fn__102700 invoke "log.clj" 208]
metabase-snowflake         |   [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
metabase-snowflake         |   [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
metabase-snowflake         |   [metabase.server.middleware.log$log_api_call$fn__102699 invoke "log.clj" 207]
metabase-snowflake         |   [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__109422 invoke "browser_cookie.clj" 42]
metabase-snowflake         |   [metabase.server.middleware.security$add_security_headers$fn__80256 invoke "security.clj" 153]
metabase-snowflake         |   [metabase.server.middleware.json$wrap_json_body$fn__106674 invoke "json.clj" 67]
metabase-snowflake         |   [metabase.server.middleware.offset_paging$handle_paging$fn__80280 invoke "offset_paging.clj" 45]
metabase-snowflake         |   [metabase.server.middleware.json$wrap_streamed_json_response$fn__106692 invoke "json.clj" 103]
metabase-snowflake         |   [ring.middleware.keyword_params$wrap_keyword_params$fn__109689 invoke "keyword_params.clj" 55]
metabase-snowflake         |   [ring.middleware.params$wrap_params$fn__109708 invoke "params.clj" 77]
metabase-snowflake         |   [metabase.server.middleware.misc$maybe_set_site_url$fn__50479 invoke "misc.clj" 61]
metabase-snowflake         |   [metabase.server.middleware.session$reset_session_timeout$fn__63770 invoke "session.clj" 430]
metabase-snowflake         |   [metabase.server.middleware.session$bind_current_user$fn__63740$fn__63741 invoke "session.clj" 336]
metabase-snowflake         |   [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 315]
metabase-snowflake         |   [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 304]
metabase-snowflake         |   [metabase.server.middleware.session$bind_current_user$fn__63740 invoke "session.clj" 335]
metabase-snowflake         |   [metabase.server.middleware.session$wrap_current_user_info$fn__63722 invoke "session.clj" 285]
metabase-snowflake         |   [metabase.server.middleware.session$wrap_session_id$fn__63705 invoke "session.clj" 217]
metabase-snowflake         |   [metabase.server.middleware.auth$wrap_api_key$fn__87435 invoke "auth.clj" 30]
metabase-snowflake         |   [ring.middleware.cookies$wrap_cookies$fn__109609 invoke "cookies.clj" 216]
metabase-snowflake         |   [metabase.server.middleware.misc$add_content_type$fn__50461 invoke "misc.clj" 29]
metabase-snowflake         |   [metabase.server.middleware.misc$disable_streaming_buffering$fn__50487 invoke "misc.clj" 78]
metabase-snowflake         |   [ring.middleware.gzip$wrap_gzip$fn__109651 invoke "gzip.clj" 86]
metabase-snowflake         |   [metabase.server.middleware.misc$bind_request$fn__50490 invoke "misc.clj" 95]
metabase-snowflake         |   [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__109438 invoke "ssl.clj" 41]
metabase-snowflake         |   [metabase.server$async_proxy_handler$fn__101465 invoke "server.clj" 77]
metabase-snowflake         |   [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
metabase-snowflake         |   [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
metabase-snowflake         |   [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
metabase-snowflake         |   [org.eclipse.jetty.server.Server handle "Server.java" 563]
metabase-snowflake         |   [org.eclipse.jetty.server.HttpChannel lambda$handle$0 "HttpChannel.java" 505]
metabase-snowflake         |   [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 762]
metabase-snowflake         |   [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 497]
metabase-snowflake         |   [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 282]
metabase-snowflake         |   [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
metabase-snowflake         |   [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
metabase-snowflake         |   [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
metabase-snowflake         |   [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy runTask "AdaptiveExecutionStrategy.java" 416]
metabase-snowflake         |   [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy consumeTask "AdaptiveExecutionStrategy.java" 385]
metabase-snowflake         |   [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy tryProduce "AdaptiveExecutionStrategy.java" 272]
metabase-snowflake         |   [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy lambda$new$0 "AdaptiveExecutionStrategy.java" 140]
metabase-snowflake         |   [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 411]
metabase-snowflake         |   [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 936]
metabase-snowflake         |   [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1080]
metabase-snowflake         |   [java.lang.Thread run nil -1]],
metabase-snowflake         |  :cause "ERROR: syntax error at or near \")\"\n  Position: 71",
metabase-snowflake         |  :message "ERROR: syntax error at or near \")\"\n  Position: 71"}
metabase-snowflake         | 
```

### To Reproduce

1) add a DB
2) click the dismiss sync spinner, you'll get a 500

### Expected behavior

we shouldn't generate badly formed SQL to the App db

### Logs

above

### Information about your Metabase installation

```JSON
1.46.2
```

### Severity

P1

### Additional context

If you can't dismiss the spinner, then the FE will keep hitting the BE asking if the sync is done

Assigning snowflake only but I'm pretty sure this happens in all DB's

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes #30837

### CODE REVIEW

File: src/metabase/api/database.clj [hunk 1]
```diff
@@ -311,8 +311,8 @@
   (if-not include
     db
     (-> (t2/hydrate db (case include
-                      "tables"        :tables
-                      "tables.fields" [:tables [:fields [:target :has_field_values] :has_field_values]]))
+                        "tables"        :tables
+                        "tables.fields" [:tables [:fields [:target :has_field_values] :has_field_values]]))
```
Comment (calherries) [inline src/metabase/api/database.clj:315]: `case` should have a two-space indent
```suggestion
                         "tables"        :tables
                         "tables.fields" [:tables [:fields [:target :has_field_values] :has_field_values]]))
```

**Review by calherries — APPROVED** [review]
Nice
