### PR TITLE
fix: pivoting json values

### LINKED ISSUE #52687: Pivot table of a json field will show wrong data
### Describe the bug

We end up showing the same row on the grouping with counts of the real rows

Image

### To Reproduce

1) set up Metabase with MongoDB
2) add to the MongoDB this table

```
// Connect to your MongoDB database
use sample; // Replace 'myDatabase' with your database name

// Define the collection name
const collectionName = "myCollection";

// Drop the collection if it exists (optional, for clean slate)
db[collectionName].drop();

// Insert documents into the collection
db[collectionName].insertMany([
    {
        key1: "value1",
        key2: { nestedKey1: "nestedValue1", nestedKey2: null },
        key3: "value3",
        key4: null,
        key5: { nestedKey1: "nestedValue2" },
        key6: "value6",
        key7: null,
        key8: { nestedKey1: "nestedValue3", nestedKey2: "nestedValue4" },
        key9: null,
        key10: "value10"
    },
    {
        key1: null,
        key2: { nestedKey1: "nestedValue1" },
        key3: null,
        key4: "value4",
        key5: null,
        key6: { nestedKey1: "nestedValue5", nestedKey2: null },
        key7: "value7",
        key8: null,
        key9: { nestedKey1: "nestedValue6" },
        key10: null
    },
    {
        key1: "value1",
        key2: "value2",
        key3: null,
        key4: null,
        key5: { nestedKey1: "nestedValue7", nestedKey2: "nestedValue8" },
        key6: null,
        key7: "value7",
        key8: "value8",
        key9: null,
        key10: { nestedKey1: "nestedValue9" }
    },
    {
        key1: null,
        key2: null,
        key3: "value3",
        key4: { nestedKey1: "nestedValue10", nestedKey2: "nestedValue11" },
        key5: null,
        key6: null,
        key7: { nestedKey1: "nestedValue12" },
        key8: null,
        key9: "value9",
        key10: "value10"
    },
    {
        key1: "value1",
        key2: null,
        key3: "value3",
        key4: null,
        key5: { nestedKey1: "nestedValue13" },
        key6: { nestedKey1: "nestedValue14", nestedKey2: null },
        key7: null,
        key8: "value8",
        key9: null,
        key10: { nestedKey1: "nestedValue15", nestedKey2: "nestedValue16" }
    }
]);

print("Documents with nested properties inserted successfully!");
```

3) sync
4) go to a table view on that new table
5) Make a count of Key5

Image

6) Do a pivot table 

### Expected behavior

We should render the correct data

### Logs

NA

### Information about your Metabase installation

```JSON
v52.6
```

### Severity

P2 only because no one reported it yet

### Additional context

NA

### PR DESCRIPTION
**Pull request by edpaget**
closes #52687
### Description

Fixes displaying pivot values when they are JSON objects (as when working with Mongodb). There were two issues here one new since the issue was originally filed.

The new issue is that we were passing complex values as clojure datastructures to a a javascript function to format them. This function was ultimately just matching on typeof value === 'object' and formatting them using JSON.stringify which just left a bunch of clojure stuff. 

The old issue which resurfaced after fixing the first problem was that the memoize function in underscore just uses === to compare the value object for its cache which meant all object values passed the memoize function were treated as equal, so each value we formatted would return the same formatted output. This changes the memoize has function to JSON.stringify the value as a shortcut to make sure different objects aren't memoized together. 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by johnswanson — APPROVED** [review]

File: frontend/src/metabase/lib/data_grid.js [hunk 1]
```diff
@@ -49,7 +49,7 @@ export function multiLevelPivot(data, settings) {
     indexes.map((index) =>
       _.memoize(
         (value) => formatValue(value, columnSettings[index]),
-        (value) => [value, index].join(),
+        (value) => [JSON.stringify(value), index].join(),
```
Comment (iethree) [inline frontend/src/metabase/lib/data_grid.js]: this is probably technically more performant, but it certainly doesn't matter.

```suggestion
        (value) => JSON.stringify(value) + String(index),
```

**Review by alxnddr — APPROVED** [review]
