### PR TITLE
[QP] Fix `:fields` clauses in `nest-query` with extra aggs outside model

### LINKED ISSUE #43993: SQL "Unknown column" errors on 0.50.0 with breakouts on nested models
### Describe the bug

After updating to V0.50.0 the errors comes, some of fields turns to unkonw

### To Reproduce

After updating to V0.50.0 

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
Any information?
```

### Severity

 blocking usage of Metabase entirely

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bshepherdson**
Fixes #43993.

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#44182** <a href="https://app.graphite.dev/github/pr/metabase/metabase/44182?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bshepherdson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: test/metabase/query_processor/pivot_test.clj [hunk 1]
```diff
@@ -254,6 +254,68 @@
...
+            (is (=? {:status    :completed
+                     :row_count 1747}
+                    (-> query
+                        (assoc :info {:visualization-settings viz-settings})
+                        qp.pivot/run-pivot-query)))))))))
+
+(deftest model-with-aggregations-nested-pivot-aggregation-names-test
+  (testing "#43993"
+    (mt/dataset
+      test-data
```
Comment (snoe) [inline test/metabase/query_processor/pivot_test.clj:289]: is it necessary to use mt/dataset for `test-data`?

File: src/metabase/query_processor/util/nest_query.clj [hunk 2]
```diff
@@ -135,6 +149,9 @@
                            desired-alias (assoc ::add/source-alias desired-alias
                                                 ::add/desired-alias desired-alias))])
 
+    [:field (id-or-name :guard string?) (opts :guard ::add/source-alias)]
```
Comment (snoe) [inline src/metabase/query_processor/util/nest_query.clj:152]: is this making a nominal-ref? does similar need to be done for `:expression`? 
a comment for this condition would be helpful

**Review by snoe — APPROVED** [review]
lgtm

File: src/metabase/query_processor/util/nest_query.clj (hunk 2 above)
Comment (bshepherdson) [reply src/metabase/query_processor/util/nest_query.clj:152]: Not exactly. It's rewriting from naive `:name` to possibly adjusted source alias, for any nominal references in the outer layer of the query. There were cases where this was generating `"source"."ID"` when the column was really called `"source"."People - User__ID"`.

Regarding `:expression`, no, because they're in different stages so there wouldn't be an `:expression` ref, it would be a `:field` ref.

I'll add a comment explaining about this.

File: test/metabase/query_processor/pivot_test.clj (hunk 1 above)
Comment (bshepherdson) [reply test/metabase/query_processor/pivot_test.clj:289]: I'm not sure. I think if I want to mutate the DB I do need to set it up like this? I'm not very familiar, I was just following how it's done in similar mutation-y tests in this namespace.

I'll experiment with it.

File: src/metabase/query_processor/util/nest_query.clj (hunk 2 above)
Comment (bshepherdson) [reply src/metabase/query_processor/util/nest_query.clj:155]: Done.

File: test/metabase/query_processor/pivot_test.clj (hunk 1 above)
Comment (bshepherdson) [reply test/metabase/query_processor/pivot_test.clj]: Cleaned this up, and it still seems to work. I think `mt/with-temp` is sufficient for this one.
