### PR TITLE
Fix native question looses visualisation settings if query fails

### LINKED ISSUE #16914: After hiding the column and then setting a required default value for SQL field filter (connected to that column) shows all fields as hidden and breaks SQL filters completely
**Describe the bug**
It is not possible to set the required + default value for the SQL field filter on the column that was previously marked as hidden. Doing so shows **all** columns as hidden and completely breaks SQL filters functionality because it's not possible to set the filter through the widget or to even change the field that filter is connected to.

**Logs**
N/A

**To Reproduce**
1. Ask new question > Native
2. In the native editor enter `SELECT * FROM products where {{filter}}`
3. In the right sidebar, choose "Field Filter" as a type and connect it to the Products Category
4. Click play icon to run the query - it runs normally and doesn't apply the filter
5. Below the visualization results, choose "Settings"
6. Left sidebar will open, hide `CATEGORY` column, click "Done"
7. Rerun the query - everything still works now (setting the field value through the widget works at this point)
8. Set the filter as required
9. Set the default value to "Gizmo"
10. Rerun the query
11. Results will render "Every field is hidden right now" (but notice it says showing "Showing 51 rows")

After this point, no matter what you do it is not possible to get any results. The only option is to start the new query again.

**Expected behavior**
It should be possible to set the default field filter value even if the connected field is hidden. All other results should be shown.

**Screenshots**
image

**Information about your Metabase Installation:**
local dev, x.40.1-SNAPSHOT, `master`, 8e684e3

**Severity**
Seems pretty severe if you rely on this functionality, but it also seems like a FE issue which makes it a bit less daunting.

**Additional context**
Additional issue: String "Every field is hidden right now" is not translated.

The related code lives in `frontend/src/metabase/visualizations/visualizations/Table.jsx`

### PR DESCRIPTION
**Pull request by kulyk**
A regression caused by #16761 (Fix newly added columns don't appear after some columns are hidden
Fixes #16914

**Explanation**

From #16761 PR doc:

> Each question has a `table.columns` property in `visualization_settings`; it defines which columns are visible and which are hidden. For structured queries (simple and custom questions), the `table.columns` property is synced with the query itself. So if a new column is added or an existing one is removed, visualization settings stay in sync. It's impossible to do for native queries as Metabase doesn't parse SQL. This PR adds columns sync for native queries based on query _results_, rather than the query.

So, #16761 introduced a way to sync columns and viz settings for native questions based on `queryResults`.
The problem is it didn't handle a scenario when `queryResults` were actually an error. So it tried to sync columns and viz settings based on a failed query result, found no columns and just cleared the question's visualization settings.

Fixed by skipping columns and viz settings sync in case a query failed.

### To Verify

Huge thanks to @lukeman for making perfect repro steps 🙌 

1. Ask a question > Native Question > Sample Dataset
2. Enter `SELECT 'a' as a, 'b' as b`
3. Click the play icon to run the query
4. Click the "Settings" button in the bottom left
5. In the left sidebar hide column `a` and click "Done"
6. Add `foo` to the end of the query, so it looks like  `SELECT 'a' as a, 'b' as b foo`
7. Run the query to trigger a SQL error response
8. Remove the errant text, so the query looks like `SELECT 'a' as a, 'b' as b` again
9. Run the query
10. Ensure there is no "Every field is hidden right now" message; you should see column `B`, and no column `A`.

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/125466981-1e8c4d8c-895a-45d4-9d1e-667a0a831d45.mov

**After**

https://user-images.githubusercontent.com/17258145/125466999-8c06e85f-7ec3-4e08-96fd-e7b280a55ca3.mov

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/view/ViewFooter.jsx [hunk 1]
```diff
@@ -191,14 +191,28 @@ const VizTypeButton = ({ question, result, ...props }) => {
...
 const VizSettingsButton = ({ ...props }) => (
-  <ViewButton medium p={[2, 1]} icon="gear" labelBreakpoint="sm" {...props}>
+  <ViewButton
+    medium
+    p={[2, 1]}
+    icon="gear"
+    labelBreakpoint="sm"
+    data-testid="viz-settings-button"
+    {...props}
+  >
```
Comment (kulyk) [inline frontend/src/metabase/query_builder/components/view/ViewFooter.jsx:215]: Added `data-testid` here, so it's easier to distinguish visualization settings button and the "settings" tab on the right sidebar for SQL filters

CleanShot 2021-07-13 at 17 14 44@2x

File: frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js [hunk 2]
```diff
@@ -28,3 +28,14 @@ export function openNativeEditor(alias = "editor") {
...
+/**
+ * Executes native query and waits for the results to load.
+ * Makes sure that the question is not "dirty" after the query successfully ran.
+ * @param {string} [xhrAlias ="dataset"]
+ */
+export function runNativeQuery(xhrAlias = "dataset") {
+  cy.get(".NativeQueryEditor .Icon-play").click();
+  cy.wait("@" + xhrAlias);
+  cy.icon("play").should("not.exist");
+}
```
Comment (kulyk) [inline frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js:41]: @nemanjaglumac I just copy-pasted this from [e2e-sql-filter-helpers](https://github.com/metabase/metabase/blob/6db73b0cfa743eefd2034ace9dd04d9b2c638d9f/frontend/test/metabase/scenarios/filters/helpers/e2e-sql-filter-helpers.js#L82) to `__support__/e2e/e2e-misc-helpers`, as it's very handy for the `native` test suite as well. Didn't like the idea to import helpers from another test group. Does it make sense to you? If so, I can follow up with a PR updating SQL filters tests to use this

Comment (nemanjaglumac) [reply frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js:41]: It's great that this happened.

There are going to be **many** helpers that are not tied to the specific folder only. I'm actually starting to think that ALL e2e helpers should live in the same place and be available to all tests. We should just import selectively.

Not sure how to approach the current situation you're in right now. Copy/pasting this helper into misc helpers doesn't seem like a good long term solution. We might end up duplicating a lot of the code and forgetting about it later.

In order to unblock you, feel free to proceed with this, and I'll deal with it later.
Thanks for the quick fix and great explanation of the problem.

**Review by flamber — APPROVED** [review]
Awesome - I tried a couple of other ways to break this.

I'm not able to restore a question (without reverting to a revision), which I created on 0.40.0. It just continues to display this error.
Would it be possible to restore any existing questions (without manual request fiddling or revision)?
That might also fix 13208

This should probably go into `release-x.40.x` - or are you going to cherry-pick after merge?

**Comment by kulyk** [comment]
Thanks @flamber

> I'm not able to restore a question, which I created on 0.40.0. It just continues to display this error.
Would it be possible to restore any existing questions (without manual request fiddling)?

I was able to restore the results, but not sure about visualization settings, there is nothing to rely on after a failed query runs for a broken question

> This should probably go into `release-x.40.x` - or are you going to cherry-pick after merge?

Yes, we're now opening bug fix PRs against `master` and then open a cherry-pick PR for the release branch

**Comment by kulyk** [comment]
@flamber I pushed a fix, could you please pull the latest changes and check if you can restore a question?

**Comment by flamber** [comment]
@kulyk 
Already playing around in it. Works perfectly and restores the broken questions without me having to do anything - it's magic! :mage: 
I'm still going to play around with this some more, since I just want to make sure that we aren't causing some weird problem from this, but not seeing anything bad. But my brain is mush, so will continue tomorrow.
LGTM

**Comment by kulyk** [comment]
Thanks, @flamber, glad to hear that! Merging this for now, please LMK if you find something else
