### PR TITLE
fix bar normalized stacking breaks line charts

### LINKED ISSUE #43538: Switching from a `stack - 100%` chart to a line chart causes the line chart to break
Switching from a `stack- 100%` bar chart to a line chart causes the line chart to incorrectly display. Essentially, the settings for `normalized` bar charts are still being respected even though they are no longer relevant

image

image

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/43538

### Description

When switching from a normalized bar chart to line chart it was not rendering correctly. `stackable.stack_type` setting definition in `frontend/src/metabase/visualizations/lib/settings/graph.js` has validation that would reset it from `normalized` to `null` but the settings definition was not included in line charts settings.

### How to verify

1. New question -> Sample Dataset -> Orders -> Count by Created at and Product: Category
2. Switch the chart display type to "Bar"
3. Make it a normalized stacked chart
4. Switch display type back to "Line"
5. Ensure it renders the line chart correctly

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/CartesianChart/chart-definition.ts [hunk 1]
```diff
@@ -97,3 +112,16 @@ export const getCartesianChartDefinition = (
...
+  ...GRAPH_GOAL_SETTINGS,
+  ...GRAPH_TREND_SETTINGS,
+  ...GRAPH_COLORS_SETTINGS,
+  ...GRAPH_AXIS_SETTINGS,
+  ...GRAPH_DISPLAY_VALUES_SETTINGS,
+  ...GRAPH_DATA_SETTINGS,
+  ...TOOLTIP_SETTINGS,
+  ...STACKABLE_SETTINGS,
+  ...LEGEND_SETTINGS,
+} as any as VisualizationSettingsDefinitions;
```
Comment (JesseSDevaney) [inline frontend/src/metabase/visualizations/visualizations/CartesianChart/chart-definition.ts:127]: Stack settings have now dropped to the bottom of the list and should probably still remain at the top, since they are more visualization specific.

**Master**
image


**This PR**
image


```suggestion
export const COMBO_CHARTS_SETTINGS_DEFINITIONS = {
  ...LINE_SETTINGS,
  ...STACKABLE_SETTINGS,
  ...GRAPH_GOAL_SETTINGS,
  ...GRAPH_TREND_SETTINGS,
  ...GRAPH_COLORS_SETTINGS,
  ...GRAPH_AXIS_SETTINGS,
  ...GRAPH_DISPLAY_VALUES_SETTINGS,
  ...GRAPH_DATA_SETTINGS,
  ...TOOLTIP_SETTINGS,
  ...LEGEND_SETTINGS,
} as any as VisualizationSettingsDefinitions;
```

**Review by JesseSDevaney — APPROVED** [review]
99.99% LGTM

Just one comment we should address before merging. It's about the `Stacking` setting in the `Display` tab being shifted to the bottom of the settings list and should probably still remain at the top.
