### PR TITLE
Look for column by id rather than first PK

### LINKED ISSUE #5648: Table with multiple Entity Key columns incorrectly filtering on "Connected To" drill-through
I'm using the current master (and other releases).

I've got a table which has 2 Entity Key Fields (it's kind of a bridge between 2 data sets); the fields are `CustID` and `CustNum`.

screen shot 2017-07-31 at 4 56 34 pm

The "connected to" counts seems to show the correct value, but then they're clicked, the filters are populated with `CustNum` -- some of the relations are on the `CustNum` key, others are on `CustID`.

screen shot 2017-07-31 at 4 59 31 pm

In other words, when there are multiple Entity Key(s) defined, it seems like the "connected to" list is correctly finding the relationships, but the links don't apply the correct filter. (in the case of this screenshot, it should be filtering by `CustID = SIR002`

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #5648

This takes the core of the fix from #5861 and redoes it on the current code. I'm sorry we left this open for an embarrassingly long time, @joshuashort!

It's still not clear we broadly support multiple Entity Keys in one table, but this code feels more robust anyways. Among other things, Entity Name remapping might break in that situation.

I didn't add new tests since it's such a weird situation. I didn't want to add more data just for that. We do have tests already covering the normal usage of the two flows affected here: counting rows in the FK table and drilling into that table with the filter applied.

### CODE REVIEW

File: frontend/src/metabase/query_builder/actions.js [hunk 1]
```diff
@@ -1216,24 +1213,12 @@ export const loadObjectDetailFKReferences = createThunkAction(
...
-
       async function getFKCount(card, queryResult, fk) {
         const fkQuery = Q_DEPRECATED.createQuery("query");
         fkQuery.database = card.dataset_query.database;
         fkQuery.query["source-table"] = fk.origin.table_id;
         fkQuery.query.aggregation = ["count"];
-        fkQuery.query.filter = [
-          "and",
-          ["=", fk.origin.id, getObjectDetailIdValue(queryResult.data)],
-        ];
```
Comment (paulrosenzweig) [inline frontend/src/metabase/query_builder/actions.js:1236]: @camsaul this `"and"` was doing nothing, right? I extracted this to a function since it was duplicated but both uses had the `"and"`.

File: frontend/src/metabase/query_builder/actions.js [hunk 2]
```diff
@@ -1271,12 +1256,9 @@ export const loadObjectDetailFKReferences = createThunkAction(
...
       // It's possible that while we were running those queries, the object
       // detail id changed. If so, these fk reference are stale and we shouldn't
-      // put them in state.
+      // put them in state. The detail id is used in the query so we check that.
       const updatedQueryResult = getFirstQueryResult(getState());
-      if (
-        getObjectDetailIdValue(queryResult.data) !==
-        getObjectDetailIdValue(updatedQueryResult.data)
-      ) {
+      if (!_.isEqual(queryResult.json_query, updatedQueryResult.json_query)) {
```
Comment (paulrosenzweig) [inline frontend/src/metabase/query_builder/actions.js:1261]: This change is not related to the bug. I removed `getObjectDetailIdValue` and updated this to use the query which is simpler anyways.

**Review by daltojohnso — APPROVED** [review]
LGTM
