### PR TITLE
Optimize datetime filters!

### LINKED ISSUE #4043: Performance Improvement: Use date range instead of casting
On postgres (9.1), when using the date filter on question creation, selecting the current date results in the following where clause: 

cast(column as date) = cast(now() as date)

moving to the following instead results in a huge speed improvement

column >= date_trunc('day',now()) and column < date_trunc('day',now() + '1 day')

currently our read-only replica cries with the following error because the cast causes the query to run too long

```
ERROR:  canceling statement due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.
```

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### LINKED ISSUE #11009: When converting Oracle questions to SQL timestamps are converted wrong
Someone whose name rhymes with fam accidentally used `yyyy-MM-dd hh:mm:ss.SSS ZZ` as his format string instead of `yyyy-MM-dd HH:mm:ss.SSS ZZ`. Say you had a "count of checkins" query where the date is on or after September 27th, 2019. The SQL generated would be:

```sql
SELECT count(*)
FROM checkins
WHERE checkin_date >= timestamp '2019-09-27 12:00:00.000 ZZ'
```

Note the hour is `12:00` where we'd expect `00:00` instead. `hh` formats using 12-hour time as opposed to `HH` which uses 24 hour.

This is a recent bug because splicing literals into queries when converting to SQL was added in either 0.31 or 0.32.

### LINKED ISSUE #11010: Druid does not properly handle multiple datetime filters joined with 'and'
When filtering on a temporal value in Druid you specify it separately from other filters using the `:intervals` key. e.g.

```clj
{:intervals ["2018-01-01/2019-01-01"]}
```

Note that you can supply multiple intervals, which act as the equivalent of SQL `OR`, e.g.:

```clj
{:intervals ["2018-01-01/2019-01-01" "2020-01-01/2021-01-01"]}
```

is the rough equivalent of

```sql
(x BETWEEN '2018-01-01' AND '2019-01-01') 
OR 
(x BETWEEN '2020-01-01' AND '2021-01-01')
```

AFAIK there is no way to supply multiple intervals joined with a logical conjunction (i.e. `AND`).

Previously, if you had constructed a query that included multiple datetime filter clauses, e.g.,

```clj
[:and
 [:> [:datetime-field [:field-id 1] :day] "2015-10-04T00:00:00"]
 [:< [:datetime-field [:field-id 1] :day] "2015-10-06T00:00:00"]]
```

our Druid driver was not smart enough to figure out how to generate a single interval out of those clauses. It would instead use the interval from the first clause (rather than failing entirely), giving you

```clj
{:intervals ["2015-10-04/5000"]}
```

(we use `5000` to signify no upper bound. We haven't had problems with dates farther than the year 5000 yet.)

#10980 now reduces a arbitrary number of filter clauses into a single logically equivalent interval:

```clj
[:and
 [:between [:datetime-field [:field-id 1] :day] "2015-10-04T00:00:00" "2015-10-20T00:00:00"]
 [:between [:datetime-field [:field-id 1] :day] "2015-10-06T00:00:00" "2015-10-21T00:00:00"]]
```

becomes

```clj
{:intervals ["2015-10-06/2015-10-20"]}
```

wow!

### LINKED ISSUE #11011: Filtering against datetimes broken in SQLite
It doesn't fail entirely, but rather returns a set of mystery results rather than the correct ones. We had previously assumed this was a bug with timezone support in SQLite. It wasn't. We were using the wrong format for datetime literals, which we splice directly into the query for other reasons.

SQLite, like most SQL databases, uses `yyyy-MM-dd HH:mm:ss` formatted strings, rather than ISO-8601 `yyyy-MM-ddTHH:mm:ss` strings. Once I tracked down and fixed this bug I was able to actually remove several incorrect special cases in some of our tests that we had assumed were timezone issues.

### LINKED ISSUE #11012: When converting SparkSQL questions to SQL timestamps are converted wrong
This is the exact same issue as #11009 but for SparkSQL. In either 0.31 or 0.32 we improved logic converting a question to SQL so literal values are spliced in instead of leaving `?` parameter placeholders. However, the literal generated for `Timestamp`s was wrong. It was generating

```sql
from_unixtime(
 unix_timestamp(
 '2019-01-19T00:00:00.000Z', 
  'yyyy-MM-dd\\\\'T\\\\'HH:mm:ss.SSS\\\\'Z\\\\'
 )
)
```

which was not only wrong, but it also didn't work.

Spark SQL probably uses `''` to escape single quotes inside literals, but either way, definitely not `\\'` -- that is one slash too many. Also, Spark SQL doesn't use ISO-8601 formatted strings. 

We now generate SQL like

```sql
timestamp '2019-01-19 00:00:00.000'
```

which 9 out of 10 dentists agree is clear and actually works correctly.

### LINKED ISSUE #11013: SparkSQL does not properly compile datetime filters with :default bucketing
In Spark SQL for whatever strange reason a datetime and timestamp can be compared against another, but it doesn't work correctly. For example,

```sql
SELECT date '2019-09-27' < timestamp '2019-09-27 00:00:00'
-- true
```

is `true` in Spark SQL, for some reason I am not able to figure out. Casting the `date` to a timestamp works as expected:

```sql
SELECT CAST(date '2019-09-27' AS timestamp) < timestamp '2019-09-27 00:00:00'
```

`:default` bucketing is mostly used internally and isn't exposed in the UI AFAIK so marking this as a p3.

### PR DESCRIPTION
**Pull request by camsaul**
The biggest performance improvement in history of Metabase since we switched to Clojure

Before when filtering by a "bucketed" datetime field we would wrap the field and the value(s) it was being compared against in casting/truncation functions. For example when compiling a query to find fields where month is September 2019, we previously generated SQL like this:

```sql
SELECT count(*)
FROM public.checkins
WHERE date_trunc('month', CAST(public.checkins.date AS timestamp)) 
    = CAST(timestamp '2019-09-01T00:00:00Z' AS date)
```

As mentioned in #4043, this is not good for performance! Metabase now generates logically equivalent SQL like

```sql
SELECT count(*)
FROM public.checkins 
WHERE (
    public.checkins.date >= timestamp '2019-09-01T00:00:00Z' AND
    public.checkins.date < timestamp '2019-10-01T00:00:00Z'
)
```
Fixes #4043
Fixes #11009 
Fixes #11010
Fixes #11011 
Fixes #11012
Fixes #11013

😮 🏎

### CODE REVIEW

File: src/metabase/query_processor/middleware/optimize_datetime_filters.clj [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+    query
+    (mbql.u/replace query
+      (_ :guard (partial mbql.u/is-clause? (set (keys (methods optimize-filter)))))
+      (if (can-optimize-filter? &match)
+        (optimize-filter &match)
+        &match))))
+
+(defn optimize-datetime-filters
+  "Middlware that optimizes `=` and `not=` datetime filters that use bucketing. Rewrites those filters as `between`
+  filters that do not use bucketing, so the data warehouses can better utilize indexes.
```
Comment (sbelak) [inline src/metabase/query_processor/middleware/optimize_datetime_filters.clj]: Perhaps for clarity mention that no bucketing means unit = `:default`

**Review by sbelak — APPROVED** [review]
<3

**Comment by camsaul** [comment]
Fixes #11009

File: modules/drivers/druid/src/metabase/driver/druid/query_processor.clj [hunk 2]
```diff
@@ -316,11 +318,15 @@
 
 (defmethod parse-filter :and
   [[_ & args]]
-  {:type :and, :fields (filterv identity (map parse-filter args))})
+  (let [fields (filterv identity (map parse-filter args))]
```
[the remark this answers is not in the document]
Comment (camsaul) [reply modules/drivers/druid/src/metabase/driver/druid/query_processor.clj]: yeah, it would, I'll change it 👍

File: src/metabase/query_processor/middleware/optimize_datetime_filters.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/query_processor/middleware/optimize_datetime_filters.clj]: good call

**Comment by camsaul** [comment]
Fixes #11010
