### PR TITLE
Fix missing result metadata

### LINKED ISSUE #35039: Field list / filtering / grouping does not work with a native model that has comments
### Describe the bug

The query builder does not show source fields for models based on native queries, when the query has trailing comments.

### To Reproduce

1. Create a native model with the following SQL
```
select * from products
-- where true=false
```
_make sure there is no trailing space in the last line_

2. Create a GUI question based on the model.
3. (!) The field list in the column selector is empty.
4. (!) Summarize and Group also do not offer options with source fields.

### Expected behavior

It should work as before.

### Logs

```
2023-10-25 09:08:30,674 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 68.9 ms (16 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (6 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/1 (0 threads blocked)
2023-10-25 09:08:30,722 DEBUG middleware.log :: GET /api/database/1 200 2.8 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (6 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
2023-10-25 09:08:33,864 DEBUG middleware.log :: GET /api/alert/question/9 200 1.3 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (6 idle, 0 queued) (125 total active threads) Queries in flight: 0 (0 queued)
2023-10-25 09:09:23,535 INFO api.dataset :: Source query for this query is Card 9
2023-10-25 09:09:23,546 INFO middleware.fetch-source-query :: Trimming trailing comment from card with id 9
2023-10-25 09:09:23,550 INFO middleware.fetch-source-query :: Trimming trailing comment from card with id 9
2023-10-25 09:09:23,554 WARN middleware.add-implicit-clauses :: Warning: cannot determine fields for an explicit `source-query` unless you also include `source-metadata`.
Query: {:native "select * from products\n"}
```

### Information about your Metabase installation

```JSON
1.47.5
```

### Severity

P1 - it has been reported in the wild. There is a workaround but it is also a loss off common functionality.

### Additional context

image

### LINKED ISSUE #37009: Updated native models may lose their result set metadata
### Describe the bug

Upon updating a native model which is based on another model, the result set metadata may be lost.
When this occurs, the query editor won't show available columns for questions that are based on this model.

The workaround is to update the model, and making sure to preview the results before saving it.

### To Reproduce

1. Create native model `model1`:
```
      select 1 as "client_id", 1 as "value"
UNION select 1 as "client_id", 2 as "value"
UNION select 2 as "client_id", 3 as "value"
UNION select 3 as "client_id", 4 as "value"
```
2. Create and save a native model `model2`, which uses `model1` as its source:
```
select * from {{ #nnn-model1 }}
```

3. Update the query definition of model2, and make a minor, non-impactful change, for instance:
```
select cte.* from {{ #nnn-model1 }} as cte
```
, and save it, without previewing the results in the editor.

4. Now start a GUI question based on `model2`. 
5. (!)The columns of the model won't be available in the editor.
image

### Expected behavior

It should wirk

### Logs

Logs:
```
2023-12-20 18:47:06,445 INFO api.dataset :: Source query for this query is Card 77
2023-12-20 18:47:06,455 WARN middleware.add-implicit-clauses :: Warning: cannot determine fields for an explicit `source-query` unless you also include `source-metadata`.
Query: {:params [],
 :native
 "select cte.* from (select 1 as \"client_id\", 1 as \"value\"\nUNION select 1 as \"client_id\", 2 as \"value\"\nUNION select 2 as \"client_id\", 3 as \"value\"\nUNION select 3 as \"client_id\", 4 as \"value\") as cte"}
```

/api/card response for `model2`:
```
{
  "description": null,
  "archived": false,
  "collection_position": 1,
  "table_id": null,
  "result_metadata": null,
  "creator": {
[…]
  },
  "can_write": true,
  "database_id": 1,
  "enable_embedding": false,
  "collection_id": null,
  "query_type": "native",
  "name": "model2",
  "last_query_start": "2023-12-20T18:49:08.371778Z",
  "dashboard_count": 0,
  "persisted": false,
  "average_query_time": 21.0,
  "creator_id": 1,
  "moderation_reviews": [],
  "updated_at": "2023-12-20T18:47:06.210264Z",
  "made_public_by_id": null,
  "embedding_params": null,
  "cache_ttl": null,
  "dataset_query": {
    "type": "native",
    "native": {
      "query": "select cte.* from {{ #76-model1 }} as cte",
      "template-tags": {
        "#76-model1": {
          "type": "card",
          "name": "#76-model1",
          "id": "56149603-5eb3-4829-84a3-1afb2774f8ff",
          "card-id": 76,
          "display-name": "#76 Model1"
        }
      }
    },
    "database": 1
  },
  "id": 77,
  "parameter_mappings": [],
  "display": "table",
  "entity_id": "srrDqNwZugt2Ip3tYamZH",
  "collection_preview": true,
  "last-edit-info": {
[…]
  },
  "visualization_settings": {
    "table.pivot_column": "client_id",
    "table.cell_column": "value"
  },
  "collection": {
    "metabase.models.collection.root/is-root?": true,
    "authority_level": null,
    "name": "Our analytics",
    "is_personal": false,
    "id": "root",
    "can_write": true
  },
  "metabase_version": "v1.48.1 (a8302d4)",
  "parameters": [],
  "dataset": true,
  "created_at": "2023-12-20T18:45:50.916686",
  "parameter_usage_count": 0,
  "public_uuid": null
}```

### Information about your Metabase installation

```JSON
1.48.0, 1.47.9
```

### Severity

Found this while troubleshooting for a customer. A simple workaround exists.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #37009
Fixes #35039

Depends on #39184

### Description

Backend won't give us `card.result_metadata` when query executes for longer than 1.5 s - [see PR description for explanation](https://github.com/metabase/metabase/pull/39184#issue-2155298796) (and [Slack discussion](https://metaboat.slack.com/archives/C052ZBWRG3W/p1708970435491839?thread_ts=1708955785.300049&cid=C052ZBWRG3W)). In this case FE needs to explicitly run the query to get this information.

### How to verify

Follow reproduction steps from #37009 or https://github.com/metabase/metabase/issues/35039#issuecomment-1946325377.
Tests are all green.

Stress test for new e2e test passes: https://github.com/metabase/metabase/actions/runs/8079345130

### CODE REVIEW

File: frontend/src/metabase/query_builder/selectors.js [hunk 1]
```diff
@@ -1059,6 +1060,12 @@ export const getSubmittableQuestion = (state, question) => {
   const resultsMetadata = getResultsMetadata(state);
   const isResultDirty = getIsResultDirty(state);
 
+  if (question.type() === "model") {
+    resultsMetadata.columns = ModelIndexes.actions.cleanIndexFlags(
+      resultsMetadata.columns,
+    );
+  }
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/selectors.js:1067]: This part should have been moved in #39147. It worked because it mutated data in redux store.

**Review by uladzimirdev — APPROVED** [review]
