### PR TITLE
fix(sdk): missing css variables when rendering under a portal

### LINKED ISSUE #44391: Embedding SDK components has missing CSS variables when rendering in a React portal
- When adding the embedding SDK components such as an Interactive Question to a modal, the filter colors from the theme settings are not applied. See (1)

CleanShot 2567-06-20 at 19 02 43@2x

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/44391

### Description

When SDK users are rendering the embedding SDK components (such as an interactive question) under a React portal (such as in a modal using their library of choice), the filter colors from the theme settings are not applied. In the screenshot below, you can notice that the filter color is not applied properly in (1).

image

This PR separates the components for injecting CSS variables to a public component (i.e. `PublicComponentStylesWrapper`) from the components injecting global sdk styles such as font-face declarations (i.e. `SdkGlobalStylesWrapper`), so we can provide the CSS variables in context of React portals.

### How to verify

- Go to the `fix-react-portal` branch under the Shoppy demo app
- Click on a product card, then click on the topmost chart
- The color should be correct

### Demo

CleanShot 2567-06-20 at 21 12 11@2x

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR - to add visual test or unit test next

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/components/private/SdkGlobalStylesWrapper.tsx [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+  ${({ fontFiles }) =>
+    fontFiles?.map(
+      file => css`
+        @font-face {
+          font-family: "Custom";
+          src: url(${encodeURI(file.src)}) format("${file.fontFormat}");
+          font-weight: ${file.fontWeight};
+          font-style: normal;
+          font-display: swap;
+        }
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/private/SdkGlobalStylesWrapper.tsx:54]: @font-face declarations are always global in nature. It is not scoped. We don't need to add them to `PublicComponentWrapper`

File: frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx [hunk 2]
```diff
@@ -66,7 +66,7 @@ export const GlobalStyles = (): JSX.Element => {
         transparent
       );
 
-      ${themeSpecificSelectors}
+      ${getThemeSpecificCssVariables(theme)}
```
Comment (heypoom) [inline frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx:69]: I want to remove the CSS variables from GlobalStyles and reply on getMetabaseCssVariables, but that's quite error-prone so let's do that in the next PR. If we do that, there will be a lot less duplication between GlobalStyles and SDK.

File: enterprise/frontend/src/embedding-sdk/components/private/SdkGlobalStylesWrapper.tsx [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+    />
+  );
+}
+
+const SdkGlobalStylesInner = styled.div<
+  SdkContentWrapperProps & {
+    fontFiles: FontFile[] | null;
+  }
+>`
+  ${({ theme }) => getMetabaseCssVariables(theme)}
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/private/SdkGlobalStylesWrapper.tsx:38]: We need this because of components like Popovers. Popovers still need the Metabase CSS variables for their colors, so we inject the CSS variables in both `SdkGlobalStyles` (applies to Mantine components) and `PublicComponentStylesWrapper` (applies to Metabase components). [Refer to this thread for more info.](https://metaboat.slack.com/archives/C063Q3F1HPF/p1718808917198979)

File: frontend/src/metabase/css/core/colors.module.css [hunk 4]
```diff
@@ -2,7 +2,7 @@
  * NOTE: KEEP SYNCRONIZED WITH:
  * frontend/src/metabase/ui/utils/colors.ts
  * frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx
- * enterprise/frontend/src/embedding-sdk/components/private/SdkContentWrapper.tsx
+ * frontend/src/metabase/styled-components/theme/css-variables.ts
```
Comment (heypoom) [inline frontend/src/metabase/css/core/colors.module.css:5]: I want to remove the CSS variables from `GlobalStyles` and rely on `getMetabaseCssVariables`, but that's quite error-prone so let's do that in the next PR where I can focus on testing. If we do that, there will be a lot less duplication between GlobalStyles and SDK.

File: enterprise/frontend/src/embedding-sdk/components/private/SdkGlobalStylesWrapper.tsx (hunk 3 above)
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/components/private/SdkGlobalStylesWrapper.tsx:38]: This is what happens when we only inject the CSS variables in the component wrapper. It breaks quite a lot of places.

CleanShot 2567-06-20 at 20 55 27@2x

**Comment by heypoom** [comment]
Note: I'll add visual test or unit test in this PR. Adding reviewers for now to see if this makes sense to other folks.

File: enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+/**
+ * Injects CSS variables and styles to the SDK components underneath them.
+ * This is to ensure that the SDK components are styled correctly,
+ * even when rendered under a React portal.
+ */
+export const PublicComponentStylesWrapper = styled.div`
+  width: 100%;
+  ${({ theme }) => getMetabaseCssVariables(theme)}
+
+  :where(svg) {
```
[the remark this answers is not in the document]
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx:14]: @deniskaber good idea! i'll take a look at the CSS to see if there are more styles we can extract to here.

[the remark this answers is not in the document]
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx:23]: @deniskaber I re-checked the CSS, and I've moved `aceEditorStyles` and `saveDomImageStyles` here, as well as adding `color` and `font-family` that matches GlobalStyles.

The only thing to be left in SdkGlobalStyles would then be `font-size` (cannot be in PublicComponentStyles due to cascades), `rootStyle` and font file loading (`@font-face` is global).

**Review by deniskaber — APPROVED** [review]
