### PR TITLE
Refresh child card result metadata on card edit

### LINKED ISSUE #50178: Custom columns in models will show in the column selector and the query
### Describe the bug

There's some weird metadata problem on models that are inherited from models

### To Reproduce

1) create a model from the people table (model 1)
2) create a model based on model 1, removing 2 columns, e.g. email and latitude (model 2)
3) create a model based on model 2 (model 3)
4) now create 2 custom columns on model 1 (e.g. concat source and state and concat longitude and source)
5) go to model 2, see that the new custom columns are selected, but not shown
Image

### Expected behavior

We should reflect the columns that are selected in the editor

### Logs

NA

### Information about your Metabase installation

```JSON
-I could repro in v50.x, but might come from before
```

### Severity

P1ish

### Additional context

NA

### LINKED ISSUE #67679: Filters in dashboards stick to old tables when switching the data source of a model
### Describe the bug

We seem to rely on old metadata on dashboard filters, so when the underlying datasource changes we don't refresh the filter sources making them unusable

### To Reproduce

1) create a people table model and an orders table model. Save these
2) create a model that joins the orders model and the people model. Save this
3) create a question using the orders + people model (created in step 2). A count of rows is fine
4) add the question to a dashboard, and also add a filter to the dashboard connected to the "Orders + People.People - User -> Source" field
5) now go to your favorite SQL IDE and run
```
CREATE SCHEMA new_schema;
SELECT * INTO new_schema.orders FROM public.orders;
SELECT * INTO new_schema.people FROM public.people;
```

6) Force a sync, otherwise you can't change the source due to this other bug https://github.com/metabase/metabase/issues/67491
7) Drop the original tables

```
DROP TABLE public.orders;
DROP TABLE public.people;
```

8) now to go the People model and change the source to new_schema.people and change the Orders model to new_schema.orders by clicking on the 3 little dots on the right and "edit query definition"

9) go to the dashboard and try using the filter, the values endpoint will fail as the filter is still connected to the old field

### Expected behavior

Filters should work

### Logs

<details>

{
    "via": [
        {
            "type": "java.lang.Exception",
            "message": "Table \"postgres-data1.public.people\" is inactive.",
            "at": [
                "metabase.query_processor.middleware.permissions$throw_inactive_table_error",
                "invokeStatic",
                "permissions.clj",
                39
            ]
        }
    ],
    "trace": [
        [
            "metabase.query_processor.middleware.permissions$throw_inactive_table_error",
            "invokeStatic",
            "permissions.clj",
            39
        ],
        [
            "metabase.query_processor.middleware.permissions$throw_inactive_table_error",
            "invoke",
            "permissions.clj",
            30
        ],
        [
            "metabase.query_processor.middleware.permissions$check_query_does_not_access_inactive_tables$fn__73670",
            "invoke",
            "permissions.clj",
            54
        ],
        [
            "metabase.query_processor.store$do_with_metadata_provider",
            "invokeStatic",
            "store.clj",
            205
        ],
        [
            "metabase.query_processor.store$do_with_metadata_provider",
            "invoke",
            "store.clj",
            186
        ],
        [
            "metabase.query_processor.middleware.permissions$check_query_does_not_access_inactive_tables",
            "invokeStatic",
            "permissions.clj",
            49
        ],
        [
            "metabase.query_processor.middleware.permissions$check_query_does_not_access_inactive_tables",
            "invoke",
            "permissions.clj",
            43
        ],
        [
            "metabase.query_processor.middleware.permissions$check_query_permissions_STAR_",
            "invokeStatic",
            "permissions.clj",
            106
        ],
        [
            "metabase.query_processor.middleware.permissions$check_query_permissions_STAR_",
            "invoke",
            "permissions.clj",
            95
        ],
        [
            "metabase.parameters.chain_filter$check_field_value_query_permissions$fn__86903",
            "invoke",
            "chain_filter.clj",
            584
        ],
        [
            "metabase.query_processor.setup$do_with_canceled_chan$fn__80158",
            "invoke",
            "setup.clj",
            196
        ],
        [
            "metabase.query_processor.setup$do_with_database_local_settings$fn__80153",
            "invoke",
            "setup.clj",
            188
        ],
        [
            "metabase.query_processor.setup$do_with_driver$fn__80144$fn__80145",
            "invoke",
            "setup.clj",
            173
        ],
        [
            "metabase.driver$do_with_driver",
            "invokeStatic",
            "driver.clj",
            54
        ],
        [
            "metabase.driver$do_with_driver",
            "invoke",
            "driver.clj",
            49
        ],
        [
            "metabase.query_processor.setup$do_with_driver$fn__80144",
            "invoke",
            "setup.clj",
            172
        ],
        [
            "metabase.query_processor.setup$do_with_metadata_provider$fn__80136$fn__80137",
            "invoke",
            "setup.clj",
            141
        ],
        [
            "metabase.query_processor.store$do_with_metadata_provider",
            "invokeStatic",
            "store.clj",
            200
        ],
        [
            "metabase.query_processor.store$do_with_metadata_provider",
            "invoke",
            "store.clj",
            186
        ],
        [
            "metabase.query_processor.store$do_with_metadata_provider",
            "invokeStatic",
            "store.clj",
            193
        ],
        [
            "metabase.query_processor.store$do_with_metadata_provider",
            "invoke",
            "store.clj",
            186
        ],
        [
            "metabase.query_processor.setup$do_with_metadata_provider$fn__80136",
            "invoke",
            "setup.clj",
            140
        ],
        [
            "metabase.query_processor.setup$do_with_resolved_database$fn__80128",
            "invoke",
            "setup.clj",
            125
        ],
        [
            "metabase.query_processor.setup$do_with_qp_setup",
            "invokeStatic",
            "setup.clj",
            240
        ],
        [
            "metabase.query_processor.setup$do_with_qp_setup",
            "invoke",
            "setup.clj",
            223
        ],
        [
            "metabase.parameters.chain_filter$check_field_value_query_permissions",
            "invokeStatic",
            "chain_filter.clj",
            583
        ],
        [
            "metabase.parameters.chain_filter$check_field_value_query_permissions",
            "invoke",
            "chain_filter.clj",
            579
        ],
        [
            "metabase.parameters.chain_filter$chain_filter",
            "invokeStatic",
            "chain_filter.clj",
            650
        ],
        [
            "metabase.parameters.chain_filter$chain_filter",
            "doInvoke",
            "chain_filter.clj",
            603
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            467
        ],
        [
            "metabase.parameters.dashboard$chain_filter$fn__119237",
            "invoke",
            "dashboard.clj",
            112
        ],
        [
            "clojure.core$map$fn__5956",
            "invoke",
            "core.clj",
            2772
        ],
        [
            "clojure.lang.LazySeq",
            "force",
            "LazySeq.java",
            50
        ],
        [
            "clojure.lang.LazySeq",
            "realize",
            "LazySeq.java",
            89
        ],
        [
            "clojure.lang.LazySeq",
            "seq",
            "LazySeq.java",
            106
        ],
        [
            "clojure.lang.RT",
            "seq",
            "RT.java",
            555
        ],
        [
            "clojure.core$seq__5488",
            "invokeStatic",
            "core.clj",
            139
        ],
        [
            "clojure.core$map$fn__5956",
            "invoke",
            "core.clj",
            2763
        ],
        [
            "clojure.lang.LazySeq",
            "force",
            "LazySeq.java",
            50
        ],
        [
            "clojure.lang.LazySeq",
            "realize",
            "LazySeq.java",
            89
        ],
        [
            "clojure.lang.LazySeq",
            "seq",
            "LazySeq.java",
            106
        ],
        [
            "clojure.lang.RT",
            "seq",
            "RT.java",
            555
        ],
        [
            "clojure.core$seq__5488",
            "invokeStatic",
            "core.clj",
            139
        ],
        [
            "clojure.core$some",
            "invokeStatic",
            "core.clj",
            2709
        ],
        [
            "clojure.core$some",
            "invoke",
            "core.clj",
            2709
        ],
        [
            "metabase.parameters.dashboard$chain_filter",
            "invokeStatic",
            "dashboard.clj",
            114
        ],
        [
            "metabase.parameters.dashboard$chain_filter",
            "invoke",
            "dashboard.clj",
            86
        ],
        [
            "metabase.parameters.dashboard$param_values$fn__119243",
            "invoke",
            "dashboard.clj",
            147
        ],
        [
            "metabase.parameters.custom_values$parameter__GT_values",
            "invokeStatic",
            "custom_values.clj",
            167
        ],
        [
            "metabase.parameters.custom_values$parameter__GT_values",
            "invoke",
            "custom_values.clj",
            150
        ],
        [
            "metabase.parameters.dashboard$param_values",
            "invokeStatic",
            "dashboard.clj",
            144
        ],
        [
            "metabase.parameters.dashboard$param_values",
            "invoke",
            "dashboard.clj",
            124
        ],
        [
            "metabase.parameters.dashboard$param_values",
            "invokeStatic",
            "dashboard.clj",
            132
        ],
        [
            "metabase.parameters.dashboard$param_values",
            "invoke",
            "dashboard.clj",
            124
        ],
        [
            "metabase.dashboards.api$fn__120083$fn__120090",
            "invoke",
            "api.clj",
            1156
        ],
        [
            "metabase.api.macros$_core_fn$core_fn__96707",
            "invoke",
            "macros.clj",
            427
        ],
        [
            "metabase.api.macros$endpoint_handler_STAR_$handler__96749",
            "invoke",
            "macros.clj",
            623
        ],
        [
            "metabase.api.macros$build_ns_handler$ns_handler_STAR___96775",
            "invoke",
            "macros.clj",
            687
        ],
        [
            "metabase.api.open_api.HandlerWithOpenAPISpec",
            "invoke",
            "open_api.clj",
            42
        ],
        [
            "metabase.api.routes.common$enforce_authentication$fn__107165",
            "invoke",
            "common.clj",
            92
        ],
        [
            "metabase.api.open_api.HandlerWithOpenAPISpec",
            "invoke",
            "open_api.clj",
            42
        ],
        [
            "metabase.api.util.handlers$_route_map_handler$fn__101748",
            "invoke",
            "handlers.clj",
            23
        ],
        [
            "metabase.api.open_api.HandlerWithOpenAPISpec",
            "invoke",
            "open_api.clj",
            42
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685$f__101686$respond_SINGLEQUOTE___101687",
            "invoke",
            "core.clj",
            197
        ],
        [
            "metabase.api.util.handlers$_route_map_handler$fn__101748",
            "invoke",
            "handlers.clj",
            24
        ],
        [
            "metabase.api.open_api.HandlerWithOpenAPISpec",
            "invoke",
            "open_api.clj",
            42
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            395
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685",
            "invoke",
            "core.clj",
            200
        ],
        [
            "metabase.api.open_api.HandlerWithOpenAPISpec",
            "invoke",
            "open_api.clj",
            42
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            395
        ],
        [
            "metabase.server.routes$api_handler$api_handler_STAR___102478",
            "invoke",
            "routes.clj",
            88
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$make_context$handler__101713",
            "invoke",
            "core.clj",
            290
        ],
        [
            "compojure.core$make_context$fn__101717",
            "invoke",
            "core.clj",
            300
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685$f__101686$respond_SINGLEQUOTE___101687",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__101666",
            "invoke",
            "core.clj",
            153
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685$f__101686$respond_SINGLEQUOTE___101687",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__101666",
            "invoke",
            "core.clj",
            153
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685$f__101686$respond_SINGLEQUOTE___101687",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__101666",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685$f__101686$respond_SINGLEQUOTE___101687",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__101666",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685$f__101686$respond_SINGLEQUOTE___101687",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__101666",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685$f__101686$respond_SINGLEQUOTE___101687",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__101666",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685$f__101686$respond_SINGLEQUOTE___101687",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__101666",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685$f__101686$respond_SINGLEQUOTE___101687",
            "invoke",
            "core.clj",
            197
        ],
        [
            "metabase.api.util.handlers$_route_map_handler$fn__101748",
            "invoke",
            "handlers.clj",
            24
        ],
        [
            "metabase.api.open_api.HandlerWithOpenAPISpec",
            "invoke",
            "open_api.clj",
            42
        ],
        [
            "metabase.api.util.handlers$_route_map_handler$fn__101748",
            "invoke",
            "handlers.clj",
            23
        ],
        [
            "metabase.api.open_api.HandlerWithOpenAPISpec",
            "invoke",
            "open_api.clj",
            42
        ],
        [
            "clojure.lang.Var",
            "invoke",
            "Var.java",
            395
        ],
        [
            "compojure.core$routes$fn__101685$f__101686",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__101685",
            "invoke",
            "core.clj",
            200
        ],
        [
            "metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__139160",
            "invoke",
            "exceptions.clj",
            84
        ],
        [
            "metabase.server.middleware.exceptions$catch_api_exceptions$fn__139157",
            "invoke",
            "exceptions.clj",
            73
        ],
        [
            "metabase.server.middleware.log$log_api_call$fn__124439$fn__124440$fn__124441",
            "invoke",
            "log.clj",
            225
        ],
        [
            "metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info",
            "invokeStatic",
            "diagnostic.clj",
            17
        ],
        [
            "metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info",
            "invoke",
            "diagnostic.clj",
            12
        ],
        [
            "metabase.server.middleware.log$log_api_call$fn__124439$fn__124440",
            "invoke",
            "log.clj",
            216
        ],
        [
            "toucan2.execute$do_with_call_counts",
            "invokeStatic",
            "execute.clj",
            112
        ],
        [
            "toucan2.execute$do_with_call_counts",
            "invoke",
            "execute.clj",
            103
        ],
        [
            "metabase.server.middleware.log$log_api_call$fn__124439",
            "invoke",
            "log.clj",
            215
        ],
        [
            "metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__145932",
            "invoke",
            "browser_cookie.clj",
            40
        ],
        [
            "metabase.server.middleware.security$add_security_headers$fn__139127",
            "invoke",
            "security.clj",
            321
        ],
        [
            "metabase.server.middleware.json$wrap_json_body$fn__138301",
            "invoke",
            "json.clj",
            128
        ],
        [
            "metabase.server.middleware.offset_paging$handle_paging$fn__141586",
            "invoke",
            "offset_paging.clj",
            48
        ],
        [
            "metabase.server.middleware.json$wrap_streamed_json_response$fn__138289",
            "invoke",
            "json.clj",
            83
        ],
        [
            "metabase.server.middleware.metadata_provider_cache$wrap_metadata_provider_cache$fn__145942",
            "invoke",
            "metadata_provider_cache.clj",
            11
        ],
        [
            "ring.middleware.keyword_params$wrap_keyword_params$fn__146207",
            "invoke",
            "keyword_params.clj",
            55
        ],
        [
            "ring.middleware.params$wrap_params$fn__146226",
            "invoke",
            "params.clj",
            77
        ],
        [
            "metabase.server.middleware.misc$maybe_set_site_url$fn__122465",
            "invoke",
            "misc.clj",
            78
        ],
        [
            "metabase.server.middleware.session$reset_session_timeout$fn__130638",
            "invoke",
            "session.clj",
            290
        ],
        [
            "metabase.server.middleware.session$bind_current_user$fn__130631$fn__130632",
            "invoke",
            "session.clj",
            265
        ],
        [
            "metabase.request.session$do_with_current_user$fn__85390",
            "invoke",
            "session.clj",
            60
        ],
        [
            "metabase.request.session$do_with_current_user$do_with_user_local_values__85385",
            "invoke",
            "session.clj",
            56
        ],
        [
            "metabase.request.session$do_with_current_user",
            "invokeStatic",
            "session.clj",
            57
        ],
        [
            "metabase.request.session$do_with_current_user",
            "invoke",
            "session.clj",
            38
        ],
        [
            "metabase.server.middleware.session$bind_current_user$fn__130631",
            "invoke",
            "session.clj",
            264
        ],
        [
            "metabase.server.middleware.session$wrap_current_user_info$fn__130627",
            "invoke",
            "session.clj",
            240
        ],
        [
            "metabase.server.middleware.settings_cache$wrap_settings_cache_check$fn__139473",
            "invoke",
            "settings_cache.clj",
            50
        ],
        [
            "metabase.analytics.sdk$embedding_mw$embedding_mw_fn__63207",
            "invoke",
            "sdk.clj",
            68
        ],
        [
            "metabase.server.middleware.session$wrap_session_key$fn__130585",
            "invoke",
            "session.clj",
            89
        ],
        [
            "metabase.server.middleware.auth$wrap_static_api_key$fn__128729",
            "invoke",
            "auth.clj",
            17
        ],
        [
            "ring.middleware.cookies$wrap_cookies$fn__146127",
            "invoke",
            "cookies.clj",
            200
        ],
        [
            "metabase.server.middleware.misc$add_version$fn__122436",
            "invoke",
            "misc.clj",
            29
        ],
        [
            "metabase.server.middleware.misc$add_content_type$fn__122444",
            "invoke",
            "misc.clj",
            47
        ],
        [
            "metabase.server.middleware.misc$disable_streaming_buffering$fn__122473",
            "invoke",
            "misc.clj",
            94
        ],
        [
            "ring.middleware.gzip$wrap_gzip$fn__146169",
            "invoke",
            "gzip.clj",
            86
        ],
        [
            "metabase.server.middleware.request_id$wrap_request_id$fn__111372",
            "invoke",
            "request_id.clj",
            10
        ],
        [
            "metabase.server.middleware.misc$bind_request$fn__122476$fn__122477",
            "invoke",
            "misc.clj",
            106
        ],
        [
            "metabase.request.current$do_with_current_request",
            "invokeStatic",
            "current.clj",
            19
        ],
        [
            "metabase.request.current$do_with_current_request",
            "invoke",
            "current.clj",
            15
        ],
        [
            "metabase.server.middleware.misc$bind_request$fn__122476",
            "invoke",
            "misc.clj",
            105
        ],
        [
            "metabase.server.middleware.ssl$redirect_to_https_middleware$fn__145956",
            "invoke",
            "ssl.clj",
            52
        ],
        [
            "metabase.server.instance$async_proxy_handler$fn__124171",
            "invoke",
            "instance.clj",
            82
        ],
        [
            "metabase.server.instance.proxy$org.eclipse.jetty.ee9.servlet.ServletHandler$ff19274a",
            "doHandle",
            null,
            -1
        ],
        [
            "org.eclipse.jetty.ee9.nested.ScopedHandler",
            "handle",
            "ScopedHandler.java",
            127
        ],
        [
            "metabase.server.statistics_handler$new_handler$fn__99711",
            "invoke",
            "statistics_handler.clj",
            105
        ],
        [
            "metabase.server.statistics_handler.proxy$org.eclipse.jetty.ee9.nested.HandlerWrapper$ff19274a",
            "handle",
            null,
            -1
        ],
        [
            "org.eclipse.jetty.ee9.nested.HandlerWrapper",
            "handle",
            "HandlerWrapper.java",
            124
        ],
        [
            "org.eclipse.jetty.ee9.nested.ScopedHandler",
            "nextHandle",
            "ScopedHandler.java",
            197
        ],
        [
            "org.eclipse.jetty.ee9.nested.ContextHandler",
            "doHandle",
            "ContextHandler.java",
            1045
        ],
        [
            "org.eclipse.jetty.ee9.nested.ScopedHandler",
            "nextScope",
            "ScopedHandler.java",
            164
        ],
        [
            "org.eclipse.jetty.ee9.servlet.ServletHandler",
            "doScope",
            "ServletHandler.java",
            483
        ],
        [
            "metabase.server.instance.proxy$org.eclipse.jetty.ee9.servlet.ServletHandler$ff19274a",
            "doScope",
            null,
            -1
        ],
        [
            "org.eclipse.jetty.ee9.nested.ScopedHandler",
            "nextScope",
            "ScopedHandler.java",
            162
        ],
        [
            "org.eclipse.jetty.ee9.nested.ContextHandler",
            "doScope",
            "ContextHandler.java",
            966
        ],
        [
            "org.eclipse.jetty.ee9.nested.ScopedHandler",
            "handle",
            "ScopedHandler.java",
            125
        ],
        [
            "org.eclipse.jetty.ee9.nested.ContextHandler",
            "handle",
            "ContextHandler.java",
            1719
        ],
        [
            "org.eclipse.jetty.ee9.nested.HttpChannel$RequestDispatchable",
            "dispatch",
            "HttpChannel.java",
            1565
        ],
        [
            "org.eclipse.jetty.ee9.nested.HttpChannel",
            "dispatch",
            "HttpChannel.java",
            724
        ],
        [
            "org.eclipse.jetty.ee9.nested.HttpChannel",
            "handle",
            "HttpChannel.java",
            512
        ],
        [
            "org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler",
            "handle",
            "ContextHandler.java",
            3029
        ],
        [
            "org.eclipse.jetty.server.handler.ContextHandler",
            "handle",
            "ContextHandler.java",
            1071
        ],
        [
            "org.eclipse.jetty.server.Server",
            "handle",
            "Server.java",
            182
        ],
        [
            "org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker",
            "run",
            "HttpChannelState.java",
            677
        ],
        [
            "org.eclipse.jetty.server.internal.HttpConnection",
            "onFillable",
            "HttpConnection.java",
            416
        ],
        [
            "org.eclipse.jetty.io.AbstractConnection$ReadCallback",
            "succeeded",
            "AbstractConnection.java",
            322
        ],
        [
            "org.eclipse.jetty.io.FillInterest",
            "fillable",
            "FillInterest.java",
            99
        ],
        [
            "org.eclipse.jetty.io.SelectableChannelEndPoint$1",
            "run",
            "SelectableChannelEndPoint.java",
            53
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "runTask",
            "AdaptiveExecutionStrategy.java",
            480
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "consumeTask",
            "AdaptiveExecutionStrategy.java",
            443
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "tryProduce",
            "AdaptiveExecutionStrategy.java",
            293
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "run",
            "AdaptiveExecutionStrategy.java",
            201
        ],
        [
            "org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread",
            "run",
            "ReservedThreadExecutor.java",
            311
        ],
        [
            "org.eclipse.jetty.util.thread.QueuedThreadPool",
            "runJob",
            "QueuedThreadPool.java",
            981
        ],
        [
            "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
            "doRunJob",
            "QueuedThreadPool.java",
            1211
        ],
        [
            "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
            "run",
            "QueuedThreadPool.java",
            1166
        ],
        [
            "java.lang.Thread",
            "run",
            null,
            -1
        ]
    ],
    "cause": "Table \"postgres-data1.public.people\" is inactive.",
    "message": "Table \"postgres-data1.public.people\" is inactive."

</details>

### Information about your Metabase installation

```JSON
v57.x
```

### Severity

P1

### Additional context

This is concerning for medallion architecture users

### PR DESCRIPTION
**Pull request by wzimrin**
Closes https://github.com/metabase/metabase/issues/67679
Closes https://github.com/metabase/metabase/issues/50178

### Description

When a card is updated, look for all mbql child cards and recalculate their result metadata.  With models, calculate what their "correct" result metadata is pre-update, use that to calculate user overrides, and then reapply those overrides when computing the new result metadata.

This should fix a variety of bugs around users updating a model and then not seeing those change downstream.

### How to verify

Create a parent model, a child model that depends on the parent, and a grandchild model that depends on the child.  Update the parent model in various ways and see that the changes are propagated to the child and grandchild.  Also, add an override to the child or grandchild's metadata and see that those overrides are preserved when you change the parent.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/audit_app/events/audit_log_test.clj [hunk 1]
```diff
@@ -65,19 +65,19 @@
...
+              (is (partial=
+                   {:topic    :card-update
+                    :user_id  (mt/user->id :rasta)
+                    :model    "Card"
+                    :model_id (:id card)
+                    :details  {:previous (cond-> {:name "Old Name"}
+                                           (= card-type :model) (assoc :model? false))
+                               :new (cond-> {:name "My Cool Card"}
+                                      (= card-type :model) (assoc :model? true))}}
+                   (mt/latest-audit-log-entry "card-update" (:id card)))))))))))
```
Comment (wzimrin) [inline test/metabase/audit_app/events/audit_log_test.clj:80]: Note that this isn't an intended change.  From what I can tell, when I added :previous-object to the card change event, this changed the logic that the audit log uses to report the change.  That seems plausibly fine (displaying what actually changed instead of just showing the current state seems like an improvement), but I would love if someone who knows more about this side of things could weigh in on whether this is actually acceptable, or whether there is a better way of adding the previous version of the card to the card update event.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 2]
```diff
@@ -0,0 +1,234 @@
...
+  (let [graph (models.dependency/filtered-graph-dependents
+               nil
+               (fn [type-field _id-field]
+                 [:and
+                  [:not= type-field "transform"]
+                  [:not= type-field "snippet"]
+                  [:not= type-field "dashboard"]
+                  [:not= type-field "document"]]))
+        start [start-type start-id]]
+    (loop [to-traverse #{start}
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: It seems like there's reusable `graph.core` functionality we could build for this.  
  
I think the right way to do it is to add two operations to `graph.core`:

- `(graph/where-edges graph predicate)` that wraps any inner `graph` to filter its edges. Go go Strategy pattern!
- Then the rest of this function becomes a new `(graph/transitive-children graph key-seq)` that is more fundamental than `graph/transitive` - it returns a map of all transitively reachable keys to their lists of adjacent children (even those already visited).

`graph/transitive` could then become `(keys (graph/transitive-children graph key-seq))`.  
  
That can go in a follow-up PR, but we should capture it as a TODO and/or bug.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 3]
```diff
@@ -0,0 +1,234 @@
...
+   start-type :- ::deps.dependency-types/dependency-types
+   start-id   :- ::deps.dependency-types/entity-id]
+  (let [graph (models.dependency/filtered-graph-dependents
+               nil
+               (fn [type-field _id-field]
+                 [:and
+                  [:not= type-field "transform"]
+                  [:not= type-field "snippet"]
+                  [:not= type-field "dashboard"]
+                  [:not= type-field "document"]]))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: A list of banned things worries me. Why not a list of allowed things? ISTM that the allowlist is much less likely to grow and we forget to edit it.  
  
If we absolutely must keep this as a banlist, please (1) add a comment saying why, and (2) probably move this into e.g. `models.dependency/cardlike-dependents` (or whatever name is appropriate) to keep the functionality closer to the core.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 4]
```diff
@@ -0,0 +1,234 @@
...
+                            (mapcat (fn [[parent current-children]]
+                                      (conj current-children parent)))
+                            children)
+                      sort)
+        full-parent-map (->> children
+                             (mapcat (fn [[parent current-children]]
+                                       (map (fn [child]
+                                              {child #{parent}})
+                                            current-children)))
+                             (apply merge-with into))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: I think Medley already has this map-inversion logic somewhere. If not, this deserves a name and moving to `metabase.util.something`.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 5]
```diff
@@ -0,0 +1,234 @@
...
+        (if (seq new-traverse)
+          (recur new-traverse new-child-map)
+          new-child-map)))))
+
+(mu/defn- do-for-card-children
+  [thunk
+   children   :- ::child-map
+   start-type :- ::deps.dependency-types/dependency-types
+   start-id   :- ::deps.dependency-types/entity-id]
+  (let [all-nodes (-> (into #{}
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: Let's get some comments on this to explain what it's doing? It's named with the `do-blah-blah` pattern that made me look for a `for-card-children` macro in the hopes of understanding its docs, but that apparently doesn't exist. Lets get a much more descriptive name and comment on it, private or not.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 6]
```diff
@@ -0,0 +1,234 @@
...
+                            (mapcat (fn [[parent current-children]]
+                                      (conj current-children parent)))
+                            children)
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: `(sort (into (set (keys children)) (mapcat vals) children))`

```suggestion
  (let [all-nodes (->> (into (set (keys children))
                             (mapcat vals)
                             children)
                       sort)
                       
```

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 7]
```diff
@@ -0,0 +1,234 @@
...
+                         (= next-node start)
+                         (thunk node-id))
+              new-nodes-remaining (remove #(= % next-node) nodes-remaining)]
+          (if result
+            (recur new-nodes-remaining
+                   (m/map-vals #(disj % next-node) parent-map)
+                   ignored)
+            (recur new-nodes-remaining
+                   parent-map
+                   (conj ignored next-node))))))))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: Especially without a comment, it's really unclear what this is going. But it smells like another case of a would-be reusable graph function wrapped around a filtered `graph` as discussed above.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 8]
```diff
@@ -0,0 +1,234 @@
...
+
+(mu/defn- dependent-mbql-cards :- [:sequential ::lib.schema.id/card]
+  [children   :- ::child-map
+   start-type :- ::deps.dependency-types/dependency-types
+   start-id   :- ::deps.dependency-types/entity-id]
+  (let [nodes (atom [])]
+    (do-for-card-children #(swap! nodes conj %) children start-type start-id)
+    @nodes))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: Both of the call sites of `do-for-card-children` have side-effecting thunks. Is there a strong reason in either case to mix that side effect with the graph traversal? Why not return a `seq` or whatever and just return it here, and `doseq` over the `t2/update!` below?  
  
The `thunk` is also, AFAICT, getting used as both a filter and has side effects in the call below. That should be separated.

**Review by bshepherdson — CHANGES_REQUESTED** [review]
Partial review, my EoD overtook me. I'll pick it up again on Wednesday.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj (hunk 2 above)
Comment (wzimrin) [reply enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: Defining `graph/transitive` in terms of `graph/transitive-children` doesn't work well, because `transitive-children` doesn't have any ordering, while `transitive` makes some strong guarantees about the order nodes are returned in.  In practice, you'd still have to do all the recursion `transitive` is currently doing.  You'd just be querying a map instead of a graph.

Beyond that, yeah, the "don't check native query" pr could use this graph logic.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj (hunk 3 above)
Comment (wzimrin) [reply enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: Fair

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 9]
```diff
@@ -0,0 +1,197 @@
...
+          [:= type-field "sandbox"]
+          [:= type-field "segment"]
+          [:= type-field "measure"]]))
+      (graph/filtered-graph (fn [[type id]]
+                              (or (not= type :card)
+                                  (-> (lib.metadata/card mp id)
+                                      :dataset-query
+                                      lib/any-native-stage?
+                                      not))))
+      graph/cached-graph))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: This still seems like it belongs in `models.dependency` with a better name, like `mbql-dependents`.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 10]
```diff
@@ -0,0 +1,197 @@
...
+(mu/defn- dependent-mbql-cards :- [:sequential ::lib.schema.id/card]
+  [graph
+   start-type :- ::deps.dependency-types/dependency-types
+   start-id   :- ::deps.dependency-types/entity-id]
+  (let [start [start-type start-id]]
+    (->> (graph/transitive graph [[start-type start-id]])
+         (keep (fn [[node-type node-id :as node]]
+                 (when (and (= node-type :card)
+                            (not= node start))
+                   node-id))))))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj:55]: So there's a subtlety here of the type that could introduce a bug later: as written, these two functions return

- A seq of all the **cards**
- Reachable transitively downstream
- Via segments, measures, cards and sandboxes.

That seems to be intended, so that's fine, but I think it's worth calling that out in some docstrings, lest this get accidentally changed to filter on the `graph/transitive` side and accidentally make this return only those cards that are directly reachable.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 11]
```diff
@@ -0,0 +1,197 @@
...
+
+(mr/def ::column-metadata-edits [:map-of :keyword :any])
+(mr/def ::card-metadata-edits [:map-of :string ::column-metadata-edits])
+(mr/def ::card-list-metadata-edits [:map-of ::lib.schema.id/card ::card-metadata-edits])
+
+(mu/defn- column-metadata-edits :- [:maybe ::column-metadata-edits]
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj:61]: These functions duplicate some logic in `querying.models.card.metadata`; especially the `editable-keys` set. That should absolutely exist in only one place.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 12]
```diff
@@ -0,0 +1,197 @@
...
+        not-empty)))
+
+(mu/defn- card-metadata-edits :- [:maybe ::card-metadata-edits]
+  [mp      :- ::lib.schema.metadata/metadata-providerable
+   card-id :- ::lib.schema.id/card]
+  (let [card (lib.metadata/card mp card-id)
+        original-metadata (:result-metadata card)
+        ;; Replace the metadata provider here to ensure that it is using the correct one.
+        calculated-metadata (->> card :dataset-query (lib/query mp) queries/infer-metadata)
+        calculated-by-name (m/index-by :lib/deduplicated-name calculated-metadata)
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj:83]: Are you sure this is the right name to use? ISTM that this is exactly where  `:lib/desired-column-alias` should be used, since it's deduplicated at the `returned-columns` [level](https://github.com/metabase/metabase/blob/master/src/metabase/lib/metadata/calculation.cljc#L476-L490) and should be populated on (lib) `:result-metadata`.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 13]
```diff
@@ -0,0 +1,197 @@
...
+
+  Takes a metadata provider because the queries' existing metadata provider may not be the one we want to use.  The
+  parent function should be ensuring that the passed-in metadata provider is correct."
+  [mp             :- ::lib.schema.metadata/metadata-providerable
+   card           :- ::lib.schema.metadata/card
+   metadata-edits :- ::card-list-metadata-edits]
+  (let [new-metadata (->> card :dataset-query (lib/query mp) queries/infer-metadata)
+        card-edits (metadata-edits (:id card))]
+    (if (= (:type card) :model)
+      (for [{name :lib/deduplicated-name :as column} new-metadata]
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj:116]: Likewise, this should be based on the `:lib/desired-column-alias`.

(Well, it should actually be based on the `:lib/column-key`s I'm working on right now, and which would survive (1) rearranging aggregations and (2) renaming expressions, unlike this logic. But they're not ready yet, so this logic with `:lib/desired-column-alias` is as correct as it's going to get.)

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 14]
```diff
@@ -0,0 +1,197 @@
...
+        (merge column (when card-edits (card-edits name))))
+      new-metadata)))
+
+(mu/defn- fresh-mp :- ::lib.schema.metadata/metadata-provider
+  "Creates a 'fresh' metadata provider for the given database id with no existing cache."
+  [db-id :- ::lib.schema.id/database]
+  (lib-be/with-existing-metadata-provider-cache (atom (cache/basic-cache-factory {}))
+    (lib-be/application-database-metadata-provider db-id)))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj:124]: `with-existing-metadata-provider-cache` is for cases where some cache outlives any one call stack, like `?dashboard_load_id` produces across several API calls.  
  
If you're creating a cache for a single call stack, you can use `lib-be/with-metadata-provider-cache` instead.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 15]
```diff
@@ -0,0 +1,197 @@
...
+
+(mu/defn- update-dependent-mbql-cards-metadata!
+  [original-mp     :- ::lib.schema.metadata/metadata-providerable
+   start-type      :- ::deps.dependency-types/dependency-types
+   start-id        :- ::deps.dependency-types/entity-id
+   previous-object :- :any
+   metadata-type   :- :keyword]
+  ;; Notes on metadata providers:
+  ;;
+  ;; The key thing here is that lib.metadata/card caches very aggressively (as of 2025/01, at least).  Instead of
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: 2026/01?

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 16]
```diff
@@ -0,0 +1,197 @@
...
+  ;; will effectively ask the underlying metadata provider for the card (using that special key) without ever talking
+  ;; to the override metadata provider.  Both the override metadata provider and the underlying metadata provider will
+  ;; always return whichever version of that card was requested and cached first.
+  ;;
+  ;; The solution here is three different metadata providers.  First, we have the original metadata provider (or
+  ;; really, metadata-providerable -- a query is fine here).  This doesn't have any special overrides and is used to
+  ;; fetch the current state of the world before any updates that happen in this function.
+  ;;
+  ;; Second, we have a "pre-update" metadata provider.  This is an override metadata provider based on a "fresh"
+  ;; metadata provider with no cached data.  This is intended to match the state of the world before whatever update
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: This should be more explicit to say something like "This has overrides intended to reproduce the state of the world before whatever update ..."

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 17]
```diff
@@ -0,0 +1,197 @@
...
+   start-type      :- ::deps.dependency-types/dependency-types
+   start-id        :- ::deps.dependency-types/entity-id
+   previous-object :- :any
+   metadata-type   :- :keyword]
+  ;; Notes on metadata providers:
+  ;;
+  ;; The key thing here is that lib.metadata/card caches very aggressively (as of 2025/01, at least).  Instead of
+  ;; going through the normal cache mechanism, it grabs the card normally, normalizes the query, and then caches the
+  ;; result using a special key.  The next time it gets called, it will check for that key first and never actually
+  ;; hit the standard card fetch flow at all.  Meanwhile, override metadata providers delegate all caching to their
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: FWIW I consider this a bug and a leak in the MP abstraction. We should update the contract for MPs to always return properly normalized `:dataset-query`s and then the regular caching mechanism works perfectly well and some of this complexity can be removed.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj [hunk 18]
```diff
@@ -0,0 +1,197 @@
...
+                     :returned-columns-fn (fn [mp card]
+                                            (updated-metadata mp card edits))
+                     :dependent-ids {:card cards}})
+        start [start-type start-id]
+        updates (->> (graph/transitive-children-of graph [start])
+                     (graph/keep-children
+                      (fn [[node-type node-id :as node]]
+                        (if (or (not= node-type :card)
+                                (= node start))
+                          nil
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]:
```suggestion
                        (when (and (= node-type :card)
                                   (not= node start))
                                   
```

File: test/metabase/audit_app/events/audit_log_test.clj [hunk 19]
```diff
@@ -65,19 +65,19 @@
...
+            (let [old-card (assoc card :name "Old Name", :type :question)]
+              (is (= {:object card :previous-object old-card :user-id (mt/user->id :rasta)}
+                     (events/publish-event! :event/card-update {:object card :previous-object old-card :user-id (mt/user->id :rasta)})))
+              (is (partial=
+                   {:topic    :card-update
+                    :user_id  (mt/user->id :rasta)
+                    :model    "Card"
+                    :model_id (:id card)
+                    :details  {:previous (cond-> {:name "Old Name"}
+                                           (= card-type :model) (assoc :model? false))
```
Comment (bshepherdson) [inline test/metabase/audit_app/events/audit_log_test.clj:77]: Isn't this inverted?

**Review by bshepherdson — APPROVED** [review]

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj (hunk 9 above)
Comment (wzimrin) [reply enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: It feels special-cased to this file to me, mostly due to excluding a bunch of entity types.  The "disable native validation" pr is actually implementing a proper, more general "only mbql dependents" function.

File: test/metabase/audit_app/events/audit_log_test.clj (hunk 19 above)
Comment (wzimrin) [reply test/metabase/audit_app/events/audit_log_test.clj:77]: This is the previous entry.  The old card was never a model.  If the new card is a model, then audit log will report that it used to not be a model but now is a model.  If the new card isn't a model, then this field didn't change and doesn't show up in the audit log.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj (hunk 11 above)
Comment (wzimrin) [reply enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj:61]: querying.models.card.metadata doesn't have any notion of editable-keys at all, from what I can tell.  It just pastes the entire model metadata into the query and lets lib figure out to keep.  Lib uses model-preserved-keys to figure out whether something can be overriden, and this just calls the same function.

querying.models.card.metadata does include logic for inferring mbql metadata, and we call that logic directly.

I don't think any logic here is duplicated.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj (hunk 12 above)
Comment (wzimrin) [reply enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj:83]: Not at all confident -- I was going off of your comment [here](https://www.notion.so/Keeping-result_metadata-up-to-date-with-the-dependency-graph-2e169354c90180908f60da8713597bed?d=2e169354c901807da5e4001ccebcfc86&source=copy_link#2e169354c90180dfb4aad79550b73af7).

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj (hunk 14 above)
Comment (wzimrin) [reply enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj:124]: I'm explicitly trying to avoid using a cached metadata provider here -- that's the whole point of the function.  Providing a new, empty cache seemed like the easiest way, though I'm open to suggestions here.

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj (hunk 18 above)
Comment (wzimrin) [reply enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: fixed

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj (hunk 16 above)
Comment (wzimrin) [reply enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: changed

File: enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj (hunk 15 above)
Comment (wzimrin) [reply enterprise/backend/src/metabase_enterprise/dependencies/metadata_update.clj]: years are hard, ok?
