### PR TITLE
don't allow the normal People admin actions to be enabled on oneself

### LINKED ISSUE #2702: unable to manually reset the password of the "setup user" in the admin panel
Tested on latest dev snapshot (0.18.0) and 0.17.1 on Heroku.
This doesn't appear to be browser specific but for what it's worth I was using Chrome.

To repro:
- Deploy a new instance, and go through set up.
- Reset own password, log out and attempt to log in with that password. This will not work.
- Login with your original password (which still works)
- Be confused, and test again by creating a new user and make them an admin.
- Log in as that new user and reset the original admin's password.
- Try to log in as the original admin with the new password. This will also not work.
- Log in as the original admin using your original password which still works.
- Contemplate the meaning of life, have a sip of coffee, and proceed to file a bug.

### PR DESCRIPTION
**Pull request by agilliland**
Fixes #2702

### CODE REVIEW

File: src/metabase/api/user.clj [hunk 1]
```diff
@@ -78,7 +78,8 @@
   {password     [Required ComplexPassword]}
   (check-self-or-superuser id)
   (let-404 [user (db/select-one [User :password_salt :password], :id id, :is_active true)]
-    (when (= id *current-user-id*)
+    (when (and (not (:is_superuser @*current-user*))
+               (= id *current-user-id*))
```
Comment (camsaul) [inline src/metabase/api/user.clj]: So we don't want superusers to be able to reset their own password?

Comment (camsaul) [inline src/metabase/api/user.clj]: it probably doesn't make sense to have the `check-self-or-superuser` call and then a few lines later a second call to check that the current user *isn't* a superuser

**Comment by camsaul** [comment]
It looks like this change will make it so only non-superusers can change their password?

File: src/metabase/api/user.clj (hunk 1 above)
Comment (agilliland) [inline src/metabase/api/user.clj]: In this case it does.  The api call as a whole is only meant to be available to any superuser or the api calling user regardless of their superuser status.  So that check continues to make sense.

The additional line a bit lower down is applying an extra check only in the case that the api call was  made by a non-superuser.

So both checks make sense.

**Comment by agilliland** [comment]
Nothing in the logic prevents a superuser from changing their password, and I've added a unit test just to verify that.

File: test/metabase/api/user_test.clj [hunk 2]
```diff
@@ -233,6 +233,23 @@
...
+             {:keys [id password]} (db/insert! User
+                                     :first_name   "test"
+                                     :last_name    "user"
+                                     :email        "hij@metabase.com"
+                                     :password     "def"
+                                     :is_superuser true)]
+  true
+  (do
+    ;; use API to reset the users password
+    (metabase.http-client/client creds :put 200 (format "user/%d/password" id) {:password     "abc123!!DEF"
```
Comment (camsaul) [inline test/metabase/api/user_test.clj]: looks like `metabase.http-client` is already aliased in this NS as `http`

**Comment by camsaul** [comment]
ok got it.
