### PR TITLE
Skip long values in JSON unfolding query

### LINKED ISSUE #45163: OOM errors during JSON unfolding
### Describe the bug

Some customers have OOM errors while inferring the schema of a JSON column during the sync-fields step. This issue is just to track its investigation and the fix.

[Context in slack](https://metaboat.slack.com/archives/C0641E4PB9B/p1719624233280609)

### To Reproduce

NA

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
NA
```

### Severity

high

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calherries**
Resolves https://github.com/metabase/metabase/issues/45163

### Why OOM errors can happen during JSON unfolding

In `describe-json-fields`, we fetch a sample of 500 rows of data into a ResultSet object from the database. We select all the JSON columns in the table at once for these rows. If there are sufficiently large JSON values among this sample we exhaust the heap space. This is all without even starting to parse the values. We could decrease the fetch size and fetch the data in batches, but doing that will make sync slower.

### The solution

This PR limits the size of each value that can be returned from the query.

Until recently (after https://github.com/metabase/metabase/pull/42638) we had a limit of 50,000 characters in a JSON string before we would attempt to parse a JSON value. This PR restores that 50,000 character limit, but in the query instead. If there is a JSON value that is longer than 50,000 characters, the query will return NULL in its place.

This PR technically constitutes a breaking change because it may result in some fields becoming inactive that would previously would be active. I still think we should backport it to 49 and 50, because that scenario seems relatively unlikely, the behaviour is the same as before https://github.com/metabase/metabase/pull/42638, and it is outweighed by the benefit of fixing the OOM errors.

### How to verify manually

```
;; launch Metabase with 4 GB of maximum heap space by setting -Xmx4g option in deps.edn

(require
 '[cheshire.core :as json]
 '[clojure.java.jdbc :as jdbc]
 '[metabase.driver.sql-jdbc.connection :as sql-jdbc.conn]
 '[metabase.sync :as sync]
 '[metabase.test :as mt]
 '[toucan2.core :as t2])

;; Create a new test db:
(mt/defdataset test-db [])
(mt/with-driver :postgres (mt/dataset test-db (def db (mt/db))))

;; Set up the table:
(let [j (json/encode {"a" (repeat 10000000 "x")})]
  (with-open [conn (jdbc/get-connection (sql-jdbc.conn/db->pooled-connection-spec db))]
    (jdbc/execute! {:connection conn} "CREATE TABLE IF NOT EXISTS large_jsonb_test (id SERIAL PRIMARY KEY, data JSONB)")
    (jdbc/execute! {:connection conn} "TRUNCATE TABLE large_jsonb_test")
    (dotimes [_ 100]
      (jdbc/execute! {:connection conn} [(str "INSERT INTO large_jsonb_test ( data ) VALUES (?::jsonb)") j]))))

(-> (:bytes (first (t2/query db "SELECT sum(pg_column_size(data)) as bytes FROM large_jsonb_test;")))
    (/ 1024 1024)
    float)
;; => 140 MB or so

;; the sync-fields step will fail with an OOM error before the change, and succeed after the change.
(sync/sync-database! db {:scan :schema})
```

This should be backported to 49. 
The new Druid JDBC driver will be implemented separately (issue: https://github.com/metabase/metabase/issues/46137), because it's currently difficult to use a new test dataset.

### CODE REVIEW

File: src/metabase/driver/sql.clj [hunk 1]
```diff
@@ -63,6 +63,17 @@
...
+  "Return a HoneySQL expression that calculates the length of a JSON field for a given driver.
+  `json-field-identifier` is the Identifier ([[metabase.util.honey-sql-2/Identifier]]) for a JSON field."
+  {:added "0.49.22", :arglists '([driver json-field-identifier])}
+  driver/dispatch-on-initialized-driver
+  :hierarchy #'driver/hierarchy)
+
+(defmethod json-field-length :default
+  [_driver _native-form]
+  ;; we rely on this to tell if the method is implemented for this driver or not
+  :nyi)
```
Comment (piranha) [inline src/metabase/driver/sql.clj:76]: is this check (for `:nyi`) implemented elsewhere?

Comment (calherries) [reply src/metabase/driver/sql.clj:76]: good catch, I removed it in a refactor. Was just thinking I needed to write a test for that... 
I've updated it now in 9c888c131122deca9571dc5280486c3610043dd2

Comment (qnkhuat) [reply src/metabase/driver/sql.clj:76]: I'd make this a var or make this value more recognizable + greppable

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj [hunk 2]
```diff
@@ -575,51 +576,70 @@
                                         (false? (:json_unfolding existing-field))))]
         (remove should-not-unfold? json-fields)))))
 
+(def ^:dynamic *nested-field-columns-max-row-length*
```
Comment (qnkhuat) [inline src/metabase/driver/sql_jdbc/sync/describe_table.clj:579]: wdyt if we make this configurable using env? Would be nice to have an escape hatch in case this is too low / or still too high.

**Comment by qnkhuat** [comment]
It would be nice to see the analysis here:
- I'm interested in whether there are more memory-intensive parts
- how much of an improvement does this make

File: src/metabase/driver/sql.clj (hunk 1 above)
Comment (calherries) [reply src/metabase/driver/sql.clj:76]: yeah I could namespace the keyword to be like `:driver.sql/nyi`

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj (hunk 2 above)
Comment (calherries) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:579]: Nice idea, I'll take it. We can't really increase this number substantially without risking additional OOMs. So allowing people to increase it if they need to is a sensible choice

Comment (calherries) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj]: done in 2d0c2360362d7df400153108fb4c7235d32d041b

**Comment by calherries** [comment]
@qnkhuat I can provide more analysis but what exactly is stopping us from landing this in its current state? The steps under `How to verify manually` already prove this is a bottleneck and that this change relieves it

**Comment by calherries** [comment]
To be fair we do not know yet, is whether this is the bottleneck that every customer getting an OOM is hitting. But I think it's a reasonable guess given the data LeAnn has given me in https://docs.google.com/spreadsheets/d/1vAL8HwgAmsAE-WhzdzTLsPDhsY6MvaixQiKPLE2YSf8/edit?gid=100008772#gid=100008772

File: src/metabase/driver/sql.clj [hunk 3]
```diff
@@ -63,6 +63,17 @@
       (seq referenced-card-ids)
       (update :metabase.models.query.permissions/referenced-card-ids set/union referenced-card-ids))))
 
+(defmulti json-field-length
+  "Return a HoneySQL expression that calculates the length of a JSON field for a given driver.
```
Comment (crisptrutski) [inline src/metabase/driver/sql.clj:67]: I would just clarify that this is the textual length, not the "collection length" (i.e. the number of top-level keys).

I assumed it was the latter before I read the code 😄

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj [hunk 4]
```diff
@@ -422,7 +425,7 @@
   "Parses given json (a string or a reader) into a map of paths to types, i.e. `{[\"bob\"} String}`.
 
   Uses Jackson Streaming API to skip allocating data structures, eschews allocating values when possible.
-  Respects *nested-field-column-max-row-length*."
+  Respects *nested-field-columns-max-row-length*."
```
Comment (crisptrutski) [inline src/metabase/driver/sql_jdbc/sync/describe_table.clj:428]: Perhaps make this a [[reference]]

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj [hunk 5]
```diff
@@ -575,51 +578,73 @@
...
+                                      (driver.sql/json-field-length driver field)]
+                                     nil
+                                     :else
+                                     field]
+                                    (last (h2x/identifier->components field))]))
+                               json-field-identifiers)]
     (if (seq pk-identifiers)
       {:select json-field-exprs
        :from   [table-expr]
-       ;; mysql doesn't support limit in subquery, so we're using inner join here
```
Comment (crisptrutski) [inline src/metabase/driver/sql_jdbc/sync/describe_table.clj:590]: Why remove this comment?

**Review by crisptrutski — APPROVED** [review]
LGTM

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj (hunk 5 above)
Comment (calherries) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:590]: whoops

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj (hunk 4 above)
Comment (calherries) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj]: 9b04fb0ca9d8d98a636088162cdbc4eb3f319e78

File: src/metabase/driver/sql.clj (hunk 3 above)
Comment (calherries) [reply src/metabase/driver/sql.clj]: yep, used "calculates the number of characters in a JSON field" 9b04fb0ca9d8d98a636088162cdbc4eb3f319e78

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj (hunk 5 above)
Comment (calherries) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:590]: put it back in 9b04fb0ca9d8d98a636088162cdbc4eb3f319e78

**Comment by calherries** [comment]
@metabase-bot backport release-x.49.x
