### PR TITLE
Cards use default values when required

### LINKED ISSUE #40038: Default value are not respected in cards (from 0.47.12 to 0.48.8 or 0.49.8)
### Describe the bug

I was following this bug because I though I had the same : https://github.com/metabase/metabase/issues/37831

But after upgrading I'm still experiencing similar issue.

I have a dashboard with several filters and no default values, it includes a card that have default values for one of these filters, it's working well in 0.47.12 but in 0.48.8 default values for the card is lost.

v0.47.12
- Dashboard filter : "activity" (dropdown, multiple values, not mandatory) that send it's values to each card filter "activity"
- Card filter : "activity" (field filter mapped to relevant table/field, string, dropdown list, mandatory, 3 default values)

 v0.48.8
- Dashboard filter : "activity" (dropdown, multiple values, not mandatory) that send it's values to each card filter "activity"
- Card filter : "activity" (field filter mapped to relevant table/field, string, dropdown list, mandatory, **no default values**)

### To Reproduce

1. Lauch a v0.47.12 instance
2. Create a card with a field filter and 3 default values
3. Add this card to a dashboard
4. Add a filter to this dashboard mapped to the card and the filter with default values
5. Test : the dashboard with no filter should show the card and results are filtered with default values
6. Upgrade to 0.48.8
7. Test : the dashboard show an error, the card can't display the result
8. Edit the card : default values are lost.
9. Rollaback to 0.47.12 (and restore a dump from this version)
10. Test : it's working again.

### Expected behavior

Default values should remain.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "4.15.18-2-pve",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-16",
      "tag": "v0.47.12",
      "branch": "?",
      "hash": "bddbc8f"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking

### Additional context

Imo related to https://github.com/metabase/metabase/issues/37831

### PR DESCRIPTION
**Pull request by wzimrin**
Closes https://github.com/metabase/metabase/issues/40038

### Description

If a card with a default value doesn't actually require a value, letting people clear the default value can be useful. However, if the card does require a value, letting people clear the default just throws an error.  This is a completely useless result, so we should use the default value in that case.

### How to verify

1. Create a saved sql query with a required parameter that has a default value
2. Add it to a dashboard with a filter, and hook the filter to the card's parameter
3. Clear the dashboard's filter
4. Confirm that the card is using its own default instead of erroring

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/driver/common/parameters/values.clj [hunk 1]
```diff
@@ -264,8 +268,6 @@
     ;; If the param is not present in `params` use a default from either the tag or the Dashboard parameter.
     ;; If both the tag and Dashboard parameter specify a default value, prefer the default value from the tag.
     (or (:value matching-param)
-        (when (and nil-value? (:required tag))
-          (throw (missing-required-param-exception (:display-name tag))))
```
Comment (appleby) [inline src/metabase/driver/common/parameters/values.clj:268]: The only thing that gives me pause is that this was clearly an intentional decision to throw in this case (and above), but the rational has been lost to the mists of time. Feels like "Chesterton's fence". Trolling through the comments in https://github.com/metabase/metabase/pull/31891 I don't see anything related to this specific point. That PR seemed to be more focused on enabling the case of overriding the default for non-required params, so hard to tell if there was any strong reason to make it an error for required params.

The only thing I can think is maybe this is the behavior you want for programatic API calls. Like if the user clears the value in the UI, using the default seems ok, but if someone writes a script that hits the API endpoints, providing a nil value for a required param might be a programming error and you want the thing to fail loudly so you know to go fix your script. Not a very compelling argument though.

**Review by appleby — APPROVED** [review]
Changes LGTM. If you haven't already, might be worth spending 5-10 mins doing git / slack archeology to see if you can unearth the rational for the original behavior.

File: src/metabase/driver/common/parameters/values.clj (hunk 1 above)
Comment (wzimrin) [reply src/metabase/driver/common/parameters/values.clj:268]: At a bare minimum, the new behavior was discussed and decided upon [here](https://metaboat.slack.com/archives/C0645JP1W81/p1719233020129649), and various people weighed in on it.
