### PR TITLE
fix(sdk): fix crashes on React 19 due to findDOMNode on Gauge and Modal

### LINKED ISSUE #67850: We're using findDOMNode which is not React 19 compatible
### Describe the bug

if you're using React 19 on your app, Metabase still uses findDOMNode on some places (gauge viz and a transitive dependency) which will break the apps

### To Reproduce

1) make an app that uses purely react 19
2) embed Metabase with the SDK
3) try editiing a filter on a dashboard
4) see that it breaks with BL(...).findDOMNode is not a function

### Expected behavior

We should not be using deprecated functions

### Logs

TypeError: BL(...).findDOMNode is not a function
    at r.performEnter (embedding-sdk.js:189:9205)
    at r.updateStatus (embedding-sdk.js:189:8951)
    at r.componentDidMount (embedding-sdk.js:189:8253)
    at react-stack-bottom-frame (react-dom-client.development.js:22996:22)
    at runWithFiberInDEV (react-dom-client.development.js:844:30)
    at commitLayoutEffectOnFiber (react-dom-client.development.js:12709:21)
    at recursivelyTraverseLayoutEffects (react-dom-client.development.js:13672:11)
    at commitLayoutEffectOnFiber (react-dom-client.development.js:12691:11)

### Information about your Metabase installation

```JSON
v57.x
```

### Severity

P2/1

### Additional context

NA

### PR DESCRIPTION
**Pull request by heypoom**
Closes #67850
Closes EMB-1171

### Description

There are 2 instances of using `findDOMNode` that crashes Modular Embedding SDK customers that are using React 19:

1. If you render an `EditableDashboard` on a dashboard that has multiple value filters, and then click on "How should people filter on this column? > Edit", it crashes the SDK that is running on React 19. This is because it's using `Modal` which uses `WindowModal` which uses `react-transition-group` which uses `findDOMNode` underneath.

I tried to do a global fix for `react-transition-group` for many hours but couldn't do it, so the easiest fix is to use Mantine modals from `mantine/ui` for now, which works well.

CleanShot 2569-01-09 at 04 33 19@2x

2. If you put a Gauge label that's really long, we used to use `findDOMNode` to hide the label if it's long. This crashes React 19 because there is no longer `findDOMNode`.
 
CleanShot 2569-01-09 at 04 34 35@2x

### How to verify

- Setup a SDK app on React 19
- Render an `EditableDashboard` on a dashboard that has multiple value filters, and then click on "Edit"
- Modal should appear correctly like the above screenshot
- Put a Gauge label that's really really long
- Gauge should not crash like the above screenshot

### Future work

The SDK can crash if using the Actions feature on React 19, but we should fix this separately as I'm not aware of SDK customers that use React 19 and use Actions (a bit of a rare combination):

```
1. ActionVizForm - metabase/actions/components/ActionViz/ActionVizForm.tsx:10
2. ActionCreator - metabase/actions/containers/ActionCreator/ActionCreator.tsx:8
3. ActionParametersInputModal - metabase/actions/containers/ActionParametersInputForm/ActionParametersInputModal.tsx:4
4. ActionPicker - metabase/actions/containers/ActionPicker/ActionPicker.tsx:7

Access path: InteractiveDashboard/EditableDashboard → ActionSidebar → ActionDashcardSettings → these components
```

### Checklist

- [x] Tests have been added/updated to cover changes in this PR - E2E

### CODE REVIEW

File: frontend/src/metabase/parameters/components/ValuesSourceSettings/ValuesSourceSettings.tsx [hunk 1]
```diff
@@ -66,15 +65,19 @@ export function ValuesSourceSettings({
...
-            parameter={parameter}
-            onSubmit={onChangeSourceSettings}
-            onClose={closeModal}
-          />
-        </Modal>
-      )}
+      <Modal
+        opened={isModalOpened}
+        onClose={closeModal}
+        size="lg"
```
Comment (WiNloSt) [inline frontend/src/metabase/parameters/components/ValuesSourceSettings/ValuesSourceSettings.tsx]: The size difference is too stark. We need to fix this. Can you make them more similar in size? It doesn't have to be the same. It's also be great if you ask in design-system channel what size this should be.

#### Before
Image

#### After
Image

**Review by WiNloSt — CHANGES_REQUESTED** [review]
Everything else looks good, but the modal size.

File: frontend/src/metabase/parameters/components/ValuesSourceSettings/ValuesSourceSettings.tsx (hunk 1 above)
Comment (heypoom) [reply frontend/src/metabase/parameters/components/ValuesSourceSettings/ValuesSourceSettings.tsx]: @WiNloSt Oh thanks, great catch! I was testing on an embedded app first so I didn't even notice the modals have shrunken in size, I thought it was always that small 🙏🏻

Comment (heypoom) [reply frontend/src/metabase/parameters/components/ValuesSourceSettings/ValuesSourceSettings.tsx]: I asked in [design-system](https://metaboat.slack.com/archives/C057WD5L0JG/p1767978856863779) here, FYI.

Comment (heypoom) [reply frontend/src/metabase/parameters/components/ValuesSourceSettings/ValuesSourceSettings.tsx]: Restored it to [be 65%](https://github.com/metabase/metabase/pull/67953/commits/1f6540d1197696f3dfc55c590eba647e04a2fa86), same as old modal's size for now. Maz asked to [leave it as before](https://metaboat.slack.com/archives/C057WD5L0JG/p1767979143478839?thread_ts=1767978856.863779&cid=C057WD5L0JG) in case there are really long options

**Review by WiNloSt — APPROVED** [review]
The modal looks good now. I have a question tho, how did you figure out the WindowModal using a transitive dependency that uses `findDOMNode` under the hood. That wasn't reported in the original issue was it?

**Comment by heypoom** [comment]
> I have a question tho, how did you figure out the WindowModal using a transitive dependency that uses findDOMNode under the hood. That wasn't reported in the original issue was it?

@WiNloSt I went into the Pylon conversation and found where the customer originally reported the issue, and there was more context and screenshots about editing dashboards using EditableDashboards there. I repro'ed and tested until I got it to no longer crash. I think that wasn't added to the GitHub issue though, maybe because of privacy reasons 🙏🏻
