### PR TITLE
Markdown->Slack refactor and fix for nested bold/italic rendering

### LINKED ISSUE #21658: Nested bold syntax in headers or other bold text doesn't render nicely in Slack
**Describe the bug**
Certain Markdown syntax will not render properly in Slack when included in a dashboard subscription.

**To Reproduce**
1. Paste the following into a text card on a dashboard and save the dashboard
```
# Heading 1 with **bold text**

**Bold text with **more bold text****
```
2. Send the dashboard as a subscription to a Slack channel
3. See that the Markdown is rendered as
```
*Heading 1 with *bold text**
*Bold text with *more bold text**
```

**Expected behavior**
Since Slack doesn't have any syntax for bold with a higher font weight than normal bold, we should just ignore nested bold syntax so that Slack will render the top-level bold text properly.

**Information about your Metabase Installation:**
Current master

**Severity**
Extremely minor, since making part of a header bold or using nested bold syntax seems like a very niche use of Markdown. Nevertheless, it's a discrepancy in how we handle formatting between the FE and BE, so it should be considered a bug.

### PR DESCRIPTION
**Pull request by noahmoss**
* Refactored the Markdown AST -> Slack syntax code to use multimethods, which I think is a bit clearer and more organized than the `case` statement I was using before. Everything should be functionally the same. This also makes the fix for #21658 much easier.

* Replaces usages of the term `mrkdwn` (which is what Slack calls their formatting syntax) with `slack`, since `mrkdwn` is needlessly confusing.

* Fixed #21658

### CODE REVIEW

File: src/metabase/pulse/markdown.clj [hunk 1]
```diff
@@ -342,14 +399,16 @@
 
 (defmulti process-markdown
   "Converts a markdown string from a virtual card into a form that can be sent to a channel
-  (mrkdwn for Slack; HTML for email)."
+  (Slack's markup language, or HTML for email)."
   (fn [_markdown channel-type] channel-type))
 
-(defmethod process-markdown :mrkdwn
```
Comment (noahmoss) [inline src/metabase/pulse/markdown.clj:348]: I changed this from `:mrkdwn` to `:slack` and removed other references to `mrkdwn` because even though Slack's syntax is technically called "mrkdwn", it's a needlessly confusing name to use in our code

File: src/metabase/pulse/markdown.clj [hunk 2]
```diff
@@ -203,113 +204,169 @@
...
+  "Given the value from the :content field of a Markdown AST node, and a keyword representing a tag type, converts all
+  instances of the tag in the content to `:default` tags. This is used to suppress rendering of nested bold and italic
+  tags, which Slack doesn't support."
+  [content tag]
+  (walk/postwalk
+   (fn [node]
+     (if (and (map? node) (= (:tag node) tag))
+        (assoc node :tag :default)
+        node))
+   content))
```
Comment (noahmoss) [inline src/metabase/pulse/markdown.clj:217]: Here's the actual fix for #21658

**Review by bshepherdson — APPROVED** [review]
