### PR TITLE
Disallow engine change on sample db

### LINKED ISSUE #16382: Re-using "Sample Dataset" database connection for another database type will stop working on restart
**Describe the bug**
The default "Sample Dataset" database connection can be changed to any other database, but upon restart of the instance the connection details are lost and the connection will be in limbo between referencing the new database type, but without correct details.
This is caused by `metabase_database.is_sample=true`, which then overwrites `metabase_database.details` on startup.

**To Reproduce**
1. Setup an instance
2. Admin > Databases > "Sample Dataset"
3. Change it to any other database type and fill in the details
4. Validate that it now makes queries to whatever is configured in step 3.
5. Restart the instance
6. Now all questions (for this connection) will stop working, since they're querying the selected database type, but without any details (so it will make queries to defaults like `localhost:3306`) and viewing Admin > Databases > (whatever "Sample Dataset" might have changed to in step 3) > will just show empty information.
image

**Expected behavior**
Either lock the "Sample Dataset", so it cannot be modified to a different type (or the Connection String), or make sure to set `metabase_database.is_sample=false` when the connection is modified (besides if the name is changed)

**Information about your Metabase Installation:**
Only tested 0.39.3, but I believe this has always been a problem, since `is_sample` was introduced.

**Additional context**
This might have been the reason for some obscure problems that people have hit, but I just never connected the dots.

### PR DESCRIPTION
**Pull request by escherize**
Fixes [#16382](https://github.com/metabase/metabase/issues/16382). 

In this PR, we do not allow changes to the `engine` of sample databases (any Database where `is_sample` is `true`). This work does not gray out fields, which turned out to be non-trivial, and involved implementing a read only mode for our Select component. This PR should be followed on with changes to make the engine select be disabled.

### CODE REVIEW

File: src/metabase/models/database.clj [hunk 1]
```diff
@@ -135,36 +135,48 @@
...
+         old-fieldvalues-schedule :cache_field_values_schedule
+         existing-engine          :engine
+         existing-name            :name} (db/select-one [Database
+                                                         :metadata_sync_schedule
+                                                         :cache_field_values_schedule
+                                                         :engine
+                                                         :name
+                                                         :is_sample] :id (u/the-id database))
+        new-engine                       (some-> new-engine keyword)]
+    (if (and is-sample?
```
Comment (noahmoss) [inline src/metabase/models/database.clj:153]: nit: up to you, but you could use `when` here to avoid indenting the rest of the function since the exception will short-circuit it

File: test/metabase/models/database_test.clj [hunk 2]
```diff
@@ -216,6 +216,24 @@
                   (is (nil? (db/select-one Secret :id secret-id))
                       (format "Secret ID %d was not removed from the app DB" secret-id)))))))))))
 
+(deftest user-may-not-update-sample-database-test
+  (binding [api/*current-user-id* (mt/user->id :crowberto)]
```
Comment (noahmoss) [inline test/metabase/models/database_test.clj:220]: is this binding important for the test?

if you do need it, you can use the `with-test-user` macro instead

**Review by noahmoss — APPROVED** [review]

File: test/metabase/models/database_test.clj (hunk 2 above)
Comment (escherize) [reply test/metabase/models/database_test.clj:220]: Good catch! I don't think the user is related to the test at all.

File: src/metabase/models/database.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/models/database.clj:153]: There are pros and cons to both approaches. I tend to lean on the side of trying to make choices that minimize the overall indentation level of the code, e.g. I personally find flatter code like

```c++
if (...) {
  return;
}
DoSomethingElse();
```

easier to read than 

```c++
if (...) {
  return;
} else {
  DoSomethingElse();
}
```

[Someone else put the reasoning for this better than me](http://blog.wilshipley.com/2005/07/code-insults-mark-i.html?q=code+insults):

> Don't indent and indent and indent for the main flow of the method. This is huge. Most people learn the exact opposite way from what's really proper — they test for a correct condition, and if it's true, they continue with the real code inside the "if".
>
> What you should really do is write "if" statements that check for improper conditions, and if you find them, bail. This cleans your code immensely, in two important ways: (a) the main, normal execution path is all at the top level, so if the programmer is just trying to get a feel for the routine, all she needs to read is the top level statements, instead of trying to trace through indention levels figuring out what the "normal" case is, and (b) it puts the "bail" code right next to the correctness check, which is good because the "bail" code is usually very short and belongs with the correctness check.

Just my 2 cents tho. I just wanted to point out good reasons you might consider keeping things flat as well

File: test/metabase/models/database_test.clj [hunk 3]
```diff
@@ -216,6 +216,23 @@
...
+                                                                    :name      "Sample Database"
+                                                                    :details   {:db "./resources/sample-database.db;USER=GUEST;PASSWORD=guest"}}]
+    (testing " updating the engine of a sample database is not allowed"
+      (try (db/update! Database id :engine :sqlite)
+           (catch Exception e
+             (is (= "The engine on a sample database cannot be changed." (.getMessage e)))
+             (is (= {:status-code     400
+                     :existing-engine :h2
+                     :new-engine      :sqlite}
+                    (ex-data e))))))
```
Comment (camsaul) [inline test/metabase/models/database_test.clj:231]: You should do `(is (thrown-with-msg? ...))` here because if this **does not** throw an Exception then those `is` forms inside the `catch` are never going to run. `thrown?` and `throw-with-msg?` actually assert that an Exception is thrown and fail if one is not

**Comment by camsaul** [comment]
Did we still want to disallow changing `details` in the API (but still allow it for the special case where we update it on launch)?

**Comment by escherize** [comment]
Reviewing the issue, changing `details` did not cause our users any problems. Also that is the piece that was complicating our tests so I decided to leave it off. It simplified this submission a lot.

**Review by camsaul — APPROVED** [review]
Approving with the caveat that you should change that test to use `thrown-with-msg?` so those specific assertions fail if an Exception isn't thrown

**Comment by escherize** [comment]
So, we just allow it to be updated all the time, and if someone wants to change their sample db details, e.g. syncing schedule, well that isn't going to cause any connection problems for them.

**Comment by escherize** [comment]
> the caveat that you should change that test to use thrown-with-msg? so those specific assertions fail if an Exception isn't thrown

Will do!
