### PR TITLE
Parse metadata of card fields passed from JS

### LINKED ISSUE #32948: Frontend breaking when selecting another group by
### Describe the bug

Can't reproduce from scratch but, there's an issue on question 12740 on our internal instance where the frontend breaks when selecting a field to group by in the joined question
[Screencast from 08-04-2023 10:38:43 AM.webm](https://github.com/metabase/metabase/assets/1711649/20c28e30-3606-4ef6-80f5-95c5e9f6a7a1)
```
Error: No matching clause: dispatch-type/map at R.s4
```

### To Reproduce

Go to question 12740, notebook
then add a group by from the joined question

see the error

### Expected behavior

Frontend should not break

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by metamben**
Fixes #32948.

### CODE REVIEW

File: src/metabase/lib/js/metadata.cljs [hunk 1]
```diff
@@ -218,9 +218,22 @@
...
+  (let [parse-object (parse-object-fn object-type)
+        unparsed-fields (object-get metadata "fields")]
+    (obj->clj (keep (fn [[k v]]
+                      ;; Sometimes fields coming from saved questions are only present with their ID
+                      ;; prefixed with "card__<card-id>:". For such keys we parse the field ID from
+                      ;; the suffix and use the entry unless the ID is present in the metadata without
+                      ;; prefix. (The assumption being that the data under the two keys are mostly the
+                      ;; same but the one under the plain key is to be preferred.)
+                      (when-let [field-id (or (parse-long k)
+                                              (when-let [[_ id-str] (re-matches #"card__\d+:(\d+)" k)]
```
Comment (camsaul) [inline src/metabase/lib/js/metadata.cljs:232]: You can use `lib.util/legacy-string-table-id->card-id` for this

**Review by camsaul — APPROVED** [review]
hmm, did not realize fields could have `card__<id>:<id>`, but this makes sense. Works for me.

It would be nice to write a test for this parsing logic tho
