### PR TITLE
Don't delete a connection impersonation policy when non-data perms are updated

### LINKED ISSUE #33754: Can't remove permission to manage database due to error: No matching clause
### Describe the bug

I have a user group that has been granted permission to manage database (I don't remember setting this so somehow it defaulted to yes when the feature got introduced?), so I tried to change to No. When saving, it is erroring out with: No matching clause

### To Reproduce

1. Create user group and grant permission to manage data base
2. Try to remove permission and save
3. Error happens: No matching clause

### Expected behavior

No error / it should save change

### Logs

[28beb7ea-944c-4cee-a8e7-819dd8203b2f] 2023-09-06T09:04:42-07:00 ERROR metabase.server.middleware.log PUT /api/permissions/graph 500 91.0 ms (10 DB calls) 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "No matching clause: ",
   :data
   {:toucan2/context-trace
    [["resolve connection" {:toucan2.connection/connectable org.postgresql.jdbc.PgConnection}]
     ["resolve connection" {:toucan2.connection/connectable nil}]
     ["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}]
     ["resolve connection" {:toucan2.connection/connectable :default}]
     ["resolve connection" {:toucan2.connection/connectable nil}]]},
   :at
   [metabase_enterprise.advanced_permissions.models.connection_impersonation$delete_impersonations_for_group_database_BANG_
    invokeStatic
    "connection_impersonation.clj"
    53]}
  {:type java.lang.IllegalArgumentException,
   :message "No matching clause: ",
   :at
   [metabase_enterprise.advanced_permissions.models.connection_impersonation$delete_impersonations_for_group_database_BANG_
    invokeStatic
    "connection_impersonation.clj"
    53]}],
 :trace
 [[metabase_enterprise.advanced_permissions.models.connection_impersonation$delete_impersonations_for_group_database_BANG_
   invokeStatic
   "connection_impersonation.clj"
   53]
  [metabase_enterprise.advanced_permissions.models.connection_impersonation$delete_impersonations_for_group_database_BANG_
   invoke
   "connection_impersonation.clj"
   47]
  [metabase_enterprise.advanced_permissions.models.connection_impersonation$delete_impersonations_for_group_BANG_
   invokeStatic
   "connection_impersonation.clj"
   63]
[metabase_enterprise.advanced_permissions.models.connection_impersonation$delete_impersonations_for_group_BANG_
   invoke
   "connection_impersonation.clj"
   60]
  [metabase_enterprise.advanced_permissions.models.connection_impersonation$fn__114003$delete_impersonations_if_needed_after_permissions_change_BANG___114004
   invoke
   "connection_impersonation.clj"
   75]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.public_settings.premium_features$dynamic_ee_oss_fn$fn__47014 doInvoke "premium_features.clj" 448]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [metabase.models.permissions$fn__48728$_AMPERSAND_f__48729$with_connection_STAR___48733$with_transaction_STAR___48734
   invoke
   "permissions.clj"
   1452]
  [toucan2.connection$bind_current_connectable_fn$fn__26580 invoke "connection.clj" 104]
  [toucan2.connection$do_with_transaction_primary_method_java_sql_Connection$fn__26642 invoke "connection.clj" 277]
  [next.jdbc.transaction$fn__26073 invokeStatic "transaction.clj" 128]
  [next.jdbc.transaction$fn__26073 invoke "transaction.clj" 115]
  [next.jdbc.protocols$fn__25232$G__25227__25241 invoke "protocols.clj" 58]
  [next.jdbc$transact invokeStatic "jdbc.clj" 416]
  [next.jdbc$transact invoke "jdbc.clj" 408]
  [toucan2.connection$do_with_transaction_primary_method_java_sql_Connection invokeStatic "connection.clj" 276]
  [toucan2.connection$do_with_transaction_primary_method_java_sql_Connection invoke "connection.clj" 270]
  [clojure.lang.AFn applyToHelper "AFn.java" 165]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 457]
  [clojure.core$partial$fn__5908 invoke "core.clj" 2643]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
...
(hard to copy long stacktrace / it would be nice if there is a copy bottom next to each log line). 

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.186-179.751.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "redshift",
      "mysql",
      "postgres",
      "bigquery-cloud-sdk",
      "mongo",
      "h2",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-06",
      "tag": "vUNKNOWN",
      "branch": "master",
      "hash": "8cb63df"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

Medium as it is a security issue but there are workarounds

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
We delete connection impersonation policies automatically if the data perms for a database in the graph are modified from `impersonated` to any other value. However, this was also being triggered when non-data perms, like data model or db detail perms are modified. I've fixed this check and made a similar fix in the GTAP code that this was derived from (though that wasn't broken due to another piece of logic that saved it) and added a test.

resolves https://github.com/metabase/metabase/issues/33754 (description is a different issue but it's the same root cause)

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/advanced_permissions/models/connection_impersonation.clj [hunk 1]
```diff
@@ -60,9 +60,10 @@
 (defn- delete-impersonations-for-group! [{:keys [group-id]} changes]
   (log/debugf "Deleting unneeded Connection Impersonation policies for Group %d. Graph changes: %s" group-id (pr-str changes))
   (doseq [database-id (set (keys changes))]
-    (delete-impersonations-for-group-database!
-     {:group-id group-id, :database-id database-id}
-     (get-in changes [database-id :data :schemas]))))
+    (when-let [data-perm-changes (get-in changes [database-id :data :schemas])]
```
Comment (adam-james-v) [inline enterprise/backend/src/metabase_enterprise/advanced_permissions/models/connection_impersonation.clj:63]: If I'm understanding your change, you're just ensuring that `nil` is never passed into the function `delete-impersonations-for-group-database!` right?

I wonder if it makes more sense to capture the nil check in the function directly?

`(when (and (not= :impersonated changes) (not (nil? changes)))` or something like that.

Since it's a private fn anyway, I don't consider this a big deal.

File: enterprise/backend/test/metabase_enterprise/advanced_permissions/api/impersonation_test.clj [hunk 2]
```diff
@@ -98,3 +98,30 @@
                                                                  :attribute "Attribute Name"}]
           (mt/user-http-request :crowberto :get 402 "ee/advanced-permissions/impersonation")
           (is (= impersonation (t2/select-one :model/ConnectionImpersonation :id impersonation-id))))))))
+
+(deftest delete-impersonation-policy-after-permissions-change-test
```
Comment (adam-james-v) [inline enterprise/backend/test/metabase_enterprise/advanced_permissions/api/impersonation_test.clj:102]: Nice, clear test!

**Review by adam-james-v — APPROVED** [review]
Straightforward and the test is a good addition!

File: enterprise/backend/src/metabase_enterprise/advanced_permissions/models/connection_impersonation.clj (hunk 1 above)
Comment (noahmoss) [reply enterprise/backend/src/metabase_enterprise/advanced_permissions/models/connection_impersonation.clj:63]: I actually had something like that originally and changed it to this. My reasoning is that it's more explicit that we're pulling out `:data :schemas` from the graph, and when that doesn't exist, we skip the connection impersonation update. 

When we're doing a `nil` check inside the function it's not super clear what circumstances might result in a `nil` being there.

Comment (adam-james-v) [reply enterprise/backend/src/metabase_enterprise/advanced_permissions/models/connection_impersonation.clj:63]: Ah, that's a really good point. Good thinking!
