### PR TITLE
44723 human readable coercion strategies

### LINKED ISSUE #44723: Coercion strategies don't have human-friendly text in Admin Table Metadata
On `master` (51.x)

Admin Panel > Table Metadata > (Select any table) > (Click the Gear Icon For any Column)

The list of possible coercion strategies just uses the underlying internal names for the strategies rather than a human friendly description of them.

IIRC these used to have human-friendly names, so I think this is probably a regression.

image

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/44723

### Description
Over a year ago, the field editor was refactored so that fields could be edited without requiring the full database metadata ([PR here](https://github.com/metabase/metabase/pull/30484)). When this work was done, we dropped humanizing the coercion strategies, and later on the files that did that string manipulation were removed as they were no longer imported by any files

This PR reverts the commit removing the files, converts them to TS, and adds an e2e test for casting field types

### How to verify
1. Admin -> Table Metadata -> Sample DB -> Feedback
2. Go to the ratings field and click the gear
3. There should be an option to cast the field to a different data type (this is being interpreted as a number, so you're able to cast to UNIX Time)
4. The options in that menu should not be namespaced with `Coercion/`

### Demo
chrome_FZvFE2ygRL

### Checklist
- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/admin/datamodel/utils/humanizeCoercionStrategy.ts [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+  UNIXMilliSeconds: "UNIX milliseconds",
+  UNIXMicroSeconds: "UNIX microseconds",
+  UNIXNanoSeconds: "UNIX nanoseconds",
+  YYYYMMDDHHMMSSString: "YYYYMMDDHHMMSS string",
+  YYYYMMDDHHMMSSBytes: "YYYYMMDDHHMMSS bytes",
+};
+
+const RIGHT_TERM_CONVERSIONS: Record<string, string> = {
+  DateTime: "Datetime",
+};
```
Comment (rafpaf) [inline frontend/src/metabase/admin/datamodel/utils/humanizeCoercionStrategy.ts:13]: Could we localize these strings?

ttag won't know the locale if these Records are defined in module scope, so you could define them inside a `getStrings` function called by the treat* functions

File: frontend/src/metabase/admin/datamodel/utils/humanizeCoercionStrategy.ts [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+  return rightTerm === undefined
+    ? shortString
+    : treatTermsAndJoin(leftTerm, rightTerm);
+}
+
+function treatTermsAndJoin(left: string, right: string) {
+  const treatedLeftTerm = treatLeftTerm(left);
+  const treatedRightTerm = treatRightTerm(right);
+
+  return [treatedLeftTerm, treatedRightTerm].join(" → ");
```
Comment (rafpaf) [inline frontend/src/metabase/admin/datamodel/utils/humanizeCoercionStrategy.ts:34]: I'll leave this up to you but strictly speaking it would be smart to localize the arrow too (with a context string explaining what it means here). Otherwise it will point backwards in RTL languages which will be super confusing

File: frontend/src/metabase/admin/datamodel/utils/humanizeCoercionStrategy.unit.spec.ts [hunk 3]
```diff
@@ -0,0 +1,173 @@
...
+    const expected = "YYYYMMDDHHMMSS string → Temporal";
+
+    const humanized = humanizeCoercionStrategy(original);
+
+    expect(humanized).toBe(expected);
+  });
+
+  it("converts YYYYMMDDHHMMSSBytes->Temporal to YYYYMMDDHHMMSS → Time", () => {
+    const original = "YYYYMMDDHHMMSSBytes->Temporal";
+    const expected = "YYYYMMDDHHMMSS bytes → Temporal";
```
Comment (rafpaf) [inline frontend/src/metabase/admin/datamodel/utils/humanizeCoercionStrategy.unit.spec.ts:167]: The test name doesn't match the string here - should one of them be changed?

Comment (rafpaf) [reply frontend/src/metabase/admin/datamodel/utils/humanizeCoercionStrategy.unit.spec.ts:167]: Same with line 158

**Review by rafpaf — CHANGES_REQUESTED** [review]
Looks close!

**Review by rafpaf — APPROVED** [review]
