### PR TITLE
[cache] surface last run time and make sure "nocache" won't use cache

### LINKED ISSUE #42778: Questions always say "Updated a few seconds ago"
There's a discrepancy between the timestamp in the sidebar and the one in the footer. In the sidebar it says this question was last cached 44 minutes ago. In the footer it says "Updated a few seconds ago."

image

### To Reproduce

View a question that was cached more than a minute ago, and look at the "Updated" timestamp in the footer.

I think this happens because `QuestionLastUpdated` has:

```
t`Updated ${moment(result.updated_at).fromNow()}`
```

But `result.updated_at` is `undefined`. I think the field might be obsolete.

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "21.0.1+12-LTS-29",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "21.0.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "21.0.1+12-LTS-29",
    "os.name": "Mac OS X",
    "os.version": "14.1",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "sqlite",
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.11 (Homebrew)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2024-05-14",
      "src_hash": "b71361ac052039d559b195106d7a46710ce08931",
      "tag": "v1.1.3-SNAPSHOT",
      "hash": "6284aeb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P3

### Additional context

_No response_

### LINKED ISSUE #44458: Some caching improvements
- `updated_at` is not updated or communicated correctly to frontend
- `nocache` strategy should prevent using cache (even when cache already exists)
- think about adding something to adjust date for e2e tests

[Context](https://metaboat.slack.com/archives/C06KX7QECN4/p1718624152579009)

### PR DESCRIPTION
**Pull request by sansolovyov**
A little change, first we want to show last execution time of a query to users - and frontend actually uses `updated_at` field, it's just nothing on backend actually returns in. But I re-use `cached` field - it's communicated to the frontend anyways, accounted in tests and makes more sense than `updated_at`.

And `:nocache` obviously should mean 'do not use cache' as much as it means 'do not store cache'.

Fixes #44458, fixes #42778

### CODE REVIEW

File: test/metabase/query_processor/middleware/cache_test.clj [hunk 1]
```diff
@@ -348,10 +349,13 @@
...
-            (let [avg-execution-time (query/average-execution-time-ms q-hash)]
+            (let [avg-execution-time (query/average-execution-time-ms q-hash)
+                  res (qp/process-query (qp/userland-query query))]
               (is (number? avg-execution-time))
-              ;; rerun query getting cached results
-              (is (:cached (qp/process-query (qp/userland-query query))))
+              (testing "rerun query getting cached results"
+                (is (:cached res))
+                ;; and user will get indication when was query ran last time
+                (is (:updated_at res)))
```
Comment (crisptrutski) [inline test/metabase/query_processor/middleware/cache_test.clj:358]: Maybe worth testing the type of res as wall?

File: test/metabase/query_processor/middleware/cache_test.clj [hunk 2]
```diff
@@ -348,10 +349,13 @@
             (u/deref-with-timeout called-promise 500)
             (is (= 1 @save-execution-metadata-count))
             (is (= 1 @update-avg-execution-count))
-            (let [avg-execution-time (query/average-execution-time-ms q-hash)]
+            (let [avg-execution-time (query/average-execution-time-ms q-hash)
+                  res (qp/process-query (qp/userland-query query))]
               (is (number? avg-execution-time))
```
Comment (crisptrutski) [inline test/metabase/query_processor/middleware/cache_test.clj:354]: Perhaps check that it is a non-zero number rather?

**Review by crisptrutski — APPROVED** [review]
Approving since the failures seem to be something needing updating in the tests themselves.

File: test/metabase/query_processor/middleware/cache_test.clj (hunk 1 above)
Comment (piranha) [reply test/metabase/query_processor/middleware/cache_test.clj:358]: idk, why? there are other tests checking that query processing works :)

Comment (crisptrutski) [reply test/metabase/query_processor/middleware/cache_test.clj:358]: Sorry, I meant the type of the timestamp. Ideally we'd even check that it's within some tolerance based on the time things took in the test.

File: src/metabase/query_processor/middleware/process_userland_query.clj [hunk 3]
```diff
@@ -95,6 +95,7 @@
        (dissoc :error :hash :executor_id :action_id :is_sandboxed :card_id :dashboard_id :pulse_id :result_rows :native))
    (dissoc result :cache/details)
    {:cached                 (boolean (:cached cache))
+    :updated_at             (:updated_at cache)
```
Comment (qnkhuat) [inline src/metabase/query_processor/middleware/process_userland_query.clj:98]: should we be more explicit ? how about `cache_updated_at`

Comment (piranha) [reply src/metabase/query_processor/middleware/process_userland_query.clj]: Yeah I thought about that (and also some tests just failing on that) and moved value to `cached`. 😁

File: test/metabase/query_processor/middleware/cache_test.clj (hunk 1 above)
Comment (piranha) [reply test/metabase/query_processor/middleware/cache_test.clj]: Ah, checking it now :)
