### PR TITLE
Optimize pie charts rendering with many rows

### LINKED ISSUE #48458: Investigate FE performance bug in v50
### Describe the bug

A customer just sent us a trace about a performance regression they're seeing on the native query editor
https://drive.google.com/file/d/17mb_kk4n8Wu6iB2HRDI16FXdl-FtHYQC/view?usp=sharing

### To Reproduce

NA

### Expected behavior

It should be fast

### Logs

NA

### Information about your Metabase installation

v50.x

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by kulyk**
Fixes #48458 

Optimizes pie chart rendering performance, cutting rendering time from ~3s to ~200ms for 32K rows. There're two changes:

1. [Optimized ring color selection code](https://github.com/metabase/metabase/commit/fc72d0417cd277592586baa5fdc4ed069ae5555f). We're calling `getColorForRing` for each row, and [it's making a hex color to accent color index map internally](https://github.com/metabase/metabase/blob/187e9508a9120d6609932f9f60ca51cf2d6104e0/frontend/src/metabase/visualizations/echarts/pie/util/colors.ts#L51). Building that map appeared to be expensive, so we're now building it once and then re-using for getting color indices. That reduced total chart rendering time from ~3s to ~770ms
2. [Memoized `pie.rows` viz setting calculation] (https://github.com/metabase/metabase/commit/5b73efa52fbeaf12f96e4e999ab6004431444943). It used to be recalculated ~3 times with the same `rawSeries` and `settings`. That reduced total chart rendering time from ~770ms (after the color code optimization) to ~200ms.

### Benchmarks

<details>
<summary>Before</summary>

before

</details>

<details>
<summary>After</summary>

after

</details>

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/PieChart/chart-definition.ts [hunk 1]
```diff
@@ -113,11 +113,15 @@ export const PIE_CHART_DEFINITION: VisualizationDefinition = {
...
-        );
-      },
+      getValue: _.memoize(
+        (rawSeries, settings) => {
+          return getPieRows(rawSeries, settings, (value, options) =>
+            String(formatValue(value, options)),
+          );
+        },
+        (rawSeries, settings) =>
+          JSON.stringify(rawSeries) + JSON.stringify(settings),
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/visualizations/PieChart/chart-definition.ts:123]: `rawSeries` can be a huge dataset potentially. I think we can use narrower data about the query run and reduce the number of viz settings keys as well to prevent recomputation on irrelevant settings change. Wdyt?

Comment (kulyk) [reply frontend/src/metabase/visualizations/visualizations/PieChart/chart-definition.ts]: Good call, [`f7c6845`](https://github.com/metabase/metabase/pull/48670/commits/f7c684541cff501738a09ce365bf0814b7a3a169) should address this, please take a look

File: frontend/src/metabase/visualizations/visualizations/PieChart/chart-definition.ts [hunk 2]
```diff
@@ -119,16 +127,21 @@ export const PIE_CHART_DEFINITION: VisualizationDefinition = {
             String(formatValue(value, options)),
           );
         },
-        (rawSeries, settings) =>
-          JSON.stringify(rawSeries) + JSON.stringify(settings),
+        ([{ card, data }], settings) =>
+          JSON.stringify({
+            cols: data.cols,
+            rows: data.rows.length,
+            dataset_query: card.dataset_query,
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/visualizations/PieChart/chart-definition.ts:134]: I think cols and rows length can remain the same if underlying data has 1 row modified. 
The `/api/dataset` endpoint returns `started_at` what should make it unique enough. What do you think if we combine it with the `dataset_query`?

Comment (kulyk) [reply frontend/src/metabase/visualizations/visualizations/PieChart/chart-definition.ts]: @alxnddr good call, I had to update the way we're building a series object in a few places to make sure they include `started_at` apart from `card` and `data`. Please take another look

**Review by alxnddr — APPROVED** [review]
Looks awesome 🙌
