### PR TITLE
Fix #66585: Updates static embeds to omit color-scheme settings to preserve legacy transparent iframe behavior

### LINKED ISSUE #66585: Dark mode w/ static embedding - black background instead of a transparent one
### Describe the bug

When the `#background=false` parameter is set for a static embedded resource, it will show up with a dark background instead of a transparent one when the browser's color scheme preference is set to dark.

V56, with an orange background and hash params: `background=false&bordered=false&titled=true`
Image

V57, with the same settings (different dashboard):
Image

### To Reproduce

Embed a question or dashboard, and set background to false. View the embedded resource with dark perference.

### Expected behavior

We should keep the same behavior that is present in v56.

### Logs

_No response_

### Information about your Metabase installation

```JSON
v1.57.5.3
```

### Severity

Severe - affects theming of all iframe-embedded resources with a `background=false` parameter

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bpander**
Closes https://github.com/metabase/metabase/issues/66585

### Description

Omits `<meta name="color-scheme" content="light dark" />` and `color-scheme` from static embeds to preserve legacy transparent iframe behavior.

### How to verify

1. See #66585 for original repro steps. Since static embeds are going away, you'll need to set it up on `release-x.57.x`.
2. Verify color-scheme meta tag and css property are still included in the main (non-embedded) app.
3. Verify background can be transparent when UA theme and embed theme are swapped (browser=light, embed=dark).
4. Verify background can still be made opaque via `background` hash param.
5. Verify embedded contents still looks/works okay in dark and light modes.
6. Verify iframes can still be made transparent if parent site has its own `<meta name="color-scheme" content="light dark" />` and `color-scheme` by adding `color-scheme: light` to iframe. In other words, this issue will come back so we need to be sure it can at least have a workaround: https://github.com/metabase/metabase/pull/64324

### Demo

**BEFORE**
before

**AFTER (Chrome)**
after-chrome

**AFTER (FF)**
after-ff

**AFTER (Safari)**
after-safari

**AFTER (#background=false&theme=night)**
Screenshot 2025-12-08 at 6 24 24 PM

**AFTER (#background=true&theme=night)**
Screenshot 2025-12-08 at 6 24 46 PM

**AFTER(#background=true)**
Screenshot 2025-12-08 at 6 26 38 PM

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/server/routes/index.clj [hunk 1]
```diff
@@ -103,7 +103,8 @@
      :enableGoogleAuth       (boolean google-auth-client-id)
      :enableAnonTracking     (boolean anon-tracking-enabled)
      ;; (metabase#65533) color-scheme meta tag breaks EAJS because it has a transparent background.
-     :hasColorSchemeMetaTag  (not= entrypoint-name "embed-sdk")}))
+     ;; (metabase#66585) Also omit for static embedding to preserve legacy behavior for transparent iframes.
+     :hasColorSchemeMetaTag  (not (contains? #{"embed-sdk" "embed"} entrypoint-name))}))
```
Comment (bpander) [inline src/metabase/server/routes/index.clj]: Baby's first clojurescript. Hopefully this isn't too far off the mark. Feel free to suggest edits anywhere but especially here.

**Review by alxnddr — APPROVED** [review]

**Comment by npretto** [comment]
I think this should support also public embed, I put up a small PR for that here: https://github.com/metabase/metabase/pull/66693
Could you check if it works correctly there too?
To test it, you can get the public link and use it in an iframe
