### PR TITLE
Fix object detail for PK field

### LINKED ISSUE #2780: Object detail doesn't always show up when clicking on primary key
Steps to reproduce:

Using the sample dataset, select the orders table, show `bare rows`, click on an order id.

You end up with a list of a single row. 

If you click on a FK (eg, the user id), you'll get to the object detail correctly.

This works correctly in version 0.17, so it's a regression.

If this is a bug report, please fill in the blanks:
*  I am using the _Chrome_ browser.
*  My computer's OS is OS X.
*  I'm running Metabase on AWS. 
*  My database is Postgres.
*  My Metabase version is 0.18-rc

### PR DESCRIPTION
**Pull request by camsaul**
Poor lil computer was confused because as we've all learned in school `["field-id" <id>] !== <id>`. Make sure we call `parseFieldTarget` so we can pull the ID out when comparing.

Fixes #2780

### CODE REVIEW

**Comment by camsaul** [comment]
@tlrobinson can you check this when you get a chance

File: frontend/src/metabase/lib/query_time.js [hunk 1]
```diff
@@ -163,15 +163,15 @@ export function parseFieldBucketing(field, defaultUnit = null) {
...
-            return field;
-        } else {
-            console.warn("Unknown field format", field);
-        }
+        if (field[0] === "field-id")       return field[1];
+        if (field[0] === "fk->")           return field[1];
+        if (field[0] === "datetime_field") return parseFieldTarget(field[1]);
     }
+
+    console.warn("Unknown field format", field);
```
Comment (tlrobinson) [inline frontend/src/metabase/lib/query_time.js]: I suspect this is going to cause a lot of logs for existing cards that use the legacy bare field-id format. Perhaps we should have a separate deprecation warning?

Comment (camsaul) [inline frontend/src/metabase/lib/query_time.js]: look above that on line 166. Bare ID would get returned right away

Comment (tlrobinson) [inline frontend/src/metabase/lib/query_time.js]: Oops, yeah.

**Comment by tlrobinson** [comment]
LGTM
