### PR TITLE
Bind *card-id* when executing a dashboard subscription to fix perm checks

### LINKED ISSUE #28947: "Pulse card query error" on user without native SQL permissions
**Describe the bug**
If you're a user without native sql permissions, you should be able to run SQL questions but not edit them, that works fine, but the issue happens when that user configures a subscription and sends it

**Logs**
```
:error "You do not have permissions to run this query.",
  :row_count 0,
  :running_time 0,
  :ex-data
  {:type :missing-required-permissions,
   :required-permissions #{"/db/2/native/"},
   :actual-permissions
   #{"/collection/2/"
     "/query/db/2/schema/"
     "/download/db/2/native/"
     "/data/db/2/"
     "/collection/namespace/snippets/root/"
     "/download/db/3/native/"
     "/download/db/3/"
     "/download/db/2/"
     "/collection/root/"
     "/application/subscription/"},
   :permissions-error? true},
```

**To Reproduce**
1) as an admin create a group and create a user. Assign this user to the group
2) go to permissions and assign "no self service" to all users and to the newly created group
3) create a dashboard and create a sql question ("select * from people") and add it to this dashboard
4) log in as the user with "no self service" permission, go to the dashboard and create a subscription
5) send it and you'll get
image

**Expected behavior**
A user without SQL permissions should be able to receive subscriptions of questions created in SQL, as it's able to run them when going to the metabase server

NOTE: watch out when fixing this, not to break sandboxing :) 

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Metabase version: 1.45.3...

**Severity**
P1

**Additional context**
NA

### PR DESCRIPTION
**Pull request by noahmoss**
Resolves https://github.com/metabase/metabase/issues/28947

When executing a card in a dashboard subscription, `qp.perms/*card-id*` wasn't been bound to the card's ID. This meant that the QP permission check was treating it as an ad-hoc native query rather than a saved question, and thus requiring native query perms to execute.

It's a simple fix to bind `*card-id*` before executing the query. Also added a test for this scenario which didn't exist before.

### CODE REVIEW

**Review by tsmacdonald — APPROVED** [review]
:boat:

**Comment by calherries** [comment]
Why isn't the binding of `qp.perms/*card-id*` inside the body of `qp.dashboard/run-query-for-dashcard-async`?

Is there a context where `qp.dashboard/run-query-for-dashcard-async` shouldn't have `qp.perms/*card-id*` bound to the `card-id` of the dashcard?

File: test/metabase/dashboard_subscription_test.clj [hunk 1]
```diff
@@ -628,6 +630,30 @@
...
+        (is (= [[1 "Red Medicine" 4 10.0646 -165.374 3]]
+               (-> (@#'metabase.pulse/execute-dashboard {:creator_id (mt/user->id :rasta)} dashboard)
+                   first
+                   :result
+                   :data
+                   :rows))))
+      (finally
+        (perms/update-data-perms-graph! (assoc-in (perms/data-perms-graph)
+                                                  [:groups (u/the-id (perms-group/all-users)) (mt/id) :data :native]
+                                                  :write))))))
```
Comment (qnkhuat) [inline test/metabase/dashboard_subscription_test.clj:655]: nit: instead of assuming the original perm is `:write` how about we select the `original-perms` and use it here?

**Review by qnkhuat — APPROVED** [review]
LGTM, have a suggestion to avoid implicit assumption in the test but should not be a blocker.

**Comment by noahmoss** [comment]
@calherries Good point. It actually seems that `*card-id*` is already being bound within ` metabase.query-processor.card/run-query-for-card-async` but it's done within the default `run` function which can be overridden by the caller. That's the actual reason it wasn't being done properly for pulses. I'll fix that function to bind it regardless of whether it uses the default `run` function or a custom one.

**Review by calherries — APPROVED** [review]
Looks good now, thanks

**Comment by noahmoss** [comment]
This also closes https://github.com/metabase/metabase/issues/18009
