### PR TITLE
Fix bug in chart column settings back behavior

### LINKED ISSUE #11775: Gauge option not editable (33.7.3 and 34.1)
**Describe the bug**
Impossible to adjust options of a Gauge (egs : color and scale)

**Logs**

```
Warning: can't clean query without metadata! 2 app-main.bundle.js:5:40881
TypeError: t is null
app-main.bundle.js:5:2068276
    value https://********/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    value https://********/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    value self-hosted:871
    c https://********/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
Error: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 3 vendor.bundle.js:1:285932
    exports https://********/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    exports https://********/app/dist/vendor.bundle.js?8902e0cb00fa4456f7bb:1
    value https://********/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
    _updateSize https://********/app/dist/app-main.bundle.js?8902e0cb00fa4456f7bb:5
```

**To Reproduce**
Check gif.

**Expected behavior**
I should be allowed to edit scale, colors and other gauge options.

**Screenshots**
bug-gauge

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.15.18-4-pve",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "date": "2020-01-13",
      "tag": "v0.34.1",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Severity**
It's really annoying, sometime blocking as gauge is no more meaningfull.

**Additional context**
-

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #11775

## Fix

This PR updates how nested columns settings override the back behavior of the settings sidebar. Previously, the back behavior was always set to unselect the current column. This was ineffective if there was only one column because it was immediately reselected. Now, we unset the current _section_ if there's just one column.

Another issue, was for settings with just one section. There resetting the current section wouldn't do anything, so we leave the standard back behavior of returning to the visualization types.

### Table

table

### Gauge

gauge

### Number

number

@mazameli this one seems a bit weird to me. What do you think about not overriding title with the column name in this case?

## Design

It feels wrong that the nested settings are aware of all this external context. It seemed like the alternative was to spread the behavior across multiple components so I left it this way.

### CODE REVIEW

**Comment by mazameli** [comment]
Tables look right, but Gauge and Number both look wrong to me in the Gifs. 

Like you suggested, Number charts should say "Number options" to follow the current pattern of all the other visualization settings.

Gauges shouldn't have the tabs disappear when clicking on the "Formatting tab." Instead, the Formatting tab should be highlighted, and there is no need for a back button other than the existing one that says "< Gauge settings," which takes you back to visualization selection. It should be transparent to the user that this is technically showing the "column settings" for the single cell result that's being visualized.

File: frontend/src/metabase/visualizations/components/settings/ChartNestedSettingColumns.jsx [hunk 1]
```diff
@@ -38,15 +38,30 @@ class ColumnWidgets extends React.Component {
...
     } = this.props;
 
+    // These two props (title and onBack) are overridden to display a column
+    // name instead of the visualization type when viewing a column's settings.
     if (setSidebarPropsOverride) {
-      setSidebarPropsOverride({
-        title: displayNameForColumn(object),
-        onBack: () => onChangeEditingObject(),
-      });
+      const overrides = { title: displayNameForColumn(object) };
```
Comment (tlrobinson) [inline frontend/src/metabase/visualizations/components/settings/ChartNestedSettingColumns.jsx]: I think your suggestion to change the title based on whether there are multiple objects or sections makes sense.

**Review by tlrobinson — CHANGES_REQUESTED** [review]

**Comment by paulrosenzweig** [comment]
New gifs:

### Table (same)

table


### Gauge

gauge


### Number

number

**Comment by mazameli** [comment]
New gifs look good to me! 👍

**Review by tlrobinson — APPROVED** [review]
