### PR TITLE
Prevent greeting refresh on the homepage

### LINKED ISSUE #11952: Adding dashboard on home screen updates Greeting text on every input
**Describe the bug**
When on homepage and clicking :heavy_plus_sign: to add a new dashboard, the greetings text updates on every input in the new dashboard modal.

**To Reproduce**
1. Go to home page
2. Click :heavy_plus_sign: top-right and "New dashboard"
3. Change input focus or start typing, notice the greetings text changes constantly

**Information about your Metabase Installation:**
Metabase 0.34.2 and `master`

**Additional context**
https://discourse.metabase.com/t/home-page-greetings-text/9095

### PR DESCRIPTION
**Pull request by kdoh**
Fixes #11952

We had been calling `Greeting.sayHello` in the render method of the homepage itself, meaning every time the props change we'd get a new greeting. This moves that method call to a selector so it should only be run once.

### CODE REVIEW

File: frontend/src/metabase/containers/Overworld.jsx [hunk 1]
```diff
@@ -61,6 +61,11 @@ const getParitionedCollections = createSelector(
   },
 );
 
+const getGreeting = createSelector(
+  [getUser],
```
Comment (tsmacdonald) [inline frontend/src/metabase/containers/Overworld.jsx:65]: Per [the docs](https://github.com/reduxjs/reselect#createselectorinputselectors--inputselectors-resultfunc), looks like making it an array isn't necessary

**Review by tsmacdonald — APPROVED** [review]
TIL about `reselect`, so that was good

**Review by paulrosenzweig — APPROVED** [review]
Works for me!

Total nitpick that's not worth addressing: 
IMO it's a bit weird to use `createSelector` just to get its memoization. I think using `_.memoize` would be more obvious to future readers. Using reselect definitely gets the job done though!
