### PR TITLE
Fix notebook being unable to resize

### LINKED ISSUE #33982: Can't use drag bar between editor and result pane while editing a model
**Describe the bug**
The draggable bar between the query editor and the result pane can't be dragged while editing the query definition of any notebook editor based model.

**Logs**
```
DraggableCore.js:158 Uncaught Error: <DraggableCore> not mounted on DragStart!
    at u.handleDragStart (DraggableCore.js:158:15)
    at DraggableCore.js:305:20
    at Object.c (react-dom.production.min.js:14:84)
    at f (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at m (react-dom.production.min.js:15:72)
    at ct (react-dom.production.min.js:52:170)
    at at (react-dom.production.min.js:51:255)
    at lt (react-dom.production.min.js:52:334)
    at At (react-dom.production.min.js:56:10)
```    
**To Reproduce**
1. Create a notebook editor based model, or open an existing one to edit its query definition.
2. Try to use the draggable bar between the editor and the results pane.
3. When clicked, the bar continues to be greyed out and doesn't work.

**Expected behavior**
The draggable bar should be enabled and resizing the panes should be possible.

**Screenshots**
https://github.com/metabase/metabase/assets/11080638/742ae267-fec1-4687-bcc8-012f68564883

**Severity**
Probably minor. Reported by some users.

**Additional context**
The same works while editing a model based on native query.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.186-179.751.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-07",
      "tag": "v1.47.1",
      "branch": "release-x.47.x",
      "hash": "bd278b9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### LINKED ISSUE #39628: Can't enlarge preview section while creating a model
### Describe the bug

This handle is not draggable
Captura de ecrã 2024-03-05, às 10 50 45

### To Reproduce

1. Click on + New model
2. Click on Use the notebook editor
3. Pick whatever data or build any query or just do nothing
4. In the bottom there is a preview section which has a handle implying you can drag it to enlarge this section, but this doesn't actually work

### Expected behavior

You should be able to adjust the height of the section by dragging the handle

### Logs

_No response_

### Information about your Metabase installation

```JSON
last version
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nemanjaglumac**
Fixes #33982 
Fixes #39628

### Description

Upgrading the `react-resizable` library in #29414 broke the ability to resize Notebook in "Editing model query" view. This was reported in #33982.

We jumped from v1 to v3 of this library. There was a breaking change that hasn't been addressed originally.
https://github.com/react-grid-layout/react-resizable/blob/master/CHANGELOG.md#breaking

The handle now needs an explicit ref. Failing to attach the ref results in an error 
```
<DraggableCore> not mounted on DragStart!
```

Apart from fixing this problem, this PR also removes the styled components and uses Mantine instead.

### How to verify
Follow the reproduction steps from the original issue.

### Demo
Kapture 2024-03-14 at 18 54 04

### Checklist
- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx [hunk 1]
```diff
@@ -30,9 +67,9 @@ function ResizableNotebook({
         onResizeStop(...args);
       }}
     >
-      <NotebookContainer isResizing={isResizing}>
+      <Box w="100%" style={{ overflowY: getOverflow(isResizing) }}>
```
Comment (nemanjaglumac) [inline frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx:70]: I intentionally didn't re-create a component called `NotebookContainer` because we already have in at least one other place.

File: frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx [hunk 2]
```diff
@@ -1,18 +1,55 @@
...
+ * @link Demo: https://github.com/metabase/metabase/pull/19103#issuecomment-981935878
+ */
+const getOverflow = isResizing => (isResizing ? "hidden" : "scroll");
+
+const Handle = forwardRef((props, ref) => (
+  <Flex
+    align="center"
+    justify="center"
+    w="100%"
+    h="8px"
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx:31]: we prefer `rem` to `px`

File: frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx [hunk 3]
```diff
@@ -1,18 +1,55 @@
...
+    style={{
+      cursor: "row-resize",
+    }}
+    ref={ref}
+    {...props}
+  >
+    <Box
+      w="100px"
+      h="5px"
+      bg={darken(color("border"), 0.03)}
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx:43]: `darken` accepts the color name as well

File: frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx [hunk 4]
```diff
@@ -1,18 +1,55 @@
...
+/**
+ * Prevents automatic scroll effect on queries with lots of steps.
+ * When overflow is 'scroll' and the notebook is being resized,
+ * its height changes and it scrolls automatically.
+ * Setting the overflow to "hidden" while resizing fixes that behavior.
+ * @link Demo: https://github.com/metabase/metabase/pull/19103#issuecomment-981935878
+ */
+const getOverflow = isResizing => (isResizing ? "hidden" : "scroll");
+
+const Handle = forwardRef((props, ref) => (
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx:26]: please pass a function like:
```
const Handle = forwardRef(function Handle(props, ref) {
```

to fix the displayName

File: frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx [hunk 5]
```diff
@@ -1,18 +1,55 @@
...
+      h="5px"
+      bg={darken(color("border"), 0.03)}
+      style={{
+        borderRadius: "4px",
+      }}
+    ></Box>
+  </Flex>
+));
+
+Handle.displayName = "Handle";
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx:51]: Please pass a function and remove this

**Review by ranquild — APPROVED** [review]
Small comments

File: frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx (hunk 3 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/ResizableNotebook.jsx]: TIL
