### PR TITLE
Fix BigQuery Percentile and Median expressions not using correct backtick quoting

### LINKED ISSUE #17856: BigQuery Custom Expression function `Percentile` and `Median` not using correct backtick quoting
**Describe the bug**
While BigQuery never had Percentile and Median listed as supported Custom Expression functions, they worked, when using it after an aggregation, but did not work on direct field references because of missing backtick quoting.
And the new driver now supports all expressions, then the limitations should be removed.

https://www.metabase.com/docs/latest/users-guide/expressions.html#database-limitations
Historic reference #12675

**To Reproduce**
1. Custom question > **BigQuery** Sample Dataset > Orders
2. Summarize Custom Expression `Percentile([Quantity], 0.5)` as "CE"
image
3. Visualize - fails query because of missing backticks
`` SELECT APPROX_QUANTILES(metabase-bigquery-driver.v6_sample_dataset.orders.quantity, 10)[OFFSET(5)] AS `CE` FROM `metabase-bigquery-driver.v6_sample_dataset.orders` ``

<details><summary>Full stacktrace</summary>

```
2021-09-13 14:50:29,410 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 43,
 :started_at #t "2021-09-13T14:50:27.528052+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class com.google.cloud.bigquery.BigQueryException,
   :error "Unrecognized name: metabase at [2:25]",
   :stacktrace
   ["com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)"
    "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:628)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1348)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1343)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
    "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
    "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
    "com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1342)"
    "com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1326)"
    "com.google.cloud.bigquery.Job$1.call(Job.java:334)"
    "com.google.cloud.bigquery.Job$1.call(Job.java:331)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
    "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
    "com.google.cloud.RetryHelper.poll(RetryHelper.java:64)"
    "com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:330)"
    "com.google.cloud.bigquery.Job.getQueryResults(Job.java:291)"
    "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1242)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:194)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:182)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:202)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:200)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__70079.invoke(bigquery_cloud_sdk.clj:253)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:255)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:248)"
    "driver.bigquery_cloud_sdk$fn__70084.invokeStatic(bigquery_cloud_sdk.clj:275)"
    "driver.bigquery_cloud_sdk$fn__70084.invoke(bigquery_cloud_sdk.clj:266)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__48991.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__49480.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__47388.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__49854.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__50845.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__50889.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49050.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39180.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__43611.invoke(annotate.clj:615)"
    "query_processor.middleware.permissions$check_query_permissions$fn__45543.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__50029.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45941.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__45879.invoke(visualization_settings.clj:57)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__46986.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__50615.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__50151.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47005.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__50203.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46377.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__45852.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__39080.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45186.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__49405.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__49703.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47373.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__46754.invoke(add_source_metadata.clj:123)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__49953.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48297.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45167.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__47975.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45240.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__51273.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__47754.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50218.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49714$fn__49718.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49714.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45790.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__45978$fn__45979.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__45978.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50001.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50008.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47703.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48976.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__47721.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__49989.invoke(process_userland_query.clj:134)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__50298.invoke(catch_exceptions.clj:168)"
    "query_processor.reducible$async_qp$qp_STAR___42431$thunk__42432.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___42431.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___42440$fn__42443.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___42440.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
    "query_processor$fn__51321$process_query_and_save_execution_BANG___51330$fn__51333.invoke(query_processor.clj:253)"
    "query_processor$fn__51321$process_query_and_save_execution_BANG___51330.invoke(query_processor.clj:245)"
    "query_processor$fn__51365$process_query_and_save_with_max_results_constraints_BANG___51374$fn__51377.invoke(query_processor.clj:265)"
    "query_processor$fn__51365$process_query_and_save_with_max_results_constraints_BANG___51374.invoke(query_processor.clj:258)"
    "api.dataset$run_query_async$fn__57364.invoke(dataset.clj:63)"
    "query_processor.streaming$streaming_response_STAR_$fn__37989$fn__37990.invoke(streaming.clj:140)"
    "query_processor.streaming$streaming_response_STAR_$fn__37989.invoke(streaming.clj:139)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$fn__25206.invoke(streaming_response.clj:84)"]}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query",
   :stacktrace
   ["--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:196)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:182)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:202)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:200)"
    "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__70079.invoke(bigquery_cloud_sdk.clj:253)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:255)"
    "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:248)"
    "driver.bigquery_cloud_sdk$fn__70084.invokeStatic(bigquery_cloud_sdk.clj:275)"
    "driver.bigquery_cloud_sdk$fn__70084.invoke(bigquery_cloud_sdk.clj:266)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
    "query_processor.context.default$default_runf.invoke(default.clj:66)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__48991.invoke(mbql_to_native.clj:25)"
    "query_processor.middleware.check_features$check_features$fn__49480.invoke(check_features.clj:39)"
    "query_processor.middleware.limit$limit$fn__47388.invoke(limit.clj:37)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__49854.invoke(cache.clj:204)"
    "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__50845.invoke(optimize_temporal_filters.clj:204)"
    "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__50889.invoke(validate_temporal_bucketing.clj:50)"
    "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49050.invoke(auto_parse_filter_values.clj:43)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39180.invoke(wrap_value_literals.clj:161)"
    "query_processor.middleware.annotate$add_column_info$fn__43611.invoke(annotate.clj:615)"
    "query_processor.middleware.permissions$check_query_permissions$fn__45543.invoke(permissions.clj:108)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__50029.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45941.invoke(cumulative_aggregations.clj:60)"
    "query_processor.middleware.visualization_settings$update_viz_settings$fn__45879.invoke(visualization_settings.clj:57)"
    "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__46986.invoke(resolve_joined_fields.clj:102)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__50615.invoke(resolve_joins.clj:171)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__50151.invoke(add_implicit_joins.clj:190)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__47005.invoke(large_int_id.clj:59)"
    "query_processor.middleware.format_rows$format_rows$fn__50203.invoke(format_rows.clj:74)"
    "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46377.invoke(add_default_temporal_unit.clj:23)"
    "query_processor.middleware.desugar$desugar$fn__45852.invoke(desugar.clj:21)"
    "query_processor.middleware.binning$update_binning_strategy$fn__39080.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__45186.invoke(resolve_fields.clj:34)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__49405.invoke(add_dimension_projections.clj:314)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__49703.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47373.invoke(upgrade_field_literals.clj:40)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__46754.invoke(add_source_metadata.clj:123)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__49953.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48297.invoke(auto_bucket_datetimes.clj:147)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45167.invoke(resolve_source_table.clj:45)"
    "query_processor.middleware.parameters$substitute_parameters$fn__47975.invoke(parameters.clj:111)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45240.invoke(resolve_referenced.clj:79)"
    "query_processor.middleware.expand_macros$expand_macros$fn__51273.invoke(expand_macros.clj:184)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__47754.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50218.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49714$fn__49718.invoke(resolve_database_and_driver.clj:31)"
    "driver$do_with_driver.invokeStatic(driver.clj:60)"
    "driver$do_with_driver.invoke(driver.clj:56)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49714.invoke(resolve_database_and_driver.clj:25)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45790.invoke(fetch_source_query.clj:274)"
    "query_processor.middleware.store$initialize_store$fn__45978$fn__45979.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__45978.invoke(store.clj:10)"
    "query_processor.middleware.validate$validate_query$fn__50001.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__50008.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47703.invoke(add_rows_truncated.clj:35)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48976.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__47721.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__49989.invoke(process_userland_query.clj:134)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__50298.invoke(catch_exceptions.clj:168)"
    "query_processor.reducible$async_qp$qp_STAR___42431$thunk__42432.invoke(reducible.clj:103)"
    "query_processor.reducible$async_qp$qp_STAR___42431.invoke(reducible.clj:109)"
    "query_processor.reducible$sync_qp$qp_STAR___42440$fn__42443.invoke(reducible.clj:135)"
    "query_processor.reducible$sync_qp$qp_STAR___42440.invoke(reducible.clj:134)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
    "query_processor$fn__51321$process_query_and_save_execution_BANG___51330$fn__51333.invoke(query_processor.clj:253)"
    "query_processor$fn__51321$process_query_and_save_execution_BANG___51330.invoke(query_processor.clj:245)"
    "query_processor$fn__51365$process_query_and_save_with_max_results_constraints_BANG___51374$fn__51377.invoke(query_processor.clj:265)"
    "query_processor$fn__51365$process_query_and_save_with_max_results_constraints_BANG___51374.invoke(query_processor.clj:258)"
    "api.dataset$run_query_async$fn__57364.invoke(dataset.clj:63)"
    "query_processor.streaming$streaming_response_STAR_$fn__37989$fn__37990.invoke(streaming.clj:140)"
    "query_processor.streaming$streaming_response_STAR_$fn__37989.invoke(streaming.clj:139)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$fn__25206.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: 99e9605e0824830508aa9b9afbe76711fb34c504dac4e655339e4cff25805ba8\nSELECT APPROX_QUANTILES(metabase-bigquery-driver.v6_sample_dataset.orders.quantity, 10)[OFFSET(5)] AS `CE` FROM `metabase-bigquery-driver.v6_sample_dataset.orders`",
    :parameters nil}}],
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :query
  {:source-table 6174,
   :aggregation [["aggregation-options" ["percentile" ["field" 35252 nil] 0.5] {:name "CE", :display-name "CE"}]]},
  :database 43,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT APPROX_QUANTILES(metabase-bigquery-driver.v6_sample_dataset.orders.quantity, 10)[OFFSET(5)] AS `CE` FROM `metabase-bigquery-driver.v6_sample_dataset.orders`",
  :params nil,
  :table-name "orders",
  :mbql? true},
 :status :failed,
 :class com.google.api.client.googleapis.json.GoogleJsonResponseException,
 :stacktrace
 ["com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)"
  "com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)"
  "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:626)"
  "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1348)"
  "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1343)"
  "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
  "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
  "com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)"
  "com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1342)"
  "com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1326)"
  "com.google.cloud.bigquery.Job$1.call(Job.java:334)"
  "com.google.cloud.bigquery.Job$1.call(Job.java:331)"
  "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)"
  "com.google.cloud.RetryHelper.run(RetryHelper.java:76)"
  "com.google.cloud.RetryHelper.poll(RetryHelper.java:64)"
  "com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:330)"
  "com.google.cloud.bigquery.Job.getQueryResults(Job.java:291)"
  "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1242)"
  "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:194)"
  "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:182)"
  "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:202)"
  "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:200)"
  "driver.bigquery_cloud_sdk$process_native_STAR_$thunk__70079.invoke(bigquery_cloud_sdk.clj:253)"
  "driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:255)"
  "driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:248)"
  "driver.bigquery_cloud_sdk$fn__70084.invokeStatic(bigquery_cloud_sdk.clj:275)"
  "driver.bigquery_cloud_sdk$fn__70084.invoke(bigquery_cloud_sdk.clj:266)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__48991.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__49480.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__47388.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__49854.invoke(cache.clj:204)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__50845.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__50889.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49050.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39180.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__43611.invoke(annotate.clj:615)"
  "query_processor.middleware.permissions$check_query_permissions$fn__45543.invoke(permissions.clj:108)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__50029.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45941.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.visualization_settings$update_viz_settings$fn__45879.invoke(visualization_settings.clj:57)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__46986.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__50615.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__50151.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47005.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__50203.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46377.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__45852.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__39080.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__45186.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__49405.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__49703.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47373.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__46754.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__49953.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48297.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45167.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__47975.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45240.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__51273.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__47754.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50218.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49714$fn__49718.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49714.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45790.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__45978$fn__45979.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__45978.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50001.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__50008.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47703.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48976.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__47721.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__49989.invoke(process_userland_query.clj:134)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__50298.invoke(catch_exceptions.clj:168)"
  "query_processor.reducible$async_qp$qp_STAR___42431$thunk__42432.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___42431.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___42440$fn__42443.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___42440.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
  "query_processor$fn__51321$process_query_and_save_execution_BANG___51330$fn__51333.invoke(query_processor.clj:253)"
  "query_processor$fn__51321$process_query_and_save_execution_BANG___51330.invoke(query_processor.clj:245)"
  "query_processor$fn__51365$process_query_and_save_with_max_results_constraints_BANG___51374$fn__51377.invoke(query_processor.clj:265)"
  "query_processor$fn__51365$process_query_and_save_with_max_results_constraints_BANG___51374.invoke(query_processor.clj:258)"
  "api.dataset$run_query_async$fn__57364.invoke(dataset.clj:63)"
  "query_processor.streaming$streaming_response_STAR_$fn__37989$fn__37990.invoke(streaming.clj:140)"
  "query_processor.streaming$streaming_response_STAR_$fn__37989.invoke(streaming.clj:139)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__25206.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error
 "400 Bad Request\nGET https://www.googleapis.com/bigquery/v2/projects/metabase-bigquery-driver/queries/d364a0da-e7ad-4ac9-ab27-2599d12a5075?location=US&maxResults=0&prettyPrint=false\n{\n  \"code\" : 400,\n  \"errors\" : [ {\n    \"domain\" : \"global\",\n    \"location\" : \"q\",\n    \"locationType\" : \"parameter\",\n    \"message\" : \"Unrecognized name: metabase at [2:25]\",\n    \"reason\" : \"invalidQuery\"\n  } ],\n  \"message\" : \"Unrecognized name: metabase at [2:25]\",\n  \"status\" : \"INVALID_ARGUMENT\"\n}",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-table 6174,
   :aggregation [[:aggregation-options [:percentile [:field 35252 nil] 0.5] {:name "CE", :display-name "CE"}]]},
  :database 43,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash
   [-103, -23, 96, 94, 8, 36, -125, 5, 8, -86, -101, -102, -5, -25, 103, 17, -5, 52, -59, 4, -38, -60, -26, 85, 51,
    -98, 76, -1, 37, -128, 91, -88]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

2021-09-13 14:50:29,432 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.9 s (8 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (60 total active threads) Queries in flight: 1 (0 queued)
```

</details>

**Expected behavior**
- Fix backtick problem
- Remove driver limitations, so functions will be displayed correctly in the GUI.
- Update docs limitations. Should probably be removed, and then add BigQuery together with the Presto additional note.

**Information about your Metabase Installation:**
Tested 0.39.2 thru 0.40.4, and master with new driver

----

**Possible workaround**
This is a hack, which will eventually stop working (#14775).
1. Summarize by Count grouped by some field
2. Create another summarize with Custom Expression like so `Percentile([Count], 0.5)`
image
3. Now remove the first summarize section (**notice** the duplicate Filter and Join buttons and other incorrect buttons) and edit the Custom Expression to reference the correct column - example `Percentile([Quantity], 0.5)`
image
4. Visualize - will work, because it's actually doing a sub-select, so it is referencing a field from the nested query
<details><summary>Generated SQL</summary>

```
SELECT APPROX_QUANTILES(source.quantity, 10)[OFFSET(5)] AS `percentile`
FROM (SELECT `v6_sample_dataset.orders`.`id` AS `id`, `v6_sample_dataset.orders`.`user_id` AS `user_id`, `v6_sample_dataset.orders`.`product_id` AS `product_id`, `v6_sample_dataset.orders`.`subtotal` AS `subtotal`, `v6_sample_dataset.orders`.`tax` AS `tax`, `v6_sample_dataset.orders`.`total` AS `total`, `v6_sample_dataset.orders`.`discount` AS `discount`, `v6_sample_dataset.orders`.`created_at` AS `created_at`, `v6_sample_dataset.orders`.`quantity` AS `quantity` FROM `v6_sample_dataset.orders`) `source`
```

</details>

### PR DESCRIPTION
**Pull request by jeff303**
Ensure the identifier components are quoted within the `:percentile` hsql (raw) form

Add test to ensure query is created properly

Mark `:percentile-aggregations` as being supported in the new driver

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj [hunk 1]
```diff
@@ -419,7 +419,9 @@
   [driver [_ arg p]]
   (let [[offset quantiles] (percentile->quantile p)]
     (hsql/raw (format "APPROX_QUANTILES(%s, %s)[OFFSET(%s)]"
-                      (hformat/to-sql (sql.qp/->honeysql driver arg))
+                      (-> (sql.qp/->honeysql driver arg)
+                          (hformat/format :quoting (sql.qp/quote-style driver))
+                          first)
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:424]: The right way to do this would be to have this function return a reified `ToSql`, here's an example: https://github.com/metabase/metabase/blob/d2433696380fb43bb2ffaf5e1b2aabebd1354bc2/src/metabase/driver/postgres.clj#L186-L197

We don't need to use `hsql/raw` here. In the impl of `to-sql` then we can recursively apply `to-sql` to its args

**Review by camsaul — CHANGES_REQUESTED** [review]
The right way to fix this is to `reify` `ToSql`... calling HoneySQL `format` isn't something that should be done as part of _HoneySQL_ generation itself.

Query compilation is basically

1.  MBQL transformations in QP middleware
2. Compile MBQL to HoneySQL map in SQL QP & driver methods
3. Compile HoneySQL map to SQL string -- mostly done in HoneySQL itself but done in a custom manner for a few reified `ToSQL` types and ` hformat/fn-handler` method impls

Using `hsql/raw` and HoneySQL `format` in step 2 is doing things prematurely and muddying up the distinction between the two steps... the HoneySQL->SQL compilation should happen all at once in step 3

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj (hunk 1 above)
Comment (jeff303) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj]: Made the change.

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj [hunk 2]
```diff
@@ -415,13 +416,25 @@
...
 
+(defn- approx-quantiles
+  "HoneySQL form for the APPROX_QUANTILES invocation. The [OFFSET(...)] part after the function call is odd and
+  needs special treatment."
+  [expr offset quantiles]
+  (reify
+    hformat/ToSql
+    (to-sql [_]
+      (format "APPROX_QUANTILES(%s, %s)[OFFSET(%s)]"
+        (hformat/to-sql (sql.qp/->honeysql :bigquery-cloud-sdk expr))
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:427]: `->honeysql` should probably happen inside `approx-quantities` itself. `approx-quantities` is part of the "generate HoneySQL" stage, so we should do all the HoneySQL generation there. Then we can just call `to-sql` on the generated HoneySQL.

Also, this is a small nitpick, but it would be better to make `driver` an explicit parameter rather than hardcoding `:bigquery-cloud-sdk`. The reason is that if we ever create a new driver derived from `:bigquery-cloud-sdk` then it would potentially not be using the correct method implementation for `->honeysql`.

**Review by camsaul — APPROVED** [review]
A few minor notes but other than that LGTM

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj (hunk 2 above)
Comment (jeff303) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj]: Fixed in the latest commit.
