### PR TITLE
fix: custom brand color not consistently applied on Enterprise UI elements

### LINKED ISSUE #62516: Custom brand color not consistently applied on Enterprise UI elements
### Describe the bug

Custom brand color configured in Metabase Enterprise is inconsistently applied to some UI elements, resulting in visual inconsistencies.

Image

Image

Image

Image

### To Reproduce

1. Configure custom brand color in Enterprise settings with `{"brand": "#0CAD9A"}`
2. Navigate through different UI sections (login, homepage, databases)
3. Observe mixed color usage across elements

### Expected behavior

All relevant UI elements should consistently apply the configured brand color (#0CAD9A) and have consistent hover backgrounds, especially primary interactive elements, buttons, and branding components.

### Logs

Not applicable

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "metabase-info": {
    "version": {
      "date": "2025-08-15",
      "tag": "v1.56.2.3",
      "hash": "5642e77"
    },
  },
}
```

### Severity

Annoying, especially the Customize button on the home page and focus ring on some inputs - affects brand consistency and professional appearance in enterprise deployments, but doesn't block functionality.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by undrfined**
closes #62516
Closes [UXW-566: Custom brand color not consistently applied on Enterprise UI elements](https://linear.app/metabase/issue/UXW-566/custom-brand-color-not-consistently-applied-on-enterprise-ui-elements)

### Description

Some components were transforming brand colors in weird ways and/or using deprecated components. Replace with new ones and correct colors.

This also [updates the color of the `:hover` for `subtle` buttons](https://metaboat.slack.com/archives/C096M2BBGHH/p1768995902829679?thread_ts=1768950486.198809&cid=C096M2BBGHH)

### Demo

- `DownloadsStatusSmall`
image

- Login form

image

- Databases list
image

- Greeting page (The original issue listed the x-ray icons as well, however I think that's intended that they are of different color?)
image
 
### Checklist

- [ ] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx [hunk 1]
```diff
@@ -42,33 +35,63 @@ export const HomeLayout = ({ children }: HomeLayoutProps): ReactNode => {
...
+          </Button>
         </Tooltip>
       )}
-      <LayoutBody>{children}</LayoutBody>
+      <Box
+        pos="relative"
+        mt={{
+          base: "2.5rem",
+          md: "4rem",
+          ml: "6rem",
```
Comment (bpander) [inline frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx]: Typo maybe? I don't think `ml` is a breakpoint. Is this supposed to be `lg` maybe?

File: frontend/src/metabase/auth/components/LoginForm/LoginForm.tsx [hunk 2]
```diff
@@ -56,26 +60,35 @@ export const LoginForm = ({
...
+        <FormTextInput
           name="username"
-          title={
+          label={
             isLdapEnabled ? t`Username or email address` : t`Email address`
           }
           type={isLdapEnabled ? "input" : "email"}
           placeholder="nicetoseeyou@email.com"
           autoFocus
+          size="lg"
```
Comment (bpander) [inline frontend/src/metabase/auth/components/LoginForm/LoginForm.tsx]: Was it intentional making the inputs `lg` but the submit button `sm`? On master, the inputs and submit button are the same size (they're all pretty medium-y). Might just be me, but it feels off to me with the inputs so much bigger than the submit button.

Screenshot 2026-01-22 at 3 18 33 PM

**Review by bpander — COMMENTED** [review]
Looks good! Love it when a PR fixes a bunch of issues _and_ removes a bunch of legacy code. Just had a couple minor nitpicks.

File: frontend/src/metabase/auth/components/LoginForm/LoginForm.tsx (hunk 2 above)
Comment (undrfined) [reply frontend/src/metabase/auth/components/LoginForm/LoginForm.tsx]: image

Agree that it looks better when it's the same size, changed now!

Comment (bpander) [reply frontend/src/metabase/auth/components/LoginForm/LoginForm.tsx]: I think we should remove `size="sm"` from `FormSubmitButton` too in LoginForm.tsx. That way they'll all be the same height.

Comment (undrfined) [reply frontend/src/metabase/auth/components/LoginForm/LoginForm.tsx]: oh right 🤦  done now!

image

**Review by bpander — APPROVED** [review]
