### PR TITLE
fix: add correct valueFormat for DateInput (GIT-8486, #65480)

### LINKED ISSUE #65480: Datepicker filters do not consider the browser language settings correctly
### Describe the bug

If I use Datepicker filters with a Browser that has german as a language, metabase uses still the english dateformat.  

### To Reproduce

1. change the language of your browser to german (here for edge)

Image

2. Open the e-comerce insights dashboards (sample dashoboard of metabase)
3. click on the date picker
4. change to the "concrete date range"
5. the date of the daterange is shown in an "english" manner (month date, year)Image

### Expected behavior

1.-4. see above
5. the date of the daterange is shown in an "german / european" manner (date month year)

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "de",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:144.0) Gecko/20100101 Firefox/144.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "sqlserver"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-09-10",
      "tag": "v0.56.5",
      "hash": "3dab72a"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.2 (Debian 17.2-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "5.14.0-570.58.1.el9_6.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  }
}
```

### Severity

very annoying (but not blocking)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by egorgrushin**
Closes https://github.com/metabase/metabase/issues/65480 and https://linear.app/metabase/issue/GIT-8473/dont-show-dashboards-that-contain-no-questions-in-data-picker

### Description
DateInput props valueFormat wasn't set. Set it to LL that respects dayjs localizedFormat (dayjs/plugin/localizedFormat).

The original bug states that in German language there is a wrong order: `month day year`. It should be `day month year`

### How to verify
See original issue

### Demo
Before:

https://github.com/user-attachments/assets/7310205c-83c2-4880-965a-418c1d26655d

After:

https://github.com/user-attachments/assets/3cc16280-2ecd-438a-ab01-feb36af38f11

### CODE REVIEW

**Comment by uladzimirdev** [comment]
@egorgrushin you can mention only linear by linear ticket number, link will be updated automatically. also linear automatically closes related github issue

**Comment by uladzimirdev** [comment]
so is O**k**tober a result of a date localization?

File: frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx [hunk 1]
```diff
@@ -85,6 +85,7 @@ export function DateRangePickerBody({
         <DateInput
           className={S.FlexDateInput}
           value={startDate}
+          valueFormat="LL"
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx]: We should probably do this for all `DateInput`s. Maybe a default prop in `DateInput.config.tsx`?

Comment (kamilmielnik) [inline frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx]: Can we add an e2e test for it? Not sure if [this](https://github.com/metabase/metabase/blob/33f9a3148d7fdda4ca2e8928c0514b7767741433/e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts#L23-L31) could do the trick.

File: frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx [hunk 2]
```diff
@@ -93,6 +94,7 @@ export function DateRangePickerBody({
         <DateInput
           className={S.FlexDateInput}
           value={endDate}
+          valueFormat="LL"
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx]: Now dates are not formatted consistently.
I suggest to ask the Querying team whether this is acceptable.
Maybe also ask for review from them.

image

**Comment by egorgrushin** [comment]
> so is O**k**tober a result of a date localization?

The original bug about German language. It's not about the word "Oktober" it's about the correct order: day month year (instead of month day year)

File: frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx (hunk 1 above)
Comment (egorgrushin) [reply frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx]: Do we need to test behavior of external libraries? I mean, testing that date will be formatted as dayjs tells how to format is just about testing that Mantines respects dayjs

Comment (chodorowicz) [reply frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx]: Some context why doing sweeping changes might not be that easy. The attempt to allow setting arbitrary format app-wide turned out to be more difficult than it seemed: https://linear.app/metabase/issue/UXW-1771/support-arbitrary-date-formats (hopefully will still happen soon). cc @egorgrushin

Comment (kamilmielnik) [reply frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx]: We need to prevent regressions

Comment (egorgrushin) [reply frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx]: Added e2e tests

File: e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts:1]: We keep e2e tests in large few-thousand-LOC files because there's a performance penalty when running a spec.
Please add this test in an existing file instead, e.g. `dashboard-filters-reproductions.cy.spec.js`.

File: e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+  },
+];
+
+const selectLocale = (localeName: string) => {
+  cy.visit("/account/profile");
+  cy.findByTestId("user-locale-select").findByRole("textbox").click();
+  H.popover().within(() => cy.findByText(localeName).click());
+
+  cy.get("[type=submit]").click();
+};
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts]: 1. The issue was reported to be browser-locale-specific, not Metabase-instance-specific, so this should not be a part of the test.
2. FYI this can be accomplished with an API call, no need to go through the UI and call expensive `cy.visit`.

File: e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+      cy.signInAsAdmin();
+    });
+
+    localesAndExpected.forEach(({ localeName, expectedDateRange }) => {
+      it(`shows LL-formatted values for specific date range for ${localeName} language`, () => {
+        selectLocale(localeName);
+        H.visitDashboard(ORDERS_DASHBOARD_ID);
+        H.editDashboard();
+        // Wait for dashboard to load
+        cy.findByTestId("dashcard-container").should("exist");
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts]: `H.visitDashboard` already waits for dashboard to load, is it not sufficient?

File: e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+          cy.findByLabelText("Start date").should(
+            "have.value",
+            expectedDateRange.startDate,
+          );
+          cy.findByLabelText("End date").should(
+            "have.value",
+            expectedDateRange.endDate,
+          );
+          cy.findByText("Add filter").click();
+        });
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts]: All this can be accomplished with an API call. We don't need to test the filter creation flow (it's already covered by other tests). We just need to assert the display value.

The test could look like this (pseudocode just for illustration):

```tsx
setupBrowserLocale();
createDashboardWithFilterAndDefaultValueViaApiAndVisitIt();
assertFilterDisplayValue();
```

File: e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts [hunk 6]
```diff
@@ -0,0 +1,88 @@
...
+
+        dashboard().within(() => {
+          cy.findByLabelText("Date").within(() => {
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard-filters/dateinput-locale.cy.spec.ts]: `within()` is not necessary both cases

File: frontend/src/metabase/querying/filters/utils/dates.ts [hunk 7]
```diff
@@ -323,9 +323,7 @@ export function getDateFilterDisplayName(
 }
 
 function formatDate(date: Date, hasTime: boolean) {
-  return hasTime
-    ? dayjs(date).format("MMMM D, YYYY hh:mm A")
-    : dayjs(date).format("MMMM D, YYYY");
+  return hasTime ? dayjs(date).format("LL hh:mm A") : dayjs(date).format("LL");
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/filters/utils/dates.ts:326]: Is this intended?
Let's make sure the Querying approves this change.

File: frontend/src/metabase/parameters/components/FormattedParameterValue/FormattedParameterValue.tsx [hunk 8]
```diff
@@ -39,6 +40,7 @@ function FormattedParameterValue({
   dashboardId,
   placeholder,
   isPopoverOpen = false,
+  dataTestId = "parameter-value",
```
Comment (kamilmielnik) [inline frontend/src/metabase/parameters/components/FormattedParameterValue/FormattedParameterValue.tsx]: There are similar tests already and they don't need the `data-testid`. Can we avoid adding it?

File: frontend/src/metabase/querying/filters/utils/dates.ts (hunk 7 above)
Comment (egorgrushin) [reply frontend/src/metabase/querying/filters/utils/dates.ts:326]: @kamilmielnik it's required because you've raised a good point about inconsistency of formatting dates inside calendar and the result value:
image

File: frontend/src/metabase/parameters/components/FormattedParameterValue/FormattedParameterValue.tsx (hunk 8 above)
Comment (egorgrushin) [reply frontend/src/metabase/parameters/components/FormattedParameterValue/FormattedParameterValue.tsx]: @kamilmielnik  in that case there is no way to distinguish pure date and date + label:
image

 And since we are testing value formatting we shouldn't care about with the label it was rendered with. For example, in the original bug (screenshot above) the label is "Date range", but in e2e tests the label is "Date".

Comment (kamilmielnik) [reply frontend/src/metabase/parameters/components/FormattedParameterValue/FormattedParameterValue.tsx]: Fair enough. In that case let's make sure the `data-testid` attribute is present for all types of filters (lines 94 & 107).

Comment (egorgrushin) [reply frontend/src/metabase/parameters/components/FormattedParameterValue/FormattedParameterValue.tsx]: It's already presented for all types of filters. Lines 94 and 107 call `renderContent()` which is already set this attribute for all cases
image

File: frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx [hunk 9]
```diff
@@ -20,12 +20,14 @@ interface DateRangePickerBodyProps {
...
   hasTime: boolean;
   onChange: (value: [Date, Date]) => void;
+  valueFormat?: string;
 }
 
 export function DateRangePickerBody({
   value,
   hasTime,
   onChange,
+  valueFormat = "LL",
```
Comment (ranquild) [inline frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx:30]: @egorgrushin to confirm - that's not set anywhere, correct? perhaps we want a constant instead. It would be also cool to have a unit test that verifies the change

File: frontend/src/metabase/querying/filters/utils/dates.ts (hunk 7 above)
Comment (ranquild) [reply frontend/src/metabase/querying/filters/utils/dates.ts:326]: It would be also cool to have a unit test that verifies the change

File: e2e/test/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js [hunk 10]
```diff
@@ -1,13 +1,50 @@
...
 } from "e2e/support/cypress_sample_instance_data";
+import { createMockParameter } from "metabase-types/api/mocks";
 
 import * as DateFilter from "../native-filters/helpers/e2e-date-filter-helpers";
 
 import { DASHBOARD_DATE_FILTERS } from "./shared/dashboard-filters-date";
 
+const { H } = cy;
+
+const localesAndExpected = [
```
Comment (ranquild) [inline e2e/test/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js]: @kamilmielnik @egorgrushin do we really need a e2e test for this? can we test different locales via a unit test?

File: frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx (hunk 9 above)
Comment (egorgrushin) [reply frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx:30]: @ranquild yes, it is. I was afraid to make the whole project regression, that's why I rollbacked it to only this place - https://github.com/metabase/metabase/pull/66298/commits/50f2d501c1ac36602abed5d9a6b4524f93a5ee75

**Review by ranquild — APPROVED** [review]
Do we need to cleanup after `setLocalization` call?

**Comment by egorgrushin** [comment]
> Do we need to cleanup after `setLocalization` call?

I don't know. I used the function in the same way as in the other tests. And since all other tests works well, it did some cleanup somehow. I didn't have a change to dive in of this function implementation, but I suppose it's because jest runs them isolated

**Comment by kamilmielnik** [comment]
It's probably a good idea to call `jest.resetModules()` in `afterAll`/`afterEach`.

**Review by kamilmielnik — APPROVED** [review]
