### PR TITLE
Fix :Postgres :day-of-week extracts coming back as 0..6 instead of 1..7

### LINKED ISSUE #17801: Grouping by "Day of week" behaves differently for some drivers depending on "First day of the week" setting
**Describe the bug**
There is inconsistency with how "Day of week" is presented depending on the database type and which day Admin > Settings > Localization > "First day of the week" is set to.
Feels like a backend issue, but might be a frontend issue (or combined).

**To Reproduce**
Create a question summarized "Standard deviation of Quantity" grouped by "Created At: Day of week" for the different drivers.
1. "First day of the week" = **Sunday** - all databases matches and are shown correctly, example H2:
image
2. "First day of the week" = **Monday**
   1. Postgres is still showing Sunday as starting
   image
   2. All the other drivers shows correctly, example H2:
   image
3. "First day of the week" = **Tuesday** (or changing to any other day in the week)
   1. MySQL, BigQuery and Snowflake makes a mess (and even worse if set to Saturday):
   image
   2. H2 and Postgres shows correctly:
   image

**Information about your Metabase Installation:**
Only tested 0.40.3.1, but I would guess this might have been present for a long time (likely since start of week was added)

**Additional context**
This might be a P2 and related to other issues like #8969 and #16114

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #17801

Postgres `:day-of-week` extracts came back in the range `Sunday(0)...Saturday(6)` instead of `Monday(1)...Sunday(7)` like our code was written to assume. The off-by-one number and off-by-one day bugs actually canceled each other in our existing tests which is why we didn't catch this before. Fixed by adding a new test based on #17801 and fixing the impl

MongoDB was also broken for Tuesday (the offset ended up causing some days of the week to come back negative) so I fixed that as well

### CODE REVIEW

File: test/metabase/query_processor_test/date_bucketing_test.clj [hunk 1]
```diff
@@ -1163,6 +1163,19 @@
                         :breakout    [!day-of-week.date]
                         :filter      [:between $date "2013-01-03" "2013-01-20"]}))))))))))
 
+(deftest first-day-of-week-for-day-of-week-bucketing-test
+  (testing "First day of week for `:day-of-week` bucketing should be the consistent (#17801)"
+    (mt/test-drivers (mt/normal-drivers-with-feature :basic-aggregations)
+      (let [query (mt/mbql-query checkins
+                    {:aggregation [[:count]]
+                     :breakout    [!day-of-week.date]})]
+        (doseq [[first-day-of-week expected-rows] {:sunday [[1 135] [2 143] [3 153] [4 136] [5 139] [6 160] [7 134]]
```
Comment (dpsutton) [inline test/metabase/query_processor_test/date_bucketing_test.clj:1172]: is it worth doing this for all days of the week?
```clojure
;; either generate it in code
(zipmap [:sunday :monday :tuesday :wednesday :thursday :friday :saturday]
        (map (fn [n coll]
                (mapv vector (next (range 7)) (drop n coll)))
              (range 7)
              (repeat (cycle [135 143 153 136 139 160 134]))))

;; or use the results of it cycling through.
{:sunday    [[1 135] [2 143] [3 153] [4 136] [5 139] [6 160]],
 :monday    [[1 143] [2 153] [3 136] [4 139] [5 160] [6 134]],
 :tuesday   [[1 153] [2 136] [3 139] [4 160] [5 134] [6 135]],
 :wednesday [[1 136] [2 139] [3 160] [4 134] [5 135] [6 143]],
 :thursday  [[1 139] [2 160] [3 134] [4 135] [5 143] [6 153]],
 :friday    [[1 160] [2 134] [3 135] [4 143] [5 153] [6 136]],
 :saturday  [[1 134] [2 135] [3 143] [4 153] [5 136] [6 139]]}
```

Comment (camsaul) [reply test/metabase/query_processor_test/date_bucketing_test.clj:1172]: Hmmm. Not a bad idea. I'll have to update that

Comment (camsaul) [reply test/metabase/query_processor_test/date_bucketing_test.clj]: fixed

**Review by flamber — APPROVED** [review]
This works great with the handful of database types (H2, MySQL, Postgres, BigQuery, Snowflake, Redshift) I tested on.

**Comment by chte** [comment]
It seems like this issue is still the case for MSSQL / Azure Synapse

**Comment by flamber** [comment]
@chte Create a new issue with all the details filled out, so it is possible for us to reproduce.
