### PR TITLE
Close table header popover with escape

### LINKED ISSUE #55673: qb: column popover should be closed by pressing ESC
**Context**
tests from `e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js` were disabled as they looked like flaky. Actually they caughed a regression somewhere near v53.1, so pressing ESC no longer closes header popover

https://github.com/user-attachments/assets/6fd02f3a-9b2a-4b71-ba4b-96cf62a71446

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/55673

### To verify 

1. Open the orders table
2. Click a header
3. Press escape
4. the popover should close

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.tsx [hunk 1]
```diff
@@ -56,6 +56,20 @@ export class ClickActionsPopover extends Component<
     }
   }
 
+  componentDidMount(): void {
+    window.addEventListener("keydown", this.handleKeyDown, { capture: true });
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.tsx]: There already is a keydown listener somewhere because Escape key will sometimes close the popover. Let's figure out why doesn't it always kick in.

In `master`:
1. Browse Products
2. Click "Category" table header
3. Click "Filter by this column"
4. Click "Is" to open up the operator picker
5. Hit Escape

The popover gets closed!
And actually the above behavior is incorrect.
Escape should close the operator picker first, and only a subsequent Escape press should close the popover in question.

----

We should also figure out the line that says  `// TODO - come back to this` in `ClickActionsPopover`.

**Review by kamilmielnik — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.tsx (hunk 1 above)
Comment (romeovs) [reply frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.tsx]: How about we just enable `trapFocus` for the popover? It probably makes sense anyway and solves the issue.

Comment (kamilmielnik) [reply frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.tsx]: Makes sense :+1: 
But we don't seem to need `closeOnEscape`.

**Review by kamilmielnik — APPROVED** [review]
