### PR TITLE
Remove flicker in SQL editing autocomplete

### LINKED ISSUE #21034: Autocomplete flicker in SQL Editor
To reproduce, follow these steps while opening DevTools and watching the Network panel (filter for Fetch/XHR only)

1. New, Native/SQL query, Sample Database
2. Type `p` (and watch the call to `/api/database/1/autocomplete_suggestions?prefix=p`)
3. After sometime, there is a flicker in the UI, particularly the suggestion popover (and another API call in the background)

**Actual**

image

**Expected**

The UI doesn't flicker. There is only a single API call.

### PR DESCRIPTION
**Pull request by ariya**
To reproduce, follow these steps while opening DevTools and watching the Network panel (filter for Fetch/XHR only)

1. New, Native/SQL query, Sample Database
2. Type `p` (and watch the call to `/api/database/1/autocomplete_suggestions?prefix=p`)
3. After sometime, there is a flicker in the UI, particularly the suggestion popover (and another API call in the background)

### Before this PR

Two calls to the `autocomplete_suggestions` API.

image

### After this PR

Only one call, hence no flickering.

Screenshot_20220328_151715

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx [hunk 1]
```diff
@@ -269,11 +270,21 @@ export default class NativeQueryEditor extends Component {
...
-          const results = await this.props.autocompleteResultsFn(prefix);
+          let { results, timestamp } = this._lastAutoComplete;
+          const cacheHit =
+            Date.now() - timestamp < AUTOCOMPLETE_CACHE_DURATION &&
+            this._lastAutoComplete.prefix === prefix;
+          if (!cacheHit) {
+            // HACK: call this.props.autocompleteResultsFn rather than caching the prop since it might change
+            results = await this.props.autocompleteResultsFn(prefix);
+            this._lastAutoComplete = { timestamp: Date.now(), prefix, results };
+          }
```
Comment (WiNloSt) [inline frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx:286]: What if we abstract this away, so we don't get lost in the implementation too much. I wish I could just read something like

```ts
const results = await this._autocompleteResultsFnWithCache(prefix)
```

or something similar

**Review by WiNloSt — APPROVED** [review]

**Review by flamber — COMMENTED** [review]
Since previous PRs were backported, then this should probably too.

Does this only prevent flicker on the first character? Or does the following characters require the backend change?

https://user-images.githubusercontent.com/1447303/160634476-536a3917-56e8-44fb-925d-3387f05c73d1.mp4

**Comment by ariya** [comment]
> Does this only prevent flicker on the first character? Or does the following characters require the backend change?

Yes and no.

There can never be any backend change that reduces the flicker further, since it's implicit in the way Ace handles autocompletes (the suggestions for the autocomplete must be _instantly_ available, it can't be retrieved remotely).

A smooth and flicker-free autocomplete that involves fetching remote data requires us to bypass Ace's current autocomplete mechanism and implement a custom one.

File: frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx (hunk 1 above)
Comment (ariya) [reply frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx:286]: I thought about that, but then since this is just a hack until we got a new Ace-based component in place, likely with a rewritten autocomplete logic anyway, then it is also beneficial to let this hack appears front and center.
