### PR TITLE
Set max height to native editor and some other refactors

### LINKED ISSUE #59075: You can drag the divider below the native query editor off the bottom of the page
### Describe the bug

If you grab the divider between the native query editor and the visualized results you can drag it down off the bottom of the page

  https://www.loom.com/share/52c67dc268c8415a91c90138ad6eece9

### To Reproduce

See loom

### Expected behavior

Should not be able to drag indefinitely

### Logs

_No response_

### Information about your Metabase installation

```JSON
bde63bb
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes #59075

I had to refactor the `NativeQueryEditor` to a functional component to make this happen.

This also fixes resizing in the SQL modal in documents and in the transform sql editor.

The editor now handles parameter lists and the window being resized.

To simplify the code, I removed the animation when auto-collapsing the editor. It was hardly noticable anyway and made the code more complex. @mazameli please confirm this ok?

I did some more refactoring of the `NativeQueryEditor` component too:
- Convert the component to a functional component and use hooks,
- Remove unused HOC's
- Switch to hooks for the snippet loaders
- Fix types, as the component was actually untyped, this surfaced a lot of misuses in different locations
- Remove `forwardedRef` patter for actual `forwardRef`

### To verify

1. New SQL query
2. Type a query with a lot of template tags, ie. `SELECT 1, [[ {{x}}, {{y}}, {{z}}, {{a}}, {{b}}, {{c}}]]`
3. Resize the editor to the bottom of the screen, it should stop above the bottom of the page 
4. Resize the window, the editor should resize accordingly
5. Keep making the window smaller, the editor should collapse when it becomes too small.

Do the same for
- Data studio -> Transforms -> New SQL transform
- New -> Document -> type `/` -> `Chart` -> `New Chart` -> `New SQL Query`

https://github.com/user-attachments/assets/4a10ec27-51dd-4893-bf68-24923c8b2b5f

### CODE REVIEW

File: frontend/src/metabase/query_builder/actions/native.ts [hunk 1]
```diff
@@ -91,9 +91,12 @@ export const setIsShowingSnippetSidebar = (
...
 });
 
-export const setIsNativeEditorOpen = (isNativeEditorOpen: boolean) => ({
+export const setIsNativeEditorOpen = (
+  isNativeEditorOpen: boolean,
+  openDataReference: boolean = true,
+) => ({
   type: SET_UI_CONTROLS,
-  payload: { isNativeEditorOpen, isShowingDataReference: isNativeEditorOpen },
+  payload: { isNativeEditorOpen, isShowingDataReference: openDataReference },
```
Comment (romeovs) [inline frontend/src/metabase/query_builder/actions/native.ts]: I'm adding a parameter here so we don't have to conditionally call setUIControls in `NativeQuery` as [was the case before](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx#L467-L473).

File: frontend/src/metabase/query_builder/components/view/View/View/View.jsx [hunk 2]
```diff
@@ -291,6 +292,9 @@ const mapDispatchToProps = (dispatch) => ({
     const deleteAction = Questions.actions.delete({ id });
     dispatch(deletePermanently(deleteAction));
   },
+  runQuery: () => {
+    dispatch(runOrCancelQuestionOrSelectedQuery());
```
Comment (romeovs) [inline frontend/src/metabase/query_builder/components/view/View/View/View.jsx:296]: I'm adding this prop here so we don't have to conditionally add it [as was the case before](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx#L460-L462)

File: frontend/src/metabase/rich_text_editing/tiptap/extensions/shared/NativeQueryModal.tsx [hunk 3]
```diff
@@ -379,21 +379,6 @@ export const NativeQueryModal = ({
                     setModifiedQuestion(newQuestion);
                   }}
                   resizable
-                  resizableBoxProps={{
```
Comment (romeovs) [inline frontend/src/metabase/rich_text_editing/tiptap/extensions/shared/NativeQueryModal.tsx:382]: This can be removed because we're now allowing actual resizing of the editor in tiptap.

File: frontend/src/metabase-lib/v1/queries/NativeQuery.ts [hunk 4]
```diff
@@ -361,6 +362,13 @@ export default class NativeQuery {
         ? this.updateSnippetNames([newSnippet])
         : this;
 
+    // We need to update the metadata first to make sure the new snippet
+    // is correctly extracted from the query
+    const metadata = new Metadata(this.metadata());
+    delete metadata.snippets[oldSnippet.name];
+    metadata.snippets[newSnippet.name] = newSnippet;
+    newQuery.question()._metadata = metadata;
```
Comment (romeovs) [inline frontend/src/metabase-lib/v1/queries/NativeQuery.ts:366]: I think it was a fluke for this to have worked before or it was depending on some very dark entity framework magic.

When changing a snippet, `metabase-lib` wants to recalculate the template tags and looks at the metadata for the actual snippet definitions. This means the metadata needs to contain the new snippet definition correctly.

**Comment by mazameli** [comment]
@romeovs, nice, all seems to be working as expected. Only suggestion I'd make is that the minimum height of the results area seems to be about 32px, which seems just a bit too small. I'd modestly increase it to 80px minimum, just so it doesn't get lost on screen.

File: e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js [hunk 5]
```diff
@@ -1120,6 +1120,9 @@ describe("scenarios > visualizations > bar chart", () => {
       },
     });
 
+    // Open the data reference sidebar to squish the data further
+    cy.findByLabelText("Learn about your data").click();
```
Comment (romeovs) [inline e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js:1124]: This test was relying on the data reference to be open, but it auto-opening at this width was a bug. We need to open it manually now to make the test work.

File: frontend/src/metabase/query_builder/components/view/View/ViewMainContainer/utils.ts [hunk 6]
```diff
@@ -0,0 +1,27 @@
+import { useEffect, useRef, useState } from "react";
+
+export function useHeightAboveFold() {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/View/ViewMainContainer/utils.ts]: Can we avoid this and use useElementSize? It's based on the ResizeObserver so I thought it would work.

**Review by ranquild — APPROVED** [review]
