### PR TITLE
Gh 17910 revision history

### LINKED ISSUE #17910: Revision history does not update until page reload
**Describe the bug**
When you update a saved question, the change is not reflected in the History timeline because the cache of revision history entities is never cleared.

**To Reproduce**
1. Ask a Question > Simple Question > Sample Dataset > People
2. Save the People table as a new question
3. Click the name of the saved question ("People" by default) to open the details sidebar
4. Click on the "History" drawer to see the revision history of the question (since it is a new question, there should only be a single entry)
5. Add a description to the question and save
6. Note that a new entry is not added to the History timeline
7. Refresh the page and return to the History timeline to see a new entry noting the change in description

**Expected behavior**
A new revision history entry should be immediately visible and not require a refresh after editing a question or dashboard.

**Severity**
p3

⚠️ See https://github.com/metabase/metabase/pull/19466. An e2e test was adapted in that PR, and should be reverted once this issue is fixed.

### PR DESCRIPTION
**Pull request by npfitz**
Fixes #17910 
Reproduces #17910 

The core of the issue is that the `revisions_list` entity can be invalidated before any revisions_lists are actually fetched. This causes the logic [here](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/redux/requests.js#L70) to apply the initial state to the entire substate for the entity, rather than on the specific queries. Because the revisions entity is set to invalidate on question and dashboard actions, creating a question immediately corrupts this substate.

This change should ensure that any bulk entity invalidations can only occur if the `requests/entites/[entity_name]` has anything to actually invalidate.

### CODE REVIEW

File: frontend/src/metabase/redux/requests.js [hunk 1]
```diff
@@ -80,9 +80,12 @@ function requestStateReducerRecursive(state, action) {
...
   if (action && action.payload && action.payload.statePath) {
-    state = updateIn(state, action.payload.statePath, subState =>
-      requestStateReducerRecursive(subState, action),
-    );
+    const statePath = action.payload.statePath;
+    if (statePath.length > 2 || getIn(state, statePath)) {
+      state = updateIn(state, action.payload.statePath, subState =>
+        requestStateReducerRecursive(subState, action),
+      );
+    }
```
Comment (kulyk) [inline frontend/src/metabase/redux/requests.js:88]: Could you please explain what exactly the check does here? Wondering what the `2` number means here. I think it'd make sense to maybe extract a condition to a constant with a more human-friendly name or maybe adding a comment or something

File: frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.cy.spec.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
+import { restore, openOrdersTable, modal } from "__support__/e2e/cypress";
+
+describe("issue 17910", () => {
```
Comment (kulyk) [inline frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.cy.spec.js:3]: We're experimenting with how we organize and run repro tests, could you please align these tests with the rest of the question repros, please?

1. Please make it export a function with test definition like in [other question repro files](https://github.com/metabase/metabase/tree/977ea2abcb61319125b82fa16d93c18610194134/frontend/test/metabase/scenarios/question/reproductions)
2. Replace `cy.spec.js` with just `.js`
3. Import and call the function from [this file](https://github.com/metabase/metabase/blob/977ea2abcb61319125b82fa16d93c18610194134/frontend/test/metabase/scenarios/question/question-reproductions.cy.spec.js)

File: frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.cy.spec.js [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+  beforeEach(() => {
+    restore();
+    cy.signInAsNormalUser();
+  });
+
+  it("Revisions should work after creating a question without reloading", () => {
```
Comment (kulyk) [inline frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.cy.spec.js:9]: Please don't use capital case for test descriptions

File: frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.cy.spec.js [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+      cy.findByText("Save").click();
+    });
+    cy.wait("@card");
+    modal().within(() => {
+      cy.findByText("Not now").click();
+    });
+    cy.findByTestId("saved-question-header-button").click();
+    cy.findByText("Add a description").click();
+    modal().within(() => {
+      cy.get("textarea[name=description]").type("A description");
```
Comment (kulyk) [inline frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.cy.spec.js:23]: You can use `cy.findByLabelText("Description")` here

File: frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.cy.spec.js [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+      cy.findByText("Save").click();
+    });
+    cy.findByText("History").click();
+    cy.findByText("History")
+      .siblings()
+      .first()
+      .find("ul")
+      .children()
+      .should("to.have.length", 2);
```
Comment (kulyk) [inline frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.cy.spec.js:32]: Tests relying on DOM structure that much can be pretty fragile, ie we can add/remove a few intermediate DOM nodes and it can break the test. We can add `data-testid` attributes to elements and then query them using `findByTestId` as an alternative

File: frontend/src/metabase/redux/requests.js (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/redux/requests.js:88]: For sure! There are 2 types of invalidations: specific request invalidations (which include a key/id in the state path), and bulk invalidations which just say "invalidate all requests for this entity". Those bulk invalidations have a statePath that is 2 items long. The fix as it exists right now is to ensure that there is something there to invalidate, which is why we also call `getIn(state, statePath)`

Comment (npfitz) [reply frontend/src/metabase/redux/requests.js:88]: Awesome! Yeah, I'll make this more readable and include a comment in there for future reference

File: frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+      openOrdersTable();
+      cy.intercept("POST", `/api/card`).as("card");
+      cy.findByText("Save").click();
+      modal().within(() => {
+        cy.findByText("Save").click();
+      });
+      cy.wait("@card");
+      modal().within(() => {
+        cy.findByText("Not now").click();
+      });
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js:20]: We can (and should) use API for this part. It makes no difference for the revision history, but it makes test faster and more resilient.

File: frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js [hunk 7]
```diff
@@ -0,0 +1,33 @@
...
+      cy.findByTestId("saved-question-header-button").click();
+      cy.findByText("Add a description").click();
+      modal().within(() => {
+        cy.findByLabelText("Description").type("A description");
+        cy.findByText("Save").click();
+      });
+      cy.findByText("History").click();
+      cy.findByTestId("saved-question-history-list")
+        .children()
+        .should("to.have.length", 2);
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js:30]:
```suggestion
        .should("have.length", 2);
```

File: frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js (hunk 6 above)
Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js:20]:
```js
cy.createQuestion(
  {
    name: "17910",
    query: { "source-table": ORDERS_ID },
  },
  // This part already does the intercepting and waiting for you under the hood
  { visitQuestion: true },
);
```

Comment (npfitz) [reply frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js:20]: I'll give this a try, but I'm pretty sure that the bug relies on the events that occur from creating the question via the UI. It's the redux events firing that puts us in a bad state

Comment (npfitz) [reply frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js:20]: I tried to repro with creating the question via the API but it didn't reproduce the bug.

**Review by kulyk — APPROVED** [review]
Looks good!

File: frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js [hunk 8]
```diff
@@ -0,0 +1,33 @@
+import { restore, openOrdersTable, modal } from "__support__/e2e/cypress";
+
+export function issue17910() {
+  describe("issue 17910", () => {
+    beforeEach(() => {
+      restore();
+      cy.signInAsNormalUser();
+    });
+
+    it("revisions should work after creating a question without reloading", () => {
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js:10]:
```suggestion
    it("revisions should work after creating a question without reloading (metabase#17910)", () => {
```
It's important to add these kind of references to the test title.

File: frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js (hunk 6 above)
Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/question/reproductions/17910-revision-history-update.js:20]: In that case, go for it :)
Thanks for going the extra mile!
