### PR TITLE
[Cmd Palette] Do not show admin and settings links to users who do not have access

### LINKED ISSUE #49729: Command palette should not show you admin actions if you do not have access to them
### Describe the bug

The command palette will show you links to the admin app, even if you are not an admin

### To Reproduce

1. Sign in as a non admin
2. open the command palette
3. type "settings"

### Expected behavior

We should not show you settings links if you are not an admin

### Logs

_No response_

### Information about your Metabase installation

1815b5248fc4cafce942a1e2e99285fe9fb5a7f9

### Severity

Low

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sloansparger**
Closes https://github.com/metabase/metabase/issues/49729

### Description

The above issue points out that users who are not admins were seeing settings links when they did not have access to the settings pages. This PR fixes that, so that only users with proper permissions to see those pages will have the appropriate options shown to them. This change also takes into account our advanced permissions which permits non-admin to make changes to a subset of our settings page.

### How to verify

Without advanced permissions:
- Sign in as a non-admin
- Open the command palette and type "settings"
- You should see no admin settings links

With advanced permissions:
- Sign in as admin
- Go to permissions page and select "Application" tab
- Give all users access to settings
- Sign out then sign in as a non-admin
- Open the command palette and type "settings"
- You should see some settings pages but not all (General settings should be available, but Setup settings should not be)

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/palette/hooks/useCommandPalette.tsx [hunk 1]
```diff
@@ -256,6 +261,10 @@ export const useCommandPalette = ({
   ]);
 
   const adminActions = useMemo<PaletteAction[]>(() => {
+    if (!isAdmin) {
```
Comment (npfitz) [inline frontend/src/metabase/palette/hooks/useCommandPalette.tsx:264]: I think this is too restrictive, because it means that people with access to tools / troubleshooting, or access to manage DBs, are now missing links. I'll submit a PR that fixes this, it's a small adjustment

**Review by npfitz — CHANGES_REQUESTED** [review]
Small adjustment, and we should cover the other permission cases with tests as well
image

**Review by npfitz — CHANGES_REQUESTED** [review]
Would be good to get coverage on the other application permissions too, as well as DB Management

**Review by npfitz — APPROVED** [review]
I added the tests 😂 . Good to go now!
