### PR TITLE
Fix row id mapping in object detail modal displaying

### LINKED ISSUE #34070: View Details: "is connected to:" uses wrong PK for query with join
### Describe the bug

In some cases, after clicking on the "**View Details**", instead of showing the connected entities, the phrase "**Unknown**" is displayed.

image

By monitoring the messages passed between Metabase and the Postgres Docker Image using Wireshark, one can notice that the problem comes from a wrong sql query, that Metabase generates and sends to the Postgres Database:

Message generated by metabase and sent to the Postgres DB:
**SELECT count(*) AS "count" FROM "source1"."rooms" WHERE "source1"."rooms"."h_id" = 9**

The Reply message from Postgres DB to metabase:
operator does not exist: **text = integer No operator matches** the given name and argument types. You might need to add explicit type casts

Similar errors can be seen by checking the Wireshark log of discussions between metabase and the postgres DB after clicking on different columns data, every now and then.

### To Reproduce

In order to reproduce this error, 
1-  start from the Destination Postgres Database from the following link:
https://github.com/ontopic-vkg/destination-tutorial

2- Add the destination database, as a source database to metabase, 

3- join the following tables: Source1.Hospitality, Source1.Municipality.
image

4- after visualizing the data, and clicking on the "View Details" as follow, 
image

one will get the following error message:
image

_No response_

### Logs
By monitoring the messages passed between Metabase and the Postgres Docker Image using Wireshark, one can notice that the problem comes from a wrong sql query, that Metabase generates and sends to the Postgres Database:

Message generated by metabase and sent to the Postgres DB:
**SELECT count(*) AS "count" FROM "source1"."rooms" WHERE "source1"."rooms"."h_id" = 9**

The Reply message from Postgres DB to metabase:
operator does not exist: **text = integer No operator matches** the given name and argument types. You might need to add explicit type casts

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.10.102.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-01-27",
      "tag": "v0.45.2.1",
      "branch": "release-x.45.2.x",
      "hash": "1a59de7"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity
Blocking the usage of metabase for us.

_No response_
```[tasklist]
### Tasks
```

### LINKED ISSUE #39477: State of the FE gets lost on detail views when there are multiple joins to the same tables
### Describe the bug

If you build a question with lots of joins to the same table (e.g. orders join people join people join products join products) and you make quick clicks to detail views, then the frontend gets lost and shows details from other items.

### To Reproduce

1) create a question like 
image

2) visualize it and click on the item details, you'll see that everything works
3) now click quickly switch between ids, clicking quickly and not even letting the rendering to finish, see that the ID's will show wrongly

### Expected behavior

We should show the correct object

### Logs

NA

### Information about your Metabase installation

```JSON
v49.x, but this has been like this since forever
```

### Severity

P1

### Additional context

uimiss

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/39477
Closes https://github.com/metabase/metabase/issues/34070

### Description

we have a not straightforward logic on detecting what the data should be shown after clicking on a table row to show object detail modal. This PR reuses logic of mapping row id to the entity id

### How to verify

- create a new question from orders table
- join people table
- click on visualize
- click on the most left cell of any displayed row
- click on first row should work
- click on any row should display a modal with the correct id (same id as the row you clicked has)

### Demo

Before

https://github.com/metabase/metabase/assets/125459446/adaff085-e940-40e4-8ade-b0eabb710214

After

https://github.com/metabase/metabase/assets/125459446/42d3a398-9278-4980-8687-6878699f8a33

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [x] stress test https://github.com/metabase/metabase/actions/runs/8527115010

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx [hunk 1]
```diff
@@ -482,10 +486,20 @@ class TableInteractive extends Component {
...
+    } else {
+      const map = this.props.PKRowIndexMap;
+
+      objectId =
+        Object.keys(map).find(key => map[key] === rowIndex) ?? rowIndex;
+    }
+
+    return () => {
+      this.props.onZoomRow(objectId);
+    };
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx:502]: I don't know if there's a problem, but I'd feel safer if all `this.props` and `this.state` references happened inside the returned callback (to avoid referencing stale props when callback is executed).

```suggestion
    return () => {
      let objectId;

      if (this.state.IDColumn) {
        objectId = this.props.data.rows[rowIndex][this.state.IDColumnIndex];
      } else {
        const map = this.props.PKRowIndexMap;

        objectId =
          Object.keys(map).find(key => map[key] === rowIndex) ?? rowIndex;
      }

      this.props.onZoomRow(objectId);
    };
```

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx [hunk 2]
```diff
@@ -77,6 +80,7 @@ function pickRowsToMeasure(rows, columnIndex, count = 10) {
 
 const mapStateToProps = state => ({
   queryBuilderMode: getQueryBuilderMode(state),
+  PKRowIndexMap: getPKRowIndexMap(state),
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx:83]: There's a very similar bug: #34070
Unfortunately this PR does not seem fix it.

**Review by kamilmielnik — COMMENTED** [review]
It'd be great if we could fix #34070 as well.

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx (hunk 2 above)
Comment (uladzimirdev) [reply frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx:83]: seems it's a different problem, which requires more investigation

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx:502]: well, this function is re-calculated every time you hover over a row

`hoverDetailEl.onclick = this.pkClick(rowIndex)` 

or press "Enter" - `this.pkClick(hoveredRowIndex)(event);` 

I'd not worry about stale props

**Review by kamilmielnik — APPROVED** [review]

File: frontend/src/metabase/query_builder/selectors.js [hunk 3]
```diff
@@ -184,6 +184,29 @@ export const getPKRowIndexMap = createSelector(
   },
 );
 
+// it's very similar to `getPKRowIndexMap` but it is required for covering "view details" click
+// we don't have objectId there, only rowId, mapping from `getPKRowIndexMap` is opposite
+// if rows are showing the same PK, only last one will have the entry in the map
+// and we'll not know which object to show
+export const getRowIndexToPKMap = createSelector(
+  [getFirstQueryResult, getPKColumnIndex],
+  (result, PKColumnIndex) => {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/selectors.js:193]: nit: lowercase `pkColumnIndex`?

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx]: changed it in fa0289f5644f3b912a901a4bdafc58f65468e797

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx (hunk 2 above)
Comment (uladzimirdev) [reply frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx]: fa0289f5644f3b912a901a4bdafc58f65468e797 should fix it

**Review by kamilmielnik — APPROVED** [review]
Works well :+1: 

----

FYI there is one more similar issue (#29390), still reproducible.
