### PR TITLE
Adjust external column type sync

### LINKED ISSUE #41788: Integer columns in Redshift external tables aren't receiving valid metadata
### Describe the bug

 The following column type signatures are mapped incorrectly in Redshift. 
 ```
 company_type_id int(11)
 internal_corporate_id int(10) unsigned
 coop_cat tinyint(1)
```
These types seem to appear only in external tables with SERDE row format, see an example table definition attached below.

Column metadata becomes:
```
{
           "database_type": "int(10) unsigned",
           "semantic_type": null,
           "base_type": "type/*",
           "effective": "type/*",
           "semantic_type": null,
[...]
}
```

A related frontend issue is that the filter selector displays these with a circle fallback icon in front of their names,
image

and when a problematic column is selected for filtering, the filter selector breaks down entirely.
https://github.com/metabase/metabase/assets/11080638/75372847-693a-4ab7-8022-518aa5320dc2

The workaround is to manually set the column type to a known type.

### To Reproduce

To reproduce the FE / filtering: override metadata for a field either in the API result or change it in the application database, so that {"semantic_type": null, "effective_type": "type/*", ...} is returned.

I did not reproduce the BE / schema sync part. For that create an external table on Redshift with a definition similar to the one I attached.

### Expected behavior

BE: The correct effective and semantic type is determined for the data types listed above.
FE: Filtering should not break down even if some of the columns is not mapped correctly.

### Logs

_No response_

### Information about your Metabase installation

```JSON
1.49.6
```

### Severity

P2

### Additional context

Table definition that caused the problem:
```
CREATE EXTERNAL TABLE oms.company (
   id int(10) unsigned,
   omega_id varchar(32),
   company_type_id int(11),
   company_block_id int(11),
   company_format_id int(11),
   company_region_id int(11),
   name varchar(128),
   gln varchar(16),
   internal_corporate_id int(10) unsigned,
   invoice_customer_id int(11),
   legal_name varchar(128),
   created_at timestamp,
   updated_at timestamp,
   coop_cat tinyint(1)
)
ROW FORMAT SERDE ''
STORED AS INPUTFORMAT ''
OUTPUTFORMAT '' LOCATION '';
```

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes https://github.com/metabase/metabase/issues/41788

### Description

This PR makes updates database type to base types mapping for Redshift external columns.

I've attempted to find a way of mapping the external type to rs database type. I've also checked whether system tables (eg. svv_external_columns, svv_external_schemas...) wouldn't offer rs type info. I've checked whether mysql data-type->base-type implementation could not be re-used.

As former didn't work, I've resorted to consulting mysql docs and redshift jdbc driver.

This PR does not implement support for set and enum rs types. That should be handled separately I believe.

### How to verify

Run new tests or follow repro from issue comments.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/redshift/src/metabase/driver/redshift.clj [hunk 1]
```diff
@@ -178,6 +178,46 @@
 
 ;; custom Redshift type handling
 
+(defn- external-datbaase-type->base-type
```
Comment (rileythomp) [inline modules/drivers/redshift/src/metabase/driver/redshift.clj:181]:
```suggestion
(defn- external-database-type->base-type
```

**Review by rileythomp — APPROVED** [review]
