### PR TITLE
Use SameSite=None for EMBEDDED_SESSION and DEVICE cookies

### LINKED ISSUE #18553: Cookie `metabase.DEVICE` does not respect SameSite environment variable
**Describe the bug**
Cookie `metabase.DEVICE` does not respect SameSite environment variable. Always uses `Lax`.
I'm currently unsure if this is aiding in some of the problems I'm seeing with FullApp embedding, but all the errors doesn't help.

**To Reproduce**
1. Setup FullApp embedding and do a login.
2. The browser console is littered with errors: `Cookie “metabase.DEVICE” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”.`, which makes it even more difficult to debug problems.

**Expected behavior**
metabase.DEVICE:
https://github.com/metabase/metabase/blob/2a7fefc4a669db96ce0ff4f6df41e274c2278b29/src/metabase/server/middleware/browser_cookie.clj#L18
Should use the environment variable `MB_SESSION_COOKIE_SAMESITE` that is used for `metabase.SESSION` https://github.com/metabase/metabase/blob/master/src/metabase/server/middleware/session.clj

But there seem to be some code, which indicates that full-app-embed is handled differently. I don't know how to use that.
https://github.com/metabase/metabase/blob/master/src/metabase/server/middleware/session.clj#L102

**Information about your Metabase Installation:**
Tested 1.41.0

### LINKED ISSUE #18822: EMBEDDED_SESSION cookie does not have SameSite=None specified
**Describe the bug**
Full app-embedding is designed to work without setting `MB_SESSION_COOKIE_SAMESITE=None`. However, right now it does not work. One of the reason is that `EMBEDDED_SESSION` does not have `SameSite=None` specified. (The parameter is omitted and previously `SameSite=None` is the default for browsers but recently they have changed to `SameSite=Lax` to improve security.)

There should not be additional security concern with  `SameSite=None` because Metabase enforces anti-CSRF token when using `EMBEDDED_SESSION` cookie.

Important: `SameSite=None` should be set only when served over HTTPS otherwise modern browsers will reject the cookie and may prevent embedding from working even on the same domain.

**Logs**
See screenshot

**To Reproduce**
1. Do full-app embedding of Metabase from a different domain without SSO
2. Login
3. You are redirected back to the login page after login

**Expected behavior**
Cookie should have `SameSite=None` specified and login should succeed.

**Screenshots**

**Information about your Metabase Installation:**
1.41.1

**Severity**
A workaround is available, which is:
1. Setting up SSO (which causes Metabase to use `SESSION` cookie instead of `EMBEDDED_SESSION` cookie to to bug #18823)
2. Set `MB_SESSION_COOKIE_SAMESITE=None` which causes the `SESSION` cookie to be set to `SameSite=None` and works cross-domain.

Nevertheless this makes it harder to setup full-app embedding, especially on cloud.

**Additional context**
Related Issue: #18553 - If we don't fix the cookie over there too, the user will get "We've Noticed a New Metabase Login" email every time login happens in embedding (even with SSO), which is not very friendly.

### PR DESCRIPTION
**Pull request by pawit-metabase**
`EMBEDDED_SESSION` previously did not specify SameSite attribute and assumed that the browser would default to SameSite=None, but recent browsers default to SameSite=Lax which does not work with cross-domain full-app embedding. (Fixes #18822)

`DEVICE` was previously set to SameSite=Lax causing devices to not be remembered during login with cross-domain full-app embedding resulting in superfluous "We've Noticed a New Metabase Login" emails. Setting it to SameSite=None is safe because the cookie is not used to authenticate a user. (Fixes #18553)

The `MB_SESSION_COOKIE_SAMESITE` configuration is not used here because there's no real reason to configure them to be anything else. (And these cookie have different security implications so we should not force them to use the same `SameSite` setting as the `SESSION` cookie.)

### CODE REVIEW

**Comment by flamber** [comment]
When testing `406b3e5` without using MB_SESSION_COOKIE_SAMESITE, I'm still seeing browser console errors about `metabase.DEVICE` cookies, and I cannot login with JWT or SAML.
Starting with MB_SESSION_COOKIE_SAMESITE=None works just like currently.

Testing with `https://metabase.domain.test` and the fullapp via `https://app.another.example`.
Perhaps it's because I'm using a reverse-proxy to do https, but the actual Metabase connection is http? But that's a very common setup.

**Comment by pawit-metabase** [comment]
@flamber This PR does not fix JWT/SAML (#18554) as that is more complicated. This is more of a preparation so that once we fix #18854, everything will work correctly.

If you're using a reverse proxy, one of these headers required to be set by the reverse proxy:
 - `x-forwarded-proto: https`
 - `x-forwarded-protocol: https`
 - `x-url-scheme: https`
 - `x-forwarded-ssl: on`
 - `front-end-https: on`

Oh, and I think the code for that warning you've shared is broken and will always warn when MB_SESSION_COOKIE_SAMESITE=None regardless of whether it's served over HTTPS or not.

**Comment by flamber** [comment]
@pawit-metabase Tested `690f144`, but still don't see any difference. Perhaps I'm misunderstanding what this PR is trying to address. Even added all the headers. My test Nginx config:
```
map $http_upgrade $connection_upgrade {
  default "upgrade";
}

server {
  server_name metabase.example.test;

  listen 80;
  listen [::]:80;

  return 301 https://$host$request_uri;
}

server {
  server_name  metabase.example.test;

  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  ssl_certificate  /etc/letsencrypt/live/  metabase.example.test/fullchain.pem;
  ssl_certificate_key  /etc/letsencrypt/live/  metabase.example.test/privkey.pem;
  ssl_trusted_certificate  /etc/letsencrypt/live/  metabase.example.test/fullchain.pem;

  location / {
    proxy_http_version  1.1;
    proxy_read_timeout  1205;
    proxy_set_header  Connection  $connection_upgrade;
    proxy_set_header  Upgrade  $http_upgrade;
    proxy_set_header  Host  $host;
    proxy_set_header  X-Real-IP  $remote_addr;
    proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;

    proxy_set_header  x-forwarded-proto  https;
    proxy_set_header  x-forwarded-protocol  https;
    proxy_set_header  x-url-scheme  https;
    proxy_set_header  x-forwarded-ssl  on;
    proxy_set_header  front-end-https  on;

    proxy_pass  http://127.0.0.1:3000/;
  }

}
```

File: src/metabase/server/middleware/browser_cookie.clj [hunk 1]
```diff
@@ -4,23 +4,32 @@
...
+;; This cookie doesn't need to be secure, because it's only used for notification purposes and cannot be used for
+;; CSRF as it is not a session cookie.
+;; However, we do need to make sure it's persisted/sent as much as possible to prevent superfluous login notification
+;; emails when used with full-app embedding, which means setting SameSite=None when possible (over HTTPS) and
+;; SameSite=Lax otherwise. (See metabases#18553)
+(defn- cookie-options
+  [request]
+  (merge {:http-only true
+          :path      "/"
+          :same-site :lax
```
Comment (camsaul) [inline src/metabase/server/middleware/browser_cookie.clj:24]: You should remove this key since this value is getting overwritten by the `merge`

File: src/metabase/server/middleware/browser_cookie.clj [hunk 2]
```diff
@@ -4,23 +4,32 @@
...
-  {:http-only true
-   :path      "/"
-   :same-site :lax
-   ;; Set the cookie to expire 20 years from now. That should be sufficient
-   :expires   (t/format :rfc-1123-date-time (t/plus (t/zoned-date-time) (t/years 20)))})
+;; This cookie doesn't need to be secure, because it's only used for notification purposes and cannot be used for
+;; CSRF as it is not a session cookie.
+;; However, we do need to make sure it's persisted/sent as much as possible to prevent superfluous login notification
+;; emails when used with full-app embedding, which means setting SameSite=None when possible (over HTTPS) and
+;; SameSite=Lax otherwise. (See metabases#18553)
```
Comment (camsaul) [inline src/metabase/server/middleware/browser_cookie.clj:19]: I think you meant `metabase`, not `metabases`.

For next time you can put just the issue number here e.g. `#18553`, that's what we do elsewhere in the codebase and a few of us have Emacs/editors set up to jump to GitHub when it finds tags like that

**Review by camsaul — APPROVED** [review]
Awesome, this looks great. I left a note about a line we can remove now but feel free to merge once that's fixed

File: src/metabase/server/middleware/browser_cookie.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/server/middleware/browser_cookie.clj:24]:
```suggestion
```

File: src/metabase/server/middleware/browser_cookie.clj (hunk 2 above)
Comment (camsaul) [reply src/metabase/server/middleware/browser_cookie.clj:19]:
```suggestion
;; SameSite=Lax otherwise. (See #18553)
```

File: src/metabase/server/middleware/session.clj [hunk 3]
```diff
@@ -74,6 +74,7 @@
 (s/defmethod set-session-cookie :normal
   [request response {session-uuid :id} :- {:id (s/cond-pre UUID u/uuid-regex), s/Keyword s/Any}]
   (let [response       (wrap-body-if-needed response)
+        is-https       (request.u/https? request)
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:77]: This is the ultimate nitpick but we use `?` at the end of boolean variable names in the codebase. I know there are different opinions on whether or not to do that in the Clojure world, but the only thing worse than picking one style and sticking with it is mashing a bunch of different styles together.

Comment (camsaul) [reply src/metabase/server/middleware/session.clj:77]:
```suggestion
        is-https?      (request.u/https? request)
```

File: src/metabase/server/middleware/session.clj [hunk 4]
```diff
@@ -89,14 +90,14 @@
...
                         ;; local dev instances) add `Secure` attribute so the cookie is only sent over HTTPS.
-                        (when (request.u/https? request)
-                          {:secure true})
-                        (when (= config/mb-session-cookie-samesite :none)
-                          (log/warn
-                           (str (deferred-trs "Session cookie's SameSite is configured to \"None\", but site is")
-                                (deferred-trs "served over an insecure connection. Some browsers will reject ")
-                                (deferred-trs "cookies under these conditions. ")
-                                (deferred-trs "https://www.chromestatus.com/feature/5633521622188032")))))]
+                        (when is-https
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:93]:
```suggestion
                        (when is-https?
```

File: src/metabase/server/middleware/session.clj [hunk 5]
```diff
@@ -89,14 +90,14 @@
...
+                          {:secure true}))]
+    (when (and (= config/mb-session-cookie-samesite :none) (not is-https))
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:95]:
```suggestion
    (when (and (= config/mb-session-cookie-samesite :none) (not is-https?))
```

File: src/metabase/server/middleware/session.clj [hunk 6]
```diff
@@ -89,14 +90,14 @@
...
+      (log/warn
+       (str (deferred-trs "Session cookie's SameSite is configured to \"None\", but site is")
+            (deferred-trs "served over an insecure connection. Some browsers will reject ")
+            (deferred-trs "cookies under these conditions. ")
+            (deferred-trs "https://www.chromestatus.com/feature/5633521622188032"))))
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:100]: I know you didn't write this stuff and it was like this before your PR, but I noticed it, so we should just fix it while we're at it.

1.  If we're joining a bunch of strings together with `str` to build a long message we need to put whitespace between the parts. This is going to read `but siteis served` because there's no space after `is`
2. `https://www.chromestatus.com/feature/5633521622188032` should **not** be marked for i18n
3. We shouldn't leave whitespace in the i18n strings, because then we'd have to hope the translators leave the whitespace in there in the translated string. I seriously doubt that is going to happen. So it's better just to do the whitespace separately outside of the i18n
4. It's crazy to ask people to translate in fragments of a sentence. How is one supposed to translate `cookies under these conditions.` ? If we're going to break things up at the very least we should try to do it by sentence

```suggestion
       (str (deferred-trs "Session cookie's SameSite is configured to \"None\", but site is served over an insecure connection.")
            " "
            (deferred-trs "Some browsers will reject cookies under these conditions.")
            " "
            "https://www.chromestatus.com/feature/5633521622188032")))
```

Comment (pawit-metabase) [reply src/metabase/server/middleware/session.clj:100]: Shouldn't we combine the two `deferred-trs` so translators have more context and freedom?

Comment (camsaul) [reply src/metabase/server/middleware/session.clj]: The tool we're using doesn't support multi-line i18n forms. This was split up because otherwise the line would be crazy long

**Review by camsaul — APPROVED** [review]
