### PR TITLE
Fix leaving native query editor with parameters

### LINKED ISSUE #52806: Native query params not cleaned from URL after leaving editor
### Describe the bug

https://github.com/user-attachments/assets/a4c3a009-cf7c-43b4-8193-bc30bddd7f36

### To Reproduce

1. New > SQL Query
2. `select {{x}}`
3. Click Metabase logo in page header to go to the index page
4. Confirm when asked to discard your changes

You land on `/?x=` instead of `/`

### Information about your Metabase installation

master, 760f65f7e5a4973d583544cafe26a3d3d14debcf

### Severity

P3

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/52806

The problem was that `SyncedParameterList` updated the URL when parameters change, and without memoization it was done on every render/tick.

Before:
Screenshot 2025-03-07 at 14 23 56

After:
Screenshot 2025-03-07 at 14 23 20

### CODE REVIEW

File: frontend/src/metabase-lib/v1/Question.ts [hunk 1]
```diff
@@ -665,14 +665,18 @@ class Question {
     return question;
   }
 
-  parameters({ collectionPreview } = {}): ParameterObject[] {
+  private _getParameters = _.memoize((collectionPreview: boolean) => {
```
Comment (romeovs) [inline frontend/src/metabase-lib/v1/Question.ts:668]: I think this is dangerous: because `_.memoize` does not receive most of it's values (like `this._parameterValues`) as an argument and so will not be part of `memoize`'s cache key.


I know `this._parameterValues` is never set in the `Question` class but that's not a guarantee.

**Review by romeovs — CHANGES_REQUESTED** [review]

File: frontend/src/metabase-lib/v1/Question.ts (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase-lib/v1/Question.ts:668]: @romeovs `Question` is immutable, we don't need to pass options to memoize.

**Review by romeovs — APPROVED** [review]
