### PR TITLE
Fix dashboard actions linked with filters don't work

### LINKED ISSUE #32974: Query actions won't work when the ID dashboard parameter linked with model ID and action parameter get values from the URL
### Describe the bug

When linking an ID dashboard parameter with a model's ID and a query action's parameter and visiting the dashboard with parameter values in the URL. That action's linked parameter won't be sent with the action execute API request, even though the action form already hides the linked parameter which suggests that the action form is aware of the linked parameter value.

### To Reproduce

1. Create a dashboard
2. Add an ID filter
3. Add a model to the dashboard and link the ID parameter with model's ID field
4. Create an action that utilizes ID because we want to connect this with dashboard ID parameter e.g.
    ```sql
    UPDATE PRODUCTS SET PRICE = 999 WHERE ID = {{ id }}
    ```
5. Add that action to the dashboard and link action's `id` to the dashboard ID parameter.
6. Save the dashboard
7. Execute the action. When creating an action you could have more than 1 parameter, but only `id` is essential to this bug.

The action failed with an error
```
Error executing Action: Cannot run the query: missing required parameters: #{"id"}
```

image

### Workaround

Modifying the dashboard filter in the UI would make the action works.

### Expected behavior

The action is executed successfully.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Mac OS X",
    "os.version": "13.4.1",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-08-03",
      "src_hash": "824184da442e0fb2453a2bdf9d708d379c83339d",
      "tag": "v1.46.7-SNAPSHOT",
      "branch": "backport-dashboard-performance-fixes",
      "hash": "9d49a66"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Not good. Broken actions on dashboards.

### Additional context

<details>
<summary>
Original report
</summary>
Something broke in the Access Request tool.

Nothing about the actions or the dashboard have changed, to my knowledge, but now when someone tries to approve a request, the ID of the request is missing in the network call to the endpoint from the existing filter. What’s weird is when I added a new filter and set the ID (or ID1 in this case) filter manually and then tried to approve with the action form hooked up to that new filter, it worked.

<https://stats.metabase.com/dashboard/982-respond-to-request>

[— from Kyle's Slack Message](https://metaboat.slack.com/archives/C04FG88HL95/p1691155169655959?thread_ts=1691155169.655959&cid=C04FG88HL95)
</details>

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/32974

### Description

This fixes the missing value to pass to a prop `prefetchesInitialValues` from PR: https://github.com/metabase/metabase/pull/32433

### How to verify

Follow the reproduce steps from https://github.com/metabase/metabase/issues/32974

#### Before
image

#### After
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/actions/components/ActionViz/ActionVizForm.tsx [hunk 1]
```diff
@@ -140,7 +140,7 @@ function ActionVizForm({
             action={action}
             mappedParameters={mappedParameters}
             initialValues={initialValues}
-            prefetchesInitialValues
+            prefetchesInitialValues={shouldPrefetch}
```
Comment (WiNloSt) [inline frontend/src/metabase/actions/components/ActionViz/ActionVizForm.tsx:143]: This part of the code is from https://github.com/metabase/metabase/pull/32671 (which comes after #32433), which is a bit weird because `git bisect` pointed out that https://github.com/metabase/metabase/pull/32433 caused it.

But in https://github.com/metabase/metabase/pull/32671, you could see that we [missed passing `shouldPrefetch` to `prefetchesInitialValues`](https://github.com/metabase/metabase/pull/32671/files#diff-00ad554d2261a533d6f01fbc893c58e0099c9d9ce29ca7d1242d8631facac1bcR143), which caused the bug. That's why I was confused about how https://github.com/metabase/metabase/pull/32433 introduced the bug in the first place.

File: e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js [hunk 2]
```diff
@@ -0,0 +1,170 @@
...
+};
+
+const MODEL_DETAILS = {
+  name: "Products model",
+  query: { "source-table": PRODUCTS_ID },
+  database: SAMPLE_DB_ID,
+  dataset: true,
+};
+
+const QUERY_ACTION = {
```
Comment (WiNloSt) [inline e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js:49]: I try to replicate the data as close as possible when we create an action via API, so we don't have to create actions through the UI which would slow down the test.

File: e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js [hunk 3]
```diff
@@ -0,0 +1,170 @@
...
+  );
+
+  cy.then(function () {
+    updateDashboardCards({
+      dashboard_id: this.dashboardId,
+      cards: [
+        {
+          card_id: this.modelId,
+          // Map dashboard parameter to PRODUCTS.ID
+          parameter_mappings: [
```
Comment (WiNloSt) [inline e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js:132]: This is where we map a dashboard parameter to a dashcard field.
image

File: e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js [hunk 4]
```diff
@@ -0,0 +1,170 @@
...
+              dataset_query: {},
+              display: "action",
+              name: null,
+              visualization_settings: {},
+            },
+          },
+          size_x: 4,
+          size_y: 1,
+          // Map action's ID parameter to dashboard parameter
+          parameter_mappings: [
```
Comment (WiNloSt) [inline e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js:157]: This is where we map an action parameter to a dashboard parameter
image

File: e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js [hunk 5]
```diff
@@ -0,0 +1,170 @@
...
+
+const QUERY_ACTION = {
+  name: "Query action",
+  type: "query",
+  parameters: [ID_ACTION_PARAMETER],
+  database_id: SAMPLE_DB_ID,
+  dataset_query: {
+    type: "native",
+    native: {
+      query: `UPDATE ${TEST_TABLE} SET PRICE = 999 WHERE ID = {{ ${ID_ACTION_PARAMETER.slug} }}`,
```
Comment (kamilmielnik) [inline e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js:57]: This `999` could be extracted to a constant and then reused in assertions section.

**Review by kamilmielnik — APPROVED** [review]
Looks & works well :+1:

File: e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js (hunk 5 above)
Comment (WiNloSt) [reply e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js]: Fixed in https://github.com/metabase/metabase/pull/33034/commits/76bedb3f863baa5379e7f83e5d6e6bb01741cf24
