### PR TITLE
Fix sorting on aggregate columns

### LINKED ISSUE #62885: Sorting on an aggregated column does not work
### Describe the bug

See https://metaboat.slack.com/archives/C05NXACAG1G/p1756401313918389

### To Reproduce

- New -> Question -> Products
- Aggregation -> Count, Sum of Price, Sum of Rating
- Breakout -> Category
- Order by -> Sum of Rating
- Visualize
- See that `Sum of Rating` is actually not sorted

Image

Image

### Expected behavior

Order-by on aggregation columns should work.

### Logs

_No response_

### Information about your Metabase installation

stats, `2c8296b`; master-only issue. Does not repro on v56.

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #62885

### CODE REVIEW

File: src/metabase/driver/sql/query_processor.clj [hunk 1]
```diff
@@ -1282,13 +1282,15 @@
 ;;  aggregation REFERENCE e.g. the ["aggregation" 0] fields we allow in order-by
 (defmethod ->honeysql [:sql :aggregation]
   [driver [_ index]]
-  (driver-api/match-one
-    (nth (:aggregation *inner-query*) index)
+  (driver-api/match-one (nth (:aggregation *inner-query*) index)
+    [:aggregation-options ag (options :guard driver-api/qp.add.source-alias)]
+    (->honeysql driver (h2x/identifier :field-alias (driver-api/qp.add.source-alias options)))
```
Comment (camsaul) [inline src/metabase/driver/sql/query_processor.clj:1287]: Drivers are supposed to use the `driver-api/qp.add.*` keys when generating native queries, not stuff like `:name` (which is not necessarily deduplicated/escaped/etc. so this was the root cause of the bug

**Review by galdre — APPROVED** [review]
