### PR TITLE
fix(sdk): support React 17 backwards compatibility

### LINKED ISSUE #45713: Embedding sdk throws a runtime error when used with React 17
The embedding sdk currently throws a runtime error when rendering the `MetabaseProvider` with React 17. We should troubleshoot and fix this, so they are compatible with both React 17 and 18.

```
o is not a function
TypeError: o is not a function
    at t.useSyncExternalStoreWithSelector (http://localhost:3004/static/js/vendors-node_modules_metabase_embedding-sdk-react_dist_main_bundle_js.chunk.js:202565:19)
    at n (http://localhost:3004/static/js/vendors-node_modules_metabase_embedding-sdk-react_dist_main_bundle_js.chunk.js:217237:23)
    at e73 (http://localhost:3004/static/js/vendors-node_modules_metabase_embedding-sdk-react_dist_main_bundle_js.chunk.js:348614:25)
    at renderWithHooks (http://localhost:3004/static/js/bundle.js:19125:22)
    at mountIndeterminateComponent (http://localhost:3004/static/js/bundle.js:21608:17)
    at beginWork (http://localhost:3004/static/js/bundle.js:22661:20)
    at HTMLUnknownElement.callCallback (http://localhost:3004/static/js/bundle.js:9702:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3004/static/js/bundle.js:9746:20)
    at invokeGuardedCallback (http://localhost:3004/static/js/bundle.js:9801:35)
    at beginWork$1 (http://localhost:3004/static/js/bundle.js:26792:11)
    at performUnitOfWork (http://localhost:3004/static/js/bundle.js:25803:16)
    at workLoopSync (http://localhost:3004/static/js/bundle.js:25748:9)
    at renderRootSync (http://localhost:3004/static/js/bundle.js:25718:11)
    at performSyncWorkOnRoot (http://localhost:3004/static/js/bundle.js:25388:22)
    at http://localhost:3004/static/js/bundle.js:16082:30
    at unstable_runWithPriority (http://localhost:3004/static/js/bundle.js:33626:16)
    at runWithPriority$1 (http://localhost:3004/static/js/bundle.js:16036:14)
    at flushSyncCallbackQueueImpl (http://localhost:3004/static/js/bundle.js:16078:13)
    at flushSyncCallbackQueue (http://localhost:3004/static/js/bundle.js:16067:7)
    at scheduleUpdateOnFiber (http://localhost:3004/static/js/bundle.js:25039:13)
```

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/45713

### Description

Dropping support for React 17 means that most of the SDK customers can't use the SDK. The incompatibility with React 17 is caused by:

- [Upgrading react-redux to v9](https://github.com/metabase/metabase/pull/44339) - it uses useSyncExternalStore without any compatibility shims, which is only available in React 18. RTK 2.0 seems to [require](https://redux.js.org/usage/migrations/migrating-rtk-2) react-redux v9. We need to monkey-patch `React.useSyncExternalStore` so that it works for React 17.
- Use of `createRoot` in `TableInteractive`, which is not supported in React 17
- Back button crashing because of it not returning `null`

### How to verify

- Setup a test application using React 17 and the Embedding SDK
  - Alternatively, you could use the `test-react-17` branch of Shoppy (shown in the demo video below), but the CSS are pretty broken because of downgrading from Mantine v7 to Mantine v6. This is an issue with Shoppy's use of Mantine v7, not with the SDK.
- The SDK should still work fine. Try the following code paths:
  - Static Questions
  - Interactive Questions
  - Drill Downs to Interactive Questions (tables) 
  - Interactive Dashboards

### Demo

<div>
    <a href="https://www.loom.com/share/c30f61fbc94d42d5ae975a15446f022f">
      <p>React 17 backwards compatibility - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/c30f61fbc94d42d5ae975a15446f022f">
      
    </a>
  </div>

### Notes

- Will add sanity checks specifically for React 17 in a separate PR (see https://github.com/metabase/metabase/issues/45714), it'll take time to setup though.

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/lib/polyfill-use-sync-external-store.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import React from "react";
+import { useSyncExternalStore } from "use-sync-external-store/shim";
+
+// Monkey-patches useSyncExternalStore if we are in React 17,
+// where useSyncExternalStore is not available.
+// This is used in react-redux v8, until they've dropped the shim in v9.
+if (!("useSyncExternalStore" in React)) {
+  // @ts-expect-error - we're patching for React 17, which doesn't have this method.
+  React.useSyncExternalStore = useSyncExternalStore;
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/lib/polyfill-use-sync-external-store.ts:9]: Unfortunately this needs to be a global monkey-patch, as we can't monkey-patch a built CJS bundle in the SDK user's environment. This is less error-prone than that as well. Luckily, the `useSyncExternalStore` shim here is officially provided by the React team, so it's 100% standard.

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/BackButton.tsx [hunk 2]
```diff
@@ -5,7 +5,9 @@ import { useInteractiveQuestionContext } from "../context";
 export const BackButton = () => {
   const { onNavigateBack } = useInteractiveQuestionContext();
 
-  return (
-    onNavigateBack && <DashboardBackButton noLink onClick={onNavigateBack} />
-  );
+  if (!onNavigateBack) {
+    return null;
+  }
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/BackButton.tsx:10]: For some reason, this caused the back button to crash in React 17. Is this because the `onNavigate` back line coalesces to non-null values?

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/BackButton.tsx [hunk 3]
```diff
@@ -5,7 +5,9 @@ import { useInteractiveQuestionContext } from "../context";
 export const BackButton = () => {
   const { onNavigateBack } = useInteractiveQuestionContext();
 
-  return (
-    onNavigateBack && <DashboardBackButton noLink onClick={onNavigateBack} />
-  );
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/BackButton.tsx:10]: For some reason, this caused the back button to crash in React 17. Is this because the onNavigate back line coalesces to non-null values?

File: frontend/src/metabase/lib/react-compat.ts [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+export function renderRoot(
+  content: React.JSX.Element,
+  element: Element,
+): Root | undefined {
+  if (isReact17OrEarlier()) {
+    ReactDOM.render(content, element);
+    return;
+  }
+
+  const root = createRoot(element);
```
Comment (heypoom) [inline frontend/src/metabase/lib/react-compat.ts:32]: Using `typeof createRoot === "function"` does not work, as that somehow also returns "true" even in React 17. Using `isReact17OrEarlier` seems to be the most reliable.

Comment (ranquild) [reply frontend/src/metabase/lib/react-compat.ts:32]: should we use the same shim check? That the hook exists. Instead of this

Comment (heypoom) [reply frontend/src/metabase/lib/react-compat.ts:32]: @ranquild This `renderRoot` is for a separate issue though, not related to the `useSyncExternalStore` hook - we already use `createRoot` in `TableInteractive`. Not sure what you exactly mean by checking if the hook exists.

Comment (ranquild) [reply frontend/src/metabase/lib/react-compat.ts:32]: I mean, if you want to check if it's React 18, you can check for the hook

Comment (heypoom) [reply frontend/src/metabase/lib/react-compat.ts:32]: @ranquild Oh right, `!("useSyncExternalStore" in React)` - good call!

**Review by ranquild — APPROVED** [review]

**Review by deniskaber — APPROVED** [review]
