### PR TITLE
Fix sqlserver does not respect `start-of-week` when bucket by `week`

### LINKED ISSUE #4910: "Week of Year" and "Week" differs
- Your browser and the version: Chrome 57.0
- Your databases: Redshift
- Metabase version: 0.23.1
- Metabase internal database: Postgres

I followed several issue discussions 
https://github.com/metabase/metabase/issues/1987
https://github.com/metabase/metabase/issues/1635
https://github.com/metabase/metabase/issues/1779
http://discourse.metabase.com/t/how-are-mysql-dates-queried-for-this-week-and-last-week/185/2

It seems at some point "add 1 day" solution was added. When I do Group By "Week of Year" in the Question interface the produced SQL expression is as follows:
`CAST(extract(week from (<datecolumn> + INTERVAL '1 day')) AS integer) AS "date"` 
What is the reason for this add 1 day? It doesn't make sense as it means that the week number is returned for following day and not current day. 
Similarly Day of Week produces `(CAST(extract(dow from <datecolumn>) AS integer) + 1) AS "date"` which adds 1 again.
`select CAST(extract(dow from '2017-04-28'::date) AS integer)` returns 5 
but above expression returns 6. Again Sunday based but seems to be forced/hacked way of setting date. 

I feel like ISO standards define the timezone, timestamp and calendar definitions pretty clearly and are fundamental concepts expected to be consistent during any analysis. Why not use the source database defaults? Why try to hack standards like calendars and times?

### LINKED ISSUE #25356: "Week" aggregation is inconsistent with setting "Start-of-the-week: Monday"
**Describe the bug**
Aggregation by "Week" is inconsistent with setting "Start-of-the-week: Monday". 
The UI shows correct week buckets but the data aggregation is still "Sunday to saturday".

**Logs**
Not relevant (I think)

**To Reproduce**
1. Select Monday as Start of the week in Admin settings.
2. Aggregate data on "Week"
3. Find data belonging to previous week in current week

**Expected behavior**
Data from 11th Sep not be included in the Sep 12, 2022 – Sep 18, 2022 bucket.

Image A: with data up to 11th September when aggregated "Daily". 
Image B: When aggregation set to "Week", bucket is correctly showing Sep 12, 2022 – Sep 18, 2022, however, data from Sep 11, 2022 is included.

**Screenshots**
Image A:
image

Image B:
image

**Information about your Metabase Installation:**
Metabase 0.44.2
First-day-of-week: Monday
Database connection: SQL Server in Azure Synapse

You can get this information by going to Admin -> Troubleshooting.

`{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "4.15.0-169-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.6.47.0"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-08-31",
      "tag": "v0.44.2",
      "branch": "release-x.44.x",
      "hash": "8d9de8a"
    },
    "settings": {
      "report-timezone": "Europe/Stockholm"
    }
  }
}`

**Severity**
Annoying for operation Dashboards based on weekly aggregation, especially comparing weeks using Trend visualization.

**Additional context**

### PR DESCRIPTION
**Pull request by qnkhuat**
- Add tests to check when bucketing by week and week-of-year behave consistently, Closes #4910
- While doing the above, found that sqlserver does not respect `start-of-week` setting, so fix that. Fix #25356

### CODE REVIEW

**Review by metamben — APPROVED** [review]
LGTM

**Comment by qnkhuat** [comment]
@metamben I added some changes to the sqlserver because tests were failing for it. would you mind doing another review?

File: test/metabase/query_processor_test/date_time_zone_functions_test.clj [hunk 1]
```diff
@@ -163,12 +163,6 @@
         (testing title
           (is (= expected (test-temporal-extract query))))))))
 
-(defmacro with-start-of-week
-  "With start of week."
```
Comment (camsaul) [inline test/metabase/query_processor_test/date_time_zone_functions_test.clj:167]: Who wrote that old docstring 💀

File: test/metabase/test/util.clj [hunk 2]
```diff
@@ -1186,3 +1186,9 @@
       (if (neg? @a)
         (apply f args)
         (throw (ex-info "Not yet" {:remaining @a}))))))
+
+(defmacro with-start-of-week
+  "Executes the body with `start-of-week` temporarily changed."
+  [start-of-week & body]
+  `(mt/with-temporary-setting-values [start-of-week ~start-of-week]
+     ~@body))
```
Comment (camsaul) [inline test/metabase/test/util.clj:1194]: Does this **really** need to be a macro, vs. just using `with-temporary-setting-values` directly? It doesn't save any lines of code... if you follow it to the logical extreme, why don't we have a separate `with-x` macro for every single Setting `x`? Because that would be crazy, right?

I think `with-temporary-setting-values` is actually a little clearer actually because it's clear you're changing a Setting as opposed to some system property or whatever.

Just my two cents

File: test/metabase/test/util.clj [hunk 3]
```diff
@@ -1186,3 +1186,9 @@
       (if (neg? @a)
         (apply f args)
         (throw (ex-info "Not yet" {:remaining @a}))))))
+
+(defmacro with-start-of-week
+  "Executes the body with `start-of-week` temporarily changed."
```
Comment (camsaul) [inline test/metabase/test/util.clj:1191]: Thank you for writing a better docstring tho. The old one was... not so helpful

File: test/metabase/query_processor_test/date_bucketing_test.clj [hunk 4]
```diff
@@ -724,6 +724,25 @@
...
+    (mt/test-drivers (mt/normal-drivers)
+      ;; 2019-01-01 is Tuesday, so set start-of-week to tuesday so
+      ;; breakout by week-of-year will have first row is the 1st week of year
+      (mt/with-start-of-week :tuesday
+       (mt/dataset sample-dataset
+         (letfn [(test-break-out [unit] (->> (mt/mbql-query orders
+                                                {:filter      [:between $created_at "2019-01-01" "2019-12-31"]
+                                                 :breakout    [:field $created_at {:temporal-unit unit}]
+                                                 :aggregation [[:count]]})
+                                           mt/process-query
```
Comment (camsaul) [inline test/metabase/query_processor_test/date_bucketing_test.clj:738]: You can use `mt/run-mbql-query` instead of `mt/mbql-query` + `mt/process-query`

File: test/metabase/query_processor_test/date_bucketing_test.clj [hunk 5]
```diff
@@ -724,6 +724,25 @@
...
+                                           (mt/formatted-rows [str int])
+                                           (map second)))]
```
Comment (camsaul) [inline test/metabase/query_processor_test/date_bucketing_test.clj:740]: Why are you removing the week from the results... isn't that an important thing to check? That the week value coming back is correct?

File: test/metabase/query_processor_test/date_bucketing_test.clj [hunk 6]
```diff
@@ -724,6 +724,25 @@
...
+          (is (= (test-break-out :week)
+                 (test-break-out :week-of-year)))
```
Comment (camsaul) [inline test/metabase/query_processor_test/date_bucketing_test.clj:742]: I was very confused at why these were supposed to be equal but then I realized you're only looking at the counts and not the actual values

**Review by camsaul — APPROVED** [review]
This looks good to me, I would like it better if the test included the actual `:week`/`:week-of-year` as well. I left a few notes besides that. But those are all suggestions so change them if you agree and then feel free to hit merge. You don't need to ping me for another review

File: test/metabase/query_processor_test/date_bucketing_test.clj (hunk 5 above)
Comment (camsaul) [reply test/metabase/query_processor_test/date_bucketing_test.clj]: I guess it wasn't important to check =(

Comment (qnkhuat) [reply test/metabase/query_processor_test/date_bucketing_test.clj]: https://github.com/metabase/metabase/pull/26474/files

I did add them. or did you mean sth else?
