### PR TITLE
Test to prove #28060 is fixed :wrench:

### LINKED ISSUE #28060: Output of fk-metadata does not match schema
**Describe the bug**
I get this exception in the log.

**Logs**

```
[85045365-d324-4467-857b-57325bde7bfd] 2023-02-03T16:50:16+01:00 WARN metabase.sync.util Error syncing FKs for Table 250 'XXXprivate'
clojure.lang.ExceptionInfo: Output of fk-metadata does not match schema: 
	   #{{:dest-table {:name (not (instance? java.lang.String nil))}, :dest-column-name (not (instance? java.lang.String nil))}}  
 {:type :schema.core/error, :schema (maybe #{{:fk-column-name (constrained Str "Non-blank string"), :dest-table {:name (constrained Str "Non-blank string"), :schema (maybe (constrained Str "Non-blank string"))}, :dest-column-name (constrained Str "Non-blank string")}}), :value #{{:fk-column-name "FK_XXX", :dest-table {:name nil, :schema nil}, :dest-column-name nil} {:fk-column-name "FK_XXX", :dest-table {:name "XXX", :schema nil}, :dest-column-name "ID_XXX"}}, :error #{{:dest-table {:name (not (instance? java.lang.String nil))}, :dest-column-name (not (instance? java.lang.String nil))}}}
```

**To Reproduce**
The ID_XXX and FK_XXX columns have the type BIGINT(20) unsigned.

**Expected behavior**
No exception in logs

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your databases: AWS Mysql
- Metabase version: v0.45.2.1
- Metabase hosting environment: AWS ECS
- Metabase internal database: Postgres

**Severity**
Not sure, there are some noticable issues in metabase. Not sure if that is beacuse of this.

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #28060
Fixes QUE2-334

Also a little bit of MySQL driver code cleanup

Fixes [QUE2-428](https://linear.app/metabase/issue/QUE2-428)

### CODE REVIEW

File: src/metabase/driver/mysql.clj [hunk 1]
```diff
@@ -120,24 +111,40 @@
...
   [db]
   (= "MySQL"
      (if-let [conn (:connection db)]
-       (->> ^java.sql.Connection conn .getMetaData .getDatabaseProductName)
-       (-> db :dbms_version :flavor))))
+       (connection-flavor conn)
+       (database-flavor db))))
 
-(defn mariadb-connection?
+(mu/defn- mariadb-connection?
```
Comment (metamben) [inline src/metabase/driver/mysql.clj]:
```suggestion
(mu/defn- mariadb-connection?  :- :boolean
```

File: src/metabase/driver/mysql.clj [hunk 2]
```diff
@@ -218,14 +225,15 @@
...
 
 (defmethod sql-jdbc.sync/current-user-table-privileges :mysql
-  [driver conn & {:as _options}]
+  [_driver conn-spec & {:as _options}]
   ;; MariaDB doesn't allow users to query the privileges of roles a user might have (unless they have select privileges
   ;; for the mysql database), so we can't query the full privileges of the current user.
-  (when-not (mariadb-connection? driver conn)
-    (let [sql->tuples (fn [sql] (drop 1 (jdbc/query conn sql {:as-arrays? true})))
+  (when-not (when-let [conn (:connection conn-spec)]
+              (mariadb-connection? conn))
```
Comment (metamben) [inline src/metabase/driver/mysql.clj]:
```suggestion
  (when-not (some-> conn-spec :connection mariadb-connection?)]
```

**Review by metamben — APPROVED** [review]
LGTM
