### PR TITLE
Make reindex! an async call

### LINKED ISSUE #62308: serialization load does a blocking search reindex
### Describe the bug

https://github.com/metabase/metabase/pull/61053/files

```
(defn load-metabase!
  "Loads in a database export from an ingestion source, which is any Ingestable instance."
  [ingestion & {:keys [backfill? continue-on-error]
                :or   {backfill?         true
                       continue-on-error false}}]
  (u/prog1
    (t2/with-transaction [_tx]
      ;; We proceed in the arbitrary order of ingest-list, deserializing all the files. Their declared dependencies
      ;; guide the import, and make sure all containers are imported before contents, etc.
      (when backfill?
        (serdes.backfill/backfill-ids!))
      (let [contents (serdes.ingest/ingest-list ingestion)
            ctx      {:expanding #{}
                      :seen      #{}
                      :circular  #{}
                      :ingestion ingestion
                      :from-ids  (m/index-by :id contents)
                      :errors    []}]
        (log/infof "Starting deserialization, total %s documents" (count contents))
        (reduce (fn [ctx item]
                  (try
                    (load-one! ctx item)
                    (catch Exception e
                      (when-not continue-on-error
                        (throw e))
                      ;; eschew big and scary stacktrace
                      (log/warnf (u/strip-error e "Skipping deserialization error"))
                      (update ctx :errors conj e))))
                ctx
                contents)))
    ;; Hack: the transaction above typically takes much longer than our delay on the search indexing queue.
    ;;       this means that the corresponding entries would have been missing or stale when we indexed them.
    ;;       ideally, we would delay the indexing somehow, or only reindex what we've loaded.
    ;;       while we're figuring that out, here's a crude stopgap.
    (search/reindex!)))
```

this wants to update the search index after ingestion. On larger dbs this can run into the minutes. This is a blocking api.

### To Reproduce

at startup, we unconditionally load analytics content. This causes an index reload on startup.

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
56.x, master
```

### Severity

p1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nvoxland**
closes #62308
### Description

Don't block on `reindex!`, since it's called by `enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj` on startup which blocks initialization

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/search/core.clj [hunk 1]
```diff
@@ -115,27 +115,32 @@
...
-        (prometheus/observe! :metabase-search/index-reindex-duration-ms duration)
-        (doseq [[model cnt] report]
-          (analytics/inc! :metabase-search/index-reindexes {:model model} cnt))
-        (log/infof "Done reindexing in %.0fms %s" duration (sort-by (comp - val) report))
-        report)
-      (catch Exception e
-        (analytics/inc! :metabase-search/index-error)
-        (throw e)))))
+  (cond->
+   (future
```
Comment (crisptrutski) [inline src/metabase/search/core.clj]: On smaller machines the future thread pool can be very small, so I don't think it's OK to use a future for something that can take 10s of minutes.

File: src/metabase/search/task/search_index.clj [hunk 2]
```diff
@@ -40,10 +39,10 @@
 (task/defjob ^{DisallowConcurrentExecution true
                :doc                        "Populate a new Search Index"}
   SearchIndexReindex [_ctx]
-  (search/reindex!))
+  @(search/reindex!))
 
 (defmethod startup/def-startup-logic! ::SearchIndexInit [_]
-  (quick-task/submit-task! init!))
+  (future init!))
```
Comment (crisptrutski) [inline src/metabase/search/task/search_index.clj]: Ditto

**Review by crisptrutski — COMMENTED** [review]
Turning off reindexing in the tests is nice, wonder how much time that was sapping in CI.

Might save a bunch of boilerplate and git noise to use a fixture instead? Could use a dynamic var turn reindexing back on for the one test that sort-of relies on it (typically passes anyway). It's worth overriding it anyway for that test so we get a handle to block on.

File: enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj [hunk 3]
```diff
@@ -44,302 +45,307 @@
...
-
-        (testing "loading into an empty database succeeds"
-          (ts/with-db dest-db
-            (serdes.load/load-metabase! (ingestion-in-memory @serialized))
-            ;; the trash is serialized and loaded, so restrict to nil type
-            (let [colls (t2/select :model/Collection :type nil)]
-              (is (= 1 (count colls)))
-              (is (= "Basic Collection" (:name (first colls))))
-              (is (= eid1               (:entity_id (first colls)))))))
+  (with-redefs [search/reindex! (constantly nil)]
```
Comment (crisptrutski) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj]: We need a linter for this, but tests should always use `mt/with-dynamic-fn-redefs` instead, which makes it thread safe.

File: src/metabase/search/core.clj (hunk 1 above)
Comment (crisptrutski) [reply src/metabase/search/core.clj]: The best solution I think is to create an executor for reindexing:

```clojure
(defonce task-executor
  (java.util.concurrent.ThreadPoolExecutor.
   1 1 0 java.util.concurrent.TimeUnit/MILLISECONDS
   (java.util.concurrent.ArrayBlockingQueue. 1)
   (java.util.concurrent.ThreadPoolExecutor$DiscardPolicy.)))
```

This not only stops us from performing concurrent reindexing on the same host, it also makes sure we don't queue up more than "one more after the current one".

File: src/metabase/search/task/search_index.clj (hunk 2 above)
Comment (crisptrutski) [reply src/metabase/search/task/search_index.clj]: I think just `(doto (Thread. (fn [] ...)) .start)` is good for this one.

File: src/metabase/search/core.clj [hunk 4]
```diff
@@ -114,28 +117,41 @@
...
-        (analytics/inc! :metabase-search/index-reindex-ms duration)
-        (prometheus/observe! :metabase-search/index-reindex-duration-ms duration)
-        (doseq [[model cnt] report]
-          (analytics/inc! :metabase-search/index-reindexes {:model model} cnt))
-        (log/infof "Done reindexing in %.0fms %s" duration (sort-by (comp - val) report))
-        report)
-      (catch Exception e
-        (analytics/inc! :metabase-search/index-error)
-        (throw e)))))
+  (let [logic (fn [] (when (supports-index?)
```
Comment (crisptrutski) [inline src/metabase/search/core.clj]: A private helper function would be a bit nicer than such a big lambda IMHO

File: src/metabase/search/task/search_index.clj [hunk 5]
```diff
@@ -40,10 +40,10 @@
 (task/defjob ^{DisallowConcurrentExecution true
                :doc                        "Populate a new Search Index"}
   SearchIndexReindex [_ctx]
-  (search/reindex!))
+  (.get ^Future (search/reindex!)))
```
Comment (crisptrutski) [inline src/metabase/search/task/search_index.clj]: TIL that you can just deref Future (`@java-future`) - is there a reason you're using interop instead?

**Review by crisptrutski — APPROVED** [review]
LGTM besides the interop instead of `@`

File: src/metabase/search/core.clj [hunk 6]
```diff
@@ -114,28 +117,41 @@
...
+                           (doseq [[model cnt] report]
+                             (analytics/inc! :metabase-search/index-reindexes {:model model} cnt))
+                           (log/infof "Done reindexing in %.0fms %s" duration (sort-by (comp - val) report))
+                           report)
+                         (catch Exception e
+                           (analytics/inc! :metabase-search/index-error)
+                           (throw e)))))]
+    (if (or search.ingestion/*force-sync* async?)
+      (let [result (logic)]
+        (future result))
```
Comment (crisptrutski) [inline src/metabase/search/core.clj]: nit: it would be a bit nicer to just return a promise here, so we don't even run the constant on a background thread.

Comment (crisptrutski) [reply src/metabase/search/core.clj]: I think this is the easiest incanation: `(doto (promise) (deliver result))`

File: src/metabase/search/core.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/search/core.clj]: this threadpool is a cached thread pool which is unbounded:

in clojure.core
```clojure
(defn future-call 
  [f]
  (let [f (binding-conveyor-fn f)
        fut (.submit clojure.lang.Agent/soloExecutor ^Callable f)]
    (reify  ...)

(defmacro future
  [& body] `(future-call (^{:once true} fn* [] ~@body)))
```

in agent.java:
```java
    public static volatile ExecutorService soloExecutor = Executors.newCachedThreadPool((ThreadFactory)Agent.createThreadFactory("clojure-agent-send-off-pool-%d", sendOffThreadPoolCounter));
```

i think it will be fine, no?

File: src/metabase/search/task/search_index.clj (hunk 2 above)
Comment (dpsutton) [reply src/metabase/search/task/search_index.clj]: if this is in a future it needs to be `(future (init!))`

**Review by dpsutton — DISMISSED** [review]
`(future init!)` will not run the init! function.

File: src/metabase/search/core.clj [hunk 7]
```diff
@@ -122,11 +122,9 @@
    1 ; pool size
    1 ; max pool size
    0 TimeUnit/MILLISECONDS ; keepalive
-   (ArrayBlockingQueue. 1)
-   (ThreadPoolExecutor$DiscardPolicy.)))
```
Comment (crisptrutski) [inline src/metabase/search/core.clj]: Why remove the discard policy?

The idea was that the "next-one-after-the-current-one-continues" is good enough both the goose and the gander.

File: src/metabase/search/api.clj [hunk 8]
```diff
@@ -80,11 +80,7 @@
   []
   (api/check-superuser)
   (if (search/supports-index?)
-    ;; The job appears to wait on the main thread when run from tests, so, unfortunately, testing this branch is hard.
-    (if (and (task/job-exists? task.search-index/reindex-job-key) (or (not ingestion/*force-sync*) config/is-test?))
-      (do (task/trigger-now! task.search-index/reindex-job-key) {:message "task triggered"})
-      (do (search/reindex! {:async? false}) {:message "done"}))
```
Comment (crisptrutski) [inline src/metabase/search/api.clj]: Reason for removing this? Nice to have the extra job telemetry if doing this in a dev or staging env.

File: src/metabase/search/api.clj [hunk 9]
```diff
@@ -80,11 +80,7 @@
...
-
+    (do (search/reindex!) {:message "done"})
```
Comment (crisptrutski) [inline src/metabase/search/api.clj]: Message is misleading, since it's happening async now.

Also for staging environments I think it's better to keep triggering the job, which avoids clobbering and improves telemetry.

File: src/metabase/search/core.clj (hunk 7 above)
Comment (crisptrutski) [inline src/metabase/search/core.clj]: Repeating comment, because not sure the one I left on the diff will be seen.

Why remove the discard policy? The point is that is N processes trigger a reindex while another one is running, they'll all be satisfied by the next one. It doesn't make sense to throw an error!

File: src/metabase/search/core.clj (hunk 1 above)
Comment (crisptrutski) [reply src/metabase/search/core.clj]: Jeez, wonder where I got the bounded pool idea from. 

So yeah I guess it would be _OK_, but we get nice de-duplication with the custom executor.

File: test/metabase/search/api_test.clj [hunk 10]
```diff
@@ -1590,15 +1592,16 @@
...
-  (testing "Non-models don't get collection_ancestors"
-    (mt/with-temp [:model/Card _ {:name "question"
-                                  :collection_id nil}]
-      (is (not (contains? (->> (mt/user-http-request :rasta :get 200 "search" :model_ancestors true :q "question" :models ["dataset" "card"])
-                               :data
-                               (filter #(= (:name %) "question"))
-                               first
-                               :collection)
-                          :effective_ancestors))))))
+  (search.tu/with-new-search-if-available
```
Comment (crisptrutski) [inline test/metabase/search/api_test.clj]: Missed a spot? Redundant with the fixture I think

**Review by crisptrutski — APPROVED** [review]

File: src/metabase/search/core.clj [hunk 11]
```diff
@@ -137,6 +136,17 @@
...
+(defn reindex!
+  "Populate a new index, and make it active. Simultaneously updates the current index.
+  Returns a future that will complete when the reindexing is done.
+  Respects `search.ingestion/*force-sync*` and waits for the future if it's true.
+  Alternately, if `:async?` is false, it will also run synchronously."
+  [& {:keys [async?] :or {async? true} :as opts}]
+  (let [f #(reindex-logic! opts)]
+    (if (or search.ingestion/*force-sync* (not async?))
+      (doto (promise) (deliver (f)))
+      (future (f)))))
```
Comment (crisptrutski) [inline src/metabase/search/core.clj:148]: Just catching up - we went back to a future so that parallel tests can populate their temp indexes independently?

Comment (nvoxland) [reply src/metabase/search/core.clj:148]: I went back to the future mostly from a code simplicity standpoint. The tests should all be sync on their call to reindex and in the production code it's mostly called from a quartz job except for the serialization load and I wasn't thinking it's worth the extra executor service setup for that usage. 

I think there's some general problems around coordinating things like reindexes to keep them happening only once across the cluster etc which maybe will lead to a different/better solution, but thinking that should be a separate project and just trying to keep this PR code more straghtforward

Comment (crisptrutski) [reply src/metabase/search/core.clj:148]: "Back to the future" 🚗 ⚡
