### PR TITLE
Fix `Metabase` name is still present despite whitelabel name existance

### LINKED ISSUE #17043: With Whitelabel custom name, `Metabase` name is still shown multiple places in Admin Panel
**Describe the bug**
The whitelabel functionality doesn't replace the name `Metabase` everywhere in the Admin Panel.

**To Reproduce**
1. Admin > Settings > Whitelabel > change name to something else - and do a browser refresh
2. Look around in the Admin Panel, there will be many references to `Metabase` instead of the custom name used.
Here are some examples:
image

**Expected behavior**
Change the name references.
There will be some things that cannot be changed (like "Diagnostic Info" attributes, or Troubleshooting Logs, or Slack bot files channel).

**Information about your Metabase Installation:**
All versions thru 1.40.0

**Additional context**
Related to #14994

### PR DESCRIPTION
**Pull request by WiNloSt**
Part of a fix for #17043

### Note
The reason I put everything inside the `t` is that we have a special logic to replace `Metabase` string only when the text is translated.
https://github.com/metabase/metabase/blob/d7223dc05d5b40296c7f58c9b6851e6da45a4e65/enterprise/frontend/src/metabase-enterprise/whitelabel/lib/whitelabel.js#L188-L190

### CODE REVIEW

File: enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSchemeWidget.jsx [hunk 1]
```diff
@@ -83,7 +87,7 @@ const ColorSchemeWidget = ({ setting, onChange }) => {
                 </td>
                 <td>
                   <span className="mx2 text-grey-4">
-                    {properties.description}
+                    {jt`${properties.description}`}
```
Comment (WiNloSt) [inline enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSchemeWidget.jsx:90]: This translates the highlighted text.
image

File: frontend/src/metabase/admin/settings/components/SettingHeader/SettingHeader.jsx [hunk 2]
```diff
@@ -1,19 +1,26 @@
...
+  // only for whitelabel name replacement.
+  // See metabase#17043
+  /* disable ttag */
+  return (
+    <div>
+      <SettingTitle htmlFor={id}>{setting.display_name}</SettingTitle>
+      <SettingDescription>
+        {setting.warningMessage && (
+          <React.Fragment>
+            <strong>{jt`${setting.warningMessage}`}</strong>{" "}
```
Comment (WiNloSt) [inline frontend/src/metabase/admin/settings/components/SettingHeader/SettingHeader.jsx:17]: Something in `setting` is probably a JSX, that's why when I used just `t` these tests failed.
- https://app.circleci.com/pipelines/github/metabase/metabase/33280/workflows/af1c70f4-a5f2-43f9-a952-1bf40ae1bf47/jobs/1715260
- https://app.circleci.com/pipelines/github/metabase/metabase/33280/workflows/af1c70f4-a5f2-43f9-a952-1bf40ae1bf47/jobs/1715201

**Review by ranquild — CHANGES_REQUESTED** [review]
While the fix seems to work, I found it very hard to understand, and I also had to go to `babel-plugin-ttag` docs.

I believe that the root cause is this line https://github.com/metabase/metabase/blob/6978a836dcf03a12328bd53d871513feb242f428/enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSchemeWidget.jsx#L25 and the fact that it's initialized as a module-level constant. Could you try replacing `const COLOR_DISPLAY_PROPERTIES = ` with a function, e.g. `const getColorDisplayProperties = () => ({` and check if it solves the issue? Thanks!

**Comment by WiNloSt** [comment]
@ranquild I reverted everything to master and tried using your suggestion the fix works for just the `ColorSchemeWidget`. Now I understood that there are 2 problems
1. declaring a `const` where it contains `t` won't change the text at runtime. e.g. `locale` changed or `whitelabel` is enabled for example.
2. Any `Metabase` text that's not processed by `ttag` won't change itself to the whitelabeled name this is what I originally write in the comment https://github.com/metabase/metabase/pull/21616#issue-1201894685.

So, for the fix to work I suggest keeping `SettingHeader.jsx` as is (in this PR), and I could use your suggestion for `[ColorSchemeWidget.jsx](https://github.com/metabase/metabase/pull/21616/files#diff-a79d11d3703bb952708d40f446007834e449172d0f9bca5af83f363675a3e52a)`. 

The reason I disabled `ttag` `SettingHeader.jsx` is because I'm wrapping a dynamic value in `ttag` which won't work as we have linter for it that ensure wrapped texts should be static. And I need the settings text to be wrapped within `ttag` since we wrote a plugin that replace every `Metabase` found in any given text wrapped within `ttag`. https://github.com/metabase/metabase/blob/d7223dc05d5b40296c7f58c9b6851e6da45a4e65/enterprise/frontend/src/metabase-enterprise/whitelabel/lib/whitelabel.js#L188-L190 Otherwise, I will need to duplicate `replaceApplicationName` or expose it and call it directly e.g.

```ts
    <SettingDescription>
      {setting.warningMessage && (
        <React.Fragment>
          <strong>{replaceApplicationName(setting.warningMessage)}</strong>{" "}
        </React.Fragment>
      )}
      {replaceApplicationName(setting.description)}
      {setting.note && <div>{replaceApplicationName(setting.note)}</div>}
    </SettingDescription>
``` 

which might still be less ambiguous. What do you think?

**Comment by ranquild** [comment]
@WiNloSt I believe we shouldn't use unprocessed ttag literals as a way to get `Metabase` replaced. Based on my investigation `Metabase` string in settings comes from settings on the backend, like this https://github.com/metabase/metabase/blob/19beda53393ef761ef57ea7dbb5474f6f4d57dd2/src/metabase/public_settings.clj#L58. The fix would be changing `tru` declarations on the backend to use `site-name` setting instead of `Metabase` literal. 

I suggest the following
- Revert changes to `SettingHeader`, leave changes to `ColorSchemeWidget`, and merge this PR
- Fix the backend translation strings in a separate PR on the backend.

WDYT?

**Review by ranquild — CHANGES_REQUESTED** [review]
Comment above

**Comment by WiNloSt** [comment]
@ranquild 

> I suggest the following
> 
> * Revert changes to `SettingHeader`, leave changes to `ColorSchemeWidget`, and merge this PR
> * Fix the backend translation strings in a separate PR on the backend.
> 
> WDYT?

Yeah, I start to think the fix I made is kind of hacky if I were to change the dynamic value from BE. That'd better be done on BE instead.

Sounds good for both points.

**Review by ranquild — APPROVED** [review]

**Comment by WiNloSt** [comment]
I noticed that the unit tests failed. There's a [conversation on Slack about this](https://metaboat.slack.com/archives/C5XHN8GLW/p1651221110690589).
