### PR TITLE
45003 entity picker recents context

### LINKED ISSUE #45003: Recents selection context gets diluted by recently viewed items.
### Describe the bug

> When I open the data picker in the query builder I expect to see in Recents only stuff that I recently picked there, and nothing else.

---

We can achieve this by removing the `context=views` query parameter from the `api/actions/recents` api call used to populate the data picker.

### To Reproduce

1. Have some recent views (you can view them by hitting Cmd+K). Make some recent views by viewing ~5 collections, dashboards, cards, models, and/or tables.
2. New > Question > select something. This is the recent item that you should see as first, next time you open the data-picker.
3. Make some more recent *views* by viewing ~5 collections, dashboards, cards, models, and/or tables.
5. You will see recently _viewed_ items, not ones that you recently picked using the datapicker.

### Expected behavior

We ought to show only recent items that were recently picked there, and either nothing else, or sort the selected items first. 

Currently that view is sorted by timestamp of the most-recent view.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21+35-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21+35-LTS",
    "os.name": "Mac OS X",
    "os.version": "14.3",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "valid-thru": "2025-01-01T12:00:00Z",
    "current-user-count": 4,
    "application-database": "postgres",
    "settings": {
      "report-timezone": null
    },
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.2 (Homebrew)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "databases": [
      "h2",
      "postgres"
    ],
    "max-users": 7,
    "hosting-env": "unknown",
    "run-mode": "dev",
    "version": {
      "date": "2024-06-27",
      "tag": "v1.2.0-SNAPSHOT",
      "hash": "2d911b9"
    },
  }
}
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/45003

### Description
PR changes the request that the data picker makes to fetch recents, but also moves the selection logging to the individual pickers so that it works for both picker modals with and without confirmation buttons.

### How to verify
1. New question -> Sample Dataset -> Pick a table
2. Re-open the data picker, and you should see the table you just picked in the recents tab of the data picker

### Demo
chrome_LfFKEElMXW

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/test/__support__/server-mocks/activity.ts [hunk 1]
```diff
@@ -10,14 +10,13 @@ export function setupRecentViewsEndpoints(recentItems: RecentItem[]) {
 
 export function setupRecentViewsAndSelectionsEndpoints(
   recentItems: RecentItem[],
+  context: string = "context=selections&context=views",
```
Comment (kamilmielnik) [inline frontend/test/__support__/server-mocks/activity.ts:13]: Right now this argument is a _query_, not a _context_.

It'd be great if this function accepted `context: RecentContexts[]` and used `querystring` to generate the URL for us.

```suggestion
  context: RecentContexts[] = ["selections", "views"],
```

File: frontend/src/metabase/common/components/EntityPicker/hooks/use-log-recent-item.tsx [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+import type { CollectionPickerItem } from "../../CollectionPicker";
+import type { NotebookDataPickerValueItem } from "../../DataPicker";
+
+export const useLogRecentItem = () => {
+  const [logRecentItem] = useLogRecentItemMutation();
+
+  const handleLogRecentItem = useCallback(
+    (item: CollectionPickerItem | NotebookDataPickerValueItem) => {
+      if (item && isLoggableActivityModel(item)) {
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/components/EntityPicker/hooks/use-log-recent-item.tsx:14]:
```suggestion
      if (isLoggableActivityModel(item)) {
```

File: frontend/src/metabase/common/components/EntityPicker/hooks/use-log-recent-item.tsx [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+          model_id: item.id,
+          model: item.model,
+        });
+      }
+    },
+    [logRecentItem],
+  );
+
+  return {
+    handleLogRecentItem,
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/components/EntityPicker/hooks/use-log-recent-item.tsx:25]: It's unusual for a hook to return a function prefixed with `handle`.

How about `tryLogRecentItem`?

File: frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx [hunk 4]
```diff
@@ -68,15 +79,15 @@ export const CollectionPickerModal = ({
       if (options.hasConfirmButtons) {
         setSelectedItem(item);
       } else if (canSelectItem(item)) {
-        await onChange(item);
+        await handleChange(item);
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx:82]: :thinking: 

If this `await` (and the one in `handleConfirm`) is correct then `handleChange` is incorrect (it'd need to be `async` and `await onChange(item)`).

But it looks like the `await` is incorrect - let's remove it.
Also [`MoveModal`](https://github.com/metabase/metabase/blob/8f8a3351b46b3439e62d83c937ae0b740dfad7e7/frontend/src/metabase/containers/MoveModal.tsx#L71) and [`MoveTimelineModal`](https://github.com/metabase/metabase/blob/7ce866130efaa1a331932d3c5cbbf4f3559898b3/frontend/src/metabase/timelines/common/components/MoveTimelineModal/MoveTimelineModal.tsx#L36-L38) should not use `async/await` when passing `onChange` to `CollectionPickerModal`.

Comment (npfitz) [reply frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx:82]: Good catch!

File: frontend/src/metabase/containers/MoveModal.tsx [hunk 5]
```diff
@@ -68,7 +68,7 @@ export const MoveModal = ({
         id: initialCollectionId,
         model: "collection",
       }}
-      onChange={async newCollection => await onMove({ id: newCollection.id })}
+      onChange={newCollection => onMove({ id: newCollection.id })}
```
Comment (iethree) [inline frontend/src/metabase/containers/MoveModal.tsx:71]: i think errors in the move modal will not propagate properly if we remove this `await`

#40700

File: frontend/src/metabase/timelines/common/components/MoveTimelineModal/MoveTimelineModal.tsx [hunk 6]
```diff
@@ -33,8 +33,8 @@ const MoveTimelineModal = ({
       value={{ id: timeline.collection_id ?? "root", model: "collection" }}
       title={t`Move ${getTimelineName(timeline)}`}
       onClose={onClose}
-      onChange={async newCollection => {
-        await handleSubmit(newCollection.id);
+      onChange={newCollection => {
+        handleSubmit(newCollection.id);
```
Comment (iethree) [inline frontend/src/metabase/timelines/common/components/MoveTimelineModal/MoveTimelineModal.tsx:37]: I think this will also prevent error propagation. we want this to throw.

#40700

**Review by iethree — CHANGES_REQUESTED** [review]
Looks good! 

Can you revert the `await` changes though? I figured out why those were there.

**Comment by iethree** [comment]
One more thing, it looks like this isn't working for questions and models

https://www.loom.com/share/74b369c3280a42d3929faf110d5381fc

Seems that your new handleOnChange functions aren't called for non-confirm-button selections in those pickers. I think we need to conditionally log in `handleItemSelect` if the item is a question or a model

**Comment by iethree** [comment]
this looks good, but I think this is blocked by the backend [model/dataset mixup](https://metaboat.slack.com/archives/C064EB1UE5P/p1722519098893339) 🥴

**Review by iethree — APPROVED** [review]
🫶
