### PR TITLE
Keep field-values for detail-only fields

### LINKED ISSUE #10851: Search suggest for "Detail view" field not working
## Bug description

When field visibility is set to "Only in detail views" the search box mode "List of all values" does not work. It just shows simple textfield without any suggest feature. See below:

**Field settings**

image

**Filter box**

image

## Metabase version

[https://github.com/metabase/metabase/commit/bf3b25a6b7a2e1460f895033b900f0292310fc9d](https://github.com/metabase/metabase/commit/bf3b25a6b7a2e1460f895033b900f0292310fc9d)

Related #4158

⬇️ Please click the 👍 reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by metamben**
Closes #10851

### Description

I conjecture that the original idea behind not allowing detail-only fields to have field-values was to prevent confusing users with large values. Instead of using visibility-type for this, I propose checking `preview_display = false` to exclude JSON and auto-cruft fields.

### How to verify

The repro steps should work.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/sync/sync_metadata/fields/sync_metadata.clj [hunk 1]
```diff
@@ -92,8 +96,11 @@
         new-db-generated?        (not= old-database-is-generated new-database-is-generated)
         new-db-nullable?         (not= old-database-is-nullable new-database-is-nullable)
         new-db-partitioned?      (not= new-db-partitioned old-db-partitioned)
-        new-db-required?         (not= old-db-required new-db-required)
-        new-visibility-type?     (not= old-visibility-type new-visibility-type)
+        new-db-required?           (not= old-db-required new-db-required)
+        new-visibility-type?       (not= old-visibility-type new-visibility-type)
+        ;; set preview_display=false for crufty fields (prevents FieldValues from being created)
+        is-crufty?                 (crufty-field? database field-metadata)
+        set-preview-display-false? (and is-crufty? old-preview-display)
```
Comment (escherize) [inline src/metabase/sync/sync_metadata/fields/sync_metadata.clj:103]: This only triggers when old-preview-display is truthy. If it's nil (the default for existing fields), this won't set it to false. Is that intentional? Might need `(not (false? old-preview-display))` instead iff you want to set it for fields that haven't been explicitly configured.

**Review by escherize — APPROVED** [review]
Overall, looks good. Some observations:

Crufty tables are unaffected (which is fine): Fields in crufty tables (visibility_type = :cruft) are excluded from sync entirely via sync-tables-clause, so they never enter the FieldValues pipeline.

Do you think it's worth documenting the distinction:
- Manually-set :details-only fields will get FieldValues (the fix)
- Auto-crufted fields won't get FieldValues (because `preview_display = false`)

File: src/metabase/sync/sync_metadata/fields/sync_metadata.clj (hunk 1 above)
Comment (metamben) [reply src/metabase/sync/sync_metadata/fields/sync_metadata.clj:103]: It should not be `nil` because the field is not nullable. But I'm quite confused. I added preview_display to `metabase.sync.sync-metadata.fields.our-metadata/table->fields` but I notice that `visibility_type` is not selected there. Where does it come from?
