### PR TITLE
[Fixes #12349] Respect disabling of PulseChannels

### LINKED ISSUE #12349: Creating an alert always turns on email alerts, even when they are toggled off
**Describe the bug**

When I attempt to set up a new alert, the toggle for email notifications defaults to on in the UI. Toggling this off and toggling on a Slack alert results in the following payload (which looks correct):

image

However, the server does persist an email alert:

image

And the UI reflects this:

image

**Logs**

I can provide more detail if necessary, just don't want to bother sanitizing logs if this is easily reproducible.

**To Reproduce**
1. Go to an existing saved question
2. Click on 'Get Alerts'
3. Toggle off the 'Email' alert
4. Toggle on a 'Slack' alert, and choose a channel
5. Click 'Done'

**Expected behavior**
Alert is created for Slack only, without email alerts enabled.

**Screenshots**
See above.

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-heroku-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "4.4.0-1062-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.2",
      "date": "2020-04-10",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**

Low severity but presumably an easy bug to squash.

**Additional context**
nil

### PR DESCRIPTION
**Pull request by tsmacdonald**
When alerts are initially set up for a question, we drop the `enabled` flag on the floor and default it to `true`, leading to spurious emails as in #12349.

Interestingly `update-pulse-channel!` was already correct, it's just `create-pulse-channel!` that had the issue. I'm interested in the code similarities between the two but don't pretend to understand Toucan well enough to make a suggestion yet.

I reproduced the bug with a failing test (see diff):

```
metabase.models.pulse-channel-test
1 non-passing tests:

(with-model-cleanup "Pulse")
 disabled

<snip>
    diff: - {:enabled false}	  
          + {:enabled true}	    
```
and it now passes. I also did manual testing locally.

### CODE REVIEW

**Review by robdaemon — APPROVED** [review]
Change looks good, but apparently we have some code that relied on the old behavior, judging by the test failures?

File: src/metabase/models/pulse.clj [hunk 1]
```diff
@@ -287,6 +287,9 @@
   (let [channel (when new-channel (assoc new-channel
                                     :pulse_id       (u/get-id notification-or-id)
                                     :id             (:id existing-channel)
+                                    :enabled        (if (some? (:enabled new-channel))
+                                                      (:enabled new-channel)
+                                                      true)
```
Comment (tsmacdonald) [inline src/metabase/models/pulse.clj:292]: I don't feel awesome about this, but due to DB constraints `nil` (which is what we were always providing beforehand) defaults to true:

```

metabase=# \d pulse_channel
                                         Table "public.pulse_channel"
     Column     |           Type           | Collation | Nullable |                  Default                  
----------------+--------------------------+-----------+----------+-------------------------------------------
 enabled        | boolean                  |           | not null | true
```

My preference is to be explicit about nils in the app layer (and that lets us use the `(boolean? enabled)` constraint later on, but if you want to rely on the DB and change the schema check to `(or (nil? enabled) (boolean? enabled))` I'll hear you out.

Comment (tsmacdonald) [reply src/metabase/models/pulse.clj:292]: The `if` could be replaced by `(or (nil? (:enabled new-channel)) (:enabled new-channel))` but I found that a little hard to reason about

Comment (robdaemon) [reply src/metabase/models/pulse.clj:292]: so looking at that table, `enabled` is a `NOT NULL` column. I wonder where we decided that `nil` on that column should equal `true`. This would benefit from a schema defined in the code.

Comment (tsmacdonald) [reply src/metabase/models/pulse.clj:292]: Talked to Cam offline; gonna try to remove this logic and just make all the callers behave by passing in a non-nil `:enabled` value. As far as we know this is only triggered by one place in the UI that already behaves well, so I suspect it's just tests that need attention.
