### PR TITLE
Attempt to reconnect during select probing if connection is closed

### LINKED ISSUE #58304: Metabase Does Not Work on Oracle (sync fails when trying to sync tables without privileges)
Arakaki edit:
- The problem here is that sync is dying when trying to get metadata from tables we don't have access to. This shouldn't happen, sync should be resilient to this kind of problem.
- Simply ignoring `APEX_` and `ORDS_` tables isn't a good solution because there might be valid reasons to sync these tables.

### Describe the bug

Oracle Apex is a Oracle product for low code development on Oracle Databases. Although it is a separated product, Oracle actually license Apex on any licensed Oracle DBMS. That means it is nowadays extremely popular and expected to be present in most Oracle DBMS intances.

When installed, Apex creates a schema named APEX_[Version] on the database. That schema is a black box and stores Apex source code and Metadata. It should keep untouched. Whenever upgraded, Apex will add new APEX_[Version] schemas to the database and keep the older ones for its own purposes.

Due to the intensive release pace, it's impossible to keep privileges on those schemas and their hundreds objects so that Metabase sync it. Also, APEX objects shouldn't be shown on Metabase metadata.

Right now, Metabase already deal with this, but in a faulty manner given a single old Apex version is hard coded.

(https://github.com/metabase/metabase/blob/master/modules%2Fdrivers%2Foracle%2Fsrc%2Fmetabase%2Fdriver%2Foracle.clj#L596-L597).

That mean Metabase will not sync metadata from virtually any Oracle Database other then the hard coded one. It will always break by absent privilege on one of the many (and always mutating) Apex objects.

Metabase should ignore all Oracle schemas prefixed "APEX_". The same applies for "ORDS_" prefixed schemas (also part of Apex "stack")

### To Reproduce

1. Connect metabase to a Oracle with Apex installed (not the old version hard coded)
2. Try to sync the metadata
3. The process breaks with error on some Apex table/view before it ends
4. Metabase Logs register a exception.

### Expected behavior

Metabase should ignore all Oracle schemas prefixed "APEX_". The same applies for "ORDS_" prefixed schemas (also part of Apex "stack")

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "h2",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-05-21",
      "tag": "v0.54.9.1",
      "hash": "5baf7ff"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.4 (Debian 17.4-1.pgdg120+2)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "6.8.0-55-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

SEVERE

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bronsa**
closes #58304
Closes https://linear.app/metabase/issue/SEM-349/metabase-does-not-work-on-oracle-sync-fails-when-trying-to-sync-tables

Instead of using one connection per call like we attempted in https://github.com/metabase/metabase/pull/58620, we try to use the current connection unless it has been closed, and if so we attempt to open a new one

This should also avoid the issue that lead to https://github.com/metabase/metabase/pull/59999, since we ask for a new connection in a non recursive context. There is a test to ensure the resilient connection has the right options set.

### CODE REVIEW

**Comment by dpsutton** [comment]
the docstring makes effort to say that the caller must explicitly close the connection but i'm not seeing in here where that happens

**Comment by bronsa** [comment]
> the docstring makes effort to say that the caller must explicitly close the connection but i'm not seeing in here where that happens

It's done as part of the `do-with-resilient-connection` context.
https://github.com/metabase/metabase/pull/60857/files#diff-885821240479a14087c2ec8e287386ca49888288728b8ef0f94dc66b77987569R847-R848

If `try-ensure-open-conn!` is used outside of a `do-with-resilient-connection`, it will be a no-op
https://github.com/metabase/metabase/pull/60857/files#diff-885821240479a14087c2ec8e287386ca49888288728b8ef0f94dc66b77987569R874-R875

FYI I'm still iterating through the docstrings and the API

File: src/metabase/driver/sql_jdbc/execute.clj [hunk 1]
```diff
@@ -827,3 +835,65 @@
...
+
+  Not thread-safe."
+
+  ^Connection [driver ^Connection connection & {:keys [force-local?] :as opts}]
+  (cond
+    (and (not force-local?) (is-conn-open connection))
+    connection
+
+    (not (thread-bound? #'*resilient-connection-ctx*))
+    connection
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/execute.clj]: 1. Why not to merge those?
2. Please help me to better understand force-local? option. It is meant to create new connection if "current conn is open" and execution is under the do-with-resilient-connection context. My understanding is that if `(some-> *resilient-connection-ctx* :conn is-conn-open)` is true we won't create a new local connection. Shouldn't we? Why?

File: src/metabase/driver/sql_jdbc/execute.clj [hunk 2]
```diff
@@ -827,3 +835,65 @@
...
+
+    (some-> *resilient-connection-ctx* :conn is-conn-open)
+    (:conn *resilient-connection-ctx*)
+
+    :else
+    ;; we locally reset `*connection-recursion-depth*` so that the new connection
+    ;; gets all the options set as we'd expect, else we may be optaining a badly
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/execute.clj]:
```suggestion
    ;; gets all the options set as we'd expect, else we may be obtaining a badly
```

**Review by lbrdnk — COMMENTED** [review]
Please see my comment.

File: src/metabase/driver/sql_jdbc/execute.clj (hunk 1 above)
Comment (bronsa) [reply src/metabase/driver/sql_jdbc/execute.clj]: The branch `(and (not force-local?) (is-conn-open connection))` tests whether we can reuse the top level connection: if we're not forcing a local connection AND the connection passed to this function is still open, we just return it.

The branch `(not (thread-bound? #'*resilient-connection-ctx*))` is a safety check: if we're not even in a resilient context, we can't create new connections, so we fall back to returning the original passed connection (even if it's closed).

The branch `(some-> *resilient-connection-ctx* :conn is-conn-open)` tests whether we can reuse the resilient context's cached connection: this only runs when the first branch failed (either `force-local?` is true OR the passed connection is closed) AND we are in a resilient context, so we check if we have a good cached connection available.

Even though the first and second branches both return `connection`, they are fundamentally different scenarios: the first is "the passed connection is good to use" while the second is "we can't provide anything better, so here's what you gave us.", so I'd rather not merge them for clarity.
    
WRT `force-local?`: this forces creation of a completely new context local connection even when both the passed connection is perfectly usable. See the comment in the `have-select-privilege?` use case where we need a separate connection to avoid interfering with outer result sets that might become unrecoverably closed.

Comment (lbrdnk) [reply src/metabase/driver/sql_jdbc/execute.clj]: > even when both the passed connection and any cached resilient connection are perfectly usable...

Is that really true? I think that branch `(some-> *resilient-connection-ctx* :conn is-conn-open)` returns connection if it is usable, regardless of value of force-local?, doesn't it?

That behavior matches _my understanding of intent_ in the have-select-privilege?, but not my understanding of this function's docstring.

File: docs/developers-guide/driver-changelog.md [hunk 3]
```diff
@@ -27,6 +27,11 @@ title: Driver interface changelog
 
 - Added a feature `:expressions/today` for drivers that support generating a date for the current day.
 
+## Metabase 0.55.8
```
Comment (lbrdnk) [inline docs/developers-guide/driver-changelog.md]:
```suggestion
## Metabase 0.55.9
```

File: src/metabase/driver/sql_jdbc/execute.clj (hunk 1 above)
Comment (bronsa) [reply src/metabase/driver/sql_jdbc/execute.clj]: > > even when both the passed connection and any cached resilient connection are perfectly usable...
> 
> Is that really true? I think that branch `(some-> *resilient-connection-ctx* :conn is-conn-open)` returns connection if it is usable, regardless of value of force-local?, doesn't it?

your understanding is correct and the intended behavior. 
my wording of the phrase you quoted was incorrectly edited, I fixed it. 

>That behavior matches my understanding of intent in the have-select-privilege?, but not my understanding of this function's docstring.

I think I see the source of confusion: my definition of `local` is "local to the context", rather than "local to the call" like you seem to be assuming. Perharps renaming to `force-context-local?` would be better?

Comment (bronsa) [reply src/metabase/driver/sql_jdbc/execute.clj]: edit: additional source of confusion was also my wording of the phrase you quoted, which I incorrectly edited

Comment (bronsa) [reply src/metabase/driver/sql_jdbc/execute.clj]: See if the renaming and updated docstring make more sense?

**Review by lbrdnk — APPROVED** [review]
LGTM. I've explored ways how the change could result in us leaving connections opened when those should get closed. I was unable to find inconsistencies.

Still, it would be great if Dan or @metabase/drivers could find a moment to double-check there  are no implications I was unable to see.

File: src/metabase/driver/sql_jdbc/execute.clj (hunk 1 above)
Comment (lbrdnk) [reply src/metabase/driver/sql_jdbc/execute.clj]: Works for me.

File: test/metabase/driver/sql_jdbc/sync/describe_database_test.clj [hunk 4]
```diff
@@ -251,3 +251,25 @@
...
           (is (= (get-in field-name->field ["humanraceid" :id])
                  (get-in field-name->field ["race\\id" :fk_target_field_id]))))))))
+
+(deftest resilient-to-conn-close?-test
+  (testing "checking sync is resilient to connections being closed during [have-select-privilege?]"
+    (let [jdbc-describe-database #(identical? (get-method driver/describe-database :sql-jdbc)
+                                              (get-method driver/describe-database %))]
+      (mt/test-drivers (into #{}
+                             (comp (filter jdbc-describe-database)
+                                   (filter #(not (driver/database-supports? % :table-privileges nil))))
```
Comment (rileythomp) [inline test/metabase/driver/sql_jdbc/sync/describe_database_test.clj]: Might be able to simplify some of this with `normal-driver-select`

**Review by rileythomp — APPROVED** [review]

**Review by snoe — APPROVED** [review]
