### PR TITLE
Dashboard sections

### LINKED ISSUE #35667: Empty header on dashboard will cause subscriptions to fail
### Describe the bug

Simple bug: if you add a heading and you leave it empty, the dashboard will fail to send

### To Reproduce

1) create a card
2) add it to a dashboard
3) add an empty header
4) send a subscription

### Expected behavior

Subscriptions shouldn't fail

### Logs

```
2023-11-13 16:30:07,840 ERROR middleware.log :: POST /api/pulse/test 500 466.7 ms (222 DB calls) 
{:via [{:type java.lang.NullPointerException, :at [clojure.string$replace invokeStatic "string.clj" 101]}],
 :trace
 [[clojure.string$replace invokeStatic "string.clj" 101]
  [clojure.string$replace invoke "string.clj" 75]
  [metabase.shared.parameters.parameters$escape_chars invokeStatic "parameters.cljc" 142]
  [metabase.shared.parameters.parameters$escape_chars invoke "parameters.cljc" 139]
  [metabase.pulse$escape_heading_markdown$fn__110875 invoke "pulse.clj" 149]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 669]
  [clojure.core$update_in$up__6922 invoke "core.clj" 6220]
  [clojure.core$update_in$up__6922 invoke "core.clj" 6219]
  [clojure.core$update_in invokeStatic "core.clj" 6221]
  [clojure.core$update_in doInvoke "core.clj" 6207]
  [clojure.lang.RestFn invoke "RestFn.java" 445]
  [metabase.pulse$escape_heading_markdown invokeStatic "pulse.clj" 149]
  [metabase.pulse$escape_heading_markdown invoke "pulse.clj" 146]
  [metabase.pulse$dashcard__GT_part invokeStatic "pulse.clj" 179]
  [metabase.pulse$dashcard__GT_part invoke "pulse.clj" 152]
  [metabase.pulse$dashcards__GT_part$iter__110879__110883$fn__110884 invoke "pulse.clj" 185]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.Cons next "Cons.java" 39]
  [clojure.lang.RT next "RT.java" 713]
  [clojure.core$next__5451 invokeStatic "core.clj" 64]
  [clojure.core$dorun invokeStatic "core.clj" 3143]
  [clojure.core$doall invokeStatic "core.clj" 3149]
  [clojure.core$doall invoke "core.clj" 3149]
  [metabase.pulse$dashcards__GT_part invokeStatic "pulse.clj" 184]
  [metabase.pulse$dashcards__GT_part invoke "pulse.clj" 181]
  [metabase.pulse$execute_dashboard$fn__110901 invoke "pulse.clj" 205]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 331]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 315]
  [metabase.pulse$execute_dashboard invokeStatic "pulse.clj" 200]
  [metabase.pulse$execute_dashboard doInvoke "pulse.clj" 194]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [metabase.pulse$pulse__GT_notifications invokeStatic "pulse.clj" 502]
  [metabase.pulse$pulse__GT_notifications invoke "pulse.clj" 496]
  [metabase.pulse$send_pulse_BANG_ invokeStatic "pulse.clj" 642]
  [metabase.pulse$send_pulse_BANG_ doInvoke "pulse.clj" 623]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [metabase.api.pulse$fn__112292 invokeStatic "pulse.clj" 322]
  [metabase.api.pulse$fn__112292 invoke "pulse.clj" 308]
  [compojure.core$wrap_response$fn__44401 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__44385 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__44390 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__44394 invoke "core.clj" 151]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__44394 invoke "core.clj" 153]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__44394 invoke "core.clj" 153]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__44394 invoke "core.clj" 153]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__44394 invoke "core.clj" 152]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__101134 invoke "auth.clj" 17]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [compojure.core$make_context$handler__44441 invoke "core.clj" 290]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 300]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 199]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 199]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 199]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [metabase.api.routes$fn__112892$fn__112893 invoke "routes.clj" 64]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__113057$fn__113058 doInvoke "routes.clj" 70]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [compojure.core$make_context$handler__44441 invoke "core.clj" 290]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 300]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__44394 invoke "core.clj" 153]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__44394 invoke "core.clj" 153]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__44394 invoke "core.clj" 153]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 199]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 199]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 199]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [compojure.core$make_context$handler__44441 invoke "core.clj" 290]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 300]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415 invoke "core.clj" 197]
  [compojure.core$make_context$fn__44445 invoke "core.clj" 301]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [compojure.core$routes$fn__44413$f__44414 invoke "core.clj" 198]
  [compojure.core$routes$fn__44413 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__109484 invoke "exceptions.clj" 107]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__109481 invoke "exceptions.clj" 95]
  [metabase.server.middleware.log$log_api_call$fn__115157$fn__115158$fn__115159 invoke "log.clj" 216]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
  [metabase.server.middleware.log$log_api_call$fn__115157$fn__115158 invoke "log.clj" 208]
  [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
  [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
  [metabase.server.middleware.log$log_api_call$fn__115157 invoke "log.clj" 207]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__120683 invoke "browser_cookie.clj" 42]
  [metabase.server.middleware.security$add_security_headers$fn__91647 invoke "security.clj" 153]
  [metabase.server.middleware.json$wrap_json_body$fn__117633 invoke "json.clj" 67]
  [metabase.server.middleware.offset_paging$handle_paging$fn__91671 invoke "offset_paging.clj" 45]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__117651 invoke "json.clj" 103]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__120950 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__120969 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__57248 invoke "misc.clj" 61]
  [metabase.server.middleware.session$reset_session_timeout$fn__71757 invoke "session.clj" 457]
  [metabase.server.middleware.session$bind_current_user$fn__71724$fn__71725 invoke "session.clj" 352]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 331]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 315]
  [metabase.server.middleware.session$bind_current_user$fn__71724 invoke "session.clj" 351]
  [metabase.server.middleware.session$wrap_current_user_info$fn__71705 invoke "session.clj" 285]
  [metabase.server.middleware.session$wrap_session_id$fn__71688 invoke "session.clj" 217]
  [metabase.server.middleware.auth$wrap_api_key$fn__101142 invoke "auth.clj" 30]
  [ring.middleware.cookies$wrap_cookies$fn__120870 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__57230 invoke "misc.clj" 29]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__57256 invoke "misc.clj" 78]
  [ring.middleware.gzip$wrap_gzip$fn__120912 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__57259 invoke "misc.clj" 95]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__120699 invoke "ssl.clj" 51]
  [metabase.server$async_proxy_handler$fn__79504 invoke "server.clj" 77]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
  [org.eclipse.jetty.server.Server handle "Server.java" 563]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$0 "HttpChannel.java" 505]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 762]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 497]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 282]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
  [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy runTask "AdaptiveExecutionStrategy.java" 416]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy consumeTask "AdaptiveExecutionStrategy.java" 385]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy tryProduce "AdaptiveExecutionStrategy.java" 272]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy lambda$new$0 "AdaptiveExecutionStrategy.java" 140]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 411]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 936]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1080]
  [java.lang.Thread run nil -1]],
 :message nil}
```

### Information about your Metabase installation

```JSON
v47.x

pretty sure it comes from the very beginning of the times
```

### Severity

P3

### Additional context

workaround: delete the empty headers

### LINKED ISSUE #38209: [Epic] Add Sections (pre-defined layout of empty dash cards) to Dashboard
## Context
[Product doc](https://www.notion.so/metabase/Make-it-fast-to-get-a-nice-looking-set-of-empty-cards-I-can-fill-in-b43be81e69284820a2cc6c2856130d71)

### PR DESCRIPTION
**Pull request by kulyk**
Closes #38209 
Fixes: #35667

Adds a concept of "sections" and "empty cards" to dashboards:

- a placeholder card is just a blank card, but can be replaced with a question using the new "replace question" action (#36744). Technically they're implemented as virtual cards with `display: "placeholder"` and their own viz component (`DashCardPlaceholder`)
- sections are pre-defined common layouts that might help people to focus on the dashboard content vs. layout fiddling. They use placeholder cards (although not limited to only them)

### To verify

1. Open a dashboard and enter the edit mode
2. Click the "Add section" button at the top right
3. Pick one of the available sections
4. Ensure it's adding a few cards to the end of the current dashboard tab
5. Click "Select question" on a placeholder card to replace it with a question
6. Ensure changes get persisted (also parameters, viz setting overrides, etc.)

Note: it's expected that placeholder cards show up as blank outside the editing mode.

### Demo

https://github.com/metabase/metabase/assets/17258145/56870e87-fedb-4765-b07c-2b976c0c9ca7

### CODE REVIEW

File: frontend/src/metabase/dashboard/actions/cards-typed.ts [hunk 1]
```diff
@@ -168,7 +208,10 @@ export const replaceCard =
     const dashboardId = getDashboardId(getState());
 
     let dashcard = getDashCardById(getState(), dashcardId);
-    if (isVirtualDashCard(dashcard)) {
+    if (
+      isVirtualDashCard(dashcard) &&
```
Comment (alxnddr) [inline frontend/src/metabase/dashboard/actions/cards-typed.ts:212]: Should we update `isVirtualDashCard` to consider placeholder cards as virtual ones?

File: frontend/src/metabase/dashboard/actions/cards-typed.ts [hunk 2]
```diff
@@ -168,7 +208,10 @@ export const replaceCard =
     const dashboardId = getDashboardId(getState());
 
     let dashcard = getDashCardById(getState(), dashcardId);
-    if (isVirtualDashCard(dashcard)) {
+    if (
```
Comment (alxnddr) [inline frontend/src/metabase/dashboard/actions/cards-typed.ts:211]: Are there cases why we need this if statement at all?

**Review by alxnddr — APPROVED** [review]
FE code looks great, I left one minor comment.

It feels that "undo" button to remove just added section can be handy.

**Comment by alxnddr** [comment]
@markbastian just to double-check, this new card type should not affect the serialization functionality, right?

**Comment by markbastian** [comment]
> @markbastian just to double-check, this new card type should not affect the serialization functionality, right?

I do not know a lot about serialization, but I don't think it should. We might want to get a review from someone with some experience in that area to do the final PR if that's a concern.

File: frontend/src/metabase/dashboard/actions/cards-typed.ts (hunk 2 above)
Comment (kulyk) [reply frontend/src/metabase/dashboard/actions/cards-typed.ts]: Good point, I added it in the first place because the action wasn't meant to be used with virtual cards. But long term it would most likely just cause confusion. Removed in [`ea9309e`](https://github.com/metabase/metabase/pull/38463/commits/ea9309ec6e83896c162bec697b700961c26c0a20)

(we're still using the "replace" action only to dashcards with questions or placeholder cards)

**Review by cdeweyx — APPROVED** [review]
