### PR TITLE
Handle date formatting specifically for Excel

### LINKED ISSUE #10803: Download full results of a Query to CSV or XLSX - Excel does not recognize the Timestamp format
Download full results of a Query to CSV or XLSX - Excel does not recognize the Timestamp format

**To Reproduce**
1. Go to any query you may have that has a timestamp field (at least in Oracle database as data source).
2. Click on 'Download full results' in XLSX or CSV.
3. Open with Excel.
4. See column containing timestamp, it is shown in the cell as:
2019-03-18T17:24:31.000+01:00 (type 'General', i.e. not recognized).
It cannot be converted either or get recognized if cell is changed to date, time, ...

**Expected behavior**
When exporting results containing dates, times or datetimes (timestamps fields), the formatting should be recognized by Excel on Open without any need to convert or tweak the data.

**Screenshots**
image

**Information about your Metabase Installation:**
- Your browser and the version: Chrome version 76.0.3809.132 (Official Build) (32-bit)
- Your operating system: Windows 10.0.17134 Build 17134
- Your databases: Oracle, MySQL
- Metabase version: v.0.33
- Metabase hosting environment: Jar-file on CentOS
- Metabase internal database: MySQL

**Severity**
This annoying and prevents that some users can make use of Metabase to complete some of their tasks.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by robdaemon**
Excel will not parse an ISO8601 date, so add a new version of
FormatValue specifically made for Excel.

The Docjure library used has formatting helpers for a few Java classes,
but specifically java.util.Date and not the newer Java 8 Time classes.
In this case, it formats any java.util.Date as m/d/yy.

Resolves #10803

### CODE REVIEW

**Comment by robdaemon** [comment]
A few notes on this one: we can make an override here to support a different date format, like `m/d/yy hh:MM` if we want, but I did not do that initially. See: https://github.com/mjul/docjure/blob/master/src/dk/ative/docjure/spreadsheet.clj#L251-L254

Docjure uses a private function to create the date format, and uses memoization to only create said style once per document (super good.): https://github.com/mjul/docjure/blob/master/src/dk/ative/docjure/spreadsheet.clj#L304

So, we could do something like that if desired, and override the `Date` format listed above.

Unit testing for this change doesn't quite make sense - we can have an integration test that ensures we get back an Excel file, but truly testing the contents of that file are dicey because we can't invoke Excel in a test (oh @dacort this is all so familiar)

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 1]
```diff
@@ -19,12 +17,45 @@
...
+    (t/java-date this)))
+
 ;; add a generic implementation for the method that writes values to XLSX cells that just piggybacks off the
 ;; implementations we've already defined for encoding things as JSON. These implementations live in
 ;; `metabase.middleware`.
 (defmethod spreadsheet/set-cell! Object [^Cell cell, value]
-  (when (= (.getCellType cell) Cell/CELL_TYPE_FORMULA)
-    (.setCellType cell Cell/CELL_TYPE_STRING))
+  (when (= (.getCellType cell) CellType/FORMULA)
+    (.setCellType cell CellType/STRING))
```
Comment (robdaemon) [inline src/metabase/query_processor/streaming/xlsx.clj:58]: These changes were to stop using the deprecated `CELL_TYPE_*` forms that are removed in POI 4.x. (would impact an upgrade)

**Review by sbelak — APPROVED** [review]
Looks good. Would be nice if we also contribute upstream so in the long run we don't accrue scar tissue from everything we use.

**Comment by robdaemon** [comment]
@sbelak yeah I really wanted to do that, but we're behind on our docjure / POI dependencies, which had other transient dependencies that would need to be updated, so it seemed a bit much to update those in a patch release.

**Comment by sbelak** [comment]
Makes total sense. It was more meant as, let's make a mental note of that and do it at some point.

**Comment by robdaemon** [comment]
@camsaul this will need your override (we don't have any tests in the xlsx generation, because... well, we don't automate Excel itself to verify)

**Comment by camsaul** [comment]
Going to make an exception to codecov rules and merge this in this time so it can get out to people. Testing how Excel handles our spreadsheets is sort of hard to do programatically anyway :(

**Comment by XaLDe** [comment]
Don't know if that helps but found a workaround to manipulate datetime data and make compatible with excel.

So, excel really treats dates as integers, where 0='1900-0-0', 1='1900-0-1' etc etc.
All I needed to do in my query for datetime values was the following: 
"DATDETIME VALUE"--'1900-01-01'+2::INT 

You will get a 5 digit number; When in excel just click Cntrl+Shift+3 to change to date and you will see your date!
