### PR TITLE
Show question and model names in filters

### LINKED ISSUE #22992: [Bulk Filters] Weird behavior on nested questions
**Describe the bug**
Bulk filters work really nice on basic tables, but the things get a bit confusing when we start applying them on the nested questions. The initial picker shows fields from the base table but the "tab" is not highlighted. If you switch to any of the implicitly joined tables, it is then impossible to choose any of the fields from the base table.

**Logs**
N/A

**To Reproduce**
1. Open Orders table and save it as a question "Q1"
2. New question > Saved Questions > Q1
3. Click "Visualize" to go to the simple mode
4. Click `...` next to the Filter which will open a bulk filter editor
5. Notice that no tab is selected, although all fields listed belong to the "Orders" table
image
6. Click on any of the implicitly joined tables (User, Product)
7. It is now impossible to filter "Orders" directly from this modal
image

Close the modal and repeat the step 4. again to be able to apply filters to "Orders"

**Expected behavior**
It can be tricky to "mark" the base table in the nested question, but at least provide the "Default" or the "Base" tab so that it's possible to:
1. know which fields do you filter on
2. come back to the base table filters

**Information about your Metabase Installation:**
local dev, `master`, adacc7ed5866e33df88aba381580028cc5cb0991, H2, Sample Database

**Severity**
P3

### LINKED ISSUE #23079: Bulk filter modal: Model names do not appear
**Describe the bug**

When applying summaries/metrics to a model, the model name does not appear in the tab bar

Potentially related to https://github.com/metabase/metabase/issues/22992

**To Reproduce**
1. Go to any model
2. apply any summary metric (like count by id)
3. open the bulk filter modal
4. see that instead of the model name, you just see a table icon in the tab bar

**Expected behavior**

The model name should appear in the tab bar header

**Screenshots**
Screen Shot 2022-06-01 at 8 41 04 AM
Screen Shot 2022-06-01 at 8 40 57 AM

**Severity**

Annoying, but doesn't impact functionality

### PR DESCRIPTION
**Pull request by iethree**
## Before

In the bulk filter modal tabs, saved question and model names would not appear

171431659-8f754b51-2fb6-4af9-9b54-269d7577f002

## After

Question and model names appear in the bulk filter modal

Screen Shot 2022-06-07 at 3 43 00 PM

This also affects the sidebar (positively, I think)

Screen Shot 2022-06-07 at 3 38 21 PM

Resolves https://github.com/metabase/metabase/issues/23079 and resolves https://github.com/metabase/metabase/issues/22992

## Testing Steps

- Open a saved question or model. 
- add some sort of summary (to force another tab)
- open the bulk filter modal and see your question or model name as one of the tabs

### CODE REVIEW

File: frontend/src/metabase-lib/lib/DimensionOptions/DimensionOptions.ts [hunk 1]
```diff
@@ -38,8 +38,7 @@ export default class DimensionOptions {
   sections({ extraItems = [] } = {}): DimensionOptionsSection[] {
     const [dimension] = this.dimensions;
     const table = dimension && dimension.field().table;
-    const tableName =
-      table && !table.isSavedQuestion() ? table.objectName() : null;
+    const tableName = table ? table.objectName() : null;
```
Comment (iethree) [inline frontend/src/metabase-lib/lib/DimensionOptions/DimensionOptions.ts:41]: I know this has side effects for the filter sidebar, and I'm comfortable with those. Not sure what else this might affect though 🤔

Comment (iethree) [reply frontend/src/metabase-lib/lib/DimensionOptions/DimensionOptions.ts:41]: @daltojohnso , it looks like you have touched https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/utils/mapping-options.js before, which appears to be one of the few places this code is called. Can you think of why we would *not* want to show a table name when the table is a saved question?

Comment (WiNloSt) [reply frontend/src/metabase-lib/lib/DimensionOptions/DimensionOptions.ts:41]: I'm not entirely sure, but the change leads back to PR https://github.com/metabase/metabase/pull/13427 which addressed both https://github.com/metabase/metabase/issues/13376 and https://github.com/metabase/metabase/issues/13406. I think @mazameli could help provide more context on that one.

I tried to test what #13427 does and it seems this change doesn't break it so I guess (with my limited knowledge) it should be fine.
image

**Review by ranquild — APPROVED** [review]
