### PR TITLE
SQL: sync only tables for which we have SELECT privilege

### LINKED ISSUE #10139: Don't try to sync Postgres schemas or tables current user has no perms for
As far as I know Postgres does not have a way to configure permissions to hide schemas entirely from users. You can revoke their `USAGE` permission of those schemas, but they can still see that it exists. 

Metabase tries to sync all the schemas it sees, and when some of them fail it results in noisy logs. Everything still works as expected, but the useless error messages clutter things up.

### PR DESCRIPTION
**Pull request by sbelak**
Previously our sync process fetched all the tables regardless if we had permissions to do anything with them or not. This changes the behaviour of SQL DBs to only sync tables for which the DB user has SELECT privilege. 

Fixes #10139, #1654, and #2591

### CODE REVIEW

**Comment by camsaul** [comment]
Looks good but you can use `deftest` now instead of `expect` to write tests

**Review by camsaul — APPROVED** [review]
You should run this with `[ci drivers]` to make sure none of the drivers are going to complain when you call `getUserName`. If that's green you can go ahead and merge

**Comment by sbelak** [comment]
Turns out the support for `getTablePrivileges` is very spotty: psql doesn't include views, for Maria it returns nothing, so I'm afraid we'll have to do it for each driver by querying the internal catalogue. Any objections to this @camsaul?

**Comment by flamber** [comment]
I might be wrong, but wouldn't this also fix #1654? Also, was seen in the [forum](https://discourse.metabase.com/t/nightly-issues-on-elb-connection-refused/8058/5) today with pg views.

**Comment by sbelak** [comment]
You're right

**Comment by mercedes-r** [comment]
Greetings. I just upgraded a company's metabase instance that was many updates behind. It's a big improvement overall, but we've noticed that via Browse Data the connected user can see schemas and tables that it does not have access to. This is an issue for us. After some searching, I found issue #10139 and ultimately ended up here. I believe this fix will solve our problem. Does anyone have an idea of when it will be merged?

**Comment by mazameli** [comment]
@sbelak It would be rad to get tests passing on this and merge it since it seems like it'll fix a few issues.

**Comment by sbelak** [comment]
DB specific ways of getting permissions: 

Postgres: https://stackoverflow.com/questions/7336413/query-grants-for-a-table-in-postgres

MySQL: https://dev.mysql.com/doc/refman/8.0/en/show-grants.html

MSSQL: https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-my-permissions-transact-sql?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-table-privileges-transact-sql?view=sql-server-ver15

sqlite: N/A

H2: ? (supports GRANT but as far as I can tell no way to get back who has which grants, but considering it's H2 not the end of the world)

Vertica: https://www.vertica.com/blog/view-privileges/

Oracle: https://chartio.com/resources/tutorials/oracle-user-privileges--how-to-show-all-privileges-for-a-user/

Redshift: https://chartio.com/learn/amazon-redshift/how-to-view-permissions-in-amazon-redshift/

Snowflake: https://docs.snowflake.net/manuals/sql-reference/sql/show-grants.html

Mongo (not really applicable to 10892): https://docs.mongodb.com/manual/reference/command/rolesInfo/#dbcmd.rolesInfo

Druid (not really applicable to 10892): : https://druid.apache.org/docs/latest/development/extensions-core/druid-basic-security.html

Spark SQL: https://docs.databricks.com/administration-guide/access-control/table-acls/object-permissions.html

BigQuery: https://cloud.google.com/bigquery/docs/access-control

Presto: https://prestodb.io/docs/current/sql/show-grants.html

--- 

what needs to happen is that `has-select-privilege?` becomes a multimethod dispatched on driver and implemented in each driver (same as eg `sql.qp/->honeysql`)

**Comment by robdaemon** [comment]
This needs more work, implementing the driver-specific code. I rebased it to get it up to date with master, but it's not ready for merge yet.

**Comment by sbelak** [comment]
I've hit a snag: for most DBs you can have your database without any permissions set in which case this new code would return no tables to sync. One thing we could do is to assume that if you have access to nothing, it's probably misconfigured.

File: src/metabase/driver/mysql.clj [hunk 1]
```diff
@@ -294,6 +294,16 @@
        (-> (dbspec/mysql details)
            (sql-jdbc.common/handle-additional-options details))))))
 
+(defmethod sql-jdbc.sync/accessible-tables-for-user :mysql
+  [_ db-or-id-or-spec user]
+  (jdbc/query (sql-jdbc.conn/db->pooled-connection-spec db-or-id-or-spec)
+              [(format "SELECT table_name, table_schema AS table_schem
+                        FROM information_schema.table_privileges
+                        WHERE grantee like \"'%s'@%%\"
```
Comment (robdaemon) [inline src/metabase/driver/mysql.clj:302]: can this be done with a bound parameter? doing formats in sql statements always makes me nervous.

Something like:

`WHERE grantee LIKE ?` and `(format "\"'%s'@%%\" user)` - basically shift the format.

File: src/metabase/driver/sql_jdbc/sync.clj [hunk 2]
```diff
@@ -85,46 +85,88 @@
...
+  "Fetch a JDBC Metadata ResultSet of tables in the DB, optionally limited to ones belonging to a given
+  schema."
   [^DatabaseMetaData metadata ^String schema-or-nil ^String db-name-or-nil]
   ;; tablePattern "%" = match all tables
   (with-open [rs (.getTables metadata db-name-or-nil schema-or-nil "%"
                              (into-array String ["TABLE" "VIEW" "FOREIGN TABLE" "MATERIALIZED VIEW"]))]
     (vec (jdbc/metadata-result rs))))
 
+(defmulti accessible-tables-for-user
+  "Return a predicate which checks if user `user` has SELECT privilega for a given table"
```
Comment (robdaemon) [inline src/metabase/driver/sql_jdbc/sync.clj:98]: s/privilega/privilege/

**Comment by camsaul** [comment]
@sbelak when you get around to writing some more tests so the CodeCov thing stops complaining: it only counts code and tests in Metabase that run as part of the main test suite (e.g. tests against H2). You can always write a one-off dummy driver and implement just a few methods so you can have better test coverage around core functionality -- see https://github.com/metabase/metabase/blob/43f5f662890c2539189c8ae2d759967ebae806a2/test/metabase/driver_test.clj#L7-L15

Of course, just because CodeCov doesn't count tests for drivers doesn't mean we shouldn't have them. Since this is definitely critical path code I think we should get as close as possible to 100% test coverage here.

**Review by robdaemon — CHANGES_REQUESTED** [review]

**Review by robdaemon — APPROVED** [review]

**Review by camsaul — DISMISSED** [review]
Can we add some more tests for the driver-specific implementations? You might have to mock stuff out in cases where we can't easily create a new user or table for the current user to test against, but even those sorts of tests would be better than nothing.

It would also be good to get up to the 75% test coverage threshold for the core, non-driver-specific stuff, maybe by creating mocked drivers for the tests. This is really critical path code and it should have really good test coverage. If this ends up breaking it would be pretty nasty

**Comment by sbelak** [comment]
@camsaul doesn't `determine-select-privilege` test test against all drivers that do not have the default implementation (which is a no op) of `accessible-tables-for-user`? That was the intent, if I'm misunderstanding how the driver tests are run/used, I'll do the same test in every driver.

**Comment by sbelak** [comment]
I fund a subtle bug in the fallback: we do a `SELECT 1 FROM foo LIMIT 1` on one of the tables. But if this table is empty, we treat this as failure. As far as I can tell JDBC does not guarantee that accessing a table for which you don't have permissions will result in an exception thrown (although that empirically seems to be the case). We can do 2 things:
1) rely on exception being thrown and just check for that
2) try all tables

**Comment by camsaul** [comment]
@sbelak `with-blank-db` just creates and binds a blank H2 DB, and at any rate you're doing a bunch of H2-specific SQL like`"set db_close_delay -1;"` and `grant all on "birds" to GUEST`, which probably wouldn't work in other types of databases. They exact syntax for granting permissions may be different between different databases.

It would almost certainly be easiest to write a driver-specific test for this functionality in each corresponding driver test namespace. Take a look at what we're doing here in `postgres_test`

https://github.com/metabase/metabase/blob/master/test/metabase/driver/postgres_test.clj#L299-L311

You can do something similar for each DB for which this feature is implemented, but create a DB/table with specific perms for the current user instead.

It's probably fine to keep those H2-specific tests in that namespace so it's clear that there is some generic coverage for those methods

**Comment by lindsay-stevens** [comment]
I think this should take a try-then-fail approach e.g. try to select from the table, and use the presence of a privileges error to determine whether Metabase has select access. This is simple and avoids worrying about how each database records privileges.

For example, the Postgres driver implementation currently in this PR uses a system view called `information_schema.table_privileges`. This only shows directly granted privileges, and does not reflect inherited privileges. So if a DBA organises privileges into groups, then grants select privileges to the Metabase user by way of group membership, it'll look like Metabase can't read any tables. There are Postgres system information functions for more reliably determining role membership, such as `has_table_privilege`, but this doesn't necessarily account for schema usage privilege which is also required to read from a table. I can imagine that most other databases have a similar variety of gotchas, but they would all throw an error if Metabase tries but is not allowed to read from a table.

**Comment by sbelak** [comment]
@lindsay-stevens thanks for the heads up. We want to minimize how much we touch the DBWH during sync (and some of our users have *a lot* of tables), but I've updated the code to handle inheritance properly (& added tests for it).

**Comment by camsaul** [comment]
@sbelak I think @lindsay-stevens suggestion might be way less moving pieces and way easier to maintain, I don't think doing a bunch of queries like

```sql
SELECT 1
FROM my_table
```

to check whether we actually have `SELECT` access is going to be a deal-breaking during sync. We already do a number of queries per-table such as a query to get all the Fields for a Table and a query to get all the PKs/FKs for a Table (even if this happen indirectly via JDBC). On top of that we do Field sample queries and FieldValues caching in some situations. So one extra `SELECT 1` query per Table is probably not going to make a huge difference in overall sync times. For someone with 10k Tables it's already going to be a long-running process.

If you switched the code to try a simple `SELECT 1` then you could probably get this PR green super easily. Since you already have tons of tests you could keep those and they should still work the same way

**Comment by lindsay-stevens** [comment]
Using `select 1 from schema.table` might still scan the table if the select privilege exists, but `select 1 from schema.table where false` or `select 1 from schema.table limit 1` should evaluate 0 or 1 rows only while still causing a privilege check.

**Comment by dacort** [comment]
FYI, BigQuery recently added [table-level access controls](https://cloud.google.com/blog/products/data-analytics/introducing-table-level-access-controls-in-bigquery).

**Comment by Opalevanescence** [comment]
Only improvement I see on the newer sandbox merge is checking that cells are clickable.

**Comment by sbelak** [comment]
Since we've moved to a db agnostic approach using a probe query, I don't think there's much point in testing this per-driver, especially since doing so would become very involved as we'd need to:
1) create a user;
2) set their permissions (can connect + schema visibility);
3) create a new MB connection to the db using that user;
4) run sync using that connection;
5) verify it handles schema visibility correctly.

1+2 get nasty because the way to do it will be different for every DB, and not all  users with which we initially connect to our test DBs have permissions to create new users and/or grant them connect permissions which in term means messing with CI containers.

File: src/metabase/driver/sql_jdbc/connection.clj [hunk 3]
```diff
@@ -121,23 +121,26 @@
...
+       (locking database-id->connection-pool
+         (or
+          ;; check if another thread created the pool while we were waiting to acquire the lock
+          (get @database-id->connection-pool database-id)
+          ;; create a new pool and add it to our cache, then return it
+          (let [db (db/select-one [Database :id :engine :details] :id database-id)]
+            (u/prog1 (create-pool! db)
+              (set-pool! database-id <>)))))))
+    ;; already a spec object
+    db-or-id-or-spec))
```
Comment (robdaemon) [inline src/metabase/driver/sql_jdbc/connection.clj:143]: @dpsutton totally unrelated, but I bet this is part of the issue with ssh tunnels!

since the connection pool is an an atom.... we don't really ever check to see if we need to re-establish the tunnel.

**Review by robdaemon — APPROVED** [review]
looks reasonable to me
