### PR TITLE
Fix table viz settings when query is out of sync with the setting

### LINKED ISSUE #38908: Broken list of columns in table settings if the setting value is out of sync with the query
### Describe the bug

When `table.columns` setting is out of sync with the query, the list of columns in the table viz settings is incomplete. It's impossible to recover from this state without updating the query or recreating the question.

### To Reproduce

https://metaboat.slack.com/archives/C01MS7DQKR6/p1708089997707009

There is no straightforward way to reproduce this without changing data via API directly. `table.columns` viz should be should be manually set to a subset of columns.

### Expected behavior

- When hiding or making columns visible, columns from the query results should be displayed (like we already do for native queries)
- In add/remove columns mode "visible columns" from the query should be used for the source of truth.

### Logs

_No response_

### Information about your Metabase installation

```JSON
-
```

### Severity

P1/P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/38908

Changes:
- Table settings are split into 2 components - `FieldPanel` (which is used to add/remove fields to/from the query) and `TableColumnPanel` (which is used to change table column settings). 
- `FieldPanel` is moved to `metabase/querying`. It no longer modifies the viz settings directly. `Question` class was updated so there is no special casing for this change, and this follows our regular rules for syncing viz settings with the query.
- `TableColumnPanel` uses incoming `columns` (`data.cols`) for the source of truth. It handles the case from the referenced issue where there is no matching setting for the column. There is a unit test for this.
- Code was simplified and it now uses a common utility `findColumnSettingIndexesForColumns`

How to verify:
- CI is green
- Try hiding/showing columns in table viz settings

### CODE REVIEW

File: frontend/src/metabase-types/api/card.ts [hunk 1]
```diff
@@ -102,11 +102,7 @@ export type PivotTableCollapsedRowsSetting = {
 export type TableColumnOrderSetting = {
   name: string;
   enabled: boolean;
-
-  // We have some corrupted visualization settings where both names are mixed
-  // We should settle on `fieldRef`, make it required and remove `field_ref`
-  fieldRef?: FieldReference;
-  field_ref?: FieldReference;
+  fieldRef: FieldReference;
```
Comment (ranquild) [inline frontend/src/metabase-types/api/card.ts:105]: We've been ignoring `field_ref` for far too long, it's time to drop it

File: frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx [hunk 2]
```diff
@@ -136,6 +138,12 @@ function DashCardInner({
     [dashcard],
   );
 
+  const question = useSelector(state =>
```
Comment (ranquild) [inline frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx:141]: `query` is needed to make MLv2 work, so we need to pass it from here

File: frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx [hunk 3]
```diff
@@ -37,24 +34,21 @@ export const HideColumnAction: LegacyDrill = ({
...
-        const columnSettings = getColumnSettingsWithRefs(
-          settings?.["table.columns"] || [],
-        );
-        const query = question.query();
-
-        const columnSettingIndex = findColumnSettingIndex(
-          query,
-          column,
+        const columnSettings = settings?.["table.columns"] ?? [];
+        const columnSettingIndex = findColumnSettingIndexForColumn(
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx:38]: Use the same function used everywhere else for this task

File: frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/QueryColumnPicker/utils.ts [hunk 4]
```diff
@@ -0,0 +1,145 @@
...
+      columnItems,
+      displayName:
+        groupInfo.fkReferenceName || groupInfo.displayName || t`Question`,
+      isSelected: columnItems.every(({ isSelected }) => isSelected),
+      isDisabled: columnItems.some(({ isDisabled }) => isDisabled),
+    };
+  });
+}
+
+function disableLastSelectedQueryColumn(groupItems: ColumnGroupItem[]) {
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/QueryColumnPicker/utils.ts:52]: This was not previously handled and resulted in broken queries

File: frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPicker/utils.ts [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+
+import type { ColumnItem, DragColumnProps } from "./types";
+
+export function getColumnItems(
+  query: Lib.Query,
+  stageIndex: number,
+  columns: DatasetColumn[],
+  columnSettings: TableColumnOrderSetting[],
+): ColumnItem[] {
+  const columnItems = columns.map(legacyColumn => {
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPicker/utils.ts:20]: Columns from query results are used for the source of truth, which is essentially the fix.

File: frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPicker/utils.ts [hunk 6]
```diff
@@ -0,0 +1,88 @@
...
+    const column = Lib.fromLegacyColumn(query, stageIndex, legacyColumn);
+    const columnInfo = Lib.displayInfo(query, stageIndex, column);
+    const columnSettingIndex = findColumnSettingIndexForColumn(
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPicker/utils.ts:23]: Drop custom code to match columns and rely on the function used everywhere else for this task

File: frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx [hunk 7]
```diff
@@ -37,24 +34,22 @@ export const HideColumnAction: LegacyDrill = ({
...
-        const columnSettings = getColumnSettingsWithRefs(
-          settings?.["table.columns"] || [],
-        );
-        const query = question.query();
-
-        const columnSettingIndex = findColumnSettingIndex(
-          query,
-          column,
+        const columnSettings = settings?.["table.columns"] ?? [];
+        const [columnSettingIndex] = findColumnSettingIndexesForColumns(
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx:38]: This is still wrong and will match the wrong column setting in complex cases. To figure out in other PRs. We need to pass the whole column list to match properly.

File: frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/utils.ts [hunk 8]
```diff
@@ -0,0 +1,91 @@
...
+  const adjustedNewIndex = columnItems[newIndex].columnSettingIndex;
+
+  const newSettings = [...columnSettings];
+  newSettings.splice(
+    adjustedNewIndex,
+    0,
+    newSettings.splice(adjustedOldIndex, 1)[0],
+  );
+
+  return newSettings;
```
Comment (uladzimirdev) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/utils.ts:83]: it took me a while to understand what's going on here 😅 worth having a comment like

// here we delete a setting from the old index and put it to the new index, shifting all elements

**Review by uladzimirdev — COMMENTED** [review]
Minor comments. I'll approve after testing locally

**Review by uladzimirdev — APPROVED** [review]
Works fine locally. hiding/showing columns is not that fast, but perf is the same as with previous version

File: frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx [hunk 9]
```diff
@@ -1,12 +1,9 @@
 import { t } from "ttag";
 
 import { onUpdateVisualizationSettings } from "metabase/query_builder/actions";
-import {
-  findColumnSettingIndex,
-  getColumnSettingsWithRefs,
-} from "metabase/visualizations/components/settings/ChartSettingTableColumns/utils";
 import type { LegacyDrill } from "metabase/visualizations/types";
 import * as Lib from "metabase-lib";
+import { findColumnSettingIndexesForColumns } from "metabase-lib/queries/utils/dataset";
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx:6]: 1. Create a question [like this](https://github.com/metabase/metabase/assets/6830683/dd28c30b-34af-47bd-9d62-8327b081a953)
2. Visualize it
3. Open visualization settings
4. Click "Add or remove columns"
5. Click to enable "Product" > "Title" column

:x: Column is not marked as enabled

It works in `master`.

----

1. Create a question [like this](https://github.com/metabase/metabase/assets/6830683/dd28c30b-34af-47bd-9d62-8327b081a953)
2. Visualize it
3. Open visualization settings
4. Click "Add or remove columns"
5. Click to enable "Product" > "Title" column
6. Click to enable "Product 2" > "Category" column

[Error: `Cannot find matching FK Table ID for FK Field 37 "Product ID"`](https://github.com/metabase/metabase/assets/6830683/946b7ddb-9265-4722-9ac8-0d4eeac732e7)

This is broken in `master` as well.

**Review by kamilmielnik — COMMENTED** [review]
Just adding a few more comments to @uladzimirdev's excellent review.

File: frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx (hunk 9 above)
Comment (uladzimirdev) [reply frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx:6]: I think this is what Alex called "broken" on slack, so there expected to be follow-up PRs

at the same time, seems we don't have tests covering such cases

Comment (ranquild) [reply frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx:6]: The first case works in master accidentally. It's definitely a MLv2 bug

File: frontend/src/metabase-lib/queries/utils/dataset.ts [hunk 10]
```diff
@@ -52,35 +52,46 @@ export function findColumnIndexForColumnSetting(
...
-  column: DatasetColumn,
 ) {
-  // ignore settings without fieldRef but preserve indexes
-  const items = columnSettings.flatMap((item, settingIndex) => {
-    const fieldRef = normalize(item.fieldRef);
-    return fieldRef ? [{ fieldRef, settingIndex }] : [];
-  });
+  const fieldRefs = columnSettings.reduce(
+    (fieldRefs: FieldRefWithIndex[], { fieldRef }, originalIndex) => {
+      if (fieldRef != null) {
```
[the remark this answers is not in the document]
Comment (ranquild) [reply frontend/src/metabase-lib/queries/utils/dataset.ts:73]: `normalize` should not be needed or there is a bug
Previously invalid field refs were created for column settings without them, and that would lead to exceptions in `findColumnIndexesFromLegacyRefs`

File: frontend/src/metabase/querying/components/FieldPanel/FieldPanel.tsx [hunk 11]
```diff
@@ -0,0 +1,106 @@
...
+    return getColumnGroupItems(query, stageIndex);
+  }, [query, stageIndex]);
+
+  const visibleGroupItems = useMemo(
+    () => searchColumnGroupItems(groupItems, searchValue),
+    [groupItems, searchValue],
+  );
+
+  const handleColumnToggle = (columnItem: ColumnItem) => {
+    onChange(toggleColumnInQuery(query, stageIndex, columnItem));
```
[the remark this answers is not in the document]
Comment (ranquild) [reply frontend/src/metabase/querying/components/FieldPanel/FieldPanel.tsx:39]: It's an warning in WebStorm to do it like that

File: frontend/src/metabase/querying/components/FieldPanel/FieldPanel.tsx [hunk 12]
```diff
@@ -0,0 +1,106 @@
...
+      <TextInput
+        value={searchValue}
+        onChange={e => setSearchValue(e.target.value)}
+        rightSection={<Icon name="search" />}
+        placeholder={t`Search for a column…`}
+        mb="1rem"
+      />
+      {visibleGroupItems.map((groupItem, groupIndex) => {
+        return (
+          <div
```
[the remark this answers is not in the document]
Comment (ranquild) [reply frontend/src/metabase/querying/components/FieldPanel/FieldPanel.tsx:57]: This is the old markup. I haven't changed anything

File: frontend/src/metabase/querying/components/FieldPanel/FieldPanel.unit.spec.tsx [hunk 13]
```diff
@@ -0,0 +1,133 @@
...
+    expect(orderGroup).not.toBeChecked();
+
+    userEvent.click(orderGroup);
+    expect(firstColumn).toBeChecked();
+    expect(firstColumn).toBeEnabled();
+  });
+
+  it("should allow to search for columns", () => {
+    setup();
+    userEvent.type(screen.getByPlaceholderText("Search for a column…"), "a");
```
[the remark this answers is not in the document]
Comment (ranquild) [reply frontend/src/metabase/querying/components/FieldPanel/FieldPanel.unit.spec.tsx:121]: It previously didn't handle such case. I haven't changed anything.

File: frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/utils.ts [hunk 14]
```diff
@@ -0,0 +1,91 @@
...
+      fieldRef: Lib.legacyRef(query, stageIndex, column),
+      enabled: columnSetting ? columnSetting.enabled : true,
+      icon: getColumnIcon(column),
+      column: datasetColumn,
+      columnSettingIndex,
+    };
+  });
+
+  return [
+    ...columnItems
```
[the remark this answers is not in the document]
Comment (ranquild) [reply frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/utils.ts:44]: I was thinking about this but this is far harder to read. Currently this block says: for columns with valid settingIndex, sort them based on the index, all others are added in the end.

File: frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/utils.ts (hunk 8 above)
Comment (ranquild) [reply frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/utils.ts:83]: Existing code, but I can add a comment

**Review by kulyk — APPROVED** [review]
