### PR TITLE
Add context to Save verb and fix similar translation issues

### LINKED ISSUE #64036: Wrong Korean translation on unsaved SQL question drill down menu
### Describe the bug

When creating a new SQL question and trying to drilldown, the translation in the drilldown popover is wrong.

#### Korean
Image

#### English for reference
Image

My best guess is that because the `Save` is a different element, so the translation is unconnected, causing the translator to have no idea these 2 translation strings are connected.

The translation is "저장 이질문을 탐색해 보세요" which means something like "save / try to  drill through this question" which doesn't make much sense. I expect to see something like "이질문을 탐색하려면 저장하세요" <- which puts the save button ("저장하세요") at the end of the sentence instead.

### To Reproduce

1. Visit http://localhost:3000/?locale=ko, 새로운 > SQL 쿼리 (New -> SQL Query)
2. `select * from orders` and run the query
3. Try to click on any of the cells in the visualization table.

### Expected behavior

The translation is correct

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-09-24",
      "src_hash": "e8057b230e02b51c6d923627f163fa206047abd4",
      "tag": "v1.57.1-SNAPSHOT",
      "hash": "feaa645"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.2+13-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.2+13-LTS",
    "os.name": "Mac OS X",
    "os.version": "15.6.1",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

low

### Additional context

Here's where the translation happens

https://github.com/metabase/metabase/blob/eeecd9a10ae997a8e4b355805a868e21fb34a29b/frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx#L28-L41

### PR DESCRIPTION
**Pull request by romeovs**
Fixes https://github.com/metabase/metabase/issues/64036

Adds context to the parts of the sentence to show what sentence it's being used in. Translators can hopefully pick that up and translate the whole sentence correctly.

Ideally, we should not be splitting translations up like this at all, since in a lot of languages the way you translate parts of sentences is super context-dependent 🙃.

That or we should switch to a library that supports whole-sentence interpolation (like `react-i18n`), but that seems like a huge lift.

### CODE REVIEW

File: frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ export const NativeQueryClickFallback: LegacyDrill = ({ question }) => {
       type: "custom",
       view: ({ dispatch }) => (
         <Flex display="flex" align="baseline" gap="0.25rem">
-          {jt`${(
+          {c('in the sentence "Save this question to drill-through"').jt`${(
             <Button
               key=""
```
Comment (nemanjaglumac) [inline frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx]: Not your diff, but why is the `key` missing?
Could you fix that, please?

File: frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx [hunk 2]
```diff
@@ -35,7 +35,8 @@ export const NativeQueryClickFallback: LegacyDrill = ({ question }) => {
                 dispatch(setUIControls({ modal: MODAL_TYPES.SAVE }))
               }
             >
-              {t`Save`}
+              {c('in the sentence "Save this question to drill-through"')
+                .t`Save`}
```
Comment (nemanjaglumac) [inline frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx]: Why do you have the same context two times?
I think only this one is enough. You can remove the one around `jt`

Comment (romeovs) [reply frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx]: Because they will show up as independent items in the translation file (AFAICT). We need to mark both to make sure the translators know what to do.

File: frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx [hunk 3]
```diff
@@ -26,16 +26,17 @@ export const NativeQueryClickFallback: LegacyDrill = ({ question }) => {
       type: "custom",
       view: ({ dispatch }) => (
         <Flex display="flex" align="baseline" gap="0.25rem">
-          {jt`${(
+          {c('in the sentence "Save this question to drill-through"').jt`${(
             <Button
-              key=""
+              key="save-button"
```
Comment (nemanjaglumac) [inline frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx]: <3

File: frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx (hunk 2 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx]: Did you try generating the translation string?
I honestly do not know how will this be presented to the translator.

**Review by nemanjaglumac — APPROVED** [review]
Up to you if you want to further investigate whether or not we need two translation contexts here.

File: frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx (hunk 2 above)
Comment (romeovs) [reply frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx]: It shows up in the `locales/metabase.po` file as such:
```
#: frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx:35
msgctxt "in the sentence \"Save this question to drill-through\""  Not Committed Yet
msgid "Save"
msgstr ""

#: frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx:40
#, javascript-format
msgctxt "in the sentence \"Save this question to drill-through\""
msgid "{0} this question to drill-through."
msgstr ""
```

This gets presented to the translators in whatever software they use.

**Comment by romeovs** [comment]
@nemanjaglumac for future reference: two contexts are needed in this case. `babel-plugin-ttag` cannot attach the outer context to the inner context.

In fact, while investigating. The inner `c(...).t` (or `t` for that matter) was just discarded due to the `c(...).jt` wrapping it, so I had to pull out the inner `c(...).t`. This is a bug in `ttag` AFAICT, and does not happen with plain `jt`...

I've searched the codebase for other places where this might have been an issue and fixed them in this PR as well.
