### PR TITLE
Disable /execute permission, ensure actions can run with standard perms

### LINKED ISSUE #28425: Non-admin users can't run actions
**Describe the bug**
Non-admin users with full permissions can't run actions

**To Reproduce**
1. Run an instance with a DB with actions
2. Create a dashboard with any valid action
3. Log in as a non-admin user with full permissions
4. Open the dashboard and try to run any action
5. Backend replies with 403 "You don't have permissions to do that."

**Expected behavior**
Non-admin users should be able to run actions

**Information about your Metabase Installation:**

`master` branch

### PR DESCRIPTION
**Pull request by tsmacdonald**
This'll be revisited as part of v47

[Fixes #28425]

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28457)

### CODE REVIEW

File: test/metabase/api/dashboard_test.clj [hunk 1]
```diff
@@ -2849,51 +2851,53 @@
                 (is (partial= {:message "No destination parameter found for #{\"price\"}. Found: #{\"id\" \"name\"}"}
                               (mt/user-http-request :crowberto :post 400 execute-path {:parameters {"id" 1 "name" "Blueberries" "price" 1234}})))))))))))
 
-(defn- ee-features-enabled? []
```
Comment (tsmacdonald) [inline test/metabase/api/dashboard_test.clj:2852]: I _hate_ commenting out code, but since we plan to come right back to this for 47 this seems like a rare case where it might make sense.

File: src/metabase/query_processor/middleware/permissions.clj [hunk 2]
```diff
@@ -135,7 +135,7 @@
   (when-not (has-data-perms? (required-perms outer-query))
     (check-block-permissions outer-query))
   (when-not (has-data-perms? (query-action-perms outer-query))
-    (throw (perms-exception required-perms))))
```
Comment (tsmacdonald) [inline src/metabase/query_processor/middleware/permissions.clj:138]: `#function ...` was showing up in the exception; invoking it here makes the actual perms list show up.

File: test/metabase/api/dashboard_test.clj (hunk 1 above)
Comment (dpsutton) [reply test/metabase/api/dashboard_test.clj:2852]: i've 50/50 on this. Is there an issue to revisit this? If so let's toss this snippet in the issue. Otherwise leave it commented out. Just worried that whoever comes back to this will write new tests and forget about this block.

**Review by dpsutton — APPROVED** [review]
