### PR TITLE
Fix for #24715: "Remember Me" functionality doesn't work

### LINKED ISSUE #24715: "Remember Me" functionality doesn't work
**Describe the bug**
On Metabase Open Source version, self-hosted, "Remember Me" checkbox doesn't seem to work after 0.43.xx => 0.44.0 upgrade.

Looking at browser's network console, the checkbox value is sent to backend, but cookies are still marked as session cookies (see screenshot).
Screenshot 2022-08-10 at 22 06 00

The installation doesn't have any customizations related to authentication. Only env variables are related to DB setup (MB_DB_ prefix)

**To Reproduce**
1. Ensure "Remember Me" checkbox is checked
2. Login using email + password
3. Fully close the browser
4. Go back to Metabase => redirected back to login page

**Expected behavior**
Metabase should remember login if corresponding checkbox has been checked

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 104.0.5112.79
- Your operating system: MacOS 12.5
- Your databases: Postgres 14
- Metabase version: 0.44.0
- Metabase hosting environment: Docker/K8s cluster
- Metabase internal database: Postgres 14

**Severity**
How severe an issue is this bug to you? 
Very annoying

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/24715. This is a regression from https://github.com/metabase/metabase/pull/23349

## Explanation of problems this PR solves

**Bug 1**
If the session timeout setting is off, checking "remember me" doesn't work. This is the bug reported in https://github.com/metabase/metabase/issues/24715. Before session timeouts, the session cookie (`metabase.SESSION`) was being used to implement "remember me" functionality. If the "remember me" checkbox ticked, the session cookie's `max-age` attribute would be set far off into the future. If the user closed the browser and opened the app, the session cookie would still be there. This worked because the session cookie was being set once, on login. But when we introduced session timeouts, we started resetting the session cookie on every request. That means overwriting the `Max-Age` attribute with an `Expires` attribute if the session timeout setting was on (correct), but also removing the `Max-Age` attribute if the session timeout setting was off (wrong).

**Bug 2**
There is another bug not reported in https://github.com/metabase/metabase/issues/24715. If the session timeout setting is off, leaving "remember me" unchecked doesn't work.

To reproduce:
1. Toggle on the session timeout setting, with any value
2. Log out
3. Log in again, and leave "remember me" unchecked on login
4. Close the browser
5. Open the app again. You will still be logged in

The expected behaviour is to be logged out, because "remember me" was unchecked.

This happens for a very similar reason as the other bug. The session cookie initially has no `Max-Age` or `Expires` attribute, which means it will expire when the browser closes. But because we're updating it on every request, it gets an `Expires` attribute.

## How the solution works

In both of the bugs, the problem arises from setting the expires/max-age attributes on the two session cookies (`metabase.SESSION` and `metabase.TIMEOUT`) **together** for two purposes: tracking when the browser closes, and when the timeout expires. The assumption was that their expires/max-age attributes should be kept in sync, so when the timeout cookie expires, the session cookie will expire automatically, and vice versa.

This PR breaks that assumption, and allows metabase.SESSION and metabase.TIMEOUT cookies max-age/expires attributes to be set separately. The `metabase.SESSION` cookie's max-age is set for the "remember me" functionality, and the `metabase.TIMEOUT` cookie's expires attribute is used for the timeout. The `metabase.SESSION` cookie's max-age attribute is set on login once, and from then on, only the `metabase.TIMEOUT` is updated. 

**Specifically, how this solves Bug 1:**
When "remember me" is unchecked the `metabase.SESSION` cookie has no max-age or expires attribute, regardless of the timeout setting. So the cookie disappears when the browser is closed.

**Specifically, how this solves Bug 2:**
When the timeout setting is on, the `metabase.TIMEOUT` cookie is set to expire regardless of whether "Remember me" was checked or not. When it does, the frontend will make a logout request, clearing the `metabase.SESSION` cookie.

### CODE REVIEW

**Comment by flamber** [comment]
If session timeout is enabled, then we probably shouldn't even display the "Remember me"?
Some history #15995

**Comment by calherries** [comment]
That could certainly be desirable from a user's point of view. Even if we were to hide the option on login if timeout was enabled, both of these bugs would still need fixing.

**Comment by alxnddr** [comment]
> If session timeout is enabled, then we probably shouldn't even display the "Remember me"? Some history #15995

It is technically still remembering — users can close all of their tabs and open one again within the timeout. The session timeout can be big

**Review by alxnddr — COMMENTED** [review]
@calherries I'm wondrering if it is possible to simplify things:

**OSS or the session timeout is disabled**: after user logged in we set far future date and do not update it — the same behavior as it was before

**EE with the sesssion timeout enabled**: current EE behavior — two cookies, update  the `expires` field on every request

**Comment by calherries** [comment]
@alxnddr Yes, on second thought something like your suggested simplification would be possible if we disable "remember me" functionality when the session timeout is enabled, as flamer suggested.

If the session timeout is enabled, then disabled, we need to remove the expires attribute of the session cookie so it expires with the browser session. To do so, on every request, we could check if the session timeout setting is `nil` and if it is, we set the session cookies without an `expires` attribute. This is still setting the session cookie on every request, but it would remove the need for the "remember-me" cookie.

**Comment by calherries** [comment]
@alxnddr I've re-discovered why we can't simplify things that way, even if "remember me" is disabled when session timeout settings are on. It takes some explanation.

We have three possible states:
1. If the setting timeout is off and "remember me" is on, the session cookies (metabase.SESSION and metabase.TIMEOUT) need to have a max-age attribute.
2. If the setting timeout is off and "remember me" is off, the session cookies need to have no max-age and no expires attribute.
3. If the setting timeout is on, the session cookies need to have an expires attribute.

Let's assume "remember me" is off, and the setting timeout is on. Then an admin user switches the setting timeout is switched from on to off.

That's a state transition from 3 to 2. So we need to remove the expires attribute on the session cookies when it's switched off. We can only know that the setting timeout has been switched off (potentially by another user) by reading the database, i.e. checking that the value of the setting is `nil`. So we need a rule on every request: if the value of the timeout setting is nil, then remove the expires attribute on the session cookie.

The problem is that rule will also trigger in state 1, when the setting timeout is off and "remember me" is on. There is no way to tell if the user is in state 1 or transitioning from 3 to 2, unless we add a "remember me" cookie. That's why this bug happened https://github.com/metabase/metabase/issues/24715 and why this PR fixes it.

**Comment by alxnddr** [comment]
@calherries good catch, thanks for the explanation. Then adding a new cookie sounds reasonable

**Comment by calherries** [comment]
@alxnddr After a long walk down the wrong path I've pulled myself out of the rabbit hole. 

The solution __can__ be a lot simpler. We just need to break the assumption that we should keep the max-age/expires attributes of the metabase.SESSION and metabase.TIMEOUT cookies in sync.

Then we can cleanly separate the remember-me feature from the timeout feature.

So the "metabase session" closes when the earliest of these events happen:
(1) the metabase.SESSION cookie expires from closing the browser (when remember me is off), or
(2) the metabase.TIMEOUT cookie expires from timing out (when the timeout setting is on)

I just need to implement the code for full-app-embedding, and then it will be ready for final review.

File: frontend/src/metabase/auth/actions.ts [hunk 1]
```diff
@@ -66,27 +66,22 @@ export const loginGoogle = createThunkAction(
...
 
-      dispatch(push(loginUrl));
-      window.location.reload(); // clears redux state and browser caches
-    };
-  },
-);
+    dispatch(push(loginUrl));
+    window.location.reload(); // clears redux state and browser caches
+  };
+});
```
Comment (calherries) [inline frontend/src/metabase/auth/actions.ts:84]: @alxnddr This is the only change on the FE. I made sure the session is deleted every time the session middleware calls `logout`. Before, we were assuming the `metabase.SESSION` cookie had expired whenever the `metabase.TIMEOUT` cookie had expired. This is no longer the case. Now, if the `metabase.TIMEOUT` cookie expires, we need to clear the `metabase.SESSION` cookie.

File: src/metabase/server/middleware/session.clj [hunk 2]
```diff
@@ -45,6 +46,19 @@
 (def ^:private ^String metabase-session-timeout-cookie  "metabase.TIMEOUT")
 (def ^:private ^String anti-csrf-token-header           "x-metabase-anti-csrf-token")
 
+(defmulti session-cookie-name
```
Comment (dpsutton) [inline src/metabase/server/middleware/session.clj:49]: Is this open to extension? This being a `defmulti` feels weird.

Comment (dpsutton) [reply src/metabase/server/middleware/session.clj:49]: Eh i guess it makes sense because of the other stuff. You should add a default case that throws though i suppose.

File: src/metabase/server/middleware/session.clj [hunk 3]
```diff
@@ -72,79 +86,87 @@
...
+  (throw (ex-info (str (tru "Invalid session-type."))
+           {:session-type session-type})))
+
+(defmethod default-session-cookie-attributes :normal
+  [_ request]
+  (merge
+   {:same-site config/mb-session-cookie-samesite
+    ;; TODO - we should set `site-path` as well. Don't want to enable this yet so we don't end
+    ;; up breaking things
+    :path      "/" #_(site-path)}
```
Comment (dpsutton) [inline src/metabase/server/middleware/session.clj:105]: should you remove the `#_(site-path)`?

File: src/metabase/server/middleware/session.clj (hunk 2 above)
Comment (calherries) [reply src/metabase/server/middleware/session.clj:49]: You're right, I can't see a future where we add another session type with a different cookie name. I'll change it to a function with a `case` expression.

**Review by dpsutton — APPROVED** [review]

**Review by alxnddr — APPROVED** [review]
