### PR TITLE
Fix pie chart display when switching from notebook editor

### LINKED ISSUE #42367: Pie chart sometimes disappears
### Describe the bug

Pie chart sometimes disappears.

### To Reproduce

Check out the loom from https://metaboat.slack.com/archives/C05NQSWPRMK/p1715122094392309

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
Latest master
```

### Severity

Looks annoying

### Additional context

May be related to https://github.com/metabase/metabase/pull/40840

### PR DESCRIPTION
**Pull request by JesseSDevaney**
- This PR addresses the Pie Chart failing to render when switching from notebook editor to the visualization mode. See slack [thread](https://metaboat.slack.com/archives/C05NQSWPRMK/p1715122094392309) for context.
- Closes: https://github.com/metabase/metabase/issues/42367

**Before**

https://github.com/metabase/metabase/assets/22608765/d012b22a-fab3-4b97-aaf9-d7374fe8e0e8

**After**

https://github.com/metabase/metabase/assets/22608765/cd041461-ba58-4d4a-bbb2-cb5a6c4ea152

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx [hunk 1]
```diff
@@ -258,11 +261,15 @@ export default class PieChart extends Component {
       const { width, height } =
         this.chartContainer.current.getBoundingClientRect();
 
+      if (width === 0 && height === 0) {
+        return this.updateChartViewportSize(delay + 200);
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx:265]: This looks a bit hackish, it would be great to avoid that.
So the problem is that ExplicitSize in `ChartWithLegend` resizes with a delay so that this `updateChartViewportSize` function is invoked when chartContainer still has zero width and zero height.

I think a more straightforward and reliable approach would be to call the previous version of `updateChartViewportSize` when ExplicitSize updates its size. Wdyt?

Comment (JesseSDevaney) [reply frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx]: Thank you for the feedback! I pushed up a commit to revert the hack and update the chart viewport size when ExplicitSize updates its size.

File: frontend/src/metabase/visualizations/components/ChartWithLegend.jsx [hunk 2]
```diff
@@ -21,6 +21,15 @@ class ChartWithLegend extends Component {
     style: {},
   };
 
+  componentDidUpdate(prevProps) {
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/ChartWithLegend.jsx:24]: I believe a more suitable place for this would be right in `ExplicitSize` component:
In `__updateSize` we can change the line 186 to `this.setState({ width, height }, () => this.props.onResize?.());`

And then slightly tweak the prop you added in the PieChart: `onResize={this.updateChartViewportSize}`

Comment (JesseSDevaney) [reply frontend/src/metabase/visualizations/components/ChartWithLegend.jsx]: Thank you, Sasha!

**Review by alxnddr — APPROVED** [review]
