### PR TITLE
when an alert failed to execute, make sure task history's status is failed

### LINKED ISSUE #54495: Alerts that fail to run are marked as success in task-history
### Describe the bug

Even if an alert fails to execute, the the corresponding system task is logged with status = 'success'. The errors are only reported in the Metabase log.

This prevents reporting failure conditions from Usage Analytics / task_history.

### To Reproduce

1. Create any question that fails to execute, for example a native question: `select 1/0`, save it
2. Set up a hourly alert for the question
3 The notification is skipped, no email is sent
4(!)The notification-send and send-pulse system tasks will be marked as success

Image

### Expected behavior

Alert failure reasons should be clearly marked in task history.
Ideally, common conditions should be easily identifiable  — for example, whether the alert triggered, didn’t trigger, it's check failed, or was skipped entirely. The same goes for the corresponding notification.

The related errors should also be recorded and surfaced in usage analytics.

### Logs

```
2025-02-28 12:00:00,195 INFO notification.send :: [Notification 4] Sending
2025-02-28 12:00:00,523 ERROR middleware.catch-exceptions :: Error processing query: Division by zero: "1"; SQL statement: […]
  :card_id 135,
  :context :pulse,
  :error "Division by zero: \"1\"; SQL statement:\nselect 1/0 [22012-214]",
  :row_count 0,
  :running_time 0,
  :data {:rows [], :cols []}}
 2025-02-28 12:00:00,542 INFO notification.send :: [Notification 4] Skipping
```

### Information about your Metabase installation

```JSON
1.53, but this has always been the case
```

### Severity

Reported by a customer

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Closes #54495

See https://github.com/metabase/metabase/pull/54949/files#r1988433689 for the reasoning

### CODE REVIEW

File: src/metabase/notification/payload/impl/card.clj [hunk 1]
```diff
@@ -11,11 +11,15 @@
 
 (mu/defmethod notification.payload/payload :notification/card
   [{:keys [creator_id payload subscriptions] :as _notification-info} :- ::notification.payload/Notification]
-  (let [card_id (:card_id payload)]
-    {:card_part       (notification.execute/execute-card creator_id card_id
-                                                         ;; for query_execution's context purposes
-                                                         ;; TODO: check whether we can remove this or rename it?
-                                                         :pulse-id (:id payload))
+  (let [card_id     (:card_id payload)
```
Comment (qnkhuat) [inline src/metabase/notification/payload/impl/card.clj:14]: The fix is we throw an exception here. why throw an exception?
- well I expected `notification.execute/execute-card` to throw an exception when it executes an invalid card, but since it uses `qp/userland-query` , which run the QP with the [around-middleware](https://github.com/metabase/metabase/blob/better-task-history-report-for-failed-alerts/src/metabase/query_processor.clj#L24), in which it has the `catch-exceptions` middleware. This middleware catch all exceptions and return the error in the result map.
- By throwing an error here, this will buble up the stack and fail at https://github.com/metabase/metabase/blob/23ad35455600c7024c8a5cd636304d2a45ae1ccb/src/metabase/notification/send.clj#L146, which will cause the whole `notification-send` task fail

IMO, this is not the best fix and I'm still open for ideas. But I plan to a refactor of how we handle error across the notification in https://www.notion.so/metabase/Maintenance-alerts-implement-proper-error-handling-and-channel-selection-behavior-for-Send-now--19d69354c901802b944cd0d58940fbd7?pvs=4

File: src/metabase/notification/payload/execute.clj [hunk 2]
```diff
@@ -249,44 +250,24 @@
...
-                            (request/with-current-user creator-id
-                              (process-query))
-                            (process-query))]
-        {:card   card
-         :result result
-         :type   :card}))
-    (catch Throwable e
-      (log/warnf e "Error running query for Card %s" card-id))))
+   card-id :- pos-int?]
+  (let [result (request/with-current-user creator-id
```
Comment (qnkhuat) [inline src/metabase/notification/payload/execute.clj:257]: this was overly complicated and have a lots of duplicated logic with `qp.card/process-query-for-card`. basically all the select process-fn or keeping metadata were done by that function.

File: test/metabase/pulse/send_test.clj [hunk 3]
```diff
@@ -622,24 +622,6 @@
          (is (mt/received-email-body? :rasta #"Manage your subscriptions"))
          (is (mt/received-email-body? "nonuser@metabase.com" #"Unsubscribe")))))))
 
-(deftest pulse-permissions-test
```
Comment (qnkhuat) [inline test/metabase/pulse/send_test.clj:625]: this is replaced by `metabase.notification.payload.impl.card-test/permission-test`

File: test/metabase/pulse/test_util.clj [hunk 4]
```diff
@@ -2,34 +2,11 @@
...
-   [metabase.pulse.send :as pulse.send]
-   [metabase.query-processor.test-util :as qp.test-util]
-   [metabase.test :as mt]
-   [metabase.test.data.users :as test.users]
-   [metabase.util :as u]))
+   [metabase.test :as mt]))
 
 (set! *warn-on-reflection* true)
 
-(defn send-alert-created-by-user!
```
Comment (qnkhuat) [inline test/metabase/pulse/test_util.clj:15]: unused

File: src/metabase/notification/payload/impl/card.clj (hunk 1 above)
Comment (piranha) [reply src/metabase/notification/payload/impl/card.clj:14]: > IMO, this is not the best fix

Why not though?

Comment (crisptrutski) [inline src/metabase/notification/payload/impl/card.clj:14]: nit: IMHO variables should always be kebab case

File: src/metabase/notification/payload/impl/card.clj [hunk 5]
```diff
@@ -11,11 +11,15 @@
...
+        part        (notification.execute/execute-card creator_id card_id)
+        card-result (:result part)]
+    (when (not= :completed (:status card-result))
+      (throw (ex-info (format "Failed to execute card with error: %s" (:error card-result))
```
Comment (crisptrutski) [inline src/metabase/notification/payload/impl/card.clj:18]: I wonder if it possible we introduce other return shapes, which are not completed, but don't have an error either. 

I would be more comfortable if we handled known error status(es) explicitly, and threw a different exception with the full result if the status is something unexpected.

File: src/metabase/notification/payload/impl/card.clj [hunk 6]
```diff
@@ -43,6 +47,9 @@
   (let [{:keys [notification_card card_part]} payload
         send-condition                        (:send_condition notification_card)]
     (cond
+      (true? (-> notification_card :card :archived))
```
Comment (crisptrutski) [inline src/metabase/notification/payload/impl/card.clj:50]: nit: I see why you've "split" things, but would prefer threading to be everything or nothing. Don't like doing acrobatics with my eyes!

**Review by crisptrutski — APPROVED** [review]

**Comment by crisptrutski** [comment]
Thanks for all the well placed comments, made reviewing this much easier!

File: src/metabase/notification/payload/impl/card.clj (hunk 1 above)
Comment (qnkhuat) [reply src/metabase/notification/payload/impl/card.clj:14]: it's uncoordinated and feel random, IMO we should have something like the error type system from QP. 

notification-payload -> generate the result, if has error, return error as map.

then notification.send check for these result and handle those errors.

Comment (qnkhuat) [reply src/metabase/notification/payload/impl/card.clj:14]: looks like @crisptrutski has the same idea: https://github.com/metabase/metabase/pull/54949#discussion_r1988761245

File: src/metabase/notification/payload/impl/card.clj (hunk 5 above)
Comment (qnkhuat) [reply src/metabase/notification/payload/impl/card.clj:18]: wdyt about my idea here; https://github.com/metabase/metabase/pull/54949#discussion_r1988778496?

this is something I plan for the "proper error handling" project.

Comment (crisptrutski) [reply src/metabase/notification/payload/impl/card.clj:18]: Yeah that sounds good, push exceptions as far to the boundary as possible. Have clear data-driven functional control flow as much as possible.
