### PR TITLE
Exclude nil card IDs for preemptive caching reruns

### LINKED ISSUE #57061: Phantom queries trigger during dashboard automatic cache-refresh
### Describe the bug

It seems that when Dashboard gets refreshed with the new Refresh Cache Automatically

https://www.metabase.com/docs/v0.53/configuring-metabase/caching#refresh-cache-automatically

It fires/caches phantom queries which aren't present in the dashboard:

Image

### To Reproduce

There is more [context here](https://metaboat.slack.com/archives/C05MPF0TM3L/p1745331900867999) and it seems to happen on stats as well

### Expected behavior

Only questions on the dashboard gets Refresh Cache Automatically

### Logs

None for now 

### Information about your Metabase installation

```JSON
1.53/54 and master
```

### Severity

It doesn't impact directly the Dashboard since it still loads but puts unnecessary load on both metabase since it has to cache it and the Database cause it's firing queries that aren't needed

### Additional context

I am assuming depending on the Phantom Questions and the number of Dashboards you are caching this can become a large problem for performance

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes https://github.com/metabase/metabase/issues/57061

When a `schedule`-type cache config is set up on a dashboard, and preemptive caching is enabled, we'll look for queries to re-run by first fetching the cards associated with the dashboard. This included text/header cards which have a `nil` card ID. But we look at `query_execution` to determine the queries to re-run, so `nil` card IDs result in some ad-hoc queries being picked up for re-run.

This doesn't hurt much from the user's POV aside from unintended load proportional to the number of text cards on the dashboard. But I've fixed it by filtering out `nil`s and added a corresponding unit test.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#57082** <a href="https://app.graphite.dev/github/pr/metabase/metabase/57082?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/metabase/metabase/57082?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: enterprise/backend/src/metabase_enterprise/task/cache.clj [hunk 1]
```diff
@@ -222,7 +222,9 @@
     "question" [model_id]
     "dashboard" (let [dashboard (-> (t2/select-one :model/Dashboard :id model_id)
                                     (t2/hydrate :dashcards))]
-                  (map :card_id (:dashcards dashboard)))))
+                  (->> (map :card_id (:dashcards dashboard))
+                       (filter some?)
+                       distinct))))
```
Comment (escherize) [inline enterprise/backend/src/metabase_enterprise/task/cache.clj:227]: nit:
```suggestion
                  (distinct (keep :card_id (:dashcards dashboard))))))     
```

**Review by edpaget — APPROVED** [review]

**Review by escherize — APPROVED** [review]
🚀
