### PR TITLE
Fix some events not shown on charts when grouping with different units

### LINKED ISSUE #56290: Event not shown on chart
### Description
On this area chart, showing an event does move the X-axis, but doesn't show the event as opposed to other chart types (gif in thread)

### Links
- Slack File: https://metaboat.slack.com/files/U02T6V8MXN2/F08LW1LRZLJ/diagnostic-info.json
- Screenshot: https://metaboat.slack.com/archives/C05NXACAG1G/p1743772162657389?thread_ts=1743772139.122879&cid=C05NXACAG1G

### PR DESCRIPTION
**Pull request by WiNloSt**
closes #56290
Closes uxw-34

### Backport reason
The last PR (https://github.com/metabase/metabase/pull/61239) that touches this file backported to 55. So I double backport (55 & 56)

### Description

There were 2 issues:
1. We failed to properly check which events are visible via `getTimelineEventsInsideRange` because we didn't take datetime's `unit` into account.
2. We didn't used the `visibleTimelineEvents` when showing the events, we used the unfiltered events instead, so this was wrong. This causes the problem when the filtered events only returns 1, but non filter events has more than 1. Then the result is the larger number of events. This wouldn't be a problem if we correctly check 1)

### How to verify

Follow the repro step in this [Linear comment](https://linear.app/metabase/issue/UXW-34/event-not-shown-on-chart#comment-fd85c37d) (Although, the date was wrong in the first bullet in the original comment).

> 1. make a new question that spans between Jul 1, 2024 and May 31, 2025 (count on orders by created at is fine)
> 1. add two events, one on March 11 2025 and the other on May 13 2025
> 1. now add a filter on Created At between Jul 1, 2024 and May 31, 2025
> 1. the event side bar should still show the two events, but only one can be displayed

#### After 
image

#### Before
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts [hunk 1]
```diff
@@ -29,7 +30,7 @@ const getIntervalWidth = (
 
 const groupEventsByUnitStart = (
   events: TimelineEvent[],
-  unit: string = "day",
+  unit: SupportedUnit = "day",
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts:33]: Tightening type wouldn't be bad.

File: frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts [hunk 2]
```diff
@@ -128,14 +129,22 @@ export const mergeOverlappingTimelineEventGroups = (
...
+
+  const filteredTimelineEvents = timelineEvents.filter((event) => {
+    const eventStartOfUnit = dayjs
+      .utc(event.timestamp)
+      .startOf(unit as OpUnitType);
+
     return (
-      (min.isSame(event.timestamp) || min.isBefore(event.timestamp)) &&
-      (max.isSame(event.timestamp) || max.isAfter(event.timestamp))
+      (min.isSame(eventStartOfUnit) || min.isBefore(eventStartOfUnit)) &&
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts]: This was where we got it wrong. So, in this case of the reproduction (see PR description), we check if 13 May is before 1 May and after 1 Jul. Of course, it's not.

13 May is after 1 May. When the original time range is 31 May, we got 1 May because we group it by month, so we should set the value of the event with the same unit before comparing their values.

File: frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts [hunk 3]
```diff
@@ -164,7 +174,7 @@ export const getTimelineEventsModel = (
   }
 
   const timelineEventsByUnitStart = groupEventsByUnitStart(
-    timelineEvents,
+    visibleTimelineEvents,
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts:168]: This was causing the issue where we have 1 filtered event, but we return 2 events instead.

So, when we selected both 11 Mar and 13 May, we got both events, but we set only 13 May we got nothing.

To break that down
#### Only selecting 13 May
- filtered events = 0
- early exit by returning null

#### Selecting both 11 Mar and 13 May
- filtered events = 1 (11 Mar)
- but we return the event including (13 May) here too.

It doesn't really matter since I fixed visible timeline function above, but I leave it here for completenett anyway.

File: frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts [hunk 4]
```diff
@@ -128,14 +129,15 @@ export const mergeOverlappingTimelineEventGroups = (
...
 ) => {
   const [min, max] = range;
-  return timelineEvents.filter((event) => {
-    return (
-      (min.isSame(event.timestamp) || min.isBefore(event.timestamp)) &&
-      (max.isSame(event.timestamp) || max.isAfter(event.timestamp))
-    );
+
+  const filteredTimelineEvents = timelineEvents.filter((event) => {
+    return dayjs(event.timestamp).isBetween(min, max, unit, "[]");
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts:137]: the gist is to take `unit` into account when calculating if the event is in the range or not.

`[]` means including both start and end dates (inclusive)

File: e2e/test/scenarios/organization/timelines-question.cy.spec.js [hunk 5]
```diff
@@ -394,6 +394,32 @@ describe("scenarios > organization > timelines > question", () => {
...
+
+          cy.button("Create").click();
+        });
+
+        cy.log("remove all other events except the new one");
+        toggleEventVisibility("RC1").should("not.be.checked");
+        toggleEventVisibility("RC2").should("not.be.checked");
+
+        cy.log("the new event should be visible in the chart");
+        H.echartsIcon("star").should("be.visible");
```
Comment (WiNloSt) [inline e2e/test/scenarios/organization/timelines-question.cy.spec.js:422]: ### After
Note the event line at the end bucket.

Image

### Before
Image

File: e2e/test/scenarios/organization/timelines-question.cy.spec.js [hunk 6]
```diff
@@ -336,7 +336,7 @@ describe("scenarios > organization > timelines > question", () => {
         // should show a newly created event
         cy.button("Create event").click();
         cy.findByLabelText("Event name").type("RC2");
-        cy.findByLabelText("Date").type("10/20/2023");
+        cy.findByLabelText("Date").clear().type("10/20/2023");
```
Comment (WiNloSt) [inline e2e/test/scenarios/organization/timelines-question.cy.spec.js:339]: Our date picker textbox is actually smart, but we should clear existing text first to avoid confusion. You can observe this step that we just append the new date on top of an existing value.

File: e2e/test/scenarios/organization/timelines-question.cy.spec.js [hunk 7]
```diff
@@ -557,7 +583,7 @@ function timelineEventCard(eventName) {
 }
 
 function toggleEventVisibility(eventName) {
-  timelineEventVisibility(eventName).click();
+  return timelineEventVisibility(eventName).click();
```
Comment (WiNloSt) [inline e2e/test/scenarios/organization/timelines-question.cy.spec.js:586]: Used for assertion e.g. `toggleEventVisibility("event-name").should(xxxx)`

**Comment by lorem--ipsum** [comment]
> Although, the date was wrong in the first bullet in the original comment

fixed it, good catch :-)

**Review by lorem--ipsum — APPROVED** [review]
