### PR TITLE
MLv2: Fix `:percentile` column name

### LINKED ISSUE #29964: [MLv2] [Bug] `:percentile` column name calculation broken
The fix itself is trivial, `%s` instead of `%d` in the format string, but we really need some tests around this.

```clj
clojure.lang.ExceptionInfo: Error calculating column name for 
[:percentile 
 #:lib{:uuid "62c4dd0b-7db4-4666-9796-62ca15c91c27"} 
 [:field #:lib{:uuid "cdc94b9f-ba6b-413f-916a-ee5a19221ecf"} 133853] 0.9]: 
d != java.lang.Double
```

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #29964

Also, constrain the schema for `:percentile` so the *percentile* has to be between zero and one, inclusive.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30022)

### CODE REVIEW

File: test/metabase/query_processor_test/test_mlv2.clj [hunk 1]
```diff
@@ -109,12 +109,6 @@
 
 (defn- skip-metadata-calculation-tests? [legacy-query]
   (or
-   ;; #29907: wrong column name for joined columns in `:breakout`
-   (mbql.u/match-one legacy-query
-     {:breakout breakouts}
-     (mbql.u/match-one breakouts
-       [:field _id-or-name {:join-alias _join-alias}]
-       "#29907"))
```
Comment (camsaul) [inline test/metabase/query_processor_test/test_mlv2.clj:117]: Unrelated, but I don't think we actually need to be skipping the metadata calculation test for #29907, because we're not actually checking that the column names are correct. I think I forgot to remove this; at first I was validating that column names matched ones calculated by the QP, but I changed the test logic to only checkout that metadata calculation works at all for the time being until we make a dent in all the bugs

**Review by metamben — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30022)* status: all files reviewed, 3 unresolved discussions (waiting on @camsaul)

___
*[`test/metabase/lib/aggregation_test.cljc` line 103 at r1](https://reviewable.io/reviews/metabase/metabase/30022#-NSpzjctDaCt4mWunDvC:-NSpzjctDaCt4mWunDvD:b-j1fzgn) ([raw file](https://github.com/metabase/metabase/blob/2c20a32ff66498dae3bcca05a6ba239738928212/test/metabase/lib/aggregation_test.cljc#L103)):*
> ```Clojure
>     ;; TODO -- not sure about these column names!
>     [:percentile {} (lib.tu/field-clause :venues :id) 0.95]
>     {:column-name "p0.95_ID", :display-name "0.95th percentile of ID"}))
> ```

Can we omit `0.`? That would result in a syntactically harmless looking name.



_Code quote:_
```Clojure
0.
```
___
*[`test/metabase/lib/schema/aggregation_test.cljc` line 12 at r1](https://reviewable.io/reviews/metabase/metabase/30022#-NSq-Sft-FPYln4f_dnx:-NSq-Sft-FPYln4f_dny:bq379q) ([raw file](https://github.com/metabase/metabase/blob/2c20a32ff66498dae3bcca05a6ba239738928212/test/metabase/lib/schema/aggregation_test.cljc#L12)):*
> ```Clojure
> (deftest ^:parallel percentile-test
>   (testing "valid"
>     (are [clause] (not (me/humanize (mc/explain :mbql.clause/percentile clause)))
> ```

I asked somewhere, but it seems to have got lost: how is `(me/humanize (mc/explain` better than `(mc/validate` in this context?



_Code quote:_
```Clojure
(me/humanize (mc/explain
```

**Review by camsaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @camsaul)

___
*[`test/metabase/lib/aggregation_test.cljc` line 103 at r1](https://reviewable.io/reviews/metabase/metabase/30022#-NSpzjctDaCt4mWunDvC:-NSqIVzpEadIU_e69DBe:bm4whod) ([raw file](https://github.com/metabase/metabase/blob/2c20a32ff66498dae3bcca05a6ba239738928212/test/metabase/lib/aggregation_test.cljc#L103)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

Can we omit `0.`? That would result in a syntactically harmless looking name.
</blockquote></details>

yes, that's a good idea!
___
*[`test/metabase/lib/schema/aggregation_test.cljc` line 12 at r1](https://reviewable.io/reviews/metabase/metabase/30022#-NSq-Sft-FPYln4f_dnx:-NSqHzK92jz2VHdWsIKT:bjhk08p) ([raw file](https://github.com/metabase/metabase/blob/2c20a32ff66498dae3bcca05a6ba239738928212/test/metabase/lib/schema/aggregation_test.cljc#L12)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

I asked somewhere, but it seems to have got lost: how is `(me/humanize (mc/explain` better than `(mc/validate` in this context?
</blockquote></details>

If the test fails, `mc/validate` will just return `false`, which is not a very helpful test failure, whereas `me/humanize` + `mc/explain` actually explains why the validation failed, which is a lot easier to debug

**Review by metamben — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30022)* status: all files reviewed, 1 unresolved discussion (waiting on @camsaul)

___
*[`test/metabase/lib/schema/aggregation_test.cljc` line 12 at r1](https://reviewable.io/reviews/metabase/metabase/30022#-NSq-Sft-FPYln4f_dnx:-NSqNdDQEO_hlwQPVAfu:b-ts3u4e) ([raw file](https://github.com/metabase/metabase/blob/2c20a32ff66498dae3bcca05a6ba239738928212/test/metabase/lib/schema/aggregation_test.cljc#L12)):*
<details><summary><i>Previously, camsaul (Cam Saul) wrote…</i></summary><blockquote>

If the test fails, `mc/validate` will just return `false`, which is not a very helpful test failure, whereas `me/humanize` + `mc/explain` actually explains why the validation failed, which is a lot easier to debug  
</blockquote></details>

Fair enough. Since this is a common pattern, we should probably add "official" support for it so that its role is obvious.
___
*[`test/metabase/lib/schema/aggregation_test.cljc` line 28 at r1](https://reviewable.io/reviews/metabase/metabase/30022#-NSqOgEbA-j3UXrWuIVV:-NSqOgEbA-j3UXrWuIVW:bpxciim) ([raw file](https://github.com/metabase/metabase/blob/2c20a32ff66498dae3bcca05a6ba239738928212/test/metabase/lib/schema/aggregation_test.cljc#L28)):*
> ```Clojure
>        0.1]))
>   (testing "invalid"
>     (are [clause] (me/humanize (mc/explain :mbql.clause/percentile clause))
> ```

Is `(me/humanize (mc/explain` useful here too? We ignore the return value...
