### PR TITLE
Lookup ip address for new login email off thread

### LINKED ISSUE #16169: Login blocked till timeout if Metabase can't reach GeoJS API
**Describe the bug**
Slow login longer than 15 seconds

**Logs**
[f6417d0b-8d46-4863-8dfd-e6a8dd6c26c7] 2021-05-20T14:51:23-03:00 ERROR metabase.server.request.util Erro de geocodificação de endereços IP {:url https://get.geojs.io/v1/ip/geo.json?ip=10.3.1.29}
java.net.SocketTimeoutException: connect timed out

**To Reproduce**
1. Go to the login screen
2. Enter credentials
3. Click enter
4. More than 15 seconds to access the home page

**Expected behavior**
The login process used to be instant

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-05-17",
      "tag": "v0.39.2",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": "Etc/GMT-3"
    }
  }
}

**Severity**
The user is under the impression that the login screen is not responsive

**Additional context**
>= v0.39

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes #16169

Put ip lookup and email sending off-thread

### CODE REVIEW

File: test/metabase/models/login_history_test.clj [hunk 1]
```diff
@@ -38,7 +38,8 @@
 (deftest send-email-on-first-login-from-new-device-test
   (testing "User should get an email the first time they log in from a new device (#14313, #15603)"
     (mt/with-temp User [{user-id :id, email :email, first-name :first_name}]
-      (let [device (str (java.util.UUID/randomUUID))]
+      (let [device              (str (java.util.UUID/randomUUID))
+            original-maybe-send (var-get #'login-history/maybe-send-login-from-new-device-email)]
```
Comment (camsaul) [inline test/metabase/models/login_history_test.clj:42]: You shouldn't need to `(var-get a-var)` here... just doing `a-var` should give you the same thing

File: test/metabase/models/login_history_test.clj [hunk 2]
```diff
@@ -47,7 +48,12 @@
                                                            (into {} (for [ip-address ip-addresses]
                                                                       [ip-address
                                                                        {:description "San Francisco, California, United States"
-                                                                        :timezone    (t/zone-id "America/Los_Angeles")}])))]
+                                                                        :timezone    (t/zone-id "America/Los_Angeles")}])))
+                          login-history/maybe-send-login-from-new-device-email
+                          (fn [login-history]
+                            (when-let [futur (original-maybe-send login-history)]
+                              ;; block in tests
+                              (deref futur)))]
```
Comment (camsaul) [inline test/metabase/models/login_history_test.clj:56]: If this never gets called (e.g. because of an Exception that gets thrown before the future is called) the tests are going to hang forever... and it's going to be almost impossible to debug the reason why. You should use `u/deref-with-timeout` here instead. 30 seconds or so is probably fine... normally it should be fast but you never know with those slow CircleCI test runners and their GC pauses

**Review by camsaul — APPROVED** [review]
This works for me.

It makes me think maybe we should just send all emails on a separate thread... maybe a email sending threadpool of some sort would be apporpriate.

Have you considered just creating app-wide high-priority, regular-priority, and low-priority thread pools? That's how Objective-C works for example:

```objective-c
dispatch_async(DISPATCH_QUEUE_PRIORITY_HIGH, ^{
   ...
});
```

maybe something like that as general tooling would make sense in the future.

File: test/metabase/models/login_history_test.clj (hunk 1 above)
Comment (dpsutton) [reply test/metabase/models/login_history_test.clj:42]: it's private so i can't just use the symbol `login-history/maybe-send`, I need the var reader macro `#login-history/maybe-send`. But this is the var, and when i redef it this var points at the redef'd version, so i need its value at this point, so I need var-get.

```clojure
user=> (ns foo)
nil
foo=> (defn- foo [] :original)
#'foo/foo
bar=> (ns bar)
nil
bar=> (let [original #'foo/foo]
        (with-redefs [foo/foo (fn [] :covered)]
          [(#'foo/foo) (original)]))
[:covered :covered] ;; :covered because original is a var, not the function value
bar=> (let [original (var-get #'foo/foo)]
        (with-redefs [foo/foo (fn [] :covered)]
          [(#'foo/foo) (original)]))
[:covered :original]
bar=> 
```

**Comment by dpsutton** [comment]
> It makes me think maybe we should just send all emails on a separate thread... maybe a email sending threadpool of some sort would be apporpriate.

Yeah I've thought of that. The emails are half on-thread, half off-thread. The threading audit i did found that they are all over the place. That's only a half measure here though as we need the lookup of the ip off thread as well. 

> Have you considered just creating app-wide high-priority, regular-priority, and low-priority thread pools? That's how Objective-C works for example:

Yeah this is what i want to do. I'm not sure about how to handle priority but I was thinking some threadpools for quick one-off's that you can just submit and kinda don't care when they get run (single thread pool) and then one or two threadpools with a few threads that can do work, perhaps identified by how long you think it might be.

We might also look into email errors. At last job we built a retry with increasing backoff times to account for network jitter.

File: test/metabase/models/login_history_test.clj (hunk 2 above)
Comment (dpsutton) [reply test/metabase/models/login_history_test.clj]: thanks. really good catch

**Comment by dpsutton** [comment]
@camsaul could you merge this for me? Presto isn't passing at the moment.
