### PR TITLE
Fix - metrics do not work with offset in custom expressions

### LINKED ISSUE #47854: metrics do not work with offset in custom expressions
**Context**

- [ ] #47855 - I accidentally converted it to issue

- new metric, orders table, save
- show editor, add summarize, custom expression -> `Offset([Orders, Count], -1)`, add name, notice the error

image

The same expression is added if you go through "compare to the past", expression is marked as not valid if you try to edit it

- issue links: https://github.com/metabase/metabase/issues/47806

### LINKED ISSUE #47855: unskip a test in `offset.cy.spec.ts`
unskip `should work with metrics (metabase#47854)` from `e2e/test/scenarios/question/offset.cy.spec.ts`

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #47854
Closes #47855

### How to verify

Follow repro steps from the issue.
CI is green.

### CODE REVIEW

File: frontend/src/metabase-lib/v1/expressions/index.ts [hunk 1]
```diff
@@ -127,31 +127,60 @@ export function formatSegmentName(
...
+  stageIndex: number;
+  expressionIndex: number | undefined;
+  startRule: string;
+}) {
+  const results = Lib.expressionableColumns(
+    query,
+    stageIndex,
+    expressionIndex,
+  ).map(dimension => {
+    return {
```
Comment (kamilmielnik) [inline frontend/src/metabase-lib/v1/expressions/index.ts:165]: I tried doing this:

```tsx
[
   ...Lib.expressionableColumns(/* ... */),
   ...Lib.availableMetric(/* ... */),
].map(dimenmsion => {
  const info = Lib.displayInfo(query, stageIndex, dimension);
  /* ... */
});
```

but TS complained about the `displayInfo` call.
That's why this function has 2 loops calling `Lib.displayInfo`

**Review by romeovs — APPROVED** [review]

**Comment by romeovs** [comment]
Code looks good!
