### PR TITLE
Self-heal database sync triggers

### LINKED ISSUE #48881: Databases added by config file are not synced regularly
### Describe the bug

No Quartz trigger is created for databases added by the config file, thus they are not synced regularly.

### To Reproduce

1. Metabase starts with an empty application database, and a [config file
   containing configuration for a connected database](https://www.metabase.com/docs/latest/configuring-metabase/config-file#databases)
2. It passes "INFO advanced-config.file :: Initializing :databases from config file... 🗄️"
3. It prints "INFO task.sync-databases :: A trigger for "Sync and Analyze" of Database "Metabase Cloud Storage" has been enabled with schedule: "0 22 * * * ? *"" *multiple* times
4. It reaches "INFO metabase.task :: Task scheduler started"
5. `qrtz_triggers` does not contain *any* `metabase.task.sync-and-analyze` triggers (not for the DB from the config file and not for the sample H2 DB)
6. Changes to the database (adding tables) do not become visible to Metabase

### Expected behavior

Databases should always be synced regularly, no matter how they are created.

### Logs

_No response_

### Information about your Metabase installation

Local setup of deac5cbcc7e68d20f7ffe71d021dafa73e6e9de6.

### Severity

Full blocker

### Additional context

References: https://metaboat.slack.com/archives/C079ZS06ERJ/p1728991333736979

### PR DESCRIPTION
**Pull request by devurandom**
== Behaviour without this fix ==

See #48881

== Behaviour with this fix ==

1. Metabase starts with an empty application database, and a config file
   containing configuration for a connected database
3. By the time it reaches "INFO metabase.task :: Task scheduler started",
   `qrtz_triggers` contains `metabase.task.sync-and-analyze.trigger.1`
   (sample DB) and `metabase.task.sync-and-analyze.trigger.2` (DB from
   config file)

Closes: https://github.com/metabase/metabase/issues/48881

### CODE REVIEW

File: src/metabase/core.clj [hunk 1]
```diff
@@ -163,6 +164,8 @@
   (settings/migrate-encrypted-settings!)
   ;; start scheduler at end of init!
   (task/start-scheduler!)
+  ;; In case we could not do this earlier, because the scheduler was not up yet:
```
Comment (noahmoss) [inline src/metabase/core.clj:167]: nit - usage context might be helpful here for the future
```suggestion
  ;; In case we could not do this earlier (i.e. for DBs added via config file), because the scheduler was not up yet:
```

File: src/metabase/models/database.clj [hunk 2]
```diff
@@ -136,6 +136,12 @@
     (catch Throwable e
       (log/error e "Error scheduling tasks for DB"))))
 
+(defn check-and-schedule-tasks!
+  "(Re)schedule sync operation tasks for any database which is not yet being synced regularly."
+  []
+  (doseq [database (t2/select Database)]
```
Comment (noahmoss) [inline src/metabase/models/database.clj:142]: nit - we're gradually moving towards using model keywords
```suggestion
  (doseq [database (t2/select :model/Database)]
```

**Review by noahmoss — APPROVED** [review]
looks reasonable!

File: src/metabase/core.clj (hunk 1 above)
Comment (devurandom) [reply src/metabase/core.clj]: https://github.com/metabase/metabase/pull/48882/commits/e09b6ff5088a52a98cdbf388b1d1241c33fdb323

File: src/metabase/models/database.clj (hunk 2 above)
Comment (devurandom) [reply src/metabase/models/database.clj]: https://github.com/metabase/metabase/pull/48882/commits/e09b6ff5088a52a98cdbf388b1d1241c33fdb323

**Comment by devurandom** [comment]
> @devurandom something went wrong while creating a backport [[Logs]](https://github.com/metabase/metabase/actions/runs/11406878670)

https://github.com/metabase/metabase/pull/48897

**Comment by devurandom** [comment]
v50: https://github.com/metabase/metabase/pull/48897
v51: https://github.com/metabase/metabase/pull/48894

**Comment by devurandom** [comment]
* v50: https://github.com/metabase/metabase/pull/48897
* v51: https://github.com/metabase/metabase/pull/48894
