### PR TITLE
Prevent repeated coercion of fields

### LINKED ISSUE #22519: Models fails query, when columns are using Casting in Data Model
**Describe the bug**
When a Model is created of a table that has columns that use Casting in the Data Model, then queries to the Model fails because of double-casting.

Workaround: Instead of creating the Model from a GUI question, use a SQL question instead as the base for the Model, which prevents the double-casting.

**To Reproduce**
1. Admin > Data Model > Sample > Reviews > Rating - set "Cast to a specific data type" = `UNIX Seconds -> Datetime`
image
2. Question > Sample > Reviews - save as "Q1"
image
3. Turn into a Model will fail the query, because it's trying to cast the column twice
On MySQL it creates an empty column instead of an error, which is a lot more confusing, when trying to debug.

```SQL
SELECT "source"."ID" AS "ID",
       "source"."PRODUCT_ID" AS "PRODUCT_ID",
       "source"."REVIEWER" AS "REVIEWER",
       timestampadd('second', "source"."RATING", TIMESTAMP '1970-01-01T00:00:00Z') AS "RATING",
       "source"."BODY" AS "BODY",
       "source"."CREATED_AT" AS "CREATED_AT"
FROM
  (SELECT "PUBLIC"."REVIEWS"."ID" AS "ID",
          "PUBLIC"."REVIEWS"."PRODUCT_ID" AS "PRODUCT_ID",
          "PUBLIC"."REVIEWS"."REVIEWER" AS "REVIEWER",
          timestampadd('second', "PUBLIC"."REVIEWS"."RATING", TIMESTAMP '1970-01-01T00:00:00Z') AS "RATING",
          "PUBLIC"."REVIEWS"."BODY" AS "BODY",
          "PUBLIC"."REVIEWS"."CREATED_AT" AS "CREATED_AT"
   FROM "PUBLIC"."REVIEWS") "source"
LIMIT 2000
```

<details><summary>Full stacktrace</summary>

```
2022-05-08 12:44:18,359 INFO api.dataset :: Source query for this query is Card 901
2022-05-08 12:44:19,087 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2022-05-08T12:44:18.417149+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class org.h2.jdbc.JdbcSQLException,
   :error
   "Data conversion error converting \"1970-01-01 01:00:05\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 9f2e21dfcb7857815de23311b218209b37c76b1c807502a4b9c365fc436415ef\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"source\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"source\".\"BODY\" AS \"BODY\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\" FROM (SELECT \"PUBLIC\".\"REVIEWS\".\"ID\" AS \"ID\", \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"REVIEWS\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"PUBLIC\".\"REVIEWS\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"PUBLIC\".\"REVIEWS\".\"BODY\" AS \"BODY\", \"PUBLIC\".\"REVIEWS\".\"CREATED_AT\" AS \"CREATED_AT\" FROM \"PUBLIC\".\"REVIEWS\") \"source\" LIMIT 2000 [22018-197]",
   :stacktrace
   ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
    "org.h2.message.DbException.get(DbException.java:168)"
    "org.h2.value.Value.convertTo(Value.java:1116)"
    "org.h2.value.Value.convertTo(Value.java:617)"
    "org.h2.value.Value.convertTo(Value.java:592)"
    "org.h2.value.Value.getLong(Value.java:480)"
    "org.h2.expression.Function.getValueWithArgs(Function.java:1434)"
    "org.h2.expression.Function.getValue(Function.java:567)"
    "org.h2.expression.Alias.getValue(Alias.java:36)"
    "org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1460)"
    "org.h2.result.LazyResult.hasNext(LazyResult.java:79)"
    "org.h2.result.LazyResult.next(LazyResult.java:59)"
    "org.h2.command.dml.Select.queryFlat(Select.java:527)"
    "org.h2.command.dml.Select.queryWithoutCache(Select.java:633)"
    "org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)"
    "org.h2.command.dml.Query.query(Query.java:371)"
    "org.h2.command.dml.Query.query(Query.java:333)"
    "org.h2.command.CommandContainer.query(CommandContainer.java:114)"
    "org.h2.command.Command.executeQuery(Command.java:202)"
    "org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:227)"
    "org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)"
    "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
    "--> driver.sql_jdbc.execute$fn__53956.invokeStatic(execute.clj:367)"
    "driver.sql_jdbc.execute$fn__53956.invoke(execute.clj:365)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:375)"
    "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:372)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__54036.invoke(execute.clj:500)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:499)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc$fn__83394.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__83394.invoke(sql_jdbc.clj:52)"
    "driver.h2$fn__80531.invokeStatic(h2.clj:90)"
    "driver.h2$fn__80531.invoke(h2.clj:87)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51425.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__47208.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50366.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__52898$combined_post_process__52903$combined_post_process_STAR___52904.invoke(query_processor.clj:207)"
    "query_processor$fn__52898$combined_pre_process__52899$combined_pre_process_STAR___52900.invoke(query_processor.clj:204)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51346$fn__51351.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51346.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47451.invoke(fetch_source_query.clj:277)"
    "query_processor.middleware.store$initialize_store$fn__47639$fn__47640.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__47639.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__51618.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48708.invoke(constraints.clj:52)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__51557.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51929.invoke(catch_exceptions.clj:162)"
    "query_processor.reducible$async_qp$qp_STAR___44179$thunk__44181.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___44179.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___44179.invoke(reducible.clj:91)"
    "query_processor.reducible$sync_qp$qp_STAR___44190.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
    "query_processor$fn__52945$process_query_and_save_execution_BANG___52954$fn__52957.invoke(query_processor.clj:337)"
    "query_processor$fn__52945$process_query_and_save_execution_BANG___52954.invoke(query_processor.clj:330)"
    "query_processor$fn__52989$process_query_and_save_with_max_results_constraints_BANG___52998$fn__53001.invoke(query_processor.clj:349)"
    "query_processor$fn__52989$process_query_and_save_with_max_results_constraints_BANG___52998.invoke(query_processor.clj:342)"
    "api.dataset$run_query_async$fn__66603.invoke(dataset.clj:68)"
    "query_processor.streaming$streaming_response_STAR_$fn__39302$fn__39303.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__39302.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
   :state "22018"}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: Data conversion error converting \"1970-01-01 01:00:05\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 9f2e21dfcb7857815de23311b218209b37c76b1c807502a4b9c365fc436415ef\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"source\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"source\".\"BODY\" AS \"BODY\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\" FROM (SELECT \"PUBLIC\".\"REVIEWS\".\"ID\" AS \"ID\", \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"REVIEWS\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"PUBLIC\".\"REVIEWS\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"PUBLIC\".\"REVIEWS\".\"BODY\" AS \"BODY\", \"PUBLIC\".\"REVIEWS\".\"CREATED_AT\" AS \"CREATED_AT\" FROM \"PUBLIC\".\"REVIEWS\") \"source\" LIMIT 2000 [22018-197]",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__54036.invoke(execute.clj:502)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:499)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
    "driver.sql_jdbc$fn__83394.invokeStatic(sql_jdbc.clj:54)"
    "driver.sql_jdbc$fn__83394.invoke(sql_jdbc.clj:52)"
    "driver.h2$fn__80531.invokeStatic(h2.clj:90)"
    "driver.h2$fn__80531.invoke(h2.clj:87)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51425.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__47208.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50366.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__52898$combined_post_process__52903$combined_post_process_STAR___52904.invoke(query_processor.clj:207)"
    "query_processor$fn__52898$combined_pre_process__52899$combined_pre_process_STAR___52900.invoke(query_processor.clj:204)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51346$fn__51351.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:75)"
    "driver$do_with_driver.invoke(driver.clj:71)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51346.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47451.invoke(fetch_source_query.clj:277)"
    "query_processor.middleware.store$initialize_store$fn__47639$fn__47640.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
    "query_processor.store$do_with_store.invoke(store.clj:38)"
    "query_processor.middleware.store$initialize_store$fn__47639.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__51618.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__48708.invoke(constraints.clj:52)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__51557.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51929.invoke(catch_exceptions.clj:162)"
    "query_processor.reducible$async_qp$qp_STAR___44179$thunk__44181.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___44179.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___44179.invoke(reducible.clj:91)"
    "query_processor.reducible$sync_qp$qp_STAR___44190.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
    "query_processor$fn__52945$process_query_and_save_execution_BANG___52954$fn__52957.invoke(query_processor.clj:337)"
    "query_processor$fn__52945$process_query_and_save_execution_BANG___52954.invoke(query_processor.clj:330)"
    "query_processor$fn__52989$process_query_and_save_with_max_results_constraints_BANG___52998$fn__53001.invoke(query_processor.clj:349)"
    "query_processor$fn__52989$process_query_and_save_with_max_results_constraints_BANG___52998.invoke(query_processor.clj:342)"
    "api.dataset$run_query_async$fn__66603.invoke(dataset.clj:68)"
    "query_processor.streaming$streaming_response_STAR_$fn__39302$fn__39303.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__39302.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: MBQL queryHash: 9f2e21dfcb7857815de23311b218209b37c76b1c807502a4b9c365fc436415ef\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"source\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"source\".\"BODY\" AS \"BODY\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\" FROM (SELECT \"PUBLIC\".\"REVIEWS\".\"ID\" AS \"ID\", \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"REVIEWS\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"PUBLIC\".\"REVIEWS\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"PUBLIC\".\"REVIEWS\".\"BODY\" AS \"BODY\", \"PUBLIC\".\"REVIEWS\".\"CREATED_AT\" AS \"CREATED_AT\" FROM \"PUBLIC\".\"REVIEWS\") \"source\" LIMIT 2000",
    :params nil,
    :type :invalid-query}}],
 :error_type :invalid-query,
 :json_query
 {:type "query",
  :database 4,
  :query {:source-table "card__901"},
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"ID\" AS \"ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"source\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"source\".\"BODY\" AS \"BODY\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\" FROM (SELECT \"PUBLIC\".\"REVIEWS\".\"ID\" AS \"ID\", \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"REVIEWS\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"PUBLIC\".\"REVIEWS\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"PUBLIC\".\"REVIEWS\".\"BODY\" AS \"BODY\", \"PUBLIC\".\"REVIEWS\".\"CREATED_AT\" AS \"CREATED_AT\" FROM \"PUBLIC\".\"REVIEWS\") \"source\" LIMIT 1048575",
  :params nil},
 :status :failed,
 :class java.lang.NumberFormatException,
 :stacktrace
 ["java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)"
  "java.base/java.lang.Long.parseLong(Long.java:692)"
  "java.base/java.lang.Long.parseLong(Long.java:817)"
  "org.h2.value.Value.convertTo(Value.java:1063)"
  "org.h2.value.Value.convertTo(Value.java:617)"
  "org.h2.value.Value.convertTo(Value.java:592)"
  "org.h2.value.Value.getLong(Value.java:480)"
  "org.h2.expression.Function.getValueWithArgs(Function.java:1434)"
  "org.h2.expression.Function.getValue(Function.java:567)"
  "org.h2.expression.Alias.getValue(Alias.java:36)"
  "org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1460)"
  "org.h2.result.LazyResult.hasNext(LazyResult.java:79)"
  "org.h2.result.LazyResult.next(LazyResult.java:59)"
  "org.h2.command.dml.Select.queryFlat(Select.java:527)"
  "org.h2.command.dml.Select.queryWithoutCache(Select.java:633)"
  "org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)"
  "org.h2.command.dml.Query.query(Query.java:371)"
  "org.h2.command.dml.Query.query(Query.java:333)"
  "org.h2.command.CommandContainer.query(CommandContainer.java:114)"
  "org.h2.command.Command.executeQuery(Command.java:202)"
  "org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:227)"
  "org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__53956.invokeStatic(execute.clj:367)"
  "driver.sql_jdbc.execute$fn__53956.invoke(execute.clj:365)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:375)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:372)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__54036.invoke(execute.clj:500)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:499)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
  "driver.sql_jdbc$fn__83394.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__83394.invoke(sql_jdbc.clj:52)"
  "driver.h2$fn__80531.invokeStatic(h2.clj:90)"
  "driver.h2$fn__80531.invoke(h2.clj:87)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
  "query_processor.context.default$default_runf.invoke(default.clj:65)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51425.invoke(cache.clj:220)"
  "query_processor.middleware.permissions$check_query_permissions$fn__47208.invoke(permissions.clj:109)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50366.invoke(mbql_to_native.clj:23)"
  "query_processor$fn__52898$combined_post_process__52903$combined_post_process_STAR___52904.invoke(query_processor.clj:207)"
  "query_processor$fn__52898$combined_pre_process__52899$combined_pre_process_STAR___52900.invoke(query_processor.clj:204)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51346$fn__51351.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:75)"
  "driver$do_with_driver.invoke(driver.clj:71)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51346.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47451.invoke(fetch_source_query.clj:277)"
  "query_processor.middleware.store$initialize_store$fn__47639$fn__47640.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__47639.invoke(store.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__51618.invoke(normalize_query.clj:22)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__48708.invoke(constraints.clj:52)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__51557.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51929.invoke(catch_exceptions.clj:162)"
  "query_processor.reducible$async_qp$qp_STAR___44179$thunk__44181.invoke(reducible.clj:100)"
  "query_processor.reducible$async_qp$qp_STAR___44179.invoke(reducible.clj:106)"
  "query_processor.reducible$async_qp$qp_STAR___44179.invoke(reducible.clj:91)"
  "query_processor.reducible$sync_qp$qp_STAR___44190.doInvoke(reducible.clj:126)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
  "query_processor$fn__52945$process_query_and_save_execution_BANG___52954$fn__52957.invoke(query_processor.clj:337)"
  "query_processor$fn__52945$process_query_and_save_execution_BANG___52954.invoke(query_processor.clj:330)"
  "query_processor$fn__52989$process_query_and_save_with_max_results_constraints_BANG___52998$fn__53001.invoke(query_processor.clj:349)"
  "query_processor$fn__52989$process_query_and_save_with_max_results_constraints_BANG___52998.invoke(query_processor.clj:342)"
  "api.dataset$run_query_async$fn__66603.invoke(dataset.clj:68)"
  "query_processor.streaming$streaming_response_STAR_$fn__39302$fn__39303.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__39302.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
 :card_id 901,
 :context :ad-hoc,
 :error
 "Data conversion error converting \"1970-01-01 01:00:05\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 9f2e21dfcb7857815de23311b218209b37c76b1c807502a4b9c365fc436415ef\nSELECT \"source\".\"ID\" AS \"ID\", \"source\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"source\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"source\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"source\".\"BODY\" AS \"BODY\", \"source\".\"CREATED_AT\" AS \"CREATED_AT\" FROM (SELECT \"PUBLIC\".\"REVIEWS\".\"ID\" AS \"ID\", \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"REVIEWS\".\"REVIEWER\" AS \"REVIEWER\", timestampadd('second', \"PUBLIC\".\"REVIEWS\".\"RATING\", timestamp '1970-01-01T00:00:00Z') AS \"RATING\", \"PUBLIC\".\"REVIEWS\".\"BODY\" AS \"BODY\", \"PUBLIC\".\"REVIEWS\".\"CREATED_AT\" AS \"CREATED_AT\" FROM \"PUBLIC\".\"REVIEWS\") \"source\" LIMIT 2000 [22018-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :database 4,
  :query
  {:source-card-id 901,
   :source-metadata
   [{:description "A unique internal identifier for the review. Should not be used externally.",
     :semantic_type :type/PK,
     :coercion_strategy nil,
     :name "ID",
     :settings nil,
     :field_ref [:field 111 nil],
     :effective_type :type/BigInteger,
     :id 111,
     :display_name "ID",
     :fingerprint nil,
     :base_type :type/BigInteger}
    {:description "The product the review was for",
     :semantic_type :type/FK,
     :coercion_strategy nil,
     :name "PRODUCT_ID",
     :settings nil,
     :field_ref [:field 110 nil],
     :effective_type :type/Integer,
     :id 110,
     :display_name "Product ID",
     :fingerprint {:global {:distinct-count 176, :nil% 0}},
     :base_type :type/Integer}
    {:description "The user who left the review",
     :semantic_type :type/Name,
     :coercion_strategy nil,
     :name "REVIEWER",
     :settings nil,
     :field_ref [:field 113 nil],
     :effective_type :type/Text,
     :id 113,
     :display_name "Reviewer",
     :fingerprint
     {:global {:distinct-count 1076, :nil% 0},
      :type
      {:type/Text
       {:percent-json 0,
        :percent-url 0,
        :percent-email 0,
        :percent-state 0.001798561151079137,
        :average-length 9.972122302158274}}},
     :base_type :type/Text}
    {:description "The rating (on a scale of 1-5) the user left.",
     :semantic_type :type/CreationTimestamp,
     :coercion_strategy "Coercion/UNIXSeconds->DateTime",
     :unit :default,
     :name "RATING",
     :settings nil,
     :field_ref [:field 115 {:temporal-unit :default}],
     :effective_type :type/DateTime,
     :id 115,
     :display_name "Rating",
     :fingerprint
     {:global {:distinct-count 5, :nil% 0},
      :type {:type/DateTime {:earliest "1970-01-01T01:00:01Z", :latest "1970-01-01T01:00:05Z"}}},
     :base_type :type/DateTime}
    {:description "The review the user left. Limited to 2000 characters.",
     :semantic_type :type/Description,
     :coercion_strategy nil,
     :name "BODY",
     :settings nil,
     :field_ref [:field 112 nil],
     :effective_type :type/Text,
     :id 112,
     :display_name "Body",
     :fingerprint
     {:global {:distinct-count 1112, :nil% 0},
      :type
      {:type/Text
       {:percent-json 0, :percent-url 0, :percent-email 0, :percent-state 0, :average-length 177.41996402877697}}},
     :base_type :type/Text}
    {:description "The day and time a review was written by a user.",
     :semantic_type :type/CreationTimestamp,
     :coercion_strategy nil,
     :unit :default,
     :name "CREATED_AT",
     :settings nil,
     :field_ref [:field 114 {:temporal-unit :default}],
     :effective_type :type/DateTime,
     :id 114,
     :display_name "Created At",
     :fingerprint
     {:global {:distinct-count 1112, :nil% 0},
      :type {:type/DateTime {:earliest "2016-06-03T00:37:05.818Z", :latest "2020-04-19T14:15:25.677Z"}}},
     :base_type :type/DateTime}],
   :source-query/dataset? true,
   :fields
   [[:field 111 nil]
    [:field 110 nil]
    [:field 113 nil]
    [:field 115 {:temporal-unit :default}]
    [:field 112 nil]
    [:field 114 {:temporal-unit :default}]],
   :source-query
   {:source-table 13,
    :fields
    [[:field 111 nil]
     [:field 110 nil]
     [:field 113 nil]
     [:field 115 {:temporal-unit :default}]
     [:field 112 nil]
     [:field 114 {:temporal-unit :default}]]},
   :limit 1048575,
   :metabase.query-processor.middleware.limit/original-limit nil},
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id 901,
   :metadata/dataset-metadata
   [{:description "A unique internal identifier for the review. Should not be used externally.",
     :semantic_type :type/PK,
     :name "ID",
     :field_ref [:field 111 nil],
     :effective_type :type/BigInteger,
     :id 111,
     :display_name "ID",
     :base_type :type/BigInteger}
    {:description "The product the review was for",
     :semantic_type :type/FK,
     :name "PRODUCT_ID",
     :field_ref [:field 110 nil],
     :effective_type :type/Integer,
     :id 110,
     :display_name "Product ID",
     :fingerprint {:global {:distinct-count 176, :nil% 0}},
     :base_type :type/Integer}
    {:description "The user who left the review",
     :semantic_type :type/Name,
     :name "REVIEWER",
     :field_ref [:field 113 nil],
     :effective_type :type/Text,
     :id 113,
     :display_name "Reviewer",
     :fingerprint
     {:global {:distinct-count 1076, :nil% 0},
      :type
      {:type/Text
       {:percent-json 0,
        :percent-url 0,
        :percent-email 0,
        :percent-state 0.001798561151079137,
        :average-length 9.972122302158274}}},
     :base_type :type/Text}
    {:description "The rating (on a scale of 1-5) the user left.",
     :semantic_type :type/CreationTimestamp,
     :coercion_strategy "Coercion/UNIXSeconds->DateTime",
     :unit :default,
     :name "RATING",
     :field_ref [:field 115 {:temporal-unit :default}],
     :effective_type :type/DateTime,
     :id 115,
     :display_name "Rating",
     :fingerprint
     {:global {:distinct-count 5, :nil% 0},
      :type {:type/DateTime {:earliest "1970-01-01T01:00:01Z", :latest "1970-01-01T01:00:05Z"}}},
     :base_type :type/DateTime}
    {:description "The review the user left. Limited to 2000 characters.",
     :semantic_type :type/Description,
     :name "BODY",
     :field_ref [:field 112 nil],
     :effective_type :type/Text,
     :id 112,
     :display_name "Body",
     :fingerprint
     {:global {:distinct-count 1112, :nil% 0},
      :type
      {:type/Text
       {:percent-json 0, :percent-url 0, :percent-email 0, :percent-state 0, :average-length 177.41996402877697}}},
     :base_type :type/Text}
    {:description "The day and time a review was written by a user.",
     :semantic_type :type/CreationTimestamp,
     :unit :default,
     :name "CREATED_AT",
     :field_ref [:field 114 {:temporal-unit :default}],
     :effective_type :type/DateTime,
     :id 114,
     :display_name "Created At",
     :fingerprint
     {:global {:distinct-count 1112, :nil% 0},
      :type {:type/DateTime {:earliest "2016-06-03T00:37:05.818Z", :latest "2020-04-19T14:15:25.677Z"}}},
     :base_type :type/DateTime}]}},
 :data {:rows [], :cols []}}

2022-05-08 12:44:19,101 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 743.4 ms (37 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (117 total active threads) Queries in flight: 1 (0 queued); h2 DB 4 connections: 0/1 (0 threads blocked)
```

</details>

**Information about your Metabase Installation:**
Tested 0.42.0 thru 0.43.0

**Additional context**
Historically the same as #12430, but this seems to only apply to Models

### PR DESCRIPTION
**Pull request by metamben**
Fixes #22519.

It seems to me that the problem is that we don't distinguish fields coming from the source table from the references to those fields in outer queries based on the results of the selection. A similar issue arises in the SQL query processor when it nests queries containing expressions. There the problem is solved by marking the fields in the outer select as such and excluding the fields so marked from casting.

My solutions is attempt to implement this scheme for all situations when a field is a reference to a field returned from a nested query.

There are some specific points too that I wanted to highlight:

- The current implementation marks the fields after implicit fields have been added but before joins are (pre)processed.
- A namespaced keyword is used as a marker (a name is probably not the best one).
- Only the SQL driver honors the new marker (though the regression test seems to pass for all drivers supporting nesting).

*TODO*

- [x] Fix coerced fields "inherited" from joins.
- [x] Check DB types other than SQL.
  - It seems to me that other DB types don't support models at all... At least I couldn't create the model described in the bug ticket with a Mongo database.
- [x] Don't remove `:nested/outer` from the metadata, adjust the tests instead.

### CODE REVIEW

File: src/metabase/driver/sql/query_processor.clj [hunk 1]
```diff
@@ -353,14 +353,15 @@
...
   [driver [_ id-or-name {:keys             [database-type]
-                         ::nest-query/keys [outer-select]
                          :as               options}
            :as field-clause]]
   (try
     (let [source-table-aliases (field-source-table-aliases field-clause)
           source-alias         (field-source-alias field-clause)
           field                (when (integer? id-or-name)
                                  (qp.store/field id-or-name))
+          outer-select         (or (:metabase.query-processor.middleware.mark-outer-select-fields/outer-select options)
```
Comment (metamben) [inline src/metabase/driver/sql/query_processor.clj:363]: I don't like this name. Since it's not SQL specific, `select` doesn't sound well. (I will `:as-alias` the namespace, I think, when I get the name right.)

File: src/metabase/query_processor/middleware/annotate.clj [hunk 2]
```diff
@@ -193,7 +193,8 @@
         ;; remapping based on that info)
         namespaced-options        (not-empty (into {}
                                                    (filter (fn [[k _v]]
-                                                             (and (keyword? k) (namespace k))))
+                                                             (and (keyword? k) (namespace k)
+                                                                  (not= k :metabase.query-processor.middleware.mark-outer-select-fields/outer-select))))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/annotate.clj:197]: I'm not quite sure what the logic is behind `namespaced-options`. I'm removing this "annotation" because it's really only needed during compilation and leaving it here makes a lot of tests fail.

File: src/metabase/query_processor/middleware/mark_outer_select_fields.clj [hunk 3]
```diff
@@ -0,0 +1,33 @@
+(ns metabase.query-processor.middleware.mark-outer-select-fields
+  (:require [clojure.walk :as walk]))
+
+(defn- matching-fields?
+  [field source-field]
+  (every? #(= (field %) (source-field %)) [0 1]))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/mark_outer_select_fields.clj:6]: Is matching the type and the "ID" of the clause good (enough)?

File: src/metabase/driver/sql/query_processor.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/driver/sql/query_processor.clj:363]: Should we unify the keywords? Might as well replace all usages of `::nest-query/outer-select` with the new `mark-outer-select-fields/outer-select`? Or is that annoying for now or planned follow up work?

File: src/metabase/query_processor/middleware/annotate.clj (hunk 2 above)
Comment (dpsutton) [reply src/metabase/query_processor/middleware/annotate.clj:197]: I think we should check if we can get the tests passing. Perhaps we can do some judicious use of `partial=` to handle new keys? As it stands, this code makes me think its "special" rather than just unnecessary and removed for tests. Do you remember how many tests were failing?

File: src/metabase/query_processor/middleware/mark_outer_select_fields.clj (hunk 3 above)
Comment (dpsutton) [reply src/metabase/query_processor/middleware/mark_outer_select_fields.clj:6]: It's really hard to parse this. I'm assuming `field` is a map representing a field. You are treating it like a vector, maybe a field_ref?

File: src/metabase/driver/sql/query_processor.clj (hunk 1 above)
Comment (metamben) [reply src/metabase/driver/sql/query_processor.clj:363]: If we agree that the meaning is the same, then we should use the same key, I think.

Comment (dpsutton) [reply src/metabase/driver/sql/query_processor.clj:363]: Yes I believe these mean the same thing: a conversion has been applied already so don't convert again. We can also use a non-namespace aliased key `:nested/outer` or `:nested/inner` so we don't need to worry about requiring namespaces for the namespace of a key. 

If I'm misreading this then I apologize.

File: src/metabase/query_processor/middleware/mark_outer_select_fields.clj (hunk 3 above)
Comment (metamben) [reply src/metabase/query_processor/middleware/mark_outer_select_fields.clj:6]: My expectation was that since both `field` and `source-field` are direct children of a `:fields` clause they have the form `[:field name-or-id opts]` and I check if the first two respective elements match. I was hoping that I can use simple equality, but the `opts` can be different because middlewares can add different annotations based on where the fields are in the query. I'm not sure though that `opts` can fully be ignored (i.e., if nothing there is part of the "identity" of the field).

**Comment by metamben** [comment]
> we can attempt to do this where we "bubble up" the fields in the first place: `metabase.query-processor.middleware.annotate`: `flow-field-metadata` (i think that's the end of the list). Did you look at setting it from this side rather than trying to recognize it after the fact?

I was thinking about this, but haven't found the place. I'm going to have a look at it now.

File: src/metabase/query_processor/middleware/annotate.clj (hunk 2 above)
Comment (dpsutton) [reply src/metabase/query_processor/middleware/annotate.clj:197]: I would expect them to be different in exactly the current circumstance. Suppose `foo` is an integer column that has a `:Coercion/UNIXSeconds->DateTime` coercion on it. I would expect the query to be

`select foo from (select from_unixtime(foo) from t)`

I think we have to do the coercion at its lowest level. We really want no part of the query to see the integer of `foo`, it should be a timestamp type value throughout.

File: src/metabase/query_processor/middleware/mark_outer_select_fields.clj (hunk 3 above)
Comment (dpsutton) [reply src/metabase/query_processor/middleware/mark_outer_select_fields.clj:6]: ah yeah they are field-refs then. I have `metabase.query-processor.util/field-ref->key` that I use. I've seen @camsaul has a similar function somewhere that grabs what's important out of the options. If you reuse the function i've listed we can more easily keep track of all of these and fix them at once.

File: src/metabase/query_processor/middleware/annotate.clj (hunk 2 above)
Comment (metamben) [reply src/metabase/query_processor/middleware/annotate.clj:197]: I think you misunderstood what I meant. In your example what I wanted to say was that I expected the metadata to be the same for `select from_unixtime(foo) as foo from t` and `select foo from (select from_unixtime(foo) as foo from t)`. In other words, just wrapping a select `s` into a `select * from (s)` should not "change" the metadata.

**Comment by metamben** [comment]
> `metabase.query-processor.middleware.annotate`: `flow-field-metadata`

@dpsutton Do you mean the call via the `add-column-info` middleware? It seems to me that's a post-processing middleware and runs after the compilation (and execution). If you mean something else, then what?

**Comment by dpsutton** [comment]
dang. i think you are right. I'd have to spend more time looking for that seam. I'm sorry to have mislead you.

**Comment by metamben** [comment]
@nemanjaglumac Are you OK with https://github.com/metabase/metabase/pull/24718/commits/a295fbcf51a0b76c0dbb9a3dab32cb72266114b5 fixing the repo test?

**Comment by nemanjaglumac** [comment]
> @nemanjaglumac Are you OK with [a295fbc](https://github.com/metabase/metabase/commit/a295fbcf51a0b76c0dbb9a3dab32cb72266114b5) fixing the repo test?

@metamben absolutely. That was my mistake. Great catch! Thank you :)

File: src/metabase/query_processor/middleware/mark_outer_fields.clj [hunk 4]
```diff
@@ -0,0 +1,36 @@
+(ns metabase.query-processor.middleware.mark-outer-fields
+  (:require [clojure.walk :as walk]
+            [metabase.mbql.util :as mbql.u]
+            [metabase.query-processor.util :as qp.util]))
+
+(defn- matching-fields?
+  [field source-field]
+  (= (qp.util/field-ref->key field) (qp.util/field-ref->key source-field)))
```
Comment (dpsutton) [inline src/metabase/query_processor/middleware/mark_outer_fields.clj:8]: this expects a field_ref, not a field. You'll need `(comp qp.util/field-ref->key :field_ref)` as the function applied before checking equality.

**Comment by dpsutton** [comment]
This looks awesome. I think I'm seeing a scenario that it doesn't work though: when adding an order by clause.

```clojure
qp=> (mt/dataset sample-dataset
       (mt/with-temp-vals-in-db Field (mt/id :reviews :rating)
         {:coercion_strategy :Coercion/UNIXSeconds->DateTime
          :effective_type    :type/Instant}
         (mt/with-temp Card [{card-id :id}
                             {:dataset_query
                              (mt/mbql-query reviews
                                             {:fields [$rating]
                                              :limit  3})}]
           (qp/process-query {:type     :query
                              :database (mt/id)
                              :query    {:source-table (str "card__" card-id)
                                         :order-by [[(mt/id :reviews :rating) :desc]]}}))))
Execution error (NumberFormatException) at java.lang.NumberFormatException/forInputString (NumberFormatException.java:67).
For input string: "1970-01-01 00:00:05"
qp=> 
```

I was wondering what the `:nested/outer      true` is doing in `rewrite-fields-to-force-using-column-aliases`. It seems like some of the breakout fields and sorting goes through this but not all. So the above is running:

```sql
 SELECT   "source"."RATING" AS "RATING"
FROM     (
                SELECT timestampadd('second', "PUBLIC"."REVIEWS"."RATING", timestamp '1970-01-01T00:00:00Z') AS "RATING"
                FROM   "PUBLIC"."REVIEWS" limit 3) "source"
ORDER BY timestampadd('second', "source"."RATING", timestamp '1970-01-01T00:00:00Z') DESC limit 1048575 
```

So I wonder if its possible to have your walk descend into other clauses (breakouts, order bys) and add the metadata there. We want to cast once and only once correct?

File: src/metabase/query_processor/middleware/mark_outer_fields.clj (hunk 4 above)
Comment (metamben) [reply src/metabase/query_processor/middleware/mark_outer_fields.clj:8]: I'm confused. This is supposed to be called with two triples (vectors of length 3) with the first value being `:field`, the second an id or a name and we don't care about the third. Calling `:field_ref` would return `nil`. I'll have a look to see where `:field_ref`s come into play.

**Comment by metamben** [comment]
Leaving `:nested/outer` in the metadata makes the models e2e test about 9 times out of 10.

**Comment by metamben** [comment]
@dpsutton I've added support for breakout and ordering.

File: src/metabase/query_processor/middleware/mark_outer_fields.clj [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+   (fn [form]
+     (let [source-fields (get-in form [:source-query :fields])]
+       (if (and (map? form)
+                (seqable? source-fields)
+                (seq source-fields))
+         (let [id-set (into #{} (map second) source-fields)]
+           (-> form
+               (m/update-existing :fields annotate-outer-fields id-set)
+               (m/update-existing :breakout annotate-outer-fields id-set)
+               (m/update-existing :order-by annotate-outer-fields id-set)))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/mark_outer_fields.clj:22]: Could `reduce` if that's more readable.

Comment (dpsutton) [reply src/metabase/query_processor/middleware/mark_outer_fields.clj:22]: I think this is very readable as is.

**Review by dpsutton — APPROVED** [review]
Looks great to me. I think this is a nice improvement and should make queries more speedy.

**Review by camsaul — APPROVED** [review]
