### PR TITLE
Fix Popover Footer placement when filter is not equalOps

### LINKED ISSUE #16830: Popover footer is displaced when using filter with a search input
**Describe the bug**
When using SQL field filter > string the popover footer is displaced. Please see the screenshot.
The same thing happens for dashboards because they use the same component. What's important is that the filter popover has some kind of search input field.

**Logs**
N/A

**To Reproduce**
1. Ask question > Native
2. Enter `SELECT * FROM products where {{ filter }}`
3. In the right sidebar choose Field Filter type and map it to Products.Category
image
4. For the filter widget type choose anything except `None` or simple `String`. For example, `String contains` will do.
5. Save question
6. Click on the filter widget (left, near the top, by "Sample Dataset" text, and notice the footer is displaced and is flowing outside of the boundaries of the popover.

**Expected behavior**
Popover footer should look like the integral part of the popover.

**Screenshots**
image

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
local dev, x.40.0-snapshot, aa78e38494811da129b2c2af5ddc9d3df3d8fe30

**Severity**
UX/UI, but it is a regression.

**Additional context**
This happens for:
- String
    - is not
    - contains
    - does not contain
    -  starts with
    - ends with

- Number*
    - not equal to
    - between
    - greater than or equal to
    - less than or equal to

*Why it doesn't happen for "equal to", although it also uses search?

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #16830

## To Test

1. Ask question › Native
2. Enter `SELECT * FROM products where {{ filter }}`
3. In the right sidebar, choose Field Filter type and map it to Products.Category
image
4. For the filter widget type choose anything except `None` or simple `String`. For example, `String contains` will do.
5. Save question
6. Click on the filter widget (left, near the top, by "Sample Dataset" text, and notice the footer is displaced and is flowing outside of the boundaries of the popover.

### After

image

### Before 
image

### CODE REVIEW

File: frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget.jsx [hunk 1]
```diff
@@ -130,7 +130,7 @@ export default class ParameterFieldWidget extends Component<*, Props, State> {
 
     const footerClassName = cx(
       "flex mt1 px1 pb1 PopoverFooter PopoverParameterFieldWidgetFooter",
-      isEqualsOp && "mr1 mb1",
+      isEqualsOp ? "mr1 mb1" : "PopoverFooterWhenIsNotEqualOps",
```
Comment (gusaiani) [inline frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget.jsx:133]: Very remedial.

All that underlies this needs a complete revamp.

**Review by nemanjaglumac — APPROVED** [review]
Tested on a few different screen sizes - looking good :)

Can't wait for the visual regression tests for this type of visual bugs.

**Comment by gusaiani** [comment]
@nemanjaglumac going off topic here, I have yet to see visual regression tests covering such far corners of an application.

Given the cost of producing all the screenshots.

I can be totally wrong here, I have never experienced it like this. 

Time and work will tell.
