### PR TITLE
Field Filter Value Normalization in Embedding Endpoints

### LINKED ISSUE #27643: Field filter linked to Boolean column causes an error when used in Embedding
**Describe the bug**
If you create a field filter in a SQL question that is linked to a boolean column, you can use it within a dashboard but when you go to embed it it loses the option of a drop down and starts to ask for a String.

This doesn't happen with the sample H2 database, but I could reproduce it with Metabase Postgres sample database using the Invoices table.

**Logs**
<details><summary>Full stacktrace</summary>

```
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:37:04+01:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: ERROR: syntax error at or near "FROM"
  Position: 305
{:database_id 2,
 :started_at #t "2023-01-12T08:37:01.637005Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query: ERROR: syntax error at or near \"FROM\"\n  Position: 305",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__56096.invoke(execute.clj:501)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:493)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
    "driver.sql_jdbc$fn__94568.invokeStatic(sql_jdbc.clj:58)"
    "driver.sql_jdbc$fn__94568.invoke(sql_jdbc.clj:56)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___53529.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__49184.invoke(permissions.clj:109)"
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__89184.invoke(permissions.clj:124)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__90261.invoke(column_level_perms_check.clj:30)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__52474.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__55005$combined_post_process__55010$combined_post_process_STAR___55011.invoke(query_processor.clj:212)"
    "query_processor$fn__55005$combined_pre_process__55006$combined_pre_process_STAR___55007.invoke(query_processor.clj:209)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450$fn__53455.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:76)"
    "driver$do_with_driver.invoke(driver.clj:72)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49450.invoke(fetch_source_query.clj:314)"
    "query_processor.middleware.store$initialize_store$fn__49640$fn__49641.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:45)"
    "query_processor.store$do_with_store.invoke(store.clj:39)"
    "query_processor.middleware.store$initialize_store$fn__49640.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__53722.invoke(normalize_query.clj:22)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__60456.invoke(handle_audit_queries.clj:130)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__50728.invoke(constraints.clj:53)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__53661.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__54033.invoke(catch_exceptions.clj:167)"
    "query_processor.reducible$async_qp$qp_STAR___45482$thunk__45484.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___45482.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___45482.invoke(reducible.clj:91)"
    "query_processor.reducible$sync_qp$qp_STAR___45493.doInvoke(reducible.clj:126)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:327)"
    "query_processor$fn__55052$process_query_and_save_execution_BANG___55061$fn__55064.invoke(query_processor.clj:342)"
    "query_processor$fn__55052$process_query_and_save_execution_BANG___55061.invoke(query_processor.clj:335)"
    "query_processor$fn__55096$process_query_and_save_with_max_results_constraints_BANG___55105$fn__55108.invoke(query_processor.clj:354)"
    "query_processor$fn__55096$process_query_and_save_with_max_results_constraints_BANG___55105.invoke(query_processor.clj:347)"
    "api.dataset$run_query_async$fn__71130.invoke(dataset.clj:69)"
    "query_processor.streaming$streaming_response_STAR_$fn__40578$fn__40579.invoke(streaming.clj:162)"
    "query_processor.streaming$streaming_response_STAR_$fn__40578.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__20017.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: native queryHash: 13000ef3f5429f992fe8910e79e48c5aed8c2095f9ea995b22289be44aac00ed\nSELECT \"public\".\"core_user\".\"id\" AS \"id\", \"public\".\"core_user\".\"email\" AS \"email\",\"public\".\"core_user\".\"date_joined\" AS \"date_joined\", \"public\".\"core_user\".\"last_login\" AS \"last_login\",\nFROM \"public\".\"core_user\"\nLIMIT 1048575",
    :params nil,
    :type :invalid-query}}],
 :state "42601",
 :error_type :invalid-query,
 :json_query
 {:type "native",
  :native
  {:query
   "SELECT \"public\".\"core_user\".\"id\" AS \"id\", \"public\".\"core_user\".\"email\" AS \"email\",\"public\".\"core_user\".\"date_joined\" AS \"date_joined\", \"public\".\"core_user\".\"last_login\" AS \"last_login\",\nFROM \"public\".\"core_user\"\nLIMIT 1048575",
   :template-tags {}},
  :database 2,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,
 :class org.postgresql.util.PSQLException,
 :stacktrace
 ["org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)"
  "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)"
  "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)"
  "org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)"
  "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)"
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
  "--> driver.sql_jdbc.execute$fn__56016.invokeStatic(execute.clj:366)"
  "driver.sql_jdbc.execute$fn__56016.invoke(execute.clj:364)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:374)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:371)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__56096.invoke(execute.clj:499)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:493)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
  "driver.sql_jdbc$fn__94568.invokeStatic(sql_jdbc.clj:58)"
  "driver.sql_jdbc$fn__94568.invoke(sql_jdbc.clj:56)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
  "query_processor.context.default$default_runf.invoke(default.clj:65)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___53529.invoke(cache.clj:220)"
  "query_processor.middleware.permissions$check_query_permissions$fn__49184.invoke(permissions.clj:109)"
  "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__89184.invoke(permissions.clj:124)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__90261.invoke(column_level_perms_check.clj:30)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__52474.invoke(mbql_to_native.clj:23)"
  "query_processor$fn__55005$combined_post_process__55010$combined_post_process_STAR___55011.invoke(query_processor.clj:212)"
  "query_processor$fn__55005$combined_pre_process__55006$combined_pre_process_STAR___55007.invoke(query_processor.clj:209)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450$fn__53455.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:76)"
  "driver$do_with_driver.invoke(driver.clj:72)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49450.invoke(fetch_source_query.clj:314)"
  "query_processor.middleware.store$initialize_store$fn__49640$fn__49641.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:45)"
  "query_processor.store$do_with_store.invoke(store.clj:39)"
  "query_processor.middleware.store$initialize_store$fn__49640.invoke(store.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__53722.invoke(normalize_query.clj:22)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__60456.invoke(handle_audit_queries.clj:130)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__50728.invoke(constraints.clj:53)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__53661.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__54033.invoke(catch_exceptions.clj:167)"
  "query_processor.reducible$async_qp$qp_STAR___45482$thunk__45484.invoke(reducible.clj:100)"
  "query_processor.reducible$async_qp$qp_STAR___45482.invoke(reducible.clj:106)"
  "query_processor.reducible$async_qp$qp_STAR___45482.invoke(reducible.clj:91)"
  "query_processor.reducible$sync_qp$qp_STAR___45493.doInvoke(reducible.clj:126)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:327)"
  "query_processor$fn__55052$process_query_and_save_execution_BANG___55061$fn__55064.invoke(query_processor.clj:342)"
  "query_processor$fn__55052$process_query_and_save_execution_BANG___55061.invoke(query_processor.clj:335)"
  "query_processor$fn__55096$process_query_and_save_with_max_results_constraints_BANG___55105$fn__55108.invoke(query_processor.clj:354)"
  "query_processor$fn__55096$process_query_and_save_with_max_results_constraints_BANG___55105.invoke(query_processor.clj:347)"
  "api.dataset$run_query_async$fn__71130.invoke(dataset.clj:69)"
  "query_processor.streaming$streaming_response_STAR_$fn__40578$fn__40579.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__40578.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$task__20017.invoke(streaming_response.clj:84)"],
 :card_id nil,
 :context :ad-hoc,
 :error "ERROR: syntax error at or near \"FROM\"\n  Position: 305",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}

[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:37:04+01:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: canceled] 2.6 s (4 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (5 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:37:18+01:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 94.7 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 4/50 (5 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:37:19+01:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 110.2 ms (6 DB calls) App DB connections: 1/4 Jetty threads: 4/50 (5 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:37:25+01:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 68.5 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 4/50 (8 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:37:31+01:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 70.7 ms (6 DB calls) App DB connections: 1/4 Jetty threads: 4/50 (9 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:38:08+01:00 DEBUG metabase.server.middleware.log GET /api/field/218/values 200 500.0 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (7 idle, 0 queued) (70 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:38:40+01:00 DEBUG metabase.server.middleware.log GET /api/collection 200 68.9 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (7 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:01+01:00 INFO metabase.models.card Card references Fields in params: (218)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:01+01:00 DEBUG metabase.server.middleware.log POST /api/card 200 452.0 ms (14 DB calls) App DB connections: 1/4 Jetty threads: 5/50 (7 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:01+01:00 DEBUG metabase.server.middleware.log GET /api/database 200 82.7 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (6 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:01+01:00 DEBUG metabase.server.middleware.log GET /api/search 200 153.4 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (6 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:09+01:00 DEBUG metabase.server.middleware.log POST /api/card/12/query 202 [ASYNC: completed] 378.2 ms (15 DB calls) App DB connections: 2/4 Jetty threads: 4/50 (6 idle, 0 queued) (73 total active threads) Queries in flight: 1 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:13+01:00 DEBUG metabase.server.middleware.log POST /api/card/12/query 202 [ASYNC: completed] 133.6 ms (13 DB calls) App DB connections: 1/4 Jetty threads: 4/50 (6 idle, 0 queued) (74 total active threads) Queries in flight: 1 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:16+01:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 31.8 ms (2 DB calls) App DB connections: 0/4 Jetty threads: 8/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:16+01:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 77.5 ms (7 DB calls) App DB connections: 0/4 Jetty threads: 7/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:16+01:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 200 232.7 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:16+01:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 200 285.9 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (3 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:20+01:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 200 66.5 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (3 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:21+01:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 200 51.8 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (3 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:23+01:00 DEBUG metabase.server.middleware.log GET /api/dashboard/5 200 99.8 ms (6 DB calls) App DB connections: 1/4 Jetty threads: 5/50 (3 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:27+01:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 200 55.4 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (3 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:33+01:00 DEBUG metabase.server.middleware.log GET /api/card/12 200 79.2 ms (9 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (3 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:33+01:00 DEBUG metabase.server.middleware.log GET /api/field/218 200 54.9 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (3 idle, 0 queued) (74 total active threads) Queries in flight: 1 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:33+01:00 DEBUG metabase.server.middleware.log POST /api/card/12/query 202 [ASYNC: completed] 151.9 ms (13 DB calls) App DB connections: 1/4 Jetty threads: 4/50 (3 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:55+01:00 INFO metabase.models.dashboard Referenced Fields in Dashboard params have changed: Was: #{} Is Now: #{218} Newly Added: #{218}
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:55+01:00 DEBUG metabase.server.middleware.log POST /api/dashboard/5/cards 200 214.5 ms (18 DB calls) App DB connections: 1/4 Jetty threads: 5/50 (3 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:55+01:00 DEBUG metabase.server.middleware.log PUT /api/dashboard/5 200 52.3 ms (8 DB calls) App DB connections: 1/4 Jetty threads: 5/50 (3 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:55+01:00 DEBUG metabase.server.middleware.log PUT /api/dashboard/5/cards 200 214.6 ms (25 DB calls) App DB connections: 1/4 Jetty threads: 5/50 (3 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:55+01:00 DEBUG metabase.server.middleware.log PUT /api/dashboard/5 200 50.9 ms (8 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (3 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:55+01:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 24.3 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 7/50 (3 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:56+01:00 DEBUG metabase.server.middleware.log GET /api/dashboard/5 200 159.2 ms (12 DB calls) App DB connections: 1/4 Jetty threads: 5/50 (3 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:39:58+01:00 DEBUG metabase.server.middleware.log GET /api/dashboard/5/params/d6892b8a/values 200 99.3 ms (10 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (3 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:01+01:00 DEBUG metabase.server.middleware.log POST /api/dashboard/5/dashcard/7/card/12/query 202 [ASYNC: completed] 220.9 ms (20 DB calls) App DB connections: 1/4 Jetty threads: 4/50 (3 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:02+01:00 DEBUG metabase.server.middleware.log POST /api/dashboard/5/dashcard/7/card/12/query 202 [ASYNC: completed] 122.6 ms (19 DB calls) App DB connections: 1/4 Jetty threads: 4/50 (3 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:31+01:00 INFO metabase.public-settings.premium-features Checking with the MetaStore to see whether a692...5bb1 is valid...
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:31+01:00 DEBUG metabase.server.middleware.log GET /api/preview_embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjV9LCJwYXJhbXMiOnt9LCJpYXQiOjE2NzM1MTI4MjksIl9lbWJlZGRpbmdfcGFyYW1zIjp7fX0.bp-17ijL9bUTBeB1V5VrgtRmUZBws-fB7Vx0IeKebCE 200 525.8 ms (7 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (4 idle, 0 queued) (76 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:32+01:00 DEBUG metabase.server.middleware.log GET /api/preview_embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjV9LCJwYXJhbXMiOnt9LCJpYXQiOjE2NzM1MTI4MjksIl9lbWJlZGRpbmdfcGFyYW1zIjp7fX0.bp-17ijL9bUTBeB1V5VrgtRmUZBws-fB7Vx0IeKebCE/dashcard/7/card/12 202 [ASYNC: completed] 621.1 ms (18 DB calls) App DB connections: 2/4 Jetty threads: 5/50 (4 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:32+01:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 1.3 s (4 DB calls) App DB connections: 2/4 Jetty threads: 5/50 (4 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:36+01:00 DEBUG metabase.server.middleware.log GET /api/preview_embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjV9LCJwYXJhbXMiOnt9LCJpYXQiOjE2NzM1MTI4MzYsIl9lbWJlZGRpbmdfcGFyYW1zIjp7fX0.fm82q4Gx1BAzanmKMiNMmw6xn7bT0oVoh0xL9Y6J65E 200 66.5 ms (7 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (4 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:36+01:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 100.0 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (4 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:36+01:00 DEBUG metabase.server.middleware.log GET /api/preview_embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjV9LCJwYXJhbXMiOnt9LCJpYXQiOjE2NzM1MTI4MzYsIl9lbWJlZGRpbmdfcGFyYW1zIjp7fX0.fm82q4Gx1BAzanmKMiNMmw6xn7bT0oVoh0xL9Y6J65E/dashcard/7/card/12 202 [ASYNC: completed] 160.5 ms (18 DB calls) App DB connections: 2/4 Jetty threads: 4/50 (4 idle, 0 queued) (78 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:41+01:00 DEBUG metabase.server.middleware.log GET /api/preview_embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjV9LCJwYXJhbXMiOnt9LCJpYXQiOjE2NzM1MTI4NDEsIl9lbWJlZGRpbmdfcGFyYW1zIjp7InRleHQiOiJlbmFibGVkIn19.YAZpKZCVW5y7_TuiwZ63pvL8gF_YqRk8r1bTle1yoV4 200 45.6 ms (7 DB calls) App DB connections: 0/4 Jetty threads: 6/50 (4 idle, 0 queued) (78 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:41+01:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 91.7 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (4 idle, 0 queued) (78 total active threads) Queries in flight: 0 (0 queued)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:41+01:00 DEBUG metabase.server.middleware.log GET /api/preview_embed/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjV9LCJwYXJhbXMiOnt9LCJpYXQiOjE2NzM1MTI4NDEsIl9lbWJlZGRpbmdfcGFyYW1zIjp7InRleHQiOiJlbmFibGVkIn19.YAZpKZCVW5y7_TuiwZ63pvL8gF_YqRk8r1bTle1yoV4/dashcard/7/card/12 202 [ASYNC: completed] 129.4 ms (18 DB calls) App DB connections: 2/4 Jetty threads: 4/50 (4 idle, 0 queued) (79 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:43+01:00 WARN metabase.server.middleware.log GET /api/dashboard/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjV9LCJwYXJhbXMiOnt9LCJpYXQiOjE2NzM1MTI4NDEsIl9lbWJlZGRpbmdfcGFyYW1zIjp7InRleHQiOiJlbmFibGVkIn19.YAZpKZCVW5y7_TuiwZ63pvL8gF_YqRk8r1bTle1yoV4/params/d6892b8a/values 404 6.3 ms (0 DB calls) 
"API endpoint does not exist."

[e6b76751-2d04-4d9f-94fb-9195e4f7383b] 2023-01-12T09:40:49+01:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: ERROR: operator does not exist: boolean = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 484
{:database_id 2,
 :started_at #t "2023-01-12T08:40:48.029120Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: ERROR: operator does not exist: boolean = character varying\n  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 484",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__56096.invoke(execute.clj:501)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:493)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
    "driver.sql_jdbc$fn__94568.invokeStatic(sql_jdbc.clj:58)"
    "driver.sql_jdbc$fn__94568.invoke(sql_jdbc.clj:56)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___53529.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__49184.invoke(permissions.clj:109)"
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__89184.invoke(permissions.clj:124)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__90261.invoke(column_level_perms_check.clj:30)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__52474.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__55005$combined_post_process__55010$combined_post_process_STAR___55011.invoke(query_processor.clj:212)"
    "query_processor$fn__55005$combined_pre_process__55006$combined_pre_process_STAR___55007.invoke(query_processor.clj:209)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450$fn__53455.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:76)"
    "driver$do_with_driver.invoke(driver.clj:72)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49450.invoke(fetch_source_query.clj:314)"
    "query_processor.middleware.store$initialize_store$fn__49640$fn__49641.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:45)"
    "query_processor.store$do_with_store.invoke(store.clj:39)"
    "query_processor.middleware.store$initialize_store$fn__49640.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__53722.invoke(normalize_query.clj:22)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__60456.invoke(handle_audit_queries.clj:130)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__50728.invoke(constraints.clj:53)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__53661.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__54033.invoke(catch_exceptions.clj:167)"
    "query_processor.reducible$async_qp$qp_STAR___45482$thunk__45484.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___45482$fn__45486.invoke(reducible.clj:105)"],
   :error_type :invalid-query,
   :ex-data
   {:sql
    "-- Metabase:: userID: 1 queryType: native queryHash: cc9ff27d3803c08718822484202c2eb255b3602271b2a32ae668afe2e6f3e8c3\nSELECT \"public\".\"core_user\".\"id\" AS \"id\", \"public\".\"core_user\".\"email\" AS \"email\",\"public\".\"core_user\".\"date_joined\" AS \"date_joined\", \n       \"public\".\"core_user\".\"last_login\" AS \"last_login\", \"public\".\"core_user\".\"is_superuser\" AS \"is_superuser\", \"public\".\"core_user\".\"is_active\" AS \"is_active\"\nFROM \"public\".\"core_user\"\nWHERE \"public\".\"core_user\".\"is_superuser\" = ?\nLIMIT 1048575",
    :params ["false"],
    :type :invalid-query}}],
 :state "42883",
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :native,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false},
  :native
  {:query
   "SELECT \"public\".\"core_user\".\"id\" AS \"id\", \"public\".\"core_user\".\"email\" AS \"email\",\"public\".\"core_user\".\"date_joined\" AS \"date_joined\", \n       \"public\".\"core_user\".\"last_login\" AS \"last_login\", \"public\".\"core_user\".\"is_superuser\" AS \"is_superuser\", \"public\".\"core_user\".\"is_active\" AS \"is_active\"\nFROM \"public\".\"core_user\"\nWHERE {{is_superuser}}\nLIMIT 1048575",
   :template-tags
   {"is_superuser"
    {:id "62c79a5c-0bdc-fc7d-dde7-d6d0f3b620cd",
     :name "is_superuser",
     :display-name "Is superuser",
     :type :dimension,
     :dimension [:field 218 nil],
     :widget-type :string/=,
     :default nil}}},
  :database 2,
  :parameters
  [{:type :string/=,
    :slug "text",
    :id "d6892b8a",
    :value ["false"],
    :target [:dimension [:template-tag "is_superuser"]]}],
  :async? true,
  :cache-ttl nil},
 :status :failed,
 :class org.postgresql.util.PSQLException,
 :stacktrace
 ["org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)"
  "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)"
  "org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)"
  "org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)"
  "--> driver.sql_jdbc.execute$fn__56014.invokeStatic(execute.clj:362)"
  "driver.sql_jdbc.execute$fn__56014.invoke(execute.clj:360)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:375)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:371)"
  "driver.sql_jdbc.execute$execute_reducible_query$fn__56096.invoke(execute.clj:499)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:493)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
  "driver.sql_jdbc$fn__94568.invokeStatic(sql_jdbc.clj:58)"
  "driver.sql_jdbc$fn__94568.invoke(sql_jdbc.clj:56)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
  "query_processor.context.default$default_runf.invoke(default.clj:65)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___53529.invoke(cache.clj:220)"
  "query_processor.middleware.permissions$check_query_permissions$fn__49184.invoke(permissions.clj:109)"
  "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__89184.invoke(permissions.clj:124)"
  "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__90261.invoke(column_level_perms_check.clj:30)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__52474.invoke(mbql_to_native.clj:23)"
  "query_processor$fn__55005$combined_post_process__55010$combined_post_process_STAR___55011.invoke(query_processor.clj:212)"
  "query_processor$fn__55005$combined_pre_process__55006$combined_pre_process_STAR___55007.invoke(query_processor.clj:209)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450$fn__53455.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:76)"
  "driver$do_with_driver.invoke(driver.clj:72)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53450.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49450.invoke(fetch_source_query.clj:314)"
  "query_processor.middleware.store$initialize_store$fn__49640$fn__49641.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:45)"
  "query_processor.store$do_with_store.invoke(store.clj:39)"
  "query_processor.middleware.store$initialize_store$fn__49640.invoke(store.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__53722.invoke(normalize_query.clj:22)"
  "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__60456.invoke(handle_audit_queries.clj:130)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__50728.invoke(constraints.clj:53)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__53661.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__54033.invoke(catch_exceptions.clj:167)"
  "query_processor.reducible$async_qp$qp_STAR___45482$thunk__45484.invoke(reducible.clj:100)"
  "query_processor.reducible$async_qp$qp_STAR___45482$fn__45486.invoke(reducible.clj:105)"],
 :card_id 12,
 :context :embedded-dashboard,
 :error
 "ERROR: operator does not exist: boolean = character varying\n  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 484",
 :row_count 0,
 :running_time 0,
 :data {:rows [], :cols []}}
```

</details>

**To Reproduce**
1. Create and save a SQL question from a Postgres table with a field filter linked to a Boolean column

Now it will fail in 2 scenarios when trying to embed it. 

Embedding a Question

1. Go to Question -> Sharing -> Embed in your Application

image

2. You will notice that in this case you are given the true or false option but will fail when you select either option

Embedding a Dashboard

1. Go to New Dashboard -> Add your Question -> Setup a Drop Down Filter

2. Go to Sharing -> Embed in your Application

image

3. You will notice that in this case the drop down filter changes to a text based filter and if you input false/true (or any other string) it will fail

**Expected behavior**
Both Embedding options will give the true/false drop down filter and work when filtered

**Information about your Metabase Installation:**

Able to replicate on both 44.6 & 45.1

**Additional context**
Seems to be related to https://github.com/metabase/metabase/issues/22591 since it was only fixed for public links and the embedded option was skipped ... Looks like the same as https://github.com/metabase/metabase/issues/15498

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes #27643

The issue actually mentions 2 different bugs:
 - the card embedding preview was failing. This is due to `"true"` not being `true`, so the normalization change fixes this.
 - the dashboard embedding preview was failing immediately AND the filter wasn't presenting a list, just an input box. The first immediate failing was due to no `:embedding-parameters` existing in the Appdb, upon 'Publish' that issue went away, so I fixed the param-values implementation to address this case. The second issue was the same as with card embedding, so that's fixed as well.

Since we use query-params to pass paramter values, we have to normalize the parameter map values.

This PR is a WIP, as I'm trying to find a way to do this hollistically/properly.

First commit here is mostly as a marker for where to start working on this properly, as I think the json parsing won't catch all cases, nor should the normalization happen without some attempt to use a schema to properly validate, maybe even coerce things.

I also want to build a small set of tests to catch these differences across cards, dashboards, card embeds, and dashboard embeds.

Finally, this may close other issues, but I still have to confirm that.

### CODE REVIEW

File: src/metabase/api/embed/common.clj [hunk 1]
```diff
@@ -125,9 +125,22 @@
...
+                                          (parse-double v)
+                                          v))
+              v))]
+    (-> query-params
+        (update-keys keyword)
+        (update-vals (fn [v]
+                       (if (and (not (string? v))
+                                (seq v))
+                         (mapv maybe-read v)
+                         (maybe-read v)))))))
```
Comment (adam-james-v) [inline src/metabase/api/embed/common.clj:143]: I only really care about turning numbers and booleans into their expected types, anything else can be kept as strings.

query-params come from the URL, like this: `/api/embedding_endpoints/some_token?my_param=true&my_param2=asdf&my_param2=wasd`

So I want that to end up as:
```
{:my_param true
 :my_param2 ["asdf" "wasd"]}
 ```
 
 And this normalize takes care of that. There's a test added to show this behaviour as well.

File: src/metabase/api/dashboard.clj [hunk 2]
```diff
@@ -1225,10 +1225,10 @@
...
   [dashboard-id dashcard-id card-id :as {{:keys [parameters], :as body}          :body
                                          {dashboard-load-id "dashboard_load_id"} :query-params}]
-  {dashboard-id  ms/PositiveInt
-   dashcard-id   ms/PositiveInt
-   card-id       ms/PositiveInt
-   parameters    [:maybe [:sequential ParameterWithID]]}
+  {dashboard-id ms/PositiveInt
+   dashcard-id  ms/PositiveInt
+   card-id      ms/PositiveInt
+   parameters   [:maybe [:sequential ms/Parameter]]}
```
[the remark this answers is not in the document]
Comment (adam-james-v) [reply src/metabase/api/dashboard.clj]: Well, nevermind for now. Don't want this schema to block the PR, so I'll revert for now.

File: src/metabase/api/embed/common.clj [hunk 3]
```diff
@@ -125,9 +125,22 @@
   not automatically converted. Thus we must do it ourselves here to make sure things are done as we'd expect.
   Also, any param values that are blank strings should be parsed as nil, representing the absence of a value."
   [query-params]
-  (-> query-params
-      (update-keys keyword)
-      (update-vals (fn [v] (if (= v "") nil v)))))
+  (letfn [(maybe-read [v]
+            (if (string? v)
+              (cond
+                (#{"true" "false"} v) (parse-boolean v)
```
Comment (tsmacdonald) [inline src/metabase/api/embed/common.clj:131]: I don't have any brilliant suggestions, but it seems crazy that this is the first time we've had to deal with this? I'm surprised there's not a lib function somewhere that replicates this entire `cond`

Comment (tsmacdonald) [reply src/metabase/api/embed/common.clj:131]: @escherize are we missing a trick here with using `malli.schema.BooleanValue` and friends?

Comment (adam-james-v) [reply src/metabase/api/embed/common.clj:131]: Yea, I'd also gladly use an existing util fn or something else if there's something obvious!

File: test/metabase/api/preview_embed_test.clj [hunk 4]
```diff
@@ -577,3 +577,62 @@
               (is (= {:values          [["African"] ["American"] ["Asian"]]
                       :has_more_values false}
                      (mt/user-http-request :rasta :get 200 url))))))))))
+
+(deftest parameter-values-are-parsed-and-query-suceeds-test
+  (testing "embedding endpoint parameter values are parsed when sensible. (#27643)"
+    (embed-test/with-embedding-enabled-and-new-secret-key
+      (mt/dataset places-cam-likes
+        (mt/with-temp [:model/Card {card-id :id :as card} {:dataset_query
```
Comment (tsmacdonald) [inline test/metabase/api/preview_embed_test.clj:585]: `mt/native-query` would save you a couple tokens of typing, but NBD

**Review by tsmacdonald — APPROVED** [review]
Behavior looks reasonable to me (but I Am Not An Embedding Dev)

File: test/metabase/api/preview_embed_test.clj (hunk 4 above)
Comment (adam-james-v) [reply test/metabase/api/preview_embed_test.clj:585]: TIL. 
I'll leave this be, but remember that for future tests :)

File: src/metabase/api/embed/common.clj (hunk 3 above)
Comment (escherize) [reply src/metabase/api/embed/common.clj:131]: I'm not sure we should be converting every single "true" query parameter value to be `true`, shouldn't that be driven by the arg->schema map in defendpoint instead? It would seem like a surprise if I chose true or false for a collection/db/query/etc name, (that got sent through a qp) this could break when e.g. inserting `true` where we rightly expect "true".

If we do it this way we should add some docs that say you're not allowed to represent the strings true or false as query param values

Comment (escherize) [reply src/metabase/api/embed/common.clj:131]: > are we missing a trick here with using malli.schema.BooleanValue and friends?

Yeah, I think we should just coerce the query param value inside of defendpoint.

Comment (escherize) [reply src/metabase/api/embed/common.clj:131]: I think the mechanim to convert these doesn't matter. I was under the impression that there is a way to go from the name of the key to the expected type, and I was going to advocate for deriving the proper conversion function that way. @adam-james-v has informed me that there actually isn't a good way to know what type a value in these query params should actually be, so I think this guess is fine, and should fix the P1.

We should probably revisit this and figure out how to actually type the query param data.

**Review by escherize — APPROVED** [review]
