### PR TITLE
Fix `batch-upsert!` method for heterogeneous entries

### LINKED ISSUE #64862: /api/search on the sidebar of dashboards return cards inside other dashboards leading to errors
### Describe the bug

When adding new cards to dashboards, the search on the sidebar returns cards which exist inside other dashboards leading to error 400
https://github.com/metabase/metabase/blob/83fdbaa65c389e130cd8d777e64e21d0d851628a/src/metabase/dashboards/api.clj#L744

The problem seems to be that if we have 2 entities with the same name, the search endpoint will return these 2 and therefore the user might mistakenly select the one that's inside another dashboard, leading to a 400 error when trying to save this new dashboard

### To Reproduce

1) create 2 GUI questions with the same name (let's say "orders" which should be simply the orders table)
2) create 2 dashboards a and b
3) then move the first "orders" question inside dashboard a
4) now go to dashboard b and add a question: search for "orders" and you'll see 2 items. If you add the 2 questions and click save, you'll get a 400

### Expected behavior

We shouldn't show questions that exist on other dashboards on the search endpoint INSIDE the context of adding questions in dashboards

### Logs

NA

### Information about your Metabase installation

```JSON
I'm on 56, but this might be coming when we re-did search/cards inside dashboards (55?) and never considered this context on the search endpoint
```

### Severity

P2

### Additional context

NA

### PR DESCRIPTION
**Pull request by johnswanson**
closes #64862

The upsert keys were calculated by looking at the first entry we were
inserting and removing `:id`, `:model`, and `:model_id`.

But the entries are not necessarily homogeneous. In this case, the first
entry is a dashboard (has no `:dashboard_id`) and the second entry is a
card (yes `:dashboard_id`).

This meant we never actually updated the dashboard_id when updating a card.

I attempted to add a test for this:

```
(deftest updates-work-properly
  (mt/with-test-user :rasta
    (mt/with-temp [:model/Dashboard {dash-id :id} {}]
      (let [card-name (str (random-uuid))
            card-id-1 (:id (mt/user-http-request :rasta :post 200 "card/" {:name card-name
                                                                           :collection_id nil
                                                                           :database_id 1
                                                                           :display "table"
                                                                           :creator_id (mt/user->id :rasta)
                                                                           :visualization_settings {}
                                                                           :dataset_query {:type "native" :native {:query "select 123"}
                                                                                           :database 1}}))
            card-id-2 (:id (mt/user-http-request :rasta :post 200 "card/" {:name card-name
                                                                           :collection_id nil
                                                                           :database_id 1
                                                                           :display "table"
                                                                           :creator_id (mt/user->id :rasta)
                                                                           :visualization_settings {}
                                                                           :dataset_query {:type "native" :native {:query "select 123"}
                                                                                           :database 1}}))]
        (mt/user-http-request :rasta :put 200 (str "card/" card-id-1) {:dashboard_id dash-id})
        (is (= [card-name]
               (map :name (:data (mt/user-http-request :rasta :get 200 "search" :q card-name)))))))))
```

The good news is that this test passes after my change. The bad news is
that it also passes without my change. I think what's going on is that
the behavior is different with `*force-sync*` on/off: in async mode, we
get the full batch that contains the updates for `[dashboard, card]`.
In synchronous mode, we get separate batches for `[dashboard]` and then
`[card]`.

I think we might want to rework tests somehow - it would be quite nice
to be able to still run things asynchronously but drain the queue before
making assertions, so the behavior wouldn't be different between
tests/prod.

### CODE REVIEW

**Review by nvoxland — APPROVED** [review]

**Review by nvoxland — CHANGES_REQUESTED** [review]
on second thought, I don't think the change helps

File: src/metabase/search/appdb/index.clj [hunk 1]
```diff
@@ -247,17 +248,14 @@
 
 (defn- document->entry [entity]
   (-> entity
-      (select-keys
-       ;; remove attrs that get explicitly aliased below
-       (remove #{:id :created_at :updated_at :native_query}
-               (conj search.spec/attr-columns :model :display_data :legacy_input)))
+      (select-keys (conj search.spec/attr-columns :model :display_data :legacy_input))
```
Comment (johnswanson) [inline src/metabase/search/appdb/index.clj:251]: This bit is exactly the same functionally, I just found the existing impl to be unclear since we were removing some keys to rename them, and removing others entirely - feels simpler to explicitly rename what we want to rename and remove the one (`:native_query`) that we want to remove.

**Review by nvoxland — APPROVED** [review]
