### PR TITLE
Fix silent data loss when importing unparseable YAML files

### LINKED ISSUE #71257: Serialization entities with deeply nested representations break remote sync imports, causing data loss
### Describe the bug

When remote sync data is exported, it uses the same format as serialization.

Custom expressions inside MBQL questions are serialized with a parsed representation. So an expression like `replace(replace(replace(...)))` will result in a YAML tree at least 3 levels deep.

If this nesting extends to over 50 levels, this content and all its dependents will fail to be imported with remote sync. The only way to fix this is to manually correct or remove the bad data and all its dependents, or restore from a database backup.

Because Metabase admins might not have access to the remote sync repository to manually correct this, this behavior is no different from data loss from their perspective. No actual data loss has occurred, but the exported data is unusable.

### To Reproduce

1. Create a GUI question that uses the Sample Database, using a deeply nested custom field like this (the table or content are not important, only that expression are nested deep).

This example uses the `Orders` table:

Image

<details><summary>Custom expression</summary>

```
replace(
  replace(
    replace(
      replace(
        replace(
          replace(
            replace(
              replace(
                replace(
                  replace(
                    replace(
                      replace(
                        replace(
                          replace(
                            replace(
                              replace(
                                replace(
                                  replace(
                                    replace(
                                      replace(
                                        replace(
                                          replace(
                                            replace(
                                              replace(
                                                replace(
                                                  replace(
                                                    replace(
                                                      replace(
                                                        replace(
                                                          replace(
                                                            replace(
                                                              replace(
                                                                replace(
                                                                  replace(
                                                                    replace(
                                                                      replace(
                                                                        replace(
                                                                          replace(
                                                                            replace(
                                                                              replace(
                                                                                replace(
                                                                                  replace(
                                                                                    replace(
                                                                                      replace(
                                                                                        replace(
                                                                                          replace(
                                                                                            [User → Email],
                                                                                            "pluto.mars@example.com",
                                                                                            "Keystone"
                                                                                          ),
                                                                                          "cedar.brook@example.com",
                                                                                          "Keystone"
                                                                                        ),
                                                                                        "falcon.ridge@example.com",
                                                                                        "Keystone"
                                                                                      ),
                                                                                      "timber.vale@example.com",
                                                                                      "Keystone"
                                                                                    ),
                                                                                    "coral.dune@example.com",
                                                                                    "Keystone"
                                                                                  ),
                                                                                  "maple.frost@example.com",
                                                                                  "Keystone"
                                                                                ),
                                                                                "river.stone@example.com",
                                                                                "Keystone"
                                                                              ),
                                                                              "amber.field@example.com",
                                                                              "Enterprise"
                                                                            ),
                                                                            "silver.peak@example.com",
                                                                            "Enterprise"
                                                                          ),
                                                                          "hazel.creek@example.com",
                                                                          "Enterprise"
                                                                        ),
                                                                        "cobalt.wave@example.com",
                                                                        "Enterprise"
                                                                      ),
                                                                      "willow.glen@example.com",
                                                                      "Enterprise"
                                                                    ),
                                                                    "crimson.lake@example.com",
                                                                    "Partnership"
                                                                  ),
                                                                  "jade.summit@example.com",
                                                                  "Partnership"
                                                                ),
                                                                "bronze.gate@example.com",
                                                                "Partnership"
                                                              ),
                                                              "pearl.haven@example.com",
                                                              "Partnership"
                                                            ),
                                                            "slate.ridge@example.com",
                                                            "Partnership"
                                                          ),
                                                          "opal.marsh@example.com",
                                                          "Partnership"
                                                        ),
                                                        "flint.grove@example.com",
                                                        "Partnership"
                                                      ),
                                                      "ivory.bluff@example.com",
                                                      "Partnership"
                                                    ),
                                                    "copper.hill@example.com",
                                                    "Partnership"
                                                  ),
                                                  "sage.hollow@example.com",
                                                  "Partnership"
                                                ),
                                                "onyx.prairie@example.com",
                                                "Partnership"
                                              ),
                                              "pine.crest@example.com",
                                              "All Funds"
                                            ),
                                            "garnet.shore@example.com",
                                            "Enterprise"
                                          ),
                                          "indigo.plain@example.com",
                                          "Enterprise"
                                        ),
                                        "lunar.drift@example.com",
                                        "Partnership"
                                      ),
                                      "quartz.bend@example.com",
                                      "Partnership"
                                    ),
                                    "ember.trail@example.com",
                                    "Partnership"
                                  ),
                                  "dusk.meadow@example.com",
                                  "Partnership"
                                ),
                                "moss.cliff@example.com",
                                "Ireland"
                              ),
                              "velvet.spring@example.com",
                              "Partnership"
                            ),
                            "birch.cove@example.com",
                            "Partnership"
                          ),
                          "coral.reef@example.com",
                          "Partnership"
                        ),
                        "thistle.bay@example.com",
                        "Enterprise"
                      ),
                      "storm.knoll@example.com",
                      "Ireland"
                    ),
                    "aurora.dell@example.com",
                    "Ireland"
                  ),
                  "raven.moor@example.com",
                  "Partnership"
                ),
                "clover.arch@example.com",
                "Ireland"
              ),
              "fern.ledge@example.com",
              "Ireland"
            ),
            "wren.glade@example.com",
            "Ireland"
          ),
          "lark.heath@example.com",
          "Ireland"
        ),
        "basil.ford@example.com",
        "Partnership"
      ),
      "aspen.wells@example.com",
      "Partnership"
    ),
    "holly.vale@example.com",
    "Ireland"
  ),
  "ivy.brook@example.com",
  "Ireland"
)
```

</details> 

2. Export this data from remote sync
3. Delete the data currently on the instance, and pull again (or switch to a different branch, and then back again)
4. The remote sync import partially succeeds. This card and any content that depends on it will NOT be imported. The only way to revert this is to manually delete/fix the card from the remote repo, and sync again

### Expected behavior

Remote sync imports must be atomic - either everything is imported, or nothing is changed

Cards that cannot be imported should not be exportable. Indicate an error when this happens

### Logs

```
2026-03-20 14:19:43,202 INFO source.git :: Fetching repository {:repo Git[Repository[/tmp/metabase-git/934bd47241d0b05fc046970e5b517bc90881b548]]} 
2026-03-20 14:19:43,205 DEBUG middleware.log :: POST /api/ee/remote-sync/import 200 16ms (8 DB calls) App DB connections: 1/14 Jetty threads: 5/50 (6 idle, 0 queued) (86 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1} 
2026-03-20 14:19:43,225 DEBUG middleware.log :: GET /api/ee/remote-sync/current-task 200 2ms (1 DB calls) App DB connections: 0/14 Jetty threads: 5/50 (6 idle, 0 queued) (86 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1} 
2026-03-20 14:19:43,964 INFO source.git :: Successfully fetched repository 
2026-03-20 14:19:43,966 INFO remote-sync.impl :: Reloading remote entities from the remote source 
2026-03-20 14:19:44,016 ERROR source.ingestable :: Error reading file collections/HyB3nRtqb7pBPhFG26evI_examples/cards/py3fNHWRpjLTP_pDZlpsb_cursed_replace.yaml 
org.yaml.snakeyaml.error.YAMLException: Nesting Depth exceeded max 50
[...]
```

(import continues normally after this, but this card and its dependents are missing)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:148.0) Gecko/20100101 Firefox/148.0",
    "vendor": ""
  },
  "metabase-info": {
    "valid-thru": "2026-12-31T12:00:00Z",
    "current-user-count": 1,
    "application-database": "postgres",
    "settings": {
      "report-timezone": null
    },
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.5 (Debian 17.5-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.8"
      }
    },
    "databases": [
      "postgres",
      "h2"
    ],
    "max-users": 50,
    "plan-alias": "enterprise-airgap",
    "hosting-env": "unknown",
    "run-mode": "prod",
    "version": {
      "date": "2026-03-02",
      "tag": "v1.59.1",
      "hash": "d609bf8"
    },
    "airgap-token": "enabled"
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.10+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.10+7-LTS",
    "os.name": "Linux",
    "os.version": "6.17.8-orbstack-00308-g8f9c941121b1",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  }
}
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
When a YAML file fails to parse during serdes ingestion (e.g. corrupted file, invalid syntax), the error is silently caught and logged — the file is simply skipped. This means remote sync imports can silently lose entities with no indication that anything went wrong. The import reports success even though data was dropped.

This PR extends the `Ingestable` protocol with an `ingest-errors` method that collects parse failures during cache population instead of discarding them. `load-metabase!` checks these errors after ingestion:

- **Default behavior** (`continue-on-error` false, used by remote sync): throws immediately, so the import fails visibly rather than silently losing data
- **Manual imports** (`continue-on-error` true): errors are collected alongside load-phase errors so callers get a unified error report

Dotfiles (editor temp files like `.hidden.yaml`) are still silently skipped per #41567 — only non-hidden YAML files that fail to parse are treated as errors.

Note that this fixes the silent skipping of unparseable YAML files. It does not fix the issue with nested entities (50+ levels) as the limited was added to protect from a DoS security issue. We could increase that limit, but imo50 levels of nesting is unlikely to be hit in the wild.

Screenshot 2026-03-26 at 21 31 56

cc @metabase/tech-writers this _might_ come up as unexpected for some customers when serdes/remote sync started to fail if they have bad yaml files, so we could you please put a disclaimer in the release note so people know about this and find ways to fix their stuff?

Fixes #71257

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/remote_sync/source.clj [hunk 1]
```diff
@@ -43,7 +43,7 @@
   [snapshot {:keys [path-filters root-dependencies]}]
   (cond->> (ingestable/->IngestableSnapshot (cond-> snapshot
                                               (seq path-filters) (->WrappingSnapshot path-filters))
-                                            (atom nil))
+                                            (atom nil) (atom []))
```
Comment (sansolovyov) [inline enterprise/backend/src/metabase_enterprise/remote_sync/source.clj:46]: low-key want a newline here :)

**Review by sansolovyov — APPROVED** [review]
That's good!

File: enterprise/backend/src/metabase_enterprise/remote_sync/source.clj (hunk 1 above)
Comment (qnkhuat) [reply enterprise/backend/src/metabase_enterprise/remote_sync/source.clj:46]: yea.. but a bit hard to get CI green lately so... excuse me 😁
