### PR TITLE
Fix custom columns lose their definition in embeddings

### LINKED ISSUE #25473: Text filter over a custom column in simple embedding expects a number
**Describe the bug**
When there's a text filter on a custom column in signed embedding, it will request for a number instead of a string

**Logs**
NA, seems like a FE error

**To Reproduce**
1) enable embedding
2) new->question->people>custom colum-> concat([Email], [Name]), save it with any name
3) add question to dashboard
4) add text filters (text contains, text does not contain, text starts with, text ends with)
5) click to embed it, enable the filters as editable
6) click on the filters to see all requesting a number

**Expected behavior**
Text filter should expect strings

**Screenshots**
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres 14
- Metabase version: 1.44.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P2

**Additional context**
Workaround: use a view in the DB to build the custom column

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes: #25473
[Notion summary](https://www.notion.so/metabase/Question-about-custom-field-definition-in-parameters-on-public-dashboards-641c1603918548a2a1bc18fd430fd901)

## PR Summary
In `<FieldValuesWidget />`, there could be the `parameter` prop passed to it which indicates the widget is connected to a dashboard filter.

In such case, if we need to perform any logic to determine the widget type e.g. showing the placeholder as `Enter a number` we should use `parameter`'s type instead of field types.

## Todos
- [x] Add tests
- [x] Troubleshoot `ExpressionDimension.parseMBQL`
- [x] Draft questions about new public table metadata endpoint

<details>
<summary><h2>Old details</h2></summary>

## Problems
When populating parameters we use this selector:
https://github.com/metabase/metabase/blob/00ce5700e31a98124b034e0586456e9ce261505c/frontend/src/metabase/dashboard/selectors.js#L171-L179

Which down the line, uses the `Field` selector:
https://github.com/metabase/metabase/blob/00ce5700e31a98124b034e0586456e9ce261505c/frontend/src/metabase/selectors/metadata.js#L32

The problem is that we don't populate `state.entities.fields` in embedding.

In the app we call `/api/table/:tableId/query_metadata` here:
https://github.com/metabase/metabase/blob/00ce5700e31a98124b034e0586456e9ce261505c/frontend/src/metabase/entities/tables.js#L95-L98
which will populate `state.entities.fields` as expected, but in embedding we only call either `/api/public/dashboard/:uuid/dashcard/:dashcardId/card/:cardId` or `/api/embed/dashboard/:token/dashcard/:dashcardId/card/:cardId`:
https://github.com/metabase/metabase/blob/00ce5700e31a98124b034e0586456e9ce261505c/frontend/src/metabase/dashboard/actions/data-fetching.js#L378
which only populate `dashboard.dashcards.[cardId]`

I think of a couple solutions
1. Modify the selector so that it pulls fields from `dashboard.dashcards.[cardId]`
2. Kind of what this PR does, is to implement the reducer to populate `state.entities.fields`, but I found some problems which are laid out in the comments.
</details>

### CODE REVIEW

File: frontend/src/metabase/entities/fields.js [hunk 1]
```diff
@@ -191,6 +191,14 @@ const Fields = createEntity({
         updateIn(state, [fieldId, "remappings"], (existing = []) =>
           Array.from(new Map(existing.concat(remappings))),
         ),
+      // Can't import metabase/dashboard/FETCH_CARD_DATA because of circular dependency
+      ["metabase/dashboard/FETCH_CARD_DATA"]: (state, { payload }) => {
```
Comment (WiNloSt) [inline frontend/src/metabase/entities/fields.js:195]: Use hard-coded action since `metabase/dashboard/FETCH_CARD_DATA` can't be imported due to cyclic dependencies.

File: frontend/src/metabase/entities/fields.js [hunk 2]
```diff
@@ -191,6 +191,14 @@ const Fields = createEntity({
...
+        const fields = getIn(payload, ["result", "data", "cols"]);
+        return {
+          ...Fields.normalizeList(fields).entities[Fields.name],
```
Comment (WiNloSt) [inline frontend/src/metabase/entities/fields.js:198]: I really hate to have to normalize the data manually. I bet this isn't idiomatic, but I don't know how to get the data in the correct shape without normalizing it.

Under the hood, calling `normalizeList` will populate `uniqueId` which will be used by some of our selectors.
https://github.com/metabase/metabase/blob/00ce5700e31a98124b034e0586456e9ce261505c/frontend/src/metabase/selectors/metadata.js#L128

without that, `fields` won't be populated using the `getMetadata` selector.

**Review by ranquild — COMMENTED** [review]
@WiNloSt I'd ask for a review from @kulyk but based on my limited understanding `data.cols` is not the same as fields obtained from metadata endpoints. What would happen if we allow this request to be done for embedded dashboards, too https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase/dashboard/actions/data-fetching.js#L177? If that won't work, I believe we should start a conversation with the backend team whether they can make the existing endpoint work or add another one that can be used for embedding.

File: frontend/src/metabase/entities/fields.js (hunk 2 above)
Comment (kulyk) [reply frontend/src/metabase/entities/fields.js:198]: Let me take another look at it though

File: frontend/src/metabase-lib/parameters/utils/parameter-type.ts [hunk 3]
```diff
@@ -22,6 +22,11 @@ function splitType(parameterOrType: Parameter | string) {
   return parameterType.split("/");
 }
 
+export function isIdParameter(parameter: Parameter | string) {
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/parameters/utils/parameter-type.ts:25]: Keep the logic to check parameter type in here. I think the signature could be refactored to `isParameterType(parameter: Parameter, type: ParameterType)`, so we don't have to import separate function to determine parameter types.

File: frontend/src/metabase/components/FieldValuesWidget.jsx [hunk 4]
```diff
@@ -291,6 +296,7 @@ class FieldValuesWidgetInner extends Component {
 
     const tokenFieldPlaceholder = getTokenFieldPlaceholder({
       fields,
+      parameter,
```
Comment (WiNloSt) [inline frontend/src/metabase/components/FieldValuesWidget.jsx:299]: This is the first place where we didn't take parameter into account, basically when there's a dashboard filter (parameter) set, we should use that filter's type instead of field types.

File: frontend/src/metabase/components/FieldValuesWidget.jsx [hunk 5]
```diff
@@ -307,6 +313,12 @@ class FieldValuesWidgetInner extends Component {
     const isLoading = loadingState === "LOADING";
     const hasListValues = hasList({ fields, disableSearch, options });
 
+    const parseFreeformValue = value => {
+      return isNumeric(fields[0], parameter)
```
Comment (WiNloSt) [inline frontend/src/metabase/components/FieldValuesWidget.jsx:317]: This is the second place, where we didn't take parameter type into account.

File: frontend/src/metabase/components/FieldValuesWidget.jsx [hunk 6]
```diff
@@ -446,17 +454,30 @@ function shouldList(fields, disableSearch) {
   );
 }
 
-function getNonSearchableTokenFieldPlaceholder(firstField) {
-  if (firstField.isID()) {
-    return t`Enter an ID`;
-  } else if (firstField.isString()) {
+function getNonSearchableTokenFieldPlaceholder(firstField, parameter) {
+  if (parameter) {
```
Comment (WiNloSt) [inline frontend/src/metabase/components/FieldValuesWidget.jsx:458]: I despise nested if, but I just want to keep things simple for now to verify if the approach is valid first.

File: frontend/src/metabase/components/FieldValuesWidget.jsx [hunk 7]
```diff
@@ -671,3 +693,17 @@ export function getValuesMode(
 
   return "none";
 }
+
+/**
+ *
+ * @param {import("metabase-types/types/Field").Field} field
+ * @param {import("metabase-types/types/Parameter").Parameter} parameter
```
Comment (ranquild) [inline frontend/src/metabase/components/FieldValuesWidget.jsx:700]: Types are wrong. `field` is coming from `metabase-lib` (it's a class), and parameter is `UiParameter` from `metabase-lib/parameters/types`. But I'd remove this comment because it will become outdated very shortly.

**Review by ranquild — CHANGES_REQUESTED** [review]
@WiNloSt I believe that the PR does parameter checks correctly. But it's hacky because we overload `FieldValuesWidget` with a notion of `parameter` instead of creating a base component that would work both for `FieldValuesWidget` and for parameters. But I'd approve the PR if there would be tests for the behavior.

**Comment by WiNloSt** [comment]
@ranquild OK if this approach sounds good I can refactor the PR tomorrow. BTW the test has just been added. I verify that without the fix the test would fail, so it's capturing the bug correctly.

**Review by ranquild — COMMENTED** [review]
@WiNloSt I'm ok with refactoring this in a separate PR. If the fix works this is good already.

File: frontend/test/metabase/scenarios/sharing/public.cy.spec.js [hunk 8]
```diff
@@ -201,4 +201,106 @@ describe("scenarios > public", () => {
       }),
     );
   });
+
+  describe("public dashboard with parameters linked to a custom field (metabase#25473)", () => {
```
Comment (WiNloSt) [inline frontend/test/metabase/scenarios/sharing/public.cy.spec.js:205]: Mostly copy the setup from https://github.com/metabase/metabase/blob/master/frontend/test/metabase/scenarios/embedding/embedding-dashboard.cy.spec.js

File: frontend/test/metabase/scenarios/sharing/public.cy.spec.js [hunk 9]
```diff
@@ -201,4 +201,106 @@ describe("scenarios > public", () => {
...
+      });
+
+      cy.get("@dashboardId").then(dashboardId => {
+        visitDashboard(dashboardId);
+      });
+
+      // Enable public sharing
+      cy.icon("share").click();
+
+      cy.contains("Enable sharing")
```
Comment (ranquild) [inline frontend/test/metabase/scenarios/sharing/public.cy.spec.js:257]: nit: I think we usually prefer `cy.findByText`

File: frontend/test/metabase/scenarios/sharing/public.cy.spec.js [hunk 10]
```diff
@@ -201,4 +201,106 @@ describe("scenarios > public", () => {
...
+        .find("input")
+        .then($input => {
+          const dashboardPublicLink = $input[0].value;
+          cy.visit(dashboardPublicLink);
+        });
+
+      // Public dashboard
+      cy.findByText(textContainsFilter.name).click();
+
+      cy.findByPlaceholderText("Enter some text").should("be.visible");
```
Comment (ranquild) [inline frontend/test/metabase/scenarios/sharing/public.cy.spec.js:273]: We should also check that it's possible to enter a value and it doesn't break

**Review by ranquild — CHANGES_REQUESTED** [review]
Please add another case to the test 👍

File: frontend/test/metabase/scenarios/sharing/public.cy.spec.js (hunk 10 above)
Comment (WiNloSt) [reply frontend/test/metabase/scenarios/sharing/public.cy.spec.js:273]: sounds good  👍

File: frontend/test/metabase/scenarios/sharing/public.cy.spec.js [hunk 11]
```diff
@@ -201,4 +201,130 @@ describe("scenarios > public", () => {
...
+
+      cy.contains("Public link")
+        .parent()
+        .find("input")
+        .then($input => {
+          const dashboardPublicLink = $input[0].value;
+          cy.visit(dashboardPublicLink);
+        });
+
+      // Assert public dashboard
```
Comment (WiNloSt) [inline frontend/test/metabase/scenarios/sharing/public.cy.spec.js:271]: Given the custom field as `concat([Email], [Name])`
There are 3 assertions here.
1. search by email
2. search by name
3. search by email+name

Each with different person, so we know it's working.

File: frontend/src/metabase/components/FieldValuesWidget.jsx (hunk 7 above)
Comment (WiNloSt) [reply frontend/src/metabase/components/FieldValuesWidget.jsx:700]: I was using the same type from `isNumberParameter`'s function signature

https://github.com/metabase/metabase/blob/2bd929c6fc1e7a0d0077c7cee903f9dd2ad817da/frontend/src/metabase-lib/parameters/utils/parameter-type.ts#L35

which seems to receive the same `parameter` we have here.
https://github.com/metabase/metabase/blob/2bd929c6fc1e7a0d0077c7cee903f9dd2ad817da/frontend/src/metabase/parameters/components/ParameterValueWidget.jsx#L234

We seem to have types in a lot of places, so that's why I was confused.

But agree on removing this comment since it'll be refactored soon.

**Review by ranquild — APPROVED** [review]

**Comment by ranquild** [comment]
@WiNloSt should we backport the PR as well?

**Comment by WiNloSt** [comment]
@ranquild Good point. I think we should. This only fixes the bug. So no default behavior change and whatnot.

File: frontend/test/metabase/scenarios/filters/view.cy.spec.js [hunk 12]
```diff
@@ -37,15 +37,15 @@ describe("scenarios > question > view", () => {
               "display-name": "CATEGORY",
               type: "dimension",
               dimension: ["field", PRODUCTS.CATEGORY, null],
-              "widget-type": "id",
+              "widget-type": "string/=",
```
Comment (WiNloSt) [inline frontend/test/metabase/scenarios/filters/view.cy.spec.js:40]: @nemanjaglumac Can you help take a look that this change is fine? I need to correct the widget type to match the actual field type so `<FieldValuesWidget />` show the correct widget type.

The [recent E2E test failure](https://www.deploysentinel.com/ci/runs/63a32c02a622c2ef12225f15) is because we mock the widget type wrong.

Since both **product.category** and **product.vendor** are both string, when we try to map the parameter using the UI, the type will be defaulted to `string/=`
image

And with this new change that takes parameter type into account, we need to make sure we mock the correct parameter type.

Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/filters/view.cy.spec.js:40]: I don't remember exactly what was going on in this test, but your change makes sense.

Thank you
