### PR TITLE
Adjust parameter_mappings for a text dashcard when its variable is removed

### LINKED ISSUE #63717: Deleting a text card variable does not delete the parameter connection.
### Describe the bug

After deleting a variable from a text card, the parameter that was connected to the variable remains on the tab, even though it has no (apparent) connections to cards on the tab.

Things work correctly if you first disconnect the parameter from the text card and then delete the variable, but not if you delete the variable first. Once you do that, the editing interface acts as though there is no connection. Outside the editor, though, the interface acts as though the connection still exists.

### To Reproduce

1. Create a new dashboard.
2. Add a text parameter "PARAM" with an input box.
3. Add a text card with the text: "Value = {{VAR}}"
4. Connect the PARAM parameter to VAR in the text box.
5. Save the dashboard.
6. Confirm that the PARAM parameter is present and that entered values display in the text card.
7. Edit the dashboard.
8. Delete the {{VAR}} variable from the text card.
9. Save the dashboard.

- Expected behavior: The PARAM parameter is not present.
- Observed behavior:
    - The PARAM parameter is still present.
    - Entered values do not display in the text card. (Confirms the connection no longer works.)
    - Editing the dashboard and clicking in the PARAM parameter shows "You can connect widgets to {{variables}} in text cards" in the text card. (Confirms that some logic in the code has determined that the connection does not exist.)
    - Re-adding the {{VAR}} variable to the text card and clicking in the PARAM parameter now shows the connection dropdown in the text card and it is populated with "VAR". (Indicates that the mapping still existed somewhere.)

### Expected behavior

When the user deletes a variable from a text card, the application should not act as if a connection to that variable still exists. In my example, when that connection was the only one from the parameter to a card on the tab, the parameter should no longer show on the tab (when not editing the report).

### Logs

N/A

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "h2",
      "starburst"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted-yearly",
    "version": {
      "date": "2025-05-27",
      "tag": "v1.54.10.1",
      "hash": "1ab9486"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "6.12.37-61.105.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

More than a little annoying if you don't know about the bug. The workaround is easy but not obvious.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
closes #63717
Adjust parameter_mappings for a text dashcard when its variable is removed

How to validate:
- check green CI
- check code
- follow reproduction steps below and be sure that now the issue is fixed

How to reproduce:
1. Create a new dashboard.
2. Add a text parameter "PARAM" with an input box.
3. Add a text card with the text: "Value = {{VAR}}"
4. Connect the PARAM parameter to VAR in the text box.
5. Save the dashboard.
6. Confirm that the PARAM parameter is present and that entered values display in the text card.
7. Edit the dashboard.
8. Delete the {{VAR}} variable from the text card.
9. Save the dashboard.

- Expected behavior: The PARAM parameter is not present.
- Observed behavior:
    - The PARAM parameter is still present.
    - Entered values do not display in the text card. (Confirms the connection no longer works.)
    - Editing the dashboard and clicking in the PARAM parameter shows "You can connect widgets to {{variables}} in text cards" in the text card. (Confirms that some logic in the code has determined that the connection does not exist.)
    - Re-adding the {{VAR}} variable to the text card and clicking in the PARAM parameter now shows the connection dropdown in the text card and it is populated with "VAR". (Indicates that the mapping still existed somewhere.)

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/Text/Text.jsx [hunk 1]
```diff
@@ -75,6 +77,10 @@ export function Text({
     [dashcard, dashboard, parameterValues, translatedText],
   );
 
+  const updateParameterMappings = useCallback(() => {
+    dispatch(updateParameterMappingsForDashcardText(dashcard.id));
+  }, [dashcard.id, dispatch]);
+
```
Comment (sanex3339) [inline frontend/src/metabase/visualizations/visualizations/Text/Text.jsx:87]: Are we fine to dispatch it directly from the Text component? 
I see that it's related to a dashcard and it already gets via `useSelector` the `parameterValues` from the state, so i assume that we can also update `parameter_mappings` from it

**Comment by npfitz** [comment]
I'm still seeing the issue present if I create a text card with a var defined, and connect a param to it. Editing the text of the card so it no longer has a variable does not hide the param from the tab

**Review by npfitz — APPROVED** [review]
