### PR TITLE
Show read-only mode banner to all users

### LINKED ISSUE #50593: `read-only-mode` setting is visible only to admins
As the title says, the `read-only-mode` setting is shown only to admins. I confirmed with the Product team that this is wrong. This setting should be visible to everyone.

@iethree raised this concern in [this comment](https://github.com/metabase/metabase/pull/49273#discussion_r1859435109).

I've erroneously assumed that the backend is correct, so I've updated the FE logic to match the backend's. Once the backend fixes this and exposes this setting to all users, the FE needs to be updated as well.

### PR DESCRIPTION
**Pull request by bgrabow**
closes #50593

### Description

Change the read-only mode setting to be visible to all logged in users, but still only writable by admins.

Previously there was no `defsetting` `:visibility` level that allowed this. This PR adds an `:admin-write-authed-read` visibility setting that provides this specific combination of permissions.

### How to verify

1. `bun run dev`
2. Open `localhost:3000`
3. Login as an admin user
4. Grab your session token from your browser's dev tools (Application tab > Cookies > metabase.SESSION)
5. Enable read-only mode
```
curl -X PUT http://localhost:3000/api/setting/read-only-mode \
    -H "Content-Type: application/json" \
    -H "X-Metabase-Session: <your-session-token>" \
    -d '{"value": true}'
```
6. Refresh the page to confirm you see the banner as an admin.
7. Log out as admin and log in as a regular user and confirm you see the banner
Optional:
8. Log in again as an admin user and turn off read-only mode with:
```
curl -X PUT http://localhost:3000/api/setting/read-only-mode \
    -H "Content-Type: application/json" \
    -H "X-Metabase-Session: <your-session-token>" \
    -d '{"value": false}'
```

### Demo

Screenshot 2026-03-11 at 2 36 44 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by bgrabow** [comment]
Note:

```
  ###### `:visibility`

  Controls where this setting is visible, and who can update it. Possible values are:

    Visibility       | Who Can See It?              | Who Can Update It?
    ---------------- | ---------------------------- | --------------------
    :public          | The entire world             | Admins and Settings Managers
    :authenticated   | Logged-in Users              | Admins and Settings Managers
    :settings-manager| Admins and Settings Managers | Admins and Settings Managers
    :admin           | Admins                       | Admins
    :internal        | Nobody                       | No one (usually for env-var-only settings)
```

This change will not only make the setting visible, but also start allowing Settings Managers to update the read-only mode setting. Is that what we want?

If not, do we need to carve out a new visibility option for "seen by everyone but updatable only by admins"?

**Comment by bgrabow** [comment]
https://github.com/metabase/metabase/pull/70529#issuecomment-4014068777
> Note:
> 
> ```
>   ###### ``:visibility``
> 
>   Controls where this setting is visible, and who can update it. Possible values are:
> 
>     Visibility       | Who Can See It?              | Who Can Update It?
>     ---------------- | ---------------------------- | --------------------
>     :public          | The entire world             | Admins and Settings Managers
>     :authenticated   | Logged-in Users              | Admins and Settings Managers
>     :settings-manager| Admins and Settings Managers | Admins and Settings Managers
>     :admin           | Admins                       | Admins
>     :internal        | Nobody                       | No one (usually for env-var-only settings)
> ```
> 
> This change will not only make the setting visible, but also start allowing Settings Managers to update the read-only mode setting. Is that what we want?
> 
> If not, do we need to carve out a new visibility option for "seen by everyone but updatable only by admins"?

@iethree do you have an opinion on this? (re: https://github.com/metabase/metabase/pull/49273#discussion_r1859435109)

File: test/metabase/session/api_test.clj [hunk 1]
```diff
@@ -519,23 +519,23 @@
 (deftest properties-test
   (testing "GET /session/properties"
     (testing "Unauthenticated"
-      (is (= (set (keys (setting/user-readable-values-map #{:public})))
+      (is (= (set (keys (setting/user-readable-values-map #{:public :admin-write-public-read})))
```
Comment (bgrabow) [inline test/metabase/session/api_test.clj]: Is the fact that a public user can see that they have access to `:admin-write-public-read` leaking some information about what admins can do or which settings can be changed by whom? Should this visibility setting be renamed to not subtly leak write permission information?

If we were to decouple the write permissions from the read permissions then this `GET /session/properties` could return just the read aspects of the permissions and not leak any information about the write aspects.

**Review by johnswanson — APPROVED** [review]
Looks good to me!

File: src/metabase/cloud_migration/settings.clj [hunk 2]
```diff
@@ -77,7 +77,7 @@
         "Will take up to 1m to propagate to other Metabase instances in a cluster."
         "Audit tables are excluded from read-only-mode mode."))
   :type       :boolean
-  :visibility :admin
+  :visibility :admin-write-authed-read
```
Comment (escherize) [inline src/metabase/cloud_migration/settings.clj:80]: Love this naming convention! Easier to know who can r/w with this visibility. 🙏

**Review by escherize — APPROVED** [review]
lgtm
