### PR TITLE
Use Indicator for update notifications

### LINKED ISSUE #30114: Admin panel update counter always displays 1, regardless of how many updates you're behind
**Describe the bug**
Super minor, but the update counter always displays "1" instead of the number of updates you're behind.
Unless it's supposed to display major versions, which would seem bizarre.

**Logs**

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Let Metabase lapse an update or two
2. Go into the admin panel
3. Look to the left nav to see the "1" in the updates section.

**Expected behavior**
I guess I'd expect it to count minor versions, or absolute updates, or present a different icon that draws attention but doesn't indicate anything numeric.  The "1" seems meaningless.  Is it the result of a calculation?  If so, what? and why?

**Screenshots/videos**
I won't waste the disk and bandwidth, lol.

**Information about your Metabase Installation:**

**Severity**
Zero severity.  More of an OCD trigger than anything else. :)

**Additional context**

### LINKED ISSUE #59987: Updates badge rotates on click
### Describe the bug

https://github.com/user-attachments/assets/24034003-6eec-4404-9910-75f678a889cd

### To Reproduce

1. Go to Admin
2. Have updates pending
3. Keep clicking on the "Updates" tab

### Information about your Metabase installation

master, 7c676d4f305bfc9bd3fa4d5355a8ec103e2b788f

### Severity

P3

### PR DESCRIPTION
**Pull request by fraserdrops**
closes #30114

closes #59987

The old badge indicator was confusing because the number `1` looked like it had meaning, such as number of updates behind, but in fact it meant nothing. [ Slack thread](https://metaboat.slack.com/archives/C02H619CJ8K/p1750282804596389)

image

### CODE REVIEW

File: frontend/src/metabase/admin/settings/components/SettingsNav/UpdatesNavItem.tsx [hunk 1]
```diff
@@ -21,23 +21,21 @@ export function UpdatesNavItem() {
...
-                backgroundColor: "var(--mb-color-error)",
-              },
-            }}
-          >
-            1
-          </Badge>
-        ) : null
+      label={
+        <Indicator
+          data-testid="testing"
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/SettingsNav/UpdatesNavItem.tsx:26]: Since we're not using this testId, I think we can remove it, or at least give it a better name than "testing"

File: frontend/src/metabase/admin/settings/components/SettingsNav/UpdatesNavItem.unit.spec.tsx [hunk 2]
```diff
@@ -69,11 +69,22 @@ const setup = async (props: {
 describe("UpdatesNavItem", () => {
   it("should not show badge if there are no updates available", async () => {
     await setup({ versionTag: "v1.53.8", updateChannel: "latest" });
-    expect(screen.queryByTestId("updates-nav-badge")).not.toBeInTheDocument();
+
+    await waitFor(() => {
+      const indicatorDot = document.querySelector(
+        '[class*="Indicator-indicator"]',
+      );
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/SettingsNav/UpdatesNavItem.unit.spec.tsx:76]: I don't love this, but it looks like there's no data-attribute associated with this dot that we could assert on otherwise 😞

**Review by iethree — APPROVED** [review]

File: frontend/src/metabase/admin/settings/components/SettingsNav/UpdatesNavItem.unit.spec.tsx (hunk 2 above)
Comment (fraserdrops) [reply frontend/src/metabase/admin/settings/components/SettingsNav/UpdatesNavItem.unit.spec.tsx:76]: I don't either. I meant to say that I'm totally open to removing these tests entirely, if they're not adding much value:
1. As you noticed, there's no good way to find the indicator through the `screen`. The way Mantine does the indicator, the wrapper/root is always present, even when the indicator is being hidden
  ```
  <Indicator disabled={isHidden}>
    Updates
  </Indicator>
  ```

So I can't even attach a test-id to the <Indicator> component because it's always present

2. This indicator being present/not present is not mission critical by any stretch

3. The logic in the component is very simple. I'm essentially testing a condition is true when it's true, and false when it's false

Comment (iethree) [reply frontend/src/metabase/admin/settings/components/SettingsNav/UpdatesNavItem.unit.spec.tsx:76]: I would leave it. I think you've taken the least bad route here.
