### PR TITLE
re-initialize qb when navigating back

### LINKED ISSUE #32387: View-only native SQL question should hide SQL when browser back button used
### Describe the bug

- Native SQL questions hide the SQL being run and instead say `This question is written in SQL.`
- If a user visits a native SQL question saved in a collection where they have view permissions and then navigates to a new Native SQL question and uses their browser's back button, the SQL is shown instead of the `This question is written in SQL` message.

### To Reproduce

1. Create a Native SQL question like `SELECT * FROM PRODUCTS` and save in a collection.
2. Create a user who has view-only permissions to the collection where the Native SQL question was saved
3. Login as the user with view-only permissions and view the Native SQL question (should see `This question is written in SQL.`)
4. Click New + > Native SQL question
5. Click the browser's back button
6. See that the SQL is now shown instead of the `This question is written in SQL.` message.

### Expected behavior

Should still say `This question is written in SQL.` instead of showing the SQL and SQL editor

### Logs

image

image

### Information about your Metabase installation

```JSON
- Metabase v1.46.6 and `master` as of `54109eeb`
```

### Severity

P1 regression in `master`: allows view-only user to edit query and re-run
P2 in `v1.46.6`: does not allow view-only user to edit query

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/32387

### Description
The Query builder will display the native query when it shouldn't if you navigate to a question you can only view, to a blank native question, and then back again. This is because the QB does not re-initialize on the way back, so the UI controls are not recalculated. This PR causes the QB to re-initialize if the location or params changes 

### How to verify

1. Create a user that has read SQL access to one DB, and full sql access on another.
2. Create a question a native question that points to the first DB and save it
3. Log in as the restricted user, and navigate to the created question. You should not be able to see the SQL behind the question
4. click New -> SQL query, then click the back button on the browser. The SQL should still be hidden.

### Demo
chrome_q1RxMxADgF

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/query_builder/containers/QueryBuilder.jsx [hunk 1]
```diff
@@ -294,6 +294,10 @@ function QueryBuilder(props) {
     initializeQB(location, params);
   });
 
+  useEffect(() => {
+    initializeQB(location, params);
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/containers/QueryBuilder.jsx:298]: This is too eager and breaks lots of things.

1. Open an existing native question (e.g. `select 1;`)
2. Open editor
3. Change query (e.g. `select 1 + 2;`
4. Run question

Expected result: 3
Actual result: "Here's where your results will appear"


https://github.com/metabase/metabase/assets/6830683/29b9bfe7-29dc-4151-a68d-710e52dbdd88

**Review by kamilmielnik — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/query_builder/containers/QueryBuilder.jsx (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/query_builder/containers/QueryBuilder.jsx]: Updated the approach to reset UI controls if we hit the back button, and the card has changed. Far less eager haha

File: e2e/test/scenarios/native/native.cy.spec.js [hunk 2]
```diff
@@ -314,6 +319,65 @@ describe("scenarios > question > native", () => {
...
+        },
+        {
+          wrapId: true,
+        },
+      );
+
+      cy.signIn("nosql");
+    });
+
+    it("should not display the query when you do not have native access to the data source", () => {
```
Comment (kamilmielnik) [inline e2e/test/scenarios/native/native.cy.spec.js:357]:
```suggestion
    it("should not display the query when you do not have native access to the data source (metabase#32387)", () => {
```

File: e2e/test/scenarios/native/native.cy.spec.js [hunk 3]
```diff
@@ -314,6 +319,65 @@ describe("scenarios > question > native", () => {
...
+      cy.get("@questionId").then(questionId =>
+        cy.visit(`/question/${questionId}`),
+      );
+
+      cy.findByTestId("native-query-top-bar").within(() => {
+        cy.findByText("This question is written in SQL.").should("be.visible");
```
Comment (kamilmielnik) [inline e2e/test/scenarios/native/native.cy.spec.js:363]: Just to zoom out a bit:

I understand we want to prevent restricted users from seeing the query (the issue is even labeled ".Security related").
But we do that only in frontend.
User can still look the query up in network tab in browser developer tools.

Shouldn't we also enforce this restriction in backend?
If not, what's the point of enforcing it in frontend?

image

**Review by kamilmielnik — DISMISSED** [review]
LGTM :+1: 

I don't understand all of the query builder yet and I can't predict all the consequences of this change, so I'm requesting review from the rest of the team.

I don't understand why this restriction is not enforced in backend - let's discuss this.

File: e2e/test/scenarios/native/native.cy.spec.js (hunk 3 above)
Comment (npfitz) [reply e2e/test/scenarios/native/native.cy.spec.js:363]: I agree that if the purpose of this is to obscure the query from the end user, this doesn't really accomplish the task. The text for the query can be found in the network bar, or by observing the DOM (the div just has `display:none`).

File: frontend/src/metabase/query_builder/actions/navigation.js [hunk 4]
```diff
@@ -60,6 +60,7 @@ export const popState = createThunkAction(
         const shouldRefreshUrl = location.state.card.dataset;
         await dispatch(setCardAndRun(location.state.card, shouldRefreshUrl));
         await dispatch(setCurrentState(location.state));
+        await dispatch(resetUIControls());
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/actions/navigation.js:63]: Could we modify `export const uiControls = handleActions` reducer instead and handle `RESET_QB` action?

**Review by ranquild — DISMISSED** [review]
Please take a look at the inline comment

**Comment by NevRA** [comment]
> LGTM 👍
> 
> I don't understand all of the query builder yet and I can't predict all the consequences of this change, so I'm requesting review from the rest of the team.
> 
> I don't understand why this restriction is not enforced in backend - let's discuss this.

Thanks for the comment! But please don't approve in this case, otherwise, someone might not notice it and automatically merge it

File: frontend/src/metabase/query_builder/actions/navigation.js (hunk 4 above)
Comment (npfitz) [reply frontend/src/metabase/query_builder/actions/navigation.js:63]: I'll need to check that RESET_QB is dispatched, but if so then sure!

**Comment by likeshumidity** [comment]
Spoke to the customer who reported this and told them that the SQL query itself is only hidden from the frontend and not actually secured since it is visible inspecting the API calls. They mentioned that based on how the functionality appears (SQL hidden), they would put secrets in their SQL that they wouldn't want end users to be able to access (through UI or via inspecting API calls).

To be clear, the regression here is that it's now visible in UI in certain circumstances. But there is a bigger issue that is we give the impression of security (by hiding something on the frontend) which means we probably need to either add a warning about this to docs on permissions or secure it on the backend. Ideally, we would secure it on the backend--though I realize that may be a significant departure from current functionality, so it may be that high priority is fix UI regression + add warning to docs (CC @jeff-bruemmer) and create a new issue re: Native SQL findable to any user who with collection access to question even if they have no Native SQL access via API calls.

File: e2e/test/scenarios/native/native.cy.spec.js (hunk 3 above)
Comment (kamilmielnik) [reply e2e/test/scenarios/native/native.cy.spec.js:363]: I guess we have an answer: https://github.com/metabase/metabase/pull/34285#issuecomment-1750698098

File: frontend/src/metabase/query_builder/actions/navigation.js (hunk 4 above)
Comment (npfitz) [reply frontend/src/metabase/query_builder/actions/navigation.js:63]: In the scenario above, the `RESET_QB` action isn't actually dispatched (and neither is Initialize QB). I think that's mainly the issue here. I can try dispatching `RESET_QB` though and seeing if that helps

Comment (npfitz) [reply frontend/src/metabase/query_builder/actions/navigation.js:63]: actually, dispatching RESET_QB causes us to just see a loading screen :/

Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/actions/navigation.js:63]: > we aren't reseting UI controls in all cases when the QB is initialized

`initializeQB` [triggers `resetQB`](https://github.com/metabase/metabase/blob/1efa6c6f000cb4bd38065563176c35ea0027c865/frontend/src/metabase/query_builder/actions/core/initializeQB.ts#L244), but it looks like `initializeQB` purposely [isn't dispatched when navigating back](https://github.com/metabase/metabase/blob/cf1d27c9fea3d64db86a1a0a6f15ecb0be92c71c/frontend/src/metabase/query_builder/actions/navigation.js#L97-L113).

BTW, the custom [back-navigation logic](https://github.com/metabase/metabase/blob/cf1d27c9fea3d64db86a1a0a6f15ecb0be92c71c/frontend/src/metabase/query_builder/actions/navigation.js#L35-L-79) is very buggy:
- #33709
- #34514
- #33708

It looks like dispatching `resetUIControls` is the cheapest effective measure we can take in this case without reworking the entire thing. I tested it manually a bit and I haven't found any regressions due to this change.

**Review by kamilmielnik — APPROVED** [review]
Approving [after all](https://github.com/metabase/metabase/pull/34285#event-10574996748) because [I was asked to look at this again](https://metaboat.slack.com/archives/C057T1QTB3L/p1697009976167689).

I did some manual testing and haven't found any regressions.
e2e test properly reproduces the issue :+1:
