### PR TITLE
Closes UXW-2237 fix admin logo click error

### LINKED ISSUE #65543: Fix admin logo click error
On stats, clicking on metabase logo in left-top corner in admin panel throws the following error

[Slack Message](https://metaboat.slack.com/archives/C505ZNNH4/p1762442818505009)

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #65543
Closes [UXW-2237: Fix admin logo click error](https://linear.app/metabase/issue/UXW-2237/fix-admin-logo-click-error)

Replaces the outdated XMLHttpRequest implementation in the LogoIcon component with modern fetch API and proper request cancellation using AbortController.

### Changes

  - Updated LogoIcon component: Replaced XMLHttpRequest with fetch + AbortController for better error handling and request cancellation
  - Added comprehensive unit tests: Created test suite using fetchMock to verify all component behaviors including data URI handling, fetch requests, and error fallbacks
  - Improved error handling: Better handling of network errors and request abortion

### CODE REVIEW

File: frontend/src/metabase/admin/utils.js [hunk 1]
```diff
@@ -29,11 +30,9 @@ const mapDispatchToProps = {
 };
 
 const _RedirectToAllowedSettings = ({ adminItems, replace }) => {
-  if (adminItems.length === 0) {
-    replace("/unauthorized");
-  } else {
-    replace(adminItems[0].path);
-  }
+  useLayoutEffect(() => {
+    replace(adminItems.length === 0 ? "/unauthorized" : adminItems[0].path);
```
Comment (iethree) [inline frontend/src/metabase/admin/utils.js:34]: it's kind of weird that we retrigger api requests on click here when we stay on the same page, but that's the existing behavior, so no harm done here.

Image

**Review by iethree — APPROVED** [review]
🏆  oh man i've been meaning to do this for years, thanks for getting rid of this weird xhr thingy

Image

File: frontend/src/metabase/admin/utils.js (hunk 1 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/admin/utils.js:34]: yeah I was confused by that too, not sure what's going on with this :D
