### PR TITLE
Fix Slack settings bugs

### LINKED ISSUE #3518: Cannot remove a slack token from slack setup in admin.
1. Add a slack token
2. Try and save (this bit seems a bit wonky as well) 
3. If you're able to save, do so.
4. Now, remove the slack token.
5. You can't even!

Tested on chrome with rc-0.20.0, OSX

### PR DESCRIPTION
**Pull request by tlrobinson**
Fixes:
- slack-token marked as required on front and backend
- validation interpreting 'false' as empty.

Resolves #3518

### CODE REVIEW

**Comment by kdoh** [comment]
JS stuff looks good. I'll defer to @camsaul for the Clojure-y bits.

File: src/metabase/api/slack.clj [hunk 1]
```diff
@@ -9,16 +9,18 @@
 (defendpoint PUT "/settings"
   "Update Slack related settings. You must be a superuser to do this."
   [:as {{slack-token :slack-token, metabot-enabled :metabot-enabled, :as slack-settings} :body}]
-  {slack-token     [Required NonEmptyString]
```
Comment (camsaul) [inline src/metabase/api/slack.clj]: it should at least still be `slack-token NonEmptyString`. No longer `Required`, but if it is passed an non-nil, it should be a non-empty string.

File: src/metabase/api/slack.clj [hunk 2]
```diff
@@ -9,16 +9,18 @@
...
-  (try
-    ;; just check that channels.list doesn't throw an exception (a.k.a. that the token works)
-    (when-not config/is-test?
-      (slack/GET :channels.list, :exclude_archived 1, :token slack-token))
-    (setting/set-many! slack-settings)
-    {:ok true}
-    (catch clojure.lang.ExceptionInfo info
-      {:status 400, :body (ex-data info)})))
+  (if (not slack-token)
+    (setting/set-many! { :slack-token nil, :metabot-enabled false })
```
Comment (camsaul) [inline src/metabase/api/slack.clj]: don't indent clojure maps like JS ones

Comment (camsaul) [inline src/metabase/api/slack.clj]: Remember you should use `when` in Lisp languages if there's only a single condition. `if` is only for `if-else`

Comment (camsaul) [inline src/metabase/api/slack.clj]: in this case you should use `when-not`

File: src/metabase/api/slack.clj [hunk 3]
```diff
@@ -9,16 +9,18 @@
...
+    (try
+      ;; just check that channels.list doesn't throw an exception (a.k.a. that the token works)
+      (when-not config/is-test?
+        (slack/GET :channels.list, :exclude_archived 1, :token slack-token))
+      (setting/set-many! slack-settings)
+      {:ok true}
+      (catch clojure.lang.ExceptionInfo info
+        {:status 400, :body (ex-data info)})))
+  )
```
Comment (camsaul) [inline src/metabase/api/slack.clj]: indentation

**Comment by camsaul** [comment]
Clojure code needs some cleanup but once that's done 👍

File: src/metabase/api/slack.clj (hunk 2 above)
Comment (camsaul) [inline src/metabase/api/slack.clj]: Whoops meant to say you should use `(if-not ...` here instead of `(if (not ...)`. That's the idiomatic way of doing things in Clojure

**Comment by tlrobinson** [comment]
@camsaul is this better?

**Comment by camsaul** [comment]
yeah. WFM 👍
