### PR TITLE
Fix pivot table de/serialization

### LINKED ISSUE #30133: Pivot table with 2 group by's gets loaded incorrectly on serialization
**Describe the bug**

**Logs**
Please include JavaScript console logs (open the browser dev tools and check the "console" tab) as well as the server logs (Metabase logs that you can get from Settings -> Admin -> Troubleshooting -> Logs) around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
Using https://github.com/paoliniluis/metabase-serialization as the base
1) create a question like the following:
image
2) view it as a pivot table and make sure it's configured like
image
3) now dump and load in destination
4) see that it changed
image

**Expected behavior**
It should be loaded in the same way as it was saved in the origin

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Metabase version: 1.46.1

**Severity**
P2

**Additional context**
NA

### PR DESCRIPTION
**Pull request by sansolovyov**
Just checks that pivot settings are exported and imported, seems like that was a problem half a year ago.

resolves #30133 and #30134

### CODE REVIEW

**Comment by calherries** [comment]
@piranha Just confirming, did you check these tests fail with 46.1?

**Comment by piranha** [comment]
@calherries ohhh I did not and will do that right now

**Comment by piranha** [comment]
I haven't been able to reproduce row/column moving to rows, but sorting problem reproduces right away.

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj [hunk 1]
```diff
@@ -735,3 +735,48 @@
...
+                                                 :collection_id coll-id
+                                                 :dataset_query {:type     :query
+                                                                 :database db-id
+                                                                 :query    {:source-table table-id
+                                                                            :aggregation  [:sum [:field pf1 nil]]
+                                                                            :breakout     [[:field field-id nil]]}}
+                                                 :visualization_settings
+                                                 {:pivot_table.column_split
+                                                  {:columns [["field" pf1 nil]]
+                                                   :rows    [["field" pf2 nil]]
```
Comment (calherries) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:761]: I wonder how you got this data structure shape. When I tried to reproduce the issue (https://github.com/metabase/metabase/issues/30133) I got this:

```json
    "visualization_settings": {
        "pivot_table.column_split": {
            "rows": [
                [
                    "field",
                    45,
                    {
                        "base-type": "type/Text",
                        "source-field": 43
                    }
                ]
            ],
            "columns": [
                [
                    "field",
                    58,
                    {
                        "base-type": "type/Text",
                        "source-field": 40
                    }
                ]
            ],
            "values": [
                [
                    "aggregation",
                    0
                ],
                [
                    "aggregation",
                    1
                ],
                [
                    "aggregation",
                    2
                ],
                [
                    "aggregation",
                    3
                ],
                [
                    "aggregation",
                    4
                ]
            ]
        }
    },
```

**Comment by piranha** [comment]
@calherries thanks a lot! I really did test on sample data, and it worked with no issues. New test catches that.

File: src/metabase/models/serialization.clj [hunk 2]
```diff
@@ -1192,6 +1192,16 @@
           (m/update-existing    :click_behavior import-viz-click-behavior-link)
           (m/update-existing-in [:click_behavior :parameterMapping] import-viz-click-behavior-mappings)))
 
+(defn- export-pivot-table [settings]
+  (some-> settings
+          (m/update-existing-in [:pivot_table.column_split :rows] ids->fully-qualified-names #_export-pivot-table-fields)
+          (m/update-existing-in [:pivot_table.column_split :columns] ids->fully-qualified-names #_export-pivot-table-fields)))
```
Comment (calherries) [inline src/metabase/models/serialization.clj:1198]: same below
```suggestion
  (some-> settings
          (m/update-existing-in [:pivot_table.column_split :rows] ids->fully-qualified-names)
          (m/update-existing-in [:pivot_table.column_split :columns] ids->fully-qualified-names)))
```

**Review by calherries — APPROVED** [review]
Looks fine to merge but why does using `test-data` surface the issue but `sample-dataset` doesn't?

We need to make sure all the IDs in the destination DB don't just happen to align with the IDs in the source DB by chance, because they both contain the same datasets. I don't have a solution to this, I'm just stating the problem here

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj [hunk 3]
```diff
@@ -735,3 +735,54 @@
...
+                  (-> (serdes/with-cache (into [] (extract/extract {})))
+                      (storage/store! dump-dir))))))
+
+          (ts/with-dest-db
+            (mt/dataset test-data
+              (mt/$ids nil
+                (serdes/with-cache (serdes.load/load-metabase! (ingest/ingest-yaml dump-dir)))
+
+                (let [viz (:visualization_settings
+                           (t2/select-one Card :entity_id (:entity_id @card1s)))]
```
[the remark this answers is not in the document]
Comment (piranha) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:777]: Hah, I specifically wrote it in this way so that query is on one line and getter is on the other; but I guess I could even use `select-one-fn` here. :)

File: src/metabase/models/serialization.clj (hunk 2 above)
Comment (piranha) [reply src/metabase/models/serialization.clj:1198]: oops 😁

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj [hunk 4]
```diff
@@ -735,3 +735,54 @@
...
                         "throws")))))))))))
+
+(deftest pivot-export-test
+  (testing "Pivot table export and load correctly"
+    (let [card1s (atom nil)]
+      (ts/with-random-dump-dir [dump-dir "serdesv2-"]
+        (ts/with-source-and-dest-dbs
+          (ts/with-source-db
+            (mt/dataset test-data
+              (mt/$ids nil
```
[the remark this answers is not in the document]
Comment (piranha) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:746]: Ehh, this only works when there is only 1 child. It's quite irritating that it works like that, since it bites you when you least expect it. :)

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj [hunk 5]
```diff
@@ -735,3 +735,54 @@
...
+                                               :column_settings
+                                               {(format "[\"ref\",[\"field\",%s,null]]" %users.name)
+                                                {:pivot_table.column_sort_order "descending"}}}}]
+                  (reset! card1s card)
+                  (-> (serdes/with-cache (into [] (extract/extract {})))
+                      (storage/store! dump-dir))))))
+
+          (ts/with-dest-db
+            (mt/dataset test-data
+              (mt/$ids nil
```
[the remark this answers is not in the document]
Comment (piranha) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:773]: For example in that case there are two children and the removal of `nil` breaks the test (since `load-metabase!` call is used as a table name, haha). So I don't really want to remove nils in both cases - it's less ambiguous this way.

[the remark this answers is not in the document]
Comment (calherries) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:773]: Yes, you're right.

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj (hunk 3 above)
[the remark this answers is not in the document]
Comment (calherries) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:777]: Both are fine objectively, it's just a little strange to read this on two separate lines, I can't quite articulate why.

In my head, this kind of thing is so familiar, I want to read this in one step, so I want it on one line.
```clojure
(let [viz (:visualization_settings (t2/select-one Card :entity_id (:entity_id @card1s)))] ...
;; or better
(let [viz (t2/select-one-fn :visualization_settings Card :entity_id (:entity_id @card1s)))] ...
;; reads as "get visualization_settings from the card"

(let [viz (:visualization_settings 
           (t2/select-one Card :entity_id (:entity_id @card1s)))
;; reads as "get the card, then get the visualization_settings from the card"
```

**Comment by piranha** [comment]
> Looks fine to merge but why does using test-data surface the issue but sample-dataset doesn't?

It does surface the issue too, but you have to have different db, which is something I did not realize at first. :)

I redid test with a sample-dataset and it still behaves in an expected way, plus it checks that column ids are indeed different between two dbs.

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj (hunk 3 above)
[the remark this answers is not in the document]
Comment (piranha) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj]: Personal preferences, I guess. :) I'm used to 80 chars line limit, and to structuring most of the complex actions on line-by-line basis, so that two-line expression looked natural to me. Especially given how long `:visualization_settings` is — it just felt uncluttered to put it on a separate line. :)

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj [hunk 6]
```diff
@@ -735,3 +735,56 @@
...
+          (ts/with-dest-db
+            (mt/dataset sample-dataset
+              (mt/$ids nil
+                (serdes/with-cache (serdes.load/load-metabase! (ingest/ingest-yaml dump-dir)))
+
+                (let [viz (t2/select-one-fn :visualization_settings Card :entity_id (:entity_id @card1s))]
+                  (is (contains? viz :pivot_table.column_split))
+                  ;; column ids are different in different dbs
+                  (is (not= (get-in @card1s [:visualization_settings :pivot_table.column_split :rows 0 1])
+                            (get-in viz [:pivot_table.column_split :rows 0 1])))
```
Comment (piranha) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:780]: @calherries I'm a bit afraid this line will flake (there is no promise that ids will indeed be different), but it's like an insurance that we're getting some real action here.

Comment (calherries) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:780]: better to use `testing` blocks to add meaningful error descriptions instead of just leaving a comment
```suggestion
                  (testing "check column ids are different in different dbs, because otherwise this test could be a false negative"
                    (is (not= (get-in @card1s [:visualization_settings :pivot_table.column_split :rows 0 1])
                              (get-in viz [:pivot_table.column_split :rows 0 1]))))
```

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj [hunk 7]
```diff
@@ -735,3 +735,56 @@
...
+                  (-> (serdes/with-cache (into [] (extract/extract {})))
+                      (storage/store! dump-dir))))))
+
+          (ts/with-dest-db
+            (mt/dataset sample-dataset
+              (mt/$ids nil
+                (serdes/with-cache (serdes.load/load-metabase! (ingest/ingest-yaml dump-dir)))
+
+                (let [viz (t2/select-one-fn :visualization_settings Card :entity_id (:entity_id @card1s))]
+                  (is (contains? viz :pivot_table.column_split))
```
Comment (calherries) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:777]: What is this testing on an abstract level? I'd suggest to make it clearer with a `testing` description

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj [hunk 8]
```diff
@@ -735,3 +735,56 @@
...
+                  ;; column ids are different in different dbs
+                  (is (not= (get-in @card1s [:visualization_settings :pivot_table.column_split :rows 0 1])
+                            (get-in viz [:pivot_table.column_split :rows 0 1])))
+                  (is (= [[:field %people.name {:base-type    :type/Text
+                                                :source-field %orders.user_id}]]
+                         (get-in viz [:pivot_table.column_split :rows])))
+                  (is (= [[:field %products.title {:base-type    :type/Text
+                                                   :source-field %orders.product_id}]]
+                         (get-in viz [:pivot_table.column_split :columns])))
```
Comment (calherries) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:786]: These deserve a `testing` block too, maybe even referencing the old issue `(metabase#30133)`

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj [hunk 9]
```diff
@@ -735,3 +735,56 @@
...
+                  (is (= "descending"
+                         (get-in viz [:column_settings
+                                      (format "[\"ref\",[\"field\",%s,null]]" %people.name)
+                                      :pivot_table.column_sort_order]))))))))))))
```
Comment (calherries) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:790]: I'd create a `testing` block for this, maybe even referencing the old issue `(metabase#30134)`

**Review by calherries — COMMENTED** [review]
You should get in the habit of documenting what we're testing. Test code is specific and concrete (unless we're using generative tests) but the logic we're testing should apply to an abstract state space, and that needs explaining in english. Simply writing "pivot table export and load works correctly" isn't enough for our future selves to work out what exactly we're testing here.

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj (hunk 6 above)
Comment (calherries) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:780]: Yeah, that's not ideal. Can you find a way to ensure that the test IDs are different, at least with high probability? I'm thinking of a hack like creating an extra database in the destination DB with one field and one table.

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj (hunk 3 above)
[the remark this answers is not in the document]
Comment (calherries) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj]: Yep, makes sense. At metabase we generally go up to 120 chars, don't be afraid to use it

[the remark this answers is not in the document]
Comment (piranha) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj]: It's not about fear, it was me who put 80 chars limit in place, takes time to unlearn old habits. 😁

File: enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj (hunk 6 above)
Comment (calherries) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:780]: Maybe you can use `mt/with-temp` for this. Just create a database, table and a field before calling `mt/dataset` to be safe

Comment (piranha) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj:780]: Results are not reassuring. :) So if I leave test in its current form, ids are 21 (source) vs 7 (dest). If I create db+table+field, it because 21 vs 24, which is closer and makes me uneasy. :\ I'm thinking of living it in place with some comment that if it flakes, here's the discussion.

**Review by calherries — APPROVED** [review]
Nice!
