### PR TITLE
Fix underlying records drill for nested queries

### LINKED ISSUE #13504: Cannot drill-through "View these ..." when aggregated results are filtered
**Describe the bug**
This setup
image

Throws this error
image

When Viewing (drilling down to) Details:
image

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)
Value does not match schema: {:query {:filter (named [nil nil nil (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses") (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses") (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses") (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses") (named (named [nil (named [(named (not (= :value :aggregation)) :value) nil (not (present? "type-info"))] "field") nil] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment") "other-clauses")] "Must be a valid instance of one of these clauses: :and, :or, :not, :=, :!=, :<, :>, :<=, :>=, :between, :starts-with, :ends-with, :contains, :does-not-contain, :inside, :is-empty, :not-empty, :is-null, :not-null, :time-interval, :segment")}}

**To Reproduce**
1. Create question as outlined above
2. Drill down with "View these" as shown above

**Expected behavior**
List of detail records If I take away filter in "Filter" section (see above) then it work.s

**Screenshots**
See above

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 86.0.4240.75
- Your operating system: Docker on Debian 10
- Your databases: SQL Server (for source) 
- Metabase version: v0.36.6
- Metabase hosting environment: Docker on Debian 10
- Metabase internal database: MySQL

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Is a show stopper for this application scenario

**Additional context**

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/13504

How to test:
- Follow steps from this comment https://github.com/metabase/metabase/issues/13504#issuecomment-710087008

Screenshot 2022-10-04 at 12 21 01

### CODE REVIEW

File: frontend/src/metabase-lib/lib/Question.ts [hunk 1]
```diff
@@ -538,16 +538,20 @@ class QuestionInner {
...
     if (!(query instanceof StructuredQuery)) {
       return this;
     }
 
-    query = values.reduce(
-      (query, { value, column }) => drillFilter(query, value, column),
-      query,
-    );
+    dimensions.forEach(({ value, column }) => {
+      if (column.source !== "aggregation") {
```
Comment (ranquild) [inline frontend/src/metabase-lib/lib/Question.ts:551]: This is from https://github.com/metabase/metabase/blob/e8526c757ee9cb1cd883543ebd8170e531a63634/frontend/src/metabase/visualizations/lib/apply_tooltips.js#L211 AFAIK we should never get `query-transform` columns here, so I only checked for aggregation columns. 

The thing is that `apply_tooltips` removes aggregation dimensions from one-stages queries and it doesn't do for other cases. It seems too risky to modify `apply_tooltips`, that's why I only changed it here.

**Review by kulyk — APPROVED** [review]
Looks good and works as described
