### PR TITLE
[serdes] check full export for escaping cards

### LINKED ISSUE #47991: Serialization exports questions with bad (?) references
### Describe the bug

Second time in 2 days where we get a report of a failed serialization due to to the fact that the card doesn't exist and it's probably on a personal collection.  We need to signal this on the export process and prevent the issue

### To Reproduce

1) make a question and save it on the personal collection
2) make a second question which uses the question of the personal collection as the source
3) export and import
4) see the process failing due to a failing reference

### Expected behavior

Signal this on the export process and even more, do not export the card with the invalid reference!

### Logs

NA

### Information about your Metabase installation

```JSON
It's been always like this
```

### Severity

P1

### Additional context

Reported 2 times 2 days. Related to https://github.com/metabase/metabase/issues/47976

### PR DESCRIPTION
**Pull request by sansolovyov**
Fixes #47991 

Combines two paths of serialization we had before (`extract-metabase` and `extract-subtrees`) into a single one, so that `escape-analysis` is always checked. Also contains rewrite of `escape-analysis` to reduce the number of queries in an attempt to lessen the slowdown of full export.

@bshepherdson asking for your review just because my serialization-reviewing teammate is ooo for 1.5 weeks :)

----

*Timings for the full export*

On my laptop for stats db after a few runs
Old way: 256s
New way: 278s

This is a 9% slowdown, which I think is acceptable to make it more correct. It's not very scientific though as it fluctuates from 200 to 250s. 🤯 Also partial exports are a bit faster, since those had escape analysis anyways and now it makes less requests to the database.

### CODE REVIEW

**Review by qnkhuat — APPROVED** [review]
The rewrite of escape analysis is brilliant, IMO. The only downside is that performance is impacted, which, from the result, I think is acceptable. 

Even when performance is worse than expected, we can rewrite descendants so it's batched.

This LGTM, but it would be nice to have Braden's eyes on this, too

**Comment by qnkhuat** [comment]
oh, how about we add `:skip-escape-analysis` option?

**Comment by piranha** [comment]
Oh, nice idea.

**Comment by piranha** [comment]
Ah, nope, other way around. Escape analysis phase takes 1-2 seconds of the whole time, most of the time added is spent running ascendants/descendants, and obviously in that code there is no good way around it (unless we have a separate path like before, but I'd love to not have it).

File: enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj [hunk 1]
```diff
@@ -152,43 +112,51 @@
...
   "Returns a reducible stream of entities to serialize"
-  [{:keys [targets] :as opts}]
+  [opts]
   (serdes.backfill/backfill-ids!)
-  (if (seq targets)
-    (extract-subtrees opts)
-    (extract-metabase opts)))
+  (extract-subtrees opts))
+
+(comment
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:155]: Please **leave this in!** I love these kinds of `comment` blocks and my personal code is full of them. I'm in favour of adopting that practice at Metabase.

File: enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj [hunk 2]
```diff
@@ -1376,17 +1376,19 @@
...
-                      [{:model "Card"          :id c4-eid  :label "question_4_1"}]
-                      ;; card that parameter on dashboard linked to
-                      [{:model "Card"          :id c1-1-eid  :label "question_1_1"}]
-                      ;; card that the card on dashboard linked to
-                      [{:model "Card"          :id c1-2-eid  :label "question_1_2"}]}
-                    (->> (extract/extract {:targets [["Collection" coll4-id]] :no-settings true :no-data-model true})
-                         (map serdes/path)
-                         set)))))))))
+          #_;; (sanya) NOTE: this looks like an irrelevant test? I mean if we do escape analysis and don't allow
+          ;; leaking cards from unrelated collections, why this test?
```
Comment (bshepherdson) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj:1380]: I think it's badly phrased, but this test is still relevant.

Parameter on a dashboard gets its values from a card in another collection. That link should appear in `deps` and `descendants`.

Therefore:
- Selective export rejects it, since it's escaping.
- Global export is fine, and during import the `deps` work properly.

So I think this test is still important, though its expectation should be changed to an escape error. This is the gap called out in a TODO, which I highlighted with a comment.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj [hunk 3]
```diff
@@ -131,19 +71,39 @@
...
-  (when-not (empty? escaped-questions)
-    (log/warnf "Failed to export Cards based on questions outside requested collections: %s"
-               (str/join ", " (for [[curated-id alien-id] escaped-questions]
-                                (str (card-label curated-id) " -> " (card-label alien-id)))))))
+(defn- parse-target [[model-name id :as target]]
+  (if (string? id)
+    [model-name (serdes/eid->id model-name id)]
+    target))
+
+(defn- escape-analysis [{colls "Collection" cards "Card" :as _nodes} reasons]
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:79]: It's not clear at all to me, looking at the code for both `escape-analysis` and `extract-subtrees`, what `reasons` are meant to be. I don't grok the shape of the `nodes`, which means I can't grok the (fairly obscure) code for `reasons` either.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj [hunk 4]
```diff
@@ -152,43 +112,51 @@
...
-                            (update-vals #(set (map second %))))
-            extract-ids (fn [[model ids]]
-                          (serdes/extract-all model (merge opts {:where [:in :id ids]})))]
+  (let [inner-targets (if (seq targets)
+                        (mapv parse-target targets)
+                        (mapv vector (repeat "Collection") (collection-set-for-user user-id)))
+        nodes         (set/union
+                       (u/traverse inner-targets #(serdes/ascendants (first %) (second %)))
+                       (u/traverse inner-targets #(serdes/descendants (first %) (second %))))
+        reasons       (u/index-by #(take 2 %) #(first (nnext %)) nodes)
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:129]: I think using destructuring here would be good for self-documentation?

```suggestion
        reasons       (u/index-by #(subvec % 0 2)
                                  (fn [[_model _id maybe-more]] maybe-more)
                                  nodes)
```

or just `#(get % 2)`, which doesn't throw `IndexOutOfBoundsException`s like `nth`.

File: src/metabase/models/serialization.clj [hunk 5]
```diff
@@ -513,8 +513,8 @@
       nested? (extract-reducible-nested model-name (dissoc opts :where)))))
 
 (defmulti descendants
-  "Returns set of `[model-name database-id]` pairs for all entities contained or used by this entity. e.g. the Dashboard
-   implementation should return pairs for all DashboardCard entities it contains, etc.
+  "Returns set of `[model-name database-id {initiating-model id}]` pairs for all entities contained or used by this
```
Comment (bshepherdson) [inline src/metabase/models/serialization.clj:516]:
```suggestion
  "Returns set of `[model-name database-id {initiating-model id}]` triples for all entities contained or used by this
```

File: src/metabase/models/collection.clj [hunk 6]
```diff
@@ -1405,22 +1407,24 @@
...
 (defmethod serdes/descendants "Collection" [_model-name id]
-  (let [location    (t2/select-one-fn :location Collection :id id)
-        child-colls (set (for [child-id (t2/select-pks-set :model/Collection {:where [:and
-                                                                                      [:like :location (str location id "/%")]
-                                                                                      [:or
-                                                                                       [:not= :type trash-collection-type]
-                                                                                       [:= :type nil]]]})]
-                           ["Collection" child-id]))
+  (let [location    (when id (t2/select-one-fn :location Collection :id id))
+        child-colls (when id ;; (sanya) NOTE: I'm not sure we should not descend here, but it seems we did not before
```
Comment (bshepherdson) [inline src/metabase/models/collection.clj:1417]: This doesn't need to be recursive; the graph traversal in the core serdes code will find the transitive closure of nested collections under this collection.

File: src/metabase/models/serialization.clj (hunk 5 above)
Comment (bshepherdson) [reply src/metabase/models/serialization.clj:516]: Or a map, per the refactoring we discussed.

Either way, an example and explanation of what might go in that map is important, I think.

File: src/metabase/util.cljc [hunk 7]
```diff
@@ -1038,6 +1039,45 @@
...
+   (group-by first second + 0 [[1 3] [1 4] [2 5]]) => {1 7,     2 5}
+   (group-by first second         [[1 [3]] [1 [4]] [2 [5]]]) => {1 [[3] [4]], 2 [[5]]}
+   (group-by first second concat  [[1 [3]] [1 [4]] [2 [5]]]) => {1 (3 4), 2 (5)}
+   (group-by first second into    [[1 [3]] [1 [4]] [2 [5]]]) => {1 [3 4], 2 [5]}
+   (group-by first second into [] [[1 [3]] [1 [4]] [2 [5]]]) => {1 [3 4], 2 [5]}
+   (group-by first second into () [[1 [3]] [1 [4]] [2 [5]]]) => {1 (4 3), 2 (5)}
+   ;; as filter:
+   (group-by first any? second even? conj () [[1 3] [1 4] [2 5]])      => {1 (4)}
+   ;; as reducer (see index-by below):
+   (group-by first any? second even? max   0 [[1 3] [1 6] [1 4] [2 5]] => {1 6})"
```
Comment (bshepherdson) [inline src/metabase/util.cljc:1053]: Can we vertically align the example inputs and outputs here? This is hard to read.

Comment (bshepherdson) [reply src/metabase/util.cljc:1053]: Also it should include an example for the 2-arity, eg. equivalent to OG `clojure.core/group-by`. I thought it was missing at first glance!

**Review by bshepherdson — CHANGES_REQUESTED** [review]
See also the refactoring of `serdes/descendants` I sent you in a DM, to return a map `{[model id] {"OtherModel" other-id}}` rather than a set of triples `#{[model id {"OtherModel" other-id}]}`.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj (hunk 3 above)
Comment (piranha) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj:79]: Oh right, I wanted to make it `mu/defn`, but then all the tests were broken and I promptly forgot about this. 😁

File: src/metabase/models/collection.clj (hunk 6 above)
Comment (piranha) [reply src/metabase/models/collection.clj:1417]: riiight

But I'm still unsure if it should return children for a root collection. Like, it needs for consistency, but it never did before (well, we also don't have a way to specify root collection from the CLI/APIs, so maybe it's less of a question).

Comment (piranha) [reply src/metabase/models/collection.clj]: just an update: it should not return children for a root collection, because it'll just export everything all the time 🤣

**Review by bshepherdson — APPROVED** [review]
