### PR TITLE
Handle numeric values for :number parameters in JWTs

### LINKED ISSUE #20845: Embedding with Locked parameters does not allow numeric values
**Describe the bug**
Embedding with Locked parameters does not allow numeric values.
Regression in 0.42

**To Reproduce**
1. Question > Sample > `select count(*) from orders where quantity={{qty_locked}}` - set variable as Number
2. Enable embedding and set parameter to **Locked**
3. Generate JWT token with locked parameter as **numeric** value (even though the example preview recommends a string value):
```
{
  "resource": {
    "question": 853
  },
  "params": {
    "qty_locked": 1
  }
}
```
4. Go to the URL - errors
image

Backend only has this unhelpful error:
```
2022-03-04 15:52:31,029 DEBUG middleware.log :: GET /api/session/properties 200 18.8 ms (2 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (71 total active threads) Queries in flight: 0 (0 queued)
2022-03-04 15:52:34,723 DEBUG middleware.log :: GET /api/embed/card/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6ODUzfSwicGFyYW1zIjp7InF0eV9sb2NrZWQiOjF9fQ.n2zsOej1QYV3603wHZJXEHIcnq8QxgniYOclB6f7tMI 200 3.4 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
2022-03-04 15:52:34,756 DEBUG middleware.log :: GET /api/session/properties 200 12.5 ms (2 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (3 idle, 0 queued) (72 total active threads) Queries in flight: 0 (0 queued)
2022-03-04 15:52:34,909 DEBUG middleware.log :: GET /api/embed/card/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6ODUzfSwicGFyYW1zIjp7InF0eV9sb2NrZWQiOjF9fQ.n2zsOej1QYV3603wHZJXEHIcnq8QxgniYOclB6f7tMI/query 400 5.9 ms (3 DB calls) 
"Don't know how to create ISeq from: java.lang.Integer"
```

**Expected behavior**
Allow numeric parameters.
While we're at it, would be nice if we allowed the resource as string, since I see that as a common mistake as well.

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.42.2

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #20845

There were two things broken here:

1. We assumed the JWT parameters were always something seqable (e.g. a string or a vector). This broke when the parameter was a number
2. The embedding code passes parsed parameters as a vector; and the code that parsed values for `:number` parameters assumed all vectors were vectors of strings (as opposed to a vector of numbers in this case)

### CODE REVIEW

File: src/metabase/driver/common/parameters/values.clj [hunk 1]
```diff
@@ -208,27 +208,28 @@
...
+    ;; if the value is a string, then split it by commas in the string. Usually there should be none.
+    ;; Parse each part as a number.
+    (string? value)
+    (let [parts (for [part (str/split value #",")]
+                  (parse-number part))]
+      (if (> (count parts) 1)
+        ;; If there's more than one number return an instance of `CommaSeparatedNumbers`
+        (i/map->CommaSeparatedNumbers {:numbers parts})
+        ;; otherwise just return the single number
+        (first parts)))))
```
Comment (camsaul) [inline src/metabase/driver/common/parameters/values.clj:232]: Unrelated to fix -- fixed the indentation here (`cond` should have its body indented two spaces)

File: src/metabase/driver/common/parameters/values.clj [hunk 2]
```diff
@@ -305,7 +306,9 @@
   (try
     (parse-value-for-type (:type tag) (parse-tag tag params))
     (catch Throwable e
-      (throw (ex-info (tru "Error determining value for parameter: {0}" (ex-message e))
+      (throw (ex-info (tru "Error determining value for parameter {0}: {1}"
+                           (pr-str (:name tag))
+                           (ex-message e))
```
Comment (camsaul) [inline src/metabase/driver/common/parameters/values.clj:311]: Unrelated to fix, but I tweaked this Exception to include the name of the parameter it failed to parse a value for, which makes debugging errors in embedding easier

**Review by flamber — APPROVED** [review]
This seems to work with everything I try to throw at it.

Would it be possible to do something similar with the resource, so it would work if you accidentally set the value to string (have seen this several times)? Currently we fail with `Assert failed: (integer? card-id)`
```
{
  "resource": {
    "question": "123"
  }
}
```

**Comment by camsaul** [comment]
@flamber can you open an issue for the integer thing? I'll try to get to it once I get some other pending PRs in
