### PR TITLE
Mantine number input fix

### LINKED ISSUE #35312: [MLv2] [Bug] FE - Fix an issue with fractional numbers in `NumberInput`

### PR DESCRIPTION
**Pull request by ranquild**
Closes https://github.com/metabase/metabase/issues/35312

How to verify:
- `yarn storybook`
- Open http://localhost:6006/?path=/story/inputs-numberinput--default-story
- Make sure you can enter numbers with arbitrary precision

Screenshot 2023-11-02 at 16 04 35

### CODE REVIEW

File: frontend/src/metabase/ui/components/inputs/TimeInput/TimeInput.tsx [hunk 1]
```diff
@@ -19,43 +19,55 @@ export function TimeInput({
...
   defaultValue = value,
   onChange,
+  onFocus,
+  onBlur,
   ...props
 }: TimeInputProps) {
-  const [inputValue, setInputValue] = useState(
-    defaultValue ? formatTime(defaultValue) : "",
-  );
+  const [inputValue, setInputValue] = useState(formatValue(defaultValue));
```
Comment (ranquild) [inline frontend/src/metabase/ui/components/inputs/TimeInput/TimeInput.tsx:26]: Just wanted to make the implementation close to `NumberInput`, no behavior changes

**Review by kulyk — APPROVED** [review]
