### PR TITLE
fix: logo in email is not centered

### LINKED ISSUE #68452: Custom Logo isn't loaded properly on User Invite Email
### Describe the bug

Custom Logo isn't loaded properly on User Invite Email

### To Reproduce

1. Go to Appearance -> Branding -> Upload a Logo ... I uploaded myself :P 

Image

And Invite someone to metabase. You will get this email:

Image

### Expected behavior

My logo to show up, same as the metabase logo:

Image

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.57.9 and 1.58.2.5
```

### Severity

Makes Whitelabeling obsolete cause the company's "logo" is missing

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by undrfined**
closes #68452
Closes [UXW-2860: Custom Logo isn't loaded properly on User Invite Email](https://linear.app/metabase/issue/UXW-2860/custom-logo-isnt-loaded-properly-on-user-invite-email)

### Description

Logo image in emails wasn't centered if it was rectangular. Now it is.

### How to verify

1. Change the logo image to be rectangular
2. Go to Admin -> People
3. Invite someone
4. Get the email

### Demo

Before:
image

After:
image

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

**Review by kevinkelleher12 — COMMENTED** [review]
Looks good to me! But we may want someone from the backend to double check the changes to the clojure code

File: src/metabase/channel/email/logo.clj [hunk 1]
```diff
@@ -0,0 +1,41 @@
+ (ns metabase.channel.email.logo
```
Comment (nvoxland) [inline src/metabase/channel/email/logo.clj:1]: Looks like an extra space here?

File: src/metabase/channel/email/messages.clj [hunk 2]
```diff
@@ -39,18 +40,21 @@
...
-    (cond
-      (= url "app/assets/img/logo.svg") "http://static.metabase.com/email_logo.png"
+  (:image-src (logo-bundle)))
 
-      :else nil)))
-      ;; NOTE: disabling whitelabeled URLs for now since some email clients don't render them correctly
-      ;; We need to extract them and embed as attachments like we do in metabase.channel.render.image-bundle
-      ;; (data-uri-svg? url)               (themed-image-url url color)
-      ;; :else                             url
+(defn logo-attachment
```
Comment (nvoxland) [inline src/metabase/channel/email/messages.clj:54]: this can be defn-

**Review by nvoxland — APPROVED** [review]
Couple minor fixes to suggest
