### PR TITLE
fix: allow dashboard caching in read-only mode

### LINKED ISSUE #70481: Remote sync - cannot update dashboard caching policy on a read-only instance
### Describe the bug

There is no way to apply or modify the dashboard level caching policy when an instance is set to Read-only:
- the caching policy is not transferred via remote sync
- when sync mode is Read-only the policy cannot be updated

Image

### To Reproduce

1. Configure remote sync
2. Create a dashboard in a synced collection
3. Set a dashboard specific caching policy
4. Commit the changes, and see that the policy set is not exported to Git
5. Pull the changes on a read only instance
6. See that the policy is not applied, but it is not possible to update it manually either

### Expected behavior

It should be possible to set or update the caching policy on a read-only instance. 
For now, I think we should just keep the policy editable.

In a future enhancement we may decide to include it in the sync, but I believe we should still allow it to be overriden locally as different environments may require different caching policies.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Reported on 1.57.13, reproduced on 1.58.7
```

### Severity

P1 - Blocker for users using remote sync and dashboard caching policies

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edpaget**
closes #70481
### Description

We were denying changing caching policy for dashboards on read-only
remote-synced instances because we set can-write? to false for
dashboards when we are in read-only mode.

we also need to create a new boolean flag we can return to the frontend
to indicate that caching is still allowed even when editing a dashboard
is otherwise disabled.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/DashboardHeader/buttons/DashboardActionMenu.tsx [hunk 1]
```diff
@@ -117,19 +117,19 @@ const DashboardActionMenuInner = ({
...
-              leftSection={<Icon name="gear" />}
-              onClick={openSettingsSidebar}
-            >
-              {t`Edit settings`}
-            </Menu.Item>
-
-            {moderationItems}
-          </>
+        {(canEdit ||
+          (dashboard?.can_set_cache_policy &&
```
Comment (alxnddr) [inline frontend/src/metabase/dashboard/components/DashboardHeader/buttons/DashboardActionMenu.tsx]: nit: would be a bit nicer to extract a variable `const canConfigureCaching = PLUGIN_CACHING.isGranularCachingEnabled() && dashboard?.can_set_cache_policy` and have this condition as `canEdit || canConfigureCaching`

**Review by alxnddr — APPROVED** [review]

**Review by nvoxland — APPROVED** [review]
