### PR TITLE
Fix: UXW-382 - Public Links menu item within sharing menu is too large

### LINKED ISSUE #61518: Public Links menu item within sharing menu is too large
### Describe the bug

Image

I'd do something like this instead, with "Enable" going to the proper page in Admin Settings:

Image

### To Reproduce

1. Go to a saved question
2. Click the Sharing action icon button
3. Sing the song "One of These Things Is Not Like the Others" in your head as you notice that one of the menu items is larger than it should be.

### Expected behavior

Image

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "databricks",
      "druid-jdbc",
      "postgres",
      "mongo",
      "redshift",
      "bigquery-cloud-sdk",
      "snowflake",
      "athena",
      "h2",
      "clickhouse",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-07-28",
      "tag": "vUNKNOWN",
      "hash": "ffb583c"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

P2

### Additional context

P2 because it looks broken.

### PR DESCRIPTION
**Pull request by bpander**
Closes https://github.com/metabase/metabase/issues/61518
Closes UXW-382

### Description

Updates "Public link" menu item for admins when public links aren't enabled so it doesn't look obviously broken.

### How to verify

See https://github.com/metabase/metabase/issues/61518 for repro steps.

No changes will be made to the non-admin state for this bugfix ([Slack thread](https://metaboat.slack.com/archives/C096M2BBGHH/p1753901002600299?thread_ts=1753899755.848609&cid=C096M2BBGHH)).

### Demo

https://github.com/user-attachments/assets/4e42ae3a-719d-47aa-ad9e-9ba0fce5ed33

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/embedding/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx [hunk 1]
```diff
@@ -30,12 +38,21 @@ export function PublicLinkMenuItem({
...
+            {t`Public link`}
+            <Button
+              component={Link}
+              to="/admin/settings/public-sharing"
+              target="_blank"
+              variant="subtle"
+              h="auto"
+              lh="inherit"
+              ml="sm"
+              className={cx(CS.floatRight, CS.borderless, CS.p0)}
```
Comment (iethree) [inline frontend/src/metabase/embedding/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx]: I think we want to avoid pulling in these global classes where possible, and in any event, I don't think `.borderless` or `.floatRight` are doing anything here


```suggestion
              p={0}
```

File: frontend/src/metabase/ui/components/overlays/Menu/Menu.module.css [hunk 2]
```diff
@@ -16,7 +16,11 @@
     color: var(--mb-color-text-light);
   }
 
-  &:hover {
+  &.ignoreHover {
+    cursor: default;
+  }
+
+  &:hover:not(.ignoreHover) {
```
Comment (iethree) [inline frontend/src/metabase/ui/components/overlays/Menu/Menu.module.css]: what if instead of using a bespoke .ignoreHover class in a global UI component, we remove the hover highlight from :disabled items, and instead just set that menu item as disabled? I think this actually lines up with default mantine styles: https://mantine.dev/core/menu/#disabled-items

File: frontend/src/metabase/embedding/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx [hunk 3]
```diff
@@ -22,6 +25,11 @@ export function PublicLinkMenuItem({
         data-testid="embed-menu-public-link-item"
         leftSection={<Icon name="link" aria-hidden />}
         onClick={onClick}
+        {...(!isPublicSharingEnabled && {
+          onClick: undefined,
+          component: "div",
+          className: cx(MenuStyles.ignoreHover, CS.textLight),
```
Comment (iethree) [inline frontend/src/metabase/embedding/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx]: I think we can avoid custom css here

```suggestion
          component: "div",
          disabled: true,
          c: "text-light",
```

**Review by iethree — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/embedding/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx (hunk 1 above)
Comment (bpander) [reply frontend/src/metabase/embedding/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx]: If I remove floatRight and borderless, I think it looks pretty off:
| With | Without |
| --- | --- |
| with | without

I think we should keep the current alignment, but I'm less opinionated on how. I swapped out some of the global classes with mantine props in fdb6825d10. Possibly TMI, I'd started using flexbox, but float:right ended up being simpler. Happy to tweak it though.

File: frontend/src/metabase/ui/components/overlays/Menu/Menu.module.css (hunk 2 above)
Comment (bpander) [reply frontend/src/metabase/ui/components/overlays/Menu/Menu.module.css]: Seems legit. It works with some caveats:
* It's not very keyboard-navigable or screen-reader-friendly
* I changed `:disabled` to `[data-disabled="true"]` in our styles because the menu item is a div (because of the nested Enable button)
* Disabled menu items were `opacity: 0.6` so the button looked faded out. I added `opacity: 1` to our disabled styles overrides (which means it'll affect disabled menu items site-wide), but lemme know if I should limit the scope of that change to just this specific menu item.

Made that change in 6af97cd5c7

**Review by iethree — APPROVED** [review]
👍
