### PR TITLE
Remove the "Groups" heading from the invite popover

### LINKED ISSUE #65296: Heading for Groups when inviting a user is in a weird place
### Describe the bug

Image

### To Reproduce

1.  Go to Admin, People
2. Click Invite New User

### Expected behavior

I actually don't know, but this seems wrong

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-cloud-yearly",
    "version": {
      "date": "2025-10-30",
      "tag": "v1.57.0-beta",
      "hash": "2e9f645"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Minor but annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nemanjaglumac**
Resolves #65296 by removing the "Groups" heading from the popover altogether. [Slack context](https://metaboat.slack.com/archives/C01LQQ2UW03/p1766077669113999).

This PR also includes the commit from @thegeekybaniya from his PR #65923. That PR didn't resolve the issue at hand, but it had a good instinct to re-position the popover position. I'm also including it here because the CI cannot run for external contributors.

### Before
Note how the popover was jumping all over the place because of the weird position. Kudos to @thegeekybaniya for fixing that part.
Kapture 2025-12-18 at 22 33 19

### Now
Kapture 2025-12-18 at 22 28 50

### CODE REVIEW

**Review by iethree — APPROVED** [review]

**Review by perivamsi — APPROVED** [review]

**Review by mazameli — CHANGES_REQUESTED** [review]
I like this, but would it be possible to have a horizontal divider after the two "special" groups? I just want to subtly indicate visually that those two groups aren't like the others.

**Comment by thegeekybaniya** [comment]
yippee-cat

Thanks for the attribution, means a lot!

**Comment by nemanjaglumac** [comment]
@mazameli sure, here's the final version

Without additional groups
Kapture 2025-12-19 at 15 11 02

With additional groups
Kapture 2025-12-19 at 15 13 49

@iethree sorry to pull you in again, but the diff in https://github.com/metabase/metabase/pull/67222/commits/666b350f62ed09368736d588097f481d86e9431f ended up bigger than I anticipated due to the way code was originally structured. I'd argue that the final solution is cleaner and easier to read. But I'd need you to take a look at it again. 🙏

**Review by mazameli — APPROVED** [review]

File: frontend/src/metabase/admin/people/components/MembershipSelect/MembershipSelect.tsx [hunk 1]
```diff
@@ -87,13 +76,61 @@ export const MembershipSelect = ({
     onChange(groupId, membershipData);
   };
 
+  const renderGroup = (group: GroupInfo) => {
```
Comment (iethree) [inline frontend/src/metabase/admin/people/components/MembershipSelect/MembershipSelect.tsx:79]: nit / pet peeve. I really dislike these render functions. if you're writing a render function, 99% of the time you should just have a separate subcomponent that will better encapsulate component-specific logic, and make your code easier to understand. 

there are some cases where performance-intensive components can leverage memoization in these components to make them worthwhile, but those are pretty rare.
