### PR TITLE
Avoid error when user searches with no data perms

### LINKED ISSUE #16855: Search does not work for users without Data access
**Describe the bug**
Search does not work for users without Data access. Works in 39.x

**To Reproduce**
1. Admin > People > create a user "U1"
2. Admin > Permissions > revoke data access to all databases
3. Login as "U1" try using the search
image

<details><summary>Full stacktrace</summary>

```
2021-07-01 17:49:22,208 ERROR middleware.log :: GET /api/search 500 10.5 ms (2 DB calls) 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message
   "Input to add-table-db-id-clause does not match schema: \n\n\t   [(named (named (not (instance? clojure.lang.IPersistentMap nil)) \"Valid map\") query) nil]  \n\n",
   :data
   {:type :schema.core/error,
    :schema
    [{:schema (named clojure.lang.IPersistentMap "Valid map"), :optional? false, :name query}
     {:schema (maybe Int), :optional? false, :name id}],
    :value [nil nil],
    :error [(named (named (not (instance? clojure.lang.IPersistentMap nil)) "Valid map") query) nil]},
   :at [metabase.api.search$fn__74284$add_table_db_id_clause__74289 invoke "search.clj" 224]}],
 :trace
 [[metabase.api.search$fn__74284$add_table_db_id_clause__74289 invoke "search.clj" 224]
  [metabase.api.search$fn__74516$search_query_for_model__74509__74521$fn__74525 invoke "search.clj" 298]
  [metabase.api.search$fn__74516$search_query_for_model__74509__74521 invoke "search.clj" 294]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [metabase.api.search$full_search_query$iter__74597__74601$fn__74602$fn__74603 invoke "search.clj" 380]
  [metabase.api.search$full_search_query$iter__74597__74601$fn__74602 invoke "search.clj" 379]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$map$fn__5866 invoke "core.clj" 2746]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.LazySeq first "LazySeq.java" 73]
  [clojure.lang.RT first "RT.java" 692]
  [clojure.core$first__5384 invokeStatic "core.clj" 55]
  [clojure.string$join invokeStatic "string.clj" 180]
  [clojure.string$join invoke "string.clj" 180]
  [honeysql.format$fn__23663 invokeStatic "format.cljc" 695]
  [honeysql.format$fn__23663 invoke "format.cljc" 693]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [honeysql.format$_format_clause invokeStatic "format.cljc" 519]
  [honeysql.format$_format_clause invoke "format.cljc" 516]
  [honeysql.format$map__GT_sql$fn__23204$fn__23205 invoke "format.cljc" 366]
  [clojure.core$comp$fn__5807 invoke "core.clj" 2569]
  [clojure.core$map$fn__5866 invoke "core.clj" 2755]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.LazySeq first "LazySeq.java" 73]
  [clojure.lang.RT first "RT.java" 692]
  [clojure.core$first__5384 invokeStatic "core.clj" 55]
  [clojure.string$join invokeStatic "string.clj" 180]
  [clojure.string$join invoke "string.clj" 180]
  [honeysql.format$space_join invokeStatic "format.cljc" 17]
  [honeysql.format$space_join invoke "format.cljc" 16]
  [honeysql.format$map__GT_sql$fn__23204 invoke "format.cljc" 365]
  [honeysql.format$map__GT_sql invokeStatic "format.cljc" 363]
  [honeysql.format$map__GT_sql invoke "format.cljc" 361]
  [honeysql.format$fn__23243 invokeStatic "format.cljc" 441]
  [honeysql.format$fn__23243 invoke "format.cljc" 407]
  [honeysql.format$fn__23057$G__23052__23062 invoke "format.cljc" 134]
  [honeysql.format$seq__GT_sql invokeStatic "format.cljc" 387]
  [honeysql.format$seq__GT_sql invoke "format.cljc" 374]
  [honeysql.format$fn__23245 invokeStatic "format.cljc" 425]
  [honeysql.format$fn__23245 invoke "format.cljc" 407]
  [honeysql.format$fn__23057$G__23052__23062 invoke "format.cljc" 134]
  [clojure.core$map$fn__5866 invoke "core.clj" 2753]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.LazySeq first "LazySeq.java" 73]
  [clojure.lang.RT first "RT.java" 692]
  [clojure.core$first__5384 invokeStatic "core.clj" 55]
  [clojure.string$join invokeStatic "string.clj" 180]
  [clojure.string$join invoke "string.clj" 180]
  [honeysql.format$comma_join invokeStatic "format.cljc" 14]
  [honeysql.format$comma_join invoke "format.cljc" 13]
  [honeysql.format$fn__23300 invokeStatic "format.cljc" 541]
  [honeysql.format$fn__23300 invoke "format.cljc" 540]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [honeysql.format$_format_clause invokeStatic "format.cljc" 519]
  [honeysql.format$_format_clause invoke "format.cljc" 516]
  [honeysql.format$map__GT_sql$fn__23204$fn__23205 invoke "format.cljc" 366]
  [clojure.core$comp$fn__5807 invoke "core.clj" 2569]
  [clojure.core$map$fn__5866 invoke "core.clj" 2755]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.Cons next "Cons.java" 39]
  [clojure.lang.LazySeq next "LazySeq.java" 83]
  [clojure.lang.RT next "RT.java" 713]
  [clojure.core$next__5386 invokeStatic "core.clj" 64]
  [clojure.string$join invokeStatic "string.clj" 180]
  [clojure.string$join invoke "string.clj" 180]
  [honeysql.format$space_join invokeStatic "format.cljc" 17]
  [honeysql.format$space_join invoke "format.cljc" 16]
  [honeysql.format$map__GT_sql$fn__23204 invoke "format.cljc" 365]
  [honeysql.format$map__GT_sql invokeStatic "format.cljc" 363]
  [honeysql.format$map__GT_sql invoke "format.cljc" 361]
  [honeysql.format$fn__23243 invokeStatic "format.cljc" 441]
  [honeysql.format$fn__23243 invoke "format.cljc" 407]
  [honeysql.format$fn__23057$G__23052__23062 invoke "format.cljc" 134]
  [honeysql.format$format invokeStatic "format.cljc" 301]
  [honeysql.format$format doInvoke "format.cljc" 269]
  [clojure.lang.RestFn invoke "RestFn.java" 486]
  [toucan.db$honeysql__GT_sql$fn__28641 invoke "db.clj" 272]
  [toucan.db$honeysql__GT_sql invokeStatic "db.clj" 271]
  [toucan.db$honeysql__GT_sql invoke "db.clj" 263]
  [toucan.db$reducible_query invokeStatic "db.clj" 296]
  [toucan.db$reducible_query doInvoke "db.clj" 292]
  [clojure.lang.RestFn invoke "RestFn.java" 439]
  [metabase.api.search$fn__74619$search__74624$fn__74625 invoke "search.clj" 395]
  [metabase.api.search$fn__74619$search__74624 invoke "search.clj" 386]
  [metabase.api.search$fn__74687 invokeStatic "search.clj" 460]
  [metabase.api.search$fn__74687 invoke "search.clj" 444]
  [compojure.core$wrap_response$fn__1996 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1980 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1985 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 151]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 152]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__77063 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.api.routes$fn__77129$fn__77131 invoke "routes.clj" 70]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.server.routes$fn__79365$fn__79366 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 152]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 152]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 152]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.server.routes$fn__79353$fn__79355 invoke "routes.clj" 41]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77120 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__77117 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__79279$fn__79280$fn__79281 invoke "log.clj" 209]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__79279$fn__79280 invoke "log.clj" 201]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__79279 invoke "log.clj" 200]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__78898 invoke "browser_cookie.clj" 30]
  [metabase.server.middleware.security$add_security_headers$fn__57723 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__79043 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__79061 invoke "json.clj" 98]
  [metabase.server.middleware.offset_paging$handle_paging$fn__57745 invoke "offset_paging.clj" 45]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__79622 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__79638 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__36084 invoke "misc.clj" 58]
  [metabase.server.middleware.session$bind_current_user$fn__42979$fn__42980 invoke "session.clj" 257]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 238]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 230]
  [metabase.server.middleware.session$bind_current_user$fn__42979 invoke "session.clj" 256]
  [metabase.server.middleware.session$wrap_current_user_info$fn__42966 invoke "session.clj" 216]
  [metabase.server.middleware.session$wrap_session_id$fn__42952 invoke "session.clj" 162]
  [metabase.server.middleware.auth$wrap_api_key$fn__77071 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__79542 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__36067 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__36092 invoke "misc.clj" 75]
  [ring.middleware.gzip$wrap_gzip$fn__79584 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__36095 invoke "misc.clj" 92]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__79298 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__78842 invoke "server.clj" 71]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 556]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 905]
  [java.lang.Thread run "Thread.java" 829]],
 :cause
 "Input to add-table-db-id-clause does not match schema: \n\n\t   [(named (named (not (instance? clojure.lang.IPersistentMap nil)) \"Valid map\") query) nil]  \n\n",
 :data
 {:type :schema.core/error,
  :schema
  [{:schema (named clojure.lang.IPersistentMap "Valid map"), :optional? false, :name query}
   {:schema (maybe Int), :optional? false, :name id}],
  :value [nil nil],
  :error [(named (named (not (instance? clojure.lang.IPersistentMap nil)) "Valid map") query) nil]},
 :message
 "Input to add-table-db-id-clause does not match schema: \n\n\t   [(named (named (not (instance? clojure.lang.IPersistentMap nil)) \"Valid map\") query) nil]  \n\n",
 :value [nil nil],
 :error [(named (named (not (instance? clojure.lang.IPersistentMap nil)) "Valid map") query) nil]}
```

</details>

**Information about your Metabase Installation:**
Tested 0.40.0-rc1

Likely the same problem as #16617

### PR DESCRIPTION
**Pull request by tsmacdonald**
[Fixes #16855] 

Introduced in 40, so I opened it against `master`

### CODE REVIEW

File: test/metabase/api/search_test.clj [hunk 1]
```diff
@@ -503,6 +503,16 @@
                (binding [*search-request-results-database-id* db-id]
                  (search-request-data user :q "Round Table"))))))))
 
+(deftest all-users-no-data-perms-table-test
+  (testing (str "If the All Users group doesn't have perms to view a Table they sholdn't see it (#16855)")
```
Comment (dpsutton) [inline test/metabase/api/search_test.clj:507]: don't think you need the `str` here

**Review by dpsutton — APPROVED** [review]

File: test/metabase/api/search_test.clj (hunk 1 above)
Comment (tsmacdonald) [reply test/metabase/api/search_test.clj]: Good call, I totally copied it from the above (which has multiple strings concatenated together) and then edited away the other strings.
