### PR TITLE
[MLv2] Removing a final JOIN condition removes the whole join

### LINKED ISSUE #36690: [MLv2] [BE] removeClause throws "Cannot remove the final join condition" error
Given the following query ([screenshot](https://github.com/metabase/metabase/assets/6830683/469a5495-47ad-478c-9ccb-5394e23b78ef)), `removeClause` throws `Cannot remove the final join condition` error when trying to remove the breakout.

```tsx
Lib.removeClause(query, 0, Lib.breakouts(query, 0)[0])
```

It is expected that `removeClause` drops the entire join clause because it becomes invalid.

### How to reproduce 

1. `git checkout 36516-notebook-steps`
2. Run any of the following e2e tests:
    - `joins.cy.spec.js` (`should handle joins on different stages`)
    - `reproductions/17767-cannot-join-on-aggregation-with-implicit-joins.cy.spec.js`
    - `reproductions/18818-crash-when-joining-on-custom-column.cy.spec.js`

### Additional context

See [Slack](https://metaboat.slack.com/archives/C04CYTEL9N2/p1702378656823469)

### PR DESCRIPTION
**Pull request by bshepherdson**
This still throws an exception on trying to directly remove the final
JOIN condition. But if the condition is being removed because a field it
depends on is being removed (eg. a custom column, a breakout, a
previous stage aggregation) then the entire JOIN is also removed, in the
usual cascading fashion.

Fixes #36690.

### CODE REVIEW

**Comment by bshepherdson** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #37229** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37229?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/37229?utm_source=stack-comment).

File: dev/src/dev/fe_helpers.cljs [hunk 1]
```diff
@@ -13,3 +13,5 @@
 
 (defn current-query []
   (.-__MLv2_query js/window))
+
+
```
Comment (metamben) [inline dev/src/dev/fe_helpers.cljs:17]: Is this intended?

File: src/metabase/lib/remove_replace.cljc [hunk 2]
```diff
@@ -118,12 +119,24 @@
...
                                                       (set/subset? (set target-opts) (set %))))
                                        target-ref-id] [location clause]))))))
-                   (stage-paths query stage-number))]
-    (reduce
-     (fn [query [location target-clause]]
-       (remove-replace-location query stage-number unmodified-query-for-stage location target-clause #(lib.util/remove-clause %1 %2 %3 stage-number)))
-     query
-     to-remove)))
+                   (stage-paths query stage-number))
+        dead-joins (atom [])]
```
Comment (metamben) [inline src/metabase/lib/remove_replace.cljc:123]: `volatile!` would be enough.

**Review by metamben — CHANGES_REQUESTED** [review]
Don't we need a test checking the new behavior?

File: dev/src/dev/fe_helpers.cljs (hunk 1 above)
Comment (bshepherdson) [reply dev/src/dev/fe_helpers.cljs:17]: Ah, no it's not. I added a new helper that didn't pan out and didn't clean it up all the way.

**Review by metamben — APPROVED** [review]
👍
