### PR TITLE
Batch query_execution, audit_log and view_log truncations

### LINKED ISSUE #51432: Pruning query execution log can time out
### Describe the bug

Query execution table can get very large. We have a twice-daily job to remove old values. But this job can last longer than ten minutes and the job continues to run detached from Metabase. Also, the application can be very sluggish during this. The job runs in a transaction so it must be able to restore the deleted rows, but we never need to roll this back.

### To Reproduce

na

### Expected behavior

Possible fixes:

delete in batches:

```clojure
(let [batch-size 40000
      time-limit (t/minus (t/local-date-time) (t/months 6))]
  (t2/query {:with [[:ids-to-delete
                     {:select [:id]
                      :from [:query_execution]
                      :where [:< :started_at time-limit]
                      :limit batch-size}]]
             :delete-from [:query_execution :qe]
             :using [[:ids-to-delete :ids]]
             :where [:= :qe.id :ids.id]}))
[0]
```

Notes about the above: if it all runs in the same transaction then it's not super helpful since we would have the same sluggishness. We can also set a timer and loop over this query until this until we run out of rows or run out of time.

Perhaps more proper: partition the table. Need to understand the full mechanics of this in the app but undoubtedly we want to end up here.

### Logs

_No response_

### Information about your Metabase installation

```JSON
current
```

### Severity

general sluggishness especially at large size

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Resolves https://github.com/metabase/metabase/issues/51432

Runs truncation jobs of all audit-related tables in batches instead of a single query that can lock up the tables and slow down the rest of the application. (Particularly relevant for `query_execution` which can get very large, but shouldn't hurt to use this for all the jobs.)

Set the default batch size to 50000 but configurable by env var `MB_AUDIT_TABLE_TRUNCATION_BATCH_SIZE`.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#51490** <a href="https://app.graphite.dev/github/pr/metabase/metabase/51490?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/metabase/metabase/51490?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: src/metabase/task/truncate_audit_tables.clj [hunk 1]
```diff
@@ -69,23 +69,56 @@
...
-                              time-column
-                              [:<= (t/minus (t/offset-date-time) (t/days (audit-max-retention-days)))])]
-            (if (> rows-deleted 0)
-              (log/infof "%s cleanup successful, %d rows were deleted" table-name rows-deleted)
-              (log/infof "%s cleanup successful, no rows were deleted" table-name)))
-          (catch Throwable e
-            (log/errorf e "%s cleanup failed" table-name)))))))
+      (try
+        (log/infof "Cleaning up %s table" table-name)
+        (let [total-rows-deleted (volatile! 0)]
```
Comment (johnswanson) [inline src/metabase/task/truncate_audit_tables.clj:110]: minor, but I think the speedup from `volatile!` here is unlikely to make a big difference, right? Like with the default limit of 50k rows per batch, we'd have to have 50 million rows before we executed this loop 1000 times... and it's hard to imagine that this is going to make a big impact compared to the DB round trip. So it feels a bit like something like...

```
(loop [total-deleted 0]
 (let [batch-deleted (...)]
    (if (= batch-deleted (batch-size))
      (recur (+ total-deleted batch-deleted))
      (if-not (= total-deleted 0)
        ...
```

might be clearer and more idiomatic? I'm not super tied to this though, the code you've written is pretty clear.

**Review by johnswanson — APPROVED** [review]

File: src/metabase/task/truncate_audit_tables.clj (hunk 1 above)
Comment (noahmoss) [reply src/metabase/task/truncate_audit_tables.clj:110]: That's fair, I'll change it
