### PR TITLE
Data migration to fix clickhouse upload dbs with missing schema

### LINKED ISSUE #69667: Models from csv uploads to Metabase Cloud Storage disappear
### Describe the bug

On Metabase Cloud v1.58.5 with a Cloud storage add on, if you upload a csv to the Cloud storage, it will create a model for you in the collection where you uploaded the csv. You can build questions based on this model. But, after a time period of 1 to 24 hours, the questions and model will disappear from the instance. I did change some column names in the csv model, but I'm not sure if that would have affected things. 

### To Reproduce

1. Add a csv upload to Metabase Cloud Storage
2. Build questions based on that model (not sure if changing model metadata affects things) 
3. Wait 1-24 hours 
4. Attempt to access questions 

### Expected behavior

The csv model should persist 

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2026-02-04",
      "tag": "v1.58.5",
      "hash": "109161b"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Severe

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/69667

### Description

https://metaboat.slack.com/archives/C052ZBWRG3W/p1771443819177789

https://metaboat.slack.com/archives/C010ZSXQY87/p1772570823344839

Uploads to a clickhouse db would create a model that would disappear after sync. This was happening because the `uploads_schema_name` field of the db was set to null. How does this field get set to null? It can happen when the user either disables or switches their upload db, and then sets it back to the clickhouse one. There was a fix for this in https://github.com/metabase/metabase/pull/68517, but we also need a data migration to fix existing cases of this. That's what this PR does. 

The problem with a null `uploads_schema_name` is that when we create an upload, we create a `metabase_table` with the `schema` set to the `uploads_schema_name` value. So it get's created with a unique `(db_id, name, schema)` key of `(2, "uploads_table", null)`. Then we associate this table with a model. When this upload db is synced, the driver reports this table with the schema that the db was actually created in (this is the `dbname` field from the upload db details). So we create a `metabase_table`with the unique key `(2, "uploads_table", "db_foo")`. Since the driver doesn't report this table with a null schema, the original `metabase_table` with unique key `(2, "uploads_table", null)` is set as inactive. Then when you try to access the model you receive an error that the table associated with it is inactive. 

The fix in this PR is a data migration. There are 3 steps. 

1. Set the `uploads_schema_name`
We are setting this to the upload db details field `dbname`, as this is what would be used when no schema is provided. 

2. Retire the active tables created by the sync
We set the active tables that were created by the sync to be inactive. We also rename these tables to avoid conflicts with the unique key constraint. We could just delete these tables, but out of caution I've just renamed them here. 

3. Revive the original upload tables that are inactive
Set the schema for the original upload tables and mark them as active.

### How to verify

1. To test locally, set the `schemas` property of the clickhouse driver to be false, and set the `uploads` property to be true. 
2. Create a clickhouse database
3. Configure it as the upload db
4. Do an upload and sync, you should still be able to access the model
5. Disable and then re-enable uploads
6. Do another upload and sync. You can access the model from 4. but not the new model.
7. Run the migration
8. You should be able to access both models

### Demo

https://www.loom.com/share/827036dad33f49e28b4ef2bbecf9894f

https://www.loom.com/share/b76a580fc95f4324bd37e09072991eac

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: fix_clickhouse_csv_upload_dbs_69667.sql
Comment (bshepherdson) [inline fix_clickhouse_csv_upload_dbs_69667.sql:1]: This file is at the root. I'm not sure if it was an accidentally included dev file or if it's supposed to be in the PR but is located badly.

File: src/metabase/app_db/custom_migrations.clj [hunk 1]
```diff
@@ -1854,3 +1854,58 @@
...
+                                         db-name (:dbname decrypted-details)]
+                                     (when db-name
+                                       (t2/query {:update :metabase_database
+                                                  :set    {:uploads_schema_name db-name}
+                                                  :where  [:= :id id]}))))]
+    (if-not (= 1 (count clickhouse-upload-db))
+      (log/warn "FixClickHouseUploadDBSchemaNames: expected 1 ClickHouse upload database with missing uploads_schema_name, found" (count clickhouse-upload-db))
+      (do
+        (run! set-uploads-schema-name! clickhouse-upload-db)
+        (let [active-non-upload-tables (t2/query {:select [:mt.id :mt.name]
```
Comment (bshepherdson) [inline src/metabase/app_db/custom_migrations.clj]: Lets get some commentary and explanations in this file. These migrations are very opaque when we've forgotten all about the issue, and `git blame` back to the PR is clumsy.

File: src/metabase/app_db/custom_migrations.clj [hunk 2]
```diff
@@ -1854,3 +1854,58 @@
...
+                                                  :from [[:metabase_table :mt]]
+                                                  :join [[:metabase_database :md] [:= :mt.db_id :md.id]]
+                                                  :where [:and
+                                                          [:= :md.engine "clickhouse"]
+                                                          [:= :md.uploads_enabled true]
+                                                          [:not= :md.uploads_schema_name nil]
+                                                          [:= :mt.schema :md.uploads_schema_name]
+                                                          [:= :mt.active true]
+                                                          [:= :mt.is_upload false]]})
```
Comment (bshepherdson) [inline src/metabase/app_db/custom_migrations.clj]: Are we certain that the uploads schema will always contain only uploads? ISTM that I could be targeting a schema that contains other tables as my upload target schema.

I wonder about doing this the other way: for all uploaded but inactive tables where `schema IS NULL`, look for a corresponding active, non-upload table with the schema set and the same name. Then it's only deactivating exactly those tables which are duplicates of the uploads, and there's no collateral damage to tables that just happen to share the schema.

Comment (bshepherdson) [reply src/metabase/app_db/custom_migrations.clj]: Ah, I see that there's a count check below, so perhaps that's okay.

File: src/metabase/app_db/custom_migrations.clj [hunk 3]
```diff
@@ -1854,3 +1854,58 @@
...
+                                     (t2/query {:update :metabase_table
+                                                :set {:active true
+                                                      :schema uploads_schema_name}
+                                                :where [:= :id id]}))]
+          (if (or (not= (count active-non-upload-tables) (count inactive-upload-tables))
+                  (= 0 (count active-non-upload-tables)))
+            (log/warn "FixClickHouseUploadDBSchemaNames: expected the same number of active non-upload tables and inactive upload tables, found" (count active-non-upload-tables) "active non-upload tables and" (count inactive-upload-tables) "inactive upload tables")
+            (do
+              (run! retire-non-upload-table! active-non-upload-tables)
+              (run! revive-upload-table! inactive-upload-tables))))))))
```
Comment (bshepherdson) [inline src/metabase/app_db/custom_migrations.clj]: Just to double check: the whole migration gets run in a transaction, right?

File: test/metabase/app_db/custom_migrations_test.clj [hunk 4]
```diff
@@ -2775,3 +2775,46 @@
...
+              uploaded-0 (insert-table! db-id "uploads_test_table_0" "db_foo" true  true "Test Table 0")
+              uploaded-1 (insert-table! db-id "uploads_test_table_1" nil      false true "Test Table 1")
+              uploaded-2 (insert-table! db-id "uploads_test_table_2" nil      false true "Test Table 2")
+              synced-1   (insert-table! db-id "uploads_test_table_1" "db_foo" true  false "Uploads Test Table 1")
+              synced-2   (insert-table! db-id "uploads_test_table_2" "db_foo" true  false "Uploads Test Table 2")
+              assert-table-state (fn [table-id name schema active is-upload]
+                                   (is (= {:name name
+                                           :schema schema
+                                           :active active
+                                           :is_upload is-upload} (t2/select-one [:metabase_table :name :schema :active :is_upload] :id table-id))))]
```
Comment (bshepherdson) [inline test/metabase/app_db/custom_migrations_test.clj]: This looks like it's reinventing `clojure.test/are`.

File: test/metabase/app_db/custom_migrations_test.clj [hunk 5]
```diff
@@ -2775,3 +2775,46 @@
...
+          (migrate!)
+          (is (= "db_foo" (:uploads_schema_name (t2/select-one :metabase_database :id db-id))))
+          (assert-table-state uploaded-0 "uploads_test_table_0" "db_foo" true true)
```
Comment (bshepherdson) [inline test/metabase/app_db/custom_migrations_test.clj]: Lets get some comments on here likewise - what cases are being tested here?

File: test/metabase/app_db/custom_migrations_test.clj [hunk 6]
```diff
@@ -2775,3 +2775,46 @@
...
+          (assert-table-state uploaded-1 "uploads_test_table_1" "db_foo" true true)
+          (assert-table-state uploaded-2 "uploads_test_table_2" "db_foo" true true)
+          (assert-table-state synced-1 "uploads_test_table_1_retired_69667" "db_foo" false false)
+          (assert-table-state synced-2 "uploads_test_table_2_retired_69667" "db_foo" false false))))))
```
Comment (bshepherdson) [inline test/metabase/app_db/custom_migrations_test.clj]: I'd like to see a test that checks what happens when there's a "bystander" table which is in the uploads schema but isn't actually uploaded. If it does nothing with a warning, then let's check that. We don't wan to be renaming and breaking tables for anyone just because they have uploads turned on.

File: test_clickhouse_csv_upload_dbs_69667.sql
Comment (bshepherdson) [inline test_clickhouse_csv_upload_dbs_69667.sql:1]: Another accidental inclusion?

**Review by bshepherdson — CHANGES_REQUESTED** [review]

File: src/metabase/app_db/custom_migrations.clj (hunk 3 above)
Comment (rileythomp) [reply src/metabase/app_db/custom_migrations.clj]: Yeah `define-migration` calls `define-reversible-migration` which calls `t2/with-transaction`

File: src/metabase/app_db/custom_migrations.clj (hunk 2 above)
Comment (rileythomp) [reply src/metabase/app_db/custom_migrations.clj]: Yeah the count was an attempt to mitigate this but I think your approach is cleaner

File: fix_clickhouse_csv_upload_dbs_69667.sql
Comment (rileythomp) [reply fix_clickhouse_csv_upload_dbs_69667.sql:1]: My bad pushed these to share with Dennis and Arkadi and forgot to remove

File: src/metabase/app_db/custom_migrations.clj (hunk 2 above)
Comment (rileythomp) [reply src/metabase/app_db/custom_migrations.clj]: https://github.com/metabase/metabase/pull/70363/commits/349a5f3083680cc484412eaa0fd9331a33c241ec

I also updated the logic to not require that the DB `uploads_schema_name` is null. This is to handle cases where someone has uploads in a bad state, but then fixed their uploads DB with a schema after 58.5.

File: test/metabase/app_db/custom_migrations_test.clj (hunk 6 above)
Comment (rileythomp) [reply test/metabase/app_db/custom_migrations_test.clj]: Added a test case for this in https://github.com/metabase/metabase/pull/70363/commits/3ab8d69bea605b77036ea77ef71b722442494ae2

Shown with local testing in the second loom

File: test/metabase/app_db/custom_migrations_test.clj (hunk 5 above)
Comment (rileythomp) [reply test/metabase/app_db/custom_migrations_test.clj]: Added some comments in https://github.com/metabase/metabase/pull/70363/commits/3ab8d69bea605b77036ea77ef71b722442494ae2, lmk if they are sufficient

File: src/metabase/app_db/custom_migrations.clj (hunk 1 above)
Comment (rileythomp) [reply src/metabase/app_db/custom_migrations.clj]: Added in [e518cc6](https://github.com/metabase/metabase/pull/70363/commits/e518cc6a0a95743f4c89184a8f278143c06c2a57), lmk if this is clear

File: src/metabase/app_db/custom_migrations.clj [hunk 7]
```diff
@@ -1854,3 +1854,76 @@
...
+                                   (let [decrypted-details (encrypted-json-out details)
+                                         db-name (:dbname decrypted-details)]
+                                     (when (and db-name (not uploads_schema_name))
+                                       (t2/query {:update :metabase_database
+                                                  :set    {:uploads_schema_name db-name}
+                                                  :where  [:= :id id]}))))]
+    (if (< 1 (count clickhouse-upload-db))
+      (log/warn "FixClickHouseUploadDBSchemaNames: expected at most 1 ClickHouse upload database, found" (count clickhouse-upload-db))
+      (do
+        (run! set-uploads-schema-name! clickhouse-upload-db)
```
Comment (bshepherdson) [inline src/metabase/app_db/custom_migrations.clj:1900]: Is this safe if there are 0? Might be better to do `(case (count clickhouse-upload-db) 1 ... 0 ...  #_default ...)`.

**Review by bshepherdson — APPROVED** [review]

File: src/metabase/app_db/custom_migrations.clj (hunk 7 above)
Comment (rileythomp) [reply src/metabase/app_db/custom_migrations.clj:1900]: Yeah it should be, `run!` just reduces over the query results
