### PR TITLE
Make chain filters viewable when collection permissions allow it

### LINKED ISSUE #24029: Users with "No self-service" permissions on tables can't use cascading filters
**Describe the bug**
When configuring cascading filters with 2 categorical fields, if a user doesn't have self-service permissions the cascading will fail and the user will have a search box only. The crazy thing is: if you click on the filters separately, you'll see the values

**Logs**
You'll get "You don't have permissions to do that." on the backend and a 403 on the FE

**To Reproduce**
1) New->question->people. Save this question and add it to a dashboard
2) on the dashboard add 2 filters: Location connected to State column, and category, connected to Source in the card. Link them, doesn't matter which. Save it
3) go to settings->admin->people-> create a new user
4) go to settings->admin->permissions. Remove from the all users the permission to do self service on the table "People"
5) Authenticate as the newly created user- >Go to the dashboard ->Click on the first filter and see the options // Click on the second filter and also see the options
6) Click on the source filter (the one that is not linked) and select any option. Then click on the second filter, you'll get a search box and the network tab will show 403

**Expected behavior**
If you have permissions to get the filter values without the cascading, you should have the permissions to do the cascading as well, even though you have "no self service"

**Screenshots**
Dashboard with linked filters seen as an admin
image
image

Dashboard with linked filters seen as a user who doesn't have self service permissions on the people table
Now you see
image
image

Now you don't
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop-OS 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.43.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
P1'ish?

**Additional context**
Maybe a cousin of https://github.com/metabase/metabase/issues/12654?

### PR DESCRIPTION
**Pull request by escherize**
Fixes #24029 and #13537

## Example

When selecting filters, we do this smart thing on a dashboard: when you select filter values to narrow down results we constrain the possible selections on the next filter dropdown you click.

So if you had a table resturaunts with the relevant structure:

| *kind* | *price* | ... |
| --- | --- | --- |
| pizza | `low` | |
| bbq   | `high` | |
| steak | `high` | |
| steak | `medium` | |

with 2 filters: one for *kind* and one for *price*. Where the *price* filter is linked to the *kind* filter. 

Next you select steak for the *kind* filter. The *price* filter's dropdown should only show `high` and `medium`. (e.g. be constrained on `*kind* == steak`).

This behavior fails when the user does not have the data permission for self-service. Access to the chained filter values is supposed to be determined by:

| can see chain filters? | data perms | collection perms for dashboard
| -------------- | --------------- | ------------------------------
| yes            | Unrestricted    | Curate
| yes            | No self-service | Curate
| yes            | Unrestricted    | View
| yes            | No self-service | View
| n/a            | Unrestricted    | No access
| n/a            | No self-service | No access

### CODE REVIEW

File: src/metabase/query_processor/middleware/permissions.clj [hunk 1]
```diff
@@ -89,16 +90,28 @@
   (doseq [{query :dataset_query} (qp.u.tag-referenced-cards/tags-referenced-cards outer-query)]
     (check-query-permissions* query)))
 
-(s/defn ^:private check-query-permissions*
+(def ^:dynamic *user-can-read-dashboard*
+  "Used to allow users looking at a dashboard to view chained filters."false)
```
Comment (qnkhuat) [inline src/metabase/query_processor/middleware/permissions.clj:94]:
```suggestion
  "Used to allow users looking at a dashboard to view chained filters."
  false)
```

File: src/metabase/query_processor/middleware/permissions.clj [hunk 2]
```diff
@@ -89,16 +90,28 @@
...
     (log/tracef "Checking query permissions. Current user perms set = %s" (pr-str @*current-user-permissions-set*))
-    (if *card-id*
+    (cond
+      *card-id*
       (do
         (check-card-read-perms *card-id*)
         (when-not (has-data-perms? (required-perms outer-query))
           (check-block-permissions outer-query)))
+
+      *user-can-read-dashboard*
```
Comment (qnkhuat) [inline src/metabase/query_processor/middleware/permissions.clj:108]: I'd appreciate a comment explaining the context we use this var and why we're returning `nil` here.

File: test/metabase/api/dashboard_test.clj [hunk 3]
```diff
@@ -1983,19 +2007,43 @@
...
+    (testing "missing data perms should not affect perms for the Fields in question when users have collection access"
+      (mt/with-temp-copy-of-db
+        (with-chain-filter-fixtures [{:keys [dashboard param-keys]}]
+          (perms/revoke-data-perms! (perms-group/all-users) (mt/id))
+          (is (= {:values ["African" "American" "Artisan"] :has_more_values false}
+                 (->> (chain-filter-values-url (:id dashboard) (:category-name param-keys))
+                      (mt/user-http-request :rasta :get 200)
+                      (chain-filter-test/take-n-values 3)))))))
+
+    ;; TODO: how do you test blocked when non ee without breaking CI?
```
Comment (qnkhuat) [inline test/metabase/api/dashboard_test.clj:2038]: I think there 2 ways of doing this:
1. move this test to ee ns (maybe block perms tests, or API dashboard tests ?)
2. wrap this with a `when-not config/ee-available?`

File: test/metabase/api/dashboard_test.clj [hunk 4]
```diff
@@ -1941,6 +1944,27 @@
...
+              (is
+               (=
+                {:values ["African" "American" "Artisan" "Asian"] :has_more_values false}
+                (chain-filter-test/take-n-values 4 (mt/user-http-request :rasta :get 200 url)))))))))
+    (let [url (chain-filter-values-url dashboard (:category-name param-keys) (:price param-keys) 4)]
+      (testing (str "\nGET /api/" url "\n")
+        (testing "\nShow me names of categories that have expensive venues (price = 4), while I lack permisisons."
+          (with-redefs [chain-filter/use-cached-field-values? (constantly false)]
+            (binding [qp.perms/*card-id* nil]
+              (is
```
Comment (qnkhuat) [inline test/metabase/api/dashboard_test.clj:1963]: the new line here is a bit weird?

File: test/metabase/api/dashboard_test.clj [hunk 5]
```diff
@@ -1983,19 +2007,43 @@
...
     (testing "should check perms for the Fields in question"
       (mt/with-temp-copy-of-db
         (with-chain-filter-fixtures [{:keys [dashboard param-keys]}]
           (perms/revoke-data-perms! (perms-group/all-users) (mt/id))
+
           ;; HACK: we currently 403 on chain-filter calls that require running a MBQL
           ;; but 200 on calls that we could just use the cache.
           ;; It's not ideal and we definitely need to have a consistent behavior
           (with-redefs [field-values/field-should-have-field-values? (fn [_] false)]
+            (is (= {:values ["African" "American" "Artisan"]
```
Comment (qnkhuat) [inline test/metabase/api/dashboard_test.clj:2023]: Could you explain this change here? I know the current behavior is questionable but I'd like to know the rationale behind changing it now.

File: src/metabase/api/dashboard.clj [hunk 6]
```diff
@@ -716,25 +719,15 @@
...
-    (chain-filter 62 \"ee876336\" {})
-    ;; -> {:values          (\"African\" \"American\" \"Artisan\" ...)
-           :has_more_values false}
-
-    ;; show me categories that have expensive restaurants
-    (chain-filter 62 \"ee876336\" {\"6f10a41f\" 4})
-    ;; -> {:values          (\"Japanese\" \"Steakhouse\")
-           :has_more_values false}"
+(mu/defn chain-filter
+  "C H A I N filters!"
```
Comment (qnkhuat) [inline src/metabase/api/dashboard.clj:723]: The existing docstring has examples of how to use this and I think it's quite nice. Any reasons why you removed it?

**Review by qnkhuat — COMMENTED** [review]
Do we have any ticket/product asking for this change?
I'd love to know the motivation for this PR.

**Comment by noahmoss** [comment]
@qnkhuat https://github.com/metabase/metabase/issues/26874 is the associated issue

File: src/metabase/api/dashboard.clj (hunk 6 above)
Comment (escherize) [reply src/metabase/api/dashboard.clj:723]: Yeah, the docstring is actually describing another `chain-filter` function, and doesn't work with this function. I'll move it to where it belongs, tho.

File: test/metabase/api/dashboard_test.clj (hunk 5 above)
Comment (escherize) [reply test/metabase/api/dashboard_test.clj:2023]: Sure. This PR is adding the ability for users with _non-block data permissions_ to be able to view chain filter values for a dashboard that they have access to see. In this case `:rasta` can see the dashboard, therefore `:rasta` should see the chain filter values.

File: src/metabase/api/dashboard.clj (hunk 6 above)
Comment (escherize) [reply src/metabase/api/dashboard.clj:723]: Looking at the args you can see that this function expects a map first, not an integer, as in the docstrings.

Comment (noahmoss) [reply src/metabase/api/dashboard.clj:723]: I think it'd still be worth having _some_ docstring for this function as well, at least with a description of the behavior if not also an example

File: src/metabase/public_settings/premium_features.clj [hunk 7]
```diff
@@ -193,7 +193,7 @@
                        (log/debug e (trs "Error validating token")))
                      ;; log every five minutes
                      :ttl/threshold (* 1000 60 5))]
-  (schema/defn ^:private token-features :- #{su/NonBlankString}
+  (schema/defn token-features :- #{su/NonBlankString}
```
Comment (noahmoss) [inline src/metabase/public_settings/premium_features.clj:196]: why'd this need to be changed?

File: src/metabase/api/dashboard.clj [hunk 8]
```diff
@@ -791,7 +784,9 @@
     GET /api/dashboard/1/params/abc/values?def=100"
   [id param-key :as {:keys [query-params]}]
   (let [dashboard (api/read-check Dashboard id)]
-    (param-values dashboard param-key query-params)))
+    ;; If a user can read the dashboard, then they can lookup the chain-filter. This also works with sandboxing.
+    (binding [qp.perms/*user-can-read-dashboard* true]
```
Comment (noahmoss) [inline src/metabase/api/dashboard.clj:788]: Maybe it'd make sense to move the read check + binding into `param-values` so that it's shared by both endpoints automatically?

File: src/metabase/query_processor/middleware/permissions.clj [hunk 9]
```diff
@@ -89,16 +90,29 @@
...
-    (if *card-id*
+    (cond
+      *card-id*
       (do
         (check-card-read-perms *card-id*)
         (when-not (has-data-perms? (required-perms outer-query))
           (check-block-permissions outer-query)))
+
+      ;; set iff the user should see this when able to view a dashboard and the user can view said dashboard.
+      ;; the motivating use here is chain-filters.
```
Comment (noahmoss) [inline src/metabase/query_processor/middleware/permissions.clj:110]: nit: this wording was a bit hard for me to parse; took a stab at making it clearer
```suggestion
      ;; set when querying for field values of dashboard filters, which only require 
      ;; collection perms for the dashboard and not ad-hoc query perms
```

File: src/metabase/query_processor/middleware/permissions.clj [hunk 10]
```diff
@@ -89,16 +90,29 @@
   (doseq [{query :dataset_query} (qp.u.tag-referenced-cards/tags-referenced-cards outer-query)]
     (check-query-permissions* query)))
 
-(s/defn ^:private check-query-permissions*
+(def ^:dynamic *user-can-read-dashboard*
```
Comment (noahmoss) [inline src/metabase/query_processor/middleware/permissions.clj:93]: Maybe this could be named something like `*param-values-query*` to make it very specific what the use case of this var is?

File: src/metabase/query_processor/middleware/permissions.clj [hunk 11]
```diff
@@ -89,16 +90,29 @@
...
+  "Used to allow users looking at a dashboard to view chained filters."
```
Comment (noahmoss) [inline src/metabase/query_processor/middleware/permissions.clj:94]: This isn't actually specific to chain filters right? i.e. all field value lookups go through those endpoints and thus have this binding set?

File: src/metabase/api/dashboard.clj [hunk 12]
```diff
@@ -791,7 +784,9 @@
     GET /api/dashboard/1/params/abc/values?def=100"
   [id param-key :as {:keys [query-params]}]
   (let [dashboard (api/read-check Dashboard id)]
-    (param-values dashboard param-key query-params)))
+    ;; If a user can read the dashboard, then they can lookup the chain-filter. This also works with sandboxing.
```
Comment (noahmoss) [inline src/metabase/api/dashboard.clj:787]: nit: technically these endpoints are used for all filters, not just chain filters, I believe

File: test/metabase/api/dashboard_test.clj [hunk 13]
```diff
@@ -1983,19 +2004,33 @@
...
+                      (chain-filter-test/take-n-values 3)))))))
+
     (testing "should check perms for the Fields in question"
       (mt/with-temp-copy-of-db
         (with-chain-filter-fixtures [{:keys [dashboard param-keys]}]
           (perms/revoke-data-perms! (perms-group/all-users) (mt/id))
+
           ;; HACK: we currently 403 on chain-filter calls that require running a MBQL
           ;; but 200 on calls that we could just use the cache.
           ;; It's not ideal and we definitely need to have a consistent behavior
```
Comment (noahmoss) [inline test/metabase/api/dashboard_test.clj:2018]: This comment is out of date now right?

**Review by noahmoss — APPROVED** [review]
👍 I think I've done enough to convince myself that the logic checks out. Comments are mostly cosmetic.

File: test/metabase/api/dashboard_test.clj (hunk 13 above)
Comment (escherize) [reply test/metabase/api/dashboard_test.clj:2018]: I think it's still correct because this piece only affects queries that hit the qp, not cached ones.

File: src/metabase/api/dashboard.clj (hunk 8 above)
Comment (escherize) [reply src/metabase/api/dashboard.clj]: Actually, after making the change and looking at it, `param-values` is called from more places than just those 2. That's probably why I originally wrapped the bindings there.

File: src/metabase/api/dashboard.clj (hunk 6 above)
Comment (escherize) [reply src/metabase/api/dashboard.clj:723]: Looking through the git history, this docstring has been wrong since it's inception. I'll add something that's more correct.

Remember it's defined via mu/defn, so we get the arg info in the docstring too:

```
metabase.api.dashboard/chain-filter
 [dashboard param-key constraint-param-key->value]
 [dashboard param-key constraint-param-key->value query]
  Inputs: ([dashboard param-key constraint-param-key->value]
           [dashboard :- ms/Map param-key :- ms/NonBlankString constraint-param-key->value :- ms/Map query :- [:maybe ms/NonBlankString]])
  Return: :any
          

  C H A I N filters!

  Used to query for values that populate chained filter dropdowns and text search boxes.
  ```

File: src/metabase/public_settings/premium_features.clj (hunk 7 above)
Comment (escherize) [reply src/metabase/public_settings/premium_features.clj:196]: It shouldn't be
