### PR TITLE
do not allow to render empty SaveQuestionModal content

### LINKED ISSUE #45416: Weird behavior after saving questions in v1.50.11
### Describe the bug

Bug first seen in v1.50.11

After saving a question a new dialogue pops up: "Save new question". It disappears after a few seconds and the question is saved as expected. This happens when you start from a saved question and either replace it or create a new question.
The behavior seems to be related to the query_metadata request. 

See screen recording below for an example

### To Reproduce

1. Upgrade to v.1.50.11
2. Go to a saved question
3. Edit something in this question
4. Save question, either by overwriting the old one or creating a new question.
5. See behavior

### Expected behavior

The second dialogue should never show.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "nb-NO",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "6.1.85+",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.19"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-07-09",
      "tag": "v1.50.11",
      "hash": "e08c1fb"
    },
    "settings": {
      "report-timezone": "Europe/Oslo"
    }
  }
}
```

### Severity

Annoying to any user creating questions

### Additional context

https://github.com/metabase/metabase/assets/55921651/a3da8813-bcea-4607-8784-a89877772f8c

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/45416

### Description

Describe the overall approach and the problem being solved.

### How to verify

- open existing question
- change it in the editor
- try to save to see a modal which suggests replacing the question
- click save and notice that modal's content doesn't disappear before modal is closed

### Demo

https://github.com/user-attachments/assets/dd94a3c4-8583-4999-b049-1fc0c110b99e

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

test was failing initially
Screenshot 2024-07-12 at 16 34 07

### CODE REVIEW

File: frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx [hunk 1]
```diff
@@ -217,7 +217,12 @@ export const SaveQuestionModal = ({
     [originalQuestion, handleOverwrite, handleCreate],
   );
 
-  const isSavedQuestionChanged = useSelector(getIsSavedQuestionChanged);
+  // we care only about the very first result as question can be changed before
+  // the modal is closed
+  const isSavedQuestionChanged = useSelector(
+    getIsSavedQuestionChanged,
+    () => true,
```
Comment (nemanjaglumac) [inline frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx:224]: I didn't even know about this pattern until today.
As I'm reading about it, it seems that this will always re-render and I think I found that it's considered a bad practice in one place.

I have no horse in the race, and no opinion given that I'm just learning about it but I was wondering if `useRef` would be a better choice here?

I experimented with it locally and it does the work.

**Review by nemanjaglumac — COMMENTED** [review]
We need to be explicit here and change `showSaveType` to `values.saveType === "overwrite"`
https://github.com/metabase/metabase/pull/45476/files#diff-bf0d55759a0bf8dbdafe017e46281730dad82e4dd028fd16011298f312589d0bR262

**Comment by uladzimirdev** [comment]
> We need to be explicit here and change `showSaveType` to `values.saveType === "overwrite"`

we can't as there is a case (and a test) when we need to show both "new question" content and radio buttons to switch between "override" and "create"

File: frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx:224]: no matter, will you choose useRef, useMemo or the variable outside component or this pattern, it's a way to get the very first value from selector

Comment (ranquild) [reply frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx:224]: nit: Maybe `const [isSavedQuestionInitiallyChanged] = useState(isSavedQuestionChanged)` to make it more obvious.

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx]: @nemanjaglumac it's a widely used pattern, redux needs to know when to trigger component render - so redux uses the second argument passed a comparator function - it compares prev and current result and if it's changed - render
