### PR TITLE
Use scrollable body instead of sticky footer in DB forms

### LINKED ISSUE #60319: Input not scrolled into view when tabbing into it
### Describe the bug

https://github.com/user-attachments/assets/492647ae-a272-4dfa-9d19-02f8ab23364a

### To Reproduce

1. Be on not super-tall viewport (e.g. 840px)
2. Admin > Databases > Add database
3. Focus first input
4. Keep hitting <kbd>Tab</kbd> until you focus an input which needs scrolling to
5. The out-of-view input gets focused but it does not get scrolled into (due to sticky footer)

### Information about your Metabase installation

master, 1169f3f04307e9de8b199de5add98c3b52e0fdac

### Severity

P3

### PR DESCRIPTION
**Pull request by iethree**
closes #60319

Closes UXW-322

### Description

Having a sticky footer allows you to tab to inputs that are behind the footer. 😢  This changes the layout to have a scrollable box for the form body.

✅  Database Modal

https://github.com/user-attachments/assets/3e8f889a-d66e-45f4-a1cd-1ef043af0454

✅  Setup form

CleanShot 2025-08-21 at 14 46 59

### CODE REVIEW

File: frontend/src/metabase/databases/components/DatabaseForm/DatabaseForm.tsx [hunk 1]
```diff
@@ -249,11 +256,9 @@ const DatabaseFormFooter = ({
 
   const hasSampleDatabase = useSetting("has-sample-database?");
 
-  const className = "database-form-footer";
-
   if (isAdvanced) {
     return (
-      <FormFooter data-testid="form-footer" className={className}>
+      <FormFooter data-testid="form-footer" px="xl">
```
Comment (iethree) [inline frontend/src/metabase/databases/components/DatabaseForm/DatabaseForm.tsx:261]: we need different padding because the footer in the modal needs padding where the footer in the setup wizard doesn't

**Review by alxnddr — APPROVED** [review]

**Comment by chodorowicz** [comment]
Good stuff! 👏  
I wonder if using container queries (using `cqh` for `max-height`) would work here too.
