### PR TITLE
Fix whitelabeled colors aren't respected in x-rays

### LINKED ISSUE #22476: X-ray charts don't seem to respect whitelabel colors
**Describe the bug**
X-ray charts don't seem to respect white label colors.

**To Reproduce**
1. Admin > Settings > Whitelabel
image
2. Browse data > Sample > click X-rays for Reviews table
image

**Information about your Metabase Installation:**
Tested 1.34.4 thru 1.42.4

**Additional context**
Colors are hardcoded:
https://github.com/metabase/metabase/blob/89382bae965cb1340129e4d6c57ff7d491c692bd/src/metabase/automagic_dashboards/populate.clj#L46-L48

Previously EE139 https://github.com/metabase/metabase-enterprise/issues/139

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes https://github.com/metabase/metabase/issues/22476

## Colors setting
image

## Before the fix
localhost_3000_auto_dashboard_table_1 (2)

## After the fix
localhost_3000_auto_dashboard_table_1 (1)

I tried fixing this on FE as I found `graph.colors` beling labeled legacy so I assumed it could be removed.
https://github.com/metabase/metabase/blob/bceca3b31e90e6ab5d23ed4937b439e466baefbd/frontend/src/metabase/visualizations/lib/settings/series.js#L164-L171
 Turns out that if I remove that all the x-rays color would be the same. But there's a logic in BE that will try to have each card have different colors if I'm not mistaken.
https://github.com/metabase/metabase/blob/1b33e3e226b0b26b1751f834470ea21073949dd8/src/metabase/automagic_dashboards/populate.clj#L82-L92

### CODE REVIEW

File: src/metabase/automagic_dashboards/populate.clj [hunk 1]
```diff
@@ -43,9 +44,22 @@
...
+         (map vector whitelabeled-color-names)
+         (map (fn [[whitelabeled-color-name default-color]]
+                (whitelabeled-color-name (public-settings/application-colors) default-color)))
+         (into []))))
+
+(defn colors
   "Colors used for coloring charts and collections."
-  ["#509EE3" "#9CC177" "#A989C5" "#EF8C8C" "#f9d45c" "#F1B556" "#A6E7F3" "#7172AD"])
+  []
+  (get-whitelabeled-colors ["#509EE3" "#88BF4D" "#A989C5" "#EF8C8C" "#F9D45C" "#F2A86F" "#98D9D9" "#7172AD"]))
```
Comment (WiNloSt) [inline src/metabase/automagic_dashboards/populate.clj:60]: Change some colors to match `colors.ts`, they were close but weren't the same color.
https://github.com/metabase/metabase/blob/8b341b1ac3b1c95d891058966bfb30b264b9285f/frontend/src/metabase/lib/colors.ts#L10-L18

From eye-balling I get that the colors were defined like this
`[brand accent1 accent2 accent3 accent4 accent5 accent6 accent7]`

File: src/metabase/automagic_dashboards/populate.clj [hunk 2]
```diff
@@ -55,14 +69,14 @@
         (fn [acc color count]
           (if (= count 1)
             (conj acc color)
-            (concat acc [color (first (drop-while (conj (set acc) color) colors))])))
+            (concat acc [color (first (drop-while (conj (set acc) color) (colors)))])))
```
Comment (WiNloSt) [inline src/metabase/automagic_dashboards/populate.clj:72]: Change from a value to a function evaluation

File: src/metabase/automagic_dashboards/populate.clj [hunk 3]
```diff
@@ -55,14 +69,14 @@
...
         [])))
 
 (defn map-to-colors
   "Map given objects to distinct colors."
   [objs]
   (->> objs
-       (map (comp colors #(mod % (count colors)) hash))
+       (map (comp (colors) #(mod % (count (colors))) hash))
```
Comment (WiNloSt) [inline src/metabase/automagic_dashboards/populate.clj:79]: Change from a value to a function evaluation

File: src/metabase/models/dashboard.clj [hunk 4]
```diff
@@ -350,7 +350,7 @@
         dashcards  (:ordered_cards dashboard)
         collection (populate/create-collection!
                     (ensure-unique-collection-name (:name dashboard) parent-collection-id)
-                    (rand-nth populate/colors)
+                    (rand-nth (populate/colors))
```
Comment (WiNloSt) [inline src/metabase/models/dashboard.clj:353]: Change from a value to a function evaluation

File: src/metabase/automagic_dashboards/populate.clj [hunk 5]
```diff
@@ -43,9 +44,22 @@
         :location "/")
       (create-collection! "Automatically Generated Dashboards" "#509EE3" nil nil)))
 
-(def colors
+(defn- get-whitelabeled-colors
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/populate.clj:47]:
```suggestion
(defn- whitelabeled-colors
```

See https://github.com/metabase/metabase/wiki/Metabase-Clojure-Style-Guide#pure-function-names-should-be-nouns and https://stuartsierra.com/2016/01/09/how-to-name-clojure-functions

File: src/metabase/automagic_dashboards/populate.clj [hunk 6]
```diff
@@ -43,9 +44,22 @@
...
+  "Get color from application-colors or default color."
+  [default-colors]
+  (let [whitelabeled-color-names [:brand :accent1 :accent2 :accent3 :accent4 :accent5 :accent6 :accent7]]
+    (->> default-colors
+         (map vector whitelabeled-color-names)
+         (map (fn [[whitelabeled-color-name default-color]]
+                (whitelabeled-color-name (public-settings/application-colors) default-color)))
+         (into []))))
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/populate.clj:55]:
```suggestion
    (mapv (fn [whitelabeled-color-name default-color]
            (get (public-settings/application-colors) whitelabeled-color-name default-color))
          whitelabeled-color-names
          default-colors)))
```

File: src/metabase/automagic_dashboards/populate.clj (hunk 1 above)
Comment (camsaul) [inline src/metabase/automagic_dashboards/populate.clj:60]: The fact that you had to try to eyeball it to figure out what those colors meant is a sign that defining them as a vector is not the way to go. It's definitely weird to have a vector like that and just assume that somebody somewhere knows what they map to. Can you change it to a map like this?

```clj
[:brand :accent1 :accent2 :accent3 :accent4 :accent5 :accent6 :accent7]
```

Can you change this to a map like it is in the FE?

e.g.

```clj
{:brand "#509EE3" 
 :accent1  "#88BF4D"
...
}
```

Comment (camsaul) [reply src/metabase/automagic_dashboards/populate.clj:60]: You'll have to change the implementation for `whitelabeled-colors` but it should be simpler

File: src/metabase/automagic_dashboards/populate.clj (hunk 5 above)
Comment (WiNloSt) [reply src/metabase/automagic_dashboards/populate.clj:47]: This function isn't pure though as it depends on `public-settings/application-colors`. Should I make `public-settings/application-colors` an argument instead what do you think?

File: src/metabase/automagic_dashboards/populate.clj [hunk 7]
```diff
@@ -43,9 +44,23 @@
         :location "/")
       (create-collection! "Automatically Generated Dashboards" "#509EE3" nil nil)))
 
-(def colors
+(defn- whitelabeled-colors
+  "Get color from application-colors or default color."
+  [default-colors-map]
+  (vec (for [[whitelabeled-color-name default-color] default-colors-map]
+         (get (public-settings/application-colors) whitelabeled-color-name default-color))))
```
Comment (WiNloSt) [inline src/metabase/automagic_dashboards/populate.clj:51]: Since I'm changing from iterating a vector to iterating a map, I'm not sure if this is idiomatic, but hope it looks better @camsaul

File: src/metabase/automagic_dashboards/populate.clj [hunk 8]
```diff
@@ -43,9 +44,23 @@
...
-  ["#509EE3" "#9CC177" "#A989C5" "#EF8C8C" "#f9d45c" "#F1B556" "#A6E7F3" "#7172AD"])
+  []
+  (whitelabeled-colors {:brand "#509EE3"
+                        :accent1 "#88BF4D"
+                        :accent2 "#A989C5"
+                        :accent3 "#EF8C8C"
+                        :accent4 "#F9D45C"
+                        :accent5 "#F2A86F"
+                        :accent6 "#98D9D9"
+                        :accent7 "#7172AD"}))
```
Comment (WiNloSt) [inline src/metabase/automagic_dashboards/populate.clj:63]: Change some colors to match `colors.ts`, they were close but weren't the same color.
https://github.com/metabase/metabase/blob/8b341b1ac3b1c95d891058966bfb30b264b9285f/frontend/src/metabase/lib/colors.ts#L10-L18

From eye-balling I get that the colors were defined like this
`[brand accent1 accent2 accent3 accent4 accent5 accent6 accent7]`

File: src/metabase/automagic_dashboards/populate.clj (hunk 7 above)
Comment (dpsutton) [reply src/metabase/automagic_dashboards/populate.clj:51]: Some feedback:
- calling `(public-settings/application-colors)` repeatedly seems unnecessary. Just get the value once and then get values from it.
- maps are unordered. Getting a `vec` from iterating over it provides an undefined order. Perhaps you could use a vector of color names in a specified order? If the order is not important here, perhaps a docstring could help reassure. But the standard reaction when getting vec from a hashmap without specifying order is one of nervousness: the datastructure is almost entirely about order.

Comment (WiNloSt) [reply src/metabase/automagic_dashboards/populate.clj:51]: @dpsutton 
> Some feedback:
> 
> * calling `(public-settings/application-colors)` repeatedly seems unnecessary. Just get the value once and then get values from it.

I still have limited knowledge on Clojure, could you point out how I could do that?

> * maps are unordered. Getting a `vec` from iterating over it provides an undefined order. Perhaps you could use a vector of color names in a specified order? If the order is not important here, perhaps a docstring could help reassure. But the standard reaction when getting vec from a hashmap without specifying order is one of nervousness: the datastructure is almost entirely about order.

Ahhh, I think the order matters based on the previous code. There's a version that would preserve the order https://github.com/metabase/metabase/pull/22458#discussion_r866204156. But the point of using a map is to really tell which color HEX maps to which color name. Is there a way to use a map and still maintain the color order?

Comment (dpsutton) [reply src/metabase/automagic_dashboards/populate.clj:51]: Something like the following:
- merge the defaults and the application settings so that a single map has the correct mapping from color type to color
- define an order that we select them in
- then, select them in that order
  - I use `(into [] ...)` because it is imperative that this is a vector since it is used as a function from index to color when using the hash in `map-to-colors` below. I like `into []` over `mapv` since it is easy to miss the `v` in `mapv` when the vector is critical.
- bonus, make a test that uses some temporary colors for the app and ensure they are selected

```clojure
(defn colors
  "A vector of colors useful for the application. Uses [[public-settings/application-colors]] for user choices."
  []
  (let [order  [:brand :accent1 :accent2 :accent3 :accent4 :accent5 :accent6 :accent7]
        merged (merge {:brand   "#509EE3"
                       :accent1 "#88BF4D"
                       :accent2 "#A989C5"
                       :accent3 "#EF8C8C"
                       :accent4 "#F9D45C"
                       :accent5 "#F2A86F"
                       :accent6 "#98D9D9"
                       :accent7 "#7172AD"}
                      (public-settings/application-colors))]
    (into [] (map merged) order)))

populate=> (colors)
["#509EE3"
 "#88BF4D"
 "#A989C5"
 "#EF8C8C"
 "#F9D45C"
 "#F2A86F"
 "#98D9D9"
 "#7172AD"]
populate=> (public-settings/application-colors)
{}
populate=> (public-settings/application-colors {:brand "blue" :accent3 "magenta"})
"{\"brand\":\"blue\",\"accent3\":\"magenta\"}"
populate=> (colors)
["blue"
 "#88BF4D"
 "#A989C5"
 "magenta"
 "#F9D45C"
 "#F2A86F"
 "#98D9D9"
 "#7172AD"]
```

Comment (WiNloSt) [reply src/metabase/automagic_dashboards/populate.clj]: Thanks, @dpsutton I learned a lot. But still needs to wrap my head around the *transducers* 😆 .

Also, I didn't write any test as I think it's gonna take too much time. Because I have to figure out
- Where to put tests
- How to write tests
- How to run tests
Maybe that's for later.

**Review by dpsutton — APPROVED** [review]

**Comment by WiNloSt** [comment]
I decided to not backport this. As this PR would conflict with https://github.com/metabase/metabase/pull/21738 which contains a lot of changes.

**Comment by qnkhuat** [comment]
@WiNloSt I could help you fix those namespaces if you need to.

**Comment by WiNloSt** [comment]
@qnkhuat Much appreciated! That'll be great.
