### PR TITLE
XLSX Pivot Exports Now Use The Sort Settings from Viz Settings

### LINKED ISSUE #49416: Column Headers in Exports Pivots are Sometimes Ordered Incorrectly
### Describe the bug

When pivots are exported to Excel in pivot format - values without results aren't exported in the same order in which they're displayed in the UI. Sort selections from viz settings are also ignored.

### To Reproduce

1. Create a pivot with a date grouping
2. Set the date as a column for the pivot
3. Ensure some of the results for the first row have a NULL result
4. Export the pivot
5. Note that columns with NULL cells are displaced in the final export (they're at the end)

https://www.loom.com/share/f24c12c571a84fbba3dfb81f8ad00ee2?sid=59120f7f-457a-4581-ba4b-a7dae2e1025a

### Expected behavior

The exported pivot should match the pivot that's visible in the user interface.

### Logs

_No response_

### Information about your Metabase installation

v51

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes #49416

Prior to this PR, the xlsx pivot exports worked correctly except for the fact that no sorting (ascending or descending) was applied to the pivot rows or columns. Now, those settings are used when they exist.

NOTE: I cannot create a unit test that inspects the appearance of a Pivot table in the xlsx file since its contents are not calculated. They only get calculated when the file is first opened by Excel or Numbers or Sheets, until then the pivot table is merely a definition.

### CODE REVIEW

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 1]
```diff
@@ -612,6 +613,15 @@
       (.addColLabel pivot-table idx))
     (doseq [idx pivot-measures]
       (.addColumnLabel pivot-table DataConsolidateFunction/SUM #_(get aggregation-functions idx DataConsolidateFunction/SUM) idx))
+    (doseq [[idx sort-setting] column-sort-order]
+      (let [setting (sort-setting {:ascending  STFieldSortType/ASCENDING
+                                   :descending STFieldSortType/DESCENDING})]
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming/xlsx.clj:618]: nit — since it's not immediately obvious that `sort-setting` is a keyword, I think a `case` statement here might be a little more readable? just a suggestion, since I was slightly thrown by this initially
```suggestion
      (let [setting (case sort-setting
                      :ascending STFieldSortType/ASCENDING
                      :descending STFieldSortType/DESCENDING)]
```

**Review by noahmoss — APPROVED** [review]
