### PR TITLE
[QP] Override `LIMIT` for pivot queries to ensure consistent results

### LINKED ISSUE #70963: Pivot tables can show incorrect numbers
### Describe the bug

Creating a Github bug report for https://linear.app/metabase/issue/QUE2-431/pivot-tables-can-show-incorrect-numbers

Pivot tables appear to return incorrect values. The issue was observed while creating a pivot from a native subquery within an MBQL query. It is not yet confirmed whether this is a regression or whether the same problem also happens when creating a pivot directly from a regular table.

Related example: [Loom video](https://www.loom.com/share/c8d835d3691b41a09f192bc0b092cde9)

### To Reproduce

SQL to reproduce:

```
with prepared_data as (
SELECT
    -- Generates 1,000 unique Customer IDs
    CONCAT('CUST-', LPAD((t1.n + t2.n * 16 + t3.n * 256) % 1000, 4, '0')) AS customer_id, 
    -- Generates 100 unique Product IDs
    CONCAT('PROD-', LPAD((t2.n + t3.n * 16 + t4.n * 256) % 100, 3, '0')) AS product_id,
    -- Added a Category for the Pivot Column
    ELT((t1.n % 4) + 1, 'Standard', 'Premium', 'Wholesale', 'Internal') AS account_type,
    -- Metrics
    ROUND(RAND() * 500, 2) AS revenue,
    1 AS transactions
FROM
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15) AS t1
CROSS JOIN
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15) AS t2
CROSS JOIN
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15) AS t3
CROSS JOIN
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15) AS t4
)
select
customer_id,
product_id,
SUM(revenue) AS total_rev
from prepared_data
GROUP BY customer_id, product_id
order by customer_id, product_id
-- order by customer_id DESC, product_id DESC

```

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
-
```

### Severity

p1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bshepherdson**
closes #70963
Fixes QUE2-431.

### Description

Previously, pivot queries got the same default row limits added as any
aggregated query. But since pivot queries synthesize the results from
several inner queries with different subsets of breakouts, they
have different row counts.

The main ("row details") query the user wrote has all the breakouts,
so it has the most rows. If that query gets truncated, only a subset
of the data is returned, leaving gaps in the pivot table. Worse, the
sub-queries with other subsets of the breakouts, intended to collect
group, column and row subtotals, and the grand total, are inconsistent
with the details in the cells, and with each other, because they can
all end up `SUM`ing (etc.) over different sets of the raw rows.

With this change, a new and much larger row limit is permitted for the
pivot sub-queries. The pivot table viz contains one cell for each
aggregation in the query, multiplied by the rows of the main query.
We budget for **200k cells**, divide by the number of aggregations,
and that becomes the row limit.

If the row details query reaches that limit, the query is rejected:
- Other sub-queries are skipped
- A `pivot-rows-truncated` flag in the results signal the FE
- Which shows an error suggesting the user add a filter or remove
  breakouts to lower the row count.

Some reasonable pivot queries might still be excluded, but now we never
run a pivot query with incorrect data in it. If we execute the query and
render the pivot results, then all the returned data should be correct.

### How to verify

See QUE2-431 for a SQL query with synthetic data. You can also reproduce this with a sufficiently high granularity in a pivot table on the Sample Database, such as `Orders, SUM(subtotal) by Created At: Week, User->State, Product->Category`.

Compare eg. the column or row subtotals with a breakout of `SUM(subtotal)` by the row/column dimension. They will be incorrect before this change and correct after it.

### Demo

TODO: Add my screenshot of the error message.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- ~~If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)~~

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#71033** <a href="https://app.graphite.com/github/pr/metabase/metabase/71033?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/metabase/metabase/71033?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: test/metabase/query_processor/pivot_test.clj [hunk 1]
```diff
@@ -827,3 +827,47 @@
                 (mt/formatted-rows
                  [str str int int int]
                  (qp.pivot/run-pivot-query query))))))))
+
+(deftest pivot-query-uses-custom-limit-test
```
Comment (camsaul) [inline test/metabase/query_processor/pivot_test.clj]: I think you can make this parallel right?

File: test/metabase/query_processor/pivot_test.clj [hunk 2]
```diff
@@ -827,3 +827,47 @@
...
+              (str "Detail count sum (" detail-count-sum ") should equal grand total ("
+                   grand-total-count ") because pivot uses its own higher limit")))))))
+
+(deftest pivot-query-short-circuits-when-master-hits-limit-test
+  (testing "When the master pivot query hits the row limit, remaining sub-queries are skipped and truncation is signaled"
+    (mt/test-drivers (qp.pivot.test-util/applicable-drivers)
+      ;; Use the standard pivot-query but override the pivot limit to be very small.
+      ;; The master query (state × source × category) produces ~200+ rows.
+      ;; With pivot-max-result-rows=20, the limit is 20/2=10 per sub-query.
+      (with-redefs [qp.pivot/pivot-max-result-rows 20]
```
Comment (camsaul) [inline test/metabase/query_processor/pivot_test.clj]: Might be worth making `pivot-max-result-rows` dynamic so this test can be made `^:parallel` too

**Review by camsaul — APPROVED** [review]

**Review by ranquild — APPROVED** [review]
