### PR TITLE
Don't compute only on non-zero scores

### LINKED ISSUE #16591: Archive page shows "Divide by zero" error on our stats instance
**Describe the bug**
When visiting https://stats.metabase.com/archive the page shows a "Divide by zero" error message. Looks like a not-covered edge case in search results scoring calculation (see the stack trace below).

**To Reproduce**
Not sure it can be reproduced for every user, maybe you need some combination of collections and data permissions

1. Open https://stats.metabase.com/archive
2. The page shows a "Divide by zero" error message

**Expected behavior**
The page should show a list of archived items

**Screenshots**

image

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes #16591 

I was removing a helper function when refactoring the scoring. That
had a filter on :score?. I'm not sure why i translated this to only
interpret the denominator of scoring to only include scores that were
positive. This is obviously wrong.

For the archive page, we just want all archived results, so it is quite reasonable that all scores are 0 (the text input is an empty string), and reducing `+` over those where the score is positive leads us to just `(reduce + ())` and we have a zero in our denominator.

Also, previously, all databases would be returned in the archived
query which seems obviously wrong. Databases cannot be archived and so
should never appear when searching for archived items.

### CODE REVIEW

File: src/metabase/api/search.clj [hunk 1]
```diff
@@ -163,7 +163,7 @@
 ;; Databases can't be archived
 (defmethod archived-where-clause (class Database)
   [model archived?]
-  [:= 1 1])
+  [:= 1 (if archived? 2 1)])
```
Comment (dpsutton) [inline src/metabase/api/search.clj:166]: @tsmacdonald wanted your eyes specifically on this part. There were databases on the archive page which was quite strange since they cannot be archived. Seems like we would never want databases in archived results

Comment (tsmacdonald) [reply src/metabase/api/search.clj:166]: Yeah, this seems sensible (thanks for the work!). Some of my early search work was completely unaware of the archived page being powered by the search endpoint (I still think is not the best idea), so when I added databases to the search results I wasn't thinking about it.

**Review by tsmacdonald — APPROVED** [review]
Looks good to me, thanks!

File: src/metabase/api/search.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/api/search.clj:166]: I agree. I was quite surprised to see that we were scoring and ranking these things.
