### PR TITLE
MLv2: Implement support for `:value` clause

### LINKED ISSUE #29895: [MLv2] [Bug] pMBQL does not handle `:value` clauses
I'm running schema validation against the pMBQL queries we generate as part of Braden's work in #29487 and making sure they work.

Apparently `:value` clauses do not work. It looks like they are converted correctly, but the Malli schema does not know about them or recognize them as a type of expression.

`:value` is supposed to be allowed to wrap any sort of literal, including `nil` (where you can give it a `:base_type`, which can be important sometimes) as well as strings like `2023` or `2023-04` that would not normally be allowed as `:type/Date` literals. 

I did some work towards supporting this in #29583, maybe that could be used as a starting point.

```clj
legacy query = 
{:database 2353,
 :type :query,
 :query
 {:expressions
  {"expr"
   [:case [[[:< [:field 132946 nil] 10] [:value nil {:base_type :type/Number}]] [[:> [:field 132946 nil] 2] 10]]]},
  :fields [[:expression "expr"]],
  :limit 10,
  :source-table 32371}}
 
pMBQL query =
{:lib/type :mbql/query,
 :type :pipeline,
 :stages
 [{:lib/type :mbql.stage/mbql,
   :lib/options {:lib/uuid "4a59f9d0-49b6-4849-a548-2b142e63037e"},
   :expressions
   {"expr"
    [:case
     {:lib/uuid "583e7db5-8d14-4896-846f-a7fdb945f344"}
     [[[:<
        {:lib/uuid "99694b62-201f-44c3-8261-21a5ccb86a2f"}
        [:field {:lib/uuid "c5e3402c-a9b0-41cc-9d99-6e4bd3da8bee"} 132946]
        10]
       [:value {:base_type :type/Number, :lib/uuid "8ac432ee-0c2f-4bd4-a6e7-42bcaebeba57"} nil]]
      [[:>
        {:lib/uuid "4f5ac10f-1bf5-4de6-817a-81f02f99394f"}
        [:field {:lib/uuid "a435632c-f8b7-4234-86c8-09ef11369cef"} 132946]
        2]
       10]]]},
   :fields [[:expression {:lib/uuid "93541bf7-1293-4d36-b175-709e8f6347bd"} "expr"]],
   :limit 10,
   :source-table 32371}],
 :database 2353}


converted pMBQL query should validate against the pMBQL schema
expected: (not (me/humanize (mc/explain :metabase.lib.schema/query pMBQL)))

  actual: (not          
           (not
            {:stages
             [{:expressions
               {"expr"
                ["invalid MBQL clause: [:case {:lib/uuid \"583e7db5-8d14-4896-846f-a7fdb945f344\"} [[[:< {:lib/uuid \"99694b62-201f-44c3-8261-21a5ccb86a2f\"} [:field {:lib/uuid \"c5e3402c-a9b0-41cc-9d99-6e4bd3da8bee\"} 132946] 10] [:value {:base_type :type/Number, :lib/uuid \"8ac432ee-0c2f-4bd4-a6e7-42bcaebeba57\"} nil]] [[:> {:lib/uuid \"4f5ac10f-1bf5-4de6-817a-81f02f99394f\"} [:field {:lib/uuid \"a435632c-f8b7-4234-86c8-09ef11369cef\"} 132946] 2] 10]]]"
                 "any type of expression"]}}]}))
```

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #29895

The `:value` clause wraps literals and is mostly used internally by the QP or to attach type information to `nil`, but we still need to support it. `:value` is a weird case because its options keys were `snake_case`, I normalized them to `kebab-case` for consistency with the rest of pMBQL, so one more weird little quirk about legacy MBQL removed there. 

A few other misc improvements that I'll call out in comments.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30163)

### CODE REVIEW

File: dev/src/user.clj [hunk 1]
```diff
@@ -2,7 +2,6 @@
   (:require
    [hawk.assert-exprs]
    [metabase.bootstrap]
-   metabase.query-processor-test.test-mlv2
```
Comment (camsaul) [inline dev/src/user.clj:5]: Discussed here https://metaboat.slack.com/archives/C010L1Z4F9S/p1681319052854699?thread_ts=1681241917.937639&cid=C010L1Z4F9S -- loading this as part of `user.clj` is a little iffy since it loads up a huge chunk of the system as a side-effect. Fixing this has been on my TODO list since last week. It's better to only load this when we actually need it, i.e. in `metabase.query-processor`.

File: src/metabase/lib/convert.cljc [hunk 2]
```diff
@@ -40,6 +42,10 @@
                                               (map (juxt :type :in))
                                               first)]
       (let [new-stage (clean-location almost-stage error-type error-location)]
+        (log/warnf "Clean: Removing bad clause in %s due to error %s:\n%s"
+                   (u/colorize :yellow (pr-str error-location))
+                   (u/colorize :yellow (pr-str error-type))
+                   (u/colorize :red (u/pprint-to-str (first (data/diff almost-stage new-stage)))))
```
Comment (camsaul) [inline src/metabase/lib/convert.cljc:48]: I added a log warning if the clean logic removes something, it makes it easier to debug stuff.

File: src/metabase/lib/convert.cljc [hunk 3]
```diff
@@ -231,9 +250,19 @@
...
+                                    :semantic-type :semantic_type
+                                    :database-type :database_type})
+                 ;; remove `:effective-type`, which is not used for `:value` in legacy MBQL and is just going to
+                 ;; confuse things.
+                 (dissoc :effective-type)
+                 disqualify
+                 not-empty)]
+    ;; in legacy MBQL, `:value` has to be three args; `opts` has to be present, but it should can be `nil` if it is
+    ;; empty.
+    [:value value opts]))
```
Comment (camsaul) [inline src/metabase/lib/convert.cljc:265]: Old logic was wrong. `:value` has to have 3 args, always.

File: src/metabase/lib/normalize.cljc [hunk 4]
```diff
@@ -35,13 +35,15 @@
 
 (def default-map-value-fns
   "Default normalization functions keys when doing map normalization."
-  {:base-type   keyword
-   :type        keyword
+  {:base-type      keyword
+   :effective-type keyword
```
Comment (camsaul) [inline src/metabase/lib/normalize.cljc:39]: Missing pMBQL normalization logic for `:effective-type` and `:semantic-type`. Fixed

File: src/metabase/lib/schema/common.cljc [hunk 5]
```diff
@@ -46,9 +42,20 @@
...
+(mr/def ::options
+  [:map
+   [:lib/uuid ::uuid]
+   ;; these options aren't required for any clause in particular, but if they're present they must follow these schemas.
+   [:base-type      {:optional true} [:maybe ::base-type]]
+   [:effective-type {:optional true} [:maybe ::base-type]]
+   [:semantic-type  {:optional true} [:maybe ::semantic-type]]
+   [:database-type  {:optional true} [:maybe ::non-blank-string]]
+   [:name           {:optional true} [:maybe ::non-blank-string]]
+   [:display-name   {:optional true} [:maybe ::non-blank-string]]])
```
Comment (camsaul) [inline src/metabase/lib/schema/common.cljc:57]: I added various things like `:base-type`, `:effective-type`, `:semantic-type`, etc. as optional keys to the lib options schema, so if those keys are present they have to conform to the relevant schemas.

File: src/metabase/lib/schema/expression.cljc [hunk 6]
```diff
@@ -48,11 +48,12 @@
...
   [expr]
   (or
-   ;; for MBQL clauses with `:base-type` in their options: ignore their dumb [[type-of*]] methods and return that type
-   ;; directly. Ignore everything else! Life hack!
+   ;; for MBQL clauses with `:effective-type` or `:base-type` in their options: ignore their dumb [[type-of*]] methods
+   ;; and return that type directly. Ignore everything else! Life hack!
    (and (mbql-clause? expr)
         (map? (second expr))
-        (:base-type (second expr)))
+        (or (:effective-type (second expr))
```
Comment (camsaul) [inline src/metabase/lib/schema/expression.cljc:55]: We're moving towards using `:effective-type` everywhere, not `:base-type` (see #29707), so I updated this to check `:effective-type` preferentially to `:base-type` if its present.

File: test/metabase/query_processor_test/test_mlv2.clj [hunk 7]
```diff
@@ -120,7 +116,7 @@
      {:aggregation aggregations}
      (mbql.u/match-one aggregations
        :metric
-       "#28689"))
+       "#29936"))
```
Comment (camsaul) [inline test/metabase/query_processor_test/test_mlv2.clj:119]: This was the wrong issue number; `#28689` is the epic, I meant to write `#29936` originally.

File: src/metabase/lib/convert.cljc [hunk 8]
```diff
@@ -143,17 +168,20 @@
...
 
 (defn- lib-key? [x]
   (and (qualified-keyword? x)
        (= (namespace x) "lib")))
 
-(defn- disqualify [x]
-  (->> x
+(defn- disqualify
+  "Remove any keys starting with the `:lib/` namespace from map `m`."
+  [m]
```
Comment (camsaul) [inline src/metabase/lib/convert.cljc:180]: `m` is a more idiomatic variable name for something that is a map than `x`, makes this a little easier for me to remember what it's doing

File: src/metabase/lib/convert.cljc [hunk 9]
```diff
@@ -59,7 +66,8 @@
 (defmulti ->pMBQL
   "Coerce something to pMBQL (the version of MBQL manipulated by Metabase Lib v2) if it's not already pMBQL."
   {:arglists '([x])}
-  lib.dispatch/dispatch-value)
+  lib.dispatch/dispatch-value
+  :hierarchy lib.hierarchy/hierarchy)
```
Comment (camsaul) [inline src/metabase/lib/convert.cljc:70]: Updated these multimethods to use the lib hierarchy added in #29773

File: src/metabase/lib/convert.cljc [hunk 10]
```diff
@@ -120,10 +128,27 @@
...
+        ;; but on the off chance it did not give this `:type/*` so the schema doesn't fail entirely.
+        opts (assoc opts :effective-type (or (:effective-type opts)
+                                             (:base-type opts)
+                                             :type/*))]
+    (lib.options/ensure-uuid [:value opts value])))
+
+(doseq [tag [:aggregation :expression]]
+  (lib.hierarchy/derive tag ::aggregation-or-expression-ref))
+
+(defmethod ->pMBQL ::aggregation-or-expression-ref
```
Comment (camsaul) [inline src/metabase/lib/convert.cljc:149]: Wow, look at the cool things you can do with that hierarchy.

**Review by bshepherdson — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30163)* status: all files reviewed, 11 unresolved discussions (waiting on @camsaul)

___
*[`src/metabase/lib/convert.cljc` line 48 at r1](https://reviewable.io/reviews/metabase/metabase/30163#gh-1169284901:-NTLEnIXCsuTV2C1ottQ:b-83sjoh) ([raw file](https://github.com/metabase/metabase/blob/8acbb37f762fd66b7e4a8a5fe53cc03b7483c009/src/metabase/lib/convert.cljc#L48)):*
<details><summary><i>Previously, camsaul (Cam Saul) wrote…</i></summary><blockquote>

I added a log warning if the clean logic removes something, it makes it easier to debug stuff.
</blockquote></details>

Nice!
___
*[`src/metabase/lib/schema/literal.cljc` line 198 at r3](https://reviewable.io/reviews/metabase/metabase/30163#-NTLFsh-1GAcrdM-wpkw:-NTLFsh-1GAcrdM-wpkx:beror54) ([raw file](https://github.com/metabase/metabase/blob/dc5cdfc5ea2c2c966f23caba7290688123d8fd70/src/metabase/lib/schema/literal.cljc#L198)):*
> ```Clojure
> ;;;
> ;;; The schema itself does not enforce that the actual <value> matches up with the `:effective-type` or
> ;;; `:effective-type` in
> ```

This comment kind of trails off?

**Review by bshepherdson — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30163)* status: all files reviewed, 9 unresolved discussions

**Review by camsaul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30163)* status: all files reviewed, 9 unresolved discussions (waiting on @bshepherdson)

___
*[`src/metabase/lib/convert.cljc` line 176 at r5](https://reviewable.io/reviews/metabase/metabase/30163#-NTPr5dl92l6n7RFcyLn:-NTPr5dl92l6n7RFcyLo:bqdnece) ([raw file](https://github.com/metabase/metabase/blob/b887abb56b716981d8cc7bdd0a6ddeba39b42844/src/metabase/lib/convert.cljc#L176)):*
> ```Clojure
>   No args = return transducer to remove `:lib/` keys from a map. One arg = update a map `m`."
>   ([]
>    (remove (fn [[k _v]]
> ```

We can make this a little more performant and compose this stuff a little more easily with a transducer, not that it makes a huge difference really but I couldn't help myself



_Code quote:_
```Clojure
   (remove (fn [[k _v]]
             (and (qualified-keyword? k)
                  (= (namespace k) "lib")))))
```
___
*[`src/metabase/lib/convert.cljc` line 182 at r5](https://reviewable.io/reviews/metabase/metabase/30163#-NTPsQhY24cjnziChc2X:-NTPsQhY24cjnziChc2Y:bk07cs8) ([raw file](https://github.com/metabase/metabase/blob/b887abb56b716981d8cc7bdd0a6ddeba39b42844/src/metabase/lib/convert.cljc#L182)):*
> ```Clojure
>    (into {} (disqualify) m)))
> 
> (defn- options->legacy-MBQL
> ```

Removed the part that removes `:effective-type` from `disqualify` and put that in a different function to fix the bug discussed in Slack where `:effective-type` was removed from places in a legacy query where it should not have been removed
___
*[`src/metabase/lib/util.cljc` line 132 at r5](https://reviewable.io/reviews/metabase/metabase/30163#-NTPs8Q99N5df-QYFsq6:-NTPs8Q99N5df-QYFsq7:bbhgka) ([raw file](https://github.com/metabase/metabase/blob/b887abb56b716981d8cc7bdd0a6ddeba39b42844/src/metabase/lib/util.cljc#L132)):*
> ```Clojure
>         previous-stage  (dec (count previous-stages))
>         previous-stages (cond-> previous-stages
>                           (and source-metadata
> ```

fix an out of bounds error if you have `:source-metadata` without a `:source-query`, which shouldn't really happen but I did trigger it while trying to write a test where I stripped out what I thought were irrelevant parts of a query.



_Code quote:_
```Clojure
                          (and source-metadata
                               (not (neg? previous-stage))) (assoc-in [previous-stage :lib/stage-metadata] source-metadata))
```
___
*[`src/metabase/lib/schema/literal.cljc` line 198 at r3](https://reviewable.io/reviews/metabase/metabase/30163#-NTLFsh-1GAcrdM-wpkw:-NTPr-9Q-cDK2cuMjd8B:b1kxy83) ([raw file](https://github.com/metabase/metabase/blob/dc5cdfc5ea2c2c966f23caba7290688123d8fd70/src/metabase/lib/schema/literal.cljc#L198)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

This comment kind of trails off?
</blockquote></details>

good catch, fixed
___
*[`test/metabase/lib/convert_test.cljc` line 267 at r5](https://reviewable.io/reviews/metabase/metabase/30163#-NTPsJea1TOmFRKAYvzs:-NTPsJea1TOmFRKAYvzt:b5gikyd) ([raw file](https://github.com/metabase/metabase/blob/b887abb56b716981d8cc7bdd0a6ddeba39b42844/test/metabase/lib/convert_test.cljc#L267)):*
> ```Clojure
>                    :name            "category"
>                    :source          :breakout
>                    :effective-type  :type/Text
> ```

This key was getting stripped out prior to the aforementioned fix
