### PR TITLE
Fix admin override for public actions

### LINKED ISSUE #47704: Public Actions Fail
### Describe the bug

Public actions fail with "An error occurred".

### To Reproduce

1. Set up a simple test table in Postgres
`CREATE TABLE test_table (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50)
);

INSERT INTO test_table (NAME)
VALUES 
    ('Alice'),  
    ('Ivan'),
    ('Judy');`
2. In Metabase create a model on this table
3. Add an action
`UPDATE test_table
SET NAME = {{newName}}
WHERE ID = {{id}};`
4. Test the action to confirm it works
5. Publish the action
6. Navigate to the public link for the action
7. Test the action and see that it fails

### Expected behavior

Public actions should work

### Logs

400 Bad Request response on the post request:

http://localhost:15023/api/public/action/ba5262f7-f0d6-41c1-af03-822837bc5bb1/execute

### Information about your Metabase installation

```JSON
v50.23
```

### Severity

Blocking some users

### Additional context

https://www.loom.com/share/d62b408926e84fcabe2f7daff746c4d3

### PR DESCRIPTION
**Pull request by noahmoss**
* Replaces `(binding [api/*current-user-permissions-set* (delay #{"/"})] ...)` with `(mw.session/as-admin ...)` so that perm checks are (correctly) skipped when executing public actions.
* Fixes a couple other instances of the above in tests for consistency, though I don't have evidence they were causing issues
* Ensures that that the `advanced-permissions` feature is enabled in public actions test so that it correctly catches this issue in CI

Resolves https://github.com/metabase/metabase/issues/47704

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#47717** <a href="https://app.graphite.dev/github/pr/metabase/metabase/47717?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: test/metabase/api/public_test.clj [hunk 1]
```diff
@@ -1757,68 +1757,70 @@
...
-                 :post 200
-                 (format "public/action/%s/execute" public_uuid)
-                 {:parameters {:id 1 :name "European"}})
-                (is (= {:data   {"action_id" (t2/select-one-pk 'Action :public_uuid public_uuid)
-                                 "event"     "action_executed"
-                                 "source"    "public_form"
-                                 "type"      "query"}
-                        :user-id nil}
-                       (last (snowplow-test/pop-event-data-and-user-id!))))))))))))
+  (mt/with-premium-features #{:advanced-permissions}
```
Comment (noahmoss) [inline test/metabase/api/public_test.clj:1760]: This is a short-term fix for this test. We will investigate a way to set up CI better as a follow-up to avoid this class of issues

**Review by johnswanson — APPROVED** [review]
