### PR TITLE
fix(sdk): Remove default Count aggregation without triggering a query update

### LINKED ISSUE #44298: Query builder does not reflect what's displayed on screen
### Describe the bug

Seems like a state bug where we show stuff on the query builder that's not displayed in the table view

### To Reproduce

1) new question -> orders
image

2) join with people and then visualize
image

3) click on summarize, count is selected when there's no count there
image

4) remove the count, the order people table only is shown
image

5) go to the query builder, you still have the 2 tables shown
image

6) click again on visualize, you still see the orders table
image

7) even the columns of people are not there
image

### Expected behavior

We should reflect on the table view what's selected in the query builder

### Logs

NA

### Information about your Metabase installation

```JSON
v50 (but most probably coming from a while ago)
```

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/44298
Demo https://www.loom.com/share/ea943eaf9548456da9c8606eb1a5083d

Previously removing the default aggregation in the summarize sidebar was a destructive action. Now we handle it with a simple state update.

I did some small cleanup and passed `stageIndex: -1` from a single place in summarize components.

How to verify:
- New -> Question -> Orders
- Join -> Products. Select some specific fields in the join, like ID, Category.
- Visualize
- Summarize -> Remove the default aggregation 
- Nothing should happen apart from changes in the sidebar itself
- Open the notebook editor
- Open join field picker
- See that your fields are still there

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Summarize.tsx [hunk 1]
```diff
@@ -50,6 +50,8 @@ const SummarizeInner = ({
   };
 
   const {
+    query,
```
Comment (kamilmielnik) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Summarize.tsx:53]: I would argue that the issue is not fully fixed yet.

> Query builder does not reflect what's displayed on screen 

That sentence is still true. "Count" is shown as if it was applied when it isn't.
I don't see any reason why would we have this one special case.
It's confusing from user's perspective and from code perspective.

----

I see 2 valid ways for it to work.
When you click "Summarize" (for a question without aggregations in the last stage), either:
1. "Count" aggregation is actually applied to the question (without having to click "Done"). Personally I don't like this, but maybe there's a good product reason for it.
2. Nothing happens, user sees "empty state" in the sidebar. User has to choose aggregations/breakouts manually.
    - I'd change one more thing in this case - show breakouts section regardless of whether aggregations are present. Scenario: 
        1. New question > Orders > join Products > Breakout by whatever > Visualize
        2. Summarize
        3. Remove the _default_ "Count" aggregation
        4. Now we don't show the breakout in the sidebar, but it's there. Confusing.

Comment (ranquild) [reply enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Summarize.tsx:53]: @kamilmielnik this is been discussed multiple times and the existing behavior is what we want. Please take a look https://metaboat.slack.com/archives/C0645JP1W81/p1719588433987439

**Review by kamilmielnik — APPROVED** [review]
