### PR TITLE
Fix `:selected?` property of `visible-columns` (CLJS only)

### LINKED ISSUE #47575: [BE] Cannot select/deselect columns coming from the source card when there are multiple breakouts of the same column
Skipped e2e test https://github.com/metabase/metabase/blob/c2dc11b1b48592e9327f412f1155440698a27fda/e2e/test/scenarios/question/multiple-column-breakouts.cy.spec.ts#L1758

When the source card contains multiple breakouts for the same column, deselecting a field leads to loss of `:selected` state for columns coming from `Lib.visibleColumns`. The problem:
1. deselection creates a `:fields` clause in the query
2. `returned-columns` now have `:lib/source :source/fields` and not `:source/card`
3. `column-metadata->field-ref` generates field id-based field refs and not based on the `:lib/desired-column-alias` for `returned-columns`; these field refs are fully identical now
4. `find-matching-column` cannot disambiguate the field refs.

### PR DESCRIPTION
**Pull request by ranquild**
Closes https://github.com/metabase/metabase/issues/47575

### CODE REVIEW

File: src/metabase/lib/js.cljs [hunk 1]
```diff
@@ -1173,13 +1173,27 @@
...
-  (let [stage          (lib.util/query-stage a-query stage-number)
-        vis-columns    (lib.metadata.calculation/visible-columns a-query stage-number stage)
-        ret-columns    (lib.metadata.calculation/returned-columns a-query stage-number stage)]
-    (to-array (lib.equality/mark-selected-columns a-query stage-number vis-columns ret-columns))))
+  (let [stage       (lib.util/query-stage a-query stage-number)
+        vis-columns (lib.metadata.calculation/visible-columns a-query stage-number stage)
+        ret-columns (lib.metadata.calculation/returned-columns a-query stage-number stage)]
+    (->> vis-columns
+         (map #(assoc % :selected? (some? (lib.equality/find-matching-column a-query stage-number % ret-columns))))
+         to-array)))
```
Comment (bshepherdson) [inline src/metabase/lib/js.cljs:1196]:
```suggestion
    (->> (for [col vis-columns
               :let [match (lib.equality/find-matching-column a-query stage-number col ret-columns)]]
           (assoc col :selected? (some? match)))
         to-array)))
```

**Review by bshepherdson — APPROVED** [review]
