### PR TITLE
fix: UUID filters across supported databases

### LINKED ISSUE #37492: Filter widget breaks page when typing a value
### Describe the bug

I was trying to filter for a specific ID in a model in the filter widget and then the page crashed.

This seems to be related to a GET `/api/field/:id/search/:id` endpoint returns HTTP 204 no content instead of an empty array.

There is a workaround to just filter on the normal column dropdown in the model table view.

### To Reproduce

I couldn't reproduce it for other models than the one where it broke but here is what I did (more context in the video in our [Slack](https://metaboat.slack.com/archives/C01LQQ2UW03/p1704872831507539))

1. Go to a model page
2. Click on the "Filter" button on the top 
image

3. Scroll down to the entity id field and start typing 
image

image

### Expected behavior

_No response_

### Logs

Some logs from the console:
```
TypeError: e.map is not a function or its return value is not iterable
    at Q (utils.ts:33:22)
    at SearchValuePicker.tsx:40:11
    at Object.ig [as useMemo] (react-dom.production.min.js:162:119)
    at t.useMemo (react.production.min.js:25:113)
    at J (SearchValuePicker.tsx:39:19)
    at o6 (react-dom.production.min.js:153:146)
    at iF (react-dom.production.min.js:175:309)
    at l (react-dom.production.min.js:263:406)
    at aH (react-dom.production.min.js:246:265)
    at react-dom.production.min.js:246:194
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.201-191.748.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "mysql",
      "postgres",
      "redshift",
      "bigquery-cloud-sdk",
      "mongo",
      "h2",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-09",
      "tag": "vUNKNOWN",
      "hash": "30fff3b"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snoe**
Fixes #37492

### CODE REVIEW

File: src/metabase/driver.clj [hunk 1]
```diff
@@ -675,6 +675,9 @@
     ;; many databases in it.
     :connection/multiple-databases
 
+    ;; Does this driver support UUID type
+    :uuid-type
```
Comment (camsaul) [inline src/metabase/driver.clj:679]: You should mention new feature flags in the driver changelog file so third-party driver authors can add them if appropriate.

File: src/metabase/driver/sql/query_processor.clj [hunk 2]
```diff
@@ -1295,17 +1303,39 @@
         expr
         [:lower expr]))))
 
+(mu/defn ^:private maybe-cast-uuid-for-equality
+  "Comparing UUID fields against text values requires casting."
+  [driver field arg]
+  (if (and (isa? (:base-type (get field 2)) :type/UUID)
```
Comment (camsaul) [inline src/metabase/driver/sql/query_processor.clj:1309]: You should  be looking at `:effective-type` in preference to `:base-type` if it's present

File: src/metabase/driver/sql/query_processor.clj [hunk 3]
```diff
@@ -1295,17 +1303,39 @@
...
+           (= (:database-type (h2x/type-info (->honeysql driver arg))) "text"))
```
Comment (camsaul) [inline src/metabase/driver/sql/query_processor.clj:1310]: What about `varchar` or `char` or `smalltext` `ntext` or anything else like that? We need to compare the actual Metabase type here to `:type/Text`, which means this logic probably needs to happen the methods for `:=` and `:!=` instead of here

File: src/metabase/driver/sql/query_processor.clj [hunk 4]
```diff
@@ -1295,17 +1303,39 @@
...
+    [::cast field "text"]
+    field))
+
+(mu/defn ^:private maybe-cast-uuid-for-text-compare
+  "Comparing UUID fields against text values requires casting."
+  [field]
+  (if (isa? (:base-type (get field 2)) :type/UUID)
+    [::cast field "text"]
+    field))
```
Comment (camsaul) [inline src/metabase/driver/sql/query_processor.clj:1319]: This is almost certainly going to break any potential indexes on this column, instead of doing 

```sql
WHERE my_uuid_column::text = ?::text
```

we should be doing 

```sql

WHERE my_uuid_column = ?::uuid
```

Comment (camsaul) [reply src/metabase/driver/sql/query_processor.clj:1319]: I think you should be able to have the `->honeysql` method for `[:postgres :value]` or `[:h2 :value]` take care of this and output this correctly `?::uuid` or `cast(? AS uuid)` instead of `? -- string`

Comment (camsaul) [reply src/metabase/driver/sql/query_processor.clj:1319]: actually I guess maybe that doesn't work if you're comparing two columns like `[:= {} my_uuid_column my_text_column]`

**Review by camsaul — CHANGES_REQUESTED** [review]
* we should mention all new feature flags in the driver changelog file
* This doesn't seem like it's going to work for a filter like `[:= {} uuid_column varchar_column]` or anything else where the database type is not literally `text`. There are lots of other `:type/Text` database types besides just `text`
* We should be applying the cast to the text value (cast to UUID) instead of casting the UUID column to text so we can still hit indexes on that column if there are any (this can be a really huge performance difference honestly)

File: src/metabase/driver/sql/query_processor.clj (hunk 3 above)
Comment (snoe) [reply src/metabase/driver/sql/query_processor.clj:1310]: I will change this to check that the arg type is not a UUID. More explanation below.

File: src/metabase/driver/sql/query_processor.clj (hunk 4 above)
Comment (snoe) [reply src/metabase/driver/sql/query_processor.clj:1319]: This is perhaps confusing, I'll add comments.

`maybe-cast-uuid-for-text-compare` is for `:contains` `:starts-with` `:ends-with` - here, indexes aren't going to come into play as the value passed in is always a string wit `"%"` prepended/appended for `LIKE`

`maybe-cast-uuid-for-equality` is for `:=` and `:!=` Here, `->honeysql [:sql :value]` will have already run, and if we have a UUID value we won't do any casting. The cast is necessary when the value is not a valid uuid (passed through dashboard filter `where uuid = "q"`) if we don't cast the field to text in this case, databases blow up.

I will change this to be more clear and add a test that ensures a proper index comparison is being made in honeysql.

**Review by camsaul — APPROVED** [review]
