### PR TITLE
Fix question name not showing when using Entity.Name

### LINKED ISSUE #33192: Question name not displayed when changing click behavior
### Describe the bug

image

It used to work like this: [image](https://github.com/metabase/metabase/assets/6830683/bc325a75-c119-472d-8efc-843eeb81fc2e)

### To Reproduce

1. Create a question (e.g. Reviews - Summarized by Count by CreatedAt: Month) and save it to a dashboard
2. Edit the dashboard
3. Click "Click behavior" button for the question
4. Select any column
5. Select "Go to a custom destination"
6. Click "Link to" > "Saved question" button
7. Choose any question

### Expected behavior

Selected question's name is displayed in "Link to" button.

Probably it should already be displayed in step 4 - not sure.

### Information about your Metabase installation
847bc00b37

### Severity

P2

### Additional context

Found when working on #17879

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/33192

### Description

This issue is a regression introduced by https://github.com/metabase/metabase/pull/30729. Since that PR landed, in some cases, if the entity Question's `getObject` is called. We'd get an instance of `metabase-lib/Question` object.

And in this particular setup when using `Entity.Name` we would get a metabase lib Question wrapped within EntityWrapper that's why I think we need to conditionally read the name.

### How to verify

Follow a repro from https://github.com/metabase/metabase/issues/33192. You could use any question, we just need a question with a name.

#### Before the fix
image

#### After the fix
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/entities/questions.js [hunk 1]
```diff
@@ -100,7 +100,14 @@ const Questions = createEntity({
   },
 
   objectSelectors: {
-    getName: question => question && question.name,
+    getName: question => {
+      // When a question is from `getObject`, it will be a `metabase-lib/Question` object wrapped in EntityWrapper.
+      if (question?._card) {
```
Comment (WiNloSt) [inline frontend/src/metabase/entities/questions.js:105]: Not sure if checking `_card` directly would make sense here.

Comment (ranquild) [reply frontend/src/metabase/entities/questions.js:105]: Maybe `question instanceof Question`?

Comment (WiNloSt) [reply frontend/src/metabase/entities/questions.js]: Fixed in https://github.com/metabase/metabase/pull/33432/commits/fc97f958d1dc46612beab96202135ee7b0327745

File: frontend/src/metabase/entities/containers/EntityName.tsx [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+
+export const EntityName = ({
+  entityType,
+  entityId,
+  property = "name",
+}: EntityNameProps) => {
+  // This is a special case for questions, because we're returning `metabase-lib/Question`
+  // from question entity's `getObject` in https://github.com/metabase/metabase/pull/30729.
+  // If we wrap it in `EntityWrapper`, we'd lose all properties from `metabase-lib/Question`.
+  if (entityType === "questions") {
```
Comment (WiNloSt) [inline frontend/src/metabase/entities/containers/EntityName.tsx:25]: The difference, in this case, is not passing `wrapped` i.e. not wrapping `metabase-lib/Question` object inside an `EntityWrapper`. This way we could call `question.displayName()` which will return the question name. Had we pass `wrapped` like other entities, we'd lose all functions from `metabase-lib/Question` and there wouldn be no way to access the question name unless we directly access `question._card.name` directly, which looks too hacky.

File: frontend/src/metabase/entities/containers/EntityName.unit.spec.tsx [hunk 3]
```diff
@@ -24,4 +24,23 @@ describe("EntityName", () => {
       expect(await screen.findByText("Testy Tableton")).toBeInTheDocument();
     });
   });
+
+  describe("questions", () => {
+    test("question with name (metabase#33192)", async () => {
```
Comment (WiNloSt) [inline frontend/src/metabase/entities/containers/EntityName.unit.spec.tsx:29]: This test was run against the `EntityName` before the fix and it failed as expected. The easiest way is to checkout `frontend/src/metabase/entities/containers/EntityName.unit.spec.tsx` from 00446edd488c7a1da4cd5056c69f1db3fe580222.

Otherwise, if you want to run this against the `EntityName` from master which would still be a jsx file, you'd need to modify the import back to default import as well.

**Review by ranquild — APPROVED** [review]
