### PR TITLE
don't apply parameter filters to object queries

### LINKED ISSUE #8055: Dashboard filter - drilldown to foreign keyed entity record fails
- Your browser and the version:  Chrome 49.0.2623.75 (64-bit) & Firefox 62.0b7 (64-bit)
- Your operating system: Ubuntu
- Your databases:  Postgres 9
- Metabase version: v0.29.3
- Metabase hosting environment: CentOS 6
- Metabase internal database: Postgres 9

- *Repeatable steps to reproduce the issue*

1. Create data source tables : 1. Sales table w/ ProductID column & Customer ID column FK'd to  2. Customer table
2. Define Entity ID  for each table and define FK relationship in Metabase datamodel
3. Create question using Sale Table grouping by customer id and reporting count(sales)
4. Embed in dashboard
5. Add Product filter to dashboard
6. Add customer filter to dashboard
7. Save dashboard
8. Set values for both filters
9. Click on "Customer ID" in table and select "View Details"
10. Throws error: **Query expansion failed: could not find table 149 (FK ID = 1507). Resolved tables ([fk-id table-id]): ([nil 151])**
11. Remove ProductID from filter - refresh - customer details displays

It appears when drilling down to view the details of an entity displayed in the dashboard, it applies all the filters irrespective of whether the associated column exists for that entity

-------
:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #15331: Dashboard drill-through fails to any Object Detail, when filtered by explicit joined column
**Describe the bug**
When a dashboard filter is connected to a question's explicit joined column, then drill-through to any Object Details (PK/FK) fails.

**To Reproduce**
1. Custom question > Sample Dataset > Orders and join Products, save as "Q1"
image
2. Add to dashboard, and add a Time:AllOptions and connect to "Q1" explicit joined column `Products.Created At`
3. Set filter value to last 30 years and click any of the PK/FK columns to go to Object Detail
image
4. Query fails with errors like `Column "Products__CREATED_AT" not found;` or `Invalid column name 'Products__CREATED_AT'` or similar depending on database type
image

<details><summary>Full stacktrace</summary>

```
2021-03-25 12:40:22,858 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2021-03-25T12:40:22.398925+01:00[Europe/Copenhagen]",
 :state "42S22",
 :json_query
 {:database 4,
  :type "query",
  :query
  {:source-table 10,
   :filter
   ["and" ["=" ["field-id" 105] 14] ["time-interval" ["joined-field" "Products" ["field-id" 108]] -30 "year"]]},
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\", \"PUBLIC\".\"PRODUCTS\".\"EAN\" AS \"EAN\", \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\", \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\", \"PUBLIC\".\"PRODUCTS\".\"VENDOR\" AS \"VENDOR\", \"PUBLIC\".\"PRODUCTS\".\"PRICE\" AS \"PRICE\", \"PUBLIC\".\"PRODUCTS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"PRODUCTS\".\"CREATED_AT\" AS \"CREATED_AT\" FROM \"PUBLIC\".\"PRODUCTS\" WHERE (\"PUBLIC\".\"PRODUCTS\".\"ID\" = 14 AND parsedatetime(year(\"Products__CREATED_AT\"), 'yyyy') BETWEEN parsedatetime(year(dateadd('year', CAST(-30 AS long), now())), 'yyyy') AND parsedatetime(year(dateadd('year', CAST(-1 AS long), now())), 'yyyy')) LIMIT 2000",
  :params nil},
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)"
  "org.h2.expression.Function.optimize(Function.java:2131)"
  "org.h2.expression.Function.optimize(Function.java:2131)"
  "org.h2.expression.Comparison.optimize(Comparison.java:179)"
  "org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:130)"
  "org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:131)"
  "org.h2.command.dml.Select.prepare(Select.java:861)"
  "org.h2.command.Parser.prepareCommand(Parser.java:283)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)"
  "org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1135)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:267)"
  "--> driver.sql_jdbc.execute$fn__77603.invokeStatic(execute.clj:237)"
  "driver.sql_jdbc.execute$fn__77603.invoke(execute.clj:235)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:255)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:252)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:388)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:375)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:384)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:375)"
  "driver.sql_jdbc$fn__79191.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__79191.invoke(sql_jdbc.clj:52)"
  "driver.h2$fn__77995.invokeStatic(h2.clj:81)"
  "driver.h2$fn__77995.invoke(h2.clj:78)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46455.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__45707.invoke(check_features.clj:41)"
  "query_processor.middleware.limit$limit$fn__46441.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__45365.invoke(cache.clj:211)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46620.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44511.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40828.invoke(wrap_value_literals.clj:147)"
  "query_processor.middleware.annotate$add_column_info$fn__40691.invoke(annotate.clj:582)"
  "query_processor.middleware.permissions$check_query_permissions$fn__45582.invoke(permissions.clj:75)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__47143.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45780.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47456.invoke(resolve_joined_fields.clj:94)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__47761.invoke(resolve_joins.clj:178)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44105.invoke(add_implicit_joins.clj:181)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__46416.invoke(large_int_id.clj:44)"
  "query_processor.middleware.format_rows$format_rows$fn__46396.invoke(format_rows.clj:74)"
  "query_processor.middleware.desugar$desugar$fn__45846.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__44871.invoke(binning.clj:228)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__45389.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__43735.invoke(add_dimension_projections.clj:316)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43966.invoke(add_implicit_clauses.clj:146)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48191.invoke(upgrade_field_literals.clj:45)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44258.invoke(add_source_metadata.clj:122)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47340.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44458.invoke(auto_bucket_datetimes.clj:139)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45436.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__47125.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45488.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__46102.invoke(expand_macros.clj:155)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44267.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48127.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351$fn__47355.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47351.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46342.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__48136$fn__48137.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__48136.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__48198.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__46468.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44123.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48112.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__45723.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__47214.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__45666.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___37431$thunk__37432.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___37431.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___37440$fn__37443.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___37440.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:237)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:233)"
  "query_processor$fn__48244$process_query_and_save_execution_BANG___48253$fn__48256.invoke(query_processor.clj:249)"
  "query_processor$fn__48244$process_query_and_save_execution_BANG___48253.invoke(query_processor.clj:241)"
  "query_processor$fn__48288$process_query_and_save_with_max_results_constraints_BANG___48297$fn__48300.invoke(query_processor.clj:261)"
  "query_processor$fn__48288$process_query_and_save_with_max_results_constraints_BANG___48297.invoke(query_processor.clj:254)"
  "api.dataset$run_query_async$fn__54402.invoke(dataset.clj:56)"
  "query_processor.streaming$streaming_response_STAR_$fn__54381$fn__54382.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__54381.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__16058.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error
 "Column \"Products__CREATED_AT\" not found; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 80d477f41c974e3c001ec25e90a3c52f3f6e39b374eec4a0ff2d3b941bb61a7a\nSELECT \"PUBLIC\".\"PRODUCTS\".\"ID\" AS \"ID\", \"PUBLIC\".\"PRODUCTS\".\"EAN\" AS \"EAN\", \"PUBLIC\".\"PRODUCTS\".\"TITLE\" AS \"TITLE\", \"PUBLIC\".\"PRODUCTS\".\"CATEGORY\" AS \"CATEGORY\", \"PUBLIC\".\"PRODUCTS\".\"VENDOR\" AS \"VENDOR\", \"PUBLIC\".\"PRODUCTS\".\"PRICE\" AS \"PRICE\", \"PUBLIC\".\"PRODUCTS\".\"RATING\" AS \"RATING\", \"PUBLIC\".\"PRODUCTS\".\"CREATED_AT\" AS \"CREATED_AT\" FROM \"PUBLIC\".\"PRODUCTS\" WHERE (\"PUBLIC\".\"PRODUCTS\".\"ID\" = 14 AND parsedatetime(year(\"Products__CREATED_AT\"), 'yyyy') BETWEEN parsedatetime(year(dateadd('year', CAST(-30 AS long), now())), 'yyyy') AND parsedatetime(year(dateadd('year', CAST(-1 AS long), now())), 'yyyy')) LIMIT 2000 [42122-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 4,
  :type :query,
  :query
  {:source-table 10,
   :filter
   [:and
    [:=
     [:field-id 105]
     [:value 14 {:base_type :type/BigInteger, :special_type :type/PK, :database_type "BIGINT", :name "ID"}]]
    [:between
     [:datetime-field [:joined-field "Products" [:field-id 108]] :year]
     [:relative-datetime -30 :year]
     [:relative-datetime -1 :year]]],
   :fields
   [[:field-id 105]
    [:field-id 102]
    [:field-id 106]
    [:field-id 107]
    [:field-id 109]
    [:field-id 104]
    [:field-id 103]
    [:datetime-field [:field-id 108] :default]],
   :limit 2000},
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash
   [-128, -44, 119, -12, 28, -105, 78, 60, 0, 30, -62, 94, -112, -93, -59, 47, 63, 110, 57, -77, 116, -18, -60, -96,
    -1, 45, 59, -108, 27, -74, 26, 122]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

2021-03-25 12:40:22,862 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 470.0 ms (18 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (3 idle, 0 queued) (101 total active threads) Queries in flight: 0 (0 queued)
```

</details>

**Information about your Metabase Installation:**
Tested 0.36.8 thru 0.38.2 and `master`

**Additional context**
Very related to #8055

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #15331
Fixes #8055 

Added logic to stop applying parameter filters to queries where we'll be navigating to a details view. The param filters break the query.

vid of the fix:

https://user-images.githubusercontent.com/13057258/122285075-1dce9100-cea3-11eb-95f4-eff80f6298d1.mov

### CODE REVIEW

File: frontend/src/metabase/lib/urls.js [hunk 1]
```diff
@@ -49,6 +49,10 @@ export function question(card, hash = "", query = "") {
   return `${path}${query}${hash}`;
 }
 
+export function serializedQuestion(card) {
+  return question(null, card);
+}
+
```
Comment (gusaiani) [inline frontend/src/metabase/lib/urls.js:55]: I just realized this file uses both major ways of declaring functions.

May be nice if FE team picks one way.

Fwiw, my personal preference would be fat arrow, with an implicit return in this case.
Small.

```suggestion
export const serializedQuestion = card => 
  question(null, card);
```

**Review by gusaiani — APPROVED** [review]
Working well now 🏆 

Minor comment inlined.

At this stage, I can't imagine possible side effects or other potential issues this fix may introduce. Probably nice if others take a look as well.

File: frontend/src/metabase/lib/urls.js (hunk 1 above)
Comment (gusaiani) [reply frontend/src/metabase/lib/urls.js:55]: We may want to introduce a typical naming convention for "static" consts and functions.

If function, we always start the name with a verb.

So it may typically look like this (imaginary situation):

```js
  const serializedQuestion = getSerializedQuestion(args)
  
  const getSerializedQuestion = args => { … }
```

when used consistently, it reveals intent that much faster.

Comment (ariya) [reply frontend/src/metabase/lib/urls.js:55]: Maintaining consistency is good, but let's spawn the discussion to a separate thread/issue.
Bug fixing needs to focus on the smallest amount of code change that solves the problem.

Comment (gusaiani) [reply frontend/src/metabase/lib/urls.js:55]: > Maintaining consistency is good, but let's spawn the discussion to a separate thread/issue.
> Bug fixing needs to focus on the smallest amount of code change that solves the problem.

Sure. Comment was meant for the future. 
So far I've been leaving approvals (when applicable of course) with occasional minor comments like this, definitely non-blocking.
