### PR TITLE
Fix initialization status and health endpoint issues

### LINKED ISSUE #4570: Return a sensible status message on /api/health while starting up
Especially when waiting on migrations, we should let the user know something is happening. Right now there's no real way to distinguish between a dead instance and one that is migrating itself.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #4570 (both parts)

### CODE REVIEW

File: src/metabase/routes.clj [hunk 1]
```diff
@@ -40,9 +41,17 @@
...
-  ; ^/app/ -> static files under frontend_client/app
+  ;; ^/api/health -> Health Check Endpoint
+  (GET "/api/health" [] (if (init-status/complete?)
+                          {:status 200, :body {:status "ok"}}
+                          {:status 503, :body {:status "initializing", :progress (init-status/progress)}}))
+  ;; ^/api/ -> All other API routes
+  (context "/api" [] (fn [& args]
+                       ;; if Metabase is not finished initializing, return a generic error message rather than something potentially confusing like "DB is not set up"
+                       (if-not (init-status/complete?)
+                         {:status 400, :body "Metabase is still initializing. Please sit tight..."}
```
Comment (spencerhakim) [inline src/metabase/routes.clj]: This should probably return 503 like `/api/health`. A 4xx client error seems inappropriate.

Comment (camsaul) [inline src/metabase/routes.clj]: good point
