### PR TITLE
Make Database details NOT NULL; add defaults for Database created_at and updated_at

### LINKED ISSUE #25658: When accessing the database page from a database loaded from serialization without all details, the page is blank
**To reproduce**
1. Create a fresh instance and log-in for the first time (create the admin)
2. Clone https://github.com/metabase/serialization-playground
3. Load the dump to the fresh instance
4. Access the `Sample Postgres` page in the database page

As the serialized version of the database misses some properties (like the connection details), something is failing in the frontend.

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #25658

We've long validated Database `details` in the REST API layer; it was probably an oversight that we never made it required in the application database schema itself. This PR sets changes all `NULL` `details` to `{}` and then adds a `NOT NULL` constraint to the column. Because older MySQL won't let us have nice things, [we cannot add a default value to `text` columns](https://dev.mysql.com/doc/refman/5.7/en/blob.html), so instead I am simulating a default value in Toucan `pre-insert`.

Note that in regular usage you still shouldn't be able to create a Database with invalid details, but in SerDes v2 it's possible to load a Database without including details -- see #25658.

While I was at it I also went ahead and added default values for Database `created_at` and `updated_at` -- we were previously simulating them in Toucan but it's probably better to do this in the application database itself where we can because it facilitates non-Toucan usage of the app DB, for example scripting or writing schema migration tests.

### CODE REVIEW

File: test/metabase/db/schema_migrations_test.clj [hunk 1]
```diff
@@ -668,3 +669,14 @@
                                                            :group_id (all-users-group-id)}]})
                               (migrate!)
                               (is (= ["All Users"] (get-perms))))))))
+
+(deftest make-database-details-not-null-test
+  (testing "Migrations v45.00-042 and v45.00-043: set default value of '{}' for Database rows with NULL details"
+    (impl/test-migrations ["v45.00-042" "v45.00-043"] [migrate!]
```
Comment (escherize) [inline test/metabase/db/schema_migrations_test.clj:675]: Handy macro

**Review by escherize — APPROVED** [review]
