### PR TITLE
Use source alias for breakout with implicit join

### LINKED ISSUE #67002: Questions with joined models fail with invalid SQL after v57 upgrade
### Describe the bug

After upgrading from v 56 to v57, some queries that used to work are now failing with a 
`"ERROR: column source. Table Name - Column__name_ef701e16 does not exist Position: 249"`

These questions used to work well before upgrade.

The bug seems to be on queries with a combination of Join and Summarize.
- When I do a join between two tables
- Then a first Summarize that select columns from both tables
- And in the final summarize, i cannot select the column from the second table (after the first left join) !!

### To Reproduce

I cannot reproduce on a healthy environment

### Expected behavior

The queries with joins and summarize work as they worked before

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-12-12",
      "tag": "v0.57.6.2",
      "hash": "07f85e3"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.9+10-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.9+10-LTS",
    "os.name": "Linux",
    "os.version": "4.14.322-244.536.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Blocking ! A lot of our dashboards are impacted

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
### Description

Closes https://github.com/metabase/metabase/issues/67002

The problem is that we are using the desired alias in `update-keys-for-col-from-previous-stage` rather than the source alias. This is usually okay with because we alias the table and the fields in a join. But for an implicit join we use the actual DB table so we should still be using the source alias. 

Implicit join:
```sql
SELECT
  "test_long_name_2__via__fk"."big_column_big_column_big_column_big_column_big_col_57ae87d0" AS "test_long_name_2__via__fk__big_column_big_column_bi_09ae9150"
FROM
  "public"."test_long_name"
  LEFT JOIN "public"."test_long_name_2" AS "test_long_name_2__via__fk" ON "public"."test_long_name"."fk" = "test_long_name_2__via__fk"."id"
GROUP BY
  "test_long_name_2__via__fk"."big_column_big_column_big_column_big_column_big_col_57ae87d0"
ORDER BY
  "test_long_name_2__via__fk"."big_column_big_column_big_column_big_column_big_col_57ae87d0" ASC
LIMIT
  1048575
```
Explicit join:
```sql
SELECT
  "Test Long Name 2 - Fk"."big_column_big_column_big_column_big_column_big_col_57ae87d0" AS "Test Long Name 2 - Fk__big_column_big_column_big_co_807b163a"
FROM
  "public"."test_long_name"
  LEFT JOIN (
    SELECT
      "public"."test_long_name_2"."id" AS "id",
      "public"."test_long_name_2"."big_column_big_column_big_column_big_column_big_column_big_colu" AS "big_column_big_column_big_column_big_column_big_col_57ae87d0"
    FROM
      "public"."test_long_name_2"
  ) AS "Test Long Name 2 - Fk" ON "public"."test_long_name"."fk" = "Test Long Name 2 - Fk"."id"
GROUP BY
  "Test Long Name 2 - Fk"."big_column_big_column_big_column_big_column_big_col_57ae87d0"
ORDER BY
  "Test Long Name 2 - Fk"."big_column_big_column_big_column_big_column_big_col_57ae87d0" ASC
LIMIT
  1048575
```

Note that in the implicit join we haven't defined `big_column_big_column_big_column_big_column_big_col_57ae87d0` anywhere whereas in the explicit join we do in the join subquery. 

### How to verify

1. Follow the repro steps in the comments of the original issue
2. It should run the query
3. Run the test and it should pass

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by MarieSophieRichard** [comment]
@rileythomp Hello ! DO you have any update on this PR ? Do you have an estimate date of resolution ?

**Review by metamben — APPROVED** [review]

File: test/metabase/query_processor/implicit_joins_test.clj [hunk 1]
```diff
@@ -225,3 +229,54 @@
...
+
+(deftest long-col-name-repro-test
+  (testing "Implicit join with long column name should use actual DB column name as source alias (#67002)"
+    (mt/test-drivers (mt/normal-drivers-with-feature :left-join)
+      (mt/dataset long-col-name-dataset
+        (let [fk-field (mt/id :long_col_name :fk)
+              id-2-field (mt/id :long_col_name_2 :id)]
+          (t2/update! :model/Field fk-field {:semantic_type :type/FK
+                                             :fk_target_field_id id-2-field})
+          (testing "Implicit join with long column name should use actual DB column name as source alias (#67002)"
```
Comment (bshepherdson) [inline test/metabase/query_processor/implicit_joins_test.clj]: Duplicated `testing` text here.

File: test/metabase/query_processor/implicit_joins_test.clj [hunk 2]
```diff
@@ -225,3 +229,54 @@
...
+                  table (lib.metadata/table mp (mt/id :long_col_name))
+                  query (lib/query mp table)
+                  breakoutable-cols (lib/breakoutable-columns query)
+                  fk-col (m/find-first (fn [col]
+                                         (and (:fk-field-id col)
+                                              (str/starts-with? (:name col) "big_column")))
+                                       breakoutable-cols)
+                  query (-> query
+                            (lib/breakout fk-col))]
+              (is (= [["b"]] (mt/rows (qp/process-query query))))))
```
Comment (bshepherdson) [inline test/metabase/query_processor/implicit_joins_test.clj]: I don't think there's enough rows in the dataset to really check that this is working properly.

This is not distinguishable from returning all of the second table. There should be multiple rows in each table, and they should cover the interesting cases:

- A1 points to B1
- A2 points to B2
- A3 points to B2 - multiple FKs to the same target.
- B3 has no incoming FKs.

Then this test should be returning B1 and B2 (deduplicated because breakouts), but not B3.

**Review by bshepherdson — CHANGES_REQUESTED** [review]

**Review by bshepherdson — APPROVED** [review]
