### PR TITLE
Fix - Admin Email does not Display on Question Timeout Page

### LINKED ISSUE #42929: Admin Email does not Display on Question Timeout Page
### Describe the bug

When a question times out you're presented with the messaging "Your Question Took Too Long". Below that the admin email address is included. The admin email is not displaying.

### To Reproduce

1. I just made a big test table in Postgres:

CREATE TABLE large_table (
    id SERIAL PRIMARY KEY,
    data1 INT,
    data2 INT,
    data3 TEXT
);

-- Insert a large number of rows into the table
INSERT INTO large_table (data1, data2, data3)
SELECT
    (random() * 1000000)::int,
    (random() * 1000000)::int,
    md5(random()::text)
FROM generate_series(1, 10000000);

2. Executed this SQL Query on the DB a few times and then added it to Metabase as a native SQL question:

SELECT
    t1.id,
    t1.data1,
    t1.data2,
    AVG(t2.data1) AS avg_data1,
    COUNT(t2.id) AS count_data2
FROM
    large_table t1
JOIN
    large_table t2 ON t1.data1 = t2.data2
GROUP BY
    t1.id, t1.data1, t1.data2
HAVING
    COUNT(t2.id) > 10
ORDER BY
    avg_data1 DESC;
    
    
    3. Eventually it times out and we get:
    
admin_email

### Expected behavior

We should see the admin email address

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-09",
      "tag": "v1.49.9",
      "hash": "c0913c7"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #42929

### Description

Simple fix, encountered during triage.

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/VisualizationError/VisualizationError.tsx [hunk 1]
```diff
@@ -25,19 +24,9 @@ import {
...
 } from "./VisualizationError.styled";
+import { AdminEmail } from "./components";
 import { adjustPositions, stripRemarks } from "./utils";
 
-function EmailAdmin(): JSX.Element | null {
-  const hasAdminEmail = isNotNull(MetabaseSettings.adminEmail());
-  return hasAdminEmail ? (
-    <span className={QueryBuilderS.QueryErrorAdminEmail}>
-      <a className={CS.noDecoration} href={`mailto:${hasAdminEmail}`}>
-        {hasAdminEmail}
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/VisualizationError/VisualizationError.tsx:35]: The bug was that a boolean was used instead of a string, I think someone confused `isNotNull` with `checkNotNull`.

**Review by uladzimirdev — APPROVED** [review]
