### PR TITLE
Restore foreign key support for Mongo

### LINKED ISSUE #44511: v50: Foreign keys no longer work with MongoDB
### Describe the bug

Questions that leverage foreign keys are no longer working as of Metabase 50, but were working well in Metabase 49.

### To Reproduce

Repro steps:
- create two collections
  - collectionA: `{ _id: ObjectId, bID: ObjectId, value: string }`
  - collectionB: `{ _id: ObjectId, value: string }`
- in metabase admin, set `collectionA.bID` as a foreign key to `collectionB._id`
- ask a new question: count of rows for collectionA where collectionB.value == 'foo'

### Expected behavior

This worked well in Metabase 49, but regressed in Metabase 50. It would answer the question.

Now I'm getting: `:mongo driver does not support foreign keys.`

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9-LTS",
    "os.name": "Linux",
    "os.version": "4.14.109-99.92.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v0.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

pretty darn significant for mongodb users

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes #44511

### Description

Probably as part of `driver/supports?` refactor, Mongo foreign key support was removed, instead of transformation to `driver/database-supports?`. Back then support for foreign keys was disabled during testing, hence no tests for eg. implicit joins ran.

This PR restores previous state, apart from conversion to `database-supports?`. Implicit joins were tested manually. Aim of this PR is to return driver to pre-regression state. Automated testing should be carried out as follow up, as required change is non-trivial.

Specifically, my belief is that implicit joins should be decoupled from `:foreign-keys` database feature, because foreign key relationships can be defined in Metabase independently from underlying database support (reproduction from the issue as an example).

If implicit joins are enabled should rather depend on `:joins` database feature. Application should not care if `fk_target_field_id` of `metabase_field` was obtained by sync or was defined by user.

Then, for implicit joins tests to pass, for databases that do not support foreign keys relationships, hence auto detection during sync is not available, `get-or-create-database` post sync hook can be created and relationships could be added to application database based on clojure side examination of test data table definitions.

Stub of described approach can be found in [`tx-post-sync-hook`](https://github.com/metabase/metabase/tree/tx-post-sync-hook) branch. Reason, this PR does not contained proposed change is that some tests fail due to ordering differences. My suspicion is that there is another issue with ordering, that is out of scope of pre-regression state restoration.

Finally, the issue https://github.com/metabase/metabase/issues/44573 was opened to track automated testing for Mongo implicit joins.

### How to verify

Manually, until the issue is not addressed.

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo.clj [hunk 1]
```diff
@@ -303,6 +303,14 @@
   [_driver _feature _db]
   true)
 
+;; We say Mongo supports foreign keys so that the front end can use implicit
+;; joins. In reality, Mongo doesn't support foreign keys.
+;; Only define an implementation for `:foreign-keys` if none exists already.
+;; In test extensions we define an alternate implementation, and we don't want
+;; to stomp over that if it was loaded already.
+(when-not (get (methods driver/database-supports?) [:mongo :foreign-keys])
+  (defmethod driver/database-supports? [:mongo :foreign-keys] [_driver _feature _db] true))
```
Comment (camsaul) [inline modules/drivers/mongo/src/metabase/driver/mongo.clj:312]: This kinda seems backwards, MongoDB really doesn't have foreign keys, I think the right way to fix this is just to remove the restriction that a database needs to support `:foreign-keys` for the FE to be able to use implicit joins. As long as someone manually marks an FK relationship and the driver supports joins they should be able to use it.

BigQuery is in the same boat so if you fix it generally then we'd be solving things for BigQuery too at the same time

Comment (camsaul) [reply modules/drivers/mongo/src/metabase/driver/mongo.clj:312]: Otherwise we should just remove `:foreign-keys` altogether because it would stop meaning anything if we're enabling it even for drivers that don't have FKs

**Review by camsaul — CHANGES_REQUESTED** [review]
Let's just remove the restriction that a driver needs to have `:foreign-keys` to use implicit joins from the FE/MLv2 instead of making `:foreign-keys` basically meaningless and something we need to set to `true` for every driver regardless of FK support. Then we'd fix this same issue for BigQuery at the same time.

**Comment by lbrdnk** [comment]
As per review feedback, closing in favor of https://github.com/metabase/metabase/pull/44894.

**Comment by lbrdnk** [comment]
Re-opening as per further discussion. Let's just re-enable fks support on Mongo the old way first. And do the right thing (complete removal of foreign keys) merging https://github.com/metabase/metabase/pull/44894 into master for next major.

**Review by camsaul — APPROVED** [review]
Let's get this merged in so the fix goes out in the next 50 patch release, then we can merge in your bigger PR without having to worry about backporting it
