### PR TITLE
Share pivot export code between XSLX/CSV instead of using native Excel pivots

### LINKED ISSUE #54497: Min, Max, Average, Distinct values are aggregated as Sum for subtotals and grand total in the xlsx export
### Describe the bug

Breakout from https://github.com/metabase/metabase/issues/51786

### To Reproduce

1. Create a pivot
Image

2. Visualize

Image

3. Download as xlsx, keep the data pivoted
Image

Issues:
* The Min, Max and Average and Distinct aggregations are computed as sum() in the Excel, resulting in incorrect subtotals and grand totals

### Expected behavior

The exports should have the same values for subtotals and totals

### Logs

_No response_

### Information about your Metabase installation

```JSON
Master
```

### Severity

P2

### Additional context

_No response_

### LINKED ISSUE #54498: Formatting issues in the xlsx export
### Describe the bug

Breakout from https://github.com/metabase/metabase/issues/51786

### To Reproduce

1. Create a pivot
Image

2. Visualize

Image

3. Download as xlsx, keep the data pivoted
Image

Issues:
* Column title for each metric is 'Sum'
* Numeric formatting is different (number of decimals, thousands separator)
* A (blank) row is present

### Expected behavior

Similar formatting as the original pivot table.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Master
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Removes our prior approach for pivoted XLSX exports, which was trying to generate native Excel PivotTables but had many correctness issues due to Excel limitations. Switches instead to generating the pivoted shape in-memory as we do for CSVs and then writing it to the XLSX workbook directly.

We're still leveraging Excel's native formatting using format codes. The XLSX export code generates custom formatters (in `make-formatters`) which annotate the raw values with their format codes, and these are passed into the pivot namespace instead of the normal value formatters.

Fixes https://github.com/metabase/metabase/issues/54498
Fixes https://github.com/metabase/metabase/issues/54497

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#56622** <a href="https://app.graphite.dev/github/pr/metabase/metabase/56622?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/metabase/metabase/56622?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: src/metabase/query_processor/pivot/postprocess.clj [hunk 1]
```diff
@@ -93,29 +91,6 @@
         (get col-settings {::mb.viz/column-name (:name col)})))
      cols)))
 
-(defn- get-formatter
```
Comment (noahmoss) [inline src/metabase/query_processor/pivot/postprocess.clj:96]: Moved this code to the CSV namespace

File: src/metabase/query_processor/streaming/csv.clj [hunk 2]
```diff
@@ -58,74 +59,99 @@
...
+                {:keys [pivot-rows pivot-cols pivot-measures]} pivot-export-options
+                columns (pivot/columns-without-pivot-group (:cols data))
+                formatters (make-formatters columns pivot-rows pivot-cols pivot-measures settings timezone format-rows?)
+                output (qp.pivot.postprocess/build-pivot-output
+                        (update-in @pivot-data [:data :rows] persistent!)
+                        formatters)]
             (doseq [xf-row output]
               (write-csv writer [xf-row]))))
-        (.flush writer)
-        (.flush os)
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming/csv.clj:130]: Removed these flushes since they seem to be redundant — closing the writer flushes it (and the underlying stream)

File: src/metabase/query_processor/streaming/csv.clj [hunk 3]
```diff
@@ -58,74 +59,99 @@
...
-        (when (and (contains? @pivot-data :data) @pivoted-export?)
-          (let [output (qp.pivot.postprocess/build-pivot-output (assoc-in @pivot-data [:data :rows] @pivot-rows))]
+        (when (and (contains? @pivot-data :data) enable-pivoted-exports?)
+          (let [{:keys [data settings timezone format-rows? pivot-export-options]} @pivot-data
+                {:keys [pivot-rows pivot-cols pivot-measures]} pivot-export-options
+                columns (pivot/columns-without-pivot-group (:cols data))
+                formatters (make-formatters columns pivot-rows pivot-cols pivot-measures settings timezone format-rows?)
+                output (qp.pivot.postprocess/build-pivot-output
+                        (update-in @pivot-data [:data :rows] persistent!)
+                        formatters)]
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming/csv.clj:154]: Here's the core of the new pivot export logic, reusing `build-pivot-output`

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 4]
```diff
@@ -573,164 +606,140 @@
...
+    {:cell-styles (compute-column-cell-styles workbook data-format viz-settings non-pivot-cols format-rows?)
+     :typed-cell-styles (compute-typed-cell-styles workbook data-format)}))
 
 (defmethod qp.si/streaming-results-writer :xlsx
   [_ ^OutputStream os]
-  (let [workbook-data      (volatile! nil)
-        cell-styles        (volatile! nil)
-        typed-cell-styles  (volatile! nil)
-        pivot-grouping-idx (volatile! nil)]
+  (let [workbook             (SXSSFWorkbook.)
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming/xlsx.clj:652]: There's a fairly large restructuring that I'll do my best to clarify:

If we want column auto-sizing to work for pivots, we need to manually track each column in the workbook before we add data to it. But we only know how many columns there will be after we've built up the pivot data structure. 

So, we need to move the _entire_ workbook creation process into `finish!` for pivot tables, after results have been accumulated in memory, rather than initializing the workbook in `begin!` and writing result rows one at a time like we do for non-pivots.

Therefore, I'm initializing the workbook here, and I've changed `init-workbook` (which tracks columns for auto-sizing) to take it as an input. We call `init-workbook` in `finish!` for pivot tables, and in `begin!` for non-pivots. I think this simplifies the code a bit and enables auto-sizing to work correctly.

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 5]
```diff
@@ -519,6 +528,30 @@
...
+        (let [{:keys [col-settings col styles value]}
+              (if (map? cell-data)
+                cell-data
+                ;; Fallback: assume it's just a value, no metadata
+                {:value cell-data
+                 :col   {}})
+              ^Cell cell   (.createCell excel-row ^Integer col-idx)
+              id-or-name   (or (:id col) (:name col))
+              settings     (or (get col-settings {::mb.viz/field-id id-or-name})
+                               (get col-settings {::mb.viz/column-name id-or-name}))
```
Comment (tsplude) [inline src/metabase/query_processor/streaming/xlsx.clj:546]: Should this be `merge`? What happens if there's a scale value set in admin settings -> table metadata -> column formatting and also a user defined column scale on the question?

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 6]
```diff
@@ -573,164 +606,140 @@
...
-  [{:keys [ordered-cols col-settings format-rows?]}]
-  (let [workbook (SXSSFWorkbook.)
-        sheet    (spreadsheet/add-sheet! workbook (tru "Query result"))]
-    (doseq [i (range (count ordered-cols))]
-      (.trackColumnForAutoSizing ^SXSSFSheet sheet i))
-    (setup-header-row! sheet (count ordered-cols))
-    (spreadsheet/add-row! sheet (streaming.common/column-titles ordered-cols col-settings format-rows?))
-    {:workbook workbook
-     :sheet    sheet}))
+  "Iniitalizes the provided workbook, and returns the created sheet"
```
Comment (tsplude) [inline src/metabase/query_processor/streaming/xlsx.clj:617]: nit typo

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 7]
```diff
@@ -573,164 +606,140 @@
...
-          (when (or (nil? row_count) (< row_count *auto-sizing-threshold*))
-            ;; Auto-size columns if we never hit the row threshold, or a final row count was not provided
-            (autosize-columns! sheet))
-          (try
-            (spreadsheet/save-workbook-into-stream! os workbook)
-            (finally
-              (.dispose ^SXSSFWorkbook workbook)
-              (.close os))))))))
+        (when @pivot-data
+          ;; For pivoted exports, we pivot in-memory lsame as CSVs) and then write the results to the
```
Comment (tsplude) [inline src/metabase/query_processor/streaming/xlsx.clj:711]: nit typo

**Review by tsplude — APPROVED** [review]
Seems good to me, curious about the `id-or-name` column settings question though

File: src/metabase/query_processor/streaming/xlsx.clj (hunk 5 above)
Comment (noahmoss) [reply src/metabase/query_processor/streaming/xlsx.clj:546]: Good call, we should use `streaming.common/viz-settings-for-col` instead. I've updated this spot and a couple others in this namespace
