### PR TITLE
Use question from state for navbar instead of api call

### LINKED ISSUE #31905: Duplicate requests to /api/card from Query Builder
### Describe the bug

Regression between 45 and 46.

The query builder makes 2 identical request to GET `/api/card/{id}` on load.

Screen Shot 2023-06-27 at 9 58 23 AM

### To Reproduce

- Make any question or model
- open the network inspector
- refresh the page
- see 2 of the same GET request

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "18.0.1+0",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "18.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "18.0.1+0",
    "os.name": "Mac OS X",
    "os.version": "12.4",
    "user.language": "en",
    "user.timezone": "America/Denver"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-14",
      "tag": "v0.46.5",
      "branch": "release-x.46.x",
      "hash": "272e3e6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

not user visible, an under-the-hood performance issue

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deniskaber**
Closes https://github.com/metabase/metabase/issues/31905

### Description

This removes arbitrary card reload in QueryBuilder.
Also: improves our entities fetch caching by waiting for a loading query with same parameters. This leads to deduplication of the same api requests.

### How to verify

1. Create a new question or model, save it.
2. Refresh the page.
3. You should not see 2 same api requests to load your question/model.
4. You should see a collection where your question/model is saved to as selected in the left menu.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.tsx [hunk 1]
```diff
@@ -122,21 +110,7 @@ function MainNavbar({
...
-) {
-  const { pathname } = location;
-  const canFetchQuestion = isQuestionPath(pathname) || isModelPath(pathname);
-  return canFetchQuestion ? Urls.extractEntityId(params.slug) : null;
-}
-
 // eslint-disable-next-line import/no-default-export -- deprecated usage
-export default _.compose(
-  connect(mapStateToProps, mapDispatchToProps),
-  Questions.load({
```
Comment (ranquild) [inline frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.tsx:137]: This should have worked - if the question was properly cached by the entity framework. Could you investigate why it didn't work?

**Review by ranquild — CHANGES_REQUESTED** [review]
The solution creates an implicit dependency between the navbar and QB state which shouldn't exist. Please investigate why the caching doesn't work here

File: frontend/src/metabase/lib/card.js [hunk 2]
```diff
@@ -26,17 +26,38 @@ export function startNewCard(type, databaseId, tableId) {
 // TODO: move to redux
 export async function loadCard(cardId, { dispatch, getState }) {
   try {
-    await dispatch(Questions.actions.fetch({ id: cardId }, { reload: true }));
```
Comment (ranquild) [inline frontend/src/metabase/lib/card.js:29]: @deniskaber you should be able to pass required `properties` here. If they aren't present on the object that is found by ID, it would be re-fetched. Like here https://github.com/metabase/metabase/blob/1efa6c6f000cb4bd38065563176c35ea0027c865/frontend/src/metabase/nav/containers/CollectionBreadcrumbs/CollectionBreadcrumbs.tsx#L9

**Review by ranquild — COMMENTED** [review]
Inline comments

File: frontend/src/metabase/lib/redux/utils.js [hunk 3]
```diff
@@ -270,45 +271,55 @@ function withCachedData(
...
+          reload !== true &&
+          // reload if the query used to load an entity has changed even if it's already loaded
+          newQueryKey === queryKey
+        ) {
+          // and we have a non-error request state or have a list of properties that all exist on the object
+          if (loaded || hasRequestedProperties) {
+            return existingData;
+          } else if (loading) {
+            // wait for current loading request to be resolved
+            const result = await waitFor(
```
Comment (ranquild) [inline frontend/src/metabase/lib/redux/utils.js:309]: I'd rather follow our pattern with storing promises for the original request. Something like this https://github.com/metabase/metabase/blob/ca2059f34e505093b0c0987307a70f763e1c032d/frontend/src/metabase/query_builder/actions/querying.js#L267. What do you think? Alternatively we can store promises outside of redux.

**Review by ranquild — APPROVED** [review]
