### PR TITLE
Fix filter changes not updating the root query

### LINKED ISSUE #11957: Changing filters on Simple question drops aggregated filters
**Describe the bug**
When creating a Simple question with filters, summarized and grouped by, and adding an aggregated filter, then changing/adding/removing regular filters will drop aggregated filters.

**To Reproduce**
1. Simple question > Sample Dataset > Orders
2. Filter by CreatedAt=CurrentMonth
3. Summarize by Count-of-rows, grouped by CreatedAt:Day
4. Filter by Metric "# Count" <= 20
5.
   A. Modify the CreatedAt filter (i.e. CurrentYear) and it will drop the aggregated ("# Count") filter.
   B. Add/remove a non-aggregated filter and it will drop the aggregated ("# Count") filter.

**Screenshots**
Screencast-2020-02-22_14 32 57

**Information about your Metabase Installation:**
Metabase 0.34.2 and `master`

**Additional context**
This is the same as #11334, but for Simple instead of Notebook.
P2? since workaround is to use the Notebook editor, which will keep the filters.

### LINKED ISSUE #14193: Changing filters on Simple question drops anything after first aggregation
https://user-images.githubusercontent.com/4180027/103077841-0b595600-45ea-11eb-98ac-5c820fb57041.mp4

**To Reproduce**
Please, watch the video

**Expected behavior**
The number and content of columns will remain according to the original formulas

**Information about your Metabase Installation:**
Google Chrome 87.0.4280.88, (64 bit)
PostgreSQL 11.7 (Ubuntu 11.7-2.pgdg16.04+1)
Metabase 0.37.4

**Severity**
Users get confused and break reports.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/14193
Fixes https://github.com/metabase/metabase/issues/11957

The root issue is that `filter.query()` returns the query for that stage level, and not the root query.

How to test:
- Follow the steps from the referenced issues or 
- Run the unskipped cypress tests

### CODE REVIEW

File: frontend/src/metabase-lib/lib/queries/StructuredQuery.ts [hunk 1]
```diff
@@ -1743,6 +1742,10 @@ class NestedStructuredQuery extends StructuredQuery {
     );
   }
 
+  rootQuery(): StructuredQuery {
```
Comment (ranquild) [inline frontend/src/metabase-lib/lib/queries/StructuredQuery.ts:1745]: Basically the idea is to make `rootQuery` return a query with `source-query` updated if it was changed. Currently it doesn't work and returned an unmodified root query.

File: frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.tsx [hunk 2]
```diff
@@ -63,20 +63,20 @@ const BulkFilterModal = ({
   );
 
   const handleAddFilter = useCallback((filter: Filter) => {
-    setQuery(filter.add());
+    setQuery(filter.add().rootQuery());
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.tsx:66]: I see that we call `rootQuery` in some places in our app so this nested thing was kind of expected by the existing code, but we didn't know that when we were implementing the bulk filter modal.

**Review by akiselev — APPROVED** [review]
