### PR TITLE
Repro #43216 - Questions based on a custom SQL query aren't updated

### LINKED ISSUE #43216: Questions based on a custom SQL query aren't updated
### Describe the bug

When you modify a SQL question A and you have a question B that use A, if you have modified A, B does not receive the change until you completely rewrite the question with the metabase editor. (B is metabase editor, A is plain SQL)

### To Reproduce

1. create a sql question that returns fields A, B and C
2. create a metabase editor based question using the first one
3. modify the first one to add a field D
4. returns in the second question, try to select the field D -> you can't unless you reset the question

### Expected behavior

It should receive change without need to almost destroy the question and restart everything ... 

### Logs

_No response_

### Information about your Metabase installation

```JSON
- metabase version 0.49.12
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #43216

Stress test: https://github.com/metabase/metabase/actions/runs/9744857410

Repro video: https://github.com/metabase/metabase/assets/6830683/f17fb317-4147-414a-bcc3-927114b9b62e

Before: [image](https://github.com/metabase/metabase/assets/6830683/0538e328-80a8-4621-92f3-ebd96d4996a8)
Now: [image](https://github.com/metabase/metabase/assets/6830683/d17dabba-4f29-4d77-9a37-8d85584b1305)

### CODE REVIEW

File: e2e/support/helpers/e2e-command-palette-helpers.js [hunk 1]
```diff
@@ -1,12 +1,20 @@
 export const commandPalette = () => cy.findByTestId("command-palette");
+
```
Comment (kamilmielnik) [inline e2e/support/helpers/e2e-command-palette-helpers.js:2]: This file was not readable

**Review by ranquild — APPROVED** [review]
