### PR TITLE
Fixing broken Configure Slack links

### LINKED ISSUE #48751: Configure Slack link in Setup Channel modal
The Current "ChannelSetupModal" when you don't have any channels setup (slack/webhook/email) only shows 2 buttons, and the Slack button link is broken.

Image

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/48751
### Description
Currently in the app there are some "configure slack" links that are broken. This PR fixes those links, as well as adds webhooks to the "setup channels" modal for alerts

### How to verify

1. Have an instance with no channels setup (email/slack/webhooks)
2. Navigate to a question and open the share modal
3. Test that the links are not broken
4. Navigate to a dashboard and open the subscriptions side panel
5. Ensure that the setup slack link is not broken

### Demo
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/components/ChannelSetupMessage/ChannelSetupMessage.jsx [hunk 1]
```diff
@@ -27,7 +42,7 @@ export default class ChannelSetupMessage extends Component {
         <div>
           {channels.map(c => (
             <Link
-              to={"/admin/settings/" + c.toLowerCase()}
+              to={CHANNEL_MAP[c.toLowerCase()].link}
```
Comment (sloansparger) [inline frontend/src/metabase/components/ChannelSetupMessage/ChannelSetupMessage.jsx:45]: Can we add validation that `c.toLowerCase()` is a valid key in `CHANNEL_MAP`? Or at the very least make sure this is wrapped in an error boundary so that if we somehow get an invalid channel name we don't break the whole page?

**Review by sloansparger — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/components/ChannelSetupMessage/ChannelSetupMessage.jsx (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/components/ChannelSetupMessage/ChannelSetupMessage.jsx:45]: Fair enough haha

**Review by sloansparger — APPROVED** [review]
