### PR TITLE
fix: Sync postgres materialized view fields

### LINKED ISSUE #49912: We don't sync materialized views fields
### Describe the bug

At least in postgres we're not getting the fields for the materialized views so you can't query these

### To Reproduce

1) on postgres with the sample DB do 
```
CREATE MATERIALIZED VIEW orders_m as select * from orders
```
2) sync it
3) try to see the table via browse data

### Expected behavior

we should sync the fields in the same way you do on a normal view

### Logs

```
2024-11-12 22:25:04,114 INFO sync-metadata.tables :: Found new table: Table  ''public.orders_m''
2024-11-12 22:25:04,130 INFO sync-metadata.tables :: Updating table metadata for Table 28 ''public.accounts''
2024-11-12 22:25:04,133 INFO sync-metadata.tables :: Updating table metadata for Table 29 ''public.feedback''
2024-11-12 22:25:04,134 INFO sync-metadata.tables :: Updating table metadata for Table 22 ''public.products''
2024-11-12 22:25:04,136 INFO sync-metadata.tables :: Updating table metadata for Table 23 ''public.reviews''
2024-11-12 22:25:04,138 INFO sync-metadata.tables :: Updating table metadata for Table 25 ''public.invoices''
2024-11-12 22:25:04,140 INFO sync-metadata.tables :: Updating table metadata for Table 24 ''public.orders''
2024-11-12 22:25:04,142 INFO sync-metadata.tables :: Updating table metadata for Table 26 ''public.people''
2024-11-12 22:25:04,143 INFO sync-metadata.tables :: Updating table metadata for Table 27 ''public.analytic_events''
2024-11-12 22:25:04,145 INFO sync-metadata.tables :: Updating table metadata for Table 140 ''public.orders_m''
2024-11-12 22:25:04,146 INFO sync-metadata.tables :: :estimated_row_count of Table 140 ''public.orders_m'' changed from null to 18760
2024-11-12 22:25:04,153 INFO sync.util :: FINISHED: step ''sync-tables'' for postgres Database 2 ''pg'' (43.4 ms)
```

but there are no errors on the fields of the views

### Information about your Metabase installation

```JSON
v51.x
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snoe**
Fixes: #49912

### CODE REVIEW

File: test/metabase/driver/sql_jdbc/sync/describe_table_test.clj [hunk 1]
```diff
@@ -754,3 +754,53 @@
                         (sql.tx/create-index-sql driver/*driver* "conditional_index" ["column"] {:condition "id > 2"}))
          (is (= #{{:type :normal-column-index :value "id"}}
                 (describe-table-indexes (t2/select-one :model/Table (mt/id :conditional_index))))))))))
+
+(defmethod driver/database-supports? [::driver/driver ::materialized-view-fields]
+  [_driver _feature _database]
+  false)
```
Comment (metamben) [inline test/metabase/driver/sql_jdbc/sync/describe_table_test.clj:760]: Where is this used?

**Review by metamben — APPROVED** [review]
LGTM
