### PR TITLE
Handle named aggregations

### LINKED ISSUE #13022: Generating metrics description breaks for custom expressions
On working 0.36.0:
1. Admin > Data Model > Metric
2. Create new, table Sample Dataset > Orders, view Custom Expression `Sum([Discount] * [Quantity])`, save the metric
image
3. Refresh on Metric overview page, errors with `Unexpected input given to normalize. Expected type to be "object", found "string".`
image

_Originally posted by @flamber in https://github.com/metabase/metabase/issues/12982#issuecomment-664945290_

### PR DESCRIPTION
**Pull request by robdaemon**
Fixes an error generating query descriptions with named aggregations and
multiple parameters in a aggregation.

Resolves #13022

### CODE REVIEW

**Review by paulrosenzweig — APPROVED** [review]
Change looks good to me 👍 

Why did having an unhandled case trigger the weird behavior though? The `/api/metrics` endpoint still returned a 200, but the body was empty. Should we add some no-op general case? Or maybe ensure that an error is thrown?

File: src/metabase/api/query_description.clj [hunk 1]
```diff
@@ -14,13 +14,21 @@
 
 (defn- get-aggregation-description
   [metadata query]
-  (let [field-name (fn [match] (:display_name (Field (mbql.u/field-clause->id-or-literal match))))]
```
Comment (robdaemon) [inline src/metabase/api/query_description.clj:17]: @paulrosenzweig this was the actual issue - `match` here was more than one match. it was `[[:field-id 10] [:field-id 14]]`

I just handled extra cases as part of the fix.

File: src/metabase/api/query_description.clj [hunk 2]
```diff
@@ -14,13 +14,21 @@
...
+  (let [field-name (fn [match] (map
```
Comment (sbelak) [inline src/metabase/api/query_description.clj:17]: Why is this a local function? It doesn't seem to close over anything.

Also, since we're only interested in ids, it might be clearer to capture that explicitly:
```
(mbql.u/match match
  [:field-id id] (-> id Field :display_name))
```

File: test/metabase/api/query_description_test.clj [hunk 3]
```diff
@@ -31,51 +31,61 @@
...
 
-        (is (= {:table "Venues"
+        (is (= {:table  "Venues"
                 :filter [{:segment (deferred-tru "[Unknown Segment]")}]}
                (sut/generate-query-description (Table (mt/id :venues))
                                                (:query (mt/mbql-query :venues
-                                                         {:filter [[:segment -1]]})))))))))
+                                                         {:filter [[:segment -1]]}))))))
+
+      (testing "with named aggregation"
```
Comment (sbelak) [inline test/metabase/api/query_description_test.clj:83]: It would be nice to also have a test for what broke: an unnamed metric referencing multiple fields.
