### PR TITLE
Closes EMB-650 move download button to footer for title-less embed tables

### LINKED ISSUE #61255: Statics Embedded Dashboard Export Icon Overlapped with Tab Navigation Arrow
### Describe the bug

User cannot click the navigation arrow to move the tabs, which means cannot navigate to the tab they want to check. 

Image

### To Reproduce

Open a statics embedded dashboard with multiple tabs in a vertical screen, you should probably see the bug.

### Expected behavior

Export icon not overlapped with tab navigation arrow

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "duckdb",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-06-09",
      "tag": "v0.55.2",
      "hash": "4575c22"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.4 (Debian 17.4-1.pgdg120+2)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.5"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.6+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.6+7-LTS",
    "os.name": "Linux",
    "os.version": "6.1.0-29-amd64",
    "user.language": "en",
    "user.timezone": "Europe/London"
  }
}
```

### Severity

Blocking users to use it

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #61255 closes #62398
Closes [EMB-758: Download button overlaps table header with embedding title is not enabled.](https://linear.app/metabase/issue/EMB-758/download-button-overlaps-table-header-with-embedding-title-is-not)

### Description

This only applies to Tables in iframes/SDK, when title is hidden.

Before:
image

After:
image

### CODE REVIEW

File: frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx [hunk 1]
```diff
@@ -64,20 +64,23 @@ export function PublicOrEmbeddedQuestionView({
...
     result && downloadsEnabled.results ? (
       <PublicOrEmbeddedQuestionDownloadPopover
         className={cx(
           CS.m1,
-          CS.textMediumHover,
-          CS.hoverChild,
-          CS.hoverChildSmooth,
+          downloadInFooter ? "" : CS.textMediumHover,
+          downloadInFooter ? "" : CS.hoverChild,
+          downloadInFooter ? "" : CS.hoverChildSmooth,
```
Comment (heypoom) [inline frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx]: note: `classnames` library makes it so you can use `&&` here safely.

```suggestion
          downloadInFooter && CS.textMediumHover,
          downloadInFooter && CS.hoverChild,
          downloadInFooter && CS.hoverChildSmooth,
```

File: .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Table_Light_Theme.png
Comment (heypoom) [inline .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Table_Light_Theme.png:1]: Is it just me or does this layout looks a bit visually weird when Metabase branding is enabled, as there are plenty of empty spaces below the "2,000 rows"? It is practical though as the Metabase branding can be hidden.

**Review by heypoom — APPROVED** [review]
nice!

File: .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Table_Light_Theme.png
Comment (lorem--ipsum) [reply .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Table_Light_Theme.png:1]: It does look a little off. Maybe we could go with a smaller logo, on the same row?

Comment (heypoom) [reply .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Table_Light_Theme.png:1]: That makes sense - it would be nice to check with design here, in case they have some design ideas on this.

Comment (lorem--ipsum) [reply .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Table_Light_Theme.png:1]: That'd be interesting, although if we want to address this it'll need to be in another PR I guess, because the code changes will be more significant.

Comment (heypoom) [reply .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Table_Light_Theme.png:1]: yup, merging this first is fine!
