### PR TITLE
Public Cards & Dashboards

### LINKED ISSUE #2595: allow parametrized questions via URL
I would like to call question via URL and supply a parameter to it

for example 

`http://metabase.mycompany.com/card/3?myparemeter=123`

where SQL for the question would be

```
SELECT * FROM MyTable WHERE myField = {myparemeter}
```

this would allow referencing metabase in other applications for example helpdesk tickets "for details go to `http://metabase.mycompany.com/card/3?myparemeter=123` " where 123 would be for example customer ID supplied by the issue system like OpsGenie

### LINKED ISSUE #3923: Loading a dashboards sometimes query the card twice (1x without default filters and 1x with)
- Your browser and the version: Chrome 54.0
- Your operating system: Mac OS X El Capitan
- Your databases: Druid
- Metabase version: 20.1 (will try to reproduce the issue with 21.0)
- Metabase hosting environment: RHEL 6.7
- Metabase internal database: MySQL

Hi,

It happens from time to time (~1/15)  that when loading a dashboards (clicking on the link from the dropdown inside metabase), metabase queries data without the default filters once before then displaying the proper values with the filter. It seems to happen more often for some of our largest dashboard (~30 queries). The issue does not seem to be linked to the load as that happens also when there is a single user.

To give you a bit more context, here is the sequence of events leading sometimes to this issue (at random it appears):

1. Click on metabase dashboard from dropdown (maybe also happens from URL)
2. The cards in the dashboards are loaded a first time without any of the default filters (e.g. default value "Past 7 days" is ignored). All the cards display the incorrect results. 
(e.g. it is clearly visible that the whole timeseries has been loaded not only the "Past 7 days")
3. After a few seconds, the cards are updated and now display the proper timeseries with the proper default filter (e.g. the timeseries plot now only shows the last 7 days)

Looking at my browser request, I indeed see 2 "query" for each cards and no other events in-between.

`{"cardID":290,"parameters":[]}`
`{"cardID":290,"parameters":[{"type":"date/relative","target":["dimension",["field-id",340]],"value":"past7days"}]}`

We haven't updated yet to 0.21 and I haven't see any bug fix for this issue. However I will try to recreate this issue with the last version of metabase and I'll keep you posted.

I attached some logs that could be useful for you with this issue

[metabase-log-2016-12-12-card-loaded-twice.txt](https://github.com/metabase/metabase/files/645928/metabase-log-2016-12-12-card-loaded-twice.txt)

### PR DESCRIPTION
**Pull request by camsaul**
After lots of consideration I decided it made more sense just to add `:public_uuid` and `:made_public_by_id` columns to Card and Dashboard rather than making entirely new DB models to track this information since the relationship is 1:1 and would require lots of joins and other wonkery since in many cases we'd want the UUID to be available without hitting separate endpoints. New code is tighter and simpler.

Implements #3680 and #3681 (and possibly #1380 and #3366, depending on what exactly those cover).

Also incidentally resolve #3923 (Loading a dashboards sometimes query the card twice (1x without default filters and 1x with))

Also resolves #2595 "allow parametrized questions via URL"

### New setting: 

*  `enable-public-sharing`
    This is returned as part of the public settings info; must be enabled to create or execute public Cards & Dashboards

### New endpoints:

*  `POST /api/card/:id/public_link`
    Create a public link for a Card. Must be admin and public sharing must be enabled. Returns UUID
*  `DELETE /api/card/:id/public_link`
    Unshare a public Card. Must be admin.
*  `POST /api/dashboard/:id/public_link`
    Create a public link for a Dashboard. Must be admin and public sharing must be enabled. Returns UUID
*  `DELETE /api/dashboard/:id/public_link`
    Unshare a public Dashboard. Must be admin.
*  `GET /api/public/card/:uuid` 
    Fetch the results for a publicly-shared Card. Includes Card info under `:card`. Does not require auth credentials. Public sharing must be enabled.
*  `GET /api/public/card/:uuid/json` and `GET /api/public/card/:uuid/csv`
    Fetch the results of publicly-shared card in JSON or CSV format. Also available via redirects `GET /public/question/:uuid.csv` and `GET /public/question/:uuid.json`.
*   `GET /api/public/dashboard/:uuid`
    Fetch a publically shared Dashboard. Does not require auth credentials. Public sharing must be enabled. This includes information about the Cards belonging to this Dashboard, but not their results; fetch those asynchronously using the endpoint below.
*   `GET /api/public/dashboard/:uuid/card/:card-id`
    Fetch the results for a Card in publically shared Dashboard. Optionally accepts *URL* param `parameters`. Does not require auth credentials. Public sharing must be enabled. This is intended for use in asynchronously populating the Cards of a Dashboard once it has been fetched.
*  `GET /api/card/public`
    Fetch a list of publically-viewable Cards. You must be an admin to do this.
*  `GET /api/dashboard/public`
    Fetch a list of publically-viewable Dashboard. You must be an admin to do this.

Updated auto-generated API dox are also available [here](https://github.com/metabase/metabase/blob/public-cards-and-dashboards-2.0/docs/api-documentation.md).

### CODE REVIEW

**Comment by tlrobinson** [comment]
@camsaul Added a TODO for a way to get the field values relevant to cards/parameters on a dashboard. Basically something like this on the dashboard endpoint:


```javascript
{
  // ... rest of the dashboard
  ordered_cards: [
    {
      // ... rest of the dashcard
      card_id: 1,
      parameter_id: "9c9306af"
      target: ["dimension", ["field-id", 1234]] // should support fks as well
    },
    // ...
  ],
  field_values: {
    1234: ["Doohickey", "Gadget", "Gizmo", "Widget"]
  }
}

**Comment by tlrobinson** [comment]
This could get a bit complicated for dimension ("field filter") template_tags since you'll have to look at every dashcards' cards' querys' template_tags, in addition to every dashcard's parameter_mappings.

Basically any field referenced by any of the following:

`dashboard.ordered_cards[*].card. dataset_query.native.template_tags[*].dimension`
`dashboard.ordered_cards[*].series[*].dataset_query.native.template_tags[*].dimension`
`dashboard.ordered_cards[*].parameter_mappings[*].target`

**Comment by tlrobinson** [comment]
Actually, we only want the fields for the `template_tags` that are actually referenced by a `parameter_mapping`.

**Comment by salsakran** [comment]
In playing with this, it all looks pretty 👍 

I do think we should 404 instead of redirect someone to log in if a public link uuid isn't valid. I.e. if I get it wrong, it'd be good to get feedback on that vs being asked to log in.

**Comment by tlrobinson** [comment]
I've split the `/public` routes into their own webpage chunk/html page and tried to eliminate some of the larger dependencies from it, react, d3, dc, etc are pretty big though and unavoidable.

Currently minified and gzipped:

"main" frontend: ~1020KB
"public" frontend: 619KB

**Comment by camsaul** [comment]
It looks like if I got to just http://localhost:3000/public/ the 404 page isn't showing up anymore, it's just a blank page. Is the 404 page included in the "mini" HTML page?

**Comment by tlrobinson** [comment]
Yeah, I'll add that to the todos

**Comment by camsaul** [comment]
@tlrobinson RE getting FieldValues for filters in a Dashboard,

does something like this response format work?

screen shot 2017-01-16 at 3 50 42 pm

I'm just adding an extra field to the public dashboard endpoint called `:param_values` that maps field ID -> field values where they exist.

**Comment by camsaul** [comment]
It looks like non-public dashboards currently get this info by calling the DB metadata endpoint but since that's not going to be available for public dashboards this is reasonably close to that format

**Comment by tlrobinson** [comment]
That should work, thanks.

**Comment by tlrobinson** [comment]
@camsaul can you please review the backend portion of https://github.com/metabase/metabase/pull/4123/commits/3e883f34c984b254e335dcb0a05caa33fe5df269 which basically adds some meta/link tags to the public html and an oEmbed endpoint (bot are needed for embed.ly support)

File: src/metabase/api/public.clj [hunk 1]
```diff
@@ -18,9 +18,13 @@
             (metabase.query-processor [expand :as ql]
                                       interface)
             [metabase.util :as u]
-            [metabase.util.schema :as su])
+            [metabase.util.schema :as su]
+            [metabase.util.embed :refer [embed-iframe]])
   (:import metabase.query_processor.interface.FieldPlaceholder))
 
+(def default-embed-max-height 800)
```
Comment (camsaul) [inline src/metabase/api/public.clj]:
```clojure
(def ^:private ^:const ^Integer default-embed-max-height 800)
```

File: src/metabase/api/public.clj [hunk 2]
```diff
@@ -129,5 +133,19 @@
                            :dashboardcard_id [:in dashcard-ids])))))
   (run-query-for-card-with-id card-id parameters))
 
+(api/defendpoint GET "/oembed"
+  "oEmbed endpoint"
```
Comment (camsaul) [inline src/metabase/api/public.clj]: Can you make this docstring a little bit more useful? Why do we need this endpoint / what's it used for / etc.

File: project.clj [hunk 3]
```diff
@@ -39,6 +39,7 @@
                                org.apache.httpcomponents/httpclient
                                net.sourceforge.nekohtml/nekohtml
                                ring/ring-core]]
+                 [com.cemerick/url "0.1.1"]                           ; URL library
```
Comment (camsaul) [inline project.clj]: don't need to add this. Just require `[ring.util.codec :as codec]` and do `codec/form-encode`

File: src/metabase/util/urls.clj [hunk 4]
```diff
@@ -28,3 +30,13 @@
...
   (format "%s/admin/datamodel/segment/%d" (setting/get :-site-url) id))
+
+(defn oembed-url
+  "Return an oEmbed URL for the relative path and format
+
+     (oembed-url \"/x\" \"json\") -> \"http://localhost:3000/api/public/oembed?url=x&format=json\""
+  [^String relative-url ^String format]
+  (str (url (setting/get :-site-url) "/api/public/oembed")
+       ;; NOTE: some oEmbed consumers require `url` be the first param???
+       "?url=" (url-encode (url (setting/get :-site-url) relative-url))
```
Comment (camsaul) [inline src/metabase/util/urls.clj]: `codec/form-encode1

File: src/metabase/util/urls.clj [hunk 5]
```diff
@@ -28,3 +30,13 @@
...
+       "&format=" format))
```
Comment (camsaul) [inline src/metabase/util/urls.clj]: This whole thing should just be

```clojure
(str (setting/get :-site-url)
     "/api/public/oembed?"
     (codec/form-encode {:url    (str (setting/get :-site-url) relative-url)
                         :format format}))
```

File: src/metabase/util/embed.clj [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+(defn- embedly-meta
+  []
+  (html [:meta {:name "generator" :content "Metabase"}]))
+
+(defn embed-head
+  [url]
+  (str (embedly-meta)
+       (oembed-link url "json" "application/json+oembed")))
+
+(defn embed-iframe
```
Comment (camsaul) [inline src/metabase/util/embed.clj]: https://github.com/metabase/metabase/wiki/Metabase-Clojure-Style-Guide#public-vars-must-have-a-useful-docstring

File: src/metabase/util/urls.clj [hunk 7]
```diff
@@ -28,3 +30,13 @@
      (segment-url 10) -> \"http://localhost:3000/admin/datamodel/segment/10\""
   [^Integer id]
   (format "%s/admin/datamodel/segment/%d" (setting/get :-site-url) id))
+
+(defn oembed-url
+  "Return an oEmbed URL for the relative path and format
+
+     (oembed-url \"/x\" \"json\") -> \"http://localhost:3000/api/public/oembed?url=x&format=json\""
```
Comment (camsaul) [inline src/metabase/util/urls.clj]: nice docstring 👍

File: src/metabase/util/urls.clj (hunk 5 above)
Comment (tlrobinson) [inline src/metabase/util/urls.clj]: The comment explains why I'm not doing that. I had exactly that but it put `format=` before `url=` which wasn't working with one of the oEmbed things I tried. ¯\_(ツ)_/¯

File: project.clj (hunk 3 above)
Comment (tlrobinson) [inline project.clj]: I'm also using the `url` method, which resolves relative paths against a base url. e.x. `(str (url "http://localhost:3000/", "/api/public/oembed"))` returns `http://localhost:3000/api/public/oembed` whereas simple string concatenation would duplicate the `http://localhost:3000//api/public/oembed` (note the double `//`) which our router doesn't match.

If you'd rather not include the dependency we could just trim the trailing or leading "/", but I'm not sure if there are any other edge cases I'm missing.

File: src/metabase/util/embed.clj [hunk 8]
```diff
@@ -0,0 +1,26 @@
...
+(defn- oembed-link
+  [url format content-type]
+  (html [:link {:rel   "alternate"
+                :type  content-type
+                :href  (urls/oembed-url url format)
+                :title "Metabase"}]))
+
+(defn- embedly-meta
+  []
+  (html [:meta {:name "generator" :content "Metabase"}]))
```
Comment (camsaul) [inline src/metabase/util/embed.clj]: I would put a comma after `"generator"`. https://github.com/metabase/metabase/wiki/Metabase-Clojure-Style-Guide#align-map-values

File: src/metabase/routes.clj [hunk 9]
```diff
@@ -7,19 +7,22 @@
...
 
-(defn- entrypoint [entry _]
+
+(defn- entrypoint [entry embeddable? {:keys [uri]}]
   (-> (if ((resolve 'metabase.core/initialized?))
         (stencil/render-string (slurp (or (io/resource (str "frontend_client/" entry ".html"))
                                           (throw (Exception. (str "Cannot find './resources/frontend_client/" entry ".html'. Did you remember to build the Metabase frontend?")))))
-                               {:bootstrap_json (json/generate-string (public-settings/public-settings))})
+                               {:bootstrap_json (json/generate-string (public-settings/public-settings))
+                                :embed_code     (if embeddable? (embed-head uri))})
```
Comment (camsaul) [inline src/metabase/routes.clj]:
```clojure
(when embeddable? ...)
```

File: src/metabase/routes.clj [hunk 10]
```diff
@@ -7,19 +7,22 @@
...
         (slurp (io/resource "frontend_client/init.html")))
       resp/response
       (resp/content-type "text/html; charset=utf-8")))
 
-(def ^:private index (partial entrypoint "index"))
-(def ^:private public (partial entrypoint "public"))
+(def ^:private index (partial entrypoint "index" false))
+(def ^:private public (partial entrypoint "public" true))
```
Comment (camsaul) [inline src/metabase/routes.clj]: Nobody knows what `false` or `true` mean here so at the very least I would use keywords.

```clojure
(def ^:private index  (partial entrypoint "index"  (not :embeddable))
(def ^:private public (partial entrypoint "public" :embeddable))
```

also it never hurts to try to align things a bit

File: src/metabase/util/embed.clj [hunk 11]
```diff
@@ -0,0 +1,26 @@
...
+
+(defn- oembed-link
+  [url format content-type]
+  (html [:link {:rel   "alternate"
+                :type  content-type
+                :href  (urls/oembed-url url format)
+                :title "Metabase"}]))
+
+(defn- embedly-meta
+  []
```
Comment (camsaul) [inline src/metabase/util/embed.clj]: If there's no docstring you usually just put the arglist on the same line as the function name.

```clojure
(defn- embedly-meta []
  ...)
```

**Comment by camsaul** [comment]
OK, reviewed. Other than adding that library which isn't necessary and some style things it looks good.

File: src/metabase/routes.clj [hunk 12]
```diff
@@ -7,19 +7,22 @@
             [stencil.core :as stencil]
             [metabase.api.routes :as api]
             [metabase.public-settings :as public-settings]
-            [metabase.util :as u]))
+            [metabase.util :as u]
+            [metabase.util.embed :refer [embed-head]]))
```
Comment (camsaul) [inline src/metabase/routes.clj]: It's probably better to avoid `:refer` when possible, I would just `:require` this `:as embed-util` and do `embed-util/embed-head`

File: src/metabase/util/urls.clj (hunk 5 above)
Comment (camsaul) [inline src/metabase/util/urls.clj]: Oh well in that case just use `codec/url-encode` for the `relative-url`.

File: project.clj (hunk 3 above)
Comment (camsaul) [inline project.clj]: `-site-url` is guaranteed to never have a trailing slash, the function that sets it already strips off trailing slashes

Comment (tlrobinson) [inline project.clj]: That's definitely not the case, at least if you manually set the site-url in the admin settings.

Comment (camsaul) [inline project.clj]: That's a big with that then. I'll fix it. But we use the site URL in lots of places and have never needed a new library to do it

**Comment by tlrobinson** [comment]
@mazameli @kdoh A couple other things to keep in mind:

1. We can detect if we're in an iframe and show different layouts.

2. I've set up a way to pass options to the embed via the URL which we can use to configure the styling or disable certain elements (parameters, card title, download button, though we should make it clear it's only hiding the elements, not enforcing security, though that could be done with signed JWT tokens)

e.x. http://yourmetabase.com/public/question/QUESTION_UUID#bordered=true

Here's a demo (we could easily offer a UI like this to configure/preview an embed URL): https://public-links.herokuapp.com/_internal/embed/question/e86d6012-7be2-434d-b36e-e5619404276d

3. We might want to offer a couple iframe styles for different use cases, e.x. content (blogs, documentation) vs. application embedding (customer dashboard).

4. I think most of the "content" style embeds tend to have the "chrome" along the bottom:

RunKit:

screenshot 2017-01-19 17 15 32

Github Gist:

screenshot 2017-01-19 17 15 16

Scribd:

screenshot 2017-01-19 17 20 24

I definitely prefer the more compact style of RunKit/Gist over the bulky Scribd bar.

**Comment by mazameli** [comment]
Share icon path:
```
<svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><title>share-icon</title><path d="M24.571 28.632H7.43V13.474h3.428v-3.369H4V32h24V10.105h-6.857v3.369h3.428v15.158zm-10.285-6.316h3.428V7.158h-3.428v15.158zm6.857-15.158H10.857L16 .42l5.143 6.737z" fill="#616D75" fill-rule="evenodd"/></svg>
```

Copy icon path:
```
<svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><title>clipboard-copy</title><path d="M10.329 6.4h-3.33c-.95 0-1.72.77-1.72 1.72v.413h17.118V8.12c0-.941-.77-1.719-1.72-1.719h-3.31l-1.432-1.705a2.137 2.137 0 0 0-2.097-2.562 2.137 2.137 0 0 0-2.054 2.73L10.329 6.4zm12.808 4.267h1.4v8.557h-4.42l.111-4.188-5.981 6.064 5.805 6.264v-3.966h4.485v6.469H3.14v-19.2h19.997zm3.54 12.731v6.888c0 .947-.769 1.714-1.725 1.714H2.725C1.772 32 1 31.23 1 30.286V5.981c0-.947.768-1.714 1.725-1.714h6.834A4.273 4.273 0 0 1 13.839 0c2.363 0 4.279 1.91 4.279 4.267h6.834c.953 0 1.725.77 1.725 1.714v13.243H31v4.174h-4.323zM5.279 12.8h10.7v2.133h-10.7V12.8zm0 4.267h5.564V19.2H5.279v-2.133zm0 4.266h5.564v2.134H5.279v-2.134zm0 4.267h8.56v2.133h-8.56V25.6z" fill="#616D75" fill-rule="evenodd"/></svg>
```

**Comment by mazameli** [comment]
@tlrobinson / @kdoh: if we want to try the chain/link icon instead of the up-arrow/share one, here's the path:

```
<svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><title>chain-link</title><path d="M12.56 17.04c-1.08 1.384-1.303 1.963 1.755 4.04 3.058 2.076 7.29.143 8.587-1.062 1.404-1.304 4.81-4.697 7.567-7.842 2.758-3.144 1.338-8.238-.715-9.987-5.531-4.71-9.5-.554-11.088.773-2.606 2.176-5.207 5.144-5.207 5.144s1.747-.36 2.784 0c1.036.36 2.102.926 2.102.926l4.003-3.969s2.367-1.907 4.575 0 .674 4.404 0 5.189c-.674.784-6.668 6.742-6.668 6.742s-1.52.811-2.37.811c-.85 0-2.582-.528-2.582-.932 0-.405-1.665-1.22-2.744.166zm7.88-2.08c1.08-1.384 1.303-1.963-1.755-4.04-3.058-2.076-7.29-.143-8.587 1.062-1.404 1.304-4.81 4.697-7.567 7.842-2.758 3.144-1.338 8.238.715 9.987 5.531 4.71 9.5.554 11.088-.773 2.606-2.176 5.207-5.144 5.207-5.144s-1.747.36-2.784 0a17.379 17.379 0 0 1-2.102-.926l-4.003 3.969s-2.367 1.907-4.575 0-.674-4.404 0-5.189c.674-.784 6.668-6.742 6.668-6.742s1.52-.811 2.37-.811c.85 0 2.582.528 2.582.932 0 .405 1.665 1.22 2.744-.166z" fill="#959595" fill-rule="evenodd"/></svg>
```

**Comment by camsaul** [comment]
This button might work too

```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"  xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:svg="http://www.w3.org/2000/svg" xmlns:ns1="http://sozi.baierouge.fr" xmlns:xlink="http://www.w3.org/1999/xlink" id="svg2" sodipodi:docname="toucan.svg" viewBox="0 0 708.66 301.77" sodipodi:version="0.32" version="1.0" inkscape:version="0.46" sodipodi:docbase="/home/melwe/Utile/Ecles/ImagesMemory" > <sodipodi:namedview id="base" bordercolor="#666666" inkscape:pageshadow="2" inkscape:window-y="24" pagecolor="#ffffff" inkscape:window-height="1130" width="20cm" inkscape:zoom="0.98994948" inkscape:window-x="0" height="20cm" borderopacity="1.0" inkscape:current-layer="layer1" inkscape:cx="318.98689" inkscape:cy="330.46991" units="cm" inkscape:window-width="1600" showgrid="false" inkscape:pageopacity="0.0" inkscape:document-units="px"/> <g id="layer1" inkscape:label="Calque 1" inkscape:groupmode="layer" transform="translate(.000043809 -203.45)" > <g id="g3410" transform="matrix(.32649 0 0 .32649 371.1 206.61)" > <path id="path2242" style="stroke-linejoin:round" d="m-1089.8 657.52c4.9-170.83 144.38-295.46 280.63-377.62 86.06-43.68 176.69-79.04 269-107.3-99.51 67.22-232.04 71.83-322.14 155.82-91.74 63.66-163.59 157.2-185.79 268.06-3.5 27.46-7.7 58.09-41.7 61.04z"/> <path id="path3220" style="stroke-linejoin:round" d="m-1019.7 625.64c-8.5 2.38 76.45-40.93 52.31-32.53 125.24-76.38 275.74-89.56 408.62-144.9 61.58 2.93 66.63-70.6 112.42-88.01-1.31 107.8-144.69 107.16-220.31 140.16-100.84 33.09-217.77 53.06-304.55 104.05 70.8-42.38-136.19 87.55-48.49 21.23z"/> <path id="path3222" style="stroke-linejoin:round" d="m-547.91 197.46c27.13 43.74 53.69 130.66 54.28 158.62-66.34 4.48-99.09-122.88-57.06-156.85l2.78-1.77z"/> <path id="path3224" style="stroke-linejoin:round" d="m-468.69 276.44c-41.44 21.36 50.49-37.54 21.69 8.26 40.74 25.51-52.47 33.18 9.31-8.94 57.66-25.93-10.08 86.61-46.26 26.16-16.51-35.06 79.18-63.31 15.26-25.48z"/> <path id="path3226" style="stroke-linejoin:round" d="m-1040 610.29c49.97-60.21 121.12-100.04 189.38-136.43-35.04 25.36 52.91-28.53-8.42 6.62 39.67-21.46-5.16 3.47 39.57-20.38 95.37-48.7 196.7-85.72 301.05-109.78-72.33 50.54-165.72 51.98-242.69 93.75-45.3 19.13-87.26 39.18-89.59 40.1-9.3 6.09-32.78 19.79-68.73 35.05 35.21-33.3-78.69 83.87-120.57 91.07z"/> <path id="path3228" style="stroke-linejoin:round" d="m-504.13 162.55c111.69-55.3 235.48 26.98 350.88-12.91 52.28-24.58-13.46 11.52 43.69-19.99-42.35 22.67 59.411-35.229 97.588-47.011 108.3-38.774 214.15-93.011 332.05-92.06 101.77-1.841 207.26 5.4907 302.9 41.889 56.04 1.517 105.22 135.07 31.93 103.67-18.14-91.612-119.53-96.175-194.13-112.2-133.89-16.285-274-14.188-398.86 42.846-43.506 15.356-151.15 66.924-158.2 60.944-2.517 4.43-102.71 68.43-159.75 57.87-93.28 2.36-192.35-44.41-280.92 3.21 9.97-9.94 22.31-16.97 32.82-26.26z"/> <path id="path3230" style="stroke-linejoin:round" d="m552.95 105.51c101.91 23.65 214.57 54.54 279.08 143.7-30.47 79.11-87.81-68.78-144.68-65.77-38.31-31.53-154.27-31.03-147.19-68.64l12.79-9.29z"/> <path id="path3232" style="stroke-linejoin:round" d="m434.61 191.56c91.54 21.11 223.19-21.12 268.58 89.28 47.85 13.25 65.6 111.7 3.3 71.55-42.69-71.51-100.34-144.14-194.84-125.53-14.43-0.22-122.16-3.76-77.04-35.3z"/> <path id="path3234" style="stroke-linejoin:round" d="m275.67 221.78c72.51 32.14 228.4 46.48 250.87 79.46-89.17 18.56-201.2-26.92-272.03-64.17 3.53-8.61 13.48-11.9 21.16-15.29z"/> <path id="path3236" style="stroke-linejoin:round" d="m111.83 385.75c130.75 61.24 276.33 13.7 412.21 1.2 52.4-11.07 125.37-16.84 163.3-39.02-88.19 50.33-192.76 58.39-290.77 77.16-100.3 13.6-207.31 30.22-304.4-7.21-16.503-12.46 9.57-28.01 19.66-32.13z"/> <path id="path3238" style="stroke-linejoin:round" d="m163.04 341.65c35.77-0.81 170.74-9.68 133.25 38.52-51.46-0.55-117.15-1.85-159.3-20.07l13.02-9.23 13.03-9.22z"/> <path id="path3240" style="stroke-linejoin:round" d="m-272.19 305.61c131.27 83.53 283.38 161.49 443.96 134.43-43.39 45.39-128.7 31.5-189.97 20.4-104.04-21.69-198.74-76.27-287.67-130.51 5.36-12.63 25.02-14.06 33.68-24.32z"/> <path id="path3242" style="stroke-linejoin:round" d="m762.48 286.3c32.81-39.33 107 20.85 30.73 14.22-27.76 9.81-83.56 12.57-30.73-14.22z"/> <path id="path3244" style="stroke-linejoin:round" d="m779.68 309.6c77.49-48.78 37.34 102.49 11.17 60.7 11.6-33.73-84.33-36.43-11.17-60.7z"/> <path id="path3246" style="stroke-linejoin:round" d="m875.53 276.27c31.39 60.1-88.13 45.35-15.07 7.91 5.02-2.64 10.05-5.27 15.07-7.91z"/> <path id="path3248" style="stroke-linejoin:round" d="m778.5 383.69c80.73-66.41 53.38 73.78 27.76 48.05-16.33 3.4 22.53-23.94-18.39 2.3 66.77-29.89-24.82-52.35-29.93-33.59l8.59-6.9 11.97-9.86z"/> <path id="path3250" style="stroke-linejoin:round" d="m780.08 406.05c56.76 33.47-56.7 93.02-30.25 18.65l14.5-10.29 15.75-8.36z"/> <path id="path3252" style="stroke-linejoin:round" d="m670.36 389.68c19.35 11.15 74.1 16.6 20.24 31.69 79.03-55.09-14.79 46.6-49.5-5.9-4.16-16.25 19.18-20.88 29.26-25.79z"/> <path id="path3254" style="stroke-linejoin:round" d="m-501.99 462.62c145.56 61.49 311.01 109.18 466.4 54.78 25.444-8.43 40.95-12.56 38.883-8.97 52.392-14.32-75.956 47.01-113.98 45.38-116.75 26.9-239.46 6.59-348.68-38.83-26.4-6.6-119.93-26.39-42.62-52.36z"/> <path id="path3256" style="stroke-linejoin:round" d="m222.64 456.31c67.86 49.36-17.99 144.98-41.38 133.84 52.93-16.93-79.27 37.84-108.81 0.46-49.827-48.38 145.27-26.42 107.5-6.44-39.33 18.52 62.35-35.12 6.15-1.81 76.65-30.1-40.9-109 36.54-126.05z"/> <path id="path3258" style="stroke-linejoin:round" d="m24.548 519.22c57.5 40.47 37.093 184.68-10.018 177.3 21.571-54.9-26.497-134.38 3.281-173.08l6.737-4.22z"/> <path id="path3260" style="stroke-linejoin:round" d="m-71.214 569.65c21.662-45.11 106.79-81.27 152.57-33.84-30.595 24.03-138.12-4.46-103.57 1.11 39.808-23.66-40.92 37.61-49 32.73z"/> <path id="path3262" style="stroke-linejoin:round" d="m-15.095 556.17c107.62 21.22-93.645 52.17 0 0z"/> <path id="path3264" style="stroke-linejoin:round" d="m-45.703 729.02c40.363 12.73 45.018 102-1.137 49.95-5.732-69.87 103 14.57 16.219 18.16-40.362-1.47-73.139-65.51-15.082-68.11z"/> <path id="path3266" style="stroke-linejoin:round" d="m269.22 518.96c48.99 5.93 125.26-27.17 135.52-14.62-37.2 21.37-156.58 60.04-149.01 24.13l13.49-9.51z"/> <path id="path3268" style="stroke-linejoin:round" d="m445.33 495.45c-18.93 33.92-46.69 35-54.21 42.47-58.04 34.85 28.77-19.03-19.78 18.03-22.07 21.66-92.06 48.81-33.43 6.48 20.53-18.98 54.2-23.43 10.01-1.87 21.08-12.04 38.31-31.56 3.69-7.14 20.24-12.17 60.19-36.35 13.23-8.6 47.12-25.94 12.79-6.41 49.25-35.38l15.4-7.6 15.84-6.39z"/> <path id="path3270" style="stroke-linejoin:round" d="m341.18 585.23c70.54-5.11 10.83 128.13-9.53 42.52-32.13-15.65-16.96-34.21 9.53-42.52z"/> <path id="path3272" style="stroke-linejoin:round" d="m404.59 577.77c70.19 20.96 79.66 172.85 24.2 166.32 17.35-58.42-45.64-124.99-39.05-159.19l14.85-7.13z"/> <path id="path3274" style="stroke-linejoin:round" d="m407.27 585.01c12.47-14.22 80.36-47.14 35.32-25.24 53.99-31.31-32.81 21.1 19.4-9.85 43.87-23.2-11.73 5.7 33.38-18.57-3.04 0.83-31.35 8.95-12.42 3.59 27.97-24.34 84.04-38.8 22.98-3.16-56.47 35.09-42.2 23.5-51.82 28.76 13.67-4.51-39.55 21.59 0.99 2.2-14.73 10.34-31.58 15.26-47.83 22.27z"/> <path id="path3276" style="stroke-linejoin:round" d="m470.07 470.24c-24.96 21.85-35.15 24.97 0 0z"/> <path id="path3278" style="stroke-linejoin:round" d="m520.68 444.65c70.12 78.01 69.9 190.47 97.45 286.71 7.52 78.53 58.08 178.97 152.25 150.57 34.55-13.28 99.89 35.1 74.82 6.62 25.49-93.41-49.64-179.26-58.91-271.08-23.31-35.14-83.54-141.19-28.42-143.89 69.97 95.09 84.42 216.15 126.57 323.84 41.48 108.21-76.3 127.61-154.58 112.79-94.2 16.82-136.19-74.26-146.68-151.23-17.39-73.48-27.98-149.04-55.78-219.66 11.99-35.53-73.26-76.67-6.72-94.67z"/> <path id="path3280" style="stroke-linejoin:round" d="m-948.15 610.48c108.42 55.96 225.51-9.81 335.28-26.01 88.59-19.44 178.67-35.71 269.68-35.22-86.54 56.97-197.99 19.21-291.7 57.34-108.24 20.98-223.27 77.52-332.61 33.69-29.85-10.62 12.44-24.45 19.35-29.8z"/> <path id="path3282" style="stroke-linejoin:round" d="m-121.7 547.69c73.171-14.69 59.112 48.88-4.29 29.55-43.59-0.84-16.82-20.16 4.29-29.55z"/> <path id="path3284" style="stroke-linejoin:round" d="m233.13 580.15c42.26-10.52 112.31 28.05 34.12 31.19-26.4-3.08-113.82 7.49-34.12-31.19z"/> <path id="path3286" style="stroke-linejoin:round" d="m479.45 597.85c54.33-17.73 80.02 48.3 12.56 32.67-39.57 1.48-61.14-14.69-12.56-32.67z"/> <path id="path3288" style="stroke-linejoin:round" d="m865.91 634.5c40.93 16.41 147.39-2.45 144.29 32.42-51.45 12.81-146.56 3.56-171.6-14.95 8.78-6.39 20.17-8.75 27.31-17.47z"/> <path id="path3292" style="stroke-linejoin:round" d="m-1112.6 757.25c107.2 21.73 215.19 41.09 322.57 60.9 96.46-4.46 193.32-28.69 282.32-64.62 184.9-67 385.01-38.25 577.21-42.32 131.9 15.72 266.04 10.83 397.1 34.08 27.59-6.52 149.18-2.63 64.97 20.74-105.28 19.14-209.36-22.12-315.2-16.54-118.37-5.25-236.06-20.92-354.69-14.98-140.12-5.99-282.42 0.14-416.14 46.38 13.99-9.82-95.89 18.53-94.45 33.34-114.02 43.05-238.95 27.25-352.69-7.33-28.2-9.63-196.6-8.98-111-49.65z"/> <path id="path3294" style="stroke-linejoin:round" d="m924.06 790.47c32.61-5.66 173.74-5.72 75.73 26.07-13.4-2.45-140.86 5.21-75.73-26.07z"/> </g > </g > <metadata > <rdf:RDF > <cc:Work > <dc:format >image/svg+xml</dc:format > <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/> <cc:license rdf:resource="http://creativecommons.org/licenses/publicdomain/"/> <dc:publisher > <cc:Agent rdf:about="http://openclipart.org/" > <dc:title >Openclipart</dc:title > </cc:Agent > </dc:publisher > <dc:title >toucan</dc:title > <dc:date >2008-10-27T01:15:39</dc:date > <dc:description/> <dc:source >https://openclipart.org/detail/19785/toucan-by-melwe</dc:source > <dc:creator > <cc:Agent > <dc:title >melwe</dc:title > </cc:Agent > </dc:creator > <dc:subject > <rdf:Bag > <rdf:li >animal</rdf:li > <rdf:li >bird</rdf:li > <rdf:li >calligraphic</rdf:li > <rdf:li >line art</rdf:li > <rdf:li >nature</rdf:li > </rdf:Bag > </dc:subject > </cc:Work > <cc:License rdf:about="http://creativecommons.org/licenses/publicdomain/" > <cc:permits rdf:resource="http://creativecommons.org/ns#Reproduction"/> <cc:permits rdf:resource="http://creativecommons.org/ns#Distribution"/> <cc:permits rdf:resource="http://creativecommons.org/ns#DerivativeWorks"/> </cc:License > </rdf:RDF > </metadata ></svg>
```

**Comment by camsaul** [comment]
@tlrobinson next time you want changes to the endpoints just let me know, the changes in #4e88b21 broke a ton of tests and also were missing some really important security checks 💔

**Comment by camsaul** [comment]
I'll fix the changes

**Comment by tlrobinson** [comment]
@kdoh I've pushed the latest I have. A few things we talked about:

* parameters styling
* dashboard style (similar to fullscreen style?)
* title font size
* description icon PR #4224 
* padding breakpoints
* which dashboard buttons should we include?

**Comment by tlrobinson** [comment]
@camsaul Here are the properties required. Might be missing some but start here:

```

GET /api/public/card/:uuid

{
  id
  name
  description
  display
  visualization_settings
  dataset_query {
    native {
      template_tags
    }
  }
}

GET /api/public/dashboard/:uuid

{
  name
  description
  ordered_cards {
    card {
      SAME PROPERTIES /api/public/card/:uuid ABOVE
    },
    series [
      {
        SAME PROPERTIES /api/public/card/:uuid ABOVE
      }
    ]
    col
    row
    sizeX
    sizeY
    parameter_mappings
    visualization_settings
  }
}

GET /api/public/card/:uuid/query
GET /api/public/dashboard/:uuid/card/:card-id

{
  data {
    cols
    rows
    rows_truncated
  }
  error
  status
}
```

**Comment by tlrobinson** [comment]
Ideally we wouldn't need to expose the real card ID but we need that for the `GET /api/public/dashboard/:uuid/card/:card-id` endpoint.

**Comment by tlrobinson** [comment]
Also it might be a good idea to replace all errors with generic "An error occurred" messages for the public / embed endpoints.

**Comment by moumny** [comment]
Hi,

Great job ! its looking very good !

I played around a bit whit this branch below are few comments

- This doesnt fix #3923 (more detail in the issue)

- In our case we wouldnt be able to enable this because we dont trust all our user to share this responsibly. Ideally we can give this privilege only to a certain group. 

- I see the create link button even if its not enabled. (but i guess you know about this already)

- For the metabase branding in the dashboard. it would be great if it was at the end of the dashboard and not always visible. real estate in dashboard is important and you need to see the branding ALL the time. 

-For the question the branding is good but i find that the question title is too small . Also the icon for download look different than the other ones ? (in QB for eg.) 

Anyway love this feature, i just hope we get the permissions so that we can use it :)

**Comment by camsaul** [comment]
@moumny sharing is only allowed for admins

**Comment by camsaul** [comment]
@tlrobinson there's still some lint failures on this branch

```
/home/ubuntu/metabase/frontend/src/metabase/public/containers/PublicQuestion.jsx
  22:8  warning  'cx' is defined but never used  no-unused-vars
```

**Comment by camsaul** [comment]
once the lint error is fixed is there anything else we need to do or can we merge this?

**Comment by tlrobinson** [comment]
Yes, @kdoh and I are still working on the frontend.

**Comment by tlrobinson** [comment]
@camsaul if the public links setting is disabled the `GET /api/card/public` and `GET /api/dashboard/public` endpoints still return the previously public links (but with public_uuid as null). Could we just have them return an empty array?

**Comment by tlrobinson** [comment]
@camsaul actually that's not a big deal, I can work around it on the frontend. But it might be nice for consistency's sake.

**Comment by camsaul** [comment]
Yeah, if public settings are disabled I would think you wouldn't want to show that UI so you shouldn't need to call that endpoint

**Comment by camsaul** [comment]
I'll still change it though. Maybe it should return a 400 if public links are disabled like the other endpoints?

**Comment by mazameli** [comment]
I mentioned this on slack but it would also be nice to add a confirmation modal before actually revoking a link in the admin panel. A mis-click could really ruin your day, 'cause you might not even have noticed _which_ link you just accidentally removed.

Like:
`Revoke this link?`
`No one will be able to access this [card/dashboard] or download the .csv or JSON data from this link anymore.`
`(Buttons)    Cancel   Revoke`
