### PR TITLE
No request to pulse if user canot manage subscriptions

### LINKED ISSUE #65536: React SDK throws invalid unhandled rejection errors when non-critical requests fail
### Describe the bug

When a dashboard is embedded using the React SDK, some of the network requests made by the SDK are expected to fail in valid conditions. However, these failed requests are not handled by the SDK, so they cause an `unhandledrejection` error in the embedding application.

So far the only non-critical request that fails like this that I've identified is [`PulseApi.form_input`](https://github.com/metabase/metabase/blob/48a5c74c413f9e0f7b37ee6024ddecb5ae606289/frontend/src/metabase/services.js#L261), but there may be others. This request can fail if the user does not have `Subscriptions and Alerts` permissions, which does not prevent them from seeing the dashboard.

Additionally, the [errors being thrown](https://github.com/metabase/metabase/blob/48a5c74c413f9e0f7b37ee6024ddecb5ae606289/frontend/src/metabase/lib/api.js#L367) are not `Error` objects - instead, they are untyped objects with the shape `{ status: number, data: string }`. This makes them be displayed as `[object Object]` by handlers that expect proper `Error` objects.

### To Reproduce

1. Embed a dashboard using the React SDK. Or, navigate to https://embedded-analytics-sdk-demo.metabase.com/admin/analytics/i5s-lcGYLc1GyFdIy4TxH which already does this
2. Make the Metabase request to `/api/pulse/form_input` fail, by either:
  - removing "Subscriptions and Alerts" permissions from the authenticated user/API key, from `/admin/permissions/application` in Metabase, or
  - manually blocking the request in your browser, e.g.
  
Image

3. Observe that an unhandled rejection error is thrown when the request is blocked or fails:

Image

This error does not prevent the dashboard from loading as expected, but the unhandled rejection can trigger undesired behavior in customer applications. For example:

* Unhandled rejections can be reported by telemetry tools like Datadog, but in this case the failure is expected and there is nothing that can be done about it
* Some bundlers like Parcel or Webpack (used by Create React App) show full-screen errors when running in development mode when unhandled rejections happen. This can give a bad first impression for users who are new to the SDK. Example from a real customer:

Image

### Expected behavior

Ideally, prevent requests to `GET /api/pulse/form_input` from happening if the user does not have permissions (may not be feasible, and is not a complete solution)

When a request to `GET /api/pulse/form_input` fails, handle the rejection in the SDK and do not propagate it to the customer application. For this specific case, I don't even think a warning is needed.

When any request fails, throw a proper `Error` object instead of a custom one.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Whatever is running on https://embedded-analytics-sdk-demo.metabase.com
```

### Severity

Annoying, especially for first-time SDK users

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #65536
Closes [EMB-967: React SDK throws invalid unhandled rejection errors when non-critical requests fail](https://linear.app/metabase/issue/EMB-967/react-sdk-throws-invalid-unhandled-rejection-errors-when-non-critical)

### Description

Wraps API call in a try catch, and avoids doing a pulse request if the user cannot manage subscriptions.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: frontend/src/metabase/notifications/pulse/actions.ts [hunk 1]
```diff
@@ -51,12 +52,20 @@ export const setEditingPulse = createThunkAction(
         }
       } else {
         // HACK: need a way to wait for form_input to finish loading
```
Comment (npretto) [inline frontend/src/metabase/notifications/pulse/actions.ts]: Should the comment be moved down?
I think the hack was the `||` part

Comment (lorem--ipsum) [reply frontend/src/metabase/notifications/pulse/actions.ts]: I'll move it down, but honestly this comment is more confusing to me than anythign else 😅

File: frontend/src/metabase/notifications/pulse/actions.ts [hunk 2]
```diff
@@ -121,8 +130,15 @@ export const testPulse = createThunkAction(
...
-    return async function (): Promise<ChannelApiResponse> {
-      return await PulseApi.form_input();
+    return async function (): Promise<ChannelApiResponse | undefined> {
+      try {
+        return await PulseApi.form_input();
+      } catch {
+        // This request is expected to fail when the user lacks
+        // "Subscriptions and Alerts" permissions. Swallow the error
+        // so it doesn't surface as an unhandled rejection (EMB-967).
+        return undefined;
```
Comment (heypoom) [inline frontend/src/metabase/notifications/pulse/actions.ts:140]: (nit: I wished we could have still surfaced non-permission errors, but we can do that some other time)

**Review by heypoom — APPROVED** [review]
nice!
