### PR TITLE
fix: improve startup by not scheduling all dbs

### LINKED ISSUE #52458: Long startup with slow check-and-schedule-tasks execution
### Describe the bug

I see similar behaviour with Metabase `v0.51.12.1` (upgraded from 0.47, tried v0.52.6.2 with the same result) running in k8s with PostgreSQL 14.

Sometimes initialization gets "stuck" at `0.97` and enabling `MB_NS_TRACE: metabase.models.database,metabase.task.sync-databases` shows that initialization reaches `database/check-and-schedule-tasks` [step](https://github.com/metabase/metabase/blob/73a07d797e92708c400ea8598f9070ab435ff05e/src/metabase/core.clj#L168) and then proceeds but very slowly: `metabase.models.database/check-and-schedule-tasks-for-db!` [for each DB](https://github.com/metabase/metabase/blob/73a07d797e92708c400ea8598f9070ab435ff05e/src/metabase/models/database.clj#L135) takes around 10 to 15 seconds which in our case (around 250 databasees) takes about 40 minutes to start metabase.

I already tried "delay" the triggers according to comment https://github.com/metabase/metabase/issues/19604#issuecomment-1009008716 so that syncs did not put additional load. Also tried to reindex https://github.com/metabase/metabase/issues/19604#issuecomment-1236383459 . Performing vacuum https://github.com/metabase/metabase/issues/19604#issuecomment-1124167487 did not bring anything either though I don't have so many entries in `qrtz_triggers` (866) and `qrtz_cron_triggers` (851). Even tried to drop indexes in `qrtz_triggers` with no success.

What makes things worse is that this issue is not permanent: If I spawn two instances of Metabase (in k8s deployment), one of them (sometimes first, sometimes last) starts in ~2 minutes and the other takes the above mentioned 40 minutes. I would suspect some race condition but in sometimes even a single instance has this slow initialization.

This issue has been created as follow up for corresponding comment in  #19604 

### To Reproduce

1. Run metabase with PostgreSQL in k8s
2. Have around 250 databases (PostgreSQL, MySQL, ClickHouse, SQLServer)
3. Upgrade from 0.47 to `v0.51.12.1` and wait for all migrations to complete
4. Start additional instances of metabase in k8s deployment
5. See some of the instances get ready quickly but some take very long time

### Expected behavior

All instances get ready in approximately same and reasonable time.

### Logs

[metabase_send.log](https://github.com/user-attachments/files/18495268/metabase_send.log)

During startup a lot of index scans happen:

Image

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "sqlserver",
      "clickhouse",
      "bigquery-cloud-sdk",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-01-15",
      "tag": "v0.51.12.1",
      "hash": "73a07d7"
    },
    "settings": {
      "report-timezone": "Europe/Moscow"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.12 (Ubuntu 14.12-201-yandex.53249.ae65d30249)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "5.4.0-167-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

blocking upgrade

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edpaget**
Closes https://github.com/metabase/metabase/issues/52458

### Description

Improve long startup times by not scheduling tasks for all dbs on startup. Due to the lack of bulk operations in quartz if an installation has 500 dbs we need to load and scan through all associated db scanning triggers 500 times for all dbs which means loading about 500k records in 1000 operations.

This is generally pretty fast on a per operation basis (about .5s in local development), but on some postgresql installations this can blow up to a few seconds per db, which makes the whole operation take 40 minutes plus. Additionally there maybe both lock contention and resource contention between the quartz scheduler and the main app thread that draws out this time.

Instead we want to init the schedule and put it into standby mode -- where we can schedule tasks but are not executing them -- before we process the configuration file. That we can schedule all necessary tasks as part of loading the database from the config file and not need to then iterate all database to schedule their tasks later in the startup.

Long term, it would be good to support rescheduling tasks using a bulk operation in quartz (there are TODOs in their code base for supporting this) rather than needing to update each trigger individually.

### How to verify

1. Create a metabase instance with 100s of dbs
2. Start up, and it it should reach the COMPLETED log message much faster.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/task.clj [hunk 1]
```diff
@@ -97,7 +97,7 @@
                        (ex-message (.getCause e)))
             (qs/delete-job scheduler job-key)))))))
 
-(defn- init-scheduler!
+(defn init-scheduler!
```
Comment (johnswanson) [inline src/metabase/task.clj:100]: Assume you've made sure that `(init-scheduler!)` is idempotent right? So we can call it once, then `(start-scheduler!)` will call it a second time and that's ok?

**Review by johnswanson — APPROVED** [review]

File: src/metabase/task.clj (hunk 1 above)
Comment (edpaget) [reply src/metabase/task.clj:100]: Yes `init-scheduler!`'s body only runs when the scheduler atom is [non-nil](https://github.com/metabase/metabase/blob/master/src/metabase/task.clj#L105)
