### PR TITLE
Fall back to base_type when calling parse-value-for-field-type

### LINKED ISSUE #15901: Variable Field Type after upgrade "Input to parse-value-to-field-type does not match schema"
**Describe the bug**
We just upgraded from 0.38 to 0.39.01, which broke our query Variables - Field Type.
All queries with such variables now return: 
> Input to parse-value-for-field-type does not match schema: [0;33m [(named (not ("Valid field type" nil)) effective-type) nil] [0m

For some it was fixed by going to the database model and remove the cached field values + rescan, but for other variables this doesn't fix it.

**Logs**
```
app-main.bundle.js?c27310ee92f8f98b4fb8:5 Error getting setting scalar.field TypeError: Cannot read property 'name' of undefined
    at Object.getDefault (app-main.bundle.js?c27310ee92f8f98b4fb8:5)
    at _ (app-main.bundle.js?c27310ee92f8f98b4fb8:5)
    at t.getComputedSettings (app-main.bundle.js?c27310ee92f8f98b4fb8:5)
 b8:495
Show 22 more frames
app-main.bundle.js?c27310ee92f8f98b4fb8:5 error Input to parse-value-for-field-type does not match schema: 

	 [0;33m  [(named (not ("Valid field type" nil)) effective-type) nil] [0m 
```

**To Reproduce**
1. Go to 'question with field type variable'
2. Click on 'run'

**Expected behavior**
no errors

**Screenshots**

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.6+10-post-Debian-1bpo91",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.6+10-post-Debian-1bpo91",
    "os.name": "Linux",
    "os.version": "4.19.0-6-amd64",
    "user.language": "en",
    "user.timezone": "Europe/Brussels"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.23"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-20",
      "tag": "v0.39.0.1",
      "branch": "release-x.39.x",
      "hash": "47bb5f2"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```
**Severity**
We have a lot of dashboard queries that rely on these variable field types, which are now all broken.
We base our daily operations on the results of these queries, so quite annoying.
It's possible to go around it by not using the variables, but by manually inserting the values in the queries, but we have a lot of them.

**Additional context**
Happened after upgrade from 0.38.X to 0.39.01.
In the metabase db table metabase_field  I found this in the fingerprint of a failing field used by variables:
> {"global":{"distinct-count":17,"nil%":0.0},"type":{"type/DateTime":{"earliest":"2021-04-19T13:30:47Z","latest":"2021-04-22T10:10:21Z"}}}

It might have something to do with the "nil%"?

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes #15901

Fall back to base_type when calling parse-value-for-field-type

I don't exactly follow what's going on in #15901. But it seems that
the field information can be kept in the db

> ""field_ref"":[""field"",""count(*)"",{""base-type"":""type/BigInteger""}]

And so we need to handle this base type here. Note that in the
function that calls `update-filter-for-field-type` it checks that the
field has a base_type.

I'm also a bit confused by the base_type vs base-type in the above
snippet. But again the calling code has

```clojure
(and (= param-type :dimension)
     (get-in value [:field :base_type]))
(update-filter-for-field-type value)
```

So it seems the field has a base_type rather than a base-type.

### CODE REVIEW

**Comment by camsaul** [comment]
Instances of Field have `field_type`, since they come from the application DB. field refs are MB snippets so they use lisp-case. `["field" "count(*)" {"base-type" "type/Integer"}]` is the way it will always look in `field-ref`

File: src/metabase/driver/common/parameters/values.clj [hunk 1]
```diff
@@ -265,17 +265,18 @@
 (s/defn ^:private update-filter-for-field-type :- ParsedParamValue
   "Update a Field Filter with a textual, or sequence of textual, values. The base type and semantic type of the field
   are used to determine what 'semantic' type interpretation is required (e.g. for UUID fields)."
-  [{{effective_type :effective_type, :as _field} :field, {value :value} :value, :as field-filter} :- FieldFilter]
-  (let [new-value (cond
+  [{field :field, {value :value} :value, :as field-filter} :- FieldFilter]
+  (let [effective-type (or (:effective_type field) (:base_type field))
```
Comment (camsaul) [inline src/metabase/driver/common/parameters/values.clj:269]: I thought Field was always supposed to have `effective_type`? Any idea why it would be missing here?

If we're determining it from the `:base-type` information in the field ref, maybe we should also add `:effective_type` at the same place we do that

Comment (dpsutton) [reply src/metabase/driver/common/parameters/values.clj:269]: I think my thinking was that our inferencing code doesn't use effective_type yet. So Fields capitol F always have an effective type. That's not necessarily the case with aggregations and the like.

Comment (dpsutton) [reply src/metabase/driver/common/parameters/values.clj:269]: Trying to move to a world where everyone only considers effective type, and only the query processor's really need to know about base type when emitting queries but that change was a bit too big especially when you had a really big field ref refactor at the same time.

Comment (camsaul) [reply src/metabase/driver/common/parameters/values.clj:269]: Yeah. That wasn't great timing on my part. Sorry about that. I think this change makes sense for now

**Review by camsaul — APPROVED** [review]

File: src/metabase/driver/common/parameters/values.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/driver/common/parameters/values.clj:269]: it wasn't just yours. the rename from special_type to semantic_type touched 140 or so files. it was a big change where basically nothing was supposed to happen. and adding inferencing code into an already huge change made it impossible. but there was a lot of upheaval outside of it too and it just was far better to delay it.
