### PR TITLE
Fix broken pivot table due to null dimension values

### LINKED ISSUE #2440: Pivot table redering crashes when dimension value is null
This is on 0.17.0-snapshot using Chrome

screen shot 2016-04-27 at 11 03 39 am

unclear what about the response is causing this issue, but here's the columns from the query result ...

screen shot 2016-04-27 at 11 06 41 am

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #2440

### CODE REVIEW

File: frontend/src/lib/data_grid.js [hunk 1]
```diff
@@ -92,7 +92,7 @@ var DataGrid = {
             }
 
             var colDef = _.clone(data.cols[cellCol]);
-            colDef['name'] = colDef['display_name'] = formatValue(val, { column: data.cols[pivotCol] });
+            colDef['name'] = colDef['display_name'] = formatValue(val, { column: data.cols[pivotCol] }) || "";
```
Comment (agilliland) [inline frontend/src/lib/data_grid.js]: @tlrobinson can we add a unit test for this?  I think it makes sense to have some coverage on this pivoting function.

Comment (tlrobinson) [inline frontend/src/lib/data_grid.js]: Done.
