### PR TITLE
Remove panning logic from map boundary calculation

### LINKED ISSUE #26213: Custom region maps only shows partial map visualization
**Describe the bug**
Custom region maps only shows partial map visualization.
Regression since 0.44.0. History #23450 and #15560.

**To Reproduce**
1. Admin > Settings > Maps > Add a map > example:
`https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/world.json`
2. Native > Sample > `select 'US' region, 5 val`
3. Change visualization to Map > select "Region map", then the custom map
image

**Information about your Metabase Installation:**
Tested 0.43.5 thru 0.44.6. Regression since 0.44.0, where previously it would show duplicated maps as #15560.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by iethree**
Resolves #26213 

### Chapter 1

Once upon a time, some maps in metabase would repeat themselves, to make the left-right panning experience nicer: e.g. it would be easier to center a global map on Japan, even though most global maps center on Europe. This functionality was removed in https://github.com/metabase/metabase/pull/22427 because it looked a little funny and users reported it as a bug. In order to make maps appear correctly after repeating was removed, we added this code to center maps:

https://github.com/metabase/metabase/blob/ccac9d9af9addbc8eb689a802b5d5ccb92b1638a/frontend/src/metabase/visualizations/components/LeafletChoropleth.jsx#L103

And all was well. (spoiler: it was not all well).

### Chapter 2

Later on, we discovered an issue where users "couldn't load" new maps https://github.com/metabase/metabase/issues/23450 (spoiler: in fact, maps would load just fine, their previews just wouldn't appear for some reason)

It appeared that the panning code actually was pushing the maps out of the viewport, and [removing the panning code](https://github.com/metabase/metabase/pull/23454) fixed everything! (spoiler: it did not fix everything)

### Chapter 3

And it came to pass that again, we have a reported issue that certain maps seem to be squished to the side and cut off 🤔 

199487692-6d131fbf-55db-400a-8ccf-aaaa4ed675e0

But some maps are totally fine:
Screen Shot 2022-12-22 at 2 50 01 PM

What if we just stick the panning code back in?
Screen Shot 2022-12-22 at 2 49 28 PM

Hooray! we've saved the world, but it cost us California, the UK and the Pacific Islands. 😢 

Alright? what's really going on here? 

Well, it turns out that in the code that sets map boundaries, for certain large maps, it sets ridiculously large boundaries  (wait for it...) to allow you to pan side to side.

## Changes

Deleted the conditional and calculations that set map boundaries wide enough to allow side-to-side map panning.

Screen Shot 2022-12-22 at 2 19 45 PM

And all the maps are happy now.

## Testing Steps

I used all of these test maps to make sure they appeared correctly, in the map loader (in admin settings), and in the query builder, and in dashboards.
```
https://raw.githubusercontent.com/metabase/metabase/master/resources/frontend_client/app/assets/geojson/world.json
https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json
https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson
https://raw.githubusercontent.com/codeforgermany/click_that_hood/main/public/data/california-counties.geojson
https://pacificdata.org/data/dataset/964dbebf-2f42-414e-bf99-dd7125eedb16/resource/dad3f7b2-a8aa-4584-8bca-a77e16a391fe/download/country_boundary_eez.geojson
https://gist.githubusercontent.com/iethree/ec57ec72e12fb61d74a595a1e88a2826/raw/d02fb28577f76c41d07fb07131f4d0ec8067839c/uk_regions.geojson
https://raw.githubusercontent.com/codeforgermany/click_that_hood/main/public/data/africa.geojson
```

~Gonna poke around a bit and see if there's a way to unit test this. 🕵️‍♀️~
It appears that JSDOM doesn't really support svg rendering, so any meaningful unit tests are impossible with our current test setup.
https://stackoverflow.com/questions/54382414/fixing-react-leaflet-testing-error-cannot-read-property-layeradd-of-null/54384719#54384719

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/mapping.js [hunk 1]
```diff
@@ -3,55 +3,13 @@ import d3 from "d3";
...
-      L.latLng(south, west), // SW
-      L.latLng(north, east), // NE
-    );
-  } else {
-    return L.latLngBounds(
-      L.latLng(south, -360 + gap[1]), // SW
-      L.latLng(north, gap[0]), // NE
-    );
-  }
-}
```
Comment (iethree) [inline frontend/src/metabase/visualizations/lib/mapping.js:24]: as far as i can tell, the only purpose of this conditional, and the `computeLargestGap` function, was to determine if a map was large enough to warrant panning.

File: frontend/src/metabase/visualizations/lib/mapping.js [hunk 2]
```diff
@@ -3,55 +3,13 @@ import d3 from "d3";
...
-  const antemeridianGapSize = 180 + west + (180 - east);
-
-  if (antemeridianGapSize > normalGapSize) {
-    return L.latLngBounds(
-      L.latLng(south, west), // SW
-      L.latLng(north, east), // NE
-    );
-  } else {
-    return L.latLngBounds(
-      L.latLng(south, -360 + gap[1]), // SW
```
Comment (iethree) [inline frontend/src/metabase/visualizations/lib/mapping.js:20]: this `-360` is the giveaway. longitude only goes to +/- 180, so no matter what the biggest gap is, this is going to give us a left boundary wider than the globe

**Comment by gusaiani** [comment]
@iethree I'm using the query `select 'US' region, 5 val` for kind of everything in testing.

So far I haven't been able to highlight a region as in the screenshots. 

Anything I should be doing?
Maybe a few more details to help manual test.

**Review by gusaiani — APPROVED** [review]
Code looks good to me and so do manual tests.

Asking @flamber for a look as you may catch outlying cases.

**Comment by iethree** [comment]
@metabase-bot run visual tests

**Comment by iethree** [comment]
Looks like I need to update the visual tests to account for loading time for map
9c3fb2ffec4fe42d9f6f8c30c0217d985cf73af6e232e43bd90f63da836bcc0c
s:

**Review by flamber — APPROVED** [review]
This seems to work as expected on all the maps I have.
Is this going into 45? Then remember the `backport` label.
