### PR TITLE
fix: perf improvements for documents

### LINKED ISSUE #70538: Can't resolve a comment, or add a subcomment, or add an emoji to a comment for a document
### Describe the bug

[https://jam.dev/c/a4dd5736-e94b-44f1-b388-4ea24c832c25](<https://jam.dev/c/a4dd5736-e94b-44f1-b388-4ea24c832c25>)

Typing a comment, adding an emoji, resolving a comment causes all the graph in this document to repaint, this makes the browser lags severely. \[ @uladzimirdev did a first quick investigation \] 

## Reproduction Doc (cloned, safe to test)

[https://stats.metabase.com/document/3400](<https://stats.metabase.com/document/3400>)

### To Reproduce

See Jam

### Expected behavior

*No response*

### Logs

*No response*

### Information about your Metabase installation

```JSON
see Jam
```

### Severity

P1?

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by uladzimirdev**
closes #70538
 
The idea is to avoid unnecessary re-renderings of the documents page when we interact with a comments sidebar.
it is done by moving some changing props outside of the state and top level page
examples
- `unresolvedCommentsCount` - we don't need to pass changing threads, we're interested only in a count
- `hasComments` - it required fetching a new query and updating state of the documents page, but this var is used only inside the header, so moved to header
- React.memo on Editor to avoid re-rendering if children change

### CODE REVIEW

File: frontend/src/metabase/documents/hooks/use-block-menus.ts [hunk 1]
```diff
@@ -38,22 +39,29 @@ export function useBlockMenus({
   const childTargetId = useSelector(getChildTargetId);
   const hoveredChildTargetId = useSelector(getHoveredChildTargetId);
   const document = useSelector(getCurrentDocument);
-  const { data: commentsData } = useListCommentsQuery(
+  const { _id } = node.attrs;
+
+  const { unresolvedCommentsCount } = useListCommentsQuery(
```
Comment (stasgavrylov) [inline frontend/src/metabase/documents/hooks/use-block-menus.ts]: I suggest to wrap this into a custom hook to reuse in 3 places instead of duplicating the logic.

**Review by stasgavrylov — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/documents/components/Editor/Editor.tsx [hunk 2]
```diff
@@ -94,190 +93,194 @@ export interface EditorProps {
...
-            target.classList.contains("ProseMirror")
-          ) {
-            const clickY = e.clientY;
-            const proseMirrorElement = target.querySelector(".ProseMirror");
+        <Box
+          className={S.editorContent}
+          ref={editorContainerRef}
+          onClick={(e) => {
+            // Focus editor when clicking on empty space
+            const target = e.target as HTMLElement;
```
Comment (chodorowicz) [inline frontend/src/metabase/documents/components/Editor/Editor.tsx]: [suggestion(non-blocking)](https://pullpo.io/cc?l=suggestion&d=non-blocking) 
```tsx
if (target !instanceof HTMLElement) {
  return;
}
``

File: frontend/src/metabase/documents/components/DocumentHeader.tsx [hunk 3]
```diff
@@ -71,8 +72,15 @@ export const DocumentHeader = ({
...
   onShowHistory,
-  hasComments = false,
 }: DocumentHeaderProps) => {
+  const { data: commentsData } = useListCommentsQuery(
+    getListCommentsQuery(document),
+  );
+  const hasComments =
+    !isNewDocument &&
+    !!commentsData?.comments &&
+    commentsData.comments.length > 0;
```
Comment (chodorowicz) [inline frontend/src/metabase/documents/components/DocumentHeader.tsx]: [suggestion](https://pullpo.io/cc?l=suggestion) 

```suggestion
  const { hasComments } = useListCommentsQuery(getListCommentsQuery(document), {
    selectFromResult: ({ data }) => ({
      hasComments: !isNewDocument && !!data?.comments?.length,
    }),
  });
```

**Review by chodorowicz — COMMENTED** [review]
Looks great, and performance issue is fixed 👏  The comment from @stasgavrylov is the only I'd deem as required. I have two nonblocking comments.

File: frontend/src/metabase/documents/hooks/use-block-menus.ts (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/documents/hooks/use-block-menus.ts]: done

File: frontend/src/metabase/documents/components/DocumentHeader.tsx (hunk 3 above)
Comment (uladzimirdev) [reply frontend/src/metabase/documents/components/DocumentHeader.tsx]: fixed

File: frontend/src/metabase/documents/components/Editor/Editor.tsx (hunk 2 above)
Comment (uladzimirdev) [reply frontend/src/metabase/documents/components/Editor/Editor.tsx]: fixed

**Review by chodorowicz — APPROVED** [review]

**Review by stasgavrylov — APPROVED** [review]
