### PR TITLE
Fix unable to save a question after converting to SQL

### LINKED ISSUE #40422: Cannot save a question based on another question after converting to SQL
### Describe the bug

After converting a saved question which is based on another saved question to SQL, it's impossible to save the question.

### To Reproduce

1. New -> Question -> Orders -> Save as Q1
2. New -> Question -> Q1 -> Save as Q2
3. Convert to SQL
4. See the save button is greyed out

### Expected behavior

It should be possible to save the question after converting

### Logs

_No response_

### Information about your Metabase installation

```JSON
49.0-49.1
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/40422

The problem appeared when we started using `can-run` for native queries in https://github.com/metabase/metabase/pull/40288. There is an issue with `malli` validation for `collection` field for native queries https://github.com/metabase/metabase/blob/c27b67692137ebd7641e80e1c19174920c71cc14/src/metabase/lib/schema.cljc#L54 It requires the `collection` to be a non-empty string or not present at all, while previously we allowed `undefined` to stay temporary in the QB state. This PR fixes the issue by excluding `undefined` `collection`.

Before
Screenshot 2024-03-21 at 07 25 46

After
Screenshot 2024-03-21 at 07 24 20

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/view/ConvertQueryModal/utils.ts [hunk 1]
```diff
@@ -1,20 +1,21 @@
...
-  const collection =
-    tableId === null || typeof tableId === "undefined"
-      ? undefined
-      : question.metadata().tables[tableId]?.name;
+  const query = question.query();
+  const databaseId = Lib.databaseID(query);
+  const tableId = Lib.sourceTableOrCardId(query);
+  const table = tableId ? Lib.tableOrCardMetadata(query, tableId) : undefined;
+  const tableName = table ? Lib.displayInfo(query, -1, table).name : undefined;
+  const extras = tableName ? { collection: tableName } : {};
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ConvertQueryModal/utils.ts:14]: Extra fields like `collection` are called `native query extras` in QP.

**Review by nemanjaglumac — APPROVED** [review]

**Review by kamilmielnik — APPROVED** [review]
:+1:
