### PR TITLE
fix: better check for dirty collection state

### LINKED ISSUE #69964: Remote sync cannot be enabled or switched to read-only mode when tenant shared collections exist
### Describe the bug

After a tenant shared collection is created, it is not possible to enable remote sync in read-only mode, or switch the sync mode from Read-write to Read-only.

Attempting to change the sync mode results in the error:
> Cannot change synced collections when remote-sync-type is read-only.

### To Reproduce

1. Enable Remote sync
2. Create a tenant shared collection
3. Include the collection in remote sync (i believe this step is optional)
4. Push changes
5. Attempt to switch the sync mode to read-only, and see the error:> Cannot change synced collections when remote-sync-type is read-only.

### Expected behavior

It should be possible to enable remote sync or switch the sync mode to Read-only, even when tenant shared collections exist.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2026-02-16",
      "tag": "v1.58.7",
      "hash": "85988ba"
    },
    "settings": {
      "report-timezone": "Australia/Melbourne"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Reported by a customer

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edpaget**
closes #69964
### Description

Our frontend code that prevents sending unchanged collections missed tenant collections being added to the payload. This fixes both the frontend to make sure we don't send when there are no changed collections and it updates the backend actually check if collections are being changed rather than just checking if the collections map exists.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/metabase-enterprise/remote_sync/components/RemoteSyncAdminSettings/RemoteSyncSettingsForm.tsx [hunk 1]
```diff
@@ -146,6 +146,60 @@ export const RemoteSyncSettingsForm = (props: RemoteSyncSettingsFormProps) => {
     modalContent: disableConfirmationModal,
   } = useConfirmation();
 
+  const initialValues = useMemo(() => {
```
Comment (npfitz) [inline enterprise/frontend/src/metabase-enterprise/remote_sync/components/RemoteSyncAdminSettings/RemoteSyncSettingsForm.tsx:149]: This was just moved eh? Didn't actually change?

**Review by npfitz — APPROVED** [review]
Didn't pull it down, but FE code looks okay

File: enterprise/frontend/src/metabase-enterprise/remote_sync/components/RemoteSyncAdminSettings/RemoteSyncSettingsForm.tsx (hunk 1 above)
Comment (edpaget) [reply enterprise/frontend/src/metabase-enterprise/remote_sync/components/RemoteSyncAdminSettings/RemoteSyncSettingsForm.tsx:149]: Yeah just moved it up so we can reference it when building the API request

**Review by nvoxland — APPROVED** [review]
