### PR TITLE
UXW-1852 Reset filter to default for specific click behavior

### LINKED ISSUE #64368: Click behavior on a dashboard question does not respect default filters
### Describe the bug

If you set a default value for a date filter in a dashboard, and then set up click behavior for date filtering based on, say, clicking a bar in a bar chart, and you double click the bar to add then remove the click-action filter, you end up with an empty value in the filter widget, not the default value. This happens even if you set the filter to "always require a value."

### To Reproduce

1. Go to a dashboard, add a date filter with a default filter, and set the filter to always require a value 
2. Set up click behavior for a question on the dashboard and set it to "update a dashboard filter" 
3. Toggle the question's click behavior to apply and remove a filter 
4. Notice that the filter widget doesn't reset to the assigned default. It lets you remove a filter that should always require a value 

### Expected behavior

The filter should restore to its default value when an applied filter is removed via click behavior. This will prevent the filter from becoming empty when it's set to always require a value 

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-09-29",
      "tag": "v1.55.17",
      "hash": "f39e95f"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deniskaber**
Closes https://github.com/metabase/metabase/issues/64368 / UXW-1852

### Description

This adds logic to reset dashboard filter to default value if it has default value and configured as required after resetting filter using `crossfilter` click behavior (Update a dashboard filter)

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Go to a dashboard, add a date filter with a default filter, and set the filter to always require a value
2. Set up click behavior for a question on the dashboard and set it to "update a dashboard filter" for date column
3. Toggle the question's click behavior to apply and remove a filter
4. Notice that the filter widget doesn't reset to the assigned default. It lets you remove a filter that should always require a value

### Demo

https://github.com/user-attachments/assets/3401a5f1-a57b-482a-9fcd-c790306bca1b

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/actions/parameters.tsx [hunk 1]
```diff
@@ -994,7 +992,22 @@ export const setOrUnsetParameterValues =
       _.isEqual(value, parameterValues[id]),
     );
     parameterIdValuePairs
-      .map(([id, value]) => setParameterValue(id, areAllSet ? null : value))
+      .map(([id, value]) => {
+        if (areAllSet) {
```
Comment (uladzimirdev) [inline frontend/src/metabase/dashboard/actions/parameters.tsx:1000]: nit: I'd revert this logic 

```
if (!areAllSet) {
	return ...
}

...
```

File: frontend/src/metabase/dashboard/actions/utils.ts [hunk 2]
```diff
@@ -103,3 +110,11 @@ export const trackAddedIFrameDashcards = (dashboard: Dashboard) => {
     console.error("Could not track added iframe dashcards", dashboard);
   }
 };
+
+export const getParameterDefaultValue = (
```
Comment (uladzimirdev) [inline frontend/src/metabase/dashboard/actions/utils.ts]: this function looks like a selector, why is it in the actions utils file?

**Review by uladzimirdev — APPROVED** [review]

**Comment by uladzimirdev** [comment]
I'd add e2e test for this specific case

**Review by bpander — APPROVED** [review]
Works great. I could even see going back to the default if the filter's _not_ required. But afaik no one's asked for that, and that might have some side effects. So I'm good with leaving `valueToSet` the way you have it.
