### PR TITLE
Fix clickhouse uuid filtering

### LINKED ISSUE #58579: Text comparison with ClickHouse UUIDs does not work
### Describe the bug

Text comparisons with ClickHouse UUIDs (starts with, ends with, contains) result in an error. 

### To Reproduce

1. Create a clickhouse table with UUID columns
2. Create a query with a text comparison filter on a UUID column
3. It will result in an error

### Expected behavior

It should properly filter the results

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "oracle",
      "bigquery-cloud-sdk",
      "snowflake",
      "clickhouse",
      "sqlite",
      "mysql",
      "sqlserver"
    ],
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-04-25",
      "src_hash": "9e60917aee222184598cf28946d8dd2f349dc952",
      "tag": "v1.55.2-SNAPSHOT",
      "hash": "d6348eb"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.18 (Debian 13.18-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.5"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "23.0.2",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "23.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "23.0.2",
    "os.name": "Mac OS X",
    "os.version": "15.3.1",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

Low

### Additional context

https://github.com/user-attachments/assets/85298be9-8eac-4eb5-9fff-645b7c15d718

### LINKED ISSUE #62492: Clickhouse question breaks when filter is applied to a Nullable(UUID) column that has a Null Value
### Describe the bug

When you apply a filter to a column that is of type Nullable(UUID) which has a Null Value the question breaks

### To Reproduce

You will need to use the Clickhouse Driver so connect to the Clickhouse Database and run the following so you create a table with a Nullable(UUID) and add 2 sample row with one of them being NULL:

```
create table table_name
(
    test_uuid Nullable(UUID)
)
    engine = Memory;

INSERT INTO table_name (*) VALUES ('721566e6-1bb6-4331-92f7-75d47e5289a1') ;
INSERT INTO table_name (*) VALUES (NULL) ;
```

Then New -> Question -> and filter on that column -> Notice it fails:

Image

### Expected behavior

The compiled SQL becomes WHERE CAST(\_organization AS text) = '12345678-1234-5678-1234-567812345678'. This results in the exception `Cannot convert NULL value to non-Nullable type` In Metabase v49, this compiles to WHERE \_organization = '12345678-1234-5678-1234-567812345678',  which works as expected.

### Logs

\[34232820-ab46-4df8-bde1-87317d6532d6\] 2025-08-21T13:06:56+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Code: 349. DB::Exception: Cannot convert NULL value to non-Nullable type: while executing 'FUNCTION CAST(\__table1.test_uuid : 3, 'text'\_String :: 1) -> CAST(\__table1.test_uuid, 'text'\_String) String : 0'. (CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN) (version 24.4.1.2088 (official build))  {:database_id 10,  :parameterized false,  :started_at #t "2025-08-21T11:06:56.298330460Z\[GMT\]",  :via  \[{:status :failed,    :class java.sql.SQLException,    :error    "Code: 349. DB::Exception: Cannot convert NULL value to non-Nullable type: while executing 'FUNCTION CAST(\__table1.test_uuid : 3, 'text'\_String :: 1) -> CAST(*table1.test_uuid, 'text'String) String : 0'. (CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN) (version 24.4.1.2088 (official build)) ",    :stacktrace    \["com.clickhouse.jdbc.internal.ExceptionUtils.toSqlState(ExceptionUtils.java:64)"     "com.clickhouse.jdbc.internal.ExceptionUtils.toSqlState(ExceptionUtils.java:39)"     "com.clickhouse.jdbc.StatementImpl.executeQuery(StatementImpl.java:207)"     "com.clickhouse.jdbc.StatementImpl.executeQuery(StatementImpl.java:151)"     "com.clickhouse.jdbc.PreparedStatementImpl.executeQuery(PreparedStatementImpl.java:110)"     "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:743)"     "--> driver.sql_jdbc.execute$fn__93247.invokeStatic(execute.clj:580)"     "driver.sql_jdbc.execute$fn__93247.invoke(execute.clj:578)"     "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG*.invokeStatic(execute.clj:593)"     "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG.invoke(execute.clj:589)"     "driver.sql_jdbc.execute$execute_reducible_query$fn__93339$fn__93340.invoke(execute.clj:769)"     "driver.sql_jdbc.execute$execute_reducible_query$fn__93339.invoke(execute.clj:768)"     "driver.clickhouse$fn__136709$fn__136711.invoke(clickhouse.clj:118)"     "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:347)"     "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:330)"     "driver.clickhouse$fn__136709.invokeStatic(clickhouse.clj:95)"     "driver.clickhouse$fn__136709.invoke(clickhouse.clj:93)"     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:761)"     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:750)"     "driver.sql_jdbc$fn__98077.invokeStatic(sql_jdbc.clj:81)"     "driver.sql_jdbc$fn__98077.invoke(sql_jdbc.clj:79)"     "query_processor.pipeline$*STAR_execute_STAR*.invokeStatic(pipeline.clj:58)"     "query_processor.pipeline$*STAR_execute_STAR*.invoke(pipeline.clj:43)"     "query_processor.pipeline$*STAR_run_STAR*.invokeStatic(pipeline.clj:116)"     "query_processor.pipeline$*STAR_run_STAR*.invoke(pipeline.clj:105)"     "query_processor.execute$run.invokeStatic(execute.clj:64)"     "query_processor.execute$run.invoke(execute.clj:58)"     "metabase_enterprise.database_routing.middleware$fn__140154$swap_destination_db__140155$fn__140156.invoke(middleware.clj:30)"     "query_processor.middleware.enterprise$swap_destination_db_middleware$fn__77119.invoke(enterprise.clj:73)"     "metabase_enterprise.impersonation.middleware$fn__126402$apply_impersonation_postprocessing__126403$fn__126404.invoke(middleware.clj:25)"     "query_processor.middleware.enterprise$apply_impersonation_postprocessing_middleware$fn__77102.invoke(enterprise.clj:48)"     "query_processor.middleware.update_used_cards$update_used_cards_BANG$fn__77318.invoke(update_used_cards.clj:67)"     "query_processor.execute$add_native_form_to_result_metadata$fn__77407.invoke(execute.clj:25)"     "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__77413.invoke(execute.clj:36)"     "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___77260.invoke(cache.clj:241)"     "query_processor.middleware.permissions$check_query_permissions$fn__72418.invoke(permissions.clj:163)"  ...

### Information about your Metabase installation

```JSON
Tested on 55 but I believe this happened before ... The version I know it works on is 49
```

### Severity

Flagged by a customer that upgraded from 49 to 55

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/62492
Closes https://github.com/metabase/metabase/issues/58579

### Description

Fixes clickhouse uuid filtering in different edge cases

### How to verify

1. Create a clickhouse table with a `Nullable(UUID)` column
```sql
create table uuid_table ( uuid_col Nullable(UUID) ) engine = Memory;
```

2. Populate it with UUIDs and nulls
```sql
INSERT INTO uuid_table (*) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');
INSERT INTO uuid_table (*) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb');
INSERT INTO uuid_table (*) VALUES (null) ;
```

3. You should be able to filter this table with all the string filter functions in metabase and get the expected results

### Demo

https://www.loom.com/share/b2cea5c5dfdd4d6f88cbe930f4696033

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/clickhouse/test/metabase/driver/clickhouse_data_types_test.clj [hunk 1]
```diff
@@ -337,22 +338,145 @@
...
+                                         [[1 #uuid "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"]]]
+
+                                        ["can filter nullable uuids with is empty"
+                                         (lib/is-empty (lib.metadata/field mp (mt/id :nullable_uuids :uuid1)))
+                                         [[3 nil]]]
+
+                                        ["can filter nullable uuids with is not empty"
+                                         (lib/not-empty (lib.metadata/field mp (mt/id :nullable_uuids :uuid1)))
+                                         [[1 #uuid "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"]
+                                          [2 #uuid "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"]]]]]
```
Comment (metamben) [inline modules/drivers/clickhouse/test/metabase/driver/clickhouse_data_types_test.clj]: I think in most cases we describe the test cases in a data structure so that it's easier to follow what the combinations are we are testing and then interpret that data structure.

**Review by metamben — APPROVED** [review]
