### PR TITLE
Fix order of cards in dashboard subscriptions

### LINKED ISSUE #15030: Dashboard Subscription doesn't follow the order of the cards on the dashboard
**Describe the bug**
Dashboard Subscription doesn't follow the order of the cards on the dashboard. Everything in `pulse_card` looks correct.

**To Reproduce**
1. Create 3 questions, like `select 'A' as name`
2. Add all three questions to a dashboard in this order: B | C | A
image
3. Dashboard Subscription (notice: clicking "Attach results" toggle will show correct order) and send email
4. The email looks like this:
image

**Expected behavior**
Follows the order similar to the dashboard, left to right, top to bottom.

**Information about your Metabase Installation:**
Tested 0.38.0.1

### PR DESCRIPTION
**Pull request by noahmoss**
Sorts dashcards by `:row` and then by `:col` which is the same ordering used by the frontend for mobile layouts: https://github.com/metabase/metabase/blob/master/frontend/src/metabase/dashboard/components/DashboardGrid.jsx#L119-L138

Also minor reformatting that my editor did automatically in `alert_test.clj`

Resolves #15030

### CODE REVIEW

File: src/metabase/pulse.clj [hunk 1]
```diff
@@ -91,12 +91,22 @@
...
+
 (defn execute-dashboard
   "Execute all the cards in a dashboard for a Pulse"
   [{pulse-creator-id :creator_id, :as pulse} dashboard-or-id & {:as options}]
   (let [dashboard-id (u/the-id dashboard-or-id)
-        dashboard (Dashboard :id dashboard-id)]
-    (for [dashcard (db/select DashboardCard :dashboard_id dashboard-id, :card_id [:not= nil])]
+        dashboard (Dashboard :id dashboard-id)
+        dashcards         (db/select DashboardCard :dashboard_id dashboard-id, :card_id [:not= nil])
+        ordered-dashcards (sort dashcard-comparator dashcards)]
```
Comment (camsaul) [inline src/metabase/pulse.clj:108]: nitpicky but it's a little weird to align some of the `let` args but not others. Either align them all or align none of them

File: test/metabase/api/alert_test.clj [hunk 2]
```diff
@@ -740,7 +740,7 @@
                                 (assoc-in (default-alert-req card pc-1) [:channels 0 :enabled] false)))
                              (api:alert-question-count :crowberto card))
                   :emails  (et/regex-email-bodies #"https://metabase.com/testmb"
-                                                  #"letting you know that Crowberto Corv" ))))))))
+                                                  #"letting you know that Crowberto Corv"))))))))
```
Comment (camsaul) [inline test/metabase/api/alert_test.clj:743]: 👍

**Review by camsaul — APPROVED** [review]
Cool, LGTM
