### PR TITLE
Fix {0} being shown when locale is "pt"

### LINKED ISSUE #16690: Some places shows {0} placeholder instead of expected value - Portuguese
**Describe the bug**
Reprise of #15694, but only for instances where language was defined as "Portuguese" prior to pre-39.0 and then upgrading to 0.39.4.
Pre-39 had "Portuguese" as `pt` internally, but that was changed in 0.39.0 (#15630) to "Portuguese (Brazil)" `pt-BR`.

Though, I don't understand what changed in 0.39.4 that suddenly caused this problem to occur, when it works on 0.39.3.

**Workaround** Go and set the language to "Portuguese (Brazil)" again in Admin > Settings > Localization. Note that it will display "en" after setting the language, but that's issue #15657.

**To Reproduce**
1. Admin > Settings > Localization > (set language value to `pt` via the API)
Note: Very likely the same problem for user-defined language under their Account settings, but haven't tested.
2. Admin > Settings > Updates - or - Simple question > Sample Dataset > Orders - will show `{0}` placeholders
Note: There are many other places that will show placeholders like that.
image
image

**Information about your Metabase Installation:**
Regression since 0.39.4, but seeded by a change in 0.39.0

**Additional context**
Related #15657/#16654
Re-write of #16681

### PR DESCRIPTION
**Pull request by pawit-metabase**
This is a combination of 2 issues:
 1) `pt` got renamed to `pt_BR` in x.39.x but the old `pt` value may still be stored in the database
 2) when making a release, an unclean build directory may be used containing old `pt` resource which gets leaked into the release build

The first issue is fixed by allowing `pt_BR` to be the fallback locale for `pt` to support users who were on `pt` since pre-x.39. (I've considered using a DB migration to fix it, but it won't work in all cases since the site locale may be encrypted in the database.)

The second issue is fixed by emptying the folder before generating locales so any old locales are deleted

Fixes #16690

### CODE REVIEW

File: src/metabase/util/i18n/impl.clj [hunk 1]
```diff
@@ -40,7 +49,9 @@
 
   String
   (locale [^String s]
-    (some-> (normalized-locale-string s) LocaleUtils/toLocale))
+    (some-> (normalized-locale-string s)
+            (migrate-legacy-locale-string)
```
Comment (camsaul) [inline src/metabase/util/i18n/impl.clj:53]:
```suggestion
            migrate-legacy-locale-string
```

The threading macros automatically wrap bare symbol forms after the first arg in parens (for example the `LocalUtils/toLocale` form below)... it's more idiomatic to let it do its thing in cases like this

File: src/metabase/util/i18n/impl.clj [hunk 2]
```diff
@@ -31,6 +31,15 @@
           (str language \_ (some-> country str/upper-case))
           language)))))
 
+(defn migrate-legacy-locale-string
```
Comment (camsaul) [inline src/metabase/util/i18n/impl.clj:34]:
```suggestion
(defn- migrate-legacy-locale-string
```

Let's make this private to make it clear that it's not used anywhere outside of this namespace... if we want to refactor it down the road it will be easier to do because we won't have to grep the codebase for usages

File: test/metabase/util/i18n/impl_test.clj [hunk 3]
```diff
@@ -18,6 +18,14 @@
       (is (= expected
              (impl/normalized-locale-string s))))))
 
+(deftest migrate-legacy-locale-string-test
+  (doseq [[s expected] {"pt"    "pt_BR"
+                        "pt_BR" "pt_BR"
+                        "en"    "en"}]
+    (testing (pr-str (list 'migrate-legacy-locale-string s))
+      (is (= expected
+             (impl/migrate-legacy-locale-string s))))))
```
Comment (camsaul) [inline test/metabase/util/i18n/impl_test.clj:27]:
```suggestion
             (#'impl/migrate-legacy-locale-string s))))))
```

You can refer to the var directly to get around it being private in tests

**Review by camsaul — CHANGES_REQUESTED** [review]
👍 on the build script changes to delete the old directories when building resources.

I don't think it makes sense to redefine (some implementations of) our low-level `locale` method function that returns an instance of `Locale` based on the string you pass in in this way:

```clj
(locale "en")    ; -> #locale "en"
(locale "en_US") ; -> #locale "en_US"
(locale "pt_BR") ; -> #locale "pt_BR"
(locale "pt")    ; -> #locale "pt_BR"

;; doesn't work
(locale (java.util.Locale. "pt"))
;; -> #locale "pt"
```

It would be like if we redefined `str/lower-case` to convert one specific word to another one to work around some bug. It's not something `str/lower-case` should be concerned with.

I'd suggest doing this mapping inside some other shared function called by `locale-edn-resource` and `metabase.server.routes.index/localization-json-file-name` since this only matters for resource bundle purposes and those are the functions concerned with actually finding relevant i18n resource bundles.

One other thought... would it make more sense to solve this problem more generally and make the resource bundle code more robust and fall back to the next closest match? For example if you ask for `es_ES` (Spanish - Spain) or `es` (Spanish) but we only have `es_MX` (Spanish - Mexico), I think serving up `es_MX` (Spanish - Mexico) is preferable to serving up `en` (English).

I think making the code more robust in that way would be future proof us a bit better than if we hardcode the specific `pt` -> `pt_BR` mapping. Otherwise we could very easily run into this sort of issue again in the future next time we change locale names around.

**Comment by pawit-metabase** [comment]
Sounds like that is what `parent-locale` already does and is already being called from both BE and FE side. How about we rename it and make it support the other direction too.

File: src/metabase/util/i18n/impl.clj [hunk 4]
```diff
@@ -57,14 +57,45 @@
    (when-let [locale (locale locale-or-name)]
      (LocaleUtils/isAvailableLocale locale))))
 
-(defn parent-locale
-  "For langugage + country Locales, returns the language-only Locale. Otherwise returns `nil`.
+(defn- available-locale-names*
```
Comment (pawit-metabase) [inline src/metabase/util/i18n/impl.clj:60]: Not sure if it's better to move things around or do `(declare)`

A change from the old implementation is that this now uses a sorted set.

Comment (camsaul) [reply src/metabase/util/i18n/impl.clj:60]: Better to move things around. In Clojure it's generally more idiomatic to avoid `declare` if you can and organize stuff so you don't need it

**Review by camsaul — APPROVED** [review]
Awesome. This LGTM
