### PR TITLE
Fixes isSticky class not being properly applied to dashboard parameters

### LINKED ISSUE #66742: IsSticky CSS applied to Parameter/Filter Panel upon scroll, not when panel sticks
**Describe the bug**
I am using Static Embedding and these params `#theme=transparent&background=false` in the embed URL. The dashboard's parameter/filter panel element with `data-testid="dashboard-parameters-widget-container"` gets the `.ParameterPanel.IsSticky` class applied immediately upon scrolling within the iframe, which adds a slightly transparent white background so that the main content well contents are hidden behind the filters element. However, this shouldn't happen until the filter element reaches the top of the iframe and actually becomes sticky and the main content scrolls behind it.

**Logs**
UI bug, no logs

**To Reproduce**
1. Render a Metabase dashboard via static embedding with the same query parameters as above in the embed URL.
2. Add a non-white background to the iframe's container element and ensure it is visible within the embedded dashboard
3. Make sure the iframe is scrollable within the browser window
4. Open the Elements tab in the developer tools and select the dashboard filters element in the DOM or search for `data-testid="dashboard-parameters-widget-container"`
5. Observe that there are no styles applying background color to this element
6. Scroll down to a point BEFORE the title disappears and the filters become sticky at the top of the iframe
7. Observe that the filters element now has a white background and observe the following css on the widget container:
```
.vPl_5.kM0g6 {
    background-color: color-mix(
    in srgb,
    #fff,
    var(--mb-color-bg-dashboard) 15%
  );
    background-color: color-mix(
    in srgb,
    var(--mb-color-bg-white),
    var(--mb-color-bg-dashboard) 15%
  );
    border-bottom-color: #eeecec;
    border-bottom-color: var(--mb-color-border);
}
```
8. Scroll until the filters become sticky and observe the classes have not changed and is working as expected

**Expected behavior**
The filter component should not have a white background applied to it until it becomes sticky.

**Screenshots**
Image
Image
Image
Image

**Severity**
This is not a severe issue. It is, however, quite annoying because the level of appearance customization available is already extremely limited and this issue prevents us from having any background color other than white in our application. My concern is that this is not considered a bug but actually expected behavior based on product requirements, despite the fact that the css class being applied is clearly not semantic for its use case.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2025-11-05",
      "tag": "v1.56.13",
      "hash": "2455296"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "6.8.0-1041-azure",
    "user.language": "en",
    "user.timezone": "America/New_York"
  }
}
```

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #66742
Closes [EMB-1125: IsSticky CSS applied to Parameter/Filter Panel upon scroll, not when panel sticks](https://linear.app/metabase/issue/EMB-1125/issticky-css-applied-to-parameterfilter-panel-upon-scroll-not-when)

### Description

The IsSticky class wasn't properly applied to the dashboard parameters panel, in embeds, because of the wrong position of the sentinel we use to detect scrolling.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Open the old static embedding on a dashboard
2. Make sure it has parameters
3. Scroll
4. The element with a testID `dashboard-parameters-widget-container`
 should  not have a CSS class `IsSticky` (and no bottom border) until it's actually sticky

### Demo

Before

https://github.com/user-attachments/assets/e7b22cd3-261b-436b-b0d8-2cfcf526a154

After

https://github.com/user-attachments/assets/b9a6503c-5413-4f00-b3fb-a2acd5373cdd

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: frontend/src/metabase/dashboard/hooks/use-is-parameter-panel-sticky.ts [hunk 1]
```diff
@@ -24,12 +24,14 @@ export function useIsParameterPanelSticky({
     sentinel.style.width = "100%";
     sentinel.style.position = "absolute";
     sentinel.style.top = "0";
+    sentinel.setAttribute("data-testid", "sticky-sentinel");
```
Comment (heypoom) [inline frontend/src/metabase/dashboard/hooks/use-is-parameter-panel-sticky.ts]: Do we use `sticky-sentinel` test id anywhere? Sorry, I couldn't find it in my branch.

File: e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js [hunk 2]
```diff
@@ -285,6 +285,47 @@ describe("scenarios > embedding > dashboard parameters", () => {
...
+      H.setEmbeddingParameter("Name", "Editable");
+
+      H.publishChanges("dashboard");
+
+      H.visitIframe();
+
+      // Scrolling duration is needed to let the time to React to update the className...
+      cy.findByTestId("embed-frame").scrollTo(0, 20, {
+        duration: 1000,
+      });
```
Comment (heypoom) [inline e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js:322]: I think putting a `timeout: 10_000` in findByTestId so that the `should("not.contain", "IsSticky")` waits for that timeout is also valid, but this is fine.

File: e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js [hunk 3]
```diff
@@ -285,6 +285,47 @@ describe("scenarios > embedding > dashboard parameters", () => {
       cy.findByTestId("scalar-value").invoke("text").should("eq", "1");
     });
 
+    it("should not apply IsSticky class to the parameter panel before it actually becomes sticky (metabase#66742)", () => {
+      H.visitDashboard("@dashboardId");
+      H.editDashboard();
+
+      // Duplicating twice to make a scrollable dashboard
+      H.getDashboardCard(0)
+        .realHover({ scrollBehavior: "bottom" })
```
Comment (heypoom) [inline e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js:294]: Nice, haven't seen realHover combined with scrollBehavior before 👍🏻

**Review by heypoom — APPROVED** [review]

File: frontend/src/metabase/dashboard/hooks/use-is-parameter-panel-sticky.ts (hunk 1 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/dashboard/hooks/use-is-parameter-panel-sticky.ts]: Ah no it was for me to understand the issue, I'll remove it, good catch

File: e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js (hunk 2 above)
Comment (lorem--ipsum) [reply e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js:322]: Hm but the problem isn't that it cannot find `IsSticky` in the className, it's rather that it tries to early and it cannot be here (even without my fix).

Comment (heypoom) [reply e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js:322]: ah alright, then your approach works!
