### PR TITLE
Use counter instead of `gensym` to make mongo field aliases unique

### LINKED ISSUE #37140: Caching not working for (all) mongo questions
### Describe the bug

A comeback of https://github.com/metabase/metabase/issues/25915, but reloaded with super powers

### To Reproduce

1) set up Metabase and a Mongo server
2) set a very very very low caching time (0.0000001 seconds), ttl 1000, size 204800
3) build a question that's hard for Mongo to do easily, like
image
4) save it
5) run it several times, see that the query never hits the cache

### Expected behavior

Caching should work for Mongo questions

### Logs

below

### Information about your Metabase installation

```JSON
v47.9+
```

### Severity

P1

### Additional context

```
2023-12-27 21:52:18,015 INFO query-processor.card :: Question's average execution duration is 12.1 s; using 'magic' TTL of 3.4 hours 💾
2023-12-27 21:52:18,019 TRACE query-processor.card :: Running query for Card 3:
{:constraints {:max-results 10000, :max-results-bare-rows 2000},
 :type :query,
 :middleware {:js-int-to-string? true, :ignore-cached-results? true, :process-viz-settings? false},
 :viz-settings nil,
 :database 2,
 :query
 {:source-table 10,
  :aggregation [[:sum [:field 113 {:base-type :type/Float}]]],
  :joins
  [{:fields :all,
    :alias "People",
    :condition [:= [:field 115 nil] [:field 126 {:join-alias "People"}]],
    :source-table 11}]},
 :parameters [],
 :async? true,
 :cache-ttl 12080}
```

seems we're caching it every time it runs
```
2023-12-27 21:52:18,100 TRACE middleware.permissions :: Checking query permissions. Current user perms set = #{"/download/db/4/" "/download/db/2/native/" "/collection/namespace/snippets/root/" "/download/db/3/native/" "/db/3/" "/collection/1/" "/" "/download/db/3/" "/download/db/2/" "/collection/root/" "/db/4/" "/db/2/" "/application/subscription/"}
2023-12-27 21:52:18,101 TRACE middleware.permissions :: Required perms to run Card: #{"/collection/root/read/"}
2023-12-27 21:52:18,104 TRACE middleware.cache :: Query is cacheable? true
2023-12-27 21:52:18,104 TRACE middleware.cache :: Running query and saving cached results (if eligible)...
2023-12-27 21:52:29,771 DEBUG middleware.format-rows :: Formatting rows with results timezone ID GMT
2023-12-27 21:52:29,771 TRACE cache.impl :: Freezing {:cols [{:name "sum"}], :cache-version 3, :last-ran #t "2023-12-27T21:52:29.771242Z[GMT]"}
2023-12-27 21:52:29,771 TRACE cache.impl :: Freezing [1595328.125160055]
2023-12-27 21:52:29,771 TRACE query-processor.reducible :: All rows consumed.
2023-12-27 21:52:29,771 TRACE cache.impl :: Freezing {:data {:cols ({:base_type :type/Float, :semantic_type nil, :settings nil, :name "sum", :display_name "Sum of Total", :source :aggregation, :field_ref [:aggregation 0], :effective_type :type/Float}), :download_perms :full, :native_form {:projections ["sum"], :query [{"$lookup" {:from "people", :let {"let_user_id_2864" "$user_id"}, :pipeline [{"$match" {"$expr" {"$eq" ["$$let_user_id_2864" "$id"]}}}], :as "join_alias_People"}} {"$unwind" {:path "$join_alias_People", :preserveNullAndEmptyArrays true}} {"$group" #ordered/map (["_id" nil] ["sum" {"$sum" "$total"}])} {"$sort" {"_id" 1}} {"$project" #ordered/map (["_id" false] ["sum" true])}], :collection "orders", :mbql? true}, :results_timezone "GMT"}}
2023-12-27 21:52:29,772 INFO middleware.cache :: Query took 11.7 s to run; minimum for cache eligibility is 100.0 ns
2023-12-27 21:52:29,772 INFO middleware.cache :: Caching results for next time for query with hash "efabc625". 💾
2023-12-27 21:52:29,772 TRACE cache.impl :: Getting result byte array
2023-12-27 21:52:29,772 TRACE middleware.cache :: Got serialized bytes; saving to cache backend
2023-12-27 21:52:29,772 DEBUG cache-backend.db :: Caching results for query with hash "efabc625".
2023-12-27 21:52:29,778 DEBUG middleware.cache :: Successfully cached results for query.
2023-12-27 21:52:29,778 TRACE middleware.cache :: Purging cache entries older than 14.3 weeks
2023-12-27 21:52:29,778 TRACE cache-backend.db :: Purging old cache entries.
2023-12-27 21:52:29,779 TRACE middleware.cache :: Successfully purged old cache entries.
2023-12-27 21:52:29,783 TRACE middleware.process-userland-query :: Saving QueryExecution info
2023-12-27 21:52:29,784 TRACE query-processor.reducible :: Port out-chan got {:database_id 2, :started_at #t "2023-12-27T21:52:18.020393Z[GMT]", :json_query {:constraints {:max-results 10000, :max-results-bare-rows 2000}, :type :query, :middleware {:js-int-to-string? true, :ignore-cached-results? true, :process-viz-settings? false}, :viz-settings nil, :database 2, :query {:source-table 10, :aggregation [[:sum [:field 113 {:base-type :type/Float}]]], :joins [{:fields :all, :alias "People", :condition [:= [:field 115 nil] [:field 126 {:join-alias "People"}]], :source-table 11}]}, :async? true, :cache-ttl 12080}, :average_execution_time nil, :status :completed, :context :question, :row_count 1, :running_time 11763, :data {:cols ({:base_type :type/Float, :semantic_type nil, :settings nil, :name "sum", :display_name "Sum of Total", :source :aggregation, :field_ref [:aggregation 0], :effective_type :type/Float}), :download_perms :full, :native_form {:projections ["sum"], :query [{"$lookup" {:from "people", :let {"let_user_id_2864" "$user_id"}, :pipeline [{"$match" {"$expr" {"$eq" ["$$let_user_id_2864" "$id"]}}}], :as "join_alias_People"}} {"$unwind" {:path "$join_alias_People", :preserveNullAndEmptyArrays true}} {"$group" #ordered/map (["_id" nil] ["sum" {"$sum" "$total"}])} {"$sort" {"_id" 1}} {"$project" #ordered/map (["_id" false] ["sum" true])}], :collection "orders", :mbql? true}, :results_timezone "GMT", :results_metadata {:columns [{:display_name "Sum of Total", :semantic_type nil, :settings nil, :field_ref [:aggregation 0], :name "sum", :base_type :type/Float, :effective_type :type/Float, :fingerprint {:global {:distinct-count 1, :nil% 0.0}, :type {:type/Number {:min 1595328.125160055, :q1 1595328.125160055, :q3 1595328.125160055, :max 1595328.125160055, :sd nil, :avg 1595328.125160055}}}}]}, :insights nil}}
2023-12-27 21:52:29,784 TRACE query-processor.reducible :: Closing out-chan.
```

but never gets retrieved

when I go to the DB I see it never hits the cache
image

in the caching table, theres a new query hash every time the query runs
image

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes #37140 

### Description

Prior to this PR we used `gensym` to make field aliases unique during compilation of mongo queries. That resulted in different compiled queries for a same mbql query. This PR changes compilation code to use counter instead of `gensym` to enable caching of compiled queries.

In [this comment](https://github.com/metabase/metabase/issues/37140#issuecomment-1871374133) I describe alternative solution. I've decided to implement this one instead as I believe it is desired to avoid randomness in compilation results if that is possible.

### How to verify

Follow reproduction steps from linked issue. The test that was added ensures that aliases are unique.

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 1]
```diff
@@ -1395,7 +1400,8 @@
   "Compile an MBQL query."
   [query]
   (let [query (update query :query preprocess)]
-    (binding [*query* query]
+    (binding [*query* query
+              *next-alias-index* (atom 0)]
```
Comment (lbrdnk) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:1404]: _Why use binding to atom?_ My current mental model is that we could have multiple threads compiling multiple mongo queries at once. As biding creates per-thread binding, this ensures that every compilation has its own counter.

I've decided to use binding as I think sending metadata (how many joins were compiled) as return values and arguments of compilation functions would make code more convoluted. If this approach is not desired, I'll change it.

Comment (metamben) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:1404]: We could emphasize the fact that this counter is not to be shared by using `volatile!` instead of `atom`.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 2]
```diff
@@ -105,6 +105,12 @@
   That is required eg. in `->lvalue :aggregation` call."
   0)
 
+(def ^:dynamic ^:private *next-alias-index*
+  "Tracks index of next alias for join compilation. It is bound in [[mbql->native]] to an atom valued 0. Hence every
+   compilation starts with a fresh 0. Indices are used in [[handle-join]] to make aliases unique. Index values
+   are gathered using `(swap *next-alias-index* inc)`, hence first used index is of value 1."
```
Comment (metamben) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:111]: It might make sense to create a function for  `(swap *next-alias-index* inc)`.

File: modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj [hunk 3]
```diff
@@ -532,3 +534,38 @@
 
         {"$expr" {"$eq" ["$price" {"$add" [{"$subtract" ["$price" 5]} 100]}]}}
         [:= $price [:+ [:- $price 5] 100]]))))
+
+(deftest uniqe-alias-index-test
+  (mt/test-driver
+   :mongo
+   (testing "Field aliases have unique indices"
```
Comment (metamben) [inline modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj:541]:
```suggestion
   (testing "Field aliases have deterministic unique indices"
```

**Review by metamben — APPROVED** [review]
👍

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 1 above)
Comment (lbrdnk) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj]: Done. I'll mind that for future. Thanks.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 2 above)
Comment (lbrdnk) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj]: Done.

**Comment by calherries** [comment]
@metabase-bot backport release-x.47.x
