### PR TITLE
Fix coercion for UNIX timestamp fields via implicit joins (#67704)

### LINKED ISSUE #67704: Filtering/Aggregating on a Coerced UNIX field via Implicit join Generates Invalid SQL
### Describe the bug

Casting an unix field to datetime generates invalid SQL if you filter on, or group by, the field via an implicit join.

### To Reproduce

1. Create a table with an ID and unix timestamp in postgres
2. Create a second table with fkey relationship to the first
3. Create a question from the 2nd table and then filter by the coerced field in the second through implicit join
4. View results and see error:

> ERROR: operator does not exist: integer >= timestamp with time zone
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 848

5. Edit the question and remove the filter. Count results and group by the field.
6. View results and see error:
> ERROR: function date_trunc(unknown, integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 124

Attached dataset query for each case.

[dataset_query_aggregation.json](https://github.com/user-attachments/files/24412854/dataset_query_aggregation.json)
[dataset_query_filter.json](https://github.com/user-attachments/files/24412855/dataset_query_filter.json)

### Expected behavior

Query should compile correctly.

### Logs

[ccd9e15b-80de-475a-8a91-e3f6fd2013d7] 2026-01-02T18:11:29-05:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: ERROR: operator does not exist: integer >= timestamp with time zone
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 848
{:database_id 7,
 :parameterized false,
 :started_at #t "2026-01-02T23:11:29.017748625Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: ERROR: operator does not exist: integer >= timestamp with time zone\n  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 848",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__93860$fn__93861.invoke(execute.clj:770)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__93860.invoke(execute.clj:767)"
    "driver.sql_jdbc.execute$fn__93635$fn__93636.invoke(execute.clj:422)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:347)"
    "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:327)"
    "driver.sql_jdbc.execute$fn__93635.invokeStatic(execute.clj:416)"
    "driver.sql_jdbc.execute$fn__93635.invoke(execute.clj:414)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:760)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:749)"
    "driver.sql_jdbc$fn__98545.invokeStatic(sql_jdbc.clj:87)"
    "driver.sql_jdbc$fn__98545.invoke(sql_jdbc.clj:85)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:59)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:44)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:119)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:108)"
    "query_processor.execute$run.invokeStatic(execute.clj:72)"
    "query_processor.execute$run.invoke(execute.clj:62)"
    "metabase_enterprise.database_routing.middleware$fn__148293$swap_destination_db__148294$fn__148295.invoke(middleware.clj:32)"
    "query_processor.middleware.enterprise$swap_destination_db_middleware$fn__79136.invoke(enterprise.clj:75)"
    "metabase_enterprise.impersonation.middleware$fn__135228$apply_impersonation_postprocessing__135229$fn__135230.invoke(middleware.clj:35)"
    "query_processor.middleware.enterprise$apply_impersonation_postprocessing_middleware$fn__79118.invoke(enterprise.clj:50)"
    "query_processor.middleware.update_used_cards$update_used_cards_BANG_$fn__80948.invoke(update_used_cards.clj:67)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__80988.invoke(execute.clj:27)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__80995.invoke(execute.clj:39)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___80867.invoke(cache.clj:248)"
    "query_processor.middleware.permissions$check_query_permissions$fn__73808.invoke(permissions.clj:153)"
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__136988$oss_or_ee_fn__47450__auto____136989$fn__136990.invoke(permissions.clj:65)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__79146.invoke(enterprise.clj:92)"
    "query_processor.execute$execute$fn__81027.invoke(execute.clj:99)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:223)"
    "query_processor.execute$execute.invokeStatic(execute.clj:98)"
    "query_processor.execute$execute.invoke(execute.clj:94)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:50)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:45)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__94079$handle_audit_app_internal_queries__94080$fn__94081.invoke(handle_audit_queries.clj:143)"
    "query_processor.middleware.enterprise$h...

### Information about your Metabase installation

```JSON
Happens in most recent version of v56 and v57. Works in v55.
```

### Severity

Preventing a customer from upgrading to 56 from 55

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by galdre**
Closes https://github.com/metabase/metabase/issues/67704

### Description

When a UNIX timestamp is accessed through an implicit join, the coercion to DateTime wasn't being applied. The `allow-casting?` check requires `pos-int?` on `::source-table` to apply coercion. For implicit joins, `::source-table` is set to a string, so it was being skipped.

Fix: in `add-alias-info/add-source-to-field-ref`, I'm setting the `:qp/allow-coercion-for-columns-without-integer-qp.add.source-table` flag. Cribbing this approach from the SparkSQL driver [here](https://github.com/metabase/metabase/blob/master/modules/drivers/sparksql/src/metabase/driver/sparksql.clj#L44) (a different condition -- there the driver is going to turn the ID into a string).

### How to verify

The test `coerced-field-via-implicit-join-test` fails without the fix. `coerced-field-via-explicit-join-test` passes before and after.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/query_processor/implicit_joins_test.clj [hunk 1]
```diff
@@ -286,3 +286,83 @@
...
+
+(deftest coerced-field-via-implicit-join-test
+  (testing "Filtering/aggregating on a coerced UNIX field via implicit join should apply coercion (#67704)"
+    (mt/test-drivers (mt/normal-drivers-with-feature :left-join)
+      (mt/dataset unix-timestamp-fk-dataset
+        (testing "Filter on coerced field via implicit join"
+            ;; This would fail with "operator does not exist: integer >= timestamp"
+            ;; if coercion is not applied to the implicitly joined field.
+          (let [query (mt/mbql-query logs
+                        {:aggregation [[:count]]
```
Comment (rileythomp) [inline test/metabase/query_processor/implicit_joins_test.clj]: nit: should/can these queries be constructed with lib methods?

**Review by rileythomp — APPROVED** [review]

**Review by metamben — APPROVED** [review]
