### PR TITLE
Fix login history emails

### LINKED ISSUE #15603: Login from new device emails not sending
It looks like it doesn't understand the timezone name `PT` which we're getting back from somewhere (IP address geocoding?). Should be an easy fix

```
4d2c8c89-e3bb-41d4-8500-74fe9818a6c5] 2021-04-13T13:41:15-07:00 ERROR metabase.models.login-history Error sending 'login from new device' notification email
clojure.lang.ExceptionInfo: Conversion failed {:path [[#object[java_time.graph.Types 0x3bc54985 "[java.lang.CharSequence]"] #object[java_time.graph.Types 0x3f498d04 "[java.time.ZoneId]"]]], :arguments ["PT"], :to java.time.ZoneId}
	at java_time.zone$zone_id$fn__25947.invoke(zone.clj:73)
	at java_time.zone$zone_id.invokeStatic(zone.clj:73)
	at java_time.zone$zone_id.invoke(zone.clj:73)
	at metabase.email.messages$send_login_from_new_device_email_BANG_.invokeStatic(messages.clj:193)
	at metabase.email.messages$send_login_from_new_device_email_BANG_.invoke(messages.clj:187)
	at metabase.models.login_history$post_insert$fn__57210.invoke(login_history.clj:71)
	at metabase.models.login_history$post_insert.invokeStatic(login_history.clj:69)
	at metabase.models.login_history$post_insert.invoke(login_history.clj:65)
	at toucan.models$fn__23565$fn__23676$G__23584__23681.invoke(models.clj:178)
	at toucan.db$insert_BANG_.invokeStatic(db.clj:611)
	at toucan.db$insert_BANG_.invoke(db.clj:597)
	at metabase.api.session$fn__73514$record_login_history_BANG___73519$fn__73520.invoke(session.clj:33)
	at metabase.api.session$fn__73514$record_login_history_BANG___73519.invoke(session.clj:31)
	at metabase.api.session$fn__73547$create_session_BANG___73539__73552$fn__73553.invoke(session.clj:61)
	at metabase.api.session$fn__73547$create_session_BANG___73539__73552.invoke(session.clj:49)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at metabase.api.session$fn__73574$create_session_BANG___73566__73579$fn__73580.invoke(session.clj:69)
	at metabase.api.session$fn__73574$create_session_BANG___73566__73579.invoke(session.clj:64)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.api.session$fn__73626$email_login__73631$fn__73632.invoke(session.clj:108)
	at metabase.api.session$fn__73626$email_login__73631.invoke(session.clj:103)
	at metabase.api.session$fn__73653$login__73658$fn__73659.invoke(session.clj:124)
	at metabase.api.session$fn__73653$login__73658.invoke(session.clj:118)
	at metabase.api.session$fn__73675$do_login__73678.invoke(session.clj:151)
	at metabase.api.session$fn__73675$fn__73681$fn__73682$fn__73683.invoke(session.clj:159)
	at throttle.core$do_with_throttling.invokeStatic(core.clj:93)
	at throttle.core$do_with_throttling.invoke(core.clj:87)
	at metabase.api.session$fn__73675$fn__73681$fn__73682.invoke(session.clj:157)
	at throttle.core$do_with_throttling.invokeStatic(core.clj:93)
	at throttle.core$do_with_throttling.invoke(core.clj:87)
	at metabase.api.session$fn__73675$fn__73681.invoke(session.clj:157)
	at metabase.api.session$do_http_400_on_error.invokeStatic(session.clj:134)
	at metabase.api.session$do_http_400_on_error.invoke(session.clj:132)
	at metabase.api.session$fn__73675.invokeStatic(session.clj:156)
	at metabase.api.session$fn__73675.invoke(session.clj:144)
	at compojure.core$wrap_response$fn__1996.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__1980.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__1985.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:151)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at metabase.api.session$_PLUS_log_all_request_failures$fn__73805.invoke(session.clj:355)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at compojure.core$make_context$handler__2036.invoke(core.clj:287)
	at compojure.core$make_context$fn__2038.invoke(core.clj:296)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at metabase.api.routes$fn__75715$fn__75717.invoke(routes.clj:70)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.server.routes$fn__77986$fn__77987.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at compojure.core$make_context$handler__2036.invoke(core.clj:287)
	at compojure.core$make_context$fn__2038.invoke(core.clj:296)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at metabase.server.routes$fn__77974$fn__77976.invoke(routes.clj:41)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75706.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__75703.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__77902$fn__77903.invoke(log.clj:195)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__77902.invoke(log.clj:189)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__77538.invoke(browser_cookie.clj:30)
	at metabase.server.middleware.security$add_security_headers$fn__75668.invoke(security.clj:142)
	at metabase.server.middleware.json$wrap_json_body$fn__77683.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__77701.invoke(json.clj:98)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__78243.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__78259.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__35489.invoke(misc.clj:58)
	at metabase.server.middleware.session$bind_current_user$fn__42461$fn__42462.invoke(session.clj:248)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:229)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:221)
	at metabase.server.middleware.session$bind_current_user$fn__42461.invoke(session.clj:247)
	at metabase.server.middleware.session$wrap_current_user_info$fn__42448.invoke(session.clj:207)
	at metabase.server.middleware.session$wrap_session_id$fn__42434.invoke(session.clj:153)
	at metabase.server.middleware.auth$wrap_api_key$fn__75601.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__78163.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__35472.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__35497.invoke(misc.clj:75)
	at ring.middleware.gzip$wrap_gzip$fn__78205.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__35500.invoke(misc.clj:92)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__77919.invoke(ssl.clj:48)
	at metabase.server$async_proxy_handler$fn__77482.invoke(server.clj:71)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.time.zone.ZoneRulesException: Unknown time-zone ID: PT
	at java.base/java.time.zone.ZoneRulesProvider.getProvider(Unknown Source)
	at java.base/java.time.zone.ZoneRulesProvider.getRules(Unknown Source)
	at java.base/java.time.ZoneRegion.ofId(Unknown Source)
	at java.base/java.time.ZoneId.of(Unknown Source)
	at java.base/java.time.ZoneId.of(Unknown Source)
	at java_time.zone$fn__25929.invokeStatic(zone.clj:32)
	at java_time.zone$fn__25929.invoke(zone.clj:31)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at java_time.defconversion$combinations$iter__25048__25052$fn__25053$fn__25054$fn__25055.doInvoke(defconversion.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at java_time.defconversion$wrap_validation$fn__25045.invoke(defconversion.clj:21)
	... 202 more
```

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #15603

The issue was we were converting the timezone we got as a result of geocoding the IP address to a human-friendly abbreviation string, e.g. `PT` (for Pacific Time); the email logic then attempted to convert this string back to a `ZoneId`, which failed, at least for `PT` -- the Java libs apparently don't know what zone `PT` refers to. The purpose of doing this in the first place was so we could coerce the login timestamp to the time zone for the associated location; this step was actually unneeded because, we were already doing this (using the original `ZoneId`) in `metabase.models.login-history` itself -- so all I had to do was remove that code from `metabase.email.messages`.

I also made some unrelated improvements to `metabase.util.date-2/format-human-friendly` so ZonedDateTimes come back like

`April 2, 2021 2:42:09 PM (Pacific Daylight Time)` instead of `April 2, 2021 2:42:09 PM PDT` -- not specifically related to this fix, but it was something I noticed while working on it and I think it looks a bit nicer.

### CODE REVIEW

File: src/metabase/email/messages.clj [hunk 1]
```diff
@@ -187,12 +187,10 @@
 (defn send-login-from-new-device-email!
   "Format and send an email informing the user that this is the first time we've seen a login from this device. Expects
   login history infomation as returned by `metabase.models.login-history/human-friendly-infos`."
-  [{user-id :user_id, :keys [timestamp timezone], :as login-history}]
+  [{user-id :user_id, :keys [timestamp], :as login-history}]
   (let [user-info    (db/select-one ['User [:first_name :first-name] :email :locale] :id user-id)
-        timestamp    (cond-> timestamp
-                       timezone (u.date/with-time-zone-same-instant (t/zone-id timezone))
```
Comment (camsaul) [inline src/metabase/email/messages.clj:193]: removing this line was the actual fix

File: src/metabase/models/login_history.clj [hunk 2]
```diff
@@ -30,7 +31,7 @@
                  :timezone (timezone-display-name timezone))
           (update :timestamp (fn [timestamp]
                                (if (and timestamp timezone)
-                                 (u.date/with-time-zone-same-instant timestamp timezone)
+                                 (t/zoned-date-time (u.date/with-time-zone-same-instant timestamp timezone) timezone)
                                  timestamp)))
```
Comment (camsaul) [inline src/metabase/models/login_history.clj:35]: not related to the fix itself but this tweaks means we always get back a ZonedDateTime rather than OffsetDateTime (depending on the DB) which means we can generate a nicer human-friendly timestamp in the emails

File: src/metabase/util/date_2.clj [hunk 3]
```diff
@@ -106,13 +106,22 @@
...
+                                  (.appendLiteral " (")
+                                  (.appendLocalizedOffset TextStyle/FULL)
+                                  (.appendLiteral ")"))]
                     (.toFormatter builder))
    OffsetDateTime (let [builder (doto (DateTimeFormatterBuilder.)
                                   (.appendLocalized FormatStyle/LONG FormatStyle/MEDIUM)
-                                  (.appendPattern " (OOOO)"))]
+                                  (.appendLiteral " (")
+                                  (.appendLocalizedOffset TextStyle/FULL)
+                                  (.appendLiteral ")"))]
```
Comment (camsaul) [inline src/metabase/util/date_2.clj:117]: this code does the same thing but I think `.appendLocalizedOffset` is a little clearer than `(.appendPattern "OOOO")` so I made this unrelated change here

File: src/metabase/util/date_2.clj [hunk 4]
```diff
@@ -106,13 +106,22 @@
...
                     (.toFormatter builder))
-   ZonedDateTime  (DateTimeFormatter/ofLocalizedDateTime FormatStyle/LONG)})
+   ZonedDateTime  (let [builder (doto (DateTimeFormatterBuilder.)
+                                  (.appendLocalized FormatStyle/LONG FormatStyle/MEDIUM)
+                                  (.appendLiteral " (")
+                                  (.appendZoneText TextStyle/FULL)
+                                  (.appendLiteral ")"))]
+                    (.toFormatter builder))})
```
Comment (camsaul) [inline src/metabase/util/date_2.clj:124]: Tweaked this so it returns a nice version of the timezone e.g. `(Pacific Daylight Time)` instead of a short abbreviation e.g. `PDT`

File: test/metabase/models/login_history_test.clj [hunk 5]
```diff
@@ -34,51 +35,61 @@
...
+      (let [device (str (java.util.UUID/randomUUID))]
+        (testing "send email on first login from *new* device (but not first login ever)"
+          (mt/with-fake-inbox
+            ;; mock out the IP address geocoding function so we can make sure it handles timezones like PST correctly
+            ;; (#15603)
+            (with-redefs [request.u/geocode-ip-addresses (fn [ip-addresses]
+                                                           (into {} (for [ip-address ip-addresses]
+                                                                      [ip-address
+                                                                       {:description "San Francisco, California, United States"
+                                                                        :timezone    (t/zone-id "America/Los_Angeles")}])))]
```
Comment (camsaul) [inline test/metabase/models/login_history_test.clj:49]: The `with-redefs` here caused this to fail before the fix

**Review by dpsutton — APPROVED** [review]

**Comment by dpsutton** [comment]
your fix for the read-only settings was nice. i did that and just redef'd the getter. I didn't think about the settings cache. That would be some good logic to capture.

File: test/metabase/models/login_history_test.clj (hunk 5 above)
Comment (dpsutton) [reply test/metabase/models/login_history_test.clj:49]: if i'm understanding correctly, you might want to return some gibberish in that timezone from the geocoding to ensure that no codepaths try to use it.

Comment (camsaul) [reply test/metabase/models/login_history_test.clj:49]: the stuff in `metabase.models.login-history/human-readable-info` does actually use it -- that's totally ok -- the issue was that `human-readable-info` converts `:timezone` to a human-friendly string (which is what we want for the API endpoint), but the email code tried to convert the string back to a `ZoneId`, which it didn't need to do.

Comment (camsaul) [reply test/metabase/models/login_history_test.clj:49]: We actually want a valid timezone here to test the code path that was failing -- previously it was just trying to geocode `127.0.0.1` or something which didn't result in a valid timezone, so #15603 didn't get triggered

File: test/metabase/models/login_history_test.clj [hunk 6]
```diff
@@ -34,51 +35,61 @@
...
+
+                (testing "don't send email on subsequent login from same device"
+                  (mt/reset-inbox!)
+                  (mt/with-temp LoginHistory [_ {:user_id user-id, :device_id device}]
+                    (is (= {}
+                           @mt/inbox)))))))))))
 
   (testing "don't send email if the setting is disabled by setting MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE=FALSE"
     (mt/with-temp User [{user-id :id, email :email, first-name :first_name}]
-      (testing "send email on first login from new device"
```
Comment (camsaul) [inline test/metabase/models/login_history_test.clj:70]: I just removed the `testing` context here because it was just copypasta from the test above and shouldn't have been here -- actual test itself it unchanged

File: test/metabase/models/login_history_test.clj (hunk 5 above)
Comment (dpsutton) [reply test/metabase/models/login_history_test.clj:49]: ah gotcha
