### PR TITLE
Fix static embedding or public embed outside iframe not working with #theme

### LINKED ISSUE #65731: Themes no longer work in public embedding
### Describe the bug

In v57, using `#theme=night` on a public link doesn't put the entity in dark mode. In v56 it does.

### To Reproduce

1. Start a v57 instance
2. Go to the example "E-commerce" dashboard
3. Create a public link and copy the link
4. Open a new tab, paste the link, and add `#theme=night`
5. The dashboard will still be in light mode

Trying the same on v56 will show the dashboard in dark mode.

### Expected behavior

Show the entity with whatever theme is passed in the URL

### Logs

_No response_

### Information about your Metabase installation

```JSON
v57.2
```

### Severity

Regression

### Additional context

See #65649 .
Note that new dark mode is not a replacement for anything here because dark mode is a user-level setting

### PR DESCRIPTION
**Pull request by WiNloSt**
closes #65731
Closes EMB-992

### Backport reason
This is a regression for 57, so there's no need to backport further than that.

### Description

Since we shipped dark mode https://github.com/metabase/metabase/pull/64016, the condition used to check whether the `#theme` should be used, was `isWithinIframe` that means it won't work with public link as it's not in an iframe, but it would work with public embed since it would be in an iframe.

### How to verify

Create a public link, then visit that link while appending `#theme=night`, you should see the dark theme.

### Demo
Screenshot 2025-11-12 at 4 55 52 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx [hunk 1]
```diff
@@ -154,7 +154,7 @@ const useColorSchemeFromHash = ({
 
 export const ThemeProvider = (props: ThemeProviderProps) => {
   const schemeFromHash = useColorSchemeFromHash({
-    enabled: getIsEmbeddingIframe(),
+    enabled: isStaticEmbedding() || isPublicEmbed(),
```
Comment (WiNloSt) [inline frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx]: The reason is that public link and even static embedding could be visited directly outside an iframe. When we do that, the `theme` hash parameter is ignored. And this fixes that bug.

File: frontend/src/metabase/embedding/config.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
+type InternalEmbeddingConfig = {
```
Comment (WiNloSt) [inline frontend/src/metabase/embedding/config.ts:1]: The whole file is structured in a way to look as closed to https://github.com/metabase/metabase/blob/42e08625133b25194cff9e49c6539a3e1510f239/frontend/src/metabase/embedding-sdk/config.ts

File: frontend/src/metabase/embedding/config.ts [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+  isPublicEmbed: boolean;
+  isStaticEmbedding: boolean;
```
Comment (heypoom) [inline frontend/src/metabase/embedding/config.ts]: Can we use either `Embed` or `Embedding` suffix? Using both feels inconsistent. Also, we should create an issue to move the `isEmbeddedAnalytics` and `isReactSdk` here so they all live together.

**Review by heypoom — APPROVED** [review]
nice!

File: frontend/src/metabase/embedding/config.ts (hunk 3 above)
Comment (WiNloSt) [reply frontend/src/metabase/embedding/config.ts]: haha, I almost commented, I forgot. The thing is that we always call them public _embed_ and static _embedding_ respectively. I also [have raised this question](https://metaboat.slack.com/archives/C063Q3F1HPF/p1762850018059569?thread_ts=1762801021.306739&cid=C063Q3F1HPF) before.

Comment (heypoom) [reply frontend/src/metabase/embedding/config.ts]: I see! That's a little weird, I feel like each embed types could naturally be called "public embeds" and "static embeds" 😰

Comment (WiNloSt) [reply frontend/src/metabase/embedding/config.ts]: fixed in 20db89a957191bd665436880446d5e936087458b
