### PR TITLE
Map Snowflake big integers to :type/BigInteger 

### LINKED ISSUE #63600: Snowflake: Cannot Cast Snowflake Number type to UNIX timestamps
### Describe the bug

For numeric types in Postgres and other engines it's possible to modify field settings and cast INT or NUMBER type column to UNIX timestamps. In Snowflake this casting option isn't available for NUMBER fields (though the engine supports this casting).

### To Reproduce

1. Set up a test table in Snowflake if you don't have one handy

```
CREATE OR REPLACE TABLE test_casting (
    id INT,          
    int_col INT,     
    num_col NUMBER 
);

INSERT INTO test_casting (id, int_col, num_col)
VALUES
    (1, 123, 456.789),
    (2, -42, 0.001);
```

2. Sync Snowflake to Metabase
3. From Table Metadata navigate to the fields and note that neither INT nor NUMBER fields have the cast to UNIX option

### Expected behavior

Should be able to cast to UNIX

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "athena",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-09-02",
      "tag": "v1.56.4",
      "hash": "aeaacd0"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "5.15.167.4-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #63600

Snowflake doesn't have a `BIGINTEGER` type... it uses `NUMBER`... however we can look at the JDBC type mapping in this case and if it's `java.sql.BigInteger` (which I think means it has a precision of zero?) we can map it to `:type/BigInteger` in sync.

### CODE REVIEW

File: modules/drivers/clickhouse/test/metabase/driver/clickhouse_introspection_test.clj [hunk 1]
```diff
@@ -463,8 +463,9 @@
                                {:name "count"
                                 :database-type "SimpleAggregateFunction(sum, Int64)"
                                 :base-type :type/BigInteger
-                                :database-position 4})}}
-             (driver/describe-table :clickhouse (mt/db) {:name "aggregate_functions_filter_test"}))))))
+                                :database-position 4})]}
+              (-> (driver/describe-table :clickhouse (mt/db) {:name "aggregate_functions_filter_test"})
+                  (update :fields (partial sort-by :name))))))))
```
Comment (camsaul) [inline modules/drivers/clickhouse/test/metabase/driver/clickhouse_introspection_test.clj]: flaky test fix if the columns come back in a different order

File: modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc_test.clj [hunk 2]
```diff
@@ -36,103 +36,104 @@
...
+                          {:name "venue_price",
+                           :database-type "BIGINT",
+                           :database-required false,
+                           :database-is-auto-increment false,
+                           :database-is-nullable true
+                           :base-type :type/BigInteger,
+                           :database-position 9,
+                           :json-unfolding false}]}
+                (-> (driver/describe-table :druid-jdbc (mt/db) {:schema "druid" :name "checkins"})
+                    (update :fields (partial sort-by :name))))))
```
Comment (camsaul) [inline modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc_test.clj:136]: another unrelated flaky test fix

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj [hunk 3]
```diff
@@ -444,11 +444,11 @@
 (deftest ^:sequential describe-table-test
   (mt/test-driver :snowflake
     (testing "make sure describe-table uses the NAME FROM DETAILS too"
-      (is (= {:name   "categories"
-              :schema "PUBLIC"
-              :fields #{{:name                       "id"
+      (is (=? {:name   "categories"
+               :schema "PUBLIC"
+               :fields [{:name                       "id"
```
Comment (camsaul) [inline modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj:449]: more flaky test fixes

**Review by rileythomp — APPROVED** [review]
