### PR TITLE
Do not show `PaymentBanner` on hosted instances

### LINKED ISSUE #50335: "Payment banner" shows on hosted instances
### Describe the bug

The "payment banner" is visible in hosted instances but it should be shown only on self-hosted ones instead. Hosted instances have the suspended page when the payment fails.

### To Reproduce

1. Be an admin of a hosted instance
2. Have an unpaid subscription
3. See the payment banner alerting you that the "pro features will not work" until the payment is resolved

### Expected behavior

Show this banner only for self-hosted Metabase instances.

### Logs

_No response_

### Information about your Metabase installation

```JSON
N/A
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nemanjaglumac**
Fixes #50335.

- [x] Tests have been added.

### CODE REVIEW

File: frontend/src/metabase/components/AppBanner/AppBanner.tsx [hunk 1]
```diff
@@ -3,15 +3,19 @@ import { useSelector } from "metabase/lib/redux";
...
+  const isHosted = useSelector(getIsHosted);
   const tokenStatus = useSetting("token-status");
   const readOnly = useSetting("read-only-mode");
 
   const paymentStatuses = ["past-due", "unpaid", "invalid"];
   const shouldRenderPaymentBanner =
-    tokenStatus && paymentStatuses.includes(tokenStatus?.status ?? "");
+    !isHosted &&
+    tokenStatus &&
+    paymentStatuses.includes(tokenStatus?.status ?? "");
```
Comment (kamilmielnik) [inline frontend/src/metabase/components/AppBanner/AppBanner.tsx:18]: Every string includes an empty string, so if `tokenStatus.status` is `undefined` this will be `true`

Comment (nemanjaglumac) [reply frontend/src/metabase/components/AppBanner/AppBanner.tsx:18]: image

Comment (nemanjaglumac) [reply frontend/src/metabase/components/AppBanner/AppBanner.tsx:18]: Added a test for this case as well. https://github.com/metabase/metabase/pull/50337/commits/06c2de326359a3845f73c012d0c79b08cac115cd

```
  AppBanner
    PaymentBanner
      ✓ should render past-due banner for admin user with tokenStatusStatus: past-due (22 ms)
      ✓ should render unpaid banner for admin user with tokenStatusStatus: unpaid (12 ms)
      ✓ should render an error with details when the token is `invalid` (19 ms)
      ✓ should not render for admin user with tokenStatusStatus: something-else (10 ms)
      ✓ should not render when token status is missing (13 ms) <<<<<<<<<
      ✓ should not render for hosted instances for past-due token status (metabase#50335) (11 ms)
      ✓ should not render for hosted instances for unpaid token status (metabase#50335) (10 ms)
      ✓ should not render for hosted instances for invalid token status (metabase#50335) (13 ms)
```

Comment (nemanjaglumac) [reply frontend/src/metabase/components/AppBanner/AppBanner.tsx:18]: > Every string includes an empty string

This is true for `String.prototype.includes` but we're operating on `Array.prototype.includes`.

Comment (kamilmielnik) [reply frontend/src/metabase/components/AppBanner/AppBanner.tsx:18]: Ah, it's an array, all good :+1:

**Review by kamilmielnik — APPROVED** [review]
:+1:
