### PR TITLE
propagate permissions fix

### LINKED ISSUE #20436: Restricting and unrestricting access to a table results in the DB-level permission still being "Granular"
**Describe the bug**
If you restrict data access to a single table in a database, and then change it back to unrestricted, the data access level in the UI for the entire database will display as "Granular" even though access to all the tables is unrestricted.

**To Reproduce**
1. On a fresh instance of Metabase, go Admin -> Permissions
2. Click on 'All Users'
3. Click on 'Sample Database'
4. Change the data access for a single table to 'No self-service', and save
5. Change the data access for that table back to 'Unrestricted', and save
6. Click on 'Sample Database' again. See that the data access is displayed as 'Granular', even though all tables have unrestricted access.

**Expected behavior**
Data access to the DB should go back to 'Unrestricted'

**Information about your Metabase Installation:**
Current master

**Severity**
Minor, but probably blocking some work for an upcoming project so serious in that regard.

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/20436

Databases can be fetched with or without tables. When tables were not included, metadata contained databases with empty `tables`, even though they were fetched in separate requests.

## How to verify
Check the original issue for repro steps

### CODE REVIEW

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/selectors/metadata.js [hunk 1]
```diff
@@ -149,7 +163,10 @@ export const getMetadata = createSelector(
 
     hydrate(meta.fields, "values", f => getFieldValues(f));
     hydrate(meta.fields, "remapping", f => new Map(getRemappings(f)));
-
+    console.log(">>>>>>>>>>>");
+    console.log(">>>databases", meta.databases);
+    console.log(">>>schemas", meta.schemas);
+    console.log(">>>tables", meta.tables);
```
Comment (iethree) [inline frontend/src/metabase/selectors/metadata.js:169]: did you mean to leave these in?
