### PR TITLE
XLSX Export truncate String cells to 32767 chars

### LINKED ISSUE #42115: Truncate columns to 32767 chars on xlsx exports to avoid errors
### Describe the bug

In https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3 MSFT says that "Total number of characters that a cell can contain" is 32,767 characters and we don´t respect that. We should truncate cells to avoid that

### To Reproduce

1) make a field with a long long long text
2) export it to xlsx
3) try to open it
4) see the error

### Expected behavior

We should truncate the cells

### Logs

```
{"database_id":34,"started_at":"2024-05-01T15:22:36.201995Z","via":[{"status":"failed","class":"class clojure.lang.ExceptionInfo","error":"Error reducing result rows: The maximum length of cell contents (text) is 32767 characters","stacktrace":["--> query_processor.context.default$default_reducef$fn__50537.invoke(default.clj:36)","query_processor.context.default$default_reducef.invokeStatic(default.clj:33)","query_processor.context.default$default_reducef.invoke(default.clj:25)","query_processor.context$reducef.invokeStatic(context.clj:70)","query_processor.context$reducef.invoke(context.clj:63)","query_processor.context.default$default_runf$respond_STAR___50541.invoke(default.clj:45)","driver.sql_jdbc.execute$execute_reducible_query$fn__79421.invoke(execute.clj:710)","driver.sql_jdbc.execute$fn__79214$fn__79215.invoke(execute.clj:389)","driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:335)","driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:318)","driver.sql_jdbc.execute$fn__79214.invokeStatic(execute.clj:383)","driver.sql_jdbc.execute$fn__79214.invoke(execute.clj:381)","driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:693)","driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:679)","driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:690)","driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:679)","driver.sql_jdbc$fn__112725.invokeStatic(sql_jdbc.clj:78)","driver.sql_jdbc$fn__112725.invoke(sql_jdbc.clj:76)","query_processor.context$executef.invokeStatic(context.clj:60)","query_processor.context$executef.invoke(context.clj:49)","query_processor.context.default$default_runf.invokeStatic(default.clj:44)","query_processor.context.default$default_runf.invoke(default.clj:42)","query_processor.context$runf.invokeStatic(context.clj:46)","query_processor.context$runf.invoke(context.clj:40)","query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)","query_processor.reducible$identity_qp.invoke(reducible.clj:36)","query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___72244.invoke(cache.clj:229)","query_processor.middleware.permissions$check_query_permissions$fn__66601.invoke(permissions.clj:140)","query_processor.middleware.enterprise$check_download_permissions_middleware$fn__72065.invoke(enterprise.clj:51)","query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__72075.invoke(enterprise.clj:64)","query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71507.invoke(mbql_to_native.clj:24)","query_processor$fn__73412$combined_post_process__73417$combined_post_process_STAR___73418.invoke(query_processor.clj:262)","query_processor$fn__73412$combined_pre_process__73413$combined_pre_process_STAR___73414.invoke(query_processor.clj:259)","query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66698.invoke(fetch_source_query.clj:299)","query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72155$fn__72159.invoke(resolve_database_and_driver.clj:77)","driver$do_with_driver.invokeStatic(driver.clj:97)","driver$do_with_driver.invoke(driver.clj:92)","query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72155.invoke(resolve_database_and_driver.clj:76)","query_processor.middleware.store$initialize_store$fn__67325$fn__67326.invoke(store.clj:14)","query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)","query_processor.store$do_with_metadata_provider.invoke(store.clj:150)","query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)","query_processor.store$do_with_metadata_provider.invoke(store.clj:150)","query_processor.middleware.store$initialize_store$fn__67325.invoke(store.clj:13)","query_processor.middleware.resolve_database_and_driver$resolve_database$fn__72152.invoke(resolve_database_and_driver.clj:60)","query_processor.middleware.normalize_query$normalize$fn__72457.invoke(normalize_query.clj:38)","query_processor.middleware.enterprise$fn__72092$handle_audit_app_internal_queries__72093$fn__72095.invoke(enterprise.clj:96)","query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__72103.invoke(enterprise.clj:103)","query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__71218.invoke(constraints.clj:104)","query_processor.middleware.process_userland_query$process_userland_query$fn__72388.invoke(process_userland_query.clj:156)","query_processor.middleware.catch_exceptions$catch_exceptions$fn__72989.invoke(catch_exceptions.clj:171)","query_processor.reducible$async_qp$qp_STAR___62839$thunk__62841.invoke(reducible.clj:126)","query_processor.reducible$async_qp$qp_STAR___62839$fn__62843.invoke(reducible.clj:131)"],"error_type":"qp","ex-data":{"type":"qp"}}],"action_id":null,"error_type":"qp","json_query":{"constraints":null,"type":"query","middleware":{"js-int-to-string?":false,"ignore-cached-results?":true,"process-viz-settings?":true,"skip-results-metadata?":true,"format-rows?":false},"viz-settings":null,"database":34,"query
```

### Information about your Metabase installation

```JSON
v49.x
```

### Severity

P3

### Additional context

NA

### PR DESCRIPTION
**Pull request by lyulifeng**
Fixes https://github.com/metabase/metabase/issues/42115

### Description

Truncate String cells to 32767 on XLSX export to avoid errors

### How to verify

1. make a field with a long long long text over 32767 chars
2. export it to xlsx
3. can open it normally

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 1]
```diff
@@ -345,7 +345,7 @@
 
 (defmethod set-cell! String
   [^Cell cell value _styles _typed-styles]
-  (.setCellValue cell ^String value))
+  (.setCellValue cell ^String (if (> (count value) 32767) (subs value 0 32767) value)))
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming/xlsx.clj:348]: We have a helper function `metabase.util/truncate` that can be used here instead

Comment (noahmoss) [reply src/metabase/query_processor/streaming/xlsx.clj:348]: The limit value would probably also be worth pulling out into a standalone var. You can mark it as `*dynamic*` to make it easier to test (by re-binding it to a smaller value in the test). You can see an example with the existing `*auto-sizing-threshold*` constant.

**Review by noahmoss — CHANGES_REQUESTED** [review]
Hi @givemesomefaces, thank you for your contribution! And apologies for the delay in getting a review.

If you could address my comments and add a new test case in `metabase.query-processor.streaming.xlsx-test`, this should be good to merge. I'm also happy to take this over and make the changes myself if you'd prefer.

**Comment by givemesomefaces** [comment]
> Hi @givemesomefaces, thank you for your contribution! And apologies in the delay in getting a review.
> 
> If you could address my comments and add a new test case in `metabase.query-processor.streaming.xlsx-test`, this should be good to merge. I'm also happy to take this over and make the changes myself if you'd prefer.

@noahmoss Hi, Thank you for your review. I completely understand that reviews are too many and can take time. And I am so glad you did review this. I'll follow your suggestions and just need a little time :)

File: src/metabase/query_processor/streaming/xlsx.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/query_processor/streaming/xlsx.clj:348]: I think it's also worth clarifying if 32767 applies to number of characters or number of bytes

Comment (givemesomefaces) [reply src/metabase/query_processor/streaming/xlsx.clj]: > I think it's also worth clarifying if 32767 applies to number of characters or number of bytes

It should be the number of characters. In what cases would it be the number of bytes?
https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3

**Comment by givemesomefaces** [comment]
Hi, @noahmoss please review this again when you have time, thank you.

**Review by noahmoss — APPROVED** [review]

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 2]
```diff
@@ -344,9 +344,14 @@
   [^Cell cell t styles typed-styles]
   (set-cell! cell (t/offset-date-time t) styles typed-styles))
 
+(def ^:dynamic *number-of-characters-cell*
+  "Total number of characters that a cell can contain, 32767 is the maximum number supported by the cell."
+  ;;See https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming/xlsx.clj:349]:
```suggestion
  ;; See https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
```

File: test/metabase/query_processor/streaming/xlsx_test.clj [hunk 3]
```diff
@@ -774,3 +774,9 @@
       (do-export)
       ;; Should always allocate less than 100Mb.
       (is (< (- (get-allocated-bytes) start-bytes) (* 100 1024 1024))))))
+
+(deftest number-of-characters-cell-test
+  (testing "When the number of characters exceeds *number-of-characters-cell*, the excess part will be truncated."
+    (binding [qp.xlsx/*number-of-characters-cell* 5]
+      (is (= ["abcde"]
+           (second (xlsx-export [{:id 0, :name "Col"}] {} [["abcdefghijklmnopqrstuvwxyz"]])))))))
```
Comment (noahmoss) [inline test/metabase/query_processor/streaming/xlsx_test.clj:782]:
```suggestion
      (is (= ["abcde"]
             (second (xlsx-export [{:id 0, :name "Col"}] {} [["abcdefghijklmnopqrstuvwxyz"]])))))))
```

**Comment by noahmoss** [comment]
@metabase-bot backport release-x.52.x
