### PR TITLE
Fix: UXW-42 Debounce on the visualization resize is causing layout jumping

### LINKED ISSUE #54147: Debounce on the visualization resize is causing layout jumping
### Describe the bug

Some funny behavior [when I go from the table to summarize](https://www.loom.com/share/d01869107734493386122072f7626aef) and back. I think the debounce on the visualization resize or something is causing this funny sense of the layout jumping when you to between a table and a roll up. It’s likely been there for a bit but I’m noticing it more today for some reason.

### To Reproduce

 Shown in loom above

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
NA
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bpander**
Closes https://github.com/metabase/metabase/issues/54147
Closes UXW-42

### Description

Tweaks DebouncedFrame so it accepts a resetKey prop which can be used to trigger an immediate update rather than a debounced one without remounting.

### How to verify

See https://github.com/metabase/metabase/issues/54147 for repro steps.

Check for resize regressions anywhere DebouncedFrame is used.

### Demo

**BEFORE**

https://github.com/user-attachments/assets/b0c59d30-7e9f-428f-b777-a80f60275559

**AFTER**

https://github.com/user-attachments/assets/7a62196b-ed91-4b9d-83f9-7ff826f632f1

**BEFORE (dashboard)**

https://github.com/user-attachments/assets/6bb9b33a-7732-4e0c-b61b-b1379169c0e0

**AFTER (dashboard)**

https://github.com/user-attachments/assets/6b15f0f8-c800-47ae-a1a2-405a3dcbeb49

### Checklist

- [n/a] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/common/components/DebouncedFrame/DebouncedFrame.jsx [hunk 1]
```diff
@@ -123,4 +140,7 @@ const DebouncedFrameForwardRef = forwardRef(
   },
 );
 
-export default ExplicitSize()(DebouncedFrameForwardRef);
+export default ExplicitSize({
+  // Disable ExplicitSize's debounce/throttle since DebouncedFrame has a built-in debounce
+  refreshMode: "none",
```
Comment (bpander) [inline frontend/src/metabase/common/components/DebouncedFrame/DebouncedFrame.jsx:145]: 💭 This _does_ change some other behavior. Somewhat confusingly, on master, DebouncedFrame's resizing is **throttled**, not debounced (because of ExplicitSize's default refreshMode). It's really only noticeable when you resize **slowly**.

**BEFORE (master) - throttle**

https://github.com/user-attachments/assets/75db3f04-2854-48d9-9321-947dda3ae090

**AFTER (this branch) - debounce**

https://github.com/user-attachments/assets/67b8fc14-2406-4ef5-be18-5e8821b3d899

I have a slight preference for the "after" because it looks less jittery, it's simpler, and it's less confusing (you don't have a throttle AND a debounce competing with each other). Resizing scalars is also much more smooth now. And the previous behavior strikes me as somewhat unintentional. And it only applies to **slow** resizes (which feels pretty edge-case-y).

However, if people prefer the "before" behavior, I pushed up a commit to a side branch that we can merge into this PR: bcced735af

**Review by alxnddr — APPROVED** [review]
🏅
