### PR TITLE
fix(sdk): remove unsafe lifecycle errors from DashboardGrid

### LINKED ISSUE #48497: Fix UNSAFE_componentWillReceiveProps and UNSAFE_componentWillMount React errors in strict mode

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/48497, ENG-8667

This PR combined with https://github.com/metabase/metabase/pull/52885 will close the above issue, but 52885 is more likely to get merged before this one

### Description

Removes the unsafe React lifecycle from the `<DashboardGrid />` component, which was causing console errors:

- Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code

It does this by replacing `UNSAFE_componentWillReceiveProps` with `static getDerivedStateFromProps`, refer to https://github.com/metabase/metabase/pull/52885 for how that works

### How to verify

Verification with manual tests

- Run the SDK and render a InteractiveDashboard (which should render a DashboardGrid)
- The UNSAFE_componentWillReceiveProps should still be there, but come from other components (e.g. Table, TableInteractive, Link from react-router 3)

Verification with end-to-end tests

- Add a dummy UNSAFE_componentWillReceiveProps to DashboardGrid.jsx
- The SDK end-to-end test now errors due to unsafe lifecycle being in Visualization

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/DashboardGrid.tsx [hunk 1]
```diff
@@ -175,17 +186,31 @@ class DashboardGridInner extends Component<
       props.dashcardData,
     );
 
+    const initialCardSizes = getInitialCardSizes(
+      props.dashboard.dashcards,
+      this.state?.initialCardSizes,
```
Comment (heypoom) [inline frontend/src/metabase/dashboard/components/DashboardGrid.tsx:191]: Has to be optional chained otherwise it cause errors. This is also the case in the original diff https://github.com/metabase/metabase/pull/53213/files#diff-156bd6482f18fc7a624b700eae3c05243a2c7965a14a84b423f7fe2e25d2618fL320-L328 - let's keep it the same as before

File: frontend/src/metabase/dashboard/components/DashboardGrid.tsx [hunk 2]
```diff
@@ -221,48 +246,70 @@ class DashboardGridInner extends Component<
...
+  ) {
     const { dashboard, dashcardData, isEditing, selectedTabId } = nextProps;
+    const lastProps = state._lastProps;
+
+    if (
+      !lastProps ||
+      !_.isEqual(dashboard.dashcards, lastProps.dashboard.dashcards) ||
+      !_.isEqual(dashcardData, lastProps.dashcardData) ||
+      isEditing !== lastProps.isEditing ||
+      selectedTabId !== lastProps.selectedTabId
```
Comment (heypoom) [inline frontend/src/metabase/dashboard/components/DashboardGrid.tsx:261]: Only trigger state updates if these props changed

File: frontend/src/metabase/dashboard/grid-utils.ts [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+import { DEFAULT_CARD_SIZE } from "metabase/lib/dashboard_grid";
+import { getVisualizationRaw } from "metabase/visualizations";
+import type {
+  BaseDashboardCard,
+  DashboardTabId,
+} from "metabase-types/api/dashboard";
+
+import { generateMobileLayout } from "./components/grid/utils";
+
+export function getLayoutForDashCard(
```
Comment (heypoom) [inline frontend/src/metabase/dashboard/grid-utils.ts:12]: These are just copy-and-pasted from the instance methods of DashboardGrid and make into a dependency-free pure function, should be 100% identical as the one in the class.

File: frontend/src/metabase/dashboard/components/DashboardGrid.tsx [hunk 4]
```diff
@@ -221,48 +246,70 @@ class DashboardGridInner extends Component<
...
+      const lastVisibleCards = lastProps?.dashboard?.dashcards
+        ? getVisibleCards(
+            lastProps.dashboard.dashcards,
+            state.visibleCardIds,
+            lastProps.isEditing,
+            lastProps.selectedTabId,
+          )
+        : [];
+
+      const hasVisibleDashcardsChanged = _.isEqual(
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/components/DashboardGrid.tsx:287]: this looks wrong, if they're equal they're not changed. You probably need to add `!` to the value and remove it from where this var is used, if you wanna keep this name.

File: frontend/src/metabase/dashboard/components/DashboardGrid.tsx (hunk 2 above)
Comment (WiNloSt) [reply frontend/src/metabase/dashboard/components/DashboardGrid.tsx:261]: I'd rather you don't have this logic, I'm fine with it in https://github.com/metabase/metabase/pull/52885 because it existed before. This was never here, and the behavior would change. I'd rather keep the behavior closer to the before-refactor version.

File: frontend/src/metabase/dashboard/components/DashboardGrid.tsx (hunk 4 above)
Comment (heypoom) [reply frontend/src/metabase/dashboard/components/DashboardGrid.tsx:287]: Good eye! It is indeed wrong, let me update it

File: frontend/src/metabase/dashboard/components/DashboardGrid.tsx (hunk 2 above)
Comment (heypoom) [reply frontend/src/metabase/dashboard/components/DashboardGrid.tsx:261]: @WiNloSt good observation, since `getDerivedStateFromProps` only updates the keys you passed to it similar to `this.setState(...)` it should not override any existing states. Let me remove this check then

Comment (heypoom) [reply frontend/src/metabase/dashboard/components/DashboardGrid.tsx]: fixed in https://github.com/metabase/metabase/pull/53213/commits/a7b1c5893ce46e3d2f6038a76363d48db1d0dfd2

File: frontend/src/metabase/dashboard/components/DashboardGrid.tsx (hunk 4 above)
Comment (heypoom) [reply frontend/src/metabase/dashboard/components/DashboardGrid.tsx]: fixed in https://github.com/metabase/metabase/pull/53213/commits/7c9a132ecdab7b0f5654466438d5c396a2062c18

**Review by WiNloSt — APPROVED** [review]
Looks good to me.

**Review by alxnddr — APPROVED** [review]

**Comment by heypoom** [comment]
@metabase-bot backport release-x.52.x
