### PR TITLE
Make object detail viz work for non-logged-in users

### LINKED ISSUE #29324: Object detail view is not working on public questions and dashboards
**Describe the bug**
Object detail view is not working on public questions and dashboards

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create an object detail question from the Sample dataset -> Orders table
2. Share the question and open the public link in incognito mode — it does not show
3. Add the same question on a dashboard, share the dashboard, and open its public link — it does not work too

**Expected behavior**
Should be showing the object detail view on public questions/dashboards

**Information about your Metabase Installation:**
Latest `master`

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/29324

### Description

Object detail has two "modes" - Visualization mode and Modal Mode. In Modal mode, it has some bonus features where it tries to use table metadata and foreign keys to pull in extra information about linked records. Users who are not logged in don't have access to that data, so the vanilla visualization was erroring. 

This adds a simple check that skips all the metadata selectors and magic for users that are not logged in. The visualization just falls back gracefully to only using the data passed to it.

Screen Shot 2023-03-17 at 12 53 40 PM

### How to verify

1. make a question on any table and set it to detail viz.
2. make the question public
3. add the question to a dashboard
4. make that dashboard public
5. in an incognito window, verify that the detail viz works for both the public question and public dashboard.

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx [hunk 1]
```diff
@@ -61,6 +63,12 @@ import {
...
 
 const mapStateToProps = (state: State, { data }: ObjectDetailProps) => {
+  const isLoggedIn = !!getUser(state);
+
+  if (!isLoggedIn) {
+    return {};
+  }
+
   const table = getTableMetadata(state);
   let zoomedRowID = getZoomedObjectId(state);
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx:73]: Oh, so the issue is that it is connected to our store and depends on its shape 🤔 Here particularly it depends on the QueryBuilder state even though it can be rendered outside of it. Ideally, it would be great to untie the ObjectDetails from it but I assume it is a significant effort

**Review by alxnddr — COMMENTED** [review]
Works as expected 👍 Can you please add a spec on this?

**Review by alxnddr — APPROVED** [review]
