### PR TITLE
fix: Don't show error page when command palette documentation link is clicked

### LINKED ISSUE #47829: Selecting search doc option in Command Palette is resulting in "An error occurred"
### Describe the bug

When using Command Palette to search for doc, when you click on "Search documentation ..." option, it will open a new tab for the doc (good), but the existing tab will now show "An error occurred" (not good). 

### To Reproduce

1. Open Command Palette
2. Search for something
3. Select "Search Documentation ..."
4. A new tab opens for doc while existing tab shows error. 

### Expected behavior

Existing tab should stay the same with Command Palette open or closed but not error. 

### Logs

n/a

### Information about your Metabase installation

```JSON
Postgres @ Master
```

### Severity

Medium as it confuses user but mostly cosmetic

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rafpaf**
Closes #47829

### Description

The bug: when you click or press enter on a command palette documentation link, the documentation opens in another tab, but the page where the command palette was displayed changes to an error page. In this branch, we fix this problem by preventDefault'ing the link's normal behavior.

### How to verify

Search for "asdf" in the command palette. You'll see a documentation link below the results. ("asdf" ensures that there are no results, which is convenient.) Try the following:

* Click the link
* Press enter while the link is selected
* Right click and open in new tab
* Middle click to open a new tab (if this works in your environment)

[Loom](https://www.loom.com/share/de524315c8e54751aaf494bbf05fd87a?sid=de1af7c8-4bf0-4d87-b5dc-20357eab5b3e) - this shows that left clicking and middle clicking on documentation and view-results links works, whether Metabase is hosted normally or on a subpath. Pressing enter also works, but I forgot to include that in the video.

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#47862** <a href="https://app.graphite.dev/github/pr/metabase/metabase/47862?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: frontend/src/metabase/palette/components/PaletteResultItem.tsx [hunk 1]
```diff
@@ -27,13 +26,13 @@ export const PaletteResultItem = ({ item, active }: PaletteResultItemProps) => {
...
-        cursor: item.disabled ? "default" : "cursor",
+        cursor: item.disabled ? "default" : "pointer",
         borderRadius: "0.5rem",
         flexGrow: 1,
         flexBasis: 0,
       }}
-      bg={active ? color("brand") : "none"}
-      c={active ? color("text-white") : color("text-dark")}
+      bg={active ? "var(--mb-color-brand)" : undefined}
+      c={active ? "var(--mb-color-text-white)" : "var(--mb-color-text-dark)"}
```
Comment (rafpaf) [inline frontend/src/metabase/palette/components/PaletteResultItem.tsx:35]: switching these in passing to our new way

**Review by npfitz — CHANGES_REQUESTED** [review]
I think the main issue here is that the `<Link>` component from react-router doesn't handle external links, but we're rendering one so that left click menus work. We may need to extend the language a bit to say that this is a <a>, not a <Link>

File: frontend/src/metabase/palette/components/PaletteResultItem.tsx [hunk 2]
```diff
@@ -113,7 +120,17 @@ export const PaletteResultItem = ({ item, active }: PaletteResultItemProps) => {
...
-      <Box component={Link} to={item.extra.href} w="100%">
+      <Box
+        component={Link}
+        to={item.extra.href}
+        w="100%"
+        onClick={e => {
+          // We provide a link to enable right clicking and middle clicking.
+          // The opening of the link on left click is already handled by the
+          // 'perform' callback, so we prevent the default behavior here.
+          e.preventDefault();
```
[the remark this answers is not in the document]
Comment (npfitz) [reply frontend/src/metabase/palette/components/PaletteResultItem.tsx:131]: chrome_LKpBXBnzBt

File: frontend/src/metabase/palette/components/PaletteResultItem.unit.spec.tsx [hunk 3]
```diff
@@ -21,9 +22,23 @@ const setup = ({
...
+        component={() => (
+          <PaletteResultItem
+            item={mockPaletteActionImpl(item)}
+            active={active}
+          />
+        )}
+      />
+      <Route path="search" component={() => null} />
+    </>,
+    { withRouter: true },
```
Comment (rafpaf) [inline frontend/src/metabase/palette/components/PaletteResultItem.unit.spec.tsx:38]: note to self: I can revert this change

File: frontend/src/metabase/palette/components/PaletteResultsList.unit.spec.tsx [hunk 4]
```diff
@@ -0,0 +1,132 @@
+import { Route } from "react-router";
```
Comment (rafpaf) [inline frontend/src/metabase/palette/components/PaletteResultsList.unit.spec.tsx:1]: note to self: probably should move this into PaletteResultItem.unit.spec.tsx, and the setup function here can become setupList there

File: frontend/src/metabase/core/components/TabLink/TabLink.tsx [hunk 5]
```diff
@@ -7,7 +7,7 @@ import { TabContext, getTabId, getTabPanelId } from "../Tab";
 
 import { TabLabel, TabLinkRoot } from "./TabLink.styled";
 
-export interface TabLinkProps<T> extends LinkProps {
+export interface TabLinkProps<T> extends Omit<LinkProps, "value"> {
   value?: T;
 }
```
Comment (rafpaf) [inline frontend/src/metabase/core/components/TabLink/TabLink.tsx:12]: Because of the change I made to `LinkProps`, we need to make this small change. No other changes are needed.

File: frontend/src/metabase/palette/components/PaletteResultsList.tsx [hunk 6]
```diff
@@ -120,7 +120,7 @@ export const PaletteResultList: React.FC<PaletteResultListProps> = props => {
       if (item.command) {
         item.command.perform(item);
         query.toggle();
-      } else {
+      } else if (!item.extra?.href) {
         query.setSearch("");
         query.setCurrentRootAction(item.id);
       }
```
Comment (rafpaf) [inline frontend/src/metabase/palette/components/PaletteResultsList.tsx:126]: <i class='graphite__hidden'>[Re: line +128]<br/><br/></i>

With this change, we don't have to include a no-op `perform` function when adding an external link to the command palette results.<span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/metabase/metabase/47862?utm_source=unchanged-line-comment">Graphite</a>.</span>

File: frontend/src/metabase/palette/components/PaletteResultsList.tsx [hunk 7]
```diff
@@ -120,7 +120,7 @@ export const PaletteResultList: React.FC<PaletteResultListProps> = props => {
       if (item.command) {
         item.command.perform(item);
         query.toggle();
-      } else {
+      } else if (!item.extra?.href) {
```
Comment (rafpaf) [inline frontend/src/metabase/palette/components/PaletteResultsList.tsx:123]: With this change, we don't have to include a no-op `perform` function when adding an external link to the command palette results.

File: frontend/src/metabase/palette/components/PaletteResultItem.unit.spec.tsx [hunk 8]
```diff
@@ -1,9 +1,17 @@
-import { render, screen } from "__support__/ui";
-import { color } from "metabase/lib/colors";
+import { Route } from "react-router";
+
+import {
+  fireEvent,
```
Comment (npfitz) [inline frontend/src/metabase/palette/components/PaletteResultItem.unit.spec.tsx:4]: Are we able to use UserEvent to do our clicking instead? I think that generally the preferred way to click things in tests

File: frontend/src/metabase/palette/components/PaletteResultItem.unit.spec.tsx [hunk 9]
```diff
@@ -62,3 +70,108 @@ describe("PaletteResultItem", () => {
     expect(screen.queryByRole("img")).not.toBeInTheDocument();
   });
 });
+
+/** For some tests we need to render the PaletteResultsList so that the Enter key works */
+const setupInList = ({ item }: { item: Partial<PaletteActionImpl> }) => {
```
Comment (npfitz) [inline frontend/src/metabase/palette/components/PaletteResultItem.unit.spec.tsx:75]: Would it make sense to do these tests in `PaletteResultsList.unit.spec.tsx`?

File: frontend/src/metabase/palette/components/PaletteResultsList.tsx (hunk 7 above)
Comment (npfitz) [reply frontend/src/metabase/palette/components/PaletteResultsList.tsx:123]: Nice!

**Review by npfitz — COMMENTED** [review]
Some small comments, but nothing major. I'm not totally sure why we needed to make changes to `core/components/Link` though, was it just for typing? Would it be possible to get this functionality without making changes here?

File: frontend/src/metabase/palette/components/PaletteResultItem.unit.spec.tsx (hunk 9 above)
Comment (rafpaf) [reply frontend/src/metabase/palette/components/PaletteResultItem.unit.spec.tsx:75]: I originally put them there, but these aren't really tests of that component

**Review by npfitz — APPROVED** [review]

File: frontend/src/metabase/core/components/Link/types.ts
Comment (rafpaf) [inline frontend/src/metabase/core/components/Link/types.ts:1]: Nick and I thought that `core/components/Link` and react-router's `Link` were fundamentally different, and I think that confusion stemmed from the fact that, on `master`, their props have quite different types. But actually `core/components/Link` is just a styled react-router `Link`, with a little extra spice for tooltips.

I've simplified the types here to make this clearer. The seven props deleted from the `LinkProps` definition in this file here are already included in react-router's `LinkProps`, so we don't need to redefine them.

Something that was causing confusion: the type of `to` in react-router is not `string` but `LocationDescriptor | ToLocationFunction`. `LocationDescriptor` can be a string or an object like `{pathname: "/a/b/c"}`. See `node_modules/@types/react-router/lib/IndexLink.d.ts`
