### PR TITLE
Strip semicolons from card refs in native queries

### LINKED ISSUE #28218: Using semicolon in Model definition leads to error in native sql questions
**Describe the bug**
When ending SQL statements with a semicolon and turning them into models, they cannot be used in further SQL queries. Instead, one must remove the semicolon to be able to query the model.

Error message:
```Syntax error in SQL statement " SELECT * FROM (SELECT TOTAL - TAX AS NETREVENUE, * FROM ORDERS O;[*]) "; expected "(, USE, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement: SELECT * FROM (select total - tax as NetRevenue, * from orders o;) [42001-197]```


**Logs**
<details>
  <summary>Full Stacktrace:</summary>

```
2023-02-10 15:09:26,597 ERROR middleware.catch-exceptions :: Error processing query: Syntax error in SQL statement "                                                                                    [121/10880]
                                                                                                                                                                                                                   SELECT * FROM                                                                                                                                                                                                      (SELECT TOTAL - TAX AS NETREVENUE, *                                                                                                                                                                               
FROM ORDERS O;[*]) "; expected "(, USE, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )"; SQL statement:             
-- Metabase:: userID: 1 queryType: native queryHash: e4c548f308a6f1b98a396a3d3e36b8216ef8ea506d4d5048eeca704e11bfdf3d                                                                                              
SELECT * FROM                                                                                                                                                                                                      
(select total - tax as NetRevenue, *                                                                                                                                                                               
from orders o;) [42001-197]                                                                                                                                                                                        {:database_id 1,                                                                                                                                                                                                   
 :started_at #t "2023-02-10T15:09:26.153558Z[GMT]",                                                      
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: Syntax error in SQL statement \"                                                                                                                     \nSELECT * FROM\n(SELECT TOTAL - TA
X AS NETREVENUE, *\nFROM ORDERS O;[*]) \"; expected \"(, USE, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )\"; SQL 
statement:\n-- Metabase:: userID: 1 queryType: native queryHash: e4c548f308a6f1b98a396a3d3e36b8216ef8ea506d4d5048eeca704e11bfdf3d\nSELECT * FROM\n(select total - tax as NetRevenue, *\nfrom orders o;) [42001-197]
",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__56094.invoke(execute.clj:501)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:493)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"
    "driver.sql_jdbc$fn__88601.invokeStatic(sql_jdbc.clj:58)"
    "driver.sql_jdbc$fn__88601.invoke(sql_jdbc.clj:56)"
    "driver.h2$fn__85791.invokeStatic(h2.clj:157)"
    "driver.h2$fn__85791.invoke(h2.clj:153)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
    "query_processor.context.default$default_runf.invoke(default.clj:65)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___53600.invoke(cache.clj:220)"
    "query_processor.middleware.permissions$check_query_permissions$fn__49259.invoke(permissions.clj:109)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__52545.invoke(mbql_to_native.clj:23)"
    "query_processor$fn__55076$combined_post_process__55081$combined_post_process_STAR___55082.invoke(query_processor.clj:212)"
    "query_processor$fn__55076$combined_pre_process__55077$combined_pre_process_STAR___55078.invoke(query_processor.clj:209)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53521$fn__53526.invoke(resolve_database_and_driver.clj:35)"
    "driver$do_with_driver.invokeStatic(driver.clj:76)"
    "driver$do_with_driver.invoke(driver.clj:72)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53521.invoke(resolve_database_and_driver.clj:34)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49525.invoke(fetch_source_query.clj:314)"
    "query_processor.middleware.store$initialize_store$fn__49715$fn__49716.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:45)"
    "query_processor.store$do_with_store.invoke(store.clj:39)"
    "query_processor.middleware.store$initialize_store$fn__49715.invoke(store.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__53793.invoke(normalize_query.clj:22)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__50803.invoke(constraints.clj:53)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__53732.invoke(process_userland_query.clj:145)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__54104.invoke(catch_exceptions.clj:167)"
    "query_processor.reducible$async_qp$qp_STAR___45514$thunk__45516.invoke(reducible.clj:100)"
    "query_processor.reducible$async_qp$qp_STAR___45514.invoke(reducible.clj:106)"
    "query_processor.reducible$async_qp$qp_STAR___45514.invoke(reducible.clj:91)"                                                                                                                                      "query_processor.reducible$sync_qp$qp_STAR___45525.doInvoke(reducible.clj:126)"                                                                                                                                    "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)"                                                                                                                                 
    "query_processor$process_userland_query.doInvoke(query_processor.clj:327)"                                                                                                                                     
    "query_processor$fn__55123$process_query_and_save_execution_BANG___55132$fn__55135.invoke(query_processor.clj:342)"                                                                                            
    "query_processor$fn__55123$process_query_and_save_execution_BANG___55132.invoke(query_processor.clj:335)"                                                                                                      
    "query_processor$fn__55167$process_query_and_save_with_max_results_constraints_BANG___55176$fn__55179.invoke(query_processor.clj:354)"                                                                         
    "query_processor$fn__55167$process_query_and_save_with_max_results_constraints_BANG___55176.invoke(query_processor.clj:347)"                                                                                       "api.dataset$run_query_async$fn__70529.invoke(dataset.clj:69)"                                                                                                                                                 
    "query_processor.streaming$streaming_response_STAR_$fn__40610$fn__40611.invoke(streaming.clj:162)"   
    "query_processor.streaming$streaming_response_STAR_$fn__40610.invoke(streaming.clj:161)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
    "async.streaming_response$do_f_async$task__20021.invoke(streaming_response.clj:84)"],
   :error_type :invalid-query,                                                                                                                                                                                     
   :ex-data                                                                                                                                                                                                        
   {:sql                                                                                                                                                                                                           
    "-- Metabase:: userID: 1 queryType: native queryHash: e4c548f308a6f1b98a396a3d3e36b8216ef8ea506d4d5048eeca704e11bfdf3d\nSELECT * FROM\n(select total - tax as NetRevenue, *\nfrom orders o;)",
    :params [],
    :type :invalid-query}}],                                                                             
 :state "42001",                                                                                         
 :error_type :invalid-query,                                                                             
 :json_query                                                                                             
 {:type "native",                                                                                        
  :native                                                                                                
  {:query "SELECT * FROM\n{{#2}}",                                                                       
   :template-tags                                 
   {:#2 {:id "75ab26cb-68ce-f2cf-1662-4fdaf1c5520d", :name "#2", :display-name "#2", :type "card", :card-id 2}}},
  :database 1,                                                                                           
  :parameters [],                                                                                        
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :status :failed,                                                                                        
 :class org.h2.jdbc.JdbcSQLException,                                                                    
 :stacktrace                                                                                             
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"  
  "org.h2.message.DbException.getSyntaxError(DbException.java:217)"
  "org.h2.command.Parser.getSyntaxError(Parser.java:555)"                                                                                                                                                          
  "org.h2.command.Parser.read(Parser.java:3518)"                                                                                                                                                                   
  "org.h2.command.Parser.readTableFilter(Parser.java:1357)"                                            
  "org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2138)"                                                                                                                                              
  "org.h2.command.Parser.parseSelectSimple(Parser.java:2287)"                                                                                                                                                      
  "org.h2.command.Parser.parseSelectSub(Parser.java:2133)"                                                                                                                                                         
  "org.h2.command.Parser.parseSelectUnion(Parser.java:1946)"
  "org.h2.command.Parser.parseSelect(Parser.java:1919)"
  "org.h2.command.Parser.parsePrepared(Parser.java:463)"                                                                                                                                                           
  "org.h2.command.Parser.parse(Parser.java:335)"                                                                                                                                                                   
  "org.h2.command.Parser.parse(Parser.java:311)"                                                         
  "org.h2.command.Parser.prepareCommand(Parser.java:278)"           
  "org.h2.engine.Session.prepareLocal(Session.java:611)"      
  "org.h2.engine.Session.prepareCommand(Session.java:549)"                            
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"                            
  "org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)"                                                                                                                                              
  "org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)"                                                                                                                                                      
  "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"                                                                                                                                  
  "--> driver.sql_jdbc.execute$fn__56014.invokeStatic(execute.clj:366)"                        
  "driver.sql_jdbc.execute$fn__56014.invoke(execute.clj:364)"                     
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:374)"
  "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:371)"                                                                                                                    "driver.sql_jdbc.execute$execute_reducible_query$fn__56094.invoke(execute.clj:499)"                                                                                                                              
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:498)"                                                                                                                                  
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"                                                                                                                                        
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:493)"                                                                                                                                  
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:485)"                                                                                                                                        
  "driver.sql_jdbc$fn__88601.invokeStatic(sql_jdbc.clj:58)"                                                                                                                                                          "driver.sql_jdbc$fn__88601.invoke(sql_jdbc.clj:56)"                                                                                                                                                              
  "driver.h2$fn__85791.invokeStatic(h2.clj:157)"                                                         
  "driver.h2$fn__85791.invoke(h2.clj:153)"                                                               
  "query_processor.context$executef.invokeStatic(context.clj:59)"                
  "query_processor.context$executef.invoke(context.clj:48)"                
  "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"            
  "query_processor.context.default$default_runf.invoke(default.clj:65)"                                                                                                                                            
  "query_processor.context$runf.invokeStatic(context.clj:45)"                                                                                                                                                      
  "query_processor.context$runf.invoke(context.clj:39)"                                                                                                                                                            
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"                                                                                                                                           
  "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___53600.invoke(cache.clj:220)"
  "query_processor.middleware.permissions$check_query_permissions$fn__49259.invoke(permissions.clj:109)" 
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__52545.invoke(mbql_to_native.clj:23)"    
  "query_processor$fn__55076$combined_post_process__55081$combined_post_process_STAR___55082.invoke(query_processor.clj:212)"
  "query_processor$fn__55076$combined_pre_process__55077$combined_pre_process_STAR___55078.invoke(query_processor.clj:209)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53521$fn__53526.invoke(resolve_database_and_driver.clj:35)"
  "driver$do_with_driver.invokeStatic(driver.clj:76)"                                                    
  "driver$do_with_driver.invoke(driver.clj:72)"   
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__53521.invoke(resolve_database_and_driver.clj:34)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49525.invoke(fetch_source_query.clj:314)"
  "query_processor.middleware.store$initialize_store$fn__49715$fn__49716.invoke(store.clj:11)"           
  "query_processor.store$do_with_store.invokeStatic(store.clj:45)"                
  "query_processor.store$do_with_store.invoke(store.clj:39)"                                             
  "query_processor.middleware.store$initialize_store$fn__49715.invoke(store.clj:10)"                     
  "query_processor.middleware.normalize_query$normalize$fn__53793.invoke(normalize_query.clj:22)"        
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__50803.invoke(constraints.clj:53)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__53732.invoke(process_userland_query.clj:145)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__54104.invoke(catch_exceptions.clj:167)"                                                                                                        
  "query_processor.reducible$async_qp$qp_STAR___45514$thunk__45516.invoke(reducible.clj:100)"                                                                                                                      
  "query_processor.reducible$async_qp$qp_STAR___45514.invoke(reducible.clj:106)"                       
  "query_processor.reducible$async_qp$qp_STAR___45514.invoke(reducible.clj:91)"                                                                                                                                    
  "query_processor.reducible$sync_qp$qp_STAR___45525.doInvoke(reducible.clj:126)"                                                                                                                                  
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)"                                                                                                                                   
  "query_processor$process_userland_query.doInvoke(query_processor.clj:327)"
  "query_processor$fn__55123$process_query_and_save_execution_BANG___55132$fn__55135.invoke(query_processor.clj:342)"
  "query_processor$fn__55123$process_query_and_save_execution_BANG___55132.invoke(query_processor.clj:335)"                                                                                                        
  "query_processor$fn__55167$process_query_and_save_with_max_results_constraints_BANG___55176$fn__55179.invoke(query_processor.clj:354)"                                                                           
  "query_processor$fn__55167$process_query_and_save_with_max_results_constraints_BANG___55176.invoke(query_processor.clj:347)"
  "api.dataset$run_query_async$fn__70529.invoke(dataset.clj:69)"    
  "query_processor.streaming$streaming_response_STAR_$fn__40610$fn__40611.invoke(streaming.clj:162)"
  "query_processor.streaming$streaming_response_STAR_$fn__40610.invoke(streaming.clj:161)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"                    
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"                                                                                                                                          
  "async.streaming_response$do_f_async$task__20021.invoke(streaming_response.clj:84)"],                                                                                                                            
 :card_id nil,                                                                                                                                                                                                     
 :context :ad-hoc,                                                                                       
 :error                                                                                                  
 "Syntax error in SQL statement \"                                                                                                                     \nSELECT * FROM\n(SELECT TOTAL - TAX AS NETREVENUE, *\nFROM 
ORDERS O;[*]) \"; expected \"(, USE, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, WHERE, GROUP, HAVING, UNION, MINUS, EXCEPT, INTERSECT, ORDER, OFFSET, FETCH, LIMIT, FOR, )\"; SQL statement:\n-- Metabase::
 userID: 1 queryType: native queryHash: e4c548f308a6f1b98a396a3d3e36b8216ef8ea506d4d5048eeca704e11bfdf3d\nSELECT * FROM\n(select total - tax as NetRevenue, *\nfrom orders o;) [42001-197]",
 :row_count 0,                                                                                           
 :running_time 0,                                                                                                                                                                                                  
 :data {:rows [], :cols []}}                                                                                                                                                                                       
                                                                                                                                                                                                                   
```
</details>


**To Reproduce**
1. Create an SQL question and have it end with a semicolon, e.g. `select total - tax as NetRevenue, * from orders o;` 
3. Turn the question into a model.
4. Create a new SQL query based on the model, e.g. `select * from {{#1}}` 
5. See error

**Expected behavior**
Since most of the examples I could find in the documentation finish SQL statements with a semicolon I would assume that this is supported. Obviously, you could just omit the semicolon in order to make this work. However, it took me a minute to realise that the optional semicolon was actually causing the issue.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

<details>
<summary>Troubleshooting information</summary>

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.167 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.15.0-60-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-01-27",
      "tag": "v0.45.2.1",
      "branch": "release-x.45.2.x",
      "hash": "1a59de7"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
</details>

Browser: Vivaldi
OS: Ubuntu 22.04.01 LTS
DB: Sample Database (H2)


**Severity**
This is just annoying, at least in the beginning when it's unexpected. Once you're used to it, I guess it's not a big deal, except maybe when migrating existing queries.

### PR DESCRIPTION
**Pull request by snoe**
Fixes #28218

While source-query substitution handled semicolons in native questions within outer mbql queries, we used a different code path when splicing into native queries. This brings the two paths inline.

### CODE REVIEW

File: test/metabase/driver/sql/parameters/substitute_test.clj [hunk 1]
```diff
@@ -278,8 +278,11 @@
   (testing "Referenced card query substitution"
     (let [query ["SELECT * FROM " (param "#123")]]
       (is (= ["SELECT * FROM (SELECT 1 `x`)" []]
-             (substitute query {"#123" (params/map->ReferencedCardQuery {:card-id 123, :query "SELECT 1 `x`"})}))))))
-
+             (substitute query {"#123" (params/map->ReferencedCardQuery {:card-id 123, :query "SELECT 1 `x`"})})))))
+  (testing "Referenced card query substitution removes trailing semicolons and whitespace"
```
Comment (metamben) [inline test/metabase/driver/sql/parameters/substitute_test.clj:282]: Reference #28218.

**Review by metamben — APPROVED** [review]
👍
