### PR TITLE
Fix exports not being in report timezone

### LINKED ISSUE #13677: Exports always uses UTC as timezone instead of the selected Report Timezone
**Describe the bug**
My team is using metabase version 0.37.2 and got an issue when downloading query result with date_trunc function inside it.
We only met this issue when using PostgreSQL, I tried on Bigquerry but its still alright.

**To Reproduce**
- First, we write query like this:
`select current_date, date_trunc('day',current_date) as day, date_trunc('week',current_date) as week, date_trunc('month',current_date) as month, date_trunc('quarter',current_date) as quarter
`
- The result on metabase seems fine

- Then we tried to export this result to excel or csv, it got an issue
image

_Plus, Our timezone is Asia, Bangkok, in case you need to know._

**Expected behavior**
The result's timestamp exported to csv/xlsx should be 12:00:00 instead of 17:00:00.

**Screenshots**
image

**Information about your Metabase Installation:**

- Databases: PostgreSQL
- Metabase version: 0.37.2

**Severity**
Its blocking our automation for reporting so please fix this issue as soon as possible

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #14393: Timestamp is always present in dates when exporting to Excel in the embedded application.
**Describe the bug**
Dates are displayed without timestamp in visualization for native queries, but when exported they include timestamp after I embed Metabase to our application.

**To Reproduce**
1. Create native query with a date and use convert function to have only dd-mm-yyyy
2. Save question (it worked fine if you download at this point) - saw that u have resolved the known issue #12964
3. Add Question in Dashboard
4. Embed the Dashboard to your application website
5. Download the result as Excel from website
6. Open Excel  and see that timestamp is still present

**Expected behavior**
I expect the Excel export to look just like what I am seeing in the table visualization, without the timestamp.

**Screenshots**
image

**Information about your Metabase Installation:**
```json
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.15.0-1103-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-05",
      "tag": "v0.37.5",
      "branch": "release-x.37.x",
      "hash": "be537ee"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

**Severity**
Our customers need this data for their analysis. So its really important to fix this.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by camsaul**
Bumped the version of Apache Poi so we can use Java 8 `java.time` classes directly instead of screwing around with `java.util.Date`s which is error-prone. The old code was actually buggy and not applying report timezone correctly, but the old tests didn't actually hit the API and thus didn't catch it. I fixed report timezone for both XLSX and CSV downloads.

I also fixed a bug where **time** columns in Excel spreadsheets were not exported correctly -- I can't find an issue related to this, but it's working now and I added tests for it.

Fixes #13677

~Might also fix #14393, #5859~

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
Nice catch with the time column, and much better formatting in Excel for all types :+1: 

Tested `17cf5f8`
It fixes #13677, but Public/Signed #14393 still includes timestamp+tz for dates and timezone for datetime.
#5859 isn't specific to exports, but this PR fixes the export parts.

I'm also noticing that the decimal precision on timetz columns is different on UTC vs non-UTC.

This is what I'm testing with now:
```
select
      '2021-03-31T01:23:45.678901+02:00'::timestamp     as "timestamp"
    , '2021-03-31T01:23:45.678901+02:00'::timestamptz   as "timestampTz"
    , '2021-03-31T01:23:45.678901'::timestamp           as "timestamp-noTz"
    , '2021-03-31T01:23:45.678901'::timestamptz         as "timestampTz-noTz"
    , '01:23:45.678901+02:00'::time                     as "time"
    , '01:23:45.678901+02:00'::timetz                   as "timetz"
    , '01:23:45.678901'::time                           as "time-noTz"
    , '01:23:45.678901'::timetz                         as "timetz-noTz"
    , '2021-03-31'::date                                as "date"
    , date_trunc('day', '2021-03-31'::date)::date       as "truncDayAsDate"
    , date_trunc('day', '2021-03-31'::date)             as "truncDay"
    , date_trunc('week', '2021-03-31'::date)            as "truncWeek"
    , date_trunc('month', '2021-03-31'::date)           as "truncMonth"
    , date_trunc('quarter', '2021-03-31'::date)         as "truncQuarter"
    , date_trunc('year', '2021-03-31'::date)            as "truncYear"
    , '123:44:55'::interval                             as "interval"
    , '2021-03-31T00:00:00.0000+02:00'::timestamp(0)    as "timestampAtMidnight"
    , '2021-03-31T00:00:00.0000+02:00'::timestamp(0)    as "timestampTzAtMidnight"
    , current_setting('TIMEZONE')                       as "tz_db"
```

Tested:
A. Java=Europe/Copenhagen and Reporting=Default and Postgres=UTC
B. Java=UTC and Reporting=Default and Postgres=UTC

**Comment by dpsutton** [comment]
@flamber that's an awesome test case

File: enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj [hunk 1]
```diff
@@ -137,7 +137,8 @@
     attrs))
 
 (defn- base64-decode [s]
-  (codecs/bytes->str (codec/base64-decode s)))
+  (when (u/base64-string? s)
+    (codecs/bytes->str (codec/base64-decode s))))
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj:141]: this looks like a duplicate of the saml fix

File: src/metabase/api/dataset.clj [hunk 2]
```diff
@@ -59,7 +59,10 @@
   "Execute a query and retrieve the results in the usual format."
   [:as {{:keys [database], query-type :type, :as query} :body}]
   {database (s/maybe s/Int)}
-  (run-query-async (update query :middleware assoc :js-int-to-string? true)))
+  (run-query-async (update-in query [:middleware :js-int-to-string?] (fn [existing-value]
```
Comment (dpsutton) [inline src/metabase/api/dataset.clj:62]: `(update-in query [...] (fnil identity true))` might be clearer and more concise

File: src/metabase/query_processor/streaming/common.clj [hunk 3]
```diff
@@ -16,24 +29,28 @@
   Object
   (format-value [this] this)
 
-  java.time.temporal.Temporal
-  (format-value [this]
-    (u.date/format this))
+  LocalDate
```
Comment (dpsutton) [inline src/metabase/query_processor/streaming/common.clj:32]: i kinda wish this protocol was renamed from the very generic `format-value` to recognize its all about dates. And then the results timezone id can be got once and passed down through the signature each call rather than cached and held. This also makes the tests much nicer. I always get annoyed when i do something and get told i don't have an initialized qp.store, and therefore need to put a very data forward test inside of a with-database and with-everything-store macros.

That said, we're 20 minutes before a release so not something that needs to be done now but feels like the right call.

File: enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj (hunk 1 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj:141]: Yeah, bumping the version of Apache commons codecs actually caused this to stop throwing an Exception when you try to base64-decode something that's not valid base 64, which caused a test failure -- I added this check here to fix that. I made the same change in the SAML branch after the fact since I was working on both at the same time and I didn't want merge conflicts. It's not *actually* required there

**Review by dpsutton — APPROVED** [review]

File: src/metabase/query_processor/streaming/common.clj (hunk 3 above)
Comment (camsaul) [reply src/metabase/query_processor/streaming/common.clj:32]: You actually still need the QP store anyway in this case, since the `report-timezone` that gets used is dependent on the database from the QP store.  

We only override `format-value` for temporal types, but we still call it for *every* value when writing CSV/JSON -- the default impl for `Object` is just identity. So `format-temporal-value` or whatever I think would be a bit of a misnomer because we'd still be making calls like `(format-temporal-value 100.0)`

**Comment by camsaul** [comment]
@flamber when you say precision is different, is it blocking merge? Excel stores temporal instants as floating point numbers internally so some conversions might result in slightly different rounding, so if things differ by a few microseconds or whatever I don't think we should lose sleep over it.
