### PR TITLE
Trim whitespace on non-password database form inputs

### LINKED ISSUE #12972: UI should trim whitespace from "Host" field when adding a new database
**Describe the bug**

Whitespace is not trimmed from UI filed `Host` when adding a new database causing a connection error if there is a trailing space/tab.

**Logs**

Not required.

**To Reproduce**

Add a new database in the UI with a trailing space, like `my-app.cluster-ro-xxxxxxxxxx.eu-west-1.rds.amazonaws.com	`

**Expected behavior**

UI should trim whitespace.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.177-139.253.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.16"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-02",
      "tag": "v0.35.1",
      "branch": "release-0.35.x",
      "hash": "e67f169"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**

Minor

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #12972

**Description**
We don't trim whitespace on string input fields, so adding/editing a database fails when there's whitespace in the hostname.

There are two commits in this PR -- the first trims only the Host field, the second trims **all non-password string inputs** in database forms. I don't want to be overly presumptive about what are/aren't acceptable values for these input fields but in general it seems like pre/postfix whitespace is most likely not going to be intended by the user or an accepted value by whatever it is these values are used for. Perhaps I'm wrong -- let me know!

You can see the form fields this change affects by running this in the browser console on a metabase instance:
`Object.entries(window.MetabaseBootstrap.engines).map(([engineName, engine]) => [engineName, engine['details-fields'].map(({name, 'display-name': displayName, type}) => ({name, displayName, type})).filter(field => !['password', 'integer', 'boolean', 'select'].includes(field.type))])`

**Verification**
Add or edit a database with a host input of something like `"  localhost  "` and it should save. The whitespace is not removed from the input when the user blurs the input or saves the form, but the whitespace will be gone after a page refresh.

### CODE REVIEW

File: frontend/src/metabase/entities/databases/forms.js [hunk 1]
```diff
@@ -180,76 +180,87 @@ function getAuthCodeEnableAPILink(engine, details) {
   }
 }
 
-function getFieldsForEngine(engine, details, id) {
-  let info = (MetabaseSettings.get("engines") || {})[engine];
-  if (engine === "bigquery") {
+function getEngineInfo(engine, details, id) {
```
Comment (ariya) [inline frontend/src/metabase/entities/databases/forms.js:183]: Is this refactoring/clean-up related to the whitespace trim? If not, then it's better to keep it as a separate PR to avoid any potential confusion (e.g. from any future `git log` or `git blame`).

Comment (daltojohnso) [reply frontend/src/metabase/entities/databases/forms.js]: Moved my refactoring to a new branch/PR -- https://github.com/metabase/metabase/pull/14610 -- and rebased this branch to target `dj-12972-refactor`. Once that PR has merged, I will retarget this PR to master.

File: frontend/test/metabase-db/mongo/add.cy.spec.js [hunk 2]
```diff
@@ -23,7 +23,7 @@ describe("mongodb > admin > add", () => {
     cy.contains("MongoDB").click({ force: true });
     cy.contains("Additional Mongo connection");
 
-    typeAndBlurUsingLabel("Name", "QA Mongo4");
+    typeAndBlurUsingLabel("Name", "QA Mongo4 ");
```
Comment (paulrosenzweig) [inline frontend/test/metabase-db/mongo/add.cy.spec.js:26]: Rather than adding whitespace to existing tests, it might be worth adding one test that's explicitly about this behavior. Two reasons:
- If I break this trimming behavior, a few tests will start failing. It would takes some debugging to see what the issue is causing those failures.
- As the tests evolve, we might drop the whitespace you added since it's not the main point of these tests. That would remove our coverage of this behavior.

I don't think we necessarily need to connect to a real db to test this. Asserting that the API call contains trimmed values seems like enough to me.

**Review by paulrosenzweig — APPROVED** [review]
Code change looks good!

File: frontend/test/metabase-db/mongo/add.cy.spec.js (hunk 2 above)
Comment (daltojohnso) [reply frontend/test/metabase-db/mongo/add.cy.spec.js:26]: Good point -- will add a test specifically for this.

File: frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js [hunk 3]
```diff
@@ -52,6 +53,28 @@ describe("scenarios > admin > databases > add", () => {
...
+    cy.visit("/admin/databases/create");
+
+    typeField("Name", "Test db name");
+    typeField("Host", "localhost  \n  ");
+    typeField("Database name", " test_postgres_db");
+    typeField("Username", "   uberadmin   ");
+
+    cy.findByText("Save").click();
+
+    cy.wait("@createDatabase");
```
Comment (paulrosenzweig) [inline frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js:73]: I think it would make sense to assert on the request body here to ensure the whitespace was removed. There's an example of asserting on a request body a bit further down in this file:

```js
cy.wait("@createDatabase").then(({ request }) => {
    expect(request.body.engine).to.equal("postgres");
    expect(request.body.name).to.equal("Test db name");
    expect(request.body.details.user).to.equal("uberadmin");	
});	
```

Comment (daltojohnso) [reply frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js]: Good idea; updated the test

**Review by paulrosenzweig — APPROVED** [review]
Looks good!

**Comment by daltojohnso** [comment]
Per the "State of Cypress..." doc it's fine to merge when default/mysql/postgres cypress tests show "pending" as they are not running currently. Have run all cypress tests locally and they pass.
