### PR TITLE
Fix redshift sync failing with duplicate key error

### LINKED ISSUE #67275: Sync Fails with Duplicate Key Constraint
### Describe the bug

A table synced into Metabase with no fields. When you try to force a resync you're met with the error:

```
ERROR: duplicate key value violates unique constraint "idx_unique_field"
  Detail: Key (name, table_id, unique_field_helper)=(desired_daily_rate (cf), 35934, 0) already exists.
```

### To Reproduce

No repro yet. Unsure if it's relevant but looks to be a Redshift DB. Context:
https://metaboat.slack.com/archives/C05MPF0TM3L/p1766152259975039

### Expected behavior

Sync should work

### Logs

_No response_

### Information about your Metabase installation

```JSON
v57.7.4
```

### Severity

blocking use of table 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/67275

### Description

Redshift views can be created with duplicated column names if `with no schema binding` is used. This results in an ambiguous error when we try to select this field. Based on [this discussion](https://metaboat.slack.com/archives/C0645JP1W81/p1769446081955849), we'll skip syncing these duplicate fields entirely. 

### How to verify

1. Create a view in redshift with two columns having the same name using `with no schema binding`
2. Sync this database in metabase
3. Prior to this change, you would get an error that the table had no fields (we failed sync with a duplicate key error)
4. With this change you should be able to query this table without the duplicate column. 

### Demo

https://github.com/user-attachments/assets/3b8a5bae-9492-42c7-8800-7f632aaa462c

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/redshift/src/metabase/driver/redshift.clj [hunk 1]
```diff
@@ -59,10 +60,30 @@
...
 ;;; +----------------------------------------------------------------------------------------------------------------+
 
-;; Skip the postgres implementation of describe fields as it has to handle custom enums which redshift doesn't support.
+(defn- remove-duplicate-fields
+  "Redshift views can have duplicate column names, but when these columns appear in a query
+   they produce an ambiguous column error. To avoid this remove all duplicate columns"
+  [fields]
+  (let [field-key      (fn [f] (perf/select-keys f [:table-schema :table-name :name]))
+        key-counts     (frequencies (map field-key fields))
+        duplicate-keys (into #{} (comp (filter #(> (val %) 1)) (map key)) key-counts)]
```
Comment (metamben) [inline modules/drivers/redshift/src/metabase/driver/redshift.clj]: I think a single `keep` destructuring the map entries would be easier to read.

File: modules/drivers/redshift/src/metabase/driver/redshift.clj [hunk 2]
```diff
@@ -59,10 +60,30 @@
...
+      (log/warnf "Duplicate column '%s' in %s.%s - skipping all occurrences"
+                 name table-schema table-name))
+    (remove #(contains? duplicate-keys (field-key %)) fields)))
+
 (defmethod sql-jdbc.sync/describe-fields-pre-process-xf :redshift
-  [driver database & args]
-  (apply (get-method sql-jdbc.sync/describe-fields-pre-process-xf :sql-jdbc) driver database args))
+  [_driver _db & _args]
+  (fn [rf]
+    (let [fields (volatile! [])]
```
Comment (metamben) [inline modules/drivers/redshift/src/metabase/driver/redshift.clj]: possibly even
```suggestion
    (let [fields (volatile! (transient []))]
```
and `conj!` and `persistent!` later on.

**Review by metamben — APPROVED** [review]
