### PR TITLE
Tests for #15131

### LINKED ISSUE #15131: Should be able to run a card with another card as its source query with just perms for the former
Suppose we have two Cards, Card 1 and Card 2. Card 2 has a query like `{:query {:source-table "card__1"}}` (i.e., Card 2 uses Card 1 as a source query). Now suppose the current User has permissions to see Card 2, but no perms for Card 1. They should still be able to run Card 2 -- we don't need to check perms for Card 1 as well.

However, we should require perms for Card 1 to save a Card with a query like `{:query {:source-table "card__1"}}`, so people can't give themselves access to arbitrary Cards.

I think this is a regression in `master` (39-SNAPSHOT)

### PR DESCRIPTION
**Pull request by camsaul**
I guess maybe we already accidentally fixed #15131, here are some tests that confirm things are now working as expected.

Resolves #15131

### CODE REVIEW

File: src/metabase/query_processor/util.clj [hunk 1]
```diff
@@ -30,7 +30,7 @@
    can access the default value."
   [{{:keys [executed-by query-hash], :as _info} :info, query-type :type}]
   (str "Metabase" (when executed-by
-                    (assert (instance? (Class/forName "[B") query-hash))
+                    (assert (bytes? query-hash) "If info includes executed-by it should also include query-hash")
```
Comment (camsaul) [inline src/metabase/query_processor/util.clj:33]: Unrelated but I improved the error message here if you're missing `query-hash` which I guess is required if you also have `executed-by`.

File: test/metabase/query_processor/card_test.clj [hunk 2]
```diff
@@ -165,3 +169,40 @@
                                                                             :some_other_key  [:ref [:field Integer/MAX_VALUE {:base-type :type/DateTime, :temporal-unit :month}]]}}}}]
       (is (= [[100]]
              (mt/rows (run-query-for-card card-id)))))))
+
+(deftest nested-query-permissions-test
```
Comment (camsaul) [inline test/metabase/query_processor/card_test.clj:173]: This test is mostly the same as the other one but uses `qp.card/process-query-for-card` instead of hitting the REST API endpoint, I was on the fence about which one was better so I just ended up putting them both in here. The REST API test is good so we can be sure that it really does work end-to-end and doesn't fail some other perms check outside of QP land, while the QP-specific test is good so we can be confident the QP is working in isolation from the REST API (e.g. if we only run QP tests with the `:test/qp` alias)

File: test/metabase/api/card_test.clj [hunk 3]
```diff
@@ -3596,3 +3597,35 @@
...
+                    (mt/user-http-request :rasta :post (format "card/%d/query" (u/the-id card))))]
+            (testing "Should not be able to run the parent Card"
+              (mt/with-test-user :rasta
+                (is (not (mi/can-read? disallowed-collection)))
+                (is (not (mi/can-read? parent-card))))
+              (is (= "You don't have permissions to do that."
+                     (process-query-for-card parent-card))))
+            (testing "Should be able to run the child Card (#15131)"
+              (mt/with-test-user :rasta
+                (is (not (mi/can-read? parent-card)))
```
Comment (lbrdnk) [inline test/metabase/api/card_test.clj:3627]: I believe this `is` is covered by the previous testing block.

File: test/metabase/query_processor/card_test.clj [hunk 4]
```diff
@@ -165,3 +169,40 @@
...
+                                (qp/process-query (assoc query :info info))))))]
+              (testing "Should not be able to run the parent Card"
+                (is (not (mi/can-read? disallowed-collection)))
+                (is (not (mi/can-read? parent-card)))
+                (is (thrown-with-msg?
+                     clojure.lang.ExceptionInfo
+                     #"\QYou don't have permissions to do that.\E"
+                     (process-query-for-card parent-card))))
+              (testing "Should be able to run the child Card (#15131)"
+                (is (not (mi/can-read? parent-card)))
```
Comment (lbrdnk) [inline test/metabase/query_processor/card_test.clj:204]: Same as with my previous comment.

**Review by lbrdnk — APPROVED** [review]
LGTM with nit on what I believe is redundant `is` assertion.
