### PR TITLE
dashboard filter: do not display "No matching..." if not filtered

### LINKED ISSUE #17211: No matching dashboard filter found when it clearly has been found
**Describe the bug**
When applying a dashboard Location filter (using dropdown) and searching for a city, the UI gives a false warning that the "No matching **City** found".

**Logs**
N/A

**To Reproduce**
1. Save "Orders" as a question and add it to a dashboard
2. Add Location filter, choose Dropdown option
3. Connect that filter to the "City" field (implicit join)
4. Save the dashboard
5. Click on the filter widget and enter "abb", the "Abbeville" city will show up
6. Click on it and see that the filter has been applied, but you can see the message "No matching City found"

**Expected behavior**
Show this message only when there are actually no results.

**Screenshots**

**Information about your Metabase Installation:**
local dev, `master`, d538024c74fb2ddabb47c307edbe2a0918521d0e

**Severity**
Although it's confusing, it's P3 because everything works as expected.

**Additional context**
This behavior may not be connected to the Location filter only. I just gave it as an example.

Related to #7231.

### PR DESCRIPTION
**Pull request by pawit-metabase**
Fixes #17211

### CODE REVIEW

File: frontend/src/metabase/components/TokenField.jsx [hunk 1]
```diff
@@ -33,6 +33,7 @@ export type LayoutRendererProps = {
   optionsList: ?React.Element,
   isFocused: boolean,
   isAllSelected: boolean,
+  isFiltered: boolean,
```
Comment (pawit-metabase) [inline frontend/src/metabase/components/TokenField.jsx:36]: Note: this is already being passed, it just wasn't in the type definition.

https://github.com/metabase/metabase/blob/776dba2a49ab6e34d6ce39c0808a784baf1ae249/frontend/src/metabase/components/TokenField.jsx#L638-L645

**Review by daltojohnso — APPROVED** [review]
nice!
