### PR TITLE
Retry have-select-privilege? on error

### LINKED ISSUE #60240: Metabase can't sync more than ~2500 tables in snowflake
### Describe the bug

Found this while making massive schemas in snowflake and testing with a local instance. Honestly I don't know the reason

### To Reproduce

1) set up Metabase 55
2) add the success snowflake instance
3) specify that you want to sync SCHEMA_1, SCHEMA_2, SCHEMA_3, SCHEMA_4

(each schema has 1000 tables)

You'll get ~2500 tables, not more than than (schema_3 will have missing tables and schema_4 will not sync at all)

### Expected behavior

All tables should be synced

### Logs

NA

### Information about your Metabase installation

```JSON
v55.x, haven't tested before this
```

### Severity

P1?

### Additional context

NA

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/60240

### Description

Retries `have-select-privilege?` if the initial select probe fails. While investigating https://github.com/metabase/metabase/issues/60240 we observed that after ~750 tables the probe would fail with a `Statement is closed.` exception. This was halting the sync for the remaining tables. This issue is addressed in https://github.com/metabase/metabase/pull/60857 such that the sync continues on the rest of the tables after this exception. But this still leaves the issue that the table that should have been synced when the `Statement is closed.` exception occurred was missed. This PR addresses that issue but attempting a single retry when a select probe query fails. 

Concerns below have been resolved by adding the `(not is-open)` check. 

Concerns:
These changes are meant to sync a table that is incorrectly marked as not having select privilege due to an unexpected connection closure, which happens infrequently (every 7-800 tables during snowflake testing). But in the case where we are getting actual exceptions due to not having select privilege, then we are issuing (potentially many) unnecessary queries. I'm not sure how big of a concern duplicating queries when we actually don't have permission is. Two possible remedies for this: 
1. We make the retry criteria more strict (i.e. only on certain types of exceptions). The snowflake exception was pretty broad (something like `SnowflakeSQLException`), so not sure how well this would work. Assuming we don't want to start looking at the exception message for certain strings.
2. Since we've only observed this issue with the snowflake driver, we make a snowflake specific implementation of `have-select-privilege?` with the retry and leave the SQL JDBC implementation as is.
3. We close this PR and just live with some tables being skipped during sync when we come across these connection closure exceptions. 

### How to verify

1. Follow the steps to connect to the success team's snowflake DB outlined in the linked issue. 
2. You should see that all the tables are synced despite there being `Statement is closed.` exceptions in the logs. 

### Demo

<details>

<summary>with and without retry results</summary>

without retry
Screenshot 2025-07-21 at 8 11 07 PM
Screenshot 2025-07-21 at 8 10 53 PM

with retry
Screenshot 2025-07-21 at 8 10 58 PM
Screenshot 2025-07-21 at 8 10 32 PM
<details>

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 1]
```diff
@@ -626,7 +626,7 @@
                           ;; See [[metabase.driver.snowflake/describe-database-default-schema-test]] and
                           ;; https://metaboat.slack.com/archives/C04DN5VRQM6/p1706220295862639?thread_ts=1706156558.940489&cid=C04DN5VRQM6
                           ;; for more info.
-                          (sql-jdbc.describe-database/db-tables driver (.getMetaData conn) "%" db-name))}))))))
+                          (vec (sql-jdbc.describe-database/db-tables driver (.getMetaData conn) "%" db-name)))}))))))
```
Comment (bronsa) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:629]: I don't think we need this

File: src/metabase/driver/sql_jdbc/sync/describe_database.clj [hunk 2]
```diff
@@ -122,7 +122,9 @@
           (try (when-not (.getAutoCommit conn)
                  (.rollback conn))
                (catch Throwable _))
-          allow?)))))
+          (if (and (not allow?) (not retry?))
```
Comment (bronsa) [inline src/metabase/driver/sql_jdbc/sync/describe_database.clj]: with this logic, we'll retry twice for every table we don't have select privileges from, not just when the connection may have been accidentally dropped. 
I think this could be `(and (not allow?) (not retry?) (not is-open))` (just rename `_is-open` from above to `is-open`).

This way we'll only retry if the connection has been closed, not if the select has legit failed

File: src/metabase/driver/sql_jdbc/execute.clj [hunk 3]
```diff
@@ -362,20 +362,20 @@
    db-or-id-or-spec
    ^Connection conn                                       :- (driver-api/instance-of-class Connection)
    {:keys [^String session-timezone write?], :as options} :- ConnectionOptions]
+  (when-let [db (cond
```
Comment (bronsa) [inline src/metabase/driver/sql_jdbc/execute.clj]: I think the role changes belong to a separate PR, I'd rather keep this one only about the retry logic

**Review by bronsa — CHANGES_REQUESTED** [review]

File: src/metabase/driver/sql_jdbc/execute.clj (hunk 3 above)
Comment (rileythomp) [reply src/metabase/driver/sql_jdbc/execute.clj]: Yeah just pushed it here so you guys could see the changes. Will remove and put in a separate PR.

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj (hunk 1 above)
Comment (rileythomp) [reply modules/drivers/snowflake/src/metabase/driver/snowflake.clj:629]: I think we might, or we need another way to work around the ResultSet in `db-tables` trying to use the closed connection. The large snowflake sync fails if we don't realize the tables here. I think it's because the ResultSet in `reducible-results` is still using the closed connection. I'm not sure of a way to continue processing the result set once the connection is closed but if there is another approach let me know

**Review by bronsa — APPROVED** [review]

File: src/metabase/driver/sql_jdbc/sync/describe_database.clj [hunk 4]
```diff
@@ -122,7 +122,9 @@
           (try (when-not (.getAutoCommit conn)
                  (.rollback conn))
                (catch Throwable _))
-          allow?)))))
+          (if (and (not allow?) (not retry?) (not is-open))
```
Comment (snoe) [inline src/metabase/driver/sql_jdbc/sync/describe_database.clj:125]: You could use `u/auto-retry` here

**Review by snoe — APPROVED** [review]
