### PR TITLE
Fix EE Starter Edition Embedding Admin page visuals

### LINKED ISSUE #68224: Starter Edition: Embedding admin UI should look the same as in OSS
### Describe the bug

Starter Edition: Embedding admin UI should look the same as in OSS

Context:
https://metaboat.slack.com/archives/C063Q3F1HPF/p1768426773839819

### To Reproduce

Context: https://metaboat.slack.com/archives/C063Q3F1HPF/p1768426773839819

### Expected behavior

Admin UI should look the same in OSS and Starter Edition

### Logs

_No response_

### Information about your Metabase installation

```JSON
58 release
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
closes #68224
Fix EE Starter Edition Embedding Admin page visuals

Context: https://metaboat.slack.com/archives/C063Q3F1HPF/p1768426773839819

Bug:
- we display the wrong state of Admin UI for Embedding Page for EE Starter Edition. It should be the same as in OSS version. But currently we display it as for EE edition with `simple embedding` enabled.

We can rely just on `simple embedding` token feature.
We should adjust visuals and routes.

PS: wizard behaves correctly.

### CODE REVIEW

File: frontend/src/metabase/admin/routes.jsx [hunk 1]
```diff
@@ -64,254 +64,269 @@ import {
...
+            />
 
-          {isEEBuild() && (
-            <>
-              <Route
-                path="guest"
-                title={t`Unauthenticated embeds`}
-                component={GuestEmbedsSettings}
-              />
+            {hasSimpleEmbedding && (
```
Comment (sanex3339) [inline frontend/src/metabase/admin/routes.jsx:186]: This line is important

File: frontend/src/metabase/admin/routes.jsx [hunk 2]
```diff
@@ -64,254 +64,269 @@ import {
...
-      {/* EE has all embedding settings on the same page */}
-      {!isEEBuild() && (
-        <>
-          <Redirect from="/admin/embedding/guest" to="/admin/embedding" />
 
-          <Redirect from="/admin/embedding/security" to="/admin/embedding" />
-        </>
-      )}
+        {/* OSS/Starter has all embedding settings on the same page */}
+        {!hasSimpleEmbedding && (
```
Comment (sanex3339) [inline frontend/src/metabase/admin/routes.jsx:205]: And this line

File: e2e/test/scenarios/embedding/embedding-admin-settings-oss.cy.spec.ts [hunk 3]
```diff
@@ -1,13 +1,21 @@
 const { H } = cy;
 
+const { IS_ENTERPRISE } = Cypress.env();
+const IS_OSS = !IS_ENTERPRISE;
+
 // These tests will run on both OSS and EE instances, both without a token.
 describe(
   "scenarios > embedding > admin settings > oss",
-  { tags: "@OSS" },
+  { ...(IS_OSS && { tags: "@OSS" }) },
```
Comment (sanex3339) [inline e2e/test/scenarios/embedding/embedding-admin-settings-oss.cy.spec.ts]: It seems the comment was missleading and this suite was not run in EE Starter

Comment (npretto) [inline e2e/test/scenarios/embedding/embedding-admin-settings-oss.cy.spec.ts]: what does this do?

Comment (sanex3339) [reply e2e/test/scenarios/embedding/embedding-admin-settings-oss.cy.spec.ts]: I changed to `  { tags: ["@OSS", "@EE"] },`, let's see if it will run in both editions

File: frontend/src/metabase/admin/routes.jsx (hunk 2 above)
Comment (WiNloSt) [reply frontend/src/metabase/admin/routes.jsx:205]: should we add `{/* OSS/Starter has all embedding settings on the same page */}` to the above line too?

Comment (sanex3339) [reply frontend/src/metabase/admin/routes.jsx:205]: Do you mean in navbar?

Comment (WiNloSt) [reply frontend/src/metabase/admin/routes.jsx:205]: i mean [this change](https://github.com/metabase/metabase/pull/68226#discussion_r2693693497)

Comment (sanex3339) [reply frontend/src/metabase/admin/routes.jsx:205]: That line is opposite so i can add `EE with hasSimpleEmbedding feature has embedding settings on different pages`

Comment (sanex3339) [reply frontend/src/metabase/admin/routes.jsx:205]: Added

**Review by lorem--ipsum — APPROVED** [review]

File: frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSettings/tests/enterprise.unit.spec.tsx [hunk 4]
```diff
@@ -4,14 +4,18 @@ import { type SetupOpts, setup as baseSetup } from "./setup";
...
+      embedding_simple: opts.isEmbeddingSimpleEnabled,
+    },
     ...opts,
   });
 
 describe("EmbeddingSdkSettings (EE)", () => {
   it("should not tell users to switch binaries when they have a EE build", async () => {
     await setup({
       isEmbeddingSdkEnabled: false,
+      isEmbeddingSimpleEnabled: true,
```
Comment (WiNloSt) [inline frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSettings/tests/enterprise.unit.spec.tsx:18]: Why would there be a test for `enterprise` with any token feature at all. Based on [the doc](https://www.notion.so/metabase/Testing-paid-features-49e03e1b2a3b41ffb4ebdc7616a93d90?source=copy_link#2041f1a8f4d64c0dba1dfd8ca56866cf), I always follow that `enterprise.unit.*` contains no feature token declaration.

**Review by WiNloSt — APPROVED** [review]
Looks good with only one comment regarding enterprise (EE without features) tests.

File: frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSettings/EmbeddingSettings.tsx [hunk 5]
```diff
@@ -121,11 +125,11 @@ function EmbeddingSettingsOSS() {
 }
 
 export const EmbeddingSettings = () => {
-  const isEE = isEEBuild();
+  const hasSimpleEmbedding = useHasTokenFeature("embedding_simple");
```
Comment (WiNloSt) [inline frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSettings/EmbeddingSettings.tsx:128]: btw based on the most [recent discussion](https://metaboat.slack.com/archives/C505ZNNH4/p1768487143746239), we should be using `PLUGIN_XXX.isEnabled` instead. For this I think it makes sense to use https://github.com/metabase/metabase/blob/c73ccb8be7fe1451257052d75b694d5e65844e2c/enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/index.ts#L11

tl;dr we shouldn't be using `useHasTokenFeature`

**Review by iethree — APPROVED** [review]
