### PR TITLE
Backend validation for landing-page to disallow external URLs

### LINKED ISSUE #32585: Custom landing page with an external URL will lock everyone out of MB
### Describe the bug

If we customize homepage with an external URL, MB will fail to load and display a blank page.

The only way to reset that value is to update the setting using SQL manually.

### To Reproduce

1. Enable enterprise
2. Go to Admin => Appearance
3. Set the custom homepage setting with `https://google.com`
4. open MB in a new tab

### Expected behavior

should not allow entering external URLs

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity
locking everyone out of MB is quite serious

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qwef**
Closes https://github.com/metabase/metabase/issues/32585

### Description

Add a setter to `landing-page` to validate URLs that come in. If the `landing-page` is a URL, then check against `site-url`. Note that I do a prefix check for this, so the same port is required.  

Related (FE version): https://github.com/metabase/metabase/pull/37322

### CODE REVIEW

File: src/metabase/public_settings.clj [hunk 1]
```diff
@@ -257,12 +258,29 @@
...
   (deferred-tru "Default page to show people when they log in.")
   :visibility :public
   :type       :string
   :default    ""
-  :audit      :getter)
+  :audit      :getter
+  :setter     (fn [new-landing-page]
+                (when new-landing-page
+                  ;; If the landing page is a valid URL or mailto, sms, or file, then check with if site-url has the same origin.
+                  (when (and (or (re-matches #"^(mailto|sms|file):(.*)" new-landing-page) (u/url? new-landing-page))
```
Comment (noahmoss) [inline src/metabase/public_settings.clj:280]: is there a reason now to throw for any non-HTTP/HTTPS URLs?

**Review by noahmoss — APPROVED** [review]

File: src/metabase/public_settings.clj (hunk 1 above)
Comment (qwef) [reply src/metabase/public_settings.clj:280]: hm good point, I think `io/as-url` won't work without the protocol.
