### PR TITLE
Sync Snowflake `VARIANT` type as new `:type/SnowflakeVariant`

### LINKED ISSUE #45206: Snowflake regextract no longer working
### Describe the bug

We have just upgraded to v0.50.6 ( and v0.50.10) using the docker image, when creating a custom column using the below expression:

substring(regexextract([Tags], "\"Name\":\"((\\\"|[^\"])*)"), 9, 60)

we're now getting "Invalid expression". I can't remember the exact version we were on but I believe it was v.0.48. I've also tried the sample from the documentation regexextract([Tags], "^[^?#]+\?utm_campaign=(.*)") and that gives the same error

[This has more details](https://discourse.metabase.com/t/snowflake-regextract-no-longer-working/128266/4)

Metabase datatype "Field containing JSON"
Snowflake datatype "Variant"

### To Reproduce

1. Enter substring(regexextract([Tags], "\"Name\":\"((\\\"|[^\"])*)"), 9, 60) into a custom expression

### Expected behavior

This should work as per previous versions

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.219-208.866.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "snowflake",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-07-04",
      "tag": "v0.50.10",
      "hash": "49d9e46"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Broken most of our Dashboards

### Additional context

_No response_

### LINKED ISSUE #45672: `regexextract` is not an actual MBQL clause
There's some super weirdness going on with the `regexextract` and `regex-match-first` MBQL clauses. I don't think `regexextract` is actually a real MBQL clause at all, it's just for whatever weird reason what the frontend expression editor calls `regex-match-first`

```js
  "regex-match-first": {
    displayName: `regexextract`,
    type: "string",
    args: ["string", "string"],
    requiresFeature: "regex",
  },
```

Anyways MLv2 defines both, but if you try to create a query with `regexextract` it fails since it's not part of the legacy MBQL schema nad the QP doesn't understand it.

We should remove the helper functions and schema for `regexextract` from MLv2 to avoid confusion.

### PR DESCRIPTION
**Pull request by camsaul**
Snowflake has a `VARIANT` type that is untyped but can be any type of value.

Probably by accident in < 49 we allowed you to use custom expressions that take `type/Text` arguments like `regexextract` (called `regex-match-first` under the hood) against `VARIANT` columns. In 49+ we have better type checking and only let you use `regex-match-first` against `type/Text` columns, so these queries stopped working.

The fix here was to sync `VARIANT` as a new base type called `:type/SnowflakeVariant` that derives from `:type/Text` as well as the other major core base types like `:type/Number` and `:type/Temporal` so you should theoretically be allowed to use with anything in the custom expression editor (whether or not this makes sense is not something we can currently check unfortunately since the column is untyped). 

Fixes #45206

This fix will not take effect until the database is re-synced.

Also I noticed that we have an MLv2 function and schema for a `:regexextract` clause, even tho it doesn't actually exist, so I fixed that while I was at it. 

Fixes #45672

### CODE REVIEW

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj [hunk 1]
```diff
@@ -746,30 +746,63 @@
 (deftest ^:parallel connection-str->parameters-test
   (testing "Returns nil for invalid connection string"
     (are [conn-str] (= nil (driver.snowflake/connection-str->parameters conn-str))
-      nil "" "asdf" "snowflake:jdbc://x"))
+      nil "" "asdf" "snowflake:jdbc://x")))
+
+(deftest ^:parallel connection-str->parameters-test-2
```
Comment (camsaul) [inline modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj:751]: Broke this up into a few smaller tests.

**Review by lbrdnk — APPROVED** [review]

File: src/metabase/types.cljc [hunk 2]
```diff
@@ -253,6 +253,17 @@
...
+;;; The Snowflake `VARIANT` type is allowed to be anything, so just mark it as deriving from the core root types so
+;;; we're allowed to use any sort of filter with it (whether it makes sense or not). See
+;;; https://docs.snowflake.com/en/sql-reference/data-types-semistructured
+(doseq [t [:type/Number
+           :type/Text
+           :type/Temporal
+           :type/Boolean
+           :type/Collection
+           :type/field-values-unsupported]]
+  (derive :type/SnowflakeVariant t))
```
Comment (metamben) [inline src/metabase/types.cljc:265]: Shouldn't we have some kind of `:type/Any`? If a 3rd party driver wants to have a similar type, are they going to use `:type/SnowflakeVariant` or ask us to introduce it?

Comment (camsaul) [reply src/metabase/types.cljc:265]: Yeah I think driver-specific types and the other existing ones actually do belong in driver namespaces, but I didn't want to turn this PR into a refactor PR that started moving unrelated stuff around. I put it here to be with everything else. I'll make a note tho and open a follow-on refactor PR to put stuff in the driver namespaces. I need to make sure it doesn't break anything if you do something like fetch a `:type/SnowflakeVariant` Field before the Snowflake driver namespace gets loaded. We probably need to have the custom type stuff get done at plugin init time which means adding a way to do that from the YAML config files so it happens without loading `metabase.driver.snowflake`
