### PR TITLE
fix(sdk-package, sdk-bundle, embed-js): Don't expose `question` in SDK's `entityTypes`

### LINKED ISSUE #65797: Entitytype question isn't a supported option for the SDK
### Describe the bug

We have this in the docs:

https://www.metabase.com/docs/latest/embedding/sdk/api/EmbeddingEntityType.html

Which gives the impression that `question` is a supported type for the SDK ... I think this was mistakenly added due to interactive embedding. Since passing `data_picker=staged` allows the entity question to appear.

There is no `data_picker` option in the SDK

### To Reproduce

Check above

### Expected behavior

Don't reference the `question` as a type if it's not supported

### Logs

None

### Information about your Metabase installation

```JSON
1.56/57
```

### Severity

Confusing

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
closes #65797
closes EMB-1026

### Backport reason
It's just type change, so safe to be backported to 57 as well.

### Description

We say we could pass `question` to our SDK components via various entity types prop. e.g. https://www.metabase.com/docs/latest/embedding/sdk/api/EmbeddingEntityType.html. Actually, `question` is only applicable sor staged picker, and that means unless our SDK fallback to staged picker which would require users to have more than 100 of combined tables or models, `question` wouldn't be used at all. This aims to remove confusion around the fact that `question` is actually meant for full-app embedding users (aka interactive embeddings)

### How to verify

When using SDK e.g. `InteractiveQuestion`, `entityTypes` would only consist of 2 values, `table` or `model`, not `question`.

### Demo

image

### Checklist

- [ ] ~Tests have been added/updated to cover changes in this PR~ just a type change.

### CODE REVIEW

File: enterprise/frontend/src/embedding/data-picker/SimpleDataPicker/SimpleDataPicker.tsx [hunk 1]
```diff
@@ -8,7 +8,7 @@ import { Box, Popover } from "metabase/ui";
 import { getQuestionVirtualTableId } from "metabase-lib/v1/metadata/utils/saved-questions";
 import type { SearchModel, SearchResult, TableId } from "metabase-types/api";
 import { SortDirection, type SortingOptions } from "metabase-types/api/sorting";
-import type { EmbeddingEntityType } from "metabase-types/store/embedding-data-picker";
+import type { ModularEmbeddingEntityType } from "metabase-types/store/embedding-data-picker";
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding/data-picker/SimpleDataPicker/SimpleDataPicker.tsx:11]: So all reference in SDK, would need to use this new type that doesn't contain `question`

File: frontend/src/embedding-sdk-bundle/components/public/dashboard/EditableDashboard/EditableDashboard.stories.tsx [hunk 2]
```diff
@@ -32,12 +32,7 @@ const meta = {
 
     "dataPickerProps.entityTypes": {
       control: "check",
-      options: [
-        "model",
-        "table",
-        "question",
-      ] satisfies SdkQuestionProps["entityTypes"],
-      description: "`question` doesn't have effect on simple data picker",
+      options: ["model", "table"] satisfies SdkQuestionProps["entityTypes"],
```
Comment (WiNloSt) [inline frontend/src/embedding-sdk-bundle/components/public/dashboard/EditableDashboard/EditableDashboard.stories.tsx:35]: this is the storybook, I suspect I added question just to satisfy the type as you can see in he description. Removing this should be no problem, as we don't want users to know we can pass it, I mean it's used in the edge case where the combined tables + models is 100 or more.

File: frontend/src/metabase-types/store/embed.ts [hunk 3]
```diff
@@ -19,7 +19,7 @@ export interface InteractiveEmbeddingOptions {
    * There might be a cleaner way to say this is in a search parameter
    * but it's not in the embed reducer, than making this optional.
    */
-  entity_types?: EmbeddingEntityType[];
+  entity_types?: FullAppEmbeddingEntityType[];
```
Comment (WiNloSt) [inline frontend/src/metabase-types/store/embed.ts:22]: This is the same type as `EmbeddingEntityType`, but the type is duplicated to make it clear this is meant for full app.

File: frontend/src/metabase-types/store/embedding-data-picker.ts [hunk 4]
```diff
@@ -2,12 +2,17 @@ export interface EmbeddingDataPickerState {
...
 /**
  * `question` only works on multi-stage data picker, not the simple data picker.
  * The reason being that we want to streamline user experience for simple embedding
  * use cases, but `question` was later added to support users who are used to
  * selecting Saved questions in interactive embedding, so this is special case.
  */
-export type EmbeddingEntityType = "model" | "table" | "question";
+export type FullAppEmbeddingEntityType = "model" | "table" | "question";
+
+export type ModularEmbeddingEntityType = "model" | "table";
```
Comment (WiNloSt) [inline frontend/src/metabase-types/store/embedding-data-picker.ts:18]: This new type is used for all modular embedding related components.

**Review by heypoom — APPROVED** [review]
> Unless our SDK fallback to staged picker which would require users to have more than 100 of combined tables or models, question wouldn't be used at all.

Should we also document that case somehow, since using questions in SDK data picker is still possible via staged pickers?

**Comment by WiNloSt** [comment]
> > Unless our SDK fallback to staged picker which would require users to have more than 100 of combined tables or models, question wouldn't be used at all.
> 
> Should we also document that case somehow, since using questions in SDK data picker is still possible via staged pickers?

@heypoom Good point. I've addressed this in f31f332962835f1375ab3c440ef343293fb0089c, which is within an `@internal` comment, so the comment won't appear on the API doc, as I don't think we should advertise this edge case. It could create more confusion.

File: frontend/src/metabase-types/store/embedding-data-picker.ts [hunk 5]
```diff
@@ -2,12 +2,19 @@ export interface EmbeddingDataPickerState {
...
 /**
  * `question` only works on multi-stage data picker, not the simple data picker.
  * The reason being that we want to streamline user experience for simple embedding
  * use cases, but `question` was later added to support users who are used to
  * selecting Saved questions in interactive embedding, so this is special case.
  */
-export type EmbeddingEntityType = "model" | "table" | "question";
+export type FullAppEmbeddingEntityType = "model" | "table" | "question";
+
+// `question` is only applicable to the staged picker, which is rarely used in SDK unless
```
Comment (WiNloSt) [inline frontend/src/metabase-types/store/embedding-data-picker.ts:16]: this originally was a JS doc comment with `@internal` but it messes up our doc and our [package generation](https://github.com/metabase/metabase/actions/runs/20506458351/job/58922807174?pr=67534#step:5:389).

What I want for this comment is to not be included in the doc, but keep the type in the doc. Using `@internal` or `@ignore` will just exclude it from the doc which isn't what we want.
