### PR TITLE
Fix flaky test and test for a new case

### LINKED ISSUE #28752: flaky test `geojson-test`
testing that it throws an error, it fails on a timeout. annoying.

```
ERROR in metabase.api.geojson-test/url-proxy-endpoint-test (jvm.clj:287)
GET /api/geojson error is returned if URL connection fails
expected: (=
           "GeoJSON URL failed to load"
           (mt/user-http-request
            :crowberto
            :get
            400
            "geojson"
            :url
            test-broken-geojson-url))
  actual: 
java.util.concurrent.TimeoutException: Timed out after 45.0 s
       metabase.util.jvm/deref-with-timeout           jvm.clj:  287
          metabase.util.jvm/do-with-timeout           jvm.clj:  294
  metabase.http-client/client-full-response   http_client.clj:  253
  metabase.http-client/client-full-response   http_client.clj:  247
                                        ...                        
                         clojure.core/apply          core.clj:  667
                metabase.http-client/client   http_client.clj:  280
                metabase.http-client/client   http_client.clj:  256
```

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes https://github.com/metabase/metabase/issues/28752

flaky test was annoying. It would timeout after 45 seconds. And annoyingly, it times out on the _client_, not the server. So we don't get the proper error message we expect. (the server will throw an error when it times out in ten minutes, but the client has long given up on the test by then).

And what's happening is that the backend just hooks up the pipe from it's request to the response. And if no bytes ever come across, we just twiddle our thumbs until the http request in the test gives up.

The only reliable way i could think of to fix this is to spin up a webserver that just accepts and then ignores requests (which is what github did to us in the flaky test).

Had to bump the ring adapter to get the newly exposed `:async-timeout 60000` parameter. By default the webserver in the test has a timeout of 30 seconds, which is shorter than the 45 second timeout for the test's request to the geojson endpoint.

### Things to think about

I chose an (arbitrary) value of 8 seconds to timeout when getting the custom geojson file. Happy to change this number.

The jetty dep bump exposes the new `:async-timeout` and sets it by default to 30 seconds. This is a non-breaking change as that was the default if no timeout was set. We also [set our own timeout](https://github.com/metabase/metabase/blob/master/src/metabase/server.clj#L67) in the application so this doesn't affect us.

Nothing stood out to me deps wise in the change.

<details>
<summary> Full deps tree</summary>

deps gotten with `clj -X:deps tree :aliases '[:dev :drivers :ee]'`
```
org.bouncycastle/bcprov-jdk15on 1.70
buddy/buddy-core 1.10.413
  X cheshire/cheshire 5.10.1 :use-top
org.clojure/java.jmx 1.0.0
org.clojure/clojure 1.11.1
  . org.clojure/spec.alpha 0.3.218
  . org.clojure/core.specs.alpha 0.2.62
lambdaisland/deep-diff2 2.7.169
  . fipp/fipp 0.6.26
    . org.clojure/core.rrb-vector 0.1.2
  . org.clojure/core.rrb-vector 0.1.2
  . lambdaisland/clj-diff 1.4.78
  . mvxcvi/arrangement 2.1.0
org.apache.logging.log4j/log4j-slf4j-impl 2.19.0
  X org.slf4j/slf4j-api 1.7.25 :use-top
  X org.apache.logging.log4j/log4j-api 2.19.0 :use-top
  X org.apache.logging.log4j/log4j-core 2.19.0 :use-top
com.fasterxml.woodstox/woodstox-core 6.4.0
  . org.codehaus.woodstox/stax2-api 4.2.1
joda-time/joda-time 2.12.2
commons-codec/commons-codec 1.15
weavejester/dependency 0.2.1
com.vladsch.flexmark/flexmark-ext-autolink 0.64.0
  . com.vladsch.flexmark/flexmark-util 0.64.0
    . com.vladsch.flexmark/flexmark-util-ast 0.64.0
    . com.vladsch.flexmark/flexmark-util-builder 0.64.0
    . com.vladsch.flexmark/flexmark-util-collection 0.64.0
    . com.vladsch.flexmark/flexmark-util-data 0.64.0
    . com.vladsch.flexmark/flexmark-util-dependency 0.64.0
    . com.vladsch.flexmark/flexmark-util-format 0.64.0
    . com.vladsch.flexmark/flexmark-util-html 0.64.0
    . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . com.vladsch.flexmark/flexmark-util-options 0.64.0
      . com.vladsch.flexmark/flexmark-util-misc 0.64.0
      . com.vladsch.flexmark/flexmark-util-sequence 0.64.0
      . org.jetbrains/annotations 15.0
    . com.vladsch.flexmark/flexmark-util-sequence 0.64.0
    . com.vladsch.flexmark/flexmark-util-visitor 0.64.0
    . org.jetbrains/annotations 15.0
  X com.vladsch.flexmark/flexmark 0.64.0 :use-top
  . org.nibor.autolink/autolink 0.6.0
org.apache.poi/poi 5.2.3
  X commons-codec/commons-codec 1.15 :use-top
  . org.apache.commons/commons-collections4 4.4
  . org.apache.commons/commons-math3 3.6.1
  X commons-io/commons-io 2.11.0 :use-top
  . com.zaxxer/SparseBitSet 1.2
  X org.apache.logging.log4j/log4j-api 2.18.0 :use-top
org.apache.commons/commons-compress 1.22
org.apache.commons/commons-lang3 3.12.0
com.draines/postal 2.0.5
  X commons-codec/commons-codec 1.9 :use-top
  . com.sun.mail/jakarta.mail 1.6.5
    . com.sun.activation/jakarta.activation 1.2.1
commons-validator/commons-validator 1.7
  . commons-collections/commons-collections 3.2.2
org.clojure/tools.logging 1.2.4
org.liquibase/liquibase-core 4.11.0
  . javax.xml.bind/jaxb-api 2.3.1
    . javax.activation/javax.activation-api 1.2.0
org.bouncycastle/bcpkix-jdk15on 1.70
  X org.bouncycastle/bcprov-jdk15on 1.70 :use-top
  . org.bouncycastle/bcutil-jdk15on 1.70
    X org.bouncycastle/bcprov-jdk15on 1.70 :use-top
com.github.vertical-blank/sql-formatter 2.0.3
org.apache.xmlgraphics/batik-all 1.16
  . xml-apis/xml-apis 1.4.01
  . xml-apis/xml-apis-ext 1.3.04
  . org.apache.xmlgraphics/xmlgraphics-commons 2.7
    X commons-io/commons-io 1.3.1 :use-top
    X commons-logging/commons-logging 1.0.4 :older-version
redux/redux 0.1.4
io.prometheus/simpleclient_jetty 0.16.0
  . io.prometheus/simpleclient 0.16.0
    . io.prometheus/simpleclient_tracer_otel 0.16.0
      . io.prometheus/simpleclient_tracer_common 0.16.0
    . io.prometheus/simpleclient_tracer_otel_agent 0.16.0
      . io.prometheus/simpleclient_tracer_common 0.16.0
  X org.eclipse.jetty/jetty-server 9.4.44.v20210927 :use-top
  X org.eclipse.jetty/jetty-servlet 9.4.44.v20210927 :superseded
    . org.eclipse.jetty/jetty-security 9.4.44.v20210927
      X org.eclipse.jetty/jetty-server 9.4.44.v20210927 :use-top
    . org.eclipse.jetty/jetty-util-ajax 9.4.44.v20210927
      X org.eclipse.jetty/jetty-util 9.4.44.v20210927 :parent-omitted
colorize/colorize 0.1.1
org.clojars.pntblnk/clj-ldap 0.0.17
  . com.unboundid/unboundid-ldapsdk 5.1.1
org.graalvm.js/js 22.3.0
  . org.graalvm.regex/regex 22.3.0
    . org.graalvm.truffle/truffle-api 22.3.0
    . com.ibm.icu/icu4j 71.1
  . org.graalvm.truffle/truffle-api 22.3.0
    . org.graalvm.sdk/graal-sdk 22.3.0
  . org.graalvm.sdk/graal-sdk 22.3.0
  . com.ibm.icu/icu4j 71.1
com.fasterxml.jackson.core/jackson-databind 2.14.1
  . com.fasterxml.jackson.core/jackson-annotations 2.14.1
  . com.fasterxml.jackson.core/jackson-core 2.14.1
metabase/saml20-clj 2.1.0
  X org.clojure/tools.logging 1.2.4 :use-top
  . org.opensaml/opensaml-core 4.2.0
    X commons-codec/commons-codec 1.15 :use-top
    . com.google.code.findbugs/jsr305 3.0.2
    X com.google.guava/guava 31.1-jre :use-top
    . io.dropwizard.metrics/metrics-core 4.2.9
      X org.slf4j/slf4j-api 1.7.36 :use-top
    X org.slf4j/slf4j-api 1.7.36 :use-top
    . net.shibboleth.utilities/java-support 8.3.1
      X org.slf4j/slf4j-api 1.7.36 :use-top
      X commons-codec/commons-codec 1.15 :use-top
      . com.google.code.findbugs/jsr305 3.0.2
      X com.google.guava/guava 31.1-jre :use-top
  . org.clojure/spec.alpha 0.3.218
  . com.onelogin/java-saml 2.9.0
    . com.onelogin/java-saml-core 2.9.0
      X org.slf4j/slf4j-api 1.7.35 :use-top
      X joda-time/joda-time 2.10.6 :use-top
      X org.apache.commons/commons-lang3 3.12.0 :use-top
      X org.apache.santuario/xmlsec 2.2.3 :older-version
      X commons-codec/commons-codec 1.15 :use-top
    X org.slf4j/slf4j-api 1.7.35 :use-top
    X joda-time/joda-time 2.10.6 :use-top
    X org.apache.commons/commons-lang3 3.12.0 :use-top
    X org.apache.santuario/xmlsec 2.2.3 :older-version
    X commons-codec/commons-codec 1.15 :use-top
  . org.apache.santuario/xmlsec 3.0.1
    X org.slf4j/slf4j-api 1.7.36 :use-top
    . jakarta.xml.bind/jakarta.xml.bind-api 3.0.1
    X commons-codec/commons-codec 1.15 :use-top
    X com.fasterxml.woodstox/woodstox-core 6.2.8 :use-top
  . org.opensaml/opensaml-xmlsec-api 4.2.0
    . org.opensaml/opensaml-core 4.2.0
    . org.opensaml/opensaml-messaging-api 4.2.0
      . org.opensaml/opensaml-core 4.2.0
      . com.google.code.findbugs/jsr305 3.0.2
      X com.google.guava/guava 31.1-jre :use-top
      . org.apache.httpcomponents/httpclient 4.5.13
      . org.apache.httpcomponents/httpcore 4.4.15
      X org.slf4j/slf4j-api 1.7.36 :use-top
      . net.shibboleth.utilities/java-support 8.3.1
    . org.opensaml/opensaml-security-api 4.2.0
      . org.opensaml/opensaml-core 4.2.0
      . org.opensaml/opensaml-messaging-api 4.2.0
      X commons-codec/commons-codec 1.15 :use-top
      . com.google.code.findbugs/jsr305 3.0.2
      X com.google.guava/guava 31.1-jre :use-top
      X org.cryptacular/cryptacular 1.2.4 :older-version
      X org.bouncycastle/bcprov-jdk15on 1.70 :use-top
      X org.bouncycastle/bcpkix-jdk15on 1.70 :use-top
      . org.apache.httpcomponents/httpclient 4.5.13
      X org.slf4j/slf4j-api 1.7.36 :use-top
      . net.shibboleth.utilities/java-support 8.3.1
    . com.google.code.findbugs/jsr305 3.0.2
    X com.google.guava/guava 31.1-jre :use-top
    X org.apache.santuario/xmlsec 2.3.0 :older-version
    X org.slf4j/slf4j-api 1.7.36 :use-top
    . net.shibboleth.utilities/java-support 8.3.1
  . org.cryptacular/cryptacular 1.2.5
    . org.bouncycastle/bcprov-jdk18on 1.71
  X commons-io/commons-io 2.11.0 :use-top
  . org.opensaml/opensaml-xmlsec-impl 4.2.0
    . org.opensaml/opensaml-core 4.2.0
    . org.opensaml/opensaml-messaging-api 4.2.0
    . org.opensaml/opensaml-security-api 4.2.0
    . org.opensaml/opensaml-xmlsec-api 4.2.0
    . com.google.code.findbugs/jsr305 3.0.2
    X com.google.guava/guava 31.1-jre :use-top
    X org.apache.santuario/xmlsec 2.3.0 :older-version
    X org.cryptacular/cryptacular 1.2.4 :older-version
    . org.opensaml/opensaml-security-impl 4.2.0
      . org.opensaml/opensaml-core 4.2.0
      . org.opensaml/opensaml-messaging-api 4.2.0
      . org.opensaml/opensaml-security-api 4.2.0
      X commons-codec/commons-codec 1.15 :use-top
      . com.google.code.findbugs/jsr305 3.0.2
      X com.google.guava/guava 31.1-jre :use-top
      X org.cryptacular/cryptacular 1.2.4 :older-version
      X org.slf4j/slf4j-api 1.7.36 :use-top
      . net.shibboleth.utilities/java-support 8.3.1
    X org.slf4j/slf4j-api 1.7.36 :use-top
    . net.shibboleth.utilities/java-support 8.3.1
  . org.opensaml/opensaml-saml-impl 4.2.0
    . org.opensaml/opensaml-core 4.2.0
    . org.opensaml/opensaml-messaging-api 4.2.0
    . org.opensaml/opensaml-profile-api 4.2.0
      . org.opensaml/opensaml-core 4.2.0
      . org.opensaml/opensaml-messaging-api 4.2.0
      . com.google.code.findbugs/jsr305 3.0.2
      X com.google.guava/guava 31.1-jre :use-top
      . io.dropwizard.metrics/metrics-core 4.2.9
      X org.slf4j/slf4j-api 1.7.36 :use-top
      . net.shibboleth.utilities/java-support 8.3.1
    . org.opensaml/opensaml-saml-api 4.2.0
    . org.opensaml/opensaml-security-api 4.2.0
    . org.opensaml/opensaml-security-impl 4.2.0
    . org.opensaml/opensaml-soap-api 4.2.0
      . org.opensaml/opensaml-core 4.2.0
      . org.opensaml/opensaml-messaging-api 4.2.0
      . org.opensaml/opensaml-security-api 4.2.0
      . org.opensaml/opensaml-xmlsec-api 4.2.0
      . com.google.code.findbugs/jsr305 3.0.2
      X com.google.guava/guava 31.1-jre :use-top
      . org.apache.httpcomponents/httpclient 4.5.13
      . org.apache.httpcomponents/httpcore 4.4.15
      X org.slf4j/slf4j-api 1.7.36 :use-top
      . net.shibboleth.utilities/java-support 8.3.1
    . org.opensaml/opensaml-soap-impl 4.2.0
      . org.opensaml/opensaml-core 4.2.0
      . org.opensaml/opensaml-messaging-api 4.2.0
      . org.opensaml/opensaml-profile-api 4.2.0
      . org.opensaml/opensaml-soap-api 4.2.0
      . org.opensaml/opensaml-xmlsec-api 4.2.0
      . com.google.code.findbugs/jsr305 3.0.2
      X com.google.guava/guava 31.1-jre :use-top
      . org.apache.httpcomponents/httpclient 4.5.13
      . org.apache.httpcomponents/httpcore 4.4.15
      X org.slf4j/slf4j-api 1.7.36 :use-top
      . net.shibboleth.utilities/java-support 8.3.1
    . org.opensaml/opensaml-storage-api 4.2.0
      . com.google.code.findbugs/jsr305 3.0.2
      X com.google.guava/guava 31.1-jre :use-top
      X org.slf4j/slf4j-api 1.7.36 :use-top
      . net.shibboleth.utilities/java-support 8.3.1
    . org.opensaml/opensaml-xmlsec-api 4.2.0
    . org.opensaml/opensaml-xmlsec-impl 4.2.0
    X commons-codec/commons-codec 1.15 :use-top
    . com.google.code.findbugs/jsr305 3.0.2
    X com.google.guava/guava 31.1-jre :use-top
    . io.dropwizard.metrics/metrics-core 4.2.9
    X org.apache.santuario/xmlsec 2.3.0 :older-version
    . org.apache.velocity/velocity-engine-core 2.3
      X org.apache.commons/commons-lang3 3.11 :use-top
      X org.slf4j/slf4j-api 1.7.30 :use-top
    . org.apache.httpcomponents/httpclient 4.5.13
    . org.apache.httpcomponents/httpcore 4.4.15 :newer-version
    X org.slf4j/slf4j-api 1.7.36 :use-top
    . net.shibboleth.utilities/java-support 8.3.1
  X hiccup/hiccup 1.0.5 :use-top
  X clojure.java-time/clojure.java-time 1.1.0 :use-top
  . ring/ring-codec 1.2.0
  X potemkin/potemkin 0.4.6 :use-top
  X pretty/pretty 1.0.5 :use-top
  . org.opensaml/opensaml-saml-api 4.2.0
    . org.opensaml/opensaml-core 4.2.0
    . org.opensaml/opensaml-messaging-api 4.2.0
    . org.opensaml/opensaml-profile-api 4.2.0
    . org.opensaml/opensaml-security-api 4.2.0
    . org.opensaml/opensaml-soap-api 4.2.0
    . org.opensaml/opensaml-xmlsec-api 4.2.0
    X commons-codec/commons-codec 1.15 :use-top
    . com.google.code.findbugs/jsr305 3.0.2
    X com.google.guava/guava 31.1-jre :use-top
    X org.apache.santuario/xmlsec 2.3.0 :older-version
    X org.slf4j/slf4j-api 1.7.36 :use-top
    . net.shibboleth.utilities/java-support 8.3.1
compojure/compojure 1.7.0
  X org.clojure/tools.macro 0.1.5 :use-top
  . clout/clout 2.2.1
    X instaparse/instaparse 1.4.8 :use-top
  X medley/medley 1.4.0 :use-top
  X ring/ring-core 1.9.5 :use-top
org.clojure/tools.trace 0.7.11
com.vladsch.flexmark/flexmark 0.64.0
  . com.vladsch.flexmark/flexmark-util-ast 0.64.0
    . com.vladsch.flexmark/flexmark-util-collection 0.64.0
    . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . com.vladsch.flexmark/flexmark-util-data 0.64.0
    . com.vladsch.flexmark/flexmark-util-sequence 0.64.0
    . com.vladsch.flexmark/flexmark-util-visitor 0.64.0
    . org.jetbrains/annotations 15.0
  . com.vladsch.flexmark/flexmark-util-builder 0.64.0
    . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . com.vladsch.flexmark/flexmark-util-data 0.64.0
    . org.jetbrains/annotations 15.0
  . com.vladsch.flexmark/flexmark-util-collection 0.64.0
    . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . org.jetbrains/annotations 15.0
  . com.vladsch.flexmark/flexmark-util-data 0.64.0
    . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . org.jetbrains/annotations 15.0
  . com.vladsch.flexmark/flexmark-util-dependency 0.64.0
    . com.vladsch.flexmark/flexmark-util-collection 0.64.0
    . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . com.vladsch.flexmark/flexmark-util-data 0.64.0
    . org.jetbrains/annotations 15.0
  . com.vladsch.flexmark/flexmark-util-format 0.64.0
    . com.vladsch.flexmark/flexmark-util-ast 0.64.0
    . com.vladsch.flexmark/flexmark-util-collection 0.64.0
    . com.vladsch.flexmark/flexmark-util-data 0.64.0
    . com.vladsch.flexmark/flexmark-util-html 0.64.0
    . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . com.vladsch.flexmark/flexmark-util-sequence 0.64.0
    . org.jetbrains/annotations 15.0
  . com.vladsch.flexmark/flexmark-util-html 0.64.0
    . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . com.vladsch.flexmark/flexmark-util-sequence 0.64.0
    . org.jetbrains/annotations 15.0
  . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . org.jetbrains/annotations 15.0
  . com.vladsch.flexmark/flexmark-util-sequence 0.64.0
    . com.vladsch.flexmark/flexmark-util-collection 0.64.0
    . com.vladsch.flexmark/flexmark-util-data 0.64.0
    . com.vladsch.flexmark/flexmark-util-misc 0.64.0
    . org.jetbrains/annotations 15.0
  . com.vladsch.flexmark/flexmark-util-visitor 0.64.0
    . org.jetbrains/annotations 15.0
methodical/methodical 0.15.1
  X mvxcvi/puget 1.3.2 :superseded
    X mvxcvi/arrangement 2.0.0 :parent-omitted
    X fipp/fipp 0.6.24 :parent-omitted
  X potemkin/potemkin 0.4.5 :use-top
  X pretty/pretty 1.0.5 :use-top
org.apache.logging.log4j/log4j-jul 2.19.0
  X org.apache.logging.log4j/log4j-api 2.19.0 :use-top
org.clojure/tools.macro 0.1.5
io.github.metabase/hawk 45ed360
  . eftest/eftest 0.6.0
    X org.clojure/tools.namespace 1.3.0 :use-top
    . progrock/progrock 0.1.2
    . io.aviso/pretty 1.3
      X org.clojure/tools.logging 1.2.4 :use-top
    . mvxcvi/puget 1.3.4
  X methodical/methodical 0.15.1 :use-top
  X commons-io/commons-io 2.11.0 :use-top
  X org.clojure/tools.namespace 1.3.0 :use-top
  X pjstadig/humane-test-output 0.11.0 :use-top
  X org.clojure/java.classpath 1.0.0 :use-top
  X environ/environ 1.2.0 :use-top
  X org.clojure/algo.generic 0.1.3 :use-top
  X prismatic/schema 1.4.1 :use-top
com.gfredericks/test.chuck 0.2.13
  X org.clojure/test.check 1.1.0 :superseded
  . clj-time/clj-time 0.15.2
    X joda-time/joda-time 2.10 :use-top
  . com.andrewmcveigh/cljs-time 0.5.2
  X instaparse/instaparse 1.4.10 :use-top
metabase/throttle 1.0.2
  X org.clojure/math.numeric-tower 0.0.4 :use-top
net.redhogs.cronparser/cron-parser-core 3.5
  X org.apache.commons/commons-lang3 3.3.2 :use-top
com.h2database/h2 2.1.212
org.clojure/core.logic 1.0.1
bigml/histogram 4.1.4
  . com.googlecode.json-simple/json-simple 1.1.1
    . junit/junit 4.10
      . org.hamcrest/hamcrest-core 1.1
honeysql/honeysql 1.0.461
clojurewerkz/quartzite 2.1.0
  X clj-time/clj-time 0.14.0 :older-version
slingshot/slingshot 0.12.2
net.sf.cssbox/cssbox 5.0.0
  . net.sourceforge.nekohtml/nekohtml 1.9.22
    . xerces/xercesImpl 2.11.0
      . xml-apis/xml-apis 1.4.01
  . net.sf.cssbox/jstyleparser 4.0.0
    . org.antlr/antlr4-runtime 4.5.3
    X org.slf4j/slf4j-api 1.7.25 :excluded
    . org.unbescape/unbescape 1.1.6.RELEASE
ring/ring-json 0.5.1
  X cheshire/cheshire 5.10.0 :use-top
  X ring/ring-core 1.9.2 :use-top
org.flatland/ordered 1.15.10
commons-io/commons-io 2.11.0
org.postgresql/postgresql 42.5.1
  X org.checkerframework/checker-qual 3.5.0 :superseded
org.clojure/tools.namespace 1.3.0
  X org.clojure/java.classpath 1.0.0 :use-top
  X org.clojure/tools.reader 1.3.6 :use-top
com.github.seancorfield/honeysql 2.4.962
io.github.camsaul/toucan2-toucan1 1.0.519
djblue/portal 0.35.0
  . org.clojure/data.json 2.4.0
  . com.cognitect/transit-cljs 0.8.280
    . com.cognitect/transit-js 0.8.874
  . com.cognitect/transit-clj 1.0.329
    . com.cognitect/transit-java 1.0.362
      X com.fasterxml.jackson.core/jackson-core 2.8.7 :older-version
      . org.msgpack/msgpack 0.6.12
        . com.googlecode.json-simple/json-simple 1.1.1
        . org.javassist/javassist 3.18.1-GA
      X javax.xml.bind/jaxb-api 2.3.0 :older-version
  . com.google.code.gson/gson 2.10
  . http-kit/http-kit 2.6.0
org.yaml/snakeyaml 1.33
clj-http/clj-http 3.12.3
  X org.apache.httpcomponents/httpcore 4.4.14 :superseded
  . org.apache.httpcomponents/httpclient 4.5.13
    X org.apache.httpcomponents/httpcore 4.4.13 :older-version
    . commons-logging/commons-logging 1.2
    X commons-codec/commons-codec 1.11 :excluded
  . org.apache.httpcomponents/httpclient-cache 4.5.13
    . org.apache.httpcomponents/httpclient 4.5.13
    . commons-logging/commons-logging 1.2
  . org.apache.httpcomponents/httpasyncclient 4.1.4
    X org.apache.httpcomponents/httpcore 4.4.10 :older-version
    . org.apache.httpcomponents/httpcore-nio 4.4.10
      X org.apache.httpcomponents/httpcore 4.4.10 :older-version
    X org.apache.httpcomponents/httpclient 4.5.6 :older-version
    . commons-logging/commons-logging 1.2
  . org.apache.httpcomponents/httpmime 4.5.13
    . org.apache.httpcomponents/httpclient 4.5.13
  X potemkin/potemkin 0.4.5 :use-top
metabase/driver-modules /Users/dan/projects/work/metabase/modules/drivers
  . metabase/vertica /Users/dan/projects/work/metabase/modules/drivers/vertica
    . com.vertica.jdbc/vertica-jdbc 12.0.3-0
  . metabase/sparksql /Users/dan/projects/work/metabase/modules/drivers/sparksql
    . org.apache.hive/hive-jdbc 3.1.3
      . org.apache.hive/hive-common 3.1.3
        X org.apache.hive/hive-classification 3.1.3 :excluded
        X org.apache.hive/hive-shims 3.1.3 :excluded
        X org.apache.hive/hive-storage-api 2.7.0 :excluded
        X commons-cli/commons-cli 1.2 :excluded
        . commons-lang/commons-lang 2.6
        X org.apache.commons/commons-lang3 3.9 :excluded
        X org.apache.orc/orc-core 1.5.8 :excluded
        X jline/jline 2.12 :excluded
        X javax.servlet/javax.servlet-api 3.1.0 :excluded
        X org.eclipse.jetty/jetty-http 9.3.20.v20170531 :excluded
        X org.eclipse.jetty/jetty-rewrite 9.3.20.v20170531 :excluded
        X org.eclipse.jetty/jetty-server 9.3.20.v20170531 :excluded
        X org.eclipse.jetty/jetty-servlet 9.3.20.v20170531 :excluded
        X org.eclipse.jetty/jetty-webapp 9.3.20.v20170531 :excluded
        X joda-time/joda-time 2.9.9 :excluded
        X org.apache.logging.log4j/log4j-1.2-api 2.17.1 :excluded
        X org.apache.logging.log4j/log4j-web 2.17.1 :excluded
        X org.apache.logging.log4j/log4j-slf4j-impl 2.17.1 :excluded
        X org.apache.commons/commons-compress 1.19 :excluded
        X org.apache.ant/ant 1.9.1 :excluded
        X net.sf.jpam/jpam 1.1 :excluded
        X com.tdunning/json 1.8 :excluded
        X io.dropwizard.metrics/metrics-core 3.1.0 :excluded
        X io.dropwizard.metrics/metrics-jvm 3.1.0 :excluded
        X io.dropwizard.metrics/metrics-json 3.1.0 :excluded
        X com.fasterxml.jackson.core/jackson-databind 2.12.0 :excluded
        X com.github.joshelser/dropwizard-metrics-hadoop-metrics2-reporter 0.1.2 :excluded
        X javolution/javolution 5.5.1 :excluded
        X org.slf4j/slf4j-api 1.7.10 :excluded
        X org.apache.hive/hive-upgrade-acid 3.1.3 :excluded
      . org.apache.hive/hive-service 3.1.3
        X org.apache.hive/hive-metastore 3.1.3 :excluded
        . org.apache.hive/hive-service-rpc 3.1.3
        X org.apache.hive/hive-llap-server 3.1.3 :excluded
        X javax.servlet.jsp/javax.servlet.jsp-api 2.3.1 :excluded
        X commons-codec/commons-codec 1.15 :excluded
        X commons-cli/commons-cli 1.2 :excluded
        X net.sf.jpam/jpam 1.1 :excluded
        X org.eclipse.jetty/jetty-server 9.3.20.v20170531 :excluded
        X org.eclipse.jetty/jetty-servlet 9.3.20.v20170531 :excluded
        X org.eclipse.jetty/jetty-runner 9.3.20.v20170531 :excluded
        X javax.servlet/javax.servlet-api 3.1.0 :excluded
        . commons-lang/commons-lang 2.6
        X org.apache.thrift/libfb303 0.9.3 :excluded
        . org.apache.thrift/libthrift 0.9.3
        . org.apache.curator/curator-framework 2.12.0
        X org.apache.curator/curator-recipes 2.12.0 :excluded
        X org.jamon/jamon-runtime 2.3.1 :excluded
        X org.slf4j/slf4j-api 1.7.10 :excluded
        X org.apache.hive/hive-upgrade-acid 3.1.3 :excluded
      . org.apache.hive/hive-serde 3.1.3
        . org.apache.hive/hive-common 3.1.3
        . org.apache.hive/hive-service-rpc 3.1.3
        X org.apache.hive/hive-shims 3.1.3 :excluded
        X com.google.code.findbugs/jsr305 3.0.0 :excluded
        X commons-codec/commons-codec 1.15 :excluded
        . commons-lang/commons-lang 2.6
        . org.apache.arrow/arrow-vector 0.8.0
          X org.apache.arrow/arrow-format 0.8.0 :excluded
          X org.apache.arrow/arrow-memory 0.8.0 :excluded
          X joda-time/joda-time 2.9.9 :excluded
          X com.fasterxml.jackson.core/jackson-core 2.7.9 :excluded
          X com.fasterxml.jackson.core/jackson-annotations 2.7.9 :excluded
          X com.fasterxml.jackson.core/jackson-databind 2.7.9 :excluded
          X com.carrotsearch/hppc 0.7.2 :excluded
          X commons-codec/commons-codec 1.10 :excluded
          X com.google.guava/guava 18.0 :excluded
          X io.netty/netty-buffer 4.1.17.Final :excluded
          X io.netty/netty-common 4.1.17.Final :excluded
          X com.vlkan/flatbuffers 1.2.0-3f79e055 :excluded
          X com.google.code.findbugs/jsr305 3.0.2 :excluded
          X org.slf4j/slf4j-api 1.7.25 :excluded
        X com.carrotsearch/hppc 0.7.2 :excluded
        X com.vlkan/flatbuffers 1.2.0-3f79e055 :excluded
        X org.apache.avro/avro 1.8.2 :excluded
        . org.apache.thrift/libthrift 0.9.3
        X net.sf.opencsv/opencsv 2.3 :excluded
        X org.apache.parquet/parquet-hadoop-bundle 1.10.0 :excluded
        X org.slf4j/slf4j-api 1.7.10 :excluded
        X org.apache.hive/hive-upgrade-acid 3.1.3 :excluded
      . org.apache.hive/hive-service-rpc 3.1.3
        X commons-codec/commons-codec 1.15 :excluded
        X commons-cli/commons-cli 1.2 :excluded
        X org.apache.thrift/libfb303 0.9.3 :excluded
        . org.apache.thrift/libthrift 0.9.3
        X org.apache.hive/hive-classification 3.1.3 :excluded
        X org.slf4j/slf4j-api 1.7.10 :excluded
        X org.apache.hive/hive-upgrade-acid 3.1.3 :excluded
      . org.apache.thrift/libthrift 0.9.3
        X org.slf4j/slf4j-api 1.7.12 :excluded
        X org.apache.httpcomponents/httpclient 4.4.1 :excluded
        X org.apache.httpcomponents/httpcore 4.4.1 :excluded
      . org.apache.curator/curator-framework 2.12.0
        . org.apache.curator/curator-client 2.12.0
          X org.apache.zookeeper/zookeeper 3.4.8 :excluded
          X com.google.guava/guava 16.0.1 :excluded
          X org.slf4j/slf4j-api 1.7.6 :excluded
  . metabase/sqlite /Users/dan/projects/work/metabase/modules/drivers/sqlite
    . org.xerial/sqlite-jdbc 3.40.0.0
  . metabase/bigquery-cloud-sdk /Users/dan/projects/work/metabase/modules/drivers/bigquery-cloud-sdk
    . com.google.cloud/google-cloud-bigquery 1.135.4
      . com.google.cloud/google-cloud-core 1.95.4
      . com.google.protobuf/protobuf-java-util 3.17.3
      X com.google.code.gson/gson 2.8.7 :older-version
      . com.google.api.grpc/proto-google-common-protos 2.3.2
      . com.google.api.grpc/proto-google-iam-v1 1.0.14
      . com.google.auth/google-auth-library-credentials 0.26.0
      X com.google.http-client/google-http-client-gson 1.39.2 :superseded
      . com.google.protobuf/protobuf-java 3.17.3
      . com.google.cloud/google-cloud-core-http 1.95.4
      . com.google.api-client/google-api-client 1.32.1
      X com.google.oauth-client/google-oauth-client 1.31.5 :older-version
      . com.google.http-client/google-http-client-apache-v2 1.39.2
      . com.google.http-client/google-http-client-appengine 1.39.2
      . com.google.api/gax-httpjson 0.83.0
      X io.opencensus/opencensus-api 0.28.0 :superseded
      . io.grpc/grpc-context 1.39.0
      X io.opencensus/opencensus-contrib-http-util 0.28.0 :superseded
      X com.google.http-client/google-http-client-jackson2 1.39.2 :older-version
      X com.fasterxml.jackson.core/jackson-core 2.12.3 :older-version
      X com.google.http-client/google-http-client 1.39.2 :superseded
      . org.apache.httpcomponents/httpclient 4.5.13
      . commons-logging/commons-logging 1.2
      X commons-codec/commons-codec 1.15 :use-top
      X org.apache.httpcomponents/httpcore 4.4.14 :older-version
      . com.google.j2objc/j2objc-annotations 1.3
      . org.checkerframework/checker-compat-qual 2.5.5
      . com.google.auth/google-auth-library-oauth2-http 0.26.0
      . com.google.code.findbugs/jsr305 3.0.2
      . com.google.apis/google-api-services-bigquery v2-rev20210617-1.32.1
      . com.google.api/api-common 1.10.4
      . javax.annotation/javax.annotation-api 1.3.2
      X com.google.guava/guava 30.1.1-android :use-top
      . com.google.guava/failureaccess 1.0.1
      . com.google.guava/listenablefuture 9999.0-empty-to-avoid-conflict-with-guava
      . com.google.api/gax 1.66.0
      . org.threeten/threetenbp 1.5.1
      X com.google.errorprone/error_prone_annotations 2.7.1 :older-version
    . com.google.code.gson/gson 2.10
    . com.google.oauth-client/google-oauth-client 1.34.1
      X com.google.http-client/google-http-client 1.42.0 :superseded
        X org.apache.httpcomponents/httpclient 4.5.13 :parent-omitted
        X org.apache.httpcomponents/httpcore 4.4.15 :parent-omitted
        X com.google.code.findbugs/jsr305 3.0.2 :parent-omitted
        X com.google.guava/guava 30.1.1-android :use-top
        X com.google.j2objc/j2objc-annotations 1.3 :parent-omitted
        X io.opencensus/opencensus-api 0.31.1 :parent-omitted
        X io.opencensus/opencensus-contrib-http-util 0.31.1 :parent-omitted
      . com.google.http-client/google-http-client-gson 1.42.0 :newer-version
        X com.google.http-client/google-http-client 1.42.0 :older-version
        X com.google.code.gson/gson 2.9.0 :older-version
      X com.google.guava/guava 31.1-android :use-top
  . metabase/snowflake /Users/dan/projects/work/metabase/modules/drivers/snowflake
    . net.snowflake/snowflake-jdbc 3.13.26
  . metabase/athena /Users/dan/projects/work/metabase/modules/drivers/athena
    . com.amazonaws/aws-java-sdk-core 1.12.392
      X commons-logging/commons-logging 1.1.3 :older-version
      X commons-codec/commons-codec 1.15 :use-top
      . org.apache.httpcomponents/httpclient 4.5.13
      . software.amazon.ion/ion-java 1.0.2
      X com.fasterxml.jackson.core/jackson-databind 2.12.7.1 :use-top
      X com.fasterxml.jackson.dataformat/jackson-dataformat-cbor 2.12.6 :older-version
      X joda-time/joda-time 2.8.1 :use-top
    . com.metabase/athena-jdbc 2.0.35
  . metabase/sqlserver /Users/dan/projects/work/metabase/modules/drivers/sqlserver
    . com.microsoft.sqlserver/mssql-jdbc 10.2.1.jre11
  . metabase/googleanalytics /Users/dan/projects/work/metabase/modules/drivers/googleanalytics
    . com.google.apis/google-api-services-analytics v3-rev20190807-1.32.1
      . com.google.api-client/google-api-client 1.32.1
        X com.google.oauth-client/google-oauth-client 1.31.5 :older-version
        X com.google.http-client/google-http-client-gson 1.39.2 :older-version
        X com.google.guava/guava 30.1.1-android :use-top
        . com.google.http-client/google-http-client-apache-v2 1.39.2
          X com.google.http-client/google-http-client 1.39.2 :older-version
          . org.apache.httpcomponents/httpclient 4.5.13
          X org.apache.httpcomponents/httpcore 4.4.14 :older-version
        X org.apache.httpcomponents/httpcore 4.4.14 :older-version
        . org.apache.httpcomponents/httpclient 4.5.13
        X com.google.http-client/google-http-client 1.39.2 :older-version
    . com.google.code.gson/gson 2.10
    . com.google.oauth-client/google-oauth-client 1.34.1
    . com.google.http-client/google-http-client-jackson2 1.42.3
      . com.google.http-client/google-http-client 1.42.3 :newer-version
        . org.apache.httpcomponents/httpclient 4.5.13
        . org.apache.httpcomponents/httpcore 4.4.15
        . com.google.code.findbugs/jsr305 3.0.2
        . com.google.errorprone/error_prone_annotations 2.16 :newer-version
        X com.google.guava/guava 30.1.1-android :use-top
        . com.google.j2objc/j2objc-annotations 1.3
        . io.opencensus/opencensus-api 0.31.1 :newer-version
          X io.grpc/grpc-context 1.27.2 :older-version
        . io.opencensus/opencensus-contrib-http-util 0.31.1 :newer-version
          . io.opencensus/opencensus-api 0.31.1
          X com.google.guava/guava 29.0-android :use-top
      X com.fasterxml.jackson.core/jackson-core 2.13.4 :older-version
  . metabase/presto-jdbc /Users/dan/projects/work/metabase/modules/drivers/presto-jdbc
    . com.facebook.presto/presto-jdbc 0.278.1
  . metabase/redshift /Users/dan/projects/work/metabase/modules/drivers/redshift
    . com.amazon.redshift/redshift-jdbc42 2.1.0.10
  . metabase/oracle /Users/dan/projects/work/metabase/modules/drivers/oracle
    . com.oracle.ojdbc/ojdbc8 19.3.0.0
      . com.oracle.ojdbc/ucp 19.3.0.0
      . com.oracle.ojdbc/oraclepki 19.3.0.0
      . com.oracle.ojdbc/osdt_cert 19.3.0.0
      . com.oracle.ojdbc/osdt_core 19.3.0.0
      . com.oracle.ojdbc/simplefan 19.3.0.0
        . com.oracle.ojdbc/ons 19.3.0.0
      . com.oracle.ojdbc/ons 19.3.0.0
  . metabase/mongo /Users/dan/projects/work/metabase/modules/drivers/mongo
    . com.novemberain/monger 3.6.0
      . org.mongodb/mongodb-driver 3.12.11
        . org.mongodb/bson 3.12.11
        . org.mongodb/mongodb-driver-core 3.12.11
          . org.mongodb/bson 3.12.11
      . clojurewerkz/support 1.5.0
        X com.google.guava/guava 21.0 :use-top
  . metabase/druid /Users/dan/projects/work/metabase/modules/drivers/druid
org.apache.logging.log4j/log4j-core 2.19.0
  X org.apache.logging.log4j/log4j-api 2.19.0 :use-top
user-agent/user-agent 0.1.0
  X net.sf.uadetector/uadetector-core 0.9.10 :superseded
    . net.sf.qualitycheck/quality-check 1.3
      X com.google.code.findbugs/jsr305 2.0.1 :parent-omitted
    X com.google.code.findbugs/jsr305 2.0.1 :older-version
    . javax.annotation/jsr250-api 1.0
    X org.slf4j/slf4j-api 1.7.5 :use-top
  . net.sf.uadetector/uadetector-resources 2014.10
    . net.sf.uadetector/uadetector-core 0.9.22 :newer-version
      . net.sf.qualitycheck/quality-check 1.3
        X com.google.code.findbugs/jsr305 2.0.1 :older-version
      X com.google.code.findbugs/jsr305 2.0.3 :older-version
      . javax.annotation/jsr250-api 1.0
      X org.slf4j/slf4j-api 1.7.7 :use-top
    X org.slf4j/slf4j-api 1.7.7 :use-top
instaparse/instaparse 1.4.12
org.quartz-scheduler/quartz 2.3.2
  X com.mchange/c3p0 0.9.5.4 :superseded
    X com.mchange/mchange-commons-java 0.2.15 :parent-omitted
  X com.mchange/mchange-commons-java 0.2.15 :superseded
  . com.zaxxer/HikariCP-java7 2.4.13
    X org.slf4j/slf4j-api 1.7.21 :use-top
  X org.slf4j/slf4j-api 1.7.7 :use-top
clj-kondo/clj-kondo 2023.01.16
  X com.cognitect/transit-clj 1.0.324 :older-version
  . io.replikativ/datalog-parser 0.2.25
  X cheshire/cheshire 5.11.0 :use-top
  . nrepl/bencode 1.1.0
  . org.babashka/sci 0.5.35
    . borkdude/sci.impl.reflector 0.0.1
    . borkdude/edamame 1.0.0
    . org.babashka/sci.impl.types 0.0.2
  . babashka/fs 0.1.11
  X org.ow2.asm/asm 9.2 :superseded
org.apache.logging.log4j/log4j-1.2-api 2.19.0
  X org.apache.logging.log4j/log4j-api 2.19.0 :use-top
org.clojure/math.numeric-tower 0.0.5
clj-http-fake/clj-http-fake 1.0.3
  X org.clojure/math.combinatorics 0.1.3 :use-top
  . robert/hooke 1.3.0
  X clj-http/clj-http 3.1.0 :use-top
  X ring/ring-codec 1.0.1 :older-version
talltale/talltale 0.5.13
  . com.lucasbradstreet/cljs-uuid-utils 1.0.2
  . tongue/tongue 0.2.6
    . clojure-future-spec/clojure-future-spec 1.9.0
  X org.clojure/test.check 0.10.0-alpha4 :older-version
  X org.clojure/core.async 1.5.648 :use-top
hiccup/hiccup 1.0.5
pjstadig/humane-test-output 0.11.0
io.prometheus/simpleclient_hotspot 0.16.0
  . io.prometheus/simpleclient 0.16.0
io.github.resilience4j/resilience4j-retry 1.7.1
  . io.vavr/vavr 0.10.2
    . io.vavr/vavr-match 0.10.2
  . io.github.resilience4j/resilience4j-core 1.7.1
    . io.vavr/vavr 0.10.2
    X org.slf4j/slf4j-api 1.7.30 :use-top
  X org.slf4j/slf4j-api 1.7.30 :use-top
cloverage/cloverage 1.2.4
  X org.clojure/tools.reader 1.3.6 :use-top
  . org.clojure/tools.cli 0.4.2
  X org.clojure/tools.logging 0.5.0 :use-top
  X org.clojure/tools.namespace 1.3.0 :use-top
  X org.clojure/java.classpath 1.0.0 :use-top
  X org.clojure/data.xml 0.2.0-alpha6 :use-top
  . org.clojure/data.json 2.4.0
  X riddley/riddley 0.2.0 :use-top
  X slingshot/slingshot 0.12.2 :use-top
riddley/riddley 0.2.0
dk.ative/docjure 1.19.0
org.apache.poi/poi-ooxml 5.2.3
  X org.apache.poi/poi 5.2.3 :use-top
  . org.apache.poi/poi-ooxml-lite 5.2.3
    . org.apache.xmlbeans/xmlbeans 5.1.1
  . org.apache.xmlbeans/xmlbeans 5.1.1
    X org.apache.logging.log4j/log4j-api 2.18.0 :use-top
  X org.apache.commons/commons-compress 1.21 :use-top
  X commons-io/commons-io 2.11.0 :use-top
  . com.github.virtuald/curvesapi 1.07
  X org.apache.logging.log4j/log4j-api 2.18.0 :use-top
  . org.apache.commons/commons-collections4 4.4
org.clojure/java.classpath 1.0.0
org.apache.logging.log4j/log4j-jcl 2.19.0
  . commons-logging/commons-logging 1.2
  X org.apache.logging.log4j/log4j-api 2.19.0 :use-top
com.snowplowanalytics/snowplow-java-tracker 0.12.0
  X commons-codec/commons-codec 1.14 :use-top
  X commons-net/commons-net 3.6 :use-top
  X org.slf4j/slf4j-api 1.7.30 :use-top
  X com.google.guava/guava 31.0-jre :use-top
environ/environ 1.2.0
com.google.guava/guava 31.1-jre
  . com.google.guava/failureaccess 1.0.1
  . com.google.guava/listenablefuture 9999.0-empty-to-avoid-conflict-with-guava
  . com.google.code.findbugs/jsr305 3.0.2
  . org.checkerframework/checker-qual 3.12.0 :newer-version
  X com.google.errorprone/error_prone_annotations 2.11.0 :superseded
  . com.google.j2objc/j2objc-annotations 1.3
com.clearspring.analytics/stream 2.9.8
org.clojure/data.xml 0.0.8
clojure.java-time/clojure.java-time 1.1.0
io.github.camsaul/humane-are 1.0.2
  X net.cgrand/macrovich 0.2.1 :use-top
amalloy/ring-buffer 1.3.1
org.clojure/algo.generic 0.1.3
net.cgrand/macrovich 0.2.1
io.github.camsaul/toucan2 1.0.519
  . better-cond/better-cond 2.1.5
  X org.clojure/tools.logging 1.2.4 :use-top
  . mvxcvi/puget 1.3.4 :newer-version
    . mvxcvi/arrangement 2.1.0
    . fipp/fipp 0.6.26
  X org.clojure/tools.trace 0.7.11 :use-top
  X methodical/methodical 0.15.1 :use-top
  X com.github.seancorfield/honeysql 2.4.972 :use-top
  X environ/environ 1.2.0 :use-top
  . com.github.seancorfield/next.jdbc 1.3.847
    . org.clojure/java.data 1.0.95
      X org.clojure/tools.logging 1.2.1 :use-top
    X camel-snake-kebab/camel-snake-kebab 0.4.3 :use-top
  X potemkin/potemkin 0.4.6 :use-top
  X pretty/pretty 1.0.5 :use-top
  X camel-snake-kebab/camel-snake-kebab 0.4.3 :use-top
org.clojure/data.csv 1.0.1
metosin/malli 0.10.0
  . fipp/fipp 0.6.26
  X mvxcvi/arrangement 2.0.0 :older-version
  . borkdude/dynaload 0.3.5
  . borkdude/edamame 1.0.0
    X org.clojure/tools.reader 1.3.4 :use-top
  . org.clojure/test.check 1.1.1 :newer-version
org.clojure/java.jdbc 0.7.12
nano-id/nano-id 1.0.0
crypto-random/crypto-random 1.2.1
  X commons-codec/commons-codec 1.15 :use-top
kixi/stats 0.4.4
  X redux/redux 0.1.3 :use-top
  X org.clojure/test.check 0.9.0 :older-version
  X org.clojure/math.combinatorics 0.1.4 :use-top
  . com.tdunning/t-digest 3.2
net.thisptr/jackson-jq 1.0.0-preview.20220705
  . org.jruby.joni/joni 2.1.43
    . org.jruby.jcodings/jcodings 1.0.57
  X com.fasterxml.jackson.core/jackson-databind 2.13.3 :use-top
prismatic/schema 1.4.1
org.clojure/math.combinatorics 0.1.6
cheshire/cheshire 5.11.0
  X com.fasterxml.jackson.core/jackson-core 2.13.3 :older-version
  . com.fasterxml.jackson.dataformat/jackson-dataformat-smile 2.13.3
    X com.fasterxml.jackson.core/jackson-core 2.13.3 :older-version
  . com.fasterxml.jackson.dataformat/jackson-dataformat-cbor 2.13.3
    X com.fasterxml.jackson.core/jackson-core 2.13.3 :older-version
  . tigris/tigris 0.1.2
jonase/eastwood 1.3.0
  . org.clojars.brenton/google-diff-match-patch 0.1
  . org.ow2.asm/asm-all 5.2
org.apache.sshd/sshd-core 2.9.2
  . org.apache.sshd/sshd-common 2.9.2
    X org.slf4j/slf4j-api 1.7.32 :use-top
    . org.slf4j/jcl-over-slf4j 1.7.32
  X org.slf4j/slf4j-api 1.7.32 :use-top
  . org.slf4j/jcl-over-slf4j 1.7.32
    X org.slf4j/slf4j-api 1.7.32 :use-top
org.clojure/core.match 1.0.0
org.clojure/tools.reader 1.3.6
org.tcrawley/dynapath 1.1.0
org.mindrot/jbcrypt 0.4
stencil/stencil 0.5.0
  . scout/scout 0.1.0
  . quoin/quoin 0.1.2
  X org.clojure/core.cache 0.6.3 :superseded
    X org.clojure/data.priority-map 0.0.2 :parent-omitted
org.threeten/threeten-extra 1.7.2
clj-commons/iapetos 0.1.13
  X io.prometheus/simpleclient 0.12.0 :older-version
  . io.prometheus/simpleclient_common 0.12.0
    X io.prometheus/simpleclient 0.12.0 :older-version
  . io.prometheus/simpleclient_pushgateway 0.12.0
    X io.prometheus/simpleclient 0.12.0 :older-version
    . io.prometheus/simpleclient_common 0.12.0
    X javax.xml.bind/jaxb-api 2.3.0 :older-version
com.taoensso/nippy 3.2.0
  X org.clojure/tools.reader 1.3.6 :use-top
  . com.taoensso/encore 3.23.0
    X org.clojure/tools.reader 1.3.6 :use-top
    . com.taoensso/truss 1.6.0
  . org.iq80.snappy/snappy 0.4
  . org.tukaani/xz 1.9
  . org.lz4/lz4-java 1.8.0
potemkin/potemkin 0.4.6
  . clj-tuple/clj-tuple 0.2.2
info.sunng/ring-jetty9-adapter 0.18.5
  X ring/ring-core 1.9.6 :use-top
  X org.eclipse.jetty/jetty-server 11.0.14 :use-top
  . org.eclipse.jetty.websocket/websocket-jetty-api 11.0.14
  . org.eclipse.jetty.websocket/websocket-jetty-server 11.0.14
    . org.eclipse.jetty.websocket/websocket-jetty-api 11.0.14
    . org.eclipse.jetty.websocket/websocket-jetty-common 11.0.14
      . org.eclipse.jetty.websocket/websocket-jetty-api 11.0.14
      . org.eclipse.jetty.websocket/websocket-core-common 11.0.14
        . org.eclipse.jetty/jetty-io 11.0.14
        . org.eclipse.jetty/jetty-http 11.0.14 :newer-version
          . org.eclipse.jetty/jetty-util 11.0.14
          . org.eclipse.jetty/jetty-io 11.0.14
          X org.slf4j/slf4j-api 2.0.5 :use-top
        X org.slf4j/slf4j-api 2.0.5 :use-top
    . org.eclipse.jetty.websocket/websocket-servlet 11.0.14
    . org.eclipse.jetty.toolchain/jetty-jakarta-servlet-api 5.0.2
    . org.eclipse.jetty/jetty-servlet 11.0.14 :newer-version
      . org.eclipse.jetty/jetty-security 11.0.14
        X org.eclipse.jetty/jetty-server 11.0.14 :use-top
        X org.slf4j/slf4j-api 2.0.5 :use-top
      X org.slf4j/slf4j-api 2.0.5 :use-top
    . org.eclipse.jetty/jetty-annotations 11.0.14
      . org.eclipse.jetty/jetty-plus 11.0.14
        . jakarta.transaction/jakarta.transaction-api 2.0.0
        . org.eclipse.jetty/jetty-jndi 11.0.14
          . org.eclipse.jetty/jetty-util 11.0.14
          X org.slf4j/slf4j-api 2.0.5 :use-top
        . org.eclipse.jetty/jetty-webapp 11.0.14
        X org.slf4j/slf4j-api 2.0.5 :use-top
      . org.eclipse.jetty/jetty-webapp 11.0.14
        . org.eclipse.jetty/jetty-servlet 11.0.14
        . org.eclipse.jetty/jetty-xml 11.0.14
          . org.eclipse.jetty/jetty-util 11.0.14
          X org.slf4j/slf4j-api 2.0.5 :use-top
        X org.slf4j/slf4j-api 2.0.5 :use-top
      . jakarta.annotation/jakarta.annotation-api 2.1.1
      . org.ow2.asm/asm 9.4 :newer-version
      . org.ow2.asm/asm-commons 9.4
        . org.ow2.asm/asm 9.4
        . org.ow2.asm/asm-tree 9.4
          . org.ow2.asm/asm 9.4
      X org.slf4j/slf4j-api 2.0.5 :use-top
      . org.eclipse.jetty.toolchain/jetty-jakarta-servlet-api 5.0.2
    X org.slf4j/slf4j-api 2.0.5 :use-top
  . org.eclipse.jetty.websocket/websocket-servlet 11.0.14
    . org.eclipse.jetty.websocket/websocket-core-server 11.0.14
      . org.eclipse.jetty.websocket/websocket-core-common 11.0.14
      X org.eclipse.jetty/jetty-server 11.0.14 :use-top
    . org.eclipse.jetty/jetty-servlet 11.0.14
    X org.slf4j/slf4j-api 2.0.5 :use-top
  . org.eclipse.jetty.http2/http2-server 11.0.14
    . org.eclipse.jetty.http2/http2-common 11.0.14
      . org.eclipse.jetty.http2/http2-hpack 11.0.14
        . org.eclipse.jetty/jetty-util 11.0.14
        . org.eclipse.jetty/jetty-http 11.0.14
        . org.eclipse.jetty/jetty-io 11.0.14
        X org.slf4j/slf4j-api 2.0.5 :use-top
      X org.slf4j/slf4j-api 2.0.5 :use-top
    X org.eclipse.jetty/jetty-server 11.0.14 :use-top
    X org.slf4j/slf4j-api 2.0.5 :use-top
  . org.eclipse.jetty/jetty-alpn-server 11.0.14
    X org.eclipse.jetty/jetty-server 11.0.14 :use-top
    X org.slf4j/slf4j-api 2.0.5 :use-top
  . org.eclipse.jetty/jetty-alpn-java-server 11.0.14
    . org.eclipse.jetty/jetty-io 11.0.14 :newer-version
      X org.slf4j/slf4j-api 2.0.5 :use-top
      . org.eclipse.jetty/jetty-util 11.0.14 :newer-version
        X org.slf4j/slf4j-api 2.0.5 :use-top
    . org.eclipse.jetty/jetty-alpn-server 11.0.14
    X org.slf4j/slf4j-api 2.0.5 :use-top
reifyhealth/specmonstah 2.1.0
  X better-cond/better-cond 2.0.1-20170618.063731-4 :older-version
  . aysylu/loom 1.0.2
    X org.clojure/data.priority-map 0.0.5 :superseded
    . tailrecursion/cljs-priority-map 1.2.1
      X org.clojure/clojurescript 1.7.170 :excluded
  X medley/medley 0.8.3 :use-top
org.slf4j/slf4j-api 1.7.36
amalloy/ring-gzip-middleware 0.1.4
buddy/buddy-sign 3.4.333
  X buddy/buddy-core 1.10.413 :use-top
metabase/connection-pool 1.2.0
  . com.mchange/c3p0 0.9.5.5 :newer-version
    . com.mchange/mchange-commons-java 0.2.19 :newer-version
pretty/pretty 1.0.5
io.forward/yaml 1.0.11
org.apache.logging.log4j/log4j-api 2.19.0
org.clojure/core.memoize 1.0.257
  . org.clojure/core.cache 1.0.225 :newer-version
    . org.clojure/data.priority-map 1.1.0 :newer-version
camel-snake-kebab/camel-snake-kebab 0.4.3
net.i2p.crypto/eddsa 0.3.0
ring/ring-mock 0.4.0
  X cheshire/cheshire 5.8.1 :use-top
  X ring/ring-codec 1.1.1 :older-version
org.eclipse.jetty/jetty-server 11.0.13
  . org.eclipse.jetty.toolchain/jetty-jakarta-servlet-api 5.0.2
  X org.eclipse.jetty/jetty-http 11.0.13 :superseded
    X org.eclipse.jetty/jetty-util 11.0.13 :superseded
      X org.slf4j/slf4j-api 2.0.5 :use-top
    X org.eclipse.jetty/jetty-io 11.0.13 :older-version
    X org.slf4j/slf4j-api 2.0.5 :use-top
  X org.eclipse.jetty/jetty-io 11.0.13 :superseded
    X org.slf4j/slf4j-api 2.0.5 :use-top
    X org.eclipse.jetty/jetty-util 11.0.13 :parent-omitted
  X org.slf4j/slf4j-api 2.0.5 :use-top
ring/ring-core 1.9.6
  . ring/ring-codec 1.2.0
  X commons-io/commons-io 2.11.0 :use-top
  . commons-fileupload/commons-fileupload 1.4
    X commons-io/commons-io 2.2 :use-top
  X crypto-random/crypto-random 1.2.1 :use-top
  . crypto-equality/crypto-equality 1.0.1
commons-net/commons-net 3.9.0
medley/medley 1.4.0
org.clojure/core.async 1.6.673
  . org.clojure/tools.analyzer.jvm 1.2.2
    . org.clojure/tools.analyzer 1.1.0
    X org.clojure/core.memoize 1.0.253 :use-top
    . org.ow2.asm/asm 9.2
    X org.clojure/tools.reader 1.3.6 :excluded
org.mariadb.jdbc/mariadb-java-client 2.7.6
```
</details>

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28757)

### CODE REVIEW

File: test/metabase/api/geojson_test.clj [hunk 1]
```diff
@@ -140,7 +143,23 @@
...
+    (testing "error is returned if URL server never responds (#28752)"
+      (let [never-responder    (fn silent-async-handler [_request _respond _raise])
+            server             (ring-jetty/run-jetty never-responder
+                                                     {:join?         false
+                                                      :async?        true
+                                                      :port          0
+                                                      :async-timeout 60000})
+            port               (.. server getURI getPort)
+            never-responds-url (str "http://localhost:" port)]
+        (try
```
Comment (qnkhuat) [inline test/metabase/api/geojson_test.clj:157]: could we have a comment on why a standalone server is needed here?

**Review by qnkhuat — APPROVED** [review]

File: test/metabase/api/geojson_test.clj [hunk 2]
```diff
@@ -140,7 +143,27 @@
...
+      ;; test flakes after 45 seconds with `mt/user-http-request` times out. And presumably other clients have similar
+      ;; issues. This ensures we give a good error message in this case.
+      (let [never-responder    (fn silent-async-handler [_request _respond _raise])
+            server             (ring-jetty/run-jetty never-responder
+                                                     {:join?         false
+                                                      :async?        true
+                                                      :port          0
+                                                      :async-timeout 60000})
+            port               (.. server getURI getPort)
+            never-responds-url (str "http://localhost:" port)]
```
Comment (camsaul) [inline test/metabase/api/geojson_test.clj:160]: I hate to be that guy but if `.getURI` or the other stuff somehow fails then the server is going to leak

It would be super duper nice to not do anything before the `try` just to be super safe.

It looks pretty safe here, but I'm more worried that people will see this code as an example and copy the pattern in the future and do something not so safe. Better if people see that you have the `try-catch` right away. 

Or if you want to be really l33t maybe you could just reify `java.io.Closeable` and have `(close) call `.stop` and then you could use `with-open`. Idk

**Review by camsaul — APPROVED** [review]

**Review by metamben — APPROVED** [review]

File: test/metabase/api/geojson_test.clj (hunk 2 above)
Comment (dpsutton) [reply test/metabase/api/geojson_test.clj]: done. good call.

File: test/metabase/api/geojson_test.clj (hunk 1 above)
Comment (dpsutton) [reply test/metabase/api/geojson_test.clj]: added. good call
