### PR TITLE
Fix revision history for old cards

### LINKED ISSUE #61555: Revision history broken
### Describe the bug

After upgrading from v0.49.4 to v0.55.8, our revision history broke.

For cards created after the upgrade everything is working normally.

For cards created before the upgrade, we can no longer see the history of a card or revert to previous versions via UI. This is what we see:

Image
 
We also noticed that after saving these pre-upgrade cards, although the text change is saved, the "Edited X time ago by Y" does not change and in Metabase's database `revision` table, no new revision is stored for the edited card.
The logs do not show any errors when saving the question, only when trying to see the revision history.

This is also likely creating other issues, specifically with downloading query results, where we have seen strange behaviours like columns added after an edit being missing in downloads.

### To Reproduce

1. Spin up Metabase v0.49.4
2. Create a question
3. Upgrade to v0.55.8
4. Check the question revision history

### Expected behavior

I expect to be able to see the revision history of cards.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "sqlserver"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-07-18",
      "tag": "v0.55.8.5",
      "hash": "5551776"
    },
    "settings": {
      "report-timezone": "UTC"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.5"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "6.1.141",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Severe if we are losing revision history

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by galdre**
Closes https://github.com/metabase/metabase/issues/61555

Previously related:
- [Slack](https://metaboat.slack.com/archives/C05NXACAG1G/p1743544469979949)
- https://github.com/metabase/metabase/issues/56121
- https://github.com/metabase/metabase/pull/56394

### Description

Cards created before v0.55 lack the `:card_schema` field in their revision history. When loading these old revisions, the system throws "Cannot SELECT a Card without including :card_schema" because the Card model's `after-select` expects this field to always be present.

Existing code adds the legacy default `card_schema` value (20) in `revert-to-revision!`. This PR adds the value (20) to old revisions in `revision.clj`'s `after-select`.

This allows users to view revision history and revert cards that were created before the v0.55 upgrade.

### How to verify

1. Start with Metabase v0.46.6.4, create and edit a card
2. Upgrade to v0.49.11, edit the card (revision history still works)
3. Upgrade to v0.55.8, try and fail to view revision history
4. Upgrade to this branch, succeed in viewing revision history

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/revisions/impl/card.clj [hunk 1]
```diff
@@ -2,6 +2,11 @@
   (:require
    [metabase.revisions.models.revision :as revision]))
 
+(def legacy-card-schema-version
+  "The default schema version assigned to all cards that existed before the `:card_schema` column was added in v0.55.
+  This value is used when loading old revision records that predate the schema versioning system."
+  20)
```
Comment (bshepherdson) [inline src/metabase/revisions/impl/card.clj]: Let's move this to `metabase.queries.models.card` [here-ish](https://github.com/metabase/metabase/blob/master/src/metabase/queries/models/card.clj#L63) and call it `starting-card-schema-version` or similar. May as well put it in a central place.

File: src/metabase/revisions/models/revision.clj [hunk 2]
```diff
@@ -12,6 +12,12 @@
    [toucan2.core :as t2]
    [toucan2.model :as t2.model]))
 
+;; This constant is also defined in metabase.revisions.impl.card but we duplicate it here
+;; to avoid circular dependencies. Keep both definitions in sync!
+(def legacy-card-schema-version
```
Comment (bshepherdson) [inline src/metabase/revisions/models/revision.clj]: Then we can remove this one, too.

**Review by bshepherdson — APPROVED** [review]

File: src/metabase/revisions/impl/card.clj (hunk 1 above)
Comment (galdre) [reply src/metabase/revisions/impl/card.clj]: I had already tried that but the linter + our Notion module guide scared me away.
