### PR TITLE
Make LDAP attribute discovery case-insensitive

### LINKED ISSUE #11411: LDAP attribute discovery should be case-insensitive
**Describe the bug**
Currently the Metabase backend checks whether the LDAP attributes for first name, last name and email exist in the LDAP record and have a non-empty value. Unfortunately the discovery of LDAP attributes is currently case-sensitive while LDAP attribute names should be treated as case-insensitive.

This is causing a problem with the LDAP directory at my current employer which happens to have a mix of LDAP entries where some use `givenName` and some `givenname` for the first name attribute. The consequence is that depending on which version I configure in the Metabase admin screen some users can login and some can not.

**To Reproduce**
1. Configure an LDAP integration in Metabase
2. Try to login using a user with an LDAP record using `givenName` LDAP attribute name -> Login will be successful
3. Try to login using a user with an LDAP record using `givenname` instead of `givenName` as the LDAP attribute name -> Login will fail

**Expected behavior**
The attribute lookup should be case-insensitive to support a mixture of LDAP attribute name spellings.

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_191",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.191-b12",
    "os.name": "Linux",
    "os.version": "4.4.0-138-generic",
    "user.language": "en",
    "user.timezone": "Europe/Zurich"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.6",
      "date": "2019-11-19",
      "branch": "release-0.33.x",
      "hash": "be1e0e1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Some of our users can't log into Metabase while some can.

### PR DESCRIPTION
**Pull request by nielspardon**
Fixes #11411 

- transforms all the keys of the retrieved LDAP record to lower case
- fetch the values from the LDAP record using the lower cased attribute names

### CODE REVIEW

File: src/metabase/integrations/ldap.clj [hunk 1]
```diff
@@ -183,10 +183,10 @@
    (with-connection find-user username))
 
   ([conn username]
-   (when-let [{:keys [dn], :as result} (search conn username)]
-     (let [{fname (keyword (ldap-attribute-firstname))
-            lname (keyword (ldap-attribute-lastname))
-            email (keyword (ldap-attribute-email))}    result]
+   (when-let [{:keys [dn], :as result} (into (empty {}) (for [[key value] (search conn username)] [(keyword (.toLowerCase (name key))) value]))]
```
Comment (walterl) [inline src/metabase/integrations/ldap.clj]: I think we can do without the call to `empty` in this case, since you're using an empty map literal `{}` already. Or am I missing something?

**Review by walterl — CHANGES_REQUESTED** [review]
Thank you for your contribution, @nielspardon!

I'm still only 95% sure that case insensitive matching should be done, but [this SO thread](https://stackoverflow.com/questions/29897684/is-ldap-dn-case-insensitive) seems to suggest that most major implementations as well as the LDAP RFC points in that direction.

Besides the few small issues I pointed out in the comments, this looks good! :+1:

File: src/metabase/integrations/ldap.clj (hunk 1 above)
[the remark this answers is not in the document]
Comment (nielspardon) [reply src/metabase/integrations/ldap.clj]: No, I wouldn't mind. Will change it to `metabase.util/lower-case-en`.

[the remark this answers is not in the document]
Comment (nielspardon) [reply src/metabase/integrations/ldap.clj]: I will create a separate function for lower casing the attribute names.

File: src/metabase/integrations/ldap.clj [hunk 2]
```diff
@@ -183,10 +183,10 @@
...
+     (let [{fname (keyword (.toLowerCase ^String (setting/get :ldap-attribute-firstname)))
```
[the remark this answers is not in the document]
Comment (nielspardon) [reply src/metabase/integrations/ldap.clj]: I'm completely new to Clojure and I was trying a bunch of different things. This was the only way I could get it to work. I also wasn't fully satisfied with it since it felt like a hack and not as elegant as the previous code. 
There might be a much nicer solution to that which I just don't know of due to my lack of Clojure experience. I'm happy to receive and suggestions on how to improve this part. 
By also using the lower-case-en function here it already will look a bit better.

File: src/metabase/integrations/ldap.clj (hunk 1 above)
Comment (nielspardon) [reply src/metabase/integrations/ldap.clj]: Makes sense to me. Will change that.

**Comment by nielspardon** [comment]
I also did a bit of digging regarding the case sensitivity of LDAP attribute names and actually found that the Java library that is ultimately being used here actually lowercases the attribute names if you would choose their API for accessing LDAP attributes: https://github.com/pingidentity/ldapsdk/blob/master/src/com/unboundid/ldap/sdk/Entry.java#L848

However the `clj-ldap` wrapper over the Java SDK you guys are using chose to go down a rather low level / incomplete path of mapping the Java library into Clojure.

**Comment by walterl** [comment]
> I also did a bit of digging regarding the case sensitivity of LDAP attribute names and actually found that the Java library that is ultimately being used here actually lowercases the attribute names if you would choose their API for accessing LDAP attributes:

Great find!

File: src/metabase/integrations/ldap.clj (hunk 2 above)
[the remark this answers is not in the document]
Comment (walterl) [reply src/metabase/integrations/ldap.clj]: Your "new Clojure" doesn't look bad at all. :slightly_smiling_face: 

You could simply wrap the setting function call in `lower-case-en`:

```clojure
(u/lower-case-en (ldap-attribute-firstname))
```

_However_, I just realized that there's an even better way, higher up the chain, where we can do the conversion: as setting getter functions!

```clojure
(defsetting ldap-attribute-firstname
  (deferred-tru "Attribute to use for the user''s first name. (usually ''givenName'')")
  :default "givenName"
  :getter (fn []
            (u/lower-case-en (setting/get-string :ldap-attribute-firstname))))
```

With that you can go back to using just the setting function like before, and you'll get a lower cased string back:

```clojure
(let [fname (keyword (ldap-attribute-firstname)) ...
```

File: src/metabase/integrations/ldap.clj [hunk 3]
```diff
@@ -177,16 +177,21 @@
      :filter     (str/replace (ldap-user-filter) filter-placeholder (Filter/encodeValue username))
      :size-limit 1})))
 
+(defn- lower-case-attribute-names
+  "Changes the attribute names of the given LDAP record to lower case."
+  [record]
+  (into {} (for [[key value] record] [(keyword (u/lower-case-en (name key))) value])))
```
Comment (walterl) [inline src/metabase/integrations/ldap.clj]: Just some minor tweaks to improve readability:

```clojure
(defn- lower-case-attribute-names
  "Changes the attribute names of the given LDAP record to lower case."
  [record]
  (into {} (for [[k v] record]
             [(-> k name u/lower-case-en keyword) v])))
```

1. Adding a newline after the `for`'s bindings is expected, and makes it a lot easier read.
2. The treading macro `->` can save you a few parentheses. It turns `(h (g (f x)))` into `(-> x f g h)`.
3. Using `k` and `v` instead of `key` and `value` avoids shadowing the built-in `key` function. Such variable names are understood as [idiomatic](https://guide.clojure.style/#idiomatic-names) in Clojure.

File: src/metabase/integrations/ldap.clj [hunk 4]
```diff
@@ -177,16 +177,21 @@
      :filter     (str/replace (ldap-user-filter) filter-placeholder (Filter/encodeValue username))
      :size-limit 1})))
 
+(defn- lower-case-attribute-names
```
Comment (walterl) [inline src/metabase/integrations/ldap.clj]: I've noticed that what this function does is actually much more general than what's applicable to LDAP attributes: it lower cases a map's keys. As such, it's probably better to move it to the `metabase.util` namespace, and rename it to suit it's more general purpose. I suggest `lower-map-keys`, similar to `metabase.util/recursive-map-keys`.

Please note that the idiomatic name for a general map, is `m`. So please rename `record` to `m` while you're at it.

Remember to update the doc string. :slightly_smiling_face:

**Review by walterl — CHANGES_REQUESTED** [review]
Functionality looks great. Just some styling and moving.

File: src/metabase/integrations/ldap.clj (hunk 2 above)
[the remark this answers is not in the document]
Comment (nielspardon) [reply src/metabase/integrations/ldap.clj]: Done.

File: src/metabase/integrations/ldap.clj (hunk 3 above)
Comment (nielspardon) [reply src/metabase/integrations/ldap.clj]: I think I applied all of the above.

File: src/metabase/integrations/ldap.clj (hunk 4 above)
Comment (nielspardon) [reply src/metabase/integrations/ldap.clj]: This should also be done.

**Review by walterl — APPROVED** [review]
Great stuff!

**Comment by walterl** [comment]
@nielspardon Thanks for indulging all my nit picks :slightly_smiling_face:

**Comment by nielspardon** [comment]
One more question if you don't mind. Should I also create a PR for the `release-0.33.x` branch? I suppose the 0.34 release is not going to happen before the next 0.33.x release. Also this is fixing a bug in the current version and not necessarily a new feature.

**Comment by walterl** [comment]
I don't think that would be necessary; we merge `master` into the release branch before cutting a new release.

AFAIK we're planning on getting 0.34 out the door in this month, but don't quote me on that :wink:.
