### PR TITLE
Fix questions with joins or filters cause re-run overlay after first save

### LINKED ISSUE #13468: Questions with joins causes re-run overlay after first save
**Describe the bug**
When creating a question with joins, then after clicking Save, the re-run overlay (Play-button) will be shown.

**To Reproduce**
1. Custom question > Sample Dataset > Orders join People and click Visualize
image
2. Save question, anywhere, and click "Not now", when asked if the question should be added to a dashboard
3. Now the re-run overlay is shown, and will run the query again if the Play-button is clicked
image

**Expected behavior**
After clicking Save on a question, it's expected to continue to show that state and not requiring re-run of the query again.

**Information about your Metabase Installation:**
Metabase 0.35.4, 0.36.7, 0.37.0-rc2

**Additional context**

### PR DESCRIPTION
**Pull request by kulyk**
Fixes #13468

Once you save a GUI question with joins or filters, a re-run overlay is shown. The re-run overlay is intended to show the query is changed and the displayed results are no longer relevant. Here it's not the case as the query doesn't change when the question is saved.

### About the fix

The overlay is displayed depending on the `isResultDirty` calculated by [this selector](https://github.com/metabase/metabase/blob/25179f743eb5249db2ed5fb3e874c64bf6d35eed/frontend/src/metabase/query_builder/selectors.js#L189). The selector compares previous and current states of a dataset query and parameters and if they're different, the `isDirty` flag is set to `true`.

When you're building a question with GUI editors, some clauses are stored as our query classes (like [Join](https://github.com/metabase/metabase/blob/master/frontend/src/metabase-lib/lib/queries/structured/Join.js) or [Filter](https://github.com/metabase/metabase/blob/master/frontend/src/metabase-lib/lib/queries/structured/Filter.js)). And other clauses are represented as plain JavaScript arrays (aggregations, breakouts, order-by clauses, etc.). So if you explore the dataset query state while building a GUI question, it would look like the following:

CleanShot 2021-09-20 at 15 03 13@2x

Once a question is saved, the "current" dataset query state is replaced with a dataset_query JSON from the server's POST response. The problem happens when the selector compares the previous and the current state. Joins' and filters' before and current states are de-facto equal, but the `isDirty` is still `true` because there're `Join` and `Filter` instances in the "previous" state and plain arrays in the "current" state.

Fixed by extending the `normalizeQuery` function, so it converts `Join` and `Filter` to JS arrays and objects for comparison.

### To Verify

1. Ask a question > Custom question > Sample Dataset > Orders
2. Join People OR add any filter
3. Click "Visualize"
3. Save the question anywhere, and click "Not now", when asked if the question should be added to a dashboard
4. You should just see the results table without the re-run overlay

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/134000825-f569ebd9-df66-462a-8f77-226bb1d03319.mov

**After**

https://user-images.githubusercontent.com/17258145/134001013-f2738981-26a3-4eca-8e15-03734ccc2306.mov

### CODE REVIEW

File: frontend/src/metabase-lib/lib/queries/structured/MBQLClause.js [hunk 1]
```diff
@@ -115,6 +115,14 @@ export class MBQLObjectClause {
   metadata() {
     return this._query.metadata();
   }
+
+  raw() {
```
Comment (gusaiani) [inline frontend/src/metabase-lib/lib/queries/structured/MBQLClause.js:119]: Nit: from the name of this function, at least for me it's not easy to understand what it accomplishes.

Does it make the entries raw?

Does it filter by only the raw entries?

File: frontend/src/metabase-lib/lib/queries/structured/MBQLClause.js [hunk 2]
```diff
@@ -115,6 +115,14 @@ export class MBQLObjectClause {
...
+    const entries = Object.entries(this).filter(entry => {
```
Comment (gusaiani) [inline frontend/src/metabase-lib/lib/queries/structured/MBQLClause.js:120]: Might be helpful to call this const something more specific, especially as we use `.entries` and later `.fromEntries`.

Just a silly idea: `entriesWithDefinedValue`?

File: frontend/src/metabase/query_builder/selectors.js [hunk 3]
```diff
@@ -162,23 +162,38 @@ const getNextRunParameterValues = createSelector(
...
-      fields = fields
-        ? // if the query has fields, copy them before sorting
-          [...fields]
-        : // if the fields aren't set, we get them from the table metadata
-          tableMetadata.fields.map(({ id }) => ["field", id, null]);
-      return fields.sort((a, b) =>
-        JSON.stringify(b).localeCompare(JSON.stringify(a)),
-      );
-    });
+  if (query.query) {
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/selectors.js:175]: This might be an opportunity to break this function down and reduce its cyclomatic complexity.

**Review by gusaiani — APPROVED** [review]
Looking good to me, just a few inlined comments.

**Review by flamber — COMMENTED** [review]
Seems to work great. Just tried a couple of related issues (like 13455) to see if it had helped or changed anything there, but no change.

File: frontend/src/metabase-lib/lib/queries/structured/MBQLClause.js (hunk 1 above)
Comment (kulyk) [reply frontend/src/metabase-lib/lib/queries/structured/MBQLClause.js:119]: There is a method doing the same thing above in `MBQLArrayClause` class and is called `raw` too, so I tried to keep things consistent. I agree the naming could be better, but I'd like to avoid as many refactorings as possible for bug fixes before 41 is rolled out

File: frontend/src/metabase-lib/lib/queries/structured/MBQLClause.js (hunk 2 above)
Comment (kulyk) [reply frontend/src/metabase-lib/lib/queries/structured/MBQLClause.js:120]: SGTM, thanks 🤝

File: frontend/src/metabase/query_builder/selectors.js (hunk 3 above)
Comment (kulyk) [reply frontend/src/metabase/query_builder/selectors.js:175]: 100%, I'd be happy to open a followup PR after 41 is released to drop some risks
