### PR TITLE
Fix SDK v56 can't drills dashboard with entity IDs

### LINKED ISSUE #64884: [SDK] Embedded InteractiveDashboard with entityId doesn't drill down
### Describe the bug

Drill-down doesn't work when you use entityId to embed a dashboard

### To Reproduce

1. Go to the E-Commerce Insights dashboard from Examples
2. Go to the info icon and copy its entityId
3. Embed with SDK using the entityId as dashboardId:
```jsx
    <MetabaseProvider authConfig={authConfig}>
      <InteractiveDashboard dashboardId={'xBLdW9FsgRuB2HGhWiBa_'}></InteractiveDashboard>
    </MetabaseProvider>
```

4. Try to drill down on something, nothing happens - no network errors or console messages

If you use the plain ID it works normally

### Expected behavior

Drill-down should work normally

### Logs

_No response_

### Information about your Metabase installation

```JSON
Metabase v56.9.1
"@metabase/embedding-sdk-react": "^0.56.3",
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
closes #64884
Closes EMB-910

> [!note]
> This PR targets 56 directly as [this bug doesn't seem to occur on 57.](https://github.com/metabase/metabase/issues/64884#issuecomment-3459911063)

### Description

Fix can't drill dashboards with entity IDs.

The fix is cherry-picked from https://github.com/metabase/metabase/pull/62953, with some conflicts (see inline comments).

Also, the back button not showing when using entity ID is believed to be fixed in https://github.com/metabase/metabase/pull/62519 (and maybe other dependent PRs) which isn't backported to 56. So I made a fix in the dashboard selector instead.

### How to verify
1. Go to the E-Commerce Insights dashboard from Examples
2. Go to the info icon and copy its entityId
3. Embed with SDK using the entityId as dashboardId:
```jsx
    <MetabaseProvider authConfig={authConfig}>
      <InteractiveDashboard dashboardId={'xBLdW9FsgRuB2HGhWiBa_'}></InteractiveDashboard>
    </MetabaseProvider>
```
4. Drills should work, and you should be able to go back to the dashboard

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/use-common-dashboard-params.tsx
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/use-common-dashboard-params.tsx:87]: These lines look different in the original PR.

https://github.com/metabase/metabase/pull/62953/files#diff-545b6ea3c4486029739c2be2c6f061dc6889a4f87b5ceafb260960049f8b4570R95-R101

Since there's no reference to `dashboards` here, I kept the change as is.

File: frontend/src/metabase/dashboard/selectors.ts [hunk 1]
```diff
@@ -183,9 +183,23 @@ export function getDashCardBeforeEditing(state: State, dashcardId: DashCardId) {
...
+  state: State,
+  dashboardId: DashboardId,
+): StoreDashboard => {
   const dashboards = getDashboards(state);
-  return dashboards[dashboardId];
+
+  const isEntityId = typeof dashboardId === "string";
+  if (isEntityId) {
+    return isNotNull(
+      Object.values(dashboards).find(
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/selectors.ts]: Use a similar code we used in `findDashboardById` function in `enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/use-common-dashboard-params.tsx`

Without this fix, the back button wouldn't show up when drilling.

Image

**Comment by WiNloSt** [comment]
@heypoom tagging you as you're the original PR author that I cherry-picked from.

File: frontend/src/metabase/dashboard/selectors.ts [hunk 2]
```diff
@@ -183,9 +183,23 @@ export function getDashCardBeforeEditing(state: State, dashcardId: DashCardId) {
...
+export const getDashboardById = (
+  state: State,
+  dashboardId: DashboardId,
+): StoreDashboard => {
   const dashboards = getDashboards(state);
-  return dashboards[dashboardId];
+
+  const isEntityId = typeof dashboardId === "string";
+  if (isEntityId) {
+    return checkNotNull(
```
Comment (heypoom) [inline frontend/src/metabase/dashboard/selectors.ts]: `checkNotNull` will throw a `TypeError` here if the `Object.values(dashboards).find` returns null. I wonder if this has a possibility of happening and if our code will handle the TypeError if it does.

**Review by heypoom — APPROVED** [review]
`getDashboardById` lookup changes looks correct to me 🙏🏻

File: frontend/src/metabase/dashboard/selectors.ts (hunk 2 above)
Comment (WiNloSt) [reply frontend/src/metabase/dashboard/selectors.ts]: Well, yeah, I believe we don't expect at this point to find that there's no dashboard. I checked the prior function signature, it says to always return a dashboard, so I can only assume with entity ID, I should be able to find the dashboard at this point too. But let's see if any tests are complaining about it (I see a bunch failing right now 😓, not sure if they're related)

Comment (WiNloSt) [reply frontend/src/metabase/dashboard/selectors.ts]: It seems this actually causes all the failure haha. I remove that and leave the signature as `StoreDashboard | undefined`. I assume the previous signature `StoreDashboard` was wrong.

File: frontend/src/metabase/dashboard/selectors.ts [hunk 3]
```diff
@@ -185,7 +186,16 @@ export const getLoadingDashCards = (state: State) =>
 
 export const getDashboardById = (state: State, dashboardId: DashboardId) => {
   const dashboards = getDashboards(state);
-  return dashboards[dashboardId];
+
+  const isEntityId = isBaseEntityID(dashboardId);
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/selectors.ts:190]: can't just simply check if `typeof dashboardId === 'string'` because the id could be in JWT form (static embed)

File: frontend/src/metabase/dashboard/actions/cards.unit.spec.ts [hunk 4]
```diff
@@ -362,7 +362,7 @@ async function runAddCardToDashboard({
   const nextState = store.getState();
 
   const tempDashCardId =
-    getDashboardById(nextState, dashId).dashcards.find(
+    getDashboardById(nextState, dashId)!.dashcards.find(
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/actions/cards.unit.spec.ts:365]: forcing non-undefined since the selector signature has changed (it was incorrect before)
