### PR TITLE
fix(sdk): fix visual artifacts in binning options

### LINKED ISSUE #53880: [SDK] Fix visual artifacts in binning options
The binning options has some jarring visual artifacts. For reference, here is the binning options on the main app. They only show up once they are active or hovered.

However, the grey border is always there in the SDK themes. In addition, the text is also visible.

In the dark mode, it shows every binning option at once which looks ugly.

### To reproduce

- Render an InteractiveQuestion with default layout
- Click on Grouping
- The grey border on the left of the binning option should not be visible if it's inactive
- The binning option text should not be visible if it's inactive

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/53880

### Description

There are a couple of visual artifacts in binning options in the SDK, both in light and dark mode. See https://github.com/metabase/metabase/issues/53880 for the screenshots.

### How to verify

- Go to InteractiveQuestion > Group
- Breakout columns should not have any visual artifacts (see the ProficiencyLabs screenshot below)
- Hover on a column in the breakout
- Binning options should now be visible
- It should also be legible in dark mode (see the theStitch screenshot below)

### Demo

Tested on the master branch, so there will be some Mantine artifacts on this branch.

On the main app - behavior is same as before

CleanShot 2568-02-19 at 17 42 04@2x

ProficiencyLabs theme

CleanShot 2568-02-19 at 17 23 06@2x

theStitch theme

CleanShot 2568-02-19 at 17 21 40@2x

Pug theme

CleanShot 2568-02-19 at 17 24 12@2x

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/test/storybook-themes.ts [hunk 1]
```diff
@@ -249,8 +249,8 @@ const proficiencyTheme: MetabaseTheme = {
     filter: proficiencyColors.primary,
     "text-primary": proficiencyColors.lightGrey,
     "text-secondary": proficiencyColors.lightGrey,
-    "text-tertiary": "rgba(0, 0, 0, 0.4)",
-    border: "rgba(0, 0, 0, 0.12)",
+    "text-tertiary": "#979898",
+    border: "#DEDFDF",
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/test/storybook-themes.ts:253]: Use non-alpha values for now. We should update the docs to reflect that this should be a `#RRGGBB` value for best results.

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.styled.tsx [hunk 2]
```diff
@@ -19,9 +19,13 @@ export const ChevronDown = styled(Icon)`
...
 export const TriggerButton = styled(Button)<ButtonProps>`
-  color: ${() => alpha(color("text-white"), 0.5)};
   border-radius: 0;
-  border-left: 2px solid ${() => alpha(color("border"), 0.1)};
+
+  /** we hide the trigger button by default, and show it on hover */
+  visibility: hidden;
+  color: color-mix(in srgb, var(--mb-color-text-white), transparent 40%);
+  border-left: 2px solid
+    color-mix(in srgb, var(--mb-color-border), transparent 80%);
```
Comment (heypoom) [inline frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.styled.tsx:28]: We could probably use `lighten` instead of `alpha` to better support dark-mode theming, but I'll keep using `alpha` for now to maintain parity with main app. I modified the percentage slightly (e.g. `90% to 80%`) to make it a bit more legible in dark mode.

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx [hunk 3]
```diff
@@ -43,6 +43,7 @@ export interface BaseBucketPickerPopoverProps {
   className?: string;
   classNames?: {
     root?: string;
+    triggerButton?: string;
```
Comment (heypoom) [inline frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx:46]: `root` seems to also cover the outer container (maybe duplicate class names being passed?), so I added a separate `triggerButton` class name which works quite well

**Review by npretto — COMMENTED** [review]
was the "issue" caused by core app using the same color for the border/text and the background when not hovered -> not visible, but that wasn't the case in the sdk with custom themes?

**Comment by heypoom** [comment]
@npretto yep, we were using white colors in the core app to disguise the binning options, but that does not work in custom themes. This PR instead hides it properly with CSS visibility so it works with any themes.

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.module.css
Comment (WiNloSt) [inline frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.module.css:1]: what is this file? It should be removed.

**Review by WiNloSt — DISMISSED** [review]

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx [hunk 4]
```diff
@@ -215,6 +215,15 @@ export function getBucketListItem(
   };
 }
 
+const TriggerButton = forwardRef(function TriggerButton(
```
Comment (WiNloSt) [inline frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx:218]: This component is needed because we assigned it on line 220 in the previous version to `BaseBucketPickerPopover`, and to not keep adding to styled component (emotion).

Also the ref is needed because this component is used as a popover target.

File: e2e/test/scenarios/binning/binning-reproductions.cy.spec.js [hunk 5]
```diff
@@ -110,6 +110,7 @@ describe("binning related reproductions", () => {
     H.popover()
       .findByRole("option", { name: "CREATED_AT" })
       .findByLabelText("Temporal bucket")
+      .realHover()
```
Comment (WiNloSt) [inline e2e/test/scenarios/binning/binning-reproductions.cy.spec.js:113]: since the fix is to properly hide the element until hover, we need to hover on the element before it's visible. Otherwise, Cypress couldn't click it.

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.styled.tsx [hunk 6]
```diff
@@ -18,12 +18,6 @@ export const ChevronDown = styled(Icon)`
   opacity: 0.75;
 `;
 
-export const TriggerButton = styled(Button)<ButtonProps>`
```
Comment (WiNloSt) [inline frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.styled.tsx:21]: Moved to CSS module instead.

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.module.css [hunk 7]
```diff
@@ -0,0 +1,12 @@
+.triggerButton {
```
Comment (WiNloSt) [inline frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.module.css:1]: This is the exact same as @heypoom 's version, but in CSS module

https://github.com/metabase/metabase/blob/9a05331b469d5324ee5614eda616478ab551d2b0/frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.styled.tsx#L21-L29

File: frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.module.css [hunk 8]
```diff
@@ -0,0 +1,12 @@
...
+  border-radius: 0;
+  /** we hide the trigger button by default, and show it on hover */
+  visibility: hidden;
+  color: color-mix(in srgb, var(--mb-color-text-white), transparent 40%);
+  border-left: 2px solid
+    color-mix(in srgb, var(--mb-color-border), transparent 80%);
+}
+
+*:hover > .triggerButton {
```
Comment (WiNloSt) [inline frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.module.css:10]: But I add a logic that shows the bucket button on hover here in the same file, so we don't need to add this logic to every call site.

**Review by npretto — APPROVED** [review]
