### PR TITLE
MBQL 5 over the wire

### LINKED ISSUE #51614: Expressions Out of Order
### Describe the bug

Description: custom column(expressions) disorder, when total columns reaching 9

### To Reproduce
1. Create New Question, From Sample Database / Accounts
2.  add custom column from c0 to c9
(like case([ID] = "1", "2")), After adding c8, out-of-order issues occur.

Image
Sorting becomes disordered after adding a new column, total columns reaching 9
Image

### Expected behavior

The expected behavior is that the displayed order should match the order in which the columns were added.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Environment:
OS: [e.g.,Ubuntu]
Version: [e.g., v0.52.3]
```

### Severity

annoying

### Additional context

Other relevant environment details: 
After reviewing the source code, I discovered that the issue is caused by using into {} to assemble :expression. The resulting HashMap is unordered, which leads to the problem. Do you have any suggestions for improving this? Also, if possible, could I be assigned to fix this issue?

### PR DESCRIPTION
**Pull request by camsaul**
This PR has a lot of whitespace changes so I suggest reviewing with the ignore whitespace option.

Move 95% of the remaining backend code doing raw MBQL manipulation to Lib. Still a few more things to finish in follow-on PRs.

MBQL 5 is now persisted in the app DB. MBQL 4 is still accepted over the wire as input but API endpoints return MBQL 5.

TODO 

- [ ] Finish porting X-Rays (follow-on PR)
- [x] Add DB migration to copy `dataset_query` to another column to facilitate DB downgrades
- [x] Delete SerDes v1
- [ ] Teach SerDes v2 about MBQL 5 (follow-on PR)
- [x] Add request middleware to initialize metadata provider caches?
- [x] Add `queryToJs()` and `jstoQuery()`
- [x] Add option to API endpoint to fetch legacy version of query
- [ ] Update `metabase.segments.models.segment` / `:model/Segment` to use MBQL 5 (follow-on PR)

### CODE REVIEW

File: src/metabase/parameters/params.clj [hunk 1]
```diff
@@ -159,19 +162,6 @@
     (->> param-id->field-ids
          (m/map-vals #(into [] (keep field-id->field) %)))))
 
-(defmulti ^:private ^{:hydrate :param_fields} param-fields
```
Comment (camsaul) [inline src/metabase/parameters/params.clj:162]: ### FIXED N+1 Hydration

Reworked this to do use Methodical multimethods directly and to do batched hydration for dashboards. It's recursively hydrating the dashcards and cards for dashboards which means the old code did N+1 hydration if those weren't already hydrated.

File: enterprise/backend/src/metabase_enterprise/dependencies/native_validation.clj [hunk 2]
```diff
@@ -2,37 +2,54 @@
...
-       :query))
+(mu/defn- compile-query :- ::lib.schema/native-only-query
+  [query :- ::lib.schema/query]
+  (-> query
+      lib/add-parameters-for-template-tags
+      ;; to expand template tag parameters
+      qp.preprocess/preprocess
+      (as-> $query (if (lib/native-only-query? $query)
+                     $query
+                     (lib/native-query query (:query (qp.compile/compile $query)))))))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/dependencies/native_validation.clj]: Is this deliberately the input `query` rather than `$query`?

File: src/metabase/queries/api/card.clj [hunk 3]
```diff
@@ -271,26 +262,28 @@
   [cols]
   (map #(update-keys % u/->kebab-case-en) cols))
 
+;; FIXME
```
Comment (bshepherdson) [inline src/metabase/queries/api/card.clj]: If this is still relevant, add a comment.

File: test/metabase/xrays/automagic_dashboards/core_test.clj [hunk 4]
```diff
@@ -49,7 +52,7 @@
 
 ;;; ------------------- `->root source` -------------------
 
-(deftest ^:parallel source-root-table-test
+(deftest ^:paralell source-root-table-test
```
Comment (bshepherdson) [inline test/metabase/xrays/automagic_dashboards/core_test.clj]: These were originally spelled correctly, and now are broken.

(Tangentially, a linter for `^:paralell` and other typos might be handy?)

**Review by bshepherdson — APPROVED** [review]
LGTM, aside from the need to grep for `^:paralllel` (three medial Ls) and `^:paralell` 😄

**Comment by sanex3339** [comment]
Sample app e2e are failing with this error
image

**Review by sanex3339 — DISMISSED** [review]
Please address the error above
