### PR TITLE
Fix race condition in sync, causing failure if a table gets deleted inbetween steps

### LINKED ISSUE #52496: The task sync-fields fail if table doesn't exist
### Describe the bug

Hello!
We have Metabase instance connected to several DBs. One of them is Clickhouse, it has about hundred schemas and more than 1700 tables.
After last update (from 0.47.1 to the 0.51.3) we faced with several issues. Metabase is currently unable to reliably synchronize new tables and their structure. Now we are on 0.52.6, the problem still exists. We use the latest version of Clickhouse driver.
I already [posted](https://discourse.metabase.com/t/debugging-table-structure-sync/196874) this on [discourse.metabase.com](http://discourse.metabase.com). But now I think that is a bug.

As far as I understand, Metabase finds some table during the sync-tables task and can't find it during the sync-fields.

### To Reproduce

1. Create a new table in Clickhouse
2. In the Metabase UI, start synchronizing the DB schema
3. When the sync-tables task is completed, delete the new table as soon as possible
4. Get a sync-fields task error.

### Expected behavior

Metabase simply displays a WARN message in the log and continues processing other tables.

### Logs

It fails with this SQL-error

```JSON
{
  "status": "failed",
  "exception": "class clojure.lang.ExceptionInfo",
  "message": "Code: 60. DB::Exception: Table <SCHEMA>.<TABLE> does not exist. Maybe you meant <SCHEMA>.<TABLE1>?. (UNKNOWN_TABLE) (version 24.8.4.13 (official build))\n",
  "stacktrace": [
    "com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:107)",
    "com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeAny(SqlBasedPreparedStatement.java:219)",
    "com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeQuery(SqlBasedPreparedStatement.java:246)",
    "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:743)",
    "--> driver.sql_jdbc.sync.describe_table$ma$reify__92292.reduce(describe_table.clj:94)",
    "driver.sql_jdbc.sync.describe_table$fields_metadata$reify$reify__92316.reduce(describe_table.clj:161)",
    "driver.sql_jdbc.sync.describe_table$fields_metadata$reify__92311.reduce(describe_table.clj:169)",
    "driver.sql_jdbc.sync.describe_table$fn__92332.invokeStatic(describe_table.clj:215)",
    "driver.sql_jdbc.sync.describe_table$fn__92332.invoke(describe_table.clj:213)",
    "driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invokeStatic(describe_table.clj:283)",
    "driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invoke(describe_table.clj:279)",
    "driver.sql_jdbc.sync.describe_table$describe_table$fn__92366.invoke(describe_table.clj:295)",
    "driver.clickhouse$fn__118389$fn__118391.invoke(clickhouse.clj:126)",
    "driver.sql_jdbc.execute$do_with_resolved_connection87379__87380.invokeStatic(execute.clj:338)",
    "driver.sql_jdbc.execute$do_with_resolved_connection87379__87380.invoke(execute.clj:321)",
    "driver.clickhouse$fn__118389.invokeStatic(clickhouse.clj:87)",
    "driver.clickhouse$fn__118389.invoke(clickhouse.clj:85)",
    "driver.sql_jdbc.sync.describe_table$describe_table.invokeStatic(describe_table.clj:290)",
    "driver.sql_jdbc.sync.describe_table$describe_table.invoke(describe_table.clj:287)",
    "driver.clickhouse_introspection$fn__114232.invokeStatic(clickhouse_introspection.clj:160)",
    "driver.clickhouse_introspection$fn__114232.invoke(clickhouse_introspection.clj:158)",
    "sync.fetch_metadata$table_fields_metadata93306__93307.invokeStatic(fetch_metadata.clj:53)",
    "sync.fetch_metadata$table_fields_metadata93306__93307.invoke(fetch_metadata.clj:40)",
    "sync.fetch_metadata$describe_fields_using_describe_table$fn__93313.invoke(fetch_metadata.clj:63)",
    "db.connection$do_with_connection_primary_method_default.invokeStatic(connection.clj:132)",
    "db.connection$do_with_connection_primary_method_default.invoke(connection.clj:130)",
    "sync.sync_metadata.fields$saync_fields_BANG_93383__93384$fn__93385.invoke(fields.clj:82)",
    "sync.util$do_with_error_handling.invokeStatic(util.clj:191)",
    "sync.util$do_with_error_handling.invoke(util.clj:184)",
    "sync.sync_metadata.fields$sync_fields_BANG_93383__93384.invokeStatic(fields.clj:76)",
    "sync.sync_metadata.fields$sync_fields_BANG_93383__93384.invoke(fields.clj:71)",
    "sync.util$run_step_with_metadata63619__63621$fn__63623$fn__63626.invoke(util.clj:495)",
    "models.task_history$do_with_task_history63456__63457.invokeStatic(task_history.clj:121)",
    "models.task_history$do_with_task_history63456__63457.invoke(task_history.clj:109)",
    "sync.util$run_step_with_metadata63619__63621$fn__63623.doInvoke(util.clj:488)",
    "sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:132)",
    "sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:126)",
    "sync.util$do_with_start_and_finish_debug_logging.invokeStatic(util.clj:150)",
    "sync.util$do_with_start_and_finish_debug_logging.invoke(util.clj:146)",
    "sync.util$run_step_with_metadata63619__63621.invokeStatic(util.clj:482)",
    "sync.util$run_step_with_metadata63619__63621.invoke(util.clj:477)",
    "sync.util$run_sync_operation63669__63670$fn__63671$fn__63679.invoke(util.clj:568)",
    "sync.util$run_sync_operation63669__63670$fn__63671.invoke(util.clj:566)",
    "models.task_history$do_with_task_history63456__63457.invokeStatic(task_history.clj:121)",
    "models.task_history$do_with_task_history63456__63457.invoke(task_history.clj:109)",
    "sync.util$run_sync_operation63669__63670.invokeStatic(util.clj:563)",
    "sync.util$run_sync_operation63669__63670.invoke(util.clj:558)",
    "sync.sync_metadata$sync_db_metadata_BANG_94014__94015$fn__94016.invoke(sync_metadata.clj:70)",
    "sync.util$do_with_error_handling.invokeStatic(util.clj:191)",
    "sync.util$do_with_error_handling.invoke(util.clj:184)",
    "driver$fn__59501.invokeStatic(driver.clj:914)",
    "driver$fn__59501.invoke(driver.clj:914)",
    "sync.util$sync_in_context$fn__63528.invoke(util.clj:167)",
    "sync.util$with_db_logging_disabled$fn__63525.invoke(util.clj:159)",
    "sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:132)",
    "sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:126)",
    "sync.util$with_start_and_finish_logging$fn__63512.invoke(util.clj:144)",
    "sync.util$with_sync_events63502__63503$fn__63507.invoke(util.clj:118)",
    "sync.util$with_duplicate_ops_prevented$fn__63492.invoke(util.clj:90)",
    "sync.util$do_sync_operation63543__63544.invokeStatic(util.clj:216)",
    "sync.util$do_sync_operation63543__63544.invoke(util.clj:210)",
    "sync.sync_metadata$sync_db_metadata_BANG_94014__94015.invokeStatic(sync_metadata.clj:68)",
    "sync.sync_metadata$sync_db_metadata_BANG_94014__94015.invoke(sync_metadata.clj:65)",
    "api.database$fn__106499$fn__106504.invoke(database.clj:1017)"
  ],
  "ex-data": {
    "toucan2/context-trace": [
      [
        "execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection",
        {
          "toucan2.jdbc.query/sql-args": [
            "SELECT * FROM `metabase_table` WHERE ((`active` = TRUE) AND (`visibility_type` IS NULL)) AND (`schema` IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)) AND (`db_id` = ?)",
            "...",
            14
          ]
        }
      ],
      [
        "resolve connection",
        {
          "toucan2.connection/connectable": "class metabase.db.connection.ApplicationDB"
        }
      ],
      [
        "resolve connection",
        {
          "toucan2.connection/connectable": "default"
        }
      ],
      [
        "resolve connection",
        {
          "toucan2.connection/connectable": null
        }
      ],
      {
        "toucan2.pipeline/rf": "clojure.core$map$fn__5950$fn__5951@4df7c638"
      },
      [
        "with compiled query",
        {
          "toucan2.pipeline/compiled-query": [
            "SELECT * FROM `metabase_table` WHERE ((`active` = TRUE) AND (`visibility_type` IS NULL)) AND (`schema` IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)) AND (`db_id` = ?)",
            "...",
            14
          ]
        }
      ],
      [
        "with built query",
        {
          "toucan2.pipeline/built-query": {
            "select": [
              "*"
            ],
            "from": [
              [
                "metabase_table"
              ]
            ],
            "where": [
              "and",
              [
                "and",
                [
                  "=",
                  "active",
                  true
                ],
                [
                  "=",
                  "visibility_type",
                  null
                ]
              ],
              [
                "in",
                "schema",
                [
                  "..."
                ]
              ],
              null,
              [
                "=",
                "db_id",
                14
              ]
            ]
          }
        }
      ],
      [
        "with resolved query",
        {
          "toucan2.pipeline/resolved-query": {
            "where": [
              "and",
              [
                "and",
                [
                  "=",
                  "active",
                  true
                ],
                [
                  "=",
                  "visibility_type",
                  null
                ]
              ],
              [
                "in",
                "schema",
                [
                  "..."
                ]
              ],
              null
            ]
          }
        }
      ],
      [
        "with parsed args",
        {
          "toucan2.pipeline/query-type": "toucan.query-type/select.instances",
          "toucan2.pipeline/parsed-args": {
            "kv-args": {
              "db_id": 14
            },
            "queryable": {
              "where": [
                "and",
                [
                  "and",
                  [
                    "=",
                    "active",
                    true
                  ],
                  [
                    "=",
                    "visibility_type",
                    null
                  ]
                ],
                [
                  "in",
                  "schema",
                  [
                    "..."
                  ]
                ],
                null
              ]
            }
          }
        }
      ],
      [
        "with model",
        {
          "toucan2.pipeline/model": "model/Table"
        }
      ],
      [
        "with unparsed args",
        {
          "toucan2.pipeline/query-type": "toucan.query-type/select.instances",
          "toucan2.pipeline/unparsed-args": [
            "model/Table",
            "db_id",
            14,
            {
              "where": [
                "and",
                [
                  "and",
                  [
                    "=",
                    "active",
                    true
                  ],
                  [
                    "=",
                    "visibility_type",
                    null
                  ]
                ],
                [
                  "in",
                  "schema",
                  [
                    "..."
                  ]
                ],
                null
              ]
            }
          ]
        }
      ]
    ]
  },
  "original-info": null
}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "exasol",
      "mysql",
      "clickhouse",
      "mongo"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-01-15",
      "tag": "v0.52.6",
      "hash": "1a9cb72"
    },
    "settings": {},
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.5.13-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.5+11-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.5+11-LTS",
    "os.name": "Linux",
    "os.version": "5.14.0-375.el9.x86_64",
    "user.language": "en"
  }
}
```

### Severity

blocking

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by bronsa**
closes #52496
Closes https://linear.app/metabase/issue/SEM-39/the-task-sync-fields-fail-if-table-doesnt-exist

### Description

If the DB has a lot of tables, and they get created/deleted often, we may be attempting to sync tables that no longer exist due to timing issues. 
In some cases, that currently crashes. This PR makes syncing a non-existent table a no-op. 

### How to verify

See steps in the ticket

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/sync/sync_metadata/fields_test.clj [hunk 1]
```diff
@@ -385,3 +385,11 @@
              (->> (db->fields db)
                   (mapv :visibility_type)
                   frequencies))))))
+
+(deftest sync-fields-resilient-to-non-existence-test
+  (testing "[[sync-fields/sync-fields-for-table!]] doesn't crash on a non-existent table"
```
Comment (lbrdnk) [inline test/metabase/sync/sync_metadata/fields_test.clj:390]: Suffix with the number of the issue in testing context could be helpful.

File: modules/drivers/clickhouse/test/metabase/driver/clickhouse_test.clj [hunk 2]
```diff
@@ -227,3 +229,12 @@
                 ["2016-05-01T00:00:00Z" 81.892]
                 ["2016-06-01T00:00:00Z" 71.954]]
                (mt/rows (qp/process-query q))))))))
+
+(deftest clickhouse-sync-fields-resilient-to-non-existence-test
```
Comment (lbrdnk) [inline modules/drivers/clickhouse/test/metabase/driver/clickhouse_test.clj:233]: I think this test is not necessary as we have the `sync-fields-resilient-to-non-existence-test` now. Isn't the clickhouse part of `mt/normal-drivers`?

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj [hunk 3]
```diff
@@ -87,23 +87,31 @@
 (defn- fallback-fields-metadata-from-select-query
   "In some rare cases `:column_name` is blank (eg. SQLite's views with group by) fallback to sniffing the type from a
   SELECT * query."
-  [driver ^Connection conn db-name-or-nil schema table]
+  [driver ^Connection conn db-name-or-nil schema table-name]
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/sync/describe_table.clj:90]: 👍

**Review by lbrdnk — APPROVED** [review]
