### PR TITLE
Fix faded dashcards when switching dashboards

### LINKED ISSUE #3470: All cards in dashboards are greyed-out
I upgraded to the 0.20 branch.
When I change to a new dashboard using the task switcher all the cards are greyed out. (like if the filter wasnt applied)

I see this in the console.
selectors.js:89 Uncaught TypeError: Cannot read property 'ordered_cards' of undefined

If i reload the dashboards it works as expected or when i access the first dashboard after a refresh. The problem only appears when I switch to another dashboard.

------
Version is the release/0.20 branch.
Chrome on OSX. 
All databases affected.
Metabase on SQL

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3470

### CODE REVIEW

File: frontend/src/metabase/dashboard/dashboard.js [hunk 1]
```diff
@@ -476,6 +476,7 @@ const cardDurations = handleActions({
 }, {});
 
 const parameterValues = handleActions({
+    [INITIALIZE]: { next: () => ({}) },
```
Comment (kdoh) [inline frontend/src/metabase/dashboard/dashboard.js]: Might be worth throwing in a comment why we're setting the state to an empty object here. I was a bit confused until I looked into the underlying issue a bit more.

**Comment by kdoh** [comment]
Left a quick note about comments but otherwise LGTM.

**Comment by swatisinghi** [comment]
I upgraded to version 0.25.2 and seeing this issue again. Can someone help?
