### PR TITLE
Disable remapping when syncing Field values. Handle human readable values in `GET /api/field/:id/values`

### LINKED ISSUE #13235: Cannot filter by selecting remapped display value from dropdown list
**Describe the bug**
When a field has remapping with foreign key display value and is showing a dropdown list, then it's not possible to select the value from the list to filter, because it uses the display value as the actual filter value instead of the ID.

**To Reproduce**
1. Admin > Data Model > Sample Dataset > Orders > Product ID - set "Filtering on this field"="A list of all values" and "Display values"="Use foreign key" as `Product.Title`
image
2. Simple question > Sample Dataset > Orders - click Filter > Product ID
image
3. Click any value on the list - this will cause the query to fail with `Data conversion error converting "Aerodynamic Bronze Hat";`, because it's trying to filter `PRODUCT_ID="Aerodynamic Bronze Hat"`
4. Inputting a number in the filter, or clicking the column row action menu "View this ...", or if the field is set to a search, then the query works.

<details><summary>stacktrace</summary>

```
09-12 00:49:24 ERROR middleware.log :: GET /api/field/105/remapping/106 500 7.7 ms (5 DB calls) 
{:via [{:type java.text.ParseException, :message "Unparseable number: \"Aerodynamic Bronze Hat\"", :at [java.text.NumberFormat parse "NumberFormat.java" 431]}],
 :trace
 [[java.text.NumberFormat parse "NumberFormat.java" 431]
  [metabase.api.field$parse_query_param_value_for_field invokeStatic "field.clj" 359]
  [metabase.api.field$parse_query_param_value_for_field invoke "field.clj" 354]
  [metabase.api.field$fn__55560 invokeStatic "field.clj" 367]
  [metabase.api.field$fn__55560 invoke "field.clj" 362]
  [compojure.core$wrap_response$fn__1993 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1977 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1982 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 151]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.middleware.auth$enforce_authentication$fn__68576 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.routes$fn__70109$fn__70110 doInvoke "routes.clj" 56]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.middleware.exceptions$catch_uncaught_exceptions$fn__68679 invoke "exceptions.clj" 96]
  [metabase.middleware.exceptions$catch_api_exceptions$fn__68676 invoke "exceptions.clj" 84]
  [metabase.middleware.log$log_api_call$fn__70557$fn__70558 invoke "log.clj" 197]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.middleware.log$log_api_call$fn__70557 invoke "log.clj" 191]
  [metabase.middleware.security$add_security_headers$fn__68642 invoke "security.clj" 121]
  [metabase.middleware.json$wrap_json_body$fn__70260 invoke "json.clj" 64]
  [metabase.middleware.json$wrap_streamed_json_response$fn__70278 invoke "json.clj" 100]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__70858 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__70874 invoke "params.clj" 69]
  [metabase.middleware.misc$maybe_set_site_url$fn__70588 invoke "misc.clj" 59]
  [metabase.middleware.session$bind_current_user$fn__65134$fn__65135 invoke "session.clj" 204]
  [metabase.middleware.session$do_with_current_user invokeStatic "session.clj" 186]
  [metabase.middleware.session$do_with_current_user invoke "session.clj" 178]
  [metabase.middleware.session$bind_current_user$fn__65134 invoke "session.clj" 203]
  [metabase.middleware.session$wrap_current_user_info$fn__65121 invoke "session.clj" 169]
  [metabase.middleware.session$wrap_session_id$fn__65109 invoke "session.clj" 127]
  [metabase.middleware.auth$wrap_api_key$fn__68584 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__70778 invoke "cookies.clj" 216]
  [metabase.middleware.misc$add_content_type$fn__70573 invoke "misc.clj" 28]
  [metabase.middleware.misc$disable_streaming_buffering$fn__70596 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__70820 invoke "gzip.clj" 86]
  [metabase.middleware.ssl$redirect_to_https_middleware$fn__70609 invoke "ssl.clj" 39]
  [metabase.server$async_proxy_handler$fn__70335 invoke "server.clj" 72]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 500]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 547]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 103]
  [org.eclipse.jetty.io.ChannelEndPoint$2 run "ChannelEndPoint.java" 117]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 806]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 938]
  [java.lang.Thread run "Thread.java" 834]],
 :cause "Unparseable number: \"Aerodynamic Bronze Hat\"",
 :message "Unparseable number: \"Aerodynamic Bronze Hat\"",
 :type java.text.ParseException}

09-12 00:49:27 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2020-09-12T00:49:26.683336+02:00[Europe/Copenhagen]",
 :via
 [{:status :failed,
   :class org.h2.jdbc.JdbcSQLException,
   :error
   "Data conversion error converting \"Aerodynamic Bronze Hat\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 1e5104b2fb903d7a88f2ea021a81c87ad497bce3cf5492c546f7f0574c0eba36\nSELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\", \"PEOPLE__via__USER_ID\".\"NAME\" AS \"NAME\", \"PRODUCTS__via__PRODUCT_ID\".\"TITLE\" AS \"TITLE\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN \"PUBLIC\".\"PEOPLE\" \"PEOPLE__via__USER_ID\" ON \"PUBLIC\".\"ORDERS\".\"USER_ID\" = \"PEOPLE__via__USER_ID\".\"ID\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"PRODUCTS__via__PRODUCT_ID\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"PRODUCTS__via__PRODUCT_ID\".\"ID\" WHERE \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = ? LIMIT 2000 [22018-197]",
   :stacktrace
   ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
    "org.h2.message.DbException.get(DbException.java:168)"
    "org.h2.value.Value.convertTo(Value.java:1116)"
    "org.h2.value.Value.convertTo(Value.java:617)"
    "org.h2.value.Value.convertTo(Value.java:592)"
    "org.h2.mvstore.db.MVSecondaryIndex.convertToKey(MVSecondaryIndex.java:326)"
    "org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:262)"
    "org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:258)"
    "org.h2.index.BaseIndex.find(BaseIndex.java:130)"
    "org.h2.index.IndexCursor.find(IndexCursor.java:176)"
    "org.h2.table.TableFilter.next(TableFilter.java:471)"
    "org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1452)"
    "org.h2.result.LazyResult.hasNext(LazyResult.java:79)"
    "org.h2.result.LazyResult.next(LazyResult.java:59)"
    "org.h2.command.dml.Select.queryFlat(Select.java:527)"
    "org.h2.command.dml.Select.queryWithoutCache(Select.java:633)"
    "org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)"
    "org.h2.command.dml.Query.query(Query.java:371)"
    "org.h2.command.dml.Query.query(Query.java:333)"
    "org.h2.command.CommandContainer.query(CommandContainer.java:114)"
    "org.h2.command.Command.executeQuery(Command.java:202)"
    "org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)"
    "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
    "--> driver.sql_jdbc.execute$fn__72618.invokeStatic(execute.clj:267)"
    "driver.sql_jdbc.execute$fn__72618.invoke(execute.clj:265)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:389)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
    "driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)"
    "driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)"
    "driver.h2$fn__72752.invokeStatic(h2.clj:82)"
    "driver.h2$fn__72752.invoke(h2.clj:79)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
    "query_processor.context.default$default_runf.invoke(default.clj:67)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:26)"
    "query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
    "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
    "query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
    "query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
    "query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
    "query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
    "query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
    "query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:311)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
    "query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
    "query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
    "driver$do_with_driver.invokeStatic(driver.clj:61)"
    "driver$do_with_driver.invoke(driver.clj:57)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
    "query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
    "query_processor.store$do_with_store.invoke(store.clj:40)"
    "query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
    "query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:147)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
    "query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
    "query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:107)"
    "query_processor.reducible$sync_qp$qp_STAR___38083$fn__38086.invoke(reducible.clj:133)"
    "query_processor.reducible$sync_qp$qp_STAR___38083.invoke(reducible.clj:132)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:215)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:211)"
    "query_processor$fn__47372$process_query_and_save_execution_BANG___47381$fn__47384.invoke(query_processor.clj:227)"
    "query_processor$fn__47372$process_query_and_save_execution_BANG___47381.invoke(query_processor.clj:219)"
    "query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425$fn__47428.invoke(query_processor.clj:239)"
    "query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425.invoke(query_processor.clj:232)"
    "api.dataset$fn__50707$fn__50710.invoke(dataset.clj:55)"
    "query_processor.streaming$streaming_response_STAR_$fn__35496$fn__35497.invoke(streaming.clj:73)"
    "query_processor.streaming$streaming_response_STAR_$fn__35496.invoke(streaming.clj:72)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
    "async.streaming_response$do_f_async$fn__23282.invoke(streaming_response.clj:85)"],
   :state "22018"}],
 :json_query
 {:type "query",
  :query {:source-table 11, :filter ["=" ["field-id" 82] "Aerodynamic Bronze Hat"]},
  :database 4,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\", \"PEOPLE__via__USER_ID\".\"NAME\" AS \"NAME\", \"PRODUCTS__via__PRODUCT_ID\".\"TITLE\" AS \"TITLE\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN \"PUBLIC\".\"PEOPLE\" \"PEOPLE__via__USER_ID\" ON \"PUBLIC\".\"ORDERS\".\"USER_ID\" = \"PEOPLE__via__USER_ID\".\"ID\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"PRODUCTS__via__PRODUCT_ID\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"PRODUCTS__via__PRODUCT_ID\".\"ID\" WHERE \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = ? LIMIT 2000",
  :params ("Aerodynamic Bronze Hat")},
 :status :failed,
 :class java.lang.NumberFormatException,
 :stacktrace
 ["java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)"
  "java.base/java.lang.Integer.parseInt(Integer.java:652)"
  "java.base/java.lang.Integer.parseInt(Integer.java:770)"
  "org.h2.value.Value.convertTo(Value.java:1061)"
  "org.h2.value.Value.convertTo(Value.java:617)"
  "org.h2.value.Value.convertTo(Value.java:592)"
  "org.h2.mvstore.db.MVSecondaryIndex.convertToKey(MVSecondaryIndex.java:326)"
  "org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:262)"
  "org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:258)"
  "org.h2.index.BaseIndex.find(BaseIndex.java:130)"
  "org.h2.index.IndexCursor.find(IndexCursor.java:176)"
  "org.h2.table.TableFilter.next(TableFilter.java:471)"
  "org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1452)"
  "org.h2.result.LazyResult.hasNext(LazyResult.java:79)"
  "org.h2.result.LazyResult.next(LazyResult.java:59)"
  "org.h2.command.dml.Select.queryFlat(Select.java:527)"
  "org.h2.command.dml.Select.queryWithoutCache(Select.java:633)"
  "org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)"
  "org.h2.command.dml.Query.query(Query.java:371)"
  "org.h2.command.dml.Query.query(Query.java:333)"
  "org.h2.command.CommandContainer.query(CommandContainer.java:114)"
  "org.h2.command.Command.executeQuery(Command.java:202)"
  "org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)"
  "--> driver.sql_jdbc.execute$fn__72618.invokeStatic(execute.clj:267)"
  "driver.sql_jdbc.execute$fn__72618.invoke(execute.clj:265)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:389)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)"
  "driver.h2$fn__72752.invokeStatic(h2.clj:82)"
  "driver.h2$fn__72752.invoke(h2.clj:79)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
  "query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
  "query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
  "query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
  "query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:311)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
  "query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
  "query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:107)"
  "query_processor.reducible$sync_qp$qp_STAR___38083$fn__38086.invoke(reducible.clj:133)"
  "query_processor.reducible$sync_qp$qp_STAR___38083.invoke(reducible.clj:132)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:215)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:211)"
  "query_processor$fn__47372$process_query_and_save_execution_BANG___47381$fn__47384.invoke(query_processor.clj:227)"
  "query_processor$fn__47372$process_query_and_save_execution_BANG___47381.invoke(query_processor.clj:219)"
  "query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425$fn__47428.invoke(query_processor.clj:239)"
  "query_processor$fn__47416$process_query_and_save_with_max_results_constraints_BANG___47425.invoke(query_processor.clj:232)"
  "api.dataset$fn__50707$fn__50710.invoke(dataset.clj:55)"
  "query_processor.streaming$streaming_response_STAR_$fn__35496$fn__35497.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__35496.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__23282.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error
 "Data conversion error converting \"Aerodynamic Bronze Hat\"; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 1e5104b2fb903d7a88f2ea021a81c87ad497bce3cf5492c546f7f0574c0eba36\nSELECT \"PUBLIC\".\"ORDERS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ORDERS\".\"USER_ID\" AS \"USER_ID\", \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" AS \"PRODUCT_ID\", \"PUBLIC\".\"ORDERS\".\"SUBTOTAL\" AS \"SUBTOTAL\", \"PUBLIC\".\"ORDERS\".\"TAX\" AS \"TAX\", \"PUBLIC\".\"ORDERS\".\"TOTAL\" AS \"TOTAL\", \"PUBLIC\".\"ORDERS\".\"DISCOUNT\" AS \"DISCOUNT\", \"PUBLIC\".\"ORDERS\".\"CREATED_AT\" AS \"CREATED_AT\", \"PUBLIC\".\"ORDERS\".\"QUANTITY\" AS \"QUANTITY\", \"PEOPLE__via__USER_ID\".\"NAME\" AS \"NAME\", \"PRODUCTS__via__PRODUCT_ID\".\"TITLE\" AS \"TITLE\" FROM \"PUBLIC\".\"ORDERS\" LEFT JOIN \"PUBLIC\".\"PEOPLE\" \"PEOPLE__via__USER_ID\" ON \"PUBLIC\".\"ORDERS\".\"USER_ID\" = \"PEOPLE__via__USER_ID\".\"ID\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"PRODUCTS__via__PRODUCT_ID\" ON \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = \"PRODUCTS__via__PRODUCT_ID\".\"ID\" WHERE \"PUBLIC\".\"ORDERS\".\"PRODUCT_ID\" = ? LIMIT 2000 [22018-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-table 11,
   :filter [:= [:field-id 82] [:value "Aerodynamic Bronze Hat" {:base_type :type/Integer, :special_type :type/FK, :database_type "INTEGER", :name "PRODUCT_ID"}]],
   :fields
   [[:field-id 83]
    [:field-id 80]
    [:field-id 82]
    [:field-id 84]
    [:field-id 87]
    [:field-id 88]
    [:field-id 81]
    [:datetime-field [:field-id 86] :default]
    [:field-id 85]
    [:joined-field "PEOPLE__via__USER_ID" [:field-id 91]]
    [:joined-field "PRODUCTS__via__PRODUCT_ID" [:field-id 106]]],
   :limit 2000,
   :joins
   [{:strategy :left-join, :source-table 12, :alias "PEOPLE__via__USER_ID", :fk-field-id 80, :condition [:= [:field-id 80] [:joined-field "PEOPLE__via__USER_ID" [:field-id 92]]]}
    {:strategy :left-join, :source-table 10, :alias "PRODUCTS__via__PRODUCT_ID", :fk-field-id 82, :condition [:= [:field-id 82] [:joined-field "PRODUCTS__via__PRODUCT_ID" [:field-id 105]]]}]},
  :database 4,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash [30, 81, 4, -78, -5, -112, 61, 122, -120, -14, -22, 2, 26, -127, -56, 122, -44, -105, -68, -29, -49, 84, -110, -59, 70, -9, -16, 87, 76, 14, -70, 54]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

09-12 00:49:27 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.2 s (29 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (3 idle, 0 queued) (62 total active threads) Queries in flight: 0 (0 queued)
```

</details>

**Information about your Metabase Installation:**
Metabase 0.36.4 and 0.36.5.1

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #13235

There were actually two things wrong here: 

1. The query used to sync FieldValues for a remapped Field was incorrectly returning the values from the remapped-to Field when a human-readable Field ID was used
2. The `GET /api/field/:id/values` endpoint was not using the special logic used by `GET /api/field/:id/search` or the Dashboard chain filter endpoints to return tuples of `[original-value remapped-value]`. Instead it was just returning tuples of `[original-value]`; however since the FieldValues were synced incorrectly it was **actually** returning pairs of `[remapped-value]`.

I fixed both issues, however this might not be fixed until the FieldValues get synced again (did not verify this). This can be manually triggered by going to Admin > Data Model > (DB) > (Table) > little gear icon for the Field > Re-scan this field

### CODE REVIEW

File: test/metabase/test_runner/effects_test.clj [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+              :pass?            false}
+             (#'effects/partial=-diff [1 2 3] [1 2 4])))))
+
+  (testing "Empty sequence match"
+    (is (= {:a 1, :b []}
+           (#'effects/remove-keys-not-in-expected
+            {:a 1, :b []}
+            {:a 1, :b [], :c [1]})))
+    (is (partial= {:a 1, :b []}
+                  {:a 1, :b []}))))
```
Comment (camsaul) [inline test/metabase/test_runner/effects_test.clj:56]: Not really part of this PR but I was using `partial=` to write my new tests and I noticed there was a bug when `expected` had an empty sequence. So I wrote a bunch of tests for it and fixed that bug here

**Comment by camsaul** [comment]
The e2e test repro is failing. I think it's failing because we need to trigger a resync for the new values to actually pop up... could use some 👀 from @flamber or @nemanjaglumac tho to confirm that that's actually right before I change the test.

**Review by dpsutton — APPROVED** [review]

**Comment by flamber** [comment]
@camsaul That sounds a lot like #15542 is in play.

**Comment by nemanjaglumac** [comment]
@camsaul I am seeing the exact same thing as the CI, both in Cypress and when testing locally.

After remapping the value, when I go to the orders table and try filtering on a (remapped) ProductId, I don't even see a dropdown with the values. The only input is "Enter an ID".
image

Reading your description, I went to the admin > data model and manually re-synced that field. Waited a little bit, did a hard refresh... nothing helps. It's still offers **only** "Enter an ID" input field.

Even if I re-sync the whole "Orders" table, nothing happens.

Hope this helps?

**Comment by camsaul** [comment]
@nemanjaglumac did you try the workaround from #15542? There are a few more steps.

> Workaround is to click "Discard cached field values" after changing "Display values", and doing a browser refresh. Or to do it on all fields, do it in Admin > Databases > (db) > click "Discard saved field values" then "Re-scan field values now".

It was working for me when I manually triggered the re-scan but I did have to refresh the page a few times.

@flamber were you able to try this locally?

**Comment by flamber** [comment]
@camsaul I've tried to Github build and seeing the same as @nemanjaglumac posted a screenshot of. No list, just text input.

**Comment by camsaul** [comment]
Ok, so I am able to reproduce the list not showing up locally now. It turns out the frontend breaks if the API response for `GET /api/field/:id/values` doesn't parrot back the original `:field_id` 😒. Fixed things by including that in the API response.
