### PR TITLE
`with-join-conditions` should add `:join-alias` to RHSes

### LINKED ISSUE #32558: [MLv2] [Bug] `join-alias` is only added to the first condition's field reference
It seems like the `join-alias` is only added to the first condition's RHS field reference. When adding more conditions to the same join, the `join-alias` is missing.

Here's an example query with two conditions:

<details>
<summary>Expand snippet</summary>

```js
{
    database: 1,
    type: "query",
    query: {
      "source-table": 2,
      joins: [
        {
          fields: "all",
          alias: "Products",
          condition: [
            "and",
            [
              "=",
              ["field", 13, { "base-type": "type/Integer" }],
              [
                "field",
                5,
                { "base-type": "type/BigInteger", "join-alias": "Products" },
              ],
            ],
            [
              "=",
              ["field", 14, { "base-type": "type/DateTime" }],
              ["field", 7, { "base-type": "type/DateTime" }],
            ],
          ],
          "source-table": 1,
        },
      ],
    },
  }
```

</details>

### To reproduce

1. Start a query from the sample Orders table
2. Join the Products table on Orders.PRODUCT_ID = Products.ID (using `Lib.joinConditionClause` + `Lib.join`)
3. Use `Lib.withJoinConditions` + `Lib.replaceClause` and add another join condition (e.g. Orders.CREATED_AT = Products.CREATED_AT)
4. Inspect the second condition's field reference

**Expected:** RHS field reference has a `join-alias`
**Actual**: RHS field reference only has a common set of options and gets dropped as invalid

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #32558

* `with-join-conditions` will now set the `:join-alias` for the RHS for all *standard join conditions*, which I'm using to mean any join condition similar to the ones the FE would create (binary filter clauses with two `:field` refs). 
   * This will not stomp on any join aliases you have explicitly specified. 
   * Only applied when you call `with-join-conditions` with a join that already has an `:alias`, which may not be true if we're in the process of building it still
* I updated `with-join-alias` to set the alias for RHSes when adding an alias to a join we're in the process of building that did not yet have an alias. This covers cases where you called `with-join-conditions` before the join had an alias

### CODE REVIEW

File: frontend/src/metabase-lib/metadata.ts [hunk 1]
```diff
@@ -33,6 +33,7 @@ export function metadataProvider(
   databaseId: DatabaseId,
   metadata: Metadata,
 ): MetadataProvider {
+  console.log("Initializing new metadata provider for metadata", metadata);
```
Comment (camsaul) [inline frontend/src/metabase-lib/metadata.ts:36]: Unrelated but I added this to make it easier to debug metadata issues like #32511

File: src/metabase/lib/join.cljc [hunk 2]
```diff
@@ -71,25 +71,68 @@
...
-
-  This is currently true of normal FE usage, but may not be true everywhere in the future; we don't want to make MLv2
-  impossible to use if you're doing something different like swapping the order of the columns or some sort of more
-  complex condition."
-  [join old-alias new-alias]
-  (if-not old-alias
+  If `old-alias` is specified, uses [[metabase.mbql.util.match]] to update all the `:field` references using the old
+  alias.
+
+  If `old-alias` is `nil`, updates the RHS of all 'normal' conditions (binary filter clauses with two `:field` refs as
```
Comment (metamben) [inline src/metabase/lib/join.cljc:112]:
```suggestion
  If `old-alias` is `nil`, updates the RHS of all 'standard' conditions (binary filter clauses with two `:field` refs as
```

**Review by metamben — APPROVED** [review]
