### PR TITLE
Fix data labels too dense with large single series

### LINKED ISSUE #39568: [dc.js migration] overly dense data labels (multi-series/breakouts)
- The overlapping issue is not-reproduceable, but the overly dense is. Combining this work with https://github.com/metabase/metabase/issues/40196

---
question/7398
https://metaboat.slack.com/archives/C06G94JTWBS/p1706193943708289

Screenshot 2024-03-04 at 1 04 34 PM

question/12334
https://metaboat.slack.com/archives/C06G94JTWBS/p1706195021545219

https://metaboat.slack.com/archives/C06G94JTWBS/p1712762091179319
https://metaboat.slack.com/archives/C06G94JTWBS/p1712762595935719

### LINKED ISSUE #40196: [dc.js migration] data labels too dense with large single series
question/12014

image

---
Relevant files for calculating how dense labels should be
- [chart_values.js (master)](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/lib/chart_values.js#L319-L346)
- [buildEChartsLabelOptions (ECharts)](https://github.com/metabase/metabase/blob/echarts/frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts#L120)
- [getDataLabelFormatter (ECharts)](https://github.com/metabase/metabase/blob/echarts/frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts#L92)

### PR DESCRIPTION
**Pull request by JesseSDevaney**
- Closes: https://github.com/metabase/metabase/issues/40196
- Closes: https://github.com/metabase/metabase/issues/39568

**Demo** _(updated)_

https://github.com/metabase/metabase/assets/22608765/c808cbf9-bebc-43f3-a3be-99f7f083729a

### CODE REVIEW

**Review by kulyk — APPROVED** [review]

**Review by alxnddr — CHANGES_REQUESTED** [review]
I think we need to tweak the logic based on chart width, data points density, and maybe data labels widths becuase it looks too rare:
Screenshot 2024-05-22 at 3 06 11 PM

**Review by cdeweyx — APPROVED** [review]
LGTM other than Sasha's comments re rare labels

**Review by alxnddr — COMMENTED** [review]
I'd slightly tweak the logic to make it more dense so cases like this show all labels since there is enough space for this:
Screenshot 2024-05-30 at 11 19 44 AM

File: frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts [hunk 1]
```diff
@@ -324,6 +330,225 @@ function shouldRenderCompact(
...
+  };
+
+  dataset.forEach(datum => {
+    totalNumberOfDots += seriesWithSymbols.filter(
+      seriesModel => datum[seriesModel.dataKey] != null,
+    ).length;
+
+    // if we will not be displaying any labels, we do not have to calculate the
+    // label statistics
+    if (
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts:441]: Seems like we don't need to iterate through the data at all if `!settings["graph.show_values"] ||
      settings["graph.label_value_frequency"] === "all"` so we can move it out of the forEach

File: frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts [hunk 2]
```diff
@@ -192,7 +192,28 @@ export type StackModel = {
...
+export type ChartDataDensity =
+  | WaterFallChartDataDensity
+  | CartesianChartDataDensity;
+
+export type WaterFallChartDataDensity = BaseChartDataDensity & {
+  type: "waterfall";
+};
+
+export type CartesianChartDataDensity = BaseChartDataDensity & {
+  type: "cartesian";
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts:210]: nit: "combo" is a better name since waterfall is a cartesian chart

**Review by alxnddr — APPROVED** [review]
Looks good, I left two minor comments, please have a look before merging

File: patches/echarts+5.5.0.patch [hunk 3]
```diff
@@ -69,3 +70,21 @@ index c25de1b..f94690e 100644
    // Add stack dimension, they can be both calculated by coordinate system in `unionExtent`.
    // That put stack logic in List is for using conveniently in echarts extensions, but it
    // might not be a good way.
+diff --git a/node_modules/echarts/lib/label/labelLayoutHelper.js b/node_modules/echarts/lib/label/labelLayoutHelper.js
+index a75f606..57bec85 100644
+--- a/node_modules/echarts/lib/label/labelLayoutHelper.js
++++ b/node_modules/echarts/lib/label/labelLayoutHelper.js
+@@ -256,6 +256,13 @@ export function hideOverlap(labelList) {
```
Comment (alxnddr) [inline patches/echarts+5.5.0.patch:77]: It would be possible to get this behavior without patching ECharts by using labelLayout and shifting empty labels to one single place outside of the chart but it would be quite hackish. So I agree that ECharts should ignore empty labels when computing layout

File: frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts (hunk 1 above)
Comment (JesseSDevaney) [reply frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts:441]: We still will need to determine how many total dots there will be, and we use that to automatically hide them if there are a lot of them. 

That conditional is only preventing label statistics from being computed since those settings relate to labels.
