### PR TITLE
fix: return 204 on nonpersisted card unpersist

### LINKED ISSUE #44857: Don't 404 on `api/card/<id>/unpersist` if the card is not persisted
we 404 on no card which is sensible. But we also 404 on the persistence record

`(api/let-404 [persisted-info (t2/select-one PersistedInfo :card_id card-id)]`

We should just 204 there if it isn't already persisted.

https://metaboat.slack.com/archives/C01LQQ2UW03/p1719529206708639

### PR DESCRIPTION
**Pull request by edpaget**
Closes https://github.com/metabase/metabase/issues/44857

### Description

changes API behaviour to give us a 204 instead of 404 status code when calling unpersist on a card that does not have a persistedinfo model

### How to verify

Still haven't figured out how this can be triggered in practice, but sending `POST /api/cards/:card-id/unpersist` from the frontend manually correctly returns a 204 and does not cause anything to break. 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by johnswanson — APPROVED** [review]
👏 looks good!

File: test/metabase/api/card_test.clj [hunk 1]
```diff
@@ -3049,7 +3049,12 @@
                  (t2/select-one-fn :state :model/PersistedInfo :id (u/the-id pnotmodel)))))
         (testing "Can't re-persist non-model cards"
           (is (= "Card is not a model"
-                 (mt/user-http-request :crowberto :post 400 (format "card/%d/persist" (u/the-id notmodel))))))))))
+                 (mt/user-http-request :crowberto :post 400 (format "card/%d/persist" (u/the-id notmodel))))))))
+    (mt/with-temp
+      [:model/Card          notmodel  {:database_id (u/the-id db), :type :question}]
```
Comment (camsaul) [inline test/metabase/api/card_test.clj:3054]:
```suggestion
      [:model/Card notmodel {:database_id (u/the-id db), :type :question}]
```
