### PR TITLE
fixes offset images when dnd-ing columns in dashcards

### LINKED ISSUE #52905: Misaligned column labels while editing dashboard visualization options of pivot tables
### Describe the bug

The measure and grouping column labels become misaligned when dragged while editing the dashboard-specific visualization options of a pivot table.

### To Reproduce

1. Edit a dashboard with a pivot table
2. Bring up visualization options for the pivot
3. Try to drag measures
4. See the metric label is misaligned while being dragged

https://github.com/user-attachments/assets/1b7fc625-ccd9-4bc3-a4e0-dacd254c704b

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
1.52.8
```

### Severity

Annoying, reported by a customer

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
Closes #52905 
### Description

This bug only happens when dragging around columns for a pivot table _within_ a dashcard, because react-beautiful-dnd (which is the lib we use to handle drag-and-drop) gets confused by the portalled dialog, basically. They recommend to use a cloning approach and the Droppable component even exposes the right prop to do so.

Incidentally, this revealed that the Pivot table doesn't refresh when the columns are being reordered. In prod, no error lmessages is logged in the console but in dev, we can see that there's a maximum call stack error happening. I fixed this too, for good measure.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Edit a dashboard with a pivot table
2. Bring up visualization options for the pivot
3. Try to drag measures
4. The dragged item should follow the mouse cursor nicely

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.tsx [hunk 1]
```diff
@@ -145,7 +145,24 @@ export const ChartSettingFieldsPartition = ({
...
-            <Droppable droppableId={partitionName} type={partitionType}>
+            <Droppable
+              droppableId={partitionName}
+              type={partitionType}
+              renderClone={(provided, snapshot, rubric) => (
+                <Box
+                  ref={provided.innerRef}
+                  {...provided.draggableProps}
+                  {...provided.dragHandleProps}
+                  className={CS.mb1}
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.tsx:156]: Can we use mantine style prop here?

**Review by alxnddr — APPROVED** [review]
