### PR TITLE
Fix serdes of missing cards in click behavior

### LINKED ISSUE #49667: Click behavior does not get removed when the destination card is deleted
### Describe the bug

New Trash functionality doesn't remove click behaviour reference to deleted card. This might work on the frontend part even though the behaviour is strange but Serialization will fail in these cases

### To Reproduce

1. Go to New -> Question -> Sample DB -> Orders -> Save as Question 1
2. Go to New -> Question -> Sample DB -> Products -> Save as Question 2
3. Add both to a dashboard:

Image

4. Setup Click behaviour on Question 1 to go to Question 2

Image

5. Now go to Question 2 -> Archive it (or as we call it now - Move to trash) ... Notice the changes that happen int he dashboard. The Question gets removed as well (so far so good)

Image

6. When you click on the Click behaviour it still takes you to the archive (not sure if it's by design):

Image

7. Now go back to that archived question and delete it permanently. Nothing changes on the dashboard which is good but now try to click on Question 1 Click behaviour and the click behviour redirects you to Question 1 and if you check the settings it shows Not Found:

Image

NOW THIS IS THE PROBLEM I AM SEEING WITH THIS. If you check the Database. report_dashbaordcard you will notice the click behaviour still points to card 213 but that card doesn't exist anymore

Image

The main problem would be around serialization cause the frontend seems to have away to handle this even though it's kind of buggy (instead of just removing the reference on all click behaviour) it redirects to the same question when the question on click behaviour is not Found. But Serailization will fail cause these references don't exist anymore

Image

to get the logs above you need to pass the `?full_stacktrace=true` else they wound show up and the serialization will just fail

### Expected behavior

Not sure but when we permanently delete a Question we should completely delete every reference there is to it

### Logs

_No response_

### Information about your Metabase installation

51

### Severity

Not sure of the severity right now but this flow can make serialization hard to work with

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by johnswanson**
When exporting a dashboard, we export its dashcards, including cards referenced inside its viz_settings.

The problem is that viz_settings might have references to now-nonexistent cards.

This is an initial stab at cleaning up the problem, specifically for click behavior. If Dashboard D has Dashcard DC, which has a click-behavior that links to Card C, then when we collect the descendants of D, we'll include a reference to C - even if C has been deleted.

So this makes two changes: first, when calculating the descendants of a dashcard, don't include links to cards that don't exist. And, when exporting the click behavior, remove the whole thing entirely if the card it points to doesn't exist.

Note that this is a bit hacky, and we're only solving the problem for click behaviors, not e.g. Card C uses card D as a source, and card D got deleted (which will trigger the same issue).

Fixes #49667

### CODE REVIEW

File: src/metabase/models/serialization.clj [hunk 1]
```diff
@@ -1379,7 +1392,11 @@
 (defn- export-viz-click-behavior [settings]
   (some-> settings
           (m/update-existing    :click_behavior export-viz-click-behavior-link)
-          (m/update-existing-in [:click_behavior :parameterMapping] export-viz-click-behavior-mappings)))
+          (m/update-existing-in [:click_behavior :parameterMapping] export-viz-click-behavior-mappings)
+          (as-> updated-settings
+                (if (nil? (:click_behavior updated-settings))
+                  (dissoc updated-settings :click_behavior)
+                  updated-settings))))
```
Comment (escherize) [inline src/metabase/models/serialization.clj:1399]:
```suggestion
          (cond-> updated-settings
            (nil? (:click_behavior updated-settings)) (dissoc :click_behavior))
```

File: src/metabase/models/serialization.clj [hunk 2]
```diff
@@ -844,10 +844,20 @@
       (cond
         (nil? entity)      (throw (ex-info "FK target not found" {:model model
                                                                   :id    id
-                                                                  :skip  true}))
+                                                                  :skip  true
+                                                                  ::type :target-not-found}))
         (= (count path) 1) (first path)
         :else              path))))
 
+(defn- export-fk?
```
Comment (escherize) [inline src/metabase/models/serialization.clj:852]: Take it or leave it, but I'm not sure about naming this `export-fk?` when it returns nil or a fk (or a seq of fks). [The style guide calls them predicate methods](https://github.com/bbatsov/clojure-style-guide?tab=readme-ov-file#predicate-methods). 

Seems like it's being used as a predicate (with the `when` below), but also not, so maybe it's ok. I can't think of a great way to express it... Maybe introducing another function that is truly a predicate so that they both have a clear use-case rather than: We use this to either check if it's truthy/falsey, _or_ use the fk returned value?

**Review by escherize — APPROVED** [review]
Nicely done!

File: src/metabase/models/serialization.clj (hunk 1 above)
Comment (johnswanson) [reply src/metabase/models/serialization.clj]: I committed this but then realized it doesn't quite work, I ended up needing to wrap this back into `as->`.
