### PR TITLE
Cancel jobs in bigquery

### LINKED ISSUE #32027: BigQuery does not stop the query when the user leaves the page
### Describe the bug

With all drivers we wait for the query to return from the DB, and if the user leaves the page or the connection gets cut, the backend stops the query.

BigQuery doesn't seem to do this:
1) create a BigQuery project and add a public dataset
2) Start a Metabase server with a reverse proxy on top, which cuts connections after 5 seconds of waiting
3) Connect your BigQuery project to Metabase
4) Build a query than can take 30-40 seconds (something with many unions)
5) run the query, and then check the queries that are running in BigQuery with
```
SELECT
 job_id,
 creation_time,
 query,
 start_time,
 end_time,
 end_time - start_time,
 state
 FROM `region-us`.INFORMATION_SCHEMA.JOBS_BY_PROJECT
WHERE state = 'RUNNING'
 order by start_time desc
```

you'll see that the reverse proxy will have already killed the connection, but the query will be still running in BigQuery

### To Reproduce

See above

### Expected behavior

If the request gets cut, we should kill the connection

### Logs

E.g. cutting the connection via a reverse proxy after 1 second
2023-06-30 01:43:07,557 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: canceled] 1.1 s (25 DB calls) App DB connections: 0/7 Jetty threads: 2/50 (10 idle, 0 queued) (69 total active threads) Queries in flight: 0 (0 queued)

but then in bigquery I had
image

### Information about your Metabase installation

```JSON
v47-RC2, but this comes from the beginning of the times
```

### Severity

P2

### Additional context

_No response_

### LINKED ISSUE #65916: Metabase doesn't actually cancel Job in Bigquery after pressing Cancel
### Describe the bug

Clicking the Cancel button (the "X" in Editor mode) doesn’t actually cancel the query on BigQuery’s side. It just stops it in Metabase.
This leads to situations where creators may write inefficient, long-running queries, execute them, and unintentionally clog BigQuery’s queue and consume excessive resources, because from their perspective it looks like the query was cancelled. Administrators then have to manually locate these long-running queries and cancel them using BigQuery’s tools.

### To Reproduce

1. Create a complex query which will run for a long time (usually due to inefficient JOINs on big tables)
2. Run it in Editor mode.
3. Find it in Jobs Explorer in BigQqery as ACTIVE
4. Cancel it before it finishes
5. Check Jobs Explorer again and see it still has the ACTIVE state

### Expected behavior

Metabase should properly cancel the running job by invoking the corresponding method of BigQuery's API.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-11-11",
      "tag": "v0.57.2",
      "hash": "cef18f9"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.19"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.9+10-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.9+10-LTS",
    "os.name": "Linux",
    "os.version": "5.15.0-1062-gcp",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

May cause excessive resource usage and related costs. Mild severity

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/65916
Closes https://github.com/metabase/metabase/issues/32027

### Description

When you cancel a bigquery query from metabase we cancel it on the metabase side but we don't actually cancel the job running on bigquery. This changes will actually cancel the job running in bigquery as well.

I'm not really sure if theres a good way to test this.

### How to verify

See demo

1. Run a slow query in metabase and cancel it:
```sql
WITH small AS (
  SELECT x, y
  FROM UNNEST(GENERATE_ARRAY(1, 900062)) AS x
  CROSS JOIN UNNEST(GENERATE_ARRAY(1, 1000)) AS y
)
SELECT SUM(SQRT(x * y))
FROM small;
```
2. Run this query:
```sql
SELECT
  creation_time,
  state,
  query,
  user_email,
  job_id,
  statement_type,
FROM
  `region-us`.INFORMATION_SCHEMA.JOBS
ORDER BY
  creation_time DESC
LIMIT 100;
```
3. Observe that it is given a status of done much quicker than before these changes.

### Demo

https://www.loom.com/share/b23ce13d8680452e8120967d0223f72b

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 1]
```diff
@@ -722,7 +726,9 @@
     (let [[status result] @result-promise]
       (case status
         :error  (handle-bigquery-exception result sql parameters)
-        :cancel (throw-cancelled sql parameters)
+        :cancel (do
+                  (.cancel client job-id)
+                  (throw-cancelled sql parameters))
```
Comment (metamben) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj]: Is it irrelevant what exception is thrown here? I think I'd have to think less if I saw something like


```suggestion
        :cancel (try
                  (.cancel client job-id)
                  (catch Throwable t
                    (log/warnf t "Couldn't cancel job %s" job-id)
                  (finally
                    (throw-cancelled sql parameters)))
```

**Review by metamben — APPROVED** [review]

**Review by metamben — APPROVED** [review]
