### PR TITLE
Make Athena test data loading more robust

### LINKED ISSUE #27534: Make Athena CI test data/loading more robust
With the normal S3 data store we can't delete data from Athena itself, so if data gets loaded more than once things are completely broken.

We need to put some code in our Athena test extensions to make sure it doesn't load duplicate data -- somehow this happened today and broke CI. Or maybe just put some logic in there to check that the test data is the right size and create something new if it's not.

Can we delete test data by hitting AWS directly automatically? (S3 bucket and Glue Console)

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #27534

Somehow we ended up loading duplicate data into the Athena `test-data` database/S3 bucket used by CI -- not sure how this happened since it's not supposed to loading data for databases that already exist. I'm guessing somehow it got its wires crossed there -- `SHOW DATABASES` must have timed out or returned nothing which lead to that data getting created a second time.

To prevent this from happening again I disabled the Athena data loading code unless you manually re-enable it, which we will still need to do occasionally when we define and load new datasets.

### CODE REVIEW

File: modules/drivers/athena/src/metabase/driver/athena.clj [hunk 1]
```diff
@@ -142,9 +142,14 @@
 
 ;;; ------------------------------------------------- date functions -------------------------------------------------
 
+(def ^:dynamic *loading-data*
+  "HACK! Whether we're loading data (e.g. in [[metabase.test.data.athena]]). We can't use `timestamp with time zone`
+  literals when loading data because Athena doesn't let you use a `timestamp with time zone` value for a `timestamp`
+  column, and you can only have `timestamp` columns when actually creating them."
+  false)
```
Comment (camsaul) [inline modules/drivers/athena/src/metabase/driver/athena.clj:149]: To fix the problems we had in CI I manually wiped all the data and recreated everything, and then ran into a bug with the data-loading code: it was trying to insert `timestamp with time zone` literals into `timezone` columns, which Athena does not allow, since you cannot create a `timestamp with time zone` column. Thus when loading data we need to compile `OffsetDateTime`s and `ZonedDateTime`s to `timestamp` literals. 

I had actually written both versions of the code for `OffsetDateTime` and `ZonedDateTime` previously -- one that compiled it to a `timestamp with time zone` literal (which is fine in `SELECT` queries), and another to a `timestamp` literal. So now that this flag was in place we can just choose the correct behavior based on what we're doing.

File: modules/drivers/athena/test/metabase/test/data/athena.clj [hunk 2]
```diff
@@ -28,8 +29,8 @@
 ;; Athena doesn't support dashes in Table names... we'll just go ahead and convert them all to underscores, even for DB
 ;; names.
 (defmethod ddl.i/format-name :athena
-  [driver table-or-field-name]
-  ((get-method ddl.i/format-name :sql-jdbc) driver (str/replace table-or-field-name #"-" "_")))
+  [driver database-or-table-or-field-name]
+  ((get-method ddl.i/format-name :sql-jdbc) driver (str/replace database-or-table-or-field-name #"-" "_")))
```
Comment (camsaul) [inline modules/drivers/athena/test/metabase/test/data/athena.clj:33]: Unrelated clarification, but this is used for database names too, at least in this namespace

File: modules/drivers/athena/test/metabase/test/data/athena.clj [hunk 3]
```diff
@@ -58,11 +59,46 @@
...
+;;; 5. After this you can recreate the database normally using the test loading code. Note that you must
+;;;    enable [[*allow-database-creation*]] for this to work:
+;;;
+;;;    ```
+;;;    (db/delete! 'Database :engine "athena", :name "sample-dataset")
+;;;    (binding [metabase.test.data.athena/*allow-database-creation* true]
+;;;      (metabase.driver/with-driver :athena
+;;;        (metabase.test/dataset sample-dataset
+;;;          (metabase.test/db))))
+;;;    ```
```
Comment (camsaul) [inline modules/drivers/athena/test/metabase/test/data/athena.clj:94]: I wrote down the steps for manually deleting data from the S3 bucket and Glue Console in case the CI issue ever comes up again. Hopefully not -- this PR should hopefully prevent that.

File: modules/drivers/athena/test/metabase/test/data/athena.clj [hunk 4]
```diff
@@ -58,11 +59,46 @@
...
+
 ;;; Athena requires backtick-escaped database name for some queries
 (defmethod sql.tx/drop-db-if-exists-sql :athena
-  [driver {:keys [database-name]}]
-  (log/warn "Dropping an Athena database does not delete existing data. You may have to delete in manually from S3 and Glue Console.")
-  (format "DROP DATABASE IF EXISTS `%s` CASCADE;" (ddl.i/format-name driver database-name)))
+  [_driver _dbdef]
+  (log/warn (str "You cannot delete a [non-Iceberg] Athena database using DDL statements. It has to be deleted "
+                 "manually from S3 and the Glue Console. See documentation in [[metabase.test.data.athena]] for "
+                 "instructions for doing this.")))
```
Comment (camsaul) [inline modules/drivers/athena/test/metabase/test/data/athena.clj:101]: `DROP DATABASE IF EXISTS ...` didn't delete data -- I think it might have deleted the Glue Console entry tho. But that seemed to cause even more problems when trying to recreate the data so I just took that out and replaced it with a message to read the instructions above if you actually want to delete data.

File: modules/drivers/athena/test/metabase/test/data/athena.clj [hunk 5]
```diff
@@ -177,11 +216,26 @@
...
   (let [database-name (ddl.i/format-name driver database-name)]
-    (if (contains? (existing-databases) database-name)
+    (cond
+      (contains? (existing-databases) database-name)
       (log/infof "Athena database %s already exists, skipping creation" (pr-str database-name))
+
+      (not *allow-database-creation*)
+      (log/fatalf (str "Athena database creation is disabled: not creating database %s. Tests will likely fail.\n"
+                       "See metabase.test.data.athena/*allow-database-creation* for more info.")
+                  (pr-str database-name))
```
Comment (camsaul) [inline modules/drivers/athena/test/metabase/test/data/athena.clj:236]: Under normal usage we should never get here, since the datasets we're testing against should already exist and come back from `(existing-databases)`. But if you defined a new dataset that doesn't exist yet, you would get here, so I made the log level here `fatalf` to make sure it pops up even in CI to tell you that you have to manually enable dataset creation.

I don't love making it hard to define new datasets in this way -- I'm sure it's only a matter of time before someone adds a new one and then can't figure out why Athena tests aren't passing -- but at least this message should point them in the right direction. And since it seems like the choice is either a) make it harder to define new datasets or b) run the risk of CI randomly exploding again with duplicate Athena data, I think option A is the lesser of two evils here.

**Review by metamben — APPROVED** [review]
👍
