### PR TITLE
Fix duplicate coercion on custom columns from joins

### LINKED ISSUE #63991: `UNIXMilliSeconds->DateTime` loses milliseconds part of the timestamp in drivers like Postgres, SQL Server, etc.
Follow steps to repro #63890. In H2 ,`ORDERS.QUANTITY` includes the millisecond component e.g. `1970-01-01T00:00:00.002Z` while in drivers like Postgres integer division (`orders.quantity / 1000)` is used and the millisecond component is lost, meaning we get `1970-01-01T00:00:00Z` instead.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #63890
Fixes #63991

Update driver QP code to only apply auto-coercion to a column that comes directly from a source table (as opposed to a join or previous stage) i.e. only columns with 

```clj
(pos-int? (driver-api/qp.add.source-table <column-metadata>))
```

I think this is an "ok" fix but a better long-term fix in the future would be to just have QP preprocessing middleware wrap any fields that need coercion in the appropriate MBQL functions and then stop having drivers need to determine when to apply coercion when compiling a field ref or not... that's a problem for another day tho, something I think I'll look at when we get to the point that we're migrating drivers to use Lib/MBQL 5.

Anyways when I wrote a test for this I discovered #63991 so I went ahead and fixed that in the ~6 or so drivers that were broken as well -- the fix was different for each driver but it involved tweaking either the SQL generation code for UNIX timestamp columns, the code for reading timestamp columns from JDBC result sets, or both

### CODE REVIEW

File: test/metabase/query_processor_test/expressions_test.clj [hunk 1]
```diff
@@ -1187,10 +1190,51 @@
                     [u.date/temporal-str->iso8601-str int int]
                     (qp/process-query query))))))))))
 
-(deftest ^:parallel null-array-test
```
Comment (camsaul) [inline test/metabase/query_processor_test/expressions_test.clj:1190]: Moved this because it has literally nothing to do with expressions

**Review by metamben — APPROVED** [review]
