### PR TITLE
Fix column alignment for fully-collapsed pivot exports

### LINKED ISSUE #58340: Pivot - More than 2 row groups mess up downloads
### Describe the bug

It seems that if you have more than 2 row groups it mess up downloads. It only works if you expand all the groups before the download. 

Image

### To Reproduce

As long as there are 2 Row Groups you will experience similar behaviour:

Image

I have created a question on stats:

https://stats.metabase.com/question/26042-question-as-pivot

Just try to download the Pivot in csv/xlsx and notice that if all are collapsed column values seem to have moved as described in the bug description

If you expand 1 group you end up with only Totals:

Image

### Expected behavior

I would expect all the Data to get exported in csv/xlsx the data should be expanded and in excel it should offer the dropdown buttons. At least not show wrong data when the columns are fully collapsed as in the "Describe the bug" section

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
54 and master
```

### Severity

Makes downloads hard to work with if you don't know what is going on and dependent on pivots

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes https://github.com/metabase/metabase/issues/58340

We just need to make sure we're limiting the number of top-left column headers to the actual depth of the left column tree. 

This means that a column header that is fully collapsed is omitted from the export. I think this is reasonable behavior — on the FE it's useful to see the header to know that you _can_ un-collapse it, but in an export it contributes no data and no utility. And you can always un-collapse it prior to exporting if you need that column.

image

image

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#58372** <a href="https://app.graphite.dev/github/pr/metabase/metabase/58372?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/metabase/metabase/58372?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: enterprise/backend/test/metabase_enterprise/cache/task/refresh_cache_configs_test.clj [hunk 1]
```diff
@@ -95,7 +95,7 @@
                                           :card_id      card-id-2}
                  :model/DashboardCard {} {:dashboard_id dashboard-id
                                           :card_id      card-id-2}]
-    (testing "Returns the card ID directly for a question cahce config"
+    (testing "Returns the card ID directly for a question cache config"
```
Comment (noahmoss) [inline enterprise/backend/test/metabase_enterprise/cache/task/refresh_cache_configs_test.clj:98]: Unrelated typo fix

**Review by tsplude — APPROVED** [review]
