### PR TITLE
Only load membership if user is updating group_ids

### LINKED ISSUE #10810: Updating Account Settings returns permission error
**Describe the bug**
Updating user name/email via :gear: Account Settings returns `Sorry, you don't have permission to see that.`, but actually saves the changes.

**Logs**
`Error: Object { status: 403 }` from `/api/permissions/membership`, when clicking Update.

**To Reproduce**
1. Login as non-admin user
2. Go to :gear: Account Settings and change name/email and click Update.
3. `Sorry, you don't have permission to see that.`

**Expected behavior**
Clicking Update would return a little confirmation message, just like changing password does.

**Screenshots**

**Information about your Metabase Installation:**
Metabase 0.33.0/0.33.1 on H2 with various OS/browsers.

**Additional context**
https://discourse.metabase.com/t/tweak-to-all-users-rights/7238

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #10810

### CODE REVIEW

File: frontend/src/metabase/entities/users.js [hunk 1]
```diff
@@ -89,11 +89,12 @@ const Users = createEntity({
...
       };
     },
-    update: thunkCreator => (...args) => async (dispatch, getState) => {
-      const result = await thunkCreator(...args)(dispatch, getState);
-      // HACK: reload memberships when updating a user
-      // TODO: only do this if group_ids changes
-      dispatch(loadMemberships());
+    update: thunkCreator => user => async (dispatch, getState) => {
+      const result = await thunkCreator(user)(dispatch, getState);
+      if (user.group_ids) {
```
Comment (paulrosenzweig) [inline frontend/src/metabase/entities/users.js]: It'd be nice to actually compare any `group_ids` passed to this with those currently stored in state. However, we store the current user both nested in entities and at the top level. We can't count on either being present, so it'd be ugly logic to extract the current `group_ids`.

Instead we just check if `group_ids` is passed to update. I added a test that will fail if the normal user update form starts fetching memberships again.

**Review by tlrobinson — APPROVED** [review]
