### PR TITLE
fix(sdk): css variables leak from Mantine to the host app

### LINKED ISSUE #56960: [SDK] css variables leaks from SDK's Mantine 7 to the customer's Mantine 7
If a customer is using Mantine 7 for their styling, the CSS variables targeting which applies the variables at runtime to `:root` will change the styles of the rest of that customer's app. For example, see this change in Shoppy when migrating from SDK 53 to 54.

Before

Image

After

Image

### PR DESCRIPTION
**Pull request by heypoom**
Closes EMB-324
Closes #56960

### Description

If a customer happened to use Mantine 7 (e.g. in the case of Shoppy), we are leaking the Mantine CSS variables to the global scope and it will alter the appearance of the customer's site. In our case, Shoppy is blocked from being upgraded to v54 because of how the CSS variables leaked.

Before - Shoppy styles looks different than production

image

Before - SDK's colors (orange) leaked into all Mantine buttons of the customer

CleanShot 2568-04-22 at 00 23 51@2x

After - there is still some issues on Shoppy's side that we can fix, but it mostly looks good.

CleanShot 2568-04-22 at 00 19 24@2x

After - SDK's colors (orange) no longer leaks into the Mantine button of the customer (pink)

CleanShot 2568-04-22 at 00 22 13@2x

### How to verify

- Check out the added end-to-end test. If you remove the code changes, the tests will fail and the colors from the customer's app will leak into the SDK. See screenshot 2 and 4 above.
- You can also test this with Shoppy by building this branch locally, and then run `rm -rf node_modules/.vite && rm -rf node_modules/@metabase/ && yarn add file:../metabase/resources/embedding-sdk && env NODE_OPTIONS=--max-old-space-size=7000 yarn dev` on Shoppy.
  - Compare this to Kelvin's https://github.com/metabase/shoppy/pull/114 branch, and the styles looks a lot different. See screenshot 1 and 3 above.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx [hunk 1]
```diff
@@ -45,6 +45,8 @@ export const PublicComponentStylesWrapper = forwardRef<
       dir="ltr"
       // eslint-disable-next-line react/prop-types -- className is in div props :shrugs:
       className={`mb-wrapper ${props.className}`}
+      // Mantine's cssVariablesSelector expects data-mantine-color-scheme to be set on the target element
+      data-mantine-color-scheme="light"
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx:49]: Mantine implicitly expects `data-mantine-color-scheme` to be present on element where `cssVariablesSelector` is applied to. Took me a long time to find out why the styles is broken.

File: frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx [hunk 2]
```diff
@@ -73,6 +73,7 @@ export const ThemeProvider = (props: ThemeProviderProps) => {
       theme={theme}
       getStyleNonce={() => window.MetabaseNonce ?? "metabase"}
       classNamesPrefix="mb-mantine"
+      cssVariablesSelector=".mb-wrapper"
```
Comment (heypoom) [inline frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx:76]: Without this, we are targeting `:root` which overrides the customer's Mantine config.

File: e2e/test-component/scenarios/embedding-sdk/styles-tests.cy.spec.tsx [hunk 3]
```diff
@@ -389,6 +390,57 @@ describe("scenarios > embedding-sdk > styles", () => {
...
+
+            <InteractiveQuestion
+              questionId={ORDERS_QUESTION_ID}
+              isSaveEnabled
+            />
+          </MetabaseProvider>
+        </MantineProvider>,
+      );
+
+      // Customer's elements outside of the SDK provider should have their brand color intact
```
Comment (WiNloSt) [inline e2e/test-component/scenarios/embedding-sdk/styles-tests.cy.spec.tsx:415]: You could also use `cy.log` which prints this text to Cypress window.

**Review by WiNloSt — APPROVED** [review]
tested on both shoppy and E2E, they look great! Thanks!

File: frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx [hunk 4]
```diff
@@ -73,6 +75,7 @@ export const ThemeProvider = (props: ThemeProviderProps) => {
       theme={theme}
       getStyleNonce={() => window.MetabaseNonce ?? "metabase"}
       classNamesPrefix="mb-mantine"
+      cssVariablesSelector={isEmbeddingSdk ? ".mb-wrapper" : undefined}
```
Comment (heypoom) [inline frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx:78]: We use `ThemeProvider` in unexpected places such as `use-body-cell-measure.tsx` and `use-measure-column-width.tsx`, and that actually caused the styles to be injected to `:root` instead of the `cssVariablesSelector`. Let's add the `isEmbeddingSdk` condition here as it's very easy to forgot to add it in `mantineProviderProps` if someone else uses it in the codebase.
