### PR TITLE
fix: add timezone to bigquery param substitution

### LINKED ISSUE #43597: BigQuery - Date Field Filter not including Timezone
### Describe the bug

In 1.49.13 and 50RC2, the query generated from a field filter doesn't include the timezone as it does in 1.49.6.
I haven't tested versions in between.

### To Reproduce

1. Confirm you have a value for Localization, I'm using Europe/Oslo for this example.

<br>
<br>

2. I'm using the following as a test query where 'timefield' is a field filter associated with a timestamp field in a BigQuery table.
```
SELECT
`mbsampledata.Cars`.`car_brand` AS `car_brand`,
`mbsampledata.Cars`.`car_model` AS `car_model`,
`mbsampledata.Cars`.`car_year` AS `car_year`,
`mbsampledata.Cars`.`msrp` AS `msrp`,
`mbsampledata.Cars`.`datesold` AS `datesold`
FROM
`mbsampledata.Cars`
WHERE {{timefield}}
```

<br>
<br>
 
3. Filter by Today
In version 1.49.6, it generates the following
```
SELECT
`mbsampledata.Cars`.`car_brand` AS `car_brand`,
`mbsampledata.Cars`.`car_model` AS `car_model`,
`mbsampledata.Cars`.`car_year` AS `car_year`,
`mbsampledata.Cars`.`msrp` AS `msrp`,
`mbsampledata.Cars`.`datesold` AS `datesold`
FROM
`mbsampledata.Cars`
WHERE timestamp_trunc(`mbsampledata.Cars`.`datesold`, day, 'Europe/Oslo') = timestamp "2024-06-04 00:00:00 Europe/Oslo"
```
<br>
<br>
 
In version 1.49.13 and 50RC2, it generates the following, without the timezone.
```
SELECT
`mbsampledata.Cars`.`car_brand` AS `car_brand`,
`mbsampledata.Cars`.`car_model` AS `car_model`,
`mbsampledata.Cars`.`car_year` AS `car_year`,
`mbsampledata.Cars`.`msrp` AS `msrp`,
`mbsampledata.Cars`.`datesold` AS `datesold`
FROM
`mbsampledata.Cars`
WHERE TIMESTAMP_TRUNC(`mbsampledata.Cars`.`datesold`, day, 'Europe/Oslo') = timestamp "2024-06-04 00:00:00Z"
```
 

### Expected behavior

For the timezone to be applied as it did in previous versions.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.49-linuxkit-pr",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-03",
      "tag": "v1.50.0-RC2",
      "hash": "7a8b73e"
    },
    "settings": {
      "report-timezone": "Europe/Oslo"
    }
  }
}
```

### Severity

P2 - Not able to use certain date filters

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snoe**
Fixes #43597

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj [hunk 1]
```diff
@@ -621,31 +622,80 @@
...
-                                                    :datetime  (if report-timezone "CURRENT_DATETIME('UTC')" "CURRENT_DATETIME()")
-                                                    :timestamp "CURRENT_TIMESTAMP()"}]
-                (testing (format "temporal type = %s" temporal-type)
-                  (is (= temporal-type
-                         (#'bigquery.qp/temporal-type (#'bigquery.qp/->temporal-type temporal-type form)))
-                      "Should be possible to convert to another temporal type/should report its type correctly")
-                  (is (= [expected-sql]
-                         (sql/format-expr (#'bigquery.qp/->temporal-type temporal-type form)))
-                      "Should convert to the correct SQL"))))))))))
+                  (qp.store/with-metadata-provider (mt/id)
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj:676]: indentation looks messed up here

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj [hunk 2]
```diff
@@ -935,10 +935,25 @@
...
-                                                             (for [arg args]
-                                                               (if (instance? java.time.temporal.Temporal arg)
-                                                                 (->temporal-type field-temporal-type arg)
-                                                                 arg)))))))
+                                                             (map (fn [arg]
+                                                                    (if (instance? java.time.temporal.Temporal arg)
+                                                                      ;; Since we add the zone as part of the
+                                                                      ;; LHS of the filter, we need to add the zone to
+                                                                      ;; the RHS as well.
+                                                                      (let [request-time-zone-id (qp.timezone/requested-timezone-id)
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:943]: Probably better to fetch this timezone once outside of the `for`, that way if its value changes inside between evaluation of the lazy sequence returned by `for` it doesn't mess stuff up

**Review by camsaul — APPROVED** [review]
well it looks ok to me except for the busted indentation and potential danger hitting `requested-timezone-id` repeatedly inside a lazy sequence
