### PR TITLE
Do not merge metadata for aggregation fields

### LINKED ISSUE #23248: Aggregation in Models causes the column name to incorrectly be parsed down to questions based on that Model
**Describe the bug**
Aggregation in Models causes the column name to incorrectly be parsed down to questions based on that Model.

Workaround is to not use Models, but just use a Saved Question instead.

**To Reproduce**
1. Question > Sample > Orders - summarize Distinct ProductID and Sum of Quantity, grouped by CreatedAt:Month
image
2. Save question and turn into Model - do a browser refresh
3. Go to Notebook to create a question based on the Model - summarize by three metrics, the first two metrics have incorrect column title
image

**Information about your Metabase Installation:**
Tested 0.43.2

**Additional context**
Likely related to #20624 and #23019.

### PR DESCRIPTION
**Pull request by qnkhuat**
Fix #23248, Part of #24815

It's important to note that this bug only happens with Models, but not questions.
This is because, with models, we want to make sure the user-edited metadata is applied (say you create a model and change the display name of a column).
In order for us to do, we often post-merge the `user-edited` metadata when annotating columns.

Let's say we have a model with a query
```clojure
{:source-table 2,
 :aggregation  [[:sum [:field 7 nil]]                ;; sum of total
                [:sum [:field 6 nil]]],              ;; sum of tax
 :breakout     [[:field 4 {:temporal-unit :month}]]} ;; break out by created_at
```

This model has a metadata
```clojure
[{:description "The date and time an order was submitted.",
  :semantic_type :type/CreationTimestamp,
  :unit :month,
  :name "CREATED_AT",
  :field_ref [:field 4 {:temporal-unit :month}],
  :effective_type :type/DateTime,
  :id 4,
  :display_name "Created At",
  :base_type :type/DateTime}
 {:display_name "Sum of Total",
  :semantic_type nil,
  :field_ref [:aggregation 0],
  :name "sum",
  :base_type :type/Float,
  :effective_type :type/Float}
 {:display_name "Sum of tax",
  :semantic_type nil,
  :settings nil,
  :field_ref [:aggregation 1],
  :name "sum_2",
  :base_type :type/Float,
  :effective_type :type/Float}]
```

Now we create a new question with the source is the above model

```clojure
{:aggregation  [["sum" ["field" "sum_2"]]], ;; sum of the "sum_2" column in the source table
 :source-table "card__1"}
```

When we run this question, we first generate the metadata based on the columns we select, which is only the `sum` aggregation in this case.
```clojure
{:base_type :type/Float,
 :display_name "Sum of Sum of Tax", ;; the display name
 :field_ref [:aggregation 0],
 :name "sum",
 :semantic_type nil,
 :settings nil,
 :source :aggregation}
```

But because the source question is a dataset, we want to merge the "user-edited" metadata over the column's metadata, which gives us
```clojure
{:display_name "Sum of Total", ;; this is the exact name of the field with "name"="sum" from the source metadata
 :semantic_type nil,
 :field_ref [:aggregation 0],
 :name "sum",
 :base_type :type/Float,
 :effective_type :type/Float}
```
This is wrong, the display_name should be "Sum of Sum of Tax", and It even got the wrong field name! -- "Total" instead of "Tax"

---

The reason for this is when we merge metadata in
https://github.com/metabase/metabase/blob/d93e15b5a0e511cb978c157b3b140466f6d3eb16/src/metabase/query_processor/middleware/annotate.clj#L524-L527

we use the "name" as an index, but we named the aggregation columns by the "operation".
So:
- The query uses a "sum" operation => it has a field with "name" = "sum"
- the source question also uses a "sum" operation, it also has a field with "name" = "sum", with the display_name = "Sum of Total"
- both the source question and the query has a field with "name" = "sum"

=> And since we `post-merge` the result-metadata from source, we get the display_name = "Sum of total"

The decision of using "name" as an index is arbitrary because a nested question could have a "sum" aggregation at both levels and they could be on totally different fields.

My current [solution](https://github.com/metabase/metabase/pull/24896#discussion_r951242049) is to *not* merge the metadata for aggregation at all.

This is not the optimal solution, I think the correct way to fix this is to have a `parent_field_ref`, in which we refer to the field that is applied aggregation on.
If we do this, we could enable things like preserving the semantic type of an aggregation field.

But I think that's a quite complex change and my solution is sufficient at the moment.

### CODE REVIEW

File: src/metabase/query_processor/middleware/annotate.clj [hunk 1]
```diff
@@ -517,10 +517,14 @@
 (defn- flow-field-metadata
   "Merge information about fields from `source-metadata` into the returned `cols`."
   [source-metadata cols dataset?]
-  (let [index           (fn [col] (or (:id col) (:name col "")))
-        index->metadata (m/index-by index source-metadata)]
-    (for [col cols]
-      (if-let [source-metadata-for-field (-> col index index->metadata)]
+  (let [by-key (m/index-by (comp qp.util/field-ref->key :field_ref) source-metadata)]
```
Comment (qnkhuat) [inline src/metabase/query_processor/middleware/annotate.clj:520]: Part of this is reverse the decision of using "name" as index we made in #19437

File: src/metabase/query_processor/util.clj [hunk 2]
```diff
@@ -127,7 +127,8 @@
   ensure survives."
   [fresh pre-existing]
   (let [by-key (m/index-by (comp field-ref->key :field_ref) pre-existing)]
-    (for [{:keys [field_ref] :as col} fresh]
-      (if-let [existing (get by-key (field-ref->key field_ref))]
+    (for [{:keys [field_ref source] :as col} fresh]
```
Comment (qnkhuat) [inline src/metabase/query_processor/util.clj:130]: Need to update it here because we merge metadata with the dataset metadata at the end.
https://github.com/metabase/metabase/blob/d93e15b5a0e511cb978c157b3b140466f6d3eb16/src/metabase/query_processor/middleware/annotate.clj#L674

File: src/metabase/query_processor/middleware/annotate.clj (hunk 1 above)
Comment (qnkhuat) [reply src/metabase/query_processor/middleware/annotate.clj:520]: Note that we could still keep that strategy of using `id then name` as an index and it'll still work.
But I think since using `field_ref` works perfectly and we also use `field_ref` as an index in `qp.util/combine-metadata`, so I think I'll keep this one consistent by reverting to the previous strategy.

File: test/metabase/query_processor/middleware/annotate_test.clj [hunk 3]
```diff
@@ -633,7 +633,43 @@
...
+                                                       "sum"
+                                                       {:base-type :type/Float}]]
+                                                     {:name "sum"}]
+                                                    [:aggregation-options
+                                                     [:count]
+                                                     {:name "count"}]]
+                                     :limit        1}))]
+        (is (= ["Sum of Sum of Price" "Count"]
+              (->> (add-column-info query {})
+                  :cols
```
Comment (calherries) [inline test/metabase/query_processor/middleware/annotate_test.clj:671]: nit: indentation

**Review by dpsutton — APPROVED** [review]

**Comment by mazameli** [comment]
Let's hold off on this one until we can get a look from @camsaul. @qnkhuat believes is straightforward and low-risk, but we're proceeding with caution around the QP.

**Review by metamben — APPROVED** [review]

File: test/metabase/query_processor_test/nested_queries_test.clj [hunk 4]
```diff
@@ -147,44 +147,49 @@
...
+                                                                               [:field
+                                                                                "sum"
+                                                                                {:base-type :type/Float}]]
+                                                                              {:name "sum"}]
+                                                                             [:aggregation-options
+                                                                              [:count]
+                                                                              {:name "count"}]]}}
+                                                  (when dataset?
+                                                    {:info {:metadata/dataset-metadata (:result_metadata card)}}))))
+                       :data
```
Comment (camsaul) [inline test/metabase/query_processor_test/nested_queries_test.clj:190]: Instead of all the `:data` and `select-keys` and stuff here you should rework this test to use `partial=`. Why? Because if the query errors there will be no `:data` key. And debugging it is going to be a pain in the butt. With `partial=` if the query fails the test failure will print the entire map including the error message.

File: test/metabase/query_processor/middleware/annotate_test.clj [hunk 5]
```diff
@@ -633,7 +633,43 @@
...
+                  (map :display_name)))))))))
```
Comment (camsaul) [inline test/metabase/query_processor/middleware/annotate_test.clj:672]: Same thing, use `partial=` here

File: src/metabase/query_processor/middleware/annotate.clj [hunk 6]
```diff
@@ -517,10 +517,14 @@
...
+    (for [{:keys [field_ref source] :as col} cols]
+     ;; aggregation fields are not from the source-metadata and their field_ref
+     ;; are not unique for a nested query. So do not merge them otherwise the metadata will be messed up.
+     ;; TODO: I think the best option here is to introduce a parent_field_ref so that
+     ;; we could merge preserve metadata such as “:sematic_type or :unit” from the source field.
```
Comment (camsaul) [inline src/metabase/query_processor/middleware/annotate.clj:525]: Not sure how I feel about the smart quote characters in code files TBH. I guess they're ok in comments. But I'm assuming something did this for you automatically... maybe you should disable that.

**Review by camsaul — APPROVED** [review]
Generally this looks good to me but I think you should rework those tests to use `partial=` so they're not nightmares to debug if they fail in the future
