### PR TITLE
Disallow aggregations in filters and custom columns

### LINKED ISSUE #58230: No validation in the custom expression editor when using an aggregation function in the custom column
### Repro steps
1. Start a new question
2. Pick any table, like Sample Database -> Orders
3. Click to add a custom column
4. In the custom expression editor enter something like `avg([Total])`and save
5. See the query error

### Expected behavior
You should not be able to save a custom column with am aggregation custom expression function

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/58230

- Adds a validator that will show an error when using an aggregation in an expression that does not support aggregations.
- Avoid showing helptext for aggregations when editing an expression that does not support them

### To verify
1. New -> Question -> Sample Database -> Orders
2. Add Custom Column (or a Custom filter)
3. Type `Average([Total])`
4. The help text popover should not appear
5. An error should be displayed

Screenshot 2025-06-03 at 11 55 12

### CODE REVIEW

File: frontend/src/metabase-lib/v1/expressions/mode.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+  operator: string,
+) {
+  if (!isDefinedClause(operator)) {
+    throw new DiagnosticError(t`Unknown operator ${operator}`);
+  }
+
+  const clause = getClauseDefinition(operator);
+  if (clause.type === "aggregation" && expressionMode !== "aggregation") {
+    throw new DiagnosticError(
+      t`Aggregations like ${clause.displayName} are not allowed when building a custom ${expressionMode}`,
```
Comment (ranquild) [inline frontend/src/metabase-lib/v1/expressions/mode.ts]: this won't be translated properly ${expressionMode}. If you want to keep it this way, you'd need a map from the enum value to a translated string

File: frontend/src/metabase-lib/v1/expressions/mode.ts [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+import type * as Lib from "metabase-lib";
+
+import { getClauseDefinition, isDefinedClause } from "./clause";
+import { DiagnosticError } from "./errors";
+
+export function expressionModeSupportsClause(
+  expressionMode: Lib.ExpressionMode,
+  operator: string,
+) {
+  try {
```
Comment (ranquild) [inline frontend/src/metabase-lib/v1/expressions/mode.ts]: Can we do it the other way? The main function returns a `boolean`, and the assert function uses it to throw?

**Review by ranquild — APPROVED** [review]
