### PR TITLE
Only log views for cards in a dashboard if the user views the tab

### LINKED ISSUE #41892: Views are logged for cards in a dashboard even if the user didn't view the tab
### Describe the bug

If a user views a dashboard, we add a `view_log` record and increment the `report_card.view_count` column for each card in the dashboard. If the dashboard has multiple tabs, we'll log views for cards on all tabs, even if the user never viewed it. We should only log and count views for the tabs users view.

[slack conversation](https://metaboat.slack.com/archives/C0641E4PB9B/p1714143102927189?thread_ts=1714129699.563259&cid=C0641E4PB9B)

### To Reproduce

1. Create a dashboard with a question in the second tab. Save it and view the first tab without viewing the second.
2. Query the app DB: `select * from view_log where model = 'card' and model_id = <id>;`, where <id> is the ID of the question.
You should see views for the question, even though you never visited the first tab.

### Expected behavior

views should only be logged if the user clicks on the tab containing the card.

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

low

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/41892, assuming [the issue with pivot table cards and metrics v2](https://metaboat.slack.com/archives/C064QMXEV9N/p1716513494230449?thread_ts=1716512794.557519&cid=C064QMXEV9N) is resolved.

The `view_count` for a card now is calculated by:
the number of successful POST /api/dashboard/:id/dashcard/:id/card/:id/query requests (and the public+embed equivalents)
+
the number of successful POST /api/dashboard/pivot/:id/dashcard/:id/card/:id/query requests (and the public+embed equivalents)
+
the number of successful GET /api/card/:id requests (and the public+embed equivalents)

### BE changes: 
Instead of logging views for all cards on a GET request for a dashboard, we now log views on each cards' query requests. The `:event/card-read` event is used for this purpose.

### FE changes: 
I've added/extended some e2e tests to verify the view counts are incremented correctly for regular, public, and embedded dashboards. I think I caught a bug in the process and reproduced it with tests, see this loom: https://www.loom.com/share/93ceb5c13c714c3eb7ad7b33bdf68f3c?sid=0ab113c7-5d8d-4f72-84ec-b0036f472401

### CODE REVIEW

**Comment by calherries** [comment]
@metabase/core-frontend-dashviz can I get a review of the e2e tests that I've added in this PR?

File: src/metabase/events/recent_views.clj [hunk 1]
```diff
@@ -12,11 +12,29 @@
...
+(m/defmethod events/publish-event! ::dashboard-read
   "Handle processing for a single event notification which should update the recent views for a user."
+  [topic {:keys [object-id user-id] :as _event}]
+  (span/with-span!
+    {:name (str "recent-views-" (name topic))
+     :topic topic
+     :user-id user-id}
+    (try
+      (let [model    (audit-log/model-name :model/Dashboard)
+            model-id object-id
```
Comment (crisptrutski) [inline src/metabase/events/recent_views.clj:27]: There's enough non-trivial duplication between these two handlers to justify a shared handler IMHO, something like `(publish-read-event! topic model model-id user-id)`. Despite being right next to each other, there's still a chance we update one and forget the other.

File: test/metabase/events/view_log_test.clj [hunk 2]
```diff
@@ -89,32 +89,25 @@
                    :model/DashboardCard _dashcard {:dashboard_id (u/id dashboard) :card_id (u/id card)}]
       (let [dashboard (t2/hydrate dashboard [:dashcards :card])]
         (testing "A basic dashboard read event is recorded in EE, as well as events for its cards"
```
Comment (crisptrutski) [inline test/metabase/events/view_log_test.clj:91]: We need to update this description to explain that the card events are dispatched separately.

File: test/metabase/events/view_log_test.clj [hunk 3]
```diff
@@ -175,7 +166,7 @@
       (mt/with-temp [:model/Dashboard dash {}]
         (testing "GET /api/dashboard/:id"
           (mt/user-http-request :crowberto :get 200 (format "dashboard/%s" (u/id dash)))
-          (is (partial= {:user_id (mt/user->id :crowberto), :model "dashboar", :model_id (u/id dash)}
+          (is (partial= {:user_id (mt/user->id :crowberto), :model "dashboard", :model_id (u/id dash)}
```
Comment (crisptrutski) [inline test/metabase/events/view_log_test.clj:169]: Good golly

**Review by crisptrutski — APPROVED** [review]
A small lie to correct in a test description, but functionally LGTM

File: src/metabase/events/recent_views.clj (hunk 1 above)
Comment (calherries) [reply src/metabase/events/recent_views.clj]: Good suggestion, I decided to tackle the duplication with a different approach though. [Here's what I have so far.](960d296c94bc59186b9f72fabf27a9969c612170) 

- I removed the `span/with-span!` calls since they are mostly redundant with this call in `recent-views/update-users-recent-views!`
https://github.com/metabase/metabase/blob/960d296c94bc59186b9f72fabf27a9969c612170/src/metabase/models/recent_views.clj#L112-L116
- I de-duplicated the try/catch calls which I assume have one purpose across all events: to reduce the impact of issues with `recent-views/update-users-recent-views!`

Nothing else can really be de-duplicated since the shape of the event map differs between events.

Comment (calherries) [reply src/metabase/events/recent_views.clj]: If you like what I did with the try/catch I'll extend this to more event types e.g. the ones in `metabase.events.view-log`

Comment (calherries) [reply src/metabase/events/recent_views.clj:27]: Actually in [this PR](https://github.com/metabase/metabase/pull/43167) I'm removing this whole file, so I'll continue this refactoring there

Comment (calherries) [reply src/metabase/events/recent_views.clj:27]: I've reverted the changes above in this PR 62cd24ec858882e6b7585c0d2692645e6d1eabf3

File: test/metabase/events/view_log_test.clj (hunk 2 above)
Comment (calherries) [reply test/metabase/events/view_log_test.clj]: updated [ca970d6](https://github.com/metabase/metabase/pull/43102/commits/ca970d626ad4d36951f4a3581e5142b1188a86a8)

**Comment by calherries** [comment]
@crisptrutski I realised this would have introduced a regression where `view_log.context` would be incorrectly set. (interestingly, it wasn't covered by tests). I've fixed it in this commit [c6f1b01](https://github.com/metabase/metabase/pull/43102/commits/c6f1b0168d533c0752b91d4aff0e5bfa35ec15c0).

File: src/metabase/events/view_log.clj [hunk 4]
```diff
@@ -89,35 +87,16 @@
...
      :user-id user-id}
     (try
-      (let [dashcards (filter :card_id (:dashcards object)) ;; filter out link/text cards wtih no card_id
-            user-id   (or user-id api/*current-user-id*)
-            views     (map (fn [dashcard]
-                             {:model      "card"
-                              :model_id   (u/id (:card_id dashcard))
-                              :user_id    user-id
-                              :has_access (readable-dashcard? dashcard)
-                              :context    "dashboard"})
```
Comment (calherries) [inline src/metabase/events/view_log.clj:115]: Previously `view_log` entries for card views from dashboard views would have `context=dashboard`. Similarly if the card view was from [a question](https://github.com/metabase/metabase/pull/43102/files#diff-1397b5fa941ecc1fba4d421b65e5cc9a6d81f158d017e3ba25020bf707fb72abL55) it would have `context=question`.

File: src/metabase/events/schema.clj [hunk 5]
```diff
@@ -21,26 +22,31 @@
...
+     :event/dashboard-delete       default-schema
+     :event/dashboard-remove-cards with-dashcards
+     :event/dashboard-add-cards    with-dashcards}))
 
 ;; card events
 
-(let [default-schema (mc/schema
+(let [view-only      (mc/schema
+                      [:map {:closed true}
+                       [:context ::lib.schema.info/context]
```
Comment (calherries) [inline src/metabase/events/schema.clj:40]: This matches the `context` column in `query_execution`.
https://github.com/metabase/metabase/blob/c0237533cbe8bae58a0127bacaac40efd16505a9/src/metabase/models/query_execution.clj#L30-L33

File: e2e/test/scenarios/dashboard/tabs.cy.spec.js [hunk 6]
```diff
@@ -404,6 +407,7 @@ describe("scenarios > dashboard > tabs", () => {
   });
 
   it("should only fetch cards on the current tab", () => {
+    cy.intercept("PUT", "/api/dashboard/*").as("saveDashboardCards");
```
Comment (alxnddr) [inline e2e/test/scenarios/dashboard/tabs.cy.spec.js:410]: A duplicated line

File: e2e/test/scenarios/dashboard/tabs.cy.spec.js [hunk 7]
```diff
@@ -486,10 +530,137 @@ describe("scenarios > dashboard > tabs", () => {
...
+    cy.wait(500); // this is needed to avoid flakes
+    firstQuestion().then(r => {
+      expect(r.view_count).to.equal(4); // 3 (previously) + 1 (firstQuestion)
+    });
+    secondQuestion().then(r => {
+      expect(r.view_count).to.equal(4); // 2 (previously) + 1 (secondQuestion) + 1 (second tab query)
+    });
+
+    goToTab("Tab 1");
+    cy.wait(1000);
```
Comment (alxnddr) [inline e2e/test/scenarios/dashboard/tabs.cy.spec.js:653]: Wdyt about replacing cy`.wait` with finding elements on the page that will indicate the state is ready for the assertion? Or waiting for requests being resolved

File: e2e/test/scenarios/dashboard/tabs.cy.spec.js [hunk 8]
```diff
@@ -444,22 +448,62 @@ describe("scenarios > dashboard > tabs", () => {
...
+    cy.wait(500); // this is needed to avoid flakes
+    firstQuestion().then(r => {
+      expect(r.view_count).to.equal(4); // 3 (previously) + 1 (firstQuestion)
+    });
+    secondQuestion().then(r => {
+      expect(r.view_count).to.equal(4); // 2 (previously) + 1 (secondQuestion) + 1 (secondTabQuery)
+    });
 
-    // Go back to first tab, expect no additional queries
+    // // Go back to first tab, expect no additional queries
```
Comment (alxnddr) [inline e2e/test/scenarios/dashboard/tabs.cy.spec.js:494]: really nit: double comments

File: e2e/test/scenarios/dashboard/tabs.cy.spec.js [hunk 9]
```diff
@@ -444,22 +448,62 @@ describe("scenarios > dashboard > tabs", () => {
...
+    });
+
     // Visit first tab and confirm only first card was queried
     visitDashboard(ORDERS_DASHBOARD_ID);
 
     cy.get("@firstTabQuery").should("have.been.calledOnce");
     cy.get("@secondTabQuery").should("not.have.been.called");
 
-    // Visit second tab and confirm only second card was queried
+    cy.wait(500); // this is needed to avoid flakes
```
Comment (alxnddr) [inline e2e/test/scenarios/dashboard/tabs.cy.spec.js:473]: Did it flake locally or on CI here? It seems that requests have been resolved so `view_count` should've been updated already. Is there some delay after which BE updates it?

**Review by crisptrutski — APPROVED** [review]

**Comment by calherries** [comment]
@alxnddr can you take another look, I took your suggestions and removed all the slow `cy.wait(1000)`s

**Review by alxnddr — APPROVED** [review]
Looks good, thanks for addressing the feedback!
