### PR TITLE
Fix Column Filters for remapped model columns

### LINKED ISSUE #23091: Not possible to filter native model using header cell context menu
**Describe the bug**
This issue is basically a duplicate of https://github.com/metabase/metabase/issues/23024, but with the slightly different context. The root cause is most probably the same.

It is not possible to filter a model based on a native question using the column header cell context.
The workaround is to use the "regular" filter sidebar, or to go to the notebook mode and use the filter there, or to use the bulk filter.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. Native > Sample > `select * from products`
2. Save question and turn into Model as "M1"
3. Edit Metadata and map `CATEGORY` to `Products.Category` field > Save changes
4. Click on the "Category" header cell
image
5. Click "Filter by this column
6. It correctly displays all filters but once you select any of them, "Add filter" button stays disabled
image
7. It is not possible to add any other filter type ("Is not", "Contains", "Is not empty"...)

**Expected behavior**
It should be possible to filter using the remapped column.

**Information about your Metabase Installation:**
local dev, `master`, 5acedcb85c51a1bf26c8f4102f3ede3f881bd7d5, H2, Sample Database

**Severity**
There is a workaround so probably a P3.

### PR DESCRIPTION
**Pull request by iethree**
## Description

Remapped columns in models were not filterable from their column header. This was because the remapping was causing the field ids to get lost in column filters. This finds the ids again and makes the column filters behave the same as the filter modal and filters in notebook mode.

Screen Shot 2022-08-04 at 2 27 56 PM

resolves https://github.com/metabase/metabase/issues/23091

## Testing Steps

1. Native > Sample > select * from products
1. Save question and turn into Model as "M1"
1. Edit Metadata and map CATEGORY to Products.Category field > Save changes
1. Click on the "Category" header cell
1. Click "Filter by this column
1. It correctly displays all filters but once you select any of them, "Add filter" button ~~stays disabled~~ is enabled
1. It is ~~not~~ possible to add any other filter type ("Is not", "Contains", "Is not empty"...)

- should still work for unmapped model columns
- should still work for regular question columns

### CODE REVIEW

File: frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx [hunk 1]
```diff
@@ -23,10 +23,17 @@ export default function ColumnFilterDrill({ question, clicked }) {
...
-  const initialFilter = new Filter([], null, query).setDimension(
-    column.field_ref,
-    { useDefaultOperator: true },
-  );
+
+  // if our field ref doesn't match our column id, we have a remapped column
+  // and need to use the field id instead of the ref
+  const fieldRef =
+    column.id !== undefined && column.id !== column.field_ref[1]
+      ? ["field", column.id, null]
```
Comment (WiNloSt) [inline frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx:31]: should we copy over the third element from the `column.field_ref` here? I'm not quite sure what they're for though.

Comment (iethree) [reply frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx:31]: 🤷  I'm not sure what it does either. I don't think i've seen it populated.

Comment (WiNloSt) [reply frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx:31]: There are some places where it's populated, but I'm not totally sure what they're used for or have a use for anything here specifically. e.g.
- https://github.com/metabase/metabase/blob/a0d5079de8315e21dc297e38c95ef1b8c2542419/frontend/test/metabase/lib/dataset.unit.spec.js#L154
- https://github.com/metabase/metabase/blob/a0d5079de8315e21dc297e38c95ef1b8c2542419/frontend/src/metabase/parameters/utils/mapping-options.unit.spec.js#L90
- https://github.com/metabase/metabase/blob/a0d5079de8315e21dc297e38c95ef1b8c2542419/frontend/test/metabase/lib/dataset.unit.spec.js#L233
- https://github.com/metabase/metabase/blob/a0d5079de8315e21dc297e38c95ef1b8c2542419/frontend/test/metabase/lib/query_time.unit.spec.js#L34

for me `null` indicate that the 3rd element is something this code won't use *for sure*. While copying it over is always look safer from the previous assumption, it would create noise if the 3rd element *isn't actually used* here. Now I'm on the fence about this since we both don't know what it's used for and whether it's being used here. Maybe other engineers would know @ranquild do you know what the 3rd item is used for and if it's used here? Or could you help tag other people who might know the answer. Thanks!

Comment (ranquild) [reply frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx:31]: The 3rd param is dimension options. `["field", 100, { "temporal-unit": "month" }]` - this is subdimension of `["field", 100, null]`. So passing `null` would likely change the behavior of this code. @WiNloSt @iethree  Could you test this with columns from aggregated results?

Comment (WiNloSt) [reply frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx:31]: When adding aggregation, the column mapping disappears. Not sure if that's supposed to happen.

What I did is using the repro steps to create "M1" and then from there count by category + created (by year) after saving I'll get a new question then after turning that into a model, there won't be an option to map which result column correspond to which table column.

I assume what this tries to fix is for a model created from SQL question, which I'm not sure there would be a subdimension in such a case.

@nemanjaglumac Is it possible to create a repo that the subdimension (3rd item in the MBQL field) isn't null?

Comment (iethree) [reply frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx:31]: In my testing, copying the field options breaks filters altogether for aggregated queries. The filters are simply invalid, and exhibit the same behavior as listed in the issue (you can't save them).

Mapping an aggregated field to a database field in a model makes any filter on that aggregated field throw an error. I think this is nonsensical, but I could see how a user would do it for something like a `max()` aggregation. Because this is a native query, I don't think we can detect if this is an aggregate column to disable filters on that field?

Screen Shot 2022-08-08 at 4 05 32 PM

Notably, filters from notebook mode and the bulk filter modal, have the same limitation.

In any event, I think we should merge this as-is. We definitely have some lingering limitations here with SQL-based models with aggregations, but this brings the column header filters to parity with the notebook and modal filters (i.e. they work for all non-aggregated fields when remapped).

Comment (WiNloSt) [reply frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx:31]: That's fair, I had some troubles with mapping column + aggregation when copying over the subdimension part as well. Seems reasonable to merge this as-is given the circumstances.

**Review by WiNloSt — APPROVED** [review]
There is a good discussion about copying the subdimension/option (3rd item in the MBQL field) and @iethree [tested the assumption](https://github.com/metabase/metabase/pull/24622#discussion_r940709967). Seems like it's best to merge this PR as-is, given how broken the filter when copying over the subdimension/option is.

File: frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx:31]: > @nemanjaglumac Is it possible to create a repo that the subdimension (3rd item in the MBQL field) is being used?

@WiNloSt not sure what **exactly** you had in mind, but asserting on that field would be possible in a repro, yes.
