### PR TITLE
Fix unable to search field values from partitioned tables

### LINKED ISSUE #40673: Bigquery: Can't search field values for required partition tables
### Describe the bug

When creating a question from a table that has a lot of rows (multiple 10.000s) and some filters of type "Is"/"Is not" on a same text column, the UI break and no data is being displayed. Instead a warning sign is showing with message "Something's gone wrong" when hovering. This happens both in the visualiser and editor modes (see screenshots below).

In my case I loaded 48 months of data partitions (with Dt = 48 last months) and had already set filters on column "Type" to not be "BANK_DEPOSIT" nor "CARD" and I was about to add another value to exclude. Please note that in the editor mode, even when the bug occur I can click the preview button next to the Filter section and see actual results, but the 3rd filter was not applied and the whole filter section is not showing anymore. It also sometimes happen when applying the first filter.

This bug appeared after updating from v0.48.3 to v0.49.1. I cannot give an exact threshold but it happens with tables that vae around 40.000 to 80.000 rows. Under 10.000 we don't seem to have this bug. In some cases we can use "contains"/"does not contain" and it will work, but for some other cases we want a specific filtering on the whole value and not just a substring.

In the visualiser mode the bug seems to not happen when creating filter by clicking on a cell and apply a "Is" or "Is not" on the cell's value. When creating the filter from the column header it almost always occurs on the first filter.

Visualiser mode:
Screenshot 2024-03-27 at 14 26 42

Editor mode:
Screenshot 2024-03-27 at 14 32 02

### To Reproduce

1. Create a question from a table that has a lot of rows (more than 10.000)

Either in editor mode or visualiser mode:
2. Apply 2 filters on a same column with parameter "Is" or "Is not"
3. Apply a third filter with "Is" or "Is not"
4. See the UI failing to display any data and not applying the later filter

### Expected behavior

I expect to be able to add as many filters I want to a same column.

### Logs

```
[a76dbbcd-e5eb-4647-9e35-862bcc736a63] 2024-03-27T14:42:27+01:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: 400 Bad Request
POST https://www.googleapis.com/bigquery/v2/projects/<project_name>/queries
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Cannot query over table 'datawarehouse.table_name' without a filter over column(s) 'dt' that can be used for partition elimination",
      "reason": "invalidQuery"
    }
  ],
  "message": "Cannot query over table 'datawarehouse.table_name' without a filter over column(s) 'dt' that can be used for partition elimination",
  "status": "INVALID_ARGUMENT"
}
{:database_id 2,
 :started_at #t "2024-03-27T13:42:27.200380860Z[Etc/UTC]",
 :via
 [{:status :failed,
   :class com.google.cloud.bigquery.BigQueryException,
   :error
   "Cannot query over table 'datawarehouse.table_name' without a filter over column(s) 'dt' that can be used for partition elimination",
   :stacktrace
   ["com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:114)"
    "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:728)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1358)"
    "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1355)"
    "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)"
    "com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)"
    "com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)"
    "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1354)"
    "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1342)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__128578.invoke(bigquery_cloud_sdk.clj:343)"]}
  {:status :failed,
   :class java.util.concurrent.ExecutionException,
   :error
   "com.google.cloud.bigquery.BigQueryException: Cannot query over table 'datawarehouse.table_name' without a filter over column(s) 'dt' that can be used for partition elimination",
   :stacktrace
   ["java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)"
    "java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)"
    "clojure.core$deref_future.invokeStatic(core.clj:2317)"
    "clojure.core$future_call$reify__8544.deref(core.clj:7042)"
    "clojure.core$deref.invokeStatic(core.clj:2337)"
    "clojure.core$deref.invoke(core.clj:2323)"
    "--> driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:331)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:327)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:371)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:369)"
    "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_$thunk__128622.invoke(bigquery_cloud_sdk.clj:419)"
    "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:427)"
    "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_.invoke(bigquery_cloud_sdk.clj:412)"
    "driver.bigquery_cloud_sdk$fn__128629.invokeStatic(bigquery_cloud_sdk.clj:448)"
    "driver.bigquery_cloud_sdk$fn__128629.invoke(bigquery_cloud_sdk.clj:440)"
    "query_processor.context$executef.invokeStatic(context.clj:60)"
    "query_processor.context$executef.invoke(context.clj:49)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
    "query_processor.context.default$default_runf.invoke(default.clj:42)"
    "query_processor.context$runf.invokeStatic(context.clj:46)"
    "query_processor.context$runf.invoke(context.clj:40)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___71992.invoke(cache.clj:229)"
    "query_processor.middleware.permissions$check_query_permissions$fn__66378.invoke(permissions.clj:140)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__71813.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__71823.invoke(enterprise.clj:64)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71255.invoke(mbql_to_native.clj:24)"
    "query_processor$fn__73137$combined_post_process__73142$combined_post_process_STAR___73143.invoke(query_processor.clj:262)"
    "query_processor$fn__73137$combined_pre_process__73138$combined_pre_process_STAR___73139.invoke(query_processor.clj:259)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66475.invoke(fetch_source_query.clj:303)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71903$fn__71907.invoke(resolve_database_and_driver.clj:77)"
    "driver$do_with_driver.invokeStatic(driver.clj:97)"
    "driver$do_with_driver.invoke(driver.clj:92)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71903.invoke(resolve_database_and_driver.clj:76)"
    "query_processor.middleware.store$initialize_store$fn__67081$fn__67082.invoke(store.clj:14)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.middleware.store$initialize_store$fn__67081.invoke(store.clj:13)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__71900.invoke(resolve_database_and_driver.clj:60)"
    "query_processor.middleware.normalize_query$normalize$fn__72205.invoke(normalize_query.clj:38)"
    "query_processor.middleware.enterprise$fn__71840$handle_audit_app_internal_queries__71841$fn__71843.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__71851.invoke(enterprise.clj:103)"
    "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__70966.invoke(constraints.clj:104)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__72136.invoke(process_userland_query.clj:156)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__72737.invoke(catch_exceptions.clj:171)"
    "query_processor.reducible$async_qp$qp_STAR___62625$thunk__62627.invoke(reducible.clj:126)"
    "query_processor.reducible$async_qp$qp_STAR___62625.invoke(reducible.clj:132)"
    "query_processor.reducible$sync_qp$qp_STAR___62637.doInvoke(reducible.clj:153)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
    "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
    "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
    "api.dataset$run_query_async$fn__93630.invoke(dataset.clj:79)"
    "query_processor.streaming$streaming_response_STAR_$fn__53145$fn__53147.invoke(streaming.clj:168)"
    "query_processor.streaming$streaming_response_STAR_$fn__53145.invoke(streaming.clj:167)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
    "async.streaming_response$do_f_async$task__43756.invoke(streaming_response.clj:88)"]}
  {:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error executing query: com.google.cloud.bigquery.BigQueryException: Cannot query over table 'datawarehouse.table_name' without a filter over column(s) 'dt' that can be used for partition elimination",
   :stacktrace
   ["--> driver.bigquery_cloud_sdk$throw_invalid_query.invokeStatic(bigquery_cloud_sdk.clj:323)"
    "driver.bigquery_cloud_sdk$throw_invalid_query.invoke(bigquery_cloud_sdk.clj:322)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:367)"
    "driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:327)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:371)"
    "driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:369)"
    "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_$thunk__128622.invoke(bigquery_cloud_sdk.clj:419)"
    "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:427)"
    "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_.invoke(bigquery_cloud_sdk.clj:412)"
    "driver.bigquery_cloud_sdk$fn__128629.invokeStatic(bigquery_cloud_sdk.clj:448)"
    "driver.bigquery_cloud_sdk$fn__128629.invoke(bigquery_cloud_sdk.clj:440)"
    "query_processor.context$executef.invokeStatic(context.clj:60)"
    "query_processor.context$executef.invoke(context.clj:49)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
    "query_processor.context.default$default_runf.invoke(default.clj:42)"
    "query_processor.context$runf.invokeStatic(context.clj:46)"
    "query_processor.context$runf.invoke(context.clj:40)"
    "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
    "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___71992.invoke(cache.clj:229)"
    "query_processor.middleware.permissions$check_query_permissions$fn__66378.invoke(permissions.clj:140)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__71813.invoke(enterprise.clj:51)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__71823.invoke(enterprise.clj:64)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71255.invoke(mbql_to_native.clj:24)"
    "query_processor$fn__73137$combined_post_process__73142$combined_post_process_STAR___73143.invoke(query_processor.clj:262)"
    "query_processor$fn__73137$combined_pre_process__73138$combined_pre_process_STAR___73139.invoke(query_processor.clj:259)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66475.invoke(fetch_source_query.clj:303)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71903$fn__71907.invoke(resolve_database_and_driver.clj:77)"
    "driver$do_with_driver.invokeStatic(driver.clj:97)"
    "driver$do_with_driver.invoke(driver.clj:92)"
    "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__71903.invoke(resolve_database_and_driver.clj:76)"
    "query_processor.middleware.store$initialize_store$fn__67081$fn__67082.invoke(store.clj:14)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
    "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
    "query_processor.middleware.store$initialize_store$fn__67081.invoke(store.clj:13)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__71900.invoke(resolve_database_and_driver.clj:60)"
    "query_processor.middleware.normalize_query$normalize$fn__72205.invoke(normalize_query.clj:38)"
    "query_processor.middleware.enterprise$fn__71840$handle_audit_app_internal_queries__71841$fn__71843.invoke(enterprise.clj:96)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__71851.invoke(enterprise.clj:103)"
    "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__70966.invoke(constraints.clj:104)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__72136.invoke(process_userland_query.clj:156)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__72737.invoke(catch_exceptions.clj:171)"
    "query_processor.reducible$async_qp$qp_STAR___62625$thunk__62627.invoke(reducible.clj:126)"
    "query_processor.reducible$async_qp$qp_STAR___62625.invoke(reducible.clj:132)"
    "query_processor.reducible$sync_qp$qp_STAR___62637.doInvoke(reducible.clj:153)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
    "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
    "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
    "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
    "api.dataset$run_query_async$fn__93630.invoke(dataset.clj:79)"
    "query_processor.streaming$streaming_response_STAR_$fn__53145$fn__53147.invoke(streaming.clj:168)"
    "query_processor.streaming$streaming_response_STAR_$fn__53145.invoke(streaming.clj:167)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
    "async.streaming_response$do_f_async$task__43756.invoke(streaming_response.clj:88)"],
   :error_type :invalid-query,
   :ex-data
   {:type :invalid-query,
    :sql
    "-- Metabase:: userID: 5 queryType: MBQL queryHash: ace1a8506501d6f6f047d0b9fc33731f15926d7a0b7c98cf503090c3aeb863a6\nSELECT <`table_name`.`column` AS `column` for all columns> LIMIT 2000",
    :parameters nil}}],
 :action_id nil,
 :error_type :invalid-query,
 :json_query
 {:database 2,
  :type "query",
  :query {:source-table 824},
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT <table_name.column AS column> LIMIT 1048575",
  :params nil,
  :table-name "table_name",
  :mbql? true},
 :status :failed,
 :class com.google.api.client.googleapis.json.GoogleJsonResponseException,
 :stacktrace
 ["com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest$3.interceptResponse(AbstractGoogleClientRequest.java:466)"
  "com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493)"
  "com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603)"
  "com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:726)"
  "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1358)"
  "com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1355)"
  "com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)"
  "com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)"
  "com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)"
  "com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1354)"
  "com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1342)"
  "--> driver.bigquery_cloud_sdk$execute_bigquery$fn__128578.invoke(bigquery_cloud_sdk.clj:343)"],
 :card_id nil,
 :context :ad-hoc,
 :error
 "400 Bad Request\nPOST https://www.googleapis.com/bigquery/v2/projects/<project_name>/queries\n{\n  \"code\": 400,\n  \"errors\": [\n    {\n      \"domain\": \"global\",\n      \"location\": \"q\",\n      \"locationType\": \"parameter\",\n      \"message\": \"Cannot query over table 'datawarehouse.table_name' without a filter over column(s) 'dt' that can be used for partition elimination\",\n      \"reason\": \"invalidQuery\"\n    }\n  ],\n  \"message\": \"Cannot query over table 'datawarehouse.table_name' without a filter over column(s) 'dt' that can be used for partition elimination\",\n  \"status\": \"INVALID_ARGUMENT\"\n}",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 2,
  :type :query,
  :query
  {:source-table 824,
   :fields
   [[:field 15900 nil]
    [:field 15918 nil]
    [:field 15934 nil]
    [:field 15932 nil]
    [:field 15892 nil]
    [:field 15920 nil]
    [:field 15904 nil]
    [:field 15895 nil]
    [:field 21987 nil]
    [:field 15891 nil]
    [:field 21986 nil]
    [:field 15901 nil]
    [:field 15924 nil]
    [:field 15928 nil]
    [:field 15903 nil]
    [:field 15935 nil]
    [:field 15908 nil]
    [:field 33357 nil]
    [:field 15939 nil]
    [:field 15888 {:temporal-unit :default}]
    [:field 15905 {:temporal-unit :default}]
    [:field 15912 {:temporal-unit :default}]
    [:field 15926 nil]
    [:field 15938 nil]
    [:field 15890 nil]
    [:field 15907 nil]
    [:field 15936 nil]
    [:field 15931 nil]
    [:field 15927 nil]
    [:field 15937 nil]
    [:field 15898 nil]
    [:field 15933 nil]
    [:field 15915 nil]
    [:field 15911 nil]
    [:field 15917 nil]
    [:field 15930 nil]
    [:field 22888 nil]
    [:field 15916 nil]
    [:field 16817 nil]
    [:field 18897 nil]
    [:field 20900 nil]
    [:field 20901 nil]
    [:field 20902 nil]
    [:field 20741 nil]
    [:field 20742 {:temporal-unit :default}]
    [:field 27000 nil]
    [:field 30181 nil]
    [:field 27643 nil]
    [:field 27642 nil]
    [:field 27641 nil]
    [:field 27644 nil]
    [:field 27640 nil]
    [:field 31069 nil]
    [:field 30184 nil]
    [:field 30182 nil]
    [:field 31070 nil]
    [:field 15897 nil]
    [:field 15910 nil]
    [:field 15894 nil]
    [:field 15923 nil]
    [:field 15913 nil]
    [:field 15941 nil]
    [:field 15906 nil]
    [:field 15899 nil]
    [:field 15889 nil]
    [:field 15887 nil]
    [:field 15929 nil]
    [:field 15896 nil]
    [:field 15921 nil]
    [:field 15909 nil]
    [:field 15925 nil]
    [:field 15940 nil]
    [:field 15886 nil]
    [:field 15914 nil]
    [:field 15893 nil]
    [:field 15919 nil]
    [:field 15922 nil]
    [:field 21511 nil]
    [:field 30183 nil]
    [:field 30185 nil]
    [:field 15902 {:temporal-unit :default}]],
   :limit 1048575,
   :metabase.query-processor.middleware.limit/original-limit nil},
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info {:executed-by 5, :context :ad-hoc}},
 :data {:rows [], :cols []}}
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.10+7-Debian-1deb12u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-17",
    "java.version": "17.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.10+7-Debian-1deb12u1",
    "os.name": "Linux",
    "os.version": "6.1.58+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v0.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking some users

### Additional context

Looking at the logs it seems that there's an issue with inferring the partitionning on our "dt" column even though there's an existing filter on dt = last 48 months given prior the bug occurs.

### PR DESCRIPTION
**Pull request by qnkhuat**
Recently, we added the ability to sync field values for tables that require a bigquery filter (epic: https://github.com/metabase/metabase/issues/36668). For these tables, each will have `metabase_table.database_require_filter = True`, and one of its fields will have `metabase_field.database_partitioned = True`. 

In https://github.com/metabase/metabase/pull/37102 we updated the query to fetch field values to include a dummy filter for these tables but we didn't update the chain filter path. This PR will do that.

Note for reviewers: The main changes are in `metabase.api.field` and `metabase.db.metadata_queries`.The rest are just changes so we can avoid using classloader in https://github.com/metabase/metabase/pull/40767/files#diff-b28eaae7ad5ee9389359e276833936958b869f4e239e8b2c4adb76078562bed9L346-L348. 

Closes https://github.com/metabase/metabase/issues/40673
Ref: https://github.com/metabase/metabase/issues/36668

### CODE REVIEW

File: src/metabase/api/field.clj [hunk 1]
```diff
@@ -351,26 +351,6 @@
     (t2/select-one Field :id fk-target-field-id)
     field))
 
-(defn- search-values-query
```
Comment (qnkhuat) [inline src/metabase/api/field.clj:354]: moved to `src/metabase/db/metadata_queries.clj`

File: src/metabase/models/field_values.clj [hunk 2]
```diff
@@ -343,9 +343,8 @@
   FieldValues. You most likely should not be using this directly in code outside of this namespace, unless it's for a
   very specific reason, such as certain cases where we fetch ad-hoc FieldValues for GTAP-filtered Fields.)"
   [field]
-  (classloader/require 'metabase.db.metadata-queries)
```
Comment (qnkhuat) [inline src/metabase/models/field_values.clj:346]: yay!

File: src/metabase/models/table.clj [hunk 3]
```diff
@@ -239,14 +237,14 @@
...
   [table]
-  (t2/select-one Database :id (:db_id table)))
+  (t2/select-one :model/Database :id (:db_id table)))
 
 ;;; ------------------------------------------------- Serialization -------------------------------------------------
 (defmethod serdes/dependencies "Table" [table]
   [[{:model "Database" :id (:db_id table)}]])
 
 (defmethod serdes/generate-path "Table" [_ table]
-  (let [db-name (t2/select-one-fn :name 'Database :id (:db_id table))]
```
Comment (crisptrutski) [inline src/metabase/models/table.clj:249]: Given that `Database` was in scope, I'm wondering why it was quoted before 😕

File: src/metabase/db/metadata_queries.clj [hunk 4]
```diff
@@ -36,39 +36,47 @@
...
-    (update query :filter (fn [existing-filter]
-                            (if (some? existing-filter)
-                              [:and existing-filter filter-form]
-                              filter-form)))))
+(defn add-required-filter-if-needed
+  "Add a dummy filter for tables that require a filters.
+  Look into tables from source tables and all the joins.
+  Currently this only apply to partitioned tables on bigquery that requires a partition filter."
+  [query]
+  (let [table-ids              (->> (conj (keep :source-table (:joins query)) (:source-table query))
```
[the remark this answers is not in the document]
Comment (calherries) [reply src/metabase/db/metadata_queries.clj:44]: OTOH there's a ton of stuff in this namespace that is not MLv2. Hmmm maybe leave it for now.

File: src/metabase/db/metadata_queries.clj [hunk 5]
```diff
@@ -36,39 +36,47 @@
...
+                                (if (some? existing-filter)
+                                  [:and existing-filter new-filter]
+                                  new-filter))]
+    (case (count required-filter-fields)
+      0
+      query
+      1
+      (update query :filter update-query-filter-fn (partition-field->filter-form (first required-filter-fields)))
+      ;; > 1
+      (update query :filter update-query-filter-fn (into [:and] (map partition-field->filter-form required-filter-fields))))))
```
Comment (calherries) [inline src/metabase/db/metadata_queries.clj:66]: hmm this could be simpler if you modified `update-query-filter-fn` to take a list, like this
```suggestion
      (update query :filter (fn [existing-filter new-filters]
                              (-> [:and] (into new-filters) (into existing-filter)))
        (map partition-field->filter-form required-filter-fields)))))
```
and then you could use `(cond-> query (seq required-filter-fields) (update ...))` instead of the `case` expression

File: src/metabase/db/metadata_queries.clj [hunk 6]
```diff
@@ -36,39 +36,47 @@
...
-    (:database_require_filter table)
-    (query-with-default-partitioned-field-filter (:id table))))
-
-(defn- field-query [{table-id :table_id} mbql-query]
+  (-> mbql-query
+      (assoc :source-table (:id table))
+      ;; Some table requires a filter to be able to query the data
+      ;; Currently this only applied to Partitioned table in bigquery where the partition field
+      ;; is required as a filter.
+      ;; In the future we probably want this to be dispatched by database engine type
```
Comment (calherries) [inline src/metabase/db/metadata_queries.clj:75]: Since you've moved the logic for whether we need a filter or not into `add-required-filter-if-needed`, I think this comment could just be part of its docstring. You've duplicated some of what it says already, so I'd suggest DRYing it up and removing this comment so it doesn't risk getting out of date

File: src/metabase/db/metadata_queries.clj [hunk 7]
```diff
@@ -104,6 +112,24 @@
    (field-query field {:breakout [[:field (u/the-id field) nil]]
                        :limit    (min max-results absolute-max-distinct-values-limit)})))
 
+;; TODO this function and field-distinct-values should be in metabase.models.field-values
```
Comment (calherries) [inline src/metabase/db/metadata_queries.clj:115]: Why did you leave this todo? You just moved this function here so I'm puzzled why there would be a TODO to move it somewhere else. If there's a reason why this is hard, maybe leave it in a comment so the next guy that reads this isn't puzzled either

File: src/metabase/db/metadata_queries.clj [hunk 8]
```diff
@@ -36,39 +36,47 @@
...
-                                           {:order-by [[:name :asc]]})
-                            (throw (ex-info (format "No partitioned field found for table: %d" table-id)
-                                            {:table_id table-id})))
-        filter-form     (partition-field->filter-form partition-field)]
-    (update query :filter (fn [existing-filter]
-                            (if (some? existing-filter)
-                              [:and existing-filter filter-form]
-                              filter-form)))))
+(defn add-required-filter-if-needed
+  "Add a dummy filter for tables that require a filters.
```
Comment (calherries) [inline src/metabase/db/metadata_queries.clj:40]: I think this name misleads a bit, because it can add multiple "filters"
```suggestion
(defn add-required-filters-if-needed
  "Add a dummy filters for tables that require filters.
```

File: test/metabase/db/metadata_queries_test.clj [hunk 9]
```diff
@@ -99,3 +99,31 @@
...
+           (is (= (assoc query
+                         :filter [:> [:field (:id order-product-id) {:base-type :type/Integer}] -9223372036854775808])
+                  (metadata-queries/add-required-filter-if-needed query)))))
+       (testing "if a joined table require a filter, add the partitioned filter"
+         (let [query (:query (mt/mbql-query product {:joins [{:source-table (:id order)
+                                                              :condition    [:= $order.product_id $product.id]
+                                                              :alias        "Product"}]}))]
+           (is (= (assoc query
+                         :filter [:> [:field (:id order-product-id) {:base-type :type/Integer}] -9223372036854775808])
+                  (metadata-queries/add-required-filter-if-needed query)))))))))
```
Comment (calherries) [inline test/metabase/db/metadata_queries_test.clj:129]: since the code now handles it, wdyt about covering these additional test cases:
1. a query that has multiple source tables that need dummy filters
2. a query that already has a filter, that has a source table that needs dummy filters

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj [hunk 10]
```diff
@@ -419,6 +419,105 @@
...
+            (drop-table-if-exists! partitioned-table))))))))
+
+(deftest chain-filter-with-fields-from-table-requires-a-filter-test
+  (testing "#40673"
+    (mt/test-driver :bigquery-cloud-sdk
+      (mt/with-model-cleanup [:model/Table]
+        (let [category-table-name "cf_category"
+              product-table-name  "cf_product"]
+          (try
+           (doseq [sql [(format "CREATE TABLE %s (id INT64, category STRING, PRIMARY KEY(id) NOT ENFORCED)
```
Comment (calherries) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:453]: `try` and `finally` have two-spaces for indentation
```suggestion
            (doseq [sql [(format "CREATE TABLE %s (id INT64, category STRING, PRIMARY KEY(id) NOT ENFORCED)
```

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj [hunk 11]
```diff
@@ -419,6 +419,105 @@
...
+               (is (= {:has_more_values false
+                       :values          [["Americano"] ["Cold brew"] ["Herbal"] ["Oolong"]]}
+                      (mt/user-http-request :crowberto :get 200 (format "/dashboard/%d/params/%s/values" (:id dashboard) "_NAME_")))))
+             (testing "searching values works"
+               (is (= {:has_more_values false
+                       :values          [["Oolong"]]}
+                      (mt/user-http-request :crowberto :get 200 (format "/dashboard/%d/params/%s/search/oo" (:id dashboard) "_NAME_"))))))
+
+           (finally
+            (doseq [table-name [product-table-name category-table-name]]
```
Comment (calherries) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:518]:
```suggestion
             (doseq [table-name [product-table-name category-table-name]]
```

**Review by calherries — APPROVED** [review]
Nice. I'm happy with this as long as you fix the MySQL test failures and we get more test coverage, see [this comment](https://github.com/metabase/metabase/pull/40767#discussion_r1548103717)

File: src/metabase/db/metadata_queries.clj (hunk 5 above)
Comment (qnkhuat) [reply src/metabase/db/metadata_queries.clj:66]: that's what I did at first. I changed to `case` because I don't want to add a `:and` if there is only one filter.

File: src/metabase/db/metadata_queries.clj (hunk 4 above)
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/db/metadata_queries.clj:45]: yea mlv2 would be nice. but I need to back port this and I don't want to complicate it too much.

File: src/metabase/models/table.clj (hunk 3 above)
Comment (qnkhuat) [reply src/metabase/models/table.clj:249]: yea I think sometimes you just used to the quick way so you don't check whether Database was required :p

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj (hunk 11 above)
Comment (qnkhuat) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj]: fixed in 5fbe2e50a90f2217d92b646057feb89ef4435c83, and also fixed my config

File: test/metabase/db/metadata_queries_test.clj (hunk 9 above)
Comment (qnkhuat) [reply test/metabase/db/metadata_queries_test.clj]: added in 5fbe2e50a90f2217d92b646057feb89ef4435c83,

**Comment by qnkhuat** [comment]
@calherries added some tests, could you take another look?

File: src/metabase/db/metadata_queries.clj (hunk 5 above)
Comment (calherries) [reply src/metabase/db/metadata_queries.clj:67]: fair, both approaches have their downsides. If you really care about the extra `:and` I guess you could use this function to remove it, but then we're talking very marginal gains in having less code

```
(defn remove-extra-and [[_and & args :as clause]]
  (if (= 1 (count args))) args clause))
```

**Review by calherries — APPROVED** [review]
Great! Thanks for adding the extra tests

edit: looks like a legit failure in CI though: `chain-filter-with-fields-from-table-requires-a-filter-test`

**Comment by qnkhuat** [comment]
the fix is in https://github.com/metabase/metabase/pull/40767/commits/66432f4e13b854f7234a71d4874a6c944ffd8086, it's a test setup thingy. not an actually failure.
