### PR TITLE
Delete invalid `source-card-id`s on native SQL questions

### LINKED ISSUE #68080: Questions converted in SQL should not be deleted when the previous parent model gets deleted
### Describe the bug

We just permanently lost 130 important Metabase questions by just removing an old unused database from Metabase. It took us some time to debug what the issue was, as the delete window from the database warned us about 17 questions and 37 models, all unused for a long time upon checking directly inside the metabase database.

Image

The 17 questions + 37 models were unused. An additional 130 questions got removed without warning due to their persistent link with one of the 37 removed model, even if they were de facto logically no longer linked.

### To Reproduce

- Create a random model, and save it. It will get an assigned ID.
- Create a question from that model, eg. using the summarize function and save it. It will get the assigned ID + 1.
- Convert that question to SQL, and write whatever you want in it. Fully overwrite it. You can even change the database source, which is what we did a long time ago. The UI does not indicate anywhere that the question is still bounded with the parent model in the database.
- Delete the model permanently, from the trash. Check in the database, in the report_card table. Both ID disappeared, although the question now had nothing to do with the model. That is because, even if the question got converted to SQL, it kept the model ID in the source_card_id column, which has an ON DELETE CASCADE property.

If you change the database source, attempt to remove the original from Metabase, on which the model is based. The count of deleted questions will NOT include the one that you derived from the model. This is a severe data loss risk!

### Expected behavior

As soon as the question is converted to SQL, source_card_id should immediately become NULL for that question. 

And if not for some reason, it should count towards the displayed number of questions to be deleted when removing the database. A fair warning would also be appreciated when deleting the model alone!

This issue has been here for at least a very long time.

### Logs

No need for logs as it is systematically reproducible.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.2 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-12-19",
      "tag": "v0.57.7.5",
      "hash": "b7e9d0a"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "18.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.9+10-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.9+10-LTS",
    "os.name": "Linux",
    "os.version": "6.8.0-88-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

HIGH

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by galdre**
Closes https://github.com/metabase/metabase/issues/68080

### Description

When a user creates a question based on a model, `source_card_id` is set to the model's ID. If that question is later converted to native SQL, `source_card_id` doesn't get cleared. This means that deleting the model will cause the question to be deleted even though they no longer have any relationship to one another.

The code fix won't help anyone who has already got incorrect data, so we have a migration to correct the inconsistent data. I added an assertion to the t2 hook to catch this at dev time in the future. And ultimately, the delete cascade seems overkill, so there's a migration to replace that with SET NULL instead.

### How to verify

Easy reproduction steps in original issue.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/queries/models/card.clj [hunk 1]
```diff
@@ -338,27 +338,27 @@
...
+   ;; mega HACK FIXME -- don't update this stuff when doing deserialization because it might differ from what's in the
+   ;; YAML file and break tests like [[metabase-enterprise.serialization.v2.e2e.yaml-test/e2e-storage-ingestion-test]].
+   ;; The root cause of this issue is that we're generating Cards that have a different Database ID or Table ID from
+   ;; what's actually in their query -- we need to fix [[metabase.test.generate]], but I'm not sure how to do that
+   (when (and (seq query)
+              (map? query)
+              (not mi/*deserializing?*))
      (merge
-      (when-let [source-id (source-card-id query)]
-        {:source_card_id source-id})
```
Comment (galdre) [inline src/metabase/queries/models/card.clj:344]: A more conservative change would be to keep this `when-let` guard (I'm a little leary, not knowing why it was there), and instead just add additional logic that ensures it's `nil` if the dataset_query is native.

File: resources/migrations/059_update_migrations.yaml [hunk 2]
```diff
@@ -240,6 +240,57 @@ databaseChangeLog:
...
+            constraintName: fk_report_card_source_card_id_ref_report_card_id
+      rollback:
+        - addForeignKeyConstraint:
+            baseTableName: report_card
+            baseColumnNames: source_card_id
+            referencedTableName: report_card
+            referencedColumnNames: id
+            constraintName: fk_report_card_source_card_id_ref_report_card_id
+            nullable: true
+            deleteCascade: true
```
Comment (metamben) [inline resources/migrations/059_update_migrations.yaml:274]: don't we want to revise the other cascades? I could argue against some of them more strongly than against this one.

File: test/metabase/queries/models/card_test.clj [hunk 3]
```diff
@@ -1057,6 +1057,55 @@
...
+  (testing "deleting a model should not cascade delete questions that were converted to native SQL"
+    (mt/with-temp [:model/Card model {:name          "Test Model"
+                                      :type          :model
+                                      :dataset_query (mt/mbql-query venues)}
+                   :model/Card question {:name          "Test Question"
+                                         :dataset_query {:database (mt/id)
+                                                         :type     :query
+                                                         :query    {:source-table (str "card__" (:id model))}}}]
+      (let [question-id (:id question)
+            model-id    (:id model)]
```
Comment (rileythomp) [inline test/metabase/queries/models/card_test.clj]: more of an fyi than a nit even: You can get the IDs from `mt/with-temp` like
```clojure
(mt/with-temp [:model/Card {model-id :id} {
```

File: test/metabase/queries/models/card_test.clj [hunk 4]
```diff
@@ -1057,6 +1057,55 @@
...
+        (testing "source_card_id is initially set to the model's ID"
+          (is (= model-id (:source_card_id (t2/select-one :model/Card :id question-id)))))
+        (testing "source_card_id is cleared when converting to native SQL"
+          (t2/update! :model/Card question-id
+                      {:dataset_query {:database (mt/id)
+                                       :type     :native
+                                       :native   {:query "SELECT * FROM venues"}}})
+          (is (nil? (:source_card_id (t2/select-one :model/Card :id question-id))))))))
```
Comment (metamben) [inline test/metabase/queries/models/card_test.clj]: I think `:id` is the default, it can be omitted.

**Review by metamben — APPROVED** [review]

**Review by rileythomp — APPROVED** [review]

File: resources/migrations/059_update_migrations.yaml (hunk 2 above)
Comment (galdre) [reply resources/migrations/059_update_migrations.yaml:274]: I didn't even look at any other cascades. Is it something you think we should do now? I'm inclined to put that in a separate PR.

File: test/metabase/queries/models/card_test.clj (hunk 3 above)
Comment (galdre) [reply test/metabase/queries/models/card_test.clj]: Thanks! I have seen that many times, I just forget it.
