### PR TITLE
Validate dashboard subscriptions [Fixes #14257]

### LINKED ISSUE #14257: Form validation on email dashboard subscriptions
**To Reproduce**
1. Go to a dashboard
2. Create a new email subscription
3. _Leave the email field blank_
4. Click "Done"

**Expected behavior**
Some sort of form validation message

** Actual behavior**
The sidebar goes blank and requires a refresh to be restored

**Screenshots**
Before:

image

After clicking "Done":

image

### PR DESCRIPTION
**Pull request by tsmacdonald**
Closes #14257

### CODE REVIEW

File: frontend/src/metabase/sharing/components/SharingSidebar.jsx [hunk 1]
```diff
@@ -709,6 +709,7 @@ class SharingSidebar extends React.Component {
           onClose={this.handleSave}
           onCancel={onCancel}
           className="text-dark"
+          closeIsDisabled={!pulseIsValid(pulse, formInput.channels)}
```
Comment (kdoh) [inline frontend/src/metabase/sharing/components/SharingSidebar.jsx:712]: @tsmacdonald Mind giving a little color on how this prop and the `Done` button relate?

Comment (tsmacdonald) [reply frontend/src/metabase/sharing/components/SharingSidebar.jsx:712]: The `Done` button auto-magically appears if `onClose` is set, and it will be disabled if `closeIsDisabled` is true. 

I totally just cargo-culted using it from the normal Pulse UI.

Comment (kdoh) [reply frontend/src/metabase/sharing/components/SharingSidebar.jsx:712]: Cool. That prop name is weird but I pulled the branch and everything seems to be working as expected. Might just add a quick code comment to help whoever comes along next decipher that a bit faster.

**Review by kdoh — APPROVED** [review]
