### PR TITLE
Fix SSO failed to sync admin group

### LINKED ISSUE #13820: Cannot map users to Admin group
**Describe the bug**
In the UI for group mappings for SAML/JWT/LDAP SSO authentication:
> Membership to the Admin group can be granted through mappings, but will not be automatically removed as a failsafe measure.

But when selecting the Admin group, then it has no effect during the login process, so the user never gets Admin access, only the regular groups are correctly assigned to the user.
image

**Expected behavior**
Should have the ability to map users to the Admin group.

**Information about your Metabase Installation:**
Metabase x.37.2
Reference: https://github.com/metabase/metabase-enterprise/issues/445 EE445

### PR DESCRIPTION
**Pull request by qnkhuat**
Closes #13820
We used to have an option to disable sync admin user using group mappings, but it's both not working and not needed, so in this PR we make sync for admin groups just like a _normal_ group.

Product doc: https://www.notion.so/metabase/Overhaul-SSO-admin-group-sync-3b02520bc4e74fa19f7e40464a23dda6

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/enhancements/integrations/ldap.clj [hunk 1]
```diff
@@ -30,11 +30,6 @@
   :default "userPassword,dn,distinguishedName"
   :type    :csv)
 
-(defsetting ldap-sync-admin-group
```
Comment (qnkhuat) [inline enterprise/backend/src/metabase_enterprise/enhancements/integrations/ldap.clj:33]: by removing this, it'll also remove this option on Frontend because the front end displays a list of settings returned by the backend.

File: src/metabase/integrations/ldap/default_implementation.clj [hunk 2]
```diff
@@ -145,9 +145,9 @@
                        (assoc :is_active true)))]
     (u/prog1 new-user
       (when sync-groups?
-        (let [group-ids   (ldap-groups->mb-group-ids groups settings)
+        (let [group-ids            (ldap-groups->mb-group-ids groups settings)
               all-mapped-group-ids (all-mapped-group-ids settings)]
-          (integrations.common/sync-group-memberships! new-user group-ids all-mapped-group-ids false))))))
```
Comment (qnkhuat) [inline src/metabase/integrations/ldap/default_implementation.clj:150]: here is the only part that is actually changed in this file, the rest are indentation.

File: test_resources/ldap.ldif [hunk 3]
```diff
@@ -40,10 +40,10 @@ objectClass: person
 objectClass: organizationalPerson
 objectClass: inetOrgPerson
 cn: Fred Taylor
-sN: Taylor
```
Comment (noahmoss) [inline test_resources/ldap.ldif:43]: I believe these were intentional, to test that attributes are case-insensitive.

It seems that LDIF supports comments, so maybe it would be worth leaving a comment here about that.

File: enterprise/backend/src/metabase_enterprise/enhancements/integrations/ldap.clj (hunk 1 above)
Comment (noahmoss) [reply enterprise/backend/src/metabase_enterprise/enhancements/integrations/ldap.clj:33]: We have a list of `retired-setting-names` in `metabase.models.setting` that ensures that setting names aren't reused after they are removed (in case values are still lingering in DBs). Could you add this there?

**Review by noahmoss — COMMENTED** [review]
The SSO changes mostly look good, just some minor comments. And it seems like one of the tests is failing on CI.

I think @camsaul should take a look at the migration stuff because I don't have full context about what kind of issues we can run into with Clojure-land migrations, and whether this will solve them in this case.

File: enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj [hunk 4]
```diff
@@ -62,11 +62,10 @@
   [user jwt-data]
   (when (sso-settings/jwt-group-sync)
     (when-let [groups-attribute (jwt-attribute-groups)]
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj:64]: you mean `groups-attribute` ? it was not before so I changed it to use it instead of calling `(jwt-attribute-groups)` again.

File: src/metabase/db/data_migrations.clj [hunk 5]
```diff
@@ -172,6 +204,34 @@
...
+(defmigration ^{:author "qnkhuat" :added "0.43.0" :data-migration-index 1} migrate-remove-admin-from-group-mapping-if-needed
+  ;;  In the past we have a setting to disable group sync for admin group when using SSO or LDAP, but it's broken and haven't really worked (see #13820)
+  ;;  In #20991 we remove this option entirely and make sync for admin group just like a regular group.
+  ;;  But with this change we want to make sure we don't accidently add/remove adminusers we need to :
+  ;;  - for LDAP, if the `ldap-sync-admin-group` is disabled, remove all mapping for admin group
+  ;;  - for SAML, JWT remove all mapping for admin group
+  (run-with-data-migration-index 1
+    (let [admin-group-id (u/the-id (group/admin))]
+      (when (= "false" (db/select-one-field :value Setting :key "ldap-sync-admin-group"))
+        (remove-group-id-from-mappings-by-setting-key :ldap-group-mappings admin-group-id))
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/db/data_migrations.clj:231]: not sure where I got it wrong? it's [2 spaces for a body indentation](https://github.com/bbatsov/clojure-style-guide#body-indentation)

File: src/metabase/integrations/ldap.clj [hunk 6]
```diff
@@ -87,9 +87,10 @@
 
                (map? new-value)
                (do (doseq [k (keys new-value)]
-                     (when-not (DN/isValidDN (name k))
+                     (when-not (DN/isValidDN (if (keyword? k) (name k) (str k)))
                        (throw (IllegalArgumentException. (tru "{0} is not a valid DN." (name k))))))
-                   (setting/set-value-of-type! :json :ldap-group-mappings new-value)))))
+                   ;; except both key with type str and DN.
+                   (setting/set-value-of-type! :json :ldap-group-mappings (into {} (map (fn [[k v]] [(str k) v]) new-value)))))))
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/integrations/ldap.clj:93]: some time  we want to call `setting/set-value-of-type!` for ldap-group-mappings with they is a `DN.` instance, not a keyword. This changes make sure we allow to have both.

I'll add some comments for it

File: src/metabase/db/data_migrations.clj [hunk 7]
```diff
@@ -172,6 +204,34 @@
...
+
+(defmigration ^{:author "qnkhuat" :added "0.43.0" :data-migration-index 1} migrate-remove-admin-from-group-mapping-if-needed
+  ;;  In the past we have a setting to disable group sync for admin group when using SSO or LDAP, but it's broken and haven't really worked (see #13820)
+  ;;  In #20991 we remove this option entirely and make sync for admin group just like a regular group.
+  ;;  But with this change we want to make sure we don't accidently add/remove adminusers we need to :
+  ;;  - for LDAP, if the `ldap-sync-admin-group` is disabled, remove all mapping for admin group
+  ;;  - for SAML, JWT remove all mapping for admin group
+  (run-with-data-migration-index 1
+    (let [admin-group-id (u/the-id (group/admin))]
+      (when (= "false" (db/select-one-field :value Setting :key "ldap-sync-admin-group"))
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/db/data_migrations.clj:230]: good catch! I'll add those checks

File: enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj (hunk 4 above)
[the remark this answers is not in the document]
Comment (noahmoss) [reply enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj:64]: yeah, you could move the `(jwt-attribute-groups)` call to be inline since that's the only place we need to use the results. But that's mostly just a stylistic thing, up to you

File: src/metabase/db/data_migrations.clj [hunk 8]
```diff
@@ -32,18 +63,22 @@
...
-        (catch Exception e
-          (if catch?
-            (log/warn (format "Data migration %s failed: %s" migration-name (.getMessage e)))
-            (throw e))))
+       (db/transaction
+        (@migration-var))
+       (catch Exception e
+         (if catch?
+           (log/warn (format "Data migration %s failed: %s" migration-name (.getMessage e)))
+           (throw e))))
```
Comment (qnkhuat) [inline src/metabase/db/data_migrations.clj:71]: run each data-migration within a transaction

File: src/metabase/db/data_migrations.clj [hunk 9]
```diff
@@ -19,6 +26,30 @@
...
+  Useful when we need to enforce a data-migration to only run once when upgrading Metabase.
+
+  When defining a new data migration, make sure the `data-migration-index` is incremented from the last data-migration,
+  otherwise the migration will be skipped even when upgrading Metabase.
+  After running migration successfully, `data-migration-index` will be automatically updated"
+  {:style/indent 1}
+  [data-migration-index & body]
+  `(when (should-run-data-migration? ~data-migration-index)
+    ~@body
+    (setting/set-value-of-type! :integer :data-migration-index ~data-migration-index)))
```
Comment (qnkhuat) [inline src/metabase/db/data_migrations.clj:51]: this is the main changes that related to the introduction of `data-migration-index` setting.
Please check the PR's description for more info.

File: test/metabase/db/data_migrations_test.clj [hunk 10]
```diff
@@ -331,3 +339,137 @@
...
+        (is (= 42 @meaning-of-life))
+        (is (= 2 (setting/get :data-migration-index)))))
+
+    (testing "should run if current data-migration-index even if current data-migration-index is nil"
+      (mt/with-temporary-setting-values
+        [data-migration-index nil]
+        (reset! meaning-of-life nil)
+        (what-is-the-meaning-of-life?)
+        (is (= 42 @meaning-of-life))
+        (is (= 2 (setting/get :data-migration-index)))))))
```
Comment (qnkhuat) [inline test/metabase/db/data_migrations_test.clj:369]: Tests for `run-with-data-migration-index` macro

File: src/metabase/db/data_migrations.clj [hunk 11]
```diff
@@ -19,6 +26,30 @@
...
+  Useful when we need to enforce a data-migration to only run once when upgrading Metabase.
+
+  When defining a new data migration, make sure the `data-migration-index` is incremented from the last data-migration,
+  otherwise the migration will be skipped even when upgrading Metabase.
+  After running migration successfully, the `data-migration-index` will be automatically updated"
+  {:style/indent 1}
+  [data-migration-index & body]
+  `(when (should-run-data-migration? ~data-migration-index)
+    ~@body
+    (setting/set-value-of-type! :integer :data-migration-index ~data-migration-index)))
```
Comment (qnkhuat) [inline src/metabase/db/data_migrations.clj:51]: This is the main change that related to the introduction of `data-migration-index` setting.

The purpose of this is to introduce a mechanism so that we could write a data-migration that is guaranteed to run once when customers upgrade Metabase.

The idea is we store an index in the `setting` table, whenever we need a data migration to run once, we define that migration with an index.
And whenever data-migrations is triggered, it will skip all data migration with an index lower than the index stored in the `setting` table.

File: src/metabase/models/permissions.clj [hunk 12]
```diff
@@ -130,13 +130,13 @@
   | Data perms? | Coll perms? | Block? | Segmented? | Can run? |
   | ----------- | ----------- | ------ | ---------- | -------- |
   |          no |          no |     no |         no |       ⛔ |
-  |          no |          no |     no |        yes |       ⚠ |
+  |          no |          no |     no |        yes |       ⚠  |
```
[the remark this answers is not in the document]
Comment (camsaul) [reply src/metabase/models/permissions.clj:133]: Good question I think I tried to use that but got this instead somehow

File: src/metabase/db/data_migrations.clj [hunk 13]
```diff
@@ -172,6 +177,39 @@
...
+        (into {}
+              (map (fn [[k v]] [k (filter #(not= admin-group-id %) v)]))
+              mapping)))))
+
+ (defmigration ^{:author "qnkhuat" :added "0.43.0"} migrate-remove-admin-from-group-mapping-if-needed
+   ;;  In the past we have a setting to disable group sync for admin group when using SSO or LDAP, but it's broken and haven't really worked (see #13820)
+   ;;  In #20991 we remove this option entirely and make sync for admin group just like a regular group.
+   ;;  But with this change we want to make sure we don't accidently add/remove adminusers we need to :
+   ;;  - for LDAP, if the `ldap-sync-admin-group` is disabled, remove all mapping for admin group
+   ;;  - for SAML, JWT remove all mapping for admin group
```
Comment (noahmoss) [inline src/metabase/db/data_migrations.clj:200]: Not a big deal, but I did some minor editing of this comment to make it a bit clearer (but feel free to edit further)

```suggestion
   ;;  But on upgrade, to make sure we don't unexpectedly begin adding or removing admin users:
   ;;  - for LDAP, if the `ldap-sync-admin-group` toggle is disabled, we remove all mapping for the admin group
   ;;  - for SAML, JWT, we remove all mapping for admin group, because they were previously never being synced
```

File: src/metabase/db/data_migrations.clj [hunk 14]
```diff
@@ -172,6 +177,39 @@
...
+   (let [admin-group-id (u/the-id (group/admin))]
```
Comment (noahmoss) [inline src/metabase/db/data_migrations.clj:201]: nit: maybe just have `remove-group-id-from-mappings-by-setting-key` take `admin-group` as an argument, and pull out the ID in that function when it's needed?

File: src/metabase/db/data_migrations.clj [hunk 15]
```diff
@@ -172,6 +177,39 @@
...
+     (when (and (ldap/ldap-configured?)
+                (= "false" (db/select-one-field :value Setting :key "ldap-sync-admin-group")))
+       (remove-group-id-from-mappings-by-setting-key :ldap-group-mappings admin-group-id))
+     ;; sso are enterprise feature, so only remove admin groups if enterprise available
+     (when (premium-features/enable-sso?)
```
Comment (noahmoss) [inline src/metabase/db/data_migrations.clj:206]: eh, I'm starting to think we should just run this logic for OSS instances too. maybe this is a super small edge case but if someone was running EE and set up an admin group mapping, then downgraded to OSS and ran this migration, then upgraded back to EE, we probably don't want to suddenly start syncing the admin group unless they add it again

File: src/metabase/db/data_migrations.clj [hunk 16]
```diff
@@ -172,6 +177,39 @@
...
+   [mapping-setting-key admin-group-id]
+   ;; Intentionally get setting using `db/select-one-field` instead of `setting/get` because for some reasons
+   ;; during start-up setting/get return the default value defined in defsetting instead of value from Setting table
+   (let [mapping (try
+                  (json/parse-string (db/select-one-field :value Setting :key (name mapping-setting-key)))
+                  (catch Exception _e
+                    {}))]
+     (when-not (empty? mapping)
+       (setting/set-value-of-type!
+        :json mapping-setting-key
```
Comment (noahmoss) [inline src/metabase/db/data_migrations.clj:190]: nit: args should probably be on separate lines here

File: src/metabase/integrations/common.clj [hunk 17]
```diff
@@ -12,21 +12,17 @@
 (defn sync-group-memberships!
   "Update the PermissionsGroups a User belongs to, adding or deleting membership entries as needed so that Users is
   only in `new-groups-or-ids`. Ignores special groups like `all-users`, and only touches groups with mappings set."
-  [user-or-id new-groups-or-ids mapped-groups-or-ids sync-admin-group?]
-  (let [included-group-ids (cond-> (set (map u/the-id mapped-groups-or-ids))
-                             sync-admin-group? (conj (u/the-id (group/admin))))
-        excluded-group-ids (cond-> #{(u/the-id (group/all-users))}
-                             (not sync-admin-group?) (conj (u/the-id (group/admin))))
+  [user-or-id new-groups-or-ids mapped-groups-or-ids]
+  (let [mapped-groups-ids  (set (map u/the-id mapped-groups-or-ids))
```
Comment (noahmoss) [inline src/metabase/integrations/common.clj:16]: nit: `mapped-group-ids`

File: src/metabase/integrations/common.clj [hunk 18]
```diff
@@ -12,21 +12,17 @@
...
+        excluded-group-ids #{(u/the-id (group/all-users))}
```
Comment (noahmoss) [inline src/metabase/integrations/common.clj:17]: since there's only one excluded group, might be clearer to get rid of this binding and just change the select statement to use `:not=`

File: src/metabase/integrations/ldap.clj [hunk 19]
```diff
@@ -86,10 +86,12 @@
                (recur (json/parse-string new-value))
 
                (map? new-value)
+               ;; keys of new-value could be string or instance of DN
+               ;; in either cases they will be converted to a string before storing
                (do (doseq [k (keys new-value)]
-                     (when-not (DN/isValidDN (name k))
+                     (when-not (DN/isValidDN (if (keyword? k) (name k) (str k)))
```
Comment (noahmoss) [inline src/metabase/integrations/ldap.clj:92]: if the keys can be strings or DN instances, why are you checking for `keyword?` here?

maybe it would be simpler to first normalize the keys in the map to strings, and then run the existing logic as-is?

File: src/metabase/integrations/ldap/default_implementation.clj [hunk 20]
```diff
@@ -64,12 +64,12 @@
...
   "Convert the result "
   [ldap-connection               :- LDAPConnectionPool
-   {:keys [dn uid], :as result} :- su/Map
+   {:keys [dn uid], :as result}  :- su/Map
    {:keys [first-name-attribute
            last-name-attribute
            email-attribute
            sync-groups?]
-    :as   settings}              :- i/LDAPSettings
+    :as settings}                :- i/LDAPSettings
```
Comment (noahmoss) [inline src/metabase/integrations/ldap/default_implementation.clj:72]: nit: `settings` should be in line with the map key above it

File: test/metabase/db/data_migrations_test.clj [hunk 21]
```diff
@@ -331,3 +339,107 @@
...
+(defn- call-with-ldap-configured [ldap-group-mapping f]
+  (mt/with-temporary-setting-values
+    [ldap-enabled          true
+     ldap-host             "http://localhost:8888"
+     ldap-user-base        "dc=metabase,dc=com"
+     ldap-group-mappings   ldap-group-mapping
+     ldap-sync-admin-group false]
+    (f)))
+
+(defmacro ^:private with-ldap-and-sso-configured
```
Comment (noahmoss) [inline test/metabase/db/data_migrations_test.clj:386]: Nice job getting all this stuff working, but especially given my comment above about running the SAML/JWT migration logic even on OSS instance, I think having SSO actually configured in these tests is overkill. 

You should be able to just set the `saml-enabled`/`jwt-enabled` setting to `true` directly in the DB, run the migration and check that stuff was updated correctly, then reset those settings to their prior value. Similar to what `with-temporary-setting-values` does, but I don't think you can use that directly here since those setting definitions live in EE code. (Although I'm not totally sure if that's an issue for using that helper or not)

**Review by noahmoss — CHANGES_REQUESTED** [review]
Really nice job, most of my comments are just nitpicks. But requesting changes because I think the JWT/SAML migration logic should be run on OSS instances as well, and the migration tests can be simplified significantly. Let me know if those comments make sense...if not I can try to explain better.

Also if you merge in the latest `master` it should fix those failing e2e tests.

File: test/metabase/db/data_migrations_test.clj [hunk 22]
```diff
@@ -331,3 +339,107 @@
...
+  v+zzpV2nLF4by0vSj7AHsubrsLgsCfV3JvJyTxCyo1aIOlv4Vrx7h9rOgl9eEmoU
+  5XJAl3D7DuvSTEOy7MyDnKF17m7l5nOPZCVOSzmCWvxSCyysijgsM5DSgAE8DPJy
+  oYezV3gTX2OO2QIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSp
+  B3lvrtbSDuXkB6fhbjeUpFmL2DAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQEL
+  BQADggEBAAEHGIAhR5GPD2JxgLtpNtZMCYiAM4Gr7hoTQMaKiXgVtdQu4iMFfbpE
+  wIr6UVaDU2HKhvSRFIilOjRGmCGrIzvJgR2l+RL1Z3KrZypI1AXKJT5pF5g5FitB
+  sZq+kiUpdRILl2hICzw9Q1M2Le+JSUcHcbHTVgF24xuzOZonxeE56Oc26Ju4CorL
+  pM3Nb5iYaGOlQ+48/GP82cLxlVyi02va8tp7KP03ePSaZeBEKGpFtBtEN/dC3NKO
+  1mmrT9284H0tvete6KLUH+dsS6bDEYGHZM5KGoSLWRr3qYlCB3AmAw+KvuiuSczL
+  g9oYBkdxlhK9zZvkjCgaLCen+0aY67A=")
```
Comment (camsaul) [inline test/metabase/db/data_migrations_test.clj:361]: The sure looks a lot like copy pasta from `metabase-enterprise.sso.integrations.saml-test`... please don't duplicate big things like this. Move it somewhere shared and have both the old stuff and the new stuff use it. Probably fine to put it in a file in `test_resources` and `slurp` it or something like that. Just no copy pasta please

File: src/metabase/models/permissions.clj (hunk 12 above)
[the remark this answers is not in the document]
Comment (camsaul) [reply src/metabase/models/permissions.clj:133]: FWIW I think the old formatting made more sense, it was basically `<character><space><vertical-pipe>` in every row. So in the future if we replaced all the `⚠` with the actual emoji `⚠️` everything would be misaligned. It only looks more aligned if you add the extra space if whatever you're looking at treats ⛔ and ✅ as being two spaces wide

File: src/metabase/db/data_migrations.clj [hunk 23]
```diff
@@ -172,6 +177,39 @@
...
+
+ (defmigration ^{:author "qnkhuat" :added "0.43.0"} migrate-remove-admin-from-group-mapping-if-needed
+   ;;  In the past we have a setting to disable group sync for admin group when using SSO or LDAP, but it's broken and haven't really worked (see #13820)
+   ;;  In #20991 we remove this option entirely and make sync for admin group just like a regular group.
+   ;;  But with this change we want to make sure we don't accidently add/remove adminusers we need to :
+   ;;  - for LDAP, if the `ldap-sync-admin-group` is disabled, remove all mapping for admin group
+   ;;  - for SAML, JWT remove all mapping for admin group
+   (let [admin-group-id (u/the-id (group/admin))]
+     (when (and (ldap/ldap-configured?)
+                (= "false" (db/select-one-field :value Setting :key "ldap-sync-admin-group")))
```
[the remark this answers is not in the document]
Comment (camsaul) [reply src/metabase/db/data_migrations.clj:203]: Another thing worth mentioning: this is a total [Yoda condition](https://en.wikipedia.org/wiki/Yoda_conditions) -- `(= "false" x)` reads as `"false" = x` which is not necessarily wrong, but is definitely weird. `(= x "false")` is much more normal to look at

File: src/metabase/db/data_migrations.clj [hunk 24]
```diff
@@ -172,6 +177,39 @@
...
+       (remove-group-id-from-mappings-by-setting-key :ldap-group-mappings admin-group-id))
+     ;; sso are enterprise feature, so only remove admin groups if enterprise available
+     (when (premium-features/enable-sso?)
+       (classloader/require 'metabase-enterprise.sso.integrations.sso-settings)
+       (when ((resolve 'metabase-enterprise.sso.integrations.sso-settings/jwt-configured?))
+         (remove-group-id-from-mappings-by-setting-key :jwt-group-mappings admin-group-id))
```
Comment (camsaul) [inline src/metabase/db/data_migrations.clj:209]: This is going to NPE on OSS.

```clj
(resolve 'this-does/not-exist)
=> nil

((resolve 'this-does/not-exist))
=>
;; Execution error (NullPointerException) at metabase.models.permissions/eval236040 (REPL:5).
;; Cannot invoke "clojure.lang.IFn.invoke()" because the return value of "clojure.lang.IFn.invoke(Object)" is null
```

File: src/metabase/db/data_migrations.clj [hunk 25]
```diff
@@ -22,17 +28,16 @@
 (defn- ^:deprecated run-migration-if-needed!
   "Run migration defined by `migration-var` if needed. `ran-migrations` is a set of migrations names that have already
   been run.
-
      (run-migration-if-needed! #{\"migrate-base-types\"} #'set-card-database-and-table-ids)
-
```
[the remark this answers is not in the document]
Comment (camsaul) [reply src/metabase/db/data_migrations.clj:27]: Yeah, those lines are intentional. See https://guide.clojure.style/#markdown-docstrings -- we're doing the usual four-space indent to signify a code block here.

**Review by camsaul — CHANGES_REQUESTED** [review]
I left a few notes but there's already a lot to do here between Noah's comments and mine, so re-request once they're addressed and I'll do another pass

File: src/metabase/integrations/common.clj (hunk 18 above)
Comment (qnkhuat) [reply src/metabase/integrations/common.clj:17]: Actually, it's also used when we add membership(see line 34), and also I think having a name for it makes the logic clearer.

File: src/metabase/models/permissions.clj (hunk 12 above)
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/models/permissions.clj:133]: Any reasons to not replace it with `⚠️` now?

File: test/metabase/db/data_migrations_test.clj (hunk 21 above)
Comment (qnkhuat) [reply test/metabase/db/data_migrations_test.clj:386]: > running the SAML/JWT migration logic even on OSS instance

Actually, it'll not. SSO will only be configured if enterprise is available, check lines 396->399 where it runs the `body` with only `ldap` configured if we run OSS

Is it too much `magic` under the hood though?

File: src/metabase/db/data_migrations.clj (hunk 24 above)
Comment (qnkhuat) [reply src/metabase/db/data_migrations.clj:209]: It'll not throw NPE because it is under `(when (premium-features/enable-sso?))` which only true if enterprise is available.

But Noah made [a good point](https://github.com/metabase/metabase/pull/20991#discussion_r833682196) about running it in OSS too,  so I'll change this in the way we could check if `smal/jwt` configured even in OSS

File: test/metabase/db/data_migrations_test.clj (hunk 21 above)
Comment (qnkhuat) [reply test/metabase/db/data_migrations_test.clj:368]: > Although I'm not totally sure if that's an issue for using that helper or not

It'll throw an exception if we try to access an _enterprise_ in OSS.

File: src/metabase/db/data_migrations.clj (hunk 15 above)
Comment (qnkhuat) [reply src/metabase/db/data_migrations.clj]: I changed it so that we’ll run it even in oss, the check conditions -are similar to jwt-configured? And saml-configured?

I suppose if a customer change from ee to oss, those settings will not be overridden right? I.e: automatically change saml-enabled to false?

File: src/metabase/integrations/ldap.clj (hunk 19 above)
Comment (qnkhuat) [reply src/metabase/integrations/ldap.clj]: Actually I just realized we don't need this anymore, I’ll revert it to the original code

File: src/metabase/db/data_migrations.clj [hunk 26]
```diff
@@ -172,6 +176,67 @@
...
+                        (json/parse-string (raw-setting mapping-setting-key))
+                        (catch Exception _e
+                          {}))]
+    (when-not (empty? mapping)
+      (db/update! Setting (name mapping-setting-key)
+                  :value
+                  (->> mapping
+                          (map (fn [[k v]] [k (filter #(not= admin-group-id %) v)]))
+                          (into {})
+                          (json/generate-string))))))
```
Comment (camsaul) [inline src/metabase/db/data_migrations.clj:199]:
```suggestion
                          json/generate-string)))))
```

File: src/metabase/db/data_migrations.clj (hunk 24 above)
Comment (camsaul) [reply src/metabase/db/data_migrations.clj]: I don't think copy-pasting all the implementations of those functions was really what I had in mind here. I just meant you should check that `(resolve 'metabase-enterprise.sso.integrations.sso-settings/jwt-configured?)` actual returns something before you invoke it as a function

File: src/metabase/db/data_migrations.clj [hunk 27]
```diff
@@ -172,6 +176,67 @@
...
+                        (raw-setting :ldap-host)
+                        (raw-setting :ldap-user-base)))
+
+    :jwt  (boolean (and (= (raw-setting :jwt-enabled) "true")
+                        (raw-setting :jwt-identity-provider-uri)
+                        (raw-setting :jwt-shared-secret)))
+
+    :saml (boolean (and (= (raw-setting :saml-enabled) "true")
+                        (raw-setting :saml-identity-provider-uri)
+                        (raw-setting :saml-identity-provider-certificate)))))
```
Comment (camsaul) [inline src/metabase/db/data_migrations.clj:221]: Not a huge fan of duplicating all this logic here. Why do we need to check this stuff at all anyway? Can't we just check whether there is a Setting named `jwt-group-mappings` and update it if it exists?

File: src/metabase/models/setting.clj [hunk 28]
```diff
@@ -122,7 +122,12 @@
   these names to avoid unintended side-effects if an application database still stores values for these settings."
   #{"-site-url"
     "enable-advanced-humanization"
-    "metabot-enabled"})
+    "metabot-enabled"
+    "ldap-sync-admin-group"})
+
+(def ^:dynamic *allow-retired-setting-names*
+  "Primarily used in test to disable retired setting check"
```
Comment (camsaul) [inline src/metabase/models/setting.clj:129]: https://guide.clojure.style/#docstring-summary

File: test/metabase/db/data_migrations_test.clj [hunk 29]
```diff
@@ -331,3 +334,100 @@
...
+  (let [original-value (db/select-one-field :value Setting :key setting-k)]
+    (try
+     (if original-value
+       (db/update! Setting setting-k :value value)
+       (db/insert! Setting :key setting-k :value value))
+     (thunk)
+     (finally
+       (if original-value
+         (db/update! Setting setting-k :value original-value)
+         (db/delete! Setting :key setting-k))))))
```
Comment (camsaul) [inline test/metabase/db/data_migrations_test.clj:352]: This looks like a less fully-featured copy of https://github.com/metabase/metabase/blob/5a67efea0e4812a75b699ff00cb68034c020d01e/test/metabase/test/util.clj#L345-L379

File: test/metabase/db/data_migrations_test.clj [hunk 30]
```diff
@@ -331,3 +334,100 @@
...
+       ldap-user-base                     "dc=metabase,dc=com"
+       ldap-group-mappings                (json/generate-string ldap-group-mapping)
+       ldap-sync-admin-group              "false"
+       jwt-enabled                        "true"
+       jwt-identity-provider-uri          "http://test.idp.metabase.com"
+       jwt-shared-secret                  (crypto-random/hex 32)
+       jwt-group-mappings                 (json/generate-string sso-group-mapping)
+       saml-enabled                       "true"
+       saml-identity-provider-uri         "http://test.idp.metabase.com"
+       saml-identity-provider-certificate (slurp "test_resources/sso/auth0-public-idp")
```
Comment (camsaul) [inline test/metabase/db/data_migrations_test.clj:381]: Is it worth giving this filename an extension? Not sure what the right one is here

**Comment by noahmoss** [comment]
@qnkhuat I think my comments yesterday may have been unclear. To clarify: the migration logic can be the same between EE and OSS in all cases.
1. Read the `ldap/jwt/saml-configured?` setting from the DB directly
2. If that setting is `true` (and in the LDAP case, `ldap-sync-admin-group` is false), remove mapped admin groups

The setting will still be `true` in the DB for EE instances that enabled SAML/JWT and then downgraded to OSS.

This means for the tests, the _only_ thing that needs to be set is the value of the `ldap/jwt/saml-configured?`setting in the DB. You don't actually need to actually set up LDAP/SAML/JWT, or have a valid SAML certificate saved, or anything.

File: test/metabase/db/data_migrations_test.clj (hunk 29 above)
Comment (camsaul) [reply test/metabase/db/data_migrations_test.clj:352]: It's better to extend the existing version to make it a little more flexible (e.g. to support raw values) so everyone can use that functionality instead of just copying it and stripping a bunch of stuff out and tweaking it.

Imagine if we did that every time we needed to do something slightly different than what existing test utils did -- we'd have a hundred different versions of every test util scattered all over the code base

**Review by camsaul — CHANGES_REQUESTED** [review]
Left some more notes

File: src/metabase/models/setting.clj (hunk 28 above)
Comment (camsaul) [reply src/metabase/models/setting.clj:129]: The variable name isn't that confusing but a docstring should still describe what the variable/function does. Right now it just describes where it is used. For example if I had a function like

```clj
(defn my-function
  "This is mostly used in [[metabase.my-namespace]]."
  [x]
  ...)
```

That tells me nothing about what `my-function` does. This is better:

```clj
(defn my-function
  "`my-function` does blah blah blah. This is mostly used in [[metabase.my-namespace]]."
  [x]
  ...)
```

Comment (camsaul) [reply src/metabase/models/setting.clj:129]: Also please use complete sentences

**Comment by camsaul** [comment]
@noahmoss `saml-configured?` isn't a Setting, it's a function

File: test/metabase/db/data_migrations_test.clj (hunk 30 above)
Comment (qnkhuat) [reply test/metabase/db/data_migrations_test.clj:381]: how about `.cert` tho?

File: src/metabase/db/data_migrations.clj (hunk 24 above)
Comment (qnkhuat) [reply src/metabase/db/data_migrations.clj]: I think you're right, no need to check if enabled.
for saml and yml we haven't synced it, so it's safe to remove admin regardless.

but for ldap, we need to check if users have been syncing admin or not.

File: test/metabase/test/util.clj [hunk 31]
```diff
@@ -342,41 +342,65 @@
...
+  (setting.cache/restore-cache!))
+
+(defn- restore-raw-setting!
+  [original-value setting-k]
+  (if original-value
+    (db/update! Setting setting-k :value original-value)
+    (db/delete! Setting :key setting-k))
+  (setting.cache/restore-cache!))
+
 (defn do-with-temporary-setting-value
```
Comment (qnkhuat) [inline test/metabase/test/util.clj:359]: @camsaul what do you think about this implementation of adding support for `raw-setting`?
Previous discussion: https://github.com/metabase/metabase/pull/20991#discussion_r834525113

**Review by camsaul — APPROVED** [review]
Cool, LGTM

File: test/metabase/test/util.clj [hunk 32]
```diff
@@ -389,13 +413,27 @@
...
+  (test-runner.parallel/assert-test-is-not-parallel "with-temporary-setting-vales")
   (if (empty? bindings)
     `(do ~@body)
     `(do-with-temporary-setting-value ~(keyword setting-k) ~value
        (fn []
          (with-temporary-setting-values ~more
            ~@body)))))
 
+(defmacro with-temporary-raw-setting-values
+  "Like `with-temporary-raw-setting-values` but works with raw value and it allows undefined settings."
```
Comment (noahmoss) [inline test/metabase/test/util.clj:425]:
```suggestion
  "Like `with-temporary-setting-values` but works with raw value and it allows undefined settings."
```

File: test/metabase/test/util.clj [hunk 33]
```diff
@@ -342,41 +342,65 @@
...
   "Temporarily set the value of the Setting named by keyword `setting-k` to `value` and execute `f`, then re-establish
   the original value. This works much the same way as [[binding]].
 
   If an env var value is set for the setting, this acts as a wrapper around [[do-with-temp-env-var-value]].
 
-  Prefer the macro [[with-temporary-setting-values]] over using this function directly."
-  [setting-k value thunk]
-  (test-runner.parallel/assert-test-is-not-parallel "with-temporary-setting-values")
+  If `raw-setting?` is `true`, this works like [[with-temp*]] against the `Setting` table, but it ensures no exception
+  is thrown if the `setting-k` is already existed.
```
Comment (noahmoss) [inline test/metabase/test/util.clj:366]: grammar nit
```suggestion
  is thrown if the `setting-k` already exists.
```

File: test/metabase/test/util.clj (hunk 32 above)
Comment (noahmoss) [reply test/metabase/test/util.clj:425]: maybe clarify what `undefined settings` means? i.e. "it can be used with setting names that are not defined with `defsetting`"

at first I read it to mean settings that have "undefined" values

**Review by noahmoss — APPROVED** [review]
looks great, just a couple nits
