### PR TITLE
Fix alerts and subscriptions bugs

### LINKED ISSUE #22496: Cannot create an Alert for Slack channel unless inputting an email address too
**Describe the bug**
Cannot create an Alert for Slack channel unless inputting an email address too.

Workaround: Leave yourself as email recipient, but with Email toggle disabled. Create the alert. Then edit the alert, which allows you to remove yourself as email recipient and save, but if you want to edit the Alert again, then you need to input an email.

**To Reproduce**
1. Setup an instance with Email and Slack configured
2. Create a question - save it - click the :bell: icon in bottom-right corner
3. Remove yourself as email recipient, then toggle Email=Off. Then toggle Slack=On and select a channel
image
4. The "Done" button is disabled.
5. To be allowed to save the Alert, then toggle Email=On and input yourself as email recipient, then toggle Email=Off

**Information about your Metabase Installation:**
Tested 0.43.0, but I believe this is how it's always been behaving.

**Additional context**
Related to #18608

### LINKED ISSUE #23483: Allow sending Alerts to private Slack channel
**Describe the bug**
Same as #20867, but just for Alerts.

**Expected behavior**
Same functionality as Subscriptions - including being able to send to private channel.
It would also be great if there was a "Send now" button, but I'm unsure if we're missing an API endpoint for that.

**Information about your Metabase Installation:**
0.43.3

**Additional context**
Would be good to address #22496 and #18608, as well as #13834 (which might fix #15831).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #23494: Slack subscriptions UX is buggy
**Describe the bug**
There are multiple bugs on the dashboard subscriptions Slack form such
- Invalid initial state when you open existing subscription with private channel
- When switching between private and public channel type and press "Send to Slack now" it sends invalid values

**To Reproduce**
1. Setup Slack integration
2. Go to a dashboard and create a Slack subscription with a private channel and click "Done"
3. Open the subscription you've created — **it shows `A public channel` option selected with no value**
4. Select any valid public channel
5. Change channel type to private and enter a private channel name and click `A public channel`
6. Send a test notification — **it is mistakingly sent to the private channel**

**Expected behavior**
Autocomplete input that accepts arbitrary values would fit better

**Information about your Metabase Installation:**
Latest `master`

### LINKED ISSUE #23527: Arbitrary recipient's email addresses are shown as empty values
**Describe the bug**
Unable to add an arbitrary email for an alert or subscription.

**To Reproduce**
1. Create a question email alert OR a dashboard email subscription
2. Type an arbitrary email that does not belong to any user and press enter
3. It shows an empty value

**Expected behavior**
It shows the entered email

**Screenshots**

Screenshot 2022-06-24 at 05 00 32

**Information about your Metabase Installation:**

`release-x.42.x` is fine, the bug is in the `release-x.43.x`

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/23483
Closes https://github.com/metabase/metabase/issues/22496
Closes https://github.com/metabase/metabase/issues/23494
Closes https://github.com/metabase/metabase/issues/23527

## Changes

Adds the ability to send alerts to private channels (https://github.com/metabase/metabase/issues/23483). In the scope of it, slightly changes UX of sending subscriptions to Slack (tackles https://github.com/metabase/metabase/issues/23494) and reuses the component for in Alerts. 

Also, fixes slightly related bugs https://github.com/metabase/metabase/issues/22496 https://github.com/metabase/metabase/issues/23527

### Subscriptions

Before (public/private channel radio button):
Screenshot 2022-06-24 at 20 43 36

After (autocomplete input that accepts arbitrary values)
Screenshot 2022-06-24 at 20 40 26

### Alerts

Uses the same channel autocomplete input from subscriptions:
Screenshot 2022-06-24 at 20 40 06

## How to verify

- Configure the Slack integration

#### Subscriptions

- Create new or open an existing dashboard 
- Create a Slack subscription
- Ensure the channel autocomplete input 
    - Shows public channels
    - Allows entering an arbitrary value for private channels
        - When an arbitrary value is entered, it shows a hint how to make subscriptions work with the private channels

#### Alerts

- Create new or open an existing question
- Create an Alert and enable the Slack alert channel
- Ensure the channel autocomplete input 
    - Shows public channels
    - Allows entering an arbitrary value for private channels
        - When an arbitrary value is entered, it shows a hint how to make subscriptions work with the private channels

#### Bug fixes

Check the repro steps of https://github.com/metabase/metabase/issues/23527 and https://github.com/metabase/metabase/issues/22496

### CODE REVIEW

File: frontend/src/metabase/sharing/components/SlackChannelField.jsx [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+  t`In order to send subscriptions and alerts to private Slack channels, you must first add the Metabase bot to them.`;
+
+const CHANNEL_FIELD_NAME = "channel";
+const CHANNEL_PREFIX = "#";
+const USER_PREFIX = "@";
+
+const ALLOWED_PREFIXES = [CHANNEL_PREFIX, USER_PREFIX];
+
+function SlackChannelField({ channel, channelSpec, onChannelPropertyChange }) {
+  const [warning, setWarning] = useState(null);
```
Comment (ranquild) [inline frontend/src/metabase/sharing/components/SlackChannelField.jsx:17]: nit: it seems it can be changed to a boolean field, e.g. if the warning is visible

File: frontend/src/metabase/sharing/components/SlackChannelField.jsx [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+const getPrivateChannelWarning = () =>
+  t`In order to send subscriptions and alerts to private Slack channels, you must first add the Metabase bot to them.`;
+
+const CHANNEL_FIELD_NAME = "channel";
+const CHANNEL_PREFIX = "#";
+const USER_PREFIX = "@";
+
+const ALLOWED_PREFIXES = [CHANNEL_PREFIX, USER_PREFIX];
+
+function SlackChannelField({ channel, channelSpec, onChannelPropertyChange }) {
```
Comment (ranquild) [inline frontend/src/metabase/sharing/components/SlackChannelField.jsx:16]: nit: could this be converted to TS? You could add missing types to `metabase-types/api`

**Review by ranquild — APPROVED** [review]
There is an issue with selecting values from the dropdown when the input has a value without prefix. Otherwise looks good

**Review by gusaiani — APPROVED** [review]
Pretty nice 👍👍👍👍
