### PR TITLE
Fix auth failure loop when session expires

### LINKED ISSUE #4660: Session Expiring puts browser in a auth-failure loop
As evidenced by leaving a dashboard on a large format monitor long enough.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #4660

### CODE REVIEW

File: frontend/src/metabase/redux/user.js [hunk 1]
```diff
@@ -6,24 +6,30 @@ import { CLOSE_QB_NEWB_MODAL } from "metabase/query_builder/actions";
...
 
+export const CLEAR_CURRENT_USER = "metabase/user/CLEAR_CURRENT_USER"
+export const clearCurrentUser = createAction(CLEAR_CURRENT_USER)
+
 export const currentUser = handleActions({
-    ["REFRESH_CURRENT_USER"]: { next: (state, { payload }) => payload },
-    ["AUTH_LOGOUT"]: { next: (state, { payload }) => null },
+    [CLEAR_CURRENT_USER]: { next: (state, payload) => null },
+    [REFRESH_CURRENT_USER]: { next: (state, { payload }) => payload },
+    [CLEAR_CURRENT_USER]: { next: (state, { payload }) => null },
```
Comment (kdoh) [inline frontend/src/metabase/redux/user.js]: Looks like `CLEAR_CURRENT_USER` is in here twice and `REFRESH_CURRENT_USER` is missing. Is that intentional?

Comment (tlrobinson) [inline frontend/src/metabase/redux/user.js]: `AUTH_LOGOUT` is missing, good catch.

**Review by kdoh — APPROVED** [review]

**Review by attekei — APPROVED** [review]
