### PR TITLE
Fix styling for heading cards in dashboard subscriptions

### LINKED ISSUE #31620: Fix styling for heading cards in dashboard subscriptions
### Describe the bug

Heading cards appear as plain text in dashboard subscriptions

"Visual Charts"
image

### To Reproduce

**Heading**
1. Go to any dashboard
2. Click on edit
3. Add a heading card and add some text to the heading
4. Create dashboard subscription
5. Send dashboard subscription to an email you can view
6. See heading in plain text

### Expected behavior

Should have the same styling as it does on a dashboard

### Information about your Metabase installation

```JSON
- Master
```

### Severity
P2

### PR DESCRIPTION
**Pull request by qwef**
Closes https://github.com/metabase/metabase/issues/31620

### Description

Escape markdown characters in headings cards, and add heading markdown.

### How to verify

Go to any dashboard
Click on edit
Add a heading card and add some text to the heading
Create dashboard subscription
Send dashboard subscription to an email you can view
See heading in plain text

### Demo

image

### CODE REVIEW

**Review by noahmoss — CHANGES_REQUESTED** [review]
This makes text cards show up in bold as well, rather than just headings. Also this won't work for Slack dashboard subscriptions.

I think we should leverage the BE markdown processing code for this. Maybe just add a `#` in front of the content to make it a markdown header first, then process it to html or Slack markup. There might be an edge case where the content already begins with `#` so you could escape it in that case.

**Comment by qwef** [comment]
When testing adding `#`, I realized it already converts to markdown. So if the user enters `# heading` in the test box, the email will already convert to markdown. This isn't intended right? So I should also escape existing `#`s, and then add our own to make it a header.

**Comment by noahmoss** [comment]
@qwef Good catch. Yeah I don't think we'd want any existing markdown in the header to be rendered if the FE doesn't also.

In `metabase.pulse.markdown` there's already `escape-text` which is specific to escaping Markdown characters for Slack. Maybe you could expand this to a multmethod dispatched on `:email`/`:slack` similar to `process-markdown` and have it work for either. Then the processing for headers would look like 1. escape characters 2. add `#` 3. process as markdown

File: src/metabase/pulse/parameters.clj [hunk 1]
```diff
@@ -49,8 +49,9 @@
   "Given a dashcard and the parameters on a dashboard, returns the dashcard with any parameter values appropriately
   substituted into connected variables in the text."
   [dashcard parameters]
-  (let [text               (-> dashcard :visualization_settings :text)
-        parameter-mappings (:parameter_mappings dashcard)
+  (let [escaped-dashcard   (update-in dashcard [:visualization_settings :text] #(str "## " (shared.params/escape-chars % shared.params/escaped-markdown-chars-regex)))
```
Comment (noahmoss) [inline src/metabase/pulse/parameters.clj:52]: This should only be done for heading cards, right? Not every text card.

File: src/metabase/pulse/parameters.clj [hunk 2]
```diff
@@ -49,7 +49,10 @@
   "Given a dashcard and the parameters on a dashboard, returns the dashcard with any parameter values appropriately
   substituted into connected variables in the text."
   [dashcard parameters]
-  (let [text               (-> dashcard :visualization_settings :text)
+  (let [dashcard           (if (= "heading" (get-in dashcard [:visualization_settings :virtual_card :display]))
+                             (update-in dashcard [:visualization_settings :text] #(str "## " (shared.params/escape-chars % shared.params/escaped-chars-regex)))
```
Comment (noahmoss) [inline src/metabase/pulse/parameters.clj:53]: Approach for escaping looks good, but I think it might be a bit nicer to lift up this logic into `metabase.pulse`, maybe as a helper function that's called from `dashcard->part`. This namespace is specifically about parameter substitution which isn't relevant here

**Review by noahmoss — APPROVED** [review]
