### PR TITLE
Fix empty state color for accordion list

### LINKED ISSUE #46667: Wrong text color in breakout column search empty state
### Describe the bug

[v50.0 for comparison](https://github.com/user-attachments/assets/289ac07f-ccbc-493d-8a39-36a12bd58465)

image

### To Reproduce

1. New > Question > Orders
2. Try to search for a breakout column
3. Type gibberish in the search so there are no results
4. See empty state

### Expected behavior

Text color is gray

### Information about your Metabase installation

master, ea677b3696

(it works correctly in v50.0)

### Severity

P3

### PR DESCRIPTION
**Pull request by sanex3339**
Fixes https://github.com/metabase/metabase/issues/46667
The wrong unsupported value was used

Fixed visuals:
image

# How to verify:
- New > Question > Orders
- Click `filter` and `summarize` buttons
- Type gibberish in the search so there are no results
- See empty state, text should have a gray color

### CODE REVIEW

File: frontend/src/metabase/static-viz/components/ProgressBar/ProgressBar.tsx [hunk 1]
```diff
@@ -112,7 +112,7 @@ const ProgressBar = ({
             <Text
               fontSize={layout.fontSize}
               textAnchor="start"
-              color="#ffffff"
+              color="text-white"
```
Comment (sanex3339) [inline frontend/src/metabase/static-viz/components/ProgressBar/ProgressBar.tsx:115]: `text-white` is `#FFF`

File: frontend/src/metabase/static-viz/components/Text/Text.tsx [hunk 2]
```diff
@@ -1,6 +1,12 @@
 import type { TextProps } from "@visx/text";
 import { Text as VText } from "@visx/text";
 
-export const Text = (props: TextProps) => {
+import type { ColorPalette } from "metabase/lib/colors/types";
+
+type Props = Omit<TextProps, "color"> & {
+  color?: keyof ColorPalette;
```
Comment (sanex3339) [inline frontend/src/metabase/static-viz/components/Text/Text.tsx:7]: Sadly, this component and the one used by EmptyState - different components.

Comment (kamilmielnik) [inline frontend/src/metabase/static-viz/components/Text/Text.tsx:7]: Nice :+1:

**Review by kamilmielnik — APPROVED** [review]
I think we don't need a repro for this one :)

----

Please remember to always [link relevant issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) :pray:

**Review by npretto — APPROVED** [review]
