### PR TITLE
Fixing of TIME breakouts in MySQL

### LINKED ISSUE #12846: MySQL grouping on a TIME field is not working
**Describe the bug**
Grouping on a MySQL `TIME` column is not working

**Logs**
See below:
```
07-06 15:31:16 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 3,
 :started_at (t/zoned-date-time "2020-07-06T15:31:15.814-04:00[America/New_York]"),
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error reducing result rows",
   :stacktrace
   ["--> query_processor.context.default$default_reducef$fn__38004.invoke(default.clj:61)"
    "query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
    "query_processor.context.default$default_reducef.invoke(default.clj:49)"
    "query_processor.context$reducef.invokeStatic(context.clj:69)"
    "query_processor.context$reducef.invoke(context.clj:62)"
    "query_processor.context.default$default_runf$respond_STAR___38008.invoke(default.clj:70)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:392)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
    "driver.sql_jdbc$fn__73052.invokeStatic(sql_jdbc.clj:49)"
    "driver.sql_jdbc$fn__73052.invoke(sql_jdbc.clj:47)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
    "query_processor.context.default$default_runf.invoke(default.clj:67)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43149.invoke(mbql_to_native.clj:26)"
    "query_processor.middleware.check_features$check_features$fn__42463.invoke(check_features.clj:42)"
    "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43314.invoke(optimize_datetime_filters.clj:133)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47282.invoke(wrap_value_literals.clj:137)"
    "query_processor.middleware.annotate$add_column_info$fn__41084.invoke(annotate.clj:577)"
    "query_processor.middleware.permissions$check_query_permissions$fn__42338.invoke(permissions.clj:64)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43813.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42536.invoke(cumulative_aggregations.clj:61)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__44345.invoke(resolve_joins.clj:183)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39271.invoke(add_implicit_joins.clj:245)"
    "query_processor.middleware.limit$limit$fn__43135.invoke(limit.clj:38)"
    "query_processor.middleware.format_rows$format_rows$fn__43116.invoke(format_rows.clj:81)"
    "query_processor.middleware.desugar$desugar$fn__42602.invoke(desugar.clj:22)"
    "query_processor.middleware.binning$update_binning_strategy$fn__41628.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__42144.invoke(resolve_fields.clj:24)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__38807.invoke(add_dimension_projections.clj:272)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39027.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39420.invoke(add_source_metadata.clj:105)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__44010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41269.invoke(auto_bucket_datetimes.clj:125)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42191.invoke(resolve_source_table.clj:46)"
    "query_processor.middleware.parameters$substitute_parameters$fn__43795.invoke(parameters.clj:97)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42243.invoke(resolve_referenced.clj:80)"
    "query_processor.middleware.expand_macros$expand_macros$fn__42858.invoke(expand_macros.clj:158)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39451.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47166.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021$fn__44025.invoke(resolve_database_and_driver.clj:33)"
    "driver$do_with_driver.invokeStatic(driver.clj:61)"
    "driver$do_with_driver.invoke(driver.clj:57)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021.invoke(resolve_database_and_driver.clj:27)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__43064.invoke(fetch_source_query.clj:243)"
    "query_processor.middleware.store$initialize_store$fn__47175$fn__47176.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
    "query_processor.store$do_with_store.invoke(store.clj:40)"
    "query_processor.middleware.store$initialize_store$fn__47175.invoke(store.clj:10)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__42120.invoke(cache.clj:209)"
    "query_processor.middleware.validate$validate_query$fn__47184.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__43162.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39289.invoke(add_rows_truncated.clj:36)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47151.invoke(results_metadata.clj:128)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__42479.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__43884.invoke(process_userland_query.clj:136)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__42422.invoke(catch_exceptions.clj:174)"
    "query_processor.reducible$async_qp$qp_STAR___38090$thunk__38091.invoke(reducible.clj:101)"
    "query_processor.reducible$async_qp$qp_STAR___38090.invoke(reducible.clj:107)"
    "query_processor.reducible$sync_qp$qp_STAR___38099$fn__38102.invoke(reducible.clj:133)"
    "query_processor.reducible$sync_qp$qp_STAR___38099.invoke(reducible.clj:132)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:218)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:214)"
    "query_processor$fn__47350$process_query_and_save_execution_BANG___47359$fn__47362.invoke(query_processor.clj:233)"
    "query_processor$fn__47350$process_query_and_save_execution_BANG___47359.invoke(query_processor.clj:225)"
    "query_processor$fn__47394$process_query_and_save_with_max_results_constraints_BANG___47403$fn__47406.invoke(query_processor.clj:245)"
    "query_processor$fn__47394$process_query_and_save_with_max_results_constraints_BANG___47403.invoke(query_processor.clj:238)"
    "api.dataset$fn__50692$fn__50695.invoke(dataset.clj:52)"
    "query_processor.streaming$streaming_response_STAR_$fn__34128$fn__34129.invoke(streaming.clj:73)"
    "query_processor.streaming$streaming_response_STAR_$fn__34128.invoke(streaming.clj:72)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
    "async.streaming_response$do_f_async$fn__23118.invoke(streaming_response.clj:85)"],
   :error_type :qp,
   :ex-data {:type :qp}}],
 :state nil,
 :error_type :qp,
 :json_query {:type "query", :query {:source-table 55, :breakout [["datetime-field" ["field-id" 792] "minute"]]}, :database 3, :parameters [], :middleware {:add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT str_to_date(date_format(`portal_eventattendance`.`time`, '%Y-%m-%d %H:%i'), '%Y-%m-%d %H:%i') AS `time` FROM `portal_eventattendance` GROUP BY str_to_date(date_format(`portal_eventattendance`.`time`, '%Y-%m-%d %H:%i'), '%Y-%m-%d %H:%i') ORDER BY str_to_date(date_format(`portal_eventattendance`.`time`, '%Y-%m-%d %H:%i'), '%Y-%m-%d %H:%i') ASC LIMIT 2000",
  :params nil},
 :status :failed,
 :class java.sql.SQLException,
 :stacktrace
 ["org.mariadb.jdbc.internal.com.read.resultset.rowprotocol.TextRowProtocol.getInternalZonedDateTime(TextRowProtocol.java:925)"
  "org.mariadb.jdbc.internal.com.read.resultset.SelectResultSet.getObject(SelectResultSet.java:1257)"
  "com.mchange.v2.c3p0.impl.NewProxyResultSet.getObject(NewProxyResultSet.java:217)"
  "--> driver.mysql$fn__72285$read_datetime_thunk__72289.invoke(mysql.clj:350)"
  "driver.sql_jdbc.execute$row_thunk$row_thunk_STAR___70943.invoke(execute.clj:348)"
  "query_processor.reducible$reducible_rows$reify__38106.reduce(reducible.clj:156)"
  "query_processor.context.default$default_reducef$fn__38004.invoke(default.clj:59)"
  "query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
  "query_processor.context.default$default_reducef.invoke(default.clj:49)"
  "query_processor.context$reducef.invokeStatic(context.clj:69)"
  "query_processor.context$reducef.invoke(context.clj:62)"
  "query_processor.context.default$default_runf$respond_STAR___38008.invoke(default.clj:70)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:392)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc$fn__73052.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__73052.invoke(sql_jdbc.clj:47)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43149.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__42463.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43314.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47282.invoke(wrap_value_literals.clj:137)"
  "query_processor.middleware.annotate$add_column_info$fn__41084.invoke(annotate.clj:577)"
  "query_processor.middleware.permissions$check_query_permissions$fn__42338.invoke(permissions.clj:64)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43813.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42536.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__44345.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39271.invoke(add_implicit_joins.clj:245)"
  "query_processor.middleware.limit$limit$fn__43135.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__43116.invoke(format_rows.clj:81)"
  "query_processor.middleware.desugar$desugar$fn__42602.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__41628.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__42144.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38807.invoke(add_dimension_projections.clj:272)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39027.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39420.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__44010.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41269.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42191.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__43795.invoke(parameters.clj:97)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42243.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__42858.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39451.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47166.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021$fn__44025.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__44021.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__43064.invoke(fetch_source_query.clj:243)"
  "query_processor.middleware.store$initialize_store$fn__47175$fn__47176.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__47175.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__42120.invoke(cache.clj:209)"
  "query_processor.middleware.validate$validate_query$fn__47184.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__43162.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39289.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47151.invoke(results_metadata.clj:128)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__42479.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__43884.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__42422.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___38090$thunk__38091.invoke(reducible.clj:101)"
  "query_processor.reducible$async_qp$qp_STAR___38090.invoke(reducible.clj:107)"
  "query_processor.reducible$sync_qp$qp_STAR___38099$fn__38102.invoke(reducible.clj:133)"
  "query_processor.reducible$sync_qp$qp_STAR___38099.invoke(reducible.clj:132)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:218)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:214)"
  "query_processor$fn__47350$process_query_and_save_execution_BANG___47359$fn__47362.invoke(query_processor.clj:233)"
  "query_processor$fn__47350$process_query_and_save_execution_BANG___47359.invoke(query_processor.clj:225)"
  "query_processor$fn__47394$process_query_and_save_with_max_results_constraints_BANG___47403$fn__47406.invoke(query_processor.clj:245)"
  "query_processor$fn__47394$process_query_and_save_with_max_results_constraints_BANG___47403.invoke(query_processor.clj:238)"
  "api.dataset$fn__50692$fn__50695.invoke(dataset.clj:52)"
  "query_processor.streaming$streaming_response_STAR_$fn__34128$fn__34129.invoke(streaming.clj:73)"
  "query_processor.streaming$streaming_response_STAR_$fn__34128.invoke(streaming.clj:72)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
  "async.streaming_response$do_f_async$fn__23118.invoke(streaming_response.clj:85)"],
 :context :ad-hoc,
 :error "0000-00-00 10:00:00 cannot be parse as LocalDateTime. time must have \"yyyy-MM-dd HH:mm:ss[.S]\" format",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query {:source-table 55, :breakout [[:datetime-field [:field-id 792] :minute]], :order-by [[:asc [:datetime-field [:field-id 792] :minute]]], :limit 2000},
  :database 3,
  :middleware {:add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash [102, -128, 88, 47, 84, 47, 14, -45, 117, 90, 87, -8, 37, -39, -123, 64, -34, -92, -13, 27, -16, -106, -57, 119, 2, 103, -40, 114, -24, -7, 4, 112]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}
```

**To Reproduce**
1. Create a new Question
2. Pick any db / table
3. Group on a column with `TIME` type
3. Click Visualize and the error pops up

**Expected behavior**
It should group on the time column by minute without raising an error

**Screenshots**
See below: 
Screen Shot 2020-07-06 at 12 37 33 PM

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_242-b08",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_242",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.242-b08",
    "os.name": "Linux",
    "os.version": "3.10.0-1127.el7.x86_64",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "5.5.65-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.4",
      "date": "2020-05-28",
      "branch": "release-0.35.x",
      "hash": "b3080fa"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```
- Your browser and the version: (see above)
- Your operating system: RedHat 7.8 (3.10.0 kernel)
- Your databases: MySQL
- Metabase version: 0.35.4
- Metabase hosting environment: JAR file
- Metabase internal database: H2

**Severity**
Medium

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by robdaemon**
Reworks :hour and :minute breakouts to function on MySQL 5.5+ and 
MariaDB 10.2+

Older versions of MySQL and newer versions of MariaDB do not accept a
date of 0000-00-00, which date_format was generating. In the cases where
we're attempting to truncate the date and normalize them all to group by
hours or minutes, this will cast the TIME to DATETIME, which will make
it possible to convert it back to the proper type after truncation.
  
Adds an additional two test cases for grouping on a TIME column (both
:hour and :minute)

Resolves #12846

[ci mysql]

### CODE REVIEW

**Comment by robdaemon** [comment]
This bug was only manifesting on MySQL 5.5, but this will make the grouping by hour / minute only consider hours and minutes on all MySQL versions (tested against 5.5 and 5.7)

File: test/metabase/driver/mysql_test.clj [hunk 1]
```diff
@@ -208,3 +208,33 @@
...
+              spec (sql-jdbc.conn/connection-details->spec driver details)]
+          (doseq [stmt ["DROP TABLE IF EXISTS time_table;"
+                        "CREATE TABLE time_table (id serial, mytime time);"
+                        "INSERT INTO time_table (mytime) VALUES ('00:00'), ('00:00'), ('23:01'), ('23:01'), ('18:43');"]]
+            (jdbc/execute! spec [stmt]))
+          (mt/with-temp Database [db {:engine driver :details details}]
+            (sync/sync-database! db)
+            (mt/with-db db
+              (testing "can group on TIME columns"
+                (is (= [["2020-07-14T00:00:00Z"] ["2020-07-14T18:43:00Z"] ["2020-07-14T23:01:00Z"]]
```
Comment (robdaemon) [inline test/metabase/driver/mysql_test.clj:230]: oh this is totally going to blow up, oops

File: src/metabase/driver/mysql.clj [hunk 2]
```diff
@@ -160,6 +160,7 @@
 
 (defn- date-format [format-str expr] (hsql/call :date_format expr (hx/literal format-str)))
 (defn- str-to-date [format-str expr] (hsql/call :str_to_date expr (hx/literal format-str)))
+(defn- sql-cast [expr newtype] (hsql/call :cast expr (hsql/raw (name newtype))))
```
Comment (sbelak) [inline src/metabase/driver/mysql.clj:163]: This already exists as `metabase.util.honeysql-extansions/cast`

**Review by sbelak — CHANGES_REQUESTED** [review]

File: src/metabase/driver/mysql.clj (hunk 2 above)
Comment (robdaemon) [reply src/metabase/driver/mysql.clj]: fixed!

**Review by sbelak — APPROVED** [review]
