### PR TITLE
UXW-603 unified picker for Document smart link

### LINKED ISSUE #62727: Limited choice of tables and dashboards to link in documents
### Describe the bug

https://github.com/user-attachments/assets/2abe38fd-0404-4e31-8baf-2568b2a28f64

### To Reproduce

1. Create a new document
2. Type `/` and click "Link"
3. Notice that 5 first suggestions contain tables and dashboards
4. Click "Browse all"

❌ The modal does not allow to pick tables or dashboards

### Information about your Metabase installation

master, 1b89bf16baf6b86db12230c9eebb66a0f65eb6d3

### Severity

P2

### PR DESCRIPTION
**Pull request by deniskaber**
Closes https://github.com/metabase/metabase/issues/62727

### Description

This adds a new data picker which is used when adding a smart link within a Document. New picker allows to pick not only tables or questions, but also dashboards and collections.

### How to verify

1. Create a document.
2. Type "/", then "Link", then "Browse all"
3. Picker should have ability to add dashboards and collections.
4. Type "@", then "Browse all"
5. Picker should have ability to add dashboards and collections.

### Demo

https://github.com/user-attachments/assets/f4fa2a7f-4d0f-4267-8381-3392ccfad5d9

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: e2e/support/helpers/e2e-document-helpers.ts [hunk 1]
```diff
@@ -19,11 +19,11 @@ export const clearDocumentContent = () => {
   documentContent().type("{selectAll}{backspace}");
 };
 
-export const documentSuggestionDialog = () =>
+export const documentMentionDialog = () =>
```
Comment (deniskaber) [inline e2e/support/helpers/e2e-document-helpers.ts:22]: Renamed this to avoid confusion between `commandSuggestionDialog` <> `documentSuggestionDialog`

**Review by iethree — APPROVED** [review]
Looks good. I'm hopeful that [Rewrite the Entity Picker](https://linear.app/metabase/project/rewrite-the-entity-picker-c3f62beae5cd) will soon remove 90% of the boilerplate required for this

**Comment by andsalves** [comment]
Merging this as Denis is OOO and asked for us to merge his approved PRs.
