### PR TITLE
Ignore unmapped groups during SSO group syncs

### LINKED ISSUE #7571: Ldap group sync wipes non-ldap group membership upon user login
If ldap group sync is enabled and a user is added to a group in the UI that membership is lost when the user logs out and logs back in. This appears to be because the ldap group membership syncing is being too aggressive when trying to determine what group membership to add and remove. LDAP syncing should not remove user memberships from any groups that are not used in any ldap group mappings.

Due to the aggressive syncing it is not possible to modify any user permissions when ldap group syncing is enabled. This is unfortunate as it requires a LDAP group per every group in Metabase.

**Steps to Reproduce**
1. Hook Metabase up to LDAP. Setup group syncing. Setup a group G in the UI. This group should not have any ldap mappings setup.
2. Have a ldap user log in (so they exist in the system) then add them to group G
3. Have the user log out and then back in. Their membership in G is wiped

**Expected Result**
Since the group G is not mapped to any ldap groups membership should not change when attempting to resync ldap permissions for a user

**Actual Result**
The users memberships in groups not hooked in to LDAP are wiped

Metabase version 0.29.0

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by noahmoss**
This PR modifies the behavior of group sync to only ever touch groups that have mappings set up for the relevant SSO provider. Metabase groups that are not mapped to SSO groups will not be modified by group sync. This is done by passing in a new argument `mapped-groups-or-ids` to `sync-group-memberships!` which restricts the set of groups that sync can modify. 

The current behavior is that users are always removed from unmapped groups on login, so these groups eventually become empty and are unusable. I thought about preserving this behavior as the default and introducing this change as a "partial group sync" setting, but after some thought and discussion with @brunobergher I realized it wouldn't make sense for an admin to create a new group but not set up a mapping for it if they expected it to still be included in group sync. So I think it should be OK to modify this behavior for all users.

Resolves #7571

### CODE REVIEW

File: src/metabase/integrations/common.clj [hunk 1]
```diff
@@ -9,29 +10,31 @@
...
         user-id            (u/the-id user-or-id)
-        ;; Get a set of Group IDs the user currently belongs to
+        ;; Get a set of mapped Group IDs the user currently belongs to
         current-group-ids  (db/select-field :group_id PermissionsGroupMembership
                                             :user_id  user-id
-                                            :group_id [:not-in special-group-ids])
-        new-group-ids      (set (map u/the-id new-groups-or-ids))
-        ;; determine what's different between current groups and new groups
+                                            ;; Add nil to included group ids to ensure valid SQL if set is empty
+                                            :group_id [:in (conj included-group-ids nil)]
```
Comment (noahmoss) [inline src/metabase/integrations/common.clj:25]: This was a workaround for a SQL error when `included-group-ids` is an empty set, since it seems to be converted to `IN NULL`. Not sure if there's a more elegant way to solve this.

**Comment by flamber** [comment]
I'm guessing this replaces #13729 ?

**Comment by noahmoss** [comment]
@flamber Yeah

**Comment by brunobergher** [comment]
@gvwilson Calling this out for you and Jeff to make sure we update any documentation.

File: src/metabase/integrations/common.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/integrations/common.clj:25]: If `included-group-ids` is empty, just don't run the query in the first place. Do 

```clj
(when (seq included-group-ids)
   ...)
```

**Review by camsaul — APPROVED** [review]
This LGTM overall. I would change the logic to avoid running the query in the first place if `included-group-ids` is empty since the query isn't going to return anything anyway and `SELECT ... WHERE some_field IN (NULL)` is too hacky/wacky
