### PR TITLE
Handle comparing ChronoLocalDateTime and Instants

### LINKED ISSUE #12311: java.lang.ClassCastException: class java.time.Instant cannot be cast to class java.time.chrono.ChronoLocalDateTime
**Describe the bug**
A Java bug while generating field fingerprint :

```
java.lang.ClassCastException: class java.time.Instant cannot be cast to class java.time.chrono.ChronoLocalDateTime (java.time.Instant and java.time.chrono.ChronoLocalDateTime are in module java.base of loader 'bootstrap')
```

**logs**

```
java.lang.ClassCastException: class java.time.Instant cannot be cast to class java.time.chrono.ChronoLocalDateTime (java.time.Instant and java.time.chrono.ChronoLocalDateTime are in module java.base of loader 'bootstrap')
at java_time.chrono$fn__4893.invokeStatic(chrono.clj:35)
at java_time.chrono$fn__4893.invoke(chrono.clj:35)
at java_time.core$fn__2990$G__2970__2997.invoke(core.clj:136)
at java_time.core$before_QMARK_.invokeStatic(core.clj:165)
at java_time.core$before_QMARK_.invoke(core.clj:154)
at metabase.sync.analyze.fingerprint.fingerprinters$earliest.invokeStatic(fingerprinters.clj:143)
at metabase.sync.analyze.fingerprint.fingerprinters$earliest.invoke(fingerprinters.clj:138)
at redux.core$juxt$fn__45867$fn__45872.invoke(core.cljc:37)
at clojure.core$map$fn__5870.invoke(core.clj:2760)
at clojure.lang.LazySeq.sval(LazySeq.java:42)
at clojure.lang.LazySeq.seq(LazySeq.java:51)
at clojure.lang.RT.seq(RT.java:535)
at clojure.core$seq__5402.invokeStatic(core.clj:137)
at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
at clojure.core$reduce.invokeStatic(core.clj:6828)
at clojure.core$into.invokeStatic(core.clj:6895)
at clojure.core$mapv.invokeStatic(core.clj:6903)
at clojure.core$mapv.invoke(core.clj:6903)
at redux.core$juxt$fn__45867.invoke(core.cljc:34)
at redux.core$post_complete$fn__45861.invoke(core.cljc:15)
at clojure.core$map$fn__5862$fn__5863.invoke(core.clj:2742)
at redux.core$post_complete$fn__45861.invoke(core.cljc:15)
at redux.core$juxt$fn__45867$fn__45872.invoke(core.cljc:37)
at clojure.core$map$fn__5870.invoke(core.clj:2760)
at clojure.lang.LazySeq.sval(LazySeq.java:42)
at clojure.lang.LazySeq.seq(LazySeq.java:51)
at clojure.lang.RT.seq(RT.java:535)
at clojure.core$seq__5402.invokeStatic(core.clj:137)
at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
at clojure.core$reduce.invokeStatic(core.clj:6828)
at clojure.core$into.invokeStatic(core.clj:6895)
at clojure.core$mapv.invokeStatic(core.clj:6903)
at clojure.core$mapv.invoke(core.clj:6903)
at redux.core$juxt$fn__45867.invoke(core.cljc:34)
at redux.core$post_complete$fn__45861.invoke(core.cljc:15)
at metabase.sync.analyze.fingerprint.fingerprinters$with_error_handling$fn__46564$fn__46569.invoke(fingerprinters.clj:121)
at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
at metabase.sync.analyze.fingerprint.fingerprinters$with_error_handling$fn__46564.invoke(fingerprinters.clj:121)
at metabase.sync.analyze.fingerprint.fingerprinters$col_wise$fn__46527$fn__46532.invoke(fingerprinters.clj:32)
at clojure.core$map$fn__5873.invoke(core.clj:2766)
at clojure.lang.LazySeq.sval(LazySeq.java:42)
at clojure.lang.LazySeq.seq(LazySeq.java:51)
at clojure.lang.Cons.next(Cons.java:39)
at clojure.lang.RT.next(RT.java:713)
at clojure.core$next__5386.invokeStatic(core.clj:64)
at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:169)
at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
at clojure.core$reduce.invokeStatic(core.clj:6828)
at clojure.core$into.invokeStatic(core.clj:6895)
at clojure.core$mapv.invokeStatic(core.clj:6903)
at clojure.core$mapv.invoke(core.clj:6903)
at metabase.sync.analyze.fingerprint.fingerprinters$col_wise$fn__46527.invoke(fingerprinters.clj:29)
at redux.core$post_complete$fn__45861.invoke(core.cljc:15)
at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
at clojure.core$transduce.invokeStatic(core.clj:6883)
at clojure.core$transduce.invokeStatic(core.clj:6879)
at clojure.core$transduce.invoke(core.clj:6870)
at metabase.sync.analyze.fingerprint$fn__51841$fingerprint_table_BANG___51846$fn__51847.invoke(fingerprint.clj:43)
at metabase.sync.analyze.fingerprint$fn__51841$fingerprint_table_BANG___51846.invoke(fingerprint.clj:41)
at metabase.sync.analyze.fingerprint$fn__52014$fingerprint_fields_BANG___52019$fn__52020.invoke(fingerprint.clj:162)
at metabase.sync.analyze.fingerprint$fn__52014$fingerprint_fields_BANG___52019.invoke(fingerprint.clj:158)
at metabase.sync.analyze.fingerprint$fn__52040$fingerprint_fields_for_db_BANG___52045$fn__52046$fn__52047$iter__52048__52052$fn__52053$fn__52054.invoke(fingerprint.clj:174)
at metabase.sync.analyze.fingerprint$fn__52040$fingerprint_fields_for_db_BANG___52045$fn__52046$fn__52047$iter__52048__52052$fn__52053.invoke(fingerprint.clj:173)
at clojure.lang.LazySeq.sval(LazySeq.java:42)
at clojure.lang.LazySeq.seq(LazySeq.java:51)
at clojure.lang.Cons.next(Cons.java:39)
at clojure.lang.RT.boundedLength(RT.java:1792)
at clojure.lang.RestFn.applyTo(RestFn.java:130)
at clojure.core$apply.invokeStatic(core.clj:667)
at clojure.core$apply.invoke(core.clj:660)
at metabase.sync.analyze.fingerprint$fn__52040$fingerprint_fields_for_db_BANG___52045$fn__52046$fn__52047.invoke(fingerprint.clj:173)
at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:46)
at metabase.query_processor.store$do_with_store.invoke(store.clj:40)
at metabase.sync.analyze.fingerprint$fn__52040$fingerprint_fields_for_db_BANG___52045$fn__52046.invoke(fingerprint.clj:170)
at metabase.sync.analyze.fingerprint$fn__52040$fingerprint_fields_for_db_BANG___52045.invoke(fingerprint.clj:165)
at metabase.sync.analyze$make_analyze_steps$fn__52186.invoke(analyze.clj:108)
at metabase.sync.util$fn__44441$run_step_with_metadata__44446$fn__44450$fn__44452.invoke(util.clj:345)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
at metabase.sync.util$fn__44441$run_step_with_metadata__44446$fn__44450.invoke(util.clj:342)
at metabase.sync.util$fn__44441$run_step_with_metadata__44446.invoke(util.clj:337)
at metabase.sync.util$fn__44633$run_sync_operation__44638$fn__44639$fn__44640.invoke(util.clj:430)
at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
at clojure.core$reduce.invokeStatic(core.clj:6827)
at clojure.core$mapv.invokeStatic(core.clj:6903)
at clojure.core$mapv.invoke(core.clj:6903)
at metabase.sync.util$fn__44633$run_sync_operation__44638$fn__44639.invoke(util.clj:430)
at metabase.sync.util$fn__44633$run_sync_operation__44638.invoke(util.clj:424)
at metabase.sync.analyze$fn__52198$analyze_db_BANG___52203$fn__52204$fn__52205.invoke(analyze.clj:125)
at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
at clojure.core$partial$fn__5839.invoke(core.clj:2623)
at metabase.driver.mongo$eval2344$fn__2345$f__1744__auto____2346.invoke(mongo.clj:91)
at metabase.driver.mongo.util$_with_mongo_connection$fn__1735.invoke(util.clj:205)
at metabase.util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)
at metabase.util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)
at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)
at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)
at metabase.driver.mongo$eval2344$fn__2345.invoke(mongo.clj:90)
at clojure.lang.MultiFn.invoke(MultiFn.java:239)
at metabase.sync.util$sync_in_context$fn__44353.invoke(util.clj:138)
at metabase.sync.util$with_db_logging_disabled$fn__44350.invoke(util.clj:129)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
at metabase.sync.util$with_start_and_finish_logging$fn__44339.invoke(util.clj:114)
at metabase.sync.util$with_sync_events$fn__44334.invoke(util.clj:88)
at metabase.sync.util$with_duplicate_ops_prevented$fn__44325.invoke(util.clj:67)
at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
at metabase.sync.analyze$fn__52198$analyze_db_BANG___52203$fn__52204.invoke(analyze.clj:122)
at metabase.sync.analyze$fn__52198$analyze_db_BANG___52203.invoke(analyze.clj:117)
at metabase.api.database$fn__54643$fn__54645.invoke(database.clj:590)
at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
at clojure.lang.AFn.call(AFn.java:18)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**

1. Use MongoDB
2. Run a database synchro.

I dont know what it cause the exception, ``deletedAt`` is a classic Date field (and it works fine for other field).

**Expected behavior**
fingerprint field should success

**Severity**
field cannot be used

**Additional context**
MongoDB as data base

### PR DESCRIPTION
**Pull request by robdaemon**
During fingerprinting, we can end up trying to compare two datatypes
that are not comparable - ChronoLocalDateTime and Instant. Coerce the
ChronoLocalDateTime to a proper Instant for the comparison to work.

Resolves #12311

[ci all]

### CODE REVIEW

File: src/metabase/sync/analyze/fingerprint/fingerprinters.clj [hunk 1]
```diff
@@ -185,6 +186,14 @@
   String   (->temporal [this] (u.date/parse this))
   Long     (->temporal [this] (t/instant this))
   Integer  (->temporal [this] (t/instant this))
+  ;; this is challenging, because ChronoLocalDate requires a ZoneOffset
+  ;; to work with. Ideally, we would use the database's ZoneOffset, but
+  ;; we don't have access to that here. Use the JVM's systemDefault to
+  ;; convert this.
+  ChronoLocalDateTime (->temporal [this] (.toInstant this
```
Comment (robdaemon) [inline src/metabase/sync/analyze/fingerprint/fingerprinters.clj:193]: if someone has an idea of the best way to get the database's timezone here, I'm all ears

Comment (sbelak) [reply src/metabase/sync/analyze/fingerprint/fingerprinters.clj:193]: Have a look at `query_processor.timezone` if you can use something from there

**Review by sbelak — CHANGES_REQUESTED** [review]
I'm not sure this fully fixes the problem. Dates as strings and dates as numbers still go through different constructors which return incompatible types, so the implementations for `Long` and `Integer` either need to recur so they go through `ChronoLocalDateTime`, or we repeat the same logic there.

File: test/metabase/sync/analyze/fingerprint/fingerprinters_test.clj [hunk 2]
```diff
@@ -11,14 +11,32 @@
...
                     (fingerprinter (field/map->FieldInstance {:base_type :type/DateTime}))
                     [#t "2013" nil #t "2018" nil nil #t "2015"])))
+  (testing "handle ChronoLocalDateTime"
+    (is (= {:global {:distinct-count 2
+                     :nil%           0.0}
+            :type   {:type/DateTime {:earliest "2013-01-01T20:04:00Z"
+                                     :latest   "2018-01-01T04:04:00Z"}}}
+           (transduce identity
+                      (fingerprinter (field/map->FieldInstance {:base_type :type/Temporal}))
+                      [(java.time.LocalDateTime/of 2013 01 01 20 04 0 0)
```
Comment (sbelak) [inline test/metabase/sync/analyze/fingerprint/fingerprinters_test.clj:21]: It would be good to test the code paths from numbers and strings, not just directly inserting the problematic types.

File: src/metabase/sync/analyze/fingerprint/fingerprinters.clj (hunk 1 above)
Comment (robdaemon) [reply src/metabase/sync/analyze/fingerprint/fingerprinters.clj:193]: I started with that, but it complains about the query processor not being initialized. I'm not sure how to do that.

**Comment by robdaemon** [comment]
@sbelak I think I addressed your concern about mixing numbers and strings, but I will need some help with getting the qp.store setup to get the database's timezone.

File: src/metabase/sync/analyze/fingerprint/fingerprinters.clj [hunk 3]
```diff
@@ -157,12 +158,14 @@
...
 
+(declare ->temporal)
+
 (defn- earliest
   ([] nil)
   ([acc]
    (some-> acc u.date/format))
   ([acc t]
-   (if (and t acc (t/before? t acc))
+   (if (and t acc (t/before? t (->temporal acc)))
```
Comment (sbelak) [inline src/metabase/sync/analyze/fingerprint/fingerprinters.clj:168]: I don't think this is a good solution -- if I change the order from string, number to number, string it breaks. I think it would be better to change implementations of `ITemporalCoerceable ` so that they always return the same thing. Something like: `Long     (->temporal [this] (->temporal (t/instant this)))`

**Review by sbelak — CHANGES_REQUESTED** [review]

File: src/metabase/sync/analyze/fingerprint/fingerprinters.clj (hunk 1 above)
Comment (sbelak) [reply src/metabase/sync/analyze/fingerprint/fingerprinters.clj:195]: I think that's only with tests, when this runs for real it's a part of the QP and the store should be initialized already (just reverse engineer which bits of the QP store you need for it to work).

**Review by camsaul — APPROVED** [review]
cool  works for me. Don't forget to set the *Milestone* for the issue this closes.

File: src/metabase/sync/analyze/fingerprint/fingerprinters.clj [hunk 4]
```diff
@@ -182,9 +186,21 @@
 
 (extend-protocol ITemporalCoerceable
   nil      (->temporal [_]    nil)
-  String   (->temporal [this] (u.date/parse this))
-  Long     (->temporal [this] (t/instant this))
-  Integer  (->temporal [this] (t/instant this))
+  String   (->temporal [this] (->temporal (u.date/parse this)))
```
Comment (sbelak) [inline src/metabase/sync/analyze/fingerprint/fingerprinters.clj:189]: Does `String` need recasting as well?

File: src/metabase/sync/analyze/fingerprint/fingerprinters.clj [hunk 5]
```diff
@@ -182,9 +186,21 @@
...
+  ;; convert this.
+  ChronoLocalDateTime (->temporal [this] (.toInstant this
+                                                     (.. (if-let [tz (or (qp.tz/report-timezone-id-if-supported)
+                                                                         (qp.tz/database-timezone-id))]
+                                                           (java.time.ZoneId/of tz)
+                                                           (java.time.ZoneId/systemDefault))
+                                                         (getRules)
+                                                         (getOffset (java.time.Instant/now)))))
+  ChronoZonedDateTime (->temporal [this] (.toInstant this))
   Temporal (->temporal [this] this))
```
Comment (sbelak) [inline src/metabase/sync/analyze/fingerprint/fingerprinters.clj:204]: Is this compatible with all the others?

**Review by sbelak — APPROVED** [review]
LGTM, I'd sleep better if we had a test that tests if all 6 possible types mash together though.

File: src/metabase/sync/analyze/fingerprint/fingerprinters.clj (hunk 5 above)
Comment (robdaemon) [reply src/metabase/sync/analyze/fingerprint/fingerprinters.clj:204]: it seems like it?

**Comment by robdaemon** [comment]
@sbelak okay I can add that test
