### PR TITLE
fix(sdk): cli suggests a relative import path with reminder message

### LINKED ISSUE #50093: Improve the import path suggestions printed into the console in the embedding cli
We should improve the default import path suggestions printed in the console. Also, we should update the console message to tweak the import path to match where their component lives.

We can print this note in the end:

> Make sure the `from` path is valid (depending on your app, you may need to move the components to a new directory).

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/50093

### Description

Uses the last path segment as an [import path](https://www.loom.com/share/a3177f2a91c1404a83ead516effbd436) (e.g. `./src/components/metabase` -> `./metabase`), and print a message to remind users to update the import path to match their app. It also updates the default import path to `./src/components/metabase` to be a more reasonable default.

### Demo

CleanShot 2567-11-20 at 20 38 45@2x

### Checklist

- [x] Tests have been added/updated to cover changes in this PR - Unit

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/cli/steps/show-post-setup-steps.ts [hunk 1]
```diff
@@ -17,11 +18,16 @@ export const showPostSetupSteps: CliStepMethod = async state => {
...
+  const importPath = getSuggestedImportPath(state.reactComponentDir);
+
   const STEP_2 = `
-  Import the component in your React frontend.
-  ${green(`import { AnalyticsPage } from "./${state.reactComponentDir}";`)}
+  Import the component in your React frontend. For example:
+  ${green(`import { AnalyticsPage } from "${importPath}";`)}
+
+  Make sure the import path is valid.
+  Depending on your app, you may need to move the components to a new directory.
```
Comment (jeff-bruemmer) [inline enterprise/frontend/src/embedding-sdk/cli/steps/show-post-setup-steps.ts:28]:
```suggestion
  Depending on your app's directory structure, you may need to move the components to a new directory.
```

**Review by jeff-bruemmer — APPROVED** [review]

**Review by deniskaber — APPROVED** [review]
