### PR TITLE
Fix Collection Tree Collapsing

### LINKED ISSUE #65610: Tree items cannot be collapsed in permissions
:bug:*Bug:  Side panel entries cannot be collapsed* 
Not sure which team this belongs to but the side-panel entries cannot be collapsed back when extended. Quick loom:
<https://www.loom.com/share/975dc583e22e44eb95ec23f36ee00a35>

[Slack Message](https://metaboat.slack.com/archives/C05MPF0TM3L/p1762503499457819?thread_ts=1762503499.457819&cid=C05MPF0TM3L)

### PR DESCRIPTION
**Pull request by iethree**
closes #65610
Closes UXW-2240
Closes UXW-2230

## Description
Checking reference changes was not acting as intended and was causing re-renders in the main app and for tree nodes to be uncloseable in permissions. This moves back to checking deep equality.

CleanShot 2025-11-07 at 14 45 18

- [x] [stress test](https://github.com/metabase/metabase/actions/runs/19178724300)

### CODE REVIEW

File: frontend/src/metabase/common/components/tree/Tree.tsx [hunk 1]
```diff
@@ -50,7 +51,8 @@ function BaseTree({
     }
     const selectedItemChanged =
       previousSelectedId !== selectedId && !expandedIds.has(selectedId);
-    if (selectedItemChanged || data !== prevData) {
+
+    if (selectedItemChanged || !_.isEqual(data, prevData)) {
```
Comment (iethree) [inline frontend/src/metabase/common/components/tree/Tree.tsx]: good point!

File: frontend/src/metabase/common/components/tree/Tree.tsx [hunk 2]
```diff
@@ -6,14 +6,13 @@ import _ from "underscore";
...
 import type { ITreeNodeItem } from "./types";
-import { getAllExpandableIds, getInitialExpandedIds } from "./utils";
+import { getInitialExpandedIds } from "./utils";
 
 interface TreeProps {
   data: ITreeNodeItem[];
   selectedId?: ITreeNodeItem["id"];
   role?: string;
   emptyState?: React.ReactNode;
-  initiallyExpanded?: boolean;
```
Comment (iethree) [inline frontend/src/metabase/common/components/tree/Tree.tsx:15]: this prop was added in the remote sync branch, but wasn't actually used 🤷

File: frontend/src/metabase/common/components/tree/Tree.tsx [hunk 3]
```diff
@@ -1,18 +1,18 @@
...
   onSelect?: (item: ITreeNodeItem) => void;
   rightSection?: (item: ITreeNodeItem) => React.ReactNode;
   TreeNode?: any; // This was previously set to TreeNodeComponent, but after upgrading to react 18, the type no longer played nice with forward ref compontents, including styled components
```
Comment (iethree) [inline frontend/src/metabase/common/components/tree/Tree.tsx:18]: not my fault!!

File: frontend/src/metabase/common/components/tree/utils.tsx [hunk 4]
```diff
@@ -18,21 +18,3 @@ export const getInitialExpandedIds = (
...
-      if (item.children && item.children.length > 0) {
-        ids.push(item.id);
-        traverse(item.children);
-      }
-    }
-  };
-
-  traverse(nodes);
-  return ids;
-};
```
Comment (iethree) [inline frontend/src/metabase/common/components/tree/utils.tsx:38]: not used anymore

**Review by npfitz — APPROVED** [review]
