### PR TITLE
Ensure static visualizations with multiple cards are rendered

### LINKED ISSUE #21559: Bar chart created from scalars in a dashboard is set as a scalar in subscription
**Describe the bug**
When you add a scalar to a dashboard and then add series to the scalar, the card is transformed into a bar chart (or funnel). If you send a subscription of this dashboard, then we send a number rather than a bar chart or a funnel, when both of them are supported.

**Logs**
No logs for this

**To Reproduce**
1) build 2 questions: sum of products filtered by doohickie, and sum of products filtered by gadget
2) add one of them to the dashboard and then add the other one as a series of the dashboard card (see a bar chart being created)
3) subscribe to the dashboard, now see the number being sent instead of a bar chart

[Or Flamber's repro
](https://github.com/metabase/metabase/issues/21559#issuecomment-1095190220)

**Expected behavior**
if we support the chart as a static viz, we should send it!

**Screenshots**
Dashboard
image

Subscription (it will only send the first series as well, so keep this in mind for the fix)
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 20.04.4
- Your databases: Postgres 14.2
- Metabase version: 1.42.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
None

**Additional context**
Customer that reported this mentioned that they were using this feature to do barcharts as they couldn't get the data into the same database to build a barchart viz

### PR DESCRIPTION
**Pull request by tsmacdonald**
[Fixes #21559]

Given this card in a dashboard:

image

Slack alerts used to look like this:

image

and now they look like this:

image

:arrow_up: this was due to an order bug in `detect-pulse-chart-type`.

A thornier issue is that when multiple scalar cards are combined they should result in a bar chart (see screenshots in [the below comment](https://github.com/metabase/metabase/pull/25811#issuecomment-1277599092)), which had to be fixed by creating the `render-multiple-scalars` function you see.

### CODE REVIEW

File: src/metabase/pulse/render.clj [hunk 1]
```diff
@@ -86,6 +86,11 @@
              (= @col-sample-count @row-sample-count 1))
         (chart-type :scalar "result has one row and one column")
 
+        (and (some? maybe-dashcard)
+             (pos? (count (dashboard-card/dashcard->multi-cards maybe-dashcard)))
+             (not (#{:combo} display-type)))
+        (chart-type :multiple "result has multiple card semantics, a multiple chart")
+
```
Comment (tsmacdonald) [inline src/metabase/pulse/render.clj:93]: literally just an order bug in `detect-pulse-chart-type`. Glad it turned out to be that simple! And shoutout to Howon for doing the hard parts back in December

**Comment by tsmacdonald** [comment]
Got it working with scalar / bar charts now, both with one extra card and with multiple:

image

File: src/metabase/pulse/render/body.clj [hunk 2]
```diff
@@ -536,32 +547,54 @@
...
+        multi-data   (cons data (map #(get-in % [:result :data]) multi-res))
+        x-rows       (map :name cards) ;; Bar labels
+        y-rows       (mapcat :rows multi-data)
+        x-cols       [{:base_type :type/Text
+                       :effective_type :type/Text}]
+        y-cols       (select-keys (first (:cols data)) [:base_type :effective_type])
+        series       (multiple-scalar-series :bar (mapv vector x-rows (flatten y-rows)) x-cols y-cols viz-settings)
+        labels       (combo-label-info x-cols y-cols viz-settings)
+        settings     (->ts-viz (first x-cols) (first y-cols) labels viz-settings)]
+    (attach-image-bundle (image-bundle/make-image-bundle render-type (js-svg/combo-chart series settings)))))
```
Comment (tsmacdonald) [inline src/metabase/pulse/render/body.clj:590]: Could DRY up the first bits of `render-multiple-lab-chart` and `render-multiple-scalars`, but tbh I feel like the duplicated code is easier to read. There's so many individual variables floating around that there's not a great way to shorten things by much.

**Review by metamben — APPROVED** [review]
👍

**Review by adam-james-v — APPROVED** [review]
Things are looking good to me here! I like the idea you had to pull out the attachment map into `attach-image-bundle`, good thinking!

As well, I agree with leaving a bit of duplicated logic for multi scalar and multi-lab cases. That definitely keeps things clear and more readable.
