### PR TITLE
Make sure the query to fetch result_metadata for native sandboxes doesn't use the streaming results handler

### LINKED ISSUE #49985: Sandboxing using a parameterized SQL card errors until an admin runs the sandboxing card successfully for the first time
### Describe the bug

Breaking this out from https://github.com/metabase/metabase/issues/49969

When a non-admin user attempts to query a table with sandboxing applied via a parameterized SQL question, they encounter the error: `Current context not Array but root`. The error appears if the question has not yet been successfully executed with a parameter value. Once an admin user runs the parameterized question successfully with a parameter, the non-admin query works without issue.

Investigation so far:
The error seems to be coming from the `.writeEndArray` method on the `com.fasterxml.jackson.core.JsonGenerator` object, used in streaming results back to the client. `begin!` on the `StreamingResultsWriter` doesn't seem to be called properly, so when `finish!` is called, it's trying to terminate a JSON array that was never started. 

Not sure yet why `begin!` doesn't get called in this case, or why running the card as an admin fixes it.

### To Reproduce

1. As an admin, create and save a SQL question like `select * from products where category = {{cat}}`. Don't run the question with template
2. Create a non-admin test user and give them the attribute `cat = Gizmo`
3. Sandbox the non-admin user on the Products table, using the SQL question as the source, and link the user's `cat` attribute with the template tag
4. Log in as the non-admin and try to run an ad-hoc query over the Products table. You should get the error `Current context not Array but root`
5. As the admin, run the SQL question again with a parameter value
6. As the non-admin, run the ad-hoc query again. It should now succeed.
7. As the admin, edit the SQL question in any way and re-save it, without re-running it. Now it will be broken again for the non-admin.

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
Current master (4418173684) but repros at least back to 51.3
```

### Severity

Unsure about p1 or p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes https://github.com/metabase/metabase/issues/49985, https://github.com/metabase/metabase/issues/38888 and https://github.com/metabase/metabase/issues/49671

Slack thread: https://metaboat.slack.com/archives/C064EB1UE5P/p1731532799297809

If a native sandbox doesn't have query metadata saved, it fires off another query to fetch it, in the course of executing the outer (sandboxed) query. But the streaming code binds `qp.pipeline/*result*` to its own handler (`streaming-result-fn`) which calls `finish!` on the streaming results-writer.

So essentially the inner query to fetch query metadata was prematurely terminating the stream. And when the outer query finishes, it doesn't have anything to terminate, leading to a JSON-writing error. My fix here is to reset the `*result*` var to its default implementation before we run the inner query to fetch the metadata.

I've also re-enabled an e2e test that had been originally disabled due to this issue. It actually seemed to be working fine even without this fix, so maybe it had been inadvertently fixed for some other reason in the past, but that's why there are two other issues that this closes. Also added a backend test, and re-enabled a separate (unrelated) e2e reproduction that had previously been fixed for good measure.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#50049** <a href="https://app.graphite.dev/github/pr/metabase/metabase/50049?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/metabase/metabase/50049?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj [hunk 1]
```diff
@@ -173,12 +174,13 @@
 
 (mu/defn- native-query-metadata :- [:+ :map]
   [source-query :- [:map [:source-query :any]]]
-  (let [result (mw.session/as-admin
-                 ((requiring-resolve 'metabase.query-processor/process-query)
-                  {:database (u/the-id (lib.metadata/database (qp.store/metadata-provider)))
-                   :type     :query
-                   :query    {:source-query source-query
-                              :limit        0}}))]
+  (let [result (binding [qp.pipeline/*result* qp.pipeline/default-result-handler]
```
Comment (escherize) [inline enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj:177]: I think we should have a comment explaining why this binding occurs, since it's super not obvious. Nice job finding this problem btw!

**Review by escherize — APPROVED** [review]
Nice find
