### PR TITLE
Fix unable to disable scan field values

### LINKED ISSUE #40715: Advanced option to turn off syncing field values doesn't work
### Describe the bug

In the database setting you have an 3 advanced options to control field values syncing. When you select “Only when adding a new filter widget” or “Never, I’ll do this manually if I need to”, the existing field values sync job should be removed. Right now the jobs are still there and sync will continue to happens

### To Reproduce

1. Go to Admin -> Database setting
2. Go down to "Scanning field values" and select "Never, I'll do this manually if I need to"
3. Make this query:  ```select * from qrtz_triggers where trigger_name = 'metabase.task.update-field-values.trigger.<YOUR-DB-ID>';```. This should return nothing

### Expected behavior

There is no scheduled triggers for syncing field values

### Logs

_No response_

### Information about your Metabase installation

```JSON
master, and probably has been like this since forever
```

### Severity

unexpected behavior

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
First part to fix https://github.com/metabase/metabase/issues/40715

This will fix it so that there will be no background jobs for scanning field values when creating or updating a DB with scan FV options: "Only when adding a new filter" or "Never, I'll do it myself."

I'll have another follow-up to introduce a migration that will remove all the existing scan field values jobs for existing DBs that turn off Scan field values.

### CODE REVIEW

File: src/metabase/models/interface.clj [hunk 1]
```diff
@@ -471,8 +471,8 @@
 (methodical/prefer-method! #'t2.before-insert/before-insert :hook/timestamped? :hook/entity-id)
 
 ;; --- helper fns
-(defn pre-update-changes
-  "Returns the changes used for pre-update hooks.
+(defn row-with-changes
```
Comment (qnkhuat) [inline src/metabase/models/interface.clj:474]: `pre-update-changes` was a bit confusing, one can think of it as the "changes" before the "update".

File: test/metabase/api/database_test.clj [hunk 2]
```diff
@@ -245,68 +248,102 @@
...
-      (let [monthly-schedule {:schedule_type "monthly" :schedule_day "fri" :schedule_frame "last"}
-            {:keys [details metadata_sync_schedule cache_field_values_schedule]}
+      (let [{:keys [details metadata_sync_schedule cache_field_values_schedule]}
             (create-db-via-api! {:schedules {:metadata_sync      monthly-schedule
                                              :cache_field_values monthly-schedule}})]
         (is (not (:let-user-control-scheduling details)))
         (is (= "daily" (-> cache_field_values_schedule u.cron/cron-string->schedule-map :schedule_type)))
         (is (= "hourly" (-> metadata_sync_schedule u.cron/cron-string->schedule-map :schedule_type)))))))
 
-(deftest create-db-test-4
```
Comment (qnkhuat) [inline test/metabase/api/database_test.clj:297]: is replaced with `create-db-with-manual-schedules-test`

File: test/metabase/test/data/impl/get_or_create.clj [hunk 3]
```diff
@@ -147,9 +148,11 @@
     ;; Add DB object to Metabase DB
     (let [connection-details (tx/dbdef->connection-details driver :db database-definition)
           db                 (first (t2/insert-returning-instances! Database
-                                                                    :name    database-name
-                                                                    :engine  (u/qualified-name driver)
-                                                                    :details connection-details))]
+                                                                    (merge
```
Comment (qnkhuat) [inline test/metabase/test/data/impl/get_or_create.clj:151]: this is needed, otherwise the DB won't have scan field values schedule, as it previously rely on having a default value in the DB.

File: src/metabase/task/sync_databases.clj [hunk 4]
```diff
@@ -238,63 +241,71 @@
...
+        (cron/with-misfire-handling-instruction-do-nothing))))))
+
+(defn- update-db-trigger-if-needed!
+  "Replace or remove the existing trigger if the schedule changes, do nothing if schedule is the same."
+  [database task-info]
+  (let [job                                 (task/job-info (job-key task-info))
+        new-trigger                         (trigger database task-info)
+        ;; there should be only one schedule per task per DB
+        existing-trigger-with-same-schedule (when new-trigger
+                                              (some #(when (and (= (:key %) (.. new-trigger getKey getName))
```
Comment (crisptrutski) [inline src/metabase/task/sync_databases.clj:271]: nitpick: I think this would be better as a `(first (filter ...))`, so you can avoid the awkward `when` block. 

I'd also hoist out `trigger-key` (`(.. new-trigger getKey getName)`) and `task-schedule` (`(cron-schedule database task-info)`) since those don't change, and they're making the predicate quite dense.

File: src/metabase/task/sync_databases.clj [hunk 5]
```diff
@@ -238,63 +241,71 @@
...
+
+     ;; need to recreate the new trigger
+     (and (some? new-trigger)
+          (nil? existing-trigger-with-same-schedule))
+     (do
+      (log/infof "Trigger for \"%s\" of Database \"%s\" is now \"%s\""
+                 (:name task-info)
+                 (:name database)
+                 (cron-schedule database task-info))
+      ;; delete all existing triggers just to be sure
```
Comment (crisptrutski) [inline src/metabase/task/sync_databases.clj:293]: It could be nice to log if there were duplicates that we implicitly removed.

**Review by crisptrutski — APPROVED** [review]
LGTM, nicely encapsulated.

A lot of logging has been removed, are you sure we want to go so minimal? For example we used to show the configuration that was being overridden.

File: src/metabase/api/database.clj [hunk 6]
```diff
@@ -779,14 +780,40 @@
...
+    [true true false]
+    (do
+     (assert (every? #(some? (% schedules)) [:cache_field_values :metadata_sync]))
+     (sync.schedules/schedule-map->cron-strings schedules))
+
+    ;; "Only when adding a new filter" or "Never, I'll do it myself"
+    ;; -> Sync metadata only
+    [true false _]
+    ;; schedules should only contains metadata_sync, but FE might sending both
+    ;; so we just manually dissoc it here
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/api/database.clj:801]: ah right, I was dissoc cache_field_values from schedules before but I then decided that I want to implicit asosc it with nil value.

File: src/metabase/models/interface.clj [hunk 7]
```diff
@@ -471,8 +469,8 @@
...
+  "The object merged with the changes in pre-update hooks.
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/models/interface.clj:473]: row it is :)

File: src/metabase/task/sync_databases.clj (hunk 4 above)
Comment (qnkhuat) [reply src/metabase/task/sync_databases.clj:271]: the `when` part is needed else `(.. new-trigger .getKey)` will throw an error because `new-trigger` is nil.

Agree with hosting out `triger-key` and `task-schedule`. I'll make a nested `let`.

File: src/metabase/task/sync_databases.clj (hunk 5 above)
Comment (qnkhuat) [reply src/metabase/task/sync_databases.clj]: trigger key has a unique constraint, and our naming for the trigger is unique per task per DB so it should be no duplicated triggers.

we will only delete the existing one.

tried to make it a bit nicer here(8fbfcf71fe) wdyt?

File: src/metabase/api/database.clj (hunk 6 above)
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/api/database.clj]: 8fbfcf71fe

File: src/metabase/models/interface.clj (hunk 7 above)
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/models/interface.clj]: 8fbfcf71fe

File: resources/migrations/001_update_migrations.yaml [hunk 8]
```diff
@@ -5551,6 +5551,29 @@ databaseChangeLog:
...
+            tableName: metabase_database
+            columnName: cache_field_values_schedule
+            columnDataType: varchar(254)
+      # nothing because it should always be like this
+      rollback:
+
+  - changeSet:
+      id: v49.2024-04-09T10:00:01
+      author: qnkhuat
+      comment: Drop not null constraint on metabase_database.cache_field_values_schedule
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply resources/migrations/001_update_migrations.yaml]: 8fbfcf71fe

**Comment by qnkhuat** [comment]
> A lot of logging has been removed, are you sure we want to go so minimal? For example we used to show the configuration that was being overridden.

The overridden is certainly nice but it would make the `after-update` hook a bit more complicated and I don't think it's worth it given the new log is quite informative.

File: src/metabase/task/sync_databases.clj (hunk 4 above)
Comment (crisptrutski) [reply src/metabase/task/sync_databases.clj]: You could also just make trigger-key nullable by using a when in its definition, if you want to save nesting.

File: src/metabase/task/sync_databases.clj (hunk 5 above)
Comment (crisptrutski) [reply src/metabase/task/sync_databases.clj]: Yeah that's much clearer!

**Comment by crisptrutski** [comment]
Nice amendments ✨

**Comment by qnkhuat** [comment]
@crisptrutski I made some updates, the main thing is I've moved the check to the hooks instead in API layer. There is a couple of places where we insert DB manually (analytics DB) and this will make sure everything is checked probably.

Also I think it makes more sense there in the first place.

**Comment by qnkhuat** [comment]
Can't merge this yet because the UI is currently broken.

File: src/metabase/api/database.clj [hunk 9]
```diff
@@ -808,13 +808,11 @@
...
                                         :details      details-or-error
                                         :is_full_sync is_full_sync
-                                        :is_on_demand (boolean is_on_demand)
+                                        :is_on_demand is_on_demand
                                         :cache_ttl    cache_ttl
                                         :creator_id   api/*current-user-id*}
-                                       (sync.schedules/schedule-map->cron-strings
-                                        (if (:let-user-control-scheduling details)
-                                          (sync.schedules/scheduling schedules)
-                                          (sync.schedules/default-randomized-schedule)))
```
Comment (crisptrutski) [inline src/metabase/api/database.clj:817]: Orthogonal to your changes, but it feels strange that we re-randomize their schedule whenever this endpoint is hit, even if it already as non user defined.

**Comment by crisptrutski** [comment]
> I've moved the check to the hooks instead in API layer.

Makes sense, and simplifies things nicely 👌 

Approval sustained 🧑‍⚖️

**Comment by qnkhuat** [comment]
FE is fixed. Thanks @nemanjaglumac
