### PR TITLE
fix: scheduler state management in cloud migration

### LINKED ISSUE #57307: Migrate to Cloud Fails
### Describe the bug

The "Migrate to Cloud" option from the admin panel fails with error:
"Scheduler is already started, cannot start temporary one"

### To Reproduce

1. Start Metabase locally
2. Go to "Admin -> Cloud -> Try for Free" and initiate a cloud migration
3. Follow the store setup wizard and initiate the migration
4. See it fails

### Expected behavior

MIgration should work

### Logs

[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 ERROR liquibase.changelog ChangeSet migrations/001_update_migrations.yaml::v46.00-086::calherries encountered an exception.,clojure.lang.ExceptionInfo: Scheduler is already started, cannot start temporary one {:toucan2/context-trace [["resolve connection" {:toucan2.connection/connectable org.h2.jdbc.JdbcConnection}] ["resolve connection" {:toucan2.connection/connectable nil}]]},	at metabase.db.custom_migrations.util$do_with_temp_schedule.invokeStatic(util.clj:32),	at metabase.db.custom_migrations.util$do_with_temp_schedule.invoke(util.clj:15),	at metabase.db.custom_migrations.DeleteAbandonmentEmailTask$with_connection_STAR___47477$with_transaction_STAR___47478.invoke(custom_migrations.clj:197),	at toucan2.connection$bind_current_connectable_fn$fn__23365.invoke(connection.clj:104),	at metabase.db.connection$do_transaction$thunk__46810.invoke(connection.clj:140),	at metabase.db.connection$do_transaction.invokeStatic(connection.clj:162),	at metabase.db.connection$do_transaction.invoke(connection.clj:136),	at metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection.invokeStatic(connection.clj:196),	at metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection.invoke(connection.clj:169),	at methodical.impl.combo.common$partial_STAR_$fn__20021.invoke(common.clj:13),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at toucan2.connection$do_with_transaction_around_method_toucan2_connection_default.invokeStatic(connection.clj:249),	at toucan2.connection$do_with_transaction_around_method_toucan2_connection_default.invoke(connection.clj:245),	at methodical.impl.combo.common$partial_STAR_$fn__20021.invoke(common.clj:13),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:58),	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47),	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:212),	at metabase.db.custom_migrations.DeleteAbandonmentEmailTask$with_connection_STAR___47477.invoke(custom_migrations.clj:196)
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.util UPDATE SUMMARY
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.util -------------------------------
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.util DBMS mismatch:               52
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.util FILTERED CHANGE SETS SUMMARY
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.util Filtered out:                52
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.util Previously run:               0
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.util Run:                        474
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.util Total change sets:          526
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.util Update summary generated
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.command Update command encountered an exception.
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.lockservice Successfully released change log lock
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.command Command execution complete
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.command Logging exception.
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO liquibase.lockservice Successfully released change log lock
[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 ERROR metabase.cmd.copy [FAIL]

[a4e76f8b-521e-40a8-a7b6-dfb27d26f85b] 2025-04-26T11:08:22-05:00 INFO metabase.cloud-migration.models.cloud-migration Migration failed

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-04-23",
      "tag": "v1.54.4.2",
      "hash": "f0764bf"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "5.15.167.4-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

blcoking cloud mirgation

### Additional context

Customer reported running 54.3. Tested locally on 54.4.

### PR DESCRIPTION
**Pull request by edpaget**
Closes https://github.com/metabase/metabase/issues/57307

### Description

When we create the h2 database to dump a metabase instance to during cloud migration we need to stop and start the quartz scheduler instance running on the instance during the migration.

Some liquibase migrations handling quartz job changes expect to control the scehduler and start/stop it while those migrations run. Recent changes to guard against this behaviour in testing case these migrations to throw an exception when they run during the cloud migration task.

This also fixes an older bug that the quartz scheduler would remain off on the instance being migrated after the cloud migration task finishes.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Start a new cloud migration
2. it should not error

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/cloud_migration/models/cloud_migration.clj [hunk 1]
```diff
@@ -235,7 +245,7 @@
           (do
             (t2/update! :model/CloudMigration id {:state :error})
             (log/info "Migration failed")
-            (throw (ex-info "Error performing migration" {:error e})))))
+            (throw (ex-info "Error performing migration" {} e)))))
```
Comment (edpaget) [inline src/metabase/cloud_migration/models/cloud_migration.clj:248]: Can revert this if this breaks something, but wanted to set the cause rather than packing an exception into the arbitrary data map.

File: src/metabase/cloud_migration/models/cloud_migration.clj [hunk 2]
```diff
@@ -226,6 +230,12 @@
       (log/info "Notifying store that upload is done")
       (http/put (migration-url external_id "/uploaded"))
 
+      ;; Need to restore the previous scheduler configuration because the database quartz is pointing at has changed
+      ;; after finishing the dump to h2 migration
+      (task.bootstrap/set-jdbc-backend-properties! (mdb/db-type))
```
Comment (edpaget) [inline src/metabase/cloud_migration/models/cloud_migration.clj:235]: The jdbc adapter for quartz is controlled through a system property and it changed when the 'temp' scheduler macro runs without being reset afterwards.

**Review by nvoxland — APPROVED** [review]
