### PR TITLE
Fix: Search box when saving question does not trigger on type

### LINKED ISSUE #28210: Search box while saving question does not trigger on type
**Describe the bug**
When searching collection to save a question, the search box does trigger on type. Only trigger on pressing "enter".

**To Reproduce**
1. New question
2. Sample Database -> Accounts
3. Click Save
4. Click to choose collection
5. Click search
6. Start typing --  notice search is not triggered
7. Press enter -- only now search is triggered

**Expected behavior**
The search is triggered by typing

**Screenshots**

https://user-images.githubusercontent.com/25661381/218076562-40517cf3-4e48-4feb-8185-90ec9d0eed0e.mov

**Information about your Metabase Installation:**
master(7e3048bf73f6cb7527579446166d054292166163)

**Severity**
Nothing serious, just make UX more reactive

### PR DESCRIPTION
**Pull request by oisincoveney**
Closes https://github.com/metabase/metabase/issues/28210

### Description

Since the `ItemPicker` component didn't handle real-time updates of search text, I needed to add some logic to handle debounced text and updating text without the user needing to press "Enter." I wanted to keep the amount of code change as small as possible, so I added the debounce logic to the `ItemPicker` component itself to ensure that other components that rely on an "Enter" keypress can still use the component, but we can also use a debounced, auto-updating search text to update search results automatically.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question
2. Sample Database -> Accounts
3. Click Save
4. Click to choose collection
5. Click search
6a. Start typing -- search should be triggered **_only for searching collections_**

6b. For any other contexts (i.e. searching for dashboards when saving a question), only the keypress should trigger the search

### Demo

The video below shows the same `ItemPicker` parent component in two contexts:
1) Saving a Question to a dashboard using the `DashboardPicker`
2) Searching for collections using the `CollectionPicker`

You can see that, when picking dashboards, we don't have real-time updates. For collections, we do. Maybe we should add this for dashboards as well (and set the default behavior of this component to use debouncing + auto-updates).

https://user-images.githubusercontent.com/25306947/229832163-86f00100-0d63-4251-9c27-5fbe4e3c11bf.mov

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29800)

### CODE REVIEW

File: frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx [hunk 1]
```diff
@@ -74,13 +78,33 @@ function ItemPickerView({
 
   const isPickingNotCollection = models.some(model => model !== "collection");
 
+  // We have the searchString here to act as the middle-man for different search
+  // behaviors. i.e. with the debounce, we can use the useDebouncedValue hook,
+  // or with a keypress we can only set the parent's search text on "Enter"
+  const [searchText, setSearchText] = useState(searchString);
```
Comment (ranquild) [inline frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx:84]: Could we make `SearchInput` a "controlled" component by passing `searchValue` to set its value? Since the component is re-rendered there would be no performance difference, but the controlled component approach would make it much more straightforward and the comment here won't be needed.

File: frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx [hunk 2]
```diff
@@ -59,6 +62,7 @@ function ItemPickerView({
   searchString,
   searchQuery,
   showSearch = true,
+  useDebouncedSearch = false,
```
Comment (ranquild) [inline frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx:65]: I believe we don't need a separate prop here since we don't want to have one `ItemPicker` with search that supports typeahead and another one that doesn't. Could you rely on `isSearchEnabled` instead?

Comment (oisincoveney) [reply frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx:65]: Yeah that was the main question I had about the behavior. Would we be ok with a typeahead for all components that implement `ItemPicker` then?

Comment (oisincoveney) [reply frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx:65]: Then we definitely should be relying on `isSearchEnabled`

File: frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js [hunk 3]
```diff
@@ -138,7 +149,11 @@ async function setup({
     },
   );
 
-  await waitForElementToBeRemoved(() => screen.queryByText("Loading..."));
+  // sometimes it expects entities to be in the Redux store so there might not be a loading state
+  // ex: collections are stored in Redux, so there isn't a meaningful loading state here
+  if (waitForInitialLoad) {
```
Comment (ranquild) [inline frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js:154]: I'd drop this extra flag and made it work without id. Something like this could work:
```
await waitFor(() => {
  expect(screen.queryByText("Loading...")).not.toBeInTheDocument();
});
```

Comment (oisincoveney) [reply frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js]: Ok sweet I added that in, looks like the test still passes as well

**Review by ranquild — APPROVED** [review]

**Comment by mazameli** [comment]
@oisincoveney, this feels nice to me (and does seem to work for me on the add-to-a-dashboard context). 

The only thing I wonder about is if we've considered how this will perform on instances that have e.g. 10,000 or 100,000 collections or dashboards etc. Do we think the debouncing will be enough to prevent it spamming search queries across that quantity of collections or dashboards?

**Comment by oisincoveney** [comment]
> @oisincoveney, this feels nice to me (and does seem to work for me on the add-to-a-dashboard context).
> 
> The only thing I wonder about is if we've considered how this will perform on instances that have e.g. 10,000 or 100,000 collections or dashboards etc. Do we think the debouncing will be enough to prevent it spamming search queries across that quantity of collections or dashboards?

Good question. On the spam issue, I think the debounce is an improvement since we now have control over how many network requests that will be sent, and we can now guarantee that a network request can only be sent every few seconds (and we can make the debounce longer if we really need it). I went back to a commit before this PR to try things out, and it seems like users would be able to spam the text box if they decided to smash the enter key, and we had no way to stop this. 

image

Obviously, this behavior isn't exactly common, but I think the user experience improvement is worth it to the vast majority of users who won't do this. We could also add some other preventative measures (i.e. searching only when >3 characters are entered, extending the debounce period, etc) if you think we need it.


On performance on larger entity lists, I'll need to defer to @kulyk @ranquild. I think a search on 10k or 100k would still be fine but I'll let the guys with more experience answer this one 😄
