### PR TITLE
Preserve FK key metadata on native models

### LINKED ISSUE #42130: [BE] [QP] [Bug] Incorrect metadata for a native model column overriden to a FK
`should allow drills on FK columns from dashboards` E2E test fails because there is a mismatch between metadata in `/api/table/card__:id/query_metadata` and `/api/card/:id`. [Run link](https://app.replay.io/team/dzoyNTM4ZjRmOC05YmFlLTRiYjYtYjljYi1jOGYzOWUyMjRhZWY=/runs?testRunId=626f055a-eefb-4146-96b5-140dc39cf2ff&testId=dHJ0OjliZDEzY2U0NjhiZjU4ZTlkNDkyYmZjMWFiYWE1Y2JkMTBjMDhhN2U%3D)

Screenshot 2024-05-01 at 15 40 25
Screenshot 2024-05-01 at 15 40 36

Actual:
- `semantic_type` of the overriden field in `query_metadata` is null but `type/FK` in `/api/card/:id`

Expected:
- `semantic_type` is the same in both endpoints - `type/FK` in this case

The issue is present in `master`, but since we moved some stuff to MBQL lib it started to cause issues because of https://github.com/metabase/metabase/blob/0633cd87702d085791aa73efd4a12b3a96127673/src/metabase/lib/card.cljc#L107

### PR DESCRIPTION
**Pull request by metamben**
Fixes #42130.

This PR assumes that the only way a native model can have columns with FK semantic types is if a user specified it by editing the metadata.

**TODO**
- [ ] unit test

### CODE REVIEW

File: src/metabase/api/table.clj [hunk 1]
```diff
@@ -442,14 +443,18 @@
                                                                         [:= :most_recent true]]
                                                              :order-by [[:id :desc]]
                                                              :limit    1}
-                                                            :id id)
+                                             :id id)
                                            first :status)
-        db (t2/select-one Database :id database_id)]
+        db (t2/select-one Database :id database_id)
+        ;; a native model can have columns with keys as semantic types on if a user specified it
+        trust-semantic-keys? (and (= (:type card) :model)
```
Comment (ranquild) [inline src/metabase/api/table.clj:450]: A regular (mbql) model can also have metadata overrides with FKs for columns that are not FKs in the DB

File: src/metabase/api/table.clj [hunk 2]
```diff
@@ -442,14 +443,18 @@
...
+                                     (= (-> card :dataset_query :type) :native))]
```
Comment (ranquild) [inline src/metabase/api/table.clj:451]: A regular (mbql) model can also have metadata overrides with FKs for columns that are not FKs in the DB

Comment (metamben) [reply src/metabase/api/table.clj:451]: @ranquild Do you have an example when that information gets lost? (The FK override on mbql models worked for me.)

Comment (ranquild) [reply src/metabase/api/table.clj:451]: I don't have an example. I think you're right and that's the fix we need to do. It should be safe to "trust" FK metadata on native queries because it won't be set automatically.

**Review by ranquild — APPROVED** [review]

File: src/metabase/api/table.clj (hunk 2 above)
Comment (metamben) [reply src/metabase/api/table.clj:451]: I've just noticed the typo in the comment. I meant "only if a user specified it", not "on if a user specified it".
