### PR TITLE
[svg] Limit the lifetime of a cached Truffle JS object to sidestep apparent memory leaks

### LINKED ISSUE #50726: Resource leak during automated report generation (subscriptions)
### Describe the bug

At 08:00 (local time) a lot of automated reports are generated for subscriptions in our Metabase install. It seems every day Metabase leaks some resources when this happens. Until the point where Metabase can't really function anymore due to GC pressure and has to be restarted.

Image

As far as I can tell this resource leak seems to be only present for the report generation for subscriptions.

I took a quick look with Eclipse MAT which seems to imply this is related to the generation of SVG's. The following screenshot is from Eclipse MAT when Metabase has been running for a couple of days. There was no activity (no visitors, no subscription report generation, etc.) at the time the heap dump was made:

Image

Image

If your interested I can send the heap dump via a private channel.

### To Reproduce

I haven't been able to create a standalone reproducer.

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-15",
      "tag": "v0.50.35-SNAPSHOT",
      "hash": "cd31b54"
    },
    "settings": {
      "report-timezone": "Europe/Amsterdam"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.3-internal-adhoc.pkgsrc.jdk-il-jdk-21.0.3-ga",
    "java.vendor": "N/A",
    "java.vendor.url": "https://openjdk.org/",
    "java.version": "21.0.3-internal",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.3-internal-adhoc.pkgsrc.jdk-il-jdk-21.0.3-ga",
    "os.name": "SunOS",
    "os.version": "5.11",
    "user.language": "en",
    "user.timezone": "Europe/Amsterdam"
  }
}
```

### Severity

Medium

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexander-yakushev**
https://github.com/metabase/metabase/issues/50726 hints that there can be a memory leak inside Truffle JS engine object. I couldn't reproduce the leak locally, but I assume it is possible. Since we are unlikely to dig inside the implementation to address or at least understand the leak, our second best bet is not to retain the engine object forever. Currently, the reusable engine is kept in a timeless delay. Ideally, we would want the lifetime of the reused engine to be tied to some finite event, like a request or a trigger. But it appears to me that `metabase.channel.render.js.svg` has multiple users and hence multiple entrypoints; so, it will be cumbersome to rewrite this API so that callers have to set up the engine explicitly.

The proposed band-aid replaces the regular `delay` with a custom `delay-with-ttl`. Think of it as of a cache with TTL but for a single value only and which guarantees that only one thread will compute the value concurrently. I've set the TTL to be 1 hour which is completely arbitrary and might not prevent the leak from inflating too much in some cases (when there are a lot of subscriptions?). I suppose the TTL can be reduced to 5-10 minutes without becoming too expensive.

### CODE REVIEW

File: test/metabase/util/delay_test.clj [hunk 1]
```diff
@@ -0,0 +1,13 @@
+(ns ^:mb/once metabase.util.delay-test
+  (:require [clojure.test :refer :all]
+            [metabase.util.delay :as delay]))
+
+(set! *warn-on-reflection* true)
+
+(deftest delay-with-ttl-test
+  (let [d (delay/delay-with-ttl 100 #(Object.))
+        vals1 (doall (repeatedly 20 (fn [] @d)))
```
Comment (metamben) [inline test/metabase/util/delay_test.clj:9]: Why 20 and not 2 (for example)? I wonder how long before some strange virtual machine pauses for 100 ms between two calls...

File: src/metabase/channel/render/js/svg.clj [hunk 2]
```diff
@@ -42,9 +44,13 @@
...
 (def ^:private static-viz-context-delay
-  "Delay containing a graal js context. It has the chart bundle and the above `src-api` in its environment suitable
-  for creating charts."
-  (delay (load-viz-bundle (js.engine/context))))
+  "Delay containing a graal js context. It has the chart bundle and the above `src-api` in its environment suitable for
+  creating charts. However, under some circumstances, the Truffle JS engine tends to leak memory, so we don't want to
+  keep the reference to the engine forever. Ideally, we would like to make the engine lifetime bound to a single
+  request or something like that, but that would introduce a lot of changes and noise to the system. Hence, with this
+  bandaid, we keep the JS engine for some reasonable time (1 hour) before recreating it."
+  (delay/delay-with-ttl (.toMillis TimeUnit/HOURS 1)
```
Comment (metamben) [inline src/metabase/channel/render/js/svg.clj:52]: I would set the timeout as low as possible while keeping the overhead negligible. If instantiating the engine every 5-10 minutes has negligible overhead, then why don't we do that?

**Review by metamben — APPROVED** [review]
LGTM

File: test/metabase/util/delay_test.clj (hunk 1 above)
Comment (alexander-yakushev) [reply test/metabase/util/delay_test.clj:9]: True, this has a flake potential. I'll probably tune the test differently to reduce the chance of it happening further.

File: src/metabase/channel/render/js/svg.clj (hunk 2 above)
Comment (alexander-yakushev) [reply src/metabase/channel/render/js/svg.clj:52]: Initializing the engine takes 3-4 seconds on my machine. I suppose, setting it to 10 minutes for now should be fine. This can be reduced if a similar problem ever happens again.
