### PR TITLE
Do not create new revision when revert dashboard

### LINKED ISSUE #30776: Reverting to an earlier version of a dashboard creates an erroneous event in revision history
### Describe the bug

In the revision history sidebar of a dashboard, I clicked the revert button next to an entry `You removed a card`. The revision took place successfully and added the `You reverted to an earlier version` event to the history, but it also added an additional `You added a card` event that should not be there, as no card was added.

https://github.com/metabase/metabase/assets/37751258/4404756b-7a29-4dbf-8575-50ec2b94ca2a

### To Reproduce

1. Create a dashboard with some cards
2. Remove one of the cards then click save
3. Add some more cards then click save
4. Open the history sidebar and click the revert button for the entry titled `You removed a card`

### Expected behavior

The `You added a card` event should not be there

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.6+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "17.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.6+10",
    "os.name": "Mac OS X",
    "os.version": "13.0",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-05-09",
      "src_hash": "df21d2a3b9cc66963ccbc45fa1896505342e77fe",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "collections",
      "hash": "b17328c"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Very minor annoyance

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/30776

This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30868)

### CODE REVIEW

File: test/metabase/api/revision_test.clj [hunk 1]
```diff
@@ -361,3 +361,35 @@
                  (map #(select-keys % [:description :has_multiple_changes])
                       (mt/user-http-request :crowberto :get 200 "revision" :entity "card" :id card-id))))
           (t2/delete! :model/Card :id card-id))))))
+
+(deftest revert-does-not-create-new-revision
+  (testing "revert a dashboard that previously added cards should not create new revision(#30869)"
```
Comment (calherries) [inline test/metabase/api/revision_test.clj:366]: The first time I read this I was a little confused, because reverting a dashboard should create exactly one revision - the one that says "reverted to an earlier version.". I think this should read:
```suggestion
  (testing "revert a dashboard that previously added cards should not recreate duplicate revisions(#30869)"
```

**Review by calherries — APPROVED** [review]
Looks good

**Comment by qnkhuat** [comment]
Changed the base to target this PR https://github.com/metabase/metabase/pull/30502
