### PR TITLE
fix: show confirmation on escape, clickoutside and browser's back actions for SidebarCacheForm

### LINKED ISSUE #53825: No unsaved changes warning when closing question caching settings via modal backdrop click or navigating back
### Describe the bug

https://github.com/user-attachments/assets/c541a513-dbd2-4303-9584-c0505364da21

### To Reproduce

**Scenario A**: clicking modal backdrop

1. New > Question > Orders > Save > Visualize
2. Click "..."
3. Click "Edit settings"
4. Click "Use default" to edit caching settings
5. Click "Duration"
6. Click modal backdrop

❌ Modal is closed

**Scenario B**: navigating back

1. New > Question > Orders > Save > Visualize
2. Click "..."
3. Click "Edit settings"
4. Click "Use default" to edit caching settings
5. Click "Duration"
6. Hit "back" browser button

❌ Modal is closed

### Expected behavior

Modal is not closed, unsaved changes warning is shown (just like when hitting "x" or modal title)

### Information about your Metabase installation

master, d8ed6a46df177bb8c71fb46c9a05cc0a5d453e0f

### Severity

P2

### PR DESCRIPTION
**Pull request by egorgrushin**
Closes https://github.com/metabase/metabase/issues/53825

### Description
The issue was because two mantine's modals are rendered at the same time - 'default' (the first) and 'caching' (the second).   The second one has a confirmation modal if user makes the form dirty. Moreover, the second one was rendered without overlay. This two factors caused situation when clicking outside / pressing Esc while the second one was opened didn't call `onClose` callback of it. Instead, `onClose` callback of the first one was called, which caused closing all with no confirmation.

Mantine's modal doesn't provide a proper way to control stacked modals with closing cancelation. Instead of building new modals systems I found a trick that allowed to fix this issues.

First, in order to allow the second one handle click outside events it has to be rendered with the overlay. But this overlay overlaps first one's overlay which causes more darkening. The trick is to open the second one with overlay, but make it transparent so it continues to capture click events, but totally invisible for the user that avoids double darkening. 

Second, to make Esc event be handled by second one, the first one should be rendered with prop `closeOnEscape=false` while the second one lives.

Finally, to provide the same confirmation when user clicks browser's back button I rewrote `useConfirmOnRouteLeave` hook, because previous one didn't work as `withRouter` HOC didn't provide `route` value. Additionally, `useConfirmOnRouteLeave` hook sometimes didn't restore browser's url. Tests `useConfirmOnRouteLeave` are also added

P.S. I added an ability to get `router` instance across application without property drilling using new hook `useRouter` instead.

P.P.S I added a `useStackedModals` hook that incapsulates this behavior.

### How to verify
See original [issue](https://github.com/metabase/metabase/issues/53825)

### Demo
Before:
https://github.com/user-attachments/assets/de30ecb9-1efa-4768-9de3-bb06c7ae699d

After:
https://github.com/user-attachments/assets/b87dbbab-2cb0-4090-bfcf-da4bb16b3daf

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/admin/performance/hooks/useConfirmIfFormIsDirty.tsx [hunk 1]
```diff
@@ -29,17 +24,19 @@ export const useConfirmIfFormIsDirty = (
...
   useConfirmOnRouteLeave({
-    router,
-    route,
     shouldConfirm: isStrategyFormDirty,
     confirm: askBeforeDiscardingChanges,
   });
   useBeforeUnload(isStrategyFormDirty);
 
+  const guardAction = (action: () => void) =>
+    isStrategyFormDirty ? askBeforeDiscardingChanges(action) : action();
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmIfFormIsDirty.tsx]: This hook's API does not need to get more complex - the consumer already has access to `askBeforeDiscardingChanges` and `isStrategyFormDirty`.

File: frontend/src/metabase/common/components/Sidesheet/Sidesheet.tsx [hunk 2]
```diff
@@ -20,6 +20,9 @@ interface SidesheetProps {
   /** use this if you want to enable interior scrolling of tab panels */
   removeBodyPadding?: boolean;
   withOverlay?: boolean;
+  /** Invisible overlay to prevent double darkening while preserving click-outside handling */
+  withTransparentOverlay?: boolean;
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/components/Sidesheet/Sidesheet.tsx]: 2 overlay-specific props make it a bit confusing. Also one prop depends on the other.
Can we make it 1?

This comment also applies to `SidesheetSubPage.tsx`.

File: frontend/src/metabase/common/hooks/use-confirmation.tsx [hunk 3]
```diff
@@ -43,26 +43,29 @@ export const useConfirmation = () => {
...
+        title,
+        message,
+        onConfirm,
+        onCancel,
+        confirmButtonText,
+        cancelButtonText,
+        confirmButtonProps,
+        size,
+      }),
+    [setConfirmationState],
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/hooks/use-confirmation.tsx]: Redundant hook dep

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.tsx [hunk 4]
```diff
@@ -1,45 +1,43 @@
...
+      router.setRouteLeaveHook(currentRoute, (nextLocation) => {
+        if (confirmedRef.current || !shouldConfirm) {
+          return true;
+        }
+        /**
+         * This will roll browser's URL back.
+         * Returning false from this function cancels routing on the redux level, but browser's URL changes anyway.
+         * So we need to roll this change back and then roll forward if user confirms.
+         */
+        router.go(1);
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.tsx]: nit: this reads slightly better:

```suggestion
        router.goForward();
```

Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.tsx]: Technically this works under assumption that user clicks the browser back button to navigate only 1 page back.
But you can press-and-hold the back button to navigate to any other point in history.
However, there's no way of telling how far user is navigating back.

Interestingly, this code works even in that case - the hook (and `router.go(1)`) will run for every route in the history.

Not sure if this was intentional, but it works well :)

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+    renderWithProviders(
+      <div>
+        <Route path="/a" component={PageA} />
+        <Route path="/b" component={ConfirmingPage} />
+      </div>,
+      { withRouter: true, initialRoute: "/a" },
+    );
+
+  // Shared happy-path to the confirmation dialog after attempting to leave /b
+  const navigateToBAndTriggerBack = async (history: any) => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx]: Please do not use `any`

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,107 @@
...
+import { Route } from "react-router";
+
+import { act, renderWithProviders, screen } from "__support__/ui";
+import { checkNotNull } from "metabase/lib/types";
+
+import { useConfirmOnRouteLeave } from "./useConfirmOnRouteLeave";
+
+const ConfirmingPage = () => {
+  const [showConfirm, setShowConfirm] = useState(false);
+  const onConfirmRef = useRef<(() => void) | null>(null);
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx]: Is this used in any meaningful way in this suite?
We should probably assert it being called.

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx [hunk 7]
```diff
@@ -0,0 +1,107 @@
...
+  const navigateToBAndTriggerBack = async (history: any) => {
+    const guardedHistory = checkNotNull(history);
+
+    // Navigate to /b to create a history entry to go back from
+    act(() => {
+      guardedHistory.push("/b");
+    });
+
+    // Ensure we're on /b
+    await screen.findByText("Form B");
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx]:
```suggestion
    expect(screen.getByText("Form B")).toBeInTheDocument();
```

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+      <div>
+        <Route path="/a" component={PageA} />
+        <Route path="/b" component={ConfirmingPage} />
+      </div>,
+      { withRouter: true, initialRoute: "/a" },
+    );
+
+  // Shared happy-path to the confirmation dialog after attempting to leave /b
+  const navigateToBAndTriggerBack = async (history: any) => {
+    const guardedHistory = checkNotNull(history);
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx:35]: We usually do the `checkNotNull` assertion in `setup` so that all tests can benefit from it.
With that, `navigateToBAndTriggerBack` wouldn't have to `return` anything.

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx [hunk 9]
```diff
@@ -0,0 +1,107 @@
...
+    // Ensure we're on /b
+    await screen.findByText("Form B");
+    expect(guardedHistory.getCurrentLocation().pathname).toBe("/b");
+
+    // Simulate browser back, which should trigger confirmation and roll URL forward
+    act(() => {
+      guardedHistory.goBack();
+    });
+
+    await screen.findByRole("dialog");
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx]:
```suggestion
    expect(screen.getByRole("dialog")).toBeInTheDocument();
```

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx [hunk 10]
```diff
@@ -0,0 +1,107 @@
...
+  it("navigates to the previous route when clicking 'Yes' in the confirmation", async () => {
+    const { history } = setup();
+
+    const guardedHistory = await navigateToBAndTriggerBack(history);
+
+    // Confirm leaving
+    await userEvent.click(screen.getByText("Yes"));
+
+    // We should navigate to /a
+    await screen.findByText("Page A");
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx]:
```suggestion
    expect(screen.getByText("Page A")).toBeInTheDocument();
```

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts [hunk 11]
```diff
@@ -0,0 +1,81 @@
...
+  withOverlay: boolean;
+};
+
+type GetModalPropsReturn = {
+  /**
+   * to support both Sidesheet and mantine's Modal property.
+   * To fix it rename Sidesheet's prop
+   */
+  opened: boolean;
+  isOpen: boolean;
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: This is a code smell indicating props spreading mess.

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts [hunk 12]
```diff
@@ -0,0 +1,81 @@
...
+  ): GetModalPropsReturn =>
+    _.defaults(override, {
+      isOpen: state[key] ?? false,
+      opened: state[key] ?? false,
+      onClose: () => close(key),
+      closeOnEscape: key === currentModal,
+      withOverlay,
+      /** Invisible overlay to prevent double darkening while preserving click-outside handling */
+      withTransparentOverlay: withOverlay && key !== firstOpenedModal,
+    });
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: :x: This is too magic.

We've had our share of pain dealing with props spreading in this project.
It makes it difficult to read code and track the flow of information.

Explicit props are almost always better (there [are exceptions](https://github.com/metabase/metabase/blob/f12e3320190ef52a325fefbab9e3a5a0ea5324ba/frontend/src/metabase/ui/components/feedback/Loader/Loader.tsx#L12-L14), of course).

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts [hunk 13]
```diff
@@ -0,0 +1,81 @@
...
+  /**
+   * to support both Sidesheet and mantine's Modal property.
+   * To fix it rename Sidesheet's prop
+   */
+  opened: boolean;
+  isOpen: boolean;
+  onClose: () => void;
+  closeOnEscape: boolean;
+  withOverlay: boolean;
+  withTransparentOverlay: boolean;
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: Unused

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts [hunk 14]
```diff
@@ -0,0 +1,81 @@
...
+};
+
+export const useStackedModals = <TKeys extends string>({
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: This is a rather complex abstraction. Things would have been simpler if data didn't have to flow through it.
We don't need n modals support either, and the hook is only used in 2 places.

How about we keep things simple and not worry about the minimal duplication?

File: frontend/src/metabase/router/useRouter.tsx [hunk 15]
```diff
@@ -0,0 +1,11 @@
+import { useContext } from "react";
+
+import { RouterContext } from "./RouterProvider";
+
+export const useRouter = () => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/router/useRouter.tsx:5]: This will come in handy :+1: 
After this is merged, let's inform engineers about it in Slack.

**Review by kamilmielnik — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/common/hooks/use-confirmation.tsx (hunk 3 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-confirmation.tsx]: It's not because `show` is used in useConfirmOnRouterLeave useEffect deps. I had some issues with constant useEffect recreating.

File: frontend/src/metabase/admin/performance/hooks/useConfirmIfFormIsDirty.tsx (hunk 1 above)
Comment (egorgrushin) [reply frontend/src/metabase/admin/performance/hooks/useConfirmIfFormIsDirty.tsx]: Otherwise the consumers duplicate the usage. I think, since the main reason of this hook is to guard actions - we need the most simple API for that

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 11 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: This two different props was already in the project, so I just didn't want to refactor all Sidesheet's usages in the project in this PR. I was going to create another one which will get rid of this.

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 12 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: This is very handy way to make powerful things in react - it's called Prop Getters pattern (or something like this). Can we discuss it more before we deny it? 
If it's typed correctly, it's easy to track the flow of information.

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 13 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: Why it's not? It is used in getModalProps fn and then is passed to Sidesheet component

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 14 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: This is the main "fixer" of the bug. The thing is that we support several stacked modals already and Mantine doesn't provide a good way to control them. In order to make it work properly you need to control two props `closeOnEscape` and `withTransparentOverlay` for two different modals. So the main reason I've created this not just to avoid duplication, but to incapsulate this "special" knowledge of controlling two stacked modals. 

Moreover, it's just a helper of managing Modal's props, no data goes through this hook, it's not a wrapper

File: frontend/src/metabase/common/components/Sidesheet/Sidesheet.tsx (hunk 2 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/components/Sidesheet/Sidesheet.tsx]: They don't depends strongly on each other. Sidesheet could be rendered with overlay, but it will be dark. Or without overlay, or with, but transparent. 

More over, this two props are from Modal's props. And since Sidesheet wraps Modal, it must have a way to control its behavior because as a consumer of Sidesheet I don't need to know whether there is a Modal inside or not. I just need to know that Sidesheet render something that has overlay.

And third, with this approach Sidesheet and Modal components become polymorphic. That also means, you can use `useStackedModals` hook in more generic way

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.tsx (hunk 4 above)
Comment (egorgrushin) [reply frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.tsx]: You raised a very good point, Kamil! I also don't understand why is this works well enough 

It works even if user has "forward" button as well. 

And however, I faced some flake issues with that, I don't want to spend so much time right now to imitate rollbacks using history api - it still will be quite dirty and unnatural comparing to browser's native behavior.

File: frontend/src/metabase/admin/performance/hooks/useConfirmIfFormIsDirty.tsx (hunk 1 above)
Comment (kamilmielnik) [reply frontend/src/metabase/admin/performance/hooks/useConfirmIfFormIsDirty.tsx]: > Otherwise the consumers duplicate the usage

It's a single condition, and there is a single consumer.

> we need the most simple API for that

When reading code of the consumer, it's easier to understand the intent here:

```tsx
      onBack={() =>
        isStrategyFormDirty ? askBeforeDiscardingChanges(onBack) : onBack()
      }
```

than here:
```tsx
      onBack={() => guardAction(onBack)}
```

In the latter you can't be sure without navigating into `guardAction` definition.

File: frontend/src/metabase/common/components/Sidesheet/Sidesheet.tsx (hunk 2 above)
Comment (kamilmielnik) [reply frontend/src/metabase/common/components/Sidesheet/Sidesheet.tsx]: > They don't depends strongly on each other.

`withTransparentOverlay` won't work without `withOverlay = true`.\
2 boolean props give 4 scenarios, but we only need to support 3 of them.

> with this approach Sidesheet and Modal components become polymorphic.

I don't understand this. Can you please explain?

> 2 overlay-specific props make it a bit confusing. (...) Can we make it 1?

Please consider 3 alternative approaches:
1. Merge `withOverlay?: boolean` and `withTransparentOverlay?: boolean` into `overlay?: "solid" | "transparent" | false`
2. Merge `withOverlay?: boolean` and `withTransparentOverlay?: boolean` into `overlay?: ReactNode`
3. Keep `withOverlay?: boolean` as is, but introduce `overlayProps?: ModalOverlayProps` instead of `withTransparentOverlay` (and yes, spread them :wink: )

File: frontend/src/metabase/common/hooks/use-confirmation.tsx (hunk 3 above)
Comment (kamilmielnik) [reply frontend/src/metabase/common/hooks/use-confirmation.tsx]: I'm not saying the hook is redundant. The dep is.

```suggestion
    [],
```

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 11 above)
Comment (kamilmielnik) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: Functions should not assume where or how will they be used.
Two aliases for the same attribute introduce duplication and confusion.

> I just didn't want to refactor all Sidesheet's usages in the project in this PR

That wouldn't be necessary.

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 13 above)
Comment (kamilmielnik) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: Right. I confused it with `Props`.

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts [hunk 16]
```diff
@@ -0,0 +1,81 @@
...
+    // the modal is not rendered until it is "open"
+    // but we want to set it open after it mounts to get
+    // pretty animations
+    open(defaultOpened);
+  });
+
+  const getModalProps = (
+    key: TKeys,
+    // TODO(egorgrushin): introduce mergeProps pattern
+    override?: Partial<GetModalPropsReturn>,
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: We wouldn't need this if consumer fully controlled (i.e. didn't spread result of this function) which props it chooses to pass to the modal.

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 12 above)
Comment (kamilmielnik) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]:
```tsx
{...getModalProps("caching", { onClose: handleClose })}
```

The only way to figure out what props are actually passed to the component is to read the `getModalProps` definition, and then come back to the consumer and see if any of these props were later overridden.

This makes it better:

```tsx
const { closeOnEscape, isOpen, withOverlay, onClose  } = getModalProps("caching", { onClose: handleClose });

/* ... */

closeOnEscape={closeOnEscape}
isOpen={isOpen}
withOverlay={withOverlay}
onClose={onClose}
```

And with suggestion from lines 62-63, even better:

```tsx
const { closeOnEscape, isOpen, withOverlay  } = getModalProps("caching");

/* ... */

closeOnEscape={closeOnEscape}
isOpen={isOpen}
withOverlay={withOverlay}
onClose={handleClose}
```

**Review by kamilmielnik — COMMENTED** [review]
@egorgrushin Please have a look at all comments from my previous review. I think you may have missed them because [GitHub collapsed them](https://github.com/user-attachments/assets/5b9a53d1-2762-48c1-bc80-853076c465a9)?

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts [hunk 17]
```diff
@@ -0,0 +1,81 @@
+import { useState } from "react";
```
Comment (chodorowicz) [inline frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: [question](https://pullpo.io/cc?l=question) 
You wrote that

> Mantine's modal doesn't provide a proper way to control stacked modals with closing cancelation. Instead of building new modals systems I found a trick that allowed to fix this issues.

Can explain why we cannot use Mantine's [useModalStack](https://mantine.dev/core/modal/#usemodalsstack-hook) to manage multiple modals? Is it lacking something specific?

**Review by chodorowicz — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 12 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: I got you. I'd like to stop discussion here because whether to provider props implicit or explicit is a matter of taste:). However, all modern libraries do that. For example Mantine's modals do the same. I will leave it like you want and maybe we can discuss it further later, like in RFC discussions.

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 17 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: It is. At the start, I wanted to use it inside my hook. But it doesn't track the first and the latest opened modalId which is crucial for that "hack". It does track, but internally I guess, no public api for that.

File: frontend/src/metabase/admin/performance/hooks/useConfirmIfFormIsDirty.tsx (hunk 1 above)
Comment (egorgrushin) [reply frontend/src/metabase/admin/performance/hooks/useConfirmIfFormIsDirty.tsx]: Ok, I accept this comment. I'd rather renamed it, but let's keep it as you suggest

File: frontend/src/metabase/common/components/Sidesheet/Sidesheet.tsx (hunk 2 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/components/Sidesheet/Sidesheet.tsx]: third option is great, it is much better and cleaner. Thank you, Kamil!

File: frontend/src/metabase/common/hooks/use-confirmation.tsx (hunk 3 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-confirmation.tsx]: Yes, you're right, the reference never changes. Thank you

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx (hunk 5 above)
Comment (egorgrushin) [reply frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx]: My mistake, I hate using any. Didn't checked after AI. I think we should add eslint restriction for specs too

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.unit.spec.tsx [hunk 18]
```diff
@@ -0,0 +1,59 @@
...
+    </div>
+  );
+};
+
+describe("useStackedModals", () => {
+  it("closes only the last opened sidesheet on Escape", async () => {
+    render(<TestComponent />);
+
+    // First should open by default (after mount)
+    await screen.findByText("First");
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.unit.spec.tsx]:
```suggestion
    expect(screen.getByText("First")).toBeInTheDocument();
```

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.unit.spec.tsx [hunk 19]
```diff
@@ -0,0 +1,59 @@
...
+    expect(screen.queryByText("Second")).not.toBeInTheDocument();
+
+    // Open the second modal
+    await userEvent.click(screen.getByText("Open second"));
+    await screen.findByText("Second");
```
Comment (kamilmielnik) [inline frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.unit.spec.tsx]:
```suggestion
    expect(screen.getByText("Second")).toBeInTheDocument();
```

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx [hunk 20]
```diff
@@ -0,0 +1,82 @@
...
+    // Navigate to /b to create a history entry to go back from
+    act(() => history.push("/b"));
+
+    // Ensure we're on /b
+    expect(screen.getByText("Page B")).toBeInTheDocument();
+    expect(history.getCurrentLocation().pathname).toBe("/b");
+
+    // Simulate browser back, which should trigger confirmation and roll URL forward
+    act(() => history.goBack());
+    return history;
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx]:
```suggestion
```

File: frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx [hunk 21]
```diff
@@ -0,0 +1,82 @@
...
+    );
+    const guardedHistory = checkNotNull(history);
+    return {
+      ...rest,
+      history: guardedHistory,
+    };
+  };
+
+  // Shared happy path for remaining on the /b route after an attempted exit
+  const navigateToBAndTriggerBack = async (history: History) => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.unit.spec.tsx]: This file does not need any `async`/`await` keywords (there are 3 + 2)

**Review by kamilmielnik — APPROVED** [review]

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 17 above)
Comment (chodorowicz) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: Maybe I'm missing something but I've tried to use [useModalStack](https://mantine.dev/core/modal/#usemodalsstack-hook) in your PR and it works fine, both with clicking outside and escape key → https://github.com/metabase/metabase/pull/66359/commits/b367b3e6060c5e7ab3ccef1f2a839ca18344215f

https://github.com/user-attachments/assets/3875c231-db4d-428f-bb7e-41b36fc1c1d8

If we would need something even more advanced, to manage 3+ modals, then [Modals Manager](https://mantine.dev/x/modals/) seems quite useful, but in a simple case of 2 modals it seems it's not even needed.

**Review by chodorowicz — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 17 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: In that case you:
1. have a flickering overlay which is not good (it shouldn't flicker and it didn't before) - for that you need to know which modal is opened first.
2. need to control two props closeOnEscape and withTransparentOverlay for two different modals in specific way which will fix a bug.

So, again, the main reason I've created this not just to avoid duplication, but to incapsulate this "special" knowledge of controlling two stacked modals and to provide nice UX.

Comment (chodorowicz) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: 1. With this simple change there's no flicker: https://github.com/metabase/metabase/pull/66359/commits/0381d021d9dbc44d6a6ada7c761e4e1c0323e150

We're creating here a new abstraction, over 130 lines of code (implementation with tests), to use it in two places., where without it the alternative fix would be as simple (same number of lines, just more explicit) and we might not use this hook more times.  Those rules came to my mind now  [AHA - Avoid Hasty Abstractions](https://kentcdodds.com/blog/aha-programming) or [WET/Rule of Three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)).

I would just leave a simple fix, but I'm not treating this as a blocker, so you have ✅  from me.

**Review by chodorowicz — APPROVED** [review]

File: frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts (hunk 17 above)
Comment (egorgrushin) [reply frontend/src/metabase/common/hooks/use-stacked-modals/useStackedModals.ts]: Okay, I decided to get rid of the hook. + added e2e tests for that behavior.

**Comment by egorgrushin** [comment]
@kamilmielnik @chodorowicz Okay, I decided to get rid of the hook. Plus added e2e tests for that behavior. Please, check

File: frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/QuestionSettingsSidebar.tsx [hunk 22]
```diff
@@ -31,24 +31,26 @@ export const QuestionSettingsSidebar = ({
...
-  });
+  const { open, state, close } = useModalsStack(["default", "caching"]);
+
+  const currentModal: keyof typeof state = state.caching
+    ? "caching"
+    : "default";
 
-  const defaultModalProps = getModalProps("default");
-  const cachingModalProps = getModalProps("caching");
+  useMount(() => {
```
Comment (chodorowicz) [inline frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/QuestionSettingsSidebar.tsx:40]: [praise](https://pullpo.io/cc?l=praise) 
for leaving comments 🙌

**Review by chodorowicz — APPROVED** [review]
Nice!  🙌

File: e2e/test/scenarios/admin/performance/helpers/e2e-strategy-form-helpers.ts [hunk 23]
```diff
@@ -138,6 +138,9 @@ export const openSidebarCacheStrategyForm = (
 export const cacheStrategySidesheet = () =>
   cy.findByRole("dialog", { name: /Caching settings/ }).should("be.visible");
 
+export const confirmModal = () =>
+  cy.findByTestId("confirm-modal").should("be.visible");
```
Comment (kamilmielnik) [inline e2e/test/scenarios/admin/performance/helpers/e2e-strategy-form-helpers.ts]: That's not a strategy-form-specific helper. Let's find a better home for it.

File: e2e/test/scenarios/dashboard/dashboard.cy.spec.js [hunk 24]
```diff
@@ -1685,6 +1687,49 @@ describe("scenarios > dashboard > caching", () => {
...
+      () =>
+        cacheStrategySidesheet().within(() =>
+          cy.findByRole("button", { name: /Caching settings/ }).click(),
+        ),
+    ].forEach((attempt) => {
+      attempt();
+      confirmModal().within(() => {
+        // cancel to attempt closing other way
+        cy.findByRole("button", { name: /Cancel/ }).click();
+      });
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard/dashboard.cy.spec.js]:
```suggestion
      // cancel to attempt closing other way
      confirmModal().findByRole("button", { name: /Cancel/ }).click();
```

File: e2e/test/scenarios/dashboard/dashboard.cy.spec.js [hunk 25]
```diff
@@ -1685,6 +1687,49 @@ describe("scenarios > dashboard > caching", () => {
...
+          .should("have.length", 2)
+          .last()
+          .click(),
+      // // clicking on title with back icon on it
+      () =>
+        cacheStrategySidesheet().within(() =>
+          cy.findByRole("button", { name: /Caching settings/ }).click(),
+        ),
+    ].forEach((attempt) => {
+      attempt();
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: The test would have been simpler to read (and shorter) without this `forEach`

**Review by kamilmielnik — APPROVED** [review]
Looks good!

The tests could be a bit simpler - left a few comments.

File: e2e/test/scenarios/dashboard/dashboard.cy.spec.js (hunk 25 above)
Comment (egorgrushin) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: In that case it will be several times copypasted ` confirmModal().findByRole("button", { name: /Cancel/ }).click();` line. It's a nature of this test to be looped - it's a list of attempt that should be made. It was two more action before (cy.back and cy.forward), but I couldn't make it work with cy - the router.setRouteLeaveHook wasn't called.

Comment (kamilmielnik) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: > In that case it will be several times copypasted

Nothing wrong with that

Comment (kamilmielnik) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: > It was two more action before (cy.back and cy.forward), but I couldn't make it work with cy - the router.setRouteLeaveHook wasn't called.

These are important to get in. Did you try `cy.go("back")` and `cy.go("forward")`?

Comment (egorgrushin) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: > These are important to get in. Did you try `cy.go("back")` and `cy.go("forward")`?
Yes, I understand that. Yes, I did. I also tried to call `cy.visit("/")` in the start of the test to populate the history - otherwise the back button will try to leave the whole app.

Comment (kamilmielnik) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: > I also tried to call cy.visit("/") in the start of the test to populate the history - otherwise the back button will try to leave the whole app.

That's _almost_ the correct way - you can start with `cy.visit("/")` and navigate to the dashboard via UI interactions - that should properly populate history entries.

Comment (kamilmielnik) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: Example: https://github.com/metabase/metabase/blob/6199e0056f0efe5a979327fd595b4b7997da4f4b/e2e/test/scenarios/models/reproductions.cy.spec.ts#L1195-L1200

Comment (egorgrushin) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: Yes, it does't work neither your way, nor mine. cy.go("back") routes to previous route without being stopped by `router.setRouteLeaveHook`:
image

However, it works when you test it manually

Comment (kamilmielnik) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: This patch works:

```diff
diff --git a/e2e/test/scenarios/dashboard/dashboard.cy.spec.js b/e2e/test/scenarios/dashboard/dashboard.cy.spec.js
index b3daba475e4..ef8489323d2 100644
--- a/e2e/test/scenarios/dashboard/dashboard.cy.spec.js
+++ b/e2e/test/scenarios/dashboard/dashboard.cy.spec.js
@@ -1694,7 +1694,9 @@ describe("scenarios > dashboard > caching", () => {
    */
   it("should guard closing caching form if it's dirty on different actions", () => {
     interceptPerformanceRoutes();
-    H.visitQuestion(ORDERS_QUESTION_ID);
+    cy.visit("/");
+    cy.findByText("Our analytics").click();
+    cy.findByText("Orders").click();
 
     openSidebarCacheStrategyForm("question");
 
@@ -1723,6 +1725,7 @@ describe("scenarios > dashboard > caching", () => {
         cacheStrategySidesheet()
           .findByRole("button", { name: /Caching settings/ })
           .click(),
+      () => cy.go("back"),
     ].forEach((attempt) => {
       attempt();
       // cancel to attempt closing other way
```

Comment (egorgrushin) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: Wow, you are good, @kamilmielnik

**Comment by iethree** [comment]
I just want point out that this PR involved weeks of effort, spawned over 60 PR comments, changed 27 files, and added two global context providers to the entire frontend application in order to fix what isn't even a bug, but a minor rough edge to user experience in a pretty niche enterprise feature that only admins will see. 

I haven't dug in enough to be able to judge if a simpler fix is feasible, and it does seem that those global providers might be helpful in other situations, but keep in mind that not every assigned ticket has to be completed. "This is more trouble than it's worth" is a very valid, and often, extremely wise choice to make.

**Comment by egorgrushin** [comment]
> I just want point out that this PR involved weeks of effort, spawned over 60 PR comments, changed 27 files, and added two global context providers to the entire frontend application in order to fix what isn't even a bug, but a minor rough edge to user experience in a pretty niche enterprise feature that only admins will see.
> 
> I haven't dug in enough to be able to judge if a simpler fix is feasible, and it does seem that those global providers might be helpful in other situations, but keep in mind that not every assigned ticket has to be completed. "This is more trouble than it's worth" is a very valid, and often, extremely wise choice to make.

Yes, it is

File: e2e/test/scenarios/dashboard/dashboard.cy.spec.js [hunk 26]
```diff
@@ -1688,6 +1691,52 @@ describe("scenarios > dashboard > caching", () => {
...
+        .findByRole("button", { name: /Cancel/ })
+        .click();
+    // Action 1: clicking on cross button
+    cacheStrategySidesheet().findByRole("button", { name: /Close/ }).click();
+    cancelModal();
+    // Action 2: ESC button
+    cy.get("body").type("{esc}");
+    cancelModal();
+    // Action 3: click outside
+    cy.findAllByTestId("modal-overlay").should("have.length", 1).last().click();
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: `findByTestId` will fail if there's more than 1 matching element

```suggestion
    cy.findByTestId("modal-overlay").click();
```

Comment (egorgrushin) [reply e2e/test/scenarios/dashboard/dashboard.cy.spec.js]: We need to click on the top one. This means we need to call `.last()`. But calling `last` without checking the length will faill by eslint rule. I've changed to
```
    // Action 3: click outside
    // When a user clicks somewhere outside he basically clicks on the top one
    cy.findAllByTestId("modal-overlay")
      .should("have.length.gte", 1)
      .last()
      .click();
```
