### PR TITLE
fix(sdk): decrease specificity of css reset in embedding sdk

### LINKED ISSUE #47344: Remove default borders from entity picker's button in the sdk's CreateQuestion component
The entity picker in create question are dependent on CSS resets being available - the default button style with gray borders are appearing. If we add `appearance: none` and `border: none` to the button, it should get rid of the browser-default grey border.

This happens when you use `<CreateQuestion />` SDK component in a React application that does not have CSS resets for buttons.

Image

### LINKED ISSUE #47561: Notebook editor's entity picker button and the pick columns button is different in size in the sdk
In the notebook editor, the button for entity picker and the "pick columns" button directly on the right size has a slight size difference. It is supposed to be of equal size.

CleanShot 2567-09-03 at 20 47 38@2x

### PR DESCRIPTION
**Pull request by npretto**
### Description

Context: in [first iteration to scope sdk styles to our components (+161 −198)](https://github.com/metabase/metabase/pull/47764) I added a "scoped" css reset to fix a bunch of issue, it created another issue though, as the scoped css reset was overriding some of our code.
Let's take the button reset, its selector was `.{emotion-class} button` which had [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) `(0,1,1)`.

Most of our styles have specificity `(0,1,0)` though, which means that the reset will win over it and that's why some buttons didn't have background-color even if it was set.

This PR addresses the issue hopefully for good.
There reason why it works is in a comment in the code, if that explanation is not good enough please tell me so we can update it

Issues that *should* be fixed with this, or are already fixed but this should make it official, please verify it when reviewing it 🙏 

Closes https://github.com/metabase/metabase/issues/47344
Closes https://github.com/metabase/metabase/issues/47561

Note: this has no tests because it's not currently easy to test for visual changes, today or tomorrow I'll share with the team a small document where I'll propose something about it

### CODE REVIEW

**Review by oisincoveney — APPROVED** [review]
so glad this got figured out

File: enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx [hunk 1]
```diff
@@ -48,3 +37,19 @@ export const PublicComponentStylesWrapper = styled.div`
     display: inline;
   }
 `;
+/**
+ * We can't apply a global css reset as it would leak into the host app but we
+ * can't also apply our entire css reset scoped to this container, as it would
+ * be of higher specificity than some of our styles.
+ *
+ * The reason why this works is two things combined:
+ * - `*:where(button)` doesn't increase specificity, so the resulting specificity is (0,1,0)
```
Comment (npretto) [inline enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx:46]: I didn't want this to become a wall of text, but both * and :where don't increase specificity (something I learned in these past days)
