### PR TITLE
Robust `InitSendPulseTriggers`

### LINKED ISSUE #58004: Some Notifications Aren’t Scheduled if Send Begins Before Qrtz Triggers are Initialized on Startup
### Describe the bug

We recreate all of the send-pulse quartz triggers each time an instance starts. This results in a window during which Quartz does not yet contain all the scheduled subscriptions, causing some to be missed.

### To Reproduce

1. Create a test dashboard with 300 - 400 subscriptions that run hourly (I just used the task runner in Postman to do this the lazy way)
2. A minute before the hourly notification run restart the instance (or initialize a 2nd one on the same app db)
3. Note the triggers are being recreated in the "QRTZ_TRIGGERS" table
4. The send job will likely start before the triggers have finished creating in the table 
5. However many pulse triggers were int he table at the time the send process beings is the number of emails you'll get; the rest won't send until the next run (unless we have another poorly timed scaling event)

I was able to replicate this locally with a few hundred notifications but we have customers with thousands of subscriptions.

Looms:

- [Longer video with more details](https://www.loom.com/share/c5425b8a18d5479e947363f6d43ac750)
- [The short version](https://www.loom.com/share/6e8bbc2da0464f82a60a4705517570bc)

### Expected behavior

All subscriptions scheduled for the hour should be sent.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "databricks",
      "druid-jdbc",
      "postgres",
      "mongo",
      "redshift",
      "bigquery-cloud-sdk",
      "snowflake",
      "athena",
      "h2",
      "clickhouse",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-05-15",
      "tag": "vUNKNOWN",
      "hash": "fa63153"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

severe

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Closes https://github.com/metabase/metabase/issues/58004

The `InitSendPulseTriggers` background job was running on every startup were deleting all dashboard subscriptions triggers then recreate each of them.

This makes it so that we'll only update the triggers only if it changes.

But why did we have the deletion step in the first place? because when we migrated alerts to notification, we need a way to delete the existing quartz triggers of the old alerts, so we used that.

In this PR, we've changed the deletion process to the AlertToNotification migration itself.

How safe is that?:
- for instances that are on 54 already, it's totally fine because those triggers were already deleted
- for instances that upgrade to 54, the migration will take care of those triggers

### CODE REVIEW

File: src/metabase/pulse/task/send_pulses.clj [hunk 1]
```diff
@@ -153,24 +153,26 @@
 
 (declare update-send-pulse-trigger-if-needed!)
 
+(defn- active-dashsub-pcs
```
Comment (qnkhuat) [inline src/metabase/pulse/task/send_pulses.clj:156]: take it out so we can test this function

File: test/metabase/db/custom_migrations/pulse_to_notification_test.clj [hunk 2]
```diff
@@ -42,7 +52,7 @@
   (let [pulse-id (t2/insert-returning-pk! :pulse (add-timestamp pulse))]
     (t2/insert! :pulse_card (map #(assoc % :pulse_id pulse-id) pulse-cards))
     (doseq [pcr pcs+recipients]
-      (let [pc-id (t2/insert-returning-pk! :pulse_channel (-> pcr (assoc :pulse_id pulse-id) (dissoc :recipients) add-timestamp))]
+      (let [pc-id (t2/insert-returning-pk! :model/PulseChannel (-> pcr (assoc :pulse_id pulse-id) (dissoc :recipients) add-timestamp))]
```
Comment (qnkhuat) [inline test/metabase/db/custom_migrations/pulse_to_notification_test.clj:55]: this pulse channel hooks have sideaffects to create quartz triggers that we want to test

File: test/metabase/db/custom_migrations/pulse_to_notification_test.clj [hunk 3]
```diff
@@ -159,40 +174,9 @@
...
                                                                 :recipients  [{:user_id (mt/user->id :rasta)}]}])
-                  notification (first (migrate-alert! alert-id))]
+                  notification (first (migrate-alert! (task/scheduler) alert-id))]
               (is (=? {:payload_type :notification/card
                        :payload      (merge {:card_id card-id} expected)
                        :active       true
                        :creator_id   (mt/user->id :crowberto)}
                       notification)))))))))
-
-(defn- bit->boolean
```
Comment (qnkhuat) [inline test/metabase/db/custom_migrations/pulse_to_notification_test.clj:169]: dead code

File: src/metabase/db/custom_migrations/pulse_to_notification.clj [hunk 4]
```diff
@@ -81,10 +84,17 @@
              (assoc pc :recipients (get pc-id->recipients (:id pc))))
            pcs))))
 
+(defn- send-pulse-trigger-key
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/db/custom_migrations/pulse_to_notification.clj:87]: yea, it's the same function that we used in https://github.com/metabase/metabase/blob/stop-hard-reset-all-dashboard-subscription-trigger-on-startup/src/metabase/pulse/task/send_pulses.clj#L34

File: src/metabase/pulse/task/send_pulses.clj [hunk 5]
```diff
@@ -228,8 +230,14 @@
...
   ^{:doc
-    "Find all active Dashboard Subscriptino channels, group them by pulse-id and schedule time and create a trigger for each.
-    Do this every startup to make sure all active pulse channels are triggered correctly."
+    "Find all notification subscriptions with cron schedules and create a trigger for each.
+    Run once on startup.
+
+    Context: Prior to 50, the SendPulse job has a single trigger that sends all pulses, but in #42316
+    We've changed it to one trigger per PulseChannel. We need this job so that users migrate from < 50
+    have all the triggers initiated properly.
+    The fact that it runs on every startup is because we have no way to have it run only once.
```
Comment (crisptrutski) [inline src/metabase/pulse/task/send_pulses.clj:239]: Hmm we could probably do something smart like initializing it with a `start-now` trigger, and then not recreating the triggers when we reload it. Something to play around with another time.

File: src/metabase/pulse/task/send_pulses.clj [hunk 6]
```diff
@@ -153,24 +153,26 @@
...
+                          ;; migrated to notifications
+                          [:not= :p.dashboard_id nil]
+                          [:= :d.archived false]]}))
+
 (defn init-dashboard-subscription-triggers!
   "Update send pulse triggers for all active pulses.
   Called once when Metabase starts up to create triggers for all existing PulseChannels"
   []
   (assert (task/scheduler) "Scheduler must be started before initializing SendPulse triggers")
-  (task/delete-all-triggers-of-job! send-pulse-job-key)
```
Comment (crisptrutski) [inline src/metabase/pulse/task/send_pulses.clj:161]: This was the line I missed the first time I review this.

**Review by crisptrutski — APPROVED** [review]
LGTM

File: src/metabase/pulse/task/send_pulses.clj (hunk 6 above)
Comment (qnkhuat) [reply src/metabase/pulse/task/send_pulses.clj:161]: oh that explains it!
