### PR TITLE
🍒 fix selecting pinned items in collections (#30653)

### LINKED ISSUE #30571: "Bulk select" checkbox selects all collection items (pinned items included)
### Describe the bug

"Bulk select" checkbox selects all collection items (pinned items included).

### To Reproduce

1. Create a collection that has one unpinned and one pinned question (and go to that collection)
2. Click on a top-level checkbox (bulk select checkbox) in a table on that collection page
3. Notice that the toast message indicates "2 Items are selected" even though only one (unpinned) question lives in that table

image

### Expected behavior

Bulk select button should only select items that are not pinned.

### Logs

_No response_

### Information about your Metabase installation

```
local dev, `master`, bc360e6, H2, Sample Database
```

### Severity

P2 because people might be unaware that they are affecting pinned collection items.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by EmmadUsmani**
Manual backport of https://github.com/metabase/metabase/pull/30653

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/30774)

### CODE REVIEW

**Comment by EmmadUsmani** [comment]
Closing this as I had mistakenly thought the new bulk move/archive UI was in 46, when in reality it is not.

File: frontend/src/metabase/collections/components/BulkActions.jsx [hunk 1]
```diff
@@ -46,11 +46,26 @@ const SelectionControls = ({
   size = 18,
 }) =>
   !hasUnselected ? (
-    <StackedCheckBox checked onChange={onSelectNone} size={size} />
+    <StackedCheckBox
+      checked
+      onChange={onSelectNone}
+      size={size}
+      aria-label="Select all items"
```
Comment (EmmadUsmani) [inline frontend/src/metabase/collections/components/BulkActions.jsx:53]: This is not in the original PR but here I need to add this `aria-label`, as the current bulk actions UI (visible on master) includes it and the e2e test depends on it.

**Review by iethree — APPROVED** [review]
