### PR TITLE
Clear out existing DashboardCards when running `load` with `--mode update`

### LINKED ISSUE #19762: Serialization overlaps cards on load
**Describe the bug**
When changing the arrangement of the cards in a dashboard in the source, the load process ends up with a really weird arrangement and even in the DB it seems that the cards are overlapped (according to the row and column values in the table)

**Logs**
No relevant logs

**To Reproduce**
1) Set up a source and destination Metabase
2) Build in the source 2 questions and a dashboard
3) Add the 2 questions in the dashboard in a 2x2 array like (image 1)
image,
4) dump and load into destination
5) now swap the cards in the second column to (image 2)
image
6) do a dump and load with --mode update to persist the changes in the destination
7) check the dashboard in the destination, which now has the 4 cards in the same column

Note: if you see what happens in the database, the source has the correct arrangement (check row and column columns):
image
but the destination is all messed up
image

EDIT: so something even more tricky here, if you run the "load" command again after step 6... the cards will be rearrange fine, but if you run once more, it will be overlapped again.
arrangement

**Expected behavior**
Have an exact clone of the dashboard in the source

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: Sample dataset
- Metabase version: 1.41.5
- Metabase hosting environment: Docker
- Metabase internal database: PostgreSQL 14.1

**Severity**
Well... it can make a mess, so users will have to rearrange everything after each load

### LINKED ISSUE #20786: Serialization does not remove cards from dashboard even with --mode update
**Describe the bug**
Serialization will not remove cards that are not present in the yaml files even with --mode update

**Logs**
No errors at all in the serialization process (it says "nothing to update" even if the dashboard changed)

**To Reproduce**
1) set up Metabase source and destination
2) create 2 questions in the source and add them to a dashboard
3) dump in source and load into destination
4) remove one of the questions in the source's dashboard
5) dump and load again, with --mode update, the destination dashboard will still have 2 questions

**Expected behavior**
It's expected that the --mode update will replace everything on destination

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: H2
- Metabase version: 1.42.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Well... this seems to cripple the serialization process a lot

**Additional context**
This can easily lead to https://github.com/metabase/metabase/issues/19762, which ends up with a database with lots of things that shouln't be there

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #19762
Fixes #20786

I don't think anyone around anymore has any idea what's going on in the serialization code. Take a 👀 at the code for loading Dashboards. It's so complicated it's almost unfollowable.

https://github.com/metabase/metabase/blob/master/enterprise/backend/src/metabase_enterprise/serialization/load.clj#L432-L502

This PR does fix #20786. Around the serialization stuff there is little test coverage, there is little institutional knowledge, and there is little code that is clear and understandable. So I consider this fix a stopgap measure until we can go in and clean that code up. 

~~I added some new test tooling to make this stuff easier to test and fixed a few things that didn't work correctly when rebinding the application DB. Now it's reasonably easy to create mock source and destination app DBs and use them to test serialization -- this tooling will come in handy when I work on more serialization bugs in the future.~~ Split out into PR #21332

I think long-term we need to invest serious time reworking this code tho.

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/serialization/load.clj [hunk 1]
```diff
@@ -439,6 +443,15 @@
...
                                                          :creator_id    @default-user))))
+        ;; MEGA HACK -- if `load` is ran with `--mode update` we should delete any Cards that were removed from a
+        ;; Dashboard (according to #20786). However there are literally zero facilities for doing this sort of thing in
+        ;; the current dump/load codebase. So for now we'll just delete ALL DashboardCards for the dumped Dashboard when
+        ;; running with `--mode update` and recreate them from the serialized definitions. This is definitely a wack way
+        ;; of doing things but no one actually understands how this code is supposed to work so this will have to do
+        ;; until we can come in here and clean things up. -- Cam 2022-03-24
+        _               (when (and (= (:mode context) :update)
+                                   (seq dashboard-ids))
+                          (db/delete! DashboardCard :dashboard_id [:in (set dashboard-ids)]))
```
Comment (camsaul) [inline enterprise/backend/src/metabase_enterprise/serialization/load.clj:454]: This is the actual fix; everything else here is related to making things work correctly when the application DB is hot-swapped to enable the new test tooling I wrote for this

**Comment by paoliniluis** [comment]
👋🏻 I'm trying to build this branch but it crashes at the presto driver step

**Comment by camsaul** [comment]
@paoliniluis try again should be fixed

**Comment by paoliniluis** [comment]
Cool! As I got tired of setting up Metabase's from scratch I built https://github.com/metabase/dev-scripts/pull/9 which will help anyone in the setup of Metabase without intervention

**Comment by paoliniluis** [comment]
I see a lot of c3p0 errors when running the application but I'm guessing that you already know that because the PR is still on draft. From the functionality status, it's perfect.

This also fixes https://github.com/metabase/metabase/issues/19762 (as now the mode --update wipes everything). It will keep overlapping cards if you don't use the mode --update tough, but I'm guessing this is a corner case of that mode (which should be addressed on another PR)

**Comment by camsaul** [comment]
The tests for this required a lot of tweaks to our Application DB code to be able to have multiple app DBs in use at the same time for the tests -- and that stuff is built on some refactors I did for 42. So backporting the test is going to be super tricky. The fix itself is not dependent on 42 stuff

**Comment by paoliniluis** [comment]
Just pulled the latest container and I'm getting as soon as I try to do the initial config
```
metabase_destination    | 2022-03-31 21:45:52,329 ERROR middleware.log :: Error logging API request
metabase_destination    | java.lang.ClassCastException: class metabase.db.setup$reify__34767 cannot be cast to class com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource (metabase.db.setup$reify__34767 and com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource are in unnamed module of loader 'app')
```

File: enterprise/backend/src/metabase_enterprise/serialization/load.clj [hunk 2]
```diff
@@ -443,6 +443,15 @@
                                                   (dissoc :dashboard_cards)
                                                   (assoc :collection_id (:collection context)
                                                          :creator_id    (default-user-id)))))
+        ;; MEGA HACK -- if `load` is ran with `--mode update` we should delete any Cards that were removed from a
+        ;; Dashboard (according to #20786). However there are literally zero facilities for doing this sort of thing in
+        ;; the current dump/load codebase. So for now we'll just delete ALL DashboardCards for the dumped Dashboard when
+        ;; running with `--mode update` and recreate them from the serialized definitions. This is definitely a wack way
+        ;; of doing things but no one actually understands how this code is supposed to work so this will have to do
+        ;; until we can come in here and clean things up. -- Cam 2022-03-24
+        _               (when (and (= (:mode context) :update)
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/serialization/load.clj:452]: is there a `-` on this line?

File: enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj [hunk 3]
```diff
@@ -77,4 +87,117 @@
...
+
+(defn- do-with-in-memory-h2-db [db-name-prefix f]
+  (let [db-name           (str db-name-prefix (mt/random-name))
+        connection-string (format "jdbc:h2:mem:%s" db-name)
+        data-source       (mdb.data-source/raw-connection-string->DataSource connection-string)]
+    ;; DB should stay open as long as `conn` is held open.
+    (with-open [_conn (.getConnection data-source)]
+      (letfn [(do-with-app-db [thunk]
+                (binding [mdb.conn/*application-db* (mdb.conn/application-db :h2 data-source)]
+                  (println (u/format-color :yellow "USING %s" (pr-str connection-string))) ; NOCOMMIT
```
Comment (dpsutton) [inline enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj:103]: `; NOCOMMIT`. We need the precommit hooks

File: enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj [hunk 4]
```diff
@@ -77,4 +87,117 @@
...
+                                                    :name          "Card_2"
+                                                    :dataset_query {:database db-id, :type :native, :native {:query "SELECT 1;"}})
+                        {dashboard-id :id} (create! Dashboard, :creator_id user-id, :name "Dashboard")]
+                    (doseq [card-id [card-1-id card-2-id]]
+                      (create! DashboardCard :dashboard_id dashboard-id, :card_id card-id))
+                    (testing "dump in source"
+                      (is (nil? (cmd/dump dump-dir)))))))))
+          (testing "verify the Dashboard was dumped as expected"
+            (is (.exists (io/file dashboard-yaml-filename)))
+            (when-let [yaml (yaml/from-file dashboard-yaml-filename)]
```
Comment (dpsutton) [inline enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj:170]: maybe change the `when-let` to an `if-let` who's else branch is a test failure in case of bad yaml? or is that overkill since the file exists? If the file were empty does `yaml/form-file` throw or return nil?

Comment (dpsutton) [reply enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj:170]: `touch empty.yaml` and then `(yaml/from-file "empty.yaml")` will return nil here.

File: enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj [hunk 5]
```diff
@@ -77,4 +87,117 @@
...
+(defmacro ^:private with-source-and-dest-dbs {:style/indent 0} [& body]
+  `(do-with-source-and-dest-dbs
+    (fn [~'&do-with-source-db ~'&do-with-dest-db]
+      ~@body)))
+
+(defmacro ^:private with-source-db {:style/indent 0} [& body]
+  `(~'&do-with-source-db (fn [] ~@body)))
+
+(defmacro ^:private with-dest-db {:style/indent 0} [& body]
+  `(~'&do-with-dest-db (fn [] ~@body)))
```
Comment (dpsutton) [inline enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj:129]: i've been struggling to find out what this was and its an anaphor introduced by the wrapping macro `with-source-and-dest-dbs`?

**Review by dpsutton — APPROVED** [review]
Some small nits to cleanup. But great idea on how to test this.

**Comment by paoliniluis** [comment]
@camsaul I'm getting a lot of erros like 
```
metabase_destination    | 2022-04-04 12:32:39,870 ERROR middleware.log :: Error logging API request
metabase_destination    | java.lang.ClassCastException: class metabase.db.setup$reify__34767 cannot be cast to class com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource (metabase.db.setup$reify__34767 and com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource are in unnamed module of loader 'app')
metabase_destination    | 	at metabase.server.middleware.log$stats.invokeStatic(log.clj:53)
metabase_destination    | 	at metabase.server.middleware.log$stats.invoke(log.clj:50)
metabase_destination    | 	at metabase.server.middleware.log$format_threads_info.invokeStatic(log.clj:80)
metabase_destination    | 	at metabase.server.middleware.log$format_threads_info.invoke(log.clj:78)
metabase_destination    | 	at metabase.server.middleware.log$format_info.invokeStatic(log.clj:90)
metabase_destination    | 	at metabase.server.middleware.log$format_info.invoke(log.clj:87)
metabase_destination    | 	at metabase.server.middleware.log$log_info.invokeStatic(log.clj:138)
metabase_destination    | 	at metabase.server.middleware.log$log_info.invoke(log.clj:129)
metabase_destination    | 	at metabase.server.middleware.log$logged_response.invokeStatic(log.clj:174)
metabase_destination    | 	at metabase.server.middleware.log$logged_response.invoke(log.clj:167)
metabase_destination    | 	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
metabase_destination    | 	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
metabase_destination    | 	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75200$fn__75201.invoke(exceptions.clj:103)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$wrap_route_matches$fn__27987$fn__27988.invoke(core.clj:151)
metabase_destination    | 	at compojure.response$send.invokeStatic(response.clj:28)
metabase_destination    | 	at compojure.response$send.invoke(response.clj:22)
metabase_destination    | 	at compojure.core$wrap_response$fn__27994.invoke(core.clj:160)
metabase_destination    | 	at compojure.core$wrap_route_middleware$fn__27978.invoke(core.clj:132)
metabase_destination    | 	at compojure.core$wrap_route_info$fn__27983.invoke(core.clj:139)
metabase_destination    | 	at compojure.core$wrap_route_matches$fn__27987.invoke(core.clj:151)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$wrap_route_matches$fn__27987.invoke(core.clj:153)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006.invoke(core.clj:200)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006.invoke(core.clj:200)
metabase_destination    | 	at compojure.core$make_context$handler__28034.invoke(core.clj:289)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:299)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:199)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:199)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006.invoke(core.clj:200)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:199)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006.invoke(core.clj:200)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006.invoke(core.clj:200)
metabase_destination    | 	at metabase.api.routes$fn__78091$fn__78092.invoke(routes.clj:57)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006.invoke(core.clj:200)
metabase_destination    | 	at clojure.lang.AFn.applyToHelper(AFn.java:160)
metabase_destination    | 	at clojure.lang.AFn.applyTo(AFn.java:144)
metabase_destination    | 	at clojure.core$apply.invokeStatic(core.clj:667)
metabase_destination    | 	at clojure.core$apply.invoke(core.clj:662)
metabase_destination    | 	at metabase.server.routes$fn__78242$fn__78243.doInvoke(routes.clj:57)
metabase_destination    | 	at clojure.lang.RestFn.invoke(RestFn.java:436)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006.invoke(core.clj:200)
metabase_destination    | 	at compojure.core$make_context$handler__28034.invoke(core.clj:289)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:299)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$wrap_route_matches$fn__27987.invoke(core.clj:153)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$wrap_route_matches$fn__27987.invoke(core.clj:153)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$wrap_route_matches$fn__27987.invoke(core.clj:153)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:199)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007$respond_SINGLEQUOTE___28008.invoke(core.clj:197)
metabase_destination    | 	at compojure.core$make_context$fn__28038.invoke(core.clj:300)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006.invoke(core.clj:200)
metabase_destination    | 	at compojure.core$routes$fn__28006$f__28007.invoke(core.clj:198)
metabase_destination    | 	at compojure.core$routes$fn__28006.invoke(core.clj:200)
metabase_destination    | 	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75200.invoke(exceptions.clj:98)
metabase_destination    | 	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__75197.invoke(exceptions.clj:86)
metabase_destination    | 	at metabase.server.middleware.log$log_api_call$fn__80313$fn__80314$fn__80315.invoke(log.clj:208)
metabase_destination    | 	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
metabase_destination    | 	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
metabase_destination    | 	at metabase.server.middleware.log$log_api_call$fn__80313$fn__80314.invoke(log.clj:200)
metabase_destination    | 	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
metabase_destination    | 	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
metabase_destination    | 	at metabase.server.middleware.log$log_api_call$fn__80313.invoke(log.clj:199)
metabase_destination    | 	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__85775.invoke(browser_cookie.clj:40)
metabase_destination    | 	at metabase.server.middleware.security$add_security_headers$fn__60621.invoke(security.clj:148)
metabase_destination    | 	at metabase.server.middleware.json$wrap_json_body$fn__83074.invoke(json.clj:63)
metabase_destination    | 	at metabase.server.middleware.json$wrap_streamed_json_response$fn__83092.invoke(json.clj:99)
metabase_destination    | 	at metabase.server.middleware.offset_paging$handle_paging$fn__60645.invoke(offset_paging.clj:42)
metabase_destination    | 	at ring.middleware.keyword_params$wrap_keyword_params$fn__86042.invoke(keyword_params.clj:55)
metabase_destination    | 	at ring.middleware.params$wrap_params$fn__86061.invoke(params.clj:77)
metabase_destination    | 	at metabase.server.middleware.misc$maybe_set_site_url$fn__34978.invoke(misc.clj:59)
metabase_destination    | 	at metabase.server.middleware.session$bind_current_user$fn__46328$fn__46329.invoke(session.clj:272)
metabase_destination    | 	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:252)
metabase_destination    | 	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:242)
metabase_destination    | 	at metabase.server.middleware.session$bind_current_user$fn__46328.invoke(session.clj:271)
metabase_destination    | 	at metabase.server.middleware.session$wrap_current_user_info$fn__46310.invoke(session.clj:223)
metabase_destination    | 	at metabase.server.middleware.session$wrap_session_id$fn__46296.invoke(session.clj:169)
metabase_destination    | 	at metabase.server.middleware.auth$wrap_api_key$fn__66918.invoke(auth.clj:27)
metabase_destination    | 	at ring.middleware.cookies$wrap_cookies$fn__85962.invoke(cookies.clj:216)
metabase_destination    | 	at metabase.server.middleware.misc$add_content_type$fn__34961.invoke(misc.clj:27)
metabase_destination    | 	at metabase.server.middleware.misc$disable_streaming_buffering$fn__34986.invoke(misc.clj:76)
metabase_destination    | 	at ring.middleware.gzip$wrap_gzip$fn__86004.invoke(gzip.clj:86)
metabase_destination    | 	at metabase.server.middleware.misc$bind_request$fn__34989.invoke(misc.clj:93)
metabase_destination    | 	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__85791.invoke(ssl.clj:38)
metabase_destination    | 	at metabase.server$async_proxy_handler$fn__80086.invoke(server.clj:73)
metabase_destination    | 	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
metabase_destination    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
metabase_destination    | 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
metabase_destination    | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
metabase_destination    | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
metabase_destination    | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
metabase_destination    | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
metabase_destination    | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
metabase_destination    | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
metabase_destination    | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
metabase_destination    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
metabase_destination    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
metabase_destination    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
metabase_destination    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
metabase_destination    | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
metabase_destination    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
metabase_destination    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
metabase_destination    | 	at java.base/java.lang.Thread.run(Unknown Source)
```

is this ok?

File: enterprise/backend/src/metabase_enterprise/serialization/load.clj (hunk 2 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/serialization/load.clj:452]: It's an underscore because it's inside of a `let`

File: enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj (hunk 3 above)
Comment (camsaul) [reply enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj]: fixed

File: enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj (hunk 5 above)
Comment (camsaul) [reply enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj:141]: Yeah this isn't super clear. I added a bunch of docstrings and comments explaining what's going on.

**Comment by camsaul** [comment]
@paoliniluis those errors should be fixed now

File: enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj (hunk 5 above)
Comment (dpsutton) [reply enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj:141]: It took me a second but i really like the style of it. This is a really nice solution.

**Review by dragonsahead — APPROVED** [review]
I tried the following:
1) dump from a source and load into destination 👍🏻 
2) dump from a source and load into destination --mode update 👍🏻 
~~3) deleting a card from source and adding a new one there, then load to destination w/ normal mode. Still https://github.com/metabase/metabase/issues/19762~~ Forget about this one, normal mode does not touch the dashboard if exists
4) deleting a card from source and adding a new one there, then load to destination --mode update 👍🏻 
~~5) adding/deleting cards in destination and then loading from source, normal mode Still https://github.com/metabase/metabase/issues/19762~~ Forget about this one, normal mode does not touch the dashboard if exists
5) adding/deleting cards in destination and then loading from source --mode update 👍🏻 

I truly like this mode :). The overlapping still exists in some cases though, so that one is not fixed yet :(

**Comment by paoliniluis** [comment]
BTW: when I do the dump or the load I get the following (I'm pretty sure this doesn't have relationship with this PR) in the App DB (postgres):
```
postgres_origin         | 2022-04-05 21:43:12.974 UTC [73] ERROR:  column "lower(email)" does not exist
postgres_origin         | 2022-04-05 21:43:12.974 UTC [73] STATEMENT:  CREATE INDEX "idx_lower_email" ON "public"."core_user"("lower(email)")
postgres_origin         | 2022-04-05 21:43:12.977 UTC [73] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_origin         | 2022-04-05 21:43:12.977 UTC [73] STATEMENT: 
```
