### PR TITLE
Fix missing React keys in embedding settings page

### LINKED ISSUE #32395: Sections in embedding settings page are missing unique React keys
**To reproduce:**
1. Open `/admin/settings/embedding-in-other-applications`
2. Enable embedding
3. Examine browser console and you'll see missing unique `key` error
```
react-jsx-runtime.development.js:124 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SettingsEditor`. See https://reactjs.org/link/warning-keys for more information.
    in SettingsSetting (created by SettingsEditor)
    in SettingsEditor (created by Title[SettingsEditor])
    in Title[SettingsEditor] (created by Connect(Title[SettingsEditor]))
    in Connect(Title[SettingsEditor]) (created by RouterContext)
    in Unknown (created by Title[])
    in Title[] (created by RouterContext)
    in Unknown (created by CanAccess(settings)(Component))
```

Alternatively, inspect elements and you'll notice that both standalone embeds and full-app embedding sections have the same `undefined-setting` test-id.

### PR DESCRIPTION
**Pull request by nemanjaglumac**
[Resolves: #32395]

How to check:
1. there should be no console error about missing keys
2. sections should have unique test ids
    - `-standalone-embeds-setting`
    - `-full-app-embedding-setting`

### CODE REVIEW

File: frontend/src/metabase/admin/settings/selectors.js [hunk 1]
```diff
@@ -471,13 +471,15 @@ const SECTIONS = {
         getHidden: (_, derivedSettings) => !derivedSettings["enable-embedding"],
       },
       {
+        key: "standalone-embeds",
```
Comment (nemanjaglumac) [inline frontend/src/metabase/admin/settings/selectors.js:474]: Nit: `standalone-embedding` sounds a bit nicer and goes along nicely with `enable-embedding` and `full-app-embedding`, but I guess we have to follow the name of the section 🤷‍♂️

**Review by EmmadUsmani — APPROVED** [review]

File: frontend/src/metabase/admin/settings/selectors.js (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/admin/settings/selectors.js:474]: I'm not sure if it's to use `key` as it's meant to represent the actual name of the setting on the backend. Perhaps the rendering code should be aware of missing keys and use something else instead

**Review by ranquild — COMMENTED** [review]
comments inline

File: frontend/src/metabase/admin/settings/selectors.js (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/admin/settings/selectors.js:474]: Just to make sure I understand - are you saying that if we use the `key` here in selectors, it could potentially mess up the communication to the backend?

I understood the second part, which is to set the missing keys in the place where we actually render this code.

Comment (WiNloSt) [reply frontend/src/metabase/admin/settings/selectors.js:474]: > Just to make sure I understand - are you saying that if we use the key here in selectors, it could potentially mess up the communication to the backend?

I think Alex meant, if he's not sure if `key` in the settings are meant to communicate to readers that it represents BE settings key. e.g.
https://github.com/metabase/metabase/blob/6e14e94f138fb8ec07b3f03e2e5be64917b038a1/frontend/src/metabase/admin/settings/selectors.js#L507-L513

This very same setting is used by the BE.

I think what you should do is to use `-` prefix like other settings that doesn't represent the BE settings. e.g.
https://github.com/metabase/metabase/blob/6e14e94f138fb8ec07b3f03e2e5be64917b038a1/frontend/src/metabase/admin/settings/selectors.js#L514-L519

```suggestion
        key: "-standalone-embeds",
```

This applies to `-full-app-embedding` as well

By the way, I can guarantee it doesn't have anything to do with communicating to our BE in this case, because these 2 settings don't have a way to modify settings in anyway.

**Review by WiNloSt — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/admin/settings/selectors.js (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/admin/settings/selectors.js]: @WiNloSt @ranquild done.

This feels weird, tbh.
I would've never guessed what the `-` prefix meant. Maybe we should make this more explicit in the future.

Comment (WiNloSt) [reply frontend/src/metabase/admin/settings/selectors.js]: > This feels weird, tbh. I would've never guessed what the `-` prefix meant. Maybe we should make this more explicit in the future.

I agree, this is what we already have and I figure it's our de facto convention, but I don't have any idea how to achieve that now.

**Review by WiNloSt — APPROVED** [review]
Awesome, tested and there is no more key errors.

**Review by ranquild — APPROVED** [review]
