### PR TITLE
Use window functions for cumulative sum and cumulative count [BigQuery]

### LINKED ISSUE #39837: [MLv2 × QP] Migrate pre-processing middleware `metabase.query-processor.middleware.upgrade-field-literals`

### LINKED ISSUE #40992: Use window function versions of cumulative aggregations for BigQuery
#13634 and #15118 are not fixed for BigQuery until we update it to implement cumulative aggregations natively like we did for most of the other SQL drivers in #40752.

### LINKED ISSUE #41053: `lib.convert/->legacy-mbql` incorrectly generates `:aggregation-options` clauses in `:expressions` if they contain certain options
This can lead to broken queries, since `:aggregation-options` is not allowed inside `:expressions` in the legacy MBQL schema.

```clj
(let [query (-> (lib/query meta/metadata-provider (meta/table-metadata :orders))
                (lib/breakout (meta/field-metadata :orders :created-at))
                (lib/expression "expr" (lib.options/update-options (lib/+ 1 2) assoc :name "my_expr", :base-type :type/Number)))]
  (lib.convert/->legacy-MBQL query))
;; =>
{:database 26001,          
 :type :query,
 :query
 {:source-table 26060,
  :breakout [[:field 26606 {:base-type :type/DateTimeWithLocalTZ}]],
  :expressions {"expr" [:aggregation-options [:+ 1 2] {:base-type :type/Number}]}}}
```

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #40992
Resolves #39837
Fixes #41053

As mentioned in #40752, all of our other SQL databases support one of the following ways of doing `ORDER BY` inside an `OVER` expression:
```sql
-- order by output column number
sum(sum(my_column) OVER (ORDER BY 1 ROWS UNBOUNDED PRECEDING) AS cumulative_sum
```

or 

```sql
-- copy order by from parent level of query
sum(sum(my_column) OVER (ORDER BY date_trunc(my_timestamp, 'month') ROWS UNBOUNDED PRECEDING) AS cumulative_sum
```

BigQuery however doesn't really fully support either. It doesn't support ordering by output column number at all. It doesn't support ordering by any sort of expression inside `OVER` other than a raw column identifier. So what do we do when we want to order by something like `date_trunc(column, 'month')` rather than just `column`?

Well, we have to introduce another stage that does the temporal bucketing (etc) so we can use plain identifiers in the windo function `ORDER BY`.

In Postgres. we compile this query

```clj
(-> (lib/query meta/metadata-provider (meta/table-metadata :orders))
    (lib/breakout (lib/with-temporal-bucket (meta/field-metadata :orders :created-at) :month))
    (lib/aggregate (lib/cum-sum (meta/field-metadata :orders :total))))
```
to

```sql
-- Postgres version
SELECT
  DATE_TRUNC('month', "public"."orders"."created_at") AS "created_at",
  SUM(SUM("public"."orders"."total")) OVER (
    ORDER BY
      DATE_TRUNC('month', "public"."orders"."created_at") ASC ROWS UNBOUNDED PRECEDING
  ) AS "sum"
FROM
  "public"."orders"
GROUP BY
  DATE_TRUNC('month', "public"."orders"."created_at")
ORDER BY
  DATE_TRUNC('month', "public"."orders"."created_at") ASC
```

In BigQuery we instead need to compile it to

```sql
-- BigQuery version
SELECT
  `source`.`created_at` AS `created_at`,
  SUM(SUM(`source`.`total`)) OVER (
    ORDER BY
      `source`.`created_at` ASC ROWS UNBOUNDED PRECEDING
  ) AS `sum`
FROM
  (
    SELECT
      `v4_test_data__transient_1712251964706.orders`.`total` AS `total`,
      TIMESTAMP_TRUNC(
        `v4_test_data__transient_1712251964706.orders`.`created_at`,
        month
      ) AS `created_at`
    FROM
      `v4_test_data__transient_1712251964706.orders`
  ) AS `source`
GROUP BY
  `created_at`
ORDER BY
  `created_at` ASC
LIMIT
  3
```

This PR introduces a new query transformation function to rewrite queries to look like that latter when needed -- actually fairly easy because of the MLv2 `lib.walk` stuff we added recently, especially the replace one stage with multiple stages stuff @snoe suggested.

I ended up removing the QP "upgrade field literals" middleware that replaced nominal field literal refs (string name instead of integer ID) with integer refs because it's not what we want to do going forward (we want to move toward using nominal field refs (string name) in all stages after the first) and it actually breaks more things than it fixes (it actually doesn't really fix anything except if you use a field literal ref with the wrong case, which shouldn't ever happen IRL). So that was a nice bonus.

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj [hunk 1]
```diff
@@ -27,7 +28,15 @@
 
 (sql.tx/add-test-extensions! :bigquery-cloud-sdk)
 
-(defonce ^:private ns-load-time (System/currentTimeMillis))
+(defonce ^:private ^{:arglists '(^java.lang.Long [])} ^{:doc "Timestamp to use for unique dataset identifiers. Initially
```
Comment (camsaul) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj:31]: When I was spending like 8 hours straight on fixing BigQuery stuff I was getting annoyed that I kept having to jump to this namespace and redef `ns-load-time` to be able to recreate ta dataset. Changed it so this identifier updates automatically every two hours, so you can reload data without having to reevaluate anything.

File: src/metabase/lib/metadata/calculation.cljc [hunk 2]
```diff
@@ -450,6 +450,11 @@
   [_query _stage-number _x _options]
   [])
 
+;;; if you pass in an integer assume it's a stage number; use the method for the query stage itself.
+(defmethod returned-columns-method :dispatch-type/integer
```
Comment (camsaul) [inline src/metabase/lib/metadata/calculation.cljc:454]: This is a convenience so you can more easily use the new walk stuff that applies functions to a specific path e.g.

```clj
(lib.walk/apply-f-for-stage-at-path lib/returned-columns query path)
```

(more on this below)

File: src/metabase/lib/schema/expression.cljc [hunk 3]
```diff
@@ -172,7 +172,15 @@
 (mr/def ::expression
   [:maybe (expression-schema :type/* "any type of expression")])
 
+(mr/def ::expression.definition
+  [:and
+   [:ref ::expression]
+   [:cat
+    #_tag :any
+    #_opts [:map
+            [:lib/expression-name [:string {:decode/normalize common/normalize-string-key}]]]
```
Comment (camsaul) [inline src/metabase/lib/schema/expression.cljc:181]: We were missing normalization behavior for the expression name. Not sure why it would ever be a keyword but I ran into someone doing it somewhere

File: src/metabase/lib/util.cljc [hunk 4]
```diff
@@ -475,6 +475,16 @@
   [query :- :map]
   (= (first-stage-type query) :mbql.stage/native))
 
+(def ^:dynamic ^{:arglists '(^java.lang.String [^java.lang.String s])} *escape-alias-fn*
```
Comment (camsaul) [inline src/metabase/lib/util.cljc:478]: When using MLv2 to determine what column names will appear in a query (in order to generate nominal field literal refs) we need to make sure we're generating unique aliases the same way we do in the old `add-alias-info` namespace, otherwise things will break. Added a dynamic variable that gets bound to `(fn [s] (driver/escape-alias driver/*driver* s))` automatically when this is used inside the QP

File: src/metabase/lib/walk.cljc [hunk 5]
```diff
@@ -139,3 +145,59 @@
    (fn [query path-type path stage-or-join]
      (when (= path-type :lib.walk/stage)
        (f query path stage-or-join)))))
+
+(mr/def ::path.stages-part
```
Comment (camsaul) [inline src/metabase/lib/walk.cljc:149]: Added some new schemas for the `lib.walk` path as we start using these tools more.

File: test/metabase/query_processor_test/cumulative_aggregation_test.clj [hunk 6]
```diff
@@ -246,3 +246,47 @@
                   [#t "2016-06-01" 57 3391.41 59.50]]
                  (mt/formatted-rows [->local-date int 2.0 2.0]
                    (qp/process-query query)))))))))
+
+(deftest ^:parallel expressions-inside-cumulative-aggregations-test
```
Comment (camsaul) [inline test/metabase/query_processor_test/cumulative_aggregation_test.clj:250]: Added a few extra tests. This stuff was already working, but we didn't have tests around these specific things

**Review by bshepherdson — APPROVED** [review]

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 7]
```diff
@@ -457,19 +457,18 @@
...
+                              :percentile-aggregations                             true
                               ;; BigQuery uses timezone operators and arguments on calls like extract() and
                               ;; timezone_trunc() rather than literally using SET TIMEZONE, but we need to flag it as
                               ;; supporting set-timezone anyway so that reporting timezones are returned and used, and
                               ;; tests expect the converted values.
-                              :set-timezone            true
-                              ;; temporarily disabled -- will be fixed by #40982
-                              :window-functions        false}]
+                              :set-timezone                                        true
+                              :sql/window-functions.order-by-output-column-numbers false}]
```
[the remark this answers is not in the document]
Comment (camsaul) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:470]: It seems like ordering by output column numbers works for more databases than it doesn't and the nicer way to do it too so I made it the default. That way third-party driver authors will hopefully have a working implementation out of the box. If that doesn't work then they can try setting `:sql/window-functions.order-by-output-column-numbers` to `false` to get the alternate implementation

File: src/metabase/lib/walk.cljc [hunk 8]
```diff
@@ -139,3 +145,59 @@
...
+   stage-path :- ::stage-path]
+  (let [[_stages stage-number & more] stage-path]
+    (if (empty? more)
+      {:query query, :stage-number stage-number}
+      (let [[_joins join-number & more] more
+            join                        (nth (lib.join/joins query stage-number) join-number)
+            query'                      (assoc query :stages (:stages join))]
+        (recur query' more)))))
+
+(defn apply-f-for-stage-at-path
```
[the remark this answers is not in the document]
Comment (camsaul) [reply src/metabase/lib/walk.cljc:191]: It doesn't return an updated query, and if it did then it wouldn't be useful for `returned-columns` and `visible-columns`, the main reason I needed it. We can definitely add `update-stage-at-path` in the future tho, could be useful for stuff. Or maybe we should just rework MLv2 as a hole so everything takes either a stage number or a path 😱
