### PR TITLE
Fix missing revisions for dashboard

### LINKED ISSUE #30935: Changes to dashboard filters do not show in revision history, filters disconnected without warning
### Describe the bug

- When changing dashboard filters, the changes do not show up in the revision history
- When reverting changes, this can break dashboard filters
  - Potential for inadvertent data leak if reversion happens to a dashboard used for signed embedding with filters to hide rows

### To Reproduce

1. Create a new question from Sample Database > Accounts, save the question
2. Add question to a new dashboard and save the dashboard
3. See revision history
image

4. Add a date filter on Created At
image

5. See revision history
image

6. Reverting to prior version leaves filters intact, but disconnects filters from any questions added between reversion target and current revision.
image

7. Reverting again back to the version prior to the first reversion, adds questions back, but they are not connected to filters anymore
image
image

### Expected behavior

- expect changes in filters to be reflected in revision history, expect reverting to include filter changes and not just clear any filters connected to cards affected by reverting, expect a warning if filters disconnected

### Logs

#N/A

### Information about your Metabase installation

```JSON
- Metabase v1.46.3
```

### Severity

P2: Revision history is misleading since it is incomplete and causes unexpected behavior without warning; customer reported, caused a significant issue for them in leaked data after reverting a dashboard and not realizing filters disconnected

### Additional context

- Adding a warning about disconnecting filters when reverting may reduce this from P2 to P3

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/30935, https://github.com/metabase/metabase/issues/31018, https://github.com/metabase/metabase/issues/31109, #31031, #30524

Make sure we track the following changes for dashboard revision:
- update dashboard params
- making public
- enable embedding
- embedding params updates
- visualization settings changes for dashcards
- param mappings update for dashcards

### CODE REVIEW

**Review by calherries — CHANGES_REQUESTED** [review]
We should also have some tests for these changes, e.g. `card-revision-description-test`

**Comment by calherries** [comment]
@qnkhuat happy to do a final review after you fix the merge conflicts

File: src/metabase/models/dashboard.clj [hunk 1]
```diff
@@ -444,7 +448,7 @@
                                                                           (assoc :collection_id (:id collection))
                                                                           save-card!))))
                             dashcard (-> dashcard
-                                         (dissoc :card :id)
+                                         (dissoc :card :id :creator_id)
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/models/dashboard.clj:461]: if we do not dissoc it here `add-dashcards!` will try to insert `creator_id` to `report_dashboardcard` which is a nonexisting column.

A transient dashboard is a magic dashboard I think.

File: src/metabase/models/dashboard_tab.clj [hunk 2]
```diff
@@ -1,5 +1,6 @@
 (ns metabase.models.dashboard-tab
   (:require
+   [clojure.data :refer [diff]]
```
Comment (calherries) [inline src/metabase/models/dashboard_tab.clj:3]: This should be 
```suggestion
   [clojure.data :as data]
```
Then use `data/diff`

File: src/metabase/models/revision/diff.clj [hunk 3]
```diff
@@ -22,39 +22,77 @@
...
+    (deferred-tru "changed the display from {0} to {1}" (name v1) (name v2))
+
+    [:result_metadata _ _]
+    (deferred-tru "edited the metadata")
+
+    ;;  whenever database_id, query_type, table_id changed,
+    ;; the dataset_query will changed so we don't need a description for this
+    [#{:table_id :database_id :query_type} _ _]
+    nil
+
```
Comment (calherries) [inline src/metabase/models/revision/diff.clj:95]: Not necessarily part of this PR but this `:else nil` still bugs me. A changed column should be required to have a `diff-string`. Are you going to address it in another PR?

File: src/metabase/models/dashboard.clj [hunk 4]
```diff
@@ -179,19 +179,33 @@
 
 ;;; --------------------------------------------------- Revisions ----------------------------------------------------
 
+(def ^:private excluded-columns-for-dashboard-revision
+  [:id :created_at :updated_at :creator_id :points_of_interest :caveats :show_in_getting_started :entity_id
```
Comment (calherries) [inline src/metabase/models/dashboard.clj:183]: `:caveats` and `:points_of_interest` are going to be removed in my PR here (they will be dissoc'd with toucan `after-select` as the model comes out of the db): https://github.com/metabase/metabase/pull/31282. Before merging this PR check that my PR has not been merged. If it has been merged, you should remove these from the line:
```suggestion
  [:id :created_at :updated_at :creator_id :show_in_getting_started :entity_id
```

**Review by calherries — APPROVED** [review]
Awesome, looks good to ship

File: src/metabase/models/revision/diff.clj (hunk 3 above)
Comment (qnkhuat) [reply src/metabase/models/revision/diff.clj:95]: like I said in the description when changing `dataset_query`, it could also changes `table_id, database_id, query_type`(query_type is unlikely but possible).

And I think having `modified query` as the description is better than `modified query and change table_id and change database_id ...`

Comment (qnkhuat) [reply src/metabase/models/revision/diff.clj:95]: another way is to exclude these keys from revision, so we don't have to worry about description. but it makes the code to record revision a bit confusing.

File: src/metabase/models/revision/diff.clj [hunk 5]
```diff
@@ -22,39 +22,77 @@
...
+      (deferred-tru "enabled collection review")
+      (deferred-tru "disabled collection preview"))
+
+    [:dataset_query _ _]
+    (deferred-tru "modified the query")
+
+    [:dataset false true]
+    (deferred-tru "turned this into a model")
+
+    [:dataset false false]
```
Comment (calherries) [inline src/metabase/models/revision/diff.clj:82]:
```suggestion
    [:dataset true false]
```

File: src/metabase/models/revision/diff.clj (hunk 3 above)
Comment (calherries) [reply src/metabase/models/revision/diff.clj:95]: Great, I like this. Still, now we can remove `:else nil` and instead throw an exception? This way the code will reflect the decision to have a description for every changed column, unless explicitly stated.

**Review by calherries — CHANGES_REQUESTED** [review]

File: src/metabase/models/revision/diff.clj (hunk 3 above)
Comment (qnkhuat) [reply src/metabase/models/revision/diff.clj:95]: which solution do you like?

but actually now thinking more about this I don't think we can omit "table_id" from the revision.

Imagine you start with: table_id = 1, 

then you update the query and table_id = 2,

now you want to revert to the original version, if table_id is not recorded then we will have a card with dataset_query and table_id mismatched.

Comment (qnkhuat) [reply src/metabase/models/revision/diff.clj:95]: about `:else nil`, it's necessary because there are changes that are not specified there.
For example in diff-strings for Dashboard, we need to handle keys that only exist on a dashboard 
https://github.com/metabase/metabase/blob/516325a22bae6974401177b68f6028792580ca92/src/metabase/models/dashboard.clj#L256

File: src/metabase/models/card.clj [hunk 6]
```diff
@@ -105,16 +105,18 @@
 
 ;;; --------------------------------------------------- Revisions ----------------------------------------------------
 
+(def ^:private excluded-columns-for-card-revision
+  [:id :created_at :updated_at :entity_id :made_public_by_id :creator_id])
```
Comment (calherries) [inline src/metabase/models/card.clj:109]: Why is `:made_public_by_id` not in the revision, but `:public_uuid` is? The value should be kept in sync with `:public_uuid`, so either both of these columns need to be in the revision, or both of them need to be excluded.

File: src/metabase/models/revision/diff.clj (hunk 3 above)
Comment (calherries) [reply src/metabase/models/revision/diff.clj:95]: > which solution do you like?

I meant I like the addition of this condition:
```
    [#{:table_id :database_id :query_type} _ _]
    nil
```

> For example in diff-strings for Dashboard, we need to handle keys that only exist on a dashboard
Which keys? I'm saying if there are any columns that are not in the `excluded-columns-for-dashboard-revision` set, they should be explicitly handled here. I did a quick check and it looks like `cache_ttl` , `made_public_by_id`, and `auto_apply_filters` aren't being handled yet.

Comment (qnkhuat) [reply src/metabase/models/revision/diff.clj:95]: those columns only exist on dashboard so it'll be generated in https://github.com/metabase/metabase/blob/d45c263f0baebf89ec12867cb80e6b631cea1dd3/src/metabase/models/dashboard.clj#L242

notice that generating description for dashboard will first call to the default implementation, which is the function we're fixing.

File: src/metabase/models/card.clj (hunk 6 above)
Comment (qnkhuat) [reply src/metabase/models/card.clj]: added 374884d4fd

I just noticed we're creating + adding public link using `/:card-id/public_link` and we didn't have any event for it, so it's probably not being recorded, will create an issue for it.

File: test/metabase/models/card_test.clj [hunk 7]
```diff
@@ -631,3 +636,166 @@
...
+
+            (testing (format "we should track when %s changes" col)
+              (is (= 1 (t2/count Revision :model "Card" :model_id (:id card)))))
+
+            (when-not (#{
+                         ;; these columns are expected to not have a description because it's always
+                         ;; comes with a dataset_query changes
+                         :table_id :database_id :query_type
+                         ;; we don't need a description for made_public_by_id because whenever this field changes
+                         ;; public_uuid will changes and we had a description for it.
```
Comment (calherries) [inline test/metabase/models/card_test.clj:774]:
```suggestion
                         ;; public_uuid will change and we have a description for it.
```

**Review by calherries — APPROVED** [review]
Looks good

File: src/metabase/models/card.clj (hunk 6 above)
Comment (qnkhuat) [reply src/metabase/models/card.clj]: created an issue here https://github.com/metabase/metabase/issues/31349
