### PR TITLE
Make formatter integral? dependent on scale

### LINKED ISSUE #49439: Exporting to Formatted CSV or JSON Rounds Numeric Fields When Using "Multiply by a Value"
### Describe the bug

If you're displaying numeric fields in a table viz and use the "Multiply by a number" formatting option, the new values may contain decimals. Exporting to Formatted CSV or JSON rounds the results in these columns. Works as expected in Excel exports.

### To Reproduce

1. Create a question that's just a count() of some field
2. View in a table or pivot
3. Modify the count using the "Multiply by a value" options - make sure to include decimals so the results are decimal
4. Export formatted to Excel - note it works
5. Export formatted to JSON or CSV - note the value is rounded

https://www.loom.com/share/3ee362c5e07d4a11afdd1b447755d1e9

### Expected behavior

Formatted exports should match like the data displayed in the user interface.

### Logs

_No response_

### Information about your Metabase installation

Tested in v50 & v51

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tsplude**
Closes #49439 

Changes include:
  - Adjust setting `integral?` to be dependent on whether `scale` is integral
    - Side effect of this will be fixing unexpected integer rounding when doing a csv or json export on an integer column that has a non integer custom multiplier

Tested CSV and JSON exports of aggregated integer column with a custom decimal scale. XLSX export was unaffected as that code path does not use the column formatters in the same way. 

<details>
<summary>Integer column config</summary>
Screenshot 2024-12-03 at 4 34 42 PM
</details>

<details>
<summary>CSV export before</summary>
image
</details>
<details>
<summary>CSV export after</summary>
image
</details>
<details>
<summary>JSON export before</summary>
image
</details>
<details>
<summary>JSON export after</summary>
image
</details>

### CODE REVIEW

File: test/metabase/channel/render/table_test.clj [hunk 1]
```diff
@@ -132,7 +132,7 @@
           (let [doc     (render.tu/render-card-as-hickory! card-id)
                 row-els (hik.s/select (hik.s/tag :tr) doc)]
             (is (= [["Eh" "Bee" "Sea" "D" "E"]
-                    ["10%" "9E3" "12/10/2022" "---0.12___" "0.667"]]
+                    ["10%" "9.00E3" "12/10/2022" "---0.12___" "0.667"]]
```
[the remark this answers is not in the document]
Comment (adam-james-v) [reply test/metabase/channel/render/table_test.clj:135]: Actually, looking at this test, it may be good to add 2 columns: one that's integer scaled and another that's non-integer scaled.

**Review by adam-james-v — COMMENTED** [review]
The fix is nice and simple, which is great!

The PR description is also really well done, the before/after screenshots are a nice touch :)

Since this is a change that will fix a bug in our exports, I think a test should be added to `downloads-exports-test` that proves the scaling works properly for all of our download/export formats and endpoints.

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 2]
```diff
@@ -459,6 +459,7 @@
          val-it (.iterator ^Iterable values)
          col-it (.iterator ^Iterable cols)
          sty-it (.iterator ^Iterable cell-styles)]
+     (def col-settings col-settings)
```
Comment (adam-james-v) [inline src/metabase/query_processor/streaming/xlsx.clj:462]: I think this is left over from debugging/exploring right?

File: src/metabase/formatter.clj [hunk 3]
```diff
@@ -125,7 +125,7 @@
 
         currency           (when currency?
                              (keyword (or currency "USD")))
-        integral?          (isa? (or effective_type base_type) :type/Integer)
+        integral?          (and (isa? (or effective_type base_type) :type/Integer) (integer? scale))
```
Comment (adam-james-v) [inline src/metabase/formatter.clj:128]: I think it makes sense to do something like this:

```clojure
(and (isa? (or effective_type base_type) :type/Integer) (integer? (or scale 1))) ;; if scale is `nil`, assume it's value is 1 for this check
````

This way, we still let `integral?` be true for the case where a value IS an integer, but the scale value doesn't exist. This was the reason a test expecting the value of `9E3` suddenly saw `9.00E3`. 

Incorporating a change like I've suggested above should bring back that behaviour.

**Review by adam-james-v — APPROVED** [review]
There's just the change to how the scale value is checked in the `integral?` logic. After that, and adjusting the `table-column-formatting-test` to the proper expected value, this looks good to merge, nice work!
