### PR TITLE
Validate common passwords in user account settings

### LINKED ISSUE #23259: Changing account password to a non-complex password misleads the user with a success message even though the process fails
**Describe the bug**
Attempting to change account password to a common one will notify the user that password change has succeeded when in fact it hasn't due to lack of password complexity.

**Logs**
See Screenshots.

**To Reproduce**
1. Go to 'Account Settings'
2. Enter a common password to 'Create a Password' fields
3. Click 'Save'

**Expected behavior**
When password is too common, it should notify the user that the password is too common and the process has failed.

**Screenshots**
metabase-bug

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 101.0
- Your operating system: Ubuntu 20.04
- Metabase version: 0.43.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
Not critical but it causes confusion when new users try to change their temporary password.

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/23259

## How to verify

- Open Account settings -> [Password](http://localhost:3000/account/password)
- Try changing the password to any common password like `qwerty123`
- Ensure it does not allow to save such password and shows an error message

### CODE REVIEW

File: frontend/src/metabase/account/password/components/UserPasswordForm/UserPasswordForm.jsx [hunk 1]
```diff
@@ -13,7 +13,8 @@ const UserPasswordForm = ({ user, validatePassword, updatePassword }) => {
   const handleAsyncValidate = useCallback(
     async ({ password }) => {
       try {
-        validatePassword(password);
+        await validatePassword(password);
```
Comment (gusaiani) [inline frontend/src/metabase/account/password/components/UserPasswordForm/UserPasswordForm.jsx:16]: Hmm, wow

**Review by gusaiani — APPROVED** [review]
👍
