### PR TITLE
fix(sdk): optimistic update query builder and update questions in notebook

### LINKED ISSUE #46523: Query builder notebook component in the embedding sdk is slow due to network request on every interaction
The query builder `Notebook` component has become really slow when adding filters and summarizing. This is reproducible by going to the Shoppy app, going to the interactive question component, and adding new filters and summarization.

This could be potentially caused by the new loader functions used in the `useLoadQuestion` hook. The extracted functions is supposed to mirror what is there in the main app's redux actions. This might be caused by how the dependency comparison or caching didn't work as expected, so it's always submitting a network request rather than skipping some requests.

See video in https://metaboat.slack.com/files/U0511SKLXCN/F07F9BS3L87/cleanshot_2024-08-06_at_14.45.07.mp4

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/46523

### Description

The notebook component in the current version of the SDK do not work at all - they do not integrate with how we update and run questions using the `updateQuestion` and `runQuestion` method from the `useLoadQuestion` hook. This PR adds support for updating and running questions with the notebook component.

It also fixes a couple of issues:

- We were always running the query on every question change, even when the change could be deferred.
- We only update the question after fetching the metadata and the query, so the UI feels super slow.

### How to verify

- Use the interactive question's notebook, filter, filter bar and summarize components.
- It should be as fast as the main Metabase app's query builder in terms of loading states, and number of network requests.

### Checklist

- Tests have been added/updated to cover changes in this PR - will open a separate PR, finding ways to ensure that optimistic updates are happening before the metadata is re-fetched

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Filter.tsx [hunk 1]
```diff
@@ -24,10 +24,10 @@ const FilterInner = ({
 }: {
   question: Question;
 } & FilterProps) => {
-  const { onQuestionChange } = useInteractiveQuestionContext();
+  const { updateQuestion } = useInteractiveQuestionContext();
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Filter.tsx:27]: `updateQuestion` updates the question instead of running the query, so it's renamed to be a bit more explicit

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Filter.tsx [hunk 2]
```diff
@@ -24,10 +24,10 @@ const FilterInner = ({
...
 
   const onQueryChange = (query: Lib.Query) =>
-    onQuestionChange(question.setQuery(query));
+    updateQuestion(question.setQuery(query), { run: true });
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Filter.tsx:30]: If I understand correctly, `onQueryChange` is being called AFTER clicking on "Apply Filters", so it makes sense to attempt auto-run here.

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Notebook.tsx [hunk 3]
```diff
@@ -1,48 +1,48 @@
...
+  const { question, originalQuestion, updateQuestion, runQuestion } =
+    useInteractiveQuestionContext();
+
+  const isDirty = useMemo(() => {
+    return isQuestionDirty(question, originalQuestion);
+  }, [question, originalQuestion]);
+
+  const isRunnable = useMemo(() => {
+    return isQuestionRunnable(question, isDirty);
+  }, [question, isDirty]);
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Notebook.tsx:25]: We use the selector functions from query builder.

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Notebook.tsx [hunk 4]
```diff
@@ -1,48 +1,48 @@
...
-  const dispatch = useDispatch();
-
   return (
     question && (
       <ScrollArea w="100%" h="100%">
         <QBNotebook
           question={question}
           isDirty={isDirty}
           isRunnable={isRunnable}
-          isResultDirty={Boolean(isResultDirty)}
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Notebook.tsx:38]: We do not have the necessary metadata for `isResultDirty` (e.g. `tableMetadata`), so we use `isDirty` for now. This should suffice for now, as `isResultDirty` determines whether to run the question's query or not. In this case, it would always re-run the question query when "Visualize" is clicked, which is an acceptable trade-off.

```ts
  // visualize switches the view to the question's visualization.
  async function visualize() {
    // Only cleanup the question if it's dirty, otherwise Metabase
    // will incorrectly display the Save button, even though there are no changes to save.
    if (isDirty) {
      cleanupQuestion();
    }
    // switch mode before running otherwise URL update may cause it to switch back to notebook mode
    await setQueryBuilderMode("view");
    if (isResultDirty) {
      await runQuestionQuery();
    }
  }

```

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 5]
```diff
@@ -36,8 +49,8 @@ export function useLoadQuestion({
 
   // Keep track of the latest question and query results.
   // They can be updated from the below actions.
-  const [result, setQuestionResult] = useState<SdkQuestionResult>({});
-  const { question, queryResults } = result;
+  const [questionState, setQuestionState] = useReducer(questionReducer, {});
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:52]: This allows us to update the `question` without modifying the `queryResults` and vice-versa.

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/run-question-on-navigate.ts [hunk 6]
```diff
@@ -1,52 +1,57 @@
...
     } else {
       nextCard = getCardAfterVisualizationClick(nextCard, previousCard);
     }
 
-    const previousQuestion = new Question(previousCard, metadata);
-    const nextQuestion = new Question(nextCard, metadata);
+    // Optimistic update the UI before we re-fetch the query metadata.
+    onQuestionChange(new Question(nextCard, getMetadata(getState())));
+
+    await dispatch(loadMetadataForCard(nextCard));
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/lib/interactive-question/run-question-on-navigate.ts:48]: Updating the question before loading the metadata allows the UI to be snappy again.

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts [hunk 7]
```diff
@@ -43,19 +48,30 @@ export const runQuestionOnQueryChangeSdk =
       shouldStartAdHocQuestion,
     });
 
+    if (!nextQuestion.canAutoRun()) {
+      run = false;
+    }
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts:53]: If the question cannot be auto-run, we shouldn't allow it to autorun.

File: frontend/src/metabase/query_builder/selectors.js [hunk 8]
```diff
@@ -594,19 +594,22 @@ export const getIsObjectDetail = createSelector(
   (mode, isZoomingSingleRow) => isZoomingSingleRow || mode?.name() === "object",
 );
 
+export function isQuestionDirty(question, originalQuestion) {
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/selectors.js:597]: We extract the inline selector functions to be their own selector functions, so we can re-use them anywhere else.

**Comment by heypoom** [comment]
@oisincoveney PS - I'm still working on the tests for this, let me know if you have some ideas on testing optimistic updates 🙏🏻

File: frontend/src/metabase/query_builder/selectors.js (hunk 8 above)
Comment (oisincoveney) [inline frontend/src/metabase/query_builder/selectors.js:597]: should we move these functions to a different folder? Maybe we can have some question functions and hooks (like the createQuestion and updateQuestion hooks that I made a few days ago) in a common folder that the main and SDK apps can use

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts [hunk 9]
```diff
@@ -43,19 +48,30 @@ export const runQuestionOnQueryChangeSdk =
...
       question: nextQuestion,
       currentQuestion: previousQuestion,
       rawSeries,
     });
 
-    nextQuestion = questionPivotResult.question;
+    nextQuestion = computedPivotQuestion.question;
+
+    if (computedPivotQuestion.shouldRun !== null) {
+      run = computedPivotQuestion.shouldRun;
```
Comment (oisincoveney) [inline enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts:70]: can we calculate `run` in some sort of a one-liner or function? I think it would be easier to read and maintain if someone else looks into this code in the future

Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts:70]: @oisincoveney we do have `checkShouldRerunPivotTableQuestion(...)` inside of the method, but the issue is that relies on other parameters as seen in `computeQuestionPivotTable`

```ts
export function computeQuestionPivotTable(options: Options) {
  const { currentQuestion, rawSeries } = options;

  let { question } = options;

  const isPivot = question.display() === "pivot";
  const wasPivot = currentQuestion?.display() === "pivot";
  let shouldRun = null;

  const isQuestionNative = Lib.queryDisplayInfo(question.query()).isNative;

  if (wasPivot || isPivot) {
    const hasBreakouts =
      !isQuestionNative && Lib.breakouts(question.query(), -1).length > 0;

    // compute the pivot setting now so we can query the appropriate data
    if (isPivot && hasBreakouts) {
      const key = "pivot_table.column_split";

      if (rawSeries) {
        const series = assocIn(rawSeries, [0, "card"], question.card());
        const setting = getQuestionWithDefaultVisualizationSettings(
          question,
          series,
        ).setting(key);

        question = question.updateSettings({ [key]: setting });
      }
    }

    shouldRun = checkShouldRerunPivotTableQuestion({
      isPivot,
      wasPivot,
      hasBreakouts,
      currentQuestion,
      question,
    });
  }

  return { shouldRun, question };
}
```

File: frontend/src/metabase/query_builder/question.ts [hunk 10]
```diff
@@ -0,0 +1,32 @@
+import * as Lib from "metabase-lib";
+import type Question from "metabase-lib/v1/Question";
+import { isAdHocModelQuestion } from "metabase-lib/v1/metadata/utils/models";
+
+export function isQuestionDirty(
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/question.ts:5]: Types are incorrect - they should include `undefined` for both `question` and `originalQuestion`

**Review by ranquild — COMMENTED** [review]
`check-autorun.ts` - empty file?

File: frontend/src/metabase/query_builder/question.ts (hunk 10 above)
Comment (heypoom) [reply frontend/src/metabase/query_builder/question.ts:5]: updated, and added a `!originalQuestion` check to the predicate in case that is undefined.

File: frontend/src/metabase/query_builder/question.ts [hunk 11]
```diff
@@ -0,0 +1,36 @@
...
+    !originalQuestion ||
+    isAdHocModelQuestion(question, originalQuestion)
+  ) {
+    return false;
+  }
+
+  return question.isDirtyComparedToWithoutParameters(originalQuestion);
+}
+
+export function isQuestionRunnable(question: Question, isDirty: boolean) {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/question.ts:25]: also `undefined`

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts (hunk 9 above)
Comment (oisincoveney) [reply enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts:70]: ok! no worries then. was wondering if there was a way to simplify that

**Review by ranquild — COMMENTED** [review]
@heypoom can you move `query_builder/question.ts` to `utils`? either to `utils.ts` or add a subfolder. Thanks

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/query_builder/question.ts (hunk 11 above)
Comment (heypoom) [reply frontend/src/metabase/query_builder/question.ts]: Good catch, thanks!

**Review by deniskaber — APPROVED** [review]

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Notebook.tsx [hunk 12]
```diff
@@ -1,48 +1,48 @@
...
-  runQuestionQuery,
-  updateQuestion,
-} from "metabase/query_builder/actions";
+import { useSelector } from "metabase/lib/redux";
 import { default as QBNotebook } from "metabase/query_builder/components/notebook/Notebook";
 import {
-  getIsDirty,
-  getIsResultDirty,
-  getIsRunnable,
+  isQuestionDirty,
```
[the remark this answers is not in the document]
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Notebook.tsx:7]: whoops, good catch!

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts [hunk 13]
```diff
@@ -13,28 +13,33 @@ import type { Dispatch, GetState } from "metabase-types/store";
...
   originalQuestion?: Question;
   shouldStartAdHocQuestion?: boolean;
   queryResults?: any[];
   cancelDeferred?: Deferred;
+
+  /** Optimistic update the question in the query builder UI */
+  onQuestionChange: (question: Question) => void;
+
+  /** Whether to run the query by default? */
+  run?: boolean;
```
[the remark this answers is not in the document]
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts:28]: I like the new names - thanks!

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:52]: I think when the `cardId` changes, the reference to the `loadQuestion` method changes, and we have a `useEffect` to call `loadQuestion` so `setQuestionState` should be called there to reset the state. It's very non-intuitive thought, so I'll document this a bit. I agree it would be better to be more explicit and have `cardId` in the dependency array.

```ts
  const {
    question,
    originalQuestion,

    queryResults,

    isQuestionLoading,
    isQueryRunning,

    runQuestion,
    loadQuestion,
    updateQuestion,
    navigateToNewCard,
  } = useLoadQuestion({
    cardId,
    options,
    deserializedCard,
  });


  useEffect(() => {
    loadQuestion();
  }, [loadQuestion]);
```
