### PR TITLE
Fix use of offset with external remapping

### LINKED ISSUE #45348: Window function for offset is generated incorrectly when there is a foreign key remapping in the breakout
### Describe the bug

The intended logic of generating window function for offset() used in aggregations is to order by first breakout and partition by all the others if any.
This breaks when there is a foreign key remapping in the breakout.

### To Reproduce

1. Go to Admin settings
2. Go to Table metadata
3. Choose Sample database, Orders table
4. Click the gear icon for Product_ID
5. Set Display values to use Foreign Key and show Title
6. Start new question
7. Select Orders table from Sample database
8. Add Product ID as a breakout
9. Add `Offset(Sum([Total]), -1)` as an aggregation
10. See the SQL for LAG function generated incorrectly (it should not add a partition by Product_ID):

`SELECT
  "source"."PRODUCTS__via__PRODUCT_ID__TITLE" AS "PRODUCTS__via__PRODUCT_ID__TITLE",
  "source"."PRODUCT_ID" AS "PRODUCT_ID",
  LAG(SUM("source"."TOTAL"), 1) OVER (
    PARTITION BY "source"."PRODUCT_ID"
   
ORDER BY
      "source"."PRODUCTS__via__PRODUCT_ID__TITLE" ASC
  ) AS "Offset"
FROM
  (
    SELECT
      "PRODUCTS__via__PRODUCT_ID"."TITLE" AS "PRODUCTS__via__PRODUCT_ID__TITLE",
      "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID",
      "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL"
    FROM
      "PUBLIC"."ORDERS"
     
LEFT JOIN "PUBLIC"."PRODUCTS" AS "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID"
  ) AS "source"
GROUP BY
  "source"."PRODUCTS__via__PRODUCT_ID__TITLE",
  "source"."PRODUCT_ID"
ORDER BY
  "source"."PRODUCTS__via__PRODUCT_ID__TITLE" ASC`

Captura de ecrã 2024-07-10, às 11 54 04

### Expected behavior

It should generate the lag function with order by PRODUCTS__via__PRODUCT_ID__TITLE and PRODUCT_ID but without partition by clause.
In case there are more breakout columns, they should be added in the partition by clause.

Also, this is minor, but it seems PRODUCT_ID is also missing in the order by for the whole query.

### Logs

_No response_

### Information about your Metabase installation

```JSON
06d1ba2ae111e66253209c01c244d6379acfc6dcb1911fa9ab6012cec9ce52e5
```

### Severity

Produces unintended results

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes #45348

This PR excludes original, remapping source, fields from over clause computation.

### CODE REVIEW

File: src/metabase/query_processor/util/transformations/nest_breakouts.clj [hunk 1]
```diff
@@ -71,6 +71,10 @@
       (-> col
           update-metadata-from-previous-stage-to-produce-correct-ref-in-current-stage
           lib/ref
+          ((fn [ref]
```
Comment (appleby) [inline src/metabase/query_processor/util/transformations/nest_breakouts.clj:74]: untested nitpick feel free to ignore (but matches below `cond->`)

```clojure
(cond->
  (:lib/external-remap col) (lib.options/update-options assoc ::externally-remapped-field true))
```

**Review by appleby — APPROVED** [review]
