### PR TITLE
Fix case-sensitive option leaking to string/=

### LINKED ISSUE #40383: Field filter breaks native question on dashboard
### Describe the bug

Field filters break native question on a dashboard

### To Reproduce

1. Create a native question: sample database, `select * from products where {{ title }}`, set the variable type to Field Filter, wire it to `Products.Title`. 
2. Save it, add to a dashboard.
3. Add a dashboard filter and wire it to `Title`.
4(!) Set a value for the title, and see the error
image

.../query api response: `"error": "Error compiling HoneySQL form: These SQL clauses are unknown or have nil values: :case-sensitive",
`

### Expected behavior

It should work.

### Logs

`.../query` response: [query_response.json](https://github.com/metabase/metabase/files/14669136/query_response.json)

### Information about your Metabase installation
Appears to be broken on stats as of 2024-03-20 / `4eea910`, `1.48.8`, `1.48.9` and `1.49.0`.

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snoe**
Fixes #40383

If a native query parameter is set up with a string widget type that supports a `case-sensitive` option, and that parameter is tied to a dashboard filter that did not support that option, the option was still leaking into the filter as an option where options were not expected.

For instance the native query parameter used `string/contains` and the dashboard used `string/=`, the QP would try to build a filter like `[:= field value {:case-sensitive false}]` which is an illegal filter.

### CODE REVIEW

File: test/metabase/query_processor_test/parameters_test.clj [hunk 1]
```diff
@@ -209,6 +209,44 @@
...
+                                             {:name         "country"
+                                              :display-name "Country"
+                                              :type         :dimension
+                                              :dimension    [:field (mt/id :country :name) nil]
+                                              :options      {:case-sensitive false}
+                                              :widget-type  :string/contains}}}
+                :database   (mt/id)
+                :parameters [{:type   :string/=
+                              :target [:dimension [:template-tag "country"]]
+                              :value  ["US"]}]})))))
```
Comment (lbrdnk) [inline test/metabase/query_processor_test/parameters_test.clj:230]: Nit: This form differs from the one used in the next testing block only by parameter type. Why not binding it in let block and doing `assoc-in [:parameters 0 :type]`?

**Review by lbrdnk — APPROVED** [review]
LGTM.
