### PR TITLE
Fix flaky test:  update-db-to-never-scan-values-on-demand-test 

### LINKED ISSUE #44148: [Flaky Test]: update-db-to-never-scan-values-on-demand-test
Last Flake: https://github.com/metabase/metabase/actions/runs/9487638443
Last Flake Time: 2024-06-12T11:42:00-07:00
Flakes in the last day: 1
Flakes in the last 3d: 1
Flakes in the last 7d: 1

### PR DESCRIPTION
**Pull request by qnkhuat**
The failure

```
  update db setting to never scan should remove scan field values trigger sanity check that it has all triggers to begin with
expected: #{"metabase.task.sync-and-analyze.trigger.157"
            "metabase.task.update-field-values.trigger.157"}
  actual: #{}  
```
this indicates that the scheduler doesn't have any triggers, and I suspect it's because the scheduler was shut down.
And the reason is that we were using `with-redefs` to bind `quartz-scheduler` during test, and there might be parallel tests that's using the scheduler to and it's shutdown the scheduler after it's done.

Closes https://github.com/metabase/metabase/issues/44148

### CODE REVIEW

File: test/metabase/db/custom_migrations_test.clj [hunk 1]
```diff
@@ -1745,35 +1745,36 @@
...
-            ;; wait a bit for the InitSendPulseTriggers to run
-            (u/poll {:thunk #(pulse-channel-test/send-pulse-triggers pulse-id)
-                     :done? #(= 1 %)})
-            (testing "sanity check that we have a send pulse trigger and 2 jobs after restart"
-              (is (= #{(pulse-channel-test/pulse->trigger-info pulse-id pc [(:id pc)])}
-                     (pulse-channel-test/send-pulse-triggers pulse-id)))
-              (is (= #{"metabase.task.send-pulses.send-pulse.job"
-                       "metabase.task.send-pulses.init-send-pulse-triggers.job"}
-                     (scheduler-job-keys))))))))))
+      (with-redefs [task/*quartz-scheduler* task/*quartz-scheduler*]
```
Comment (qnkhuat) [inline test/metabase/db/custom_migrations_test.clj:1748]: this test legitimately need with-redefs because the `metabase.task.send-pulses.send-pulse.job` is need to access the scheduler to add triggers, and since quartz-job runs in a different thread, so we need to bind the scheduler globally.

File: test/metabase/db/custom_migrations_test.clj [hunk 2]
```diff
@@ -1745,35 +1745,38 @@
...
-            (u/poll {:thunk #(pulse-channel-test/send-pulse-triggers pulse-id)
-                     :done? #(= 1 %)})
-            (testing "sanity check that we have a send pulse trigger and 2 jobs after restart"
-              (is (= #{(pulse-channel-test/pulse->trigger-info pulse-id pc [(:id pc)])}
-                     (pulse-channel-test/send-pulse-triggers pulse-id)))
-              (is (= #{"metabase.task.send-pulses.send-pulse.job"
-                       "metabase.task.send-pulses.init-send-pulse-triggers.job"}
-                     (scheduler-job-keys))))))))))
+      ;; need this because the InitSendPulseTriggers job will need access to the scheduler, and since
+      ;; quartz job is running in a different thread other than this test's thread, we need to bind it globally
```
Comment (qnkhuat) [inline test/metabase/db/custom_migrations_test.clj:1749]:
```suggestion
      ;; the `pulse-channell-test/with-send-pulse-setup!` dynamicall bind a in-memory scheduler to `task/*quartz-scheduler*`
      ;; but we need to re-bind that to global here because the InitSendPulseTriggers job will need access to the scheduler, 
      ;; and since quartz job is running in a different thread other than this test's thread, we need to bind it globally
```

**Review by sansolovyov — APPROVED** [review]
