### PR TITLE
Only use snowflake dbname value if db value is not present

### LINKED ISSUE #63652: Snowflake connection complains of not having a current database
### Describe the bug.

All our questions using a snowflake database fails with the same error message : `Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.`.

Note that even if I set a `db=my-db-name` in the Additional JDBC connection string options, it doesn't work.

### To Reproduce

It was tested 2 hours ago on metabase `0.56.6`.

- Create a database of type snowflake
- With or without a `db=xxx` specified in `Additional JDBC connection string options`
- Run an query

### Expected behavior

I would have expected the error to be fixed (at least when `db=xxx` is specified in `Additional JDBC connection string options`.
For info, on `0.56.4`, the bug doesn't exists and every query work.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-09-17",
      "tag": "v0.56.6",
      "hash": "c168e71"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.14 (Debian 15.14-1.pgdg13+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "6.15.11-orbstack-00539-g9885ebd8e3f4",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

blocking an upgrade

### Additional context

I suspect PR #63047 to be the source of the regression

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/63652

### Description

Only use the `:dbname` detail value as the `:db` value in the JDBC spec if the `:db` value is not present. Otherwise the spec tries to use the `:dbname` value, but other parts of the snowflake code use the `:db` value (via `db-name`)

### How to verify

1. Create a snowflake DB that has a valid `:db` value in the details and an invalid `:dbname`
2. Sync this database
3. You should get the expected sync results from the `:db` value

### Demo

https://www.loom.com/share/1595e312a0eb4baa9f52860f7ab77133

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj [hunk 1]
```diff
@@ -1421,3 +1421,25 @@
...
+  (testing "db with a valid db and an invalid dbname in details should be synced with db correctly"
+    (mt/test-driver :snowflake
+      (let [priv-key-val (mt/priv-key->base64-uri (tx/db-test-env-var-or-throw :snowflake :private-key))]
+        (mt/with-temp [:model/Database db {:engine :snowflake
+                                           :details (-> (:details (mt/db))
+                                                        (dissoc :private-key-id)
+                                                        (assoc :private-key-options "uploaded")
+                                                        (assoc :private-key-value priv-key-val)
+                                                        (assoc :use-password false)
+                                                        (assoc :dbname nil))}]
```
Comment (bshepherdson) [inline modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj:1435]: nit; can leave this and just know in the future:  
  
`assoc` accepts arbitrarily many key-value pairs, so you can use a single `assoc` here. You can also `(merge #threaded {:k1 v1 ...})` if that's more readable.

**Review by bshepherdson — APPROVED** [review]

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj (hunk 1 above)
Comment (rileythomp) [reply modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj:1435]: Thanks appreciate this type of feedback. Not always sure of the most idiomatic way to do stuff so I often copy existing examples (which is often my own non-idiomatic stuff 🙃)
