### PR TITLE
`add-alias-info`: recognize `:field` clauses in join source queries to be the same if it has a `:temporal-unit`

### LINKED ISSUE #18512: Joining multiple Saved Questions with the same implicit/explicit grouped field causes wrong reference
**Describe the bug**
Joining multiple Saved Questions with the same implicit/explicit grouped field causes wrong reference.

It does not matter if implicit/explicit joining the table in the Saved Questions, but probably worth having tests for both.

**To Reproduce**
1. Custom question > Sample Dataset > Reviews. (explicit join Products or use implicit). Filter Products.Category=`Doohickey`. Summarize Distinct Products.ID grouped by Products.CreatedAt - save as "Q1"
image
2. Create a similar question, just filter Products.Category=`Gizmo` - save as "Q2"
image
3. Custom question > Saved Questions > "Q1" join "Q2" on CreatedAt=CreatedAt
image
4. Errors because it's not using the correct alias reference from second question, but the actual field reference:
`Column "Q2.CREATED_AT" not found;` (should have been `"Q2"."Products__CREATED_AT"`)

<details><summary>SQL query</summary>

```
SELECT
  "source"."Products__CREATED_AT" AS "Products__CREATED_AT",
  "source"."count" AS "count",
  "Question 944"."CREATED_AT" AS "Question 944__CREATED_AT",
  "Question 944"."count" AS "count_2" 
FROM
  (
    SELECT
      parsedatetime(formatdatetime("Products"."CREATED_AT", 'yyyyMM'), 'yyyyMM') AS "Products__CREATED_AT",
      count(distinct "Products"."ID") AS "count" 
    FROM
      "PUBLIC"."REVIEWS" 
      LEFT JOIN
        "PUBLIC"."PRODUCTS" "Products" 
        ON "PUBLIC"."REVIEWS"."PRODUCT_ID" = "Products"."ID" 
    WHERE
      "Products"."CATEGORY" = 'Doohickey' 
    GROUP BY
      parsedatetime(formatdatetime("Products"."CREATED_AT", 'yyyyMM'), 'yyyyMM') 
    ORDER BY
      parsedatetime(formatdatetime("Products"."CREATED_AT", 'yyyyMM'), 'yyyyMM') ASC
  )
  "source" 
  LEFT JOIN
    (
      SELECT
        parsedatetime(formatdatetime("Products"."CREATED_AT", 'yyyyMM'), 'yyyyMM') AS "Products__CREATED_AT",
        count(distinct "Products"."ID") AS "count" 
      FROM
        "PUBLIC"."REVIEWS" 
        LEFT JOIN
          "PUBLIC"."PRODUCTS" "Products" 
          ON "PUBLIC"."REVIEWS"."PRODUCT_ID" = "Products"."ID" 
      WHERE
        "Products"."CATEGORY" = 'Gizmo' 
      GROUP BY
        parsedatetime(formatdatetime("Products"."CREATED_AT", 'yyyyMM'), 'yyyyMM')
    )
    "Question 944" 
    ON parsedatetime(formatdatetime("source"."Products__CREATED_AT", 'yyyyMM'), 'yyyyMM') = parsedatetime(formatdatetime("Question 944"."Products__CREATED_AT", 'yyyyMM'), 'yyyyMM')

```

</details>

<details><summary>Full stacktrace</summary>

```
2021-10-17 12:56:45,608 INFO api.dataset :: Source query for this query is Card 943
2021-10-17 12:56:45,626 INFO middleware.fetch-source-query :: Fetched source query from Card 943: 
 {:source-table 13,
 :joins
 [{:fields :all,
   :source-table 10,
   :condition [:= [:field 110 nil] [:field 105 {:join-alias "Products"}]],
   :alias "Products"}],
 :filter [:= [:field 107 {:join-alias "Products"}] "Doohickey"],
 :aggregation [[:distinct [:field 105 {:join-alias "Products"}]]],
 :breakout [[:field 108 {:join-alias "Products", :temporal-unit :month}]]}

2021-10-17 12:56:45,640 INFO middleware.fetch-source-query :: Fetched source query from Card 944: 
 {:source-table 13,
 :joins
 [{:fields :all,
   :source-table 10,
   :condition [:= [:field 110 nil] [:field 105 {:join-alias "Products"}]],
   :alias "Products"}],
 :filter [:= [:field 107 {:join-alias "Products"}] "Gizmo"],
 :aggregation [[:distinct [:field 105 {:join-alias "Products"}]]],
 :breakout [[:field 108 {:join-alias "Products", :temporal-unit :month}]]}

2021-10-17 12:56:45,656 INFO middleware.fetch-source-query :: Fetched source query from Card 943: 
 {:source-table 13,
 :joins
 [{:fields :all,
   :source-table 10,
   :condition [:= [:field 110 nil] [:field 105 {:join-alias "Products"}]],
   :alias "Products"}],
 :filter [:= [:field 107 {:join-alias "Products"}] "Doohickey"],
 :aggregation [[:distinct [:field 105 {:join-alias "Products"}]]],
 :breakout [[:field 108 {:join-alias "Products", :temporal-unit :month}]]}

2021-10-17 12:56:45,672 INFO middleware.fetch-source-query :: Fetched source query from Card 944: 
 {:source-table 13,
 :joins
 [{:fields :all,
   :source-table 10,
   :condition [:= [:field 110 nil] [:field 105 {:join-alias "Products"}]],
   :alias "Products"}],
 :filter [:= [:field 107 {:join-alias "Products"}] "Gizmo"],
 :aggregation [[:distinct [:field 105 {:join-alias "Products"}]]],
 :breakout [[:field 108 {:join-alias "Products", :temporal-unit :month}]]}

2021-10-17 12:56:46,411 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2021-10-17T12:56:45.612610+02:00[Europe/Copenhagen]",
 :state "42S22",
 :json_query
 {:database 4,
  :query
  {:source-table "card__943",
   :joins
   [{:fields "all",
     :source-table "card__944",
     :condition
     ["=" ["field" 108 {:temporal-unit "month"}] ["field" 108 {:join-alias "Question 944", :temporal-unit "month"}]],
     :alias "Question 944"}],
   :limit 10},
  :type "query",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT \"source\".\"Products__CREATED_AT\" AS \"Products__CREATED_AT\", \"source\".\"count\" AS \"count\", \"Question 944\".\"CREATED_AT\" AS \"Question 944__CREATED_AT\", \"Question 944\".\"count\" AS \"count_2\" FROM (SELECT parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') AS \"Products__CREATED_AT\", count(distinct \"Products\".\"ID\") AS \"count\" FROM \"PUBLIC\".\"REVIEWS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" = \"Products\".\"ID\" WHERE \"Products\".\"CATEGORY\" = ? GROUP BY parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') ORDER BY parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') ASC) \"source\" LEFT JOIN (SELECT parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') AS \"Products__CREATED_AT\", count(distinct \"Products\".\"ID\") AS \"count\" FROM \"PUBLIC\".\"REVIEWS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" = \"Products\".\"ID\" WHERE \"Products\".\"CATEGORY\" = ? GROUP BY parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM')) \"Question 944\" ON parsedatetime(formatdatetime(\"source\".\"Products__CREATED_AT\", 'yyyyMM'), 'yyyyMM') = parsedatetime(formatdatetime(\"Question 944\".\"Products__CREATED_AT\", 'yyyyMM'), 'yyyyMM') LIMIT 10",
  :params ("Doohickey" "Gizmo")},
 :status :failed,
 :class org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.get(DbException.java:179)"
  "org.h2.message.DbException.get(DbException.java:155)"
  "org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)"
  "org.h2.expression.Alias.optimize(Alias.java:51)"
  "org.h2.command.dml.Select.prepare(Select.java:858)"
  "org.h2.command.Parser.prepareCommand(Parser.java:283)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)"
  "org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1135)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:267)"
  "--> driver.sql_jdbc.execute$fn__79675.invokeStatic(execute.clj:262)"
  "driver.sql_jdbc.execute$fn__79675.invoke(execute.clj:260)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:302)"
  "driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:299)"
  "driver.sql_jdbc.execute$statement_or_prepared_statement.invokeStatic(execute.clj:326)"
  "driver.sql_jdbc.execute$statement_or_prepared_statement.invoke(execute.clj:323)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:466)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:462)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)"
  "driver.sql_jdbc$fn__81350.invokeStatic(sql_jdbc.clj:54)"
  "driver.sql_jdbc$fn__81350.invoke(sql_jdbc.clj:52)"
  "driver.h2$fn__80139.invokeStatic(h2.clj:83)"
  "driver.h2$fn__80139.invoke(h2.clj:80)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
  "query_processor.context.default$default_runf.invoke(default.clj:66)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47664.invoke(mbql_to_native.clj:25)"
  "query_processor.middleware.check_features$check_features$fn__46778.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__47650.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__46230.invoke(cache.clj:211)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47910.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49840.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45349.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41497.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__41372.invoke(annotate.clj:605)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46650.invoke(permissions.clj:81)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48768.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46851.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__49067.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__49380.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44925.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47614.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__47595.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44219.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__46917.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45736.invoke(binning.clj:227)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46453.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__44574.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44803.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49789.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__45088.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48942.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45296.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46500.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48750.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46552.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47301.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__45097.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49742.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48953$fn__48957.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48953.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47541.invoke(fetch_source_query.clj:273)"
  "query_processor.middleware.store$initialize_store$fn__49751$fn__49752.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__49751.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__49796.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47677.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44943.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49727.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46794.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48839.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46734.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___38051.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___38060$fn__38063.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___38060.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:241)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:237)"
  "query_processor$fn__49886$process_query_and_save_execution_BANG___49895$fn__49898.invoke(query_processor.clj:253)"
  "query_processor$fn__49886$process_query_and_save_execution_BANG___49895.invoke(query_processor.clj:245)"
  "query_processor$fn__49930$process_query_and_save_with_max_results_constraints_BANG___49939$fn__49942.invoke(query_processor.clj:265)"
  "query_processor$fn__49930$process_query_and_save_with_max_results_constraints_BANG___49939.invoke(query_processor.clj:258)"
  "api.dataset$run_query_async$fn__56143.invoke(dataset.clj:56)"
  "query_processor.streaming$streaming_response_STAR_$fn__56122$fn__56123.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__56122.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error
 "Column \"Question 944.CREATED_AT\" not found; SQL statement:\n-- Metabase:: userID: 1 queryType: MBQL queryHash: 9bb3819f1642989ee11139c0b032cd437592cc4859a850bbfc1f427db6c47b51\nSELECT \"source\".\"Products__CREATED_AT\" AS \"Products__CREATED_AT\", \"source\".\"count\" AS \"count\", \"Question 944\".\"CREATED_AT\" AS \"Question 944__CREATED_AT\", \"Question 944\".\"count\" AS \"count_2\" FROM (SELECT parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') AS \"Products__CREATED_AT\", count(distinct \"Products\".\"ID\") AS \"count\" FROM \"PUBLIC\".\"REVIEWS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" = \"Products\".\"ID\" WHERE \"Products\".\"CATEGORY\" = ? GROUP BY parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') ORDER BY parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') ASC) \"source\" LEFT JOIN (SELECT parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') AS \"Products__CREATED_AT\", count(distinct \"Products\".\"ID\") AS \"count\" FROM \"PUBLIC\".\"REVIEWS\" LEFT JOIN \"PUBLIC\".\"PRODUCTS\" \"Products\" ON \"PUBLIC\".\"REVIEWS\".\"PRODUCT_ID\" = \"Products\".\"ID\" WHERE \"Products\".\"CATEGORY\" = ? GROUP BY parsedatetime(formatdatetime(\"Products\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM')) \"Question 944\" ON parsedatetime(formatdatetime(\"source\".\"Products__CREATED_AT\", 'yyyyMM'), 'yyyyMM') = parsedatetime(formatdatetime(\"Question 944\".\"Products__CREATED_AT\", 'yyyyMM'), 'yyyyMM') LIMIT 10 [42122-197]",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 4,
  :query
  {:limit 10,
   :source-metadata
   [{:description "The date the product was added to our catalog.",
     :semantic_type :type/CreationTimestamp,
     :coercion_strategy nil,
     :unit :month,
     :name "CREATED_AT",
     :field_ref [:field 108 {:join-alias "Products", :temporal-unit :month}],
     :effective_type :type/DateTime,
     :id 108,
     :display_name "Products → Created At",
     :fingerprint
     {:global {:distinct-count 200, :nil% 0},
      :type {:type/DateTime {:earliest "2016-04-27T01:29:55.147Z", :latest "2019-04-15T19:34:19.931Z"}}},
     :base_type :type/DateTime}
    {:name "count",
     :display_name "Distinct values of Products → ID",
     :base_type :type/BigInteger,
     :semantic_type :type/Quantity,
     :field_ref [:aggregation 0],
     :fingerprint
     {:global {:distinct-count 3, :nil% 0},
      :type
      {:type/Number
       {:min 1, :q1 1, :q3 1.9725159777964119, :max 3, :sd 0.642732769590452, :avg 1.4814814814814814}}}}],
   :fields
   [[:field 108 {:join-alias "Products", :temporal-unit :default}]
    [:field "count" {:base-type :type/BigInteger}]
    [:field 108 {:join-alias "Question 944"}]
    [:field "count" {:base-type :type/BigInteger, :join-alias "Question 944"}]],
   :joins
   [{:strategy :left-join,
     :condition
     [:= [:field 108 {:temporal-unit :month}] [:field 108 {:join-alias "Question 944", :temporal-unit :month}]],
     :alias "Question 944",
     :source-query
     {:source-table 13,
      :filter
      [:=
       [:field 107 {:join-alias "Products"}]
       [:value
        "Gizmo"
        {:base_type :type/Text,
         :effective_type :type/Text,
         :coercion_strategy nil,
         :semantic_type :type/Category,
         :database_type "VARCHAR",
         :name "CATEGORY"}]],
      :aggregation [[:aggregation-options [:distinct [:field 105 {:join-alias "Products"}]] {:name "count"}]],
      :breakout [[:field 108 {:join-alias "Products", :temporal-unit :month}]],
      :joins
      [{:strategy :left-join,
        :source-table 10,
        :condition [:= [:field 110 nil] [:field 105 {:join-alias "Products"}]],
        :alias "Products"}]},
     :source-metadata
     [{:description "The date the product was added to our catalog.",
       :semantic_type :type/CreationTimestamp,
       :coercion_strategy nil,
       :unit :month,
       :name "CREATED_AT",
       :field_ref [:field 108 {:join-alias "Products", :temporal-unit :month}],
       :effective_type :type/DateTime,
       :id 108,
       :display_name "Products → Created At",
       :fingerprint
       {:global {:distinct-count 200, :nil% 0},
        :type {:type/DateTime {:earliest "2016-04-27T01:29:55.147Z", :latest "2019-04-15T19:34:19.931Z"}}},
       :base_type :type/DateTime}
      {:name "count",
       :display_name "Distinct values of Products → ID",
       :base_type :type/BigInteger,
       :semantic_type :type/Quantity,
       :field_ref [:aggregation 0],
       :fingerprint
       {:global {:distinct-count 4, :nil% 0},
        :type
        {:type/Number
         {:min 1, :q1 1, :q3 2.129171306613029, :max 4, :sd 0.9416472308615167, :avg 1.6206896551724137}}}}]}],
   :source-query
   {:source-table 13,
    :filter
    [:=
     [:field 107 {:join-alias "Products"}]
     [:value
      "Doohickey"
      {:base_type :type/Text,
       :effective_type :type/Text,
       :coercion_strategy nil,
       :semantic_type :type/Category,
       :database_type "VARCHAR",
       :name "CATEGORY"}]],
    :aggregation [[:aggregation-options [:distinct [:field 105 {:join-alias "Products"}]] {:name "count"}]],
    :breakout [[:field 108 {:join-alias "Products", :temporal-unit :month}]],
    :order-by [[:asc [:field 108 {:join-alias "Products", :temporal-unit :month}]]],
    :joins
    [{:strategy :left-join,
      :source-table 10,
      :condition [:= [:field 110 nil] [:field 105 {:join-alias "Products"}]],
      :alias "Products"}]}},
  :type :query,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :card-id 943,
   :nested? true,
   :query-hash
   [-101, -77, -127, -97, 22, 66, -104, -98, -31, 17, 57, -64, -80, 50, -51, 67, 117, -110, -52, 72, 89, -88, 80, -69,
    -4, 31, 66, 125, -74, -60, 123, 81]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

2021-10-17 12:56:46,418 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 812.7 ms (18 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (1 idle, 0 queued) (78 total active threads) Queries in flight: 0 (0 queued)
```

</details>

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.41.0

**Additional context**
Was related to #12928, which was fixed in 0.39.4, but I must have overlooked something back then because of the errors generated was different before that version, which confused me and I thought it was the same problem.
Similar to #18502, but opposite, though this issue is not a regression since 0.38.0

### PR DESCRIPTION
**Pull request by camsaul**
Follow on to #19384
Part of the #18580 project
Fixes #18512

The root issue was that the new `add-alias-info` QP code from #19384 did not recognize the `[:field ... {:temporal-unit :month}]`  clause inside the join `Q2`'s `:source-query` as being the same as `[:field ... {:join-alias "Q2"}]` and thus did not pass along the alias used in the join's source query to the parent level, which ultimately resulted in SQL like `SELECT Q2.created_at` instead of the expected `SELECT Q2.Products__created_at`. See my comment here: https://github.com/metabase/metabase/issues/18512#issuecomment-1016898883 

Fixed by adding some minor tweaks to the "are these clauses the same?" logic so it first tries to find an exact match for a clause, then falls back to finding a match ignoring temporal bucketing and binning. (The purpose of trying to find the exact match first is so that if the join's source query buckets or bins the same column more than once with different options, we will try to match the correct version if the clause in the parent query was specific enough. i.e. if you tell us you want `created_at` bucketed by `:month` from `Q2` then we'll give you that in preference to `created_at` bucketed by `:day`; if you just tell us you want plain `created_at` we'll try to give you plain `created_at` but give you `created_at` bucketed by `:month` if it's not there.)

I've also added a new error check in `:add-alias-info` that throws an Exception if you have a `:field` clause, we cannot determine where it came from, **and** the query does not have a `:source-query`. Previously it would fall back to assuming it was from the `:source-query` even if there was no source query. This should help catch a few malformed queries -- at any rate, it's preferable to having to wonder why the compiled SQL has `SELECT source.whatever` in it when there is no table aliased as `source`.

One more change: I backported the `debug-qp` improvements from #19754 and made a few more tweaks. It fixes some of the logic that sorts the MBQL maps in close-to-equivalent-SQL-clause order and prints namespaced keys like `:metabase.query-processor.util.add-alias-info/source-table` as `::add/source-table` (or whatever alias you're using) if you've aliased that namespace in `*ns*`. Which means less work when copy-pasting its output into tests I'm writing which is what I use it for 99.9% of the time. (Also the sorted-MBQL map stuff applies to `debug-qp/add-names`, `process-query-debug`, `query=` as well now, which means it will print the MBQL maps with the name info added in and order that's roughly equivalent to the corresponding  SQL. This makes the diffs in `query=` easier to read too IMO

### CODE REVIEW

File: dev/src/dev/debug_qp.clj [hunk 1]
```diff
@@ -14,6 +14,85 @@
...
+                                       (when (and (keyword? k) (namespace k))
+                                         Integer/MAX_VALUE)
+                                       (dec Integer/MAX_VALUE)))
+                         x-order (order x)
+                         y-order (order y)]
+                     (if (= x-order y-order)
+                       (compare (str x) (str y))
+                       (compare x-order y-order))))))
+
+(def ^:dynamic *shorten-namespaced-keywords?*
```
Comment (dpsutton) [inline dev/src/dev/debug_qp.clj:60]: stuff like this makes me think we should just not use auto-resolved namespace keywords at all. `:add/source-info` would be the same information, not likely to clash with anything, and would not risk errors in the reader.

File: src/metabase/query_processor/util/add_alias_info.clj [hunk 2]
```diff
@@ -186,19 +191,34 @@
...
+                                                                     :or   {normalize-fn normalize-clause}}]
+  (let [normalized (normalize-fn field-clause)
+        exports    (filter (partial mbql.u/is-clause? :field)
+                           (exports source-query))]
+    ;; first look for an EXACT match in the `exports`
+    (or (some (fn [a-clause]
+                (when (= (normalize-fn a-clause) normalized)
+                  a-clause))
+              exports)
+        ;; if there is no EXACT match, attempt a 'fuzzy' match by disregarding the `:temporal-unit` and `:binning`
```
Comment (jeff303) [inline src/metabase/query_processor/util/add_alias_info.clj:204]: Does it make sense to log something at trace level for possible QP debugging purposes?

File: src/metabase/query_processor/util/add_alias_info.clj [hunk 3]
```diff
@@ -186,19 +191,34 @@
...
+        (let [fuzzify          (fn [clause] (mbql.u/update-field-options clause dissoc :temporal-unit :binning))
+              fuzzy-normalized (fuzzify normalized)]
+          (some (fn [a-clause]
+                  (when (= (fuzzify (normalize-fn a-clause)) fuzzy-normalized)
+                    a-clause))
```
Comment (jeff303) [inline src/metabase/query_processor/util/add_alias_info.clj:209]: And here?

File: src/metabase/query_processor/util/add_alias_info.clj [hunk 4]
```diff
@@ -186,19 +191,34 @@
...
+  (let [normalized (normalize-fn field-clause)
+        exports    (filter (partial mbql.u/is-clause? :field)
+                           (exports source-query))]
+    ;; first look for an EXACT match in the `exports`
+    (or (some (fn [a-clause]
+                (when (= (normalize-fn a-clause) normalized)
+                  a-clause))
+              exports)
+        ;; if there is no EXACT match, attempt a 'fuzzy' match by disregarding the `:temporal-unit` and `:binning`
+        (let [fuzzify          (fn [clause] (mbql.u/update-field-options clause dissoc :temporal-unit :binning))
```
Comment (jeff303) [inline src/metabase/query_processor/util/add_alias_info.clj:205]: nit: function body to next line/indented?

**Review by jeff303 — APPROVED** [review]

File: dev/src/dev/debug_qp.clj (hunk 1 above)
Comment (camsaul) [reply dev/src/dev/debug_qp.clj:60]: True, but there are a few benefits to them: 
- they're basically guaranteed to be unique 
- it's super clear where they came from
- to get auto-resolution you have to `require` the namespace that introduces them which is usually desirable from a topological namespace dependency standpoint e.g. it enforces the constraint that `add-alias-info` does not depend on any of the namespaces that use the `::add/` keys 

RE reader errors: This only shortens stuff if there's an alias inside `*ns*`. So that shouldn't cause any reader errors, unless you take that form and try to evaluate it in a different namespace that doesn't have that alias. There's actually no good reason I can think of to turn this switch off, but I put it there just in case something comes up in the future

Comment (camsaul) [reply dev/src/dev/debug_qp.clj:60]: FWIW I think you're right about just giving them some sort of arbitrary prefix so we don't have to mess around with weird things -- in hindsight, `:add/` or something like that would have probably been a better namespace than `::add/` for the reasons you mentioned. Not sure how easy this is going to be to change tho

File: src/metabase/query_processor/util/add_alias_info.clj (hunk 4 above)
Comment (camsaul) [reply src/metabase/query_processor/util/add_alias_info.clj:205]: Why? https://guide.clojure.style/#one-line-functions

File: src/metabase/query_processor/util/add_alias_info.clj (hunk 2 above)
Comment (camsaul) [reply src/metabase/query_processor/util/add_alias_info.clj:204]: I did have tracing in here at one point but it was pretty noisy because there are a lot of Fields that go thru this code so I took it out because it was distracting from other stuff I was trying to look at.

I think maybe we can add it back in somewhere better if we need it in the future?
