### PR TITLE
Fix people dropdown goes outside of the screen

### LINKED ISSUE #17186: People search dropdown goes outside of the screen
**Describe the bug**
People search dropdown goes outside of the screen with body scroll instead of popover scroll.

**To Reproduce**
1. Create a bunch of users in Admin > People
2. Go to Dashboard Subscription, Pulses or Alerts
3. Click the people search
image

**Expected behavior**
Similar to 0.39.x
image

**Information about your Metabase Installation:**
Tested 0.39.5 thru 0.40.1. Regression since 0.40.0

### PR DESCRIPTION
**Pull request by alxnddr**
### Description

Fixes people dropdown does out of the screen. Closes https://github.com/metabase/metabase/issues/17186 — check out repro steps there
Caused by https://github.com/metabase/metabase/pull/16308 so I reverted the way styles are being set to the `frontend/src/metabase/components/TokenField.jsx`

#### Before
Screen Shot 2021-07-27 at 16 34 19

#### After
Screen Shot 2021-07-27 at 16 33 38

### CODE REVIEW

File: frontend/src/metabase/components/FieldValuesWidget.jsx [hunk 1]
```diff
@@ -93,7 +93,6 @@ type Props = {
   formatOptions?: FormattingOptions,
   maxWidth?: number,
   minWidth?: number,
-  optionsMaxHeight?: Number,
```
Comment (alxnddr) [inline frontend/src/metabase/components/FieldValuesWidget.jsx:96]: This is mysterious because the only values passed to `optionsMaxHeight` were `null` and `undefined` based on this line `optionsMaxHeight={isSidebar ? null : undefined}` from `frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker.jsx`

File: frontend/src/metabase/components/TokenField.jsx [hunk 2]
```diff
@@ -590,10 +590,7 @@ export default class TokenField extends Component {
       filteredOptions.length === 0 ? null : (
         <ul
           className={cx(optionsClassName, "overflow-auto pl1 my1 scroll-hide")}
-          style={{
-            ...optionsStyle,
-            maxHeight: this.props.parameter ? 300 : "none",
-          }}
+          style={{ maxHeight: 300, ...optionsStyle }}
```
Comment (alxnddr) [inline frontend/src/metabase/components/TokenField.jsx:593]: Reverted to https://github.com/metabase/metabase/pull/16308/files#diff-52dbad60907bc454d0a20c6b831ee0bb9d5e585d7ac0daab1f7b618f052d82a8L596

File: frontend/src/metabase/components/FieldValuesWidget.jsx [hunk 3]
```diff
@@ -482,11 +481,7 @@ export class FieldValuesWidget extends Component {
           style={style}
           className={className}
           parameter={this.props.parameter}
-          optionsStyle={
-            optionsMaxHeight !== undefined
-              ? { maxHeight: optionsMaxHeight }
-              : {}
-          }
+          optionsStyle={!parameter ? { maxHeight: "none" } : {}}
```
Comment (alxnddr) [inline frontend/src/metabase/components/FieldValuesWidget.jsx:484]: When there is no parameter `maxHeight` should be `none` https://github.com/metabase/metabase/pull/16308/files#diff-52dbad60907bc454d0a20c6b831ee0bb9d5e585d7ac0daab1f7b618f052d82a8R595

**Review by gusaiani — APPROVED** [review]
Having touched this (components inside Popover) a good few times now, for this PR I think we have to trust that e2e tests are not breaking.

Saying this because every change creates side effects at a distance, uncovered, and in places we don't know we should check.

So let's hope none is introduced here and let's keep an eye out for them.
