### PR TITLE
Substitute persisted queries in parameter card references

### LINKED ISSUE #25516: Referencing a model in a SQL query won't use the persisted model
**Describe the bug**
When referencing the model in a SQL query ( {{# ..}} ), then the query won't use the persisted model but rather will go to the actual table

**Logs**
NA

**To Reproduce**
1) Enable model caching (ensure that the model is being cached by checking the DB)
2) create a model (e.g. select * from people), cache it
3) then create a new GUI question and use the model, see that Metabase pulls the data from the cache (even when using the /dataset endpoint)
4) now create a SQL question, and reference the model as it would be a saved question with its id (e.g. select * from {{ # x }}, being x the id of the model), save it and run it. See that the model is pulled from the source tables rather than from the cache

**Expected behavior**
Cached models should always be pulled from the cache

**Screenshots**
Using GUI question
image
image

Using SQL question
image
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop 22.04
- Your databases: Postgres
- Metabase version: 1.44.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P2?

**Additional context**
Reported by a customer

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes #25516 

```sql
select o.total, o.quantity, model_p.category, model_p.title
from orders o
left join {{#14-pg-products}} model_p -- reference to products model
on o.product_id = model_p.id
limit 4
```

Testing:

I'm unhappy with how verbose the test is. At some point we're going to need a better, standardized way to test persistence. But the test makes a persisted table of the test-data.categories
table (test/metabase/test/data/dataset_definitions/test-data.edn). It runs some sql to update the values in the table to turn `"Winery"` -> `"Winery from cached table"`, joins the two tables together to have both at once.

There's a lot of moving pieces and the setup is a bit verbose. There's also no obvious place where these types of tests should go. We'll need to consolidate them in the future (and extend them).

### CODE REVIEW

File: src/metabase/query_processor/util/persisted_cache.clj [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+               [metabase.driver :as driver]
+               [metabase.driver.ddl.interface :as ddl.i]
+               [metabase.driver.sql.util :as sql.u]
+               [metabase.driver.util :as driver.u]
+               [metabase.models.persisted-info :as persisted-info]
+               [metabase.public-settings :as public-settings]))
+
+(defn- segmented-user?
+  []
+  (if-let [segmented? (resolve 'metabase-enterprise.sandbox.api.util/segmented-user?)]
```
Comment (qnkhuat) [inline src/metabase/query_processor/util/persisted_cache.clj:12]: Double-check:
The function `segmented-user?` could throw an exception in case no `current-permissions` are found.

Does this safe when we run it in the context of a background task?

File: src/metabase/query_processor/util/persisted_cache.clj [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+       (:definition persisted-info)
+       (:query_hash persisted-info)
+       (= (:query_hash persisted-info) (persisted-info/query-hash (:dataset_query card)))
+       (= (:definition persisted-info)
+          (persisted-info/metadata->definition (:result_metadata card)
+                                               (:table_name persisted-info)))
+       (not (segmented-user?))))
+
+(defn persisted-info-native-query
+  "Returns a query for "
```
Comment (qnkhuat) [inline src/metabase/query_processor/util/persisted_cache.clj:33]: Incomplete docstring

File: src/metabase/query_processor/util/persisted_cache.clj [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+  [persisted-info]
+  (let [database-id (:database_id persisted-info)
+        driver (or driver/*driver* (driver.u/database->driver database-id))]
+    (format "select %s from %s.%s"
+            (str/join ", " (map #(sql.u/quote-name
+                                  driver
+                                  :field
+                                  (:field-name %))
+                                (get-in persisted-info [:definition :field-definitions])))
+            (sql.u/quote-name
```
Comment (qnkhuat) [inline src/metabase/query_processor/util/persisted_cache.clj:43]: Making `sql.u/qoute-name driver :field` a partial function could make these code look much cleaner.

File: src/metabase/query_processor/util/persisted_cache.clj [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+       (= (:definition persisted-info)
+          (persisted-info/metadata->definition (:result_metadata card)
+                                               (:table_name persisted-info)))
+       (not (segmented-user?))))
+
+(defn persisted-info-native-query
+  "Returns a query for "
+  [persisted-info]
+  (let [database-id (:database_id persisted-info)
+        driver (or driver/*driver* (driver.u/database->driver database-id))]
```
Comment (qnkhuat) [inline src/metabase/query_processor/util/persisted_cache.clj:36]:
```suggestion
  (let [database-id (:database_id persisted-info)
        driver      (or driver/*driver* (driver.u/database->driver database-id))]
```

File: src/metabase/driver/common/parameters/values.clj [hunk 5]
```diff
@@ -139,15 +141,19 @@
   (when-not card-id
     (throw (ex-info (tru "Invalid :card parameter: missing `:card-id`")
                     {:tag tag, :type qp.error-type/invalid-parameter})))
-  (let [query (or (db/select-one-field :dataset_query Card :id card-id)
-                  (throw (ex-info (tru "Card {0} not found." card-id)
-                                  {:card-id card-id, :tag tag, :type qp.error-type/invalid-parameter})))]
+  (let [card           (db/select-one Card :id card-id)
+        persisted-info (db/select-one PersistedInfo :card_id card-id)
```
Comment (qnkhuat) [inline src/metabase/driver/common/parameters/values.clj:145]: nit:
```suggestion
        persisted-info (when (:dataset card) (db/select-one PersistedInfo :card_id card-id))
```
saving some CPU cycle

File: test/metabase/driver/common/parameters/values_test.clj [hunk 6]
```diff
@@ -317,6 +324,61 @@
...
+            (let [mbql-query (mt/mbql-query categories)]
+              (mt/with-temp* [Card [model {:name "model"
+                                           :dataset true
+                                           :dataset_query mbql-query
+                                           :database_id (mt/id)}]]
+                (ddl.i/check-can-persist (mt/db))
+                (persisted-info/ready-database! (mt/id))
+                (#'task.persist-refresh/refresh-tables!
+                 (mt/id)
+                 (var-get #'task.persist-refresh/dispatching-refresher))
```
Comment (qnkhuat) [inline test/metabase/driver/common/parameters/values_test.clj:341]: could all this be a `with-persisted-model` that takes in an mbql-query ? or maybe a card-definition?

**Review by qnkhuat — APPROVED** [review]
This LGTM and I believe it'll fix #25516?

I have some minor comments and a suggestion to write a `with-persisted-model` that might save some LOC when testing models.

File: src/metabase/query_processor/util/persisted_cache.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/query_processor/util/persisted_cache.clj:12]: It's a good call out. I would prefer a function that doesn't throw but i'm nervous to catch the exceptions because in this case they feel truly exceptional.

I don't believe we'll bind a user for background tasks. But I can't think of any scenario where we would hit the persistence in a background task. I'll ask @camsaul for some thoughts.

File: test/metabase/driver/common/parameters/values_test.clj (hunk 6 above)
Comment (dpsutton) [reply test/metabase/driver/common/parameters/values_test.clj]: I ended up making a macro that will do the necessary setup and then let you call a function to persist. This is because you might need lots of temp items (collections, other cards) and in one test we need to assert some counts before and after persistence. This also avoids having to teach clj-kondo how to parse model definitions in another place.

File: src/metabase/query_processor/util/persisted_cache.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/query_processor/util/persisted_cache.clj:12]: Also, this change happened previously and here I just pull it into a shared util namespace. I'm gonna merge with it in this state and chat with cam about it.

Comment (qnkhuat) [reply src/metabase/query_processor/util/persisted_cache.clj:12]: I like your version. having the `persists-fn` is convienet for cases where we want to test things before the persistent happens.

File: test/metabase/driver/common/parameters/values_test.clj (hunk 6 above)
Comment (qnkhuat) [reply test/metabase/driver/common/parameters/values_test.clj]: I like your version. having the `persists-fn` is convienet for cases where we want to test things before the persistent happens.
