### PR TITLE
fix(sdk): fix tooltip crash by migrating away from renderToString

### LINKED ISSUE #58393: [SDK] Tooltip crashes on a very specific setup due to renderToString
Rendering `<InteractiveQuestion />` in the SDK can crash a very specific setup due to the use of `renderToString` from `react-dom/server`, which we used in several tooltip-related components to pass the HTML to echarts.

This cannot be reproduced by us yet, but swapping out this API could work.

### Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'getCurrentStack')
at react-dom-server-legacy.browser.development.js
```

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/58393

### Description

Rendering an `<InteractiveQuestion />` in the SDK can crash a very specific setup due to the use of `renderToString` from `react-dom/server`, which we used in several tooltip-related components to pass the HTML to echarts. The React documentation specifically tell us to migrate away from this API in React 18: https://18.react.dev/reference/react-dom/server/renderToString#removing-rendertostring-from-the-client-code

### How to verify

- Render an `InteractiveQuestion`
- Hover on echarts visualizations (e.g. bar chart) to show the tooltip
- Echarts tooltip should show 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by sanex3339 — APPROVED** [review]
Tested all 3 variants, works great, no errors in console

File: frontend/src/metabase/lib/react-to-html.tsx [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import type { ReactNode } from "react";
+import { flushSync } from "react-dom";
+import { createRoot } from "react-dom/client";
+
+/**
+ * Given a React node, it renders the node into a HTML string synchronously.
+ *
+ * https://18.react.dev/reference/react-dom/server/renderToString#removing-rendertostring-from-the-client-code
+ */
+export function reactNodeToHtmlString(node: ReactNode) {
```
Comment (sanex3339) [inline frontend/src/metabase/lib/react-to-html.tsx:10]: Btw, we also have `frontend/src/metabase/lib/react-compat.ts`

**Review by lorem--ipsum — APPROVED** [review]

File: frontend/src/metabase/lib/react-to-html.tsx (hunk 1 above)
Comment (heypoom) [reply frontend/src/metabase/lib/react-to-html.tsx:10]: @npretto technically yes, but we are already incompatible with React 17 because of Mantine 7 so there's not much point 😞
