### PR TITLE
Scroll dashboard tabs to the end when adding a tab

### LINKED ISSUE #38641: "Add tab" button is covered with a right scroll button on dashboards with many tabs
### Describe the bug

Once the number of tabs in a dashboard exceed the width of the screen, the tab bar scrolls. However, when the scroll bar is present, the > symbol presents hides the new tab button (unless you adjust the window size). 

Sufficient room, see plus symbol on second row to add a new tab:

image

When scroll bar present, the tab insert + symbol to add a new tab is gone - it is hidden behind the > symbol, and it is not possible to scroll further to make it visible:

image

### To Reproduce

1. Go to a dashboard
2. Add multiple tabs, until they can no longer fit on the screen and see a scroll bar appears to move between them
3. The > arrow on the scroll bar will cover the + symbol, preventing more from being added
4. If you change the dimensions of the window, making it wider, more tabs can be added - similarly making it narrow prevent new tabs from being added

### Expected behavior

The tab insert plus symbol should not be hidden by the arrow symbol.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.1+12-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.1+12-LTS",
    "os.name": "Windows 11",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "sqlite"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-06",
      "tag": "v0.48.5",
      "hash": "dab12cf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kulyk**
Fixes #38641 

When adding a new tab to a dashboard with many tabs, the new tab and the "new tab" button can get covered by the "scroll to the right" button. Now we'll be scrolling to the right automatically once a new tab is added; also makes the transition instant.

### Demo

**Before**

https://github.com/metabase/metabase/assets/17258145/39ad0d8b-96db-4d30-b8ec-bfc049bd787c

**After**

https://github.com/metabase/metabase/assets/17258145/22817111-f3b4-4f45-83aa-ed8fb7ef3c5b

### CODE REVIEW

File: frontend/src/metabase/core/components/TabRow/TabRow.tsx [hunk 1]
```diff
@@ -73,6 +58,33 @@
...
+
+  useLayoutEffect(() => {
+    if (!width || !tabListRef.current) {
+      return;
+    }
+
+    setShowScrollRight(
+      Math.round(scrollPosition + width) < tabListRef.current?.scrollWidth,
+    );
+  }, [children, scrollPosition, width]);
```
Comment (EmmadUsmani) [inline frontend/src/metabase/core/components/TabRow/TabRow.tsx:86]: I think we can remove `children` from the deps array

**Review by EmmadUsmani — APPROVED** [review]
