### PR TITLE
Handle LocalDate values in Excel export

### LINKED ISSUE #10803: Download full results of a Query to CSV or XLSX - Excel does not recognize the Timestamp format
Download full results of a Query to CSV or XLSX - Excel does not recognize the Timestamp format

**To Reproduce**
1. Go to any query you may have that has a timestamp field (at least in Oracle database as data source).
2. Click on 'Download full results' in XLSX or CSV.
3. Open with Excel.
4. See column containing timestamp, it is shown in the cell as:
2019-03-18T17:24:31.000+01:00 (type 'General', i.e. not recognized).
It cannot be converted either or get recognized if cell is changed to date, time, ...

**Expected behavior**
When exporting results containing dates, times or datetimes (timestamps fields), the formatting should be recognized by Excel on Open without any need to convert or tweak the data.

**Screenshots**
image

**Information about your Metabase Installation:**
- Your browser and the version: Chrome version 76.0.3809.132 (Official Build) (32-bit)
- Your operating system: Windows 10.0.17134 Build 17134
- Your databases: Oracle, MySQL
- Metabase version: v.0.33
- Metabase hosting environment: Jar-file on CentOS
- Metabase internal database: MySQL

**Severity**
This annoying and prevents that some users can make use of Metabase to complete some of their tasks.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### LINKED ISSUE #13271: Unable to export XLSX with more than 64k cells
**Describe the bug**
After the update from 0.35 to 0.36.6 i'm unable to export XLSX if the report includes type/DateTime (timestamp without time zone) columns. The same report, without date columns, will exports without problem.

**Logs**
```
metabase_1_c425448d3056 |   :params nil},
metabase_1_c425448d3056 |  :status :failed,
metabase_1_c425448d3056 |  :class java.lang.IllegalStateException,
metabase_1_c425448d3056 |  :stacktrace
metabase_1_c425448d3056 |  ["org.apache.poi.xssf.model.StylesTable.createCellStyle(StylesTable.java:815)"
metabase_1_c425448d3056 |   "org.apache.poi.xssf.usermodel.XSSFWorkbook.createCellStyle(XSSFWorkbook.java:730)"
metabase_1_c425448d3056 |   "org.apache.poi.xssf.streaming.SXSSFWorkbook.createCellStyle(SXSSFWorkbook.java:858)"
metabase_1_c425448d3056 |   "dk.ative.docjure.spreadsheet$apply_date_format_BANG_.invokeStatic(spreadsheet.clj:225)"
metabase_1_c425448d3056 |   "dk.ative.docjure.spreadsheet$apply_date_format_BANG_.invoke(spreadsheet.clj:223)"
metabase_1_c425448d3056 |   "dk.ative.docjure.spreadsheet$fn__35183.invokeStatic(spreadsheet.clj:252)"
metabase_1_c425448d3056 |   "dk.ative.docjure.spreadsheet$fn__35183.invoke(spreadsheet.clj:248)"
metabase_1_c425448d3056 |   "clojure.lang.MultiFn.invoke(MultiFn.java:234)"
metabase_1_c425448d3056 |   "dk.ative.docjure.spreadsheet$add_row_BANG_.invokeStatic(spreadsheet.clj:267)"
metabase_1_c425448d3056 |   "dk.ative.docjure.spreadsheet$add_row_BANG_.invoke(spreadsheet.clj:260)"
metabase_1_c425448d3056 |   "--> query_processor.streaming.xlsx$fn$reify__35434.write_row_BANG_(xlsx.clj:76)"
metabase_1_c425448d3056 |   "query_processor.streaming$streaming_rff$fn__35441$fn__35442.invoke(streaming.clj:35)"
metabase_1_c425448d3056 |   "query_processor.middleware.process_userland_query$add_and_save_execution_info_xform_BANG_$execution_info_rf_STAR___46380.invoke(process_userland_query.clj:95)"
metabase_1_c425448d3056 |   "query_processor.middleware.add_rows_truncated$add_rows_truncated_xform$fn__39275.invoke(add_rows_truncated.clj:28)"
metabase_1_c425448d3056 |   "query_processor.middleware.limit$limit_xform$fn__45618.invoke(limit.clj:25)"
metabase_1_c425448d3056 |   "query_processor.middleware.large_int_id$result_int__GT_string$fn__45589.invoke(large_int_id.clj:12)"
metabase_1_c425448d3056 |   "query_processor.reducible$reducible_rows$reify__38090.reduce(reducible.clj:157)"
metabase_1_c425448d3056 |   "query_processor.context.default$default_reducef$fn__37988.invoke(default.clj:59)"
metabase_1_c425448d3056 |   "query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
metabase_1_c425448d3056 |   "query_processor.context.default$default_reducef.invoke(default.clj:49)"
metabase_1_c425448d3056 |   "query_processor.context$reducef.invokeStatic(context.clj:69)"
metabase_1_c425448d3056 |   "query_processor.context$reducef.invoke(context.clj:62)"
metabase_1_c425448d3056 |   "query_processor.context.default$default_runf$respond_STAR___37992.invoke(default.clj:70)"
metabase_1_c425448d3056 |   "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:392)"
metabase_1_c425448d3056 |   "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
metabase_1_c425448d3056 |   "driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)"
metabase_1_c425448d3056 |   "driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)"
metabase_1_c425448d3056 |   "query_processor.context$executef.invokeStatic(context.clj:59)"
metabase_1_c425448d3056 |   "query_processor.context$executef.invoke(context.clj:48)"
metabase_1_c425448d3056 |   "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
metabase_1_c425448d3056 |   "query_processor.context.default$default_runf.invoke(default.clj:67)"
metabase_1_c425448d3056 |   "query_processor.context$runf.invokeStatic(context.clj:45)"
metabase_1_c425448d3056 |   "query_processor.context$runf.invoke(context.clj:39)"
metabase_1_c425448d3056 |   "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
metabase_1_c425448d3056 |   "query_processor.reducible$pivot.invoke(reducible.clj:31)"
metabase_1_c425448d3056 |   "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:26)"
metabase_1_c425448d3056 |   "query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
metabase_1_c425448d3056 |   "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
metabase_1_c425448d3056 |   "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
metabase_1_c425448d3056 |   "query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
metabase_1_c425448d3056 |   "query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
metabase_1_c425448d3056 |   "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
metabase_1_c425448d3056 |   "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
metabase_1_c425448d3056 |   "query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
metabase_1_c425448d3056 |   "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
metabase_1_c425448d3056 |   "query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
metabase_1_c425448d3056 |   "query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
metabase_1_c425448d3056 |   "query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
metabase_1_c425448d3056 |   "query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
metabase_1_c425448d3056 |   "query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
metabase_1_c425448d3056 |   "query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
metabase_1_c425448d3056 |   "query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:318)"
metabase_1_c425448d3056 |   "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
metabase_1_c425448d3056 |   "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
metabase_1_c425448d3056 |   "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
metabase_1_c425448d3056 |   "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
metabase_1_c425448d3056 |   "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
metabase_1_c425448d3056 |   "query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
metabase_1_c425448d3056 |   "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
metabase_1_c425448d3056 |   "query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
metabase_1_c425448d3056 |   "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
metabase_1_c425448d3056 |   "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
metabase_1_c425448d3056 |   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
metabase_1_c425448d3056 |   "driver$do_with_driver.invokeStatic(driver.clj:61)"
metabase_1_c425448d3056 |   "driver$do_with_driver.invoke(driver.clj:57)"
metabase_1_c425448d3056 |   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
metabase_1_c425448d3056 |   "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
metabase_1_c425448d3056 |   "query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
metabase_1_c425448d3056 |   "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
metabase_1_c425448d3056 |   "query_processor.store$do_with_store.invoke(store.clj:40)"
metabase_1_c425448d3056 |   "query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
metabase_1_c425448d3056 |   "query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
metabase_1_c425448d3056 |   "query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
metabase_1_c425448d3056 |   "query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
metabase_1_c425448d3056 |   "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
metabase_1_c425448d3056 |   "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:143)"
metabase_1_c425448d3056 |   "query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
metabase_1_c425448d3056 |   "query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
metabase_1_c425448d3056 |   "query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
metabase_1_c425448d3056 |   "query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
metabase_1_c425448d3056 |   "query_processor.reducible$async_qp$qp_STAR___38074$fn__38077.invoke(reducible.clj:106)"],
metabase_1_c425448d3056 |  :context :xlsx-download,
metabase_1_c425448d3056 |  :error "The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx Workbook",
metabase_1_c425448d3056 |  :row_count 0,
metabase_1_c425448d3056 |  :running_time 0,
metabase_1_c425448d3056 |  :preprocessed

```

**To Reproduce**
1. Go to Browse Data
2. Click on a report that contains ~100000 rows with DateTime columns
3. Export XLSX
4. Receive error

5. Open Editor
6. Click columns
7. Remove all DateTime columns
8. Close editor, refresh report
9. Export XLSX
10. Report OK

**Expected behavior**
The report should be exported also with DateTime columns

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "it-IT",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "5.4.0-47-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-15",
      "tag": "v0.36.6",
      "branch": "release-0.36.x",
      "hash": "cb258fb"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Severity**
This bug was recently introduced. Upgrading to the latest version of the metabase is blocked because XLSX reports are "vital" for BI users to further manipulate data in Excel. On the other hand, the latest versions of Metabase correct too many errors and inaccuracies to make the upgrade urgent!

### LINKED ISSUE #13298: Exporting XLSX with `date` or `time` columns fails with stacktrace
**Describe the bug**
exporting excel file can't open. 

**Logs**
{:database_id 4,
 :started_at #t "2020-09-23T14:34:36.138704+07:00[Asia/Bangkok]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error reducing result rows",
   :stacktrace
   ["--> query_processor.context.default$default_reducef$fn__37988.invoke(default.clj:61)"
    "query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
    "query_processor.context.default$default_reducef.invoke(default.clj:49)"
    "query_processor.context$reducef.invokeStatic(context.clj:69)"
    "query_processor.context$reducef.invoke(context.clj:62)"
    "query_processor.context.default$default_runf$respond_STAR___37992.invoke(default.clj:70)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:392)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
    "driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)"
    "driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
    "query_processor.context.default$default_runf.invoke(default.clj:67)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:26)"
    "query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
    "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
    "query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
    "query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
    "query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
    "query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
    "query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
    "query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
    "query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:318)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
    "query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
    "query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
    "driver$do_with_driver.invokeStatic(driver.clj:61)"
    "driver$do_with_driver.invoke(driver.clj:57)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
    "query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
    "query_processor.store$do_with_store.invoke(store.clj:40)"
    "query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
    "query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:143)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
    "query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
    "query_processor.reducible$async_qp$qp_STAR___38074$fn__38077.invoke(reducible.clj:106)"],
   :error_type :qp,
   :ex-data {:type :qp}}],
 :error_type :qp,
 :json_query {:database 4, :query {:source-table 457}, :type "query", :middleware {:js-int-to-string? true, :skip-results-metadata? true, :format-rows? false}, :async? true},
 :native
 {:query
  "SELECT `paidpromoter`.`memberId` AS `memberId`, `paidpromoter`.`mobile` AS `mobile`, `paidpromoter`.`beginDate` AS `beginDate`, `paidpromoter`.`endDate` AS `endDate` FROM `paidpromoter` LIMIT 1048576",
  :params nil},
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["java_time.temporal$instant.invokeStatic(temporal.clj:350)"
  "java_time.temporal$instant.invoke(temporal.clj:350)"
  "java_time.pre_java8$java_date.invokeStatic(pre_java8.clj:16)"
  "java_time.pre_java8$java_date.invoke(pre_java8.clj:8)"
  "--> query_processor.streaming.xlsx$fn__35422.invokeStatic(xlsx.clj:38)"
  "query_processor.streaming.xlsx$fn__35422.invoke(xlsx.clj:29)"
  "query_processor.streaming.xlsx$fn__35407$G__35402__35412.invoke(xlsx.clj:20)"
  "query_processor.streaming.xlsx$fn$reify__35434.write_row_BANG_(xlsx.clj:76)"
  "query_processor.streaming$streaming_rff$fn__35441$fn__35442.invoke(streaming.clj:35)"
  "query_processor.middleware.process_userland_query$add_and_save_execution_info_xform_BANG_$execution_info_rf_STAR___46380.invoke(process_userland_query.clj:95)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated_xform$fn__39275.invoke(add_rows_truncated.clj:28)"
  "query_processor.middleware.limit$limit_xform$fn__45618.invoke(limit.clj:25)"
  "query_processor.reducible$reducible_rows$reify__38090.reduce(reducible.clj:157)"
  "query_processor.context.default$default_reducef$fn__37988.invoke(default.clj:59)"
  "query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
  "query_processor.context.default$default_reducef.invoke(default.clj:49)"
  "query_processor.context$reducef.invokeStatic(context.clj:69)"
  "query_processor.context$reducef.invoke(context.clj:62)"
  "query_processor.context.default$default_runf$respond_STAR___37992.invoke(default.clj:70)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:392)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
  "driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)"
  "driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)"
  "query_processor.context$executef.invokeStatic(context.clj:59)"
  "query_processor.context$executef.invoke(context.clj:48)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
  "query_processor.context.default$default_runf.invoke(default.clj:67)"
  "query_processor.context$runf.invokeStatic(context.clj:45)"
  "query_processor.context$runf.invoke(context.clj:39)"
  "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
  "query_processor.reducible$pivot.invoke(reducible.clj:31)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:26)"
  "query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)"
  "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)"
  "query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)"
  "query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)"
  "query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)"
  "query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)"
  "query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)"
  "query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:318)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)"
  "query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)"
  "query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)"
  "driver$do_with_driver.invokeStatic(driver.clj:61)"
  "driver$do_with_driver.invoke(driver.clj:57)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)"
  "query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
  "query_processor.store$do_with_store.invoke(store.clj:40)"
  "query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)"
  "query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:143)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__44927.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__46389.invoke(process_userland_query.clj:136)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__44870.invoke(catch_exceptions.clj:174)"
  "query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)"
  "query_processor.reducible$async_qp$qp_STAR___38074$fn__38077.invoke(reducible.clj:106)"],
 :context :xlsx-download,
 :error "Could not convert [#t \"2020-06-01\"] to class java.time.Instant!",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:database 4,
  :query {:source-table 457, :fields [[:field-id 7336] [:field-id 7335] [:datetime-field [:field-id 7337] :default] [:datetime-field [:field-id 7338] :default]], :limit 1048576},
  :type :query,
  :middleware {:js-int-to-string? true, :skip-results-metadata? true, :format-rows? false},
  :async? true,
  :info
  {:executed-by 1,
   :context :xlsx-download,
   :query-hash [40, -36, 44, 50, 119, 105, -55, 12, 122, 51, -57, 6, -20, 100, 91, -99, 78, 26, -107, 7, 9, -38, -87, -58, 32, -72, -19, -13, -28, -11, -8, -99]}},
 :ex-data {:arguments [#t "2020-06-01"], :constructor #object[java_time.temporal$instant 0x1f18ffa0 "java_time.temporal$instant@1f18ffa0"], :to java.time.Instant},
 :data {:rows [], :cols []}}

**To Reproduce**
1. Go to 'Browser Data'
2. Open Table
3. Click "Download full results to .xlsx"
4. Open download file fail.
5. Click "Download full results to .csv" correct

**Expected behavior**
download file correct excel file

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (Firefox 80.0,)
- Your operating system: (OS X 10.15.6)
- Your databases: (MySQL 5.7.31)
- Metabase version: (0.36.6)
- Metabase hosting environment: (Docker on Centos 7)
- Metabase internal database: (MySQL 5.7.31)

**Severity**
blocking my usage of Metabase, i just download full results to .csv instead.

### PR DESCRIPTION
**Pull request by robdaemon**
Adds an additional handler for LocalDate objects and a graceful
degradation of any other errors converting date/time objects to Java
Instants.

Resolves #13271
Resolves #10803
Resolves #13298

### CODE REVIEW

**Review by dpsutton — APPROVED** [review]

**Review by sbelak — APPROVED** [review]
Looks good!

**Review by flamber — CHANGES_REQUESTED** [review]
Current state fixes #13298, but not #13271 and there are some issues with #10803:

1. When export SQL/QB of a saved question, then it still contains the full timezone string for both date and timestamp columns. And sometimes the date-column has a timezone, where the DST doesn't seem to be correct every time (ex People ID=2).
2. When exporting SQL/QB of dirty (unsaved) question, then it correctly converts timestamp-column, but displays it as date only (XLSX NumFmtId=14) instead of date+time. But a date-column is now getting the time of the export added to it's cell, and is also only shown as NumFmtId=14.

Several of these problems also occurs on CSV - like issue #12964

I have just tested with Sample Dataset > People.

**Comment by flamber** [comment]
Tested `599cc79`.

This now fixes #6012, #10803, #12964, #13298 and #13271 (although a tiny bit slower compared to 0.36.4, but that's expected)
Awesomeness :tada: :champagne: 

But it still adds the time of the export to any date columns (either from table or by binning Day on any timestamp-like column).
If we need to hack something, then adding time `00:00:00` would be more correct.
- Simple question > Sample Dataset > People > export as XLSX.
The first row of "Birth Date" will be shown as `12/12/1986`, but the cell value is `12/12/1986 11:45:36` (where the time will depend on when it was exported)

And a minor thing is that the XLSX column width isn't auto-sized, so it now shows datetime columns as `###` until resized.
image
But we have #9251 for that.

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 1]
```diff
@@ -17,38 +19,68 @@
...
+(defn- create-or-get-date-format [^Workbook workbook ^String format-string]
+  (when-not (contains? @*cell-styles* format-string)
+    (let [new-val (let [format-helper (.getCreationHelper workbook)
+                        date-style (.createCellStyle workbook)]
+                    (assoc
+                     @*cell-styles*
+                     format-string
+                     (doto date-style
+                       (.setDataFormat (.. format-helper createDataFormat (getFormat format-string))))))]
+      (reset! *cell-styles* new-val)))
```
Comment (sbelak) [inline src/metabase/query_processor/streaming/xlsx.clj:43]: why `reset!` instead of `swap!` + `assoc`?

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 2]
```diff
@@ -17,38 +19,68 @@
...
+  "m/d/yy")
 
-  java.time.ZonedDateTime
-  (excel-format-value [this]
-    (t/java-date this)))
+(def ^:const datetime-format
+  "Standard date/time format for any of the :type/Date variants with a Time"
+  "m/d/yy HH:MM:ss")
+
+(defmethod spreadsheet/set-cell! LocalDate [^Cell cell val]
```
Comment (sbelak) [inline src/metabase/query_processor/streaming/xlsx.clj:58]: These all look super similar. Can we somehow factor the repeating bits out?

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 3]
```diff
@@ -66,14 +98,16 @@
...
+  (let [workbook    (SXSSFWorkbook.)
+        cell-styles (atom {})
+        sheet       (spreadsheet/add-sheet! workbook (tru "Query result"))]
     (reify i/StreamingResultsWriter
       (begin! [_ {{:keys [cols]} :data}]
         (spreadsheet/add-row! sheet (map (some-fn :display_name :name) cols)))
 
       (write-row! [_ row _]
-        (spreadsheet/add-row! sheet (map excel-format-value row)))
+        (binding [*cell-styles* cell-styles]
```
Comment (sbelak) [inline src/metabase/query_processor/streaming/xlsx.clj:109]: I know you had a huge debate around this, but if performance is a concern you could also have a global atom that is a map of workbook->cell-styles that way it's still thread-isolated but you don't have to go through the binding mechanism for each row. What I do like about the dynamic solution is that it also implicitly cleans up after itself, while with a global atom we'd have to do that manually (perhaps with a macro for clarity).

**Review by sbelak — APPROVED** [review]
Looks like it fixes a shit ton of bugs, great job!

File: src/metabase/query_processor/streaming/xlsx.clj (hunk 2 above)
Comment (robdaemon) [reply src/metabase/query_processor/streaming/xlsx.clj:58]: They're similar except for the date format, they can likely be refactored. I'll give that a shot.

File: src/metabase/query_processor/streaming/xlsx.clj (hunk 1 above)
Comment (robdaemon) [reply src/metabase/query_processor/streaming/xlsx.clj:43]: :shrug: Is one style preferred over the other?

**Comment by robdaemon** [comment]
> But it still adds the time of the export to any date columns (either from table or by binning Day on any timestamp-like column).
> If we need to hack something, then adding time `00:00:00` would be more correct.

@flamber I addressed this - it now sets any `LocalDate` type to `00:00` on the time, so you'll see a `x.0` value in the XML.

File: src/metabase/query_processor/streaming/xlsx.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/query_processor/streaming/xlsx.clj:43]: `swap!` is preferable because it performs a transformation atomically while `reset!` replaces the whole thing atomically. It doesn't really matter here because it's non running on multiple threads but `swap!` will do all the updates without stomping on changes from other threads while `reset!` will just completely replace the contents of the atom with no regards to what any other threads might be doing

Comment (camsaul) [reply src/metabase/query_processor/streaming/xlsx.clj:43]: swap! = apply a transformation
reset! = completely reset the contents of the atom

**Review by flamber — APPROVED** [review]
I have tested this several times over, and I think we're good now. This is a big improvement over the old version (pre-0.36.4) and the current version (0.36.7) :gift_heart:

_I might be slightly blinded by testing this so much for several days - I'm XLSX :vomiting_face:_
