### PR TITLE
certain settings should be decrypted for cache config migration to run

### LINKED ISSUE #44012: Error migrating to the 50.0 with the database connection encrypted
### Describe the bug

I have a Metabase instance that runs in the docker container with the database connection encrypted with MB_ENCRYPTION_SECRET_KEY. 
During the upgrade to 50.0 version, database migration fails. I believe that's caused by the fill_cache_config.pg.sql migration script that tries to set up the default settings for the new cache config but doesn't take into the account the fact that this setting is encrypted.
I believe it might be an issue for the migrations on the other database engines as well.
The workaround is to remove the settings keys affected by the migration scripts before the migration.

### To Reproduce

1. Have the pre-0.50.0 Metabase instance setup with MB_ENCRYPTION_SECRET_KEY setting and the query caching set up.
2. Upgrade to 0.50.0 version.
3. See the error during migration.

### Expected behavior

Migration completes successfully.

### Logs

```
2024-06-11 15:56:56 2024-06-11 12:56:56,331 INFO db.liquibase :: Database has unrun migrations. Checking if migration lock is taken...
2024-06-11 15:56:56 2024-06-11 12:56:56,348 INFO db.liquibase :: No migration lock found.
2024-06-11 15:56:56 2024-06-11 12:56:56,348 INFO db.liquibase :: Migration lock acquired.
2024-06-11 15:56:56 2024-06-11 12:56:56,609 INFO db.liquibase :: Running 32 migrations ...
2024-06-11 15:56:56 2024-06-11 12:56:56,932 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v50.2024-04-12T12:33:09::piranha encountered an exception.
2024-06-11 15:56:56 liquibase.exception.DatabaseException: ERROR: invalid input syntax for type double precision: "BW2J+jGXv2seSOh2ZXEehWTUWTwUJx5lSUr20Sw6mulcSaaFxjEmtgtLwE+wacV5CqyebuY/zg/e5pP7Wg5m3Q==" [Failed SQL: (0) WITH root AS (
2024-06-11 15:56:56   select 'root' AS model,
2024-06-11 15:56:56          0      AS model_id,
2024-06-11 15:56:56          'ttl'  AS strategy,
2024-06-11 15:56:56          json_build_object(
2024-06-11 15:56:56            'multiplier', coalesce((select value::float::int from setting where key = 'query-caching-ttl-ratio'), 10),
2024-06-11 15:56:56            'min_duration_ms', coalesce((select value::float::int from setting where key = 'query-caching-min-ttl'), 60000)
2024-06-11 15:56:56          ) AS config
2024-06-11 15:56:56 ), database AS (
2024-06-11 15:56:56   select 'database' AS model,
2024-06-11 15:56:56          id         AS model_id,
2024-06-11 15:56:56          'duration' AS strategy,
2024-06-11 15:56:56          json_build_object('duration', cache_ttl, 'unit', 'hours') AS config
2024-06-11 15:56:56     from metabase_database
2024-06-11 15:56:56    where cache_ttl is not null
2024-06-11 15:56:56 ), dashboard AS (
2024-06-11 15:56:56   select 'dashboard' AS model,
2024-06-11 15:56:56          id          AS model_id,
2024-06-11 15:56:56          'duration'  AS strategy,
2024-06-11 15:56:56          json_build_object('duration', cache_ttl, 'unit', 'hours') AS config
2024-06-11 15:56:56     from report_dashboard
2024-06-11 15:56:56    where cache_ttl is not null
2024-06-11 15:56:56 ), card AS (
2024-06-11 15:56:56   select 'question' AS model,
2024-06-11 15:56:56          id         AS model_id,
2024-06-11 15:56:56          'duration' AS strategy,
2024-06-11 15:56:56          json_build_object('duration', cache_ttl, 'unit', 'hours') AS config
2024-06-11 15:56:56     from report_card
2024-06-11 15:56:56    where cache_ttl is not null
2024-06-11 15:56:56 ), rows1 AS (
2024-06-11 15:56:56   SELECT * FROM root UNION ALL
2024-06-11 15:56:56   SELECT * FROM database UNION ALL
2024-06-11 15:56:56   SELECT * FROM dashboard UNION ALL
2024-06-11 15:56:56   SELECT * FROM card
2024-06-11 15:56:56 ), rows AS (
2024-06-11 15:56:56   SELECT * FROM rows1
2024-06-11 15:56:56    WHERE (SELECT true FROM setting WHERE key = 'enable-query-caching' AND VALUE = 'true')
2024-06-11 15:56:56 )
2024-06-11 15:56:56     INSERT INTO cache_config (model, model_id, strategy, config)
2024-06-11 15:56:56     SELECT * FROM rows
2024-06-11 15:56:56     ON CONFLICT (model, model_id) DO NOTHING]
2024-06-11 15:56:56     at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(jdbcexecutor.java:470)
2024-06-11 15:56:56     at liquibase.executor.jvm.JdbcExecutor.execute(jdbcexecutor.java:77)
2024-06-11 15:56:56     at liquibase.executor.jvm.JdbcExecutor.execute(jdbcexecutor.java:179)
2024-06-11 15:56:56     at liquibase.executor.AbstractExecutor.execute(abstractexecutor.java:141)
2024-06-11 15:56:56     at liquibase.database.AbstractJdbcDatabase.executeStatements(abstractjdbcdatabase.java:1285)
2024-06-11 15:56:56     at liquibase.changelog.ChangeSet.execute(changeset.java:755)
2024-06-11 15:56:56     at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(updatevisitor.java:119)
2024-06-11 15:56:56     at liquibase.changelog.visitor.UpdateVisitor.visit(updatevisitor.java:68)
2024-06-11 15:56:56     at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(changelogiterator.java:133)
2024-06-11 15:56:56     at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(changelogiterator.java:133)
2024-06-11 15:56:56     at liquibase.Scope.lambda$child$0(scope.java:186)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:195)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:185)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:164)
2024-06-11 15:56:56     at liquibase.changelog.ChangeLogIterator$[2.run](https://2.run/)(changelogiterator.java:122)
2024-06-11 15:56:56     at liquibase.Scope.lambda$child$0(scope.java:186)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:195)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:185)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:164)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:252)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:256)
2024-06-11 15:56:56     at [liquibase.changelog.ChangeLogIterator.run](https://liquibase.changelog.changelogiterator.run/)(changelogiterator.java:89)
2024-06-11 15:56:56     at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(abstractupdatecommandstep.java:110)
2024-06-11 15:56:56     at liquibase.Scope.lambda$child$0(scope.java:186)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:195)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:185)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:164)
2024-06-11 15:56:56     at [liquibase.command.core.AbstractUpdateCommandStep.run](https://liquibase.command.core.abstractupdatecommandstep.run/)(abstractupdatecommandstep.java:108)
2024-06-11 15:56:56     at [liquibase.command.core.UpdateCommandStep.run](https://liquibase.command.core.updatecommandstep.run/)(updatecommandstep.java:105)
2024-06-11 15:56:56     at liquibase.command.CommandScope.execute(commandscope.java:217)
2024-06-11 15:56:56     at liquibase.Liquibase.lambda$update$0(liquibase.java:245)
2024-06-11 15:56:56     at liquibase.Scope.lambda$child$0(scope.java:186)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:195)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:185)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:164)
2024-06-11 15:56:56     at liquibase.Liquibase.runInScope(liquibase.java:1419)
2024-06-11 15:56:56     at liquibase.Liquibase.update(liquibase.java:234)
2024-06-11 15:56:56     at liquibase.Liquibase.update(liquibase.java:212)
2024-06-11 15:56:56     at liquibase.Liquibase.update(liquibase.java:194)
2024-06-11 15:56:56     at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44378.invoke(liquibase.clj:359)
2024-06-11 15:56:56     at metabase.db.liquibase$run_in_scope_locked$reify__44374.run(liquibase.clj:324)
2024-06-11 15:56:56     at liquibase.Scope.lambda$child$0(scope.java:186)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:195)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:185)
2024-06-11 15:56:56     at liquibase.Scope.child(scope.java:164)
2024-06-11 15:56:56     at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:317)
2024-06-11 15:56:56     at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:300)
2024-06-11 15:56:56     at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:348)
2024-06-11 15:56:56     at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:341)
2024-06-11 15:56:56     at metabase.db.setup$migrate_BANG_$fn__53305.invoke(setup.clj:84)
2024-06-11 15:56:56     at metabase.db.liquibase$do_with_liquibase$f_STAR___44315.invoke(liquibase.clj:139)
2024-06-11 15:56:56     at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:142)
2024-06-11 15:56:56     at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:130)
2024-06-11 15:56:56     at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
2024-06-11 15:56:56     at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
2024-06-11 15:56:56     at clojure.lang.RestFn.invoke(restfn.java:425)
2024-06-11 15:56:56     at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
2024-06-11 15:56:56     at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
2024-06-11 15:56:56     at metabase.db.setup$setup_db_BANG_$fn53333$fn53334.invoke(setup.clj:167)
2024-06-11 15:56:56     at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
2024-06-11 15:56:56     at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
2024-06-11 15:56:56     at metabase.db.setup$setup_db_BANG_$fn__53333.invoke(setup.clj:161)
2024-06-11 15:56:56     at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
2024-06-11 15:56:56     at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
2024-06-11 15:56:56     at metabase.db$setup_db_BANG_$fn__53358.invoke(db.clj:82)
2024-06-11 15:56:56     at metabase.db$setup_db_BANG_.invokeStatic(db.clj:77)
2024-06-11 15:56:56     at metabase.db$setup_db_BANG_.doInvoke(db.clj:64)
2024-06-11 15:56:56     at clojure.lang.RestFn.invoke(restfn.java:421)
2024-06-11 15:56:56     at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
2024-06-11 15:56:56     at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
2024-06-11 15:56:56     at metabase.core$init_BANG_.invokeStatic(core.clj:170)
2024-06-11 15:56:56     at metabase.core$init_BANG_.invoke(core.clj:165)
2024-06-11 15:56:56     at metabase.core$start_normally.invokeStatic(core.clj:182)
2024-06-11 15:56:56     at metabase.core$start_normally.invoke(core.clj:176)
2024-06-11 15:56:56     at metabase.core$entrypoint.invokeStatic(core.clj:215)
2024-06-11 15:56:56     at metabase.core$entrypoint.doInvoke(core.clj:209)
2024-06-11 15:56:56     at clojure.lang.RestFn.invoke(restfn.java:397)
2024-06-11 15:56:56     at clojure.lang.AFn.applyToHelper(afn.java:152)
2024-06-11 15:56:56     at clojure.lang.RestFn.applyTo(restfn.java:132)
2024-06-11 15:56:56     at clojure.lang.Var.applyTo(var.java:705)
2024-06-11 15:56:56     at clojure.core$apply.invokeStatic(core.clj:667)
2024-06-11 15:56:56     at clojure.core$apply.invoke(core.clj:662)
2024-06-11 15:56:56     at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
2024-06-11 15:56:56     at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
2024-06-11 15:56:56     at clojure.lang.RestFn.invoke(restfn.java:397)
2024-06-11 15:56:56     at clojure.lang.AFn.applyToHelper(afn.java:152)
2024-06-11 15:56:56     at clojure.lang.RestFn.applyTo(restfn.java:132)
2024-06-11 15:56:56     at metabase.bootstrap.main(Unknown Source)
2024-06-11 15:56:56 Caused by: org.postgresql.util.PSQLException: ERROR: invalid input syntax for type double precision: "BW2J+jGXv2seSOh2ZXEehWTUWTwUJx5lSUr20Sw6mulcSaaFxjEmtgtLwE+wacV5CqyebuY/zg/e5pP7Wg5m3Q=="
2024-06-11 15:56:56     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(queryexecutorimpl.java:2725)
2024-06-11 15:56:56     at org.postgresql.core.v3.QueryExecutorImpl.processResults(queryexecutorimpl.java:2412)
2024-06-11 15:56:56     at org.postgresql.core.v3.QueryExecutorImpl.execute(queryexecutorimpl.java:371)
2024-06-11 15:56:56     at org.postgresql.jdbc.PgStatement.executeInternal(pgstatement.java:502)
2024-06-11 15:56:56     at org.postgresql.jdbc.PgStatement.execute(pgstatement.java:419)
2024-06-11 15:56:56     at org.postgresql.jdbc.PgStatement.executeWithFlags(pgstatement.java:341)
2024-06-11 15:56:56     at org.postgresql.jdbc.PgStatement.executeCachedSql(pgstatement.java:326)
2024-06-11 15:56:56     at org.postgresql.jdbc.PgStatement.executeWithFlags(pgstatement.java:302)
2024-06-11 15:56:56     at org.postgresql.jdbc.PgStatement.execute(pgstatement.java:297)
2024-06-11 15:56:56     at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(newproxystatement.java:75)
2024-06-11 15:56:56     at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(jdbcexecutor.java:464)
2024-06-11 15:56:56     ... 86 more
2024-06-11 15:56:56 
2024-06-11 15:56:56 UPDATE SUMMARY
2024-06-11 15:56:56 Run:                         32
2024-06-11 15:56:56 Previously run:             302
2024-06-11 15:56:56 Filtered out:                49
2024-06-11 15:56:56 -------------------------------
2024-06-11 15:56:56 Total change sets:          383
```

### Information about your Metabase installation

```JSON
- Metabase version: 0.49.6 (tried the migration starting with the 0.49.13 as well
- Metabase environment: Docker
- Metabase internal database: PostgreSQL
```

### Severity

blocking usage of Metabase entirely

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sansolovyov**
Fixes #44012

We did not trigger that error during testing since when `enable-query-caching` setting is encrypted, then migration is a no-op effectively. This means we need to decrypt those settings before running migration - it doesn't matter that much since they will be removed in the next version anyway.

We need original migration to run once again for everyone who had `enable-query-caching` encrypted, which is why I moved it to a new id. Why moved instead of copying: I think a stale entry in `databasechangelog` is preferential to a duplication in migrations.yaml, which is often read by people and could be confusing.

There is also a new migration for MySQL, for those people who had same partially-encrypted settings table. MySQL, encountering invalid integer value, returns 0 in some versions. This migration update config with correct values *if* the config was not updated by a human yet.

### CODE REVIEW

**Review by qnkhuat — APPROVED** [review]
I repro-ed this and checked out this branch and it fixes it.

I'm not too sure about changing the migration id though.

I'd approach it differently by making the original migration to mark ran when it fails though(see [failOnError](https://docs.liquibase.com/concepts/changelogs/attributes/fail-on-error.html)) .This way we don't have to remove the migration.

Just a suggestion, as I don't think the current approach has many downsides. So feel free to merge :)

**Review by qnkhuat — DISMISSED** [review]
a new [issue](https://metaboat.slack.com/archives/C0641E4PB9B/p1718198279276439?thread_ts=1718120957.799409&cid=C0641E4PB9B) with Mysql just came to light

**Comment by calherries** [comment]
+1 to Ngoc's concern with changing the migration ID. Is the original migration is idempotent? The original migration will now run twice for those that upgrade from 49 to 50.0, and then to 50.1

**Comment by piranha** [comment]
> Is the original migration is idempotent?

It is! :)

File: test/metabase/db/custom_migrations_test.clj [hunk 1]
```diff
@@ -1995,3 +1996,21 @@
           :date_joined   :%now})
         (migrate!)
         (is (false? (sample-content-created?)))))))
+
+(deftest decrypt-cache-settings-test
+  (impl/test-migrations "v50.2024-06-12T12:33:07" [migrate!]
+    (encryption-test/with-secret-key "whateverwhatever"
+      (mdb.query/update-or-insert! :model/Setting {:key "enable-query-caching"} (constantly {:value "true"}))
+      (mdb.query/update-or-insert! :model/Setting {:key "query-caching-ttl-ratio"} (constantly {:value "100"}))
+      (mdb.query/update-or-insert! :model/Setting {:key "query-caching-min-ttl"} (constantly {:value "123"})))
```
Comment (calherries) [inline test/metabase/db/custom_migrations_test.clj:2005]: I see this was an existing issue with the tests before, and should not block the PR, but just like migrations, migration tests shouldn't depend on toucan model code because they are subject to change. Dependencies of migrations and their tests should be limited to things unlikely to change because migration bugs have such a high impact. So this should be replaced with:
```
(encryption-test/with-secret-key "whateverwhatever"
      (t2/insert! :setting [{:key "enable-query-caching", :value (encryption/maybe-encrypt "true")}
                            {:key "query-caching-ttl-ratio", :value (encryption/maybe-encrypt "100")}
                            {:key "query-caching-min-ttl", :value (encryption/maybe-encrypt "123")}]))
```

Comment (piranha) [reply test/metabase/db/custom_migrations_test.clj:2005]: oh, indeed! I was too caught up with other stuff, will update the code right now

File: test/metabase/db/schema_migrations_test.clj [hunk 2]
```diff
@@ -1494,10 +1496,13 @@
...
 (deftest cache-config-migration-test
   (testing "Caching config is correctly copied over"
-    (impl/test-migrations "v50.2024-04-12T12:33:09" [migrate!]
-      (mdb.query/update-or-insert! :model/Setting {:key "enable-query-caching"} (constantly {:value "true"}))
-      (mdb.query/update-or-insert! :model/Setting {:key "query-caching-ttl-ratio"} (constantly {:value "100"}))
-      (mdb.query/update-or-insert! :model/Setting {:key "query-caching-min-ttl"} (constantly {:value "123"}))
+    (impl/test-migrations ["v50.2024-06-12T12:33:07"] [migrate!]
+      ;; this peculiar setup is to reproduce #44012, `enable-query-caching` should be unencrypted for the condition
+      ;; to hit it
+      (t2/insert! :setting [{:key "enable-query-caching", :value (encryption/maybe-encrypt "true")}])
```
Comment (calherries) [inline test/metabase/db/schema_migrations_test.clj:1502]: If the test instance has encryption enabled, this will still encrypt the value, but with the encryption key for the instance. Just remove the `maybe-encrypt` call entirely like this:
```suggestion
      (t2/insert! :setting [{:key "enable-query-caching", :value "true"}])
```

File: test/metabase/db/schema_migrations_test.clj [hunk 3]
```diff
@@ -1554,7 +1562,35 @@
                                                       (assoc :cache_ttl 10)))
       (migrate!)
       (is (= []
-             (t2/select :model/CacheConfig))))))
+             (t2/select :cache_config))))))
+
+(deftest cache-config-mysql-update-test
+  (when (= (mdb/db-type) :mysql)
```
Comment (calherries) [inline test/metabase/db/schema_migrations_test.clj:1568]: This doesn't stop the test from running on H2 when the application database is MySQL.

If you execute 
`(mt/set-test-drivers! [:h2])`
And then run this test, it will run the test migrations on an H2 database and the test will fail because the MySQL migration doesn't run.

You need to change this to use mysql for the tests
```suggestion
  (mt/test-driver :mysql
```

**Review by calherries — APPROVED** [review]
LGTM, all I see are some small problems with running the tests locally, but they don't appear in CI so we can merge this now and fix them later
