### PR TITLE
Group by "pivot-grouping" column

### LINKED ISSUE #14148: Pivot Table creates failing query and never shows visualization
**Describe the bug**
Pivot Table visualization (0.38) creates incorrect query and just shows loading-spinner forever, even though the request completes and no errors/stacktraces in the log, the request response content is a stacktrace.

**To Reproduce**
1. Make any query like this (uses the application database on Postgres)
image
2. Visualize - this will show a Bar chart by default - change visualization to Pivot Table, it will just show loading spinner forever:
image
3. Looking at the successful request response `POST /api/advanced_computation/pivot/dataset`, it's a stacktrace instead of normal structured data - error is `ERROR: column \"source.pivot-grouping\" must appear in the GROUP BY clause or be used in an aggregate function`

<details><summary>Full response stacktrace</summary>

`
{"via":[{"type":"org.postgresql.util.PSQLException","message":"ERROR: column \"source.pivot-grouping\" must appear in the GROUP BY clause or be used in an aggregate function\n  Position: 99","at":["org.postgresql.core.v3.QueryExecutorImpl","receiveErrorResponse","QueryExecutorImpl.java",2497]}],"trace":[["org.postgresql.core.v3.QueryExecutorImpl","receiveErrorResponse","QueryExecutorImpl.java",2497],["org.postgresql.core.v3.QueryExecutorImpl","processResults","QueryExecutorImpl.java",2233],["org.postgresql.core.v3.QueryExecutorImpl","execute","QueryExecutorImpl.java",310],["org.postgresql.jdbc.PgStatement","executeInternal","PgStatement.java",446],["org.postgresql.jdbc.PgStatement","execute","PgStatement.java",370],["org.postgresql.jdbc.PgPreparedStatement","executeWithFlags","PgPreparedStatement.java",149],["org.postgresql.jdbc.PgPreparedStatement","executeQuery","PgPreparedStatement.java",108],["com.mchange.v2.c3p0.impl.NewProxyPreparedStatement","executeQuery","NewProxyPreparedStatement.java",431],["metabase.driver.sql_jdbc.execute$fn__77048","invokeStatic","execute.clj",266],["metabase.driver.sql_jdbc.execute$fn__77048","invoke","execute.clj",264],["clojure.lang.MultiFn","invoke","MultiFn.java",234],["metabase.driver.sql_jdbc.execute$execute_reducible_query","invokeStatic","execute.clj",391],["metabase.driver.sql_jdbc.execute$execute_reducible_query","invoke","execute.clj",376],["metabase.driver.sql_jdbc.execute$execute_reducible_query","invokeStatic","execute.clj",385],["metabase.driver.sql_jdbc.execute$execute_reducible_query","invoke","execute.clj",376],["metabase.driver.sql_jdbc$fn__78557","invokeStatic","sql_jdbc.clj",49],["metabase.driver.sql_jdbc$fn__78557","invoke","sql_jdbc.clj",47],["clojure.lang.MultiFn","invoke","MultiFn.java",244],["metabase.query_processor.context$executef","invokeStatic","context.clj",59],["metabase.query_processor.context$executef","invoke","context.clj",48],["metabase.query_processor.context.default$default_runf","invokeStatic","default.clj",69],["metabase.query_processor.context.default$default_runf","invoke","default.clj",67],["metabase.query_processor.context$runf","invokeStatic","context.clj",45],["metabase.query_processor.context$runf","invoke","context.clj",39],["metabase.query_processor.reducible$pivot","invokeStatic","reducible.clj",34],["metabase.query_processor.reducible$pivot","invoke","reducible.clj",31],["metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46221","invoke","mbql_to_native.clj",26],["metabase.query_processor.middleware.check_features$check_features$fn__45497","invoke","check_features.clj",42],["metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46386","invoke","optimize_datetime_filters.clj",133],["metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44298","invoke","auto_parse_filter_values.clj",44],["metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39953","invoke","wrap_value_literals.clj",149],["metabase.query_processor.middleware.annotate$add_column_info$fn__39816","invoke","annotate.clj",575],["metabase.query_processor.middleware.permissions$check_query_permissions$fn__45372","invoke","permissions.clj",70],["metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46904","invoke","pre_alias_aggregations.clj",40],["metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45570","invoke","cumulative_aggregations.clj",61],["metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47141","invoke","resolve_joined_fields.clj",36],["metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__47460","invoke","resolve_joins.clj",183],["metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__43896","invoke","add_implicit_joins.clj",254],["metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__46182","invoke","large_int_id.clj",44],["metabase.query_processor.middleware.limit$limit$fn__46207","invoke","limit.clj",38],["metabase.query_processor.middleware.format_rows$format_rows$fn__46162","invoke","format_rows.clj",75],["metabase.query_processor.middleware.desugar$desugar$fn__45636","invoke","desugar.clj",22],["metabase.query_processor.middleware.binning$update_binning_strategy$fn__44657","invoke","binning.clj",229],["metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__45174","invoke","resolve_fields.clj",24],["metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__43444","invoke","add_dimension_projections.clj",318],["metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43647","invoke","add_implicit_clauses.clj",141],["metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44045","invoke","add_source_metadata.clj",105],["metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47101","invoke","reconcile_breakout_and_order_by_bucketing.clj",98],["metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44245","invoke","auto_bucket_datetimes.clj",140],["metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45221","invoke","resolve_source_table.clj",46],["metabase.query_processor.middleware.parameters$substitute_parameters$fn__46886","invoke","parameters.clj",114],["metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45273","invoke","resolve_referenced.clj",80],["metabase.query_processor.middleware.expand_macros$expand_macros$fn__45892","invoke","expand_macros.clj",158],["metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__44054","invoke","add_timezone_info.clj",15],["metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47822","invoke","splice_params_in_response.clj",32],["metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47112$fn__47116","invoke","resolve_database_and_driver.clj",33],["metabase.driver$do_with_driver","invokeStatic","driver.clj",61],["metabase.driver$do_with_driver","invoke","driver.clj",57],["metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47112","invoke","resolve_database_and_driver.clj",27],["metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46110","invoke","fetch_source_query.clj",267],["metabase.query_processor.middleware.store$initialize_store$fn__47831$fn__47832","invoke","store.clj",11],["metabase.query_processor.store$do_with_store","invokeStatic","store.clj",44],["metabase.query_processor.store$do_with_store","invoke","store.clj",40],["metabase.query_processor.middleware.store$initialize_store$fn__47831","invoke","store.clj",10],["metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__45150","invoke","cache.clj",214],["metabase.query_processor.middleware.validate$validate_query$fn__47840","invoke","validate.clj",10],["metabase.query_processor.middleware.normalize_query$normalize$fn__46234","invoke","normalize_query.clj",22],["metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__43914","invoke","add_rows_truncated.clj",36],["metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47807","invoke","results_metadata.clj",147],["metabase.query_processor.reducible$async_qp$qp_STAR___36611$thunk__36612","invoke","reducible.clj",103],["metabase.query_processor.reducible$async_qp$qp_STAR___36611$fn__36614","invoke","reducible.clj",108],["clojure.core$binding_conveyor_fn$fn__5754","invoke","core.clj",2030],["clojure.lang.AFn","call","AFn.java",18],["java.util.concurrent.FutureTask","run",null,-1],["java.util.concurrent.ThreadPoolExecutor","runWorker",null,-1],["java.util.concurrent.ThreadPoolExecutor$Worker","run",null,-1],["java.lang.Thread","run",null,-1]],"cause":"ERROR: column \"source.pivot-grouping\" must appear in the GROUP BY clause or be used in an aggregate function\n  Position: 99","_status":500}
`

</details>

**Information about your Metabase Installation:**
Metabase 0.38.0-rc1 and `master` querying Postgres, Redshift and BigQuery. It works querying MySQL and H2.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #14148

The issue was due to H2's leniency towards ungrouped columns. The `pivot-grouping` column is a constant expression to identify the breakouts used in a row. Not grouping by that works fine for H2 but fails in Postgres. To fix that I added it as a breakout. 

Question: How can I ensure the tests run against all drivers? Or, are they and we never ran `[ci all]`?

### CODE REVIEW

File: src/metabase/query_processor/pivot.clj [hunk 1]
```diff
@@ -32,7 +32,7 @@
   "Add the grouping field and expression to the query"
   [query breakout bitmask]
   (-> query
-      (assoc-in [:query :breakout] breakout)
+      (assoc-in [:query :breakout] (conj (seq breakout) [:expression "pivot-grouping"]))
```
Comment (paulrosenzweig) [inline src/metabase/query_processor/pivot.clj:35]: `(conj (seq breakout)...` feels wrong. I think one of the values for `breakout` is a vector since it was being appended for one of the breakouts in the test. Is there a better way to append/prepend consistently?

Comment (sbelak) [reply src/metabase/query_processor/pivot.clj:35]: `cons` always prepends, but returns a seq which is not ideal (in general the schema calls for a vector and as you've just experienced we don't always gracefully handle other seq types). If you want to consistently append, we usually use either `(concat seq [value])`, or `(conj (vec seq) breakout)`. In general I personally prefer `concat` as it's the most explicit, but in this case explicitly casting to vector is being nice to everyone downstream. 

Having said all that, if this is only to make the Testing Gods happy, I'd be tempted to just change the tests and sneak in something along the lines of `(update :breakout sort)`, rather than complicating things here.

**Review by sbelak — CHANGES_REQUESTED** [review]
All tests should be wrapped in `(mt/test-drivers (mt/normal-drivers-with-feature :expressions)` else things will break for drivers that don't support expressions (incidentally how is this -- driver not supporting expressions -- accounted for in the UI and in normal usage). 

Aside from that, looks good. 

`[ci all]` forces the tests to be run against all drivers.

**Comment by paulrosenzweig** [comment]
> incidentally how is this -- driver not supporting expressions -- accounted for in the UI and in normal usage

😬 it's not. If there's no clear workaround on the server, we can disable pivot tables for those dbs.

**Comment by sbelak** [comment]
> > incidentally how is this -- driver not supporting expressions -- accounted for in the UI and in normal usage
> 
> 😬 it's not. If there's no clear workaround on the server, we can disable pivot tables for those dbs.

I don't think there's a clean workaround. We perhaps picked the wrong abstraction level and now there's no way for a driver to overwrite the pivot computation implementation. Probably best disable it for now and open a followup issue.

**Comment by camsaul** [comment]
You don't need to use `[ci all]` anymore -- CI will do the right thing automatically now

**Review by camsaul — APPROVED** [review]
LGTM

**Comment by robdaemon** [comment]
@camsaul sweet, I'm working on resolving the driver tests right now, otherwise they'll haunt us (they're not specific to this change, but because of the new `sample-dataset`)

**Comment by robdaemon** [comment]
so I had to make a few changes to the Snowflake driver for this, and then go into the Snowflake web UI and drop the broken `v3_sample_dataset` database so it could be reinserted.

Redshift seems to be timing out, so I'll see if there's another way to pre-load the data into Redshift.

**Review by sbelak — APPROVED** [review]
Looks good
