### PR TITLE
Relax constraints on GET /api/user/:id endpoint

### LINKED ISSUE #44034: "Not able to modify the internal user" for example dashboard creator user
### Describe the bug

I'm the author of [dbt-metabase](https://github.com/gouline/dbt-metabase) that allows users to export Metabase dashboards as dbt exposures. To populate the exposure owner, I use dashboard `creator` block whenever available or `creator_id` fetched via [`GET /api/user/:id`](https://www.metabase.com/docs/latest/api/user#get-apiuserid) otherwise.

Attempting to query the `creator_id` on example dashboards returns HTTP 400 "Not able to modify the internal user", even though I'm only reading, not modify it. [`GET /api/dashboard/:id`](https://www.metabase.com/docs/latest/api/dashboard#get-apidashboardid) also doesn't return the `creator` block like some others (e.g. [`GET /api/dashboard/`](https://www.metabase.com/docs/latest/api/dashboard#get-apidashboard)), so there's nowhere to get that name from.

### To Reproduce

1. Fresh install of Metabase 50
2. Query `GET /api/dashboard/:id` with any example dashboard ID (from `GET /api/dashboard`)
3. Find `creator_id` and query API `GET /user/:id` with that ID
4. Observe HTTP 400 "Not able to modify the internal user" response

### Expected behavior

- **Option 1:** `GET /user/:id` responds 200 with internal user details
- **Option 2:** `GET /api/dashboard/:id` includes `creator` block with user details

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Metabase version: 0.50.0
```

### Severity

Annoying

### Additional context

There's likely no legitimate use case for exporting examples to dbt, but I'm sure users will attempt to export everything and be puzzled by the error. For now, I'm filtering for 400 responses that mention "internal user", not the most elegant workaround.

### PR DESCRIPTION
**Pull request by noahmoss**
Resolves https://github.com/metabase/metabase/issues/44034

* Allows internal user to be fetched by ID
* Allows deactivated users to be fetched by ID

Discussion: https://metaboat.slack.com/archives/C064EB1UE5P/p1718200137771559

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#44100** <a href="https://app.graphite.dev/github/pr/metabase/metabase/44100?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: src/metabase/api/user.clj [hunk 1]
```diff
@@ -19,7 +19,7 @@
    [metabase.models.login-history :refer [LoginHistory]]
    [metabase.models.permissions-group :as perms-group]
    [metabase.models.setting :refer [defsetting]]
-   [metabase.models.user :as user :refer [User]]
```
Comment (noahmoss) [inline src/metabase/api/user.clj:22]: Also switched this namespace over to using `:model/User` for good measure

**Comment by dpsutton** [comment]
Want to call out two things to this. I don't think they are wrong but just two user types that will be exposed following this change:

```shell
# we will expose api key users:
❯ http get localhost:3000/api/user/2 x-api-key:$API_KEY -pb
{
    "common_name": "foo",
    "email": "api-key-user-b8578580-3917-4a2e-9941-46def5e376e1@api-key.invalid",
    "first_name": "foo",
    "id": 2,
   ....
    "user_group_memberships": [
        {
            "id": 1,
            "is_group_manager": false
        },
        {
            "id": 2,
            "is_group_manager": false
        }
    ]
}
``` 

and also the internal users

```shell
❯ http get localhost:3000/api/user/13371338 x-api-key:$API_KEY -pb
{
    "common_name": "Metabase Internal",
    "date_joined": "2024-06-11T16:16:16.533833Z",
    "email": "internal@metabase.com",
    "first_name": "Metabase",
...
```

**Review by johnswanson — APPROVED** [review]
