### PR TITLE
fix: Ensure that local timestamps params work

### LINKED ISSUE #53371: Metabase casts date fields to datetime on Oracle, making indexes to be unusable
### Describe the bug

A similar one to https://github.com/metabase/metabase/issues/47026, but this time with Oracle.

### To Reproduce

1) Let's say you have a table in oracle like:
Number, (int) Date (date)
1,2020-01-01
2,2020-01-02
3,2020-01-03
4,2020-01-04
5,2020-01-05

2) Add an index into the table field

3) Now sync it with Metabase and do a query that gives you the sum between some dates... see that it will do a full table scan rather than an index scan, as we don't understand the dates and we cast it to a timestamp

### Expected behavior

We should use the plain date and not cast it

### Logs

NA

### Information about your Metabase installation

```JSON
It has always been like that
```

### Severity

P1

### Additional context

Hurting an enterprise customer

### PR DESCRIPTION
**Pull request by snoe**
Fixes #53371

By filtering a timestamp or date column on an OffsetDateTime it results in an index being missed since the lhs needs to be upcast by the db engine to a `timestamp with timezone`.

This ensures we only pass OffsetDateTime to `timestamp with timezone` columns.

Context about decision here:
https://metaboat.slack.com/archives/C0645JP1W81/p1743111964032089

### CODE REVIEW

File: src/metabase/driver/common/parameters/dates.clj [hunk 1]
```diff
@@ -11,6 +11,7 @@
    [metabase.lib.schema.parameter :as lib.schema.parameter]
    [metabase.query-processor.error-type :as qp.error-type]
    [metabase.query-processor.timezone :as qp.timezone]
+   [metabase.util :as u]
```
Comment (rileythomp) [inline src/metabase/driver/common/parameters/dates.clj:14]: nit: kondo complains unused

File: modules/drivers/oracle/test/metabase/driver/oracle_test.clj [hunk 2]
```diff
@@ -617,6 +620,33 @@
...
+                      {:query "SELECT * FROM \"mb_test\".\"date_cols_with_datetime_values_dates_with_time\" WHERE {{date_filter}}"
+                       :template-tags
+                       {"date_filter"
+                        {:name         "date_filter"
+                         :display-name "Date Filter"
+                         :type         :dimension
+                         :widget-type :date/relative
+                         :dimension    [:field (mt/id
+                                                :date_cols_with_datetime_values_dates_with_time :date_with_time) nil]}}})
+              hours (assoc query :parameters [{:type   :date/relative
```
Comment (rileythomp) [inline modules/drivers/oracle/test/metabase/driver/oracle_test.clj:639]: nit: kondo complains unused

**Review by rileythomp — APPROVED** [review]
