### PR TITLE
fix(sdk): disable dashboard card click behavior and prevent url formatting

### LINKED ISSUE #51099: Disable custom click action when in embedding sdk
Contexts:
- https://metaboat.slack.com/archives/C06FCQT0KMZ/p1733768624642749
- https://metaboat.slack.com/archives/C06FCQT0KMZ/p1736331137834799

As a temporary solution, we want to disable click behavior in the SDK components. This would work in conjunction with https://github.com/metabase/metabase/issues/51970 where SDK users would be able to define their own click behavior

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/51099

### Description

Disables the dashboard card click behaviors by not invoking the URL action if we are in the embedding sdk environment. It also prevents URL formatting for columns with semantic type of URL. See [this thread](https://metaboat.slack.com/archives/C06FCQT0KMZ/p1733768624642749) for context.

### How to verify

Scenario 1: columns with custom destinations

- Create a dashboard card with "Go to a custom destination" click action
- Click on it in the embedding sdk
- Drill-through menu should not show up
- We should not be navigated to the custom destination, i.e. nothing should happen
- Links should be formatted as plain text

Scenario 2: columns of URL semantic type
- Create a dashboard card with the "URL" semantic type
- The column must not show be formatted as URL (anchor) when rendered in sdk's dashboard component

### Checklist

- [x] Tests have been added/updated to cover changes in this PR - E2E

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/action.js [hunk 1]
```diff
@@ -13,10 +14,16 @@ export function performAction(
     const reduxAction = action.action();
     if (reduxAction) {
       dispatch(reduxAction);
+
       didPerform = true;
     }
   }
   if (action.url) {
+    // (metabase#51099) disable url click behavior
```
Comment (npretto) [inline frontend/src/metabase/visualizations/lib/action.js:22]: This change still makes the table display the custom link text, and renders the column as a link.

https://github.com/user-attachments/assets/d46418e9-1af1-41c0-9bb9-fb2a3b4c5570


I haven't looked too much into the details but it seems like to address that we need to change formatValueRaw, specifically https://github.com/metabase/metabase/blob/e029869dfdf1517f7c38a5cc1f1c21df24f0e005/frontend/src/metabase/lib/formatting/value.tsx#L166-L167

Do you know how much we'd be in prod with this simpler solution?

File: e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx [hunk 2]
```diff
@@ -71,4 +80,40 @@ describeEE("scenarios > embedding-sdk > interactive-dashboard", () => {
       cy.contains("This is a custom question layout.");
     });
   });
+
+  it.only("should not trigger url click behaviors when clicking on cards (metabase#51099)", () => {
```
Comment (npretto) [inline e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx:84]:
```suggestion
  it("should not trigger url click behaviors when clicking on cards (metabase#51099)", () => {
```

File: e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx [hunk 3]
```diff
@@ -3,11 +3,8 @@ import {
   InteractiveQuestion,
 } from "@metabase/embedding-sdk-react";
 
-import {
-  ORDERS_DASHBOARD_DASHCARD_ID,
-  ORDERS_QUESTION_ID,
-} from "e2e/support/cypress_sample_instance_data";
-import { describeEE, getTextCardDetails } from "e2e/support/helpers";
+import { ORDERS_QUESTION_ID } from "e2e/support/cypress_sample_instance_data";
+import { describeEE, popover, POPOVER_ELEMENT } from "e2e/support/helpers";
```
Comment (npretto) [inline e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx:7]:
```suggestion
import { POPOVER_ELEMENT, describeEE, popover } from "e2e/support/helpers";
```

**Review by npretto — APPROVED** [review]
This solution is not ideal as it still shows custom text for the link and still renders the column value as link, I think we should try to see if it's hard to fallback to the default formatting, but if that takes too much then it's better to talk with Alberto

**Review by npretto — DISMISSED** [review]
This solution is not ideal as it still shows custom text for the link and still renders the column value as link, I think we should try to see if it's hard to fallback to the default formatting, but if that takes too much then it's better to talk with Alberto

File: frontend/src/metabase/visualizations/lib/action.js (hunk 1 above)
Comment (heypoom) [reply frontend/src/metabase/visualizations/lib/action.js:22]: @npretto Good catch, I'll also update the table formatting! I think this will be in production until we can implement click behaviors (e.g. linking to questions and dashboards) for SDK: https://metaboat.slack.com/archives/C06FCQT0KMZ/p1733768624642749

Comment (heypoom) [reply frontend/src/metabase/visualizations/lib/action.js]: updated in https://github.com/metabase/metabase/pull/51290/commits/b321652d228fffb61a97ed184795e6c049ad3934, should be good to go now. Thanks!

CleanShot 2567-12-20 at 03 57 00@2x

Comment (npretto) [reply frontend/src/metabase/visualizations/lib/action.js]: I was stil able to reproduce the issue for both my customized columns:
image
image

Comment (npretto) [reply frontend/src/metabase/visualizations/lib/action.js]: Note that I did customize how the link was rendered
image

Comment (heypoom) [reply frontend/src/metabase/visualizations/lib/action.js]: @npretto Woah, I didn't knew that "On-click behavior for each column" was a thing - thanks! Was scouring the docs but couldn't find out how to set that up. Let me try that.

Comment (heypoom) [reply frontend/src/metabase/visualizations/lib/action.js]: updated the formatter to skip rendering custom link text and do not show those as links.

In the SDK's Storybook:

CleanShot 2567-12-21 at 04 09 16@2x

In the main app:

CleanShot 2567-12-21 at 04 09 07@2x

Comment (heypoom) [reply frontend/src/metabase/visualizations/lib/action.js]: @npretto Thanks for pointing out the click behavior in tables! I updated the formatter to skip rendering custom link text and do not show those as links.

In the SDK's Storybook:

CleanShot 2567-12-21 at 04 18 08@2x

In the main app:

CleanShot 2567-12-21 at 04 09 07@2x

PS. I wanted to add more E2E tests to cover these cases, but seems like it'll take a bit to setup and might not be worth it for a temporary solution. I might give it a try on Monday.

File: e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx [hunk 4]
```diff
@@ -71,4 +80,40 @@ describeEE("scenarios > embedding-sdk > interactive-dashboard", () => {
       cy.contains("This is a custom question layout.");
     });
   });
+
+  it("should not trigger url click behaviors when clicking on cards (metabase#51099)", () => {
```
Comment (WiNloSt) [inline e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx:84]: Can you double check this test? I tried running this test with `master` code and it still passed, but instead, the only other existing test in this file failed.

Screenshot 2024-12-24 at 4 26 45 PM

If the test works as expected it should fail on master and pass only on this PR.

Comment (heypoom) [reply e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx:87]: @WiNloSt Thanks for catching this! This happened because the setup block created two dashcards that has same "Orders" title, so the existing test errored because it found two dashcards instead of one.

CleanShot 2568-01-07 at 23 33 58@2x

Both are green now:

Comment (heypoom) [reply e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx]: update: I rewrote the test so that it covers the table column click behavior and line chart click behavior in https://github.com/metabase/metabase/pull/51290/commits/e758a86253886c268563dfd3722ca3bc101ecff1

File: frontend/src/metabase/lib/formatting/url.tsx [hunk 5]
```diff
@@ -40,6 +41,12 @@ export function formatUrl(value: string, options: OptionsType = {}) {
   if (jsx && rich && url) {
     const text = getLinkText(value, options);
     const className = cx(CS.link, CS.linkWrappable);
+
+    // (metabase#51099) prevent url from being rendered as a link when in sdk
+    if (isEmbeddingSdk) {
+      return url;
+    }
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/formatting/url.tsx:48]: I removed this line and the test suite (`e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx`) still passes, that means it didn't assert this part of the code.

**Review by WiNloSt — COMMENTED** [review]
The test behavior is correct now, but can you check if we still need to the code that I added an inline comment, or we need more tests.

File: frontend/src/metabase/lib/formatting/url.tsx (hunk 5 above)
Comment (heypoom) [reply frontend/src/metabase/lib/formatting/url.tsx:48]: @WiNloSt oh yes, I think that is because it won't format the URL in the first place because of a condition I put in https://github.com/metabase/metabase/pull/51290/files#diff-9f8b69e52e4308de8ce217916c6f07365263f6532626dc64d4ff2976f05cac69R169-R170 - so I think the tests is correct but we might not need that change in formatting/url

Comment (heypoom) [reply frontend/src/metabase/lib/formatting/url.tsx:48]: let me remove that and see if the tests pass

**Comment by heypoom** [comment]
Putting this PR on hold while we discuss making external URLs a prop: https://metaboat.slack.com/archives/C06FCQT0KMZ/p1736331137834799

File: frontend/src/metabase/lib/formatting/url.tsx (hunk 5 above)
Comment (heypoom) [reply frontend/src/metabase/lib/formatting/url.tsx:48]: @WiNloSt I added another test case for columns with URL semantic type: https://github.com/metabase/metabase/pull/51290/commits/e40eca0fb4ad9055da3555c32d352a150b91dab3. This updates the ORDERS.PRODUCT_ID column to `type/URL` which should show up as clickable URL on Metabase app, but now becomes a plain column.

**Comment by WiNloSt** [comment]
For scenario 2) which tests the table with links in the value. Not sure if this the expected behavior.

I created a model with a custom column from Orders table and set it to `Concat("http://facebook.com","")`

It doesn't matter whether or not I set the custom column type to URL or not, I still get this drills on the SDK.

image

**Comment by heypoom** [comment]
@WiNloSt I see, I think this is expected as it gets treated like a regular text field which has drills. I think we can implement a way to disable drill actions when handling custom click actions (e.g. via `onVisualizationClick` with middlewares in https://github.com/metabase/metabase/pull/51983), so users have a choice to disable drills for other fields as well. I can add this to the tech design doc.

File: e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+        const urlCell = H.getDashboardCard(0).findByText("123");
+        urlCell.should("not.have.attr", "data-testid", "link-formatted-text");
+        urlCell.click();
+
+        popover().should("contain.text", "Filter by this value");
+
+        // Table column click behavior should be disabled in the sdk
+        H.getDashboardCard(0).should("not.contain.text", "Link Text Applied");
+        H.getDashboardCard(0).findByText("37.65").click();
+        cy.get(POPOVER_ELEMENT).should("not.exist");
```
Comment (WiNloSt) [inline e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx:120]: these assertions don't seem to work well. If I commented out
https://github.com/metabase/metabase/blob/9ab32109b70c48c51dd6d31391e7c57b37261d79/frontend/src/metabase/visualizations/lib/action.js#L23-L25

The test would still pass, but it will open a new tab to metabase.com

Comment (heypoom) [reply e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx:120]: @WiNloSt I was hoping on this block to catch the "navigating away" issue 😢 

```tsx
      // We should not be navigated away from the current page
      cy.location().then(location => {
        cy.get("@initialPath").should("eq", location.pathname);
      });
```

Comment (WiNloSt) [reply e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx:120]: It'd also be great if we could test the URL value 
image

Comment (heypoom) [reply e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx:120]: oh right, we are technically in the same tab even though we opened a new tab. let me find a better way to catch that.

Comment (heypoom) [reply e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx:129]: @WiNloSt Thanks for catching that! I updated https://github.com/metabase/metabase/pull/51290/commits/ff8b760a87c47c513b668387409e062dfb266737 to add an assertion that fails if we have opened a new window. Here is the screenshot of the test failing if I removed that block:



> It'd also be great if we could test the URL value

Ah, the test database we use does not have any fields with actual URIs, so I updated the semantic type of PRODUCT_ID to URL and assert that instead. I also added assertions that no anchor tags are present in the table as another failsafe.

https://github.com/metabase/metabase/blob/ff8b760a87c47c513b668387409e062dfb266737/e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx#L118-L122

File: e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx [hunk 7]
```diff
@@ -0,0 +1,161 @@
...
+
+    cy.intercept("GET", "/api/dashboard/*").as("getDashboard");
+    cy.intercept("POST", "/api/dashboard/*/dashcard/*/card/*/query").as(
+      "dashcardQuery",
+    );
+  });
+
+  it("should not trigger url click behaviors in the sdk (metabase#51099)", () => {
+    // Spies to intercept opening external links.
+    // See "clickLink" in frontend/src/metabase/lib/dom.js to see what we are intercepting.
```
Comment (WiNloSt) [inline e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx:94]: I was in `lib/dom.js`, but I'm not really sure what part of it this is referring to.

File: e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx [hunk 8]
```diff
@@ -0,0 +1,161 @@
...
+
+      // We should never open a window in new tab in this test.
+      cy.get<sinon.SinonSpy>("@anchorClick").then(clickSpy => {
+        const blankClicks = clickSpy
+          .getCalls()
+          .filter(
+            (call: sinon.SinonSpyCall) => call.thisValue.target === "_blank",
+          );
+
+        expect(blankClicks).to.have.length(0, "should never open a new tab");
```
Comment (WiNloSt) [inline e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx:152]: This assertion works now! It checks if a new tab has been opened.

**Review by WiNloSt — APPROVED** [review]

File: e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx (hunk 7 above)
Comment (heypoom) [reply e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx:94]: Ah, this is referring to the clickLink function which creates an `<a href>` element and clicks on it to open a link:

https://github.com/metabase/metabase/blob/76ca2833e0ec33bfcbee307530bc41283559b880/frontend/src/metabase/lib/dom.js#L339

**Comment by heypoom** [comment]
@metabase-bot backport release-x.51.x

File: e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx (hunk 7 above)
Comment (WiNloSt) [reply e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx:94]: cool thanks. Not sure why I missed the function name you referred to.
