### PR TITLE
Trend Chart Viz Should Use Proper Card execute in Rendering

### LINKED ISSUE #39854: Trend viz might not appear correctly on alerts
### Describe the bug

In some cases, trend visualization do not display correctly on alerts.

### To Reproduce

1. create a GUI question: Sample Database, Products
- filter by: Created at, previous 2 months, including current one
- summarize: Count
- group by: Created at: month
2. Set visualization to Trend. The visualization works:
image

3. Save it, and set up an alert

4. (!) The received alert does not display
image

### Expected behavior

The alert should display the viz the same way.

### Logs

n/a

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "6.1.30-0-virt",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-22",
      "tag": "v1.48.7",
      "hash": "c192db1"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P2 - reported by a customer

### Additional context

Also tested this on stats, a different error is displayed there:

image

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes: #39854

See the issue for a screenshot of the failure. After this fix:

image

The core of the issue is that `metabase.pulse.render.body/render` `:javascript_visualization` was first written for only line, area, and bar chart types. These types allow the user to add other questions to display on the same dashcard (Only in Dashobards), and the function `metabase.pulse.util/execute-multi-card` requires that a dashcard is passed in.

In the case of a subscription, this function works correctly (even though the trend chart won't actually have multi-series data). In the case of an alert, which exists on Questions, not dashboards, there is no dashcard.

So, this PR fixes this by using `metabase.pulse.util/execute-card` directly when there is no dashcard.

### CODE REVIEW

File: test/metabase/pulse/render/body_test.clj [hunk 1]
```diff
@@ -843,3 +843,28 @@
...
+        ;; which implicitly expected a DashCard to exist
+        ;; Here, we simulate an Alert (NOT a subscription) by only providing a card and not mocking a DashCard.
+        (mt/with-temp [:model/Card {card-id :id} {:display       :smartscalar
+                                                  :dataset_query q}]
+          (let [doc       (render.tu/render-card-as-hickory card-id)
+                span-text (->> doc
+                               (hik.s/select (hik.s/tag :span))
+                               (mapv (comp first :content))
+                               (filter string?)
+                               (filter #(str/includes? % "previous month")))]
```
Comment (escherize) [inline test/metabase/pulse/render/body_test.clj:867]: An observation, and no need to change anything. But maybe a helper like this would make these easier to see what is getting returned:

``` clojure
(defn seek-form [ds seeked]
    (let [*found? (atom false)]
      (walk/postwalk
       (fn [x] (when (= seeked x) (reset! *found? true)) x)
       ds)
      @*found?))

  (seek-form
   [:html
    [:body
     [:div
      [:li
       [:ol [:p.styled "eggs"]]
       [:ol {:class "selected"} [:p.styled "lemons"]]
       [:ol [:p.styled "oranges"]]
       [:ol [:p.styled "apples"]]]]]]
   [:ol [:p.styled "oranges"]])
  ;; => true

  "Elapsed time: 2.227166 msecs"
  ```

**Review by escherize — APPROVED** [review]
LGTM
