### PR TITLE
Don't consider text box dashcards for loading timer

### LINKED ISSUE #11926: Query counter shown on dashboards with a text box after 10 seconds
**Describe the bug**
Dashboard with a Text Box shows query counter/timer (#11611) after 10 seconds. It doesn't matter if the text box is the only thing on the dashboard or together with questions.

**Logs**
I don't see any different logs from an empty dashboard.

**To Reproduce**
1. Go to an empty dashboard
2. Edit dashboard and add Text Box
3. Save, and refresh browser
4. Wait 10 seconds, notice the browser title (or browser tab) shows the query counter

**Screenshots**
Screencast 2020-02-15 23 38 29

**Information about your Metabase Installation:**
Metabase `master`

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #11926

Note: merging into master since this feature isn't in v0.34.

This is the second "text boxes weren't considered" bug recently. (The other is #11929). I don't think it's yet worth adding more structure to separate out these two categories of dashcards, but it's worth considering going forward.

### CODE REVIEW

File: frontend/src/metabase/dashboard/dashboard.js [hunk 1]
```diff
@@ -1132,9 +1132,9 @@ const loadingDashCards = handleActions(
     [FETCH_DASHBOARD]: {
       next: (state, { payload }) => ({
         ...state,
-        dashcardIds: Object.values(payload.entities.dashcard || {}).map(
-          dc => dc.id,
-        ),
+        dashcardIds: Object.values(payload.entities.dashcard || {})
+          .filter(dc => dc.card.display !== "text")
```
Comment (tlrobinson) [inline frontend/src/metabase/dashboard/dashboard.js]: Would using `isVirtualDashCard` would actually be better here?

**Review by tlrobinson — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/dashboard/dashboard.js (hunk 1 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/dashboard/dashboard.js]: Ah didn't realize we had that! I'll swap that in for this and my fix for #11929.

Comment (paulrosenzweig) [reply frontend/src/metabase/dashboard/dashboard.js]: Actually the fix for #11929 only had a card not a dashcard so I left as-is. I updated this spot though.

**Review by tlrobinson — APPROVED** [review]
