### PR TITLE
Respect alphabetical order of collections in "Move" modal

### LINKED ISSUE #31294: Respect alphabetical order of collections in "Move" modal
## Feedback
Image

## Expected Behavior
Right now it appears that the collections shown in the "Move" modal don't have explicit ordering. Let's make them alphabetical to better match the behavior in the sidebar and user expectations.

Image

### LINKED ISSUE #31425: Add to Dashboard/Save Question Menu doesn't respect Collection Alphabetical order as in Main Menu
### Describe the bug

In the Main Menu Collections are sorted Alphabetically but when you go to Add a Question form a Dashboard those seem to be ordered based on creation Date

### To Reproduce

1. Go to New Collection -> Name it `a` -> Save
2. Go to New Collection -> Name it `c` -> Save
3. Go to New Collection -> Name it `b` -> Save

image

4. New -> Dashboard -> Add Question -> Notice how order is not alphabetically anymore:

image

5. This also happens when you create a new question and save it:

image

### Expected behavior

Same ordering, ideally alphabetically

### Logs

None

### Information about your Metabase installation

```JSON
1.46.4 and master
```

### Severity

minor

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #31294
Closes #31425

### Description

- I discovered that there was the same sorting issue with Snippet Collection Picker and got green light from Roman to fix it as well, so the fix is included here.
- I reported this issue I found while working on this: #31394

### How to verify

Currently collections are ordered by id - the earlier collection was created, the earlier it will be on the list in the picker.
We want the collections to be sorted alphabetically instead.
See demos below for exact reproduction steps.

<details>
<summary>
<h3>Demo - Collection Picker</h3>
</summary>

#### Before

https://github.com/metabase/metabase/assets/6830683/b963f134-54ba-48da-8254-1315803c22ed

#### After

https://github.com/metabase/metabase/assets/6830683/9b55fc33-3030-4d22-8bdc-0fab0e7ac362

</details>
<details>
<summary>
<h3>Demo - Snippet Collection Picker</h3>
<p>This can be tested only using the Enterprise Edition.</p>
</summary>

#### Before

https://github.com/metabase/metabase/assets/6830683/891b18d6-ff99-4b04-930c-64f22118a427

#### After

https://github.com/metabase/metabase/assets/6830683/932c4055-28c2-48dd-808d-c238a016e35b

</details>

### CODE REVIEW

**Review by ranquild — CHANGES_REQUESTED** [review]
Added a comment about mocking _list state. Please ping me if you have questions about that

**Review by ranquild — CHANGES_REQUESTED** [review]
@kamilmielnik As discussed, we don't test reducers (you can search for this in the official redux docs for the rationale). I'd follow the steps from the issue https://github.com/metabase/metabase/issues/31294, render the affected component with mocked BE data, and check that the order of the items is preserved. To simulate the issue you would likely need to add some other existing collections to the `entities` state directly before rendering the component. Please let me know if that works

File: frontend/src/metabase/common/hooks/use-collections-query/use-collections-query.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
+import type { Collection, CollectionListQuery } from "metabase-types/api";
+import Collections from "metabase/entities/collections";
+
+import {
+  UseEntityListQueryProps,
+  UseEntityListQueryResult,
+  useEntityListQuery,
+} from "../use-entity-list-query";
+
+export const useCollectionsQuery = (
```
Comment (ranquild) [inline frontend/src/metabase/common/hooks/use-collections-query/use-collections-query.ts:10]: `useCollectionListQuery` - please follow the established conventions

File: frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js [hunk 2]
```diff
@@ -241,4 +294,134 @@ describe("ItemPicker", () => {
...
+
+  describe("preserves order of collections coming from API endpoint", () => {
+    it("[personal, regular, regular 2]", async () => {
+      const collections = [
+        COLLECTION.PERSONAL,
+        COLLECTION.REGULAR,
+        COLLECTION.REGULAR_2,
+      ];
+
+      fetchMock.get("path:/api/collection", collections);
```
Comment (ranquild) [inline frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js:306]: We setup fetch mocks within the `setup` function, and use mocks defined in `server-mocks`

File: frontend/test/__support__/server-mocks/collection.ts [hunk 3]
```diff
@@ -14,8 +14,23 @@ import {
 } from "metabase-lib/metadata/utils/saved-questions";
 import { PERMISSION_ERROR } from "./constants";
 
-export function setupCollectionsEndpoints(collections: Collection[]) {
-  fetchMock.get("path:/api/collection/root", ROOT_COLLECTION);
+export function setupCollectionsEndpoints({
```
Comment (ranquild) [inline frontend/test/__support__/server-mocks/collection.ts:17]: We have different functions to setup error cases, and the one for collections already exist - it's `setupUnauthorizedCollectionsEndpoints`. Please use the existing one.

**Review by ranquild — COMMENTED** [review]
@kamilmielnik Looks very good! I've left some comments about using the established patterns, please take a look

File: frontend/src/metabase/common/hooks/use-collections-query/use-collections-query.ts (hunk 1 above)
Comment (kamilmielnik) [reply frontend/src/metabase/common/hooks/use-collections-query/use-collections-query.ts]: 3b8b52fc54755af96433335406bb470d8132fe94

File: frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js (hunk 2 above)
Comment (kamilmielnik) [reply frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js:309]: This was a leftover, good catch, removed: 4d444a33f293169f855ace66217f27f6a86c81bf

File: frontend/test/__support__/server-mocks/collection.ts (hunk 3 above)
Comment (kamilmielnik) [reply frontend/test/__support__/server-mocks/collection.ts:17]: I think setup like this would be semantically misleading - after all we're not testing authorization here.
It'd be more appropriate to use a more generic error.

BTW `setupUnauthorizedCollectionsEndpoints` is unused.
I'll reuse it as suggested but first refactor it to allow more generic errors.

Comment (kamilmielnik) [reply frontend/test/__support__/server-mocks/collection.ts:17]: > We have different functions to setup error cases,

Did just that: eb8e6377729da45557ee926f2c17bda8064563ce

File: frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js (hunk 2 above)
Comment (kamilmielnik) [reply frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js]: + 066febb437e5081f5f14a37e007dcc80d2269363

File: frontend/src/metabase/entities/collections/constants.ts [hunk 4]
```diff
@@ -1,12 +1,17 @@
 import { t } from "ttag";
 
+import { Collection } from "metabase-types/api";
+
 export const DEFAULT_COLLECTION_COLOR_ALIAS = "brand";
 
-export const ROOT_COLLECTION = {
+export const ROOT_COLLECTION: Collection = {
```
Comment (ranquild) [inline frontend/src/metabase/entities/collections/constants.ts:7]: We shouldn't do it like that. The constant is used in the app for real and setting values `can_write: false` affects the runtime behavior. Furthermore, it's on purpose not a `Collection`, it's only a constant with a set of properties that the root collection has. 

If you need to pass it to somewhere in test where a `Collection` is expected, you need to use `createMockCollection(ROOT_COLLECTION)`

**Review by ranquild — CHANGES_REQUESTED** [review]
`ROOT_COLLECTION` should not be changed

File: enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx [hunk 5]
```diff
@@ -40,27 +50,30 @@ const TEST_CARD = createMockCard({
   },
 });
 
-const setup = ({
+const TestComponent: typeof EditSandboxingModal = props => {
```
Comment (ranquild) [inline enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx:53]: It's not clear why we're changing this. We should only preload data via the hooks in the test component if the component expects its to be loaded and doesn't handle loading the data himself. Is that's the case here? I've quickly went over `EditSandboxingModal` and couldn't find that it expects them to be preloaded.

If the component handles the data loading (e.g. using the entity loader / hook) it should be fine just to use `setupCollectionsEndpoints`

**Review by ranquild — COMMENTED** [review]
Unclear test changes

File: enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx (hunk 5 above)
Comment (kamilmielnik) [reply enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx:53]: `EditSandboxingModal` uses `QuestionPicker` which uses `ItemPicker` which triggers `Collections.selectors.getExpandedCollectionsById`, which I modified, which now uses `Collections.selectors.getList`, which uses `entity.selectors.getObject` which  requires `collections_list` to be present in the redux store.

Comment (kamilmielnik) [reply enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx:53]: Without this rendering will crash because of data missing from redux store.

Comment (kamilmielnik) [reply enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx:53]: > Is that's the case here? 

Yes, I believe so.

Comment (ranquild) [reply enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx:53]: @kamilmielnik if the above is true, `ItemPicker` should be fixed and it should call `Collections.loadList` or new `useCollectionListQuery` - there shouldn't be a dependency like this. Can you fix this?

**Review by ranquild — COMMENTED** [review]
Commented inline

File: enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx (hunk 5 above)
Comment (kamilmielnik) [reply enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx]: Ok, now I get it.

Turns out there was a bug and the error message was misleading. I reverted these changes.

Good catch, thanks :+1: 

7c030c1fcd3fbb5a5ee03087e4ac66caf14857e1

**Review by cdeweyx — APPROVED** [review]
Working as expected, nice job

**Review by ranquild — APPROVED** [review]
