### PR TITLE
Fix no visual feedback when updating data model column properties

### LINKED ISSUE #19710: No visual feedback when setting column properties in Admin > Data Model
1. Go to Admin > Data Model > select a table
2. Change "No semantic type" for one of the columns to an FK relationship
3. There is no visual feedback to show that this has been persisted and no save button. I had to hit refresh on the page for me to feel confident my changes were actually saved.

image

### PR DESCRIPTION
**Pull request by WiNloSt**
Fix #19710

### Repro steps
See #19710

> 1. Go to Admin > Data Model > select a table
> 2. Change "No semantic type" for one of the columns to an FK relationship
> 3. There is no visual feedback to show that this has been persisted and no save button. I had to hit refresh on the page for me to feel confident my changes were actually saved.

### Before the fix
There's no toast message after any property is updated.

### After the fix
image

### CODE REVIEW

File: frontend/src/metabase/admin/datamodel/containers/MetadataEditorApp.jsx [hunk 1]
```diff
@@ -48,7 +48,7 @@ const mapDispatchToProps = {
       : push(`/admin/datamodel/database/${id}`),
   selectTable: ({ id, db_id }) =>
     push(`/admin/datamodel/database/${db_id}/table/${id}`),
-  updateField: field => Fields.actions.update(field),
+  updateField: field => Fields.actions.updateField(field),
```
Comment (WiNloSt) [inline frontend/src/metabase/admin/datamodel/containers/MetadataEditorApp.jsx:51]: I see we don't call too `Entity.actions.update` with lots of parameters directly, but we do that in the entity file.

File: frontend/src/metabase/entities/fields.js [hunk 2]
```diff
@@ -86,6 +87,13 @@ const Fields = createEntity({
       return { id, values };
     }),
 
+    updateField(field, opts) {
```
Comment (WiNloSt) [inline frontend/src/metabase/entities/fields.js:90]: I assume `opts` would likely be `undefined` but I put it here anyway since other entities seems to always pass along `opts`.

**Review by daltojohnso — CHANGES_REQUESTED** [review]
I noticed that for some reason the "Undo" button breaks when on the ID field of the Products table:

https://user-images.githubusercontent.com/13057258/157135872-9013767a-8e0c-4693-b436-66901895e755.mov

I see in my debugger that the field still has a table property that is an instance of `Table` from `metabase-lib`. This is likely the source of the circular reference as it contains a list of `fields`, I think. It's worth looking at why this field has the references and others seem not to have them. Fix might simply be to remove the property, but I'm not 100% certain about that.

**Comment by WiNloSt** [comment]
> I noticed that for some reason the "Undo" button breaks when on the ID field of the Products table:
> 
>  Screen.Recording.2022-03-07.at.3.30.31.PM.mov 
> I see in my debugger that the field still has a table property that is an instance of `Table` from `metabase-lib`. This is likely the source of the circular reference as it contains a list of `fields`, I think. It's worth looking at why this field has the references and others seem not to have them. Fix might simply be to remove the property, but I'm not 100% certain about that.

@daltojohnso I think I know why this happened. When we try to undo any entity action, we will get the original object
https://github.com/metabase/metabase/blob/16d319400ae86e7b9df1b2634efcb8c781ac813a/frontend/src/metabase/lib/entities.js#L246-L248

And with `Field`, it implements its own `getObject` rather than using the default in https://github.com/metabase/metabase/blob/16d319400ae86e7b9df1b2634efcb8c781ac813a/frontend/src/metabase/lib/entities.js#L386-L391

and the way `getMetadata(state).field(entityId)` works is that (as far as I understand) it tries to populate the field data similar to how [normalizr](https://github.com/paularmstrong/normalizr)'s `denormalize` does that's why the `table` property inside the ID field is an instance of `Table`

https://github.com/metabase/metabase/blob/e152e67f72597d9217aae3b913361c0cee30159b/frontend/src/metabase/selectors/metadata.js#L71

https://github.com/metabase/metabase/blob/692e7f44da378bbe2cddb4593044c5c0d64ed160/frontend/src/metabase-lib/lib/metadata/Field.ts#L47

One interesting thing is that, only the IDs field seems to have `table` as an object in the response. e.g. from this API call
`api/database/1/idfields`

#### response
```json
[
  {
    ...,
    "table": {
      "description": "Confirmed Sample Company orders for a product, from a user.",
      "entity_type": "entity/TransactionTable",
      "schema": "PUBLIC",
      "show_in_getting_started": false,
      "name": "ORDERS",
      "caveats": "You can join this on the Products and Orders table using the ID fields. Discount is left null if not applicable.",
      "updated_at": "2022-03-08T08:36:00.228684Z",
      "active": true,
      "id": 2,
      "db_id": 1,
      "visibility_type": null,
      "field_order": "database",
      "initial_sync_status": "complete",
      "display_name": "Orders",
      "created_at": "2022-03-03T08:26:17.604932Z",
      "points_of_interest": "Is it? You tell us!"
    }
  }
]
```

That's how in the end the response is denormalized and `table` is turned into `Table`.

#### Here's my proposal

Remove this line from `fields.js` https://github.com/metabase/metabase/blob/3a257c23bd7599f24e8793c10e24287da0b6562e/frontend/src/metabase/entities/fields.js#L50, so it'll use the default `getObject` which is more appropriate for undoing actions, as we should be using the actual response when undoing not the denormalized object which contains more data than needed.

Imagine the API returns `{ id: 1, other_entity: 2 }`, but when undoing actions we send `{ id: 1, other_entity: { id: 2 }}` instead. That'd be weird and that's why that circular dependency caused `JSON.stringify` to fail.

However, I'm not quite sure if it'll break other pages or not, I only tested that it works fine on this very page.

File: frontend/src/metabase/lib/entities.js [hunk 3]
```diff
@@ -259,12 +259,14 @@ export function createEntity(def) {
...
-              originalObject,
-              ...Object.keys(updatedObject || {}),
-            );
+          // pick only the attributes that were updated
+          const undoObject = _.pick(
+            originalObject,
+            ...Object.keys(updatedObject || {}),
+          );
+          // https://github.com/metabase/metabase/pull/20874#pullrequestreview-902384264
+          const canUndo = !hasCircularReference(undoObject);
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/entities.js:268]: @daltojohnso This is kind of a hack to not show an `undo` button when we detect circular reference.

https://www.loom.com/share/b60b9abe30ed490286636089ad77a110

**Review by daltojohnso — APPROVED** [review]
Thanks for the digging into this and giving a thorough write-up. Interesting stuff. I went looking to see what `/api/database/:dbId/idfields` is used for in the FE, and it seems like we just use it for this code here: https://github.com/metabase/metabase/blob/e144e993851911156eb1303c8260168836713af8/frontend/src/metabase/admin/datamodel/components/database/ColumnItem.jsx#L184

I wonder if at some point we can refactor away the need for this request since we are also fetching fields via `/api/table/:tableId/query_metadata` and I think that request might be sufficient when paired with a request for tables.

**Comment by WiNloSt** [comment]
> I wonder if at some point we can refactor away the need for this request

Maybe not. https://github.com/metabase/metabase/blob/b78c9832672446554c0dc52be163a09d97babaf0/frontend/src/metabase/admin/datamodel/components/database/ColumnItem.jsx#L254

the `idfields` is currently used for a dropdown for `Foreign Key` type
image

`/api/table/:tableId/query_metadata` seems to only fetch the data for 1 table, but for the dropdown we'd have to have every table's ID field, I assume `/api/database/:dbId/idfields` is for that.

**Comment by flamber** [comment]
@WiNloSt Would it be possible to do the same, when you're on the field details page (click :gear: icon) - just for consistency?

**Comment by WiNloSt** [comment]
@flamber I'm on it.
