### PR TITLE
Add /api/ee/ai-fix-sql/fix endpoint

### LINKED ISSUE #53142: [BE] Add a endpoint to autofix SQL

### LINKED ISSUE #53144: [BE] Add `ai-sql-fixer` token feature

### PR DESCRIPTION
**Pull request by metamben**
Fixes #53142
Fixes #53144

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/ai_sql_fixer/api.clj [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+   [metabase.util.malli.schema :as ms]))
+
+(api.macros/defendpoint :post "/fix"
+  "Suggest fixes for a SQL query."
+  [_route-params
+   _query-params
+   {:keys [query error_message]} :- [:map
+                                     [:query [:map
+                                              [:database ms/PositiveInt]
+                                              [:pretty   {:default true} [:maybe :boolean]]]]
```
Comment (ranquild) [inline enterprise/backend/src/metabase_enterprise/ai_sql_fixer/api.clj:21]: `pretty` should be removed as otherwise line numbers would not match.

**Review by ranquild — APPROVED** [review]
Please remove `pretty`, otherwise lgtm

**Review by Somtom — APPROVED** [review]

File: enterprise/backend/src/metabase_enterprise/ai_sql_fixer/api.clj (hunk 1 above)
Comment (metamben) [reply enterprise/backend/src/metabase_enterprise/ai_sql_fixer/api.clj:21]: So the query shown to user will never be generated with `pretty`? Or are they _always_ generated with `pretty`?

Comment (ranquild) [reply enterprise/backend/src/metabase_enterprise/ai_sql_fixer/api.clj:21]: always without

Comment (ranquild) [reply enterprise/backend/src/metabase_enterprise/ai_sql_fixer/api.clj:21]: @metamben

Comment (metamben) [reply enterprise/backend/src/metabase_enterprise/ai_sql_fixer/api.clj]: Done.
