### PR TITLE
Fix - Cannot remove questions when combining questions to create multi-series charts

### LINKED ISSUE #12794: Cannot remove questions when combining questions to create multi-series charts
**Describe the bug**

When adding additional questions to an existing question to create a multi-series chart, you cannot remove a question by clicking on the `X` next to the question title above the chart. The sidebar checkboxes, however, function as expected, i.e. users can add and remove questions by checking and unchecking sidebar boxes.

**Logs**
What happens when clicking the `X` next to a question:

```
app-main.bundle.js?a9635a44a9161a01fd75:5 Error getting setting graph.dimensions TypeError: Cannot read property 'filter' of null
    at N (app-main.bundle.js?a9635a44a9161a01fd75:5)
    at he (app-main.bundle.js?a9635a44a9161a01fd75:5)
    at Object.getDefault (app-main.bundle.js?a9635a44a9161a01fd75:5)
    at g (app-main.bundle.js?a9635a44a9161a01fd75:5)
    at g (app-main.bundle.js?a9635a44a9161a01fd75:5)
    at t.getComputedSettings (app-main.bundle.js?a9635a44a9161a01fd75:5)
    at h (app-main.bundle.js?a9635a44a9161a01fd75:5)
    at Function.value (app-main.bundle.js?a9635a44a9161a01fd75:5)
    at app-main.bundle.js?a9635a44a9161a01fd75:5
    at Array.filter (<anonymous>)

And many more cannot read ... of null errors.

```
**To Reproduce**

When editing a question on a dashboard, you can add additional questions by clicking on the add icon.

If you select a question from the sidebar by checking its box, Metabase adds the question to the chart as expected.

However, if you try to remove the question by clicking on the `X` next to the question above the chart, nothing happens (except errors logged to the console).

Unchecking the box next to the question in the sidebar does correctly remove the question, so users at least still have a way to add and remove questions.

**Expected behavior**
Clicking on the `X` next to the question should remove the question.

**Screenshots**

The inert `X`es are next to the currently selected questions above the chart:

cannot_delete_question_by_clicking_on_x

**Severity**
Small bug. Just unexpected UI behavior, and users can still remove questions via the checkboxes in the sidebar.

The sluggishness of the sidebar is a bigger usability issue.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.181-108.257.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "mysql",
      "druid",
      "postgres",
      "bigquery",
      "redshift",
      "mongo",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-06-26",
      "tag": "v0.36.0-snapshot",
      "branch": "master",
      "hash": "bc9e3db"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #12794

### Description

The issue has been introduced in #30321. That PR also left some unused code in `AddSeriesModal`.

- There were 2 problems that caused the bug:
    - reference to `this` was getting lost
    - `handleRemoveSeries` function interface was different than expected
        -  should `AddSeriesModal` be implemented in TS this would not have happened
- This PR also refactors `AddSeriesModal` to TS
    - this uncovered wrong parameter name being used in 1 place (`clear` instead of `clearCache`)
    - there was also some unused code in this component - I cleaned it all up
- This PR also hides the "x" button to to remove the first series in legend
    - this never worked (removing the base dashcard query does not make sense in that modal)

### How to verify

Follow reproduction steps from original report: #12794

#### Before

https://github.com/metabase/metabase/assets/6830683/0b7a8e6d-6196-40aa-9be9-121bdafde814

#### After

https://github.com/metabase/metabase/assets/6830683/0c82ab9f-b043-4c85-aac8-4916417d6ba5

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx [hunk 1]
```diff
@@ -83,12 +109,6 @@ class AddSeriesModal extends Component {
     );
   };
 
-  handleLoadMetadata = async queries => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx:86]: `handleLoadMetadata` & `loadMetadataForQueries` were unused leftovers after #30321.

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx [hunk 2]
```diff
@@ -1,39 +1,59 @@
...
+}
+
+class AddSeriesModal extends Component<Props, State> {
+  constructor(props: Props, context: unknown) {
     super(props, context);
 
     this.state = {
       error: null,
       series: props.dashcard.series || [],
-      isLoadingMetadata: false,
```
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx:22]: `isLoadingMetadata` was unused.

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx [hunk 3]
```diff
@@ -1,39 +1,59 @@
...
+      isLoading: false,
```
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx:50]: I refactored the old `this.state.state` to `isLoading`, since now it only has 2 states (previously there was `"incompatible"` state as well).

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx [hunk 4]
```diff
@@ -65,10 +85,15 @@ class AddSeriesModal extends Component {
     );
   };
 
-  handleRemoveSeries(card) {
-    this.setState({ series: this.state.series.filter(c => c.id !== card.id) });
+  handleRemoveSeries = (_event: MouseEvent, removedIndex: number) => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx:88]: I didn't submit TS refactoring as a separate PR because it happens to uncover the bug that I'm fixing.

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx [hunk 5]
```diff
@@ -108,27 +142,22 @@ class AddSeriesModal extends Component {
           </div>
           <div className="flex-full ml2 mr1 relative">
             <Visualization
+              canRemoveSeries={CAN_REMOVE_SERIES}
               className="spread"
               rawSeries={series}
               showTitle
               isDashboard
               isMultiseries
               onRemoveSeries={this.handleRemoveSeries}
```
Comment (kamilmielnik) [inline frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx:151]: Reference to `this` was being lost here, so I had to bind `this.handleRemoveSeries`.

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx (hunk 4 above)
Comment (kamilmielnik) [reply frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx:95]: @uladzimirdev 

> I don't see where the parameter list is changed based on your code.

I didn't change that part - the `onRemoveSeries` callback is always called with `(event, index)` arguments, see:
- https://github.com/metabase/metabase/blob/1f7e261ec4702b36aa1f815440396187c4b7e931/frontend/src/metabase/visualizations/components/legend/LegendItem.jsx#L48
- https://github.com/metabase/metabase/blob/a1b09db0af6aad40b2bb9494b3928132abbfc785/frontend/src/metabase/visualizations/components/LegendHeader.jsx#L120

The problem was that this `handleRemoveSeries` handler of aforementioned `onRemoveSeries` callback assumed wrong interface.

**Comment by WiNloSt** [comment]
@kamilmielnik Have you confirmed with product regarding this?
> - This PR also hides the "x" button to to remove the first series in legend
>      - this never worked (removing the base dashcard query does not make sense in that modal)

**Comment by kamilmielnik** [comment]
> @kamilmielnik Have you confirmed with product regarding this?

@WiNloSt asked in Slack, awaiting answer: https://metaboat.slack.com/archives/C057T1QTB3L/p1691488910028279
I won't merge it without confirmation. Feel free to review in the meantime :)

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx [hunk 6]
```diff
@@ -46,15 +66,15 @@ class AddSeriesModal extends Component {
     }
 
     if (getIn(dashcardData, [dashcard.id, card.id]) === undefined) {
-      this.setState({ state: "loading" });
+      this.setState({ isLoading: true });
       await this.props.fetchCardData(card, dashcard, {
         reload: false,
-        clear: true,
+        clearCache: true,
```
[the remark this answers is not in the document]
Comment (WiNloSt) [reply frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx:79]: `clear: true` was supposed to be changed to `clearCache: true` in https://github.com/metabase/metabase/pull/30981. Good catch!

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx (hunk 4 above)
Comment (WiNloSt) [reply frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx:95]: Gotcha so here's where the bug happened.

**Review by WiNloSt — APPROVED** [review]
Tested and looks good to me. Feel free to merge once you got product confirmation.
