### PR TITLE
Fix zero measure count issue for pivot tables

### LINKED ISSUE #60428: Upgrade from 1.54 to 1.55 : Error sending to channel channel/email,java.lang.ArithmeticException: Divide by zero
### Describe the bug

Error in logs when sending a report by email 
`Error sending to channel channel/email,java.lang.ArithmeticException: Divide by zero`

### To Reproduce

1. Go to my dashboard''
2. Share it to send it by email
3. Click on send
4. In the logs : 

### Expected behavior

_No response_

### Logs

`[a4318b47-c4d3-4fe8-a7e9-a69023fdf8f4] 2025-07-03T09:21:17+02:00 WARN metabase.notification.send Error sending to channel channel/email,java.lang.ArithmeticException: Divide by zero,	at clojure.lang.Numbers.divide(Numbers.java:190),	at clojure.lang.Numbers.divide(Numbers.java:3891),	at metabase.query_processor.pivot.postprocess$build_full_pivot$iter__90058__90062$fn__90063$fn__90064.invoke(postprocess.clj:160),	at metabase.query_processor.pivot.postprocess$build_full_pivot$iter__90058__90062$fn__90063.invoke(postprocess.clj:154),	at clojure.lang.LazySeq.force(LazySeq.java:50),	at clojure.lang.LazySeq.realize(LazySeq.java:89),	at clojure.lang.LazySeq.seq(LazySeq.java:106),	at clojure.lang.RT.seq(RT.java:555),	at clojure.core$seq__5486.invokeStatic(core.clj:139),	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24),	at clojure.core.protocols$fn__8262.invokeStatic(protocols.clj:74),	at clojure.core.protocols$fn__8262.invoke(protocols.clj:74),	at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13),	at clojure.core$reduce.invokeStatic(core.clj:6965),	at clojure.core$into.invokeStatic(core.clj:7038),	at clojure.core$into.invoke(core.clj:7029),	at metabase.util.performance$concat.invokeStatic(performance.clj:149),	at metabase.util.performance$concat.invoke(performance.clj:146),	at metabase.query_processor.pivot.postprocess$build_full_pivot.invokeStatic(postprocess.clj:151)`

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-06-30",
      "tag": "v0.55.6",
      "hash": "e3a390e"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.18 (Ubuntu 14.18-1.pgdg24.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.5"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-Ubuntu-0ubuntu124.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-Ubuntu-0ubuntu124.04",
    "os.name": "Linux",
    "os.version": "6.8.0-62-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
}
```

### Severity

High

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by johnswanson**
I'm not exactly sure how the count of values could end up at 0, but I was able to manually create a card with this configuration via an API request, which then resulted in `java.lang.ArithmeticException: Divide by zero` when sending emails.

Fixes #60428

### CODE REVIEW

File: src/metabase/query_processor/pivot/postprocess.clj [hunk 1]
```diff
@@ -157,7 +157,7 @@
                         cell-values (mapcat (fn [col-idx]
                                               (let [values (get-row-section col-idx row-idx)]
                                                 (map :value values)))
-                                            (range (/ col-count measure-count)))]
+                                            (range (/ col-count (max measure-count 1))))]
```
Comment (edpaget) [inline src/metabase/query_processor/pivot/postprocess.clj:160]: How does this affect the reported pivot results?

Comment (johnswanson) [reply src/metabase/query_processor/pivot/postprocess.clj:160]: i made a table with cars with types and numbers of seats, then made a card. the query is the avg number of seats by car type. then i made it a pivot table. the configuration initially looked like:
```
    "pivot_table.column_split": {
      "rows": [
        "car_type"
      ],
      "columns": [],
      "values": ["avg"]
    },
```
but i modified it via curl to
```
    "pivot_table.column_split": {
      "rows": [
        "car_type"
      ],
      "columns": [],
      "values": []
    },
```

now - as chatgpt puts it, this is a weird configuration that leads to ambiguous results:

```
Depending on the tool:
	•	Some tools may default to a count if values is empty (i.e., treat it as ["count"] implicitly).
	•	Others may produce an error or just return a list of unique SEATS values with no associated value column.
```

and it's totally right :sweat_smile:  before this change, we used to do (1) and (2), with this change we'll do options (1) and (3) :joy: basically, it's as if you did a `SELECT FROM cars GROUP BY car_type` and we're trying to guess what columns you're actually asking for.

if you download the CSV (with my change) the result looks like this:
```
Car Type
Sedan
SUV
Truck
Grand totals
```
where if you view the actual card it seems to default to just showing you the actual query:
```
+-----------+------------------+
| Car Type  | Average of Seats |
+-----------+------------------+
| Sedan     | 5                |
| SUV       | 6                |
| Truck     | 4                |
+-----------+------------------+
| Grand total | 5.2            |
```
i don't think either one is perfect, and ideally we'd be consistent, but i think fixing the div-by-zero is an improvement over the status quo while we figure out what behavior we actually want here.

**Review by edpaget — APPROVED** [review]
