### PR TITLE
Make cumulative aggregations work with nils

### LINKED ISSUE #12585: Query fails on "Error reducing result rows" #2
**Describe the bug**
Query fails under special conditions. Similar to #12251, but for `null` (I think)

**Logs**
<details>

```
05-25 23:01:27 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at (t/zoned-date-time "2020-05-25T23:01:26.613595+02:00[Europe/Copenhagen]"),
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error reducing result rows",
   :stacktrace
   ["--> query_processor.context.default$default_reducef$fn__37866.invoke(default.clj:61)"
    "query_processor.context.default$default_reducef.invokeStatic(default.clj:58)"
    "query_processor.context.default$default_reducef.invoke(default.clj:49)"
    "query_processor.context$reducef.invokeStatic(context.clj:69)"
    "query_processor.context$reducef.invoke(context.clj:62)"
    "query_processor.context.default$default_runf$respond_STAR___37870.invoke(default.clj:70)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:392)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)"
    "driver.sql_jdbc$fn__72711.invokeStatic(sql_jdbc.clj:50)"
    "driver.sql_jdbc$fn__72711.invoke(sql_jdbc.clj:48)"
    "driver.h2$fn__71677.invokeStatic(h2.clj:81)"
    "driver.h2$fn__71677.invoke(h2.clj:78)"
    "query_processor.context$executef.invokeStatic(context.clj:59)"
    "query_processor.context$executef.invoke(context.clj:48)"
    "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
    "query_processor.context.default$default_runf.invoke(default.clj:67)"
    "query_processor.context$runf.invokeStatic(context.clj:45)"
    "query_processor.context$runf.invoke(context.clj:39)"
    "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
    "query_processor.reducible$pivot.invoke(reducible.clj:31)"
    "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43003.invoke(mbql_to_native.clj:26)"
    "query_processor.middleware.check_features$check_features$fn__42317.invoke(check_features.clj:42)"
    "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43168.invoke(optimize_datetime_filters.clj:133)"
    "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47065.invoke(wrap_value_literals.clj:137)"
    "query_processor.middleware.annotate$add_column_info$fn__40946.invoke(annotate.clj:577)"
    "query_processor.middleware.permissions$check_query_permissions$fn__42192.invoke(permissions.clj:64)"
    "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43667.invoke(pre_alias_aggregations.clj:40)"
    "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42390.invoke(cumulative_aggregations.clj:70)"
    "query_processor.middleware.resolve_joins$resolve_joins$fn__44199.invoke(resolve_joins.clj:183)"
    "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39133.invoke(add_implicit_joins.clj:245)"
    "query_processor.middleware.limit$limit$fn__42989.invoke(limit.clj:38)"
    "query_processor.middleware.format_rows$format_rows$fn__42970.invoke(format_rows.clj:81)"
    "query_processor.middleware.desugar$desugar$fn__42456.invoke(desugar.clj:22)"
    "query_processor.middleware.binning$update_binning_strategy$fn__41490.invoke(binning.clj:229)"
    "query_processor.middleware.resolve_fields$resolve_fields$fn__41998.invoke(resolve_fields.clj:24)"
    "query_processor.middleware.add_dimension_projections$add_remapping$fn__38669.invoke(add_dimension_projections.clj:272)"
    "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__38889.invoke(add_implicit_clauses.clj:147)"
    "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39282.invoke(add_source_metadata.clj:105)"
    "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__43864.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
    "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41131.invoke(auto_bucket_datetimes.clj:125)"
    "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42045.invoke(resolve_source_table.clj:46)"
    "query_processor.middleware.parameters$substitute_parameters$fn__43649.invoke(parameters.clj:97)"
    "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42097.invoke(resolve_referenced.clj:80)"
    "query_processor.middleware.expand_macros$expand_macros$fn__42712.invoke(expand_macros.clj:158)"
    "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39313.invoke(add_timezone_info.clj:15)"
    "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__46949.invoke(splice_params_in_response.clj:32)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__43875$fn__43879.invoke(resolve_database_and_driver.clj:33)"
    "driver$do_with_driver.invokeStatic(driver.clj:61)"
    "driver$do_with_driver.invoke(driver.clj:57)"
    "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__43875.invoke(resolve_database_and_driver.clj:27)"
    "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__42918.invoke(fetch_source_query.clj:243)"
    "query_processor.middleware.store$initialize_store$fn__46958$fn__46959.invoke(store.clj:11)"
    "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
    "query_processor.store$do_with_store.invoke(store.clj:40)"
    "query_processor.middleware.store$initialize_store$fn__46958.invoke(store.clj:10)"
    "query_processor.middleware.cache$maybe_return_cached_results$fn__41974.invoke(cache.clj:208)"
    "query_processor.middleware.validate$validate_query$fn__46967.invoke(validate.clj:10)"
    "query_processor.middleware.normalize_query$normalize$fn__43016.invoke(normalize_query.clj:22)"
    "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39151.invoke(add_rows_truncated.clj:36)"
    "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46934.invoke(results_metadata.clj:128)"
    "query_processor.middleware.constraints$add_default_userland_constraints$fn__42333.invoke(constraints.clj:42)"
    "query_processor.middleware.process_userland_query$process_userland_query$fn__43738.invoke(process_userland_query.clj:136)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__42276.invoke(catch_exceptions.clj:174)"
    "query_processor.reducible$async_qp$qp_STAR___37952$thunk__37953.invoke(reducible.clj:101)"
    "query_processor.reducible$async_qp$qp_STAR___37952.invoke(reducible.clj:107)"
    "query_processor.reducible$sync_qp$qp_STAR___37961$fn__37964.invoke(reducible.clj:133)"
    "query_processor.reducible$sync_qp$qp_STAR___37961.invoke(reducible.clj:132)"
    "query_processor$process_userland_query.invokeStatic(query_processor.clj:218)"
    "query_processor$process_userland_query.doInvoke(query_processor.clj:214)"
    "query_processor$fn__47133$process_query_and_save_execution_BANG___47142$fn__47145.invoke(query_processor.clj:233)"
    "query_processor$fn__47133$process_query_and_save_execution_BANG___47142.invoke(query_processor.clj:225)"
    "query_processor$fn__47177$process_query_and_save_with_max_results_constraints_BANG___47186$fn__47189.invoke(query_processor.clj:245)"
    "query_processor$fn__47177$process_query_and_save_with_max_results_constraints_BANG___47186.invoke(query_processor.clj:238)"
    "api.dataset$fn__50475$fn__50478.invoke(dataset.clj:52)"
    "query_processor.streaming$streaming_response_STAR_$fn__33990$fn__33991.invoke(streaming.clj:73)"
    "query_processor.streaming$streaming_response_STAR_$fn__33990.invoke(streaming.clj:72)"
    "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
    "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
    "async.streaming_response$do_f_async$fn__23079.invoke(streaming_response.clj:85)"],
   :error_type :qp,
   :ex-data {:type :qp}}],
 :error_type :qp,
 :json_query
 {:type "query",
  :query {:source-table 11, :aggregation [["cum-sum" ["field-id" 81]]], :breakout [["datetime-field" ["field-id" 86] "month"]]},
  :database 4,
  :parameters [],
  :middleware {:add-default-userland-constraints? true}},
 :native
 {:query
  "SELECT parsedatetime(formatdatetime(\"PUBLIC\".\"ORDERS\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') AS \"CREATED_AT\", sum(\"PUBLIC\".\"ORDERS\".\"DISCOUNT\") AS \"sum\" FROM \"PUBLIC\".\"ORDERS\" GROUP BY parsedatetime(formatdatetime(\"PUBLIC\".\"ORDERS\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') ORDER BY parsedatetime(formatdatetime(\"PUBLIC\".\"ORDERS\".\"CREATED_AT\", 'yyyyMM'), 'yyyyMM') ASC",
  :params nil},
 :status :failed,
 :class java.lang.NullPointerException,
 :stacktrace [nil],
 :context :ad-hoc,
 :error nil,
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-table 11,
   :aggregation [[:aggregation-options [:sum [:field-id 81]] {:name "sum"}]],
   :breakout [[:datetime-field [:field-id 86] :month]],
   :order-by [[:asc [:datetime-field [:field-id 86] :month]]]},
  :database 4,
  :middleware {:add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash [33, 114, -57, -127, 110, -72, -2, -100, -31, -58, 75, -68, -30, 125, -90, 73, -91, 90, 34, -8, -89, 110, -105, 85, -115, 40, 125, 13, -114, -68, 126, 115]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

05-25 23:01:27 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 634.0 ms (10 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (4 idle, 0 queued) (140 total active threads) Queries in flight: 1 (0 queued)
```

</details>

**To Reproduce**
1. Simple question > Sample Dataset > Orders
2. Summarize "Cumulative sum of Discount" by CreatedAt:Month
3. Query fails with error `Error reducing result rows`

**Information about your Metabase Installation:**
Metabase 0.35.3 and `master`

**Additional context**
Giving P2, since it doesn't seem as common as the first issue

### PR DESCRIPTION
**Pull request by sbelak**
Correctly handles nils when doing cumulative aggregations. Fixes #12585

### CODE REVIEW

File: src/metabase/query_processor/middleware/cumulative_aggregations.clj [hunk 1]
```diff
@@ -24,6 +24,12 @@
     [:cum-count field] [:count field]
     [:cum-sum field]   [:sum field]))
 
+(defn- maybe-add
```
Comment (camsaul) [inline src/metabase/query_processor/middleware/cumulative_aggregations.clj:27]: You could just do `(fnil + 0 0)`

**Review by camsaul — APPROVED** [review]
Cool WFM

File: src/metabase/query_processor/middleware/cumulative_aggregations.clj (hunk 1 above)
Comment (sbelak) [reply src/metabase/query_processor/middleware/cumulative_aggregations.clj]: I always forget fnil works for >1 arg. Thanks. Much nicer solution.
