### PR TITLE
fix(sdk): Standardize SDK components errors with different ID formats

### LINKED ISSUE #49581: SDK components madness with different entity ID formats
### Describe the bug

All 5 SDK questions and dashboards components behave vastly differently with different entity ID formats.

|                                             | InteractiveQuestion      | StaticQuestion                     | InteractiveDashboard | StaticDashboard    | EditableDashboard  |
|---------------------------------------------|--------------------------|------------------------------------|----------------------|--------------------|--------------------|
| **Entity ID**                               |                          |                                    |                      |                    |                    |
| Correct ID                                  | -                        | -                                  | -                    | -                  | -                  |
| 1 too many character/1 too little character | Error Question not found | Error API endpoint does not exist. | Loading spinner      | Loading spinner    | Loading spinner    |
| 21 characters but wrong ID                  | Error Question not found | Loading spinner                    | Error ID not found   | Error ID not found | Error ID not found |
| **Number ID (number and string)**           |                          |                                    |                      |                    |                    |
| Correct ID                                  | -                        | -                                  | -                    | -                  | -                  |
| Wrong ID                                    | Error Question not found | Error Not found.                   | Loading spinner      | Loading spinner    | Loading spinner    |

For example
Image

### To Reproduce

1. Use the SDK, and embed either a dashboard or a question using the above-mentioned components with various ID formats
2. Observe the results.

### <a id='expected-behavior'></a>Expected behavior

The error state should be consistent, for example.

|                                             | InteractiveQuestion      | StaticQuestion           | InteractiveDashboard      | StaticDashboard           | EditableDashboard         |
|---------------------------------------------|--------------------------|--------------------------|---------------------------|---------------------------|---------------------------|
| **Entity ID**                               |                          |                          |                           |                           |                           |
| Correct ID                                  | -                        | -                        | -                         | -                         | -                         |
| 1 too many character/1 too little character | Error Question not found | Error Question not found | Error Dashboard not found | Error Dashboard not found | Error Dashboard not found |
| 21 characters but wrong ID                  | Error Question not found | Error Question not found | Error Dashboard not found | Error Dashboard not found | Error Dashboard not found |
| **Number ID (number and string)**           |                          |                          |                           |                           |                           |
| Correct ID                                  | -                        | -                        | -                         | -                         | -                         |
| Wrong ID                                    | Error Question not found | Error Question not found | Error Dashboard not found | Error Dashboard not found | Error Dashboard not found |

### Logs

_No response_

### Information about your Metabase installation

-

### Severity

maybe high? This makes the SDK looks highly unpolished.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/49581

[Error component design (Figma)](https://www.figma.com/design/W1TfzdrR8ldzp4vdjP1z36/SDK-Embedding%3A-admin-settings-%2B-embed-flow?node-id=11613-23031&t=z4vjXKUradcAyyAp-0)

```[tasklist]
### Todo
- [x] Extract color in the `Code` component that is for displaying errored ID to `colors.module.css`
- [x] Clean up storybook (if we want to keep the ID arguments) or just revert them.
```

### Description

Make all question/dashboard public components loading/error state consistent.

The design is subject to change.

I haven't thought much how to deal with stories, I think each story's control has value. Please let me know if you have any idea how to keep those stories, or maybe we don't need them after the development since we already have Cypress tests for them now. Thought?

### How to verify

Go to each story below and follow the same instructions.
- InteractiveQuestion.stories.tsx
- StaticQuestion.stories.tsx
- InteractiveDashboard.stories.tsx
- StaticDashboard.stories.tsx
- EditableDashboard.stories.tsx

To test each story:
1. Open the storybook's Default story.
2. Change each question/dashboard ID to each option in the addon section
    image
3. The result should match the expected behavior table in #49581

### Demo
image

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: e2e/support/helpers/component-testing-sdk/component-embedding-sdk-interactive-question-helpers.tsx
Comment (WiNloSt) [inline e2e/support/helpers/component-testing-sdk/component-embedding-sdk-interactive-question-helpers.tsx:1]: I rename this to be just question helpers, so I could put static question helpers in there.

File: e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+  cy.intercept("GET", "/api/card/*").as("getCard");
+  cy.intercept("POST", "/api/card/*/query").as("cardQuery");
+
+  cy.get<number>("@questionId").then(questionId => {
+    mountSdkContent(
+      <InteractiveQuestion questionId={questionId} {...extraProps} />,
+    );
+  });
+
+  if (shouldAssertCardQuery) {
```
Comment (WiNloSt) [inline e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx:26]: This is added, previously we only assert questions that will load, but now we will want to test questions that would fail to load as well.

File: e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+    cy.wait("@getCard").then(({ response }) => {
+      expect(response?.statusCode).to.equal(200);
+    });
+  }
+}
+
+export function mountStaticQuestion(
```
Comment (WiNloSt) [inline e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx:33]: this basically copy the function above, but render `StaticQuestion` instead.

File: e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx [hunk 3]
```diff
@@ -12,12 +12,12 @@ describeEE("scenarios > embedding-sdk > editable-dashboard", () => {
...
-      {
-        name: "Embedding SDK Test Dashboard",
-      },
-      { wrapId: true },
-    );
+    cy.createDashboard({
+      name: "Embedding SDK Test Dashboard",
+    }).then(({ body: dashboard }) => {
+      cy.wrap(dashboard.id).as("dashboardId");
+      cy.wrap(dashboard.entity_id).as("dashboardEntityId");
```
Comment (WiNloSt) [inline e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx:19]: All existing test setups are changed so that we manually set aliases, so I could also set the entity ID alias which I'll need to use for testing entity IDs

File: e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx [hunk 4]
```diff
@@ -45,4 +45,65 @@ describeEE("scenarios > embedding-sdk > editable-dashboard", () => {
     cy.findByRole("tab", { name: "Overview" }).should("not.exist");
     cy.findByRole("tab", { name: "History" }).should("not.exist");
   });
+
+  describe("loading behavior for both entity IDs and number IDs (metabase#49581)", () => {
```
Comment (WiNloSt) [inline e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx:49]: All component tests use the same structure.

2 success cases for entity and number ID, and 3 failure cases (2 for entity ID, 1 for number).

File: e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx [hunk 5]
```diff
@@ -20,7 +20,7 @@ describeEE("scenarios > embedding-sdk > interactive-dashboard", () => {
   beforeEach(() => {
     signInAsAdminAndEnableEmbeddingSdk();
 
-    const textCard = getTextCardDetails({ col: 16, text: "Text text card" });
+    const textCard = getTextCardDetails({ col: 16, text: "Test text card" });
```
Comment (WiNloSt) [inline e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx:23]: I believe this is a typo, since there's a counterpart `Test question card` in StaticDashboard test suite.

File: e2e/test-component/scenarios/embedding-sdk/static-question.cy.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,96 @@
+import { SAMPLE_DATABASE } from "e2e/support/cypress_sample_database";
```
Comment (WiNloSt) [inline e2e/test-component/scenarios/embedding-sdk/static-question.cy.spec.tsx:1]: copy the base code from `interactive-question.cy.spec.tsx`, and leave 1 success render case + 5 new cases for loading states.

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Editor.tsx [hunk 7]
```diff
@@ -22,7 +22,7 @@ export const Editor = ({ onApply = () => {} }: EditorProps) => {
     question,
     originalQuestion,
     updateQuestion,
-    runQuestion,
+    queryQuestion,
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Editor.tsx:25]: you'll see where this is renamed later on.

Bascially, I want to make it clear which function does what. There's a `queryQuestion` and `loadAndQueryQuestion`.

The first one only query existing question, but the later load a question first then query it.

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx [hunk 8]
```diff
@@ -72,7 +76,7 @@ export const InteractiveQuestionProvider = ({
       await onBeforeSave?.(sdkQuestion, saveContext);
       await handleSaveQuestion(question);
       onSave?.(sdkQuestion, saveContext);
-      await loadQuestion();
+      await loadAndQueryQuestion();
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx:79]: This is just a renaming to make it clear what this does. Previously it wasn't clear if we only load a question or also make a query, but now it's super duper clear.

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx [hunk 9]
```diff
@@ -145,11 +150,12 @@ export const InteractiveQuestionProvider = ({
     modelsFilterList: mapEntityTypeFilterToDataPickerModels(entityTypeFilter),
     isSaveEnabled,
     saveToCollectionId,
+    isCardIdError,
   };
 
   useEffect(() => {
-    loadQuestion();
-  }, [loadQuestion]);
+    loadAndQueryQuestion();
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx:157]: nothing changes, it's just a renaming to make it more clear what's being executed here.

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx [hunk 10]
```diff
@@ -49,20 +52,35 @@ export const InteractiveQuestionResult = ({
...
+    isCardIdError,
   } = useInteractiveQuestionContext();
 
   const [isSaveModalOpen, { open: openSaveModal, close: closeSaveModal }] =
     useDisclosure(false);
 
   // When visualizing a question for the first time, there is no query result yet.
-  const isQueryResultLoading = question && !queryResults;
+  const isQueryResultLoading =
+    question && shouldRunCardQuery(question) && !queryResults;
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx:63]: When we fail to resolve an entity ID, there won't be any question loaded, so we need to use the same logic to check that. But `question` will be populated, from my testing this is needed so `CreateQuestion` still works, it works by populating an empty question.

https://github.com/metabase/metabase/blob/c3b6176b8ecf05cfe3e938811863a8cf3f040fdb/enterprise/frontend/src/embedding-sdk/lib/interactive-question/run-question-query.ts#L32-L38

This code is basically the same, but the condition has been moved into this new function.

If we don't add this condition, the component will be stuck in the loading state.

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx [hunk 11]
```diff
@@ -49,20 +52,35 @@ export const InteractiveQuestionResult = ({
...
 
   if (isQuestionLoading || isQueryResultLoading) {
     return <SdkLoader />;
   }
 
-  if (!question) {
-    return <SdkError message={t`Question not found`} />;
+  // `isCardError: true` when the entity ID couldn't be resolved
+  if (!question || isCardIdError) {
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx:70]: as mentioned earlier, when we fail to resolve an entity ID, we will already have an empty `question`, so we need to check if the entity ID resolving failed (`isCardIdError`).

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx [hunk 12]
```diff
@@ -49,20 +52,35 @@ export const InteractiveQuestionResult = ({
...
+    return (
+      <SdkError
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx:72]: There's no design for this component, so the design could be changed, I use `Code` directly from Mantine, but if we're really going to use it I will add it to `metabase/ui`

File: enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx [hunk 13]
```diff
@@ -15,7 +15,7 @@ import QuestionEditorS from "./QuestionEditor.module.css";
 const QuestionEditorInner = () => {
   const {
     queryResults,
-    runQuestion,
+    queryQuestion,
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx:18]: just a renaming

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx [hunk 14]
```diff
@@ -127,19 +130,41 @@ const ConnectedDashboardInner = ({
...
->(({ dashboardId: initId, ...rest }) => {
-  const { id: dashboardId, isLoading } = useValidatedEntityId({
+>(({ dashboardId: initialDashboardId, ...rest }) => {
+  const { id: resolvedDashboardId, isLoading } = useValidatedEntityId({
     type: "dashboard",
-    id: initId,
+    id: initialDashboardId,
   });
 
+  const errorPage = useSdkSelector(getErrorPage);
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx:139]: there's already this data in the store, anytime we try to load a dashboard with the wrong ID, this property will be populated.

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx [hunk 15]
```diff
@@ -127,19 +130,41 @@ const ConnectedDashboardInner = ({
...
+  const dispatch = useSdkDispatch();
+  useEffect(() => {
+    if (resolvedDashboardId) {
+      dispatch(setErrorPage(null));
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx:143]: since we use `errorPage` from above we need to clear it if client change the ID to the resolved ones.

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.stories.tsx [hunk 16]
```diff
@@ -7,7 +7,13 @@ import {
   type EditableDashboardProps,
 } from "./EditableDashboard";
 
-const DASHBOARD_ID = (window as any).DASHBOARD_ID || 1;
+const ENTITY_ID = "xBLdW9FsgRuB2HGhWiBa_";
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.stories.tsx:10]: these are the arguments I used when testing and fixing this bug. Maybe we won't need it anymore, thought? The same pattern is applied to all other component test files.

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx [hunk 17]
```diff
@@ -131,20 +136,49 @@ const InteractiveDashboardInner = ({
 };
 
 export const InteractiveDashboard = renderOnlyInSdkProvider(
-  ({ dashboardId, ...rest }: InteractiveDashboardProps) => {
-    const { id, isLoading } = useValidatedEntityId({
+  ({ dashboardId: initialDashboardId, ...rest }: InteractiveDashboardProps) => {
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx:139]: The change is almost exactly the same as the `ConnectedDashboard` one.

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx [hunk 18]
```diff
@@ -131,20 +136,49 @@ const InteractiveDashboardInner = ({
...
+      if (resolvedDashboardId) {
+        dispatch(setErrorPage(null));
+      }
+    }, [dispatch, resolvedDashboardId]);
+
+    const { style, className } = rest;
     if (isLoading) {
-      return <SdkLoader />;
+      return (
+        <StyledPublicComponentWrapper className={className} style={style}>
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx:156]: Fix the issue where the loading state isn't properly themed. This was outside the scope, but I added it for completeness.

File: enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx [hunk 19]
```diff
@@ -88,17 +94,41 @@ export const StaticDashboardInner = ({
 };
 
 const StaticDashboard = withPublicComponentWrapper<StaticDashboardProps>(
-  ({ dashboardId, ...rest }) => {
-    const { isLoading, id } = useValidatedEntityId({
+  ({ dashboardId: initialDashboardId, ...rest }) => {
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx:97]: basically, all dashboard changes are almost the same.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 20]
```diff
@@ -3,11 +3,11 @@ import { useAsyncFn, useUnmount } from "react-use";
 
 import type { ParameterValues } from "embedding-sdk/components/private/InteractiveQuestion/context";
 import {
-  runQuestionOnLoadSdk,
+  loadQuestionSdk,
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:6]: this file is for interactive question components, not static question component.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 21]
```diff
@@ -22,6 +22,9 @@ type LoadQuestionResult = Promise<
 >;
 
 export interface LoadQuestionHookResult {
+  // The ID provided to the question component.
+  originalId?: number | string;
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:26]: This is used to display the ID that cause the error in the error message.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 22]
```diff
@@ -30,9 +33,9 @@ export interface LoadQuestionHookResult {
   isQuestionLoading: boolean;
   isQueryRunning: boolean;
 
-  runQuestion(): Promise<void>;
+  queryQuestion(): Promise<void>;
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:36]: these 2 properties are only renamed, with no functionalities change whatsoever.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 23]
```diff
@@ -58,7 +61,7 @@ export function useLoadQuestion({
 
   // Keep track of the latest question and query results.
   // They can be updated from the below actions.
-  const [questionState, setQuestionState] = useReducer(questionReducer, {});
+  const [questionState, mergeQuestionState] = useReducer(questionReducer, {});
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:64]: This is also a rename, just to make it clearer. Normally, I'd expect `setSomething` to override the whole thing. Let me know if you think otherwise, I can revert this if it makes more sense for you guys.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 24]
```diff
@@ -79,23 +82,30 @@ export function useLoadQuestion({
   // Avoid re-running the query if the parameters haven't changed.
   const sqlParameterKey = getParameterDependencyKey(initialSqlParameters);
 
-  const [loadQuestionState, loadQuestion] = useAsyncFn(async () => {
-    const state = await dispatch(
-      runQuestionOnLoadSdk({
+  const [loadQuestionState, loadAndQueryQuestion] = useAsyncFn(async () => {
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:85]: This is only a rename, with no base functionalities change. But there's a change in the function itself, I'll explain more later.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 25]
```diff
@@ -79,23 +82,30 @@ export function useLoadQuestion({
...
         options,
         deserializedCard,
         cardId,
-        cancelDeferred: deferred(),
         initialSqlParameters,
       }),
     );
 
-    setQuestionState(state);
+    mergeQuestionState(questionState);
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:95]: The problem with the previous version of the code is that we won't know when the query is running i.e. we couldn't rely on `isQueryResultsRunning` since the state will change from not loading question to everything is loaded at once.

This change breaks the chain and update the intermediate state after we've got the first question loaded. This needed to properly render loading and error states.

tl;dr This only changes the intermediate state, but the end states are essentially the same.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 26]
```diff
@@ -79,23 +82,30 @@ export function useLoadQuestion({
...
+    });
+
+    mergeQuestionState(results);
 
-    return state;
+    return { ...results, originalQuestion };
   }, [dispatch, options, deserializedCard, cardId, sqlParameterKey]);
 
-  const [runQuestionState, runQuestion] = useAsyncFn(async () => {
+  const [runQuestionState, queryQuestion] = useAsyncFn(async () => {
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:108]: This is also just a renaming.

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/index.ts [hunk 27]
```diff
@@ -1,3 +1,4 @@
 export { updateQuestionSdk } from "./update-question";
-export { runQuestionOnLoadSdk } from "./run-question-on-load";
+export { loadQuestionSdk } from "./load-question";
 export { runQuestionOnNavigateSdk } from "./run-question-on-navigate";
+export { runQuestionQuerySdk, shouldRunCardQuery } from "./run-question-query";
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/lib/interactive-question/index.ts:4]: we missed exporting from `qun-question-query`.

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/load-question.ts [hunk 28]
```diff
@@ -57,11 +51,5 @@ export const runQuestionOnLoadSdk =
...
     }
 
-    const result = await runQuestionQuerySdk({
-      question,
-      originalQuestion,
-      cancelDeferred,
-    });
-
-    return { ...result, originalQuestion };
+    return { question, originalQuestion };
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/lib/interactive-question/load-question.ts:54]: I only moved the run query part out of this function so I could update the state with the loaded question first, before the query is running. This function is only used in one place, so it's safe to make this change.

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/run-question-query.ts [hunk 29]
```diff
@@ -32,7 +29,7 @@ export async function runQuestionQuerySdk(
 
   let queryResults;
 
-  if (question.canRun() && (question.isSaved() || !isNative)) {
+  if (shouldRunCardQuery(question)) {
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/lib/interactive-question/run-question-query.ts:32]: The code acts the same, I just moved the logic into a seprate function.

File: frontend/src/metabase/core/components/Alert/Alert.tsx [hunk 30]
```diff
@@ -22,7 +22,12 @@ const Alert = ({
   className,
 }: AlertProps) => {
   return (
-    <AlertRoot hasBorder={hasBorder} className={className} variant={variant}>
+    <AlertRoot
+      hasBorder={hasBorder}
+      className={className}
+      variant={variant}
+      role="alert"
```
Comment (WiNloSt) [inline frontend/src/metabase/core/components/Alert/Alert.tsx:29]: based on Mantine's `Alert` it also has the role `alert`, this is so that I could use query `*ByRole("alert")` in the tests.

File: frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts [hunk 31]
```diff
@@ -54,7 +54,7 @@ export const useValidatedEntityId = <
   );
 
   return useMemo(() => {
-    if (!isEntityId) {
+    if (isNumber(id)) {
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts:57]: some strings are also not an EntityId and we don't want to return yet, we should only return when the ID is number because there's nothing to resolve.

File: frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts [hunk 32]
```diff
@@ -64,11 +64,19 @@ export const useValidatedEntityId = <
     }
 
     if (isLoading) {
-      return { id: null, isLoading: true, isError: false } as const;
+      return {
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts:67]: just format change

File: frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts [hunk 33]
```diff
@@ -64,11 +64,19 @@ export const useValidatedEntityId = <
...
+        id: null,
+        isLoading: true,
+        isError: false,
+      } as const;
     }
 
-    if (isError) {
-      return { id: null, isLoading: false, isError: true } as const;
+    if (!isEntityId || isError) {
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts:74]: if it's not an entity ID here, there won't be `isError` since we will not call the endpoint to resolve an entity ID in the first place, so we need this extra condition.

File: e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx [hunk 34]
```diff
@@ -45,4 +45,65 @@ describeEE("scenarios > embedding-sdk > editable-dashboard", () => {
...
+        getSdkRoot().within(() => {
+          cy.findByDisplayValue("Embedding SDK Test Dashboard").should(
+            "be.visible",
+          );
+          cy.findByText("This dashboard is looking empty.").should(
+            "be.visible",
+          );
+        });
+      });
+    });
```
Comment (heypoom) [inline e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx:91]: I suggest using `it.each` to make it easier to identify which tests caused the issue when they fail.

```suggestion
  it.each(successTestCases)(
    'should load dashboard content for $name',
    ({ name, dashboardIdAlias }) => {
      cy.get(dashboardIdAlias).then(dashboardId => {
        mountSdkContent(<EditableDashboard dashboardId={dashboardId} />);
      });

      getSdkRoot().within(() => {
        cy.findByDisplayValue("Embedding SDK Test Dashboard").should("be.visible");
        cy.findByText("This dashboard is looking empty.").should("be.visible");
      });
    }
  );
```

File: e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx [hunk 35]
```diff
@@ -45,4 +45,65 @@ describeEE("scenarios > embedding-sdk > editable-dashboard", () => {
...
+
+    failureTestCases.forEach(({ name, dashboardId }) => {
+      it(`should show an error message for ${name}`, () => {
```
Comment (heypoom) [inline e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx:94]: We can also use `it.each` here

File: e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx (hunk 1 above)
Comment (heypoom) [reply e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx:26]: I wonder if it makes sense to assert a 404 response as well for questions that failed to load?

File: e2e/test-component/scenarios/embedding-sdk/static-dashboard.cy.spec.tsx [hunk 36]
```diff
@@ -79,4 +79,63 @@ describeEE("scenarios > embedding-sdk > static-dashboard", () => {
...
+      {
+        name: "wrong number ID",
+        dashboardId: 9999,
+      },
+    ];
+
+    successTestCases.forEach(({ name, dashboardIdAlias }) => {
+      it(`should load dashboard content for ${name}`, () => {
+        cy.get(dashboardIdAlias).then(dashboardId => {
+          mountSdkContent(<StaticDashboard dashboardId={dashboardId} />);
```
Comment (heypoom) [inline e2e/test-component/scenarios/embedding-sdk/static-dashboard.cy.spec.tsx:113]: I wonder if we can share the same test suite for static and interactive dashboard tests (since the only difference is the mounting `StaticDashboard` and `InteractiveDashboard` component), or at least share the test cases.

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx [hunk 37]
```diff
@@ -49,20 +52,35 @@ export const InteractiveQuestionResult = ({
...
+        message={jt`Question ${(
+          <Code
+            bg="var(--mb-base-color-ocean-20)"
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx:75]: Should we add a semantic variable for this?

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx [hunk 38]
```diff
@@ -127,19 +130,41 @@ const ConnectedDashboardInner = ({
 
 export const ConnectedDashboard = connector<
   ComponentType<ConnectedDashboardProps & ReduxProps>
->(({ dashboardId: initId, ...rest }) => {
-  const { id: dashboardId, isLoading } = useValidatedEntityId({
+>(({ dashboardId: initialDashboardId, ...rest }) => {
+  const { id: resolvedDashboardId, isLoading } = useValidatedEntityId({
     type: "dashboard",
-    id: initId,
+    id: initialDashboardId,
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx:136]: nit: can we update other instances of `initId` to `initialId` in other files to make it consistent?

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx [hunk 39]
```diff
@@ -131,20 +136,49 @@ const InteractiveDashboardInner = ({
...
+      id: initialDashboardId,
     });
 
+    const errorPage = useSdkSelector(getErrorPage);
+    const dispatch = useSdkDispatch();
+    useEffect(() => {
+      if (resolvedDashboardId) {
+        dispatch(setErrorPage(null));
+      }
+    }, [dispatch, resolvedDashboardId]);
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx:151]: I wonder if there could be cases where other errors were showing first, and this `setErrorPage(null)` call would inadvertently clear that error?

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx [hunk 40]
```diff
@@ -131,20 +136,49 @@ const InteractiveDashboardInner = ({
...
+        <StyledPublicComponentWrapper className={className} style={style}>
+          <SdkError
+            message={jt`Dashboard ${(
+              <Code
+                bg="var(--mb-base-color-ocean-20)"
+                c="text-dark"
+                key="question-id"
+              >
+                {initialDashboardId}
+              </Code>
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx:173]: Might be worth creating a component for this (considering we are using it in 3+ places)

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.stories.tsx [hunk 41]
```diff
@@ -5,7 +5,13 @@ import { CommonSdkStoryWrapper } from "embedding-sdk/test/CommonSdkStoryWrapper"
 
 import { InteractiveQuestion } from "./InteractiveQuestion";
 
-const QUESTION_ID = (window as any).QUESTION_ID || 12;
+const NUMBER_ID = 12;
+const ENTITY_ID = "VFCGVYPVtLzCtt4teeoW4";
+const ONE_TOO_MANY_ENTITY_ID = ENTITY_ID + "1";
+const WRONG_ENTITY_ID = ENTITY_ID.slice(0, -1) + "1";
+const WRONG_NUMBER_ID = 99999999;
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.stories.tsx:12]: nit: can we share these option across stories?

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts (hunk 23 above)
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:64]: Agree!

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 42]
```diff
@@ -79,23 +82,30 @@ export function useLoadQuestion({
...
-  const [loadQuestionState, loadQuestion] = useAsyncFn(async () => {
-    const state = await dispatch(
-      runQuestionOnLoadSdk({
+  const [loadQuestionState, loadAndQueryQuestion] = useAsyncFn(async () => {
+    const questionState = await dispatch(
+      loadQuestionSdk({
         options,
         deserializedCard,
         cardId,
-        cancelDeferred: deferred(),
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:88]: I wonder why the deferred for request cancellation `cancelDeferred: deferred()` was removed? afaik this allows other subsequent requests to cancel the existing requests. I noticed the below `runQuestionQuerySdk` also have `cancelDeferred` intact.

File: frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts [hunk 43]
```diff
@@ -83,3 +91,7 @@ export const useValidatedEntityId = <
     return { id: null, isLoading: false, isError: true } as const;
   }, [isEntityId, isLoading, isError, entity_ids, id]);
 };
+
+function isNumber(num: unknown): num is number {
+  return typeof num === "number" && Number.isFinite(num) && !Number.isNaN(num);
+}
```
Comment (heypoom) [inline frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts:97]: PS. `isNumber` also exists in `metabase/lib/types` but it's defined as `typeof value === "number"`

File: frontend/src/metabase/lib/errors/messages.ts [hunk 44]
```diff
@@ -26,3 +26,7 @@ export function getResponseErrorMessage(error: unknown): string | undefined {
 
   return undefined;
 }
+
+export function isResourceNotFoundError(error: any) {
+  return error?.status === 404;
+}
```
Comment (heypoom) [inline frontend/src/metabase/lib/errors/messages.ts:32]: This is fine as I couldn't find an error type with `{status?: number}` in the codebase

**Review by heypoom — APPROVED** [review]
Nice work! Left some notes below

File: e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx (hunk 34 above)
Comment (WiNloSt) [reply e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx:91]: afaik, Cypress don't have it.each like jest does. I searched for that before, and none exists in our Cypress directory.

File: e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx (hunk 1 above)
Comment (WiNloSt) [reply e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx:26]: not in all cases that we'd call the card/dashboard endpoint. If we couldn't resolve the entity ID we'd not call such endpoints, so `wait("@getCard")` or whatever would fail.

This is from removing the if check from one test.
image

File: e2e/test-component/scenarios/embedding-sdk/static-dashboard.cy.spec.tsx (hunk 36 above)
Comment (WiNloSt) [reply e2e/test-component/scenarios/embedding-sdk/static-dashboard.cy.spec.tsx:113]: so what helper do you have in mind?

`mountSdkContent(<StaticDashboard dashboardId={dashboardId} />);` is already pretty light imo. The rest are assertions which shouldn't be extracted as the assertion logic should be in the test suites.

Also, these suite aren't quite the same, only the new set of tests are almost the same (the tests for this PR). These suites (static dashboard, and interactive dashboard) already exist and they have different set of tests.

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx (hunk 37 above)
Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx:75]: Agree, we shouldn't even use semantic colors directly like this. I just slapped something that I think it would make the ID stand out more.

@AlessioLaiso I think we need some design for the error component with ID.

Here's how it looks currently.
image

I've added a todo list for cleaning up in [the description](https://github.com/metabase/metabase/pull/49714#issue-2641539254), thanks for reminding me this 🙏

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx (hunk 38 above)
Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx:136]: you mean like `initialXxxId`? right? Fixed in 7061c613220ce6a202a13f98d5d6990b42832c5a


I leave one place as `originalId` since there's a counterpart `originalQuestion` in the `interactiveQuestionContext`

https://github.com/metabase/metabase/blob/5b15e9b522ef24b8c611e9f0d4fc7193079bc2b8/enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx#L79

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx (hunk 39 above)
Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx:151]: Good point. I don't think we've ever used this error yes anywhere in our SDK, so this should be safe. I was trying to get the info on the dashboard request, if there's a better to do that then I'll take it.

Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx:151]: Seems we're still using the old API (non-RTK query) for this request.

https://github.com/metabase/metabase/blob/7061c613220ce6a202a13f98d5d6990b42832c5a/frontend/src/metabase/services.js#L177

I was trying to use other dashboard state with no success

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx (hunk 40 above)
Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx]: Fixed in 35ecb49a9fe582d2df14aca6890fedf33b52d430

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts (hunk 42 above)
Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:88]: this cancelDeferred was passed to `runQuestionQuerySdk` which was inside `runQuestionOnLoadSdk` (pre-change), since we extract that part out and put it after this `loadQuestionSdk` call (after-change) we don't need this `cancelDeferred` anymore.

File: frontend/src/metabase/lib/errors/messages.ts (hunk 44 above)
Comment (WiNloSt) [reply frontend/src/metabase/lib/errors/messages.ts:32]: 🙏 I don't wanna fix any type right now, I don't remember why I went with `any` but it seems using `GenericErrorResponse | null` which is the type where the argument is passed doesn't pass TypeScript here. So a deliberate `any` is a compromise.

File: e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx (hunk 35 above)
Comment (WiNloSt) [reply e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx:94]: answered here https://github.com/metabase/metabase/pull/49714#discussion_r1909912019

File: e2e/test-component/scenarios/embedding-sdk/static-dashboard.cy.spec.tsx (hunk 36 above)
Comment (heypoom) [reply e2e/test-component/scenarios/embedding-sdk/static-dashboard.cy.spec.tsx:113]: @WiNloSt I was thinking of sharing `failureTestCases` and `successTestCases` across files, but I think in this case keeping the assertions as-is would indeed be better. Ignore my comment then 🙏🏻

**Review by heypoom — APPROVED** [review]
Re-reviewed the changes since my last review, looks great!

**Review by heypoom — APPROVED** [review]
Re-reviewed the changes since my last review, looks great!

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 45]
```diff
@@ -79,23 +82,39 @@ export function useLoadQuestion({
...
         initialSqlParameters,
       }),
-    );
+    ).finally(() => {
+      setIsQuestionLoading(false);
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:101]: Set the loading to false whether this promise is resolved or not. It will be rejected if the the provided ID couldn't be loaded.

This should fix #51969

File: frontend/src/metabase/core/components/Alert/Alert.styled.tsx [hunk 46]
```diff
@@ -14,17 +14,17 @@ interface AlertRootProps {
 const colorsByVariant = {
   border: {
     info: "var(--mb-color-bg-medium)",
-    error: color("error"),
+    error: "var(--mb-color-error)",
```
Comment (WiNloSt) [inline frontend/src/metabase/core/components/Alert/Alert.styled.tsx:17]: Update the error component colors according to [the design.](https://www.figma.com/design/W1TfzdrR8ldzp4vdjP1z36/SDK-Embedding%3A-admin-settings-%2B-embed-flow?node-id=11613-23031&t=z4vjXKUradcAyyAp-0)

**Comment by WiNloSt** [comment]
I [discussed this with the team](https://metaboat.slack.com/archives/C063Q3F1HPF/p1736906844739559) and this should be backported.
