### PR TITLE
Move away from deprecated slack upload endpoints

### LINKED ISSUE #41890: Slack integration uses a deprecated API
### Describe the bug

Slack integration uses a deprecated endpoint to upload files.

https://api.slack.com/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay
> The original web API method for uploading files to Slack, [files.upload](https://api.slack.com/methods/files.upload), is being sunset on March 11, 2025. Beginning May 8, 2024, newly-created apps will be unable to use this API method.
> 
> Apps & integrations should migrate away from files.upload and instead leverage a combination of two APIs: [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) and [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal). The use of these two methods is more reliable, especially when uploading large files.
> 

### To Reproduce

n/a

### Expected behavior

Use the endpoints recommended instead of the deprecated one.

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

P1 - beginning May 8 it won't be possible to set up a new Slack integration

### Additional context

https://github.com/metabase/metabase/blob/dd66a69a264c10fe6cadb1860a45a77a1b5061d6/src/metabase/integrations/slack.clj#L321-L342

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/41890

This PR changes `metabase.integrations.slack/upload-file!` from using one deprecated endpoint to use the new set of three endpoints (why slack, why?). I used the [python slack SDK](https://github.com/seratch/python-slack-sdk/blob/1d0eed1c73a1ee419561d7924f164f271414679d/slack_sdk/web/async_client.py#L3003) as a reference implementation.

I'm doing this in the laziest simplest way possible, making three requests for each file in series. A simple optimization to follow this up would be to make the first two requests for each file in parallel, and then when all those requests complete call `files.completeUploadExternal` only once for all files. Given this was pretty slow and unoptimized already (we could have been executing requests in parallel before) I'm assuming it's not a huge issue for now, and I've left a TODO in the code explaining this possibility.

This needs manual testing because there's a lot of mocking going on in our automated tests. How to test:
1. Create a slack app following the instructions in Admin > Slack
2. you can use the public channel "cals-slack-integration-test-channel" I've created for testing purposes, or create your own
3. Create a dashboard with a graph in it, or use the example dashboard
4. Create a subscription, pick a user or channel, and click "Send to Slack now".

### CODE REVIEW

File: src/metabase/pulse.clj [hunk 1]
```diff
@@ -541,6 +543,8 @@
 (defmethod send-notification! :slack
   [{:keys [channel-id message attachments]}]
   (let [attachments (create-and-upload-slack-attachments! attachments)]
+    ;; Cal 2024-03-04: Without this sleep, attached images don't always appear. I tried with 1000ms and it wasn't enough.
+    (Thread/sleep 2000)
```
Comment (calherries) [inline src/metabase/pulse.clj:547]: Frankly I don't know why this is happening. I can only guess it's an issue with slack's state.

Without this sleep, instead of getting a result like this:
image

I would get this:
image

even though the sent message and attachments were the same in both cases, based on the logs
```
2024-04-29 17:06:54,493 TRACE integrations.slack :: Slack API request: "https://slack.com/api/chat.postMessage" {:form-params {:channel "@cal", :username "MetaBot", :icon_url "http://static.metabase.com/metabot_slack_avatar_whitebg.png", :text nil, :attachments "[{\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\"subdash\",\"emoji\":true}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"Sent by Crowberto Corv\"}]}]},{\"title\":\"Orders, Count\",\"title_link\":\"http://localhost:3001/question/30\",\"fallback\":\"Orders, Count\",\"text\":\"18,760\"},{\"title\":\"Best selling products\",\"title_link\":\"http://localhost:3001/question/23\",\"fallback\":\"Best selling products\",\"image_url\":\"https://files.slack.com/files-pri/T078VCLCR-F071306S06R/image.png\"},{\"blocks\":[{\"type\":\"divider\"},{\"type\":\"context\",\"elements\":[{\"type\":\"mrkdwn\",\"text\":\"<http://localhost:3001/dashboard/2|*Sent from Metabase Test*>\"}]}]}]"}}
```

File: test_resources/slack_upload_file_response.json [hunk 2]
```diff
@@ -1,64 +1,40 @@
...
-        } ]
-      }
-    },
-    "permalink_public" : "https://slack-files.com/T078VLEET-F017C3TSBK6-d9c051e26f"
-  },
-  "warning" : "superfluous_charset",
-  "response_metadata" : {
-    "warnings" : [ "superfluous_charset" ]
-  }
+  "ok": true,
```
Comment (calherries) [inline test_resources/slack_upload_file_response.json:2]: I copied this from a real test and replaced some IDs

File: src/metabase/pulse.clj (hunk 1 above)
Comment (calherries) [reply src/metabase/pulse.clj]: I hit this again with a 2000ms sleep, so I've extended it to 3000ms. 

The issue appears to be caused by a race condition between the message being sent to the subscription's destination, and the actual upload of the file to the files channel. The latter needs to finish first, and the former needs to finish afterwards. The race condition is happening on the slack side, because on our side we're calling 

Here's when the app integration uploaded the image to the files channel, from slacks' point of view:
image

And here's when the message was sent to me, from slack's point of view:
image

The upload request ([files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal)) was completed first, but in slack they appear the other way around.

Comment (calherries) [reply src/metabase/pulse.clj]: Seems like others are running into this issue too. https://github.com/slackapi/python-slack-sdk/issues/1363

We could try polling `[conversations_history](https://api.slack.com/methods/conversations.history)` on the file channel, but that seems pretty invasive and I wonder if we're allowed to do that.

> using conversations_history is one of the recommended approaches to retrieve your message's details such as the timestamp

Comment (calherries) [reply src/metabase/pulse.clj]: Hard to believe slack screwed up this API so bad. They must have been in a rush

File: src/metabase/integrations/slack.clj [hunk 3]
```diff
@@ -319,26 +319,38 @@
...
+        complete-response (try
+                            (complete!)
+                            (catch Throwable e
+                              ;; If file upload fails with a "not_in_channel" error, we join the channel and try again.
+                              ;; This is expected to happen the first time a Slack subscription is sent.
+                              (if (= "not_in_channel" (:error-code (ex-data e)))
+                                (do (join-channel! channel-id)
+                                    (complete!))
+                                (throw e))))]
+    (u/prog1 (get-in complete-response [:files 0 :url_private])
```
Comment (tsmacdonald) [inline src/metabase/integrations/slack.clj:353]: I think this is a lot easier to read with named functions and less complex `let` destructuring. Something like:

```clojure
(defn slack-upload-url
  [filename file]
  (POST "files.getUploadExternal" {:query-params {:filename filename
                                                  :length   (count file)}}))

(defn upload-file-or-throw!
  [file {upload-url :upload_url file-id :file_id}]
  (let [response (http/post upload-url {:multipart [{:name "file"
                                                     :content "file"}]})]
    (if (= (:status response) 200)
      response
      (throw (ex-info "Failed to upload file to Slack:" (select-keys response [:status :body]))))))

(defn complete-upload!*
  [channel-id filename file-id]
  (POST "files.completeUploadExternal"
      {:query-params {:files      (json/generate-string [{:id file-id :title filename}])
                      :channel_id channel-id}}))

(defn complete-upload!
  [channel-id filename file-id]
  (try
    (complete-upload!* channel-id filename file-id)
    (catch Throwable e
      ;; If file upload fails with a [etc]
      (if (= (:error-code (ex-data e)) "not_in_channel")
        (doto channel-id
          (join-channel!)
          (complete-upload!* filename file-id))
        (throw e)))))


(defn upload-file!
  [file filename channel-id]
  (let [external-url      (slack-upload-url filename file)
        _                 (upload-file-or-throw! file external-url)
        complete-response (complete-upload! (maybe-lookup-id channel-id (slack-cached-channels-and-usernames))
                                            filename
                                            (:file_id external-url))
        image-url (get-in complete-response [:files 0 :url_private])]
    (log/debug "Uploaded image" image-url)
    image-url))
```

Comment (tsmacdonald) [reply src/metabase/integrations/slack.clj:353]: I didn't transcribe all the comments / write docstrings / etc (and I should have) but you get the idea

Comment (calherries) [reply src/metabase/integrations/slack.clj:377]: Thanks, this is good stuff. I'll try it

Comment (calherries) [reply src/metabase/integrations/slack.clj]: [f351704](https://github.com/metabase/metabase/pull/41974/commits/f351704195fa0cd4b43be83353921dfb403fc34d)

File: src/metabase/integrations/slack.clj [hunk 4]
```diff
@@ -318,27 +318,83 @@
...
+                               (boolean (some-> response :files first :shares not-empty)))
+        _ (when-not (or
+                     (uploaded-to-channel? complete-response)
+                     (poll {:thunk       complete!
+                            :done?       uploaded-to-channel?
+                            ;; Cal 2024-04-30: this typically takes 1-2 seconds to succeed.
+                            ;; If it takes more than 10 seconds, something else is wrong and we should abort.
+                            :timeout-ms  10000
+                            :interval-ms 500}))
+            (throw (Exception. "Confirming the file was uploaded to a Slack channel timed out.")))]
```
Comment (piranha) [inline src/metabase/integrations/slack.clj:366]: ex-info + filename in there maybe? So you know which file was not uploaded?

File: src/metabase/integrations/slack.clj [hunk 5]
```diff
@@ -318,27 +318,83 @@
...
 
+(defn- poll
+  "Returns true if `(thunk)` returns a result that satisfies the `done?` predicate within the timeout,
+   and false otherwise."
+  [{:keys [thunk done? timeout-ms interval-ms]}]
+  (let [start-time (System/currentTimeMillis)]
+    (loop []
+      (let [response (thunk)]
+        (if (done? response)
+          true
```
Comment (piranha) [inline src/metabase/integrations/slack.clj:329]: I think for this case it's fine, but I'd rather have `response` or `nil` returned here, it seems like a generally more useful abstraction then.

**Review by sansolovyov — APPROVED** [review]
IDK what @tsmacdonald thinks, but LGTM

**Comment by calherries** [comment]
@piranha thanks for your enhancements, I've applied them here [f8a8a8c](https://github.com/metabase/metabase/pull/41974/commits/f8a8a8c9fb91e7d6e3d86d9ab5d6e8ff5a7a2b36)

**Comment by calherries** [comment]
@metabase-bot backport release-x.48.x
