### PR TITLE
Fix params for saved card csv downloading + JSON download widget

### LINKED ISSUE #3682: Provide a JSON download of a saved question
Similar to how we provide a CSV download, we should also allow users to download a JSON file with the results. 

The intention is that this will be used programmatically most of the time, and often in connection with #3680

### LINKED ISSUE #3695: CSV Download for SQL Query Returns Default Value on Variable
### Bugs

If you're filing an issue about a bug please include as much information
as you can including the following.
- Chrome 53.0.2785.143
- OSX 10.10
- Postgres, MySQL
- Metabase version v0.20.2
- Metabase hosting environment: Ubuntu16.04
- Metabase internal database: Postgres 9.5

_Repeatable steps to reproduce the issue_
1. Create new card with SQL query with below sample from database **Sample Dataset**:
screen shot 2016-10-28 at 10 42 50 am
`select * from orders
where user_id={{user_id}}`
Then I set default value of user_id into 2.
2. Save the question, reopen it and change the value of variable (example: change the user_id into 3). Everything went well until this step:
screen shot 2016-10-28 at 10 45 58 am
3. Click download CSV, and when we open the CSV, it contains user_id 2 (default value of variable user_id). It doesn't respect variable value that we choose. Here is the result from CSV download:
screen shot 2016-10-28 at 10 49 16 am

Okay let's try another case not to set the default value like below card:
1. Create card with sql query and a required variable (without default value)
screen shot 2016-10-28 at 10 51 23 am
2. Reopen the card, set the variable value, and click download csv:
screen shot 2016-10-28 at 10 53 17 am
screen shot 2016-10-28 at 10 53 24 am
We cannot download the CSV  with error `'User' is a required param.`

---

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3695
Resolves #3682

screenshot 2016-11-17 17 33 08

Also combines the "large dataset" warning modal with the popover (I'm open to alternative styling):

screenshot 2016-11-17 17 33 19

Also we need to add support for the Mac app. Ideally I think we'd change `window.OSX.saveCSV(JSON.stringify(card.dataset_query));` to something more generic, with a signature like what the new `DownloadButton` component accepts, something like `window.OSX.download(method, url, params)`, so we'd do `window.OSX.download(url, { query: JSON.stringify(card.dataset_query) });`

### CODE REVIEW

File: frontend/src/metabase/components/Button.jsx [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+            className={cx("Button", className, variantClasses)}
+        >
+            <div className="flex layout-centered">
+                { icon && <Icon name={icon} size={14} className="mr1" />}
+                <div>{children}</div>
+            </div>
+        </button>
+    );
+}
+
```
Comment (kdoh) [inline frontend/src/metabase/components/Button.jsx]: We should definitely add some PropTypes here since this will no doubt be a highly reused component.

File: frontend/src/metabase/components/DownloadButton.jsx [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+
+    render() {
+        const { children, url, method, params, ...props } = this.props;
+        return (
+            <form ref={(c) => this._form = c} method={method} action={url}>
+                { Object.entries(params).map(([name, value]) =>
+                    <input key={name} type="hidden" name={name} value={value} />
+                )}
+                <Button
+                    onClick={() => ReactDOM.findDOMNode(this._form).submit()}
```
Comment (kdoh) [inline frontend/src/metabase/components/DownloadButton.jsx]: Is there a way to handle the submission via component state here or is the form required because of the fact that we're downloading a file? If we're not able to use the component state I'd just as soon remove it from up above in the constructor so it's clear the component has no local state. 

(It's too bad you can't use refs with stateless functional components).

File: frontend/src/metabase/components/DownloadButton.jsx [hunk 3]
```diff
@@ -0,0 +1,41 @@
+import React, { Component, PropTypes } from "react";
+import ReactDOM from "react-dom";
+
+import Button from "metabase/components/Button.jsx";
+
+export default class DownloadButton extends Component {
+    constructor(props, context) {
+        super(props, context);
```
Comment (kdoh) [inline frontend/src/metabase/components/DownloadButton.jsx]: There's no need to pass context in here since we're not using context. (I think a ton of our components have this copypasta problem).

File: frontend/src/metabase/query_builder/components/DownloadWidget.jsx [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+import FieldSet from "metabase/components/FieldSet.jsx";
+
+export default class DownloadWidget extends Component {
+    constructor(props, context) {
+        super(props, context);
+        this.state = {};
+    }
+
+    static propTypes = {};
+    static defaultProps = {};
```
Comment (kdoh) [inline frontend/src/metabase/query_builder/components/DownloadWidget.jsx]: If we aren't using `propTypes` or `defaultProps` my personal feeling is we should just omit them.

File: frontend/src/metabase/query_builder/components/DownloadWidget.jsx [hunk 5]
```diff
@@ -0,0 +1,53 @@
+import React, { Component, PropTypes } from "react";
+import ReactDOM from "react-dom";
+
+import PopoverWithTrigger from "metabase/components/PopoverWithTrigger.jsx";
+import Icon from "metabase/components/Icon.jsx";
+import DownloadButton from "metabase/components/DownloadButton.jsx";
+
+import FieldSet from "metabase/components/FieldSet.jsx";
+
+export default class DownloadWidget extends Component {
```
Comment (kdoh) [inline frontend/src/metabase/query_builder/components/DownloadWidget.jsx]: It looks like we aren't needing any of the functions of a full component class here so I wonder if it would make things a bit simpler to just use a stateless functional component here?

File: frontend/src/metabase/components/Button.jsx [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+    "large",
+    "primary",
+    "warning",
+    "cancel",
+    "purple",
+    "borderless"
+];
+
+const Button = ({ className, icon, children, ...props }) => {
+    let variantClasses = BUTTON_VARIANTS.filter(variant => props[variant]).map(variant => "Button--" + variant);
```
Comment (kdoh) [inline frontend/src/metabase/components/Button.jsx]: So is the general idea of the usage here that you'd do something like `<Button large cancel {...props} />` to get a large cancel button? I think overall I like that approach but it does make me really want to have pretty strict proptypes so that usage is a bit more clear. I _think_ the various button classes should all be isolated enough that you won't get weird effects when combining them but we should double check.

**Review by kdoh — COMMENTED** [review]
Left some thoughts, mostly on some boilerplate we could remove and on the usage of the `Button` component.

**Comment by kdoh** [comment]
Left some comments on some boilerplate we can remove and a couple thoughts on the `Button` component. Other than those, the code looks good.

I do think we're going to want a different visual style for the Warning here. The contrast is a bit rough. I'll see if I can come up with something.

File: frontend/src/metabase/components/DownloadButton.jsx (hunk 3 above)
Comment (tlrobinson) [inline frontend/src/metabase/components/DownloadButton.jsx]: Is there a reason to not include `context`?

File: frontend/src/metabase/components/Button.jsx (hunk 6 above)
Comment (tlrobinson) [inline frontend/src/metabase/components/Button.jsx]: Are you suggesting validating combinations of those props? I'm not sure that's necessary, we certainly don't do anything like that for the CSS classes.

I'll add the basic proptypes though.

Comment (kdoh) [inline frontend/src/metabase/components/Button.jsx]: Nah wasn't suggesting that. Was just mentioning how there's the potential for that to happen and since it's being done via prop not an explicit CSS class it might be a bit harder to track down.

File: frontend/src/metabase/components/DownloadButton.jsx (hunk 3 above)
Comment (kdoh) [inline frontend/src/metabase/components/DownloadButton.jsx]: I think the main reason is just legibility. This is totally just personal preference but it feels cleaner to only really reference what you need which is neither in this case.

**Comment by tlrobinson** [comment]
@camsaul do you want to review the clojure and Mac app changes?

**Comment by camsaul** [comment]
Yeah, I'll review them shortly

**Comment by camsaul** [comment]
@tlrobinson looks fine to me. There was one place where it looks like you spaced a map JS-style spacing instead of Clojure-style (noted in comment above) but besides that 👍
