### PR TITLE
fix(sdk): Ensure that questions don't flicker when fetching entity IDs

### LINKED ISSUE #57059: [SDK] using entity id in static questions causes flickering for a couple frames
If we use entity id as the question id in static questions (instead of numerical IDs) e.g. `<StaticQuestion questionId="some-entity-id" />`, we get a different view for a couple of frames (<1s). This results in static questions flickering for a couple of frames.

The root cause is likely because the view is rendered before the Entity ID has finished resolving to numerical IDs.

### Screenshots

In some cases, it shows "To run your code, click on the Run button"

Image

In some cases, it shows "Question not found"

Image

In some cases, it shows "Here's where your results may appear"

Image

### Context

[See the discussion on Slack](https://metaboat.slack.com/archives/C063Q3F1HPF/p1742481081285169)

### LINKED ISSUE #57123: Metabot on SDK could fail to fetch a question, and the loading spinner won't disappear
### Describe the bug

For whatever reason, if the question from Ridirect reaction from agent couldn't be loaded, we should show the error state instead of the inifinite loading spinner.

Image

### To Reproduce

1. setup the embedding metabot collection with some models
1. setup permissions so that the user has view permissions for the collection but not query buider permissions on the database
1. send a prompt, there will be a result, the adhoc question will be built but will fail to execute with a 403
1. we keep showing the spinner although the query failed

### Expected behavior

We should see the error state instead of the spinner.

### Logs

_No response_

### Information about your Metabase installation

```JSON
`metabot-v3-main` @ f8aa29dcdbf96b9f4d02d1b6875f682e2c3ee695
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by oisincoveney**
closes #57059 
closes #57123
I've realized that using the `useValidatedEntityId` hook is causing issues because we are then playing with the fire that is the React lifecycle. Since we load the question through a few dispatch calls mainly through the `loadQuestionSdk` function, I've decided to use an async function based off the RTK call that will allow us to have a more predictable loading setup for questions.

### CODE REVIEW

**Comment by oisincoveney** [comment]
This change is part of the following stack:

- #57073 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/load-question.ts [hunk 1]
```diff
@@ -12,13 +13,17 @@ export const loadQuestionSdk =
...
     deserializedCard,
-    questionId,
+    questionId: initQuestionId,
     initialSqlParameters,
   }: LoadSdkQuestionParams) =>
   async (
     dispatch: Dispatch,
     getState: GetState,
   ): Promise<{ question: Question; originalQuestion?: Question }> => {
+    const { id: questionId } = await dispatch(
```
Comment (oisincoveney) [inline enterprise/frontend/src/embedding-sdk/lib/interactive-question/load-question.ts:23]: @npretto This is the main thing I'm concerned about - the fact that our `Dispatch` type is a bit useless is messing things up here and I'm not particularly sure what to do. I was thinking that I would just need to manually cast it. My issue is that I've already done a bunch of manual casts in the `fetchEntityId` function and it's incredibly annoying to have to do it again here

File: frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts [hunk 2]
```diff
@@ -101,3 +119,42 @@ export const useValidatedEntityId = <
     return { id: null, isLoading: false, isError: true } as const;
   }, [isEntityId, isLoading, isError, entity_ids, id]);
 };
+
```
Comment (oisincoveney) [inline frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts:122]: We're able to use this setup as a function rather than a hook so hopefully it makes the loading logic much more predictable

File: frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts [hunk 3]
```diff
@@ -101,3 +119,42 @@ export const useValidatedEntityId = <
...
+    if (_.isNumber(id)) {
+      return { id, isError: false };
+    }
+
+    const { data, isError } = await (dispatch(
+      entityIdApi.endpoints.translateEntityId.initiate({
+        [type]: [id],
+      }),
+    ) as Promise<{
```
Comment (oisincoveney) [inline frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts:149]: I find this to be incredibly annoying but idk what we can do to change this since we're using the metabase `dispatch` which is badly typed:
```
export type Dispatch<T = any> = (action: T) => unknown | Promise<unknown>;
```

File: frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts [hunk 4]
```diff
@@ -101,3 +119,42 @@ export const useValidatedEntityId = <
...
+  async (
+    dispatch: Dispatch,
+  ): Promise<ValidatedEntityIdReturned<TEntity, TReturnedId>> => {
+    if (!isBaseEntityID(id)) {
+      return { id: null, isError: true };
+    }
+
+    if (_.isNumber(id)) {
+      return { id, isError: false };
+    }
```
Comment (heypoom) [inline frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts:143]: Should we have `isNumber` before `isBaseEntityID`? It looks to me like we fail immediately if it's not a valid entity id, so I think this might break numerical IDs.

**Review by heypoom — APPROVED** [review]

File: frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts (hunk 4 above)
Comment (oisincoveney) [reply frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts:143]: That's exactly what will happen. Great catch!

**Review by WiNloSt — CHANGES_REQUESTED** [review]
The overall approach looks good. But storybook's Interactive question default story fail to render with almost every ID option.
image

#### master
Screenshot 2025-04-23 at 5 02 49 PM

I'd expect to see such error instead of the first image.

File: enterprise/frontend/src/embedding-sdk/lib/interactive-question/load-question.ts (hunk 1 above)
Comment (oisincoveney) [reply enterprise/frontend/src/embedding-sdk/lib/interactive-question/load-question.ts:23]: Let's fix the type in another PR. I don't want to pollute this one.

Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/lib/interactive-question/load-question.ts:23]: That's alright. We can slap ts-ignore, or whatever, to suppress the error for now.

File: frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts [hunk 5]
```diff
@@ -101,3 +119,46 @@ export const useValidatedEntityId = <
     return { id: null, isLoading: false, isError: true } as const;
   }, [isEntityId, isLoading, isError, entity_ids, id]);
 };
+
+export const fetchEntityId =
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts:123]: I just realized we put this redux action inside a `hooks` folder. Which sounds really wrong.

**Review by WiNloSt — APPROVED** [review]
looks good to me.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 6]
```diff
@@ -88,28 +88,38 @@ export function useLoadQuestion({
...
+      return { ...results, originalQuestion };
+    } catch (err) {
+      mergeQuestionState({
+        question: undefined,
+        originalQuestion: undefined,
+        queryResults: undefined,
+      });
+
+      setIsQuestionLoading(false);
+      return {};
```
[the remark this answers is not in the document]
Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:121]: feels free to address this later.
