### PR TITLE
Mongo remove v3 support

### LINKED ISSUE #23422: Drop support for Mongo version < 4 and run all :expressions tests for Mongo
MongoDB 3.x was EOL'ed over a year ago so now it's probably safe to say we don't support MongoDB 3.x anymore. We don't test against it anyway -- we test against 4.0 and 5.0. 

We could replace the `driver/database-supports?` method for `[:mongo :expressions]` with a `drvier/supports?` method in `metabase.driver.mongo` and then we could get rid of the special case code in `metabase.query-processor-test.filter-test/timezone-arithmetic-drivers`. This would also provide the added benefit of having other `:expressions` code run against Mongo without us needing special case code here, so we might catch some more bugs.

**Links**
- [PR](https://github.com/metabase/metabase/pull/23292) which led to the discovery of this issue with some more discussion

### LINKED ISSUE #24315: Sorting by Custom Columns on MongoDB does not work
**Describe the bug**
image
image

Database used: MongoDB

Metabase v0.43.4.

**Severity**
Somewhat problematic - We were planning to use this combined with alerts to get us a sense of the top values for this query. If we can't resolve this we'll have to figure out some other way.

### LINKED ISSUE #25472: Replace function in Mongo doesn't have the right syntax
**Describe the bug**
When creating a custom column adn using replace as a function, it translates to something like this:

{"$replaceAll":["$field"," ",""]}}

After running it, Mongo returns the following error:
Command failed with error 51751 (Location51751): 'Invalid $project :: caused by :: $replaceAll requires an object as an argument, found: array'

[MongoDB documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceAll/)

**To Reproduce**
Create a question from a mongo database and try to create a replace custom column

**Expected behavior**
The right syntax should be:
{"$replaceAll":**{**"$field"," ",""**}**}}

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome/105.0.0.0
- Your operating system: Mac OS 12.6
- Your databases: MongoDB
- Metabase version: v0.42.3

**Severity**
We cannot use this custom column formula and it's stopping some key questions :(

### LINKED ISSUE #27270: The MongoDB driver uses zero-based indexing for `substring`
**Describe the bug**
The MongoDB driver uses `$substrCP` to get a substring of a string. This is using zero-based indexing, but all other drivers use one-based indexing.

This bug surfaced when we were implementing and testing other things in the MongoDB driver.

Will be fixed by #27176.

### LINKED ISSUE #27275: MongoDB does not support expressions inside aggregations
As part of https://github.com/metabase/metabase/issues/23422 we discovered that `metabase.query-processor-test.sum-where-test/sum-where-inside-expressions-test` was failing.

An example mbql query which will ignore the `:+` and `:/` 

```clojure
{:aggregation 
 [[:+
   [:/
    [:sum-where
     [:field (mt/id :venues :price) nil]
     [:< [:field (mt/id :venues :price) nil] 4]]
    2]
   1]]}
```

### PR DESCRIPTION
**Pull request by snoe**
Fixes #25472
Fixes #23422
Fixes #27270
Fixes #27275
Fixes #24315

It turns out that a number of tests were not running for mongo `:expressions`. This issue, and related changes to `dbms_version` caused us to find a number of short-comings in our mongo implementation, many of them were fixed as part of this PR.

- [x] Bump CI image minimum to 4.2 and max to latest
- [x] Update `replace` doc to indicate it replaces all occurrences

Tests to be fixed here
- [x] metabase.api.database-test/db-ids-with-deprecated-drivers-test
- [x] metabase.api.table-test/datetime-binning-options-test
- [x] metabase.query-processor-test.case-test/test-case-aggregations+expressions
- [x] metabase.query-processor-test.count-where-test/count-where-inside-expression-test
  - ~skipped~: #27275
- [x] metabase.query-processor-test.sum-where-test/sum-where-inside-expressions-test
  -  ~skipped~: #27275
- [x] metabase.query-processor-test.expressions-test/nulls-and-zeroes-test
- [x] metabase-enterprise.serialization.cmd-test/blank-target-db-test
- [x] metabase.query-processor-test.expressions-test/expression-using-aggregation-test
  -  skipped: #27249
- [x] metabase.query-processor-test.expressions-test/expressions-in-order-by-test

extra 4.0 tests failing:
- [x] metabase.query-processor-test.advanced-math-test/test-round
- [x] metabase.query-processor-test.string-extracts-test/replace-test

Other tests
- [x]  merge https://github.com/metabase/metabase/pull/27209 or https://github.com/metabase/metabase/pull/27214

After merging
- [x] remove the workaround made in #27137

### CODE REVIEW

**Comment by snoe** [comment]
Opening review to get mongo tests to run

File: modules/drivers/mongo/src/metabase/driver/mongo.clj [hunk 1]
```diff
@@ -233,30 +234,24 @@
                  :standard-deviation-aggregations]]
   (defmethod driver/supports? [:mongo feature] [_driver _feature] true))
 
-(defn- db-version [db]
-  (get-in db [:details :version]))
+(defmethod driver/database-supports? [:mongo :expressions]
+  [_driver _feature db]
+  (boolean (some-> (:dbms_version db)
+                   :semantic-version
+                   (driver.u/semantic-version-gte [4 2]))))
```
Comment (calherries) [inline modules/drivers/mongo/src/metabase/driver/mongo.clj:241]: Can we not do nil punning here, and require `(:dbms_version db)` to not return nil? I can imagine if `(:dbms_version db)` returns nil in the future and suddenly we're skipping tests because of it.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 2]
```diff
@@ -420,21 +425,52 @@
...
+  [[_ & [_ & divisors :as args]]]
+  (let [build-division (fn build-division
+                         [[dividend & divisors]]
+                         (if (seq divisors)
+                           {"$divide" [(build-division divisors) (->rvalue dividend)]}
+                           (->rvalue dividend)))
+        division (build-division (reverse args))
+        nil-check (if (= 1 (count divisors))
+              {"$eq" [(->rvalue (first divisors)) 0]}
+              {"$or" (mapv (fn [divisor] {"$eq" [(->rvalue divisor) 0]}) divisors)})]
```
Comment (metamben) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:470]: It would be nice to include this test when the divisor is known to different from zero.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 3]
```diff
@@ -460,16 +460,28 @@
...
   (let [build-division (fn build-division
-                         [[dividend & divisors]]
-                         (if (seq divisors)
-                           {"$divide" [(build-division divisors) (->rvalue dividend)]}
-                           (->rvalue dividend)))
+                         [[head & tail]]
+                         (if (seq tail)
+                           {"$divide" [(build-division tail) (->rvalue head)]}
+                           (->rvalue head)))
+        ;; args go in reversed because build-division works outside in (/ 1 2 3) => (/ (/ 1 2) 3)
```
Comment (metamben) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:467]: Isn't this the shape a straight `reduce` would build?

Comment (snoe) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:467]: Thank you, I thought so but was having trouble making the leap.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 4]
```diff
@@ -420,21 +425,64 @@
...
+                  (if (some? cnt)
+                    (->rvalue cnt)
+                    {"$subtract" [{"$strLenCP" expr-val} idx-val]})]}))
+
+(defmethod ->rvalue :/
+  [[_ & [_ & divisors :as args]]]
+  ;; division works outside in (/ 1 2 3) => (/ (/ 1 2) 3)
+  (let [division (reduce
+                   (fn [accum head]
+                     (if accum
```
Comment (metamben) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:465]: In what situation can `accum` be falsy?

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 5]
```diff
@@ -755,41 +799,69 @@
...
+        stddev-name (name (gensym "$stddev-"))]
+    {:group {(subs stddev-name 1) (aggregation->rvalue [:stddev expr])}
+     :post  [{(annotate/aggregation-name ag) {:$pow [stddev-name 2]}}]}))
 
 (defmethod expand-aggregation :default
   [ag]
   {:group {(annotate/aggregation-name ag) (aggregation->rvalue ag)}})
 
+(def ^:private group-op
+  #{:var :share :count :avg :stddev :sum :min :max :distinct :sum-where :count-where})
```
Comment (metamben) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:825]: This kind of duplicates the aggregation operators.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 6]
```diff
@@ -755,41 +799,69 @@
...
-  (let [expanded-ags (map expand-aggregation aggregations)
+  (let [expanded-ags (map expand-embedded-aggregation aggregations)
         group-ags    (mapcat :group expanded-ags)
         post-ags     (mapcat :post expanded-ags)]
-    [{$group (into (ordered-map/ordered-map "_id" id) group-ags)}
-     (when (not-empty post-ags)
-       {:$addFields (into (ordered-map/ordered-map) post-ags)})]))
+    (into [{$group (into (ordered-map/ordered-map "_id" id) group-ags)}]
+          (map (fn [p] {:$addFields p}))
+          post-ags)))
```
Comment (metamben) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:864]: Create separate groups so that values introduced by previous stages can be referred to.

**Review by camsaul — APPROVED** [review]
Awesome. This LGTM
