### PR TITLE
Fix localization number separators

### LINKED ISSUE #61854: Matching numbers fails on CSV upload
### Describe the bug

We experienced the following issue when trying to upload CSV files to our Metabase instance:

Image

Interestingly, the issue was only present in our production environment and not in our staging environment. Extensive comparisons of configuration, runtime parameters and application state did not help in fixing it.

After spinning up Metabase in a Dev-environment and tracing the execution of the csv upload it became clear that the problem was happening when parsing numbers.

When an admin selects the "wrong" number separator style in the localization settings of the admin interface, the CSV upload does not work. When changing it to a different one, it works again.

### To Reproduce

1. Prepare a CSV file (any content will do):
`test.csv`
```
col_a,col_b
1,a
2,b
3,c
```
3. Spin up a new Metabase instance
4. Enable CSV uploads to the sample database (or any other database) in the admin interface
5. Upload the CSV to any collection => It will work
6. Go to the admin interface and change the number separator style in the localization settings to the last value `100'000.00`:

Image

7. Upload the same CSV to any collection again
8. See error
Image

### Expected behavior

The CSV upload works regardless of the selected number separator style.

### Logs

[601d0adf-9060-4457-87d5-3cc60c0f9895] 2025-08-06T09:57:33+02:00 DEBUG metabase.server.middleware.log GET /api/collection/4 200 10ms (5 DB calls) App DB connections: 1/5 Jetty threads: 5/50 (5 idle, 0 queued) (58 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
[601d0adf-9060-4457-87d5-3cc60c0f9895] 2025-08-06T09:57:33+02:00 ERROR metabase.server.middleware.log POST /api/upload/csv 500 91ms (5 DB calls) {:metabase-user-id 1} 
{:message "No matching clause: .'"}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "run-mode": "dev",
    "plan-alias": "",
    "version": {
      "tag": "vLOCAL_DEV",
      "hash": "06d1ba2ae111e66253209c01c244d6379acfc6dcb1911fa9ab6012cec9ce52e5"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-Ubuntu-0ubuntu124.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-Ubuntu-0ubuntu124.04.1",
    "os.name": "Linux",
    "os.version": "6.8.0-71-generic",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

P2, work around by not selecting 100'000.00 as separator

### Additional context

The error can possibly be found here: https://github.com/metabase/metabase/blob/cc758a125def0e47f52f2ff50a3b3f3c728f3b8f/src/metabase/upload/types.cljc in `int-regex`, `float-or-int-regex` or `float-regex`

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes https://github.com/metabase/metabase/issues/61854

Frontend has been modified recently so `.'` (apostrophe; utf8 0x27) separator is used for localization settings instead of `.’` (right single quotation mark; utf8 0xe28099).

This PR fixes the FE, updates the setter of the corresponding setting to avoid similar errors and adds test that ensures only correct values can be set.

### CODE REVIEW

File: frontend/src/metabase/admin/settings/components/widgets/FormattingWidget.tsx [hunk 1]
```diff
@@ -158,7 +158,7 @@ export function FormattingWidget() {
                 { label: "100 000,00", value: ", " },
                 { label: "100.000,00", value: ",." },
                 { label: "100000.00", value: "." },
-                { label: "100'000.00", value: ".'" },
+                { label: "100’000.00", value: ".’" },
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/widgets/FormattingWidget.tsx:161]: we should also have a frontend test for this so that the materiality of this is documented

**Review by edpaget — APPROVED** [review]

**Review by johnswanson — APPROVED** [review]

File: frontend/src/metabase/admin/settings/components/widgets/FormattingWidget.unit.spec.tsx [hunk 2]
```diff
@@ -164,4 +164,21 @@ describe("FormattingWidget", () => {
       expect(toasts).toHaveLength(6);
     });
   });
+
+  it("should proivde expected number separators (#61854)", async () => {
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/widgets/FormattingWidget.unit.spec.tsx]:
```suggestion
  it("should provide expected number separators (#61854)", async () => {
```

**Review by iethree — APPROVED** [review]
