### PR TITLE
Properly run tiles-query as admin user for static endpoints if JWT token is valid

### LINKED ISSUE #63687: Static embedding does not load pin map tiles: unauthorized error
### Describe the bug

Static embedding does not load pin map tiles: unauthorized error.
We have separate endpoints for static embedding tiles, but it seems we still require auth there instead of checking JWT

### To Reproduce

Do a static embedding and embed a map with tiles there. Open it in an incognito tab.

Image

### Expected behavior

Tiles should be loaded

### Logs

_No response_

### Information about your Metabase installation

```JSON
-
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
closes #63687
Properly run tiles-query as admin user for static endpoints if JWT token is valid

Currently, even though we have separate endpoints for pin map tiles, they don't properly disable the auth check if a JWT token is valid.

How to verify:
- `yarn dev-ee`
- create any question, set its viz type as `map`
- select `map type` as `pin map` and `pin type` as `tiles`
- save it
- statically embed it, get its iframe URL in a `preview` window, open the iframe in an incognito tab
- you should see blue pit tiles

### CODE REVIEW

File: src/metabase/embedding/api/embed.clj [hunk 1]
```diff
@@ -327,12 +328,13 @@
    :- [:map
        [:parameters {:optional true} ms/JSONString]]]
   (let [unsigned   (unsign-and-translate-ids token)
-        card-id    (embedding.jwt/get-in-unsigned-token-or-throw unsigned [:resource :question])
+        card-id    (api.embed.common/unsigned-token->card-id unsigned)
         parameters (json/decode+kw parameters)
```
Comment (sanex3339) [inline src/metabase/embedding/api/embed.clj:332]: `get-in-unsigned-token-or-throw` is called under the hood

File: src/metabase/embedding/api/embed.clj [hunk 2]
```diff
@@ -347,8 +349,10 @@
    :- [:map
        [:parameters {:optional true} ms/JSONString]]]
   (let [unsigned     (unsign-and-translate-ids token)
-        dashboard-id (embedding.jwt/get-in-unsigned-token-or-throw unsigned [:resource :dashboard])
+        dashboard-id    (api.embed.common/unsigned-token->dashboard-id unsigned)
         parameters   (json/decode+kw parameters)
```
Comment (sanex3339) [inline src/metabase/embedding/api/embed.clj:353]: `get-in-unsigned-token-or-throw` is called under the hood

File: src/metabase/embedding/api/embed.clj [hunk 3]
```diff
@@ -327,12 +328,13 @@
...
   (let [unsigned   (unsign-and-translate-ids token)
-        card-id    (embedding.jwt/get-in-unsigned-token-or-throw unsigned [:resource :question])
+        card-id    (api.embed.common/unsigned-token->card-id unsigned)
         parameters (json/decode+kw parameters)
         lat-field    (json/decode+kw lat-field)
         lon-field    (json/decode+kw lon-field)]
     (api.embed.common/check-embedding-enabled-for-card card-id)
-    (api.tiles/process-tiles-query-for-card card-id parameters zoom x y lat-field lon-field)))
+    (request/as-admin
+      (api.tiles/process-tiles-query-for-card card-id parameters zoom x y lat-field lon-field))))
```
Comment (sanex3339) [inline src/metabase/embedding/api/embed.clj:337]: @noahmoss please validate tha this is the correct approach to bypass regular user auth checks

Comment (noahmoss) [reply src/metabase/embedding/api/embed.clj:337]: looks fine

**Review by noahmoss — APPROVED** [review]
