### PR TITLE
JSON query in postgres now walks identifier tree if one encountered (fixes #22967)

### LINKED ISSUE #22967: "Can't pop empty vector" when binning JSON fields
**Describe the bug**
When you have a JSON column and make Metabase do the auto-binning on a summarization, it fails with "Can't pop empty vector".

**Logs**
<details>
```
metabase         | 2022-05-26 02:15:27,083 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 24.0 ms (23 DB calls) App DB connections: 1/13 Jetty threads: 5/50 (2 idle, 0 queued) (119 total active threads) Queries in flight: 0 (0 queued); postgres DB 2 connections: 0/1 (0 threads blocked)
metabase         | 2022-05-26 02:15:30,066 ERROR middleware.catch-exceptions :: Error processing query: null
metabase         | {:database_id 2,
metabase         |  :started_at #t "2022-05-26T02:15:30.001783Z[GMT]",
metabase         |  :json_query
metabase         |  {:type "query",
metabase         |   :query {:source-table 10, :aggregation [["count"]], :breakout [["field" 84 {:binning {:strategy "default"}}]]},
metabase         |   :database 2,
metabase         |   :parameters [],
metabase         |   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
metabase         |  :native nil,
metabase         |  :status :failed,
metabase         |  :class java.lang.IllegalStateException,
metabase         |  :stacktrace
metabase         |  ["clojure.lang.PersistentVector.pop(PersistentVector.java:470)"
metabase         |   "clojure.lang.PersistentVector.pop(PersistentVector.java:22)"
metabase         |   "clojure.lang.RT.pop(RT.java:755)"
metabase         |   "clojure.core$pop.invokeStatic(core.clj:1476)"
metabase         |   "clojure.core$pop.invoke(core.clj:1469)"
metabase         |   "--> models.field$nfc_field__GT_parent_identifier.invokeStatic(field.clj:234)"
metabase         |   "models.field$nfc_field__GT_parent_identifier.invoke(field.clj:219)"
metabase         |   "driver.postgres$json_query.invokeStatic(postgres.clj:296)"
metabase         |   "driver.postgres$json_query.invoke(postgres.clj:291)"
metabase         |   "driver.postgres$fn__59804.invokeStatic(postgres.clj:318)"
metabase         |   "driver.postgres$fn__59804.invoke(postgres.clj:304)"
metabase         |   "driver.sql.query_processor$as.invokeStatic(query_processor.clj:597)"
metabase         |   "driver.sql.query_processor$as.doInvoke(query_processor.clj:583)"
metabase         |   "driver.sql.query_processor$fn__46209$fn__46211.invoke(query_processor.clj:649)"
metabase         |   "driver.sql.query_processor$fn__46209.invokeStatic(query_processor.clj:648)"
metabase         |   "driver.sql.query_processor$fn__46209.invoke(query_processor.clj:643)"
metabase         |   "driver.postgres$fn__59811.invokeStatic(postgres.clj:334)"
metabase         |   "driver.postgres$fn__59811.invoke(postgres.clj:327)"
metabase         |   "driver.sql.query_processor$apply_top_level_clauses$fn__46472.invoke(query_processor.clj:913)"
metabase         |   "driver.sql.query_processor$apply_top_level_clauses.invokeStatic(query_processor.clj:911)"
metabase         |   "driver.sql.query_processor$apply_top_level_clauses.invoke(query_processor.clj:907)"
metabase         |   "driver.sql.query_processor$apply_clauses.invokeStatic(query_processor.clj:941)"
metabase         |   "driver.sql.query_processor$apply_clauses.invoke(query_processor.clj:931)"
metabase         |   "driver.sql.query_processor$mbql__GT_honeysql.invokeStatic(query_processor.clj:960)"
metabase         |   "driver.sql.query_processor$mbql__GT_honeysql.invoke(query_processor.clj:955)"
metabase         |   "driver.sql.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:969)"
metabase         |   "driver.sql.query_processor$mbql__GT_native.invoke(query_processor.clj:965)"
metabase         |   "driver.sql$fn__82577.invokeStatic(sql.clj:40)"
metabase         |   "driver.sql$fn__82577.invoke(sql.clj:38)"
metabase         |   "query_processor.middleware.mbql_to_native$query__GT_native_form.invokeStatic(mbql_to_native.clj:13)"
metabase         |   "query_processor.middleware.mbql_to_native$query__GT_native_form.invoke(mbql_to_native.clj:8)"
metabase         |   "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50385.invoke(mbql_to_native.clj:20)"
metabase         |   "query_processor$fn__52917$combined_post_process__52922$combined_post_process_STAR___52923.invoke(query_processor.clj:207)"
metabase         |   "query_processor$fn__52917$combined_pre_process__52918$combined_pre_process_STAR___52919.invoke(query_processor.clj:204)"
metabase         |   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365$fn__51370.invoke(resolve_database_and_driver.clj:35)"
metabase         |   "driver$do_with_driver.invokeStatic(driver.clj:75)"
metabase         |   "driver$do_with_driver.invoke(driver.clj:71)"
metabase         |   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365.invoke(resolve_database_and_driver.clj:34)"
metabase         |   "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47469.invoke(fetch_source_query.clj:281)"
metabase         |   "query_processor.middleware.store$initialize_store$fn__47657$fn__47658.invoke(store.clj:11)"
metabase         |   "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
metabase         |   "query_processor.store$do_with_store.invoke(store.clj:38)"
metabase         |   "query_processor.middleware.store$initialize_store$fn__47657.invoke(store.clj:10)"
metabase         |   "query_processor.middleware.normalize_query$normalize$fn__51637.invoke(normalize_query.clj:22)"
metabase         |   "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__58301.invoke(handle_audit_queries.clj:130)"
metabase         |   "query_processor.middleware.constraints$add_default_userland_constraints$fn__48727.invoke(constraints.clj:52)"
metabase         |   "query_processor.middleware.process_userland_query$process_userland_query$fn__51576.invoke(process_userland_query.clj:145)"
metabase         |   "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51948.invoke(catch_exceptions.clj:162)"
metabase         |   "query_processor.reducible$async_qp$qp_STAR___44196$thunk__44198.invoke(reducible.clj:100)"
metabase         |   "query_processor.reducible$async_qp$qp_STAR___44196.invoke(reducible.clj:106)"
metabase         |   "query_processor.reducible$async_qp$qp_STAR___44196.invoke(reducible.clj:91)"
metabase         |   "query_processor.reducible$sync_qp$qp_STAR___44207.doInvoke(reducible.clj:126)"
metabase         |   "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
metabase         |   "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
metabase         |   "query_processor$fn__52964$process_query_and_save_execution_BANG___52973$fn__52976.invoke(query_processor.clj:337)"
metabase         |   "query_processor$fn__52964$process_query_and_save_execution_BANG___52973.invoke(query_processor.clj:330)"
metabase         |   "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017$fn__53020.invoke(query_processor.clj:349)"
metabase         |   "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017.invoke(query_processor.clj:342)"
metabase         |   "api.dataset$run_query_async$fn__67408.invoke(dataset.clj:68)"
metabase         |   "query_processor.streaming$streaming_response_STAR_$fn__39319$fn__39320.invoke(streaming.clj:162)"
metabase         |   "query_processor.streaming$streaming_response_STAR_$fn__39319.invoke(streaming.clj:161)"
metabase         |   "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
metabase         |   "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
metabase         |   "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
metabase         |  :card_id nil,
metabase         |  :context :ad-hoc,
metabase         |  :error "Can't pop empty vector",
metabase         |  :row_count 0,
metabase         |  :running_time 0,
metabase         |  :preprocessed
metabase         |  {:type :query,
metabase         |   :query
metabase         |   {:source-table 10,
metabase         |    :aggregation [[:aggregation-options [:count] {:name "count"}]],
metabase         |    :breakout
metabase         |    [[:field 84 {:binning {:strategy :num-bins, :min-value 24.0, :max-value 24.0, :num-bins 8, :bin-width 1}}]],
metabase         |    :order-by
metabase         |    [[:asc [:field 84 {:binning {:strategy :num-bins, :min-value 24.0, :max-value 24.0, :num-bins 8, :bin-width 1}}]]]},
metabase         |   :database 2,
metabase         |   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
metabase         |   :info {:executed-by 1, :context :ad-hoc}},
metabase         |  :data {:rows [], :cols []}}
metabase         | 
metabase         | 2022-05-26 02:15:30,067 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 77.2 ms (16 DB calls) App DB connections: 0/13 Jetty threads: 5/50 (2 idle, 0 queued) (119 total active threads) Queries in flight: 0 (0 queued)
```
</details>

**To Reproduce**
1. run the script that is in the additional comments
2. Go to the "jsons" table, click on Summarize->Values-->Qty (leave it with the auto-binning)
3. see the error

**Expected behavior**
See the bins

**Screenshots**
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop-OS 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.43.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
Important

**Additional context**
```
create table jsons
(
    values jsonb
);
INSERT INTO public.jsons (values)
VALUES ('{"qty": 2}');

INSERT INTO public.jsons (values)
VALUES ('{"qty": 5}');

INSERT INTO public.jsons (values)
VALUES ('{"qty": 6}');

INSERT INTO public.jsons (values)
VALUES ('{"qty": 8}');

INSERT INTO public.jsons (values)
VALUES ('{"qty": 1}');

INSERT INTO public.jsons (values)
VALUES ('{"qty": 25}');

INSERT INTO public.jsons (values)
VALUES ('{"qty": 54}');

INSERT INTO public.jsons (values)
VALUES ('{"qty": 2}');

INSERT INTO public.jsons (values)
VALUES ('{"qty": 4}');

INSERT INTO public.jsons (values)
VALUES ('{"qty": 7}');
```

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to #22967.

Previously the notion of the identifier in `json-query` in postgres assumed a singular identifier at the top-level of the `Identifier` record. This is not always the case in complicated binning scenarios - the identifier could also just comprise an entire tree of Identifier record maps with the actual Identifier we're looking to turn into the JSON query in some leaf somewhere.

Therefore, the json-query's determination of what the identifier is now walks that identifier record tree and replaces the identifiers that have JSON field semantics with the reification of `ToSql` from `json-query`.

Previous attempt at solution hacked together something at the `json-query` level, changing the reification, but that only worked for one level down, instead of just walking the Identifier tree and therefore getting stuff at arbitrary tree depth. And we do get nontrivial tree depth in the bucketing in #22967.

### CODE REVIEW

File: test/metabase/driver/postgres_test.clj [hunk 1]
```diff
@@ -300,6 +301,30 @@
...
+        (mt/with-temp* [Database [database  {:engine :postgres, :details details}]
+                        Table    [table     {:db_id (u/the-id database)
+                                             :name "complicated_identifiers"}]
+                        Field    [val-field {:table_id      (u/the-id table)
+                                             :nfc_path      [:jsons "values" "qty"]
+                                             :database_type "integer"}]]
+        (qp.store/with-store
+          (qp.store/fetch-and-store-database! (u/the-id database))
+          (qp.store/fetch-and-store-tables! [(u/the-id table)])
+          (qp.store/fetch-and-store-fields! [(u/the-id val-field)])
```
Comment (camsaul) [inline test/metabase/driver/postgres_test.clj:318]: We have `mt/with-everything-store` that you can use here instead of doing this manually

**Review by camsaul — APPROVED** [review]
This looks good to me 👍

File: test/metabase/driver/postgres_test.clj (hunk 1 above)
Comment (howonlee) [reply test/metabase/driver/postgres_test.clj:318]: Macro doesn't seem to work with JSON columns, will also investigate...
