### PR TITLE
Handle not available Notifications API

### LINKED ISSUE #22172: Dashboard/question causes frontend reload loop, when browser Notification API cannot be read
**Describe the bug**
Metabase v0.43.0-rc1 refreshes nearly every second on Mobile Safari.

**Logs**
N/A

**To Reproduce**
1. Open mobile safari
2. Open MB
3. Open a dashboard
4. Notice MB refreshing on it's own. (Video below may look like I am "pulling to refresh", but I am not.)

**Expected behavior**
No refreshing.

**Screenshots**

https://user-images.githubusercontent.com/659829/165672442-97698a7e-9fde-4db9-be02-a95d66a599d5.MP4

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "iPhone",
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.4.181-99.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-18",
      "tag": "v0.43.0-rc1",
      "branch": "release-x.43.x",
      "hash": "2cab453"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
Pretty severe, but this is an RC so you know.

**Additional context**
Metabase is awesome?

### PR DESCRIPTION
**Pull request by kulyk**
Fixes #22172

Dashboard and question pages were constantly erroring and reloading on mobile because they were trying to use unavailable web notifications API. Fixed by adding checks if the `Notification` class is available in `window`. It'd be better to encapsulate all of these inside the `useWebNotification` hook, but we should better do that in another PR and keep the fix simple.

### To Verify

_I'm not sure if there is a go-to approach on how to spin up Metabase locally so you can open it on mobile, but here's what I did:_

1. Get your local IP address (`192.168.x.x`)
2. Replace `localhost` in [here](https://github.com/metabase/metabase/blob/6602f0f57138a20737b6ceb233900b868673365e/webpack.config.js#L221) with your local IP (keep the 8080 port though)
3. Remove [this line](https://github.com/metabase/metabase/blob/6602f0f57138a20737b6ceb233900b868673365e/src/metabase/server/middleware/security.clj#L126) to get remove the `Content-Security-Policy` HTTP header
4. Run Metabase with `MB_JETTY_HOST` var set to your local IP, example: `MB_JETTY_PORT=192.168.x.x yarn dev`
5. On your mobile phone, go to `{{ YOUR_LOCAL_IP }}:8000`
6. Open any question/dashboard
7. Ensure the page opens and can be normally used
8. On the desktop: ensure changes from #21414 work

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/166446384-a37d0b91-e567-4777-b713-a5f9c2d894d9.MP4

**After**

https://user-images.githubusercontent.com/17258145/166446381-9de2cb55-d762-4d8e-b859-02d5c4d015e6.mov

### CODE REVIEW

**Review by flamber — APPROVED** [review]
Found an easy way to test this on Firefox desktop.
Go to `about:config` - find `dom.webnotifications.enabled` and set it to `false`
Then try going to a dashboard on 0.43 - **warning** it might crash the browser

Works as it should with this PR.

File: frontend/src/metabase/query_builder/containers/QueryBuilder.jsx [hunk 1]
```diff
@@ -373,7 +373,7 @@ function QueryBuilder(props) {
   const { isRunning } = uiControls;
 
   const onTimeout = useCallback(() => {
-    if (Notification.permission === "default") {
+    if ("Notification" in window && Notification.permission === "default") {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/containers/QueryBuilder.jsx:376]: Could we move all `Notification` checks to a module, e.g. to `lib/notifications.ts`? This would prevent copy-pasting these checks across different files.

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/query_builder/containers/QueryBuilder.jsx (hunk 1 above)
Comment (kulyk) [reply frontend/src/metabase/query_builder/containers/QueryBuilder.jsx:376]: I'd actually vote for hiding all that in the `useWebNotification`. Let's let the fix in and then polish the implementation 🙂
