### PR TITLE
Fix redundant network requests triggered in object detail modal 

### LINKED ISSUE #32720: Redundant network requests triggered in object detail modal
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/ea4a56c9-a2fc-4d31-957f-bffbf6be1400

### To Reproduce

1. Create & save a new model based on the Accounts table from Sample Database
2. Click any id in the table to open object detail view
3. Modal opens. Notice 3 network requests are sent to `/api/dataset` - it's because the accounts table has relations with 3 other tables.
4. Close the modal.
5. Open up the same modal again. Notice 9 network requests are sent to `/api/dataset`.

### Expected behavior

Only 3 nework requests are sent. 6 redundant network requests are not sent.

### Logs

_No response_

### Information about your Metabase installation

```JSON
You're on version v0.47.1-SNAPSHOT
Built on 2023-07-28

Src_hash: d2a447f20d7b7cbd4a7db387df96702e81fd0ced

Branch: 32350-actions-tests

Hash: f3094f6
```

### Severity

P4

### Additional context

Slack conversation for reference: https://metaboat.slack.com/archives/C057T1QTB3L/p1690442248075069?thread_ts=1690440580.596059&cid=C057T1QTB3L

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #32720

### Description

There is a bug where object relationships are not loaded at all, and it may seem to be caused by this PR, but it's not - it exists in `master` - #33708.

This PR also includes extracting `ObjectRelationships.styled.tsx` & `ObjectDetailTable.styled.tsx` out of `ObjectDetailView.styled.tsx`, which I forgot to do in #33694.

### How to verify

Follow reproduction steps in the [original issue report](https://github.com/metabase/metabase/issues/32720).

### Demo

https://github.com/metabase/metabase/assets/6830683/4cfca50d-5bcc-41ad-b915-090e4059b485

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx [hunk 1]
```diff
@@ -116,10 +120,6 @@ export function ObjectDetailView({
     if (table && _.isEmpty(table.fks) && !isVirtualCardId(table.id)) {
       fetchTableFks(table.id as ConcreteTableId);
     }
-    // load up FK references
-    if (!_.isEmpty(tableForeignKeys)) {
-      loadFKReferences();
-    }
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx:122]: The first time Object Detail Modal is mounted, this condition did not execute.
On subsequent mounts, this `loadFKReferences` call was duplicating what `useEffect` takes care of later on.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx [hunk 2]
```diff
@@ -176,10 +176,12 @@ export function ObjectDetailView({
...
 
   useEffect(() => {
-    if (!_.isEmpty(tableForeignKeys) && prevZoomedRowId !== zoomedRowID) {
+    const hadPrevZoomedRow = prevZoomedRowId != null;
+
+    if (hasFks && hadPrevZoomedRow && prevZoomedRowId !== zoomedRowID) {
       loadFKReferences();
     }
-  }, [tableForeignKeys, prevZoomedRowId, zoomedRowID, loadFKReferences]);
+  }, [hasFks, prevZoomedRowId, zoomedRowID, loadFKReferences]);
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx:184]: This was the second `loadFKReferences` call duplication.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx [hunk 3]
```diff
@@ -46,9 +46,7 @@ const mapStateToProps = (state: State, { data }: ObjectDetailProps) => {
   const canZoomNextRow = isZooming ? Boolean(getCanZoomNextRow(state)) : false;
 
   return {
-    // FIXME: remove the non-null assertion operator
-    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
-    question: getQuestion(state)!,
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx:51]: Following the Boy Scout Rule.

**Review by ranquild — APPROVED** [review]
