### PR TITLE
fix incorrect value is used for the bubble size domain

### LINKED ISSUE #23977: Bubble size is scaling according to y-axis on scatter charts
**Describe the bug**
On Metabase 0.43.4, the bubble size is not scaling appropriately and seems to be taking the y-axis as the scale indicator, so if the y-axis is a small number and the bubble size is a large number. In reality the bubble size may have absolutely nothing to do with the y-axis.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

[reporting.zayzoon.xyz-1657833454992.log](https://github.com/metabase/metabase/files/9115530/reporting.zayzoon.xyz-1657833454992.log)

**To Reproduce**
1. Create a NEW question as an SQL question, with the following SQL:
`select 1 as x_axis, 100 as bubble_size, 0.5 as y_axis
union all
select 2 as x_axis, 75 as bubble_size, 0.25 as y_axis
union all
select 3 as x_axis, 140 as bubble_size, 0.6 as y_axis
`

2. Change the visualization to a "Scatter Plot"
3. Select `bubble_size` as bubble size, `x_axis` as x-axis, and `y_axis` as y-axis
4. See graph that's generated

**Expected behavior**
What used to happen in prior versions is that the bubbles would be scaled automatically and independently of the y-axis. I believe there as a maximum radius or something to that effect.

**Screenshots**
This situation is problematic 👇
image

This opposite situation is less of a problem but one could envision the bubbles just being tiny 
image

**Information about your Metabase Installation:**

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "4.14.281-212.502.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.23"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-27",
      "tag": "v0.43.4",
      "branch": "release-x.43.x",
      "hash": "61cc28e"
    },
    "settings": {
      "report-timezone": "America/Edmonton"
    }
  }
}

**Severity**
It's preventing us from doing some key 3-dimensional analysis for our business, so I consider it extremely important.

**Additional context**

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/23977

## Changes

Fixes domain calculation for the bubble size dimension. It used yAxis domain before that.

## How to verify

Check the original issue for repro steps

## Screenshots

Before
Screenshot 2022-07-19 at 19 23 59

After
Screenshot 2022-07-19 at 19 23 39

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js [hunk 1]
```diff
@@ -444,20 +444,31 @@ function applyChartLineBarSettings(
...
 
+const BUBBLE_SIZE_INDEX = 2;
+
+const getBubbleSizeMaxDomain = (datas, seriesIndex) => {
+  const seriesData = datas[seriesIndex];
+  const sizeValues = seriesData.map(data => data[BUBBLE_SIZE_INDEX]);
+  return d3.max(sizeValues);
+};
+
 // TODO - give this a good name when I figure out what it does
```
Comment (gusaiani) [inline frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js:455]: @alxnddr, I'd heartily encourage you to follow up with a PR raising code morale here.

Basic stuff comes to mind:
A fitting function name.
Extracting what happens if `isBubble === true` into its own function.
Renaming the `datas` variable. Plural of plural's been a first for me.

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js [hunk 2]
```diff
@@ -444,20 +444,31 @@ function applyChartLineBarSettings(
   }
 }
 
+const BUBBLE_SIZE_INDEX = 2;
+
+const getBubbleSizeMaxDomain = (datas, seriesIndex) => {
```
Comment (gusaiani) [inline frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js:449]: I was late to realize we use the name `datas` quite a lot.

Actually wrote a comment below about it before I grepped our codebase and saw how many there are.

Strikes me as quite bizarre, no idea if this is used for real anywhere else.

**Review by gusaiani — APPROVED** [review]
Awesome, 2 comments around the fix.

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js (hunk 1 above)
Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js:455]: @gusaiani thanks for your suggestions

> Extracting what happens if isBubble === true into its own function.

The function has 20 lines and the outer `if` condition which is 19 lines of the function does one particular thing — configures bubble radius. Do you think it worth splitting already not so long function extracting subpart of generally one thing?

> Renaming the datas variable. Plural of plural's been a first for me.

This imperfect name is widely in our codebase:
datas — array of arrays of series data
data — array of series data

It seems like an overkill to rename it in the entire codebase in the scope of a bugfix. What do you think?

> A fitting function name.

Thanks, renamed it

Comment (gusaiani) [reply frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js]: Thanks, @alxnddr.

Communication's a hard thing.
My comment wasn't so clear about how important I felt each thought was.

I do think you tackled what I also thought was most important — the function name. Thanks for that.

> Do you think it worth splitting already not so long function extracting subpart of generally one thing?

I personally do think it's worth it.
This isn't the style we use everyday.
One person that summed this idea up well is [Sandi Metz](https://thoughtbot.com/blog/sandi-metz-rules-for-developers).

Another way to do the same thing is by having each function do just one thing, really as much as possible.
As it is, this function does about 4 things.

1. `chart.keyAccessor(d => d.key[0]).valueAccessor(d => d.key[1]);` which is pretty incomprehensible for the non-initiated.

2. Nested if-elses to treat the visuals, with about 3 outcomes including doing nothing.

So extracting at least that longer block, and naming it well (otherwise we may be worse off), in my view reduces cognitive strain. This chunking, imho, changes our lives. We are happier to wake up to work and much more productive.

> It seems like an overkill to rename it in the entire codebase in the scope of a bugfix. What do you think?

Definitely. 

In fact all suggestions were possibilities for future edits.

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js [hunk 3]
```diff
@@ -444,20 +444,29 @@ function applyChartLineBarSettings(
...
+  return d3.max(sizeValues);
+};
+
+function configureScatterChart(chart, datas, index) {
   chart.keyAccessor(d => d.key[0]).valueAccessor(d => d.key[1]);
 
   if (chart.radiusValueAccessor) {
-    const isBubble = datas[index][0].length > 2;
-    if (isBubble) {
+    const hasBubbleRaduisValues = datas[index][0].length > BUBBLE_SIZE_INDEX;
```
Comment (gusaiani) [inline frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js:459]: little typo: …Radius…

**Review by gusaiani — CHANGES_REQUESTED** [review]
Little typo introduced, see inlined comment.

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js (hunk 1 above)
Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js]: @gusaiani thanks for the clarification. I do personally think that breaking down everything into <=5 lines functions is not a very good pattern and it brings maintainability issues as very long functions do.

First,  the smallest granularity functions that at up to 5 lines makes you jumping to implementation to understand how it works or when you debug it. Compared to that, 20 lines fit in 1/3 of a laptop screen and you don't need to jump to small functions in the same file above or even in different files. So it still seems like to much to break down 20 line functions 4 different tiny functions especially when they are not even extracting any shared reusable logic.
There is a [research](https://softwarebyscience.com/very-short-functions-are-a-code-smell-an-overview-of-the-science-on-function-length/) on this topic.

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js (hunk 3 above)
Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js]: Thanks, fixed that

**Review by gusaiani — APPROVED** [review]

**Comment by gusaiani** [comment]
@ranquild Yup agreed, apologies!
