### PR TITLE
GDGT-232 fix: dashboard subscriptions should work even if Slack channels are renamed

### LINKED ISSUE #19496: Dashboard subscription should still work if Slack channel is renamed
**Describe the bug**
Currently, when a dashboard subscription for Slack is created, we store the target Slack channel by name. This means that if the channel is renamed, the subscription will stop being sent to that channel until the subscription is re-saved with the new channel name.

Instead, we should save channel IDs which remain constant even if a channel name is changed.

**To Reproduce**
1. Create and save a dashboard subscription sent to a slack channel
2. In Slack, rename the channel
3. In Metabase, click the "Send to Slack now" button to send a test subscription
4. Observe that the message is not sent, and that a `channel_not_found` error is printed in the logs. If you refresh the dashboard and open the subscription details, the channel selection is blank.

### PR DESCRIPTION
**Pull request by metatyb**
Closes https://github.com/metabase/metabase/issues/19496

### Description

Dashboard subscriptions store Slack channels by name (e.g. `"#alerts"`). Slack channel IDs are immutable, but names are not. Renaming a channel breaks all subscriptions targeting it with just the name.

This PR fixes this by storing the immutable Slack channel ID alongside the display name at subscription creation time. At send time, we prefer the ID over the name - this maintains backwards compatibility with legacy subscriptions. The UI remains entirely name-based - users never see or interact with channel IDs.

There remains related issues we may follow up on in separate PRs:
* Backfilling old subscriptions with a custom migration
* Keeping slack channel display names synced (this is now possible since we persist the immutable channel IDs) - this is to maintain a more consistent UX for users when viewing channels in the picker (which shows names, not IDs)

Possible UX issue:
* Slack channel pickers cache the list of Slack channels, so if a slack channel changes its name within the 10 minute interval after that list of cached, the user does not see the newly renamed channel display name till after the cache expires.

### How to verify
Prereqs:
* Slack integrated into your Metabase instance - https://www.metabase.com/docs/latest/configuring-metabase/slack

1. Create a dashboard 
2. Set up a subscription to send to Slack
3. Pick a channel from the list of channels available. (e.g. `#old-channel`)
4. Rename the channel in slack (`#new-channel`)
5. Create a new channel in slack with the old name (`old-channel`)
6. Press the test send to Slack button - this should post the results of the dashboard to the channel `#new-channel` even though the Slack channel displayed in Metabase was the old channel `#old-channel`.
7. Save the subscription, and wait for the normal send job to complete at the hourly mark. The dashboard should be sent to `#old-channel`

This proves subscriptions are persisted with the channel ID and prioritise that as the identifier when sending to subscribed Slack channels.

### Demo

This shows the test slack send flow:

https://github.com/user-attachments/assets/7584b8dd-6e97-4a29-b31d-a5a361bc29cb

Hourly job sent to the right channel by ID:
hourly-subscription-sends-to-slack-id

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase-types/api/notification-channels.ts [hunk 1]
```diff
@@ -5,10 +5,15 @@ import type {
...
+export type SlackChannelOption = {
+  displayName: string;
+  id: string;
+};
+
 type ChannelField = {
   name: string;
   displayName: string;
-  options?: string[];
+  options?: string[] | SlackChannelOption[];
```
Comment (kamilmielnik) [inline frontend/src/metabase-types/api/notification-channels.ts]: Should strings still be allowed?

```suggestion
  options?: SlackChannelOption[];
```

File: frontend/src/metabase/notifications/channels/SlackChannelField.tsx [hunk 2]
```diff
@@ -31,13 +46,19 @@ export const SlackChannelField = ({
   const channelField = channelSpec.fields?.find(
     (field) => field.name === CHANNEL_FIELD_NAME,
   );
+  const slackOptions = (channelField?.options ?? []) as SlackChannelOption[];
```
Comment (kamilmielnik) [inline frontend/src/metabase/notifications/channels/SlackChannelField.tsx]: We should not need a cast here

File: frontend/src/metabase/notifications/channels/SlackChannelFieldNew.tsx [hunk 3]
```diff
@@ -31,16 +37,20 @@ export const SlackChannelFieldNew = ({
   const channelField = channelSpec.fields?.find(
     (field) => field.name === CHANNEL_FIELD_NAME,
   );
+  const slackOptions = (channelField?.options ?? []) as SlackChannelOption[];
```
Comment (kamilmielnik) [inline frontend/src/metabase/notifications/channels/SlackChannelFieldNew.tsx]: We should not need a cast here

File: frontend/src/metabase/notifications/channels/SlackChannelField.unit.spec.tsx [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+  name: "Slack",
+  schedules: ["hourly"],
+  schedule_type: null,
+  allows_recipients: false,
+  configured: true,
+  fields: [
+    {
+      name: "channel",
+      displayName: "Post to",
+      options: SLACK_OPTIONS as any,
```
Comment (kamilmielnik) [inline frontend/src/metabase/notifications/channels/SlackChannelField.unit.spec.tsx]:
```suggestion
      options: SLACK_OPTIONS,
```

File: frontend/src/metabase/notifications/channels/SlackChannelField.unit.spec.tsx [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+  Channel,
+  ChannelSpec,
+  SlackChannelOption,
+} from "metabase-types/api";
+
+import {
+  SlackChannelField,
+  findChannelId,
+  getDisplayNames,
+} from "./SlackChannelField";
```
Comment (kamilmielnik) [inline frontend/src/metabase/notifications/channels/SlackChannelField.unit.spec.tsx]: We put utils in `utils.ts` and test them in a separate suite

File: frontend/src/metabase/notifications/channels/SlackChannelField.unit.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,146 @@
...
+
+function StatefulWrapper({
+  initialChannel,
+  spy,
+}: {
+  initialChannel: Channel;
+  spy: jest.Mock;
+}) {
+  const [channel, setChannel] = useState(initialChannel);
+  const onChannelPropertyChange = (prop: string, value: any) => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/notifications/channels/SlackChannelField.unit.spec.tsx]: We should not use `any` here.
I see that `SlackChannelFieldProps["onChannelPropertyChange"]` is not typed at all - let's fix it while we're at it 🙏

File: frontend/src/metabase/notifications/channels/SlackChannelField.tsx [hunk 7]
```diff
@@ -17,7 +21,10 @@ const ALLOWED_PREFIXES = [CHANNEL_PREFIX, USER_PREFIX];
 interface SlackChannelFieldProps {
   channel: Channel;
   channelSpec: ChannelSpec;
-  onChannelPropertyChange: any;
+  onChannelPropertyChange: (
+    key: string,
+    value: Record<string, string | boolean>,
```
Comment (metatyb) [inline frontend/src/metabase/notifications/channels/SlackChannelField.tsx:26]: Keeping this type specific to only the `details` property that this SlackChannelField updates:

https://github.com/metabase/metabase/blob/fcc151522a2e39fc38dcceeb7cdd1a49aa52d6d7/frontend/src/metabase-types/api/notification-channels.ts#L102

File: frontend/src/metabase/notifications/channels/utils.ts [hunk 8]
```diff
@@ -0,0 +1,12 @@
+import type { SlackChannelOption } from "metabase-types/api";
+
+export function getDisplayNames(options: SlackChannelOption[]): string[] {
+  return options.map((o) => o.displayName);
+}
+
+export function findChannelId(
+  options: SlackChannelOption[],
+  displayName: string,
+): string | undefined {
```
Comment (kamilmielnik) [inline frontend/src/metabase/notifications/channels/utils.ts]:
```suggestion
): SlackChannelOption["id"] | undefined {
```

or even better we should alias this type, like we do in many other places (e.g. `UserId`, `CardId`, etc.)


```suggestion
): SlackChannelOptionId | undefined {
```

**Review by kamilmielnik — COMMENTED** [review]
FE changes look good 👍 

----

We need a test reproducing the issue - is the backend coverage sufficient, or should we add an e2e/unit test for it?

File: frontend/src/metabase/notifications/channels/utils.ts (hunk 8 above)
Comment (metatyb) [reply frontend/src/metabase/notifications/channels/utils.ts]: TIL, i like the alias approach

**Comment by metatyb** [comment]
@kamilmielnik 
> We need a test reproducing the issue - is the backend coverage sufficient, or should we add an e2e/unit test for it?

Agreed, I added both the unit and e2e tests. Not entirely sure if the e2e tests are necessary / worth the extra seconds added to the test suite though.

**Comment by kamilmielnik** [comment]
> @kamilmielnik
> 
> > We need a test reproducing the issue - is the backend coverage sufficient, or should we add an e2e/unit test for it?
> 
> Agreed, I added both the unit and e2e tests. Not entirely sure if the e2e tests are necessary / worth the extra seconds added to the test suite though.

By repro I meant a test that runs this scenario:

> 1. Create a dashboard subscription sent to a Slack channel
> 2. In Slack, rename the channel
> 3. Click "Send to Slack now" — observe channel_not_found error in logs
> 4. Refreshing the dashboard shows the channel selection as blank

However with the Slack being mocked in e2e tests, I don't think it's possible to test this scenario.

**Review by kamilmielnik — APPROVED** [review]
