### PR TITLE
Fix issue with stale SQL connection pools consuming unneeded connections

### LINKED ISSUE #2038: generic_sql driver is not shutting down old connection pools properly
Metabase version is `0.15.0`

To reproduce:
* open up psql console and check that you have no clients connected using `select datname, ((date_part('min', age(now(), backend_start)))) as age, count(*) from pg_stat_activity GROUP BY 1, 2 ORDER BY 1, 2;`  which shows the database connected to, the age of the connection in minutes, and the count of connections.
* start up a metabase REPL and navigate to the `metabase.driver.generic-sql` namespace
* to make testing easy, modify the `:ttl/threshold` to be `(* 60 1000)` aka 1 minute
* verify that there is nothing in your current memoize cache `(memoize/snapshot connection-spec->pooled-connection-spec)` which should output `{}`
* make a call to `connection-spec->pooled-connection-spec` with a connection-spec which represents valid connection details for your postgres database
* check the contents of your memoize cache to see the cached connection pool `(memoize/snapshot connection-spec->pooled-connection-spec)`
* then check your database connections on postgres again, you should now see 4 connections (1 is your local shell + 3 for the MB connection pool)
* wait a minute+ and repeat
* wait a minute+ and repeat.  etc, etc.

In the output you will see that as the minutes go by and the specified 1 minute ttl value elapses, memoize is properly replacing the value in the cache with a new connection pool, however nothing is done to shutdown the old connection pools and close their db connections.  So 2 basic problems exist:
1. if no activity takes place against the memoized cache then the existing db pool remains in place without disruption.  so if the pool has 3 open connections and then nobody access the Metabase instance for 12 hours the pool will remain open and active during all that time.  Ideally we'd more actively reclaim pools after a given amount of inactivity.
2. when the ttl expires memoize replaces the old cache entry with a new one but it does nothing to shutdown the old connection pool and thus leaves it lying around and still holding onto db connection.

### PR DESCRIPTION
**Pull request by agilliland**
fixes #2038 

This does a small bit of tidy work on our generic_sql driver around the code that handles connection formation and pooling.  Main change is that instead of using memoize/ttl which wasn't accomplishing what we wanted, instead we simply maintain our own atom which manages a connection pool per database.

In addition to simplifying the connection pool management and only maintaining a single pool per database, we also add in the ability to actively shutdown a pool when we detect that something about the database has changed.  This is mostly necessary to account for the case where the user changed something such as turning SSL on/off, so we close the old pool and allow a new one to be created on demand.

### CODE REVIEW

**Comment by agilliland** [comment]
@camsaul any thoughts here?  this is g2g.

File: src/metabase/driver/generic_sql.clj [hunk 1]
```diff
@@ -89,38 +87,56 @@
...
+  [{:keys [id], :as database}]
+  (if (contains? @connection-pools id)
+    ;; we have an existing pool for this database, so use it
+    (get @connection-pools id)
+    ;; need to create a new pool
+    (let [new-pool (create-connection-pool database)]
+      ;; add the newly created pool to the cache so we maintain a reference to it
+      (reset! connection-pools (assoc @connection-pools id new-pool))
+      ;; just return the newly created pool
+      new-pool)))
```
Comment (camsaul) [inline src/metabase/driver/generic_sql.clj]: This could be written a little more concisely. Something like this should work:
```clojure
(get @connection-pools id (u/prog1 (create-connection-pool database)
                            (swap! connection-pools assoc id <>)))
```

*  `get` can return a default value so you can create the new pool there
*  `u/prog1` is the business, this is a perfect place to use it
*  prefer `swap!` instead of `reset!`

File: src/metabase/events/driver_notifications.clj [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+
+;;; ## ---------------------------------------- EVENT PROCESSING ----------------------------------------
+
+
+(defn process-driver-notifications-event
+  "Handle processing for a single event notification received on the driver-notifications-channel"
+  [driver-notifications-event]
+  ;; try/catch here to prevent individual topic processing exceptions from bubbling up.  better to handle them here.
+  (try
+    (when-let [{topic :topic database :item} driver-notifications-event]
```
Comment (camsaul) [inline src/metabase/events/driver_notifications.clj]: this is nitpicky but I would prefer putting the `try` inside of the `when-let` instead of vice versa. That way if the `when-let` doesn't execute it's body we avoid the overhead of a `try-catch` block. Otherwise we'd be wasting a few CPU cycles

File: src/metabase/events/driver_notifications.clj [hunk 3]
```diff
@@ -0,0 +1,41 @@
+(ns metabase.events.driver-notifications
+  (:require [clojure.core.async :as async]
+            [clojure.tools.logging :as log]
+            [metabase.db :as db]
+            [metabase.driver :as driver]
+            [metabase.events :as events]
+            [metabase.models.database :refer [Database]]))
+
+
+(def ^:const driver-notifications-topics
```
Comment (camsaul) [inline src/metabase/events/driver_notifications.clj]: can this be `^:private`

File: src/metabase/driver/generic_sql.clj [hunk 4]
```diff
@@ -89,38 +87,56 @@
...
+                                     :excess-timeout              (* 15 60)))))
+
+(defn- notify-database-updated
+  "We are being informed that a DATABASE has been updated, so lets shut down the connection pool (if it exists) under
+   the assumption that the connection details have changed."
+  [_ {:keys [id]}]
+  (when-let [pool (get @connection-pools id)]
+    (log/debug (u/format-color 'red "Closing connection pool for database %d ..." id))
+    ;; remove the cached reference to the pool so we don't try to use it anymore
+    (reset! connection-pools (dissoc @connection-pools id))
```
Comment (camsaul) [inline src/metabase/driver/generic_sql.clj]: Prefer `swap!` to `reset!`
```clojure
(swap! connection-pools dissoc id)
```

**Comment by camsaul** [comment]
Besides the style suggestions this looks good to me :+1:
