### PR TITLE
Fixed conditional formatting for numerical primary/foreign keys

### LINKED ISSUE #17448: Conditional formatting - equals and not equals do not work correctly for PK/PK columns
**Describe the bug**
When applying conditional formatting to a numerical column, the equals and not equals options do not work correctly. Equals and greater than as well as equals and less than work as you would expect.

Very similar to #8478 but this issue was from several years ago, so felt a new issue is better than reviving that one.

See that issue for more screenshots.

**Expected behavior**
Expect the columns to be coloured appropriately when the ID column matches the values (e.g ID 2 would turn blue etc.)

**Screenshots**
image

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Firefox 90.0.2
- Your operating system: Ubuntu 18.04
- Your databases: MySQL
- Metabase version: 0.40.2
- Metabase hosting environment: Jar file on Ubuntu
- Metabase internal database: H2 (default)

**Severity**
Important to us as we have lots of dashboard functionality awaiting this change for colour coding of key data

### PR DESCRIPTION
**Pull request by lorem--ipsum**
Closes #17448

### Description

A primery/foreign key is treated as a string in the app, value-wise, but the conditional formatting editor would erroneously consider it as a numerical column (if the underlying type was number). The conditional coloring would therefore fail, given a string value would be compared to a number.

### How to verify

 1. Set a numerical column as the primary key in a table
 2. View it in a table visualization
 3. Configure the conditional coloring to kick in for an equality (or inequality)
 4. The proper cell should be colored

### Demo

image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx [hunk 1]
```diff
@@ -426,9 +429,9 @@ const RuleEditor = ({
               ...COMMON_OPERATOR_NAMES,
               ...(isBooleanRule
                 ? BOOLEAN_OPERATIOR_NAMES
-                : isNumericRule
+                : !isKeyRule && isNumericRule
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx:432]: Wdyt about migrating nested ternaries to `ts-pattern` for better readability?

**Review by alxnddr — APPROVED** [review]
Looks good, I left one minor suggestion

File: frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx (hunk 1 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx:432]: I don't think it'll make this clearer, since ts-pattern is primarily made to work with a limited number of objects taking various shapes, and we're dealing with several variables here. I can shoehorn this into ts-pattern but I wouldn't count on it to improve readability.

**Review by alxnddr — APPROVED** [review]
Looks awesome, thanks for the refactoring!

**Comment by oisincoveney** [comment]
@metabase-bot backport release-x.52.x

**Comment by oisincoveney** [comment]
@lorem--ipsum I'm going to backport this to 52 as well - I'm fixing a few things in Conditional Formatting for the SDK, and I like to have this #54388
