### PR TITLE
Fix pivoted table crash

### LINKED ISSUE #45481: Fix table crash when going from normal to pivot mode
### Describe the bug

https://metaboat.slack.com/archives/C05MPF0TM3L/p1720460335669239

### To Reproduce

1. New -> Question -> Orders
2. Visualize
3. Notebook -> Summarize -> Count, Group by User ID, Product -> Category
4. Visualize
5. See the viz crashed

### Expected behavior

The viz should not crash

### Logs

_No response_

### Information about your Metabase installation

```JSON
v50
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/45481

Before
Screenshot 2024-07-12 at 10 46 54

After
Screenshot 2024-07-12 at 10 47 10

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/Table.tsx [hunk 1]
```diff
@@ -355,7 +356,6 @@ class Table extends Component<TableProps, TableState> {
           rows: rows.map(row => columnIndexes.map(i => row[i])),
           results_timezone,
         },
-        // cache question for performance reasons
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/visualizations/Table.tsx:358]: This is not true atm. There is a comment above "// construct a Question that is in-sync with query results" that is accurate.

**Review by uladzimirdev — APPROVED** [review]

File: e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js [hunk 2]
```diff
@@ -950,3 +953,31 @@ describe.skip("issue 25415", () => {
...
+
+describe("issue 45481", () => {
+  beforeEach(() => {
+    restore();
+    cy.signInAsNormalUser();
+  });
+
+  it("should not crash when the table viz gets automatically pivoted (metabase#45481)", () => {
+    openOrdersTable();
+    openNotebook();
```
Comment (nemanjaglumac) [inline e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js:965]: Nit:
_Do not change this now to avoid another CI cycle!_

`openOrdersTable({ mode: "notebook" });`

**Review by nemanjaglumac — APPROVED** [review]
