### PR TITLE
xray should not fail on models with filters

### LINKED ISSUE #44379: Making a model that joins a table 2 times will generate wrong x-rays
### Describe the bug

A query that is extremely wrong formed is made out of an x-ray
image

### To Reproduce

1) do new question: orders join people join people
2) save it as a model
3) x-ray the model

see the queries that are being generated

### Expected behavior

It should generate correct queries

### Logs

NA

### Information about your Metabase installation

```JSON
v50.x
```

### Severity

P1

### Additional context

NA

### PR DESCRIPTION
**Pull request by sansolovyov**
The issue: when we have a Model that has a filter *and* an aggregation, model does not contain filtered field in the end results. Our logic re-applies filters (I guess for the sake of filter tables) on x-ray cards, and this fails since you cannot filter by `created_at` if the data you have is just `id` and `count` columns.

This change skips filters for models, data is already filtered in there.

Fixes #44379

### CODE REVIEW

File: src/metabase/xrays/automagic_dashboards/combination.clj [hunk 1]
```diff
@@ -78,13 +79,16 @@
...
+                       (->> source u/the-id (str "card__")))
+        model?       (and (mi/instance-of? :model/Card source)
+                          (card/model? source))]
     (assoc ground-metric-with-dimensions
            :dataset_query {:database database
                            :type     :query
                            :query    (cond-> (assoc metric-definition
                                                     :source-table source-table)
-                                       query-filter (assoc :filter query-filter))})))
+                                       (and (not model?)
```
Comment (crisptrutski) [inline src/metabase/xrays/automagic_dashboards/combination.clj:90]: Do we not also need to check whether it has an aggregation?

**Review by crisptrutski — APPROVED** [review]
Makes sense, just a small question.

File: src/metabase/xrays/automagic_dashboards/combination.clj (hunk 1 above)
Comment (piranha) [reply src/metabase/xrays/automagic_dashboards/combination.clj:90]: Hmmm... I think the question here is - if it's a model, all the filtering has already happened inside it, so we don't add it on top. If it's a direct table - then yeah, we should carry the filtering defined in a card.
