### PR TITLE
Release migration locks during shutdown

### LINKED ISSUE #37866: SIGTERM during migration does not cleanly abort migration
### Describe the bug

When Metabase v48.3 receives a `SIGTERM` while it is running migrations (after "Migration lock is cleared. Running ${n} migrations ...", but before "Migration complete in ${x} s"), Metabase will shut down ("Metabase Shutting Down ...") but not cleanly abort the migration / clear the migration lock (subsequent runs of Metabase will report "liquibase.exception.LockException: Database has migration lock; cannot run migrations.")

Once this happened, the workaround is running the mentioned command `java -jar metabase.jar migrate release-locks`, but until this has been done Metabase cannot start again.

### To Reproduce

1. Start Metabase v47.9 and have it set up its database
2. Update to v48.3
3. Wait until you see it log "Migration lock is cleared. Running ${n} migrations ..."
4. Send `SIGTERM` (before "Migration complete")
5. Wait for Metabase to shut down
6. Start it again
7. Observe startup failure and "Database has migration lock; cannot run migrations."

### Expected behavior

Upon SIGTERM Metabase aborts the migration and clears the migration lock

### Logs

Example logs of the migration termination:
```
2024-01-18 00:14:14,102 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2024-01-18 00:14:14,104 INFO db.setup :: Verifying postgres Database Connection ...
2024-01-18 00:14:15,237 INFO db.setup :: Successfully verified PostgreSQL 14.7 application database connection. ✅
2024-01-18 00:14:15,238 INFO db.setup :: Checking if a database downgrade is required...
2024-01-18 00:14:17,567 INFO db.setup :: Running Database Migrations...
2024-01-18 00:14:17,568 INFO db.setup :: Setting up Liquibase...
2024-01-18 00:14:17,645 INFO db.setup :: Liquibase is ready.
2024-01-18 00:14:17,645 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-01-18 00:14:19,958 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2024-01-18 00:14:20,381 INFO db.liquibase :: Migration lock is cleared. Running 55 migrations ...
2024-01-18 00:14:20,690 ERROR middleware.log :: GET /api/health 503 379.9 µs (0 DB calls) 
{:status "initializing", :progress 0.3}

2024-01-18 00:14:22,920 INFO metabase.core :: Metabase Shutting Down ...
2024-01-18 00:14:22,921 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-01-18 00:14:22,995 INFO metabase.core :: Metabase Shutdown COMPLETE
```

Example logs of subsequent startup failure:
```
2024-01-18 00:14:39,308 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2024-01-18 00:14:39,310 INFO db.setup :: Verifying postgres Database Connection ...
2024-01-18 00:14:39,629 INFO db.setup :: Successfully verified PostgreSQL 14.7 application database connection. ✅
2024-01-18 00:14:39,630 INFO db.setup :: Checking if a database downgrade is required...
2024-01-18 00:14:39,922 INFO db.setup :: Running Database Migrations...
2024-01-18 00:14:39,922 INFO db.setup :: Setting up Liquibase...
2024-01-18 00:14:39,962 INFO db.setup :: Liquibase is ready.
2024-01-18 00:14:39,962 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-01-18 00:14:40,349 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2024-01-18 00:14:42,358 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__47884@347004f6: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2024-01-18 00:14:43,379 ERROR middleware.log :: GET /api/health 503 2.5 ms (0 DB calls)
{:status "initializing", :progress 0.3}
	
2024-01-18 00:14:44,365 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__47884@347004f6: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2024-01-18 00:14:46,372 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__47884@347004f6: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2024-01-18 00:14:48,378 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__47884@347004f6: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2024-01-18 00:14:50,385 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__47884@347004f6: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2024-01-18 00:14:52,393 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.LockException: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
	at metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__47884.invoke(liquibase.clj:204)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:176)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.db.liquibase$wait_for_migration_lock_to_be_cleared.invokeStatic(liquibase.clj:199)
	at metabase.db.liquibase$wait_for_migration_lock_to_be_cleared.invoke(liquibase.clj:195)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:216)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:209)
	at metabase.db.setup$fn__50134$_AMPERSAND_f__50135$fn__50136.invoke(setup.clj:80)
	at metabase.db.liquibase$fn__47860$_AMPERSAND_f__47861.invoke(liquibase.clj:131)
	at metabase.db.liquibase$fn__47860$fn__47863.invoke(liquibase.clj:124)
	at metabase.db.setup$fn__50134$_AMPERSAND_f__50135.doInvoke(setup.clj:75)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:673)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.db.setup$fn__50134$fn__50144.doInvoke(setup.clj:56)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.db.setup$fn__50172$_AMPERSAND_f__50173.invoke(setup.clj:148)
	at metabase.db.setup$fn__50172$fn__50179.invoke(setup.clj:142)
	at metabase.db.setup$fn__50182$_AMPERSAND_f__50183$fn__50186$fn__50187.invoke(setup.clj:166)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$fn__50182$_AMPERSAND_f__50183$fn__50186.invoke(setup.clj:161)
	at metabase.db.setup$fn__50182$_AMPERSAND_f__50183.invoke(setup.clj:160)
	at metabase.db.setup$fn__50182$fn__50194.invoke(setup.clj:154)
	at metabase.db$setup_db_BANG_$fn__50203.invoke(db.clj:69)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:64)
	at metabase.db$setup_db_BANG_.invoke(db.clj:55)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:113)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
	at metabase.core$init_BANG_.invokeStatic(core.clj:156)
	at metabase.core$init_BANG_.invoke(core.clj:151)
	at metabase.core$start_normally.invokeStatic(core.clj:168)
	at metabase.core$start_normally.invoke(core.clj:162)
	at metabase.core$entrypoint.invokeStatic(core.clj:201)
	at metabase.core$entrypoint.doInvoke(core.clj:195)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
2024-01-18 00:14:52,399 INFO metabase.core :: Metabase Shutting Down ...
2024-01-18 00:14:52,399 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-01-18 00:14:52,402 INFO metabase.core :: Metabase Shutdown COMPLETE
```

### Information about your Metabase installation

```JSON
Metabase v48.3 on Linux.
```

### Severity

can cause downtime, but easy workaround

### Additional context

https://metaboat.slack.com/archives/C013N8XL286/p1705573653217009

Different issue, not the problem I ran into, but similar cause: https://github.com/metabase/metabase/issues/30360

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes https://github.com/metabase/metabase/issues/37866

### Description

This change updates our shutdown hooks to avoid leaving orphaned migration locks in the database, which require manual action to resolve.

If any locks are still held, we will wait a bit to see if they are released on their own, and otherwise we force release them.

While it's not ideal to release the locks while the migrations are still running, they are at least within a transaction, and their underlying connection is also closed thereafter preventing further statements from being run.

### CODE REVIEW

File: src/metabase/db/liquibase.clj [hunk 1]
```diff
@@ -198,18 +202,18 @@
     (try
       (force-release-locks! liquibase)
       (catch Exception e
-        (log/error e (trs "Unable to release the Liquibase lock after a migration failure"))))))
```
Comment (crisptrutski) [inline src/metabase/db/liquibase.clj:201]: This code was being run in cases sitatuions to migration failures already.

Comment (crisptrutski) [reply src/metabase/db/liquibase.clj:201]: Hmm, we probably want to remove this translation - but either way we'll conflict with the outstanding the [PR to fix all the logs ](https://github.com/metabase/metabase/pull/41067#issuecomment-2039120716), so not worth another revision now.

File: src/metabase/db/liquibase.clj [hunk 2]
```diff
@@ -228,14 +232,43 @@
...
+    (if (done?)
+      :none
+      (do (log/info "Waiting for migration lock(s) to be released")
+          (wait-until done? sleep-ms timeout-ms)))))
+
+(defn release-all-locks-if-needed!
+  "Release all locks held by this process."
+  []
+  (doseq [liquibase (locked-instances)]
+    (release-lock-if-needed! liquibase)))
```
Comment (crisptrutski) [inline src/metabase/db/liquibase.clj:262]: There might be a critical issue here - by using the same `liquibase` instance as the migrations, we end up sharing the connection. I'm not sure how this would play out, but it might mean the server hangs.

I think this needs to be reworked to make sure we open new connections, but not sure how to do that in a way that supports multiple databases, as the rest of the code notionally does.

Comment (crisptrutski) [reply src/metabase/db/liquibase.clj]: Resolved this in a fairly clumsy way - I could not find a way to clone the connection as nothing seems to have held onto the password. Its as if these objects are meant to be secure.

File: src/metabase/db/liquibase.clj [hunk 3]
```diff
@@ -31,6 +31,10 @@
 
 (set! *warn-on-reflection* true)
 
+(defonce ^{:doc "The set of Liquibase instances which potentially have taken locks by this process."}
```
Comment (qnkhuat) [inline src/metabase/db/liquibase.clj:34]: In which case there is more than one liquibase instance that held a lock?

File: src/metabase/db/liquibase.clj [hunk 4]
```diff
@@ -228,14 +232,52 @@
...
+    (-> conn .getMetaData .getURL)))
+
+(defn release-concurrent-locks!
+  "Release any locks held by this process corresponding to the same database."
+  [conn-or-data-source]
+  (when-let [instances (not-empty (locked-instances))]
+    (with-liquibase [liquibase conn-or-data-source]
+      (let [url (liquibase->url liquibase)]
+        (doseq [instance instances]
+          (when (= url (liquibase->url instance))
```
[the remark this answers is not in the document]
Comment (crisptrutski) [reply src/metabase/db/liquibase.clj:270]: There's a bit of an unfortunate story here.

The liquibase namespace is agnostic as to what databases it is run against, so it's technically possible its running migrations against multiple databases - it doesn't know about our single global app db architecture, and I don't think it should - needless coupling.

In order to release the lock, we need a separate connection to the one that's tied up performing the migrations, and there's no way to "clone" the existing connection as we're unable to recover the password. For this reason we need to pass the db connection details in from our db.setup namespace.

Since we're now passing in the details for only a specific DB, I feel that we should ignore any of the (theoretical) other databases under migration. If it's only other dbs being modified there's nothing we can do about them as we don't have their connection details.

File: src/metabase/db/liquibase.clj (hunk 3 above)
Comment (crisptrutski) [reply src/metabase/db/liquibase.clj:34]: As mentioned in some of my other comments, this namespace is agnostic as to how its used. Theoretically you could have multiple "app dbs", for example when testing multiple drivers in the REPL.

File: src/metabase/db/liquibase.clj (hunk 4 above)
[the remark this answers is not in the document]
Comment (crisptrutski) [reply src/metabase/db/liquibase.clj:270]: We chatted about this offline, and decided it's worth replicating the "connection deadlock" issue this is hacking around, ideally captured as a test.

[the remark this answers is not in the document]
Comment (crisptrutski) [reply src/metabase/db/liquibase.clj:272]: So I didn't find a good way to replicate this in a test, without blowing up the test database with a long running query. I did manage to reproduce the blocking behavior by running a dev server from the CLI and sending that an actual SIGTERM though. With this "fresh" instance trick the blocking is avoided.

File: src/metabase/db/liquibase.clj [hunk 5]
```diff
@@ -228,14 +232,55 @@
...
+  "Release any locks held by this process corresponding to the same database."
+  [conn-or-data-source]
+  (when-let [instances (not-empty (locked-instances))]
+    ;; We cannot use the existing instances to clear the locks, as their connections are currently blocked.
+    ;; Since we cannot "clone" a connection (they have "forgotten" their password), we use this new conn.
+    (with-liquibase [liquibase conn-or-data-source]
+      (let [url (liquibase->url liquibase)]
+        (doseq [instance instances]
+          (when (= url (liquibase->url instance))
+            (log/warnf "Releasing liquibase lock on %s before migrations finished" url)
```
Comment (qnkhuat) [inline src/metabase/db/liquibase.clj:273]: we shouldn't log the url in any case since it might contains sensitive info.

Comment (crisptrutski) [reply src/metabase/db/liquibase.clj:273]: The password will always be stripped but I guess the username could be sensitive, will remove.

**Comment by crisptrutski** [comment]
* **#41089** <a href="https://app.graphite.dev/github/pr/metabase/metabase/41089?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @crisptrutski and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by qnkhuat — APPROVED** [review]
We talked about this over a call and it's all good now. Thanks!

File: src/metabase/db/liquibase.clj [hunk 6]
```diff
@@ -263,13 +266,23 @@
 (defn release-concurrent-locks!
   "Release any locks held by this process corresponding to the same database."
   [conn-or-data-source]
+  ;; Check whether there are Liquibase locks held by the current process - we don't want to release the database locks
+  ;; if they are held by another server, for example if this host is part of an "old" fleet shutting down while new
```
Comment (qnkhuat) [inline src/metabase/db/liquibase.clj:270]:
```suggestion
  ;; Check whether there are Liquibase locks held by the current instance - we don't want to release the database locks
  ;; if they are held by another instance, for example if this host is part of an "old" fleet shutting down while new
```

IMO we often use "instance" in this context

Comment (crisptrutski) [reply src/metabase/db/liquibase.clj:270]: I worry this could be confusing as we're also talking about Liquibase and Lock Service "instances" in the same comment - also I don't want to rerun CI for such a minor tweak 😋
