### PR TITLE
Fix initial focus of the filter modal

### LINKED ISSUE #52733: Unable to focus search input with keyboard in Filter Modal
### Describe the bug

https://github.com/user-attachments/assets/994e7f38-7601-456c-82ab-945f7a0a59f2

### To Reproduce

1. New > Question > Orders > Visualize
2. Click "Filter"
3. Try to use <kbd>Tab</kbd> to focus the search input

### Information about your Metabase installation

master, a7b8f79b031eefeff5b3b0c8f8f40bcb7fd2e005

### Severity

P3

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/52733

How to verify:
- Open a question
- Click Filter
- Press tab. You should focus the search input
- Press tab again, then tab back. You would focus the search input.

### CODE REVIEW

File: frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.tsx [hunk 1]
```diff
@@ -46,6 +46,7 @@ export function FilterModal({
         <Modal.Content>
           <Modal.Header className={S.ModalHeader} p="lg">
             <Modal.Title>{getModalTitle(groupItems)}</Modal.Title>
+            <FocusTrap.InitialFocus />
```
Comment (uladzimirdev) [inline frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.tsx:49]: I think it's useless, just removal of `aria-hidden` did the trick for me


https://github.com/user-attachments/assets/af9e2f53-52f9-4b76-9daf-795342615333

File: frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.unit.spec.tsx [hunk 2]
```diff
@@ -191,6 +191,15 @@ describe("FilterModal", () => {
     expect(Lib.filters(nextQuery, 0)).toHaveLength(3);
   });
 
+  it("should allow to focus the search input via keyboard", async () => {
+    setup({ query });
```
Comment (uladzimirdev) [inline frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.unit.spec.tsx:195]: seems e2e test would be better

File: frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.tsx (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.tsx:49]: I think the issue claims that search input itself is not focusable with tab navigation

Comment (ranquild) [reply frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.tsx:49]: Nope, for sure. `aria-hidden` was added to disable the initial focus ring.

File: frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.unit.spec.tsx (hunk 2 above)
Comment (ranquild) [reply frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.unit.spec.tsx:195]: added e2e tests

**Review by uladzimirdev — APPROVED** [review]
