### PR TITLE
Paginate caching dashboard

### LINKED ISSUE #68096: Dashboard and question caching section in tools errors in /api/search if there are too many entities with custom caching
### Describe the bug

If you define custom caching policies on too many entities then the page will fail with URI too long, as we seem to be passing the entities via a concatenation of URL parameters

### To Reproduce

1) crate 100 questions or dashboards
2) enable custom caching policies on each
3) go to settings->admin->tools->dashboard and question caching
4) see the error

### Expected behavior

Users should be able to browse that section of the app without hitting a URI too long error

### Logs

[1ee12a90-813e-4a80-b63b-b6d2f1f745c0] 2026-01-12T20:02:57-03:00 WARN org.eclipse.jetty.http.HttpParser ParameterizedMessage[messagePattern=URI is too large >{}, argCount=1, throwableProvided=false]

### Information about your Metabase installation

```JSON
v57.x
```

### Severity

P2/1

### Additional context

Image

### PR DESCRIPTION
**Pull request by nvoxland**
closes #68096
### Description

When there are a lot of questions or dashboards that are cached, the search request was erroring out due to such a long `&ids=x&ids=y...` call.

This PR switches the page to be paginated to avoid needing to fetch all the cache details at once and be such a huge page to go through as a user

Then, since we were changing the cache API anyway, made it join in the info needed by the page which was coming from the search API in the first place so we can also avoid the search call.

### Notes

Frontend code was mostly clauded, so LMK if that is close to right

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/metabase-enterprise/caching/components/StrategyEditorForQuestionsAndDashboards/StrategyEditorForQuestionsAndDashboards.tsx
Comment (iethree) [inline enterprise/frontend/src/metabase-enterprise/caching/components/StrategyEditorForQuestionsAndDashboards/StrategyEditorForQuestionsAndDashboards.tsx:1]: the code quality in this component is concerning ( I realize claude probably wrote it). Also there are some visual issues with the table, like: we usually right-align the pagination controls

Image

I think we should assign a frontend engineer to take a dedicated pass at this

File: frontend/src/metabase/api/cache-config.ts
Comment (iethree) [inline frontend/src/metabase/api/cache-config.ts:1]: adding this api to RTK is good, but I think we should also remove the legacy api provider from `services.js` while we're at it.

File: frontend/src/metabase/admin/performance/utils.tsx [hunk 1]
```diff
@@ -332,11 +332,11 @@ export const populateMinDurationSeconds = (strategy: AdaptiveStrategy) => ({
 });
 
 /** Translate a config from the API into a format the frontend can use */
-export const translateConfigFromAPI = (config: CacheConfig): CacheConfig =>
+export const translateConfigFromAPI = <T extends CacheConfig>(config: T): T =>
```
Comment (iethree) [inline frontend/src/metabase/admin/performance/utils.tsx:335]: 😳 I'm not sure this type warrants a generic

**Review by iethree — CHANGES_REQUESTED** [review]
Appreciate you taking a pass at the frontend implementation, but I think this should be a dedicated task for a frontend engineer. This particular component isn't the cleanest to begin with, and I'm afraid claude has made it even more convoluted here.

File: frontend/src/metabase/admin/performance/utils.tsx (hunk 1 above)
Comment (kevinkelleher12) [reply frontend/src/metabase/admin/performance/utils.tsx:335]: since the listCacheConfigs endpoint now returns a CacheConfigWithDetails, which extends CacheConfig, the generics are actually needed so that you get a CacheConfigWithDetails back after passing it through the translater

File: frontend/src/metabase/services.js [hunk 2]
```diff
@@ -345,10 +345,3 @@ export const ActionsApi = {
     "/api/dashboard/:dashboardId/dashcard/:dashcardId/execute",
   ),
 };
-
-export const CacheConfigApi = {
-  list: GET("/api/cache"),
-  update: PUT("/api/cache"),
-  delete: DELETE("/api/cache"),
-  invalidate: POST("/api/cache/invalidate"),
-};
```
Comment (iethree) [inline frontend/src/metabase/services.js:354]: ❤️

**Review by iethree — APPROVED** [review]
Frontend looks good! Thanks for the cleanup @kevinkelleher12

File: src/metabase/cache/api.clj [hunk 3]
```diff
@@ -114,21 +115,33 @@
 ;;
 #_{:clj-kondo/ignore [:metabase/validate-defendpoint-has-response-schema]}
 (api.macros/defendpoint :get "/"
```
Comment (edpaget) [inline src/metabase/cache/api.clj:117]: if it's not too annoying can resolve the lack of response schema in this PR (since we are changing it with the pagination).

**Review by edpaget — APPROVED** [review]
