### PR TITLE
Fix applying default values for a pinned question

### LINKED ISSUE #37831: Default values are not respected for pinned questions in collections in v48
### Describe the bug

When you add default values to the filters (normal or field filters) on a native questions, those are not taken into account in v48

### To Reproduce

1) new question -> select * from people where {{something}}
2) something is a field filter mapped to the state field, it's of type "location is"
3) add a default value, like NY
4) select a state, run the question, it will run
5) now remove the state from the filter (not from the default value). Run the question, see it failing

### Expected behavior

It should run with the default filter

### Logs

NA

### Information about your Metabase installation

```JSON
v48.x
```

### Severity

P2

### Additional context

Pretty sure this worked in v47

### PR DESCRIPTION
**Pull request by uladzimirdev**
should fix #37831 in v48, but not in master

### Description

https://github.com/metabase/metabase/pull/31891 changed the way of preparing parameters for BE - we started adding `{value: null}` if value wasn't presented.

> The point of the change is so we can differentiate between value: null (which means the no value should be applied even if it has a default) and the absence of a value key (which means we should apply the default value)

That comment made me think there could be a problem of handling cases like this on BE.

This PR adds a check whether it's collection preview or not, uses old way of calculating parameters (with value: null) for collection preview and the way introduced in #31891 for other cases.

Code in master has changed comparing to v48, so we need to provide a slightly different solution there

### CODE REVIEW

**Comment by calherries** [comment]
As discussed, this is a FE problem, the BE is behaving as designed. I've added a BE test [here](https://github.com/metabase/metabase/pull/39106) to document behaviour of the `POST /api/card/:id/query` endpoint in case this comes up again.

File: frontend/src/metabase-lib/Question.ts [hunk 1]
```diff
@@ -1090,12 +1090,13 @@ class Question {
...
 
-  // TODO: Fix incorrect Flow signature
-  parameters(): ParameterObject[] {
+  parameters({ collectionPreview } = {}): ParameterObject[] {
     return getCardUiParameters(
       this.card(),
       this.metadata(),
       this._parameterValues,
+      undefined,
+      collectionPreview,
```
Comment (oleggromov) [inline frontend/src/metabase-lib/Question.ts:1099]: Not a big fan of comments like this but this function has become ugly. Let's probably use named parameters?

File: frontend/src/metabase-lib/parameters/utils/parameter-values.js [hunk 2]
```diff
@@ -9,7 +9,27 @@ import {
...
+      ? parameters.map(parameter => {
+          return parameter.id in parameterValues
+            ? {
+                ...parameter,
+                value: parameterValues[parameter.id],
+              }
+            : parameter;
+        })
+      : parameters;
+  }
```
Comment (oleggromov) [inline frontend/src/metabase-lib/parameters/utils/parameter-values.js:31]: What I don't understand, is why if we just sent `undefined` instead of `null` as it happens now in [line 35](https://github.com/metabase/metabase/pull/39072/files#diff-8b5188e613c51e0dd17810bc8859b25544494e8b319ecdb428038048fe4b0542R35) the default value isn't picked up by the BE?

@calherries I thought that sending `undefined` means "use default" but here we send empty parameter list instead.

File: frontend/src/metabase-lib/Question.ts (hunk 1 above)
Comment (uladzimirdev) [reply frontend/src/metabase-lib/Question.ts:1099]: you did similar refactoring in master, but it's not backported to 48 (see the base branch)

Comment (uladzimirdev) [reply frontend/src/metabase-lib/Question.ts:1099]: v48 branch in "support state" atm, so I'll not do this refactoring

File: frontend/src/metabase-lib/parameters/utils/parameter-values.js (hunk 2 above)
Comment (oleggromov) [reply frontend/src/metabase-lib/parameters/utils/parameter-values.js:22]: The discussion has moved here: https://github.com/metabase/metabase/pull/39106/files#r1502499549
Not related to or blocking this PR

**Review by oleggromov — APPROVED** [review]

File: e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js [hunk 3]
```diff
@@ -55,6 +55,25 @@ const SQL_QUESTION_DETAILS = {
...
+  display: "scalar",
+  native: {
+    "template-tags": {
+      filter: {
+        type: "dimension",
+        name: "filter",
+        id: "4b77cc1f-ea70-4ef6-84db-58432fce6928",
+        "display-name": "date",
+        default: "1999-02-26~2024-02-26",
+        dimension: ["field", 35 /* PEOPLE.BIRTH_DATE */, null],
```
Comment (nemanjaglumac) [inline e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js:69]: Use `ORDERS.BIRTH_DATE` instead.

```js
import { SAMPLE_DATABASE } from "e2e/support/cypress_sample_database";

const { PEOPLE } = SAMPLE_DATABASE;
```

**Review by nemanjaglumac — CHANGES_REQUESTED** [review]
Please, never ever hard code field IDs in Cypress tests.
These are guaranteed to fail sooner or later.

We've had the mechanism to dynamically and programmatically reference those fields for years. All the data that you need lives in `e2e/support/cypress_sample_database`. It is dynamically generated each time you spin Cypress up.

**Review by nemanjaglumac — APPROVED** [review]
