### PR TITLE
Fix "remember me" checkbox on login 

### LINKED ISSUE #15223: Unchecking "Remember me" box has no effect -- close the browser and reopen, then go back to your MB instance and you're still logged in
This is on Edge (Chromium) but I don't think it's browser-specific.

1. Be logged out
1. Go to http://localhost:3000/auth/login 
2. Uncheck the "remember me" box
3. log in
4. close your browser
5. Go back to http://localhost:3000
6. You are still logged in. I'd expect to have to log in again

I'm assuming the "remember me" box is meant to tell Metabase to generate a session cookie that gets wiped when you close the browser, similar to way cookies usually work for sensitive stuff like banks. 

We create the same cookies on the backend regardless of whether that box is checked or not. I'm not sure if that checkbox corresponds to a flag passed to the auth API endpoints or not, but the backend definitely is not looking for it or doing anything different if it is there. I wrote the most recent iteration of our session cookie code on the backend, and I wasn't even aware that checkbox was there before today.

Either way, it should be easy to get this working:

1. Figure out what flag the FE client is passing in if that box is checked
2. Look for this flag and create a session cookie on the backend if it is present

### PR DESCRIPTION
**Pull request by noahmoss**
Previously, the "remember me" checkbox was sending a `remember` field to the backend in the login request, but that was being entirely ignored. This PR changes the behavior so that permanent cookies are used when `remember me` is checked, and session cookies (which expire on closing the browser) are used when the box is unchecked. Setting the `MB_SESSION_COOKIES` env var will override the checkbox and force the use of session cookies for all logins.

Also updated the docs, and fixed some indentation in session.clj which is why a lot of lines are changed there.

I went down a bit of a rabbit hole trying to figure out if it would be possible to modify the login UI when `MB_SESSION_COOKIES` is set, to hide or gray out the "Remember me" checkbox since it won't have any effect. But I couldn't quite figure out how to access the environment variable at that point in the code. If anyone has any pointers on how to do this I can update this PR to include it.

Resolves #15223

### CODE REVIEW

**Comment by camsaul** [comment]
If you want to have the value of `MB_SESSION_COOKIES` available to the frontend, you just need to make it a Setting, e.g.

```clj
(defsetting session-cookies
  "Docstring goes here"
  :type :boolean
  :visibility :public
  :default false)
```

and then the FE will have access to it via `MetabaseSettings.get('session-cookies')`

File: src/metabase/server/middleware/session.clj [hunk 1]
```diff
@@ -51,6 +51,15 @@
...
   (reduce clear-cookie (wrap-body-if-needed response) [metabase-session-cookie metabase-embedded-session-cookie]))
 
+(defn- use-permanent-cookies?
+  "Check if we should use permanent cookies for a given request, which are not cleared when a browser sesion ends."
+  [request]
+  (if (config/config-bool :mb-session-cookies)
+    ;; Disallow permanent cookies if MB_SESSION_COOKIES is set
+    false
+    ;; Otherwise check whether the user selected "remember me" during login
+    (:remember (:body request))))
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:61]: You can do `(get-in request [:body :remember])` here, or even `(-> request :body :remember)` -- I think those are a little cleaner, especially if you have > 2 keys. Not worth changing here tho unless you feel like it.

File: src/metabase/server/middleware/session.clj [hunk 2]
```diff
@@ -65,29 +74,28 @@
...
-                        ;; local dev instances) add `Secure` attribute so the cookie is only sent over HTTPS.
-                        (when (request.u/https? request)
-                          {:secure true})
-                        (when (= config/mb-session-cookie-samesite :none)
-                          (log/warn
-                           (str (deferred-trs "Session cookie's SameSite is configured to \"None\", but site is")
-                                (deferred-trs "served over an insecure connection. Some browsers will reject ")
-                                (deferred-trs "cookies under these conditions. ")
-                                (deferred-trs "https://www.chromestatus.com/feature/5633521622188032")))))]
+                         {:same-site config/mb-session-cookie-samesite
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:77]: The old indentation for `merge` was actually correct. `merge` is a function call, so if its arguments are all on new lines, they should be indented 1 space. 

2 spaces is for macros or special forms with a varargs `& body`, which includes things like `let` or `do` or `when` or `def`.

Your editor should do this for you automatically tho. Since `merge` is a core function it shouldn't even need to have an active nREPL connection to know the correct indentation. I'm not sure how to configure VIM do this correctly, but maybe @walterl can point you in the right direction

**Comment by camsaul** [comment]
It might be nice to add a test to `metabase.api.session-test` as well to make sure this works end-to-end (i.e. the `Set-Cookie` header should be different based on whether or not the API request has `:remember` in it). `mt/client-full-response` will give you the full response including the headers. You can probably just tweak the existing `login-test` a bit and have it test both with and without `:remember`

**Review by camsaul — CHANGES_REQUESTED** [review]
Overall this LGTM, but a couple of minor things:

-  Old indentation was correct
- We should add an end-to-end test for `/api/session`
- Disabling that checkbox on the FE would be a nice to have, but I'm ok with that being a follow-on PR

File: src/metabase/server/middleware/session.clj (hunk 2 above)
Comment (walterl) [reply src/metabase/server/middleware/session.clj:77]: This is actually one of the things that I haven't managed to figure out yet. Please let me know if you find a solution.

Comment (noahmoss) [reply src/metabase/server/middleware/session.clj:77]: @walterl I think I just got this behavior working by installing this plugin: https://github.com/guns/vim-clojure-static and putting `let g:clojure_align_subforms = 1` in my vimrc. Not sure if there are any unintended side effects of this plugin yet...

Comment (walterl) [reply src/metabase/server/middleware/session.clj:77]: Ah yes. I had that in my config for a while too, but it only fixes half the use cases: it either formats _all_ forms with one space (enabled), or _all_ forms with 2 spaces (disabled). The [single space indent guildeline](https://guide.clojure.style/#one-space-indent) is for _function calls_ with no args on the same line as the function. Macros taking a `& body` (e.g. `do`) should still be indented 2 spaces.

Comment (noahmoss) [reply src/metabase/server/middleware/session.clj:77]: Ah I see. Yeah, seems like `do` doesn't indent properly now.

Comment (noahmoss) [reply src/metabase/server/middleware/session.clj:77]: Here's a workaround to make specific words indent by two space: https://github.com/guns/vim-clojure-static#gclojure_fuzzy_indent-gclojure_fuzzy_indent_patterns-gclojure_fuzzy_indent_blacklist

`autocmd FileType clojure set lispwords+=do` makes `do` work properly for me.

Comment (walterl) [reply src/metabase/server/middleware/session.clj:77]: Great! I don't think I've tried that one before. :raised_hands:

**Comment by noahmoss** [comment]
Addressed comments, and changed frontend to hide the checkbox when the `session-cookies` setting is `true`:

Screen Shot 2021-05-13 at 5 09 37 PM

File: src/metabase/server/middleware/session.clj [hunk 3]
```diff
@@ -51,6 +52,15 @@
   [response]
   (reduce clear-cookie (wrap-body-if-needed response) [metabase-session-cookie metabase-embedded-session-cookie]))
 
+(defn- use-permanent-cookies?
```
Comment (camsaul) [inline src/metabase/server/middleware/session.clj:55]: This might be a little misleading, since the cookies aren't permanent. They last 2 weeks or for however long someone configures session length. Maybe `use-persistent-cookies?` would be a better name?

**Review by camsaul — APPROVED** [review]
Cool, LGTM. One note about whether the `use-permanent-cookies?` function might be more accurately named if you change its name to `use-persistent-cookies?`. I'm cool with merging either way tho

**Comment by noahmoss** [comment]
@camsaul I was actually going off of the MDN for the "permanent" terminology: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_the_lifetime_of_a_cookie
