### PR TITLE
VIZ-1281 - Fix include-current for dashboard parameters

### LINKED ISSUE #60605: Dashboard date filter label does not change when `include-current: true`
### Describe the bug

Dashboard filter: ["Previous 30 days"](https://github.com/user-attachments/assets/f8c13fbe-2bb4-4624-be29-a12db6929db9)

Query builder: ["Previous 30 days or today"](https://github.com/user-attachments/assets/71feb80b-e2dd-4aa7-a37e-2dbbced809b5)

### To Reproduce

1. Create a date dashboard filter, connect it to a card, save dashboard
2. Click the filter and use "Previous 30 days" (or any other "Previous ..." filter) 
3. Notice the label is "Previous 30 days"
4. Click to edit the filter and check "Include today"

❌ Filter label does not change

### Expected behavior

Label should change to "Previous 30 days or today" (just like in QB)

### Information about your Metabase installation

master, 7b1ac77db0b5cc35eb69b9f10faf7a90185a57d5

### Severity

P3

### PR DESCRIPTION
**Pull request by tsplude**
closes #60605
Resolves VIZ-1281

Changes include:
  - Adds support for passing the options parameter down into `lib.core/describe-temporal-interval` so that we properly show e.g. " or today" suffix on relative date parameters in dashboards

### CODE REVIEW

File: frontend/src/metabase-lib/temporal_bucket.ts [hunk 1]
```diff
@@ -55,11 +55,16 @@ export function defaultTemporalBucket(
...
 type IntervalAmount = number | "current" | "next" | "last";
 
+type TemporalIntervalOptions = {
+  "include-current"?: boolean;
+};
+
 export function describeTemporalInterval(
   n: IntervalAmount,
   unit?: TemporalUnit,
+  opts?: TemporalIntervalOptions,
```
Comment (alxnddr) [inline frontend/src/metabase-lib/temporal_bucket.ts]: nit: if include-current is the only option we can pass it right away without wrapping in `options` object

**Review by alxnddr — COMMENTED** [review]
JS part looks good, one minor comment. Could you please add specs?

File: src/metabase/lib/js.cljs [hunk 2]
```diff
@@ -823,10 +823,14 @@
...
 
   > **Code health:** Healthy"
-  [n unit]
-  (let [n    (if (string? n) (keyword n) n)
-        unit (if (string? unit) (keyword unit) unit)]
-    (lib.core/describe-temporal-interval n unit)))
+  ([n unit]
+   (let [n    (if (string? n) (keyword n) n)
+         unit (if (string? unit) (keyword unit) unit)]
+     (lib.core/describe-temporal-interval n unit)))
```
Comment (noahmoss) [inline src/metabase/lib/js.cljs]: nit
```suggestion
  ([n unit]
   (describe-temporal-interval n unit {}))
```

**Review by noahmoss — APPROVED** [review]
