### PR TITLE
Fix rendering issue with hidden columns

### LINKED ISSUE #33279: Some table columns are unable to be rendered
### Describe the bug

Some card columns aren't being able to be rendered. Without the specific column though, the card renders fine.

### To Reproduce

1. Unable to reproduce on master, but it happens on stats: https://stats.metabase.com/question/12874-cancellation-survey-responses-for-alert

### Expected behavior

Should render correctly

### Logs

_No response_

### Information about your Metabase installation

```JSON
master branch (bec9c95)
```

### Severity

Unknown

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qwef**
Closes https://github.com/metabase/metabase/issues/33279

### Description

Before rendering the html rows, we don't remove columns with visibility type of details-only, but after we do. So now we just process the rows before rendering the html. 

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Create a table/model/view
2. In the table metadata switch the visibility to details views
3. The table/model/view will still have the column, but newly created tables won't have the column
4. visualization settings swap a few a the columns around (for table.columns to be replicated in viz-settings), then trigger a pulse

### CODE REVIEW

File: src/metabase/pulse/render/body.clj [hunk 1]
```diff
@@ -214,30 +214,29 @@
...
 
-(defn- filter-rows [data table-columns rows]
-  (let [column-order      (qp.streaming/export-column-order (:cols data) table-columns)
-        keep-filtered-idx (fn [row] (if column-order
-                                      (let [row-v (into [] row)]
-                                        (for [i column-order] (row-v i)))
-                                      row))
-        filtered-rows     (map #(update % :row keep-filtered-idx) rows)]
-    filtered-rows))
+(defn- filter-rows [data viz-settings]
```
Comment (noahmoss) [inline src/metabase/pulse/render/body.clj:217]: should this be named something different if it's filtering & ordering both rows and cols?

**Review by noahmoss — APPROVED** [review]
