### PR TITLE
Fix broken deps not surfaced for missing fields in :fields (GHY-3157)

### LINKED ISSUE #69927: Broken dependencies are not surfaced for some mbql queries
### Describe the bug

Dependency analysis ignores missing-field breakage in between mbql questions

### To Reproduce

1. MBQL Q1 that translates to `select id, total, subtotal from orders`.
2.MBQL Q2 that translates to `select id, total, from Q1`.
3. MBQL Q3 that translates to `select total, subtotal from Q1`.
4. Modify Q1 removing id from `:fields` list. 

### Expected behavior

Q2 fails to execute. I'd expect broken dependency to be reflected in _Dependency diagnostics_. I.e. Q2 being broken due to missing `id` column from Q1. Q3 should (and does) work fine.

### Logs

_No response_

### Information about your Metabase installation

```JSON
`83fdafad015de7652552c57635bf4ec5b2f1daf9`
```

### Severity

P2ish

### Additional context

The [GHY-3044: Do not mark removable inactive field refs as broken](https://linear.app/metabase/issue/GHY-3044/do-not-mark-removable-inactive-field-refs-as-broken) requires not signalling breakage for inactive fields.

It seems that addressing that, the checks are too benevolent: the `metabase.lib.validate/find-bad-refs-with-source` seems to mark also the active fields as `:soft`, which are then in turn removed from findings in `metabase-enterprise.dependencies.analysis/check-query`.

### PR DESCRIPTION
**Pull request by ericnormand**
closes #69927
## Summary
- The `:soft?` marking in `find-bad-refs-with-source` was too broad — it marked **all** bad refs in `:fields` clauses as soft, even when the field was completely missing from the source (not just inactive).
- Added `(not (:active column true))` guard so only **inactive** fields in `:fields` are marked `:soft?`. Missing/unresolvable fields remain hard errors and are properly surfaced by dependency analysis.
- This preserves the GHY-3044 fix (inactive fields the QP can drop are still soft) while fixing GHY-3157 (genuinely missing fields are reported).

## Test plan
- [x] New unit test: missing card field in `:fields` is NOT marked `:soft?`
- [x] New integration test: `check-entity` on Q2 reports findings when Q1 drops a referenced field
- [x] Updated existing tests to expect missing (not inactive) fields in `:fields` to be reported as findings
- [x] Existing `find-bad-refs-with-source` tests continue to pass

Closes: GHY-3157

### CODE REVIEW

**Review by ranquild — COMMENTED** [review]
use mock metadata providers without any app db dependency, make test parallel, increment the analysis version

**Review by bshepherdson — APPROVED** [review]

File: enterprise/backend/test/metabase_enterprise/dependencies/findings_test.clj [hunk 1]
```diff
@@ -86,7 +90,7 @@
       (mt/with-premium-features #{:dependencies}
         (mt/with-temp [:model/Card {card-id :id} {:dataset_query query}]
           (is (= 1 (deps.findings/analyze-batch! :card 1)))
-          (is (= [models.analysis-finding/*current-analysis-finding-version* true]
+          (is (= [models.analysis-finding/*current-analysis-finding-version* false]
```
Comment (ranquild) [inline enterprise/backend/test/metabase_enterprise/dependencies/findings_test.clj:93]: why it's false now?

**Review by ranquild — COMMENTED** [review]
inline comment

File: enterprise/backend/test/metabase_enterprise/dependencies/findings_test.clj (hunk 1 above)
Comment (ericnormand) [reply enterprise/backend/test/metabase_enterprise/dependencies/findings_test.clj:93]: The bug was that missing fields were marked as soft problems, which were being filtered out. My fix makes it so that missing fields are not soft, unless the field was inactive (in which case, it is soft).

Comment (ericnormand) [reply enterprise/backend/test/metabase_enterprise/dependencies/findings_test.clj:93]: So it is a change in behavior of this test.

**Review by escherize — APPROVED** [review]

**Comment by escherize** [comment]
could maybe use a test for the inactive-field-still-soft case
