### PR TITLE
[Auditv2] Don't show broken move and archive buttons for analytics collections

### LINKED ISSUE #35700: Can see move and archive buttons for metabase analytics collection in the root collection
https://metaboat.slack.com/archives/C01LQQ2UW03/p1699525120236779

### Describe the bug

Metabase analytics is supposed to be a read-only collection. So we shouldn't allow users to move or archive it, although these actions do nothing, it's confusing that we can even see them.

image

After moving or archive it shows this error, but after refreshing the page, the collection is still there
image

### To Reproduce

1. Go to the root collection
2. Select **Metabase analytics** collection
3. See that you can either **Move** or **Archive** it

### Expected behavior

I shouldn't be able to select this collection with bulk actions in the first place since it's a read-only collection

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Mac OS X",
    "os.version": "14.0",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-11-12",
      "src_hash": "93a2193e3bb61e49153bcf2aa91b6ee2110b129c",
      "tag": "v1.48.0-SNAPSHOT",
      "hash": "d00c3f6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Confusing, because these actions does nothing.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/35700 again? I don't think https://github.com/metabase/metabase/pull/35894 actually addressed this, which was caused by the UI not respecting `can_write` properties on collections in the collection list view.

### Description

Checks `can_write` for collections in the collection list view to determine whether we should show the move and archive buttons

Before | After
--- | ---
Screen Shot 2023-11-30 at 8 54 45 AM | Screen Shot 2023-11-30 at 8 54 21 AM

### How to verify

Describe the steps to verify that the changes are working as expected.

1. visit the "our analytics collection"
2. click on the ... menu next to "metabase analytics"
3. do the same for "custom reports" within metabase analytics
4. see that you don't get the option to move or archive

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by npfitz — APPROVED** [review]

File: frontend/src/metabase/collections/utils.ts [hunk 1]
```diff
@@ -140,6 +144,7 @@ export function canPreviewItem(item: CollectionItem, collection: Collection) {
 export function canMoveItem(item: CollectionItem, collection: Collection) {
   return (
     collection.can_write &&
+    !isReadOnlyCollection(item) &&
```
Comment (npfitz) [inline frontend/src/metabase/collections/utils.ts:147]: That's cheeky. So previously we were only checking to see if we could write to the collection the item was in, not the item itself? If so, this probably impacted other things as well.

**Comment by npfitz** [comment]
If it's an easy add, it would be nice to have an e2e test for this sort of thing

File: frontend/src/metabase/collections/utils.ts (hunk 1 above)
Comment (iethree) [reply frontend/src/metabase/collections/utils.ts:147]: I don't think there are other situations where people have read but not write access to collections 🤔
