### PR TITLE
fix: allow scalar user-attributes

### LINKED ISSUE #61611: SDK dashboards are broken
### Describe the bug

SDK dashboards are broken
Probably something related to sandboxing

Context: https://metaboat.slack.com/archives/C063Q3F1HPF/p1753887741103769

Seems it's related to Sandboxing
The commit that breaks it https://github.com/metabase/metabase/pull/61221

### To Reproduce

https://metaboat.slack.com/archives/C063Q3F1HPF/p1753887741103769

Reproducible when running Shoppy Sample App e2e

### Expected behavior

Dashboards should work

### Logs

-

### Information about your Metabase installation

```JSON
-
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edpaget**
closes #61611
### Description

Only drop collections which cannot be converted to strings when generating database queries.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by sanex3339 — APPROVED** [review]
Works locally

File: enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj [hunk 1]
```diff
@@ -135,3 +135,13 @@
...
   (= (get-in request [:headers "x-metabase-client"]) "embedding-simple"))
+
+(defn filter-non-stringable-attributes
+  "Removes vectors and map json attribute values that cannot be turned into strings."
+  [attrs]
+  (->> attrs
+       (filter (fn [[key value]]
+                 (if (or (vector? value) (map? value) (nil? value))
+                   (log/warnf "Dropping attribute '%s' with non-stringable value: %s" (name key) value)
+                   value)))
```
Comment (johnswanson) [inline enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj]: can the value be `false`?

File: enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj [hunk 2]
```diff
@@ -135,3 +135,13 @@
   "Check if the client has indicated it is from simple embedding"
   [request]
   (= (get-in request [:headers "x-metabase-client"]) "embedding-simple"))
+
+(defn filter-non-stringable-attributes
+  "Removes vectors and map json attribute values that cannot be turned into strings."
+  [attrs]
+  (->> attrs
+       (keep (fn [[key value]]
```
Comment (johnswanson) [inline enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj:143]: nit: could just be `filter` since you're not changing the outcome in the happy-case

**Review by johnswanson — APPROVED** [review]
