### PR TITLE
Fix pivot metadata

### LINKED ISSUE #56348: Metabase 54.x doesn’t show pivot cards on dashboards
### Describe the bug

Metabase 54.x doesn’t show pivot cards 

### To Reproduce

Go to the example dashboard E-commerce Insights and then wait for "Orders according to sources per quarter"

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-04-04",
      "tag": "v0.54.1.4",
      "hash": "ffc38af"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.2 (Debian 17.2-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.5"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.6+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.6+7-LTS",
    "os.name": "Linux",
    "os.version": "6.10.14-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Can’t use pivot cards on dashboard

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/56348

After https://github.com/metabase/metabase/pull/56692 there is no observable behavior that can be tested. The goal of this PR is make sure `metadata` is always passed when constructing a `Question`.

### CODE REVIEW

File: frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx [hunk 1]
```diff
@@ -157,7 +159,7 @@ export const PublicOrEmbeddedQuestion = ({
       console.error("error", error);
       dispatch(setErrorPage(error));
     }
-  }, [card, dispatch, parameterValues, token, uuid]);
+  }, [card, metadataRef, dispatch, parameterValues, token, uuid]);
```
Comment (ranquild) [inline frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx:162]: We cannot pass `metadata` here directly, otherwise we `run` will be executed on any metadata change

File: frontend/src/metabase/services.js [hunk 2]
```diff
@@ -35,6 +35,8 @@ export const StoreApi = {
 export function maybeUsePivotEndpoint(api, card, metadata) {
   const question = new Question(card, metadata);
 
+  // we need to pass pivot_rows & pivot_cols only for ad-hoc queries endpoints
+  // in other cases the BE extracts these options from the viz settings
   function wrap(api) {
```
Comment (ranquild) [inline frontend/src/metabase/services.js:40]: This is somewhat costly operation, so let's not do it for endpoints which don't use these params

**Review by kamilmielnik — APPROVED** [review]

File: frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx (hunk 1 above)
Comment (romeovs) [reply frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx:162]: Please add this as a comment in the code.

**Review by heypoom — APPROVED** [review]
