### PR TITLE
delete old dashcards when moving question from QB view

### LINKED ISSUE #51150: No error shown when failed to move question to a dashboard
### Describe the bug

https://github.com/user-attachments/assets/2995f524-366f-462b-97f5-ce63f92b47da

### To Reproduce

Not sure about exact steps. But I had a question that is present in multiple dashboards and I tried to move it to another dashboard.

### Expected behavior

1. Error is shown to the user if request fails.
2. Maybe the request should succeed? Unclear.

### Information about your Metabase installation

master, ce493525897de71415ad3fc666c0da80eadd756d

### Severity

P2

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/51150

### Description
Passes the `delete_old_dashcards` query param when moving a question into a dashboard from the Query Builder perspective. previously, after confirming that it was okay to remove a question from other dashboards that it appears in, we would not pass this prop and the update would fail. This works as expected in the other view, of moving questions in the collection view.

Also adds an additional test to ensure the that "It should still appear here" flow of dashboard -> collection works apropriately.

### How to verify

1. Go to a question that appears in a dashboard
2. Try to move it to another dashboard
3. On the confirmation screen, click confirm
4. There should be no API errors, and the question should be in it's new home, with appearances removed from other dashboards

### Demo
chrome_jRBfmYakBx

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/MoveQuestionModal/MoveQuestionModal.tsx [hunk 1]
```diff
@@ -48,7 +48,10 @@ export const MoveQuestionModal = ({
     boolean | undefined
   >();
 
-  const handleMove = async (destination: MoveDestination) => {
+  const handleMove = async (
+    destination: MoveDestination,
+    _deleteOldDashcards?: boolean | undefined,
```
Comment (sloansparger) [inline frontend/src/metabase/query_builder/components/MoveQuestionModal/MoveQuestionModal.tsx:53]: I think you're doing this due to variable shadowing, but this reads to me as an unused variable. Can we rename it?

**Review by sloansparger — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/MoveQuestionModal/MoveQuestionModal.tsx (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/query_builder/components/MoveQuestionModal/MoveQuestionModal.tsx:53]: I'm so sorry, I scrolled past this and hit merge before seeing this comment. I'll get it renamed in another PR 🙏
