### PR TITLE
Fix can't drilldown on null date dimension record

### LINKED ISSUE #23817: Drill-through on "View these X" fails when date column is null
**Describe the bug**

When you have an aggregate, and one of the `GROUP BY` columns is `NULL`. Attempting to "View These ..." for the aggregated column creates an invalid query.

image
image
image

> Text 'Invalid date' could not be parsed, unparsed text found at index 0

**Logs**

```
error Text 'Invalid date' could not be parsed, unparsed text found at index 0 3 VisualizationError.jsx:94:12
```

```
Jul 09 13:34:28 t6 metabase[2848554]: 2022-07-09 13:34:28,152 INFO query-processor.card :: Question's average execution duration is 83.0 ms; using 'magic' TTL of 1000.0 ms 💾
Jul 09 13:34:28 t6 metabase[2848554]: 2022-07-09 13:34:28,250 INFO driver.impl :: Initializing driver :postgres...
Jul 09 13:34:29 t6 metabase[2848554]: 2022-07-09 13:34:29,622 INFO middleware.cache :: Query took 963.0 ms to run; minimum for cache eligibility is 60.0 s
Jul 09 13:34:29 t6 metabase[2848554]: 2022-07-09 13:34:29,634 DEBUG middleware.log :: POST /api/card/15/query 202 [ASYNC: completed] 1.6 s (26 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (47 total active threads) Queries in flight: 1 (0 queued); postgres DB 2 connections: 0/0 (0 threads blocked)
Jul 09 13:34:35 t6 metabase[2848554]: 2022-07-09 13:34:35,565 DEBUG middleware.log :: GET /api/card/15 200 129.7 ms (9 DB calls) App DB connections: 0/4 Jetty threads: 4/50 (3 idle, 0 queued) (47 total active threads) Queries in flight: 0 (0 queued)
Jul 09 13:34:35 t6 metabase[2848554]: 2022-07-09 13:34:35,636 INFO api.dataset :: Source query for this query is Card 14
Jul 09 13:34:36 t6 metabase[2848554]: 2022-07-09 13:34:36,036 ERROR middleware.catch-exceptions :: Error processing query: null
Jul 09 13:34:36 t6 metabase[2848554]: {:database_id 2,
Jul 09 13:34:36 t6 metabase[2848554]:  :started_at #t "2022-07-09T13:34:35.746705Z[GMT]",
Jul 09 13:34:36 t6 metabase[2848554]:  :json_query
Jul 09 13:34:36 t6 metabase[2848554]:  {:type "query",
Jul 09 13:34:36 t6 metabase[2848554]:   :query
Jul 09 13:34:36 t6 metabase[2848554]:   {:source-table "card__14",
Jul 09 13:34:36 t6 metabase[2848554]:    :filter
Jul 09 13:34:36 t6 metabase[2848554]:    ["and"
Jul 09 13:34:36 t6 metabase[2848554]:     ["=" ["field" "id" {:base-type "type/Integer"}] 3]
Jul 09 13:34:36 t6 metabase[2848554]:     ["=" ["field" "first_payment" {:base-type "type/DateTimeWithLocalTZ", :temporal-unit "day"}] "Invalid date"]]},
Jul 09 13:34:36 t6 metabase[2848554]:   :database 2,
Jul 09 13:34:36 t6 metabase[2848554]:   :parameters [],
Jul 09 13:34:36 t6 metabase[2848554]:   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
Jul 09 13:34:36 t6 metabase[2848554]:  :native nil,
Jul 09 13:34:36 t6 metabase[2848554]:  :status :failed,
Jul 09 13:34:36 t6 metabase[2848554]:  :class java.time.format.DateTimeParseException,
Jul 09 13:34:36 t6 metabase[2848554]:  :stacktrace
Jul 09 13:34:36 t6 metabase[2848554]:  ["java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2049)"
Jul 09 13:34:36 t6 metabase[2848554]:   "java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1874)"
Jul 09 13:34:36 t6 metabase[2848554]:   "--> util.date_2.parse$fn__19192$parse_with_formatter__19197$fn__19198.invoke(parse.clj:48)"
Jul 09 13:34:36 t6 metabase[2848554]:   "util.date_2.parse$fn__19192$parse_with_formatter__19197.invoke(parse.clj:41)"
Jul 09 13:34:36 t6 metabase[2848554]:   "util.date_2.parse$parse.invokeStatic(parse.clj:128)"
Jul 09 13:34:36 t6 metabase[2848554]:   "util.date_2.parse$parse.invoke(parse.clj:125)"
Jul 09 13:34:36 t6 metabase[2848554]:   "util.date_2$parse.invokeStatic(date_2.clj:39)"
Jul 09 13:34:36 t6 metabase[2848554]:   "util.date_2$parse.invoke(date_2.clj:34)"
Jul 09 13:34:36 t6 metabase[2848554]:   "util.date_2$parse.invokeStatic(date_2.clj:42)"
Jul 09 13:34:36 t6 metabase[2848554]:   "util.date_2$parse.invoke(date_2.clj:34)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$fn__40645.invokeStatic(wrap_value_literals.clj:95)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$fn__40645.doInvoke(wrap_value_literals.clj:87)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql$replace_40654__40655.invoke(wrap_value_literals.clj:120)"
Jul 09 13:34:36 t6 metabase[2848554]:   "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:47)"
Jul 09 13:34:36 t6 metabase[2848554]:   "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql$replace_40654__40655$fn__40669$fn__40670.invoke(wrap_value_literals.clj:120)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql$replace_40654__40655$fn__40669.invoke(wrap_value_literals.clj:120)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql$replace_40654__40655.invoke(wrap_value_literals.clj:120)"
Jul 09 13:34:36 t6 metabase[2848554]:   "mbql.util.match.impl$replace_in_collection$iter__20130__20134$fn__20135.invoke(impl.cljc:44)"
Jul 09 13:34:36 t6 metabase[2848554]:   "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
Jul 09 13:34:36 t6 metabase[2848554]:   "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql$replace_40654__40655$fn__40669$fn__40670.invoke(wrap_value_literals.clj:120)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql$replace_40654__40655$fn__40669.invoke(wrap_value_literals.clj:120)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql$replace_40654__40655.invoke(wrap_value_literals.clj:120)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql.invokeStatic(wrap_value_literals.clj:120)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql.invoke(wrap_value_literals.clj:106)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql_query.invokeStatic(wrap_value_literals.clj:145)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals_in_mbql_query.invoke(wrap_value_literals.clj:141)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals.invokeStatic(wrap_value_literals.clj:156)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.wrap_value_literals$wrap_value_literals.invoke(wrap_value_literals.clj:147)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$preprocess_STAR_$fn__52911.invoke(query_processor.clj:124)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$preprocess_STAR_.invokeStatic(query_processor.clj:122)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$preprocess_STAR_.invoke(query_processor.clj:117)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$fn__52919$combined_pre_process__52920$combined_pre_process_STAR___52921.invoke(query_processor.clj:204)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51367$fn__51372.invoke(resolve_database_and_driver.clj:35)"
Jul 09 13:34:36 t6 metabase[2848554]:   "driver$do_with_driver.invokeStatic(driver.clj:75)"
Jul 09 13:34:36 t6 metabase[2848554]:   "driver$do_with_driver.invoke(driver.clj:71)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51367.invoke(resolve_database_and_driver.clj:34)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47472.invoke(fetch_source_query.clj:277)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.store$initialize_store$fn__47660$fn__47661.invoke(store.clj:11)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.store$do_with_store.invoke(store.clj:38)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.store$initialize_store$fn__47660.invoke(store.clj:10)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.normalize_query$normalize$fn__51639.invoke(normalize_query.clj:22)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.constraints$add_default_userland_constraints$fn__48729.invoke(constraints.clj:53)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.process_userland_query$process_userland_query$fn__51578.invoke(process_userland_query.clj:145)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51950.invoke(catch_exceptions.clj:162)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.reducible$async_qp$qp_STAR___44199$thunk__44201.invoke(reducible.clj:100)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.reducible$async_qp$qp_STAR___44199.invoke(reducible.clj:106)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.reducible$async_qp$qp_STAR___44199.invoke(reducible.clj:91)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.reducible$sync_qp$qp_STAR___44210.doInvoke(reducible.clj:126)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$fn__52966$process_query_and_save_execution_BANG___52975$fn__52978.invoke(query_processor.clj:337)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$fn__52966$process_query_and_save_execution_BANG___52975.invoke(query_processor.clj:330)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$fn__53010$process_query_and_save_with_max_results_constraints_BANG___53019$fn__53022.invoke(query_processor.clj:349)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor$fn__53010$process_query_and_save_with_max_results_constraints_BANG___53019.invoke(query_processor.clj:342)"
Jul 09 13:34:36 t6 metabase[2848554]:   "api.dataset$run_query_async$fn__66700.invoke(dataset.clj:68)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.streaming$streaming_response_STAR_$fn__39322$fn__39323.invoke(streaming.clj:162)"
Jul 09 13:34:36 t6 metabase[2848554]:   "query_processor.streaming$streaming_response_STAR_$fn__39322.invoke(streaming.clj:161)"
Jul 09 13:34:36 t6 metabase[2848554]:   "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
Jul 09 13:34:36 t6 metabase[2848554]:   "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
Jul 09 13:34:36 t6 metabase[2848554]:   "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
Jul 09 13:34:36 t6 metabase[2848554]:  :card_id 14,
Jul 09 13:34:36 t6 metabase[2848554]:  :context :ad-hoc,
Jul 09 13:34:36 t6 metabase[2848554]:  :error "Text 'Invalid date' could not be parsed, unparsed text found at index 0",
Jul 09 13:34:36 t6 metabase[2848554]:  :row_count 0,
Jul 09 13:34:36 t6 metabase[2848554]:  :running_time 0,
Jul 09 13:34:36 t6 metabase[2848554]:  :preprocessed nil,
Jul 09 13:34:36 t6 metabase[2848554]:  :data {:rows [], :cols []}}
Jul 09 13:34:36 t6 metabase[2848554]: 2022-07-09 13:34:36,043 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 415.2 ms (17 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (3 idle, 0 queued) (50 total active threads) Queries in flight: 0 (0 queued)
```

**To Reproduce**
1. New "SQL Query" (Regular Questions will work too but this makes for an easier example)

```sql
SELECT
    users.id,
    users.first_payment,
    items.id AS item_id
FROM
    (VALUES
        (1, '2000-01-01'::TIMESTAMPTZ),
        (2, '2000-01-02'::TIMESTAMPTZ),
        (3, NULL))
        users(id, first_payment)
JOIN
    (VALUES
        (1, 1),
        (2, 2),
        (3, 2),
        (4, 2),
        (5, 3),
        (6, 3))
        items(id, user_id)
    ON items.user_id = users.id
```

The example was done with PostgreSQL

3. Save as "Example"
4. Click "Explore Results"
5. "Summarize" by "Count" group by id and first_payment.
6. Done
7. Switch to Table View.
8. Click on the cell in the "count" column where id is 3.
9. Click "View these Examples"

**Expected behavior**

It shows me the rows behind that aggregation. In this example this would be "first_payment is empty AND id is equal to 3". Even more ideally for cases where `id` is a primary key (not in this example but common for tables coming from databases) the `first_payment` filter could be excluded. This makes the generated filter simpler and more stable in case the data changes. (Imagine that the field was `last_login` which may be changing frequently.)

Instead the filter is "first_payment is Invalid date AND id is equal to 3" and the page crashes.

> There was a problem with your question
> 
> Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.
> Hide error details
> Here's the full error message
> Text 'Invalid date' could not be parsed, unparsed text found at index 0

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "en-CA",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+0-adhoc..source",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+0-adhoc..source",
    "os.name": "Linux",
    "os.version": "5.18.6",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-13",
      "tag": "v0.43.3",
      "branch": "release-x.43.x",
      "hash": "c9c7ef0"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**

It is quite annoying. It is not blocking because I can remove the filter field in most cases with one-click per null column or in the worst case switch it to an explicit "Is Empty" condition. However since this is for "exploration" it isn't a one-time cost to work around but something that I need to do every time I am exploring a new row.

**Additional context**

Maybe be the same as https://github.com/metabase/metabase/issues/11345 but in a different context.
Sounds similar to https://github.com/metabase/metabase/issues/13504 but a different error.

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes #23817

### CODE REVIEW

File: frontend/src/metabase/modes/lib/actions.js [hunk 1]
```diff
@@ -123,11 +123,18 @@ const fieldRefWithTemporalUnitForColumn = (column, unit) =>
 export function drillFilter(query, value, column) {
   let filter;
   if (isDate(column)) {
-    filter = [
-      "=",
-      fieldRefWithTemporalUnitForColumn(column, column.unit),
-      parseTimestamp(value, column.unit).format(),
-    ];
+    if (value == null) {
```
Comment (WiNloSt) [inline frontend/src/metabase/modes/lib/actions.js:126]: use double equals instead of triple equals to match the other line below
https://github.com/metabase/metabase/blob/b0baa94c100dcb950ac04fa2680a69bef929b0e3/frontend/src/metabase/modes/lib/actions.js#L142

**Review by iethree — APPROVED** [review]
👍
