### PR TITLE
Respect user-set settings during sync

### LINKED ISSUE #12574: Sync: distinguish between metadata coming from the db & user set
We allow users to overwrite some of the metadata we get from the DB such as descriptions, special type, etc. This creates a problem for subsequent syncs. Currently we avoid this problem by only setting these properties during sync if the current value is nil, but this creates bugs such as #12493. What we should do instead is track user set values separately from what comes from the db. There is already some precedence for that in `database_type` and the new `database_position` in eg. Fields.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #59123: `:visibility-type` of jsonb column is overwritten on sync
### Describe the bug

Postgres jsonb columns are unfolded by default if they have less than 50000 char length. Otherwise their visibility type is set to detail-only.

If the visibility type is set manually through table metadata page it is overwritten on next sync.

### To Reproduce

Use this to generate table

```
CREATE TABLE IF NOT EXISTS test_table (
    id INT PRIMARY KEY,
    something JSONB
);

INSERT INTO test_table (id, something) VALUES (
    1,
    jsonb_build_object(
        'field1', repeat('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ', 500),
        'field2', repeat('The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. How vexingly quick daft zebras jump! ', 500)
    )
);

INSERT INTO test_table (id, something) VALUES (
    2,
    jsonb_build_object(
        'field1', repeat('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>? ', 667),
        'field2', repeat('1234567890 The quick brown fox jumps over the lazy dog. ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz !@#$%^&*() ', 480)
    )
) ON CONFLICT (id) DO NOTHING;

SELECT 
    id,
    length(something->>'field1') as field1_length,
    length(something->>'field2') as field2_length,
    pg_column_size(something) as json_size_bytes
FROM test_table;
```

### Expected behavior

The application should respect user set visibility type and unfolding settings.

### Logs

_No response_

### Information about your Metabase installation

```JSON
54.11
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bronsa**
closes #12574 closes #59123
Closes https://linear.app/metabase/issue/SEM-5/sync-distinguish-between-metadata-coming-from-the-db-and-user-set
Closes https://linear.app/metabase/issue/SEM-377/visibility-type-of-jsonb-column-is-overwritten-on-sync

# Description 

This PR introduces a new `FieldUserSettings` model to track user-modified field metadata that would otherwise be overwritten during database sync operations. This ensures that user customizations to field properties (like descriptions, display names, semantic types, etc.) are preserved when the database schema is synced.
### Core Model & Database Schema
- **New model**: `:model/FieldUserSettings`
- **New table**: `metabase_field_user_settings` with foreign key to `metabase_field`

### API & Sync Behavior
- **Field API updates**: Modified field update endpoint to set `FieldUserSettings`
- **Sync protection**: Database sync operations now respect user-set values, no-opping on updates that would override them

## Migration Safety

- The migration is additive-only (new table, no schema changes to existing tables)
- Existing field behavior is unchanged for fields without user customizations
- Backward compatible - no breaking changes to existing APIs

### CODE REVIEW

**Review by lbrdnk — COMMENTED** [review]
_Coercion strategy_. @bronsa, would not holding `coercion_strategy` (and `effective_type`) in `metabase_field_user_settings` result in no update to coercion strategy (nil) when base type of a field changes during sync?

_Database overrides_. @thebiglabasky, (1) with this change we lose way of shutting down unfolding on database level (connection page). If field is overridden to unfold, changing the setting on database level has no effect on field. Thoughts?

_Serialization_. @bshepherdson, @piranha would you be able to help with review of serialization parts?

**Comment by bronsa** [comment]
> _Coercion strategy_. @bronsa, would not holding `coercion_strategy` (and `effective_type`) in `metabase_field_user_settings` result in no update to coercion strategy (nil) when base type of a field changes during sync?

No, it will still result in a proper update. See the test `base-type-change-will-trigger-fingerprint-and-analyze-test`. .
The behavior of the `metabase_field_user_settings` override is to overlay whatever non-nil values it holds over request updates, so if something is not present, it won't prevent anything.

**Comment by bronsa** [comment]
> _Database overrides_. @thebiglabasky, (1) with this change we lose way of shutting down unfolding on database level (connection page). If field is overridden to unfold, changing the setting on database level has no effect on field. Thoughts?

From my understanding of how the db-override of json-unfolding works, I don't think this is the case: 
It looks like the db-level json-unfolding setting is retrieved via [json-unfolding-default](https://github.com/metabase/metabase/blob/master/src/metabase/driver/common.clj#L387-L396) which is used to drive driver's implementation of [database-supports?](https://github.com/metabase/metabase/blob/master/src/metabase/driver/postgres.clj#L81-L83)` for  :nested-field-column`, so it will still disable it regardless of the field-level setting of `json-unfolding`. I believe this is captured by the `json-unfolding-initially-true-test` test

**Review by lbrdnk — COMMENTED** [review]
_Coercion_. My observation:

1. Using `string-nums-db` I've set coercion strategy to string->float.
2. Then connected to string-nums-db `alter table string_nums alter column int_col type int using int_col::integer;`
3. Do sync.
4. Check the contents of field as seen through toucan:

```
(toucan2.core/select :model/Field :name "int_col")
[(toucan2.instance/instance
  :model/Field
  {:description nil,
   :database_type "int4",
   :semantic_type nil,
   :table_id 24,
   :coercion_strategy :Coercion/String->Float,
   :database_indexed nil,
   :name "int_col",
   :fingerprint_version 5,
   :has_field_values :auto-list,
   :settings nil,
   :caveats nil,
   :fk_target_field_id nil,
   :updated_at #t "2025-06-17T10:39:58.146944Z",
   :custom_position 0,
   :effective_type :type/Float,
   :active true,
   :nfc_path nil,
   :parent_id nil,
   :id 251,
   :last_analyzed #t "2025-06-17T10:39:58.146944Z",
   :database_partitioned nil,
   :database_is_auto_increment false,
   :json_unfolding false,
   :position 1,
   :visibility_type :normal,
   :preview_display true,
   :display_name "Int Col",
   :database_position 1,
   :database_required false,
   :fingerprint
   {:global {:distinct-count 5, :nil% 0.0},
    :type #:type{:Number {:min 0.0, :q1 0.75, :q3 3.25, :max 4.0, :sd 1.5811388300841898, :avg 2.0}}},
   :created_at #t "2025-06-17T10:28:52.554125Z",
   :base_type :type/Integer,
   :points_of_interest nil})]
```

The field contains coercion strategy and modified effective type with the new base type. 

I assume the query with this field completes successfully thanks to [condition](https://github.com/metabase/metabase/blob/21c90d92c3ee9b7987219d69172c4593a5b604b6/src/metabase/driver/sql/query_processor.clj#L767) in `cast-field-if-needed`.

_Database level unfolding_. Thanks for the explanation. That is right. While checking locally I've tested without triggering sync that disables the unfolding.

**Comment by bronsa** [comment]
> _Coercion_. My observation:
> [..]

Ah, apologies for misunderstanding you. I see your point now. That is indeed wrong, thanks for spotting and testing. I will follow up with a fix and an additional test case for this scenario

**Review by lbrdnk — COMMENTED** [review]
One more thing that I'm unsure of is the nature of the change to the behavior of `t2/update! :model/Field`.

With this change merged we'd get to the state where `t2/update!` alone will be noop for fields of `metabase_field` that have user set values in `metabase_field_user_settings`.

Hence for an update to take effect the new table would have to be modified first.

Are we sure there are no other places in code that should be overwriting user set values?

I'd like to have opinion of someone with clearer picture of the "greater plan" before we get the PR in.

@dpsutton, is it ok to make update! noop in this specific case?

**Comment by bronsa** [comment]
> One more thing that I'm unsure of is the nature of the change to the behavior of `t2/update! :model/Field`.
> 
> With this change merged we'd get to the state where `t2/update!` alone will be noop for fields of `metabase_field` that have user set values in `metabase_field_user_settings`.
> 
> Hence for an update to take effect the new table would have to be modified first.
> 
> Are we sure there are no other places in code that should be overwriting user set values?
> 
> I'd like to have opinion of someone with clearer picture of the "greater plan" before we get the PR in.
> 
> @dpsutton, is it ok to make update! noop in this specific case?

I agree this approach needs to be agreed upon and it does come with certain drawbacks. I'm happy to explore other approaches if anybody has better proposals. For what it's worth, that was an intentional consideration I took when coming up with this approach, because in my opinion, updates to user settings should be explicit and intentional. 

Making `t2/update!` a noop when user-set values exist helps ensure we don't unintentionally override user intent during syncs or automated updates, and when we need to do that, we do so explicitely. 

I had explored an alternative where we’d transparently apply updates by syncing changes via FieldUserSettings, but I ran into issues with t2’s `after-update` not providing the full pre-update model. More importantly, that approach risked masking accidental overrides, which IMO is what we're trying to prevent.

**Review by sansolovyov — APPROVED** [review]
seems fine to me from serialization point of view

took me way more time than I care to admin to figure out it's practically a copycat of FieldValues setup :-)

**Comment by bronsa** [comment]
> seems fine to me from serialization point of view
> 
> took me way more time than I care to admin to figure out it's practically a copycat of FieldValues setup :-)

it is indeed, apologies I should've left a comment about it for ease of review

File: src/metabase/warehouse_schema/models/field.clj [hunk 1]
```diff
@@ -131,17 +136,45 @@
...
-  (u/prog1 field
-    (when (false? (:active (t2/changes <>)))
-      (t2/update! :model/Field {:fk_target_field_id (:id field)} {:semantic_type      nil
-                                                                  :fk_target_field_id nil}))))
+  (when (false? (:active (t2/changes field)))
+    (ensure-field-user-settings-exist-for-fk-target-field field)
+    (let [k {:fk_target_field_id (:id field)}
+          upds {:semantic_type      nil
+                :fk_target_field_id nil}]
+      (t2/update! :model/Field k upds)
```
Comment (edpaget) [inline src/metabase/warehouse_schema/models/field.clj:169]: if this is updating the `field` passed to `before-update` you can `assoc` the keys to change into the return value and that will add them to the update.

Comment (bronsa) [reply src/metabase/warehouse_schema/models/field.clj:169]: it isn't, this is triggering updates to related fields (this is preexisting behavior)

**Review by lbrdnk — APPROVED** [review]
The concern I had about need to update new table prior updating metabase_field does not seem to be shared as per https://metaboat.slack.com/archives/CKZEMT1MJ/p1750684455798959.

Hence LGTM.
