### PR TITLE
Fix caching of postgres domains in arrays

### LINKED ISSUE #55301: Postgres arrays break when cached
### Describe the bug

With a custom text type embedded in an array, we're seeing bad data displayed when loaded from a cache.
Image

### To Reproduce

1. Create a postgres custom domain with `CREATE DOMAIN my_domain AS text CHECK ( length(value) BETWEEN 1 AND 299 );`
2. Save a question that uses that to create an array: `SELECT array_agg('foo'::my_domain) AS foo`
3. Update caching rules so you'll get the cached result (e.g. set to duration 1hr)
4. Load the question and see `[{"nippy/unthawable":{"type":"serializable","cause":"quarantined","class-name":"org.postgresql.util.PGobject","content":"0xACED0005"}}]`

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
Running v1.53.6.2 and Postgres 16.
```

### Severity

Low since rerunning fixes it

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/55301

### Description

Adds custom nippy handling for `PGobjects` so that they are cached properly.

### How to verify

See repro steps in issue. The question should load properly now. 

### Demo

todo

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by metamben — APPROVED** [review]
I believe this solves the issue. Could we have a test that more directly repros the issue?

File: test/metabase/query_processor/middleware/cache_test.clj [hunk 1]
```diff
@@ -345,6 +347,47 @@
...
+                    cached-result   (qp/process-query query)]
+                (is (= [["foo"]]
+                       (mt/rows original-result)))
+                (is (= [["foo"]]
+                       (mt/rows cached-result)))
+                (is (=? {:cache/details {:stored true
+                                         :hash   some?}
+                         :row_count     1
+                         :status        :completed}
+                        (dissoc original-result :data)))
```
Comment (metamben) [inline test/metabase/query_processor/middleware/cache_test.clj]: Why is `dissoc` needed?

File: test/metabase/query_processor/middleware/cache_test.clj [hunk 2]
```diff
@@ -345,6 +347,47 @@
...
+                (is (=? {:cache/details {:cached     true
+                                         :updated_at #t "2025-02-06T00:00:00.000Z[UTC]"
+                                         :hash       some?}
+                         :row_count     1
+                         :status        :completed}
+                        (dissoc cached-result :data)))
```
Comment (metamben) [inline test/metabase/query_processor/middleware/cache_test.clj]: And here?

**Review by metamben — APPROVED** [review]

File: test/metabase/query_processor/middleware/cache_test.clj (hunk 1 above)
Comment (rileythomp) [reply test/metabase/query_processor/middleware/cache_test.clj]: I just copied it from the existing cache tests, but you're right it's not needed with `=?`
