### PR TITLE
Unverify cards when they are edited

### LINKED ISSUE #17886: Question verification remains even after someone edits the question
**Describe the bug**
The verification on a question changes, even after someone changes the question.

**Logs**
```
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:43-04:00 DEBUG metabase.server.middleware.log GET /api/setting 200 873.7 µs (0 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (5 idle, 0 queued) (71 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:43-04:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 5.3 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (5 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:43-04:00 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 5.5 ms (11 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (5 idle, 0 queued) (73 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:44-04:00 DEBUG metabase.server.middleware.log GET /api/database 200 2.5 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:44-04:00 DEBUG metabase.server.middleware.log GET /api/automagic-dashboards/database/1/candidates 200 5.9 ms (6 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:47-04:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 3.6 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:47-04:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 1.5 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:47-04:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 200 26.6 ms (4 DB calls) App DB connections: 1/7 Jetty threads: 6/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:47-04:00 DEBUG metabase.server.middleware.log GET /api/collection/root/items 200 19.3 ms (6 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:48-04:00 DEBUG metabase.server.middleware.log GET /api/card/47 200 8.7 ms (10 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:48-04:00 DEBUG metabase.server.middleware.log GET /api/alert/question/47 200 657.4 µs (1 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:48-04:00 DEBUG metabase.server.middleware.log GET /api/table/2/query_metadata 200 7.1 ms (11 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:48-04:00 DEBUG metabase.server.middleware.log GET /api/table/3/query_metadata 200 7.2 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:48-04:00 DEBUG metabase.server.middleware.log GET /api/table/1/query_metadata 200 4.9 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (5 idle, 0 queued) (77 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:48-04:00 DEBUG metabase.server.middleware.log POST /api/card/47/query 202 [ASYNC: completed] 53.4 ms (19 DB calls) App DB connections: 1/7 Jetty threads: 4/50 (5 idle, 0 queued) (79 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/1 (0 threads blocked)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:54-04:00 DEBUG metabase.server.middleware.log GET /api/user/1 200 1.1 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (79 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:54-04:00 DEBUG metabase.server.middleware.log GET /api/user 200 2.3 ms (4 DB calls) App DB connections: 1/7 Jetty threads: 6/50 (5 idle, 0 queued) (79 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:51:54-04:00 DEBUG metabase.server.middleware.log GET /api/revision 200 11.1 ms (7 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (79 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:06-04:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 63.7 ms (15 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (5 idle, 0 queued) (81 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/1 (0 threads blocked)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:12-04:00 INFO metabase.api.card Card results metadata passed in to API is VALID. Thanks!
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:12-04:00 DEBUG metabase.server.middleware.log PUT /api/card/47 202 [ASYNC: completed] 26.2 ms (23 DB calls) App DB connections: 1/7 Jetty threads: 4/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:12-04:00 DEBUG metabase.server.middleware.log GET /api/alert/question/47 200 624.5 µs (1 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:22-04:00 DEBUG metabase.server.middleware.log GET /api/revision 200 8.5 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 1.8 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 4.1 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log GET /api/database 200 1.9 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log GET /api/card/47 200 5.3 ms (10 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log GET /api/alert/question/47 200 726.3 µs (1 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log GET /api/table/2/query_metadata 200 6.4 ms (11 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log GET /api/table/3/query_metadata 200 9.4 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log GET /api/table/1/query_metadata 200 8.1 ms (8 DB calls) App DB connections: 0/7 Jetty threads: 7/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 1.4 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (82 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:35-04:00 DEBUG metabase.server.middleware.log POST /api/card/47/query 202 [ASYNC: completed] 56.3 ms (19 DB calls) App DB connections: 1/7 Jetty threads: 4/50 (5 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/1 (0 threads blocked)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:42-04:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 45.8 ms (15 DB calls) App DB connections: 1/7 Jetty threads: 4/50 (5 idle, 0 queued) (85 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/1 (0 threads blocked)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:45-04:00 INFO metabase.api.card Card results metadata passed in to API is VALID. Thanks!
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:45-04:00 DEBUG metabase.server.middleware.log PUT /api/card/47 202 [ASYNC: completed] 24.7 ms (23 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (5 idle, 0 queued) (83 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:52:45-04:00 DEBUG metabase.server.middleware.log GET /api/alert/question/47 200 563.0 µs (1 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (5 idle, 0 queued) (83 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:53:17-04:00 DEBUG metabase.server.middleware.log GET /api/setting 200 902.9 µs (0 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (3 idle, 0 queued) (83 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:53:17-04:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 5.9 ms (2 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (3 idle, 0 queued) (83 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:53:17-04:00 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 3.3 ms (11 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (3 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
[def0f5a8-a4f1-4ef7-978e-85b94a06a580] 2021-09-14T15:53:18-04:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 1.3 ms (1 DB calls) App DB connections: 0/7 Jetty threads: 5/50 (3 idle, 0 queued) (84 total active threads) Queries in flight: 0 (0 queued)
```

**To Reproduce**
1. Create a question with a filter.
2. Using an Admin account, verify the question.
3. Log in as a different user and change the question by removing the filter. Save the question, and when prompted, select overwrite the question.
4. The verification remains, even though the question is different.

**Expected behavior**
When a question changes, it should need to be verified again.

**Screenshots**
image

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Mac OS X",
    "os.version": "11.5",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-09-14",
      "tag": "vUNKNOWN",
      "branch": "master",
      "hash": "b7d52e5"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Unexpected behavior that renders verification moot. Changes to questions should affect their verification status, otherwise verification is more akin to an official question, as opposed to confirmation that someone has vetted the validity of the query.

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes #17886

Verified questions lose verification status when edited to prevent hijinks.

from maz in slack:
##### Should not remove verification:
 - Moving to another collection
 - Pinning/unpinning
 - Adding/removing an alert on the question
 - Turning sharing on the question on/off

##### Should remove verification:
 - Editing the query
 - Editing the visualization or viz settings
 - Editing the title or description

This really just identifies when not to remove verification, otherwise
does remove verification. Alerts are not related to questions through
the api so no worries there. Everything else is just excluding
attributes from the diff calculation.

In tests, went perhaps a bit haywire with the macrolet, allowing to
define macros inline rather than farther away from the call site. Used
twice:
- once to optionally add in moderation review into the with-temp. This
macro is handy to ensure we always have a fresh state of card and don't
have leftover changes or verifications. Has to be a macro since i want
to dynamically change whether there are verifications in the with-temp*
vector binding
- a way to more easily reduce repetition when asserting something is
verified, do an action, and assert it is still verified

I'm like 70/30 in favor of this style. Happy to be convinced to change but the tests really just move all of the boilerplate above and focus just on the behavior and assertion.

### CODE REVIEW

File: src/metabase/api/card.clj [hunk 1]
```diff
@@ -415,6 +418,46 @@
...
+  [card]
+  (-> card :moderation_reviews first :status #{"verified"} boolean))
+
+(defn- changed?
+  "Return whether there were any changes other than ignored values.
+
+  returns false because changes to collection_id are ignored:
+  (changed? {:collection_id 1 :description \"foo\"}
+            {:collection_id 2}
+            {:ignore #{:collection_id}})
```
Comment (camsaul) [inline src/metabase/api/card.clj:433]: We don't have Marginalia or Cljdoc set up rn but if we did (and we probably should get one of them set up at some point) it will format docstrings as Markdown. So it's good to add a newline and then indent code examples in docstrings four spaces so they'd be interpreted as code blocks

File: src/metabase/api/card.clj [hunk 2]
```diff
@@ -415,6 +418,46 @@
...
+                                                                        (name x)
+                                                                        x))
+                                                              card))
+        before               (apply dissoc card-before ignore)
+        after                (apply dissoc updates ignore)
+        [_ changes-in-after] (data/diff (prepare before) (prepare after))]
+    (boolean (seq changes-in-after))))
+
+
+
```
Comment (camsaul) [inline src/metabase/api/card.clj:451]: extra newlines?

**Review by camsaul — APPROVED** [review]
WFM

**Comment by rlotun** [comment]
hi @jeff-bruemmer a favor - can you verify this closes the bug you opened?
