### PR TITLE
Fix ultra wide tooltips (closes #52199)

### LINKED ISSUE #52199: Ultra wide tooltips
### Describe the bug

Image

### To Reproduce

To see this in the wild: go to https://stats.metabase.com/dashboard/1887 and inspect tooltips in the "Dashboards" section

----

1. Create a new dashboard and save it
2. Add this description to it:
```
This is a very very very very very very very very very very long dashboard description. Boy, I sure hope it does not overflow the screen when it's displayed in a tooltip. The only thing that would make it worse is if the text didn't wrap. 
```
3. Edit dashboard
4. Add a link to this very dashboard
5. Save dashboard
6. Change viewport width to 1000px or less
7. Hover the "i" icon in the link

### Expected behavior

1. Tooltip does not overflow the viewport
2. Text is wrapped into multiple lines - tooltip should have a reasonable `max-width` set

### Information about your Metabase installation

master, 304e1077ee9c47336b3766e0665b05eea5ba7fa3

### Severity

P3

### PR DESCRIPTION
**Pull request by lorem--ipsum**
Closes #52199

### Description

Avoids that longs description in tooltips spill over the viewport's width:
Image

### How to verify

1. Create a new dashboard and save it
2. Add this description to it:
```
This is a very very very very very very very very very very long dashboard description. Boy, I sure hope it does not overflow the screen when it's displayed in a tooltip. The only thing that would make it worse is if the text didn't wrap. 
```
3. Edit dashboard
4. Add a link to this very dashboard
5. Save dashboard
6. Change viewport width to 1000px or less
7. Hover the "i" icon in the link

### CODE REVIEW

File: frontend/src/metabase/ui/components/icons/Icon/Icon.tsx [hunk 1]
```diff
@@ -10,6 +10,7 @@ import type { IconName } from "./icons";
 import { Icons } from "./icons";
 
 const defaultSize = 16;
+const multiline = true;
```
Comment (rafpaf) [inline frontend/src/metabase/ui/components/icons/Icon/Icon.tsx:13]: Should this be a prop?

File: frontend/src/metabase/ui/components/icons/Icon/Icon.tsx [hunk 2]
```diff
@@ -39,7 +40,17 @@ export const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
     />
   );
 
-  return tooltip ? <Tooltip label={tooltip}>{icon}</Tooltip> : icon;
+  return tooltip ? (
+    <Tooltip
+      style={{ whiteSpace: multiline ? "unset" : "nowrap" }}
+      label={tooltip}
+      data-testid={`${multiline ? "wrapped-" : ""}tooltip`}
```
Comment (rafpaf) [inline frontend/src/metabase/ui/components/icons/Icon/Icon.tsx:47]: `expect(tooltip).toHaveStyle` seems like a smart way to go - great find. Is the testid still useful here?

File: frontend/src/metabase/visualizations/visualizations/LinkViz/EntityDisplay.tsx [hunk 3]
```diff
@@ -21,13 +21,13 @@ export const EntityDisplay = ({
   return (
     <EntityDisplayContainer>
       <LeftContainer>
-        <Icon color={color("brand")} name={getSearchIconName(entity)} />
+        <Icon color="var(--mb-color-brand)" name={getSearchIconName(entity)} />
```
Comment (rafpaf) [inline frontend/src/metabase/visualizations/visualizations/LinkViz/EntityDisplay.tsx:24]: Cheers for updating the legacy code here

File: frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx [hunk 4]
```diff
@@ -201,6 +202,46 @@ describe("LinkViz", () => {
   });
 
   describe("entity links", () => {
+    it("wraps the dashboard's description", async () => {
+      const longDescription =
+        "This is a very very very very very very very very very very long dashboard description. Boy, I sure hope it does not overflow the screen when it's displayed in a tooltip. The only thing that would make it worse is if the text didn't wrap.";
```
Comment (rafpaf) [inline frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx:207]: 😆

File: frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx [hunk 5]
```diff
@@ -201,6 +202,46 @@ describe("LinkViz", () => {
...
+
+      renderWithProviders(
+        <LinkViz
+          dashboard={createMockDashboard({})}
+          dashcard={card}
+          isEditing={false}
+          settings={card.visualization_settings as LinkCardVizSettings}
+          onUpdateVisualizationSettings={jest.fn()}
+        />,
+      );
```
Comment (rafpaf) [inline frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx:231]: As you've probably seen, our test files usually have a `setup` function that creates the component, and that function calls `render` or `renderWithProviders`. Would it be useful to re-use the setup function here?

**Review by rafpaf — CHANGES_REQUESTED** [review]
`toHaveStyle` looks like a good approach. I think this is pretty close to mergeable apart from some small issues.

(I find the red 'Request changes' stop sign kind of intense, like a big X in red ink, and I wish there were an amber 'Almost ready' button.)

File: frontend/src/metabase/ui/components/icons/Icon/Icon.tsx (hunk 2 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/ui/components/icons/Icon/Icon.tsx:47]: So, it turns out the test failed on CI, not sure why, so I changed it and it now uses the test id.

File: frontend/src/metabase/ui/components/icons/Icon/Icon.tsx (hunk 1 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/ui/components/icons/Icon/Icon.tsx:13]: We've talked with @alxnddr and I understood that we want the Tooltip to be multiline by default, everywhere. If needed further on we can indeed make this a prop I suppose?

File: frontend/src/metabase/ui/components/icons/Icon/Icon.tsx [hunk 6]
```diff
@@ -39,7 +40,17 @@ export const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
     />
   );
 
-  return tooltip ? <Tooltip label={tooltip}>{icon}</Tooltip> : icon;
+  return tooltip ? (
+    <Tooltip
+      style={{ whiteSpace: multiline ? "unset" : "nowrap" }}
```
Comment (rafpaf) [inline frontend/src/metabase/ui/components/icons/Icon/Icon.tsx:45]: At least to my way of thinking, this line seems to support a non-multiline code path - but if I understand correctly, there isn’t one, and doesn’t need to be one. That might confuse someone, so I’d think about either going all-in with multiline (don’t even make it a variable) or making it a prop with a default value. 

This isn’t a blocker, though.

**Review by rafpaf — APPROVED** [review]
Approved with one new comment

File: frontend/src/metabase/ui/components/icons/Icon/Icon.tsx (hunk 6 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/ui/components/icons/Icon/Icon.tsx]: you're right, this'll be cleaner

File: frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx [hunk 7]
```diff
@@ -201,6 +202,43 @@ describe("LinkViz", () => {
   });
 
   describe("entity links", () => {
+    it("wraps the dashboard's description", async () => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx:205]: 1. :x: This test does not have assertions for what was broken - please turn it into actual repro
2. We add `(metabase#1234)` tags to test names that are repros ([like this](https://github.com/metabase/metabase/blob/92d615073a3ba31710e26be9f2e83141352d1d1c/frontend/src/metabase/visualizations/components/ChartCaption.unit.spec.tsx#L71))

File: frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx [hunk 8]
```diff
@@ -201,6 +202,43 @@ describe("LinkViz", () => {
...
+
+      await userEvent.hover(infoIcon);
+
+      await waitFor(() => {
+        expect(screen.getByText(longDescription)).toBeInTheDocument();
+      });
+
+      expect(screen.getByText(longDescription)).toBe(
+        screen.getByTestId("wrapped-tooltip"),
+      );
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx:239]: This is a bit unexpected to see, we always assert this the other way around:

``` suggestion
      expect(screen.getByTestId("wrapped-tooltip")).toHaveTextContent(
        longDescription,
      );
```

File: frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx [hunk 9]
```diff
@@ -201,6 +202,43 @@ describe("LinkViz", () => {
...
+        link: {
+          entity: {
+            id: 1,
+            db_id: 20,
+            name: "Table Une",
+            model: "table",
+            description: longDescription,
+          },
+        },
+      } as LinkCardVizSettings;
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx:219]: Please avoid type casting:

```suggestion
      const settings: LinkCardVizSettings = {
        virtual_card: createMockVirtualCard(),
        link: {
          entity: {
            id: 1,
            db_id: 20,
            name: "Table Une",
            model: "table",
            description: longDescription,
          },
        },
      };
```

File: frontend/src/metabase/ui/components/icons/Icon/Icon.tsx [hunk 10]
```diff
@@ -39,7 +39,17 @@ export const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
     />
   );
 
-  return tooltip ? <Tooltip label={tooltip}>{icon}</Tooltip> : icon;
+  return tooltip ? (
+    <Tooltip
+      style={{ whiteSpace: "unset" }}
```
Comment (kamilmielnik) [inline frontend/src/metabase/ui/components/icons/Icon/Icon.tsx:44]: We can do better than [this](https://github.com/user-attachments/assets/f9758964-9059-4f50-84eb-89dc835bf233).
@lorem--ipsum did you consider using `max-width` as suggested in the issue report?

**Review by kamilmielnik — COMMENTED** [review]
:x: repro is missing key assertions

File: frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx (hunk 7 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx:205]: 1. should this be an e2e test then? Alternatively we cant check that a max-width has indeed been set on the component, but that would not really test the issue (whatever the max-width is, there can always be a smaller viewport I guess)
 2. yep, didn't know that, will change

File: frontend/src/metabase/ui/components/icons/Icon/Icon.tsx (hunk 10 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/ui/components/icons/Icon/Icon.tsx:44]: I have considered it, yes, but I was unsure what value to pick for that, as it is dependant on the context, which is why I favored this approach.

File: frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx (hunk 7 above)
Comment (kamilmielnik) [reply frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx:205]: > should this be an e2e test then? 

Yes, we need to assert that tooltip does not overflow the viewport - we can't use unit tests for this as elements don't have dimensions there.

>  Alternatively we cant check that a max-width has indeed been set on the component, but that would not really test the issue (whatever the max-width is, there can always be a smaller viewport I guess)

Yeah, `max-width` assertion should be treated as "extra" - the main problem is the overflow.

File: frontend/src/metabase/ui/components/icons/Icon/Icon.tsx (hunk 10 above)
Comment (kamilmielnik) [reply frontend/src/metabase/ui/components/icons/Icon/Icon.tsx:44]: Designers are very helpful with that, and often they'll have better ideas on what the expected result could be :)
