### PR TITLE
Include subpath to the URL during downloading question results

### LINKED ISSUE #33244: Download results (.csv, .json, .xlsx) request does not include subpath when deploying on subpath
### Describe the bug

We have deployed Metabase on subpath behind nginx for example domain:
`https://example.com/metabase/`.

When we want to download results of a question or table of database, requests are sent to
`https://example.com` 
instead of 
`https://example.com/metabase/`.

I have set `MB_SITE_URL`.

Request full url:
`https://sub.example.com/api/card/1/query/csv`
Expected request url:
`https://sub.example.com/subpath/api/card/1/query/csv`

### To Reproduce

1. Deploy Metabase on subpath
2. Create a question
3. Click "Download full result" Icon
4. Get a 404 error.

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```
- Chrome updated
- Ubuntu 22.04
- Postgres
- Metabase: latest version
- Docker community edition self-hosted
- Internal database: Postgres
```

### Severity

Blocking my usage

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/33244

### Description

Subpath (deploying the app at some route like https://website.com/metabase) is not a standard way of handing URL requests, so urls starting with `/` e.g. `/api/card/3` will be calculated by browser starting from the origin or `https://website.com`, which is not correct as metabase handles BE requests using URLs including subpath (`/metabase/api/card/3`).

To bypass this browser behaivour we identify the deployment location (subpath or not) and manually build links to the downloading resources, this PR covers question results

### How to verify

1. run your local instance (frontend and backend separately), go to the question and download results (csv, json, xlsx) - make sure they show correct result
2. go to admin settings -> change metabase URL from `localhost:3000` to `localhost:9090/metabase/`
3. stop your frontend server, keep backend server running
4. build js files with `yarn build`, open `localhost:3000` and make sure js files are loaded
5. clone https://github.com/iethree/metabase-subpath-proxy: e.g. `cd .. && git clone git@github.com:iethree/metabase-subpath-proxy.git`
6. go to the  e.g. `cd ./metabase-subpath-proxy` and run `docker-compose up` (or `docker compose up`)
7. now open `localhost:9090/metabase/` - notice `/` at the end of the line, it's required
8. go to the question and try to download results, make sure they show correct results

### Demo

https://www.loom.com/share/5e3a325deb2a4d78be81b39d44b18bf9

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/query_builder/actions/downloading.ts [hunk 1]
```diff
@@ -68,7 +68,9 @@ const getDatasetParams = ({
   if (isSecureDashboardEmbedding) {
     return {
       method: "GET",
-      url: `/api/embed/dashboard/${token}/dashcard/${dashcardId}/card/${cardId}/${type}`,
+      url: Urls.getURLIncludingSubpath(
+        `/api/embed/dashboard/${token}/dashcard/${dashcardId}/card/${cardId}/${type}`,
```
Comment (uladzimirdev) [inline frontend/src/metabase/query_builder/actions/downloading.ts:72]: I'm not 100% sure about it

**Review by dragonsahead — APPROVED** [review]
Approved from the functional side

**Review by ranquild — CHANGES_REQUESTED** [review]
Please use the same approach we use with `api.js` for all other requests:
- https://github.com/metabase/metabase/blob/a06e640e97efe03646a5c98bab4a8ba3af2a20dc/frontend/src/metabase/lib/api.js#L240
- https://github.com/metabase/metabase/blob/7820266e7d551b038df60b5e8317b16b7ed7a90e/frontend/src/metabase/app.js#L58

You'd probably need to modify it only here https://github.com/metabase/metabase/blob/1efa6c6f000cb4bd38065563176c35ea0027c865/frontend/src/metabase/query_builder/actions/downloading.ts#L136

**Comment by paoliniluis** [comment]
@Tony-metabase can you check this out?
@uladzimirdev I'm leaving on vacations and I need this to be in 47.2

File: frontend/src/metabase/query_builder/actions/downloading.ts [hunk 2]
```diff
@@ -127,15 +127,20 @@ const getDatasetParams = ({
   };
 };
 
+// remove trailing slash
+const BASENAME = (window.MetabaseRoot ?? "").replace(/\/+$/, "");
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/actions/downloading.ts:131]: Why not use `api.basename` here?

**Review by ranquild — COMMENTED** [review]
Comments inline

File: frontend/src/metabase/query_builder/actions/downloading.ts (hunk 2 above)
Comment (uladzimirdev) [reply frontend/src/metabase/query_builder/actions/downloading.ts:131]: because we do not import `api` here and I didn't want to bring such overhead to get just basename. Anyhow, let me change this

Comment (uladzimirdev) [reply frontend/src/metabase/query_builder/actions/downloading.ts]: fixed

**Review by ranquild — APPROVED** [review]
