### PR TITLE
Fix `escape-join-aliases` middleware not properly deduplicating all aliases

### LINKED ISSUE #28341: `escape-join-aliases` middleware does not properly deduplicate join aliases for joins inside source queries inside joins
The `escape-join-aliases` middleware is supposed to ensure every join alias across the entire query is unique. It turns out this is broken when a join contains a source query that contains a join and both of those joins use the same alias. See the preprocessed MBQL for the query in `metabase.query-processor-test.explicit-joins-test/joining-nested-queries-with-same-aggregation-test` for example.

I don't think this has caused problems in SQL queries, but it's a big issue for MongoDB join support we're working on.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #28341

Seems like a big PR but most of this is just new tests

### CODE REVIEW

**Review by bshepherdson — APPROVED** [review]

File: src/metabase/query_processor/middleware/escape_join_aliases.clj [hunk 1]
```diff
@@ -1,15 +1,214 @@
...
+
+  * Replace the `:join-alias` in `:field` clauses with the `::join-alias` and remove `::join-alias`.
+
+  * Replace the `:alias` in join clauses with the `::alias` and remove `::alias`.
+
+  * Remove the `::original->escaped` maps.
+
+  You might be asking, why don't we just do this in the first place rather than adding all these extra keys that we
+  eventually remove? For joins, we need to track the original alias for a while to build the `::original->escaped`
+  map. For `:field` clauses, we need to keep track of whether we already escaped it or not , since the mapping between
```
Comment (metamben) [inline src/metabase/query_processor/middleware/escape_join_aliases.clj:140]:
```suggestion
  map. For `:field` clauses, we need to keep track of whether we already escaped it or not, since the mapping between
```

File: src/metabase/query_processor/middleware/escape_join_aliases.clj [hunk 2]
```diff
@@ -1,15 +1,214 @@
...
+    (m :guard (every-pred map? ::original->escaped))
+    (-> (dissoc m ::original->escaped)
+        ;; recursively update source levels and `:field` clauses.
+        replace-original-aliases-with-escaped-aliases)
+
+    ;; update joins
+    (m :guard (every-pred map? ::alias))
+    (-> m
+        (assoc :alias (::alias m))
+        (dissoc ::alias)
```
Comment (metamben) [inline src/metabase/query_processor/middleware/escape_join_aliases.clj:154]:
```suggestion
    (set/rename-keys m {::alias :alias})
```

File: src/metabase/query_processor/middleware/escape_join_aliases.clj [hunk 3]
```diff
@@ -1,15 +1,214 @@
...
+        ;; recursively update source levels and `:field` clauses.
+        replace-original-aliases-with-escaped-aliases)
+
+    ;; update `:field` clauses
+    [:field id-or-name (options :guard (every-pred map? ::join-alias))]
+    [:field id-or-name (-> options
+                           (assoc :join-alias (::join-alias options))
+                           (dissoc ::join-alias))]))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/escape_join_aliases.clj:162]: This is rename keys too.

File: src/metabase/query_processor/middleware/escape_join_aliases.clj [hunk 4]
```diff
@@ -1,15 +1,214 @@
...
+
+(defn escape-join-aliases
+  "Pre-processing middleware. Make sure all join aliases are unique, regardless of case (some databases treat table
```
Comment (metamben) [inline src/metabase/query_processor/middleware/escape_join_aliases.clj:165]: Just by looking at the name I wouldn't expect this to generate unique aliases. It sounds like as if it just worried about special characters in names.

**Review by metamben — APPROVED** [review]
LGTM
