### PR TITLE
Fix Heading card input and Text card content clipping

### LINKED ISSUE #31613: Heading input and text dash-cards clipping after new grid sizing
### Describe the bug

Text dash-cards and the heading input field clip after the new dashboard grid sizing. Due to the resizing, rows are now smaller than before (at certain breakpoints) and this is causing the clipping.

**Text Fields**
image

**Heading Input**
image

### To Reproduce

**Heading**
1. Go to any dashboard
2. Click on edit
3. Add a heading card
4. Focus the input on a heading card
5. See the heading input clipping on characters that dip down (`g`, `p`)

**Text**
1. Go to any dashboard
2. Click on edit
3. Add a text card
4. Resize to be one row in height
5. Add `# Heading` to the card
6. Save
7. See the text clipping
  - If you do not, slowly resize from largest to smallest to see the breakpoints at which text cards clip

### Expected behavior

No clipping should occur

### Fix Criteria

```[tasklist]
### Tasks
- [x] Fix heading input clipping [PR #31965](https://github.com/metabase/metabase/pull/31965)
- [x] Fix text cards clipping between small and large breakpoints  [PR #31965](https://github.com/metabase/metabase/pull/31965)
- [x] Backport Fixes [PR #32103](https://github.com/metabase/metabase/pull/32103)
```

### Information about your Metabase installation

```JSON
- Master
```

### Severity

P1: Broken common features, correctness

### PR DESCRIPTION
**Pull request by JesseSDevaney**
**Problem:** The content of text dash-cards and the input of heading dash-cards clip after the new dashboard grid sizing. Due to the resizing, rows are now smaller than before (at certain resolutions) and this is causing the clipping.

**Context:** #31613  (Will close after backport)

_Text Card Content Clipping_
image

_Heading Input Clipping_
image

---
**Desired Behavior**

_Text Cards_
image
- [ ] A single line of text does not clip or have a scroll bar at any screen width (single row text cards - top card)

image
- [ ] A H2 heading in markdown does not clip or have a scroll bar at any screen width (single row text cards - top card)

_Heading Cards_
image
- [ ] Heading input for single row cards does not clip at any screen width

---
**Solution Implementation**

_Text Cards:_
- Refactor CSS module into a styled component wrapper
  - Motive: Move all styling into one file and be able to set `ReactMarkdown` styling using styled component props
- Use `isMobile`, `isSingleRow`, and media breakpoints for styling text dash-cards
  - Pass `isMobile` down from grid layout to dash-cards for mobile styling
  - Scale single row text cards padding and font-size for mid-size desktop resolutions to large desktop resolutions to allow for more content without clipping/scroll bar

_Heading Cards:_
- Increase heading input max-height to prevent clipping

---
**Acceptance Criteria**

- [ ] Single row text cards and text input on heading cards work according to the **Desired Behavior** (above)
- [ ] All other text and heading card behavior is unchanged

### CODE REVIEW

**Comment by JesseSDevaney** [comment]
Hello @iethree! I moved this to draft b/c I have to tweak some of the styles

File: frontend/src/metabase/visualizations/visualizations/Text/Text.jsx [hunk 1]
```diff
@@ -15,14 +15,12 @@ import { useToggle } from "metabase/hooks/use-toggle";
 import { isEmpty } from "metabase/lib/validate";
 
 import {
-  ClickToEditWrapper,
   DisplayContainer,
   EditModeContainer,
+  ReactMarkdownStyleWrapper,
```
Comment (iethree) [inline frontend/src/metabase/visualizations/visualizations/Text/Text.jsx:20]: I like this!

**Review by iethree — APPROVED** [review]
👍
