### PR TITLE
Fix SAML redirect to with certain URLs e.g. /collection/root

### LINKED ISSUE #13666: Invalid Redirect Location After SAML Sign-in via Full App Embed
**Describe the bug**
When using full app embedding, the redirect location provided by Metabase in response to the SAML IdP callback is invalid.

**Logs**
Nothing at all is being logged by Metabase v1.37.0.2 - it seems Log4j config is being ignored, maybe a separate bug?
For Metabase v1.35.4.3 with `log4j.logger.metabase=TRACE` there's not much logged during the repro steps:

```
2020-11-03 14:03:36,477 [qtp1468657944-20] DEBUGmetabase.middleware.log - GET /api/user/current 401 208.6 µs (0 DB calls)
"Unauthenticated"

2020-11-03 14:03:36,487 [qtp1468657944-60] DEBUGmetabase.middleware.log - GET /api/session/properties 200 4.5 ms (0 DB calls) App DB connections: 0/10 Jetty threads: 3/50 (5 idle, 0 queued) (49 total active threads) Queries in flight: 0 (0 queued)
```

In the Firefox or Chrome console there's just this:

```
example.domain.com/auth/%%20%20-%20%20%20%20%20-:1 Failed to load resource: the server responded with a status of 400 ()
```

**To Reproduce**
1. Configure SAML SSO
2. Configure full app embedding
3. Attempt log in via SSO
4. IdP re-direct POST goes to `example.domain.com/auth/sso`. The response status code is 302, the `location` header value is `%  -     -` (percent with some spaces and dashes) which is URL-encoded to `%%20%20-%20%20%20%20%20-`, which is not valid either since the first character should've been encoded to `%25`, so it doesn't decode.
6. The malformed request to `example.domain.com/auth/%%20%20-%20%20%20%20%20-` is caught by nginx proxy and results in a very plain-looking `400 Bad Request` page.
7. Refresh the page and the iframe src e.g. `https://example.domain.com` results in a valid GET/200 request with the session still active so users can proceed as normal.

**Expected behavior**
Post sign-in re-direction to the White-label `Landing Page` (also set as SAML `RelayState`), or at least the `Site URL`, without showing an error page or requiring a page reload.

**Screenshots**
The 400 error page looks like this: 
image

**Severity**
It's not a complete blocker, but it is a severe interruption to the user login process and likely to cause a lot of confusion.

**Additional context**
As mentioned above, I tried this with the v1.35.4.3 initially, then gave v1.37.0.2 a whirl to see if it was fixed there but unfortunately not. Other attempts included some hours of trying to override this bug with nginx rewrites etc. but it doesn't seem to be possible to rewrite a proxied response header only for a specific URL and request method.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10-LTS",
    "java.vendor": "N/A",
    "java.vendor.url": "https://openjdk.java.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-957.1.3.el7.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "(custom driver)"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v1.37.0.2",
      "branch": "release-x.37.x",
      "hash": "7996551"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

The other version tried was:

```json
    "version": {
      "date": "2020-09-30",
      "tag": "v1.35.4.3",
      "branch": "enterprise-release-1.35.x",
      "hash": "e3ead72"
    },
```

Also tested with Chrome Version 86.0.4240.111.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #13666

The basic issue here was we were skipping base-64 encoding of `/collection/root` (passed to the initial `GET /auth/sso` request as a `?redirect` query parameter) because it technically already is a valid base-64 string, but then we base-64 decoded it which gave us the weird `% - -` nonsense string. Fixed by removing the check before base-64 encoding the redirect string; now we always base-64 encode it -- `?redirect` doesn't come in base-64 encoded anyway so no need to check this

### CODE REVIEW

File: test/metabase/http_client.clj [hunk 1]
```diff
@@ -23,17 +24,23 @@
   "Prefix to automatically prepend to the URL of calls made with `client`."
   (str "http://localhost:" (config/config-str :mb-jetty-port) "/api/"))
 
+(def ^:dynamic *url-encode-query-parameters?*
+  "Whether to automatically URL-encode query parameter keys and values."
+  true)
```
Comment (dpsutton) [inline test/metabase/http_client.clj:29]: where in the code is this ever adjusted and why would we want to not encode?

**Review by dpsutton — APPROVED** [review]

File: test/metabase/http_client.clj (hunk 1 above)
Comment (camsaul) [reply test/metabase/http_client.clj:29]: I'm not sure we'd ever want to not encode it. I guess you can just manually append your weird parameters to the URL itself if you don't want them to automatically be encoded. I'll remove this option since it's just clutter
