### PR TITLE
Fix MB in an iframe running on a subpath

### LINKED ISSUE #67642: Iframes might break when Metabase is in a sub path
### Describe the bug

After [https://github.com/metabase/metabase/pull/65662](https://github.com/metabase/metabase/pull/65662) things might break when Metabase is running or being proxied in a sub path. Considering that we don't support sub paths (we never officially did) [https://github.com/metabase/metabase/issues/30895](https://github.com/metabase/metabase/issues/30895), this issue is created as a warning

### To Reproduce

1. make Metabase run on a sub path
2. embed metabase in an iframe and navigate through it

### Expected behavior

Should it work?

### Logs

NA

### Information about your Metabase installation

```JSON
v57.x
```

### Severity

P2

### Additional context

This is a customer's debugging:

The Problem:
In QueryBuilder.tsx there's this check added in v0.57:

const isRouteInSync = window.location.pathname === location.pathname;
if (isWithinIframe() && !isRouteInSync) {
  return null; // Don't initialize
}

Why it breaks with subpath:
window.location.pathname = /proxy/reporting/question (absolute)
location.pathname (react-router) = /question (relative to basename)
These never match when using a subpath → query builder never initializes

Console proof:
Direct access (8118 /  your demo ) - works
window.location.pathname: /
router pathname: /
Match - true, works.

Via proxy subpath (embedding_app/proxy/reporting)
window.location.pathname: /proxy/reporting
router pathname: /
Match: false - meaning query builder never initializes and queries are blocked (!)

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #67642
Closes [EMB-1162: Iframes might break when Metabase is in a sub path](https://linear.app/metabase/issue/EMB-1162/iframes-might-break-when-metabase-is-in-a-sub-path)

### Description

When running Metabase through a proxy, the querybuilder and the dashboard app would not initialize because of the fix made in #65662. This is now fixed by stripping any potential subpath before the check.

### How to verify

1. Run Metabase through a proxy
2. Open an interactive embedding, it should work, for both questions and dashboards)

No automated tests unfortunately, spinning up a proxy within Cypress is too cumbersome at the moment.

### CODE REVIEW

File: frontend/src/metabase/common/hooks/is-route-in-sync.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import { getPathnameWithoutSubPath, isWithinIframe } from "metabase/lib/dom";
+
+/**
+ * Returns whether the current route is in sync with the given pathname,
```
Comment (WiNloSt) [inline frontend/src/metabase/common/hooks/is-route-in-sync.ts:4]: There should be some mention of #65500, which was the purpose of this hook. To be fair, I'm on the fence about having this in `metabase/common` at all. For one, it's only used in 2 places, and we might mistake this for something that are used more widely. But anyway, I think having a comment linking this to a specific bug should suffice.

File: frontend/src/metabase/common/hooks/is-route-in-sync.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+ * @param pathname the current path name
+ * @returns whether the routes are in sync, if we're in an iframe context
+ */
+export function isRouteInSync(pathname: string): boolean {
+  const isRouteInSync =
+    getPathnameWithoutSubPath(window.location.pathname) === pathname;
+
+  if (isWithinIframe() && !isRouteInSync) {
+    return false;
+  }
```
Comment (WiNloSt) [inline frontend/src/metabase/common/hooks/is-route-in-sync.ts]: In my head, this one would be easier to understand.


```suggestion
  if (isWithinIframe()) {
    return isRouteInSync;
  }
```

This reads exactly like the function comment above, in my opinion.

File: frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.tsx [hunk 3]
```diff
@@ -162,9 +162,8 @@ export const DashboardApp = ({
   const { autoScrollToDashcardId, reportAutoScrolledToDashcard } =
     useAutoScrollToDashcard(location);
 
-  const isRouteInSync = window.location.pathname === location.pathname;
-  if (isWithinIframe() && !isRouteInSync) {
-    return null; // Don't render until route syncs (metabase#65500)
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.tsx:167]: I feel like I like having the issue reference and a comment about not rendering it here, more than not having it. Even if we're adding the reference to the function definition itself, at glance, we'd know this particular block that renders nothing contributes to a fix for a specifc bug right away.

File: frontend/src/metabase/lib/dom.js [hunk 4]
```diff
@@ -224,7 +224,13 @@ export function constrainToScreen(element, direction, padding) {
...
 
 export function getSitePath() {
-  return new URL(MetabaseSettings.get("site-url")).pathname.toLowerCase();
+  const siteUrl = MetabaseSettings.get("site-url");
+
+  if (!siteUrl) {
+    return "/";
+  }
+
+  return new URL(siteUrl).pathname.toLowerCase();
```
Comment (WiNloSt) [inline frontend/src/metabase/lib/dom.js]: I think this is unrealistic. You won't have a case where `site-url` is undefined. It's already set when the instance is instantiated. And after that, it's impossible to set this to an invalid URL because of there's a validation for that.

https://github.com/metabase/metabase/blob/a1a62cd6031849498f810900159668e9c82eea09/src/metabase/system/settings.clj#L59

https://github.com/metabase/metabase/blob/a1a62cd6031849498f810900159668e9c82eea09/src/metabase/system/settings.clj#L29-L39

I wouldn't modify this function, but rather modify the unit tests to set a proper `site-url` instead. What do you think?

Comment (lorem--ipsum) [reply frontend/src/metabase/lib/dom.js]: Yeah I was on the fence about this, I'll try your approach.

File: frontend/src/metabase/common/hooks/is-route-in-sync.unit.spec.ts [hunk 5]
```diff
@@ -1,10 +1,20 @@
...
+  beforeAll(() => {
+    MetabaseSettings.set("site-url", "http://localhost:3000");
+  });
+
   beforeEach(() => {
     delete (window as any).overrideIsWithinIframe;
   });
 
+  afterAll(() => {
+    MetabaseSettings.set("site-url", undefined as any);
```
Comment (WiNloSt) [inline frontend/src/metabase/common/hooks/is-route-in-sync.unit.spec.ts:15]: Do we need to undo the setting? Does the setting persist across different test suites? In my mind, different suites would have their own `MetabaseSettings` instance. If it's actually needed then disregard this comment.

**Review by WiNloSt — APPROVED** [review]
Ok looks great now. Thanks for addressing the feedback!

File: frontend/src/metabase/common/hooks/is-route-in-sync.unit.spec.ts (hunk 5 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/common/hooks/is-route-in-sync.unit.spec.ts:15]: Not sure, I usually assume it's safer to undo what's been done ¯\_(ツ)_/¯
