### PR TITLE
Reload metadata after saving a question or model

### LINKED ISSUE #22518: Changing Model definition will not show changes until after browser refresh
**Describe the bug**
When changing a Model's query definition, then the changes do not show until after a browser refresh, which makes it difficult to understand what is happening, and is being confused with query caching.

Workaround: After changing the query definition of a Model, then do a browser refresh.

**To Reproduce**
1. Question > SQL > Sample - save as "Q1"
```
select 1 id, 'a' test1
```
2. Turn into a Model
image
3. Click Summarize - it shows "ID" and "TEST1" as expected
image
4. Click "Edit query definition" - ex. add a column - Save changes
```
select 1 id, 'a' test1, 'b' test2
```
5. Click Summarize - it will not show the newly added "TEST2" column, even though it's part of the results
image
6. Do a browser refresh - now it works as expected
image

**Expected behavior**
Changes to a Model should be usable instantly without a browser refresh.

**Information about your Metabase Installation:**
Tested 0.42.0 thru 0.43.0

**Additional context**
Historically related to #9027 and friends.

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/22518

How to test:
- Follow the steps from the original issue
- There is also an unskipped cypress test with the same steps

### CODE REVIEW

File: frontend/src/metabase/redux/metadata.js [hunk 1]
```diff
@@ -313,11 +313,10 @@ export const loadMetadataForQuery = (query, extraDependencies) =>
   loadMetadataForQueries([query], extraDependencies);
 
 export const loadMetadataForQueries =
-  (queries, extraDependencies = []) =>
-  dispatch => {
+  (queries, extraDependencies, options) => dispatch => {
     const dependencies = _.chain(queries)
       .map(q => q.dependentMetadata())
-      .push(...extraDependencies)
+      .push(...(extraDependencies ?? []))
```
Comment (WiNloSt) [inline frontend/src/metabase/redux/metadata.js:319]: Is there any particular reason you moved the default value from the parameter here? I guess you were trying to improve the parameter readability?

**Review by WiNloSt — APPROVED** [review]
Looks good to me 👍

File: frontend/src/metabase/redux/metadata.js (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/redux/metadata.js:319]: No, it's not allowed to use default parameters for parameters that are not last ones.
