### PR TITLE
Fix returns 500 when exception is thrown from handle-page middleware

### LINKED ISSUE #23277: Certain invalid URL causes error response from Jetty
**Describe the bug**
Certain invalid URL causes error response from Jetty.

**To Reproduce**
1. Go to `http://localhost:3000/api/search?limit=a` (doesn't matter if authenticated or not)
image

<details><summary>Full stacktrace</summary>

```
2022-06-10 10:15:07,645 ERROR metabase.server :: Unexpected Exception in API request handler
java.lang.IllegalArgumentException: No implementation of method: :write-body-to-stream of protocol: #'ring.core.protocols/StreamableResponseBody found for class: clojure.lang.PersistentArrayMap
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at ring.core.protocols$fn__4555$G__4550__4564.invoke(protocols.clj:8)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:109)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:94)
	at metabase.server.protocols$fn__4682.invokeStatic(protocols.clj:27)
	at metabase.server.protocols$fn__4682.invoke(protocols.clj:20)
	at metabase.server.protocols$fn__4658$fn__4661$G__4659__4668.invoke(protocols.clj:5)
	at metabase.server$async_proxy_handler$fn__78514$fn__78524.invoke(server.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__82207$fn__82208.invoke(gzip.clj:89)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at ring.middleware.cookies$wrap_cookies$fn__82165$fn__82166.invoke(cookies.clj:217)
	at metabase.server.middleware.offset_paging$handle_paging$fn__60377.invoke(offset_paging.clj:49)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__82245.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__82264.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__35183.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__46654$fn__46655.invoke(session.clj:291)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:270)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:259)
	at metabase.server.middleware.session$bind_current_user$fn__46654.invoke(session.clj:290)
	at metabase.server.middleware.session$wrap_current_user_info$fn__46636.invoke(session.clj:240)
	at metabase.server.middleware.session$wrap_session_id$fn__46620.invoke(session.clj:173)
	at metabase.server.middleware.auth$wrap_api_key$fn__66768.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__82165.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__35166.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__35191.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__82207.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__35194.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__81994.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__78514.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-10 10:15:07,650 ERROR metabase.server :: Unexpected exception in endpoint
java.lang.IllegalArgumentException: No implementation of method: :write-body-to-stream of protocol: #'ring.core.protocols/StreamableResponseBody found for class: clojure.lang.PersistentArrayMap
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at ring.core.protocols$fn__4555$G__4550__4564.invoke(protocols.clj:8)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:109)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:94)
	at metabase.server.protocols$fn__4682.invokeStatic(protocols.clj:27)
	at metabase.server.protocols$fn__4682.invoke(protocols.clj:20)
	at metabase.server.protocols$fn__4658$fn__4661$G__4659__4668.invoke(protocols.clj:5)
	at metabase.server$async_proxy_handler$fn__78514$fn__78524.invoke(server.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__82207$fn__82208.invoke(gzip.clj:89)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at ring.middleware.cookies$wrap_cookies$fn__82165$fn__82166.invoke(cookies.clj:217)
	at metabase.server.middleware.offset_paging$handle_paging$fn__60377.invoke(offset_paging.clj:49)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__82245.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__82264.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__35183.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__46654$fn__46655.invoke(session.clj:291)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:270)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:259)
	at metabase.server.middleware.session$bind_current_user$fn__46654.invoke(session.clj:290)
	at metabase.server.middleware.session$wrap_current_user_info$fn__46636.invoke(session.clj:240)
	at metabase.server.middleware.session$wrap_session_id$fn__46620.invoke(session.clj:173)
	at metabase.server.middleware.auth$wrap_api_key$fn__66768.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__82165.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__35166.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__35191.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__82207.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__35194.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__81994.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__78514.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

**Expected behavior**
Never return plain Jetty errors. Simple error when authenticated. And "Unauthenticated" when not.

**Information about your Metabase Installation:**
Tested 0.41.7 thru 0.43.2 and master

**Additional context**
Related to #23083. Historically related to #15231

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes #23277

We had this bug because of how we ordered our API's middleware.

For most APIs we stream the response as JSON. This bugs happen when there is an error in `handle-paging` middleware and we respond with an error response.

Because of how we ordered our middleware, this error message was not serialized and we get the error `No implementation of method :write-body-to-stream for clojure.lang.PersistentArrayMap` from Jetty.

The fix is fairly simple in that we need to ensure the error response from `handle-paging` middleware is properly streamed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/27526)

### CODE REVIEW

**Review by calherries — CHANGES_REQUESTED** [review]
Looks pretty good, I have a few suggestions to clean up the code but nothing major.

File: test/metabase/server/middleware/offset_paging_test.clj [hunk 1]
```diff
@@ -1,45 +1,57 @@
...
   (testing "no paging params"
-    (is (= {:status  200
-            :headers {}
-            :body    {:limit  nil
-                      :offset nil
-                      :paged? false
-                      :params {}}}
-           (handler (ring.mock/request :get "/")))))
+    (is (=? {:status  200
+             :headers (mw.security/security-headers)
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply test/metabase/server/middleware/offset_paging_test.clj:39]: I thought about removing it but then I think it was nice to have a piece of test.

Since it's a rare case for us to have API that throws exceptions in the middleware, I'm not sure if are there any tests to make sure we have security headers in those cases.

[the remark this answers is not in the document]
Comment (calherries) [reply test/metabase/server/middleware/offset_paging_test.clj:36]: If so, I would put that in a separate test since it's testing a code path unrelated to offsets and pages. `=?` allows us to write narrow tests easily, so we might as well use it.

[the remark this answers is not in the document]
Comment (qnkhuat) [reply test/metabase/server/middleware/offset_paging_test.clj]: on second thought, we explicitly include security headers when there is an error [here](https://github.com/metabase/metabase/blob/6f64abedd82d037029b8ad13ab6f214c496a475b/src/metabase/server/middleware/offset_paging.clj#L51).

So I added a headers test but only for the error case.

File: src/metabase/server/handler.clj [hunk 2]
```diff
@@ -68,7 +68,8 @@
    #'mw.ssl/redirect-to-https-middleware])
 ;; ▲▲▲ PRE-PROCESSING ▲▲▲ happens from BOTTOM-TO-TOP
 
-(defn- apply-middleware [handler]
+(defn- apply-middleware
+  [handler]
```
Comment (calherries) [inline src/metabase/server/handler.clj:72]: I think this was a mistake but let's try not to change unrelated code, even if it's just formatting

Comment (tsmacdonald) [reply src/metabase/server/handler.clj:72]: Oh…I absolutely change (minor) formatting issues / typos / etc. when I see them. Keep the codebase improving with things I'd never open a separate PR for.

Comment (calherries) [reply src/metabase/server/handler.clj:72]: Good point. I still think was a mistake, as we usually don't have new lines between `defn-` and the args vector unless there's a docstring.

**Review by calherries — APPROVED** [review]
Good!

File: src/metabase/server/handler.clj (hunk 2 above)
Comment (qnkhuat) [reply src/metabase/server/handler.clj:72]: According to https://guide.clojure.style/#optional-new-line-after-fn-name
both are valid style, so I'll leave it as it is. 

I changed it originally because I added a docstring, but then I removed it.

**Comment by tsmacdonald** [comment]
(just rebased the branch to fix the flaky build)
