### PR TITLE
dashboard_tab.entity_id is nullable now, makes drop-entity-ids work

### LINKED ISSUE #34871: Serialization v2 duplicates entities loaded with serialization v1 on old versions
### Describe the bug

This one has been haunting some customers for some time and I was able to repro it today after finding https://github.com/metabase/metabase/issues/34870

When loading with serdes v2 after upgrading, the entities get duplicated

### To Reproduce

1) set up Metabase with 45.4 as an origin and another as as a destination (same version)
2) create a dashboard with an x-ray on the origin.
3) dump the origin and load it onto the destination
4) now upgrade to v47 both instances
5) clean up the folder where the files are, so you're in a clean slate. Now export the source and import on the destination (use the new commands)
6) now see on the destination that the x-ray collection was duplicated

### Expected behavior

We shouldn´t duplicate entities

### Logs

no errors at all

### Information about your Metabase installation

```JSON
v47.x coming from v45
```

### Severity

P1

### Additional context

NA

### LINKED ISSUE #36365: drop-entity-ids fails when dashboards have tabs
### Describe the bug

When a dashboard has tabs, the command we introduced in v47 does not work with a weird error about actions

### To Reproduce

1) use v47, create a dashboard with a tab
2) run "java -jar metabase.jar drop-entity-ids"
3) see the error

### Expected behavior

the command should not error

### Logs

```
2023-12-04 17:51:32,703 INFO v2.entity-ids :: Dropping Entity IDs for model Action
java.lang.Exception: Error encountered while dropping entity IDs
	at metabase.cmd$drop_entity_ids.invokeStatic(cmd.clj:229)
	at metabase.cmd$drop_entity_ids.invoke(cmd.clj:225)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__118907.invoke(cmd.clj:300)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:299)
	at metabase.cmd$run_cmd.invoke(cmd.clj:289)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:181)
	at metabase.core$run_cmd.invoke(core.clj:179)
	at metabase.core$_main.invokeStatic(core.clj:203)
	at metabase.core$_main.doInvoke(core.clj:198)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Command failed with exception: Error encountered while dropping entity IDs
```

### Information about your Metabase installation

```JSON
v47.9
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sansolovyov**
Resolves #36365

### CODE REVIEW

**Comment by darksciencebase** [comment]
resolves https://github.com/metabase/metabase/issues/36365 ?

File: enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj [hunk 1]
```diff
@@ -45,24 +48,36 @@
...
+    (testing "empty table"
+      (testing "has no entity ids"
+        (mt/with-temp! [Collection _ {:name "No Entity ID Collection"
+                                      :slug "no_entity_id_collection"}]
+                       (is (nil? (t2/select-fn-set :entity-id Dashboard)))
+                       (testing "but doesn't crash drop-entity-ids"
+                         (is (= true
+                                (v2.entity-ids/drop-entity-ids!)))
+                         (is (nil? (t2/select-fn-set :entity-id Dashboard)))))))
+    (testing "entity_id field is nullable everywhere so that drop-entity-ids will work for"
```
Comment (qnkhuat) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj:73]:
```suggestion
    (testing "entity_id field is nullable everywhere so that drop-entity-ids will work for"
```

I'd make this a `deftest` on its own, it doesn't really need to be run in an empty h2 db tho.

File: resources/migrations/001_update_migrations.yaml [hunk 2]
```diff
@@ -3118,6 +3118,15 @@ databaseChangeLog:
                     nullable: true
                     unique: true
 
+  - changeSet:
+      id: v47.00-059
+      author: piranha
+      comment: 'Drops not null from dashboard_tab.entity_id since it breaks drop-entity-ids command'
+      changes:
+        - dropNotNullConstraint:
```
Comment (qnkhuat) [inline resources/migrations/001_update_migrations.yaml:3126]: will rollback revert the drop not null constraint? some liquibase changes will automatically create a rollback automatically.

if it does I think it's better if we specify a no-op rollback here because there is no benefit to adding it back.

but I guess one downside is you need to make this "drop if exists"

File: enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj (hunk 1 above)
Comment (qnkhuat) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj:73]: and what if we make this testing context more actionable?

like `entity_id field should be nullable for model so that drop-entity-ids work (#36365)`

Comment (piranha) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj:73]: It'll fail on pgsql since table name is not upper-case there. So I either need to dispatch logic on a db type, or bind it to a specific db. Later seems easier and less cluttered, so I went that way.

Why the whole test is wrapped in `empty-h2-db`: it reliably fails without it locally without it, and I couldn't understand why.

Comment (piranha) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj:73]: Nevermind, code is ok either way 😁

**Review by qnkhuat — APPROVED** [review]
cool, this lgtm!
