### PR TITLE
Prevent falling back on type before cast when qp/ignore-coercion

### LINKED ISSUE #56886: Incorrect SQL Generated for BigInts Cast as Datetimes
### Describe the bug

We generate invalid SQL in some cases for BigInt values vast as datetimes. 

### To Reproduce

1. Create a table in Postgres with a BigInt field
2. In table metadata set field casting to "UNIX milliseconds -> Datetime"
3. Create a question on the table that returns an aggregate grouped by this field (by day)
4. Note that this runs just fine
5. Add a customer column column to the question (above the summarize block) and then add it to the group by function alongside the date field
6. Observer error, "ERROR: cannot cast type date to bigint Position: 124"

Grouping by fields that aren't custom columns doens't seem to cause this behavior. Grouping with a custom column modifies the casting for the date field to:

```
  CAST(CAST("source"."order_date_millis" AS date) AS int8) ASC,
  "source"."test1" ASC
```

https://www.loom.com/share/2241364e6c32420d9301cbe34bb33b65

### Expected behavior

We should generate valid SQL in this case

### Logs

[47985132-250a-40ed-9d81-81bcc1eb82af] 2025-04-17T13:32:09-05:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: ERROR: cannot cast type date to bigint
  Position: 124
{:database_id 2,
 :parameterized false,
 :started_at #t "2025-04-17T18:32:09.252816523Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error "Error executing query: ERROR: cannot cast type date to bigint\n  Position: 124",
   :stacktrace
   ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__80023$fn__80024.invoke(execute.clj:747)"
    "driver.sql_jdbc.execute$execute_reducible_query$fn__80023.invoke(execute.clj:744)"
    "driver.sql_jdbc.execute$fn__79812$fn__79813.invoke(execute.clj:399)"
    "driver.sql_jdbc.execute$do_with_resolved_connection79782__79783.invokeStatic(execute.clj:339)"
    "driver.sql_jdbc.execute$do_with_resolved_connection79782__79783.invoke(execute.clj:322)"
    "driver.sql_jdbc.execute$fn__79812.invokeStatic(execute.clj:393)"
    "driver.sql_jdbc.execute$fn__79812.invoke(execute.clj:391)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:738)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:724)"
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:735)"
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:724)"
    "driver.sql_jdbc$fn__134820.invokeStatic(sql_jdbc.clj:79)"
    "driver.sql_jdbc$fn__134820.invoke(sql_jdbc.clj:77)"
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:52)"
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:39)"
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:102)"
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:95)"
    "query_processor.execute$run.invokeStatic(execute.clj:62)"
    "query_processor.execute$run.invoke(execute.clj:56)"
    "query_processor.middleware.update_used_cards$update_used_cards_BANG_76369__76370$fn__76371.invoke(update_used_cards.clj:62)"
    "query_processor.execute$add_native_form_to_result_metadata$fn__76474.invoke(execute.clj:25)"
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__76480.invoke(execute.clj:36)"
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76317.invoke(cache.clj:241)"
    "query_processor.middleware.permissions$check_query_permissions$fn__76083.invoke(permissions.clj:148)"
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__128218$check_download_permissions__128219$fn__128220.invoke(permissions.clj:99)"
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__76184.invoke(enterprise.clj:57)"
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$fn__130392$maybe_apply_column_level_perms_check__130393$fn__130394.invoke(column_level_perms_check.clj:38)"
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__76194.invoke(enterprise.clj:70)"
    "query_processor.execute$execute76507__76508$fn__76509.invoke(execute.clj:94)"
    "query_processor.setup$do_with_qp_setup76460__76461.invokeStatic(setup.clj:225)"
    "query_processor.setup$do_with_qp_setup76460__76461.invoke(setup.clj:216)"
    "query_processor.execute$execute76507__76508.invokeStatic(execute.clj:93)"
    "query_processor.execute$execute76507__76508.invoke(execute.clj:89)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__82765$handle_audit_app_internal_queries__82766$fn__82767.invoke(handle_audit_queries.clj:143)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__76222.invoke(enterprise.clj:109)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware82973__82974$fn__82975.invoke(proc...
[47985132-250a-40ed-9d81-81bcc1eb82af] 2025-04-17T13:32:09-05:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 144ms (21 DB call

### Information about your Metabase installation

```JSON
Tested in 53.1.1 and 54.3
```

### Severity

blocking some users

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by metamben**
Fixes #56886

### Description

This is assuming that qp/ignore-coercion is set to avoid repeated casting.  That means, that we should type the expression as if the cast has happened and should not revert to the type before the cast.

### How to verify

The repro steps from #56886 should not lead to an error.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/driver/sql/query_processor.clj [hunk 1]
```diff
@@ -747,20 +746,20 @@
...
                                     (not (:qp/ignore-coercion options)))
-          database-type        (or database-type
-                                   (:database-type field-metadata))
           ;; preserve metadata attached to the original field clause, for example BigQuery temporal type information.
           identifier           (-> (apply h2x/identifier :field
                                           (concat source-table-aliases (->honeysql driver [::nfc-path source-nfc-path]) [source-alias]))
                                    (with-meta (meta field-clause)))
           identifier           (->honeysql driver identifier)
+          casted-field         (cast-field-if-needed driver field-metadata identifier)
+          database-type        (or (h2x/database-type casted-field)
```
Comment (ericnormand) [inline src/metabase/driver/sql/query_processor.clj:755]: It looks like we might use the database type from the casted field even if allow-casting? is false. Is this desired?

Comment (metamben) [reply src/metabase/driver/sql/query_processor.clj:755]: That is the point of this PR. It makes the assumption that `(:qp/ignore-coercion options)` is true, because we want to avoid casting a second time (I know for sure that this is a reason, I'm not 100% sure this is the only reason). The problem this PR wants to solve is that when a number (e.g., of type `int8`) was coerced to a `timestamp`, we use the type `timestamp` and don't revert back to `int8`.

The bug I'm fixing here resulted from using the type `int8` here. Then this field is converted to `:day`. But for postgres (because of your earlier fix), after converting to a date we cast back to the original type. That "original type" is `int8`, which breaks.

**Review by ericnormand — APPROVED** [review]
