### PR TITLE
Show currency list in native queries and add Kyrgyz Som

### LINKED ISSUE #9828: Add Kyrgyz Som to currency list
frontend/src/metabase/lib/currency.js
``` 
  KGS: {
    symbol: "KGS",
    name: "Kyrgyz Som",
    symbol_native: "сом",
    decimal_digits: 2,
    rounding: 0,
    code: "KGS",
    name_plural: "Kyrgyz soms",
  },
```
I didn't make PR because i cant build metabase myselft to test changes.

### LINKED ISSUE #11233: For a new Custom column, I can set Style to "Currency", but cannot choose the Unit of Currency
## Bug description
Say I create the _Custom column_ as  `Total Price = Quantity × Unit Price`.

The created metric is a unit-less float.
I want to assign it a (currency). So in table option, I select the column `Total Price` and choose the style _Currency_.

That all good… except that **I cannot choose which currency to use** (the default is USD, whatever the global default currency chosen in `Admin/Settings/Formatting/Currency/Unit of currency`).

## Expected behavior

I want to be able to chose which currency to use, just like it is possible for columns that have been casted as "Currency" in the Data Model:

## Metabase Installation:

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_191-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_191",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.191-b12",
    "os.name": "Linux",
    "os.version": "4.13.9-300.fc27.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "tag": "v0.33.4",
      "date": "2019-10-07",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

## Severity
Annoying

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by dragonsahead**
Added the Kyrgyz Som to fix https://github.com/metabase/metabase/issues/9828 and also changed the control in the frontend so people can choose their currency in native queries, as they would do in GUI queries. Will fix https://github.com/metabase/metabase/issues/11233.

Please let me know the consequences of this change in relaxing the restrictions on showing the currency list on native queries, I don't see any but just in case.

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/settings/column.js [hunk 1]
```diff
@@ -327,8 +327,7 @@ export const NUMBER_COLUMN_SETTINGS = {
     },
     default: "USD",
     getHidden: (column: Column, settings: ColumnSettings) =>
-      // NOTE: ideally we'd hide this if number_style != "currency" but that would result in a circular dependency
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/lib/settings/column.js:330]: This comment pointed to the potential issue. Since the `currency` setting now uses `number_style`, it should add that under `readDependencies` to ensure `number_style` is computed when we need it here. However, adding that would create a circular dependency between the two settings. I doubt we detect that situation well, so it might just infinite loop and crash the app.

In this case I think `getHidden` will only receive stale data if `number_style` is unset and we're computing a default. Given that, I guess leaving the dependency out is fine for native questions? The one situation I'd check is that for GUI questions with a default `number_style` we still display `currency`'s widget. If that's broken, this might need to be: `!isCurrency(column) && settings["number_style"] !== "currency"`

**Review by paulrosenzweig — APPROVED** [review]
🥳 Nice! I left one comment with a situation to check, but it looks good! It might also be nice to have a test that native questions have the setting.

File: frontend/src/metabase/visualizations/lib/settings/column.js (hunk 1 above)
Comment (paoliniluis) [reply frontend/src/metabase/visualizations/lib/settings/column.js:330]: Yup, it does, but won't take the default currency, which I believe it's another issue:
Peek 2021-04-02 12-37

What do you think? ready to merge?

Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/lib/settings/column.js:330]: I agree not using the instance default is probably another issue. 

The situation I was curious about was whether the `currency` widget is still displayed when the default `number_style` is currency. In the gif, you set Count's `number_style` to currency, but Total should already have that as a default. If there are any setting dependency issues, I think that's where it would show up.

Comment (flamber) [reply frontend/src/metabase/visualizations/lib/settings/column.js:330]: Not picking up the defaults is #10787 (and 11394)
