### PR TITLE
Validate suffix & strip whitespace from Google auth client id

### LINKED ISSUE #15975: Validate Google sign-in client IDs
Google client IDs have a specific format and are suffixed by `.apps.googleusercontent.com`. We could do basic validation on client IDs (on the frontend and/or backend) and reject IDs with an incorrect format.

### LINKED ISSUE #15976: Strip whitespace from Google sign-in client IDs
Client IDs that are saved with leading or trailing whitespace result in an OAuth error when trying to log in, even if the ID is otherwise valid.

### PR DESCRIPTION
**Pull request by noahmoss**
* Adds a custom setter for the `google-auth-client-id` setting which strips whitespace and makes sure the client ID ends with the correct suffix
* Some tests and formatting tweaks
* Changed "Google Auth" to "Google Sign-In" in user-facing strings, since "Sign-In" is the official name

Resolves  #15976 and #15975.

The error message on an invalid suffix is surfaced to the frontend, but the padding is a bit odd. I'll open a separate issue for tweaking this CSS. 
Screen Shot 2021-11-18 at 11 28 40 AM

### CODE REVIEW

File: src/metabase/integrations/google.clj [hunk 1]
```diff
@@ -21,8 +21,16 @@
...
-  (deferred-tru "Client ID for Google Auth SSO. If this is set, Google Auth is considered to be enabled.")
-  :visibility :public)
+  (deferred-tru "Client ID for Google Sign-In. If this is set, Google Sign-In is considered to be enabled.")
+  :visibility :public
+  :setter (fn [client-id]
+            (if client-id
+              (let [trimmed-client-id (str/trim client-id)]
+                (if-not (str/ends-with? trimmed-client-id ".apps.googleusercontent.com")
+                  (throw (ex-info (tru "Invalid Google Sign-In Client ID: must end with \".apps.googleusercontent.com\"")
+                                  {:status-code 400}))
```
Comment (camsaul) [inline src/metabase/integrations/google.clj:31]: This is more of a general observation than something you should feel the need to fix here, but in situations like this where you're checking some condition and exiting the function in some way it's better _not_ to put the non-exiting branch of the code in an `else` clause. You could rewrite this as

```clj
(when-not (str/ends-with? ...)
  (throw ...))
(setting/set-string! ...)
```

instead which lowers the total indentation level of the code which makes everything easier to read and understand. When given the choice, make the code flat.

Btw this applies to any language, not just Clojure.

```c++
if (...) {
  return;
}
DoSomethingElse();
```

is easier to read than 

```c++
if (...) {
  return;
} else {
  DoSomethingElse();
}
```

even tho they both do exactly the same thing

Comment (camsaul) [reply src/metabase/integrations/google.clj:31]: It would probably be more readable to write the whole thing like

```clj
(fn [client-id]
  (let [client-id (some-> client-id str/trim)]
    (when (and client-id (str/ends-with? client-id ...))
      (throw ...))
    (setting/set-string! ...))
```

so you avoid all that branching. Just my 2 cents tho. It ultimately doesn't make a big difference

**Review by camsaul — APPROVED** [review]

File: src/metabase/integrations/google.clj (hunk 1 above)
Comment (noahmoss) [reply src/metabase/integrations/google.clj:31]: That's fair, although I have heard the opposite argument: that it's clearer to put `DoSomethingElse()` inside an `else` block to make it super obvious that it will _only_ execute if the condition is false (i.e. if you're skimming the code and don't notice that the `if` block returns or throws an exception).

In the Clojure case I agree though; will change it here

File: frontend/test/metabase/scenarios/admin/settings/sso/google.cy.spec.js [hunk 2]
```diff
@@ -8,16 +8,30 @@ describe("scenarios > admin > settings > SSO > Google", () => {
...
+
+  it(
+    "Google sign-in client ID form should show an error message if it does not end with the correct suffix (metabase#15975)",
+  ),
+    () => {
+      cy.findByLabelText("Client ID").type("fake-client-id");
+      saveSettings();
+
+      cy.findByText("Invalid Google Sign-In Client ID");
+    };
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/admin/settings/sso/google.cy.spec.js:34]: @noahmoss I didn't notice this before, but this test never runs. The arrow function should be the second argument of the `it()` function like this:
```js
it("should do somehting", ()=> {});
```

Comment (noahmoss) [reply frontend/test/metabase/scenarios/admin/settings/sso/google.cy.spec.js:34]: Oh you're right. Seems like it's already been fixed?
