### PR TITLE
fix(embed-js): black background is shown on systems with dark mode preferences

### LINKED ISSUE #65533: Embedded Analytics JS shows a black background on systems with OS dark mode preferences
### Describe the bug

If we try to render a simple Embedded Analytics JS iframe on systems with OS dark mode preferences set, it shows a black background in place of the usually transparent one:

Image

### To Reproduce

1. Set your system to OS dark mode

2. Use the following snippet.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>EAJS</title>
  </head>
  <script defer src="http://localhost:3000/app/embed.js"></script>
  <script>
    function defineMetabaseConfig(config) {
      window.metabaseConfig = config;
    }
  </script>

  <script>
    defineMetabaseConfig({
      useExistingUserSession: true,
      instanceUrl: "http://localhost:3000",
    });
  </script>

  <body>
    <metabase-question
      question-id="18"
      is-save-enabled="false"
      with-title="true"
      with-downloads="false"
      initial-sql-parameters="{}"
      drills="true"
    ></metabase-question>
  </body>
</html>

```

3. You should see the content has a black background as opposed to transparent.

### Expected behavior

There should be no black background.

### Logs

_No response_

### Information about your Metabase installation

```JSON
-
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by heypoom**
Closes #65533
Closes EMB-966

Conditionally applies the change from #64324 which was causing EAJS to display a black background color:

CleanShot 2568-11-06 at 20 29 49@2x

The reason for this is that EAJS iframes are transparent by default, and the meta tag sets the iframe's background color to follow system preferences (i.e. light or dark). Even if users are on dark mode, that should not set the background to dark by default.

I tried setting `bg="bg-primary"`, but that still causes a flash of dark background while the React components are being loaded.

For now, we simply stop applying `color-scheme` in EAJS.

### CODE REVIEW

**Comment by heypoom** [comment]
(Let me check if I can conditionally do this, so it only affects EAJS)

**Review by lorem--ipsum — APPROVED** [review]

File: src/metabase/server/routes/index.clj [hunk 1]
```diff
@@ -78,33 +78,35 @@
         (throw (Exception. message e))))))
 
 (defn- template-parameters
```
Comment (heypoom) [inline src/metabase/server/routes/index.clj:80]: Click on "Minimize comments" to review

Image

**Review by lorem--ipsum — APPROVED** [review]

**Review by sansolovyov — APPROVED** [review]
