### PR TITLE
Fix column scaling ("Multiply by a number") bugs

### LINKED ISSUE #12214: Manual Y axis min/max don't take the "Multiply by" factor into account
**Describe the bug**
With the "Multiply by" factor set on Y axis, the manual min and max axis settings expect values on original scale instead of on the multiplied scale.

**To Reproduce**
1. Create a line chart.
2. Set Y multiplication factor (e.g. 0.000453 for metric tons to pounds).
3. Turn off the "Automatic Y axis range" and set your own min and max values.
4. Notice you have to input the values for original data scale (before multiplication).

**Expected behavior**
User would expect to use the same scale he sees on chart after setting the multiplication factor (i.e. min and max should be applied after the multiplication instead of before).

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.165-103.209.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.26-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-25",
      "tag": "v0.34.3",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Severity**
A nuisance, as I have to convert values back and forth.

### LINKED ISSUE #43536: Using scaling on a question with multiple y-axis columns breaks tool-tips and y-axis label formatting
### Multiple Y-axis columns breaks with scaling breaks chart

Since we only use one of the columns targeting a specific y-axis (left or right), we may or may not apply the column `scale` factor. This can result in an incorrectly displayed chart - i.e. plotted data points do not align with y-axis values. And, tool-tip values do not align with actual values.

---
**1. Multiple Y-axis columns breaks y-axis formatting**

image

image

image

---
**2. Multiple Y-axis columns breaks tool-tip values**

image

image

As you can see, the scaling factor had not effect on the chart display or tool-tip values.

### PR DESCRIPTION
**Pull request by JesseSDevaney**
### Issues Fixed

- Closes: https://github.com/metabase/metabase/issues/12214
- Closes: https://github.com/metabase/metabase/issues/43536

---
### Manual Y axis min/max don't take the "Multiply by" factor into account (#12214)

**Demo**

https://github.com/metabase/metabase/assets/22608765/8e398917-d6e5-4b8a-b145-ef83e249c74b

**How to Verify**
1. Create a line chart with column scaling added to the metric/y-axis column
2. Turn on `"Linear"` y-axis scale
3. Turn off `"Auto y-axis range"
4. Input a custom range that is outside the bounds of the current min/max
   - customMin < minimum dataset value
   - customMax > maximum dataset value
5. See that the exact values you inputted are selected
6. Go back to step 1->6 and verify with:
   - Different y-axis scales: `["Log", "Pow"]`
   - Different chart types: `["Bar", "Area", "Combo", "Scatter", "Waterfall", "Stacked Bar", "Stacked Area"]`

**Acceptance Criteria**
- [ ] Column scaling/`multiply by` factor should still work as expected
- [ ] The custom y-axis range given should be used as is and should not have to be adjusted based on data transformations - y-axis scale type (linear, pow, log) and metric value scaling
  - [ ] This behavior should be extended to all relevant charts (line, area, bar, scatter, waterfall, stacked/non-stacked)
- [ ] Loki variant added to verify and enforce the expected behavior

---
### Using scaling on a question with multiple y-axis columns breaks tool-tips and y-axis label formatting (#43536)

**Demo**

https://github.com/metabase/metabase/assets/22608765/b396b5e7-f041-4902-af79-e5506e97d778

**How to Verify**
1. Create a line chart with multiple aggregations (`["Sum of Total", "Sum of Subtotal"]`) and one breakout (`"Created at: Year"`)
2. Toggle on data labels: `"Show values for data points"`
3. Set both metrics/y-axis columns selected to use the left y-axis.
4. Add column scaling to the either one of the metrics (but do not both with the same value)
5. See that the charts are plotted and behave as expected.
   - All of the data point values line up with the correct corresponding y-axis tick value
   - All of the data point values behave as expected: i.e. are displaying the correct column scaled value
6. Update the chart type to be stacked bar/stacked area
7. Turn the data labels on for the inside stacked segments as well (`"Both"`)
8. See that the charts inside labels and bar sizes relative to their values behave as expected.
9. Hover over one of the stacks and verify that the tool-tip contains the correct values for both series (correct values are the correctly scaled values based off of each column's own scale factor)

**Acceptance Criteria**
- [ ] Using column scaling with multiple y-axis metrics should generate the chart as expected
  - [ ] If one column uses scaling and the other does not, we should still see that each of the plotted data points line up with the correct corresponding y-axis tick value
- [ ] E2E test has been added to verify and enforce the expected behavior

### CODE REVIEW

**Review by cdeweyx — APPROVED** [review]

File: frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts [hunk 1]
```diff
@@ -634,14 +636,18 @@ const createSeriesLabelsFormatter = (
 ) =>
   cachedFormatter((value: RowValue) => {
     if (typeof value !== "number") {
-      return " ";
```
Comment (EmmadUsmani) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts:637]: I think there may have been a reason we did `" "` instead of `""`, I remember Sasha wrote a comment about it but I can't find it now. To be safe maybe we should just keep it as a space.

File: frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts [hunk 2]
```diff
@@ -368,7 +368,7 @@ export const buildEChartsStackLabelOptions = (
       const value = datum[seriesModel.dataKey];
 
       if (typeof value !== "number") {
-        return " ";
```
Comment (EmmadUsmani) [inline frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts:371]: Same here, let's keep it as a space

**Review by EmmadUsmani — APPROVED** [review]
Looks good! Could you add some more specs similar to the line chart one you created before merging? Ideally one for the scatter plot and waterfall chart would be nice, since they use different codepaths

File: frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts [hunk 3]
```diff
@@ -628,6 +628,32 @@ const interpolateTimeSeriesData = (
...
+      }
+    }
+    return transformedRecord;
+  };
+
+  return dataset.map(datum => {
+    return transformFn(datum);
+  });
+}
+
```
Comment (JesseSDevaney) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts:656]: We only need to use the scale factor once for transforming the dataset and then we can disregard the fact that it was ever scaled thereon after. Eventually it would nice to rip out the additional scaling in the value formatter, so that we do not have to maintain that across many different contexts.

File: frontend/src/metabase/visualizations/shared/utils/data.ts
Comment (JesseSDevaney) [inline frontend/src/metabase/visualizations/shared/utils/data.ts:1]: Porting the value scaling to RowCharts since they are not implemented as an ECharts chart yet.

File: frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts (hunk 1 above)
Comment (JesseSDevaney) [reply frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts:637]: I actually created an ECharts patch on a prior PR ([#42985](https://github.com/metabase/metabase/pull/42985)) that was specifically addressing how label are handled by ECharts.
If we keep the `" "` instead of a `""`, it will cause non-empty labels to potentially be hidden because `" "` still has a non-zero length and hence non-zero width and height.

File: frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts (hunk 2 above)
Comment (JesseSDevaney) [reply frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts:371]: I actually created an ECharts patch on a prior PR ([#42985](https://github.com/metabase/metabase/pull/42985)) that was specifically addressing how label are handled by ECharts.
If we keep the `" "` instead of a `""`, it will cause non-empty labels to potentially be hidden because `" "` still has a non-zero length and hence non-zero width and height.
