### PR TITLE
Performance: partial data-permissions graph refactor

### LINKED ISSUE #44768: PUT /api/permissions/graph is 7x slower in v50 than in v49
### Describe the bug

There's a big performance regression when you change permissions on v50. This impacts customers with big permission graphs

### To Reproduce

1) run the following script to create big permission graphs (please use host, user, password, lower and upper bounds and also ensure you have a postgres sample db added
```
import requests, os

# Authentication
login_url = f"{os.environ['host']}/api/session"
login_payload = {"username": f"{os.environ['user']}", "password": f"{os.environ['password']}"}
session = requests.Session()
response = session.post(login_url, json=login_payload)

for i in range(int(os.environ['lower']), int(os.environ['upper'])):
    elapsed = 0
    # Create database
    create_db_url = f"{os.environ['host']}/api/database"
    create_db_payload = {
        "is_on_demand": False,
        "is_full_sync": False,
        "is_sample": False,
        "cache_ttl": None,
        "refingerprint": False,
        "auto_run_queries": True,
        "schedules": {},
        "details": {
            "host": "postgres-data1",
            "port": 5432,
            "dbname": "sample",
            "user": "metabase",
            "password": "metasample123",
            "schema-filters-type": "all",
            "ssl": False,
            "tunnel-enabled": False,
            "advanced-options": False,
        },
        "name": f"postgres-data-{i}",
        "engine": "postgres"
    }
    response = session.post(create_db_url, json=create_db_payload)
    db_time = response.elapsed
    db_id = response.json()["id"]

    # Create group
    create_group_url = f"{os.environ['host']}/api/permissions/group"
    create_group_payload = {"name": f"data{i}"}
    response = session.post(create_group_url, json=create_group_payload)
    group_time = response.elapsed

    group_id = response.json()["id"]

    # Create user
    create_user_url = f"{os.environ['host']}/api/user"
    create_user_payload = {
        "first_name": f"data{i}",
        "last_name": f"data{i}",
        "email": f"data{i}@a.com",
        "user_group_memberships": [
            {"id": 1, "is_group_manager": False},
            {"id": group_id, "is_group_manager": False},
        ],
    }
    response = session.post(create_user_url, json=create_user_payload)
    user_time = response.elapsed

    # Update permissions
    get_permissions_url = f"{os.environ['host']}/api/permissions/graph"
    response = session.get(get_permissions_url)
    graph_time = response.elapsed

    # Get the graph revision
    revision_id = response.json()["revision"]

    update_permissions_url = f"{os.environ['host']}/api/permissions/graph"
    update_permissions_payload = {
        "groups": {
            group_id: {
                db_id: {
                    "data": {
                        "native": "write",
                        "schemas": "all"
                    }
                }
            }
        },
        "revision": revision_id
    }
    response = session.put(update_permissions_url, json=update_permissions_payload)
    permission_time = response.elapsed

    # Now change permissions 5 more times
    response = session.get(get_permissions_url)
    revision_id = response.json()["revision"]
    update_permissions_payload = {
        "groups": {
            group_id: {
                db_id: {
                    "data": {
                        "native": "none",
                        "schemas": "all"
                    },
                    "data_model": {
                        "schemas": "all"
                    },
                    "download": {
                        "schemas": "full"
                    },
                    "details": "yes"
                }
            }
        },
        "revision": revision_id
    }
    response = session.put(update_permissions_url, json=update_permissions_payload)
    # One
    response = session.get(get_permissions_url)
    revision_id = response.json()["revision"]
    update_permissions_payload = {
        "groups": {
            group_id: {
                db_id: {
                    "data": {
                        "native": "write",
                        "schemas": "all"
                    }
                }
            }
        },
        "revision": revision_id
    }
    response = session.put(update_permissions_url, json=update_permissions_payload)

    # Two
    response = session.get(get_permissions_url)
    revision_id = response.json()["revision"]
    update_permissions_payload = {
        "groups": {
            group_id: {
                db_id: {
                    "data": {
                        "native": "none",
                        "schemas": "all"
                    },
                    "data_model": {
                        "schemas": "all"
                    },
                    "download": {
                        "schemas": "full"
                    },
                    "details": "yes"
                }
            }
        },
        "revision": revision_id
    }
    response = session.put(update_permissions_url, json=update_permissions_payload)

    # Three
    response = session.get(get_permissions_url)
    revision_id = response.json()["revision"]
    update_permissions_payload = {
        "groups": {
            group_id: {
                db_id: {
                    "data": {
                        "native": "write",
                        "schemas": "all"
                    }
                }
            }
        },
        "revision": revision_id
    }
    response = session.put(update_permissions_url, json=update_permissions_payload)

    # Four
    response = session.get(get_permissions_url)
    revision_id = response.json()["revision"]
    update_permissions_payload = {
        "groups": {
            group_id: {
                db_id: {
                    "data": {
                        "native": "none",
                        "schemas": "all"
                    },
                    "data_model": {
                        "schemas": "all"
                    },
                    "download": {
                        "schemas": "full"
                    },
                    "details": "yes"
                }
            }
        },
        "revision": revision_id
    }
    response = session.put(update_permissions_url, json=update_permissions_payload)

    # Five
    response = session.get(get_permissions_url)
    revision_id = response.json()["revision"]
    update_permissions_payload = {
        "groups": {
            group_id: {
                db_id: {
                    "data": {
                        "native": "write",
                        "schemas": "all"
                    }
                }
            }
        },
        "revision": revision_id
    }
    response = session.put(update_permissions_url, json=update_permissions_payload)

    print(f"{i} db: {db_time} group: {group_time} user: {user_time} graph: {graph_time} permission: {permission_time}")
```
2) now with a big permissions graph use a telemetry tool to get the times

### Expected behavior

Performance should be equal or a little slower due to permissions being more atomic than on v49

### Logs

NA

### Information about your Metabase installation

```JSON
v50
```

### Severity

P1

### Additional context

[GET-api-permissions-graph-49.json](https://github.com/user-attachments/files/15992266/GET-api-permissions-graph-49.json)
[PUT-api-permissions-graph-49.json](https://github.com/user-attachments/files/15992272/PUT-api-permissions-graph-49.json)
[GET-api-permissions-graph-50.json](https://github.com/user-attachments/files/15992274/GET-api-permissions-graph-50.json)
[PUT-api-permissions-graph-50.json](https://github.com/user-attachments/files/15992278/PUT-api-permissions-graph-50.json)

### PR DESCRIPTION
**Pull request by sloansparger**
Closes #44768

### Description

Updates to the BE (code already approved) and FE changes to allow for partial editing of permissions graphs in the admin settings. This change detects which groups have had some kind of modification within the graph and only sends that part of the graph / omits unmodified groups in the update request body. The backend now only sends a response with just the modified groups, which the FE will now merge back into the client's graph.

### How to verify

The changes _should_ not change the user experience in any way than increasing performance. Please verify that modifying permissions continue to do what you'd expect.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+
+  return Object.fromEntries(
+    Object.entries(advancedPermissions).map(([key, items]) => {
+      const modified = (items || []).filter(item =>
+        groupIds.has(`${item.group_id}`),
+      );
+      return [key, modified];
+    }),
+  );
+}
```
Comment (iethree) [inline frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts:45]: I think this and anything else dealing with advanced permissions needs to be in the advanced permissions enterprise plugin

File: frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+function getModifiedGroupIdsInGraph(
+  groupIds: string[],
+  originalDataPermissions: GroupsPermissions,
+  newDataPermissions: GroupsPermissions,
+) {
+  // find only the groupIds that have had some kind of modification made in their permissions graph
+  return groupIds.filter(groupId => {
+    return !_.isEqual(
+      newDataPermissions[groupId as unknown as number],
```
Comment (iethree) [inline frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts:25]: if this is really a string, shouldn't we 
```suggestion
      newDataPermissions[Number(groupId)],
```

?

File: frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+function getModifiedAdvancedPermissions(
+  advancedPermissions: AdvancedPermissions,
+  modifiedGroupIds: string[],
+) {
+  const groupIds = new Set(modifiedGroupIds);
+
+  return Object.fromEntries(
+    Object.entries(advancedPermissions).map(([key, items]) => {
+      const modified = (items || []).filter(item =>
+        groupIds.has(`${item.group_id}`),
```
Comment (iethree) [inline frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts:40]: maybe make this cast a bit more explicit?
```suggestion
        groupIds.has(String(item.group_id})),
```

File: frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+
+  const allGroupIds = _.uniq([
+    ...Object.keys(originalDataPermissions),
+    ...Object.keys(newDataPermissions),
+  ]);
+
+  const latestPermissionsEntries = allGroupIds.map(groupId => {
+    const permissions =
+      newDataPermissions[groupId as unknown as number] ??
+      originalDataPermissions[groupId as unknown as number];
```
Comment (iethree) [inline frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts:92]: same as above, if this cast is necessary, maybe we can at least get an apologetic comment explaining where the type conflict is?

File: frontend/src/metabase/plugins/index.ts [hunk 5]
```diff
@@ -117,7 +117,7 @@ export const PLUGIN_ADMIN_PERMISSIONS_TABLE_FIELDS_POST_ACTION = {
 export const PLUGIN_DATA_PERMISSIONS: {
   permissionsPayloadExtraSelectors: ((
     state: State,
-  ) => Record<string, unknown>)[];
+  ) => [Record<string, undefined | { group_id: string }[]>, string[]])[];
```
Comment (iethree) [inline frontend/src/metabase/plugins/index.ts:120]: ❤️

File: enterprise/frontend/src/metabase-enterprise/sandboxes/selectors.ts [hunk 6]
```diff
@@ -24,6 +25,33 @@ export const getGroupTableAccessPolicy = (
   );
 };
 
+// return new and altered policies
+export const getGroupIdsOfModifiedPolices = (state: SandboxesState) => {
```
Comment (iethree) [inline enterprise/frontend/src/metabase-enterprise/sandboxes/selectors.ts:29]: can we get some unit test coverage on this function?

**Review by iethree — CHANGES_REQUESTED** [review]
functionality looks great 🥳 

Would love some more clarity on some of the type casting and we need some tests on the sandboxing selector.

File: frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts (hunk 1 above)
Comment (sloansparger) [reply frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts]: Great feedback, I ended up solving this in another way all together. Since impersonation and sandbox state always gets reset on save, we can just send it directly along without picking values off. I refactored the main `get` function in this file to accept an `externallyModifiedGroupIds` so that we can still pick values off of the groups graph when advanced perms are updated, while removing references to advanced permissions in this file.

File: frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts (hunk 2 above)
Comment (sloansparger) [reply frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts]: yeah, we constructed the permissions graph interface to be keyed on `GroupId` which is a `number`. this doesn't work as expected since javascript converts numbers to strings for object keys. I solved this by making a change to the type.

File: frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts (hunk 3 above)
Comment (sloansparger) [reply frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts]: ended up removing this function

File: frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts (hunk 4 above)
Comment (sloansparger) [reply frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts:47]: also fixed

File: enterprise/frontend/src/metabase-enterprise/sandboxes/selectors.ts [hunk 7]
```diff
@@ -1,4 +1,5 @@
 import { createSelector } from "@reduxjs/toolkit";
+import _ from "underscore";
```
Comment (iethree) [inline enterprise/frontend/src/metabase-enterprise/sandboxes/selectors.ts:2]: I think this is unused now? I think `_` gets an exception from unused imports rule

File: frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts (hunk 4 above)
Comment (iethree) [reply frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts:47]: did you forget a commit? since you update the type, these casts aren't necessary anymore

**Review by iethree — APPROVED** [review]
👏  very nice

(but do clean up these couple little things) 👇

**Review by npfitz — APPROVED** [review]
👍 from me. I did notice some situations where we were sending more data than was actually needed (changing a permission and then changing it back usually still counts as a change), but this is still an improvement over what sending the entire graph on update. Good work folks!
