### PR TITLE
fix reset password flow

### LINKED ISSUE #24700: After a password change, users should just be let in
**Describe the bug**
After I reset my password, I should be able to just use the product.
Currently, it asks me to log in again. But extra-brokenly, it's already logged me in, and shows that message in a small frame, next to the navigation.

**To Reproduce**
1. Do something to forget your password
2. Click on forget password (in an instance which supports it)
3. Click the link in the email, reset it
4. Read the message

**Expected behavior**
This could be controversial.
Some folks may expect me to need to log in again, as some sort of extra security measure.
IMO we should just log people in, and show a toast in the bottom-left saying something like "Your password have been reset, welcome back" (and if we can detect that it's the first time, "Your password has been set, welcome")

**Screenshots**
image

**Information about your Metabase Installation:**
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "5.4.196-108.356.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-07-29",
      "tag": "v1.43.4.2",
      "branch": "release-x.43.x",
      "hash": "7809f82"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Severity**
Low severity.

**Additional context**
Using my suggested solution would also close #5063.

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/24700

## Changes

Redirect users to the home page after they changed their password and show a toast message. I've used the existing localized text message so that we can backport the fix.

Screen Shot 2022-08-11 at 11 54 57 PM

## How to verify
Set up emails on your Metabase instance:
You can use a container with maildev: ` docker run -p 80:80 -p 25:25 maildev/maildev` 

- Log out
- Visit the login page and click the forgot password link
- Go through the reset password process
- Ensure you end up on the home page logged in the app

### CODE REVIEW

File: frontend/src/metabase/auth/components/ResetPassword/ResetPassword.tsx [hunk 1]
```diff
@@ -23,13 +21,17 @@ export interface ResetPasswordProps {
   onResetPassword: (token: string, password: string) => void;
   onValidatePassword: (password: string) => void;
   onValidatePasswordToken: (token: string) => void;
+  showToast: (toast: { message: string }) => void;
```
Comment (ranquild) [inline frontend/src/metabase/auth/components/ResetPassword/ResetPassword.tsx:24]: nit: `onShowToast`?

**Review by ranquild — APPROVED** [review]
