### PR TITLE
Fix Snowflake/Redshift filtering on date for timestamp with time zone columns

### LINKED ISSUE #8804: Snowflake JDBC driver incorrectly converts JDBC dates with a timezone
When dealing with the older (pre JDK 8) dates, the dates are always converted to the JVM timezone. The can present a problem when using Metabase's `report-timezone` feature, which will set the database sessions timezone to the user configured value. When filtering based on a date and the `report-timezone` is specified, that date needs to also be in the report timezone. Since the JVM always converts the date to the JVM's timezone (and there is no tracking of an "original" timezone) the JDBC library allows the timezone to be included as a [separate parameter](https://github.com/metabase/metabase/blob/master/src/metabase/driver/generic_sql/query_processor.clj#L552).

This doesn't appear to work correctly with Snowflake as when that parameter is included, it looks to be double converting the values. Creating this to track the issue and for linking to the tests with the incorrect values so it can be fixed after Snowflake support is merged.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #11643: Quarterly Date Filter different on Dashboard than on Question
**Describe the bug**
When clicking on the a question from a dashboard with a quarterly date filter, the "<FIELD> is Q4 - 2019" filter generates SQL that causes records with a date equal to the last date in the quarter to be excluded. 

**Update**: We originally submitted this bug report for v0.33.7.3. We then tried to deploy v0.34.0 and the problem got worse. In v0.34.0, the problem is now present on the dashboard AND the question AND further, records from the last day of the previous quarter are included: https://github.com/metabase/metabase/issues/11643#issuecomment-571341318

**To Reproduce**
1. Create a dashboard with a quarterly date filter and add a question using that filter
2. Set the date filter on the dashboard to "Q4 - 2019"
3. Insert a record in the data with a value in the filter field of "Dec 31, 2019 12:00AM"
4. Click on the question from the dashboard
5. See the question 

**Expected behavior**
Expected: Question result includes records with a value of "Dec 31, 2019 12:00AM" in the date field.

**Screenshots**
The question on the dashboard (with filter):
Question on Dashboard

What you see after clicking on the question:
After Clicking

Here's the same question/filters with a table view:
Table - After Clicking

As a workaround, I changed the filter from "FIELD is Q4 - 2019" to "FIELD between October 1, 2019 and December 31, 2019". The question now shows the same result as the dashboard:
Change Filter to Between

 And if I change the visualization to Table, the row with "Dec 31, 2019 12:00AM" in the field I'm filtering on appears:
Table - Change Filter to Between

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome/79.0.3945.88 
- Your operating system: MacOS 10.4.6
- Your databases: Redshift
- Metabase version: v0.33.7.3 => v0.34.0 is also broken, but in a different way. see my comment
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
Critical, dashboards are showing in correct data in v0.34.0

**Additional context**
The SQL generated at the Question when the filter is "FIELD is Q4 - 2019" is:
After Clicking - SQL

While the SQL when the filter is "FIELD between October 1, 2019 and December 31, 2019" is:
Change Filter to Between - SQL

The hour is different in the filter timestamp (4 in the first case, 5 in the second). The timezone for our Metabase instance is US/Eastern. Could this bug be caused by some sort of DST related issue?

### LINKED ISSUE #19910: Data mismatch between custom question and raw sql query with Redshift
**Describe the bug**
Data mismatch when using Redshift custom Query VS Raw SQL query.

Screenshot 2022-01-25 at 6 33 34 PM

**Logs**
- Not needed

**To Reproduce**
1. Connect Redshift DB
2. Create table which has timestamp with timezone column 
3. Set time zone in settings to Asia/Culcutta
4. Ask question via Custom question, add date filter like date_created < "something"  and check count of rows
5. Convert same custom question to SQL query and execute 
Screenshot 2022-01-25 at 6 41 18 PM

6. Check count of rows, you will find mismatch 

**Expected behavior**
Ideally when we convert "Custom Question" to SQL query it should return same results. 

**Screenshots**

Screenshot 2022-01-25 at 6 45 05 PM
Screenshot 2022-01-25 at 6 45 43 PM

**Severity**
Annoying & Misleading, our analytics team can't rely on data when we query via Custom question.

**Additional context**
I tried debugging the problem found out due to certain reason default question makes query in GMT timezone but when we convert it to SQL question it has timezone data in it so it shows different but correct and expected data.

I tired setting timezone at user level and still it didn't work, because somehow queries made by custom question overrides that.  
```sql
ALTER USER dbuser SET timezone to 'America/New_York';
```

Also checked Metabase connector code, it seems its setting timezone there - [perm link](https://github.com/metabase/metabase/blob/912c76962808bdce4159263ce195a27620861f28/modules/drivers/redshift/src/metabase/driver/redshift.clj#L119)
```
(defmethod sql-jdbc.execute/set-timezone-sql :redshift
  [_]
  "SET TIMEZONE TO %s;")
```

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.252-131.483.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-16",
      "tag": "v0.41.5",
      "branch": "release-x.41.x",
      "hash": "fbfffc6"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #39769: Filtering by a Specific Date in Snowflake will bring inaccurate results
### Describe the bug

Filtering by "Specific date" filter in Snowflake will bring wrong results

### To Reproduce

1. Create a table in Snowflake with the SQL below the steps
2. Create a GUI * from table and put it in a dashboard
3. Add a Relative dates filter and connect it to the card
4. Select "Specific dates" as a filter, "On" and filter by "November 12th, 2023"
5. See that the card will show records from November 13th as well
Screenshot 2024-03-07 at 11 39 29 AM

<details>
<summary>SQL for creating table and adding data with date time column</summary>

CREATE TABLE sample_table (
    id INTEGER,
    user_name VARCHAR,
    created_at TIMESTAMP
);

-- Insert sample data for each hour of each day from November 10 to November 15
INSERT INTO sample_table (id, user_name, created_at)
SELECT
    ROW_NUMBER() OVER (ORDER BY day, hour) AS id,
    'User_' || ROW_NUMBER() OVER (ORDER BY day, hour) AS user_name,
    DATEADD('MINUTE', (hour + day * 24) * 60, '2023-11-10 00:00:00') AS created_at
FROM
    (
        SELECT 0 AS day UNION ALL
        SELECT 1 UNION ALL
        SELECT 2 UNION ALL
        SELECT 3 UNION ALL
        SELECT 4 UNION ALL
        SELECT 5
    ) AS days
CROSS JOIN
    (
        SELECT 0 AS hour UNION ALL
        SELECT 1 UNION ALL
        SELECT 2 UNION ALL
        SELECT 3 UNION ALL
        SELECT 4 UNION ALL
        SELECT 5 UNION ALL
        SELECT 6 UNION ALL
        SELECT 7 UNION ALL
        SELECT 8 UNION ALL
        SELECT 9 UNION ALL
        SELECT 10 UNION ALL
        SELECT 11 UNION ALL
        SELECT 12 UNION ALL
        SELECT 13 UNION ALL
        SELECT 14 UNION ALL
        SELECT 15 UNION ALL
        SELECT 16 UNION ALL
        SELECT 17 UNION ALL
        SELECT 18 UNION ALL
        SELECT 19 UNION ALL
        SELECT 20 UNION ALL
        SELECT 21 UNION ALL
        SELECT 22 UNION ALL
        SELECT 23
    ) AS hours;
</details>

### Expected behavior

Should only bring the results from that day

### Logs

query in snowflake
```
SELECT "PUBLIC"."SAMPLE_TABLE_2"."ID" AS "ID", "PUBLIC"."SAMPLE_TABLE_2"."USER_NAME" AS "USER_NAME", "PUBLIC"."SAMPLE_TABLE_2"."CREATED_AT" AS "CREATED_AT" 
FROM "sample"."PUBLIC"."SAMPLE_TABLE_2" 
WHERE ("PUBLIC"."SAMPLE_TABLE_2"."CREATED_AT" >= ?) AND ("PUBLIC"."SAMPLE_TABLE_2"."CREATED_AT" < ?) LIMIT 2000

-- {"pulseId":null,"serverId":"adbf7a69-c037-43f2-9b43-bb98001f852f","client":"Metabase","queryHash":"233e5c2a605bb015ded3bc42a539d1c9607a48eae959eed9d316e10ce199d526","queryType":"query","cardId":114,"dashboardId":35,"context":"dashboard","userId":1,"databaseId":34}
```

### Information about your Metabase installation

```JSON
- Metabase 48.8
```

### Severity

P2

### Additional context

_No response_

### LINKED ISSUE #41863: Snowflake UNIX timestamps interpreted as being in report timezone rather than UTC
Leads to wrong values and incorrect results when filtering.

This is broken; see `metabase.query-processor-test.date-bucketing-test/sanity-check-test` (disabled for Snowflake) for example.

### LINKED ISSUE #41866: Snowflake always returns times truncated second precision, we should fix this for tests
Mostly important for tests, since all of the other DBs use millisecond precision meaning Snowflake results are different for no reason.

The default output format is `HH24:MI:SS` apparently 

https://docs.snowflake.com/en/sql-reference/parameters#time-output-format

```clj
(mt/test-driver :snowflake
  (mt/with-temporary-setting-values [report-timezone "US/Pacific"]
    (mt/dataset attempted-murders
      (mt/rows
       (qp/process-query
        (-> (mt/native-query
              {:query "SELECT time '00:23:18.331', '00:23:18.331'::time(9), time_from_parts(0, 23, 18, 123456789)"})
            (assoc-in [:middleware :format-rows?] false)))))))
;; => [[#t "00:23:18" #t "00:23:18" #t "00:23:18"]]
```

### LINKED ISSUE #42073: Snowflake temporal extract operators like `hour-of-day` do not respect report timezone
If the report timezone is `-10:00` we would expect `get-hour` for a `timestamptz` like `"2011-12-31T15:30:54-10:00"` to return `15`, however it currently returns `1` (value for the timestamp when it is normalized to UTC)

Try enabling `metabase.query-processor-test.timezones-test/general-timezone-support-test` for Snowflake to see more examples of things that are broken

```clj
(deftest x-test
  (mt/test-driver :snowflake
    (mt/dataset all-dates-leap-year
      (mt/with-temporary-setting-values [report-timezone "Pacific/Honolulu"]
        (let [query (mt/mbql-query alldates
                      {:expressions {"hour-of-day" [:temporal-extract $dt :hour-of-day]}
                       :fields      [$dt
                                     [:expression "hour-of-day"]]
                       :order-by [[:asc $id]]
                       :limit 5})]
          (mt/with-native-query-testing-context query
            (is (= [["2011-12-31T15:30:54-10:00" 15]
                    ["2012-01-01T15:30:54-10:00" 15]
                    ["2012-01-02T15:30:54-10:00" 15]
                    ["2012-01-03T15:30:54-10:00" 15]
                    ["2012-01-04T15:30:54-10:00" 15]]
                   (mt/rows (qp/process-query query))))))))))
```

```                   
Native Query =
SELECT
  "source"."dt" AS "dt",
  "source"."hour-of-day" AS "hour-of-day"
FROM
  (
    SELECT
      "PUBLIC"."alldates"."id" AS "id",
      "PUBLIC"."alldates"."dt" AS "dt",
      DATE_PART("hour", "PUBLIC"."alldates"."dt") AS "hour-of-day"
    FROM
      "2024_04_30_e15f5997_60ab_4c7d_8fde_164a001da04c_all-dates-leap-year"."PUBLIC"."alldates"
  ) AS "source"
ORDER BY
  "source"."id" ASC
LIMIT
  5

{:params nil}


expected: [["2011-12-31T15:30:54-10:00" 15]
           ["2012-01-01T15:30:54-10:00" 15]
           ["2012-01-02T15:30:54-10:00" 15]
           ["2012-01-03T15:30:54-10:00" 15]
           ["2012-01-04T15:30:54-10:00" 15]]
  actual: [["2011-12-31T15:30:54-10:00" 1]
           ["2012-01-01T15:30:54-10:00" 1]
           ["2012-01-02T15:30:54-10:00" 1]
           ["2012-01-03T15:30:54-10:00" 1]
           ["2012-01-04T15:30:54-10:00" 1]]                   
```

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #8804
Fixes #11643
Fixes #19910
Fixes #39769
Fixes #41863
Fixes #41866
Fixes #42073

The Snowflake JDBC driver still doesn't support Java 8 `java.time` classes, which means we were setting things like `OffsetDateTime` as a `java.sql.Timestamp`... even worse, it ignores attached `java.util.Calendar`s (`java.sql.Timestamp` + `java.util.Calendar` is basically the pre-Java-8 way of setting a `timestamp with time zone` value in JDBC)... we actually had code to do the right thing for Snowflake from #11718 but it only worked for `ZonedDateTime`:

https://github.com/metabase/metabase/blob/b93e99d/modules/drivers/snowflake/src/metabase/driver/snowflake.clj?rgh-link-date=2024-04-25T21%3A33%3A43Z#L618-L632

In #40530 I fixed related issues for `date = date` filtering but there were still issues with `timestamp_tz = date` filtering. 

I ended up changing the Snowflake QP code to just output timestamp literals directly, e.g. 

```sql
'2024-04-25 17:58:00 -07:00'::timestamp_tz
```

instead of 

```sql
? -- a java.sql.Timestamp 
```

so we can be sure it's doing the right thing and so we're no longer at the mercy of a poorly-implemented JDBC driver.

I had to fix some stuff with native query parameter compilation, for whatever reason it wasn't calling `->honeysql` for `java.time` classes and just assuming everyone wanted `?`; now it's working correctly.

### CODE REVIEW

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 1]
```diff
@@ -576,65 +601,11 @@
...
-  [_ t]
-  (format "'%s %s %s'::timestamp_tz" (t/local-date t) (t/local-time t) (t/zone-offset t)))
-
-(defmethod unprepare/unprepare-value [:snowflake ZonedDateTime]
-  [driver t]
-  (unprepare/unprepare-value driver (t/offset-date-time t)))
-
-(defmethod unprepare/unprepare-value [:snowflake OffsetTime]
-  [driver t]
-  (unprepare/unprepare-value driver (t/local-time (t/with-offset-same-instant t (t/zone-offset 0)))))
```
Comment (camsaul) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:589]: No longer needed since we don't parameterize these anymore.

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 2]
```diff
@@ -576,65 +601,11 @@
...
-        (log/tracef "(.getString rs %d) [TIME] -> %s -> %s" i (pr-str s) (pr-str t))
-        t))))
-
-(defmethod sql-jdbc.execute/read-column-thunk [:snowflake Types/TIME_WITH_TIMEZONE]
-  [_ ^ResultSet rs _ ^Integer i]
-  (fn []
-    (when-let [s (.getString rs i)]
-      (let [t (u.date/parse s)]
-        (log/tracef "(.getString rs %d) [TIME_WITH_TIMEZONE] -> %s -> %s" i (pr-str s) (pr-str t))
-        t))))
```
Comment (camsaul) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:616]: The `TIME` impl is exactly the same as the version in `metabase.driver.sql-jdbc.execute.legacy-impl`, which Snowflake would have used anyway, so I removed it. Snowflake doesn't have `TIME_WITH_TIMEZONE`, so this was dead code. But `metabase.driver.sql-jdbc.execute.legacy-impl` was missing `TIME_WITH_TIMEZONE` and `TIMESTAMP_WITH_TIMEZONE` impls so I moved them there since they look almost exactly like the other impls.

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 3]
```diff
@@ -576,65 +601,11 @@
...
-  [driver ps i t]
-  (sql-jdbc.execute/set-parameter driver ps i (t/sql-time (t/with-offset-same-instant t (t/zone-offset 0)))))
-
-(defmethod sql-jdbc.execute/set-parameter [::use-legacy-classes-for-read-and-set java.time.OffsetDateTime]
-  [driver ps i t]
-  (sql-jdbc.execute/set-parameter driver ps i (t/sql-timestamp (t/with-offset-same-instant t (t/zone-offset 0)))))
-
-(defmethod sql-jdbc.execute/set-parameter [:snowflake java.time.ZonedDateTime]
-  [driver ps i t]
-  (sql-jdbc.execute/set-parameter driver ps i (t/sql-timestamp (t/with-zone-same-instant t (t/zone-id "UTC")))))
```
Comment (camsaul) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:632]: No longer needed since we're generating SQL literals instead

File: src/metabase/driver/sql/parameters/substitution.clj [hunk 4]
```diff
@@ -58,7 +59,8 @@
 (defn- honeysql->prepared-stmt-subs
   "Convert X to a replacement snippet info map by passing it to HoneySQL's `format` function."
   [driver x]
-  (let [[snippet & args] (sql.qp/format-honeysql driver x)]
+  (let [honeysql         (sql.qp/->honeysql driver x)
+        [snippet & args] (sql.qp/format-honeysql driver honeysql)]
```
Comment (camsaul) [inline src/metabase/driver/sql/parameters/substitution.clj:63]: Parameter compilation code should call `->honeysql` on `java.time` arguments

File: src/metabase/driver/sql_jdbc/execute/legacy_impl.clj [hunk 5]
```diff
@@ -60,29 +60,45 @@
...
 (defmethod sql-jdbc.execute/read-column-thunk [::use-legacy-classes-for-read-and-set Types/TIME]
-  [_ ^ResultSet rs _ ^Integer i]
+  [_driver ^ResultSet rs _rsmeta ^Integer i]
   (fn []
     (when-let [s (.getString rs i)]
       (let [t (u.date/parse s)]
         (log/tracef "(.getString rs i) [TIME] -> %s -> %s" (pr-str s) (pr-str t))
         t))))
 
+(defmethod sql-jdbc.execute/read-column-thunk [::use-legacy-classes-for-read-and-set Types/TIME_WITH_TIMEZONE]
```
Comment (camsaul) [inline src/metabase/driver/sql_jdbc/execute/legacy_impl.clj:70]: Moved from Snowflake

File: test/metabase/query_processor/test_util.clj [hunk 6]
```diff
@@ -383,7 +383,7 @@
   also have this issue."
   [driver]
   ;; TIMEZONE FIXME — remove this and fix the drivers
-  (contains? #{:snowflake :oracle :redshift} driver))
+  (contains? #{:oracle :redshift} driver))
```
Comment (metamben) [inline test/metabase/query_processor/test_util.clj:386]: The docstring is out of date now.

**Review by metamben — APPROVED** [review]
