### PR TITLE
18180 better handle unauthenticated route

### LINKED ISSUE #18180: Handle React routes better for unauthenticated and not-setup instance
**Describe the bug**
It's currently possible to visit some routes unauthenticated, but there's no redirect to login.
This is almost just a tech debt issue, but given we're showing blank pages or some general pages, then leaving as bug.

**To Reproduce**
1. Logout
2. Try visiting
   1. `/user/edit_current` - blank page - this has been renamed to `/account/profile` in 41, but should have a redirect then
   2. `/_internal` - should this even be included in releases?
   3. `/dash/1` - blank page
   4. `/collections/create` - flashes "modal" and redirects to blank page

**Expected behavior**
Almost everything below line 246 should be part of the previous `MAIN` `IsAuthenticated`
https://github.com/metabase/metabase/blob/d012c89b17e61b9af984c49efed581ca1b4fe1c2/frontend/src/metabase/routes.jsx#L246
I don't think there's a way for an outside (non-user) receiver of alerts/subscriptions to unsubscribe from them via an unauthorized link in the email. I think there once was, but cannot see there's this option anymore, so shouldn't be a problem adding all routes to authenticated.

**Information about your Metabase Installation:**
Tested 0.40.5 and master

**Additional context**
Related to #15471 / #15636 / #15225 / #18155

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes #18180

- I intentionally leave `_internal` the same because it won't be included in the production build anyway.
- Other redirection should be outside the authenticated route otherwise the redirection won't work for unauthenticated users.

### CODE REVIEW

File: frontend/src/metabase/routes.jsx [hunk 1]
```diff
@@ -384,7 +387,7 @@ export const getRoutes = store => (
         })
       }
     />
-    <Redirect from="/dash/:dashboardId" to="/dashboard/:slug" />
+    <Redirect from="/dash/:dashboardId" to="/dashboard/:dashboardId" />
```
Comment (WiNloSt) [inline frontend/src/metabase/routes.jsx:390]: This wasn't working.

image

**Review by kulyk — APPROVED** [review]

**Comment by kulyk** [comment]
@WiNloSt should we backport it?
