### PR TITLE
Ghy-3466/relax the mysql minimum version constraint

### LINKED ISSUE #73297: Aurora MYSQL version without 60
I'm currently without version 60; Amazon Aurora doesn't support MySQL 8.4.0. Was this intended for all types of databases?
 
Image

### Logs

[4:13 PM]2026-04-16 16:11:01,108 ERROR core.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Metabase mysql DB version not supported (found 8.0.42 (8.0.42), required 8.4.0). Please upgrade your database to a supported version and try again.

### Information about your Metabase installation

```JSON
Metabase 0.60.2 is available. You're running 0.59.5.
```

### Severity

Medium

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bgrabow**
Closes https://github.com/metabase/metabase/issues/73297
Closes https://linear.app/metabase/issue/UXW-3908
Closes https://linear.app/metabase/issue/GHY-3466

### Description

In v60 we tightened the minimum app db version requirements, and started blocking application start-up if the requirements were not met. In anticipation of MySQL 8.0 going EOL at the end of April 2026 we updated the minimum MySQL version to 8.4. However, AWS Aurora doesn't support MySQL 8.4 or newer. (They added 8.4 to RDS 2 years ago, but Aurora still does not have it.) This presents a blocker for our customers using Aurora who want to upgrade Metabase but have no feasible way to upgrade their app db without switching hosting platforms/products.

This PR relaxes the MySQL requirement back to 8.0. When AWS Aurora supports a newer version we should consider tightening this minimum version requirement again.

### CODE REVIEW

**Review by perivamsi — APPROVED** [review]

File: mage/src/mage/bgrabow/ci_test_repl.clj [hunk 1]
```diff
@@ -144,7 +144,7 @@
 (defn- image->container-suffix
   "Derive a container name suffix from a Docker image string.
    e.g. 'circleci/mariadb:10.6' → 'mariadb-10-6'
-        'cimg/mysql:8.4'        → 'mysql-8-4'
+        'cimg/mysql:8.4'        → 'mysql-8-0'
```
Comment (galdre) [inline mage/src/mage/bgrabow/ci_test_repl.clj]: Not quite right.

**Review by galdre — APPROVED** [review]

File: mage/src/mage/bgrabow/ci_test_repl.clj (hunk 1 above)
Comment (bgrabow) [reply mage/src/mage/bgrabow/ci_test_repl.clj]: Regex find-replace failed me because two matches were on the same line.

**Review by nemanjaglumac — APPROVED** [review]
