### PR TITLE
Closes EMB-816 misleading text for number of rows

### LINKED ISSUE #60046: Static Embedding shows a misleading text for the number of returned rows for Table Viz
### Describe the bug

Static Embedding shows a misleading text for the number of returned rows. The following implies there is only 2000 rows there

Image

In metabase you always get the `showing first` which implies there is other information there but is limited to 2000

Image

### To Reproduce

Create a question with more than 2000 (for unaggregated) / 10000 (for aggregated) and embed it. You will notice the above text I shared in the images

### Expected behavior

Similar behaviour as metabase If result is higher than our UI limit we should specify that we're showing the first 2000 or 10000

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
1.55
```

### Severity

It's misleading to the end user of static embedding

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #60046
Closes [EMB-816: Static Embedding shows a misleading text for the number of returned rows for Table Viz](https://linear.app/metabase/issue/EMB-816/static-embedding-shows-a-misleading-text-for-the-number-of-returned)

### Description

Extracted out the logic that generates the "Showing first X rows" so we can use it from table dashcards as well.

### Demo

Before:
image

After:
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/common/utils/format-row-count.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import { msgid, ngettext } from "ttag";
+
+import type { NumberFormatter } from "../hooks/use-number-formatter";
+
+export const formatRowCount = (
+  count: number,
+  formatNumber: NumberFormatter,
+) => {
+  const countString = formatNumber(count);
+  return ngettext(msgid`${countString} row`, `${countString} rows`, count);
```
Comment (heypoom) [inline frontend/src/metabase/common/utils/format-row-count.ts:10]: Just curious, how does using ngettext with msgid differ from using c with interpolated strings? I usually do `c("{0} is the number of rows").jt`. I guess the difference is that this emits a plain JS string, while jt emits a ReactNode.

File: frontend/src/metabase/common/utils/get-row-count-message.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+export function getRowCountMessage(
+  result: { data: { rows_truncated: number }; row_count: number },
+  formatNumber: NumberFormatter,
+) {
+  if (result.data.rows_truncated > 0) {
+    return t`Showing first ${formatRowCount(result.row_count, formatNumber)}`;
+  }
+  if (result.row_count === HARD_ROW_LIMIT) {
+    return t`Showing first ${formatRowCount(HARD_ROW_LIMIT, formatNumber)}`;
+  }
```
Comment (heypoom) [inline frontend/src/metabase/common/utils/get-row-count-message.ts:18]: Do we have tests that cover the `HARD_ROW_LIMIT` logic? I think we have updated the tests to cover the above `Showing first` case, but not sure if it already covers HARD_ROW_LIMIT.

File: frontend/src/metabase/data-grid/components/Footer/Footer.tsx [hunk 3]
```diff
@@ -58,11 +61,19 @@ export const Footer = <TData,>({
...
+                  data: { rows_truncated: rowsTruncated ?? 0 },
+                  row_count: total,
+                },
+                formatNumber,
+              )
+            : ngettext(
+                msgid`${formatNumber(total)} row`,
+                `${formatNumber(total)} rows`,
+                total,
+              )}
```
Comment (heypoom) [inline frontend/src/metabase/data-grid/components/Footer/Footer.tsx:76]: As `getRowCountMessage` contains both `rowsTruncated` and `total`, I wonder if `getRowCountMessage` itself should contain the `${formatNumber(total)} rows` condition. So we just need to call `getRowCountMessage(...)` here, avoiding an extra condition at the call site.

**Review by heypoom — APPROVED** [review]
Both code changes and Loki snapshot changes looks good 🎉

File: frontend/src/metabase/common/utils/format-row-count.ts (hunk 1 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/common/utils/format-row-count.ts:10]: > this emits a plain JS string, while jt emits a ReactNode

That, and also `msgid` is adapted for interpolated/complex expressions, while `t` and `jt` work for simple, direct translations.

File: frontend/src/metabase/common/utils/get-row-count-message.ts (hunk 2 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/common/utils/get-row-count-message.ts:18]: Good call

_Edit:_ wait but won't the first `if` always kick in then?

File: frontend/src/metabase/common/utils/format-row-count.ts (hunk 1 above)
Comment (heypoom) [reply frontend/src/metabase/common/utils/format-row-count.ts:10]: Thanks! I didn't realize `ngettext` existed so I _may_ have abused `c` in the past 😅

File: frontend/src/metabase/data-grid/components/Footer/Footer.tsx (hunk 3 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/data-grid/components/Footer/Footer.tsx:76]: Yup, that's cleaner

File: frontend/src/metabase/common/utils/get-row-count-message.ts (hunk 2 above)
Comment (heypoom) [reply frontend/src/metabase/common/utils/get-row-count-message.ts:18]: @lorem--ipsum yeah, I also think `row_count === HARD_ROW_LIMIT` is weird. I think it should be `if row_count >= HARD_ROW_LIMIT` as the first if condition, as I think the row count may go beyond the hard row limit (unless the backend already does that for you)

File: frontend/src/metabase/data-grid/components/Footer/Footer.tsx (hunk 3 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/data-grid/components/Footer/Footer.tsx:76]: Okay it's too clean: it breaks like ten e2e tests 😅

Comment (heypoom) [reply frontend/src/metabase/data-grid/components/Footer/Footer.tsx:76]: hahaha let's leave it be
