### PR TITLE
[Release blocker fix] Correctly handle remapping inside joins

### LINKED ISSUE #59918: Pivot with breakout on nested joined question fails with "column not found"
### Describe the bug

If you join a question with joins, and then try to pivot grouping by a column inside the joined question's join, it creates an invalid SQL query and fails. Also happens with models.

### To Reproduce

1. Create a question "Orders + Products"
Image
2. Create a question - People joined with the previous "Orders + Products"
Image
3. Create a question - "People + Orders + Products", count, group by Orders + Products -> Category
Image
4. Change to pivot, see error
Image

### Expected behavior

It should select the correct column in the outer GROUP BY

### Logs

```
```

### Information about your Metabase installation

```JSON
v55.3.2, v54.12
```

### Severity

P2

### Additional context

The SQL it tried to run is the following, where it missed the alias from the inner query:
```sql
SELECT
  "source"."Orders + Products__Products__CATEGORY" AS "Orders + Products__Products__CATEGORY", -- (!) This column was renamed to "Orders + Products__CATEGORY" in the nested select below
  "source"."pivot-grouping" AS "pivot-grouping",
  COUNT(*) AS "count"
FROM
  (
    SELECT
      "source"."Orders + Products__Products__CATEGORY" AS "Orders + Products__CATEGORY",
      ABS(0) AS "pivot-grouping"
    FROM
      (
        SELECT
          "PUBLIC"."PEOPLE"."ID" AS "ID",
          "PUBLIC"."PEOPLE"."ADDRESS" AS "ADDRESS",
          "PUBLIC"."PEOPLE"."EMAIL" AS "EMAIL",
          "PUBLIC"."PEOPLE"."PASSWORD" AS "PASSWORD",
          "PUBLIC"."PEOPLE"."NAME" AS "NAME",
          "PUBLIC"."PEOPLE"."CITY" AS "CITY",
          "PUBLIC"."PEOPLE"."LONGITUDE" AS "LONGITUDE",
          "PUBLIC"."PEOPLE"."STATE" AS "STATE",
          "PUBLIC"."PEOPLE"."SOURCE" AS "SOURCE",
          "PUBLIC"."PEOPLE"."BIRTH_DATE" AS "BIRTH_DATE",
          "PUBLIC"."PEOPLE"."ZIP" AS "ZIP",
          "PUBLIC"."PEOPLE"."LATITUDE" AS "LATITUDE",
          "PUBLIC"."PEOPLE"."CREATED_AT" AS "CREATED_AT",
          "Orders + Products"."ID" AS "Orders + Products__ID",
          "Orders + Products"."USER_ID" AS "Orders + Products__USER_ID",
          "Orders + Products"."PRODUCT_ID" AS "Orders + Products__PRODUCT_ID",
          "Orders + Products"."SUBTOTAL" AS "Orders + Products__SUBTOTAL",
          "Orders + Products"."TAX" AS "Orders + Products__TAX",
          "Orders + Products"."TOTAL" AS "Orders + Products__TOTAL",
          "Orders + Products"."DISCOUNT" AS "Orders + Products__DISCOUNT",
          "Orders + Products"."CREATED_AT" AS "Orders + Products__CREATED_AT",
          "Orders + Products"."QUANTITY" AS "Orders + Products__QUANTITY",
          "Orders + Products"."PEOPLE__via__USER_ID__NAME" AS "Orders + Products__PEOPLE__via__USER_ID__NAME",
          "Orders + Products"."PRODUCTS__via__PRODUCT_ID__TITLE" AS "Orders + Products__PRODUCTS__via__PRODUCT_ID__TITLE",
          "Orders + Products"."Products__ID" AS "Orders + Products__Products__ID",
          "Orders + Products"."Products__EAN" AS "Orders + Products__Products__EAN",
          "Orders + Products"."Products__TITLE" AS "Orders + Products__Products__TITLE",
          "Orders + Products"."Products__CATEGORY" AS "Orders + Products__Products__CATEGORY",
          "Orders + Products"."Products__VENDOR" AS "Orders + Products__Products__VENDOR",
          "Orders + Products"."Products__PRICE" AS "Orders + Products__Products__PRICE",
          "Orders + Products"."Products__RATING" AS "Orders + Products__Products__RATING",
          "Orders + Products"."Products__CREATED_AT" AS "Orders + Products__Products__CREATED_AT"
        FROM
          "PUBLIC"."PEOPLE"
          LEFT JOIN (
            SELECT
              "PUBLIC"."ORDERS"."ID" AS "ID",
              "PUBLIC"."ORDERS"."USER_ID" AS "USER_ID",
              "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID",
              "PUBLIC"."ORDERS"."SUBTOTAL" AS "SUBTOTAL",
              "PUBLIC"."ORDERS"."TAX" AS "TAX",
              "PUBLIC"."ORDERS"."TOTAL" AS "TOTAL",
              "PUBLIC"."ORDERS"."DISCOUNT" AS "DISCOUNT",
              "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT",
              "PUBLIC"."ORDERS"."QUANTITY" AS "QUANTITY",
              "PEOPLE__via__USER_ID"."NAME" AS "PEOPLE__via__USER_ID__NAME",
              "PRODUCTS__via__PRODUCT_ID"."TITLE" AS "PRODUCTS__via__PRODUCT_ID__TITLE",
              "Products"."ID" AS "Products__ID",
              "Products"."EAN" AS "Products__EAN",
              "Products"."TITLE" AS "Products__TITLE",
              "Products"."CATEGORY" AS "Products__CATEGORY",
              "Products"."VENDOR" AS "Products__VENDOR",
              "Products"."PRICE" AS "Products__PRICE",
              "Products"."RATING" AS "Products__RATING",
              "Products"."CREATED_AT" AS "Products__CREATED_AT"
            FROM
              "PUBLIC"."ORDERS"
              LEFT JOIN "PUBLIC"."PRODUCTS" AS "Products" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "Products"."ID"
              LEFT JOIN "PUBLIC"."PEOPLE" AS "PEOPLE__via__USER_ID" ON "PUBLIC"."ORDERS"."USER_ID" = "PEOPLE__via__USER_ID"."ID"
              LEFT JOIN "PUBLIC"."PRODUCTS" AS "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID"
          ) AS "Orders + Products" ON "PUBLIC"."PEOPLE"."ID" = "Orders + Products"."USER_ID"
      ) AS "source"
  ) AS "source"
GROUP BY
  "source"."Orders + Products__Products__CATEGORY",
  "source"."pivot-grouping"
ORDER BY
  "source"."Orders + Products__Products__CATEGORY" ASC,
  "source"."pivot-grouping" ASC
```

### LINKED ISSUE #60444: column number mismatch between initial metadata columns returned by driver (X) and those expected by MLv2 (Y)
### Describe the bug

https://pr60036.coredev.metabase.com/question/113-analytic-events-analytic-events

```
column number mismatch between initial metadata columns returned by driver (13) and those expected by MLv2 (14). Did the driver return the wrong number of columns?  Or is there a bug in MLv2 metadata calculation?
```

### To Reproduce

1. Open https://pr60036.coredev.metabase.com/question/113-analytic-events-analytic-events
2. See error

Image

Image

### Expected behavior

The query should work

### Logs

```
{
  "database_id": 1,
  "parameterized": false,
  "started_at": "2025-07-03T13:51:21.607587403Z",
  "via": [
    {
      "status": "failed",
      "class": "class clojure.lang.ExceptionInfo",
      "error": "Error building query results reducing function: column number mismatch between initial metadata columns returned by driver (13) and those expected by MLv2 (14). Did the driver return the wrong number of columns?  Or is there a bug in MLv2 metadata calculation?",
      "stacktrace": [
        "--> query_processor.pipeline$_STAR_reduce_STAR_$fn__63853.invoke(pipeline.clj:72)",
        "query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:69)",
        "query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:60)",
        "query_processor.pipeline$_STAR_run_STAR_$respond__63870.invoke(pipeline.clj:114)",
        "driver.sql_jdbc.execute$execute_reducible_query$fn__94323.invoke(execute.clj:754)",
        "driver.h2$fn__129912$fn__129914.invoke(h2.clj:553)",
        "driver.sql_jdbc.execute$do_with_resolved_connection94089__94090.invokeStatic(execute.clj:345)",
        "driver.sql_jdbc.execute$do_with_resolved_connection94089__94090.invoke(execute.clj:328)",
        "driver.h2$fn__129912.invokeStatic(h2.clj:544)",
        "driver.h2$fn__129912.invoke(h2.clj:540)",
        "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:737)",
        "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:723)",
        "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:734)",
        "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:723)",
        "driver.sql_jdbc$fn__98956.invokeStatic(sql_jdbc.clj:80)",
        "driver.sql_jdbc$fn__98956.invoke(sql_jdbc.clj:78)",
        "driver.h2$fn__129743.invokeStatic(h2.clj:265)",
        "driver.h2$fn__129743.invoke(h2.clj:261)",
        "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:58)",
        "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:43)",
        "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:116)",
        "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:105)",
        "query_processor.execute$run.invokeStatic(execute.clj:64)",
        "query_processor.execute$run.invoke(execute.clj:58)",
        "metabase_enterprise.database_routing.middleware$fn__140247$swap_destination_db__140248$fn__140249.invoke(middleware.clj:31)",
        "query_processor.middleware.enterprise$swap_destination_db_middleware$fn__77846.invoke(enterprise.clj:73)",
        "metabase_enterprise.impersonation.middleware$fn__126618$apply_impersonation_postprocessing__126619$fn__126620.invoke(middleware.clj:25)",
        "query_processor.middleware.enterprise$apply_impersonation_postprocessing_middleware$fn__77829.invoke(enterprise.clj:48)",
        "query_processor.middleware.update_used_cards$update_used_cards_BANG_78045__78046$fn__78047.invoke(update_used_cards.clj:67)",
        "query_processor.execute$add_native_form_to_result_metadata$fn__78150.invoke(execute.clj:25)",
        "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__78156.invoke(execute.clj:36)",
        "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___77989.invoke(cache.clj:241)",
        "query_processor.middleware.permissions$check_query_permissions$fn__73329.invoke(permissions.clj:160)",
        "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__128067$check_download_permissions__128068$fn__128069.invoke(permissions.clj:97)",
        "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__77856.invoke(enterprise.clj:90)",
        "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$fn__131864$maybe_apply_column_level_perms_check__131865$fn__131866.invoke(column_level_perms_check.clj:38)",
        "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__77866.invoke(enterprise.clj:103)",
        "query_processor.execute$execute78183__78184$fn__78185.invoke(execute.clj:96)",
        "query_processor.setup$do_with_qp_setup78136__78137.invokeStatic(setup.clj:225)",
        "query_processor.setup$do_with_qp_setup78136__78137.invoke(setup.clj:216)",
        "query_processor.execute$execute78183__78184.invokeStatic(execute.clj:95)",
        "query_processor.execute$execute78183__78184.invoke(execute.clj:91)",
        "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:50)",
        "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:45)",
        "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__94478$handle_audit_app_internal_queries__94479$fn__94480.invoke(handle_audit_queries.clj:143)",
        "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__77894.invoke(enterprise.clj:142)",
        "query_processor.middleware.process_userland_query$process_userland_query_middleware85796__85797$fn__85798.invoke(process_userland_query.clj:177)",
        "query_processor.middleware.catch_exceptions$catch_exceptions85861__85862$fn__85863.invoke(catch_exceptions.clj:137)",
        "query_processor$process_query85931__85932$fn__85933.invoke(query_processor.clj:81)",
        "query_processor.setup$do_with_canceled_chan78131__78132$fn__78133.invoke(setup.clj:187)",
        "query_processor.setup$do_with_database_local_settings78124__78125$fn__78126.invoke(setup.clj:181)",
        "query_processor.setup$do_with_driver78117__78118$fn__78119$fn__78120.invoke(setup.clj:166)",
        "driver$do_with_driver.invokeStatic(driver.clj:49)",
        "driver$do_with_driver.invoke(driver.clj:44)",
        "query_processor.setup$do_with_driver78117__78118$fn__78119.invoke(setup.clj:165)",
        "query_processor.setup$do_with_metadata_provider78108__78109$fn__78110.invoke(setup.clj:140)",
        "query_processor.setup$do_with_resolved_database78098__78099$fn__78100.invoke(setup.clj:128)",
        "query_processor.setup$do_with_qp_setup78136__78137.invokeStatic(setup.clj:232)",
        "query_processor.setup$do_with_qp_setup78136__78137.invoke(setup.clj:216)",
        "query_processor$process_query85931__85932.invokeStatic(query_processor.clj:79)",
        "query_processor$process_query85931__85932.invoke(query_processor.clj:72)",
        "query_processor.card$process_query_for_card_default_qp89716__89717.invokeStatic(card.clj:237)",
        "query_processor.card$process_query_for_card_default_qp89716__89717.invoke(card.clj:233)",
        "query_processor.card$process_query_for_card_default_run_fn$fn__89719$fn__89720.invoke(card.clj:245)",
        "query_processor.streaming$_streaming_response$fn__66040$fn__66041$fn__66042.invoke(streaming.clj:188)",
        "query_processor.streaming$_streaming_response$fn__66040$fn__66041.invoke(streaming.clj:186)",
        "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:177)",
        "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:164)",
        "query_processor.streaming$_streaming_response$fn__66040.invoke(streaming.clj:183)",
        "server.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:79)",
        "server.streaming_response$do_f_STAR_.invoke(streaming_response.clj:77)",
        "server.streaming_response$do_f_async$task__57619.invoke(streaming_response.clj:94)"
      ],
      "error_type": "qp",
      "ex-data": {
        "type": "qp",
        "rff": "metabase.query_processor.middleware.update_used_cards$update_used_cards_BANG_78045__78046$fn__78047$rff_STAR___78048@6d3e9d2e"
      }
    }
  ],
  "action_id": null,
  "error_type": "qp",
  "json_query": {
    "constraints": {
      "max-results": 10000,
      "max-results-bare-rows": 2000
    },
    "type": "query",
    "middleware": {
      "js-int-to-string?": true,
      "ignore-cached-results?": true,
      "process-viz-settings?": false,
      "userland-query?": true
    },
    "cache-strategy": null,
    "viz-settings": {},
    "database": 1,
    "query": {
      "source-table": 7,
      "joins": [
        {
          "fields": "all",
          "alias": "Analytic Events - Account",
          "strategy": "left-join",
          "ident": "J7WkBQISgrk9UXWOBhCdx",
          "condition": [
            "and",
            [
              "=",
              [
                "field",
                32,
                {
                  "base-type": "type/Text"
                }
              ],
              [
                "value",
                "Page Viewed",
                {
                  "base_type": "type/Text"
                }
              ]
            ],
            [
              "=",
              [
                "field",
                45,
                {
                  "base-type": "type/BigInteger"
                }
              ],
              [
                "field",
                45,
                {
                  "base-type": "type/BigInteger",
                  "join-alias": "Analytic Events - Account"
                }
              ]
            ],
            [
              "=",
              [
                "field",
                49,
                {
                  "base-type": "type/Text"
                }
              ],
              [
                "value",
                "www.piespace.example/login",
                {
                  "base_type": "type/Text"
                }
              ]
            ],
            [
              "=",
              [
                "value",
                "Button Clicked",
                {
                  "base_type": "type/Text"
                }
              ],
              [
                "field",
                32,
                {
                  "base-type": "type/Text",
                  "join-alias": "Analytic Events - Account"
                }
              ]
            ],
            [
              "=",
              [
                "value",
                "Signup",
                {
                  "base_type": "type/Text"
                }
              ],
              [
                "field",
                29,
                {
                  "base-type": "type/Text",
                  "join-alias": "Analytic Events - Account"
                }
              ]
            ],
            [
              "<=",
              [
                "field",
                35,
                {
                  "base-type": "type/DateTime",
                  "temporal-unit": "minute",
                  "original-temporal-unit": "minute"
                }
              ],
              [
                "field",
                35,
                {
                  "base-type": "type/DateTime",
                  "temporal-unit": "minute",
                  "join-alias": "Analytic Events - Account",
                  "original-temporal-unit": "day"
                }
              ]
            ]
          ],
          "source-table": 7
        }
      ]
    },
    "parameters": []
  },
  "native": {
    "query": "SELECT \"PUBLIC\".\"ANALYTIC_EVENTS\".\"ID\" AS \"ID\", \"PUBLIC\".\"ANALYTIC_EVENTS\".\"ACCOUNT_ID\" AS \"ACCOUNT_ID\", \"PUBLIC\".\"ANALYTIC_EVENTS\".\"EVENT\" AS \"EVENT\", \"PUBLIC\".\"ANALYTIC_EVENTS\".\"TIMESTAMP\" AS \"TIMESTAMP\", \"PUBLIC\".\"ANALYTIC_EVENTS\".\"PAGE_URL\" AS \"PAGE_URL\", \"PUBLIC\".\"ANALYTIC_EVENTS\".\"BUTTON_LABEL\" AS \"BUTTON_LABEL\", \"ACCOUNTS__via__ACCOUNT_ID\".\"EMAIL\" AS \"ACCOUNTS__via__ACCOUNT_ID__EMAIL\", \"Analytic Events - Account\".\"ID\" AS \"Analytic Events - Account__ID\", \"Analytic Events - Account\".\"ACCOUNT_ID\" AS \"Analytic Events - Account__ACCOUNT_ID\", \"Analytic Events - Account\".\"EVENT\" AS \"Analytic Events - Account__EVENT\", \"Analytic Events - Account\".\"TIMESTAMP\" AS \"Analytic Events - Account__TIMESTAMP\", \"Analytic Events - Account\".\"PAGE_URL\" AS \"Analytic Events - Account__PAGE_URL\", \"Analytic Events - Account\".\"BUTTON_LABEL\" AS \"Analytic Events - Account__BUTTON_LABEL\" FROM \"PUBLIC\".\"ANALYTIC_EVENTS\" LEFT JOIN \"PUBLIC\".\"ANALYTIC_EVENTS\" AS \"Analytic Events - Account\" ON (\"PUBLIC\".\"ANALYTIC_EVENTS\".\"EVENT\" = ?) AND (\"PUBLIC\".\"ANALYTIC_EVENTS\".\"ACCOUNT_ID\" = \"Analytic Events - Account\".\"ACCOUNT_ID\") AND (\"PUBLIC\".\"ANALYTIC_EVENTS\".\"PAGE_URL\" = ?) AND (? = \"Analytic Events - Account\".\"EVENT\") AND (? = \"Analytic Events - Account\".\"BUTTON_LABEL\") AND (DATE_TRUNC('minute', \"PUBLIC\".\"ANALYTIC_EVENTS\".\"TIMESTAMP\") <= DATE_TRUNC('minute', \"Analytic Events - Account\".\"TIMESTAMP\")) LEFT JOIN \"PUBLIC\".\"ACCOUNTS\" AS \"ACCOUNTS__via__ACCOUNT_ID\" ON \"PUBLIC\".\"ANALYTIC_EVENTS\".\"ACCOUNT_ID\" = \"ACCOUNTS__via__ACCOUNT_ID\".\"ID\" LIMIT 2000",
    "params": [
      "Page Viewed",
      "www.piespace.example/login",
      "Button Clicked",
      "Signup"
    ]
  },
  "status": "failed",
  "class": "class clojure.lang.ExceptionInfo",
  "stacktrace": [
    "--> lib.metadata.result_metadata$merge_cols79115__79116.invokeStatic(result_metadata.cljc:104)",
    "lib.metadata.result_metadata$merge_cols79115__79116.invoke(result_metadata.cljc:86)",
    "lib.metadata.result_metadata$add_extra_metadata79252__79253$fn__79254.invoke(result_metadata.cljc:336)",
    "lib.metadata.result_metadata$add_extra_metadata79252__79253.invokeStatic(result_metadata.cljc:334)",
    "lib.metadata.result_metadata$add_extra_metadata79252__79253.invoke(result_metadata.cljc:316)",
    "lib.metadata.result_metadata$returned_columns79272__79279.invokeStatic(result_metadata.cljc:404)",
    "lib.metadata.result_metadata$returned_columns79272__79279.invoke(result_metadata.cljc:385)",
    "query_processor.middleware.annotate$expected_cols79292__79293.invokeStatic(annotate.clj:73)",
    "query_processor.middleware.annotate$expected_cols79292__79293.invoke(annotate.clj:61)",
    "query_processor.middleware.annotate$add_column_info_no_type_inference79310__79311$fn__79312.invoke(annotate.clj:83)",
    "query_processor.middleware.annotate$add_column_info_no_type_inference79310__79311.invokeStatic(annotate.clj:83)",
    "query_processor.middleware.annotate$add_column_info_no_type_inference79310__79311.invoke(annotate.clj:78)",
    "query_processor.middleware.annotate$add_column_info79366__79367$fn__79368.invoke(annotate.clj:155)",
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__128067$check_download_permissions__128068$fn__128069$rff_STAR___128070.invoke(permissions.clj:98)",
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__78156$rff_STAR___78157.invoke(execute.clj:31)",
    "query_processor.execute$add_native_form_to_result_metadata$fn__78150$rff_STAR___78151.invoke(execute.clj:22)",
    "query_processor.middleware.update_used_cards$update_used_cards_BANG_78045__78046$fn__78047$rff_STAR___78048.invoke(update_used_cards.clj:66)",
    "query_processor.pipeline$_STAR_reduce_STAR_$fn__63853.invoke(pipeline.clj:70)",
    "query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:69)",
    "query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:60)",
    "query_processor.pipeline$_STAR_run_STAR_$respond__63870.invoke(pipeline.clj:114)",
    "driver.sql_jdbc.execute$execute_reducible_query$fn__94323.invoke(execute.clj:754)",
    "driver.h2$fn__129912$fn__129914.invoke(h2.clj:553)",
    "driver.sql_jdbc.execute$do_with_resolved_connection94089__94090.invokeStatic(execute.clj:345)",
    "driver.sql_jdbc.execute$do_with_resolved_connection94089__94090.invoke(execute.clj:328)",
    "driver.h2$fn__129912.invokeStatic(h2.clj:544)",
    "driver.h2$fn__129912.invoke(h2.clj:540)",
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:737)",
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:723)",
    "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:734)",
    "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:723)",
    "driver.sql_jdbc$fn__98956.invokeStatic(sql_jdbc.clj:80)",
    "driver.sql_jdbc$fn__98956.invoke(sql_jdbc.clj:78)",
    "driver.h2$fn__129743.invokeStatic(h2.clj:265)",
    "driver.h2$fn__129743.invoke(h2.clj:261)",
    "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:58)",
    "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:43)",
    "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:116)",
    "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:105)",
    "query_processor.execute$run.invokeStatic(execute.clj:64)",
    "query_processor.execute$run.invoke(execute.clj:58)",
    "metabase_enterprise.database_routing.middleware$fn__140247$swap_destination_db__140248$fn__140249.invoke(middleware.clj:31)",
    "query_processor.middleware.enterprise$swap_destination_db_middleware$fn__77846.invoke(enterprise.clj:73)",
    "metabase_enterprise.impersonation.middleware$fn__126618$apply_impersonation_postprocessing__126619$fn__126620.invoke(middleware.clj:25)",
    "query_processor.middleware.enterprise$apply_impersonation_postprocessing_middleware$fn__77829.invoke(enterprise.clj:48)",
    "query_processor.middleware.update_used_cards$update_used_cards_BANG_78045__78046$fn__78047.invoke(update_used_cards.clj:67)",
    "query_processor.execute$add_native_form_to_result_metadata$fn__78150.invoke(execute.clj:25)",
    "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__78156.invoke(execute.clj:36)",
    "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___77989.invoke(cache.clj:241)",
    "query_processor.middleware.permissions$check_query_permissions$fn__73329.invoke(permissions.clj:160)",
    "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$fn__128067$check_download_permissions__128068$fn__128069.invoke(permissions.clj:97)",
    "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__77856.invoke(enterprise.clj:90)",
    "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$fn__131864$maybe_apply_column_level_perms_check__131865$fn__131866.invoke(column_level_perms_check.clj:38)",
    "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__77866.invoke(enterprise.clj:103)",
    "query_processor.execute$execute78183__78184$fn__78185.invoke(execute.clj:96)",
    "query_processor.setup$do_with_qp_setup78136__78137.invokeStatic(setup.clj:225)",
    "query_processor.setup$do_with_qp_setup78136__78137.invoke(setup.clj:216)",
    "query_processor.execute$execute78183__78184.invokeStatic(execute.clj:95)",
    "query_processor.execute$execute78183__78184.invoke(execute.clj:91)",
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:50)",
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:45)",
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__94478$handle_audit_app_internal_queries__94479$fn__94480.invoke(handle_audit_queries.clj:143)",
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__77894.invoke(enterprise.clj:142)",
    "query_processor.middleware.process_userland_query$process_userland_query_middleware85796__85797$fn__85798.invoke(process_userland_query.clj:177)",
    "query_processor.middleware.catch_exceptions$catch_exceptions85861__85862$fn__85863.invoke(catch_exceptions.clj:137)",
    "query_processor$process_query85931__85932$fn__85933.invoke(query_processor.clj:81)",
    "query_processor.setup$do_with_canceled_chan78131__78132$fn__78133.invoke(setup.clj:187)",
    "query_processor.setup$do_with_database_local_settings78124__78125$fn__78126.invoke(setup.clj:181)",
    "query_processor.setup$do_with_driver78117__78118$fn__78119$fn__78120.invoke(setup.clj:166)",
    "driver$do_with_driver.invokeStatic(driver.clj:49)",
    "driver$do_with_driver.invoke(driver.clj:44)",
    "query_processor.setup$do_with_driver78117__78118$fn__78119.invoke(setup.clj:165)",
    "query_processor.setup$do_with_metadata_provider78108__78109$fn__78110.invoke(setup.clj:140)",
    "query_processor.setup$do_with_resolved_database78098__78099$fn__78100.invoke(setup.clj:128)",
    "query_processor.setup$do_with_qp_setup78136__78137.invokeStatic(setup.clj:232)",
    "query_processor.setup$do_with_qp_setup78136__78137.invoke(setup.clj:216)",
    "query_processor$process_query85931__85932.invokeStatic(query_processor.clj:79)",
    "query_processor$process_query85931__85932.invoke(query_processor.clj:72)",
    "query_processor.card$process_query_for_card_default_qp89716__89717.invokeStatic(card.clj:237)",
    "query_processor.card$process_query_for_card_default_qp89716__89717.invoke(card.clj:233)",
    "query_processor.card$process_query_for_card_default_run_fn$fn__89719$fn__89720.invoke(card.clj:245)",
    "query_processor.streaming$_streaming_response$fn__66040$fn__66041$fn__66042.invoke(streaming.clj:188)",
    "query_processor.streaming$_streaming_response$fn__66040$fn__66041.invoke(streaming.clj:186)",
    "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:177)",
    "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:164)",
    "query_processor.streaming$_streaming_response$fn__66040.invoke(streaming.clj:183)",
    "server.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:79)",
    "server.streaming_response$do_f_STAR_.invoke(streaming_response.clj:77)",
    "server.streaming_response$do_f_async$task__57619.invoke(streaming_response.clj:94)"
  ],
  "card_id": 113,
  "context": "question",
  "error": "column number mismatch between initial metadata columns returned by driver (13) and those expected by MLv2 (14). Did the driver return the wrong number of columns?  Or is there a bug in MLv2 metadata calculation?",
  "row_count": 0,
  "running_time": 0,
  "preprocessed": {
    "constraints": {
      "max-results": 10000,
      "max-results-bare-rows": 2000
    },
    "metabase.query-processor.middleware.add-dimension-projections/external-remaps": [
      {
        "id": 3,
        "name": "Account ID",
        "field-id": 45,
        "field-name": "ACCOUNT_ID",
        "human-readable-field-id": 62,
        "human-readable-field-name": "EMAIL"
      }
    ],
    "middleware": {
      "js-int-to-string?": true,
      "ignore-cached-results?": true,
      "process-viz-settings?": false,
      "userland-query?": true
    },
    "viz-settings": {},
    "info": {
      "executed-by": 1,
      "context": "question",
      "card-id": 113,
      "card-entity-id": "WGUIotVghaAI2aOevK3cn",
      "card-name": "Analytic Events + Analytic Events"
    },
    "database": 1,
    "type": "query",
    "query": {
      "source-table": 7,
      "fields": [
        [
          "field",
          60,
          null
        ],
        [
          "field",
          45,
          {
            "metabase.query-processor.middleware.add-dimension-projections/original-field-dimension-id": 3
          }
        ],
        [
          "field",
          32,
          null
        ],
        [
          "field",
          35,
          null
        ],
        [
          "field",
          49,
          null
        ],
        [
          "field",
          29,
          null
        ],
        [
          "field",
          62,
          {
            "source-field": 45,
            "metabase.query-processor.middleware.add-dimension-projections/new-field-dimension-id": 3,
            "join-alias": "ACCOUNTS__via__ACCOUNT_ID"
          }
        ],
        [
          "field",
          60,
          {
            "join-alias": "Analytic Events - Account"
          }
        ],
        [
          "field",
          45,
          {
            "join-alias": "Analytic Events - Account"
          }
        ],
        [
          "field",
          32,
          {
            "join-alias": "Analytic Events - Account"
          }
        ],
        [
          "field",
          35,
          {
            "join-alias": "Analytic Events - Account"
          }
        ],
        [
          "field",
          49,
          {
            "join-alias": "Analytic Events - Account"
          }
        ],
        [
          "field",
          29,
          {
            "join-alias": "Analytic Events - Account"
          }
        ]
      ],
      "joins": [
        {
          "alias": "Analytic Events - Account",
          "strategy": "left-join",
          "fields": [
            [
              "field",
              60,
              {
                "join-alias": "Analytic Events - Account"
              }
            ],
            [
              "field",
              45,
              {
                "join-alias": "Analytic Events - Account"
              }
            ],
            [
              "field",
              32,
              {
                "join-alias": "Analytic Events - Account"
              }
            ],
            [
              "field",
              35,
              {
                "join-alias": "Analytic Events - Account"
              }
            ],
            [
              "field",
              49,
              {
                "join-alias": "Analytic Events - Account"
              }
            ],
            [
              "field",
              29,
              {
                "join-alias": "Analytic Events - Account"
              }
            ]
          ],
          "ident": "J7WkBQISgrk9UXWOBhCdx",
          "condition": [
            "and",
            [
              "=",
              [
                "field",
                32,
                {
                  "base-type": "type/Text"
                }
              ],
              [
                "value",
                "Page Viewed",
                {
                  "base_type": "type/Text"
                }
              ]
            ],
            [
              "=",
              [
                "field",
                45,
                {
                  "base-type": "type/BigInteger"
                }
              ],
              [
                "field",
                45,
                {
                  "base-type": "type/BigInteger",
                  "join-alias": "Analytic Events - Account"
                }
              ]
            ],
            [
              "=",
              [
                "field",
                49,
                {
                  "base-type": "type/Text"
                }
              ],
              [
                "value",
                "www.piespace.example/login",
                {
                  "base_type": "type/Text"
                }
              ]
            ],
            [
              "=",
              [
                "value",
                "Button Clicked",
                {
                  "base_type": "type/Text"
                }
              ],
              [
                "field",
                32,
                {
                  "base-type": "type/Text",
                  "join-alias": "Analytic Events - Account"
                }
              ]
            ],
            [
              "=",
              [
                "value",
                "Signup",
                {
                  "base_type": "type/Text"
                }
              ],
              [
                "field",
                29,
                {
                  "base-type": "type/Text",
                  "join-alias": "Analytic Events - Account"
                }
              ]
            ],
            [
              "<=",
              [
                "field",
                35,
                {
                  "base-type": "type/DateTime",
                  "temporal-unit": "minute",
                  "original-temporal-unit": "minute"
                }
              ],
              [
                "field",
                35,
                {
                  "base-type": "type/DateTime",
                  "temporal-unit": "minute",
                  "join-alias": "Analytic Events - Account",
                  "original-temporal-unit": "day"
                }
              ]
            ]
          ],
          "source-table": 7
        },
        {
          "qp/is-implicit-join": true,
          "alias": "ACCOUNTS__via__ACCOUNT_ID",
          "strategy": "left-join",
          "ident": "implicit_via__field__ACCOUNT_ID",
          "fk-field-id": 45,
          "condition": [
            "=",
            [
              "field",
              45,
              null
            ],
            [
              "field",
              24,
              {
                "join-alias": "ACCOUNTS__via__ACCOUNT_ID"
              }
            ]
          ],
          "source-table": 6
        }
      ],
      "limit": 2000,
      "metabase.query-processor.middleware.limit/original-limit": null
    }
  },
  "ex-data": {
    "initial-cols": [
      {
        "name": "ID"
      },
      {
        "name": "ACCOUNT_ID"
      },
      {
        "name": "EVENT"
      },
      {
        "name": "TIMESTAMP"
      },
      {
        "name": "PAGE_URL"
      },
      {
        "name": "BUTTON_LABEL"
      },
      {
        "name": "ACCOUNTS__via__ACCOUNT_ID__EMAIL"
      },
      {
        "name": "Analytic Events - Account__ID"
      },
      {
        "name": "Analytic Events - Account__ACCOUNT_ID"
      },
      {
        "name": "Analytic Events - Account__EVENT"
      },
      {
        "name": "Analytic Events - Account__TIMESTAMP"
      },
      {
        "name": "Analytic Events - Account__PAGE_URL"
      },
      {
        "name": "Analytic Events - Account__BUTTON_LABEL"
      }
    ],
    "lib-cols": [
      {
        "id": 60,
        "lib/desired-column-alias": "ID",
        "lib/deduplicated-name": "ID",
        "lib/original-name": "ID",
        "name": "ID"
      },
      {
        "id": 45,
        "lib/desired-column-alias": "ACCOUNT_ID",
        "lib/deduplicated-name": "ACCOUNT_ID",
        "lib/original-name": "ACCOUNT_ID",
        "name": "ACCOUNT_ID"
      },
      {
        "id": 32,
        "lib/desired-column-alias": "EVENT",
        "lib/deduplicated-name": "EVENT",
        "lib/original-name": "EVENT",
        "name": "EVENT"
      },
      {
        "id": 35,
        "lib/desired-column-alias": "TIMESTAMP",
        "lib/deduplicated-name": "TIMESTAMP",
        "lib/original-name": "TIMESTAMP",
        "name": "TIMESTAMP"
      },
      {
        "id": 49,
        "lib/desired-column-alias": "PAGE_URL",
        "lib/deduplicated-name": "PAGE_URL",
        "lib/original-name": "PAGE_URL",
        "name": "PAGE_URL"
      },
      {
        "id": 29,
        "lib/desired-column-alias": "BUTTON_LABEL",
        "lib/deduplicated-name": "BUTTON_LABEL",
        "lib/original-name": "BUTTON_LABEL",
        "name": "BUTTON_LABEL"
      },
      {
        "id": 62,
        "metabase.lib.join/join-alias": "ACCOUNTS__via__ACCOUNT_ID",
        "lib/desired-column-alias": "ACCOUNTS__via__ACCOUNT_ID__EMAIL",
        "lib/deduplicated-name": "EMAIL",
        "lib/original-name": "EMAIL",
        "name": "EMAIL"
      },
      {
        "id": 60,
        "metabase.lib.join/join-alias": "Analytic Events - Account",
        "lib/desired-column-alias": "Analytic Events - Account__ID",
        "lib/deduplicated-name": "ID_2",
        "lib/original-name": "ID",
        "name": "ID_2"
      },
      {
        "id": 45,
        "metabase.lib.join/join-alias": "Analytic Events - Account",
        "lib/desired-column-alias": "Analytic Events - Account__ACCOUNT_ID",
        "lib/deduplicated-name": "ACCOUNT_ID_2",
        "lib/original-name": "ACCOUNT_ID",
        "name": "ACCOUNT_ID_2"
      },
      {
        "id": 32,
        "metabase.lib.join/join-alias": "Analytic Events - Account",
        "lib/desired-column-alias": "Analytic Events - Account__EVENT",
        "lib/deduplicated-name": "EVENT_2",
        "lib/original-name": "EVENT",
        "name": "EVENT_2"
      },
      {
        "id": 35,
        "metabase.lib.join/join-alias": "Analytic Events - Account",
        "lib/desired-column-alias": "Analytic Events - Account__TIMESTAMP",
        "lib/deduplicated-name": "TIMESTAMP_2",
        "lib/original-name": "TIMESTAMP",
        "name": "TIMESTAMP_2"
      },
      {
        "id": 49,
        "metabase.lib.join/join-alias": "Analytic Events - Account",
        "lib/desired-column-alias": "Analytic Events - Account__PAGE_URL",
        "lib/deduplicated-name": "PAGE_URL_2",
        "lib/original-name": "PAGE_URL",
        "name": "PAGE_URL_2"
      },
      {
        "id": 29,
        "metabase.lib.join/join-alias": "Analytic Events - Account",
        "lib/desired-column-alias": "Analytic Events - Account__BUTTON_LABEL",
        "lib/deduplicated-name": "BUTTON_LABEL_2",
        "lib/original-name": "BUTTON_LABEL",
        "name": "BUTTON_LABEL_2"
      },
      {
        "id": 62,
        "metabase.lib.join/join-alias": "Analytic Events - Account",
        "lib/desired-column-alias": "Analytic Events - Account__EMAIL",
        "lib/deduplicated-name": "EMAIL_2",
        "lib/original-name": "EMAIL",
        "name": "EMAIL_2"
      }
    ]
  },
  "data": {
    "rows": [],
    "cols": []
  }
}
```

### Information about your Metabase installation

```JSON
Hash `156c7a6`
```

### Severity

P1

### Additional context

_No response_

### LINKED ISSUE #60498: [refs] "Column does not exist" error referencing an `active: false` column
### Describe the bug

See https://stats.metabase.com/question/17735 which fails saying `column Contact.is_curated does not exist`. That field is marked `active: false` but either appears in some `:result_metadata` or in the outer query. The generated SQL refers to it but the inner queries do not mention it.

I think the QP previously filtered out "bad" columns like this, but it's now missing this case.

### To Reproduce

[Card 17735 on stats](https://stats.metabase.com/question/17735)

### Expected behavior

The bad column reference should be dropped, and the query execute neatly.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Stats at c8e9cca
```

### Severity

Low, but a regression of previously working queries

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by camsaul**
The important parts of this fix are

1. add micro middleware to force all joins in legacy MBQL to use `:source-query` e.g. `{:source-query {:source-table 1}}` instead of `{:source-table 1}` which means the `add-implicit-clauses` middleware will automatically add `:fields` which in turn means the `add-remaps` middleware will automatically add remaps
2. Update `add-remaps` middleware to update join `:fields` to propagate the remaps

There are other misc fixes as well. 

This change results in a little noisier compiled SQL but fixes at least 3 P1 ref-related bugs (if not more) so it's worth it IMO. 

Fixes #59918
Fixes #60444
Fixes #60498

Depends on #61437

### CODE REVIEW

File: src/metabase/query_processor/middleware/add_remaps.clj [hunk 1]
```diff
@@ -83,76 +81,81 @@
...
-                                              :name                      remap-name
-                                              :field-id                  (:id field)
-                                              :field-name                (:name field)
-                                              :human-readable-field-id   remap-field-id
-                                              :human-readable-field-name (:name remap-field)}])))))
-              field-metadatas)))))
+   field-id              :- ::lib.schema.id/field]
+  (let [col (lib.metadata/field metadata-providerable field-id)]
+    (when (:lib/external-remap col)
+      (let [{remap-id :id, remap-name :name, remap-field-id :field-id} (:lib/external-remap col)]
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_remaps.clj]: Why not combine these into a `when-let`?

File: src/metabase/query_processor/middleware/add_remaps.clj [hunk 2]
```diff
@@ -83,76 +81,81 @@
...
+    [:new-field-clause      [:and
+                             :mbql.clause/field
+                             [:tuple
+                              [:= :field]
+                              [:map
+                               [::new-field-dimension-id ::lib.schema.id/dimension]]
+                              :any]]]
+    [:dimension             ::external-remapping]]
+   [:fn
+    {:error/message "if the original field clause had a join alias, the new clause should as well"}
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_remaps.clj]:
```suggestion
    {:error/message "the new field clause should have the same join alias as the original field clause"}
```

File: src/metabase/query_processor/middleware/add_remaps.clj [hunk 3]
```diff
@@ -83,76 +81,81 @@
...
+    (not-empty
+     (into []
+           (comp
+            ;; DON'T remap fields added by implicit joins. DO remap fields added by explicit joins.
+            (remove :fk-field-id)
+            (keep (fn [{:keys [id], :as col}]
+                    (when-let [dimension (when (pos-int? id)
+                                           (field-id->remapping-dimension query id))]
+                      {:original-field-clause (or (:lib/original-ref col)
+                                                  (lib/ref col))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_remaps.clj]: Consider extracting the original ref into a `let`.

File: src/metabase/query_processor/middleware/add_remaps.clj [hunk 4]
```diff
@@ -83,76 +81,81 @@
...
+                       :new-field-clause      [:field
+                                               (merge
+                                                {:lib/uuid                (str (random-uuid))
+                                                 :source-field            id
+                                                 ::new-field-dimension-id (u/the-id dimension)}
+                                                (when (lib/current-join-alias (or (:lib/original-ref col)
+                                                                                  (lib/ref col)))
+                                                  (when-let [join-alias (:metabase.lib.join/join-alias col)]
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_remaps.clj]: A comment explaining why check the existence of the join alias in the ref and then take the join alias from column would be very helpful.

File: src/metabase/query_processor/middleware/resolve_joined_fields.clj [hunk 5]
```diff
@@ -93,7 +93,7 @@
                source-query (assoc :source-query source-query))]
     ;; now deduplicate :fields clauses
     (lib.util.match/replace form
-      (m :guard (every-pred map? :fields))
+      (m :guard (every-pred map? :fields #(sequential? (:fields %))))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/resolve_joined_fields.clj]:
```suggestion
      (m :guard (every-pred map? #(sequential? (:fields %))))
```

File: test/metabase/query_processor_test/field_ref_repro_test.clj [hunk 6]
```diff
@@ -349,58 +359,154 @@
...
+                                       [:asc $user_id]
+                                       [:asc $product_id]
+                                       [:asc [:field %id {:join-alias "j"}]]
+                                       [:asc [:field %user_id {:join-alias "j"}]]]
+                            :limit    2}))
+                results (qp/process-query query)]
+            ;; should return 20 columns and 37320 rows
+            (mt/with-native-query-testing-context query
+              (is (= 20
+                     (count (mt/cols results))))
```
Comment (metamben) [inline test/metabase/query_processor_test/field_ref_repro_test.clj]: This can be removed now.

**Review by metamben — APPROVED** [review]
👍
