### PR TITLE
Check for min arg count in expressions

### LINKED ISSUE #53682: [Bug Report] model - https://stats.metabase.com/model/24105-github-actions-usage/notebook
Image

### Description
trying to create an invalid custom column expression (contains("e2e")), then clicking into the name field crashes the entire quiery builder

### Links
- Original URL: https://stats.metabase.com/model/24105-github-actions-usage/notebook
- Slack File: https://metaboat.slack.com/files/U02T6V8MXN2/F08CZT2UXF0/diagnostic-info.json

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://metaboat.slack.com/archives/C05NXACAG1G/p1739461293440689
Fixes #53682

Checks for the min number of args for multi-arg operators. 

How to verify:
- New -> Question -> Products -> Custom column
- Try `contains()`, `contains([Category])`. It should be rejected.
- Try `contains([Category], "A")`, `contains([Category], "case-insensitive")`, `contains([Category], "A", "case-insensitive")`, `contains([Category], "A", "B")`, `contains([Category], "A", "B", "case-insensitive")`. It should be allowed.

Screenshot 2025-02-19 at 15 35 53
Screenshot 2025-02-19 at 15 36 07
Screenshot 2025-02-19 at 15 36 18
Screenshot 2025-02-19 at 15 36 25

### CODE REVIEW

**Review by romeovs — APPROVED** [review]

File: frontend/src/metabase-lib/v1/expressions/resolver.js [hunk 1]
```diff
@@ -192,7 +192,21 @@ export function resolve({
         throw new ResolverError(validationError, expression.node);
       }
     }
-    if (!multiple) {
+    if (multiple) {
+      const argCount = operands.filter(arg => !isOptionsObject(arg)).length;
+      const minArgCount = args.length;
+
+      if (argCount < minArgCount) {
+        throw new ResolverError(
```
Comment (kamilmielnik) [inline frontend/src/metabase-lib/v1/expressions/resolver.js:200]: Error message in this screenshot is confusing - the function is being used with 2 arguments.

image

File: frontend/test/metabase/lib/expressions/resolver.unit.spec.js [hunk 2]
```diff
@@ -170,6 +170,31 @@ describe("metabase-lib/v1/expressions/resolve", () => {
       it("should allow substring with index=1", () => {
         expect(() => expr(["substring", "foo", 1, 1])).not.toThrow();
       });
+
```
Comment (kamilmielnik) [inline frontend/test/metabase/lib/expressions/resolver.unit.spec.js:173]: Let's also add an explicit repro for the app crash?
BTW there's a GH issue for this bug: #53682

File: frontend/src/metabase-lib/v1/expressions/resolver.js (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase-lib/v1/expressions/resolver.js:200]: The last "argument" is an option, not a real argument.

File: frontend/test/metabase/lib/expressions/resolver.unit.spec.js (hunk 2 above)
Comment (ranquild) [reply frontend/test/metabase/lib/expressions/resolver.unit.spec.js:173]: Added a e2e repro

File: frontend/src/metabase-lib/v1/expressions/resolver.js (hunk 1 above)
Comment (mngr) [reply frontend/src/metabase-lib/v1/expressions/resolver.js:200]: Why do we show an error here? Shouldn't it check if Category contains "case-insensitive" as a substring?

Comment (ranquild) [reply frontend/src/metabase-lib/v1/expressions/resolver.js:200]: Because `"case-insensitive"` is an option. You could do `contains([Category], "case-insensitive", "case-insensitive")` if you want to use this string.

Comment (ranquild) [reply frontend/src/metabase-lib/v1/expressions/resolver.js:200]: there is no way with the current implementation to just use `contains([Category], "case-insensitive"`) in case-sensitive manner.

Comment (mngr) [reply frontend/src/metabase-lib/v1/expressions/resolver.js:200]: Can we make the message more [clear, attributable and actionable](https://www.notion.so/metabase/Good-Errors-1bfc875a0ad145c5bc9736c3309d3853) then?
For example:
> Missing the string to search for, "case-insensitive" is an optional parameter

Comment (ranquild) [reply frontend/src/metabase-lib/v1/expressions/resolver.js:200]: Screenshot 2025-02-20 at 12 49 44

@mngr I changed the implementation so that it works now. Would that be acceptable?

Comment (mngr) [reply frontend/src/metabase-lib/v1/expressions/resolver.js:200]: Yes, ok!
