### PR TITLE
Fix load-from-h2 command :wrench:

### LINKED ISSUE #3592: On migration from h2 to mysql, duplicate entry error with PermissionsGroup
Metabase version 0.20
on an aws ubuntu instance
error after running "java -jar metabase.jar load-from-h2"

`Transfering 3 instances of PermissionsGroup....BatchUpdateException:
 Message: Duplicate entry '3' for key 'PRIMARY'
 SQLState: 23000
 Error Code: 1062
java.sql.BatchUpdateException: Duplicate entry '3' for key 'PRIMARY'
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1166)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:426)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:419)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__2805.invoke(jdbc.clj:792)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:791)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
	at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1069)
	at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1061)
	at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1110)
	at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1093)
	at metabase.cmd.load_from_h2$insert_entity_BANG_$fn__30770.invoke(load_from_h2.clj:125)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:124)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:106)
	at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:140)
	at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:134)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__30850.invoke(load_from_h2.clj:209)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:629)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:206)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:199)
	at clojure.lang.Var.invoke(Var.java:379)
	at metabase.core$fn__31589.invokeStatic(core.clj:209)
	at metabase.core$fn__31589.doInvoke(core.clj:207)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$run_cmd$fn__31592.invoke(core.clj:216)
	at metabase.core$run_cmd.invokeStatic(core.clj:216)
	at metabase.core$run_cmd.doInvoke(core.clj:211)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$_main.invokeStatic(core.clj:228)
	at metabase.core$_main.doInvoke(core.clj:224)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '3' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
	... 51 more
Command failed with exception: Duplicate entry '3' for key 'PRIMARY'
`

### PR DESCRIPTION
**Pull request by camsaul**
It turns out the data migrations that create the "magic" permissions groups and add users and databases to the default group was running before the code to load data from an H2 database. This was causing `load-from-h2` to fail because it tried to transfer the original magic permissions groups into the new DB which failed because of duplicate entries.

Fix this by adding some logic to disable the offending data migrations when Metabase is started via `load-from-h2`

Fixes #3592

### CODE REVIEW

File: src/metabase/db.clj [hunk 1]
```diff
@@ -368,10 +368,12 @@
...
   (create-connection-pool! (jdbc-details db-details))
 
-  ;; Do any custom code-based migrations now that the db structure is up to date
-  ;; NOTE: we use dynamic resolution to prevent circular dependencies
-  (require 'metabase.db.migrations)
-  ((resolve 'metabase.db.migrations/run-all)))
+  ;; Do any custom code-based migrations now that the db structure is up to date.
+  ;; None of the migrations should be ran when Metabase is launched via `load-from-h2`. That's because they will end up doing things like
+  ;; creating duplicate entries for the "magic" groups and permissions entries. They appropriate things will be copied over from the H2 database.
+  (when-not (= config/launch-command :load-from-h2)
```
Comment (salsakran) [inline src/metabase/db.clj]: this makes me feel really itchy.

hardcoding the specific command + a global state

**Comment by salsakran** [comment]
Why is the loading happening *after* migrations are run? That seems like the root of the problem, and this is a weird bandaid on top of that.

**Comment by camsaul** [comment]
The root problem was that we were running the data migrations on the empty DB which was unnecessary (there was no data in there to fix) and undesirable (it doesn't make sense to do things like create the "magic" groups since we'll be loading them over. 

So not sure how disabling something that shouldn't be happening is a "bandaid".

File: src/metabase/db.clj (hunk 1 above)
Comment (camsaul) [inline src/metabase/db.clj]: It's not really state because it doesn't change. It's just information about what command was used to launch Metabase.

If we change the name of the command (unlikely) we'll have to grep the codebase anyway to make sure we update the dox and the entrypoint functions. So I'm not worried about hardcoding it

**Comment by salsakran** [comment]
I'm in total agreement that we shouldn't run data migrations on an empty db.

I'm specifically objecting to the fact that the migrations code needs to know what kind of command is running. If we add a "migrate from old instance", will we need to rewrite this to be aware of that command? 

The command should control whether a migration gets run or not. The db namespace shouldn't need to know anything about what to run for each command.

👎

**Comment by camsaul** [comment]
The DB handles everything that needs to be done to set up the DB when you start using it so that kind of logic doesn't need to be spread all over the app.

**Comment by salsakran** [comment]
assuming we want to keep that, this should be a situation where there's a "run-migrations" flag that each command can set or unset. 

But db.clj shouldn't be aware of what's going on in the rest of the app.

**Comment by camsaul** [comment]
Right. I guess that makes sense. Take a look at the code again I adjusted the approach.

**Comment by salsakran** [comment]
👍  that last commit resolves my issues (which I'm guessing come from not being hugged enough as a child)
