### PR TITLE
Fix #44754: qbnewq modal can't be dismissed with keyboard

### LINKED ISSUE #44754: "It's okay to play around with saved questions" modal can't be dismissed with keyboard
### Describe the bug

This modal can't be dismissed with escape or enter.

image

### To Reproduce

1. Start up a new instance
2. Create a saved question and view it
3. Try to close the model with the keyboard

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
Current master
```

### Severity

p3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### What does this PR accomplish?
Fixes #44754.
Adds an E2E reproduction for this issue as well.

Note that @mazameli [said in Slack](https://metaboat.slack.com/archives/C02H619CJ8K/p1717517825579359) he would redesign this modal because it currently looks weird. This PR also moves the modal more toward that new design, but it is faaar from pixel perfect (since this wasn't the intention of this PR)

We can either wait for Maz to bless this change, or we can adjust the design later as needed.

**Before**
image

**Maz**
image

**This PR**
image

image

image

### Stress-test
100 x ✅ https://github.com/metabase/metabase/actions/runs/9842301728

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/SavedQuestionIntroModal.tsx [hunk 1]
```diff
@@ -48,18 +44,19 @@ export const SavedQuestionIntroModal = ({
...
-      </ModalContent>
-    </Modal>
+    <Modal.Root opened={isShowingNewbModal} onClose={onClose} size={500}>
+      <Modal.Overlay />
+      <Modal.Content p="md">
+        <Modal.Header mb="md">
+          <Modal.Title>{title}</Modal.Title>
+        </Modal.Header>
+        <Modal.Body ta="center">
+          <Box mb="md" ta="left">
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/SavedQuestionIntroModal.tsx:54]: You can convert it to `Text` and play with text settings to make it look line in the designs.

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/SavedQuestionIntroModal.tsx (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/SavedQuestionIntroModal.tsx]: https://github.com/metabase/metabase/pull/45148/commits/f2884d883daee4c531a2a2e4e96642a2e4615aee
