### PR TITLE
QB3 mobile layouts

### LINKED ISSUE #10503: View mode shouldn't look broken on mobile
There are some max-widths and wrapping behaviors that we should alter to make questions look respectable at mobile widths:

- Title can be wider
- Collection and data source breadcrumbs should be wider and wrap to next line if needed
- Active filters should wrap to new line if expanded
- Lineage should be on a new line
- Refresh should be visible, ideally in top-right
- Probably hide the Open Editor button
- Either hide Filter and Summarize, or put on new line
- Stretch: have filter, summarize, and viz sidebars slide all the way in to take up 100% of the available width

image

image

### LINKED ISSUE #10582: When a user doesn't have SQL editor access, the new question page doesn't show the Custom Question option
Possibly related to #10527? But not fixed by https://github.com/metabase/metabase/pull/10574

If I don't have SQL editor access to any database, when I click the New Question button I go straight to the Simple Question data selection step. I can still get to the notebook from the top-right button and use it normally, though:

no-notebook-option

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #10503
Resolves #10582

Screenshot 2019-08-12 16 48 11

Screenshot 2019-08-12 16 49 31

Screenshot 2019-08-12 16 50 10

Screenshot 2019-08-12 16 50 25

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/view/ViewSection.jsx [hunk 1]
```diff
@@ -4,8 +4,15 @@ import { Flex } from "grid-styled";
...
-  <Flex align="center" px={3} style={style} {...props} className={className} />
+const ViewSection = ({
+  align = "center",
+  bottom,
+  trim,
+  style,
+  className,
+  ...props
+}) => (
+  <Flex align={align} px={3} style={style} {...props} className={className} />
```
Comment (kdoh) [inline frontend/src/metabase/query_builder/components/view/ViewSection.jsx]: I think we'll want to adjust the `px` value here so that it's a little tighter on mobile. I'd go with `px={[1,3]}`

**Comment by mazameli** [comment]
Two main things:
1.  The bottom action buttons feel too small when you view this on a phone. I'll take a look at tweaking that.
2. Still some wonky alignment/spacing when there's a combination of expanded filters, data breadcrumbs, and filters:
image

Couple other things:
- the DB+table page title for raw data questions isn't looking properly aligned (should be further down)
- the gear icon in the top right seems to be getting clipped a bit
- on the Browse page, we should probably collapse the `learn about our data` link to be just the book icon, because it's colliding with the database+table breadcrumbs

**Comment by tlrobinson** [comment]
@mazameli are these release blockers?

**Comment by mazameli** [comment]
Pushed a commit to enlarge the action buttons a bit for mobile and to space out the toggle some:

image

**Comment by mazameli** [comment]
It looks like the thing I noticed with the raw data breadcrumb titles being too high up (or having too much padding below) is happening in view and notebook modes on desktop, too. That's a merge blocker for me.

image

**Expected:**

image

**Comment by mazameli** [comment]
@tlrobinson I think the only _real_ 0.33 release blocker in this branch is what I just commented on since it impacts desktop mode. The gear icon item is borderline for me; looks a bit janky.

The other two items (lineage and filter padding/alignment, and collapsing the Learn About Our Data link are not blockers IMO. 

Most states of View mode and even the Notebook are looking pretty good or at least passable now.

**Review by kdoh — APPROVED** [review]

**Comment by mazameli** [comment]
One thing I noticed is that we're letting folks get to the notebook from the NQF, but you can't get back there once you're in View mode. Maybe on mobile we put a button to go to the notebook in the bottom-right? I think it could probably fit next to the data/viz toggle for summarized questions, and we could maybe just hide the "showing x rows" label on raw data questions so there could be room for the notebook button in that state as well.

WDYT @kdoh?
