### PR TITLE
[QP] Allow multiple dashboard/card params to exist, if only one is set

### LINKED ISSUE #64135: If you Combine Native Questions with the SQL Vars via Visualizer and Wire both Dashboard & Card Filters to the SQL Var they Completely Fail
### Describe the bug

If you have two native questions with SQL variables, combine them with the visualizer on a dashboard, then wire both dashboard and card level filters to the multi-series viz it dies in a bad way. The card won't load, is not editable and can't be removed in edit mode.

Completely removing the dashboard filter allows you to modify the card - but this is a really burdensome approach for customer with larges dashboards / lots of tabs that are wired to the card. It's also not obvious. The dashboard that had this problem contained 20+ filters and identifying the implicated filter was not simple (particularly since we can no longer replicate dashboards for testing much of the time due to cards being saved in the dashboard)

### To Reproduce

1. Write 2 native SQL questions with a SQL variable (I tested with number type)
2. Add one of them to a dashabord
3. Using the visualizer, add the second card to the first on the dashboard
4. Wire a dashboard filter to the SQL varaibles
5. Wire a card level filter to the SQL variables
6. Save
7. Be sad

Here's a recording:
https://www.loom.com/share/a71ec27a6b1f469b967c8f98770471f8

### Expected behavior

The card should load

### Logs

[917c271d-7c4a-41b1-9609-72ba11cfe5c4] 2025-09-26T16:46:09-04:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: Error: multiple values specified for parameter; non-Field Filter parameters can only have one value.
{:database_id 1,
 :parameterized false,
 :started_at #t "2025-09-26T20:46:09.626944303Z[GMT]",
 :via
 [{:status :failed,
   :class clojure.lang.ExceptionInfo,
   :error
   "Error determining value for parameter \"orderID\": Error: multiple values specified for parameter; non-Field Filter parameters can only have one value.",
   :stacktrace
   ["--> driver.common.parameters.values$value_for_tag.invokeStatic(values.clj:436)"
    "driver.common.parameters.values$value_for_tag.invoke(values.clj:428)"
    "driver.common.parameters.values$query__GT_params_map$iter__93064__93068$fn__93069.invoke(values.clj:454)"
    "driver.common.parameters.values$query__GT_params_map.invokeStatic(values.clj:453)"
    "driver.common.parameters.values$query__GT_params_map.invoke(values.clj:444)"
    "driver.sql$fn__93121$f__15385__auto____93123.invoke(sql.clj:63)"
    "query_processor.middleware.parameters.native$expand_inner.invokeStatic(native.clj:43)"
    "query_processor.middleware.parameters.native$expand_inner.invoke(native.clj:34)"
    "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:66)"
    "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:57)"
    "query_processor.middleware.parameters$expand_all$replace_83799__83800.invoke(parameters.clj:77)"
    "lib.util.match.impl$replace_in_collection$fn__19699.invoke(impl.cljc:53)"
    "lib.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:52)"
    "lib.util.match.impl$replace_in_collection.invoke(impl.cljc:47)"
    "query_processor.middleware.parameters$expand_all$replace_83799__83800.invoke(parameters.clj:75)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:75)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:69)"
    "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:72)"
    "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:69)"
    "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:99)"
    "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:94)"
    "query_processor.middleware.parameters$substitute_parameters_STAR_.invokeStatic(parameters.clj:108)"
    "query_processor.middleware.parameters$substitute_parameters_STAR_.invoke(parameters.clj:105)"
    "query_processor.middleware.parameters$substitute_parameters.invokeStatic(parameters.clj:135)"
    "query_processor.middleware.parameters$substitute_parameters.invoke(parameters.clj:126)"
    "query_processor.preprocess$ensure_legacy$fn__85247.invoke(preprocess.clj:70)"
    "query_processor.preprocess$preprocess$fn__85271$fn__85272.invoke(preprocess.clj:198)"
    "query_processor.preprocess$preprocess$fn__85271.invoke(preprocess.clj:187)"
    "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225)"
    "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
    "query_processor.preprocess$preprocess.invokeStatic(preprocess.clj:185)"
    "query_processor.preprocess$preprocess.invoke(preprocess.clj:181)"
    "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)"
    "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:45)"
    "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$fn__93953$handle_audit_app_internal_queries__93954$fn__93955.invoke(handle_audit_queries.clj:143)"
    "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__77385.invoke(enterprise.clj:142)"
    "query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__85379.invoke(process_userland_query.clj:179)"
    "query_processor.middleware.catch_exceptions$catch_exceptions$fn__85439.invoke(catch_exceptions.clj:137)"
    "query_processor$process_query$fn__85504.invoke(query_processor....

### Information about your Metabase installation

```JSON
v56.5, 56.7
```

### Severity

blocking in some cases

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bshepherdson**
Fixes #64135.

### Description

Previously this code would throw if multiple dashboard and/or card
params were bound to the same SQL variable. Now multiple links are
allowed, provided that only one is actually given a value.

Actually, this logic de-duplicates the values, so if multiple filters
all set the same value, that also works.

### How to verify

1. Create a SQL question with a variable, eg.
   `SELECT * FROM ORDERS [[WHERE product_id = {{product}}]]`.
2. Add that card to a dashboard.
3. Add a dashboard filter (type Number) linked to `product`.
4. Add a card filter (type Number) linked to `product`.

Previously, the card would fail to run. Now the QP will accept it.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#64428** <a href="https://app.graphite.com/github/pr/metabase/metabase/64428?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/metabase/metabase/64428?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: src/metabase/driver/common/parameters/values.clj [hunk 1]
```diff
@@ -303,27 +304,31 @@
...
+      (:default tag)              (:default tag)
+      ;; If there are conflicting default values among the parameters, throw.
+      (> (count defaults) 1)
+      (throw (multiple-conflicting-default-values-exception (:display-name tag)))
+      ;; If there is exactly one (distinct) default value among the matching parameters, use it.
+      (= (count defaults) 1)      (first defaults)
+      ;; No value at all - throw if this tag was required.
+      (:required tag)             (throw (missing-required-param-exception (:display-name tag)))
+      ;; Fall back to no value.
+      :else                       params/no-value)))
```
Comment (metamben) [inline src/metabase/driver/common/parameters/values.clj:339]: These two branches could be swapped for symmetry with the order so far.

**Review by metamben — APPROVED** [review]
