### PR TITLE
Do not offer to save questions to view-only collections

### LINKED ISSUE #22727: Do not offer to save questions to view-only collections
**Describe the bug**
When modifying a question in a view-only collection and clicking Save, then it offers to save in the current collection, but that will result in permission error, which is not handled by the frontend correctly, so it just shows a javascript error.

P2 because of the bad error shown.

**To Reproduce**
1. Question > Sample > Orders - save as "Q1" in "Our analytics"
2. Admin > Permissions > Collections > set "Our analytics" to `View` for "All users"
3. Login as user and go to "Q1" and make a modification to the question (e.g. sort by ID)
4. Click "Save" - by default it offers to save the question in "Our analytics", even though it's not one of the available collections
image
5. Just clicking "Save" in the modal, without manually changing the collection, will show the very unhelpful error `e is undefined` (Firefox) or `Cannot read properties of undefined (reading 'id')` (Chrome)
image

The backend returns a more sensible error: `You do not have curate permissions for this Collection.`
<details><summary>Full stacktrace</summary>

```
2022-05-14 12:12:39,049 WARN middleware.log :: POST /api/card 403 29.5 ms (9 DB calls) 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "You do not have curate permissions for this Collection.",
   :data
   {:status-code 403,
    :collection nil,
    :required-perms "/collection/root/",
    :actual-perms
    #{"/collection/root/read/"
      "/collection/3/"
      "/db/4/schema/"
      "/collection/143/read/"
      "/collection/12/read/"
      "/collection/32/"
      "/collection/2/read/"
      "/collection/144/read/"}},
   :at [metabase.models.collection$check_write_perms_for_collection invokeStatic "collection.clj" 908]}],
 :trace
 [[metabase.models.collection$check_write_perms_for_collection invokeStatic "collection.clj" 908]
  [metabase.models.collection$check_write_perms_for_collection invoke "collection.clj" 899]
  [metabase.api.card$fn__72165 invokeStatic "card.clj" 308]
  [metabase.api.card$fn__72165 invoke "card.clj" 293]
  [compojure.core$wrap_response$fn__28029 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__28013 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__28018 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__28022 invoke "core.clj" 151]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28022 invoke "core.clj" 152]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__66669 invoke "auth.clj" 14]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28069 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28073 invoke "core.clj" 299]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28073 invoke "core.clj" 300]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28073 invoke "core.clj" 300]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043 invoke "core.clj" 197]
  [compojure.core$make_context$fn__28073 invoke "core.clj" 300]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043 invoke "core.clj" 197]
  [metabase.api.routes$fn__78001$fn__78004 invoke "routes.clj" 59]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__78149$fn__78150 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041 invoke "core.clj" 200]
  [compojure.core$make_context$handler__28069 invoke "core.clj" 289]
  [compojure.core$make_context$fn__28073 invoke "core.clj" 299]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28022 invoke "core.clj" 153]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28022 invoke "core.clj" 153]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__28022 invoke "core.clj" 153]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043 invoke "core.clj" 197]
  [metabase.server.routes$fn__78137$fn__78139 invoke "routes.clj" 41]
  [compojure.core$routes$fn__28041$f__28042 invoke "core.clj" 198]
  [compojure.core$routes$fn__28041 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__74985 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__74982 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__78619$fn__78620$fn__78621 invoke "log.clj" 211]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__78619$fn__78620 invoke "log.clj" 203]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__78619 invoke "log.clj" 202]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__81845 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__60355 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__80994 invoke "json.clj" 63]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__81012 invoke "json.clj" 99]
  [metabase.server.middleware.offset_paging$handle_paging$fn__60379 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__82112 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__82131 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__35170 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__46635$fn__46636 invoke "session.clj" 291]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 270]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 259]
  [metabase.server.middleware.session$bind_current_user$fn__46635 invoke "session.clj" 290]
  [metabase.server.middleware.session$wrap_current_user_info$fn__46617 invoke "session.clj" 240]
  [metabase.server.middleware.session$wrap_session_id$fn__46601 invoke "session.clj" 173]
  [metabase.server.middleware.auth$wrap_api_key$fn__66677 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__82032 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__35153 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__35178 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__82074 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__35181 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__81861 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__78391 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 400]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 645]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 392]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 409]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run "Thread.java" 829]],
 :cause "You do not have curate permissions for this Collection.",
 :data
 {:status-code 403,
  :collection nil,
  :required-perms "/collection/root/",
  :actual-perms
  #{"/collection/root/read/"
    "/collection/3/"
    "/db/4/schema/"
    "/collection/143/read/"
    "/collection/12/read/"
    "/collection/32/"
    "/collection/2/read/"
    "/collection/144/read/"}},
 :message "You do not have curate permissions for this Collection.",
 :collection nil,
 :required-perms "/collection/root/",
 :actual-perms
 #{"/collection/root/read/"
   "/collection/3/"
   "/db/4/schema/"
   "/collection/143/read/"
   "/collection/12/read/"
   "/collection/32/"
   "/collection/2/read/"
   "/collection/144/read/"}}
```

</details>

**Expected behavior**
- Do not offer collections, which are view-only.
- Show a proper error

**Information about your Metabase Installation:**
Tested 0.42.4 thru 0.43.0

**Additional context**
Historical #7881 and #15281 and #20717

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/22727

When saving a question forked from another question in a read-only collection, do not suggest the original question's collection. Also makes this model display backend error messages, if any.

How to test:
- There a cypress test that reproduces the issue

Screenshot 2022-07-26 at 16 09 23

### CODE REVIEW

File: frontend/src/metabase/containers/SaveQuestionModal.jsx [hunk 1]
```diff
@@ -87,7 +87,8 @@ export default class SaveQuestionModal extends Component {
           : "",
       description: card.description || "",
       collection_id:
-        card.collection_id === undefined
+        card.collection_id === undefined ||
+        (originalCard != null && !originalCard.can_write)
```
Comment (kulyk) [inline frontend/src/metabase/containers/SaveQuestionModal.jsx:91]: I think it might be worth extracting to a constant with a readable name. Needed a moment to parse that

File: frontend/src/metabase/entities/schemas.js [hunk 2]
```diff
@@ -50,8 +50,8 @@ export default createEntity({
     },
   },
 
-  reducer: (state = {}, { type, payload }) => {
-    if (type === Questions.actionTypes.CREATE) {
+  reducer: (state = {}, { type, payload, error }) => {
+    if (type === Questions.actionTypes.CREATE && !error) {
```
Comment (kulyk) [inline frontend/src/metabase/entities/schemas.js:54]: This makes me think about other entity reducers handling this kind of actions. I think most of them don't do the `!error` check. Would it make sense to go through them and add them? WDYT? No meaning this specific PR

**Review by kulyk — APPROVED** [review]
LGTM! Got a question and a cosmetic change proposal

File: frontend/src/metabase/entities/schemas.js (hunk 2 above)
Comment (ranquild) [reply frontend/src/metabase/entities/schemas.js:54]: Sure, I'll do that

Comment (kulyk) [reply frontend/src/metabase/entities/schemas.js:54]: Thank you!
