### PR TITLE
Pass missing native extras when switching databases

### LINKED ISSUE #53299: It's not possible to switch to MongoDB in native query editor
### Describe the bug

Locally, I'm running the sample database and a MongoDB database.

I cannot write native queries in the MongoDB anymore.

### To Reproduce

1. New > Native query
2. Click the datbase selector and select the MongoDB instance
3. Nothing happens

There is an error message in the browser console:
```
Uncaught (in promise) Error: Assert failed: Missing extra, required keys for native query: #{:collection}
(empty? missing-keys)
    with_native_extras61457 native.cljc:150
    3 core.cljs:5464
    cljs$core$IFn$_invoke$arity$3 app-main.hot.bundle.js:35442
    cljs$core$apply_to core.cljs:3966
    cljs$core$IFn$_invoke$arity$5 core.cljs:4045
    metabase$lib$util$update_query_stage37074__delegate util.cljc:348
    metabase$lib$util$update_query_stage37074 util.cljc:343
    metabase$lib$native$with_native_extras61457 native.cljc:141
    metabase$lib$native$with_different_database61459__3 native.cljc:186
    cljs$core$IFn$_invoke$arity$5 core.cljs:4001
    cljs$core$IFn$_invoke$arity$4 core.cljs:3997
    cljs$core$IFn$_invoke$arity$3 core.cljs:3991
    cljs$core$IFn$_invoke$arity$2 core.cljs:3985
    cljs$core$IFn$_invoke$arity$2 core.cljs:4020
    metabase$lib$core$with_different_database__delegate core.cljc:80
    cljs$core$IFn$_invoke$arity$4 js.cljs:1898
    cljs$core$IFn$_invoke$arity$3 js.cljs:1898
    metabase$lib$js$with_different_database js.cljs:1898
    withDifferentDatabase native.ts:39
    setDatabaseId NativeQuery.ts:161
    setDatabaseId NativeQueryEditor.tsx:246
    onChangeDatabase DataSelector.jsx:781
    onChange DataSelectorDatabasePicker.tsx:86
    handleChange AccordionList.jsx:252
    onClick AccordionListCell.jsx:276
    React 15
    4 native.cljc:150
```

### Expected behavior

I should be able to select the MongoDB instance.

### Logs

_No response_

### Information about your Metabase installation

```JSON
`master` on `c9d6609021f5db9275a0307190c3db7c727eb555`
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/53299

Passes the missing `nativeExtras` map when switching databases.

To test:
1. Make sure you have a mongo db database set up
1. New > Native query
2. Click the data selector and select the Mongo DB

This should work

### CODE REVIEW

File: frontend/src/metabase-lib/v1/queries/NativeQuery.ts [hunk 1]
```diff
@@ -158,10 +158,15 @@ export default class NativeQuery extends AtomicQuery {
   setDatabaseId(databaseId: DatabaseId): NativeQuery {
     if (databaseId !== this._databaseId()) {
       const metadataProvider = Lib.metadataProvider(databaseId, this._metadata);
+      const extras = Lib.nativeExtras(this._query());
       const newQuery = Lib.withDifferentDatabase(
         this._query(),
         databaseId,
         metadataProvider,
+        {
+          collection: null,
```
Comment (romeovs) [inline frontend/src/metabase-lib/v1/queries/NativeQuery.ts:167]: Should we always be passing this? Or should we look at the query to see what's missing?

Comment (ranquild) [reply frontend/src/metabase-lib/v1/queries/NativeQuery.ts:167]: what happens if you just pass `extras`?

Comment (ranquild) [reply frontend/src/metabase-lib/v1/queries/NativeQuery.ts:167]: I mean, without spreading and without `collection: null`

**Review by filiphric — APPROVED** [review]

File: frontend/src/metabase-lib/v1/queries/NativeQuery.ts (hunk 1 above)
Comment (romeovs) [reply frontend/src/metabase-lib/v1/queries/NativeQuery.ts:167]: In my case extra's is `{}` so, so it's the same issue.

**Review by ranquild — CHANGES_REQUESTED** [review]
@romeovs I think the API is broken and we cannot provide valid `native-extras` at all when switching databases. This part should be removed https://github.com/metabase/metabase/blob/5fe517a03ea9b7922260c55e7b65fdb7971807d7/src/metabase/lib/native.cljc#L187, and there should be no extra parameter in a `withDifferenceDatabase` call.

**Comment by romeovs** [comment]
@ranquild I've removed the requirement from the call site and from its corresponding test.

**Review by ranquild — APPROVED** [review]

**Review by lbrdnk — APPROVED** [review]
