### PR TITLE
 Closes VIZ-982 settings not always being propagated 

### LINKED ISSUE #57902: Question viz settings aren't always propagated to "Visualize another way"
### Describe the bug

[Repro loom](https://www.loom.com/share/314d9d8c6d3e454b964a230b863edae5?sid=cc05fe57-ccf8-43f6-816c-6bbde8431de6).

### To Reproduce

See above

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
Master
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorem--ipsum**
closes #57902
Closes [VIZ-982: Question viz settings aren't always propagated to "Visualize another way"](https://linear.app/metabase/issue/VIZ-982/question-viz-settings-arent-always-propagated-to-visualize-another-way)

### Description

Series specific settings weren't propagated when converting a question to a visualizer card, because it weren't migrated to use column refs' names.

### Demo

https://www.loom.com/share/1703c6de8bea44a089b310c586e4efe4

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizer/utils/update-viz-settings-with-refs.ts [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+ * If the settings contain the color for a series called, say, `avg` (`{colors: {avg: "#000"}}`),
+ * and the column reference for `avg` is `COLUMN_1`, this function will convert it
+ * to `{colors: {COLUMN_1: "#000"}}`.
+ *
+ *
+ * @param settings the settings to convert
+ * @param columnsToRefs the mapping of column names to their references
+ * @returns the converted settings
+ */
+export function updateVizSettingsWithRefs(
```
Comment (alxnddr) [inline frontend/src/metabase/visualizer/utils/update-viz-settings-with-refs.ts:15]: Wdyt about changing this signature to `deepUpdateObjectKeys(object: unknown, mapping: Record<string, string>)` to make it more precise and remove type casts like `null as any` in specs?

**Review by alxnddr — APPROVED** [review]
Works good! I left one minor comment, please have a look before merging

File: frontend/src/metabase/visualizer/utils/update-viz-settings-with-refs.ts (hunk 1 above)
Comment (lorem--ipsum) [reply frontend/src/metabase/visualizer/utils/update-viz-settings-with-refs.ts:15]: I don't want this function to be too generic, in fact I think the specs that test it against non-object values is meaningless (I'll remove it), TS would catch that.
