### PR TITLE
Unify TTLs for token check caching, simplify some code

### LINKED ISSUE #49879: We broken premium token caching
### Describe the bug

We refactored the token check mechanism in https://github.com/metabase/metabase/pull/48147
Looks like we have two problems:

1. We Log that we are checking the token with the metastore _a lot_.

```shell
2024-11-12 07:46:39,006 DEBUG middleware.log :: GET /api/setup/admin_checklist 200 6.5 ms (11 DB calls) App DB connections: 0/10 Jetty threads: 8/50 (5 idle, 0 queued) (67 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:46:39,213 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:46:39,217 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:46:39,219 DEBUG middleware.log :: GET /api/setting 200 230.5 ms (20 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (5 idle, 0 queued) (67 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:46:39,221 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:46:39,221 DEBUG middleware.log :: GET /api/session/properties 200 235.7 ms (14 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (5 idle, 0 queued) (67 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:46:39,235 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:46:39,240 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:46:39,240 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:46:39,241 DEBUG middleware.log :: GET /api/session/properties 200 15.4 ms (14 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (5 idle, 0 queued) (67 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:46:39,243 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
```

2. And *far more serious*, we are not honoring the 24 hour cache policy but only a 5 minute cache policy. 

The thing to note from https://github.com/metabase/metabase/pull/48147 is that the function`metabase.public-settings.premium-features/fetch-token-status` went from a TTL of 24 hours to no caching. And the only thing catching us is that we had some double redundancy in `fetch-token-and-parse-body*` of `(u/minutes->ms 5)`.

### To Reproduce

`MB_JETTY_PORT=3006 MB_PREMIUM_EMBEDDING_TOKEN=$TOKEN java "$(socket-repl 6006)" -jar $JARS/1.51.1.8.jar`

and then see the logs. I've instrumented my jar to print out when it is actually making the request and i dropped the cache duration from 5 minutes to 20 seconds to illustrate the problem.

```
2024-11-12 07:43:25,561 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:43:25,561 DEBUG middleware.log :: GET /api/user/current 200 12.8 ms (12 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (6 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
******************************************************************************
MAKING THE REQUEST
******************************************************************************
2024-11-12 07:43:25,592 DEBUG middleware.log :: GET /api/database 200 4.4 ms (1 DB calls) App DB connections: 0/10 Jetty threads: 10/50 (4 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:43:25,617 DEBUG middleware.log :: GET /api/search 200 27.7 ms (5 DB calls) App DB connections: 0/10 Jetty threads: 7/50 (4 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
...
2024-11-12 07:43:50,355 DEBUG middleware.log :: GET /api/session/properties 200 19.5 ms (14 DB calls) App DB connections: 0/10 Jetty threads: 7/50 (5 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:43:50,361 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:43:50,364 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:43:50,365 DEBUG middleware.log :: GET /api/setting 200 30.4 ms (20 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (5 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:43:50,391 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:43:50,405 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:43:50,406 DEBUG middleware.log :: GET /api/session/properties 200 40.9 ms (14 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (5 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:43:50,411 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:43:50,414 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:43:50,415 DEBUG middleware.log :: GET /api/setting 200 45.4 ms (20 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (5 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:45:57,965 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:45:57,966 DEBUG middleware.log :: GET /api/collection/tree 200 22.4 ms (4 DB calls) App DB connections: 0/10 Jetty threads: 10/50 (0 idle, 0 queued) (60 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:45:57,966 DEBUG middleware.log :: GET /api/activity/recents 200 20.2 ms (2 DB calls) App DB connections: 0/10 Jetty threads: 10/50 (0 idle, 0 queued) (60 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:45:57,966 DEBUG middleware.log :: GET /api/database 200 21.8 ms (1 DB calls) App DB connections: 0/10 Jetty threads: 10/50 (0 idle, 0 queued) (60 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
******************************************************************************
MAKING THE REQUEST
******************************************************************************
...
2024-11-12 07:45:58,010 DEBUG middleware.log :: GET /api/automagic-dashboards/database/1/candidates 200 17.9 ms (12 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (5 idle, 0 queued) (67 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:45:58,194 DEBUG middleware.log :: GET /api/util/bug_report_details 200 250.1 ms (1 DB calls) App DB connections: 0/10 Jetty threads: 5/50 (5 idle, 0 queued) (67 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:46:39,003 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
******************************************************************************
MAKING THE REQUEST
******************************************************************************
2024-11-12 07:46:39,006 DEBUG middleware.log :: GET /api/setup/admin_checklist 200 6.5 ms (11 DB calls) App DB connections: 0/10 Jetty threads: 8/50 (5 idle, 0 queued) (67 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:46:39,213 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:46:39,217 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...
2024-11-12 07:46:39,219 DEBUG middleware.log :: GET /api/setting 200 230.5 ms (20 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (5 idle, 0 queued) (67 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-11-12 07:46:39,221 INFO public-settings.premium-features :: Checking with the MetaStore to see whether token 'f325...d01a' is valid...

```

So over a span of a few minutes (`07:46:39,221` - `07:43:25,561`) i've made three actual token requests to the store and have logged _myriad_ logs of "Checking with the MetaStore to see whether token"

### Expected behavior

We should cache token checks for 24 hours

### Logs

_No response_

### Information about your Metabase installation

```JSON
1.51.1.8.jar
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes https://github.com/metabase/metabase/issues/49879

* Standardizes TTL for token check memoization to be 12 hours
* A little refactor/simplification of related code

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#49916** <a href="https://app.graphite.dev/github/pr/metabase/metabase/49916?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: src/metabase/public_settings/premium_features.clj [hunk 1]
```diff
@@ -208,27 +214,25 @@
...
-                          (let [body (u/ignore-exceptions (some-> (ex-data e1) :body (json/parse-string keyword)))]
-                            (or
-                             body
-                             {:valid         false
-                              :status        (tru "Unable to validate token")
-                              :error-details (.getMessage e1)}))))))))
+        (let [site-uuid (setting/get :site-uuid-for-premium-features-token-checks)]
+          (try (fetch-token-and-parse-body token token-check-url site-uuid)
+               (catch Exception e1
+                 ;; Unwrap exception from inside the future
```
Comment (johnswanson) [inline src/metabase/public_settings/premium_features.clj:220]: I think this was my fault from my previous refactor and definitely not a blocker but I just noticed that this comment is outdated, we're no longer unwrapping anything.

**Review by johnswanson — APPROVED** [review]
LGTM!
