### PR TITLE
fix tab actions not working in firefox

### LINKED ISSUE #45364: Duplicate a tab on dashboard only works once per dashboard
### Describe the bug

I can make a duplicate of a dashboard tab only a single time. When trying to make another duplicate (of the same tab or another tab), nothing happens.  
Deleting the first tab doesn't work either.

Even after saving the dashboard, refreshing the browser window, and opening the dashboard again, duplicate/delete doesn't work.

I managed to delete the first tab when opening the dashboard in an Incognito window. However, this workaround does NOT work for our real (more complicated) dashboards.

### To Reproduce

1. New dashbaord
2. Add a text element to the first (and only) tab "Tab 1"
3. Duplicate the tab      
    image
4. --> Now I have two tabs: "Tab 1" and "Copy of Tab 1"      
image
5. Try to create another duplicate of "Tab 1"  
    image
6. --> Nothing happens

And to delete:
7. Try to delete "Tab 1"  
    image
8. --> Nothing happens

Retry delete:
9. Save the dashboard
10. Refresh the browser
11. Open dashboard in edit mode
12. Try to delete "Tab 1"
13. --> Nothing happens

### Expected behavior

Duplication and deletion should work without the need to open a new Incognito browser window after each operation.

### Logs

Just clicking the pencil to "Edit the dashboard" already gives errors in the browser:

```
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
```

When trying the second duplicate:
```
Uncaught TypeError: r.hasAttribute is not a function
    r use-click-outside.js:10
    o use-click-outside.js:17
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 16
        ir
        ia
        io
        eB
        tF
        re
        n9
        n7
        n7
        n
        a8
        a6
        a4
        a4
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        ir
        ia
        io
        eB
        tF
[use-click-outside.js:10:63](webpack:///node_modules/@mantine/hooks/esm/use-click-outside/use-click-outside.js)
    r use-click-outside.js:10
    (Async: EventListener.handleEvent)
    o use-click-outside.js:17
    forEach self-hosted:157
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 8
    forEach self-hosted:4280
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
Uncaught TypeError: r.hasAttribute is not a function
    r use-click-outside.js:10
    o use-click-outside.js:17
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
        ir
        ia
        io
        a$
        enqueueSetState
        setState
    __updateSize ExplicitSize.tsx:192
    Lodash 2
        M
        O
    t resize-observer.ts:12
    t resize-observer.ts:12
    t resize-observer.ts:10
3 [use-click-outside.js:10:63](webpack:///node_modules/@mantine/hooks/esm/use-click-outside/use-click-outside.js)
    r use-click-outside.js:10
    (Async: EventListener.handleEvent)
    o use-click-outside.js:17
    forEach self-hosted:157
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    __updateSize ExplicitSize.tsx:192
    Lodash 2
    t resize-observer.ts:12
    forEach self-hosted:157
    t resize-observer.ts:12
    forEach self-hosted:157
    t resize-observer.ts:10
```

When trying to delete:
```
Uncaught TypeError: r.hasAttribute is not a function
    r use-click-outside.js:10
    o use-click-outside.js:17
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        ir
        ia
        io
        eB
        tF
[use-click-outside.js:10:63](webpack:///node_modules/@mantine/hooks/esm/use-click-outside/use-click-outside.js)
    r use-click-outside.js:10
    (Async: EventListener.handleEvent)
    o use-click-outside.js:17
    forEach self-hosted:157
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
Uncaught TypeError: r.hasAttribute is not a function
    r use-click-outside.js:10
    o use-click-outside.js:17
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
        ir
        ia
        io
        a$
        enqueueSetState
        setState
    __updateSize ExplicitSize.tsx:192
    Lodash 2
        M
        O
    t resize-observer.ts:12
    t resize-observer.ts:12
    t resize-observer.ts:10
3 [use-click-outside.js:10:63](webpack:///node_modules/@mantine/hooks/esm/use-click-outside/use-click-outside.js)
    r use-click-outside.js:10
    (Async: EventListener.handleEvent)
    o use-click-outside.js:17
    forEach self-hosted:157
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    __updateSize ExplicitSize.tsx:192
    Lodash 2
    t resize-observer.ts:12
    forEach self-hosted:157
    t resize-observer.ts:12
    forEach self-hosted:157
    t resize-observer.ts:10
```

After saving, refreshing the browser window and editing again. When trying to delete:
```
Uncaught TypeError: r.hasAttribute is not a function
    r use-click-outside.js:10
    o use-click-outside.js:17
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        ia
        io
        aJ
    Redux 12
        notify
        notifyNestedSubs
        i
        m
        default
        el
        el
        eF
        default
        a
        dispatch
        unsubscribe
    React 2
        r
        sn
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 13
        ir
        ia
        io
        eB
        tF
        re
        n9
        n7
        n7
        sz
        _reactRootContainer
        s_
        render
    fn app.js:68
    fl app.js:99
    32900 app-main.js:24
    Webpack 6
        a
        <anonymous>
        O
        <anonymous>
        i
        <anonymous>
[use-click-outside.js:10:63](webpack:///node_modules/@mantine/hooks/esm/use-click-outside/use-click-outside.js)
Uncaught TypeError: r.hasAttribute is not a function
    r use-click-outside.js:10
    o use-click-outside.js:17
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        ir
        ia
        io
        a$
        oW
    d use-tooltip.js:15
    React 4
        T
        r
        A
        sn
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        ia
        io
        aJ
    Redux 12
        notify
        notifyNestedSubs
        i
        m
        default
        el
        el
        eF
        default
        a
        dispatch
        unsubscribe
    React 2
        r
        sn
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 13
        ir
        ia
        io
        eB
        tF
        re
        n9
        n7
        n7
        sz
        _reactRootContainer
        s_
        render
    fn app.js:68
    fl app.js:99
    32900 app-main.js:24
    Webpack 6
        a
        <anonymous>
        O
        <anonymous>
        i
        <anonymous>
3 [use-click-outside.js:10:63](webpack:///node_modules/@mantine/hooks/esm/use-click-outside/use-click-outside.js)
    r use-click-outside.js:10
    (Async: EventListener.handleEvent)
    o use-click-outside.js:17
    forEach self-hosted:157
    o use-click-outside.js:17
    sn React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        ir
        ia
        io
        a$
        oW
    d use-tooltip.js:15
    React 4
        T
        r
    (Async: EventListener.handleEvent)
        A
        sn
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        ia
        io
        aJ
    Redux 12
        notify
        notifyNestedSubs
        i
        m
        default
        el
    (Async: VoidFunction)
        el
        eF
        default
        a
        dispatch
        unsubscribe
    React 2
        r
        sn
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        ir
        se
        aK
        ia
    unstable_runWithPriority scheduler.production.min.js:18
    React 8
        ir
        ia
        io
        eB
        tF
    (Async: EventListener.handleEvent)
        re
        n9
        n7
    forEach self-hosted:4280
    React 5
        n7
        sz
        _reactRootContainer
        s_
        render
    fn app.js:68
    fl app.js:99
    32900 app-main.js:24
    Webpack 6
        a
        <anonymous>
        O
        <anonymous>
        i
        <anonymous>
```

No message in the server log.

### Information about your Metabase installation

```
- Firefox 127.0.2
- Windows 11
- Postgres 14
- Metabase 0.50.11
- Metabase internal database: Postgres 14
```

### Severity

Blocks dashboard creators

### PR DESCRIPTION
**Pull request by EmmadUsmani**
Closes https://github.com/metabase/metabase/issues/45364

### Description

The root cause of the issue is a bug in React 18: https://github.com/facebook/react/issues/25282. Our issue only surfaced after v50 release since we just upgraded to React 18. What happened was `TabButton` would re-render excessively when clicking on tabs or tab menu items, due to it's use of the `isDragging` value from the `useSortable` hook. These re-renders caused the `onClick` handler in `TabButtonMenu` to be lost, which is why nothing was happening when the user tried to duplicate or delete a tab. For some unknown reason, this bug would only appear in Firefox, not Chrome or Safari.

To resolve the issue, we eliminate the excessive re-renders by no longer using the `useSortable` hook and its `isDragging` value in `TabButton`. This boolean was originally used to truncate the name of a tab to allow it to be dragged to the end of the tab list. Now, instead of truncating the name to make the tab smaller and draggable to the end of the tab list, we instead implement a custom collision detection algorithm to provide to dnd-kit, that will use the edge of the tab to determine collision, and thus allow the user to drag a tab with a long name to either end, without needing to truncate the name using the `isDragging` value. 

### How to verify

Follow repro steps from the issue using Firefox, confirm it no longer happens. Also confirm you can drag a tab with a long name to either end, and dragging tabs to re-order generally still works.

### Demo

https://github.com/user-attachments/assets/8ae41b56-42e2-40d0-96b5-e3df3d525731

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by EmmadUsmani** [comment]
* **#45682** <a href="https://app.graphite.dev/github/pr/metabase/metabase/45682?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @EmmadUsmani and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: e2e/support/helpers/e2e-dashboard-helpers.js [hunk 1]
```diff
@@ -114,9 +114,18 @@ export function saveDashboard({
   buttonLabel = "Save",
   editBarText = "You're editing this dashboard.",
   waitMs = 1,
+  awaitRequest = true,
 } = {}) {
+  cy.intercept("PUT", "/api/dashboard/*").as("saveDashboardCards");
   cy.button(buttonLabel).click();
-  cy.findByText(editBarText).should("not.exist");
+
+  if (awaitRequest) {
```
Comment (EmmadUsmani) [inline e2e/support/helpers/e2e-dashboard-helpers.js:122]: Some e2e tests may fail due to this change, I'll have to take a look at the failures then update them

**Review by alxnddr — APPROVED** [review]
