### PR TITLE
Fix: Command palette layout shift on open

### LINKED ISSUE #59112: Command palette layout shift on open
### Describe the bug

It's giving me a headache and I have to wait for it to load every time I want to use it.
It's not related to network requests, the layout shift is there regardless.

https://github.com/user-attachments/assets/cb09875a-8f28-47ac-bdf4-d0c45e701d3b

### To Reproduce

1. Open command palette

### Information about your Metabase installation

master, a6544c6cae3d72323748816c7ea5ea46bcf51fb1

### Severity

P2 annoying

### PR DESCRIPTION
**Pull request by bpander**
Closes https://github.com/metabase/metabase/issues/59112
Closes [UXW-295](https://linear.app/metabase/issue/UXW-295)

### Description

Fixes command palette layout shift by moving `useCommandPalette` to the always-mounted Palette component

### How to verify

1. Open the command palette (cmd+k)
2. Verify there's no layout shift
3. Verify no regressions, e.g.
  a. Recents refresh on open
  b. Search is debounced, doesn't use cached responses for previous search terms, and isn't called more than it needs to be
  c. Filters are retained in "View and filter ..." option when kbar-ing from /search
  d. Command palette is disabled in iframe/when logged out/when setting up
  e. Anything else you can think of

### Demo

https://github.com/user-attachments/assets/f11adda8-726b-45f6-8292-001373f15a7e

### Checklist

- [n/a] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/palette/components/PaletteResults.tsx [hunk 1]
```diff
@@ -1,13 +1,10 @@
-import type { Location } from "history";
```
Comment (bpander) [inline frontend/src/metabase/palette/components/PaletteResults.tsx:1]: ℹ️ This diff is mostly just prettier whitespace changes. The main change with this file is `useCommandPalette` was moved from here to Palette.tsx.

File: frontend/src/metabase/palette/hooks/useCommandPalette.tsx [hunk 2]
```diff
@@ -60,10 +63,10 @@ export const useCommandPalette = ({
 
   useDebounce(
     () => {
-      setDebouncedSearchText(trimmedQuery);
+      setDebouncedSearchText(isVisible ? trimmedQuery : "");
     },
-    SEARCH_DEBOUNCE_DURATION,
-    [trimmedQuery],
+    isVisible ? SEARCH_DEBOUNCE_DURATION : 0,
+    [trimmedQuery, isVisible],
```
Comment (bpander) [inline frontend/src/metabase/palette/hooks/useCommandPalette.tsx:69]: ℹ️ Open to suggestions here. These `useDebounce` changes are solely to make e2e tests pass. On `master`, when the menu is closed/reopened, this hook is re-mounted which resets the debounce/useSearchQuery. On _this_ branch, useCommandPalette stays mounted (that's howcome the shift is fixed). The runner goes so fast though, the 300ms debounce messed with the intercepts in some e2e tests. So `isVisible` is used here to do what remounting did (reset the debounce/useSearchQuery on close/reopen) to make the e2e tests pass.

**Review by iethree — APPROVED** [review]
nice!
