### PR TITLE
Fix binning - serialize clojure Ratios as doubles (#9228)

### LINKED ISSUE #9228: Metabase 0.31.x auto binning broken
In Metabase 0.31.2 create a query of a count of rows on the sample Reviews table grouped by a binned rating. Only 3 rows show up (1-1.5, 1.5-2, and 2-2.5). If you look at the raw data there are clearly values for numbers between 1-5.

image

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

### PR DESCRIPTION
**Pull request by MarkRx**
Fixes #9228

Clojure Ratio objects were being converted to "a/b" in SQL. This causes issues with order-of-operation sensitive queries such as x / a / b and is manifested by breaking binning when "nice ratios" are used.

@cgopalan and I couldn't figure out how to always wrap Ratio objects in parenthesis so instead we opted to convert them to doubles.

### CODE REVIEW

**Comment by camsaul** [comment]
This makes senes.

When were you seeing Ratios? AFAIK it's only for integer division (e.g. `(/ 1 2)`) that Clojure returns Ratios. I've been trying to avoid using integer division in the query processing code because when people do something like `1/2` they usually expect to see `0.5` instead of `0`.

File: src/metabase/util/honeysql_extensions.clj [hunk 1]
```diff
@@ -3,9 +3,11 @@
   (:require [clojure.string :as s]
             [honeysql
              [core :as hsql]
-             [format :as hformat]])
-  (:import honeysql.format.ToSql
-           java.util.Locale))
+             [format :as hformat]]
+            [metabase
+              [util :as u]])
```
Comment (camsaul) [inline src/metabase/util/honeysql_extensions.clj]: Instead of namespace prefixes you can do `[metabase.util :as u]` for a single namespace

**Comment by MarkRx** [comment]
It came from [nicer-bin-width](https://github.com/metabase/metabase/blob/master/src/metabase/query_processor/middleware/binning.clj#L98). The code seems to try to align bins and bounds to nicer numbers even if it means they are slightly skewed.

File: src/metabase/util/honeysql_extensions.clj [hunk 2]
```diff
@@ -64,6 +66,12 @@
   java.lang.Number
   (to-sql [x] (str x)))
 
+;; Ratios are represented as the division of two numbers which may cause order-of-operation issues when dealing with
+;; queries. The easiest way around this is to convert them to their decimal representations (with some rounding).
+(extend-protocol honeysql.format/ToSql
+  clojure.lang.Ratio
+  (to-sql [x] (str (u/round-to-decimals 5 x))))
```
Comment (camsaul) [inline src/metabase/util/honeysql_extensions.clj]: instead of rounding this you should just use `double` to convert it to a Double and then it will do the right thing.

e.g.

```clj
(to-sql [x] (double x))
```

Comment (MarkRx) [reply src/metabase/util/honeysql_extensions.clj]: I wasn't sure. I saw rounding elsewhere so I figured I would here. I can remove it.

As to casting to strings there was a comment above it that said Numbers needed to be treated as strings so I think as long as that comment still applies a string cast is necessary.
```
;; HoneySQL 0.7.0+ parameterizes numbers to fix issues with NaN and infinity -- see
;; https://github.com/jkk/honeysql/pull/122. However, this broke some of Metabase's behavior, specifically queries
;; with calculated columns with numeric literals -- some SQL databases can't recognize that a calculated field in a
;; SELECT clause and a GROUP BY clause is the same thing if the calculation involves parameters. Go ahead an use the
;; old behavior so we can keep our HoneySQL dependency up to date.
(extend-protocol honeysql.format/ToSql
  java.lang.Number
  (to-sql [x] (str x)))
```

Comment (camsaul) [reply src/metabase/util/honeysql_extensions.clj]: for example consider a Ratio like `(/ 1 1000000)`. 

```clj
(u/round-to-decimals 5 (/ 1 1000000)) ;; -> 0.0
(double (/ 1 1000000)) ;; -> 1.0E-6
```

If you round to 5 decimal places, your number is now zero! And that's usually  a good thing -- dividing by zero is frowned upon by most DBMSes.

Comment (camsaul) [reply src/metabase/util/honeysql_extensions.clj]: Right, we pass numbers in to SQL as literals instead of prepared statement args (e.g. `SELECT 1.5` instead of `SELECT ?`) because it breaks behavior with some DBs. But that's handled by the `to-sql` implementation for Number; you need not be concerned with that. Pass the Double to `to-sql` like in my example above and and then that implementation can convert it to a literal or not as needed

File: src/metabase/util/honeysql_extensions.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/util/honeysql_extensions.clj]: You actually don't need to import this ns at all because you don't need `u/round-to-decimals` as discussed below

File: src/metabase/util/honeysql_extensions.clj (hunk 2 above)
Comment (MarkRx) [reply src/metabase/util/honeysql_extensions.clj]: Ah I see. I wasn't sure if that other method would get called if I returned a double.

Comment (camsaul) [reply src/metabase/util/honeysql_extensions.clj]: Sorry, I think I typed my example above wrong. Do

```clj
(to-sql [x] (to-sql (double x)))
```

Comment (MarkRx) [reply src/metabase/util/honeysql_extensions.clj]: All set

**Comment by salsakran** [comment]
@MarkRx have you signed our CLA?

We can't accept any PRS (and will revert your previous PRs) if there isn't a CLA signature.

**Comment by MarkRx** [comment]
@salsakran according to my records legal corresponded with Metabase in December 2017 and the CLA was signed in behalf of the company (Paychex) by a director in March 2018. We contribute under the github handles @MarkRx and @cgopalan.
