### PR TITLE
Make SSO respect Metabase subpath

### LINKED ISSUE #28650: SSO does not respect Metabase subpath
Describe the bug
When Metabase is mounted on a subpath (e.g. https://example.org/metabase), and a user navigates to that address and signs in with SSO, they get redirected to the path relative to the root path.

For example, the user visits https://example.org/metabase/collections/10, gets redirected to https://example.org/metabase/auth/login?redirect=/collection/10, clicks "sign in", completes authentication against the identity provider and finally gets redirected to https://example.org/collections/10 instead of https://example.org/metabase/collections/10

Logs
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

To Reproduce

Configure Metabase Enteprise Edition on a subpath like /metabase
Setup SAML SSO
Login
Note that user gets redirected to root instead of subpath
Expected behavior
User should get redirected to /metabase.

Screenshots
n/a

Information about your Metabase Installation:
Latest Enterprise Edition: 1.35.3

Severity
Fairly critical - breaks Metabase login.
Workaround is to use some load balancer redirects, but not always feasible.

Additional context
n/a

### PR DESCRIPTION
**Pull request by qwef**
Closes https://github.com/metabase/metabase/issues/28650

### Description

Append site-url when redirect url for SSO has only the. relative path.

### How to verify

1. Reverse proxy + keycloak instance

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29570)

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj [hunk 1]
```diff
@@ -579,10 +581,33 @@
...
-                             (get-in response [:headers "Location"]))))))))))))))
+                 (fn []
+                   (let [req-options (saml-post-request-options (saml-test-response)
+                                                                (:RelayState params-map))
+                         response    (client-full-response :post 302 "/auth/sso" req-options)]
+                     (is (successful-login? response))
+                     (is (= redirect-url
+                            (get-in response [:headers "Location"])))))))))))
+
+
```
Comment (noahmoss) [inline enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj:592]: nit: don't need the extra line here

File: enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj [hunk 2]
```diff
@@ -579,10 +581,33 @@
...
+      (doseq [redirect-url ["/collection/root"
+                            "/test"
+                            "/"]]
+        (testing (format "\nredirect URL = %s" redirect-url)
+          (mt/with-temporary-setting-values [site-url "http://localhost:3001/path"]
```
Comment (noahmoss) [inline enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj:597]: I think this probably warrants its own top-level test. Otherwise it's not obvious that this is testing the specific case of `site-url` including a subpath. I'd split it out into its own test, give it a descriptive `testing` context string, and stick the issue # in it, like what's done on line 565.

I think you can also test the combination of `redirect-url` being a full URL and `site-url` including a subpath, for comprehensiveness.

**Review by noahmoss — CHANGES_REQUESTED** [review]
Fix looks good, just a small comment regarding the test

File: enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj (hunk 2 above)
Comment (qwef) [reply enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj:597]: Makes sense, think `relay-state-e2e-test` should cover `redirect-url` being a full URL.

**Review by noahmoss — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29570)* status: all files reviewed, 2 unresolved discussions (waiting on @qwef)
