### PR TITLE
Fix dashboard subscription sometimes shows empty result

### LINKED ISSUE #52467: Email Subscriptions show almost all charts with "No results" after auto update to Metabase 52.6
**Describe the bug**
We have daily email subscriptions that show charts of user signups, etc. They have worked consistently until this update, where now almost all of the charts show "no results". If you click on the dashboard from the email the charts work and data is there, so the issue is specifically with the email subscription. Nothing has changed in terms of amount of data on the dash or anything else.

**Logs**
Logs in metabase UI do not go back far enough (~6 hours) to show

**To Reproduce**
Not sure if it can be reproduced - set up a dash with simple queries, set up an email subscription, run before and after updating to newest Metabase version.

**Expected behavior**
Show charts with data like on dashboard

**Screenshots**

Image
Data shows in dashboard

**Severity**
We can live with this in the short term but it is making us consider alternatives to Metabase when auto-updates break something we look at daily

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "athena"
    ],
    "run-mode": "prod",
    "plan-alias": "starter",
    "version": {
      "date": "2025-01-15",
      "tag": "v1.52.6",
      "hash": "1a9cb72"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/52467

In https://github.com/metabase/metabase/pull/51708, we've changed it so that when sending dashboard subscription, we save the results to disk to reduce memory usage. 

The file we saved to disk has a default TIL of 5 minutes, after this the file will automatically get removed. This caused the bug because for big dashboard, it often takes > 5 minutes to finish the whole pipeline.

In hindsight this is a bad design, so I've changed it so that we cleaned it up manually.

### CODE REVIEW

File: src/metabase/notification/payload/temp_storage.clj [hunk 1]
```diff
@@ -56,24 +44,42 @@
...
+
+  clojure.lang.IDeref
+  (deref [_]
+    (if (.exists file)
+      (read-from-file file)
+      (throw (ex-info "File no longer exists" {:file file}))))
+
+  Object
+  (toString [_]
+    (str "#TempFileStorage{:file " file "}"))
```
Comment (piranha) [inline src/metabase/notification/payload/temp_storage.clj:64]: 💅

**Review by sansolovyov — APPROVED** [review]
