### PR TITLE
Fix athena sync 65728

### LINKED ISSUE #65728: Sync Fails to Identify Fields for Athena Table
### Describe the bug

Metabase fails to identify fields for Athena table in some cases.

### To Reproduce

Will share DDL in bug report channel in Slack.

### Expected behavior

_No response_

### Logs

[a8642d7e-a9ca-474b-95de-7e5d59355417] 2025-11-11T17:56:50-05:00 ERROR metabase.driver.athena Error retreiving fields for DB athena_test.location_like,com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate Object entries, at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 24],	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2672),	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:742),	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2429),	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:691),	at cheshire.parse$parse_STAR_.invokeStatic(parse.clj:65),	at cheshire.parse$parse_STAR_.invoke(parse.clj:63),	at cheshire.parse$parse.invokeStatic(parse.clj:100),	at cheshire.parse$parse.invoke(parse.clj:88),	at cheshire.core$parse_string.invokeStatic(core.clj:212),	at cheshire.core$parse_string.invoke(core.clj:198),	at cheshire.core$parse_string.invokeStatic(core.clj:209),	at cheshire.core$parse_string.invoke(core.clj:198),	at metabase.util.json$decode.invokeStatic(json.clj:79),	at metabase.util.json$decode.invoke(json.clj:75),	at metabase.util.json$decode.invokeStatic(json.clj:77),	at metabase.util.json$decode.invoke(json.clj:75),	at metabase.driver.athena.hive_parser$hive_schema__GT_map.invokeStatic(hive_parser.clj:59),	at metabase.driver.athena.hive_parser$hive_schema__GT_map.invoke(hive_parser.clj:56)

### Information about your Metabase installation

```JSON
v56.13
```

### Severity

blocking use of this table

### Additional context

[_No response_](https://metaboat.slack.com/archives/C05NXACAG1G/p1762901935706759)

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/65728

### Description

TLDR:
Disabling nested fields parsing since it's not actually supported (i.e. `:nested-fields` feature is already false)
Fixes `map<K,V>` parsing, which is technically useless given the above, but will enable proper nested-fields handling going forward. 

This was being caused by a few issues. First is that the JDBC driver only reports a struct type if we have a non-nested struct. Nested structs have their type reported as nil. This is why separating each column out into their own tables would sync successfully, because if the struct was nested we didn't actually take the nested path. The next issue was that we were only parsing out `map<string, string>` and not more generic `map<K, V>`. So a table with a non-nested struct column and a `map<K, V>` column would break the sync. The change in this PR is to properly parse out `map<K, V>`. With this done correctly we should be able to also parse out nested fields and support the `:nested-fields` feature. But since this is a P1 and that is a separate feature I've just disabled the nested field parsing for now which is still broken (issues separate of the `map<K, V>` parsing).

### How to verify

1. Create an athena table that has a column with a non-nested struct and a column of map<string, V> where V is not a string
2. Try to sync this table
3. It should only sync the top level columns and not the nested columns. 

### Demo

todo

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/athena/src/metabase/driver/athena/schema_parser.clj [hunk 1]
```diff
@@ -1,37 +1,37 @@
 (ns metabase.driver.athena.schema-parser
   (:require
+   #_[metabase.driver.athena.hive-parser :as athena.hive-parser]
```
Comment (bshepherdson) [inline modules/drivers/athena/src/metabase/driver/athena/schema_parser.clj:3]: Dead code here and below can go.

File: modules/drivers/athena/test/metabase/driver/athena_test.clj [hunk 2]
```diff
@@ -41,7 +41,7 @@
                {:name              "data"
                 :base-type         :type/Dictionary
                 :database-type     "struct"
-                :nested-fields     #{{:name "name", :base-type :type/Text, :database-type "string", :database-position 1}},
+                #_#_:nested-fields     #{{:name "name", :base-type :type/Text, :database-type "string", :database-position 1}},
```
Comment (bshepherdson) [inline modules/drivers/athena/test/metabase/driver/athena_test.clj:44]: Here too.

**Review by bshepherdson — APPROVED** [review]
