### PR TITLE
Fix Analytics DB Appearing in Permissions

### LINKED ISSUE #44856: Saving a Question based on a Question from "Metabase Analytics" makes Internal Database available in GUI
### Describe the bug

If you start from a question in the "Metabase Analytics" collection and save a copy of it anywhere you temporarily gain access to "Internal Metabase Database" in the native SQL editor and in "Admin -> Data -> Permissions".

### To Reproduce

1. Spin up an instance of v49
2. Go to "Metabase Analytics"
3. Open any Question in the collection
4. Save a copy to Metabase Analytics -> Custom Reports
5. Now create a SQL Question and note that you can see "Internal Metabase Database" as an option
6. Go to Admin -> Permissions -> Data and select a group; you can also see it there
7. Refresh the page and it's gone
8. Rinse / repeat

Loom recording:
https://www.loom.com/share/ce2a5512835e493db96789957abe1ddc

### Expected behavior

"Internal Metabase Database" shouldn't be visible in data permissions or accessible from the native editor

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "snowflake",
      "athena",
      "mysql",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-28",
      "tag": "v1.49.13",
      "hash": "de28e83"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

It's certainly confusing when it happens

### Additional context

I had v50.3 already up so I tested there, too, and I can partially reproduce. It shows up in "Permissions -> Data" but not the Native SQL Editor.

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/44856

### Description

Filters out analytics database(s) in permissions which uses legacy database fetching logic.

The easiest way to reproduce this is:
1. Navigate to any instance-analytics question
2. refresh the page
3. open admin/permissions settings, and you will see the audit db in the database list

Before | After
---|---
Screen Shot 2024-07-22 at 4 19 28 PM | Screen Shot 2024-07-22 at 4 20 26 PM
Screen Shot 2024-07-22 at 4 19 36 PM | Screen Shot 2024-07-22 at 4 20 21 PM

This has a pretty different fix in v49, where MLv2 isn't implemented as much yet. https://github.com/metabase/metabase/pull/45957

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/admin/permissions/selectors/data-permissions/data-sidebar.ts [hunk 1]
```diff
@@ -51,6 +53,7 @@ const getTableId = (id: string | number) => `table:${id}`;
 const getDatabasesSidebar = (metadata: Metadata): DataSidebarProps => {
   const entities = metadata
     .databasesList({ savedQuestions: false })
+    .filter(db => !PLUGIN_AUDIT.isAuditDb(db as DatabaseType))
```
Comment (iethree) [inline frontend/src/metabase/admin/permissions/selectors/data-permissions/data-sidebar.ts:56]: this isn't the _best_ way to handle this. `databasesList` is deprecated, and if we use the RTK query cache, it would just work correctly since the databases endpoint excludes the analytics DB. _However_ the permissions editor is generated by a whole bunch of selectors that would have to be completely refactored to be able to use RTK in a sane way.

**Review by rafpaf — APPROVED** [review]
