### PR TITLE
Fix field values re-rendering for virtual tables

### LINKED ISSUE #34414: User needs to refresh the page 3 times to get field values
### Describe the bug

Context: https://metaboat.slack.com/archives/C01LQQ2UW03/p1696357897768009

### To Reproduce

Reproduction steps in the Slack convo. Not posting here bc of private data.

### Expected behavior

User should get field values on the first time

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Stats
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/34414

### Description

Virtual tables have different keys in the store - `card__23:id`, our custom method of fetching field values utilizes Fields entity and updates store with the duplicated key (both `card__23:150` and `150` will present in the store).

So this PR removes this unnecessary duplication and updates field of the virtual table.  

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Create a model from Invoices table (new question -> Invoices -> convert into model)
2. new question -> from Model -> Invoices Model -> Filter -> Plan
3. click back from Plan (click on title with left arrow), then click Plan again -> values should be rendered (not only empty textarea)

### Demo

Before

https://github.com/metabase/metabase/assets/125459446/35a2c9f4-176d-4e52-b8e5-29c3e975446a

After

https://github.com/metabase/metabase/assets/125459446/bc20f06f-b5b2-429e-9995-894ab91a7b65

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/core/components/AccordionList/AccordionList.jsx [hunk 1]
```diff
@@ -353,7 +353,7 @@ export default class AccordionList extends Component {
 
     const searchRow = this.getRows().findIndex(row => row.type === "search");
 
-    if (searchRow >= 0) {
```
Comment (uladzimirdev) [inline frontend/src/metabase/core/components/AccordionList/AccordionList.jsx:356]: only virtualized list can scroll to row

File: frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx [hunk 2]
```diff
@@ -212,7 +212,12 @@ export function FieldValuesWidgetInner({
 
       const results = await Promise.all(
         nonVirtualFields.map(field =>
-          dispatch(Fields.objectActions.fetchFieldValues({ id: field.id })),
+          dispatch(
+            Fields.objectActions.fetchFieldValues({
+              id: field.id,
```
Comment (uladzimirdev) [inline frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx:217]: fetching is done by `id`

File: frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx [hunk 3]
```diff
@@ -222,7 +227,7 @@ export function FieldValuesWidgetInner({
         (field, index) =>
           results[index]?.payload?.values ??
           Fields.selectors.getFieldValues(results[index]?.payload, {
-            entityId: field.id,
+            entityId: field.getUniqueId(),
```
Comment (uladzimirdev) [inline frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx:230]: but store contains both `id` based and `uniqueId` based values:
- `id` is a number
- `uniqueId` is either `id` or a construction like `card__123:id`, so it's a UI specific id

File: e2e/test/scenarios/question/reproductions/34414-populate-field-values.cy.spec.js [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+
+      assertPlanFieldValues();
+    });
+  });
+});
+
+function assertPlanFieldValues() {
+  cy.contains("Basic");
+  cy.contains("Business");
+  cy.contains("Premium");
```
Comment (WiNloSt) [inline e2e/test/scenarios/question/reproductions/34414-populate-field-values.cy.spec.js:46]: Is there any reason you don't use a more standard assertion?

```suggestion
  cy.findByText("Basic").should("be.visible");
  cy.findByText("Business").should("be.visible");
  cy.findByText("Premium").should("be.visible");
```

**Review by WiNloSt — COMMENTED** [review]
Looks good to me, though I'll let Anton approve, since he's involved more in the conversation regarding this bug.

File: frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx [hunk 5]
```diff
@@ -103,6 +103,7 @@ describe("FieldValuesWidget", () => {
         });
         expect(fetchFieldValues).toHaveBeenCalledWith({
           id: PRODUCTS.CATEGORY,
+          table_id: field?.table_id,
```
[the remark this answers is not in the document]
Comment (uladzimirdev) [reply frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx:106]: me neither 😄

**Review by kulyk — COMMENTED** [review]
The overall approach looks solid 👍 I summarized the key suggestion in a [separate comment](https://github.com/metabase/metabase/pull/35014#issuecomment-1781410790). Here're a few more minor comments on e2e tests

File: e2e/test/scenarios/question/reproductions/34414-populate-field-values.cy.spec.js [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+    });
+
+    startNewQuestion();
+
+    popover().within(() => {
+      cy.findByText("Models").click();
+      cy.findByText("Invoices Model").click();
+    });
+
+    cy.findAllByTestId("notebook-cell-item").contains("Add filters").click();
```
[the remark this answers is not in the document]
Comment (uladzimirdev) [reply e2e/test/scenarios/question/reproductions/34414-populate-field-values.cy.spec.js:26]: it turned out, filter is not in the list of action-buttons as it's visible, so I have to select `notebook-cell-item`, it looks like there are other places with the same approach

image

**Comment by uladzimirdev** [comment]
https://www.loom.com/share/62bee0b28374425495054e04613a1fb1

@kulyk seems the requests are in order after applying your suggestions

File: frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (uladzimirdev) [reply frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx]: fixed

**Review by kulyk — APPROVED** [review]
Nicely done!
