### PR TITLE
Fix - Clicking Saved Questions option in data selector when instance have no questions leads to Raw Data option instead

### LINKED ISSUE #29760: Clicking Saved Questions option in data selector when instance have no questions leads to Raw Data option instead
**Describe the bug**
First, I think this bug rarely surfaces since it only appears when a Metabase instance doesn't have any saved questions, but have at least one model.

When that happens, if you try to create a new question, there'll be an option to select saved questions. After you click that it'll lead to Raw Data option instead (since there's no saved question at this point).

**To Reproduce**
Create a fresh Metabase instance.
1. Create a model
2. Click `+ New` -> `Question`
3. Click `Saved Question` option

**Expected behavior**
There is no **Saved Questions** option since there's no save question at this point.

**Screenshots/videos**
bug no question then click question picker

**Information about your Metabase Installation:**

Metabase version: 7837070b4000c73d213615f7ab58752761d0c6c0

<details>
<summary>Diagnostic Info</summary>

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-LTS",
    "java.vendor": "Azul Systems, Inc.",
    "java.vendor.url": "http://www.azul.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-LTS",
    "os.name": "Mac OS X",
    "os.version": "13.3",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-03-31",
      "src_hash": "7d4e7684afe846f84b911658485c6b803ca383aa",
      "tag": "v1.45.1-SNAPSHOT",
      "branch": "29267-preserve-dashboard-parameter-values-when-saving-dashboards",
      "hash": "8aa6f38"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
</details>

**Severity**
Minor, it just makes new users confused.

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #29760

### Description

There is partial duplication of this logic in `query_builder/components/DataSelector` & `containers/DataPicker`.
This PR tries to consolidate and reuse some of that logic from the latter in the former.

- Refactor `MetabaseSettings.get("enable-nested-queries")` in `DataSelector`
  - :warning: This affects how settings are mocked in tests, so if you try out the unit test that reproduces this on `master`, this test won't work as expected. The test marked with `(metabase#29760)` should correctly detect the reported issue.
- Refactor `getDataTypes` in `DataPicker/utils.ts`
  - move `DataTypeInfoItem` to `DataPicker/types.ts`
  - extract & move constants to `DataPicker/constants.ts`
  - improve test coverage
- Refactor `DataSelectorDataBucketPicker`
  - Move `DATA_BUCKET` to `metabase/containers/DataPicker`
  - Reuse `getDataTypes` from `metabase/containers/DataPicker`
  - Remove props spreading
  - Remove `Bucket` type in favor of `DataTypeInfoItem`
  - Fix typing of `onChangeDataBucket` prop
- Refactor `useDataPickerValue` to use named export

`query_builder/components/DataSelector` implementation is very complex and has lots of issues. I already found and reported 2 different ones while working on it:
- #32252
- #32225

### How to verify

0. Create a fresh Metabase instance.
1. Create a new model and save it
2. Click `+ New` -> `Question`

There should be no "Saved Questions" option visible in the popup.

#### Before

https://github.com/metabase/metabase/assets/6830683/886fd8f7-1902-4b66-b88b-fea67c9a197b

#### After

https://github.com/metabase/metabase/assets/6830683/ebef0ad3-63b0-4510-ba78-de149963e1be

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.tsx [hunk 1]
```diff
@@ -22,59 +23,71 @@ type Bucket = {
   icon: IconName;
   name: string;
   description: string;
-  onSelect: () => void;
 };
 
-const BUCKETS = [
-  {
+type ValueOf<T> = T[keyof T];
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.tsx:28]: Is there a place where such generic helpers can be defined?

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx [hunk 2]
```diff
@@ -662,6 +665,12 @@ export class UnconnectedDataSelector extends Component {
   async loadStepData(stepName) {
     const loadersForSteps = {
       // NOTE: make sure to return the action's resulting promise
+      [DATA_BUCKET_STEP]: () => {
+        return Promise.all([
+          this.props.fetchDatabases(this.props.databaseQuery),
+          this.props.fetchDatabases({ saved: true }),
+        ]);
+      },
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx:673]: After refactoring, [this test](https://github.com/metabase/metabase/blob/75b6d92/e2e/test/scenarios/question/notebook.cy.spec.js#L504-L517) started to fail, and these changes make it pass again.

**Review by deniskaber — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.unit.spec.tsx [hunk 3]
```diff
@@ -1,13 +1,40 @@
...
+      hasModels: true,
+      hasSavedQuestions: true,
+      hasNestedQueriesEnabled: true,
+    });
+    const { container } = setup(dataTypes);
 
     expect(screen.getByText("Models")).toBeInTheDocument();
     expect(screen.getByText("Raw Data")).toBeInTheDocument();
     expect(screen.getByText("Saved Questions")).toBeInTheDocument();
+    expect(container.childNodes[0].childNodes.length).toBe(dataTypes.length);
```
[the remark this answers is not in the document]
Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.unit.spec.tsx:28]: a59c949d023694a54a860e16cf5be45996307b5f
