### PR TITLE
Fix - Filtering the semantic types list is super annoying

### LINKED ISSUE #45409: Text cut off in FK target dropdown
### Describe the bug

image

### To Reproduce

1. Go to Admin -> Table Metadata -> Sample Database -> Orders
2. Click on "Products -> ID" in `PRODUCT_ID` section
3. Dropdown opens
4. Scroll down in the dropdown to see currently selected option

Notice that currently selected option covers the previous option, and last option is cut off.
note: things work fine if dropdown is opened again.

### Information about your Metabase installation

master, 359ae5804d

### Severity

P3

### LINKED ISSUE #53595: Filtering the semantic types list is super annoying
### Describe the bug

Whenever choosing a semantic type and attempting at filtering the list, the dropdown is cropped too much, making the list barely usable, except using keyboard.

Here's a capture of the problem in action:
Image

While not the end of the world, if you're in the process of heavily editing metadata, this is driving me borderline crazy.

### To Reproduce

1. Go to any place you can edit a field's metadata
2. Open the semantic type selector
3. Type in something to filter down the list, like "c"
4. See isse

### Expected behavior

Keep the dropdown sized correctly

### Logs

_No response_

### Information about your Metabase installation

```JSON
stats
```

### Severity

can live with it... until not

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #53595
Fixes #45409

### Description

Replaces 4 instances of legacy `Select` component with the one from Mantine, and also 1 instance of legacy `Button` component. All 5 in Admin > Table Metadata.

No repro for #45409 since it's a specific, hard-to-test visual issue.

Mantine issue found while working on this: https://github.com/mantinedev/mantine/issues/7583.

Related [Slack conversation](https://metaboat.slack.com/archives/C08E17FN206/p1741686034501049?thread_ts=1741685285.213999&cid=C08E17FN206).

### How to verify

1. Go to Admin > Table Metadata
2. Play around with these 4 dropdowns:
    - visibility type picker
    - semantic type picker
    - currency picker (shown when semantic type is set to currency)
    - target FK picker (shown when semantic type is set to foreign key)

### Demo

Video comparing previous implementation with the new one: https://metaboat.slack.com/archives/C08E17FN206/p1741785246367739?thread_ts=1741685285.213999&cid=C08E17FN206

image

### CODE REVIEW

File: frontend/src/metabase/admin/datamodel/metadata/components/SemanticTypeAndTargetPicker/FkTargetPicker/FkTargetPicker.tsx [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+  idFields,
+  value,
+  onChange,
+}: Props) => {
+  const comparableIdFields = idFields.filter((idField: Field) => {
+    return field.isComparableWith(idField);
+  });
+  const hasIdFields = comparableIdFields.length > 0;
+  const includeSchema = hasMultipleSchemas(comparableIdFields);
+  const data = getData(comparableIdFields, includeSchema);
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/datamodel/metadata/components/SemanticTypeAndTargetPicker/FkTargetPicker/FkTargetPicker.tsx:29]: This code is just moved

File: frontend/src/metabase/ui/components/inputs/Combobox/Combobox.config.ts [hunk 2]
```diff
@@ -0,0 +1,9 @@
+import { Combobox, type MantineThemeOverride } from "@mantine/core";
+
+export const comboboxOverrides: MantineThemeOverride["components"] = {
```
Comment (kamilmielnik) [inline frontend/src/metabase/ui/components/inputs/Combobox/Combobox.config.ts:3]: The only reason I'm adding `Combobox` is to use `Combobox.Chevron` which is used by default in `Select`.
`Combobox.Chevron` is needed to customize `CurrencyPicker`.

File: frontend/src/metabase/ui/components/inputs/Select/SelectItem/SelectItem.module.css [hunk 3]
```diff
@@ -1,7 +1,7 @@
 .item {
   cursor: pointer;
   border-radius: 6px;
-  word-break: break-all;
+  overflow-wrap: break-word;
```
Comment (kamilmielnik) [inline frontend/src/metabase/ui/components/inputs/Select/SelectItem/SelectItem.module.css:4]: Words would be broken in random places.

File: frontend/src/metabase/ui/components/inputs/Select/SelectItem/SelectItem.tsx [hunk 4]
```diff
@@ -44,11 +36,6 @@ export const SelectItem = forwardRef(function SelectItem(
       flex={1}
       aria-selected={selected}
       {...props}
-    >
-      {icon && <Icon name={icon} />}
-      <Text c="inherit" lh="inherit">
-        {label}
-      </Text>
-    </Group>
+    />
```
Comment (kamilmielnik) [inline frontend/src/metabase/ui/components/inputs/Select/SelectItem/SelectItem.tsx:39]: For the purpose of full customization, `SelectItem` is now the one where you need to provide `children`.
`DefaultSelectItem` is the one that accepts `icon` and `label` props.

File: frontend/src/metabase/ui/components/inputs/Select/Select.module.css [hunk 5]
```diff
@@ -124,7 +124,7 @@
       content: "";
       display: block;
       margin-top: calc(var(--mantine-spacing-sm) - 1px);
-      margin-bottom: var(--mantine-spacing-xs);
+      margin-bottom: var(--mantine-spacing-sm);
```
Comment (kamilmielnik) [inline frontend/src/metabase/ui/components/inputs/Select/Select.module.css:127]: Feedback from Maz: https://metaboat.slack.com/archives/C08E17FN206/p1741818530661099?thread_ts=1741685285.213999&cid=C08E17FN206

File: frontend/src/metabase/lib/core.ts [hunk 6]
```diff
@@ -1,8 +1,17 @@
...
-export const field_semantic_types = [
+interface FieldSemanticType {
+  id: string;
+  name: string;
+  section: string;
+  description?: string;
+  icon: IconName;
+}
+
+export const FIELD_SEMANTIC_TYPES: FieldSemanticType[] = [
```
Comment (kamilmielnik) [inline frontend/src/metabase/lib/core.ts:14]: I converted this file to TS and renamed the constants to match our convention

**Review by ranquild — COMMENTED** [review]
@kamilmielnik you can get rid of all style overrides.

for `width`, use `comboboxProps`:
```
comboboxProps={{
  width: 300,
  position: "bottom-start",
}}
```

for color:
```
{option?.description && (
                <Text
                  c={
                    selected
                      ? "var(--mb-color-text-selected)"
                      : "var(--mb-color-text-tertiary)"
                  }
                  lh="1rem"
                >
                  {option.description}
                </Text>
              )}
```

File: frontend/test/__support__/mocks.js [hunk 7]
```diff
@@ -6,6 +6,8 @@ global.window.matchMedia = () => ({
   removeEventListener: () => {},
 });
 
+HTMLElement.prototype.scrollIntoView = () => {}; // used under the hood in Mantine's Select component
```
Comment (npfitz) [inline frontend/test/__support__/mocks.js:9]: Doesn't need to happen in this PR, but we do have a `mockScrollIntoView` function in `_support_/ui.tsx`. Maybe we should just have it mocked by default in unit tests since so many Mantine components expect it to be there now.

**Review by npfitz — COMMENTED** [review]
Looks good from my perspective! Happy to see us moving away from the old select component

File: frontend/test/__support__/mocks.js (hunk 7 above)
Comment (kamilmielnik) [reply frontend/test/__support__/mocks.js:9]: > Maybe we should just have it mocked by default in unit tests since so many Mantine components expect it to be there now.

Good idea, I'll submit a follow-up PR :+1:

**Comment by kamilmielnik** [comment]
> @kamilmielnik you can get rid of all style overrides.

> for width, use comboboxProps:

Done: cff1e6a0f0adbbd56ddc765d2cea75441c6d92f

> for color:

@ranquild this does not work when navigating Select options with up/down arrow keys - in this case highlighted option has the same styling as selected option: https://github.com/metabase/metabase/blob/32118e35657456393afe0d503a5d372d9d98185a/frontend/src/metabase/ui/components/inputs/Select/SelectItem/SelectItem.module.css#L11-L14

**Review by npfitz — APPROVED** [review]
Pulled this down and played with it yesterday. Great work Kamil! 🔥
