### PR TITLE
When MB_ENABLE_EMBEDDING is set show correct embedding settings UI

### LINKED ISSUE #13166: Environment variable MB_ENABLE_EMBEDDING=true makes Admin > Embedding subpage not function
**Describe the bug**
When setting environment variable [MB_ENABLE_EMBEDDING](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_enable_embedding)=`true`, then it looks Embedding isn't enabled.

Workaround is to not use environment variable, but enable embedding through the API with the key `enable-embedding`:
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#put-apisettingkey

**To Reproduce**
1. Start Metabase with `MB_ENABLE_EMBEDDING=true`
2. Go to Admin > Settings > Embedding in other Applications
image
3. Shows as if Embedding is not enabled, but it is - and clicking "Enable" button does not change anything.

**Expected behavior**
To show the Embedding page as if it was enabled, so it's possible to view/edit secret, and see which dashboard and questions are currently available through embedding.
image

**Information about your Metabase Installation:**
Metabase 1.36.4 and 0.36.4

**Additional context**
Related to #13160 and #12272

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/13166

## Changes

When MB_ENABLE_EMBEDDING is set show correct embedding settings UI:
- show proper state `enabled/disabled`
- disable controls and show that the value comes from the env variable

## How to verify

- Check the original issue repro steps

Screenshot 2022-04-30 at 03 00 21

### CODE REVIEW

File: frontend/src/metabase/admin/settings/components/widgets/EmbeddingLegalese.jsx [hunk 1]
```diff
@@ -21,18 +23,25 @@ const EmbeddingLegalese = ({ onChange }) => (
...
-          onChange(true);
-        }}
+      <Tooltip
+        tooltip={setting.placeholder}
+        isEnabled={setting.is_env_setting}
+        maxWidth={300}
       >
-        {t`Enable`}
-      </button>
+        <span>
```
Comment (ranquild) [inline frontend/src/metabase/admin/settings/components/widgets/EmbeddingLegalese.jsx:31]: Do we need a `span` here? `Button` should correctly forward refs

**Review by ranquild — APPROVED** [review]
