### PR TITLE
Convert nulls to "(empty)" in row charts and line area bar charts

### LINKED ISSUE #10580: Row Chart Displaying Incorrect Data
**Describe the bug**
The Row Chart is displaying incorrect data. The correct labels are shown, but with the wrong count value.

**Logs**
No errors found in javascript console

**To Reproduce**
We have a question with the following data:
image

When we visualize it as a Row Chart, the labels have different count values:
image

**Expected behavior**
The Bar visualization works. I would expect the Row Chart to have the same values as the bar chart: 
image

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 76
- Your operating system: OSX 10.14.5
- Your databases: Redshift
- Metabase version: v0.32.10
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

Annoying

Note: the more honest and specific you are here the more we will take you seriously. 

**Additional context**

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #10580

Crossfilter doesn't allow null, undefined, or NaN in dimensions. The nulls were getting merged and summed with adjacent rows.

The fix is to explicitly convert nulls to "null". A side effect is that this will merge actual nulls with the string "null" if that distinction matters in a report. Though, that use case was already broken so I'm not particularly worried about it.

This `null` => `"null"` conversion already happens in LineAreaBarCharts [here](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js#L106).

### CODE REVIEW

**Comment by tlrobinson** [comment]
@kdoh @mazameli @salsakran Is `null` a word we want to expose to end users?

**Comment by salsakran** [comment]
Hmmmm .... what are alternatives? Is an empty space reasonable here?

**Comment by paulrosenzweig** [comment]
I think an empty space is good here too. Or, maybe something like "[Blank Field]".

For this PR, I wanted to match what we do for LineAreaBar. (see below) That wasn't picked intentionally though. It's just a result of `String(null)`.
image

**Comment by mazameli** [comment]
Maybe `(empty)` ?

**Comment by paulrosenzweig** [comment]
I just updated this and LineAreaBar to show "(empty)" instead.

File: frontend/src/metabase/visualizations/lib/RowRenderer.js [hunk 1]
```diff
@@ -25,16 +25,20 @@ export default function rowRenderer(
   // disable clicks
   chart.onClick = () => {};
 
-  const formatDimension = row =>
-    formatValue(row[0], { column: cols[0], type: "axis" });
+  const formatDimension = v =>
+    formatValue(v, { column: cols[0], type: "axis" });
```
Comment (tlrobinson) [inline frontend/src/metabase/visualizations/lib/RowRenderer.js]: FWIW I think my reasoning for passing `row` here was that `formatDimension` references `cols[0]` anyway. 

Maybe `formatCell(row, 0)` would have been better, but not important.

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js [hunk 2]
```diff
@@ -103,6 +103,8 @@ function getDatas({ settings, series }, warn) {
           ? HACK_parseTimestamp(row[0], s.data.cols[0].unit, warn)
           : isDimensionNumeric(series)
           ? row[0]
+          : row[0] === null
+          ? "(empty)"
```
Comment (tlrobinson) [inline frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js]: I think it would be good to pull `"(empty)"` into a `const` somewhere, maybe a `visualizations/lib/format` file.

I was also wondering if we should use a magic string that's very unlikely to appear in the data (`__METABASE_NULL__` or something), but `(empty)` is probably already rare enough.

Comment (walterl) [reply frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js]: Remember to also mark it as translatable :slightly_smiling_face:

File: frontend/test/metabase/visualizations/components/RowRenderer.unit.spec.js [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+  it("should render", () => {
+    renderChart(rowRenderer, element, [
+      {
+        card: { display: "row", visualization_settings: {} },
+        data: { cols: [StringColumn(), NumberColumn()], rows: [["a", 1]] },
+      },
+    ]);
+  });
+
+  it('should render null as "null"', () => {
```
Comment (walterl) [inline frontend/test/metabase/visualizations/components/RowRenderer.unit.spec.js]: You meant 'null as *"(empty)"*', right?

**Review by walterl — COMMENTED** [review]
@paulrosenzweig I'm not sure if it has come up in the discussion of this issue at all, but should other falsey values (empty string, `undefined`, others?) not also be rendered as `NULL_DISPLAY_VALUE`?

**Review by walterl — APPROVED** [review]
