### PR TITLE
fix trend lines scaling

### LINKED ISSUE #47351: Trend Lines are incorrect when a multiplier is in use
### Describe the bug

Trend lines are incorrectly displayed when the Y-axis multiplier is in use.

### To Reproduce

1. Create a question: Sample database, Sum of Total, by Created At: Month
2. In Data / Y-axis: set multiplier to 0.001
image
3. In  options, enable trend line
image
4.(!) See the error that the trend line does not honor the multiplier
image

### Expected behavior

It should work as before.

### Logs

_No response_

### Information about your Metabase installation

```JSON
1.50.22
```

### Severity

P1 - regression / correctness, reported by a customer.

### Additional context

Working fine in `1.49.x`.

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/47351

### Description

Introduced in https://github.com/metabase/metabase/pull/43668. The scaling formatting setting implementation has changed significantly in the PR and updating trend lines to support it got missing.

This PR scales the trend lines dataset to match the original scaled dataset when scaling settings are applied.

### How to verify

- New -> Orders: Count group by Created At -> make it a line chart
- Enable trend lines
- Go to the "Data" tab, under "Y-axis" section open the formatting settings for "Count"
- Set "Multiply by a number" to 0.01 
- Ensure the trend line appears correctly

### Demo

Before
Screenshot 2024-08-28 at 1 38 17 PM

After
Screenshot 2024-08-28 at 1 38 01 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/cartesian/model/trend-line.ts [hunk 1]
```diff
@@ -59,7 +60,7 @@ const getSeriesModelsWithTrends = (
         return null;
       }
 
-      const trendFunction = getTrendLineFunction(insight);
+      const trendFunction = getTrendLineFunction(insight); // add a multiplier here
```
Comment (EmmadUsmani) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/trend-line.ts:63]: Do we still need the comment?

**Review by EmmadUsmani — APPROVED** [review]

File: frontend/src/metabase/visualizations/echarts/cartesian/model/trend-line.ts (hunk 1 above)
Comment (alxnddr) [reply frontend/src/metabase/visualizations/echarts/cartesian/model/trend-line.ts:63]: I left it for myself and forgot to remove 😄 Thanks for catching
