### PR TITLE
Fix empty pivot cell misalignment

### LINKED ISSUE #14243: Pivot tables are missing cells when there aren't records(?)
On master, it appears that in [a query like this one](http://localhost:3000/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjIsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdLFsic3VtIixbImZpZWxkLWlkIiwxNF1dXSwiYnJlYWtvdXQiOltbImRhdGV0aW1lLWZpZWxkIixbImZpZWxkLWlkIiwxMl0sInllYXIiXSxbImZrLT4iLFsiZmllbGQtaWQiLDExXSxbImZpZWxkLWlkIiwyNV1dLFsiZmstPiIsWyJmaWVsZC1pZCIsMTFdLFsiZmllbGQtaWQiLDI2XV1dfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJwaXZvdCIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJwaXZvdF90YWJsZS5jb2x1bW5fc3BsaXQiOnsicm93cyI6W1siZGF0ZXRpbWUtZmllbGQiLFsiZmllbGQtaWQiLDEyXSwieWVhciJdLFsiZmstPiIsWyJmaWVsZC1pZCIsMTFdLFsiZmllbGQtaWQiLDI1XV1dLCJjb2x1bW5zIjpbWyJmay0-IixbImZpZWxkLWlkIiwxMV0sWyJmaWVsZC1pZCIsMjZdXV0sInZhbHVlcyI6W1siYWdncmVnYXRpb24iLDBdLFsiYWdncmVnYXRpb24iLDFdXX19fQ==), there must be some states with no orders, which is causing empty cells, which in turn is resulting in misaligned subtotal rows:

image

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #14243 

I was a bit overzealous simplifying in #14222. I dropped some fixed heights that were needed with empty cells.

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/PivotTable.jsx [hunk 1]
```diff
@@ -168,7 +168,7 @@ export default class PivotTable extends Component {
       leftIndex.length === 0
         ? 0
         : LEFT_HEADER_LEFT_SPACING +
-          leftIndex[0].length * LEFT_HEADER_CELL_WIDTH;
+          leftIndex[0][0].length * LEFT_HEADER_CELL_WIDTH;
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/visualizations/PivotTable.jsx:171]: This change is unrelated to the fixed heights but was another bug introduced in #14222. The `leftIndex` structure changed to accommodate including the subtotal rows.

**Review by ariya — APPROVED** [review]
