### PR TITLE
Round small y-axis values to zero with no min/max difference on the Y scale

### LINKED ISSUE #32815: Zero on axis not rounded, has many decimal places with single-row chart
### Describe the bug

Zero value on axis is not rounded as expected

### To Reproduce

1. Create a new Native SQL question
```sql
WITH base_query AS (
SELECT '2023-06-01' AS time_value, 'Under Benchmark' AS relative_status, -0.0094 AS special_clients
)

SELECT * FROM base_query
```

2. Select a bar chart visualization type
3. See the issue, zero on axis not visible, instead showing near-zero value
image

### Expected behavior

- expect value on axis to be rounded to zero

### Logs

_No response_

### Information about your Metabase installation

```JSON
- v1.46.6.4 and `master` as of `c8afac24`
```

### Severity

P3: makes chart look unpolished

### Additional context

related to:
- https://github.com/metabase/metabase/issues/9986
- https://github.com/metabase/metabase/issues/10062

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/32815

### Problem

This bug manifested only on charts where there was a single value. In those cases, there was an edge case where our existing round-to-zero logic would get bypassed.

On master, a bar chart with a single value shows the error, but multiple values do not:

<table>
<thead>
<tr><td>query</td><td>chart</td></tr>
</thead>
<tbody>

<tr>
  <td>
<pre>
SELECT 'a' as label, -0.0094 AS val
UNION ALL 
SELECT 'b' as label, -0.0094 AS val
</pre>
</td>
<td>
  
</td>
</tr>
<tr>
  <td>
<pre>
SELECT 'a' as label, -0.0094 AS val
UNION ALL 
SELECT 'b' as label, -0.0095 AS val
</pre>
</td>
<td>
  
</td>
</tr>
</tbody>
</table>

### Solution

If a chart has no difference between the min and max values, for rounding purposes, we treat it as if the min/max difference is 1.

Screen Shot 2023-08-14 at 2 47 19 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by EmmadUsmani — APPROVED** [review]

File: frontend/src/metabase/visualizations/lib/apply_axis.js [hunk 1]
```diff
@@ -490,7 +493,8 @@ export function getYValueFormatter(chart, series, yExtent) {
     const metricColumn = series[seriesIndex].data.cols[1];
     const columnSettings = chart.settings.column(metricColumn);
     const columnExtent = options.extent ?? yExtent;
-    const roundedValue = maybeRoundValueToZero(value, columnExtent);
+    const roundedValue =
+      value === null ? "" : maybeRoundValueToZero(value, columnExtent);
```
Comment (iethree) [inline frontend/src/metabase/visualizations/lib/apply_axis.js:497]: This was necessary to preserve the behavior where nulls display as empty strings.

https://www.deploysentinel.com/ci/runs/64da9f82c4985efd77cda2b9
