### PR TITLE
Angular Apocalypse

### LINKED ISSUE #2871: Dashboards don't show up after creating them until you refresh the page
If this is a bug report, please fill in the blanks:
-  I am using the Chrome browser.
-  My computer's OS is OS X
-  I'm running Metabase locally via `lein ring server`
-  My database is H2 Sample Dataset
-  My Metabase version is 0.19.0-SNAPSHOT

Basically the dashboards dropdown doesn't update until you refresh the page.
1.  Have no dashboards
2.  Create a new dashboard
3.  Dashboard doesn't show up in menu

screen shot 2016-07-01 at 6 22 15 pm

### PR DESCRIPTION
**Pull request by tlrobinson**
TODO:
- [x] Move Navbar into main React app
- [x] Replace Angular routing + AppState etc with `react-router, react-redux-router, redux-auth-wrapper` etc
- [x] replace all instances of `state.router` / `getState().router`
- [x] replace all instances of `onChangeLocation` with `push`
- [x] replace `<a>`s with `<Link>`s
- [x] replace updateUrl in query builder
- [x] replace 401/403 handler
- [x] replace GA enable/disable
- [x] ensure all auth modes work
- [x] ensure analytics click listener works

KNOWN ISSUES:
- [x] Query builder forward/back doesn't work due to react-router mucking with popstate/history.state
- [x] `<Links>` in popovers/modals don't work due to missing router context
- [x] Parameter widgets broken on dashboards
- [x] Popovers hidden behind modals
- [x] Popover and modal closing at same time

Resolves #2871  and probably a bunch of other stuff.

### CODE REVIEW

**Comment by mazameli** [comment]
Chart setting dropdowns and color picker don't seem to be working in the modal, e.g. selecting x/y-axis columns.

**Comment by tlrobinson** [comment]
This should be ready to go. Anyone want to review it?

**Comment by kdoh** [comment]
I'm down to take a look.

**Comment by lewisl9029** [comment]
Sure I'll take a look too.

File: frontend/src/metabase/App.jsx [hunk 1]
```diff
@@ -0,0 +1,15 @@
+import React, { Component, PropTypes } from "react";
+
+import Navbar from "metabase/nav/containers/Navbar.jsx";
+
+export default class App extends Component {
```
Comment (lewisl9029) [inline frontend/src/metabase/App.jsx]: Any reason why this couldn't be a stateless component?

File: frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx [hunk 2]
```diff
@@ -17,15 +18,14 @@ import * as databaseActions from "../database";
...
         database:         getEditingDatabase(state),
-        formState:        getFormState(state),
-        onChangeLocation: props.onChangeLocation
+        formState:        getFormState(state)
     }
 }
 
 const mapDispatchToProps = {
-    ...databaseActions
+    ...databaseActions,
```
Comment (lewisl9029) [inline frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx]: Missed a trailing comma here. 

Although I'm actually partial to the idea of keeping trailing comma's when args are vertically aligned like this, but either way we should apply it consistently.

File: frontend/src/metabase/admin/datamodel/selectors.js [hunk 3]
```diff
@@ -3,17 +3,17 @@ import { createSelector } from 'reselect';
 import { computeMetadataStrength } from "metabase/lib/schema_metadata";
 
 
-const segmentsSelector         = state => state.datamodel.segments;
-const metricsSelector          = state => state.datamodel.metrics;
+const segmentsSelector         = (state, props) => state.datamodel.segments;
```
Comment (lewisl9029) [inline frontend/src/metabase/admin/datamodel/selectors.js]: Hmm... adding props to every selector whether or not it's using props just for the sake of consistency seems a bit excessive. Is there some other reason for doing this that I'm missing? 

Don't feel too strongly either way though, so feel free to keep it this way if you disagree. Changing everything back might be a bit of a pain.

File: frontend/src/metabase/App.jsx (hunk 1 above)
Comment (tlrobinson) [inline frontend/src/metabase/App.jsx]: At one point I was using the lifecycle methods. It's moderately likely we might need to in the future, and there's only one instance of this so memory consumption isn't a concern, so I'll probably leave it as-is for now.

File: frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx (hunk 2 above)
Comment (tlrobinson) [inline frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx]: Yeah it's pretty inconsistent all over the app, so don't worry about this stuff for now unless we've already established a preference.

Comment (tlrobinson) [inline frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx]: http://eslint.org/docs/rules/comma-dangle

File: frontend/src/metabase/admin/datamodel/selectors.js (hunk 3 above)
Comment (tlrobinson) [inline frontend/src/metabase/admin/datamodel/selectors.js]: Possibly overkill, but pretty harmless, and it was getting annoying trying to track down which ones needed `props`, especially in `mapStateToProps`. I suppose it's not at all necessary for the "leaf" selectors though.

Comment (lewisl9029) [inline frontend/src/metabase/admin/datamodel/selectors.js]: I see that makes sense then. 

Although I think this might be a good use case for rest params and then destructuring into the selector args if we ever want to refactor this. I've never actually used it before though so not sure if there might be complications.

File: frontend/src/metabase/admin/settings/selectors.js [hunk 4]
```diff
@@ -149,6 +150,9 @@ const SECTIONS = [
         ]
     }
 ];
+for (const section of SECTIONS) {
```
Comment (lewisl9029) [inline frontend/src/metabase/admin/settings/selectors.js]: The functional nazi in me wants to suggest declaring a separate `RAW_SECTIONS` constant and then map & i.assoc on that to build `SECTIONS`, but feel free to ignore him. =P

File: frontend/src/metabase/admin/settings/selectors.js [hunk 5]
```diff
@@ -183,14 +187,14 @@ export const getSections = createSelector(
...
+export const getActiveSectionName = (state, props) => props.params.section
 
 export const getActiveSection = createSelector(
     getActiveSectionName,
     getSections,
-    (section = "Setup", sections) => {
+    (section = "setup", sections) => {
         if (sections) {
-            return _.findWhere(sections, {name: section});
+            return _.findWhere(sections, { slug: section });
```
Comment (lewisl9029) [inline frontend/src/metabase/admin/settings/selectors.js]: I usually prefer to build a map keyed on `slug` and use that whenever I find myself having to use find like this, but probably not be worth the risk and effort to refactor something that already works in this particular case.

File: frontend/src/metabase/components/OnClickOutsideWrapper.jsx [hunk 6]
```diff
@@ -39,11 +39,14 @@ export default class OnClickOutsideWrapper extends Component {
...
-        var index = popoverStack.indexOf(this);
-        if (index >= 0) {
-            popoverStack.splice(index, 1);
-        }
+        // remove from the stack after a delay, if it is removed through some other
+        // means this will happen too early causing parent modal to close
+        setTimeout(() => {
+            var index = popoverStack.indexOf(this);
+            if (index >= 0) {
+                popoverStack.splice(index, 1);
```
Comment (lewisl9029) [inline frontend/src/metabase/components/OnClickOutsideWrapper.jsx]: Saw this code just now. It's great that it works, but we might want to add a TODO to eventually consider refactoring `popoverStack` into a prop passed down from a reducer somewhere. It just seems really hacky to have a component depend on a random floating variable that doesn't even live in any component internal state, let alone in any reducers. Feels like this could become problematic if we want to make use of some of the nicer tooling available for redux later down the line.

File: frontend/src/metabase/query_builder/actions.js [hunk 7]
```diff
@@ -20,11 +21,81 @@ import { getParameters } from "./selectors";
...
+                dispatch(setCardAndRun(location.state.card, false));
+                dispatch(setCurrentState(location.state));
+            } else {
+                console.log("QB SKIP POP")
+            }
+        }
+    }
+);
+
+function updateUrl(dispatch, getState, card, isDirty=false, replaceState=false) {
```
Comment (lewisl9029) [inline frontend/src/metabase/query_builder/actions.js]: Hmm... couldn't we make this an actual action? So we can dispatch it and have access to dispatch and getState without having to pass it in? The other args can just be part of the payload right?

**Comment by lewisl9029** [comment]
Looks great to me (LGTM!) asides from the very small nitpicks I noted above.

It was a beautiful thing to finally see some of the last remaining angular code getting nuked from orbit. Awesome work @tlrobinson. =)

File: frontend/src/metabase/components/OnClickOutsideWrapper.jsx (hunk 6 above)
Comment (tlrobinson) [inline frontend/src/metabase/components/OnClickOutsideWrapper.jsx]: That's a possibility, but I don't think pure UI component state really needs to go in the Redux store. The one disadvantage is in certain cases Redux "time travel" etc won't work correctly, but we have *tons* of component state for things that actually definitely should be in the Redux store, not to mention our over-usage of thunk actions, so time travel is a long ways off from actually working in Metabase anyways.

File: frontend/src/metabase/admin/settings/selectors.js (hunk 5 above)
Comment (tlrobinson) [inline frontend/src/metabase/admin/settings/selectors.js]: In general I don't worry too much about `O(n)` operations if I know `n` is less than some reasonably small number (like 6 sections or whatever we have)

File: frontend/src/metabase/query_builder/actions.js (hunk 7 above)
Comment (tlrobinson) [inline frontend/src/metabase/query_builder/actions.js]: Yeah that's a good point, I'll give it a try.

**Comment by lewisl9029** [comment]
New changes look great. Let's get this merged (LGTM!) if nobody else has any objections.

**Comment by tlrobinson** [comment]
@kdoh did you still want to take a look at this?

**Comment by kdoh** [comment]
LGTM
