### PR TITLE
[Metrics V2] Metrics with filters on implicitly joined columns produce query error when added in a Summarize block

### LINKED ISSUE #43943: Metrics with filters on implicitly joined columns produce query error when added in a Summarize block
### Describe the bug

If a metric definition includes a filter for an implicitly joined column, when added in a Summarize block, the metric breaks the query with an error

### To Reproduce

1. New metric
2. Select Orders in data picker
3. Add filter Product -> Category is Gadget
4. Summarize Count by Created At: Month
5. Save
6. New question
7. Select Orders in data picker
8. Choose your saved metric from the Common metrics
9. Hit Visualize
10. See error `Cannot determine the source table or query for Field clause [:field 16 {:base-type :type/Text, :source-field 10, :join-alias "PRODUCTS__via__PRODUCT_ID", :metabase.query-processor.middleware.escape-join-aliases/join-alias nil}]`

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

breaks one of use cases

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snoe**
Fixes #43943

### CODE REVIEW

File: test/metabase/query_processor/middleware/metrics_test.clj [hunk 1]
```diff
@@ -89,6 +89,44 @@
                      :aggregation [[:+ {} [:avg {} [:field {} (meta/id :products :rating)]] 1]]}]}
           (adjust query)))))
 
+(deftest ^:parallel metric-with-implicit-join-test
+  (testing "Metrics with filters on implicitly joined columns produce query error when added in a Summarize block #43943"
```
Comment (metamben) [inline test/metabase/query_processor/middleware/metrics_test.clj:93]: Usually, we describe the desired behavior not the error we are fixing, I think.

**Review by metamben — APPROVED** [review]
