### PR TITLE
Pre-36 snippet updates

### LINKED ISSUE #8773: Should we hide the SQL editor entirely if you don't have write-SQL permission?
This goes way back to issue https://github.com/metabase/metabase/issues/1689, and has also been [discussed on Discourse](http://discourse.metabase.com/t/remove-or-permanently-hide-sql-query-string-on-questions-written-in-sql/2376). 

Now that we have collection permissions to let people selectively see saved SQL questions, and we have permissions settings that let you turn off SQL editing for certain user groups, does it make sense anymore to expose the read-only view of the SQL editor on a saved question if the user doesn't have SQL editing access for that database?

If I'm not allowed to write SQL, what use is there in letting me see the SQL query? As others have commented, this feels like unfortunate surface area where we're exposing more complexity and potentially sensitive information in a case where we really don't need to.

The only additional UI considerations would be making sure SQL question filter widgets remain visible, and making sure the saved question page generally looks right without that bar. Or we go an even dumber, simpler route and just hide the `show query` button on that bar, but that feels a bit like half-assing it to me.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #12735: Highlighting multiple lines for SQL snippet fails to bring up save as snippet option
**Describe the bug**
When trying to create a SQL snippet, if you highlight multiple lines then right-click on the highlighted selection to save as snippet, you often get the system menu, and not the expected Metabase menu to **Run selection** or **Save as snippet**. The behavior is inconsistent. Highlights of single lines appear not to have this issue.

**Logs**
No relevant logs from Javascript console or server.

**To Reproduce**
1. Go to SQL Editor and write some sql:

```sql
select *
from ORDERS
left join PRODUCTS
on PRODUCT_ID = PRODUCT_ID
```
2. Highlight multiple lines, eg. lines 2-4. 
3. Right-click to bring up Metabase dropdown menu.
4. (Usually) get system menu instead.

**Expected behavior**
I should be able to highlight multiple lines of SQL code and right-click on the selection to save as snippet.

**Screenshots**
system menu instead of metbase menu

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.181-108.257.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "mysql",
      "druid",
      "postgres",
      "bigquery",
      "redshift",
      "mongo",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-06-17",
      "tag": "v0.36.0-snapshot",
      "branch": "master",
      "hash": "69aa33f"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```
**Severity**
Annoying and unexpected.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Addresses #12708 

1. Not scoped to a specific database
- [x] Stop filtering to current db in UI
- [x] Allow running snippet on any db
- [x] Remove database id column from snippet table

2. Robust to name changes
- [x] Save `snippet-id` with each snippet template tag
- [x] When running a query, look up snippets with the saved name->id mapping rather than the snippet name
- [x] Update the query text to correct changed names (check correctness on read?)

3. Better UX around name collisions
- [x] Add error message for general name collision
- [x] Add error message for archived name collision

### CODE REVIEW

**Comment by mazameli** [comment]
Here's a small bug: if the snippets sidebar is open and you leave the SQL query builder, when you start a new query, the sidebar opens up unexpectedly.

sidebar-pops-open-unexpectedly

File: src/metabase/models/native_query_snippet.clj [hunk 1]
```diff
@@ -35,10 +28,11 @@
   i/IObjectPermissions
   (merge
    i/IObjectPermissionsDefaults
-   {:perms-objects-set perms-objects-set
-    :can-read?         (partial i/current-user-has-full-permissions? :write)
-    :can-write?        (partial i/current-user-has-full-permissions? :write)
-    :can-create?       (partial i/current-user-has-full-permissions? :write)}))
+   {;; In Metabase CE, everyone can read all NativeQuerySnippets; only admins can create or edit them. In EE
+    ;; permissions are dictated by a 'folder' system similar to Collections (not yet implemented).
```
Comment (paulrosenzweig) [inline src/metabase/models/native_query_snippet.clj:32]: I thought that in CE anyone could create/edit snippets. I like this behavior better (feels more consistent with metrics/segments) but want to confirm what the plan is. cc @mazameli

Comment (mazameli) [reply src/metabase/models/native_query_snippet.clj:32]: Yes, in CE, any user can create, edit, archive, and unarchive snippets from the native query editor screen.

Comment (paulrosenzweig) [reply src/metabase/models/native_query_snippet.clj:32]: @camsaul should I just change these `i/superuser?` to `(constantly true)` or would you want to do a bigger change?

File: frontend/src/metabase-lib/lib/queries/NativeQuery.js [hunk 2]
```diff
@@ -323,6 +321,53 @@ export default class NativeQuery extends AtomicQuery {
       .filter(variableFilter);
   }
 
+  updateSnippetsWithIds(snippets): NativeQuery {
+    const snippetTags = this.templateTags().filter(t => t.type === "snippet");
+    let _this = this; // swap out "this" as we update each template tag
```
Comment (tlrobinson) [inline frontend/src/metabase-lib/lib/queries/NativeQuery.js:326]: not a big deal but this could be written something like this:

```js
return snippets.reduce((query, snippet) => {
  const tag = snippetTags.find(tag => tag["snippet-name"] === snippet.name);
  return tag ? query.setTemplateTag(tag.name, {
    ...tag,
    "snippet-id": snippet.id,
  }) : query;
}, this);

**Comment by mazameli** [comment]
I've found that when logged in as a user with no SQL editor perms, I can open the editor (expected, but probably doesn't make sense), and then open the snippets sidebar, which we don't want (because that would let me view and edit snippets even without SQL editor perms).

Maybe the solution here is to hide the `show query` button on the SQL editor if you don't have SQL editor perms for the DB the question is based on, as described in https://github.com/metabase/metabase/issues/8773. (We even hide that entire bar in situations where no SQL filter widgets are present.)

Here's what I'm currently able to see as a user with no SQL editor perms for any database:

image

**Comment by mazameli** [comment]
I found an interesting bug with renaming snippets. As a user with no sql editor perms, but with collection access to a sql question that uses a snippet, I can see the question just fine. But if another user edits the name of that snippet, when the first user tries to view that same question, they get a permissions error page. Logs say `06-23 15:36:05 WARN middleware.log :: POST /api/dataset 403 1.8 ms (3 DB calls) "You don't have permissions to do that."`

renaming-perms

**Comment by paulrosenzweig** [comment]
@mazameli nice find! The way we handle name updates is by updating the query text on load for any snippet names that have changed. I failed to realize that perms would block some users from running those edited queries. They would run correctly and without perms issues if we didn't edit them, but it seems like going farther down the wrong path to differentiate that based on permissions.

@camsaul what do you think about moving that logic to the backend? Either (a) porting the current behavior of checking for updated snippet names on read or _maybe_ (b) doing a bulk update of queries when a snippet name is changed.

File: src/metabase/models/native_query_snippet.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/models/native_query_snippet.clj:32]: @paulrosenzweig I can tackle that really quick

**Comment by camsaul** [comment]
@paulrosenzweig I think it would be too complicated to do a bulk query search and replace and get it working nicely on the backend. We'd have to load up potentially thousands of saved queries, parse them all, and then save updated versions, and figure out how that works with revisions. So if we were to move logic to the backend, updating on read would be a better option. But since that's basically the same thing that's already working/implemented on the FE is there a pressing reason to do it right now?

If it's working I think reimplementing it isn't super pressing and I'd rather save that for nice-to-have polish tasks at the end

**Comment by camsaul** [comment]
@paulrosenzweig on second thought this idea that the names of snippet references in SQL has to match the name of the snippet is only a thing the frontend code, the backend doesn't care what you name your snippet reference. You can literally call your snippet reference whatever you want in the SQL, whether it's `{{snippet: My Snippet}}` or `{{x}}` and it makes no difference since the mapping of name -> snippet ID is what we actually use.

Sort of like variables/template tags/references to Saved Questions in native queries, the name you use in the query doesn't have to actually line up with anything. We don't update names automatically anywhere else. You can have a Field Filter called `{{my_field}}` that filters a Field called `my_field` and if that field name changes to `my_field_old` for example we don't change the query to have `{{my_field_old}}`. 

I think updating queries automatically when snippets are renamed is definitely nice but to me it feels like more of a polish thing/stretch goal than a core part of snippet functionality. So I would rather get everything else done (including EE stuff) and worry about automatic query updates later. Thoughts @mazameli ?

**Comment by paulrosenzweig** [comment]
It'd be a quick change in the FE to avoid the permission error Maz mentioned. That fix would prevent updating the query text when the user doesn't have sql access. The only remaining issue with that would be that they see the un-updated snippet name in the query text. Fixing in the BE would solve that, but it doesn't seem like a huge deal IMO. 

We _could_ update the query text in the UI but not run that updated text unless the user has permissions. That seems tricky and error prone.

**Comment by camsaul** [comment]
Alternatively can we just let people type in `{{whatever they want}}` like they do for everything else and then choose what snippet it maps to in the side bar, the same way we let people choose what variables/template tags/field filters map to? It seems like in a big query that references `{{source_snippet}}` 10 times if you wanted to switch the snippet you're using it's a lot easier to switch it once in the side bar than to edit 10 references in the SQL

**Comment by camsaul** [comment]
I'm cool with making it work whichever way @mazameli thinks is best, I just would strongly prefer not to add too many more moving parts in the backend code until we get EE perms working, otherwise it starts getting really complicated to sort out

**Comment by camsaul** [comment]
The perms tweaks are pushed now

**Comment by mazameli** [comment]
> That fix would prevent updating the query text when the user doesn't have sql access. The only remaining issue with that would be that they see the un-updated snippet name in the query text. Fixing in the BE would solve that, but it doesn't seem like a huge deal IMO.

It's 100% okay IMO if users without sql editor access would see an un-updated snippet name (I don't even really think they should be the sql query at all).

File: frontend/src/metabase-lib/lib/queries/NativeQuery.js (hunk 2 above)
Comment (paulrosenzweig) [reply frontend/src/metabase-lib/lib/queries/NativeQuery.js]: Good point. When I gave this a second look, I realized I wasn't handling multiple template tags with the same name (due to different spacing). That would require nested `reduce` calls, which seems a bit unreasonable. I went with nested for loops.

**Comment by paulrosenzweig** [comment]
I hid the "show query" button for users who don't have sql perms and avoided the 403 Maz saw when snippets were renamed. I think this PR is ready to go!

**Comment by mazameli** [comment]
@paulrosenzweig After pulling the latest, there's a permissions bug now where, as a non-admin with no SQL editor or data acces perms, I can't view a saved SQL question which includes a snippet even when it's in a collection for which I have View access.

I _can_ view the question if I'm given data access to at least one table in the database that the SQL question is based on.

This _doesn't_ seem to be a problem with saved SQL questions _without_ snippets. I can view those just fine without data or SQL editor perms.

Here's the JS errors I'm seeing when trying to view the SQL snippet question without any data access perms:

```
api.js:236 GET http://localhost:3000/api/database/1 403 (Forbidden)
(anonymous) @ api.js:236
_makeRequest @ api.js:193
_callee2$ @ api.js:166
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ api.js:9
(anonymous) @ api.js:9
(anonymous) @ api.js:9
_makeRequestWithRetries @ api.js:184
_callee$ @ api.js:88
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ api.js:9
(anonymous) @ api.js:9
(anonymous) @ api.js:9
(anonymous) @ api.js:154
_callee$ @ entities.js:309
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ entities.js:26
(anonymous) @ entities.js:26
(anonymous) @ entities.js:26
(anonymous) @ entities.js:310
_callee4$ @ redux.js:237
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ redux.js:20
(anonymous) @ redux.js:20
(anonymous) @ redux.js:20
(anonymous) @ redux.js:229
(anonymous) @ redux.js:271
_callee3$ @ redux.js:203
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ redux.js:20
(anonymous) @ redux.js:20
(anonymous) @ redux.js:20
(anonymous) @ redux.js:213
(anonymous) @ store.js:19
dispatch @ applyMiddleware.js:35
_callee3$ @ actions.js:373
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ actions.js:82
(anonymous) @ actions.js:82
Promise.then (async)
step @ actions.js:82
(anonymous) @ actions.js:82
(anonymous) @ actions.js:82
(anonymous) @ actions.js:518
(anonymous) @ store.js:19
(anonymous) @ bindActionCreators.js:3
componentWillMount @ QueryBuilder.jsx:184
(anonymous) @ ReactCompositeComponent.js:345
measureLifeCyclePerf @ ReactCompositeComponent.js:73
performInitialMount @ ReactCompositeComponent.js:344
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createInitialChildren @ ReactDOMComponent.js:701
mountComponent @ ReactDOMComponent.js:520
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
_updateRenderedComponent @ ReactCompositeComponent.js:762
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
performUpdateIfNecessary @ ReactCompositeComponent.js:558
performUpdateIfNecessary @ ReactReconciler.js:154
runBatchedUpdates @ ReactUpdates.js:148
perform @ Transaction.js:141
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
(anonymous) @ Router.js:103
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
done @ AsyncUtils.js:74
(anonymous) @ AsyncUtils.js:80
getComponentsForRoute @ getComponents.js:6
(anonymous) @ getComponents.js:30
(anonymous) @ AsyncUtils.js:79
mapAsync @ AsyncUtils.js:78
getComponents @ getComponents.js:29
finishEnterHooks @ createTransitionManager.js:77
next @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
wrappedNext @ TransitionUtils.js:110
_callee$ @ routes.jsx:160
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ routes.jsx:93
(anonymous) @ routes.jsx:93
Promise.then (async)
step @ routes.jsx:93
(anonymous) @ routes.jsx:93
(anonymous) @ routes.jsx:93
(anonymous) @ routes.jsx:183
transitionHook @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
next @ AsyncUtils.js:34
loopAsync @ AsyncUtils.js:51
runTransitionHooks @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
runTransitionHooks @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
finishMatch @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
next @ AsyncUtils.js:41
loopAsync @ AsyncUtils.js:51
matchRoutes @ matchRoutes.js:231
match @ createTransitionManager.js:41
historyListener @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
Router_componentWillMount @ Router.js:96
(anonymous) @ ReactCompositeComponent.js:345
measureLifeCyclePerf @ ReactCompositeComponent.js:73
performInitialMount @ ReactCompositeComponent.js:344
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountComponentIntoNode @ ReactMount.js:102
perform @ Transaction.js:141
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
_init @ app.js:75
(anonymous) @ app.js:132
Show 173 more frames
redux.js:231 Request entities,databases,1,fetch failed: {status: 403, data: "You don't have permissions to do that.", isCancelled: false}
_callee4$ @ redux.js:231
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ redux.js:20
(anonymous) @ redux.js:20
Promise.then (async)
step @ redux.js:20
(anonymous) @ redux.js:20
(anonymous) @ redux.js:20
(anonymous) @ redux.js:229
(anonymous) @ redux.js:271
_callee3$ @ redux.js:203
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ redux.js:20
(anonymous) @ redux.js:20
(anonymous) @ redux.js:20
(anonymous) @ redux.js:213
(anonymous) @ store.js:19
dispatch @ applyMiddleware.js:35
_callee3$ @ actions.js:373
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ actions.js:82
(anonymous) @ actions.js:82
Promise.then (async)
step @ actions.js:82
(anonymous) @ actions.js:82
(anonymous) @ actions.js:82
(anonymous) @ actions.js:518
(anonymous) @ store.js:19
(anonymous) @ bindActionCreators.js:3
componentWillMount @ QueryBuilder.jsx:184
(anonymous) @ ReactCompositeComponent.js:345
measureLifeCyclePerf @ ReactCompositeComponent.js:73
performInitialMount @ ReactCompositeComponent.js:344
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createInitialChildren @ ReactDOMComponent.js:701
mountComponent @ ReactDOMComponent.js:520
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
_updateRenderedComponent @ ReactCompositeComponent.js:762
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
performUpdateIfNecessary @ ReactCompositeComponent.js:558
performUpdateIfNecessary @ ReactReconciler.js:154
runBatchedUpdates @ ReactUpdates.js:148
perform @ Transaction.js:141
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
../../../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:62
(anonymous) @ Router.js:103
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
done @ AsyncUtils.js:74
(anonymous) @ AsyncUtils.js:80
getComponentsForRoute @ getComponents.js:6
(anonymous) @ getComponents.js:30
(anonymous) @ AsyncUtils.js:79
mapAsync @ AsyncUtils.js:78
getComponents @ getComponents.js:29
finishEnterHooks @ createTransitionManager.js:77
next @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
wrappedNext @ TransitionUtils.js:110
_callee$ @ routes.jsx:160
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
step @ routes.jsx:93
(anonymous) @ routes.jsx:93
Promise.then (async)
step @ routes.jsx:93
(anonymous) @ routes.jsx:93
(anonymous) @ routes.jsx:93
(anonymous) @ routes.jsx:183
transitionHook @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
next @ AsyncUtils.js:34
loopAsync @ AsyncUtils.js:51
runTransitionHooks @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
runTransitionHooks @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
finishMatch @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
next @ AsyncUtils.js:41
loopAsync @ AsyncUtils.js:51
matchRoutes @ matchRoutes.js:231
match @ createTransitionManager.js:41
historyListener @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
Router_componentWillMount @ Router.js:96
(anonymous) @ ReactCompositeComponent.js:345
measureLifeCyclePerf @ ReactCompositeComponent.js:73
performInitialMount @ ReactCompositeComponent.js:344
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountComponentIntoNode @ ReactMount.js:102
perform @ Transaction.js:141
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
_init @ app.js:75
(anonymous) @ app.js:132
Show 149 more frames
app.js:8 Error: {status: 403, data: "You don't have permissions to do that.", isCancelled: false}
```

**Comment by paulrosenzweig** [comment]
@mazameli another good permissions catch! It turns out we can't fetch the db to check write perms if the user doesn't have any perms. I switched the individual db fetch to a list fetch and all seems well.

**Comment by mazameli** [comment]
Sweet, lemme test again.

**Review by mazameli — APPROVED** [review]
Looks good! I think this also closes https://github.com/metabase/metabase/issues/8773 now that we're hiding the `show query` button from folks without SQL editor access.
