### PR TITLE
Describe nested json refactor

### LINKED ISSUE #25744: JSON unfolded field always uses type from original schema
**Describe the bug**
We have a number of JSON fields which can have different types, the two basic situations where this occurs are:

* they can have different values in our application - eg. something that can be a boolean or an object
* the value has changed over time (eg. an integer has become a float)

It looks like when extracting the data out of the JSON blobs it always try to cast the result as what it detected in the 'original schema'. Even if the actual DB field is set not to cast.

**Logs**

For our table (load_count_cycles), if I try and open it directly I get this page:

image

If I change the sort I can get this error instead:

image

Which relates to a value of 'dumped_at` in one of blobs, which has no value of casted:

image

In the original schema it was detected as an integer, which makes me think it is actually being casted based on the original detected value?

image

**To Reproduce**

We have this issue many of our tables, so presumably it will happen for any mixed type json values in a postgres database.

**Expected behavior**
I expect to be able to see my table.

If it is limited to a single type, I would also be expect to be able to manage this type. It seems to detect one 'at random' (two different DBs have detected different types for the same field). 

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16.1+1",
    "os.name": "Linux",
    "os.version": "4.14.287-215.504.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Australia/Sydney"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.13"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-29",
      "tag": "v0.44.4",
      "branch": "release-x.44.x",
      "hash": "382d728"
    },
    "settings": {
      "report-timezone": "Australia/Sydney"
    }
  }
}
```

**Severity**

This is currently blocking our upgrade to 0.44, since many of tables do not work anymore. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by qnkhuat**
Notable changes:
- Making some tests run by feature, not by driver, this makes the test more robust in case we support more drivers in the future
- Break down the big `describe-nested-field-columns` to smaller functions

This is preparation to fix https://github.com/metabase/metabase/issues/25744

### CODE REVIEW

File: test/metabase/driver/mysql_test.clj [hunk 1]
```diff
@@ -123,7 +120,9 @@
      ["Toucan"                2]
      ["Empty Vending Machine" 0]]]])
 
-(defn- db->fields [db]
+(defn db->fields
+  "Give a DB return it fields as a set."
```
Comment (calherries) [inline test/metabase/driver/mysql_test.clj:124]:
```suggestion
  "Given a DB return its fields as a set."
```

**Review by calherries — APPROVED** [review]
LGTM
