### PR TITLE
Fix broken drill thrus/make sure all drill thrus produce valid queries after application

### LINKED ISSUE #33480: [MLv2] Fix `drill_thru` method to handle additional drill parameters
Calling `drill_thru` lib method throws an error in case any additional parameter has been passed, which most of drills require. Example - sort drill: `Error: No method in multimethod 'metabase.lib.drill-thru/drill-thru-method' for dispatch value: :drill-thru/sort`

You can use this unit test to reproduce - https://github.com/metabase/metabase/blob/mblib-drill-thru-fe/frontend/src/metabase-lib/drills.unit.spec.ts#L713

I did some investigation and it seems the root cause is that compiled Closure-to-JS code filters out additional function attributes.

### PR DESCRIPTION
**Pull request by camsaul**
- Add logic to the tests in `metabase.lib.drill-thru-test` to check that we can apply every suggested drill thru and that applying it returns a valid query.
- Implement `drill-thru-method` for several drill thrus that were missing it and fix several others that were broken.

Fixes #33480

### CODE REVIEW

File: .clj-kondo/com.github.seancorfield/next.jdbc/config.edn [hunk 1]
```diff
@@ -1,5 +1,8 @@
 {:hooks
  {:analyze-call
   {next.jdbc/with-transaction
-   hooks.com.github.seancorfield.next-jdbc/with-transaction}}
```
Comment (camsaul) [inline .clj-kondo/com.github.seancorfield/next.jdbc/config.edn:4]: I ran Kondo locally and these are the new imports. Not strictly related to this PR but we want to check these in so I'm doing it here

File: src/metabase/lib/binning.cljc [hunk 2]
```diff
@@ -69,54 +71,49 @@
...
+  {:lib/type     :option/binning
+   :display-name (i18n/tru "Auto bin")
    :default      true
    :mbql         {:strategy :default}})
 
 (defn- with-binning-option-type [m]
   (assoc m :lib/type :option/binning))
 
-(def ^:private *numeric-binning-strategies
-  (delay (mapv with-binning-option-type
```
Comment (camsaul) [inline src/metabase/lib/binning.cljc:85]: Using a delay here is broken because it will only call `i18n/tru` when the delay is dereffed the first time, it will be broken if the user changes their language... the performance impact of recalculating i18n strings for binning options is not important enough to try to optimize things this way anyway.

File: src/metabase/lib/binning.cljc [hunk 3]
```diff
@@ -69,54 +71,49 @@
...
 
-(defn default-auto-bin
+(mu/defn default-auto-bin :- ::lib.schema.binning/binning-option
   "Returns the basic auto-binning strategy.
 
   Public because it's used directly by some drill-thrus."
   []
-  {:display-name (i18n/tru "Auto bin")
+  {:lib/type     :option/binning
+   :display-name (i18n/tru "Auto bin")
```
Comment (camsaul) [inline src/metabase/lib/binning.cljc:80]: Once of the drill thru impls was calling `default-auto-bin` but it didn't produce a valid binning-option resulting in a broken drill

File: src/metabase/lib/drill_thru.cljc [hunk 4]
```diff
@@ -3,20 +3,28 @@
...
    [metabase.lib.drill-thru.zoom-in-timeseries :as lib.drill-thru.zoom-in-timeseries]
    [metabase.lib.metadata.calculation :as lib.metadata.calculation]
    [metabase.lib.schema :as lib.schema]
    [metabase.lib.schema.drill-thru :as lib.schema.drill-thru]
    [metabase.util.malli :as mu]))
 
+(comment
+  lib.drill-thru.fk-details/keep-me
+  lib.drill-thru.pk/keep-me
+  lib.drill-thru.zoom/keep-me)
```
Comment (camsaul) [inline src/metabase/lib/drill_thru.cljc:26]: Moved the methods for these into their own namespaces so it was easier to find them when working on fixing them

File: src/metabase/lib/drill_thru/column_filter.cljc [hunk 5]
```diff
@@ -36,6 +34,10 @@
   {:type       :drill-thru/column-filter
    :initial-op initial-op})
 
-(defmethod lib.drill-thru.common/drill-thru-method :drill-thru/column-filter
-  [query stage-number {:keys [column] :as _drill-thru} filter-op value & _]
-  (lib.filter/filter query stage-number (lib.options/ensure-uuid [(keyword filter-op) {} (lib.ref/ref column) value])))
```
Comment (camsaul) [inline src/metabase/lib/drill_thru/column_filter.cljc:41]: This was basically just duplicating the logic in `lib.filter/filter-clause` so I just updated `filter-clause` to take keywords or strings as well and removed the duplication.

File: src/metabase/lib/drill_thru/fk_details.cljc [hunk 6]
```diff
@@ -0,0 +1,42 @@
+(ns metabase.lib.drill-thru.fk-details
```
Comment (camsaul) [inline src/metabase/lib/drill_thru/fk_details.cljc:1]: Moved from `lib.drill-thru.object-details`

File: src/metabase/lib/drill_thru/pk.cljc [hunk 7]
```diff
@@ -0,0 +1,18 @@
+(ns metabase.lib.drill-thru.pk
```
Comment (camsaul) [inline src/metabase/lib/drill_thru/pk.cljc:1]: moved

File: src/metabase/lib/drill_thru/object_details.cljc [hunk 8]
```diff
@@ -55,47 +50,3 @@
...
-
-(defmethod lib.drill-thru.common/drill-thru-info-method :drill-thru/fk-details
-  [_query _stage-number drill-thru]
-  (select-keys drill-thru [:many-pks? :object-id :type]))
-
-(defmethod lib.drill-thru.common/drill-thru-method :drill-thru/pk
-  [query stage-number {:keys [column object-id]} & _]
-  ;; This type is only used when there are multiple PKs and one was selected - [= pk x] filter.
-  (lib.filter/filter query stage-number
-                     (lib.options/ensure-uuid [:field {} (lib.ref/ref column) object-id])))
```
Comment (camsaul) [inline src/metabase/lib/drill_thru/object_details.cljc:75]: This looked extremely busted. Fixed

File: src/metabase/lib/drill_thru/object_details.cljc [hunk 9]
```diff
@@ -55,47 +50,3 @@
...
-    (string? x)                x
-    (and (vector? x)
-         (= :field (first x))) (field-id (nth x 2))
-    (map? x)                   (:id x)))
-
-(defmethod lib.drill-thru.common/drill-thru-method :drill-thru/fk
-  [query stage-number {:keys [column object-id]} & _]
-  (let [fk-column-id     (:fk-target-field-id column)
-        fk-column        (lib.metadata/field query fk-column-id)
-        fk-filter        (lib.options/ensure-uuid [:= {} (lib.ref/ref fk-column) object-id])
```
Comment (camsaul) [inline src/metabase/lib/drill_thru/object_details.cljc:89]: Changed this to `(lib.filter/= fk-column object-id)`... no need to construct things the hard way

File: src/metabase/lib/drill_thru/summarize_column_by_time.cljc [hunk 10]
```diff
@@ -21,20 +24,22 @@
...
-      {:lib/type :metabase.lib.drill-thru/drill-thru
-       :type     :drill-thru/summarize-column-by-time
-       :column   column
-       :breakout breakout-column})))
+    (when-let [breakout-column (m/find-first lib.types.isa/temporal?
+                                             (lib.breakout/breakoutable-columns query stage-number))]
+      (when-let [bucketing-unit (m/find-first :default
+                                              (lib.temporal-bucket/available-temporal-buckets query stage-number breakout-column))]
+        ;; only suggest this drill thru if the breakout it would apply does not already exist.
+        (let [bucketed (lib.temporal-bucket/with-temporal-bucket breakout-column bucketing-unit)]
```
Comment (camsaul) [inline src/metabase/lib/drill_thru/summarize_column_by_time.cljc:32]: Fixed bug: this drill thru was suggested even if the query already had the same exact breakout.

**Review by bshepherdson — APPROVED** [review]
