### PR TITLE
fix(sdk): remove usage of legacy query in static question

### LINKED ISSUE #47690: Replace legacy MBQL queries in the sdk in StaticQuestion
We should get rid of the use of [legacy MBQL queries](https://github.com/metabase/metabase/blob/c2b7cc9e807ee75d2bc94f0b5a814e01d29fd077/enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.tsx#L134) in StaticQuestion.

```ts
const legacyQuery = question.legacyQuery({
  useStructuredQuery: true,
});
```

[See the note in this channel](https://metaboat.slack.com/archives/C0645JP1W81/p1725554873732219) for more information on how to replace it.

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/47690

We do not need to pass in `query` anymore to `visualization.isSensible`, so we are safe to remove that from the viz selector in chart type sidebar.

### Demo

The visualization selector continues to work in the SDK's StaticQuestion, and in the main Metabase app.

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/PivotTable/utils.ts [hunk 1]
```diff
@@ -206,15 +206,8 @@ function databaseSupportsPivotTables(query: StructuredQuery) {
...
-export function isSensible(
-  { cols }: { cols: DatasetColumn[] },
-  query: StructuredQuery,
-) {
-  return (
-    cols.length >= 2 &&
-    cols.every(isColumnValid) &&
-    databaseSupportsPivotTables(query)
-  );
+export function isSensible({ cols }: { cols: DatasetColumn[] }) {
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/visualizations/PivotTable/utils.ts:209]: `query` is no longer passed in since v0.49

File: frontend/src/metabase/visualizations/types/visualization.ts [hunk 2]
```diff
@@ -236,8 +236,7 @@ export type VisualizationDefinition = {
   placeHolderSeries?: Series;
 
   transformSeries?: (series: Series) => TransformedSeries;
-  // TODO: remove dependency on metabase-lib
-  isSensible: (data: DatasetData, query?: Query) => boolean;
+  isSensible: (data: DatasetData) => boolean;
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/types/visualization.ts:239]: I assume the "dependency on metabase-lib" TODO here refers to the `Query` type and `databaseSupportsPivotTables`, which we just removed.

**Review by ranquild — APPROVED** [review]
