### PR TITLE
Do not render `ExecutionTime` if there is no `time` to format

### LINKED ISSUE #45730: NaN displayed in query execution time
### Describe the bug

image

### To Reproduce

1. New > Question > Orders > Visualize
2. Disable network
3. Summarize > Done

### Information about your Metabase installation

master, 24caede62a

### Severity

P3

### PR DESCRIPTION
**Pull request by nemanjaglumac**
### What does this PR accomplish?
Fixes #45730 by preventing the render to happen if `time` is missing for any reason.

We could run into this because of a network error (as explained in the issue). In that case, `result` does not contain the `running_time` that we're passing down to `ExecutionTime` component.

I've adjusted the props interface to reflect this new finding.

### Checklist
- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx [hunk 1]
```diff
@@ -5,11 +5,17 @@ import { Tooltip } from "metabase/ui";
...
+  time?: number;
 }
 
-export const ExecutionTime = ({ time }: Props) => (
-  <Tooltip label={t`Query execution time`}>
-    <span data-testid="execution-time">{formatDuration(time)}</span>
-  </Tooltip>
-);
+export const ExecutionTime = ({ time }: Props) => {
+  if (!time) {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx:12]: Maybe check for `if (time == null)`? So we could render `0`

**Review by ranquild — APPROVED** [review]
One comment

File: frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx:12]: The `time` is explicitly `undefined` in case of an error. The response has the following shape:
```
{
  duration: number,
  error: string // or maybe object - I'd have to double check
}
```` 

In all other scenarios, the response seems to have an explicit `running_time`. Not sure if it's possible that it's ever `null`, since we don't have the type for it.

So I can add the check for null, just in case but we definitely need to leave the undefined check, IMO.
It makes sense not to display anything. We use the same approach for "Showing ___ rows", after all.

File: frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.unit.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+describe("ExecutionTime", () => {
+  it("renders nothing when no time is provided (metabase#45730)", () => {
+    const { container } = render(<ExecutionTime />);
+
+    expect(container).toBeEmptyDOMElement();
+  });
+
+  it("renders formatted time when time is provided", () => {
+    render(<ExecutionTime time={100} />);
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.unit.spec.tsx:14]: Please add a test case where `time={0}`

Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.unit.spec.tsx:14]: Ok, but it makes sense to add it here, right?
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/view/ExecutionTime/utils.unit.spec.ts

Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.unit.spec.tsx:14]: Here because `if (!time)` check lives in the component.

Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.unit.spec.tsx:14]: Good catch.
I guess the question is do we want to display "0 ms" or do we want to not render the component. The solution depends on that answer.

Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.unit.spec.tsx:14]: "0 ms" please :pray:

Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.unit.spec.tsx:14]: https://github.com/metabase/metabase/pull/45749/commits/88506425652f9b343f9ad57e97f4212c66769065

File: frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx (hunk 1 above)
Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx]: @qnkhuat helped me check the type for running_time and it's set to not null.
image

Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx]: I'm pretty sure @ranquild meant the `=== undefined` case but `==` made it ambiguous.

https://www.notion.so/metabase/56f6f59da3b647de89acb28ea9ebc424?v=cca33933b6244a7a94f256d1c110ce09&p=5e63b631c8c545a9bbd272e54deeeebe&pm=s ;)

Comment (nemanjaglumac) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx]: In that case, here's an explicit check for `undefined`.
This also simplifies the logic as I don't have to guard against 0.

**Review by kamilmielnik — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/query_builder/components/view/ExecutionTime/ExecutionTime.tsx]: I meant that we would ignore `0` this way
