### PR TITLE
Embed query endpoints should handle operator filters with a single arg

### LINKED ISSUE #20438: Embed dashboard Field Filter cannot work when choosing single option
Embed dashboard Field Filter cannot work when choosing one option, but if you choose multiple options, it can work.
The question was generated by native SQL.
The previous Metabase v0.41.6 does not have this bug.

```
SELECT * FROM PUBLIC.PEOPLE
WHERE true
    [[AND {{NAME}}]]
```

**Screenshots**
metabase_issue

### PR DESCRIPTION
**Pull request by camsaul**
Operator parameter types like `:string/=` expect a sequence of values. Embed query endpoints specify parameter values as URL query params, meaning something like `GET ...?name=Cam` gets translated to `{:value "Cam"}` rather than the `{:value ["Cam"]}` the operator parameter type handlers expect. Fixed by tweaking code to fix up non-sequential operator parameter values when we encounter them.

Fixes #20438

### CODE REVIEW

**Review by flamber — APPROVED** [review]

File: src/metabase/api/embed.clj [hunk 1]
```diff
@@ -160,7 +161,12 @@
   [parameters slug->value]
   (when (seq parameters)
     (for [param parameters
-          :let  [value (get slug->value (keyword (:slug param)))]
+          :let  [value (get slug->value (keyword (:slug param)))
+                 value (if (and (seq value)
+                              (params.operators/operator? (:type param))
+                              (not (sequential? value)))
+                         [value]
+                         value)]
```
Comment (noahmoss) [inline src/metabase/api/embed.clj:169]: Could `u/one-or-many` be useful here?

**Review by noahmoss — APPROVED** [review]

File: src/metabase/api/embed.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/api/embed.clj]: Good idea. Fixed
