### PR TITLE
Dashboard param value (chain filter) endpoints should return cached FieldValues

### LINKED ISSUE #13832: Filters with dropdown lists uses query on the database
**Describe the bug**
Since 0.37, filters with dropdown lists gets the information by querying the source database, when focusing the filter, and caching is not effective for those queries.
In previous versions, this information was retrieved from the application database as part of the dashboard data (`/api/dashboard/:id`)

**To Reproduce**
(this is using a converted Sample Dataset on MariaDB)
1. Make sure Admin > Data Model > (MariaDB) > Products > Category > "Field Type"="Category" and "Filtering on this field"="A list of all values"
2. Simple question > (MariaDB) > Products - save as "Q1"
3. Create dashboard, add Q1 and add filter type "Categories" and connect to Q1.Category - save dashboard
4. Click filter widget, which sends request `/api/dashboard/:id/params/:params/values`, which makes a query in the source database. Clicking the filter widget again will do the same. The query sent every time:
```SELECT `PRODUCTS`.`CATEGORY` AS `CATEGORY` FROM `PRODUCTS` GROUP BY `PRODUCTS`.`CATEGORY` ORDER BY `PRODUCTS`.`CATEGORY` ASC LIMIT 1000```

**Expected behavior**
While it might not be possible to have a behavior like previous versions, since part of the change was to allow linked filters, it should not make a query to the source database, since that makes the scan-process moot (which is still used in QB filters) and causes excessive amount of queries on busy dashboards.

The `LIMIT 1000` also makes it behave differently than in QB filter, which does some auto-widget-conversion of the filter, when there's more than 300 distinct values - that conversion has it's own quirks #7603
But now, the dashboard filter list will only list 1000 values. Creating a filter for Reviews.Reviewer would only show results until "timmy" and never show or indicate that there are 76 results were not included. This might need it's own issue coupled with #7603

**Information about your Metabase Installation:**
Metabase 0.37 thru 0.37.2

Related to #13537 and #12654

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #13832

Dashboard param values (aka Chain Filter) endpoints will return cached FieldValues if no additional constraints are passed, i.e. if the query is a "fetch all values of this Field" query. Sandboxing is respected the same way it is for the FieldValues endpoint `GET /api/field/:id/values`.

I refactored a few things in the process of getting this working.

-  `reify-ee-strategy-impl` now takes a predicate var as an argument instead of always checking `(metabase.public-settings.metastore/enable-enhancements?)` to decide whether the EE impl should be used. `enable-enhancements?` returns true if we have an EE token with *any* features. Now we can have the EE strategy impl only enable certain EE impls if tokens have certain features, e.g. by using `metabase.public-settings.metastore/enable-sandboxing?`. This change isn't strictly necessary for this fix, but the behavior is more correct (e.g. we shouldn't sandbox FieldValues for a EE token without sandboxing enabled)
- Reworked the way we implement the different OSS/EE behavior for `GET /api/field/:id/values` endpoints, Previously, we had an EE version of this endpoint that overshadowed the OSS version when EE code was present. I refactored this to use an EE Strategy Impl instead (this was necessary because the chain-filter code has to use the EE/OSS field values code)
- I made the normal hydration function for Card/Dashboard `:param_values` respect current user sandboxes, and added a dynamic variable `*ignore-current-user-perms-and-return-all-field-values*` for situations where we want to do that (i.e., for public or embedded Cards/Dashboards, which have no current User). It seems preferable to have to opt-in to situations where we bypass normal security mechanisms

Also:

- lots and lots of tests
- I fixed an issue where Dashboard `param_values` didn't come back at all when sandboxing was enabled. Fixed this so `param_values` returns the sandboxed values, the same way the chain filter or field values endpoints do.

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+    pretty/PrettyPrintable
+    (pretty [_]
+      `impl)
+
+    params.field-values/FieldValuesForCurrentUser
+    (get-or-create-field-values-for-current-user!* [_ field]
+      (or (when (field-is-sandboxed? field)
+            (fetch-sandboxed-field-values field))
+          (params.field-values/get-or-create-field-values-for-current-user!* params.field-values/default-impl field)))
+
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:71]: if a user had sandboxing and there were no values they could see would this fall back to showing all values? Should that `or` be an `if` on (field-is-sandboxed? field)`

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+            [metabase.util :as u]
+            [pretty.core :as pretty]
+            [toucan.db :as db]))
+
+(def ^:private ^{:arglist '([user-id last-updated field])} fetch-sandboxed-field-values*
+  (memoize/ttl
+   ;; use a custom key fn for memoization so two Field maps with different keys but the same `:id` still have the same
+   ;; cache key.
+   ^{::memoize/args-fn (fn [[current-user-id updated-at field]]
+                         [current-user-id updated-at (u/the-id field)])}
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:19]: should permissions go into this as well? If someone doesn't have full access, complains to their boss, they expand access, they wouldn't see the newly available field values for 30 days under this strategy.

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+(defn- fetch-sandboxed-field-values
+  [field]
+  (fetch-sandboxed-field-values*
+   api/*current-user-id*
+   (db/select-one-field :updated_at FieldValues :field_id (u/the-id field))
+   field))
+
+(defn- field-is-sandboxed? [field]
+  (sandbox.api.table/only-segmented-perms? (field/table field)))
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:39]: `field/table` does a `(db/select-one 'Table, :id table_id)`. If segmentation of a field is really segmentation of a table, perhaps grouping by table-id and then basing segmentation off of that would save some trips to the db. (instead of the `(group-by (comp boolean field-is-sandboxed?) fields)` below

Comment (dpsutton) [reply enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:39]: or does the qp store come into play here?

File: enterprise/backend/src/metabase_enterprise/enhancements/ee_strategy_impl.clj [hunk 4]
```diff
@@ -5,14 +5,13 @@
...
             [pretty.core :refer [PrettyPrintable]]))
 
 (defn invoke-ee-when-enabled
-  "Impo for `reify-ee-strategy-impl`. Invoke `method` using `ee-impl` if EE features are enabled, otherwise invoke with
+  "Impl for `reify-ee-strategy-impl`. Invoke `method` using `ee-impl` if EE features are enabled, otherwise invoke with
   `oss-impl`."
-  [method ee-impl oss-impl & args]
-  (let [impl (if (settings.metastore/enable-enhancements?)
+  [enable-pred-var method ee-impl oss-impl & args]
+  (let [impl (if (enable-pred-var)
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/enhancements/ee_strategy_impl.clj:14]: this machinery is really clever. I think the only thing i don't like is how sensitive it would be to getting the order of `ee-impl` and `oss-impl` mixed up, and it's kinda hardcoded to just the two. If you're in there and want to change it a bit, maybe instead of `pred`, `ee-impl`, and `oss-impl` it could just take an impl-thunk which will return an impl. This allows for arbitrarily many impls in the future and makes sure that the macro invocation sites clearly express which impl goes with which branch of the pred.

```clojure
(ee-strategy-impl/reify-ee-strategy-impl #'settings.metastore/enable-sandboxes? impl params.field-values/default-impl
  params.field-values/FieldValuesForCurrentUser)

;; after
(ee-strategy-impl/reify-ee-strategy-impl #(if (settings.metastore/enable-sandboxes?) impl params.field-values/default-impl) params.field-values/FieldValuesForCurrentUser)
```

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj (hunk 1 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:71]: Yeah, this should probably be an `if`

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj (hunk 2 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:19]: That's a good point. I'll tweak it

File: enterprise/backend/src/metabase_enterprise/enhancements/ee_strategy_impl.clj (hunk 4 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/enhancements/ee_strategy_impl.clj:14]: that's a good idea

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj (hunk 3 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:39]: Actually, we could just `hydrate` the `:table` for the Fields (Toucan will do a batched hydration here) so we don't end up making a bunch of separate calls

File: enterprise/backend/src/metabase_enterprise/enhancements/ee_strategy_impl.clj (hunk 4 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/enhancements/ee_strategy_impl.clj:14]: Now that you brought this up, there's no reason this should really even be just an EE strategy impl anymore -- it could be called something more general like `strategy-impl` or `fn-strategy-impl` (not sure on the name). At that point moving the namespace and renaming everything and reworking all the macroexpansion tests would be a bit more that I want to tackle in this bugfix PR. I probably shouldn't have even made the pred fn change in the first place -- I thought I needed it at first but it turns out I didn't; the change still seemed like more correct behavior so I left it in place. I think the additional refactoring would make more sense in `master` as a follow-on PR

**Review by flamber — COMMENTED** [review]
This works much better. A couple of notes, where some might want to be tackled in separate issues.
I'm testing with MariaDB and Postgres loaded with the Sample Dataset.

1. If a field has 301+ (?) distinct values, and is set as a dropdown ("A list of all values"), then it makes a query (5000 distinct) to the datadb on every dashboard load.
Reproduce with People.City set as dropdown. Can also be reproduce by reloading the field details page in Data Model.
   1. For sandboxed users, this gets even more interesting, since we're querying 5000, when the user enters the dashboard (memorized), but when the user opens the dropdown, then we're querying 100 again (non-memorized), when a field has 301+ (?) distinct values.
   When the field is <301 distinct values (non-sandboxed), then the query for 100 is memorized.
   2. Sandbox queries are only stored in memory, but that's issue #15977.
2. We're querying 5000 distinct values for dropdowns, but we're currently only showing 100 results (regression issue #15695, was previously 300 results in issue #7603). It would be a performance improvement if we only queried the same amount as we actual show.
3. It sends a request to the appdb every time the dropdown is opened. While this is still much faster than datadb, would it be possible for the frontend to store the values from the first request, so it doesn't need to do another request if dropdown is opened again?
4. For fields with less than 300 distinct values and set to dropdown/plain, those values are included in `/api/dashboard/:id` in `param_values`, so it should probably not include those in the dashboard request and just use the API to lookup the values (and do some frontend cache - point 3).
5. When using Linked Filters, then queries are to the datadb, which is understandable - though it would be nice if point 3+4 was done, so it doesn't need to do query every time the dropdown is opened at least.

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+   ;; Expire entires older than 30 days so we don't have entries for users and/or fields that
+   ;; no longer exists hanging around.
+   ;; (`clojure.core.cache/TTLCacheQ` (which `memoize` uses underneath) evicts all stale entries on
+   ;; every cache miss)
+   :ttl/threshold (* 1000 60 60 24 30)))
+
+(defn- fetch-sandboxed-field-values
+  [field]
+  (fetch-sandboxed-field-values*
+   (db/select-one-field :updated_at FieldValues :field_id (u/the-id field))
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:41]: The timestamp here is used as cache invalidation when there would be new field values. If a field has no FieldValues (too many distinct values, temporal, marked manually as don't cache them) this will be nil and there would be no way to get newer field values afterwards. This is certainly an edge case on fields that get promoted out of list or auto-list. Is this endpoint ever hit for other types of fields, where it doesn't expect to find FieldValues?

**Review by dpsutton — APPROVED** [review]

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj (hunk 5 above)
Comment (camsaul) [reply enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:41]: I don't think so. Fields have a hydrated `has_field_values` key we add in API responses and I think the FE doesn't hit this endpoint in that case

**Comment by ariya** [comment]
Note that, in combination with PR #13481, this seems [to fix another dashboard filter issue](https://github.com/metabase/metabase/issues/15119#issuecomment-840533015).
