### PR TITLE
Fix passing a font for static embedded question

### LINKED ISSUE #45638: Embed preview doesn't change the font when setting static question font to any font
### Describe the bug

Embed preview doesn't change the font when setting static question font to any font.
image

https://github.com/user-attachments/assets/1e72924d-0a5a-4773-9681-04f553adb0ef

### To Reproduce

Using EE/Pro license, with embedding enabled
1. Go to a question
2. Click sharing icon > Embed > Static Embed
3. Select Appearance tab and click the preview to see the question preview
4. Change the font to any font. The preview font stays the same regardless of any font selected.

### Expected behavior

The embed preview font should reflect the selected font option immediately.

### Logs

_No response_

### Information about your Metabase installation

```JSON
commit: `master` @ 97cfe29e894d63733ce29e391d5ff8d5e98fe4d2

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.2+13-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.2+13-LTS",
    "os.name": "Mac OS X",
    "os.version": "14.5",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-07-15",
      "src_hash": "80ae6221f268db83d6c316285073f7428bd3c659",
      "tag": "v1.2.0-SNAPSHOT",
      "hash": "efeab36"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
Fix passing a font for static embedded question

Fixes https://github.com/metabase/metabase/issues/45638

Before:

https://github.com/user-attachments/assets/1e72924d-0a5a-4773-9681-04f553adb0ef

After:

https://github.com/user-attachments/assets/390d66c7-290a-4a53-aa06-08b4f643d21e

# How to verify
## Preview
- Create any question or open an existing one
- Click the `Sharing/Embed`
- Select the `Static embedding`
- Select the `Look and feel` tab and click `preview`
- Now select any font via the `Font` dropdown
- Font should be changed in the `preview` window

## When embedded
- Now embed this question (locally) using code template from the preview window
- The passed `font` parameter should be applied to the embedded question

### CODE REVIEW

File: frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx [hunk 1]
```diff
@@ -74,7 +74,7 @@ type OwnProps = {
 type PublicOrEmbeddedDashboardProps = OwnProps &
   ReduxProps &
   DashboardDisplayOptionControls &
-  EmbedDisplayParams &
+  Omit<EmbedDisplayParams, "font"> &
```
Comment (sanex3339) [inline frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx:77]: The `font` field was not used inside this component (because it was set to the store directly in `use-embed-font` hook.

I removed it from types and from being passed to this component as a prop

File: frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/tests/PublicOrEmbeddedQuestion.common.unit.spec.tsx [hunk 2]
```diff
@@ -1,24 +1,40 @@
...
     ...opts,
     questionName: QUESTION_NAME,
     uuid: FAKE_UUID,
   });
+
+  return { useSetEmbedFontMock };
 }
 
 describe("PublicOrEmbeddedQuestion", () => {
+  it("sets embed font", async () => {
```
Comment (WiNloSt) [inline frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/tests/PublicOrEmbeddedQuestion.common.unit.spec.tsx:29]: I'm not a fan of a test like this since it relies on a specific kind of implementation. If we change the way we reads `font` this test could fail, but the Cypress test would still pass since it actually asserts a behavior of the application rather than an implementation. I'd remove revert this file. What do you think?

**Review by WiNloSt — COMMENTED** [review]
The approach looks good, but I have concerns about a few things.
1. I think the dashboard changes shouldn't be in this PR.
2. The question unit test (that relies on mock hook) could be reverted imo, and only relies on Cypress tests instead.

File: e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js [hunk 3]
```diff
@@ -1015,6 +1015,27 @@ H.describeEE("scenarios > embedding > dashboard appearance", () => {
 
     cy.url().should("include", "locale=de");
   });
+
+  it("should allow to set font from the `font` hash parameter", () => {
```
[the remark this answers is not in the document]
Comment (sanex3339) [reply e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js:1019]: We didn't have this bug for the dashboard. But for `embedding-question.cy.spec.js` I will mention the issue. Thank you.

File: frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/tests/PublicOrEmbeddedQuestion.common.unit.spec.tsx (hunk 2 above)
Comment (sanex3339) [reply frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/tests/PublicOrEmbeddedQuestion.common.unit.spec.tsx:29]: Let's remove it.

File: frontend/src/metabase/dashboard/hooks/use-dashboard-url-params.ts [hunk 4]
```diff
@@ -23,7 +19,7 @@ export const useDashboardUrlParams = ({
   location: Location;
   onRefresh: () => Promise<void>;
 }) => {
-  const { font, setFont } = useEmbedFont();
+  useSetEmbedFont({ location });
```
[the remark this answers is not in the document]
Comment (sanex3339) [reply frontend/src/metabase/dashboard/hooks/use-dashboard-url-params.ts]: Will split it into 2 PRs

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx [hunk 5]
```diff
@@ -84,7 +83,6 @@ const InteractiveDashboardInner = ({
   });
 
   const { theme } = useEmbedTheme();
-  const { font } = useEmbedFont();
```
[the remark this answers is not in the document]
Comment (sanex3339) [reply enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx]: Will split it into 2 PRs

File: frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx (hunk 1 above)
Comment (sanex3339) [reply frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx]: I reverted this change as well and will extract it to a separate PR

File: frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx [hunk 6]
```diff
@@ -48,6 +51,14 @@ export const PublicOrEmbeddedQuestion = ({
   const [parameterValues, setParameterValues] = useState<ParameterValuesMap>(
     {},
   );
+
+  const { setFont } = useEmbedFont();
+  useEffect(() => {
+    const { font } = parseHashOptions(location.hash) as DashboardUrlHashOptions;
```
Comment (WiNloSt) [inline frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx:57]: I think you could use `EmbeddingDisplayOptions`. As this type has 3 specific dashboard options that aren't present on questions
https://github.com/metabase/metabase/blob/0d33cce6228ba25d11232e36cc4932f7c91e0a66/frontend/src/metabase/dashboard/types/hash-options.ts#L9-L13

File: frontend/src/metabase/dashboard/hooks/use-dashboard-url-params.unit.spec.tsx [hunk 7]
```diff
@@ -1,59 +0,0 @@
-import { renderHook } from "@testing-library/react";
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/hooks/use-dashboard-url-params.unit.spec.tsx:1]: why is this file deleted? It's not like it was added in this PR.

**Review by WiNloSt — APPROVED** [review]
I tested this. It worked as expected!

File: frontend/src/metabase/dashboard/hooks/use-dashboard-url-params.unit.spec.tsx (hunk 7 above)
Comment (sanex3339) [reply frontend/src/metabase/dashboard/hooks/use-dashboard-url-params.unit.spec.tsx:1]: I added this file + test in my previous PR, it contained only a single test that had the same issue as you mentioned here: https://github.com/metabase/metabase/pull/52368#discussion_r1923600632

So I removed it and we can rely on e2e

Comment (sanex3339) [reply frontend/src/metabase/dashboard/hooks/use-dashboard-url-params.unit.spec.tsx]: Reverted, it's better to remove it in the next PR with refactoring.
I created it in a previous PR related to the fonts issue as well.

And it has the same issue as you mentioned here https://github.com/metabase/metabase/pull/52368#discussion_r1923600632

But let's remove it in the next PR
