### PR TITLE
Unskip and update calendar test + fix date range picker text inputs not in sync with calendar inputs

### LINKED ISSUE #55688: calendar test is broken after migration away from filter modal
**Context**

`e2e/test/scenarios/question-reproductions/reproductions.cy.spec.ts`

`calendar has constant size when using date range picker filter (metabase#39487)`

Fix the test and unskip

### LINKED ISSUE #64602: Date range picker text inputs are not in sync with calendar inputs
### Describe the bug

It works correctly for "Before", "On", and "After" filters.
It's a regression - it worked correctly for "Between" filter in v48.13.

### To Reproduce

1. New > Question > Orders > Visualize
2. Filter > Created at > Fixed date range
3. Focus first input, change the year, tab away

❌ First calendar is not updated

4. Focus second input, change the year, tab away

❌ Second calendar is not updated

### Information about your Metabase installation

master, 6ab4cca8f2500f1a7d419194a8236791ff900b10

### Severity

P3

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #55688 (alternative to #64441)
Fixes #64602

### Description

After updating the test (#55688) I realized it was producing false positives because typing in text inputs did not navigate the calendar. It turned out to be a regression: #64602

Now date range picker text inputs behave like date picker text inputs.

### How to verify

1. New > Question > Orders > Visualize
2. Filter > Created at > Fixed date range
3. Focus first input, change the date

Calendars should navigate as you type valid dates.
Value from first input should be shown in the first calendar.

4. Focus second input, change the date

Calendars should navigate as you type valid dates.
Value from second input should be shown in the second calendar.

### Demo

https://github.com/user-attachments/assets/675bc960-8f99-494c-9813-8d8ef17855e9

### CODE REVIEW

File: frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx [hunk 1]
```diff
@@ -30,6 +30,7 @@ export function DateRangePickerBody({
   const [startDate, endDate] = value;
   const [inProgressDateRange, setInProgressDateRange] =
     useState<DatesRangeValue | null>(value);
+  const [date, setDate] = useState(startDate);
```
Comment (ranquild) [inline frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx]: Let's rename it to something more specific. Maybe `calendarDate`?

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx (hunk 1 above)
Comment (kamilmielnik) [reply frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx]: Mantine says `date` prop is "Displayed date in controlled mode", so I went with `displayedDate`.

365e61cdfa6a2c54f3a1948cfb4473bf75c35ce8
