### PR TITLE
Fix cannot select fields for double aggregations

### LINKED ISSUE #27462: Cannot select fields for double aggregated metrics, and existing sections gets removed on change
**Describe the bug**
It's not possible to select fields for double aggregation, and existing questions will drop the double aggregation metrics on modification.
Regression since 0.45.0

**To Reproduce**
1. Question > Sample > Products
2. Summarize Count by Category
3. Double aggregation summarize, try selecting Sum of Count, no metrics will be available
image

For already existing questions, just viewing the question will show several browser console logs `Removing invalid MBQL clause 
Array [ "sum", (3) […] ]`, and making question changes (example add sort or changing a filter) will drop the second summarize section.
Note, for the existing test question, there's 15 `Warning: can't clean query without metadata!` in 44.6, while there's only a single in 45.1, which seems to indicate that there's too much cleanup going on in the frontend.

**Information about your Metabase Installation:**
Tested 0.44.6 thru 0.45.1. Regression since 0.45.0

Seems related to #24839, as it causes the same problem.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by WiNloSt**
Fixes #27462

The fix follows the behavior before we change it accidentally in #25267, I assume.

#### The problem
The problem is that there’s no field options showing for double aggregation. 
 I tracked down to this line of code.
https://github.com/metabase/metabase/blob/f1d355d4f8d907ec7d0851743fac3f07461597b9/frontend/src/metabase/query_builder/components/AggregationPopover/AggregationPopover.jsx#L379

From here the `query.aggregationFieldOptions` will call `this.fieldOptions` which calls `this.dimensionOptions` under the hood. However, on both version (44.6 vs master or 45) `this.dimensionOptions` will return different **count** dimension (which is the first aggregation from “products -> count by category”).

On master we the dimension's field source would be `aggregation` (which cause the bug). But on 44.6 the field source would be `fields` which make **count** appear when being populated in `query.aggregationFieldOptions`
- image
- 
image

#### How to test
Follow the repro steps in https://github.com/metabase/metabase/issues/27462

### CODE REVIEW

File: frontend/src/metabase-lib/queries/utils/structured-query-table.ts [hunk 1]
```diff
@@ -50,6 +50,7 @@ function getFieldsForSourceQueryTable(
     const virtualField = createVirtualField({
       ...column,
       id,
+      source: "fields",
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/queries/utils/structured-query-table.ts:53]: This is what we missed from https://github.com/metabase/metabase/pull/25267. I'm not sure if this code is intended to fix it or not. But after that PR, the field source for **Count** would be `aggregation` which sounds more correct to me, but would produce the bug. Forcing the field source to be `fields` would follow the old behavior, thus fixing the regression.

File: frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx [hunk 2]
```diff
@@ -254,9 +255,10 @@ const ActionButton = ({
       iconVertical={large}
       iconSize={large ? 18 : 14}
       onClick={onClick}
+      aria-label={label}
```
Comment (WiNloSt) [inline frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx:258]: So, `findByRole("option", { name: "xxx" })` would work, since there's also an icon in front of the next which makes its way into the accessibility name.

File: frontend/test/metabase/scenarios/question/reproductions/27462-no-field-options-for-double-aggregations.cy.spec.js [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+          breakout: [["field", PRODUCTS.CATEGORY, null]],
+        },
+      },
+      display: "table",
+      visualization_settings: {},
+    };
+
+    visitQuestionAdhoc(questionDetails, { mode: "notebook" });
+
+    cy.findByRole("button", { name: "Summarize" }).click();
```
Comment (WiNloSt) [inline frontend/test/metabase/scenarios/question/reproductions/27462-no-field-options-for-double-aggregations.cy.spec.js:31]: Follow Kent's advice to use `*ByRole` most of the time if possible.

File: frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx [hunk 4]
```diff
@@ -120,6 +120,7 @@ export const AccordionListCell = ({
     content = (
       <ListCellItem
         data-testid={itemTestId}
+        aria-label={name}
```
Comment (WiNloSt) [inline frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx:123]: Make this component more accessible and able to be found by `*ByRole("option", {name: "xxx"})`

File: frontend/test/metabase/scenarios/question/reproductions/27462-no-field-options-for-double-aggregations.cy.spec.js (hunk 3 above)
Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/question/reproductions/27462-no-field-options-for-double-aggregations.cy.spec.js:31]: `cy.button()` abstraction does exactly this.

Comment (WiNloSt) [reply frontend/test/metabase/scenarios/question/reproductions/27462-no-field-options-for-double-aggregations.cy.spec.js:31]: @nemanjaglumac Ah nice! Thanks for letting me know that. I actually saw we used `cy.button` in a couple of places, but totally forget about that this time.

A few more questions about that. Let's say we want to create a new test helper.
1. What's a good indicator that that function should exist as a helper? e.g. it's used in multiple places and has certain criteria, otherwise, we could end up with a lot of helpers that are rarely used.
2. If it should be a helper should we use `Cypress.Commands.add` or create them in `__support__/e2e/helpers` and import them directly? And do both of them have their place or should we favor one over another and why?

Comment (WiNloSt) [reply frontend/test/metabase/scenarios/question/reproductions/27462-no-field-options-for-double-aggregations.cy.spec.js]: Thank you. This is really helpful.

**Review by ranquild — APPROVED** [review]

**Comment by ranquild** [comment]
@WiNloSt You'd need to backport this PR as well

**Comment by WiNloSt** [comment]
@ranquild Thanks! 🤦 I somehow thought this is a new feature when it was clearly fixing a regression.
