### PR TITLE
Fix postgres bytea truncation

### LINKED ISSUE #30671: Postgres bytea columns are truncated to show only the first 4 bytes in Question results
### Describe the bug

When Metabase queries a `bytea` type column in Native SQL or GUI questions, the results are truncated displaying only the first 4 bytes of the value.

- No indication that the value is incomplete is given, so this can lead to incorrect results for `bytea` values longer than 4 bytes.

Workarounds:
- Use Native SQL questions only and cast the `bytea` column to `varchar` or similar
- Create a view casting the `bytea` column to `varchar` or similar and use that instead of the table.

### To Reproduce

1. Create a Postgres table with a bytea column and insert some data more than 4 bytes long like:
```sql
create table public.table_with_bytea
(
    id           serial
        constraint table_with_bytea_pk
            primary key,
    varchar_col  varchar,
    bytea_column bytea
);

INSERT INTO
    table_with_bytea (varchar_col, bytea_column)
VALUES
    ('mno131415', '\x900000000000810074123E9DB008AB5C'),
    ('pqr161718', '\x900000000000475000DE4EC0C0A920AB');

```

2. Create a Native SQL Question to query the table in Metabase like `SELECT * FROM table_with_bytea`, see that the `bytea_column` has truncated values:
image

3. Create a GUI question on the same table selecting all columns, see that the `bytea_column` has truncated values:
image

### Expected behavior

Expect to see full bytea displayed similar to results when running a native query against the database with another client.

### Logs

#N/A - no errors or warnings

### Information about your Metabase installation

```JSON
- Metabase version: v1.46.2
- Database and version: Postgres 11
```

### Severity

P2

### Additional context

- Related to:
  - https://github.com/metabase/metabase/issues/1723

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/30671

### Description

Gets the byte array and converts it to a string, similar to what psql does. 

```
metabase=# select * from table_with_bytea;
 id | varchar_col |            bytea_column            
----+-------------+------------------------------------
  1 | mno131415   | \x900000000000810074123e9db008ab5c
  2 | pqr161718   | \x900000000000475000de4ec0c0a920ab
```

### How to verify

See repro steps in issue. You should now see byte array as a string. 

### Demo

https://github.com/user-attachments/assets/b243b4e3-0859-4eb2-b79e-ead0fd4c457d

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/driver/postgres_test.clj [hunk 1]
```diff
@@ -1936,3 +1936,26 @@
...
                 (-> results :data :rows deref first)))))))
+
+(defn- hex->bytes [hex]
+  (->> (partition 2 hex)
+       (map #(apply str %))
+       (map #(Integer/parseInt % 16))
+       (map unchecked-byte)
+       byte-array))
+
+(deftest bytea-column-not-truncated-test
```
Comment (bshepherdson) [inline test/metabase/driver/postgres_test.clj:1946]: "Not truncated" sounds ominous but it's not clear what the bad case looks like. Better to have the issue reference here as well, since this is where someone will end up if they break the functionality :)

**Review by bshepherdson — APPROVED** [review]
