### PR TITLE
Do not break waterfall when there is 0 in the series

### LINKED ISSUE #16246: Bug in values on data points for waterfall charts
**Describe the bug**
Waterfall charts values on data point are not accurate when there is a **0** in the table.

**To Reproduce**
1. Go to the query editor
2. Run 
```
SELECT * FROM (
VALUES 
('a',2),
('b',1),
('c',-0.5),
('d',-0.5),
('e',0.1),
('f',0),
('g', -2)
)
```
3. Choose Waterfall Charts
4. Show values on data points

**Expected behavior**
The values on data points should be the series of number from the table, including the **0** on **f** in the example.

**Observed behavior**
Instead of a 0, we get the cumulative sum (2.1 in this example). It also breaks the **total**.

**Screenshots**
image

**Severity**
It prevents us from integrating these charts in important reports.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_282-b08",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_282",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.282-b08",
    "os.name": "Linux",
    "os.version": "4.14.231-173.360.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.0",
      "date": "2021-02-16",
      "branch": "release-x.38.x",
      "hash": "471aa51"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by ariya**
This shall fix #16246.

Run the E2E tests:
```
yarn test-cypress-no-build --spec frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
```

Manual steps to try (copied from #16246):
1. Ask a question, Native query
2. Type the following SQL query and then Run query (Ctrl+Enter):
```
SELECT * FROM (
VALUES 
('a',2),
('b',1),
('c',-0.5),
('d',-0.5),
('e',0.1),
('f',0),
('g', -2)
)
```
3. Visualization, Waterfall
4. Settings, Display, Show values on data points

**Before this PR**

image

**After this PR**

image

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
This works for zero, but seems to have similar problem with nulls
```
SELECT * FROM (
VALUES 
('a',2),
('b',1),
('c',-0.5),
('d',-0.5),
('e',null),
('f',0),
('g', -2)
)
```
image

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js [hunk 1]
```diff
@@ -893,7 +893,7 @@ export default function lineAreaBar(
 
   datas.map(data => {
     data.map(d => {
-      if (d._waterfallValue) {
+      if (typeof d._waterfallValue === "number") {
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js:896]:
```suggestion
      if (isFinite(d._waterfallValue)) {
```

It handles null as 0 and solves the issue Flamber found

Comment (ariya) [reply frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js:896]: Shouldn't it be [Number.isFinite](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite) instead?

Comment (ariya) [reply frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js:896]: I stand corrected, we actually do *not* want `Number.isFinite` since it won't treat null as 0.

Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js]: Yes, maybe it is a bit implicit but works

**Review by alxnddr — APPROVED** [review]
LGTM 👍

**Comment by ariya** [comment]
> This works for zero, but seems to have similar problem with nulls

Thanks for this edge case @flamber! I've added a new tweak to account for that.
