### PR TITLE
Restore theme preference after login

### LINKED ISSUE #66874: Dark mode - Account Settings / Theme preference resets to “Use system default” after logout/login
### Describe the bug

After changing the preference in Account Settings → Theme (Dark / Light / Use system default), the selection is not persisted across logout/login. 

After logging out, the UI falls back to the system/browser theme (e.g., Dark). 
After logging back in, the theme continue to follows the system theme and the saved preference in Account Settings is reset to Use system default.

### To Reproduce

1. Set your OS/browser theme to Dark (system-level dark mode enabled).
2. Sign in
3. Go to Account Settings → Theme.
4. Select Light, and see the UI switches to Light immediately.
5. Log out.
6. The logged-out UI appears dark again (system default).
7(!). Sign back in, and see the UI continues to be dark.
8(!). In Account Settings → Theme observe it is reset to Use system default.

### Expected behavior

The pereference should be kept across logouts / logins.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "athena",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-12-11",
      "tag": "v1.57.6.1",
      "hash": "7b1a438"
    },
    "settings": {
      "report-timezone": "Australia/Melbourne"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Sever, affects a widely visible feature.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gantoreno**
Closes #66874

### Description

The colorscheme appearance of the app is determined at page load time, where the server injects the colorscheme preference (which is a user setting). In the case of a sign-out, the page gets fully reloaded and the app defaults to `auto`, and this value is preserved even after logging back in, because post-login navigation is client-side, and doesn't reload the page.

This results in the app preserving the `auto` appearance until the window gets refreshed, which isn't ideal. This PR implements colorscheme preference restoration immediately after authentication.

### How to verify

Follow the steps described in #66874:

> 1. Set your OS/browser theme to Dark (system-level dark mode enabled).
> 2. Sign in
> 3. Go to Account Settings → Theme.
> 4. Select Light, and see the UI switches to Light immediately.
> 5. Log out.
> 6. The logged-out UI appears dark again (system default).

Then verify the following:

- Sign back in, and see the UI is back to being Light.
- In Account Settings → Theme observe it is set to Light.

### Demo

https://github.com/user-attachments/assets/17507fb4-93b9-4ac3-938b-c8e3205512d5

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/ui/components/theme/ColorSchemeProvider/ColorSchemeProvider.tsx [hunk 1]
```diff
@@ -57,6 +58,11 @@ export function ColorSchemeProvider({
   const [colorScheme, setColorScheme] = useState<ColorScheme>(
     defaultColorScheme || "auto",
   );
+
+  useEffect(() => {
+    setColorScheme(defaultColorScheme);
+  }, [defaultColorScheme]);
```
Comment (iethree) [inline frontend/src/metabase/ui/components/theme/ColorSchemeProvider/ColorSchemeProvider.tsx:73]: maybe worth adding a comment describing when/how the default color scheme chan change

**Review by iethree — APPROVED** [review]
😍

File: frontend/src/metabase/ui/components/theme/ColorSchemeProvider/ColorSchemeProvider.tsx (hunk 1 above)
Comment (gantoreno) [reply frontend/src/metabase/ui/components/theme/ColorSchemeProvider/ColorSchemeProvider.tsx:73]: Nice tip! Added via https://github.com/metabase/metabase/pull/66892/commits/de44cfc861cab409f2941202d2553f989d6389de

Comment (iethree) [reply frontend/src/metabase/ui/components/theme/ColorSchemeProvider/ColorSchemeProvider.tsx:73]: I wonder if this is causing additional re-renders, which might be failing tests?

File: frontend/src/metabase/lib/settings.ts [hunk 2]
```diff
@@ -108,6 +108,14 @@ class MetabaseSettings {
...
   }
 
+  /**
+   * @deprecated remove an event listener
+   */
+  off(key: SettingKey, callback: SettingListener) {
+    this._listeners[key] =
+      this._listeners[key]?.filter((c) => c !== callback) || [];
+  }
+
```
Comment (iethree) [inline frontend/src/metabase/lib/settings.ts:118]: 😬  not a fan. I really want to get rid of MetabaseSettings, not expand its usage

**Review by iethree — APPROVED** [review]
don't love the metabaseSettings approach, but it makes sense for now 👍 

let's make sure we schedule follow up work to make sure that the providers in our storybook accurately reflect the way the app works.
