### PR TITLE
Only try to parse temporal values during xlsx export when effective type is temporal

### LINKED ISSUE #29708: Incorrect data types for numeric values in text fields exported to Excel via subscription attachment
**Describe the bug**
Tables with numeric values in text fields, sometimes are using the incorrect data types when exported to Excel, but only in the subscription attachment. If the same table is exported manually, it works fine.

**Logs**
No errors in the log.
image

**To Reproduce**
1. Create a new SQL Query. I've tested against a postgresql server, and the H2 sample database.
2. Use the following query:
`select
    '0001' as "this_is_not_-1",
    '4161' as "this_is_not_a_date",
    '02' as "this_is_not_an_hour"`

4. Export the result to Excel. The 'number format' is General, and the text shows as expected.
image

6. Save the query, and add it to a new dashboard.
7. Once in the dashboard click Save -> Subscriptions -> Email
8.  Add your user in the 'To:' field, and select to attach the result table in .xlsx format.
9. Click on 'Send email now', get email and check the attachment.
10. The 'number format' is not General, and the text has been converted to some other format.
image

**Expected behavior**
Both results should be the same, treating the numeric strings as text.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "5.15.0-56-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "postgres",
      "csv",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-28",
      "tag": "v0.46.0",
      "branch": "release-x.46.x",
      "hash": "0ca7df3"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
For us, it's just annoying. As a workaround, we are sending csv files in the subscriptions. It requires some extra steps from our users, but the format is ok.

### PR DESCRIPTION
**Pull request by noahmoss**
Resolves https://github.com/metabase/metabase/issues/29708

The issue boils down to this:
* During normal queries, the format-rows middleware will convert any temporal types to a string in the appropriate timezone.
* During export queries, this middleware is skipped, since each export type handles formatting differently.
* Subscription attachments are executed as normal queries, then the data is separately streamed through the XLSX export code to generate the attachments. This means that the format-rows middleware is included during the query execution, and all temporal values end up as plain strings during XLSX generation.
* Thus, we need to parse these values back to timestamps. However, we were attempting to parse every value, resulting in some strings being unintentionally interpreted as timestamps. I _think_ that checking the `:effective_type` to determine whether we parse the value is what we want here instead.

### CODE REVIEW

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 1]
```diff
@@ -412,6 +412,15 @@
   formatting can be applied. This should be enabled for generation of pulse/dashboard subscription attachments."
   false)
 
+(defn- maybe-parse-temporal-value
+  [value col]
+  (when (and *parse-temporal-string-values*
+             (isa? (:effective_type col) :type/Temporal)
+             (string? value))
+    (try (u.date/parse value)
```
Comment (john-metabase) [inline src/metabase/query_processor/streaming/xlsx.clj:420]: I think that we have enough info available to be fairly confident and drop the `try` here.

Comment (noahmoss) [reply src/metabase/query_processor/streaming/xlsx.clj:420]: I'm a bit wary of that, because I could imagine a column incorrectly having a temporal type but actually being a non-parsable string value. Not sure if that's likely, but if an exception is thrown here it renders the entire export invalid, so I think it's safer to keep the `try`

File: test/metabase/query_processor/streaming/xlsx_test.clj [hunk 2]
```diff
@@ -451,7 +451,13 @@
            (second (xlsx-export [{:id 0, :name "Col"}] {} [["2020-03-28T10:12:06.681"]]))))
     (binding [qp.xlsx/*parse-temporal-string-values* true]
       (is (= [#inst "2020-03-28T10:12:06.681"]
-             (second (xlsx-export [{:id 0, :name "Col"}] {} [["2020-03-28T10:12:06.681"]]))))))
+             (second (xlsx-export [{:id 0, :name "Col" :effective_type :type/Temporal}]
+                                  {}
+                                  [["2020-03-28T10:12:06.681"]]))))
+      (is (= ["2020-03-28T10:12:06.681"]
```
Comment (dpsutton) [inline test/metabase/query_processor/streaming/xlsx_test.clj:457]: Suggestion: add the offending values from the original ticket to ensure that they work correctly, and a ticket number in the `testing` block:

```clojure
      (testing "Text values that are parseable as dates are not when effective_type is not temporal (#29708)"
        (doseq [value ["0001" "4161" "02" "2020-03-28T10:12:06.681"]]
          (is (= [value]
                 (second (xlsx-export [{:id 0, :name "Col" :effective_type :type/Text}]
                                      {}
                                      [[value]]))))))
```

**Review by dpsutton — APPROVED** [review]
