### PR TITLE
Fix #12140

### LINKED ISSUE #12140: The expression editor shouldn't start in error mode without any user input
**Describe the bug**
Right now when you try to create a custom expression or custom column once the editor opens it starts off in an error state even though you haven't entered any input yet. This makes me think I'm bad at expressions, when I really don't even know if I am yet. (I am).

**To Reproduce**
1. Go to the notbook
2. Select any data source and try and create a custom column or aggregation.
3. The expression editor input field will have a red border and an error message shows if you click out of it to hide the suggestion list.

**Expected behavior**
The expression editor should be in a non angry state to begin.

**Screenshots**
Screen Shot 2020-03-16 at 3 30 46 PM

**Information about your Metabase Installation:**
```{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Mac OS X",
    "os.version": "10.15.3",
    "user.language": "en",
    "user.timezone": "America/Los_Angeles"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "tag": "v0.35.0-rc1",
      "hash": "37b3f82",
      "branch": "fix-12139",
      "date": "2020-03-16"
    },
    "settings": {
      "report-timezone": null
    }
  }
}```

### PR DESCRIPTION
**Pull request by camsaul**
I was working on #13175 and ran into some issues trying to test stuff so I ended up fixing #12140 while working on it.

Fixes #12140

I thought `ExpressionEditorTextfield` was way too hairy so I split off the suggestions popover code into its own component. The version of the widget used in notebook mode didn't show error messages for whatever reason so I moved the error display code from the version of the widget used in the other place into `ExpressionEditorTextfield` itself so now it shows errors in both cases.

I fixed behavior so it doesn't try to parse empty input and display parse errors when there is no input.

### CODE REVIEW

**Comment by ariya** [comment]
Note that the specific test that caused the failure above (fe-tests-cypress-3-oss) is already temporarily quarantined/skipped in the master branch due to its own flakiness.

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx [hunk 1]
```diff
@@ -86,18 +133,20 @@ export default class ExpressionEditorTextfield extends React.Component {
...
       const source = format(newProps.expression, parserOptions);
 
-      const { expression, compileError, syntaxTree } = this._processSource({
-        source,
-        ...this._getParserOptions(newProps),
-      });
-
+      const { expression, compileError, syntaxTree } =
+        source &&
+        source.length &&
```
Comment (paulrosenzweig) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx:138]: I don't think this guard will work since `const { foo } = undefined` will fail. Maybe that should be an early return at the start of `processSource`?

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx [hunk 2]
```diff
@@ -318,104 +354,13 @@ export default class ExpressionEditorTextfield extends React.Component {
...
-                    ) : (
-                      suggestion.name
-                    )}
-                  </li>,
-                ],
-              )}
-            </ul>
-          </Popover>
-        ) : null}
+        <Errors compileError={compileError} />
```
Comment (paulrosenzweig) [inline frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx:357]: It looks like this is new. Are these understandable errors to display?

**Review by paulrosenzweig — APPROVED** [review]
Nice extractions!

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx (hunk 2 above)
Comment (camsaul) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx:357]: There are two expression widgets, both of which wrap `ExpressionEditorTextfield`. `ExpressionPopover` which is used in basic QB mode (?) and a different widget used in the notebook mode. Only `ExpressionPopover` had code for displaying any errors -- they weren't displayed in notebook mode -- so I moved the error display code into `ExpressionEditorTextfield` so they'd display in both places. Take a look at the screenshots posted in #13175 -- the error messages weren't showing up in both places originally

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx (hunk 1 above)
Comment (camsaul) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx:138]: yeah, that makes sense

File: frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx (hunk 2 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx:357]: 👍 sweet makes sense
