### PR TITLE
User with view collection perms can create Alerts

### LINKED ISSUE #13908: Users with view-only Collection permissions cannot create Alerts for questions
**Describe the bug**
Users with view-only Collection permissions cannot create Alerts for questions

**To Reproduce**
1. Admin > People > Create a user "U1"
2. Admin > Permissions - revoke data on Sample Dataset for "All users" - set collection "Our analytics" to View-only.
3. Simple question > Sample Dataset > Orders summarize Count by CreatedAt:Year - save as "Q1" in "Our analytics"
4. Login as "U1" and go to "Q1" and click :bell: icon in lower-right corner and click Done in the alert fullscreen overlay
5. The question refreshes, but no alerts are created - the log contains the following:
```
2020-11-27 18:45:22,715 DEBUG middleware.log :: GET /api/pulse/form_input 200 723.7 µs (0 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (2 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued)
2020-11-27 18:45:26,568 WARN middleware.log :: PUT /api/card/289 403 30.8 ms (11 DB calls) 
"You don't have permissions to do that."

2020-11-27 18:45:26,694 DEBUG middleware.log :: GET /api/card/289 200 9.4 ms (6 DB calls) App DB connections: 2/10 Jetty threads: 4/50 (3 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued)
2020-11-27 18:45:26,788 DEBUG middleware.log :: GET /api/alert/question/289 200 1.5 ms (1 DB calls) App DB connections: 1/10 Jetty threads: 4/50 (3 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued)
2020-11-27 18:45:26,820 WARN middleware.log :: GET /api/table/11/query_metadata 403 4.6 ms (3 DB calls) 
"You don't have permissions to do that."

2020-11-27 18:45:27,016 DEBUG middleware.log :: POST /api/card/289/query 202 [ASYNC: completed] 132.6 ms (10 DB calls) App DB connections: 1/10 Jetty threads: 3/50 (3 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued)
```

**Expected behavior**
1. Possible for a user without data permissions to create alerts - including for view-only questions?
2. A user creating an alert should not create a card revision history - when a user unsubscribes from an alert, then it does not create a revision history

**Information about your Metabase Installation:**
Tested 0.34.3 thru 0.37.2

Related to #11719

### PR DESCRIPTION
**Pull request by qnkhuat**
Fix #13908 by changing permission to allow users with permissions to view collection to call:
- `POST /api/alert`
- `PUT /api/alert/:id` can update the alert but will 403 if attempts to update card

I also make a change in FE in which I remove the call to `PUT /api/card/:id` when creating an alert.
This seems to be a no-op call and should not be a problem to remove (details in [here](https://github.com/metabase/metabase/pull/22364#discussion_r863862561))
FWIW when creating a Pulse, we don't update the dashboard.

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/AlertModals.jsx [hunk 1]
```diff
@@ -109,16 +109,9 @@ export class CreateAlertModalContent extends Component {
...
-      question,
-      createAlert,
-      apiUpdateQuestion,
-      updateUrl,
-      onAlertCreated,
-    } = this.props;
+    const { question, createAlert, updateUrl, onAlertCreated } = this.props;
     const { alert } = this.state;
 
-    await apiUpdateQuestion(question);
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/AlertModals.jsx:121]: I'm no the author of this change, and I believe I've just moved this code from a different place. AFAIK this line couldn't be removed because you might want to create an alert for an unsaved question.

Comment (qnkhuat) [reply frontend/src/metabase/query_builder/components/AlertModals.jsx:121]: that's interesting, I'll take a look.

Comment (qnkhuat) [reply frontend/src/metabase/query_builder/components/AlertModals.jsx:121]: when I click create Alert on an unsaved question, It prompts me to save it first.

So I guess it's ok to remove this?

Comment (ranquild) [reply frontend/src/metabase/query_builder/components/AlertModals.jsx:121]: I don't know all the cases where this modal is used. I'm not the author or owner of this feature, I can't tell for sure.

Comment (ranquild) [reply frontend/src/metabase/query_builder/components/AlertModals.jsx:121]: Do on your own risk I guess.

Comment (qnkhuat) [reply frontend/src/metabase/query_builder/components/AlertModals.jsx:121]: TLDR: I'll move forward with deleting that line.

Okay I chased the origin of this and it's from this [PR](https://github.com/metabase/metabase/pull/6278).
The main author is no longer working with us but some how @iethree is one of the contributor? 

It was implemented 5 years ago so I'd not hope anyone remember the background, but I found this [comment](https://github.com/metabase/metabase/blob/1a391c5e55706a7f506715d663b9efb429af362b/frontend/src/metabase/query_builder/components/AlertModals.jsx#L111), I guess the author's intention here is to save the qs before creating an alert if it's in edit mode ( or maybe it was used for dashboard back then hence the x/y axes )

I've double checked with our current behavior: if we create an alert if a question is either not save, in edit mode, we'll prompt user to save the Question first.

So I believe remove that line is totally safe.

Comment (iethree) [reply frontend/src/metabase/query_builder/components/AlertModals.jsx:121]: haha. there was a former ryan@metabase.com (4 years ago) and somehow I got credit for all his commits :grin: I probably won't be much help here.

**Review by noahmoss — APPROVED** [review]
BE changes lgtm
