### PR TITLE
Persist selected theme in account settings

### LINKED ISSUE #65665: Dark Mode is displayed by default in Firefox in v57
### Describe the bug

If you open v57 in Chrome or IE you land on a light mode login page. If you open in Firefox you get a dark mode landing page.

### To Reproduce

1. Set up Metabase v57.1
2. Go to chrome and note the UI is in light mode
3. Look at user profile settings and note the profile is set to use the default theme
4. Go it Firefox and see dark mode login page

### Expected behavior

We should default to light mode 

### Logs

_No response_

### Information about your Metabase installation

```JSON
v57 beta, 57.1 and stats
```

### Severity

confusing

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deniskaber**
Closes https://github.com/metabase/metabase/issues/65665 / UXW-2257

### Description

Describe the overall approach and the problem being solved.

### How to verify

1. Open Chrome, set dark theme in account settings.
2. Open Firefox / Safari, login as same user, check account settings - theme should be set to "dark".

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by bpander — COMMENTED** [review]
Overall I think this looks and works well. I was especially worried about a flash of the opposite theme on load (e.g. when your system theme is the opposite of your profile setting), but it's working about as well as we can expect.

Just had a question and a comment.

Question: mainly just leaving a paper trail, I noticed it uses a `PUT()` utility rather than `useUpdateSettingMutation`. I'm guessing there was like a circular dependency or something that prevented the latter?

Comment: Why does this PR _add_ some "metabase-color-scheme" stuff (in user_settings.cy.spec)? With these changes, "metabase-color-scheme" shouldn't be used at all anymore right? If so, we should remove the rest of the "metabase-color-scheme" vestiges.

**Comment by deniskaber** [comment]
> Overall I think this looks and works well. I was especially worried about a flash of the opposite theme on load (e.g. when your system theme is the opposite of your profile setting), but it's working about as well as we can expect.
> 
> Just had a question and a comment.
> 
> Question: mainly just leaving a paper trail, I noticed it uses a `PUT()` utility rather than `useUpdateSettingMutation`. I'm guessing there was like a circular dependency or something that prevented the latter?
> 
> Comment: Why does this PR _add_ some "metabase-color-scheme" stuff (in user_settings.cy.spec)? With these changes, "metabase-color-scheme" shouldn't be used at all anymore right? If so, we should remove the rest of the "metabase-color-scheme" vestiges.

You are absolutely right! 😏 
1 - We have to use raw `PUT()` call to avoid circular dependencies that break page load and e2e tests.

2 - Idea was to emulate that we don't rely on old behavior that uses localStorage. I will try to clean whole localStorage/sessionStorage rather than a single key.

File: frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx [hunk 1]
```diff
@@ -163,8 +171,35 @@ export const ThemeProvider = (props: ThemeProviderProps) => {
...
+  );
+  const isLoadingSettings = useSelector(getSettingsLoading);
+
+  const defaultColorScheme = ["light", "dark", "auto"].includes(
+    savedColorScheme as ColorScheme,
+  )
+    ? (savedColorScheme as "light" | "dark" | "auto")
+    : undefined;
+
+  const handleUpdateColorScheme = useCallback(async (value: ColorScheme) => {
```
Comment (npfitz) [inline frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx:174]: Can we use the `useUpdateSettingMutation` here instead of hitting the bare PUT request?

**Review by npfitz — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx (hunk 1 above)
Comment (npfitz) [reply frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx:174]: Just saw your thread with @bpander

Comment (npfitz) [reply frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx:174]: The Circular dependency actually exists regardless, but it can be solved by exporting ThemeProvider (and other theme things) from `metabase/ui/index`, not from `metabase/ui/components/index`. Some additional info is in Slack

Comment (npfitz) [reply frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx:174]: Looks like this isn't very straightforward. I'll approve since this is a cloud blocker, but I've created [UXW-2402: Color Scheme Provider should use RTK Query for api calls, not PUT](https://linear.app/metabase/issue/UXW-2402/color-scheme-provider-should-use-rtk-query-for-api-calls-not-put) to come back to this in the future

**Review by npfitz — APPROVED** [review]

File: src/metabase/server/routes/index.clj [hunk 2]
```diff
@@ -89,6 +90,7 @@
      :siteLocalizationJSON   (escape-script (load-localization (system/site-locale)))
      :nonceJSON              (escape-script (json/encode nonce))
      :language               (hiccup.util/escape-html (or (i18n/user-locale-string) (system/site-locale)))
+     :userColorScheme        (escape-script (json/encode (users-settings/color-scheme)))
```
Comment (deniskaber) [inline src/metabase/server/routes/index.clj:93]: We need to pass user's selected color scheme in html template, but this import is banned in linter. Not sure how to refactor that.

Comment (johnswanson) [reply src/metabase/server/routes/index.clj:93]: I just fixed this - we needed to add `users` to the list of modules that the `server` module is allowed to use.

**Review by johnswanson — APPROVED** [review]
BE looks good to me!
