### PR TITLE
Fix rendering of "Ends with" button on Safari

### LINKED ISSUE #5075: `Ends with` filter button text wrapping in Safari/Mac app
screen shot 2017-05-10 at 3 12 40 pm

### PR DESCRIPTION
**Pull request by attekei**
Fixes #5075

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/filters/OperatorSelector.jsx [hunk 1]
```diff
@@ -39,6 +41,15 @@ export default class OperatorSelector extends Component<*, Props, State> {
         onOperatorChange: PropTypes.func.isRequired
     };
 
+    expandOperators = () => {
+        this.setState({ expanded: true });
+
+        // HACK: Address Safari rendering bug which causes https://github.com/metabase/metabase/issues/5075
+        setTimeout(() => {
```
Comment (tlrobinson) [inline frontend/src/metabase/query_builder/components/filters/OperatorSelector.jsx]: I think you can pass this as a callback to `setState` (2nd arg) and it will do the same thing.

File: frontend/src/metabase/lib/dom.js [hunk 2]
```diff
@@ -208,3 +208,10 @@ export function constrainToScreen(element, direction, padding) {
     }
     return false;
 }
+
+// Used for tackling Safari rendering issues
```
Comment (tlrobinson) [inline frontend/src/metabase/lib/dom.js]: If you found a page describing this problem and solution it would be good to link to it.

File: frontend/src/metabase/query_builder/components/filters/OperatorSelector.jsx (hunk 1 above)
Comment (attekei) [inline frontend/src/metabase/query_builder/components/filters/OperatorSelector.jsx]: Cool, will do that

File: frontend/src/metabase/lib/dom.js (hunk 2 above)
Comment (attekei) [inline frontend/src/metabase/lib/dom.js]: Whoops. Was intending to do that but forgot

**Review by mazameli — APPROVED** [review]
Looks good!

screen shot 2017-05-12 at 11 43 16 am
