### PR TITLE
Potentially fix StackOverflow in flaky tests

### LINKED ISSUE #32356: BE Flake: `fetch-logs-test`
## Error
```
ERROR in metabase-enterprise.advanced-config.api.logs-test/fetch-logs-test (AFn.java:148)
Uncaught exception, not in assertion.

java.lang.StackOverflowError: 
```

### Postgres
- https://github.com/metabase/metabase/actions/runs/5517779878/jobs/10060878523?pr=32173#step:4:408
- https://github.com/metabase/metabase/actions/runs/5386767028/jobs/9777220183?pr=31887#step:4:410
- https://github.com/metabase/metabase/actions/runs/5478588617/jobs/9979271493#step:4:410

### MySQL
- https://github.com/metabase/metabase/actions/runs/5445139775/jobs/9903968768?pr=32084#step:4:411

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #32356

(hopefully)

The root issue here was that inserting a User would insert a couple of PermissionsGroupMemberships which would in turn trigger an update of User... Not 100% sure why this was causing a StackOverflow TBH since the PGM insert did not trigger any further Toucan calls, but at any rate we can eliminate the pointless call here and hopefully fix the StackOverflow. 

I also combined the separate inserts into one call which should very slightly improve performance in tests and when creating new admins

### CODE REVIEW

File: src/metabase/models/permissions_group.clj [hunk 1]
```diff
@@ -106,10 +106,10 @@
...
   [group]
   (let [changes (t2/changes group)]
-   (u/prog1 group
-     (check-not-magic-group group)
-     (when-let [group-name (:name changes)]
-       (check-name-not-already-taken group-name)))))
+    (u/prog1 group
+      (check-not-magic-group group)
+      (when-let [group-name (:name changes)]
+        (check-name-not-already-taken group-name)))))
```
Comment (camsaul) [inline src/metabase/models/permissions_group.clj:112]: Indentation fix

**Review by qnkhuat — APPROVED** [review]
