### PR TITLE
Normalize :temporal_units in action, card, and dashboard entries

### LINKED ISSUE #50371: Customizing grouping options for time group filter breaks some functionality (Ex: Publishing Static Dashboards)
### Describe the bug

If you add a time group filter to a dashboard and then customize the "Time Grouping Options" for the filter you can save it. But you cannot subsequently publish the changes to embedded dashboards, move the dashboard to trash, etc. Seems we're sending malformed requests to '/api/dashboard/id'.

### To Reproduce

1. Set up a dashboard
2. Add time group filter
3. See that you can publish the static dashboard
4. Edit the dashboard and customize the "time grouping options" for the filter
5. See that you cannot publish the embedding changes, put the dashboard in the trash, drill into questions, duplicate the dashboard, etc.

https://www.loom.com/share/31b9bad1317b494185c0c093a89ee0de

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
v51.3
```

### Severity

Blocking

### Additional context

If you add all options back to the time filter settings the UX is still broken. As a workaround you can remove the filter completely, add it back and save it without customizing granularity.

### PR DESCRIPTION
**Pull request by metamben**
Fixes #50371

### Description

The `:parameters` field was normalized according to the legacy parameters schema, which resulted in `:temporal_units` not getting converted to keywords.

I've marked a few tests as `:^parallel`. This is not really relevant for the bug fix.

### How to verify

Use the steps from #50371 and check out the new test in `test/metabase/api/dashboard_test.clj`.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/models/interface.clj [hunk 1]
```diff
@@ -216,6 +217,17 @@
   (or (mbql.normalize/normalize-fragment [:parameters] parameters)
       []))
 
+(defn- keywordize-temporal_units
+  [parameter]
+  (m/update-existing parameter :temporal_units (fn [units] (mapv keyword units))))
+
+(defn normalize-card-parameters-list
```
Comment (metamben) [inline src/metabase/models/interface.clj:224]: This is not a good name. Enumerating the places where it's used is not good either.

**Review by ranquild — APPROVED** [review]

**Review by bshepherdson — APPROVED** [review]
