### PR TITLE
Fix ID column & null value sorting in SimpleTable

### LINKED ISSUE #13135: Table widget sorting in dashboards doesn't appear consistent for string columns with nulls
**Describe the bug**
When manually ordering a table question in a dashboard by a column that has null values the ordering doesn't work as expected. I end up with nulls scattered throughout the column, and the non nulls are not sorted.

**Logs**
Not applicable

**To Reproduce**
1. Create new SQL question as a table (or use an existing one that has nulls in string columns)
```SQL
select 'z' as code1, null as descrip
union all
select 'y' as code1, '3' descrip
union all
select null as code1, null descrip
union all
select null as code1, '4' descrip
union all
select 'b' as code1, '09' descrip
```
2. Add it to a dashboard
3. Click the column header of the "code1" field to sort it
4. Note the nulls in the middle, that's not what I expected, and the letters aren't ordered alphabetically
5. Click it again, again note that the order changes, but it's still not correct, it's just wrong in a different way

Note that this happens with questions built using the query builder too, not just native SQL.
Also, number columns appear to behave as expected.

**Expected behavior**
I expect null records to be ordered consistently, either as highest or lowest sort order values (I don't have a strong preference on which one), strings to be ordered alphabetically.

**Screenshots**
Ordered Ascending
image

Ordered Descending
image

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_161-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_161",
    "java.vm.name": "Java HotSpot(TM) Client VM",
    "java.vm.version": "25.161-b12",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.36.2",
      "date": "2020-07-31",
      "branch": "release-0.36.x",
      "hash": "13f0225"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}
```

**Severity**
It's a frustration. For logged in users they can drill into the question and order there which seems to work. But for users accessing via a shared dashboard they have no way of predictably ordering by these columns.

### LINKED ISSUE #20781: Client-side sorting on PK/FK uses alpha instead of numeric ordering
**Describe the bug**
When you try to sort numeric fields (I've tried on PK and FK fields), then sorting doesn't work properly because it doesn't account for tens, hundreds, thousands, etc.

For example, it would sort like this: `1, 10, 100, 1000, 2, 3, 4...`

**Logs**
N/A

**To Reproduce**
1. Save Orders table as a question
2. Embed it and either observe the embedding preview, or go to an actual link for the iframe
3. Click on the header for Orders ID (PK) or a user ID (FK)
4. Note that it doesn't show the popup with possible actions like it does in Metabase app (this is expected) - the only action that's possible is sorting and it happens automatically when you click the header
5. If it sorts the column in ascending order, it puts 10s and 100s immediately after 1

**Expected behavior**
Single digit numbers should always go before two digit numbers, etc. The ascending order should be `1, 2, 3, 4, 5., 10, 20, 100..`

**Screenshots**
image

**Information about your Metabase Installation:**
local dev, `master`, c7573b2bce188946ebcb0685b14b52baf9ffea31, H2, Sample database

**Severity**
P3?

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #20781 
Fixes #13135

ID columns return as strings now, so before sorting, we need to parse them as integers.

`null` values are getting coerced into strings. Looks like underscore makes an exception for `void 0` so converting the `null` into an `undefined` in the sortBy callback fixes the issue: https://github.com/jashkenas/underscore/blob/master/modules/sortBy.js#L19

**Testing**
Follow steps in #20781 and #13135

---

ID sorting:
Screen Shot 2022-04-20 at 4 47 45 PM

null sorting:
Screen Shot 2022-04-20 at 4 47 30 PM

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/TableSimple.jsx [hunk 1]
```diff
@@ -108,9 +108,17 @@ export default class TableSimple extends Component {
...
         let value = rows[rowIndex][sortColumn];
+        const col = cols[sortColumn];
         // for strings we should be case insensitive
         if (typeof value === "string") {
-          value = value.toLowerCase();
+          if (isID(col)) {
+            value = parseInt(value, 10);
+          } else {
+            value = value.toLowerCase();
+          }
```
Comment (kulyk) [inline frontend/src/metabase/visualizations/components/TableSimple.jsx:118]: I suppose it won't work as expected for UUID or any other non-numeric PK. I've tested locally with [the sample MongoDB](https://github.com/metabase/metabase-qa#mongo-4)

1. If a UUID starts with numeric characters, `parseInt` will just extract them and drop the rest which works, but probably doesn't make a lot of sense.
2. If a UUID starts with letters (e.g. `ff2ae2f1-ab0d-45b4-8f8b-604df3ca92e4`), `parseInt` will return `NaN` and we'll probably enter some weird behaviour zone

Should we ensure that when we do `parseInt`, we're certain it is actually a numeric value we're dealing with?

**Example of scenario 1**

`originalValue` is the cell value, `value` is what will be used after `parseInt` and other checks

CleanShot 2022-04-21 at 13 49 26@2x

Comment (daltojohnso) [reply frontend/src/metabase/visualizations/components/TableSimple.jsx]: I've added an additional check to make sure the string is a positive integer: https://github.com/metabase/metabase/pull/21838/commits/70be543e54927a3b363d3aa78ba7783c0cc60140

Screen Shot 2022-04-21 at 10 44 34 AM

**Review by kulyk — APPROVED** [review]
Nice! 🎉
