### PR TITLE
Fix #31447: Remapped fields in native query editor field filters

### LINKED ISSUE #31447: Field Filters generating different results when used from a question vs a dashboard
### Describe the bug
Native SQL ID Field Filters Variables are not searching by Entity Name on Questions.
- on Dashboards
  - searches by Entity Name and NOT by Entity Key
  - returns a list of Entity Names and Entity Keys
- on Questions
  - searches by Entity Key and NOT by Entity Name
  - returns a list of only Entity Keys

#### OP Description:
We recently updated to Metabase 46 and since that upgrade we noticed that our field filters no longer allow us to search by the models name when filtering from the question. It will instead return IDs, but only when you enter a number instead of a string. The behavior is unchanged when accessing those same questions via a dashboard.

### To Reproduce
1. Update the Admin > Table Metadata/Data Model for Sample Database > People to set `Email` as an `Entity Key` and `ID` as `No semantic type`
2. Update the Admin > Table Metadata/Data Model for Sample Database > People to set `Zip` as an `Entity Name` and `Name` as `No semantic type`
3. Create a Native SQL question called `People Question` on the Sample Database as `SELECT * FROM people WHERE {{email}}`
4. Update the `email` variable to be an ID Field Filter on Sample Database > People > Email
5. Save the question and add it to a dashboard
6. Add an ID filter to the dashboard connected to `Email` which is the Entity Key
7. Enter a Zipcode like `82633` into the filter and see that this searches correctly
image

8. Enter an Entity Key in the filter such as `adams.arnold@gmail.com` and see that this filters the results correctly (type it, don't copy and paste, just start with `adam`)
image
image
image

9. Open the Question and enter an Entity Key in the filter (type it, don't copy and paste, just start with `adam`)
  - expect not to show results like in step 8

image
image

10. Enter an Entity Name like `82633`
image

#### OP reproduction steps:
1. Create Question with a field filter for a model that has a primary_key column and a name column. In our case, the ID column is an integer and is marked as the entity key. The name column is a string and marked as the entity name.
2. In the SQL for your question, use a field filter
12. If you query from the question editor it will only allow you to search via IDs (you can no longer see the names)
13. If you insert that same question into a dashboard and add the filter and search for names here it will work as you would expect it to.

### Expected behavior
In both dashboards and questions, ID Field Filter placeholder instruction text states to `Search by [Entity Name] or enter an ID`
image
- Expect to search Entity Names and to accept entered IDs
  - Dashboard works as expected
  - Question does not

### Logs

_No response_

### Information about your Metabase installation

- Browser: *any*
- OS: *any*
- Database: *any*
- Metabase: v1.45.3.1, v0.46.4, v1.46.6, `master` as of `3d2c121d`

### Severity
P1: regression, incorrect instructions vs. behavior, common functionality

### Additional context

Regression: works as expected in v1.44.6.1

### PR DESCRIPTION
**Pull request by calherries**
This PR fixes https://github.com/metabase/metabase/issues/31447

### What caused the bug

The regression began from this PR https://github.com/metabase/metabase/pull/27765, but when `GET /api/card/:card-id/params/:param-key/search/:query` was first used on the FE to search for field filter values instead of `GET /api/field/:field-id/search/:query`. However, the actual new endpoint was first introduced in https://github.com/metabase/metabase/pull/27403, though it was unused initially.

**Before:**
The previously-used endpoint `GET /api/field/:field-id/search/:query` calls `metabase.api.field/search-values` with the original field and a search field (in the remapping case these are different):
https://github.com/metabase/metabase/blob/c546984f5aeba6adbf479c67965668928b771c41/src/metabase/api/field.clj#L439

**After the regression:**
But with the newly created endpoint `GET /api/card/:card-id/params/:param-key/search/:query`, it results in a  call to `metabase.api.field/search-values` with the original field as the search field:
https://github.com/metabase/metabase/blob/c2945ad00db774082afbfb8bfffd5bda9ec0af66/src/metabase/api/field.clj#L278

### The fix

The key change is [here](https://github.com/metabase/metabase/pull/32516/files#diff-bb8506333802dafc8eb7a852ddd43d552ebef22cc989380aa66ea4c974a6f496R259-R269). 

Now a request to `GET /api/card/:card-id/params/:param-key/search/:query` results in a call to `search-values` with a possibly remapped field: `(search-values field search-field query)`

### CODE REVIEW

File: src/metabase/models/params/chain_filter.clj [hunk 1]
```diff
@@ -536,7 +538,7 @@
    :limit  1})
 
 ;; TODO -- add some caching here?
-(s/defn ^:private remapped-field-id :- (s/maybe su/IntGreaterThanZero)
+(s/defn remapped-field-id :- (s/maybe su/IntGreaterThanZero)
```
Comment (calherries) [inline src/metabase/models/params/chain_filter.clj:541]: This is now reused in `metabase.api.field`

File: test/metabase/test/util.clj [hunk 2]
```diff
@@ -517,6 +517,15 @@
                  #(u/round-to-decimals decimal-place %)
                  data))
 
+(defmacro let-url
```
Comment (qnkhuat) [inline test/metabase/test/util.clj:520]: make it available in `mt` too?

File: src/metabase/api/field.clj [hunk 3]
```diff
@@ -408,6 +397,10 @@
 
       [<value-of-field> <matching-value-of-search-field>].
 
+   If `search-field` and `field` are the same, simply return 1-vectors like
```
Comment (qnkhuat) [inline src/metabase/api/field.clj:400]: to confirm: this is how FE understands it too right?

File: src/metabase/api/field.clj [hunk 4]
```diff
@@ -246,47 +247,35 @@
...
-(defn check-perms-and-return-field-values
-  "Impl for `GET /api/field/:id/values` endpoint; check whether current user has read perms for Field with `id`, and, if
-  so, return its values."
-  [field-id]
-  (let [field (api/check-404 (t2/select-one Field :id field-id))]
-    (api/check-403 (params.field-values/current-user-can-fetch-field-values? field))
-    (field->values field)))
-
-;; todo: we need to unify and untangle this stuff
 (defn field-id->values
```
Comment (qnkhuat) [inline src/metabase/api/field.clj:259]: this is a bit confuse given we have `field->values` too.  and `field-id->values` is only used n `api.card`, maybe we should move its definition there?

File: test/metabase/api/card_test.clj [hunk 5]
```diff
@@ -2735,6 +2736,37 @@
...
+                                                           :display_name "ID"
+                                                           :type         :dimension
+                                                           :dimension    [:field (mt/id :venues :id) nil]
+                                                           :required     true}}}}
+                         :name       "native card with ID field filter"
+                         :parameters [{:id     param-key,
+                                       :type   :id,
+                                       :target [:dimension [:template-tag "ID"]],
+                                       :name   "ID",
+                                       :slug   "ID"}]}]
```
Comment (qnkhuat) [inline test/metabase/api/card_test.clj:2757]: nit: I'd have a test `(is (= :type/Name (t2/select-one-fn :semantic_type :model/Field (metabase.test/id :venues :name)))`  for document's sake

**Review by qnkhuat — APPROVED** [review]
LGTM, just have some small suggestions

File: src/metabase/api/field.clj (hunk 4 above)
Comment (calherries) [reply src/metabase/api/field.clj]: Renamed this function to `search-values-from-field-id`. I don't really feel like moving the function to `api.card` is an improvement because it feels more closely coupled with other functions from this namespace like `search-values` and `field->values`. Eventually all the `FieldValues` should probably move to a common namespace so we don't feel like splitting logic between api namespaces

File: src/metabase/api/field.clj (hunk 3 above)
Comment (calherries) [reply src/metabase/api/field.clj:400]: Yes. Here's the type used by the `FieldValuesWidget` for example:
https://github.com/metabase/metabase/blob/567cdb7fe62a59a11ae720bae12c4abbdd4a07aa/frontend/src/metabase-types/api/field.ts#L53
