### PR TITLE
Adjust dependent dashboard cards

### LINKED ISSUE #49202: Editing and saving a question when a dashboard time grouping parameter is applied with new time granularity breaks the parameter wiring
### Describe the bug

If you connect a time grouping widget to a question, select a grouping that different from original, then edit and save the question, the time grouping will not be doing anything anymore.

This can be confusing because someone can go edit the question to, for example, add filters (which is how I ran into this issue) or change chart settings, and it'll break the connection between the parameter widget and the column.

Here's an [example stats dashboard+questions](https://stats.metabase.com/dashboard/2681-time-parameter-testing?time_grouping=quarter)

Disconnecting and reconnecting the widget will fix the issue.

### To Reproduce

1. Create a question Sample DB > Orders > Count of Orders by `Created At: Month`
2. Add the question to a dashboard
3. Add a time grouping widget to the dashboard and connect the widget to `Created At`
5. Save
6. Pick a different time grouping (e.g. week)
7. While the grouping is applied, click on the question to edit it
8. Save the question and pick "replace"
9. Go back to the dashboard
10. Try to change the grouping 
-> doesn't do anything

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

51.1, master

### Severity

P2

### Additional context

https://github.com/user-attachments/assets/6f80cb12-b744-4fc8-ae5b-dc746ec45fb2

### PR DESCRIPTION
**Pull request by lbrdnk**
Closes #49202

### Description

Card can have multiple multiple breakout elements referencing same field or expression, having different  _temporal unit_. Those refs can be targeted by dashboard _temporal unit parameter_. If refs change, and card is saved, _parameter mappings_ have to be updated to target new, modified refs. This PR implements that for the case, where it is certain which ref was modified how.

First mappings of _identifier_ -> _action_ are generated (described in docstrings). Then, dashcards are fetched, updates are generated and executed.

### Tests

Run newly added tests or follow the reproduction steps.

### CODE REVIEW

File: src/metabase/models/card.clj [hunk 1]
```diff
@@ -767,6 +767,112 @@
...
+  (let [card->breakout     #(-> % :dataset_query mbql.normalize/normalize :query :breakout)
+        breakout-before    (card->breakout card-before)
+        breakout-after     (card->breakout card-after)]
+    (when-some [identifier->action (breakouts-->identifier->action breakout-before breakout-after)]
+      (let [dashcards          (t2/select :model/DashboardCard :card_id (some :id [card-after card-before]))
+            updates            (updates-for-dashcards identifier->action dashcards)]
+        ;; Beware. This can have negative impact on card update performance as queries are fired in sequence. I'm not
+        ;; aware of more reasonable way.
+        (doseq [[id update] updates]
+          (t2/update! :model/DashboardCard :id id update))))))
```
Comment (lbrdnk) [inline src/metabase/models/card.clj:874]: I'm unaware of better way. Please let me know if you do.

Comment (bshepherdson) [reply src/metabase/models/card.clj:858]: Probably it's better to do these in one transaction, to keep the index locking etc. under control. Otherwise I'm not aware of a better way to do this.

Comment (lbrdnk) [reply src/metabase/models/card.clj:858]: Thanks. Done.

File: src/metabase/models/card.clj [hunk 2]
```diff
@@ -767,6 +767,96 @@
...
+                                         (comp vec (partial keep (partial update-mapping identifier->action))))
+                                 [:parameter_mappings])]
+    (when (not= (:parameter_mappings dashcard) (:parameter_mappings card-update))
+      [(:id dashcard) card-update])))
+
+(defn- updates-for-dashcards
+  [identifier->action dashcards]
+  (not-empty (keep (partial update-for-dashcard identifier->action) dashcards)))
+
+(defn- update-associated-parameters!
```
Comment (bshepherdson) [inline src/metabase/models/card.clj:835]: Just calling it out for future reference: all of this becomes dead code with the refs overhaul. Parameters mappings would use the new `:ident`s, which are consistently applied to a particular breakout. Editing its temporal unit (either directly or via a parameter) won't change the `:ident`, and so won't change the parameter mapping.

I've got a big "hit list" for cleanup after refs are landed; this is on it.

File: src/metabase/models/card.clj [hunk 3]
```diff
@@ -767,6 +767,96 @@
...
+(defn- breakout-->identifier->refs
+  "Generate mapping of of _ref identifier_ -> #{_ref..._}.
+
+  _ref identifier_ is a vector of first 2 elements of ref, eg. [:expression \"xix\"] or [:field 10]"
+  [breakout-clause]
+  (reduce (fn [acc breakout]
+            (update acc (subvec breakout 0 2)
+                    #(conj (set %1) breakout)))
+          {}
+          breakout-clause))
```
Comment (bshepherdson) [inline src/metabase/models/card.clj:779]:
```suggestion
  [breakouts]
  (-> (group-by #(subvec % 0 2) breakouts)
      (update-vals set)))
```

**Review by bshepherdson — CHANGES_REQUESTED** [review]
Some substantial edits to the functions in `metabase.model.card`.

File: src/metabase/models/card.clj (hunk 2 above)
Comment (lbrdnk) [reply src/metabase/models/card.clj:832]: > after refs are landed

That is going to be a big day for the qp :)

File: src/metabase/models/card.clj [hunk 4]
```diff
@@ -767,6 +767,96 @@
...
+
+  _identifier_ is is a vector of first 2 elements of ref, eg. [:expression \"xix\"] or [:field 10]. Action is generated
+  in [[action-for-identifier+refs]] and performed later in [[update-mapping]]."
+  [breakout-before-update breakout-after-update]
+  (let [before--identifier->refs (breakout-->identifier->refs breakout-before-update)
+        after--identifier->refs  (breakout-->identifier->refs breakout-after-update)
+        action (partial action-for-identifier+refs after--identifier->refs)
+        action-kvrf (fn [acc identifier before--refs] (assoc acc identifier (action identifier before--refs)))]
+    ;; Remove no-ops to avoid redundant db calls in [[update-associated-parameters!]].
+    (not-empty (m/filter-vals (complement #{[:noop]}) (reduce-kv action-kvrf {} before--identifier->refs)))))
```
[the remark this answers is not in the document]
Comment (lbrdnk) [reply src/metabase/models/card.clj]: Addressed as per [small comment on slack](https://metaboat.slack.com/archives/C0645JP1W81/p1730321635387229?thread_ts=1730305715.724079&cid=C0645JP1W81).

**Review by bshepherdson — APPROVED** [review]
