### PR TITLE
Fix LDAP requires `uid` to do group sync

### LINKED ISSUE #22014: LDAP user groups not requested when group-base field is filled
**Describe the bug**
We use adfs with slapd to expand nested ldap user groups. With Metabase 0.38.* all worked well. But after upgrading on version 0.40.0+ we faced with problems.
When a field `group-base` is filled we expect that Metabase will request a list of user's groups in an additional ldap request. But in new version Metabase don't send any such requests. If a reply with information about the user contain a `MemberOf` attribute Metabase uses only this list of groups in this attribute, and if reply doesn't contain that attribute we get an error: 
`Input to user-groups does not match schema: \n\n\t   [nil nil (named (not (instance? java.lang.String nil)) uid) nil nil]  \n\n`
The problem is that one of the functions in Metabase for ldap has mandatory parameter as `uid`, that doesn't provided by MS AD.
Currently we solve this problem by force adding a attribute `uid` in ldap reply with slapd. 

**Logs**

<details><summary>Full stacktrace: Input to user-groups does not match schema</summary>

```
[89ad8419-8a74-4c2f-a524-f18df373f521] 2022-04-25T11:53:31+02:00 ERROR metabase.api.session Authentication endpoint error
clojure.lang.ExceptionInfo: Input to user-groups does not match schema:
	   [nil nil (named (not (instance? java.lang.String nil)) uid) nil nil]
 {:type :schema.core/error, :schema [#schema.core.One{:schema com.unboundid.ldap.sdk.LDAPConnectionPool, :optional? 
 false, :name ldap-connection} #schema.core.One{:schema (constrained Str "Non-blank string"), :optional? false, :name 
 dn} #schema.core.One{:schema (constrained Str "Non-blank string"), :optional? false, :name uid} #schema.core
 .One{:schema {Keyword Any, :group-mappings (maybe {com.unboundid.ldap.sdk.DN [(constrained Int "Integer greater than 
 zero")]}), :first-name-attribute (constrained Str "Non-blank string"), :sync-groups? java.lang.Boolean, :user-base 
 (constrained Str "Non-blank string"), :last-name-attribute (constrained Str "Non-blank string"), :email-attribute 
 (constrained Str "Non-blank string"), :user-filter (constrained Str "Non-blank string"), :group-base (maybe 
 (constrained Str "Non-blank string"))}, :optional? false, :name arg3} #schema.core.One{:schema (constrained Str "Non-blank string"), :optional? false, :name group-membership-filter}], :value [...], :error [nil nil (named (not (instance? java.lang.String nil)) uid) nil nil], :status-code 401}
	at metabase.api.session$do_http_401_on_error.invokeStatic(session.clj:155)
	at metabase.api.session$do_http_401_on_error.invoke(session.clj:151)
	at metabase.api.session$fn__75692.invokeStatic(session.clj:175)
	at metabase.api.session$fn__75692.invoke(session.clj:163)
	at compojure.core$wrap_response$fn__32273.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__32257.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__32262.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__32266.invoke(core.clj:151)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285.invoke(core.clj:200)
	at metabase.api.session$_PLUS_log_all_request_failures$fn__75749.invoke(session.clj:298)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285.invoke(core.clj:200)
	at compojure.core$make_context$handler__32313.invoke(core.clj:289)
	at compojure.core$make_context$fn__32317.invoke(core.clj:299)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$make_context$fn__32317.invoke(core.clj:300)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at metabase.api.routes$fn__76493$fn__76496.invoke(routes.clj:56)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__76638$fn__76639.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285.invoke(core.clj:200)
	at compojure.core$make_context$handler__32313.invoke(core.clj:289)
	at compojure.core$make_context$fn__32317.invoke(core.clj:299)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32266.invoke(core.clj:153)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32266.invoke(core.clj:153)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32266.invoke(core.clj:153)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287.invoke(core.clj:197)
	at metabase.server.routes$fn__76626$fn__76628.invoke(routes.clj:41)
	at compojure.core$routes$fn__32285$f__32286.invoke(core.clj:198)
	at compojure.core$routes$fn__32285.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73621.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__73618.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__77107$fn__77108$fn__77109.invoke(log.clj:209)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__77107$fn__77108.invoke(log.clj:201)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__77107.invoke(log.clj:200)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80460.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__55229.invoke(security.clj:148)
	at metabase.server.middleware.json$wrap_json_body$fn__79615.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__79633.invoke(json.clj:98)
	at metabase.server.middleware.offset_paging$handle_paging$fn__55253.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__80727.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__80743.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__34379.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__45722$fn__45723.invoke(session.clj:262)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:243)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:235)
	at metabase.server.middleware.session$bind_current_user$fn__45722.invoke(session.clj:261)
	at metabase.server.middleware.session$wrap_current_user_info$fn__45709.invoke(session.clj:221)
	at metabase.server.middleware.session$wrap_session_id$fn__45695.invoke(session.clj:167)
	at metabase.server.middleware.auth$wrap_api_key$fn__65377.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__80647.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__34362.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__34387.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__80689.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__34390.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80476.invoke(ssl.clj:48)
	at metabase.server$async_proxy_handler$fn__76880.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
[89ad8419-8a74-4c2f-a524-f18df373f521] 2022-04-25T11:53:32+02:00 DEBUG metabase.server.middleware.log POST /api/session 401 66.2 ms (0 DB calls)
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message
   "Input to user-groups does not match schema: \n\n\t   [nil nil (named (not (instance? java.lang.String nil)) uid) nil nil]  \n\n",
   :data
   {:type :schema.core/error,
    :schema
    [{:schema com.unboundid.ldap.sdk.LDAPConnectionPool, :optional? false, :name ldap-connection}
     {:schema (constrained Str "Non-blank string"), :optional? false, :name dn}
     {:schema (constrained Str "Non-blank string"), :optional? false, :name uid}
     {:schema
      {Keyword Any,
       :group-mappings (maybe {com.unboundid.ldap.sdk.DN [(constrained Int "Integer greater than zero")]}),
       :first-name-attribute (constrained Str "Non-blank string"),
       :sync-groups? java.lang.Boolean,
       :user-base (constrained Str "Non-blank string"),
       :last-name-attribute (constrained Str "Non-blank string"),
       :email-attribute (constrained Str "Non-blank string"),
       :user-filter (constrained Str "Non-blank string"),
       :group-base (maybe (constrained Str "Non-blank string"))},
      :optional? false,
      :name arg3}
     {:schema (constrained Str "Non-blank string"), :optional? false, :name group-membership-filter}],
    :value
    [...],
    :error [nil nil (named (not (instance? java.lang.String nil)) uid) nil nil],
    :status-code 401},
   :at [metabase.api.session$do_http_401_on_error invokeStatic "session.clj" 155]}],
 :trace
 [[metabase.api.session$do_http_401_on_error invokeStatic "session.clj" 155]
  [metabase.api.session$do_http_401_on_error invoke "session.clj" 151]
  [metabase.api.session$fn__75692 invokeStatic "session.clj" 175]
  [metabase.api.session$fn__75692 invoke "session.clj" 163]
  [compojure.core$wrap_response$fn__32273 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__32257 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__32262 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 151]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [metabase.api.session$_PLUS_log_all_request_failures$fn__75749 invoke "session.clj" 298]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32313 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 299]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 300]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [metabase.api.routes$fn__76493$fn__76496 invoke "routes.clj" 56]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__76638$fn__76639 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32313 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32317 invoke "core.clj" 299]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 153]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 153]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32266 invoke "core.clj" 153]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285$f__32286$respond_SINGLEQUOTE___32287 invoke "core.clj" 197]
  [metabase.server.routes$fn__76626$fn__76628 invoke "routes.clj" 41]
  [compojure.core$routes$fn__32285$f__32286 invoke "core.clj" 198]
  [compojure.core$routes$fn__32285 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73621 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__73618 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__77107$fn__77108$fn__77109 invoke "log.clj" 209]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__77107$fn__77108 invoke "log.clj" 201]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__77107 invoke "log.clj" 200]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80460 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__55229 invoke "security.clj" 148]
  [metabase.server.middleware.json$wrap_json_body$fn__79615 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__79633 invoke "json.clj" 98]
  [metabase.server.middleware.offset_paging$handle_paging$fn__55253 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__80727 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__80743 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__34379 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__45722$fn__45723 invoke "session.clj" 262]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 243]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 235]
  [metabase.server.middleware.session$bind_current_user$fn__45722 invoke "session.clj" 261]
  [metabase.server.middleware.session$wrap_current_user_info$fn__45709 invoke "session.clj" 221]
  [metabase.server.middleware.session$wrap_session_id$fn__45695 invoke "session.clj" 167]
  [metabase.server.middleware.auth$wrap_api_key$fn__65377 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__80647 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__34362 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__34387 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__80689 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__34390 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80476 invoke "ssl.clj" 48]
  [metabase.server$async_proxy_handler$fn__76880 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 388]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 633]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 380]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 386]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run nil -1]],
 :cause
 "Input to user-groups does not match schema: \n\n\t   [nil nil (named (not (instance? java.lang.String nil)) uid) nil nil]  \n\n",
 :data
 {:type :schema.core/error,
  :schema
  [{:schema com.unboundid.ldap.sdk.LDAPConnectionPool, :optional? false, :name ldap-connection}
   {:schema (constrained Str "Non-blank string"), :optional? false, :name dn}
   {:schema (constrained Str "Non-blank string"), :optional? false, :name uid}
   {:schema
    {Keyword Any,
     :group-mappings (maybe {com.unboundid.ldap.sdk.DN [(constrained Int "Integer greater than zero")]}),
     :first-name-attribute (constrained Str "Non-blank string"),
     :sync-groups? java.lang.Boolean,
     :user-base (constrained Str "Non-blank string"),
     :last-name-attribute (constrained Str "Non-blank string"),
     :email-attribute (constrained Str "Non-blank string"),
     :user-filter (constrained Str "Non-blank string"),
     :group-base (maybe (constrained Str "Non-blank string"))},
    :optional? false,
    :name arg3}
   {:schema (constrained Str "Non-blank string"), :optional? false, :name group-membership-filter}],
  :value
  [...],
  :error [nil nil (named (not (instance? java.lang.String nil)) uid) nil nil],
  :status-code 401},
 :message
 "Input to user-groups does not match schema: \n\n\t   [nil nil (named (not (instance? java.lang.String nil)) uid) nil nil]  \n\n",
 :value
 [...],
 :error [nil nil (named (not (instance? java.lang.String nil)) uid) nil nil]}
```

</details>

**To Reproduce**
1. Setup some ldap server, that doesn't provide MemberOf and uid attributes;
2. Add your user in some groups in a some OU;
5. Set Group Search Base, configure and enable Group Mapping in Metabase;
6. Try to login;

**Expected behavior**
Metabase get list of user's groups in particular OU and map it on local groups without errors.

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 100.0.4896.127
- Your operating system: MacOS 12.1
- Metabase version: 0.42.4
- Metabase hosting environment: (official docker build)

### PR DESCRIPTION
**Pull request by qnkhuat**
Fix #22014 and clean up some LDAP tests

### CODE REVIEW

File: test/metabase/api/session_test.clj [hunk 1]
```diff
@@ -401,15 +399,11 @@
 (deftest ldap-login-test
   (ldap.test/with-ldap-server
     (testing "Test that we can login with LDAP"
-      (let [user-id (mt/user->id :rasta)]
```
Comment (qnkhuat) [inline test/metabase/api/session_test.clj:404]: clean up some tests

File: src/metabase/integrations/ldap/default_implementation.clj [hunk 2]
```diff
@@ -49,7 +49,7 @@
   "Retrieve groups for a supplied DN."
   [ldap-connection         :- LDAPConnectionPool
    dn                      :- su/NonBlankString
-   uid                     :- su/NonBlankString
```
Comment (qnkhuat) [inline src/metabase/integrations/ldap/default_implementation.clj:52]: here is the fix

File: src/metabase/integrations/ldap/default_implementation.clj [hunk 3]
```diff
@@ -49,7 +49,7 @@
...
+   uid                     :- (s/maybe su/NonBlankString)
```
Comment (qnkhuat) [inline src/metabase/integrations/ldap/default_implementation.clj:52]: Here is the fix

**Review by noahmoss — APPROVED** [review]
