### PR TITLE
Hide columns from SQL Query such that they will take effect in dashboard subscription email/slack

### LINKED ISSUE #19508: Visualization settings applied on dashboard cards are not present in Subscription emails
**Describe the bug**
Only formatting applied to the underlying question is included in the Subscription emails, but any formatting applied to dashboard cards are not included.

EDIT: Formatting is **differently** applied if using the "Send email test" button vs waiting for the schedule.
On schedule: It will correctly apply column formatting it seems, but no conditional formatting is applied.
Test email: It will correctly apply conditional formatting it seems, but no column formatting is applied.
I would hate if this becomes another way of too many different ways something can be tested, similar to #17753.

**To Reproduce**
1. Create a table question and apply formatting to a couple of columns - save question and add to dashboard twice
2. On dashboard, modify the second card and change the formatting
Screenshot 2022-01-03 at 12-31-47 flamber test dashboard · Dashboard · Metabase
3. Save question and send subscription via email
Screenshot 2022-01-03 at 12-31-07 flamber test dashboard - email

**Information about your Metabase Installation:**
Tested 0.42.0-rc1

**Additional context**
Very related to #3735

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #32312: Hiding columns from SQL Query will not take effect in dashboard subscription email/slack
### Describe the bug

If you hide columns from the results of an SQL Query and you schedule a dashboard subscription it will ignore those hidden columns and still send them 

### To Reproduce

1. Go to New -> SQL Question -> `Select * from orders` -> Hide a number of columns:

image

2. Add this question to a dashboard -> Schedule a subscription -> Send a test

3. Notice how the columns are all visible & the attachment only shows 3

image

### Expected behavior

Columns that are hidden shouldn't be visible in the subscription

### Logs

None

### Information about your Metabase installation

```JSON
Replicated on 1.46.5, 1.47 and even master
```

### Severity

Annoying

### Additional context

This is pretty annoying because you are stuck in not being able to use SQL so you have to use the SQL as a datasource to a question to work this out, adding an additional step

### PR DESCRIPTION
**Pull request by qwef**
Closes https://github.com/metabase/metabase/issues/32312
Also closes https://github.com/metabase/metabase/issues/19508

### Description

Find a filter of names in column names, then apply that to the data.

### Demo
Before
image
After
image

### CODE REVIEW

File: test/metabase/pulse/render/table_test.clj
[the remark this answers is not in the document]
Comment (noahmoss) [reply test/metabase/pulse/render/table_test.clj:1]: @adam-james-v seems like you wrote this test, do you know?

File: src/metabase/pulse/render/body.clj [hunk 1]
```diff
@@ -213,14 +213,28 @@
...
+        filtered-rows (map #(update % :row keep-filtered-idx) rows)]
+    filtered-rows))
+
 (s/defmethod render :table :- common/RenderedPulseCard
   [_ render-type timezone-id :- (s/maybe s/Str) card dashcard {:keys [rows viz-settings] :as data}]
   (let [viz-settings (merge viz-settings (:visualization_settings dashcard))
+        filter-columns? (some? (:table.columns viz-settings))
+        filtered-columns-names (if filter-columns?
+                                 (mapv :name (filter :enabled (:table.columns viz-settings)))
+                                 (mapv :name (:cols data)))
```
Comment (noahmoss) [inline src/metabase/pulse/render/body.clj:230]: Tested locally and it didn't work for me, I think because you're not using the correct keys for pulling data out of `viz-settings`. They should be namespaced with `mb.viz` like `::mb.viz/table-columns`.

**Review by noahmoss — CHANGES_REQUESTED** [review]
I think this works for hiding columns (once you fix the viz-settings key names) but doesn't work for reordered columns. There's probably a way to make it a bit more generic and handling reordering as well.

Take a look at `export-column-order` in `metabase.query-processor.streaming` which is doing something very similar. You might be able to reuse that function or at least adapt the logic a bit.

File: src/metabase/pulse/render/body.clj (hunk 1 above)
Comment (qwef) [reply src/metabase/pulse/render/body.clj:230]: Tested with `::mb.viz/table-columns` and didn't work for me, but it does work for `:table.columns`. What does your `viz-settings` look like? It doesn't show `::mb.viz/table-columns ` for me.

```{:table.pivot_column QUANTITY, :table.cell_column ID, :metabase.shared.models.visualization-settings/column-settings nil, :metabase.shared.models.visualization-settings/global-column-settings {:type/Temporal {:metabase.shared.models.visualization-settings/date-style D/M/YYYY, :metabase.shared.models.visualization-settings/date-separator -, :metabase.shared.models.visualization-settings/date-abbreviate false}, :type/Number {:metabase.shared.models.visualization-settings/number-separators ,.}}, :table.columns [{:name ID, :fieldRef [:field ID {:base-type :type/BigInteger}], :enabled true} {:name USER_ID, :fieldRef [:field USER_ID {:base-type :type/Integer}], :enabled true} {:name SUBTOTAL, :fieldRef [:field SUBTOTAL {:base-type :type/Float}], :enabled true} {:name TAX, :fieldRef [:field TAX {:base-type :type/Float}], :enabled true} {:name CREATED_AT, :fieldRef [:field CREATED_AT {:base-type :type/DateTime}], :enabled true} {:name TOTAL, :fieldRef [:field TOTAL {:base-type :type/Float}], :enabled false} {:name DISCOUNT, :fieldRef [:field DISCOUNT {:base-type :type/Float}], :enabled false} {:name PRODUCT_ID, :fieldRef [:field PRODUCT_ID {:base-type :type/Integer}], :enabled false} {:name QUANTITY, :fieldRef [:field QUANTITY {:base-type :type/Integer}], :enabled false}]}```

Comment (noahmoss) [reply src/metabase/pulse/render/body.clj:230]: Here's what I see in `viz-settings` in `render`:

```
{:table.pivot_column "QUANTITY",
 :table.cell_column "ID",
 :metabase.shared.models.visualization-settings/table-columns
 [#:metabase.shared.models.visualization-settings{:table-column-name "ID",
                                                  :table-column-field-ref [:field "ID" {:base-type :type/BigInteger}],
                                                  :table-column-enabled false}
  #:metabase.shared.models.visualization-settings{:table-column-name "USER_ID",
                                                  :table-column-field-ref
                                                  [:field "USER_ID" {:base-type :type/Integer}],
                                                  :table-column-enabled false}
  #:metabase.shared.models.visualization-settings{:table-column-name "PRODUCT_ID",
                                                  :table-column-field-ref
                                                  [:field "PRODUCT_ID" {:base-type :type/Integer}],
                                                  :table-column-enabled false}
  #:metabase.shared.models.visualization-settings{:table-column-name "SUBTOTAL",
                                                  :table-column-field-ref [:field "SUBTOTAL" {:base-type :type/Float}],
                                                  :table-column-enabled false}
  #:metabase.shared.models.visualization-settings{:table-column-name "TAX",
                                                  :table-column-field-ref [:field "TAX" {:base-type :type/Float}],
                                                  :table-column-enabled false}
  #:metabase.shared.models.visualization-settings{:table-column-name "TOTAL",
                                                  :table-column-field-ref [:field "TOTAL" {:base-type :type/Float}],
                                                  :table-column-enabled false}
  #:metabase.shared.models.visualization-settings{:table-column-name "DISCOUNT",
                                                  :table-column-field-ref [:field "DISCOUNT" {:base-type :type/Float}],
                                                  :table-column-enabled true}
  #:metabase.shared.models.visualization-settings{:table-column-name "CREATED_AT",
                                                  :table-column-field-ref
                                                  [:field "CREATED_AT" {:base-type :type/DateTime}],
                                                  :table-column-enabled true}
  #:metabase.shared.models.visualization-settings{:table-column-name "QUANTITY",
                                                  :table-column-field-ref
                                                  [:field "QUANTITY" {:base-type :type/Integer}],
                                                  :table-column-enabled true}],
 :metabase.shared.models.visualization-settings/column-settings nil,
 :metabase.shared.models.visualization-settings/global-column-settings {}}
```

File: src/metabase/pulse/render/body.clj [hunk 2]
```diff
@@ -878,9 +884,8 @@
              :src   (:image-src image-bundle)}]]}))
 
 (s/defmethod render :scalar :- common/RenderedPulseCard
-  [_chart-type _render-type timezone-id _card dashcard {:keys [cols rows viz-settings]}]
-  (let [viz-settings (merge viz-settings (:visualization_settings dashcard))
-        value        (format-cell timezone-id (ffirst rows) (first cols) viz-settings)]
+  [_chart-type _render-type timezone-id _card _dashcard {:keys [cols rows viz-settings]}]
+  (let [value        (format-cell timezone-id (ffirst rows) (first cols) viz-settings)]
```
Comment (noahmoss) [inline src/metabase/pulse/render/body.clj:888]: (I know this was from my PR but just noticed it)

```suggestion
  (let [value (format-cell timezone-id (ffirst rows) (first cols) viz-settings)]
```

**Review by noahmoss — APPROVED** [review]
Cool, tested locally and seems like everything works now. Thanks for pulling in my changes.
