### PR TITLE
JWT Login URL configured by user may have URL parameters

### LINKED ISSUE #13078: Incorrect URL parsing/generation for JWT login page
**Describe the bug**
Metabase does not generate a valid URL if the base URL contains query parameters

**Logs**
n/a

**To Reproduce**
1. Configure the JWT login page URL as something like "http://myauthserver.mydomain.home:9000/login/to/reports?tenantId=abc"
2. Attempt to log in 
3. The generated URL will be "http://myauthserver.mydomain.home:9000/login/to/reports?tenantId=abc?return_to=/" (note two "?")

**Expected behavior**
The URL is properly parsed, the "return_to" query parameter is added and then the URL is properly serialized, e.g. it should be "http://myauthserver.mydomain.home:9000/login/to/reports?tenantId=abc&return_to=/" instead.

**Information about your Metabase Installation:**

- Safari 13.1.1
- OS X 10.15.5
- Your databases: none configured
- Metabase version: 1.36.3
- Metabase hosting environment: jar-file
- Metabase internal database: H2

**Severity**
somewhat blocking, although another way to pass the argument can be used (path).

### PR DESCRIPTION
**Pull request by adam-james-v**
Since params may already exist in the login URL, a check is performed to make sure the generated URL
with 'return_to' param formats correctly.

If a param already exists, all subsequent params should have an '&' character.

fixes: #13078

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj [hunk 1]
```diff
@@ -10,7 +10,8 @@
             [metabase.server.middleware.session :as mw.session]
             [metabase.server.request.util :as request.u]
             [metabase.util.i18n :refer [trs tru]]
-            [ring.util.response :as resp])
+            [ring.util.response :as resp]
+            [clojure.string :as str])
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj:14]: you'll need to sort your ns to satisfy the namespace linter which is failing the build right now.

Comment (adam-james-v) [reply enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj:14]: Oops. Yea, thanks.

File: enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj [hunk 2]
```diff
@@ -77,7 +77,16 @@
                                                          {:request-options {:redirect-strategy :none}}
                                                          :redirect default-redirect-uri)
             redirect-url (get-in result [:headers "Location"])]
-        (is (str/starts-with? redirect-url default-idp-uri))))))
+        (is (str/starts-with? redirect-url default-idp-uri)))))
+  (testing (str "JWT configured with a redirect-uri containing query params, "
+                "a GET request should result in a redirect to the IdP as a correctly formatted URL")
```
Comment (noahmoss) [inline enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj:82]: nit: often when we add test cases for bug fixes we add a mention of the issue number, might be worth doing here

**Review by noahmoss — APPROVED** [review]

**Comment by dpsutton** [comment]
One thought: we are using the predicate of `contains a ?` to see if it already has other query params. Is there a structured way of doing this? Something like `(if (seq (query-params idp)) "&" "?")` or perhaps something even more url-aware that can do this for us `(add-param idp "redirect_to" location)` that knows about existing query params? Or is all of this over-kill and it will just be checking for a question mark anyways?

File: enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj (hunk 2 above)
Comment (adam-james-v) [reply enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj:82]: Ah, thanks. Do we add it in a comment or in a string somewhere inside the test?

Comment (noahmoss) [reply enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj:82]: just in the testing context string, like https://github.com/metabase/metabase/pull/19530/files#diff-c00373b640a0d87270c78f3b00299b78d569505bb3cfab808d7c039ec7a836deR473-R474
