### PR TITLE
Fix png image paths when rendered inside Embedding SDK

### LINKED ISSUE #52102: Invalid URLs for some png images when displayed inside Embedding SDK
### Describe the bug

Some images, when displayed inside the Embedding SDK, are referenced by a path like `app/assets/img/pin.png`, which results in an invalid image URL.

Example:
`frontend/src/metabase/visualizations/components/LeafletMarkerPinMap.jsx`
```
iconUrl: "app/assets/img/pin.png",
```

I've also found another example that is reproducible in the Embedded SDK:
`frontend/src/metabase/visualizations/visualizations/Table.tsx`
```
<img
  width={99}
  src="app/assets/img/hidden-field.png"
  srcSet="
    app/assets/img/hidden-field.png     1x,
    app/assets/img/hidden-field@2x.png  2x
  "
  className={CS.mb2}
/>
```

Image

### To Reproduce

For example, display a dashboard containing a map with the `pin.png` icons inside the Embedding SDK

### Expected behavior

Icons should be displayed

### PR DESCRIPTION
**Pull request by sanex3339**
Fixes https://github.com/metabase/metabase/issues/52102

To fix images inside Embedded SDK, the `api.basename` is added to image URLs (via an existing helper).

Issue:
image

How to verify:
- setup any dashboard containing a map visualisation with visible `pin` icons
- open this dashboard via Embedded SDK and be sure that `pin` icons visible

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/Table.tsx [hunk 1]
```diff
@@ -435,12 +444,13 @@ class Table extends Component<TableProps, TableState> {
           )}
         >
           <img
+            data-testid="Table-all-fields-hidden-image"
```
Comment (sanex3339) [inline frontend/src/metabase/visualizations/visualizations/Table.tsx:447]: What is the up-to-date data-testid naming convention?

File: e2e/test-component/scenarios/embedding-sdk/interactive-question-map.cy.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+  METABASE_INSTANCE_URL,
+  mockAuthProviderAndJwtSignIn,
+  mountInteractiveQuestion,
+  signInAsAdminAndEnableEmbeddingSdk,
+} from "e2e/support/helpers/component-testing-sdk";
+import { getSdkRoot } from "e2e/support/helpers/e2e-embedding-sdk-helpers";
+
+const { PEOPLE_ID } = SAMPLE_DATABASE;
+
+describeEE("scenarios > embedding-sdk > interactive-question", () => {
```
Comment (heypoom) [inline e2e/test-component/scenarios/embedding-sdk/interactive-question-map.cy.spec.tsx]: nit: sync test suite name with file name

```suggestion
describeEE("scenarios > embedding-sdk > interactive-question-map", () => {
```

File: frontend/src/metabase/visualizations/components/LeafletMarkerPinMap.jsx [hunk 3]
```diff
@@ -1,22 +1,23 @@
...
     super.componentDidMount();
 
     this.pinMarkerLayer = L.layerGroup([]).addTo(this.map);
+    this.pinMarkerIcon = L.icon({
+      iconUrl: getSubpathSafeUrl("app/assets/img/pin.png"),
+      iconSize: [28, 32],
+      iconAnchor: [15, 24],
+      popupAnchor: [0, -13],
+    });
+
```
Comment (sanex3339) [inline frontend/src/metabase/visualizations/components/LeafletMarkerPinMap.jsx:20]: Decided to put it here, because:
- ideally, it should be created only once
- we should not call `getSubpathSafeUrl` while the root of the module is evaluated, because at that moment `api.basename` is empty

File: e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx [hunk 4]
```diff
@@ -91,15 +93,28 @@ describeEE("scenarios > embedding-sdk > interactive-question", () => {
...
-      .findByTestId("click-actions-sort-control-formatting-hide")
-      .click();
+      tableHeaderClick(columnName);
 
-    tableInteractive().findByText("Max of Quantity").should("not.exist");
+      popover()
+        .findByTestId("click-actions-sort-control-formatting-hide")
+        .click();
+
+      if (index < columnNames.length - 1) {
```
Comment (heypoom) [inline e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx:107]: nit: looks like this only evaluates to `false` on the last column. considering that we only have two columns here, we could probably hard-code the column to make it easier to read.

File: e2e/test/scenarios/dashboard/dashboard.cy.spec.js [hunk 5]
```diff
@@ -855,9 +856,7 @@ describe("scenarios > dashboard", () => {
         });
 
         H.visitDashboard(dashboardId);
-        cy.get(".leaflet-marker-icon") // pin icon
-          .eq(0)
-          .click({ force: true });
+        mapPinIcon().eq(0).click({ force: true });
```
Comment (heypoom) [inline e2e/test/scenarios/dashboard/dashboard.cy.spec.js:859]: nice refactoring!

File: frontend/src/metabase/visualizations/visualizations/Table.tsx (hunk 1 above)
Comment (heypoom) [reply frontend/src/metabase/visualizations/visualizations/Table.tsx:447]: Good question! Usually I use `lowercase-dash-case` but can I see in the codebase that sometimes we prefix the testid with the capitalized visualization component like you did here (`Table-xyz`), so this is fine

**Review by heypoom — APPROVED** [review]
diffs looks great!

File: e2e/test-component/scenarios/embedding-sdk/interactive-question-map.cy.spec.tsx (hunk 2 above)
Comment (sanex3339) [reply e2e/test-component/scenarios/embedding-sdk/interactive-question-map.cy.spec.tsx]: Done, thank you

File: e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx (hunk 4 above)
Comment (sanex3339) [reply e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx:107]: Do you mean something like `if (columnName === "Max of Quantity") {...}`?

Comment (heypoom) [reply e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx:107]: @sanex3339 yes, seems a little bit easier to read that way (as we only have two columns)

**Review by alxnddr — APPROVED** [review]
