### PR TITLE
Fix missing summarize operations after creation of numeric custom column

### LINKED ISSUE #27745: Missing summarize operations after creation of numeric custom column
**Describe the bug**
I created a query that is based on dimension table and created a custom column. The Dimension table has timestamps, IDs and strings column types but no numeric column types. When trying to use the summarize option in the query builder, option like sum, cumulative sum or average are not shown there is no numeric field to use these functions on.

However when adding a custom column that is a numeric field,
e.g.   case([ID] = "1", 5, 3)
or      datetimeDiff([Create Time], [Update Time] , "minute")

the options for sums, avg and so on are still not shown.

**To Reproduce**
1. Create a query with a table that has no numeric columns in the query builder
2. Create a numeric custom column like the examples above
3. Click on summarize and then on "Pick metric you want to see"
4. See that the sum/avg options are missing

**Optional Steps**
5. Try to create a custom expression instead on the created custom column
6. Click visualize
7. Summarize breaks and is kicked out of query builder, you return to after Step 2

**Expected behavior**
When a custom column is created that is numeric, the options should show. Also the custom summarize should not break.

**Screenshots**
Screenshot 2023-01-18 at 09 59 22
Screenshot 2023-01-18 at 09 59 27

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "5.4.202+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-01-17",
      "tag": "v0.45.2",
      "branch": "release-x.45.x",
      "hash": "819ce29"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
High. Regular users cannot create queries on dimension tables. Only SQL-Editor would work in that scenario.

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/27745

### Description

Previously, any code regarding the aggregation operators will only be called from `Table` it's fine until we have a table which doesn't have certain field types, but we introduce those field types in expressions. Since `Table`s are not aware of expressions which only exist in `StructuredQuery`. It caused the bug.

This PR address the bug by shifting calls to `aggregationOperators` and `aggregationOperator` from `Table` to `StructuredQuery` instead.

### How to verify

2 ways to test this PR.

1. Run Cypress tests in `e2e/test/scenarios/custom-column/reproductions/27745-cc-numeric-missing-summarize.cy.spec.js` and it should pass.

OR

1. Create a question based on `Orders` only select `id` and `created_at`.
2. Open the query builder, and select the saved question from the previous step as a source.
3. Click on **Summarize** button, and make sure there is no **Average of ...** option
4. Close the aggregation section
5. Add this expression `case([ID] = 1, 2, 3)` (or other expression which results in numeric field)
6. Click on **Summarize** button, and make sure there is **Average of ...** option
7. Click **Visualize** should show the result.

#### Before (no aggregations for numeric fields)
Screenshot 2023-03-17 at 6 53 12 PM

#### After (has aggregations for numeric fields)
Screenshot 2023-03-17 at 6 52 50 PM

### Checklist

- [X] Tests have been added/updated to cover changes in this PR (E2E + Unit)

### CODE REVIEW

File: frontend/src/metabase-lib/queries/StructuredQuery.ts [hunk 1]
```diff
@@ -640,7 +643,27 @@ class StructuredQueryInner extends AtomicQuery {
...
+        ])) ||
+      []
+    );
+  }
+
+  aggregationOperatorsLookup(): Record<string, AggregationOperator> {
+    return createLookupByProperty(this.aggregationOperators(), "short");
+  }
+
+  aggregationOperator(short: string): AggregationOperator {
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/queries/StructuredQuery.ts:665]: `aggregationOpertors` (with an ending `s`) was introduced in https://github.com/metabase/metabase/pull/11032 in `Table`, `StructuredQuery` and a number of other Metabase lib inteties it also introduced `aggregationOperator` but only to `Dimension`. 

This function `aggregationOperator` (_without_ an ending `s`) was only additionally introduced in `Table` and `Field` in https://github.com/metabase/metabase/pull/12859

This change brings it closer to how `Table`'s `aggregationOperators` and `aggregationOperator` were implemented.

File: frontend/src/metabase-lib/queries/StructuredQuery.ts [hunk 2]
```diff
@@ -1719,6 +1746,7 @@ class StructuredQuery extends memoizeClass<StructuredQueryInner>(
   "joinedDimensions",
   "breakoutDimensions",
   "aggregationDimensions",
+  "aggregationOperatorsLookup",
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/queries/StructuredQuery.ts:1749]: as this function is memoized in `Table`:
https://github.com/metabase/metabase/blob/fa37b582653012264173e72a786a99a312eef345/frontend/src/metabase-lib/metadata/Table.ts#L176

I should do that here as well to stay consistent.

File: frontend/src/metabase-lib/queries/StructuredQuery.ts [hunk 3]
```diff
@@ -1272,6 +1297,8 @@ class StructuredQueryInner extends AtomicQuery {
       // de-duplicate explicit and implicit joined tables
       const explicitJoins = this._getExplicitJoinsSet(joins);
 
+      // This is only a refactor, I moved this line down to limit the scope where this variable could be used.
+      const dimensionIsFKReference = dimension => dimension.field?.().isFK();
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/queries/StructuredQuery.ts:1301]: This is only a small refactor. I don't see the point of declaring `dimensionIsFKReference` too early since it's only been used once on the next line.

File: frontend/src/metabase-lib/queries/StructuredQuery.ts [hunk 4]
```diff
@@ -656,8 +679,10 @@ class StructuredQueryInner extends AtomicQuery {
    * @returns the field options for the provided aggregation
    */
   aggregationFieldOptions(agg: string | AggregationOperator): DimensionOptions {
+    // XXX: We need to fix this function so that it takes expression (custom field) into account
+    // aggregationOperator seem to check if the aggregation would be valid for the the given table
     const aggregation: AggregationOperator =
-      typeof agg === "string" ? this.table().aggregationOperator(agg) : agg;
+      typeof agg === "string" ? this.aggregationOperator(agg) : agg;
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/queries/StructuredQuery.ts:685]: This fixes the issue to take expression into account when calculating the available aggregation operators. By using `StructuredQuery`'s `aggregationOperator` (introduced in this PR) instead of `Table`'s

image

File: frontend/src/metabase-lib/queries/structured/Aggregation.ts [hunk 5]
```diff
@@ -157,9 +157,7 @@ export default class Aggregation extends MBQLClause {
       return this.aggregation().isValid();
     } else if (this.isStandard() && this.dimension()) {
       const dimension = this.dimension();
-      const aggregationOperator = this.query()
-        .table()
-        .aggregationOperator(this[0]);
+      const aggregationOperator = this.query().aggregationOperator(this[0]);
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/queries/structured/Aggregation.ts:160]: after we click `Visualize`
image

MBQL validation will kick in. So this part needs to call query's `aggregationOperator` instead of `Table` since tables aren't aware of expressions.

File: frontend/src/metabase/query_builder/components/AggregationPopover/AggregationPopover.jsx [hunk 6]
```diff
@@ -143,11 +143,12 @@ export default class AggregationPopover extends Component {
   };
 
   _getAvailableAggregations() {
+    // XXX: This looks like the place we generate the options for the aggregation popover
     const { aggregationOperators, query, dimension, showRawData } = this.props;
     return (
       aggregationOperators ||
       dimension?.aggregationOperators() ||
-      query.table().aggregationOperators()
+      query.aggregationOperators()
```
Comment (WiNloSt) [inline frontend/src/metabase/query_builder/components/AggregationPopover/AggregationPopover.jsx:151]: Even though `aggregationOperators` already exists in `StructuredQuery` before this PR, we still call the one in `Table` instead. Previously it'd be equivalent whether or not we call `query.aggregationOperators()` or `query.table().aggregationOperators()`, but not after this PR, since the new `StructuredQuery`'s `aggregationOperators` takes expression into account not only table fields when calculating which aggregation operators it would show in the aggregation step.

image

File: frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js [hunk 7]
```diff
@@ -28,6 +30,36 @@ function makeQueryWithAggregation(agg) {
   return makeQuery({ aggregation: [agg] });
 }
 
+function makeQueryWithoutNumericFields() {
```
Comment (WiNloSt) [inline frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js:33]: I'm pretty new to testing `Question` and `StructuredQuery` in general, this might not be ideal, but it does the job for now. Please feel free to suggest better alternatives.

I need the question to rely on the saved question, if we only rely on one of the sample table, they already have almost all field types which results in every aggregations being shown.

This setup create a question based on `Orders` table which only has 2 fields selected (ID and created_at), so there's no numeric field at this point.

File: frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js [hunk 8]
```diff
@@ -28,6 +30,36 @@ function makeQueryWithAggregation(agg) {
...
+      db_id: SAMPLE_DATABASE.id,
+      fields: [ORDERS.ID.id, ORDERS.CREATED_AT.id],
+    };
+    return state.assocIn(
+      ["entities", "tables", virtualCardId],
+      tableWithWithoutNumericFields,
+    );
+  });
+
+  return new Question(questionDetail, metadata).query();
```
Comment (WiNloSt) [inline frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js:60]: the only way I can make it work is to create a metadata that contains a saved question's info.

So when a query has this `"source-table": "card__123"`, it can resolve the original question fields correctly.

File: frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js [hunk 9]
```diff
@@ -296,6 +328,96 @@ describe("StructuredQuery", () => {
...
+          // Expression: case([ID] = 1, 11, 99)
+          ["case", [["=", ORDERS.ID, 1], 11], { default: 99 }],
+        );
+
+        expect(query.aggregationOperators()).not.toEqual(
+          query.table().aggregationOperators(),
+        );
+        expect(
+          query.aggregationOperators().map(aggregation => aggregation.short),
+        ).toEqual([
```
Comment (WiNloSt) [inline frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js:379]: This asserts that previously we ensure there wouldn't be aggregations for numeric fields here (previous test), but after adding an expression that would result in a numeric field, this aggregations for numeric fields start being available.

File: frontend/src/metabase-lib/queries/StructuredQuery.ts [hunk 10]
```diff
@@ -640,7 +643,27 @@ class StructuredQueryInner extends AtomicQuery {
...
+      (table &&
+        getAggregationOperators(table, [
+          ...expressionFields,
+          ...table.fields,
+        ])) ||
+      []
+    );
+  }
+
+  aggregationOperatorsLookup(): Record<string, AggregationOperator> {
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/queries/StructuredQuery.ts:661]: This function looks the exact same as the one in `Table`.

File: frontend/src/metabase-lib/utils/create-lookup-by-property.ts [hunk 11]
```diff
@@ -1,8 +1,8 @@
-export function createLookupByProperty(items: any[], property: string) {
-  const lookup: Record<string, any> = {};
+export function createLookupByProperty<T>(items: T[], property: keyof T) {
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/utils/create-lookup-by-property.ts:1]: Fix types so that it infers a better return value type. Previously id would return `Record<string, any>`

**Review by ranquild — COMMENTED** [review]
Looks good! One thing that makes me worry is that it seems that `Table.getAggregationOperators` should never be called without fields because it will introduce a bug. Can we address that somehow? E.g. fixing existing tests by providing `table.fields` and making sure it is never called without expression fields in the app code?

**Comment by WiNloSt** [comment]
@ranquild Just for clarification.
- `getAggregationOperators` the one with `get` in front, isn't a part of any Metabase lib entities, it lives in `frontend/src/metabase-lib/operators/utils/index.js`.
- Before this PR, `getAggregationOperators` is only called in `Table`, but this PR call `getAggregationOperators` within `StructuredQuery` too.

Given those points, I'm not sure I follow your comment
> `Table.getAggregationOperators` should never be called without fields because it will introduce a bug.

`Table.aggregationOperators` is not changed in this PR. It still passes a single parameter `table` to `getAggregationOperators` and by default `fields` (the newly introduced parameter will use the value from `table.fields` from the first parameter), this makes the current tests pass without needing to change them.

> Can we address that somehow? E.g. fixing existing tests by providing table.fields...

I'm not sure this will answer your request, but I can make changes to `getAggregationOperators` to make `fields` required, this ensures its API is more transparent, rather than relying on `table.fields` for the second parameter under the hood.

>  ... and making sure it is never called without expression fields in the app code?

I'm not totally sure what this means given the context in this comment above. But given I don't change the way `Table.aggregationOperators` is called, it's guaranteed to have never been called with expression fields. Also, I think it's impossible since I assume `Table` has no access to expression anyway.

Please let me know if this is clear, or did I misunderstand anything.

**Comment by ranquild** [comment]
@WiNloSt to your point, could you make `fields` required where you default to `table.fields` currently? What that would result in?

**Comment by WiNloSt** [comment]
@ranquild That would result in unit tests failure, I opt to this solution–default to `table.fields`–since I don't want to change fix those tests initially.

**Comment by ranquild** [comment]
@WiNloSt It seems important to me that this Table method doesn't work correctly with default arguments. Could we make  `fields` argument required and pass `table.fields` in tests?

**Comment by WiNloSt** [comment]
> @WiNloSt It seems important to me that this Table method doesn't work correctly with default arguments. Could we make `fields` argument required and pass `table.fields` in tests?

Sure, I can do that 👍

File: frontend/src/metabase-lib/operators/utils/index.js [hunk 12]
```diff
@@ -102,9 +102,9 @@ function populateFields(aggregationOperator, fields) {
   };
 }
 
-export function getAggregationOperators(table) {
+export function getAggregationOperators(table, fields) {
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/operators/utils/index.js:105]: we used to only get `fields` from `table` however, in the case we have custom fields too, so we need to be able to get `Field` based on those custom fields too.

File: frontend/src/metabase-lib/operators/utils/index.unit.spec.js [hunk 13]
```diff
@@ -202,7 +202,7 @@ describe("metabase-lib/operators/utils", () => {
           features: ["basic-aggregations", "standard-deviation-aggregations"],
         },
       };
-      const fullOperators = getAggregationOperators(table);
+      const fullOperators = getAggregationOperators(table, fields);
```
Comment (WiNloSt) [inline frontend/src/metabase-lib/operators/utils/index.unit.spec.js:205]: Fix unit tests.

**Review by ranquild — APPROVED** [review]

**Comment by ranquild** [comment]
@WiNloSt great work!

**Comment by WiNloSt** [comment]
@ranquild turns out I only need to fix a single place for all test test failures since the code that calls `getAggregationOperators` is in the `setup` function.
