### PR TITLE
Fix infinite loop when logging error when fetching `site-locale` 

### LINKED ISSUE #32376: Stack overflow/infinite loop when logging decryption error message when getting setting value
See https://github.com/metabase/harbormaster/issues/3963 for more info.

Filtered stacktrace:

```
  at metabase.db.setup$build_around_method_default.invokeStatic(setup.clj:197)
  at metabase.db.setup$build_around_method_default.invoke(setup.clj:190)
  at metabase.models.setting$db_or_cache_value.invokeStatic(setting.clj:440)
  at metabase.models.setting$db_or_cache_value.invoke(setting.clj:422)
  at metabase.models.setting$get_raw_value.invokeStatic(setting.clj:476)
  at metabase.models.setting$get_raw_value.invoke(setting.clj:450)
  at metabase.models.setting$get_raw_value.invokeStatic(setting.clj:490)
  at metabase.models.setting$get_raw_value.invoke(setting.clj:450)
  at metabase.models.setting$fn__45043.invokeStatic(setting.clj:509)
  at metabase.models.setting$fn__45043.invoke(setting.clj:507)
  at metabase.util.i18n.impl$fn__3907$f__3908.invoke(impl.clj:216)
  at metabase.util.i18n.impl$site_locale_from_setting.invokeStatic(impl.clj:227)
  at metabase.util.i18n.impl$site_locale_from_setting.invoke(impl.clj:220)
  at metabase.util.i18n$site_locale_string.invokeStatic(i18n.clj:41)
  at metabase.util.i18n$site_locale_string.invoke(i18n.clj:36)
  at metabase.util.i18n$site_locale.invokeStatic(i18n.clj:54)
  at metabase.util.i18n$site_locale.invoke(i18n.clj:51)
  at metabase.util.i18n$translate_site_locale.invokeStatic(i18n.clj:73)
  at metabase.util.i18n$translate_site_locale.invoke(i18n.clj:70)
  at metabase.util.i18n.SiteLocalizedString.toString(i18n.clj:98)
  at metabase.util.encryption$maybe_decrypt$log_error_fn__9632.invoke(encryption.clj:160)
  at metabase.util.encryption$maybe_decrypt.invokeStatic(encryption.clj:173)
  at metabase.util.encryption$maybe_decrypt.doInvoke(encryption.clj:146)
  at metabase.models.setting$db_or_cache_value.invokeStatic(setting.clj:440)
  at metabase.models.setting$db_or_cache_value.invoke(setting.clj:422)
  at metabase.models.setting$get_raw_value.invokeStatic(setting.clj:476)
  at metabase.models.setting$get_raw_value.invoke(setting.clj:450)
  at metabase.models.setting$get_raw_value.invokeStatic(setting.clj:490)
  at metabase.models.setting$get_raw_value.invoke(setting.clj:450)
  at metabase.models.setting$fn__45043.invokeStatic(setting.clj:509)
  at metabase.models.setting$fn__45043.invoke(setting.clj:507)
  at metabase.util.i18n.impl$fn__3907$f__3908.invoke(impl.clj:216)
  at metabase.util.i18n.impl$site_locale_from_setting.invokeStatic(impl.clj:227)
  at metabase.util.i18n.impl$site_locale_from_setting.invoke(impl.clj:220)
  at metabase.util.i18n$site_locale_string.invokeStatic(i18n.clj:41)
  at metabase.util.i18n$site_locale_string.invoke(i18n.clj:36)
  at metabase.util.i18n$site_locale.invokeStatic(i18n.clj:54)
  at metabase.util.i18n$site_locale.invoke(i18n.clj:51)
  at metabase.util.i18n$translate_site_locale.invokeStatic(i18n.clj:73)
  at metabase.util.i18n$translate_site_locale.invoke(i18n.clj:70)
  at metabase.util.i18n.SiteLocalizedString.toString(i18n.clj:98)
  at metabase.util.encryption$maybe_decrypt$log_error_fn__9632.invoke(encryption.clj:160)
  at metabase.util.encryption$maybe_decrypt.invokeStatic(encryption.clj:173)
  at metabase.util.encryption$maybe_decrypt.doInvoke(encryption.clj:146)
  at metabase.models.setting$db_or_cache_value.invokeStatic(setting.clj:440)
  at metabase.models.setting$db_or_cache_value.invoke(setting.clj:422)
  at metabase.models.setting$get_raw_value.invokeStatic(setting.clj:476)
  at metabase.models.setting$get_raw_value.invoke(setting.clj:450)
  at metabase.models.setting$get_raw_value.invokeStatic(setting.clj:490)
  at metabase.models.setting$get_raw_value.invoke(setting.clj:450)
  at metabase.models.setting$fn__45043.invokeStatic(setting.clj:509)
  at metabase.models.setting$fn__45043.invoke(setting.clj:507)
  at metabase.util.i18n.impl$fn__3907$f__3908.invoke(impl.clj:216)
  at metabase.util.i18n.impl$site_locale_from_setting.invokeStatic(impl.clj:227)
  at metabase.util.i18n.impl$site_locale_from_setting.invoke(impl.clj:220)
  at metabase.util.i18n$site_locale_string.invokeStatic(i18n.clj:41)
  at metabase.util.i18n$site_locale_string.invoke(i18n.clj:36)
  at metabase.util.i18n$site_locale.invokeStatic(i18n.clj:54)
  at metabase.util.i18n$site_locale.invoke(i18n.clj:51)
  at metabase.util.i18n$translate_site_locale.invokeStatic(i18n.clj:73)
  at metabase.util.i18n$translate_site_locale.invoke(i18n.clj:70)
  at metabase.util.i18n.SiteLocalizedString.toString(i18n.clj:98)
  at metabase.util.encryption$maybe_decrypt$log_error_fn__9632.invoke(encryption.clj:160)
  at metabase.util.encryption$maybe_decrypt.invokeStatic(encryption.clj:173)
  at metabase.util.encryption$maybe_decrypt.doInvoke(encryption.clj:146)
  at metabase.models.setting$db_or_cache_value.invokeStatic(setting.clj:440)
  at metabase.models.setting$db_or_cache_value.invoke(setting.clj:422)
  at metabase.models.setting$get_raw_value.invokeStatic(setting.clj:476)
  at metabase.models.setting$get_raw_value.invoke(setting.clj:450)
  at metabase.models.setting$get_raw_value.invokeStatic(setting.clj:490)
  at metabase.models.setting$get_raw_value.invoke(setting.clj:450)
  at metabase.models.setting$fn__45043.invokeStatic(setting.clj:509)
  at metabase.models.setting$fn__45043.invoke(setting.clj:507)
  at metabase.util.i18n.impl$fn__3907$f__3908.invoke(impl.clj:216)
  at metabase.util.i18n.impl$site_locale_from_setting.invokeStatic(impl.clj:227)
  at metabase.util.i18n.impl$site_locale_from_setting.invoke(impl.clj:220)
  at metabase.util.i18n$site_locale_string.invokeStatic(i18n.clj:41)
  at metabase.util.i18n$site_locale_string.invoke(i18n.clj:36)
  at metabase.util.i18n$site_locale.invokeStatic(i18n.clj:54)
  at metabase.util.i18n$site_locale.invoke(i18n.clj:51)
  at metabase.util.i18n$translate_site_locale.invokeStatic(i18n.clj:73)
  at metabase.util.i18n$translate_site_locale.invoke(i18n.clj:70)
  at metabase.util.i18n.SiteLocalizedString.toString(i18n.clj:98)
  at metabase.util.encryption$maybe_decrypt$log_error_fn__9632.invoke(encryption.clj:160)
  at metabase.util.encryption$maybe_decrypt.invokeStatic(encryption.clj:173)
  at metabase.util.encryption$maybe_decrypt.doInvoke(encryption.clj:146)
```

Looks like we're stuck in a loop where it's trying to access the `site-locale` Setting when trying to log an error message in `metabase.util.encryption`... but fetching the setting needs to use `metabase.util.encryption` to decrypt the value.

https://github.com/metabase/metabase/blob/7e3048bf73f6cb7527579446166d054292166163/src/metabase/util/encryption.clj#L160

https://github.com/metabase/metabase/blob/cb65459082797280bfcd4c9bb0e28b0144de3074/src/metabase/models/setting.clj#L495

(decryption happens via Toucan 2 type transformation for `:value`)

We have some existing logic that doesn't i18n messages if the app DB isn't initialized, and I think we should extend that so it prevents infinite loops when we're in the process of fetching `:site-locale` or whatever too. Like maybe change

```clj
(t2/select-one-fn :value Setting :key (setting-name setting-definition-or-name))
```

to 

```clj
(let [setting-name (setting-name setting-definition-or-name)]
  (binding [i18n/*disable-i18n* (if (= setting-name :site-locale)
                                  true
                                  i18n/*disable-i18n*)]
    (t2/select-one-fn :value Setting :key setting-name)))
```

That seems more robust than just not i18n'ing this specific message.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #32376 
Fixes https://github.com/metabase/harbormaster/issues/3963

There was an infinite loop if we tried to fetch the `site-locale` Setting recursively when already fetching it. This could be triggered by logging an error message when attempting to decrypt an encrypted value in the app DB

### CODE REVIEW

File: src/metabase/models/setting.clj [hunk 1]
```diff
@@ -481,18 +481,19 @@
         db-is-set-up? (or (requiring-resolve 'metabase.db/db-is-set-up?)
                           ;; this should never be hit. it is just overly cautious against a NPE here. But no way this
                           ;; cannot resolve
-                          (constantly false))]
+                          (constantly false))
+        db-value      #(t2/select-one-fn :value Setting :key (setting-name setting-definition-or-name))]
```
Comment (camsaul) [inline src/metabase/models/setting.clj:485]: Not really needed anymore but at first I was tweaking code here, and it's nicer to have the fetch-from-DB logic only defined once. Easier to read the rest of the code I think.

File: src/metabase/models/setting.clj [hunk 2]
```diff
@@ -617,10 +618,11 @@
...
     (if (or (nil? enabled?) (enabled?))
-      (if (= *disable-cache* disable-cache?)
-        (getter)
+      ;; optimization: only bind if the value will change. Saves FRACTIONS OF A SECOND
+      (if (and disable-cache? (not *disable-cache*))
         (binding [*disable-cache* disable-cache?]
-          (getter)))
+          (getter))
+        (getter))
       default)))
```
Comment (camsaul) [inline src/metabase/models/setting.clj:626]: There was actually a bug here, if `*disable-cache*` was truthy it would get bound to `false` if the Setting was a normal cached Setting, which was super confusing. Fixed

File: src/metabase/models/setting.clj [hunk 3]
```diff
@@ -615,12 +616,10 @@
...
   (let [{:keys [cache? getter enabled? default]} (resolve-setting setting-definition-or-name)
-        disable-cache?                           (not cache?)]
+        disable-cache?                           (or *disable-cache* (not cache?))]
     (if (or (nil? enabled?) (enabled?))
-      (if (= *disable-cache* disable-cache?)
-        (getter)
-        (binding [*disable-cache* disable-cache?]
-          (getter)))
+      (binding [*disable-cache* disable-cache?]
+        (getter))
```
Comment (camsaul) [inline src/metabase/models/setting.clj:622]: There was actually a bug here: if `*disable-cache*` was truthy it would get stomped on if the Setting in question was a normal cached Setting. Fixed.

Also the "optimization" to avoid `binding` if the value wouldn't change was super duper silly, it saved about a tenth of a microsecond so really not worth making the code more confusing.

File: src/metabase/public_settings.clj [hunk 4]
```diff
@@ -201,6 +201,10 @@
     (application-name-for-setting-descriptions))
   :default    "en"
   :visibility :public
+  :getter     (fn []
+                (let [value (setting/get-value-of-type :string :site-locale)]
+                  (when (i18n/available-locale? value)
+                    value)))
```
Comment (camsaul) [inline src/metabase/public_settings.clj:207]: Not strictly needed for this fix but I noticed the Setting getter did not validate its values and happily returned invalid ones; I fixed this

File: src/metabase/util/i18n/impl.clj [hunk 5]
```diff
@@ -203,31 +203,25 @@
...
-  (atom
-   (fn []
-     (when-let [db-is-set-up? (resolve 'metabase.db/db-is-set-up?)]
-       (when (and (bound? db-is-set-up?)
-                  (db-is-set-up?))
-         (when-let [get-value-of-type (resolve 'metabase.models.setting/get-value-of-type)]
-           (when (bound? get-value-of-type)
-             (let [f (fn [] (get-value-of-type :string :site-locale))]
-               (reset! site-locale-from-setting-fn f)
-               (f)))))))))
```
Comment (camsaul) [inline src/metabase/util/i18n/impl.clj:218]: Here's another dumb optimization that saved about two tenths of a microsecond, it's simply not worth turning our code into a hairball to save a few fractions of a millionth of a second.

```
old impl

Evaluation count : 389046 in 6 samples of 64841 calls.
             Execution time mean : 1.545614 µs
    Execution time std-deviation : 6.218459 ns
   Execution time lower quantile : 1.539294 µs ( 2.5%)
   Execution time upper quantile : 1.552483 µs (97.5%)
                   Overhead used : 1.566506 ns

new impl

Evaluation count : 351720 in 6 samples of 58620 calls.
             Execution time mean : 1.741505 µs
    Execution time std-deviation : 6.093460 ns
   Execution time lower quantile : 1.735728 µs ( 2.5%)
   Execution time upper quantile : 1.750150 µs (97.5%)
                   Overhead used : 1.566506 ns
```

Also `metabase.db.setting/db-or-cache-value` already checks `db-is-set-up?`, so this check was a duplicate.

File: src/metabase/models/setting.clj (hunk 3 above)
Comment (camsaul) [reply src/metabase/models/setting.clj:622]:
```
unoptimized

Evaluation count : 165768 in 6 samples of 27628 calls.
             Execution time mean : 3.758099 µs
    Execution time std-deviation : 346.067313 ns
   Execution time lower quantile : 3.602993 µs ( 2.5%)
   Execution time upper quantile : 4.356128 µs (97.5%)
                   Overhead used : 1.566506 ns

Found 1 outliers in 6 samples (16.6667 %)
	low-severe	 1 (16.6667 %)
 Variance from outliers : 15.8136 % Variance is moderately inflated by outliers

"optimized"

Evaluation count : 173400 in 6 samples of 28900 calls.
             Execution time mean : 3.696985 µs
    Execution time std-deviation : 146.793030 ns
   Execution time lower quantile : 3.590312 µs ( 2.5%)
   Execution time upper quantile : 3.915156 µs (97.5%)
                   Overhead used : 1.566506 ns
```

File: src/metabase/util/i18n/impl.clj [hunk 6]
```diff
@@ -203,31 +203,25 @@
...
+  "Whether we're currently inside a call to [[site-locale-from-setting]], so we can prevent infinite recursion."
+  false)
 
 (defn site-locale-from-setting
-  "Fetch the value of the `site-locale` Setting.
-  When metabase is shutting down, we need to log some messages after the db connection is closed, so we keep around a
-  cached-site-locale for that purpose."
+  "Fetch the value of the `site-locale` Setting, or `nil` if it is unset."
   []
-  (let [cached-site-locale (atom "en")]
```
Comment (camsaul) [inline src/metabase/util/i18n/impl.clj:225]: This `cached-site-locale` introduced #21831 actually doesn't cache anything if you look at the code closely, because we're creating a new atom every time you call the function. So effectively it's just a try-catch that always returns `"en"` in the catch. We have other code that decides `"en"` is the fallback/default, so it's more appropriate to define that only once and return `nil` here on error. This would also return `nil` if the Setting is unset.

File: src/metabase/util/i18n/impl.clj [hunk 7]
```diff
@@ -203,31 +203,25 @@
...
-      (let [site-locale (@site-locale-from-setting-fn)]
-        (reset! cached-site-locale site-locale)
-        site-locale)
-      (catch Exception _ @cached-site-locale))))
+  (when-let [get-value-of-type (resolve 'metabase.models.setting/get-value-of-type)]
+    (when (bound? get-value-of-type)
+      ;; make sure we don't try to recursively fetch the site locale when we're actively in the process of fetching it,
+      ;; otherwise that will cause infinite loops if we try to log anything... see #32376
+      (when-not *in-site-locale-from-setting*
+        (binding [*in-site-locale-from-setting* true]
```
Comment (camsaul) [inline src/metabase/util/i18n/impl.clj:218]: This is the actual fix for the bug

File: test/metabase/public_settings_test.clj [hunk 8]
```diff
@@ -127,41 +127,44 @@
...
-                   (public-settings/site-locale)))))
-
-        (testing "non-existant locale"
-          (mt/with-temporary-setting-values [site-locale "en_US"]
-            (is (thrown-with-msg?
-                 clojure.lang.ExceptionInfo
-                 #"Invalid locale \"en_EN\""
-                 (public-settings/site-locale! "en_EN")))
-            (is (= "en_US"
-                   (public-settings/site-locale)))))))
```
Comment (camsaul) [inline test/metabase/public_settings_test.clj:150]: I split this up into a few smaller tests, looking at a big `deftest` form with a lot of newlines and completely separate test cases was hurting my eyes a bit. Smaller tests = better. Don't put a million assertions in one test unless they actually share state or temp objects or whatever

File: test/metabase/public_settings_test.clj [hunk 9]
```diff
@@ -127,41 +127,44 @@
...
+    (mt/discard-setting-changes [site-locale]
+      (public-settings/site-locale! "es")
+      (public-settings/site-locale! nil)
+      (is (= "en"
+             (public-settings/site-locale))
+          "should default to English"))))
+
+(deftest site-locale-only-return-valid-locales-test
+  (mt/with-temporary-raw-setting-values [site-locale "wow_this_in_not_a_locale"]
+    (is (nil? (public-settings/site-locale)))))
```
Comment (camsaul) [inline test/metabase/public_settings_test.clj:167]: test 1 for the fix

File: test/metabase/util/i18n/impl_test.clj [hunk 10]
```diff
@@ -117,3 +122,32 @@
...
+                (is (encryption/possibly-encrypted-string? (i18n.impl/site-locale-from-setting))
+                    `i18n.impl/site-locale-from-setting))
+              (testing "since the encrypted string is an invalid value for a Locale, high-level functions should return nil"
+                (is (nil? (i18n/site-locale))
+                    `i18n/site-locale)
+                (is (nil? (public-settings/site-locale))
+                    `public-settings/site-locale))
+              (testing "we should still be able to (no-op) i18n stuff"
+                (is (= "Testing"
+                       (i18n/trs "Testing")))))))))))
```
Comment (camsaul) [inline test/metabase/util/i18n/impl_test.clj:153]: actual test for the fix

**Review by bshepherdson — APPROVED** [review]

File: src/metabase/models/setting.clj (hunk 3 above)
Comment (camsaul) [reply src/metabase/models/setting.clj:622]: I have https://github.com/hugoduncan/criterium/ in my user `deps.edn`
