### PR TITLE
Invalidate model caching when updating upload table

### LINKED ISSUE #41630: Uploaded model not showing latest rows appended to the underlying table
### Describe the bug

When appending new rows to an existing Uploaded model it can appear that the action "succeeds" but no new data is actually added. This appears to be an issue with the model however, the underlying table appears to be updated as expected. Perhaps this is a caching issue?

This is sporadic issue and hard to reproduce, but one a given model is being affected the issue persists even when additional appends are made.

You can see the issue in action during [this portion of the Metabase 49 webinar](https://youtu.be/iig0-CoZLbw?si=irWaWpHZMdo7b2LV&t=1358). 🙈 

### To Reproduce

1. Go to [this uploaded model](https://stats.metabase.com/model/17094-pixarmovies)
2. Notice that 27 rows are being shown.
3. Append this file: [Pixar Movies(2).csv](https://github.com/metabase/metabase/files/15038812/Pixar.Movies.2.csv)
4. Wait for upload to succeed and model to refresh.
5. Notice that there are still only 27 rows being shown, i.e. it looks like nothing was appended.
6. Go to a [question that queries the underlying model directly](https://stats.metabase.com/question/17191-pixarmovies-direct-query-to-20240415131022/notebook).
7. Notice that there are a bunch of extra rows, a bunch of duplicates from the file above being appended multiple times.

Converting the model into a native question also appears to resolve the issue.

### Expected behavior

I expect the model to display all the newly appended rows after the upload succeeds.

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Server: stats.metabase.com 
- Built on: 2024-04-17
- Commit: 39cf70c
- Version: pre-50.0
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes https://github.com/metabase/metabase/issues/41630

### Description

With this change we "bust" the related model caches when updating an uploaded table, to avoid surprising behavior where the updates are not visible when viewing those models or their derived questions.

We only consider "trivial" models which don't have any calculated columns, joins, filter, etc 

A gotcha with this approach, is that you are still given the option to update the table from models which *do* have all these potentially expensive operations applied, and then the user will still get the confusing experience of seeing their upload succeed, the question refreshing, and the new data still not being present.

You could argue that such non-trivial models should not expose an "upload" option anyway - I was surprised that they do.

### CODE REVIEW

**Comment by crisptrutski** [comment]
Digression, based on my experience experimenting with these features. 

Rather than having magic behavior on the server side, as a (power) user I would far prefer it if the UI just made it more obvious what was going on, and gave me levers to pull to get what I wanted:

1. Indicate when caches were used.[^1]
2. Indicate when the underlying tables have data newer than the caches.[^2]
3. Give an option to invalidate the relevant caches.[^3]

[^1]: For example the "More Info" section, or a new icon with say some hover text, could show all the models whose caches were used, along with the last update time of their cache. Alternatively a simplified version would just show the oldest timestamp.

[^2]: Knowing when tables in general were last updated is hard, but it's trivial for uploaded tables.

[^3]: An action to invalidate the caches would be the same as toggling the caching off and on again for a basic model, but as soon as you're talking about an arbitrary question querying cached models which themselves could depend on other cached models, which would need to be invalidated from bottom to top, the convenience factor would be a significant improvement.

Additionally, I would not expect a cache to ever be populated or used for a "pass through" model (i.e. just select-table and nothing else). You can make an argument that limiting fields or rows will change query performance, but I don't see the value add for the "alias" models we create for Uploads.

Finally, it seems very strange to me that querying a model which has been queued to be cached will not actually populate the cache. It seems surprising and dangerous that you will repeatedly query the underlying table in the gap between creating it and the next time the model refresh job is run, potentially hours later.

Please take this drive by armchair critique with heaps of salt, as I'm still wet behind the ears on both the product and the codebase.

File: src/metabase/models/persisted_info.clj [hunk 1]
```diff
@@ -117,6 +117,14 @@
   ([conditions-map state]
    (t2/update! PersistedInfo conditions-map {:active false, :state state, :state_change_at :%now})))
 
+(defn invalidate!
+  "Invalidates any caches corresponding to the `conditions-map`. Equivalent to toggling the caching off and on again."
+  [conditions-map]
+  ;; TODO confirm that the corresponding tables will still be cleaned up.
```
Comment (crisptrutski) [inline src/metabase/models/persisted_info.clj:123]: If it doesn't we should rework the caching mechanism itself, since this is no different to what you end up with if you turn it off and on again in the interface.

File: src/metabase/upload.clj [hunk 2]
```diff
@@ -513,6 +514,16 @@
            (field->db-type driver field->new-type)
            args)))
 
+(defn- invalidate-cached-models! [table]
```
Comment (crisptrutski) [inline src/metabase/upload.clj:517]: I've tested this manually, but I'm not sure where to start with writing an automated test. The model caching code is um not that modular. 🍝

Comment (piranha) [reply src/metabase/upload.clj:517]: IDK, maybe the test should capture call to `invalidate!` with correct model-ids?

Comment (crisptrutski) [reply src/metabase/upload.clj:517]: Yeah I guess a mockist test is better than nothing. They are a bit smell in my book though.

Comment (piranha) [reply src/metabase/upload.clj:517]: Yeah, but at least we catch that _some_ logic is executed - to serve as notification if someone removes/breaks it.

Comment (crisptrutski) [reply src/metabase/upload.clj:517]: Added, and glad I did - it found some issues 😄

File: src/metabase/models/persisted_info.clj (hunk 1 above)
Comment (calherries) [reply src/metabase/models/persisted_info.clj:123]: It won't get cleaned up based on this:

https://github.com/metabase/metabase/blob/3c71e3a473a440e17c5fb0e90e35c5ab2e55aeee/src/metabase/task/persist_refresh.clj#L128-L130

The only states that get cleaned up are in `persisted-info/prunable-states`, i.e. `"deletable"` or `"off"` when using EE. If persisted info is in the `"creating"` state it will be persisted here

https://github.com/metabase/metabase/blob/3c71e3a473a440e17c5fb0e90e35c5ab2e55aeee/src/metabase/task/persist_refresh.clj#L60

File: src/metabase/upload.clj [hunk 3]
```diff
@@ -513,6 +514,16 @@
...
+  ;; Find all the models for which this is the "primary table", and there is no meaningful filtering or transformation.
+  (let [model-ids (->> (t2/select [:model/Card :id :dataset_query] :table_id (:id table) :type :model)
+                       (remove (fn [{query :dataset_query}]
+                                 ;; Notably there are no joins or custom columns, which might be expensive.
+                                 (every? #{:source-table :fields :limit} (keys query))))
```
Comment (calherries) [inline src/metabase/upload.clj]: 1. This line depends on the internals of `:dataset_query`, which we should try to limit to MLv2 these days. See `no-joins` in this query for an example.
2. This feels like it will miss models that we'd still want to invalidate, e.g. a simple filter might be applied to the CSV table that excludes certain dirty rows or something. Also a model that just aggregates a CSV upload table should probably be invalidated too. I feel like we can be on the safe side and invalidate more models than we need to. If someone updates a table outside metabase, sure, it's expected that metabase shouldn't update models. But if someone updates a table inside metabase, we should expect that they want to see that data immediately.
3. This will return a false positive match for a model that wraps a more complex model. e.g. consider creating a model using the Orders table joined with People. Then make another model with a simple query selecting from that model, only applying a limit. It will match `model-ids` above, even though the actual query being executed is more complex than a simple select. The solution is to use MLv2 to get `lib/source-table-id` as is used here: https://github.com/metabase/metabase/blob/3c71e3a473a440e17c5fb0e90e35c5ab2e55aeee/src/metabase/upload.clj#L727

My gut feeling now is that simpler is better and we actually want to invalidate the model cache for any model that uses CSV upload data, regardless of the complexity of the query. Using just `table_id` to invalidate all models that use the upload table seems like a good starting point. Ideally we'd want to update even models that use the uploaded table in joins and in native queries too, but that's harder at the moment. Probably @luizarakaki has an opinion on this too

**Comment by calherries** [comment]
> but I don't see the value add for the "alias" models we create for Uploads.

Yeah, maybe we should turn off model caching for uploads for the models we create for uploads. Unfortunately we could only do this easily with EE right now, because turning off model caching for a model is an EE feature.

File: src/metabase/models/persisted_info.clj (hunk 1 above)
Comment (crisptrutski) [reply src/metabase/models/persisted_info.clj:123]: I see we actually use a consistent table name for the cache (`:table-name` on the `persisted-info` row), so this is actually fine - we'll clobber the stale cache during the next refresh cycle.

File: test/metabase/upload_test.clj [hunk 4]
```diff
@@ -1412,6 +1416,59 @@
...
+          (let [table-id    (:id table)
+                csv-rows    ["name" "Luke Skywalker"]
+                file        (csv-file-with csv-rows)
+                other-id    (mt/id :venues)
+                other-table (t2/select-one :model/Table other-id)
+                mp          (lib.metadata.jvm/application-database-metadata-provider (:db_id table))]
+
+            (mt/with-temp [:model/Card {question-id         :id} {:table_id table-id, :dataset_query (mbql mp table)}
+                           :model/Card {model-id            :id} {:table_id table-id, :type :model, :dataset_query (mbql mp table)}
+                           :model/Card {complex-model-id    :id} {:table_id table-id, :type :model :dataset_query (join-mbql mp table other-table)}
```
Comment (calherries) [inline test/metabase/upload_test.clj:1455]: super nit: these commas are inconsistent

File: src/metabase/upload.clj [hunk 5]
```diff
@@ -513,6 +514,38 @@
            (field->db-type driver field->new-type)
            args)))
 
+(defn- mbql? [model]
+  (= "query" (name (:query_type model "query"))))
+
+(defn- no-joins?
+  "Returns true if `query` has no joins in it, otherwise false."
```
Comment (calherries) [inline src/metabase/upload.clj:521]: Not your fault, but I realised this function (written by me) has a small logical bug in that it returns true even if the query has implicit joins in it. We should be explicit here in the docstring:
```suggestion
  "Returns true if `query` has no explicit joins in it, otherwise false."
```

Comment (calherries) [reply src/metabase/upload.clj:521]: Model FKs are currently not implemented, and CSV upload tables are unlikely to have FKs set up, because that requires database privileges most CSV upload users wouldn't use. But that might change so you could leave a TODO here for now

File: test/metabase/upload_test.clj (hunk 4 above)
Comment (crisptrutski) [reply test/metabase/upload_test.clj:1455]: meta nit: Are super nits the opposite of pico nits? 😄

**Review by calherries — COMMENTED** [review]
All this looks good, the only thing missing is test coverage that `invalidate!` adheres to its spec. Alternatively, we could test `invalidate!` indirectly and actually test the bug end-to-end, by checking that query results get updated after append with model persistence enabled. You can use the `mt/with-persistence-enabled` macro like so:
```
(mt/with-persistence-enabled [persist-models!] ...  (persist-models!) ...)
```

see here for an example of its usage
https://github.com/metabase/metabase/blob/435f9acbad63b434c08291d1306dd450eec80777/test/metabase/query_processor/persistence_test.clj#L63

**Comment by crisptrutski** [comment]
> All this looks good, the only thing missing is test coverage that `invalidate!` adheres to its spec. 

Thanks for the pointer on making it end-to-end, the test is much stronger now - even finding a critical bug 🐛 😅

File: test/metabase/upload_test.clj [hunk 6]
```diff
@@ -384,11 +388,13 @@
                 (is (not= (:id table-1)
                           (:id table-2)))))))))))
 
-(defn- query-table
-  [table]
-  (qp/process-query {:database (:db_id table)
+(defn- query [db-id source-table]
```
Comment (calherries) [inline test/metabase/upload_test.clj:391]: with dynamic typing it always pays to be consistent with names and types, so I'd suggest renaming this
```suggestion
(defn- query [db-id source-table-id]
```

**Review by calherries — APPROVED** [review]
Looks good!

File: test/metabase/upload_test.clj (hunk 6 above)
Comment (crisptrutski) [reply test/metabase/upload_test.clj:391]: This argument stumped me a bit, because it could either be a numeric table id or string card reference. I felt like playing it safe so used the same name as the key it's assigned to.
