### PR TITLE
[MLv2] Fix template-tags snippet-id

### LINKED ISSUE #33546: [MLv2] `template-tags` returns tags with `snippet_id` when `snippet-id` is expected

### PR DESCRIPTION
**Pull request by snoe**
Resolves #33546 

Looking at this bug I found there were a couple problems that the converters were not properly handling. First, the conversion to js was copying snake case to kebab case instead of renaming. Second the conversion to clojure was not picking up kebab case keys but using the snake case keys.

So I dropped the TemplateTag encoder and decoder and went forward with js->clj and clj->js since the only tricky part was keeping the tag names as strings and keeping the :type as keyword.

### CODE REVIEW

File: test/metabase/lib/js_test.cljs [hunk 1]
```diff
@@ -85,3 +86,22 @@
...
+  (let [db                meta/database
+        metadata-provider (lib.tu/mock-metadata-provider {:snippets {"my snippet" {:snippet-id 19
+                                                                                   :content "where 1 = 1"}}})
+        snippets {"snippet: my snippet"
+                  {:type :snippet
+                   :name "snippet: my snippet",
+                   :id "fd5e96f7-08f8-486b-9919-b2ab72857db4",
+                   :display-name "Snippet: My Snippet",
+                   :snippet-name "my snippet",
+                   :snippet-id 1}}
```
Comment (metamben) [inline test/metabase/lib/js_test.cljs:100]: Is it important that here we have `:snippet-id 1`  and in the metadata provider `:snippet-id 19`? I mean is this what we expect to encounter in the wild?

**Review by metamben — APPROVED** [review]
LGTM. The test could have a reference to the issue fixed in this PR.

File: test/metabase/lib/js_test.cljs (hunk 1 above)
Comment (snoe) [reply test/metabase/lib/js_test.cljs]: The mock metadata should have been dropped, snippets are not in metadata at the moment. Perhaps they should be as the FE currently fills in the ids.
