### PR TITLE
Don't log a full exception when fetching a dashboard that has a stray param

### LINKED ISSUE #15494: Dashboard generates exception log, when dashboard filter is connected to a filter that doesn't exist in card anymore
**Describe the bug**
An error rendering a dashboard for a hosting customer is happening with extreme frequency.

**Logs**

```text
2021-04-06 03:38:45,629 ERROR models.params :: Could not find matching Field ID for target: [:dimension [:template-tag NEM_WEEK]]
clojure.lang.ExceptionInfo: Input to unwrap-field-clause does not match schema: 
	 [0;33m  [(named (named (not (some-matching-condition? nil)) "Must be a valid instance of one of these clauses: :field-id, :field-literal, :joined-field, :fk->, :datetime-field, :expression, :binning-strategy") clause)] [0m 
	at metabase.mbql.util$fn__21843$unwrap_field_clause__21848.invoke(util.clj:433) ~[metabase.jar:?]
	at metabase.models.params$fn__42015$unwrap_field_clause__42020$fn__42021.invoke(params.clj:32) ~[metabase.jar:?]
	at metabase.models.params$fn__42015$unwrap_field_clause__42020.invoke(params.clj:24) ~[metabase.jar:?]
	at metabase.models.params$fn__42068$param_target__GT_field_clause__42073$fn__42074.invoke(params.clj:70) ~[metabase.jar:?]
	at metabase.models.params$fn__42068$param_target__GT_field_clause__42073.invoke(params.clj:62) ~[metabase.jar:?]
	at metabase.models.params$fn__42171$dashboard__GT_parameter_mapping_field_clauses__42176$fn__42177$iter__42178__42184$fn__42185$iter__42180__42186$fn__42187$fn__42188.invoke(params.clj:178) ~[metabase.jar:?]
	at metabase.models.params$fn__42171$dashboard__GT_parameter_mapping_field_clauses__42176$fn__42177$iter__42178__42184$fn__42185$iter__42180__42186$fn__42187.invoke(params.clj:176) ~[metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[metabase.jar:?]
	at clojure.lang.RT.seq(RT.java:535) ~[metabase.jar:?]
	at clojure.core$seq__5402.invokeStatic(core.clj:137) ~[metabase.jar:?]
	at clojure.core$seq__5402.invoke(core.clj:137) ~[metabase.jar:?]
	at metabase.models.params$fn__42171$dashboard__GT_parameter_mapping_field_clauses__42176$fn__42177$iter__42178__42184$fn__42185.invoke(params.clj:176) ~[metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[metabase.jar:?]
	at clojure.lang.RT.seq(RT.java:535) ~[metabase.jar:?]
	at clojure.core$seq__5402.invokeStatic(core.clj:137) ~[metabase.jar:?]
	at clojure.core$seq__5402.invoke(core.clj:137) ~[metabase.jar:?]
	at metabase.models.params$fn__42171$dashboard__GT_parameter_mapping_field_clauses__42176$fn__42177.invoke(params.clj:176) ~[metabase.jar:?]
	at metabase.models.params$fn__42171$dashboard__GT_parameter_mapping_field_clauses__42176.invoke(params.clj:172) ~[metabase.jar:?]
	at metabase.models.params$fn__42236$dashboard__GT_param_field_ids__42241$fn__42242.invoke(params.clj:200) ~[metabase.jar:?]
	at metabase.models.params$fn__42236$dashboard__GT_param_field_ids__42241.invoke(params.clj:194) ~[metabase.jar:?]
	at metabase.models.params$fn__42264.invokeStatic(params.clj:215) ~[metabase.jar:?]
	at metabase.models.params$fn__42264.invoke(params.clj:214) ~[metabase.jar:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:229) ~[metabase.jar:?]
	at clojure.lang.Var.invoke(Var.java:384) ~[metabase.jar:?]
	at toucan.hydrate$simple_hydrate$iter__33575__33579$fn__33580.invoke(hydrate.clj:262) ~[metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[metabase.jar:?]
	at clojure.lang.LazySeq.first(LazySeq.java:73) ~[metabase.jar:?]
	at clojure.lang.RT.first(RT.java:692) ~[metabase.jar:?]
	at clojure.core$first__5384.invokeStatic(core.clj:55) ~[metabase.jar:?]
	at clojure.core$first__5384.invoke(core.clj:55) ~[metabase.jar:?]
	at toucan.hydrate$hydrate.invokeStatic(hydrate.clj:433) ~[metabase.jar:?]
	at toucan.hydrate$hydrate.doInvoke(hydrate.clj:343) ~[metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:464) ~[metabase.jar:?]
	at metabase.api.dashboard$get_dashboard.invokeStatic(dashboard.clj:211) ~[metabase.jar:?]
	at metabase.api.dashboard$get_dashboard.invoke(dashboard.clj:206) ~[metabase.jar:?]
	at metabase.api.dashboard$fn__68452.invokeStatic(dashboard.clj:252) ~[metabase.jar:?]
	at metabase.api.dashboard$fn__68452.invoke(dashboard.clj:249) ~[metabase.jar:?]
	at compojure.core$wrap_response$fn__11944.invoke(core.clj:160) ~[metabase.jar:?]
	at compojure.core$wrap_route_middleware$fn__11928.invoke(core.clj:132) ~[metabase.jar:?]
	at compojure.core$wrap_route_info$fn__11933.invoke(core.clj:139) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:151) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:153) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956.invoke(core.clj:200) ~[metabase.jar:?]
	at metabase.server.middleware.auth$enforce_authentication$fn__55043.invoke(auth.clj:14) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956.invoke(core.clj:200) ~[metabase.jar:?]
	at compojure.core$make_context$handler__11984.invoke(core.clj:287) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:296) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:297) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:297) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:297) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:297) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:297) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:199) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:297) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:297) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:297) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956.invoke(core.clj:200) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956.invoke(core.clj:200) ~[metabase.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:160) ~[metabase.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[metabase.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:665) ~[metabase.jar:?]
	at clojure.core$apply.invoke(core.clj:660) ~[metabase.jar:?]
	at metabase.server.routes$fn__80946$fn__80947.doInvoke(routes.clj:57) ~[metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:436) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956.invoke(core.clj:200) ~[metabase.jar:?]
	at compojure.core$make_context$handler__11984.invoke(core.clj:287) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:296) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$wrap_route_matches$fn__11937.invoke(core.clj:152) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:199) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957$respond_SINGLEQUOTE___11958.invoke(core.clj:197) ~[metabase.jar:?]
	at compojure.core$make_context$fn__11986.invoke(core.clj:297) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956.invoke(core.clj:200) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956$f__11957.invoke(core.clj:198) ~[metabase.jar:?]
	at compojure.core$routes$fn__11956.invoke(core.clj:200) ~[metabase.jar:?]
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__79024.invoke(exceptions.clj:96) ~[metabase.jar:?]
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__79021.invoke(exceptions.clj:84) ~[metabase.jar:?]
	at metabase.server.middleware.log$log_api_call$fn__80862$fn__80863.invoke(log.clj:195) ~[metabase.jar:?]
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216) ~[metabase.jar:?]
	at toucan.db$_do_with_call_counting.invoke(db.clj:209) ~[metabase.jar:?]
	at metabase.server.middleware.log$log_api_call$fn__80862.invoke(log.clj:189) ~[metabase.jar:?]
	at metabase.server.middleware.security$add_security_headers$fn__78987.invoke(security.clj:142) ~[metabase.jar:?]
	at metabase.server.middleware.json$wrap_json_body$fn__80643.invoke(json.clj:62) ~[metabase.jar:?]
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__80661.invoke(json.clj:98) ~[metabase.jar:?]
	at ring.middleware.keyword_params$wrap_keyword_params$fn__81203.invoke(keyword_params.clj:55) ~[metabase.jar:?]
	at ring.middleware.params$wrap_params$fn__81219.invoke(params.clj:69) ~[metabase.jar:?]
	at metabase.server.middleware.misc$maybe_set_site_url$fn__35106.invoke(misc.clj:58) ~[metabase.jar:?]
	at metabase.server.middleware.session$bind_current_user$fn__42732$fn__42733.invoke(session.clj:277) ~[metabase.jar:?]
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:258) ~[metabase.jar:?]
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:250) ~[metabase.jar:?]
	at metabase.server.middleware.session$bind_current_user$fn__42732.invoke(session.clj:276) ~[metabase.jar:?]
	at metabase.server.middleware.session$wrap_current_user_info$fn__42719.invoke(session.clj:236) ~[metabase.jar:?]
	at metabase.server.middleware.session$wrap_session_id$fn__42705.invoke(session.clj:182) ~[metabase.jar:?]
	at metabase.server.middleware.auth$wrap_api_key$fn__55051.invoke(auth.clj:27) ~[metabase.jar:?]
	at ring.middleware.cookies$wrap_cookies$fn__81123.invoke(cookies.clj:216) ~[metabase.jar:?]
	at metabase.server.middleware.misc$add_content_type$fn__35089.invoke(misc.clj:27) ~[metabase.jar:?]
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__35114.invoke(misc.clj:75) ~[metabase.jar:?]
	at ring.middleware.gzip$wrap_gzip$fn__81165.invoke(gzip.clj:86) ~[metabase.jar:?]
	at metabase.server.middleware.misc$bind_request$fn__35117.invoke(misc.clj:92) ~[metabase.jar:?]
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80879.invoke(ssl.clj:48) ~[metabase.jar:?]
	at metabase.server$async_proxy_handler$fn__80476.invoke(server.clj:71) ~[metabase.jar:?]
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) ~[metabase.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[metabase.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[metabase.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[metabase.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [metabase.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [metabase.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [metabase.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [metabase.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [metabase.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [metabase.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [metabase.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [metabase.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [metabase.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [metabase.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [metabase.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [metabase.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [metabase.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Information about your Metabase Installation:**

metabase/metabase-enterprise:v1.38.2

Customer: hosting-6860a89bc8744a3f

**Severity**
Annoying - it is so prevalent in the logs that it's hard to track down other issues with this instance.

### PR DESCRIPTION
**Pull request by qnkhuat**
Resolves #15494 by carefully checking when we can't find a field given param on dashboard and logs a warn message instead.

### CODE REVIEW

File: src/metabase/models/params.clj [hunk 1]
```diff
@@ -100,19 +100,21 @@
...
-            (log/error e (tru "Could not find matching Field ID for target:") target)))))))
+      (let [[_ dimension] target
+            field-form    (if (mbql.u/is-clause? :template-tag dimension)
+                            (template-tag->field-form dimension card)
+                            dimension)]
+        (if (some? field-form)
+          (try
+           (unwrap-field-clause field-form)
+           (catch Exception e
+             (log/error e "Failed to unwrap field" field-form)))
```
Comment (qnkhuat) [inline src/metabase/models/params.clj:116]: try catch here is just to be extra safe because we really don't want this to fail and thrown an error when fetching field

Comment (calherries) [reply src/metabase/models/params.clj:116]: I think we can remove this try/catch clause. There's no "fetching" going on, and unwrapping the field is a pure operation. If there is a failure we'd want to know about it with an exception thrown.

Comment (qnkhuat) [reply src/metabase/models/params.clj]: fair, I've removed the try catch in [20b736a](https://github.com/metabase/metabase/pull/33613/commits/20b736ae8c6cd0b662439e4cd2e8d7cdc1c6448c)

**Review by calherries — DISMISSED** [review]

File: src/metabase/models/params.clj [hunk 2]
```diff
@@ -102,19 +101,18 @@
...
-             (template-tag->field-form dimension card)
-             dimension))
-          (catch Throwable e
-            (log/error e (tru "Could not find matching Field ID for target:") target)))))))
+      (let [[_ dimension] target
+            field-form    (if (mbql.u/is-clause? :template-tag dimension)
+                            (template-tag->field-form dimension card)
+                            dimension)]
+        (when (or (integer? field-form)
+                  (mbql.u/is-clause? :field field-form))
```
Comment (calherries) [inline src/metabase/models/params.clj:114]: I'm confused here. What else can field-form be other than an integer, a field clause, or `nil`? If it can't be anything else, we should explicitly handle `nil`  here rather than have to list all the other types field-form could be.

Comment (qnkhuat) [reply src/metabase/models/params.clj]: `field-form` can be an expression as well, but yea the check should be written as "not expression" rather than checking it's of certain types.

I've updated the log, please help taking another look.

File: src/metabase/models/params.clj [hunk 3]
```diff
@@ -106,19 +106,18 @@
...
     (when (mbql.u/is-clause? :dimension target)
       (let [[_ dimension] target
             field-form    (if (mbql.u/is-clause? :template-tag dimension)
                             (template-tag->field-form dimension card)
                             dimension)]
-        (when (or (integer? field-form)
-                  (mbql.u/is-clause? :field field-form))
-          (unwrap-field-clause field-form))))))
+        (when (and (some? field-form) (not (mbql.u/is-clause? :expression field-form)))
+          (unwrap-field-or-expression-clause field-form))))))
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/models/params.clj:120]: Tamas updated that function and renamed it in https://github.com/metabase/metabase/pull/34262

[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/models/params.clj:120]: it's from here https://github.com/metabase/metabase/pull/34262

File: test/metabase/api/dashboard_test.clj [hunk 4]
```diff
@@ -1769,6 +1791,37 @@
...
+                                               {:cards        [{:id                     -1
+                                                                :card_id                card-id
+                                                                :row                    0
+                                                                :col                    0
+                                                                :size_x                 4
+                                                                :size_y                 4
+                                                                :parameter_mappings     [{:parameter_id "abc"
+                                                                                          :card_id card-id
+                                                                                          :target [:dimension [:field-id (mt/id :venues :id)]]}]}]}))]
+        (is (some? (t2/select-one :model/DashboardCard (:id (first resp))))))))
```
Comment (calherries) [inline test/metabase/api/dashboard_test.clj:1808]: Reading this test description makes me wonder what exactly this test is covering here. Is it just testing that there's no exception? If that's the case you should put that in the testing description, rather than "should work" which is quite general.

File: src/metabase/models/params.clj [hunk 5]
```diff
@@ -111,16 +110,14 @@
   "Parse a Card parameter `target` form, which looks something like `[:dimension [:field-id 100]]`, and return the Field
```
Comment (calherries) [inline src/metabase/models/params.clj:110]: On line 110, why isn't the return type `mbql.s/field` instead of `mbql.s/Field`? Given it can't be an expression

Comment (qnkhuat) [reply src/metabase/models/params.clj:111]: it could be an expression, see https://github.com/metabase/metabase/pull/34262

**Review by calherries — APPROVED** [review]

**Comment by qnkhuat** [comment]
@calherries I put the try-catch back because historically, we've seen ppl report(#8917) loading dashboard fail due to `unwrap-field-or-expression-clause` throwing a schema error.

Even though the previous solution is okay and I can't think of a way it'll fail, but It's close to the release date so I'm trying to be extra safe here.

**Comment by calherries** [comment]
Okay, good idea. The problem now is that this will suppress actual errors that we will never be able to debug because we simply ignore them. Should we restore logging the full exception for those "unknown" errors?

**Review by calherries — CHANGES_REQUESTED** [review]
requesting changes

File: src/metabase/models/params.clj [hunk 6]
```diff
@@ -119,10 +119,11 @@
                             dimension)]
         ;; Being extra safe here since we've got many reports on this cause loading dashboard to fail
         ;; for unknown reasons. See #8917
-        (u/prog1 (u/ignore-exceptions
-                  (unwrap-field-or-expression-clause field-form))
-         (when-not <>
-           (log/warn "Could not find matching Field or Expression for target:" target)))))))
+        (when field-form
```
Comment (qnkhuat) [inline src/metabase/models/params.clj:122]: `param-target->field-clause` does not guarantee to return a `field`, so we don't need the warning for field not found

**Comment by calherries** [comment]
I had the impression the problem was that the warning logged the full exception, and we should still log something. Your [first commit](https://github.com/metabase/metabase/pull/33613/commits/ded894772b4cb064da8b770d2ef80ff5c8056ff1) did that. I'm not sure what changed.

So basically if it's a stray param:
```diff
+ (log/error "Could not find matching Field ID for target:" target)
- (log/error e "Could not find matching Field ID for target:" target)
```
But if there's some other exception, we still do:
```
(log/error e "Failed unwrap field form" field-form)
```

What do you think?

**Comment by qnkhuat** [comment]
Previously the `param-target->field-clause` had the schema `mbql.s/field` now it's `[:maybe mbqls.field]`.

So I think we no longer need a "Could not find matching Field ID for target:" log because the function doesn't promise to return one, it was changed recently in https://github.com/metabase/metabase/commit/a597d5ef2f3058962aa28b968dabcb89d0d043c3#diff-86a8f1d5b67465f8646c822bf102c69d51fb9dd05f271671aa05228ea8e4c1fb


about logging the error, yeah I can put that back.

**Comment by calherries** [comment]
I'm confused, that in that [commit](https://github.com/metabase/metabase/commit/a597d5ef2f3058962aa28b968dabcb89d0d043c3#diff-86a8f1d5b67465f8646c822bf102c69d51fb9dd05f271671aa05228ea8e4c1fb) you referenced, the original type is `[:maybe mbql.s/field]`, not `mbql.s/field`. Anyway, I don't see why the return type has anything to do with logging

**Comment by qnkhuat** [comment]
I meant it was changed to add a [:maybe] in that commit.

About the logging, if the function doesn't promise to return one, why do we need to log if we can't find it?

**Comment by qnkhuat** [comment]
anw, I added that log for when a field is not found. I don't strongly believe in the need for it, but it doesn't harm to have it.

**Review by calherries — APPROVED** [review]

**Comment by calherries** [comment]
Looks like you'll need to update the test too, but feel free to merge once that's updated
