### PR TITLE
fix: update saml20 for full SAML SLO support

### LINKED ISSUE #46605: Single Logout Fails for Okta
### Describe the bug

If you enabled SLO for Okta the logout fails when initiated from Metabase.

### To Reproduce

1. Set up Metabase v49
2. Create a keystore for signing SSO requests & export the cert in PEM format
3. Set up a test SAML application in Okta
Enable single logout in Okta (it requires digital signing)
4. Set up SAML in Metabase with the keystore you created and the Okta settings
5. Set up a test Okta user
6. Login via SSO as the test user in Okta
7. Note that logging in with the signed request works as expected
8. Try to logout
9. See "error 400" page

### Expected behavior

SLO should work with Okta

### Logs

_No response_

### Information about your Metabase installation

```JSON
v49
```

### Severity

annoying

### Additional context

I suspect that we're failing to sign the the SLO request and that we're supposed to be directing the logout request to Oktas SLO endpoint (it looks like we may be hitting their sso endpoint instead).**Handy links**

**Okta docs:**
- [Enable SLO for SAML integrations](https://help.okta.com/en-us/content/topics/apps/apps_single_logout.htm)
- [Configure Single Lgout](https://developer.okta.com/docs/guides/single-logout/saml2/main/)

Quick run through in Loom:
https://www.loom.com/share/9bf0882488ba480c8016a08b5e8002bd

error
settings_okta

### PR DESCRIPTION
**Pull request by edpaget**
Closes https://github.com/metabase/metabase/issues/46605

### Description

Update metabase to use a new version of the saml20-clj library that correctly builds and signs HTTP Redirect requests and provides support for checking LogoutResponses.

Note right now SAML SLO cannot be enabled just through the API it requires the following settings to work correctly:

* saml-slo-enable - must be true
* saml-identity-provider-slo-uri - must be set to the IdP's SLO endpoint
* session-cookie-samesite - must be set to none

For the samesite none cookie to work metabase must be served over SSL. Without this setting Chrome (and other browsers) will not send the cookie when Okta redirects to our SLO endpoint which means we can't sign out the user session.

### How to verify

1. Setup a new SAML SP in Okta
2. Configure metabase to use this SP
3. In the REPL enable saml slo, provide Okta's SLO uri, and set the session cookie samesite to `:none`
4. Attempt to login
5. After login go to log out
6. You should be signed out from both metabase and okta

### Demo

https://github.com/user-attachments/assets/40477645-06f4-4f4d-a5bf-54a2302c2e67

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/sso/api/sso.clj [hunk 1]
```diff
@@ -77,12 +77,14 @@
                          :where  [:= :session.id metabase-session-id]})]
       ;; If a user doesn't have SLO setup on their IdP,
       ;; they will never hit "/handle_slo" so we must delete the session here:
-      (t2/delete! :model/Session :id metabase-session-id)
+      (when-not #p (sso-settings/saml-slo-enabled)
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sso/api/sso.clj:80]: these `#p` calls will probably need to come out

**Review by nvoxland — APPROVED** [review]
