### PR TITLE
Fix rare axis ticks for timeseries axes

### LINKED ISSUE #41281: [dc.js migration] timeseries x-axis sometimes shows fewer ticks
https://metaboat.slack.com/archives/C06G94JTWBS/p1712760628635309

P3 because It happens only in some cases. ECharts automatically hides overlapping ticks.

There is a potential improvement by introducing new intervals such as half a year https://metaboat.slack.com/archives/C064QMXEV9N/p1715962353532299?thread_ts=1715962202.978199&cid=C064QMXEV9N

### PR DESCRIPTION
**Pull request by kulyk**
Fixes #41281

Tunes `maxTicksForChartWidth` calculation to prefer smaller time series intervals in certain cases. A combo of 5px char width and the 10px tick buffer seem to produce readable results

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.ts [hunk 1]
```diff
@@ -206,7 +206,7 @@ function maxTicksForChartWidth(
   chartWidth: number,
   tickFormat: (value: RowValue) => string,
 ) {
-  const PIXELS_PER_CHARACTER = 7;
+  const PIXELS_PER_CHARACTER = 5;
```
Comment (kulyk) [inline frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.ts:209]: That's the main change here

**Review by alxnddr — COMMENTED** [review]
Some charts look way better 🙌 

However, duplicated ticks leaked here:
Screenshot 2024-05-26 at 8 56 00 PM

Seems like ECharts inserted half-year ticks that are formatted just as years

**Comment by kulyk** [comment]
@alxnddr oh, nice catch! I totally missed the tick labels that are duplicated on that screenshot.
I could fix this particular screenshot by tweaking the pixel value a bit more: [`20b1e05`](https://github.com/metabase/metabase/pull/43127/commits/20b1e0576fab595f5d9e2bca01231d335c55b34b) 🥴 But I guess it's still possible to get duplicated ticks under certain conditions. WDYT?

**Review by alxnddr — APPROVED** [review]
