### PR TITLE
Fix formatting of month-of-year when there are 53 weeks in the year

### LINKED ISSUE #51777: YoY vizualisation displays two '1st week' datapoints for year 2025
### Describe the bug

On YoY visualization, the first week of 2025 appears twice:
- Once after week 52 of 2024
- Once correctly aligned with week 1 of previous years
This issue started a few days ago.

Image
https://github.com/user-attachments/assets/994fb0e9-09f7-42f9-99a3-562863d5bc34

### To Reproduce

1. Go to 'New - Question'
2. Select any metric in the summarize section
3. Select 2 grouping options : 
- any timestamp with 'week of year' option
- the same timestamp with 'year' option

### Expected behavior

There should be only one data point for the first week of 2025, positioned consistently with the first week of previous years.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-11-28",
      "tag": "v0.51.6",
      "hash": "fc77ed4"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.25+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.25",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.25+9",
    "os.name": "Linux",
    "os.version": "5.15.0-1072-aws",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  }
}
```

### Severity

 medium-low

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/51777

How to verify:
- New -> Question -> Orders
- Summarize -> Count
- Breakout -> Created At -> Week of Year
- Visualize as a bar chart
- However over the last bar. It should say it's for the 53rd week
- Switch to table viz. It should correctly display the value as 53rd as well.

Screenshot 2025-01-08 at 21 05 21
Screenshot 2025-01-08 at 21 05 25

### CODE REVIEW

File: frontend/src/metabase/lib/formatting/date.tsx [hunk 1]
```diff
@@ -118,8 +118,8 @@ export const DATE_RANGE_FORMAT_SPECS: {
   const DDDoP = "DDDo [days of the year]";
   const DoS = "Do [day of the month]";
   const DoP = "Do [days of the month]";
-  const woS = "wo [week of the year]";
-  const woP = "wo [weeks of the year]";
+  const WoS = "Wo [week of the year]";
```
Comment (ranquild) [inline frontend/src/metabase/lib/formatting/date.tsx:121]: AFAIK this is unreachable code. There cannot be week-of-year ranges in the app, and there is no way to call this function to trigger this behavior. Still, I changed it for consistency.

File: frontend/src/metabase/lib/time-dayjs.unit.spec.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+
+import { parseTimestamp } from "metabase/lib/time-dayjs";
+
+describe("parseTimestamp", () => {
+  afterEach(() => {
+    dayjs.updateLocale(dayjs.locale(), { weekStart: 0 });
+  });
+
+  it("should parse week of year correctly", () => {
+    const daysOfWeek = [0, 1, 2, 3, 4, 5, 6];
```
Comment (ranquild) [inline frontend/src/metabase/lib/time-dayjs.unit.spec.ts:11]: Much easier to read than `Array.from({ length: 7 }, (_, i) => i)` I think

**Review by uladzimirdev — APPROVED** [review]
