### PR TITLE
fix(sdk): Fix ad-hoc question view when clicking into SDK dashboard

### LINKED ISSUE #55114: Drilling on a visualization (e.g. "See these orders") shows the query builder and you have to click "Visualize" first to see the table.
### Describe the bug

It used to immediately show a table.

Image

### To Reproduce

Shoppy

### Expected behavior

Show a table

### Logs

_No response_

### Information about your Metabase installation

```JSON
Shoppy
```

### Severity

p1

### Additional context

_No response_

### LINKED ISSUE #55398: [SDK] Clicking "Visualize" when creating new question shows "Question not found" on master
Rendering `<InteractiveQuestion questionId="new" />` and clicking on "Visualization" shows "Question not found" on master. Does not happen on the latest NPM release, so the offending PR is not yet released or backported.

Image

### PR DESCRIPTION
**Pull request by oisincoveney**
Closes #55114
Closes #55398
Closes EMB-275

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Visualization.tsx [hunk 1]
```diff
@@ -44,11 +43,12 @@ export const QuestionVisualization = ({
   }
 
   // `isCardError: true` when the entity ID couldn't be resolved
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Visualization.tsx:45]: nit: I think we can remove this comment as we don't check for `isCardIdError` anymore

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Visualization.tsx [hunk 2]
```diff
@@ -44,11 +43,12 @@ export const QuestionVisualization = ({
...
-    if (originalId && originalId !== "new") {
+
+  if (!question) {
+    if (originalId) {
       return <QuestionNotFoundError id={originalId} />;
     } else {
-      return <SdkError message={t`Question not found`}></SdkError>;
+      return <SdkError message={t`Question not found`} />;
     }
   }
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Visualization.tsx:53]: oh nice, I suppose we could get rid of the `originalId === "new"` check because we won't be rendering `<Visualization />` anyway if we are still in the query builder.

I wonder if removing `isCardIdError` would break anything though, maybe @WiNloSt or @npretto knows

**Review by heypoom — APPROVED** [review]
Overall logic looks good! Thanks for adding the tests, I completely missed this when implementing `questionId="new"` so that must have broken it - super helpful tests 🙏🏻

File: enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Visualization.tsx (hunk 2 above)
Comment (oisincoveney) [reply enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Visualization.tsx:53]: Yeah, I think `isCardIdError` is double duty. If the question doesn't load, the user won't care _how_ the question doesn't load, but _why_ and that will either come down to some random error that they haven't caused, or the fact that they have a a bad `questionId`.

Comment (WiNloSt) [reply enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Visualization.tsx:53]: as long as tests like this work, I'm cool with removing that `isCardIdError` https://github.com/metabase/metabase/blob/0977fdd97fbdb7070b8ccadf1f7681b1e31fc7b9/e2e/test-component/scenarios/embedding-sdk/static-question.cy.spec.tsx#L43

**Comment by oisincoveney** [comment]
This change is part of the following stack:

- #55254 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

**Comment by heypoom** [comment]
@oisincoveney the new test assertions are passing, let's get this merged 🎉
