### PR TITLE
Fallback to Card's description when sending Pulse

### LINKED ISSUE #20948: Question descriptions are not included in dashboard subscription when inherited from the question
**Describe the bug**
When you add a description to a dashboard card via editing the card's visualization options, we include in dashboard subscription emails under the question's title.

However, if you don't edit the card's description, we will display the description of the underlying question instead, if one exists. However, this is _not_ included in dashboard subscriptions.

**To Reproduce**
1. Create and save any question with a description, and add it to a dashboard
3. Hover over the card, and hover over the `i` icon. Note that the question's description is shown. 
4. Create and send an email dashboard subscription
5. Note that the question description is not included
6. On the dashboard, click "Edit dashboard", then hover over the card and click "Visualization options"
7. Edit the description and then save the dashboard
8. Send another dashboard subscription. Note that the new question description is now included, under the question's title.

**Expected behavior**
We should always include whatever description is shown on the dashboard.

**Severity**
Mild

### PR DESCRIPTION
**Pull request by qnkhuat**
Fix #20948 by fallback to Card's description if Dashcard's visualization settings does not have description.

Thanks @escherize for paring with me 💪.

### CODE REVIEW

**Comment by flamber** [comment]
I don't think this is the correct approach. Dashcard should not automatically include the description from the Card, when adding it.
It sounds like the general problem with Pulses not handling viz_settings very well (or not at all) - issue 3735 is the catch-all, but there's several issues with StaticViz: https://github.com/metabase/metabase/labels/Visualization%2FStatic

**Comment by noahmoss** [comment]
@qnkhuat  Wouldn't this mean that if you change the underlying card description, it won't be reflected on the dashboard (as it is currently?) Can't we just fallback to the card description when generating the subscription email if the dashboard card description is not set?

**Comment by qnkhuat** [comment]
@noahmoss yep! should have think of it in the first place. I updated the PR to fallback to Card's description

**Review by escherize — APPROVED** [review]

File: src/metabase/pulse/render.clj [hunk 1]
```diff
@@ -50,7 +52,8 @@
 (s/defn ^:private make-description-if-needed :- (s/maybe common/RenderedPulseCard)
   [dashcard]
   (when *include-description*
-    (when-let [description (-> dashcard :visualization_settings :card.description)]
+    (when-let [description (or (get-in dashcard [:visualization_settings :card.description])
+                               (db/select-one-field :description Card :id (:card_id dashcard)))]
```
Comment (noahmoss) [inline src/metabase/pulse/render.clj:56]: `render-pulse-card`, which calls this function, already has `card` as an argument. Could you pass that into here rather than reading it from the DB again?

File: src/metabase/pulse/render.clj [hunk 2]
```diff
@@ -48,9 +48,10 @@
                                  :src   (:image-src image-bundle)}])]]]]})))
 
 (s/defn ^:private make-description-if-needed :- (s/maybe common/RenderedPulseCard)
-  [dashcard]
+  [dashcard card]
   (when *include-description*
-    (when-let [description (-> dashcard :visualization_settings :card.description)]
+    (when-let [description (or (get-in dashcard [:visualization_settings :card.description])
+                               ( :description card))]
```
Comment (noahmoss) [inline src/metabase/pulse/render.clj:54]: nit
```suggestion
                               (:description card))]
```

**Review by noahmoss — APPROVED** [review]
