### PR TITLE
Fix a couple of edge cases in column ordering for exports

### LINKED ISSUE #19796: Exports ignore column ordering regression in v0.41.6
**Describe the bug**
Since deploying version 0.41.6, data exports (emailed from pulse or from UI download button) do not respect the configured column order.

**Logs**
Not sure of logs relevant to this issue.

**To Reproduce**
1. Setup a question with at least two columns of the same type (e.g., one group and one aggregation column won't work)
2. Re-order the columns (the default seems to be alphabetic, so use a different order than that)
3. Download results

**Expected behavior**
The columns in the export CSV should be in the same order as configured in the question

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your databases: Postgres
- Metabase version: v0.41.6 (tested and this problem is not present in v0.41.5)
- Metabase hosting environment: AWS Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely? Low. For now I've just downgraded to 0.41.5

**Additional context**

### LINKED ISSUE #19889: Certain visualization_settings can cause empty/missing columns on export
**Describe the bug**
Certain visualization_settings can cause empty/missing columns on export.
Very similar to #19465 (#17753)

**To Reproduce**
1. Native query > Sample Dataset > `select 1 a, 2 b, 3 c` - run query, save question
image
2. Visualization settings > change the order of the column, C A B - run query, save question
image
3. Change the query to `select 1 x, 2 y, 3 c` - do **not** run query, save question - this is likely some thing that Anton fixed in 40/41, where it would update the columns, when you ran the query, but that's not important, the empty export is important.
4. After question is saved, do a browser refresh and export (CSV/XLSX), which now only contains `c` column, since we only renamed `a` and `b`. If we had also renamed `c`=>`z`, then export would have been completely empty.
image
image

Basically the reproduction is a question with the following:
- query = `select 1 x, 2 y, 3 c`
- visualization_settings = `{"table.pivot_column":"A","table.cell_column":"B","table.columns":[{"name":"C","fieldRef":["field","C",{"base-type":"type/Integer"}],"enabled":true},{"name":"A","fieldRef":["field","A",{"base-type":"type/Integer"}],"enabled":true},{"name":"B","fieldRef":["field","B",{"base-type":"type/Integer"}],"enabled":true}]}`

**Information about your Metabase Installation:**
0.41.6

**Additional context**
Thanks to @ds-clearago from #19717

### PR DESCRIPTION
**Pull request by noahmoss**
* Changes the logic in the `validate-table-columns` function I added in #19530 so that it checks that all columns in the viz settings can be found in the results metadata by field ref _or_ by name. This is more correct, since it's the same logic used to determine the final column order in `export-column-order`.
  * This fixes an edge case where a column using binning will have it's `:min-value` or `:max-value` stored as a float in the `field-ref` returned in the column metadata, but stored as an int in the viz settings, causing a comparison of the two `field-refs` to fail.
  * This also fixes the issue in #19889 in which the viz settings stored in the DB for a native query that is edited and saved without re-running are out of date during export.
* Adds `:field_ref` as another key that should be converted to `::table-column-field-ref` during viz setting normalization. This fixes the case that @flamber detailed in #19796.
* Adds a cypress repro for #19889 (thanks @nemanjaglumac for help with this!)

Fixes #19889 and #19796

### CODE REVIEW

**Comment by noahmoss** [comment]
@nemanjaglumac I tried my hand at adding a Cypress repro for #19889, which I'm fixing in this PR, mostly by copying  bits and pieces of other repros. I have two basic tests for native query exports, which are working fine, and a third test which contains the actual repro for the issue, which isn't working. It seems to be an issue with the Cypress export helper function -- the export is being downloaded in my browser and doesn't seem to be intercepted by Cypress. Do you know how to fix this?

File: src/metabase/query_processor/streaming.clj [hunk 1]
```diff
@@ -35,14 +35,15 @@
...
 (defn- validate-table-columms
-  "Validate that all of the field refs in `table-columns` correspond to actual columns in `cols`, if `cols` contains
-  field refs. Returns `nil` if any do not, so that we fall back to using `cols` directly for the export (#19465).
+  "Validate that all of the columns in `table-columns` correspond to actual columns in `cols`, correlating them by
+  field ref or name. Returns `nil` if any do not, so that we fall back to using `cols` directly for the export (#19465).
   Otherwise returns `table-columns`."
   [table-columns cols]
-  (let [col-field-refs (set (remove nil? (map :field_ref cols)))]
-    ;; If there are no field refs in `cols` (e.g. for native queries), we should use `table-columns` as-is
-    (when (or (empty? col-field-refs)
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming.clj:44]: Removed this check, which was a special case for native queries that don't have field refs in their result metadata here, since we can correlate by name instead.

File: shared/src/metabase/shared/models/visualization_settings.cljc [hunk 2]
```diff
@@ -420,11 +420,12 @@
...
 (def ^:private db->norm-table-columns-keys
-  {:name     ::table-column-name
+  {:name      ::table-column-name
    ; for now, do not translate the value of this key (the field vector)
-   :fieldref ::table-column-field-ref
-   :fieldRef ::table-column-field-ref
-   :enabled  ::table-column-enabled})
+   :fieldref  ::table-column-field-ref
+   :field_ref ::table-column-field-ref
+   :fieldRef  ::table-column-field-ref
```
Comment (camsaul) [inline shared/src/metabase/shared/models/visualization_settings.cljc:427]: A suggestion if you have to do more of this in the future:

It might actually be a little easier just to iterate thru all the keys in the map, normalize them, and then map them to the renaming map. I was going to suggest [CSK](https://github.com/clj-commons/camel-snake-kebab) but I guess that wouldn't work for both `:fieldref` **and** `:field-ref`. 

Something like this might work tho:

```clj
(defn- normalize-key [k]
  (keyword (str/lower-case (str/replace (name k) #"_-" ""))))

(defn normalized-rename-keys [m]
  (let [k->norm {:fieldref ::table-column-field-ref}]
    (into {}
          (map (fn [[k v]]
                 [(get k->norm (normalize-key k) k)
                  v]))
          m)))

(normalized-rename-keys {:field_ref 1, :can_count 2}) ; => {::table-column-field-ref 1, :can_count 2}
```

**Review by camsaul — APPROVED** [review]
the backend stuff LGTM.

**Review by flamber — APPROVED** [review]
This works in all the ways I try to break it.
I'm still not completely confident if dropping all column orders is the right approach.
