### PR TITLE
Fix transparent embedding menu option text

### LINKED ISSUE #37525: Sharing menu is empty when sharing is disabled in settings
### Describe the bug

When sharing is disabled in settings, we show an empty popup:

image

### To Reproduce

1. Ensure public sharing is toggled off in settings `/admin/settings/public-sharing` (maybe you'll need a clean installation/DB, not sure)
2. Open any dashboard
3. Click share button
4. See the empty popup

### Expected behavior

Share button should be hidden or disabled

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "21.0.1+12-LTS-29",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "21.0.1",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "21.0.1+12-LTS-29",
    "os.name": "Mac OS X",
    "os.version": "14.1.2",
    "user.language": "en",
    "user.timezone": "Europe/London"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.10 (Homebrew)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.1"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-12-28",
      "src_hash": "a35b887bebfceb8749327caa6f54841c2b12cf3e",
      "tag": "v0.48.2-SNAPSHOT",
      "hash": "a37aacf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by oisincoveney**
Closes https://github.com/metabase/metabase/issues/37525

### Description

Mantine's `Menu.Item` component sets the `color` attribute based on the `disabled` prop, and uses the default colors to set the color to a lighter version of its default gray. 

From [Mantine's v6 repo for `Menu.Item`](https://github.com/mantinedev/mantine/blob/6b214a5a20afc1d48127a1939514191a061352da/src/mantine-core/src/Menu/MenuItem/MenuItem.styles.ts#L31)
```
	'&:disabled': {
      color: theme.colorScheme === 'dark' ? theme.colors.dark[3] : theme.colors.gray[5],
      pointerEvents: 'none',
      userSelect: 'none',
    },
```

With the introduction of [Use colors by names PR](https://github.com/metabase/metabase/pull/37443), we set all of the default Mantine colors to `transparent`, which causes issues when we use Mantine components which rely on those default colors for the states we haven't accounted for yet, such as the disabled state of the `Menu.Item` component. This PR explicitly states the color for this state to the `text-light` color.

### How to verify

* Disable embedding and public sharing in the admin settings
* Go to a dashboard or a question
* Open the Sharing/Embedding menu
* See that both options are visible and the text is `text-light`, not `transparent`

### Before/After

_**Before** (on master)_ 
image

The CSS on the `Menu.Item:disabled` property
image

_**After** (on this PR branch)_

image

The CSS on the `Menu.Item:disabled` property (notice the override that I put here, which comes from `metabase/ui/components/overlays/Menu/Menu.styled.tsx`)
image

### CODE REVIEW

**Comment by oisincoveney** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #37547** <a href="https://app.graphite.dev/github/pr/metabase/metabase/37547?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/37547?utm_source=stack-comment).

File: frontend/src/metabase/dashboard/components/EmbedMenu/AdminEmbedMenu.tsx [hunk 1]
```diff
@@ -69,15 +69,13 @@ export const AdminEmbedMenu = ({
           onClick={() => setMenuMode("public-link-popover")}
         >
           {isPublicSharingEnabled ? (
-            <Title c="inherit" order={4}>
+            <Title order={4}>
               {hasPublicLink ? t`Public link` : t`Create a public link`}
             </Title>
           ) : (
             <Stack spacing="xs">
-              <Title c="inherit" order={4}>
```
Comment (oisincoveney) [inline frontend/src/metabase/dashboard/components/EmbedMenu/AdminEmbedMenu.tsx:77]: The `inherit` property isn't needed here, it was needed before for some coloring reasons but it seems to work fine without it now

File: frontend/src/metabase/ui/components/overlays/Menu/Menu.styled.tsx [hunk 2]
```diff
@@ -27,6 +27,10 @@ export const getMenuOverrides = (): MantineThemeOverride["components"] => ({
             color: theme.fn.themeColor("brand"),
           },
         },
+
```
Comment (oisincoveney) [inline frontend/src/metabase/ui/components/overlays/Menu/Menu.styled.tsx:30]: The override for the `Menu.Item:disabled -> color` that I mention in the PR description

**Review by ranquild — APPROVED** [review]

**Review by deniskaber — APPROVED** [review]
