### PR TITLE
fix(sdk): introduce `.mb-wrapper` to scope down our css

### LINKED ISSUE #50279: [SDK] if the sdk is imported after the css of the host app, the body and h1 tags takes the styles from core app
This is mostly an edge case that reproduces https://github.com/metabase/metabase/issues/44802

This will affect anyone using next as they'll need to lazy load the sdk components to disable ssr

Image

https://github.com/user-attachments/assets/d43c8267-9a77-42bd-b2e4-347a5e91913d

### PR DESCRIPTION
**Pull request by npretto**
Fixes https://github.com/metabase/metabase/issues/50279

# Context
When the embedding sdk is imported on a project, all the css used by the app is loaded.
Even though we use a mix of emotion and css modules, both can "leak" styles in the host app if they target plain tags, such as `button`, `div`, `body` etc 

# Description

This PR adds a `mb-wrapper` class to the body (in the core app) and to the "public component wrapper" (for the sdk) so that our styles can be scoped to that class.

## Problem 

We can't _simply_ do `button` -> `.mb-wrapper button`, as that will increase the specificity from (0,0,1) to (0,1,1) and will break stuff:
image
image

## Solution
Use `:where()`:
> The difference between :where() and [:is()](https://developer.mozilla.org/en-US/docs/Web/CSS/:is) is that :where() always has 0 [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity), whereas :is() takes on the specificity of the most specific selector in its arguments.

([from mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/:where))

`:where` can be used to add selectors without increasing specificity:
image

# Note about scope and backporting

We need to backport the sdk changes up to the v51 release branch in order to make it go out in sdk version that's compatible with version 51 (see the [docs about sdk versions](https://www.metabase.com/docs/latest/embedding/sdk/version)).
For this reason, even though there are more places that use "unscoped" plain tags selectors in our css files, I find it safer to address them one-by-one as we find them, as changing a css file has a potentially huge blast radius.

# Open questions
- is `mb-wrapper` a unique enough name or do we think customers may use that? if so, what name should be use?
- will this break anything? Do we have visual regression tests on the core app? It seems we don't have percy anymore

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx [hunk 1]
```diff
@@ -37,6 +38,18 @@ export const PublicComponentStylesWrapper = styled.div`
     display: inline;
   }
 `;
+
+export const PublicComponentStylesWrapper = (
```
Comment (npretto) [inline enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx:42]: Had to make a wrapper (on the wrapper 🫠) to add the `mb-wrapper` className on all instances. The class is needed to make the component work correctly.

File: .storybook/preview.tsx [hunk 2]
```diff
@@ -42,15 +42,20 @@ const globalStyles = css`
...
-        <EmotionCacheProvider>
-          <ThemeProvider>
-            <Global styles={globalStyles} />
-            <CssVariables />
-            {renderStory()}
-          </ThemeProvider>
-        </EmotionCacheProvider>
-      ),
+      renderStory => {
+        if (!document.body.classList.contains("mb-wrapper")) {
```
Comment (npretto) [inline .storybook/preview.tsx:46]: This is needed to make storybook work correctly

**Review by ranquild — APPROVED** [review]

File: .storybook/preview.tsx (hunk 2 above)
Comment (WiNloSt) [reply .storybook/preview.tsx:46]: This looks hacky. I tried putting this in `.storybook/preview-body.html`

```html
<body class="mb-wrapper"></body>
```

and it worked as expected. Can you try that?

Screenshot 2024-11-29 at 8 41 57 PM

File: enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx [hunk 3]
```diff
@@ -37,6 +38,18 @@ export const PublicComponentStylesWrapper = styled.div`
...
+  props: React.ComponentProps<"div">,
+) => {
+  return (
+    <PublicComponentStylesWrapperInner
+      {...props}
+      // eslint-disable-next-line react/prop-types -- className is in div props :shrugs:
+      className={`mb-wrapper ${props.className}`}
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx:49]: we could be a little cleaner with `className` by using `cx` from `className` which should handle spacing automatically when `props.className` is undefined.

**Review by WiNloSt — APPROVED** [review]
Looks good to me, but let's see if we could make storybook render less hacky.

File: .storybook/preview.tsx (hunk 2 above)
Comment (npretto) [reply .storybook/preview.tsx:46]: @WiNloSt I think that will also apply to the sdk stories though, I don't think that's good as we'd miss all the issues that happen when our components are rendered outside
Out of scope for this pr, but I wish we had an entire different storybook for the sdk

Comment (WiNloSt) [reply .storybook/preview.tsx:46]: Good point. Let's keep this as is.

**Comment by npretto** [comment]
@metabase-bot backport release-x.51.x
