### PR TITLE
fix ssl connection logic for new databases added in setup

### LINKED ISSUE #1304: failing to add ssl based database connections from setup
error will result regardless of database type or location if the connection needs to happen over ssl.

### PR DESCRIPTION
**Pull request by agilliland**
add back the ssl and non-ssl database connection try logic which went missing when we moved setup over to react/redux.  fixes #1304

### CODE REVIEW

**Comment by agilliland** [comment]
@tlrobinson , could use a quick check on this one to validate that adding ssl based dbs from setup is working again.

File: frontend/src/setup/components/DatabaseStep.jsx [hunk 1]
```diff
@@ -37,25 +37,47 @@ export default class DatabaseStep extends Component {
...
             await this.props.dispatch(validateDatabase(details));
 
-            // now that they are good, store them
-            this.props.dispatch(setDatabaseDetails({
-                'nextStep': ++this.props.stepNumber,
-                'details': details
-            }));
+        } catch (error) {
+            let formError = error;
+            if (details.details.ssl === true) {
```
Comment (tlrobinson) [inline frontend/src/setup/components/DatabaseStep.jsx]: Is the check for `ssl === true` actually necessary? Isn't it always going to be since we explicitly set it above?

Comment (agilliland) [inline frontend/src/setup/components/DatabaseStep.jsx]: yeah, true.  i'll trim that out and remove the extra code.
