### PR TITLE
Fix actions menu permission checks

### LINKED ISSUE #44854: Users with "No Query Access" receive Incorrect error when trying to promote Questions to models
### Describe the bug

If a user does not have access to create queries for a database they are presented the option in the GUI to promote Questions for that Database to models. If they attempt to do so they're presented with the error: "Variables in models aren't supported yet" even though the questions do not have variables.

### To Reproduce

1. Spin up a new Metabase instance (v50)
2. Create a simple Question from the Sample DB and call is "Test Question"
3. Create a test user
4. Set "Create Queries" data permission to "No" for hte "All Users" group on the Sample DB
5. Log in as test user
6. Navigate to "Test Question" and attempt to convert it into a model
7. Error says "Variables in models aren't supported yet"

### Expected behavior

I am unclear on whether users with this access level should be able to promote questions to models or not. Either this should work or, if they're not able to do this, the option should be removed or the error message corrected.

### Logs

[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:10-05:00 DEBUG metabase.server.middleware.log GET /api/ee/audit-app/user/audit-info 200 4.5 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (2 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 24.3 ms (8 DB calls) App DB connections: 1/15 Jetty threads: 7/50 (2 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 30.0 ms (13 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (2 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 9.2 ms (2 DB calls) App DB connections: 2/15 Jetty threads: 10/50 (1 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 7.1 ms (1 DB calls) App DB connections: 4/15 Jetty threads: 10/50 (1 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 17.6 ms (6 DB calls) App DB connections: 2/15 Jetty threads: 9/50 (1 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/database 200 23.4 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (1 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/search 200 34.0 ms (5 DB calls) App DB connections: 1/15 Jetty threads: 7/50 (1 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/timeline 200 7.2 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 8/50 (1 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/card/120 200 67.1 ms (19 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (1 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/search 200 38.8 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (1 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:23-05:00 DEBUG metabase.server.middleware.log GET /api/alert/question/120 200 8.0 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (2 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:24-05:00 WARN metabase.api.query-metadata Some (possibly virtual) tables are not readable by the current user
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:24-05:00 WARN metabase.api.query-metadata Error in dashboard metadata :database 1: You don't have permissions to do that.
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:24-05:00 DEBUG metabase.server.middleware.log GET /api/card/120/query_metadata 200 77.2 ms (26 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (2 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:24-05:00 DEBUG metabase.server.middleware.log GET /api/collection/8 200 10.6 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (2 idle, 0 queued) (75 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:24-05:00 DEBUG metabase.server.middleware.log POST /api/card/120/query 202 [ASYNC: completed] 196.5 ms (26 DB calls) App DB connections: 1/15 Jetty threads: 5/50 (2 idle, 0 queued) (78 total active threads) Queries in flight: 0 (0 queued); h2 DB 1 connections: 0/1 (0 threads blocked) {:metabase-user-id 2}
[2295ac22-8263-4a0f-9c0f-88fca6df06d1] 2024-06-27T15:41:24-05:00 WARN metabase.server.middleware.log GET /api/database/1 403 9.0 ms (2 DB calls) {:metabase-user-id 2} 
"You don't have permissions to do that."

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "athena",
      "mysql",
      "sqlserver",
      "h2",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-25",
      "tag": "v1.50.7",
      "hash": "431cd8f"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

### Additional context

In permissions the deprecation message for "No Self Service" also contains a link to documentation that does not exist anymore.

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/44854

Changes:
- No `Edit query definition` without data OR collection permissions. `Edit metadata` is still available with collection permissions only
- Make `Turn into a model` / `Turn back to saved question` available without data permissions; only collection permissions required.

### CODE REVIEW

**Review by nemanjaglumac — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx [hunk 1]
```diff
@@ -150,8 +154,8 @@ export const QuestionActions = ({
     ),
   );
 
-  if (canWrite) {
-    if (isModelOrMetric) {
+  if (hasCollectionPermissions) {
+    if (isModelOrMetric && hasDataPermissions) {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx:158]: Change 1

File: frontend/src/metabase-lib/v1/metadata/utils/models.ts [hunk 2]
```diff
@@ -86,21 +86,12 @@ function isSupportedTemplateTagForModel(tag: TemplateTag) {
...
-function checkDatabaseSupportsModels(database?: Database | null) {
-  return database && database.hasFeature("nested-queries");
-}
-
 export function checkDatabaseCanPersistDatasets(database?: Database | null) {
   return database && database.supportsPersistence() && database.isPersisted();
 }
 
 export function checkCanBeModel(question: Question) {
-  if (!checkDatabaseSupportsModels(question.database())) {
```
Comment (ranquild) [inline frontend/src/metabase-lib/v1/metadata/utils/models.ts:98]: Change 2 - this code disallowed converting a question into a model for nodata users because they didn't have access to `database`

File: frontend/src/metabase/query_builder/actions/models.js [hunk 3]
```diff
@@ -67,7 +67,7 @@ export const turnQuestionIntoDataset = () => async (dispatch, getState) => {
   );
 };
 
-export const turnDatasetIntoQuestion = () => async (dispatch, getState) => {
+export const turnModelIntoQuestion = () => async (dispatch, getState) => {
```
Comment (nemanjaglumac) [inline frontend/src/metabase/query_builder/actions/models.js:70]: <3

**Review by nemanjaglumac — APPROVED** [review]
