### PR TITLE
Fix scalar value font-size on dashboards not rendered properly the first time

### LINKED ISSUE #29304: Scalar value font size noticeable delay on dashboards
**Describe the bug**
Scalar values in dashboard cards have noticeable delay in rendering the full font-size.

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Make an X-ray of Product table
2. Go to automatically generated dashboard "A look at your Products table"
3. Look at the first two cards in this dashboard and notice how the initial font size is small but then abruptly scales to the full font size about 1s later

**Expected behavior**
The transition should either be smooth or we shouldn't display the initial small font size.

**Screenshots/videos**
https://www.loom.com/share/7621add49aad47839d290b191eb598c8

**Severity**
Cosmetic, but it can be quite distracting especially if a dashboard has a lot of scalar cards

**Additional context**
Seems to be related to https://github.com/metabase/metabase/pull/24028 (cc @alxnddr )

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/29304

### Description

Uses similar approach described in https://github.com/metabase/metabase/pull/31963#diff-48d6f4802294f837678e90fda148a480099b0db885a58fb28347d64fb16c062cR109-R110. It makes sense to use `debounceLeading` instead `debounce` so that `ExplicitSize` will calculate size on the first render, not waiting after some wait time before calculating the size which caused the bug.

### How to verify

1. Create a scalar question
1. Create a dashboard with 2 tabs
1. Put a scalar question in both tabs and click save
1. Switch back and forth between tabs

#### Before
before

#### After
after

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx [hunk 1]
```diff
@@ -538,7 +538,7 @@ Visualization.defaultProps = defaultProps;
 export default _.compose(
   ExplicitSize({
     selector: ".CardVisualization",
-    refreshMode: props => (props.isVisible ? "throttle" : "debounce"),
+    refreshMode: props => (props.isVisible ? "throttle" : "debounceLeading"),
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx:541]: Uses similar approach described in https://github.com/metabase/metabase/pull/31963#diff-48d6f4802294f837678e90fda148a480099b0db885a58fb28347d64fb16c062cR109-R110. It makes sense to use debounceLeading instead debounce so that ExplicitSize will calculate size on the first render, not waiting after some wait time before calculating the size which caused the bug.

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+describe("issue 29304", () => {
+  describe("display: scalar", () => {
+    beforeEach(() => {
+      restore();
+      cy.signInAsAdmin();
+      cy.intercept("api/dashboard/*/dashcard/*/card/*/query").as(
+        "getDashcardQuery",
+      );
+      cy.intercept("api/dashboard/*").as("getDashboard");
+      cy.clock();
```
Comment (WiNloSt) [inline e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js:48]: mock clock so we could make sure we assert the visualization on the first render.

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+      });
+    });
+  });
+});
+
+// Use full-app embedding to test because `ExplicitSize` checks for `isCypressActive`,
+// which checks `window.Cypress`, and will disable the refresh mode on Cypress test.
+// If we test by simply visiting the dashboard, the refresh mode will be disabled,
+// and we won't be able to reproduce the problem.
+const visitFullAppEmbeddingUrl = ({ url }) => {
```
Comment (WiNloSt) [inline e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js:101]: Copy the function from https://github.com/metabase/metabase/blob/64c642d908842875cae715599116512ddfb78c36/e2e/test/scenarios/admin/databases/database-prompt-banner.cy.spec.js#L158-L169

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+          SCALAR_QUESTION_CARD,
+        );
+
+        visitFullAppEmbeddingUrl({ url: `/dashboard/${dashboard.id}` });
+
+        cy.wait("@getDashboard");
+        cy.wait("@getDashcardQuery");
+        // The timeout necessary to make sure the dashcard is rendered.
+        const DASHCARD_FIRST_RENDER_TIMEOUT = 400;
+        cy.tick(DASHCARD_FIRST_RENDER_TIMEOUT);
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js:65]: This `400` got me puzzled so I investigated a bit. It turns out it will work with `300`, but not `299`.

The value of this timeout must be greater or equal to [`WAIT_TIME` defined in `ExplicitSize`](https://github.com/metabase/metabase/blob/110b682/frontend/src/metabase/components/ExplicitSize.jsx#L11).

I suggest to import that `WAIT_TIME` here and reuse it, to clearly indicate the reason and intention.

**Review by kamilmielnik — COMMENTED** [review]
Fix works great :+1: 

However I noticed performance degradation during initial render (affects all visualizations).

I suggest stress-testing this to make sure it's acceptable: create a dashboard with 2 or more tabs, add multiple various visualizations in both tabs and then navigate between those tabs. The app "freezes" for a while it renders the visualizations - you can tell, because the cursor will still be `pointer` for a while after switching tab, see [video](https://github.com/metabase/metabase/assets/6830683/8aaec278-9270-4b4e-83d8-e34c5b35bd5d).

I also left some suggestions on how we can improve the tests.

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+        cy.findByTestId("scalar-value").then(([$scalarValue]) => {
+          // Before the fix the width would be around 50px
+          expect($scalarValue.offsetWidth).to.be.greaterThan(100);
```
[the remark this answers is not in the document]
Comment (WiNloSt) [reply e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js:68]: Didn't know there was such an assertion. I agree that'll be great. I didn't want to assert the correct size because I feel it could be flaky real easily with time. But `closeTo` could work.

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js (hunk 4 above)
Comment (WiNloSt) [reply e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js:65]: I don't fully understand this bit, to be honest. Since the new code uses `debounceLeading` the first render should not have to wait for the `WAIT_TIME` at all, I can understand if needs to wait for the `WAIT_TIME` if we use `debounce`.

Maybe I'll have to investigate and see why 300ms is still applied to `debounceLeading` mode.

**Comment by WiNloSt** [comment]
@kamilmielnik TBH I'm not entirely sure how to interpret performance between this PR and master here is the performance benchmark summary for each branch. These results are run with 4x CPU throttle. I don't feel they're any different.

#### This PR
- 1st run
image
- 2nd run
image

#### `master`
- 1st run
image
- 2nd run
image

**Comment by kamilmielnik** [comment]
> TBH I'm not entirely sure how to interpret performance between this PR and master here is the performance benchmark summary for each branch. These results are run with 4x CPU throttle. I don't feel they're any different.

Ok, great :+1: :tada:

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (uladzimirdev) [reply e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js:68]: I'm second on the exact size

**Comment by uladzimirdev** [comment]
@kamilmielnik I think performance overall is not great in resize, it bothers me a lot when I touch dashboard with cards 😄

**Review by uladzimirdev — APPROVED** [review]

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (WiNloSt) [reply e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js]: Fixed in fab35e5b5b01cf3410672e4adf829fe7dfed2de3, but I forgot to push the commit 🤦

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js (hunk 4 above)
Comment (WiNloSt) [reply e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js]: Fixed in 1765c3615028fb5cd2009a4e11b3cd21b397fa77.

Basically, it was exactly the `WAIT_TIME` that cause this delay. I've tested locally and both `debounce` and `debounceLeading` needs to wait exactly `WAIT_TIME` before it starts rendering in Cypress. I'm not sure why. But I've imported `WAIT_TIME` to use in the test to communicate it's `WAIT_TIME` that we're using in the test.

**Review by kamilmielnik — APPROVED** [review]
:+1:

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+        cy.wait("@getDashboard");
+        cy.wait("@getDashcardQuery");
+        cy.tick(WAIT_TIME);
+
+        const expectedWidth = 147;
+        cy.findByTestId("scalar-value").then(([$scalarValue]) => {
+          expect($scalarValue.offsetWidth).to.be.closeTo(
+            expectedWidth,
+            expectedWidth * 0.1,
+          );
```
Comment (WiNloSt) [inline e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js:71]: The previous version
https://github.com/metabase/metabase/blob/fab35e5b5b01cf3410672e4adf829fe7dfed2de3/e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js#L67
flakes on CI. Here's the [example failed run](https://www.deploysentinel.com/ci/runs/64bfb4a3857dcf477f8d637c).

So I increase the tolerance to 10%

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js [hunk 7]
```diff
@@ -0,0 +1,120 @@
+import { restore } from "e2e/support/helpers";
+
+import { SAMPLE_DATABASE } from "e2e/support/cypress_sample_database";
+
+// Couldn't import from `metabase/components/ExplicitSize` because dependency issue.
+// It will fail Cypress tests.
+const WAIT_TIME = 300;
```
Comment (WiNloSt) [inline e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js:7]: Can't import from `metabase/components/ExplicitSize` because it will also import other dependencies in that file and will cause [Cypress test to crash](https://github.com/metabase/metabase/actions/runs/5656362887/job/15323756506?pr=32534).

File: e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+          dashboard.id,
+          SCALAR_QUESTION_CARD,
+        );
+
+        visitFullAppEmbeddingUrl({ url: `/dashboard/${dashboard.id}` });
+
+        cy.wait("@getDashboard");
+        cy.wait("@getDashcardQuery");
+        // This extra 1ms is crucial, without this the test would fail.
+        cy.tick(WAIT_TIME + 1);
```
Comment (WiNloSt) [inline e2e/test/scenarios/dashboard/reproductions/29304-scalar-first-render-size-change.cy.spec.js:68]: Tested locally that waiting `300` will fail the test, I need to wait for `301` which is `WAIT_TIME` + 1https://github.com/metabase/metabase/blob/12870cf862e53de8b71d6df5147102877cffede2/frontend/src/metabase/components/ExplicitSize.jsx#L11
