### PR TITLE
Properly mention available subscription & alert channels for non-admins

### LINKED ISSUE #65526: Incomplete non-admin user warning when setting up subscriptions and alerts when no notification channel is set up
### Describe the bug

For Subscriptions (dashboards), we support:

1. Email
2. Slack

For Alerts (questions), we support:

1. Email
2. Slack
3. Webhook

We can see that on a new instance, admins will see these screens when no notification channel has been set up yet.

#### Subscriptions

Image

#### Alerts

Image

But when logged in with non-admin users, they'll see these warnings.

#### Subscriptions

It only mentions Email, not *Slack*

Image

#### Alerts

It only mentions Email, and Slack, but not *Webhook*

Image

### To Reproduce

1. Create a new instance
2. Add a non-admin user
3. Sign in as non-admin user
4. check an example dashboard, and try to subscribe
5. check any question in the Example collection, and try to set up and alert

Those warnings should match the number of notification channels we support.

### Expected behavior

Those warnings should match the number of notification channels we support.

### Logs

*No response*

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "run-mode": "dev",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2025-11-03",
      "src_hash": "62b8529a3fa0a137d47ce07fe9d3dea64be033ab",
      "tag": "v1.56.13-SNAPSHOT",
      "hash": "b959675"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.2+13-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.2+13-LTS",
    "os.name": "Mac OS X",
    "os.version": "15.6.1",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

low

### Additional context

The warning is inconsistent, and misleading to non-admin users.

### PR DESCRIPTION
**Pull request by gantoreno**
Closes #65526 → [UXW-2228](https://linear.app/metabase/issue/UXW-2228/incomplete-non-admin-user-warning-when-setting-up-subscriptions-and)

### Description

This PR fixes an inconsistency between admin & non-admin views when attempting to set up subscriptions & alerts on a dashboard. Before, non-admin views wouldn't mention Webhooks for subscriptions, and subscriptions wouldn't mention Slack. 

It also fixes an underlying bug where, if Slack was configured, the option for subscriptions still wouldn't be available as it was only checking for email configuration. Wording was also adjusted to always use lowercase 'admin' and 'email' instead of 'SMTP'.

### How to verify

From #65526:

> 1. Create a new instance
> 2. Add a non-admin user
> 3. Sign in as non-admin user
> 4. check an example dashboard, and try to subscribe
> 5. check any question in the Example collection, and try to set up and alert

Step 3 should mention email, Slack, and webhooks. Step 5 should mention email, and Slack.

### Demo

| Place | Before | After |
| --- | --- | --- |
| Subscriptions | CleanShot 2025-11-25 at 15 18 28@2x | CleanShot 2025-11-25 at 15 21 47@2x |
| Alerts | CleanShot 2025-11-25 at 15 20 35@2x | CleanShot 2025-11-25 at 15 21 13@2x |

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.tsx [hunk 1]
```diff
@@ -26,19 +27,24 @@ export function DashboardSubscriptionMenuItem({
...
         data-testid="dashboard-subscription-menu-item"
         leftSection={<Icon name="subscription" />}
         disabled
       >
         <Text size="md" c="inherit">{t`Can't send subscriptions`}</Text>
-        <Text size="sm" c="inherit">{t`Ask your admin to set up email`}</Text>
+        <Text
+          size="sm"
+          c="inherit"
+        >{t`Ask your admin to set up email, or Slack`}</Text>
```
Comment (iethree) [inline frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.tsx]:
```suggestion
        >{t`Ask your admin to set up email or Slack`}</Text>
```

**Review by iethree — CHANGES_REQUESTED** [review]
looks good! please add a test!

File: frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.tsx (hunk 1 above)
Comment (gantoreno) [reply frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.tsx]: The dialog from the admin POV also has a final comma - didn't like it too much either. Want me to drop that one as well?

image

Comment (iethree) [reply frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.tsx]: this is a hotly debated issue that doesn't matter at all. Personally, I'm in favor of the [oxford comma](https://en.wikipedia.org/wiki/Serial_comma). You can go either way with lists of 3 or more items, but never use a comma with 2 items.

Comment (gantoreno) [reply frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.tsx]: Nice tip, thanks!

Comment (gantoreno) [reply frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.tsx]: Addressed via https://github.com/metabase/metabase/pull/66273/commits/fb5af7b2a7c85acd3e4e3386544addde7dcde6fe 👍🏻

File: frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.unit.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+        />
+      </Menu.Dropdown>
+    </Menu>,
+    { storeInitialState },
+  );
+};
+
+describe("DashboardSubscriptionMenuItem", () => {
+  describe("when user can manage subscriptions and dashboard has data cards", () => {
+    it("should show 'Subscriptions' menu item when email and slack are not set up", async () => {
```
Comment (iethree) [inline frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.unit.spec.tsx]: nit: if a describe block only has one test in it, you probably don't need to keep the describe

File: frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.unit.spec.tsx [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+    });
+  });
+
+  describe("when user can't manage subscriptions and dashboard has data cards", () => {
+    it.each([
+      { hasEmailSetup: true, hasSlackSetup: false },
+      { hasEmailSetup: false, hasSlackSetup: true },
+      { hasEmailSetup: true, hasSlackSetup: true },
+    ])(
+      "should show 'Subscriptions' menu item when email is $hasEmailSetup and slack is $hasSlackSetup",
```
Comment (iethree) [inline frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.unit.spec.tsx:83]: TIL you could interpolate variables like that in jest  ❤️

**Review by iethree — APPROVED** [review]
Very nice 👏

**Comment by iethree** [comment]
I think this test: `scenarios > dashboard > subscriptions > with Slack set up > should disable subscriptions for non-admin users` may no longer be testing the correct behavior. we used to prevent non-admins from sending slack alerts, but that was changed. see 
- https://github.com/metabase/metabase/issues/17526
- https://github.com/metabase/metabase/issues/35955
- https://github.com/metabase/metabase/issues/46100

File: frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.unit.spec.tsx (hunk 2 above)
Comment (gantoreno) [reply frontend/src/metabase/notifications/NotificationsActionsMenu/DashboardSubscriptionMenuItem.unit.spec.tsx]: Extracted it via https://github.com/metabase/metabase/pull/66273/commits/cc58fea3cb662a54b6c6dfce5180618ef15a319d 👍🏻
