### PR TITLE
hide terminal-report logs from console

### LINKED ISSUE #46954: cleanup logs from cypress at CI
we have two kinds of mess that makes search of the failing test complicated:
- cypress testing library prints whole DOM into logs (we don't need it, it's not useful in any way)
- cypress terminal report pollutes logs with debug info, but it also makes search more complicated, so we'll keep such logs only in mocha reports

### PR DESCRIPTION
**Pull request by uladzimirdev**
closes https://github.com/metabase/metabase/issues/46954

### Description

This PR hides cypress-terminal-reports logs from github actions, as users said it's hard to find a failing test name because of the noise from terminal-report.

From now, cypress-terminal-report logs will be inside mocha report only

### How to verify

Currently we have a single explicitly failing test, check logs of dashboard-ee job and verify that there is no log from cypress-terminal-report

download mocha report from the artifacts section of the job, unzip and verify that mocha report contains logs from cypress-terminal-report (above the screenshot)

image

### Demo

check the [failing job](https://github.com/metabase/metabase/actions/runs/10410178544/job/28831691309?pr=46891), it's much cleaner than before, you can easily navigate to the error if needed

mocha report has logs from cypress-terminal-report 
image

### CODE REVIEW

File: e2e/support/cypress.js [hunk 1]
```diff
@@ -3,12 +3,29 @@ registerCypressGrep();
...
 const isCI = Cypress.env("CI");
 
+// remove default html output on test failure
+configure({
+  getElementError: (message, container) => {
+    // to re-enable the default stack trace, uncomment
+    // import { prettyDOM } from "@testing-library/dom";
+    // const error = new Error(
+    //  [message, prettyDOM(container)].filter(Boolean).join('\n\n'),
+    // )
```
Comment (iethree) [inline e2e/support/cypress.js:20]: ❤️

**Review by iethree — APPROVED** [review]
