### PR TITLE
Sync dynamic tables for snowflake

### LINKED ISSUE #35194: Metabase won't sync Snowflake materialized views (dynamic tables)
### Describe the bug

If you create a materialized view in Snowflake (their fancy name is dynamic tables), Metabase won't be able to use them

### To Reproduce

With a snowflake DB that has the sample db run
```
USE DATABASE "sample";
CREATE OR REPLACE DYNAMIC TABLE orders_people
                  TARGET_LAG = '5 minutes'
                  WAREHOUSE = 'COMPUTE_WH'
                  AS SELECT "ORDERS".*, "PEOPLE"."EMAIL" FROM "sample"."PUBLIC"."ORDERS" LEFT JOIN "sample"."PUBLIC"."PEOPLE" ON "ORDERS"."USER_ID" = "PEOPLE"."ID";
```
then force a sync

### Expected behavior

we should be able to get those materialized views

### Logs

```
metabase-snowflake         | 2023-10-29 16:04:36,082 WARN sync.util :: Error syncing Fields for Table 'Table 17 'PUBLIC.ORDERS_PEOPLE''
metabase-snowflake         | net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error: show [constraint] command doesnt support this domain.
metabase-snowflake         | 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:129)
metabase-snowflake         | 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:70)
metabase-snowflake         | 	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:456)
metabase-snowflake         | 	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:366)
metabase-snowflake         | 	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:464)
metabase-snowflake         | 	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:192)
metabase-snowflake         | 	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:129)
metabase-snowflake         | 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:742)
metabase-snowflake         | 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:652)
metabase-snowflake         | 	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:251)
metabase-snowflake         | 	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:136)
metabase-snowflake         | 	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.executeAndReturnEmptyResultIfNotFound(SnowflakeDatabaseMetaData.java:3439)
metabase-snowflake         | 	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.getPrimaryKeys(SnowflakeDatabaseMetaData.java:2071)
metabase-snowflake         | 	at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getPrimaryKeys(NewProxyDatabaseMetaData.java:3198)
metabase-snowflake         | 	at metabase.driver.snowflake$fn__132769$fn__132770.invoke(snowflake.clj:457)
metabase-snowflake         | 	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__85678.reduce(common.clj:38)
metabase-snowflake         | 	at clojure.core$reduce.invokeStatic(core.clj:6885)
metabase-snowflake         | 	at clojure.core$into.invokeStatic(core.clj:6958)
metabase-snowflake         | 	at clojure.core$into.invoke(core.clj:6950)
metabase-snowflake         | 	at metabase.driver.snowflake$fn__132769.invokeStatic(snowflake.clj:456)
metabase-snowflake         | 	at metabase.driver.snowflake$fn__132769.invoke(snowflake.clj:453)
metabase-snowflake         | 	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
metabase-snowflake         | 	at metabase.driver.sql_jdbc.sync.describe_table$add_table_pks.invokeStatic(describe_table.clj:212)
metabase-snowflake         | 	at metabase.driver.sql_jdbc.sync.describe_table$add_table_pks.invoke(describe_table.clj:209)
metabase-snowflake         | 	at metabase.driver.snowflake$fn__132762$fn__132763.invoke(snowflake.clj:437)
metabase-snowflake         | 	at metabase.driver.sql_jdbc.execute$fn__80836$fn__80837.invoke(execute.clj:384)
metabase-snowflake         | 	at metabase.driver.sql_jdbc.execute$fn__80804$do_with_resolved_connection__80805.invoke(execute.clj:334)
metabase-snowflake         | 	at clojure.lang.AFn.applyToHelper(AFn.java:165)
metabase-snowflake         | 	at clojure.lang.AFn.applyTo(AFn.java:144)
metabase-snowflake         | 	at clojure.core$apply.invokeStatic(core.clj:667)
metabase-snowflake         | 	at clojure.core$apply.invoke(core.clj:662)
metabase-snowflake         | 	at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
metabase-snowflake         | 	at clojure.lang.RestFn.invoke(RestFn.java:457)
metabase-snowflake         | 	at metabase.driver.sql_jdbc.execute$fn__80836.invokeStatic(execute.clj:378)
metabase-snowflake         | 	at metabase.driver.sql_jdbc.execute$fn__80836.invoke(execute.clj:376)
metabase-snowflake         | 	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
metabase-snowflake         | 	at metabase.driver.snowflake$fn__132762.invokeStatic(snowflake.clj:429)
metabase-snowflake         | 	at metabase.driver.snowflake$fn__132762.invoke(snowflake.clj:427)
metabase-snowflake         | 	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
metabase-snowflake         | 	at metabase.sync.fetch_metadata$fn__97989$table_metadata__97994$fn__97995.invoke(fetch_metadata.clj:20)
metabase-snowflake         | 	at metabase.sync.fetch_metadata$fn__97989$table_metadata__97994.invoke(fetch_metadata.clj:17)
metabase-snowflake         | 	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__98265$db_metadata__98270$fn__98271.invoke(fetch_metadata.clj:94)
metabase-snowflake         | 	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__98265$db_metadata__98270.invoke(fetch_metadata.clj:90)
metabase-snowflake         | 	at metabase.sync.sync_metadata.fields$fn__98799$sync_fields_for_table_BANG___98808$fn__98811$fn__98812.invoke(fields.clj:73)
metabase-snowflake         | 	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
metabase-snowflake         | 	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
metabase-snowflake         | 	at metabase.sync.sync_metadata.fields$fn__98799$sync_fields_for_table_BANG___98808$fn__98811.invoke(fields.clj:72)
metabase-snowflake         | 	at metabase.sync.sync_metadata.fields$fn__98799$sync_fields_for_table_BANG___98808.invoke(fields.clj:66)
metabase-snowflake         | 	at clojure.core$partial$fn__5908.invoke(core.clj:2641)
metabase-snowflake         | 	at clojure.core$map$fn__5935.invoke(core.clj:2770)
metabase-snowflake         | 	at clojure.lang.LazySeq.sval(LazySeq.java:42)
metabase-snowflake         | 	at clojure.lang.LazySeq.seq(LazySeq.java:51)
metabase-snowflake         | 	at clojure.lang.RT.seq(RT.java:535)
metabase-snowflake         | 	at clojure.core$seq__5467.invokeStatic(core.clj:139)
metabase-snowflake         | 	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
metabase-snowflake         | 	at clojure.lang.LazySeq.sval(LazySeq.java:42)
metabase-snowflake         | 	at clojure.lang.LazySeq.seq(LazySeq.java:51)
metabase-snowflake         | 	at clojure.lang.Cons.next(Cons.java:39)
metabase-snowflake         | 	at clojure.lang.RT.boundedLength(RT.java:1790)
metabase-snowflake         | 	at clojure.lang.RestFn.applyTo(RestFn.java:130)
metabase-snowflake         | 	at clojure.core$apply.invokeStatic(core.clj:669)
metabase-snowflake         | 	at clojure.core$apply.invoke(core.clj:662)
metabase-snowflake         | 	at metabase.sync.sync_metadata.fields$fn__98838$sync_fields_BANG___98843$fn__98844.invoke(fields.clj:86)
metabase-snowflake         | 	at metabase.sync.sync_metadata.fields$fn__98838$sync_fields_BANG___98843.invoke(fields.clj:78)
metabase-snowflake         | 	at clojure.lang.AFn.applyToHelper(AFn.java:154)
metabase-snowflake         | 	at clojure.lang.AFn.applyTo(AFn.java:144)
metabase-snowflake         | 	at clojure.core$apply.invokeStatic(core.clj:669)
metabase-snowflake         | 	at clojure.core$apply.invoke(core.clj:662)
metabase-snowflake         | 	at metabase.sync.util$fn__62954$run_step_with_metadata__62959$fn__62963$fn__62965.doInvoke(util.clj:380)
metabase-snowflake         | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
metabase-snowflake         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
metabase-snowflake         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
metabase-snowflake         | 	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)
metabase-snowflake         | 	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)
metabase-snowflake         | 	at metabase.sync.util$fn__62954$run_step_with_metadata__62959$fn__62963.invoke(util.clj:375)
metabase-snowflake         | 	at metabase.sync.util$fn__62954$run_step_with_metadata__62959.invoke(util.clj:370)
metabase-snowflake         | 	at metabase.sync.util$fn__63181$run_sync_operation__63186$fn__63187$fn__63195.invoke(util.clj:486)
metabase-snowflake         | 	at metabase.sync.util$fn__63181$run_sync_operation__63186$fn__63187.invoke(util.clj:484)
metabase-snowflake         | 	at metabase.sync.util$fn__63181$run_sync_operation__63186.invoke(util.clj:478)
metabase-snowflake         | 	at metabase.sync.sync_metadata$fn__100383$sync_db_metadata_BANG___100388$fn__100389$fn__100390.invoke(sync_metadata.clj:60)
metabase-snowflake         | 	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
metabase-snowflake         | 	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
metabase-snowflake         | 	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
metabase-snowflake         | 	at metabase.driver$fn__48142.invokeStatic(driver.clj:693)
metabase-snowflake         | 	at metabase.driver$fn__48142.invoke(driver.clj:693)
metabase-snowflake         | 	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
metabase-snowflake         | 	at metabase.sync.util$sync_in_context$fn__62874.invoke(util.clj:140)
metabase-snowflake         | 	at metabase.sync.util$with_db_logging_disabled$fn__62871.invoke(util.clj:131)
metabase-snowflake         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
metabase-snowflake         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
metabase-snowflake         | 	at metabase.sync.util$with_start_and_finish_logging$fn__62858.invoke(util.clj:116)
metabase-snowflake         | 	at metabase.sync.util$with_sync_events$fn__62853.invoke(util.clj:90)
metabase-snowflake         | 	at metabase.sync.util$with_duplicate_ops_prevented$fn__62843.invoke(util.clj:69)
metabase-snowflake         | 	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:183)
metabase-snowflake         | 	at metabase.sync.util$do_sync_operation.invoke(util.clj:180)
metabase-snowflake         | 	at metabase.sync.sync_metadata$fn__100383$sync_db_metadata_BANG___100388$fn__100389.invoke(sync_metadata.clj:59)
metabase-snowflake         | 	at metabase.sync.sync_metadata$fn__100383$sync_db_metadata_BANG___100388.invoke(sync_metadata.clj:55)
metabase-snowflake         | 	at metabase.api.database$fn__109288$fn__109289.invoke(database.clj:983)
metabase-snowflake         | 	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
metabase-snowflake         | 	at clojure.lang.AFn.call(AFn.java:18)
metabase-snowflake         | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
metabase-snowflake         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
metabase-snowflake         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
metabase-snowflake         | 	at java.base/java.lang.Thread.run(Unknown Source)
metabase-snowflake         | 2023-10-29 16:04:36,094 INFO sync.util :: FINISHED: step 'sync-fields' for snowflake Database 2 'Snowflake' (10.7 s)

```

### Information about your Metabase installation

```JSON
latest
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Closes #35194

This bug has 2 problems:

1. 
Currently, if you have a snowflake database containing dynamic tables, sync will fail for those dynamic tables with an exception.

```net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error: show [constraint] command doesn't support this domain.```

This is because we're trying to find pks and fks for those dynamic tables, but the snowflake jdbc is throwing an error because apparently, they're not supported for dynamic tables.

2. 
We used the [getColumns method
](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-) to get a list of columns for each table, but currently there is a bug in snowflake jdbc where it returns an empty list for dynamic tables. I've filed  [bug](https://github.com/snowflakedb/snowflake-jdbc/issues/1574) on their repo, for now we'll rely on the fallback method that call a select query then use it to figure out column details

### CODE REVIEW

File: src/metabase/driver/sql_jdbc/sync/interface.clj [hunk 1]
```diff
@@ -72,9 +72,9 @@
   overriden because SQLite is silly and only returns column information for views if the query returns a non-zero
   number of rows.
 
-    (fallback-metadata-query :postgres \"public\" \"my_table\")
-    ;; -> [\"SELECT * FROM public.my_table WHERE 1 <> 1 LIMIT 0\"]"
-  {:added "0.37.1" :arglists '([driver schema table])}
+    (fallback-metadata-query :postgres \"my_database\" \"public\" \"my_table\")
+    ;; -> [\"SELECT * FROM my_database.public.my_table WHERE 1 <> 1 LIMIT 0\"]"
+  {:added "0.37.1" :arglists '([driver db schema table])}
```
Comment (calherries) [inline src/metabase/driver/sql_jdbc/sync/interface.clj:77]: This is a breaking change to a multimethod that could be used by external drivers. I think those driver authors would appreciate if you extended this multimethod to have two arities instead, one with the db and one without.

File: modules/drivers/sqlite/src/metabase/driver/sqlite.clj [hunk 2]
```diff
@@ -109,9 +109,9 @@
 ;; The normal SELECT * FROM table WHERE 1 <> 1 LIMIT 0 query doesn't return any information for SQLite views -- it
 ;; seems to be the case that the query has to return at least one row
 (defmethod sql-jdbc.sync/fallback-metadata-query :sqlite
-  [driver schema table]
+  [driver db schema table]
   (sql.qp/format-honeysql driver {:select [:*]
-                                  :from   [[(h2x/identifier :table schema table)]]
+                                  :from   [[(h2x/identifier :table db schema table)]]
```
Comment (calherries) [inline modules/drivers/sqlite/src/metabase/driver/sqlite.clj:114]: This doesn't make logical sense to allow sqlite to have an identifier like `x.y.z`. See this comment for a solution: offer a 3-arity implementation instead https://github.com/metabase/metabase/pull/36121/files#r1410580202

File: src/metabase/driver/sql_jdbc/sync/interface.clj (hunk 1 above)
Comment (calherries) [reply src/metabase/driver/sql_jdbc/sync/interface.clj:77]: Thinking about this a bit more, this is a little dangerous because while driver authors aren't forced to implement all arities, it could be easy to make a mistake by calling the wrong arity.

Maybe a better solution is to convert this multimethod into a variadic function instead. So you'd have `[driver & table-components]` instead.

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 3]
```diff
@@ -459,11 +450,18 @@
...
+    (try
+     (into [] (sql-jdbc.sync.common/reducible-results
+               #(.getPrimaryKeys metadata db-name-or-nil
+                                 (-> table :schema escape-name-for-metadata)
+                                 (-> table :name escape-name-for-metadata))
+               (fn [^ResultSet rs] #(.getString rs "COLUMN_NAME"))))
+     (catch SnowflakeSQLException e
+       ;; dynamic tables doesn't support pks and it'll throw an error if you try to get one
+       (if (= "SQL compilation error: show [constraint] command doesnt support this domain."
+              (ex-message e))
```
Comment (calherries) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:462]: Relying on error strings staying the same is a brittle assumption. Ideally, we'd know that this table is a dynamic table from the metadata. It seems like you can get the type name from the metadata, based on [the javadocs](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#:~:text=getSearchStringEscape()-,getTables,-ResultSet%C2%A0getTables()) of `.getTables`

**Review by calherries — CHANGES_REQUESTED** [review]
Approach looks solid, but I'd like to avoid relying on error strings if we can

File: src/metabase/driver/sql_jdbc/sync/interface.clj (hunk 1 above)
Comment (qnkhuat) [reply src/metabase/driver/sql_jdbc/sync/interface.clj:77]: the [single call site](https://github.com/metabase/metabase/blob/e620d24b96b645e011471fdb0232c1fb9fcdd888/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L85) of this multimethod will always call it with 4 arguments, so I think any drivers that implement this multimethod will need to update it to 4-arity anw.

Comment (calherries) [reply src/metabase/driver/sql_jdbc/sync/interface.clj:77]: You _could_ modify that call site to use `apply` to apply only non-nil table components but I don't love that either, it feels like an abuse of variadic args. Make the breaking change then

Comment (calherries) [reply src/metabase/driver/sql_jdbc/sync/interface.clj:77]: But you should change this multimethod to explain that `db` and `table` are strings. Calling them `db-name` and `table-name` should suffice

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj [hunk 4]
```diff
@@ -67,31 +67,33 @@
...
     (reify clojure.lang.IReduceInit
       (reduce [_ rf init]
         (with-open [stmt (sql-jdbc.sync.common/prepare-statement driver conn sql params)
                     rs   (.executeQuery stmt)]
           (let [metadata (.getMetaData rs)]
             (reduce
              ((map (fn [^Integer i]
-                     {:name          (.getColumnName metadata i)
-                      :database-type (.getColumnTypeName metadata i)})) rf)
+                     ;; TODO: missing :database-required column
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:93]: the [ResultSetMetadata](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/sql/ResultSetMetaData.html) doesn't know contains information about whether a column has a default value so we can't really know whether it's required or not

[the remark this answers is not in the document]
Comment (calherries) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:93]: Got it. Would it make sense to add that to the TODO comment?

**Review by calherries — APPROVED** [review]
Looks good, just need to update driver docs

File: modules/drivers/sqlite/src/metabase/driver/sqlite.clj [hunk 5]
```diff
@@ -109,9 +109,9 @@
 ;; The normal SELECT * FROM table WHERE 1 <> 1 LIMIT 0 query doesn't return any information for SQLite views -- it
 ;; seems to be the case that the query has to return at least one row
 (defmethod sql-jdbc.sync/fallback-metadata-query :sqlite
-  [driver schema table]
+  [driver _db-name-or-nil schema-name table-name]
   (sql.qp/format-honeysql driver {:select [:*]
-                                  :from   [[(h2x/identifier :table schema table)]]
+                                  :from   [[(h2x/identifier :table schema-name table-name)]]
```
Comment (calherries) [inline modules/drivers/sqlite/src/metabase/driver/sqlite.clj:114]: We can remove `schema-name` here too. SQLite doesn't have schema
