### PR TITLE
fix series names overflow available space in viz settings

### LINKED ISSUE #52975: Long column names overflow in data viz settings on cartesian charts
[Slack thread](https://metaboat.slack.com/archives/C01LQQ2UW03/p1738228937437259)

**Context**

Column names should not overflow:
Image

Possibly related to https://github.com/metabase/metabase/pull/52290

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/52975

### Description

Fixes incorrect layout of series viz settings items in cartesian charts.

The `release-x.53.x` branch has been fixed separately in https://github.com/metabase/metabase/pull/54099

### How to verify

Query:
```
select 'foo' x, 10 "very very very long column", 20 "very very very very very very very very very very very long column 2", 20 "very very very very very very very very very very very long column 3"
```

- Create a native question
- Make it a bar chart
- Ensure series items in viz settings have correct layouts

### Demo

Before
Screenshot 2025-02-20 at 9 28 37 PM

After
Screenshot 2025-02-20 at 9 28 13 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/settings/ChartSettingSelect.jsx [hunk 1]
```diff
@@ -64,7 +64,6 @@ export const ChartSettingSelect = ({
       placeholder={options.length === 0 ? placeholderNoOptions : placeholder}
       initiallyOpened={isInitiallyOpen}
       searchable={!!searchProp}
-      rightSectionWidth={rightSectionWidth ?? "10px"}
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingSelect.jsx:67]: This prop was completely ignored

**Review by lorem--ipsum — APPROVED** [review]
