### PR TITLE
Use saved card metadata to filter fields in query metadata for sandboxed tables

### LINKED ISSUE #48707: Column sandboxing powered by a SQL question still shows all columns in query builder, leading to errors
### Describe the bug

As an admin, you can set up a sandbox powered by a SQL question which selects a subset of columns from a table, in order to restrict the columns which a user should have access to.

However, the user still is able to see the full list of columns in the query builder, and thus might try to create a query which will subsequently error due to the sandbox. 

### To Reproduce

1. As an admin, create a SQL question as a base for sandboxing like:
```sql
select ID, USER_ID, TAX, TOTAL from ORDERS where USER_ID = 1;
```
2. Sandbox Orders table for "All users" using this SQL question
3. Log in as a non-admin, and start a new question using the query builder
4. You'll be able to see the full list of fields in the table in the query builder, and if you try to create a question that includes all fields, you will get an error

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

n/a (already fixed)

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
When fetching the `query_metadata` for a table which is sandboxed using a source card, the sandboxing card might only include a subset of the columns in the table. So we need to filter out fields from the table's metadata which are not present in the sandboxing card.

Previously, this was done by looking for field references in the sandboxing query itself. This worked for MBQL queries but never worked for native queries. 

I've changed this to instead look at the sandboxing card's `result_metadata`. If it's an MBQL card, we filter out fields from the table's metadata by ID. If it's a native card, we correlate them by name, since we don't have an ID mapping.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#48577** <a href="https://app.graphite.dev/github/pr/metabase/metabase/48577?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: enterprise/backend/src/metabase_enterprise/sandbox/api/table.clj [hunk 1]
```diff
@@ -33,52 +31,61 @@
...
+        thunk (fn [] (api.table/fetch-query-metadata* table opts))]
+    (if (only-sandboxed-perms? table)
+      (filter-fields-for-sandboxing
        table
+         ;; if the user has sandboxed perms, temporarily upgrade their perms to read perms for the Table so they can
+         ;; fetch the metadata
        (data-perms/with-additional-table-permission :perms/view-data (:db_id table) (u/the-id table) :unrestricted
          (data-perms/with-additional-table-permission :perms/create-queries (:db_id table) (u/the-id table) :query-builder
            (thunk))))
+      ;; Not sandboxed
```
Comment (escherize) [inline enterprise/backend/src/metabase_enterprise/sandbox/api/table.clj:71]:
```suggestion
      ;; Not only sandboxed, so they can fetch metadata
```

**Review by escherize — APPROVED** [review]
LGTM 🚀
