### PR TITLE
fix(EmbedJS): Downloads fail on guest embedded questions

### LINKED ISSUE #69949: Downloads Fail on Guest Embedded Questions
### Describe the bug

Guest embedded Questions cannot be downloaded (dashboard downloads work fine).

### To Reproduce

1. Enabled guest embedding
2. Set up guest embedding on a questions (downloads work fine on dashboards)
3. You can see the download failure from the Guest Embed preview

Probably related to the iFrame counter set in the frame source.

### Expected behavior

Downloads should work for guest embedded questions.

### Logs

[8805abef-630e-415b-836d-dade656ceb0e] 2026-02-19T18:21:45-05:00 DEBUG metabase.server.middleware.log GET /api/embed/card/eyJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6eyJxdWVzdGlvbiI6MTM2fSwicGFyYW1zIjp7fSwiaWF0IjoxNzcxNTQzMjc5LCJleHAiOjE3NzE1NDY4NzksIl9lbWJlZGRpbmdfcGFyYW1zIjp7fX0.OeA7Q4isp8F9Hyt8y5YxaqkgXjXOykxPt-AbQeaK37g/query/csv 400 20ms (2 DB calls) {:metabase-user-id 1} 
"Unknown parameter :v."

### Information about your Metabase installation

```JSON
v58.7
```

### Severity

blocking downloads for guest embedded questions

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
Fixes https://github.com/metabase/metabase/issues/69949

The issue was that I added `?v` query param to EmbedJS iframe to allow its parallel loading, but in the case of downloading we take window.location.search and pass is params to the API endpoint in addition with some other query params.

This causes the error.

The fix:
- i changed the name of the parameter to the more internal name
- i filter out this name when embedjs iframe is loaded

How to verify:
- open any embedJS wizard in guest mode for a question, select `with downloads` and try to download a question as CSV

### CODE REVIEW

File: e2e/support/helpers/e2e-downloads-helpers.ts [hunk 1]
```diff
@@ -167,8 +169,12 @@ export function downloadAndAssert({
     cy.findByTestId("download-results-button").click();
   });
 
-  cy.wait("@fileDownload").then(() => {
-    ensureDownloadStatusDismissed();
+  cy.wait("@fileDownload").then(({ response }) => {
+    expect(response?.statusCode).to.eq(200);
+
+    if (waitForDismiss) {
+      ensureDownloadStatusDismissed();
```
Comment (sanex3339) [inline e2e/support/helpers/e2e-downloads-helpers.ts:180]: This part is not needed for EmbedJS as we don't show this element

File: e2e/test/scenarios/embedding/sdk-iframe-embedding/guest-embed.cy.spec.ts [hunk 2]
```diff
@@ -60,6 +60,42 @@ describe(
...
+        frame.within(() => {
+          H.downloadAndAssert({
+            isDashboard: false,
+            isEmbed: true,
+            enableFormatting: true,
+            waitForDismiss: false,
+            fileType: "csv",
+            downloadUrl: "/api/embed/card/*/query/csv*",
+            downloadMethod: "GET",
+          });
```
Comment (sanex3339) [inline e2e/test/scenarios/embedding/sdk-iframe-embedding/guest-embed.cy.spec.ts:95]: This fails without the fix

File: frontend/src/metabase/embedding/embedding-iframe-sdk/components/SdkIframeEmbedRoute.tsx [hunk 3]
```diff
@@ -58,6 +59,10 @@ export const SdkIframeEmbedRoute = () => {
     [embedSettings?.theme],
   );
 
+  useEffect(() => {
+    stripInternalIframeQueryParameters();
```
Comment (sanex3339) [inline frontend/src/metabase/embedding/embedding-iframe-sdk/components/SdkIframeEmbedRoute.tsx:63]: I thought on what level we should fix it.
I thought on fixing it on the level of the DownloadWidget where we access `window.locations.search` but i had worries that it will fix that place but we may have cases when other API endpoints behave the same or if we may get similar issue in the future.

So i did it here

**Review by npretto — APPROVED** [review]

File: frontend/src/metabase/embedding/embedding-iframe-sdk/components/SdkIframeEmbedRoute.tsx (hunk 3 above)
Comment (sanex3339) [reply frontend/src/metabase/embedding/embedding-iframe-sdk/components/SdkIframeEmbedRoute.tsx:63]: We're discussing, we may adjust the place and approach later, we have to discuss the best option, but for the fix i think it's enough
