### PR TITLE
Site url validation fixes #14491

### LINKED ISSUE #14491: Site URL validation too strict, doesn't accept underscore
**Describe the bug**
We have an internal domain for Metabase, it looks like this: http://xxx-xxx-com_metabase.c01ilx.internal:3000

This URL is not accepted as site URL because of the _ (underscore). As far as I can see this is a valid host character according to https://www.ietf.org/rfc/rfc3986.html#page-13

**Logs**
```
2021-01-22 14:06:28,943 INFO middleware.misc :: Setting Metabase site URL to http://xxx-xxx-com_metabase.c01ilx.internal:3000
2021-01-22 14:06:28,944 WARN middleware.misc :: Failed to set site-url
clojure.lang.ExceptionInfo: Invalid site URL: "http://xxx-xxx-com_metabase.c01ilx.internal:3000"
	at metabase.public_settings$normalize_site_url.invokeStatic(public_settings.clj:80) ~[metabase.jar:?]
	at metabase.public_settings$normalize_site_url.invoke(public_settings.clj:71) ~[metabase.jar:?]
	at metabase.public_settings$fn__24050$fn__24051.invoke(public_settings.clj:96) ~[metabase.jar:?]
	at metabase.models.setting$set_BANG_.invokeStatic(setting.clj:428) ~[metabase.jar:?]
	at metabase.models.setting$set_BANG_.invoke(setting.clj:413) ~[metabase.jar:?]
	at metabase.models.setting$setting_fn$fn__22271.invoke(setting.clj:500) ~[metabase.jar:?]
	at metabase.middleware.misc$maybe_set_site_url_STAR_.invokeStatic(misc.clj:50) ~[metabase.jar:?]
	at metabase.middleware.misc$maybe_set_site_url_STAR_.invoke(misc.clj:43) ~[metabase.jar:?]
	at metabase.middleware.misc$maybe_set_site_url$fn__34513.invoke(misc.clj:58) ~[metabase.jar:?]
	at metabase.middleware.session$bind_current_user$fn__69513$fn__69514.invoke(session.clj:278) ~[metabase.jar:?]
	at metabase.middleware.session$do_with_current_user.invokeStatic(session.clj:260) ~[metabase.jar:?]
	at metabase.middleware.session$do_with_current_user.invoke(session.clj:252) ~[metabase.jar:?]
	at metabase.middleware.session$bind_current_user$fn__69513.invoke(session.clj:277) ~[metabase.jar:?]
	at metabase.middleware.session$wrap_current_user_info$fn__69500.invoke(session.clj:238) ~[metabase.jar:?]
	at metabase.middleware.session$wrap_session_id$fn__69486.invoke(session.clj:184) ~[metabase.jar:?]
	at metabase.middleware.auth$wrap_api_key$fn__72942.invoke(auth.clj:27) ~[metabase.jar:?]
	at ring.middleware.cookies$wrap_cookies$fn__75018.invoke(cookies.clj:216) ~[metabase.jar:?]
	at metabase.middleware.misc$add_content_type$fn__34498.invoke(misc.clj:28) ~[metabase.jar:?]
	at metabase.middleware.misc$disable_streaming_buffering$fn__34521.invoke(misc.clj:76) ~[metabase.jar:?]
	at ring.middleware.gzip$wrap_gzip$fn__75060.invoke(gzip.clj:86) ~[metabase.jar:?]
	at metabase.middleware.misc$bind_request$fn__34524.invoke(misc.clj:93) ~[metabase.jar:?]
	at metabase.middleware.ssl$redirect_to_https_middleware$fn__74849.invoke(ssl.clj:36) ~[metabase.jar:?]
	at metabase.server$async_proxy_handler$fn__74610.invoke(server.clj:72) ~[metabase.jar:?]
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) ~[metabase.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[metabase.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[metabase.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[metabase.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) ~[metabase.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) ~[metabase.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) ~[metabase.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[metabase.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[metabase.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[metabase.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[metabase.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[metabase.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[metabase.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135) ~[metabase.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [metabase.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [metabase.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2021-01-22 14:06:28,968 DEBUG middleware.log :: PUT /api/setting/site-url 204 21.5 ms (8 DB calls) App DB connections: 0/4 Jetty threads: 5/50 (2 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)
```

**To Reproduce**
1. Go to Metabase Admin
2. Open Settings -> General
3. Click to edit "Site URL" input
4. Enter "xxx-xxx-com_metabase.c01ilx.internal:3000"

**Expected behavior**
All URLs valid according to the RFC should be accepted.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "de-DE",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.15.0-74-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-01-20",
      "tag": "v0.37.7",
      "branch": "release-x.37.x",
      "hash": "2b034aa"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
We can't use Metabase in our current environment like this. We are trying to work around it using a CNAME DNS entry without an underscore.

### PR DESCRIPTION
**Pull request by adam-james-v**
The url? predicate function in our utils namespace uses UrlValidator from Apache commons with a custom regex. This was done, I think, to allow URLs with internal TLDs. (eg. "https://metabase.intranet").

Now, a url like this: "https://under_score.ca" is accepted.

Relevant RFC for domain names:
[RFC2181 Section 11](https://www.rfc-editor.org/rfc/rfc2181#section-11)

Relevant RFC for hostnames:
[RFC1123 Section 2.1](https://www.ietf.org/rfc/rfc1123.html#section-2.1)

It seems that our url? regex is for hostnames, and is based on the UrlValidator code . 

Though the issue #14491 author brings up the RFC1034 (which links to RFC1123 with a bit of a spec) to indicate that underscores SHOULD be allowed, they aren't really in that case. But it seems that there's wiggle room in allowing it for domains generally, and perhaps we should permit the use of underscores in this URL validation to allow for more configuration options for our users.

A stackoverflow page with helpful context and explanantion which helped me think about this:
[can-domain-name-subdomains-have-an-underscore-in-it](https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it)

### CODE REVIEW

File: test/metabase/util_test.clj [hunk 1]
```diff
@@ -53,6 +53,13 @@
     "http://localhost:3000/auth/reset_password/144_f98987de-53ca-4335-81da-31bb0de8ea2b#new" true
     "http://192.168.1.10/"                                                                   true
     "http://metabase.intranet/"                                                              true
+    "http://under_score.ca/"                                                                 true
+    "http://under__score.ca/"                                                                true
+    "http://_under_score.ca/"                                                                true
+    "http://__under_score.ca/"                                                               true
+    "http://hy-phen.ca/"                                                                     true
+    "http://hy--phen.ca/"                                                                     true
```
Comment (howonlee) [inline test/metabase/util_test.clj:61]: nit: space

**Review by howonlee — APPROVED** [review]
LGTM tested on my machine, test runs, does what it says on the tin

fun little fact about the terribleness of urls: navigate to _네이버.com_ - this unicode stuff seems like it's forbidden by the spec itself but it involves a funky little indirection for IDNA so the real url is some line noise and if you copy-paste the url in chrome's address bar it'll get rid of the indirection opaquely for you. led to a weird gold rush for a little while

File: src/metabase/util.clj [hunk 2]
```diff
@@ -137,7 +137,7 @@
   "Is `s` a valid HTTP/HTTPS URL string?"
   ^Boolean [s]
   (let [validator (UrlValidator. (varargs String ["http" "https"])
-                                 (RegexValidator. "^\\p{Alnum}+([\\.|\\-]\\p{Alnum}+)*(:\\d*)?")
+                                 (RegexValidator. "^[\\p{Alnum}\\_]+([\\.|\\-][\\p{Alnum}\\_]+)*(:\\d*)?")
```
Comment (dpsutton) [inline src/metabase/util.clj:140]: looks great to me. I am wondering what that last `+` operator does since there's a * after it. Do you know which tests fail if that is removed? I don't see the purpose of it

Comment (dpsutton) [reply src/metabase/util.clj:140]: Ran them locally and got lots of failures. It seems to be doing quite a bit of work in there so carry on.

**Comment by rlotun** [comment]
Two things:
1. Make sure you link the issue this fixes. You can do that either by putting something in your PR description like "Fixes: #14491" which GitHub will automatically parse, or explicitly linking the issue in the "linked issues" field in the PR on the right (sometimes, due some GitHub wackiness, you won't be able to find the issue in the search picker so you can try going to the issue and linking the PR form the issue)
2. We strive to have bug fixes backported to the latest live release (in this case that's x.41.3.1). These maintenance releases are released off the latest release branch (in this case that's `release-x.41.x`). We have automated machinery to backport bug fixes in master to the latest release branch which you can enable by adding the `backport` label to the PR. The only reason to not backport a fix to the latest release branch is if we think the code change is a little risky - I don't think the code in this PR is risky unless someone thinks otherwise.

Thanks!
