### PR TITLE
Handle missing `dataset_query` when trying to map parameter targets to fields

### LINKED ISSUE #20656: Dashboards breaks when there's filters to cards that a user don't have permissions to view
**Describe the bug**
Dashboards breaks when there's filters to cards that a user don't have permissions to view.
Kinda a repeat of #13005, but this requires that there's a filter connected to the card. Guessing it's a frontend issue.
Regression since 0.42.0

**To Reproduce**
1. As user1: Question > Sample > Products - save as "Q1" to user1's Personal Collection (could be any collection that user2 doesn't have permissions to).
2. Add the question to a shared dashboard and connect a filter.
image
3. Login as user2 and try to view the dashboard - Firefox shows `e is undefined`, and Chrome `Cannot read properties of undefined (reading 'type')`, which is equally unhelpful.
image

```
TypeError: Cannot read properties of undefined (reading 'type')
    at Function.value (app-main.bundle.js:2:528159)
    at e.value (app-main.bundle.js:2:532770)
    at app-main.bundle.js:2:653173
    at u (app-main.bundle.js:2:652879)
    at e.n.value (app-main.bundle.js:2:653146)
    at c (app-main.bundle.js:2:4263016)
    at map.r.ZP.findWhere.id (app-main.bundle.js:2:4249644)
    at app-main.bundle.js:2:4249659
    at Array.map (<anonymous>)
    at b (app-main.bundle.js:2:4249552)
```

**Expected behavior**
Like 0.41.6, be able to see/user the entire dashboard, and any cards with no permissions should just show a nice human error
image

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.42.1

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes #20656

When a user visits a dashboard that contains a card they do not have the proper permissions to view, the card data structure the FE is given is essentially `{ id }` and nothing else. The new parameters code added in 42 instantiates a `Question` with this `card` and calls `question.query()` when instantiating a `Dimension` instance, but `Question.prototype.query` does not handle scenarios where `dataset_query` is undefined.

I'm adding an additional predicate to check for a missing `card.dataset_query` in a dashboard parameters util function. Long term it probably makes more sense to avoid having parameters code inspect the internals of a `card`, but I want to avoid making a hasty decision regarding how to handle a question with a missing `card.dataset_query` -- alternatives to this likely need a bit more thinking. If `Question.prototype.query` is changed to return `null` or something, it'd force a cascade of changes as the function is currently guaranteed to return some sort of Query. Another possible alternative is that we default to something like `OpaqueQuery` if `dataset_query` is undefined.

**Testing**
Follow the steps in #20656 

**Before**

https://user-images.githubusercontent.com/13057258/155383111-3e967912-f911-47e7-a660-1426d5a73a8a.mov

**After**

https://user-images.githubusercontent.com/13057258/155383161-e7e4bc91-872b-408e-9f2e-41b48d4734af.mov

### CODE REVIEW

**Review by flamber — APPROVED** [review]

File: frontend/src/metabase/parameters/utils/dashboards.js [hunk 1]
```diff
@@ -63,8 +63,8 @@ export function isDashboardParameterWithoutMapping(parameter, dashboard) {
   return parameterExistsOnDashboard && !parameterHasMapping;
 }
 
-function getMappingTargetField(card, mapping, metadata) {
-  if (!card) {
+export function getMappingTargetField(card, mapping, metadata) {
+  if (!card || !card.dataset_query) {
```
Comment (alxnddr) [inline frontend/src/metabase/parameters/utils/dashboards.js:67]: nit: could be `if (!card?.dataset_query)`

**Review by alxnddr — APPROVED** [review]

File: frontend/src/metabase/parameters/utils/dashboards.js (hunk 1 above)
Comment (daltojohnso) [reply frontend/src/metabase/parameters/utils/dashboards.js]: yep, updated in https://github.com/metabase/metabase/pull/20678/commits/ca8ef992d01559d963496684db80c2d122dbc323
