### PR TITLE
Set network timeout in connection options

### LINKED ISSUE #66656: "Queries in flight" are slowly being leaked until metabase feels very slow
### Describe the bug

After about a week of uptime we end up with there permanently being 40+ (of the 50 limit) Queries in flight (even after waiting several days) despite there being long periods of no query traffic overnight. This causes metabase to seem very slow as it can only process a few actual requests at a time. Is there any way to see which queries it thinks are still running or to expire them?  Scouring the logs for when "Queries in flight: 0" went permanently to non-zero it's not obvious which ones are running forever.  

I believe this has been happening for us since metabase 56.  We're considering a cron job to restart metabase regularly, since a restart does indeed fix the problem for another week, but would prefer to fix the root cause

### To Reproduce

Leave our metabase running.  It seems to leak a few "Queries in flight" per day

### Expected behavior

"Queries in flight" should return to zero when metabase is under no load

### Logs

happy to email our full logs for many days if you think they'd be helpful

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "netsuite",
      "bigquery-cloud-sdk",
      "athena"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-11-05",
      "tag": "v0.56.13",
      "hash": "2455296"
    },
    "settings": {
      "report-timezone": "UTC"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "6.1.156-177.286.amzn2023.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

blocking until we restart

### Additional context

i don't think it's related to OOM's but was originally reported here https://github.com/metabase/metabase/issues/65668

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/66656

### Description

Sets a network timeout on jdbc connections. 

Databricks doesn't implement this method: https://github.com/databricks/databricks-jdbc/issues/1140

### How to verify

See my repro steps in linked issue and in loom below

### Demo

https://www.loom.com/share/064eb46635734892b9a2668fafd194cb

<details>

<summary> no audio </summary

https://www.loom.com/share/624b3ce27393403b8c9dd9673847fe38

</details>

Note by the timestamps that the time between initiating the query and it being cancelled is 23 seconds, which is what the network timeout was set to. 

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/driver/sql_jdbc/execute.clj [hunk 1]
```diff
@@ -405,6 +406,7 @@
             (.setAutoCommit conn false)
             (catch Throwable e
               (log/debug e "Error setting connection autoCommit to false"))))
+    (.setNetworkTimeout conn (Executors/newSingleThreadExecutor) driver.settings/*query-timeout-ms*)
```
Comment (rileythomp) [inline src/metabase/driver/sql_jdbc/execute.clj]: Should we use a different value for the timeout? Maybe a new env var?

File: test/metabase/driver/postgres_test.clj [hunk 2]
```diff
@@ -2105,3 +2106,33 @@
               (is (= [[1 "1" "10101010" "1101" "111000111"]
                       [2 "0" "00001111" "10101" "1001001"]]
                      (mt/rows (qp/process-query query)))))))))))
+
+(defn- caused-by?
+  "Return true if `ex` or any of its causes is an instance of `clazz`."
+  [clazz ex]
+  (some #(instance? clazz %)
+        (take-while some? (iterate #(.getCause %) ex))))
```
Comment (dpsutton) [inline test/metabase/driver/postgres_test.clj]: you could reuse `metabase.util/full-exception-chain` for this 

```clojure
(defn full-exception-chain
  "Gather the full exception chain into a sequence."
  [e]
  (when (instance? Throwable e)
    (take-while some? (iterate ex-cause e))))
```

File: src/metabase/driver/sql_jdbc/execute.clj [hunk 3]
```diff
@@ -405,6 +406,10 @@
             (.setAutoCommit conn false)
             (catch Throwable e
               (log/debug e "Error setting connection autoCommit to false"))))
+    (try
+      (.setNetworkTimeout conn (Executors/newSingleThreadExecutor) driver.settings/*network-timeout-ms*)
```
Comment (dpsutton) [inline src/metabase/driver/sql_jdbc/execute.clj]: I think this is not a great strategy for the executors here. This feels strange to make a new executor to make a new thread. Should this perhaps be cached thread executor and reuse those threads?

File: src/metabase/driver/sql_jdbc/execute.clj [hunk 4]
```diff
@@ -419,7 +440,11 @@
    options
    (fn [^Connection conn]
      (set-default-connection-options! driver db-or-id-or-spec conn options)
-     (f conn))))
+     (let [cancel-timeout! (wire-up-connection-close-timeout! conn driver.settings/*query-timeout-ms*)]
+       (try
+         (f conn)
+         (finally
+           (cancel-timeout!)))))))
```
Comment (rileythomp) [inline src/metabase/driver/sql_jdbc/execute.clj]: Note: This doesn't fix the reported issue. It was done as part of [this discussion](https://metaboat.slack.com/archives/C0645JP1W81/p1765561441861569). We need to decide whether we think this is worthwhile to keep or not.

File: src/metabase/driver/settings.clj [hunk 5]
```diff
@@ -100,6 +100,17 @@
   Adjusting the timeout does not impact Metabase’s frontend.
   Please be aware that other services (like Nginx) may still drop long-running queries.")
 
+;; This is normally set via the env var `MB_JDBC_NETWORKOUT_TIMEOUT_MS`
+(defsetting jdbc-networkout-timeout-ms
+  "By default, this is 30 minutes."
+  :visibility :internal
+  :export?    false
+  :type       :integer
+  :default    (if config/is-prod? 1800000 600000)
```
Comment (bronsa) [inline src/metabase/driver/settings.clj]: Those defaults look good to me, but if somebody manually tweaked `MB_DB_QUERY_TIMEOUT_MINUTES` to be higher, we risk not respecting it now that we have an additional timeout on top of it. 
How about something like `(min (if config/is-prod? 1800000 600000) (* 1000 60 (+ (db-query-timeout-minutes) 5)))` to ensure the default network timeout is always > than the query timeout (by 5 minutes in my example)?

File: src/metabase/driver/sql_jdbc/execute.clj [hunk 6]
```diff
@@ -405,6 +409,10 @@
             (.setAutoCommit conn false)
             (catch Throwable e
               (log/debug e "Error setting connection autoCommit to false"))))
+    (try
+      (.setNetworkTimeout conn @network-timeout-executor driver.settings/*network-timeout-ms*)
```
Comment (bronsa) [inline src/metabase/driver/sql_jdbc/execute.clj:415]: could do with a comment explaining why we're doing this, something like
```
  ;; setNetworkTimeout sets Socket.setSoTimeout() which releases
  ;; from blocked socket reads. This is necessary because .close() doesn't 't reliably interrupt 
  ;; threads stuck in native socket reads 
```

File: src/metabase/driver/settings.clj (hunk 5 above)
Comment (rileythomp) [reply src/metabase/driver/settings.clj]: @bronsa I think it sholud be `max` right?

Comment (bronsa) [reply src/metabase/driver/settings.clj]: yeah :)

**Review by bronsa — APPROVED** [review]
