### PR TITLE
Mongo objects should download as JSON, not EDN

### LINKED ISSUE #48198: Downloading data from Mongo Custom Query breaks the output
### Describe the bug

When creating a new custom query and downloading the results as CSV/JSON, the data downloaded is broken. The query I'm using is: 

```
[
  { $unwind: "$events" },
  {
    $group: {
      _id: {
        numberId: "$numberId",
        companyId: "$companyId"
      },
      eventsMap: {
        $push: {
          k: "$events.name",
          v: "$events.date"
        }
      }
    }
  },
  {
    $project: {
      numberId: "$_id.numberId",
      companyId: "$_id.companyId",
      events: { $arrayToObject: "$eventsMap" },
      _id: 0
    }
  },
  { $limit: 10 }
]
```

this returns values like 

Screenshot 2024-09-30 122852

At first sight the data seems correct, but when downloading it as JSON I get:

```
    {
        "numberId": "1000025",
        "companyId": "6579c1d289ad6a000767524f",
        "events": "{:last-accessed 2024-09-16T01:13:44.484Z, :last-order-created 2024-09-16T01:15:05.930Z}"
    },
```

The "events" object is parsed as a string and it is badly constructed too.

### To Reproduce

1. Create a custom mongo query that returns an object such as described above
2. Download data as JSON/CSV

### Expected behavior

It should download a proper JSON/CSV

### Logs

_No response_

### Information about your Metabase installation

```JSON
      "tag": "v0.50.24",
```

### Severity

blocking

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes #48198

Prior to this change, object columns (base or effective type of :type/Dictionary) were just formatted with `(str value)` which results in a csv or json download containing EDN formatted objects.

This is a bug because we present object column values as json in the app, so the expected formatting of the download should match this.

The formatter function now takes this type into account. As well, since this is a type of formatting that should be always applied (even when format_rows is false), the function is modified to unconditionally apply the json/encode formatting to dictionary types when encountered.

### CODE REVIEW

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 1]
```diff
@@ -365,12 +365,7 @@
 ;; `metabase.server.middleware`.
 (defmethod set-cell! Object
   [^Cell cell value _styles _typed-styles]
-  ;; stick the object in a JSON map and encode it, which will force conversion to a string. Then unparse that JSON and
-  ;; use the resulting value as the cell's new String value.  There might be some more efficient way of doing this but
-  ;; I'm not sure what it is.
-  (.setCellValue cell (str (-> (json/generate-string {:v value})
-                               (json/parse-string keyword)
-                               :v))))
+  (.setCellValue cell (json/generate-string value)))
```
Comment (adam-james-v) [inline src/metabase/query_processor/streaming/xlsx.clj:369]: I don't really understand why this is written this way. @camsaul maybe you know?
I think it's better to just use the json encoded string as the cell value. 

This way, we export xlsx files with values that look like json, matching the app. Before this change, a json-looking column is downloaded and looks like clojure edn, which most people think is broken json.

File: src/metabase/formatter.clj [hunk 2]
```diff
@@ -265,22 +266,39 @@
              (format "%.8f° %s" (Math/abs v) dir)
              v)))))
 
+(defn dictionary-formatter
```
Comment (camsaul) [inline src/metabase/formatter.clj:269]:
```suggestion
(defn- dictionary-formatter
```

Since this isn't used outside of this namespace it might be wise to mark it private. That way if someone wants to tweak it later (add another parameter or something like that) they don't need to check and see if it's used elsewhere first.

Best to keep surface area of things small

File: src/metabase/formatter.clj [hunk 3]
```diff
@@ -265,22 +266,39 @@
...
+  "Format dictionaries as json.
+  The value if a dictionary is Clojure edn on the backend, but displays as JSON in
+  When exporting, the map must be encoded as json so that exports match the app's output."
+  [value]
+  (if (string? value)
+    value
+    (json/encode value)))
```
Comment (camsaul) [inline src/metabase/formatter.clj:276]: You could use `cond->` here e.g.

```clj
(cond-> value
  (string? value) json/encode)
```

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 4]
```diff
@@ -365,12 +365,7 @@
 ;; `metabase.server.middleware`.
 (defmethod set-cell! Object
   [^Cell cell value _styles _typed-styles]
-  ;; stick the object in a JSON map and encode it, which will force conversion to a string. Then unparse that JSON and
-  ;; use the resulting value as the cell's new String value.  There might be some more efficient way of doing this but
-  ;; I'm not sure what it is.
```
Comment (camsaul) [inline src/metabase/query_processor/streaming/xlsx.clj:370]: what the hecc was the old code doing lol

File: src/metabase/query_processor/streaming/xlsx.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/query_processor/streaming/xlsx.clj:369]: Honestly this was 4 years ago and I really don't remember what my exact thinking was, but I'm guessing it was probably that if we had no other encoding method for something the fallback (`Object` method) would be to write it out as a some as a string representation. By using `json/generate-string` we could leverage our Cheshire methods for converting various Clojure data types to something more universally understood. I don't really remember why I have it reading it back to EDN tho. I think your change makes a lot of sense

File: test/metabase/query_processor/streaming/xlsx_test.clj [hunk 5]
```diff
@@ -643,7 +643,7 @@
 (deftest encode-strange-classes-test
   (testing (str "Make sure that we're piggybacking off of the JSON encoding logic when encoding strange values in "
                 "XLSX (#5145, #5220, #5459)")
-    (is (= ["Hello XLSX World!" "{:v \"No Encoder\"}"]
+    (is (= ["\"Hello XLSX World!\"" "{\"v\":\"No Encoder\"}"]
```
Comment (camsaul) [inline test/metabase/query_processor/streaming/xlsx_test.clj:646]: Devil's advocate but I think the old unquoted string behavior was probably preferrable. Someone is probably going to open a regression if we start quoting string column values in XLSX downloads when we didn't before. Maybe it's worth having a method specifically for `String`.

File: src/metabase/formatter.clj (hunk 2 above)
Comment (camsaul) [reply src/metabase/formatter.clj:269]: I'm also going to nitpick a little bit here and point out that _dictionary_, _map_, and _associative array_ are all basically synonyms in the computer science world but Clojure is in the _map_ camp so it probably be more idiomatic to use that name here instead of the alternatives.

```suggestion
(defn- map-formatter
```

Not that it makes a gigantic difference but not having to make that _dictionary => map_ translation in your head reduces the cognitive load of reading the code which makes it easier for other people to understand and work on going forward. If in doubt I like to error on the side of code that's easier to read

Comment (camsaul) [reply src/metabase/formatter.clj:269]: Actually I guess we call it `:type/Dictionary` so this argument maybe doesn't make sense. I'm not even sure what to believe anymore.

File: src/metabase/formatter.clj [hunk 6]
```diff
@@ -265,22 +266,39 @@
...
+              (isa? (:base_type col) :type/Number)))
+     (number-formatter col visualization-settings)
 
-    ;; todo integer columns with a unit
-    (or (isa? (:effective_type col) :type/Number)
-        (isa? (:base_type col) :type/Number))
-    (number-formatter col visualization-settings)
+     (or (isa? (:semantic_type col) :type/SerializedJSON)
+         (isa? (:base_type col) :type/Dictionary)
+         (isa? (:effective_type col) :type/Dictionary))
```
Comment (camsaul) [inline src/metabase/formatter.clj:300]: I think this should actually be something like 

```clj
(isa? (some-fn :effective_type :base_type) :type/Dictionary)
```

rather than `(or <isa? base-type...> <isa? effective-type...>)`... 

The reason for this is that effective type is how we actually treat the column whereas base type is the actual underlying column type, for example in the future it might be possible that we have a column of base type `:type/Dictionary` that undergoes a transformation to pull out a specific key giving it an effective type of `:type/Number` which means that we definitely shouldn't be applying map rules to that value.

This is not true now but it is the way this stuff is supposed to work so it would be nice that if we add that in the future it doesn't break this code

File: src/metabase/formatter.clj (hunk 2 above)
Comment (camsaul) [reply src/metabase/formatter.clj:269]: You know what forget I said anything about the name of this function. Not important. We should def make it private tho

**Review by camsaul — APPROVED** [review]
Well, overall this LGTM but I have a few suggestions

- I think we should not start wrapping string values in quotes if we weren't doing so before, this is one of those "who moved my cheese" things that is going to lead to people opening P1 regressions and it's better not to change behavior if we can avoid it 
- Stuff only used in the current namespace should be kept `:^private` for ease of changing the code in the future
- If effective type is present let's use just that and ignore base type to future-proof ourselves

These are minor tweaks so feel free to make those and then merge this in so we don't have to spend time on another PR review so I can 👍 again after you changed like 2 lines. I trust you
