### PR TITLE
Fix overly frequent line series dots

### LINKED ISSUE #39567: [dc.js migration] overly frequent line series dots
- Discussion: https://metaboat.slack.com/archives/C05NQSWPRMK/p1714165072406309

---
We should also switch the default setting to not show dots, per product/design feedback ([thread](https://metaboat.slack.com/archives/C06G94JTWBS/p1706194727139419)). In fact, if we do that then maybe this issue isn't worth fixing given how infrequently it'd come up.

question/4868
https://metaboat.slack.com/archives/C06G94JTWBS/p1706193945370869

Screenshot 2024-03-04 at 1 01 37 PM

question/4223
https://metaboat.slack.com/archives/C06G94JTWBS/p1706193960436849

https://metaboat.slack.com/archives/C05NQSWPRMK/p1714473071596039

### PR DESCRIPTION
**Pull request by JesseSDevaney**
- Closes: https://github.com/metabase/metabase/issues/39567

**Demo Changes** _(before and after)_

https://github.com/metabase/metabase/assets/22608765/7bd0c563-a6fa-4ede-bfef-4bd498cad729

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts [hunk 1]
```diff
@@ -302,31 +302,57 @@ const buildEChartsBarSeries = (
...
-  if (!isAuto) {
-    return seriesSettings["line.marker_enabled"];
+): boolean {
+  if (chartWidth <= 0) {
+    return false;
   }
+
+  const seriesWithSymbols = seriesModels.filter(seriesModel => {
+    const seriesSettings = seriesSettingsByDataKey[seriesModel.dataKey];
+    if (["area", "line"].includes(seriesSettings.display ?? "")) {
```
Comment (EmmadUsmani) [inline frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts:317]: We can replace this entire block with just `return ["area", "line"].includes(seriesSettings.display ?? "")`

**Review by EmmadUsmani — APPROVED** [review]
