### PR TITLE
Show name in save action form model picker

### LINKED ISSUE #30989: When saving a new action from the model detail, the model name isn't pre populated.
### Describe the bug

We don't seem to be auto populating the md

### To Reproduce

1. Go to a model that has actions enabled and create a new action for that model
2. Create your action and then go to save it.
3. In the name, description, model save modal - model isn't pre populated with the model you're working with.
4. Additionally, when you go to select the model manually, the model name doesn't get populated in the select.

### Expected behavior

I'd expect to see the model name pre selected.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Encountering this on stats as of build `f60e1e4`
```

### Severity

p1 I'd say. It busts working with actions in a pretty major way.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/30989

### Description

Model picker didn't preselect model in the picker on saving new action

### How to verify

Open a model -> create new Action -> save 
in the save new action modal the model should be preselected

if you click `+ New button` without model selected, placeholder should be shown

### Demo

https://www.loom.com/share/8e57ad87d22b4d46b0da4244621d9241

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/models/containers/FormModelPicker/FormModelPicker.tsx [hunk 1]
```diff
@@ -39,6 +38,11 @@ function FormModelPicker({
   const [{ value }, { error, touched }, { setValue }] = useField(name);
   const formFieldRef = useRef<HTMLDivElement>(null);
   const [width, setWidth] = useState(MIN_POPOVER_WIDTH);
+  const isActionFromModel = typeof value === "number";
```
Comment (WiNloSt) [inline frontend/src/metabase/models/containers/FormModelPicker/FormModelPicker.tsx:41]: I think this is a bit misleading, Actions are always tied to a model. I believe this check is for when no model is selected yet, so we would display a placeholder instead. e.g. when creating a new model via `+ New` button in the top right of the screen > `Action`
image

I think the name could be something along the line
```suggestion
  const isModelSelected = typeof value === "number";
```

Comment (uladzimirdev) [reply frontend/src/metabase/models/containers/FormModelPicker/FormModelPicker.tsx:41]: The action can be created from the top "+ New" button, in this case you don't have a model preselected 
image

I'm open for a better name, but I also want to highlight if there is a model already associated with the action. `isModelSelected` is fine, maybe `shouldPreselectModel`?

Comment (uladzimirdev) [reply frontend/src/metabase/models/containers/FormModelPicker/FormModelPicker.tsx:41]: what about `shouldInitiallyPreselectModel`? 😄 
`isModelSelected` - I can say the same - user didn't select the model, so why should we call it like this.

at the same time having in the code `typeof value === 'number'` is not self explained anyway

Comment (uladzimirdev) [reply frontend/src/metabase/models/containers/FormModelPicker/FormModelPicker.tsx:41]: hasValue doesn't show any business value here, it just tries to rephrase `typeof value === 'number'` IMO

Comment (uladzimirdev) [reply frontend/src/metabase/models/containers/FormModelPicker/FormModelPicker.tsx]: Alright, @WiNloSt I appreciate your patience and push for improvement, the var is changed

File: frontend/src/metabase/actions/containers/ActionCreator/ActionCreator.tsx [hunk 2]
```diff
@@ -183,7 +183,6 @@ function ActionCreator({
 }
 
 function ensureAceEditorClosed() {
-  // @ts-expect-error — `ace` isn't typed yet
```
Comment (uladzimirdev) [inline frontend/src/metabase/actions/containers/ActionCreator/ActionCreator.tsx:186]: had to remove it, otherwise ts-expect-error fails

File: frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts [hunk 3]
```diff
@@ -1,14 +1,16 @@
...
   createMockActionParameter,
+  createMockCard,
   createMockQueryAction,
 } from "metabase-types/api/mocks";
 
 import { setup } from "./common";
 
 describe("ActionCreator > Query Actions", () => {
-  describe("new action", () => {
+  describe("New Action", () => {
```
Comment (WiNloSt) [inline frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts:13]: Should you change https://github.com/metabase/metabase/blob/7b47197d561ed51a8765b4c7d75e8fea23001a4c/frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts#L113

to `Editing Action` too? Since it's at the same level as this `describe` block, I think their names should be consistent.

File: frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts [hunk 4]
```diff
@@ -45,6 +47,67 @@ describe("ActionCreator > Query Actions", () => {
...
+      const originalAce = window.ace;
+
+      beforeAll(() => {
+        window.ace = {
+          edit: jest.fn(),
+        };
+      });
+      afterAll(() => {
+        window.ace = originalAce;
+      });
```
Comment (WiNloSt) [inline frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts:61]: I find that adding `id={ACE_ELEMENT_ID}` to the `textarea` in the mock `NativeQueryEditor` can make the test work without having to mock ace's `edit` function manually here. I think that might be preferable since we basically double-mock here. One for `NativeQueryEditor` and one for `ace`s `edit` which I think should be taken care of by the mocked `NativeQueryEditor` instead.

What do you think?

https://github.com/metabase/metabase/blob/7b47197d561ed51a8765b4c7d75e8fea23001a4c/frontend/src/metabase/query_builder/components/__mocks__/NativeQueryEditor.jsx#L14

**Review by WiNloSt — APPROVED** [review]
I left a few comments, but overall this is looking great 👍

File: frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts (hunk 3 above)
Comment (uladzimirdev) [reply frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts:13]: changed

File: frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts (hunk 4 above)
Comment (uladzimirdev) [reply frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts]: it worked, all other tests passed too, thanks!
