### PR TITLE
Fix conditional formatting

### LINKED ISSUE #10663: Conditional formatting doesn't work
Conditional formatting appears to be totally broken in `release-0.33.x` and in the 0.33 jar. The only option that sort of works is highlighting the whole row, but it doesn't correctly highlight the individual cell(s) that meet the condition.

@metabase/core-developers I'm marking this as a P1 but do we think it's a P0?

image

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #10663

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/TableInteractive.jsx [hunk 1]
```diff
@@ -438,8 +443,9 @@ export default class TableInteractive extends Component {
     const isClickable = this.visualizationIsClickable(clicked);
     const backgroundColor = this.getCellBackgroundColor(
       settings,
+      value,
       rowIndex,
-      columnIndex,
+      column.name,
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/components/TableInteractive.jsx]: Why do we now need value and name rather than index? I guess that change happened before and broke formatting?

File: frontend/test/metabase/visualizations/components/Visualization-table.unit.spec.js [hunk 2]
```diff
@@ -0,0 +1,53 @@
+jest.mock("metabase/components/ExplicitSize");
+
+import React from "react";
+import { render, cleanup } from "@testing-library/react";
```
Comment (paulrosenzweig) [inline frontend/test/metabase/visualizations/components/Visualization-table.unit.spec.js]: Are we still using going to use this for unit tests?

**Review by paulrosenzweig — APPROVED** [review]
👍

**Review by kdoh — COMMENTED** [review]
Seems to do what it says on the tin as far as returning conditional formatting goes. One thing I did notice is the field selection dropdown gets an outline effect when you select the column for the first time. There's also a bit of a UX issue where it's not immediately clear that you can multi select the fields, especially since the text is `Select a column`

Screen Shot 2019-08-21 at 5 58 00 PM

**Review by mazameli — APPROVED** [review]
Seems to fix things 👍

**Comment by mazameli** [comment]
Shall we merge this Tom?

File: frontend/src/metabase/visualizations/components/TableInteractive.jsx (hunk 1 above)
Comment (tlrobinson) [reply frontend/src/metabase/visualizations/components/TableInteractive.jsx]: I think I broke it when I refactored some things. The conditional formatting settings always used column name as the key rather than index.

File: frontend/test/metabase/visualizations/components/Visualization-table.unit.spec.js (hunk 2 above)
Comment (tlrobinson) [reply frontend/test/metabase/visualizations/components/Visualization-table.unit.spec.js]: I copy pastad that from pie chart tests, but no probably not. Need to finish up #10478
