### PR TITLE
handle effective_type/coercions in fingerprinters

### LINKED ISSUE #15937: Fingerprints need to respect effective_type
our fingerprinters need to respect effective_type. Example, a string type that becomes a temporal type, when fingerprinted will throw variants of the following error:

> 2021-05-05 19:50:05,966 WARN sync.util :: Error fingerprinting Table 5,279 'default.yyyymmddhhss_times_times'
clojure.lang.ExceptionInfo: line 2:422: Unexpected parameters (timestamp, integer, integer) for function substring. Expected: substring(varchar(x), bigint, bigint) , substring(varchar(x), bigint)  {:message "line 2:422: Unexpected parameters (timestamp, integer, integer) for function substring.

This was never a problem in the past but has become one due to the ability to refingerprint fields. Fields are fingerprinted on first sync, and then basically never again. Exceptions to this are updating fingerprints for types and specifically redoing them (see `fingerprint-version->types-that-should-be-re-fingerprinted` and `honeysql-for-fields-that-need-fingerprint-updating`). These initial fingerprints were done before any conversion could be applied as these require human input.

Things to do:
- ensure that fingerprinting uses fingerprinters for the effective type, not the base type. It doesn't matter that a field is a string if our query_processor always inserts a cast to a temporal type. We never see the string.
- possibly dump fingerprints when changing the effective_type. The fingerprints are necessarily stale when the type changes. These can be left blank to be recomputed on the next sync, or possibly scheduled to refingerprint right away. If so, there's a ExecutorService in api.tables that could be moved to a better shared location to schedule these. It's there to sync tables as they become unhidden. Could become a general shared syncing executor.

I'm labelling this a P2 as fingerprints have been out of date for as long as we've had unix timestamps from integers. We should clean this up but it hasn't been catastrophic.

### PR DESCRIPTION
**Pull request by bronsa**
closes #15937
Closes https://linear.app/metabase/issue/SEM-3/fingerprints-need-to-respect-effective-type

This PR just adds unit tests explicitely verifying the behavior, it looks like the bug was already fixed by https://github.com/metabase/metabase/pull/15994, and refingerprinting on change was done by https://github.com/metabase/metabase/pull/16776

### CODE REVIEW

File: test/metabase/analyze/fingerprint/fingerprinters_test.clj [hunk 1]
```diff
@@ -71,7 +71,15 @@
                                  1234                                              ; int
                                  1594067133360                                     ; long
                                  "2007-12-03T10:15:30.00Z"                         ; string
-                                 (java.time.ZonedDateTime/of 2016 01 01 20 04 0 0 java.time.ZoneOffset/UTC)]))))))))))
+                                 (java.time.ZonedDateTime/of 2016 01 01 20 04 0 0 java.time.ZoneOffset/UTC)]))))
+            (testing "we respect effective_type"
```
Comment (lbrdnk) [inline test/metabase/analyze/fingerprint/fingerprinters_test.clj:76]: Looking at the [metabase.analyze.fingerprint.fingerprinters/fingerprinter](https://github.com/metabase/metabase/blob/fcef77fdef7af7ac7fac2333d9800109ad8e0070/src/metabase/analyze/fingerprint/fingerprinters.clj#L120) I'd say we do not properly handle the following scenario:
```
clj꞉metabase.analyze.fingerprint.fingerprinters-test꞉> 
(transduce identity
           (fingerprinters/fingerprinter (mi/instance :model/Field {:base_type :type/Text
                                                                    :coercion_strategy :Coercion/String->Float
                                                                    :effective_type :type/Float}))
           [1 2])
{:global {:distinct-count 2, :nil% 0.0},
 :type #:type{:Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 1.0}}}
```
Or is there some flaw in my reasoning?

**Review by lbrdnk — COMMENTED** [review]
Please see my comment first. 

For the other part of the issue that goes along ~"possibly dump fingerprints when changing the effective_type", were you able to confirm that behavior?

File: test/metabase/analyze/fingerprint/fingerprinters_test.clj (hunk 1 above)
Comment (bronsa) [reply test/metabase/analyze/fingerprint/fingerprinters_test.clj:76]: You're right, thank you. 
I have been following all the coercion definitions via `coercion-hierarchies/define-types!` and was under the impression we'd only coerce to `Temporal` values, which are all already handled, but I was not aware of `define-non-inheritable-type!` which defines the `String->Number` coercions. I'll extend this PR with treatment for those

**Comment by bronsa** [comment]
> For the other part of the issue that goes along ~"possibly dump fingerprints when changing the effective_type", were you able to confirm that behavior?

There's this code https://github.com/metabase/metabase/blob/master/src/metabase/warehouse_schema/api/field.clj#L155-L161 that forces refingerprinting of the field once the `effective_type` changes, I have verified that it does indeed happen and fingerprints are replaced when changing casting of a field from the UI

File: test/metabase/analyze/fingerprint/fingerprinters_test.clj (hunk 1 above)
Comment (bronsa) [reply test/metabase/analyze/fingerprint/fingerprinters_test.clj:76]: I've now updated the fingerprinters to also respect `->Number` coercions, following a similar approach for `->Temporal` coercions.  

One thing I don't like of the current approach, is that there is a disconnect between the coercions hieararchy and its handling in the fingerprinters, which is ad-hoc and opaque. 

For now, I've added an explicit check for the set of coercions we currently support (which is the whole set of coercions defined, for now), so that if others get added in the future, we'll be guarded against it.

File: src/metabase/analyze/fingerprint/fingerprinters.clj [hunk 2]
```diff
@@ -103,27 +103,49 @@
...
+    :Coercion/String->Number
+    ;; the numeric fingerprinter consider every number as a double
+    :Coercion/Float->Integer})
+
+(defn- ensure-coercion-is-supported [{coercion-strategy :coercion_strategy :as field}]
+  (when coercion-strategy
+    (when-not (some #(isa? coercion-strategy %) supported-coercions)
+      (throw (ex-info (format "Coercion strategy %s not supported by fingerprinters" coercion-strategy) field)))))
+
+(defn- fingerprinter-dispatch
```
Comment (lbrdnk) [inline src/metabase/analyze/fingerprint/fingerprinters.clj:120]: 👍

File: test/metabase/analyze/fingerprint/fingerprinters_test.clj (hunk 1 above)
Comment (lbrdnk) [reply test/metabase/analyze/fingerprint/fingerprinters_test.clj:76]: > if others get added in the future, we'll be guarded against it

I like that idea. I'm unsure of state of tests for coerced fields. The standard flow is (1) add database, (2) set coercion. The latter may have happened after the initial fingerprint ran, hence I think it could make sense to ensure that `fingerprinter-dispatch` could be called with all currently (or in future) derived coercions.

Something along enseure that dispatch won't throw for:
```
(filter #(= #{:Coercion/*} (parents %)) (descendants :Coercion/*))
```

Or would that be an overkill? WDYT?

Comment (lbrdnk) [reply test/metabase/analyze/fingerprint/fingerprinters_test.clj:76]: Or rather `(every? (fn [c] (some #(isa? c %) supported-coercions)) (descendants :Coercion/*))`.

**Review by lbrdnk — APPROVED** [review]

File: test/metabase/analyze/fingerprint/fingerprinters_test.clj (hunk 1 above)
Comment (bronsa) [reply test/metabase/analyze/fingerprint/fingerprinters_test.clj:76]: yeah that's a good idea to universally test this holds! I'll add the test and merge
