### PR TITLE
show banner and log error when token format is invalid

### LINKED ISSUE #33858: Entering a token with the wrong schema will make the properties endpoint fail
### Describe the bug

Try entering a wrong premium token with the env var, it will make the properties endpoint to fail

image

### To Reproduce

1) enter a premium token with the wrong schema
2) start Metabase

### Expected behavior

Nothing should fail if you enter a token with the wrong schema

<details><summary>Logs</summary>

```
{
    "via": [
        {
            "type": "clojure.lang.ExceptionInfo",
            "message": "Input to fetch-token-status* does not match schema: \n\n\t \u001B[0;33m  [(named (not (re-find #\"^[0-9a-f]{64}$\" a-java.lang.String)) token)] \u001B[0m \n\n",
            "data": {
                "type": "schema.core/error",
                "schema": [
                    {
                        "schema": "^[0-9a-f]{64}$",
                        "optional?": false,
                        "name": "token"
                    }
                ],
                "value": [
                    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                ],
                "error": [
                    "schema.utils.NamedError@17f2d3d1"
                ]
            },
            "at": [
                "metabase.public_settings.premium_features$fn__46693$fetch_token_status_STAR___46698",
                "invoke",
                "premium_features.clj",
                108
            ]
        }
    ],
    "trace": [
        [
            "metabase.public_settings.premium_features$fn__46693$fetch_token_status_STAR___46698",
            "invoke",
            "premium_features.clj",
            108
        ],
        [
            "metabase.public_settings.premium_features$fn__46725$fn__46726",
            "invoke",
            "premium_features.clj",
            161
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            154
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.core$apply",
            "invokeStatic",
            "core.clj",
            667
        ],
        [
            "clojure.core$apply",
            "invoke",
            "core.clj",
            662
        ],
        [
            "clojure.core.memoize$through_STAR_$fn__1558",
            "invoke",
            "memoize.clj",
            110
        ],
        [
            "clojure.core.cache$through$fn__1294",
            "invoke",
            "cache.clj",
            55
        ],
        [
            "clojure.core.memoize$through_STAR_$fn__1554$fn__1555",
            "invoke",
            "memoize.clj",
            109
        ],
        [
            "clojure.core.memoize.RetryingDelay",
            "deref",
            "memoize.clj",
            47
        ],
        [
            "clojure.core$deref",
            "invokeStatic",
            "core.clj",
            2337
        ],
        [
            "clojure.core$deref",
            "invoke",
            "core.clj",
            2323
        ],
        [
            "clojure.core.memoize$cached_function$fn__1622",
            "doInvoke",
            "memoize.clj",
            234
        ],
        [
            "clojure.lang.RestFn",
            "applyTo",
            "RestFn.java",
            137
        ],
        [
            "clojure.lang.AFunction$1",
            "doInvoke",
            "AFunction.java",
            31
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            408
        ],
        [
            "metabase.public_settings.premium_features$fn__46725$fn__46730",
            "invoke",
            "premium_features.clj",
            165
        ],
        [
            "metabase.public_settings.premium_features$fn__46765$fn__46766",
            "invoke",
            "premium_features.clj",
            194
        ],
        [
            "metabase.models.setting$get",
            "invokeStatic",
            "setting.clj",
            636
        ],
        [
            "metabase.models.setting$get",
            "invoke",
            "setting.clj",
            625
        ],
        [
            "metabase.models.setting$user_readable_values_map$fn__45789",
            "invoke",
            "setting.clj",
            1268
        ],
        [
            "clojure.core$map$fn__5931$fn__5932",
            "invoke",
            "core.clj",
            2759
        ],
        [
            "clojure.core$filter$fn__5958$fn__5959",
            "invoke",
            "core.clj",
            2823
        ],
        [
            "clojure.core.protocols$iter_reduce",
            "invokeStatic",
            "protocols.clj",
            49
        ],
        [
            "clojure.core.protocols$fn__8230",
            "invokeStatic",
            "protocols.clj",
            75
        ],
        [
            "clojure.core.protocols$fn__8230",
            "invoke",
            "protocols.clj",
            75
        ],
        [
            "clojure.core.protocols$fn__8178$G__8173__8191",
            "invoke",
            "protocols.clj",
            13
        ],
        [
            "clojure.core$transduce",
            "invokeStatic",
            "core.clj",
            6947
        ],
        [
            "clojure.core$into",
            "invokeStatic",
            "core.clj",
            6962
        ],
        [
            "clojure.core$into",
            "invoke",
            "core.clj",
            6950
        ],
        [
            "metabase.models.setting$user_readable_values_map",
            "invokeStatic",
            "setting.clj",
            1262
        ],
        [
            "metabase.models.setting$user_readable_values_map",
            "invoke",
            "setting.clj",
            1249
        ],
        [
            "metabase.api.session$fn__103719",
            "invokeStatic",
            "session.clj",
            294
        ],
        [
            "metabase.api.session$fn__103719",
            "invoke",
            "session.clj",
            290
        ],
        [
            "compojure.core$wrap_response$fn__42930",
            "invoke",
            "core.clj",
            160
        ],
        [
            "compojure.core$wrap_route_middleware$fn__42914",
            "invoke",
            "core.clj",
            132
        ],
        [
            "compojure.core$wrap_route_info$fn__42919",
            "invoke",
            "core.clj",
            139
        ],
        [
            "compojure.core$wrap_route_matches$fn__42923",
            "invoke",
            "core.clj",
            151
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__42923",
            "invoke",
            "core.clj",
            153
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__42923",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__42923",
            "invoke",
            "core.clj",
            153
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__42923",
            "invoke",
            "core.clj",
            153
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "metabase.api.session$_PLUS_log_all_request_failures$fn__103731",
            "invoke",
            "session.clj",
            324
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$make_context$handler__42970",
            "invoke",
            "core.clj",
            290
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            300
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "metabase.api.routes$fn__104720$fn__104721",
            "invoke",
            "routes.clj",
            64
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "clojure.lang.AFn",
            "applyToHelper",
            "AFn.java",
            160
        ],
        [
            "clojure.lang.AFn",
            "applyTo",
            "AFn.java",
            144
        ],
        [
            "clojure.core$apply",
            "invokeStatic",
            "core.clj",
            667
        ],
        [
            "clojure.core$apply",
            "invoke",
            "core.clj",
            662
        ],
        [
            "metabase.server.routes$fn__104883$fn__104884",
            "doInvoke",
            "routes.clj",
            72
        ],
        [
            "clojure.lang.RestFn",
            "invoke",
            "RestFn.java",
            436
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$make_context$handler__42970",
            "invoke",
            "core.clj",
            290
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            300
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__42923",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__42923",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$wrap_route_matches$fn__42923",
            "invoke",
            "core.clj",
            152
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            199
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$make_context$handler__42970",
            "invoke",
            "core.clj",
            290
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            300
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942$f__42943$respond_SINGLEQUOTE___42944",
            "invoke",
            "core.clj",
            197
        ],
        [
            "compojure.core$make_context$fn__42974",
            "invoke",
            "core.clj",
            301
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "compojure.core$routes$fn__42942$f__42943",
            "invoke",
            "core.clj",
            198
        ],
        [
            "compojure.core$routes$fn__42942",
            "invoke",
            "core.clj",
            200
        ],
        [
            "metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__101780",
            "invoke",
            "exceptions.clj",
            107
        ],
        [
            "metabase.server.middleware.exceptions$catch_api_exceptions$fn__101777",
            "invoke",
            "exceptions.clj",
            95
        ],
        [
            "metabase.server.middleware.log$log_api_call$fn__106766$fn__106767$fn__106768",
            "invoke",
            "log.clj",
            216
        ],
        [
            "metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info",
            "invokeStatic",
            "diagnostic.clj",
            18
        ],
        [
            "metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info",
            "invoke",
            "diagnostic.clj",
            12
        ],
        [
            "metabase.server.middleware.log$log_api_call$fn__106766$fn__106767",
            "invoke",
            "log.clj",
            208
        ],
        [
            "toucan2.execute$do_with_call_counts",
            "invokeStatic",
            "execute.clj",
            112
        ],
        [
            "toucan2.execute$do_with_call_counts",
            "invoke",
            "execute.clj",
            103
        ],
        [
            "metabase.server.middleware.log$log_api_call$fn__106766",
            "invoke",
            "log.clj",
            207
        ],
        [
            "metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__111849",
            "invoke",
            "browser_cookie.clj",
            41
        ],
        [
            "metabase.server.middleware.security$add_security_headers$fn__86414",
            "invoke",
            "security.clj",
            169
        ],
        [
            "metabase.server.middleware.json$wrap_json_body$fn__109266",
            "invoke",
            "json.clj",
            67
        ],
        [
            "metabase.server.middleware.offset_paging$handle_paging$fn__86438",
            "invoke",
            "offset_paging.clj",
            45
        ],
        [
            "metabase.server.middleware.json$wrap_streamed_json_response$fn__109284",
            "invoke",
            "json.clj",
            103
        ],
        [
            "ring.middleware.keyword_params$wrap_keyword_params$fn__112116",
            "invoke",
            "keyword_params.clj",
            55
        ],
        [
            "ring.middleware.params$wrap_params$fn__112135",
            "invoke",
            "params.clj",
            77
        ],
        [
            "metabase.server.middleware.misc$maybe_set_site_url$fn__59226",
            "invoke",
            "misc.clj",
            61
        ],
        [
            "metabase.server.middleware.session$reset_session_timeout$fn__68854",
            "invoke",
            "session.clj",
            441
        ],
        [
            "metabase.server.middleware.session$bind_current_user$fn__68821$fn__68822",
            "invoke",
            "session.clj",
            336
        ],
        [
            "metabase.server.middleware.session$do_with_current_user",
            "invokeStatic",
            "session.clj",
            315
        ],
        [
            "metabase.server.middleware.session$do_with_current_user",
            "invoke",
            "session.clj",
            304
        ],
        [
            "metabase.server.middleware.session$bind_current_user$fn__68821",
            "invoke",
            "session.clj",
            335
        ],
        [
            "metabase.server.middleware.session$wrap_current_user_info$fn__68802",
            "invoke",
            "session.clj",
            285
        ],
        [
            "metabase.server.middleware.session$wrap_session_id$fn__68785",
            "invoke",
            "session.clj",
            217
        ],
        [
            "metabase.server.middleware.auth$wrap_api_key$fn__96457",
            "invoke",
            "auth.clj",
            30
        ],
        [
            "ring.middleware.cookies$wrap_cookies$fn__112036",
            "invoke",
            "cookies.clj",
            216
        ],
        [
            "metabase.server.middleware.misc$add_content_type$fn__59208",
            "invoke",
            "misc.clj",
            29
        ],
        [
            "metabase.server.middleware.misc$disable_streaming_buffering$fn__59234",
            "invoke",
            "misc.clj",
            78
        ],
        [
            "ring.middleware.gzip$wrap_gzip$fn__112078",
            "invoke",
            "gzip.clj",
            86
        ],
        [
            "metabase.server.middleware.misc$bind_request$fn__59237",
            "invoke",
            "misc.clj",
            95
        ],
        [
            "metabase.server.middleware.ssl$redirect_to_https_middleware$fn__111865",
            "invoke",
            "ssl.clj",
            41
        ],
        [
            "metabase.server$async_proxy_handler$fn__75050",
            "invoke",
            "server.clj",
            77
        ],
        [
            "metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a",
            "handle",
            null,
            -1
        ],
        [
            "org.eclipse.jetty.server.handler.StatisticsHandler",
            "handle",
            "StatisticsHandler.java",
            173
        ],
        [
            "org.eclipse.jetty.server.handler.HandlerWrapper",
            "handle",
            "HandlerWrapper.java",
            122
        ],
        [
            "org.eclipse.jetty.server.Server",
            "handle",
            "Server.java",
            563
        ],
        [
            "org.eclipse.jetty.server.HttpChannel",
            "lambda$handle$0",
            "HttpChannel.java",
            505
        ],
        [
            "org.eclipse.jetty.server.HttpChannel",
            "dispatch",
            "HttpChannel.java",
            762
        ],
        [
            "org.eclipse.jetty.server.HttpChannel",
            "handle",
            "HttpChannel.java",
            497
        ],
        [
            "org.eclipse.jetty.server.HttpConnection",
            "onFillable",
            "HttpConnection.java",
            282
        ],
        [
            "org.eclipse.jetty.io.AbstractConnection$ReadCallback",
            "succeeded",
            "AbstractConnection.java",
            314
        ],
        [
            "org.eclipse.jetty.io.FillInterest",
            "fillable",
            "FillInterest.java",
            100
        ],
        [
            "org.eclipse.jetty.io.SelectableChannelEndPoint$1",
            "run",
            "SelectableChannelEndPoint.java",
            53
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "runTask",
            "AdaptiveExecutionStrategy.java",
            416
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "consumeTask",
            "AdaptiveExecutionStrategy.java",
            385
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "tryProduce",
            "AdaptiveExecutionStrategy.java",
            272
        ],
        [
            "org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
            "lambda$new$0",
            "AdaptiveExecutionStrategy.java",
            140
        ],
        [
            "org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread",
            "run",
            "ReservedThreadExecutor.java",
            411
        ],
        [
            "org.eclipse.jetty.util.thread.QueuedThreadPool",
            "runJob",
            "QueuedThreadPool.java",
            969
        ],
        [
            "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
            "doRunJob",
            "QueuedThreadPool.java",
            1194
        ],
        [
            "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
            "run",
            "QueuedThreadPool.java",
            1149
        ],
        [
            "java.lang.Thread",
            "run",
            null,
            -1
        ]
    ],
    "cause": "Input to fetch-token-status* does not match schema: \n\n\t \u001B[0;33m  [(named (not (re-find #\"^[0-9a-f]{64}$\" a-java.lang.String)) token)] \u001B[0m \n\n",
    "data": {
        "type": "schema.core/error",
        "schema": [
            {
                "schema": "^[0-9a-f]{64}$",
                "optional?": false,
                "name": "token"
            }
        ],
        "value": [
            "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],
        "error": [
            "schema.utils.NamedError@17f2d3d1"
        ]
    },
    "message": "Input to fetch-token-status* does not match schema: \n\n\t \u001B[0;33m  [(named (not (re-find #\"^[0-9a-f]{64}$\" a-java.lang.String)) token)] \u001B[0m \n\n",
    "value": [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    ],
    "error": [
        "schema.utils.NamedError@17f2d3d1"
    ]
}
```

</details>

### Information about your Metabase installation

```JSON
forever
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sansolovyov**
Makes `/api/properties` and `/api/premium-features/token/status` return valid structures with information about invalid token, plus logs the error about token being invalid in logs. Also this information is used to show a `PaymentBanner` on top of the screen so that admins can understand what is going on.

image

Plus `PremiumEmbeddingLicensePage` got a bit of an update — it relied on `value`, which is not returned from the backend (anymore?), so now it looks for `status`.

Resolves #33858.

### CODE REVIEW

**Review by uladzimirdev — APPROVED** [review]
FROM code perspective LGTM

File: src/metabase/public_settings/premium_features.clj [hunk 1]
```diff
@@ -105,38 +106,42 @@
...
-        result (deref fut fetch-token-status-timeout-ms ::timed-out)]
-    (if (= result ::timed-out)
-      (do
-        (future-cancel fut)
-        {:valid         false
-         :status        (tru "Unable to validate token")
-         :error-details (tru "Token validation timed out.")})
-      result)))
+  (log/infof "Checking with the MetaStore to see whether token '%s' is valid..." (u.str/mask token))
+  (if-not (mc/validate ValidToken token)
```
Comment (qnkhuat) [inline src/metabase/public_settings/premium_features.clj:113]: I think we can do this earlier in the call chain, how about checking this in the getter of `token-status`?

also, I wonder why it doesn't go through the setter of `premium-embedding-token`, we already have a schema check there.

File: src/metabase/util/string.clj [hunk 2]
```diff
@@ -29,3 +30,19 @@
        (= (count parts) 1) (str (first parts) (when stop? \.))
        (= (count parts) 2) (str (first parts) " " (deferred-tru "and")  " " (second parts) (when stop? \.))
        :else               (str (first parts) ", " (build-sentence (rest parts) options))))))
+
+
```
Comment (qnkhuat) [inline src/metabase/util/string.clj:34]:
```suggestion
```

File: src/metabase/util/string.clj [hunk 3]
```diff
@@ -29,3 +30,19 @@
...
+(defn mask
```
Comment (qnkhuat) [inline src/metabase/util/string.clj:35]: nice, looks like slack-app-token use this feature as well, maybe we could re-use this helper fn there ? https://github.com/metabase/metabase/blob/d8322e9a89b65835d4c3726e7dd4131ca8c7d744/src/metabase/integrations/slack.clj#L33

out of scope of this PR so up to you if you want to do it.

File: test/metabase/util/string_test.clj [hunk 4]
```diff
@@ -0,0 +1,22 @@
+(ns metabase.util.string-test
+  (:require
+   [clojure.test :refer :all]
+   [metabase.util.string :as u.str]))
+
+
```
Comment (qnkhuat) [inline test/metabase/util/string_test.clj:6]:
```suggestion
```

File: src/metabase/public_settings/premium_features.clj (hunk 1 above)
Comment (piranha) [reply src/metabase/public_settings/premium_features.clj:113]: If I understood code correctly, then `:setter` is only called when you set something from inside Metabase' codebase. With env var, Metabase starts up and then when you call `(premium-embedding-token)`, it's going through `settings/get`, which eventually gets value from the environment. I agree it would be better if `register-setting!` or whoever is at fault should call `:setter`, but this looks like a much bigger (and not totally backward compatible) change?

File: src/metabase/util/string.clj (hunk 2 above)
Comment (piranha) [reply src/metabase/util/string.clj:34]: I just love newlines, it seems I can't notice them in diffs...

**Review by qnkhuat — APPROVED** [review]
BE LGTM
