### PR TITLE
Always create a transient dataset for BigQuery tests

### LINKED ISSUE #28792: [CI] BigQuery intermittent (but frequent) test failures
Example of a failed run:
https://github.com/metabase/metabase/actions/runs/4304721614/jobs/7506170453#step:3:471

This failure happens **a lot** and the key thing seems to be: `Failed to create :bigquery-cloud-sdk 'test-data' test database`

```
ERROR in metabase-enterprise.sandbox.query-processor.middleware.row-level-restrictions-test/pivot-query-test (impl.clj:140)
Uncaught exception, not in assertion.

clojure.lang.ExceptionInfo: Failed to create :bigquery-cloud-sdk 'test-data' test database: Failed to create test database: Error in sync step Sync bigquery-cloud-sdk Database 66 'test-data': Error in sync step Analyze data for bigquery-cloud-sdk Database 66 'test-data': Error in sync step fingerprint-fields: Error fingerprinting Table 229 'v3_test_data.view_WXBVWOIRAWZVTGRPPCNZ': Output of get-table does not match schema: 
                            
                            	   (not (instance? com.google.cloud.bigquery.Table nil))  
    database-name: "test-data"
           driver: :bigquery-cloud-sdk
clojure.lang.ExceptionInfo: Failed to create test database: Error in sync step Sync bigquery-cloud-sdk Database 66 'test-data': Error in sync step Analyze data for bigquery-cloud-sdk Database 66 'test-data': Error in sync step fingerprint-fields: Error fingerprinting Table 229 'v3_test_data.view_WXBVWOIRAWZVTGRPPCNZ': Output of get-table does not match schema: 
                            
                            	   (not (instance? com.google.cloud.bigquery.Table nil))  
    connection-details: {:project-id nil,
                         :service-account-json
                         "***",
                         :dataset-id "v3_test_data",
                         :include-user-id-and-hash true}
         database-name: "test-data"
                driver: :bigquery-cloud-sdk
clojure.lang.ExceptionInfo: Error in sync step Sync bigquery-cloud-sdk Database 66 'test-data': Error in sync step Analyze data for bigquery-cloud-sdk Database 66 'test-data': Error in sync step fingerprint-fields: Error fingerprinting Table 229 'v3_test_data.view_WXBVWOIRAWZVTGRPPCNZ': Output of get-table does not match schema: 
                            
                            	   (not (instance? com.google.cloud.bigquery.Table nil))  
clojure.lang.ExceptionInfo: Error in sync step Analyze data for bigquery-cloud-sdk Database 66 'test-data': Error in sync step fingerprint-fields: Error fingerprinting Table 229 'v3_test_data.view_WXBVWOIRAWZVTGRPPCNZ': Output of get-table does not match schema: 
                            
                            	   (not (instance? com.google.cloud.bigquery.Table nil))  
clojure.lang.ExceptionInfo: Error in sync step fingerprint-fields: Error fingerprinting Table 229 'v3_test_data.view_WXBVWOIRAWZVTGRPPCNZ': Output of get-table does not match schema: 
                            
                            	   (not (instance? com.google.cloud.bigquery.Table nil))  
clojure.lang.ExceptionInfo: Error fingerprinting Table 229 'v3_test_data.view_WXBVWOIRAWZVTGRPPCNZ': Output of get-table does not match schema: 
                            
                            	   (not (instance? com.google.cloud.bigquery.Table nil))  
clojure.lang.ExceptionInfo: Output of get-table does not match schema: 
                            
                            	   (not (instance? com.google.cloud.bigquery.Table nil))  
     error: (not (instance? com.google.cloud.bigquery.Table nil))
    schema: com.google.cloud.bigquery.Table
      type: :schema.core/error
     value: nil

### PR DESCRIPTION
**Pull request by john-metabase**
The BigQuery test data code already has a mechanism for transient datasets. Now all datasets get the transient treatment.

Fixes common test flakes in `be-tests-bigquery-cloud-sdk-ee` and `be-google-related-drivers-classpath-test`.

Resolves #28792 🤞

### CODE REVIEW

**Comment by john-metabase** [comment]
Obviously there's a problem with creating test tables now... working on that locally. Sorry for the bad push.

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj [hunk 1]
```diff
@@ -23,16 +23,32 @@
    [metabase.util.honeysql-extensions :as hx]
    [toucan2.tools.with-temp :as t2.with-temp]))
 
+(def ^:private test-db-name (bigquery.tx/normalize-name :db "test_data"))
+
+(def ^:private sample-dataset-name (bigquery.tx/normalize-name :db "sample_dataset"))
+
+(defn- with-test-db-name
```
Comment (john-metabase) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj:30]: This is so complicated because it handles simple strings as well as the SQL maps passed to `sql=`.

**Comment by john-metabase** [comment]
I do not love the solution here, especially in the query processor tests, but this is a band-aid fix to stop a major cause of CI failures. A second pass to further clean up test code could happen when I get back to working on nested fields in the BigQuery driver.

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj [hunk 2]
```diff
@@ -23,16 +23,32 @@
...
+  "Replaces instances of v3_test_data with the full per-test-run DB name"
+  [x]
+  (cond
+    (string? x) (str/replace x "v3_test_data" test-db-name)
+    (map? x)    (update-vals x with-test-db-name)
+    (vector? x) (mapv with-test-db-name x)
+    (list?   x) (-> x vec with-test-db-name list*)
```
Comment (metamben) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj:37]: If we want to keep the original types, then we need
```suggestion
    (list?   x) (apply list (map with-test-db-name x))
```
but this wouldn't handle sequences. Maybe we should do
```suggestion
    (seq?    x) (map with-test-db-name x)
```
instead. (We can put it into `doall` if fully realizing is important.)

File: modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj [hunk 3]
```diff
@@ -326,52 +309,33 @@
...
+      (log/info (u/format-color 'blue "Deleting temporary dataset more than two hours old: %s`." outdated))
+      (u/ignore-exceptions
+       (destroy-dataset! outdated))))
   ;; now check and see if we need to create the requested one
   (let [database-name (normalize-name :db database-name)]
-    (when-not (contains? @existing-datasets database-name)
-      (u/ignore-exceptions
+    (u/auto-retry 2
+     (try
+       (log/infof "Creating dataset %s..." (pr-str database-name))
```
[the remark this answers is not in the document]
Comment (john-metabase) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj:321]: I believe `tx/create-db!` is only called when a `Database` doesn't exist for the given dataset in the Metabase instance. I checked locally and it seems to behave sanely for BigQuery tests.

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj (hunk 2 above)
Comment (john-metabase) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj:37]: This is only to accommodate test expressions in this file, and the tests pass, so I don't think we need to cover any other cases.

Comment (john-metabase) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj:37]: And this is just for test equality, so the types don't matter.

```
(= (list 1 2 3) (list* (list 1 2 3))) ;; => true
```

File: modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj (hunk 3 above)
[the remark this answers is not in the document]
Comment (john-metabase) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj:321]: I removed the comment in question. Will push it as soon as BQ tests pass again (want to stress test the flakiness)

**Comment by john-metabase** [comment]
The latest push had a failure in `be-google-related-drivers-classpath-test`, but it looks like a different flake (timeout), unrelated to anything in this PR.

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj (hunk 2 above)
Comment (metamben) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj:37]: Wouldn't 
```suggestion
    (list?   x) (map with-test-db-name x)
```
work just as well?

**Review by metamben — APPROVED** [review]

**Comment by camsaul** [comment]
Question

How does this affect performance for BigQuery tests? I think the reason I put the reuse-existing-dataset stuff in there in the first place was that loading data was for BigQuery was really slow. Do you have a sense of whether that's still the case or not?

**Comment by john-metabase** [comment]
@camsaul the performance is fine. In fact, this latest run was (by chance I'd assume) a few minutes faster than a run in a branch without these changes.

**Comment by qnkhuat** [comment]
I always thought main the reason we do this billing concern. Same with snowflake

**Comment by camsaul** [comment]
No, CI performance is the main driver, not billing
