### PR TITLE
[serdes] handle circular dependencies in dashboards

### LINKED ISSUE #38665: Cannot import dashboards with circular click behavior
### Describe the bug

It is impossible to import dashboards with a circular click behavior, for example, when a dashboard links to itself, or when click behavior dashboard A has a link pointing to dashboard B which has a link pointing to dashboard A.

### To Reproduce

1. Create a DashboardA, add a QuestionA
2. Create DashboardB, add a QuestionB
3. Set up a circular click route between the dashboards:
   * DashboardA/QuestionA --> DashboardB
   * DashboardB/QuestionB --> DashboardA
4. Export everything
5. (!) Import and see the circular reference error below

### Expected behavior

The import should work, load all resources, and restore all exported links.

### Logs

clojure.lang.ExceptionInfo: Circular dependency on [{:model "Dashboard", :id "GUnezeAXjrWMd8k4x8PXx"}] {:path [{:model "Dashboard", :id "GUnezeAXjrWMd8k4x8PXx"}]}

### Information about your Metabase installation

```JSON
Reported in v47, also broken as of 1.48.5.
```

### Severity

Reported by a customer. No workaround, apart from removing some of the links..

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sansolovyov**
Resolves #38665

### CODE REVIEW

**Review by tsmacdonald — APPROVED** [review]

File: enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj [hunk 1]
```diff
@@ -1223,3 +1223,36 @@
...
+      (t2/delete! DashboardCard :id [:in (map :id [dc1 dc2 dc3])])
+      (testing "Circular dependencies are loaded correctly"
+        (is (serdes.load/load-metabase! (ingestion-in-memory @ser)))
+        (let [select-target #(-> % :visualization_settings :click_behavior :targetId)]
+          (is (= (:id dash2)
+                 (t2/select-one-fn select-target DashboardCard :entity_id (:entity_id dc1))))
+          (is (= (:id dash3)
+                 (t2/select-one-fn select-target DashboardCard :entity_id (:entity_id dc2))))
+          (is (= (:id dash1)
+                 (t2/select-one-fn select-target DashboardCard :entity_id (:entity_id dc3)))))))))
```
Comment (bshepherdson) [inline enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj:1258]: <i class='graphite__hidden'>[Re: line 1259]<br/><br/></i>

These tests look good but I'd be glad to see what happens if the no-deps retry fails. We really want to make sure that partial entities are never left in the DB. They need to abort.<span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/metabase/metabase/42267?utm_source=unchanged-line-comment">Graphite</a>.</span>

**Review by bshepherdson — CHANGES_REQUESTED** [review]

File: enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj (hunk 1 above)
Comment (piranha) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj:1258]: We have a [test to check what happens when exception comes through](https://github.com/metabase/metabase/blob/master/enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj#L1199-L1225), seems like it should be enough to guarantee no problems here?

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 2]
```diff
@@ -22,29 +29,41 @@
...
-                  (if (and (= (:error (ex-data e)) ::not-found)
-                           (serdes/load-find-local dep))
+                  (cond
                     ;; It was missing but we found it locally, so just return the context.
+                    (and (= (:error (ex-data e)) ::not-found)
+                         (serdes/load-find-local dep))
                     ctx
-                    ;; Different error, or couldn't find it locally, so rethrow.
+
+                    ;; It's a circular dep, strip of probable cause and retry. This will store an incomplete version
```
Comment (crisptrutski) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:38]:
```suggestion
                    ;; It's a circular dep, strip off probable cause and retry. This will store an incomplete version
```

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 3]
```diff
@@ -22,29 +29,41 @@
...
-  references in this entity can be resolved properly.
+  If the incoming entity has any dependencies, they are recursively processed first (postorder) so that any foreign
+  key references in this entity can be resolved properly.
 
   This is mostly bookkeeping for the overall deserialization process - the actual load of any given entity is done by
   [[metabase.models.serialization/load-one!]] and its various overridable parts, which see.
 
-  Circular dependencies are not allowed, and are detected and thrown as an error."
-  [{:keys [expanding ingestion seen] :as ctx} path]
+  Error is thrown on a circular dependency, should be handled and retried at the caller. `modfn` is an optional
```
Comment (crisptrutski) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:59]: It seems smelly to me to define `modfn` only in terms of a specific function it gets used with, rather than according to how it works in an abstract setting. It's also a pretty opaque name.

This could point to just using a flag instead, until you find another use-case. If you were to just take a flag, this function could then encapsulate the detail of stripping (disj) `path` from `expanding` as well.

**Comment by crisptrutski** [comment]
Do we not need to worry about circular dependencies in `load-metabase!` as well?

**Review by crisptrutski — APPROVED** [review]

**Comment by crisptrutski** [comment]
With the wit of the staircase, it was only after I posted my review that I put my finger on why the naming had confused me.

This is not about breaking a circuit, it is about short-circuiting.

The former is about aborting a process, e.g. due to too many attempts, whereas this is about skipping things that aren't actually required. 💡

**Comment by piranha** [comment]
> This is not about breaking a circuit, it is about short-circuiting.

Hm, how so? It's absolutely about breaking a circuit - I strip references so that it's not going into another loop of referencing and this way stop the circuit from happening.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 4]
```diff
@@ -54,7 +73,10 @@
                                               :deps-chain expanding
                                               :error      ::not-found}
                                              e))))
+                ingested (cond-> ingested
```
[the remark this answers is not in the document]
Comment (piranha) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:76]: It's going to be 3 inlines or 3 renames and it's similar enough not to bother me that it's keeping the name :)

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 5]
```diff
@@ -22,29 +29,41 @@
...
 
   This is mostly bookkeeping for the overall deserialization process - the actual load of any given entity is done by
   [[metabase.models.serialization/load-one!]] and its various overridable parts, which see.
 
-  Circular dependencies are not allowed, and are detected and thrown as an error."
-  [{:keys [expanding ingestion seen] :as ctx} path]
+  Error is thrown on a circular dependency, should be handled and retried at the caller. `modfn` is an optional
+  parameter to modify entity so that circular dependency could be stripped and (temporary) incomplete entity could be
+  stored."
+  [{:keys [expanding ingestion seen] :as ctx} path & [modfn]]
```
[the remark this answers is not in the document]
Comment (piranha) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:62]: It's a modification function, not a preload function, right? `modfn` sounds way more understandable to me.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj (hunk 3 above)
Comment (piranha) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:59]: Right now logic is incapsulated in `load-deps!`, I don't think it's a problem, but I agree that describing only in terms of circuit breaking is not ideal.

**Comment by calherries** [comment]
I guess because "circuit breaking" is a name taken up by https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern, so calling this circuit breaking is misleading for new readers. I would rather call this something else to avoid that confusion

**Comment by piranha** [comment]
Right... it's more like a loop breaker, yeah. But short-circuiting is something else too, right?

**Comment by piranha** [comment]
I've removed all mentions of "circuit breaking", since that obviously got in my mind because of words similarity with "circular". 😁 @crisptrutski do you like it better now? :)

**Comment by piranha** [comment]
> Do we not need to worry about circular dependencies in load-metabase! as well?

I don't think so, since `:expanding` is encapsulated in `load-one!`, it only gets increased (and then decreased) during `load-deps!`.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj (hunk 4 above)
[the remark this answers is not in the document]
Comment (crisptrutski) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:76]: Ah, I missed the extra usages over the fold.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj (hunk 5 above)
[the remark this answers is not in the document]
Comment (crisptrutski) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:62]: To each his own 🤷

File: enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj (hunk 1 above)
Comment (bshepherdson) [reply enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj:1258]: Ah, that's acceptable, yeah. We don't need to check specifically on a circular deps error.

**Review by bshepherdson — APPROVED** [review]
