### PR TITLE
fix(sdk): use background color in sankey chart text outline

### LINKED ISSUE #56872: [SDK] sankey charts white text outline cannot be removed or themed in dark-themed apps
When using the SDK with a dark-themed theme object ([see example used by a customer here](https://metaboat.slack.com/archives/C07166YL2UU/p1743776481388599?thread_ts=1743721302.432259&cid=C07166YL2UU)) and rendering a Sankey chart, a white text stroke outline is very visible and cannot be removed via a theme object. This is only visible on dark/colored backgrounds as the text stroke is white.

> For Sankey chart, I'm having trouble figuring out how to target the white stroke that is getting added to the labels, not sure what property in the config controls this.

### How to reproduce

See this message in the [ext-sdk-customers Slack channel](https://metaboat.slack.com/archives/C07166YL2UU/p1743721302432259).

### PR DESCRIPTION
**Pull request by heypoom**
Closes EMB-319
Closes #56872

### Description

When using the SDK with a dark-themed theme object ([see example used by a customer here](https://metaboat.slack.com/archives/C07166YL2UU/p1743776481388599?thread_ts=1743721302.432259&cid=C07166YL2UU)) and rendering a Sankey chart, a white text stroke outline is very visible and cannot be removed via a theme object. This is only visible on dark-themed backgrounds as the text stroke is white.

image

This can be fixed by using `bg-white`. We cannot use `var(--mb-color-background)` because static viz's SVG engine does not support CSS variables and will throw errors.

CleanShot 2568-04-23 at 23 13 52@2x

### How to verify

Use this setup in the Embedding SDK to test.

```
<MetabaseProvider
  authConfig={{
    metabaseInstanceUrl: "http://localhost:3000",
    apiKey: "(your-api-key)",
  }}
  theme={{
    colors: {
      background: "#2d2d30",
      "text-primary": "#fff",
      "text-secondary": "#b3b3b3",
      "text-tertiary": "#fff",
      brand: "#ff8d00",
    },
  }}
>
  <InteractiveDashboard dashboardId={13} />
</MetabaseProvider>
```

Use this SQL query for Sankey

```
WITH static_data AS (
    SELECT * FROM (
        VALUES
            ('Entry', 'Homepage', 584),
            ('Homepage', 'Product Page', 2700),
            ('Product Page', 'Add to Cart', 572),
            ('Add to Cart', 'Checkout', 2490),
            ('Checkout', 'Purchase', 1756),
            ('Homepage', 'Search', 2427),
            ('Search', 'Product Page', 2027),
            ('Homepage', 'Exit', 850),
            ('Search', 'Exit', 400),
            ('Product Page', 'Exit', 650)
        ) AS t("SOURCE PAGE", "TARGET PAGE", "TOTAL VISITORS")
)

SELECT
    "SOURCE PAGE" as source_page,
    "TARGET PAGE" as target_page,
    "TOTAL VISITORS" as total_visitors
FROM
    static_data
ORDER BY
    source_page,
    target_page;
```

### Checklist

- [x] Tests have been added/updated to cover changes in this PR - Loki test

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/graph/sankey/option/index.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ export const getSankeyChartOption = (
       color: renderingContext.getColor("text-dark"),
       fontSize: SANKEY_CHART_STYLE.edgeLabels.size,
       textBorderWidth: SANKEY_CHART_STYLE.edgeLabels.textBorderWidth,
-      textBorderColor: renderingContext.getColor("white"),
+      textBorderColor: renderingContext.getColor("bg-white"),
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/echarts/graph/sankey/option/index.ts:70]: Using `var(--mb-color-background)` would break static viz, so we use `bg-white` instead.

**Review by lorem--ipsum — APPROVED** [review]

**Review by alxnddr — APPROVED** [review]
