### PR TITLE
fix(sdk): load custom font files when font is set to custom

### LINKED ISSUE #44370: Custom font families are not loading in embedding sdk
The custom font families are not loading in the embedding sdk. I configured the families in the MB instance and the custom fonts show in the main Metabase app, but it seems like the font declaration is not loading even when the font family is set to Custom.

I suspect it has to do with `fontFiles.map` line in `SdkContentWrapper`.

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/44370

### Description

Return custom font files when the embedded font is set to Custom.

### How to verify

- Go to the `fix-font-families` branch in the demo app. Run the demo app (including the API) locally.
- Fonts should now be loaded properly.

### Limitations

- We only support the 400, 700 and 900 weights in the appearance settings, and we can only set one font at a time. We will address this in https://github.com/metabase/metabase/issues/44394 next.

CleanShot 2567-06-20 at 01 06 42@2x

### Demo

CleanShot 2567-06-20 at 01 07 57@2x

### CODE REVIEW

File: frontend/src/metabase/styled-components/selectors.ts [hunk 1]
```diff
@@ -20,7 +20,9 @@ export const getFont = createSelector(
 export const getFontFiles = createSelector(
   [getSettings, getEmbedOptions],
   (settings, embedOptions) => {
-    if (embedOptions.font) {
+    // If a font is set in the embed options, we don't need to load any font files.
+    // However, we still need to load the custom font files if the font is set to "Custom".
+    if (embedOptions.font && embedOptions.font !== "Custom") {
```
Comment (heypoom) [inline frontend/src/metabase/styled-components/selectors.ts:25]: I'm adding a unit test today. I just added you as reviewer first, so I can confirm if this makes sense.

Comment (WiNloSt) [inline frontend/src/metabase/styled-components/selectors.ts:25]: With the way we're loading font files right now. If there's `settings["application-font-files"]` we should just return it. There's no reason to conditionally return this value since `application-font-files` only exists when Metabase font is set to `custom`. Also, it's okay to even leave font files in the CSS since if `font-family` isn't set to `Custom` these fonts shouldn't be loaded anyway.

Here's how we use `fontFiles` at the moment. https://github.com/metabase/metabase/blob/5638d797689f87861ee20a92dea326d988d2bc58/frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx#L73-L83

I suggest we remove this if block entirely and the selector would just simply returns `settings["application-font-files"]`

Also see a [related discussion.](https://metaboat.slack.com/archives/C505ZNNH4/p1715098187144839)

**Review by WiNloSt — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/styled-components/selectors.ts (hunk 1 above)
Comment (heypoom) [reply frontend/src/metabase/styled-components/selectors.ts:25]: @WiNloS Awesome - thanks Kelvin! I thought something was fishy when I read this conditions, but I was unsure about removing it altogether since I'm not sure how it would work in static embedding / interactive embedding.

Comment (heypoom) [reply frontend/src/metabase/styled-components/selectors.ts]: done!

File: enterprise/frontend/src/embedding-sdk/components/private/SdkContentWrapper.unit.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+            fontFormat: "woff2",
+            fontWeight: 700,
+          },
+        ],
+      }),
+    });
+
+    renderWithProviders(<SdkContentWrapper />, { storeInitialState: state });
+
+    const rules = Array.from(document.styleSheets).flatMap(sheet =>
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk/components/private/SdkContentWrapper.unit.spec.tsx:24]: I never knew you could directly use `document` in the test.

**Review by WiNloSt — APPROVED** [review]

File: enterprise/frontend/src/embedding-sdk/components/private/SdkContentWrapper.unit.spec.tsx (hunk 2 above)
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/components/private/SdkContentWrapper.unit.spec.tsx:24]: God bless react-testing-library and JSDOM!
