### PR TITLE
MBQL: fix integer divisions

### LINKED ISSUE #8783: Dividing integers not working using Custom Expression
We work with a few metrics which involve ratios between values, e.g. the click-through rate for visitors coming to our website through paid ads. In some cases I compute these in data pipelines but in some cases it's not feasible to compute all potential derived metrics; I want our analysts to do this when they need them.

I found that when asking questions in Metabase using the custom builder it doesn't handle dividing integer values, e.g. the click-through rate defined as number of clicks over number of impressions. Adjusting the data model and defined types for these fields (e.g. Number) doesn't make a difference. If I look at the SQL generated, it looks like this:

```sql
SELECT
  (sum("table"."integer") / sum("table"."another_integer")) AS "sum / sum"
FROM "table"
```

This won't work in e.g. Postgres. Multiplying with 100 and dividing by 100 in the Custom Expressions works as intended, because the value is actually converted to a float:

```sql
SELECT
  ((sum("table"."integer") * 100.0 / sum("table"."another_integer") / 100.0) AS "(sum * ) / sum / "
FROM "table"
```

This produces the correct result. We're using Metabase v0.30.1 but I ran the same query on the most recent v0.30.4, without luck.

I don't want to change all attributes in all tables to `float`s because it feels weird to go with that type just in cause someone wants to run a division on this field at some point.

My suggestion would be that Metabase casts the affected fields to a float if it's a division (or any computation?). Let me know what you think or if there's an easier way to achieve the same result.

- Your browser and the version: Safari 12.0
- Your operating system: macOS High Sierra 10.13.6
- Your databases: Postgres 10.4
- Metabase version: v0.30.1
- Metabase hosting environment: AWS ECS
- Metabase internal database: Postgres 10.4

### PR DESCRIPTION
**Pull request by sbelak**
Adds explicit cast to `FLOAT` when doing integer division. Without it integer division produces unintuitive results (rounded to the nearest integer).

Fixes #8783

### CODE REVIEW

File: test/metabase/query_processor_test/expressions_test.clj [hunk 1]
```diff
@@ -39,6 +39,20 @@
          :limit       3
          :order-by    [[:asc $id]]}))))
 
+;; Make sure FLOATING POINT division is done when dividing by expressions/fields
+(datasets/expect-with-drivers (qp.test/non-timeseries-drivers-with-feature :expressions)
+  [[0.6]
+   [0.5]
+   [0.5]]
+  (qp.test/format-rows-by [double]
```
Comment (camsaul) [inline test/metabase/query_processor_test/expressions_test.clj]: If you need to round this because some drivers are doing weird stuff you can do `format-rows-by [1.0]` now for example which will round to the nearest `1` decimal place

**Review by camsaul — APPROVED** [review]
This works for me, just make sure it passes with `[ci all]` before merging so we don't end up with broken driver tests

**Comment by mazameli** [comment]
@sbelak What needs to happen to close this out?

**Comment by sbelak** [comment]
Some dbs have a different syntax for casts, so I need to change the code to push this functionality to the driver layer

**Review by camsaul — APPROVED** [review]
Cool WFM

**Comment by vvaezian** [comment]
It seems this merge hasn't fixed the rounding issue when we use the AVG function in simple/custom questions:

avg

**Comment by flamber** [comment]
@vvaezian It does work on AVG, but it depends on how the database handles types too. H2 is really strange with `avg(int_column)`, since it returns an integer. If you have copied the Sample Dataset to MySQL or Postgres, then it returns a float.

**Comment by vvaezian** [comment]
@flamber I see. My actual data is in SQL Server, and it is rounding to int when I use AVG on a column with integer values, which is the behavior of SQL Server.
The workaround in Native queries is to use `AVG(myCol * 1.0)`, but I don't know any workaround for Simple/Custom questions (in Custom questions when I use a custom expression to multiply the column by 1.0, it changes 1.0 to 1 automatically, and therefore the workaround doesn't work.)

**Comment by flamber** [comment]
@vvaezian Hacky hacky hacky - `Average([column] * 1.1 / 1.1)`:
image
