### PR TITLE
Fix custom mapping doesn't work on dashboard

### LINKED ISSUE #29347: Custom mappings are broken
**Describe the bug**
We seem to have broken custom field remappings in 45. They worked in 44.6 but now 46-RC3 does not display the mappings:
Values are there, the filters simply don't show them
image

**Logs**
NA

**To Reproduce**
1) go to settings->data model->orders-> change the data type to category and click on the gear on "quantity" field
2) remap a few quantities to words
3) create a new question with the orders table, add it to a dashboard
4) create a dropdown filter and connect it to quantity field
5) Click on the filter, you won't see the remappings

**Expected behavior**
Remappings should be there

**Screenshots/videos**
Above

**Information about your Metabase Installation:**
- Metabase version: 1.46.0-RC3

**Severity**
P1

**Additional context**
NA

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes #29347, and #29346 by reverting the change I did in https://github.com/metabase/metabase/pull/22836,

Basically, before 43 we have a hydration key `param_values` that is a map of `param-id-> [[label, value]]` which FE used to infer the label of selected value on widget params

This PR brings back that hydration key.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29359)

### CODE REVIEW

**Comment by qnkhuat** [comment]
I'm thinking about not merging it at all since this is adding a bunch of READ db calls to `/api/dashboard/:id` and we recently have a P1 for performance on that API: [issue](https://github.com/metabase/metabase/issues/28956).

I think we could avoid this if we store the default value as a `tuple` of [label, value] so FE doesn't need to get the full mapping from BE on load.

File: src/metabase/models/params.clj [hunk 1]
```diff
@@ -68,6 +69,28 @@
...
+
+(defn- field-ids->param-field-values-ignoring-current-user
+  [param-field-ids]
+  (t2/select-fn->fn :field_id identity ['FieldValues :values :human_readable_values :field_id]
+                    :type :full
+                    :field_id [:in param-field-ids]))
+
+(defn- field-ids->param-field-values
+  "Given a collection of `param-field-ids` return a map of FieldValues for the Fields they reference. This map is
+  returned by various endpoints as `:param_values`."
```
Comment (metamben) [inline src/metabase/models/params.clj:87]: Consider documenting that `nil` is returned if `param-field-ids` is empty.

**Review by metamben — APPROVED** [review]
LGTM

File: src/metabase/models/params.clj (hunk 1 above)
Comment (qnkhuat) [reply src/metabase/models/params.clj]: I documented it in https://github.com/metabase/metabase/pull/29359/commits/46c41746948627cd8e6aab89464f227162332464

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj [hunk 2]
```diff
@@ -76,6 +77,26 @@
...
+  [field-ids]
+  (let [fields                   (when (seq field-ids)
+                                   (hydrate (db/select Field :id [:in (set field-ids)]) :table))
+        {unsandboxed-fields false
+         sandboxed-fields   true} (group-by (comp boolean field-is-sandboxed?) fields)]
+    (merge
+     ;; use the normal OSS batched implementation for any Fields that aren't subject to sandboxing.
+     (when (seq unsandboxed-fields)
+       (params.field-values/default-field-id->field-values-for-current-user
+        (set (map u/the-id unsandboxed-fields))))
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj]: no indeed, removed in https://github.com/metabase/metabase/pull/29359/commits/46c41746948627cd8e6aab89464f227162332464

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj [hunk 3]
```diff
@@ -75,6 +76,26 @@
                                          (mbql.u/match-one v [:dimension [:field field-id _]] field-id))]
                     {k (get login-attributes k)})))])))
 
+(defenterprise field-id->field-values-for-current-user
+  "Fetch *existing* FieldValues for a sequence of `field-ids` for the current User. Values are returned as a map of
+    {field-id FieldValues-instance}
+  Returns `nil` if `field-ids` is empty oo no matching FieldValues exist."
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:82]: `oo` is a typo for `or` presumably

File: src/metabase/models/params.clj [hunk 4]
```diff
@@ -67,6 +68,28 @@
...
     field-id-or-form))
 
+(def ^:dynamic *ignore-current-user-perms-and-return-all-field-values*
+  "Whether to ignore permissions for the current User and return *all* FieldValues for the Fields being parameterized by
+  Cards and Dashboards. This determines how `:param_values` gets hydrated for Card and Dashboard. Normally, this is
+  `false`, but the public and embed versions of the API endpoints can bind this to `true` to bypass normal perms
+  checks (since there is no current User) and get *all* values."
+  false)
+
+(defn- field-ids->param-field-values-ignoring-current-user
```
Comment (dpsutton) [inline src/metabase/models/params.clj:78]: This doesn't create them if they don't exist. There are some functions in `metabase.models.params.field-values` that handle all of the logic. Do we need to bind current-perms to admin level and call those functions here?

**Review by dpsutton — CHANGES_REQUESTED** [review]
The change seems fundamentally correct except that `field-ids->param-field-values-ignoring-current-user` will not create field values if needed. That seems like it should reuse existing functions for this with perms appropriately set.

**Comment by qnkhuat** [comment]
@ranquild could you help me check why the `e2e-tests-dashboard-filters-ee` is failing for embedding? I checked and the API does returns `param_values`, also it works on public dashboard.

**Comment by ranquild** [comment]
@qnkhuat I'll take a look

**Comment by ranquild** [comment]
@qnkhuat I've fixed the tests, everything seems to be working correctly

**Review by ranquild — APPROVED** [review]

**Comment by qnkhuat** [comment]
@dpsutton can you take another look ?
this [commit](https://github.com/metabase/metabase/pull/29359/commits/64c82d15ae7834eb74b439e0ded1be6a99209629) adds the change, and this [one](https://github.com/metabase/metabase/pull/29359/commits/a537e056681885a7de0e052218edef4272cf0ec7) adds a test.

File: enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj [hunk 5]
```diff
@@ -75,6 +76,26 @@
                                          (mbql.u/match-one v [:dimension [:field field-id _]] field-id))]
                     {k (get login-attributes k)})))])))
 
+(defenterprise field-id->field-values-for-current-user
+  "Fetch *existing* FieldValues for a sequence of `field-ids` for the current User. Values are returned as a map of
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj:80]: Can you clarify the expectation here? The docstring stresses this fetches `*existing*` FieldValues. It seems the unsandboxed fields behave this way (`params.field-values/default-field-id->field-values-for-current-user` only selects from the app db), but the sandboxed version calls a `get-or-create` style function which seems to create FieldValues that do not yet exist.

I guess I'm confused why existence is a relevant factor for return value. To me, it seems like the existence of FieldValues is a bit of an implementation detail. My thinking is both sandboxed and not should create field values if they don't exist. Can you explain the thinking behind the divergence here?

File: enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj [hunk 6]
```diff
@@ -14,6 +15,46 @@
    [schema.core :as s]
    [toucan2.core :as t2]))
 
+(deftest params-values-test
```
Comment (dpsutton) [inline enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj:18]: A lot of times these tests can be flaky and really tricky because sometimes the field values already exist and sometimes they don't. I added

```clojure
(t2/delete! 'FieldValues :field_id
            [:in [(mt/id :users :name)
                  (mt/id :categories :name)
                  (mt/id :venues :name)]])
```
Right before the assertion and I got a failure:

```clojure
expected: {46100 {:values ["Garaje" "Gordo Taqueria" "La Tortilla"], :human_readable_values [], :field_id 46100},
           46112 {:values ["African" "American" "Artisan"], :human_readable_values [], :field_id 46112}}
  actual: {46100 {:values ("Garaje" "Gordo Taqueria" "La Tortilla"), :human_readable_values (), :field_id 46100}}
    diff: - {46112 {:values ["African" "American" "Artisan"], :human_readable_values [], :field_id 46112}}
```

Do you know what should happen here if none of these field values exist? 

I'm sorry to harp so much on this but this is a source of really hard to track down bugs. If the answer is "if they exist the user can see them" then that's fine if a bit weird. But at least it is deliberate. And if so we should test them that way.

File: src/metabase/models/params.clj [hunk 7]
```diff
@@ -67,6 +70,38 @@
...
+  (let [fv-return-keys    [:values :human_readable_values :field_id]
+        field-id->fvs     (t2/select-fn->fn :field_id identity (cons FieldValues fv-return-keys)
+                                            :type :full
+                                            :field_id [:in param-field-ids])
+        missing-field-ids (set/difference (set param-field-ids) (set (keys field-id->fvs)))
+        missing-fields    (when (seq missing-field-ids)
+                            (t2/select Field :id [:in missing-field-ids]))]
+    (into field-id->fvs
+          (for [field missing-fields
+                :let [field-values (field-values/get-or-create-full-field-values! field)]]
```
Comment (dpsutton) [inline src/metabase/models/params.clj:93]: Does the `field-values/get-or-create-full-field-values!` function ignore the current user? It seems like it behaves that way but it just hits `qp/process-query` so I'm a bit surprised that it works if we aren't telling it to ignore the current user.

**Review by dpsutton — APPROVED** [review]
I'm approving as I think it's generally ok. I just have concerns that we aren't clear if we care about field values that don't exist yet. Docstrings seem to say we only fetch existing field values but for sandboxed fields we get-or-create.

This will also make tests a little flaky as previous tests might create or remove field values and thereby change what we find. If this is the behavior, I suggest each test ensure that field values are deleted or created as needed so we aren't tracking down flakes and we have deterministic output.

**Comment by qnkhuat** [comment]
oops I forgot that I auto-merged this :( sorry, created this [PR](https://github.com/metabase/metabase/pull/30182) to revert it, then I'll address your comments here.
