### PR TITLE
Show "view-only" badge when the question is not editable

### LINKED ISSUE #15947: Hiding a table makes it impossible to edit existing questions that uses that table
**Describe the bug**
When questions have been built on tables, which are hidden later, then it's either impossible to edit the question or the question will drop all references to the hidden table.

Possible workaround: Change the table name in Admin > Data Model by prepending `~DEPRECATED` or similar, so the table is added to the end of tables.

**To Reproduce**
1. Custom question > Sample Dataset > create a question like this and save as "Q1":
image
2. Admin > Data Model > Sample Dataset > hide Orders table - refresh browser and view "Q1"
It's now not possible to edit the question at all - almost looks like a user without data access
image
3. Admin > Data Model > Sample Dataset > show Orders, but hide Products table - refresh browser and view "Q1"
It's possible to edit the question, but making any changes will drop all references to Products table
image

**Expected behavior**
This issue might not be straight forward, since it should probably allow existing questions to keep working, but should not include all hidden tables in the API response by default, since that could introduce a performance issue on instances, where perhaps 1k tables have been hidden for technical reasons, because it's not possible to limit via the db privileges.
A possible solution would be to introduce a "Deprecated" along with "Technical" and "Cruft", which would then include those tables in the API.

**Information about your Metabase Installation:**
Tested 0.37.8 thru 0.39.1

Related to #6445 and #6298

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/15947

[Testing plan](https://www.notion.so/metabase/Testing-plan-Disallow-editing-queries-with-hidden-tables-12369354c90180f9be40c4bea7fba5ba)

### Description

This PR makes the situation in https://github.com/metabase/metabase/issues/15947 a bit clearer by adding a badge explaining why the question is read-only.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> Orders -> Save
2. Admin Settings -> Table Metadata -> Make Orders hidden
3. Navigate to the question you created before
4. It should not be editable and it should show a `view-only` badge
5. Hover the badge and verify the copy in the popover makes sense

### Demo

Screenshot 2024-10-16 at 14 51 32

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+  const query = question.query();
+  const { isEditable, isNative } = Lib.queryDisplayInfo(query);
+
+  const canHaveHiddenSourceTables = !isEditable && !isNative;
+
+  const { data } = useGetCardQueryMetadataQuery(question.id(), {
+    skip: !canHaveHiddenSourceTables,
+  });
+
+  if (!canHaveHiddenSourceTables) {
```
Comment (uladzimirdev) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts:16]:
```suggestion
  if (!canHaveHiddenSourceTables || !data) {
```

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/SavedQuestionLeftSide.module.css [hunk 2]
```diff
@@ -0,0 +1,5 @@
+.badge {
+  background: var(--mb-color-bg-medium);
+  border-radius: 4px;
```
Comment (uladzimirdev) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/SavedQuestionLeftSide.module.css:3]: rem?

File: e2e/test/scenarios/question/saved.cy.spec.js [hunk 3]
```diff
@@ -317,6 +323,68 @@ describe("scenarios > question > saved", () => {
...
+        .realHover();
+      popover()
+        .findByText(
+          "One of the administrators hid the source table “Orders”, making this question view-only.",
+        )
+        .should("be.visible");
+    });
+
+    it("should show a View-only tag when a joined table is hidden", () => {
+      cy.signInAsAdmin();
```
Comment (uladzimirdev) [inline e2e/test/scenarios/question/saved.cy.spec.js:352]: nit: move to beforeEach

**Review by uladzimirdev — APPROVED** [review]
LGTM, minor comments

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts [hunk 4]
```diff
@@ -0,0 +1,21 @@
+import { useGetCardQueryMetadataQuery } from "metabase/api";
+import * as Lib from "metabase-lib";
+import type Question from "metabase-lib/v1/Question";
+import type { Table } from "metabase-types/api";
+
+export function useHiddenSourceTables(question: Question): Table[] {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts:6]: Usually people use either `hooks.ts` or just call it by the hook name, e.g. `use-hidden-source-tables.ts`. `utils` are for regular functions only.

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+
+  const { data } = useGetCardQueryMetadataQuery(question.id(), {
+    skip: !canHaveHiddenSourceTables,
+  });
+
+  if (!canHaveHiddenSourceTables) {
+    return [];
+  }
+
+  return data?.tables.filter(table => table.visibility_type === "hidden") ?? [];
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts:20]: This is incorrect - you need to check that `visibility_type != null`. There are visibility types which are all considered hidden. You can view them in Table metadata. Please make sure this is tested.

Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts:20]: I believe that this approach - where you check each table in card query metadata - might not work because extra tables can be returned. For instance, an implicitly joinable table can be hidden but it is not used in the query and thus it would be incorrect to use it here.

E.g. a possible bug:
- data source is a inaccessible card
- there are accessible (and visible) joined tables
- there are hidden implicitly joined tables

The query is readonly because the source card is unavailable but this logic would show the name of the first implicitly joinable table.

Comment (ranquild) [reply frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts:20]: Unsure if that's a correct approach but what you could do:

First of all, you need to know that `getMetadata` selector removes hidden tables by default so you won't get them with MBQL lib. You could re-construct the `query` object with unfiltered metadata:
```
const datasetQuery = question.datasetQuery();
const metadata = useSelector(getMetadataUnfiltered);
const metadataProvider = Lib.metadataProvider(datasetQuery.database, metadata);
const query = Lib.fromLegacyQuery(datasetQuery.database, metadataProvider, datasetQuery);

const sourceTableId = Lib.sourceTableOrCardId(query);
const sourceTable = Lib.tableOrCardMetadata(sourceTableId);
const sourceTableInfo = sourceTable ? Lib.displayInfo(query, -1, sourceTable) : undefined;
const joinTablesInfo = Lib.stageIndexes(query).flatMap(stageIndex => 
  Lib.joins(query, stageIndex)
       .map(join => Lib.joinedThing(query, join))
       .filter(joinTable => joinTable != null)
       .map(joinTable => Lib.displayInfo(query, stageIndex, joinTable));

const tablesInfo = [
   ...(sourceTableInfo ? [sourceTableInfo] : []),
   ...joinTablesInfo
];
return tablesInfo.first(tableInfo => tableInfo.isHidden);
```

^ This assumes that:
- There is a new property in `TableDisplayInfo` in MBQL lib. You could add one in clojure based on `visibility-type` of the table.
- There is no need to add an API call

**Review by ranquild — CHANGES_REQUESTED** [review]
See inline comments

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts (hunk 5 above)
Comment (ranquild) [reply frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts:20]: Also - let's not merge non-trivial changes to master without a testing plan.

Comment (romeovs) [reply frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/util.ts]: I've implemented this suggestion and it works!

Not sure I would've ever been able to come up with that code snippet myself (let alone believe that it would work)...

I've added the extra cases to the [testing plan](https://www.notion.so/metabase/Testing-plan-Disallow-editing-queries-with-hidden-tables-12369354c90180f9be40c4bea7fba5ba) and wrote the tests too.
Am I missing any test cases?

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/ViewOnly.unit.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,281 @@
...
+async function expectPopoverToHaveText(text: string) {
+  userEvent.hover(screen.getByText("View-only"));
+  const dialog = await screen.findByRole("dialog");
+  expect(dialog).toBeInTheDocument();
+  expect(dialog).toHaveTextContent(text);
+}
+
+const HIDDEN_VISIBILITY_TYPES = ["hidden", "technical", "cruft"] as const;
+
+const ORDERS_QUESTION: Partial<Card> = {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/ViewOnly.unit.spec.tsx:80]: Please use MBQL lib and not raw MBQL

**Review by ranquild — APPROVED** [review]
It would be great to use MBQL lib in tests and not raw MBQL. Take a look at this example https://github.com/metabase/metabase/blob/8486a9f9c85b4820c99249468286ead200a79c9c/frontend/src/metabase/querying/filters/hooks/use-filter-modal/utils/filters.unit.spec.ts#L9

File: frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/SavedQuestionLeftSide.tsx [hunk 7]
```diff
@@ -111,3 +121,33 @@ export function SavedQuestionLeftSide({
...
+    <HoverCard position="bottom-start" disabled={!tableName}>
+      <HoverCard.Target>
+        <Flex align="center" gap="xs" px={4} py={2} mt={4} className={CS.badge}>
+          <Icon name="lock_filled" size={12} />
+          <Text size="xs" fw="bold">
+            {t`View-only`}
+          </Text>
+        </Flex>
+      </HoverCard.Target>
+      <HoverCard.Dropdown>
```
[the remark this answers is not in the document]
Comment (romeovs) [reply frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/SavedQuestionLeftSide.tsx]: Yes that what's this PR already does!
