### PR TITLE
Fix recents in the entity picker for tables in joins

### LINKED ISSUE #52523: Join data picker does not show recent tables
### Describe the bug

https://github.com/user-attachments/assets/0cab745c-338b-4db4-ab14-d835f67a2a67

### To Reproduce

Scenario: you want to create a question "Orders join Products"

1. Make sure you have Orders and Products tables in Recents
2. New > Question
3. Notice that you can see Orders and Products tables in Recents
4. Choose Orders
5. Click "Join data"
6. Entity picker is shown

❌ Products table is not shown in Recents

### Information about your Metabase installation

master, 9290125217ab473835298e58d3b7e6a3b73cbde0

### Severity

P2, annoying

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/52523

How to verify:
- New -> Question
- See that in the entity picker there are recent items
- Pick any table
- Click on join
- Verify that there are tables in the join entity picker as well

### CODE REVIEW

File: frontend/src/metabase/common/components/DataPicker/utils.ts [hunk 1]
```diff
@@ -212,3 +213,11 @@ export const createQuestionPickerItemSelectHandler = (
     onItemSelect(item);
   };
 };
+
+export function getRecentItemDatabaseId(item: RecentItem) {
+  if (item.model === "table") {
+    return item.database.id;
```
Comment (uladzimirdev) [inline frontend/src/metabase/common/components/DataPicker/utils.ts:219]: 🤯

**Review by uladzimirdev — APPROVED** [review]
