### PR TITLE
Remove `driver/set-use-database` in favour of setting the DB in the jdbc spec

### LINKED ISSUE #63040: Unnecessary USE DATABASE in Snowflake before every question with routing turned off
### Describe the bug

Since v56 we run `USE DATABASE` before each question, this is even if there's no DB routing and even if the instance is Open Source (which doesn't even support routing).
This extra overhead can become ~40ms before every question. A customer reports this ran 120k USE DATABASE in a day. Customer reports a big increase in their billing since v56, and they suspect it is related to this:

> Compute cost: The additional executions contribute ~15.5 hours/month of extra compute time. On their own, these are relatively minor.
> Cloud services cost: This is where the bigger impact is. Since the v0.56 upgrade, our cloud services charges have roughly doubled. The excess 120K+ operations per day are driving higher warehouse utilization and more frequent auto-scaling, which directly feeds into this increase.

### To Reproduce

1. Run any question in Snowflake like a SQL question with `SELECT 1`
2. Open the Snowlfake query history, USE DATABASE is run before it even without enabling Routing

### Expected behavior

It should not do USE DATABASE if routing is not enabled or if it's the OSS edition

### Logs

_No response_

### Information about your Metabase installation

```JSON
v56.3.6
```

### Severity

P2

### Additional context

It could be suspected that since [this PR](https://github.com/metabase/metabase/pull/61563/files) (always runs `driver/set-database-used!`) + [this PR](https://github.com/metabase/metabase/pull/61434) (implements it for Snowflake), USE DATABASE is sent every time before running a question.

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/63040
Closes https://github.com/metabase/metabase/issues/62998

### Description

Running USE DATABASE frequently increased Snowflake costs for customers. Instead of doing that we'll set the default database in the JDBC spec. This was done in https://github.com/metabase/metabase/issues/27856 but only if an advanced option was selected. I believe this can be done all the time and doesn't require the advanced option. 

### How to verify

1. Snowflake queries should work and not have the DB name in identifiers.
2. You should be able to query other DBs in native queries by including the DB name in identifiers.
3. DB routing and impersonation should still work

### Demo

https://www.loom.com/share/c230f798a9994003925c7f5b10ddf743

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/database_routing/core.clj [hunk 1]
```diff
@@ -41,3 +41,9 @@
   metabase-enterprise.database-routing.model
   [_db-id]
   nil)
+
+(defenterprise db-routing-enabled?
+  "OSS version, does nothing"
+  metabase-enterprise.database-routing.common
+  [_db-or-id]
+  nil)
```
Comment (dpsutton) [inline src/metabase/database_routing/core.clj]: return false here for predicates with a `?`

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 2]
```diff
@@ -869,9 +871,10 @@
            (.next rs)))))))
 
 (defmethod driver/set-database-used! :snowflake [_driver conn db]
-  (let [sql (format "USE DATABASE \"%s\"" (db-name db))]
-    (with-open [stmt (.createStatement ^java.sql.Connection conn)]
-      (.execute stmt sql))))
+  (when (driver-api/db-routing-enabled? db)
```
Comment (dpsutton) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj]: should the check go here or in the set-default-connection-options call?

```
(driver/set-database-used! driver conn db)
``` 

vs

```
    (when (driver-api/db-routing-enabled?)
      (driver/set-database-used! driver conn db))
```

but this still does this for each connection on a database where db routing is enbaled, even if the current query does not need it. in particular all metadata queries will use this.

Comment (rileythomp) [reply modules/drivers/snowflake/src/metabase/driver/snowflake.clj]: I think we might be able to avoid metadata queries doing USE DATABASE by checking `*database-routing-on*`

**Review by metamben — APPROVED** [review]
LGTM
