### PR TITLE
Fix automagic dashboards for queries with source queries

### LINKED ISSUE #15655: X-rays from a nested question fails
**Describe the bug**
Doing automatic explorations ("X-ray" or "Compare to the rest") from a nested question errors with "Something's gone wrong" or in some cases shows a completely blank screen (depending on version).

**To Reproduce**
1. Native query > Sample Dataset > `select * from people` - save as "Q1" (note: using a QB question here instead of SQL will make the "X-ray" in step 3/4 work)
2. Simple question > Saved Questions > "Q1" and Summarize by Count grouped by SOURCE
3. Click the the first result and select "X-ray" or "Compare to the rest"
image
4. It starts loading automatic exploration and then shows "Something's gone wrong".
   a. For "X-ray", it generates a lot of browser console errors, and seems like a frontend problem only.
   b. For "Compare to the rest" it shows `For input string: "card__123"` and there's a stacktrace.

<details><summary>Full stacktrace</summary>

```
2021-04-16 17:39:40,463 ERROR middleware.log :: GET /api/automagic-dashboards/adhoc/eyJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOiJjYXJkX181MyIsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiwiU09VUkNFIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XV19LCJkYXRhYmFzZSI6NH0=/cell/WyI9IixbImZpZWxkIiw5NSxudWxsXSwiQWZmaWxpYXRlIl0=/compare/table/card__53 500 4.3 ms (4 DB calls) 
{:via
 [{:type java.lang.NumberFormatException,
   :message "For input string: \"card__53\"",
   :at [java.lang.NumberFormatException forInputString "NumberFormatException.java" 65]}],
 :trace
 [[java.lang.NumberFormatException forInputString "NumberFormatException.java" 65]
  [java.lang.Integer parseInt "Integer.java" 652]
  [java.lang.Integer parseInt "Integer.java" 770]
  [metabase.api.automagic_dashboards$ensure_int invokeStatic "automagic_dashboards.clj" 75]
  [metabase.api.automagic_dashboards$ensure_int invoke "automagic_dashboards.clj" 72]
  [clojure.core$comp$fn__5807 invoke "core.clj" 2569]
  [metabase.api.automagic_dashboards$fn__54849 invokeStatic "automagic_dashboards.clj" 190]
  [metabase.api.automagic_dashboards$fn__54849 invoke "automagic_dashboards.clj" 180]
  [compojure.core$wrap_response$fn__1996 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1980 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1985 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 151]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__75562 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 297]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.api.routes$fn__75684$fn__75686 invoke "routes.clj" 70]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.server.routes$fn__77955$fn__77956 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2036 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2038 invoke "core.clj" 296]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 152]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 152]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1989 invoke "core.clj" 152]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010 invoke "core.clj" 197]
  [metabase.server.routes$fn__77943$fn__77945 invoke "routes.clj" 41]
  [compojure.core$routes$fn__2008$f__2009 invoke "core.clj" 198]
  [compojure.core$routes$fn__2008 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75675 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__75672 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__77871$fn__77872 invoke "log.clj" 195]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__77871 invoke "log.clj" 189]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__77507 invoke "browser_cookie.clj" 30]
  [metabase.server.middleware.security$add_security_headers$fn__75637 invoke "security.clj" 142]
  [metabase.server.middleware.json$wrap_json_body$fn__77652 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__77670 invoke "json.clj" 98]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__78212 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__78228 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__35489 invoke "misc.clj" 58]
  [metabase.server.middleware.session$bind_current_user$fn__42461$fn__42462 invoke "session.clj" 248]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 229]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 221]
  [metabase.server.middleware.session$bind_current_user$fn__42461 invoke "session.clj" 247]
  [metabase.server.middleware.session$wrap_current_user_info$fn__42448 invoke "session.clj" 207]
  [metabase.server.middleware.session$wrap_session_id$fn__42434 invoke "session.clj" 153]
  [metabase.server.middleware.auth$wrap_api_key$fn__75570 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__78132 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__35472 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__35497 invoke "misc.clj" 75]
  [ring.middleware.gzip$wrap_gzip$fn__78174 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__35500 invoke "misc.clj" 92]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__77888 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__77451 invoke "server.clj" 71]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 556]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 905]
  [java.lang.Thread run "Thread.java" 834]],
 :cause "For input string: \"card__53\"",
 :message "For input string: \"card__53\""}
```

</details>

**Information about your Metabase Installation:**
Tested 0.36.8 thru 0.39.0-rc2

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #15655

Automagic dashboards did not work if you tried to hit the endpoint like

```
/api/automagic-dashboards/adhoc/<query>/cell/<cell-query>/compare/table/card__10
```

Now It does seem like you should probably have just called 

```
/api/automagic-dashboards/adhoc/<query>/cell/<cell-query>/compare/question/10
```

instead but it was easy enough for me to detect this case and fix it on our end.

Once I fixed that I ran into a bunch of other bugs that had to be fixed (I will explain in the comments)

### CODE REVIEW

File: src/metabase/automagic_dashboards/core.clj [hunk 1]
```diff
@@ -1014,11 +1023,12 @@
...
-  ^{:doc "Create a transient dashboard analyzing given entity."
-    :arglists '([entity opts])}
-  automagic-analysis (fn [entity _]
-                       (type entity)))
+
+(defmulti automagic-analysis
+  "Create a transient dashboard analyzing given entity."
+  {:arglists '([entity opts])}
+  (fn [entity _]
+    (type entity)))
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/core.clj:1031]: Minor unrelated code cleanup

File: src/metabase/api/automagic_dashboards.clj [hunk 2]
```diff
@@ -75,23 +76,50 @@
...
+  (api/read-check (Metric (ensure-int metric-id-str))))
+
+(defmethod ->entity :field
+  [_entity-type field-id-str]
+  (api/read-check (Field (ensure-int field-id-str))))
+
+(defmethod ->entity :transform
+  [_entity-type transform-name]
+  (api/read-check (Collection (tf.materialize/get-collection transform-name)))
+  transform-name)
```
Comment (camsaul) [inline src/metabase/api/automagic_dashboards.clj:118]: I changed `->entity` from a function map to a multimethod. This is a little bit more code but it's easier to read if you ask me and definitely way easier to debug. Before this change I was seeing errors in `ensure-int` with no idea where they were coming from since the `->entity` functions in the stacktrace anywhere.

The one change I did make here was to have `->entity :table` detect `card__<id>` strings and hand off to the `:question` method in that case -- this was much cleaner to implement with these as multimethods instead of a map of functions

File: src/metabase/api/automagic_dashboards.clj [hunk 3]
```diff
@@ -115,8 +144,9 @@
    show   Show
    prefix Prefix
    rule   Rule}
-  (-> entity-id-or-query ((->entity entity)) (automagic-analysis {:show (keyword show)
-                                                                  :rule ["table" prefix rule]})))
+  (-> (->entity entity entity-id-or-query)
+      (automagic-analysis {:show (keyword show)
+                           :rule ["table" prefix rule]})))
```
Comment (camsaul) [inline src/metabase/api/automagic_dashboards.clj:149]: As a result of the multimethod change above I think the rest of the code here reads a lot cleaner.

File: src/metabase/automagic_dashboards/core.clj [hunk 4]
```diff
@@ -44,23 +44,32 @@
...
+                                      result-metadata)]
+         (-> field
+             (update :base_type keyword)
+             (update :semantic_type keyword)
+             field/map->FieldInstance
+             (classify/run-classifiers {}))))
+     ;; otherwise this isn't returning something, and that's probably an error. Log it.
+     (log/warn (str (trs "Cannot resolve Field {0} in automagic analysis context" field-id-or-name-or-clause)
+                    \newline
+                    (u/pprint-to-str root))))))
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/core.clj:72]: One major bug I was running into was that `->field` would return `nil` in some cases -- I'm not really 100% sure what the original intention was here but I tried to comment it a bit and log a warning if this is returning `nil`

File: src/metabase/automagic_dashboards/core.clj [hunk 5]
```diff
@@ -44,23 +44,32 @@
...
-            field/map->FieldInstance
-            (classify/run-classifiers {}))))))
+  [{{result-metadata :result_metadata} :source, :as root}
+   field-id-or-name-or-clause :- (s/cond-pre su/IntGreaterThanZero su/NonBlankString mbql.s/Field)]
+  (let [id-or-name (if (sequential? field-id-or-name-or-clause)
+                     (filters/field-reference->id field-id-or-name-or-clause)
+                     field-id-or-name-or-clause)]
+    (or
+     ;; Handle integer Field IDs.
+     (when (integer? id-or-name)
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/core.clj:56]: I have no idea why there was a restriction that we couldn't resolve integer Field IDs unless the source type was Table. Since we didn't actually check that `id-or-name` was an integer anywhere I'm guess that was a roundabout way of doing that -- otherwise `(Field id-or-name)` would fail if `id-or-name` was a string.

I replaced 

```clj
(->> root :source (instance? (type Table)))
```

with

```clj
(integer? id-or-name)
```

which seems to make the X-Ray code fail a lot less often and seems to make sense to me.

File: src/metabase/automagic_dashboards/core.clj [hunk 6]
```diff
@@ -1032,7 +1042,7 @@
   [metric opts]
   (automagic-dashboard (merge (->root metric) opts)))
 
-(defn- collect-metrics
+(s/defn ^:private collect-metrics :- (s/maybe [(type Metric)])
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/core.clj:1045]: It seems like the calling code expects this to return a sequence of Metrics. So this is to catch bugs sooner and document that fact.

File: src/metabase/automagic_dashboards/core.clj [hunk 7]
```diff
@@ -1047,21 +1057,30 @@
                                           :table_id   table-id}))))
        (get-in question [:dataset_query :query :aggregation])))
 
-(defn- collect-breakout-fields
+(s/defn ^:private collect-breakout-fields :- (s/maybe [(type Field)])
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/core.clj:1060]: The calling code definitely expects this to return a sequence of Fields. Because of bugs this would sometimes return `[nil]`. So the schema check here catches those bugs sooner

File: src/metabase/automagic_dashboards/core.clj [hunk 8]
```diff
@@ -1047,21 +1057,30 @@
...
   [root question]
-  (map (comp (partial ->field root)
-             first
-             filters/collect-field-references)
-       (get-in question [:dataset_query :query :breakout])))
+  (for [breakout     (get-in question [:dataset_query :query :breakout])
+        field-clause (take 1 (filters/collect-field-references breakout))
+        :let         [field (->field root field-clause)]
+        :when        field]
+    field))
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/core.clj:1066]: Fixed the bug causing this to return `[nil]` if `->field` returned `nil`. Rewrote as a list comprehension since it's a lot easier to read.

File: src/metabase/automagic_dashboards/core.clj [hunk 9]
```diff
@@ -1047,21 +1057,30 @@
...
+                                           :query-filter (:query-filter root)
+                                           :database     (:database root)))
+              (catch Throwable e
+                (throw (ex-info (tru "Error decomposing question: {0}" (ex-message e))
+                                {:root root, :question question, :object x}
+                                e)))))]
+    (into []
+          (comp cat (map analyze))
+          [(collect-metrics root question)
+           (collect-breakout-fields root question)])))
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/core.clj:1083]: Rewrote this a bit to make it easier to read and add a try-catch that rethrows with extra info if it fails to make debugging easier.

File: src/metabase/automagic_dashboards/filters.clj [hunk 10]
```diff
@@ -137,10 +137,11 @@
...
   ([dashboard dimensions max-filters]
-   (let [fks (->> (db/select Field
-                    :fk_target_field_id [:not= nil]
-                    :table_id [:in (keep (comp :table_id :card) (:ordered_cards dashboard))])
-                  field/with-targets)]
+   (let [fks (when-let [table-ids (not-empty (set (keep (comp :table_id :card)
+                                                        (:ordered_cards dashboard))))]
+               (->> (db/select Field :fk_target_field_id [:not= nil]
+                               :table_id [:in table-ids])
+                    field/with-targets))]
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/filters.clj:144]: This was broken if `table-ids` was an empty sequence -- `table_id IN ()` is not valid SQL. Fixed by not running the query at all in this case

File: src/metabase/sync/analyze/classifiers/name.clj [hunk 11]
```diff
@@ -143,9 +143,10 @@
                 (str/blank? (:name field-or-column)))
     (semantic-type-for-name-and-base-type (:name field-or-column) (:base_type field-or-column))))
 
-(s/defn infer-and-assoc-semantic-type  :- (s/maybe FieldOrColumn)
+(s/defn infer-and-assoc-semantic-type :- (s/maybe FieldOrColumn)
```
Comment (camsaul) [inline src/metabase/sync/analyze/classifiers/name.clj:146]: Formatting fixes

File: test/metabase/api/automagic_dashboards_test.clj [hunk 12]
```diff
@@ -117,13 +117,12 @@
...
 
-
 ;;; ------------------- Comparisons -------------------
 
 (def ^:private segment
   (delay
-   {:table_id   (mt/id :venues)
-    :definition {:filter [:> [:field-id (mt/id :venues :price)] 10]}}))
+    {:table_id   (mt/id :venues)
+     :definition {:filter [:> [:field-id (mt/id :venues :price)] 10]}}))
```
Comment (camsaul) [inline test/metabase/api/automagic_dashboards_test.clj:125]: indentation fix

**Comment by camsaul** [comment]
I actually had to fix 3 or 4 separate things that were broken here to get this to work. This might have inadvertently fixed some other X-Ray bugs too

File: src/metabase/automagic_dashboards/core.clj (hunk 4 above)
Comment (howonlee) [reply src/metabase/automagic_dashboards/core.clj:72]: I think this was an interaction with the big ol' field array change in MBQL that got in months ago, which never was reconcilliated with this xray codebase

File: src/metabase/automagic_dashboards/core.clj [hunk 13]
```diff
@@ -44,23 +44,32 @@
...
+  [{{result-metadata :result_metadata} :source, :as root}
+   field-id-or-name-or-clause :- (s/cond-pre su/IntGreaterThanZero su/NonBlankString mbql.s/Field)]
+  (let [id-or-name (if (sequential? field-id-or-name-or-clause)
+                     (filters/field-reference->id field-id-or-name-or-clause)
+                     field-id-or-name-or-clause)]
+    (or
+     ;; Handle integer Field IDs.
+     (when (integer? id-or-name)
+       (Field id-or-name))
+     ;; handle field string names. Only if we have result metadata. (Not sure why)
```
Comment (howonlee) [inline src/metabase/automagic_dashboards/core.clj:58]: I think the reason was underlying assumption that field string names are associated with the root entities that have results_metadata, sorta a duck type check

**Review by howonlee — APPROVED** [review]
Speculations made as to what's going on

**Review by flamber — APPROVED** [review]
