### PR TITLE
Treat empty strings as ObjectId value equivalent to nil

### LINKED ISSUE #15801: Cannot filter ObjectId column by "Is (not) empty" unless Field Type is "Entity Key"
**Describe the bug**
Cannot filter MongoDB ObjectId column by "Is empty" or "Not empty" unless Field Type is "Entity Key".

**Workaround**: Since 0.39.0 it is now possible to create a Custom Expression with the function `isnull([column_name])`

**To Reproduce**
1. Admin > Data Model > MongoDB Sample > Orders > change the Field Type of the `_id` column () to "No semantic type"
2. Simple question > Mongo Sample > Orders > filter the `_id` column with "Is empty" or "Not empty" - query fails with error `invalid hexadecimal representation of an ObjectId: []` because it tries to filter by both null and string="", but the string comparison is not allowed.

<details><summary>Full stacktrace</summary>

```
2021-04-24 10:55:36,308 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 36,
 :started_at #t "2021-04-24T10:55:35.888808+02:00[Europe/Copenhagen]",
 :json_query
 {:type "query",
  :query {:source-table 1376, :filter ["is-empty" ["field" 20263 nil]]},
  :database 36,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class java.lang.IllegalArgumentException,
 :stacktrace
 ["org.bson.types.ObjectId.parseHexString(ObjectId.java:550)"
  "org.bson.types.ObjectId.<init>(ObjectId.java:239)"
  "--> driver.mongo.query_processor$eval858$fn__860.invoke(query_processor.clj:230)"
  "driver.mongo.query_processor$filter_expr.invokeStatic(query_processor.clj:327)"
  "driver.mongo.query_processor$filter_expr.invoke(query_processor.clj:325)"
  "driver.mongo.query_processor$eval944$fn__946.invoke(query_processor.clj:340)"
  "driver.mongo.query_processor$eval1000$fn__1002.invoke(query_processor.clj:355)"
  "driver.mongo.query_processor$handle_filter.invokeStatic(query_processor.clj:379)"
  "driver.mongo.query_processor$handle_filter.invoke(query_processor.clj:376)"
  "driver.mongo.query_processor$eval1447$generate_aggregation_pipeline__1452$fn__1453$fn__1454.invoke(query_processor.clj:643)"
  "driver.mongo.query_processor$eval1447$generate_aggregation_pipeline__1452$fn__1453.invoke(query_processor.clj:642)"
  "driver.mongo.query_processor$eval1447$generate_aggregation_pipeline__1452.invoke(query_processor.clj:639)"
  "driver.mongo.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:674)"
  "driver.mongo.query_processor$mbql__GT_native.invoke(query_processor.clj:667)"
  "driver.mongo$eval2738$fn__2739.invoke(mongo.clj:220)"
  "query_processor.middleware.mbql_to_native$query__GT_native_form.invokeStatic(mbql_to_native.clj:14)"
  "query_processor.middleware.mbql_to_native$query__GT_native_form.invoke(mbql_to_native.clj:9)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47220.invoke(mbql_to_native.clj:22)"
  "query_processor.middleware.check_features$check_features$fn__46462.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__47206.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__45914.invoke(cache.clj:211)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47466.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49396.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45033.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41378.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__41253.invoke(annotate.clj:598)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46334.invoke(permissions.clj:81)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48324.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46535.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48623.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__48936.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44609.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47170.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__47151.invoke(format_rows.clj:74)"
  "query_processor.middleware.desugar$desugar$fn__46601.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45420.invoke(binning.clj:227)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46137.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__44258.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44487.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49345.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44772.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48498.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44980.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46184.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48306.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46236.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__46857.invoke(expand_macros.clj:155)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44781.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49298.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48509$fn__48513.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48509.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47097.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__49307$fn__49308.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__49307.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__49352.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47233.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44627.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49283.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46478.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48395.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46418.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___37956$thunk__37957.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___37956.invoke(reducible.clj:109)"
  "query_processor.reducible$sync_qp$qp_STAR___37965$fn__37968.invoke(reducible.clj:135)"
  "query_processor.reducible$sync_qp$qp_STAR___37965.invoke(reducible.clj:134)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:239)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:235)"
  "query_processor$fn__49442$process_query_and_save_execution_BANG___49451$fn__49454.invoke(query_processor.clj:251)"
  "query_processor$fn__49442$process_query_and_save_execution_BANG___49451.invoke(query_processor.clj:243)"
  "query_processor$fn__49486$process_query_and_save_with_max_results_constraints_BANG___49495$fn__49498.invoke(query_processor.clj:263)"
  "query_processor$fn__49486$process_query_and_save_with_max_results_constraints_BANG___49495.invoke(query_processor.clj:256)"
  "api.dataset$run_query_async$fn__55699.invoke(dataset.clj:56)"
  "query_processor.streaming$streaming_response_STAR_$fn__55678$fn__55679.invoke(streaming.clj:72)"
  "query_processor.streaming$streaming_response_STAR_$fn__55678.invoke(streaming.clj:71)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
  "async.streaming_response$do_f_async$fn__16071.invoke(streaming_response.clj:84)"],
 :context :ad-hoc,
 :error "invalid hexadecimal representation of an ObjectId: []",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-table 1376,
   :filter
   [:or
    [:=
     [:field 20263 nil]
     [:value
      nil
      {:base_type :type/MongoBSONID,
       :effective_type :type/MongoBSONID,
       :coercion_strategy nil,
       :semantic_type nil,
       :database_type "org.bson.types.ObjectId",
       :name "_id"}]]
    [:=
     [:field 20263 nil]
     [:value
      ""
      {:base_type :type/MongoBSONID,
       :effective_type :type/MongoBSONID,
       :coercion_strategy nil,
       :semantic_type nil,
       :database_type "org.bson.types.ObjectId",
       :name "_id"}]]],
   :fields
   [[:field 20263 nil]
    [:field 20269 nil]
    [:field 20267 nil]
    [:field 20264 nil]
    [:field 20268 nil]
    [:field 20261 nil]
    [:field 20266 nil]
    [:field 20260 nil]
    [:field 20265 nil]
    [:field 20262 {:temporal-unit :default}]],
   :limit 2000},
  :database 36,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash
   [-125, -26, -60, 22, -23, -32, -106, -110, 78, 16, -96, -65, -40, 7, 4, 72, -125, -88, -84, -68, 106, 43, 70, 82,
    -79, -12, 27, -26, -30, -35, 12, 8]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

2021-04-24 10:55:36,317 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 432.4 ms (19 DB calls) App DB connections: 0/13 Jetty threads: 3/50 (4 idle, 0 queued) (62 total active threads) Queries in flight: 0 (0 queued)
```

</details>

**Information about your Metabase Installation:**
Tested 0.36.8 thru 0.39.0.1

For history #11134

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by metamben**
Fixes #15801.

### CODE REVIEW

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 1]
```diff
@@ -245,9 +245,10 @@
   [[_ value {base-type :base_type}]]
   (if (and (isa? base-type :type/MongoBSONID)
            (some? value))
-    ;; Passing a nil to the ObjectId constructor throws an exception
+    ;; Passing nil or "" to the ObjectId constructor throws an exception
     ;; "invalid hexadecimal representation of an ObjectId: []" so, just treat it as nil
-    (ObjectId. (str value))
+    (when (not= value "")
```
Comment (dpsutton) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:250]: This kinda confuses me as to what types of values flow through. We check for empty string and then call `str` on the value. I'm surprised that seemingly more than just strings are flowing through this. What values come through this path?

Comment (metamben) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:250]: I suppose constants provided by the user and values provided by the query processor. From the latter group I only know about `""` used when checking emptiness.

Comment (dpsutton) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:250]: I'm still not following. We're checking `value` against the empty string and then calling `str` on it. What types flow through here (or do we know?). Obviously strings can come through if we check against the empty string. Do integers come through? Maps, vectors, etc.

**Review by dpsutton — APPROVED** [review]
