### PR TITLE
[Fixes #11879] [Fixes #8410] Don't wrap email attachment filenames

### LINKED ISSUE #8410: pulse attachment file(question name) Korean support problem
I'm using metabase version: v0.30.1 on docker.
My problem is metabase pulse attachment files never shown my email.

I found out the cause.
file never shown problem happend when I create question in "Korean".
But I created question name to English. It works well.

I want to crete question to my own langauge. I need help.

### LINKED ISSUE #11879: Pulse attachment file sent without file extension
**Describe the bug**
When using Pulse feature and define email sent as XLS or CSV,  the file generated with incorrect extension and the file name is too long.

**Logs**

Sample filename generated: _=_UTF-8_B_16DXmdeq15XXp9eZINeS15HXmdeZ15Qg16bXpNeV15nXmdedLn___ ___filename_1=__hsc3g=_=_

**To Reproduce**
1. Create pulse.
2. Select sample question.
3. Choose the attachment option.
4. Mail will be sent with incorrect file name and without file extension.

**Expected behavior**
File name should be sent with the pulse name (escaping special characters) and perhaps some datetime format (_YYYYmmdd) suffix. The extension should xls or csv depend on what the user selected.

**Screenshots**
image

**Information about your Metabase Installation:**
0.34.2

**Severity**
Medium as the file cannot be opened with various mail clients.

### PR DESCRIPTION
**Pull request by tsmacdonald**
* Non-ASCII characters in filenames are encoded [as per IETF RFC  2047](https://tools.ietf.org/html/rfc2047) (c.f. #8410)
* Sufficiently-long _encoded_ filenames are sent over multiple lines as per [RFC 2184 section 3](https://tools.ietf.org/html/rfc2184#section-3), for example:

    ```
    Content-Disposition: attachment;
      filename*0="=?UTF-8?Q?T=C3=A9=C5=BFting_non-ASCII_=C4=8D=C4=A5=C3=A4ract";
      filename*1="ers.xlsx?="
    ```
* Many mail clients do the right thing, but Gmail does not.

This commit therefore turns off wrapping, as per [Bill Shannon's Stack Overflow answer re. an undocumented system
property](https://stackoverflow.com/a/53344141/220529) (Bill Shannon co-wrote the Java email library, which is used by postal
(the Clojure wrapper we use)).

This is another case where the testing is awkward, and the real test is how email clients parse the dang thing anyway.

Fixes #11879 
Fixes #8410

### CODE REVIEW

**Comment by tsmacdonald** [comment]
Two problems:

1) This only works for local dev, not in deployed environments
2) I do think I can test the filename wrangling

**Review by robdaemon — CHANGES_REQUESTED** [review]
So we can do this in the `email.clj` file, around line 95, in `send-message-or-throw!` via `(System/setProperty "mail.mime.splitlongparameters" "false")` as opposed to the `project.clj` change

**Comment by tsmacdonald** [comment]
@robdaemon Got it fixed up. Lost a ton of time figuring out the test. I'm still not thrilled with it…lots of moving parts, and it's disappointing to have to deal with `with-redefs` and mucking around with `postal` and whatnot. I couldn't think of a better solution, though, and it does test what I think it does (I made sure it failed). And it should make future email tests easier to deal with.

But, of course, I'm very open to hearing about better approaches.

**Comment by tsmacdonald** [comment]
Only build failure is a FE problem unrelated to this PR

File: src/metabase/email.clj [hunk 1]
```diff
@@ -41,10 +41,13 @@
 
 ;; ## PUBLIC INTERFACE
 
-(def ^{:arglists '([smtp-credentials email-details]), :style/indent 1} send-email!
+(defn send-email!
   "Internal function used to send messages. Should take 2 args - a map of SMTP credentials, and a map of email details.
    Provided so you can swap this out with an \"inbox\" for test purposes."
-  postal/send-message)
+  [smtp-credentials email-details]
+  (System/setProperty "mail.mime.splitlongparameters" "false") ; https://github.com/metabase/metabase/issues/11879#issuecomment-713816386
```
Comment (dpsutton) [inline src/metabase/email.clj:48]: there's an idiom to set this property once in task.clj:

```clojure
(when-not *compile-files*
  (System/setProperty "org.quartz.dataSource.db.connectionProvider.class" (.getName ConnectionProvider)))
```

I'm wondering if perhaps something like this is more what we want? Or is there a reason we continuously set this system property each time we send a message?

Comment (tsmacdonald) [reply src/metabase/email.clj]: Good point; added it to the toplevel and things are :ok_hand:

Comment (robdaemon) [reply src/metabase/email.clj]: awesome, this call of `System/setProperty` was my fault, I like this top-level approach.

**Review by camsaul — APPROVED** [review]
