### PR TITLE
fix(sdk): support hiding columns in InteractiveQuestion

### LINKED ISSUE #48789: Hiding columns in InteractiveQuestion in the sdk throws a JavaScript error
Hiding columns in InteractiveQuestion throws a JavaScript error in the embedding sdk.

### Screenshot

When clicking on "Hide Column"

JavaScript error is thrown

```tsx
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'query')
    at visualization-settings.js:36:58
    at Object.dispatch (redux-thunk.mjs:5:14)
    at dispatch (page.bundle.js:6:7424)
    at pR (action.js:12:7)
    at ClickActionsPopover.tsx:56:26
    at onClick (ClickActionsView.tsx:52:32)
    at o10 (ClickActionControl.tsx:53:15)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
```

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/48789

### Description

Hiding columns currently throws a JavaScript error and does not work in `InteractiveQuestion`. This PR adds support for hiding columns in the SDK by adding a `onUpdateVisualizationSettingsSdk` handler, so the SDK's `InteractiveQuestion` component can update its own React context.

### Out of scope

There is currently no UI to restore the hidden columns in the SDK - we should implement that in a follow-up PR!

### How to verify

- Click on the "hide columns" button in the column header in the SDK
- Column should be hidden

### Demo

Hiding columns now work as expected.

### Checklist

- [x] tests has been added to this PR - e2e and unit

### CODE REVIEW

File: frontend/src/metabase/query_builder/actions/visualization-settings.ts [hunk 1]
```diff
@@ -24,16 +24,11 @@ export const onUpdateVisualizationSettings =
       queryBuilderMode === "dataset" && datasetEditorTab === "metadata";
     const wasJustEditingModel =
       previousQueryBuilderMode === "dataset" && queryBuilderMode !== "dataset";
-    const changedSettings = Object.keys(settings);
-    const isColumnWidthResetEvent =
-      changedSettings.length === 1 &&
-      changedSettings.includes("table.column_widths") &&
-      settings["table.column_widths"] === undefined;
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/actions/visualization-settings.ts:31]: We extract these conditions into `shouldUpdateVisualizationSettings`, so it can be re-used outside of this Redux action.

File: enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts [hunk 2]
```diff
@@ -143,6 +146,17 @@ export function useLoadQuestion({
     [dispatch, originalQuestion],
   );
 
+  const updateVisualizationSettings = useCallback(
+    async (settings: VisualizationSettings) => {
+      if (!question || !shouldUpdateVisualizationSettings(settings)) {
+        return;
+      }
+
+      return updateQuestion(question.updateSettings(settings), { run: false });
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts:155]: This matches the `onUpdateVisualizationSettings` redux action, but uses the context from the `useLoadQuestion` React hook instead.

File: frontend/src/metabase/query_builder/components/QueryVisualization.jsx [hunk 3]
```diff
@@ -78,6 +79,7 @@ export default function QueryVisualization(props) {
             maxTableRows={maxTableRows}
             className={CS.spread}
             onUpdateWarnings={setWarnings}
+            onUpdateVisualizationSettings={onUpdateVisualizationSettings}
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/QueryVisualization.jsx:82]: We need to pass `onUpdateVisualizationSettings` from the SDK's `QueryVisualization` component to `Visualization.jsx`

File: frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx [hunk 4]
```diff
@@ -48,9 +49,18 @@ export const HideColumnAction: LegacyDrill = ({
...
+        const vizSettings = { "table.columns": columnSettingsCopy };
+
+        const onUpdateVisualizationSettingsSdk = clicked?.extraData
+          ?.onUpdateVisualizationSettingsSdk as (
+          settings: VisualizationSettings,
+        ) => void;
+
+        // The embedding sdk does not store the question in the query builder store,
+        // therefore we must update the visualization settings in the React context.
+        onUpdateVisualizationSettingsSdk?.(vizSettings);
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx:61]: If `onUpdateVisualizationSettingsSdk` is passed into `extraData` which only happens we are in a SDK context, we also call this handler to update the SDK's question via the `useLoadQuestion` React context

File: enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.stories.tsx [hunk 5]
```diff
@@ -0,0 +1,28 @@
+import type { StoryFn } from "@storybook/react";
+
+import { InteractiveQuestion } from "embedding-sdk";
+import type { InteractiveQuestionProps } from "embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion";
+import { CommonSdkStoryWrapper } from "embedding-sdk/test/CommonSdkStoryWrapper";
+
+const QUESTION_ID = (window as any).QUESTION_ID || 1;
+
+export default {
+  title: "EmbeddingSDK/InteractiveQuestion",
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.stories.tsx:10]: TODO: write Cypress e2e tests for InteractiveQuestion once I got the E2E set up locally. I tried to write a unit test with react-testing-library, but the click actions popover would not trigger.

File: frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx [hunk 6]
```diff
@@ -48,9 +49,18 @@ export const HideColumnAction: LegacyDrill = ({
           };
         }
 
-        return onUpdateVisualizationSettings({
-          "table.columns": columnSettingsCopy,
-        });
+        const vizSettings = { "table.columns": columnSettingsCopy };
+
+        const onUpdateVisualizationSettingsSdk = clicked?.extraData
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx:54]: This is very questionable. I think the correct way is to make to work like drills where click actions do not know about the SDK. You might want to explore the `question` callback https://github.com/metabase/metabase/blob/7e879221af64a9c5422519bd40c596155289a847/frontend/src/metabase/querying/drills/utils/sort-drill.ts#L35 or something similar to archive this behavior.

**Review by ranquild — CHANGES_REQUESTED** [review]
Inline comment

File: frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx (hunk 6 above)
Comment (heypoom) [reply frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx:54]: @ranquild Thanks! I think something similar to `question: () => question.updateSettings(settings)` should do the trick. Looks like I will have to change the `onChangeCardAndRun` prop to notify the SDK of the change though, so we can update the `question` in the SDK's `InteractiveQuestion` context accordingly. I think the SDK can implement its own `onChangeCardAndRun` and pass it down the tree.

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.tsx#L56

Comment (heypoom) [reply frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx]: @ranquild Looks like the `question` callback currently always run the question because of the `onChangeCardAndRun` in `performAction`, which is not ideal for hiding columns. I'll add a `shouldRunQuestion` flag to the click action, so we can update the question without running it.

File: frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx [hunk 7]
```diff
@@ -48,10 +47,9 @@ export const HideColumnAction: LegacyDrill = ({
           };
         }
 
-        return onUpdateVisualizationSettings({
-          "table.columns": columnSettingsCopy,
-        });
+        return question.updateSettings({ "table.columns": columnSettingsCopy });
       },
+      questionChangeBehavior: "updateQuestion",
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx:52]: Default behaviour of the `question` callback is to change and run the card. We don't want to run the question every time we hide the column though, so we add the `updateQuestion` behaviour to simply update the question.

File: frontend/src/metabase/query_builder/components/view/View.jsx [hunk 8]
```diff
@@ -141,6 +141,7 @@ const ViewMainContainer = props => {
           noHeader
           className={CS.spread}
           mode={queryMode}
+          onUpdateQuestion={updateQuestion}
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/view/View.jsx:144]: We need to pass `onUpdateQuestion` to `VisualizationResult` underneath. Luckily, we already have an implementation of `updateQuestion` in the QB.

File: frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.tsx [hunk 9]
```diff
@@ -49,13 +51,14 @@ export class ClickActionsPopover extends Component<
...
   handleClickAction = (action: RegularClickAction) => {
-    const { dispatch, onChangeCardAndRun } = this.props;
+    const { dispatch, onChangeCardAndRun, onUpdateQuestion } = this.props;
     if (isPopoverClickAction(action)) {
       this.setState({ popoverAction: action });
     } else {
       const didPerform = performAction(action, {
         dispatch,
         onChangeCardAndRun,
+        onUpdateQuestion,
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.tsx:61]: Allows updating the question without running. Looks like there is a lot going on in `onChangeCardAndRun`, so I didn't want to add a `run` flag there - best to keep them separate.

File: frontend/src/metabase/visualizations/lib/action.unit.spec.ts [hunk 10]
```diff
@@ -16,6 +20,7 @@ describe("performAction", () => {
     const extraProps = {
       dispatch: jest.fn(),
       onChangeCardAndRun: jest.fn(),
+      onUpdateQuestion: jest.fn(),
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/lib/action.unit.spec.ts:23]: This is just to fix type check errors because of TypeScript type inference for `.js` files - it assume that `onUpdateQuestion` is required, when it really isn't. We could've also refactored `action.js` to TypeScript here.

**Review by ranquild — APPROVED** [review]

**Review by deniskaber — APPROVED** [review]
