### PR TITLE
Fix - Default names for date and number filters are off

### LINKED ISSUE #51996: Default names for date and number filters are off
### Describe the bug

When I add a date dashboard filter, I get a default name of "All options".
For a number filter by default it's "Equal to".

### To Reproduce

1. Go to any dashboard
2. Start adding a date filter or a number filter
3. See that the default name is "All options" or "Equal to", respectively

### Expected behavior

Should be just "Date" and "Number". When multiple filters of the same type added, should be like "Date 1", "Date 2", etc...

### Logs

_No response_

### Information about your Metabase installation

```JSON
27c6fe4
```

### Severity

Confusing, frequent

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #51996

### Description

Changes default name of date filter from "All options" to "Date".
Changes default name of number filter from "Equal to" to "Number".

No new tests - this already has coverage (as evidenced by updated tests).

### How to verify

For both dashboard filters and native editor filters:
- Filter names are as specified in PR description
- Filter operator names didn't change

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/template_tags/TagEditorParamParts/FilterWidgetTypeSelect.tsx [hunk 1]
```diff
@@ -27,7 +29,7 @@ export function FilterWidgetTypeSelect({
     () =>
       (hasOptions ? options : [{ name: t`None`, type: "none" }]).map(
         option => ({
-          label: option.name,
+          label: option.menuName ?? option.name,
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/template_tags/TagEditorParamParts/FilterWidgetTypeSelect.tsx:32]: This is to make filters in native editor work the same as in dashboards: https://github.com/metabase/metabase/blob/9108dd750c5cba9f2da0416f1c27c649f59e8444/frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.tsx#L153

**Review by ranquild — APPROVED** [review]
