### PR TITLE
visual permissions fixes

### LINKED ISSUE #21763: The Original Schema tab in the data model has duplicated table names
The second table and larger table name `PEOPLE` isn't necessary

[Figma Spec](https://www.figma.com/file/UPmKgv5KW7L9M9jC0ygnj0/Support-to-records-in-JSON-fields?node-id=317%3A6517)

image

### LINKED ISSUE #21765: In data permissions page, the minimum width of the `Database name` column is too large
The minimum width of the first column in the table is too large, it can harm the experience of admins with small screens

Expected behavior:
- The column width is the size of the biggest database name until a reasonable limit (the current width is a reasonable limit).

image

### PR DESCRIPTION
**Pull request by alxnddr**
1) Closes https://github.com/metabase/metabase/issues/21765

Open the [data permissions page](http://localhost:3000/admin/permissions/data/group) and ensure it handles short and long names correctly.
**Short name**
Screenshot 2022-04-20 at 17 27 38

**Long name**
Screenshot 2022-04-20 at 17 27 21

2) Closes https://github.com/metabase/metabase/issues/21763
Open the [data model page](http://localhost:3000/admin/datamodel/database/5/table/25) and click on the original schema. Ensure the table name is not duplocated.

Screenshot 2022-04-20 at 17 32 05

### CODE REVIEW

File: frontend/src/metabase/admin/permissions/components/PermissionsTable/PermissionsTable.jsx [hunk 1]
```diff
@@ -102,10 +103,12 @@ export function PermissionsTable({
...
+                      <Ellipsified>{entity.name}</Ellipsified>
                     </EntityNameLink>
                   ) : (
-                    <EntityName>{entity.name}</EntityName>
+                    <EntityName>
+                      <Ellipsified>{entity.name}</Ellipsified>
+                    </EntityName>
                   )}
 
                   {entity.hint && (
```
Comment (iethree) [inline frontend/src/metabase/admin/permissions/components/PermissionsTable/PermissionsTable.jsx:114]: this causes entity hints to get wrapped to the next line. I think they're meant to be on the same line

Screenshot from 2022-04-20 16-30-05

**Comment by iethree** [comment]
maybe we should give the group name list on `/admin/people/groups` the `<Ellipsified>` treatment as well, or at least not wrap long names under the letter-icon.
Screenshot from 2022-04-20 16-30-56

**Comment by alxnddr** [comment]
@iethree good catch, thanks! Fixed both

Screenshot 2022-04-22 at 19 55 06

On the groups page I added text wrapping instead of trimming similarly to the people page:
Screenshot 2022-04-22 at 20 25 24

**Review by iethree — APPROVED** [review]
:sparkling_heart:
