### PR TITLE
Send pulse skip legacy alerts

### LINKED ISSUE #63189: Fix double alert send
### Describe the bug

Since bumping Metabase from v55.10 to v56.2, our Metabase Slack alerts have been duplicated. Questions and alerts are not duplicated in the UI (only one is visible), but Metabot sends two of each message. Deleting and recreating the alerts had no effect. 

This seems to be another occurrence of a previous double alerts issue (see #54478). 

### To Reproduce

1. Set up Slack alerts in Metabase v55.10
2. Update Metabase to v56.2
3. Wait for the alert to run and see duplicate messages

### Expected behavior

One alert in Metabase UI should equate to one alert sent in Slack. 

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-08-12",
      "tag": "v0.56.2",
      "hash": "75e1c0b"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "5.10.240-238.959.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Closes https://github.com/metabase/metabase/issues/63189
Thread: https://metaboat.slack.com/archives/C052ZBWRG3W/p1757704378937449

Background: in 54, we've migrated alerts from pulse to the new notification system, as part of that process we don't archive the alerts on pulse tables because we want to be able to rollback. 
What we did to make sure the legacy won't be send is by deleting the quartz triggers for legacy pulse as part of the migration process. 

Though the above solution should ensure no old pulses will be sent, but it's might be that some naming pattern change and the we haven't fully deleted all the triggers of the legacy pulse. so some customers might experience this issue.

This PR add another layer of safeguard by making sure the send pulse api skip pulse that are alerts.
Ideally we should be able to clean up those triggers but unfortunately quartz doesn't allow self-cleaning a trigger while it's running.
I think it's alright as this should be a rare case and also we plan to migrate dashboard subscription to notification soon, once we do that we can clean up all of the remaining pulse triggers.

### CODE REVIEW

File: test/metabase/api/downloads_exports_test.clj [hunk 1]
```diff
@@ -980,14 +980,13 @@
                                                        :type     :native
                                                        :native   {:query "SELECT 1 as A FROM generate_series(1,109);"}}}]
         (let [results (all-outputs! card {:export-format :csv})]
-          (is (= {:card-download            110
-                  :unsaved-card-download    110
-                  :alert-attachment         110
```
Comment (crisptrutski) [inline test/metabase/api/downloads_exports_test.clj:985]: I'd prefer we explicitly dissoc this key from results, so that the assert is more powerful.

**Review by crisptrutski — APPROVED** [review]

**Comment by crisptrutski** [comment]
I didn't understand the root cause explanation, but the mitigation seems straight forward and safe.
