### PR TITLE
Handle locationlization errors from java.util.Locale

### LINKED ISSUE #22192: Selecting language Indonesian causes error
Setting a users language to Indonesian throws an error that the user cannot recover from

**Logs**
Can be seen in the gif below, but it appears that Moment is attempting to load the locale `in`. The locale for Indonesian that we use is `id`.

**To Reproduce**
On a Fresh install of metabase
1. Complete initial setup screen. Select english as your language
2. Go to account settings
3. Select Indonesian as the language
4. Click update

**Expected behavior**
Page to be refreshed and displayed in Indonesian

**Screenshots**
chrome_HMnzAeRFuz

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.10.16.3-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "America/Halifax"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-04-27",
      "src_hash": "8878eded49230b44f9d94c8d7d86a32ab910ce4d",
      "tag": "v0.43.1-SNAPSHOT",
      "branch": "revision-history-not-updating-after-revert",
      "hash": "614127d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Seems to put us in an irrecoverable state. Potential P1

**Additional context**
@flamber @diegmonti 
We have confirmed that we call `PUT /api/user/:id` with the correct locale, but it appears to be set incorrectly in `window.MetabaseLocalization`. The terminal console will display `Locale 'in' not found`, which suggests that maybe something is happening [here](https://github.com/metabase/metabase/blob/master/src/metabase/server/routes/index.clj#L50)

### PR DESCRIPTION
**Pull request by dpsutton**
Indonesian has code "id". But
```
;; java 11
(str (java.util.Locale/forLanguageTag "id")) => "in"

;; java 17
(str (java.util.Locale/forLanguageTag "id")) => "id"
```

And this was bad. Because the frontend sends us the language to use:
"id" for indonesian. We write that down. And then when we need to
construct the index.html page with the correct translations, instead of
using "id"-- the value we were given-- we construct a Locale from "id"
and then get the str value of that which is "in". We don't have a in.edn
file, there's no frontend in.json file, and moment.js has no in
localization. And this all happened because we kept this value we all
agreed upon in a java util class and then asked it for that value back.
\

### CODE REVIEW

**Review by adam-james-v — APPROVED** [review]
The locale coercion that we avoid here makes sense.
I think this is a good solution to the bug (#22192).

It makes me wonder if we might have a similar problem with the translation implementation itself? Like, if we have "id.edn" but try to load from (locale "id"), we could get the same issue failing quietly in the backend.

File: src/metabase/util/i18n.clj [hunk 1]
```diff
@@ -25,25 +25,32 @@
   nil)
 
 (def ^:dynamic *site-locale-override*
-  "Bind this to a string, keyword, or `Locale` to override the value returned by `site-locale`. For testing purposes,
+  "Bind this to a string, keyword to override the value returned by `site-locale`. For testing purposes,
   such as when swapping out an application database temporarily, when the setting table may not even exist."
   nil)
 
+(defn site-locale-string
+  []
```
Comment (adam-james-v) [inline src/metabase/util/i18n.clj:33]: This needs a docstring to pass the linter

**Comment by nemanjaglumac** [comment]
@dpsutton this issue had a repro associated with it, signaled by the `.Reproduced` label. It should've been unskipped and merged together with the fix.

It helps if you use closing keyword directly in the description because that creates a direct connection between the issue and the PR **and** it makes it easier to quickly navigate to the issue in the future.
