### PR TITLE
Ensure :error is present for frontend

### LINKED ISSUE #23281: Metabase returns "No results!" when the SSH tunnel is down on a query
**Describe the bug**
If you connect to a database via an SSH tunnel, and then the tunnel is disconnected, then Metabase will try to run the queries but will timeout in 5 seconds and return a "No results!" message. This is an issue since we're not returning the correct error message here which should be a "Can't connect to database" or "can't resolve the tunnel".

The exception in the backend is
{:status :failed,
:class org.apache.sshd.common.SshException,
:error "DefaultConnectFuture[metabase@ssh-choke:2222]: Failed (UnresolvedAddressException) to execute: null"

**Logs**
<details>
```
metabase-choke         | 2022-06-10 13:59:42,655 WARN sql-jdbc.connection :: ssh tunnel for database 2 looks closed; marking pool invalid to reopen it
metabase-choke         | 2022-06-10 13:59:47,819 ERROR middleware.catch-exceptions :: Error processing query: null
metabase-choke         | {:database_id 2,
metabase-choke         |  :started_at #t "2022-06-10T13:59:42.653766Z[GMT]",
metabase-choke         |  :via
metabase-choke         |  [{:status :failed,
metabase-choke         |    :class org.apache.sshd.common.SshException,
metabase-choke         |    :error "DefaultConnectFuture[metabase@ssh-choke:2222]: Failed (UnresolvedAddressException) to execute: null",
metabase-choke         |    :stacktrace
metabase-choke         |    ["org.apache.sshd.common.future.AbstractSshFuture.lambda$verifyResult$1(AbstractSshFuture.java:131)"
metabase-choke         |     "org.apache.sshd.common.future.AbstractSshFuture.formatExceptionMessage(AbstractSshFuture.java:185)"
metabase-choke         |     "org.apache.sshd.common.future.AbstractSshFuture.verifyResult(AbstractSshFuture.java:130)"
metabase-choke         |     "org.apache.sshd.client.future.DefaultConnectFuture.verify(DefaultConnectFuture.java:42)"
metabase-choke         |     "org.apache.sshd.client.future.DefaultConnectFuture.verify(DefaultConnectFuture.java:34)"
metabase-choke         |     "--> util.ssh$start_ssh_tunnel_BANG_.invokeStatic(ssh.clj:55)"
metabase-choke         |     "util.ssh$start_ssh_tunnel_BANG_.invoke(ssh.clj:48)"
metabase-choke         |     "util.ssh$include_ssh_tunnel_BANG_.invokeStatic(ssh.clj:89)"
metabase-choke         |     "util.ssh$include_ssh_tunnel_BANG_.invoke(ssh.clj:83)"
metabase-choke         |     "util.ssh$fn__34670.invokeStatic(ssh.clj:115)"
metabase-choke         |     "util.ssh$fn__34670.invoke(ssh.clj:105)"
metabase-choke         |     "driver.sql_jdbc.connection$create_pool_BANG_.invokeStatic(connection.clj:111)"
metabase-choke         |     "driver.sql_jdbc.connection$create_pool_BANG_.invoke(connection.clj:106)"
metabase-choke         |     "driver.sql_jdbc.connection$db__GT_pooled_connection_spec.invokeStatic(connection.clj:235)"
metabase-choke         |     "driver.sql_jdbc.connection$db__GT_pooled_connection_spec.invoke(connection.clj:182)"
metabase-choke         |     "driver.sql_jdbc.execute$datasource.invokeStatic(execute.clj:135)"
metabase-choke         |     "driver.sql_jdbc.execute$datasource.invoke(execute.clj:131)"
metabase-choke         |     "driver.sql_jdbc.execute$datasource_with_diagnostic_info_BANG_.invokeStatic(execute.clj:142)"
metabase-choke         |     "driver.sql_jdbc.execute$datasource_with_diagnostic_info_BANG_.invoke(execute.clj:137)"
metabase-choke         |     "driver.sql_jdbc.execute$fn__53780.invokeStatic(execute.clj:190)"
metabase-choke         |     "driver.sql_jdbc.execute$fn__53780.invoke(execute.clj:188)"
metabase-choke         |     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:497)"
metabase-choke         |     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
metabase-choke         |     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
metabase-choke         |     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
metabase-choke         |     "driver.sql_jdbc$fn__88851.invokeStatic(sql_jdbc.clj:54)"
metabase-choke         |     "driver.sql_jdbc$fn__88851.invoke(sql_jdbc.clj:52)"
metabase-choke         |     "query_processor.context$executef.invokeStatic(context.clj:59)"
metabase-choke         |     "query_processor.context$executef.invoke(context.clj:48)"
metabase-choke         |     "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
metabase-choke         |     "query_processor.context.default$default_runf.invoke(default.clj:65)"
metabase-choke         |     "query_processor.context$runf.invokeStatic(context.clj:45)"
metabase-choke         |     "query_processor.context$runf.invoke(context.clj:39)"
metabase-choke         |     "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
metabase-choke         |     "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
metabase-choke         |     "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51444.invoke(cache.clj:220)"
metabase-choke         |     "query_processor.middleware.permissions$check_query_permissions$fn__47227.invoke(permissions.clj:109)"
metabase-choke         |     "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__83113.invoke(permissions.clj:127)"
metabase-choke         |     "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__84885.invoke(column_level_perms_check.clj:30)"
metabase-choke         |     "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50385.invoke(mbql_to_native.clj:23)"
metabase-choke         |     "query_processor$fn__52917$combined_post_process__52922$combined_post_process_STAR___52923.invoke(query_processor.clj:207)"
metabase-choke         |     "query_processor$fn__52917$combined_pre_process__52918$combined_pre_process_STAR___52919.invoke(query_processor.clj:204)"
metabase-choke         |     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365$fn__51370.invoke(resolve_database_and_driver.clj:35)"
metabase-choke         |     "driver$do_with_driver.invokeStatic(driver.clj:75)"
metabase-choke         |     "driver$do_with_driver.invoke(driver.clj:71)"
metabase-choke         |     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365.invoke(resolve_database_and_driver.clj:34)"
metabase-choke         |     "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47470.invoke(fetch_source_query.clj:281)"
metabase-choke         |     "query_processor.middleware.store$initialize_store$fn__47658$fn__47659.invoke(store.clj:11)"
metabase-choke         |     "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
metabase-choke         |     "query_processor.store$do_with_store.invoke(store.clj:38)"
metabase-choke         |     "query_processor.middleware.store$initialize_store$fn__47658.invoke(store.clj:10)"
metabase-choke         |     "query_processor.middleware.normalize_query$normalize$fn__51637.invoke(normalize_query.clj:22)"
metabase-choke         |     "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__58302.invoke(handle_audit_queries.clj:130)"
metabase-choke         |     "query_processor.middleware.constraints$add_default_userland_constraints$fn__48727.invoke(constraints.clj:53)"
metabase-choke         |     "query_processor.middleware.process_userland_query$process_userland_query$fn__51576.invoke(process_userland_query.clj:145)"
metabase-choke         |     "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51948.invoke(catch_exceptions.clj:162)"
metabase-choke         |     "query_processor.reducible$async_qp$qp_STAR___44197$thunk__44199.invoke(reducible.clj:100)"
metabase-choke         |     "query_processor.reducible$async_qp$qp_STAR___44197.invoke(reducible.clj:106)"
metabase-choke         |     "query_processor.reducible$async_qp$qp_STAR___44197.invoke(reducible.clj:91)"
metabase-choke         |     "query_processor.reducible$sync_qp$qp_STAR___44208.doInvoke(reducible.clj:126)"
metabase-choke         |     "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
metabase-choke         |     "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
metabase-choke         |     "query_processor$fn__52964$process_query_and_save_execution_BANG___52973$fn__52976.invoke(query_processor.clj:337)"
metabase-choke         |     "query_processor$fn__52964$process_query_and_save_execution_BANG___52973.invoke(query_processor.clj:330)"
metabase-choke         |     "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017$fn__53020.invoke(query_processor.clj:349)"
metabase-choke         |     "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017.invoke(query_processor.clj:342)"
metabase-choke         |     "api.dataset$run_query_async$fn__67419.invoke(dataset.clj:68)"
metabase-choke         |     "query_processor.streaming$streaming_response_STAR_$fn__39320$fn__39321.invoke(streaming.clj:162)"
metabase-choke         |     "query_processor.streaming$streaming_response_STAR_$fn__39320.invoke(streaming.clj:161)"
metabase-choke         |     "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
metabase-choke         |     "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
metabase-choke         |     "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"]}],
metabase-choke         |  :json_query
metabase-choke         |  {:type "native",
metabase-choke         |   :native {:query "select * from people", :template-tags {}},
metabase-choke         |   :database 2,
metabase-choke         |   :parameters [],
metabase-choke         |   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
metabase-choke         |  :status :failed,
metabase-choke         |  :class java.nio.channels.UnresolvedAddressException,
metabase-choke         |  :stacktrace
metabase-choke         |  ["java.base/sun.nio.ch.Net.checkAddress(Unknown Source)"
metabase-choke         |   "java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(Unknown Source)"
metabase-choke         |   "java.base/sun.nio.ch.AsynchronousSocketChannelImpl.connect(Unknown Source)"
metabase-choke         |   "org.apache.sshd.common.io.nio2.Nio2Connector.connect(Nio2Connector.java:70)"
metabase-choke         |   "org.apache.sshd.client.SshClient.doConnect(SshClient.java:634)"
metabase-choke         |   "org.apache.sshd.client.SshClient.doConnect(SshClient.java:616)"
metabase-choke         |   "org.apache.sshd.client.SshClient.connect(SshClient.java:547)"
metabase-choke         |   "org.apache.sshd.client.SshClient.connect(SshClient.java:539)"
metabase-choke         |   "org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:74)"
metabase-choke         |   "org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:57)"
metabase-choke         |   "--> util.ssh$start_ssh_tunnel_BANG_.invokeStatic(ssh.clj:54)"
metabase-choke         |   "util.ssh$start_ssh_tunnel_BANG_.invoke(ssh.clj:48)"
metabase-choke         |   "util.ssh$include_ssh_tunnel_BANG_.invokeStatic(ssh.clj:89)"
metabase-choke         |   "util.ssh$include_ssh_tunnel_BANG_.invoke(ssh.clj:83)"
metabase-choke         |   "util.ssh$fn__34670.invokeStatic(ssh.clj:115)"
metabase-choke         |   "util.ssh$fn__34670.invoke(ssh.clj:105)"
metabase-choke         |   "driver.sql_jdbc.connection$create_pool_BANG_.invokeStatic(connection.clj:111)"
metabase-choke         |   "driver.sql_jdbc.connection$create_pool_BANG_.invoke(connection.clj:106)"
metabase-choke         |   "driver.sql_jdbc.connection$db__GT_pooled_connection_spec.invokeStatic(connection.clj:235)"
metabase-choke         |   "driver.sql_jdbc.connection$db__GT_pooled_connection_spec.invoke(connection.clj:182)"
metabase-choke         |   "driver.sql_jdbc.execute$datasource.invokeStatic(execute.clj:135)"
metabase-choke         |   "driver.sql_jdbc.execute$datasource.invoke(execute.clj:131)"
metabase-choke         |   "driver.sql_jdbc.execute$datasource_with_diagnostic_info_BANG_.invokeStatic(execute.clj:142)"
metabase-choke         |   "driver.sql_jdbc.execute$datasource_with_diagnostic_info_BANG_.invoke(execute.clj:137)"
metabase-choke         |   "driver.sql_jdbc.execute$fn__53780.invokeStatic(execute.clj:190)"
metabase-choke         |   "driver.sql_jdbc.execute$fn__53780.invoke(execute.clj:188)"
metabase-choke         |   "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:497)"
metabase-choke         |   "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
metabase-choke         |   "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
metabase-choke         |   "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
metabase-choke         |   "driver.sql_jdbc$fn__88851.invokeStatic(sql_jdbc.clj:54)"
metabase-choke         |   "driver.sql_jdbc$fn__88851.invoke(sql_jdbc.clj:52)"
metabase-choke         |   "query_processor.context$executef.invokeStatic(context.clj:59)"
metabase-choke         |   "query_processor.context$executef.invoke(context.clj:48)"
metabase-choke         |   "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
metabase-choke         |   "query_processor.context.default$default_runf.invoke(default.clj:65)"
metabase-choke         |   "query_processor.context$runf.invokeStatic(context.clj:45)"
metabase-choke         |   "query_processor.context$runf.invoke(context.clj:39)"
metabase-choke         |   "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
metabase-choke         |   "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
metabase-choke         |   "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51444.invoke(cache.clj:220)"
metabase-choke         |   "query_processor.middleware.permissions$check_query_permissions$fn__47227.invoke(permissions.clj:109)"
metabase-choke         |   "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__83113.invoke(permissions.clj:127)"
metabase-choke         |   "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__84885.invoke(column_level_perms_check.clj:30)"
metabase-choke         |   "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50385.invoke(mbql_to_native.clj:23)"
metabase-choke         |   "query_processor$fn__52917$combined_post_process__52922$combined_post_process_STAR___52923.invoke(query_processor.clj:207)"
metabase-choke         |   "query_processor$fn__52917$combined_pre_process__52918$combined_pre_process_STAR___52919.invoke(query_processor.clj:204)"
metabase-choke         |   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365$fn__51370.invoke(resolve_database_and_driver.clj:35)"
metabase-choke         |   "driver$do_with_driver.invokeStatic(driver.clj:75)"
metabase-choke         |   "driver$do_with_driver.invoke(driver.clj:71)"
metabase-choke         |   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51365.invoke(resolve_database_and_driver.clj:34)"
metabase-choke         |   "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47470.invoke(fetch_source_query.clj:281)"
metabase-choke         |   "query_processor.middleware.store$initialize_store$fn__47658$fn__47659.invoke(store.clj:11)"
metabase-choke         |   "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
metabase-choke         |   "query_processor.store$do_with_store.invoke(store.clj:38)"
metabase-choke         |   "query_processor.middleware.store$initialize_store$fn__47658.invoke(store.clj:10)"
metabase-choke         |   "query_processor.middleware.normalize_query$normalize$fn__51637.invoke(normalize_query.clj:22)"
metabase-choke         |   "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__58302.invoke(handle_audit_queries.clj:130)"
metabase-choke         |   "query_processor.middleware.constraints$add_default_userland_constraints$fn__48727.invoke(constraints.clj:53)"
metabase-choke         |   "query_processor.middleware.process_userland_query$process_userland_query$fn__51576.invoke(process_userland_query.clj:145)"
metabase-choke         |   "query_processor.middleware.catch_exceptions$catch_exceptions$fn__51948.invoke(catch_exceptions.clj:162)"
metabase-choke         |   "query_processor.reducible$async_qp$qp_STAR___44197$thunk__44199.invoke(reducible.clj:100)"
metabase-choke         |   "query_processor.reducible$async_qp$qp_STAR___44197.invoke(reducible.clj:106)"
metabase-choke         |   "query_processor.reducible$async_qp$qp_STAR___44197.invoke(reducible.clj:91)"
metabase-choke         |   "query_processor.reducible$sync_qp$qp_STAR___44208.doInvoke(reducible.clj:126)"
metabase-choke         |   "query_processor$process_userland_query.invokeStatic(query_processor.clj:326)"
metabase-choke         |   "query_processor$process_userland_query.doInvoke(query_processor.clj:322)"
metabase-choke         |   "query_processor$fn__52964$process_query_and_save_execution_BANG___52973$fn__52976.invoke(query_processor.clj:337)"
metabase-choke         |   "query_processor$fn__52964$process_query_and_save_execution_BANG___52973.invoke(query_processor.clj:330)"
metabase-choke         |   "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017$fn__53020.invoke(query_processor.clj:349)"
metabase-choke         |   "query_processor$fn__53008$process_query_and_save_with_max_results_constraints_BANG___53017.invoke(query_processor.clj:342)"
metabase-choke         |   "api.dataset$run_query_async$fn__67419.invoke(dataset.clj:68)"
metabase-choke         |   "query_processor.streaming$streaming_response_STAR_$fn__39320$fn__39321.invoke(streaming.clj:162)"
metabase-choke         |   "query_processor.streaming$streaming_response_STAR_$fn__39320.invoke(streaming.clj:161)"
metabase-choke         |   "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
metabase-choke         |   "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
metabase-choke         |   "async.streaming_response$do_f_async$task__18948.invoke(streaming_response.clj:84)"],
metabase-choke         |  :card_id nil,
metabase-choke         |  :context :ad-hoc,
metabase-choke         |  :error nil,
metabase-choke         |  :row_count 0,
metabase-choke         |  :running_time 0,
metabase-choke         |  :data {:rows [], :cols []}}
metabase-choke         | 
```
</details>

**To Reproduce**
1. Clone this repo: https://github.com/paoliniluis/mariadb-10.1.48-ssh and do a docker-compose up
2. Start Metabase and connect to the database with the following
image
3. Do a SQL query like "SELECT * FROM `PEOPLE`", run it and see the data
4. Now kill the SSH container with a "docker stop ssh-choke" (wait till the op finishes)
5. Run the SQL query again, you get the "No results!" error

**Expected behavior**
Show the true error? or at least a "cannot connect to the database"

**Screenshots**
with the tunnel up
image

with the tunnel down
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop-OS 22.04
- Your databases: Postgres 14.2
- Metabase version: 1.43.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14.2

**Severity**
Not severe

**Additional context**
NA

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes https://github.com/metabase/metabase/issues/23281 and https://github.com/metabase/metabase/issues/23258

NOTE: it does not add the functionality of filtering by quarters to native queries but makes it clear that they error rather than return no results.

The frontend checks for a string at "error" to determine if there's an
error or not. Any error that lacks a message (`(.getMessage e) = nil`)
will report as a successful query with no results. This was hard to
reproduce at first because java 14+ added a nice error message to NPEs
in [JEP-358](https://openjdk.org/jeps/358).

```java
;; java 11
jshell> HashSet x = null;
x ==> null

jshell> x.contains(3);
|  Exception java.lang.NullPointerException
|        at (#2:1)

jshell>

;; java 17
jshell> HashSet x = null;
x ==> null

jshell> x.contains(3);
|  Exception java.lang.NullPointerException: Cannot invoke "java.util.HashSet.contains(Object)" because "REPL.$JShell$11.x" is null
|        at (#4:1)
```

```clojure
;; java 17
catch-exceptions=> (let [x nil] (x 3))
Execution error (NullPointerException) at metabase.query-processor.middleware.catch-exceptions/eval130385 (REPL:41).
Cannot invoke "clojure.lang.IFn.invoke(Object)" because "x" is null

;; java 11

catch-exceptions=> (let [x nil] (x 3))
Execution error (NullPointerException) at metabase.driver.sql.parameters.substitution/eval118508 (REPL:17).
null
```

Here are the responses to the FE edited to the relevant bits:

```javascript
// objects are edited for clarity/brevity:
// from java-11
{
  "error_type": "qp",
  "status": "failed",
  "class": "class java.lang.NullPointerException",
  "stacktrace": [...],
  "error": null,   // <---- the FE ignores all of the other data and only sees this
}

// vs java-17
{
  "error_type": "qp",
  "status": "failed",
  "class": "class java.lang.NullPointerException",
  "stacktrace": [...],
  "error": "Cannot invoke \"clojure.lang.IFn.invoke(Object)\" because \"to_period\" is null",,
}
```

Also, note that we were still logging

> ERROR middleware.catch-exceptions :: Error processing query: null

because we were looking for `(:error format-exception)` instead of
`(:error formatted-exception)`. `format-exception` is a multimethod and
lookup on non-associative things will happily return nil.

### CODE REVIEW

File: test/metabase/query_processor/middleware/catch_exceptions_test.clj [hunk 1]
```diff
@@ -104,37 +104,50 @@
                  :metadata
                  (update :stacktrace boolean)))))))
 
-(deftest include-query-execution-info-test
-  (testing "Should include info from QueryExecution if added to the thrown/raised Exception"
+(deftest catch-exceptions-test
+  (testing "include-query-execution-info-test"
```
Comment (dpsutton) [inline test/metabase/query_processor/middleware/catch_exceptions_test.clj:108]: this is just moving another test named `include-query-execution-info-test` inside of a catchall `catch-exceptions-test` with the former test name being a `testing` context now.

File: test/metabase/query_processor/middleware/catch_exceptions_test.clj [hunk 2]
```diff
@@ -104,37 +104,50 @@
...
+                                                                                                 :executor_id  500
+                                                                                                 :dashboard_id 700
+                                                                                                 :pulse_id     800
+                                                                                                 :native       900}}
+                                                                              (Exception. "Something went wrong"))
+                                                                     context))})
+                  :metadata
+                  (update :stacktrace boolean)))))))
+  (testing "Should always include :error (#23258, #23281)"
     (tu.log/suppress-output
```
Comment (dpsutton) [inline test/metabase/query_processor/middleware/catch_exceptions_test.clj:140]: `tu.log/suppress-output` is deprecated but running the tests in the repl still would print the exceptions so it still has a purpose. It was deprecated now that we have a log config which sets the log threshold to fatal but still has a use for ad-hoc repl testing, ie `(catch-exceptions-test)` at the repl.

Comment (howonlee) [reply test/metabase/query_processor/middleware/catch_exceptions_test.clj:140]: can't we just... put in a temp config in test context, since this PR is not in the repl?

**Review by howonlee — APPROVED** [review]
"Error processing query: Error running query" would be kinda funny-looking when encountered but this is a pretty absurdly small nit. OW LGTM

File: test/metabase/query_processor/middleware/catch_exceptions_test.clj (hunk 2 above)
Comment (dpsutton) [reply test/metabase/query_processor/middleware/catch_exceptions_test.clj:140]: We do have a test config: https://github.com/metabase/metabase/blob/master/test_config/log4j2-test.xml . I'm addressing when you actually run these tests in the repl while developing. In this context the normal log4js.xml is used so the errors get logged and they end up in the repl.
