### PR TITLE
Nested joins ignore temporal units

### LINKED ISSUE #48058: Error when using Group by "hour of day" on an attribute from a join and a custom column
### Describe the bug

When trying to group by "hour of day" on an attribute that comes from a join and a custom column, I encounter the following error:

```
ERROR: function pg_catalog.extract(unknown, integer) does not exist
Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Position: 129
```

### To Reproduce

1. Create a query that involves joining tables.
2. Group by "hour of day" on an attribute from the joined table.
3. The above error is triggered.

### Expected behavior

I expect Metabase to correctly group by "hour of day" without throwing an error.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-09-16",
      "tag": "v0.50.26",
      "hash": "5a65f46"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "6.8.12-clevercloud-vm-dirty",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

This issue is annoying but not blocking our usage of Metabase entirely

### Additional context

 Screenshots of the query editor and the generated SQL will be provided.

Capture d’écran 2024-09-23 à 16 37 38

```sql
SELECT
  CAST(
    extract(
      hour
      from
        "source"."Message Delivery__opened_at_2"
    ) AS integer
  ) AS "Message Delivery__opened_at",
  "source"."status message" AS "status message",
  COUNT(*) AS "count"
FROM
  (
    SELECT
      "public"."message"."id" AS "id",
      "public"."message"."name" AS "name",
      CASE
        WHEN "Message Delivery"."clicked_at" IS NOT NULL THEN 'clicked'
        WHEN "Message Delivery"."opened_at" IS NOT NULL THEN 'open'
        WHEN "Message Delivery"."delivered_at" IS NOT NULL THEN 'delivery'
        ELSE 'other'
      END AS "status message",
      "Message Delivery"."id" AS "Message Delivery__id",
      "Message Delivery"."created_at" AS "Message Delivery__created_at",
      "Message Delivery"."updated_at" AS "Message Delivery__updated_at",
      "Message Delivery"."recipient_id" AS "Message Delivery__recipient_id",
      "Message Delivery"."message_id" AS "Message Delivery__message_id",
      "Message Delivery"."sent_at" AS "Message Delivery__sent_at",
      "Message Delivery"."delivered_at" AS "Message Delivery__delivered_at",
      "Message Delivery"."opened_at" AS "Message Delivery__opened_at",
      "Message Delivery"."clicked_at" AS "Message Delivery__clicked_at",
      "Message Delivery"."failed_at" AS "Message Delivery__failed_at",
      "Message Delivery"."error_type" AS "Message Delivery__error_type",
      "Message Delivery"."error_msg" AS "Message Delivery__error_msg",
      "Message Delivery"."recipient_type" AS "Message Delivery__recipient_type",
      "Message Delivery"."email" AS "Message Delivery__email",
      "Message Delivery"."mail_code" AS "Message Delivery__mail_code",
      CAST(
        extract(
          hour
          from
            "Message Delivery"."opened_at"
        ) AS integer
      ) AS "Message Delivery__opened_at_2"
    FROM
      "public"."message"
     
LEFT JOIN "public"."message_delivery" AS "Message Delivery" ON "public"."message"."id" = "Message Delivery"."message_id"
   
WHERE
      "public"."message"."name" = 'mission-mail-campaign:fdfoct2024'
  ) AS "source"
GROUP BY
  CAST(
    extract(
      hour
      from
        "source"."Message Delivery__opened_at_2"
    ) AS integer
  ),
  "source"."status message"
ORDER BY
  CAST(
    extract(
      hour
      from
        "source"."Message Delivery__opened_at_2"
    ) AS integer
  ) ASC,
  "source"."status message" ASC
  ```

### PR DESCRIPTION
**Pull request by wzimrin**
Closes https://github.com/metabase/metabase/issues/48058

### Description

The underlying issue is that nest-query/nest-expression included temporal units when copying over joined fields into the nested query.  This caused both the nested query and the parent query to include the "extract the unit from the date" code.  In cases where the extraction didn't change the type, this duplication wasn't a big deal.  However, for temporal units like hour-of-day, the first extraction changed the type of the field from date to string, and then the second extraction broke.

### How to verify

Follow the reproduction instructions in the linked case.  Basically, set up a question with a join, a custom fields, and a summary on a date field from the joined table grouped by hour of day.  This used to not work, and now it does.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/util/nest_query.clj [hunk 1]
```diff
@@ -24,7 +24,7 @@
    add/normalize-clause
    (lib.util.match/match (walk/prewalk (fn [x]
                                          (if (map? x)
-                                           (dissoc x :source-query :source-metadata)
+                                           (dissoc x :source-query :source-metadata :temporal-unit)
```
Comment (wzimrin) [inline src/metabase/query_processor/util/nest_query.clj:27]: It's possible that we want a broader fix here.  If other options can produce sql that changes the type of the field, they would cause similar issues. 
 Perhaps we want a whitelist instead of blacklisting certain fields?

Comment (bshepherdson) [reply src/metabase/query_processor/util/nest_query.clj:27]: There are a few more cases like this, though they're handled somewhat differently than temporal units.

But I wouldn't worry too much about implementation details; this whole setup will be changing substantially with the new refs.

File: test/metabase/query_processor/util/nest_query_test.clj [hunk 2]
```diff
@@ -762,3 +762,24 @@
...
+                     :joins [{:source-table $$people
+                              :alias        "p"
+                              :condition    [:= $user-id &p.people.id]}]})
+                  qp.preprocess/preprocess
+                  add/add-alias-info
+                  nest-expressions
+                  :source-query
+                  :fields
+                  (map #(% 2))
+                  (filter :temporal-unit))))))))
```
Comment (bshepherdson) [inline test/metabase/query_processor/util/nest_query_test.clj:785]: This feels like squinting too hard, stripping everything away from the test output. We tend to leverage the `=?` fuzzy matcher to get a more solid picture of the expectation.

Let's try something more like `(is (=? {:source-query {:fields [[:field (mt/id :some :field) {:temporal-unit (symbol "nil #_\"key is not present.\"")}] ...]}} ...))`.

**Review by bshepherdson — CHANGES_REQUESTED** [review]

File: test/metabase/query_processor/util/nest_query_test.clj (hunk 2 above)
Comment (wzimrin) [reply test/metabase/query_processor/util/nest_query_test.clj]: sure

**Review by bshepherdson — APPROVED** [review]
