### PR TITLE
array-map for json export to preserve order

### LINKED ISSUE #12247: Columns are sorted in JSON export, when there more than 8 columns
**Describe the bug**

After activate my Metabase Enterprise Version during some tests I noticed some problems with sort colluns when I exported QUESTION to JSON format using API or download button.

If the quantity of collumns are less than 8 works fine if is more than 8 I got problems, that situation happens only with JSON format export questions.

**To Reproduce**
1. Create a question with more than 9 collums
3. Modify the collumn order
4 Click on export to JSON format
5. You can see that the order that you selected is not the same

**Expected behavior**
Correct sort colluns

**Screenshots**
image

**Severity**
I think that is high that moment, we are developing a POC and we need to decide the best BI solution to fit in our plans to continue the project.

**Additional context**

**Diagnostic Info**

{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_241-b07",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_241",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.241-b07",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v1.34.3",
      "date": "2020-02-28",
      "branch": "enterprise-release-1.34.x",
      "hash": "ab6cc46"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

```

### PR DESCRIPTION
**Pull request by tsplude**
closes #12247
Closes VIZ-29

- Use `array-map` instead of `zipmap` when streaming the row results of json exports so that we avoid the hash map conversion that occurs for maps with 8+ key/values as this results in nondeterministic ordering

<details>
<summary>Before & After</summary>
image
</details>

### CODE REVIEW

File: src/metabase/query_processor/streaming/json.clj [hunk 1]
```diff
@@ -63,19 +63,20 @@
...
-                     ;; Metabase UI, especially numbers (e.g. percents, currencies, and rounding). However, this
-                     ;; does mean that all JSON values are strings. Any other strategy requires some level of
-                     ;; inference to know if we should or should not parse a string (or not stringify an object).
-                     (let [res (formatter (streaming.common/format-value r))]
-                       (cond
-                         (formatter/NumericWrapper? res) (:num-str res)
-                         (formatter/TextWrapper? res)    (:text-str res)
-                         :else                          res)))
-                   @ordered-formatters cleaned-row))
+             (apply array-map
```
Comment (noahmoss) [inline src/metabase/query_processor/streaming/json.clj:66]: Maybe worth leaving a comment on why we're using `array-map` here for posterity

**Review by noahmoss — APPROVED** [review]
