### PR TITLE
Disallow invalid values for the 'humanization strategy' setting (#35469)

### LINKED ISSUE #35469: Setting a wrong value in MB_HUMANIZATION_STRATEGY will break the sync
### Describe the bug

Trying to go over the MB_HUMANIZATION_STRATEGY env var, I gave it a "disabled" value and it broke all the sync

### To Reproduce

Set up a MB environment with
MB_HUMANIZATION_STRATEGY=disabled
as an env var...

it will break the sync

### Expected behavior

It should switch to the default value but not break everything

### Logs
```
2023-11-07 22:31:28,723 INFO sync-metadata.tables :: Found new tables: (Table  'public.orders' Table  'public.feedback' Table  'public.analytic_events' Table  'public.accounts' Table  'public.people' Table  'public.products' Table  'public.reviews' Table  'public.invoices')
2023-11-07 22:31:28,724 WARN sync.util :: Error creating/reactivating tables for postgres Database 2 'pg'
java.lang.IllegalArgumentException: No method in multimethod 'name->human-readable-name' for dispatch value: :disabled
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at metabase.models.humanization$name__GT_human_readable_name.invokeStatic(humanization.clj:37)
	at metabase.models.humanization$name__GT_human_readable_name.invoke(humanization.clj:23)
	at metabase.models.humanization$name__GT_human_readable_name.invokeStatic(humanization.clj:35)
	at metabase.models.humanization$name__GT_human_readable_name.invoke(humanization.clj:23)
	at metabase.sync.sync_metadata.tables$create_or_reactivate_table_BANG_.invokeStatic(tables.clj:118)
	at metabase.sync.sync_metadata.tables$create_or_reactivate_table_BANG_.invoke(tables.clj:96)
	at metabase.sync.sync_metadata.tables$fn__99107$create_or_reactivate_tables_BANG___99112$fn__99113.invoke(tables.clj:132)
	at metabase.sync.sync_metadata.tables$fn__99107$create_or_reactivate_tables_BANG___99112.invoke(tables.clj:125)
	at metabase.sync.sync_metadata.tables$fn__99361$sync_tables_and_database_BANG___99370$fn__99373$fn__99386.invoke(tables.clj:204)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
	at metabase.sync.sync_metadata.tables$fn__99361$sync_tables_and_database_BANG___99370$fn__99373.invoke(tables.clj:202)
	at metabase.sync.sync_metadata.tables$fn__99361$sync_tables_and_database_BANG___99370.invoke(tables.clj:180)
	at metabase.sync.sync_metadata$make_sync_steps$fn__100372.invoke(sync_metadata.clj:47)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__62954$run_step_with_metadata__62959$fn__62963$fn__62965.doInvoke(util.clj:380)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)
	at metabase.sync.util$fn__62954$run_step_with_metadata__62959$fn__62963.invoke(util.clj:375)
	at metabase.sync.util$fn__62954$run_step_with_metadata__62959.invoke(util.clj:370)
	at metabase.sync.util$fn__63181$run_sync_operation__63186$fn__63187$fn__63195.invoke(util.clj:486)
	at metabase.sync.util$fn__63181$run_sync_operation__63186$fn__63187.invoke(util.clj:484)
	at metabase.sync.util$fn__63181$run_sync_operation__63186.invoke(util.clj:478)
	at metabase.sync.sync_metadata$fn__100383$sync_db_metadata_BANG___100388$fn__100389$fn__100390.invoke(sync_metadata.clj:60)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__48142.invokeStatic(driver.clj:693)
	at metabase.driver$fn__48142.invoke(driver.clj:693)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__62874.invoke(util.clj:140)
	at metabase.sync.util$with_db_logging_disabled$fn__62871.invoke(util.clj:131)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__62858.invoke(util.clj:116)
	at metabase.sync.util$with_sync_events$fn__62853.invoke(util.clj:90)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__62843.invoke(util.clj:69)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:183)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:180)
	at metabase.sync.sync_metadata$fn__100383$sync_db_metadata_BANG___100388$fn__100389.invoke(sync_metadata.clj:59)
	at metabase.sync.sync_metadata$fn__100383$sync_db_metadata_BANG___100388.invoke(sync_metadata.clj:55)
	at metabase.api.database$fn__109288$fn__109289.invoke(database.clj:983)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-11-07 22:31:28,725 INFO sync-metadata.tables :: Updating description for tables: (Table  'public.feedback' Table  'public.people' Table  'public.orders' Table  'public.accounts' Table  'public.invoices' Table  'public.reviews' Table  'public.products' Table  'public.analytic_events')
```
### Information about your Metabase installation
It's been like this forever

### Severity

P3

### Additional context

Seems like correct values are here https://github.com/metabase/metabase/issues/14521#issuecomment-767568072

### PR DESCRIPTION
**Pull request by rafpaf**
Closes https://github.com/metabase/metabase/issues/35469

### Description

We support two values for `MB_HUMANIZATION_STRATEGY`: `simple` and `none`. With this PR, if any other value is used, we'll use `simple` and display a warning message. This ensures that if the user specifies a deprecated strategy like `advanced`, or a non-existent strategy like `disabled`, the app won't break - and the user will still be told that the value isn't supported.

### How to verify

Setting up a MB environment with `MB_HUMANIZATION_STRATEGY=disabled` throws an `java.lang.IllegalArgumentException` on master but not on this branch

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/models/humanization.clj [hunk 1]
```diff
@@ -82,10 +83,15 @@
...
   :getter     (fn []
-                (let [strategy (setting/get-value-of-type :keyword :humanization-strategy)]
-                  ;; actual advanced method has been excised. Use `:simple` instead if someone had specified
-                  ;; `:advanced`.
-                  (if (= strategy :advanced)
-                    :simple
-                    strategy)))
+                (let [strategy (setting/get-value-of-type :keyword :humanization-strategy)
+                      valid-values (set (keys (methods u.humanization/name->human-readable-name)))
+                      strategy-is-valid (contains? valid-values strategy)
```
Comment (dpsutton) [inline src/metabase/models/humanization.clj:88]: clojure allows `?` in var names. `valid-strategy?` is probably a better name here

**Comment by dpsutton** [comment]
we should also write a test for this. in `metabase.models.humanization-test` something like

```clojure
(deftest invalid-strategies-default-to-simple
  (mt/with-temporary-raw-setting-values [humanization-strategy "invalid-choice"]
    (is (= :simple (humanization/humanization-strategy)))
    (is (= "Foo Bar" (humanization/name->human-readable-name "foo_bar")))))
```

This test currently fails for me with

```clojure
humanization-test=> (clojure.test/run-test invalid-strategies-default-to-simple)

Testing metabase.models.humanization-test

FAIL in (invalid-strategies-default-to-simple) (humanization_test.clj:67)

Setting :humanization-strategy = "invalid-choice"

expected: :simple
  actual: :invalid-choice
    diff: - :simple
          + :invalid-choice

ERROR in (invalid-strategies-default-to-simple) (MultiFn.java:156)

Setting :humanization-strategy = "invalid-choice"

expected: (= "Foo Bar" (humanization/name->human-readable-name "foo_bar"))
  actual: java.lang.IllegalArgumentException: No method in multimethod 'name->human-readable-name' for dispatch value: :invalid-choice
```

File: src/metabase/models/humanization.clj [hunk 2]
```diff
@@ -82,10 +83,15 @@
...
-                (let [strategy (setting/get-value-of-type :keyword :humanization-strategy)]
-                  ;; actual advanced method has been excised. Use `:simple` instead if someone had specified
-                  ;; `:advanced`.
-                  (if (= strategy :advanced)
-                    :simple
-                    strategy)))
+                (let [strategy (setting/get-value-of-type :keyword :humanization-strategy)
+                      valid-values (set (keys (methods u.humanization/name->human-readable-name)))
+                      valid-strategy? (contains? valid-values strategy)
+                      ]
```
Comment (noahmoss) [inline src/metabase/models/humanization.clj:89]: nit: this should go on the previous line

File: src/metabase/models/humanization.clj [hunk 3]
```diff
@@ -82,10 +83,15 @@
...
   :getter     (fn []
-                (let [strategy (setting/get-value-of-type :keyword :humanization-strategy)]
-                  ;; actual advanced method has been excised. Use `:simple` instead if someone had specified
-                  ;; `:advanced`.
-                  (if (= strategy :advanced)
-                    :simple
-                    strategy)))
+                (let [strategy (setting/get-value-of-type :keyword :humanization-strategy)
+                      valid-values (set (keys (methods u.humanization/name->human-readable-name)))
+                      valid-strategy? (contains? valid-values strategy)
```
Comment (noahmoss) [inline src/metabase/models/humanization.clj:88]: nit: sets can be used as functions which look up their value, or return `nil` if the value doesn't exist. I think it's actually slightly more idiomatic in clojure to just do `(valid-values strategy)` here, since any non-nil value will be truthy.

File: src/metabase/models/humanization.clj [hunk 4]
```diff
@@ -82,10 +83,15 @@
...
+                      ]
+                  (cond
+                    (and (= strategy :advanced) valid-strategy?) :simple
+                    valid-strategy? strategy
+
+                    :else
+                    (do (log/warn (u/format-color :yellow "Invalid humanization strategy '%s'" strategy))
+                        :simple ))))
```
Comment (noahmoss) [inline src/metabase/models/humanization.clj:96]: I think it might be a little clearer to do the warning up front. Just reduces the number of logic branches a bit.
```suggestion
                  (when (not valid-strategy?) (log/warn ...)
                  (if valid-strategy? strategy :simple)
```

File: src/metabase/models/humanization.clj [hunk 5]
```diff
@@ -82,10 +83,15 @@
...
   :audit      :raw-value
   :getter     (fn []
-                (let [strategy (setting/get-value-of-type :keyword :humanization-strategy)]
-                  ;; actual advanced method has been excised. Use `:simple` instead if someone had specified
-                  ;; `:advanced`.
-                  (if (= strategy :advanced)
-                    :simple
-                    strategy)))
+                (let [strategy (setting/get-value-of-type :keyword :humanization-strategy)
+                      valid-values (set (keys (methods u.humanization/name->human-readable-name)))
```
Comment (noahmoss) [inline src/metabase/models/humanization.clj:87]: How about we exclude `:advanced` from `valid-values` as well? It hasn't been supported for a long time and the implementation of `name->human-readable-name` just defaults to `:simple`. So if someone is trying to set `:advanced` they should probably also see an error.

**Review by noahmoss — CHANGES_REQUESTED** [review]
Great start but I have a few style comments. Requesting changes for treating `:advanced` as an invalid value as well and also log a warning.

File: src/metabase/models/humanization.clj (hunk 5 above)
Comment (rafpaf) [reply src/metabase/models/humanization.clj:87]: While `:advanced` hasn't been used for while, we've been silently converting it to `:simple` without warning the user. Do you think it would make sense to begin now to regard `:advanced` as an invalid humanization strategy - and make sure users know that this may break their installation (if, somehow, they've still got the humanization strategy set to `:advanced`)? I'm not sure what our policy is on deprecating features.

Comment (noahmoss) [reply src/metabase/models/humanization.clj:87]: Isn't the behavior in this PR treating invalid values as `:simple` as well, and just logging a warning? I'm just suggesting we should do the same for `:advanced`. So still coerce it to `:simple` like all other invalid values, and also log a warning that it's invalid. Shouldn't break anyone's installation.

Or am I misunderstanding the behavior here?

File: src/metabase/util/humanization.cljc [hunk 6]
```diff
@@ -41,9 +41,3 @@
 (defmethod name->human-readable-name :none
   [_strategy s]
   s)
-
-;;; `:advanced` doesn't exist anymore, it used to be super fancy and do neat things. On the off chance someone still
-;;; tries to use it, just do the same thing `:simple` does.
-(defmethod name->human-readable-name :advanced
-  [strategy s]
-  ((get-method name->human-readable-name :simple) strategy s))
```
Comment (rafpaf) [inline src/metabase/util/humanization.cljc:49]: @noahmoss Removing this per your suggestion. Could you sanity check this decision? I don't know the whole context of our cljc files, and don't know if somehow some other process might invoke this, expecting `:advanced` to be supported.

Comment (noahmoss) [reply src/metabase/util/humanization.cljc:49]: Makes sense to me

**Review by noahmoss — APPROVED** [review]
Looks good!

File: src/metabase/models/humanization.clj (hunk 5 above)
Comment (noahmoss) [reply src/metabase/models/humanization.clj:87]: Sorry, should have said "warning"
