### PR TITLE
Fix ObjectDrill on queries with joined tables

### LINKED ISSUE #27094: Links for the IDs are showing wrong objects when table join is in place
**Describe the bug**
After creating a question that includes table joins, Links in the result table are referencing the wrong objects or the objects that do not exist.

This is reproducible in both our deployments (staging and prod)

**Logs**
There is no error in the javascript console.

**To Reproduce**
1. Create a new question that includes table joins
2. Click on the ID of the object to see its details
3. See the error

**Expected behavior**
After clicking on the object ID to see its details, proper object details are shown.

**Screenshots**

Notification_Center-2
On clicking on the another ID
Zrzut ekranu 2022-12-8 o 23 15 14
Used question
Zrzut ekranu 2022-12-8 o 23 53 56

**Information about your Metabase Installation:**
Hosted in AWS ECS using Fargate
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.17+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.17",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.17+8",
    "os.name": "Linux",
    "os.version": "4.14.294-220.533.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-12-07",
      "tag": "v0.45.1",
      "branch": "release-x.45.x",
      "hash": "019d31c"
    },
    "settings": {
      "report-timezone": "US/Central"
    }
  }
}
```

**Severity**
This issue is annoying to people who are working on the reporting, and it makes research harder. This tool is used mostly by non-technical staff, and they've started complaining about that tool, and they are asking for a replacement.

**Additional context**
This issue has been observed in version 0.44.x, which we started from.

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/27094
Reproduces https://github.com/metabase/metabase/issues/27094

### Description

Joined questions with 1 PK from the source table and >0 PK from the joined table did show the correct ObjectDetail view when the PK from the source table got clicked. The previous logic ignored to which tables PKs belong so it considered that the row cannot be identified by a single value since there are multiple PKs even though there is only a single PK in the source table.

This PR adds consideration of table columns when searching for primary keys.
- https://github.com/metabase/metabase/pull/28076/files#diff-2fc40467e8370b516c4ce51320cd4d159278808493231640527a65f51d06e65aR154
- https://github.com/metabase/metabase/pull/28076/files#diff-d398b83ed4884463296bff30877810bde5f8c222529606d995616d088918dcd2R58

#### Related but not fixed here issues

The following issues did exist before and this PR does not fix them:

- Columns from nested queries do not have table_id set which should be `card__*number*` in this case so joining nested questions still hasn't been fixed
- Clicking on PK of a joined table does not work correctly. On `master` it uses the joined table PK value for the source table PK which was completely wrong

### How to verify

1. New question -> Sample Dataset -> Orders join Products
2. Click visualize
3. Click on the `ID` column of the Orders table and ensure the object detail is correct
4. You can try doing so with UUID columns as it is described in the original issue but is no different

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### Demo

<video src="https://user-images.githubusercontent.com/14301985/216737640-9b4db8d8-d8fd-4ab3-9e31-b75e55e89e8e.mov" />

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/ObjectDetail/utils.ts [hunk 1]
```diff
@@ -76,22 +79,19 @@ export const getDisplayId = ({
...
 
 export const getIdValue = ({
   data,
-  zoomedRowID,
+  tableId,
 }: GetIdValueArgs): ObjectId | null => {
   if (!data) {
     return null;
   }
-  if (zoomedRowID) {
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/ObjectDetail/utils.ts:89]: This argument was never passed except for specs 🤔

File: frontend/src/metabase/query_builder/selectors.js [hunk 2]
```diff
@@ -139,18 +139,25 @@ export const getFirstQueryResult = createSelector([getQueryResults], results =>
...
-  result => {
+  [getFirstQueryResult, getTableId],
+  (result, tableId) => {
     if (!result) {
       return;
     }
     const { cols } = result.data;
-    const hasMultiplePks = cols.filter(isPK).length > 1;
+
+    const hasMultiplePks =
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/selectors.js:154]: One thing in the original code that at first took me in a not-ideal direction to solve this was that `hasMultiplePks` alone was not clear if it was about a question or a table.

Now it's sure clearer because we have the word `table` in `getIsPKFromTablePredicate` and its arg `tableId`.

It might me enough.

Or maybe we want to be even more clear that the whole check is also about a table and not a question by renaming `hasMultiplePks` something like `tableHasMultiplePks`

Maybe also renaming the selector `getPKColumnIndex` something like `getTablePKColumnIndex`.

I don't know if these things are already clear enough to most people, but thinking from the root cause of this issue, I'd think they weren't clear enough.

**Review by gusaiani — COMMENTED** [review]
What did you think of using these 2 e2e tests?

https://github.com/metabase/metabase/pull/27934/files#diff-d1bf75a5b297fd8e562ae4d746fa25f990bf6cc078c4869211dc194c4e1d5a7dR184-R248

The fix is wonderfully independent from column settings in a question, but maybe this will catch future changes that break the independence, and QB is full of these possibilities.

**Review by gusaiani — COMMENTED** [review]
Overall this approach is looking really great, thank you Sasha.

Agree that going for this scope of a fix is good, and the fix is super clean.

Left a couple of minor comments, would be great to see what Anton and Ryan have to say as well.

Thanks very much!

**Review by gusaiani — COMMENTED** [review]
We've changed the criteria for PKs.

Is there any situation at all where a _table_ can have more than one primary key, perhaps in some particular db engine or situation?

If not, is it right to ask if we should remove code treating for multiple or non-existing PKs in a table in selector functions:

getPKColumnIndex
getPKRowIndexMap

?

These selectors seem to only be used in the context of object detail.

Considering object detail is only reachable by clicking on some primary key, and assuming a table can only have a single primary key.

**Comment by alxnddr** [comment]
@gusaiani thanks for reviewing! I copied one spec from your PR that tests joined tables. I think other specs are not relevant since the column order is not affecting and should not affect the logic.

Having composite primary keys is pretty common and all DB engines support that. I mentioned the case with composite keys [here](https://github.com/metabase/metabase/pull/27934#issuecomment-1416593383)

**Comment by gusaiani** [comment]
> composite primary keys is pretty common 

Gotcha, these count in this context. Thanks.

**Review by gusaiani — APPROVED** [review]
Thank you very much, Sasha.

**Comment by krschacht** [comment]
Yay! I was the one who reported this. I'm a paid customer with a subscription that I access through metabaseapp.com. However, I'm still seeing the issue on there.

File: frontend/test/metabase/scenarios/visualizations/object_detail.cy.spec.js [hunk 3]
```diff
@@ -8,30 +8,59 @@ import {
...
+        ],
+      },
+    };
+
+    cy.createQuestion(questionDetails, { visitQuestion: true });
+
+    drillPK({ id: 1 });
+
+    cy.findByTestId("object-detail").within(() => {
+      cy.get("h2").should("contain", "Order").should("contain", 1);
```
Comment (nemanjaglumac) [inline frontend/test/metabase/scenarios/visualizations/object_detail.cy.spec.js:60]: @alxnddr I didn't see this on time, so forgive me for the late reply.

Please do not use selectors like `h2`. That's very brittle.
You can use `cy.findByRole("heading")` instead.

Comment (nemanjaglumac) [reply frontend/test/metabase/scenarios/visualizations/object_detail.cy.spec.js:60]: Also, wasn't this supposed to be reproduced with uuid?
I've tried to reproduce it with the Sample Database originally but wasn't able to.

**Comment by nemanjaglumac** [comment]
> However, I'm still seeing the issue on there.

@krschacht can you please give us a bit more details so that we can go back and fix this properly?

**Comment by paoliniluis** [comment]
Hi @krschacht , please contact us at the support email. Thanks!

File: frontend/test/metabase/scenarios/visualizations/object_detail.cy.spec.js (hunk 3 above)
Comment (alxnddr) [reply frontend/test/metabase/scenarios/visualizations/object_detail.cy.spec.js:60]: @nemanjaglumac the issue is not related to the column type
