### PR TITLE
Remapping endpoint checks for common remapping definitions

### LINKED ISSUE #47951: Linking a dashboard filter to multiple dashboard tiles, and viewing as a grouped user causes entity keys to appear in the dropdown filter in place of entity names.
### Describe the bug

When viewing a dashboard with a filter that is linked to multiple questions as a users with grouped permission access, the filters display entity keys rather than entity names.

### To Reproduce

1. Create a new permission group and give it "Can view" access to the "Accounts", "Feedback" and "Invoices" sample database tables.

Screenshot 2024-09-16 134807

2. Verify that the "Account ID" fields within the "Feedback" and "Invoices" tables are linked to "Accounts -> ID", that "filtering on this field" is set to "a list of all values" and that the display value is set to "Use foreign key-> First Name"

Screenshot 2024-09-16 134859

3. Create a new user and assign it to the group created in step 1 (don't log into it yet).

Screenshot 2024-09-16 135344

4. Create a new collection (and allow the user created in step 3 "View" access), and create two simple GUI questions against the Feedback and Invoices tables.

image

5. Create a new dashboard, and add The Feedback and Invoices questions created in step 4. Add a new "ID" filter and link it to the "Invoices.Account ID" field.

Screenshot 2024-09-16 135144

6. Log into the account you created in step 3, and verify that the filter correctly loads the first names.

Screenshot 2024-09-16 135213

7. Log back into the admin account, unlink the "ID" filter from the Invoices question, and link it to the "Feedback.Account ID" field.

Screenshot 2024-09-16 135233

8. Log back into the account you created in step 3, and verify that the filter still correctly loads the first names.

Screenshot 2024-09-16 135243

9. At this point, we have verified that the filter works correctly when assigned to either the Invoices or Feedback questions. But, now log back into the admin account, and assign the "ID" filter to **both** the "Invoices.Account ID" and Feedback.Account ID" fields together.

Screenshot 2024-09-16 135251

10. Log back into the account you created in step 3, and you will now find that the filter displays a list of entity keys rather than entity names.

Screenshot 2024-09-16 135310

### Expected behavior

When a filter is linked to multiple fields on multiple tiles, the entity names should still display in the filter dropdown when viewed as a user with grouped permission access.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2024-09-10",
      "tag": "v1.50.25",
      "hash": "473a7ca"
    },
    "settings": {
      "report-timezone": "Europe/London"
    },
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.39-0ubuntu0.22.04.1"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.5.0-1023-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

High

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by galdre**
Closes https://github.com/metabase/metabase/issues/47951

### Description

This PR fixes a bug where dashboard filters linked to multiple fields would show entity keys instead of remapped entity names when viewed by users with grouped (limited) permissions. 

The core problem was in the use of chain filter for multi-field dashboard parameters. When a dashboard filter was mapped to multiple fields (e.g., both `invoices.account_id` and `feedback.account_id`) that were foreign keys to the same target, the system switched to returning remappings defined for that target.

The reason we could not reproduce 47951 exactly as originally described is that the target in question (Account ID) by default has the exact same remapping defined, so it looked like it was working just fine with that example!

The solution in this PR is to add support for explicit remapping field specification:
- Added `find-common-remapping-target` function to detect when all fields corresponding to a parameter share the same display field
- Enhanced `chain-filter` to accept a `:remapping-field` option for explicit remapping control  
- When multiple fields have a common remapping target, we now explicitly tell the chain filter which field to use for display values

**Bonus Fix**: Also resolved a separate permissions caching bug in `data_permissions.clj` where the `use-cache?` logic was inverted. Cached permissions leaking from one test to another was causing utter havoc on the new backend tests for this issue. Disabling the cache didn't work, for two different reasons: (1) the previous implementation ignored the cache-disabling flag based on checking who the current user was; (2) the boolean flag was incorrectly negated -- attempting to disable the cache would **ensure** it was used.

### How to verify

1. Set up permissions: Give Data group "Can view" access but "No" query access to Sample Database
2. Configure field remappings: Set up `Orders.Product ID` and `Reviews.Product ID` to both display as `Products.Title`
   - Set both Product ID fields to have field values as "list"  
   - Create external dimension for both fields pointing to `Products.Title`
3. Create a dashboard with two questions: one from Orders table, one from Reviews table
4. Add an ID parameter to the dashboard
5. Map the parameter to BOTH `Orders.Product ID` and `Reviews.Product ID` fields, create a default value
6. Log in as a normal user 
7. Visit the dashboard and verify:
   - Filter shows product names (e.g., "Rustic Paper Wallet"), not just product IDs
   - Both in the default values and dropdown options
   - No raw entity keys are visible

The fix ensures that even with multiple field mappings, the remapped values are correctly displayed for users with limited permissions.

### Demo

_The existing e2e test `issue 47951` has been re-enabled and now passes._

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
  - Added regression test for new `use-cache?` helper function
  - Enabled existing e2e test for [issue #47951](https://github.com/metabase/metabase/issues/47951)
  - Added test coverage for multi-field dashboard parameter scenarios

### CODE REVIEW

**Review by ranquild — COMMENTED** [review]
FE lgtm

File: src/metabase/parameters/chain_filter.clj [hunk 1]
```diff
@@ -605,10 +605,15 @@
   (assert (even? (count options)))
   (let [{:as options}         options
         relax-fk-requirement? (:relax-fk-requirement? options)
-        options               (dissoc options :relax-fk-requirement?)
+        remapping-field       (:remapping-field options)
```
Comment (metamben) [inline src/metabase/parameters/chain_filter.clj:615]: The docstring should mention this.

File: test/metabase/permissions/test_util.clj [hunk 2]
```diff
@@ -132,12 +132,28 @@
...
+
 (defmacro with-perm-for-group-and-table!
   "Sets the data permission for the test dataset and specified table to the given value for the given permission group
   and runs `body` in that context."
   [group-or-id table-or-id perm-type value & body]
   `(do-with-perm-for-group-and-table! ~group-or-id ~table-or-id ~perm-type ~value (fn [] ~@body)))
 
+(defmacro with-perms-for-group-and-tables!
+  "Sets the data permission for the test dataset and specified tables to the given values for the given permission
+  groups, running `body` in that context."
```
Comment (metamben) [inline test/metabase/permissions/test_util.clj]: Should this read
```suggestion
  group, running `body` in that context."
```
?

File: test/metabase/permissions/test_util.clj [hunk 3]
```diff
@@ -132,12 +132,28 @@
...
+  [group-or-id table-or-id->perm-type->value & body]
+  `(do-with-perms-for-group-and-tables! ~group-or-id ~table-or-id->perm-type->value (fn [] ~@body)))
+
```
Comment (metamben) [inline test/metabase/permissions/test_util.clj:148]: Should the singular versions call the plural versions?

File: src/metabase/parameters/dashboard.clj [hunk 4]
```diff
@@ -144,6 +144,17 @@
...
       (fn [] (chain-filter dashboard param-key constraint-param-key->value query))))))
 
+(defn- find-common-remapping-target
+  "Check if ALL field-ids have identical remappings to the same display field.
+   Returns the common target field-id if ALL fields have the same remapping, nil otherwise."
+  [field-ids]
+  (let [target-field-ids (into #{}
+                               (map (comp :id chain-filter/remapping))
+                               field-ids)]
+    (when (and (not (target-field-ids nil))
```
Comment (metamben) [inline src/metabase/parameters/dashboard.clj]: `(target-field-ids nil)` looks like a complicated way of writing `nil`.
```suggestion
    (when (and (not (contains? target-field-ids nil))
```

This seems to be a case that has no tests.

File: src/metabase/parameters/dashboard.clj [hunk 5]
```diff
@@ -153,20 +164,33 @@
...
+         get-common-remapping #(when-let [common-display-field (find-common-remapping-target field-ids)]
+                                 (when-let [pk-field-id (custom-values/pk-of-fk-pk-field-ids field-ids)]
+                                   (chain-filter/chain-filter pk-field-id
+                                                              [{:field-id pk-field-id, :op :=, :value value}]
+                                                              :limit 1
+                                                              :remapping-field common-display-field)))
+         default-case-fn (fn dashboard-param-remapped-default-case []
+                           (-> (if (= (count field-ids) 1)
+                                 (get-direct-remapping) ; only one field id
+                                 (get-common-remapping)) ; more than one
```
Comment (metamben) [inline src/metabase/parameters/dashboard.clj:193]: Why aren't this inlined?

**Review by metamben — CHANGES_REQUESTED** [review]
Please resolve the `(target-field-ids nil)` issue. LGTM otherwise.

File: src/metabase/parameters/dashboard.clj (hunk 5 above)
Comment (galdre) [reply src/metabase/parameters/dashboard.clj:193]: I found it easier to read this way, especially with the more complex logic. It reduces the levels of nesting (stressing working memory less, keeping the main conditional focused on the 'what' (single field vs. multiple fields) while the named functions handle the 'how'. For me, this makes it easier to "[chunk](https://en.wikipedia.org/wiki/Chunking_(psychology))" the pieces and follow the control flow.

File: test/metabase/permissions/test_util.clj (hunk 3 above)
Comment (galdre) [reply test/metabase/permissions/test_util.clj:148]: Probably!

File: src/metabase/parameters/dashboard.clj (hunk 4 above)
Comment (galdre) [reply src/metabase/parameters/dashboard.clj]: The `"When only one FK field has remapping"` test case exercises this.

**Review by metamben — APPROVED** [review]
