### PR TITLE
Manage Table Metadata permission is enough to sync table schema

### LINKED ISSUE #64096: "Manage table metadata" permission is not enough to trigger sync/scan
### Describe the bug

Since v56 there is a button "Sync options" available in the Table Metadata page, where you are able to trigger syncs and scans of a table. However, you don't necessarily have permission to actually start a sync/scan because you need the "Manage database" permission.

Is this intended?

### To Reproduce

1. Create a database where you have "Manage table metadata" permission and not "Manage database".
2. Go to Table Metadata in Admin Settings.
3. Select a table in the database from 1).
4. Click sync options > Sync table schema or Re-scan table
5. Observe error "Failed to start sync" and response "You don't have permission to do that".

### Expected behavior

To be able to use all functionality in Table Metadata with "Manage table metadata" permission.

### Logs

_No response_

### Information about your Metabase installation

```JSON
- v1.56.4
- selfhosted with postgresql database
- datasource in database is BigQuery table
```

### Severity

Low severity, but a feature that would be very useful to us

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nvoxland**
closes #64096
### Description

Updates table `sync_schema` API to allow it to be called with `perms/manage-table-metadata`

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/warehouse_schema_rest/api/table.clj [hunk 1]
```diff
@@ -191,8 +192,8 @@
      (fn []
        (doseq [[db-id tables] (group-by :db_id newly-unhidden)]
          (let [database (t2/select-one :model/Database db-id)]
-           ;; it's okay to allow testing H2 connections during sync. We only want to disallow you from testing them for the
-           ;; purposes of creating a new H2 database.
+            ;; it's okay to allow testing H2 connections during sync. We only want to disallow you from testing them for the
```
Comment (edpaget) [inline src/metabase/warehouse_schema_rest/api/table.clj]: nit it'd be cool not to change this formatting unless its cljfmt doing it.

**Review by edpaget — APPROVED** [review]
