### PR TITLE
Bigquery - Ignore retry on query cancellation

### LINKED ISSUE #36623: Cancelled Queries are retried with Bigquery Driver
### Describe the bug

When a query is cancelled (either actively or by closing the page), the Bigquery driver will retry the query. 

### To Reproduce

1. Start a query with Bigquery
2. Cancel the query
3. Go to the Bigquery UI and check the project history, the query will have run two times.

### Expected behavior

A cancelled query should not be retried. The Bigquery driver already has the problem that it can not cancel running queries  (#32027). In addition to this the cancelled queries even gets called a SECOND time. This is especially a problem since often long running and thus expensive queries are the ones being cancelled.

### Logs

_No response_

### Information about your Metabase installation

```JSON
v0.47.2
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LarsKlingen**
Closes https://github.com/metabase/metabase/issues/36623 

### Description

Instead of retrying all types of exceptions, we only retry if its not a cancellation exception. 

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Run a (long running) query with Bigquery Conenctor
2. Cancel Query 
3. Verify in Bigquery Project history that only one query appears instead of two.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by darksciencebase** [comment]
Thank you for opening a PR! Have you looked into adding or updating tests to cover this change?

**Comment by LarsKlingen** [comment]
@darksciencebase I added some tests!

**Comment by LarsKlingen** [comment]
I realized that you get different results if you run all tests or only one test. I think it is because the `with-redefs` will overwrite the call in the db setup queries, if you run only one test instead of the query it wants to test. Thats why I added the condition to only mock the behaviour if its the specific test query.  

E.g. removing the retry mechanism the already existing test _retry-certain-exceptions-test_ will fail here:
`DRIVERS=bigquery-cloud-sdk clojure -X:dev:drivers:drivers-dev:test `

But not running like this:
`DRIVERS=bigquery-cloud-sdk clojure -X:dev:drivers:drivers-dev:test :only [metabase.driver.bigquery-cloud-sdk-test/retry-certain-exceptions-test`

**Comment by LarsKlingen** [comment]
@darksciencebase also fixed another problem that queries dont get cancelled. These two changes together can reduce a lot the slot usage when using Bigquery. Can someone help in giving feedback?

**Comment by darksciencebase** [comment]
@LarsKlingen yep, it's in the queue.

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj [hunk 1]
```diff
@@ -371,6 +371,30 @@
...
+  (mt/test-driver :bigquery-cloud-sdk
+    (let [fake-execute-called (atom false)
+          orig-fn        @#'bigquery/execute-bigquery]
+      (testing "Should not retry query on cancellation"
+        (with-redefs [bigquery/execute-bigquery (fn [^BigQuery client ^String sql parameters _ _]
+                                                  ;; We dont want to retry the db setup queries, so only retry if the query contains "cancel_test"
+                                                  (if (and (re-find #"cancel_test" sql) (not @fake-execute-called))
+                                                    (do (reset! fake-execute-called true)
+                                                        ;; Simulate a CancellationException being thrown
+                                                        (throw (java.util.concurrent.CancellationException. "Query cancelled")))
```
Comment (metamben) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:384]: According to the suggestion, this would have to throw an `ex-info` with `::bigquery/cancelled? true`.

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj [hunk 2]
```diff
@@ -371,6 +371,30 @@
...
           (is (true? @fake-execute-called)))))))
 
+(deftest not-retry-cancellation-exception-test
+  (mt/test-driver :bigquery-cloud-sdk
+    (let [fake-execute-called (atom false)
+          orig-fn        @#'bigquery/execute-bigquery]
+      (testing "Should not retry query on cancellation"
+        (with-redefs [bigquery/execute-bigquery (fn [^BigQuery client ^String sql parameters _ _]
+                                                  ;; We dont want to retry the db setup queries, so only retry if the query contains "cancel_test"
+                                                  (if (and (re-find #"cancel_test" sql) (not @fake-execute-called))
```
Comment (metamben) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:381]: I would prefer a string more specific than this. I'm fine with appending a random UUID or prefixing with the namespace or something similar.

**Review by metamben — CHANGES_REQUESTED** [review]
Looks good, thanks! 👍 

I have some minor/trivial requests and a suggestion, please have a look.

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 3]
```diff
@@ -265,24 +265,25 @@
           ;; as long as we don't set certain additional QueryJobConfiguration options, our queries *should* always be
           ;; following the fast query path (i.e. RPC)
           ;; check out com.google.cloud.bigquery.QueryRequestInfo.isFastQuerySupported for full details
-          res-fut (future (.query client (.build request) (u/varargs BigQuery$JobOption)))]
+          ;; Additional configuration here if needed
+          job-builder (-> (JobId/newBuilder)
+                                (.setRandomJob))
```
[the remark this answers is not in the document]
Comment (LarsKlingen) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj]: fixed

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 4]
```diff
@@ -265,24 +265,25 @@
...
             (reset! cancel-requested? true) ; signal the page iteration fn to stop
             (if-not (or (future-cancelled? res-fut) (future-done? res-fut))
-              ;; somehow, even the FIRST page hasn't come back yet (i.e. the .query call above), so cancel the future to
-              ;; interrupt the thread waiting on that response to come back
-              ;; unfortunately, with this particular overload of .query, we have no access to (nor the ability to control)
-              ;; the jobId, so we have no way to use the BigQuery client to cancel any job that might be running
-              (future-cancel res-fut)
-              (when (future-done? res-fut) ; canceled received after it was finished; may as well return it
+            (do (.cancel client job-id) ; Cancel running job before canceling task
+                (future-cancel res-fut))
```
[the remark this answers is not in the document]
Comment (LarsKlingen) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj]: fixed

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj [hunk 5]
```diff
@@ -371,6 +371,30 @@
...
+            (qp/process-query {:native {:query "SELECT CURRENT_TIMESTAMP() AS cancel_test"} :database (mt/id)
+                               :type     :native})
+            ;; If no exception is thrown, then the test should fail
+            (is false "Query should have failed")
+            (catch clojure.lang.ExceptionInfo e
+              ;; Verify exception as expected
+              (is (= "Query cancelled" (.getMessage e)))
+              ;; make sure that the fake exception was thrown
+              (is (true? @fake-execute-called))))))))
+)
```
[the remark this answers is not in the document]
Comment (LarsKlingen) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj]: fixed

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj (hunk 1 above)
Comment (LarsKlingen) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj]: fixed

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj (hunk 2 above)
Comment (LarsKlingen) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj]: I used the full test name now as the string

**Comment by LarsKlingen** [comment]
thanks for your suggestions @metamben

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 6]
```diff
@@ -353,7 +353,7 @@
       (thunk)
       (catch Throwable e
         (let [ex-data (u/all-ex-data e)]
-          (if (or (:retryable? e) (not (qp.error-type/client-error? (:type ex-data))))
+          (if (and not (::cancelled? ex-data) (or (:retryable? e) (not (qp.error-type/client-error? (:type ex-data)))))
```
Comment (metamben) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:356]:
```suggestion
          (if (and (not (::cancelled? ex-data))
                   (or (:retryable? e) (not (qp.error-type/client-error? (:type ex-data)))))
```

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj [hunk 7]
```diff
@@ -371,6 +371,29 @@
...
+      (testing "Should not retry query on cancellation"
+        (with-redefs [bigquery/execute-bigquery (fn [^BigQuery client ^String sql parameters _ _]
+                                                  ;; We only want to simulate exception on the query that we're testing and not on possible db setup queries
+                                                  (if (and (re-find #"not-retry-cancellation-exception-test" sql) (not @fake-execute-called))
+                                                    (do (reset! fake-execute-called true)
+                                                        ;; Simulate a cancellation happening
+                                                        (throw (ex-info "Query cancelled" {::cancelled? true})))
+                                                    (orig-fn client sql parameters nil nil)))]
+          (try
+            (qp/process-query {:native {:query "SELECT CURRENT_TIMESTAMP() AS not-retry-cancellation-exception-test"} :database (mt/id)
```
Comment (metamben) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:387]: It's unusual to having dashes in names without quoting, I wonder if this works...

**Review by metamben — CHANGES_REQUESTED** [review]
Thanks for the changes! 
A pair of parentheses are missing.

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 8]
```diff
@@ -351,6 +352,9 @@
                                                  cancel-requested?))]
     (try
       (thunk)
+      (catch java.util.concurrent.CancellationException _e
+        ;; Handle cancellation exception without retrying
+        (throw (ex-info (tru "Query cancelled") {:sql sql :parameters parameters})))
       (catch Throwable e
         (let [ex-data (u/all-ex-data e)]
           (if (or (:retryable? e) (not (qp.error-type/client-error? (:type ex-data))))
```
[the remark this answers is not in the document]
Comment (metamben) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj]: I was suggesting fixing  `(:retryable? e)` -> `(:retryable? ex-data)` too.

[the remark this answers is not in the document]
Comment (LarsKlingen) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj]: sorry, adjusted now

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj (hunk 7 above)
Comment (LarsKlingen) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj]: Adjusted it since its indeed unusual

**Comment by LarsKlingen** [comment]
To make the test work I had to explcitly set the namespace in the mock exception since its another namespace. Not sure this is the best way to do it

File: modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj [hunk 9]
```diff
@@ -371,6 +371,29 @@
...
+  (mt/test-driver :bigquery-cloud-sdk
+    (let [fake-execute-called (atom false)
+          orig-fn        @#'bigquery/execute-bigquery]
+      (testing "Should not retry query on cancellation"
+        (with-redefs [bigquery/execute-bigquery (fn [^BigQuery client ^String sql parameters _ _]
+                                                  ;; We only want to simulate exception on the query that we're testing and not on possible db setup queries
+                                                  (if (and (re-find #"notRetryCancellationExceptionTest" sql) (not @fake-execute-called))
+                                                    (do (reset! fake-execute-called true)
+                                                        ;; Simulate a cancellation happening
+                                                        (throw (ex-info "Query cancelled" {:metabase.driver.bigquery-cloud-sdk/cancelled? true})))
```
Comment (metamben) [inline modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj:384]:
```suggestion
                                                        (throw (ex-info "Query cancelled" {::bigquery/cancelled? true})))
```

Comment (LarsKlingen) [reply modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj]: Sorry, didnt see you already suggested like this. Im new to Clojure and missing to pay attention to some of the details. Passed the test like this!

**Comment by metamben** [comment]
This looks good, thank you! I'm running the full test suite and we'll merge your PR when all tests pass.

**Comment by metamben** [comment]
@LarsKlingen the tests are consistently failing at https://github.com/metabase/metabase/actions/runs/7225869362/job/19736615187?pr=36780#step:3:1671. The underlying cause seems to be that the way we try to control the page size doesn't work and first page gets all the results instead of the expected 1000.

**Comment by metamben** [comment]
> For now I can remove the query cancellation part and only leave the part to ignore retries. It would already help in reducing slot usage. And then maybe discuss the query cancellation further in a new issue or this one #32027, what do you think?

Separating the two issues sounds good to me. 👍 

The "slow" vs "fast" RPC path issue needs a more thorough analysis, we have to understand the implications of that.

**Comment by LarsKlingen** [comment]
I undid the changes and brought the discussion to #32027

**Review by metamben — APPROVED** [review]
Looks good, thank you! The PR mirroring this has passed the tests, we'll merge your PR.
