### PR TITLE
Handle clickhouse dbname when it has spaces in it

### LINKED ISSUE #70798: New Clickhouse driver v9.7.0 breaks connection with Invalid URL when Enable multiple databases is enabled - 59.2
### Describe the bug

I cannot replicate but seems that old Instance that upgraded to 59.2 and have Enable multiple databases the list of the databases is getting added to the URL

```
Not a valid URL 'jdbc:clickhouse://abcdef.eu-central-1.aws.clickhouse.cloud:8443/production (http://abcdef.eu-central-1.aws.clickhouse.cloud:8443/production) metabase'.
```

### To Reproduce

more context here with step by step flow

https://metaboat.slack.com/archives/C013N8XL286/p1773317759733969

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
Not a valid URL 'jdbc:clickhouse://abcdef.eu-central-1.aws.clickhouse.cloud:8443/production (http://abcdef.eu-central-1.aws.clickhouse.cloud:8443/production) metabase'.
```

### Severity

Blocks connections

### Additional context

There seems to be a workaround 

1. Disable “Enable multiple databases”
2. Reconnect Metabase to a single database (remove the weird list that is visible in the default)
3. Re-enable multiple databases
4. Re‑enter the database list again

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/70798

### Description

Old clickhouse `dbname` can have spaces in them, so we can't pass it directly to the jdbc spec. Instead we need to parse out the first db name. 

### How to verify

1. Create a clickhouse db connection
2. Manually update the db details so that there is a `dbname` field with spaces in it
3. You should still be able to connect and sync

### Demo

https://www.loom.com/share/824be69a7c7241f2b5c91dd215820c1e

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: modules/drivers/clickhouse/src/metabase/driver/clickhouse.clj [hunk 1]
```diff
@@ -140,7 +143,8 @@
       ;; Default SELECT 1 is not enough for Metabase test suite,
       ;; as it works slightly differently than expected there
       (let [spec  (sql-jdbc.conn/connection-details->spec driver details)
-            db    (ddl.i/format-name driver (or (:dbname details) (:db details) "default"))]
+            dbname (not-empty (first (str/split (str/trim (or (:dbname details) "default")) #" ")))
```
Comment (rileythomp) [inline modules/drivers/clickhouse/src/metabase/driver/clickhouse.clj]: This is test code

**Review by metamben — APPROVED** [review]
