### PR TITLE
Normalize virtual card table fields using its `table_id` and `id`

### LINKED ISSUE #25141: our schema identifies fields by `id` alone, so the fields on virtual card tables get clobbered by the fields from concrete tables
**Describe the bug**
- the metadata on a Table coming from a `/api/table/card__123/query_metadata` GET may be specific to the given card if the card is a Model or based on a Model
- our normalizr `FieldSchema` identifies field objects via their `id` property, so fields shared between card__123 tables and concrete tables are seen as identical
- these fields clobber each other in our store, depending on the order of the requests we make for table metadata

**To Reproduce**
1. Created a question (Q1) based on the Products table.
2. Make it a Model and change the names of columns
3. Create a question (Q2) based on the model
4. Refresh the page
5. Using Redux dev tools, inspect how entities are stored and see that we store the Fields for Model tables in the same location as the Fields coming from concrete Tables.

**Expected behavior**
We should hold onto both fields somehow. Or at least hold onto the metadata that is unique to a given nested card table.

**Severity**
P2 -- it is the root cause for a number of the Models bugs we are seeing.

### PR DESCRIPTION
**Pull request by daltojohnso**
Fixes https://github.com/metabase/metabase/issues/25141

`normalizr` docs: https://github.com/paularmstrong/normalizr/blob/master/docs/api.md

- I'm using the `idAttribute` config function on normalizr entities to create a unique `${table_id}:${id}` value for fields coming from virtual card tables.
- I'm using the `processStrategy` config function to add this unique identifier to the field object. I've named it `uniqueId`. This lets us avoid messing with the field's `id` property, which we frequently use directly to create field refs that go into mbql queries.
- I've updated the metadata selector code to use the `uniqueId` property for fields so that we avoid clobbering fields that share the same `id` value.
- I've updated the `Metadata` class `field` method to accept an optional `tableId` arg. Doing it this way helps avoid breaking existing code that calls `metadata.field(fieldId)` -- that'll work the same way. There are also scenarios (such as in admin data model code) where we don't need to use the second arg, anyways.
- I've updated one use of `metadata.field(fieldId)` to `metadata.field(fieldId, tableId)`, in some models code. There are other places where we use `metadata.field(fieldId)`, but I'm not totally certain which should be updated, so I'm leaving them alone for now. A small risk to this approach is that we fail to find any field where previously we would have. A fix might be to always fetch the base table of a Question, using the `card.table_id` property (I'm doing this anyway in https://github.com/metabase/metabase/pull/25109)
  - I'm also updating FieldDimension's usage of this function in PR #25109

Note that this doesn't fix all places where we are clobbering metadata because this PR does not update `FieldDimension.prototype.field`. I'm leaving that for https://github.com/metabase/metabase/pull/25109

**Testing**
This affects a lot of stuff. Try playing with...
- Create a question & click on column headers & mutate the underlying query (filters, drilldowns, etc.)
- Create a model & update the metadata of the model
- Create a question based on a model and see if its overrided metadata persists
- Add these questions to a dashboard and map field filter parameters to the fields and make sure things still work (ignore clobbering here)
- Make sure #22715 can't be repro'd 
- Same for https://github.com/metabase/metabase/issues/20419

### CODE REVIEW

File: frontend/test/__support__/sample_database_fixture.js [hunk 1]
```diff
@@ -34,8 +36,16 @@ function aliasTablesAndFields(metadata) {
   }
 }
 
+function normalizeFields(fields) {
```
Comment (daltojohnso) [inline frontend/test/__support__/sample_database_fixture.js:39]: The `metadata` object we pass to unit tests doesn't normalize things. I added this to normalize Fields specifically, but can add something more general if necessary.

File: frontend/test/metabase/scenarios/joins/joins.cy.spec.js [hunk 2]
```diff
@@ -188,7 +188,7 @@ describe("scenarios > question > joined questions", () => {
     cy.icon("add_data").click();
 
     enterCustomColumnDetails({
-      formula: "[Question 5 → Sum of Rating] / [Sum of Rating]",
+      formula: "[Question 5 → Sum of Rating] / [Sum of Total]",
```
Comment (daltojohnso) [inline frontend/test/metabase/scenarios/joins/joins.cy.spec.js:191]: If you look at the field this tests uses, it is actually `Sum of Total`. Not sure how it passed originally.

**Review by gusaiani — COMMENTED** [review]
Dalton, first thing I did to review was go to https://github.com/metabase/metabase/issues/25141

There I saw 

https://github.com/metabase/metabase/issues/25141#issuecomment-1233125376

and because of that tip, tried reproing 

https://github.com/metabase/metabase/issues/23019

under this very branch we're in here.

What I see now is the undesired behavior happening before and after a page reload.
Do you see something different?

**Comment by daltojohnso** [comment]
@gusaiani that issue is fixed if you look at https://github.com/metabase/metabase/pull/25109 (which is based on this branch). I was trying to split out PRs to keep things nice and small, but all of this code is very coupled, etc., as you know, so my plan is for these PRs to land together.

This PR alone probably doesn't change much, especially since I'm not updating `metadata.field(...)` here besides one spot.

File: frontend/src/metabase-lib/lib/metadata/Field.ts [hunk 3]
```diff
@@ -77,6 +78,19 @@ class FieldInner extends Base {
...
+    if (this.uniqueId) {
+      return this.uniqueId;
+    }
+
+    const uniqueId = getUniqueFieldId(this.getId(), this.table_id);
+    this.uniqueId = uniqueId;
+
+    return uniqueId;
+  }
+
```
Comment (kulyk) [inline frontend/src/metabase-lib/lib/metadata/Field.ts:93]: Should we maybe make it a [`getter` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get)?

**Review by kulyk — APPROVED** [review]
Awesome! 👏

**Review by gusaiani — APPROVED** [review]
Thank you very much, Dalton.
