### PR TITLE
[search] better search for CamelCased tables and dbs

### LINKED ISSUE #63995: Cannot do partial String match Search for Tables with camelCase Names anymore
### Describe the bug

We used to match substrings in the middle/end of a word when looking for tables and other content. Now it seems like we only match substring if there at the beginning or after a token (like an underscore). 

Context: We have tons of tables with camelCaseNames. We used to very commonly search for a word in the middle or end of the table name to get a list of tables. This doesn't work any more so we have to scroll through a massive list of things in the table browser or recall all of the prefixes for the tables they may care about.

### To Reproduce

Try to search for tables as described above. 

### Expected behavior

camelCase is a common naming convention and it feels like this should still work

### Logs

_No response_

### Information about your Metabase installation

```JSON
v55
```

### Severity

frustrating user experience to upgrade into

### Additional context

customer request

### PR DESCRIPTION
**Pull request by sansolovyov**
This PR adds ability to specify transformations to the text fields we're going to be using in search.

Fixes #63995

### CODE REVIEW

File: src/metabase/warehouse_schema/models/table.clj [hunk 1]
```diff
@@ -384,7 +384,9 @@
                   :view-count    true
                   :created-at    true
                   :updated-at    true}
-   :search-terms [:name :display_name :description]
+   :search-terms {:name         search.spec/camel-case
+                  :display_name nil
+                  :description  nil}
```
Comment (noahmoss) [inline src/metabase/warehouse_schema/models/table.clj]: The convention in the other maps in a search spec (like `:attrs`) is to use booleans to include/exclude specific fields, so my instinct was to assume that `nil` = "not included" even though it just means "no transform". Maybe `true` or `identity` would be clearer here to indicate "include with no transform"?

File: src/metabase/search/spec.clj [hunk 2]
```diff
@@ -390,3 +383,10 @@
 
   (let [where (-> (:model/ModelIndexValue (model-hooks)) first :where)]
     (insert-values where :updated {:model_index_id 1 :model_pk 5})))
+
+;;;; indexing helpers
+
+(defn camel-case
```
Comment (noahmoss) [inline src/metabase/search/spec.clj]: maybe `explode-camel-case` (or something) for clarity?

**Review by noahmoss — APPROVED** [review]

File: src/metabase/warehouse_schema/models/table.clj (hunk 1 above)
Comment (sansolovyov) [reply src/metabase/warehouse_schema/models/table.clj]: Ah, good idea; I don't know if there is a need to process `nil`s though, but I agree with `true` being more obvious.
