### PR TITLE
Make sunburst charts reflect colors set in the appearance tab

### LINKED ISSUE #68343: Sunburst Charts show Random Colors not the one you setup in the Appearance Tab
### Describe the bug

When i create a pivot the colors are random. The issue is only on Sunburst Charts. Normal Pie:

Image

Add a Sunburst layer:

Image

### To Reproduce

1. Go to Appearance and make sure to have a custom color scheme, this is mine for reference:

Image

2. Go to New -> Products -> Count Group by Category and Rating Binned:

Image

3. Build a Sunburst Chart and notice how the colors are completely off:

Image

### Expected behavior

The following is what you get when running the same replication on 57.8

Image

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
happens on 1.58.2 and also 57.9
```

### Severity

This was introduced recently cause previous versions don't have this issue. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevinkelleher12**
Closes #68343

### Description

There were two separate bugs here:

- Sunburst charts used to ignore colors set in the appearance tab completely - this was fixed by #68169
- The "application-colors" setting can save hex colors in upper or lowercase, but the sunburst chart code (namely `getColorForRing`) assumed it would always be saved in uppercase, which could cause unexpected results

#68169 introduced a separate issue, though. By calling `mapChartColorsToAccents(baseTheme.chartColors)` in `deriveFullMetabaseTheme`, it added color variants like "accent0-light" based on the base theme to the global `colors` object, where they weren't previously included.

Previously, users didn't have to set the light and dark variants in the appearance tab - they could pick only the base color and the light and dark variants would be calculated for them. So their `whitelabelColors` object might look like `{ accent0: "#123456"}`. 

However, since `colors` now includes the color variants, any code that is functionally equivalent to`{ ...colors, ...whitelabelColors }` is now wrong - the resulting object will include "accent0" from `whitelabelColors` but "accent0-light" from `colors`. This PR fixes that issue.

The change to `createColorGetter` changes some of the font colors in the SmartScalar loki tests. Updating the snapshots is the right approach, because the new snapshots actually reflect the correct font color used when sending a SmartScalar alert via email/slack.

### How to verify

Follow the steps in #68343

### Demo

Before (does not reflect appearance settings):
image

After:
image

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/lib/colors/derive-theme.ts [hunk 1]
```diff
@@ -38,12 +42,54 @@ export function deriveFullMetabaseTheme({
     ...PROTECTED_COLORS,
   );
 
+  const whitelabelAccentColors = Object.fromEntries(
+    Object.entries(whitelabelColors ?? {}).filter(([key]) =>
+      key.startsWith("accent"),
+    ),
+  );
+  const allWhitelabelAccentColors = Object.entries(
```
Comment (npfitz) [inline frontend/src/metabase/lib/colors/derive-theme.ts]: We had a quick call to chat about this, but just to write it down somewhere:
- For whitelabel colors, you can define up to 24 colors to use in charting. However, we don't require that you define a base color. If you choose to only define the light or dark variant of a color and leave the base to `auto`, we won't save that value in the BE, and we expect the FE to derive it at runtime
- A recent change made the assumption that light and dark variants are derived from the base color, and will always be present. so if accent2 was missing, we would always fall back to the default color, even if `accent2-dark` was defined.
- This logic takes your "at least 8 colors" and provides the full map of 24 values

Eventually, I was these chart / accent colors to not be part of the mantine theme, as they should only be used in charting and should not be used as css vars. But for now, I'd like if we can move this logic into it's own function with a comment saying what it's for, and why we need it for the time being

**Review by npfitz — CHANGES_REQUESTED** [review]
Awesome work untangling the color web @kevinkelleher12. I'll give it a ✅ once we get this logic in it's own function

**Review by npfitz — APPROVED** [review]
Looks good to me! Can we get someone from @metabase/embedding to just take a quick look and make sure we're not breaking anything on that side?

**Comment by npfitz** [comment]
Didn't notice that auto-merge was enabled 😅 .
