### PR TITLE
In notebook: clicking Visualize should only offer to save question if there are changes

### LINKED ISSUE #13470: Clicking Visualize in Notebook makes the question "dirty" even if no changes was made
**Describe the bug**
When clicking Visualize in Notebook editor, on an existing question, then the state gets "dirty" showing the possibility to "Save" the question, even though there isn't any changes.

**To Reproduce**
1. Simple question > Sample Dataset > Orders - save question
image
2. Click Notebook-editor (top-right), without making any changes, click Visualize
3. Now the question state is "dirty", with the option to save the question, but no new results are requested, so it's just the frontend state which is set to "dirty". If there were changes to the question, then it would also request `POST /api/dataset`.
image

**Expected behavior**
Only set question to "dirty" if there has been changes to the question.

**Information about your Metabase Installation:**
Metabase 0.35.0, 0.36.7, 0.37.0-rc2

**Additional context**
Related to #11994

### PR DESCRIPTION
**Pull request by jeff-bruemmer**
Fixes #13470: "Metabase shouldn't offer to save the question when there were no changes (metabase#13470)".

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/notebook/Notebook.jsx [hunk 1]
```diff
@@ -26,12 +27,18 @@ export default function Notebook({ className, ...props }) {
           primary
           style={{ minWidth: 220 }}
           onClick={async () => {
-            let cleanQuestion = question.setQuery(question.query().clean());
-            if (cleanQuestion.display() === "table") {
-              cleanQuestion = cleanQuestion.setDefaultDisplay();
+            // Only update the question if it's dirty, otherwise Metabase
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/components/notebook/Notebook.jsx:30]: This may be a great opportunity to move out the function currently inside the `onClick` prop.

So it would look roughly like 

```js
...
} = props;

function cleanupQuestion() {
…
}

return (
 ...
 onClick={cleanupQuestion}
 ...
)
```

Comment (jeff-bruemmer) [reply frontend/src/metabase/query_builder/components/notebook/Notebook.jsx]: Thanks @gus

**Review by gusaiani — APPROVED** [review]
Thank you @jeff-bruemmer, working nicely now, and code that much more understandable.
