### PR TITLE
Fix model metadata editing for SQL models with manually sorted columns

### LINKED ISSUE #42355: Database mapped field in model metadata shows None after mapping/saving
### Describe the bug

In a model's metadata, I edited a field to map the database field. It mapped, however it still shows None. 
Screenshot 2024-05-03 at 2 52 21 PM

### To Reproduce

1. Edit any model and map a field to a database field
2. Observe the mapping shows None even though it mapped and works. 

### Expected behavior

It should show the mapped field

### Logs

_No response_

### Information about your Metabase installation

```JSON
Master on Postgres
```

### Severity

Cosmetic

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/42355

How to verify:
- New -> SQL query -> `SELECT ID, USER_ID FROM ORDERS`
- Run the query -> Save
- Turn into model
- Edit metadata -> Select first column
- Database column this maps to -> Orders -> ID
- Make sure the selected column stays visible

Screenshot 2024-06-21 at 16 55 52

### CODE REVIEW

File: frontend/src/metabase-lib/v1/metadata/utils/models.ts [hunk 1]
```diff
@@ -171,29 +167,23 @@ function getFieldFromColumnVizSetting(
...
 
-  const orderedColumns = model.setting("table.columns");
-
-  if (!Array.isArray(orderedColumns)) {
+  const columnSettings = model.setting("table.columns");
+  if (!Array.isArray(columnSettings)) {
     return columnMetadata;
   }
 
-  const table = model.legacyQueryTable();
```
Comment (ranquild) [inline frontend/src/metabase-lib/v1/metadata/utils/models.ts:186]: Broken MLv1 logic that should not be used in the first place

**Review by kamilmielnik — APPROVED** [review]
