### PR TITLE
fix(sdk): Avoid portal root taking space under flex parents

### LINKED ISSUE #64578: [SDK] mb-wrapper for portal root container is occupying flex spaces on 57
The portal's root container is now occupying spaces where it wasn't before. When the `EditableDashboard` is rendered inside of a flex parent, the will dashboard renders only half the space as the `mb-wrapper` for `#metabase-sdk-portal-root` is rendering the other half:

Image

Setting this to P3 for now as it only happens in the master branch.

## How to reproduce

1. Render a flex container parent on top of an EditableDashboard, e.g.

```tsx
<div style={{ display: 'flex' }}>
  <EditableDashboard />
</div>
```

2. The dashboard should be render at only half the width, and the portal container should occupy the other half

### PR DESCRIPTION
**Pull request by WiNloSt**
closes #64578
Closes EMB-898

### Backport reasons
This is going directly to 57, so we should not backport this.

### Description
The problem was that after introducing hosted-bundle, we render necessary roots e.g. portal roots, popover roots within a certain Metabase component, from my testing it's the last element.

When such element is wrapped under `display: flex` parent, the portal root in particular will start to take space, so I remove it from the box model with `display: contents`

### How to verify
Render this snippet
```tsx
<div style={{ display: 'flex' }}>
  <EditableDashboard dashboardId={1} />
</div>
```

#### After
Screenshot 2025-10-28 at 5 17 41 PM

#### Before
Screenshot 2025-10-28 at 5 19 45 PM

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk-bundle/components/private/PublicComponentStylesWrapper.tsx [hunk 1]
```diff
@@ -1,36 +1,20 @@
...
 import { forwardRef } from "react";
 
 import { saveDomImageStyles } from "metabase/visualizations/lib/image-exports";
 
+import S from "./PublicComponentStylesWrapper.style.css";
+
 /**
  * Injects CSS variables and styles to the SDK components underneath them.
  * This is to ensure that the SDK components are styled correctly,
  * even when rendered under a React portal.
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk-bundle/components/private/PublicComponentStylesWrapper.tsx:14]: just a clean up

File: enterprise/frontend/src/embedding-sdk-bundle/components/private/PublicComponentStylesWrapper.tsx [hunk 2]
```diff
@@ -1,36 +1,20 @@
...
  */
 const PublicComponentStylesWrapperInner = styled.div`
-  // Try to reset as much as possible to avoid css leaking from host app to our components
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk-bundle/components/private/PublicComponentStylesWrapper.tsx:14]: just a clean up, move this to css modules as Styled components are already deprecated.

File: enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkPortalContainer.style.css [hunk 3]
```diff
@@ -0,0 +1,4 @@
+.portalWrapper {
+  /* Avoid taking space inside a container e.g. flex */
+  display: contents;
```
Comment (WiNloSt) [inline enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkPortalContainer.style.css:3]: this is the fix, by removing this from the box model, it won't take space in any parent e.g. flex

**Review by heypoom — APPROVED** [review]
Tested locally with a flex container, works well!

Image
