### PR TITLE
Inline parameter in clickhouse honeysql method

### LINKED ISSUE #70901: Clickhouse field filter on casted timestamp generates invalid SQL
### Describe the bug

If you add a field filter over a timestamp that is either milliseconds or microseconds casted to Datetime, it generates invalid SQL

### To Reproduce

1. Connect to Clickhouse, set up a table:
```sql

CREATE TABLE events (
    time UInt64,
    name String
) ENGINE = MergeTree()
ORDER BY time;

INSERT INTO events (time, name) VALUES
(1617187200000, 'Event A'),
(1617187260000, 'Event B'),
(1617187320000, 'Event C'),
(1617187380000, 'Event D'),
(1617187440000, 'Event E');

```
2. Go to Table Metadata, cast `events.time` to `UNIX milliseconds->Datetime`
3. New SQL question, `select * from events where {{time}}`
4. Make the variable a field filter on `events.time` and set it to anything e.g. Previous 7 days, run it
5. See error

Image

Generated SQL from Preview the query looks correct and runs
```sql
SELECT
  *
FROM
  events
WHERE
  `toDateTime64`(`db`.`events`.`time` / 1000, 3) >= `parseDateTimeBestEffort`('2026-03-06 00:00:00.000Z')
  AND `toDateTime64`(`db`.`events`.`time` / 1000, 3) < `parseDateTimeBestEffort`('2026-03-13 00:00:00.000Z')
```

But breaks when sent programmatically to the underlying JDBC driver

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
v59.2.5
```

### Severity

P2

### Additional context

Locally overwrote this part of the code and it seems to fix it:

https://github.com/metabase/metabase/blob/653d9ab52f900742ca0d0ec7fb32f0fa8749e716/modules/drivers/clickhouse/src/metabase/driver/clickhouse_qp.clj#L181-L187

By wrapping the 3 with [:raw] and report timezone with `h2x/literal`
```clj
(defmethod sql.qp/unix-timestamp->honeysql [:clickhouse :milliseconds]
  [_ _ expr]
  (let [report-timezone (get-report-timezone-id-safely)
        inner-expr      (h2x// expr 1000)]
    (if report-timezone
      [:'toDateTime64 inner-expr [:raw 3] (h2x/literal report-timezone)]
      [:'toDateTime64 inner-expr [:raw 3]])))
```

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/70901

### Description

Uses fix suggested by @ghostframe to inline the precision value in the millseconds -> datetime casting

### How to verify

See original issue. The query should work now. 

### Demo

https://github.com/user-attachments/assets/9b45ed08-003e-4a89-8a39-1e45dcfea241

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [ ] If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)

### CODE REVIEW

File: modules/drivers/clickhouse/test/metabase/driver/clickhouse_substitution_test.clj [hunk 1]
```diff
@@ -336,6 +336,45 @@
...
+                                                                    :type         "dimension"
+                                                                    :dimension    ["field" (mt/id :milliseconds-table :time) nil]
+                                                                    :required     true}}
+                                      :query "SELECT * FROM `milliseconds_db`.`milliseconds_table` WHERE {{date_filter}}"}
+                         :parameters [{:type   "date/all-options"
+                                       :value  "past7days"
+                                       :target ["dimension" ["template-tag" "date_filter"]]
+                                       :id     uuid}]}]
+              (is (= [[1 1574982000000 "Event A"]
+                      [2 1575068400000 "Event B"]]
```
Comment (metamben) [inline modules/drivers/clickhouse/test/metabase/driver/clickhouse_substitution_test.clj:375]: I can't see how `time` column is not dependent on when we run the test.

Comment (rileythomp) [reply modules/drivers/clickhouse/test/metabase/driver/clickhouse_substitution_test.clj:375]: It's using `mt/with-clock clock`, clock is defined above for other tests as `(t/instant "2019-11-30T23:00:00Z")`

**Review by metamben — APPROVED** [review]
