### PR TITLE
embed: call postMessage to all origins

### LINKED ISSUE #12069: Full App embed postMessage listener not working with multiple domains
**Describe the bug**
I have the following handler for messages

```window.addEventListener('message', (e) => { console.log(e) })```
Whenever I change the url on the metabase embedded iframe, I should get a message with the new location. I am not getting anything

On the other hand, when I postMessage from the parent (I use this when I want the parent to modify the URL, it works fine)

I am on enterprise edition.

**To Reproduce**
Attach a window.addEventListener('message') and click around on the embedded metabase. You will not get any messages.

**Expected behavior**
https://www.metabase.com/docs/latest/enterprise-guide/full-app-embedding.html

As documented, I am supposed to get an object in which I will see the current URL

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by pawit-metabase**
`embedding-app-origin` may contain multiple origins but postMessage supports only a single origin, so we need to use `*` instead.

The risk should be very low because
 - the data we send is not sensitive data (frame size, current URL)
 - we are already using frame ancestor policy to limit domains that can embed metabase

Fixes #12069

### CODE REVIEW

File: frontend/src/metabase/lib/embed.js [hunk 1]
```diff
@@ -47,10 +47,16 @@ export function initializeEmbedding(store) {
...
 
 function sendMessage(message) {
-  window.parent.postMessage(
-    { metabase: message },
-    MetabaseSettings.get("embedding-app-origin"),
-  );
+  // Since postMessage does not support multiple origins and sending message to "*"
+  // is discouraged, what we can do is send a message to each origin and messages
+  // where the origin does not match will be dropped by the browser.
+  const origins = MetabaseSettings.get("embedding-app-origin").split(" ");
```
Comment (daltojohnso) [inline frontend/src/metabase/lib/embed.js:53]: I see in `public_settings.clj` that `embedding-app-origin` has no default value, so let's make sure we have a string here by doing something like:
```
const origins = (MetabaseSettings.get("embedding-app-origin") || "").split(" ");
```

**Review by daltojohnso — CHANGES_REQUESTED** [review]

**Review by flamber — COMMENTED** [review]
So while this would work, it would also litter the browser console with errors:
`Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://another-url.test’) does not match the recipient window’s origin (‘https://app.example.com’).`

**Comment by pawit-metabase** [comment]
I was trying to avoid having to do a manual check but having that error there isn't good either. Plus `postMessage` doesn't support the `https://*.subdomain.dom` syntax.

Maybe we should just use `*` which should be relatively safe because we have iframe ancestor policy and we're not sending sensitive information.

**Review by daltojohnso — APPROVED** [review]
