### PR TITLE
fix: respect time format in exclude date picker filter QUE-2611

### LINKED ISSUE #64269: Date picker filter: Hour of the day exclusion does not respect instance localization settings
### Describe the bug

When the instance is configured to use the 24-hour clock and the user applies a date filter to exclude certain hours, the dropdown still shows AM/PM.

Image

### To Reproduce

1. Configure the instance to use 24-hour clock.
2. Create/view a dashboard with a date filter with all options.
3. Select exclude -> hours of the day
4. See list of AM/PM values instead of their 24-hour counterpart

### Expected behavior

This dropdown should show values like

Image

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:142.0) Gecko/20100101 Firefox/142.0",
    "vendor": ""
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2025-09-15",
      "tag": "v1.56.5.6",
      "hash": "9a3297a"
    },
    "settings": {
      "report-timezone": "Europe/Stockholm"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "6.12.13-200.fc41.aarch64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chodorowicz**
closes #64269
Closes https://linear.app/metabase/issue/QUE-2611/date-picker-filter-hour-of-the-day-exclusion-does-not-respect-instance

### Description

Describe the overall approach and the problem being solved.

### How to verify

- create a dashboard and a add to it a question
- add Date Picker filter to it and save the dashboard
- add filtering and choose exclude
- default time formatting options (US 12 hour format should be visible)
- now go to to localization settings (`/admin/settings/localization`) and change the time format to 24 hour one
- go back to the dashboard
- 24 hour format should be visible in the exclude time filter

### Demo

https://github.com/user-attachments/assets/f988bf83-b857-47a5-be8a-82a2e230e045

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.tsx [hunk 1]
```diff
@@ -178,8 +180,14 @@ function ExcludeValuePicker({
   readOnly,
 }: ExcludeValuePickerProps) {
   const [values, setValues] = useState(initialValues);
+  const formattingOptions = useSelector((state) =>
```
Comment (fraserdrops) [inline frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.tsx]: we have `useSetting` which wraps this up

File: frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.unit.spec.tsx [hunk 2]
```diff
@@ -193,4 +207,48 @@ describe("ExcludeDatePicker", () => {
...
+      expect(screen.getByLabelText("1 PM")).toBeInTheDocument();
+      expect(screen.getByLabelText("11 PM")).toBeInTheDocument();
+    });
+
+    it("should display hours in 24-hour format when setting is HH:mm", async () => {
+      setup({ timeStyle: "HH:mm" });
+
+      await userEvent.click(screen.getByText("Hours of the day…"));
+
+      expect(screen.getByLabelText("00:00")).toBeInTheDocument();
```
Comment (fraserdrops) [inline frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.unit.spec.tsx]: I quite like this pattern for making lots of text assertions

```js
 [
      "From Name",
      "From Address",
      "Reply-To Address",
      "Add Recipients as CC or BCC",
      "Approved domains for notifications",
      "Suggest recipients on dashboard subscriptions and alerts",
    ].forEach((text) => {
      expect(screen.getByText(text)).toBeInTheDocument();
    });
```

**Review by fraserdrops — APPROVED** [review]

File: frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.tsx (hunk 1 above)
Comment (chodorowicz) [reply frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.tsx]: yeah, two weeks holidays and I forgot about it 😅 fixed https://github.com/metabase/metabase/pull/67384/changes/d41e0a1a05117f9dbbe630a96bec062109ce7f38

File: frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.unit.spec.tsx (hunk 2 above)
Comment (chodorowicz) [reply frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.unit.spec.tsx]: yeah, good point! https://github.com/metabase/metabase/pull/67384/commits/aa9f92ed47a52d0279331715010595274a9ce969
