### PR TITLE
Put db-level cache_ttl behind enterprise feature flag

### LINKED ISSUE #29477: It is possible to set a custom database cache ttl in Metabase OSS version
**Describe the bug**
It is possible to set a custom database cache ttl in OSS Metabase version.

**To Reproduce**
1. Open an OSS instance of Metabase (JAR, Docker, local dev... doesn't matter)
2. Using `curl`, or a tool like Postman or Insomnia try to send a `PUT` request to the existing database (let's say its id is `1`) `/api/database/1` with the following payload `cache_ttl: 42`
3. The request goes through and responds with `200`
4. If you then try to `GET /api/database/1`, you'll see that the `cache_ttl` is there with the value you set it to in the step 2

This is possible even without `enable-query-caching` enabled. Not sure if it has any effect without it enabled, but doesn't hurt to mention it.

**Expected behavior**
If this is a feature that shouldn't exist in OSS version, backend shouldn't accept it.

**Important thing to note here is that frontend correctly handles this and doesn't show advanced caching config in the UI for OSS Metabase version!**

**Information about your Metabase Installation:**
H2, Sample Database.
Tested all the way back to `v0.43.4`

**Severity**
P1

### PR DESCRIPTION
**Pull request by noahmoss**
Resolves https://github.com/metabase/metabase/issues/29477

* Throws a 402 (payment required) error when adding a new database with the `cache_ttl` key if the `advanced-config` feature is not enabled.
* Does not update `cache_ttl` when updating a database if the `advanced-config` feature is not enabled
* Does not take the DB-level `cache_ttl` value into account when running a card if `advanced-config` is not enabled

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/advanced_config/caching_test.clj [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  (premium-features-test/with-premium-features #{:advanced-config}
+    (mt/discard-setting-changes [enable-query-caching]
+      (public-settings/enable-query-caching! true)
+      (testing "multiple ttl, db ttl wins"
+        ;; corresponding OSS tests in metabase-enterprise.advanced-config.caching-test
+        (mt/with-temp* [Database [db {:cache_ttl 1337}]
+                        Dashboard [dash]
+                        Card [card {:database_id (u/the-id db)}]]
+          (is (= (* 3600 1337)
+                 (:cache-ttl (#'qp.card/query-for-card card {} {} {} {:dashboard-id (u/the-id dash)})))))))))
```
Comment (escherize) [inline enterprise/backend/test/metabase_enterprise/advanced_config/caching_test.clj:22]: It seems like there should be multiple `ttl`s, but I don't see where the other `ttl` is coming from.

Comment (noahmoss) [reply enterprise/backend/test/metabase_enterprise/advanced_config/caching_test.clj:22]: oh that's misleading, it's just the database ttl here. I'll change it.

Comment (noahmoss) [reply enterprise/backend/test/metabase_enterprise/advanced_config/caching_test.clj:22]: (was just copying the string that was there before)

File: test/metabase/query_processor/card_test.clj [hunk 2]
```diff
@@ -41,12 +41,13 @@
...
       (mt/with-temp* [Database [db {:cache_ttl 1337}]
                       Dashboard [dash]
                       Card [card {:database_id (u/the-id db)}]]
-        (is (= (* 3600 1337) (:cache-ttl (#'qp.card/query-for-card card {} {} {} {:dashboard-id (u/the-id dash)}))))))
-    (testing "no ttl, nil res"
+        (is (= nil (:cache-ttl (#'qp.card/query-for-card card {} {} {} {:dashboard-id (u/the-id dash)}))))))
+    (testing "no ttl, nil result"
       (mt/with-temp* [Database [db]
                       Dashboard [dash]
                       Card [card {:database_id (u/the-id db)}]]
```
Comment (escherize) [inline test/metabase/query_processor/card_test.clj:53]: I think this is missing an assertion. probably just need to check for nil again

**Review by escherize — APPROVED** [review]
Looks good, just 2 minor changes I noticed.

1. A comment on a test out of date
2. I don't think your change caused it, but it may be worth adding in that missing assertion

File: test/metabase/query_processor/card_test.clj (hunk 2 above)
Comment (noahmoss) [reply test/metabase/query_processor/card_test.clj:53]: it's the line below, just cut off by the diff

Comment (escherize) [reply test/metabase/query_processor/card_test.clj:53]: 🤦‍♂️
