### PR TITLE
Fix X-Ray/Automagic Dashboards when source query has a filter

### LINKED ISSUE #19241: X-rays fails if there's a filter in the question
**Describe the bug**
X-rays fails if there's a filter in the question.
Regression since 0.39.0

**To Reproduce**
1. Custom question > Sample Dataset > Products, filter Category="Doohickey", summarize Count grouped by CreatedAt:Year
image
2. Visualize, click any of the points and select X-ray
3. Errors with "Something's gone wrong"
image

<details><summary>Full stacktrace</summary>

```
2021-12-07 17:08:34,380 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 18.4 ms (11 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (2 idle, 0 queued) (110 total active threads) Queries in flight: 0 (0 queued); h2 DB 4 connections: 0/1 (0 threads blocked)
2021-12-07 17:08:38,270 ERROR middleware.log :: GET /api/automagic-dashboards/adhoc/eyJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjEwLCJmaWx0ZXIiOlsiPSIsWyJmaWVsZCIsMTA3LG51bGxdLCJEb29oaWNrZXkiXSwiYWdncmVnYXRpb24iOltbImNvdW50Il1dLCJicmVha291dCI6W1siZmllbGQiLDEwOCx7InRlbXBvcmFsLXVuaXQiOiJ5ZWFyIn1dXX0sImRhdGFiYXNlIjo0fQ==/cell/WyI9IixbImZpZWxkIiwxMDgseyJ0ZW1wb3JhbC11bml0IjoieWVhciJ9XSwiMjAxNy0wMS0wMVQwMDowMDowMCswMTowMCJd 500 516.7 ms (32 DB calls) 
{:via
 [{:type org.h2.jdbc.JdbcSQLException,
   :message
   "Data conversion error converting \"()\"; SQL statement:\nSELECT * FROM \"METABASE_FIELD\" WHERE \"ID\" = () LIMIT 1 [22018-197]",
   :at [org.h2.message.DbException getJdbcSQLException "DbException.java" 357]}
  {:type java.lang.NumberFormatException,
   :message "For input string: \"()\"",
   :at [java.lang.NumberFormatException forInputString "NumberFormatException.java" 65]}],
 :trace
 [[java.lang.NumberFormatException forInputString "NumberFormatException.java" 65]
  [java.lang.Long parseLong "Long.java" 678]
  [java.lang.Long parseLong "Long.java" 817]
  [org.h2.value.Value convertTo "Value.java" 1063]
  [org.h2.value.Value convertTo "Value.java" 617]
  [org.h2.value.Value convertTo "Value.java" 592]
  [org.h2.mvstore.db.MVPrimaryIndex getKey "MVPrimaryIndex.java" 335]
  [org.h2.mvstore.db.MVDelegateIndex find "MVDelegateIndex.java" 69]
  [org.h2.index.BaseIndex find "BaseIndex.java" 130]
  [org.h2.index.IndexCursor find "IndexCursor.java" 176]
  [org.h2.table.TableFilter next "TableFilter.java" 471]
  [org.h2.command.dml.Select$LazyResultQueryFlat fetchNextRow "Select.java" 1452]
  [org.h2.result.LazyResult hasNext "LazyResult.java" 79]
  [org.h2.result.LazyResult next "LazyResult.java" 59]
  [org.h2.command.dml.Select queryFlat "Select.java" 527]
  [org.h2.command.dml.Select queryWithoutCache "Select.java" 633]
  [org.h2.command.dml.Query queryWithoutCacheLazyCheck "Query.java" 114]
  [org.h2.command.dml.Query query "Query.java" 371]
  [org.h2.command.dml.Query query "Query.java" 333]
  [org.h2.command.CommandContainer query "CommandContainer.java" 114]
  [org.h2.command.Command executeQuery "Command.java" 202]
  [org.h2.jdbc.JdbcPreparedStatement executeQuery "JdbcPreparedStatement.java" 114]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeQuery "NewProxyPreparedStatement.java" 431]
  [clojure.java.jdbc$execute_query_with_params invokeStatic "jdbc.clj" 1090]
  [clojure.java.jdbc$execute_query_with_params invoke "jdbc.clj" 1084]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invokeStatic "jdbc.clj" 1113]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invoke "jdbc.clj" 1093]
  [clojure.java.jdbc$query invokeStatic "jdbc.clj" 1182]
  [clojure.java.jdbc$query invoke "jdbc.clj" 1144]
  [toucan.db$query invokeStatic "db.clj" 288]
  [toucan.db$query doInvoke "db.clj" 284]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [toucan.db$simple_select invokeStatic "db.clj" 394]
  [toucan.db$simple_select invoke "db.clj" 383]
  [toucan.db$simple_select_one invokeStatic "db.clj" 420]
  [toucan.db$simple_select_one invoke "db.clj" 409]
  [toucan.db$select_one invokeStatic "db.clj" 627]
  [toucan.db$select_one doInvoke "db.clj" 620]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.core$apply invokeStatic "core.clj" 673]
  [clojure.core$apply invoke "core.clj" 662]
  [toucan.models$invoke_model invokeStatic "models.clj" 380]
  [toucan.models$invoke_model doInvoke "models.clj" 368]
  [clojure.lang.RestFn invoke "RestFn.java" 445]
  [toucan.models$invoke_model invokeStatic "models.clj" 378]
  [toucan.models$invoke_model invoke "models.clj" 368]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 669]
  [clojure.core$apply invoke "core.clj" 662]
  [toucan.models$invoke_model_or_instance invokeStatic "models.clj" 395]
  [toucan.models$invoke_model_or_instance doInvoke "models.clj" 391]
  [clojure.lang.RestFn invoke "RestFn.java" 423]
  [metabase.models.field.FieldInstance invoke "field.clj" 61]
  [metabase.automagic_dashboards.core$__GT_field invokeStatic "core.clj" 52]
  [metabase.automagic_dashboards.core$__GT_field invoke "core.clj" 45]
  [metabase.automagic_dashboards.core$filter_referenced_fields$fn__66462$iter__66466__66470$fn__66471$fn__66472
   invoke
   "core.clj"
   978]
  [metabase.automagic_dashboards.core$filter_referenced_fields$fn__66462$iter__66466__66470$fn__66471
   invoke
   "core.clj"
   977]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5419 invokeStatic "core.clj" 139]
  [clojure.core$concat$fn__5510 invoke "core.clj" 727]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5419 invokeStatic "core.clj" 139]
  [clojure.core$filter$fn__5911 invoke "core.clj" 2813]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5419 invokeStatic "core.clj" 139]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 24]
  [clojure.core.protocols$fn__8168 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8168 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8110$G__8105__8123 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6830]
  [clojure.core$into invokeStatic "core.clj" 6897]
  [clojure.core$into invoke "core.clj" 6889]
  [metabase.automagic_dashboards.core$filter_referenced_fields invokeStatic "core.clj" 980]
  [metabase.automagic_dashboards.core$filter_referenced_fields invoke "core.clj" 971]
  [metabase.automagic_dashboards.core$automagic_dashboard invokeStatic "core.clj" 1011]
  [metabase.automagic_dashboards.core$automagic_dashboard invoke "core.clj" 982]
  [metabase.automagic_dashboards.core$fn__66596 invokeStatic "core.clj" 1233]
  [metabase.automagic_dashboards.core$fn__66596 invoke "core.clj" 1216]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [metabase.api.automagic_dashboards$fn__78438 invokeStatic "automagic_dashboards.clj" 131]
  [metabase.api.automagic_dashboards$fn__78438 invoke "automagic_dashboards.clj" 121]
  [compojure.core$wrap_response$fn__32066 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__32050 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__32055 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 151]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 152]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__70282 invoke "auth.clj" 14]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32106 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32110 invoke "core.clj" 299]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
  [compojure.core$make_context$fn__32110 invoke "core.clj" 300]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
  [metabase.api.routes$fn__79759$fn__79762 invoke "routes.clj" 56]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__79904$fn__79905 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078 invoke "core.clj" 200]
  [compojure.core$make_context$handler__32106 invoke "core.clj" 289]
  [compojure.core$make_context$fn__32110 invoke "core.clj" 299]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 152]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 152]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__32059 invoke "core.clj" 152]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080 invoke "core.clj" 197]
  [metabase.server.routes$fn__79892$fn__79894 invoke "routes.clj" 41]
  [compojure.core$routes$fn__32078$f__32079 invoke "core.clj" 198]
  [compojure.core$routes$fn__32078 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77364 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__77361 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__80359$fn__80360$fn__80361 invoke "log.clj" 209]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__80359$fn__80360 invoke "log.clj" 201]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__80359 invoke "log.clj" 200]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__83572 invoke "browser_cookie.clj" 30]
  [metabase.server.middleware.security$add_security_headers$fn__59226 invoke "security.clj" 147]
  [metabase.server.middleware.json$wrap_json_body$fn__82716 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__82734 invoke "json.clj" 98]
  [metabase.server.middleware.offset_paging$handle_paging$fn__59250 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__83839 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__83855 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__34077 invoke "misc.clj" 59]
  [metabase.server.middleware.session$bind_current_user$fn__44978$fn__44979 invoke "session.clj" 257]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 238]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 230]
  [metabase.server.middleware.session$bind_current_user$fn__44978 invoke "session.clj" 256]
  [metabase.server.middleware.session$wrap_current_user_info$fn__44965 invoke "session.clj" 216]
  [metabase.server.middleware.session$wrap_session_id$fn__44951 invoke "session.clj" 162]
  [metabase.server.middleware.auth$wrap_api_key$fn__70290 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__83759 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__34060 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__34085 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__83801 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__34088 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83588 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__80132 invoke "server.clj" 71]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 388]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 633]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 380]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 386]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run "Thread.java" 829]],
 :cause "For input string: \"()\"",
 :message
 "Data conversion error converting \"()\"; SQL statement:\nSELECT * FROM \"METABASE_FIELD\" WHERE \"ID\" = () LIMIT 1 [22018-197]",
 :sql-exception-chain
 ["JdbcSQLException:"
  "Message: Data conversion error converting \"()\"; SQL statement:"
  "SELECT * FROM \"METABASE_FIELD\" WHERE \"ID\" = () LIMIT 1 [22018-197]"
  "SQLState: 22018"
  "Error Code: 22018"]}
```

</details>

Different application databases will cause different errors, which threw me off completely, when originally debugging this, since I thought the error was coming from the warehouse, but H2 makes it clear what the problem is.

H2: `Data conversion error converting "()"; SQL statement: SELECT * FROM "METABASE_FIELD" WHERE "ID" = () LIMIT 1 [22018-197]`

Postgres: `ERROR: syntax error at or near \")\"\n  Position: 46`

MySQL: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') LIMIT 1' at line 1`

**Information about your Metabase Installation:**
Tested 0.38.4 thru 0.41.3.1 and master - regression since 0.39.0

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #19241

The main issue here was that the code for iterating over all the Field IDs or names in the query was wrong:

https://github.com/metabase/metabase/compare/fix-xrays-with-filters?expand=1#diff-917546b664c1f28360366030be7ac6c6db5d58df5e6548078b7751859ed4a523L976-R980

It was iterating over everything in a `:field` clause after the initial keyword. This worked fine before the last MBQL refactor because `:field-id` never had a third element. But after the last refactor this code started breaking and the field clause options e.g.`{:temporal-unit :year}` could get treated as a Field ID/name (this is why X-Rays were only failing if there was a temporal filter in the original query).

Everything else in this PR is either adding schema validation to stuff (which would have caught this bug much early/made debugging a lot easier) or some code reformatting for readability

### CODE REVIEW

File: src/metabase/automagic_dashboards/core.clj [hunk 1]
```diff
@@ -969,50 +971,46 @@
...
 
 (defn- filter-referenced-fields
-  "Return a map of fields referenced in filter cluase."
+  "Return a map of fields referenced in filter clause."
   [root filter-clause]
   (->> filter-clause
        filters/collect-field-references
-       (mapcat (fn [[_ & ids]]
-                 (for [id ids]
-                   [id (->field root id)])))
```
Comment (camsaul) [inline src/metabase/automagic_dashboards/core.clj:978]: This was the actual fix here, as you can see destructuring something like `[:field 1 {:temporal-unit :year}]` as `[_ & ids]` is busted -- this was what was breaking

**Comment by howonlee** [comment]
I'm creating a thing in the internal notion refactoring backlog to note that we should deal with x-ray types, because I've been pissed off at them too

**Review by howonlee — APPROVED** [review]
Can confirm that fixes actually fix.
