### PR TITLE
More useful error message if index.html is missing when running `lein ring server`

### LINKED ISSUE #2195: Provide better error message if frontend files are missing when running `lein ring server`
*  I am using the Chrome  browser.
*  My computer's OS is OSX (El capitan)
*  I'm running Metabase locally compled with lein
*  My database is default
*  My Metabase version is master branch

After running ./lein ring server I'm getting the following error.

```
03-21 11:07:23 DEBUG db.internal :: DB CALL: Setting [:value] (where (limit (select* ENTITY11194) 1) {:key (name k)})
03-21 11:07:23 INFO metabase.core :: Metabase Initialization COMPLETE
Started server on port 3000
java.lang.IllegalArgumentException: Cannot open <nil> as a Reader.
                    io.clj:288 clojure.java.io/fn
                    io.clj:288 clojure.java.io/fn
                     io.clj:69 clojure.java.io/fn[fn]
                    io.clj:102 clojure.java.io/reader
                     io.clj:86 clojure.java.io/reader
               RestFn.java:410 clojure.lang.RestFn.invoke
                  AFn.java:154 clojure.lang.AFn.applyToHelper
               RestFn.java:132 clojure.lang.RestFn.applyTo
                  core.clj:648 clojure.core/apply
                 core.clj:6657 clojure.core/slurp
                 core.clj:6657 clojure.core/slurp
               RestFn.java:410 clojure.lang.RestFn.invoke
                 routes.clj:13 metabase.routes/index
                 routes.clj:11 metabase.routes/index
               response.clj:33 compojure.response/eval1592[fn]
                response.clj:6 compojure.response/eval1547[fn]
                  core.clj:135 compojure.core/make-route[fn]
                  core.clj:122 compojure.core/wrap-route-middleware[fn]
                  core.clj:126 compojure.core/wrap-route-info[fn]
                   core.clj:45 compojure.core/if-route[fn]
                   core.clj:27 compojure.core/if-method[fn]
                  core.clj:151 compojure.core/routing[fn]
                 core.clj:2592 clojure.core/some
                 core.clj:2583 clojure.core/some
                  core.clj:151 compojure.core/routing
                  core.clj:148 compojure.core/routing
               RestFn.java:139 clojure.lang.RestFn.applyTo
                  core.clj:648 clojure.core/apply
                  core.clj:641 clojure.core/apply
                  core.clj:156 compojure.core/routes[fn]
            middleware.clj:255 metabase.middleware/log-api-call[fn]
            middleware.clj:194 metabase.middleware/add-security-headers[fn]
                   json.clj:46 ring.middleware.json/wrap-json-body[fn]
                   json.clj:87 ring.middleware.json/wrap-json-response[fn]
         keyword_params.clj:35 ring.middleware.keyword-params/wrap-keyword-params[fn]
                 params.clj:64 ring.middleware.params/wrap-params[fn]
             middleware.clj:94 metabase.middleware/bind-current-user[fn]
             middleware.clj:62 metabase.middleware/wrap-current-user-id[fn]
            middleware.clj:104 metabase.middleware/wrap-api-key[fn]
             middleware.clj:53 metabase.middleware/wrap-session-id[fn]
               cookies.clj:161 ring.middleware.cookies/wrap-cookies[fn]
               session.clj:102 ring.middleware.session/wrap-session[fn]
                   gzip.clj:65 ring.middleware.gzip/wrap-gzip[fn]
                  Var.java:379 clojure.lang.Var.invoke
                 reload.clj:22 ring.middleware.reload/wrap-reload[fn]
             stacktrace.clj:23 ring.middleware.stacktrace/wrap-stacktrace-log[fn]
             stacktrace.clj:86 ring.middleware.stacktrace/wrap-stacktrace-web[fn]
                  jetty.clj:24 ring.adapter.jetty/proxy-handler[fn]
              (Unknown Source) ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle
        HandlerWrapper.java:97 org.eclipse.jetty.server.handler.HandlerWrapper.handle
               Server.java:497 org.eclipse.jetty.server.Server.handle
          HttpChannel.java:310 org.eclipse.jetty.server.HttpChannel.handle
       HttpConnection.java:257 org.eclipse.jetty.server.HttpConnection.onFillable
   AbstractConnection.java:540 org.eclipse.jetty.io.AbstractConnection$2.run
     QueuedThreadPool.java:635 org.eclipse.jetty.util.thread.QueuedThreadPool.runJob
     QueuedThreadPool.java:555 org.eclipse.jetty.util.thread.QueuedThreadPool$3.run
```

### PR DESCRIPTION
**Pull request by camsaul**
Resolves #2195

### CODE REVIEW

File: src/metabase/routes.clj [hunk 1]
```diff
@@ -10,7 +10,9 @@
 
 (defn- index [_]
   (-> (if (@(resolve 'metabase.core/initialized?))
-        (stencil/render-string (slurp (io/resource "frontend_client/index.html"))
+        (stencil/render-string (slurp (or (io/resource "frontend_client/index.html")
+                                          ;; Occasionally people try to launch from 'lein ring server' and move stuff around. In that case give them a useful error message.
+                                          (throw (Exception. "Cannot find './resources/frontend_client/index.html'."))))
```
Comment (agilliland) [inline src/metabase/routes.clj]: Can we add one additional line in the exception saying something like, "Have you built the Metabase frontend?"

Comment (camsaul) [inline src/metabase/routes.clj]: Ya that's a good point I forgot about that.
