### PR TITLE
Fix pie chart label not visible on dark theme

### LINKED ISSUE #66055: graph subtitles are not displaying
### Describe the bug

The night mode for the public dashboard was fixed in #65731, but after the Theme change, graph subtitles are not displaying in some areas.

Image

### To Reproduce

1. Start a v57 instance
1. Go to the example "E-commerce" dashboard
1. Create a public link and copy the link
1. Open a new tab, paste the link, and add #theme=night

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
v0.57.3
```

### Severity

Minor

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
closes #66055
closes git-8595

### Backport reasons
I changed this PR to double-backport so it backported it to 57, which is the reporting version.

### Description

Fix pie chart label not visible when using dark theme, this happens on both the public link (and presumably public embedding) and direct Metabase access.

### How to verify

- Visit the example dashboard "E-commerce Insight".
- Use dark theme in devtool or via Metabase command palette

#### After (look at the pie chart label)
localhost_3000_dashboard_1-e-commerce-insights_date_grouping= date_range= product_category=Doohickey product_category=Gizmo product_category=Gadget product_category=Widget tab=1-overview vendor= (4)

#### Before
localhost_3000_dashboard_1-e-commerce-insights_date_grouping= date_range= product_category=Doohickey product_category=Gizmo product_category=Gadget product_category=Widget tab=1-overview vendor= (3)

#### New loki test (PR)
Screenshot 2025-12-30 at 11 41 12 PM

#### New loki test (master)
Screenshot 2025-12-30 at 11 39 57 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR (loki)

### CODE REVIEW

File: frontend/src/metabase/common/hooks/use-palette.ts [hunk 1]
```diff
@@ -2,25 +2,17 @@ import { useMemo } from "react";
...
-      border: theme.fn.themeColor("border"),
-      "text-dark": theme.fn.themeColor("text-dark"),
-      "text-medium": theme.fn.themeColor("text-medium"),
-      "text-light": theme.fn.themeColor("text-light"),
-      "text-white": theme.fn.themeColor("text-white"),
-      "text-primary": theme.fn.themeColor("text-primary"),
-      "bg-white": theme.fn.themeColor("bg-white"),
-    };
+    return Object.fromEntries(
+      ALL_COLOR_NAMES.map((name) => [name, theme.fn.themeColor(name)]),
```
Comment (WiNloSt) [inline frontend/src/metabase/common/hooks/use-palette.ts:15]: We decided, it's [best to export all colors.](https://metaboat.slack.com/archives/C063Q3F1HPF/p1767108054685829?thread_ts=1767107128.248049&cid=C063Q3F1HPF) So we don't have to be adding more colors over time.

**Review by lorem--ipsum — APPROVED** [review]

File: frontend/src/metabase/styled-components/theme/css-variables.ts [hunk 2]
```diff
@@ -26,7 +26,6 @@ export function getMetabaseCssVariables(theme: MantineTheme) {
 
   return css`
     :root {
-      --mb-default-font-family: "${theme.fontFamily}";
```
Comment (WiNloSt) [inline frontend/src/metabase/styled-components/theme/css-variables.ts:29]: we don't need `--mb-default-font-family` for the main Metabase application because this is already defined here

https://github.com/metabase/metabase/blob/83809e7cc04165b140b371eaaac0b7f11d42e89f/frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx#L34

I believe this is a leftover from when we're refactoring the CSS varaiables for the SDK. Now that we have the SDK's own version of the CSS variables we shouldn't need this variable definition here anymore.

https://github.com/metabase/metabase/blob/83809e7cc04165b140b371eaaac0b7f11d42e89f/frontend/src/metabase/styled-components/theme/css-variables.ts#L39-L49

Also, it's wrong because you'll get a definition like this

```css
--mb-default-font-family: var(--mb-default-font-family), sans-serif
```

The default value is from https://github.com/metabase/metabase/blob/83809e7cc04165b140b371eaaac0b7f11d42e89f/frontend/src/metabase/ui/theme.ts#L145

which doesn't work, as it would render as `sans-serif`, but in reality, it would rely on a different `--mb-default-font-family` definition anyway. However, the problem arises when you somehow slap these variables after all other `--mb-default-font-family` definitions.

In this PR, I included the CSS variables under `VisualizationWrapper` so, it's possible to render dark theme on storybook. And in reality, I don't think putting these variables last should mess up the font, so removing the declaration here would still make sense.

File: frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx [hunk 3]
```diff
@@ -70,11 +70,6 @@ export const EmbeddedQuestion = {
     isDashboard: false,
     backgroundColor: "#ebe6e2",
   },
-
-  parameters: {
-    // TODO unskip this and the next story once rendering delay is completely gone.
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx:75]: based on the todo comment, it's pretty old (15 months ago (September 30th, 2024 5:25 AM) via  [ PR #48054](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)).

And there are already aother story within this file (Watermark, 8-month old) that has a snapshot, so why not just render everything here too.

File: frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx [hunk 4]
```diff
@@ -84,12 +79,16 @@ export const EmbeddedDashcard = {
     isDashboard: true,
     backgroundColor: "#dee9e9",
   },
-
-  parameters: {
-    loki: { skip: true },
-  },
 };
 
+export const DarkTheme: StoryFn = () => (
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx:84]: This is a new test for the dark theme that demonstrates the original issue.

You can revert `frontend/src/metabase/common/hooks/use-palette.ts` and see that the story should render with a dark subtitle, rendering it invisible on dark background.
```sh
git checkout master -- frontend/src/metabase/common/hooks/use-palette.ts
```

File: frontend/test/__support__/ui.tsx [hunk 5]
```diff
@@ -222,9 +224,13 @@ export function getTestStoreAndWrapper({
 
 /**
  * A minimal version of the GlobalStyles component, for use in Storybook stories.
- * Contains strictly only the base styles to act as CSS resets, without font files.
+ * Contains strictly only the base styles to act as CSS resets and css variables, without font files.
  **/
-const GlobalStylesForTest = () => <Global styles={baseStyle} />;
+const GlobalStylesForTest = () => {
```
Comment (WiNloSt) [inline frontend/test/__support__/ui.tsx:229]: Adding css variables here allows all variables to follow the theme defined in `displayTheme` on line 262. Without this change, storybook variables would still base on the light theme, the the result isn't accurate for the given `displayTheme="dark"`

#### With this change

Image

#### Without this change

Image

File: frontend/test/__support__/ui.tsx [hunk 6]
```diff
@@ -245,13 +252,14 @@ export function TestWrapper({
...
   theme?: MantineThemeOverride;
+  displayTheme?: "light" | "dark";
   withCssVariables?: boolean;
 }): JSX.Element {
   return (
     <MetabaseReduxProvider store={store}>
       <MaybeDNDProvider hasDND={withDND}>
         <ThemeProviderContext.Provider value={{ withCssVariables }}>
-          <ThemeProvider theme={theme}>
+          <ThemeProvider theme={theme} displayTheme={displayTheme}>
```
Comment (WiNloSt) [inline frontend/test/__support__/ui.tsx:262]: This allows any storybook to pass the desired theme.

File: frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx [hunk 7]
```diff
@@ -84,12 +79,16 @@ export const EmbeddedDashcard = {
...
+  <VisualizationWrapper displayTheme="dark">
+    <Box h={500}>
+      <Visualization rawSeries={data.defaultSettings as unknown as Series} />
```
Comment (lorem--ipsum) [inline frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx:87]: Super minor since this is a `*.stories` file, but isn't there a way to avoid this `as unknown`?

**Review by lorem--ipsum — APPROVED** [review]
This looks good to me

File: frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx (hunk 7 above)
Comment (WiNloSt) [reply frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx:87]: Not that I know of. I'm also not well-versed in viz types. I found we use `any` in one place
https://github.com/metabase/metabase/blob/9bcdd5b4f39e14911e27fb80984c6c48bacee2e9/frontend/src/metabase/static-viz/components/PieChart/PieChart.stories.tsx#L43

and this `as unknown as Series` down below though.
https://github.com/metabase/metabase/blob/9bcdd5b4f39e14911e27fb80984c6c48bacee2e9/frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx#L104

**Review by iethree — APPROVED** [review]
