### PR TITLE
Configure foreign key support for Mongo to allow implicit joins

### LINKED ISSUE #29538: Questions using native PK/FK relationships on Mongo fails
Loom: https://www.loom.com/share/ac98eb53a3e04ebd87cbdfab69c41961

image

### PR DESCRIPTION
**Pull request by metamben**
Fixes #29538.

This PR configures foreign key support for Mongo to allow implicit joins.

### CODE REVIEW

File: modules/drivers/mongo/test/metabase/test/data/mongo.clj [hunk 1]
```diff
@@ -21,6 +23,9 @@
 (defmethod tx/supports-time-type? :mongo [_driver] false)
 (defmethod tx/supports-timestamptz-type? :mongo [_driver] false)
 
+;; during unit tests don't treat Mongo as having FK support
+(defmethod driver/supports? [:sparksql :foreign-keys] [_ _] (not config/is-test?))
```
Comment (camsaul) [inline modules/drivers/mongo/test/metabase/test/data/mongo.clj:27]: ?

Comment (metamben) [reply modules/drivers/mongo/test/metabase/test/data/mongo.clj]: Copypasta, fixed.

**Review by camsaul — APPROVED** [review]
