### PR TITLE
Fix `flaky onboarding/command-palette.cy.spec.js`

### LINKED ISSUE #41072: [E2E] Fix flaky `onboarding/command-palette.cy.spec.js`
[Stats](https://stats.metabase.com/question?objectId=6cd383cd46f9cf965cba7b9f5557356a#eyJuYW1lIjoiVGVzdCBGbGFraW5lc3MiLCJkZXNjcmlwdGlvbiI6IkZsYWtleSB0ZXN0cyBmb3IgTWV0YWJhc2UgZnJvbSB3b3JrZmxvdyBqb2JzIHBlciB0ZXN0L2pvYi9ydW4vYnJhbmNoL2NvbW1pdC4gVXBkYXRlZCBkYWlseS4iLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyNiwidHlwZSI6InF1ZXJ5IiwicXVlcnkiOnsic291cmNlLXRhYmxlIjoiY2FyZF9fMTQ4MjgiLCJmaWx0ZXIiOlsiPSIsWyJmaWVsZCIsInN1aXRlX25hbWUiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJjb21tYW5kIHBhbGV0dGUiXX19LCJkaXNwbGF5IjoidGFibGUiLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5waXZvdF9jb2x1bW4iOiJyZXBvc2l0b3J5IiwidGFibGUuY2VsbF9jb2x1bW4iOiJ0ZXN0cyJ9LCJvcmlnaW5hbF9jYXJkX2lkIjoxNDgyOH0=)
[GH action run](https://github.com/metabase/metabase/actions/runs/8556716908/job/23447686936?pr=41030#step:13:236)

I'm not sure why some runs aren't included in the first stat link, like the example GH Action run I included here.

### PR DESCRIPTION
**Pull request by WiNloSt**
It's weird that I always see it failing locally, so I'm not sure why this test hasn't been failing consistently on CI.

Closes https://github.com/metabase/metabase/issues/41072

### Description

Adjust the accessibility tree, so that we could get the exact item we want in Cypress rather than relying on partial matching with regex which is more prone to error.

### How to verify

The tests in `e2e/test/scenarios/onboarding/command-palette.cy.spec.js` pass.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- [x] [Stress test results](https://github.com/metabase/metabase/actions/runs/8567995035) [20/20] ✅ 

### Note
I'm not backporting this because the [original PR also wasn't backported.](https://github.com/metabase/metabase/pull/39268)

### CODE REVIEW

File: frontend/src/metabase/palette/components/PaletteResults.tsx [hunk 1]
```diff
@@ -92,6 +92,7 @@ export const PaletteResults = () => {
                   <Flex gap=".5rem" style={{ minWidth: 0 }}>
                     {item.icon && (
                       <Icon
+                        aria-hidden
```
Comment (WiNloSt) [inline frontend/src/metabase/palette/components/PaletteResults.tsx:95]: So I adjust the accessibility tree so that `option` will have the correct label. Looking at the screenshot below
image

You can see that we can ignore the first icon since it's just a decorative element, and we could also remove `Open` plus its icon from the tree because this is already an option that users have to select anyway so `Open` serves only as a visual aid.

File: e2e/test/scenarios/onboarding/command-palette.cy.spec.js [hunk 2]
```diff
@@ -43,16 +43,16 @@ describe("command palette", () => {
...
 
-      cy.findByRole("option", { name: /Orders, Count/ }).should("exist");
+      cy.findByRole("option", { name: "Orders, Count" }).should("exist");
       cy.findByText('Search documentation for "Orders, Count"').should("exist");
 
       // Since the command palette list is virtualized, we will search for a few
       // to ensure they're reachable
       commandPaletteSearch().clear().type("People");
-      cy.findByRole("option", { name: /People/ }).should("exist");
+      cy.findByRole("option", { name: "People" }).should("exist");
```
Comment (WiNloSt) [inline e2e/test/scenarios/onboarding/command-palette.cy.spec.js:52]: This was the problem

image

It matches multiple elements, but please be aware that the second element from the search results appear a little after the first and the last element, so when we query exactly by the name `People` we'll only get the first option briefly before the search results pop up.

File: e2e/support/helpers/e2e-command-palette-helpers.js [hunk 3]
```diff
@@ -1,5 +1,5 @@
 export const commandPalette = () => cy.findByTestId("command-palette");
-export const openCommandPalette = () => cy.get("body").type("{ctrl+k}");
+export const openCommandPalette = () => cy.get("body").type("{ctrl+k}{cmd+k}");
```
Comment (WiNloSt) [inline e2e/support/helpers/e2e-command-palette-helpers.js:2]: Makes it possible to run tests locally on Mac.

**Review by deniskaber — APPROVED** [review]
