### PR TITLE
Remove obsolete CLI flags for `export`; fix collection specification

### LINKED ISSUE #33168: Some Serialization v2 commands are not working as described
### Describe the bug

On 47-RC3, if the user types: `java -jar metabase.jar help export`, they get

```
export path & options
	 Serialize Metabase instance into directory at `path`.
	 Options:
	   -u, --user EMAIL                Include collections owned by the specified user
	   -c, --collection ID             Export only specified ID; may occur multiple times.
	       --collections ID_LIST       (Legacy-style) Export collections in comma-separated list of IDs, e.g. '123,456'.
	   -C, --no-collections            Do not export any content in collections.
	   -S, --no-settings               Do not export settings.yaml
	   -D, --no-data-model             Do not export any data model entities; useful for subsequent exports.
	   -f, --include-field-values      Include field values along with field metadata.
	   -s, --include-database-secrets  Include database connection details (in plain text; use caution).
```

There are two groups of problems.
1. Some of these commands were not defined in the product doc.
2. Some commands are not working.

---

1. Commands that were not planned:
- [ ] `-u, --user` this command existed on v1 and was not supposed to exist on v2.
It is also not working
- [ ] `--collections` this command also wasn't planned. Collections can be only serialized using `-c or --collection`.

2. Commands not working
- [ ] `-c, --collection` is not working. Expected behavior: serialize only the selected collections (including personal collections). Current behavior: serializes all collections regardless flag. 

### To Reproduce

1. Get 47.0-RC3 with a premium token
2. Serialize using the commands above
3. Check serialized directory

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
- 47.0-RC3
```

### Severity

High, feature not working as expected

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tsmacdonald**
[Fixes #33168]

Key thing to note is that the dump expects `collection-ids` (which seems like a better name than `collections`):

```
;; /enterprise/.../serialization/cmd.clj
(defn v2-dump
  "Exports Metabase app data to directory at path"
  [path {:keys [collection-ids] :as opts}]
```

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/serialization/cmd.clj [hunk 1]
```diff
@@ -203,15 +203,14 @@
 
 (defn v2-dump
   "Exports Metabase app data to directory at path"
-  [path {:keys [user-email collection-ids] :as opts}]
+  [path {:keys [collection-ids] :as opts}]
   (log/info (trs "Exporting Metabase to {0}" path) (u/emoji "🏭 🚛💨"))
   (mdb/setup-db!)
   (check-premium-token!)
   (t2/select User) ;; TODO -- why??? [editor's note: this comment originally from Cam]
```
Comment (tsmacdonald) [inline enterprise/backend/src/metabase_enterprise/serialization/cmd.clj:210]: Tim's note: why???

Comment (tsmacdonald) [reply enterprise/backend/src/metabase_enterprise/serialization/cmd.clj:210]: (Not removing it since that's certainly a Chesterton's Fence if I ever saw one…)

File: enterprise/backend/src/metabase_enterprise/serialization/cmd.clj [hunk 2]
```diff
@@ -203,15 +203,14 @@
 
 (defn v2-dump
   "Exports Metabase app data to directory at path"
-  [path {:keys [user-email collection-ids] :as opts}]
+  [path {:keys [collection-ids] :as opts}]
```
[the remark this answers is not in the document]
Comment (tsmacdonald) [reply enterprise/backend/src/metabase_enterprise/serialization/cmd.clj:206]: Yeah, this only accepts `-c 1 -c 2 -c 3 ...`.

The legacy one that I removed accepted a comma-separated list:

```
:parse-fn (fn [s] (map #(Integer/parseInt %) (str/split s #"\s*,\s*")))
```

**Review by metamben — APPROVED** [review]
LGTM

**Comment by tsmacdonald** [comment]
@luizarakaki just fixed it

**Review by luizarakaki — APPROVED** [review]
tested locally and looks good
