### PR TITLE
Fix UX for empty dashboard filter with multiple choices

### LINKED ISSUE #25533: Filters in dashboards allow an empty value
**Describe the bug**
When using dropdown filters, if you don't select a value and click on the button, then the filter will populate but with an empty value. No effect at all, but seems like the queries run

**Logs**
NA

**To Reproduce**
1) Build a question (people table)
2) add it to a dashboard
3) add a dropdown filter to a dashboard and connect it with source
4) save the dashboard and pop up the filter, don't select any value but click the button
5) see the error

**Expected behavior**
If there's no value, you can't confirm

**Screenshots**
empty-value

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: pop 22.04
- Your databases: postgres
- Metabase version: 1.44.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P3

**Additional context**
NA

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/25533

### Description

Solution is pretty similar to what we have in other places, as it's more UX problem and not code problem, we need to explicitly show to use that no data is selected in the filter to avoid confusing.
We should be able to update filter even with empty values to handle a case with unchecked checkboxes in the filter

### How to verify

- open dashboard with a filter (choose category and multiple options to select)
- choose some value in the filter, save
- then unselect selected values, save
- parameter filter should be in the initial state (not like before - the empty value and cross icon)

### Demo

https://www.loom.com/share/1551740d8e704571b203da78843cd0f6

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/actions/parameters.js [hunk 1]
```diff
@@ -190,10 +190,22 @@ export const setParameterValue = createThunkAction(
...
+    return {
+      id: parameterId,
+      value: normalizeValue(value),
+      isDraft: isSettingDraftParameterValues,
+    };
   },
 );
 
+function normalizeValue(value) {
+  if (Array.isArray(value) && value.length === 0) {
```
Comment (uladzimirdev) [inline frontend/src/metabase/dashboard/actions/parameters.js:202]: actual fix

File: e2e/test/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js [hunk 2]
```diff
@@ -47,6 +47,34 @@ describe("scenarios > dashboard > filters > text/category", () => {
     );
   });
 
+  it("should reset filter state when all values are unselected", () => {
```
Comment (kamilmielnik) [inline e2e/test/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js:50]:
```suggestion
  it("should reset filter state when all values are unselected (metabase#25533)", () => {
```

**Review by kamilmielnik — APPROVED** [review]
Looks good & works well :+1: 

:1st_place_medal: for updating imports
