### PR TITLE
with-temporary-setting-values should use Setting's getter to fetch orig value

### LINKED ISSUE #18835: Fix `with-temporary-setting-values` macro for settings with non-idempotent setters
The `with-temporary-setting-values` macro currently does the following:
1. It reads the raw string value of a setting from the DB
2. It calls `setting/set!` to write a new setting value to the DB for the test
3. At the end of the test, it calls `setting/set!` again to restore the original value of the setting

This implementation only works for settings that have idempotent setters. e.g. for a setter `f`, `f(A) -> B` and `f(B) -> A`. However, not all setters behave this way. For example, the default setter for timestamp settings encodes values as strings, but will throw an exception when passed a string. This can lead to issues with tests that are very tricky to debug.

We should fix this by passing the parsed setting value into `setting/set!` to restore the setting rather than the raw string value from the DB.

### PR DESCRIPTION
**Pull request by camsaul**
As @noahmoss pointed out, fetching the original string-serialized value from the DB and then then trying to restore that value with `setting/set!` makes no sense, does it? e.g. we shouldn't pass serialized JSON to a setter that expects a Clojure map (deserialized JSON). Not sure how so many things actually ended up still working anyways.

Fixes #18835

### CODE REVIEW

File: src/metabase/api/geojson.clj [hunk 1]
```diff
@@ -83,9 +83,11 @@
...
   :getter  (fn [] (merge (setting/get-json :custom-geojson) builtin-geojson))
   :setter  (fn [new-value]
-             (when new-value
-               (validate-geojson new-value))
-             (setting/set-json! :custom-geojson new-value))
+             ;; remove the built-in keys you can't override them and we don't want those to be subject to validation.
+             (let [new-value (not-empty (reduce dissoc new-value (keys builtin-geojson)))]
+               (when new-value
+                 (validate-geojson new-value))
+               (setting/set-json! :custom-geojson new-value)))
```
Comment (camsaul) [inline src/metabase/api/geojson.clj:90]: This was the only thing that broke, because the built-in GeoJSON entries that we got out failed validation going back in, because they're local resources. We don't support overriding those anyway, since we `merge` `builtin-geojson` last in the `:getter` above. So I just tweaked the setter to ignore the built-in values

File: test/metabase/api/geojson_test.clj [hunk 2]
```diff
@@ -67,6 +67,23 @@
...
+                                    s/Keyword s/Any}
+                        s/Keyword  s/Any}
+                       built-in))
+          (is (= built-in
+                 (geojson-api/custom-geojson))))
+        (testing "Try to change one of the built-in entries..."
+          (geojson-api/custom-geojson (assoc-in built-in [:us_states :name] "USA"))
+          (testing "Value should not have actually changed"
+            (is (= built-in
+                   (geojson-api/custom-geojson)))))))))
```
Comment (camsaul) [inline test/metabase/api/geojson_test.clj:85]: I added a test to be extra sure we're not letting people override the built-in keys to get around validation or anything like that

File: test/metabase/test/util.clj [hunk 3]
```diff
@@ -332,32 +332,40 @@
...
+                            e)))
+          (finally
+            (try
+              (setting/set! setting-k original-value)
+              (catch Throwable e
+                (throw (ex-info (str "Error restoring original Setting value: " (ex-message e))
+                                {:setting        setting-k
+                                 :location       (symbol (name (:namespace setting)) (name setting-k))
+                                 :original-value original-value}
+                                e))))))))))
```
Comment (camsaul) [inline test/metabase/test/util.clj:368]: I made some small tweaks to the error messages that happen here to give you better info when they happen as well as the location where the Setting is actually defined

File: test/metabase/test/util.clj [hunk 4]
```diff
@@ -332,32 +332,40 @@
...
-        (testing (colorize/blue (format "\nSetting %s = %s\n" (keyword setting-k) (pr-str value)))
-          (thunk))
-        (catch Throwable e
-          (throw (ex-info (str "Error in with-temporary-setting-values: " (ex-message e))
-                          {:setting setting-k
-                           :value   value}
-                          e)))
-        (finally
-          (setting/set! setting-k original-db-or-cache-value))))))
+      (let [original-value (setting/get setting-k)]
```
Comment (camsaul) [inline test/metabase/test/util.clj:349]: This is the actual change right here

File: src/metabase/api/geojson.clj [hunk 5]
```diff
@@ -18,7 +18,7 @@
               :region_name              (s/maybe s/Str)
               (s/optional-key :builtin) s/Bool}})
 
-(def ^:private ^:const builtin-geojson
+(def ^:private builtin-geojson
```
Comment (camsaul) [inline src/metabase/api/geojson.clj:21]: This shouldn't have really been `^:const` in the first place IMO

**Review by noahmoss — APPROVED** [review]
Awesome, looks great 🙌
