### PR TITLE
fix charts crash in safari when dataset timezone is not in iana format

### LINKED ISSUE #44128: v0.50.x - "scale: Timeseries" not working with Oracle database - "invalid time zone in DateTimeFormat(): +00:00"
### Describe the bug

Since v0.50.x visualizations using `scale: Timeseries` (Bar, Line, Area, Combo) are not working with **Oracle Databases** any more.

grafik

### To Reproduce

1. Set up a new metabse-Instance with docker putting an `oracle-jdbc-driver` into the plugins folder.
2. Connect metabase to the an Oracle Database
3. Make a SQL-Querry against the Oracle Database to receive some testdata with a Date:
```
SELECT CURRENT_DATE, 10 AS VALUE FROM DUAL
UNION ALL
SELECT CURRENT_DATE+1, 20 AS VALUE FROM DUAL
UNION ALL
SELECT CURRENT_DATE+2, 5 AS VALUE FROM DUAL
```
4. Try to visualize the testdata in a `Line` chart using `CURRENT_DATE` as `scale:Timeseries`

I used the latest [ojdbc11.jar](https://download.oracle.com/otn-pub/otn_software/jdbc/234/ojdbc11.jar) as jdbc driver.
To reproduce the error i used the latest [Oracle Database XE Release 21c](https://container-registry.oracle.com/ords/f?p=113:4:116595847545161:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:803,803,Oracle%20Database%20Express%20Edition,Oracle%20Database%20Express%20Edition,1,0&cs=31RJ2Qrbu6s3cv9VTJmRigJuIm2BglixteP4I7m8uBo7s1uurGg1td0jk0Lhlme1etvT9Qc-v5-O6uA1el6SuSA)

In my setup to reproduce the error i started a fresh metabase with a fresh oracle-xe Database with the following docker compose file:
```
version: "2"


services:
  metabase:
    image: metabase/metabase:v0.50.3
    depends_on:
      - oracle-xe
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./plugins
        target: /plugins

  oracle-xe:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PWD=test
```
Make sure u have a `plugins` folder with the ojdbc.jar in the folder you have the docker compose.yml.
Start it with `docker compose up`.
You can connect to the oracle database on:
- url: oracle-xe
- port: 1521
- service: XE
- user: system
- password: test

### Expected behavior

The Line Chart should be rendered using `scale: Timeseries` 

### Logs

Browser Console log:
```
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
RangeError: invalid time zone in DateTimeFormat(): +00:00
    tz Angular
    toEChartsAxisValue axis.ts:677
    fn dataset.ts:757
    _ dataset.ts:271
    x dataset.ts:227
    x dataset.ts:225
    x dataset.ts:224
    N dataset.ts:733
    r_ index.ts:130
    w use-models-and-option.ts:68
    React 2
    <anonymous> use-models-and-option.ts:58
    iI CartesianChart.tsx:49
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 9
    em querying.js:211
    Redux 2
    eo querying.js:139
    promise callback*83402/eo/< querying.js:130
    Redux 2
    runQuery NativeQueryEditor.tsx:388
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 11
    m4 app.js:68
    m6 app.js:99
    71017 app-main.js:24
    Webpack 6
[console.js:13:4](webpack:///lib/errors/console.js)
invalid time zone in DateTimeFormat(): +00:00 [console.js:13:4](webpack:///lib/errors/console.js)
    error console.js:13
    onRenderError Visualization.jsx:325
    componentDidCatch ChartRenderingErrorBoundary.tsx:14
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 9
    em querying.js:211
    Redux 2
    eo querying.js:139
    (Async: promise callback)
    eo querying.js:130
    Redux 2
    runQuery NativeQueryEditor.tsx:388
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 11
    m4 app.js:68
    m6 app.js:99
    71017 app-main.js:24
    Webpack 6

```
Metabase Log:
```
[5ae29451-85d7-4b59-98f5-365ec77fc147] 2024-06-13T14:17:48+02:00 INFO metabase.core 
Metabase v0.50.3 (855535b) 

Copyright © 2024 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
[5ae29451-85d7-4b59-98f5-365ec77fc147] 2024-06-13T14:17:48+02:00 INFO metabase.core Starting Metabase in STANDALONE mode
[5ae29451-85d7-4b59-98f5-365ec77fc147] 2024-06-13T14:17:48+02:00 INFO metabase.server Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "0.0.0.0"}

[5ae29451-85d7-4b59-98f5-365ec77fc147] 2024-06-13T14:17:48+02:00 INFO metabase.core Starting Metabase version v0.50.3 (855535b) ...
[5ae29451-85d7-4b59-98f5-365ec77fc147] 2024-06-13T14:17:48+02:00 INFO metabase.core System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "11.0.23+9",
 "java.vendor" "Eclipse Adoptium",
 "java.vendor.url" "https://adoptium.net/",
 "java.version" "11.0.23",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "11.0.23+9",
 "os.name" "Linux",
 "os.version" "4.19.128-microsoft-standard",
 "user.language" "en",
 "user.timezone" "GMT"}
...
```

No Errors here Error is in Frontend.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "de",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "4.19.128-microsoft-standard",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-13",
      "tag": "v0.50.3",
      "hash": "855535b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Workaround exits using `scale:Ordinal`

### Additional context

Error only seen using an Oracle Database. Using H2-DB works fine

Using `scale: Ordinal` works as expected.
grafik

Request to database works fine and result set is shown.:
grafik

Error is thrown in frontend while rendering the chart:
grafik

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/44128

### Description

The new implementation of cartesian charts use `dayjs` instead of `moment` since it has been deprecated. Dayjs relies on browser APIs but it can behave differently depending on a browser engine. Turns out Safari does not support non-IANA time zones, that are offsets, such as `+00:00` as they come from the backend side. Since there are cases when an arbitrary offset does not have a non-DST IANA timezone, I went with the approach of adding or subtracting the offset value in minutes.

### How to verify

- Revert all changes except for the new `safari-non-iana-timezone-repro-44128` story
- Run storybook
- Open the story in Safari (I could repro on 17.1.2)
- Ensure it fails
- Return back all the changes
- Ensure the story works in Safari

### Demo

Works in Safari:
Screenshot 2024-06-14 at 3 01 05 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/lib/time.ts [hunk 1]
```diff
@@ -197,3 +197,45 @@ export function parseTimestamp(
...
+    const matchingTimezone = getTimezoneWithOffset(timezone);
+
+    if (!matchingTimezone) {
+      console.warn(`Could not find a time zone with offset ${timezone}`);
+      return timezone;
+    }
+
+    return matchingTimezone;
+  } catch (e) {
+    console.warn(e);
```
Comment (heypoom) [inline frontend/src/metabase/lib/time.ts:238]: should we also add a prefix message so we knows where the message comes from, when the sourcemap isn't available?

File: frontend/src/metabase/lib/time.ts [hunk 2]
```diff
@@ -197,3 +197,45 @@ export function parseTimestamp(
...
+
+  const totalOffsetMinutes =
+    (offsetHours * 60 + offsetMinutes) * (offsetSign === "+" ? 1 : -1);
+
+  const matchingZones = moment.tz.names().filter(zone => {
+    const tzOffset = moment.tz(zone).utcOffset();
+    return tzOffset === totalOffsetMinutes;
+  });
+
+  const etcZone = matchingZones.find(zone => zone.startsWith("Etc/GMT"));
```
Comment (heypoom) [inline frontend/src/metabase/lib/time.ts:219]: might be nice to add a small comment here on why we prioritize Etc/GMT here instead of just using the first matching timezone

**Review by heypoom — APPROVED** [review]
The fix looks good to me!

File: frontend/src/metabase/lib/time.ts (hunk 1 above)
Comment (alxnddr) [reply frontend/src/metabase/lib/time.ts]: I removed this code as I decided to go with a different approach

File: frontend/src/metabase/lib/time.ts (hunk 2 above)
Comment (alxnddr) [reply frontend/src/metabase/lib/time.ts]: I realized that this logic was not correct for arbitrary offsets like +9:30. Even if there is an IANA time zone for such value, it can be a DST timezone. So it would be more correct to just apply the offset manually

File: frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.ts [hunk 3]
```diff
@@ -249,10 +249,28 @@ export function getLargestInterval(intervals: TimeSeriesInterval[]) {
   });
 }
 
+const isTimezoneInOffsetFormat = (timezone: string) => {
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.ts:252]: you could use regex groups and extract the sign, hours, and minutes here without parsing it again

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.ts (hunk 3 above)
Comment (alxnddr) [reply frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.ts]: Thanks, I addressed that

**Comment by uladzimirdev** [comment]
in my branch (2 weeks behind master) this story works in safari 
image

**Review by uladzimirdev — APPROVED** [review]

**Review by JesseSDevaney — APPROVED** [review]
