### PR TITLE
fix: check email in update before validing for sso

### LINKED ISSUE #63581: Non-admin SSO users can't change language in Account Settings
### Describe the bug

It is not possible to change Language in Account settings when the user is an SSO user and does not have admin permissions.

### To Reproduce

1. Enable SSO
2. Log in with an SSO user that does not have admin permissions
3. Go to account settings and try to change the language
4. See the error:
Image

### Expected behavior

This should work.

### Logs

Reported on 1.55.14, reproduced on 1.56.5.6 and on master (stats).

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "athena",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2025-09-15",
      "tag": "v1.56.5.6",
      "hash": "9a3297a"
    },
    "settings": {
      "report-timezone": "Etc/UTC"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Reported by a customer on v1.55.14.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edpaget**
closes #63581
closes #60456

### Description

Changes to any user attribute for sso users were failing preventing them from being to set their user locale. This was due to us not checking if `email` is present in the body of the update request before failing a `check-403` call if the user has an sso source.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/users/api.clj [hunk 1]
```diff
@@ -444,7 +444,8 @@
   ;; only allow updates if the specified account is active
   (api/let-404 [user-before-update (fetch-user :id id, :is_active true)]
     ;; Google/LDAP non-admin users can't change their email to prevent account hijacking
-    (api/check-403 (valid-email-update? user-before-update email))
+    (when (contains? body :email)
+      (api/check-403 (valid-email-update? user-before-update email)))
```
Comment (johnswanson) [inline src/metabase/users/api.clj:448]: nittiest of nits, but wonder if `valid-email-update?` should just take `user-before-update` and `updates` and be something like
```
 (defn- valid-email-update?
  "This predicate tests whether or not the user is allowed to update the email address associated with this account."
  [{:keys [sso_source email]} {:as updates maybe-new-email :email}]
  (or
   ;; Admin users can update
   api/*is-superuser?*
   ;; We're not updating the email at all
   (not (contains? updates :email))
   ;; We're 'updating' the email but new value's the same as the old value
   (= email maybe-new-email)
   ;; We should not allow a regular user to change their email address if they are a google/ldap user
   (and
    (not (= :google sso_source))
    (not (= :ldap sso_source)))))
```

**Review by johnswanson — APPROVED** [review]

File: src/metabase/users/api.clj (hunk 1 above)
Comment (edpaget) [reply src/metabase/users/api.clj:448]: I think that would be a valid way to do but we should probably update the other validations to work the same way if we did that. The valid first/last name change method also just checks if we using sso and has the `when (contains? body ...` check in the PUT method
