### PR TITLE
Fix `mu/fn` and `mu/defn` support for map schemas on key-value args 

### LINKED ISSUE #46864: Our `mu/defn` and `mu/fn` macros don't work correctly on functions with rest parameters and schemas
```clj
(mu/defn my-plus :- :int
  [x :- :int
   y :- :int
   & more :- [:sequential :int]]
  (reduce + (list* x y more)))
```

macroexpands to 

```clj
(def my-plus
  "Inputs: [x :- :int y :- :int & more :- [:sequential :int]]\n  Return: :int"
  (let [&f (fn my_plus90163 [x y & more] (reduce + (list* x y more)))]
    (fn ([a b c]
         (try
           (metabase.util.malli.fn/validate-input {:fn-name 'my-plus} :int a)
           (metabase.util.malli.fn/validate-input {:fn-name 'my-plus} :int b)
           (metabase.util.malli.fn/validate-input {:fn-name 'my-plus} [:sequential :int] c)
           (->> (&f a b c) (metabase.util.malli.fn/validate-output {:fn-name 'my-plus} :int))
           (catch java.lang.Exception error (throw (metabase.util.malli.fn/fixup-stacktrace error))))))))
```
notice that the new function does has the signature `(f a b c)` rather than `(f a b & c)`.

### PR DESCRIPTION
**Pull request by camsaul**
Things like

```clj
(mu/defn my-fn [& {:as options} :- [:map [:type :keyword]]]
  (:type options))
```

now validate input correctly.

Fixes #46864 

Also made a small tweak to the cljfmt config (for `let*`, only used in one file) and fixed some errors with the `./bin/cljfmt-updated.sh` and `kondo-updated.sh` scripts I found when trying them on a different computer

### CODE REVIEW

File: src/metabase/util/malli/fn.clj [hunk 1]
```diff
@@ -189,41 +213,43 @@
...
+                       args)]
     (concat
      (for [n (range (count normal-args))]
        (symbol (str (char (+ (int \a) n)))))
-     (when varargs?
-       ['more]))))
+     (case varargs-type
+       :varargs/sequential ['more]
+       :varargs/map        ['kvs]
+       nil))))
```
Comment (appleby) [inline src/metabase/util/malli/fn.clj:230]: TIL: clojure's `case` does not return `nil` by default

**Review by appleby — APPROVED** [review]

File: src/metabase/util/malli/fn.clj (hunk 1 above)
Comment (metamben) [reply src/metabase/util/malli/fn.clj:230]: `No matching clause` is a famous exception.
