### PR TITLE
Fix XLSX month bucketing regression

### LINKED ISSUE #23980: Exports fail on specific date styles
**Describe the bug**
When setting the global config of date style to:
- 7 January, 2018
- Sunday, January 7, 2018

XLSX exports will fail with a stack trace

**Logs**
<details>
```
metabase-postgres         | 2022-07-15 00:26:42,364 ERROR middleware.catch-exceptions :: Error processing query: Error running query
metabase-postgres         | {:database_id 2,
metabase-postgres         |  :started_at #t "2022-07-15T00:26:42.259757Z[GMT]",
metabase-postgres         |  :via
metabase-postgres         |  [{:status :failed,
metabase-postgres         |    :class clojure.lang.ExceptionInfo,
metabase-postgres         |    :error "Error reducing result rows",
metabase-postgres         |    :stacktrace
metabase-postgres         |    ["--> query_processor.context.default$default_reducef$fn__38690.invoke(default.clj:59)"
metabase-postgres         |     "query_processor.context.default$default_reducef.invokeStatic(default.clj:56)"
metabase-postgres         |     "query_processor.context.default$default_reducef.invoke(default.clj:48)"
metabase-postgres         |     "query_processor.context$reducef.invokeStatic(context.clj:69)"
metabase-postgres         |     "query_processor.context$reducef.invoke(context.clj:62)"
metabase-postgres         |     "query_processor.context.default$default_runf$respond_STAR___38694.invoke(default.clj:68)"
metabase-postgres         |     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:507)"
metabase-postgres         |     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
metabase-postgres         |     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)"
metabase-postgres         |     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)"
metabase-postgres         |     "driver.sql_jdbc$fn__90280.invokeStatic(sql_jdbc.clj:54)"
metabase-postgres         |     "driver.sql_jdbc$fn__90280.invoke(sql_jdbc.clj:52)"
metabase-postgres         |     "query_processor.context$executef.invokeStatic(context.clj:59)"
metabase-postgres         |     "query_processor.context$executef.invoke(context.clj:48)"
metabase-postgres         |     "query_processor.context.default$default_runf.invokeStatic(default.clj:67)"
metabase-postgres         |     "query_processor.context.default$default_runf.invoke(default.clj:65)"
metabase-postgres         |     "query_processor.context$runf.invokeStatic(context.clj:45)"
metabase-postgres         |     "query_processor.context$runf.invoke(context.clj:39)"
metabase-postgres         |     "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)"
metabase-postgres         |     "query_processor.reducible$identity_qp.invoke(reducible.clj:9)"
metabase-postgres         |     "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___52196.invoke(cache.clj:220)"
metabase-postgres         |     "query_processor.middleware.permissions$check_query_permissions$fn__47754.invoke(permissions.clj:109)"
metabase-postgres         |     "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__84263.invoke(permissions.clj:127)"
metabase-postgres         |     "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__86045.invoke(column_level_perms_check.clj:30)"
metabase-postgres         |     "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__51137.invoke(mbql_to_native.clj:23)"
metabase-postgres         |     "query_processor$fn__53672$combined_post_process__53677$combined_post_process_STAR___53678.invoke(query_processor.clj:211)"
metabase-postgres         |     "query_processor$fn__53672$combined_pre_process__53673$combined_pre_process_STAR___53674.invoke(query_processor.clj:208)"
metabase-postgres         |     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52117$fn__52122.invoke(resolve_database_and_driver.clj:35)"
metabase-postgres         |     "driver$do_with_driver.invokeStatic(driver.clj:75)"
metabase-postgres         |     "driver$do_with_driver.invoke(driver.clj:71)"
metabase-postgres         |     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52117.invoke(resolve_database_and_driver.clj:34)"
metabase-postgres         |     "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__48186.invoke(fetch_source_query.clj:346)"
metabase-postgres         |     "query_processor.middleware.store$initialize_store$fn__48374$fn__48375.invoke(store.clj:11)"
metabase-postgres         |     "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
metabase-postgres         |     "query_processor.store$do_with_store.invoke(store.clj:38)"
metabase-postgres         |     "query_processor.middleware.store$initialize_store$fn__48374.invoke(store.clj:10)"
metabase-postgres         |     "query_processor.middleware.normalize_query$normalize$fn__52389.invoke(normalize_query.clj:22)"
metabase-postgres         |     "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__59093.invoke(handle_audit_queries.clj:130)"
metabase-postgres         |     "query_processor.middleware.constraints$add_default_userland_constraints$fn__49442.invoke(constraints.clj:53)"
metabase-postgres         |     "query_processor.middleware.process_userland_query$process_userland_query$fn__52328.invoke(process_userland_query.clj:145)"
metabase-postgres         |     "query_processor.middleware.catch_exceptions$catch_exceptions$fn__52700.invoke(catch_exceptions.clj:167)"
metabase-postgres         |     "query_processor.reducible$async_qp$qp_STAR___44604$thunk__44606.invoke(reducible.clj:100)"
metabase-postgres         |     "query_processor.reducible$async_qp$qp_STAR___44604$fn__44608.invoke(reducible.clj:105)"],
metabase-postgres         |    :error_type :qp,
metabase-postgres         |    :ex-data {:type :qp}}],
metabase-postgres         |  :error_type :qp,
metabase-postgres         |  :json_query
metabase-postgres         |  {:constraints nil,
metabase-postgres         |   :type :query,
metabase-postgres         |   :middleware
metabase-postgres         |   {:js-int-to-string? false,
metabase-postgres         |    :ignore-cached-results? true,
metabase-postgres         |    :process-viz-settings? true,
metabase-postgres         |    :skip-results-metadata? true,
metabase-postgres         |    :format-rows? false},
metabase-postgres         |   :database 2,
metabase-postgres         |   :query
metabase-postgres         |   {:source-table 6,
metabase-postgres         |    :joins
metabase-postgres         |    [{:fields :all,
metabase-postgres         |      :source-table 5,
metabase-postgres         |      :condition [:= [:field 50 nil] [:field 44 {:join-alias "Orders"}]],
metabase-postgres         |      :alias "Orders"}],
metabase-postgres         |    :aggregation [[:sum [:field 40 {:join-alias "Orders"}]] [:sum [:field 37 {:join-alias "Orders"}]]],
metabase-postgres         |    :breakout [[:field 48 {:temporal-unit :month}]]},
metabase-postgres         |   :parameters nil,
metabase-postgres         |   :async? true,
metabase-postgres         |   :cache-ttl nil},
metabase-postgres         |  :native
metabase-postgres         |  {:query
metabase-postgres         |   "SELECT date_trunc('month', \"public\".\"people\".\"created_at\") AS \"created_at\", sum(\"Orders\".\"tax\") AS \"sum\", sum(\"Orders\".\"total\") AS \"sum_2\" FROM \"public\".\"people\" LEFT JOIN \"public\".\"orders\" \"Orders\" ON \"public\".\"people\".\"id\" = \"Orders\".\"user_id\" GROUP BY date_trunc('month', \"public\".\"people\".\"created_at\") ORDER BY date_trunc('month', \"public\".\"people\".\"created_at\") ASC",
metabase-postgres         |   :params nil},
metabase-postgres         |  :status :failed,
metabase-postgres         |  :class java.lang.NullPointerException,
metabase-postgres         |  :stacktrace [nil],
metabase-postgres         |  :card_id 1,
metabase-postgres         |  :context :xlsx-download,
metabase-postgres         |  :error nil,
metabase-postgres         |  :row_count 0,
metabase-postgres         |  :running_time 0,
metabase-postgres         |  :preprocessed
metabase-postgres         |  {:type :query,
metabase-postgres         |   :middleware
metabase-postgres         |   {:js-int-to-string? false,
metabase-postgres         |    :ignore-cached-results? true,
metabase-postgres         |    :process-viz-settings? true,
metabase-postgres         |    :skip-results-metadata? true,
metabase-postgres         |    :format-rows? false},
metabase-postgres         |   :info
metabase-postgres         |   {:executed-by 1,
metabase-postgres         |    :context :xlsx-download,
metabase-postgres         |    :card-id 1,
metabase-postgres         |    :card-name "People, Sum of  and Sum of , Grouped by Created At (month)"},
metabase-postgres         |   :database 2,
metabase-postgres         |   :query
metabase-postgres         |   {:source-table 6,
metabase-postgres         |    :aggregation
metabase-postgres         |    [[:aggregation-options [:sum [:field 40 {:join-alias "Orders"}]] {:name "sum"}]
metabase-postgres         |     [:aggregation-options [:sum [:field 37 {:join-alias "Orders"}]] {:name "sum_2"}]],
metabase-postgres         |    :breakout [[:field 48 {:temporal-unit :month}]],
metabase-postgres         |    :order-by [[:asc [:field 48 {:temporal-unit :month}]]],
metabase-postgres         |    :joins
metabase-postgres         |    [{:alias "Orders",
metabase-postgres         |      :strategy :left-join,
metabase-postgres         |      :fields
metabase-postgres         |      [[:field 38 {:join-alias "Orders"}]
metabase-postgres         |       [:field 44 {:join-alias "Orders"}]
metabase-postgres         |       [:field 43 {:join-alias "Orders"}]
metabase-postgres         |       [:field 39 {:join-alias "Orders"}]
metabase-postgres         |       [:field 40 {:join-alias "Orders"}]
metabase-postgres         |       [:field 37 {:join-alias "Orders"}]
metabase-postgres         |       [:field 45 {:join-alias "Orders"}]
metabase-postgres         |       [:field 42 {:temporal-unit :default, :join-alias "Orders"}]
metabase-postgres         |       [:field 41 {:join-alias "Orders"}]],
metabase-postgres         |      :source-table 5,
metabase-postgres         |      :condition [:= [:field 50 nil] [:field 44 {:join-alias "Orders"}]]}]},
metabase-postgres         |   :async? true},
metabase-postgres         |  :data {:rows [], :cols []}}
```
</details>
**To Reproduce**
1) set up Metabase
2) go to settings->admin->localization and set the date options to the ones described above
3) click new->question->People-> Sum of Longitude by Created at
4) click on download as XLSX
5) open the downloaded file

**Expected behavior**
Get an export without errors :)

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop os 22.04
- Your databases: H2
- Metabase version: 43.4
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
P2, you can get around changing the date format of the column in the report

**Additional context**
Reported by a customer

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes #23980

Basically the issue was we had a map for determining what style to use for formatting month buckets based on the current date format. But this map wasn't exhaustive -- it included the date styles that could be set in the viz settings on a question, but not a couple of styles that could be set in the admin panel. This led to an NPE later on in the code.

I've changed it to just use a `case` statement with a default value so that we never throw an error here.

### CODE REVIEW

**Comment by paoliniluis** [comment]
Just tested and works

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 1]
```diff
@@ -198,17 +198,20 @@
...
-   "yyyy/m/d"     "yyyy/m"
-   "mmmm d, yyyy" "mmmm, yyyy"})
+(defn- month-style
+  "For a given date format, returns the format to use in exports if :unit is :month"
+  [date-format]
+  (case date-format
+    "m/d/yyyy" "m/yyyy"
+    "yyyy/m/d" "yyyy/m"
+    ;; Default for all other styles
+    "mmmm, yyyy"))
```
Comment (camsaul) [inline src/metabase/query_processor/streaming/xlsx.clj:208]: 👍

**Review by camsaul — APPROVED** [review]
