### PR TITLE
Fix Snowflake start of week

### LINKED ISSUE #20999: First Day of Week Setting off by one in Snowflake
**Describe the bug**
When grouping by week in the question editor, the date ranges start on the day of the week **one day after**  what is set in the Localization Settings.  For instance, when we set our "First Day of Week" setting set to Sunday, the date ranges start on Monday.  We are not setting any JDBC connection string options in the database connection settings. We do have our Snowflake account WEEK_START parameter set to 1 on the account level, however changing it does not affect the issue.

Also to note, the Metabase SQL editor is not affected by the "First Day of Week" setting.  It is being correctly controlled by our Snowflake account and session WEEK_START parameter.

First Day of Week set to Sunday:
Screen Shot 2022-03-14 at 1 49 45 PM

In the Question Editor, week groups start on Mondays (this is the issue):
Screen Shot 2022-03-14 at 1 42 52 PM

**Logs**

```
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:12-07:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 9.1 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (14 idle, 0 queued) (148 total active threads) Queries in flight: 0 (0 queued)
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:12-07:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 14.8 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (14 idle, 0 queued) (148 total active threads) Queries in flight: 0 (0 queued)
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:12-07:00 DEBUG metabase.server.middleware.log GET /api/table/3393/query_metadata 200 17.7 ms (9 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (14 idle, 0 queued) (148 total active threads) Queries in flight: 0 (0 queued)
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:12-07:00 DEBUG metabase.server.middleware.log GET /api/database 200 9.8 ms (3 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (14 idle, 0 queued) (148 total active threads) Queries in flight: 0 (0 queued)
[bcce7941-c1ae-4460-9ba0-b75bc22773af] 2022-03-14T13:58:13-07:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 644.1 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 2/50 (15 idle, 0 queued) (151 total active threads) Queries in flight: 0 (0 queued); snowflake DB 9 connections: 0/1 (0 threads blocked)
```

**To Reproduce**
1. Using a Snowflake database, group a timestamp or date column by week in the question editor.
2. Notice that the date ranges all start 1 day after the "First Day of Week" Localization setting is set to.

**Expected behavior**
When grouping by week in the Question editor, the date ranges should start on whatever is set for "First Day of Week".

**Screenshots**

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.14.262-200.489.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-28",
      "tag": "v0.42.2",
      "branch": "release-x.42.x",
      "hash": "d6ff494"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

This is annoying verging on blocking at our organization.  We have both Snowflake and Postgres databases set up in Metabase, and having to pick which one has the correct week_start is causing a big headache.

**Additional context**
I know that PR #19375 was supposed to address the "First Day of Week" setting in Snowflake, but we are still having this off by one problem.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #20999

The root issue here was that we were Setting both the `WEEK_START` connection parameter **and** doing a start-of-week adjustments in the queries we generated. We only should have been doing one or the other.

I ended up sticking with the `WEEK_START` connection parameter for now and removing the start-of-week arithmetic in the generated SQL, and now things are working as expected.

Previously we only specified the `WEEK_START` connection parameter if someone did not explicitly include it in the additional connection string options. There is no way things will work correctly if people explicitly include it in the options and it differs from what we would have set -- so I removed this logic and it now logs a warning instead if you include `WEEK_START` in the additional options. See

https://github.com/metabase/metabase/compare/fix-snowflake-week-start?expand=1#diff-5472d9d00fa628881a6887a87e2be860f2d679f85aeada5d9f2c86173646800aR57-R58

I also made some tweaks so the SQL JDBC driver connection pool cache is invalidated when the (unpooled) JDBC spec returned by `connection-details->spec` changes, rather than when the details map itself changes. This means that changes to other things outside of connection details that affect the JDBC connection parameters, for example the `report-timezone` or `start-of-week` Settings will now properly result in the connection pool cache being flushed

### CODE REVIEW

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 1]
```diff
@@ -45,23 +45,17 @@
...
-        (assoc details :week_start (or (start-of-week-setting->snowflake-offset) 7))
-        details))
-    (assoc details :week_start (or (start-of-week-setting->snowflake-offset) 7))))
+  (inc (driver.common/start-of-week->int)))
 
 (defmethod sql-jdbc.conn/connection-details->spec :snowflake
-  [_ {:keys [account], :as opts}]
+  [_ {:keys [account additional-options], :as details}]
+  (when (get "week_start" (sql-jdbc.common/additional-options->map additional-options :url))
+    (log/warn (trs "You should not set WEEK_START in Snowflake connection options; this might lead to incorrect results. Set the Start of Week Setting instead.")))
```
Comment (camsaul) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:58]: warning if you try to set `WEEK_START` yourself

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 2]
```diff
@@ -76,17 +70,19 @@
...
                 ;; stuff doesn't work, even though we ultimately override this when we set the session timezone
-                :timezone                                   "UTC"}
-               (-> opts
-                   ;; original version of the Snowflake driver incorrectly used `dbname` in the details fields instead of
-                   ;; `db`. If we run across `dbname`, correct our behavior
-                   maybe-set-week-start
+                :timezone                                   "UTC"
+                ;; tell Snowflake to use the same start of week that we have set for the
+                ;; [[metabase.public-settings/start-of-week]] Setting.
+                :week_start                                 (start-of-week-setting->snowflake-offset)}
```
Comment (camsaul) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:76]: Now we always set it regardless

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj [hunk 3]
```diff
@@ -180,40 +180,42 @@
 (deftest week-start-test
   (mt/test-driver :snowflake
     (testing "The WEEK_START session setting is correctly incorporated"
-      (letfn [(invalidate-pool! []
-                (sql-jdbc.conn/invalidate-pool-for-db! (mt/db)))
```
Comment (camsaul) [inline modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj:184]: Manually invalidating the connection pool like we do in tests is no longer needed so I removed it here

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj [hunk 4]
```diff
@@ -180,40 +180,42 @@
...
-                                                       :value  date-str}]}))
+                     (qp/process-query {:database   (mt/id)
+                                        :type       :native
+                                        :native     {:query         (str "SELECT DAYOFWEEK({{filter_date}})")
+                                                     :template-tags {:filter_date {:name         "filter_date"
+                                                                                   :display_name "Just A Date"
+                                                                                   :type         "date"}}}
+                                        :parameters [{:type   "date/single"
+                                                      :target ["variable" ["template-tag" "filter_date"]]
+                                                      :value  date-str}]}))
```
Comment (camsaul) [inline modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj:193]: Indentation fix

File: modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj [hunk 5]
```diff
@@ -180,40 +180,42 @@
...
-          ;; invalidate pool again after the test to ensure the connection cache forgets the temp setting version
-          (finally (invalidate-pool!)))))))
+        (testing "under the default value of 7 (Sunday)"
+          (mt/with-temporary-setting-values [start-of-week :sunday]
+            (is (= 1 (run-dayofweek-query "2021-01-10")) "Sunday (first day of the week)")
+            (is (= 2 (run-dayofweek-query "2021-01-11")) "Monday (second day of the week)")))
+        (testing "when we control it via the Metabase setting value"
+          (mt/with-temporary-setting-values [start-of-week :monday]
+            (is (= 7 (run-dayofweek-query "2021-01-10")) "Sunday (last day of week now)")
+            (is (= 1 (run-dayofweek-query "2021-01-11")) "Monday (first day of week now)")))))))
```
Comment (camsaul) [inline modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj:202]: Removed the `(try ... (finally ...))` form that manually nuked the Snowflake connection pool since it's done automatically now. Tweaked the tests a little so the comments next to the assertions are included as testing context

File: shared/src/metabase/mbql/schema.cljc [hunk 6]
```diff
@@ -41,6 +41,9 @@
 
 ;;; ------------------------------------------------- Datetime Stuff -------------------------------------------------
 
+;; `:day-of-week` depends on the [[metabase.public-settings/start-of-week]] Setting, by default Sunday.
+;; 1 = first day of the week (e.g. Sunday)
+;; 7 = last day of the week (e.g. Saturday)
```
Comment (camsaul) [inline shared/src/metabase/mbql/schema.cljc:46]: This was not really clearly specified anywhere so I wrote it down to make sure things are clear

File: src/metabase/driver/common.clj [hunk 7]
```diff
@@ -435,16 +435,18 @@
 (def ^:private ^clojure.lang.PersistentVector days-of-week
   [:monday :tuesday :wednesday :thursday :friday :saturday :sunday])
 
-(defn start-of-week->int
-  "Returns the int value for the current :start-of-week setting value, which ranges from 0 (:monday) to 6 (:sunday).
-  If the :start-of-week setting does not have a value, then `nil` is returned."
+(s/defn start-of-week->int :- (s/pred (fn [n] (and (integer? n) (<= 0 n 6)))
+                                      "Start of week integer")
+  "Returns the int value for the current [[metabase.public-settings/start-of-week]] Setting value, which ranges from
+  `0` (`:monday`) to `6` (`:sunday`). This is guaranteed to return a value."
```
Comment (camsaul) [inline src/metabase/driver/common.clj:441]: Docstring was off a little here. This never returns `nil`. It returns the default value `6` for `:sunday` if `start-of-week` is not set.

File: src/metabase/driver/sql_jdbc/connection.clj [hunk 8]
```diff
@@ -128,7 +129,9 @@
   [database]
   {:pre [(or nil? (instance? (type Database) database))]}
   (if (some? database)
-    (hash (:details database))
+    (hash [(:details database)
+           (driver/report-timezone)
+           (public-settings/start-of-week)])
```
Comment (camsaul) [inline src/metabase/driver/sql_jdbc/connection.clj:134]: Report timezone and start of week are now included in the DB details hash which is used to determine whether the current connection pool for a database is still valid or whether we need to drop it and create a new one. Previously we only hashed the Database `:details` column, but that didn't accurately include stuff that goes in the JDBC spec (e.g. the `WEEK_START` option for Snowflake, which is not based on `:details`). 

Probably the actual correct thing to do here is hash the JDBC connection spec instead of `:details`. I'm going to look into that, but will probably do it as a separate PR either way

File: src/metabase/driver/sql_jdbc/connection.clj [hunk 9]
```diff
@@ -119,22 +119,21 @@
...
+(defn- jdbc-spec-hash
+  "Computes a hash value for the JDBC connection spec based on `database`'s `:details` map, for the purpose of
+  determining if details changed and therefore the existing connection pool needs to be invalidated."
+  [{driver :engine, :keys [details], :as database}]
   {:pre [(or nil? (instance? (type Database) database))]}
-  (if (some? database)
-    (hash (:details database))
-    nil))
+  (when (some? database)
+    (hash (connection-details->spec driver details))))
```
Comment (camsaul) [inline src/metabase/driver/sql_jdbc/connection.clj:131]: Just hashing `details` isn't enough because some databases such as Snowflake will change the actual underlying connection parameters based on other factors such as the `start-of-week` Setting. Now we hash the JDBC spec and use that as a key instead

File: test/metabase/driver/sql_jdbc/connection_test.clj [hunk 10]
```diff
@@ -75,50 +75,64 @@
...
 
+(deftest same-connection-details-result-in-equal-specs-test
+  (testing "Two JDBC specs created with the same details must be considered equal for the connection pool cache to work correctly"
+    ;; this is only really a concern for drivers like Spark SQL that create custom DataSources instead of plain details
+    ;; maps -- those DataSources need to be considered equal based on the connection string/properties
+    (mt/test-drivers (sql-jdbc.tu/sql-jdbc-drivers)
+      (let [details (:details (mt/db))
+            spec-1  (sql-jdbc.conn/connection-details->spec mt/*driver* details)
+            spec-2  (sql-jdbc.conn/connection-details->spec mt/*driver* details)]
+        (is (= spec-1 spec-2))))))
```
Comment (camsaul) [inline test/metabase/driver/sql_jdbc/connection_test.clj:86]: Added a test to make sure that two specs created with identical details are considered equal. This test will run for all SQL JDBC drivers. This only really affects drivers that return a `{:datasource javax.sql.DataSource}` spec since just reifying it will not result in the objects being considered equal even if the underlying connection URL and properties are. A record type is more appropriate here; this test should catch situations where we forget to use them

File: test/metabase/driver/sql_jdbc/connection_test.clj [hunk 11]
```diff
@@ -75,50 +75,64 @@
...
+              (cond-> details
+                ;; swap localhost and 127.0.0.1
+                (= "localhost" (:host details))
+                (assoc :host "127.0.0.1")
+
+                (= "127.0.0.1" (:host details))
+                (assoc :host "localhost")
+
+                :else
+                (assoc :new-config "something"))))))
```
Comment (camsaul) [inline test/metabase/driver/sql_jdbc/connection_test.clj:105]: Moved this out of the test below to make it a little more readable. No changes to logic.

File: test/metabase/driver/sql_jdbc/connection_test.clj [hunk 12]
```diff
@@ -133,7 +147,7 @@
                     ;; even after getting the latest `DatabaseInstance`
                     (sync/sync-database! db {:scan :schema})
                     (is (some? pool-spec-2))
-                    (is (= 1 @hash-change-called-times))
+                    (is (= 1 @hash-change-called-times) "One hash change should have been logged")
```
Comment (camsaul) [inline test/metabase/driver/sql_jdbc/connection_test.clj:150]: Added context because otherwise a test failure like `(not= 1 0)` is a little bit confusing to read.

File: src/metabase/driver/common.clj (hunk 7 above)
Comment (dpsutton) [reply src/metabase/driver/common.clj:441]: If that's the case should we get rid of the `when-let`? Structurally, this still seems like it is ready to return nil.

**Review by dpsutton — APPROVED** [review]

File: src/metabase/driver/common.clj (hunk 7 above)
Comment (camsaul) [reply src/metabase/driver/common.clj:441]: Yeah that's true. I'll fix it

File: src/metabase/driver/common.clj [hunk 13]
```diff
@@ -435,16 +435,18 @@
...
   {:added "0.42.0"}
   []
   (when-let [v (setting/get-value-of-type :keyword :start-of-week)]
     (.indexOf days-of-week v)))
```
Comment (camsaul) [inline src/metabase/driver/common.clj:445]:
```suggestion
  (.indexOf days-of-week (setting/get-value-of-type :keyword :start-of-week)))
```

File: src/metabase/driver/common.clj (hunk 7 above)
Comment (camsaul) [reply src/metabase/driver/common.clj:441]: fixed

**Review by flamber — APPROVED** [review]
This seems to work as intended now - also for Snowflake SQL queries, though it will cause problems for anyone who had previously written queries with the [workaround previously used](https://github.com/metabase/metabase/issues/16114#issuecomment-850837877).

I'm not seeing any warnings in the log, when I set `WEEK_START=7` (or any other value).
