### PR TITLE
Wrap sqlserver boolean expressions in a case statement

### LINKED ISSUE #53805: Boolean expression in a custom column is accepted but does not not work on SQL Server
### Describe the bug

SQL Server does not have a boolean data type so boolean expressions cannot be returned in the SELECT clause.

As a result, a custom expression returning a boolean does work on SQL Server, it has to be wrapped into a case() expression. For example:
- `[ColumnA] > [ColumnB]` - does not work, but accepted as valid
- case([ColumnA] > [ColumnB], True, False) - works
- case([ColumnA] > [ColumnB], 1, 0) - works

### To Reproduce

Try the expressions above on a SQL Server database.

### Expected behavior

In case of SQL Server - either prevent adding a custom expression returning a boolean (as it was the case before v51),
or - perhaps better - use a CASE expression in the SQL.

### Logs

_No response_

### Information about your Metabase installation

```JSON
1.52.9.1
```

### Severity

Confusing / annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/53805

### Description

SQL Server doesn't have a boolean data type so we can't select comparison expression like `a > b`. To get around this we can wrap these comparison expressions in a case statement and then convert them to a `bit` type. 

### How to verify

1. Create a custom expression with a comparison operator on a sql server DB
2. The query should succeed and return true or false. The generated sql should have the comparison expression wrapped in a case statement and casted to a bit. 

### Demo

https://github.com/user-attachments/assets/2ce39059-29cc-467d-851f-d9d20294b070

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj [hunk 1]
```diff
@@ -590,9 +590,17 @@
         ;; Tell [[sql.qp/as]] to insert a cast to :bit for boolean expressions. This ensures the :type/Boolean is
         ;; preserved in results metadata, so downstream questions and query stages can use the column in contexts
         ;; where a boolean is required; otherwise, SQL Server returns a value of type int for `SELECT 1 AS MyBool`.
-        maybe-add-cast #(cond-> %
+        ;; For comparison expressions (like [:> field1 field2]), we use ::sql.qp/wrap-in-case instead since SQL Server
+        ;; cannot CAST a comparison result directly - it needs CASE WHEN expr THEN 1 ELSE 0 END.
+        maybe-add-cast #(cond
+                          (sql.qp.boolean-to-comparison/comparison-expression-clause? %)
+                          (driver-api/assoc-field-options % ::sql.qp/wrap-in-case true)
+
```
Comment (bshepherdson) [inline modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj]: The logic immediately below looks like it's doing something very similar. Even if we do want both conditions here, it seems like it would be best to use the same approach for both - either cast to `BIT` or wrap in a `CASE`. (Probably casting to `BIT`.)

File: modules/drivers/sqlserver/test/metabase/driver/sqlserver_test.clj [hunk 2]
```diff
@@ -644,6 +644,56 @@
                   (is (= expected-types
                          (map :base_type results-metadata-cols))))))))))))
 
+(deftest ^:parallel comparison-expression-in-custom-column-test
+  (mt/test-driver :sqlserver
+    (testing "Comparison expressions in custom columns are wrapped in CASE statements (#53805)"
+      (testing "Greater than comparison between two fields"
+        (let [query (mt/mbql-query orders
```
Comment (bshepherdson) [inline modules/drivers/sqlserver/test/metabase/driver/sqlserver_test.clj]: This test should be using `lib/*` functions not `mt/mbql-query` to build the queries.

File: modules/drivers/sqlserver/test/metabase/driver/sqlserver_test.clj [hunk 3]
```diff
@@ -644,6 +644,56 @@
...
+                       :fields      [[:expression "subtotal-gt-total"]]
+                       :limit       1})]
+          (testing "Should generate CASE WHEN ... THEN 1 ELSE 0 END"
+            (is (= ["SELECT"
+                    "  TOP(1) CASE"
+                    "    WHEN dbo.orders.subtotal > dbo.orders.total THEN 1"
+                    "    ELSE 0"
+                    "  END AS subtotal - gt - total"
+                    "FROM"
+                    "  dbo.orders"]
```
Comment (bshepherdson) [inline modules/drivers/sqlserver/test/metabase/driver/sqlserver_test.clj]: This is overfitting; better to grep the SQL for just the `CASE` part and ignore newlines.

**Review by bshepherdson — CHANGES_REQUESTED** [review]

File: modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj (hunk 1 above)
Comment (rileythomp) [reply modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj]: I think in this case we need both, first wrap the expression in a case statement, and then cast it to a bit. Updated the PR to do that.

File: modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj [hunk 4]
```diff
@@ -603,9 +603,19 @@
         ;; Tell [[sql.qp/as]] to insert a cast to :bit for boolean expressions. This ensures the :type/Boolean is
         ;; preserved in results metadata, so downstream questions and query stages can use the column in contexts
         ;; where a boolean is required; otherwise, SQL Server returns a value of type int for `SELECT 1 AS MyBool`.
-        maybe-add-cast #(cond-> %
```
Comment (bshepherdson) [inline modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj:606]: Doesn't this still work as a `cond->` ?

File: src/metabase/driver/sql/query_processor/boolean_to_comparison.clj [hunk 5]
```diff
@@ -79,6 +79,20 @@
   (and (driver-api/is-clause? :expression clause)
        (boolean-value-clause? (driver-api/expression-with-name sql.qp/*inner-query* (second clause)))))
 
+(def ^:private comparison-operators
+  #{:= :!= :> :>= :< :<= :is-null :not-null :is-empty :not-empty :starts-with :ends-with :contains :does-not-contain :between :inside})
```
Comment (bshepherdson) [inline src/metabase/driver/sql/query_processor/boolean_to_comparison.clj]: This should probably live in the `lib.schema.*` namespaces, or at least be referenced from there. I'm concerned about how easy it would be to forget to update this list and introduce an obscure bug.

**Review by bshepherdson — APPROVED** [review]

File: modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj (hunk 4 above)
Comment (rileythomp) [reply modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj:606]: `boolean-expression-clause?` is bit of a misnomer because it looks for a boolean `:value` clause, so it would have to look like this:
```clojure
#(cond-> %
   (sql.qp.boolean-to-comparison/comparison-expression-clause? %)
   (driver-api/assoc-field-options ::sql.qp/wrap-in-case true)

   (or (sql.qp.boolean-to-comparison/comparison-expression-clause? %)
       (sql.qp.boolean-to-comparison/boolean-expression-clause? %))
   (driver-api/assoc-field-options % ::sql.qp/add-cast :bit))
```
I don't feel strongly either way so lmk if you prefer this

File: src/metabase/driver/sql/query_processor/boolean_to_comparison.clj (hunk 5 above)
Comment (rileythomp) [reply src/metabase/driver/sql/query_processor/boolean_to_comparison.clj]: Moved it to `lib.schema.filter`
