### PR TITLE
Remove db paging

### LINKED ISSUE #16983: Only first 50 databases are displayed
**Describe the bug**
After the updated to v0.40 we can only see and operate with the first 50 databases ordered by Database Name.

**To Reproduce**
1 - Upgrade to v0.40
2 - Get the list of DBs, you only can see the first 50
2 - Try to edit / sync / change permissions / data model for any database after 50th order by name.They don't exist but they are in `metabase_database `

**Expected behavior**
Show and use any of your existing database connections, not only the first 50

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "es-ES",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_291-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_291",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.291-b10",
    "os.name": "Windows Server 2012 R2",
    "os.version": "6.3",
    "user.language": "es",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "googleanalytics",
      "bigquery",
      "sqlserver",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.22"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.40.0",
      "date": "2021-07-08",
      "branch": "master",
      "hash": "961caed"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### PR DESCRIPTION
**Pull request by howonlee**
Pursuant to 16983. Default behavior is actually paging with limit 50, not unlimited like I thought, so it wasn't safe to just shove in paging willy-nilly. All the actual work is done, just splice this back in whenever we're ready to actually page

### CODE REVIEW

**Comment by alxnddr** [comment]
Closes https://github.com/metabase/metabase/issues/16983

**Review by alxnddr — APPROVED** [review]
@howonlee thanks for a quick fix!
Checked locally 👍 I'd wait for one more approval from the BE team

File: test/metabase/api/database_test.clj [hunk 1]
```diff
@@ -362,15 +362,6 @@
               (is (= expected-keys
                      (set (keys db)))))))))
 
-    (doseq [query-param ["?limit=2"
```
[the remark this answers is not in the document]
Comment (howonlee) [reply test/metabase/api/database_test.clj:365]: makes sense

File: src/metabase/api/collection.clj [hunk 2]
```diff
@@ -406,14 +406,23 @@
...
-                     :offset   offset-paging/*offset*}]
-    {:total  (->> (db/query total-query) first :count)
-     :data   (->> (db/query rows-query) post-process-rows)
-     :limit  offset-paging/*limit*
-     :offset offset-paging/*offset*
-     :models models}))
+                     :order-by sql-order}
+        ;; We didn't implement collection pagination for snippets namespace for root/items
+        ;; Rip out the limit for now and put it back in when we want it
+        limit-query (if (= (:collection-namespace options) "snippets")
```
Comment (dpsutton) [inline src/metabase/api/collection.clj:412]: Just for the future, let's try to refrain from extra work in a PR to fix a P1. Makes it harder to be secure that we are delivering a fix for the P1 without introducing other errors.

File: src/metabase/api/database.clj [hunk 3]
```diff
@@ -220,12 +215,8 @@
...
     {:data  (or (dbs-list :include-tables?                  include-tables?
                           :include-saved-questions-db?      include-saved-questions-db?
-                          :include-saved-questions-tables?  include-saved-questions-tables?
-                          :limit                            offset-paging/*limit*
-                          :offset                           offset-paging/*offset*)
+                          :include-saved-questions-tables?  include-saved-questions-tables?)
                 [])
-     :limit  offset-paging/*limit*
-     :offset offset-paging/*offset*
      :total  (db/count Database)}))
```
Comment (dpsutton) [inline src/metabase/api/database.clj:220]: should this just count the `dbs-list` above? no reason to issue another query.

Also, if this is no longer paginated, do we need/want to revert back to just a vector of databases rather than the `{:data [] :total N}` shape?

Comment (howonlee) [reply src/metabase/api/database.clj:220]: FE can have either / or. It makes it easier to add it back in when we actually do want pagination finally

**Review by jeff303 — APPROVED** [review]
