### PR TITLE
Better handle numeric action parameters with "select" and "radio" types

### LINKED ISSUE #28953: Parameter values are not coerced to numbers when parameter input type is dropdown
**Describe the bug**
If an action has a numeric parameter with a "Dropdown" input type, Metabase doesn't coerce its value to a number before submitting the form, which causes an error.

**To Reproduce**

1. Connect a Postgres / MySQL database and enable actions for it
2. Create a structured model based on this database's table
3. Create an action that takes a numeric parameter (e.g. UPDATE products SET category = "Gadget" WHERE price > {{ price }}`)
4. Set field type to "Number" for numeric parameters
5. Click the "gear" icon on the form field preview panel and set the input type to "Dropdown"
6. Click the "list" icon next to the "gear" icon and provide some value options for a parameter
7. Try to run an action
8. You get an error about string value passed to a numeric parameter

**Expected behavior**
1. Metabase should coerce string filter value to a number before submitting action parameters
2. Metabase shouldn't let people put non-numeric values into the option list

### PR DESCRIPTION
**Pull request by kulyk**
Closes #28953

### Description

Ensures we're coercing values for numeric parameters with "select" or "radio" input values. Adds a few safety nets to prevent us from having non-numbers in the list of options:

* adds validation to options popover before submit
* makes field type change a bit smarter: when'd try to preserve the input type and coerce `valueOptions` to a new field type and throwing away values that can't be converted (e.g. when changing from "string" to "number", value options like `[ "1", "2", "A" ]` would turn into `[ 1, 2 ]`)
* updates sample options for select/radio inputs, so numbers always use numbers and strings always use strings

### How to verify

Follows the steps from #28953

### Demo

https://user-images.githubusercontent.com/17258145/223750916-6d74f5bc-8bea-4991-93c1-7602cd0fb36f.mp4

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29000)

### CODE REVIEW

File: frontend/src/metabase/actions/components/ActionForm/utils.ts [hunk 1]
```diff
@@ -23,14 +23,8 @@ const getOptionsFromArray = (
   options: (number | string)[],
 ): ActionFormOption[] => options.map(o => ({ name: o, value: o }));
 
-const getSampleOptions = () => [
-  { name: t`Option One`, value: 1 },
-  { name: t`Option Two`, value: 2 },
-  { name: t`Option Three`, value: 3 },
-];
```
Comment (iethree) [inline frontend/src/metabase/actions/components/ActionForm/utils.ts:30]: Sample options might not be the best solution here, but the empty array is kinda confusing too

Screen Shot 2023-03-07 at 3 00 48 PM

the radio is even more of a "what am I supposed to do here" ?

Screen Shot 2023-03-07 at 3 24 07 PM

What about a single dummy option that says "Add options to this field" or some other sort of empty state prompt?

File: frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.tsx [hunk 2]
```diff
@@ -42,11 +43,24 @@ function FormFieldEditor({
   const inputTypes = useMemo(getInputTypes, []);
 
   const handleChangeFieldType = (nextFieldType: FieldType) => {
-    const [defaultInputType] = inputTypes[nextFieldType];
+    // When field type changes, we automatically set the first available input type
+    const [nextInputType] = inputTypes[nextFieldType];
+
+    const shouldResetOptions =
+      nextFieldType !== fieldSettings.fieldType ||
+      !inputTypeHasOptions(nextInputType.value);
```
Comment (iethree) [inline frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.tsx:51]: I think auto-erasing user-defined options here will be frustrating to users. What if, instead of clearing the options any time the fieldType changes, if we filter them based on validity?

**Scenario 1**
- I define a list of options: 1,2,3,4,5
- oh crap, i forgot to change the field type to number
- change fieldType to number
- all my options are gone 😢 

**Scenario 2**
- I select number fieldType
- I define a list of options: 1,2,3,4,5
- I realize that my column is actually a text column
- I change the fieldType to string
- all my options are gone 😢 

**What if instead we filter valid options**
- I define text options: 1,2,3,4,5, "none of the above"
- I change the fieldType to number
- now my options are: 1,2,3,4,5
- makes sense 😁 

Also, if you change from number -> string, everything remains valid.

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx [hunk 3]
```diff
@@ -5,29 +5,72 @@ import TippyPopoverWithTrigger from "metabase/components/PopoverWithTrigger/Tipp
...
+    }
+  };
+
+  const handleSave = (closePopover: () => void) => {
+    setError(null);
+    const nextOptions = cleanOptions(textToOptions(text), fieldType);
+    const error = validateOptions(nextOptions, fieldType);
+    if (error) {
+      setError(error);
+    } else {
```
Comment (iethree) [inline frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:70]: This is great. ❤️ 

Screen Shot 2023-03-07 at 3 12 19 PM

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx [hunk 4]
```diff
@@ -5,29 +5,72 @@ import TippyPopoverWithTrigger from "metabase/components/PopoverWithTrigger/Tipp
...
   text.split("\n").map(option => option.trim());
 
+function cleanOptions(options: ValueOptions, fieldType: FieldType) {
+  if (fieldType === "number") {
+    return options.map(option => Number(option));
+  }
+  return options;
+}
+
+function validateOptions(options: ValueOptions, fieldType: FieldType) {
```
Comment (iethree) [inline frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx:30]: maybe `getValidationError` would be a better name for this function?

File: frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.styled.tsx [hunk 5]
```diff
@@ -7,15 +7,22 @@ export const OptionEditorContainer = styled.div`
   display: flex;
   flex-direction: column;
   padding: ${space(2)};
+  gap: ${space(1)};
 `;
 
-export const AddMorePrompt = styled.div`
+export const AddMorePrompt = styled.div<{ isVisible: boolean }>`
```
Comment (iethree) [inline frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.styled.tsx:13]: ❤️

**Review by iethree — APPROVED** [review]
This works as intended, but I left a couple suggestions that I think could lead to less user frustration.

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/actions/components/ActionForm/utils.ts (hunk 1 above)
Comment (kulyk) [reply frontend/src/metabase/actions/components/ActionForm/utils.ts:30]: Oh, I see, thanks for pointing me at this! I've returned the sample options back in [this commit](https://github.com/metabase/metabase/pull/29000/commits/90f047e68f8ad10996ed949c2edd390d08344ffc), but made it use `[ 1, 2, 3 ]` for "number" field type and `[ "Option One", "Option Two", "Option Three" ]` for "string" field type. What do you think?

File: frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.tsx (hunk 2 above)
Comment (kulyk) [reply frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.tsx]: That's an excellent idea, thank you! I think I've managed to achieve this. Please take a look at this demo and LMK if it matches your idea:

https://user-images.githubusercontent.com/17258145/223750916-6d74f5bc-8bea-4991-93c1-7602cd0fb36f.mp4

**Comment by kulyk** [comment]
@iethree @ranquild, mind giving this PR another look? I took in mind Ryan's [feedback](https://github.com/metabase/metabase/pull/29000#discussion_r1128658660) about new behavior being a bit too aggressive and annoying. I've updated the PR description and the demo video, it should explain the difference. LMK if you have any questions

**Review by ranquild — APPROVED** [review]

**Review by iethree — APPROVED** [review]
🙌  This is so great. Thanks.

I did find one little bug, probably just with the options popover state. It seems to keep cleaned options in the option input popover.

popoverState

**Comment by kulyk** [comment]
> I did find one little bug, probably just with the options popover state. It seems to keep cleaned options in the option input popover.

@iethree, great catch, thank you! Should be good now:

https://user-images.githubusercontent.com/17258145/224054562-a9812ace-6990-4588-8dd6-711b828a9ec3.mp4
