### PR TITLE
fix: return 404 when logout without session

### LINKED ISSUE #55457: hitting logout endpoint throws an error if not logged in
### Describe the bug

hitting the logout endpoint will throw an ugly error if you don't have a session.

```shell
❯ http delete localhost:3000/api/session -pb
{
    "cause": "Cannot invoke \"String.getBytes(java.nio.charset.Charset)\" because \"session_key\" is null",
    "message": "Cannot invoke \"String.getBytes(java.nio.charset.Charset)\" because \"session_key\" is null",
    "trace": [
...
```

### To Reproduce

```
❯ http delete localhost:3000/api/session -pb
{
    "cause": "Cannot invoke \"String.getBytes(java.nio.charset.Charset)\" because \"session_key\" is null",
    "message": "Cannot invoke \"String.getBytes(java.nio.charset.Charset)\" because \"session_key\" is null",
    "trace": [
...
```

### Expected behavior

don't make an ugly error

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

p2

### Additional context

this is not a big deal, just cluttering up some logs and ugly. We can and should fix it

### PR DESCRIPTION
**Pull request by edpaget**
Closes https://github.com/metabase/metabase/issues/55457

### Description

Previously we were returning 500 instead of 404 when logging out without any session identifier. This checks that the identifier is non-empty and returns 404 if it is empty.

### How to verify

on a local instance

`curl -X DELETE http://localhost:3000/api/session` returns 404 instead of 500.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: test/metabase/session/api_test.clj [hunk 1]
```diff
@@ -192,11 +192,13 @@
...
   (reset-throttlers!)
   (testing "DELETE /api/session"
+    (testing "Test that logout 404s if there is no session key supplied"
+      (client/client :delete 404 "session"))
     (testing "Test that we can logout"
       ;; clear out cached session tokens so next time we make an API request it log in & we'll know we have a valid
       ;; Session
       (test.users/clear-cached-session-tokens!)
-      (let [session-key       (client/authenticate (test.users/user->credentials :rasta))
+      (let [session-key       #p (client/authenticate (test.users/user->credentials :rasta))
```
Comment (johnswanson) [inline test/metabase/session/api_test.clj:201]: stray `#p`

**Review by johnswanson — APPROVED** [review]
Not really sure if it should be a 404 or a 400 or what. But anything seems better than a 500 😂

File: test/metabase/session/api_test.clj (hunk 1 above)
Comment (edpaget) [reply test/metabase/session/api_test.clj]: 🤦

**Comment by edpaget** [comment]
I was trying to match the check-404 for when there was no session in the db, but 400 is also cool.
