### PR TITLE
Druid: don't make timestamps PKs 

### LINKED ISSUE #6290: Raw queries with "ON" datefilter are broken for Druid [Regression]
Hi,

Since metabase 0.26.2, there is an issue with raw queries that have a filter set to ON specific date or time. When filter "on XX/xx/2017" is added only 1 record (i guess first) is shown in the "details"/"1 record" format instead of a table with all records.
This does not happen if filter is changed to past X days for example or current day.

Database: druid

### PR DESCRIPTION
**Pull request by sbelak**
Stops classifying timestamps in Druid as PKs. Slightly changes the behaviour of field sync. Until now we only updated the special type if what came back from `driver/describe-database` was not nil. This prevents this fix for working for existing databases, as the new special type (nil instead of `:type/PK`) will not get used (interaction between user changes and sync is something we have issues with in a couple of places). As far as I can tell the change does not nuke custom special types, but would appreciate @camsaul thinking it through as well. If the change is dicey we could also write a one-time migration that fixes offending fields.

A consequence of not marking the timestamp as PK is that it's not the first col in the results anymore. This is not ideal (and was raised in #6290), but will be solved once we implement #3720, so punting on this here.

Fixes #6290

### CODE REVIEW

File: src/metabase/sync/sync_metadata/fields.clj [hunk 1]
```diff
@@ -94,13 +94,10 @@
            new-hash      (calculate-table-hash db-metadata)
            hash-changed? (or (not old-hash) (not= new-hash old-hash))]
        ;; if hash is unchanged we can skip the rest of the sync process
-       (when-not hash-changed?
```
Comment (sbelak) [inline src/metabase/sync/sync_metadata/fields.clj:97]: Unless I'm missing something, it's safe to replace these two disjunct `when-not`s with an if.

**Review by camsaul — APPROVED** [review]
Cool LGTM
