### PR TITLE
Async card metadata

### LINKED ISSUE #14957: Saving a question before query has been executed can be slow with UI "hanging"
**Describe the bug**
When saving a question that has not been executed, then the query will be run during the save process and it looks like it's the UI is hanging. And if the user closes the modal and tries to save again, then it will create multiple questions and run more queries.

**To Reproduce**
1. Native query > MySQL or some db with sleep-function (it's also possible to do via GUI, but needs a slow query).
2. Write query `select sleep(60)` - do **not** run the query.
3. Click Save - give it a name and click Save - the button gets disabled (expected), but the modal does not go away until after the query has executed (60 seconds in this test), and then the "Saved! Add this to a dashboard?" modal is shown.
image
4. The log will indicate that it's missing metadata (for `report_card.result_metadata`)
```
2021-02-24 22:37:02,222 INFO api.card :: Card results metadata passed in to API is MISSING. Running query to fetch correct metadata.
2021-02-24 22:38:02,245 DEBUG middleware.log :: POST /api/card 202 [ASYNC: completed] 1.0 mins (8 DB calls) App DB connections: 1/10 Jetty threads: 3/50 (5 idle, 0 queued) (71 total active threads) Queries in flight: 0 (0 queued)
```

**Expected behavior**
The question should be saved instantly without "hanging" the Save-modal. Or even better if it could fetch the metadata without having to run the full query, but not sure if that would even be possible.

**Information about your Metabase Installation:**
Tested 0.35.4 through 0.38.0

Looks like it might have been fixed long ago, but I'm unsure #6866 - not listing as regression.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #23861: Error message misplaced when duplicating question if user is under `no self-serve` permission.
### Steps to reproduce:

1. In test question-management.cy.spec.js, run any test with user "nodata" and signing in with `cy.signIn("nodata")`.
2. After test is done, and it may pass, duplicate the question.

You should see the misplaced error message like below.

image

### PR DESCRIPTION
**Pull request by dpsutton**
Resolves #14957

#### Background:
We need query metadata on cards. This is how the FE knows how to display the results, but it is also how the query processor can use nested queries. Without this information we cannot select from another query (we don't know what to select). This makes metadata _extremely_ important to have.

This also causes some problems. When we are saving questions we have to get this metadata. We have several strategies to make this less painful:
- if the query hasn't changed and we have metadata, don't do anything
- for mbql queries, we can just construct the metadata ourselves. We have field information, types, etc. So no need to hit a database and we just reason about the types
- for native queries, we have no such reasoning. We _must_ query the db. We attempt to make this nicer by running the query and abandoning it after the first row comes back. But we are still at the mercy of long-running queries even if we only take the first row.

#### The idea:
We proceed as before, starting an asynchronous fetching of the metadata. If, after some timeout period (randomly chosen as 1.5 seconds at first) we do not have metadata yet, allow the request to succeed and have the metadata populate the question whenever it is ready, provided that the query is still the same.

annotated Log output:
```
<--- send request
<--- wait 1.5 seconds
INFO api.card :: Metadata not available soon enough. Saving card 5,470 and asynchronously updating metadata
DEBUG middleware.log :: PUT /api/card/5470 200 1.5 s (18 DB calls) <----- request succeeds and unblocks UI
DEBUG middleware.log :: GET /api/alert/question/5470 200 1.0 ms
INFO api.card :: Metadata updated asynchronously for card 5,470     <----- later metadata is ready and saved in background
```

#### Hesitations

I'm a bit worried about this. There are lots of subtleties to metadata. And we have to untangle how the `Card` model has some safeguards already in place.

```clojure
(defn- populate-result-metadata
  "When inserting/updating a Card, populate the result metadata column if not already populated by inferring the
  metadata from the query."
  [{query :dataset_query, metadata :result_metadata, existing-card-id :id, :as card}]
  (cond
    ;; not updating the query => no-op
    (not query)
    (do
      (log/debug "Not inferring result metadata for Card: query was not updated")
      card)

    ;; passing in metadata => no-op
    metadata
    (do
      (log/debug "Not inferring result metadata for Card: metadata was passed in to insert!/update!")
      card)

    ;; this is an update, and dataset_query hasn't changed => no-op
    (and existing-card-id
         (= query (db/select-one-field :dataset_query Card :id existing-card-id)))
    (do
      (log/debugf "Not inferring result metadata for Card %s: query has not changed" existing-card-id)
      card)

    ;; query has changed (or new Card) and this is a native query => set metadata to nil
    ;;
    ;; we can't infer the metadata for a native query without running it, so it's better to have no metadata than
    ;; possibly incorrect metadata.
    (= (:type query) :native)
    (do
      (log/debug "Can't infer result metadata for Card: query is a native query. Setting result metadata to nil")
      (assoc card :result_metadata nil))

    ;; otherwise, attempt to infer the metadata. If the query can't be run for one reason or another, set metadata to
    ;; nil.
    :else
    (do
      (log/debug "Attempting to infer result metadata for Card")
      (let [inferred-metadata (not-empty (mw.session/with-current-user nil
                                           (classloader/require 'metabase.query-processor)
                                           (u/ignore-exceptions
                                             ((resolve 'metabase.query-processor/query->expected-cols) query))))]
        (assoc card :result_metadata inferred-metadata)))))
```

This is in the `pre-insert` and `pre-update` chain for `Card`s. This is a bit heavy handed (note for all native queries it just throws away the metadata _regardless_. My thinking is that this all needs to go away. But I need to research how all of this stuff fits together. It is quite sensitive and quite subtle.

So right now it blanks out the metadata when saving this for native queries. Perhaps we could thread through the previous metadata (if it exists) and we'd hit the case above.

##### Other considerations
this is inherently a bit racy. Especially if there are queries that can take longer than 15 minutes to complete. That's a lot of changes that can be done while we have a pending write of the metadata. Some occurrences:
- someone changes the query. Then the metadata that is pending is no longer even relevant. I check against this at the moment
- someone edits model metadata. Those edits will be tossed away at this time. At this point the metadata is actually empty so there's not much to edit. Not sure what the UI would do if you tried to edit in this case.
- there's an error when getting the metadata: connections can go down, etc. Before this change that would prevent saving and give us a chance to inform the user. Now it happens silently in a java process that no one will notice
- there's an error with the query. `select id, total, quantity, sleep(1) from orders limit 3 limit 3` is an invalid query but nothing really prevents that from saving right now. You can happily save it and just be frustrated later downstream from the actual issue.

### CODE REVIEW

**Comment by adam-james-v** [comment]
> * someone edits model metadata. Those edits will be tossed away at this time. At this point the metadata is actually empty so there's not much to edit. Not sure what the UI would do if you tried to edit in this case.

Does editing 'nil' metadata in the UI just imply that a user is adding their own metadata? Could such data be handled with a merge of some kind once the metadata computation completes? `(merge inferred-metadata user-metadata)`? Of course, then a user's edits might make the inferred metadata completely obsolete and unnecessary...

> * there's an error when getting the metadata: connections can go down, etc. Before this change that would prevent saving and give us a chance to inform the user. Now it happens silently in a java process that no one will notice
> 
> * there's an error with the query. `select id, total, quantity, sleep(1) from orders limit 3 limit 3` is an invalid query but nothing really prevents that from saving right now. You can happily save it and just be frustrated later downstream from the actual issue.

These make me think of  a tuple of 'card health' `{:query-success? true :metadata-success? true}` with 'nil's or something while the query is pending. All of that could be used to report different information to the user? When both are true, things look exactly the same. For short queries, things would hopefully work alright. For something like a 15min query, there would be something to make that obvious to a user? It doesn't eliminate the problems, but can be useful to explain to users so that they know that cards are sort of 'conditionally saved'.

**Comment by dpsutton** [comment]
So there's a failing e2e test.

The card endpoints used to return streaming responses so they _always_ returned a 202. Thus you had weirdness like the following:
image

which is a 202 with payload:

```javascript
{"message":"Invalid Field Filter: Field 4 \"PRODUCTS\".\"CATEGORY\" belongs to Database 1 \"Sample Database\", but the query is against Database 2 \"copy sample dataset\"",
 "_status":400}
```

But after this change, the endpoint (sensibly IMO) returns a 400 with the message 
> Invalid Field Filter: Field 26 "PRODUCTS"."CATEGORY" belongs to Database 1 "Sample Database", but the query is against Database 990 "copy of sample dataset"


Functionally the same but more "proper". However, I need some help updating the FE to accept this new shape. I don't know if this is a big ask or not though.

To recreate:
- go to the admin > Databases screen and select the sample dataset. Copy it's path, create a new h2 database named "copy of sample dataset" and paste the path you copied earlier as the "Connection String"
- make a new native sql question based on the first sample dataset whose contents are `select count(*) from products where {{filter}}`. Make the variable `filter` a field filter on the category field from the products table
- on the top left, change the datasource from the sample dataset to the copy of the dataset
- Click save

We get the correct API behavior: a 400 and a nice error message, but the UI doesn't know to show it:
image

**Comment by alxnddr** [comment]
@dpsutton I'm wondering if you can make back-end not changing `content-type` to `text/plain` and return a JSON with error like 
```{"message":"Invalid Field Filter: Field 4 \"PRODUCTS\".\"CATEGORY\" belongs to Database 1 \"Sample Database\", but the query is against Database 2 \"copy sample dataset\""}```

File: src/metabase/api/card.clj [hunk 1]
```diff
@@ -245,31 +244,19 @@
...
-  thrown. Closing this channel before it finishes will cancel the Card creation."
+(def ^:private metadata-sync-wait-ms
+  "Duration in milliseconds to wait for the metadata before saving the card without the metadata. That metadata will be
+saved later when it is ready."
+  1500)
+
+(def ^:private metadata-async-timeout
+  "Duration in milliseconds to wait for the metadata before abandoning the asynchronous metadata saving. Default is 15
+  minutes."
+  (* 1000 60 15))
```
Comment (camsaul) [inline src/metabase/api/card.clj:255]: We have `u/minutes->ms` which does the same thing but I think is a little easier to read and harder to accidentally forget a zero or whatever

File: src/metabase/api/card.clj [hunk 2]
```diff
@@ -245,31 +244,19 @@
...
-
-(defn- create-card-async!
-  "Create a new Card asynchronously. Returns a channel for fetching the newly created Card, or an Exception if one was
-  thrown. Closing this channel before it finishes will cancel the Card creation."
+(def ^:private metadata-sync-wait-ms
+  "Duration in milliseconds to wait for the metadata before saving the card without the metadata. That metadata will be
+saved later when it is ready."
+  1500)
+
+(def ^:private metadata-async-timeout
```
Comment (camsaul) [inline src/metabase/api/card.clj:252]:
```suggestion
(def ^:private metadata-async-timeout-ms
```

Probably better to error on the side of overly explicit and make sure the fact that this is in milliseconds obvious just by looking at it. I know it's probably safe to assume it's in milliseconds since we didn't assume otherwise but I don't want someone who doesn't know that think this is in seconds and turn this into a 15,000 minute timeout

File: src/metabase/api/card.clj [hunk 3]
```diff
@@ -280,24 +267,58 @@
...
+
+                             (not= current-query (:dataset_query <>))
+                             (log/info (trs "Not updating metadata asynchronously for card {0} because query has changed"
+                                            id))
+
+                             (not (seq metadata))
+                             (log/info (trs "Not updating metadata asynchronously for card {0} because no metadata"
+                                            id))))
+                     (catch Exception e
+                       (log/warn e (trs "Error updating card metadata asynchronously"))))))))))
```
Comment (camsaul) [inline src/metabase/api/card.clj:319]: This is a mega function (66 lines) -- can any parts of it be split out into separate functions? It's a bit hard to read huge functions. But maybe the async metadata update stuff can be split out

File: src/metabase/api/card.clj [hunk 4]
```diff
@@ -280,24 +267,58 @@
...
+      (when timed-out?
+        (.submit clojure.lang.Agent/pooledExecutor
+                 ^Runnable
+                 (fn []
+                   (try
+                     (let [timeoutc        (a/timeout metadata-async-timeout)
+                           [metadata port] (a/alts!! [result-metadata-chan timeoutc])
+                           id              (:id <>)
+                           current-query   (db/select-one-field :dataset_query Card :id id)]
+                       (cond (= port timeoutc)
```
Comment (camsaul) [inline src/metabase/api/card.clj:304]: I think you need to be closing `result-metadata-chan` here. Otherwise the query will keep running forever or until it times out in the QP

File: src/metabase/api/card.clj [hunk 5]
```diff
@@ -280,24 +267,58 @@
...
+    (u/prog1 (-> card
+                 (hydrate :creator
+                          :dashboard_count
+                          :can_write
+                          :average_query_time
+                          :last_query_start
+                          :collection [:moderation_reviews :moderator_details])
+                 (assoc :last-edit-info (last-edit/edit-information-for-user @api/*current-user*)))
+      (when timed-out?
+        (.submit clojure.lang.Agent/pooledExecutor
```
Comment (camsaul) [inline src/metabase/api/card.clj:296]: I'm not convinced `Agent/pooledExecutor` is the best executor to use. Its size is nCPUs + 2, so on a small EC2 instance it's 3 or 4. OTOH it's 34 on my home computer.

Neither one really matches up to the IRL effective limit of 15 open connections per data warehouse DB. 

My only concern is that on instances with a lot of users we could be waiting a while if a lot of people create Cards at the same time.

Since the QP already handles thread pool nonsense and connection pooling is handled by the drivers maybe just doing this with core async would be better. We already have `result-metadata-chan` anyway

Comment (dpsutton) [reply src/metabase/api/card.clj:296]: Good point. My main consideration here was to make sure we didn't run into shenanigans with toucan's connection closing. I can switch this around. Maybe I can finish waiting in a `go` block and then just submit somewhere (or even a future?) to actually save the the results to the db. That execution will need some thread somewhere but it its only concerned with saving (and not waiting on the channel) it should be fine. Good point.

**Review by camsaul — APPROVED** [review]
Sorry this took so long to review.

> this is inherently a bit racy.

Do you mean race-conditiony? I like the idea of our code being vigorous and/or risqué but I don't think that's what you meant lol.

> there's an error with the query

This also applies for parameterized queries with required parameters -- we can't run them without those parameters and we don't have values for them when you save a Card.

With the writeback/actions stuff we're working on we're introducing the concept of `is_write` queries which you're not supposed to run at all ever outside of the new writeback QP -- but it will never have result metadata. You don't need to worry about this here but in the future we'll probably have more cases where people are saving queries without running them, that can't be ran normally either

### Anyways

Anyways overall this looks like a big improvement over the current state of things. I think this also resolves #14385, right?

File: src/metabase/api/card.clj (hunk 5 above)
Comment (camsaul) [reply src/metabase/api/card.clj:296]: 👍 I/O should go on a separate thread so we don't tie up our precious limited core.async threads (I think the pool is fixed at like 4 or 8 threads or something) but `future` should be fine there.

I guess ideally maybe you want to do the `db/select` on a separate thread too for the same reason (you can use `a/thread` to run it on a different thread and get a channel to get the result when it comes back).
