### PR TITLE
Fix default fields for joined SQL models

### LINKED ISSUE #58829: Cannot join a native model that has column names different to the mapped database fields (outside of the join condition)
### Describe the bug

When joining a native model with mapped database fields, either all the field names match SQL or the query will fail.

### To Reproduce

1. Models -> New -> SQL -> `SELECT 1 AS ID, 2 AS _USER_ID` -> Run
2. Metadata -> Map `ID` to `Orders.ID`, `_USER_ID` to `Orders.User ID` -> Save as M1
3. Editor -> Join M1 on `ID` -> Run the query
4. The query fails

### Expected behavior

It should work

### Logs

_No response_

### Information about your Metabase installation

```JSON
master, v55
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/58829

Follows the same approach as in `add_implicit_clauses` - take the `field_ref` from `source-metadata` if possible as it's correct for native models (name-based).

Note that this PR fixes "expanding" join fields only. Until MBQL lib starts to use name-based refs for joined columns, any other clause, e.g. a filter for a joined model column will not work. This is also the reason why the PR doesn't fix the columns in the join condition as they should use name-based refs as well.

How to verify:
1. Models -> New -> SQL -> `SELECT 1 AS ID, 2 AS _USER_ID` -> Run
2. Metadata -> Map `ID` to `Orders.ID`, `_USER_ID` to `Orders.User ID` -> Save as M1
3. Editor -> Join M1 on `ID` -> Run the query
4. The query runs!

### CODE REVIEW

File: src/metabase/query_processor/middleware/resolve_joins.clj [hunk 1]
```diff
@@ -80,11 +80,17 @@
...
-      (if (and field-id (not (contains? duplicate-ids field-id)))
-        ;; field-id is a unique reference, use it
-        [:field field-id   {:join-alias alias}]
-        [:field field-name {:base-type base-type, :join-alias alias}]))))
+    (for [{field-name :name
+           base-type :base_type
+           field-id :id
+           field-ref :field_ref} source-metadata]
+      ;; if `field-ref` is a unique id-based reference, use it
+      ;; use an id-based reference only if the source query uses it
```
Comment (bshepherdson) [inline src/metabase/query_processor/middleware/resolve_joins.clj:88]: These two lines together aren't very clear to me. Is it:
> If `field-ref` is an id-based reference, only use it if the source query uses it.

?

File: test/metabase/query_processor/middleware/resolve_joins_test.clj [hunk 2]
```diff
@@ -255,6 +255,35 @@
...
+    (let [source-metadata [{:id            (mt/id :checkins :id)
+                            :name          "_USER_ID"
+                            :display_name  "User ID"
+                            :base_type     :type/Integer
+                            :semantic_type :type/FK
+                            :field_ref     [:field "_USER_ID" {:base-type :type/Integer :join-alias "alias"}]
+                            :fingerprint   {:global {:distinct-count 15, :nil% 0.0}}}]]
+      (is (query= (mt/mbql-query users
+                    {:fields [$id
+                              [:field "_USER_ID" {:base-type :type/Integer :join-alias "alias"}]]
```
Comment (bshepherdson) [inline test/metabase/query_processor/middleware/resolve_joins_test.clj:269]: nit: don't need to change this, but for the record, you can write this as `&alias.*_USER_ID/Integer`. 

The type can also be omitted if the main table (`users` here) has a field with the name after `*`, like `*LATITUDE`. The docs for this are on `metabase.test/$ids`.

**Review by bshepherdson — APPROVED** [review]
