### PR TITLE
Fix - SQL view is opened when creating a question on small screens

### LINKED ISSUE #48170: SQL view is opened when creating a question on small screens
### Describe the bug

There were 2 separate requirements:
- remember if the sql view is shown or hidden
- on small screens show it instead of the notebook editor, not to the right
But we didn't foresee that when you switch from big screen when you opened the sql view in the sidebar to a small screen if you start a question it is shown by default.

### To Reproduce

1. Open a question
3. Click on 'View the SQL'
4. Open Metabase on small screen
5. Start new question
6. Generated SQL will be shown by default

### Expected behavior

We should remember the view sql toggle state only for big screens and for small screens hide it by default

### Logs

_No response_

### Information about your Metabase installation

```JSON
93cd63a
```

### Severity

Just weird and unexpected

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #48170

### Description

`notebook-native-preview-shown` setting no longer has any effect on viewports less than 1280px wide.
See issue description and [this comment](https://github.com/metabase/metabase/issues/48170#issuecomment-2682652581) for details.

[Hiding diff whitespace](https://github.com/user-attachments/assets/9e9d3de0-bcb6-4e10-9060-0c6abb6aed95) recommended.

### How to verify

1. Set viewport width to >= 1200px
2. Open any notebook question
3. Show SQL preview
4. Navigate to home page
5. Set viewport width to < 1200px
6. Open any notebook question

Expected result: SQL preview is closed

7. Set viewport width to >= 1200px

Expected result: SQL preview is open

8. Set viewport width to < 1200px

Expected result: SQL preview is closed

9. Set viewport width to >= 1200px

Expected result: SQL preview is open 

10. Hide SQL preview
11. Set viewport width to < 1200px
12. Open SQL Preview
13. Set viewport width to >= 1200px

Expected result: SQL preview is closed

### CODE REVIEW

**Review by ranquild — COMMENTED** [review]
I think the fix a bit hard to follow. I mean, it's hard to predict all the possible states given that there are multiple effects. Maybe the only thing that needs to be fixed is this line https://github.com/metabase/metabase/blob/72538ba54b8168aee304881e69b69ebb3e4680d3/frontend/src/metabase/query_builder/actions/core/initializeQB.ts#L345 we could ignore the setting there based on the window size.

**Comment by kamilmielnik** [comment]
> I mean, it's hard to predict all the possible states given that there are multiple effects.

I merged the effects. Now there's only 1. dafb0ef8e37b2d7c3fa553b03b9b4e9097f7bbf8

> we could ignore the setting there based on the window size.

We need to handle screen resize.

**Comment by nemanjaglumac** [comment]
Nit: since we're already using Mantine, there's also https://mantine.dev/hooks/use-viewport-size/
It might simplify the custom hook.

Now, I have no idea about the performance differences (if any) between it and `useWindowSize`

File: frontend/src/metabase/query_builder/hooks/use-notebook-screen-size.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+const NOT_MOUNTED_YET = undefined;
+
+type NotMountedYet = typeof NOT_MOUNTED_YET;
+
+type NotebookScreenSize = {
+  isSmallScreen: boolean | NotMountedYet;
+  isLargeScreen: boolean | NotMountedYet;
+};
+
+export const useNotebookScreenSize = (): NotebookScreenSize => {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/hooks/use-notebook-screen-size.ts:16]: wdyt about returning a single enum, e.g. `undefined | "small" | "large"`? I find it confusing when there is a difference between `undefined` and `false` for a boolean field

File: frontend/src/metabase/query_builder/components/view/View/NotebookContainer/NotebookContainer.tsx [hunk 2]
```diff
@@ -141,28 +163,32 @@ export const NotebookContainer = ({
...
-          handle={<Handle />}
-          onResizeStop={handleResizeStop}
-          style={{
-            borderLeft: "1px solid var(--mb-color-border)",
-            marginInlineStart: "0.25rem",
-          }}
-        >
-          <NotebookNativePreview />
-        </ResizableBox>
+      {isShowingNotebookNativePreview && typeof isSmallScreen === "boolean" && (
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/View/NotebookContainer/NotebookContainer.tsx:166]: If it was a enum there would be no need to do that

**Review by ranquild — APPROVED** [review]
LGTM, but some cleanup can be done

File: frontend/src/metabase/query_builder/hooks/use-notebook-screen-size.ts (hunk 1 above)
Comment (kamilmielnik) [reply frontend/src/metabase/query_builder/hooks/use-notebook-screen-size.ts:13]: Good point :+1: 
d350c9adcde03f25ef265e4213ed182a627e583c
