### PR TITLE
Fix multiple origins support by handling invalid origins

### LINKED ISSUE #42631: Embedding app origin setting should allow multiple origins for the `Access-Control-Allow-Origin` header
**Context**

We're started using `embedding-app-origin` to make the embedding sdk work on other domains via `Access-Control-Allow-Origin`. This has a small issue as `Access-Control-Allow-Origin` should only return one origin (or "*") while we tell the users to give us a list of origins separated by a space:
image

A solution could be to change the following line https://github.com/metabase/metabase/blob/ef15d0e32b0fe9d72cfd57ed6163f1c00cff7af0/src/metabase/server/middleware/security.clj#L131
to return the referrer if it's present in the list of allowed origins. We'll need to normalize the origins before doing the check.

We use the same setting for multiple headers, we should also double check if the formats are compatible.

### PR DESCRIPTION
**Pull request by npretto**
Closes https://github.com/metabase/metabase/issues/42631

### Description

This fixes https://github.com/metabase/metabase/pull/42888 which was reverted because it broke staging.
The issue was caused by the logic not supporting "invalid" input, such as multiple spaces in the authorized origins. This caused parse-url to be called on "" which caused the "Invalid URL" exception.

`approved-origin?` now never throws, to make sure this won't break the BE for an invalid input.
It will instead log an error if it gets an invalid input.

- 6337f67f557bc8652af84e82780c83a57ec08d84 reverts the revert, to put back the original code in the PR
- 2eb30b1c8dfcfe9c20f0aead631b5909548fb6f7 extracts a `parse-approved-origins` function that will be tested and improved in the other commits
- 26b02220bc1814b8dabda3d9d0a1c0cb347973e1 implements the fix for the multiple spaces
- 0052ec8795c820d648d2d834c7ae9b24348f0e71 moves the calls of `parse-url` for the approved origins inside `parse-approved-origins` and filters out invalid origins, to make the code more robust

### CODE REVIEW

File: src/metabase/server/middleware/security.clj [hunk 1]
```diff
@@ -124,11 +125,77 @@
...
+          {:protocol protocol
+           :domain domain
+           :port port})
+        (throw (IllegalArgumentException. (str "Invalid URL '" url "'")))))))
+
+
+(defn approved-domain?
+  "Checks if the domain is compatible with the reference one"
+  [domain reference-domain]
+  (or (= reference-domain "*")
```
Comment (johnswanson) [inline src/metabase/server/middleware/security.clj:146]: nit: indentation (arguments to `or` should be lined up)

File: src/metabase/server/middleware/security.clj [hunk 2]
```diff
@@ -124,11 +125,77 @@
...
+  [port reference-port]
+  (or
+   (= reference-port "*")
+   (= port reference-port)))
+
+(defn parse-approved-origins
+    "Parses the space separated string of approved origins"
+    [approved-origins-raw]
+    (let [urls (filter seq (str/split approved-origins-raw #" "))]
+     (remove nil? (map
```
Comment (johnswanson) [inline src/metabase/server/middleware/security.clj:168]: Instead of mapping to `nil` and then doing `(remove nil? ...)`, you can use `keep`, which is like `map` but removes `nil` https://clojuredocs.org/clojure.core/keep

File: src/metabase/server/middleware/security.clj [hunk 3]
```diff
@@ -124,11 +125,77 @@
...
+  (if (= url "*")
+    {:protocol nil :domain "*" :port "*"}
+    (let [pattern #"^(?:(https?)://)?([^:/]+)(?::(\d+|\*))?$"
+          matches (re-matches pattern url)]
+      (if matches
+        (let [[_ protocol domain port] matches]
+          {:protocol protocol
+           :domain domain
+           :port port})
+        (throw (IllegalArgumentException. (str "Invalid URL '" url "'")))))))
```
Comment (johnswanson) [inline src/metabase/server/middleware/security.clj:140]: I was thinking, maybe we could just skip throwing the exception since all we're doing is logging it? Maybe something like:

```
(if-not matches
 (do (log/errorf "Invalid URL: %s" url) nil)
 (let ...)
```

Then later we can just do `(keep parse-url urls)` without needing to worry about having a `try/catch`. WDYT?

File: src/metabase/server/middleware/security.clj [hunk 4]
```diff
@@ -124,11 +125,77 @@
...
+  "Checks if the port is compatible with the reference one"
+  [port reference-port]
+  (or
+   (= reference-port "*")
+   (= port reference-port)))
+
+(defn parse-approved-origins
+    "Parses the space separated string of approved origins"
+    [approved-origins-raw]
+    (let [urls (filter seq (str/split approved-origins-raw #" "))]
```
Comment (johnswanson) [inline src/metabase/server/middleware/security.clj:167]: `(str/split approved-origins-raw #" +")` will do what you want, I think - split on *at least one* space. Then you don't need the `filter`.

**Review by johnswanson — APPROVED** [review]
Looks good to me! Noticed a few style/indentation things, but nothing is a blocker IMO.

File: src/metabase/server/middleware/security.clj (hunk 1 above)
Comment (npretto) [reply src/metabase/server/middleware/security.clj:146]: Thanks! Done in e8edb32d74015421e78825adc388ecc569aab50c

File: src/metabase/server/middleware/security.clj (hunk 2 above)
Comment (npretto) [reply src/metabase/server/middleware/security.clj]: `keep` looks nice, thanks! Done as part of 0435edec07d4e2e08896f91e011ae1ceded5832d

File: src/metabase/server/middleware/security.clj (hunk 3 above)
Comment (npretto) [reply src/metabase/server/middleware/security.clj]: Makes sense, done in 0435edec07d4e2e08896f91e011ae1ceded5832d

File: src/metabase/server/middleware/security.clj (hunk 4 above)
Comment (npretto) [reply src/metabase/server/middleware/security.clj]: Looks much better now, thanks (703f369d10ff421fa808ae15157feacfaa2d828c)

**Comment by npretto** [comment]
Thanks again for the review and the suggestions @escherize and @johnswanson 🙏 

I should have addressed all the comments
