### PR TITLE
Fingerprints reduce over table-rows-sample instead of realizing all

### LINKED ISSUE #13288: Sync crashes with OOM on very large columns/row samples [proposal]
There are 2 possible situations:
1) entire sampled result set (via `metabase.db.metadata-queries/table-rows-sample` doesn't fit in memory, but all individual rows do
2) there exists a row with a single value bigger than available memory.

1 is relatively straightforward to fix: currently we take `:rows` from `metabase.db.metadata-queries/table-rows-sample` and fingerprint those. This is inefficient as we could (and already do for normal query results) fingerprint as we reduce over the results, but not accrue the rows. We already have the majority of machinery to do this in place, would just need to assemble a different transducer for the fingerprinting step.

2 is harder as we can't touch the value in any way. Here we can do two things: 
2.1) not fingerprint blobs & co at all. The only real ramification of this is that we then also can't have field values on fields of those types, but the value of those is questionable anyway. There are probably edge cases where people use an inappropriate field type and we still explode, but at least we shore up the common usages.    
2.2) add some more functionality to each driver and get upper bounds on individual columns from the DB catalogue or with queries that get object size or similar. The former is not exposed in all the DBs we support; the latter has questionable performance and I'm also not sure out of hand that all the DBs have a function for that.

I suggest doing 1 + 2.1. Both will make sync much more performant for everyone.

### PR DESCRIPTION
**Pull request by dpsutton**
fixes https://github.com/metabase/metabase/issues/13288

Pass the fingerprinting transducer into the query processor to reduce over the result set rather than building up a vector of results and then fingerprinting.

One possibility is to make this rff function to `table-sample-rows` required rather than optional so that no one accidentally does this again in the future.

### CODE REVIEW

File: src/metabase/db/metadata_queries.clj [hunk 1]
```diff
@@ -93,32 +93,47 @@
...
+     :middleware {:format-rows?           false
+                  :skip-results-metadata? true}}))
+
+(s/defn table-rows-sample
+  "Run a basic MBQL query to fetch a sample of rows of FIELDS belonging to a TABLE.
+
+  Options: a map of
+  `:truncation-size`: [optional] size to truncate text fields if the driver supports expressions.
+  `:rff`: [optional] a reducing function to reduce over the result set in the the query-processor rather than
+  realizing the whole collection"
```
Comment (sbelak) [inline src/metabase/db/metadata_queries.clj:126]: Do we actually need both options? Currently `table-rows-sample` is only used in one place. If we ever need a realised version it might be better to have an adapter function that does the transduction.

File: test/metabase/sync/analyze/fingerprint_test.clj [hunk 2]
```diff
@@ -120,7 +121,8 @@
 (defn- field-was-fingerprinted? {:style/indent 0} [fingerprint-versions field-properties]
   (let [fingerprinted? (atom false)]
     (with-redefs [i/fingerprint-version->types-that-should-be-re-fingerprinted fingerprint-versions
-                  metadata-queries/table-rows-sample                           (constantly [[1] [2] [3] [4] [5]])
+                  qp/process-query                                             (fn [_ {:keys [rff]}]
```
Comment (sbelak) [inline test/metabase/sync/analyze/fingerprint_test.clj:124]: This is reasonable all things considered, although to be honest they way I've written these tests using with-redefs gross af

**Review by sbelak — APPROVED** [review]
Awesome! Great job, our QP is a relatively gnarly application of transducers.

File: src/metabase/db/metadata_queries.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/db/metadata_queries.clj:126]: that's true. and its kind of a footgun to start doing table samples without it as you end up with memory pressure.

That said, the testing strategy is _WAY_ nicer by just mocking out what the table-rows-sample function returns versus hijacking the query processor to just use `rff` over the return values.

File: test/metabase/db/metadata_queries_test.clj [hunk 3]
```diff
@@ -64,17 +64,14 @@
 
   (testing "substring checking"
     ;; turn off validation so we can just return the query that is emitted and check for expressions
-    (s/without-fn-validation
```
Comment (camsaul) [inline test/metabase/db/metadata_queries_test.clj:67]: might want to remove the comment now as well

File: src/metabase/db/metadata_queries.clj (hunk 1 above)
Comment (camsaul) [inline src/metabase/db/metadata_queries.clj:126]: `rff` (at least elsewhere in the QP code) isn't a reducing function, it's a function that (given initial results metadata) returns a reducing function. If it was just a reducing function it would be called `rf` (conventional Clojure variable name for a *reducing function*). `rff` instead is short for *reducing function function*.

I don't know if you're actually taking an `rf` or `rff` -- the docstring seems to suggest the former while the name suggests the latter

Comment (dpsutton) [reply src/metabase/db/metadata_queries.clj:126]: right thanks. it's an `rff` the query-processor will call this with the results metadata. and that's the signature of it in fingerprint.clj. I've updated the docstring now.

```clojure
(s/defn ^:private fingerprint-table!
  [table :- i/TableInstance, fields :- [i/FieldInstance]]
  (let [rff (fn [_metadata]
              (redux/post-complete
                (f/fingerprint-fields fields)
                (fn [fingerprints]
                  (reduce (fn [count-info [field fingerprint]]
                            (cond
                              (instance? Throwable fingerprint)
                              (update count-info :failed-fingerprints inc)

                              (some-> fingerprint :global :distinct-count zero?)
                              (update count-info :no-data-fingerprints inc)

                              :else
                              (do
                                (save-fingerprint! field fingerprint)
                                (update count-info :updated-fingerprints inc))))
                          (empty-stats-map (count fingerprints))
                          (map vector fields fingerprints)))))]
    (metadata-queries/table-rows-sample table fields
                                        {:truncation-size truncation-size
                                         :rff             rff})))
```

File: src/metabase/db/metadata_queries.clj [hunk 4]
```diff
@@ -93,32 +93,47 @@
...
-  (s/maybe {(s/optional-key :truncation-size) s/Int}))
+  (s/maybe {(s/optional-key :truncation-size) s/Int
+            (s/optional-key :rff)             s/Any}))
 
-(s/defn table-rows-sample :- (s/maybe si/TableSample)
-  "Run a basic MBQL query to fetch a sample of rows belonging to a Table. Can pass in optional `:truncation-size` for
-  text fields which will be honored only if the driver supports expressions."
+(defn- table-rows-sample-query
+  "Returns the mbql query to query a table for sample rows"
+  [table fields {:keys [truncation-size] :as _opts}]
```
Comment (camsaul) [inline src/metabase/db/metadata_queries.clj:101]: I'm not sure why we had `:as _opts` before but it doesn't look like it's used anywhere. Not a big deal tho

**Review by camsaul — APPROVED** [review]
This LGTM

File: src/metabase/db/metadata_queries.clj (hunk 4 above)
Comment (dpsutton) [reply src/metabase/db/metadata_queries.clj:101]: it used to just be destructured out but now the query builder is a separate function so the whole opts are passed to that. I'm a fan of `_unused` instead of just an underscore. I think this might go against the grain of the coding style here though.

**Comment by camsaul** [comment]
@dpsutton does this close any issues? If so, make sure you mention them in the PR description (e.g. "closes #<issue number>") and tag that issue with the appropriate milestone (0.38.0 in this case). Since you're merging in to `master` this will ship as part of 0.38.0. You don't need to tag the PR itself unless there's no issue associated with the PR.

When CI is green and you have reviews approving it feel free to hit the big green merge button and then close out the issue(s) that this closes if there are any.

**Comment by dpsutton** [comment]
ah dang. this was supposed to be into 0.37.x to help out with memory pressure issues in sync. good eye @camsaul

**Comment by sbelak** [comment]
It's the second part of the fix for #13288

**Comment by nemanjaglumac** [comment]
@dpsutton it is safe to ignore these CircleCI warnings. [The last two](https://dashboard.cypress.io/projects/a394u1/runs?branches=%5B%7B%22label%22%3A%22reducible-table-sample%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22reducible-table-sample%22%7D%5D&committers=%5B%5D&flaky=%5B%5D&page=1&status=%5B%5D&tags=%5B%5D&timeRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D) Cypress runs were green for you.

**Comment by dpsutton** [comment]
> @dpsutton it is safe to ignore these CircleCI warnings. [The last two](https://dashboard.cypress.io/projects/a394u1/runs?branches=%5B%7B%22label%22%3A%22reducible-table-sample%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22reducible-table-sample%22%7D%5D&committers=%5B%5D&flaky=%5B%5D&page=1&status=%5B%5D&tags=%5B%5D&timeRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D) Cypress runs were green for you.

thanks @nemanjaglumac . Its crazy to see the entire suite of cypress failed. never seen that before. I did change the target branch from master to release-x.37.x so that may have busted the cache or thrown a wrench into it.

**Comment by nemanjaglumac** [comment]
It failed to start with this message:
```
The run you are attempting to access is already complete and will not accept new groups.

The existing run is: https://dashboard.cypress.io/projects/a394u1/runs/2704

When a run finishes all of its groups, it waits for a configurable set of time before finally completing. You must add more groups during that time period.

The --tag flag you passed was: 
The --group flag you passed was: default
The --parallel flag you passed was: true

https://on.cypress.io/already-complete
```

Changing the target branch could be the cause.

**Comment by dpsutton** [comment]
image

```clojure
(tt/with-temp* [Table [table]
                  Field [field (assoc {:base_type :type/Decimal, :fingerprint_version 1} :table_id (u/get-id table))]]

    (with-redefs [i/fingerprint-version->types-that-should-be-re-fingerprinted {2 #{:type/Float}}


                  qp/process-query              (fn qp-faked [q {:keys [rff]}]
                                                  (transduce identity (rff :metadata)
                                                             (mapv vector (range 10000000))
                                                             #_(reify
                                                               clojure.lang.IReduceInit
                                                               (reduce [_ rf init]
                                                                 (loop [acc init
                                                                        n 0]
                                                                   (if (= n 10000000)
                                                                     acc
                                                                     (recur (rf acc [n]) (inc n))))))))
                  fingerprint/save-fingerprint! (fn [_field fingerprint] (println fingerprint))]
      (#'fingerprint/fingerprint-table! table [field])))
```

I _think_ this should simulate the difference. The run with `(mapv vector (range 10000000))` must realize the entire collection ahead of time and the memory usages are the two higher areas on the edges. When transducing over the `reify` (which should simulate the reducible sql results) we see the much lower spot in the middle.
