### PR TITLE
Reset join condition state when the rhs table changes

### LINKED ISSUE #46675: Draft join can cause invalid queries
### Describe the bug

image

### To Reproduce

1. New > Question > Orders
2. Join > Reviews > Choose right join column: "Created At" (don't choose the left one)
3. Change join table to Invoices
4. Choose left join column, e.g. "Created At"
5. Visualize

Error:
"Column "Invoices - Created At.CREATED_AT" not found"

### Information about your Metabase installation

master, e6b84e42e05a051f357d8c20ca438ef4e387216c

### Severity

P2

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/46675

Case 1: source table change
- New -> Question -> Orders
- Join -> Reviews -> ID (LHS column). Do not pick the RHS column.
- Click on Orders -> Change to Products
- The draft join state should be reset; Reviews should not be present

Case 2: RHS table change
- New -> Question -> Orders
- Join -> Reviews -> ID (LHS column). Do not pick the RHS column.
- Click on Reviews -> Change to Orders
- The draft join state should be reset; the LHS column should not be selected and there should be a column picker opened.

Screenshot 2024-10-21 at 15 24 40

### CODE REVIEW

**Review by kamilmielnik — APPROVED** [review]

File: frontend/src/metabase/querying/notebook/components/JoinStep/JoinConditionDraft/JoinConditionDraft.tsx [hunk 1]
```diff
@@ -77,6 +77,13 @@ export function JoinConditionDraft({
     handleColumnChange(lhsColumn, newRhsColumn);
   };
 
+  useLayoutEffect(() => {
+    setLhsColumn(undefined);
+    setRhsColumn(undefined);
+    setIsLhsOpened(true);
+    setIsRhsOpened(false);
+  }, [joinable]);
```
Comment (romeovs) [inline frontend/src/metabase/querying/notebook/components/JoinStep/JoinConditionDraft/JoinConditionDraft.tsx:85]: Does this rely on the referential integrity of the `joinable`? 
And if so, is that safe?

**Review by romeovs — APPROVED** [review]
Just one question.

File: frontend/src/metabase/querying/notebook/components/JoinStep/JoinConditionDraft/JoinConditionDraft.tsx (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/querying/notebook/components/JoinStep/JoinConditionDraft/JoinConditionDraft.tsx]: That's a good point. I modified it in a way so we rely on the identify of `rhsTable` only which we store in react state for draft joins.
