### PR TITLE
Fix several problems with the localization of the Performance feature

### LINKED ISSUE #45779: [Cache] Some strings are not translated in strategy form
Descriptions of OSS-only strategies are not translated

Image

### PR DESCRIPTION
**Pull request by rafpaf**
Fixes several problems with localization of the Performance feature:
* There were untranslated strings in the strategy form
* Incorrect usage of placeholders was preventing the Schedule picker from using the correct word ordering
* The colon punctuation mark in Asian languages was making the styling of radio buttons incorrect in Japanese and Korean
* The dropdowns were too narrow in Japanese and Korean. The reason is that I assumed that the average character width in all languages is the same as English, but characters are relatively wide in those languages

As part of this work I also looked through some of our most popular languages and corrected a lot of translations of performance-related strings.

Closes #45779

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#45773** <a href="https://app.graphite.dev/github/pr/metabase/metabase/45773?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: frontend/src/metabase/admin/performance/components/StrategyForm.tsx [hunk 1]
```diff
@@ -341,7 +342,7 @@ const ScheduleStrategyFormFields = () => {
       schedule={schedule}
       scheduleOptions={["hourly", "daily", "weekly", "monthly"]}
       onScheduleChange={onScheduleChange}
-      verb={t`Invalidate`}
+      verb={c("A verb in the imperative mood").t`Invalidate`}
```
Comment (rafpaf) [inline frontend/src/metabase/admin/performance/components/StrategyForm.tsx:345]: Some translators have rendered this as an infinitive, but it's an imperative. I'm hoping the context will help

File: frontend/src/metabase/components/Schedule/constants.ts [hunk 2]
```diff
@@ -2,81 +2,145 @@ import { c, t } from "ttag";
...
+    weekly: c("adverb").t`weekly`,
+    monthly: c("adverb").t`monthly`,
+  };
+
+  const weekdays: Weekday[] = [
+    {
+      label: c(
+        "Occurs in phrases like 'Send weekly on Sunday'. Only capitalize if necessary",
+      ).t`Sunday`,
+      value: "sun",
```
Comment (rafpaf) [inline frontend/src/metabase/components/Schedule/constants.ts:66]: Some translators have used capitalized forms of "Sunday", "Monday", etc., even in languages where these are not standardly capitalized.

File: frontend/src/metabase/components/Schedule/constants.ts [hunk 3]
```diff
@@ -2,81 +2,145 @@ import { c, t } from "ttag";
...
-export const amAndPM = [
-  { label: c("As in 9:00 AM").t`AM`, value: "0" },
-  { label: c("As in 9:00 PM").t`PM`, value: "1" },
-];
+  const amAndPM = [
+    // We use a fallback string in case the translator translated
+    // 'AM' or 'PM' as an empty string, which might happen since
+    // certain cultures do not use AM/PM.
+    { label: c("As in 9:00 AM").t`AM`.trim() || "AM", value: "0" },
+    { label: c("As in 9:00 PM").t`PM`.trim() || "PM", value: "1" },
```
Comment (rafpaf) [inline frontend/src/metabase/components/Schedule/constants.ts:116]: I've added this fallback value because the Finnish translation currently uses spaces as the translation for "AM" and "PM", which causes a bug

File: frontend/src/metabase/components/Schedule/i18n.tsx [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+import { getScheduleStrings } from "./constants";
+
+const isDay = (item: any, day: ScheduleDayType) =>
+  isValidElement(item) &&
+  (item.type === SelectWeekday || item.type === SelectWeekdayOfMonth) &&
+  (item as { props: SelectWeekdayProps }).props.schedule.schedule_day === day;
+
+const isSaturday = (item: any) => isDay(item, "sat");
+const isSunday = (item: any) => isDay(item, "sun");
+
```
Comment (rafpaf) [inline frontend/src/metabase/components/Schedule/i18n.tsx:23]: What follows is a small layer of code needed to correct a few mistranslations in relatively popular languages

These mistranslations are due to the composition of word translations into phrases, so they can't be straightforwardly remedied inside POEditor.

File: frontend/src/metabase/components/Schedule/components.tsx [hunk 5]
```diff
@@ -164,26 +180,38 @@ export const SelectMinute = ({
...
+export const estimateWidthOfString = _.memoize(estimateWidthOfString_base);
+
 export const AutoWidthSelect = (props: SelectProps) => {
   const longestLabel = useMemo(
     () => getLongestSelectLabel(props.data),
     [props.data],
   );
-  const maxWidth =
-    longestLabel.length > 15 ? "unset" : `${longestLabel.length + 0.85}rem`;
+  const maxWidth = `${estimateWidthOfString(longestLabel) + 60}px`;
```
Comment (sloansparger) [inline frontend/src/metabase/components/Schedule/components.tsx:200]: Few things:
1. Why is this needed? I'm a bit concerned that this is adding complexity that manual setting a wider input could also solve.
2. I don't know if we want to use a canvas to measure? i think we could probably use a div for the same purpose
3. canvas creation can fail, we're not handling the error
4. your memoization function on line 193 is a memory leak if we begin to use this lots of places. I would suggest creating a memoized instance of the memoized function within the AutoSelect component (i.e. `useMemo(() => _.memoize(estimateWidthOfString_base))`) so that it gets gc'ed on unmount.

File: frontend/src/metabase/components/Schedule/i18n.tsx (hunk 4 above)
Comment (sloansparger) [reply frontend/src/metabase/components/Schedule/i18n.tsx:23]: We should fix the translations in POEditor and remove this code. I don't think really many folks on this team could maintain this and I don't think it's a pattern we'd want to follow for other features.

**Review by sloansparger — DISMISSED** [review]

File: frontend/src/metabase/components/Schedule/components.tsx (hunk 5 above)
Comment (rafpaf) [reply frontend/src/metabase/components/Schedule/components.tsx:200]: 1. In many cases it's nice to have the selects appear on the same line if possible, like this:

image

2. This approach doesn't change the DOM so some people prefer it ([discussion on SO](https://stackoverflow.com/questions/118241/calculate-text-width-with-javascript/21015393#21015393))

3. Just in case there are any issues I've wrapped it in a try/catch with a fallback value. It has good support: [caniuse](https://caniuse.com/mdn-api_canvasrenderingcontext2d_measuretext)

4. This is a really interesting - and cool - point. I've pushed a change along these lines; let's discuss it

File: frontend/src/metabase/components/Schedule/Schedule.tsx [hunk 6]
```diff
@@ -85,6 +78,18 @@ export const Schedule = ({
...
+  const fill = useCallback(
+    (template: string, components: ReactNode[]) =>
+      fillScheduleTemplate(
+        template,
+        components,
+        // Memoization function created here so it gets garbage collected when the Schedule component is unmounted
+        _.memoize(getStringWidth),
+      ),
+    [],
+  );
```
Comment (rafpaf) [inline frontend/src/metabase/components/Schedule/Schedule.tsx:91]: @sloansparger This is my attempt to implement your suggestion relating to memoization and gc

File: frontend/src/metabase/components/Schedule/components.tsx [hunk 7]
```diff
@@ -165,25 +183,24 @@ export const SelectMinute = ({
...
-    () => getLongestSelectLabel(props.data),
-    [props.data],
-  );
-  const maxWidth =
-    longestLabel.length > 15 ? "unset" : `${longestLabel.length + 0.85}rem`;
+  const maxWidth = useMemo(() => {
+    const longestLabel = getLongestSelectLabel(props.data);
+    const maxWidth = `${measureTextWidth(longestLabel) + 60}px`;
+    return maxWidth;
+  }, [props.data]);
```
Comment (npfitz) [inline frontend/src/metabase/components/Schedule/components.tsx:190]: I'm assuming the idea here is that we want the select to be _just big enough_ to handle the largest possible item. However, this function is still just guessing at what the length might be and assumes a default font. I think the real answer here might be to use a custom dropdown component and use a ref to measure it's contents, but I'm going to punt this to @iethree and get his opinion

**Review by npfitz — APPROVED** [review]
I'd like to get a second opinion on the use of measure text, but otherwise I think it's good

File: frontend/src/metabase/components/Schedule/components.tsx (hunk 7 above)
Comment (rafpaf) [reply frontend/src/metabase/components/Schedule/components.tsx]: I've made the `AutoWidthSelect` component a bit smarter so it takes the current font into consideration. Here's how the dropdowns look with Poppins as the font: 

image

Previously, the dropdowns were narrower to a a slightly uncomfortable degree.

**Comment by rafpaf** [comment]
Note to self that this e2e test previously failed. I assume this is a flake, but if it fails again, maybe not:

```
) scenarios > visualizations > table
       should show field metadata hovercards for native query tables:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid=cell-data]`, but never found it.
      at Context.eval (../../../../../../../../../../../work/metabase/metabase/e2e/test/scenarios/visualizations-tabular/table.cy.spec.js:297:7)
```
