### PR TITLE
Use all text scorers in the final result to increase scoring signal

### LINKED ISSUE #19366: Add Question search in Dashboard editor does not return question with exact name match
**Describe the bug**
When using the search function to add a question to a dashboard, the question whose name exactly matches my search phrase does not show up in the result list. The question does show up, however, in the global search.

**Logs**
<details><summary>The web console doesn't show anything particularly notable, but here it is.</summary>

```
i18n.js:49 Setting moment.js start of week for Locale en to sunday
react-dom.development.js:88 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ThemeProvider
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11371
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
scheduleUpdateOnFiber @ react-dom.development.js:21188
updateContainer @ react-dom.development.js:24373
(anonymous) @ react-dom.development.js:24758
unbatchedUpdates @ react-dom.development.js:21903
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24757
render @ react-dom.development.js:24840
_init @ app.js:76
(anonymous) @ app.js:118
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DragDropContextProvider, ThemeProvider
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11377
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
scheduleUpdateOnFiber @ react-dom.development.js:21188
updateContainer @ react-dom.development.js:24373
(anonymous) @ react-dom.development.js:24758
unbatchedUpdates @ react-dom.development.js:21903
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24757
render @ react-dom.development.js:24840
_init @ app.js:76
(anonymous) @ app.js:118
react-dom.development.js:88 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Box, Dashboardstyled__DashboardLoadingAndErrorWrapper, Flex, Icon, Icon__IconWrapper, Link, MetabaseIsSetup(Connect(UserIsAuthenticated(Component))), SearchBarstyled__SearchInput, SearchBarstyled__SearchWrapper, UndoListing__UndoList, UserIsAuthenticated(Component)
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11371
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
(anonymous) @ Router.js:109
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
done @ AsyncUtils.js:74
(anonymous) @ AsyncUtils.js:80
getComponentsForRoute @ getComponents.js:6
(anonymous) @ getComponents.js:30
(anonymous) @ AsyncUtils.js:79
mapAsync @ AsyncUtils.js:78
getComponents @ getComponents.js:29
finishEnterHooks @ createTransitionManager.js:77
next @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
wrappedNext @ TransitionUtils.js:110
_callee$ @ routes.jsx:166
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ utils.js:127
_next @ utils.js:127
Show 8 more frames
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Box, Dashboardstyled__DashboardLoadingAndErrorWrapper, Flex, Icon, Icon__IconWrapper, Link, MetabaseIsSetup(Connect(UserIsAuthenticated(Component))), SearchBarstyled__SearchInput, SearchBarstyled__SearchWrapper, UndoListing__UndoList, UserIsAuthenticated(Component)
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11377
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
(anonymous) @ Router.js:109
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
done @ AsyncUtils.js:74
(anonymous) @ AsyncUtils.js:80
getComponentsForRoute @ getComponents.js:6
(anonymous) @ getComponents.js:30
(anonymous) @ AsyncUtils.js:79
mapAsync @ AsyncUtils.js:78
getComponents @ getComponents.js:29
finishEnterHooks @ createTransitionManager.js:77
next @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
wrappedNext @ TransitionUtils.js:110
_callee$ @ routes.jsx:166
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ utils.js:127
_next @ utils.js:127
Show 8 more frames
metadata.js:18 DEPRECATED: metabase/redux/metadata addFields
deprecated @ metadata.js:18
addFields @ metadata.js:124
_callee6$ @ actions.js:707
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ index.js:20
_next @ index.js:20
react-dom.development.js:88 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Button, Buttonstyled__TextButton, DashboardHeaderstyled__DashboardHeaderButton, Dashboardstyled__CardsContainer, Dashboardstyled__DashboardBody, Dashboardstyled__DashboardStyled, Dashboardstyled__HeaderContainer, Dashboardstyled__ParametersAndCardsContainer, FullWidthContainer, TransitionGroup
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11371
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
_callee3$ @ redux.js:204
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
Show 3 more frames
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Button, Buttonstyled__TextButton, DashboardHeaderstyled__DashboardHeaderButton, Dashboardstyled__CardsContainer, Dashboardstyled__DashboardBody, Dashboardstyled__DashboardStyled, Dashboardstyled__HeaderContainer, Dashboardstyled__ParametersAndCardsContainer, FullWidthContainer, TransitionGroup
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11377
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
_callee3$ @ redux.js:204
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
Show 3 more frames
checkPropTypes.js:20 Warning: Failed prop type: minWidth larger than item width/maxWidth
    in GridItem (created by ReactGridLayout)
    in ReactGridLayout (created by ResponsiveReactGridLayout)
    in ResponsiveReactGridLayout (created by GridLayout)
    in GridLayout (created by DashboardGrid)
    in div (created by DashboardGrid)
    in DashboardGrid (created by ExplicitSize[DashboardGrid])
    in ExplicitSize[DashboardGrid] (created by LoadingAndErrorWrapper)
    in div (created by FullWidthContainer)
    in FullWidthContainer (created by Dashboardstyled__CardsContainer)
    in Dashboardstyled__CardsContainer (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__ParametersAndCardsContainer)
    in Dashboardstyled__ParametersAndCardsContainer (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardBody)
    in Dashboardstyled__DashboardBody (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardStyled)
    in Dashboardstyled__DashboardStyled (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboardstyled__DashboardLoadingAndErrorWrapper)
    in Dashboardstyled__DashboardLoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Connect(DashboardControls[Dashboard]))
    in Connect(DashboardControls[Dashboard]) (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by Connect(FitViewport))
    in Connect(FitViewport) (created by Title[Connect(FitViewport)])
    in Title[Connect(FitViewport)] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Title[Connect(App)])
    in Title[Connect(App)] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:82
validatePropTypes @ react.development.js:1714
createElementWithValidation @ react.development.js:1813
processGridItem @ ReactGridLayout.js:649
(anonymous) @ ReactGridLayout.js:714
mapSingleChildIntoContext @ react.development.js:1149
traverseAllChildrenImpl @ react.development.js:1007
traverseAllChildrenImpl @ react.development.js:1023
traverseAllChildren @ react.development.js:1092
mapIntoWithKeyPrefixInternal @ react.development.js:1174
mapChildren @ react.development.js:1198
render @ ReactGridLayout.js:713
finishClassComponent @ react-dom.development.js:17160
updateClassComponent @ react-dom.development.js:17110
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
_callee3$ @ redux.js:204
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
Show 13 more frames
react-dom.development.js:88 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ChartCaptionstyled__ChartCaptionRoot, LegendActionsstyled__LegendActionsRoot, LegendCaptionstyled__LegendCaptionRoot, LegendCaptionstyled__LegendLabel
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11371
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
_callee3$ @ redux.js:204
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
Show 3 more frames
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ChartCaptionstyled__ChartCaptionRoot, LegendActionsstyled__LegendActionsRoot, LegendCaptionstyled__LegendCaptionRoot, LegendCaptionstyled__LegendLabel
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11377
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
_callee3$ @ redux.js:204
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
Show 3 more frames
react-dom.development.js:88 Warning: React does not recognize the `hasMargin` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hasmargin` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in svg (created by BaseIcon)
    in BaseIcon (created by Icon)
    in Icon (created by Tooltipify[Icon])
    in Tooltipify[Icon] (created by Badgestyled__BadgeIcon)
    in Badgestyled__BadgeIcon (created by Badge)
    in a (created by Link)
    in Link (created by BaseLink)
    in BaseLink (created by Link)
    in Link (created by RawMaybeLink)
    in RawMaybeLink (created by Badgestyled__MaybeLink)
    in Badgestyled__MaybeLink (created by Badge)
    in Badge (created by CollectionBadge)
    in CollectionBadge (created by EntityObjectLoader)
    in EntityObjectLoader (created by Connect(EntityObjectLoader))
    in Connect(EntityObjectLoader) (created by EntityType)
    in EntityType (created by Connect(EntityType))
    in Connect(EntityType)
    in Unknown (created by Header)
    in div (created by Clean.div)
    in Clean.div (created by Flex)
    in Flex (created by Header)
    in div (created by Clean.div)
    in Clean.div (created by Box)
    in Box (created by Header)
    in div (created by Header)
    in div (created by Header)
    in Header (created by DashboardHeader)
    in DashboardHeader (created by LoadingAndErrorWrapper)
    in header (created by Dashboardstyled__HeaderContainer)
    in Dashboardstyled__HeaderContainer (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardStyled)
    in Dashboardstyled__DashboardStyled (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboardstyled__DashboardLoadingAndErrorWrapper)
    in Dashboardstyled__DashboardLoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Connect(DashboardControls[Dashboard]))
    in Connect(DashboardControls[Dashboard]) (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by Connect(FitViewport))
    in Connect(FitViewport) (created by Title[Connect(FitViewport)])
    in Title[Connect(FitViewport)] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Title[Connect(App)])
    in Title[Connect(App)] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
printWarning @ react-dom.development.js:88
react-dom.development.js:88 Warning: React does not recognize the `activeColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activecolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by Link)
    in Link (created by BaseLink)
    in BaseLink (created by Link)
    in Link (created by RawMaybeLink)
    in RawMaybeLink (created by Badgestyled__MaybeLink)
    in Badgestyled__MaybeLink (created by Badge)
    in Badge (created by CollectionBadge)
    in CollectionBadge (created by EntityObjectLoader)
    in EntityObjectLoader (created by Connect(EntityObjectLoader))
    in Connect(EntityObjectLoader) (created by EntityType)
    in EntityType (created by Connect(EntityType))
    in Connect(EntityType)
    in Unknown (created by Header)
    in div (created by Clean.div)
    in Clean.div (created by Flex)
    in Flex (created by Header)
    in div (created by Clean.div)
    in Clean.div (created by Box)
    in Box (created by Header)
    in div (created by Header)
    in div (created by Header)
    in Header (created by DashboardHeader)
    in DashboardHeader (created by LoadingAndErrorWrapper)
    in header (created by Dashboardstyled__HeaderContainer)
    in Dashboardstyled__HeaderContainer (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardStyled)
    in Dashboardstyled__DashboardStyled (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboardstyled__DashboardLoadingAndErrorWrapper)
    in Dashboardstyled__DashboardLoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Connect(DashboardControls[Dashboard]))
    in Connect(DashboardControls[Dashboard]) (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by Connect(FitViewport))
    in Connect(FitViewport) (created by Title[Connect(FitViewport)])
    in Title[Connect(FitViewport)] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Title[Connect(App)])
    in Title[Connect(App)] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
printWarning @ react-dom.development.js:88
react-dom.development.js:88 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Badgestyled__BadgeIcon, Badgestyled__MaybeLink
printWarning @ react-dom.development.js:88
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Badgestyled__BadgeIcon, Badgestyled__MaybeLink
printWarning @ react-dom.development.js:88
VM2823 react_devtools_backend.js:2540 Warning: Failed prop type: Invalid prop `target` supplied to `Popover`.
    in Popover (created by TooltipPopover)
    in TooltipPopover
    in TooltipPopover (created by Tooltip)
    in Tooltip (created by DashboardHeader)
    in span (created by Header)
    in span (created by Header)
    in div (created by Header)
    in div (created by Header)
    in div (created by Header)
    in Header (created by DashboardHeader)
    in DashboardHeader (created by LoadingAndErrorWrapper)
    in header (created by Dashboardstyled__HeaderContainer)
    in Dashboardstyled__HeaderContainer (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardStyled)
    in Dashboardstyled__DashboardStyled (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboardstyled__DashboardLoadingAndErrorWrapper)
    in Dashboardstyled__DashboardLoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Connect(DashboardControls[Dashboard]))
    in Connect(DashboardControls[Dashboard]) (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by Connect(FitViewport))
    in Connect(FitViewport) (created by Title[Connect(FitViewport)])
    in Title[Connect(FitViewport)] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Title[Connect(App)])
    in Title[Connect(App)] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
overrideMethod @ VM2823 react_devtools_backend.js:2540
VM2823 react_devtools_backend.js:2540 Warning: React does not recognize the `maxHeight` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `maxheight` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in span (created by TooltipPopover)
    in div
    in span
overrideMethod @ VM2823 react_devtools_backend.js:2540
VM2823 react_devtools_backend.js:2540 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `DashCardActionButtons`. See https://fb.me/react-warning-keys for more information.
    in ChartSettingsButton (created by DashCardActionButtons)
    in DashCardActionButtons (created by DashCard)
    in div (created by DashCard__DashboardCardActionsPanel)
    in DashCard__DashboardCardActionsPanel (created by DashCard)
    in div (created by DashCard)
    in DashCard (created by GridLayout)
    in div (created by GridItem)
    in Resizable (created by GridItem)
    in DraggableCore (created by GridItem)
    in GridItem (created by ReactGridLayout)
    in div (created by ReactGridLayout)
    in ReactGridLayout (created by ResponsiveReactGridLayout)
    in ResponsiveReactGridLayout (created by GridLayout)
    in GridLayout (created by DashboardGrid)
    in div (created by DashboardGrid)
    in DashboardGrid (created by ExplicitSize[DashboardGrid])
    in ExplicitSize[DashboardGrid] (created by LoadingAndErrorWrapper)
    in div (created by FullWidthContainer)
    in FullWidthContainer (created by Dashboardstyled__CardsContainer)
    in Dashboardstyled__CardsContainer (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__ParametersAndCardsContainer)
    in Dashboardstyled__ParametersAndCardsContainer (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardBody)
    in Dashboardstyled__DashboardBody (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardStyled)
    in Dashboardstyled__DashboardStyled (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboardstyled__DashboardLoadingAndErrorWrapper)
    in Dashboardstyled__DashboardLoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Connect(DashboardControls[Dashboard]))
    in Connect(DashboardControls[Dashboard]) (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by Connect(FitViewport))
    in Connect(FitViewport) (created by Title[Connect(FitViewport)])
    in Title[Connect(FitViewport)] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Title[Connect(App)])
    in Title[Connect(App)] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ react.development.js:315
error @ react.development.js:287
validateExplicitKey @ react.development.js:1630
validateChildKeys @ react.development.js:1656
createElementWithValidation @ react.development.js:1806
DashCardActionButtons @ DashCard.jsx:366
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
VM2823 react_devtools_backend.js:2540 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DashCard__DashboardCardActionsPanel
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11371
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
VM2823 react_devtools_backend.js:2540 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DashCard__DashboardCardActionsPanel
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11377
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
VM2823 react_devtools_backend.js:2540 Warning: Failed prop type: Invalid prop `collectionId` of type `number` supplied to `QuestionList`, expected `string`.
    in QuestionList (created by QuestionPicker)
    in QuestionPicker (created by Connect(QuestionPicker))
    in Connect(QuestionPicker) (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by Connect(EntityType))
    in Connect(EntityType) (created by Connect(QuestionPicker))
    in Connect(QuestionPicker) (created by AddCardSidebar)
    in div (created by Sidebar)
    in aside (created by Sidebar)
    in Sidebar (created by AddCardSidebar)
    in AddCardSidebar (created by DashboardSidebars)
    in DashboardSidebars (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardBody)
    in Dashboardstyled__DashboardBody (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardStyled)
    in Dashboardstyled__DashboardStyled (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboardstyled__DashboardLoadingAndErrorWrapper)
    in Dashboardstyled__DashboardLoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Connect(DashboardControls[Dashboard]))
    in Connect(DashboardControls[Dashboard]) (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by Connect(FitViewport))
    in Connect(FitViewport) (created by Title[Connect(FitViewport)])
    in Title[Connect(FitViewport)] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Title[Connect(App)])
    in Title[Connect(App)] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:82
validatePropTypes @ react.development.js:1714
createElementWithValidation @ react.development.js:1813
QuestionPicker @ QuestionPicker.jsx:105
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
VM2823 react_devtools_backend.js:2540 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: QuestionPickerstyled__BreadcrumbsWrapper, QuestionPickerstyled__SearchInput, TextInputstyled__IconWrapper, TextInputstyled__Input, TextInputstyled__TextInputRoot
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11371
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
VM2823 react_devtools_backend.js:2540 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: QuestionPickerstyled__BreadcrumbsWrapper, QuestionPickerstyled__SearchInput, TextInputstyled__IconWrapper, TextInputstyled__Input, TextInputstyled__TextInputRoot
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11377
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
VM2823 react_devtools_backend.js:2540 Warning: Failed prop type: Invalid prop `id` of type `number` supplied to `SelectListItem`, expected `string`.
    in SelectListItem (created by QuestionListstyled__QuestionListItem)
    in QuestionListstyled__QuestionListItem (created by LoadingAndErrorWrapper)
    in ul (created by SelectList)
    in SelectList (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by Connect(EntityType))
    in Connect(EntityType) (created by search.ListLoader)
    in search.ListLoader (created by QuestionList)
    in QuestionList (created by QuestionPicker)
    in div (created by Clean.div)
    in Clean.div (created by Box)
    in Box (created by QuestionPicker)
    in QuestionPicker (created by Connect(QuestionPicker))
    in Connect(QuestionPicker) (created by EntityListLoader)
    in EntityListLoader (created by Connect(EntityListLoader))
    in Connect(EntityListLoader) (created by _class2)
    in _class2 (created by EntityType)
    in EntityType (created by Connect(EntityType))
    in Connect(EntityType) (created by Connect(QuestionPicker))
    in Connect(QuestionPicker) (created by AddCardSidebar)
    in div (created by Sidebar)
    in aside (created by Sidebar)
    in Sidebar (created by AddCardSidebar)
    in AddCardSidebar (created by DashboardSidebars)
    in DashboardSidebars (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardBody)
    in Dashboardstyled__DashboardBody (created by LoadingAndErrorWrapper)
    in div (created by Dashboardstyled__DashboardStyled)
    in Dashboardstyled__DashboardStyled (created by LoadingAndErrorWrapper)
    in div (created by LoadingAndErrorWrapper)
    in LoadingAndErrorWrapper (created by Dashboardstyled__DashboardLoadingAndErrorWrapper)
    in Dashboardstyled__DashboardLoadingAndErrorWrapper (created by Dashboard)
    in Dashboard (created by DashboardControls[Dashboard])
    in DashboardControls[Dashboard] (created by Connect(DashboardControls[Dashboard]))
    in Connect(DashboardControls[Dashboard]) (created by DashboardApp)
    in div (created by DashboardApp)
    in DashboardApp
    in Unknown (created by Title[])
    in Title[] (created by Title[Title[]])
    in Title[Title[]] (created by FitViewport)
    in FitViewport (created by Connect(FitViewport))
    in Connect(FitViewport) (created by Title[Connect(FitViewport)])
    in Title[Connect(FitViewport)] (created by RouterContext)
    in Unknown (created by UserIsAuthenticated(Component))
    in UserIsAuthenticated(Component) (created by Connect(UserIsAuthenticated(Component)))
    in Connect(UserIsAuthenticated(Component)) (created by MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component))) (created by Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))) (created by RouterContext)
    in div (created by App)
    in ScrollToTop (created by withRouter(ScrollToTop))
    in withRouter(ScrollToTop) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Title[Connect(App)])
    in Title[Connect(App)] (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in ThemeProvider
    in DragDropContextProvider
    in Provider
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:82
validatePropTypes @ react.development.js:1714
createElementWithValidation @ react.development.js:1813
render @ styled-components.browser.es.js:1791
finishClassComponent @ react-dom.development.js:17160
updateClassComponent @ react-dom.development.js:17110
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
(anonymous) @ redux.js:241
setTimeout (async)
_callee4$ @ redux.js:241
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
Promise.then (async)
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ redux.js:229
(anonymous) @ redux.js:298
_callee3$ @ redux.js:200
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ redux.js:200
(anonymous) @ store.js:23
(anonymous) @ bindActionCreators.js:3
_callee$ @ EntityListLoader.jsx:141
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ EntityLink.jsx:31
_next @ EntityLink.jsx:31
(anonymous) @ EntityLink.jsx:31
(anonymous) @ EntityLink.jsx:31
(anonymous) @ EntityListLoader.jsx:140
UNSAFE_componentWillMount @ EntityListLoader.jsx:160
callComponentWillMount @ react-dom.development.js:12953
mountClassInstance @ react-dom.development.js:13048
updateClassComponent @ react-dom.development.js:17101
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 43 more frames
VM2823 react_devtools_backend.js:2540 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: QuestionListstyled__QuestionListItem, SelectListItemstyled__ItemIcon, SelectListItemstyled__ItemRoot, SelectListItemstyled__ItemTitle, Text
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11371
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
(anonymous) @ redux.js:241
setTimeout (async)
_callee4$ @ redux.js:241
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
Promise.then (async)
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ redux.js:229
(anonymous) @ redux.js:298
_callee3$ @ redux.js:200
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ redux.js:200
(anonymous) @ store.js:23
(anonymous) @ bindActionCreators.js:3
_callee$ @ EntityListLoader.jsx:141
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ EntityLink.jsx:31
_next @ EntityLink.jsx:31
(anonymous) @ EntityLink.jsx:31
(anonymous) @ EntityLink.jsx:31
(anonymous) @ EntityListLoader.jsx:140
UNSAFE_componentWillMount @ EntityListLoader.jsx:160
callComponentWillMount @ react-dom.development.js:12953
mountClassInstance @ react-dom.development.js:13048
updateClassComponent @ react-dom.development.js:17101
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 43 more frames
VM2823 react_devtools_backend.js:2540 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: QuestionListstyled__QuestionListItem, SelectListItemstyled__ItemIcon, SelectListItemstyled__ItemRoot, SelectListItemstyled__ItemTitle, Text
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11377
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
push.../../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:204
dispatch @ createStore.js:173
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
(anonymous) @ redux.js:241
setTimeout (async)
_callee4$ @ redux.js:241
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
Promise.then (async)
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ redux.js:229
(anonymous) @ redux.js:298
_callee3$ @ redux.js:200
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ query_time.js:284
_next @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ query_time.js:284
(anonymous) @ redux.js:200
(anonymous) @ store.js:23
(anonymous) @ bindActionCreators.js:3
_callee$ @ EntityListLoader.jsx:141
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ EntityLink.jsx:31
_next @ EntityLink.jsx:31
(anonymous) @ EntityLink.jsx:31
(anonymous) @ EntityLink.jsx:31
(anonymous) @ EntityListLoader.jsx:140
UNSAFE_componentWillMount @ EntityListLoader.jsx:160
callComponentWillMount @ react-dom.development.js:12953
mountClassInstance @ react-dom.development.js:13048
updateClassComponent @ react-dom.development.js:17101
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 43 more frames
VM2823 react_devtools_backend.js:2540 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TextInputstyled__ClearButton
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11371
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPendingDiscreteUpdates @ react-dom.development.js:21847
flushDiscreteUpdates @ react-dom.development.js:21827
finishEventHandler @ react-dom.development.js:764
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
VM2823 react_devtools_backend.js:2540 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TextInputstyled__ClearButton
overrideMethod @ VM2823 react_devtools_backend.js:2540
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
push.../../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11377
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23112
commitRootImpl @ react-dom.development.js:22396
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPendingDiscreteUpdates @ react-dom.development.js:21847
flushDiscreteUpdates @ react-dom.development.js:21827
finishEventHandler @ react-dom.development.js:764
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
```

</details>

I couldn't find anything relevant in the server logs.

**To Reproduce**
1. Edit a dashboard
2. Click `Add question`
3. Search for a question title that you know exists
4. It does not show up in results
5. Try searching the same phrase in global search
6. Question shows up at top of search results, click to open it

Most of this video is just the loading time during the search. You can feel free to skip around - there isn't anything very exciting. 

https://user-images.githubusercontent.com/29556484/146084497-1315ef9d-6da6-488d-b032-efc642b7c256.mp4

**Expected behavior**
This question should show up at the top of the search list for Add Question just as it does for Global Search. If not the top, it should be somewhere on the list.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.186-146.268.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "postgres",
      "snowflake",
      "h2",
      "sparksql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-10",
      "tag": "v0.41.5-SNAPSHOT",
      "branch": "convoy-release-0.41.4",
      "hash": "7cf979c"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
This is low priority. Users are working around this by using `Add to dashboard` directly from the question.

### PR DESCRIPTION
**Pull request by escherize**
Fixes #19366

- use the results of all text scorers instead of just the max.
- add tests

## Use all the text-* matcher results

Instead of the max one, there is some signal to be gained by taking all of them, and combining every sort of score (i.e. a map with `:name`, `:score`, `:weight`) right at the end. That helps figure out "Why is it sorted this way", which is a question I was trying to figure out at first.

## Introduces the `prefix-scorer`.

Even though it seems naive, this scorer helps gain more signal, and it is also really fast. In my testing it has helped to boost exact matches too.

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/search/scoring_test.clj [hunk 1]
```diff
@@ -18,67 +21,104 @@
...
+    (-> (scoring/score-and-result search-string item) :score)))
 
 (defn- oss-score
-  [search-string]
-  (fn [item]
-    (with-redefs [#_{:clj-kondo/ignore [:deprecated-var]} premium-features/enable-enhancements? (constantly true)]
-      (-> (scoring/score-and-result search-string item) :score))))
+  [search-string item]
+  (with-redefs [#_{:clj-kondo/ignore [:deprecated-var]}
+                premium-features/enable-enhancements? (constantly false)]
```
Comment (escherize) [inline enterprise/backend/test/metabase_enterprise/search/scoring_test.clj:32]: This typo caused me to make a bunch of changes in these tests! `oss-score` and `ee-score` were behaving the same way.

File: src/metabase/search/scoring.clj [hunk 2]
```diff
@@ -138,23 +136,44 @@
...
-    :weight 1}
-   {:scorer fullness-scorer
-    :weight 1/2}
-   {:scorer exact-match-scorer
-    :weight 2}])
+  [{:scorer exact-match-scorer :name "exact-match" :weight 4}
+   {:scorer consecutivity-scorer :name "consecutivity" :weight 2}
+   {:scorer total-occurrences-scorer :name "total-occurrences" :weight 2}
+   {:scorer fullness-scorer :name "fullness" :weight 1}
+   {:scorer prefix-scorer :name "prefix" :weight 1}])
```
Comment (escherize) [inline src/metabase/search/scoring.clj:177]: Sorted these by their weights. Also added prefix-scorer.

File: src/metabase/search/scoring.clj [hunk 3]
```diff
@@ -271,31 +275,51 @@
...
-     ;; If the search string is non-blank, results with no text match have a score of zero.
-     (if (or (str/blank? raw-search-string)
-             (pos? (:score text-match)))
-       {:score  (/ (reduce + (map (fn [{:keys [weight score]}] (* weight score)) scores))
-                   (reduce + (map :weight scores)))
-        :result (serialize result text-match scores)}
-       {:score 0}))))
+  "Returns a map with the normalized, combined score from relevant-scores as `:score` and `:result`."
+  [raw-search-string result]
+  (let [text-matches     (force-weight (text-scores-with-match raw-search-string result) 10)
```
Comment (escherize) [inline src/metabase/search/scoring.clj:298]: To disrupt less testing, we keep the text-matches at weight 10. We just return all of them, so we can get a clearer picture of the "why" behind result sorting.

File: src/metabase/search/scoring.clj [hunk 4]
```diff
@@ -271,31 +275,51 @@
...
+    ;; Searches with a blank search string mean "show me everything, ranked";
+    ;; see https://github.com/metabase/metabase/pull/15604 for archived search.
+    ;; If the search string is non-blank, results with no text match have a score of zero.
+    (if (or (str/blank? raw-search-string)
+            (pos? (reduce + (map :score text-matches))))
+      {:score total-score
+       :result (serialize result all-scores relevant-scores)}
+      {:score 0})))
+
+(defn compare-score
```
Comment (escherize) [inline src/metabase/search/scoring.clj:311]: `compare-score` was moved down since it wasn't needed until top-results

File: src/metabase/search/scoring.clj [hunk 5]
```diff
@@ -81,31 +81,29 @@
...
-                                                                  (f query-tokens match-tokens)))
-                                                             0
-                                                             (map :scorer weighted-scorers)))]
-                           :when  (and matched-text
-                                       (pos? score))]
-                       {:score               (/ score total-weight)
+  ;; TODO is pmap over search-result worth it?
+  (let [scores       (for [column      (search-config/searchable-columns-for-model (:model search-result))
+                           {:keys [scorer name weight]
+                            :as   _ws} weighted-scorers
```
Comment (tsmacdonald) [inline src/metabase/search/scoring.clj:91]: Nit, why bother with the `:as _ws` ?

File: src/metabase/search/scoring.clj [hunk 6]
```diff
@@ -81,31 +81,29 @@
                 {:is_match is-match
                  :text     (tokens->string text-tokens (not is-match))})))))
 
-(defn- text-score-with
+(defn- text-scores-with
   "Scores a search result. Returns a map with the score and other info about the text match,
    if there is one. If there is no match, the score is 0."
```
Comment (tsmacdonald) [inline src/metabase/search/scoring.clj:86]:
```suggestion
  "Scores a search result. Returns a vector of score maps, each containing the `:score`
  and other details about the text match, if there is one. If there is no match, a vector with a single map of score 0 will be returned."
```

(or something. And the linebreaking/whitespace will need fixing)

File: src/metabase/search/scoring.clj (hunk 2 above)
Comment (tsmacdonald) [reply src/metabase/search/scoring.clj:177]: Adding `name` *almost* makes me want a macro

```
(scorer consecutivity 2) ;; => {:scorer consecutivity-scorer :name "consecutivity" :weight 2}
```

but probably it's cleaner to just accept the repetition and not worry about it

File: src/metabase/search/scoring.clj [hunk 7]
```diff
@@ -164,14 +183,13 @@
...
   (if (seq raw-search-string)
-    (text-score-with match-based-scorers
-                     (tokenize (normalize raw-search-string))
-                     result)
-    {:score  0
-     :match  ""}))
+    (text-scores-with match-based-scorers
+                      (tokenize (normalize raw-search-string))
+                      result)
+    [{:score 0 :weight 1 :match ""}]))
```
Comment (tsmacdonald) [inline src/metabase/search/scoring.clj:192]: I'm wondering if `text-scores-with` should handle the nil `raw-search-string` case so that its `{:score 0 ...}` result can be returned if there's no search string or if there's no match, instead of having the separate `{:score 0 ...}` here.

I also don't understand why the one in `text-scores-with` has weight 0 and this one has weight 1.

(I have a sinking sensation that if you `git blame` long enough you'll discover I'm the one who wrote it that way in the first place. If so, sorry!)

**Review by tsmacdonald — APPROVED** [review]
:boat:

File: src/metabase/search/scoring.clj [hunk 8]
```diff
@@ -271,31 +275,53 @@
...
+      (/ score-sum weight-sum))))
+
+(defn force-weight
+  "Reweight `scores` such that the sum of their weights equals `total`, and their proportions do not change."
+  [scores total]
+  (let [total-found (reduce + (map :weight scores))]
+    (mapv #(update % :weight (fn [weight]
+                               (if (contains? #{nil 0} total-found)
+                                 0
+                                 (* total (/ weight total-found))))) scores)))
```
Comment (metamben) [inline src/metabase/search/scoring.clj:295]: Wouldn't it be clearer if we created a function before mapping? In the `(contains? #{nil 0} total-found)` case it'd be `(constantly 0)`.

File: test/metabase/api/search_test.clj [hunk 9]
```diff
@@ -134,7 +134,7 @@
 
 (def ^:private remove-databases
   "Remove DBs from the results, which is useful since test databases unrelated to this suite can pollute the results"
-  (partial filter #(not= (:model %) "database")))
+  (partial remove #(= (:model %) "database")))
```
Comment (metamben) [inline test/metabase/api/search_test.clj:137]: 👍

File: test/metabase/api/search_test.clj [hunk 10]
```diff
@@ -215,16 +215,16 @@
...
     (with-search-items-in-root-collection "test"
       (is (<= 4 (count (search-request-data :crowberto :q "test" :limit "100" :offset "2"))))))
   (testing "It offsets without limit properly"
     (with-search-items-in-root-collection "test"
-      (is (= 5 (count (search-request-data :crowberto :q "test" :offset "2"))))))
+      (is (<= 5 (count (search-request-data :crowberto :q "test" :offset "2"))))))
   (testing "It limits without offset properly"
     (with-search-items-in-root-collection "test"
-      (is (= 2 (count (search-request-data :crowberto :q "test" :limit "2"))))))
+      (is (>= 2 (count (search-request-data :crowberto :q "test" :limit "2"))))))
```
Comment (metamben) [inline test/metabase/api/search_test.clj:227]: It's not clear to me why we sometimes relax the lower bound, sometimes the upper bound.

File: test/metabase/search/scoring_test.clj [hunk 11]
```diff
@@ -302,3 +317,20 @@
     (is (nil? (-> {:name "dash" :model "dashboard"}
                   (#'scoring/serialize {} {})
                   :dataset_query)))))
+
+(deftest force-weight-test
+  (is (= [{:weight 10}]
+         (scoring/force-weight [{:weight 1}] 10)))
+
+  (is (= [{:weight 5N} {:weight 5N}]
```
Comment (metamben) [inline test/metabase/search/scoring_test.clj:325]: Wouldn't `5` work instead of `5N`?

**Review by metamben — APPROVED** [review]

File: src/metabase/search/scoring.clj (hunk 5 above)
Comment (escherize) [reply src/metabase/search/scoring.clj:91]: That is a trick I use to keep the alignment of the r.h.s. of the for comprehension from being too far over to the right

Screen Shot 2022-10-27 at 4 24 43 PM

If you think it's too weird I'm open to nixing it.

File: src/metabase/search/scoring.clj (hunk 7 above)
Comment (escherize) [reply src/metabase/search/scoring.clj]: Good catch, I'll try having `text-scores-with-match` handle the empty `raw-search-string`. I also have the philosophy that the more stuff someone does the more mistakes they'll make so mistakes aren't such a bad thing! Mine or yours!

File: src/metabase/api/search.clj [hunk 12]
```diff
@@ -440,36 +441,32 @@
                              query)} sql-alias]]
        :order-by order-clause})))
 
-(s/defn ^:private search
+(defn ^:private search
```
[the remark this answers is not in the document]
Comment (escherize) [reply src/metabase/api/search.clj]: No, I take those off because my debugger doesn't work with the schema/defn. I'll add it back in. 👍

File: src/metabase/search/scoring.clj [hunk 13]
```diff
@@ -138,23 +136,44 @@
...
 (def ^:private match-based-scorers
-  [{:scorer consecutivity-scorer
-    :weight 1}
-   {:scorer total-occurrences-scorer
-    :weight 1}
-   {:scorer fullness-scorer
-    :weight 1/2}
-   {:scorer exact-match-scorer
-    :weight 2}])
+  [{:scorer exact-match-scorer :name "exact-match" :weight 4}
```
[the remark this answers is not in the document]
Comment (escherize) [reply src/metabase/search/scoring.clj:172]: Yeah, And I think it does do that. Why are you confused here? Maybe I am missing something

File: src/metabase/search/scoring.clj [hunk 14]
```diff
@@ -244,21 +258,11 @@
...
-    :name   "recency"}
-   {:weight 1
-    :score  (dashboard-count-score result)
-    :name   "dashboard"}
-   {:weight 1/2
-    :score  (model-score result)
-    :name   "model"}])
+  [{:weight 2 :score (pinned-score result) :name "pinned"}
+   {:weight 2 :score (bookmarked-score result) :name "bookmarked"}
+   {:weight 3/2 :score (recency-score result) :name "recency"}
```
[the remark this answers is not in the document]
Comment (escherize) [reply src/metabase/search/scoring.clj:261]: I moved the other weights to integers, I think we agree that it's aesthetically pleasing. The reason I could do that is because I force the "text-*" scorers total weight to be exactly 10. Meaning the weights I changed are only relative to each other. But doubling these weights would reduce the signal coming from the "text-*" scorers, so I left them unchanged.

File: src/metabase/search/scoring.clj [hunk 15]
```diff
@@ -271,31 +275,53 @@
    [result]
    (weights-and-scores result))
 
+(defn- compute-normalized-score [scores]
+  (let [weight-sum (reduce + (map #(or (:weight %) 0) scores))
```
[the remark this answers is not in the document]
Comment (escherize) [reply src/metabase/search/scoring.clj]: I noticed that I was doing this weight summing in a few places, and pulled it out into a fn.

```
(defn- sum-weights [weights]
  (reduce
   (fn [acc {:keys [weight] :or {weight 0}}]
     (+ acc weight))
   0
   weights))
```

`:weight` might not be there, but the weights are assumed to be maps.

File: src/metabase/search/scoring.clj [hunk 16]
```diff
@@ -271,31 +275,53 @@
...
+                   0
+                   scores)]
+    (if (zero? weight-sum)
+      0
+      (/ score-sum weight-sum))))
+
+(defn force-weight
+  "Reweight `scores` such that the sum of their weights equals `total`, and their proportions do not change."
+  [scores total]
+  (let [total-found (reduce + (map :weight scores))]
```
[the remark this answers is not in the document]
Comment (escherize) [reply src/metabase/search/scoring.clj]: This is the second place I'm computing the total weight, I've pulled it into a fxn.

File: src/metabase/search/scoring.clj (hunk 13 above)
[the remark this answers is not in the document]
Comment (metamben) [reply src/metabase/search/scoring.clj:172]: Just because the original issue seems to about an exact match not getting top score.

File: test/metabase/api/search_test.clj (hunk 10 above)
Comment (escherize) [reply test/metabase/api/search_test.clj]: It's related to the change in search ordering.

There an updated search ordering, and `search-request-data` removes databases (for a good reason -- e.g. if you have test databases they will show up in the search results, so the tests would be unstable based on the testing env).

So that is why the results here changed -- I think I can use `=` instead tho, after all.

**Comment by flamber** [comment]
@escherize Is this going into 45 or 46? If 45, then you need to add `backport` label to this PR.
