### PR TITLE
Fix min extent histogram

### LINKED ISSUE #48021: Regression: y-axis minimum is ignored for stacked 100% histograms
### Describe the bug

A regression was introduced in the last few versions of Metabase.
For stacked 100% histgrams the y-axis minimum value is now ignored. It used to work.
It was fixed for simple stacked histograms, but not for "stacked 100%" histograms.

The following issue is the same bug, but it was only partially fixed:
https://github.com/metabase/metabase/issues/44672#issuecomment-2228586365

### To Reproduce

See reproduction in https://github.com/metabase/metabase/issues/44672.

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.223-212.873.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-12",
      "tag": "v0.50.12",
      "hash": "86d4671"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

### Severity

low

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tsplude**
Closes #48021 

- Respect custom min / max axis values in normalized stacked charts
- Switches input format of normalized min / max values so that users now input non-normalized values (e.g. 10 for 10% rather than 0.1)
- Fixes small bug where you could not set 0 as max value

<details>
<summary>Before</summary>
image
</details>
<details>
<summary>After</summary>
image
</details>

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts [hunk 1]
```diff
@@ -33,8 +33,20 @@ const getCustomAxisRange = (
   axisExtent: Extent,
   customMin: number | null,
   customMax: number | null,
+  settings: ComputedVisualizationSettings,
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts:36]: Wdyt if we replace settings with `isNormalized: boolean`?

File: frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts [hunk 2]
```diff
@@ -514,7 +514,7 @@ export function getYAxisModel(
   seriesKeys: string[],
   seriesNames: string[],
   stackModels: StackModel[],
-  trasnformedDataset: ChartDataset,
+  transformedDataset: ChartDataset,
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts:517]: 🙏

**Review by alxnddr — COMMENTED** [review]
Could you please add a spec as well?

To add a visual spec you need to add a new story to `frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx`

**Review by alxnddr — APPROVED** [review]
