### PR TITLE
Fix issue with goal line position when chart has a single data point

### LINKED ISSUE #5448: Goal lines are twice as high in dashboards
I have a dashboard with few cards containing bar charts a set goal line. It also has a date filter (all options) with default value last 60 days.

When I change the date filter to "today" or "yesterday" the goal lines are twice as high as they should be. For example 2000 instead of 1000.

### PR DESCRIPTION
**Pull request by attekei**
Fixes #5448 and implements the fix suggested in https://github.com/metabase/metabase/issues/5448#issuecomment-318584337

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js [hunk 1]
```diff
@@ -1175,7 +1175,8 @@ export default function lineAreaBar(element: Element, {
         const goalValue = settings["graph.goal_value"];
         const goalData = [[xDomain[0], goalValue], [xDomain[1], goalValue]];
         const goalDimension = crossfilter(goalData).dimension(d => d[0]);
-        const goalGroup = goalDimension.group().reduceSum(d => d[1]);
+        // take the last point rather than summing in case xDomain[0] === xDomain[1], e.x. single row
+        const goalGroup = goalDimension.group().reduce((p,d) => d[1], (p,d) => p, () => 0);
```
Comment (salsakran) [inline frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js]: can you add a bit more commentary around what's going on in this expression?

**Review by salsakran — APPROVED** [review]
