### PR TITLE
Fix for #23940: Error sending emails when reply-to setting contains empty string

### LINKED ISSUE #23940: Error sending emails when reply-to setting contains empty string
This bug was introduced in https://github.com/metabase/metabase/pull/23381, so a fix should be backported to release-x.44.0

Typing an empty string (by typing and then pressing backspace) into the reply-to address field in the Admin > Settings > Email form breaks email sending.
image

Steps to reproduce: 
1. Setup SMTP settings (e.g. use `maildev -s 25 -w 80` and see cypress test setup [here](https://github.com/metabase/metabase/blob/master/frontend/test/__support__/e2e/helpers/e2e-email-helpers.js#L13)). Make sure you have set something in the reply-to address field.
2. Send a test email
3. Delete the contents of the Reply-to address field, and save your changes.
4. Try sending a test email again. The email will not send and you will see the error.

The error stems from `email-reply-to` being a list containing an empty string, where it should be nil.
```
email-test=> (email-reply-to)
("")
```

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/23940
Bug introduced in https://github.com/metabase/metabase/pull/23381

Made a couple of changes:
- The value of the reply-to setting on the FE will be `null` instead of `[""]` if the input field's value is "".
- The value of the reply-to setting on the BE will be validated to be a list of emails, so the value can never set to [""] anyway.

### CODE REVIEW

File: frontend/src/metabase/admin/settings/selectors.js [hunk 1]
```diff
@@ -214,7 +214,7 @@ const SECTIONS = updateSectionsWithPlugins({
         type: "string",
         required: false,
         widget: SettingCommaDelimitedInput,
-        validations: [["email_list", t`That's not a valid email addresses`]],
+        validations: [["email_list", t`That's not a valid email address`]],
```
Comment (WiNloSt) [inline frontend/src/metabase/admin/settings/selectors.js:217]: Do we only allow 1 reply-to email? The setting description tells otherwise and that's a bit confusing.
image.

And you might want to fix the copy here as well?
https://github.com/metabase/metabase/blob/68572a75df81e5a7e51e5f87fc8b5b89a5c9175c/frontend/src/metabase/admin/settings/components/SettingsBatchForm.jsx#L24

File: src/metabase/email.clj [hunk 2]
```diff
@@ -22,9 +22,19 @@
...
+(def ^:private ^{:arglists '([reply-to-addresses])} validate-reply-to-addresses
+  (s/validator ReplyToAddresses))
+
 (defsetting email-reply-to
   (deferred-tru "The email address you want the replies to go to, if different from the from address. You can have multiple reply-to email addresses, just separate them with a comma.")
-  :type :json)
+  :type :json
+  :setter (fn [new-value]
+            (->> new-value
+                 (validate-reply-to-addresses)
```
Comment (qnkhuat) [inline src/metabase/email.clj:36]:
```suggestion
                 validate-reply-to-addresses
```
nit: we could drop the parenthesis when threading without args

File: frontend/src/metabase/admin/settings/selectors.js (hunk 1 above)
Comment (WiNloSt) [reply frontend/src/metabase/admin/settings/selectors.js:217]: If we support multiple reply-to addresses, then we're gonna change the FE part a bit too. Now the PR seems to assume we can only input 1 email.

Comment (calherries) [reply frontend/src/metabase/admin/settings/selectors.js:217]: Good catch. The FE copy was wrong and I've since updated it. We currently support one reply-to email, with the option to extend it to more than one email address in the future, which is why it's stored as a JSON list.

**Review by WiNloSt — APPROVED** [review]
FE parts look good to me 👍

**Review by qnkhuat — APPROVED** [review]
