### PR TITLE
Make stacked row chart tooltips use custom display names

### LINKED ISSUE #66574: Stacked Row Chart Tooltips do not Display the "Renamed" Series Names
### Describe the bug

Row chart tooltips do not display the "renamed" series titles.

### To Reproduce

1. Create a row chart
2. Rename the series
3. Hover over the rows and see the new name sin the tooltips
4. Set display to "stacked"
5. Now hover again and note the tooltips do not display the renamed series names

[Loom Recording](https://www.loom.com/share/bb721dc845d74f0e8c93f3282d10bafc
)

**Note:**

You'll probably hit this bug while trying to reproduce:
https://github.com/metabase/metabase/issues/66490

If so just rename the series in a bar chart first. Then display as a row and process with reproduction steps.

### Expected behavior

The tooltips should display the names provided in viz settings.

### Logs

_No response_

### Information about your Metabase installation

```JSON
v56.17 and stats
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andsalves**
closes #66574
Closes https://linear.app/metabase/issue/UXW-2478/stacked-row-chart-tooltips-do-not-display-the-renamed-series-names

### Description

This fixes the stacked row bar chart tooltips, that are not using custom label names for data rows.

### How to verify

1. Create a row chart, and then on Data settings rename an X-axis series by clicking the ellipsis icon;
2. Observe the tooltips on the chart bars show the custom name properly
3. On the Display settings, make the chart be stacked.
4. Make sure the custom names on the tooltips still work properly.

### Demo
https://www.loom.com/share/0e149f25be744c8ea38111952cb4ad69

### Checklist

- [X] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts [hunk 1]
```diff
@@ -211,7 +211,9 @@ export const getStackedTooltipRows = <TDatum>(
       }
 
       return {
-        name: series.seriesName,
+        name:
+          settings?.series_settings?.[series.seriesKey]?.title ??
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts]: There are a few places with this logic, I wonder if we can have this series object to always have correct `seriesName` so we don't need to try checking `settings?.series_settings?.[series.seriesKey]?.title` first in every place where we try to get the actual series name. If for some reason we need to have the raw series name, then we could add `displaySeriesName` prop

**Review by alxnddr — APPROVED** [review]
Awesome!
