### PR TITLE
Fix missing translation of Others on the row chart

### LINKED ISSUE #14451: Row chart "Others" series is not translated
**Describe the bug**
Row chart "Others" series is not translated - and is not available in POEditor. Seems like it's part of magic from DC.js library.
In pie charts, it's called "Other" and was fixed in #11542, so for consistency it should probably be called the same.

**To Reproduce**
1. Simple question > Sample Dataset > Products
2. Summarize Count by Vendor
image

**Information about your Metabase Installation:**
Tested 0.34.3 thru 0.38.0-rc2

**Additional context**
Related to #12523

### PR DESCRIPTION
**Pull request by alxnddr**
### Description

"Others" was not translated on the row chart because it came from dc.js. There is a way to configure it.
https://dc-js.github.io/dc.js/docs/html/dc.capMixin.html

Fixes https://github.com/metabase/metabase/issues/14451

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/RowRenderer.js [hunk 1]
```diff
@@ -117,7 +118,8 @@ export default function rowRenderer(
     .elasticX(true)
     .dimension(dimension)
     .group(group)
-    .ordering(d => d.index);
+    .ordering(d => d.index)
+    .othersLabel(t`Others`);
```
Comment (flamber) [inline frontend/src/metabase/visualizations/lib/RowRenderer.js:122]: We need an English native here. Pie chart is "Other", so we should probably just use that?

**Review by flamber — APPROVED** [review]

File: frontend/src/metabase/visualizations/lib/RowRenderer.js (hunk 1 above)
Comment (daltojohnso) [reply frontend/src/metabase/visualizations/lib/RowRenderer.js:122]: hmmmm, I think "Others" works fine here. I think "Other" works for pie charts because you're looking at percentages.

**Review by daltojohnso — APPROVED** [review]
