### PR TITLE
QueryBuilder and SQL questions: hide Explore results with parameters

### LINKED ISSUE #35476: Don't show "explore results" on SQL questions with filters
### Describe the bug

If you build a SQL question with filters and then click on explore results, question will fail, so don't make the users trip on this error

### To Reproduce

1) create a sql question (select * from people where state = {{state}})
2) click on explore results

see the error

### Expected behavior

that button shouldn't appear if there are filters

### Logs

_No response_

### Information about your Metabase installation

```JSON
NA
```

### Severity

It has been like that forever

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by oleggromov**
Fixes https://github.com/metabase/metabase/issues/35476

### Description
Sometimes SQL-based questions could be used a data source for GUI questions, which is done by clicking "Explore results".

This is only possible though when a few conditions are met, and the missing one was that the question must have exactly 0 parameters (as per issue). 

This PR fixes it and does a bit of housekeeping. 

### How to verify

1. Create an SQL question without parameters, click save - you should see the "Explore results" button
2. Now add a parameter, for instance, `select * from orders where product_id = {{product_id}}`, click "Save" - the button must not show
3. There's a known bug: https://github.com/metabase/metabase/issues/36104 (see the last comment, there's a link to the one that supercedes it) 

### Demo

https://github.com/metabase/metabase/assets/2196347/c1d0da47-b8f8-436f-a001-56bb6016a01e

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase-lib/Question.ts [hunk 1]
```diff
@@ -1249,6 +1249,21 @@ class Question {
...
+  canExploreResults() {
+    return (
+      this.isNative() &&
+      this.isSaved() &&
+      this.parameters().length === 0 &&
+      this.query().canNest() &&
+      !this.query().readOnly() // originally "canRunAdhocQuery"
+    );
+  }
+
```
Comment (oleggromov) [inline frontend/src/metabase-lib/Question.ts:1266]: I was a bit hesitant to enlarge this god-object even further but it's still better than keeping this logic in essentially a view.

A nice consequence of that is that we could easily test this behavior with just a few unit tests as it is a pure function, which doesn't require any mocking or integration. 

I've seen that there's no tests for the `Question` now. Should I add them?

Comment (ranquild) [reply frontend/src/metabase-lib/Question.ts:1266]: This is a (very) legacy file https://github.com/metabase/metabase/blob/bf45689cd60bf337bc93bc7e23abf98f4a481a91/frontend/test/metabase-lib/lib/Question.unit.spec.js#L324 but that's what we have right now. We should add tests for this change.

Comment (ranquild) [reply frontend/src/metabase-lib/Question.ts:1266]: Btw, for new things we don't separate test files from the implementation files

**Review by ranquild — COMMENTED** [review]
Looks good, please add tests

File: frontend/src/metabase-lib/queries/AtomicQuery.ts [hunk 2]
```diff
@@ -34,7 +34,7 @@ export default class AtomicQuery extends Query {
     return null;
   }
 
-  canNest() {
-    return this.database()?.hasFeature("nested-queries");
+  canNest(): boolean {
```
Comment (oleggromov) [inline frontend/src/metabase-lib/queries/AtomicQuery.ts:37]: Previously, this would've returned `undefined` or `true`.

File: frontend/src/metabase-lib/question.unit.spec.ts [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+    expect(q.canExploreResults()).toBe(false);
+  });
+
+  it("should be false with parameters", () => {
+    const card = createMockCard({
+      dataset_query: createMockNativeDatasetQuery({
+        type: "native",
+        native: {
+          query: "select * from order where id > {{min_id}}",
+          "template-tags": {
```
Comment (ranquild) [inline frontend/src/metabase-lib/question.unit.spec.ts:35]: `createMockTemplateTag`

File: frontend/src/metabase-lib/question.unit.spec.ts [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+            min_id: {
+              type: "text",
+              name: "min_id",
+              id: "uuid",
+              "display-name": "Min ID",
+            },
+          },
+        },
+      }),
+      parameters: [
```
Comment (ranquild) [inline frontend/src/metabase-lib/question.unit.spec.ts:45]: `createMockParameter`

File: frontend/src/metabase/query_builder/components/view/ExploreResultsLink.tsx [hunk 5]
```diff
@@ -0,0 +1,25 @@
+import { t } from "ttag";
+import Link from "metabase/core/components/Link";
+import ViewButton from "metabase/query_builder/components/view/ViewButton";
+import type Question from "metabase-lib/Question";
+import { getUrl as ML_getUrl } from "metabase-lib/urls";
+
+type Props = {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/view/ExploreResultsLink.tsx:7]: `interface ExploreResultsLinkProps`

**Review by ranquild — COMMENTED** [review]
@oleggromov Please use helpers like `createMockTemplateTag` for creating template tags and parameters in tests. This is to make sure all required properties have correct default values, now and in the future.

File: frontend/src/metabase/query_builder/components/view/ExploreResultsLink.tsx (hunk 5 above)
Comment (oleggromov) [reply frontend/src/metabase/query_builder/components/view/ExploreResultsLink.tsx:7]: If it's not exported, why would we need that?

**Review by ranquild — APPROVED** [review]
