### PR TITLE
Fix static viz ignore viz-settings order

### LINKED ISSUE #63962: Wrong Table column order gets sent via subscription
### Describe the bug

The order of a Table isn't respected when sent over a subscription email/slack

### To Reproduce

1. Go to New -> Dashboard -> Add New Question -> Orders -> Save
2. On the Dashborad -> Click Visualization option for this Card -> Move the ID from first to third column

Image

Image

3. Send a test subscription - notice order messed up

Image

.
NOTE: I create a dashboard on stats so you can easily test this https://stats.metabase.com/dashboard/4444-test-t

### Expected behavior

The order as seen in the dashboard is respected

### Logs

None that I found relevant

### Information about your Metabase installation

```JSON
Happens on 56 and master ... Doesn't happen on version 55
```

### Severity

A number of customers already reachout about this since mine is a simple example but in their case it messes their flow

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Resolves https://github.com/metabase/metabase/issues/63962

It's a regression from https://github.com/metabase/metabase/pull/62306/files where we tried to de-up the table-columns in viz-setting and accidentally break the order.
changed from `m/index-by` to use `m/distinct-by` which preserve the order.

This also fixes a bug that I think has been there for a long time is that when static viz render table that has viz-settings, some columns went missing a long with data.

For example this is what we get when sending the order table with columns re-arranged. notice we only have 7 columns here (we should have 9) and the row data is incorrect (Total shouldn't be a timestamp). more in the comment
Screenshot 2025-09-24 at 22 26 19

### CODE REVIEW

File: test/metabase/channel/render/body_test.clj [hunk 1]
```diff
@@ -1079,3 +1079,40 @@
...
+                               {:metabase.models.visualization-settings/table-column-name col-name
+                                :metabase.models.visualization-settings/table-column-enabled true}))}
+          [ordered-cols ordered-rows] (#'body/order-data test-data viz-settings)]
+      (testing "cols should follow table-columns order"
+        (is (= reordered-names (map :name ordered-cols))))
+      (testing "rows should be reordered to match columns"
+        (is (= ["alice@example.com" "Alice" "Boston" "MA" "02101" 1 "555-1234" "123 Main St" "USA" "2024-01-01"]
+               (first ordered-rows)))))))
+
+(deftest render-table-with-remapped-with-custom-columns-order-test
```
Comment (qnkhuat) [inline test/metabase/channel/render/body_test.clj:1104]: e2e test with a remapped column

**Comment by dpsutton** [comment]
```clojure
user=> (source medley.core/index-by)
(defn index-by
  "Returns a map of the elements of coll keyed by the result of f on each
  element. The value at each key will be the last element in coll associated
  with that key. This function is similar to `clojure.core/group-by`, except
  that elements with the same key are overwritten, rather than added to a
  vector of values."
  {:added "1.2.0"}
  [f coll]
  (persistent! (reduce #(assoc! %1 (f %2) %2) (transient {}) coll)))

user=> (source medley.core/distinct-by)
(defn distinct-by
  "Returns a lazy sequence of the elements of coll, removing any elements that
  return duplicate values when passed to a function f. Returns a transducer
  when no collection is provided."
  ([f]
   (fn [rf]
     (let [seen (volatile! #{})]
       (fn
         ([] (rf))
         ([result] (rf result))
         ([result x]
          (let [fx (f x)]
            (if (contains? @seen fx)
              result
              (do (vswap! seen conj fx)
                  (rf result x)))))))))
  ([f coll]
   (let [step (fn step [xs seen]
                (lazy-seq
                 ((fn [[x :as xs] seen]
                    (when-let [s (seq xs)]
                      (let [fx (f x)]
                        (if (contains? seen fx)
                          (recur (rest s) seen)
                          (cons x (step (rest s) (conj seen fx)))))))
                  xs seen)))]
     (step coll #{}))))
```

index-by returns the map so order is destroyed.

@qnkhuat what's the theory for the missing columns?

**Review by dpsutton — APPROVED** [review]
both tests pass for me without the santitized orders cols thing. I also don't understand how this could fix a long standing bug where columns went missing.

**Comment by qnkhuat** [comment]
@dpsutton the reason it's missing is because we have a mismatch in viz-setting we save in card and viz-settings we return from the qp in that if a card has remapped column:
- viz-settings from qp returns all the columns (including the original and remapped ones)
- viz-settings on the card will only includes columns that'll be displayed on the card (not the remapped from columns)

I've updated the test to truly be an e2e now.
