### PR TITLE
show meaningful error for waterfall chart of multiple series questions

### LINKED ISSUE #15152: Waterfall chart should not be selectable with more than 1 metric
**Describe the bug**
When results have more than 1 metric, then selecting Waterfall chart will display blank page.

**To Reproduce**
1. Custom question > Sample Dataset > Orders - summarize Count and Sum of Total grouped by CreatedAt:Year
image
2. Visualization > select Waterfall, which is enabled
image
3. The viz area is now blank (besides legends) - the browser console has errors like `TypeError: a[1][d] is undefined`
image
4. Remove one of the Y-axis series will correctly show the Waterfall chart
image

**Expected behavior**
When there's more than one metric, then Waterfall should be disabled.
There should not be "Add another series..." button under the Y-axis.

**Information about your Metabase Installation:**
Tested 0.38.0 thru 0.38.1, and master

### PR DESCRIPTION
**Pull request by alxnddr**
Fixes https://github.com/metabase/metabase/issues/15152

### Description

The original issue suggests disabling "Waterfall" visualization button when more than 1 metric is selected. I think it might be better to show a meaningful error message the same way as we do for the Row chart in the same situation. It seems like we use pseudo-disabled buttons to indicate data shape compatibility. Wdyt @flamber?

### How to verify

Check repro steps of the linked issue https://github.com/metabase/metabase/issues/15152

### Screenshots

Before
Screen Shot 2021-09-21 at 22 07 02

After
Screen Shot 2021-09-21 at 22 03 52

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/settings/graph.js [hunk 1]
```diff
@@ -152,13 +153,18 @@ export const GRAPH_DATA_SETTINGS = {
...
         .filter(vizSettings["graph._metric_filter"])
         .map(getOptionFromColumn);
+
+      const addedMetricsCount = vizSettings["graph.metrics"].length;
+      const supportedMetrics = getMaxMetricsSupported(card.display);
+
+      const canAddAnother =
+        addedMetricsCount < supportedMetrics &&
+        options.length > value.length &&
+        vizSettings["graph.dimensions"].length < 2;
```
Comment (kulyk) [inline frontend/src/metabase/visualizations/lib/settings/graph.js:163]: Mind improving the conditionals readability here?

`addedMetricsCount < supportedMetrics` is very straightforward, but the following conditions can be confusing, I guess. (btw, `supportedMetrics` sounds like a list of metrics to me, and not the number. Should we maybe call it like `maxMetricsCount` or `maxMetricsCountForDisplay`?)

`options.length > value.length` can be something like `hasMetricsToAdd` (if I understand the meaning behind it correctly)

`vizSettings["graph.dimensions"].length < 2` is a bit of a mystery for me TBH. Does `2` mean X and Y axes? Fixing the magic number and giving a meaningful name to the comparison can make things easier, I believe

**Review by kulyk — APPROVED** [review]
Looks great and works as described, good job! Have a minor readability thing inlined

Like the idea of showing an error instead of disabling the viz completely -- it's good to have some context _why_ the viz is unavailable and _what_ should people do to build a waterfall. But let's see what others think.

**Review by flamber — APPROVED** [review]
Think it's the right approach to mimic Row. That makes everything more consistent :tada:
If we then want to revisit how that is done, then we can do that generally.

File: frontend/src/metabase/visualizations/lib/settings/graph.js (hunk 1 above)
Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/settings/graph.js]: Thanks for pointing it out. I've made it more readable now
