### PR TITLE
Fix x axis range calculation when undefined values are present

### LINKED ISSUE #64921: Combining two timeseries in visualizer extends time axis up to current day
### Describe the bug

If you have two timeseries plots over specific periods in the past, and combine them with "Visualize another way", the X axes extends up to today resulting in extra empty space on the resulting graph

### To Reproduce

1. Go to E-Commerce Insights
2. Go to Edit
3. Add question - "Number of Subscriptions"
4. Click "Visualize another way" on this question
5. Add "Enormous Wool Car Trend"
6. Now the X axis extends up to today, but the plots are over past periods, so this adds mostly empty space:

Image

### Expected behavior

The combined plot should only cover both plotted periods and no extra periods

### Logs

_No response_

### Information about your Metabase installation

```JSON
v56.11
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ghostframe**
Closes https://github.com/metabase/metabase/issues/64921

Ignores undefined values (that appear when two timeseries are combined) for calculating the span of the x axis, where the range was erroneously interpreted as ending today (when parsing `undefined` as a date)

Following the repro, before:
image

After the fix:
image

### CODE REVIEW

File: frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts [hunk 1]
```diff
@@ -881,9 +881,11 @@ export function getXAxisModel(
   };
 }
 
-const getXAxisDateRangeFromSortedXAxisValues = (
+export const getXAxisDateRangeFromSortedXAxisValues = (
   xValues: RowValue[],
 ): DateRange | undefined => {
+  xValues = xValues.filter((x) => x !== undefined);
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts]: This comment is valid although a nit pick

**Review by alxnddr — APPROVED** [review]
Looks great! Please have a look at Metabot's comment before merging
