### PR TITLE
Fix not able to Enable/Disable Actions when Choose when syncs and scans happen is Enabled

### LINKED ISSUE #30699: Not able to Enable/Disable Actions when Choose when syncs and scans happen is Enabled
### Describe the bug

If Choose when syncs and scans happen is enabled it blocks me from clicking the Enable button of the Model Actions

image

You can only Enable/Disable when Choose when syncs and scans happen is Disabled

### To Reproduce

1. Go to Admin -> Database -> Sample Database
2. Choose when syncs and scans happen -> Enable it -> Save
3. Try to Enable Model Actions and it doesn't work

The Workaround is to Disable Choose when syncs and scans happen and Save ... Then Enable Model Actions ... Then Re-Enable Choose when syncs and scans happen ... Note that in this case you are not able to Disable it now

### Expected behavior

Able to Enable/Disable Model Actions

### Logs

No Error in the logs but when you click it it shows the following in the logs:

```
[6cad9d57-1904-4c70-a176-9fdfc5b48b54] 2023-05-11T16:52:15+02:00 INFO metabase.models.database :h2 Database 'Sample Database' sync/analyze schedules have changed! 
 Sync metadata was: '0 18 * * * ? *' is now: '0 8 * * * ? *' 
 Cache FieldValues was: '0 0 16 * * ? *', is now: '0 0 22 * * ? *'
```

### Information about your Metabase installation

```JSON
1.46.2 and master
```

### Severity

none

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/30699

### CODE REVIEW

File: src/metabase/api/database.clj [hunk 1]
```diff
@@ -912,15 +917,7 @@
 
                                     ;; if user is controlling schedules
                                     (:let-user-control-scheduling details)
-                                    (sync.schedules/schedule-map->cron-strings (sync.schedules/scheduling schedules))
-
-                                    ;; upsert settings with a PATCH-style update. `nil` key means unset
-                                    ;; the Setting.
-                                    (seq settings)
-                                    {:settings (into {}
```
Comment (calherries) [inline src/metabase/api/database.clj:920]: This should simply be independent from the other conditions

**Review by qnkhuat — APPROVED** [review]
