### PR TITLE
Doing isBreakout check sooner, removing column formatting from 2nd dimension

### LINKED ISSUE #26765: Visualization settings can crash Query Builder
**Describe the bug**
Dimensions and formatting settings show invalid states, errors, and crash the entire app.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

**To Reproduce**
1. New -> Orders
2. Change Viz type to Bar
3. Select X-axis: ID, add a breakout by Total
4. Click on the Total dimension formatting settings
5. The app has crashed
6. Press the browser back button: it shows an invalid state: no breakout dimension but `undefined` sort item

**Expected behavior**
It does not crash

**Video**
<video src="https://user-images.githubusercontent.com/14301985/204292111-c87f353d-1204-4c7d-98e6-935177005436.mov" />

**Severity**
P2?

### PR DESCRIPTION
**Pull request by npfitz**
Fixes #26765 

Change to `getSeriesSettings` function where we detect if the series is a breakout series sooner, because if no metric has been set, than `series.data.cols` will not have a second element. We also hide the column settings on any dimension that isn't the first one, since making changes to the breakout dimension will have no impact on the visualization at that point in time, it ends up looking like something is broken because nothing is changing.

Adding a filter, we can see that we get a legitimate (if maybe not very useful 😅) graph:
image

And moving `Tax` to be the first dimension of the graph then gives us the opportunity to format the colum as we see fit
image

### CODE REVIEW

**Comment by WiNloSt** [comment]
Unrelated to this change. I've noticed the viz settings have become significantly slower lately in certain inputs e.g. number of decimal places and value multiplier.
Screenshot 2022-11-29 at 10 35 47 AM

Here you can see that in v0.44 it was already slow (800ms after a single key press) but isn't that slow compared to the current state (1.6–1.8s after a single key press) which is about double the waiting time.

#### v0.44
0 44 perf

#### `master` branch
master perf

#### this PR
branch perf

Not sure how serious this is, but it could get annoying.

File: frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPicker.jsx [hunk 1]
```diff
@@ -51,6 +53,11 @@ const ChartSettingFieldsPicker = ({
                         >
                           <ChartSettingFieldPicker
                             {...props}
+                            showColumnSetting={
+                              _.isArray(showColumnSetting)
+                                ? showColumnSetting.includes(index)
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPicker.jsx:58]: `index` is used pretty far from where it's declared (almost 20 lines apart), do you think giving it a more specific name would help this part be easier to read? e.g.
```suggestion
                                ? showColumnSetting.includes(columnIndex)
```

File: frontend/src/metabase/visualizations/lib/settings/graph.js [hunk 2]
```diff
@@ -146,7 +146,7 @@ export const GRAPH_DATA_SETTINGS = {
             ? t`Add series breakout`
             : null,
         columns: data.cols,
-        showColumnSetting: true,
+        showColumnSetting: [0],
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/lib/settings/graph.js:149]: TBH, seeing this alone feels a bit weird. I wish we could add type to this, so it's easier to understand what this does. Maybe a comment could or giving the value a name would help with that?

**Review by WiNloSt — APPROVED** [review]
I'm feeling like we should improve the hard-coded value `[0]` though I'm not currently sure how. But overall this fixes the bug, so it should be good to go.

File: frontend/src/metabase/visualizations/lib/settings/graph.js (hunk 2 above)
Comment (npfitz) [reply frontend/src/metabase/visualizations/lib/settings/graph.js:149]: Yeah, I feel that. Especially when we don't have some of these things documented. I'll add a comment explaining the prop

**Comment by npfitz** [comment]
One big reason that things have gotten slower is the amount of times I'm calculating widgets and calculated settings now (getting the style widget, column formatting widget, etc). We could certainly optimize this with some memoization

**Comment by alxnddr** [comment]
The performance issue @WiNloSt found seems like an important issue to be fixed before 45

**Comment by npfitz** [comment]
I'll see what I can do, but it's not related to this PR

**Comment by alxnddr** [comment]
@npfitz `Add a prefix` field triggers an update on blur which feels better, so it can be a simple fix like that

File: frontend/src/metabase/visualizations/lib/settings/graph.js (hunk 2 above)
Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/settings/graph.js:151]: Maybe `showForIndices` or something like that would be more clear

**Review by alxnddr — APPROVED** [review]
Works well, I could get any invalid states 👍

File: frontend/src/metabase/visualizations/lib/settings/graph.js (hunk 2 above)
Comment (npfitz) [reply frontend/src/metabase/visualizations/lib/settings/graph.js:151]: I'd really like to avoid changing the name of the prop, unless you're suggesting I add separate prop and resolve it in `ChartSettingFieldsPicker`

Comment (alxnddr) [reply frontend/src/metabase/visualizations/lib/settings/graph.js:151]: A separate prop sounds better too because future engineers may struggle to understand `showColumnSetting` potentially be a boolean or an array

Comment (npfitz) [reply frontend/src/metabase/visualizations/lib/settings/graph.js:151]: I hate it when you're right haha. But I agree. I'll update this PR

**Comment by WiNloSt** [comment]
@alxnddr @npfitz Using `onblur` could help mitigate some slowness, but I think the underlying problem should still be fixed because in some cases, they will still be slow e.g. for settings that require clicking like dropdown or click to add more breakout or metrics.

Although I tested this briefly this morning, it seems to be a lot faster, not sure if it's because my laptop was restarted or @npfitz has made the magic happen 😄

**Comment by npfitz** [comment]
I also noticed it was quite a bit quicker than what you were experiencing. It's also proportional to the size of the series, so it may not be what I originally thought haha
