### PR TITLE
Do not set card when using browser back button

### LINKED ISSUE #56775: Edit Query Definition does not open the models definition after using browser back button
### Describe the bug

After using the browser's back button clicking "Edit query definition" incorrectly opens a new questions definition instead of the models definition until the model page is reloaded.

### To Reproduce

1. Open a model
2. Click on editor
2. Click on visualize
3. Hit the browser back button to return to the model
4. Click on edit query definition, and see the error: 
the model wrapped into a new question is opened rather than the models definition
Image
5. After this point, Edit query definition no longer opens up the model unless the model's page is reloaded.

### Expected behavior

The models definition should be opened regardless of the previous browse events.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  }
}
```

### Severity

Annoying, reported by a customer

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/56775

When clicking `Visualize` from a question started from a Model, we don't "uncompose" the question. This caused the wrong state being saved when clicking the back button.

### To verify

1. Open a model
2. Click on editor
3. Click on visualize
4. Hit the browser back button to return to the model
6. Click on edit query definition
7. The correct query should be shown (not the wrapped model).

### CODE REVIEW

File: frontend/src/metabase/query_builder/actions/navigation.ts [hunk 1]
```diff
@@ -176,8 +177,9 @@ export const updateUrl = createThunkAction(
         datasetEditorTab = getDatasetEditorTab(getState());
       }
 
+      const card = isAdHocModelOrMetric ? getCard(getState()) : question.card();
       const newState = {
-        card: question._doNotCallSerializableCard(),
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/actions/navigation.ts:180]: We can remove `Question.prototype._doNotCallSerializableCard`

**Review by kamilmielnik — APPROVED** [review]
