### PR TITLE
Sourcing column ids from metadata if present

### LINKED ISSUE #28145: Model written in SQL doesn't load dropdown list on Dashboard when used with a Category Filter
**Describe the bug**
Model written in SQL doesn't load dropdown list on Dashboard when used with a Category Filter 

**Logs**

<details><summary>Full stacktrace</summary>

```
[7c13e9c9-fb7c-486f-a589-ef6957eb6132] 2023-02-08T13:28:10+01:00 DEBUG metabase.server.middleware.log GET /api/dashboard/2/params/f5d17ab6/values 400 53.1 ms (5 DB calls) 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "Parameter \"f5d17ab6\" does not have any Fields associated with it",
   :data
   {:param
    {:name "Text 2",
     :slug "text_2",
     :id "f5d17ab6",
     :type :string/=,
     :sectionId "string",
     :mappings
     #{{:parameter_id "f5d17ab6",
        :card_id 12,
        :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]],
        :dashcard
        {:size_x 4,
         :action_id nil,
         :collection_authority_level nil,
         :card
         {:description nil,
          :archived false,
          :collection_position 2,
          :table_id nil,
          :result_metadata
          ({:display_name "ID",
            :semantic_type :type/PK,
            :field_ref [:field "ID" {:base-type :type/BigInteger}],
            :name "ID",
            :base_type :type/BigInteger,
            :effective_type :type/BigInteger,
            :fingerprint nil}
           {:display_name "EAN",
            :field_ref [:field "EAN" {:base-type :type/Text}],
            :name "EAN",
            :base_type :type/Text,
            :effective_type :type/Text,
            :semantic_type nil,
            :fingerprint
            {:global {:distinct-count 200, :nil% 0.0},
             :type
             {:type/Text
              {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 13.0}}}}
           {:display_name "TITLE",
            :semantic_type :type/Title,
            :field_ref [:field "TITLE" {:base-type :type/Text}],
            :name "TITLE",
            :base_type :type/Text,
            :effective_type :type/Text,
            :fingerprint
            {:global {:distinct-count 199, :nil% 0.0},
             :type
             {:type/Text
              {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.495}}}}
           {:description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
            :semantic_type :type/Category,
            :name "CATEGORY",
            :field_ref [:field "CATEGORY" {:base-type :type/Text}],
            :effective_type :type/Text,
            :id 63,
            :visibility_type :normal,
            :display_name "Category",
            :fingerprint
            {:global {:distinct-count 4, :nil% 0.0},
             :type
             {:type/Text
              {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
            :base_type :type/Text}
           {:display_name "VENDOR",
            :semantic_type :type/Company,
            :field_ref [:field "VENDOR" {:base-type :type/Text}],
            :name "VENDOR",
            :base_type :type/Text,
            :effective_type :type/Text,
            :fingerprint
            {:global {:distinct-count 200, :nil% 0.0},
             :type
             {:type/Text
              {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}}}
           {:display_name "PRICE",
            :field_ref [:field "PRICE" {:base-type :type/Float}],
            :name "PRICE",
            :base_type :type/Float,
            :effective_type :type/Float,
            :semantic_type nil,
            :fingerprint
            {:global {:distinct-count 170, :nil% 0.0},
             :type
             {:type/Number
              {:min 15.691943673970439,
               :q1 37.25154462926434,
               :q3 75.45898071609447,
               :max 98.81933684368194,
               :sd 21.711481557852057,
               :avg 55.74639966792074}}}}
           {:display_name "RATING",
            :semantic_type :type/Score,
            :field_ref [:field "RATING" {:base-type :type/Float}],
            :name "RATING",
            :base_type :type/Float,
            :effective_type :type/Float,
            :fingerprint
            {:global {:distinct-count 23, :nil% 0.0},
             :type
             {:type/Number
              {:min 0.0,
               :q1 3.5120465053408525,
               :q3 4.216124969497314,
               :max 5.0,
               :sd 1.3605488657451452,
               :avg 3.4715}}}}
           {:display_name "CREATED_AT",
            :semantic_type :type/CreationTimestamp,
            :field_ref [:field "CREATED_AT" {:base-type :type/DateTime}],
            :name "CREATED_AT",
            :base_type :type/DateTime,
            :effective_type :type/DateTime,
            :fingerprint
            {:global {:distinct-count 200, :nil% 0.0},
             :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147Z", :latest "2019-04-15T13:34:19.931Z"}}}}),
          :database_id 1,
          :enable_embedding false,
          :collection_id nil,
          :query_type :native,
          :name "products_model",
          :creator_id 1,
          :updated_at #t "2023-02-08T12:28:02.188319Z",
          :made_public_by_id nil,
          :embedding_params nil,
          :cache_ttl nil,
          :dataset_query {:type :native, :native {:query "Select * from products", :template-tags {}}, :database 1},
          :id 12,
          :parameter_mappings [],
          :display :table,
          :entity_id "6YukSvXZYQ2XjIvpWK0yN",
          :collection_preview true,
          :visualization_settings {:table.pivot_column "CATEGORY", :table.cell_column "ID"},
          :is_write false,
          :parameters [],
          :dataset true,
          :created_at #t "2023-02-08T12:07:09.994967Z",
          :public_uuid nil},
         :updated_at #t "2023-02-08T12:28:06.435645Z",
         :col 7,
         :id 9,
         :parameter_mappings
         [{:parameter_id "f5d17ab6", :card_id 12, :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]]}],
         :card_id 12,
         :entity_id "e0OH1kMW17EwGUo8evYEI",
         :visualization_settings {},
         :size_y 3,
         :dashboard_id 2,
         :created_at #t "2023-02-08T12:27:44.627410Z",
         :row 0}}}},
    :status-code 400},
   :at [metabase.api.dashboard$fn__75998$chain_filter__76007$fn__76010 invoke "dashboard.clj" 718]}],
 :trace
 [[metabase.api.dashboard$fn__75998$chain_filter__76007$fn__76010 invoke "dashboard.clj" 718]
  [metabase.api.dashboard$fn__75998$chain_filter__76007 invoke "dashboard.clj" 691]
  [metabase.api.dashboard$fn__75998$chain_filter__76007$fn__76008 invoke "dashboard.clj" 704]
  [metabase.api.dashboard$fn__75998$chain_filter__76007 invoke "dashboard.clj" 691]
  [metabase.api.dashboard$fn__76033 invokeStatic "dashboard.clj" 748]
  [metabase.api.dashboard$fn__76033 invoke "dashboard.clj" 740]
  [compojure.core$wrap_response$fn__29313 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__29297 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__29302 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 151]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 152]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 152]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 153]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 153]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 153]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 153]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 152]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 152]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 152]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 153]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 152]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 153]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 153]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 153]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__71293 invoke "auth.clj" 17]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325 invoke "core.clj" 200]
  [compojure.core$make_context$handler__29353 invoke "core.clj" 289]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 299]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 199]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 199]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325 invoke "core.clj" 200]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 199]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325 invoke "core.clj" 200]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325 invoke "core.clj" 200]
  [metabase.api.routes$fn__83245$fn__83246 invoke "routes.clj" 62]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__83409$fn__83410 doInvoke "routes.clj" 69]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325 invoke "core.clj" 200]
  [compojure.core$make_context$handler__29353 invoke "core.clj" 289]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 299]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 152]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 152]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__29306 invoke "core.clj" 152]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 199]
  [compojure.core$routes$fn__29325$f__29326$respond_SINGLEQUOTE___29327 invoke "core.clj" 197]
  [compojure.core$make_context$fn__29357 invoke "core.clj" 300]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325 invoke "core.clj" 200]
  [compojure.core$routes$fn__29325$f__29326 invoke "core.clj" 198]
  [compojure.core$routes$fn__29325 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__79767 invoke "exceptions.clj" 98]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__79764 invoke "exceptions.clj" 86]
  [metabase.server.middleware.log$log_api_call$fn__86377$fn__86378$fn__86379 invoke "log.clj" 211]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 15]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 9]
  [metabase.server.middleware.log$log_api_call$fn__86377$fn__86378 invoke "log.clj" 203]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 236]
  [toucan.db$_do_with_call_counting invoke "db.clj" 229]
  [metabase.server.middleware.log$log_api_call$fn__86377 invoke "log.clj" 202]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__92548 invoke "browser_cookie.clj" 38]
  [metabase.server.middleware.security$add_security_headers$fn__64622 invoke "security.clj" 149]
  [metabase.server.middleware.json$wrap_json_body$fn__90098 invoke "json.clj" 63]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__90116 invoke "json.clj" 99]
  [metabase.server.middleware.offset_paging$handle_paging$fn__64646 invoke "offset_paging.clj" 42]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__92815 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__92834 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__36696 invoke "misc.clj" 59]
  [metabase.server.middleware.session$reset_session_timeout$fn__48385 invoke "session.clj" 394]
  [metabase.server.middleware.session$bind_current_user$fn__48368$fn__48369 invoke "session.clj" 331]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 310]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 299]
  [metabase.server.middleware.session$bind_current_user$fn__48368 invoke "session.clj" 330]
  [metabase.server.middleware.session$wrap_current_user_info$fn__48350 invoke "session.clj" 280]
  [metabase.server.middleware.session$wrap_session_id$fn__48334 invoke "session.clj" 213]
  [metabase.server.middleware.auth$wrap_api_key$fn__71301 invoke "auth.clj" 30]
  [ring.middleware.cookies$wrap_cookies$fn__92735 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__36679 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__36704 invoke "misc.clj" 76]
  [ring.middleware.gzip$wrap_gzip$fn__92777 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__36707 invoke "misc.clj" 93]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__92564 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__85173 invoke "server.clj" 73]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 181]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 487]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 732]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 479]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 277]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 338]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 315]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 173]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 131]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 409]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 883]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1034]
  [java.lang.Thread run nil -1]],
 :cause "Parameter \"f5d17ab6\" does not have any Fields associated with it",
 :data
 {:param
  {:name "Text 2",
   :slug "text_2",
   :id "f5d17ab6",
   :type :string/=,
   :sectionId "string",
   :mappings
   #{{:parameter_id "f5d17ab6",
      :card_id 12,
      :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]],
      :dashcard
      {:size_x 4,
       :action_id nil,
       :collection_authority_level nil,
       :card
       {:description nil,
        :archived false,
        :collection_position 2,
        :table_id nil,
        :result_metadata
        ({:display_name "ID",
          :semantic_type :type/PK,
          :field_ref [:field "ID" {:base-type :type/BigInteger}],
          :name "ID",
          :base_type :type/BigInteger,
          :effective_type :type/BigInteger,
          :fingerprint nil}
         {:display_name "EAN",
          :field_ref [:field "EAN" {:base-type :type/Text}],
          :name "EAN",
          :base_type :type/Text,
          :effective_type :type/Text,
          :semantic_type nil,
          :fingerprint
          {:global {:distinct-count 200, :nil% 0.0},
           :type
           {:type/Text
            {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 13.0}}}}
         {:display_name "TITLE",
          :semantic_type :type/Title,
          :field_ref [:field "TITLE" {:base-type :type/Text}],
          :name "TITLE",
          :base_type :type/Text,
          :effective_type :type/Text,
          :fingerprint
          {:global {:distinct-count 199, :nil% 0.0},
           :type
           {:type/Text
            {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.495}}}}
         {:description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
          :semantic_type :type/Category,
          :name "CATEGORY",
          :field_ref [:field "CATEGORY" {:base-type :type/Text}],
          :effective_type :type/Text,
          :id 63,
          :visibility_type :normal,
          :display_name "Category",
          :fingerprint
          {:global {:distinct-count 4, :nil% 0.0},
           :type
           {:type/Text
            {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
          :base_type :type/Text}
         {:display_name "VENDOR",
          :semantic_type :type/Company,
          :field_ref [:field "VENDOR" {:base-type :type/Text}],
          :name "VENDOR",
          :base_type :type/Text,
          :effective_type :type/Text,
          :fingerprint
          {:global {:distinct-count 200, :nil% 0.0},
           :type
           {:type/Text
            {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}}}
         {:display_name "PRICE",
          :field_ref [:field "PRICE" {:base-type :type/Float}],
          :name "PRICE",
          :base_type :type/Float,
          :effective_type :type/Float,
          :semantic_type nil,
          :fingerprint
          {:global {:distinct-count 170, :nil% 0.0},
           :type
           {:type/Number
            {:min 15.691943673970439,
             :q1 37.25154462926434,
             :q3 75.45898071609447,
             :max 98.81933684368194,
             :sd 21.711481557852057,
             :avg 55.74639966792074}}}}
         {:display_name "RATING",
          :semantic_type :type/Score,
          :field_ref [:field "RATING" {:base-type :type/Float}],
          :name "RATING",
          :base_type :type/Float,
          :effective_type :type/Float,
          :fingerprint
          {:global {:distinct-count 23, :nil% 0.0},
           :type
           {:type/Number
            {:min 0.0, :q1 3.5120465053408525, :q3 4.216124969497314, :max 5.0, :sd 1.3605488657451452, :avg 3.4715}}}}
         {:display_name "CREATED_AT",
          :semantic_type :type/CreationTimestamp,
          :field_ref [:field "CREATED_AT" {:base-type :type/DateTime}],
          :name "CREATED_AT",
          :base_type :type/DateTime,
          :effective_type :type/DateTime,
          :fingerprint
          {:global {:distinct-count 200, :nil% 0.0},
           :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147Z", :latest "2019-04-15T13:34:19.931Z"}}}}),
        :database_id 1,
        :enable_embedding false,
        :collection_id nil,
        :query_type :native,
        :name "products_model",
        :creator_id 1,
        :updated_at #t "2023-02-08T12:28:02.188319Z",
        :made_public_by_id nil,
        :embedding_params nil,
        :cache_ttl nil,
        :dataset_query {:type :native, :native {:query "Select * from products", :template-tags {}}, :database 1},
        :id 12,
        :parameter_mappings [],
        :display :table,
        :entity_id "6YukSvXZYQ2XjIvpWK0yN",
        :collection_preview true,
        :visualization_settings {:table.pivot_column "CATEGORY", :table.cell_column "ID"},
        :is_write false,
        :parameters [],
        :dataset true,
        :created_at #t "2023-02-08T12:07:09.994967Z",
        :public_uuid nil},
       :updated_at #t "2023-02-08T12:28:06.435645Z",
       :col 7,
       :id 9,
       :parameter_mappings
       [{:parameter_id "f5d17ab6", :card_id 12, :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]]}],
       :card_id 12,
       :entity_id "e0OH1kMW17EwGUo8evYEI",
       :visualization_settings {},
       :size_y 3,
       :dashboard_id 2,
       :created_at #t "2023-02-08T12:27:44.627410Z",
       :row 0}}}},
  :status-code 400},
 :message "Parameter \"f5d17ab6\" does not have any Fields associated with it",
 :param
 {:name "Text 2",
  :slug "text_2",
  :id "f5d17ab6",
  :type :string/=,
  :sectionId "string",
  :mappings
  #{{:parameter_id "f5d17ab6",
     :card_id 12,
     :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]],
     :dashcard
     {:size_x 4,
      :action_id nil,
      :collection_authority_level nil,
      :card
      {:description nil,
       :archived false,
       :collection_position 2,
       :table_id nil,
       :result_metadata
       ({:display_name "ID",
         :semantic_type :type/PK,
         :field_ref [:field "ID" {:base-type :type/BigInteger}],
         :name "ID",
         :base_type :type/BigInteger,
         :effective_type :type/BigInteger,
         :fingerprint nil}
        {:display_name "EAN",
         :field_ref [:field "EAN" {:base-type :type/Text}],
         :name "EAN",
         :base_type :type/Text,
         :effective_type :type/Text,
         :semantic_type nil,
         :fingerprint
         {:global {:distinct-count 200, :nil% 0.0},
          :type
          {:type/Text
           {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 13.0}}}}
        {:display_name "TITLE",
         :semantic_type :type/Title,
         :field_ref [:field "TITLE" {:base-type :type/Text}],
         :name "TITLE",
         :base_type :type/Text,
         :effective_type :type/Text,
         :fingerprint
         {:global {:distinct-count 199, :nil% 0.0},
          :type
          {:type/Text
           {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 21.495}}}}
        {:description "The type of product, valid values include: Doohicky, Gadget, Gizmo and Widget",
         :semantic_type :type/Category,
         :name "CATEGORY",
         :field_ref [:field "CATEGORY" {:base-type :type/Text}],
         :effective_type :type/Text,
         :id 63,
         :visibility_type :normal,
         :display_name "Category",
         :fingerprint
         {:global {:distinct-count 4, :nil% 0.0},
          :type
          {:type/Text
           {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 6.375}}},
         :base_type :type/Text}
        {:display_name "VENDOR",
         :semantic_type :type/Company,
         :field_ref [:field "VENDOR" {:base-type :type/Text}],
         :name "VENDOR",
         :base_type :type/Text,
         :effective_type :type/Text,
         :fingerprint
         {:global {:distinct-count 200, :nil% 0.0},
          :type
          {:type/Text
           {:percent-json 0.0, :percent-url 0.0, :percent-email 0.0, :percent-state 0.0, :average-length 20.6}}}}
        {:display_name "PRICE",
         :field_ref [:field "PRICE" {:base-type :type/Float}],
         :name "PRICE",
         :base_type :type/Float,
         :effective_type :type/Float,
         :semantic_type nil,
         :fingerprint
         {:global {:distinct-count 170, :nil% 0.0},
          :type
          {:type/Number
           {:min 15.691943673970439,
            :q1 37.25154462926434,
            :q3 75.45898071609447,
            :max 98.81933684368194,
            :sd 21.711481557852057,
            :avg 55.74639966792074}}}}
        {:display_name "RATING",
         :semantic_type :type/Score,
         :field_ref [:field "RATING" {:base-type :type/Float}],
         :name "RATING",
         :base_type :type/Float,
         :effective_type :type/Float,
         :fingerprint
         {:global {:distinct-count 23, :nil% 0.0},
          :type
          {:type/Number
           {:min 0.0, :q1 3.5120465053408525, :q3 4.216124969497314, :max 5.0, :sd 1.3605488657451452, :avg 3.4715}}}}
        {:display_name "CREATED_AT",
         :semantic_type :type/CreationTimestamp,
         :field_ref [:field "CREATED_AT" {:base-type :type/DateTime}],
         :name "CREATED_AT",
         :base_type :type/DateTime,
         :effective_type :type/DateTime,
         :fingerprint
         {:global {:distinct-count 200, :nil% 0.0},
          :type {:type/DateTime {:earliest "2016-04-26T19:29:55.147Z", :latest "2019-04-15T13:34:19.931Z"}}}}),
       :database_id 1,
       :enable_embedding false,
       :collection_id nil,
       :query_type :native,
       :name "products_model",
       :creator_id 1,
       :updated_at #t "2023-02-08T12:28:02.188319Z",
       :made_public_by_id nil,
       :embedding_params nil,
       :cache_ttl nil,
       :dataset_query {:type :native, :native {:query "Select * from products", :template-tags {}}, :database 1},
       :id 12,
       :parameter_mappings [],
       :display :table,
       :entity_id "6YukSvXZYQ2XjIvpWK0yN",
       :collection_preview true,
       :visualization_settings {:table.pivot_column "CATEGORY", :table.cell_column "ID"},
       :is_write false,
       :parameters [],
       :dataset true,
       :created_at #t "2023-02-08T12:07:09.994967Z",
       :public_uuid nil},
      :updated_at #t "2023-02-08T12:28:06.435645Z",
      :col 7,
      :id 9,
      :parameter_mappings
      [{:parameter_id "f5d17ab6", :card_id 12, :target [:dimension [:field "CATEGORY" {:base-type :type/Text}]]}],
      :card_id 12,
      :entity_id "e0OH1kMW17EwGUo8evYEI",
      :visualization_settings {},
      :size_y 3,
      :dashboard_id 2,
      :created_at #t "2023-02-08T12:27:44.627410Z",
      :row 0}}}}}
```

</details>

**To Reproduce**
1. Go to New -> Native Query -> Sample Database -> `Select * from products` -> Save -> Turn into a Model
2. Click on Edit Metadata -> Category -> Map to Product Category -> Column type Category -> Save
image

3. you will notice that you are able to see a dropdown if you try to filter directly from the model result (make sure to refresh after save)
image

4. Go to New Dashboard -> Add the above Model -> Add Dropdown Text Filter -> Link filter with column Category -> Notice no dropdown list is visible (there is an error in the logs as well, attached to this ticket)
image

**Expected behavior**
A drop down list appears since it works for GUI based questions

**Information about your Metabase Installation:**

Able to replicate on both 45.2.1 and `master`

### PR DESCRIPTION
**Pull request by markbastian**
Fixes #28145

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28274)

### CODE REVIEW

File: src/metabase/api/dashboard.clj [hunk 1]
```diff
@@ -683,11 +683,21 @@
...
-             :let  [field-id (mbql.u/match-one field-clause [:field (id :guard integer?) _] id)]
+             :let  [{:keys [result_metadata]} card
+                    field-id (or
+                              ;; Get the field id from the field-clause if it contains it. This is the common case for
+                              ;; mbql queries.
+                              (mbql.u/match-one field-clause [:field (id :guard integer?) _] id)
+                              ;; Attempt to get the field clause from the model metadata corresponding to the field.
+                              ;; This is the common case for native queries in which mappings from original columns
+                              ;; have been performed using model metadata.
+                              (some
```
Comment (qnkhuat) [inline src/metabase/api/dashboard.clj:697]: to find field in a result_metadata, I suggest using `metabase.query_processor.util/field->field-info`

It's a helper function I wrote to deal with the fact that `field-clause !== field_ref` in some special case.

If you're interested in a long discussion about this, here is the slack thread:[link](https://metaboat.slack.com/archives/CKZEMT1MJ/p1671721589099509)

File: test/metabase/api/dashboard_test.clj [hunk 2]
```diff
@@ -1992,6 +1992,56 @@
...
+                                                            :sectionId "string"}]}]
+                        DashboardCard [_dashcard {:parameter_mappings
+                                                  [{:parameter_id "_NATIVE_CATEGORY_NAME_"
+                                                    :card_id      question-id
+                                                    :target       [:dimension
+                                                                   [:field "CATEGORY" {:base-type :type/Text}]]}]
+                                                  :card_id      question-id
+                                                  :dashboard_id (:id dashboard)}]]
+          (let [url (format "dashboard/%d/params/%s/values" (u/the-id dashboard) "_NATIVE_CATEGORY_NAME_")]
+            (is (= {:values          ["Doohickey"
```
Comment (qnkhuat) [inline test/metabase/api/dashboard_test.clj:2038]:
```suggestion
            (is (=? {:values          ["Doohickey"
```

super nitty, but I think we should start using this, otherwise every time we update the param values endpoint, we have to update all the tests.

**Review by qnkhuat — APPROVED** [review]
nice
