### PR TITLE
Don't reload dashcards that have unmapped filters

### LINKED ISSUE #3339: Dashboard filter not attached to a card still causing the card to be reloaded
Reproduction steps
1. Create a "count of rows by time" for the users table
2. Create a "count of rows by time" for the orders table
3. Add both to a dashboard
4. Create a category filter and wire it to the orders by time card
5. Save the changes
6. Pick a category from the drop down

The users by time card is not greyed out.

This is on MB OS X Version 0.19.3

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3339

### CODE REVIEW

File: frontend/src/metabase/dashboard/dashboard.js [hunk 1]
```diff
@@ -150,26 +146,49 @@ export const fetchCardData = createThunkAction(FETCH_CARD_DATA, function(card, d
...
-        let { dashboardId } = getState().dashboard;
-        let { dashboards, parameterValues } = getState().dashboard;
+        const datasetQuery = applyParameters(card, dashboard.parameters, parameterValues, dashcard && dashcard.parameter_mappings);
 
-        let dashboard = dashboards[dashboardId];
+        if (!reload) {
+            // if reload not set, check to see if the last result has the same query dict and return that
+            const lastResult = i.getIn(dashcardData, [dashcard.id, card.id]);
+            // "constraints" is added by the backend, remove it when comparing
+            if (lastResult && angular.equals(_.omit(lastResult.json_query, "constraints"), datasetQuery)) {
```
Comment (kdoh) [inline frontend/src/metabase/dashboard/dashboard.js]: `angular.equals` O.o seems like there should be a way to determine equivalent values without using an angular function.

**Review by kdoh — COMMENTED** [review]
Other than the use of angular.equals this LGTM.
