### PR TITLE
Fix bad parameterized i18n template strings on FE

### LINKED ISSUE #15561: localization - placeholder displayed instead of the actual string
Metabase version 575714b

Snímek obrazovky 2021-04-12 v 0 22 29

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #15561

In #15189 I converted our old untested node/bash scripts that generated i18n resources to Clojure ones with tests. For the frontend resources the new scripts were outputting parameterized singular strings incorrectly, like `Número de {0}` (unmodified from the source PO files) as opposed to `Número de ${ 0 }` (the format expected by the ttag library we use on the frontend). It was an easy fix, since we were already converting the `{0}` style references to `${ 0 }` ones elsewhere -- we just had to use that code in this spot as well. I've added new tests for it this specific situation to make sure we don't run into a regression in the future.

Here's a screenshot of it working correctly after the fix. Note you'll have to rebuild the translation resources and restart the server (or just reload the `metabase.server.routes.index` namespace if you're running from a REPL) to see the fixed behavior:

image

### CODE REVIEW

File: bin/i18n/src/i18n/create_artifacts/frontend.clj [hunk 1]
```diff
@@ -29,7 +29,7 @@
                      (if (:plural? message)
                        {:msgid_plural (:id-plural message)
                         :msgstr       (:str-plural message)}
-                       {:msgstr [(:str message)]})])))
```
Comment (camsaul) [inline bin/i18n/src/i18n/create_artifacts/frontend.clj:32]: this line was the actual fix, the rest of this PR is just additional tests

File: bin/i18n/src/i18n/create_artifacts/frontend.clj [hunk 2]
```diff
@@ -29,7 +29,7 @@
...
+                       {:msgstr [(->ttag-reference (:str message))]})])))
             messages)})
```
Comment (camsaul) [inline bin/i18n/src/i18n/create_artifacts/frontend.clj:33]: this line was the actual fix, the rest of this PR is just additional tests

**Review by flamber — COMMENTED** [review]
Something isn't working. It's not translating anything now. I'm testing Spanish, French and German, and neither the frontend or logs are translated - it works on rc2 (besides parameterized)

When I change language it throws this in the log:
`2021-04-13 21:36:04,997 WARN routes.index :: Locale 'es' not found.`

**Comment by flamber** [comment]
@camsaul I'm using the builds from CI - it seems like we're not building translations, so I guess this might have fixed it, but I cannot test. I normally use builds from GitHub, since they have faster downloads, but they're only available on master repo.

**Comment by camsaul** [comment]
@flamber I'll build you an uberjar, give me a second

**Comment by camsaul** [comment]
@flamber here ya go https://s3.amazonaws.com/downloads.metabase.com/v0.39.0-i18n-fix/metabase.jar

**Review by flamber — APPROVED** [review]
@camsaul Thank you! :heart:
