### PR TITLE
Fix parameter tags reordering in the presence of snippet tags

### LINKED ISSUE #69160: Reordering native filter widgets is unreliable when variables are inside a snippet
### Describe the bug

When dashboard or query filters are defined as part of a SQL snippet, the filters cannot be reliably reordered via drag-and-drop. 

Dragging one filter over another often fails, making it difficult to change their order. This issue does not occur when the same filters are defined directly (not via a snippet).

### To Reproduce

1. Create two snippets: `{{ a }}, {{ b }}` and `{{ c }}, {{ d }}` 
2. Reference them in a question: `select {{ snippet:a and b }}, {{ snippet: c and d}}` 
3. Try to reorder the widgets - some movements won't be possible, for example try to replace **a** and **b**:
- drag **a** over **b** --> not possible, **a** snaps back to its original position
- drag **b** over **a** --> works

### Expected behavior

Reordering via dragging should always work.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "bigquery-cloud-sdk",
      "h2",
      "clickhouse"
    ],
    "run-mode": "prod",
    "plan-alias": "internal",
    "version": {
      "date": "2026-02-04",
      "tag": "v1.58.5",
      "hash": "109161b"
    },
    "settings": {
      "report-timezone": "Australia/Melbourne"
    },
    "hosting-env": "unknown",
    "application-database": "postgres"
  }
}
```

### Severity

Customer reported. There is no reliable workaround. 

### Additional context

Can be reproduced on v57 as well.

### PR DESCRIPTION
**Pull request by romeovs**
Closes #69160 

The reordering of native parameters is broken when the query contains snippets because the snippets are in the parameter tag list but their indexes are not being disregarded when reordering the parameter tags.

This is fixed by disregarding the snippet tags when reordering parameters and then tacking them back on at the end.

### CODE REVIEW

File: frontend/src/metabase-lib/v1/queries/NativeQuery.ts [hunk 1]
```diff
@@ -235,12 +235,22 @@ export default class NativeQuery {
     // template tags, and the order is determined by the key order
     const query = this._query();
     const tags = this.templateTags();
-    const oldIndex = tags.findIndex((tag) => tag.id === id);
 
-    const newTags = [...tags];
+    // NOTE: The snippet tags are part of the snippet tags map, but they do
+    // not appear in the parameter lists. To correctly reorder the parameters
+    // and keep track of indexes, we need to pluck out the snippet tags first.
+    // We then tack them on before returning the reorder tags map.
```
Comment (kamilmielnik) [inline frontend/src/metabase-lib/v1/queries/NativeQuery.ts]:
```suggestion
    // We then tack them on before returning the reordered tags map.
```

**Review by kamilmielnik — APPROVED** [review]
