### PR TITLE
fix(sdk): Use modal instead of hacky form for saving questions

### LINKED ISSUE #47346: Improve appearance of the save question modal for sdk's CreateQuestion component
- We should make the save question modal a full-screen modal, similar to the current behaviour of the entity picker modal. The reason is that the current save question modal is dependent on the content's height, and looks jarring against a white background because of the modal backdrop. See the screenshots below.
- We should update the modal to follow the `background` theme colors. The white background does not work well in dark themes. [Private Loom.](https://www.loom.com/share/0db0a79b98de4902b6aa768156589284?sid=707e95e9-2bb5-4921-aded-ebc4be932eb7)

Image

Image

### PR DESCRIPTION
**Pull request by oisincoveney**
Fixes https://github.com/metabase/metabase/issues/47346

Uses a modal for saving questions instead of the weird overlay form that was being used in the `QuestionEditor`

### CODE REVIEW

File: frontend/src/metabase/components/SaveQuestionForm/SaveQuestionForm.tsx [hunk 1]
```diff
@@ -7,16 +7,20 @@ import FormErrorMessage from "metabase/core/components/FormErrorMessage";
...
 import CS from "metabase/css/core/index.css";
-import { Form } from "metabase/forms";
+import { Form, FormSubmitButton } from "metabase/forms";
 import { DEFAULT_MODAL_Z_INDEX } from "metabase/ui";
 
 import { useSaveQuestionContext } from "./context";
-import type { SaveQuestionFormProps } from "./types";
 
-export const SaveQuestionForm = ({ onCancel }: SaveQuestionFormProps) => {
+export const SaveQuestionForm = ({
```
Comment (oisincoveney) [inline frontend/src/metabase/components/SaveQuestionForm/SaveQuestionForm.tsx:17]: this enables us to close the modal on save

File: frontend/src/metabase/components/SaveQuestionForm/context.tsx [hunk 2]
```diff
@@ -30,6 +30,23 @@ type SaveQuestionContextType = {
 export const SaveQuestionContext =
   createContext<SaveQuestionContextType | null>(null);
 
+/*
```
Comment (oisincoveney) [inline frontend/src/metabase/components/SaveQuestionForm/context.tsx:33]: I figured it out!

File: frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx [hunk 3]
```diff
@@ -27,7 +25,7 @@ export const SaveQuestionModal = ({
     multiStep={multiStep}
     initialCollectionId={initialCollectionId}
   >
-    <Modal.Root onClose={onCancel} opened={true} padding="40px">
+    <Modal.Root padding="2.5rem" {...modalProps}>
```
Comment (oisincoveney) [inline frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx:28]: I've moved the logic for the modal props to each iteration of `SaveQuestionModal`. In an ideal world I hope we can use the modal in a proper way rather than having to use `opened=true` for all of it

File: frontend/src/metabase/ui/utils/colors.ts [hunk 4]
```diff
@@ -59,3 +59,8 @@ export function getThemeColors(): Record<string, ColorShades> {
     ),
   };
 }
+
+export type MantineColor =
```
Comment (oisincoveney) [inline frontend/src/metabase/ui/utils/colors.ts:63]: I couldn't find a type that worked (there is the `MantineColors` type that's included with Mantine but it's just a straight-up `string` which isn't helpful for auto-complete)

File: frontend/src/metabase/query_builder/components/QueryModals/QueryModals.tsx
Comment (oisincoveney) [inline frontend/src/metabase/query_builder/components/QueryModals/QueryModals.tsx:1]: This change might be a little controversial, but this is the `QueryModals` component which controls the modals in the QueryBuilder, so imo the logic that controls whether a modal is opened or closed should be in this component as well

File: frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx [hunk 5]
```diff
@@ -37,6 +39,12 @@ export const FormSubmitButton = forwardRef(function FormSubmitButton(
   });
   const submitColor = getSubmitButtonColor(status, { color });
 
+  useEffect(() => {
```
Comment (oisincoveney) [inline frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx:42]: this triggers the `success` state that allows us to close the modal when the question is saved

File: frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx [hunk 6]
```diff
@@ -55,7 +63,7 @@ type SubmitButtonColorOpts = Pick<FormSubmitButtonProps, "color">;
 const getSubmitButtonColor = (
   status: FormStatus | undefined,
   { color }: SubmitButtonColorOpts,
-) => {
+): MantineColor | undefined => {
```
Comment (WiNloSt) [inline frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx:66]: Why do we need to type color here? If we don't have this change I assume we also don't need to introduce the color type `MantineColor`.

After removing the type here, `yarn type-check` still passed locally.

Comment (oisincoveney) [reply frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx:66]: there was a good reason I had this here, but now I can't remember. I'll remove it

File: frontend/src/metabase/components/SaveQuestionForm/context.tsx [hunk 7]
```diff
@@ -30,6 +30,23 @@ type SaveQuestionContextType = {
...
+ * we calculate isSavedQuestionInitiallyChanged, the question and originalQuestion are different, so the form works as
+ * it should.
+ *
+ * When we use the Modal's props to control the modal itself (i.e. no outside component controlling
+ * the modal), the question and originalQuestion are the same when they are passed in to the provider
+ * so isSavedQuestionInitiallyChanged will calculate to false and then *never* change because it's saved
+ * as a state variable. This means that, to use this provider, we have to make sure that the question
+ * and the original question are different *at the time of the Provider rendering*.
+ *
+ * Thanks for coming to my TED talk.
```
Comment (heypoom) [inline frontend/src/metabase/components/SaveQuestionForm/context.tsx:48]: I saw the above comment on `Refer to the SaveQuestionProvider for context on why we have to do it like this` and I had a hunch that it has to do with the `isSavedQuestionInitiallyChanged` thing, haha. I just had a look at our existing `SaveQuestionForm` component, and that is definitely more complicated that I would've anticipated 😅

File: frontend/src/metabase/query_builder/components/QueryModals/QueryModals.tsx [hunk 8]
```diff
@@ -214,7 +217,8 @@ export function QueryModals({
           originalQuestion={originalQuestion}
           onSave={handleSaveAndClose}
           onCreate={handleCreateAndClose}
-          onCancel={onCloseModal}
+          onClose={onCloseModal}
+          opened={true}
```
Comment (heypoom) [inline frontend/src/metabase/query_builder/components/QueryModals/QueryModals.tsx:221]: Just curious, will we ever have any uses of this component where the `opened` prop would ever be `false`?

**Review by heypoom — APPROVED** [review]
Yay for full-screen modals! The `SaveQuestionForm` component is a doozy.

File: enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx [hunk 9]
```diff
@@ -64,12 +71,16 @@ const QuestionEditorInner = () => {
         </Tabs.Panel>
       </Tabs>
 
-      {isSaveEnabled && isSaveFormOpen && (
-        <Overlay center>
-          <Paper>
-            <InteractiveQuestion.SaveQuestionForm onClose={closeSaveForm} />
-          </Paper>
-        </Overlay>
+      {/* Refer to the SaveQuestionProvider for context on why we have to do it like this */}
```
Comment (npretto) [inline enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx:74]: I read the comment but I still haven't understood what we're doing, why, and what was the problem 😅

File: frontend/src/metabase/query_builder/components/QueryModals/QueryModals.tsx (hunk 8 above)
Comment (oisincoveney) [reply frontend/src/metabase/query_builder/components/QueryModals/QueryModals.tsx:221]: exactly. I hope we end up in a world where we use the modal controls as they should be used rather than this current state, but for now here we are 😅

File: enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx (hunk 9 above)
Comment (oisincoveney) [reply enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx:74]: I've changed it a little bit so hopefully it's a little better explained

File: frontend/src/metabase/components/SaveQuestionForm/SaveQuestionForm.tsx [hunk 10]
```diff
@@ -61,9 +65,10 @@ export const SaveQuestionForm = ({ onCancel }: SaveQuestionFormProps) => {
         <FormErrorMessage inline />
         <Button type="button" onClick={onCancel}>{t`Cancel`}</Button>
         <FormSubmitButton
-          title={t`Save`}
+          label={t`Save`}
           data-testid="save-question-button"
-          primary
+          variant="filled"
+          onSuccess={onSaveSuccess}
```
[the remark this answers is not in the document]
Comment (oisincoveney) [reply frontend/src/metabase/components/SaveQuestionForm/SaveQuestionForm.tsx:71]: yes!

File: frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx (hunk 5 above)
Comment (oisincoveney) [reply frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx:42]: yeah, fair enough. that's a good call

Comment (oisincoveney) [reply frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx:42]: fixed. I moved the logic to the provider and the modal component itself

**Comment by oisincoveney** [comment]
@npretto I know you were having issues with this PR - I've made a few changes so let me know if it works for you now

File: frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx (hunk 5 above)
Comment (npretto) [reply frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx:42]: Did you forget to push?

File: frontend/src/metabase/components/SaveQuestionForm/context.tsx [hunk 11]
```diff
@@ -30,6 +30,23 @@ type SaveQuestionContextType = {
 export const SaveQuestionContext =
   createContext<SaveQuestionContextType | null>(null);
 
+/*
+ * Why are we using these useState calls?
+ *
+ * When we use SaveQuestionModal within the QueryModals, the 'opened' prop on the modal
```
Comment (npretto) [inline frontend/src/metabase/components/SaveQuestionForm/context.tsx:36]: I see opened={true} on every usage though, not only on QueryModals?

File: enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx (hunk 9 above)
Comment (npretto) [reply enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx:75]: I still don't understand what we mean by "we have to do it like this" 😅
When a modal uses an entity, i think it's fairly normal to only render it when needed instead of using `open={flag}`

File: frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx (hunk 5 above)
Comment (oisincoveney) [reply frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx:42]: Yes I did 🙃

File: frontend/src/metabase/components/SaveQuestionForm/context.tsx (hunk 11 above)
Comment (oisincoveney) [reply frontend/src/metabase/components/SaveQuestionForm/context.tsx:36]: Just trying to give context for why we had to do this in the first place

Comment (npretto) [reply frontend/src/metabase/components/SaveQuestionForm/context.tsx:36]: I see, I thought this was related to the PR i found in git blame where you split the files and (it think?) introduced the context, but I see all the things that confuse me were there even before that 😅

Comment (oisincoveney) [reply frontend/src/metabase/components/SaveQuestionForm/context.tsx:36]: ah yeah the context was never the problem 😅
