### PR TITLE
move subtext to command palette item generation. Support model-indexes

### LINKED ISSUE #44136: Indexed Entities lack visual context in command palette
### Describe the bug

image

The indexed entities in the command palette lack visual information

Contrast with 49's search results:
image

and the full page results
image

### To Reproduce

on a 50 or master version, create a model on Products, edit it's metadata and create an index on the title

image

Then use command palette to search for some of the products ("rustic" is a great search term)

### Expected behavior

Some visual indicator that these are _rows_ in a model rather than just tables or cards themselves.

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

p3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npfitz**
Closes https://github.com/metabase/metabase/issues/44136

### Description
Adds subtext to search results in the command palette that are indexed entities. Also re-arranges some logic into util files for (hopefully) easier testing

### How to verify

Describe the steps to verify that the changes are working as expected.

1.  Ensure that you have an indexed model (see issue for steps)
2. Type a search query
3. You should see subtext of `a model in ${x}`

### Demo
image

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by mazameli — DISMISSED** [review]
This is looking great. One mistake that I don't want to repeat here though is that I'm realizing we probably want to include the schema name in front of the table for DBs that have > 1 schema. We could use the same string structure that we're planning on using in the command palette, so it would be I think something like `a record in SomeSchema / Customers`

**Review by mazameli — COMMENTED** [review]
I think the string could be improved to `a record in the Products model` or even better, `a record in {model icon} {Model name}`, like this:

image

4px in between "a record in" and the icon, and 2px in between the icon and the model's name, text in `text-medium`, icon in `text-light`

File: frontend/src/metabase/palette/components/PaletteResultItem.tsx [hunk 1]
```diff
@@ -81,15 +80,18 @@ export const PaletteResultItem = ({ item, active }: PaletteResultItemProps) => {
...
             <Text
               component="span"
               ml="0.25rem"
               c={active ? color("brand-light") : color("text-light")}
               fz="0.75rem"
               lh="1rem"
               fw="normal"
-            >{`— ${parentName}`}</Text>
+            >
+              {`—`}
```
Comment (rafpaf) [inline frontend/src/metabase/palette/components/PaletteResultItem.tsx:92]: Should there be a space here?

File: frontend/src/metabase/palette/hooks/useCommandPalette.tsx [hunk 2]
```diff
@@ -242,22 +244,15 @@ export const useCommandPalette = ({
...
-                      : item.parent_collection.name,
-                  isVerified: item.moderated_status === "verified",
-                  href: Urls.modelToUrl(item),
-                  iconColor: icon.color,
-                },
+          extra: {
+            isVerified:
+              item.model === "table"
+                ? false
+                : item.moderated_status === "verified",
```
Comment (rafpaf) [inline frontend/src/metabase/palette/hooks/useCommandPalette.tsx:251]: nit: for readability maybe do:

```suggestion
              item.model !== "table" && item.moderated_status === "verified",
```

File: frontend/src/metabase/palette/hooks/useCommandPalette.tsx [hunk 3]
```diff
@@ -301,3 +296,36 @@ export const useCommandPalette = ({
...
+export const getSearchResultSubtext = (wrappedSearchResult: any) => {
+  if (wrappedSearchResult.model === "indexed-entity") {
+    return (
+      <>
+        {t`a record in`}{" "}
+        <Icon
+          name="model"
+          style={{
+            verticalAlign: "bottom",
+            marginLeft: "0.25rem",
```
Comment (rafpaf) [inline frontend/src/metabase/palette/hooks/useCommandPalette.tsx:309]:
```suggestion
            marginInlineStart: "0.25rem",
```

File: frontend/src/metabase/palette/hooks/useCommandPalette.tsx [hunk 4]
```diff
@@ -301,3 +296,36 @@ export const useCommandPalette = ({
     [adminActions, adminSettingsActions, hasQuery],
   );
 };
+
+export const getSearchResultSubtext = (wrappedSearchResult: any) => {
+  if (wrappedSearchResult.model === "indexed-entity") {
+    return (
+      <>
+        {t`a record in`}{" "}
```
Comment (rafpaf) [inline frontend/src/metabase/palette/hooks/useCommandPalette.tsx:304]: For better-quality translations you could translate the whole phrase using `jt`, maybe like this:

```ts
jt`a record in ${(
  <>
    <Icon />
    {wrappedSearchResult.model_name}
  </>
)}`;
```

Then this can be translated correctly in languages where the name of the model would not appear at the end of the phrase. (According to ChatGPT, these languages include Japanese, Korean, and Turkish)

To help the translators more you could do something like this:

```ts
c("{0} is the name of the model in which the record appears").jt`a record in ${(
  <>
    <Icon />
    {wrappedSearchResult.model_name}
  </>
)}`;

File: frontend/src/metabase/palette/types.ts [hunk 5]
```diff
@@ -5,19 +5,17 @@ import type { IconName } from "metabase/ui";
...
     /** isVerified: If true, will show a verified badge next to the item name */
     isVerified?: boolean;
-    /** database: Name of the database to show next the name in the palette item. */
-    database?: string | null;
     /**
      * href: If defined, the palette item will be wrapped in a link. This allows for
      * browser interactions to open items in new tabs/windows
      */
     href?: LocationDescriptor | null;
     /** iconColor: Color of the icon in the  */
```
Comment (rafpaf) [inline frontend/src/metabase/palette/types.ts:15]: This isn't part of the diff but I noticed something was missing in this comment, worth throwing in a fix?

File: frontend/src/metabase/palette/types.ts [hunk 6]
```diff
@@ -5,19 +5,17 @@ import type { IconName } from "metabase/ui";
...
     iconColor?: string;
+    /**subtext: text to come after the item name */
```
Comment (rafpaf) [inline frontend/src/metabase/palette/types.ts:17]: nit: Not sure there's any need to repeat the variable name in jsdoc comments

**Review by rafpaf — CHANGES_REQUESTED** [review]
Looks good. Pretty close to mergeable.

Something worth looking into, I think: When I search for `products`, which appears in the subtext of the Reviews table, the name "Reviews" appears in uppercase - but the same item uses title case when I find it by searching for `reviews`

image

image

**Review by rafpaf — APPROVED** [review]

**Comment by dhuniverse** [comment]
Looks good. Approved.
