### PR TITLE
Throw an error if a setting already exists

### LINKED ISSUE #15000: defsetting macro throw an Exception if you try to define a setting that's already defined in a different namespace
It's a bug if two different places try to use the same setting name for two different things. We can catch bugs at compile time using the `defsetting` macro, so we should

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes #15000

```clojure
setting-test=> (defsetting site-name (deferred-tru "A testing setting") :visibility :public)
Execution error (ExceptionInfo) at metabase.models.setting/register-setting! (setting.clj:464).
Setting :site-name already registered in metabase.public-settings
setting-test=> (pprint (ex-data *e))
{:existing-setting
 {:description "The name used for this instance of Metabase.",
  :cache? true,
  :default "Metabase",
  :name :site-name,
  :type :string,
  :sensitive? false,
  :tag java.lang.String,
  :namespace metabase.public-settings,
  :visibility :admin}}
nil
```

### CODE REVIEW

File: test/metabase/models/setting_test.clj [hunk 1]
```diff
@@ -513,3 +513,31 @@
...
+(deftest duplicated-setting-name
+  (testing "can re-register a setting in the same ns (redefining or reloading ns)"
+    (is (defsetting foo (deferred-tru "A testing setting") :visibility :public))
+    (is (defsetting foo (deferred-tru "A testing setting") :visibility :public)))
+  (testing "if attempt to register in a different ns throws an error"
+    (let [current-ns (ns-name *ns*)]
+      (try
+        (ns nested-setting-test
+          (:require [metabase.models.setting :refer [defsetting]]
+                    [metabase.util.i18n :as i18n :refer [deferred-tru]]))
```
Comment (camsaul) [inline test/metabase/models/setting_test.clj:527]: Can't you just bind `*ns*` here? It seems a little funky putting an `ns` declaration inside a test

File: src/metabase/models/setting.clj [hunk 2]
```diff
@@ -441,10 +442,11 @@
 (defn register-setting!
   "Register a new Setting with a map of `SettingDefinition` attributes. Returns the map it was passed. This is used
   internally be `defsetting`; you shouldn't need to use it yourself."
-  [{setting-name :name, setting-type :type, default :default, :as setting}]
+  [{setting-name :name, setting-type :type, default :default, :as setting} namespace-sym]
```
Comment (camsaul) [inline src/metabase/models/setting.clj:445]: Why not just make namespace symb another map argument? It seems a little weird to have a big options map as arg 1 and then a plain symbol arg as the second arg

**Review by camsaul — APPROVED** [review]
A couple style questions but besides that it LGTM

File: test/metabase/models/setting_test.clj (hunk 1 above)
Comment (dpsutton) [reply test/metabase/models/setting_test.clj:527]: The test needs another namespace, and the most reliable way to do that is to create and be in the namespace. I'm not sure if i can just bind `*ns*`. I know changing namespaces changes that binding but I honestly don't know if binding that dynamic var is sufficient to "be in" another ns. I suppose i could do `(in-ns 'nested-setting-test)` but then i'd need to require everything i need (including clojure) and that's what the `ns` form does anyways.

File: src/metabase/models/setting.clj (hunk 2 above)
Comment (dpsutton) [reply src/metabase/models/setting.clj:445]: I left it as a separate arg as its not really part of the setting but more an annotation but i can add it back in.
