### PR TITLE
Fix combined tooltip for charts

### LINKED ISSUE #16249: Tooltip of combined dashboard cards does not show the correct column title
**Describe the bug**
When combining two cards on a dashboard, and changing the series name on the dashboard, then it shows the first series name in the tooltip for both series. When using CE, then it doesn't change the name for the second series.
Continuation of #11395, but for dashboard combined cards. Regression since 0.38.3.

Note for developers: Any reason why the tooltip is only showing values for a single question, when combined? Normally with multi-series, it would show all the series values, but perhaps this is a limitation, when combining.

**To Reproduce**
1. Create 4 questions - Custom question > Sample Dataset
   1. Orders - summarize CE `Sum(Total)` called `CE` group by CreatedAt:Year - save as "Q1"
   2. Orders - summarize CE `Average(Subtotal)` called `CE` group by CreatedAt:Year - save as "Q2"
   3. Orders - summarize "Sum of Total" group by CreatedAt:Year - save as "Q3"
   4. Products - summarize "Sum of Price" group by CreatedAt:Year - save as "Q4"
2. On a dashboard. CE-test:
   1. Add "Q1"
   2. Hover the "Q1" card and click "Add series" and add "Q2"
   3. Hover the combined Q1+Q2 card and click "Visualization options"
   4. Change the names of the series to something unique for each series
3. Hover the lines of the Q1+Q2 card
image
4. Do the same as step 2 again, but using Q3 and Q4 instead of Q1 and Q2
5. Hover the lines of the Q3+Q4 card
image

**Information about your Metabase Installation:**
Tested 0.38.2 thru 0.39.2 and commit `0401256` (almost 0.39.3) - regression since 0.38.3

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/16249

How to test:
- Follow the steps from the issue or
- Run the unskipped cy test

The original issue comes from this line https://github.com/metabase/metabase/blob/dd6f0cc45346b2d8ad49cb9fc34acfddac68bb01/frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx#L543 Basically all `visualization_settings.series_settings` use `card.name` and not `column.key` for renamed series when the `seriesIndex > 0`. Because of backward compatibility issues, we cannot change `_seriesKey` but have to get the correct column name for the tooltip by mirroring this logic. We also need to check for `columnIndex === 1` because only the first metric column should be renamed by this setting.

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/apply_tooltips.js [hunk 1]
```diff
@@ -32,11 +32,13 @@ export function getClickHoverObject(
   const isBar = classList.includes("bar");
   const isSingleSeriesBar = isBar && !isMultiseries;
 
-  function getColumnDisplayName(col) {
-    const title = getIn(settings, ["series_settings", col.name, "title"]);
+  function getColumnDisplayName(col, colIndex, card) {
+    const colKey = seriesIndex > 0 && colIndex === 1 ? card.name : col.name;
```
Comment (daltojohnso) [inline frontend/src/metabase/visualizations/lib/apply_tooltips.js:36]: I think this line warrants a comment above it to explain why we need to do this

Comment (ranquild) [reply frontend/src/metabase/visualizations/lib/apply_tooltips.js:40]: Agree, added a comment

**Review by daltojohnso — APPROVED** [review]
