### PR TITLE
fix: bigquery handle local date params as date

### LINKED ISSUE #30602: BigQuery Connection issue with Date Parameter
### Describe the bug

When using DATE parameter in BigQuery connection, Metabase automatically adds timezone as REPORT TIMEZONE (we chose Asia/Saigon), so with BigQuery DATE default function convert it to UTC and it is not correct date for end users.
Example: 
current_date: 08 May 2023 18:00:00
DATE filter: 08-05-2023
BigQuery query: select {{date}}, DATE({{date}}), DATE({{date}}, 'Asia/Saigon')
=> the result: 
May 8, 2023, 00:00
May 7, 2023
May 8, 2023

Note: metabase version v0.46.1

Attachment files: 
image

### To Reproduce

When using DATE parameter in BigQuery connection, Metabase automatically adds timezone as REPORT TIMEZONE (we chose Asia/Saigon), so with BigQuery DATE default function convert it to UTC and it is not correct date for end users.
Example: 
current_date: 08 May 2023 18:00:00
DATE filter: 08-05-2023
BigQuery query: select {{date}}, DATE({{date}}), DATE({{date}}, 'Asia/Saigon')
=> the result: 
May 8, 2023, 00:00
May 7, 2023
May 8, 2023

Note: metabase version v0.46.1

Attachment files: 
image

### Expected behavior

Correct date with config timezone. We did not see this issue in older version (v0.43.4)

### Logs

_No response_

### Information about your Metabase installation

```JSON
- Chrome
- MacOS
- BigQuery connection
- Metabase version v0.46.1
- Metabase hosting env: Docker container in Ubuntu server
- Metabase internal database: Postgresql
```

### Severity

Blocking users when using parameter with BigQuery connection

### Additional context

Please review and fix it asap, thank you  <3

### PR DESCRIPTION
**Pull request by snoe**
Fixes #30602

We were overriding localdate in bigquery driver to produce offsetdatetimes for no apparent reason. This causes a number of problems when dealing with date type columns.

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj [hunk 1]
```diff
@@ -984,11 +983,6 @@
   [_driver]
   :mysql)
 
-;; convert LocalDate to an OffsetDateTime in UTC since BigQuery doesn't handle LocalDates as we'd like
-(defmethod driver.sql/->prepared-substitution [:bigquery-cloud-sdk LocalDate]
-  [driver t]
-  (driver.sql/->prepared-substitution driver (t/offset-date-time t (t/local-time 0) (t/zone-offset 0))))
-
```
Comment (lbrdnk) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:991]: Yeah, the comment is not super clear on why. I assume it could be due to potentially comparing date against the DateTime columns. As the other tests are passing I _believe_ this is not the case anymore.

**Review by lbrdnk — APPROVED** [review]
LGTM, please see my comment prior to merging.
