### PR TITLE
Remove stack traces from `SQLException`s

### LINKED ISSUE #53539: SQL errors on Databricks return a full stack trace
### Describe the bug

When SQL queries return errors on Databricks, we are showing the full stack trace in the UI

Image

### To Reproduce

1. Go to Databricks db > Native query
2. Write any non-conforming query
3. See stacktrace

### Expected behavior

We should show only the error message and omit the stacktrace. As we do with all other drivers.

### Logs

_No response_

### Information about your Metabase installation

```JSON
53
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rileythomp**
Closes https://github.com/metabase/metabase/issues/53539

### Description

Some JDBC drivers (e.g. Databricks) return stack traces in their `SQLException`s, which are not very readable when displayed on the FE. This PR removes those stacktraces if they are in the error message.

### How to verify

1. Run an invalid query like `select bad;` on a Databricks DB.
2. An error message with no stack trace should be displayed

### Demo

https://github.com/user-attachments/assets/3295e830-30a6-4632-9a2b-1123dafbaf9b

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/query_processor/middleware/catch_exceptions.clj [hunk 1]
```diff
@@ -64,7 +65,9 @@
   [maps :- [:sequential {:min 1} :map]]
   (some (fn [m]
           (when (isa? (:class m) SQLException)
-            (select-keys m [:error])))
+            ;; Some JDBC drivers (e.g. Databricks) return a stacktrace in the
+            ;; error message that we don't want to show the user
+            {:error (first (str/split (get m :error "") #"\n\tat"))}))
```
Comment (rileythomp) [inline src/metabase/query_processor/middleware/catch_exceptions.clj:70]: Should we do an `includes?` check first to avoid splitting on the regex unnecessarily?

File: src/metabase/query_processor/middleware/catch_exceptions.clj [hunk 2]
```diff
@@ -64,7 +65,9 @@
   [maps :- [:sequential {:min 1} :map]]
   (some (fn [m]
           (when (isa? (:class m) SQLException)
-            (select-keys m [:error])))
+            ;; Some JDBC drivers (e.g. Databricks) return a stacktrace in the
+            ;; error message that we don't want to show the user
+            {:error (first (str/split (get m :error "") #"\n\tat "))}))
```
Comment (rileythomp) [inline src/metabase/query_processor/middleware/catch_exceptions.clj:70]: Should we do an `includes?` check first to avoid splitting on the regex unnecessarily?

**Review by snoe — APPROVED** [review]
