### PR TITLE
fix(sdk): non-editable dashboard should not have "add a chart" button and title should be read-only

### LINKED ISSUE #65001: [SDK] InteractiveDashboard on empty dashboards renders "Add a chart" button and has editable title
### Describe the bug

When using the InteractiveDashboard component (not EditableDashboard) on an empty dashboard, we still show the "Add a chart" button and the "Click on the edit button" hint text when the dashboard is empty. It actually enters the edit mode when "Add a chart" is clicked on despite being a read-only dashboard component.

In addition, the title is editable.

Image

### To Reproduce

See description

### Expected behavior

*No response*

### Logs

*No response*

### Information about your Metabase installation

```JSON
Latest SDK
```

### Severity

Ugly but low impact, because usually you would not embed a dashboard that is empty

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by heypoom**
Closes EMB-922
Closes #65001

The InteractiveDashboard and StaticDashboard SDK components should not show the "Add a chart" button on its empty state, and the dashboard title should not be editable as it is supposed to be a purely read-only component.

### How to verify

- Log in as an admin or a user with edit permission. I suggest using Storybook to test.
- Create an empty dashboard.
- Render an EditableDashboard with the latest id. You can search and modify `function generateIds` to change `numberId: 1` to point to your empty dashboard ID.
- You should be able to edit the title and see the "Add a chart" button
- Render an StaticDashboard or InteractiveDashboard
- You should **not** be able to edit the title and **not** see the "Add a chart" button

### Demo

After: EditableDashboard remains editable, but InteractiveDashboard and StaticDashboard is no longer editable.

https://github.com/user-attachments/assets/0f429c02-d752-4d69-b882-47df1fef3be3

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/tests/setup.tsx [hunk 1]
```diff
@@ -212,7 +219,14 @@ export const setupSdkDashboard = async ({
   );
 
   if (!isLocaleLoading) {
-    expect(await screen.findByTestId("dashboard-grid")).toBeInTheDocument();
+    if (dashcards.length === 0) {
+      // For empty dashboards, wait for the empty state instead of the grid
+      expect(
+        await screen.findByTestId("dashboard-empty-state"),
+      ).toBeInTheDocument();
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/tests/setup.tsx:226]: When testing `dashcards: []`, there is no dashboard grid because there is no dashcard. It will render an empty state in that case.

File: enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.unit.spec.tsx [hunk 2]
```diff
@@ -131,4 +131,17 @@ describe("InteractiveDashboard", () => {
       dashboardHeader.queryByTestId("dashboard-header-row-button"),
     ).not.toBeInTheDocument();
   });
+
+  it("should not show 'Add a chart' button on empty dashboards", async () => {
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.unit.spec.tsx:135]: This is inverted from the EditableDashboard test above. Note the "not" in front of each test.

File: frontend/src/metabase/dashboard/components/Dashboard/components/Grid.tsx [hunk 3]
```diff
@@ -30,9 +30,11 @@ export const Grid = ({
     onRefreshPeriodChange,
     isLoadingWithoutCards,
     onAddQuestion,
+    hasEditAction,
   } = useDashboardContext();
 
-  const canWrite = Boolean(dashboard?.can_write);
+  const isDashboardEditable = hasEditAction && Boolean(dashboard?.can_write);
```
Comment (heypoom) [inline frontend/src/metabase/dashboard/components/Dashboard/components/Grid.tsx]: We consider a dashboard to be editable if there is an edit action (`EDIT_DASHBOARD`)

File: frontend/src/metabase/dashboard/context/context.tsx [hunk 4]
```diff
@@ -80,6 +80,9 @@ export type DashboardContextOwnProps = {
 export type DashboardContextOwnResult = {
   dashboardId: DashboardId | null;
   dashboardActions?: DashboardActionButtonList;
+
+  /** Does the dashboard has an `edit` dashboard action? */
+  hasEditAction: boolean;
```
Comment (heypoom) [inline frontend/src/metabase/dashboard/context/context.tsx]: I could've named this `isEditable`, but that can be confused with `dashboard.can_write`, so saying that it has an "Edit" action is more explicit.

I don't want to add an `editable` flag to the public interface, so using dashboard actions seems to be a good enough heuristic.

File: frontend/src/metabase/dashboard/context/context.tsx [hunk 5]
```diff
@@ -348,6 +351,14 @@ const DashboardContextProviderInner = forwardRef(
         ? initDashboardActions({ isEditing, downloadsEnabled })
         : (initDashboardActions ?? null);
 
+    // Determine if the dashboard is editable based on the dashboard actions.
+    // This lets us distinguish read-only dashboards (e.g. public embeds, InteractiveDashboard)
+    // from editable dashboards (e.g. main app, EditableDashboard).
+    const hasEditAction = useMemo(
+      () => dashboardActions?.includes("EDIT_DASHBOARD") ?? false,
```
Comment (WiNloSt) [inline frontend/src/metabase/dashboard/context/context.tsx]: I feel like the below version reads a bit better, but your mileage may vary.

```suggestion
      () => (dashboardActions ?? []).includes("EDIT_DASHBOARD"),
```

This new version feels like I only need to read from left to right without having to backtrack. The original is like, ok return if the actions include something, but if it returns null, that means we don't have dashboard actions, then return false.

IDK, it just feels like the new version could flow better.

**Review by WiNloSt — APPROVED** [review]
Tested. Works great. It could be great if you add tests for dashboard with cards, but a tab doesn't have one.

Image
