### PR TITLE
Select fields with parent-ids and hide parents by default

### LINKED ISSUE #47146: Querying :all fields on tables with nested (json) fields return only non-nested fields while the UI shows all fields.
### Describe the bug

`:all` fields on tables with nested fields is expected to work like this:
- show all nested fields
- hide the top-level parsed fields

This was reproduced on Mongo and BigQuery (that we are working on now) https://github.com/metabase/metabase/pull/47106

### To Reproduce

1. Browse data > Table with nested fieds (like [this](https://stats.metabase.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxNjYsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NTIyMjh9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319))
2. It shows that all fields are selected, but nested fields are not in the query

### Expected behavior

image

In this case, it should hide the `Host` and `Address` field and expand all nested fields in the query.
At the very least, the UI should be consistent with the generated query.

Unselecting a single field makes the query consistent with the UI.

### Logs

_No response_

### Information about your Metabase installation

```JSON
- v50.20
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wzimrin**
Closes https://github.com/metabase/metabase/issues/47146

### Description

In postgres, json fields are hidden by default, and we just show their children instead.  However, mongo fields and bigquery struct fields work differently -- we default to just showing the parent, even though the ui claims that all fields are selected.  This makes mongo and bigquery work like postgres.

In addition, this fixes a presumably-longstanding bug where mongo had incorrect column names when selecting both a parent and its child.  Basically, you can't ask mongo for both a parent and its child.  The returned data is just json, so asking for the parent field includes all of its children.  Instead, mongo just errors when you try to make a request like that.  As a workaround, the mongo driver was just requesting and returning the child fields.  This meant that it was returning a different number of fields than expected, which confused annotate.

Now, the mongo query processor only selects for parent fields, because as mentioned, parent fields include their children.  However, it also keeps track of all the fields we asked for in :projections, so when we get data back, we know to pull all of those fields out of the returned data.

### How to verify

1. Sync your mongo or bigquery db
2. Make a mongo or bigquery query against a table with child cols
3. Verify that you got the child cols back in the query, while the parent col is hidden by default
4. With mongo, verify that the col labels are correct

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 1]
```diff
@@ -318,9 +318,10 @@
                                         nested-fields (get-in nested-column-lookup [(:table-name col) new-path])]
                                     (cond-> (assoc col :database-position root-database-position)
                                       (and (= :type/Dictionary (:base-type col)) nested-fields)
-                                      (assoc :nested-fields (into #{}
-                                                                  (map #(maybe-add-nested-fields % new-path root-database-position))
-                                                                  nested-fields)))))
+                                      (-> (assoc :nested-fields (into #{}
+                                                                      (map #(maybe-add-nested-fields % new-path root-database-position))
+                                                                      nested-fields))
+                                          (assoc :visibility-type :details-only)))))
```
Comment (bshepherdson) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj]: Prefer multiple key-value pairs in one `assoc`:

```suggestion
                                      (assoc :nested-fields (into #{}
                                                                      (map #(maybe-add-nested-fields % new-path root-database-position))
                                                                      nested-fields))
                                             :visibility-type :details-only))))
```

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 2]
```diff
@@ -1468,10 +1488,14 @@
...
-    (let [new-projections (for [field (remove-parent-fields fields)]
+    (let [new-projections (for [field (remove-child-fields fields)]
                             [(field-alias field) (->rvalue field)])]
       (-> pipeline-ctx
-          (assoc :projections (map first new-projections))
+          ;; we can't ask mongo for both a parent field and its child at the same time, because mongo will throw an
+          ;; error. It's also unnecessary, because the parent includes the child. However, we need to list all fields
+          ;; we think we want in :projections so that we know to look for them all once we get data back.
+          (assoc :projections (for [field fields]
+                                (field-alias field)))
```
Comment (bshepherdson) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj]:
```suggestion
          (assoc :projections (map field-alias fields))
```

**Review by bshepherdson — APPROVED** [review]
