### PR TITLE
Fix redirect URI validation for relative paths

### LINKED ISSUE #33028: Invalid redirect URL when doing JWT SSO
### Describe the bug

After upgrading to 1.46.7 JWT SSO no longer works. It looks like https://github.com/metabase/metabase/issues/32816 broke the documented flow for JWT SSO auth.

### To Reproduce

Make a JWT SSO auth request as per the docs: https://www.metabase.com/docs/latest/people-and-groups/authenticating-with-jwt#typical-flow-for-a-jwt-based-sso-interaction-with-metabase, specifically the line `In the event of a successful sign-in, your authentication app should issue a GET request to your Metabase endpoint with the token and the “return to” URI: http://localhost:3000/auth/sso?jwt=TOKEN_GOES_HERE&return_to=/question/1-superb-question.`

ie:
* a query parameter of 'jwt' with a valid JWT
* a query parameter of 'return_to' with something like '/collection/2'

Observe a 400 response with Invalid redirect URL.

### Expected behavior

It should perform an SSO login

### Logs
```
{
	"via": [
		{
			"type": "clojure.lang.ExceptionInfo",
			"message": "Invalid redirect URL",
			"data": {
				"status-code": 400,
				"redirect-url": "/collection/2-re-staging"
			},
			"at": [
				"metabase_enterprise.sso.integrations.sso_utils$check_sso_redirect",
				"invokeStatic",
				"sso_utils.clj",
				65
			]
		}
	],
	"trace": [
		[
			"metabase_enterprise.sso.integrations.sso_utils$check_sso_redirect",
			"invokeStatic",
			"sso_utils.clj",
			65
		],
		[
			"metabase_enterprise.sso.integrations.sso_utils$check_sso_redirect",
			"invoke",
			"sso_utils.clj",
			55
		],
		[
			"metabase_enterprise.sso.integrations.jwt$login_jwt_user",
			"invokeStatic",
			"jwt.clj",
			79
		],
		[
			"metabase_enterprise.sso.integrations.jwt$login_jwt_user",
			"invoke",
			"jwt.clj",
			76
		],
		[
			"metabase_enterprise.sso.integrations.jwt$fn__101322",
			"invokeStatic",
			"jwt.clj",
			104
		],
		[
			"metabase_enterprise.sso.integrations.jwt$fn__101322",
			"invoke",
			"jwt.clj",
			100
		],
		[
			"clojure.lang.MultiFn",
			"invoke",
			"MultiFn.java",
			229
		],
		[
			"metabase_enterprise.sso.api.sso$fn__101333$fn__101334",
			"invoke",
			"sso.clj",
			35
		],
		[
			"metabase_enterprise.sso.api.sso$fn__101333",
			"invokeStatic",
			"sso.clj",
			34
		],
		[
			"metabase_enterprise.sso.api.sso$fn__101333",
			"invoke",
			"sso.clj",
			30
		],
		[
			"compojure.core$wrap_response$fn__42432",
			"invoke",
			"core.clj",
			160
		],
		[
			"compojure.core$wrap_route_middleware$fn__42416",
			"invoke",
			"core.clj",
			132
		],
		[
			"compojure.core$wrap_route_info$fn__42421",
			"invoke",
			"core.clj",
			139
		],
		[
			"compojure.core$wrap_route_matches$fn__42425",
			"invoke",
			"core.clj",
			151
		],
		[
			"compojure.core$routes$fn__42444$f__42445",
			"invoke",
			"core.clj",
			198
		],
		[
			"compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446",
			"invoke",
			"core.clj",
			197
		],
		[
			"compojure.core$wrap_route_matches$fn__42425",
			"invoke",
			"core.clj",
			153
		],
		[
			"compojure.core$routes$fn__42444$f__42445",
			"invoke",
			"core.clj",
			198
		],
		[
			"compojure.core$routes$fn__42444",
			"invoke",
			"core.clj",
			200
		],
		[
			"compojure.core$routes$fn__42444$f__42445",
			"invoke",
			"core.clj",
			198
		],
		[
			"compojure.core$routes$fn__42444",
			"invoke",
			"core.clj",
			200
		],
		[
			"compojure.core$make_context$handler__42472",
			"invoke",
			"core.clj",
			290
		],
		[
			"compojure.core$make_context$fn__42476",
			"invoke",
			"core.clj",
			300
		],
		[
			"compojure.core$routes$fn__42444$f__42445",
			"invoke",
			"core.clj",
			198
		],
		[
			"compojure.core$routes$fn__42444",
			"invoke",
			"core.clj",
			200
		],
		[
			"compojure.core$routes$fn__42444$f__42445",
			"invoke",
			"core.clj",
			198
		],
		[
			"compojure.core$routes$fn__42444",
			"invoke",
			"core.clj",
			200
		],
		[
			"compojure.core$make_context$handler__42472",
			"invoke",
			"core.clj",
			290
		],
		[
			"compojure.core$make_context$fn__42476",
			"invoke",
			"core.clj",
			300
		],
		[
			"compojure.core$routes$fn__42444$f__42445",
			"invoke",
			"core.clj",
			198
		],
		[
			"compojure.core$routes$fn__42444",
			"invoke",
			"core.clj",
			200
		],
		[
			"compojure.core$routes$fn__42444$f__42445",
			"invoke",
			"core.clj",
			198
		],
		[
			"compojure.core$routes$fn__42444",
			"invoke",
			"core.clj",
			200
		],
		[
			"metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__96459",
			"invoke",
			"exceptions.clj",
			103
		],
		[
			"metabase.server.middleware.exceptions$catch_api_exceptions$fn__96456",
			"invoke",
			"exceptions.clj",
			91
		],
		[
			"metabase.server.middleware.log$log_api_call$fn__103115",
			"invoke",
			"log.clj",
			205
		],
		[
			"metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__109567",
			"invoke",
			"browser_cookie.clj",
			42
		],
		[
			"metabase.server.middleware.security$add_security_headers$fn__80396",
			"invoke",
			"security.clj",
			153
		],
		[
			"metabase.server.middleware.json$wrap_json_body$fn__106819",
			"invoke",
			"json.clj",
			69
		],
		[
			"metabase.server.middleware.offset_paging$handle_paging$fn__80420",
			"invoke",
			"offset_paging.clj",
			45
		],
		[
			"metabase.server.middleware.json$wrap_streamed_json_response$fn__106837",
			"invoke",
			"json.clj",
			103
		],
		[
			"ring.middleware.keyword_params$wrap_keyword_params$fn__109834",
			"invoke",
			"keyword_params.clj",
			55
		],
		[
			"ring.middleware.params$wrap_params$fn__109853",
			"invoke",
			"params.clj",
			77
		],
		[
			"metabase.server.middleware.misc$maybe_set_site_url$fn__50568",
			"invoke",
			"misc.clj",
			61
		],
		[
			"metabase.server.middleware.session$reset_session_timeout$fn__63848",
			"invoke",
			"session.clj",
			441
		],
		[
			"metabase.server.middleware.session$bind_current_user$fn__63817$fn__63818",
			"invoke",
			"session.clj",
			336
		],
		[
			"metabase.server.middleware.session$do_with_current_user",
			"invokeStatic",
			"session.clj",
			315
		],
		[
			"metabase.server.middleware.session$do_with_current_user",
			"invoke",
			"session.clj",
			304
		],
		[
			"metabase.server.middleware.session$bind_current_user$fn__63817",
			"invoke",
			"session.clj",
			335
		],
		[
			"metabase.server.middleware.session$wrap_current_user_info$fn__63798",
			"invoke",
			"session.clj",
			285
		],
		[
			"metabase.server.middleware.session$wrap_session_id$fn__63781",
			"invoke",
			"session.clj",
			217
		],
		[
			"metabase.server.middleware.auth$wrap_api_key$fn__87854",
			"invoke",
			"auth.clj",
			30
		],
		[
			"ring.middleware.cookies$wrap_cookies$fn__109754",
			"invoke",
			"cookies.clj",
			216
		],
		[
			"metabase.server.middleware.misc$add_content_type$fn__50550",
			"invoke",
			"misc.clj",
			29
		],
		[
			"metabase.server.middleware.misc$disable_streaming_buffering$fn__50576",
			"invoke",
			"misc.clj",
			78
		],
		[
			"ring.middleware.gzip$wrap_gzip$fn__109796",
			"invoke",
			"gzip.clj",
			86
		],
		[
			"metabase.server.middleware.misc$bind_request$fn__50579",
			"invoke",
			"misc.clj",
			95
		],
		[
			"metabase.server.middleware.ssl$redirect_to_https_middleware$fn__109583",
			"invoke",
			"ssl.clj",
			51
		],
		[
			"metabase.server$async_proxy_handler$fn__101881",
			"invoke",
			"server.clj",
			77
		],
		[
			"metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a",
			"handle",
			null,
			-1
		],
		[
			"org.eclipse.jetty.server.handler.StatisticsHandler",
			"handle",
			"StatisticsHandler.java",
			173
		],
		[
			"org.eclipse.jetty.server.handler.HandlerWrapper",
			"handle",
			"HandlerWrapper.java",
			122
		],
		[
			"org.eclipse.jetty.server.Server",
			"handle",
			"Server.java",
			563
		],
		[
			"org.eclipse.jetty.server.HttpChannel",
			"lambda$handle$0",
			"HttpChannel.java",
			505
		],
		[
			"org.eclipse.jetty.server.HttpChannel",
			"dispatch",
			"HttpChannel.java",
			762
		],
		[
			"org.eclipse.jetty.server.HttpChannel",
			"handle",
			"HttpChannel.java",
			497
		],
		[
			"org.eclipse.jetty.server.HttpConnection",
			"onFillable",
			"HttpConnection.java",
			282
		],
		[
			"org.eclipse.jetty.io.AbstractConnection$ReadCallback",
			"succeeded",
			"AbstractConnection.java",
			314
		],
		[
			"org.eclipse.jetty.io.FillInterest",
			"fillable",
			"FillInterest.java",
			100
		],
		[
			"org.eclipse.jetty.io.SelectableChannelEndPoint$1",
			"run",
			"SelectableChannelEndPoint.java",
			53
		],
		[
			"org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
			"runTask",
			"AdaptiveExecutionStrategy.java",
			416
		],
		[
			"org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
			"consumeTask",
			"AdaptiveExecutionStrategy.java",
			385
		],
		[
			"org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
			"tryProduce",
			"AdaptiveExecutionStrategy.java",
			272
		],
		[
			"org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy",
			"lambda$new$0",
			"AdaptiveExecutionStrategy.java",
			140
		],
		[
			"org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread",
			"run",
			"ReservedThreadExecutor.java",
			411
		],
		[
			"org.eclipse.jetty.util.thread.QueuedThreadPool",
			"runJob",
			"QueuedThreadPool.java",
			936
		],
		[
			"org.eclipse.jetty.util.thread.QueuedThreadPool$Runner",
			"run",
			"QueuedThreadPool.java",
			1080
		],
		[
			"java.lang.Thread",
			"run",
			null,
			-1
		]
	],
	"cause": "Invalid redirect URL",
	"data": {
		"status-code": 400,
		"redirect-url": "/collection/2-re-staging"
	},
	"message": "Invalid redirect URL",
	"redirect-url": "/collection/2-re-staging"
}
```
### Information about your Metabase installation

```JSON
Note that this is after I downgraded it in order to work around the bug.

{
  "browser-info": {
    "language": "en-NZ",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.10.184-175.749.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v1.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking an upgrade

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
https://github.com/metabase/metabase/issues/32816 fixed the issue with open redirects but broke it for relative paths since `(.getHost (URI. "/"))` is `nil` 🤦. JWT tests didn't catch this since they were only using a full URL for the redirect, not a relative URL, but the default behavior in Metabase is to redirect to `/` so I've changed the tests to use that, and added a unit test for the validation function.

Resolves https://github.com/metabase/metabase/issues/33028

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/sso/integrations/sso_utils_test.clj [hunk 1]
```diff
@@ -0,0 +1,17 @@
+(ns metabase-enterprise.sso.integrations.sso-utils-test
+  (:require [clojure.test :refer :all]
+            [metabase-enterprise.sso.integrations.sso-utils :as sso-utils]))
+
+(deftest check-sso-redirect-test
```
Comment (camsaul) [inline enterprise/backend/test/metabase_enterprise/sso/integrations/sso_utils_test.clj:5]:
```suggestion
(deftest ^:parallel check-sso-redirect-test
```

**Review by camsaul — APPROVED** [review]
