### PR TITLE
Fix notebook performance issue

### LINKED ISSUE #12378: Notebook Editor becomes very slow (or freezes browser), when there is a lot of fields/sections
**Describe the bug**
When opening the editor, the panel slides weirdly and verrrrry slowly.

**To Reproduce**
1. Go to any saved question
2. Click to open it
3. Click to show the editor

**Expected behavior**
well...the panel should just slide down, right? 

**Screenshots**

https://user-images.githubusercontent.com/1447303/131403586-0cae1a36-03c0-41ac-9beb-10446f5f4f1f.mp4

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko)",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+9-202002041938",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+9-202002041938",
    "os.name": "Mac OS X",
    "os.version": "10.15.2",
    "user.language": "en",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "osx",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-21",
      "tag": "v0.35.3",
      "branch": "release-0.35.x",
      "hash": "1d424cb"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### LINKED ISSUE #33676: Performance regression in how we parse query_metadata response leads to notebook being unusable
### Describe the bug

We introduced a regression in the query_metadata, possibly because of several factors, that lead questions with lots of Metadata to slow down heavily the frontend (Pro tip: use the table metadata and generate a large lorem ipsum on the fields and tables descriptions to make a heavy response along with a "big" question with lots of stages and fields. remember we call the table_metadata for every linked table on a query, so if table 1 has a FK to table 2, we fetch both tables metadata)

Performance in 46:
image

Profiler
image
image

Now let's move to 47:
look at the separation between calls (sizes of responses stayed the same)
image

profiler:
2X
image

This will get amplified as more tables are joined in the data model

### To Reproduce

1) go to the data model and try to join a single table to all others. Also try to complete as much metadata as possible
2) then create a GUI question and add that single table, build a question with lots of aggregations, fields, etc
3) compare it between 46 and 47, see the difference in rendering

### Expected behavior

UI should be F A S T

### Logs

NA

### Information about your Metabase installation

```JSON
v47
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/12378
Fixes https://github.com/metabase/metabase/issues/33676

Based on the profiler, we had 2 different issues:
- Rendering "not yet opened" popovers, which called Mlv2 functions
- `BreakoutStep` did per-clause calculation even outside of the opened popover

This PR fixes the issues:
- `Triggerable` won't render the wrapped component if it's not "opened"
- Per-clause calculation happens in `BreakoutPopover` now

How to verify:
- New -> Question -> Orders
- Join with Products and Reviews
- Add 10+ summarize and breakout clauses
- Toggle notebook mode with and without changes in this PR. Compare the performance.

Screenshot 2023-09-08 at 15 41 44

Screenshot 2023-09-08 at 14 57 25

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.tsx [hunk 1]
```diff
@@ -28,39 +28,17 @@ function BreakoutStep({
...
-    columnInfo: Lib.ColumnDisplayInfo,
-    breakoutIndex?: number,
-  ) => {
-    return (
-      typeof breakoutIndex === "number" &&
-      columnInfo.breakoutPosition === breakoutIndex
-    );
-  };
-
-  const getColumnGroups = (breakoutIndex?: number) => {
```
Comment (ranquild) [inline frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.tsx:43]: Heavy calculations, moved to the popover to make sure they run already when it's opened

**Review by deniskaber — APPROVED** [review]

**Comment by paoliniluis** [comment]
@ranquild do we create another issue for the rest of the regressions so you can create specific PR's for those? let me know

**Comment by renatodossantosleal** [comment]
Hi! We're still suffering with this issue as the UI becomes really slow after adding 2 simple custom columns and 10+ summarized fields at the visual builder.

Every new aggregation/summarization makes the UI painfully slower, that happens specially after clicking the done.
Has this been released? I'm in version 0.47.8

Trace below:
[Trace-20231208T181503.zip](https://github.com/metabase/metabase/files/13621168/Trace-20231208T181503.zip)
