### PR TITLE
Closes VIZ-1318 - Visualize in another way uses the Card Definition rather than the Dashboard Card

### LINKED ISSUE #61072: Visualize in another way uses the Card Definition rather than the Dashboard Card
### Describe the bug

So the visualizer loads the question and not the dashboard question. This becomes problematic if you're using SQL questions and passing filters

### To Reproduce

1. Go to New Question -> Sample Database -> Add Text Filter with Title -> Checkout the [question here](https://stats.metabase.com/question/27359-test?title_=):
```
SELECT *
FROM
  "PUBLIC"."PRODUCTS"
WHERE "PUBLIC"."PRODUCTS"."TITLE" = {{title_}}
LIMIT
  1048575
```
This will fail cause you're required to pass a filter but that's fine cause we will be passing one from the dashboard

Image

2. Add this to a dashboard -> Link Text Filter to it and pass a Value -> Checkout [Dashboard here](https://stats.metabase.com/dashboard/3600-test?text=Rustic+Paper+Wallet)

Image

3. Now if you go to visualize in another way:

Image

You get no results with no indication what is wrong. The problem is that the Visualizer is loading the Question which doesn't have a filter passed to it and it should load the question on the dashboard with the dashboard filter

### Expected behavior

It works and loads the question that I am trying to visualize from the dashboard ... Or to the very least gives you an indication of what is wrong and why you get No Results

### Logs

None the are relevant

### Information about your Metabase installation

```JSON
master
```

### Severity

Very Annoying if you don't know what is going on

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bpander**
Closes https://github.com/metabase/metabase/issues/61072
Closes VIZ-1318

### Description

Updates behavior of "Visualize another way" for sql questions with parameters to avoid cases where a missing parameters yields invalid sql.

### How to verify

See #61072 for repro steps.

### Demo

**BEFORE**

🐛 SQL questions with variables could never be visualized another way because dashboard parameters aren't pulled into the visualizer so the SQL is never valid and thus never returns results.

https://github.com/user-attachments/assets/3c39bea2-4098-41b0-bb3b-b9a126296ecb

**AFTER**

The workaround was to pull in dashboard parameters ONLY for this case to make the query successful and thus allow some data to be visualized.

https://github.com/user-attachments/assets/00ea4a0a-5e29-436f-a1f8-d45f1c2707e2

Non-parameterized questions aren't affected.

https://github.com/user-attachments/assets/1f45871d-1f30-45b6-806e-e901303bb36a

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx [hunk 1]
```diff
@@ -311,18 +315,23 @@ function DashCardInner({
...
 
     if (isVisualizerDashboardCard(dashcard)) {
-      initialState = getInitialStateForVisualizerCard(dashcard, datasets);
+      initialState = getInitialStateForVisualizerCard(
+        dashcard,
+        datasets,
+        getParametersForDashcard(store.getState(), dashcard),
+      );
     } else if (series.length > 1) {
       initialState = getInitialStateForMultipleSeries(series);
```
Comment (bpander) [inline frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx]: ❓ Does anyone know if SQL questions can be added here too? I wasn't able to figure out a way to combine SQL questions together in the visualizer, but maybe I was just doing it wrong.

File: frontend/src/metabase/dashboard/selectors.ts [hunk 2]
```diff
@@ -741,3 +742,22 @@ export const getCanResetFilters = createSelector(
...
 );
+
+export const getParametersForDashcard = createSelector(
+  [
+    getDashboard,
+    getParameterValues,
+    (_: State, dashcard: DashboardCard) => dashcard,
+  ],
+  (dashboard, parameterValues, dashcard) => {
+    const parameters = dashcard.card?.parameters?.length
```
Comment (bpander) [inline frontend/src/metabase/dashboard/selectors.ts]: ❓ Is this condition sufficient? Will it ever trigger parameters to get added when we DON'T want them to?

**Review by alxnddr — COMMENTED** [review]
I'm getting a `Invalid parameter type :id for parameter \"id\". Parameter type must be one of: :category, :text, :string/=` error from `/api/card/852/query` — the request that should load data in the Visualizer: https://www.loom.com/share/6544b35442154c8caeb36f6e91097748?sid=1ec0ffae-13ea-4d1a-b7f3-847892d5d124

The question is `select * from orders where id ={{id}}` and dashboard parameter type is ID. Maybe there is some mapping logic needed? Alternatively, we could maybe pass the already loaded dataset with applied parameter from the dashboard instead of fetching it via `/api/card/:cardId/query` endpoint

File: frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx (hunk 1 above)
Comment (alxnddr) [reply frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx]: This behavior is coming from the previously existed "Add Series Modal" which has been replaced by the visualizer. On v54 you can combine two SQL questions with the same axis type, then upgrade to v55 and this condition will come into play

File: frontend/src/metabase/dashboard/selectors.ts (hunk 2 above)
Comment (alxnddr) [reply frontend/src/metabase/dashboard/selectors.ts]: I think this is fine, it should not

**Comment by bpander** [comment]
@alxnddr Good catch! Regarding "Maybe there is some mapping logic needed?", I'm not sure what other mapping could be applied there on the FE. Maybe I'm missing something?

I looked at the payload getting sent to `api/dashboard/:1/dashcard/:2/card/:3/query` on **dashboard load** and compared it with the payload getting sent to `api/card/:id/query` on **visualizer load**, and the parameters are the same.

I like the idea of passing the already loaded dataset. I'll start looking into that. That should handle the v54 multiple sql series case as well I think.

**Comment by bpander** [comment]
@alxnddr I changed the approach with this PR. Based on your suggestion, instead of trying to send parameters (which apparently doesn't work for ID parameters (unless you make it a text/category filter)), it passes the previously loaded datasets as fallbacks which it will use if a query fails.

It should also handle the v54 multiple sql series case:

https://github.com/user-attachments/assets/874d894b-3deb-47a7-a110-cad272432579

I noticed a lot of weirdness with cards set up that way on master, but at least with these changes, it'll use fallbacks if needed.

And here's it working with the original "title_" sql from the bug report and the "id" issue you found above:

https://github.com/user-attachments/assets/12e608a1-8774-4fb0-87c2-f1160672ea8d

**Review by alxnddr — APPROVED** [review]
Looks great 🏅
