### PR TITLE
Fix home page our analytics

### LINKED ISSUE #16784: The list of collections available on homepage "Our analytics" depends on the name of the first 50 objects
**Describe the bug**
The list of collections on the homepage section "Our analytics" will depend on the naming of the first 50 objects in root.

**To Reproduce**
1. Create 10 collections under root - named something like "C01", "C02", ...
2. Create 45 questions under root - named "A01", "A02", ...
3. Go to homepage - it will only list the first 5 collections. Example from one of my setups:
image

**Expected behavior**
Example from one of my setups with hundreds of questions in root - 0.39.4
image

**Information about your Metabase Installation:**
Tested master `c040f15` (2021-06-25)

### LINKED ISSUE #16869: The pinned items from the main collection are not showed on the front page anymore
**Describe the bug**
Items that were pinned in the "our analytics" collection (the top level one) used to appear on the top of the welcome page, which was really helpful to surface key dashboards for the whole company. After a recent update, they disappeared.

**Logs**
[not really relevant]

**To Reproduce**
1. Make sure that some items are pinned in your top-level collection
2. Go to the welcome page of your metabase instance
3. See that there is no pinned item that are presented on top

**Expected behavior**
Have the pinned items on the front page.

**Screenshots**
[not applicable]

**Information about your Metabase Installation:**

Below is our current instal, but the bug appeared when updating from 0.38.5 to 0.40.0 rc1

<details> <summary><strong> Details from troubleshooting page </strong></summary>
<p>

They seem surprisingly few - another small bug?

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36",
    "vendor": "Google Inc."
  }
}
```

</p>
</details>

**Severity**
This is "annoying". Mostly, it was very useful to have a way to surface results to the front page (which was the ~only feature of the front page, currently a bit lacking).

### PR DESCRIPTION
**Pull request by alxnddr**
#### Home page does not show all folders under `Our analytics` on the home page:
Screen Shot 2021-07-07 at 16 37 09

Reason: we added pagination `http://localhost:3000/api/collection/root/items` endpoint but previously it loaded all the items and filtered collections on the client-side. I replaced it with `http://localhost:3000/api/collection/root/items?models=collection` query to fetch only collections

#### Home page does not show pinned dashboards under `Start here` on the home page:
Screen Shot 2021-07-07 at 16 40 05

Reason: we added pagination to `http://localhost:3000/api/collection/root/items` endpoint but previously it loaded all the items and filtered pinned dashboards on the client-side. Now we can do this on the back end using new query params:
`http://localhost:3000/api/collection/root/items?models=dashboard&pinned_state=is_pinned&limit=200&sort_column=name&sort_direction=asc`

Fixes https://github.com/metabase/metabase/issues/16784
Fixes https://github.com/metabase/metabase/issues/16869

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/template_tags/TagEditorSidebar.jsx [hunk 1]
```diff
@@ -161,7 +161,7 @@ const SettingsPane = ({
 );
 
 SettingsPane.propTypes = {
-  tags: PropTypes.object.isRequired,
+  tags: PropTypes.array.isRequired,
```
Comment (alxnddr) [inline frontend/src/metabase/query_builder/components/template_tags/TagEditorSidebar.jsx:164]: Fixes console warning

File: frontend/src/metabase/entities/containers/EntityObjectLoader.jsx [hunk 2]
```diff
@@ -106,7 +106,7 @@ export default class EntityObjectLoader extends React.Component {
   UNSAFE_componentWillReceiveProps(nextProps: Props) {
     if (
       nextProps.entityId !== this.props.entityId &&
-      this.props.entityId != null
+      nextProps.entityId != null
```
Comment (alxnddr) [inline frontend/src/metabase/entities/containers/EntityObjectLoader.jsx:109]: Referring other questions using `{{#question_id}}` in the native query mode started failing because of this line which looks not correct. When we receive a new entityId which is not null we should fetch it. Before that, when users typed `{{#}}` and then for instance `{{#3}}` nextProps.entityId becomes `3` but `props.entityId` is null and this `if` state did not let fetch the new entity

File: frontend/src/metabase/containers/CollectionItemsLoader.jsx [hunk 3]
```diff
@@ -13,7 +13,14 @@ const CollectionItemsLoader = ({ collectionId, children, ...props }: Props) => (
...
       <Search.ListLoader
         {...props}
-        query={{ collection: collectionId }}
+        query={{
+          collection: collectionId,
+          pinned_state: "is_pinned",
+          sort_column: "name",
+          sort_direction: "asc",
+          models: "dashboard",
+          limit: 200,
```
Comment (alxnddr) [inline frontend/src/metabase/containers/CollectionItemsLoader.jsx:22]: @flamber @mazameli can you please share how many folders we can show on the home page under "Our analytics"?
Screen Shot 2021-07-07 at 16 29 05

Comment (alxnddr) [inline frontend/src/metabase/containers/CollectionItemsLoader.jsx:22]: @flamber @mazameli can you please share how pinned dashboards we can show on the home page under "Start here"?

Screen Shot 2021-07-07 at 16 31 14

Comment (alxnddr) [reply frontend/src/metabase/containers/CollectionItemsLoader.jsx:22]: The same question about the number of folders under "Our analytics"

Comment (kulyk) [reply frontend/src/metabase/containers/CollectionItemsLoader.jsx:22]: Worth to be a constant value in the top of a file I guess

**Review by kulyk — APPROVED** [review]
LGTM 👍

File: frontend/src/metabase/containers/CollectionItemsLoader.jsx (hunk 3 above)
Comment (mazameli) [reply frontend/src/metabase/containers/CollectionItemsLoader.jsx:22]: Huh, good question. I'll throw out some opinions, but I defer to @flamber here; he knows better than I do what our real customers' upper bounds might be.

But, my answer for both is, "display as many as we can before we expect we'll see performance degredation." 

It looks like you set it to 200 here for dashboards, which seems fine enough to me — I find it hard to picture a scenario where an instance will have 200 _pinned_ dashboards all in the root folder.

I can imagine a super large instance theoretically having hundreds of top-level folders, so I might bump the cap up to like 500 just to give ourselves ample breathing room, provided that that doesn't cause performance problems.

Comment (alxnddr) [reply frontend/src/metabase/containers/CollectionItemsLoader.jsx]: @mazameli I bumped it to 500 for now, thanks. Let's hear @flamber.
I assume it would not be convenient enough to have that many folders on the home page, however, this problem should be tackled in a different way

Comment (alxnddr) [reply frontend/src/metabase/containers/CollectionItemsLoader.jsx]: @mazameli @flamber @rlotun it seems the question about the limits of pinned dashboards and collections on the home page is not a blocker and this PR already fixes an important issue for the `0.40` release, so I'll merge it now. We will easily change limits later if we need it
