### PR TITLE
Removing FK->PK remapping hack

### LINKED ISSUE #53275: Dashboard parameter selection uses incorrect style on foreign keys
### Describe the bug

When you have a dashboard parameter hooked up to a foreign key, it seems to look at the original column in the other table instead of the foreign key column in the current table when deciding what sort of dropdown to show (plain text box vs list of values).

### To Reproduce

1. Set up "Filtering on this field" table metadata on the sample database such that orders.product_id uses "a list of all values" and products.id uses "plain input box"
2. Create dashboard with the question that is just "count orders"
3. Create id parameter and hook it up to orders.product_id
4. Save dashboard
5. Try to use the id parameter and see that it is using a plain input box

### Expected behavior

I would expect it to use a list of all values instead of a plain input box, given that orders.product_id was explicitly set to use that sort of dropdown

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "run-mode": "dev",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-01-16",
      "src_hash": "a8b23670b1827cdb0a04650edac0dfff4c6de1d5",
      "tag": "v0.53.0-SNAPSHOT",
      "hash": "bea3c3d"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.15 (Homebrew)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.5"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.5+11-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.5+11-LTS",
    "os.name": "Mac OS X",
    "os.version": "15.1.1",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

Very confusing while debugging other problems

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/53275

Before:
Normally the mapped field's `has_field_values` setting is used in dashboard filter widgets. There is one exception - if the field is a FK, then we use the `has_field_values` property of the target pk field instead, if it's available. It causes a lot of confusion both in code and from the UX point of view.

After:
Now the `has_field_values` property of the mapped field is used in all cases. To avoid changes for existing dashboards, this PR migrates `has_field_value` setting for FKs so that there is no difference in behavior for end users. If the PK's `has_field_values` is set to anything but `Plain input`, then the FK's `has_field_values` will be set to this value in the migration.

### CODE REVIEW

**Comment by mngr** [comment]
How can I test this?

**Comment by ranquild** [comment]
@mngr e.g. new Question -> Orders -> Save as Q1. Add to a dashboard. Connect an ID filter to Orders.User ID. The filter widget will be controlled by `has_field_values` setting on `Orders.User ID` and not `People.ID`

**Comment by mngr** [comment]
And how can we test the migration?

**Comment by mngr** [comment]
> @mngr e.g. new Question -> Orders -> Save as Q1. Add to a dashboard. Connect an ID filter to Orders.User ID. The filter widget will be controlled by `has_field_values` setting on `Orders.User ID` and not `People.ID`

This works fine. But when I switched the branch to master, for some reason the People.ID field had empty setting in Table Matadata (not input, not search and not list) - is this ok?

**Comment by ranquild** [comment]
@mngr can you reproduce it?

**Review by romeovs — APPROVED** [review]
FE looks good

**Comment by mngr** [comment]
> @mngr can you reproduce it?

No, it was only the first time I switched

File: src/metabase/parameters/params.clj [hunk 1]
```diff
@@ -123,8 +123,9 @@
   (let [table-id->name-field (fields->table-id->name-field (pk-fields fields))]
     (for [field fields]
       ;; add matching `:name_field` if it's a PK
-      (assoc field :name_field (when (isa? (:semantic_type field) :type/PK)
-                                 (table-id->name-field (:table_id field)))))))
+      (when field
```
Comment (ranquild) [inline src/metabase/parameters/params.clj:126]: added `when`

File: resources/migrations/001_update_migrations.yaml [hunk 2]
```diff
@@ -11957,6 +11957,40 @@ databaseChangeLog:
...
+        - sql:
+            dbms: h2
+            sql: >-
+              UPDATE metabase_field AS fk
+              SET has_field_values = (
+                SELECT coalesce(pk.has_field_values, fk.has_field_values)
+                FROM metabase_field AS pk
+                WHERE pk.id = fk.fk_target_field_id
+              )
+              WHERE fk_target_field_id IS NOT NULL AND semantic_type = 'type/FK';
```
Comment (metamben) [inline resources/migrations/001_update_migrations.yaml:12111]: Have you considered a cross platform query like
```sql
UPDATE metabase_field 
   SET has_field_values = (
       SELECT pk.has_field_values 
       FROM metabase_field pk 
       WHERE pk.id = metabase_field.fk_target_field_id
   )
 WHERE semantic_type = 'type/FK'
   AND has_field_values IS DISTINCT FROM (
       SELECT pk.has_field_values 
       FROM metabase_field pk 
       WHERE pk.id = metabase_field.fk_target_field_id
   );
```

Not doing the update when the two values are the same might be beneficial.

**Review by metamben — APPROVED** [review]
LGTM

File: resources/migrations/001_update_migrations.yaml (hunk 2 above)
Comment (ranquild) [reply resources/migrations/001_update_migrations.yaml:12111]: MySQL won't allow to query the table this way AFAIK
