### PR TITLE
Retain source alias for aggregates

### LINKED ISSUE #22310: Creating custom expressions with spaces in the name, then filtering, results in an error
**Describe the bug**
When creating a custom expression that has spaces in the name, e.g.
image
then applying a filter - the resulting question ends up with an error.

This error is caused by the subquery changing spaces in the column name to underscores (e.g. `Example_custom_expression`), then the final SELECT statement it errors as it tries to select the column with the old name (`Example custom expression`).

This issue seems to occur when adding filters, as it results in the subquery being created with the underscores replacing spaces.

**Logs**
```
400 Bad Request POST https://www.googleapis.com/bigquery/v2/projects/crested-unity-321617/queries { "code" : 400, "errors" : [ { "domain" : "global", "location" : "q", "locationType" : "parameter", "message" : "Name Example custom expression not found inside source at [2:72]", "reason" : "invalidQuery" } ], "message" : "Name Example custom expression not found inside source at [2:72]", "status" : "INVALID_ARGUMENT" }
```

**To Reproduce**
1. Create a new question with any custom expression that has a name with spaces in it
2. Add a group by 
3. Add a filter
image

**Expected behavior**
A 400 bad request error due to the final SELECT statement using the custom expression name with spaces, and a subquery with the custom column aliases with underscores instead

**Screenshots**
BigQuery editor showing the compiled SQL and the corresponding error.
image

This can be fixed manually by editing the SQL subquery to change the column name.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.10.76-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-04-07",
      "tag": "v0.42.4",
      "branch": "release-x.42.x",
      "hash": "7c3ce2d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Low for someone who is used to SQL and can manually edit queries, potentially medium otherwise

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by metamben**
Fixes #22310.

On the surface, the problem is that for BigQuery aliases are escaped but the reference to the aggregated value is not, so filtering on an aggregated value fails if the name of the aggregated expression changes when escaped.

Looking deeper, the problem seems to be that the result of the aggregation is not found as exported when adding the alias info: `:aggregation-options` clauses are ignored completely.
1.  I think because of a typo they are not added to the list of exports.
1. The `:name` property is overwritten with the escaped alias which makes it difficult to find the match.

The fix consists of adding `:aggregation-options` to the exports, saving the original name of the aggregation expression under `::source-alias`, and searching the aggregation expression in `matching-field-in-source-query*`.

### CODE REVIEW

**Review by dpsutton — APPROVED** [review]

File: src/metabase/query_processor/util/add_alias_info.clj [hunk 1]
```diff
@@ -186,7 +186,7 @@
 
 (defn- exports [query]
   (into #{} (mbql.u/match (dissoc query :source-query :source-metadata :joins)
-              [(_ :guard #{:field :expression :aggregation}) _ (_ :guard (every-pred map? ::position))])))
+              [(_ :guard #{:field :expression :aggregation-options}) _ (_ :guard (every-pred map? ::position))])))
```
Comment (camsaul) [inline src/metabase/query_processor/util/add_alias_info.clj:189]: So this wasn't a typo. `[:aggregation <index>]` is a reference to the aggregation at that index. Example

```clj
;; SELECT COUNT(*) AS "count" FROM "my_table" ORDER BY "count" DESC 
{:source-table 2
 :aggregation [[:count]]
 :order-by [[:desc [:aggregation 0]]]}
```

I think the idea was that `:aggregation` was supposed to come back with the appropriate info including the `::position` and stuff like that. That being said this clearly wasn't doing the right thing and wasn't working as intended, so I'm cool with doing something different.

**Review by camsaul — APPROVED** [review]
👍 

Good catch. The `add-alias-info` stuff is a pretty deep dive into QP internals and definitely a little hairy (but still a big improvement to what we had before where we attempted to calculate this stuff programmatically at the same time we compiled the query, which was pretty buggy). Color me impressed.
