### PR TITLE
Uppercase certain identifiers for snowflake

### LINKED ISSUE #9511: Snowflake Tables Don't Show
Hi guys,

I connected Snowflake and I see no error, but none of tables or views show.
I see the very similar issue https://github.com/metabase/metabase/issues/8864 , and after following that thread my problem persists. In my case, the database is called the same in Metabase and in Snowflake, so even if that same bu were occurring, it could not be causing the problem. 

- Your browser and the version: Chrome Version 72.0.3626.119 (Official Build) (64-bit)
- Your operating system: OS X 10,
- Your databases: Snowflake
- Metabase version: You're on version v0.31.2 
- Metabase hosting environment: Heroku
- Metabase internal database: not sure, Postgres, I think

- steps to reproduce issue:
- Log in, navigate to database
- Add new Snowflake in the Admin console, get successful connection test, but no tables or schemas appear

### PR DESCRIPTION
**Pull request by robdaemon**
Snowflake stores warehouse, database and schema names in uppper case.
When creating the connection details, uppercase them.

Resolves #9511

[ci snowflake]

### CODE REVIEW

**Comment by robdaemon** [comment]
@camsaul this is good to go. I can't do anything about the coverage diff here, since it's not including driver tests.

**Comment by camsaul** [comment]
@robdaemon so the codecoverage is yellow only because `be-linter-cloverage` failed, and that failed because there was a test failure, not due to coverage changes. The test failure was with one of the SSH tests which failed because the port was already in use -- it's a random failure I've seen once or twice before.

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj [hunk 1]
```diff
@@ -28,16 +28,26 @@
...
+    #"(?s).*" ; default - the Snowflake errors have a \n in them
+    message))
+
 (defmethod sql-jdbc.conn/connection-details->spec :snowflake
   [_ {:keys [account regionid], :as opts}]
   (let [host (if regionid
                (str account "." regionid)
-               account)]
+               account)
+        upcase-not-nil (fn [s] (when s (str/upper-case s)))]
```
Comment (camsaul) [inline modules/drivers/snowflake/src/metabase/driver/snowflake.clj:50]: I think this is going to be a problem with Turkish

**Review by camsaul — CHANGES_REQUESTED** [review]
Change `str/upper-case` to the one we have in `metabase.util` that uses `Locale/US`

File: modules/drivers/snowflake/src/metabase/driver/snowflake.clj (hunk 1 above)
Comment (robdaemon) [reply modules/drivers/snowflake/src/metabase/driver/snowflake.clj:50]: hah yes you're right, let me go change that

File: modules/drivers/snowflake/test/metabase/test/data/snowflake.clj [hunk 2]
```diff
@@ -45,13 +45,15 @@
...
+    ;; this lowercasing this value is part of testing the fix for
+    ;; https://github.com/metabase/metabase/issues/9511
+    :warehouse (str/lower-case (tx/db-test-env-var-or-throw :snowflake :warehouse))
     ;; SESSION parameters
     :timezone "UTC"}
    ;; Snowflake JDBC driver ignores this, but we do use it in the `query-db-name` function in
    ;; `metabase.driver.snowflake`
    (when (= context :db)
-     {:db (qualified-db-name database-name)})))
+     {:db (qualified-db-name (str/lower-case database-name))})))
```
Comment (camsaul) [inline modules/drivers/snowflake/test/metabase/test/data/snowflake.clj:56]: We should probably do this with `Locale/US` too. I don't know if Turkish is going to do anything weird but I'd rather not find out the hard way

File: src/metabase/util.clj [hunk 3]
```diff
@@ -745,6 +745,14 @@
   [^CharSequence s]
   (.. s toString (toLowerCase (Locale/US))))
 
+(defn upper-case-en
+  "Locale-agnostic version of `clojure.string/upper-case`.
+  `clojure.string/upper-case` uses the default locale in conversions, turning
+  `ID` into `ıd`, in the Turkish locale. This function always uses the
```
Comment (camsaul) [inline src/metabase/util.clj:751]: I think this docstring is backwards, this function is `upper-case` but the example is lowercasing stuff.

Anyways I think we should add a `lower-case-en` version too, just in case normal `str/lower-case` with Turkish does `ID` into `ıd

File: test/metabase/util_test.clj [hunk 4]
```diff
@@ -235,6 +235,16 @@
...
 
+(deftest upper-case-en-test
+  (let [original-locale (Locale/getDefault)]
+    (try
+      (Locale/setDefault (Locale/forLanguageTag "tr"))
+      ;; `(str/upper-case "id")` returns "İD" in the Turkish locale
+      (is (= "ID"
+             (u/upper-case-en "id")))
+      (finally
+        (Locale/setDefault original-locale)))))
```
Comment (camsaul) [inline test/metabase/util_test.clj:246]: we actually have a test util macro that does this already.

```clj
(mt/with-locale "tr"
  (str/lower-case "ID"))
;; -> "ıd"
```

**Review by camsaul — DISMISSED** [review]
I went and checked in the REPL and it looks like `str/lower-case` does weird things too for Turkish. So we should add a `lower-case-en` function and use that instead of `str/lower-case` as well so we don't end up with more bugs when people run Metabase in Turkish

**Comment by robdaemon** [comment]
Addressed the feedback.

We already had a `u/lower-case-en` function - I'm just adding the `u/upper-case-en` version.

I made an attempt at finding all of our `str/lower-case` and `str/upper-case` uses, but I ended up botching A LOT of stuff in the process. We should file a separate issue to do that? I do see places where things can go very wrong in the Turkish locale.

**Comment by flamber** [comment]
@robdaemon Could #11424 be expanded to include upper too?

**Review by sbelak — APPROVED** [review]
looks good
