### PR TITLE
Fetch nested card table metadata on dashboard load

### LINKED ISSUE #12614: Dashboard filters to Nested Question can only be added one way, and cannot be edited (FE bug)
**Describe the bug**
On `master`, it's now possible (#9802) to connect dashboard filter to columns from a nested question (ex. Custom question that uses a Native question), but it's only possible to add/edit the connection, when going directly from the question via "Add to dashboard".
If you start from dashboard and add the question from there, then you only see `No valid fields`.

**To Reproduce**
1. Native question > Sample Dataset - `SELECT * FROM "ORDERS"` - and save as Q1
2. Simple question > Saved Questions > select Q1 - and save as Q2
3. When it asks "Add to dashboard", click yes (or click pencil-icon next to question title)
4. Q2 is now added to dashboard, click "Add a filter" > Time > All Options, and connect to Q2 card
5. Save dashboard and try using the filter (ie. past 30 months) - works
6. Browser refresh
7. Edit dashboard
   a. Edit filter, notice that the card says `No valid fields`, but the filter is still working
   b. or, Add question Q2 again as another card and edit filter, which also says `No valid fields` for that card, when it's added directly from the dashboard, instead of thru the question (step 3)

**Information about your Metabase Installation:**
`master` commit `81edcd4`

**Severity**
Giving P1, since it makes all the work done in #9802 hard to use.

**Additional context**
There's a separate requests for exposing variable filters, which would allow more advanced filtering, while also allowing filters set to Required, which currently fails with `You'll need to pick a value for 'Filter' before this query can run.` (question) or `There was a problem displaying this chart.` (dashboard)
#6449 and #4367

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #12614 

As @camsaul mentioned in the issue, we didn't have data for nested tables stored in state. We do the big "fetch metadata" call for each database on the dashboard but that only includes real tables not saved questions. I added a bit of code to fetch metadata on any source tables with ids matching `/card__\d+/`.

### CODE REVIEW

**Comment by flamber** [comment]
@paulrosenzweig This only works if you've opened the question before going to the dashboard or the question already exists on the dashboard.
If you're adding the question directly from the dashboard, then it still says "No valid fields".

But you've also fixed #12455 as it is right now :tada:

**Comment by flamber** [comment]
Uhhh... just noticed, this replaces all Saved Questions with only the ones on the dashboard.

Currently I have two nested-questions on a dashboard, then go to Ask Question > Simple Question > Saved Questions, it only lists the two source-questions. Doing a browser refresh on Ask Question, then it lists the collections and hundreds of other questions I have in Saved Questions.

**Comment by paulrosenzweig** [comment]
@flamber thanks for spotting those!

The first issue was because I had missed another place we fetch the db metadata (adding a card to the dashboard). I extracted that logic to another function so fetching the db and any nested cards are stuck together better.

The other issue was a bug in the DataSelector. We checked for preloaded data by looking for _any_ data to display. e.g. if we had one database, we wouldn't fetch databases. It's likely that our preload calls prevented this from showing up elsewhere, but I tried to fix it generally. If we haven't made the relevant preloading call, we try and fetch data.

It looks like that second fix broke a test, which I'll look into tomorrow.

**Comment by flamber** [comment]
Awesomeness! From what I can tell, everything now seems to working as expected - including #12455

File: frontend/src/metabase/dashboard/dashboard.js [hunk 1]
```diff
@@ -1173,6 +1162,28 @@ const loadingDashCards = handleActions(
   { dashcardIds: [], loadingIds: [], startTime: null },
 );
 
+// This loads database metadata and nested questions for a list of dash cards.
+// We load the nested questions separately because the db metadata only includes real tables.
+function fetchDashCardEntities(dispatch, dashCards) {
```
Comment (tlrobinson) [inline frontend/src/metabase/dashboard/dashboard.js:1167]: Two things:

1. I'm not sure but it seems like `fetchDatabaseMetadata` might be overfetching tables that aren't needed. Maybe we should be calling `Tables.actions.fetchMetadata` for non-nested queries too.
2. We have an action called `loadMetadataForQuery` we use in the query builder: https://github.com/metabase/metabase/blob/03a5f98ff2c449ac30e02b6762cb0a37f2ff4449/frontend/src/metabase/redux/metadata.js#L326 I don't think we'll want to use that directly since we want to deduplicate requests, but we might want to write a similar one called `loadMetadataForQueries` or something, that calls `dependentMetadata()` on each query, deduplicates them, and makes the `Tables.actions.fetchMetadata` requests.

Comment (paulrosenzweig) [reply frontend/src/metabase/dashboard/dashboard.js]: Good call! That feels like a better solution.

I'm somewhat nervous that replacing the one big db fetch with one per table could slow things down for some dashboards. Still it's a step in the right direction though. If we see any slowness, we could batch those table fetches.

File: frontend/src/metabase/dashboard/dashboard.js [hunk 2]
```diff
@@ -1173,6 +1160,30 @@ const loadingDashCards = handleActions(
   { dashcardIds: [], loadingIds: [], startTime: null },
 );
 
+const loadMetadataForDashboard = dashCards => (dispatch, getState) => {
+  const metadata = getMetadata(getState());
+  _.chain(dashCards)
+    .map(dc => [dc.card].concat(dc.series))
+    .flatten()
+    .map(card => new Question(card, metadata).query().dependentMetadata())
```
Comment (tlrobinson) [inline frontend/src/metabase/dashboard/dashboard.js:1168]: I think everything from here down (except the `new Question().query()` part) should go in frontend/src/metabase/redux/metadata.js in a function called `loadMetadataForQueries` since they're similar. We could even replace `loadMetadataForQuery` with `const loadMetadataForQuery = query => loadMetadataForQueries([query])`

Comment (tlrobinson) [reply frontend/src/metabase/dashboard/dashboard.js:1168]: e.x. something like


```js
export const loadMetadataForQuery = query => loadMetadataForQueries([query]);

export const loadMetadataForQueries = query => dispatch => {
  const dependencies = queries
    .map(query => query.dependentMetadata())
    .flatten()
    // these next three lines dedupe deps by (type, id)
    .groupBy(dm => dm.type + dm.id)
    .values()
    .map(([dependency]) => dependency)
  return Promise.all(
    dependencies.map(({ type, id, ...options }) => {
      if (type === "table") {
        if (options.foreignTables) {
          return dispatch(Tables.actions.fetchMetadataAndForeignTables({ id }));
        } else {
          return dispatch(Tables.actions.fetchMetadata({ id }));
        }
      } else {
        console.warn(`loadQueryMetadata: type ${type} not implemented`);
      }
    }),
  ).catch(e => console.error("Failed loading metadata for query", e));
  )
}

Comment (tlrobinson) [reply frontend/src/metabase/dashboard/dashboard.js:1168]: Then 

```js
const queries = getMetadata(getState());
  _.chain(dashCards)
    .map(dc => [dc.card].concat(dc.series))
    .flatten()
    .map(card => new Question(card, metadata).query())
dispatch(loadMetadataForQueries(queries));
```

Comment (paulrosenzweig) [reply frontend/src/metabase/dashboard/dashboard.js]: 👍 I like it. I pushed those changes.

File: frontend/src/metabase/redux/metadata.js [hunk 3]
```diff
@@ -323,17 +323,27 @@ export const fetchRealDatabasesWithMetadata = createThunkAction(
...
+      .uniq(false, dep => dep.type + dep.id)
+      .map(({ type, id, foreignTables }) => {
+        if (type === "table") {
+          return (foreignTables
+            ? Tables.actions.fetchMetadataAndForeignTables
+            : Tables.actions.fetchMetadata)({ id });
         } else {
-          return dispatch(Tables.actions.fetchMetadata({ id }));
+          console.warn(
+            `loadMetadataForDashboard: type ${type} not implemented`,
```
Comment (tlrobinson) [inline frontend/src/metabase/redux/metadata.js:341]: loadMetadataForQueries

**Review by tlrobinson — APPROVED** [review]
LGTM, just one incorrect log string I noticed.
