### PR TITLE
Guard against version duplication (#33803)

### LINKED ISSUE #33803: Version info could have duplicated versions
### Describe the bug

The older version from `http://static.metabase.com/version-info-ee.json` could contain the latest version
image

This could happen for cases where we release a version twice, but that' totally possible so the code to update version info should prevent this.

### To Reproduce

^

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
master
```

### Severity

P3? since it does not really introduce any bug

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes https://github.com/metabase/metabase/issues/33803

### Description

This change adds some defensive code to avoid introducing duplicate versions into the "version-info" files during a release.

It also adds test coverage to show that not only are duplicates now prevented, existing duplication will be remediated.

### How to verify

Run the build tests:

```sh
clj -X:dev:drivers:build:build-dev:build-test
```

### CODE REVIEW

File: bin/build/src/release/version_info.clj [hunk 1]
```diff
@@ -47,19 +47,25 @@
...
-        (let [{:keys [latest], :as info} (current-version-info)]
-          (spit tmpname (-> info
-                            ;; move the current `:latest` to the beginning of `:older`
-                            (update :older (fn [older]
-                                             (distinct (cons latest older))))
-                            (assoc :latest (info-for-new-version))
-                            json/generate-string)))))))
+          (let [current-info (current-version-info)
+                new-version-info (info-for-new-version)
+                new-info (update-version-info current-info new-version-info)]
```
Comment (qnkhuat) [inline bin/build/src/release/version_info.clj:67]:
```suggestion
          (let [current-info     (current-version-info)
                new-version-info (info-for-new-version)
                new-info         (update-version-info current-info new-version-info)]
```

nit: we try to align let binding and map this way, it's much easier to read IMHO.

File: bin/build/test/release/version_info_test.clj [hunk 2]
```diff
@@ -17,34 +17,43 @@
...
+     :older  (for [v (rest versions)]
+               (apply make-version-map (conj v enterprise?)))}))
+
+(defn- duplicate-version [versions]
+  (into [(first versions)] versions))
+
+(def ^:private previous-version-cases
+  {"with previous versions" (rest test-versions)
+   "with duplicate previous versions" (duplicate-version (rest test-versions))
+   "including the current version" test-versions})
```
Comment (qnkhuat) [inline bin/build/test/release/version_info_test.clj:42]:
```suggestion
  {"with previous versions"           (rest test-versions)
   "with duplicate previous versions" (duplicate-version (rest test-versions))
   "including the current version"    test-versions})
```

nit: we try to align the map so that the values are aligned

If you're on emacs I think there are a plugin that do this automatically.

**Review by qnkhuat — APPROVED** [review]
LGTM, just has a couple of nits.

**Comment by crisptrutski** [comment]
Totally agree with the style tips - had naively hoped that Calva would pick up the repo conventions. Will manually fix for now.

File: bin/build/test/release/version_info_test.clj [hunk 3]
```diff
@@ -17,34 +17,43 @@
...
-                              ["38.3" "2021-04-01" true ["Fix 1" "Fix 2"]]
-                              ["38.2" "2021-03-21" true ["Older Fix 1" "Older Fix 2"]]
-                              ["38.1" "2021-03-14" true ["Much Older Fix 1" "Much Older Fix 2"]]
-                              ["38.0" "2021-02-15" true ["Super Old Fix 1" "Super Old Fix 2"]]])
+(def ^:private test-versions
+  [["39.0" today false ["Super New Fix 1" "Super New Fix 2"]]
+   ["38.3" "2021-04-01" true ["Fix 1" "Fix 2"]]
+   ["38.2" "2021-03-21" true ["Older Fix 1" "Older Fix 2"]]
+   ["38.1" "2021-03-14" true ["Much Older Fix 1" "Much Older Fix 2"]]
+   ["38.0" "2021-02-15" true ["Super Old Fix 1" "Super Old Fix 2"]]])
```
Comment (calherries) [inline bin/build/test/release/version_info_test.clj:28]: This is fairly subjective they were here before, but I would have expect these private defs to be inside `build-info-test`. Same with `previous-version-cases`. The main benefit is readability - these defs are very specific to the test's implementation and should be grouped with the assertions in a `deftest` block.

**Review by calherries — APPROVED** [review]
Nice! I left one cosmetic suggestion

File: bin/build/test/release/version_info_test.clj (hunk 3 above)
Comment (crisptrutski) [reply bin/build/test/release/version_info_test.clj:28]: That makes sense, although one concern I have is that the deftest expression will balloon somewhat! 

I'm still adjusting to reading Lisp again, and in particular the Metabase flavour, but will take a look at this restructuring and see how it feels to me.
