### PR TITLE
Fix settings left-hand nav being in opposite order in EE edition

### LINKED ISSUE #15441: Settings left-hand nav in opposite order in EE edition
Settings left-hand nav is in the opposite order (Caching... General, Setup) on EE that is is in OSS (Setup, General, ... Caching)

Left side is EE and right is OSS.

image

### PR DESCRIPTION
**Pull request by jeff303**
Updated the updateSectionsWithPlugins fn to sort the sections again after reducing by PLUGIN_ADMIN_SETTINGS_UPDATES, because those update functions might change the order of keys

Adding explicit order property for the items in SECTIONS to facilitate that re-sorting

Fix expected property type for SettingsEditorApp sections (which is truly an object, not an array), and fixed the null case accordingly

Added lightweight check in existing Cypress test for this

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
Not sure how the Cypress test passes, since Whitelabel is now the first option instead of the last.
image

Likely need to move https://github.com/metabase/metabase/blob/release-x.39.x/enterprise/frontend/src/metabase-enterprise/whitelabel/index.js#L61 to before the whitelabel section. Or add an order-attribute to the section.
But still don't understand how the test passes.

**Comment by nemanjaglumac** [comment]
> Not sure how the Cypress test passes

It probably doesn't. That's the smoke test and it's running nightly, so it didn't run now in CI.

**Comment by nemanjaglumac** [comment]
@flamber I just built this and am looking at the UI - it seems normal to me:
image

**Comment by jeff303** [comment]
> @flamber I just built this and am looking at the UI - it seems normal to me:
> image

Yeah I think the whitelabel feature has to be turned on, in order for it to appear in the top position.  It wasn't on my local EE instance (where I developed the test).  So I will either need to put it last, or change the assertion, maybe only for the last item.

**Comment by flamber** [comment]
@nemanjaglumac I'm using CI builds, so if they're not correct, then we need to fix them - they don't have translations either.

File: frontend/src/metabase/admin/settings/selectors.js [hunk 1]
```diff
@@ -26,20 +26,43 @@ import { PLUGIN_ADMIN_SETTINGS_UPDATES } from "metabase/plugins";
...
+        const bMap = sections[b[0]];
+        if (aMap.order !== undefined && bMap.order !== undefined) {
+          return aMap.order - bMap.order;
+        }
+      }
+      // undefined relative ordering, so just sort these two arbitrarily
+      return 1;
+    };
+
+    return Object.fromEntries(Object.entries(reduced).sort(reSortFn));
```
Comment (daltojohnso) [inline frontend/src/metabase/admin/settings/selectors.js:50]: in general, we shouldn't rely on order in objects since things like this can happen really easily, so we should probably make this an array of objects at some point soon. i won't make you do that here, but we can simplify the sort function a little bit. `Object.entries` generates a list of `[key, value]` pairs, so we can make `reSortFn`:

```
([, aVal], [, bVal]) => aVal && bVal && aVal.order - bVal.order
```

I suppose `aVal` and `bVal` have a chance to be `null` or `undefined` but I wouldn't worry too much about safeguards besides that.

**Review by daltojohnso — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/admin/settings/selectors.js (hunk 1 above)
Comment (jeff303) [reply frontend/src/metabase/admin/settings/selectors.js:41]: Done

**Review by daltojohnso — APPROVED** [review]
nice work
