### PR TITLE
Consistently handle infinite and empty values in scalar visualizations

### LINKED ISSUE #27395: Handle non-integer values consistently for all scalar visualizations
**Describe the bug**
Handle non-integer values consistently for all scalar visualizations

**To Reproduce**
1. Example use the following query to see types like `NaN` or `Infinity` or `null`
```
select case
  when {{type}}='0' then 0
  when {{type}}='1' then 1
  when {{type}}='null' then null
  when {{type}}='infinity' then 'Infinity'::real
  when {{type}}='nan' then 'NaN'::real
  end as val
from dual
where 1 = case when {{type}}='nothing' then 0 else 1 end
```

https://user-images.githubusercontent.com/1447303/209827694-caddad51-724a-4d00-8ac4-519bff6b6a3a.mp4

**Expected behavior**
Handle non-integer values consistently for all scalar visualizations. Currently the Number visualizations seems like the most correct one, where the Process Bar is most wrong.

**Information about your Metabase Installation:**
Tested 0.45.1

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/27395

### Description

- organizes Gauge and Progress visualizations into their own directories
- adds easily-testable getValue functions for these visualizations

the visualizations should show the following values for each case

  | number | gauge | progress
-- | -- | -- | --
0 | 0 | 0 | 0
null | null | 0 | 0
NaN | NaN | 0 | 0
infinity | infinity | Infinity (full gauge) | infinity (full bar)

### How to verify

- create a few visualizations using the sample query in the issue above
- see that the visualizations produce the expected output in each case

### Demo

Screen Shot 2023-04-03 at 5 02 01 PM
Screen Shot 2023-04-03 at 5 01 54 PM
Screen Shot 2023-04-03 at 5 01 46 PM
Screen Shot 2023-04-03 at 5 01 39 PM
Screen Shot 2023-04-03 at 5 01 32 PM
Screen Shot 2023-04-03 at 5 01 25 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/29805)

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/Progress/utils.ts
Comment (iethree) [inline frontend/src/metabase/visualizations/visualizations/Progress/utils.ts:1]: you might notice that this is the same as the Gauge getValue. I intentionally gave them separate functions to enable them to have different behavior, and avoid accidentally changing vbth when you wanted to change only one.

File: frontend/src/metabase/visualizations/visualizations/Gauge/utils.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+export const getValue = (rows: unknown[][]) => {
+  const rawValue = rows[0] && rows[0][0];
+
+  if (rawValue === "Infinity") {
```
Comment (EmmadUsmani) [inline frontend/src/metabase/visualizations/visualizations/Gauge/utils.ts:4]: Should this check be case insensitive, and are there other names to check for infinity? Or do we know for sure that it'll always a a serialized javascript "Infinity" value?

File: frontend/src/metabase/visualizations/visualizations/Progress/utils.ts
Comment (EmmadUsmani) [reply frontend/src/metabase/visualizations/visualizations/Progress/utils.ts:1]: Love this. I'm a big proponent of not sharing util functions unless you are absolutely certain the behavior should be 100% the same at all call sites, I've created bugs in the past by not doing this.

**Review by EmmadUsmani — APPROVED** [review]

File: frontend/src/metabase/visualizations/visualizations/Gauge/utils.ts (hunk 1 above)
Comment (iethree) [reply frontend/src/metabase/visualizations/visualizations/Gauge/utils.ts:4]: Postgres and H2 support an `Infinity` value, mySQL (following the generic SQL spec) doesn't allow it at all. As far as I can tell it will always be capitalized from the DB itself.
