### PR TITLE
Viz settings field partition dnd

### LINKED ISSUE #25785: Reordering columns in pivot tables breaks the UI
**Describe the bug**
When going to the settings of the pivot table and reordering a columns, the UI breaks

**Logs**
Unfortunately there are no logs

**To Reproduce**
1) create a pivot table
2) reorder a column

**Expected behavior**
Shouldn't break

**Screenshots**
image

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop OS 22.04
- Your databases: Postgres 14.4
- Metabase version: 1.44.4
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P2 at least

**Additional context**
NA

### PR DESCRIPTION
**Pull request by npfitz**
Fixes #25785 

Updating `ChartSettinFieldsPartition` to use `react-beautiful-dnd`. A lot of the logic updating state while dragging has been removed to keep the implementation light weight. The result is a slightly different experience, but much more understandable code.

chrome_IrYShIyNUK

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx [hunk 1]
```diff
@@ -44,148 +31,121 @@ class ChartSettingFieldsPartition extends React.Component {
...
-              updateDisplayedValue={updateDisplayedValue}
-              commitDisplayedValue={commitDisplayedValue}
-            />
-          ))
-        )}
-      </div>,
-    );
-  }
-}
+    if (
```
Comment (npfitz) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx:50]: This logic is kinda gross, but it's what was originally here. I'd be curious if folks can think of any improvements. Being a map of arrays, I suspect shallow cloning the map gets a little awkward.

File: frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx [hunk 2]
```diff
@@ -44,148 +31,121 @@ class ChartSettingFieldsPartition extends React.Component {
...
-    // The version of react-dnd we're on has a bug where endDrag isn't called.
-    // Drop is still called here, so we trigger commit here.
-    drop: (props, monitor, component) => {
-      props.commitDisplayedValue();
-    },
-  },
-  (connect, monitor) => ({ connectDropTarget: connect.dropTarget() }),
-)(PartitionInner);
+      partitionDup[sourceIndex] = partition[destinationIndex];
+      partitionDup[destinationIndex] = partition[sourceIndex];
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx:58]: It should not be a swap of source and destination because it is not natural:
- Initial list [1, 2, 3]
- Move 1 to the end, expected — [2, 3, 1] 
However, if your swap source and destination the list will become [3, 2, 1]

File: frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx [hunk 3]
```diff
@@ -44,148 +31,121 @@ class ChartSettingFieldsPartition extends React.Component {
...
+      fieldRefs
+        .map(field_ref =>
+          this.props.columns.find(col => _.isEqual(col.field_ref, field_ref)),
+        )
+        .filter(col => col != null),
+    );
+
+    return (
+      <DragDropContext onDragEnd={this.handleDragEnd}>
+        <div>
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx:89]: Do we need this div? Removing would slightly help to decrease the indentation

**Review by alxnddr — COMMENTED** [review]
I love how much cleaner it looks now and takes fewer lines!

Wdyt about making column items' height consistent with the regular table?
Screen Shot 2022-10-12 at 5 09 22 AM

File: frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx (hunk 2 above)
Comment (npfitz) [reply frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx:58]: That is true! I'll fix that up

**Comment by npfitz** [comment]
>dyt about making column items' height consistent with the regular table?
I agree that there isn't really any reason for them to be thicker. I removed some of their extra padding

File: frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx [hunk 4]
```diff
@@ -44,148 +33,118 @@ class ChartSettingFieldsPartition extends React.Component {
...
-    const { displayedValue } = this.state;
-    if (displayedValue != null) {
-      this.props.onChange(displayedValue);
-      this.setState({ displayedValue: null });
-    }
+
+  getPartitionType = partitionName => {
+    return partitionName === "rows" || partitionName === "columns"
+      ? "dimension"
+      : "metric";
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx:40]: Do you think using switch...case would make this easier to understand?

```suggestion
    switch (partitionName) {
      case "rows":
      case "columns":
        return "dimension";
      default:
        return "metric";
    }
```

It doesn't make much different though given this code is still fairly short.

**Review by WiNloSt — APPROVED** [review]
The code looks pretty solid to me. Also works great

File: frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js [hunk 5]
```diff
@@ -929,9 +930,39 @@ function assertOnPivotFields() {
 function dragField(startIndex, dropIndex) {
   cy.get(".Icon-grabber2").should("be.visible").as("dragHandle");
 
-  cy.get("@dragHandle").eq(startIndex).trigger("dragstart");
-
-  cy.get("@dragHandle").eq(dropIndex).trigger("drop");
+  const BUTTON_INDEX = 0;
+  const SLOPPY_CLICK_THRESHOLD = 10;
+  cy.get("@dragHandle")
```
[the remark this answers is not in the document]
Comment (npfitz) [reply frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js:934]: Had a quick call with Nemanja. Because we're using mouse events and need to determine coordinates, we kinda need to do this nesting (cypress doesn't play nice with async/await). I'm going to leave it like this for now, but in the future we should abstract this out into a more generic helper function and use it in our other DnD tests
