### PR TITLE
fix(sdk): make isEmbeddingSdk consistent on new iframe embed using singletons

### LINKED ISSUE #59602: `isEmbeddingSdk` from `metabase/env` and `getIsEmbeddingSdk` is not the same on iframe embedding.
### Describe the bug

We starts to use `isEmbeddingSdk` as a drop-in replacement for the selector `isEmbeddingSdk` which relies on redux. The reason was that we don't really change this value on Redux, so let's just inject an environment variable right?

The problem is that I found in the new iframe embedding. `getIsEmbeddingSdk` would be `true` while `isEmbeddingSdk` is false. This fails a lot of tests in #59243 because I also refer to `isEmbeddingSdk` from the env, not redux.

I think these 2 values should be the same on all environments for consistency.

### To Reproduce

1. Try printing `isEmbeddingSdk` from `metabase/env` and the value from the selector `getIsEmbeddingSdk` when using iframe embedding.

### Expected behavior

They should return the same value.

### Logs

_No response_

### Information about your Metabase installation

```JSON
master @ d710fb129f038ecf7144e7083aaf71ce223c896e
```

### Severity

p2 or almost p1, since this should break a lot of assumption when we use `isEmbeddingSdk` on iframe embedding.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by heypoom**
Closes #59602
Closes EMB-504

Introduces a [config singleton object](https://github.com/metabase/metabase/commit/1f95265d5cdad4ffa5a5fb0051f2a27e0b1b3001) `EMBEDDING_SDK_CONFIG` which stores `isEmbeddingSdk`, and conditionally sets this singleton based on the entry points. We then replace the `isEmbeddingSdk` environment variable and `getIsEmbeddingSdk` Redux selector with the `isEmbeddingSdk()` function that checks `EMBEDDING_SDK_CONFIG.isEmbeddingSdk`.

This intentionally excludes tree-shaking scenarios which uses `if (process.env.IS_EMBEDDING_SDK)` explicitly to tree-shake huge imports, such as lazy-loading date locales.

### How to verify

- Existing tests should continue to pass.
- `SDK environment config` unit test should pass.

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/index.ts [hunk 1]
```diff
@@ -11,6 +13,10 @@ import "sdk-ee-plugins";
 // Imports which are only applicable to the embedding sdk, and not the new iframe embedding.
 import "sdk-specific-imports";
 
+// Enable SDK mode as we are in the SDK bundle
+// This applies to SDK derivatives such as new iframe embedding.
+EMBEDDING_SDK_CONFIG.isSdk = true;
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/index.ts:18]: We import the `"embedding-sdk"` from `SdkIframeEmbedRoute.tsx` for new iframe embedding too, so this flag gets set both for the SDK and new iframe embed.

**Comment by heypoom** [comment]
~Tests are failing. Let me check~ Fixed unit tests.

File: enterprise/frontend/src/embedding-sdk/index.ts [hunk 2]
```diff
@@ -11,6 +13,10 @@ import "sdk-ee-plugins";
 // Imports which are only applicable to the embedding sdk, and not the new iframe embedding.
 import "sdk-specific-imports";
 
+// Enable SDK mode as we are in the SDK bundle
+// This applies to SDK derivatives such as new iframe embedding.
+EMBEDDING_SDK_CONFIG.isEmbeddingSdk = true;
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/index.ts]: We import the "embedding-sdk" entry point from `SdkIframeEmbedRoute.tsx` in new iframe embedding too, so this field gets set to `true` for both for the SDK and new iframe embedding.

File: enterprise/frontend/src/embedding-sdk/store/index.ts [hunk 3]
```diff
@@ -38,7 +38,6 @@ export const getSdkStore = () =>
       options: {
         entity_types: DEFAULT_EMBEDDING_ENTITY_TYPES,
       },
-      isEmbeddingSdk: true,
```
Comment (heypoom) [inline enterprise/frontend/src/embedding-sdk/store/index.ts:41]: This is replaced with a singleton.

File: frontend/src/metabase/env.ts [hunk 4]
```diff
@@ -43,8 +43,3 @@ export const isChartsDebugLoggingEnabled = tryOrDefault(
   () => process.env.MB_LOG_CHARTS_DEBUG === "true",
   false,
 );
-
-export const isEmbeddingSdk = tryOrDefault(
-  () => !!process.env.IS_EMBEDDING_SDK,
-  false,
-);
```
Comment (heypoom) [inline frontend/src/metabase/env.ts:50]: The environment is also replaced by a singleton.

File: enterprise/frontend/src/embedding-sdk/index.ts (hunk 2 above)
Comment (npretto) [reply enterprise/frontend/src/embedding-sdk/index.ts]: This looks almost like a side effect that we could remove by mistake though, can we make it explicit?

Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/index.ts]: @npretto Would setting it by function e.g. `setIsEmbeddingSdk(true)` be more explicit in your opinion? I'll do that if that works

Comment (npretto) [reply enterprise/frontend/src/embedding-sdk/index.ts]: It's not about `= true` or `set(true)`, is that this is only set in the iframe embedidng  that is importing this file.
What if in 2 months we change the way we import the components and instead of importing them from `index.ts` we import them from the subfolders for performance reasons?
I'm wondering if we should put `EMBEDDING_SDK_CONFIG.isEmbeddingSdk = true;` in the entry point of the iframe entry point too

Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/index.ts]: Ah! I get what you mean now, let me add it in `app-embed-sdk.tsx` (the new iframe's entry point)

Comment (npretto) [inline enterprise/frontend/src/embedding-sdk/index.ts]: Can we move this as high as possible in the file? I'm scared we may add an import before this line and we'll run into horrible bugs 😢 
Right after `import { EMBEDDING_SDK_CONFIG } from "metabase/embedding-sdk/config";` is a good place

**Review by npretto — APPROVED** [review]

File: enterprise/frontend/src/embedding-sdk/index.ts (hunk 2 above)
Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/index.ts]: Good point! Fixed in https://github.com/metabase/metabase/pull/60349/commits/513556141404122df9e0f5d7e4080723366716f5. I was afraid of eslint failing but apparently it allows doing assignments before imports 😮

Comment (heypoom) [reply enterprise/frontend/src/embedding-sdk/index.ts]: Fixed in https://github.com/metabase/metabase/pull/60349/commits/5082535584f36ee3b0685053f7a39c9894c0d9a0, thanks!
