### PR TITLE
Ensure :effective-type for columns from an aggregation in a card

### LINKED ISSUE #47184: `Lib.isNumber` returns `false` for aggregation-based columns after join is removed
### Describe the bug

https://github.com/user-attachments/assets/0fdad69e-ef03-4de4-9084-6c24748402d8

### To Reproduce

_this might not be the optimal path to reproduce and certainly isn't the only possible one_

1. New > Question > Orders > Save
2. New > Model > Notebook > Use question from step (1) as data source > Join Reviews on Product ID = Product ID > Count > Save
3. New Dashboard > Add new number filter
4. Add model from step 2 to dashboard 
5. Try to connect the number filter to the model - notice that you can choose "Count" column
6. Save dashboard
7. Open model
8. Edit query definition
9. Remove join
10. Save
11. Go back to dashboard
12. Try to connect the number filter to the model

### Expected behavior

It should be possible to connect the "Count" column to the number filter

### Information about your Metabase installation

master, 743ae09aca

### Severity

P2

### Additional info

This `Lib.isNumber` check gives unexpected result for the "Count" column: https://github.com/metabase/metabase/blob/bcd1a90cb67e4aa10da252aa296b00f06496a74f/frontend/src/metabase-lib/v1/parameters/utils/filters.ts#L52

### PR DESCRIPTION
**Pull request by metamben**
Fixes #47184

### Description

Ensure `:effective-type` is set.

### How to verify

Describe the steps to verify that the changes are working as expected.

Try the repro steps from #47184.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/api/query_metadata.clj [hunk 1]
```diff
@@ -63,8 +63,7 @@
      ;; since they tend to query only a handful of databases at most.
      :databases (sort-by :id (get-databases database-ids))
      :tables    (sort-by (comp str :id) tables)
-     :fields    (or (sort-by :id (api.field/get-fields template-tag-field-ids))
-                    [])}))
+     :fields    (sort-by :id (api.field/get-fields template-tag-field-ids))}))
```
Comment (metamben) [inline src/metabase/api/query_metadata.clj:66]: Unrelated, dead code removal.

**Review by ranquild — APPROVED** [review]
