### PR TITLE
Performance + memory usage optimisations for json unfolding during sync

### LINKED ISSUE #55912: "Allow unfolding of JSON columns" reproducibly causes OutOfMemoryError in sync-fields again, this time within 90s despite Xmx=2GB
### Describe the bug

Same as https://github.com/metabase/metabase/issues/34754 but came back either because of v0.52.6.2 or more likely something in our data changed.  Reproducible on 53.8 it's never been so fast to crash before but I don't know how to find which column is causing it so I had to disable unfolding entirely again, after which sync-fields completes after 200s.  

Could limiting the size of json queried help per https://github.com/metabase/metabase/issues/34798#issuecomment-1768753488 and similar to  https://github.com/metabase/metabase/issues/46137 ?  Or maybe you can tell from my logs what the issue is or add more instrumentation in a future release to indicate which table to disable?  I know @piranha couldn't reproduce this before but @darksciencebase generated larger JSON that maybe did?

### To Reproduce

1. Click "Sync database schema now"
2. Watch logs to see OutOfMemoryError

### Expected behavior

shouldn't run itself out of memory unfolding json columns

### Logs

[unfold_json_oom_53_8.txt](https://github.com/user-attachments/files/19507964/unfold_json_oom_53_8.txt)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "netsuite",
      "bigquery-cloud-sdk",
      "athena"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-03-25",
      "tag": "v0.53.8",
      "hash": "e1eecad"
    },
    "settings": {
      "report-timezone": "UTC"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.15"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.6+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.6",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.6+7-LTS",
    "os.name": "Linux",
    "os.version": "4.14.326-245.539.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

blocking use of JSON

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bronsa**
closes #55912
Closes https://linear.app/metabase/issue/SEM-193/allow-unfolding-of-json-columns-reproducibly-causes-outofmemoryerror

# Description:
Several attempts were made to reproduce the original OOM by generating large numbers of tables with varying numbers of JSON columns and inserting different configurations of generated JSON data to stress the JSON unfolding analysis. While we failed to reproduce the OOM, we encountered a scenario that led to a larger memory footprint than expected: a large number of rows with many unique JSON paths per column.

This PR makes several performance optimizations to the JSON unfolding process:

- Made queries lazier by selecting only the fields they need
- Used more transducers instead of realizing sequences
- Moved some filtering from Clojure to SQL
- Fixed a potential resource leak of Jackson parser objects
- Most importantly, introduced a new hard limit for the total working set built up during type analysis, after which we short-circuit

### CODE REVIEW

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj [hunk 1]
```diff
@@ -502,7 +498,7 @@
   [v path]
   (if-not (json-object? v)
     {}
-    (let [p (json-parser v)]
+    (with-open [p (json-parser v)]
```
Comment (bronsa) [inline src/metabase/driver/sql_jdbc/sync/describe_table.clj:502]: this fixes a potential resource leak

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj [hunk 2]
```diff
@@ -540,42 +536,63 @@
...
+  5)
+
 (defn- describe-json-rf
   "Reducing function that takes a bunch of maps from json-map->types,
   and gets them to conform to the type hierarchy,
   going through and taking the lowest common denominator type at each pass,
-  ignoring the nils."
-  ([] nil)
+  ignoring the nils.
+  Short circuits after `(max-nested-field-columns * max-nested-field-columns-factor)` entries."
```
Comment (bronsa) [inline src/metabase/driver/sql_jdbc/sync/describe_table.clj:578]: I believe this is the crux of the issue: without limiting the working set, in degenerate cases with JSON entries containing many unique paths, the working set can theoretically grow much larger than our `max-nested-field-columns`, up to `max-nested-field-columns * table-rows-sample/nested-field-sample-limit`. In my testing, I've easily gotten it to reach 50,500 entries.

Adding this extra limit trades some completeness in the type analysis for memory usage guarantees. We're already making this tradeoff earlier in the pipeline by limiting the number of JSON paths we parse to `max-nested-field-columns`, so this doesn't introduce any new uncertainty, it just extends the tradeoff we already make in `json->types`.

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj [hunk 3]
```diff
@@ -187,50 +187,49 @@
...
+               {:visibility-type :details-only})))))))
 
 (defn describe-table-fields-xf
-  "Returns a transducer for computing metadata about the fields in a table, given the database `db`."
-  [driver db]
-  (comp
-   (describe-fields-xf driver db)
-   (map-indexed (fn [i col] (dissoc (assoc col :database-position i) :table-schema)))))
+  "Returns a transducer for computing metadata about the fields in a table"
+  [driver table]
```
Comment (bronsa) [inline src/metabase/driver/sql_jdbc/sync/describe_table.clj:227]: this is a breaking change, but `describe-table-fields-xf` isn't actually used anywhere else, and given that `*table-info*` is private, it would've been difficult to even use it correctly. 
I've documented the change in the drivers changelog

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj [hunk 4]
```diff
@@ -540,42 +536,62 @@
...
-              (fn [column-type]
-                (some (fn [allowed-type]
-                        (isa? column-type allowed-type))
-                      [String Number Boolean java.time.LocalDateTime]))
-              [(acc-field-type-map json-column) (second-field-type-map json-column)])
-             [json-column java.lang.String]
-
-             :else
-             [json-column nil])))))
+   (let [max-count (* max-nested-field-columns max-nested-field-columns-factor)]
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: My understanding is that we are limiting the processing of paths found among json fields of a table to first 1K unique paths found.

In [json->types](https://github.com/metabase/metabase/blob/0d61f1dc9f5ed7279e0c9493d3daf53e16e27a2d/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L498) we generate at most ~~500~~ 100 paths per field per row of sampled data. 

That is merged with other this-table json column path maps [json->map-types](https://github.com/metabase/metabase/blob/0d61f1dc9f5ed7279e0c9493d3daf53e16e27a2d/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L542) and that single merged map is input to this function.

So now examine only first 1K unique paths. Later we use only 100 fields generated from those paths [here](https://github.com/metabase/metabase/blob/0d61f1dc9f5ed7279e0c9493d3daf53e16e27a2d/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L708).

@bronsa, does that match you understanding? If so I think that process could be further optimized _in future_.

**Review by lbrdnk — APPROVED** [review]

File: src/metabase/driver/sql_jdbc/sync/describe_table.clj (hunk 4 above)
Comment (bronsa) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: > My understanding is that we are limiting the processing of paths found among json fields of a table to first 1K unique paths found.
> 

> 
> That is merged with other this-table json column path maps [json->map-types](https://github.com/metabase/metabase/blob/0d61f1dc9f5ed7279e0c9493d3daf53e16e27a2d/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L542) and that single merged map is input to this function.
> 
> So now examine only first 1K unique paths. Later we use only 100 fields generated from those paths [here](https://github.com/metabase/metabase/blob/0d61f1dc9f5ed7279e0c9493d3daf53e16e27a2d/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L708).
> 
> @bronsa, does that match you understanding? If so I think that process could be further optimized _in future_.

almost, but not quite: 
> In [json->types](https://github.com/metabase/metabase/blob/0d61f1dc9f5ed7279e0c9493d3daf53e16e27a2d/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L498) we generate at most 500 paths per field per row of sampled data.

we generate at most 100(+1) paths per field per row of sampled data, sampled data is at most 500 rows.

Those unique paths are then merged together, which in the best case (the set of 100 paths is the same for each of the 500 rows sampled) gives us 100 paths, in the worse (the 500 sets are totally disjoint) give us 50500 unique paths (ther is an off by one). 

Crucially, during the merging process paths can be made "useless for consideration", if the type narrowing can't find a common type, and if so, [the path is discarded](https://github.com/metabase/metabase/pull/59122/files#diff-e4db3baaafcba181fc735b94c34048deb437fc47e8a2bd3acb9057732d92b330R636). 

This is why we must consider more than 100 paths to then reduce the working set back to 100: it could be that a high percentage of paths would end up being discarded, thus we'd end up with fewer than `max-nested-field-columns` paths. 

10*max-nested-field-columns seems a good compromise.

Comment (lbrdnk) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: Sorry, the 500 is typo. The unsuccessful attempt to refer to [max-nested-field-columns](https://github.com/metabase/metabase/blob/5631b69254f5d938523941762dfed6c01e423af5/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L457).

---

> Those unique paths are then merged together, which in the best case (the set of 100 paths is the same for each of the 500 rows sampled) gives us 100 paths, in the worse (the 500 sets are totally disjoint) give us 50500 unique paths (ther is an off by one).

Yes.

> Crucially, during the merging process paths can be made "useless for consideration", if the type narrowing can't find a common type, and if so, [the path is discarded](https://github.com/metabase/metabase/pull/59122/files#diff-e4db3baaafcba181fc735b94c34048deb437fc47e8a2bd3acb9057732d92b330R636).

Isn't the discarding based solely on whether lowest common denominator type is nil? I think that would be nil only for examined paths that are nil type for every examined row. Based on that I think that maybe discarding those nil columns during reduction would enable us to just take first 100 paths. Or is there a flaw in my reasoning?

Comment (bronsa) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: > Isn't the discarding based solely on whether lowest common denominator type is nil? I think that would be nil only for examined paths that are nil type for every examined row. Based on that I think that maybe discarding those nil columns during reduction would enable us to just take first 100 paths. Or is there a flaw in my reasoning?

Consider `[{path b, ...} {path a, ..} {path a, .. }]`, assuming `a` and `b` are incompatible and would reduce to `nil`
If we were to discard on `nil`, the reduction would produce:
```
- {}
- {path b}
- {path b, ..}
- {path nil, ..} -> discarded into {.. }
- {path a, ..}
```
In other words, after reducing to `nil`, by discarding the path we would lose knowledge of having hit an incompatibility, and we'd potentially add the path back into the working set

Comment (lbrdnk) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: > In other words, after reducing to nil, by discarding the path we would lose knowledge of having hit an incompatibility, and we'd potentially add the path back into the working set.

Reading `lowest-common-denominator-type` I have a feeling it does not not matter whether path was in a map with nil value or it was not present.

It seems to me that we get the types from acc and second-map and we pick the non-nil if present.

Comment (bronsa) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: > Reading `lowest-common-denominator-type` I have a feeling it does not not matter whether path was in a map with nil value or it was not present.
> 
> It seems to me that we get the types from acc and second-map and we pick the non-nil if present.

.. ah :) that is a bug in `lowest-common-denominator-type` then, `nil`s that make their way into `acc` are important. I just pushed a fix for that case

Comment (lbrdnk) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: Shouldn't we consider the lowest common denominator the string? (That reads unnaturally but could be the case.) I'd expect there to be some tests to catch this and probably there are not (EDIT: not in your PR, but present already; seems that those will be added in your PR :)).

Prior merging, I think we should confirm there is no change in behavior and write tests to avoid misunderstandings in future.

Comment (bronsa) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: > Shouldn't we consider the lowest common denominator the string? (That reads unnaturally but could be the case.) I'd expect there to be some tests to catch this and probably there are not.

We do, IFF the types are non-reducible but all part of the [allowed set](https://github.com/metabase/metabase/pull/59122/files#diff-e4db3baaafcba181fc735b94c34048deb437fc47e8a2bd3acb9057732d92b330R554-R560).

The nil case is for strictly irreducible and disallowed types, which from my understanding would be to guard against [this case](https://github.com/metabase/metabase/blob/b18ea984335e43361a6029979fb71ca9fbd831d8/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L533), i.e. arrays.

I'll follow up with extra test cases

Comment (lbrdnk) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: I think arrays are handled separately as per [this mapping](https://github.com/metabase/metabase/blob/b18ea984335e43361a6029979fb71ca9fbd831d8/src/metabase/driver/sql_jdbc/sync/describe_table.clj#L597). To the best of my knowledge that is represented as string in the application.

Comment (bronsa) [reply src/metabase/driver/sql_jdbc/sync/describe_table.clj:582]: As discussed offline, it does look like there's a pre-existing bug in type analysis, but we're not sure what the intended behavior is supposed to be.
As such, I've backed out my fix and we'll merge the PR as is with just perf improvements, and follow up with a bug fix after confirming expected behavior.
