### PR TITLE
remove misleading permissions tooltip

### LINKED ISSUE #22356: [Permissions > Downloads] Slightly misleading copy in the popover when data permissions are set to `block`
**Describe the bug**
When data permissions for a certain user group are set to `block`, we automatically prevent users from that group from downloading. The UI will automatically grey out Download permissions for that group and set it to "No". When you hover it, it will display a popup that says: _"Downloads results access requires a full data access"_.
That is not true because users with "No self-service" data permissions and the permissions for collections can still access **and** download saved questions.

**Logs**
N/A

**To Reproduce**
_Applicable only to EE version:_
1. Go to data permissions and select a Sample Databsae (`/admin/permissions/data/database/1`)
2. By default, All users have full download permissions (set to 1 million rows)
3. Set the data permissions for All users to `block`
4. Notice how download permissions changed to "No" which is now greyed out
5. Hover it and you'll see the tooltip popover

**Expected behavior**
Either remove the tooltip or update the copy so it reflects our permissions model more truthfully.

**Screenshots**
image

**Information about your Metabase Installation:**
local dev, `master`, 7b98efbd92c5639d2969f9de3d0f30b1b6bf39e7, H2, Sample Database

**Severity**
P3

### PR DESCRIPTION
**Pull request by alxnddr**
Closes https://github.com/metabase/metabase/issues/22356

## Changes

Update hint tooltip copy for the download permission when it is disabled due to `block` data access permission.

Screenshot 2022-05-04 at 23 16 27

## How to verify

Check the original issue for repro steps

### CODE REVIEW

File: enterprise/frontend/src/metabase-enterprise/feature_level_permissions/permission-management/download-permission.ts [hunk 1]
```diff
@@ -21,7 +21,19 @@ import {
 import { getGroupFocusPermissionsUrl } from "metabase/admin/permissions/utils/urls";
 import { PLUGIN_ADVANCED_PERMISSIONS } from "metabase/plugins";
 
-export const DOWNLOAD_PERMISSION_REQUIRES_DATA_ACCESS = t`Download results access requires full data access.`;
+export const UNABLE_TO_DOWNLOAD_RESULTS = t`Users with Block data access can't download results`;
```
Comment (nemanjaglumac) [inline enterprise/frontend/src/metabase-enterprise/feature_level_permissions/permission-management/download-permission.ts:24]: I'm not sure this can be backported to the current release because it's adding a new translation string. cc @flamber @mazameli @jeff-bruemmer

Comment (nemanjaglumac) [reply enterprise/frontend/src/metabase-enterprise/feature_level_permissions/permission-management/download-permission.ts:24]: Maybe the solution is to remove the tooltip all together for this release (as @jeff-bruemmer suggested on Slack), and follow up with the newer version of the tooltip with this string, but point it to the v44.

Comment (jeff-bruemmer) [reply enterprise/frontend/src/metabase-enterprise/feature_level_permissions/permission-management/download-permission.ts:24]: You can backport this change. I believe @mazameli  said in the #releases channel that he'd do a round of translations for the next point release.

```suggestion
export const UNABLE_TO_DOWNLOAD_RESULTS = t`Groups with Block data access can't download results`;
```

I'm suggesting we change "Users" to "Groups", as we assign permissions to groups, not people.

Thanks for catching this, and creating the fix, @nemanjaglumac!

Comment (alxnddr) [reply enterprise/frontend/src/metabase-enterprise/feature_level_permissions/permission-management/download-permission.ts]: @jeff-bruemmer updated, thanks for your suggestion!

**Review by jeff-bruemmer — APPROVED** [review]
