### PR TITLE
Fix adding a time in legacy date picker

### LINKED ISSUE #49075: "Add filter" button is disabled after clicking "add a time"
### Describe the bug

Image

### To Reproduce

1. New > SQL query
2. Type `select {{date}}`
3. Change variable type to Date
4. Click the filter to set the value
5. Notice "Add filter" button is enabled
6. Click "Add a time"

"Add filter" button is disabled

### Expected behavior

"Add filter" button is enabled

### Information about your Metabase installation

master, b96f55194c2670c1c8e73d75ab0645c6864bd940

### Severity

P2

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/49075

How to verify:
- New -> SQL query -> `SELECT * FROM PRODUCTS WHERE CREATED_AT = {{created_at}}`
- Change the variable type to `Date`
- Click on the date picker widget -> `Add a time`
- The `Add filter` button should not be disabled and it should be possible to add the filter.

Screenshot 2024-10-24 at 14 07 31
Screenshot 2024-10-24 at 14 07 34

### CODE REVIEW

File: frontend/src/metabase/admin/datamodel/components/filters/pickers/DatePicker/DatePickerFooter.tsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ const DatePickerFooter: React.FC<React.PropsWithChildren<Props>> = ({
         operator,
         field,
         start,
-        operator === "between" && !end ? start : end,
+        ...(operator === "between" ? [end ?? start] : []),
```
Comment (ranquild) [inline frontend/src/metabase/admin/datamodel/components/filters/pickers/DatePicker/DatePickerFooter.tsx:65]: This is raw MBQL. Yes, dashboard components use raw MBQL for state and then convert it to string values; it's not used for MBQL queries in dashboards. The unit test verifies that we get correct raw MBQL now.

File: frontend/src/metabase/admin/datamodel/components/filters/pickers/DatePicker/DatePicker.unit.spec.tsx [hunk 2]
```diff
@@ -265,6 +265,25 @@ describe("DatePicker", () => {
             "2020-05-21",
           ]);
         });
+
+        it(`can add time to a specific ${description} date filter`, async () => {
```
Comment (kamilmielnik) [inline frontend/src/metabase/admin/datamodel/components/filters/pickers/DatePicker/DatePicker.unit.spec.tsx:269]: :x: All new tests pass without the fix

**Review by kamilmielnik — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/admin/datamodel/components/filters/pickers/DatePicker/DatePicker.unit.spec.tsx (hunk 2 above)
Comment (ranquild) [reply frontend/src/metabase/admin/datamodel/components/filters/pickers/DatePicker/DatePicker.unit.spec.tsx:269]: Super great catch. Fixed. https://metaboat.slack.com/archives/C505ZNNH4/p1729871695712579

**Review by kamilmielnik — APPROVED** [review]
