### PR TITLE
 Optimise autocomplete query

### LINKED ISSUE #30588: Autosuggestion in native queries peaks the CPU on instances with > 1M fields
### Describe the bug

Several times a day, Metabase has huge CPU spikes. This makes our EC2 instance unresponsive for hours, and even crashed 4 times in the last 3 days.

CPU usage of the EC2 instance, with crashes numbered:
Screenshot 2023-05-05 at 18 34 53

After investigating, this is related to the internal Postgres database CPU spikes (the correlation is pretty clear):
image

Skimming through the logs, it turns out calls to `/api/database/4/autocomplete_suggestions` are spamming the internal Postgres database, making it crash. The logs are available below.

The query running is something along the lines of this (except it's parametrized, and I renamed tables for clarity):
```sql
SELECT field.name
     , field.base_type
     , field.semantic_type
     , field.id
     , field.table_id
     , mb_table.name AS table_name
FROM metabase_field AS field
LEFT JOIN metabase_table AS mb_table
    ON mb_table.id = field.table_id
WHERE field.active
    AND LOWER(field.name) LIKE '%y%'
    AND field.visibility_type NOT IN ('sensitive', 'retired')
AND (mb_table.db_id = 4)
ORDER BY LOWER(field.name) ASC, LOWER(mb_table.name) ASC
LIMIT 50
```

There are 2 main issues:
* This query is ran ~700x in 10s, with different parameters
* This query takes ~3s to run outside CPU peaks, because there is a very expensive ORDER BY (which could be optimized using a materialized view). Without the ORDER BY, query runs instantly. But I understand we can't just remove it.

700 calls that all take at least ~3s is very expensive, and happens again and again and again... This is a severe issue, and is making our Metabase instance very unstable.

### To Reproduce

Not sure about the specific steps.

To give a rough idea of our scale:
* `metabase_field` has `1 791 609` values.
* `metabase_table` has `73 762` values.

That's clearly a lot (way more than our actual Snowflake database), which made me investigate the problem a little more: **Metabase does not delete old tables from `metabase_table`**, which is a known [feature](https://github.com/metabase/metabase/issues/6146#issuecomment-1466337334). 

We have a lot of tables that stay for ~1 day and then get deleted, but Metabase keeps them in the DB. Same for the fields. This lead to unecessary big JOIN in our case. We can lower the time taken by the query by adding `AND mb_table.active` in the WHERE, and `AND field.active AND mb_table.active` in the JOIN: this make Postgres remove rows faster, and increases the query speed - though it's still so slow it would create CPU spikes:
```
SELECT field.name
     , LOWER(field.name) AS name_lower
     , field.base_type
     , field.semantic_type
     , field.id
     , field.table_id
     , mb_table.name AS table_name
     , LOWER(mb_table.name) AS table_name_lower
FROM metabase_field AS field
LEFT JOIN metabase_table AS mb_table
    ON mb_table.id = field.table_id
    AND mb_table.active
    AND field.active
WHERE field.active
  AND LOWER(field.name) LIKE '%y%'
  AND field.visibility_type NOT IN ('sensitive', 'retired')
  AND (mb_table.db_id = 4)
  AND mb_table.active
ORDER BY name_lower ASC, table_name_lower ASC
LIMIT 50
```

### Expected behavior

We should not have CPU spikes - either the query shouldn't be spammed, or it should be faster to execute.

### Logs

Internal Postgres logs (around 700 queries in 10s):
```
2023-05-05 06:17:51 UTC:<redacted>(49228):<redacted>@metabase:[29158]:LOG:  duration: 5920.578 ms  execute <unnamed>: SELECT "metabase_field"."name", "metabase_field"."base_type", "metabase_field"."semantic_type", "metabase_field"."id", "metabase_field"."table_id", "table"."name" AS "table_name" FROM "metabase_field" LEFT JOIN "metabase_table" AS "table" ON "table"."id" = "metabase_field"."table_id" WHERE ("metabase_field"."active" = TRUE) AND (LOWER("metabase_field"."name") LIKE $1) AND ("metabase_field"."visibility_type" NOT IN ($2, $3)) AND ("table"."db_id" = $4) ORDER BY LOWER("metabase_field"."name") ASC, LOWER("table"."name") ASC LIMIT $5
2023-05-05 06:17:51 UTC:<redacted>(49228):<redacted>@metabase:[29158]:DETAIL:  parameters: $1 = '%y%', $2 = 'sensitive', $3 = 'retired', $4 = '4', $5 = '50'
2023-05-05 06:17:51 UTC:<redacted>(49214):<redacted>@metabase:[29157]:LOG:  duration: 6167.508 ms  execute <unnamed>: SELECT "metabase_field"."name", "metabase_field"."base_type", "metabase_field"."semantic_type", "metabase_field"."id", "metabase_field"."table_id", "table"."name" AS "table_name" FROM "metabase_field" LEFT JOIN "metabase_table" AS "table" ON "table"."id" = "metabase_field"."table_id" WHERE ("metabase_field"."active" = TRUE) AND (LOWER("metabase_field"."name") LIKE $1) AND ("metabase_field"."visibility_type" NOT IN ($2, $3)) AND ("table"."db_id" = $4) ORDER BY LOWER("metabase_field"."name") ASC, LOWER("table"."name") ASC LIMIT $5
2023-05-05 06:17:51 UTC:<redacted>(49214):<redacted>@metabase:[29157]:DETAIL:  parameters: $1 = '%y%', $2 = 'sensitive', $3 = 'retired', $4 = '4', $5 = '50'
2023-05-05 06:17:54 UTC:<redacted>(49232):<redacted>@metabase:[29159]:LOG:  duration: 8810.162 ms  execute <unnamed>: SELECT "metabase_field"."name", "metabase_field"."base_type", "metabase_field"."semantic_type", "metabase_field"."id", "metabase_field"."table_id", "table"."name" AS "table_name" FROM "metabase_field" LEFT JOIN "metabase_table" AS "table" ON "table"."id" = "metabase_field"."table_id" WHERE ("metabase_field"."active" = TRUE) AND (LOWER("metabase_field"."name") LIKE $1) AND ("metabase_field"."visibility_type" NOT IN ($2, $3)) AND ("table"."db_id" = $4) ORDER BY LOWER("metabase_field"."name") ASC, LOWER("table"."name") ASC LIMIT $5
2023-05-05 06:17:54 UTC:<redacted>(49232):<redacted>@metabase:[29159]:DETAIL:  parameters: $1 = '%y%', $2 = 'sensitive', $3 = 'retired', $4 = '4', $5 = '50'
2023-05-05 06:17:54 UTC:<redacted>(47544):<redacted>@metabase:[14892]:LOG:  duration: 8911.150 ms  execute <unnamed>: SELECT "metabase_field"."name", "metabase_field"."base_type", "metabase_field"."semantic_type", "metabase_field"."id", "metabase_field"."table_id", "table"."name" AS "table_name" FROM "metabase_field" LEFT JOIN "metabase_table" AS "table" ON "table"."id" = "metabase_field"."table_id" WHERE ("metabase_field"."active" = TRUE) AND (LOWER("metabase_field"."name") LIKE $1) AND ("metabase_field"."visibility_type" NOT IN ($2, $3)) AND ("table"."db_id" = $4) ORDER BY LOWER("metabase_field"."name") ASC, LOWER("table"."name") ASC LIMIT $5
2023-05-05 06:17:54 UTC:<redacted>(47544):<redacted>@metabase:[14892]:DETAIL:  parameters: $1 = '%y%', $2 = 'sensitive', $3 = 'retired', $4 = '4', $5 = '50'
2023-05-05 06:17:54 UTC:<redacted>(47548):<redacted>@metabase:[14891]:LOG:  duration: 9233.002 ms  execute S_88: SELECT "metabase_field"."name", "metabase_field"."base_type", "metabase_field"."semantic_type", "metabase_field"."id", "metabase_field"."table_id", "table"."name" AS "table_name" FROM "metabase_field" LEFT JOIN "metabase_table" AS "table" ON "table"."id" = "metabase_field"."table_id" WHERE ("metabase_field"."active" = TRUE) AND (LOWER("metabase_field"."name") LIKE $1) AND ("metabase_field"."visibility_type" NOT IN ($2, $3)) AND ("table"."db_id" = $4) ORDER BY LOWER("metabase_field"."name") ASC, LOWER("table"."name") ASC LIMIT $5
2023-05-05 06:17:54 UTC:<redacted>(47548):<redacted>@metabase:[14891]:DETAIL:  parameters: $1 = '%y%', $2 = 'sensitive', $3 = 'retired', $4 = '4', $5 = '50'
2023-05-05 06:17:55 UTC:<redacted>(49160):<redacted>@metabase:[29152]:LOG:  duration: 9266.541 ms  execute <unnamed>: SELECT "metabase_field"."name", "metabase_field"."base_type", "metabase_field"."semantic_type", "metabase_field"."id", "metabase_field"."table_id", "table"."name" AS "table_name" FROM "metabase_field" LEFT JOIN "metabase_table" AS "table" ON "table"."id" = "metabase_field"."table_id" WHERE ("metabase_field"."active" = TRUE) AND (LOWER("metabase_field"."name") LIKE $1) AND ("metabase_field"."visibility_type" NOT IN ($2, $3)) AND ("table"."db_id" = $4) ORDER BY LOWER("metabase_field"."name") ASC, LOWER("table"."name") ASC LIMIT $5
2023-05-05 06:17:55 UTC:<redacted>(49160):<redacted>@metabase:[29152]:DETAIL:  parameters: $1 = '%y%', $2 = 'sensitive', $3 = 'retired', $4 = '4', $5 = '50'
```

At the same time, here are the Metabase logs:
```
May 05 06:17:51 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:51,738 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 6.1 s (6 DB calls) App DB connections: 15/15 Jetty threads: 43/300 (10 idle, 0 queued) (432 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:52 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:52,540 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 2.9 s (6 DB calls) App DB connections: 15/15 Jetty threads: 42/300 (10 idle, 0 queued) (432 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:52 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:52,658 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 2.9 s (6 DB calls) App DB connections: 15/15 Jetty threads: 41/300 (10 idle, 0 queued) (432 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:54 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:54,090 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 4.2 s (6 DB calls) App DB connections: 15/15 Jetty threads: 67/300 (0 idle, 0 queued) (446 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:54 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:54,593 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 9.1 s (6 DB calls) App DB connections: 15/15 Jetty threads: 67/300 (1 idle, 0 queued) (447 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:55 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:55,160 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 3.0 s (6 DB calls) App DB connections: 15/15 Jetty threads: 84/300 (0 idle, 0 queued) (463 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:55 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:55,187 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 9.7 s (6 DB calls) App DB connections: 15/15 Jetty threads: 84/300 (0 idle, 0 queued) (463 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:55 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:55,247 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 3.4 s (6 DB calls) App DB connections: 15/15 Jetty threads: 88/300 (0 idle, 0 queued) (467 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:55 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:55,276 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 9.6 s (6 DB calls) App DB connections: 13/15 Jetty threads: 90/300 (0 idle, 0 queued) (469 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:55 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:55,370 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 9.8 s (6 DB calls) App DB connections: 15/15 Jetty threads: 88/300 (1 idle, 0 queued) (470 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:55 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:55,691 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 10.2 s (6 DB calls) App DB connections: 15/15 Jetty threads: 87/300 (1 idle, 0 queued) (470 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:55 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:55,726 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 10.1 s (6 DB calls) App DB connections: 15/15 Jetty threads: 86/300 (1 idle, 0 queued) (470 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:55 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:55,743 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 10.2 s (6 DB calls) App DB connections: 15/15 Jetty threads: 85/300 (1 idle, 0 queued) (470 total active threads) Queries in flight: 0 (0 queued)
May 05 06:17:55 ip-172-31-61-102.eu-central-1.compute.internal bash[3832]: 2023-05-05 06:17:55,773 DEBUG middleware.log :: GET /api/database/4/autocomplete_suggestions 200 3.9 s (6 DB calls) App DB connections: 15/15 Jetty threads: 84/300 (1 idle, 0 queued) (470 total active threads) Queries in flight: 0 (0 queued)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7-LTS",
    "os.name": "Linux",
    "os.version": "4.14.313-235.533.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-04-05",
      "tag": "v0.46.1",
      "branch": "release-x.46.x",
      "hash": "12a6e1d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Crashes our Metabase instance 4 times in the last 3 days ⇒ very impactful.

### Additional context

Related issue: [#19016](https://github.com/metabase/metabase/issues/19016) (was closed).

### PR DESCRIPTION
**Pull request by romeovs**
Partially resolves https://github.com/metabase/metabase/issues/30588

### Description

This PR implements some of the suggestions made in https://github.com/metabase/metabase/issues/30588#issuecomment-1536676195, as far as `toucan2` will take them.

This is what's implemented:

1. Optimizing the auto-suggestion queries (at least 10x faster is needed): 
    - [x] `A materialized view might work very well here, to be tested`, or an index on a `lower(metabase_field.name)` (only for pgsql though)
    - [x] `Checking if the table is active in the WHERE`,
    - [x] `Duplicating the .active checks in the JOIN ON … condition`.
    - [x] `The LEFT JOIN is not necessary (and should be changed to a INNER JOIN)`
2. `Lower the spam of queries with some trick`. This is done in #37852

### How to verify

It's hard to verify the extreme memory usage locally, but we can at least verify these changes did not break the autocomplete endpoint:

1. `SQL Query` → `Sample Dataset`
2. Start typing a query like `SELECT SEA`
3. The autocompletion dropdown should return `SEATS`

### Checklist

I've added no extra tests for this issue.

### CODE REVIEW

**Comment by piranha** [comment]
Would be nice to have some query which exhibits performance problems, right now looking at `explain analyze` is almost useless since it's so fast for everything I'm trying... Have you seen slowness like this on stats perhaps?

**Comment by piranha** [comment]
As for point number three, you can write `:inner-join [[:metabase_table :table] [:and [:= :table.id :metabase_field.table_id] :table.active]]` and this will work.

**Comment by piranha** [comment]
@metabase/core-backend-components this is ready for review

**Comment by qnkhuat** [comment]
Could you add note on why the cache control change is needed?

**Comment by piranha** [comment]
@qnkhuat done, how'd you like it?

File: src/metabase/api/database.clj [hunk 1]
```diff
@@ -620,11 +621,16 @@
...
+    {:status  200
+     ;; Presumably user will repeat same prefixes many times writing the query,
+     ;; so let them cache response to make autocomplete feel fast. 60 seconds
+     ;; is not enough to be a nuisance when schema or permissions change. Cache
+     ;; is user-specific since we're checking for permissions.
+     :headers {"Cache-Control" "public, max-age=60"
+               "Vary"          "Cookie"}
+     :body    (cond
+                substring (autocomplete-suggestions id (str "%" substring "%"))
+                prefix    (autocomplete-suggestions id (str prefix "%")))}
```
Comment (crisptrutski) [inline src/metabase/api/database.clj:633]: nit: I'm a sucker for small methods and avoiding mixing too many levels of abstraction. I'd break out a small `with-user-specific-cache-header` method which takes the body.

File: src/metabase/api/database.clj [hunk 2]
```diff
@@ -551,10 +551,11 @@
              :%lower.metabase_field/name     [:like (u/lower-case-en search-string)]
              :metabase_field.visibility_type [:not-in ["sensitive" "retired"]]
              :table.db_id                    db-id
-             {:order-by  [[[:lower :metabase_field.name] :asc]
-                          [[:lower :table.name] :asc]]
-              :left-join [[:metabase_table :table] [:= :table.id :metabase_field.table_id]]
-              :limit     limit}))
+             {:order-by   [[[:lower :metabase_field.name] :asc]
+                           [[:lower :table.name] :asc]]
+              :inner-join [[:metabase_table :table] [:and :table.active
```
Comment (crisptrutski) [inline src/metabase/api/database.clj:556]: It might be worth commenting that it was (counter-intuitively) faster to have the "active" check within the join, in case someone comes to optimize again.

File: src/metabase/api/database.clj [hunk 3]
```diff
@@ -551,10 +551,11 @@
              :%lower.metabase_field/name     [:like (u/lower-case-en search-string)]
```
Comment (crisptrutski) [inline src/metabase/api/database.clj:551]: It might be worth commenting that an index on `lower(name)` dramatically speeds the query up in DBs that support it, but we left it for now since Maria and H2 do not support indexes on computed fields. Perhaps they'll catch up in future? I also wonder if there are other use cases for a lowercase username, we could always materialize this as another column.

**Review by crisptrutski — APPROVED** [review]

File: test/metabase/api/database_test.clj [hunk 4]
```diff
@@ -683,6 +685,13 @@
                                         ["CATEGORY" "PRODUCTS :type/Text :type/Category"]
                                         ["CATEGORY_ID" "VENUES :type/Integer :type/FK"]]}]
         (is (= expected (prefix-fn (mt/id) prefix))))
+      (testing " returns sane Cache-Control headers"
+        (is (=? {"Cache-Control" "public, max-age=30"
```
Comment (crisptrutski) [inline test/metabase/api/database_test.clj:689]: This needs to be changed to 60 now

File: src/metabase/api/database.clj (hunk 2 above)
Comment (piranha) [reply src/metabase/api/database.clj:556]: Hah, it felt intuitive for me - you get less data to join this way 😁 But sure, I can leave a comment there.

File: src/metabase/api/database.clj (hunk 1 above)
Comment (piranha) [reply src/metabase/api/database.clj:634]: IDK, I'd rather this be "in the face" until a general pattern emerges...

File: src/metabase/api/database.clj (hunk 2 above)
Comment (crisptrutski) [reply src/metabase/api/database.clj:561]: Probably you're right, my intuition is quite rusty and I didn't give much thought to it 😆

File: src/metabase/api/database.clj (hunk 1 above)
Comment (crisptrutski) [reply src/metabase/api/database.clj:638]: Rule of 3? Fine 😄

**Review by crisptrutski — APPROVED** [review]
