### PR TITLE
Fix popover width for dual date picker

### LINKED ISSUE #5971: "Between" time filter's calendar is cut off
It overflows the popover's boundaries:

screen shot 2017-09-14 at 9 58 49 am

This is on Chrome on our stats instance, and it happens with both dashboard filters and query builder filters.

### PR DESCRIPTION
**Pull request by kdoh**
Fixes #5971 

Removes the max-width on the PopoverBody when the FilterWidget is working with dates. This max width was causing the cut off in dual calendar mode when using between filters.

Also moves to use our Grid system for calendar layout to make the calendar layout logic more explicit.

### CODE REVIEW

**Comment by kdoh** [comment]
So one aspect of how I initially tried to do this is we have to address any instance of `Popover` or `PopoverWithTrigger` that renders something we want to remove the maxwidth from. In the case of the original issue it's side by side date pickers, but you could imagine there being other cases where we need to override the max-width.

For that reason it seems like we'll want to probably make this fix more generic and rather than specify that date picker popovers need to be allowed to expand, just say that there's a way to remove the max width on a popover and that in this case, date pickers should use those. Maybe a modifier class like `Popover.Popover--autoWidth` or something along those lines so we have it for future use.

The alternative of course would be to remove the max-width globally and instead specify instances where we need things to wrap, but I'm not sure I dig that as much as the "whitelisting" approach, since it'll mean we don't have the at least some minimum assurance of things capping their width and not looking goofy like in #4930 which spawned the max-width in the first place.

@attekei I might wait to get your feedback on those thoughts before I actually go in and change things in the PR.

File: frontend/src/metabase/qb/components/TimeseriesFilterWidget.jsx [hunk 1]
```diff
@@ -125,6 +125,7 @@ export default class TimeseriesFilterWidget extends Component {
                 triggerClasses={cx(className, "my2")}
                 ref={ref => this._popover = ref}
                 sizeToFit
+                className="DatePopover"
```
Comment (attekei) [inline frontend/src/metabase/qb/components/TimeseriesFilterWidget.jsx]: Yeah I think we talked earlier that as a general principle, passing class names to our React components is considered an anti-pattern. So something like `noMaxWidth` or `maxWidth={null}`would probably be better – maybe the former because then we can have something like `noMaxWidth={isDatePicker}`in case of `FilterWidget`.

**Comment by kdoh** [comment]
@attekei Updated with a new `autoWidth` prop for the popovers. Let me know what you think.

File: frontend/src/metabase/query_builder/components/filters/FilterWidget.jsx [hunk 2]
```diff
@@ -135,6 +137,13 @@ export default class FilterWidget extends Component {
                     isInitiallyOpen={this.props.filter[1] === null}
                     onClose={this.close}
                     horizontalAttachments={["left"]}
+                    autoWidth={
+                        // If the field is a date field the filter popover
+                        // should be allowed to auto size its width to accomodate
+                        // the calendars
+                        // $FlowFixMe
+                        dimension.field().isDate()
```
Comment (kdoh) [inline frontend/src/metabase/query_builder/components/filters/FilterWidget.jsx]: @attekei Running into one issue here. This only evaluates to true if the filter has actually been added, so if you're adding a new filter the issue still persists. Any ideas on how to properly handle that?

Comment (attekei) [reply frontend/src/metabase/query_builder/components/filters/FilterWidget.jsx]: Ah, I think that I can take a look tomorrow and push a commit that fixes that.

I like the `autoWidth` prop! I could merge this PR after pushing the fix if that is fine to you.

Comment (kdoh) [reply frontend/src/metabase/query_builder/components/filters/FilterWidget.jsx]: Sounds great. Thanks!

**Comment by attekei** [comment]
Pushed a fix; it moves the conditional width logic to FilterPopover and uses the new Popover `maxWidth` prop always when you show any kind of filter popover.

I'd like @kdoh you to still verify that this works as expected.

**Comment by kdoh** [comment]
@attekei Yeah looks like everything is working as I'd expect. I'll fix up CI and merge this once it's done.
