### PR TITLE
Fix x-ray generate invalid query for table with Date column

### LINKED ISSUE #46249: X-rays can't be saved
### Describe the bug

Some x-rays can't be saved

### To Reproduce

1. Create PG database `dvdrental` and import sample dataset from https://www.postgresqltutorial.com/postgresql-getting-started/postgresql-sample-database/
2. Add it as new data source in Metabase 
3. X-ray some tables like City
5. Errors are thrown in the backend but the X-ray is still saved
6. Then x-ray the Customer table and try to save it. This throws a 500 error

### Expected behavior

X-rays should be saved

### Logs

```
[backend] 2024-07-29 20:37:18,538 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 182.8 ms (20 DB calls) App DB connections: 8/13 Jetty threads: 8/50 (8 idle, 0 queued) (126 total active threads) Queries in flight: 1 (0 queued); postgres DB 2 connections: 4/6 (0 threads blocked) {:metabase-user-id 1}
[backend] 2024-07-29 20:37:18,539 WARN api.common :: Unexpected parameters at [:post "/api/dataset"]: [:type :query :parameters]
[backend] Please add them to the schema or remove them from the API client
[backend] 2024-07-29 20:37:18,539 WARN api.common :: Unexpected parameters at [:post "/api/dataset"]: [:type :query :parameters]
[backend] Please add them to the schema or remove them from the API client
[backend] 2024-07-29 20:37:18,540 WARN api.common :: Unexpected parameters at [:post "/api/dataset"]: [:type :query :parameters]
[backend] Please add them to the schema or remove them from the API client
[backend] 2024-07-29 20:37:18,559 ERROR middleware.catch-exceptions :: Error processing query: Invalid output: {:query {:breakout [[nil nil ["Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}"]]], :order-by [[nil [nil nil ["Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}"]]]]}}
[backend] {:database_id 2,
[backend]  :started_at #t "2024-07-29T20:37:18.477399+01:00[Atlantic/Canary]",
[backend]  :via
[backend]  [{:status :failed,
[backend]    :class clojure.lang.ExceptionInfo,
[backend]    :error
[backend]    "Error preprocessing query in clojure.lang.AFunction$1@3d0ea128: Invalid output: {:query {:breakout [[nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]], :order-by [[nil [nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]]]}}",
[backend]    :stacktrace
[backend]    ["--> query_processor.preprocess$fn__95624$_AMPERSAND_f__95625$fn__95626$fn__95627.invoke(preprocess.clj:150)"
[backend]     "query_processor.preprocess$fn__95624$_AMPERSAND_f__95625$fn__95626.invoke(preprocess.clj:124)"
[backend]     "query_processor.setup$fn__95589$_AMPERSAND_f__95590.invoke(setup.clj:225)"
[backend]     "query_processor.setup$fn__95589$fn__95594.invoke(setup.clj:216)"
[backend]     "query_processor.preprocess$fn__95624$_AMPERSAND_f__95625.invoke(preprocess.clj:122)"
[backend]     "query_processor.preprocess$fn__95624$fn__95639.invoke(preprocess.clj:118)"
[backend]     "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:46)"
[backend]     "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
[backend]     "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$eval146220$handle_audit_app_internal_queries__146221$fn__146222.invoke(handle_audit_queries.clj:145)"
[backend]     "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__90731.invoke(enterprise.clj:103)"
[backend]     "query_processor.middleware.process_userland_query$fn__96509$_AMPERSAND_f__96510$_AMPERSAND_f__96511.invoke(process_userland_query.clj:196)"
[backend]     "query_processor.middleware.process_userland_query$fn__96509$_AMPERSAND_f__96510$fn__96517.invoke(process_userland_query.clj:179)"
[backend]     "query_processor.middleware.catch_exceptions$fn__96336$_AMPERSAND_f__96337$_AMPERSAND_f__96338.invoke(catch_exceptions.clj:128)"
[backend]     "query_processor.middleware.catch_exceptions$fn__96336$_AMPERSAND_f__96337$fn__96350.invoke(catch_exceptions.clj:118)"
[backend]     "query_processor$fn__96839$_AMPERSAND_f__96840$fn__96841.invoke(query_processor.clj:80)"
[backend]     "query_processor.setup$fn__95581$_AMPERSAND_f__95582$fn__95583.invoke(setup.clj:189)"
[backend]     "query_processor.setup$fn__95571$_AMPERSAND_f__95572$fn__95573.invoke(setup.clj:181)"
[backend]     "query_processor.setup$fn__95561$_AMPERSAND_f__95562$fn__95563$fn__95564.invoke(setup.clj:166)"
[backend]     "driver$do_with_driver.invokeStatic(driver.clj:106)"
[backend]     "driver$do_with_driver.invoke(driver.clj:101)"
[backend]     "query_processor.setup$fn__95561$_AMPERSAND_f__95562$fn__95563.invoke(setup.clj:165)"
[backend]     "query_processor.setup$fn__95549$_AMPERSAND_f__95550$fn__95551$fn__95554.invoke(setup.clj:151)"
[backend]     "query_processor.store$fn__76049$_AMPERSAND_f__76050.invoke(store.clj:171)"
[backend]     "query_processor.store$fn__76049$fn__76053.invoke(store.clj:151)"
[backend]     "query_processor.store$fn__76049$_AMPERSAND_f__76050.invoke(store.clj:160)"
[backend]     "query_processor.store$fn__76049$fn__76053.invoke(store.clj:151)"
[backend]     "query_processor.setup$fn__95549$_AMPERSAND_f__95550$fn__95551.invoke(setup.clj:150)"
[backend]     "query_processor.setup$fn__95531$_AMPERSAND_f__95532$_AMPERSAND_f__95533.invoke(setup.clj:128)"
[backend]     "query_processor.setup$fn__95531$_AMPERSAND_f__95532$fn__95536.invoke(setup.clj:122)"
[backend]     "query_processor.setup$fn__95589$_AMPERSAND_f__95590.invoke(setup.clj:232)"
[backend]     "query_processor.setup$fn__95589$fn__95594.invoke(setup.clj:216)"
[backend]     "query_processor$fn__96839$_AMPERSAND_f__96840.invoke(query_processor.clj:78)"
[backend]     "query_processor$fn__96839$fn__96845.invoke(query_processor.clj:71)"
[backend]     "api.dataset$fn__121816$_AMPERSAND_f__121819$fn__121823.invoke(dataset.clj:84)"
[backend]     "query_processor.streaming$_streaming_response$fn__83953$fn__83954$fn__83955.invoke(streaming.clj:175)"
[backend]     "query_processor.streaming$_streaming_response$fn__83953$fn__83954.invoke(streaming.clj:174)"
[backend]     "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
[backend]     "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
[backend]     "query_processor.streaming$_streaming_response$fn__83953.invoke(streaming.clj:171)"
[backend]     "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:68)"
[backend]     "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66)"
[backend]     "async.streaming_response$do_f_async$task__46251.invoke(streaming_response.clj:87)"],
[backend]    :error_type :qp,
[backend]    :ex-data
[backend]    {:fn #object[clojure.lang.AFunction$1 0x3d0ea128 "clojure.lang.AFunction$1@3d0ea128"],
[backend]     :query
[backend]     {:constraints {:max-results 10000, :max-results-bare-rows 2000},
[backend]      :middleware {:js-int-to-string? true, :userland-query? true, :add-default-userland-constraints? true},
[backend]      :user-parameters
[backend]      [{:type :category, :id "978782895", :target [:dimension [:field 352 nil]]}
[backend]       {:type :category, :id "-1186615977", :target [:dimension [:field 252 {:source-field 358}]]}],
[backend]      :info {:executed-by 1, :context :ad-hoc, :query-hash #object["[B" 0x6e56b4a6 "[B@6e56b4a6"]},
[backend]      :database 2,
[backend]      :type :query,
[backend]      :query
[backend]      {:aggregation [[:count]],
[backend]       :breakout [[:field 350 {:temporal-unit :minute}]],
[backend]       :source-table 41,
[backend]       :order-by [[:asc [:field 350 {:temporal-unit :minute}]]]}},
[backend]     :type :qp}}],
[backend]  :action_id nil,
[backend]  :error_type :qp,
[backend]  :json_query
[backend]  {:database 2,
[backend]   :type "query",
[backend]   :query {:aggregation [["count"]], :breakout [["field" 350 {:temporal-unit "minute"}]], :source-table 41},
[backend]   :parameters
[backend]   [{:type "category", :value nil, :id "978782895", :target ["dimension" ["field" 352 nil]]}
[backend]    {:type "category", :value nil, :id "-1186615977", :target ["dimension" ["field" 252 {:source-field 358}]]}],
[backend]   :middleware {:js-int-to-string? true, :userland-query? true, :add-default-userland-constraints? true}},
[backend]  :native nil,
[backend]  :status :failed,
[backend]  :class clojure.lang.ExceptionInfo,
[backend]  :stacktrace
[backend]  ["--> query_processor.middleware.desugar$fn__90654$fn__90657.invoke(desugar.clj:50)"
[backend]   "query_processor.preprocess$ensure_legacy$fn__95616.invoke(preprocess.clj:64)"
[backend]   "query_processor.preprocess$fn__95624$_AMPERSAND_f__95625$fn__95626$fn__95627.invoke(preprocess.clj:134)"
[backend]   "query_processor.preprocess$fn__95624$_AMPERSAND_f__95625$fn__95626.invoke(preprocess.clj:124)"
[backend]   "query_processor.setup$fn__95589$_AMPERSAND_f__95590.invoke(setup.clj:225)"
[backend]   "query_processor.setup$fn__95589$fn__95594.invoke(setup.clj:216)"
[backend]   "query_processor.preprocess$fn__95624$_AMPERSAND_f__95625.invoke(preprocess.clj:122)"
[backend]   "query_processor.preprocess$fn__95624$fn__95639.invoke(preprocess.clj:118)"
[backend]   "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:46)"
[backend]   "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)"
[backend]   "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$eval146220$handle_audit_app_internal_queries__146221$fn__146222.invoke(handle_audit_queries.clj:145)"
[backend]   "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__90731.invoke(enterprise.clj:103)"
[backend]   "query_processor.middleware.process_userland_query$fn__96509$_AMPERSAND_f__96510$_AMPERSAND_f__96511.invoke(process_userland_query.clj:196)"
[backend]   "query_processor.middleware.process_userland_query$fn__96509$_AMPERSAND_f__96510$fn__96517.invoke(process_userland_query.clj:179)"
[backend]   "query_processor.middleware.catch_exceptions$fn__96336$_AMPERSAND_f__96337$_AMPERSAND_f__96338.invoke(catch_exceptions.clj:128)"
  "query_processor.middleware.catch_exceptions$fn__96336$_AMPERSAND_f__96337$fn__96350.invoke(catch_exceptions.clj:118)"
[backend]   "query_processor$fn__96839$_AMPERSAND_f__96840$fn__96841.invoke(query_processor.clj:80)"
[backend]   "query_processor.setup$fn__95581$_AMPERSAND_f__95582$fn__95583.invoke(setup.clj:189)"
[backend]   "query_processor.setup$fn__95571$_AMPERSAND_f__95572$fn__95573.invoke(setup.clj:181)"
[backend]   "query_processor.setup$fn__95561$_AMPERSAND_f__95562$fn__95563$fn__95564.invoke(setup.clj:166)"
[backend]   "driver$do_with_driver.invokeStatic(driver.clj:106)"
[backend]   "driver$do_with_driver.invoke(driver.clj:101)"
[backend]   "query_processor.setup$fn__95561$_AMPERSAND_f__95562$fn__95563.invoke(setup.clj:165)"
[backend]   "query_processor.setup$fn__95549$_AMPERSAND_f__95550$fn__95551$fn__95554.invoke(setup.clj:151)"
[backend]   "query_processor.store$fn__76049$_AMPERSAND_f__76050.invoke(store.clj:171)"
[backend]   "query_processor.store$fn__76049$fn__76053.invoke(store.clj:151)"
[backend]   "query_processor.store$fn__76049$_AMPERSAND_f__76050.invoke(store.clj:160)"
[backend]   "query_processor.store$fn__76049$fn__76053.invoke(store.clj:151)"
[backend]   "query_processor.setup$fn__95549$_AMPERSAND_f__95550$fn__95551.invoke(setup.clj:150)"
[backend]   "query_processor.setup$fn__95531$_AMPERSAND_f__95532$_AMPERSAND_f__95533.invoke(setup.clj:128)"
[backend]   "query_processor.setup$fn__95531$_AMPERSAND_f__95532$fn__95536.invoke(setup.clj:122)"
[backend]   "query_processor.setup$fn__95589$_AMPERSAND_f__95590.invoke(setup.clj:232)"
[backend]   "query_processor.setup$fn__95589$fn__95594.invoke(setup.clj:216)"
[backend]   "query_processor$fn__96839$_AMPERSAND_f__96840.invoke(query_processor.clj:78)"
[backend]   "query_processor$fn__96839$fn__96845.invoke(query_processor.clj:71)"
[backend]   "api.dataset$fn__121816$_AMPERSAND_f__121819$fn__121823.invoke(dataset.clj:84)"
[backend]   "query_processor.streaming$_streaming_response$fn__83953$fn__83954$fn__83955.invoke(streaming.clj:175)"
[backend]   "query_processor.streaming$_streaming_response$fn__83953$fn__83954.invoke(streaming.clj:174)"
[backend]   "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
[backend]   "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
[backend]   "query_processor.streaming$_streaming_response$fn__83953.invoke(streaming.clj:171)"
[backend]   "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:68)"
[backend]   "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66)"
[backend]   "async.streaming_response$do_f_async$task__46251.invoke(streaming_response.clj:87)"],
[backend]  :card_id nil,
[backend]  :context :ad-hoc,
[backend]  :error
[backend]  "Invalid output: {:query {:breakout [[nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]], :order-by [[nil [nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]]]}}",
[backend]  :row_count 0,
[backend]  :running_time 0,
[backend]  :preprocessed nil,
[backend]  :ex-data
[backend]  {:type :metabase.util.malli.fn/invalid-output,
[backend]   :error
[backend]   {:schema [:ref :metabase.legacy-mbql.schema/Query],
[backend]    :value
[backend]    {:constraints {:max-results 10000, :max-results-bare-rows 2000},
[backend]     :middleware {:js-int-to-string? true, :userland-query? true, :add-default-userland-constraints? true},
[backend]     :user-parameters
[backend]     [{:type :category, :id "978782895", :target [:dimension [:field 352 nil]]}
[backend]      {:type :category, :id "-1186615977", :target [:dimension [:field 252 {:source-field 358}]]}],
[backend]     :info {:executed-by 1, :context :ad-hoc, :query-hash #object["[B" 0x6e56b4a6 "[B@6e56b4a6"]},
[backend]     :database 2,
[backend]     :type :query,
[backend]     :query
[backend]     {:aggregation [[:count]],
[backend]      :breakout
[backend]      [[:field
[backend]        350
[backend]        {:temporal-unit :minute,
[backend]         :base-type :type/Date,
[backend]         :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]],
[backend]      :source-table 41,
[backend]      :order-by
[backend]      [[:asc
[backend]        [:field
[backend]         350
[backend]         {:temporal-unit :minute,
[backend]          :base-type :type/Date,
[backend]          :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]]]}},
[backend]    :errors
[backend]    ({:path [0 0 :query 0 0 :breakout 0 0 0 :field 0 0 1 "options" 0 0 1 0],
[backend]      :in [:query :breakout 0 2],
[backend]      :schema
[backend]      [:fn {:error/message "Invalid :temporal-unit for the specified :base-type."} #object[metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_ 0x43fdf27a "metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_@43fdf27a"]],
[backend]      :value
[backend]      {:temporal-unit :minute,
[backend]       :base-type :type/Date,
[backend]       :metabase.query-processor.middleware.desugar/desugar-added-base-type true}}
[backend]     {:path [0 0 :query 0 0 :order-by 0 0 0 :asc 0 1 "field" 0 :field 0 0 1 "options" 0 0 1 0],
[backend]      :in [:query :order-by 0 1 2],
[backend]      :schema
[backend]      [:fn {:error/message "Invalid :temporal-unit for the specified :base-type."} #object[metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_ 0x43fdf27a "metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_@43fdf27a"]],
[backend]      :value
[backend]      {:temporal-unit :minute,
[backend]       :base-type :type/Date,
[backend]       :metabase.query-processor.middleware.desugar/desugar-added-base-type true}})},
[backend]   :humanized
[backend]   {:query
[backend]    {:breakout
[backend]     [[nil
[backend]       nil
[backend]       ["Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}"]]],
[backend]     :order-by
[backend]     [[nil
[backend]       [nil
[backend]        nil
[backend]        ["Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}"]]]]}},
[backend]   :schema [:ref :metabase.legacy-mbql.schema/Query],
[backend]   :value
[backend]   {:constraints {:max-results 10000, :max-results-bare-rows 2000},
[backend]    :middleware {:js-int-to-string? true, :userland-query? true, :add-default-userland-constraints? true},
[backend]    :user-parameters
[backend]    [{:type :category, :id "978782895", :target [:dimension [:field 352 nil]]}
[backend]     {:type :category, :id "-1186615977", :target [:dimension [:field 252 {:source-field 358}]]}],
[backend]    :info {:executed-by 1, :context :ad-hoc, :query-hash #object["[B" 0x6e56b4a6 "[B@6e56b4a6"]},
[backend]    :database 2,
[backend]    :type :query,
[backend]    :query
[backend]    {:aggregation [[:count]],
[backend]     :breakout
[backend]     [[:field
[backend]       350
[backend]       {:temporal-unit :minute,
[backend]        :base-type :type/Date,
[backend]        :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]],
[backend]     :source-table 41,
[backend]     :order-by
[backend]     [[:asc
[backend]       [:field
[backend]        350
[backend]        {:temporal-unit :minute,
[backend]         :base-type :type/Date,
[backend]         :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]]]}},
[backend]   :fn-name desugar},
[backend]  :data {:rows [], :cols []}}
[backend]
```

```
[backend] 2024-07-29 20:37:19,491 INFO metabase.query-analysis :: Performing query analysis for card 220
[backend] 2024-07-29 20:37:19,528 INFO metabase.query-analysis :: Performing query analysis for card 221
[backend] 2024-07-29 20:37:19,556 INFO metabase.query-analysis :: Performing query analysis for card 222
[backend] 2024-07-29 20:37:19,632 ERROR middleware.log :: POST /api/dashboard/save 500 224.3 ms (107 DB calls) {:metabase-user-id 1}
[backend] {:via
[backend]  [{:type clojure.lang.ExceptionInfo,
[backend]    :message
[backend]    "Error preprocessing query in clojure.lang.AFunction$1@3d0ea128: Invalid output: {:query {:breakout [[nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]], :order-by [[nil [nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]]]}}",
[backend]    :data
[backend]    {:fn #object[clojure.lang.AFunction$1 0x3d0ea128 "clojure.lang.AFunction$1@3d0ea128"],
[backend]     :query
[backend]     {:database 2,
[backend]      :info {:executed-by 1},
[backend]      :type :query,
[backend]      :query
[backend]      {:aggregation [[:count]],
[backend]       :breakout [[:field 350 {:temporal-unit :minute}]],
[backend]       :source-table 41,
[backend]       :order-by [[:asc [:field 350 {:temporal-unit :minute}]]]}},
[backend]     :type :qp},
[backend]    :at
[backend]    [metabase.query_processor.preprocess$fn__95624$_AMPERSAND_f__95625$fn__95626$fn__95627 invoke "preprocess.clj" 150]}
[backend]   {:type clojure.lang.ExceptionInfo,
[backend]    :message
[backend]    "Invalid output: {:query {:breakout [[nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]], :order-by [[nil [nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]]]}}",
[backend]    :data
[backend]    {:type :metabase.util.malli.fn/invalid-output,
[backend]     :error
[backend]     {:schema [:ref :metabase.legacy-mbql.schema/Query],
[backend]      :value
[backend]      {:database 2,
[backend]       :info {:executed-by 1},
[backend]       :type :query,
[backend]       :query
[backend]       {:aggregation [[:count]],
[backend]        :breakout
[backend]        [[:field
[backend]          350
[backend]          {:temporal-unit :minute,
[backend]           :base-type :type/Date,
[backend]           :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]],
[backend]        :source-table 41,
[backend]        :order-by
[backend]        [[:asc
[backend]          [:field
[backend]           350
[backend]           {:temporal-unit :minute,
[backend]            :base-type :type/Date,
[backend]            :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]]]}},
[backend]      :errors
[backend]      ({:path [0 0 :query 0 0 :breakout 0 0 0 :field 0 0 1 "options" 0 0 1 0],
[backend]        :in [:query :breakout 0 2],
[backend]        :schema
[backend]        [:fn {:error/message "Invalid :temporal-unit for the specified :base-type."} #object[metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_ 0x43fdf27a "metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_@43fdf27a"]],
[backend]        :value
[backend]        {:temporal-unit :minute,
[backend]         :base-type :type/Date,
[backend]         :metabase.query-processor.middleware.desugar/desugar-added-base-type true}}
[backend]       {:path [0 0 :query 0 0 :order-by 0 0 0 :asc 0 1 "field" 0 :field 0 0 1 "options" 0 0 1 0],
[backend]        :in [:query :order-by 0 1 2],
[backend]        :schema
[backend]        [:fn {:error/message "Invalid :temporal-unit for the specified :base-type."} #object[metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_ 0x43fdf27a "metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_@43fdf27a"]],
[backend]        :value
[backend]        {:temporal-unit :minute,
[backend]         :base-type :type/Date,
[backend]         :metabase.query-processor.middleware.desugar/desugar-added-base-type true}})},
[backend]     :humanized
[backend]     {:query
[backend]      {:breakout
[backend]       [[nil
[backend]         nil
[backend]         ["Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}"]]],
[backend]       :order-by
[backend]       [[nil
[backend]         [nil
[backend]          nil
[backend]          ["Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}"]]]]}},
[backend]     :schema [:ref :metabase.legacy-mbql.schema/Query],
[backend]     :value
[backend]     {:database 2,
[backend]      :info {:executed-by 1},
[backend]      :type :query,
[backend]      :query
[backend]      {:aggregation [[:count]],
[backend]       :breakout
[backend]       [[:field
[backend]         350
[backend]         {:temporal-unit :minute,
[backend]          :base-type :type/Date,
[backend]          :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]],
[backend]       :source-table 41,
[backend]       :order-by
[backend]       [[:asc
[backend]         [:field
[backend]          350
[backend]          {:temporal-unit :minute,
[backend]           :base-type :type/Date,
[backend]           :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]]]}},
[backend]     :fn-name desugar},
[backend]    :at [metabase.query_processor.middleware.desugar$fn__90654$fn__90657 invoke "desugar.clj" 50]}],
[backend]  :trace
[backend]  [[metabase.query_processor.middleware.desugar$fn__90654$fn__90657 invoke "desugar.clj" 50]
[backend]   [clojure.lang.Var invoke "Var.java" 384]
[backend]   [metabase.query_processor.preprocess$ensure_legacy$fn__95616 invoke "preprocess.clj" 64]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 154]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 408]
[backend]   [metabase.query_processor.preprocess$fn__95624$_AMPERSAND_f__95625$fn__95626$fn__95627 invoke "preprocess.clj" 134]
[backend]   [clojure.lang.PersistentVector reduce "PersistentVector.java" 343]
[backend]   [clojure.core$transduce invokeStatic "core.clj" 6947]
[backend]   [clojure.core$transduce invoke "core.clj" 6934]
[backend]   [metabase.query_processor.preprocess$fn__95624$_AMPERSAND_f__95625$fn__95626 invoke "preprocess.clj" 124]
[backend]   [metabase.query_processor.setup$fn__95589$_AMPERSAND_f__95590 invoke "setup.clj" 225]
[backend]   [metabase.query_processor.setup$fn__95589$fn__95594 invoke "setup.clj" 216]
[backend]   [metabase.query_processor.preprocess$fn__95624$_AMPERSAND_f__95625 invoke "preprocess.clj" 122]
[backend]   [metabase.query_processor.preprocess$fn__95624$fn__95639 invoke "preprocess.clj" 118]
[backend]   [metabase.query_processor.compile$fn__95672$_AMPERSAND_f__95673$fn__95674 invoke "compile.clj" 43]
[backend]   [metabase.query_processor.setup$fn__95589$_AMPERSAND_f__95590 invoke "setup.clj" 225]
[backend]   [metabase.query_processor.setup$fn__95589$fn__95594 invoke "setup.clj" 216]
[backend]   [metabase.query_processor.compile$fn__95672$_AMPERSAND_f__95673 invoke "compile.clj" 42]
[backend]   [metabase.query_processor.compile$fn__95672$fn__95677 invoke "compile.clj" 39]
[backend]   [metabase.driver.sql_jdbc.metadata$fn__110844$_AMPERSAND_f__110845$fn__110846 invoke "metadata.clj" 22]
[backend]   [metabase.query_processor.setup$fn__95581$_AMPERSAND_f__95582$fn__95583 invoke "setup.clj" 189]
[backend]   [metabase.query_processor.setup$fn__95571$_AMPERSAND_f__95572$fn__95573 invoke "setup.clj" 181]
[backend]   [metabase.query_processor.setup$fn__95561$_AMPERSAND_f__95562$fn__95563$fn__95564 invoke "setup.clj" 166]
[backend]   [metabase.driver$do_with_driver invokeStatic "driver.clj" 106]
[backend]   [metabase.driver$do_with_driver invoke "driver.clj" 101]
[backend]   [metabase.query_processor.setup$fn__95561$_AMPERSAND_f__95562$fn__95563 invoke "setup.clj" 165]
[backend]   [metabase.query_processor.setup$fn__95549$_AMPERSAND_f__95550$fn__95551$fn__95554 invoke "setup.clj" 151]
[backend]   [metabase.query_processor.store$fn__76049$_AMPERSAND_f__76050 invoke "store.clj" 171]
[backend]   [metabase.query_processor.store$fn__76049$fn__76053 invoke "store.clj" 151]
[backend]   [metabase.query_processor.store$fn__76049$_AMPERSAND_f__76050 invoke "store.clj" 160]
[backend]   [metabase.query_processor.store$fn__76049$fn__76053 invoke "store.clj" 151]
[backend]   [metabase.query_processor.setup$fn__95549$_AMPERSAND_f__95550$fn__95551 invoke "setup.clj" 150]
[backend]   [metabase.query_processor.setup$fn__95531$_AMPERSAND_f__95532$_AMPERSAND_f__95533 invoke "setup.clj" 128]
[backend]   [metabase.query_processor.setup$fn__95531$_AMPERSAND_f__95532$fn__95536 invoke "setup.clj" 122]
[backend]   [metabase.query_processor.setup$fn__95589$_AMPERSAND_f__95590 invoke "setup.clj" 232]
[backend]   [metabase.query_processor.setup$fn__95589$fn__95594 invoke "setup.clj" 216]
[backend]   [metabase.driver.sql_jdbc.metadata$fn__110844$_AMPERSAND_f__110845 invoke "metadata.clj" 20]
[backend]   [metabase.driver.sql_jdbc.metadata$fn__110844$fn__110854 invoke "metadata.clj" 15]
  [metabase.driver.sql_jdbc$eval111020$fn__111021 invoke "sql_jdbc.clj" 228]
[backend]   [clojure.lang.MultiFn invoke "MultiFn.java" 234]
[backend]   [metabase.query_processor.metadata$fn__96897$_AMPERSAND_f__96898 invoke "metadata.clj" 73]
[backend]   [metabase.query_processor.metadata$fn__96897$fn__96901 invoke "metadata.clj" 64]
[backend]   [metabase.query_processor.metadata$fn__96918$_AMPERSAND_f__96919 invoke "metadata.clj" 106]
[backend]   [metabase.query_processor.metadata$fn__96918$fn__96922 invoke "metadata.clj" 103]
[backend]   [metabase.query_processor.metadata$fn__96945$_AMPERSAND_f__96946 invoke "metadata.clj" 155]
[backend]   [metabase.query_processor.metadata$fn__96945$fn__96948 invoke "metadata.clj" 146]
[backend]   [metabase.models.dashboard$legacy_result_metadata_for_query invokeStatic "dashboard.clj" 472]
[backend]   [metabase.models.dashboard$legacy_result_metadata_for_query invoke "dashboard.clj" 468]
[backend]   [metabase.models.dashboard$save_card_BANG_$fn__106341 invoke "dashboard.clj" 486]
[backend]   [clojure.core$update invokeStatic "core.clj" 6232]
[backend]   [clojure.core$update invoke "core.clj" 6224]
[backend]   [metabase.models.dashboard$save_card_BANG_ invokeStatic "dashboard.clj" 486]
[backend]   [metabase.models.dashboard$save_card_BANG_ invoke "dashboard.clj" 474]
[backend]   [metabase.models.dashboard$save_transient_dashboard_BANG_$iter__106350__106354$fn__106355$fn__106356
[backend]    invoke
[backend]    "dashboard.clj"
[backend]    526]
[backend]   [metabase.models.dashboard$save_transient_dashboard_BANG_$iter__106350__106354$fn__106355 invoke "dashboard.clj" 525]
[backend]   [clojure.lang.LazySeq sval "LazySeq.java" 42]
[backend]   [clojure.lang.LazySeq seq "LazySeq.java" 51]
[backend]   [clojure.lang.RT seq "RT.java" 535]
[backend]   [clojure.core$seq__5467 invokeStatic "core.clj" 139]
[backend]   [clojure.core$map$fn__5935 invoke "core.clj" 2763]
[backend]   [clojure.lang.LazySeq sval "LazySeq.java" 42]
[backend]   [clojure.lang.LazySeq seq "LazySeq.java" 51]
[backend]   [clojure.lang.RT seq "RT.java" 535]
[backend]   [clojure.core$seq__5467 invokeStatic "core.clj" 139]
[backend]   [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 24]
[backend]   [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
[backend]   [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
[backend]   [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
[backend]   [clojure.core$reduce invokeStatic "core.clj" 6887]
[backend]   [clojure.core$reduce invoke "core.clj" 6869]
[backend]   [malli.core$_collection_schema$reify$reify__9032$fn__9033 invoke "core.cljc" 1224]
[backend]   [metabase.util.malli.registry$explainer$make_explainer__27422$schema_explainer__27423 invoke "registry.cljc" 47]
[backend]   [metabase.util.malli.registry$explain invokeStatic "registry.cljc" 54]
[backend]   [metabase.util.malli.registry$explain invoke "registry.cljc" 51]
[backend]   [metabase.util.malli.fn$validate invokeStatic "fn.clj" 152]
[backend]   [metabase.util.malli.fn$validate invoke "fn.clj" 150]
[backend]   [metabase.util.malli.fn$validate_input invokeStatic "fn.clj" 183]
[backend]   [metabase.util.malli.fn$validate_input invoke "fn.clj" 179]
[backend]   [metabase.models.dashboard_card$fn__82077$fn__82100 invoke "dashboard_card.clj" 209]
[backend]   [metabase.models.dashboard$add_dashcards_BANG_ invokeStatic "dashboard.clj" 428]
[backend]   [metabase.models.dashboard$add_dashcards_BANG_ invoke "dashboard.clj" 417]
[backend]   [metabase.models.dashboard$save_transient_dashboard_BANG_ invokeStatic "dashboard.clj" 524]
[backend]   [metabase.models.dashboard$save_transient_dashboard_BANG_ invoke "dashboard.clj" 504]
[backend]   [metabase.api.dashboard$fn__125662 invokeStatic "dashboard.clj" 988]
[backend]   [metabase.api.dashboard$fn__125662 invoke "dashboard.clj" 981]
[backend]   [compojure.core$wrap_response$fn__12079 invoke "core.clj" 160]
[backend]   [compojure.core$wrap_route_middleware$fn__12063 invoke "core.clj" 132]
[backend]   [compojure.core$wrap_route_info$fn__12068 invoke "core.clj" 139]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 151]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 152]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 152]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 152]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 152]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 152]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
  [metabase.server.middleware.auth$enforce_authentication$fn__117154 invoke "auth.clj" 18]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [compojure.core$make_context$handler__12159 invoke "core.clj" 290]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 300]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [clojure.lang.Var invoke "Var.java" 393]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 199]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 199]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 199]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [metabase.api.routes$fn__141985$fn__141986 invoke "routes.clj" 69]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [clojure.lang.AFn applyToHelper "AFn.java" 160]
[backend]   [clojure.lang.AFn applyTo "AFn.java" 144]
[backend]   [clojure.core$apply invokeStatic "core.clj" 667]
[backend]   [clojure.core$apply invoke "core.clj" 662]
[backend]   [metabase.server.routes$fn__142949$fn__142950 doInvoke "routes.clj" 73]
[backend]   [clojure.lang.RestFn invoke "RestFn.java" 436]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [compojure.core$make_context$handler__12159 invoke "core.clj" 290]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 300]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__12072 invoke "core.clj" 153]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 199]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 199]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 199]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [compojure.core$make_context$handler__12159 invoke "core.clj" 290]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 300]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091$f__12092$respond_SINGLEQUOTE___12093 invoke "core.clj" 197]
[backend]   [compojure.core$make_context$fn__12163 invoke "core.clj" 301]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [compojure.core$routes$fn__12091$f__12092 invoke "core.clj" 198]
[backend]   [compojure.core$routes$fn__12091 invoke "core.clj" 200]
[backend]   [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__117393 invoke "exceptions.clj" 107]
[backend]   [metabase.server.middleware.exceptions$catch_api_exceptions$fn__117390 invoke "exceptions.clj" 96]
[backend]   [metabase.server.middleware.log$log_api_call$fn__117625$fn__117626$fn__117627 invoke "log.clj" 236]
[backend]   [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
[backend]   [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
[backend]   [metabase.server.middleware.log$log_api_call$fn__117625$fn__117626 invoke "log.clj" 227]
[backend]   [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
[backend]   [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
[backend]   [metabase.server.middleware.log$log_api_call$fn__117625 invoke "log.clj" 226]
[backend]   [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__117199 invoke "browser_cookie.clj" 40]
[backend]   [metabase.server.middleware.security$add_security_headers$fn__117341 invoke "security.clj" 240]
[backend]   [ring.middleware.json$wrap_json_body$fn__143244 invoke "json.clj" 64]
[backend]   [metabase.server.middleware.offset_paging$handle_paging$fn__117660 invoke "offset_paging.clj" 49]
[backend]   [metabase.server.middleware.json$wrap_streamed_json_response$fn__71977 invoke "json.clj" 88]
[backend]   [ring.middleware.keyword_params$wrap_keyword_params$fn__143341 invoke "keyword_params.clj" 55]
[backend]   [ring.middleware.params$wrap_params$fn__143368 invoke "params.clj" 77]
[backend]   [metabase.server.middleware.misc$maybe_set_site_url$fn__80281 invoke "misc.clj" 60]
[backend]   [metabase.server.middleware.session$reset_session_timeout$fn__97321 invoke "session.clj" 568]
[backend]   [metabase.server.middleware.session$bind_current_user$fn__97279$fn__97280 invoke "session.clj" 462]
[backend]   [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 441]
[backend]   [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 424]
[backend]   [metabase.server.middleware.session$bind_current_user$fn__97279 invoke "session.clj" 461]
[backend]   [metabase.server.middleware.session$wrap_current_user_info$fn__97250 invoke "session.clj" 385]
[backend]   [metabase.analytics.sdk$bind_embedding_mw$bound_embedding__47970 invoke "sdk.clj" 31]
[backend]   [metabase.server.middleware.session$wrap_session_id$fn__97222 invoke "session.clj" 261]
[backend]   [metabase.server.middleware.auth$wrap_static_api_key$fn__117162 invoke "auth.clj" 32]
[backend]   [ring.middleware.cookies$wrap_cookies$fn__143156 invoke "cookies.clj" 200]
[backend]   [metabase.server.middleware.misc$add_content_type$fn__80263 invoke "misc.clj" 28]
[backend]   [metabase.server.middleware.misc$disable_streaming_buffering$fn__80289 invoke "misc.clj" 77]
[backend]   [ring.middleware.gzip$wrap_gzip$fn__143206 invoke "gzip.clj" 86]
[backend]   [metabase.server.middleware.request_id$wrap_request_id$fn__117675 invoke "request_id.clj" 9]
[backend]   [metabase.server.middleware.misc$bind_request$fn__80292 invoke "misc.clj" 94]
[backend]   [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__117698 invoke "ssl.clj" 41]
[backend]   [metabase.server$async_proxy_handler$fn__73033 invoke "server.clj" 77]
[backend]   [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
[backend]   [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
[backend]   [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
[backend]   [org.eclipse.jetty.server.Server handle "Server.java" 563]
[backend]   [org.eclipse.jetty.server.HttpChannel$RequestDispatchable dispatch "HttpChannel.java" 1598]
[backend]   [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 753]
[backend]   [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 501]
[backend]   [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 287]
[backend]   [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
[backend]   [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
[backend]   [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
[backend]   [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy runTask "AdaptiveExecutionStrategy.java" 421]
[backend]   [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy consumeTask "AdaptiveExecutionStrategy.java" 390]
[backend]   [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy tryProduce "AdaptiveExecutionStrategy.java" 277]
[backend]   [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy run "AdaptiveExecutionStrategy.java" 199]
[backend]   [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 411]
[backend]   [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 969]
[backend]   [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner doRunJob "QueuedThreadPool.java" 1194]
[backend]   [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1149]
[backend]   [java.lang.Thread run "Thread.java" 1570]],
[backend]  :cause
[backend]  "Invalid output: {:query {:breakout [[nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]], :order-by [[nil [nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]]]}}",
[backend]  :data
[backend]  {:type :metabase.util.malli.fn/invalid-output,
[backend]   :error
[backend]   {:schema [:ref :metabase.legacy-mbql.schema/Query],
[backend]    :value
[backend]    {:database 2,
[backend]     :info {:executed-by 1},
[backend]     :type :query,
[backend]     :query
[backend]     {:aggregation [[:count]],
[backend]      :breakout
[backend]      [[:field
[backend]        350
[backend]        {:temporal-unit :minute,
[backend]         :base-type :type/Date,
[backend]         :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]],
[backend]      :source-table 41,
[backend]      :order-by
[backend]      [[:asc
[backend]        [:field
[backend]         350
[backend]         {:temporal-unit :minute,
[backend]          :base-type :type/Date,
[backend]          :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]]]}},
[backend]    :errors
[backend]    ({:path [0 0 :query 0 0 :breakout 0 0 0 :field 0 0 1 "options" 0 0 1 0],
[backend]      :in [:query :breakout 0 2],
[backend]      :schema
[backend]      [:fn {:error/message "Invalid :temporal-unit for the specified :base-type."} #object[metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_ 0x43fdf27a "metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_@43fdf27a"]],
[backend]      :value
[backend]      {:temporal-unit :minute,
[backend]       :base-type :type/Date,
[backend]       :metabase.query-processor.middleware.desugar/desugar-added-base-type true}}
    {:path [0 0 :query 0 0 :order-by 0 0 0 :asc 0 1 "field" 0 :field 0 0 1 "options" 0 0 1 0],
[backend]      :in [:query :order-by 0 1 2],
[backend]      :schema
[backend]      [:fn {:error/message "Invalid :temporal-unit for the specified :base-type."} #object[metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_ 0x43fdf27a "metabase.legacy_mbql.schema$valid_temporal_unit_for_base_type_QMARK_@43fdf27a"]],
[backend]      :value
[backend]      {:temporal-unit :minute,
[backend]       :base-type :type/Date,
[backend]       :metabase.query-processor.middleware.desugar/desugar-added-base-type true}})},
[backend]   :humanized
[backend]   {:query
[backend]    {:breakout
[backend]     [[nil
[backend]       nil
[backend]       ["Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}"]]],
[backend]     :order-by
[backend]     [[nil
[backend]       [nil
[backend]        nil
[backend]        ["Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}"]]]]}},
[backend]   :schema [:ref :metabase.legacy-mbql.schema/Query],
[backend]   :value
[backend]   {:database 2,
[backend]    :info {:executed-by 1},
[backend]    :type :query,
[backend]    :query
[backend]    {:aggregation [[:count]],
[backend]     :breakout
[backend]     [[:field
[backend]       350
[backend]       {:temporal-unit :minute,
[backend]        :base-type :type/Date,
[backend]        :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]],
[backend]     :source-table 41,
[backend]     :order-by
[backend]     [[:asc
[backend]       [:field
[backend]        350
[backend]        {:temporal-unit :minute,
[backend]         :base-type :type/Date,
[backend]         :metabase.query-processor.middleware.desugar/desugar-added-base-type true}]]]}},
[backend]   :fn-name desugar},
[backend]  :message
[backend]  "Error preprocessing query in clojure.lang.AFunction$1@3d0ea128: Invalid output: {:query {:breakout [[nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]], :order-by [[nil [nil nil [\"Invalid :temporal-unit for the specified :base-type., got: {:temporal-unit :minute, :base-type :type/Date, :metabase.query-processor.middleware.desugar/desugar-added-base-type true}\"]]]]}}",
[backend]  :fn #object[clojure.lang.AFunction$1 0x3d0ea128 "clojure.lang.AFunction$1@3d0ea128"],
[backend]  :query
[backend]  {:database 2,
[backend]   :info {:executed-by 1},
[backend]   :type :query,
[backend]   :query
[backend]   {:aggregation [[:count]],
[backend]    :breakout [[:field 350 {:temporal-unit :minute}]],
[backend]    :source-table 41,
[backend]    :order-by [[:asc [:field 350 {:temporal-unit :minute}]]]}}}
[backend]
[backend] 2024-07-29 20:40:00,070 INFO task.refresh-slack-channel-user-cache :: Slack is not configured, not refreshing slack user/channel cache.
```

### Information about your Metabase installation

```JSON
- Metabase from master, commit hash 06d1ba2ae111e66253209c01c244d6379acfc6dcb1911fa9ab6012cec9ce52e5
```

### Severity

p1 - onboarding path 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/46249

In the reproduction step of the issue, we're generating a breakout on the `customer.create_date` column with `:minute` breakout, this is invalid because the base type of this column is `:type/Date`.

The temporal unit is inferred by the `metabase.xrays.automagic-dashboards.interesting/optimal-temporal-resolution` function that takes a field and uses its fingerprint info of datetime `earliest and lastest` to get a temporal unit.
The fix here is to guard this function from returning an invalid unit.

### How to test:
1. Create a db with this sql
```sql
CREATE TABLE shows (
    name TEXT,
    event_date DATE,
);

INSERT INTO shows (name, event_date)
VALUES ('taylor swift concert', '2024-07-31');

```
2. sync it and x-ray on the `shows` table
3. You should be able to save the x-ray successfully

### CODE REVIEW

File: src/metabase/xrays/automagic_dashboards/interesting.clj [hunk 1]
```diff
@@ -100,43 +100,49 @@
...
-      ;; e.g. if 3 hours > [duration between earliest and latest] then use `:minute` resolution
-      (condp u.date/greater-than-period-duration? (u.date/period-duration earliest latest)
-        (t/hours 3) :minute
-        (t/days 7) :hour
-        (t/months 6) :day
-        (t/years 10) :month
-        :year)
-      :day)))
+      (let [duration      (u.date/period-duration earliest latest)
+            greater-than? #(u.date/greater-than-period-duration? % duration)]
```
Comment (crisptrutski) [inline src/metabase/xrays/automagic_dashboards/interesting.clj:116]: Since we're comparing "in reverse", I would find it more natural to call this `less-than?`

File: src/metabase/xrays/automagic_dashboards/interesting.clj [hunk 2]
```diff
@@ -100,43 +100,49 @@
...
+        (cond
+         ;; e.g. if 3 hours > [duration between earliest and latest] then use `:minute` resolution
+         (and (or time? date-time?) (greater-than? (t/hours 3)))  :minute
+         (and (or time? date-time?) (greater-than? (t/days 7)))   :hour
+         (and (or date? date-time?) (greater-than? (t/months 6))) :day
+         (and (or date? date-time?) (greater-than? (t/years 10))) :month
+         (or date? date-time?)                                    :year
+         time?                                                    :hour))
```
Comment (crisptrutski) [inline src/metabase/xrays/automagic_dashboards/interesting.clj:124]: This log is quite dense and tangled, and would be hard and failure prone to extend.

A more declarative approach could keep the old logic in a helper method, say `optimal-temporal-resolution*`, and use a data-driven approach to keep the values within a type determined range:

```clojure
(def time-resolutions [:minute :hour :day :month :year])

(def resolution-idx
  (into {} (map-indexed (fn [idx res] [res idx]) time-resolutions)))

(def type-constraints
  {:type/Time     [nil (resolution-idx :hour)]
   :type/Date     [(resolution-idx :day) nil]
   :type/DateTime [nil nil]})

(defn optimal-temporal-resolution [type field]
  (let [res               (optimal-temporal-resolution* field)
        res-idx           (resolution-idx res)
        [min-idx max-idx] (type-constraints type)
        constrained-idx   (cond-> res-idx
                            min-idx (max min-idx)
                            max-idx (min max-idx))]
    (time-resolutions constrained-idx)))
```

What do you think?

**Review by crisptrutski — APPROVED** [review]

File: src/metabase/xrays/automagic_dashboards/interesting.clj (hunk 2 above)
Comment (qnkhuat) [reply src/metabase/xrays/automagic_dashboards/interesting.clj]: tbh, I find that a bit complicated and rely on the order time resolutions.
I updated the code by using a helper to check whether it can use a resolution [4ac6d32](https://github.com/metabase/metabase/pull/46317/commits/4ac6d32b606ae5f5a9a329680c56dec1376681a6) I think this make the code not much difference from the original.

Wdyt?

File: src/metabase/xrays/automagic_dashboards/interesting.clj (hunk 1 above)
Comment (qnkhuat) [reply src/metabase/xrays/automagic_dashboards/interesting.clj:115]: yes 21e7926103

**Review by crisptrutski — APPROVED** [review]
