### PR TITLE
Fix in-progress selection in the date range picker

### LINKED ISSUE #51994: Selected first date is not highlighted in the date range picker when trying to change the range
### Describe the bug

https://www.loom.com/share/e88e070e82274685afd7a89af9f1dda9

### To Reproduce

1. Go to the query builder
2. Start adding Specific dates filter
3. See the range preselected
4. Click on any date inside or outside the current range (except for the first date of it)
5. See that the range selection is removed, while the first date of the old range still is shown in blue and the date you clicked is not highlighted

### Expected behavior

The previous range highlight should be removed completely and the clicked date should be highlighted as the start date of the new range.
This worked fine in the dashboard filter component before it was replaced by the QB component.

### Logs

_No response_

### Information about your Metabase installation

```JSON
27c6fe4
```

### Severity

Misleading, frequent

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/51994

How to verify:
- Open a dashboard with a `date/range` or `date/all-options` widget
- Select a date range
- Now start to select a new date range, starting from a date inside the current range
- The new start date should be highlighted before the selection is completed, i.e. before the end date is clicked.

Screenshot 2025-01-14 at 16 05 58

### CODE REVIEW

File: frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx [hunk 1]
```diff
@@ -92,7 +97,7 @@ export function DateRangePickerBody({
       )}
       <DatePicker
         type="range"
-        value={[startDate, hasEndDate ? endDate : null]}
+        value={inProgressDateRange ?? value}
```
Comment (kamilmielnik) [inline frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx:100]: I think we should disable the "Update filter" button if range selection is in progress.
It will submit the previous valid selection, not the current in-progress one.

**Review by kamilmielnik — APPROVED** [review]

File: frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx (hunk 1 above)
Comment (ranquild) [reply frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePickerBody/DateRangePickerBody.tsx:100]: @mngr maybe this is something we want to follow-up with. I'm personally not sure if that would be an improvement since I don't expect most people wouldn't face issues with the existing approach and the disabled button can only bring more confusion.
