### PR TITLE
Fix `:postgres` filtering by current quarter; remove a few unneeded casts in PG SQL output

### LINKED ISSUE #20683: Error when filtering date by current quarter in Postgres
**Describe the bug**
When filtering by current quarter on a Postgres database the following error appears:
`ERROR: invalid input syntax for type interval: "1 quarter" Position: 1550`

**Logs**
[metabase.log](https://github.com/metabase/metabase/files/8119658/metabase.log)

**To Reproduce**
1. Create any regular question 
2. Create a filter using a date and filter by current quarter

**Expected behavior**
Filter by current quarter is actually filtering instead of giving an error

**Screenshots**
image

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "4.9.43-17.39.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.14"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-17",
      "tag": "v0.42.1",
      "branch": "release-x.42.x",
      "hash": "629f4de"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
Only way to work around this right now is to create native queries. We use quarterly queries quite often.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #20683

Postgres doesn't support `interval 'n quarter'` forms which we were generating in this case. Fixed by instead generating `<n * 3> month` forms.

Added cross-driver test to make sure this works for all drivers.

Also did a few small tweaks to make simplify the SQL we generate to avoid unneeded casts

### CODE REVIEW

File: src/metabase/driver/postgres.clj [hunk 1]
```diff
@@ -263,6 +267,10 @@
 ;;; |                                           metabase.driver.sql impls                                            |
 ;;; +----------------------------------------------------------------------------------------------------------------+
 
+(defmethod sql.qp/current-datetime-honeysql-form :postgres
+  [_driver]
+  (hx/with-database-type-info :%now "timestamptz"))
```
Comment (camsaul) [inline src/metabase/driver/postgres.clj:272]: Not part of this fix but Postgres `now()` returns a `timestamp with time zone` so I added this impl to include the type info so we generate `now()` in SQL instead of `cast(now() AS timestamp)` which is not necessary in Postgres land.

File: src/metabase/driver/postgres.clj [hunk 2]
```diff
@@ -362,7 +370,7 @@
       (pg-conversion identifier :numeric)
 
       (some? nfc-path)
-      (json-query identifier nfc-path)
+      (json-query nfc-path)
```
Comment (camsaul) [inline src/metabase/driver/postgres.clj:373]: Also unrelated. Removed unused arg (thanks `clj-kondo` and Flycheck)

File: src/metabase/driver/postgres.clj [hunk 3]
```diff
@@ -44,9 +44,13 @@
...
-  [_ hsql-form amount unit]
-  (hx/+ (->timestamp hsql-form)
-        (hsql/raw (format "(INTERVAL '%s %s')" amount (name unit)))))
+  [driver hsql-form amount unit]
+  ;; Postgres doesn't support quarter in intervals (#20683)
+  (if (= unit :quarter)
+    (recur driver hsql-form (* 3 amount) :month)
+    (let [hsql-form (->timestamp hsql-form)]
+      (-> (hx/+ hsql-form (hsql/raw (format "(INTERVAL '%s %s')" amount (name unit))))
+          (hx/with-type-info (hx/type-info hsql-form))))))
```
Comment (camsaul) [inline src/metabase/driver/postgres.clj:53]: The `with-type-info` is also not strictly part of this fix but this tweak lets us avoid more unneeded `cast(... AS timestamp)` casts since a `timestamp` or interchangeable plus a date interval doesn't need to be casted again after adding the interval. Probably not a noticeable difference performance wise but it simplifies the SQL we generate which is still a win.

**Review by flamber — APPROVED** [review]
