### PR TITLE
Alert schedule in email template

### LINKED ISSUE #18115: Whitelabel includes `Metabase` in the subject for Alerts
**Describe the bug**
Whitelabel with a different name still includes `Metabase` in the subject for Alerts.

**To Reproduce**
1. Admin > Settings > Whitelabel > change Application Name to something custom
2. Create a question and setup an alert
3. When the alert is received, the email subject says `Metabase alert: <name of the question>`
4. Using Pulses, the email subject says `Pulse: <name of the pulse>`

**Expected behavior**
Not include `Metabase`, or use the custom whitelabelled name instead.

**Information about your Metabase Installation:**
Tested 1.38.0 thru 1.40.5

**Additional context**
Originally EE605 - https://github.com/metabase/metabase-enterprise/issues/605

### PR DESCRIPTION
**Pull request by noahmoss**
Small final additions to the new alert template

* Adds the alert schedule, with timezone, to alert emails per the design
* Adds back the line about the goal being reached, for alerts with goals

### CODE REVIEW

File: src/metabase/email/messages.clj [hunk 1]
```diff
@@ -513,25 +513,63 @@
             (when alert-condition-map
               {:alertCondition (get alert-condition-map (pulse->alert-condition-kwd alert))})))))
 
+(defn- schedule-hour-text
+  [{hour :schedule_hour}]
+  (str (if (= hour 0)
```
Comment (jeff303) [inline src/metabase/email/messages.clj:518]: This is fairly simple, but I still wonder if it would be better to use Java date time formatting code to do it?  Like get a `LocalTime` instance from the hour, then format with [`h a`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html)?

File: src/metabase/email/messages.clj [hunk 2]
```diff
@@ -513,25 +513,63 @@
...
+            (driver/report-timezone))))
+
 (defn- alert-context
   "Context that is applicable only to the actual alert template (not alert management templates)"
-  [alert]
+  [alert channel]
   (let [{card-id :id, card-name :name} (first-card alert)]
     {:title    card-name
      :titleUrl (url/card-url card-id)
+     :alertSchedule (alert-schedule-text channel)
```
Comment (jeff303) [inline src/metabase/email/messages.clj:560]: nit: in this map, the rest of the values are currently aligned.  I'm fine with either aligning or not, but keep it consistent within each map.

File: src/metabase/email/messages.clj (hunk 1 above)
Comment (noahmoss) [reply src/metabase/email/messages.clj:518]: sure, done

**Review by jeff303 — APPROVED** [review]
