### PR TITLE
Fix failed to cast datetime in mongo

### LINKED ISSUE #18733: MongoDB date filtering not working for ISO-8601 strings
**Describe the bug**
When using a mongo DB, a casted date field derived from JSON is not filterable by date. It is filterable by if the value exists however.

**Logs**
[Metabase.log](https://github.com/metabase/metabase/files/7435246/Metabase.log)
[console.log](https://github.com/metabase/metabase/files/7435255/console.log)

Please LMK if any other logs would be helpful, not quite sure I see any errors

**To Reproduce**
1. Add a Mongo DB
2. add a Table with an `Info` column
3. add the json below to the column
3. Sync fields, so `Info: started`  is discoved
4. Date Cast as seen in screen shot at bottom
5. Attempt to filter on date
#### JSON being Parsed
```
{
  "started": "2021-10-22 21:33:37",
  "category": "file",
  "package": "exe",
  "source_url": null,
  "ended": "2021-10-22 21:37:35",
  "shrike_refer": null,
  "shrike_msg": null,
  "custom": "",
  "duration": 238,
  "route": "none",
  "shrike_sid": null,
  "shrike_url": null,
  "parent_id": null,
  "id": 1,
  "parent_sample": {
    "source_url": null,
    "md5": "7a456d32d3eb4a1bb245aa77d0a99abf",
    "parent": null,
    "file_type": "Zip archive data, at least v6.3 to extract",
    "file_size": 87934,
    "ssdeep": null,
    "sha1": "8e3a840487b709381ca3d30a30970a44d454905b",
    "sha512": "ed7083892396e9a1429e4eb1a5e7d639fdc06870ce2bf7c22ac8965b03e51ac67c7af6ea4e52efe9ea6ba32bf586275faf6c25405f633486750e9d2a16e02a33",
    "id": 1,
    "crc32": "BD199F57",
    "sha256": "88d363988f58ed1364800ae1000e2d0ae7e630e4bbf87269011ffbb08ef03962"
  },
  "machine": {
    "id": 1,
    "status": "stopping",
    "name": "Biscotti-WIN10",
    "label": "Biscotti-WIN10",
    "manager": "Proxmox",
    "started_on": "2021-10-22 21:33:37",
    "shutdown_on": "2021-10-22 21:37:35"
  },
  "tlp": "",
  "user_id": 0,
  "options": {},
  "timeout": true,
  "version": "2.2-CAPE",
  "has_cents_rules": false
}
```

**Expected behavior**
Expecting results to filter based on date

**Screenshots**

image

image

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 94.0.4606.81 (Official Build) (64-bit)
- Your operating system: Windows 10
- Your databases:  MongoDB
- Metabase version: 0.41.0
- Metabase hosting environment: Kubernetes
- Metabase internal database: MSQL (AWS RDS)

**Severity**
This is preventing us from making actionable dashboards for our SOC, so it would be very helpful to get this resolved

**Additional context**
Field is set to cast the date ISO 8601 -> Datetime; casting does seem to be working
Database is a CAPE MongoDB, which is a lot of large JSON
image

### PR DESCRIPTION
**Pull request by qnkhuat**
Fix #18733 by adding `Coercion/ISO8601->DateTime` for Mongo.

This does not add support for casting to `date` or `time` because Mongo doesn't have those types natively.

We also need a follow-up for FE to remove the ability select cast ISO8601 to Date or Time because Mongo doesn't support these types.

### CODE REVIEW

File: test/metabase/query_processor_test/alternative_date_test.clj [hunk 1]
```diff
@@ -215,16 +229,33 @@
...
+
+     (testing "mongo only supports datetime"
+       (mt/test-drivers #{:mongo}
+         (is (= [[1 "foo" (t/instant "2004-10-19T10:23:54Z")]
+                 [2 "bar" (t/instant "2012-10-19T10:23:54Z")]
+                 [3 "baz" (t/instant "2008-10-19T00:00:00Z")]]
+                (mt/rows (mt/dataset mongo-dates
+                                     (qp/process-query
+                                      (assoc (mt/mbql-query dates)
+                                             :middleware {:format-rows? false})))))))))
```
Comment (camsaul) [inline test/metabase/query_processor_test/alternative_date_test.clj:242]: Mongo-only tests should go in `modules/drivers/mongo/test/`

File: test/metabase/query_processor_test/alternative_date_test.clj [hunk 2]
```diff
@@ -215,16 +229,33 @@
...
         (mt/test-drivers (disj (sql-jdbc.tu/sql-jdbc-drivers) :oracle :sparksql)
-          (is (= 1
-                 (count (mt/rows (mt/dataset string-times
-                                   (mt/run-mbql-query times
-                                     {:filter   [:= [:datetime-field $ts :day] "2008-10-19"]}))))))))
-      (testing "a date field"
+         (is (= 1
+                (count (mt/rows (mt/dataset string-times
+                                  (mt/run-mbql-query times
+                                    {:filter   [:= [:datetime-field $ts :day] "2008-10-19"]}))))))))
```
Comment (camsaul) [inline test/metabase/query_processor_test/alternative_date_test.clj:257]: I'm confused, why doesn't this work for MongoDB. Why do we need a separate test

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 3]
```diff
@@ -132,10 +133,27 @@
...
+      ;; mongo only supports datetime
+      (isa? coercion :Coercion/ISO8601->DateTime)
+      {"$dateFromString" {:dateString field-name
+                          :onError    field-name}}
+
+
+      (isa? coercion :Coercion/ISO8601->Date)
+      (throw (ex-info (tru "Driver Mongo does not support {0}" coercion)
+                      {:type              qp.error-type/unsupported-feature
+                       :coercion-strategy coercion}))
```
Comment (camsaul) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:148]: I'm confused. [`$dateFromString` can definitely parse stuff in `YYYY-MM-DD` format.(https://www.mongodb.com/docs/v5.0/reference/operator/aggregation/dateFromString/)

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 4]
```diff
@@ -132,10 +133,27 @@
...
+
+
+      (isa? coercion :Coercion/ISO8601->Time)
```
Comment (camsaul) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:151]: `$dateFromString` can accept an optional `:format` parameter so it seems like you should be able to parse times as well.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 3 above)
Comment (qnkhuat) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:148]: yes but it requires the source to have `YYYY-MM-DD` format and the resulted data type is still a Datetype.

Maybe this is the question of what does cast `ISO8601->Date` mean? 
1. does it mean it takes a field with ISO8601 format (either DateTime or Date format) and uses it as a `Date` type?
2. Or it means taking a field with ISO8601 with Date format

I'm inclined to believe it is the 1st, because it makes cast consistency with SQL => We can have a text column like `2022-05-13T09:57:17+00:00`, and we could use it as a Date or Datetime by using cast.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 4 above)
Comment (qnkhuat) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:151]: The `$dateFromString` function requires a Date component.

I.e if we have a source column like `09:09:30` and try to parse it with `%H:%M%S` format, it'll give an error 

```sh
sample> db.nestedData.aggregate([{ $project: { date: { $dateFromString: { dateString: "$Info.started", format: "%H:%M:%S" } } } }])
MongoServerError: PlanExecutor error during aggregation :: caused by :: an incomplete date/time string has been found, with elements missing: "09:09:30"
```

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 3 above)
Comment (qnkhuat) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:148]: but I could see supporting the `YYYY-MM-DD` format would be useful though.

**Comment by dpsutton** [comment]
@qnkhuat is there anything you are waiting on? I'm wondering if i can help you get this merged or if you are waiting on some help with anything?

File: test/metabase/query_processor_test/alternative_date_test.clj (hunk 2 above)
Comment (qnkhuat) [reply test/metabase/query_processor_test/alternative_date_test.clj]: it was failing for Mongo because mong doesn't support casting for datetime and time, and this test is selecting all columns which contain those casting.

I create another similar test that only select the `ts` column for this.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 3 above)
Comment (qnkhuat) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:152]: FWIW, I consulted this with @luizarakaki and he agrees mongo shouldn't have support casting to `date` and `time`.

https://metaboat.slack.com/archives/C03SHMZ266R/p1662980879849149

**Review by dpsutton — APPROVED** [review]

File: test/metabase/query_processor_test/alternative_date_test.clj [hunk 5]
```diff
@@ -225,15 +228,33 @@
...
                               (assoc (mt/mbql-query times)
-                                     :middleware {:format-rows? false})))))))))
+                                     :middleware {:format-rows? false}))))))))
+
+      (testing "mongo only supports datetime"
+        (mt/test-drivers #{:mongo}
+          (is (= [[(t/instant "2004-10-19T10:23:54Z")]
+                  [(t/instant "2008-10-19T10:23:54Z")]
+                  [(t/instant "2012-10-19T10:23:54Z")]]
+               (mt/rows (mt/dataset string-times
```
Comment (camsaul) [inline test/metabase/query_processor_test/alternative_date_test.clj:238]: It's slightly preferrable to put `mt/dataset` around the entire test because then it adds `testing` context. But it's not that important. For next time tho you might want to consider doing it

File: test/metabase/query_processor_test/alternative_date_test.clj [hunk 6]
```diff
@@ -225,15 +228,33 @@
                  (mt/rows (mt/dataset string-times
                             (qp/process-query
                               (assoc (mt/mbql-query times)
-                                     :middleware {:format-rows? false})))))))))
+                                     :middleware {:format-rows? false}))))))))
+
+      (testing "mongo only supports datetime"
+        (mt/test-drivers #{:mongo}
```
Comment (camsaul) [inline test/metabase/query_processor_test/alternative_date_test.clj:234]: I know the other tests above are doing it this way but we actually have `mt/test-driver` for just one specific driver.

```suggestion
        (mt/test-driver :mongo
```

Altho maybe having two different ways of doing it actually doesn't make sense... 🤔 

Either way that's the pattern we generally use for testing just one driver

File: test/metabase/query_processor_test/alternative_date_test.clj [hunk 7]
```diff
@@ -225,15 +228,33 @@
...
           (is (= 1
                  (count (mt/rows (mt/dataset string-times
                                    (mt/run-mbql-query times
-                                     {:filter   [:= [:datetime-field $ts :day] "2008-10-19"]}))))))))
+                                     {:filter   [:= [:datetime-field $ts :day] "2008-10-19"]})))))))
+        (mt/test-drivers #{:mongo}
+          (is (= 1
+                 (count (mt/rows (mt/dataset string-times
+                                   (mt/run-mbql-query times
+                                     {:filter   [:= [:datetime-field $ts :day] "2008-10-19"]
```
Comment (camsaul) [inline test/metabase/query_processor_test/alternative_date_test.clj:256]: `:datetime-field` is legacy MBQL syntax, you shouldn't write any new tests with it. If you touch a test with it, it's probably a good idea to update it 

```suggestion
                                     {:filter   [:= [:field %ts {:temporal-unit :day}] "2008-10-19"]
```

Actually you could use the MBQL shorthand and do

```suggestion
                                     {:filter   [:= !day.ts "2008-10-19"]
```

which doesn't win points for obviousness but it sure is easy to write.

**Review by camsaul — APPROVED** [review]
I think this is good enough to merge at this point. I don't want to let the perfect be the enemy of the good and I think this is a clear improvement over it not working at all. But I would like to note a couple things about it to keep in mind for the future:

1. Hardcoding driver names in tests is definitely not something I like, but seeing how all the existing tests were already doing that I think it's okay to do it here for now. The main reason is that we want third-party driver authors to be able to run our test suite against their drivers without having to maintain a fork of all of our tests. That means in a perfect world none of our tests would have special casing for any drivers -- they would instead rely on a bunch of test extension methods to decide which version of the test to run. In this case, there would be some sort of method like `tx/driver-only-supports-parsing-datetimes?` and you'd check that and then run the appropriate version of the test. Third-party driver authors could add a method for that if they needed to.

2. Any time you consider adding a test extension method like `tx/driver-only-supports-parsing-datetimes?`, you should stop and ask yourself if that information is better captured as a driver `supports?` feature flag. I can definitely see the fact that Mongo doesn't support casting to String -> date or whatever being a feature flag. Why? Maybe the frontend client can use that information, that MongoDB doesn't support parsing a date from a string, and not even let you do it in the GUI expression editor, for example. It's much better to prevent someone from doing something wrong in the first place than to let them do something wrong and then return an error.

Does that make sense? If so can you please open a follow-on issue to add feature flag(s) for these sorts of things. I don't think we need to do that right now since it's going to require frontend work to be able to respect it, but it's something we should try to address at some point.

One last note, I think that error message could be improved a little bit, and it would be nice to add a test for it too 💪

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 8]
```diff
@@ -136,10 +137,27 @@
...
 
-      :else field-name)))
+      ;; mongo only supports datetime
+      (isa? coercion :Coercion/ISO8601->DateTime)
+      {"$dateFromString" {:dateString field-name
+                          :onError    field-name}}
+
+
+      (isa? coercion :Coercion/ISO8601->Date)
+      (throw (ex-info (tru "Driver Mongo does not support {0}" coercion)
```
[the remark this answers is not in the document]
Comment (camsaul) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:150]: Also, I'm not sure this is a great error message. It's not user-friendly to have an error message like

```
Driver Mongo does not support :Coercion/ISO8601->Date
```

Our users do not know what `:Coercion/ISO8601->Date` means, and they'd have to guess.

How about something like

```suggestion
      (throw (ex-info (tru "MongoDB does not support parsing strings as dates. Try parsing to a datetime instead.")
```

[the remark this answers is not in the document]
Comment (qnkhuat) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:150]: Yep, that's easier to understand! I updated it.

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj [hunk 9]
```diff
@@ -136,10 +137,27 @@
...
+      ;; mongo only supports datetime
+      (isa? coercion :Coercion/ISO8601->DateTime)
+      {"$dateFromString" {:dateString field-name
+                          :onError    field-name}}
+
+
+      (isa? coercion :Coercion/ISO8601->Date)
+      (throw (ex-info (tru "MongoDB does not support parsing strings as dates. Try parsing to a datetime instead")
+                      {:type              qp.error-type/unsupported-feature
+                       :coercion-strategy coercion}))
```
Comment (calherries) [inline modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:152]: What do think about composing our own parser for dates with MongoDB expressions? e.g.

```suggestion
      (isa? coercion :Coercion/ISO8601->DateTime)
      {"$dateFromString" {:dateString field-name
                          :onError    field-name}}

      (isa? coercion :Coercion/ISO8601->Date)
      {"$dateFromString" {:dateString {"$substr" [field-name 0 10]}
                          :onError    field-name}}
```

Comment (qnkhuat) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:152]: I think we shouldn't support `Coercion/ISO8601->Date` because even if we could parse the `datestring` it's still a `datetime` type in mongoDb.

In all of our SQL drivers when `Coercion/ISO8601->Date` we convert it to a `date` column and we should keep the behavior consistence even that means we don't support for Mongo.

File: test/metabase/query_processor_test/alternative_date_test.clj [hunk 10]
```diff
@@ -225,21 +228,57 @@
...
+       (testing "a datetime field"
+         ;; TODO: why does this fail on oracle? gives a NPE
+         (mt/test-drivers (disj (sql-jdbc.tu/sql-jdbc-drivers) :oracle :sparksql)
+           (is (= 1
+                  (->> (mt/run-mbql-query times
+                         {:filter [:= !day.ts "2008-10-19"]})
+                       mt/rows
+                       count))))
+
+         (mt/test-drivers #{:mongo}
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply test/metabase/query_processor_test/alternative_date_test.clj:267]: I think I'll change it back to `test-drivers` actually, it's basically the same but iff we decided to remove `test-driver` in the future we don't have  to change too much.

File: test/metabase/query_processor_test/alternative_date_test.clj [hunk 11]
```diff
@@ -225,21 +228,57 @@
...
+                         {:filter [:= !day.ts "2008-10-19"]
+                          :fields [$ts]})
+                       mt/rows
+                       count)))))
+
+       (testing "a date field"
+         (mt/test-drivers (disj (sql-jdbc.tu/sql-jdbc-drivers) :oracle :sparksql)
+           (is (= 1
+                  (->> (mt/run-mbql-query times
+                         {:filter [:= [:datetime-field $d :day] "2008-10-19"]})
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply test/metabase/query_processor_test/alternative_date_test.clj:279]: will do. Thanks!

File: test/metabase/query_processor_test/alternative_date_test.clj [hunk 12]
```diff
@@ -225,21 +228,57 @@
...
+                   (mt/rows (qp/process-query
+                              (assoc (mt/mbql-query times
+                                                    {:fields [$ts]})
+                                     :middleware {:format-rows? false})))))
+            (is (thrown-with-msg?
+                  clojure.lang.ExceptionInfo
+                  #"MongoDB does not support parsing strings as dates. Try parsing to a datetime instead"
+                  (qp/process-query
+                    (mt/mbql-query times
+                                   {:fields [$d]}))))
```
[the remark this answers is not in the document]
Comment (qnkhuat) [reply test/metabase/query_processor_test/alternative_date_test.clj]: did it in 1ec2c9cfd0

File: modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj (hunk 9 above)
Comment (calherries) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:152]: I understood the purpose of coercion strategies is to be able to convert between base types and effective types. Effective types don't need to be represented in the DB.

See the docstring for the `metabase.types` namespace:
https://github.com/metabase/metabase/blob/aa30353a164a6febb6c932ba65208cf023d62eba/shared/src/metabase/types.cljc#L20

The example given in that docstring is for a DB that doesn't support `:type/DateTime`. It explains how we can still support `:Coercion/ISO8601->DateTime` with the following types:
- base_type: :type/Text
- effective_type: :type/DateTime
- a coercion strategy of :Coercion/ISO8601->DateTime

Comment (qnkhuat) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:152]: I worry that if we add support for `date` and our users might run into correctness problems because `2000/01/01 00:00:00` is not exactly = `2000/01/01`.

I can't think of an example right now but I'd imagine solving those problems in Mongo would not be easy, 
The worse part is we'll have to solve it because we already offered the feature.

So I'd rather avoid putting us in that position.

Comment (calherries) [reply modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj:152]: Makes sense, I also haven't fully resolved the implications of doing this.

My thinking was that `2000/01/01 00:00:00` is isomorphic to `2000/01/01` in every case except formatting on the frontend, where the effective_type is used. That assumption could easily be wrong. Let's leave it for now.

**Comment by flamber** [comment]
@metabase-bot backport release-x.45.x

**Comment by flamber** [comment]
@qnkhuat You'll need to manually backport this.
