### PR TITLE
Fix implicit field refs for cases when the source-field is coming from a join

### LINKED ISSUE #46845: Notebook editor can show the same columns multiple times
### Describe the bug

image

### To Reproduce

1. New > Questions
2. Join Reviews on Product ID = Product ID
3. Visualize
4. Open filter modal

Product columns are listed twice

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
master, a4f1223d1d
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/46845
Closes https://linear.app/metabase/issue/QUE-1286/implicitly-joinable-column-groups-cannot-be-distinguished

Implicit join fix:
1. Handle implicit joins via joins (this PR)
2. Handle implicit joins via cards (follow-up PR)

Changes:
- Adds `source-field-join-alias` to ref opts for cases when the source field is coming from a joined table
- Uses this info in `lib.equality`
- Updates `add_implicit_joins` middleware to generate correct joins in this case

### CODE REVIEW

File: src/metabase/query_processor/middleware/add_implicit_joins.clj [hunk 1]
```diff
@@ -30,63 +30,78 @@
...
+          target-field-ids   (into #{} (keep :fk-target-field-id) fk-fields)
+          target-fields      (when (seq target-field-ids)
+                               (lib.metadata/bulk-metadata-or-throw (qp.store/metadata-provider) :metadata/column target-field-ids))
+          target-table-ids   (into #{} (keep :table-id) target-fields)]
       ;; this is for cache-warming purposes.
       (when (seq target-table-ids)
         (lib.metadata/bulk-metadata-or-throw (qp.store/metadata-provider) :metadata/table target-table-ids))
-      (for [{fk-name :name, fk-field-id :id, fk-ident :ident, pk-id :fk-target-field-id} fk-fields
-            :when                                                                        pk-id]
+      (for [{fk-field-id :fk-field-id, fk-join-alias :fk-join-alias} fk-field-infos
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_implicit_joins.clj:72]:
```suggestion
      (for [{:keys [fk-field-id fk-join-alias]} fk-field-infos
```

File: src/metabase/query_processor/middleware/add_implicit_joins.clj [hunk 2]
```diff
@@ -30,63 +30,78 @@
...
+          (-> (merge {:source-table  source-table
+                      :alias         alias-for-join
+                      :ident         (lib/implicit-join-clause-ident fk-ident)
+                      :fields        :none
+                      :strategy      :left-join
+                      :condition     [:= [:field fk-field-id (when fk-join-alias {:join-alias fk-join-alias})]
+                                      [:field pk-id {:join-alias alias-for-join}]]
+                      :fk-field-id   fk-field-id}
+                     (when fk-join-alias
+                       {:fk-join-alias fk-join-alias}))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_implicit_joins.clj:89]: Could use `m/assoc-some` instead of `merge`.

File: src/metabase/query_processor/middleware/add_implicit_joins.clj [hunk 3]
```diff
@@ -30,63 +30,78 @@
...
               (vary-meta assoc ::needs [:field fk-field-id nil])))))))
 
-(defn- implicitly-joined-fields->joins
+(mu/defn- implicitly-joined-fields->joins :- [:maybe [:sequential JoinInfo]]
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_implicit_joins.clj:92]:
```suggestion
(mu/defn- implicitly-joined-fields->joins :- [:sequential JoinInfo]
```
or make the `let` a `when-let`, or add a `not-empty` after `into`.

File: src/metabase/query_processor/middleware/add_implicit_joins.clj [hunk 4]
```diff
@@ -30,63 +30,78 @@
...
-                                    (:source-field opts))))
-                           (filter integer?)
-                           set
+                                    {:fk-field-id (:source-field opts), :fk-join-alias (:source-field-join-alias opts)})))
+                           distinct
                            not-empty)]
-     (fk-ids->join-infos fk-field-ids))))
+    (->> (fk-field-infos->join-infos k-field-infos)
+         distinct
+         (into []))))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_implicit_joins.clj:104]:
```suggestion
         (into [] (distinct)))))
```

File: src/metabase/query_processor/middleware/add_implicit_joins.clj [hunk 5]
```diff
@@ -30,63 +30,78 @@
...
-   (let [fk-field-ids (->> field-clauses-with-source-field
+  (let [k-field-infos (->> field-clauses-with-source-field
                            (map (fn [clause]
                                   (lib.util.match/match-one clause
                                     [:field (id :guard integer?) (opts :guard (every-pred :source-field (complement :join-alias)))]
-                                    (:source-field opts))))
-                           (filter integer?)
-                           set
+                                    {:fk-field-id (:source-field opts), :fk-join-alias (:source-field-join-alias opts)})))
+                           distinct
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_implicit_joins.clj:100]: This could be a `(sequence (comp (map ...) (distinct) field-clauses-with-source-field)` if we wanted to generate a bit less garbage. (Not important.)

File: src/metabase/query_processor/middleware/add_implicit_joins.clj [hunk 6]
```diff
@@ -104,42 +119,47 @@
...
   [form]
-  ;; Build a map of FK Field ID -> alias used for IMPLICIT joins. Only implicit joins have `:fk-field-id`
+  ;; Build a map of [[FkFieldInfo]] -> alias used for IMPLICIT joins. Only implicit joins have `:fk-field-id`
   (into {}
-        (comp (map (fn [{:keys [fk-field-id], join-alias :alias}]
-                     (when fk-field-id
-                       [fk-field-id join-alias])))
-              ;; only keep the first alias for each FK Field ID
-              (m/distinct-by first))
+        (map (fn [{:keys [fk-field-id fk-join-alias], join-alias :alias}]
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_implicit_joins.clj:128]: I would strongly prefer using `keep` here
```suggestion
        (keep (fn [{:keys [fk-field-id fk-join-alias], join-alias :alias}]
```

File: src/metabase/query_processor/middleware/add_implicit_joins.clj [hunk 7]
```diff
@@ -104,42 +119,47 @@
...
+               (when fk-field-id
+                 [(merge {:fk-field-id fk-field-id}
+                         (when fk-join-alias
+                           {:fk-join-alias fk-join-alias})) join-alias])))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_implicit_joins.clj:132]:
```suggestion
                 [(m/assoc-some {:fk-field-id fk-field-id} :fk-join-alias fk-join-alias)
                  join-alias])))
```

**Review by metamben — APPROVED** [review]
LGTM, just some nits.
