### PR TITLE
Fix missing snippet create button

### LINKED ISSUE #57441: Add snippet icon not visible
### Describe the bug

Add snippet icon not visible.

### To Reproduce

1. Open a Metabase instance with at least one snippet, create a snippet if none exist (New SQL Question > Snippets > Create Snippet)
2. When reviewing the list of snippets, the add button is not visible, but it is still clickable.

Image

➕ should be visibile to right of ... menu. It is clickable to create a new snippet but not visible

### Expected behavior

expect the add snippet button to be visible

### Logs

n/a

### Information about your Metabase installation

```JSON
Metabase v1.54.4 and v1.54.5
```

### Severity

P1: missing common functionality, does not match docs

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/57441

Converts the popover to use Mantine.
Also fixes a similar issue for the snippet search button.

To verify
1. New -> Native question
2. Click the snippet icon
3. There should be a + icon in the top-right corner
4. It should allow you to create a new snippet
5. Create enough snippets to make the search button show up (you need at least 15)
6. Click the search button and type something 
 
Screenshot 2025-05-01 at 12 34 53
Screenshot 2025-05-01 at 12 36 15

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx [hunk 1]
```diff
@@ -164,70 +161,46 @@ class SnippetSidebarInner extends React.Component {
...
-                      [S.isHidden]: showSearch,
-                    })}
-                    name="search"
-                    size={HEADER_ICON_SIZE}
-                    onClick={this.showSearch}
-                  />
-                )}
+                {snippets.length >= MIN_SNIPPETS_FOR_SEARCH &&
+                  (showSearch ? (
+                    <Button variant="subtle" onClick={this.hideSearch} p="sm">
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx:166]: - These buttons should be square, now they're 34x40
- These buttons give its container the height - let's give the container some padding instead. Buttons should not cause the container (with title) to grow

File: frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx [hunk 2]
```diff
@@ -164,70 +161,46 @@ class SnippetSidebarInner extends React.Component {
...
-                  <Icon
-                    className={cx(S.SearchSnippetIcon, {
-                      [S.isHidden]: showSearch,
-                    })}
-                    name="search"
-                    size={HEADER_ICON_SIZE}
-                    onClick={this.showSearch}
-                  />
-                )}
+                {snippets.length >= MIN_SNIPPETS_FOR_SEARCH &&
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx:164]: The seach input is cut off. In this screenshots the search query is "jj", but first "j" looks like "i"

image

File: frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx [hunk 3]
```diff
@@ -58,7 +55,7 @@ class SnippetSidebarInner extends React.Component {
       className={S.SidebarFooter}
       onClick={() => this.setState({ showArchived: true })}
     >
-      <Icon className={S.SidebarIcon} name="view_archive" size={ICON_SIZE} />
+      <Icon className={S.SidebarIcon} name="view_archive" />
```
Comment (kamilmielnik) [inline frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx:58]: "Archived snippets" header is styled differently than "Snippets" header: [snippets](https://github.com/user-attachments/assets/ae753cd2-7765-47d1-bf69-781deeef08e0) vs [archived snippets](https://github.com/user-attachments/assets/6876655a-8eba-4280-9043-e8e97e76b26b) (font, padding)

File: e2e/support/helpers/e2e-native-editor-helpers.ts [hunk 4]
```diff
@@ -162,3 +162,16 @@ export const NativeEditor = {
...
 };
+
+export function createSnippet({
+  name,
+  content,
+}: {
+  name: string;
+  content: string;
+}) {
+  cy.request("POST", "/api/native-query-snippet", {
```
Comment (kamilmielnik) [inline e2e/support/helpers/e2e-native-editor-helpers.ts:173]: Let's keep api helpers in `e2e/support/helpers/api`

**Review by kamilmielnik — COMMENTED** [review]
Works fine. I left some styling comments

File: e2e/support/helpers/api/createSnippet.ts [hunk 5]
```diff
@@ -0,0 +1,12 @@
+export function createSnippet({
+  name,
+  content,
+}: {
+  name: string;
+  content: string;
+}) {
```
Comment (kamilmielnik) [inline e2e/support/helpers/api/createSnippet.ts:7]:
```suggestion
}): Cypress.Chainable<Cypress.Response<NativeQuerySnippet>> {
```

**Review by kamilmielnik — APPROVED** [review]
