### PR TITLE
Render table header when dataset is empty

### LINKED ISSUE #37300: Editing metadata of a model is not possible when the model returns an empty recordset
### Describe the bug

It is not possible to edit the metadata of a model when the model does not return any records, because the metadata editor won't display the column header in this case.

### To Reproduce

1. Create or update a model, and set filters so that the model does not return any records
2. Switch to Metadata
3. No results! is displayed, and the header will be hidden which makes it impossible to select a column to edit its metadata.
image

### Expected behavior

A column header should still be present.

### Logs

_No response_

### Information about your Metabase installation

```JSON
1.48.1
```

### Severity

Probably minor as it is not a common practice to edit models returning no data. I don't know a workaround though.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by romeovs**
Closes https://github.com/metabase/metabase/issues/37300

### Description

This PR allows the visualization to render its own empty message, thus allowing it to render other parts for the visualization too.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> Orders
2. Add a filter to make the result set empty, ie. Tax < 0
3. Switch to Metadata by clicking the button in the header
4. The table headers should be visible and clickable

### Demo

Screenshot 2024-11-18 at 22 47 14

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx [hunk 1]
```diff
@@ -1137,6 +1151,8 @@ class TableInteractive extends Component {
         0,
       ) + (gutterColumn ? SIDEBAR_WIDTH : 0);
 
+    const isEmpty = rows === null || rows.length === 0;
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx:1154]: Safer: 

```suggestion
    const isEmpty = rows == null || rows.length === 0;
```

**Review by kamilmielnik — COMMENTED** [review]
LGTM :+1: 
Not approving yet because I think it needs some DashViz eyes first.

**Review by kulyk — APPROVED** [review]

**Review by kamilmielnik — APPROVED** [review]
