### PR TITLE
Check email test errors for javax.mail.AuthenticationFailedException

### LINKED ISSUE #19662: office365.com and "Sorry, something went wrong. Please try again. Error: : Exception reading response: Read timed out"
**Describe the bug**

We're getting an error when we try to use a office365 mail account in the metabase mail settings. In general it looks very similar to this issue: https://github.com/metabase/metabase/issues/4272. 

- This issue affects only office365 accounts, other tested mail provider are working fine.
- We also tried different office365 mail accounts and ensured that a MFA is not enabled. 
- A telnet test (`telnet smtp.office365.com 587`) works fine, so no firewall issues 
- We also tried STARTTLS and TLS and NONE
- We used the official [configuration from microsoft](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353) and also tried alternative ports like 25, 465, & 587

**Screenshots**

image

**Logs**

```log
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: 2022-01-13 14:30:35,411 ERROR metabase.email :: Fehler beim Test der SMTP Verbindung
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: javax.mail.AuthenticationFailedException: ;
Jan 13 14:30:35 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011javax.mail.MessagingException: Exception reading response;
Jan 13 14:30:35 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011java.net.SocketTimeoutException: Read timed out
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:942)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:858)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:762)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at javax.mail.Service.connect(Service.java:342)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020$fn__55024$fn__55027.invoke(email.clj:158)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020$fn__55024.invoke(email.clj:157)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020.invoke(email.clj:141)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55072$test_smtp_connection__55077$fn__55081.invoke(email.clj:205)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55072$test_smtp_connection__55077.invoke(email.clj:189)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.api.email$fn__66853.invokeStatic(email.clj:79)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.api.email$fn__66853.invoke(email.clj:68)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_response$fn__32066.invoke(core.clj:160)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_middleware$fn__32050.invoke(core.clj:132)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_info$fn__32055.invoke(core.clj:139)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:151)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.auth$enforce_authentication$fn__70354.invoke(auth.clj:14)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$handler__32106.invoke(core.clj:289)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:299)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.api.routes$fn__79831$fn__79834.invoke(routes.clj:56)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at clojure.lang.AFn.applyToHelper(AFn.java:160)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at clojure.lang.AFn.applyTo(AFn.java:144)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at clojure.core$apply.invokeStatic(core.clj:667)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at clojure.core$apply.invoke(core.clj:662)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.routes$fn__79976$fn__79977.doInvoke(routes.clj:57)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at clojure.lang.RestFn.invoke(RestFn.java:436)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$handler__32106.invoke(core.clj:289)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:299)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.routes$fn__79964$fn__79966.invoke(routes.clj:41)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77436.invoke(exceptions.clj:98)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.exceptions$catch_api_exceptions$fn__77433.invoke(exceptions.clj:86)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432$fn__80433.invoke(log.clj:209)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432.invoke(log.clj:201)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at toucan.db$_do_with_call_counting.invoke(db.clj:209)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431.invoke(log.clj:200)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__83644.invoke(browser_cookie.clj:30)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.security$add_security_headers$fn__59281.invoke(security.clj:147)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.json$wrap_json_body$fn__82788.invoke(json.clj:62)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.json$wrap_streamed_json_response$fn__82806.invoke(json.clj:98)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.offset_paging$handle_paging$fn__59305.invoke(offset_paging.clj:42)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at ring.middleware.keyword_params$wrap_keyword_params$fn__83911.invoke(keyword_params.clj:55)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at ring.middleware.params$wrap_params$fn__83927.invoke(params.clj:69)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$maybe_set_site_url$fn__34077.invoke(misc.clj:59)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$bind_current_user$fn__44978$fn__44979.invoke(session.clj:257)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:238)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:230)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$bind_current_user$fn__44978.invoke(session.clj:256)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$wrap_current_user_info$fn__44965.invoke(session.clj:216)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$wrap_session_id$fn__44951.invoke(session.clj:162)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.auth$wrap_api_key$fn__70362.invoke(auth.clj:27)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at ring.middleware.cookies$wrap_cookies$fn__83831.invoke(cookies.clj:216)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$add_content_type$fn__34060.invoke(misc.clj:27)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$disable_streaming_buffering$fn__34085.invoke(misc.clj:76)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at ring.middleware.gzip$wrap_gzip$fn__83873.invoke(gzip.clj:86)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$bind_request$fn__34088.invoke(misc.clj:93)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83660.invoke(ssl.clj:38)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server$async_proxy_handler$fn__80204.invoke(server.clj:71)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.Server.handle(Server.java:516)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at java.lang.Thread.run(Thread.java:748)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: Caused by: javax.mail.MessagingException: Exception reading response;
Jan 13 14:30:35 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011java.net.SocketTimeoutException: Read timed out
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2476)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.simpleCommand(SMTPTransport.java:2406)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport$LoginAuthenticator.doAuth(SMTPTransport.java:983)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:924)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011... 126 more
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: Caused by: java.net.SocketTimeoutException: Read timed out
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.socketRead0(Native Method)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.read(SocketInputStream.java:171)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.read(SocketInputStream.java:141)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1341)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:957)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:102)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:100)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2456)
Jan 13 14:30:35 ip-10-13-21-72 bash[678]: #011... 129 more
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: 2022-01-13 14:30:39,451 INFO middleware.exceptions :: Die Anfrage wurde vorzeitig abgebrochen.
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: 2022-01-13 14:30:39,457 ERROR metabase.email :: Fehler beim Test der SMTP Verbindung
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: javax.mail.AuthenticationFailedException: ;
Jan 13 14:30:39 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011javax.mail.MessagingException: Exception reading response;
Jan 13 14:30:39 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011java.net.SocketTimeoutException: Read timed out
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:942)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:858)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:762)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at javax.mail.Service.connect(Service.java:342)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020$fn__55024$fn__55027.invoke(email.clj:158)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020$fn__55024.invoke(email.clj:157)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020.invoke(email.clj:141)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55047$guess_smtp_security__55052$fn__55053$fn__55054.invoke(email.clj:182)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at clojure.core$some.invokeStatic(core.clj:2705)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at clojure.core$some.invoke(core.clj:2696)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55047$guess_smtp_security__55052$fn__55053.invoke(email.clj:180)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55047$guess_smtp_security__55052.invoke(email.clj:171)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55072$test_smtp_connection__55077$fn__55081.invoke(email.clj:208)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55072$test_smtp_connection__55077.invoke(email.clj:189)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.api.email$fn__66853.invokeStatic(email.clj:79)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.api.email$fn__66853.invoke(email.clj:68)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_response$fn__32066.invoke(core.clj:160)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_middleware$fn__32050.invoke(core.clj:132)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_info$fn__32055.invoke(core.clj:139)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:151)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.auth$enforce_authentication$fn__70354.invoke(auth.clj:14)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$handler__32106.invoke(core.clj:289)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:299)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.api.routes$fn__79831$fn__79834.invoke(routes.clj:56)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at clojure.lang.AFn.applyToHelper(AFn.java:160)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at clojure.lang.AFn.applyTo(AFn.java:144)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at clojure.core$apply.invokeStatic(core.clj:667)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at clojure.core$apply.invoke(core.clj:662)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.routes$fn__79976$fn__79977.doInvoke(routes.clj:57)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at clojure.lang.RestFn.invoke(RestFn.java:436)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$handler__32106.invoke(core.clj:289)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:299)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.routes$fn__79964$fn__79966.invoke(routes.clj:41)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77436.invoke(exceptions.clj:98)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.exceptions$catch_api_exceptions$fn__77433.invoke(exceptions.clj:86)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432$fn__80433.invoke(log.clj:209)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432.invoke(log.clj:201)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at toucan.db$_do_with_call_counting.invoke(db.clj:209)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431.invoke(log.clj:200)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__83644.invoke(browser_cookie.clj:30)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.security$add_security_headers$fn__59281.invoke(security.clj:147)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.json$wrap_json_body$fn__82788.invoke(json.clj:62)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.json$wrap_streamed_json_response$fn__82806.invoke(json.clj:98)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.offset_paging$handle_paging$fn__59305.invoke(offset_paging.clj:42)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at ring.middleware.keyword_params$wrap_keyword_params$fn__83911.invoke(keyword_params.clj:55)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at ring.middleware.params$wrap_params$fn__83927.invoke(params.clj:69)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$maybe_set_site_url$fn__34077.invoke(misc.clj:59)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$bind_current_user$fn__44978$fn__44979.invoke(session.clj:257)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:238)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:230)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$bind_current_user$fn__44978.invoke(session.clj:256)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$wrap_current_user_info$fn__44965.invoke(session.clj:216)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$wrap_session_id$fn__44951.invoke(session.clj:162)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.auth$wrap_api_key$fn__70362.invoke(auth.clj:27)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at ring.middleware.cookies$wrap_cookies$fn__83831.invoke(cookies.clj:216)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$add_content_type$fn__34060.invoke(misc.clj:27)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$disable_streaming_buffering$fn__34085.invoke(misc.clj:76)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at ring.middleware.gzip$wrap_gzip$fn__83873.invoke(gzip.clj:86)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$bind_request$fn__34088.invoke(misc.clj:93)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83660.invoke(ssl.clj:38)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server$async_proxy_handler$fn__80204.invoke(server.clj:71)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.Server.handle(Server.java:516)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at java.lang.Thread.run(Thread.java:748)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: Caused by: javax.mail.MessagingException: Exception reading response;
Jan 13 14:30:39 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011java.net.SocketTimeoutException: Read timed out
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2476)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.simpleCommand(SMTPTransport.java:2406)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport$LoginAuthenticator.doAuth(SMTPTransport.java:983)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:924)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011... 131 more
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: Caused by: java.net.SocketTimeoutException: Read timed out
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.socketRead0(Native Method)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.read(SocketInputStream.java:171)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.read(SocketInputStream.java:141)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1341)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:957)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:102)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:100)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2456)
Jan 13 14:30:39 ip-10-13-21-72 bash[678]: #011... 134 more
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: 2022-01-13 14:30:44,046 ERROR metabase.email :: Fehler beim Test der SMTP Verbindung
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: javax.mail.AuthenticationFailedException: ;
Jan 13 14:30:44 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011javax.mail.MessagingException: Exception reading response;
Jan 13 14:30:44 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011java.net.SocketTimeoutException: Read timed out
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:942)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:858)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:762)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at javax.mail.Service.connect(Service.java:342)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020$fn__55024$fn__55027.invoke(email.clj:158)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020$fn__55024.invoke(email.clj:157)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020.invoke(email.clj:141)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55047$guess_smtp_security__55052$fn__55053$fn__55054.invoke(email.clj:182)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.core$some.invokeStatic(core.clj:2705)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.core$some.invoke(core.clj:2696)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55047$guess_smtp_security__55052$fn__55053.invoke(email.clj:180)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55047$guess_smtp_security__55052.invoke(email.clj:171)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55072$test_smtp_connection__55077$fn__55081.invoke(email.clj:208)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55072$test_smtp_connection__55077.invoke(email.clj:189)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.api.email$fn__66853.invokeStatic(email.clj:79)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.api.email$fn__66853.invoke(email.clj:68)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_response$fn__32066.invoke(core.clj:160)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_middleware$fn__32050.invoke(core.clj:132)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_info$fn__32055.invoke(core.clj:139)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:151)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.auth$enforce_authentication$fn__70354.invoke(auth.clj:14)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$handler__32106.invoke(core.clj:289)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:299)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.api.routes$fn__79831$fn__79834.invoke(routes.clj:56)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.lang.AFn.applyToHelper(AFn.java:160)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.lang.AFn.applyTo(AFn.java:144)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.core$apply.invokeStatic(core.clj:667)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.core$apply.invoke(core.clj:662)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.routes$fn__79976$fn__79977.doInvoke(routes.clj:57)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.lang.RestFn.invoke(RestFn.java:436)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$handler__32106.invoke(core.clj:289)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:299)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.routes$fn__79964$fn__79966.invoke(routes.clj:41)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77436.invoke(exceptions.clj:98)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.exceptions$catch_api_exceptions$fn__77433.invoke(exceptions.clj:86)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432$fn__80433.invoke(log.clj:209)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432.invoke(log.clj:201)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at toucan.db$_do_with_call_counting.invoke(db.clj:209)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431.invoke(log.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__83644.invoke(browser_cookie.clj:30)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.security$add_security_headers$fn__59281.invoke(security.clj:147)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.json$wrap_json_body$fn__82788.invoke(json.clj:62)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.json$wrap_streamed_json_response$fn__82806.invoke(json.clj:98)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.offset_paging$handle_paging$fn__59305.invoke(offset_paging.clj:42)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at ring.middleware.keyword_params$wrap_keyword_params$fn__83911.invoke(keyword_params.clj:55)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at ring.middleware.params$wrap_params$fn__83927.invoke(params.clj:69)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$maybe_set_site_url$fn__34077.invoke(misc.clj:59)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$bind_current_user$fn__44978$fn__44979.invoke(session.clj:257)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:238)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:230)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$bind_current_user$fn__44978.invoke(session.clj:256)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$wrap_current_user_info$fn__44965.invoke(session.clj:216)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$wrap_session_id$fn__44951.invoke(session.clj:162)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.auth$wrap_api_key$fn__70362.invoke(auth.clj:27)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at ring.middleware.cookies$wrap_cookies$fn__83831.invoke(cookies.clj:216)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$add_content_type$fn__34060.invoke(misc.clj:27)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$disable_streaming_buffering$fn__34085.invoke(misc.clj:76)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at ring.middleware.gzip$wrap_gzip$fn__83873.invoke(gzip.clj:86)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$bind_request$fn__34088.invoke(misc.clj:93)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83660.invoke(ssl.clj:38)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server$async_proxy_handler$fn__80204.invoke(server.clj:71)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.Server.handle(Server.java:516)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at java.lang.Thread.run(Thread.java:748)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: Caused by: javax.mail.MessagingException: Exception reading response;
Jan 13 14:30:44 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011java.net.SocketTimeoutException: Read timed out
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2476)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.simpleCommand(SMTPTransport.java:2406)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport$LoginAuthenticator.doAuth(SMTPTransport.java:983)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:924)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011... 131 more
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: Caused by: java.net.SocketTimeoutException: Read timed out
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.socketRead0(Native Method)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.read(SocketInputStream.java:171)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at java.net.SocketInputStream.read(SocketInputStream.java:141)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1341)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:957)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:102)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:100)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2456)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011... 134 more
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: 2022-01-13 14:30:44,555 ERROR metabase.email :: Fehler beim Test der SMTP Verbindung
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: javax.mail.MessagingException: Could not connect to SMTP host: smtp.office365.com, port: 587;
Jan 13 14:30:44 ip-10-13-21-72 bash[678]:   nested exception is:
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2212)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at javax.mail.Service.connect(Service.java:342)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020$fn__55024$fn__55027.invoke(email.clj:158)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020$fn__55024.invoke(email.clj:157)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55015$test_smtp_settings__55020.invoke(email.clj:141)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55047$guess_smtp_security__55052$fn__55053$fn__55054.invoke(email.clj:182)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.core$some.invokeStatic(core.clj:2705)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.core$some.invoke(core.clj:2696)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55047$guess_smtp_security__55052$fn__55053.invoke(email.clj:180)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55047$guess_smtp_security__55052.invoke(email.clj:171)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55072$test_smtp_connection__55077$fn__55081.invoke(email.clj:208)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.email$fn__55072$test_smtp_connection__55077.invoke(email.clj:189)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.api.email$fn__66853.invokeStatic(email.clj:79)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.api.email$fn__66853.invoke(email.clj:68)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_response$fn__32066.invoke(core.clj:160)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_middleware$fn__32050.invoke(core.clj:132)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_info$fn__32055.invoke(core.clj:139)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:151)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.auth$enforce_authentication$fn__70354.invoke(auth.clj:14)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$handler__32106.invoke(core.clj:289)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:299)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.api.routes$fn__79831$fn__79834.invoke(routes.clj:56)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.lang.AFn.applyToHelper(AFn.java:160)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.lang.AFn.applyTo(AFn.java:144)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.core$apply.invokeStatic(core.clj:667)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.core$apply.invoke(core.clj:662)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.routes$fn__79976$fn__79977.doInvoke(routes.clj:57)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at clojure.lang.RestFn.invoke(RestFn.java:436)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$handler__32106.invoke(core.clj:289)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$make_context$fn__32110.invoke(core.clj:299)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.routes$fn__79964$fn__79966.invoke(routes.clj:41)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at compojure.core$routes$fn__32078.invoke(core.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77436.invoke(exceptions.clj:98)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.exceptions$catch_api_exceptions$fn__77433.invoke(exceptions.clj:86)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432$fn__80433.invoke(log.clj:209)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432.invoke(log.clj:201)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at toucan.db$_do_with_call_counting.invoke(db.clj:209)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.log$log_api_call$fn__80431.invoke(log.clj:200)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__83644.invoke(browser_cookie.clj:30)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.security$add_security_headers$fn__59281.invoke(security.clj:147)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.json$wrap_json_body$fn__82788.invoke(json.clj:62)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.json$wrap_streamed_json_response$fn__82806.invoke(json.clj:98)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.offset_paging$handle_paging$fn__59305.invoke(offset_paging.clj:42)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at ring.middleware.keyword_params$wrap_keyword_params$fn__83911.invoke(keyword_params.clj:55)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at ring.middleware.params$wrap_params$fn__83927.invoke(params.clj:69)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$maybe_set_site_url$fn__34077.invoke(misc.clj:59)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$bind_current_user$fn__44978$fn__44979.invoke(session.clj:257)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:238)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:230)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$bind_current_user$fn__44978.invoke(session.clj:256)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$wrap_current_user_info$fn__44965.invoke(session.clj:216)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.session$wrap_session_id$fn__44951.invoke(session.clj:162)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.auth$wrap_api_key$fn__70362.invoke(auth.clj:27)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at ring.middleware.cookies$wrap_cookies$fn__83831.invoke(cookies.clj:216)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$add_content_type$fn__34060.invoke(misc.clj:27)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$disable_streaming_buffering$fn__34085.invoke(misc.clj:76)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at ring.middleware.gzip$wrap_gzip$fn__83873.invoke(gzip.clj:86)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.misc$bind_request$fn__34088.invoke(misc.clj:93)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83660.invoke(ssl.clj:38)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server$async_proxy_handler$fn__80204.invoke(server.clj:71)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.Server.handle(Server.java:516)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at java.lang.Thread.run(Thread.java:748)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:455)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:184)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1392)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1300)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
Jan 13 14:30:44 ip-10-13-21-72 bash[678]: #011... 130 more
Jan 13 14:30:45 ip-10-13-21-72 bash[678]: 2022-01-13 14:30:45,064 WARN api.email :: Problem connecting to mail server: : Exception reading response: Read timed out
Jan 13 14:30:45 ip-10-13-21-72 bash[678]: 2022-01-13 14:30:45,068 DEBUG middleware.log :: #033[31mPUT /api/email 400 13,7 s (0 DB-Aufrufe)
Jan 13 14:30:45 ip-10-13-21-72 bash[678]: {:message "Sorry, something went wrong. Please try again. Error: : Exception reading response: Read timed out"}
Jan 13 14:30:45 ip-10-13-21-72 bash[678]: #033[0m
```

**Information about your Metabase Installation:**

- Your operating system: Ubuntu 20.04.3 LTS
- Your databases: Postgres
- Metabase version: v0.41.5
- Metabase hosting environment: Jar-file on Ubuntu (EC2 Amazon)

**Severity**
It blocks our user management setup.

### LINKED ISSUE #23918: Wrong username/password on Office365 for email settings has misleading error
Incorrect username/password values for Office365 email settings returns a misleading error message:

```clojure
{:host "smtp.office365.com"
 :user "some@person.com"
 :pass "badpassword"
 :port 587
 :security :starttls
 :sender-name ""
 :sender "local@localmb.com"
 :reply-to [""]}
```

Yields the UI message 
> Sorry, something went wrong. Please try again. Error: : Exception reading response: Read timed out

On the backend we have an error message like:
```clojure
;; nested errors
{:type javax.mail.AuthenticationFailedException
 :message ""
 :at [com.sun.mail.smtp.SMTPTransport$Authenticator authenticate "SMTPTransport.java" 942]}
{:type javax.mail.MessagingException
 :message "Exception reading response"
 :at [com.sun.mail.smtp.SMTPTransport readServerResponse "SMTPTransport.java" 2476]}
{:type java.net.SocketTimeoutException
 :message "Read timed out"
 :at [sun.nio.ch.NioSocketImpl timedRead "NioSocketImpl.java" 283]}
```

So the message presented to the user is a "Read timed out" message nested inside of a `javax.mail.AuthenticationFailedException` which has no message. We should identify that this class indicates authentication failed and present a better error message to the user.

See `humanize-error-messages` in `metabase.api.email` namespace.

### PR DESCRIPTION
**Pull request by dpsutton**
fixes #23918 (and with #23925 fixes #19662)

Authing with Office365 led to a less-than-great user experience. If you
type in the wrong username or password, we would display an unhelpful
message:

> Sorry, something went wrong. Please try again. Error::Exception
reading response.Read timed out.

This is an error from an inner nested exception which looks like:
```clojure
(javax.mail.AuthenticationFailedException.
 "" ;; Office365 returns auth exception with no message so we only saw "Read timed out" prior
 (javax.mail.MessagingException.
  "Exception reading response"
  (java.net.SocketTimeoutException. "Read timed out")))
```

We didn't get any message from the AuthenticationFailedException so our
humanization strategy only went on the underlying "Read timed out". Now
we can check against the error class and use that information.

#### Before

image

#### After
image

#### Recreate:

give some invalid Office365 credentials:
- smtp host: smtp.office365.com
- smtp port: 587
- username: make up anything, I used `some@person.com`
- password: the world is your oyster here

Attempt to save those credentials. Before this change it seems like perhaps we don't work well with office365 (particularly if you don't know you mistyped your password or if you are hitting #23919 (which sends the obfuscated password on edits rather than what you think is the saved password)). Before this change you get a cryptic timeout error. After this change you get highlighted username and password fields.

### CODE REVIEW

File: src/metabase/api/email.clj [hunk 1]
```diff
@@ -31,9 +31,16 @@
                                 :email-smtp-port "Wrong host or port"}}
           creds-error {:errors {:email-smtp-username "Wrong username or password"
                                 :email-smtp-password "Wrong username or password"}}
-          message     (str/join ": " (map ex-message (u/full-exception-chain error)))]
-          (log/warn "Problem connecting to mail server:" message)
-      (condp re-find message
+          exceptions  (u/full-exception-chain error)
+          message     (str/join ": " (map ex-message exceptions))
+          check       (fn check [regex|exception-class [m es]]
```
Comment (camsaul) [inline src/metabase/api/email.clj:36]: I have nothing against using pipes in symbol names but I have no idea what this is supposed to mean. Is `regex|exception-class` a regex pattern that you pipe the name of `exception-class` into to see if it matches something? That's my best guess. Maybe this is worth a comment

Comment (camsaul) [reply src/metabase/api/email.clj:36]: Oh I get it now. It means `regex-or-exception-class`. I only figured it out by reading the code which I think is a sign that it's not the greatest variable name. I'm generally a fan of fancy characters in symbol names because we can -- I've put `₁` and `°` in names in the codebase in the past but eventually removed them after other people whined about them -- but I think we should make sure their meaning is obvious.

I think `x|y` is a neat convention but if this is the only place we're using it it's not much of a convention. So maybe we should hate fun and just call this `regex-or-exception-class`. Just so no one else gets super confused.

Comment (camsaul) [reply src/metabase/api/email.clj:36]: Other observation: `check` is a little bit terse. Check _what_? `m` and `es` are cryptic. Is `m` supposed to be a message? 

I probably sound like a broken record but code is write-once, read-many so making these variable names a little longer makes the code a lot easier to understand

**Review by camsaul — APPROVED** [review]
Overall this LGTM but I spent 90% of my time reviewing this PR trying to decipher the variable names to figure out what they meant. Do with that information what you will.

File: src/metabase/api/email.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/api/email.clj:36]: ha sorry. I've seen that as a standard convention in the past. I'll rename it so its not confusing.

Comment (dpsutton) [reply src/metabase/api/email.clj]: updated. thanks for the pointers.
