### PR TITLE
Hide auth config pages from setting managers

### LINKED ISSUE #27055: Authentication admin page doesn't show auth methods as active for non-admins with settings access
**To Reproduce**
1. As an admin, create a new non-admin user and add them to a new permissions group
2. Go to Permissions -> Application and give the new group settings access
3. Go to Settings -> Authentication and set up any auth method. The easiest is Google Auth; just use a random Client ID.
4. Log in as the non-admin user and go to Admin -> Settings -> Authentication
5. The page will not show the auth method as being active, as it does for the admin user. However, when you click `Set up`, you can see the saved details.

**Expected behavior**
Non-admins with settings access should see the same thing on the Authentication page as admin users do.

**Information about your Metabase Installation:**
Current master

### LINKED ISSUE #27056: For non-admins with settings access, the group mapping UI only includes groups for which a non-admin is a group manager
**Describe the bug**
If you're a non-admin with settings access, and you view the group mapping configuration for an auth method, you'll only see mappings for groups that you're a manager of. However, you can still remove mappings entirely. This means that there could be some SSO groups that appear to not have any mappings configured, even though they're just mapped to groups you're not a manager of, and this might lead to you erroneously deleting them.

**To Reproduce**
1. As an admin U1, create a new non-admin user U2 and add them to a new permissions group G1
2. Create another permissions group G2 that U2 is not in
3. Go to Permissions -> Application and give G1 settings access
4. Go to Settings -> Authentication -> JWT and put in an arbitrary IdP URI
5. Click "Edit Mappings" and add two mappings, one for each of G1 and G2, and save changes
6. Log in as U2 and go to Admin -> Settings -> Authentication -> JWT -> Edit Mappings
7. You will only see G1 as being mapped. The mapping for G2 will instead appear as if it has no mapped groups.

**Expected behavior**
This makes sense from a permissions perspective but could potentially lead to confusion, and users deleting group mappings that they shouldn't.

**Screenshots**
Admin view:
image

Non-admin view:
image

**Information about your Metabase Installation:**
Current master

**Severity**
Confusing

### LINKED ISSUE #27089: Hide Authentication settings page for non-admins with settings access
There are some weird bugs & side effects of non-admins with settings access having the ability to set up and/or edit authentication details. We've decided to remove this capability for these users, per [this Slack comment](https://metaboat.slack.com/archives/C04CHU61MF1/p1670506660645509?thread_ts=1670446443.605969&cid=C04CHU61MF1).

There's precedent for this, since we already hide the "Updates" and "License and billing" tabs for non-admins. 

Closes #27056 and #27055

Steps

- [ ] Update FE to hide auth setting pages for non-admins
- [ ] Restrict SSO-related settings from being updated by non-admins via the API. This will require some changes to the `Settings` model.

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes #27089, and by extension https://github.com/metabase/metabase/issues/27056 and https://github.com/metabase/metabase/issues/27055

* Hides the auth settings page from non-admin setting managers
* Adds a `:settings-manager` visibility level to settings, which should be used specifically for settings that non-admin setting managers _should_ have access to read and write. The default will stay `:admin` so that we fail closed, just in case.
* Updates all the necessary settings (at least, that I could find) to have `:settings-manager` visibility.
* New tests and a fair bit of settings test reorganization that felt prudent. Sorry for bloating the PR but I've called those areas out in comments so hopefully it's obvious what's going on.

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/27187)

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/advanced_permissions/api/setting_test.clj [hunk 1]
```diff
@@ -2,64 +2,17 @@
...
             [metabase.public-settings.premium-features-test :as premium-features-test]
             [metabase.test :as mt]
-            [metabase.test.fixtures :as fixtures]
-            [metabase.test.integrations.ldap :as ldap.test])
+            [metabase.test.fixtures :as fixtures])
   (:import java.util.UUID))
 
 (use-fixtures :once (fixtures/initialize :db))
 
-(deftest setting-api-test
```
Comment (noahmoss) [inline enterprise/backend/test/metabase_enterprise/advanced_permissions/api/setting_test.clj:19]: Removed this test since it's no longer testing correct behavior, and the new behavior is tested in `metabase.api.setting-test`

File: enterprise/backend/test/metabase_enterprise/advanced_permissions/api/setting_test.clj [hunk 2]
```diff
@@ -152,59 +105,6 @@
               (set-slack-settings :crowberto 200)
               (get-manifest :crowberto 200))))))))
 
-(deftest ldap-api-test
```
Comment (noahmoss) [inline enterprise/backend/test/metabase_enterprise/advanced_permissions/api/setting_test.clj:155]: Removed these tests since they're no longer relevant (setting managers don't have access to auth settings)

File: frontend/src/metabase/admin/settings/selectors.js [hunk 3]
```diff
@@ -228,6 +228,7 @@ const SECTIONS = updateSectionsWithPlugins({
     name: t`Authentication`,
     order: 6,
     settings: [], // added by plugins
+    adminOnly: true,
```
Comment (noahmoss) [inline frontend/src/metabase/admin/settings/selectors.js:231]: Here's the only frontend change

File: test/metabase/models/setting_test.clj [hunk 4]
```diff
@@ -266,69 +266,71 @@
...
-            :is_env_setting false
-            :env_name       "MB_TEST_SETTING_2"
-            :default        "[Default Value]"}
-           (some (fn [setting]
-                   (when (re-find #"^test-setting-2$" (name (:key setting)))
-                     setting))
-                 (setting/admin-writable-settings))))
-
-    (testing "with a custom getter"
+    (mt/with-test-user :crowberto
```
Comment (noahmoss) [inline test/metabase/models/setting_test.clj:269]: The diff here isn't super clear but I only added this line (to keep the test functioning); the rest is the same just shifted down.

File: test/metabase/models/setting_test.clj [hunk 5]
```diff
@@ -576,119 +578,8 @@
     (is (= "Banana Beak"
            (toucan-name)))))
 
-(deftest duplicated-setting-name
```
Comment (noahmoss) [inline test/metabase/models/setting_test.clj:579]: These tests I just moved down to the bottom of the file under the "Misc Tests" heading

File: src/metabase/models/setting.clj [hunk 6]
```diff
@@ -905,7 +910,8 @@
 
   ###### `:visibility`
 
-  `:public`, `:authenticated`, `:admin` (default), or `:internal`. Controls where this setting is visible
+  `:public`, `:authenticated`, `:settings-manager`, `:admin` (default), or `:internal`. Controls where this setting is
+  visible. `:settings-manager` refers to non-admins with the 'settings' permission.
```
Comment (camsaul) [inline src/metabase/models/setting.clj:914]: Just to make sure I understand this correctly. This is the new way this works after this PR, right?

| Visibility        | Who can see it?              | Who can update it?                        |
|-------------------|------------------------------|-------------------------------------------|
| :public           | The entire world             | Only admins                               |
| :authenticated    | Logged-in Users              | Only Admins                               |
| :settings-manager | Admins and Settings Managers | Admins and Settings Managers              |
| :admin            | Admins                       | Admins                                    |
| :internal         | Nobody                       | No one; usually for env-var-only Settings |

I think we're conflating who can see a Setting -- `:visibility`, which

> Controls where this setting is visible

with who can **set** a Setting. Would there ever be a situation where we'd want to let a `:settings-manager` set a Setting that should be visible to `:authenticated`? Maybe in the future `site-locale`, which has `:visibility :public`, should be settable by Settings managers. Should `:visibility` and _setability_ be two separate options?

**Review by camsaul — COMMENTED** [review]
Overall I'm 👍 on this change but I think maybe we should consider making `:visibility` and `:setabilty` or whatever two separate options so we don't box ourselves into a corner here if we ever want to make a generally visible Setting like `site-url` settable by Settings managers.

I don't want to approve or reject this PR until I hear back about your thoughts on that idea so please just tag me for review again after you've got a chance to reply and/or change anything

File: src/metabase/models/setting.clj (hunk 6 above)
Comment (noahmoss) [reply src/metabase/models/setting.clj:914]: It's slightly different—settings managers can update settings that have `:public`, `:authenticated` or `:settings-manager` visibility. Admins can additionally update settings with `:admin` visibility.

I agree that we're conflating read access and write access in one property, but there's not really a need to have separate controls over them right now. Maybe I can just clarify the doc string if it wasn't clear (a table like the one you created might be a good idea).

**Comment by noahmoss** [comment]
@camsaul See my response above—something like `site-url` should currently be writable by settings managers.

File: src/metabase/models/setting.clj (hunk 6 above)
Comment (camsaul) [reply src/metabase/models/setting.clj:914]: Ok, that makes sense.

**Review by camsaul — APPROVED** [review]
Ok, I think this change makes sense now that you've cleared up my questions.

Approving, but it might make sense to clarify some of the documentation a bit. Sticking a table like the one I made in the documentation somewhere probably isn't a bad idea either. If you don't make stuff like this super clear there's always a risk that at some point in the future someone is going to get confused about how this was intended to work and open a PR to break stuff like we've seen over and over with data perms and block perms
