### PR TITLE
Fix parsing timestamps with time zone in CLJS

### LINKED ISSUE #72937: Incorrect date filter on second drill-through after double summarize
### Describe the bug

When I build a question from a base table, then apply two levels of grouping (summarize twice) and display the result as a line chart, the drill-through behavior is inconsistent.

Image

The first drill-down works correctly.
However, after drilling down into the first level and then drilling down again into the second level, the default date filter applied by Metabase is shifted by one day. Because of this incorrect date filter, the second drill-down returns no detailed records, even though matching data actually exists.

From the screenshots:

Image

Image

Image

The chart is based on a question that summarizes the base table twice.
The first drill-down by week/day works as expected.
On the second drill-down, the generated filter uses the wrong date (shifted by one day), which causes the result set to be empty.

### To Reproduce

1. Start from a base table.
2. Build a question with a first Summarize step:
 * group by dateFlag: Day and semiProductNo
 * aggregate fields such as Max of originWeight, qualifiedWeight, and unqualifiedWeight
3. Add a second Summarize step:
 * aggregate the results again
 * group by dateFlag: Day
4. Visualize the result as a line chart grouped by Week.
5. Click a point on the chart and drill down into the first level.
This works correctly.
6. From the first drill-down result, click again to drill into the detailed rows.
7. Observe that the automatically generated date filter is off by one day, so the second drill-down shows “No results”, even though detailed data exists for the selected point.

### Expected behavior

The second drill-down should preserve the correct date context from the selected chart point / grouped result.

The automatically generated filter should match the actual underlying date represented by the selected data point, so that the detailed records are displayed correctly.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "h2",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2026-04-15",
      "tag": "v0.59.7",
      "hash": "46c477c"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "18.1 (Debian 18.1-1.pgdg13+2)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.8"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.10+7-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.10+7-LTS",
    "os.name": "Linux",
    "os.version": "6.8.0-100-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

This is significant for us because it affects business users’ ability to analyze and inspect detailed data. The incorrect date filter on the second drill-through causes valid detail records to disappear, which blocks an important drill-down workflow, although it does not block all usage of Metabase.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by metamben**
closes #72937
Closes QUE2-524

### Description

Preserve the offset of the timestamps.

### How to verify

The repro steps should not end without data, the correct time range should be produced.
Also, see the new tests.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR
- ~If adding new Loki tests: they pass [stress testing](https://github.com/metabase/metabase/actions/workflows/loki-stress-test-flake-fix.yml)~

### CODE REVIEW

File: src/metabase/util/time/impl.cljs [hunk 1]
```diff
@@ -243,15 +243,15 @@
...
+  truncated to May 12 (in UTC) instead of May 13 (in +08:00). See #72937."
   [value]
-  (let [;; Check if it has a timezone offset
-        has-offset? (re-find #"[Zz]|[+-]\d{2}:?\d{2}$" value)]
-    (if has-offset?
-      ;; Parse as UTC and keep the offset info
-      (.utc dayjs value true)
-      ;; No timezone, parse normally
-      (dayjs value))))
+  (if-let [offset (re-find #"Z|[+-]\d{2}:?\d{2}$" value)]
```
Comment (metamben) [inline src/metabase/util/time/impl.cljs:251]: I don't think `z` has to be supported, but can add it back, if there is demand.

**Review by rileythomp — APPROVED** [review]
