### PR TITLE
Fix issue with not being able to go back to schema picker

### LINKED ISSUE #3309: Select a table dropdown doesn't allow going back to schema selection screen
This is on v19.3, using Chrome 53
in postgres, if I have multiples schemas, I get to pick a schema first
image

After clicking on a schema, I can get stuck on the next screen and have no way of going back to the schema selection screen
image

The only workaround I have is to refresh the entire page

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #3309

### CODE REVIEW

**Comment by tlrobinson** [comment]
@metabase/core-developers Needs review

File: frontend/src/metabase/query_builder/components/DataSelector.jsx [hunk 1]
```diff
@@ -243,12 +243,16 @@ export default class DataSelector extends Component {
 
     renderTablePicker() {
         const schema = this.state.selectedSchema;
+
         const hasMultipleDatabases = this.props.databases.length > 1;
+        const hasMultipleSchemas = schema && schema.database && _.chain(schema.database.tables).pluck("schema").uniq().value().length > 1;
```
Comment (salsakran) [inline frontend/src/metabase/query_builder/components/DataSelector.jsx]: what's ` _.chain(schema.database.tables).pluck("schema").uniq().value().length`  all about?

seems a little too much of a one-liner.
