### PR TITLE
Fix date ranges generated for MongoDB params

### LINKED ISSUE #11690: MongoDB single date field filters aren't working correctly
MongoDB field filters against a single date e.g. `2019-12-08` should correctly generating a `$match` condition like

```clj
"[{$match: {$and: [{"date": {$gte: ISODate("2019-12-08")}}, {"date": {$lt: ISODate("2019-12-09")}}]}}]"
```

so it correctly works for all temporal types with a date (e.g. date or timestamp).

Noticed this while working on fix for another bug. Already have fix

### PR DESCRIPTION
**Pull request by camsaul**
The logic used to translate Field filter date params such as `thismonth` generated *inclusive* ranges, e.g. 

```clj
(date-string->range \"past2days\") ; -> {:start \"2020-01-20\", :end \"2020-01-21\"}
```

Originally this was only used for SQL, e.g.

```sql
WHERE date(some_column) BETWEEN date '2020-01-20' AND date '2020-01-21'
```

which works as expected (`BETWEEN` is inclusive).

With MongoDB we're generating a`$match` with an exclusive end date, meaning the range needs to be adjusted to be correct.

Fixes #11690 by adding support for either inclusive or exclusive ranges to `date-string->range`. Once that was in place the Mongo stuff started working as expected.

### CODE REVIEW

File: modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj [hunk 1]
```diff
@@ -78,25 +80,71 @@
...
 (deftest field-filter-test
   (testing "Date ranges"
     (mt/with-clock #t "2019-12-13T12:00:00.000Z[UTC]"
-      (is (= "[{$match: {$and: [{\"date\": {$gte: ISODate(\"2019-12-08\")}}, {\"date\": {$lt: ISODate(\"2019-12-12\")}}]}}]"
-             (substitute {:date (field-filter "date" :date/range "past5days")}
-                         ["[{$match: " (param :date) "}]"])))))
+      (letfn [(substitute-date-range [s]
+                (substitute {:date (field-filter "date" :date/range s)}
+                            ["[{$match: " (param :date) "}]"]))]
+        (is (= (to-bson [{:$match {:$and [{"date" {:$gte (ISODate "2019-12-08")}}
```
Comment (camsaul) [inline modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj]: reading big serialized BSON strings was hurting my head so I slapped together a quick BSON serializer to make the tests easier to read

File: src/metabase/driver/common/parameters/dates.clj [hunk 2]
```diff
@@ -201,36 +202,80 @@
...
+   (when start
+     {:start (if inclusive-start?
+               start
+               (u.date/add start :day -1))})
+   (when end
+     {:end (if inclusive-end?
+             end
+             (u.date/add end :day 1))})))
+
+(def ^:private DateStringRange
```
Comment (camsaul) [inline src/metabase/driver/common/parameters/dates.clj]: added extra schemas and documentation to clarify what everything here is supposed to be doing
