### PR TITLE
Fix removing a notebook section can remove other sections

### LINKED ISSUE #17712: Notebook: removing a section can also delete other sections if they have invalid MBQL
**Describe the bug**
Originally described in [this comment](https://github.com/metabase/metabase/pull/17633#issuecomment-908330423) from #17633. On the notebook editor, if there are two incomplete join sections (without table / any field / second field specified), once you remove one of them, the second is also removed.

The issue can be easily reproduced with joins, but most likely it can happen with any other notebook step.
It's just easier to make an "invalid MBQL" join.

**To Reproduce**
1. Ask a question > Custom Question > Sample Dataset > Orders
2. Join the Products table
3. Join the Reviews table
4. Remove only one field from the right side of the Products join section
5. Hover the Reviews join section and click the cross icon in the top-right
6. Both joins are removed

**Expected behavior**
Only the section user removes has to be removed.

**Demo**

https://user-images.githubusercontent.com/17258145/131664455-4e1dffaf-3980-42f5-aab7-95ea83437ddb.mov

**Information about your Metabase Installation:**

Metabase v0.41.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by kulyk**
Followup [this comment](https://github.com/metabase/metabase/pull/17633#issuecomment-908330423) from #17633. On the notebook editor, if there are two incomplete join sections (without table / any field / second field specified), once you remove one of them, the second is also removed.

The issue can be easily reproduced with joins, but most likely it can happen with any other notebook step.
It's just easier to make an "invalid MBQL" join.

Reproduces #17712, fixes #17712

### ⚠️ Warning

The reason removing a section also removes other invalid sections is because of this code section from the `NotebookStep`:

```js
const reverted = step.revert(step.query).clean();
if (reverted.isValid()) {
   onRemove = () => reverted.update(updateQuery);
}
```

`onRemove` will be called when a user clicks the cross icon on the section. It will generate a reverted query (current query, but without a section you're removing) and also call `StructuredQuery's` `clean` method on it. `clean` will remove the invalid MBQL clauses and that leads to removing other sections apart from the one user removes intentionally.

We used to display the cross icon only if removing a section will result in a valid query state (see in the code block: get reverted query > clean it > check if the reverted and clean query is valid > define the `onRemove` callback > display the icon if there is a callback).

My thinking here is that we _MAYBE_ can display the icon all the time because the `clean` will happen anyway once we run the query, so we should be safe about query validity. This is something I'm not sure about, so I'd appreciate feedback from somebody confident about the notebook 🙏 

Also, the cleanup happens any time you remove a section. In that way, we can remove clauses that were depending on a removed part. Let's say you joined a Products table and then added a filter on "Category" and a summarization like "Average of Price". If you remove the join, the filter and the summarization are invalid now, so we should remove that. The problem with join sections is that an incomplete join is also considered invalid and gets removed. This PR extends the `Join` class with a `hasGaps` method. If there are not yet specified join dimensions, the join won't get removed not to confuse people. `join.isValid()` will still be `false` if there are gaps, so once you run the query, all the incomplete joins will be removed.

### To Verify

1. Ask a question > Custom Question > Sample Dataset > Orders
2. Join the Products table
3. Join the Reviews table
4. Remove only one field from the right side of the Products join section
5. Hover the Reviews join section and click the cross icon in the top-right
6. Only the section you clicked has to be removed.

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/131664455-4e1dffaf-3980-42f5-aab7-95ea83437ddb.mov

**After**

https://user-images.githubusercontent.com/17258145/131813760-aeedab4e-230c-46fd-b892-504a510564bd.mov

### CODE REVIEW

**Review by flamber — COMMENTED** [review]
Works exactly as described. I cannot trigger any strange behavior. I'm good with this PR :+1: 

From all my testing, it only seems to apply to join sections.
Example, in metric section do Count grouped by some field, and then remove Count, then the entire section is removed even though it is valid. If you remove the grouped field, then it does not remove the section. This is how it has been doing since 0.33, but probably only something that annoys me.

Though, not new to this PR, when a join is invalid state, then it seems to include the table in other sections, but will show duplicate when there are implicit joins too (just something I noticed now, but seems to have always been the case, so I'm not saying you should fix it)
image

**Comment by kulyk** [comment]
@metabase-bot run visual tests

**Review by alxnddr — APPROVED** [review]

File: frontend/src/metabase/query_builder/components/notebook/lib/steps.js [hunk 1]
```diff
@@ -110,7 +110,14 @@ const STEPS: StepDefinition[] = [
     revert: (query, index) => query.removeJoin(index),
     clean: (query, index) => {
       const join = query.joins()[index];
-      return !join || join.isValid() ? query : query.removeJoin(index);
+      if (!join || join.isValid()) {
+        return query;
+      }
+      const cleanJoin = join.clean();
+      if (!cleanJoin.isValid()) {
```
Comment (daltojohnso) [inline frontend/src/metabase/query_builder/components/notebook/lib/steps.js:117]: this logic might be totally correct, but I'm finding it confusing to understand. Let me put how I'm reading it into english:

1. if a given join either doesn't exist or is valid, do nothing to the query.
2. otherwise (if a join exists and is invalid), create a cleaned instance of the join
3. if the cleaned join still isn't valid, replace the original, invalid join with the cleaned, invalid join
4. if the cleaned join is now valid, remove the original, invalid join

is that correct? I find that the steps to this function, in particular steps 3 and 4, don't really follow how you'd expect

Comment (kulyk) [reply frontend/src/metabase/query_builder/components/notebook/lib/steps.js:117]: Ouch, you're absolutely right, if the clean join is valid, we should replace the original one with it. Otherwise, we should just remove the whole join. Thank you so much for being so attentive

**Comment by kulyk** [comment]
Thanks for @daltojohnso attention, I learned more about Notebook's behavior. I've updated the PR description, but here's the diff

> The query cleanup happens before a query is run, but also any time you remove a section. In that way, we can remove clauses that were depending on a removed part. Let's say you joined a Products table and then added a filter on "Category" and a summarization like "Average of Price". If you remove the join, the filter and the summarization are invalid now, so we should remove that.
> 
> The problem with join sections is that an incomplete join is also considered invalid and gets removed. This PR extends the `Join` class with a `hasGaps` method. If there are not yet specified join dimensions, the join won't get removed not to confuse people. `join.isValid()` will still be `false` if there are gaps, so once you run the query, all the incomplete joins will be removed.

Hopefully that was the final extension to the fix :)
@flamber @alxnddr @daltojohnso I would be grateful if you take one more look at that

**Review by flamber — COMMENTED** [review]
I'm not noticing any difference with `06e5447` compared to previous test. It still works as expected, but perhaps I'm not understanding what was changed.

**Review by daltojohnso — APPROVED** [review]
nice work, this reads a lot clearer to me
