### PR TITLE
Sort GeoJSON maps

### LINKED ISSUE #14696: Custom GeoJSON files are not sorted in the dropdown
**Describe the bug**
Region maps are not sorted. This becomes a pain when dealing with many custom GeoJSON files.
image

**To Reproduce**
If you need several geojson files i found https://geojson-maps.ash.ms/ to be helpful in creating them quickly with several predefined ones for continents.

1. put a few of these maps in resources
2. add them under Admin > maps. I chose name as the display and "gu_a3" as the identifier
3. ask a question, native, sample dataset `select 1 as counter, 'CHN' as country`, choose map visualization, and then select from the region map

**Expected behavior**
The list is sorted for ease in finding maps. Bonus points if it becomes searchable above some threshold.

### PR DESCRIPTION
**Pull request by dpsutton**
https://github.com/metabase/metabase/issues/14696

Sort GeoJSON files on maps visualization

## Before
image

## After
image

## Questions

Simple implementation, just chaining with underscore. One question is how to elegantly handle null names. Figure @paulrosenzweig might have 1-liner trick for that. Also its possible that `name` is required? Not sure if that's actually validated or just by convention always true.

### CODE REVIEW

**Comment by dpsutton** [comment]
Would love to add a test for this but I don't know how to even begin. Happy to do the work though.

**Comment by dpsutton** [comment]
getting failing tests but tests seem to fail on `release-x.38.x` for me with `yarn run test-unit`

**Comment by flamber** [comment]
Looks like a timeout - don't think I've seen that before at that spot, but there has been a lot of wack-a-mole with CI this week.
Try rerunning the failed test once Cypress finishes.

**Comment by nemanjaglumac** [comment]
> Would love to add a test for this but I don't know how to even begin. Happy to do the work though.

I can help with Cypress if e2e is what you meant?

File: frontend/src/metabase/visualizations/visualizations/Map.jsx [hunk 1]
```diff
@@ -237,10 +237,12 @@ export default class Map extends Component {
         return null;
       },
       getProps: () => ({
-        options: Object.entries(MetabaseSettings.get("custom-geojson", {})).map(
-          // $FlowFixMe:
-          ([key, value]) => ({ name: value.name, value: key }),
-        ),
+        options: _.chain(
+          Object.entries(MetabaseSettings.get("custom-geojson", {})),
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/visualizations/Map.jsx:241]: `Object.entries` could be moved into the `chain` with `pairs`.

File: frontend/src/metabase/visualizations/visualizations/Map.jsx [hunk 2]
```diff
@@ -237,10 +237,12 @@ export default class Map extends Component {
...
+        )
+          .map(([key, value]) => ({ name: value.name, value: key }))
+          .sortBy(x => x.name.toLowerCase())
```
Comment (paulrosenzweig) [inline frontend/src/metabase/visualizations/visualizations/Map.jsx:244]: This won't handle strings with accents correctly, but that that's probably ok for now. Browsers have `localeCompare` to handle that, but it doesn't work with `_.sortBy`.

**Review by paulrosenzweig — APPROVED** [review]
This works for me! As-is I wouldn't bother testing since E2E seems a bit heavyweight for this.

I think a better solution long term is to handle this in `AccordionList` with some flag to enable sorting. That would be a good place to unit test the behavior centrally and also eliminate duplicated effort anywhere else we need this. That's a bit more involved, so I think getting this in for the next release is still a good move!

File: frontend/src/metabase/visualizations/visualizations/Map.jsx (hunk 2 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/visualizations/Map.jsx:244]: Oh also, I think we do validate `name` in the UI, but I'm not sure if there's also backend validation. Adding `(name || "")` doesn't hurt since this will break if someone has some old map stored will a null name.

**Comment by dpsutton** [comment]
@paulrosenzweig thanks a bunch!
