### PR TITLE
Ensure postgres downloads don't OOM

### LINKED ISSUE #60733: OOM on large CSV download (postgres)
### Describe the bug

Downloading a large CSV in postgres brings the entire result set into memory causing an OOM if the data set is large enough

### To Reproduce

1. Start up Metabase, limit memory to 2GB to see this happen quickly (`-Xmx2048m`)
2. Add a Postgres DB
3. New SQL query: `SELECT repeat('x', 2048) FROM generate_series(1, 1_000_000) -- 2kb per row * 1M = 2GB`
4. Save, download as CSV
5. OOM

### Expected behavior

It should stream the result set from the DB instead of bringing it all into memory

### Logs

Memory analyzer on heap dump:

Image

```

streaming-response-thread-pool-3
  at java.lang.OutOfMemoryError.<init>()V (OutOfMemoryError.java:48)
  at org.postgresql.core.PGStream.receiveTupleV3()Lorg/postgresql/core/Tuple; (PGStream.java:619)
  at org.postgresql.core.v3.QueryExecutorImpl.processResults(Lorg/postgresql/core/ResultHandler;IZ)V (QueryExecutorImpl.java:2387)
  at org.postgresql.core.v3.QueryExecutorImpl.execute(Lorg/postgresql/core/Query;Lorg/postgresql/core/ParameterList;Lorg/postgresql/core/ResultHandler;IIIZ)V (QueryExecutorImpl.java:372)
  at org.postgresql.jdbc.PgStatement.executeInternal(Lorg/postgresql/core/CachedQuery;Lorg/postgresql/core/ParameterList;I)V (PgStatement.java:517)
  at org.postgresql.jdbc.PgStatement.execute(Lorg/postgresql/core/CachedQuery;Lorg/postgresql/core/ParameterList;I)V (PgStatement.java:434)
  at org.postgresql.jdbc.PgStatement.executeWithFlags(Lorg/postgresql/core/CachedQuery;I)Z (PgStatement.java:356)
  at org.postgresql.jdbc.PgStatement.executeCachedSql(Ljava/lang/String;I[Ljava/lang/String;)Z (PgStatement.java:341)
  at org.postgresql.jdbc.PgStatement.executeWithFlags(Ljava/lang/String;I)Z (PgStatement.java:317)
  at org.postgresql.jdbc.PgStatement.execute(Ljava/lang/String;)Z (PgStatement.java:312)
  at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(Ljava/lang/String;)Z (NewProxyStatement.java:1341)
  at metabase.driver.sql_jdbc.execute$fn__93645.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:563)
  at metabase.driver.sql_jdbc.execute$fn__93645.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:561)
  at clojure.lang.MultiFn.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (MultiFn.java:239)
  at metabase.driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:571)
  at metabase.driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:568)
  at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__93732$fn__93733.invoke()Ljava/lang/Object; (execute.clj:737)
  at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__93732.invoke(Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:736)
  at metabase.driver.sql_jdbc.execute$fn__93528$fn__93529.invoke(Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:398)
  at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:338)
  at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:321)
  at metabase.driver.sql_jdbc.execute$fn__93528.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:392)
  at metabase.driver.sql_jdbc.execute$fn__93528.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:390)
  at clojure.lang.MultiFn.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (MultiFn.java:244)
  at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:730)
  at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:716)
  at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:727)
  at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:716)
  at metabase.driver.sql_jdbc$fn__95703.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (sql_jdbc.clj:79)
  at metabase.driver.sql_jdbc$fn__95703.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (sql_jdbc.clj:77)
  at clojure.lang.MultiFn.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (MultiFn.java:244)
  at metabase.query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (pipeline.clj:58)
  at metabase.query_processor.pipeline$_STAR_execute_STAR_.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (pipeline.clj:43)
  at metabase.query_processor.pipeline$_STAR_run_STAR_.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (pipeline.clj:116)
  at metabase.query_processor.pipeline$_STAR_run_STAR_.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (pipeline.clj:105)
  at metabase.query_processor.execute$run.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:64)
  at metabase.query_processor.execute$run.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:58)
  at metabase.query_processor.middleware.enterprise$swap_destination_db_middleware$fn__76550.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (enterprise.clj:73)
  at metabase.query_processor.middleware.enterprise$apply_impersonation_postprocessing_middleware$fn__76533.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (enterprise.clj:48)
  at metabase.query_processor.middleware.update_used_cards$update_used_cards_BANG_$fn__76746.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (update_used_cards.clj:67)
  at metabase.query_processor.execute$add_native_form_to_result_metadata$fn__76835.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:25)
  at metabase.query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__76841.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:36)
  at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76691.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (cache.clj:241)
  at metabase.query_processor.middleware.permissions$check_query_permissions$fn__76432.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (permissions.clj:160)
  at metabase.query_processor.middleware.enterprise$check_download_permissions_middleware$fn__76560.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (enterprise.clj:90)
  at metabase.query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__76570.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (enterprise.clj:103)
  at metabase.query_processor.execute$execute$fn__76869.invoke(Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:96)
  at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (setup.clj:225)
  at metabase.query_processor.setup$do_with_qp_setup.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (setup.clj:216)
  at metabase.query_processor.execute$execute.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:95)
  at metabase.query_processor.execute$execute.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (execute.clj:91)
  at metabase.query_processor$process_query_STAR__STAR_.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (query_processor.clj:50)
  at metabase.query_processor$process_query_STAR__STAR_.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (query_processor.clj:45)
  at metabase.query_processor.middleware.enterprise$fn__76587$handle_audit_app_internal_queries__76588$fn__76590.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (enterprise.clj:135)
  at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__76598.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (enterprise.clj:142)
  at metabase.query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__85106.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (process_userland_query.clj:177)
  at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__85166.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (catch_exceptions.clj:137)
  at metabase.query_processor$process_query$fn__85206.invoke(Ljava/lang/Object;)Ljava/lang/Object; (query_processor.clj:81)
  at metabase.query_processor.setup$do_with_canceled_chan$fn__76819.invoke(Ljava/lang/Object;)Ljava/lang/Object; (setup.clj:187)
  at metabase.query_processor.setup$do_with_database_local_settings$fn__76813.invoke(Ljava/lang/Object;)Ljava/lang/Object; (setup.clj:181)
  at metabase.query_processor.setup$do_with_driver$fn__76807$fn__76808.invoke()Ljava/lang/Object; (setup.clj:166)
  at metabase.driver$do_with_driver.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (driver.clj:48)
  at metabase.driver$do_with_driver.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (driver.clj:43)
  at metabase.query_processor.setup$do_with_driver$fn__76807.invoke(Ljava/lang/Object;)Ljava/lang/Object; (setup.clj:165)
  at metabase.query_processor.setup$do_with_metadata_provider$fn__76799.invoke(Ljava/lang/Object;)Ljava/lang/Object; (setup.clj:140)
  at metabase.query_processor.setup$do_with_resolved_database$fn__76791.invoke(Ljava/lang/Object;)Ljava/lang/Object; (setup.clj:128)
  at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (setup.clj:232)
  at metabase.query_processor.setup$do_with_qp_setup.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (setup.clj:216)
  at metabase.query_processor$process_query.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (query_processor.clj:79)
  at metabase.query_processor$process_query.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (query_processor.clj:72)
  at metabase.query_processor.card$process_query_for_card_default_qp.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (card.clj:235)
  at metabase.query_processor.card$process_query_for_card_default_qp.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (card.clj:231)
  at metabase.query_processor.card$process_query_for_card_default_run_fn$fn__91262$fn__91263.invoke(Ljava/lang/Object;)Ljava/lang/Object; (card.clj:242)
  at metabase.query_processor.streaming$_streaming_response$fn__90431$fn__90432$fn__90433.invoke()Ljava/lang/Object; (streaming.clj:188)
  at metabase.query_processor.streaming$_streaming_response$fn__90431$fn__90432.invoke(Ljava/lang/Object;)Ljava/lang/Object; (streaming.clj:186)
  at metabase.query_processor.streaming$do_with_streaming_rff.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (streaming.clj:177)
  at metabase.query_processor.streaming$do_with_streaming_rff.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (streaming.clj:164)
  at metabase.query_processor.streaming$_streaming_response$fn__90431.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (streaming.clj:183)
  at clojure.lang.AFn.applyToHelper(Lclojure/lang/IFn;Lclojure/lang/ISeq;)Ljava/lang/Object; (AFn.java:156)
  at clojure.lang.AFn.applyTo(Lclojure/lang/ISeq;)Ljava/lang/Object; (AFn.java:144)
  at clojure.core$apply.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (core.clj:667)
  at clojure.core$with_bindings_STAR_.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Lclojure/lang/ISeq;)Ljava/lang/Object; (core.clj:1990)
  at clojure.core$with_bindings_STAR_.doInvoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (core.clj:1990)
  at clojure.lang.RestFn.applyTo(Lclojure/lang/ISeq;)Ljava/lang/Object; (RestFn.java:145)
  at clojure.core$apply.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (core.clj:671)
  at clojure.core$bound_fn_STAR_$fn__5837.doInvoke(Ljava/lang/Object;)Ljava/lang/Object; (core.clj:2020)
  at clojure.lang.RestFn.invoke(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (RestFn.java:424)
  at metabase.server.streaming_response$do_f_STAR_.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (streaming_response.clj:79)
  at metabase.server.streaming_response$do_f_STAR_.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (streaming_response.clj:77)
  at metabase.server.streaming_response$do_f_async$task__88344.invoke()Ljava/lang/Object; (streaming_response.clj:94)
  at clojure.lang.AFn.run()V (AFn.java:22)
  at java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; (Executors.java:572)
  at java.util.concurrent.FutureTask.run()V (FutureTask.java:317)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run()V (ThreadPoolExecutor.java:642)
  at java.lang.Thread.runWith(Ljava/lang/Object;Ljava/lang/Runnable;)V (Thread.java:1588)
  at java.lang.Thread.run()V (Thread.java:1575)

```

### Information about your Metabase installation

```JSON
v55.7
```

### Severity

P1

### Additional context

Primary suspect is autoCommit(true) not respecting JDBC max fetch size, more context [here](https://metaboat.slack.com/archives/CKZEMT1MJ/p1749129796018449), also see thread to see the ticket of our customer facing this issue

### PR DESCRIPTION
**Pull request by dpsutton**
Fixes https://github.com/metabase/metabase/issues/60733

For performance reasons we set autocommit to true. this has an unfortunate consequence that the postgres driver does not honor batch sizes. We go through a lot of trouble to hook the streaming results of a query to the output stream of the download, but the postgres jdbc driver will realize all rows in memory.

A fast way forward is to set autocommit to false only when `write?` (previous condition) or when executing a postgres download, as reported in https://github.com/metabase/metabase/issues/60733.

How to test:
this is difficult. In CI we use

```clojure
  :ci
  {:jvm-opts ["-Xmx12g"
              "-Xms12g"
```

So hitting a query that would deterministically OOM the instance requires a lot more muscle than we realistically want to use.

I'm running the following tests locally:

```
  :small-ram
  {:jvm-opts ["-Xmx400m"
              "-Xms400m"
              "-Dci=TRUE"]}
```

```clojure
(defn- readable [bytes]
  (cond (nil? bytes)  "0 bytes"
        (zero? bytes) "0 bytes"
        :else
        (let [units ["b" "kb" "mb" "gb" "tb"]
              magnitude   1024.0]
          (loop [[unit & remaining] units
                current (double bytes)]
            (if (and (seq remaining) (> current magnitude))
              (recur remaining (/ current magnitude))
              (format "%.1f %s" current unit))))))

(defn- consume
  [^java.io.InputStream is]
  (let [arr (byte-array 8024)]
    (loop [c 0, gas 5000000]
      (let [r (java.io.InputStream/.read is arr 0 (alength arr))]
        (cond (zero? gas)
              (throw (ex-info "Ran out of gas" {}))
              (neg? r) c
              :else (recur (+ c r) (dec gas)))))))

(deftest large-csv-test
  (mt/test-driver :postgres
    (testing "Postgres can download csvs without holding the entire results in memory #(#60733)"
      (let [large-query "SELECT repeat('x', 2048) FROM generate_series(1, 1000000)"
            result (mt/user-real-request :crowberto :post 200 "dataset/csv"
                                         {:request-options {:as :stream}}
                                         {:query       (mt/native-query
                                                        {:query large-query})
                                          :format_rows true})
            size (consume result)]
        (is (> size 2000000000)
            (format "Only consumed %s but expected ~2gb" (readable size)))))))
```

and then

```
❯ time source pg.env && DRIVERS=postgres clojure -X:dev:test:small-ram :only metabase.driver.postgres-test/large-csv-test

Running QP tests against these drivers: #{:postgres}

LONG TEST in metabase.driver.postgres-test/large-csv-test
Test took 23.358 seconds seconds to run

Ran 1 tests in 32.825 seconds
2 assertions, 0 failures, 0 errors.
{:test 1, :pass 2, :fail 0, :error 0, :type :summary, :duration 32825.099875, :single-threaded 1}
Ran 0 tests in parallel, 1 single-threaded.
Finding and running tests took 40.7 s.
All tests passed.
Running after-run hooks...
```

Why not add these tests now?
We probably should write a full memory regression suite. This is a great candidate for a first one. But it seems silly to run a new CI job with just this one job. Push back if you think i'm wrong.

Another area of pushback:
I took the lazy way when determining if a driver should have autocommit set to false or not: i hardcoded it.

```clojure
(and (-> options :download?) (= driver :postgres))
```

The alternative is some method of a new driver multimethod or driver-supports?. The former feels a bit heavy-weight, the latter feels not quite right since this is almost a non-support and all other jdbc drivers do support it, presumably?

I'm quite open to pushback here and invite comments if you see a better way.

### CODE REVIEW

File: src/metabase/driver/sql_jdbc/execute.clj [hunk 1]
```diff
@@ -720,53 +733,59 @@
...
+  {:added "0.35.0", :arglists '([driver query context respond])}
+  [driver {{sql :query, params :params} :native, :as outer-query} _context respond]
+  {:pre [(string? sql) (seq sql)]}
+  (let [database (driver-api/database (driver-api/metadata-provider))
+        sql      (if (get-in database [:details :include-user-id-and-hash] true)
+                   (->> (driver-api/query->remark driver outer-query)
+                        (inject-remark driver sql))
+                   sql)
+        max-rows (driver-api/determine-query-max-rows outer-query)]
+    #_(execute-reducible-query driver sql params max-rows context respond)
```
Comment (lbrdnk) [inline src/metabase/driver/sql_jdbc/execute.clj]: - Why to leave this in?
- I assume the dropped arity was not exercised anywhere else hence existing tests are passing.

**Review by lbrdnk — APPROVED** [review]
LGTM.

_Hardcoding postgres_. I'd say this is the reasonable exception to the rule. It would make sense to me to address that when/if we are tackling more general case, not concerned only with download, or when there is demand for similar in other drivers.

_Test suite_. I don't think it is silly to run single job. We have to start somehow. I think it would make sense to open a task on that and assign either SEM or DRI so approach in this PR will be considered when we are writing that suite.

**Comment by rileythomp** [comment]
Agree that this is fine as is for now. I'd be in favour of a test that runs across all drivers so we can see if this occurs in any other than postgres (but it can be left for the future). Re hardcoding:
> feels not quite right since this is almost a non-support and all other jdbc drivers do support it

I think that's probably fine? We could have a feature that defaults all jdbc drivers to true and override it to false for just postgres which doesn't seem like too much overhead.

**Review by rileythomp — APPROVED** [review]

**Comment by lindsay-stevens** [comment]
Will the hardcoding `(and (-> options :download?) (= driver :postgres))` apply this fix for drivers inheriting from postgres? I have a custom driver based on pg.

Was an option considered for this issue to terminate threads / connections taking up too much memory - or is that not possible to do cleanly with the driver (e.g. both clean up on the JVM side, and make sure the query is cancelled)?

A memory regression suite would be great, it'd be useful to know at what point users could DoS themselves. Hopefully never but some idea of what can trigger it.

Thanks!

**Comment by dpsutton** [comment]
@lindsay-stevens that's a great point.
Let me check how redshift behaves to see if i can safely apply this there or not. I was hoping to quickly get this out but you raise good points that i might need to have drivers be able to specify this or not. I'm running this query on redshift and it's not looking great at the moment:
```sql
WITH
  digits AS (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9),
  series AS (
    SELECT
      d1.n + (d2.n * 10) + (d3.n * 100) + (d4.n * 1000) + (d5.n * 10000) + (d6.n * 100000) AS i
    FROM digits d1, digits d2, digits d3, digits d4, digits d5, digits d6
  )
SELECT REPEAT('x', 2048)
FROM series
WHERE i < 1000000;
```
(query generated by gemini to create ~2gb of results without needing disk)

and unfortunately it's been frozen here for a few minutes (😱 )

```
"streaming-response-thread-pool-1" #1713 [248171] daemon prio=5 os_prio=31 cpu=13081.69ms elapsed=768.71s tid=0x000000013a646800 nid=248171 waiting on condition  [0x0000000328e4b000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@21.0.2/Native Method)
	- parking to wait for  <0x000000061b3856d0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@21.0.2/LockSupport.java:371)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@21.0.2/AbstractQueuedSynchronizer.java:519)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@21.0.2/ForkJoinPool.java:3780)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@21.0.2/ForkJoinPool.java:3725)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@21.0.2/AbstractQueuedSynchronizer.java:1707)
	at java.util.concurrent.LinkedBlockingQueue.take(java.base@21.0.2/LinkedBlockingQueue.java:435)
	at com.amazon.redshift.core.v3.RedshiftRowsBlockingQueue.take(RedshiftRowsBlockingQueue.java:132)
	at com.amazon.redshift.jdbc.RedshiftResultSet.next(RedshiftResultSet.java:2076)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.next(NewProxyResultSet.java:4511)
	at metabase.driver.sql_jdbc.execute$row_thunk$row_thunk_STAR___144394.invoke(execute.clj:664)
	at metabase.query_processor.reducible$fn__116108$reducible_rows116107$reify__116110.reduce(reducible.clj:61)
	at clojure.core$transduce.invokeStatic(core.clj:7025)
	at clojure.core$transduce.invokeStatic(core.clj:7021)
	at clojure.core$transduce.invoke(core.clj:7012)
	at metabase.query_processor.pipeline$_STAR_reduce_STAR_$fn__98198.invoke(pipeline.clj:78)
	at metabase.query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:77)
	at metabase.query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:60)
	at metabase.query_processor.pipeline$_STAR_run_STAR_$respond__98214.invoke(pipeline.clj:114)
```

As for terminating threads: we would love some way to accomplish that but i don't know of a good way to accomplish this. I'm not sure how to reach into the thread that the connection pool uses and bound its memory usage. But that also sounds less optimal than this direction which rather than killing those queries lets them succeed without using too much memory.

As to a memory regression suite, that's what i've been doing the last few days. It's a bit of a big lift to get the initial version out the door for a few reasons. I need to not run these tests in regular CI since we run the instances with 12gb of ram. Those are poor machines to verify OOM workloads. I've got a lower limit, but with a new job i have to get all of the secrets to the instance so that it can connect to all of the databases and ensure they work, plus ensure that the machines of non-cloud databases are around. All of this holds up the original OOM fix which has been done for a few days now. 

So I think i will figure out how i can get you the same behavior for your pg-descending driver without having to edit the code of metabase itself and then slowly develop the performance regression suite

File: src/metabase/driver/sql_jdbc/execute.clj (hunk 1 above)
Comment (dpsutton) [reply src/metabase/driver/sql_jdbc/execute.clj]: ah good catch! yes i was removing the arity and left this in here to make sure i lined everything up. The previous multi-arity split was for a bit of clarity and never used anywhere. It also prevented the query's info from being in scope when we did the connection stuff. That's why i consolidated it back into one arity so that i could have that around without adding another parameter to `execute driver sql params info max-rows context respond`
