### PR TITLE
fix(sdk): Properly expose `initialParameters` type on dashboard components

### LINKED ISSUE #58337: SDK dashboards `initialParameters` type is `any` in a user app.
### Describe the bug

When using the SDK in an application e.g. Next.js the dashboards' `initialParameters` type is `any` and the [doc link](https://www.metabase.com/docs/latest/embedding/sdk/dashboards) shows [`Search`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/92af6adfa92bac7261e17aefeb93a7fb2d44317b/types/history/index.d.ts#L67) instead.

Image

### To Reproduce

1. Create an application and install `@metabase/embedding-sdk-react`
2. Import `InteractiveDashboard` and set `intialParameters`, see if your IDE can see the actual type.

### Expected behavior

It should show an actual type similar to how we're having `SqlParameterValues`
https://github.com/metabase/metabase/blob/1061de72ca568fbadda47796905ee55cdb711e78/enterprise/frontend/src/embedding-sdk/types/question.ts#L64

I think the type should be something like this `Record<string, string | string[]>` or maybe `Record<string, string | string[] | number | number[]>`

### Logs

_No response_

### Information about your Metabase installation

```JSON
SDK built from 1061de72ca568fbadda47796905ee55cdb711e78 (this is today's commit, but actually it's a commit from yesterday, so it would be a little older. I don't think it matters.)
```

### Severity

low. It's just a wrong type, but annoying and looks unpolished.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WiNloSt**
Closes https://github.com/metabase/metabase/issues/58337, closes EMB-409

### Description

Stop using `Query` from `history` and use our own type insteaad. This is similar to how we're exposing `SqlParameterValues`.
https://github.com/metabase/metabase/blob/9b77830a96a65a1c1d69c475317b70a63b97c5d1/enterprise/frontend/src/embedding-sdk/types/question.ts#L64

Please note that I inline the type from `Query` exactly to not have to deal with type incompatibility with query builder code. I tested that even if we pass string number, the dashboard componets will eventually parse it according to the widget type correctly, so even if you pass `"1"` as a parameter value, it will be turned into `1` (number) in `dashboards.parameterValues[string]` correctly.

### How to verify

1. Run `yarn build-embedding-sdk` and install the built package in your application.
1. Try to use autocompletion on `InteractiveDashboard`'s `initialParameters` and see that the type should be reported correctly, no as `any` anymore.

#### After 
Screenshot 2025-06-06 at 9 20 10 PM

#### Before
image

### Checklist

- [ ] ~Tests have been added/updated to cover changes in this PR~ Just type change

### CODE REVIEW

File: frontend/src/metabase/embedding-sdk/types/dashboard.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+export type ParameterValues = Record<
+  string,
+  string | string[] | undefined | null
```
Comment (heypoom) [inline frontend/src/metabase/embedding-sdk/types/dashboard.ts:3]: Could the initialParameters accept a number? e.g. `{productId: 26}`

**Review by heypoom — APPROVED** [review]
