### PR TITLE
Optimize relative datetime filters

### LINKED ISSUE #8626: Google Analytics - Filter escaping causing issues
### Outline

When creating a custom question using Google Analytics with the **_view_** set to **_Pageviews_** and then **_filter_** set to: **_Page (contains)_** `acon/manager---community-partnerships-and-population-programs` or similar the escaping/encoding of the page path produces JSON as such:

```json
{
  "ids": "ga:XXXXXX",
  "start-date": "2005-01-01",
  "end-date": "today",
  "metrics": "ga:pageviews",
  "dimensions": "",
  "filters": "ga:pagePath=~(?i)acon/manager\\\\-\\\\-\\\\-community\\\\-partnerships\\\\-and\\\\-population\\\\-programs",
  "include-empty-rows": false,
  "max-results": 2000
}
```

This produces no results as the escaping of the filter is incorrect. `-` characters are being incorrectly escaped. When this query is converted to a native query and written as follows its successful.

```json
{
  "ids": "ga:XXXXXX",
  "start-date": "2005-01-01",
  "end-date": "today",
  "metrics": "ga:pageviews",
  "dimensions": "",
  "filters": "ga:pagePath=~(?i)acon\/manager---community-partnerships-and-population-programs",
  "include-empty-rows": false,
  "max-results": 2000
}
```

### Platform

- **Database:** Google Analytics
- **Metabase internal database:** MySQL
- **Metabase:** v0.30.3 (2018-09-13)
- **Environment:** Docker, Kubernetes

### LINKED ISSUE #12791: Extra ; in filters when using Date Between filter with Google Analytics Source
Hi 👋

When creating a question that use both date and string filters, an extra `;` is set at the beginning of filters. Date is considered as a different filter I guess (`start_date` and `end_date`). 

Server logs : 
```
2020-06-26T16:53:32.983674+00:00 app[web.1]: 06-26 16:53:32 DEBUG middleware.log :: GET /api/database 200 738.0 ms (18 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (2 idle, 0 queued) (138 total active threads) Queries in flight: 0 (0 queued)
2020-06-26T16:53:33.008043+00:00 app[web.1]: 06-26 16:53:33 DEBUG middleware.log :: GET /api/database 200 761.9 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (3 idle, 0 queued) (138 total active threads) Queries in flight: 0 (0 queued)
2020-06-26T16:53:33.547334+00:00 heroku[router]: at=info method=GET path="/api/table/370/query_metadata" host=lcds-reports.herokuapp.com request_id=425fefff-a49e-4e47-91d3-ac63226448c6 fwd="91.169.250.171" dyno=web.1 connect=0ms service=132ms status=200 bytes=16739 protocol=https
2020-06-26T16:53:33.481974+00:00 app[web.1]: 06-26 16:53:33 DEBUG middleware.log :: GET /api/table/370/query_metadata 200 52.8 ms (8 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (138 total active threads) Queries in flight: 0 (0 queued)
2020-06-26T16:53:33.951212+00:00 heroku[router]: at=info method=GET path="/app/dist/947e87c53b5765bfc8982613ccd789e9.woff2" host=lcds-reports.herokuapp.com request_id=59cb8a6c-ead1-4e5f-afaa-9caeeebd6f79 fwd="91.169.250.171" dyno=web.1 connect=0ms service=25ms status=200 bytes=23621 protocol=https
2020-06-26T16:53:35.649962+00:00 heroku[router]: at=info method=POST path="/api/dataset" host=lcds-reports.herokuapp.com request_id=95b26899-9693-4189-adec-be9dc600f280 fwd="91.169.250.171" dyno=web.1 connect=1ms service=1715ms status=202 bytes=3528 protocol=https
2020-06-26T16:53:35.633828+00:00 app[web.1]: 06-26 16:53:35 ERROR middleware.catch-exceptions :: Error processing query: null
2020-06-26T16:53:35.633832+00:00 app[web.1]: {:database_id 14,
2020-06-26T16:53:35.633832+00:00 app[web.1]: :started_at (t/zoned-date-time "2020-06-26T16:53:33.956Z[Etc/UTC]"),
2020-06-26T16:53:35.633833+00:00 app[web.1]: :json_query
2020-06-26T16:53:35.633833+00:00 app[web.1]: {:type "query",
2020-06-26T16:53:35.633834+00:00 app[web.1]: :query
2020-06-26T16:53:35.633834+00:00 app[web.1]: {:source-table 370,
2020-06-26T16:53:35.633835+00:00 app[web.1]: :aggregation [["metric" "ga:sessions"]],
2020-06-26T16:53:35.633836+00:00 app[web.1]: :filter ["and" ["between" ["datetime-field" ["field-id" 5717] "minute"] "2020-06-17T18:00:00" "2020-07-16"] ["contains" ["field-id" 5657] "groupama" {:case-sensitive false}]],
2020-06-26T16:53:35.633836+00:00 app[web.1]: :breakout [["field-id" 5657]],
2020-06-26T16:53:35.633836+00:00 app[web.1]: :order-by [["asc" ["field-id" 5657]]]},
2020-06-26T16:53:35.633837+00:00 app[web.1]: :database 14,
2020-06-26T16:53:35.633837+00:00 app[web.1]: :parameters [],
2020-06-26T16:53:35.633838+00:00 app[web.1]: :middleware {:add-default-userland-constraints? true}},
2020-06-26T16:53:35.633838+00:00 app[web.1]: :native
2020-06-26T16:53:35.633838+00:00 app[web.1]: {:query
2020-06-26T16:53:35.633839+00:00 app[web.1]: {:end-date "2020-07-15",
2020-06-26T16:53:35.633839+00:00 app[web.1]: :include-empty-rows false,
2020-06-26T16:53:35.633840+00:00 app[web.1]: :filters ";ga:sourceMedium=~(?i)groupama",
2020-06-26T16:53:35.633840+00:00 app[web.1]: :max-results 10000,
2020-06-26T16:53:35.633840+00:00 app[web.1]: :ids "ga:213307164",
2020-06-26T16:53:35.633841+00:00 app[web.1]: :dimensions "ga:sourceMedium",
2020-06-26T16:53:35.633841+00:00 app[web.1]: :start-date "2020-06-17",
2020-06-26T16:53:35.633841+00:00 app[web.1]: :metrics "ga:sessions",
2020-06-26T16:53:35.633842+00:00 app[web.1]: :sort "ga:sourceMedium"},
2020-06-26T16:53:35.633842+00:00 app[web.1]: :mbql? true},
2020-06-26T16:53:35.633845+00:00 app[web.1]: :status :failed,
2020-06-26T16:53:35.633845+00:00 app[web.1]: :class java.lang.IllegalArgumentException,
2020-06-26T16:53:35.633845+00:00 app[web.1]: :stacktrace
2020-06-26T16:53:35.633846+00:00 app[web.1]: ["com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)"
2020-06-26T16:53:35.633846+00:00 app[web.1]: "com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:47)"
2020-06-26T16:53:35.633847+00:00 app[web.1]: "com.google.api.services.analytics.Analytics$Data$Ga$Get.setFilters(Analytics.java:465)"
2020-06-26T16:53:35.633847+00:00 app[web.1]: "--> driver.googleanalytics$mbql_query__GT_request.invokeStatic(googleanalytics.clj:128)"
2020-06-26T16:53:35.633847+00:00 app[web.1]: "driver.googleanalytics$mbql_query__GT_request.invoke(googleanalytics.clj:112)"
2020-06-26T16:53:35.633848+00:00 app[web.1]: "driver.googleanalytics$execute_STAR_.invokeStatic(googleanalytics.clj:151)"
2020-06-26T16:53:35.633848+00:00 app[web.1]: "driver.googleanalytics$execute_STAR_.invoke(googleanalytics.clj:149)"
2020-06-26T16:53:35.633849+00:00 app[web.1]: "driver.googleanalytics.execute$execute_reducible_query.invokeStatic(execute.clj:125)"
2020-06-26T16:53:35.633849+00:00 app[web.1]: "driver.googleanalytics.execute$execute_reducible_query.invoke(execute.clj:122)"
2020-06-26T16:53:35.633850+00:00 app[web.1]: "driver.googleanalytics$eval2916$fn__2917.invoke(googleanalytics.clj:155)"
2020-06-26T16:53:35.633850+00:00 app[web.1]: "query_processor.context$executef.invokeStatic(context.clj:59)"
2020-06-26T16:53:35.633850+00:00 app[web.1]: "query_processor.context$executef.invoke(context.clj:48)"
2020-06-26T16:53:35.633851+00:00 app[web.1]: "query_processor.context.default$default_runf.invokeStatic(default.clj:69)"
2020-06-26T16:53:35.633851+00:00 app[web.1]: "query_processor.context.default$default_runf.invoke(default.clj:67)"
2020-06-26T16:53:35.633852+00:00 app[web.1]: "query_processor.context$runf.invokeStatic(context.clj:45)"
2020-06-26T16:53:35.633852+00:00 app[web.1]: "query_processor.context$runf.invoke(context.clj:39)"
2020-06-26T16:53:35.633853+00:00 app[web.1]: "query_processor.reducible$pivot.invokeStatic(reducible.clj:34)"
2020-06-26T16:53:35.633853+00:00 app[web.1]: "query_processor.reducible$pivot.invoke(reducible.clj:31)"
2020-06-26T16:53:35.633854+00:00 app[web.1]: "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43003.invoke(mbql_to_native.clj:26)"
2020-06-26T16:53:35.633854+00:00 app[web.1]: "query_processor.middleware.check_features$check_features$fn__42317.invoke(check_features.clj:42)"
2020-06-26T16:53:35.633856+00:00 app[web.1]: "query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43168.invoke(optimize_datetime_filters.clj:133)"
2020-06-26T16:53:35.633856+00:00 app[web.1]: "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47065.invoke(wrap_value_literals.clj:137)"
2020-06-26T16:53:35.633857+00:00 app[web.1]: "query_processor.middleware.annotate$add_column_info$fn__40946.invoke(annotate.clj:577)"
2020-06-26T16:53:35.633857+00:00 app[web.1]: "query_processor.middleware.permissions$check_query_permissions$fn__42192.invoke(permissions.clj:64)"
2020-06-26T16:53:35.633857+00:00 app[web.1]: "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43667.invoke(pre_alias_aggregations.clj:40)"
2020-06-26T16:53:35.633858+00:00 app[web.1]: "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42390.invoke(cumulative_aggregations.clj:61)"
2020-06-26T16:53:35.633858+00:00 app[web.1]: "query_processor.middleware.resolve_joins$resolve_joins$fn__44199.invoke(resolve_joins.clj:183)"
2020-06-26T16:53:35.633859+00:00 app[web.1]: "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39133.invoke(add_implicit_joins.clj:245)"
2020-06-26T16:53:35.633859+00:00 app[web.1]: "query_processor.middleware.limit$limit$fn__42989.invoke(limit.clj:38)"
2020-06-26T16:53:35.633860+00:00 app[web.1]: "query_processor.middleware.format_rows$format_rows$fn__42970.invoke(format_rows.clj:81)"
2020-06-26T16:53:35.633860+00:00 app[web.1]: "query_processor.middleware.desugar$desugar$fn__42456.invoke(desugar.clj:22)"
2020-06-26T16:53:35.633860+00:00 app[web.1]: "query_processor.middleware.binning$update_binning_strategy$fn__41490.invoke(binning.clj:229)"
2020-06-26T16:53:35.633861+00:00 app[web.1]: "query_processor.middleware.resolve_fields$resolve_fields$fn__41998.invoke(resolve_fields.clj:24)"
2020-06-26T16:53:35.633862+00:00 app[web.1]: "query_processor.middleware.add_dimension_projections$add_remapping$fn__38669.invoke(add_dimension_projections.clj:272)"
2020-06-26T16:53:35.633868+00:00 app[web.1]: "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__38889.invoke(add_implicit_clauses.clj:147)"
2020-06-26T16:53:35.633868+00:00 app[web.1]: "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39282.invoke(add_source_metadata.clj:105)"
2020-06-26T16:53:35.633869+00:00 app[web.1]: "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__43864.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)"
2020-06-26T16:53:35.633869+00:00 app[web.1]: "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41131.invoke(auto_bucket_datetimes.clj:125)"
2020-06-26T16:53:35.633870+00:00 app[web.1]: "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42045.invoke(resolve_source_table.clj:46)"
2020-06-26T16:53:35.633870+00:00 app[web.1]: "query_processor.middleware.parameters$substitute_parameters$fn__43649.invoke(parameters.clj:97)"
2020-06-26T16:53:35.633870+00:00 app[web.1]: "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42097.invoke(resolve_referenced.clj:80)"
2020-06-26T16:53:35.633871+00:00 app[web.1]: "query_processor.middleware.expand_macros$expand_macros$fn__42712.invoke(expand_macros.clj:158)"
2020-06-26T16:53:35.633871+00:00 app[web.1]: "query_processor.middleware.add_timezone_info$add_timezone_info$fn__39313.invoke(add_timezone_info.clj:15)"
2020-06-26T16:53:35.633872+00:00 app[web.1]: "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__46949.invoke(splice_params_in_response.clj:32)"
2020-06-26T16:53:35.633873+00:00 app[web.1]: "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__43875$fn__43879.invoke(resolve_database_and_driver.clj:33)"
2020-06-26T16:53:35.633873+00:00 app[web.1]: "driver$do_with_driver.invokeStatic(driver.clj:61)"
2020-06-26T16:53:35.633873+00:00 app[web.1]: "driver$do_with_driver.invoke(driver.clj:57)"
2020-06-26T16:53:35.633874+00:00 app[web.1]: "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__43875.invoke(resolve_database_and_driver.clj:27)"
2020-06-26T16:53:35.633875+00:00 app[web.1]: "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__42918.invoke(fetch_source_query.clj:243)"
2020-06-26T16:53:35.633876+00:00 app[web.1]: "query_processor.middleware.store$initialize_store$fn__46958$fn__46959.invoke(store.clj:11)"
2020-06-26T16:53:35.633876+00:00 app[web.1]: "query_processor.store$do_with_store.invokeStatic(store.clj:46)"
2020-06-26T16:53:35.633876+00:00 app[web.1]: "query_processor.store$do_with_store.invoke(store.clj:40)"
2020-06-26T16:53:35.633877+00:00 app[web.1]: "query_processor.middleware.store$initialize_store$fn__46958.invoke(store.clj:10)"
2020-06-26T16:53:35.633878+00:00 app[web.1]: "query_processor.middleware.cache$maybe_return_cached_results$fn__41974.invoke(cache.clj:208)"
2020-06-26T16:53:35.633878+00:00 app[web.1]: "query_processor.middleware.validate$validate_query$fn__46967.invoke(validate.clj:10)"
2020-06-26T16:53:35.633878+00:00 app[web.1]: "query_processor.middleware.normalize_query$normalize$fn__43016.invoke(normalize_query.clj:22)"
2020-06-26T16:53:35.633879+00:00 app[web.1]: "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39151.invoke(add_rows_truncated.clj:36)"
2020-06-26T16:53:35.633879+00:00 app[web.1]: "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46934.invoke(results_metadata.clj:128)"
2020-06-26T16:53:35.633880+00:00 app[web.1]: "query_processor.middleware.constraints$add_default_userland_constraints$fn__42333.invoke(constraints.clj:42)"
2020-06-26T16:53:35.633880+00:00 app[web.1]: "query_processor.middleware.process_userland_query$process_userland_query$fn__43738.invoke(process_userland_query.clj:136)"
2020-06-26T16:53:35.633880+00:00 app[web.1]: "query_processor.middleware.catch_exceptions$catch_exceptions$fn__42276.invoke(catch_exceptions.clj:174)"
2020-06-26T16:53:35.633881+00:00 app[web.1]: "query_processor.reducible$async_qp$qp_STAR___37952$thunk__37953.invoke(reducible.clj:101)"
2020-06-26T16:53:35.633881+00:00 app[web.1]: "query_processor.reducible$async_qp$qp_STAR___37952.invoke(reducible.clj:107)"
2020-06-26T16:53:35.633882+00:00 app[web.1]: "query_processor.reducible$sync_qp$qp_STAR___37961$fn__37964.invoke(reducible.clj:133)"
2020-06-26T16:53:35.633882+00:00 app[web.1]: "query_processor.reducible$sync_qp$qp_STAR___37961.invoke(reducible.clj:132)"
2020-06-26T16:53:35.633882+00:00 app[web.1]: "query_processor$process_userland_query.invokeStatic(query_processor.clj:218)"
2020-06-26T16:53:35.633883+00:00 app[web.1]: "query_processor$process_userland_query.doInvoke(query_processor.clj:214)"
2020-06-26T16:53:35.633883+00:00 app[web.1]: "query_processor$fn__47133$process_query_and_save_execution_BANG___47142$fn__47145.invoke(query_processor.clj:233)"
2020-06-26T16:53:35.633884+00:00 app[web.1]: "query_processor$fn__47133$process_query_and_save_execution_BANG___47142.invoke(query_processor.clj:225)"
2020-06-26T16:53:35.633884+00:00 app[web.1]: "query_processor$fn__47177$process_query_and_save_with_max_results_constraints_BANG___47186$fn__47189.invoke(query_processor.clj:245)"
2020-06-26T16:53:35.633885+00:00 app[web.1]: "query_processor$fn__47177$process_query_and_save_with_max_results_constraints_BANG___47186.invoke(query_processor.clj:238)"
2020-06-26T16:53:35.633885+00:00 app[web.1]: "api.dataset$fn__50475$fn__50478.invoke(dataset.clj:52)"
2020-06-26T16:53:35.633890+00:00 app[web.1]: "query_processor.streaming$streaming_response_STAR_$fn__33990$fn__33991.invoke(streaming.clj:73)"
2020-06-26T16:53:35.633891+00:00 app[web.1]: "query_processor.streaming$streaming_response_STAR_$fn__33990.invoke(streaming.clj:72)"
2020-06-26T16:53:35.633891+00:00 app[web.1]: "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66)"
2020-06-26T16:53:35.633891+00:00 app[web.1]: "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64)"
2020-06-26T16:53:35.633892+00:00 app[web.1]: "async.streaming_response$do_f_async$fn__23079.invoke(streaming_response.clj:85)"],
2020-06-26T16:53:35.633892+00:00 app[web.1]: :context :ad-hoc,
2020-06-26T16:53:35.633893+00:00 app[web.1]: :error "Parameter filters must conform to the pattern ga:.+",
2020-06-26T16:53:35.633893+00:00 app[web.1]: :row_count 0,
2020-06-26T16:53:35.633893+00:00 app[web.1]: :running_time 0,
2020-06-26T16:53:35.633894+00:00 app[web.1]: :preprocessed
2020-06-26T16:53:35.633894+00:00 app[web.1]: {:type :query,
2020-06-26T16:53:35.633894+00:00 app[web.1]: :query
2020-06-26T16:53:35.633895+00:00 app[web.1]: {:source-table 370,
2020-06-26T16:53:35.633895+00:00 app[web.1]: :aggregation [[:aggregation-options [:metric "ga:sessions"] {:name "metric"}]],
2020-06-26T16:53:35.633895+00:00 app[web.1]: :filter
2020-06-26T16:53:35.633896+00:00 app[web.1]: [:and
2020-06-26T16:53:35.633896+00:00 app[web.1]: [:and
2020-06-26T16:53:35.633897+00:00 app[web.1]: [:>= [:datetime-field [:field-id 5717] :default] [:absolute-datetime (t/zoned-date-time "2020-06-17T18:00Z[Etc/UTC]") :default]]
2020-06-26T16:53:35.633897+00:00 app[web.1]: [:< [:datetime-field [:field-id 5717] :default] [:absolute-datetime (t/zoned-date-time "2020-07-16T00:01Z[Etc/UTC]") :default]]]
2020-06-26T16:53:35.633898+00:00 app[web.1]: [:contains [:field-id 5657] [:value "groupama" {:base_type :type/Text, :special_type :type/Category, :database_type "STRING"}] {:case-sensitive false}]],
2020-06-26T16:53:35.633898+00:00 app[web.1]: :breakout [[:field-id 5657]],
2020-06-26T16:53:35.633898+00:00 app[web.1]: :order-by [[:asc [:field-id 5657]]]},
2020-06-26T16:53:35.633899+00:00 app[web.1]: :database 14,
2020-06-26T16:53:35.633899+00:00 app[web.1]: :middleware {:add-default-userland-constraints? true},
2020-06-26T16:53:35.633899+00:00 app[web.1]: :info
2020-06-26T16:53:35.633900+00:00 app[web.1]: {:executed-by 2,
2020-06-26T16:53:35.633900+00:00 app[web.1]: :context :ad-hoc,
2020-06-26T16:53:35.633901+00:00 app[web.1]: :nested? false,
2020-06-26T16:53:35.633901+00:00 app[web.1]: :query-hash [-107, -95, -48, 31, -116, 109, 84, 105, -18, 30, -62, 9, -73, -84, -53, -66, 73, -118, 125, -56, -20, -15, 120, 120, 60, 13, 45, 31, 15, 82, 84, -54]},
2020-06-26T16:53:35.633902+00:00 app[web.1]: :constraints {:max-results 10000, :max-results-bare-rows 2000}},
2020-06-26T16:53:35.633902+00:00 app[web.1]: :data {:rows [], :cols []}}
2020-06-26T16:53:35.633903+00:00 app[web.1]: 
2020-06-26T16:53:35.646328+00:00 app[web.1]: 06-26 16:53:35 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.7 s (9 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (4 idle, 0 queued) (139 total active threads) Queries in flight: 0 (0 queued)
```
**To Reproduce**
1. Create a question using a google analytics source
2. Add a filter `Date between`
3. Add another filter, `Source contains` for instance
4. See error : `"filters": ";ga:source=~(?i)foobar",`

**Expected behavior**
We should have `"filters": "ga:source=~(?i)foobar",`

**Screenshots**
Quick screen shot about the generated code of the question : 
image

Metabase 0.35.3, installed on an Heroku instance

**Severity**
It is not that bad, because we don't use that many filters "date between" on google analytics source, and it can be easily corrected by converting the question into native query. It's pretty annoying to the non-technical users though 😅

### LINKED ISSUE #13361: Presto non-optimal timestamp column queries
Presto doesn't support pushing down functions to it's connectors (yet). That means that any parsing would have to happen on Presto itself instead of the remote connector/database, which when you're filtering would involve a full load of all the data into Presto (full table scan in other DBs). Metabase currently generated quieries like this for Presto:

```sql
# pushdown of date_trunc('hour', "druid"."table"."__time") doesn't happen
...
WHERE date_trunc('hour', "druid"."table"."__time")
BETWEEN date_trunc('hour', date_add('hour', -4, now())) AND date_trunc('hour', date_add('hour', -1, now())) LIMIT 2000
```

Which is something that has been brought up before (https://github.com/metabase/metabase/issues/4043, https://github.com/metabase/metabase/issues/9934 and more).

In short performance on all Metabase towards Presto involving timestamp columns will be exceedingly slow. Ideally Metabase would simply generate the aforementioned query like this:

```sql
...
WHERE "druid"."table"."__time"
BETWEEN date_trunc('hour', date_add('hour', -4, now())) AND date_trunc('hour', date_add('hour', -1, now())) LIMIT 2000
```

This could be a minutiae of code that hasn't yet reached the Presto driver, as seemingly this is what https://github.com/metabase/metabase/pull/10980 aimed to do.

### PR DESCRIPTION
**Pull request by camsaul**
1. Rename `optimize-datetime-filters` middleware -> `optimize-temporal-filters` (it's more accurate, because this also optimizes `date` or `time` filter clauses)
2. `optimize-temporal-filters` middleware now optimizes `relative-datetime` clauses (which represent a moment in time relative to when the query is ran, e.g. "last month") in addition to `absolute-datetime` clauses (which represent an absolute moment in time, e.g. `2021-02-15T14:40:00-08:00`) . This middleware rewrites queries so we filter against specific temporal ranges without casting the column itself, meaning we can leverage indexes on that column. See #11837 for more details
3. Added new `validate-temporal-bucketing` middleware that throws an Exception if you try to do something that makes no sense, e.g. bucket a `DATE` field by `:time` or a `TIME` field by `:month`. This is a better situation then running the query and waiting for the DB to complain. (In practice, I don't think the FE client would let you generate a query like this in the first place)
4. Fix random test failures for MySQL in `task-history-cleanup-test`

Implements #11837

I also fixed a couple of tiny Google Analytics bugs I came across while getting this working.

Fixes #8626 
Fixes #12791
Fixes #13361

### CODE REVIEW

**Comment by camsaul** [comment]
Need to merge #14838 to fix Mongo tests here

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj [hunk 1]
```diff
@@ -99,13 +154,16 @@
       (_ :guard (partial mbql.u/is-clause? (set (keys (methods optimize-filter)))))
       (if (can-optimize-filter? &match)
         (let [optimized (optimize-filter &match)]
+          (when-not optimized
```
Comment (dpsutton) [inline src/metabase/query_processor/middleware/optimize_temporal_filters.clj:157]: should this perhaps log `&match` and then fall back to the unoptimized filter?

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj [hunk 2]
```diff
@@ -99,13 +154,16 @@
...
+            (throw (ex-info (tru "Error optimizing temporal filter clause")
+                            {:clause &match})))
           (when-not (= &match optimized)
             (log/tracef "Optimized filter %s to %s" (pr-str &match) (pr-str optimized)))
           optimized)
         &match))))
 
 (defn optimize-temporal-filters
-  "Middlware that optimizes equality (`=` and `!=`) and comparison (`<`, `between`, etc.) filter clauses against
+  "Middlware that optimizes equality (`=` and `!=`) and comparison (`<`, `between`, etc.) filter clauses agat
```
Comment (dpsutton) [inline src/metabase/query_processor/middleware/optimize_temporal_filters.clj:166]: `against` -> `agat` looks accidental

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj (hunk 1 above)
Comment (camsaul) [reply src/metabase/query_processor/middleware/optimize_temporal_filters.clj:157]: yeah that's probably a better situation. I'll change it

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj (hunk 2 above)
Comment (camsaul) [reply src/metabase/query_processor/middleware/optimize_temporal_filters.clj:166]: Totally is. Oops. Not sure how I did that

**Comment by camsaul** [comment]
Someone please review 😢

File: modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj [hunk 3]
```diff
@@ -30,46 +30,45 @@
                                                          {:native [{:collection "wow"}]}}}))))))
 
 ;; disabled for now -- re-enable in #14835
```
Comment (jeff303) [inline modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj:32]: Can delete this comment now?

**Comment by jeff303** [comment]
> Someone please review 😢

Will take a look on Thursday morning.

File: modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj [hunk 4]
```diff
@@ -164,11 +167,11 @@
 
 (defmethod parse-filter :and
   [[_ & clauses]]
-  (str/join ";" (filter some? (map parse-filter clauses))))
+  (str/join ";" (remove str/blank? (map parse-filter clauses))))
```
Comment (jeff303) [inline modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj:170]: Purely for my own edification, why replace `filter some?` with `remove str/blank?`?

File: backend/mbql/src/metabase/mbql/schema.clj [hunk 5]
```diff
@@ -521,6 +521,7 @@
 (defclause <=, field OrderComparible, value-or-field OrderComparible)
 (defclause >=, field OrderComparible, value-or-field OrderComparible)
 
+;; :between is INCLUSIVE just like SQL !!!
 (defclause between field OrderComparible, min OrderComparible, max OrderComparible)
```
Comment (tsmacdonald) [inline backend/mbql/src/metabase/mbql/schema.clj:525]: Is `Comparible` misspelled on purpose? Should be `Comparable`

image

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj [hunk 6]
```diff
@@ -0,0 +1,205 @@
+(ns metabase.query-processor.middleware.optimize-temporal-filters
+  "Middlware that optimizes equality filter clauses agat bucketed temporal fields. See docstring for
```
Comment (jeff303) [inline src/metabase/query_processor/middleware/optimize_temporal_filters.clj:2]: "agat"?

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj [hunk 7]
```diff
@@ -0,0 +1,205 @@
...
+(defmethod temporal-value-lower-bound :relative-datetime
+  [[_ n unit] datetime-field-unit]
+  [:relative-datetime (if (= n :current) 0 n) (or unit datetime-field-unit)])
+
+(defmethod temporal-value-upper-bound :relative-datetime
+  [[_ n unit] datetime-field-unit]
+  [:relative-datetime (inc (if (= n :current) 0 n)) (or unit datetime-field-unit)])
+
+(defmulti ^:private optimize-filter
+  "Optimize a filter clause agat a bucketed `:datetime-field` clause and `:absolute-datetime` or `:relative-datetime`
```
Comment (jeff303) [inline src/metabase/query_processor/middleware/optimize_temporal_filters.clj:103]: "agat" again?  Just trying to understand in case it's a term I haven't heard.

File: modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj [hunk 8]
```diff
@@ -361,14 +384,16 @@
...
+            (remove
+             str/blank?
+             (for [[direction field] order-by]
+               (str (case direction
+                      :asc  ""
+                      :desc "-")
+                    (mbql.u/match-one field
+                      [:datetime-field _ unit] (unit->ga-dimension unit)
+                      [:aggregation index]     (mbql.u/aggregation-at-index query index)
+                      [& _]                    (->rvalue &match))))))}))
```
Comment (tsmacdonald) [inline modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj:396]: for my tasted I'd prefer a

```
(->> order-by
  (map ...)
  (remove str/blank?)
  (str/join ","))
  ```
  since I'm not a big fan of deeply-nested `for`s, but it doesn't really matter

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj [hunk 9]
```diff
@@ -0,0 +1,205 @@
...
+  (mbql.u/replace query
+    (_ :guard (partial mbql.u/is-clause? (set (keys (methods optimize-filter)))))
+    (or (when (can-optimize-filter? &match)
+          (u/prog1 (optimize-filter &match)
+            (if <>
+              (when-not (= &match <>)
+                (log/tracef "Optimized filter %s to %s" (pr-str &match) (pr-str <>)))
+              ;; if for some reason `optimize-filter` doesn't return an optimized filter clause, log and error and use
+              ;; the original. `can-optimize-filter?` shouldn't have said we could optimize this filter in the first
+              ;; place
```
Comment (jeff303) [inline src/metabase/query_processor/middleware/optimize_temporal_filters.clj:160]: For things like this, do we have a special way of marking/capturing the info for our own diagnostic purposes?

File: resources/migrations/000_migrations.yaml [hunk 10]
```diff
@@ -7933,6 +7933,29 @@ databaseChangeLog:
             newColumnName: semantic_type
             columnDataType: varchar(255)
 
+  # Change the TaskHistory timestamp columns to higher-resolution columns: on MySQL, they previously only had *second*
+  # resolution, which caused annoying test failures and made it hard to correctly sort tasks that happened in quick succession.
```
Comment (tsmacdonald) [inline resources/migrations/000_migrations.yaml:7937]: just had one of these failures on my own branch, excited they're getting fixed

File: test/metabase/query_processor/middleware/validate_temporal_bucketing_test.clj [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+  (mt/dataset attempted-murders
+    (mt/with-everything-store
+      (doseq [field-clause-type [:field-id :field-literal]]
+        (testing (format "With %s clauses" field-clause-type)
+          (letfn [(query [field unit]
+                    (mt/mbql-query attempts
+                      {:filter [:=
+                                [:datetime-field
+                                 (case field-clause-type
+                                   :field-id [:field-id (mt/id :attempts field)]
```
Comment (jeff303) [inline test/metabase/query_processor/middleware/validate_temporal_bucketing_test.clj:21]: nit: line up the `[:field-id...` with the `[:field-literal...` below it?

File: test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj [hunk 12]
```diff
@@ -214,3 +214,140 @@
...
+                 :filter       [:and
+                                [:>= [:datetime-field $date :default] [:relative-datetime -1 :month]]
+                                [:< [:datetime-field $date :default] [:relative-datetime 0 :month]]]}})
+             (:pre
+              (mt/test-qp-middleware
+               optimize-temporal-filters/optimize-temporal-filters
+               (mt/mbql-query checkins
+                 {:source-query
+                  {:source-table $$checkins
+                   :filter       [:= [:datetime-field  $date :month] [:relative-datetime -1 :month]]}}))))))))
```
Comment (jeff303) [inline test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj:353]: nit: extra space before `$date`

File: test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj [hunk 13]
```diff
@@ -214,3 +214,140 @@
...
+  (testing "Should flatten the `:filter` clause after optimizing"
+    (mt/$ids checkins
+      (is (= [:and
+              [:= $venue_id 1]
+              [:>= [:datetime-field $date :default] [:relative-datetime -1 :month]]
+              [:< [:datetime-field $date :default] [:relative-datetime 0 :month]]]
+             (optimize-temporal-filters
+              [:and
+               [:= $venue_id 1]
+               [:= [:datetime-field  $date :month] [:relative-datetime -1 :month]]]))))))
```
Comment (jeff303) [inline test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj:325]: nit: extra space before `$date`

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj [hunk 14]
```diff
@@ -0,0 +1,205 @@
...
+   (change-datetime-field-unit-to-default field)
+   (optimize-temporal-value-fn temporal-value (datetime-field-unit field))])
+
+(defmethod optimize-filter :<
+  [filter-clause]
+  (optimize-comparison-filter temporal-value-lower-bound filter-clause :<))
+
+(defmethod optimize-filter :<=
+  [filter-clause]
+  (optimize-comparison-filter temporal-value-upper-bound filter-clause :<))
```
Comment (jeff303) [inline src/metabase/query_processor/middleware/optimize_temporal_filters.clj:133]: At first blush, this looks like a mistake, even though I'm guessing it's intentional.  Both this (`:<=`) and the `:<` pass `:<` through to the `optimize-comparison-filter` call, which is confusing.

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj [hunk 15]
```diff
@@ -0,0 +1,205 @@
...
+
+(defmethod optimize-filter :>
+  [filter-clause]
+  (optimize-comparison-filter temporal-value-upper-bound filter-clause :>=))
```
Comment (jeff303) [inline src/metabase/query_processor/middleware/optimize_temporal_filters.clj:137]: Similar to above.  It's passing `:>=` through from the `:>` case.

File: test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj [hunk 16]
```diff
@@ -214,3 +214,140 @@
                                (t/zoned-date-time "2019-10-02T00:00Z[UTC]")]}
            (mt/$ids checkins
              (filter->sql [:between !day.date "2019-09-01" "2019-10-01"]))))))
+
+(deftest optimize-relative-datetimes-test
```
Comment (jeff303) [inline test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj:218]: I'm just noticing that everything here is operating on a `:month` resolution (as per the #11837 starter comment).  But does it make sense to also cover other resolutions, like `:hour`?  Or does `validate-temporal-bucketing-test` cover that same path?

**Review by jeff303 — APPROVED** [review]
Aside from the nits and questions for my own learning purposes, it looks good to me.

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj (hunk 14 above)
Comment (tsmacdonald) [reply src/metabase/query_processor/middleware/optimize_temporal_filters.clj:133]: note that some use `temporal-value-upper-bound` and some use `temportal-value-lower-bound`

**Review by tsmacdonald — APPROVED** [review]
Looks good to me, but definitely a new area of the codebase for me so take that with a big grain of salt

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj (hunk 7 above)
Comment (camsaul) [reply src/metabase/query_processor/middleware/optimize_temporal_filters.clj:102]: I think it was just a typo, I used that same sentence as the starting point for the docstring for both the namespace and that function

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj (hunk 9 above)
Comment (camsaul) [reply src/metabase/query_processor/middleware/optimize_temporal_filters.clj:159]: It will show up in the console, so hopefully someone will spot the error if it happens. We don't have any way to record the frequency of this happening, tho -- that's something that would be good to record

File: modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj (hunk 8 above)
Comment (camsaul) [reply modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj]: yeah, that would be nicer. I'll change it

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj (hunk 14 above)
Comment (camsaul) [reply src/metabase/query_processor/middleware/optimize_temporal_filters.clj:132]: It is intentional, if "month of myDate is before Feb 2021", then `myDate is <= 2021-03-01T00:00:00`

File: src/metabase/query_processor/middleware/optimize_temporal_filters.clj (hunk 15 above)
Comment (camsaul) [reply src/metabase/query_processor/middleware/optimize_temporal_filters.clj:136]: yup, it's intentional

File: test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj (hunk 16 above)
Comment (camsaul) [reply test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj:218]: that's a good point. I'll update the tests to cover all the supported units

**Comment by camsaul** [comment]
CI was passing a second ago, but Snowflake is currently over the quota after I committed some unrelated changes
