### PR TITLE
fix(sdk): Fix map visualizations breaking

### LINKED ISSUE #42767: Don't use relative link for geojson maps
From @oisincoveney 

Hey backend team! I have a quick question for y'all. Right now we're trying to embed a static dashboard using the Embedding SDK, but one snag that we found was that the geojson maps that we use for the visualizations aren't loading, since the links to the map are using a relative URL. That means that if a client has a map visualization on, for example, localhost:420420/admin/whatever, the SDK tried to fetch the map from localhost:420420/admin/whatever/app/assets/geojson/us-states.json .
I see that it's initialized to this relative url within the geojson.clj  file as a setting. Do you think we could do something to explicitly specify the backend URL so it looks like [MB_BACKEND_URL]/app/assets/geojson/us-states.json? Or is there something else that we should do?

### PR DESCRIPTION
**Pull request by oisincoveney**
Closes #42767

This PR adds a `metabaseInstanceUrl` key to the SDK slice of the store which we can then pass to the `ChoroplethMap` visualization component. We can then inject the instance URL to the link to the map visualizations.

### CODE REVIEW

File: enterprise/frontend/src/embedding-sdk/store/reducer.ts [hunk 1]
```diff
@@ -12,10 +12,14 @@ import { createAsyncThunk } from "metabase/lib/redux";
 import { getSessionTokenState } from "./selectors";
 
 const SET_LOGIN_STATUS = "sdk/SET_LOGIN_STATUS";
+const SET_METABASE_CLIENT_URL = "sdk/SET_METABASE_CLIENT_URL";
```
Comment (npretto) [inline enterprise/frontend/src/embedding-sdk/store/reducer.ts:15]: Not strictly related to this PR and we can address it later, but do we have any reason to create those consts?
I know they've been "a thing" in the past but now with redux toolkit we could just inline them in the createAction and save a few lines (and layers)

**Review by npretto — APPROVED** [review]
Left one comment about something else, but this solution looks good

**Comment by NevRA** [comment]
@oisincoveney can you merge it?
