### PR TITLE
[Notification] Fix query limit for alerts

### LINKED ISSUE #55522: Notifications limit result to 2k for raw and 10k for aggregate questions
### Describe the bug

When you send a Questions notification the result is truncated. Doesn't happen to subscriptions

### To Reproduce

1. Go to New -> Question -> Sample DB Analytics Events -> Send a pulse test.

You will see the resultant file is truncated to 2k but the actual Analytics Events has around 36k rows.

### Expected behavior

A file with 36k rows

### Logs

None that are relevant

### Information about your Metabase installation

```JSON
Happens on version 53 and master ... Isn't the case for version 52
```

### Severity

Could break internal process if users are dependent on those files 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/55522

Make sure we don't override the limit with the default value of 2k.

### CODE REVIEW

File: src/metabase/notification/payload/execute.clj [hunk 1]
```diff
@@ -255,16 +255,17 @@
...
-                                                              :process-viz-settings?             true
-                                                              :js-int-to-string?                 false
-                                                              :add-default-userland-constraints? false}
-                                                 :make-run      (fn make-run [qp _export-format]
-                                                                  (^:once fn* [query info]
-                                                                    (qp
-                                                                     (qp/userland-query query info)
-                                                                     nil)))))]
+                                                 :context     :pulse
+                                                 :constraints {}
```
Comment (qnkhuat) [inline src/metabase/notification/payload/execute.clj:259]: the fix is to add the constraints :)

**Review by crisptrutski — APPROVED** [review]
