### PR TITLE
Hide QB tutorial when Sample Dataset is deleted, warn when deleting Sample Dataset

### LINKED ISSUE #1774: QB Tutorial doesn't work properly when sample dataset isn't present
The QB Tutorial is dependent on having access to the sample dataset and the current code generates an error if it turns out there is no available Database of sample data.

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #1774

### CODE REVIEW

File: frontend/src/admin/databases/components/DeleteDatabaseModal.jsx [hunk 1]
```diff
@@ -52,6 +54,9 @@ export default class DeleteDatabaseModal extends Component {
                 closeFn={this.props.onClose}
             >
                 <div className="Form-inputs mb4">
+                    { database.name === "Sample Dataset" &&
```
Comment (agilliland) [inline frontend/src/admin/databases/components/DeleteDatabaseModal.jsx]: we should be checking for `database.is_sample` which is a more accurate way to tell if the database is the sample data.  the name is editable by the user.

File: frontend/src/home/components/Homepage.jsx [hunk 2]
```diff
@@ -25,26 +25,42 @@ export default class Homepage extends Component {
...
+        activity: PropTypes.array,
+        hasSampleDataset: PropTypes.bool,
+        fetchActivity: PropTypes.func.isRequired,
+        fetchRecentViews: PropTypes.func.isRequired,
+        fetchHasSampleDataset: PropTypes.func.isRequired
     };
 
+    async componentDidMount() {
+        try {
+            await this.props.fetchHasSampleDataset();
```
Comment (agilliland) [inline frontend/src/home/components/Homepage.jsx]: this feels a bit icky to me.  we are now requiring an api call to get the list of databases every time someone hits the homepage.  it would be nice if we could think of another way to get at this information.

File: frontend/src/admin/databases/components/DeleteDatabaseModal.jsx (hunk 1 above)
Comment (tlrobinson) [inline frontend/src/admin/databases/components/DeleteDatabaseModal.jsx]: Ok, fixed

File: frontend/src/home/components/Homepage.jsx (hunk 2 above)
Comment (tlrobinson) [inline frontend/src/home/components/Homepage.jsx]: There are a lot of places we reload data more often than we should. That doesn't mean this is a good thing, I just think we need to think about it on a broader scale at some point (soonish)

Comment (agilliland) [inline frontend/src/home/components/Homepage.jsx]: What if we simply added this as part of the MetabaseSettings and we include it in the values on window.MetabaseBootstrap?  

Doing that would mean we only have to call `MetabaseSettings.get('sample_data_available')` and you'd have the value you need and you'd never actually have to make a call to list the dbs.

Comment (tlrobinson) [inline frontend/src/home/components/Homepage.jsx]: Sure, except that will break for an admin who is adding/removing the Sample Dataset.

Comment (agilliland) [inline frontend/src/home/components/Homepage.jsx]: I suppose, but it's not really much of a practical scenario.  It's not all that likely that someone goes into the admin section and deletes the sample dataset, then goes out of the admin section and tries to run the QB tutorial.

We can also protect against that by calling `MetabaseSettings.setAll({sample_data_available: false})` when the sample data is deleted.

**Comment by tlrobinson** [comment]
Ok, updated to use @agilliland's approach, should be ready to go.
