### PR TITLE
Use actual time zone marker (Z) when parsing offset times

### LINKED ISSUE #53724: Dragging to zoom in chart sometimes has end time before start time
### Describe the bug

The time range in filters from zooming sometimes has the end time before the start time.

https://www.loom.com/share/ac6b56527d3e4c1e839c70e8407ca633?sid=e6d1371b-ffcd-4018-8606-6ffe9ac33ac2

### To Reproduce

1. New question
2. Orders table
3. aggregate count by created at:day
4. Visualize -- bar chart
5. Zoom in until you can zoom in on one day's bar
6. click and drag over one of the bars, but with little margin on either side
7. Notice the date range.

### Expected behavior

The date range should always have the start time before the end time.

### Logs

_No response_

### Information about your Metabase installation

```JSON
master: 0b4dd2e7568ca4bbdd78d3b2bf1a37a0a6720658
```

### Severity

annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by metamben**
Fixes #53724

### How to verify

Make sure you have a REPL with a non-zero offset time zone, pick a datetime for which the local and the GMT dates differ and try parsing with the different format strings in the Rich comment.

### CODE REVIEW

File: src/metabase/util/time/impl.cljs [hunk 1]
```diff
@@ -151,7 +151,7 @@
   (.local value))
 
 (def ^:private parse-time-formats
-  #js ["HH:mm:ss.SSS[Z]"
```
Comment (ranquild) [inline src/metabase/util/time/impl.cljs:154]: On FE we use `SSS[Z]` in many cases, especially in viz. It's unclear whether 1) this is a correct fix 2) if yes, it should probably be updated everywhere.

Comment (alxnddr) [reply src/metabase/util/time/impl.cljs:154]: @metamben could you please clarify for a frontend engineer what are the implications of these changes to what parts of the code? Frontend does use `[Z]` format in a few places but I do not understand if the PR changes affect these places. There are two specific for ECharts rendering which won't be affected as long as the data formats in datasets remain the same. And there is one usage in `frontend/src/metabase/lib/time.ts` that is used by formatting

Comment (metamben) [reply src/metabase/util/time/impl.cljs:154]: My change only affects parsing. My understanding is that when parsing with `[Z]` in the format, moment doesn't interpret the trailing `Z` as a timezone marker, and it parses as a local (date)time. My experience is that when formatting, the (date)times are formatted in `GMT` and `[Z]` adds the trailing `Z`.

The effect of the change is that Metabase lib should now parse (date)times with a trailing `Z` in the `GMT` timezone (as opposed to the local timezone).

> It's unclear whether 1) this is a correct fix

What is needed to convince ourselves? What are alternatives?

> 2) if yes, it should probably be updated everywhere.

My guess is that parsing with `[Z]` hardly does what was intended and should be updated.

Comment (alxnddr) [reply src/metabase/util/time/impl.cljs:154]: Understood, thank you! So now I'm confident this change won't affect the presentation layer. But I don't think I can meaningfully approve PR by myself as I'm not familiar with the area it actually impacts

**Review by bshepherdson — CHANGES_REQUESTED** [review]
I'm surprised this didn't impact any tests. Can we get a test run with this new behaviour? I'm not sure how readily we can set the time zone for a CLJS test run.

**Comment by metamben** [comment]
> I'm surprised this didn't impact any tests. Can we get a test run with this new behaviour? I'm not sure how readily we can set the time zone for a CLJS test run.

That's exactly why I haven't added that test yet. I'll look into what can be done. 👍

**Review by bshepherdson — APPROVED** [review]
