### PR TITLE
Fix - Redundant GET `/api/action` request when viewing non-model object details

### LINKED ISSUE #50266: Redundant GET `/api/action` request when viewing non-model object details
### Describe the bug

Image

### To Reproduce

1. Browse databases > Sample database > Orders
2. Click on "Product ID" cell in the first data row
3. Click "View details"

Observe network tab and see GET `/api/action` triggered even though it's not a model

### Expected behavior

GET `/api/action` should not be triggered

### Information about your Metabase installation

master, 9ed2c3a26fef60537e84e23168916249eec820df

### Severity

P3

### PR DESCRIPTION
**Pull request by kamilmielnik**
Fixes #50266

### How to verify

1. Browse databases > Sample database > Orders
2. Click on "Product ID" cell in the first data row
3. Click "View details"

Observe network tab in dev tools - there should be no GET `/api/action` request

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx [hunk 1]
```diff
@@ -244,16 +242,20 @@ export function ObjectDetailView({
     [zoomedRowID, followForeignKey],
   );
 
-  const areImplicitActionsEnabled =
+  const areImplicitActionsEnabled = Boolean(
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx:245]: The bug was that `areImplicitActionsEnabled` was `undefined` when `question` was `undefined` and then `useListActionsQuery` used `useEntityListQuery` which has a default value `enabled = true`.

Casting this to boolean is enough to fix the issue.

File: frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx [hunk 2]
```diff
@@ -244,16 +242,20 @@ export function ObjectDetailView({
...
+      question.supportsImplicitActions(),
+  );
 
-  const { data: actions = [] } = useActionListQuery({
-    enabled: areImplicitActionsEnabled,
-    query: { "model-id": question?.id() },
-  });
+  const modelId = question?.type() === "model" ? question.id() : undefined;
+
+  const { data: actions = [] } = useListActionsQuery(
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx:254]: Changed deprecated `useActionListQuery` to `useListActionsQuery`.

**Review by romeovs — APPROVED** [review]

**Review by filiphric — APPROVED** [review]
