### PR TITLE
Fix dashboard filter reordering/renaming

### LINKED ISSUE #10001: Missing Index props for the ParameterWidget in Parameters.jsx at line 166
Hi, I am just playing around and found out two big issues with I am working on the filter in dashboard.

I found that if you try to reorder the filter, other the filter box will hidden and cannot rearrange.

So I look into the sources code and found out the index props was missing in the file (see title).

Also when I try to rename the filter. The filter will be delete if I do the following step:
1. Ctrl + a to select all.
2. Press delete / backspace

I understand that the name should not be empty but I also thinks this is a issues to any type of users.

I added a alert for that when user try to clear the name but I don't thinks that is a correct way to handle this case. Do anybody have other idea?

### LINKED ISSUE #10299: Reordering fields in dashboard causes fields to disappear in edit mode
**Describe the bug**
In a dashboard that has many fields click the edit button and try to reorder one of the fields, it will cause other fields to disappear.

**Logs**
When clicking one of the fields to change its place it gives the error below in console:
```

Uncaught TypeError: Cannot read property 'id' of undefined
    at r.handleSortEnd (app-main.bundle.js?0d1325582067a4b57db2:5)
    at t.handleSortEnd (vendor.bundle.js?0d1325582067a4b57db2:1)
```

**To Reproduce**
Explained in the description above

**Expected behavior**
Reorder fields and place them anywhere we want without ever causing the fields to disappear.

**Screenshots**
1st-pic

2nd-pic

**Information about your Metabase Installation:**
- Your browser and the version: Chrome 75.0

- Your operating system: Ubuntu

- Your databases: Postgres

- Metabase version: 0.32.9

- Metabase hosting environment: Docker

- Metabase internal database: H2

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #10001 

That issue describes two problems:

1. Filters can't be dragged without disappearing.

There was a missing `index` prop. Adding that back fixes it.

2. Removing the filter name while editing removes filter

I moved the name into component state while editing. If onBlur, the name is still blank, it's replaced with "unnamed".

I think the issue with blank name was actually due to the slug rather than name, but it felt like it should be solved for name itself.

Resolves #10299

### CODE REVIEW

**Comment by flamber** [comment]
@paulrosenzweig Also fixes #10299

**Comment by flamber** [comment]
@paulrosenzweig A question, since I'm looking at preview2, it looks like the SQL widgets are using the same code now, since they now disappear in similar fashion when moved. Will this also resolve that? If so, then you can resolve 9357 and 7460 (not linking in case I'm wrong)

**Comment by paulrosenzweig** [comment]
@flamber thanks for flagging those!

Those are still broken on the branch for this PR, and it looks like they're also broken (but in different ways) on notebook-mode.

I guess we know it's not worth fixing those on master before notebook-mode is merged in then! 🤷‍♂

File: frontend/src/metabase/parameters/components/ParameterWidget.jsx [hunk 1]
```diff
@@ -111,9 +111,15 @@ export default class ParameterWidget extends Component {
                 p => p.name === parameter.name && p.id !== parameter.id,
               ),
             })}
-            value={parameter.name}
-            onChange={e => setName(e.target.value)}
-            onBlur={() => this.setState({ isEditingName: false })}
+            value={this.state.editingNameValue}
```
Comment (tlrobinson) [inline frontend/src/metabase/parameters/components/ParameterWidget.jsx]: I try to always declare every state property when defining state, so just add `editingNameValue: null` in the ` state = {` block at the top.

**Review by tlrobinson — CHANGES_REQUESTED** [review]

**Review by tlrobinson — APPROVED** [review]
