### PR TITLE
Show all "details-only" columns in the metadata tab of the DatasetEditor

### LINKED ISSUE #22521: Model becomes confusing, when Data Model column visibility is used
**Describe the bug**
Model becomes confusing, when Data Model column visibility is used. And makes it impossible to edit metadata correctly.
Not sure if this is both BE or FE.

**To Reproduce**
1. Question > Sample > Products - save as "Q1"
2. Question > Sample > Orders - join with Saved Question "Q1" - save as "Q2"
3. Admin > Data Model > Products > change visibility of Vendor to "Only in detail views"
4. Turn in a Model
5. Go back to the model > click "Edit query definition" - it looks like Vendor is included, but is not shown anywhere
image
6. Clicking Metadata and trying to select any of the last columns (eg. Rating) will mark the next column as selected.
image

Addition to step 6: It seems like this can sometimes cause the metadata sidebar to become blank in some situations, but I haven't been able to reproduce that consistently (only on some of my test setups):

https://user-images.githubusercontent.com/1447303/170826729-bbc20f3e-9582-42cb-838a-1ecdc68dbcac.mp4

**Information about your Metabase Installation:**
Tested 0.42.0 thru 0.43.0

**Additional context**
Likely very related to #22520

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/22521

### How this fix works:
Currently, the `Table` component hides columns by default if they have `visibility-type: "details-only"` in the `result_metadata` of the card. But columns _should_ be shown in the metadata tab, even if they're `"details-only"`. The missing columns were causing the bug because the DatasetEditor assumed that the all the columns in `result.data.result_metadata.columns` match up exactly with the columns shown in the `Table` component.

To use the example in the [issue](https://github.com/metabase/metabase/issues/22521), the Vendor column shouldn't be hidden at all, and it should appear in the metadata table:
image

This PR changes the `Table` component never filter "details-only" columns when the metadata tab is open.

**Context on how the columns in `Table` get filtered:**
The columns are determined as "enabled" or not in the table [here](https://github.com/metabase/metabase/blob/22521-metadata-tab-details-view-only/frontend/src/metabase/visualizations/visualizations/Table.jsx#L196), and finally filtered [here](https://github.com/metabase/metabase/blob/22521-metadata-tab-details-view-only/frontend/src/metabase/visualizations/visualizations/Table.jsx#L363). The `data` then gets passed from the `state` of the `Table` component [here](https://github.com/metabase/metabase/blob/22521-metadata-tab-details-view-only/frontend/src/metabase/visualizations/visualizations/Table.jsx#L399) into the child component for display. 

### How to verify:
Follow steps 1-5 in the issue.

Notice how the Vendor column isn't hidden in the "Metadata" tab, even though the "details-only" is set:
image

But if you switch to the "Query" tab, it is hidden:
Captura de Pantalla 2022-08-18 a las 21 42 32

Also, if you set "details-only" in on any other column in the metadata tab, the same logic applies.

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/Table.jsx [hunk 1]
```diff
@@ -185,7 +192,9 @@ export default class Table extends Component {
         cols.map(col => ({
           name: col.name,
           fieldRef: col.field_ref,
-          enabled: col.visibility_type !== "details-only",
+          enabled:
+            this.props.datasetEditorTab === "metadata" ||
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/visualizations/Table.jsx:196]: This seems to crash the app. As `settings` is static, so it has no access to table instances. i.e. `this.props` is `undefined` here. I'm not sure how to get around this yet.

**Review by WiNloSt — DISMISSED** [review]

File: frontend/src/metabase/visualizations/visualizations/Table.jsx [hunk 2]
```diff
@@ -432,3 +441,5 @@ export default class Table extends Component {
     );
   }
 }
+
+export default _.compose(connect(mapStateToProps))(Table);
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/visualizations/Table.jsx:445]: nit: since we're not wrapping Table inside more than 1 higher-order function yet, maybe it's better to leave out `compose`

```suggestion
export default connect(mapStateToProps)(Table);
```

File: frontend/src/metabase/visualizations/visualizations/Table.jsx (hunk 1 above)
Comment (calherries) [reply frontend/src/metabase/visualizations/visualizations/Table.jsx:196]: Right, makes sense. In that case, I need to repeat the same predicate in another place though. 
https://github.com/metabase/metabase/blob/b8339af7c629757dbe2e13e2a956ef442536ac69/frontend/src/metabase/visualizations/visualizations/Table.jsx#L404

Do you think it would be better to extract this predicate as a separate function?

File: frontend/src/metabase/visualizations/visualizations/Table.jsx (hunk 2 above)
Comment (calherries) [reply frontend/src/metabase/visualizations/visualizations/Table.jsx:445]: Makes sense. I was copying the style here, which could also do with changing:
https://github.com/metabase/metabase/blob/22521-metadata-tab-details-view-only/enterprise/frontend/src/metabase-enterprise/audit_app/containers/AuditTable.jsx#L98

File: frontend/src/metabase/visualizations/visualizations/Table.jsx (hunk 1 above)
Comment (WiNloSt) [reply frontend/src/metabase/visualizations/visualizations/Table.jsx:196]: > Do you think it would be better to extract this predicate as a separate function?

Good catch! I didn't realize it's used in other places too. Yeah let's extract the predicate into its own function so it could be reused.

Comment (calherries) [reply frontend/src/metabase/visualizations/visualizations/Table.jsx]: Actually, I realised I can replace that second predicate by looking to see if the columns in `data` are empty. So no need to extract it.

https://github.com/metabase/metabase/blob/cbf80a90d51970b23c7b4fd5971719ba631d1cfe/frontend/src/metabase/visualizations/visualizations/Table.jsx#L404

File: frontend/src/metabase/visualizations/visualizations/Table.jsx [hunk 3]
```diff
@@ -34,7 +37,11 @@ import cx from "classnames";
 
 import { getIn } from "icepick";
 
-export default class Table extends Component {
+const mapStateToProps = state => ({
+  datasetEditorTab: "qb" in state && getDatasetEditorTab(state),
+});
```
Comment (kulyk) [inline frontend/src/metabase/visualizations/visualizations/Table.jsx:42]: Why do we need to check if `qb` is in `state`? It should always be there

**Review by kulyk — CHANGES_REQUESTED** [review]
We should avoid tightening up the viz layer within an environment it is rendered in. Unfortunately, we don't have a good solution for that yet (there's in a [RFC](https://www.notion.so/metabase/Visualization-Context-c3527ed8b82b44428dac5b3eb281557f) about how can we address that though).

Could you please explore if we can avoid using `datasetEditorTab` directly in the viz component? It should be possible to add a `TableInteractive` prop like `hasDetailViewOnlyColumns` and then pass it down from the `DatasetEditor` component. You can take a look at [how `hasMetadataPopovers` prop is handled in a similar fashion](https://github.com/metabase/metabase/blob/d93e15b5a0e511cb978c157b3b140466f6d3eb16/frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx#L467). Also, heads-up, make sure to include a new prop into [this list](https://github.com/metabase/metabase/blob/d93e15b5a0e511cb978c157b3b140466f6d3eb16/frontend/src/metabase/query_builder/components/VisualizationResult.jsx#L14) to make sure it reaches the end viz

File: frontend/src/metabase/visualizations/visualizations/Table.jsx [hunk 4]
```diff
@@ -391,8 +401,7 @@ export default class Table extends Component {
     const [{ card }] = series;
     const sort = getIn(card, ["dataset_query", "query", "order-by"]) || null;
     const isPivoted = Table.isPivoted(series, settings);
-    const columnSettings = settings["table.columns"] || [];
-    const areAllColumnsHidden = !columnSettings.some(f => f.enabled);
+    const areAllColumnsHidden = data.cols.length === 0;
```
Comment (WiNloSt) [inline frontend/src/metabase/visualizations/visualizations/Table.jsx:404]: Tested that disabled columns don't show up in `data.cols`

**Review by WiNloSt — APPROVED** [review]
This is looking great 👍  Tested and I couldn't reproduce the bug anymore. But you might want to check my question about `datasetEditorTab` since I want the code to be clean, unless that guard check is really needed.

File: frontend/src/metabase/visualizations/visualizations/Table.jsx [hunk 5]
```diff
@@ -34,7 +37,11 @@ import cx from "classnames";
 
 import { getIn } from "icepick";
 
-export default class Table extends Component {
+const mapStateToProps = state => ({
+  datasetEditorTab: "qb" in state && getDatasetEditorTab(state),
```
[the remark this answers is not in the document]
Comment (calherries) [reply frontend/src/metabase/visualizations/visualizations/Table.jsx]: 1. Good to know you've never seen a guard check like this. There's probably a better way to fix this issue that doesn't require this kind of check.
2. This was failing in an e2e test (which I can't find anymore) where `qb` wasn't present on `state`.

Anyway, [my latest commit](https://github.com/metabase/metabase/pull/24882/commits/2a2d502b9914bb774cd7dbc548b041c165bd031d) replaces this use of `mapStateToProps` with prop drilling from `DatasetEditor`.

File: frontend/src/metabase/visualizations/visualizations/Table.jsx (hunk 3 above)
Comment (calherries) [reply frontend/src/metabase/visualizations/visualizations/Table.jsx]: There was an e2e test where this was failing because `qb` wasn't in `state`. I've replaced this anyway with prop drilling in my [latest commit](https://github.com/metabase/metabase/pull/24882/commits/2a2d502b9914bb774cd7dbc548b041c165bd031d).

**Review by kulyk — APPROVED** [review]
LGTM! Thanks for addressing the comments @calherries 🙏
