### PR TITLE
Ignore parameters targets with `stage-number` out of range

### LINKED ISSUE #55678: Applying Filter to Summarize Layer of Question Breaks Drill-through behaviour on Dashboard
### Describe the bug

Applying Filter to Summarize Layer of Question Breaks Drill-through behaviour on Dashboard

### To Reproduce

Hard to explain in words so sharing a video:

https://github.com/user-attachments/assets/4e2fd778-7840-4f21-bb7a-826e4dd06ca3

Also step by step:

1. Go to New -> Question -> Sample DB -> Products -> Count Group by Month
2. Add Question to a Dashboard -> Create a Date Filter on the Dashboard and link it to the Summarise Created:at of the Question
3. Select a value for the filter (last 12 months) then try to use Drill Through by clicking on the "See these Products"
4. Notice nothing happens and you get a console error

Note that the drill through works at question level for the same filter it just breaks when the filter is applied (and has a value) at dashboard level

### Expected behavior

Drill Through should work or if it doesn't then I shouldn't get the option

### Logs

No log errors so its a frontend issue but you see this in the Console tab:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'query')
    at Object.push (useQueries.js:81:58)
    at middleware.js:29:25
    at rtk-query.modern.mjs:2290:17
    at index.js:36:12
    at redux-thunk.mjs:7:12
    at dispatch (redux.mjs:371:38)
    at app.ts:57:7
    at redux-thunk.mjs:5:14
    at dispatch (redux.mjs:371:38)
    at navigation.js:61:9
```

### Information about your Metabase installation

```JSON
1.53.7.3 and master
```

### Severity

breaks functionality and it's confusing to figure out what might be going on

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Closes https://github.com/metabase/metabase/issues/55678

We can get into a state where there is a parameter target with a stage index outside the query stages. E.g. in the referenced P1 issue we modify the query via the underlying-records drill, which drops query stages, and now post-aggregation parameters targets become invalid. We need to ignore them in this case.

How to verify:
- Follow the steps from the issue
- The post-aggregation filter should not take affect when doing `underying-records` drill

### CODE REVIEW

File: frontend/src/metabase/parameters/utils/mapping-options.ts [hunk 1]
```diff
@@ -244,37 +244,48 @@ export function getMappingOptionByTarget(
   }
 
   const { query, columns } = getParameterColumns(question, parameter);
-  const stageIndexes = _.uniq(columns.map(({ stageIndex }) => stageIndex));
```
Comment (ranquild) [inline frontend/src/metabase/parameters/utils/mapping-options.ts:247]: The previous implementation was incorrect. It tried to match the field ref from the parameter target with mapping options for all stages in the query, ignoring the stage index set in the target. We need to match the parameter target with mapping options for the same stage only. Doing otherwise leads to incorrect matches.

File: frontend/src/metabase/querying/parameters/utils/query.ts [hunk 2]
```diff
@@ -59,6 +59,10 @@ export function applyParameter(
     return query;
   }
 
+  if (stageIndex >= Lib.stageCount(query)) {
```
Comment (ranquild) [inline frontend/src/metabase/querying/parameters/utils/query.ts:62]: Issue 2. We can get into a state where there is a parameter target with a stage index outside the query stages. E.g. in the referenced P1 issue we modify the query via the `underlying-records` drill, which drops query stages, and now post-aggregation parameters targets become invalid. We need to ignore them in this case.

File: e2e/test/scenarios/dashboard-filters-2/shared/dashboard-filters-query-stages.ts [hunk 3]
```diff
@@ -621,20 +621,17 @@ export function setup2ndStageAggregationFilter() {
     getPopoverList().scrollTo("bottom");
     getPopoverItem("Count", 1).click();
   });
-  dismissToast();
```
Comment (ranquild) [inline e2e/test/scenarios/dashboard-filters-2/shared/dashboard-filters-query-stages.ts:624]: The toast previously appeared because of over-matching. See my comment about `getMappingOptionByTarget`

**Review by uladzimirdev — APPROVED** [review]
