### PR TITLE
Fix LDAP admin settings form not allowing modification if a custom port is set

### LINKED ISSUE #41494: Error message in LDAP settings
### Describe the bug

Although everything should be set up correctly (it seems to work normally), a red error message "**e.ldap-port?.trim is not a function**" appears above the Save button. I didn't notice this in previous versions.

### To Reproduce

Settings is like:
FQDN for server name
636 for port
SSL
some LDAP user
some LDAP password
set Search base for user
set User filter
set Attribute for name

Appears only when creating mappings!

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
Metabase version v0.49.1 v0.49.4
```

### Severity

low

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sloansparger**
Closes #41494

### Description

Our TS types weren't matching reality if the user didn't change the port number and tries to modify + save the LDAP form after having already configured it. This was due to the server providing a number and the client wanting a string, which resulted in our `.trim` call during submission to fail. If the user re-enters the exact same port number that is already configured, the form would work as expected.

### How to verify

- setup a ldap locally via the admin settings
- refresh the page
- change something like the host from localhost to 0.0.0.0
- you should have seen an error before, but not with these changes

### Checklist

- [ ] ~Tests have been added/updated to cover changes in this PR~
I don't have a good way to test this given our e2e LDAP host is configured on the default port of 389, which ends up nulling out this value / avoiding the issue we're noticing (notice related issue has a different port number configured). I can spend more time there, but I think it would be better to spend the effort on converting some of our admin settings to typescript which would have surfaced this error via the type system.

### CODE REVIEW

File: frontend/src/metabase/admin/settings/components/SettingsLdapForm.tsx [hunk 1]
```diff
@@ -226,18 +226,27 @@ export const SettingsLdapFormView = ({
...
         : values[key],
     ]),
   );
+
+  return {
+    ...attributeValues,
+    // ldap port is number | null, we need to edit as a string if it is a number
+    "ldap-port":
+      typeof attributeValues["ldap-port"] === "number"
+        ? "" + attributeValues["ldap-port"]
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/SettingsLdapForm.tsx:247]: what about ?
```suggestion
        String(attributeValues["ldap-port"])
```

**Review by iethree — APPROVED** [review]
💖

File: frontend/src/metabase/admin/settings/components/SettingsLdapForm.tsx [hunk 2]
```diff
@@ -226,18 +226,27 @@ export const SettingsLdapFormView = ({
 
 const getAttributeValues = (
   ldapAttributes: SettingKey[],
-  settings: Record<string, LdapFormSettingElement>,
+  settings: Record<SettingKey, LdapFormSettingElement>,
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/SettingsLdapForm.tsx:229]: 😢  type error

Comment (sloansparger) [reply frontend/src/metabase/admin/settings/components/SettingsLdapForm.tsx:229]: oh didn't mean to commit this... oops

**Comment by sloansparger** [comment]
@metabase-bot backport release-x.49.x
