### PR TITLE
fix: allow update last_used_at in read-only mode

### LINKED ISSUE #47376: Cloud migration read-only mode prevents middleware.update-used-cards
### Describe the bug

We put the app-db in readonly mode when doing a cloud migration. But there are some exceptions to this: we want to register usages, record field values, but we don't want to create new records in the core tables. To allow for this we have some exceptions to read-only mode: https://github.com/metabase/metabase/blob/master/src/metabase/models/cloud_migration.clj#L89-L99

We should make the middleware.update-used-cards not throw exceptions

```
2024-08-28 12:41:21,673 ERROR middleware.update-used-cards :: Error updating used cards
clojure.lang.ExceptionInfo: Metabase is in read-only-mode mode! {:status-code 403, :toucan2/context-trace [["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}] ["resolve connection" {:toucan2.connection/connectable :default}] ["resolve connection" {:toucan2.connection/connectable nil}] ["with resolved query" {:toucan2.pipeline/resolved-query {}}] ["with parsed args" {:toucan2.pipeline/query-type :toucan.query-type/update.update-count, 
```

### Expected behavior

not entirely sure.

Start a cloud migration and then trigger the update-used-cards middleware

### Logs

_No response_

### Information about your Metabase installation

```JSON
v50
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edpaget**
Closes https://github.com/metabase/metabase/issues/47376

### Description

We want to allow the last_used_at field on a card to be set for logging purposes during cloud migrations. We don't otherwise want to allow changes to card models for the creation of new models during the migration. 

To support this I updated the read-only mode exemption check to use a map of table names to either a a keyword `:all` to indicate any column could be changed (or that new records could be created/deleted) or a set of columns that are allowed to be in a change. The set of columns implicitly disallows creates/deletes because the `:changes` keyword is only included from toucan on updates.  

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Start a cloud migration
2. Look at some cards

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Review by filipesilva — APPROVED** [review]
LGTM, thanks for pinging me for review.

File: test/metabase/query_processor/middleware/update_used_cards_test.clj [hunk 1]
```diff
@@ -108,4 +109,16 @@
         (is (= now
                (-> (t2/select-one-fn :last_used_at :model/Card card-id-2)
                    t/offset-date-time
-                   (.withNano 0))))))))
+                   (.withNano 0))))))
+    (testing "if metabase is in read only mode still set the last_used_at timestamp"
+      (mt/with-temp
+        [:model/Card {card-id-1 :id} {:last_used_at one-hour-ago}]
+        (try
+          (cloud-migration/read-only-mode! true)
```
Comment (johnswanson) [inline test/metabase/query_processor/middleware/update_used_cards_test.clj:117]: We have a nice utility function for this, `(mt/with-temporary-setting-values [read-only-mode true] ...)`, that makes this a little cleaner (and makes it harder to forget to reset the setting when you're done testing 😅).

**Review by johnswanson — APPROVED** [review]
LGTM, one small suggestion to use `mt/with-temporary-setting-values`

File: test/metabase/query_processor/middleware/update_used_cards_test.clj (hunk 1 above)
Comment (edpaget) [reply test/metabase/query_processor/middleware/update_used_cards_test.clj:117]: Thanks I will swap for that. I had just looked at how it was tested in the cloud-migration tests, so I'll update those too.
