### PR TITLE
fix(sdk): upgrade D3.js to the latest version for Vite compatibility

### LINKED ISSUE #44392: Update D3.js to a newer version for Vite compatibility in embedding sdk
We want to unblock embedding SDK customers who are using Vite, which uses Rollup and ESBuild under the hood.

The incompability with Vite was caused by the very old version of D3.js that cannot be bundled by Rollup, the bundler used by Vite under the hood, which results in a [runtime error](https://stackoverflow.com/questions/56400413/d3-js-runtime-error-after-upgrade-to-angular-8). We're using D3.js version 3.5.17, released 8 years ago.

> [StackOverflow](https://stackoverflow.com/questions/35560305/d3-js-uncaught-typeerror-cannot-read-property-document-of-undefined): It sounds like [[Rollup](https://github.com/evanw/esbuild/issues/2264)] is inserting "use strict"; at the beginning of the D3 script file or combining it into another file with "use strict" at the top. That means this at global scope (or in a function called without a specific this) is no longer a reference to the global object, it's undefined. Whereas in "loose" mode or in a function called with no specific this value, this at global scope is a reference to the global object, which is also accessible via the global variable `window1.

### The most minimal version possible to upgrade

D3 version 4.0 changes to ES6 Strict Mode, so 4.0 is the lowest possible version that enables Vite to work.

> D3 now ships as pure ES modules and requires Node.js 12 or higher. For more, please read [Sindre Sorhus’s FAQ](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). [snip] The adoption of ES6 modules also means that D3 is now written exclusively in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) and has better readability. Refer to https://github.com/d3/d3/blob/main/CHANGES.md

### PR DESCRIPTION
**Pull request by heypoom**
Closes https://github.com/metabase/metabase/issues/44392

### Description

Upgrades the D3.js libraries and its usages to the latest version. See [the issue](https://github.com/metabase/metabase/issues/44392) and [the RFC](https://www.notion.so/metabase/106-Upgrade-D3-js-version-to-unblock-Vite-compatibility-for-embedding-SDK-9698ae61ee394446898c6c059d9c530b?pvs=4) for more information.

- Changes the method namespaces to the new flattened version (e.g. `scale.linear` to `scaleLinear`)
- Removed `d3-shape` from dependencies and replaced it with `d3` as it causes unit tests on pie charts to fail, likely due to conflicts
- Uses `scaleLinear(domain, range)` for type inference instead of `scaleLinear().domain(domain).range(range)`
- Replace the removed `d3.round` with a custom `roundFloat`
- Fix TypeScript type changes (e.g. for D3 Arc)

### How to verify

Re-test the affected viz and code paths that are using D3.js:

- Pie Chart
- Row Chart
- Heat Map, Choropleth Map
- Gauge
- Cartesian Chart
- Formatting: Geography, Numbers

### Demo

CleanShot 2567-06-22 at 01 38 19@2x

CleanShot 2567-06-25 at 01 08 10@2x

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/ChoroplethMap.jsx [hunk 1]
```diff
@@ -41,10 +41,10 @@ export function getColorplethColorScale(
...
   const darkColor = Color(color).darken(darken).saturate(saturate);
 
-  const scale = d3.scale
-    .linear()
-    .domain([0, 1])
-    .range([lightColor.string(), darkColor.string()]);
+  const scale = d3.scaleLinear(
+    [0, 1],
+    [lightColor.string(), darkColor.string()],
+  );
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/components/ChoroplethMap.jsx:47]: TypeScript is willing to interpret strings as ranges when using the `scaleLinear(domain, range)` api, but it throws a type error when using `scaleLinear().domain(...).range(...)`, as it expects the range to be numbers only.

File: frontend/src/metabase/visualizations/components/ChoroplethMap.jsx [hunk 2]
```diff
@@ -63,12 +63,13 @@ const geoJsonCache = new Map();
...
-      geoJsonCache.set(geoJsonPath, json);
-      callback(json);
-    });
+    return;
   }
+
+  d3.json(geoJsonPath).then(json => {
+    geoJsonCache.set(geoJsonPath, json);
+    callback(json);
+  });
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/components/ChoroplethMap.jsx:72]: callback is deprecated by `d3.json`, it now supports Promises only.

File: frontend/src/metabase/lib/formatting/numbers.tsx [hunk 3]
```diff
@@ -45,6 +45,17 @@ const NUMBER_REGEX = /([\+\-])?[^0-9]*([0-9\., ]+)/;
 
 const DEFAULT_NUMBER_SEPARATORS = ".,";
 
+// TODO: unit test this!
```
Comment (heypoom) [inline frontend/src/metabase/lib/formatting/numbers.tsx:48]: to unit test this.

File: frontend/src/metabase/visualizations/components/ChoroplethMap.jsx [hunk 4]
```diff
@@ -201,13 +202,13 @@ class ChoroplethMapInner extends Component {
     let projection, projectionFrame;
     // projectionFrame is the lng/lat of the top left and bottom right corners
     if (settings["map.region"] === "us_states") {
-      projection = d3.geo.albersUsa();
+      projection = d3.geoAlbersUsa();
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/components/ChoroplethMap.jsx:205]: Newer versions of D3 now flattens the namespaces (e.g. `geo.albersUsa` becomes `geoAlbersUsa`)

File: frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts [hunk 5]
```diff
@@ -191,7 +191,10 @@ function generateSplits(
 
 function axisCost(extents: Extent[], favorUnsplit = true) {
   const axisExtent = d3.extent(extents.flatMap(e => e));
-  const axisRange = axisExtent[1] - axisExtent[0];
+
+  // TODO: handle cases where members of axisExtent is undefined
+  const axisRange = axisExtent[1]! - axisExtent[0]!;
```
Comment (heypoom) [inline frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts:196]: the undefined case was never handled in the original code.

File: frontend/src/metabase/lib/formatting/numbers.tsx [hunk 6]
```diff
@@ -141,7 +142,7 @@ export function formatNumber(
       // fall back to old, less capable formatter
       // NOTE: does not handle things like currency, percent
       return FIXED_NUMBER_FORMATTER(
-        d3.round(number, options.maximumFractionDigits),
+        roundFloat(number, options.maximumFractionDigits),
```
Comment (heypoom) [inline frontend/src/metabase/lib/formatting/numbers.tsx:145]: `d3.round` has been removed with no alternatives, so we have to write this ourselves.

File: .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png
Comment (heypoom) [inline .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png:1]: Notice that the "-476.8" label was showing before, but it is gone now. Might need some help from dashviz folks as I'm not sure where to begin.

CleanShot 2567-06-24 at 21 02 20@2x

File: package.json [hunk 7]
```diff
@@ -42,10 +42,8 @@
     "cronstrue": "^2.11.0",
     "crossfilter": "^1.3.12",
     "csv-parse": "^5.5.6",
-    "d3": "^3.5.17",
-    "d3-array": "^3.1.1",
-    "d3-scale": "^3.3.0",
-    "d3-shape": "^3.1.0",
```
Comment (heypoom) [inline package.json:48]: This caused unit test errors in Pie Charts where `d3Arc(slice)` throws a Path error, where error messages points to `d3-shape`. Removing this fixes the issue.

**Comment by heypoom** [comment]
There is a bug caught by the Loki visual tests. You can see that the "-476.8" label was showing before, but it is gone now. I'll likely likely need some pointers from dashviz folks as I'm not sure where to begin; this looks like a sneaky bug 🙏🏻 

CleanShot 2567-06-24 at 21 02 20@2x

File: frontend/test/metabase/lib/formatting.unit.spec.js [hunk 8]
```diff
@@ -95,15 +95,15 @@ describe("formatting", () => {
       });
       it("shouldn't display small numbers as 0", () => {
         expect(formatNumber(0.1, { compact: true })).toEqual("0.1");
-        expect(formatNumber(-0.1, { compact: true })).toEqual("-0.1");
+        expect(formatNumber(-0.1, { compact: true })).toEqual("−0.1");
         expect(formatNumber(0.01, { compact: true })).toEqual("0.01");
-        expect(formatNumber(-0.01, { compact: true })).toEqual("-0.01");
+        expect(formatNumber(-0.01, { compact: true })).toEqual("−0.01");
```
Comment (heypoom) [inline frontend/test/metabase/lib/formatting.unit.spec.js:100]: D3 v6 uses the minus sign instead of the hyphen-minus for negative numbers. That was a fun bug to track. https://github.com/d3/d3-format/issues/62

U+002D: HYPHEN-MINUS {hyphen, dash; minus sign}
U+2212: MINUS SIGN

**Comment by heypoom** [comment]
Getting a `security/snyk` error, will try to get access to Snyk to investigate.

File: .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png
Comment (heypoom) [inline .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png:1]: see comment here https://github.com/metabase/metabase/pull/44562#issuecomment-2187152609

Comment (alxnddr) [reply .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png:1]: This is due to the minus sign get slightly bigger so it would start overlapping with the previous data label

**Review by alxnddr — APPROVED** [review]

File: .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png
Comment (heypoom) [reply .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png:1]: @alxnddr oh my god, I would have never noticed that 🤯

thanks!

**Review by deniskaber — APPROVED** [review]
Awesome work! 🥇
