### PR TITLE
Fix segment editing

### LINKED ISSUE #11343: Can't edit segment
After creating a Segment in the Admin panel, editing it is not possible. E.g. changing filter doesn't take effect, or trying to edit the name doesn't work. It seems like a front-end problem, because it doesn't let me delete the name or enter a reason for change.

I'm on Metabase v0.33.4 and tried with Firefox and Chrome on Mac.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Resolves #11343 

The recursive metadata structures led to an infinite loop somewhere in redux form's deep equals comparison. This PR just uses _plainObject instead and adds an update test.

### CODE REVIEW

File: frontend/src/metabase/admin/datamodel/containers/MetricForm.jsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ import Table from "metabase-lib/lib/metadata/Table";
       return errors;
     },
   },
-  (state, { metric }) => ({ initialValues: metric }),
+  (state, { metric }) => ({ initialValues: metric && metric._plainObject }),
```
Comment (tlrobinson) [inline frontend/src/metabase/admin/datamodel/containers/MetricForm.jsx]: I think I would prefer if we assumed `MetricForm` took the non-wrapped object and instead unwrapped it in `MetricApp`:

```js
@Metrics.load({
  id: (state, props) => parseInt(props.params.id),
  wrapped: true,
})
@Tables.load({ id: (state, props) => props.metric.table_id, wrapped: true })
@withTableMetadataLoaded
class UpdateMetricForm extends Component {
  onSubmit = async metric => {
    await this.props.metric.update(metric);
    MetabaseAnalytics.trackEvent("Data Model", "Metric Updated");
    const { id: tableId, db_id: databaseId } = this.props.table;
    this.props.onChangeLocation(
      `/admin/datamodel/database/${databaseId}/table/${tableId}`,
    );
  };

  render() {
    const { metric, ...props } = this.props;
    return <MetricForm {...props} metric={metric.getPlainObject()} onSubmit={this.onSubmit} />;
  }
}
```

**Review by tlrobinson — CHANGES_REQUESTED** [review]

File: frontend/src/metabase/admin/datamodel/containers/MetricForm.jsx (hunk 1 above)
Comment (paulrosenzweig) [reply frontend/src/metabase/admin/datamodel/containers/MetricForm.jsx]: 👍I like that more.

Unrelated to the fix, but I also unwrapped them (in the entity sense) since those methods were only used once.

**Review by tlrobinson — APPROVED** [review]
