### PR TITLE
fix(sdk): Fix the empty container detection in SDK question layouts

### LINKED ISSUE #70391: StaticQuestion layout has empty space when TopBar has no children
### Describe the bug

 StaticQuestion layout has empty space when TopBar has no children

Image

### To Reproduce

Can be reproduced on Shoppy

### Expected behavior

There should be no empty space when TopBar is not visible

### Logs

_No response_

### Information about your Metabase installation

```JSON
na
```

### Severity

p2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sanex3339**
The PR fixes the empty container detection in SDK question layouts

Fixes https://github.com/metabase/metabase/issues/70391

We introduced a regression in 59:
- even when the TopBar does not have children we still rendered it in DOM
- this was causing the wrong grid layout selection, so the top-row for the TopBar was rendered

The PR replaces the hook with HideIfEmpty component that still uses observer but does not render children if children of observed element are not rendered

Before:
image

After:
image

### CODE REVIEW

File: frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+ *
+ * This is useful with CSS `:has()` selectors that rely on the wrapper's class
+ * being absent when content is empty (e.g., grid layout adjustments).
+ */
+export function HideIfEmpty<C extends ElementType>({
+  component: Component,
+  children,
+  ...props
+}: HideIfEmptyProps<C>) {
+  const [node, setNode] = useState<HTMLElement | null>(null);
```
Comment (npretto) [inline frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx]: Shouldn't this be a ref?

File: frontend/src/embedding-sdk-bundle/components/private/HideIfEmpty/HideIfEmpty.tsx [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+
+/**
+ * Renders children inside the given `component` when they have visible content.
+ * When children are empty, renders a hidden sentinel `<div>` to keep observing
+ * for content changes, while removing the styled wrapper from the DOM entirely.
+ *
+ * This is useful with CSS `:has()` selectors that rely on the wrapper's class
+ * being absent when content is empty (e.g., grid layout adjustments).
+ */
+export function HideIfEmpty<C extends ElementType>({
```
Comment (npretto) [inline frontend/src/embedding-sdk-bundle/components/private/HideIfEmpty/HideIfEmpty.tsx]: Isn't the name misleading?
This doesn't "hide", it actually not renders the children

File: frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx (hunk 1 above)
Comment (sanex3339) [reply frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx]: we need to trigger re-render on ref change

File: frontend/src/embedding-sdk-bundle/components/private/HideIfEmpty/HideIfEmpty.tsx (hunk 2 above)
Comment (sanex3339) [reply frontend/src/embedding-sdk-bundle/components/private/HideIfEmpty/HideIfEmpty.tsx]: Renamed to RenderIfHasContent

**Review by heypoom — APPROVED** [review]
Tested locally /w the new ref callback implementation, works:

Have scrollbar (correct):

Image

No scrollbar (correct):

Image

File: frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx (hunk 1 above)
Comment (sanex3339) [reply frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx]: Committed approach suggested by @heypoom

File: frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+    );
+  }
+
+  return createElement(Component, { ...props, ref: refCallback }, children);
+}
+
+/**
+ * Elements that are visually meaningful even without text content.
+ */
+const REPLACED_ELEMENTS = new Set([
```
Comment (WiNloSt) [inline frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx:65]: not sure what "replaced" is supposed to mean in this context.

File: frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+
+  const children = Array.from(element.children);
+
+  // Leaf node: check for direct text content
+  if (children.length === 0) {
+    return !!element.textContent?.trim();
+  }
+
+  return children.some((child) => {
+    const el = child as HTMLElement;
```
Comment (WiNloSt) [inline frontend/src/embedding-sdk-bundle/components/private/RenderIfHasContent/RenderIfHasContent.tsx:86]: nit 
```suggestion
    const element = child as HTMLElement;
```

**Review by WiNloSt — COMMENTED** [review]
Tested. This works great.
