### PR TITLE
Make Usage Analytics work on mysql

### LINKED ISSUE #61331: Usage Analytics, Metabase Metrics collection questions fail with MySQL:8.0.28
### Describe the bug

When Metabase’s application database is MySQL (8.x), Usage analytics Metabase metrics cards that groups or filters on a timestamp fails.

SQL issue in Metabase:
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'timestamptz) AS timestamp, count(distinct source.user_id) AS count FROM at line 2`

Image

I believe the issue arises when casting by 'TimestampWithLocalTZ', here:
`CAST(source.timestamp AS timestamptz) AS timestamp`.

CAST( … AS timestamptz ) doesn't seem to be a part of the accepted target types for CAST() in MySQL: [https://dev.mysql.com/doc/refman/8.4/en/cast-functions.html](https://dev.mysql.com/doc/refman/8.4/en/cast-functions.html)

### To Reproduce

1. Spin up Metabase with MySQL version 8.0.28 as the app db
2. Go to Usage Analytics > Metabase Metrics

### Expected behavior

Using this against the app-db worked fine:
`CAST(qe.started_at AS DATETIME) AS started_at_local`

### Logs

*No response*

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2025-07-18",
      "tag": "v1.55.8.4",
      "hash": "362bae8"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "5.15.49-linuxkit",
    "user.language": "en",
    "user.timezone": "Asia/Seoul"
  }
}
```

### Severity

p2

### Additional context

*No response*

### PR DESCRIPTION
**Pull request by escherize**
closes #61331
resolves DEV-778

  ### Problem
  Usage Analytics (Instance Analytics > Metabase Metrics) queries were failing on MySQL 8.0.28 with SQL syntax errors. The root cause was that the audit database contains PostgreSQL-specific field types (like
   `timestamptz`, `int4`, `float8`, etc.) from the serialized metadata, which MySQL doesn't recognize.

  ### Solution
  After installing the audit database and adjusting it for the host database engine, we now sync the database to update field metadata to match the actual host database types. This ensures fields get the
  correct types for the target database (e.g., `datetime` instead of `timestamptz` for MySQL).

  ### Changes
  - Added automatic database sync after audit DB installation
  - Sync runs asynchronously to avoid blocking startup
  - Sync runs without logs to keep output clean
  - Re-fetches the database after engine adjustment to ensure we sync with updated engine value

  ### Impact
  - Fixes Most[1] Usage Analytics queries on MySQL 8.0.28
  - Resolves P1 escalation from enterprise customer
  - Should also fix similar issues on H2 and other non-PostgreSQL databases
  - Prevents "Unknown column" and SQL syntax errors in analytics queries

  ### Testing
  - Verified Usage Analytics > Metabase Metrics loads correctly on MySQL 8.0.28
  - Confirmed field types are properly updated after sync
  - Other analytics pages (Content with cobwebs, Performance overview) may need additional fixes in follow-up PRs

[1] - This is a targeted fix for the immediate P1 issue. On mysql 8.0.28, 2 cards on the `Usage Analytics` > `Performance overview` have problems due to mysql not handling `PERCENTILE_CONT` function. The work required to add that feature is non trivial, and this PR fixes most of the usage analytics and will unblock folks.

### CODE REVIEW

**Review by dpsutton — APPROVED** [review]

File: enterprise/backend/src/metabase_enterprise/audit_app/audit.clj [hunk 1]
```diff
@@ -265,8 +267,22 @@
             (do
               (log/info (str "Loading Analytics Content Complete (" (count (:seen report)) ") entities loaded."))
               (audit/last-analytics-checksum! current-checksum))))
-        (when-let [audit-db (t2/select-one :model/Database :is_audit true)]
-          (adjust-audit-db-to-host! audit-db))))))
+        (when-let [{:keys [engine] :as audit-db} (t2/select-one :model/Database :is_audit true)]
+          (let [original-engine engine]
+            (adjust-audit-db-to-host! audit-db)
+            ;; Only sync if we actually changed the engine type
+            (when (not= original-engine (name (mdb/db-type)))
```
Comment (dpsutton) [inline enterprise/backend/src/metabase_enterprise/audit_app/audit.clj]: calling `(name (mdb/db-type))` will give us a string, but the `engine` key coming from `t2` will always be a keyword. As such this will always be false and this body will always run.

Comment (escherize) [reply enterprise/backend/src/metabase_enterprise/audit_app/audit.clj]: good catch, fixed

File: enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj [hunk 2]
```diff
@@ -31,6 +34,9 @@
   (mt/test-drivers #{:postgres :h2 :mysql}
     (audit-test/with-audit-db-restoration
       (mt/with-premium-features #{:audit-app}
+        (is (= "complete"
```
Comment (dpsutton) [inline enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj]: i'm surprised this poll-until needs to be here. Why does this block when in testing?

Comment (escherize) [reply enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj]: This might be left in accidentally, I'll remove it
