### PR TITLE
Fix waterfall visualization with ordinal and numeric X-axis

### LINKED ISSUE #15550: Waterfall visualization does not work with ordinal X-axis
**Describe the bug**
Waterfall visualization does not work with ordinal X-axis

**To Reproduce**
1. Go to Native query question page
2. Run the following query:
```
select 0 as "a", 1 as "b" union all
select 1 as "a", 2 as "b" union all
select 5 as "a", 3 as "b"
```
3. Select Waterfall visualization mode and specify X-axis to be `a` and Y-axis to be `b`
4. Go to Axes -> X-axis scale: change it to Ordinal

**Actual behavior**
The chart is not visible, there is an error in the console
`Cannot read property 'data' of undefined`

**Expected behavior**
The chart is rendered

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/15550

**Problem**
Waterfall visualization does not work with ordinal and numeric X-axis.

**Root cause**
Total values are used with `crossfilter`'s  `dimension` and `group` methods.  `dimension` has limitations https://github.com/square/crossfilter/wiki/API-Reference#dimension, most notably issues with mixed types, and the previous solution with static `Total` string didn't work when `xValues` were numeric. It made `group` treat `Total` as the last numeric value in the series, but `Total` should be a unique column by itself.

**Solution**
To not change the whole processing logic, we need to come with a unique value that will satisfy limitations of `dimension`. The exact value is not important, but:
1. It must be unique among `xValues`
2. If `xValues` are numbers, it must be a number or a numeric string
3. If `xValues` are strings, it must be a string

This fix:
1. Finds the max value for `xValues` in way that works both for numbers and strings
2. Adds `1` to the value, which would work correctly for a number or a string
3. Please note that `xValues` can be unsorted, so using the last value is incorrect.

**How to test manually**
1. Go to Native query question page
2. Run the following query:
```
select 0 as "a", 1 as "b" union all
select 1 as "a", 2 as "b" union all
select 5 as "a", 3 as "b"
```
3. Select Waterfall visualization mode and specify X-axis to be `a` and Y-axis to be `b`
4. Go to Axes -> X-axis scale: change it to Ordinal

**Notes**
The total behavior for `quantitative` and `histogram` waterfall charts are also broken, I'm going to fix it separately.

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/apply_axis.js [hunk 1]
```diff
@@ -301,6 +302,12 @@ export function applyChartOrdinalXAxis(
 
   const dimensionColumn = firstSeries.data.cols[0];
 
+  const waterfallTotalX =
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/lib/apply_axis.js:305]: Same condition used in other types of axises

File: frontend/src/metabase/visualizations/lib/renderer_utils.js [hunk 2]
```diff
@@ -346,10 +345,14 @@ export function xValueForWaterfallTotal({ settings, series }) {
     const lastXValue = xValues[xValues.length - 1];
     return lastXValue.clone().add(count, interval);
   } else if (isQuantitative(settings) || isHistogram(settings)) {
-    return xValues[xValues.length - 1] + xInterval;
+    const lastXValue = xValues[xValues.length - 1];
+    return lastXValue + xInterval;
+  } else if (isOrdinal(settings)) {
+    const maxXValue = xValues.reduce((a, b) => (a > b ? a : b), xValues[0]);
```
Comment (alxnddr) [inline frontend/src/metabase/visualizations/lib/renderer_utils.js:351]: What do you think about using `Math.max(...xValues)` for a bit better readability?


Also, maybe returning `Infinity` here would be fine even though it is hackish. Infinity value can't come from the back end, in a super rare case with `maxXValue === Number.MAX_SAFE_INTEGER` it will still work correctly. And it can be readable enough if we define it as a constant `frontend/src/metabase/lib/constants.js` with an explanation similarly to `NULL_NUMERIC_VALUE`

**Review by alxnddr — COMMENTED** [review]
Checked locally, works great! I left a couple of suggestions in comments

**Review by alxnddr — APPROVED** [review]
👍
