### PR TITLE
Fix druid-jdbc issues

### LINKED ISSUE #42237: [BE] [QP] Metrics aren't working for Druid (old driver)
The test `metabase.driver.druid.query-processor-test/metrics-inside-aggregation-clauses-test` is failing because the (old) druid driver doesn't support nested queries.  This test is now commented out.

There are several ways to "fix" this:
1. Change QP to optimize "v1 metric" queries semantics to non-nested queries.
2. Migrate the test to the new JDBC druid driver and if that works, tell users to switch to it (this has to be discussed with the success team).
3. Lose metric support for druid (this has to be discussed with the success team).

### PR DESCRIPTION
**Pull request by metamben**
Fixes #42237.

### CODE REVIEW

**Review by camsaul — APPROVED** [review]

File: modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc/nested_field_columns_test.clj [hunk 1]
```diff
@@ -15,6 +15,7 @@
 (set! *warn-on-reflection* true)
 
 (deftest ^:parallel json-details-only-test
+  (is (= 0 1) "the nested test gets invoked")
```
Comment (camsaul) [inline modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc/nested_field_columns_test.clj:18]: shouldn't this fail? 😱

Comment (metamben) [reply modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc/nested_field_columns_test.clj:18]: Well spotted! I had doubts the tests actually run, so I added a couple of forced failures. As you see, they are not failing. Something to look into...
