### PR TITLE
fix: Remove help email from error diagnostic modal

### LINKED ISSUE #44150: Remove help@metabase.com from Error Diagnostic Modal
We want to avoid getting a deluge of emails from customers without support plans.

see [discussion](https://metaboat.slack.com/archives/C013N8XL286/p1718285213011609?thread_ts=1718284371.001519&cid=C013N8XL286)

### PR DESCRIPTION
**Pull request by rafpaf**
Closes #44150

### CODE REVIEW

**Comment by rafpaf** [comment]
* **#44165** <a href="https://app.graphite.dev/github/pr/metabase/metabase/44165?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sloansparger — APPROVED** [review]

File: frontend/src/metabase/components/ErrorPages/ErrorDiagnosticModal.tsx [hunk 1]
```diff
@@ -266,12 +242,7 @@ export const ErrorExplanationModal = ({
       </Text>
       <Text my="md">
         {c("indicates an email address to which to send diagnostic information")
```
Comment (iethree) [inline frontend/src/metabase/components/ErrorPages/ErrorDiagnosticModal.tsx:244]: i think this context is no longer relevant, also, we probably only need `t` instead of `jt` since we're no longer interpolating a link

**Review by iethree — APPROVED** [review]
❤️  LGTM, but run by success real quick before merging

File: frontend/src/metabase/components/ErrorPages/ErrorPages.tsx [hunk 2]
```diff
@@ -19,8 +19,8 @@ import {
 import { ErrorPageRoot } from "./ErrorPages.styled";
 
 export const GenericError = ({
-  title = t`Something's gone wrong`,
-  message = t`We've run into an error. You can try refreshing the page, or just go back.`,
+  title = t`Something’s gone wrong`,
```
Comment (iethree) [inline frontend/src/metabase/components/ErrorPages/ErrorPages.tsx:22]: I think you broke an e2e test with this change
