### PR TITLE
Fix broken force migration

### LINKED ISSUE #32115: Force migration is broken
### Describe the bug

We introduced Custom migrations in https://github.com/metabase/metabase/pull/28175 which is a way for us to write migrations in Clojure. 

Now if you have an unrun migrations and it's a custom-migration, Doing a force migration will run all `custom migrations` first, then run the `sql` ones regardless of the order we defined it.

Meaning using force migration will:
- execute migrations in undefined orders
- Create incorrect data to the appDB and it's irreversible

### To Reproduce

1. Checkout this branch `reproduce-broken-force-migration` ([the diff](https://github.com/metabase/metabase/compare/reproduce-broken-force-migration?expand=1))
2. Run force migration with `clojure -M:run migrate force`
3. Check the log you will see
```
START EXECUTING a custom migration
INSERTED a database with id 5
DONE!
2023-07-04 17:48:06,371 INFO db.liquibase :: Start running force migrations
....
migration fails
```

Notice:
- we execute custom migration before `start running force migrations`
- In the branch, I intentionally wrote a migration that will fail when execute, which cause the whole command to fail. But if you do `select count(*) from metabasee_databse where id <whatever-the-id-you-got-from-log>`, it'll return 1. which means the result of the custom migration is persisted!

### Expected behavior

we should fix the migration to make it runs in exact order, or remove this feature.

### Logs
```
2023-07-04 17:48:04,491 INFO db.setup :: Setting up Liquibase...
2023-07-04 17:48:04,620 INFO db.setup :: Liquibase is ready.
START EXECUTING a custom migration
2023-07-04 17:48:06,251 INFO driver.impl :: Initializing driver :sql...
2023-07-04 17:48:06,252 INFO driver.impl :: Initializing driver :sql-jdbc...
2023-07-04 17:48:06,252 INFO driver.impl :: Initializing driver :postgres...
2023-07-04 17:48:06,356 INFO task.sync-databases :: Scheduling sync/analyze for database 5: trigger: metabase.task.sync-and-analyze.trigger.5
2023-07-04 17:48:06,357 INFO task.sync-databases :: Scheduling field-values for database 5: trigger: metabase.task.update-field-values.trigger.5
INSERTED a database with id 5
DONE!
2023-07-04 17:48:06,371 INFO db.liquibase :: Start running force migrations
2023-07-04 17:48:06,372 INFO db.liquibase :: UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = '192.168.1.102 (192.168.1.102)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;
2023-07-04 17:48:06,374 INFO db.liquibase :: [SUCCESS]
2023-07-04 17:48:06,374 INFO db.liquibase :: INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v47.00-051', 'qnkhuat', 'migrations/000_migrations.yaml', NOW(), 623, '8:bedaee9df6474603401ac5730bcacf2a', 'customChange', 'Added 0.47.0 -', 'EXECUTED', NULL, NULL, '4.11.0', '8467686032');
2023-07-04 17:48:06,375 INFO db.liquibase :: [SUCCESS]
2023-07-04 17:48:06,375 INFO db.liquibase :: ALTER TABLE "public"."metabase_table" ADD "is_upload" BOOLEAN DEFAULT FALSE NOT NULL;
org.postgresql.util.PSQLException: ERROR: ROLLBACK TO SAVEPOINT can only be used in transaction blocks
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgConnection.execSQLUpdate(PgConnection.java:560)
        at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:1810)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:1007)
        at metabase.db.liquibase$eval65584$force_migrate_up_if_needed_BANG___65589$fn__65590$fn__65595.invoke(liquibase.clj:178)
        at metabase.db.liquibase$eval65584$force_migrate_up_if_needed_BANG___65589$fn__65590.invoke(liquibase.clj:174)
        at metabase.db.liquibase$eval65584$force_migrate_up_if_needed_BANG___65589.invoke(liquibase.clj:151)
        at metabase.db.setup$eval66880$migrate_BANG___66885$fn__66886$fn__66887.invoke(setup.clj:79)
        at metabase.db.liquibase$eval65518$do_with_liquibase__65523$fn__65524.invoke(liquibase.clj:64)
        at metabase.db.liquibase$eval65518$do_with_liquibase__65523.invoke(liquibase.clj:56)
        at metabase.db.setup$eval66880$migrate_BANG___66885$fn__66886.invoke(setup.clj:73)
```
### Information about your Metabase installation

```JSON
master
```

### Severity

Not sure how often this feature is used, but if it's used then it'll cause irreversible change to the AppDB, which is bad.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/32115

The force migration will now attempt to run each migration in order, if one fails, it ignores and moves on to the next migration.

The explanation for the changes:
- previously, the way we execute force migration is by getting all the unrun migrations, converting them to SQL, then execute those statements manually
- But in we introduced https://github.com/metabase/metabase/pull/28175 which is a way for us to write migrations in Clojure, this breaks force migrations because:
  - In the process of generating SQL to execute, the custom migrations will be executed by liquibase, This is unexpected for us because we want to execute migration ourselves. This result in migrations being executed in an incorrect order: Custom migrations, then SQLs
  - What's worse is those custom migrations do not run in a transaction. Meaning if it fails their operations will still be committed.

That said, I've made the change so that force migration now will execute one 1 migration at a time using Liquibase API. This way whether it's a SQL or custom migration, it doesn't matter. We still archive the original goal of force migration:
- bypass the lock ( we force release the lock before executing )
- Run migration individually in order, if one fails, ignore then move on to the next.

### CODE REVIEW

File: src/metabase/db/custom_migrations.clj [hunk 1]
```diff
@@ -42,7 +42,8 @@
   `(defrecord ~name []
      CustomTaskChange
      (execute [_# database#]
-       ~migration-body)
+       (t2/with-transaction [_conn#]
```
Comment (qnkhuat) [inline src/metabase/db/custom_migrations.clj:45]: run each custom migrations in a transaction to prevent it from commit prematurelly if error happens

File: src/metabase/db/liquibase.clj [hunk 2]
```diff
@@ -79,37 +84,14 @@
     (fn [~(vary-meta liquibase-binding assoc :tag (symbol (.getCanonicalName Liquibase)))]
       ~@body)))
 
-(defn migrations-sql
```
Comment (qnkhuat) [inline src/metabase/db/liquibase.clj:82]: moved down

File: src/metabase/db/liquibase.clj [hunk 3]
```diff
@@ -118,6 +100,34 @@
...
+      (catch Exception e
+        (log/error e (trs "Unable to release the Liquibase lock after a migration failure"))))))
+
+(defn migrations-sql
+  "Return a string of SQL containing the DDL statements needed to perform unrun `liquibase` migrations.
+  Note that custom migrations are not included."
+  ^String [^Liquibase liquibase]
+  ;; calling update on custom migrations will execute them, and we don't want it to happen
+  ;; so ignore its
+  (doseq [^ChangeSet change (.listUnrunChangeSets liquibase nil nil)]
```
Comment (qnkhuat) [inline src/metabase/db/liquibase.clj:124]: without doing this, whenever calling `migrations-sql` all the custom migrations will be executed, but not the SQL ones

**Review by camsaul — APPROVED** [review]
Cool, this looks good to me. Adding tests around this stuff is definitely a huge improvement.

I did want to mention that MySQL is snippy about doing DDL inside transactions, so I think we're going to run into problems if we try to do anything like that programmatically inside a Clojure migration, but I think maybe this is actually a good thing since we should be doing that stuff in Liquibase anyway

File: test/metabase/db/force_migration_test.clj [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+                {:name   "Greek"
+                 :period "1500BC"})
+    (throw (ex-info "Intentionally throw an error" {}))))
+
+(custom-migrations/define-migration SuccessCustomMigration
+  (t2/insert! :ancient_civilization
+              {:name "Egypt"
+               :period "3100BC"}))
+
+;; This tests test 4 things:
```
Comment (qnkhuat) [inline test/metabase/db/force_migration_test.clj:32]:
```suggestion
;; This test tests 4 things:
```
