### PR TITLE
fix add series modal

### LINKED ISSUE #15222: Corrupted question shows "Something's gone wrong" with no more info, and breaks "Add series" modal on the dashboard, and breaks Archive page
Steps to repro:

1.  Go to <horror-show>/question/1472 
2. See "Something's gone wrong" page with no more info. 
3. `Cannot read property 'type' of null` in the browser console. API response is a 200

I suspect it can't read the empty viz settings or something? We should have better error handling around this, and more graceful fallback, an maybe more info for debugging purposes. Not sure what's part of the data it doesn't like, but I think it should still be able to render the rest of the page

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by alxnddr**
Add a couple of try-catch blocks to the AddSeries modal to avoid the app crashing when anything is wrong with questions' queries or their metadata.

### CODE REVIEW

**Comment by alxnddr** [comment]
@metabase-bot backport release-x.45.x

**Comment by alxnddr** [comment]
@metabase-bot backport release-x.45.x

**Comment by alxnddr** [comment]
@metabase-bot backport release-x.45.x

**Comment by paoliniluis** [comment]
Just tried this branch and it LGTM
image

**Review by dragonsahead — APPROVED** [review]

File: frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.jsx [hunk 1]
```diff
@@ -83,17 +83,38 @@ export const QuestionList = React.memo(function QuestionList({
...
+        try {
+          return isQuestionCompatible(
+            visualization,
+            dashcard,
+            dashcardData,
+            question,
+          );
+        } catch (e) {
+          console.warn(
+            `Could not check question compatibility for a question with id=${question?.id?.()}`,
```
Comment (npfitz) [inline frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.jsx:96]: Should we be adding console messages for things like this?

Comment (alxnddr) [reply frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.jsx:96]: It will help us identify ids of problematic questions, which is a part of https://github.com/metabase/metabase/issues/26507

Comment (paoliniluis) [reply frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.jsx:96]: ❤️
