### PR TITLE
Change the remaning columns that has text type in mysql,mariadb to longtext

### LINKED ISSUE #26212: Changing permissions can fail with `Data too long for column 'before' at row 1` when using MySQL/MariaDB application database
**Describe the bug**
Changing permissions can fail with `Data too long for column 'before' at row 1` when using MySQL/MariaDB application database.
Repeat of #7006/#13088 - I'm unsure how those two table was missed.

**Workaround**
Manually change the TEXT to LONGTEXT, and BLOB to LONGBLOB - run this query on the Metabase application database:
```mysql
-- collection_permission_graph_revision
ALTER TABLE `collection_permission_graph_revision` MODIFY COLUMN `before` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Serialized JSON of the collections graph before the changes.';
ALTER TABLE `collection_permission_graph_revision` MODIFY COLUMN `after` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Serialized JSON of the collections graph after the changes.';
ALTER TABLE `collection_permission_graph_revision` MODIFY COLUMN `remark` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL NULL COMMENT 'Optional remarks explaining why these changes were made.';

-- permissions_revision
ALTER TABLE `permissions_revision` MODIFY COLUMN `before` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Serialized JSON of the permissions before the changes.';
ALTER TABLE `permissions_revision` MODIFY COLUMN `after` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Serialized JSON of the permissions after the changes.';
ALTER TABLE `permissions_revision` MODIFY COLUMN `remark` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL NULL COMMENT 'Optional remarks explaining why these changes were made.';

-- secret
ALTER TABLE `secret` MODIFY COLUMN `value` longblob NOT NULL COMMENT 'The base64 encoded binary value of this secret record. If encryption is enabled, this will be the output of the encryption procedure on the plaintext. If not, it will be the base64 encoded plaintext.';
```

**Information about your Metabase Installation:**
Tested 0.44.6 with MySQL+MariaDB appdb

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by qnkhuat**
Fixes https://github.com/metabase/metabase/issues/26212 and is a follow up of https://github.com/metabase/metabase/pull/18749

Sanity check

```sql
SELECT table_schema, table_name, column_name, data_type
FROM INFORMATION_SCHEMA.COLUMNS
WHERE (data_type='text' OR data_type='blob') AND table_schema='metabase';

-- before
+--------------+--------------------------------------+-------------+-----------+
| TABLE_SCHEMA | TABLE_NAME                           | COLUMN_NAME | DATA_TYPE |
+--------------+--------------------------------------+-------------+-----------+
| metabase     | collection_permission_graph_revision | after       | text      |
| metabase     | collection_permission_graph_revision | before      | text      |
| metabase     | collection_permission_graph_revision | remark      | text      |
| metabase     | permissions_revision                 | after       | text      |
| metabase     | permissions_revision                 | before      | text      |
| metabase     | permissions_revision                 | remark      | text      |
| metabase     | QRTZ_BLOB_TRIGGERS                   | BLOB_DATA   | blob      |
| metabase     | QRTZ_CALENDARS                       | CALENDAR    | blob      |
| metabase     | QRTZ_JOB_DETAILS                     | JOB_DATA    | blob      |
| metabase     | QRTZ_TRIGGERS                        | JOB_DATA    | blob      |
| metabase     | secret                               | value       | blob      |
+--------------+--------------------------------------+-------------+-----------+

-- after
+--------------+--------------------+-------------+-----------+
| TABLE_SCHEMA | TABLE_NAME         | COLUMN_NAME | DATA_TYPE |
+--------------+--------------------+-------------+-----------+
| metabase     | QRTZ_BLOB_TRIGGERS | BLOB_DATA   | blob      |
| metabase     | QRTZ_CALENDARS     | CALENDAR    | blob      |
| metabase     | QRTZ_JOB_DETAILS   | JOB_DATA    | blob      |
| metabase     | QRTZ_TRIGGERS      | JOB_DATA    | blob      |
+--------------+--------------------+-------------+-----------+
```

### CODE REVIEW

File: test/metabase/db/schema_migrations_test.clj [hunk 1]
```diff
@@ -747,3 +747,35 @@
...
+                (testing (format " %s in %s" exp-type driver/*driver*)
+                  ;; just get the first/only scalar value from the results (which is a vec of maps)
+                  (is (= (str/lower-case exp-type)
+                         (str/lower-case (get tbl-cols (name-fn col-nm))))
+                      (format "Using %s, type for %s.%s was supposed to be %s, but was %s"
+                              driver/*driver*
+                              tbl-nm
+                              col-nm
+                              exp-type
+                              (get tbl-cols col-nm))))))))))))
```
Comment (calherries) [inline test/metabase/db/schema_migrations_test.clj:781]: Do we really need this test? It is relatively costly to execute, and we don't run tests like this for all migrations. I feel the same way about `convert-text-to-longtext-migration-test` actually.

I can see the need to test more complicated migrations that involve SQL like `v45.00-049` but in this case I think your sense check in the PR description is sufficient.

**Review by calherries — APPROVED** [review]
LGTM, approving even if I question whether the test can be deleted.

File: test/metabase/db/schema_migrations_test.clj (hunk 1 above)
Comment (qnkhuat) [reply test/metabase/db/schema_migrations_test.clj:781]: Fair point, I'll remove this test.
