### PR TITLE
Fix Presto JDBC connection error

### LINKED ISSUE #17199: Bug when I try to use the new Presto Driver
Hello,

Im trying to test the new presto driver but I got some errors.

I use this docker image:
docker run -it -p 3000:3000 metabase/metabase-head

Error:
2021-07-25 01:11:40,339 ERROR api.database :: Não posso conectar ao banco de dados
java.lang.Exception: Unrecognized connection property 'engine'

Configuration:
Captura de Tela 2021-07-24 às 22 13 52

Could you help me?

Thank you so much.

### PR DESCRIPTION
**Pull request by jeff303**
Remove the `driver/can-connect?` implementation and move the dissoc logic instead to the existing place in `sql-jdbc.conn/connection-details->spec`

Update test to also include the `:let-user-control-scheduling` details entry

### CODE REVIEW

File: modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj [hunk 1]
```diff
@@ -224,7 +224,9 @@
                                   (Integer/parseInt port)
                                   port)))
                 (assoc :SSL ssl?)
-                (dissoc :ssl))]
+                ;; remove Metabase specific properties that are not recognized by the PrestoDB JDBC driver, which is
+                ;; very picky about properties (throwing an error if any are unrecognized)
+                (dissoc :ssl :engine :let-user-control-scheduling))]
```
Comment (dpsutton) [inline modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj:229]: if presto is very picky about keys, can we change this to a positive `select-keys` of what is valid for presto? So that any new keys in the future won't affect us and we play whack-a-mole? Probably not huge but perhaps a slightly more robust way to guard this.

Comment (jeff303) [reply modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj]: You're right; that would be a better approach.  I found the inclusive list from the source and added a new commit to do things that way instead.

File: modules/drivers/presto-jdbc/test/metabase/driver/presto_jdbc_test.clj [hunk 2]
```diff
@@ -194,5 +194,9 @@
 
 (deftest test-database-connection-test
   (mt/test-driver :presto-jdbc
-    (testing "can-test-database-connection works"
-      (is (nil? (database-api/test-database-connection :presto-jdbc (:details (mt/db))))))))
+    (testing "can-test-database-connection works properly"
+      ;; for whatever reason, :let-user-control-scheduling is the only "always available" option that goes into details
+      ;; the others (ex: :auto_run_queries and :refingerprint) are one level up (fields in the model, not in the details
+      ;; JSON blob)
+      (let [db-details (assoc (:details (mt/db)) :let-user-control-scheduling false)]
```
Comment (dpsutton) [inline modules/drivers/presto-jdbc/test/metabase/driver/presto_jdbc_test.clj:201]: `:let-user-control-scheduling` is just a marker that the schedules for the two syncs are system-randomized and not user input. It is optional and i imagine can be safely ignored. None of the databases in my dev copy have this key and it shouldn't be important enough here i don't think

```sql
select distinct json_object_keys(details::json) from metabase_database;
  json_object_keys
--------------------
 password
 db
 host
 port
 user
 additional-options
 tunnel-enabled
 ssl
 dbname
(9 rows)
```

Comment (dpsutton) [reply modules/drivers/presto-jdbc/test/metabase/driver/presto_jdbc_test.clj:201]: oh i guess i misread. this key is added as one of the "bad" keys that presto blows up on. I see.

**Review by dpsutton — APPROVED** [review]

File: modules/drivers/presto-jdbc/test/metabase/driver/presto_jdbc_test.clj (hunk 2 above)
Comment (jeff303) [reply modules/drivers/presto-jdbc/test/metabase/driver/presto_jdbc_test.clj:201]: The point of the test, though, is to ensure that even if a user happens to set it, the connection still succeeds (see the screenshot [here](https://github.com/metabase/metabase/issues/17199#issuecomment-891368881)).

File: modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj (hunk 1 above)
Comment (jeff303) [reply modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj]: OK, it ended up being a fairly long key sequence, but in the end it's probably better/safer this way.

Comment (dpsutton) [reply modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj]: yeah. and a bit more explicit so easier to have an idea of what is flowing through.

File: modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj [hunk 3]
```diff
@@ -333,10 +335,6 @@
         (log/debug e (trs "Error setting statement fetch direction to FETCH_FORWARD"))))
     stmt))
 
-(defmethod driver/can-connect? :presto-jdbc
```
Comment (ArtemKha) [inline modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj:336]: Now I get the error `No method in multimethod 'can-connect?' for dispatch value: :presto-jdbc` when adding a  source database with a new Presto driver.

Comment (flamber) [reply modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj:336]: Which commit are you running? Sounds like the driver hasn't been build correctly or is old.

Comment (ArtemKha) [reply modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj:336]: The last commit on master.
