### PR TITLE
fix: populate param-fields for named fields on public dashboards

### LINKED ISSUE #44231: Field values remapping with mixed PK and a FK targeting the same PK is broken in public dashboards
### Describe the bug

https://metaboat.slack.com/archives/C01LQQ2UW03/p1718352501337109

Remapped field values are not shown in public dashboards when a parameter is mapped to a FK field.

#### Bug 1

When:
- A parameter is mapped to a PK and to a FK targeting this PK (different questions)
- In the PK table there is a field with the semantic type set to `type/Name`
- For the PK column `has_field_values` is set to `list`

Then:
- Parameter values are not shown in public dashboards

#### Bug 2

When:
- Same as 1, but set `has_field_values` for the FK field to `list` as well

Then:
- Dropdown values would not appear even in regular dashboards

### Expected behavior

- The parameter values endpoint should not throw an exception because it cannot combine remapped and non-remapped values. Values from multiple fields should be merged in one list.
- It should be possible to use remapped values in public dashboards as in the app.

### Logs

- 

### Information about your Metabase installation

```JSON
v50
```

### Severity

P1/P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snoe**
closes https://github.com/metabase/metabase/issues/44231

### CODE REVIEW

**Review by ranquild — APPROVED** [review]

File: src/metabase/models/params.clj [hunk 1]
```diff
@@ -221,10 +211,19 @@
...
+    (set (for [{:keys [card] :as dashcard} dashcards
+               param    (:parameter_mappings dashcard)
+               :let     [field-clause (param-target->field-clause (:target param) (:card dashcard))]
+               :when    field-clause]
+           (or
+             ;; Get the field id from the field-clause if it contains it. This is the common case
+             ;; for mbql queries.
+             (lib.util.match/match-one field-clause [:field (id :guard integer?) _] id)
+             ;; Attempt to get the field clause from the model metadata corresponding to the field.
+             ;; This is the common case for native queries in which mappings from original columns
```
Comment (ranquild) [inline src/metabase/models/params.clj:223]: We don't allow mapping between parameters and native models now. This is actually needed for mbql models because they have string-based refs and the above condition with `integer?` doesn't work. Maybe it's worth updating the comment

**Review by bshepherdson — APPROVED** [review]
