### PR TITLE
Bigquery handles nested fields in nested queries appropriately

### LINKED ISSUE #55562: Bigquery STRUCT types break in the GUI for nested layers
### Describe the bug

If you're using STRUCT types inside the GUI metabase would reference the dictionary column instead of the source column breaking the query

### To Reproduce

You need to connect to bigquery and create a sample Table and Data containing STRUCT:

```
CREATE OR REPLACE TABLE my_project.my_dataset.dictionary (
  word_id INT64,
  details STRUCT<
    frequency INT64,
    length INT64,
    popularity_score FLOAT64
  >
);

INSERT INTO my_project.my_dataset.dictionary (word_id, details)
VALUES
  (1, STRUCT(1200, 11, 8.7)),
  (2, STRUCT(800, 9, 7.4)),
  (3, STRUCT(1500, 10, 9.2));
```

Then sync to metabase. JSON unfolding is enabled by default for Bigquery

Go to New Question -> Dictionary -> Count and Group by Frequency -> Create any custom column example `concat([Count] ,'')`

Image

Notice that fails because metabase is adding a Select ``details.frequency`` which isn't part of the source

### Expected behavior

The GUI question doesn't break

### Logs

400 Bad Request POST https://bigquery.googleapis.com/bigquery/v2/projects/senseful-cl-mb/queries { "code": 400, "errors": [ { "domain": "global", "location": "q", "locationType": "parameter", "message": "Name details not found inside source at [2:17]", "reason": "invalidQuery" } ], "message": "Name details not found inside source at [2:17]", "status": "INVALID_ARGUMENT" }

### Information about your Metabase installation

```JSON
1.53.7.3
```

### Severity

Makes working with JSON unfolding on Bigquery an issue

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wzimrin**
Closes https://github.com/metabase/metabase/issues/55562

### Description

Before, when you had an outer query referring to something in a nested field from the inner query, the query processor would assume the field is still nested and generate invalid sql.  Now, it will just refer to the alias.

### How to verify

See case for repro

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj [hunk 1]
```diff
@@ -672,9 +673,17 @@
...
+                            (lib.metadata/field (qp.store/metadata-provider) id-or-name))
+            result       (parent-method driver field-clause)
+            result       (cond-> result
+                           (not (temporal-type result))
+                           (with-temporal-type (temporal-type field-clause)))]
+        (if (and (lib.field/json-field? stored-field)
+                 (or (::sql.qp/forced-alias opts)
+                     (= source-table ::add/source)))
+          (keyword source-alias)
+          result)))))
```
Comment (wzimrin) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:686]: This logic was taken pretty directly from the postgres version of :field ->honeysql

Comment (appleby) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:686]: I wonder if this part about checking `forced-alias` and `source-table` should be broken out into a reusable predicate? Seems like it would be easy to forget about `::sql.qp/forced-alias` if you didn't know about it (then again, same problem if you don't know about the predicate).

**Review by appleby — APPROVED** [review]

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj (hunk 1 above)
Comment (appleby) [reply modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj:686]: E.g. the mysql driver checks `::sql.qp/forced-alias` but not `source-table`

https://github.com/metabase/metabase/blob/2aa82343e2e1c43a9f27b57c77f91efbe7891059/src/metabase/driver/mysql.clj#L374
