### PR TITLE
Fix metabot toggle :robot_face:

### LINKED ISSUE #3112: Enable Metabot toggle not working in admin slack settings
*  I am using the Chrome browser Version 51.0.2704.103 (64-bit)
*  My computer's OS is Mac OS 10.11.6.
*  I'm running Metabase in Docker and it is using the H2 database.
*  My data is in a mysql database.
*  My Metabase version is 0.19.

We're trying to enable the Slack integration and metabot. I've tried with both a slack test key and with setting up a bot in Slack. Pulses work great, so we know the integration is working to that extent.

However, we can't enable metabot. In the Slack settings panel, the switch is set to 'Disabled' and grayed out. We can't click the slider to enable it.

cant_enable

### PR DESCRIPTION
**Pull request by camsaul**
It was only rendering the toggle switch as "On" if the value for the setting in question was `true`, but the code actually set the new value was setting it to `"true"`. 

The simplest fix here seemed to be to just tweak it to accept either representation of truthiness.

Fixes #3112

### CODE REVIEW

File: frontend/src/metabase/admin/settings/components/SettingsSetting.jsx [hunk 1]
```diff
@@ -56,7 +56,8 @@ export default class SettingsSetting extends Component {
     }
 
     renderToggleInput(setting) {
-        const on = (setting.value == null ? setting.default : setting.value) === true;
+        const value = setting.value == null ? setting.default : setting.value,
+              on    = value === true || value === "true";
```
Comment (tlrobinson) [inline frontend/src/metabase/admin/settings/components/SettingsSetting.jsx]: This is pretty minor so don't worry about changing it, but I prefer to just duplicate the `const`/`let` for every declaration. It doesn't use any more characters (unless you don't count whitespace) and looks more symetric / makes moving code around easier.

**Comment by tlrobinson** [comment]
LGTM (Let Great Toggles Mutate)

**Comment by salsakran** [comment]
cool, merging.
