### PR TITLE
Duplicate dashboard handle dashboard with tabs

### LINKED ISSUE #31077: When duplicating a dashboard with tabs, tabs are not brought to the new duplicated dash
### Describe the bug

Original dashboard tables and graphs are added to the bottom of the new dashboard when it's duplicated and the other tabs will not appear.

### To Reproduce

1. Create a dashboard with tabs and charts/tables on each tab with the Sample Database
2. Duplicate it into any collection
3. Check the new duplicated dash 

https://github.com/metabase/metabase/assets/132273646/9113b089-51d3-4fa9-8a2f-ea27b344ee28

### Expected behavior

Tabs should be brought to the duplicated dashboard

### Logs

_No response_

### Information about your Metabase installation

```JSON
- master
```

### Severity

Minor

### Additional context

https://github.com/metabase/metabase/issues/29502

### PR DESCRIPTION
**Pull request by qnkhuat**
Fix #31077

Epic: https://github.com/metabase/metabase/issues/29502

### CODE REVIEW

File: src/metabase/api/dashboard.clj [hunk 1]
```diff
@@ -274,45 +274,60 @@
              :uncopied discard}
             copy)))
 
+(defn- duplicate-tabs
+  [new-dashboard existing-tabs]
+  (let [new-tab-ids (t2/insert-returning-pks! :model/DashboardTab
+                                              (for [tab existing-tabs]
+                                                (-> tab
+                                                  (assoc :dashboard_id (:id new-dashboard))
+                                                  (dissoc :id :entity_id :created_at :updated_at))))]
```
Comment (calherries) [inline src/metabase/api/dashboard.clj:283]: formatting
```suggestion
                                                (-> tab
                                                    (assoc :dashboard_id (:id new-dashboard))
                                                    (dissoc :id :entity_id :created_at :updated_at))))]
```

**Review by calherries — APPROVED** [review]
Looks good, just had some small suggestions
