### PR TITLE
Pulse render fixes

### LINKED ISSUE #1714: pulse card rendering fails on question with decimal values when using sql
not sure if this is specific to SQL usage or not, but this error is being generated when trying to add a card to a pulse when the card has decimal values in the data.

```metabase.pulse :: Pulse card render error:java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.```

### PR DESCRIPTION
**Pull request by tlrobinson**
Resolves #1714 and a few other things.

I was able to reproduce using data @agilliland sent me. Also the problem was not limited to SQL questions, equivalent query builder questions also failed.

It looks like the problem was due to dividing two BigDecimals that resulted in a repeating decimal, e.x. `(/ (new java.math.BigDecimal 1) (new java.math.BigDecimal 3))`. Casting the values to `float` fixes this.

### CODE REVIEW

File: src/metabase/pulse.clj [hunk 1]
```diff
@@ -324,12 +325,12 @@
...
         xmax   (apply max xs)
         xrange (- xmax xmin)
-        xs'    (map #(/ (- % xmin) xrange) xs)
+        xs'    (map #(/ (float (- % xmin)) xrange) xs)
         ys     (map second rows)
         ymin   (apply min ys)
         ymax   (apply max ys)
         yrange (max 1 (- ymax ymin)) ; `(max 1 ...)` so we don't divide by zero
-        ys'    (map #(/ (- % ymin) yrange) ys)
+        ys'    (map #(/ (float (- % ymin)) yrange) ys) ; cast to float to avoid "Non-terminating decimal expansion" errors
```
Comment (camsaul) [inline src/metabase/pulse.clj]: probably better to cast these to `Double` instead of `Float` so we don't lose too much precision

File: src/metabase/pulse.clj [hunk 2]
```diff
@@ -415,10 +421,12 @@
...
         "We were unable to display this card." [:br] "Please view this card in Metabase."])]
     (catch Throwable e
-      (log/warn (str "Pulse card render error:" e))
+      (log/warn "Pulse card render error:")
+      (print-stack-trace e)
       [:div {:style (style font-style
                            {:color       "#EF8C8C"
-                            :font-weight 700})}
+                            :font-weight 700
+                            :padding     "16px"})}
```
Comment (camsaul) [inline src/metabase/pulse.clj]: could just do `:padding :16px` here

File: src/metabase/pulse.clj [hunk 3]
```diff
@@ -1,7 +1,8 @@
 (ns metabase.pulse
   (:require [clojure.java.io :as io]
             (clojure [pprint :refer [cl-format]]
-                     [string :refer [upper-case]])
+                     [string :refer [upper-case]]
+                     [stacktrace :refer [print-stack-trace]])
```
Comment (camsaul) [inline src/metabase/pulse.clj]: try to keep these sorted alphabetically if you can

**Comment by camsaul** [comment]
merge in master it should fix the intermittent test failures.
