### PR TITLE
CSV upload loading messages

### LINKED ISSUE #31214: Update csv loading status when taking a long time
## Context
We have made performance improvements to csv uploads but there will still be some files that take multiple minutes to load. It can be confusing to the user since they just see a spinner and don't know if the file is still on track to upload or if something has gone wrong.

## Specified Behavior
Let's update the copy on the status component after 1 min (and each subsequent minute it's still uploading afterwards) to let the user know we're still working on the upload. Let's cycle through these copy bits:
1. Still working…
2. Getting our ducks in a row...
3. Arranging bits and bytes...
4. Doing the heavy lifting...
5. Pushing pixels...
6. [[Other fun ideas if you have them]]

Note that `Uploading data to [[Collection Name]]` is the current default and should still be shown for the first minute. Then we start cycling through the new copy above.

Screenshot 2023-05-31 at 12 13 32

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/31214

### Description

Updates loading message in the database status popover every 30 seconds for long uploads.

(sped up for demo)
loading-messages

### How to verify

- upload a CSV that takes more than 30 seconds to process [like this one](https://www.notion.so/metabase/nba-player-box-score-stats-4cabf8ddbe8a43948abfe9910029a80a)
- see the loading message change every 30 seconds

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadStatusLarge.tsx [hunk 1]
```diff
@@ -54,10 +74,23 @@ const getTitle = (uploads: FileUpload[], collection: Collection) => {
   } else if (isError) {
     return t`Error uploading your File`;
   } else {
-    return t`Uploading data to ${collection.name}...`;
+    return t`Uploading data to ${collection.name} …`;
```
Comment (iethree) [inline frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadStatusLarge.tsx:77]: updating this to use the correct single-character ellipsis.

**Review by EmmadUsmani — APPROVED** [review]
