### PR TITLE
Showing `currency_in_header` options in admin for fields

### LINKED ISSUE #38021: Table Metadata Option Missing in v48 (Where to Display the Unit of currency)
### Describe the bug

In v47 users can apply default settings to currency fields in table metadata that identify whether to display the unit of currency in column heading VS in every table cell. In v48 this option no longer exists.

### To Reproduce

1. Go to Admin -> Table Metadata
2. Select a current field
3. Go to "formatting"
4. Note that the menu titled "Where to display the unit of currency" is nowhere on the page

### Expected behavior

Option to set default display settings should be still be available as they were in v47

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "mongo",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.2.0"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-01-11",
      "tag": "v0.48.3",
      "hash": "80d8323"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Users that choose to display the currency field in every cell now have to edit every visualization individually in order to accomplish this.

### Additional context

Additional context:

- https://www.loom.com/share/6e85f1abf6454d9896fe3d2e59b9d9b7
- Zendesk ticket # 24224

### PR DESCRIPTION
**Pull request by markbastian**
The Table Metadata > Database Name > Table Name > Field Name > Formatting view did not show `Where to display the unit of currency` due to the following previous logic:

```
getHidden: (column, settings, { series }) =>
  settings["number_style"] !== "currency" ||
  series[0].card.display !== "table"
```

The second clause, `series[0].card.display !== "table"`, always returned true since `series[0].card.display` is `undefined`.

This has been updated to:

```
getHidden: (column, settings, { series }) =>
  settings["number_style"] !== "currency" &&
  (!series[0].card.display || series[0].card.display === "table")
```

The requirement is now that the series card display must be defined or be of type table.

Fixes #38021

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/settings/column.js [hunk 1]
```diff
@@ -346,8 +346,8 @@ export const NUMBER_COLUMN_SETTINGS = {
     },
     default: true,
     getHidden: (column, settings, { series }) =>
-      settings["number_style"] !== "currency" ||
-      series[0].card.display !== "table",
+      settings["number_style"] !== "currency" &&
+      (!series[0].card.display || series[0].card.display === "table"),
```
Comment (npfitz) [inline frontend/src/metabase/visualizations/lib/settings/column.js:350]: Rather than adjust this to say if display is undefined, It should be possible to get some information into that 3rd property in the getHidden function (sometimes called `extraData` in a few places). I think you could introduce something [here](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/datamodel/metadata/components/FieldFormattingSettings/FieldFormattingSettings.tsx) into the `ColumnSettings` component that would make it's way there and help settings make a better decision

File: e2e/test/scenarios/admin/settings/settings.cy.spec.js [hunk 2]
```diff
@@ -189,6 +191,32 @@ describe("scenarios > admin > settings", () => {
...
+      cy.findByText("In every table cell").click();
+    });
+
+    // Open the orders table
+    openOrdersTable({ limit: 2 });
+
+    cy.get("#main-data-grid").within(() => {
+      // Items in the total column should have a leading dollar sign
+      cy.findByText("$39.72");
+      cy.findByText("$117.03");
```
Comment (adam-james-v) [inline e2e/test/scenarios/admin/settings/settings.cy.spec.js:216]: The row order will be stable right? If it's not this might flake. 
I suspect it's fine though.

**Review by adam-james-v — APPROVED** [review]
Makes sense. Looks good :)
