### PR TITLE
Fix Slack integration & make it more robust

### LINKED ISSUE #2694: Pulse cannot be sent to Private Channel
Seems as though a pulse cannot be sent to a private channel despite the presence of Metabot in that channel.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### LINKED ISSUE #12678: Can't create new Slack Metabot
**Describe the bug**
When I go to the admin/settings/slack page and I try to save the form after adding a new bot to slack, then I have an error that indicates that the method is deprecated.

**Logs**
06-10 21:47:02 DEBUG middleware.log :: PUT /api/slack/settings 400 243.0 ms (0 DB calls)
{:message "Slack API error: method_deprecated",
 :response
 {:ok false,
  :error "method_deprecated",
  :response_metadata
  {:messages
   ["[ERROR] This method is retired and can no longer be used. Please use conversations.list or users.conversations instead. Learn more: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api."]}}}

**To Reproduce**
1. Go to admin/settings/slack
2. Click on Create a user bot for slack
3. Publish the bot and get the API token on slack
4. Get back on admin/settings/slack, put the token, click to activate the bot
5. Save

**Expected behavior**
No error and a working bot

**Information about your Metabase Installation:**

- Your browser and the version: "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Mobile Safari/537.36"
- Your operating system: MacOS
- Your databases: MySQL
- Metabase version: 0.35.4
- Metabase hosting environment: Jar File
- Metabase internal database: H2

**Severity**
Annoying (the marketing team is not happy at all ;) )

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

### PR DESCRIPTION
**Pull request by camsaul**
* Updates the Slack API endpoints we use; fixes #12678
*  MetaBot/Pulses now work with private channels. Fixes #2694 (see image below)
*  Reworked and more robust Slack integration code
*  Reworked and expanded test coverage for Slack API integration.

image

Note for private channel integration you have to 

```
/invite @your_bot_name
```

in the private channel for things to work as expected.

### CODE REVIEW

File: src/metabase/integrations/slack.clj [hunk 1]
```diff
@@ -24,75 +23,130 @@
...
+
+(defn- paged-list-request
+  "Make a GET request to a Slack API list `endpoint`, returning a sequence of objects returned by the top level
+  `results-key` in the response. If additional pages of results exist, fetches those lazily, up to a total of
+  `max-list-results`."
+  [endpoint results-key params]
+  (let [response (m/mapply GET endpoint params)]
+    (when (seq response)
+      (take
+       max-list-results
```
Comment (lukeman) [inline src/metabase/integrations/slack.clj:92]: @camsaul I'm not a Clojure-head so might be reading this wrong, but this looks like it'll only ever take the first 1,000 list items even after fetching the nth 1,000 items and concatenating to the first page. If so, that matches what I'm seeing in #12978 where the Pulse Slack list is limited to 2,000 items (presumably 1,000 channels and 1,000 users).

Comment (camsaul) [reply src/metabase/integrations/slack.clj:92]: Yup, I put a limit in there of 1000 items as a failsafe to make sure we didn't get into an infinite loop. Previously we only fetched the first page (so only the first 100) results. 

It looks like the limit is too small in reality so we can bump that limit. Unfortunately it doesn't look like the Slack API has a way to search for channels by name so it's not great that we'd have to fetch potentially hundreds of channels to find the `metabase_files` channel
