### PR TITLE
SEM-176 Use new semantic type picker everywhere

### LINKED ISSUE #55617: Cannot change field's semantic type in field detail view in data reference
### Describe the bug

https://github.com/user-attachments/assets/9b4dedc1-b65b-4a23-a0c6-5a2fc8e0110a

### To Reproduce

1. Databases > Learn about our data > Sample Database > Tables in Sample Database > Products > Fields in this table > Click any field > Edit
2. Try to change "Field type"

Nothing happens

### Expected behavior

It's possible to change "Field type"

### Logs

_No response_

### Information about your Metabase installation

```JSON
master, 92c9e8736dd828cdc5dd98be24b4d0f9fb9996af
```

### Severity

P2

### Additional context

_No response_

### LINKED ISSUE #55618: Cannot change field's FK type mapping in data reference
### Describe the bug

Both fields list and field detail view.

https://github.com/user-attachments/assets/5635ee3f-2046-4c22-b9df-dad44f3a5b23

### To Reproduce

1. Databases > Learn about our data > Sample Database > Tables in Sample Database > Products > Fields in this table > Edit
2. Try to change target FK for "User ID"

❌ dropdown is empty

3. Cancel
4. Click "User ID"
5. Click "Edit"

Try to change target FK

❌ dropdown is empty

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
master, 92c9e8736dd828cdc5dd98be24b4d0f9fb9996af
```

### Severity

P2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes [SEM-176](https://linear.app/metabase/issue/SEM-176/use-new-semantic-type-picker-everywhere)
Fixes #55617 ([SEM-188](https://linear.app/metabase/issue/SEM-188/cannot-change-fields-semantic-type-in-field-detail-view-in-data))
Fixes #55618 ([SEM-189](https://linear.app/metabase/issue/SEM-189/cannot-change-fields-fk-type-mapping-in-data-reference))

### Description

Hiding whitespace changes recommended.

This PR is a follow-up on #54965.

- introduces new frontend directory: `metabase/metadata` (see `metabase/metadata/README.md`)
- moves `CurrencyPicker`, `FkTargetPicker`, `SemanticTypePicker` and `SemanticTypeAndTargetPicker` in there
- removes usages of "global" CSS classes from aforementioned components (e.g. `import CS from "metabase/css/core/index.css"`)
- fixes alignment issue in Table Metadata > Field Settings ([before](https://github.com/user-attachments/assets/9e8932dd-4657-4c11-b2ab-98a2965b77b1) vs [after](https://github.com/user-attachments/assets/fc77e11b-dc6b-4af2-be39-ffb5f4ff8105))
- fixes invalid docs links (`data-modeling/segments-and-metrics`) to use either `data-modeling/segments` or `data-modeling/metrics` accordingly
- removes old `FKTargetPicker` component (in favor of new `FkTargetPicker`)
- removes old `SemanticTypePicker` component (in favor of new one by the same name)
- places where new `SemanticTypePicker` and `FkTargetPicker` are used in this PR:
  - Model > Metadata
  - Data reference > Table fields list view
  - Data reference > Table field detail view
  - Data reference > Segment fields list view
  - Data reference > Segment field detail view

### How to verify

Semantic type picker and FK target picker (visible only when semantic type is set to "Foreign Key") should work as expected in these 5 places:
1. Model > Metadata
2. Data reference > Table fields list view
3. Data reference > Table field detail view
4. Data reference > Segment fields list view
5. Data reference > Segment field detail view

### Demo

Video shows all 5 places where new components are used.

https://github.com/user-attachments/assets/90b17c10-d7a7-45ed-bda3-374a112e48c6

### CODE REVIEW

File: frontend/src/metabase/reference/components/FieldTypeDetail.jsx [hunk 1]
```diff
@@ -25,25 +23,17 @@ const FieldTypeDetail = ({
...
+              field={field}
               value={fieldTypeFormField.value || field.semantic_type}
-              options={FIELD_SEMANTIC_TYPES.concat({
-                id: null,
-                name: t`No field type`,
-                section: t`Other`,
-              }).filter(type =>
-                !isNumericBaseType(field)
-                  ? !(type.id && type.id.startsWith("timestamp_"))
-                  : true,
```
Comment (kamilmielnik) [inline frontend/src/metabase/reference/components/FieldTypeDetail.jsx:41]: No idea what this code was for, but no `type.id` starts with `"timestamp_"` (they all start with `"type/"`), so I just removed it. It should work the same in every context anyway.

File: frontend/src/metabase/reference/components/Detail.jsx [hunk 2]
```diff
@@ -15,7 +15,6 @@ const Detail = ({
   placeholder,
   subtitleClass,
   url,
-  icon,
```
Comment (kamilmielnik) [inline frontend/src/metabase/reference/components/Detail.jsx:18]: Unused

File: frontend/src/metabase/reference/components/FieldTypeDetail.jsx [hunk 3]
```diff
@@ -25,25 +23,17 @@ const FieldTypeDetail = ({
...
-              )}
-              optionValueFn={o => o.id}
-              onChange={({ target: { value } }) =>
-                fieldTypeFormField.onChange(value)
-              }
+              onChange={value => {
+                fieldTypeFormField.onChange({
+                  target: { name: "semantic_type", value },
+                });
```
Comment (kamilmielnik) [inline frontend/src/metabase/reference/components/FieldTypeDetail.jsx:35]: This fixes  #55617

File: frontend/src/metabase/reference/components/FieldTypeDetail.jsx [hunk 4]
```diff
@@ -25,25 +23,24 @@ const FieldTypeDetail = ({
...
-              )}
-              optionValueFn={o => o.id}
-              onChange={({ target: { value } }) =>
-                fieldTypeFormField.onChange(value)
+            <SemanticTypePicker
+              field={field}
+              value={
+                typeof fieldTypeFormField.value !== "undefined"
+                  ? fieldTypeFormField.value
+                  : field.semantic_type
```
Comment (kamilmielnik) [inline frontend/src/metabase/reference/components/FieldTypeDetail.jsx:34]: `fieldTypeFormField.value || field.semantic_type` would make it impossible to select "No semantic type" option (which has `null` value) - this fixes it.

File: frontend/src/metabase/reference/components/FieldTypeDetail.jsx [hunk 5]
```diff
@@ -4,81 +4,90 @@ import PropTypes from "prop-types";
...
+              <SemanticTypePicker
+                field={field}
+                value={semanticType}
+                onChange={value => {
+                  fieldTypeFormField.onChange({
+                    target: {
+                      name: fieldTypeFormField.name,
+                      value,
+                    },
+                  });
```
Comment (kamilmielnik) [inline frontend/src/metabase/reference/components/FieldTypeDetail.jsx:46]: This fixes #55617

File: frontend/src/metabase/reference/components/FieldTypeDetail.jsx [hunk 6]
```diff
@@ -4,81 +4,90 @@ import PropTypes from "prop-types";
...
-                <span>
-                  {getIn(foreignKeys, [field.fk_target_field_id, "name"])}
-                </span>
-              )}
-        </span>
+}) => {
+  const semanticType =
+    typeof fieldTypeFormField.value !== "undefined"
+      ? fieldTypeFormField.value
+      : field.semantic_type;
```
Comment (kamilmielnik) [inline frontend/src/metabase/reference/components/FieldTypeDetail.jsx:26]: `fieldTypeFormField.value || field.semantic_type` would make it impossible to select "No semantic type" option (which has `null` value) - this fixes it.

File: frontend/src/metabase/metadata/components/FkTargetPicker/FkTargetPicker.tsx [hunk 7]
```diff
@@ -40,8 +47,11 @@ export const FkTargetPicker = ({
 
   return (
     <Select
-      className={className}
+      aria-label={t`Foreign key target`}
       comboboxProps={{
+        middlewares: {
+          flip: true,
```
Comment (kamilmielnik) [inline frontend/src/metabase/metadata/components/FkTargetPicker/FkTargetPicker.tsx:53]: Without this the dropdown would only be like 30px tall in data reference pages

**Review by ranquild — APPROVED** [review]
