### PR TITLE
fix: collection archive/move w/out parent perms

### LINKED ISSUE #59652: Normal users can't delete sub collections if there's any restricted collection in the path
### Describe the bug

If you're a normal user and try to delete a sub collection when there's any collection in the path that you don't have curate permissions to, then you can't delete the collection.

### To Reproduce

1) create a new group and a user. Add the new user to the group
2) create a collection under root collection
3) create a child collection under collection created on 
4) set the collection you created on step 1 to "No access" permissions
5) set the collection you created on step 2 to "curate"
6) now log in with the user you created on step 1 and try to delete the collection you see, you'll get a 403

### Expected behavior

You should be able to delete a collection if there's enough permissions ("curate") on it

### Logs

NA

### Information about your Metabase installation

```JSON
Tested only on 53+, probably comes from before
```

### Severity

P2?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edpaget**
closes #59652
### Description

Allow users to archive and move collections even when they do not have read-write permissions on the parent collection.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: src/metabase/collections/models/collection.clj [hunk 1]
```diff
@@ -963,56 +963,73 @@
 ;;; |                                    Recursive Operations: Moving & Archiving                                    |
 ;;; +----------------------------------------------------------------------------------------------------------------+
 
-(mu/defn perms-for-archiving :- [:set perms/PathSchema]
-  "Return the set of Permissions needed to archive or unarchive a `collection`. Since archiving a Collection is
-  *recursive* (i.e., it applies to all the descendant Collections of that Collection), we require write ('curate')
-  permissions for the Collection itself and all its descendants, but not for its parent Collection.
+(mu/defn perms-for-collection-and-descendants :- [:set perms/PathSchema]
+  "Return the set of Permissions needed for a `collection` and its descendants, without requiring
```
Comment (johnswanson) [inline src/metabase/collections/models/collection.clj]: Feels like this docstring is confusing because it's just like "perms need for a collection" - to do what?

Really what this is is "the set of write permissions for this collection and all its descendants." I think we can delete all the explanation of "what set of permissions is this" and just keep a brief explanation of why this might be useful.

Something like

```
"Return the set of write permissions for this collection and all its descendants.

This is useful for operations that need to modify a collection *and* its descendants - for example, moving or archiving a collection necessarily moves/archives all its descendants as well, so permissions on those are required as well.

Note that technically these operations could be seen as modifying the parent as well (e.g., moving a collection out of a parent collection "modifies" the parent's content) but it seems confusing if a user can't archive a collection they have permissions on because of the parent permissions.
```

**Review by johnswanson — APPROVED** [review]
we might want to confirm that it's ok that you'll be able to e.g. archive something and then not be able to restore it (though you could obviously just move it somewhere else, so it's not a huge issue).
