### PR TITLE
stack from top to bottom for area/bar charts

### LINKED ISSUE #28772: The order of series in a visualization should match the order in the sidebar
**Describe the bug**
When configuring any multi-series visualization, the order in the sidebar is reflected in the legend, but not in the chart itself. In the example below, I'd expect the order in stacked bars to be Green → Yellow → Purple → Orange from top to bottom, but it appears from bottom to top.

**To Reproduce**
Create a multi-series viz and reorder the series.

**Screenshots/videos**
Screenshot 2023-03-01 at 10 31 10 AM

**Information about your Metabase Installation:**
Master as of Mar 1 2023 in Chrome 110 on MacOS 13.2, but it's not relevant in this case.

**Severity**
It's a small annoyance in that I have to change my way of thinking to fit the product's.

### PR DESCRIPTION
**Pull request by EmmadUsmani**
Closes https://github.com/metabase/metabase/issues/28772

### Description

In stacked bar/area charts, series were stacked from bottom to top. This created an incongruity with the sidebar, where the order of the series was displayed top to bottom. See the "Before" demo for an example.

To fix this, in `LineAreaBarChart` I added a condition to reverse the order of the series if it was a stacked chart. I also updated the `Legend` component to render its labels and colors in the correct order, and to select the correct series when hovering.

### How to verify

1. Create a stacked bar/area chart visualization (an easy one is "Products, Count, Grouped by Category and Created At (month)")
2. Verify series are stacked from top to bottom, matching sidebar.
3. Verify legend still works properly (labels and colors are correct, correct series is selected on hover).
4. Verify tooltips show correct series.

### Demo

222114156-07782712-2fca-40bf-a31f-616106a61cb1

Before

https://user-images.githubusercontent.com/37751258/223561597-693d4c57-e489-40a1-8025-04b4d1289be1.mov

After

### Checklist

- ✅ Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx [hunk 1]
```diff
@@ -349,7 +349,10 @@ export default class LineAreaBarChart extends Component {
       settings,
     } = this.props;
 
-    const orderedSeries = getOrderedSeries(series, settings);
+    const isReversed =
+      settings["stackable.stack_type"] !== null &&
+      settings["stackable.stack_type"] !== undefined;
```
Comment (iethree) [inline frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx:354]: I'm not usually a big proponent of comments, but I think one could be helpful here to explain why we would want to be reversing stacked charts.

**Review by iethree — APPROVED** [review]
Looks good to me. I got to make a cool chart to test this. 😁 
Pokemon Types By Generation-3_9_2023, 4_06_33 PM

File: frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx (hunk 1 above)
Comment (EmmadUsmani) [reply frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx:354]: Definitely agree. I usually prefer when code is self-explanatory, but in this case I think explaining the business/design logic would be helpful.

File: frontend/src/metabase/visualizations/components/legend/Legend.jsx [hunk 2]
```diff
@@ -53,21 +55,31 @@ const Legend = ({
     setMaxWidth(0);
   }, []);
 
+  const labels = isReversed
+    ? originalLabels.slice(0).reverse()
+    : originalLabels;
+  const colors = isReversed
+    ? originalColors.slice(0).reverse()
```
[the remark this answers is not in the document]
Comment (EmmadUsmani) [reply frontend/src/metabase/visualizations/components/legend/Legend.jsx:62]: Makes sense, we could also use `_.clone` which is probably the most semantic.
