### PR TITLE
getting started guide empty state fixes

### LINKED ISSUE #3463: Data reference isn't accessible if an admin hasn't created a getting started guide
In a new installation, I should still be able to get to all metrics, all segments and all tables even if an administrator hasn't created a getting started guide for that instance.

Right now, all I see is the below

screen shot 2016-10-05 at 4 35 18 pm

### PR DESCRIPTION
**Pull request by kdoh**
fixes #3463

### CODE REVIEW

File: frontend/src/metabase/reference/utils.js [hunk 1]
```diff
@@ -465,3 +465,7 @@ export const typeToBgClass = {
     segment: 'bg-purple',
     table: 'bg-purple'
 };
+
+// little utility function to determin if we 'has' things, useful
+// for
```
Comment (tlrobinson) [inline frontend/src/metabase/reference/utils.js]: For what, @kdoh?!

**Comment by tlrobinson** [comment]
LGTM
