### PR TITLE
fix #3781

### LINKED ISSUE #3781: Some time filter options are not working on Druid
Hi all,

There are a few errors with time filter on Druid. Here are some that I found:

- Past year is not working 
- This [week, month, year] return current day

How to reproduce:
1. select a druid table 
2. add one of the filters mentioned above
3. look at the native query -> dates are wrong

### PR DESCRIPTION
**Pull request by moumny**
Hi 
This is an attempt as fixing #3781 
Not sure about about modifying the expand code but since tests seem to be still passing im putting it here for review.

### CODE REVIEW

File: src/metabase/query_processor/expand.clj [hunk 1]
```diff
@@ -307,7 +307,7 @@
       :next    (recur f  1 unit))
     (let [f (datetime-field f unit)]
       (cond
-        (core/= n  0) (= f (value f (relative-datetime :current)))
+        (core/= n  0) (= f (value f (relative-datetime  0 unit)))
```
Comment (camsaul) [inline src/metabase/query_processor/expand.clj]: @moumny, what's the reason behind the changes in this file? Just so I can better understand the PR

Comment (camsaul) [inline src/metabase/query_processor/expand.clj]: any are you sure that doesn't break anything for the other query processors, like SQL

Comment (moumny) [inline src/metabase/query_processor/expand.clj]: Basically after the query is expanded, the field that contains 0 (week, month year) is replaced by :current day which is why Druid filters on today instead of this week/month/year.

I tried to test a bit and see if this has an effect on SQL queries but haven't found any. Filters on the sample dataset seem correct.
However im really not familiar with this part of code, so a deep look is required.

**Comment by moumny** [comment]
@camsaul  replying to 

> @moumny date-trunc-or-extract will call date-extract if the unit is something like month-of-year or year

If you look at the code you see that you convert the value in ISO timestamp. This obviously doesnt make sense for an extract like x-of-y.
For year this change makes is use date trunc instead date extract. That way the timestamp can get converted to ISO timestamp required for the query.

**Comment by camsaul** [comment]
@moumny I think the merge you did borked somehow, if you look at Files Changed there are dozens of changes that are already in the `master` branch showing up in this PR now

**Comment by camsaul** [comment]
@moumny, just ran tests against the latest commit locally and everything looks good. 👍
