### PR TITLE
Fix blank eid not creating a new entity on load

### LINKED ISSUE #50106: Serialization: Importing Same YAML with NULL Entity ID Twice Later Breaks Export
### Describe the bug

You can import a card via serialization that has with a NULL entity ID and Metabase generates the ID for you. You can import it again and it will also work.

On third import it fails with:

`Error during serialization: ERROR: duplicate key value violates unique constraint "report_card_entity_id_key"`

If you attempt to export now you are also met with this error.

### To Reproduce

1. Set up a test instance and export a collection
2. Modify one of the cards to set a NULL entity ID and change the name
3. Import via serialization - it works!
4. Import it again - it works!
5. Import it again - constraint violation
6. Attempt to export - also constraint violation

### Expected behavior

We should be able to prevent users from creating this state, I would think.

### Logs

_No response_

### Information about your Metabase installation

```JSON
Replicated in 50 and 51
```

### Severity

Blocking some users

### Additional context

A cloud customer broken the export functionality on their instance this way. Seems like the second imported card exists without an entityID. On export it attempts to generate an ID identical to one that already exists (which makes sense). So we can work around this by editing the card in the instance and exporting again. But it's a very frustrating experience.

### PR DESCRIPTION
**Pull request by wotbrew**
Closes https://github.com/metabase/metabase/issues/50106

### Description

The documentation https://www.metabase.com/docs/latest/installation-and-operation/serialization#how-import-works suggests a 'blank' entity_id should result in a new entity being created. 

This lead to issue #50106 in which multiple repeated imports of the same entity (having a null entity_id) would on the 3rd import result in a constraint violation exception.

After discussing with @piranha - I have confirmed the desired behaviour is as documented, additionally we do not think the requirement for removing the `:id` from the `:serdes/meta` is necessary.

Previous behaviour: 

- Import 1
   - the existing entity matched, despite the null entity_id - as looking up the previous entity is based on the `:serdes/meta` `:id`. 
  -  the existing entity is updated to have a null entity_id.
- Import 2 
     - backfill runs, the null entity id is replaced with the identity-hash of the entity.
     - the new entity `:serdes/meta` does not match what is in the app db, so a new entity is created (with a null entity_id)
- Import 3
     - backfill runs, spots the null entity_id and tries again to replace with the identity-hash - failing because the hash already exists.

### How to verify

1. Import a serialized entity containing a null entity_id. 
2. Observe the entity is created
3. Repeat a further 2 or 3 times, you should expect to see new entities be created.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 1]
```diff
@@ -102,10 +106,10 @@
                              (update :seen conj path)
                              (update :expanding disj path))
                 ;; Use the abstract path as attached by the ingestion process, not the original one we were passed.
-                rebuilt-path    (serdes/path ingested)
-                local-or-nil    (serdes/load-find-local rebuilt-path)]
+                rebuilt-path (serdes/path ingested)
+                local-or-nil (serdes/load-find-local rebuilt-path)]
             (try
```
Comment (wotbrew) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:111]: foo

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 2]
```diff
@@ -102,10 +106,10 @@
...
-              (serdes/load-one! ingested local-or-nil)
+              (serdes/load-one! ingested (when-not require-new-entity local-or-nil))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:112]: `serdes/load-find-local` requires an appdb lookup, which is wasted when `require-new-entity`. Move the `when-not` to the definition of `local-or-nil`, so we avoid doing wasted work.

File: enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj [hunk 3]
```diff
@@ -92,7 +93,10 @@
                              (throw (ex-info (format "Failed to read file for %s" (serdes/log-path-str path))
                                              (path-error-data ::not-found expanding path)
                                              e))))
+                ;; if no :entity_id specified we must guarantee a new entity is created
+                require-new-entity (nil? (:entity_id ingested ::not-found))
```
Comment (bshepherdson) [inline enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj:97]: I think it would be worth calling out another bit of context here: any truly exported entity should have `:entity_id` set, since we backfill before export. So if it's blank in the incoming file then it's been removed on purpose. Likewise we did a backfill before import, so the appdb cannot have any blank `entity_id`s in it either.

Comment (wotbrew) [reply enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj]: I've been a bit more explicit in the comment.  Hope its an improvement.

**Comment by wotbrew** [comment]
There is some ambiguity for me in what 'blank' means. Originally I took it to mean entity_id is 'null OR absent from the yaml'. Unfortunately if I do that (i.e remove the `::not-found`) a bunch of tests break as they assume ingesting entities without an entity_id at all should match local entities using the `:serdes/meta` `:id` as before.

That is why the 'new entity' behaviour is only implemented in terms of :entity_id being both present and nil.

Happy to take advice on what to do in this case. Can rework the tests, but equally this may well be acceptable as a fix to the original issue.

**Comment by piranha** [comment]
To be honest I'm thinking that missing entity-id should be treated the same as null, since I imagine if I was doing that for the sake of duplicating data I'd just delete the line (`grep -v entity_id:` basically) rather than replacing a value with null.

As for id in `serdes/meta` my thinking here is that if we have two sources for an identifier it just makes situation way more complicated. We're not actively checking their equality, so why have another place to look up an id? As for tests - maybe I'm mistaken, but with migration from serdes v1 effectively complete we can count on data being consistent enough and we should fix/change/remove those tests.

I'd love to hear @bshepherdson and @luizarakaki view on those thoughts before proceeding. :)

**Comment by bshepherdson** [comment]
> To be honest I'm thinking that missing entity-id should be treated the same as null, since I imagine if I was doing that for the sake of duplicating data I'd just delete the line (`grep -v entity_id:` basically) rather than replacing a value with null.

I think this is reasonable. If there's any fallback to pulling the id from `:serdes/meta` then I think we can drop it.
 
> As for id in `serdes/meta` my thinking here is that if we have two sources for an identifier it just makes situation way more complicated. We're not actively checking their equality, so why have another place to look up an id?

As I say, this makes sense. We definitely should not be *removing* the `:serdes/meta`, but we don't need to mine it for a backup `entity_id`.

> As for tests - maybe I'm mistaken, but with migration from serdes v1 effectively complete we can count on data being consistent enough and we should fix/change/remove those tests.

That makes me concerned... I've forgotten what the state of v1 is, though. Did we disable its commands? In what version? I think it should have been unusable for a few major versions before we can drop any compatibility and tests for the upgrade process.

**Comment by wotbrew** [comment]
Good news everyone! I realised I had misunderstood the test issue, and I did not have to change a load of tests after all! it was simply that some loadable entities do not actually have an entity_id (e.g tables). 

I've changed the logic so that it only applies if we should expect an entity_id in the first place. See `exported-with-entity-id?`. Everything now passes, and the behaviour applies for absent OR null.

Any comments or feedback on the new changes are welcome!

@piranha, @bshepherdson what do you think?

**Review by sansolovyov — APPROVED** [review]
Oh well that makes lots of sense :)

**Comment by wotbrew** [comment]
Great, thanks for approving!

@bshepherdson any comments before I merge?

**Review by bshepherdson — APPROVED** [review]
