### PR TITLE
Fix deleted documents were editable

### LINKED ISSUE #63112: It's possible to edit documents in trash
### To Reproduce

1. Create and save a document
2. Move it to trash
3. Try to edit it in trash

❌ it should not be possible to edit a trashed entity

### Information about your Metabase installation

master, 0c17daf51bbdf2977edef3da32f9ef0b8e13012e

### Severity

P3

### PR DESCRIPTION
**Pull request by WiNloSt**
closes #63112
Closes UXW-1995

### Backport reason
This PR will likely be merged after 57 is cut, so I set it to backport.

### Description

Deleted documents were editable, this PR fixes that. However, I think we should also fix commenting as the UI is still visible and submit-able even though the API would fail. I was trying to work on comment entrypoints, but it would make this PR much bigger, so I think it deserves its own issue.

### How to verify

Create a document and delete it, now try to modify either the document title or the document body.

You shouldn't be able to to those things.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by npretto** [comment]
was the document already not editable on the backend? or should the fix also change the backend?

**Comment by WiNloSt** [comment]
> was the document already not editable on the backend? or should the fix also change the backend?

It's also editable on the BE, although the comments couldn't be saved. Good point about that. I'm not sure how these permissions work. Let me have a look.

**Review by heypoom — APPROVED** [review]
🎉

**Comment by WiNloSt** [comment]
@npretto Fixed the API allowing modifying archived documents in https://github.com/metabase/metabase/pull/65136/files/d410bcfc414e0e5164bdd35b0e3394c6e9682e30..1e9ab3d0eb714ff378b16ce8f16ad32473587512. I'll take a look at tests later. I think some might fail.

File: enterprise/backend/src/metabase_enterprise/documents/api/document.clj [hunk 1]
```diff
@@ -194,6 +194,7 @@
    {:keys [name document collection_id collection_position cards] :as body} :- DocumentUpdateOptions]
   (let [existing-document (api/check-404 (get-document document-id))]
     (api/write-check existing-document)
+    (api/check-not-archived existing-document)
```
Comment (WiNloSt) [inline enterprise/backend/src/metabase_enterprise/documents/api/document.clj]: This prevents documents from being updated when archieved.
