### PR TITLE
Fix: Inconsistent icon position in pinned dashboard item loading state

### LINKED ISSUE #31328: Inconsistent icon position in pinned dashboard item loading state
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/468d7d86-3f7d-4202-b509-3a053fae3fd9

### To Reproduce

1. Create a question and add a description to it.
2. Save the question and pin it in a dashboard.
3. Use "show visualization" for it.
4. Reload the page (throttle your network)
5. Hover over "i" icon of that pinned question
6. Read the label and wait until data is loaded

### Expected behavior

Icon does not jump to the right after data is loaded.

### Severity

P4

### PR DESCRIPTION
**Pull request by oisincoveney**
Closes https://github.com/metabase/metabase/issues/31328

### Description

Solves the problem of inconsistent icon positioning for visualization loading skeletons, removes a lot of duplicated code, and consolidates some styling to match the actual visualization to prevent content jumping.

- `ChartSkeleton` now calls `ScalarSkeleton` and `VisualizationSkeleton`
	- `ScalarSkeleton` now handles `Scalar` and `SmartScalar` visualizations
	- `VisualizationSkeleton` now handles title, description, and actionMenu elements for non-scalar visualizations
- Removes `EmptySkeleton` since `VisualizationSkeleton` now handles title/description/etc
- Removes `SkeletonCaption` and `SkeletonRoot` from all of the non-scalar visualizations, effectively creating image-only components for those visualizations
- Removes `SkeletonRoot` from non-scalar visualizations, and uses `VisualizationHeader` for consistency in spacing with the actual visualizations. After the visualization is loaded, the title text will not move as it did before
- Adds `ChartSkeletonDisplayType` for typescript happiness
- Moves `animationStyles` to `util/animation` rather than exporting from `Skeleton.styled.tsx`

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/components/skeletons/util/display-type.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
+export const chartSkeletonDisplayTypes = [
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/components/skeletons/util/display-type.ts:1]: I would't define viz types like that. They can be extended and can be something outside of this list. That's why there is `CardDisplayType` and it's a `string`. Could you use that type instead of this one?

File: frontend/src/metabase/visualizations/components/skeletons/util/animation.ts [hunk 2]
```diff
@@ -14,13 +14,6 @@ export const fadingKeyframes = keyframes`
...
   }
 `;
-
-export const containerStyles = css`
-  display: flex;
-  flex-direction: column;
-  height: 100%;
-`;
-
 export const animationStyles = css`
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/components/skeletons/util/animation.ts:17]: I don't think that css styles should go to the utils folder. By looking at the code it seems that we could either:
- extract `SkeletonImage` as a styled component in its own folder and use that instead of `styled.svg` + `animationStyles` pair
- do not change the components but place these styles in the corresponding `*.styled.tsx` file in one of the component folders (presumably `VisualizationSkeleton` or `ChartSkeleton`). <- I'd probably do this

**Review by ranquild — APPROVED** [review]
Looks good, please take a look at the comments

File: frontend/src/metabase/visualizations/components/skeletons/util/display-type.ts (hunk 1 above)
Comment (oisincoveney) [reply frontend/src/metabase/visualizations/components/skeletons/util/display-type.ts:1]: Yep, that makes sense. I also use the `TableSkeleton` as the default skeleton component as the default in the `switch` statement if a skeleton isn't found:

https://github.com/metabase/metabase/blob/38c15a7bba73f1ba1e33f35ac7511c497af851b1/frontend/src/metabase/visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.tsx

Comment (oisincoveney) [reply frontend/src/metabase/visualizations/components/skeletons/util/display-type.ts]: Also added a test for the display type  `"a random display type"` just to make sure that strings outside of the ones in the switch statement still render

File: frontend/src/metabase/visualizations/components/skeletons/util/animation.ts (hunk 2 above)
Comment (oisincoveney) [reply frontend/src/metabase/visualizations/components/skeletons/util/animation.ts]: Did the second option 😄

**Review by cdeweyx — APPROVED** [review]

File: frontend/src/metabase/visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.unit.spec.tsx [hunk 3]
```diff
@@ -1,74 +1,89 @@
...
-  it("should render area", () => {
-    render(<ChartSkeleton display="area" name="Area" />);
-    expect(screen.getByText("Area")).toBeInTheDocument();
-  });
-
-  it("should render bar", () => {
-    render(<ChartSkeleton display="bar" name="Bar" />);
-    expect(screen.getByText("Bar")).toBeInTheDocument();
-  });
+jest.unmock("metabase/components/Popover");
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.unit.spec.tsx:6]: Should we move that into a `beforeAll`/`beforeEach`?

**Review by kamilmielnik — APPROVED** [review]

File: frontend/src/metabase/visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.unit.spec.tsx (hunk 3 above)
Comment (oisincoveney) [reply frontend/src/metabase/visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.unit.spec.tsx:6]: Yeah, that's a decent call, I'll move it to `beforeAll`
