### PR TITLE
Preprocess queries before data perms check

### LINKED ISSUE #45595: Sandboxed users that in 49 were able to save questions are not able to do it in 50
### Describe the bug

A user that could create and save queries in 49 can't do it in 50.11. The error "You cannot save this Question because you do not have permissions to run its query" pops up in the saving modal even though permissions are OK to run queries and save into his personal collection

### To Reproduce

1. Spin up 49.20
2. Create a test user and test group. Give an attribute UserID = 1 to the test user and add it to the test group
3. Block data access for All Users group of the Sample Database.  I also gave No Access perms to Our Analytics collection to all users and the test group to match a customer's setup, but I don't think this is relevant to this bug
4. Give Sandboxing permissions to the Orders table for the Test Group, and set the sandboxing to match the UserID
5. See that the user can easily create a question from that data and save it in his personal collection.
6. Upgrade to 50.x (i did it with 50.11)
7. Log in as the test user. Try to save a question from the Orders table into your personal collection. You will see: "You cannot save this Question because you do not have permissions to run its query" error. This is not expected

### Expected behavior

User should be able to save the question, as it previously could

### Logs

[de93ec6d-a244-43a0-83b2-e7e2e89c289b] 2024-07-15T15:23:13-03:00 WARN metabase.server.middleware.log POST /api/card 403 41.1 ms (10 DB calls) {:metabase-user-id 2} 
{:via
 [{:type clojure.lang.ExceptionInfo,
   :message "You cannot save this Question because you do not have permissions to run its query.",
   :data
   {:status-code 403,
    :query
    {:database 1,
     :type "query",
     :query
     {:source-table 5,
      :aggregation [["count"]],
      :breakout
      [["field" 35 {:base-type "type/Float", :binning {:strategy "default"}}]
       ["field" 34 {:base-type "type/BigInteger"}]]}},
    :required-perms {:perms/create-queries {5 :query-builder}, :perms/view-data :unrestricted},
    :actual-perms
    #{"/collection/namespace/snippets/root/" "/collection/root/read/" "/collection/4/" "/application/subscription/"}},
   :at [metabase.api.card$check_data_permissions_for_query invokeStatic "card.clj" 417]}],
 :trace
 [[metabase.api.card$check_data_permissions_for_query invokeStatic "card.clj" 417]
  [metabase.api.card$check_data_permissions_for_query invoke "card.clj" 407]
  [metabase.api.card$fn__99374 invokeStatic "card.clj" 449]
  [metabase.api.card$fn__99374 invoke "card.clj" 432]
  [compojure.core$wrap_response$fn__52910 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__52894 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__52899 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__52903 invoke "core.clj" 151]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52903 invoke "core.clj" 152]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [metabase.server.middleware.auth$enforce_authentication$fn__98244 invoke "auth.clj" 18]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [compojure.core$make_context$handler__52950 invoke "core.clj" 290]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 300]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52903 invoke "core.clj" 153]
  [clojure.lang.Var invoke "Var.java" 393]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 199]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 199]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 199]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [metabase.api.routes$fn__104704$fn__104705 invoke "routes.clj" 70]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 31]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [metabase.server.routes$fn__104984$fn__104985 doInvoke "routes.clj" 73]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [compojure.core$make_context$handler__52950 invoke "core.clj" 290]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 300]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52903 invoke "core.clj" 153]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52903 invoke "core.clj" 153]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52903 invoke "core.clj" 153]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__52903 invoke "core.clj" 153]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 199]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 199]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 199]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [compojure.core$make_context$handler__52950 invoke "core.clj" 290]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 300]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922$f__52923$respond_SINGLEQUOTE___52924 invoke "core.clj" 197]
  [compojure.core$make_context$fn__52954 invoke "core.clj" 301]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [compojure.core$routes$fn__52922$f__52923 invoke "core.clj" 198]
  [compojure.core$routes$fn__52922 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__101123 invoke "exceptions.clj" 107]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__101120 invoke "exceptions.clj" 96]
  [metabase.server.middleware.log$log_api_call$fn__107323$fn__107324$fn__107325 invoke "log.clj" 236]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invokeStatic "diagnostic.clj" 18]
  [metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info invoke "diagnostic.clj" 12]
  [metabase.server.middleware.log$log_api_call$fn__107323$fn__107324 invoke "log.clj" 227]
  [toucan2.execute$do_with_call_counts invokeStatic "execute.clj" 112]
  [toucan2.execute$do_with_call_counts invoke "execute.clj" 103]
  [metabase.server.middleware.log$log_api_call$fn__107323 invoke "log.clj" 226]
  [metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__113447 invoke "browser_cookie.clj" 40]
  [metabase.server.middleware.security$add_security_headers$fn__101079 invoke "security.clj" 238]
  [ring.middleware.json$wrap_json_body$fn__113706 invoke "json.clj" 64]
  [metabase.server.middleware.offset_paging$handle_paging$fn__87551 invoke "offset_paging.clj" 43]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__54365 invoke "json.clj" 83]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__113795 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__113814 invoke "params.clj" 77]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__70006 invoke "misc.clj" 60]
  [metabase.server.middleware.session$reset_session_timeout$fn__77190 invoke "session.clj" 552]
  [metabase.server.middleware.session$bind_current_user$fn__77156$fn__77157 invoke "session.clj" 446]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 425]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 408]
  [metabase.server.middleware.session$bind_current_user$fn__77156 invoke "session.clj" 445]
  [metabase.server.middleware.session$wrap_current_user_info$fn__77137 invoke "session.clj" 383]
  [metabase.server.middleware.session$wrap_session_id$fn__77109 invoke "session.clj" 259]
  [metabase.server.middleware.auth$wrap_static_api_key$fn__98252 invoke "auth.clj" 32]
  [ring.middleware.cookies$wrap_cookies$fn__113634 invoke "cookies.clj" 200]
  [metabase.server.middleware.misc$add_content_type$fn__69988 invoke "misc.clj" 28]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__70014 invoke "misc.clj" 77]
  [ring.middleware.gzip$wrap_gzip$fn__113676 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__70017 invoke "misc.clj" 94]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__113463 invoke "ssl.clj" 41]
  [metabase.server$async_proxy_handler$fn__70352 invoke "server.clj" 77]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.StatisticsHandler handle "StatisticsHandler.java" 173]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 122]
  [org.eclipse.jetty.server.Server handle "Server.java" 563]
  [org.eclipse.jetty.server.HttpChannel$RequestDispatchable dispatch "HttpChannel.java" 1598]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 753]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 501]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 287]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 314]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 100]
  [org.eclipse.jetty.io.SelectableChannelEndPoint$1 run "SelectableChannelEndPoint.java" 53]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy runTask "AdaptiveExecutionStrategy.java" 421]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy consumeTask "AdaptiveExecutionStrategy.java" 390]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy tryProduce "AdaptiveExecutionStrategy.java" 277]
  [org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy run "AdaptiveExecutionStrategy.java" 199]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 411]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 969]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner doRunJob "QueuedThreadPool.java" 1194]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 1149]
  [java.lang.Thread run "Thread.java" 833]],
 :cause "You cannot save this Question because you do not have permissions to run its query.",
 :data
 {:status-code 403,
  :query
  {:database 1,
   :type "query",
   :query
   {:source-table 5,
    :aggregation [["count"]],
    :breakout
    [["field" 35 {:base-type "type/Float", :binning {:strategy "default"}}]
     ["field" 34 {:base-type "type/BigInteger"}]]}},
  :required-perms {:perms/create-queries {5 :query-builder}, :perms/view-data :unrestricted},
  :actual-perms
  #{"/collection/namespace/snippets/root/" "/collection/root/read/" "/collection/4/" "/application/subscription/"}},
 :message "You cannot save this Question because you do not have permissions to run its query.",
 :query
 {:database 1,
  :type "query",
  :query
  {:source-table 5,
   :aggregation [["count"]],
   :breakout
   [["field" 35 {:base-type "type/Float", :binning {:strategy "default"}}]
    ["field" 34 {:base-type "type/BigInteger"}]]}},
 :required-perms {:perms/create-queries {5 :query-builder}, :perms/view-data :unrestricted},
 :actual-perms
 #{"/collection/namespace/snippets/root/" "/collection/root/read/" "/collection/4/" "/application/subscription/"}}

### Information about your Metabase installation

```JSON
- 50.11
```

### Severity

P1

### Additional context

Maybe caused by: https://github.com/metabase/metabase/pull/45000 ?

### PR DESCRIPTION
**Pull request by johnswanson**
When we run queries, we preprocess them, during which the sandboxing middleware adds information that we use when checking permissions later on in query processing.

When we checked data permissions before saving a card, we were checking permissions on the raw query, without preprocessing. Without the data provided by the sandboxing middleware, the permission check sometimes failed (depending on the permissions for other tables in the DB).

Fixes #45595

### CODE REVIEW

File: src/metabase/api/card.clj [hunk 1]
```diff
@@ -435,20 +436,24 @@
...
-                       :query          query
-                       :required-perms (if (instance? Throwable required-perms)
-                                         :error
-                                         required-perms)
-                       :actual-perms   @api/*current-user-permissions-set*}
-                      (when (instance? Throwable required-perms)
-                        required-perms))))))
+  (let [preprocessed-query (try (some-> query qp/preprocess)
+                                (catch Exception e
+                                  (log/warn e "Error preprocessing query for permissions check, using original!")
```
Comment (dpsutton) [inline src/metabase/api/card.clj:441]: should this be a warn? (i genuinely don't know. Want us to justify this level, not saying we have to change it)

File: src/metabase/query_processor.clj [hunk 2]
```diff
@@ -21,6 +21,9 @@
    [metabase.util.log :as log]
    [metabase.util.malli :as mu]))
 
+(def preprocess "For export"
+  qp.preprocess/preprocess)
```
[the remark this answers is not in the document]
Comment (johnswanson) [reply src/metabase/query_processor.clj:25]: We could - I was thinking that over time we want to move to having defined APIs for modules, so wasn't sure about reaching into `qp.preprocess` for this. But I'd be fine either way.

[the remark this answers is not in the document]
Comment (noahmoss) [reply src/metabase/query_processor.clj:25]: `qp.preprocess/preprocess` is already used in a lot of places, so I think it's the expected interface for this. I'd lean towards not changing that in this PR

File: src/metabase/api/card.clj (hunk 1 above)
Comment (noahmoss) [reply src/metabase/api/card.clj:441]: You'd think that if you can't preprocess a query you can't run it, which is what we're trying to check here anyway. So maybe we should just let the error bubble up? But maybe that feels a little risky.

**Review by noahmoss — APPROVED** [review]

**Comment by johnswanson** [comment]
> You'd think that if you can't preprocess a query you can't run it, which is what we're trying to check here anyway. So maybe we should just let the error bubble up? But maybe that feels a little risky.

I think this is right, but it seems like we're doing some specific checks to get better error messages than the QP can provide. For example, if you try to create a card with a query like this:

```
{:database bird-counts-db-id
                                                        :type     :native
                                                        :native   {:query         "SELECT COUNT(*) FROM PRODUCTS WHERE {{FILTER}}"
                                                                   :template-tags {"FILTER" {:id           "_FILTER_"
                                                                                             :name         "FILTER"
                                                                                             :display-name "Filter"
                                                                                             :type         :dimension
                                                                                             :dimension    [:field (mt/id :venues :name) nil]
                                                                                             :widget-type  :string/=
                                                                                             :default      nil}}}}
```

We give back `Invalid Field Filter: Field {0} belongs to Database {1}, but the query is against Database {2}`, where QP will give us:

```
Error preprocessing query in clojure.lang.AFunction$1@494c947d: Error building query parameter map: Error determining value for parameter \"FILTER\": Can't find field with ID: 50
```

File: src/metabase/api/card.clj (hunk 1 above)
Comment (johnswanson) [reply src/metabase/api/card.clj]: When I added this I was thinking that the only reason this would fail was if the query was malformed somehow, which was unlikely to happen in production (since it's our own frontend constructing it) and a problem worthy of a warning if it did.

But I think this could happen for other reasons which might be caused by user error. So I've changed this to `log/info` instead.
