### PR TITLE
Format Rows toggle also applies to Column Names

### LINKED ISSUE #42500: Columns are excluded from the unformatted option when downloading
### Describe the bug

Columns are excluded form the formatted/unformatted option when downloading ... External systems are expecting an unformatted column which used to be downloaded before 48 differently when it does now in 49

### To Reproduce

1. Go to New -> Question -> Orders -> Save
2. Go to Total Column -> Rename it to ->  "This is a formatted column"

image

3. Download the question using unformatted option, notice the name remains the same even though results themself change:

image

### Expected behavior

If you download unformatted results then nothing should keep the formatting. Applies for Question, Dashboards and anywhere else we offer the unformatted option

### Logs

Nothing that is relevant

### Information about your Metabase installation

```JSON
1.49.9 and master
```

### Severity

Blocker since external systems are expecting an unformatted column which used to be downloaded before 48 differently when it does now in 49

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adam-james-v**
Fixes: #42500
When format-rows is false, we want to also pass that true/false value to the title column formatting.

That is, if a column is renamed and formatting is applied, we want to use that column's name. But, if a column is renamed and the user exports unformatted csv or json, the custom column name should NOT be used, as was the behaviour in prior versions.

### CODE REVIEW

File: test/metabase/api/card_test.clj [hunk 1]
```diff
@@ -3483,17 +3483,26 @@
                 (mt/user-http-request :crowberto :post 400 "card" card-data)))))))
 
 (deftest ^:parallel format-export-middleware-test
-  (testing "The `:format-export?` query processor middleware has the intended effect on file exports."
+  (testing "The `:format-rows` query processor middleware has the intended effect on file exports."
```
Comment (escherize) [inline test/metabase/api/card_test.clj:3486]: > has the intended effect

Could you explain what this means in some more detail?

**Review by escherize — APPROVED** [review]
Looks good, just 1 small thing about a `testing` doc string
