### PR TITLE
Move table hidden table filtering to backend

### LINKED ISSUE #9759: Hidden tables show in "our data" page when it is marked as technical/cruft
Browser: Firefox Quantum (66.0.1)
OS: Linux Manjaro
Databases: Postgres 11.2
Metabase version: 31.2
Metabase hosting env: Ubuntu 18.04.1 LTS
Internal db: H2

### Steps to reproduce
1. Change visibility of a table to hidden of a data model under admin.
2. It won't appear under "Our Data" page now.
3. Change "Why hide" to technical/cruft.
4. Now, it appears in "Our Data" page.

https://github.com/metabase/metabase/pull/8831 should respect technical/cruft visibility type.

### PR DESCRIPTION
**Pull request by paulrosenzweig**
Fixes #9759

Filtering out hidden tables was happening in a few places across the front end. It seemed to keep breaking as the way we fetched data was updated. This PR moves it to the backend.

### CODE REVIEW

File: test/metabase/api/database_test.clj [hunk 1]
```diff
@@ -281,6 +281,18 @@
...
+(deftest fetch-database-metadata-without-hidden-test
+  (testing "GET /api/database/:id/metadata"
+    (try
+      (db/update! Table (mt/id :categories) :visibility_type "hidden")
+      (is (= ["CHECKINS" "USERS" "VENUES"]
+             (->> ((mt/user->client :rasta) :get 200 (format "database/%d/metadata" (mt/id)))
+                  :tables
+                  (map :name))))
+      (finally
+        (db/update! Table (mt/id :categories) :visibility_type nil)))))
```
Comment (paulrosenzweig) [inline test/metabase/api/database_test.clj:293]: @camsaul I need to add more tests, but wanted to check in on the right approach first. Is there a better way to temporarily adjust the fixture data like I do here setting `:visibility_type` to hidden?

Comment (camsaul) [reply test/metabase/api/database_test.clj:293]: You can use `with-temp-vals-in-dB` to do it. Example: https://github.com/metabase/metabase/blob/005b4567f8ab8eb05d1719e98ded66441332bb49/modules/drivers/bigquery/test/metabase/driver/bigquery/query_processor_test.clj#L126

File: frontend/src/metabase/selectors/metadata.js [hunk 2]
```diff
@@ -104,16 +104,9 @@ export const getMetadata = createSelector(
...
-        : schema.database && schema.database.tables.length > 0
-        ? // if the schema has a database with tables, use those
-          schema.database.tables.filter(t => t.schema_name === schema.name)
-        : // otherwise use any loaded tables that match the schema id
-          Object.values(meta.tables).filter(
-            t => t.schema && t.schema.id === schema.id,
-          ),
+      Object.values(meta.tables).filter(
+        t => t.schema && t.schema.id === schema.id,
+      ),
```
Comment (paulrosenzweig) [inline frontend/src/metabase/selectors/metadata.js:109]: @tlrobinson I wanted to get your thoughts on dropping those optimizations.

With this PR's change, hidden tables are only loaded in the datamodel pages. If a user has loaded tables in the main app and then goes to the datamodel we wouldn't show the full list. It seems that this bug occurred because even though the full table list was loaded, the `schema.tables` and `database.tables` lists weren't updated. Removing this optimization fixed it.

Do you think removing this will kill performance?

**Review by tlrobinson — DISMISSED** [review]
Unfortunately this isn't going to work correctly if you load with and without `include_hidden_tables`  in the same session, because after you load the hidden tables they will be in the entity store until you refresh the browser.

For example, try hiding a table in the data model then going to the native query editor and looking at the data reference. The hidden table will appear until you refresh. After you refresh, if you again navigate to the data model and back then the hidden tables will appear.

I'm not sure what the best solution is.

We could also filter out the hidden tables when calling ` hydrate(meta.schemas, "tables", schema =>` and (and similar for databases' `tables` and tables' `fields`?) and have additional properties like `allTables`/`tablesIncludingHidden` for the few cases where we want to see them all.

File: frontend/src/metabase/selectors/metadata.js (hunk 2 above)
Comment (tlrobinson) [reply frontend/src/metabase/selectors/metadata.js:109]: Aside from main problem I described already, I do think in general it's better to have a single "source of truth", so this might be good to do. A possible downside is it loses the ordering provided by the API, if that matters.

I could see this being slow if there are lots of schemas/tables. One optimization to avoid iterating the whole list of tables for every schema would be to pre-group tables by schema, something like:

```js
const tablesBySchema = _.groupBy(meta.tables, (id, table) => table.schema && table.schema.id);
hydrate(meta.schemas, "tables", schema => tablesBySchema[schema.id] || [])
```

We should also make sure table objects returned by the server always have a `schema` property (or they're added before normalizing like in .

**Comment by paulrosenzweig** [comment]
> try hiding a table in the data model then going to the native query editor and looking at the data reference

@tlrobinson, that seems to work for me. Though, it's possible that I missed some client-side filtering that's masking the issue. I'll try and trace where the filtering is happening.

I thought the list of tables would be scoped by the query used for the fetch (`include_hidden_tables=true` vs empty). Does the entity system not allow for server-side filtering?

**Comment by paulrosenzweig** [comment]
@camsaul I think this is ready for backend review.

---

> what do you think about using entity lists without metadata walking in the data model?

@tlrobinson, this is what I ended up doing. I added back the `schema.tables` optimization but updated the relevant data model component so that it didn't access `schema.tables`. Instead it uses the tables it gets from `Tables.loadList` which include hidden.

It seemed easier than splitting `getMetadata` into filtered and unfiltered forms and passing a flag through the list loader to access the unfiltered one.

However, this approach didn't work for fields. There, I did client side filtering instead. I don't really like this hybrid setup, but I feel I've already spent too long on this.

File: src/metabase/api/database.clj [hunk 3]
```diff
@@ -264,9 +266,13 @@
   []
   (saved-cards-virtual-db-metadata :include-tables? true, :include-fields? true))
 
-(defn- db-metadata [id]
+(defn- db-metadata [id include-hidden-tables]
```
Comment (camsaul) [inline src/metabase/api/database.clj:269]: I would name this `include-hidden-tables?` since it's a boolean param

File: src/metabase/api/database.clj [hunk 4]
```diff
@@ -240,7 +241,8 @@
     (-> (hydrate db (case include
                       "tables"        :tables
                       "tables.fields" [:tables [:fields [:target :has_field_values] :has_field_values]]))
-        (update :tables (partial filter mi/can-read?)))))
+        (update :tables (fn [tables]
+                          (filter #(and (nil? (:visibility_type %)) (mi/can-read? %)) tables))))))
```
Comment (camsaul) [inline src/metabase/api/database.clj:245]: This isn't a request to change your code, just some feedback for writing more concise code for future reference. 

Instead of `(nil? (:visibility_type %))` you could do `(complement :visibility_type)`. `(:visibility_type table)` is truthy for any value besides `nil` and `false`. So the `complement` would be truthy for `nil` *or* `false`. Since visibility type is a keyword it's never going to be `false`.

You could tighten this up a little further with `every-pred` which combines several predicate functions into a single predicate function as if by `and`:

```clj
(fn [tables]
  (filter (every-pred (complement :visibility_type) mi/can-read?) tables))
```

At that point I'd take it a step further and use `partial` e.g.

```clj
(partial filter (every-pred (complement :visibility_type) mi/can-read?))
```

Now that is definitely a bit more concise. But I think the jury is out on whether it's clearer. Either way the code is fine as it is

File: src/metabase/api/database.clj [hunk 5]
```diff
@@ -264,9 +266,13 @@
...
   (saved-cards-virtual-db-metadata :include-tables? true, :include-fields? true))
 
-(defn- db-metadata [id]
+(defn- db-metadata [id include-hidden-tables]
   (-> (api/read-check Database id)
       (hydrate [:tables [:fields [:target :has_field_values] :has_field_values] :segments :metrics])
+      (update :tables (fn [tables]
+                        (if include-hidden-tables
+                          tables
+                          (filter #(nil? (:visibility_type %)) tables))))
```
Comment (camsaul) [inline src/metabase/api/database.clj:275]: You could do 

```clj
(update :tables (if include-hidden-tables?
                  identity
                  (partial remove :visibility_type)))
```

here to make it a bit more concise. `(remove pred coll)` is the same as `(filter (complement pred) coll)`.

File: test/metabase/api/database_test.clj [hunk 6]
```diff
@@ -281,6 +282,19 @@
...
              (assoc resp :tables (filter #(= "CATEGORIES" (:name %)) (:tables resp))))))))
 
+(defn- is-named [name]
+  #(= name (:name %)))
+
+(deftest fetch-database-metadata-include-hidden-test
+  (mt/with-temp-vals-in-db Table (mt/id :categories) {:visibility_type "hidden"}
+    (testing "GET /api/database/:id/metadata?include_hidden_tables=true"
+      (let [tables (:tables ((mt/user->client :rasta) :get 200 (format "database/%d/metadata?include_hidden_tables=true" (mt/id))))]
+        (is (some (is-named "CATEGORIES") tables))))
```
Comment (camsaul) [inline test/metabase/api/database_test.clj:292]: This doesn't matter too much but you could do something like 

```clj
(some (partial = "CATEGORIES") (map :name tables))
```

or
 
```clj
(contains? (set (map :name tables)) "CATEGORIES")
```

instead of defining the separate function

File: test/metabase/api/database_test.clj [hunk 7]
```diff
@@ -281,6 +282,19 @@
            (let [resp ((mt/user->client :rasta) :get 200 (format "database/%d/metadata" (mt/id)))]
              (assoc resp :tables (filter #(= "CATEGORIES" (:name %)) (:tables resp))))))))
 
+(defn- is-named [name]
```
Comment (camsaul) [inline test/metabase/api/database_test.clj:285]: Predicate functions should end in `?` e.g. `is-named?`

**Review by camsaul — APPROVED** [review]
Backend code looks good to me other than a couple names that really need to end in `?`

File: src/metabase/api/database.clj (hunk 4 above)
Comment (paulrosenzweig) [reply src/metabase/api/database.clj:245]: 🎉 thanks for all the tips! They're super helpful as I wade into Clojure's endless supply of small utility functions.

**Comment by tlrobinson** [comment]
> Does the entity system not allow for server-side filtering?

Not for nested properties, only the "top level" lists via ListLoader. To be clear, the problem is if you load a `table` with a filter on `fields`, for example you might get something in the store like


```js
{
  entities: {
    tables: {
      "1": { fields: [1,2,3] }
    }
  }
}
```

then if you load without a filter it will replace it with the new `table` object, override the list of fields

```js
{
  entities: {
    tables: {
      "1": { fields: [1,2,3,4,5,6] }
    }
  }
}
```

Whereas if you use a list loader on `fields` directly you might get something like

```
{
  entities: {
    field_lists: {
      "{ table_id: 1 }": [1,2,3],
      "{ table_id: 1, include_hidden_tables: true }": [1,2,3,4,5,6],
    }
  }
}
```

So yeah, using list loaders is probably the right way to do it. I'm struggling to think of a way to easily support filtering in nested properties.

However, maybe we should just say `database.tables`, `schema.tables` and `table.fields` should *never* include hidden tables, and if you need the hidden fields *then* you should use a list loader.

**Comment by paulrosenzweig** [comment]
> maybe we should just say database.tables, schema.tables and table.fields should never include hidden tables, and if you need the hidden fields then you should use a list loader.

Works for me! I'll add a `include_sensitive_fields` flag to `/api/database/:id/field` and then update the data model.

> That would mean having to completely remove code like `Object.values(meta.tables)...`

I guess we could avoid that by updating `getNormalizedFields` and `getNormalizedTables` to filter out hidden. Or, maybe we avoid storing hidden entities when normalizing a response? Either way we have the ugly situation of filtering on the server and again in the metadata logic. That would let us safely access `meta.tables` though.

**Review by kdoh — APPROVED** [review]
Seems to be doing what it says on the tin. Spent a bit of time hiding and unhiding fields and not seeing anything show up where I don't expect it. (Haven't done a code review on this though).

**Review by robdaemon — APPROVED** [review]
backend code looks :+1: - can't speak to the frontend

**Comment by kdoh** [comment]
@paulrosenzweig Is this PR supposed to address #2146 at all?

**Comment by kdoh** [comment]
Hrm. Ran into an issue while playing with this some more where if I hit `Hidden` control on a table's visibility it doesn't do anything and blows up my browser.

Screen Shot 2020-05-21 at 12 46 26 PM


I get the following errors in my browser console.
```
[Error] Request entities,tables,3,update failed: – TypeError: null is not an object (evaluating 'table.fields') — schema_metadata.js:263
TypeError: null is not an object (evaluating 'table.fields') — schema_metadata.js:263
	_callee4$ (app-main.hot.bundle.js:93500)
	tryCatch (vendor.hot.bundle.js:222788)
	invoke (vendor.hot.bundle.js:223014)
	step (app-main.hot.bundle.js:93123:192)
	(anonymous function) (app-main.hot.bundle.js:93123:407)
	promiseReactionJob
[Error] TypeError: null is not an object (evaluating 'table.fields')
	render (vendor.hot.bundle.js:189998)
	measureLifeCyclePerf (vendor.hot.bundle.js:170748)
	_renderValidatedComponentWithoutOwnerOrContext (vendor.hot.bundle.js:171467)
	_renderValidatedComponent (vendor.hot.bundle.js:171494)
	_updateRenderedComponent (vendor.hot.bundle.js:171418)
	_performComponentUpdate (vendor.hot.bundle.js:171396)
	updateComponent (vendor.hot.bundle.js:171317)
	performUpdateIfNecessary (vendor.hot.bundle.js:171233)
	performUpdateIfNecessary (vendor.hot.bundle.js:177731)
	runBatchedUpdates (vendor.hot.bundle.js:178488)
	perform (vendor.hot.bundle.js:180467)
	perform (vendor.hot.bundle.js:180467)
	flushBatchedUpdates (vendor.hot.bundle.js:178510)
	flushBatchedUpdates
	closeAll (vendor.hot.bundle.js:180533)
	perform (vendor.hot.bundle.js:180480)
	dispatchEvent (vendor.hot.bundle.js:175639)
	dispatchEvent
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'table.fields')
	dispatchException (vendor.hot.bundle.js:223285)
	invoke (vendor.hot.bundle.js:223006)
	step (app-main.hot.bundle.js:93123:192)
	(anonymous function) (app-main.hot.bundle.js:93123:407)
	promiseReactionJob```

**Comment by flamber** [comment]
1. Not sure if it's this branch, but all linked tables doesn't show in QB. Example Sample Dataset > Orders > Summarize Count by Product.Category.
2. :+1: Tables are hidden from Browse Data (test with a schema-based db)
3. I have to click twice on Visibility Queryable-link, when the table is Hidden (just saw Kyle already posted the error)
4. This might be expected behavior: When a table is hidden, then existing columns with Foreign Key to the hidden table are empty - showing the table again will show the reference. Same if "Display values" is set to "Use foreign key". There doesn't seem to be any problems with queries.
5. :+1: It's hiding the hidden table and do-not-include column from the auto-complete in the SQL editor. It's still possible to manually write it.

**Review by camsaul — APPROVED** [review]
backend stuff works for me
