### PR TITLE
Fix numeric parameter value parsing when there are no connected database fields

### LINKED ISSUE #51058: Click behavior doesn't work for numeric columns for questions based on models
### Describe the bug

Until now, it was possible to set a filter field of type “Number” in dashboard with a numeric value corresponding to a row ID. 
Specifically, I was using the “click behavior” feature to set the filter value with the ID of the row clicked.  

Today, I had to change the filter type from “Number” to “ID” for all my filters of this type because clicking no longer changed the filter value. 

For instance, that how my widget fetch the data used to set the filter:
```
SELECT  name, id
FROM
...
```

### To Reproduce

This is an example on how to setup the dashboard:

Image

Image

Image

The last image was the setting for the filter until today.

If the "Filter or parameter type" is set to "ID" the click behavior works fine.

### Expected behavior

To be in line with the previous version of metabase, the filter should be set even if the filter type is "Number" when a numeric ID is used to set its value.

### Logs

_No response_

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-12-04",
      "tag": "v0.52.1",
      "hash": "5bc320b"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.5+11-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.5+11-LTS",
    "os.name": "Linux",
    "os.version": "5.15.164.1-1.cm2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

blocking some users

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ranquild**
Fixes https://github.com/metabase/metabase/issues/51058

How to verify:
- Create a new SQL query `SELECT ID, RATING FROM PRODUCTS [[WHERE RATING = {{rating}}]]`. Make `Rating` a `number` parameter. Save it.
- Create a new dashboard with the question above. Add a `Number` / `Equal to` parameter and connect it to `Rating`.
- Setup a click behavior on the `ID` column. It should update the dashboard filter.
- Save the dashboard.
- After clicking on ID column values, the filter should be properly updated and the query executed.

Before
Screenshot 2025-01-22 at 11 36 47

After
Screenshot 2025-01-22 at 11 36 12

### CODE REVIEW

File: frontend/src/metabase-lib/v1/parameters/utils/parameter-parsing.ts [hunk 1]
```diff
@@ -58,29 +59,27 @@ export function parseParameterValue(value: any, parameter: Parameter) {
...
 
-function parseParameterValueForNumber(value: string | string[]) {
-  if (Array.isArray(value)) {
-    const numbers = value.map(number => parseFloat(number));
-    return numbers.every(number => !isNaN(number)) ? numbers : null;
-  }
+function parseParameterValueForNumber(value: ParameterValueOrArray) {
+  // HACK to support multiple values for SQL parameters
+  // https://github.com/metabase/metabase/issues/25374#issuecomment-1272520560
+  if (typeof value === "string") {
```
Comment (ranquild) [inline frontend/src/metabase-lib/v1/parameters/utils/parameter-parsing.ts:65]: Not breaking the hack now as it's unclear how many people use it

**Review by uladzimirdev — APPROVED** [review]
LGTM
