### PR TITLE
Incremental Pivot Processing for Exports

### LINKED ISSUE #44556: Big Pivot Tables export breaks or fail silently
### Describe the bug

While trying to export a pivot table "Download full results" button fails silently without any errors shown (both formatted and unformatted options doesn't work). Metabase is running on Kubernetes on 2vcpu and 8 GB memory. On one try I also got a 502 error and Metabase crashed and restarted (doesn't show in the logs).

### To Reproduce

Pivot table size: 42000 rows
row columns: 5 (300 total rows)
pivot columns: 2 (that expand to 70 columns when pivoted)

### Expected behavior

Pivot table CSV file is exported succesfully

### Logs

Didn't find relevant logs.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.10.216-204.855.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-19",
      "tag": "v1.50.6",
      "hash": "a5fbebf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

P1

### PR DESCRIPTION
**Pull request by adam-james-v**
**Outstanding work**
- [x] - Embedding endpoints fail when `pivot_results` is passes like `/api/embed/dashboard/:token/dashcard/1/card/1/csv?format_rows=true&pivot_results=false`
- [x] - XLSX formatting setting is not working
- [x] FE: use Chip component

Fixes pivot exports for CSV and xlsx.

Fixes #44556

This PR:
- moves the `format_rows` query param for the various dowload endpoints (card, dashcard, public questions, etc.) to a `format-rows` body param (boolean)
- adds `pivot_results` boolean body param to the same endpoints to allow downloading pivot results either in pivoted form OR as the unpivoted results
- for xlsx exports, adds a 'native' pivot table matching the row/column/measure settings and allows the user to interact with an actual pivot table if they open the file in a spreadsheet app (assuming the app can handle pivot tables)
  - the unpivoted results are included in a 'data' sheet, and are the source data for the pivot table
  - the file is initialized with an empty pivot table, but rows are added in a streaming manner, keeping the memory use of this pivot export roughly equivalent to a non-pivoted export
- for csv pivoted exports, a nested map structure is used to build up the pivot data on a row-by-row basis, saving only the relevant aggregated data, keeping memory usage lower than if all rows are stored in memory and 'post processed' all at once.

In cases where the pivot rows/cols do combine into many many columns and rows, this can still be a large set of data,
but it should behave much better now in most cases.

The Excel export is a little more straightforward: create the export rows in the same fashion, streaming one row at a
time, and just post-process the sheet to add the pivot table in one shot at the end.

A CSV export of a pivot table, when exporting pivoted, looks like the pivoted data:

image

A Pivot table export when exporting 'non-pivoted' now correctly removes the 'pivot-grouping' column as well as the additional rows related to grand total/sub-totals/row-totals.

image

A 'native' pivot export 
image

### CODE REVIEW

File: src/metabase/api/card.clj [hunk 1]
```diff
@@ -702,10 +702,12 @@
 
   `parameters` should be passed as query parameter encoded as a serialized JSON string (this is because this endpoint
   is normally used to power 'Download Results' buttons that use HTML `form` actions)."
-  [card-id export-format :as {{:keys [parameters format_rows]} :params}]
+  [card-id export-format :as {{:keys [parameters]} :params
+                              {:keys [pivot-results format-rows]} :body}]
```
Comment (adam-james-v) [inline src/metabase/api/card.clj:706]: I thought that passing format-rows (and now also pivot-results) as body params is a bit better than passing them as query params

File: src/metabase/api/public.clj [hunk 2]
```diff
@@ -188,7 +188,7 @@
 (api/defendpoint GET "/card/:uuid/query/:export-format"
   "Fetch a publicly-accessible Card and return query results in the specified format. Does not require auth
   credentials. Public sharing must be enabled."
-  [uuid export-format :as {{:keys [parameters format_rows]} :params}]
+  [uuid export-format :as {{:keys [parameters format_rows pivot_results]} :params}]
```
Comment (adam-james-v) [inline src/metabase/api/public.clj:191]: since this endpoint is still a GET, pass both format_rows and pivot_results as query params here.

File: src/metabase/email/messages.clj [hunk 3]
```diff
@@ -392,7 +392,7 @@
   point in the future; for now, this function is a stopgap.
 
   Results are streamed synchronously. Caller is responsible for closing `os` when this call is complete."
-  [export-format format-rows? ^OutputStream os {{:keys [rows]} :data, database-id :database_id, :as results}]
+  [^OutputStream os {:keys [export-format format-rows? pivot?]} {{:keys [rows]} :data, database-id :database_id, :as results}]
```
Comment (adam-james-v) [inline src/metabase/email/messages.clj:395]: slightly refactor the args here to pass the flags in in a map instead.

File: src/metabase/query_processor/pivot.clj [hunk 4]
```diff
@@ -96,7 +96,8 @@
                        :pivot-cols    pivot-cols}))))
   (sort-by
    (partial group-bitmask num-breakouts)
-   (distinct
+   (m/distinct-by
```
Comment (adam-james-v) [inline src/metabase/query_processor/pivot.clj:99]: This change was needed because some group bitmasks end up being equivalent [0 1] and [1 0], but the order still matters as they correspond to how the user set up the pivot-rows and/or pivot-cols, which affects how the result is displayed. But, prior to this change, [0 1] and [1 0] would not be considered equivalent, and this would result in duplicated rows for the given group.

File: src/metabase/query_processor/pivot/postprocess.clj [hunk 5]
```diff
@@ -192,41 +58,181 @@
...
-        pivot-spec (add-pivot-measures pivot-spec)]
-    (vec (concat
-          (header-builder rows pivot-spec)
-          (row-builder rows pivot-spec)))))
+  (-> pivot-spec
+      (assoc :pivot-measures (pivot-measures pivot-spec))
+      (assoc :pivot-grouping (pivot-grouping-key (:column-titles pivot-spec)))))
+
+(mu/defn add-totals-settings :- ::pivot-spec
+  "Given a pivot-spec map without the `:pivot-measures` key, determine what key(s) the measures will be and assoc that value into `:pivot-measures`."
```
Comment (adam-james-v) [inline src/metabase/query_processor/pivot/postprocess.clj:66]: I'll have to change this docstring, it's a copy-paste... and isn't correct yet.

File: src/metabase/query_processor/pivot/postprocess.clj [hunk 6]
```diff
@@ -192,41 +58,181 @@
...
+     :data           {}
+     :row-values     (zipmap pivot-rows (repeat (sorted-set)))
+     :column-values  (zipmap pivot-cols (repeat (sorted-set)))
+     :measure-values (zipmap pivot-measures (repeat (sorted-set)))}))
+
+(defn- update-set [m k v]
+  (update m k conj v))
+
+(defn- update-aggregate [measure-aggregations new-values agg-fns]
+  (into {}
```
Comment (adam-james-v) [inline src/metabase/query_processor/pivot/postprocess.clj:92]: also add a docstring explaining this, it's a little confusing

Comment (adam-james-v) [reply src/metabase/query_processor/pivot/postprocess.clj:92]: I actually am wondering now as I do this if there may be a missed case or two with aggregation; supposing someone sets up an average, the aggregation logic works fine for each 'cell' of the table (since the pivot query processor already does the aggregating), but might not apply when doing totals/subtotals, since the data structure used for the pivot post processing does indeed take care of totals aggregating. This means it might mis-calculate the totals for average. I will check this

File: src/metabase/query_processor/pivot/postprocess.clj [hunk 7]
```diff
@@ -192,41 +58,181 @@
...
+                          col-combo
+                          [measure-key]))))
+   (when row-totals?
+     (for [measure-key pivot-measures]
+       (fmt (get ordered-formatters measure-key)
+            (get-in totals [:section-totals section measure-key]))))))
+
+(defn- build-grand-totals
+  "Build grand totals row."
+  [{:keys [pivot-cols pivot-rows]} col-combos pivot-measures totals row-totals? ordered-formatters]
```
Comment (adam-james-v) [inline src/metabase/query_processor/pivot/postprocess.clj:199]: some of these build fns could probably do with a slight refactor of the order/grouping of args. (eg. should all of them take the config map as 1st arg, then row/col combos, then whatever else is needed.)

File: src/metabase/query_processor/streaming/csv.clj [hunk 8]
```diff
@@ -72,50 +73,72 @@
...
-            ;; if we're processing a pivot result, we don't write it out yet, just store it
-            ;; so that we can post process the full set of results in finish!
-            (swap! rows! conj xf-row)
-            (do
-              (write-csv writer [xf-row])
-              (.flush writer)))))
+                              (into [] (for [i output-order] (row-v i))))
+                            row)]
+          (if (contains? @pivot-data :config)
+            ;; if we're processing a pivot result, we don't write it out yet, just aggregate it
```
Comment (adam-james-v) [inline src/metabase/query_processor/streaming/csv.clj:117]: My previous attempt at pivot post-processing stored every row in an atom and did the post-process aggregations/building of the table in one go, that proved to be memory-inefficient.

This approach still stores data in an atom, but it will only grow as big as the final table size anyway, and each row is just aggregated one at a time (so effectively only totals + distinct values are stored).

Of course, the nature of pivot tables is combinatorial and depends on the number of unique values in each pivot row and pivot column, so a user can still construct a table that is quite large, but this is a better approach than before.

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 9]
```diff
@@ -428,73 +429,76 @@
   "Adds a row of values to the spreadsheet. Values with the `scaled` viz setting are scaled prior to being added.
 
   This is based on the equivalent function in Docjure, but adapted to support Metabase viz settings."
-  {:arglists '([sheet values cols col-settings cell-styles typed-cell-styles])}
-  (fn [sheet _values _cols _col-settings _cell-styles _typed-cell-styles]
+  {:arglists '([sheet values cols col-settings cell-styles typed-cell-styles]
+               [sheet row-num values cols col-settings cell-styles typed-cell-styles])}
```
Comment (adam-james-v) [inline src/metabase/query_processor/streaming/xlsx.clj:433]: add an arity here that adds `row-num` as an arg. 

This is used in the pivot table case because the pivot initialization function needs to create an empty row to attach the pivot header sources. If we don't explicitly target that row number, all rows will be added in an append style, and be off by 1, and the pivot table will work but not have the heading labels.

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 10]
```diff
@@ -567,10 +556,18 @@
...
         (assoc :pivot-grouping-key (qp.pivot.postprocess/pivot-grouping-key titles)))))
 
-(defn- native-pivot
-  [rows
-   {:keys [pivot-grouping-key] :as pivot-spec}
-   {:keys [ordered-cols col-settings viz-settings]}]
+;; Below, we need to provide an AreaReference to create a pivot table.
+;; Creating an AreaReference will 'realize' every CellReference inside it, and so the larger the AreaReference,
+;; the more memory we use, and the larger the filesize.
+;; Unfortunately, we can't avoid this, so we try to only create a reference that matches the row count, which we can
```
Comment (adam-james-v) [inline src/metabase/query_processor/streaming/xlsx.clj:562]: this comment is outdated and I should fix it up

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 11]
```diff
@@ -589,106 +587,100 @@
...
+    (let [swb   (-> (SXSSFWorkbook. ^XSSFWorkbook wb)
+                    (doto (.setCompressTempFiles true)))
+          sheet (spreadsheet/select-sheet "data" swb)]
+      (doseq [i (range (count ordered-cols))]
+        (.trackColumnForAutoSizing ^SXSSFSheet sheet i))
+      (setup-header-row! sheet (count ordered-cols))
+      {:workbook swb
+       :sheet    sheet})))
+
+(defn- init-workbook
```
Comment (adam-james-v) [inline src/metabase/query_processor/streaming/xlsx.clj:614]: Refactor the reguarl workbook setup stuff into its own function, both `init-workbook` and `init-pivot` output a map with the workbook and the sheet to add rows to.

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 12]
```diff
@@ -589,106 +587,100 @@
...
-                (autosize-columns! sheet))))))
+        (let [ordered-row        (if output-order
+                                   (let [row-v (into [] row)]
+                                     (for [i output-order] (row-v i)))
+                                   row)
+              col-settings       (::mb.viz/column-settings viz-settings)
+              pivot-grouping-key @pivot-grouping-key
+              group              (get row pivot-grouping-key)
+              modified-row       (if pivot-grouping-key
+                                   (vec (m/remove-nth pivot-grouping-key ordered-row))
```
Comment (adam-james-v) [inline src/metabase/query_processor/streaming/xlsx.clj:668]: we want to remove the 'pivot-grouping' column from our rows.

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 13]
```diff
@@ -589,106 +587,100 @@
...
+                                   ordered-row)
+              {:keys [sheet]}    @workbook-data]
+          (when (or (not group)
+                    (= group 0))
```
Comment (adam-james-v) [inline src/metabase/query_processor/streaming/xlsx.clj:672]: We also only want to keep pivot-grouping = 0 rows. These are the actual data rows we care about, and they're the rows you'll see if you change the viz from a pivot to a regular table. pivot-grouping > 0 are subtotals, and would mess up the pivot table's values (they'd be wrong) if we write them to the file, so we just don't write them

File: src/metabase/query_processor/streaming/xlsx.clj [hunk 14]
```diff
@@ -589,106 +587,100 @@
...
-;; (which is basically that very large pivot tables can crash the export process),
-;; The post processing is disabled completely.
-;; This should remain `false` until it's fixed
-;; TODO: rework this post-processing once there's a clear way in app to enable/disable it, or to select alternate download options
-(def ^:dynamic *pivot-export-post-processing-enabled*
-  "Flag to enable/disable export post-processing of pivot tables.
-  Disabled by default and should remain disabled until Issue #44556 is resolved and a clear plan is made."
-  false)
+      (.addColumnLabel pivot-table DataConsolidateFunction/SUM #_(get aggregation-functions idx DataConsolidateFunction/SUM) idx))
+    (let [swb   (-> (SXSSFWorkbook. ^XSSFWorkbook wb)
```
Comment (adam-james-v) [inline src/metabase/query_processor/streaming/xlsx.clj:605]: The pivot table class/methods are only available in a XSSFWorkbook (non-streaming). So, we first create a non-streaming workbook, add the pivot table and set up its references, set up the sheets, etc. 

With the correct stuff set up, we can then turn that workbook into a streaming version, which is what we want. That's the key change compared to the last attempt at native pivot exports: we can use the streaming writer properly (one row at a time) instead of storing all rows in memory and writing them in one go at the end.

File: src/metabase/api/public.clj [hunk 15]
```diff
@@ -308,7 +309,7 @@
 (api/defendpoint POST ["/dashboard/:uuid/dashcard/:dashcard-id/card/:card-id/:export-format"
                        :export-format api.dataset/export-format-regex]
   "Fetch the results of running a publicly-accessible Card belonging to a Dashboard and return the data in one of the export formats. Does not require auth credentials. Public sharing must be enabled."
-  [uuid card-id dashcard-id parameters export-format]
+  [uuid card-id dashcard-id parameters export-format :as {{:keys [format-rows pivot-results]} :body}]
```
Comment (alxnddr) [inline src/metabase/api/public.clj:312]: I see in some places it is `format_rows` but in others `format-rows`. Will BE accept the underscore variant of the parameter in every endpoint?

Comment (adam-james-v) [reply src/metabase/api/public.clj:312]: I'll double check, but in the POST body it should be ok to send as `format_rows`

**Comment by NevRA** [comment]
@bshepherdson can you please review this?

File: frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx [hunk 16]
```diff
@@ -14,11 +10,39 @@ export const getRadioOverrides = (): MantineThemeOverride["components"] => ({
...
+          transition: "all 0.2s ease",
+          padding: 0,
+          "&:not([data-checked])": {
+            color: theme.fn.themeColor("brand"),
+          },
+          "[data-checked] &": {
+            backgroundColor: theme.fn.themeColor("brand"),
+            color: "white",
+          },
+        },
```
Comment (iethree) [inline frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx:42]: this new  radio variant looks good to me. Tagging @kdoh for design review

Screen Shot 2024-10-02 at 4 37 22 PM

File: frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx [hunk 17]
```diff
@@ -14,11 +10,39 @@ export const getRadioOverrides = (): MantineThemeOverride["components"] => ({
...
+          cursor: "pointer",
+          transition: "all 0.2s ease",
+          padding: 0,
+          "&:not([data-checked])": {
+            color: theme.fn.themeColor("brand"),
+          },
+          "[data-checked] &": {
+            backgroundColor: theme.fn.themeColor("brand"),
+            color: "white",
+          },
```
Comment (iethree) [inline frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx:41]:
```suggestion
          "&:not([data-checked])": {
            color: "var(--mb-color-brand)",
          },
          "[data-checked] &": {
            backgroundColor: "var(--mb-color-brand-light)",
            color: "var(--mb-color-text-white)",
          },
```

**Review by iethree — APPROVED** [review]
just reviewing the ui component changes, which look good, but should also get a design review.

File: resources/migrations/001_update_migrations.yaml [hunk 18]
```diff
@@ -9270,6 +9270,25 @@ databaseChangeLog:
...
+                columnName: pivot_results
+      changes:
+        - addColumn:
+            tableName: pulse_card
+            columns:
+              - column:
+                  name: pivot_results
+                  type: ${boolean.type}
+                  defaultValue: false
+                  remarks: Whether or not to apply pivot processing to the rows of the export
```
Comment (camsaul) [inline resources/migrations/001_update_migrations.yaml:9290]: Do we need to add this column? This info is already stored in viz settings but honestly it feels like it could be part of the query itself

File: src/metabase/email/messages.clj (hunk 3 above)
Comment (camsaul) [reply src/metabase/email/messages.clj:395]: nice

File: resources/migrations/001_update_migrations.yaml (hunk 18 above)
Comment (camsaul) [reply resources/migrations/001_update_migrations.yaml:9290]: Why do we only need to add it to `pulse_card` and not to `report_card`?

**Review by camsaul — APPROVED** [review]
Let's get this merged in but I do have a question:

I don't fully understand the need to add the `pivot_results` column to `pulse_card`... I don't love having multiple sources of truth 

Also it would be nice if we could move towards using this code for doing pivot post-processing in "normal" non-export QP runs so we could always do it on the backend and remove that post-processing code from the frontend. This has been on our wishlist for a while now. This is big step in that direction 💪

File: frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx [hunk 19]
```diff
@@ -14,11 +10,39 @@ export const getRadioOverrides = (): MantineThemeOverride["components"] => ({
     defaultProps: {
       size: "md",
     },
-    styles: (
-      theme: MantineTheme,
-      { labelPosition: _labelPosition }: RadioStylesParams,
-      { size = "md" },
-    ) => ({
+    variants: {
+      pill: (theme: MantineTheme) => ({
```
Comment (iethree) [inline frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx:14]: Would the mantine chip component fulfill your needs here?

https://mantine.dev/core/chip/

File: frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx (hunk 16 above)
Comment (iethree) [reply frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx:42]: see also: https://mantine.dev/core/chip/
