### PR TITLE
fix: bigquery more resilient querying

### LINKED ISSUE #47990: NullPointerException in BigQuery still in > 50.25
### Describe the bug

A customer just reported that they had this issue and 

### To Reproduce

Seems like this is a native query in BigQuery, but I don't know the conditions (yet)

### Expected behavior

Should work

### Logs

```
2024-09-18 11:20:21.264	
 :data {:rows [], :cols []}}
2024-09-18 11:20:21.264	
 :running_time 0,
2024-09-18 11:20:21.264	
 :row_count 0,
2024-09-18 11:20:21.264	
 :error nil,
2024-09-18 11:20:21.264	
 :context :question,
2024-09-18 11:20:21.264	
 :card_id 1924,
2024-09-18 11:20:21.264	
  "async.streaming_response$do_f_async$task__52029.invoke(streaming_response.clj:97)"],
2024-09-18 11:20:21.264	
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)"
2024-09-18 11:20:21.264	
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)"
2024-09-18 11:20:21.264	
  "query_processor.streaming$_streaming_response$fn__70064.invoke(streaming.clj:171)"
2024-09-18 11:20:21.264	
  "query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)"
2024-09-18 11:20:21.264	
  "query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)"
2024-09-18 11:20:21.264	
  "query_processor.streaming$_streaming_response$fn__70064$fn__70065.invoke(streaming.clj:174)"
2024-09-18 11:20:21.264	
  "query_processor.streaming$_streaming_response$fn__70064$fn__70065$fn__70066.invoke(streaming.clj:176)"
2024-09-18 11:20:21.264	
  "query_processor.card$process_query_for_card_default_run_fn$fn__84624$fn__84625.invoke(card.clj:177)"
2024-09-18 11:20:21.264	
  "query_processor.card$process_query_for_card_default_qp.invoke(card.clj:166)"
2024-09-18 11:20:21.264	
  "query_processor.card$process_query_for_card_default_qp.invokeStatic(card.clj:170)"
2024-09-18 11:20:21.264	
  "query_processor$process_query.invoke(query_processor.clj:69)"
2024-09-18 11:20:21.264	
  "query_processor$process_query.invokeStatic(query_processor.clj:76)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_resolved_database$fn__67153.invoke(setup.clj:128)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_metadata_provider$fn__67159.invoke(setup.clj:150)"
2024-09-18 11:20:21.264	
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
2024-09-18 11:20:21.264	
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:159)"
2024-09-18 11:20:21.264	
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
2024-09-18 11:20:21.264	
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:170)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_metadata_provider$fn__67159$fn__67162.invoke(setup.clj:151)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_driver$fn__67166.invoke(setup.clj:165)"
2024-09-18 11:20:21.264	
  "driver$do_with_driver.invoke(driver.clj:99)"
2024-09-18 11:20:21.264	
  "driver$do_with_driver.invokeStatic(driver.clj:104)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_driver$fn__67166$fn__67167.invoke(setup.clj:166)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_database_local_settings$fn__67171.invoke(setup.clj:181)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_canceled_chan$fn__67176.invoke(setup.clj:187)"
2024-09-18 11:20:21.264	
  "query_processor$process_query$fn__76850.invoke(query_processor.clj:78)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__76813.invoke(catch_exceptions.clj:128)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__76744.invoke(process_userland_query.clj:198)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__66772.invoke(enterprise.clj:103)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.enterprise$fn__66761$handle_audit_app_internal_queries__66762$fn__66764.invoke(enterprise.clj:96)"
2024-09-18 11:20:21.264	
  "query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43)"
2024-09-18 11:20:21.264	
  "query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)"
2024-09-18 11:20:21.264	
  "query_processor.execute$execute.invoke(execute.clj:87)"
2024-09-18 11:20:21.264	
  "query_processor.execute$execute.invokeStatic(execute.clj:91)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)"
2024-09-18 11:20:21.264	
  "query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225)"
2024-09-18 11:20:21.264	
  "query_processor.execute$execute$fn__71555.invoke(execute.clj:92)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__66744.invoke(enterprise.clj:64)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__66734.invoke(enterprise.clj:51)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.permissions$check_query_permissions$fn__66122.invoke(permissions.clj:147)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___71481.invoke(cache.clj:238)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:185)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:212)"
2024-09-18 11:20:21.264	
  "query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__71528.invoke(execute.clj:34)"
2024-09-18 11:20:21.264	
  "query_processor.execute$add_native_form_to_result_metadata$fn__71523.invoke(execute.clj:23)"
2024-09-18 11:20:21.264	
  "query_processor.middleware.update_used_cards$update_used_cards_BANG_$fn__71508.invoke(update_used_cards.clj:60)"
2024-09-18 11:20:21.264	
  "query_processor.execute$run.invoke(execute.clj:54)"
2024-09-18 11:20:21.264	
  "query_processor.execute$run.invokeStatic(execute.clj:60)"
2024-09-18 11:20:21.264	
  "query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)"
2024-09-18 11:20:21.264	
  "query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)"
2024-09-18 11:20:21.264	
  "query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)"
2024-09-18 11:20:21.264	
  "query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)"
2024-09-18 11:20:21.264	
  "driver.bigquery_cloud_sdk$fn__130633.invoke(bigquery_cloud_sdk.clj:537)"
2024-09-18 11:20:21.264	
  "driver.bigquery_cloud_sdk$fn__130633.invokeStatic(bigquery_cloud_sdk.clj:545)"
2024-09-18 11:20:21.264	
  "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_.invoke(bigquery_cloud_sdk.clj:506)"
2024-09-18 11:20:21.264	
  "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:529)"
2024-09-18 11:20:21.264	
  "driver.bigquery_cloud_sdk$_STAR_process_native_STAR_$thunk__130626.invoke(bigquery_cloud_sdk.clj:516)"
2024-09-18 11:20:21.264	
  "driver.bigquery_cloud_sdk$post_process_native.invoke(bigquery_cloud_sdk.clj:483)"
2024-09-18 11:20:21.264	
 ["--> driver.bigquery_cloud_sdk$post_process_native.invokeStatic(bigquery_cloud_sdk.clj:490)"
2024-09-18 11:20:21.264	
 :stacktrace
2024-09-18 11:20:21.264	
 :class java.lang.NullPointerException,
2024-09-18 11:20:21.264	
 :status :failed,
2024-09-18 11:20:21.264	
    :target ["dimension" ["template-tag" "do_not_show_if_flag_set"]]}]},
2024-09-18 11:20:21.264	
    :value nil,
2024-09-18 11:20:21.264	
    :type "string/=",
2024-09-18 11:20:21.264	
   {:id "533f8232-d909-44cc-99e5-fe21289ca6f7",
2024-09-18 11:20:21.264	
    :target ["dimension" ["template-tag" "only_show_if_flag_set"]]}
2024-09-18 11:20:21.264	
    :value nil,
2024-09-18 11:20:21.264	
    :type "string/=",
2024-09-18 11:20:21.264	
   {:id "b7fa68c9-e7c4-4867-a40e-9eb51bb8efbc",
2024-09-18 11:20:21.264	
    :target ["dimension" ["template-tag" "stages_to_hide"]]}
2024-09-18 11:20:21.264	
    :value nil,
2024-09-18 11:20:21.264	
    :type "string/=",
2024-09-18 11:20:21.264	
   {:id "03a87557-989b-4a7a-aa80-472778dfae4e",
2024-09-18 11:20:21.264	
    :target ["dimension" ["template-tag" "flag_with_underscores"]]}
2024-09-18 11:20:21.264	
    :value ["plan_page_hide_slot_booker_for_new_users_with_no_connection"],
2024-09-18 11:20:21.264	
    :type "string/=",
2024-09-18 11:20:21.264	
   {:id "84e7a90e-0c58-4b7a-bf63-d04470b67035",
2024-09-18 11:20:21.264	
    :target ["variable" ["template-tag" "after"]]}
2024-09-18 11:20:21.264	
    :value "2024-09-02",
2024-09-18 11:20:21.264	
    :type "date/single",
2024-09-18 11:20:21.264	
  [{:id "5d575d6f-4489-492b-9d42-72ce63e548e4",
2024-09-18 11:20:21.264	
  :parameters
2024-09-18 11:20:21.264	
  :database 2,
2024-09-18 11:20:21.264	
   :stackable.stack_type nil},
2024-09-18 11:20:21.264	
   :graph.dimensions ["stage" "test_group"],
2024-09-18 11:20:21.264	
    :cash_per_user {:color "#689636"}},
2024-09-18 11:20:21.264	
    :arpu {:color "#88BF4D"},
2024-09-18 11:20:21.264	
    :trial_cancelled {:color "#EF8C8C"},
2024-09-18 11:20:21.264	
    :trial_started {:color "#88BF4D"},
2024-09-18 11:20:21.264	
   {:monthly_arpu {:color "#88BF4D"},
2024-09-18 11:20:21.264	
   :series_settings
2024-09-18 11:20:21.264	
    "[\"name\",\"cash_per_user\"]" {:number_style "currency"}},
2024-09-18 11:20:21.264	
    "[\"name\",\"monthly_arpu\"]" {:number_style "currency"},
2024-09-18 11:20:21.264	
    "[\"name\",\"arpu\"]" {:number_style "currency"},
2024-09-18 11:20:21.264	
    "[\"name\",\"revenue\"]" {:number_style "currency"},
2024-09-18 11:20:21.264	
   {"[\"name\",\"percentage\"]" {:number_style "percent"},
2024-09-18 11:20:21.264	
   :column_settings
2024-09-18 11:20:21.264	
   :table.pivot_column "variation",
2024-09-18 11:20:21.264	
   :graph.series_order nil,
2024-09-18 11:20:21.264	
   :graph.metrics ["percentage"],
2024-09-18 11:20:21.264	
   :graph.series_order_dimension nil,
2024-09-18 11:20:21.264	
   :table.cell_column "users",
2024-09-18 11:20:21.264	
  {:graph.show_values true,
2024-09-18 11:20:21.264	
  :viz-settings
2024-09-18 11:20:21.264	
<redacted>
2024-09-18 11:20:21.264	
   :query
2024-09-18 11:20:21.264	
     :widget-type :string/=}},
2024-09-18 11:20:21.264	
     :dimension [:field 124503 nil],
2024-09-18 11:20:21.264	
     :display-name "Do Not Show If Flag Set",
2024-09-18 11:20:21.264	
     :id "533f8232-d909-44cc-99e5-fe21289ca6f7",
2024-09-18 11:20:21.264	
     :name "do_not_show_if_flag_set",
2024-09-18 11:20:21.264	
    {:type :dimension,
2024-09-18 11:20:21.264	
    "do_not_show_if_flag_set"
2024-09-18 11:20:21.264	
     :options nil},
2024-09-18 11:20:21.264	
     :widget-type :string/=,
2024-09-18 11:20:21.264	
     :dimension [:field 124503 nil],
2024-09-18 11:20:21.264	
     :default nil,
2024-09-18 11:20:21.264	
     :display-name "Only Show If Flag Set",
2024-09-18 11:20:21.264	
     :id "b7fa68c9-e7c4-4867-a40e-9eb51bb8efbc",
2024-09-18 11:20:21.264	
     :name "only_show_if_flag_set",
2024-09-18 11:20:21.264	
    {:type :dimension,
2024-09-18 11:20:21.264	
    "only_show_if_flag_set"
2024-09-18 11:20:21.264	
     :widget-type :string/=},
2024-09-18 11:20:21.264	
     :dimension [:field 115709 nil],
2024-09-18 11:20:21.264	
     :display-name "Stages To Hide",
2024-09-18 11:20:21.264	
     :id "03a87557-989b-4a7a-aa80-472778dfae4e",
2024-09-18 11:20:21.264	
     :name "stages_to_hide",
2024-09-18 11:20:21.264	
    {:type :dimension,
2024-09-18 11:20:21.264	
    "stages_to_hide"
2024-09-18 11:20:21.264	
     :widget-type :string/=},
2024-09-18 11:20:21.264	
     :dimension [:field 124503 nil],
2024-09-18 11:20:21.264	
     :default nil,
2024-09-18 11:20:21.264	
     :display-name "Flag (with underscores)",
2024-09-18 11:20:21.264	
     :id "84e7a90e-0c58-4b7a-bf63-d04470b67035",
2024-09-18 11:20:21.264	
     :name "flag_with_underscores",
2024-09-18 11:20:21.264	
    {:type :dimension,
2024-09-18 11:20:21.264	
    "flag_with_underscores"
2024-09-18 11:20:21.264	
     :widget-type nil},
2024-09-18 11:20:21.264	
     :default nil,
2024-09-18 11:20:21.264	
     :display-name "After",
2024-09-18 11:20:21.264	
     :id "5d575d6f-4489-492b-9d42-72ce63e548e4",
2024-09-18 11:20:21.264	
     :name "after",
2024-09-18 11:20:21.264	
    {:type :date,
2024-09-18 11:20:21.264	
   {"after"
2024-09-18 11:20:21.264	
  {:template-tags
2024-09-18 11:20:21.264	
  :native
2024-09-18 11:20:21.264	
  :cache-strategy {:multiplier 20, :min_duration_ms 1, :type :ttl, :avg-execution-ms 639109},
2024-09-18 11:20:21.264	
  {:js-int-to-string? true, :ignore-cached-results? true, :process-viz-settings? false, :userland-query? true},
2024-09-18 11:20:21.264	
  :middleware
2024-09-18 11:20:21.264	
  :type :native,
2024-09-18 11:20:21.264	
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
2024-09-18 11:20:21.264	
 :json_query
2024-09-18 11:20:21.264	
 :action_id nil,
2024-09-18 11:20:21.264	
 :started_at #t "2024-09-18T11:16:10.188873Z[GMT]",
2024-09-18 11:20:21.264	
{:database_id 2,
2024-09-18 11:20:21.264	
2024-09-18 11:20:21,263 ERROR middleware.catch-exceptions :: Error processing query: Error running query
```

### Information about your Metabase installation

```JSON
v50.25.x
```

### Severity

P1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snoe**
Fixes #47990

Inline some function calls to make it easier to track what's happening.

Make sure that cancellation during the initial query and subsequent page fetches are handled properly. Explicitly throw when cancelled.

Only retry queries if bigquery says they are retryable.

Try to cancel the BigQuery job if an exception or cancellation occurs.

### CODE REVIEW

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 1]
```diff
@@ -609,27 +600,20 @@
...
+                 sql
+                 parameters
+                 cancel-chan))]
     (try
       (thunk)
       (catch Throwable e
         (let [ex-data (u/all-ex-data e)]
-          (if (and (not (::cancelled? ex-data))
-                   (or (:retryable? ex-data) (not (qp.error-type/client-error? (:type ex-data)))))
+          (if (:retryable? ex-data)
```
Comment (snoe) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:613]: This would retry random exceptions and cause loops, we only care to retry if bigquery says we should

File: modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj [hunk 2]
```diff
@@ -479,6 +433,30 @@
...
+;;;     - Sets timezone based on queried DB
+;;;     - Adds remarks to sql.
+;;;     - Execution passes to `*process-native*`
+;;; 2. `*process-native*`
+;;;     - Responsible for retrying queries that BigQuery tells us to retry
+;;;     - Execution passes to `execute-bigquery`
+;;; 3. `execute-bigquery`
+;;;     - Makes the initial query and checks `cancel-chan` in case the browser cancels execution.
+;;;     - Either throws approriate exceptions or takes the initial page `TableResult` to the next step.
+;;;     - Execution passes to `execute-bigquery`
```
Comment (metamben) [inline modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj:448]:
```suggestion
;;;     - Execution passes to `bigquery-execute-response`
```

**Review by metamben — APPROVED** [review]
LGTM
