### PR TITLE
[PivotTable] Improve scrolling performance

### LINKED ISSUE #14607: Scrolling in Firefox is difficult using the scrollbar
**Describe the bug**
Scrolling in Firefox is difficult using the scrollbar

**To Reproduce**
Specially in Pivot Table:
screencast-2021-02-01_15 25 38

**Expected behavior**
Same behavior as Chrome

**Information about your Metabase Installation:**
Tested 0.38.0-rc4

**Additional context**
Likely very related to #13773. And to #10339

### PR DESCRIPTION
**Pull request by uladzimirdev**
Closes https://github.com/metabase/metabase/issues/14607

### Description

I wasn't able to reproduce the initial problem with older and new versions of the metabase (tried 0.39.5, 0.40.8, 0.45, 0.46, 0.46.5), but overall experience with PivotTable wasn't great during scrolling. I found there were added optimizations from @iethree (probably), but even virtualized table required calculating if cell has content which should be ellipsified together with tooltip rendering for _every cell_. 
Initial idea to skip rendering of the tooltip if text content doesn't overflow allocated space didn't work out because of the way we calculate if element overflows or not. 
But at least during scrolling we don't need to render tooltip and calculate text overflow - so I optimized that part and seems results are not that bad.

### How to verify

Create a question from Orders based on following configuration
image
Choose `Pivot Table` visualization, save the question.

To get a more clear results, open devtools -> performance tab -> choose throttle CPU by 6 times. Now scroll by dragging scroll

### Demo

https://www.loom.com/share/36541f957bfb47d582d56f666cbee180

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTableCell.tsx [hunk 1]
```diff
@@ -59,6 +60,7 @@ export function Cell({
   hasTopBorder,
   onClick,
   onResize,
+  isScrolling = false,
```
Comment (kamilmielnik) [inline frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTableCell.tsx:63]: `Cell` and `BodyCell` are rather "dumb" UI components therefore I think they don't need to know _why_ the tooltip is disabled. All they need to know is whether the tooltip is disabled. So I'd call this property `disabledTooltip` or `showTooltip` or something like that.

**Review by kamilmielnik — APPROVED** [review]
> I wasn't able to reproduce the initial problem with older and new versions of the metabase (tried 0.39.5, 0.40.8, 0.45, 0.46, 0.46.5),

Did you try old Firefox though?
Perhaps this was a browser issue that got fixed over the last 2 years.

I can't reproduce it with modern browsers.

> Closes #14607

If it was an issue with old Firefox, then I would not say this PR closes #14607.

> But at least during scrolling we don't need to render tooltip

Just for the record: I would not agree with that statement in general case.
There are multiple ways to trigger a tooltip (mouse hover, tab on keyboard) and there are multiple ways to scroll (arrow keys, page up/down, mouse, touchpad).

So for example, if I select a button with <kbd>Tab</kbd> I expect its tooltip to be shown.
And then, if I press arrow down to scroll, I expect the button to still be selected and tooltip still to be shown.

I'm kind of nit-picking here, but in general case this is breaking a11y in a way.
It does not seem to be a concern with `PivotTable` at this time though, so all good :+1: 

> so I optimized that part and seems results are not that bad.

Oh yes, scrolling is definitely smoother now :+1: :100:

**Comment by uladzimirdev** [comment]
Thanks for the valuable feedback @kamilmielnik 🙇 

> Did you try old Firefox though?

nope, we support 2 latest versions of firefox. I know old versions of firefox had problems with calculating flexbox elements, so rendering could be slower

> If it was an issue with old Firefox, then I would not say this PR closes https://github.com/metabase/metabase/issues/14607.

you're right, at the same time there is no any reason to keep this issue open as it's not relevant anymore (ever green browsers get updates, we do not support old browsers)

> Just for the record: I would not agree with that statement in general case.
There are multiple ways to trigger a tooltip (mouse hover, tab on keyboard) and there are multiple ways to scroll (arrow keys, page up/down, mouse, touchpad).

> So for example, if I select a button with Tab I expect its tooltip to be shown.
And then, if I press arrow down to scroll, I expect the button to still be selected and tooltip still to be shown.

Actually I agree with you here. Specifically talking about PivotTable or any table which is rendered using divs, accessibility is broken by default - you have to provide tabIndex to select a div, currently we do not support even nagivating through cells using keyboard. 

perhaps regarding scrolling and focused mode you're right, if element is not in focus like we have in PivotTable, mouse will not be over the cell anyway during scrolling, so we can skip showing it
