### PR TITLE
User friendly error message when combining series that cannot be visualized together

### LINKED ISSUE #32231: Cannot read properties of undefined (reading 'name') when adding an incomplete card
### Describe the bug

Spin off of https://github.com/metabase/metabase/issues/32230

If you combine 2 cards:
1) a barchart (e.g. count of all people group by birth_date)
2) an incomplete bar char (e.g. sql question of select 1, saved as a bar chart)

you'll get a frontend error
image

### To Reproduce

Above

### Expected behavior

We should return what's the offending card?

### Logs

_No response_

### Information about your Metabase installation

```JSON
v47.x but guessing this comes from way before
```

### Severity

P3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes #32231

### Description

- See explanation for this in Slack: https://metaboat.slack.com/archives/C057T1QTB3L/p1691587662019079?thread_ts=1691585903.901969&cid=C057T1QTB3L
- I was not able to reproduce `"TypeError: Cannot read properties of undefined (reading 'name')"` in jest, so I went with an e2e test for it.

#### Before

image

#### After

image

### How to verify

Follow reproduction steps from original report.

### CODE REVIEW

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx [hunk 1]
```diff
@@ -144,6 +145,9 @@ export class AddSeriesModal extends Component<Props, State> {
             <Visualization
               canRemoveSeries={CAN_REMOVE_SERIES}
               className="spread"
+              errorView={
```
Comment (ranquild) [inline frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx:148]: Can we instead of overriding the component pass the message itself, e.g. e.g. `error={t`Unable to combine these questions`}`?

File: e2e/test/scenarios/dashboard-cards/reproductions/32231-add-incompatible-series.cy.spec.js [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+
+        visitDashboard(dashboard_id);
+      },
+    );
+
+    cy.icon("pencil").click();
+    cy.findByTestId("add-series-button").click({ force: true });
+    cy.wait("@seriesQuery");
+
+    cy.get(".AddSeriesModal").within(() => {
```
[the remark this answers is not in the document]
Comment (kamilmielnik) [reply e2e/test/scenarios/dashboard-cards/reproductions/32231-add-incompatible-series.cy.spec.js]: `modal()` does not work here. Added custom `data-testid`: c9b4a8c930ee0f0f5b1ce40ea4374f3c1c2d443f

File: e2e/test/scenarios/dashboard-cards/reproductions/32231-add-incompatible-series.cy.spec.js [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+              size_y: 10,
+            },
+          ],
+        });
+
+        visitDashboard(dashboard_id);
+      },
+    );
+
+    cy.icon("pencil").click();
```
[the remark this answers is not in the document]
Comment (kamilmielnik) [reply e2e/test/scenarios/dashboard-cards/reproductions/32231-add-incompatible-series.cy.spec.js]: 9d81241b72ca5bba0e50ed29ed5dbfd9043c02e6

File: frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx (hunk 1 above)
Comment (kamilmielnik) [reply frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx]: 20b605a9a86b62268645991776f276fca15bf070

Comment (kamilmielnik) [reply frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx]: Refactored `errorView` prop to `errorMessageOverride`: 20b605a9a86b62268645991776f276fca15bf070

File: frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx [hunk 4]
```diff
@@ -476,7 +478,7 @@ class Visualization extends PureComponent {
             <NoResultsView isSmall={small} />
           ) : error ? (
             <ErrorView
-              error={error}
+              error={errorMessageOverride ?? error}
```
Comment (ranquild) [inline frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx:481]: Why do we need this? It seems that `error` coming from `props` has precedence anyway: `let error = this.props.error || this.state.error;`

Comment (kamilmielnik) [reply frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx:481]: Unfortunately that `let error = this.props.error || this.state.error;` is used to determine whether the error state should be displayed or not.

The parent component does not know whether `Visualization` rendering failed and error state should be displayed in it.

In other words: if we used `error` prop instead of `errorMessageOverride`, the error would be always displayed.

Comment (ranquild) [reply frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx:481]: Got it, makes sense, thanks!

**Review by ranquild — APPROVED** [review]
