### PR TITLE
BE - Handle existing actions when database-enable-actions setting is disabled

### LINKED ISSUE #27751: BE - Handle existing actions when database-enable-actions setting is disabled
FE issue: https://github.com/metabase/metabase/issues/28132

We need to handle the case when actions already exist and the database-enable-actions setting is then disabled for the database that powers the action / model. There are two things we should do to handle this:

- [ ] Make the action un-executable and un-editable but leave them visible
- [ ] Return an error message so users of the API know why it failed “Running/Executing Actions is not enabled for database <db_name>”

Context:
1. https://metaboat.slack.com/archives/C04DAKFDTCZ/p1674053644841749
2. https://metaboat.slack.com/archives/C04FG88HL95/p1675786352115169

### PR DESCRIPTION
**Pull request by calherries**
Resolves https://github.com/metabase/metabase/issues/27751

Here's a list of all the endpoints under the "api/action" path, and whether they've been updated:
- GET "/": no change, this should return actions even if setting is disabled
- GET "/:action-id": no change, this should return actions even if setting is disabled
- DELETE "/:action-id": no change, this should allow actions to be deleted even if setting is disabled
- POST "/": updated, was missing checks on implicit and http actions before (see [comment](https://github.com/metabase/metabase/pull/27900/files#r1101694001))
- PUT "/:id": updated
- POST "/:id/public_link": updated
- DELETE "/:id/public_link": updated

One more endpoint was updated in the "api/public" path:
- GET "api/public/:action-uuid"

- - -
This change is [Reviewable](https://reviewable.io/reviews/metabase/metabase/28153)

### CODE REVIEW

File: src/metabase/actions.clj [hunk 1]
```diff
@@ -114,9 +115,10 @@
           (swap! *misc-value-cache* assoc unique-key value))
         value)))
 
-(defn check-actions-enabled!
-  "Throws an appropriate error if actions are unsupported or disabled, otherwise returns nil."
+(defn check-actions-enabled-for-database!
+  "Throws an appropriate error if actions are unsupported or disabled for a database, otherwise returns nil."
   [{db-settings :settings db-id :id driver :engine db-name :name :as db}]
+  (tap> db)
```
Comment (qnkhuat) [inline src/metabase/actions.clj:121]: 🧹

File: src/metabase/actions.clj [hunk 2]
```diff
@@ -130,6 +132,21 @@
 
   nil)
 
+(defn database-for-action [action-or-id]
+  (toucan.models/do-post-select
```
Comment (qnkhuat) [inline src/metabase/actions.clj:136]: from @camsaul .

> There is no need to manually do-post-select or anything like that ever again, all that stuff is done with transducers now under the hood and is applied regardless of the query. You can even do (t2/select User ["SELECT * FROM user"]) and it will still do the post-select stuff on the results. Neat.

we will probably have a way to go around this without manually call `do-post-select` here

File: src/metabase/actions.clj [hunk 3]
```diff
@@ -130,6 +132,21 @@
 
   nil)
 
+(defn database-for-action [action-or-id]
```
Comment (qnkhuat) [inline src/metabase/actions.clj:135]: make it private?

File: src/metabase/actions.clj [hunk 4]
```diff
@@ -130,6 +132,21 @@
...
+   (first (db/query {:select [:db.*]
+                     :from   :action
+                     :join   [[:report_card :card] [:= :card.id :action.model_id]
+                              [:metabase_database :db] [:= :db.id :card.database_id]]
+                     :where  [:= :action.id (u/the-id action-or-id)]}))))
+
+(defn check-actions-enabled!
+  "Throws an appropriate error if actions are unsupported or disabled for the database of the action's model,
+   otherwise returns nil."
+  ([action-or-id]
```
Comment (qnkhuat) [inline src/metabase/actions.clj:147]: this doesn't look like it needs multi-arity?

File: src/metabase/actions/execution.clj [hunk 5]
```diff
@@ -80,7 +78,7 @@
                          :type                   qp.error-type/invalid-parameter
                          :parameters             request-parameters
                          :destination-parameters (:parameters action)}))))
-    (actions/check-actions-enabled! database)
+    (actions/check-actions-enabled-for-database! action)
```
Comment (qnkhuat) [inline src/metabase/actions/execution.clj:81]: why is it taking an action, but not `database`?

File: src/metabase/api/action.clj [hunk 6]
```diff
@@ -89,15 +89,13 @@
...
-
-  (api/write-check Card model_id)
   (when (and (nil? database_id)
              (= "query" type))
     (throw (ex-info (tru "Must provide a database_id for query actions")
                     {:type        type
                      :status-code 400})))
-  (when database_id
-    (actions/check-actions-enabled! (db/select-one Database :id database_id)))
+  (let [model (api/write-check Card model_id)]
```
Comment (qnkhuat) [inline src/metabase/api/action.clj:97]: any reason why this is better than having `(api/write-check Card model_id)` at top?

IMO write check should be the 1st thing to do.

File: src/metabase/actions/execution.clj (hunk 5 above)
Comment (calherries) [reply src/metabase/actions/execution.clj:81]: It's an optimization. It does the some thing as before but now with only one DB query, and it's all wrapped up in `actions/check-actions-enabled!`.

File: src/metabase/api/action.clj (hunk 6 above)
Comment (calherries) [reply src/metabase/api/action.clj:97]: I thought schema validation is generally first. And the check for a non-nil database_id is part of that

File: src/metabase/actions.clj (hunk 2 above)
Comment (calherries) [reply src/metabase/actions.clj]: Good point, I tried using toucan 2 for this. But if I'm using `t2/query-one`, it looks like I need to grab the current connection. It's a bit more work than I expected, so I wonder if @camsaul can advise on a more concise approach? https://github.com/metabase/metabase/pull/28153/commits/b9a3dcee7a0b65bda242a0c72b956e200325dc7c

Comment (camsaul) [reply src/metabase/actions.clj]: Pretty sure you want select-one here, not query-one. Either way if you pass nil as the connection to query-one it will use the default connection

**Review by qnkhuat — APPROVED** [review]
I think you want to change `t2/query-one` to `t2/select-one` as Cam advised.

otherwise this LGTM. I disabled auto-merge so it doesn't merge right after I approved.

**Comment by ranquild** [comment]
@calherries we also need to modify public actions endpoints

**Comment by calherries** [comment]
@ranquild Yes this PR updates the `GET "api/public/:action-uuid"` endpoint to check the setting, I had just left it out of the description. I've updated the description now, thanks for catching

File: src/metabase/actions.clj (hunk 2 above)
Comment (calherries) [reply src/metabase/actions.clj]: Updated to use `select-one`, thanks https://github.com/metabase/metabase/pull/28153/commits/4d586ab945c6d4bd392afcc143c94a66d91004f2
