### PR TITLE
Fix drilling through FKs outside of 2000 rows limit

### LINKED ISSUE #21756: View Detail on Foreign Key does not work when targeting an item outside the first 2000 rows
**Describe the bug**
When clicking "view detail" on a foreign key - if it is not in the first 2000 rows of the table, it will give the user a not found message.

Because of the nature of the bug, I don't think it's reproducible with the sample DB.

**Logs**

(nothing material)

**To Reproduce**
1. Go to a table with more than 2000 foreign keys defined
2. Click on a foreign key (that's not in the first 2000 rows of the table) and select "View Details"
3. Instead of seeing the object's details, you will get a "we're a little lost" error

**Expected behavior**
The user should see the detail view of the object selected

**Screenshots**

https://user-images.githubusercontent.com/30528226/164040471-68409750-8641-4d3e-b452-65741ce339f0.mp4

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Google Chrome Version 100.0.4896.127 (Official Build) (64-bit) 
- Your operating system: Ubutntu 20.04
- Your databases: Postgres 14.2
- Metabase version: master branch - 2022-04-19 - v0.42.1-SNAPSHOT"
- Metabase hosting environment: local development
- Metabase internal database: H2

**Severity**

Makes foreign-key object detail view useless for most large tables.

### PR DESCRIPTION
**Pull request by kulyk**
Reproduces #21756, fixes #21756

#20101 introduced a new mechanism for PK and FK drills. This PR fixes a regression caused by this change: when trying to open an object detail from a foreign table that is out of the first 2000 foreign table rows, you'll see a "not found" message. The simplest way to reproduce is to open an orders table, sort the "User ID" column desc and try to open a user record with an ID > 2000.

The PR reverts the drilling behavior for FKs. So when you open an object detail in a foreign table, Metabase will create a query to another table with an ID filter. So if we're drilling to "User ID = 2500", Metabase will query `select * from people where ID = 2500`, which guarantees that we'll always have the result as long as it's present in the DB itself. The PR also removes the prev and next buttons for drilled FKs.

### To Verify

1. New > Question > Sample Database > Orders
2. Click the "User ID" column and set the sorting to desc
3. Click a "User ID" cell with ID 2500
4. Ensure you can see the user record details, ensure the data is correct
5. Ensure there are now "previous" and "next" buttons
6. Ensure PK drills work normally

### Demo

**Before**

https://user-images.githubusercontent.com/17258145/165724956-5def4478-9692-4d08-b366-3e71c354b48c.mp4

**After**

https://user-images.githubusercontent.com/17258145/165724981-5bfd4690-3d2a-4e80-bfee-d19b7193f05f.mp4

### CODE REVIEW

File: frontend/src/metabase/modes/components/drill/ObjectDetailDrill.jsx [hunk 1]
```diff
@@ -74,16 +49,11 @@ function getPKAction({ question, column, objectId, isDashboard }) {
...
+  if (!fkField?.target) {
     return;
   }
-  const [actionKey, action] = getActionForFKColumn({
-    field: targetField,
-    objectId,
-  });
-
-  actionObject[actionKey] = action;
+  actionObject.question = () => question.drillPK(fkField.target, objectId);
```
Comment (kulyk) [inline frontend/src/metabase/modes/components/drill/ObjectDetailDrill.jsx:56]: We used to use this approach before #20101 (see [code](https://github.com/metabase/metabase/blob/8f119d6457f70827a40b105a60218d855a030969/frontend/src/metabase/modes/components/drill/ObjectDetailDrill.jsx#L31)), so I suppose it would match the previous behaviour better

File: frontend/src/metabase/query_builder/actions.js [hunk 2]
```diff
@@ -1554,10 +1554,14 @@ export const loadObjectDetailFKReferences = createThunkAction(
       dispatch.action(CLEAR_OBJECT_DETAIL_FK_REFERENCES);
 
       const state = getState();
+      const tableForeignKeys = getTableForeignKeys(state);
+
+      if (!Array.isArray(tableForeignKeys)) {
+        return null;
+      }
```
Comment (kulyk) [inline frontend/src/metabase/query_builder/actions.js:1561]: Just a safety-check, we should be able to leave it when backporting to `master` as the `ObjectDetail` component changes are not going to the 43 release

**Review by ranquild — APPROVED** [review]

File: frontend/src/metabase/query_builder/actions.js [hunk 3]
```diff
@@ -1523,50 +1523,55 @@ function getFilterForFK(zoomedObjectId, fk) {
...
 
-    dispatch(resetRowZoom());
-    dispatch(setCardAndRun(newCard));
-  };
-});
+      dispatch(resetRowZoom());
+      dispatch(setCardAndRun(newCard));
+    };
+  },
+);
```
Comment (kulyk) [inline frontend/src/metabase/query_builder/actions.js:1548]: All the diff here is caused by adding an explicit `objectId` argument to `followForeignKey`. It used to select `zoomedObjectId` from redux, but it's not going to be there now if we're drilling by FKs. So now both `followForeignKey` and `loadObjectDetailFKReferences` will expect an explicit `objectId` as an argument

**Review by ranquild — APPROVED** [review]

**Review by flamber — APPROVED** [review]
I'm still seeing some problems, but it's better now than before.

https://user-images.githubusercontent.com/1447303/165739559-c44eadf0-9677-4094-9e4d-b3cb91618229.mp4

**Comment by kulyk** [comment]
> I'm still seeing some problems, but it's better now than before.
> 
>  Screencast-2022-04-28_13.06.19.mp4

@flamber #22190 should fix the problem on the video
