### PR TITLE
[QP] Correctly handle `:lib/internal-remap` columns in `:result_metadata`

### LINKED ISSUE #45938: Model breaks with "column source.ID does not exist"
### Describe the bug

Older models in 50.x (at least 50.6 models in 50.8; probably earlier ones really) can result in this error.

It seems to be a change somewhere in how columns and refs are handled with models, causing us to generate a SQL that `SELECT`s a column that the inner query doesn't provide.

More context in [this slack thread](https://metaboat.slack.com/archives/C01LQQ2UW03/p1721654026800009).

### To Reproduce

See the [broken original model](https://metabase-public.metabaseapp.com/model/1382-euro-2024-player-stats) or the (nearly) working [duplicate](https://metabase-public.metabaseapp.com/model/1519-euro-2024-player-stats-duplicate).

### Expected behavior

The original model should still be working fine.

### Information about your Metabase installation

```JSON
* Version v1.50.8 (after upgrading from v1.50.6)
```

### PR DESCRIPTION
**Pull request by bshepherdson**
Fixes #45938.

### Description

Remapping is handled at the top level of the query, and should be
ignored for inner queries. This PR hides it from `results_metadata` on
source queries.

It also fixes the interaction with `large-int-id` logic to make big
integers JS-safe.

### How to verify

1. Set up an ID column with an **internal** remap
    - (Remapping based on a fixed drop-down list, not another column.)
2. Create a model which **joins** in that column and does a breakout on it.
3. Consume that model from a question

Before this change, it will error with the message in #45938. With this change, it will remap correctly.
I also fixed a tangential issue with the `large-int-id` and internal remapping.

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

**Comment by bshepherdson** [comment]
* **#47587** <a href="https://app.graphite.dev/github/pr/metabase/metabase/47587?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bshepherdson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: src/metabase/query_processor/middleware/add_dimension_projections.clj [hunk 1]
```diff
@@ -431,11 +437,12 @@
...
     :as                                                    col} :- ColumnMetadataWithOptionalBaseType]
   (when (seq values)
-    (let [remap-from (:name col)]
+    (let [remap-from       (:name col)
+          stringified-idxs (qp.store/miscellaneous-value [::large-int-id/field-indexes])]
       {:col-index       idx
        :from            remap-from
        :to              remap-to
-       :value->readable (zipmap (transform-values-for-col col values)
+       :value->readable (zipmap (transform-values-for-col col values (and stringified-idxs (stringified-idxs idx)))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/add_dimension_projections.clj:445]:
```suggestion
       :value->readable (zipmap (transform-values-for-col col values (get stringified-idxs idx))
```

File: src/metabase/query_processor/middleware/large_int_id.clj [hunk 2]
```diff
@@ -15,28 +15,33 @@
...
-                         (lib.metadata.protocols/field (qp.store/metadata-provider) field-id))]
-        (when (should-convert-to-string? field)
-          idx)))
-    fields)))
+  PKs and FKs which are numbers need converting, lest they lose precision. JS numbers only guarantee 52 bits."
+  [{:keys [base-type semantic-type] :as _column-metadata}]
+  (and (or (isa? semantic-type :type/PK)
+           (isa? semantic-type :type/FK))
+       (or (isa? base-type     :type/Integer)
+           (isa? base-type     :type/Number))))
```
Comment (metamben) [inline src/metabase/query_processor/middleware/large_int_id.clj:26]: Isn't this equivalent to
```suggestion
       (isa? base-type :type/Number)))
```

File: src/metabase/query_processor/middleware/large_int_id.clj [hunk 3]
```diff
@@ -15,28 +15,33 @@
...
+     (keep-indexed
+      (fn [idx val]
+          ;; TODO -- we could probably fix the rest of #5816 by adding support for
+          ;; `:field` w/ name and removing the PK/FK requirements -- might break
+          ;; the FE client tho.
+        (when-let [field (lib.util.match/match-one val
+                           [:field (field-id :guard integer?) _]
+                                                     ;; TODO -- can't we use the QP store here? Seems like
+                                                     ;; we should be able to, but it doesn't work (not
+                                                                                                    ;; initialized)
```
Comment (metamben) [inline src/metabase/query_processor/middleware/large_int_id.clj:40]: Strange indentation.

File: test/metabase/query_processor/middleware/add_dimension_projections_test.clj [hunk 4]
```diff
@@ -521,19 +534,20 @@
...
-                                             ["Another store" (cast-fn 24)]]))))))))
+      (qp.store/with-metadata-provider meta/metadata-provider
+        (testing (format "Base type = %s; IDs in result rows are %s" base-type (class (cast-fn 1)))
+          (let [info (#'qp.add-dimension-projections/col->dim-map
+                      1
+                      (assoc (meta/field-metadata :venues :category-id)
+                             :base-type          base-type
+                             :effective-type     base-type
+                             :lib/internal-remap {:lib/type              :metadata.column.remapping/internal
+                                                  :id                    1
```
Comment (appleby) [inline test/metabase/query_processor/middleware/add_dimension_projections_test.clj:545]: Does comment from schema above about nil ids for internal remaps not apply here?

**Review by appleby — APPROVED** [review]
LGTM

File: src/metabase/query_processor/middleware/large_int_id.clj [hunk 5]
```diff
@@ -15,28 +15,33 @@
...
-          idx)))
-    fields)))
+  PKs and FKs which are numbers need converting, lest they lose precision. JS numbers only guarantee 52 bits."
+  [{:keys [base-type semantic-type] :as _column-metadata}]
+  (and (or (isa? semantic-type :type/PK)
+           (isa? semantic-type :type/FK))
+       (or (isa? base-type     :type/Integer)
+           (isa? base-type     :type/Number))))
+
+(defn- field-indexes [query]
```
Comment (metamben) [inline src/metabase/query_processor/middleware/large_int_id.clj:28]: Even in this namespace, I think this name is too general. (I understand this is not new in this PR.)

**Review by metamben — APPROVED** [review]
LGTM

File: src/metabase/query_processor/middleware/large_int_id.clj (hunk 2 above)
Comment (bshepherdson) [reply src/metabase/query_processor/middleware/large_int_id.clj:27]: Probably, but I'm not inclined to mess with the `:type/*` hierarchy.

File: src/metabase/query_processor/middleware/large_int_id.clj (hunk 5 above)
Comment (bshepherdson) [reply src/metabase/query_processor/middleware/large_int_id.clj]: This actually got reverted anyway, due to a concurrent change in this file. It was no longer needed.

File: test/metabase/query_processor/middleware/add_dimension_projections_test.clj (hunk 4 above)
Comment (bshepherdson) [reply test/metabase/query_processor/middleware/add_dimension_projections_test.clj:546]: Good catch.

**Comment by jordanell** [comment]
Are there any plans to get this into an upcoming release? My team is desperately awaiting this on Metabase cloud to fix several issues we are having.
