### PR TITLE
Fix #23689: Sandboxed group managers can't see other users in the People tab

### LINKED ISSUE #23689: Sandboxed/Impersonated group managers can't see other users in the People tab
**Describe the bug**
A group manager that has sandboxed access to any database can't see other users in the People tab in the Admin panel.

As @calherries found:

One strange thing I noticed with the query is that if a group manager has sandboxed permissions, they can't see any other users in the group. Perhaps we should make a separate issue for this?

Below is an example query that runs to load users in a group on this page. Note the clause core_user.id = 272. That restriction is included in the query if the user has any sandboxed permissions on their account.

```
SELECT "core_user"."id", "core_user"."email", "core_user"."first_name", "core_user"."last_name", "core_user"."is_superuser", "core_user"."last_login"
FROM "core_user" RIGHT JOIN "permissions_group_membership" ON "core_user"."id" = "permissions_group_membership"."user_id"
WHERE ("is_active" = TRUE AND "core_user"."id" = 272 AND "permissions_group_membership"."group_id" = 162)
ORDER BY "core_user"."is_superuser" DESC, "is_group_manager" DESC, lower("last_name") ASC, lower("first_name")
```

**To Reproduce**
1. As an admin, go to the People tab, create a group, add at least 2 users, promote one of them to group manager and restrict their access to any database to a sandbox.
2. Log in as the group manager and access the people tab. You can't see the other group members besides yourself.

**Expected behavior**
The group manager should see every other instance user in the People/People tab and the users in their group in the People/Groups tab.

**Severity**
This makes group managers useless for sandboxed managers. But there shouldn't be a lot of sandboxed group managers.

**Additional context**
Related to #23246 

Not sure why we are restricting the people tab in the admin panel for sandboxed users, it may be wise to investigate why we are doing it.

### PR DESCRIPTION
**Pull request by calherries**
Fixes https://github.com/metabase/metabase/issues/23689.

Allows a group manager to manage members of a group, even if they're sandboxed on a table.
image

### CODE REVIEW

File: enterprise/backend/test/metabase_enterprise/sandbox/api/user_test.clj [hunk 1]
```diff
@@ -1,41 +1,3 @@
 (ns metabase-enterprise.sandbox.api.user-test
```
Comment (qnkhuat) [inline enterprise/backend/test/metabase_enterprise/sandbox/api/user_test.clj:1]: I think we could remove the whole file

**Review by qnkhuat — APPROVED** [review]
I think the changes make sense.

But I'd like to state the obvious: this restriction wasn't made because we want to limit Group Managers. 

In fact, this restriction exists before we have Group Managers, this was supposed to limit segmented-admin users to only see themselves when they call `GET /api/user`.
It's in our intention to remove this behavior right?

**Comment by calherries** [comment]
I thought so, but your comment about this feature predating group managers makes me want to double check my assumptions. I've commented on the issue to clarify [here](https://github.com/metabase/metabase/issues/23689#issuecomment-1180826074).
