### PR TITLE
Make sure we insert special segmented permission paths for sandboxed tables on downgrade to 49

### LINKED ISSUE #47082: Downgrading from 50 to 49 makes sandboxed tables not appear as sandboxed in permissions editor.
### Describe the bug

When sandboxing is configured in v50 of the app (first screenshot) then you downgrade to v49 via the CLI, it appears we lose sandboxing permissions (second screenshot)
image (3)
image (4)
Sandboxes are still enforced, but the UI makes it seem like it's not going to be. It appears the permissions graph sent to the client contains no sandboxing data. However, upgrading back to v50 shows sandbox data.

### To Reproduce

- On v50, set up a sandboxed table (I specifically use v50.20)
- Downgrade to v49 (I used v49.18)
- See that table is no longer set to sandboxed

### Expected behavior

Tables should remain sandboxed

### Logs

_No response_

### Information about your Metabase installation

```JSON
Multi-version issue. Using v50.20 and v49.18.
```

### Severity

likely to scare users, but ultimately annoying

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by noahmoss**
Fixes https://github.com/metabase/metabase/issues/47082

Adjusts permissions rollback to handle sandboxing better:
* If a table is sandboxed, we add a `/query/segmented/` permission path on the rollback so that it will be included properly in the permissions graph on 49
* If at least one table in a DB is sandboxed, and all the other tables are unrestricted, we need to add granular permission paths for the non-sandboxed tables.

### CODE REVIEW

**Comment by noahmoss** [comment]
* **#47085** <a href="https://app.graphite.dev/github/pr/metabase/metabase/47085?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @noahmoss and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: test/metabase/db/schema_migrations_test.clj [hunk 1]
```diff
@@ -2048,31 +2058,54 @@
...
+                                                                                        :created_at :%now
+                                                                                        :updated_at :%now
+                                                                                        :active     true}))
+              table-id-2 (first (t2/insert-returning-pks! (t2/table-name :model/Table) {:db_id      db-id
+                                                                                        :schema     "SchemaName"
+                                                                                        :name       "Table 2"
+                                                                                        :created_at :%now
+                                                                                        :updated_at :%now
+                                                                                        :active     true}))
+              group-id   (first (t2/insert-returning-pks! (t2/table-name :model/PermissionsGroup) {:name "Test Group"}))
```
Comment (escherize) [inline test/metabase/db/schema_migrations_test.clj:2079]: nit: could be `t2/insert-returning-pk!`

**Review by escherize — APPROVED** [review]
LGTM

**Review by johnswanson — APPROVED** [review]
