### PR TITLE
Return 5000 unique user attribute keys

### LINKED ISSUE #55647: Custom property won't appear for sandboxing when more than 1000 users
### Describe the bug

We only do a limit 1000 of core_user table when getting custom properties on /api/mt/user/attributes, and therefore you don't get the custom properties of user 1001 when configuring sandboxing

### To Reproduce

1) create 1000 users in Metabase with a custom property (let's say: name)
2) create an additional user, and add a custom property like "surname"
3) try to configure sandboxing with that new custom property, you can't

### Expected behavior

We should list all the custom properties

e.g. SELECT DISTINCT jsonb_object_keys(login_attributes::jsonb) AS key
FROM core_user;

### Logs

NA

### Information about your Metabase installation

```JSON
v53.x
```

### Severity

P1

### Additional context

It has always been like that

### PR DESCRIPTION
**Pull request by johnswanson**
Previously we looked at 1000 users and got the set of unique user attribute names from them. So if 1000 users each had a `name` and user 1001 had `some-other-attribute`, we would give you back `name` as the complete set of available attributes.

This modifies the magic number (to 5000 from 1000) and the logic. We select the first 5000 unique *attributes*. So if 1000 users each have a `name`, that only counts as 1, and we'll continue looking for other unique attributes before returning to the client.

Fixes https://github.com/metabase/metabase/issues/55647

### CODE REVIEW

File: enterprise/backend/src/metabase_enterprise/sandbox/api/user.clj [hunk 1]
```diff
@@ -28,17 +28,19 @@
...
-   ;; look at the `login_attributes` for the first 1000 users that have them set. Then make a set of the keys
-   (for [login-attributes (t2/select-fn-set :login_attributes :model/User :login_attributes [:not= nil] {:limit 1000})
-         :when (seq login-attributes)]
-     (set (keys login-attributes)))
-   ;; combine all the sets of attribute keys into a single set
-   (reduce set/union #{})))
+  (->> (t2/select-fn-set :login_attributes :model/User {:where [:and
+                                                                [:not= :login_attributes nil]
+                                                                [:not= :login_attributes "{}"]]})
+       (mapcat keys)
```
Comment (edpaget) [inline enterprise/backend/src/metabase_enterprise/sandbox/api/user.clj:40]: I think mapcat is not lazy, so am wondering if this chain cloud cause us to load a bunch db rows into memory if this table is particularly large? I ran into that in the analytics module.

If we do (map keys) (flatten) would that make sure we only realize enough rows from the db to satisfy the take?

Comment (johnswanson) [reply enterprise/backend/src/metabase_enterprise/sandbox/api/user.clj]: Actually, `mapcat` does seem to be lazy:

```
(type (mapcat identity (range 1000)))
;; => clojure.lang.LazySeq
```

So I decided to just make this lazier across the board using `t2/select-fn-reducible`

Comment (edpaget) [reply enterprise/backend/src/metabase_enterprise/sandbox/api/user.clj]: neat, had it in my head it was the same as `(apply concat (map fn` so was worried it was going to realize everything

**Review by edpaget — APPROVED** [review]
