### PR TITLE
Obey `start_of_week` day setting in filter label

### LINKED ISSUE #23142: Relative filter preview dates does not account for Start of Week setting
**Describe the bug**
Relative filter preview dates does not account for Start of Week setting. Confusing. The results are correct.

**To Reproduce**
1. Admin > Settings > Localization > First day of the week = Monday
2. _we don't have any current data, but this is a frontend issue, the correct data is filtered, so just open a filter "Past 1 week"_
image

**Information about your Metabase Installation:**
Only tested 0.43.2, since there were other problems previously with the relative preview.

### PR DESCRIPTION
**Pull request by gusaiani**
Fixes #23142

### How to Test

1. Admin > Settings > Localization > First day of the week = Monday
2. _we don't have any current data, but this is a frontend issue, the correct data is filtered, so just open a filter "Past 1 week"_

Weekdays displayed should start on Monday and end on Sunday

image

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/SpecificDatePicker.tsx [hunk 1]
```diff
@@ -27,7 +28,7 @@ type Props = {
 
 const SpecificDatePicker: React.FC<Props> = props => {
   const onChange = (
-    date?: string | moment.Moment,
+    date?: string | momentTimezone.Moment,
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/SpecificDatePicker.tsx:31]: I don't love types coming from `moment` and `moment-timezone`, but I suppose the libraries are like this. Moving everything to `moment-timezone` might be ill-advised, and a ton of work.

**Review by WiNloSt — APPROVED** [review]
Works great for me 👍

**Review by alxnddr — APPROVED** [review]
👍
