### PR TITLE
Properly handle SMTP Settings environment variables

### LINKED ISSUE #45445: "Send test email" button missing via Admin Email config page when email related env vars are set
### Describe the bug

I am not able to send a test email using the Metabase admin email page when the following environment variables are specified.

MB_EMAIL_FROM_ADDRESS
MB_EMAIL_FROM_NAME
MB_EMAIL_SMTP_HOST
MB_EMAIL_SMTP_PORT
MB_EMAIL_SMTP_SECURITY
MB_EMAIL_SMTP_PASSWORD
MB_EMAIL_SMTP_USERNAME

The issue remains even after going to the Metabase admin panel > Email > Edit configuration and filling the form with values as found in the env vars above.
Entering values:
image

After entering and saving values, a green success button is visible, however no send test email button.
image

### To Reproduce

1. Start Metabase container with the env vars populated like so:
MB_EMAIL_FROM_ADDRESS = from@yourdomain.com
MB_EMAIL_FROM_NAME = name@yourdomain.com
MB_EMAIL_SMTP_HOST = email-smtp.us-west-2.amazonaws.com
MB_EMAIL_SMTP_PORT = 2587
MB_EMAIL_SMTP_SECURITY = starttls
MB_EMAIL_SMTP_PASSWORD = youpassword
MB_EMAIL_SMTP_USERNAME = yourusername
2. Login to your metabase instance via UI
3. Navigate to admin section > settings > email
4. Edit SMTP configuration (values will be blank despite env vars)
5. Manually enter values in the form and save changes.

Note that the email will successfully send if a scheduled alert is present, so this confirms the configuration values are correct, it just isnt possible to trigger a test email adhoc and you must wait an hour or until the next scheduled alert.

### Expected behavior

How I think it should work:
EMAIL/SMTP configuration values can be set via env vars and in the Admin page the send test email should be available due to the existence of the env vars. If that isnt desired then at minimum I think that regardless of if the env vars are present you should be able to manually add in the form and trigger a test.

### Logs

No console logs were generated
No service log lines that are relevant

### Information about your Metabase installation

```JSON
- Chrome Version 126.0.6478.127 (Official Build) (arm64)
- MacOS : Sanoma 14.12
- Metabase Version: v0.50.11
- Metabase environment docker Image: metabase/metabase:v0.50.11
- Metabase database: RDS aurora postgres 16.2
```

### Severity

annoying - low

### Additional context

If I do not set the env vars mentioned above and go to the Email form and enter the values as I would have set for the env vars, I do get the sent email button.

### PR DESCRIPTION
**Pull request by iethree**
Closes https://github.com/metabase/metabase/issues/45445

### Description

The reported problem was that you can't send test emails from this form when all settings are set by environment variable. In reality there were a bunch of problems with this form.

1. Disabled inputs when SMTP settings are set by environment variable
2. Enabled the test button when one or more SMTP settings are set by environment variable
3. Updated validation to be sensitive to whether settings are set by environment variable
4. disabled `clear` button when all settings were set via environment variable.
5. Fixed the security type selection and update the setting options to match the type definitions elsewhere
6. Added unit tests for this component
7. Fixed a bunch of type mismatches, some of which caused errors.

Screen Shot 2024-07-30 at 2 58 39 PM

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

### CODE REVIEW

File: frontend/src/metabase-types/api/settings.ts [hunk 1]
```diff
@@ -201,7 +201,7 @@ interface InstanceSettings {
   "admin-email": string;
   "email-smtp-host": string | null;
   "email-smtp-port": number | null;
-  "email-smtp-security": "None" | "SSL" | "TLS" | "STARTTLS";
+  "email-smtp-security": "none" | "ssl" | "tls" | "starttls";
```
Comment (iethree) [inline frontend/src/metabase-types/api/settings.ts:204]: these values actually match what the backend expects, the previous values were display values

File: frontend/src/metabase-types/store/admin.ts [hunk 2]
```diff
@@ -37,6 +38,7 @@ export interface AdminState {
   };
   settings: {
     settings: SettingDefinition[];
+    warnings: Partial<Record<SettingKey, unknown>>;
```
Comment (iethree) [inline frontend/src/metabase-types/store/admin.ts:41]: I don't know what this does, but it's in the redux store 🤷

File: frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.tsx [hunk 3]
```diff
@@ -53,17 +54,33 @@ type FormValueProps = Pick<
...
-    .default(null),
-  "email-smtp-security": Yup.string(),
-  "email-smtp-username": Yup.string().default(""),
-  "email-smtp-password": Yup.string().default(""),
-});
+const anySchema = Yup.mixed().nullable().default(null);
+
+// we need to allow this form to be submitted even when we have removed certain inputs
+// when they are set by env vars
+const getFormValueSchema = (elementMap: _.Dictionary<SettingElement>) => {
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.tsx:61]: had to make this schema dynamically generated, because we don't know before runtime whether we should require values for fields that might be set by environment variable

File: frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.tsx [hunk 4]
```diff
@@ -80,11 +97,11 @@ export const SMTPConnectionForm = ({
 
   const initialValues = useMemo<FormValueProps>(
     () => ({
-      "email-smtp-host": settingValues["email-smtp-host"] || "",
+      "email-smtp-host": settingValues["email-smtp-host"],
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.tsx:100]: if we set a default value for this, it will bypass the required validation

File: frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.tsx [hunk 5]
```diff
@@ -136,107 +153,122 @@ export const SMTPConnectionForm = ({
...
   }, [dispatch, isHosted]);
 
+  const allSetByEnvVars = useMemo(() => {
+    return elements.every(element => element.is_env_setting);
+  }, [elements]);
+
   return (
     <Flex justify="space-between">
-      <Stack spacing="sm" maw={400} style={{ paddingInlineStart: "0.5rem" }}>
+      <Stack spacing="sm" maw={600} style={{ paddingInlineStart: "0.5rem" }}>
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.tsx:162]: this looked silly with the environment var component at 400 width

File: frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.unit.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,388 @@
...
+
+    const [emailApiCall] = fetchMock.calls();
+    const body = await emailApiCall?.request?.json();
+
+    expect(body).toEqual({
+      "email-smtp-host": "smtp.rotom.com",
+      "email-smtp-port": "123",
+      "email-smtp-security": "tls",
+      "email-smtp-username": "misty@example.com",
+      "email-smtp-password": "iheartpikachu",
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.unit.spec.tsx:267]: note to all the code secret scanners out there, these are not real credentials

File: frontend/src/metabase/admin/settings/selectors.js [hunk 7]
```diff
@@ -251,7 +251,12 @@ export const ADMIN_SETTINGS_SECTIONS = {
         display_name: t`SMTP Security`,
         description: null,
         type: "radio",
-        options: { none: "None", ssl: "SSL", tls: "TLS", starttls: "STARTTLS" },
+        options: [
+          { value: "none", name: "None" },
+          { value: "ssl", name: "SSL" },
+          { value: "tls", name: "TLS" },
+          { value: "starttls", name: "STARTTLS" },
+        ],
```
Comment (iethree) [inline frontend/src/metabase/admin/settings/selectors.js:259]: this format violated our types and was inconsistent with every other options key 🙄

File: frontend/src/metabase/admin/upsells/UpsellHosting.tsx [hunk 8]
```diff
@@ -27,7 +27,7 @@ export const UpsellHosting = ({ source }: { source: string }) => {
       maxWidth={UPSELL_CARD_WIDTH}
     >
       {jt`${(
-        <strong>{t`Migrate to Metabase Cloud`}</strong>
+        <strong key="migrate">{t`Migrate to Metabase Cloud`}</strong>
```
Comment (iethree) [inline frontend/src/metabase/admin/upsells/UpsellHosting.tsx:30]: this is unrelated, but threw up react key errors in my tests

File: frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.tsx [hunk 9]
```diff
@@ -53,17 +54,33 @@ type FormValueProps = Pick<
...
+      ? anySchema
+      : Yup.string().required(Errors.required).default(""),
+    "email-smtp-port": elementMap["email-smtp-port"].is_env_setting
+      ? anySchema
+      : Yup.number()
+          .positive()
+          .nullable()
+          .required(Errors.required)
+          .default(null),
+    "email-smtp-security": elementMap["email-smtp-security"].is_env_setting
```
Comment (rafpaf) [inline frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.tsx:73]: This is slightly outside your diff but I believe we need to give Yup localized error messages or it will use its own unlocalized ones

**Comment by rafpaf** [comment]
Might be nice to localize the error messages in `src/metabase/api/email.clj` if a backender can knock that out in a few minutes

**Review by rafpaf — APPROVED** [review]
Approved - see comments though
