### PR TITLE
Fix questions used in SQL query aren't linked correctly from variables sidebar

### LINKED ISSUE #16212: Questions used in SQL query aren't linked correctly from variables sidebar
image

The `Question #123` link points to `/questions` rather than `/questions/123`.

Workaround is easy but annoying: type the url manually.

### PR DESCRIPTION
**Pull request by kulyk**
Users can reference another question inside a SQL query like `{{ #4 }}`, where `4` is the question's ID. Native query editor has a sidebar displaying a list of referenced questions. The problem is we don't display correct links for them. E.g. a link to question with ID = 4 points to `/question`, however `/question-4` is expected

It's a regression appeared after implementing entity URL slugs (#15989)

Closes #16212

### To Verify

1. Create a native question like `select 1 as "a", 2 as "b"` and remember its ID. Let's say it's `4`
2. Create a new native question, paste `{{ #4 }}` inside the editor, and click "Visualize"
3. Click the "X" icon in the right part of the SQL editor
4. Click "Question #4"
5. You should be navigated to `/question/4` (with a slugified question name in the URL)

### Demo

https://user-images.githubusercontent.com/17258145/122422509-dffe6500-cf95-11eb-9dbd-cdb72141ee57.mov

### CODE REVIEW

File: frontend/src/metabase/query_builder/components/template_tags/CardTagEditor.jsx [hunk 1]
```diff
@@ -78,7 +78,9 @@ export default class CardTagEditor extends Component {
           {cardId == null ? (
             t`Question #…`
           ) : (
-            <Link to={questionUrl(cardId)}>{t`Question #${cardId}`}</Link>
+            <Link
+              to={Urls.question(question ? question : { id: cardId })}
+            >{t`Question #${cardId}`}</Link>
```
Comment (gusaiani) [inline frontend/src/metabase/query_builder/components/template_tags/CardTagEditor.jsx:83]: Wdyt of definining a function for this above `render`:

```js
  buildLinkToQuestion(question, cardId) {
    return Urls.question(question || { id: cardId });
  }
```

and then making the Link call a one-liner by calling the function:

```suggestion
         <Link to={this.buildLinkToQuestion(question, cardId)}>
              {t`Question #${cardId}`}
         </Link>
```

**Review by gusaiani — APPROVED** [review]
👍

One comment inlined.

File: frontend/src/metabase/query_builder/components/template_tags/CardTagEditor.jsx (hunk 1 above)
Comment (gusaiani) [reply frontend/src/metabase/query_builder/components/template_tags/CardTagEditor.jsx:83]: …maybe not even a function, just a constant set outside render may do the trick.

Comment (kulyk) [reply frontend/src/metabase/query_builder/components/template_tags/CardTagEditor.jsx]: Good point, thank you! Extracted a method for now. Defining a constant can be a bit confusing because there are cases when both `question` and `cardId` are undefined (during loading). That's why there is a `cardId == null` ternary above
