### PR TITLE
Custom expression: avoid circular reference

### LINKED ISSUE #21135: Custom Column with same names as existing table columns causes confusion in the Expression editor
**Describe the bug**
Custom Columns with same names as "real" table columns can cause confusion in the expression editor, when updating an expression, which then causes a StackOverflow, which is presented as a "No results", which is even more confusing.

**To Reproduce**
1. Question > Sample > Products
2. Custom Column `[Price] + 2` as "Price" (yes, the same name as the field) - press Done
image
3. Now open the custom column again, as if you were to adjust the expressions, but don't make any changes, just click Update
image
4. Visualize will show "No results", but the log has a stackoverflow

<details><summary>Full stacktrace</summary>

```
2022-03-21 16:39:25,478 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2022-03-21T16:39:24.252184+01:00[Europe/Copenhagen]",
 :json_query
 {:type "query",
  :query {:source-table 10, :expressions {:Price ["expression" "Price"]}},
  :database 4,
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class java.lang.StackOverflowError,
 :stacktrace
 ["schema.spec.leaf.LeafSpec$fn__2536.invoke(leaf.clj:13)"
  "schema.spec.variant.VariantSpec$fn__2588.invoke(variant.clj:53)"
  "schema.spec.variant$option_step$fn__2563.invoke(variant.clj:35)"
  "schema.spec.variant.VariantSpec$fn__2592.invoke(variant.clj:59)"
  "schema.spec.collection$element_transformer$fn__2626$fn__2627.invoke(collection.clj:36)"
  "schema.core$fn__3648$fn__3658$fn__3659.invoke(core.clj:959)"
  "schema.spec.collection$element_transformer$fn__2626.invoke(collection.clj:36)"
  "schema.spec.collection$element_transformer$fn__2626.invoke(collection.clj:36)"
  "schema.spec.collection.CollectionSpec$fn__2658.invoke(collection.clj:79)"
  "schema.spec.variant$option_step$fn__2557.invoke(variant.clj:28)"
  "schema.spec.variant.VariantSpec$fn__2592.invoke(variant.clj:59)"
  "schema.spec.variant$option_step$fn__2563.invoke(variant.clj:35)"
  "schema.spec.variant.VariantSpec$fn__2592.invoke(variant.clj:59)"
  "schema.spec.variant.VariantSpec$fn__2592.invoke(variant.clj:59)"
  "schema.spec.variant$option_step$fn__2557.invoke(variant.clj:28)"
  "schema.spec.variant$option_step$fn__2557.invoke(variant.clj:31)"
  "schema.spec.variant$option_step$fn__2557.invoke(variant.clj:31)"
  "schema.spec.variant$option_step$fn__2557.invoke(variant.clj:31)"
  "schema.spec.variant.VariantSpec$fn__2592.invoke(variant.clj:59)"
  "clojure.core$comp$fn__5825.invoke(core.clj:2573)"
  "--> mbql.util$fn__26434$expression_with_name__26439.invoke(util.cljc:341)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"
  "driver.sql.query_processor$fn__43860.invoke(query_processor.clj:300)"
  "driver.sql.query_processor$fn__43860.invokeStatic(query_processor.clj:302)"],
 :card_id nil,
 :context :ad-hoc,
 :error nil,
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:type :query,
  :query
  {:source-table 10,
   :expressions {:Price [:expression "Price"]},
   :fields
   [[:field 105 nil]
    [:field 102 nil]
    [:field 106 nil]
    [:field 107 nil]
    [:field 109 nil]
    [:field 104 nil]
    [:field 103 nil]
    [:field 108 {:temporal-unit :default}]
    [:expression "Price"]],
   :limit 2000},
  :database 4,
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
  :info
  {:executed-by 1,
   :context :ad-hoc,
   :nested? false,
   :query-hash
   [29, -33, -115, 34, 74, -10, -116, 47, -127, 10, 35, -111, 108, 109, 13, 59, 56, 5, -113, -105, 93, -43, -73, -41,
    18, 9, 99, -30, 73, -127, -114, -119]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000}},
 :data {:rows [], :cols []}}

2022-03-21 16:39:25,483 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.3 s (18 DB calls) App DB connections: 0/13 Jetty threads: 3/50 (4 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
```

</details>

**Expected behavior**
In a perfect world, it would know which field was written and not automatically change that, when reopening the editor.
Think this is a difficult issue to fix, but I triggered this so many times during #21131 and thought I was seeing other problems.

**Information about your Metabase Installation:**
Tested 0.41.6 thru 0.42.2 and master

### PR DESCRIPTION
**Pull request by ariya**
Fixed #21135.

To verify:
1. New, Question, Sample Database, Products
2. Custom column, type `[Price] + 2` and name it as `Price`, press Done
3. Click on that custom column again, don't change anything, press Update
4. Preview

### Before this PR

The front-end tries to resolve `[Price]` dimension to itself (instead of the field in the Products table), leading to an expression with a circular reference. This confuses the back-end (rightfully).

image

### After this PR

Now the front-end will avoid resolving any dimension with the same name to itself. The query/preview works as expected.

image

### CODE REVIEW

File: frontend/src/metabase/lib/expressions/diagnostics.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ export function countMatchingParentheses(tokens) {
   return tokens.reduce(count, 0);
 }
 
-export function diagnose(source, startRule, query) {
+export function diagnose(source, startRule, query, name = null) {
```
Comment (akiselev) [inline frontend/src/metabase/lib/expressions/diagnostics.js:37]: This inconsistency with how we pass arguments is a bit disconcerting. Maybe we should move the arguments into a single object arg?

**Review by akiselev — APPROVED** [review]
Minor nitpick about arguments but otherwise, this works and looks great!

File: frontend/src/metabase/lib/expressions/diagnostics.js (hunk 1 above)
Comment (ariya) [reply frontend/src/metabase/lib/expressions/diagnostics.js:37]: The idea is to convey that `name` is indeed optional (e.g. there is no associated name for the custom expression for the filter, but there is one for a custom column).
What's a good alternative?
