### PR TITLE
Fix #14035: waterfall issue with explicit time zone

### LINKED ISSUE #14035: Waterfall error with time series data with an explicit timezone
**Describe the bug**

When setting the timezone explicitly, waterfall chart doesn't get rendered.

**Logs**

```
CardRenderer.jsx:112 TypeError: warn is not a function
    at getTimezone (timeseries.js:237)
    at getXInterval (renderer_utils.js:301)
    at xValueForWaterfallTotal (renderer_utils.js:328)
    at getXAxisProps (LineAreaBarRenderer.js:115)
    at lineAreaBar (LineAreaBarRenderer.js:821)
    at Object.waterfallRenderer [as renderer] (LineAreaBarRenderer.js:936)
    at CardRenderer.renderChart (CardRenderer.jsx:107)
    at CardRenderer.componentDidUpdate (CardRenderer.jsx:60)
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponent.js:726
```

**To Reproduce**

Before launching Metabase, set `MB_REPORT_TIMEZONE` to "US/Pacific"`.

1. Ask a question, Simple question
2. Choose Sample Dataset, Orders table
3. Summarize, Group by Created At
4. Visualization, Waterfall

**Expected behavior**

Waterfall chart is displayed.

**Actual behavior**

The chart section is empty. Upon inspecting using Dev Tools, there are JavaScript errors (as mentioned above).

image

### PR DESCRIPTION
**Pull request by ariya**
See for ##14035 for more details and how to verify the fix.

### CODE REVIEW

File: frontend/src/metabase/visualizations/lib/renderer_utils.js [hunk 1]
```diff
@@ -323,7 +323,7 @@ export function getXInterval({ settings, series }, xValues, warn) {
 
 export function xValueForWaterfallTotal({ settings, series }) {
   const xValues = getXValues({ settings, series });
-  const xInterval = getXInterval({ settings, series }, xValues);
+  const xInterval = getXInterval({ settings, series }, xValues, () => {});
```
Comment (ariya) [inline frontend/src/metabase/visualizations/lib/renderer_utils.js:326]: The last argument is for the `warn` function and IMO, it's not needed at all for computing this total's X value.

Comment (paulrosenzweig) [reply frontend/src/metabase/visualizations/lib/renderer_utils.js:326]: Yeah that's fair. We would have already called `warn` if there's an issues.

Maybe needing to pass the no-op warn function is a sign we either split out the "warning" from `getXInterval` or pass the results of `getXInterval` into `xValueForWaterfallTotal`. Those both are messy and out of scope here though.

**Review by paulrosenzweig — APPROVED** [review]
Nice find!
